### ISSUE TITLE
Manage AIT environment logs independently

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10006]
Right now our AIT build a docker environment before running the tests themselves. If there is an error in the first test, where the docker image is built, all the docker logs will be added to the report.

To keep the test reports clean we should capture the docker output in a different file and make it accessible on higher testing automation levels in case this process fails.

**Comment by davidjiglesias** [comment]
Maybe we should add this environment logs to the report no matter the result.

**Comment by Kondent** [comment]
## Update
I've working with this issue today and found out a fix. Will do more tests to check if everything is going well.

Regards,
Alexis
