### ISSUE TITLE
24 hours logs on seprate wazuh server

### ISSUE THREAD

**Issue by sulaiman35** [wazuh/wazuh#1001]
Dear team,

Recently I get a request from my management that I have to create another wazuh server where I have to keep only 24hours logs for qa and other team.

For now I have setup elasticsearch and logstash, and I am willing to copy logs from already wazuh server (alerts and archive) logs.

But I am not able to complete this using rsyslog so far, can you please help me with this if possible.

**Comment by crolopez** [comment]
Hi @sulaiman35,

Wazuh can perform daily log rotations, which are compressed. You can use these rotated logs to know when the logs are 24 hours old and delete them with an external tool or script.

If this doesn't answer your question, can you specify it?

Best regards.
