### ISSUE TITLE
Issue with Email alert

### ISSUE THREAD

**Issue by killmasta93** [wazuh/wazuh#10014]
Hi
I was wondering if someone else has had this issue before,
Currently i have WAZUH working fine with email alerts all of a sudden it stopped working, 
I checked the alerts.json and see that it shows the alerts to send the email 

`{"timestamp":"2021-09-08T00:10:55.008-0500","rule":{"level":12,"description":"sshd: authentication success.","id":"5715","mitre":{"id":["T1078","T1021"],"tactic":["Defense Evasion","Initial Access","Persistence","Privilege Escalation","Lateral Movement"],"technique":["Valid Accounts","Remote Services"]},"firedtimes":3,"mail":true,"groups":["local","syslog","sshd","authentication_success"],"pci_dss":["10.2.5"],"gpg13":["7.1","7.2"],"gdpr":["IV_32.2"],"hipaa":["164.312.b"],"nist_800_53":["AU.14","AC.7"],"tsc":["CC6.8","CC7.2","CC7.3"]},"agent":{"id":"000","name":"wazuh"},"manager":{"name":"wazuh"},"id":"1631077855.758920","full_log":"Sep  8 00:10:54 wazuh sshd[3706]: Accepted password for root from 192.168.100.2 port 39102 ssh2","predecoder":{"program_name":"sshd","timestamp":"Sep  8 00:10:54","hostname":"wazuh"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"192.168.100.2","dstuser":"root"},"location":"/var/log/auth.log"}`

i thought it was an issue of the email but i ran 

`echo "Hi! We are testing Postfix!" | mail -s "Test Postfix" alerts@domain.com`

and it works so not an email issue either so not sure if wazuh has another service that sends the email?

Thank you

**Comment by DProvinciani** [comment]
Hi @killmasta93 , let's troubleshoot this issue so we can make the email alerts work again.

First of all, is good to mention that Wazuh has a whole implementation in the source code to send the emails. This results in a daemon called [wazuh-maild](https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-maild.html) in charge of sending the alerts by email.

Having said that, could you check in the `/var/ossec/logs/ossec.log` file whether is an error or failure reported by `wazuh-maild`?

On the other hand, did you change any configuration in the host that could affect the network access of the Wazuh daemons?

I'll be waiting for your answer. Thanks!

**Comment by killmasta93** [comment]
im very sorry for the late reply, i did not get the notification, after troubleshooting it was an issue with my email server
