### ISSUE TITLE
[Feed]: Results stress tests 30min

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh#10019]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.1 | Feed | Report |

## Description

This issue is a report of the Stress tests for 4 hours launched in Jenkins:

- Without using CDB list: https://ci.wazuh.info/view/Tests/job/Test_stress/2409/
- With CDB list loaded in manager: https://ci.wazuh.info/view/Tests/job/Test_stress/2410/

Aiming to determine if the `ip_reputation_v2` list is too heavy to be included in manager compared with another manager without the list but with the same amount of events.

**Comment by JavierBejMen** [comment]
## Update
Results indicate that performance impact is negligible for a 30 minutes run:

### Analysisd events and alerts

![Test_stress_B2409_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/32262972/133062370-7292561b-685d-4613-97b6-3a9eeb471657.png)


![Test_stress_B2410_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/32262972/133062452-88ad0eb8-edd7-4c43-8604-c7aa047b69a6.png)

We can see that the number of events is as expected in both tests, and on 2410 approximately generates alerts from half the events received.

### VMS

![monitor-manager-Test_stress_B2409_manager-live_VMS](https://user-images.githubusercontent.com/32262972/133062974-8e3ab891-db7f-4313-97a6-c38baf678bba.png)

![monitor-manager-Test_stress_B2410_manager-live_VMS](https://user-images.githubusercontent.com/32262972/133062924-03292b10-f44f-469e-8211-0e6eac0dabf5.png)

Memory footprint it's even lesser when using the cdb, we can conclude that differences are negligible.
