### ISSUE TITLE
how to build wazuh-manager RPM with mysql output enabled

### ISSUE THREAD

**Issue by w1306349125** [wazuh/wazuh#10017]
Is there any way to build wazuh-manager rpm with support for mysql?
I've read documents, but it only tell how to install with install.sh or how to make normal wazuh-manager rpm which not enable mysql output.
Thanks

**Comment by vikman90** [comment]
Hi @w1306349125,

According to the documentation ([Configuring database output](https://documentation.wazuh.com/current/user-manual/manager/manual-database-output.html)) we only support MySQL by building the manager manually.

So, if we want to build a RPM package that natively supports MySQL, I guess we need to:

1. Install the C connector development package for MySQL.

Add `mysql-devel` to the package list ([Dockerfile](https://github.com/wazuh/wazuh-packages/blob/153d3beba3cebad163ac51ef83fbe09543b950fe/rpms/CentOS/7/aarch64/Dockerfile#L25)).

2. Build Wazuh Manager with MySQL support.

Add the flag `DATABASE=mysql` to the `make` command ([wazuh-manager-4.3.0.spec](https://github.com/wazuh/wazuh-packages/blob/153d3beba3cebad163ac51ef83fbe09543b950fe/rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec#L42)).
```sh
make -j%{_threads} TARGET=server USE_SELINUX=yes DEBUG=%{_debugenabled} DATABASE=mysql
```

3. Declare the dependency on the MySQL library.

Add "mysql-libs" to the list of requirements ([wazuh-manager-4.3.0.spec](https://github.com/wazuh/wazuh-packages/blob/153d3beba3cebad163ac51ef83fbe09543b950fe/rpms/SPECS/4.3.0/wazuh-manager-4.3.0.spec#L20)).
```
Requires: coreutils mysql-libs
```

I think these are the changes required to build a package with MySQL support.

Hope it helps.
Best regards.
