### ISSUE TITLE
Windows active response executables netsh.exe and route-null.exe incompatible with Windows Eventchannel 

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#10022]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.1 | active-response | Agent | n/a | Windows |

On Windows agents, the included active response executables only accept data.srcip as input.  Thus any Windows ARs triggered by an event from a Windows agent will not fire at all.  For example a bruteforce RDP attack on a Windows system could not be made to trigger the netsh.exe AR to block the attacker.

All of Wazuh's Windows ARs that act on a source IP address need to expect the source IP to be found in data.win.eventdata.ipAddress and if not present then in data.srcip which would still need to work for some special cases.

This needs to be fixed as soon as possible.  It literally cripples all but corner-case uses of Windows AR.

The function that needs to be fixed is [here](https://github.com/wazuh/wazuh/blob/886c8cc33fe7200901f38fc3b1a49ec551ab4727/src/active-response/active_responses.c#L212).

Kevin

**Comment by Nicogp** [comment]
Hello Team, 
I have reopened this issue because it has been reported to us through a `community `that Windows events obtained through the `sysmon channel` contain the `ip` in `data.win.eventdata.destinationIp`, it would be important to support that `AR` also looks in that location.
Sample event:
```
"eventdata": {
          "destinationPort": "443",
          "image": "C:\\\\Windows\\\\System32\\\\WindowsPowerShell\\\\v1.0\\\\powershell.exe",
          "sourcePort": "64239",
          "initiated": "true",
          "destinationIp": "IP-attacker",
          "protocol": "tcp",
          "processGuid": "{171c60a3-228d-6157-3f6e-7d3300000000}",
          "sourceIp": "My-IP",
          "processId": "29460",
          "utcTime": "2021-10-01 15:00:31.991",
          "ruleName": "technique_id=T1059.001,technique_name=PowerShell",
          "destinationIsIpv6": "false",
          "user": "NT AUTHORITY\\\\SYSTEM",
          "sourceIsIpv6": "false"
```

**Comment by branchnetconsulting** [comment]
Very good thought but note that for a given sysmon event, either source or dest IP could be the non-local ip address you would want to block.  Sysmon network events can be thrown on outbound or inbound connections.  Perhaps we could made netsh.exe accept an optional extra_args string value of "src" ot "dst" so if set to "dst" the dest ip would be targeted instead of the default src ip.  Or just allow extra_args to specify the exact field name to target.  An extra command section could then be added for a dest-ip use of netsh.
