### ISSUE TITLE
Improve the configuration options for Authd during agents replacement in CICD repositories

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#10047]
### Description

As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. This is a tracking purposes issue to reflect all the work that should be done in the next set of repositories.

- https://github.com/wazuh/wazuh-jenkins/issues/2937
- https://github.com/wazuh/wazuh-cloudformation/issues/90
- https://github.com/wazuh/wazuh-puppet/issues/386
- https://github.com/wazuh/wazuh-chef/issues/136
- https://github.com/wazuh/wazuh-ansible/issues/625
- https://github.com/wazuh/wazuh-kubernetes/issues/177

**Comment by alberpilot** [comment]
Hello @DProvinciani 
 Please consider closing this issue. 

Regards, 
Alberto R

**Comment by DProvinciani** [comment]
As all the linked issues were completed and closed. Closing this issue.
