### ISSUE TITLE
Release 4.2.2 - Release Candidate 1 - Footprint metrics - macOS/Solaris11-i386 -ALL (4H)

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#10078]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #9983 |
| **Main footprint metrics issue** | #9947 |
| **Version** | 4.2.2                                     |
| **Release candidate #** | RC1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.2-rc1
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: https://ci.wazuh.info/job/Test_stress/---

<details><summary>Stress scripts used</summary>

</details>
<details><summary>Stress configuration</summary>

</details>

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
  

   </details>
+ <details><summary>Logs and configuration</summary>

  

   </details>
+ <details><summary>CSV</summary>

 

   </details>
</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>
 
  

   </details>
+ <details><summary>Logs and configuration</summary>

 

   </details>
+ <details><summary>CSV</summary>

 

   </details>
</details>

**Comment by rauldpm** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | https://github.com/wazuh/wazuh/issues/9983                                         |
| **Main footprint metrics issue #** | https://github.com/wazuh/wazuh/issues/9947                                         |
| **Version** | 4.2.2                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.2.2-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://devel.ci.wazuh.info/view/Tests/job/Test-Stress-Vagrant-cbordon/81/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/133128129-b81fa6c1-6fa9-4804-893c-aa2ead0f8780.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/133128130-5b1749bd-da48-4011-a5a0-cb4fa841e621.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/133128131-4244bec5-16b2-46b4-aea1-953c6208f096.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/133128136-9cb093f0-86a5-44c0-ae25-e1b5a84117a4.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/133128137-4fcac7a2-c3bb-48c6-8840-e72ceb2fbbb2.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_PSS](https://user-images.githubusercontent.com/14913942/133128139-9e2979ad-ed72-4726-9b69-14ae3ecad6f5.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/133128141-f9f1d7c3-e1d8-4431-84bd-9a4cc73659ff.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/133128143-460a273b-5c38-4317-abd8-e82daa4fe17f.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/133128144-a922224c-387c-4998-bc23-8c3b3d592aa9.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/133128146-359bbe52-8f6e-47cd-bd46-ad4d27cd0237.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_USS](https://user-images.githubusercontent.com/14913942/133128147-fd62f016-66fe-497a-a3c4-d099e3a804c3.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_VMS](https://user-images.githubusercontent.com/14913942/133128149-9b976909-b86c-403e-82cb-8c51b16d6c10.png)
![monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/133128150-bd84d347-dfb8-4b5a-a9d1-80198b54ffe0.png)
![Test-Stress-Vagrant-cbordon_B81_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/14913942/133128151-8c0b950b-51ad-47a7-81e8-fcb75b210afb.png)
![Test-Stress-Vagrant-cbordon_B81_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/14913942/133128152-e8694739-e709-4699-bd68-e96c439b992d.png)
![Test-Stress-Vagrant-cbordon_B81_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/14913942/133128154-4d1818d2-746e-4f58-a289-560cc1b92ba0.png)



    </details>
+ <details><summary>Logs and configuration</summary>


    [ossec_Test-Stress-Vagrant-cbordon_B81_manager_2021-09-13.zip](https://github.com/wazuh/wazuh/files/7156209/ossec_Test-Stress-Vagrant-cbordon_B81_manager_2021-09-13.zip)


    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release.csv](https://github.com/wazuh/wazuh/files/7156211/monitor-manager-Test-Stress-Vagrant-cbordon_B81_manager-pre-release.csv)
[Test-Stress-Vagrant-cbordon_B81_manager_analysisd_state.csv](https://github.com/wazuh/wazuh/files/7156212/Test-Stress-Vagrant-cbordon_B81_manager_analysisd_state.csv)
[Test-Stress-Vagrant-cbordon_B81_manager_remoted_state.csv](https://github.com/wazuh/wazuh/files/7156213/Test-Stress-Vagrant-cbordon_B81_manager_remoted_state.csv)


    </details>

</details>

<details><summary>Macos agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_CPU](https://user-images.githubusercontent.com/14913942/133128239-4c694025-730a-460d-b7e7-e3fdcbfd5046.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/133128244-0a02f915-950e-455f-945c-8c085574eefa.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/133128245-1e4a03b3-7c7e-48f0-9abe-474d185ff560.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_Disk](https://user-images.githubusercontent.com/14913942/133128246-80df89c3-f720-477d-bd16-45454a50efe2.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_FD](https://user-images.githubusercontent.com/14913942/133128249-81798951-1e6e-4320-aa55-858d60f2dd82.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/133128250-590f0eb4-42f3-4cdd-98b5-c12d75fc44c6.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/133128251-5ad43793-e15f-4317-8e8d-dd4231f08dac.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_RSS](https://user-images.githubusercontent.com/14913942/133128254-c4c9d7fe-3622-439b-b04d-1a17a649d294.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_USS](https://user-images.githubusercontent.com/14913942/133128255-ddc46839-f0d9-42a2-9bfb-96a95c1b27db.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_VMS](https://user-images.githubusercontent.com/14913942/133128257-ffb1c4b7-4f95-4a25-8854-4298cfa93c7b.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/133128258-d7ae9dc1-332c-41c0-834b-12a4ac110505.png)
![Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/133128259-8a47f159-6eca-41b4-8957-f867d9c5567d.png)
![Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/133128261-4373d530-ce61-4650-a5e1-9927639e354b.png)
![Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/133128263-48e57896-8976-4374-a40a-f1ca54d142e5.png)
![Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/133128264-25a6868a-6703-4c84-8528-1c2fc49a76d4.png)



    </details>
+ <details><summary>Logs and configuration</summary>

 
    [ossec_Test-Stress-Vagrant-cbordon_B81_macos_agent_2021-09-13.zip](https://github.com/wazuh/wazuh/files/7156217/ossec_Test-Stress-Vagrant-cbordon_B81_macos_agent_2021-09-13.zip)



    </details>
+ <details><summary>CSV</summary>


    [monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release.csv](https://github.com/wazuh/wazuh/files/7156219/monitor-agent-Test-Stress-Vagrant-cbordon_B81_macos_agent-pre-release.csv)
[Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state.csv](https://github.com/wazuh/wazuh/files/7156220/Test-Stress-Vagrant-cbordon_B81_macos_agent_agentd_state.csv)


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_CPU](https://user-images.githubusercontent.com/14913942/133128332-008e5f7d-c4d6-474a-ae36-5987383efce0.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/133128337-3a701d66-910d-4a01-8d5f-4f94ade49b22.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/133128340-4b79bfb2-aeae-4fa5-aef2-e35612d8a81e.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_Disk](https://user-images.githubusercontent.com/14913942/133128342-66e27124-a721-4bb3-b086-1ac3a5ad9bd0.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_FD](https://user-images.githubusercontent.com/14913942/133128345-57d69350-34fd-4992-8ab4-272b63b6fc40.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/133128347-85de0de8-8243-42a2-b72a-876624ce587b.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/133128349-debcfdd2-a11e-4657-bb4d-d0712a74ea31.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_RSS](https://user-images.githubusercontent.com/14913942/133128352-3f571f33-218e-42b0-950a-ff2946bccd33.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_USS](https://user-images.githubusercontent.com/14913942/133128355-57eebc85-7f34-4da0-bb56-a334e002446e.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_VMS](https://user-images.githubusercontent.com/14913942/133128358-bd32c9f0-e005-423b-acf5-d753c05db713.png)
![monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/133128361-1ebc09e6-7aaa-4f93-b634-bb1f98ab1359.png)
![Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/133128363-6dfe093d-7961-4c6a-86f4-85d40b1e8a29.png)
![Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/133128365-e0db24f2-6f3d-4636-bf09-9dfe64b52a9e.png)
![Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/133128366-bad47f8b-1303-4d11-92dd-5234320273f0.png)
![Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/133128369-9ba72b45-87a0-42e4-8ed5-9d4688d4b8d9.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test-Stress-Vagrant-cbordon_B81_solaris_agent_2021-09-13.zip](https://github.com/wazuh/wazuh/files/7156222/ossec_Test-Stress-Vagrant-cbordon_B81_solaris_agent_2021-09-13.zip)


    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release.csv](https://github.com/wazuh/wazuh/files/7156223/monitor-agent-Test-Stress-Vagrant-cbordon_B81_solaris_agent-pre-release.csv)
[Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state.csv](https://github.com/wazuh/wazuh/files/7156224/Test-Stress-Vagrant-cbordon_B81_solaris_agent_agentd_state.csv)



    </details>

</details>
