### ISSUE TITLE
C++ design for FIM

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#10099]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|[9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) | FIMDB | Manager/Agent | Packages/Sources | All |

Hi team!

With the changes that are going to be introduced in https://github.com/wazuh/wazuh/issues/9103, we are going to move the FIM DB implementation to c++.

This issue aims to collect the design phase and create the needed diagrams to start the development.
The list with the diagrams to create may increase.

- [x] Class diagram
- [x] Sequence diagram

**Comment by antoniomanuelfr** [comment]
We have been discussing how to implement the new DB. We have come out with the following class diagram:
![FIMDB_class-Page-2 drawio](https://user-images.githubusercontent.com/22987701/133105473-0c8bc05a-56e7-4791-a737-48c58c550416.png)

This diagram may be changed in the future, as this is the first iteration of this process

**Comment by antoniomanuelfr** [comment]
As well as the class diagram, we have been designing the following sequence diagram:
```puml
@startuml
' Copyright (C) 2015-2021, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2



database "<agent-id>.db" as agent.db
actor "wazuh-manager" as manager
participant syscheck_agent as fim
participant os as os
participant rsync
participant dbsync
database fim.db as fdb

activate fim

fim -> dbsync ++: reset DB
dbsync -> fdb -- : reset


loop scan (each ""frequency"" seconds)
    group for each [directory]
        fim -> os ++: get_file_data
        fim <-- os --: info
        fim -> dbsync++ : update DB with new file data
        dbsync -> fdb : save data DB
        dbsync <-- fdb
        fim <-- dbsync
        manager <- fim ++: send fim event
        manager --> fim
     end group
        dbsync--
end loop
        agent.db <- manager++: update db
        agent.db --> manager --

... sync databases ...

loop every ""sync frequency"" seconds


    
    fim -> rsync++ : get sync data
    rsync -> dbsync++ : get DB data
    dbsync -> fdb : get data
    dbsync <-- fdb
    rsync <-- dbsync-- : DB data
    rsync -> rsync : build sync data
    rsync --> fim --: sync data 
    fim --> manager : send sync data
    manager -> agent.db: update DB
end loop
@enduml
```
![image](https://user-images.githubusercontent.com/22987701/133105682-e1302a94-60d8-49a7-99d0-17e46a43e255.png)

**Comment by FrancoRivero** [comment]
Registries:
General method:
	*Remove: 
		- fim_db_remove_registry_key(fdb_t *, fim_entry) 
		- fim_db_remove_registry_value_data(fdb_t *, fim_registry_value_data)
	*Set:
		- fim_db_set_all_registry_data_unscanned(fdb_t *) 
		- fim_db_set_all_registry_key_unscanned(fdb_t *)
		- fim_db_set_registry_key_scanned(fdb_t *, const char *, unsigned int)
		  fim_db_set_registry_data_scanned(fdb_t *, const char *, unsigned int)
	*Get:
		- fim_db_get_registry_keys_not_scanned(fdb_t *, fim_tmp_file **, int)
		  fim_db_get_registry_data_not_scanned(fdb_t *, fim_tmp_file **, int)
		- fim_db_get_count_registry_key(fdb_t *)
		  fim_db_get_count_registry_data(fdb_t *)
		- fim_db_get_registry_key_rowid(fdb_t *, const char *, unsigned int, unsigned int *)
		- fim_db_get_registry_key(fdb_t *, const char *, unsigned int)
		- fim_db_get_registry_key_using_id(fdb_t *, unsigned int)
	*Decode:  
		- fim_db_decode_registry_key(sqlite3_stmt *)
		- fim_db_decode_registry_value(sqlite3_stmt *)
		- _fim_db_decode_registry_value(sqlite3_stmt *, int)
		- fim_db_decode_registry(int, sqlite3_stmt *)
	*Insert:
		- fim_db_insert_registry_data(fdb_t *, fim_registry_value_data *, unsigned int, unsigned int)
	  	  fim_db_insert_registry_key(fdb_t *, fim_registry_key *, unsigned int)
		- fim_db_insert_registry(fdb_t *, fim_entry *)

Particular methods:
- fim_db_callback_save_reg_data_name(__attribute__((unused))fdb_t *, fim_entry *, int, void *)
- fim_db_process_read_registry_data_file(fdb_t *, fim_tmp_file *, pthread_mutex_t *,
                   			  void (*callback)(fdb_t *, fim_entry *, pthread_mutex_t *, void *, void *, void *), int , void *, void *, void *) 
- fim_db_get_values_from_registry_key(fdb_t *, fim_tmp_file **, int, unsigned long int)



*Files:*
General methods:
	*Remove:
		- fim_db_remove_path(fdb_t *, const char *)
		- fim_db_remove_validated_path(fdb_t *, fim_entry *,pthread_mutex_t *, void *, void *, void *)
		- fim_db_delete_range(fdb_t *, fim_tmp_file *, pthread_mutex_t *, int, fim_event_mode, int *)
		- fim_db_delete_not_scanned(fdb_t *, fim_tmp_file *, pthread_mutex_t *, int)
	*Set:
		- fim_db_set_all_unscanned(fdb_t *)
		- fim_db_set_scanned(fdb_t *, const char *)
	*Get:
		- fim_db_get_not_scanned(fdb_t *, fim_tmp_file **, int)
		- fim_db_get_count_file_data(fdb_t *), fim_db_get_count_file_entry(fdb_t *)
		- fim_db_get_path(fdb_t *, const char *)
		- fim_db_get_paths_from_inode(fdb_t *, unsigned long int, unsigned long int)
		- fim_db_get_path_from_pattern(fdb_t *, const char *, fim_tmp_file **, int)
	*Decode:
		- fim_db_decode_full_row(sqlite3_stmt *)
	*Insert:
		- fim_db_insert_data(fdb_t *, const fim_file_data *, int *)
  		  fim_db_insert_path(fdb_t *, const char *, const fim_file_data *, int)
		- fim_db_insert(fdb_t *, const char *, const fim_file_data *, const fim_file_data *)


Particular methods:
- fim_db_process_missing_entry(fdb_t *, fim_tmp_file *, pthread_mutex_t *, int, fim_event_mode, whodata_evt *)
- fim_db_append_paths_from_inode(fdb_t *, unsigned long int, unsigned long int, OSList *, rb_tree *)
- fim_db_data_exists(fdb_t *, unsigned long int, unsigned long int)
- fim_db_file_is_scanned(fdb_t *, const char *)

**Comment by FrancoRivero** [comment]
![db_class](https://user-images.githubusercontent.com/11745030/134018782-11aa374f-d02a-4e30-9757-cb341b3195ab.png)
Add a first iteration of a possible design for FIM DB module
