### ISSUE TITLE
OSSEC Windows Agent fails to extract data from some eventchannel events.

### ISSUE THREAD

**Issue by gjahchan** [wazuh/wazuh#101]
This following is only _one_ example:

![screenshot - 2017-04-11 08_00_16](https://cloud.githubusercontent.com/assets/22189754/24893535/f7cf165c-1e8c-11e7-8c5f-a7e542be793c.png)

Other than the usual header information, only the fields within the blue rectangles are picked up in the forwarded event. The Security ID is translated into Domain & Account Name. The fields in the red rectangles which contain _critical_ information are not parsed or forwarded.

Following is what the OSSEC Agent forwards to the OSSEC server:

2017 Apr 11 07:24:30 WinEvtLog: Microsoft-Windows-AppLocker/EXE and DLL: INFORMATION(8002): Microsoft-Windows-AppLocker: XXXXXX: XXXXXX: Xxxxxxx: %PROGRAMFILES%\GOOGLE\CHROME\APPLICATION\CHROME.EXE was allowed to run.

The PolicyName, RuleId, RuleName, RuleSddl, TargetUser, TargetProcessId, FileHash, Fqbn and TargetLogonId are missing. TargetLogonId is decimal, whereas everywhere else Windows logs it as a Hex number. Go figure why!

**Comment by leotant** [comment]
Hi @gjahchan. Where do you find the log depicted in your picture?

**Comment by gjahchan** [comment]
You need to enable Windows AppLocker on a version of Windows that supports it (Vista or later).

Then open EventViewer, and go to:

Applications and Services Logs -> Microsoft -> Windows -> AppLocker -> EXE and DLL.

![image](https://cloud.githubusercontent.com/assets/22189754/26234965/dbf577d0-3c70-11e7-8d0d-67a3e63d99f2.png)

Select an event, in the bottom pane showing the event detail, select: Details -> XML View.

![image](https://cloud.githubusercontent.com/assets/22189754/26235183/2a1419ac-3c72-11e7-94f7-e1d7cbff850a.png)

**Comment by gjahchan** [comment]
Now that Wazuh 2.0 is out, is a fix on your radar? If yes, is there a tentative date?

**Comment by Zenidd** [comment]
Hi @gjahchan,

sorry for the late reply.

The bug was fixed in release v3.8.0. If you use a Wazuh version equal to or greater than 3.8 you won't have this kind of problem with Eventchannel. Check the PR: https://github.com/wazuh/wazuh/pull/2142


I'm closing this ticket. Please feel free to reopen this or a new one whenever you need us.
<br></br>
Best regards,

Juan Pablo Sáez
