### ISSUE TITLE
Avoid the use of hardcoded temporary directory names in framework

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10115]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding the use of insecure usage of temp file/directory.

Vulnerabilities found in:

- framework/wazuh/core/configuration.py line 676
- framework/wazuh/core/utils.py line 1755

These flaws are caused by hardcoded temporary directories. We could investigate if we could generate a temporary one in a safer way (the tmpfile library can create it by its own): https://docs.openstack.org/bandit/1.4.0/plugins/hardcoded_tmp_directory.html

Once changes are done, pass the test to check that these flaws were deleted from the known flaws JSON file of framework.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I found out a solution using `NamedTemporaryFile` from `tempfile` package.
I'll need to do more tests but it seems to be properly working. Bandit is no longer alerting of this flaw at our code.

Regards,
Alexis
