### ISSUE TITLE
Investigate and change the use of MD2, MD4, MD5, or SHA1 hash functions in wodles

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10116]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding the use of insecure hash functions.

Investigate if it is possible to use SHA256 or a different secure cryptograpthic algorithm.
Algorithms which are not considered secure with alternatives: https://security.stackexchange.com/questions/78/what-cryptographic-algorithms-are-not-considered-secure

This is not a problem since the data handled are not critical and are only used internally by the wodle, so there is no decoding possibility. Despite this, we could investigate and use secure hash functions, similar to the same possible flaws found in framework.

Vulnerabilities found in:

- wodles/azure/azure-logs.py line 246
https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/azure/azure-logs.py#L248

- wodles/azure/azure-logs.py line 384
https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/azure/azure-logs.py#L386

- wodles/azure/azure-logs.py line 530
https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/wodles/azure/azure-logs.py#L532

More info.: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b303-md5

Once changes are done, pass the test to check that these flaws were deleted from the known flaws JSON file of framework.

**Comment by noise-kngdm** [comment]
## Issue update
We opened wazuh/wazuh-qa#2338 to mark the security flaw reported by this issue as a false positive.
