### ISSUE TITLE
Exploratory test - syscollector/sysinfo callback changes

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#10126]
Hi team!

This issue aims to keep record of exploratory sessions related to #9268 epic implementation.

Regards,
Nico

Functional testing.
## DoD
- [x] Ubuntu functional test - @tinachoB 
- [x] Debian functional test. - @HanesSciarrone 
- [x] Centos7/8 functional test. - @jnasselle
- [x] Centos5 functional test. - @dwordcito
- [x] Windows XP functional test - @tinachoB 
- [x] Windows 7 functional test - @tinachoB
- [x] Windows 8.1 functional test. - @HanesSciarrone 
- [x] Windows 10 functional test. - @HanesSciarrone 
- [x] MacOS Sierra or Catalina functional test. @tinachoB 
- [x] MacOS BigSur functional test. @Dwordcito 
- [x] FreeBSD functional test. @jnasselle 
- [x] ArcLinux functional test. @jnasselle 

### Charter 1
1. Install the callback Wazuh agent version.
2. Synchronize the agent with the Wazuh server.
3. Start the Wazuh agent and check if everything is up and running.
4. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

### Charter 2
1. Install the callback Wazuh agent version.
3. Synchronize the agent with the Wazuh server.
4. Start the Wazuh agent and check if everything is up and running.
5. Create a new process and re-sync (decrease syscollector main loop time to review this.)
6. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

### Charter 3
1. Install the callback Wazuh agent version.
3. Synchronize the agent with the Wazuh server.
4. Start the Wazuh agent and check if everything is up and running.
5. Install new package and re-sync (decrease syscollector main loop time to review this.)
6. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

### Charter 4
1. Install the callback Wazuh agent version.
3. Synchronize the agent with the Wazuh server.
4. Start the Wazuh agent and check if everything is up and running.
5. Open a new port and re-sync(decrease syscollector main loop time to review this.)
6. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

### Additional charter Windows 1
1. Install the callback Wazuh agent version.
2. Disable hotfixes and start agent.
3. Synchronize the agent with the Wazuh server.
4. Start the Wazuh agent and check if everything is up and running (hotfixes should not be displayed, and packages should be displayed).
5. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

### Additional charter Windows 2
1. Install the callback Wazuh agent version.
2. Disable packages and start agent.
3. Synchronize the agent with the Wazuh server.
4. Start the Wazuh agent and check if everything is up and running (hotfixes should be displayed, and packages should not be displayed).
5. Check inventory data, under Wazuh Kibana Dashboard, which has correct information.

**NOTE**: If the agent had synchronized a certain scan with the manager, and later it is deactivated, the manager will show the last information obtained (it is cached). This was solved (but still not merged in currend dev branch) in #9133

**Comment by tinachoB** [comment]
## Ubuntu (20.04) funcional test

|Charter|Status|
|---|---|
|Charter 1|✔️ PASSED|
|Charter 2|✔️ PASSED|
|Charter 3|✔️ PASSED|

**Comment by jnasselle** [comment]
## Centos 7/8 Functional test

|Charter|Status|
|---|---|
|Charter 1|✔️ PASSED|
|Charter 2|✔️ PASSED|
|Charter 3|✔️ PASSED|
|Charter 4|✔️ PASSED|

**Comment by HanesSciarrone** [comment]
## Windows 10 Functional test

|Charter|Status|
|---|---|
|Charter 1|✔️ PASSED|
|Charter 2|✔️ PASSED|
|Charter 3|✔️ PASSED|
|Charter 4|✔️ PASSED|
|Additional charter Windows 1|✔️ PASSED|
|Additional charter Windows 1|✔️ PASSED|

**Comment by Dwordcito** [comment]
## Centos 5 Functional test

|Charter|Status|
|---|---|
|Charter 1|✔️ PASSED|
|Charter 2|✔️ PASSED|
|Charter 3|✔️ PASSED|
|Charter 4|✔️ PASSED|
