### ISSUE TITLE
Fix Python code vulnerabilities found in framework and wodles

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10125]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

These possible flaws have been studied and new issues have been created to include the solutions to avoid these vulnerabilities.

---
**WORKING BRANCH**: [dev-fix-python-code-vulnerabilities](https://github.com/wazuh/wazuh/tree/dev-fix-python-code-vulnerabilities)
**TARGET WAZUH BRANCH**: [master](https://github.com/wazuh/wazuh/tree/master)

Latest rebase of `dev-fix-python-code-vulnerabilities` (working) with `master`: February, 4 - 14:40 UTC

---
**WORKING QA BRANCH**: [dev-fix-python-code-vulnerabilities](https://github.com/wazuh/wazuh-qa/tree/dev-fix-python-code-vulnerabilities)
**TARGET WAZUH-QA BRANCH**: [master](https://github.com/wazuh/wazuh/tree/master)

Latest rebase of `dev-fix-python-code-vulnerabilities` (working) with `master`: February, 4 - 14:50 UTC

The known flaws files are updated with the `master` branch of `wazuh/wazuh` repo since: February, 4 - 14:50 UTC (ONCE https://github.com/wazuh/wazuh-qa/pull/2548 IS MERGED)

**Comment by Kondent** [comment]
## Update

Latest rebase of `dev-fix-python-code-vulnerabilities` (working) with `master`: NOV, 3 - 14:05 UTC

**Comment by Kondent** [comment]
## Update
Latest rebase of `dev-fix-python-code-vulnerabilities` (working) with master: NOV, 5 - 18:26 UTC

**Comment by noise-kngdm** [comment]
Latest rebase of dev-fix-python-code-vulnerabilities (working) with master: NOV, 10 - 14:40 UTC
