### ISSUE TITLE
SCA: sshd config CIS benchmarks fail on RHEL8

### ISSUE THREAD

**Issue by joar-rasmussen** [wazuh/wazuh#10139]
|Wazuh version| Component | Action type |
| 4.2.1| Rules/Decoders | Error |

## Description
We are experiencing false positives from SCA using cis_rhel8_linux on RHEL8 servers.
This affects all parts of the benchmark targeting SSHD config.

### Service/Product/Module
RHEL8 SSHD

### Current results
All tests based on parsing SSHD config fail even if actual config is correct according to CIS. Seems to affect all tests with names starting with "Ensure SSH."
The problem seems to be that "sshd -T" does not output the running config to stdout on RHEL8, as it does on RHEL7.
Our own research indicates that, on RHEL8, you need additional parameters to this command. "sshd -T -C user=root -C host=localhost -C addr=localhost" seems to work as intended.

### Expected results
Correct result on sshd config tests. E.g. a pass on "Ensure SSH X11 forwarding is disabled" if X11 forwarding is actually disabled in current and running configuration.

### Log source / integration
Output of "sshd -T"

### Log reference
Example output of "sshd -T" on RHEL8:
'Match Address' in configuration but 'addr' not in connection test specification.

Example output of "sshd -T" on RHEL7:
port 22
addressfamily any
listenaddress [::]:22
listenaddress 0.0.0.0:22
usepam yes
[..]

### Threats and compliance
We are trying to use Wazuh to measure compliance against CIS and PCI-DSS for RHEL8.

**Comment by jcruzlp** [comment]
As @joar-rasmussen mentioned on the slack communtiy https://wazuh.slack.com/archives/C0A933R8E/p1631785900389600
There could be a bug, we'll study and try to reproduce the issue 

```
I wonder if I have found another error in "CIS Benchmark for Red Hat Enterprise Linux 8."
The check "Ensure updates, patches, and additional security software are installed",  runs the command "yum check-update --security" and looks for the phrase "No packages needed for security" in output.
But on my RHEL8 systems, a different phrasing is returned from that command: "No security updates needed" and the check erroneously is reported as Failed.
```

**Comment by jcruzlp** [comment]
## Progress Update

Taking special care for IDs 5032 and 5022.
Using the PDF for version 1.0.1 https://learn.cisecurity.org/l/799323/2021-05-19/47xyb
