### ISSUE TITLE
Investigate possible vulnerabilities regarding SQL injection vector through string-based query construction in `framework`

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10147]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding possible SQL injection vectors.

- [framework/wazuh/core/rootcheck.py line 98](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/rootcheck.py#L98)
- [framework/wazuh/core/rootcheck.py line 104](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/rootcheck.py#L104)
- [framework/wazuh/syscheck.py line 93](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/syscheck.py#L93)
- [framework/wazuh/syscheck.py line 95](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/syscheck.py#L95)
- [framework/wazuh/syscheck.py line 97](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/syscheck.py#L97)

More information: https://bandit.readthedocs.io/en/latest/plugins/b608_hardcoded_sql_expressions.html

We should investigate these lines and see if they are real vulnerabilities.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
* Wazuh QA PR: https://github.com/wazuh/wazuh-qa/pull/2361.
