### ISSUE TITLE
Investigate possible vulnerabilities when using `subprocess` in the `framework/` directory

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10144]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding the use of subprocess calls in `framework/`.

In total, we have 11 possible vulnerabilities with the use of subprocess.

- [framework/wazuh/core/cluster/cluster.py line 39](https://github.com/wazuh/wazuh/blob/b1c7ae23cba517c05b64063e8d54121b9e003191/framework/wazuh/core/cluster/cluster.py#L39)
- [framework/wazuh/core/common.py line 62](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/common.py#L62)
- [framework/wazuh/core/configuration.py line 713](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/configuration.py#L713)
- [framework/wazuh/core/utils.py line 112](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/utils.py#L112)
- [framework/scripts/wazuh-logtest.py line 421](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/scripts/wazuh-logtest.py#L421)
- [framework/wazuh/core/cluster/cluster.py line 39](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/cluster.py#L39)
- [framework/scripts/wazuh-logtest.py line 14](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/scripts/wazuh-logtest.py#L14)
- [framework/wazuh/core/cluster/cluster.py line 14](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/cluster/cluster.py#L14)
- [framework/wazuh/core/common.py line 7](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/common.py#L7)
- [framework/wazuh/core/configuration.py line 9](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/configuration.py#L9)
- [framework/wazuh/core/utils.py line 24](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/utils.py#L24)

The last 5 vulnerabilities are also due to the use of subprocess but the difference is that these possible flaws were just telling to consider the possible security implications of importing subprocess, instead of its usage.

### Vulnerability when using subprocess:

**Issue text:** subprocess call - check for execution of untrusted input.

**More info.:** https://bandit.readthedocs.io/en/latest/plugins/b603_subprocess_without_shell_equals_true.html

### Vulnerability when importing subprocess:

**Issue text:** Consider possible security implications associated with subprocess module.

**More info.:** https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html#b404-import-subprocess

We should investigate these results and see if they are real vulnerabilities.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I've finished the investigation on this issue. The report is available at related [pull request](https://github.com/wazuh/wazuh/pull/10740).

Regards,
Alexis
