### ISSUE TITLE
Investigate possible vulnerabilities when using `chmod` in the `framework/` directory

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10145]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws regarding the use of `chmod` in `framework/`.

Issue text: Chmod setting a permissive mask 0o770 on file (group_path).

- [framework/wazuh/agent.py line 582.](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/agent.py#L582)

Issue text: Chmod setting a permissive mask 0o750 on file (agent_backup_dir).

- [framework/wazuh/core/agent.py line 611.](https://github.com/wazuh/wazuh/blob/7d423ab0328632d6b37f919d68110e683445b065/framework/wazuh/core/agent.py#L611)

A MEDIUM warning is generated if a file is set to group executable and a HIGH warning is reported if a file is set world writable. In this case, both possible flaws are reported with severity MEDIUM so the file is set to group executable.

More information about these possible vulnerabilities: https://bandit.readthedocs.io/en/latest/plugins/b103_set_bad_file_permissions.html

We should investigate these results and see if they are real vulnerabilities.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
This code flaw could be fixed changing `group` value of the permission tuple.
I think there's no need to give permission to `group` and we can just go with user (`700`, for instance). I'm currently asking to core-team if this permission assignment is something they should be aware of (For example, I can change permission of a new group folder but the `default` one should be modified from core). 

In the meantime I made those changes and tried few tests (AIT) to check overall operation. Everything seems to be properly working.

Regards,
Alexis
