### ISSUE TITLE
Investigate possible Python code vulnerabilities in the `api/` directory

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10142]
## Description

With the test created in the issue https://github.com/wazuh/wazuh-qa/issues/1615, some possible code flaws were found by Bandit.

In this issue we specify flaws found in the api/ directory. We have 2 possible flaws.

### Issue 1

Possible flaw found in `wazuh-apid.py:`

Code:

```
    app.add_api('spec.yaml',
                arguments={'title': 'Wazuh API',
                           'protocol': 'https' if api_conf['https']['enabled'] else 'http',
                           'host': api_conf['host'],
                           'port': api_conf['port']
                           },
                strict_validation=True,
                validate_responses=False,
                pass_context_arg_name='request',
                options={"middlewares": [response_postprocessing, set_user_name, security_middleware, request_logging,
                                         set_secure_headers]})
```

Possible flaw: Possible hardcoded password: 'request'

The `pass_context_arg_name` defines the name of a request argument that will be added to the endpoints. It is not a password. We should investigate this result and see if it is a real vulnerability.

More info: https://bandit.readthedocs.io/en/latest/plugins/b106_hardcoded_password_funcarg.html

### Issue 2

Possible flaw found in `configuration.py`

Code:

```
default_api_configuration = {
    "host": "0.0.0.0",
    "port": 55000,
    "use_only_authd": False,
    "drop_privileges": True,
    "experimental_features": False,
    "max_upload_size": 10485760,
    "intervals": {
        "request_timeout": 10
    },
    "https": {
        "enabled": True,
        "key": "api/configuration/ssl/server.key",
        "cert": "api/configuration/ssl/server.crt",
        "use_ca": False,
        "ca": "api/configuration/ssl/ca.crt",
        "ssl_protocol": "TLSv1.2",
        "ssl_ciphers": ""
    },
    "logs": {
        "level": "info",
        "path": "logs/api.log"
    },
    "cors": {
        "enabled": False,
        "source_route": "*",
        "expose_headers": "*",
        "allow_headers": "*",
        "allow_credentials": False,
    },
    "cache": {
        "enabled": True,
        "time": 0.750
    },
    "access": {
        "max_login_attempts": 50,
        "block_time": 300,
        "max_request_per_minute": 300
    },
    "remote_commands": {
        "localfile": {
            "enabled": True,
            "exceptions": []
        },
        "wodle_command": {
            "enabled": True,
            "exceptions": []
        }
    }
}
```

Possible flaw: Possible binding to all interfaces.

We are told that we are exposing the API from all network interfaces. This is due to the design of the API, by default, the API accepts all connections unless otherwise indicated in its configuration.

More info: https://bandit.readthedocs.io/en/latest/plugins/b104_hardcoded_bind_all_interfaces.html

We should investigate this result and see if it is a real vulnerability.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
# Issue report


## `wazuh-apid.py: B106: hardcoded_password_funcarg`
```
The use of hard-coded passwords increases the possibility of password guessing tremendously.
This plugin test looks for all function calls being passed a keyword argument that is a string literal.
It checks that the assigned local variable does not look like a password.

Variables are considered to look like a password if they have match any one of:
* password
* pass
* passwd
* pwd
* secret
* token
* secrete

Note: this can be noisy and may generate false positives.
```
This possible flaw is pointing to the following code block:

https://github.com/wazuh/wazuh/blob/4ecd41ba8cd02f07fbe521c2aa8605f120a766aa/api/scripts/wazuh-apid.py#L160-L170

`Possible hardcoded password: 'request'`

Diving into `connexion.AioHttpApp` package, I found more information about this parameter and its uses.
```python
class AioHttpApp(AbstractApp):
...
...
    def add_api(self, specification, **kwargs):
        if self._only_one_api:
            if self._api_added:
                raise ConnexionException(
                    "an api was already added, "
                    "create a new app with 'only_one_api=False' "
                    "to add more than one api"
                )
            else:
                self.app = self._get_api(specification, kwargs).subapp
                self._api_added = True
                return self.app

        api = self._get_api(specification, kwargs)
        try:
            self.app.add_subapp(api.base_path, api.subapp)
        except ValueError:
            raise ConnexionException(
                "aiohttp doesn't allow to set empty base_path ('/'), "
                "use non-empty instead, e.g /api"
            )

        return api

    def _get_api(self, specification, kwargs):
        return super(AioHttpApp, self).add_api(specification, **kwargs)
```

From `connexion.AbstractApp:`
```
:param pass_context_arg_name: Name of argument in handler functions to pass request context to.
:type pass_context_arg_name: str | None
```

Therefore I can conclude that `pass_context_arg_name='request'` is not a hardcoded password.
We can set it as false positive.


## `configuration.py: B104: hardcoded_bind_all_interfaces`
```
Binding to all network interfaces can potentially open up a service to traffic on unintended interfaces,
that may not be properly documented or secured.
This plugin test looks for a string pattern “0.0.0.0” that may indicate a hardcoded binding to all network interfaces.
```
https://github.com/wazuh/wazuh/blob/4ecd41ba8cd02f07fbe521c2aa8605f120a766aa/api/api/configuration.py#L29-L31

The main problem here could be that the running program, which is binding to all network interfaces, is not secure.
Our Wazuh API is safe to use, but we also recommend certain changes to its default configuration to [make it even more secure](https://documentation.wazuh.com/current/user-manual/api/securing-api.html).

Possible solutions:
* set it as false positive.
* deny wazuh-apid service to start if API host is not configured.
* force the user to set an IP on the installation process (or network interface).

In my opinion, this should be set as false positive too and let the user decide its configuration.

**Comment by Kondent** [comment]
## Update
* Wazuh QA PR: https://github.com/wazuh/wazuh-qa/pull/2359.
