### ISSUE TITLE
Agent is connected to wazuh manager but kibana displays agent status as never connected>

### ISSUE THREAD

**Issue by mmali277** [wazuh/wazuh#1014]
my windows Agent is working fine, sending all logs to wazuh manager, where as kibana also displays all logs but staus of agent is alayways never conneccted, i added new agents and gave same results. Please Help!!

Agent connected log in Kibana:

![screenshot from 2018-07-27 16-49-26](https://user-images.githubusercontent.com/24794007/43319266-7ba24cde-91bd-11e8-881d-240822ed4cfb.png)

Agent connected log in alerts.log:

** Alert 1532692065.4830880: mail  - ossec,pci_dss_10.6.1,pci_dss_10.2.6,gpg13_10.1,gdpr_IV_35.7.d,
2018 Jul 27 16:47:45 (WIN_10) 192.168.10.10->ossec
Rule: 503 (level 3) -> 'Ossec agent started.'
ossec: Agent started: 'WIN_10->192.168.10.10'.

Agent status shown in kibana:

![screenshot from 2018-07-27 16-50-18](https://user-images.githubusercontent.com/24794007/43319338-ca539270-91bd-11e8-8509-be5f1c3c034a.png)

**Comment by mmali277** [comment]
Yes i tried that too, nothing changes

**Comment by jesusgn90** [comment]
Seems pretty weird, could you paste the output of the next command (manager machine)?

```
 cat /var/ossec/logs/ossec.log | grep -i -E "(error|warn)"
```

Execute the same command in some of your agents machines.

Regards,
Jesús

**Comment by mmali277** [comment]
Here is the output.

2018/07/27 00:02:34 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:02:40 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:02:44 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:02:49 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:02:55 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:09:33 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:09:39 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:09:43 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:09:48 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:09:54 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:16:50 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:16:56 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:17:00 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:17:05 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:17:11 ossec-remoted: ERROR: (1408): Invalid ID 001 for the source ip: '192.168.10.9' (name 'unknown').
2018/07/27 00:31:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 01:04:25 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 01:43:30 ossec-authd: ERROR: (1206): Unable to Bind port '1515' due to [(98)-(Address already in use)]
2018/07/27 14:14:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:25:39 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:27:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:35:20 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:36:43 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:43:09 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:44:16 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:46:28 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:55:31 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:56:52 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 15:59:47 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 16:01:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 16:19:17 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 16:20:32 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 16:21:25 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 18:07:56 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 18:08:45 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.
2018/07/27 18:18:02 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/apache2/error.log'.

**Comment by bah07** [comment]
Hi @mmali277 

It looks like the IP '192.168.10.9' was registered, then, either the manager was reinstalled or the agent's registration key was removed. But the agent keeps reporting to that manager who doesn't recognize it.

If this is true, we can check it as follows, the agent'192.168.10.9' will have in its _client.keys_ a key that is not registered in the manager's _client.keys_ file.

The location on both systems is: ''/var/ossec/etc/client.keys''.

Regards.

**Comment by mmali277** [comment]
Thanks for reply

The issue was not with the ip (192.168.10.9) as if u look the timestamps, this was another issue which i sorted out, the real issue was, agent was connected, also sending logs to manager (which was consantly showing on kibana, but in kibana agent status was "never Connected"). 

But i reinstalled all the setup, and then everything was ok, dont know what was the issue before, Anyways Thanks for your help.

**Comment by YashMangla** [comment]
Hi Team,

I deployed Wazuh Platform at production in client environment.
I'm facing same issue Agents is registered but the still it is showing never connected state at kibana.
I didn't able to receive any log from agent machine.

I enabled port for communication TCP 1514 & 1515 in firewall. 
Kindly help me with this issue ASAP.

**Comment by mgmacias95** [comment]
Hello @YashMangla,

Can you check if the agent is showed as active in `/var/ossec/bin/agent_control -l`  binary? If so, your problem is in the database the Kibana app uses to check agent statuses, otherwise, your problem is at network level.

Best regards,
Marta

**Comment by juergenc** [comment]
Hello @YashMangla, @mgmacias95,

this bug was already filed on 19. of September this year, see ticket #1345. Some other individual including me has the same issue.

**Comment by Justangatang** [comment]
I just started getting this same issue today on Wazuh 3.5.0.
```
{"timestamp":"2018/10/31 08:52:16","tag":"ossec-remoted","level":"warning","description":"(1408): Invalid ID 8790 for the source ip: '10.10.100.165' (name 'u
nknown')."}
{"timestamp":"2018/10/31 08:52:22","tag":"ossec-remoted","level":"warning","description":"(1408): Invalid ID 8790 for the source ip: '10.10.100.165' (name 'unknown')."}
{"timestamp":"2018/10/31 08:52:26","tag":"ossec-remoted","level":"warning","description":"(1408): Invalid ID 8790 for the source ip: '10.10.100.165' (name 'unknown')."}
{"timestamp":"2018/10/31 10:13:19","tag":"ossec-remoted","level":"warning","description":"(1408): Invalid ID 8790 for the source ip: '10.10.0.17' (name 'unknown')."}
```

Was occurring until I restarted the manager and then it stopped. I have close to 10,000 keys in client.keys that I moved over from an old 2.* ossec version. Couldn't find that ID '8790' in the list, or the IPs, or the hostnames associated to the IPs.

Weird one!
