### ISSUE TITLE
Modulesd crashes after upgrade

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#10165]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| >= 4.2.0 | modulesd | Agent | WPK/RPM | Linux |

# Description

Given specific conditions, the building of the `wazuh-modulesd` binary makes it behave strangely. It crashes, from time to time, in the firsts 5 to 10 seconds of execution. **The issue is directly related to the WPK/RPM building environment and is totally independent of the agent's system**.

An example output was obtained when running the `wazuh-modulesd` process in debugging and foreground mode, but the only message in common, among different tests, is the "core dumped":
```
╰─# /var/ossec/bin/wazuh-modulesd -fd    
.
.
.
2021/09/21 22:41:21 sca[9125] wm_sca.c:983 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 3016 'Ensure lockout for failed password attempts is configured'
2021/09/21 22:41:21 sca[9125] wm_sca.c:984 at wm_sca_do_scan(): DEBUG: Rule aggregation strategy for this check is 'all'
2021/09/21 22:41:21 sca[9125] wm_sca.c:986 at wm_sca_do_scan(): DEBUG: Beginning rules evaluation.
2021/09/21 22:41:21 2021/09/21 22:41:21 wazuh-modulesd:syscollector[9125] wm_syscollector.c:81 at wm_sys_log(): INFO: Module started.
2021/09/21 22:41:21 wazuh-modulesd:syscollector[9125] wm_syscollector.c:81 at wm_sys_log(): INFO: Starting evaluation.
[1]    9125 IOT instruction (core dumped)  /var/ossec/bin/wazuh-modulesd -fd
```

Here is a collection of core dump files obtained when running `wazuh-modulesd` (build in debug mode):
[v4.2.2-rc1_crash.zip](https://github.com/wazuh/wazuh/files/7227829/v4.2.2-rc1_crash.zip)

# Test Environments

This condition was reproduced in two different environments with a similar setup.

### Environment I

- **CPU**: AMD Ryzen 9 3950X
- **Host OS**: Arch Linux 64bit (5.14)
- **Building Vagrant Image**:  bento/ubuntu-20.04
- **Hypervisor**: Virtualbox 6.1
- **Vagrant Image's Docker version**: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
- **Wazuh Package**: 4.2

### Environment II

- **CPU**: AMD Ryzen 7 PRO 4750U
- **Host OS**: Manjaro Linux (Arch based)
- **Building Vagrant Image**:  bento/ubuntu-20.04
- **Hypervisor**: Virtualbox 6.1
- **Vagrant Image's Docker version**: Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.2
- **Wazuh Package**: 4.2

# Steps to reproduce

### Building steps \*

- Clone `wazuh-packages` repository
- Go to `wazuh-packages/rpm/`
- Generate the RPM package with the following command:
```./generate_rpm_package.sh -b v4.2.1 -t agent -d --packages-branch 4.2```

\* After these steps, the RPM package is correctly build but `wazuh-modulesd` binary contains a bug

### Installing steps
- Install Wazuh v4.1.5 Linux agent. (released)
- Upgrade agent via RPM

# Observations

- When trying to reproduce the bug by following the steps using the same environment but changing the Vagrant's Image to a Centos 7, then no crash occurs during `wazuh-modulesd` runtime.
- When trying to reproduce the bug by following the steps using the same environment but changing the GCC version, from 5.5 to 9.4, on the [Dockerfile](https://github.com/wazuh/wazuh-packages/blob/4.2/rpms/CentOS/6/x86_64/Dockerfile#L43-L59) that is used to generate the WPK/RPM package, then no crash occurs during `wazuh-modulesd` runtime.

**Comment by JcabreraC** [comment]
Replicated in Ubuntu Focal:
```
# /var/ossec/bin/wazuh-modulesd -fd
2021/09/16 15:13:03 wazuh-modulesd[24228] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2021/09/16 15:13:03 wazuh-modulesd[24228] main.c:76 at main(): DEBUG: Wazuh home directory: /var/ossec
2021/09/16 15:13:03 wazuh-modulesd[24228] main.c:86 at main(): INFO: Started (pid: 24228).
2021/09/16 15:13:03 wazuh-modulesd:agent-upgrade[24228] wm_agent_upgrade_agent.c:96 at wm_agent_upgrade_start_agent_module(): INFO: (8153): Module Agent Upgrade started.
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:47 at StartMQ(): DEBUG: Connected succesfully to 'queue/sockets/queue' after 0 attempts
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:48 at StartMQ(): DEBUG: (unix_domain) Maximum send buffer set to: '212992'.
2021/09/16 15:13:03 wazuh-modulesd:ciscat[24228] wm_ciscat.c:1426 at wm_ciscat_check(): INFO: Module disabled. Exiting...
2021/09/16 15:13:03 wazuh-modulesd[24228] wmcom.c:122 at wmcom_main(): DEBUG: Local requests thread ready
2021/09/16 15:13:03 wazuh-modulesd:control[24228] wm_control.c:199 at wm_control_main(): INFO: Starting control thread.
2021/09/16 15:13:03 wazuh-modulesd:osquery[24228] wm_osquery_monitor.c:590 at wm_osquery_monitor_main(): INFO: Module disabled. Exiting...
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:47 at StartMQ(): DEBUG: Connected succesfully to 'queue/sockets/queue' after 0 attempts
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:48 at StartMQ(): DEBUG: (unix_domain) Maximum send buffer set to: '212992'.
2021/09/16 15:13:03 sca[24228] wm_sca.c:141 at wm_sca_main(): INFO: Module started.
2021/09/16 15:13:03 sca[24228] wm_sca.c:180 at wm_sca_main(): INFO: Loaded policy '/var/ossec/ruleset/sca/cis_debian10.yml'
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:47 at StartMQ(): DEBUG: Connected succesfully to 'queue/sockets/queue' after 0 attempts
2021/09/16 15:13:03 wazuh-modulesd[24228] mq_op.c:48 at StartMQ(): DEBUG: (unix_domain) Maximum send buffer set to: '212992'.
2021/09/16 15:13:03 sca[24228] wm_sca.c:314 at wm_sca_start(): INFO: Starting Security Configuration Assessment scan.
Segmentation fault (core dumped)
```
Alert.log:
```
** Alert 1631805705.2970923: - syslog,errors,service_availability,gdpr_IV_35.7.d,
2021 Sep 16 17:21:45 (vm-ubuntu20) any->/var/log/kern.log
Rule: 1010 (level 5) -> 'Process segfaulted.'
Sep 16 15:21:39 ubuntu-focal kernel: [ 1904.754735] wazuh-modulesd[25502]: segfault at 0 ip 00007fb4b70bcb04 sp 00007fb4b5777618 error 4 in libc-2.31.so[7fb4b6fbb000+178000]
```

**Comment by 0x4c6565** [comment]
We're also seeing this quite frequently:

```
Aug 10 08:36:26 redacted kernel: wazuh-modulesd[40353]: segfault at 10 ip 0000000000464b00 sp 00007f2ecaf15e70 error 4 in wazuh-modulesd[400000+f2000]
Aug 10 11:25:31 redacted kernel: wazuh-modulesd[41720]: segfault at 0 ip 00007fd873bb0e71 sp 00007fd863ffeb58 error 4 in libc-2.17.so[7fd873b24000+1c4000]
Aug 10 20:20:37 redacted kernel: wazuh-modulesd[46876]: segfault at 0 ip 00007fa8d6f70e71 sp 00007fa8c77fdb58 error 4 in libc-2.17.so[7fa8d6ee4000+1c4000]
Aug 11 10:17:51 redacted kernel: wazuh-modulesd[64150]: segfault at 0 ip 00007f36f4f0de71 sp 00007f36ed7f9b58 error 4 in libc-2.17.so[7f36f4e81000+1c4000]
Aug 11 10:31:42 redacted kernel: wazuh-modulesd[91836]: segfault at 0 ip 00007f2efa266e71 sp 00007f2eea7fbb58 error 4 in libc-2.17.so[7f2efa1da000+1c4000]
Aug 11 19:39:58 redacted kernel: wazuh-modulesd[94599]: segfault at 0 ip 00007f612ad06e71 sp 00007f6127a5fb58 error 4 in libc-2.17.so[7f612ac7a000+1c4000]
Aug 12 10:41:01 redacted kernel: wazuh-modulesd[2191]: segfault at 0 ip 00007f120b2fde71 sp 00007f1203ffeb58 error 4 in libc-2.17.so[7f120b271000+1c4000]
Aug 12 10:45:44 redacted kernel: wazuh-modulesd[5906]: segfault at 0 ip 00007fb69c016e71 sp 00007fb683ffeb58 error 4 in libc-2.17.so[7fb69bf8a000+1c4000]
```

Debug logs don't really indicate much:

```
2022/08/12 10:45:38 wazuh-modulesd:vulnerability-detector[5899] wm_vuln_detector_nvd.c:1798 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5470): It took '3' seconds to 'find NVD' vulnerabilities in agent '1578'
2022/08/12 10:45:38 wazuh-modulesd:vulnerability-detector[5899] wm_vuln_detector_nvd.c:1800 at wm_vuldet_win_nvd_vulnerabilities(): DEBUG: (5466): Sending vulnerabilities report for agent '1578'
Segmentation fault
```

* OS: `CentOS 7`
* Kernel: `Linux version 3.10.0-1160.66.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed May 18 16:02:34 UTC 2022`

**Comment by Dwordcito** [comment]
@juliancnn any update?

**Comment by juliancnn** [comment]
Hi @Dwordcito I have not been able to replicate the crash in `v4.4.0-rc1` with packages branch 4.4 ([commit](https://github.com/wazuh/wazuh-packages/commit/d4c0f00d6a16acf2c3265fd10e0933c1c9411c4a))

**Comment by Dwordcito** [comment]
Closed because not is reproducible after build environment changes.
