### ISSUE TITLE
Agents stay with "pending" status for too long

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10162]
| Version |Component|
|---|---|
| 4.2.2 | Wazuh agents |

As it was reported in https://github.com/wazuh/wazuh/issues/9943, some of the API integration tests are failing due to agents not being `active` after a long time.

These agents can be restarted throughout the test execution, but every time that happens we apply a delay of 45 seconds. This means that some agents are still `pending` after at least 45 seconds. Sometimes that time is even longer.

It is not responsability of the test to cover these cases as the time to become `active` should not be that long, keeping in mind that we only have 3 cluster nodes and 8 active agents.

**Comment by davidjiglesias** [comment]
After the investigation and fixes done in #10913, it has been determined that the pending issue is no longer existing.
