### ISSUE TITLE
Add support for Debian Bullseye in Vulnerability Detector

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#10180]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | wazuh-modulesd | Manager/Agent | Packages/Sources | Debian Bullseye |

The aim of this issue is to add native support for vulnerability scans to Debian Bullseye.

Debian Bullseye offers its own OVAL DB: https://www.debian.org/security/oval/

We currently support older versions of Debian. We should incorporate this new OVAL that has just been released.

The configuration block for this new distribution will be like the one we have for the previous versions:
```xml
<!-- Debian OS vulnerabilities -->  
<provider name="debian">
   <enabled>no</enabled>
   <os>bullseye</os>
   <update_interval>1h</update_interval>
</provider>
```

Regards,
Juan Cabrera

**Comment by chemamartinez** [comment]
Done #10357. Thanks @MarcelKemp!
