### ISSUE TITLE
Integrity check task flow optimization

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#10182]
|Wazuh version|Component|
|---|---|
| 4.2.2+ | Wazuh Cluster |

As part of the changes implemented for the cluster in the issue https://github.com/wazuh/wazuh/issues/10123, several performance tests have been launched for it. In these tests, the chosen configuration was 50000 agents and 25 workers.

Analyzing the results we can see a relationship between the integrity_check and integrity_sync plots.

#### Integrity check
![image](https://user-images.githubusercontent.com/15522808/133783080-d40d3cb4-6878-4ec0-b023-00a92f284337.png)

#### Integrity sync
![image](https://user-images.githubusercontent.com/15522808/133783118-714c8627-896c-4582-a8ff-eb87f9ebdbb4.png)

On the x-axis, we have the number of occurrences (entries) that appear in the log over the entire test. The period that corresponds to ~800 - ~1500 of the integrity_check task, corresponds to the period 0 - 600 of the integrity_sync task. This is because the integrity_check task checks the integrity of the files and is always running, however, the integrity_sync task only runs when changes are needed. So once the changes have been applied this task is no longer printed in the log because no synchronization is necessary.

In this issue we will focus on the period where synchronization is no longer necessary, i.e., approximately from log 1500 of the integrity_check task:

![image](https://user-images.githubusercontent.com/15522808/133783235-2c68f187-2f5a-4d0e-be59-e24bbf0b8526.png)

As we can see, despite not having to synchronize any files, this task still consumes a time between ~2 to ~5 seconds. This time may be partly due to the communication between the nodes, but it is also possible that some of the functions used by this task are not as optimized as they could be.

Therefore, the goal of this issue is to optimize the flow of the integrity_check task, so we will review function by function and analyze its performance to finally make the appropriate modifications.

Regards.

### Logs
[50000A25W.zip](https://github.com/wazuh/wazuh/files/7185567/50000A25W.zip)

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Already fixed by https://github.com/wazuh/wazuh/pull/10920 and https://github.com/wazuh/wazuh/pull/11328
