### ISSUE TITLE
The replacement of a never connected agent is rejected by the new disconnection_time authd setting

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#10185]
# Description

During the testing of the epic #9550, it was found that a new agent that was never connected can't be replaced if the `disconnection_time` setting is enabled. The **authd** daemon considers this agent as active because its `disconnected_time`
 is zero.

## Expected behavior

In case of a `never_connected` agent, the setting `disconnection_time` should be ignored.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10187 was merged.
