### ISSUE TITLE
Additional security checks for commands execution

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1019]
Agent ability to run commands is sometimes useful to capture certain data, for example, to periodically query the system about open sockets (`netstat`), running processes (`ps aux`), hard disk space (`df`), etc. 

This task will include additional hash validation of binaries being executed. For instance: only run a binary if it matches a specific SHA256 checksum. 

This change will apply to the wodle *command*.

## Proposed configuration

```xml
<wodle name="command">
  <command>/path/to/binary</command>
  <verify_md5>d41d8cd98f00b204e9800998ecf8427e</verify_md5>
  <verify_sha1>da39a3ee5e6b4b0d3255bfef95601890afd80709</verify_sha1>
  <verify_sha256>e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</verify_sha256>
  <skip_verification>no</skip_verification>
</wodle>
```

### verify_md5

Verify the binary MD5 sum. If it does not match, the agent will refuse to run the application.

### verify_sha1

Verify the binary SHA1 sum. If it does not match, the agent will refuse to run the application.

### verify_sha256

Verify the binary SHA256 sum. If it does not match, the agent will refuse to run the application.

### force_run

Run the command defined although the checksum does not match. In this case, the agent will log that the checksum verification failed but will run the application.

## Notes

The `<command>` option allows a full path and a program-only command. In the latter case, if the checksum verification is enabled for some hash, the agent will resolve the full path to the binary in order to validate the checksum. Hence, no further path resolution is performed: the agent will run the full path to the command.

**Comment by jesuslinares** [comment]
I would change the _force_run_ setting to _skip_verification_.
