### ISSUE TITLE
Unhandled JSONDecodeError in distributed API requests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#10212]
|Wazuh version|Component|
|---|---|
| 4.3.0 | Distributed API |

## Description

I have encountered the following error during a cluster workload test:
```
2021/09/20 11:12:06 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2021/09/20 11:12:06 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2021/09/20 11:12:06 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2021/09/20 11:12:13 INFO: Listening on 0.0.0.0:55000..
2021/09/20 11:18:18 INFO: Listening on 0.0.0.0:55000..
2021/09/20 11:35:36 INFO: wazuh 172.31.32.158 "GET /security/user/authenticate" with parameters {} and body {} done in 0.546s: 200
2021/09/20 11:36:10 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 157, in distribute_function
    response = await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 514, in forward_request
    response = await asyncio.shield(asyncio.gather(*[forward(node) for node in cleaned_valid_nodes]))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 423, in forward
    result = json.loads(await client.execute(b'dapi_fwd',
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021/09/20 11:36:10 INFO: wazuh 172.31.32.158 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 999999} done in 34.930s: 500
```

This same error has already been corrected in other parts of the code, in this PR: https://github.com/wazuh/wazuh/pull/8901. However, it seems not to be correctly handled when getting it as a response to a distributed call, here:
https://github.com/wazuh/wazuh/blob/bb1449a3bd89644ad8aed335439ceb6f94061555/framework/wazuh/core/cluster/dapi/dapi.py#L419-L434

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
### Issue update

This exception is unhandled and it can appear when forwarding the request or executing the request locally in the dapi:

`response = await self.forward_request()
`

and

`response = await self.execute_remote_request()
`

In `forward_request` the exception can appear as in the example shown and in `execute_remote_request`, it can appear when loading the `node_response` as json.

We have already an exception code to indicate an error when trying to decode using `json.loads`. It is the **3036** code and it is used in the `sync_wazuh_db_info` function when the master node can't load the string received from the worker as json.

I will make the proper changes to return a WazuhClusterError with this 3036 code in distribute_function if a string gives Error when trying to load it as JSON.

This error must be shown by the API as an internal error, so status code must be 500.

**Comment by mcarmona99** [comment]
## Issue update

This error can also appear in the `get_nodes` function in `control.py` and it is also unhandled. This would affect the endpoint `GET /cluster/nodes`. It also appears in the rest of functions in `control.py` but `get_system_nodes`. Because of this, it also affects `GET /cluster/healthcheck`.

These requests are `local_master`, so the exception is catched in the `execute_local_request` function and not outside (`distribute_function`).

To sum up, we have 2 situations where the `JSONDecodeError` can be catched:

**1.- forward_request and execute_remote_request**

https://github.com/wazuh/wazuh/blob/dcb82531821cfef8351283e358729fdb3b7b5e51/framework/wazuh/core/cluster/dapi/dapi.py#L173-L188

**2.- execute_local_request**

https://github.com/wazuh/wazuh/blob/dcb82531821cfef8351283e358729fdb3b7b5e51/framework/wazuh/core/cluster/dapi/dapi.py#L267-L285


In both cases the `JSONDecodeError` is catched as a generic `Exception` and a `WazuhInternalError` is generated with code **1000** (unhandled exception).

**Comment by mcarmona99** [comment]
## Issue update

I have added three unit test cases to test we are raising WazuhInternalError with code 3036 when handling a JSONDecodeError.

```
pytest framework/wazuh/core/cluster/dapi/tests/ --disable-warnings 
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/manuel/git/wazuh/framework
plugins: html-3.1.1, metadata-1.11.0, cov-2.12.0, testinfra-5.0.0, asyncio-0.14.0
collected 25 items                                                             

framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................... [ 76%]
......                                                                   [100%]

======================== 25 passed, 9 warnings in 0.60s ========================
```
