### ISSUE TITLE
Clean FIM deprecated code

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#10225]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

Moving FIM DB and synchronization modules of FIM to C++ makes the old code to be outdated. The goal of this issue is to ensure no residual code is present in the repository after the development.

- [x] Makefile
- [x] `cmocka` unit tests
- [x] Wrappers
- [x] Source code and headers

**Comment by jotacarma90** [comment]
Remember to delete this lines in the function `fim_link_delete_range`
https://github.com/wazuh/wazuh/blob/5a34b719a808f33297bb22e113b0bafe9fc79705/src/syscheckd/run_check.c#L793-L800

This condition cannot occur in this situation, since these events are always in scheduled mode!

**Comment by antoniomanuelfr** [comment]
These two functions can also be deleted
https://github.com/wazuh/wazuh/blob/a69deac35d6834b2da65a25ed1814a27f782ac66/src/syscheckd/src/run_check.c#L102-L137
