### ISSUE TITLE
Unknown HZ value on Ubuntu systems

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1022]
When installing Wazuh 3.5 from packages on an Ubuntu 16 system, the following messages appear:

```
Starting Wazuh v3.5.0 (maintained by Wazuh Inc.)...
Unknown HZ value! (93) Assume 1024.
Started wazuh-modulesd...
Unknown HZ value! (93) Assume 1024.
Started ossec-execd...
Unknown HZ value! (93) Assume 1024.
2018/07/30 17:18:39 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
Started ossec-agentd...
Unknown HZ value! (93) Assume 1024.
2018/07/30 17:18:39 rootcheck: INFO: Rootcheck disabled.
Started ossec-syscheckd...
Unknown HZ value! (93) Assume 1024.
Started ossec-logcollector...
Completed.
```

This may caused from generating the packages from an Ubuntu 12 version.

The problem doesn't appear if you install Wazuh from the sources on Ubuntu > 12

**Comment by TJOSERAFAEL** [comment]
This issue is caused by the version of `procps` library used. In the 'sysinfo.c` file there is a line that prints out the message.

```C
fprintf(stderr, "Unknown HZ value! (%d) Assume %Ld.\n", h, Hertz);
```

We will comment this line out for now. The Wazuh packages need to be compiled individual for each Debian platform.

**Comment by vikman90** [comment]
Fixed in the procps library bottle, downloadable with `make deps`.

GJ @TJOSERAFAEL !!
