### ISSUE TITLE
Develop a testing tool for the FIM DBSync

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#10226]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync)  | FIMDB | Manager/Agent | Packages/Sources | All |

## Description

During the implementation of the new fim DB module, using the DBSync library, we have considered developing a test tool that allows us to check that the DB is working correctly, verifying that the events correctly generate the necessary entries in the DB, and that the synchronization with the manager occurs correctly.
This is a way to quickly check all the changes carried out during the development of DBSync.

### Possible capabilities
After several analyzed proposals and a lot of research for possible designs we have come up with some possibilities for the testtool:

- Mainly we want it to be a black box that is in charge of receiving an input, process what is needed from the new FIM DB module, and return a variable output that gives us to understand that everything has worked correctly.
For this, we can use a json file, with which we can configure the necessary input, passing it the actions that we want to check and even the specific data of the files with which to make the test. Then the tool would be in charge of processing and using the functions that are needed, and give us an output of the state of the database that allows us to verify that everything is correct.

- Another possibility could be to use a tool that directly receives as parameter the name of a function of the FIM DB module that we are interested in testing, as well as the necessary information of files/registries to work with.
Here we have the advantage of not needing a very complex logic that converts the input in different checks.

**Comment by jotacarma90** [comment]
Once we start with the development, we will be able to have more clear what exactly we need the tool to automate, the scope of action, and the results that can give us more help. 
For the moment, due to not finding a suitable design to start with, we are going to pass this issue to stale while waiting to illuminate and collect more ideas.

**Comment by antoniomanuelfr** [comment]
We are planning to have a structure like the following (similar to the dbsync testtool):
![image](https://user-images.githubusercontent.com/22987701/135099692-d061108d-c7dc-47a8-bd38-313ea3cf525b.png)
- The main file will read one or more JSON that will contain the action that will be performed in the database and the data to be used. 
- The action structure will use the information stored in the JSON to execute a certain action in the database.
The JSON structure will have the following structure:
```json
{
    "action": "DB_INSERT|DB_REMOVE|DB_UPDATE",
    "table": "FILE|REGISTRY_KEY|REGISTRY_VALUE",
    "data": [
        {
            "path": "...",
            "checksum": "..",
            ----------
        },
        {
            "path": "...",
            "checksum": ".."
            ............
        }
    ]
}
```

**Comment by antoniomanuelfr** [comment]
For now, we are going to stop the development of this tool until the issue https://github.com/wazuh/wazuh/issues/10222 is finished. 
The main structure has already been done:
- [X] TestAction
- [X] UpdateAction
- [X] RemoveAction
- [X] InsertAction
- [X] Main
- [X] ReadJson
- [X] ReadArguments
- [ ] UpdateAction::execute
- [ ] RemoveAction::execute
- [ ] InsertAction::execute
All this has been done in the following branch: https://github.com/wazuh/wazuh/tree/10226_fim_db_testtool

**Comment by antoniomanuelfr** [comment]
The structure of the JSON with the data is going to change only for registries, as the key information and its values must be stored.
The final format  for registries is the following:

## Insert action
```json
{
    "action": "DB_INSERT|DB_UPDATE|DB_REMOVE",
    "table": "FILE|REGISTRY",
    "data": [
        {
            "key": {
                "id": "integer",
                "path": "string",
                "perm": "string",
                "uid": "string",
                "gid": "string",
                "user_name": "string",
                "group_name": "string",
                "mtime": "integer (modification time)" ,
                "arch": "integer (0=32bits, 1=64bits)", 
                "scanned": "boolean", 
                "last_event": "integer", 
                "checksum": "string"
            },
            "values": [ 
                {
                    "id": "integer (key identifier)",
                    "name": "string",
                    "type": "integer",
                    "size": "integer",
                    "md5": "string",
                    "sha1": "string",
                    "sha256": "string",
                    "scanned": "boolean",
                    "last_event": "integer",
                    "checksum": "string",
                    "mode": "0 (only 0 as scheduled is the only avaliable mode)"
                }
            ]
        }
    ]
}
```
The `values` field is optional, and it will store the values inside the key
