### ISSUE TITLE
Implementation of FIM DB wrappers

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#10227]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

The aim of this issue is to implement the methods for the two following classes:

- The `FimDBWrapper`, in charge of providing an interface in C for the rest of the components of FIM with all the needed methods to handle the scanned data in the database.
- The `DBItemWrapper` which is attempted to implement the operations needed to take the actions over the database.

**Comment by FrancoRivero** [comment]
All problems related to this epic are finished.
