### ISSUE TITLE
Prevent Analysisd from rejecting startup when dependant rules are missing

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#10244]
Analysisd parses the ruleset on startup. If it finds a rule that depends on another which does not exist, it drops an error and aborts the startup.

- `overwrite="yes"`
```
ERROR: Overwrite rule '100001' not found.
CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
```

- `<if_sid>`
```
ERROR: rules_list: Signature ID '57160' not found. Invalid 'if_sid'.
CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
```

- `<if_matched_sid>`
```
ERROR: rules_list: Signature ID '57160' not found. Invalid 'if_sid'.
CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
```

In the last case, it shows that the failing option is `<if_sid>`.
We need Analysisd to drop a warning but skip the invalid rule.

**Comment by branchnetconsulting** [comment]
If you are going to do this, you would probably want to also cover the case of <if_group> or <if_matched_group> referencing a non-existent rule group.  However,  it would be good to also make sure that the bad/skipped-rule warnings actually appear clearly in the Web UI when saving a change to a rule file.  Users are presently accustomed to understand the Web UI claiming success when saving rule/decoder changes, to mean none of the rules are invalid.  They are not going to start digging through analysisd logs just in case.
