### ISSUE TITLE
Email notifications not sending

### ISSUE THREAD

**Issue by prayingmantis287** [wazuh/wazuh#10241]
Hi Team,

I'm hoping someone can help with this issue. I recently noticed email notifications are not being sent during events where I would normally expect to receive them. The only recent change made was migrating the VM to a different hypervisor (along with other VMs, which are successfully sending emails using the same local mail server relay).

I tried sending a test email from the terminal using the format advised from another wazuh email related issue, but apparently the mail program does not exist. I did at least verify that ossec-mail exists.
`echo "Test message" | mail -s "Test Postfix" -r "recipient@mydomain.com" recipient@mydomain.com`
`-bash: mail: command not found`

I have tried the following:
- Rebooted both the wazuh and mail servers
- Updated wazuh-manager from 4.1.5 to  4.2.1
- Checked router logs for smtp connections from the wazuh server, of which there were none.
- Set the rule level threshold for emails to 3 and restarted the wazuh manager. Level 3 events are being logged, but emails are still not being sent.

This is part of the current ossec config (domains/IPs redacted for security):

```<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>10.10.10.10</smtp_server>
    <email_from>sender@mydomain.com</email_from>
    <email_to>recipient@mydomain.com</email_to>
    <email_maxperhour>20</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>20s</agents_disconnection_time>
    <agents_disconnection_alert_time>100s</agents_disconnection_alert_time>
  </global>
  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>3</email_alert_level>
  </alerts>
  <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
  <logging>
    <log_format>plain,json</log_format>
  </logging>
```

**Comment by DProvinciani** [comment]
Hi @prayingmantis287! Thanks for using Wazuh!

First of all, is good to mention that Wazuh has a whole implementation in the source code to send the emails. This results in a daemon called [wazuh-maild](https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-maild.html) in charge of sending the alerts by email.

Having said that, could you check in the `/var/ossec/logs/ossec.log` file whether is an error or failure reported by `wazuh-maild`?

On the other hand, did you verify that the smtp server IP is reachable? I'm wondering whether the new hypervisor isn't routing correctly the emails.

I'll be waiting for this information so I can help you with the troubleshooting.

**Comment by prayingmantis287** [comment]
I confirmed the mail server is reachable from wazuh, and that the mail relay server's firewall is allowing the wazuh smtp traffic through.

When attempting to telnet from wazuh to port 25 on the mail server, the connection hangs for a bit then returns "Connection timed out". However, an unrelated server can telnet port 25 and send emails successfully using the same mail relay server.
(Even though the mail server is allowing the wazuh smtp traffic through, it may be worth noting the other server that is able to send email is on a different vlan.)

The ossec log is showing the following for all attempted emails:
```
wazuh-maild: ERROR: (1762): Banner not received from server
wazuh-maild: ERROR: (1223): Error Sending email to 10.10.10.10 (smtp server)
```

I suspect a misconfiguration on the mail server, but am at a loss as to what it could be. The Postfix main.cf file has not been changed, and I have verified it is configured correctly, at least to the best of my knowledge.

**Comment by DProvinciani** [comment]
Hi @prayingmantis287 ! Thanks for all the details 👍 

With the Wazuh logs that you shared, I was able to confirm all the things that you mention in your comments. Basically, the next log appears only after a successful connection from Wazuh to the email server.

```
wazuh-maild: ERROR: (1762): Banner not received from server 
```

The thing is that after opening the connection, Wazuh will wait for the message `220 — SMTP Service ready` from the SMTP server. This message never arrives in Wazuh and so, `maild` logs the error.

Is good to mention that Wazuh will wait five minutes for this SMTP server message so, I think this is time enough for the server to respond.

Having said that, it makes even more sense the log `match_list_match: 10.10.23.52: no match` that probably tells you that the postfix server is rejecting the connection because of some network configuration. So, my suggestion at this point is to review your postfix configuration and in any case, ask about this behavior in the postfix users list [here](https://groups.google.com/g/mailing.postfix.users).

Please, let me know if you find the problem. And if you have any other questions related to Wazuh, don't hesitate to share them with us, we will be glad to help you.

**Comment by prayingmantis287** [comment]
Thanks very much @DProvinciani. Knowing the insight on how wazuh-maild works is really helpful. I will bring up an issue in the group you advised, and will post the resolution once found.

**Comment by DProvinciani** [comment]
Great! I'll be waiting for your comments!

Meanwhile, any idea that I would get from the Wazuh team, for sure I'll share it with you.

**Comment by prayingmantis287** [comment]
@DProvinciani, You were absolutely right about the hypervisor being a possible reason for emails not routing correctly.

The firewalls on the hypervisors were disabled, but the firewall for the hypervisor cluster was configure to only allow HTTP(S) traffic through. That explains why some servers were able to send mail to the mail relay; they were on the same vlan as the HVs, whereas the wazuh server was not. The emails are now sending properly.

How "some" of the SMTP traffic from the wazuh server was reaching the mail relay, I don't think I will ever understand. Guess I'll add it to the list of cosmic networking mysteries.

Thanks again for all of your help.

**Comment by DProvinciani** [comment]
@prayingmantis287 awesome! Happy to see that now everything is working.

With this resolved, we close this issue. But please, don't hesitate to share any other questions that you may have. You could use the community channel in Slack, our group in Google, Github, Reddit, Stackoverflow, Youtube, etc. All the Wazuh team is permanently reviewing all these channels to provide support quickly.
