### ISSUE TITLE
Release 4.2.2 - Release Candidate 2- External integration modules tests

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#10258]
The following issue aims to run test for some python wodles for the current release candidate, report the results, and open new issues for any encountered errors.

## External integration modules manual tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     | #10253                                            |
| **Version**                          | 4.2.2                                           |
| **Release candidate #**              | RC2                                           |
| **Tag**                              | https://github.com/wazuh/wazuh/tree/v4.2.2-rc2                                           |
| **Previous external integration modules manual tests issue** | N/A                                           |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

## Conclusions

All tests have **passed** and the results can be found [here](https://github.com/wazuh/wazuh/issues/10258#issuecomment-926552034). There is an extended test report [here](https://github.com/wazuh/wazuh/issues/10258#issuecomment-926639199). I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @santiago-bassett 
- [x] @davidjiglesias 
- [x] @CarlosRS9  
- [x] @noise-kngdm

**Comment by noise-kngdm** [comment]
## Status update
| Module | Status | Notes |
|---|--|--|
| AWS CloudWatch Logs  | :green_circle: | N/A | 
| AWS WAF  |  | N/A | 
| GCP  | | N/A | 
| Azure | | N/A |

**Comment by noise-kngdm** [comment]
## Test results
### CloudWatch Logs
For this test, a log group called `v4.2.2-rc2` was created. It has two log streams populated with logs that range from several days in the past until a couple of hours in the future. The module was executed in the following fashion:
`python3 ./aws-s3.py -d3 -sr cloudwatchlogs -g v4.2.2-rc2 -r us-east-1 -s 2021-Jan-3`

The module successfully creates the log streams and process them, as can be seen in the following execution trace:
```
root@3a5f21edeae1:/var/ossec/wodles/aws# python3 ./aws-s3.py -d3 -sr cloudwatchlogs -g v4.2.2-rc2 -r us-east-1 -s 2021-Jan-3
DEBUG: +++ Debug mode on - Level: 3
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: only logs: 1609632000000
DEBUG: +++ Table does not exist; create
DEBUG: Getting log streams for "v4.2.2-rc2" log group
DEBUG: Found "test_stream1" log stream in v4.2.2-rc2
DEBUG: Found "test_stream2" log stream in v4.2.2-rc2
DEBUG: Getting data from DB for log stream "test_stream1" in log group "v4.2.2-rc2"
DEBUG: Token: "None", start_time: "None", end_time: "None"
DEBUG: Getting CloudWatch logs from log stream "test_stream1" in log group "v4.2.2-rc2" using token "None", start_time "1609632000000" and end_time "None"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 0"
DEBUG: The message's timestamp is 1632261984000
DEBUG: "Old test log 0"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 1"
DEBUG: The message's timestamp is 1632265584000
DEBUG: "Old test log 1"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 2"
DEBUG: The message's timestamp is 1632269184000
DEBUG: "Old test log 2"
DEBUG: Getting CloudWatch logs from log stream "test_stream1" in log group "v4.2.2-rc2" using token "f/36400819167797498236219572516983835364366261927384186880/s", start_time "1609632000000" and end_time "None"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 3"
DEBUG: The message's timestamp is 1632272784000
DEBUG: "Old test log 3"
...
...
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 60"
DEBUG: The message's timestamp is 1632477984000
DEBUG: "Old test log 60"
DEBUG: Getting CloudWatch logs from log stream "test_stream1" in log group "v4.2.2-rc2" using token "f/36405475563394951430331525192269754601092573735067713536/s", start_time "1609632000000" and end_time "None"
DEBUG: Saving data for log group "v4.2.2-rc2" and log stream "test_stream1".
DEBUG: The saved values are "{'token': 'f/36405549512677180128503578673736915030379384152386404351/s', 'start_time': 1609632000000, 'end_time': 1632477984000}"
DEBUG: Getting data from DB for log stream "test_stream2" in log group "v4.2.2-rc2"
DEBUG: Token: "None", start_time: "None", end_time: "None"
DEBUG: Getting CloudWatch logs from log stream "test_stream2" in log group "v4.2.2-rc2" using token "None", start_time "1609632000000" and end_time "None"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 0"
DEBUG: The message's timestamp is 1632175604059
DEBUG: "Old test log 0"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 1"
DEBUG: The message's timestamp is 1632179204059
DEBUG: "Old test log 1"
...
...
DEBUG: Getting CloudWatch logs from log stream "test_stream2" in log group "v4.2.2-rc2" using token "f/36400498484397287332572104034784538867410185569832534016/s", start_time "1609632000000" and end_time "None"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "Old test log 23"
DEBUG: The message's timestamp is 1632258404059
DEBUG: "Old test log 23"
DEBUG: Getting CloudWatch logs from log stream "test_stream2" in log group "v4.2.2-rc2" using token "f/36400578767080002042815413563593071675776103500342624256/s", start_time "1609632000000" and end_time "None"
DEBUG: Saving data for log group "v4.2.2-rc2" and log stream "test_stream2".
DEBUG: The saved values are "{'token': 'f/36400777153204694575151290030026568281017104343362404351/s', 'start_time': 1609632000000, 'end_time': 1632258404059}"
DEBUG: Purging the BD
DEBUG: Getting log streams for "v4.2.2-rc2" log group
DEBUG: Found "test_stream1" log stream in v4.2.2-rc2
DEBUG: Found "test_stream2" log stream in v4.2.2-rc2
DEBUG: committing changes and closing the DB
```
The `start_time` and `end_time` fields of the database are correctly set with the timestamp of the date that was passed as `only_logs_after` value and the timestamp of the last log processed respectively.
As a note, the module will only fetch logs from the past until the time it was executed, it won't fetch any log with a timestamp belonging to the future. 

We made sure that the module wouldn't process already processed logs executing it twice and checking that it wouldn't fetch any log:
```
root@3a5f21edeae1:/var/ossec/wodles/aws# python3 ./aws-s3.py -d3 -sr cloudwatchlogs -g v4.2.2-rc2 -r us-east-1 -s 2021-Jan-3
DEBUG: +++ Debug mode on - Level: 3
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: only logs: 1609632000000
DEBUG: Getting log streams for "v4.2.2-rc2" log group
DEBUG: Found "test_stream1" log stream in v4.2.2-rc2
DEBUG: Found "test_stream2" log stream in v4.2.2-rc2
DEBUG: Getting data from DB for log stream "test_stream1" in log group "v4.2.2-rc2"
DEBUG: Token: "f/36405716411454245931687169927052467530716894909819748351/s", start_time: "1609632000000", end_time: "1632488784001"
DEBUG: Getting CloudWatch logs from log stream "test_stream1" in log group "v4.2.2-rc2" using token "f/36405716411454245931687169927052467530716894909819748351/s", start_time "1632488784002" and end_time "None"
DEBUG: Saving data for log group "v4.2.2-rc2" and log stream "test_stream1".
DEBUG: The saved values are "{'token': 'f/36405716411454245931687169927052467530716894909819748351/s', 'start_time': 1609632000000, 'end_time': 1632488784002}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Getting data from DB for log stream "test_stream2" in log group "v4.2.2-rc2"
DEBUG: Token: "f/36400578767135753903838190939910493615824697193446473727/s", start_time: "1609632000000", end_time: "1632258404061"
DEBUG: Getting CloudWatch logs from log stream "test_stream2" in log group "v4.2.2-rc2" using token "f/36400578767135753903838190939910493615824697193446473727/s", start_time "1632258404062" and end_time "None"
DEBUG: Saving data for log group "v4.2.2-rc2" and log stream "test_stream2".
DEBUG: The saved values are "{'token': 'f/36400578767158054649036721563052029334097345554952454143/s', 'start_time': 1609632000000, 'end_time': 1632258404062}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "v4.2.2-rc2" log group
DEBUG: Found "test_stream1" log stream in v4.2.2-rc2
DEBUG: Found "test_stream2" log stream in v4.2.2-rc2
DEBUG: committing changes and closing the DB
```
### AWS WAF
The module is working fine, we executed it with `-d3` and it fetched and processed all the logs, but the output was too large to put it here, so instead we decided to post an execution example with `-d2` since it won't print every fetched log.
```
root@3a5f21edeae1:/var/ossec/wodles/aws# py ./aws-s3.py -d2 -b wazuh-aws-wodle-waf -t waf 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2021/09/24
DEBUG: ++ Found new log: community-test/
DEBUG: ++ Found new log: community-test/test_waf_log
DEBUG: ++ Found new log: test_empty/
DEBUG: ++ Found new log: test_prefix/
DEBUG: ++ Found new log: test_prefix/2019/10/22/10/aws-waf-logs-delivery-stream-1-2019-10-22-10-32-48-792c6d1f-bfed-4b00-9f5e-88ce44718193
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
root@3a5f21edeae1:/var/ossec/wodles/aws# py ./aws-s3.py -d2 -b wazuh-aws-wodle-waf -t waf 
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: community-test/
DEBUG: ++ Skipping previously processed file: community-test/test_waf_log
DEBUG: ++ Skipping previously processed file: test_empty/
DEBUG: ++ Skipping previously processed file: test_prefix/
DEBUG: ++ Skipping previously processed file: test_prefix/2019/10/22/10/aws-waf-logs-delivery-stream-1-2019-10-22-10-32-48-792c6d1f-bfed-4b00-9f5e-88ce44718193
DEBUG: +++ DB Maintenance
DEBUG: +++ DB Maintenance
```

### GCP
The module is working as expected, but we discovered an error in the description of a debug message. We opened issue #10265 to fix that.
To check that the module is OK we executed the following commands and checked that every execution was fetching and processing 100 messages.

```
root@3a5f21edeae1:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s test_gcloud_blog -c /var/ossec/wodles/gcloud/credentials.json -l 1 -t 1 | tee /tmp/gcp_l
ogs_1_thread
root@3a5f21edeae1:/var/ossec/wodles/gcloud# /var/ossec/wodles/gcloud/gcloud -p wazuh-dev-258815 -s test_gcloud_blog -c /var/ossec/wodles/gcloud/credentials.json -l 1 -t 2 | tee /tmp/gcp_l
ogs_2_threads
...
...
root@3a5f21edeae1:/var/ossec/wodles/gcloud# wc -l /tmp/*
   102 /tmp/gcp_logs_1_thread
   102 /tmp/gcp_logs_2_threads
```

The +2 lines in each file are the following debug messages added by the `-l 1` parameter at the beginning and the end of the output respectively: 
``` 
gcloud_wodle: DEBUG: Setting 1 thread to pull 100 messages each
gcloud_wodle: INFO: Received and acknowledged 100 messages
```

### Azure
In progress...
