### ISSUE TITLE
Improve the logs generated during the agents registration attempts

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#10268]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/9550 in which we added new settings to configure the forced addition of agents, we identified some logs that could be improved.

When an agent registration attempt fails, it generates two `INFO` logs with this information:

```
minfo("Duplicate name '%s' (%s).", agentname, id);
minfo("Agent '%s' can't be replaced since it is not disconnected.", id);
```

And when an agent is replaced, it generates:

```
minfo("Duplicate name '%s' (%s).", agentname, id);
minfo("Removing old agent '%s'.", id); 
```

In some scenarios in which the agents could attempt to be autoregistered, it could flood the log. Because of this, we decided to improve this information being logged by unifying it in a single line to `WARNING` and `INFO` levels respectively.

```
WARN: Duplicate agent name 'X' (id YYY). Rejecting enrollment since agent ZZZ is connected.
INFO: Duplicate agent name 'X' (id YYY). Removing old agent ZZZ.
```

### DoD:

- [x] Implementation done.
- [x] Manual testing of failed registration attempts.
- [x] Manual testing of agents being replaced.
- [x] Update all the necessary Unit Tests cases.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10325 was merged.

**Comment by pereyra-m** [comment]
## Reopen

This issue is reopened to standardize the logs generated in the `local_add()` method (used for cluster, key-polling, etc.). 
There is an extra **ERROR** message that is no longer necessary, only the **WARNING** message should be printed

![key_polling_no](https://user-images.githubusercontent.com/65046601/135284783-5c74acb8-f52f-4033-99d8-2d555e64aaf7.png)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10349 was merged.
