### ISSUE TITLE
Critical Emails

### ISSUE THREAD

**Issue by sulaiman35** [wazuh/wazuh#1028]
How to send critical alerts only, critical alerts can be wrong IP ssh / portscanners / SQL Injection Attack / XSS / DoS / or any server is down.

need help.

and share complete detail of all level of alerts .

**Comment by TJOSERAFAEL** [comment]
Hi @sulaiman35,

if you know exactly what rules are you going to send, you can do that in you `ossec.conf` file on your manager:

```xml
<email_alerts>
  <email_to>you@example.com</email_to>
  <rule_id>40111, 31103, 31105</rule_id>
  <do_not_delay />
</email_alerts>
```

- Rule 40111 is for Brute force SSH attack
- Rule 31103 is for SQL Injection attack
- Rule 31105 is for XSS attack

You can search the rules in this repository https://github.com/wazuh/wazuh-ruleset
Also here you have a guide for configuring email alerts https://documentation.wazuh.com/3.x/user-manual/manager/manual-email-report/index.html

Best regards.

**Comment by sulaiman35** [comment]
Thanks
