### ISSUE TITLE
Syslog port

### ISSUE THREAD

**Issue by whois51** [wazuh/wazuh#103]
I've configured wazuh and everthing is working like charm, but...

I can't recieve syslog from cisco asa when use command lsof -P -a -i -c ossec-remoted
 
COMMAND     PID   USER   FD   TYPE  DEVICE SIZE/OFF NO
DE NAME                                               
ossec-rem 20250 ossecr    4u  IPv4 1506204      0t0  U
DP ossec.localdomain:1514

I have config like this
  <remote>                                            
                                                      
                        
                                                      
         <connection>syslog</connection>              
         <port>514</port>                             
         <protocol>udp</protocol>                     
                                                      
         <allowed-ips>192.168.60.1</allowed-ips>      
                                                      
                                                      
                                
    <connection>secure</connection>                   
    <port>1514</port>                                 
    <protocol>udp</protocol>                          
                                                      
                                                      
        <allowed-ips>192.168.10.0/24</allowed-ips>    
        <allowed-ips>192.168.10.71</allowed-ips>

192.168.60.1 is my ASA

# tcpdump -i eth0 src 192.168.60.1  an
d port 514 -vvX                                       
tcpdump: listening on eth0, link-type EN10MB (Ethernet
), capture size 65535 bytes                           
17:00:49.790138 IP (tos 0x0, ttl 254, id 5530, offset 
0, flags [none], proto UDP (17), length 154)          
    192.168.60.1.syslog > ossec.localdomain.syslog: [u
dp sum ok] SYSLOG, length: 126                        
        Facility local4 (20), Severity critical (2) 

How to enable syslog?

**Comment by vikman90** [comment]
Hi @whois51,

your configuration appears to be correct. Use this command in order to make sure that Wazuh is listening to port 514:

```
# netstat -plun | grep ":514"
```

You should see a result like:
> `udp        0      0 0.0.0.0:514             0.0.0.0:*                           5473/ossec-remoted`

If your result is correct please review your firewall configuration, in fact `tcpdump` captures traffic arriving to your system before the firewall filter, so if your firewall has port 514 closed you will see packets in `tcpdump` but they will not arrive to Wazuh.

Hope it help.

Best regards,
Victor.

**Comment by whois51** [comment]
Tested and dispite that config is ok doesn't lisen on port 514

# netstat -plun | grep ":514"      
# netstat -plun | grep ":1514"     
udp        0      0 192.168.10.139:1514     0.0.0
.0:*                           20250/ossec-remote
d

**Comment by vikman90** [comment]
Hi,

I tested your configuration (`syslog` and `secure`) on the last version (Master branch) and had no issues.

Please find any related error or warning for `ossec-remoted` at file `/var/ossec/logs/ossec.log`.

What version are you using? Please tell us if you see any strange log at the `ossec.log`.

Best regards.
