### ISSUE TITLE
Issue with ossec.conf in Windows installation

### ISSUE THREAD

**Issue by srikwit** [wazuh/wazuh#1031]
Dear Team,

I am trying to write my own Powershell script for agent installation.

However, when I modify the ossec.conf to provide my manager IP using the following Powershell command, my ossec.conf config seems to be invalid.

$ossec_conf | Out-File $config

When I manually try to provide the Manager IP using the GUI, I get the following error message:
Unable to set OSSEC Server IP Address (Internal Error on XML Write). Kindly note that the ossec.conf contains the same string used in the official code which is 

"`n<ossec_config>   <client>    <server>  <address>$($wazuh_manager)</address> </server>   </client> </ossec_config>":

https://github.com/wazuh/wazuh-api/blob/master/examples/api-register-agent.ps1 with just the manager address replaced with the actual value

This command however works:
Add-Content $config $ossec_conf

My questions are:
1. Why is the XML parser unable to parse the same string when I completely modify ossec.conf?
2. Even when I use the Add-Content command and provide my IP and I successfully connect to my manager, Why does Manager IP value in win32ui.exe still reflect as 0.0.0.0 and not as the new IP?

**Comment by albertomn86** [comment]
Hi @srikwit 

The correct XML structure should be the following:

```
<ossec_config>
  <client>
    <server>
      <address>YOUR_MANAGER_IP</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
...
  </client>
...
</ossec_config>
```
If you modify this block structure, the XML parser might not validate it.

To replace the manager IP using a Powershell script, you can use the following example:

`(Get-Content ".\ossec.conf") -replace("<address>.*</address>","<address>$server_ip</address>") | Set-Content ".\ossec.conf"`

Hope this helps.

Best regards.

**Comment by srikwit** [comment]
Hi @albertomn86 

Thanks for replying. I am using the ossec.conf format defined with the following string defined in the sample GitHub code:

"`n<ossec_config>   <client>    <server>  <address>$($wazuh_manager)</address> </server>   </client> </ossec_config>"

I am sure replace will work because it will only modify the requisite value while retaining the original XML format.

My issue is with why I am unable to completely replace the contents of ossec.conf using the Out-File command whereas appending the same string to the file works.

**Comment by albertomn86** [comment]
Hi @srikwit 

If you are using a non-english Windows version, maybe the problem is the file encoding.
Use the `-Encoding` parameter in the `Out-File` command to specify **UTF8** character encoding.

Hope this helps you.

Best regards.
