### ISSUE TITLE
Release 4.2.2 - Release Candidate 2 - Upgrade metrics - AMD64

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#10317]
### Pre-release metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #10253 |
| **Main package tests issue** | #10264 |
| **Version** | 4.2.2 |
| **Release candidate #** | RC2 |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.2-rc2 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins builds**:  https://ci.wazuh.info/job/Test_upgrade_tier/1809/

---
| System | 3.5.0 | 3.6.0 | 3.6.1 | 3.7.0 | 3.7.2 | 3.8.0 | 3.8.2 | 3.9.0 | 3.9.5 | 3.10.0 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --  
| CentOS 8 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🔴 | 🟢 | 🔴 | 🟢 |
| CentOS 7 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 6 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 5 | 🔴  | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 
| Debian 10 | 🔴  | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 |
| Debian 9   | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 32 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 31 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Focal | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Bionic | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Xenial | 🟢  | 🔴 | 🟢 | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Trusty | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🔴 |
| Amazon Linux 2 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 1 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Oracle Linux 8 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| OpenSuse Tumbleweed |  🔴  | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🟢 |
| Redhat 6 | 🟢  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 7 | 🟢  | 🟢 | 🔴 | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 8 | 🔴  | 🟢 | 🟢 | 🟢 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 |

| System | 3.10.2 | 3.11.0 | 3.11.4 | 3.12.0 | 3.12.3 | 3.13.0 | 3.13.2 | 4.0.0 | 4.0.1 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- 
| CentOS 8 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 7 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 6 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 5 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 
| Debian 10 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 
| Debian 9   | 🔴 | 🔴 | 🔴 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢  | 🟢 | 
| Fedora 32 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Fedora 31 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Focal  | 🔴 | 🔴 | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Bionic | 🟢 | 🔴 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Xenial | 🔴 | 🟢 | 🟢 | 🔴 | 🔴 | 🔴 | 🟢 | 🟢  | 🟢 | 
| Ubuntu Trusty | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🟢 | 🟢 | 🟢 | 
| Amazon Linux 2 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Amazon Linux 1 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Oracle Linux 8  | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| OpenSuse Tumbleweed | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🔴 | 🔴 | 
| Redhat 6 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Redhat 7 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 
| Redhat 8 | 🟢 | 🟢 | 🟢 | 🔴 | 🔴 | 🔴 | 🟢 | 🟢 | 🟢 | 

| System | 4.0.2 | 4.0.3 | 4.0.4 | 4.1.0 | 4.1.1 | 4.1.2 | 4.1.3 | 4.1.4 | 4.1.5 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| CentOS 8 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 7  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 
| CentOS 6 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 5 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 |
| Debian 10  | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 |
| Debian 9 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 32 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 31  | 🟢| 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Focal  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Bionic  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Xenial  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Trusty  | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 2 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 1 | 🔴 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Oracle Linux 8   | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| OpenSuse Tumbleweed | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 | 🔴 |
| Redhat 6 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 7  | 🟢 | 🟢| 🟢 | 🟢 | 🟢 | 🔴 | 🟢 | 🟢 | 🟢 |
| Redhat 8 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 

| System | 4.2.0 | 4.2.1 |
| -- | -- | -- |
| CentOS 8 | 🟢 | 🟢 |
| CentOS 7  | 🟢 | 🟢 |
| CentOS 6 | 🟢 | 🟢 |
| CentOS 5 | 🔴 | 🔴 |
| Debian 10  | 🟢 | 🟢 |
| Debian 9 | 🟢 | 🟢 |
| Fedora 32 | 🟢 | 🟢 |
| Fedora 31  | 🟢 | 🟢 |
| Ubuntu Focal  | 🟢 | 🔴 |
| Ubuntu Bionic  | 🟢 | 🟢 |
| Ubuntu Xenial  | 🟢 | 🟢 |
| Ubuntu Trusty  | 🔴 | 🔴 |
| Amazon Linux 2 | 🔴 | 🟢 |
| Amazon Linux 1 | 🟢 | 🔴 |
| Oracle Linux 8   | 🔴 | 🔴 |
| OpenSuse Tumbleweed | 🔴 | 🔴 |
| Redhat 6 | 🟢 | 🟢 |
| Redhat 7  | 🟢 | 🔴 |
| Redhat 8 | 🟢 | 🔴 |

Legend:
Test not launched: ⚫
Test failed: 🔴 
Test success: 🟢 
Need review: 🟡

**Comment by rauldpm** [comment]
## Errors --> Centos8

<details><summary>4.2.1 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134954196-2c2fdfd5-d9e8-49b9-ab81-d2b48d2704df.png)

![image](https://user-images.githubusercontent.com/14913942/134954125-60a4732b-c04e-4e85-b4ea-e522709ecfc3.png)
</details>

**Comment by rauldpm** [comment]
## Errors --> RedHat7

<details><summary>4.2.1 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134959007-f4b8de7e-4477-44ed-ac34-a5b93b98adf8.png)

</details>

<details><summary>4.1.2 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134959292-8fe1867e-77aa-4c50-bab0-b97a7d7a8cfe.png)

</details>

<details><summary>3.13.2 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134959576-215b2e5e-05b9-41d2-9c8e-bf5bbdeb67e8.png)
![image](https://user-images.githubusercontent.com/14913942/134959646-ae6fa5f9-b55b-4513-96b3-7f55cee52345.png)


</details>

**Comment by rauldpm** [comment]
## Errors --> RedHat6

No errors for now

**Comment by rauldpm** [comment]
## Errors --> Oracle Linux 8

<details><summary>4.2.1 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134970462-107fe3bb-8870-4460-89ac-1d475a34344c.png)


</details>

<details><summary>4.2.0 to 4.2.2</summary>

Unknow error. Relaunched at https://ci.wazuh.info/job/Test_upgrade/79623/

</details>

**Comment by rauldpm** [comment]
## Errors --> Amazon Linux 2

<details><summary>4.2.1 to 4.2.2</summary>

Unknow error. Relaunched at https://ci.wazuh.info/job/Test_upgrade/79624/

</details>

**Comment by rauldpm** [comment]
## Errors --> Ubuntu Trusty

<details><summary>4.2.1 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134972620-a43eddeb-79cc-45f6-addc-044419c20781.png)


</details>

<details><summary>4.2.0 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134972681-298f56da-33ae-4afc-af02-6028f95591a7.png)

</details>

<details><summary>3.13.0 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134972788-e7d0b66c-249b-4b7f-8fad-882717e91904.png)
![image](https://user-images.githubusercontent.com/14913942/134972839-ef3f960f-4a3c-44d6-b536-badb6bc1136f.png)
![image](https://user-images.githubusercontent.com/14913942/134972874-962135d9-b9fd-422b-b63b-bda1565340ed.png)

</details>

<details><summary>3.12.3 to 4.2.2</summary>

Same error as 3.13.0

</details>

<details><summary>3.12.0 to 4.2.2</summary>

Same error as 3.13.0

</details>

**Comment by c-bordon** [comment]
## Errors --> Debian 9

<details><summary>3.12.3 to 4.2.2</summary>

![Screenshot_20210927_162934](https://user-images.githubusercontent.com/64099752/134972518-e3f6c6c0-981e-4526-86c3-f5ed3e71a473.png)
![Screenshot_20210927_162955](https://user-images.githubusercontent.com/64099752/134972557-cea3f411-8751-459d-9fd9-70d3040c9866.png)
![Screenshot_20210927_163013](https://user-images.githubusercontent.com/64099752/134972600-4882230d-165e-4f1a-9b30-d31c98b6c977.png)

</details>
<details><summary>3.11.4 to 4.2.2</summary>

![Screenshot_20210927_163221](https://user-images.githubusercontent.com/64099752/134972884-6def2c17-63b0-427f-b2a7-9f4b2a595fc5.png)
![Screenshot_20210927_163447](https://user-images.githubusercontent.com/64099752/134973203-c98c6714-0f75-4786-99ce-07deb717c03e.png)
![Screenshot_20210927_163509](https://user-images.githubusercontent.com/64099752/134973250-8e796aa5-15f3-4aeb-8f4c-ddcf8e39913d.png)

</details>
<details><summary>3.11.0 to 4.2.2</summary>

![Screenshot_20210927_163619](https://user-images.githubusercontent.com/64099752/134973392-472cc848-eff0-41eb-84f3-50a75b05e790.png)
![Screenshot_20210927_163639](https://user-images.githubusercontent.com/64099752/134973439-ca741d68-efb9-46a1-87e9-15213c49d289.png)
![Screenshot_20210927_163702](https://user-images.githubusercontent.com/64099752/134973483-9cdf0b7a-7f9b-4340-8f6e-b445ee023566.png)


</details>
<details><summary>3.10.2 to 4.2.2</summary>

![Screenshot_20210927_163801](https://user-images.githubusercontent.com/64099752/134973595-cef0550a-64f7-41c2-a969-1357e9f136b2.png)
![Screenshot_20210927_163818](https://user-images.githubusercontent.com/64099752/134973630-60c5ff6d-36a6-427b-a11e-6f460a197cd1.png)
![Screenshot_20210927_163832](https://user-images.githubusercontent.com/64099752/134973672-00605d42-49a5-45d1-b5f3-46334a4605b1.png)

</details>

**Comment by rauldpm** [comment]
## Errors --> Ubuntu Xenial

<details><summary>3.13.0 to 4.2.2</summary>

Agent
![image](https://user-images.githubusercontent.com/14913942/134973586-eb80947a-b078-464e-abb3-51d47c00db53.png)
![image](https://user-images.githubusercontent.com/14913942/134973667-ca06384a-8dd9-4fe6-aed3-250c7d5ced33.png)
![image](https://user-images.githubusercontent.com/14913942/134973692-7b8c7108-f6c6-4958-bfd2-d61245799dba.png)


</details>

<details><summary>3.12.3 to 4.2.2</summary>

Agent
![image](https://user-images.githubusercontent.com/14913942/134973876-6235dbad-854c-4674-b1e8-a12dc3db6e2a.png)
![image](https://user-images.githubusercontent.com/14913942/134973949-13c04482-cf7d-43cf-b9da-e4716b393523.png)
![image](https://user-images.githubusercontent.com/14913942/134974002-63ce7efa-2929-4de1-beb1-bdecb572be5c.png)


</details>

<details><summary>3.12.0 to 4.2.2</summary>

Agent
![image](https://user-images.githubusercontent.com/14913942/134974081-99d84ebd-e12e-4130-8f4e-84ba5078fb1d.png)
![image](https://user-images.githubusercontent.com/14913942/134974115-8d4e90e5-fa38-4542-882f-526882ad0fee.png)
![image](https://user-images.githubusercontent.com/14913942/134974153-0c607aef-4b08-4fad-8852-98005985f3bc.png)

</details>

**Comment by c-bordon** [comment]
## Errors --> Ubuntu Focal

<details><summary>4.2.1 to 4.2.2</summary>

![Screenshot_20210927_164108](https://user-images.githubusercontent.com/64099752/134974062-9c1b5510-dfe8-4d8e-914a-4cae319b4f18.png)
![Screenshot_20210927_164125](https://user-images.githubusercontent.com/64099752/134974100-4399a9e3-2000-48f9-ba6d-56098ed9a622.png)


</details>
<details><summary>3.12.3 to 4.2.2</summary>

![Screenshot_20210927_164219](https://user-images.githubusercontent.com/64099752/134974254-1fd87a1d-3467-43b6-9c2a-f1d82cbecee2.png)
![Screenshot_20210927_164246](https://user-images.githubusercontent.com/64099752/134974316-b48ff197-0bd3-4e48-813c-2f5793cfcf6d.png)
![Screenshot_20210927_164306](https://user-images.githubusercontent.com/64099752/134974354-f24de561-4244-4e3f-aee1-2f2a4db74e15.png)


</details>
<details><summary>3.11.0 to 4.2.2</summary>

![Screenshot_20210927_164403](https://user-images.githubusercontent.com/64099752/134974528-19f33a07-b503-4700-b441-f0bbbdd54600.png)
![Screenshot_20210927_164429](https://user-images.githubusercontent.com/64099752/134974589-fec3a291-9abd-4d78-a6a8-b2a93269064e.png)


</details>
<details><summary>3.10.2 to 4.2.2</summary>

![Screenshot_20210927_164507](https://user-images.githubusercontent.com/64099752/134974695-45c57c8f-224c-48b0-b286-782994022728.png)
![Screenshot_20210927_164544](https://user-images.githubusercontent.com/64099752/134974793-397a6cd9-7b9e-4e9d-8fd6-d03b560cd243.png)


</details>

**Comment by rauldpm** [comment]
## Errors --> Ubuntu Bionic

<details><summary>3.11.4 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134975213-2282d6f4-6c10-4384-abd7-d72fb160005a.png)
![image](https://user-images.githubusercontent.com/14913942/134975252-599df03b-bb46-463e-af00-e62a31fea807.png)
![image](https://user-images.githubusercontent.com/14913942/134975289-4ca5b55c-5d28-4612-8d70-b3a0f1c1d3eb.png)

</details>

<details><summary>3.11.0 to 4.2.2</summary>

Same error as 3.11.4

</details>

**Comment by c-bordon** [comment]
## Errors --> Centos 7

<details><summary>4.2.1 to 4.2.2</summary>

![Screenshot_20210927_164820](https://user-images.githubusercontent.com/64099752/134975176-ba3ff1df-00ca-4bea-a20c-d0a0a9eb5f75.png)
![Screenshot_20210927_164842](https://user-images.githubusercontent.com/64099752/134975221-8a2140cd-d5bd-4917-a05d-344e38d8dd79.png)
![Screenshot_20210927_164857](https://user-images.githubusercontent.com/64099752/134975253-3026af6b-7d80-4e9f-96f7-8a6f5ecb5000.png)


</details>
<details><summary>3.10.2 to 4.2.2</summary>

![Screenshot_20210927_165001](https://user-images.githubusercontent.com/64099752/134975398-92b73e1b-ef1d-496d-8c84-d96cb31ad2c9.png)


</details>
<details><summary>3.8.0 to 4.2.2</summary>

![Screenshot_20210927_165101](https://user-images.githubusercontent.com/64099752/134975526-36ab1324-3501-4a11-85b9-9c6d90e00db1.png)
![Screenshot_20210927_165117](https://user-images.githubusercontent.com/64099752/134975553-eb2ec8c7-b295-435d-a758-75b2304196cb.png)


</details>

**Comment by c-bordon** [comment]
## Errors --> Centos 8

<details><summary>3.8.2 to 4.2.2</summary>

![Screenshot_20210927_165406](https://user-images.githubusercontent.com/64099752/134975853-88ea149e-1bdb-4698-8dd4-61218b3cf284.png)
![Screenshot_20210927_165421](https://user-images.githubusercontent.com/64099752/134975882-538d3726-bd90-4de0-8056-a6edba7d6eb3.png)


</details>

**Comment by c-bordon** [comment]
## Errors --> Centos 5

<details><summary>4.2.1 to 4.2.2</summary>

![Screenshot_20210927_165801](https://user-images.githubusercontent.com/64099752/134976429-9dc35bc1-87bf-4f68-9283-be46859d2865.png)
![Screenshot_20210927_165825](https://user-images.githubusercontent.com/64099752/134976466-be6314b0-8edd-49d7-ba04-71e64674c115.png)
![Screenshot_20210927_165842](https://user-images.githubusercontent.com/64099752/134976514-768c6064-f6f4-4bd0-a0ef-903e77af8c6b.png)


</details>

<details><summary>4.2.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.5 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.4 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.3 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.1 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.1.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.0.4 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.0.3 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.0.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.0.1 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>4.0.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.13.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.13.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.12.3 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.12.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.11.4 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.11.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.10.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.10.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.9.5 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.9.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.8.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.8.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.7.2 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.7.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.6.1 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.6.0 to 4.2.2</summary>

Same as 4.2.1

</details>

<details><summary>3.5.0 to 4.2.2</summary>

Same as 4.2.1

</details>

**Comment by rauldpm** [comment]
## Errors --> Debian 10

<details><summary>4.1.5 to 4.2.2</summary>

Agent
![image](https://user-images.githubusercontent.com/14913942/134976545-6b212ecb-7540-4e32-b41b-be721314c9ad.png)
Manager
![image](https://user-images.githubusercontent.com/14913942/134976609-89cf7bc7-8d56-44b6-8c46-fce7f3876fc0.png)


</details>

<details><summary>4.1.4 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134976672-19a0a4d8-570d-4630-a018-1a2beaf636d2.png)
![image](https://user-images.githubusercontent.com/14913942/134976708-967a3f2d-3103-4a29-86d3-11ad918c734c.png)
Agent
![image](https://user-images.githubusercontent.com/14913942/134976732-b99b139d-c5cb-4260-a979-c8db6c779465.png)
Manager
![image](https://user-images.githubusercontent.com/14913942/134976781-7a34a279-0d22-4645-8e85-c7730d1d048a.png)


</details>

<details><summary>4.1.3 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.1.2 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.1.1 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.1.0 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.0.4 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.0.3 to 4.2.2</summary>

Same error as 4.1.4
![image](https://user-images.githubusercontent.com/14913942/134977092-5f2de6bb-cf26-4303-b9da-28bfae461402.png)


</details>

<details><summary>4.0.2 to 4.2.2</summary>

Same error as 4.1.4

</details>

<details><summary>4.0.1 to 4.2.2</summary>

Same error as 4.1.4 and
![image](https://user-images.githubusercontent.com/14913942/134977244-729e8f95-7ea0-4dc8-9bf5-15a4efbc473c.png)


</details>

<details><summary>3.13.2 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134977315-eac3d06a-be5a-42a7-b1b1-c27178c10315.png)
![image](https://user-images.githubusercontent.com/14913942/134977337-6e3fcaa1-8ffe-4081-8fd4-d44c7c181b35.png)


</details>

<details><summary>3.13.0 to 4.2.2</summary>

![image](https://user-images.githubusercontent.com/14913942/134977537-b2f3e1b2-6b72-41c8-8744-d1f2442ea5d0.png)
![image](https://user-images.githubusercontent.com/14913942/134977570-adc9e904-8773-4180-ae81-5ad54e9047b9.png)


</details>

<details><summary>3.12.3 to 4.2.2</summary>

Same errors as 3.13.0

</details>

<details><summary>3.12.0 to 4.2.2</summary>

Same errors as 3.13.0

</details>
