### ISSUE TITLE
REQUEST : CISCO SYSLOGS / FORTIGATE 

### ISSUE THREAD

**Issue by mmbar1986** [wazuh/wazuh#10330]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.1 | Rules/Decoders | New/Error/Improve |

## Description

HI community , 
just asking if there is articles that describes how to integrate on WAZUH : 
- Cisco Switchs 
- Fortigate 

Thank you

**Comment by xrisbarney** [comment]
Hi @mmbar1986 ,

Below are some articles that can help you set up syslog data collection and agentless monitoring:

- https://documentation.wazuh.com/current/user-manual/capabilities/agentless-monitoring/index.html
- Monitoring network devices https://wazuh.com/blog/monitoring-network-devices-wazuh-hids/
- Also, creating custom decoders and rules for these devices https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

I hope these help you get started with using Wazuh to monitor your network devices

**Comment by mmbar1986** [comment]
Hi @xrisbarney , 
Thank you , i'll try 

Best regards

**Comment by xrisbarney** [comment]
You're welcome. 

I'll close this issue now, and if you have any more questions you can always ask via the community slack channel [here](https://wazuh.com/community/join-us-on-slack/).
