### ISSUE TITLE
Allow the new authd configurations to accept time values using minutes, hours and days for the API

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#10359]
## Description

The epic #9550 creates a new set of configurations for authd. The format **m,h,d** can be used in the `ossec.conf` file but not with the API calls.
This format must be extended to this use case too.

## DoD

- [x] Implement the parsing for **s,m,h,d** with `disconnected_time` and `after_registration_time` for the API
- [x] Validate the correct behavior of the settings

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10373 was merged.
