### ISSUE TITLE
The new disconnected_time DB field is not being propagated in a cluster for the new authd settings

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#10350]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | authd | Manager | Packages/Sources | Any |

## Description 

It was found during the development of #9550 (issue #10268) that the new setting `disconnected_time` requires a new DB field in `global.db` that is not being propagated from workers to master.

This prevents the correct `disconnected_time` to be used in the master node for agente replacement.

## DoD

- [ ] The new database column has to be propagated
- [ ] The correct behavior of the setting `disconnected_time` has to be tested in a cluster scenario
- [ ] All the required UT should be updated

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10351 was merged.
