### ISSUE TITLE
Issue: Rules 

### ISSUE THREAD

**Issue by mmbar1986** [wazuh/wazuh#10363]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.1 | Rules | New |

## Description
Hi community , 
I configured a costume rule as a test in the local_rules.xml  , i want to have an alert when the root user is logging in  , so i used the default rule 5715 and modified it  but the event is not generated in the logs . below the custom rule 
<rule id="100003" level="12">
    if_sid>5700  /if_sid>
    match>^Accepted|authenticated.$  /match>
    field name="data.dstuser">root    /field>
    description>sshd: authentication douteuse    /description>

**Comment by juliancnn** [comment]
Hi @mmbar1986 

To create a rule that generates an alert when the root user logs in via ssh, you should create a child rule of rule 5715.
When the user connects via ssh it generates a log like one of the following:

```
Oct  1 14:55:36 200-u20-dev-manager sshd[15976]: Accepted publickey for root from 192.168.3.5 port 44248 ssh2: RSA SHA256:.....
```
or
```
Oct  1 15:06:56 200-u20-dev-manager sshd[18135]: Accepted password for root from 192.168.3.5 port 44252 ssh
```

As we could see Wazuh-Logtest, both trigger the rule 5715


```bash
─# /var/ossec/bin/wazuh-logtest                                                                               130 ↵
Starting wazuh-logtest v4.2.1
Type one log per line

Oct  1 15:06:56 200-u20-dev-manager sshd[18135]: Accepted password for root from 192.168.3.5 port 44252 ssh

**Phase 1: Completed pre-decoding.
	full event: 'Oct  1 15:06:56 200-u20-dev-manager sshd[18135]: Accepted password for root from 192.168.3.5 port 44252 ssh'
	timestamp: 'Oct  1 15:06:56'
	hostname: '200-u20-dev-manager'
	program_name: 'sshd'

**Phase 2: Completed decoding.
	name: 'sshd'
	parent: 'sshd'
	dstuser: 'root'
	srcip: '192.168.3.5'

**Phase 3: Completed filtering (rules).
	id: '5715'
	level: '3'
	description: 'sshd: authentication success.'
	groups: '['syslog', 'sshd', 'authentication_success']'
	firedtimes: '1'
	gdpr: '['IV_32.2']'
	gpg13: '['7.1', '7.2']'
	hipaa: '['164.312.b']'
	mail: 'False'
	mitre.id: '['T1078', 'T1021']'
	mitre.tactic: '['Defense Evasion', 'Persistence', 'Privilege Escalation', 'Initial Access', 'Lateral Movement']'
	mitre.technique: '['Valid Accounts', 'Remote Services']'
	nist_800_53: '['AU.14', 'AC.7']'
	pci_dss: '['10.2.5']'
	tsc: '['CC6.8', 'CC7.2', 'CC7.3']'
**Alert to be generated.


```

Since the rule engine uses a tree structure, when a rule matches, it will look for child rules. If it does not have or does not match, it will return the last rule that matched.
On the other hand, you can see that the `user` field is decoded with the name `dstuser` which is an alias to the `user` field ([doc here](On the other hand, you can see that the user field is decoded with the name dstuser which is an alias to the user field (doc here), so the rule would be as follows:
)), so the rule would be as follows:



```xml
  <rule id="100001" level="5">
    <if_sid>5715</if_sid>
    <user>root</user>
    <description>root user logged via ssh</description>
    <group>authentication_success,sshd,</group>
  </rule>
```

Finally we test our custom rule in Wazuh-Logtest:

```bash
╰─# /var/ossec/bin/wazuh-logtest                                                                               130 ↵
Starting wazuh-logtest v4.2.1
Type one log per line

Oct  1 15:06:56 200-u20-dev-manager sshd[18135]: Accepted password for root from 192.168.3.5 port 44252 ssh

**Phase 1: Completed pre-decoding.
	full event: 'Oct  1 15:06:56 200-u20-dev-manager sshd[18135]: Accepted password for root from 192.168.3.5 port 44252 ssh'
	timestamp: 'Oct  1 15:06:56'
	hostname: '200-u20-dev-manager'
	program_name: 'sshd'

**Phase 2: Completed decoding.
	name: 'sshd'
	parent: 'sshd'
	dstuser: 'root'
	srcip: '192.168.3.5'

**Phase 3: Completed filtering (rules).
	id: '100001'
	level: '5'
	description: 'root user logged via ssh'
	groups: '['local', 'syslog', 'sshd', 'authentication_success', 'sshd']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.


```

Please let me know if this was helpful.
Regards,
 Julian

**Comment by mmbar1986** [comment]
hi @juliancnn 
Thank you so much for the detailed explaination  , it's just what i needed  !! 

Best regards

**Comment by juliancnn** [comment]
Glad to hear that! :smile:. As this is solved I will close the issue. 
Feel free to create new issues for new concerns.

Thank you for using Wazuh!
Best regards!

**Comment by juliancnn** [comment]
Glad to hear that! :smile:. As this is solved I will close the issue. 
Feel free to create new issues for new concerns.

Thank you for using Wazuh!
Best regards!
