### ISSUE TITLE
Add API URI parser unit tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10393]
Our current unit tests do not include any coverage for the API URI parser.

This issue aims to add new python unit tests for the API encoder located at [api/uri_parser.py](https://github.com/wazuh/wazuh/tree/master/api/api/uri_parser.py). The new unit tests should cover as much of the code as possible.

**Comment by Kondent** [comment]
## Update
I have completed this test module with all covered, however I will do an overall review before opening its PR.

Regards,
Alexis
