### ISSUE TITLE
Improve the configuration options for Authd during agents replacement - Coverity

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#10400]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/9550 we implemented a new set of configurations for the agents' enrollment mechanism that instructs Authd how to behave when an agent addition attempt is performed. This required many changes in the code so, a Coverity analysis should be performed over the implementation.

### DoD
- [x] Run the Coverity scan tool over the branch
- [x] Fix any issue found
- [x] Run the scan again to check the errors were fixed

**Comment by pereyra-m** [comment]
## Coverity results

The scan reported two new issues
![coverity](https://user-images.githubusercontent.com/65046601/135930418-4856fc0e-7e4a-42a8-85f0-3b289f8e8c2c.png)

One of them corresponds to another development and will be fixed in a different branch
```
** CID 240346:    (RESOURCE_LEAK)
/wazuh_modules/vulnerability_detector/wm_vuln_detector.c: 5540 in wm_vuldet_generate_win_cpe()
```

And the other one is a memory leak that will be fixed because it's related to the changes in this epic
```
** CID 240347:    (RESOURCE_LEAK)
/os_auth/local-server.c: 250 in local_dispatch()
```

**Comment by DProvinciani** [comment]
@pereyra-m the pull request with the fix was merged. We will close the issue after having a confirmation of the fix with a new Coverity scan.

**Comment by pereyra-m** [comment]
## Scan re-run

The Coverity scan was launched again to verify the fix

![coverity](https://user-images.githubusercontent.com/65046601/136046489-3117c30f-0b91-4342-8881-9e879f0df25d.png)

The remaining issue doesn't correspond to this implementation and will be fix in another branch.

**Comment by DProvinciani** [comment]
Closing the issue as the fix was validated.
