### ISSUE TITLE
Open SCAP support for Ubuntu 18.04

### ISSUE THREAD

**Issue by MaxVerro** [wazuh/wazuh#1040]
Is the support of open SCAP for Ubuntu 18.04 planned for the near future? We have upgraded some of our servers to 18.04 but the Open SCAP module is not working. It does not generate any alerts.

**Comment by TJOSERAFAEL** [comment]
Hi @MaxVerro ,

currently there is no xml profile released by open SCAP for Ubuntu 18. The latest profile open SCAP released is for Ubuntu 16. As soon as they release the profile, we will add it to our repository.

Best regards.

**Comment by MaxVerro** [comment]
This is what I tough. I've searched on the open SCAP repository and could find anything for Ubuntu 18.04 LTS. 

You can close this issues I was just making sure I hadn't miss anything.

Thank you!

**Comment by TJOSERAFAEL** [comment]
Thank you!
