### ISSUE TITLE
Windows Rootcheck Not Completing When Syscheck Enabled

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#1041]
(Edit: Just tested v3.4.0 and the rootcheck started running after a few minutes) This can be closed and considered resolved.

I'm testing the the default Windows agent (ossec.conf) file that was created with 3.3.1-1, and when syscheck is enabled the rootcheck never runs. It identifies the following in the agent logs, but the rootcheck never actually runs/completes:

2018/08/01 11:50:28 rootcheck: DEBUG: Starting ...
2018/08/01 11:50:28 rootcheck: INFO: Started (pid: 12924).

If I disable the syscheck then the rootcheck completes correctly right away. Has anyone ran into this issue?

Running the agent on Windows 10
Running wazuh-manager on Ubuntu 16.04

'''
  Status:     Active

   Operating system:    Microsoft Windows 10 Enterprise [Ver: 10.0.17134]
   Client version:      Wazuh v3.3.1 / ######
   Shared file hash:    #####
   Last keep alive:     Wed Aug  1 12:13:40 2018

   Syscheck last started  at: Wed Aug  1 11:51:31 2018
   Rootcheck last started at: Unknown
'''

**Comment by vikman90** [comment]
Hi @Justangatang,

Indeed, both Syscheck and Rootcheck run in the same process. The Syscheck scan runs first and when it finished, Rootcheck starts.

We have a PR to fix this issue: https://github.com/wazuh/wazuh/pull/991.

Best regards.
