### ISSUE TITLE
OSSEC command Result

### ISSUE THREAD

**Issue by sulaiman35** [wazuh/wazuh#1042]
How to get complete output of OSSEC commands in readable format which runs on all agents.

**Comment by TJOSERAFAEL** [comment]
Hi @sulaiman35,

you can view the complete output of a command by changing the format to `full_command`, for example in your **ossec.conf** file:

```xml
 <localfile>
    <log_format>full_command</log_format>
    <command>last -n 20</command>
    <frequency>10</frequency>
  </localfile>
```

Best regards.

**Comment by sulaiman35** [comment]
I wanted to have completed out put of all those commands which are executed by wazuh (df -h, sed etc)

**Comment by TJOSERAFAEL** [comment]
Hi @sulaiman35 ,

if you want to see the complete output you can use the` <log_format>full_command</log_format>` for each command that you want to in your `/var/ossec/etc/ossec.conf` file.

If this is not what you want to achieve, please clarify your question.

Best regards.
