### ISSUE TITLE
Fix agent ID limit issues

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#10447]
Hello team,

Currently, we are using 8 digits as a limit to be used for the Agent IDs. In an ephemeral environment, this may lead to issues if we reach this limit.

We should study increasing the limit or considering an option for reusing IDs.

Regards,

Miguel Casares

**Comment by GGP1** [comment]
## Limit not working

I was able to insert an agent with and ID of 10 digits through the API.

Endpoint: `POST /agents/insert`

<details><summary>Body</summary>

```json
{
  "id": "1234567890",
  "name": "test",
  "ip": "any"
} 
```

</details>

<details><summary>Response</summary>

```json
{
	"data": {
    	"id": "1234567890",
    	"key": "MTIzNDU2Nzg5MCB0ZXN0IGFueSBlZWE0MjAzMGFhMjc3MWUwOTk1NTJiNzZkZGY1NGZkNWI5YzM5ZGNhMTRiYmI5NTQ3N2FjNTYwMTViNDMzNjEy"
	},
	"error": 0
}
```

</details>

And I could validate with `GET /agents` that it indeed exists.

<details><summary>Response</summary>

```json
{
	"data": {
    	"affected_items": [
        	...
        	{
            	"registerIP": "any",
            	"status_code": 0,
            	"group_config_status": "not synced",
            	"id": "1234567890",
            	"node_name": "unknown",
            	"name": "test",
            	"status": "never_connected",
            	"dateAdd": "2024-04-24T16:05:06+00:00",
            	"ip": "any"
        	}
    	],
    	"total_affected_items": 2,
    	"total_failed_items": 0,
    	"failed_items": []
	},
	"message": "All selected agents information was returned",
	"error": 0
}
```

</details>

We should review whether all the agent resources were created correctly and why it is stored in the `wazuh-db` database if the ID was longer than permitted.
