### ISSUE TITLE
SPIKE - Packages information gathering

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#10451]
## Description
This issue aims to double-check the feasibility of gathering packages information from an AIX OS. After this SPIKE the corresponding US will be created in order to scope the specific work needed to be done.

## DoD
- [x] Check how to get packages information
- [ ] Document the learning acquired.

**Comment by Dwordcito** [comment]
Packages are stored and installed with RPM.
rpm -qai should be used, as the fallback mechanism if the rpmv4 database does not exist (may have been updated in aix 6.1), in this way we contemplate the reading of packages for both versions 6 and 7 of AIX.

for rpmv4 reading, we are currently using berkeleydb reading, which changed from 4.16 as ndb is now used as rpm's backend.
The optimal thing is to replace the direct reading by the use of rpmlib, which makes selection of the rpm backend.

AIX 6.1 use RPMv3 (last version 3.0.6 launched in 2001) as default version.
AIX 7.X use RPMv4 as default version.

**Comment by Dwordcito** [comment]
RPMv4 AIX example for development.

[Packages.zip](https://github.com/wazuh/wazuh/files/7315858/Packages.zip)
