### ISSUE TITLE
SPIKE - OS information gathering

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#10454]
## Description
This issue aims to double-check the feasibility of gathering OS information from an AIX OS. After this SPIKE the corresponding US will be created in order to scope the specific work needed to be done.

## DoD
- [x] Check how to get OS information
- [x] Document the learning acquired.

**Comment by Dwordcito** [comment]
We are already obtaining this information through uname.

![image](https://user-images.githubusercontent.com/14300208/136676416-42831c39-e683-48d2-aff0-624c4f4d98e4.png)
