### ISSUE TITLE
SPIKE - Ports information gathering

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#10452]
## Description
This issue aims to double-check the feasibility of gathering ports information from an AIX OS. After this SPIKE the corresponding US will be created in order to scope the specific work needed to be done.

## DoD
- [x] Check how to get ports information
- [x] Document the learning acquired.

**Comment by Dwordcito** [comment]
Example to get ports information from AIX 6 and 7

[ports.zip](https://github.com/wazuh/wazuh/files/7316550/ports.zip)
