### ISSUE TITLE
Wazuh-Agent: Critical: (1226) Error reading XML file 'ossec.conf' (line 0)

### ISSUE THREAD

**Issue by k1ngk005** [wazuh/wazuh#10536]
I am getting the error above. New clean build WIn 10 VM wazuh-agent-4.2.3.1. Even did a manual install and still, I get this error message in the ossec file. Tried 3 different clean Win 10 VM builds but I get the same error on all 3?
Trying to connect to Wazuh server version 4.2.3

**Comment by amernet** [comment]
Hello @JcabreraC , I also run into the same error message after editing the ossec.conf in my Mac.
I followed the info from this thread.
https://groups.google.com/g/wazuh/c/BY2dKhk5ais

Thanks!
[ossec.txt](https://github.com/wazuh/wazuh/files/11328841/ossec.txt)
