### ISSUE TITLE
Add extra information to AWS event location for CloudwatchLogs

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#10539]
We need to add more information to the current event location for the AWS CloudWatchLogs module. 

As stated in https://github.com/wazuh/wazuh/issues/9725, the final solution should include adding `cloudwatchlogs` to the source field for the event. However, and taking into account the current decoders and rules design, doing so would completely negate the actual Wazuh ruleset for said events.

In this case, and while we work towards a definitive solution for future Wazuh releases, we propose to modify the location header, currently being `Wazuh-AWS` for all AWS events to `Wazuh-AWS-CloudWatchLogs`. By doing so we allow the creation of Wazuh ruleset and custom rules that include the `<location>` tag.

The header is being set in: https://github.com/wazuh/wazuh/blob/f20c2c746a776aab573850b354a117c50abf42eb/wodles/aws/aws_s3.py#L151

We should override the header for the AWSCloudWatchLogs class:
https://github.com/wazuh/wazuh/blob/f20c2c746a776aab573850b354a117c50abf42eb/wodles/aws/aws_s3.py#L2553

**Comment by aglarendil** [comment]
I suggest that it be determined simply by providing an additional flag to CW wodle, i.e. "line_output" (default: true) or "json_output" (default: false). In the case when we enable json output, we simply format message with additional fields.
