### ISSUE TITLE
Update unit tests for GCP-PUBSUB module

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#10534]
# Description

The unit tests for the `gcp-pubsub` module need to be expanded to increase the coverage for the `wm_gcp_pubsub_run` and `wm_gcp_pubsub_read` functions. Here are the details about the missing coverage for these functions:

**wm_gcp_pubsub_run**

![imagen](https://user-images.githubusercontent.com/39765143/137368459-17313aae-2a1b-4f06-8630-491b250d0e8b.png)

![imagen](https://user-images.githubusercontent.com/39765143/137368483-8e36ed6b-23f1-4596-a763-44ce23a5c9b3.png)

**wm_gcp_pubsub_read**

![imagen](https://user-images.githubusercontent.com/39765143/137368645-8ed7885f-2e22-4bcc-a9f8-d8251928a18b.png)

![imagen](https://user-images.githubusercontent.com/39765143/137368650-c576be5f-5fd1-4239-ae02-d572d257d858.png)

![imagen](https://user-images.githubusercontent.com/39765143/137368658-0822a5b3-bbaf-488d-8181-6d11d7f260bf.png)

**Comment by TomasTurina** [comment]
Added in https://github.com/wazuh/wazuh/pull/9279/commits/099810a857b1ebc4cc3135a72b99aaefac92cd0a and https://github.com/wazuh/wazuh/pull/9279/commits/e4d6222e241d4202ed7ef97caabd336303cac9b5
