### ISSUE TITLE
Wazuh Issue with e-mail.

### ISSUE THREAD

**Issue by moodstory** [wazuh/wazuh#10560]
Hi there,

I'm using Wazuh with ELK stack.
Everything is fine with alerting system.
I have two issues with emaling atm.

First;

I want to get email from specific server with 60109 rule.
But whenever this rule triggers i get more than one email with 60110 and 60111 rules.
Rules are level 8.

Part of my config is below,

<ossec_config>

<jsonout_output>yes</jsonout_output>
<alerts_log>yes</alerts_log>
no
<logall_json>no</logall_json>
<email_notification>yes</email_notification>
<email_from>mysender.com</email_from>
<smtp_server>mysmtp.com</smtp_server>
<email_maxperhour>12</email_maxperhour>
<email_log_source>alerts.log</email_log_source>
<agents_disconnection_time>10m</agents_disconnection_time>
<agents_disconnection_alert_time>0</agents_disconnection_alert_time>

<email_alerts>
<email_to>mymailaddress.com</email_to>
<rule_id>60109</rule_id>
0
<event_location>MyserverLocation</event_location>
<do_not_delay />
</email_alerts>

<log_alert_level>3</log_alert_level>
<email_alert_level>8</email_alert_level>
Second;

I want to change alert email template.
Its fine for me but too complicated for managers. For example: when account created wazuh sends email with all paramaters about account. But they want to see only "who created" and "Name of the account"

Is there any way to make it simple ?

BTW Wazuh is great solution.
There is no way to tell how wonderfull job you did.

Thanks for your help.

**Comment by jnasselle** [comment]
Hi @moodstory !

I am glad you are happy with Wazuh! My response between lines:

> But whenever this rule triggers i get more than one email with 60110 and 60111 rules.
> Rules are level 8.

`email_alert_level` option is part of [Generic email options](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html#generic-email-options), allowing to simply change overall configuration. In this case, setting it to `8` will create email alerts to **every** alert with level equal or greater than 8, causing that both mentioned rules (60110, 60111) trigger those alerts.
If you meant to get only alerts for `60109` you should
- Set `email_alert_level` to the higher possible value (16) to avoid any email alert
- [Force a alert by email]( https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html#force-forwarding-an-alert-by-email) for 60109

> I want to change alert email template.
> Its fine for me but too complicated for managers. For example: when account created wazuh sends email with all paramaters about account. But they want to see only "who created" and "Name of the account"
> 
> Is there any way to make it simple ?

At this moment, email alerts cannot be configured without editing the source code.
Alternatively, you can use a custom integration (I recommend you to have a look at this [blogpost](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/)) and use a python script that gets the alerts and send them.

Regards,
Nico
