### ISSUE TITLE
Unable to install from CentOS repo - HTTP 403

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#106]
Using repo config as described here: https://documentation-dev.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#adding-the-wazuh-repository

Getting the following error:

```
http://packages.wazuh.com/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden
```

**Comment by jlruizmlg** [comment]
Hi @rossengeorgiev which OS are you using? 

We have two different repositories, one for Redhat and other for CentOS (the baseurl is different, one has ```el``` the other ```rhel```), also all our URL's are with https.

CentOS

```
[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=CentOS-$releasever - Wazuh
baseurl=https://packages.wazuh.com/yum/el/$releasever/$basearch
protect=1
```

Redhat

```
[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=RHEL-$releasever - Wazuh
baseurl=https://packages.wazuh.com/yum/rhel/$releasever/$basearch
protect=1
```



thanks!.

**Comment by rossengeorgiev** [comment]
Hi @jlruizmlg I'm on CentOS 7, and I should be on the right one

**Comment by jlruizmlg** [comment]
hi @rossengeorgiev, can you paste here your repository?

Your error seems like you are using a ```https``` URL.


**http**://packages.wazuh.com/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 403 - Forbidden

**Comment by rossengeorgiev** [comment]
This is what I have:

```
# cat /etc/yum.repos.d/wazuh.repo

[wazuh]
protect=1
file=/etc/yum.repos.d/wazuh.repo
key_url=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
baseurl=http://packages.wazuh.com/el/$releasever/$basearch
clean_file=1
gpgcheck=1
name=CentOS-$releasever - Wazuh
```

**Comment by jlruizmlg** [comment]
Hi @rossengeorgiev, i think we have the error:

 if you take a look from the ```baseurl``` line,  you have:

```
baseurl=http://packages.wazuh.com/el/$releasever/$basearch
```

and should be

```
baseurl=https://packages.wazuh.com/yum/el/$releasever/$basearch
```

After https://packages.wazuh.com you need to add ```yum```, in systems like Debian or Ubuntu we add ```apt``` instead of ```yum```

can you check this please?

thanks!

**Comment by rossengeorgiev** [comment]
That was it. I feel like a idiot now. It was in fact missing `yum` from the path. Apologies for this silly issue and thank for the help.

**Comment by jlruizmlg** [comment]
@rossengeorgiev no problem! happy to help and it's monday for me too! :)

**Comment by rossengeorgiev** [comment]
Quick question, is any release date set for wazuh 2.0 ?

**Comment by jlruizmlg** [comment]
Yes!, Today!!
![screen shot 2017-04-24 at 10 41 57 am](https://cloud.githubusercontent.com/assets/13950509/25342688/bc29b884-28da-11e7-9ad1-2a77eba3543b.png)

**Comment by rossengeorgiev** [comment]
Monday Monday Monday

**Comment by jlruizmlg** [comment]
@rossengeorgiev you can start to use https://documentation.wazuh.com.
