### ISSUE TITLE
Ignore rules if dependant rule is missing when using the "overwrite" option

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#10614]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Analysisd | Manager | any | Linux |

As requested on #10244, this issue aims to prevent Analysisd from rejecting the manager startup when creating a rule and using the [rule's "overwrite" option](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#rule) if the dependant rule is missing. At the moment, if trying to overwrite an unexistent rule, the manager won't start.

The new implementation will discard the new rule when the dependant rule is missing.

Best Regards,

Mariano Koremblum

**Comment by JcabreraC** [comment]
This issues is closed in favor of https://github.com/wazuh/wazuh/issues/10244
