### ISSUE TITLE
Wazuh API Errors in a large environment

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#10625]
|Wazuh version|Component|
|---|---|
| 4.2.3 | Wazuh API |

Hello Team,
We are experiencing some issues regarding the API, the environment is big and our SplunkApp for Wazuh is giving us some random errors and it is unable to connect with the API.
### Environment
- Nodes: `20` Wazuh Managers
- Agents: `260k+` Registered | `80k+` Active

### Logs
These are the logs from the Splunk App.
```
10-14-2021 18:54:06.654 +0000 ERROR HttpListener [27916 TcpChannelThread] - Exception while processing request from <IP_ADDRESS>:39788 for /services/streams/search?sh_sid=_c21hcmFtLnN1QHNhbGVzZm9yY2UuY29t_c21hcmFtLnN1QHNhbGVzZm9yY2UuY29t__SplunkAppForWazuh__RMD5c161683b6f2f8ad7_1634237548.136: Connection closed by peer
```
Wazuh API errors:
```
2021/10/14 16:49:12 ERROR: Timeout executing API request
```
Cluster log errors:
```
2021/10/21 17:51:59 ERROR: [Worker <worker-name>] [Main] Error in synchronization process: Error 3016 - Received an error response: b'Error sending request: timeout expired.'
2021/10/21 17:51:59 ERROR: [Worker <worker-name>] [Main] Error in synchronization process: Error 3016 - Received an error response: b'Error sending request: timeout expired.'
2021/10/21 17:51:59 ERROR: [Worker <worker-name>] [Main] Error in synchronization process: Error 3016 - Received an error response: b'Error sending request: timeout expired.'
2021/10/21 17:51:59 ERROR: [Local 503537] [Main] Error during connection with '503537': [Errno 32] Broken pipe.
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)

2021/10/21 17:51:59 ERROR: [Local 279274] [Main] Error during connection with '279274': [Errno 32] Broken pipe.
  File "/u01/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
```
Wazuh logs:
```
2021/10/21 17:41:48 wazuh-db: ERROR: at run_worker(): OS_SendSecureTCP(18): Broken pipe (32)
```

I hope this information could be helpful.
Thank you in advance.

**Comment by Kondent** [comment]
## Update

We discussed this situation with the team. The main problem here is strictly overload and from there more troubles arise.
* Broken Pipe - Errno 32.
* API timeout.
* Cluster timeout - Error 3016

We currently have certain improvements at our roadmap to take care of a situation like this. It's the case of the following issue: [Improve distributed cluster and API performance: multi-process](https://github.com/wazuh/wazuh/issues/8251).

For this particular case, we thought of some possible solutions to amend this behavior:

* **Customize cluster default values:**
Adjust timeout values and periodicity of synchronization tasks according to the environment size.
It's well known that cluster tasks will take more time to finish, but they will end successfully.

* **Remove inactive agents:**
Review all inactive agents and evaluate which can be removed. For instance, remove agents which have been disconnected for a month.

A more complex but possible solution could be redesigning and splitting this Wazuh Environment in two, separating workers and agents and reducing overload at manager side.

Regards,
Alexis.
