### ISSUE TITLE
Vulnerability detector does not detect manual changes in cpe_helper file.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#10631]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0 | Vulnerability Detector | Manager | All | Windows |
# Description

For packages like PuTTY 0.74, WinRAR 4.20 among others, we found that adding entries in the `cpe_helper.json` file does not suffice to update the information in the cve.db with that recently added data. 
We must make think to Vulnerability Detector that the cpe_helper.json is updated with new information by modifying the `timestamp` value in the `metadata` table to differ from the `update_date` field in the cpe_helper.json.

It is worth mentioning also, that any changes added in the cpe_helper.json file will be lost once the manager is upgraded. 

# Steps to reproduce it

- Install a package that needs to use the cpe_helper dictionary. 
- Update the entry in **/var/ossec/queue/vulnerabilities/dictionary/cpe_helper.json**.
- Change the `timestamp` value in `metadata` table to a different value than `update_date` in the cpe_helper.json` file.
- Perform a vulnerability detector scan. The timestamp should be now set equal to the `update_date` and the cpe_helper tables in cve.db should have the new information.

**Comment by sebasfalcone** [comment]
## Won't fix
This feature was deprecated in 4.8.0
