### ISSUE TITLE
Add custom object hook to decode at api/decoder.py

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#10659]
We need to add a way to decode a JSON to `object` at `api/api/encoder.py` since we only have a way to encode. In other words we need an `object_hook` to be used with `json.loads`.
Due to another development, we already have a working object hook for this scenario that should be reviewed and probably refactored.

https://github.com/wazuh/wazuh/blob/a1b044b5c219b03f78d710653e8b9d39fefbb618/api/api/test/test_encoder.py#L13-L19

This issue aims to be similar to the object hook implemented for `WazuhJSONEncoder` at `framework/wazuh/core/cluster/common.py`.
https://github.com/wazuh/wazuh/blob/a1b044b5c219b03f78d710653e8b9d39fefbb618/framework/wazuh/core/cluster/common.py#L1100-L1133

Regards,
Alexis

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-5b4dd684c93e4717b2160eea/issues/wazuh/wazuh/10659?planning-poker) with ZenHub @Kondent @mcarmona99 @vicferpoy
