### ISSUE TITLE
Number of Agents and Number of TCP Session mismatch in cluster

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#10665]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.3-rev | Remoted/API | Manager | Packages | Docker |

Hello Team,
Some discrepancies were presented between the remoted stats and the number of agents. The normal behavior is that the number of TCP sessions should be similar (equal) to the number of active agents connected to the node. This is not happening in the environment at hand.
![image](https://user-images.githubusercontent.com/37050249/138969196-767538fd-18aa-4a9d-a73b-89e8f38083ec.png)
![image](https://user-images.githubusercontent.com/37050249/138969226-eb8fb480-9f73-4e6e-b9ab-c7e474d274c1.png)

### Statistics from worker-4
```
# /var/ossec/bin/cluster_control -a | grep active | grep worker-4 | wc -l
310
```
`wazuh-remoted.state` file:
```
# State file for wazuh-remoted
# Updated every 5 seconds.

# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='1092'

# Events sent to Analysisd
evt_count='11757324'

# Control messages received
ctrl_msg_count='271871'

# Discarded messages
discarded_count='0'

# Messages sent
msg_sent='367145'

# Total number of bytes received
recv_bytes='4573093116'

# Messages dequeued after the agent closes the connection
dequeued_after_close='2'
```

Remoted Stats from API:
```
{
   "data": {
      "affected_items": [
         {
            "queue_size": 0.0,
            "total_queue_size": 131072.0,
            "tcp_sessions": 1093.0,
            "evt_count": 9574194.0,
            "ctrl_msg_count": 201496.0,
            "discarded_count": 0.0,
            "msg_sent": 291618.0,
            "recv_bytes": 3737039692.0,
            "dequeued_after_close": 2.0
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "Statistical information for each node was successfully read",
   "error": 0
```

Results from cluster health:
```
         {
            "info": {
               "name": "XXXXXXX-worker-4",
               "type": "worker",
               "version": "4.2.3",
               "ip": "XXXXXXX,
               "n_active_agents": 347
            },
...
               "last_sync_agentinfo": {
                  "date_start_master": "2021-10-26 21:35:07.599492",
                  "date_end_master": "2021-10-26 21:35:09.809608",
                  "n_synced_chunks": 18
               },
               "last_keep_alive": "2021-10-26 21:34:18.713787"
            }
         },
```
*The differences between the cluster control command and the cluster health in the API are recognized because the API call took some time to complete.
The question here is what we have more than 1000 TCP Sessions in remoted and only more than 300 agents active?
Thank you in advance.

**Comment by TomasTurina** [comment]
Hi @dariommr,

We need more information to verify if this is a problem.

Could you please send the status of all agents?

**Comment by TomasTurina** [comment]
Related to: https://github.com/wazuh/wazuh/issues/12776

**Comment by vikman90** [comment]
Closing this issue as we think it got fixed by https://github.com/wazuh/wazuh/issues/12776.
