### ISSUE TITLE
Add Windows Security Audit rules grouped by auditing categories

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#10674]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.4-rev | Rules | New |

## Description
Hello Team,
I wanted to ask you to add this set of rules. They are intended for Windows Auditing, which means in order to work properly the systems where the agent is collecting the Security Event Logs, should have enabled the [Security Audit Options](https://techcommunity.microsoft.com/t5/itops-talk-blog/step-by-step-enabling-advanced-security-audit-policy-via/ba-p/282452) 
Also, these rules are categorized based on this Article: https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/best-practices-for-securing-active-directory

And the rule level is given by these correlations:
```
High: Level 13
Medium to High: Level 10
Medium: Level 7
Low: Level 5
```

I attach the file regarding these rules: [windows-auditing-rules.txt](https://github.com/wazuh/wazuh/files/7506883/windows-auditing-rules.txt)

I think it would be great to add to these rules the MITRE ATT&CK Tactic it matches.

Thank you in advance!

**Comment by commandline-be** [comment]
excellent proposal

**Comment by ooniagbi** [comment]
https://github.com/wazuh/wazuh/pull/22276 merged!
