### ISSUE TITLE
New decoders and rules development experience

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#10681]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | analysisd | manager | - | - |

We've started to work on a new design for the decoders and rules definition syntax to ease its development, increase its expressiveness and robustness.

This work will impact in other Wazuh components, which will be adapted to accommodate the identified requirements.

The proposal design document of this initiative has been [published ](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit?usp=sharing) on Google Docs. It is an early draft and will have deep modifications over time. Also, this document is not a promise about what will get done or how, but a way to work on the issue and generate the necessary feedback.

We can use this issue to discuss the proposal. Also, we will link the related issues  when they start appearing.

**Comment by BonAtd** [comment]
Hey @gdiazlo i have quesion about DD - this GoogleDocs is still relevant ? or maybe do youu have new, im very interestig :)
Thanks for your work
