### ISSUE TITLE
Specific custom rule to an agent 

### ISSUE THREAD

**Issue by mmbar1986** [wazuh/wazuh#10687]
|4.2.1| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | Rules | New |

## Description

Hi , 
I juste want to know how to create a specific custom rule to an agent 
Thank you

**Comment by Spades0** [comment]
Hello,

For custom rules for an agent, you can try using the `<location>` tag. This tag is sort of a hydrid header that contains not just where the logs is coming from but also other data like hostname and ip address. Take a look at the example below,
```
<rule id="2502" level="10">
    <match>more authentication failures;|REPEATED login failures</match>
    <description>syslog: User missed the password more than one time</description>
    <var name="agnt">workstation1</var>
    <location>$agnt</location>
    <mitre>
      <id>T1110</id>
    </mitre>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.8,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
``` 

This rule will therefore work for only agent - workstation1. You can also take a look at this link with similar issue - https://groups.google.com/g/wazuh/c/tNL2X0VgLlM/m/Pq565uEuAgAJ

Best Regards!

**Comment by mmbar1986** [comment]
Hi @Spades0 , 
Thank you so much , it's working now !!

Best regards
