### ISSUE TITLE
Remove unnecesary variable present in the `worker.py` file

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh#10688]
Hi team,

Previously, in the method `sync_agent_info`, which belongs to the WorkerHandler class a variable called `synced` was used in order to decrease the retrieval time to 1 second whenever it was set to False. However, this variable is no longer in use. 

We will have to determine whether this functionality will be used in the future or its use can be self-defeating. In the latter case, we will have to find all its uses and remove them completely. 

 Link to the code: [https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/worker.py](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/worker.py)

The mentioned method and variable:
https://github.com/wazuh/wazuh/blob/1b25ae1caec50b39368994f72750d59eeafc3820/framework/wazuh/core/cluster/worker.py#L629-L657

**Comment by davidjiglesias** [comment]
To be fixed in #10627
