### ISSUE TITLE
Add SCA Policy for HP-UX B.11.31

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#10696]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.3-rev | SCA | Agent | Packages | HP-UX B.11.31 |

Hello Team,
I am reaching you with this request for Security Assessment Policies for HP-UX B.11.31.

The only document I found is this, and it is from 2009 and for version 11i: https://www.cisecurity.org/wp-content/uploads/2017/04/CIS_HP-UX_11i_Benchmark_v1.5.0.pdf

I hope this could be helpful.

There will be two different policies for the same OS, one will use the bastille tool from HP, the other one will use standard UNIX commands

**Comment by jcruzlp** [comment]
Branch for tracking the changes and progress: https://github.com/wazuh/wazuh/tree/10696-hpux-sca

**Comment by maumrsms** [comment]
Hello team,
I've tried to add the policies worked here but they don't seem to work:
![image](https://user-images.githubusercontent.com/29696136/152064399-7e2a24f8-3482-4346-a61e-138329848833.png)
![image](https://user-images.githubusercontent.com/29696136/152064407-67dee933-7190-424b-972c-1e5d507f8349.png)
![image](https://user-images.githubusercontent.com/29696136/152064429-68c83408-e346-478a-a23a-396307b6bd7d.png)
![image](https://user-images.githubusercontent.com/29696136/152064444-dbc397fe-4d21-4b54-bb97-31355146d9de.png)

Now checking the rules I noticed we're using some Bastille related files. For example:
![image](https://user-images.githubusercontent.com/29696136/152065889-75efc2e1-1e5c-4a07-888d-fad46a82a994.png)

I haven't seen any mention about this nor its configuration (I'm not even sure if Bastille comes out-of-the-box in HP-UX).
I imagine that some specific configuration would be needed on it too (files ownership in `/var/opt/sec_mgmt/bastille/log/Assessment` at least)
Could you please provide more information about this?

**Comment by maumrsms** [comment]
Hello team,

I've just confirmed that this solution requires Bastille to be installed in `/opt/sec_mgmt/bastille/` for the Agent to be able to create it source files in `/var/opt/sec_mgmt/bastille/log/Assessment`.

I managed to replicate the situation in a different box after renaming the Bastille binary (`/opt/sec_mgmt/bastille/bin/bastille`):
![image](https://user-images.githubusercontent.com/29696136/152233559-75d1db2a-4962-4213-a497-f66189ac5187.png)
![image](https://user-images.githubusercontent.com/29696136/152233595-c69dbf19-8981-4c10-b3d7-df36038eb8fa.png)
With the binary out, the Agent was not able to generate iits source files in `/var/opt/sec_mgmt/bastille/log/Assessment`, thus, most items as "Not Applicable"

**Comment by sebastiandbustos** [comment]
Hello Team, 
The customer informs the HP-UX policy is working with the exception of 2 checks, here is the information provided by the customer with the checks and the errors:
```
21039
Configure IPFilter to allow only select communication.
Invalid path or wrong permissions to run command 'ipf -v -l'

21133 - Resolve "unowned" files and directories.
Timeout overtaken running command 'find / ( -nouser -o -nogroup )'
```
Please let me know.
Thank you.

**Comment by sebastiandbustos** [comment]
Jose Izquierdo provided the corrected policy, updating the issue with the file.

[cis_hpux_11i.zip](https://github.com/wazuh/wazuh/files/8100584/cis_hpux_11i.zip)
