### ISSUE TITLE
Wazuh-db doesn´t start if <database_output> is configured

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#10690]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.3 | Wazuh-db | Manager |

When **<database_output>** is configured in **ossec.conf**, **wazuh-dbd** starts to write the alerts into a custom DataBase.
When this occurs, **wazuh-db** doesn´t start. The daemon is called once in test-config mode but it isn´t called the second time to run in foreground as expected. 
It was confirmed that the daemon can be started with **/var/ossec/bin/wazuh-db -f** and is able to run and work as expected.
Thus, the problem seems to be on the service handler when handling the daemons to be started.

**Comment by MiguelazoDS** [comment]
As mentioned here 

https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-dbd.html

The `ossec-dbd` daemon was renamed to `wazuh-dbd`. When this module is configured, the `wazuh-control` tool starts `wazuh-dbd` and then, wrongly assumed that `wazuh-db` has already started.
This behavior is a consequence of a regex matching the daemon name followed by the wildcard character "\*". So in this case wazuh-db* and wazuh-dbd* are the same.

https://github.com/wazuh/wazuh/blob/master/src/init/wazuh-server.sh#L53
