### ISSUE TITLE
Wazuh Agent is missing events when Windows Event Log service is restarted/stopped

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh#10697]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.x | Log Collection | Agent | Package | Windows |

Hi team,

When restarting/stopping the Windows Event Log service the Agent stops collecting events (expected) but when the Windows Event Log service starts again the Agent doesn't collect the Events that were fired during this time. The end result is that Wazuh doesn't show that something happened to the Windows Event Log Service and this is an important security indicator of compromise.

Some screenshots:

**- Restart Windows Event Log service**

![image](https://user-images.githubusercontent.com/46934023/139508869-61a39f93-226d-402c-a9b1-234630ed669c.png)

**- Events shown on the Event Viewer:**

![image](https://user-images.githubusercontent.com/46934023/139509027-fc265501-3a17-4b22-bdcf-96587123eebb.png)

![image](https://user-images.githubusercontent.com/46934023/139509049-0bc48d29-349a-4b83-81db-8ecec406747f.png)

![image](https://user-images.githubusercontent.com/46934023/139509217-28d498f7-f2bc-4ed5-a629-48eddc6aecf0.png)

![image](https://user-images.githubusercontent.com/46934023/139509237-e0dd667d-8284-43a7-bafe-7e7ec3daf575.png)

![image](https://user-images.githubusercontent.com/46934023/139509246-db15d10a-c715-43ec-991e-d4c6fe96ea5f.png)

![image](https://user-images.githubusercontent.com/46934023/139509258-7653de71-5deb-4c5c-95f0-fa749e07a1cd.png)

![image](https://user-images.githubusercontent.com/46934023/139509276-7a22145f-a199-4b2f-b314-349804567507.png)

**- Events collected and sent to Wazuh:**

![image](https://user-images.githubusercontent.com/46934023/139509309-99e8491d-37b0-4c4e-ad33-3cf9249f6c02.png)

Regards.

**Comment by jnasselle** [comment]
Hi @orsifacundo ,

It appears to be a duplicate of # 8581.

Regards,
Nioc

**Comment by orsifacundo** [comment]
Hi @jnasselle, not really. In this case the problem is that the Log Collector is not resuming since the last events it collected so there are missing events (important events like the EventLog service being stopped).

Regards.

**Comment by jnasselle** [comment]
You are absolutely right @orsifacundo.

**Comment by vikman90** [comment]
@orsifacundo can you confirm that `<only-future-events>` is disabled in your configuration?

```xml
<only-future-events>no</only-future-events>
```

Best regards.

**Comment by orsifacundo** [comment]
Hi @vikman90, you are right! That solved the problem. I didn't take into account that this parameter is set to YES by default.

![image](https://user-images.githubusercontent.com/46934023/140573009-09e0b70a-43fe-41db-9cc6-f98181b5024a.png)

Regards.

**Comment by alexmateescu** [comment]
I know this is an old post but i am in the same situation. anybody can explain where is the future logs settings?

**Comment by adil78320** [comment]
Hi @orsifacundo 
I would like you to share with me how you do to monitor the status of services on Windows as in your screenshot Wazuh, can you share the configurations made on the agent and the rule on Wazuh
Thanks advance!

**Comment by alyvusal** [comment]
@vikman90 @orsifacundo Hi, I also on agent node same config, restartted wazuh-agent service, but still can not see logs. What I did wrong:

```xml
  <localfile>
      <log_format>syslog</log_format>
      <location>/var/log/messages</location>
      <only-future-events>no</only-future-events>
  </localfile>

  <localfile>
      <log_format>syslog</log_format>
      <location>/var/log/secure</location>
      <only-future-events>no</only-future-events>
  </localfile>

  <localfile>
      <log_format>syslog</log_format>
      <location>/var/log/maillog</location>
      <only-future-events>no</only-future-events>
  </localfile>

  <localfile>
      <log_format>audit</log_format>
      <location>/var/log/audit/audit.log</location>
      <only-future-events>no</only-future-events>
  </localfile>
```

**Comment by vikman90** [comment]
@alyvusal this issue was related to the Windows Event Log service, I would kindly ask you to open a new issue.

Please let us know which version of the agent you're using, as the log file bookmarking is relatively modern (v4.2.0): #6707.

A sample of the logs you're receiving in any of the files would also help us to figure out the cause of the issue.

You can perform these actions to debug your problem:

### Agent

Enable debug-2 for Logcollector:

```shell
echo "logcollector.debug=2" >> /var/ossec/etc/local_internal_options.conf
service wazuh-agent restart
```

We expect Logcollector to print a log like this into _etc/ossec.log_:

```
2022/11/28 10:33:19 wazuh-logcollector[4323] read_audit.c:155 at read_audit(): DEBUG: Read 1 lines from /var/log/audit.log
```

### Manager

If you confirm that the agent is picking the logs, the next step is to check if they don't become alerts because they don't match any rule or for any other cause.

For this, please enable archives in _etc/ossec.conf_:

```xml
<ossec_config>
  <global>
    <logall>yes</logall>
```

And restart the manager:
```shell
service wazuh-manager restart
```

We expect a line like this to arrive into _logs/archives/archives.log_:

```
2022 Nov 28 10:37:17 ubuntu->/var/log/audit.log type=PATH msg=audit(1660868417.986:12082): item=0 name="/usr/bin/df" inode=2097761 dev=fd:00 mode=0100755 ouid=0 ogid=0 rdev=00:00 obj=? nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
```

Hope this helps.
Best regards.
