### ISSUE TITLE
Cannot retrieve the windows package installation date if the registry does not have it

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#10703]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.x | sysinfo - syscollector | Manager - Agent | Any  | Windows |

## Description
Currently, Syscollector through the dataprovider is retrieving Windows packages information from Registry, expecting `InstallDate` as the package installation date. Apparently, this field is optional, but somehow Control Panel is showing the installation date.

Registry:
![image](https://user-images.githubusercontent.com/1791430/139734701-0c6640ca-330f-4375-8606-7ffa766d34d8.png)
Control Panel:
![image](https://user-images.githubusercontent.com/1791430/139734733-baf90d53-b543-4d6e-8938-999b54fc6113.png)

A possible solution could be using registry key last modification date with [RegQueryInfoKey](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryinfokeya?redirectedfrom=MSDN) as installation date as a fallback mechanism.

It is desirable that data provider can also report that date.

## DoD
- [x] Research about different and possible workarounds.
- [x] Propose a fix to @wazuh/data-pirates and implement it. Target branch: master
- [x] After updating the package the install_time field should be changed with the update date
- [x] Modify UT to validate applied changes
- [x] Exploratory session: different Windows versions and check it with sysinfo test tool. E2E test
- [x] Create QA issue and propose a test chart

**Comment by Dwordcito** [comment]
@vikman90 @snaow Based on the comment -> https://github.com/wazuh/wazuh/pull/14499#issuecomment-1206765876 from @MiguelazoDS, this issue it must incorporate in 4.4 to be aligned to the behavior of the install time in Microsoft applications.
