### ISSUE TITLE
Custom rules not match

### ISSUE THREAD

**Issue by PafPif22** [wazuh/wazuh#10716]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4 | Rules/Decoders | Manager/Agent | 

Hi Guys, i want to create a custon rule to detect the all mssql events on Windows.

I create a new rules in /etc/rules/custom_rules:

![image](https://user-images.githubusercontent.com/93645016/140034406-b329a6b4-01a7-454f-99d3-82c5e7abf744.png)

This rules work for event 33205, 18453 but not for 15457.
![image](https://user-images.githubusercontent.com/93645016/140034063-e678abea-5f97-41f0-90bf-35bbeb107b68.png)

I can see the 15457 event in archives.log but not in alert.json.

Someone help-me?

Thanks

**Comment by fabamatic** [comment]
Hi @PafPif22, could you share the log from archives.log?. Sanitize any data that may be risky for you before sharing.

**Comment by PafPif22** [comment]
Thank you for your advice.
I tried this, but i have an error for sid 61069 and 61070: 
![image](https://user-images.githubusercontent.com/93645016/140284846-c7a6b579-4272-428b-9e9f-e2acdb385fc8.png)

![image](https://user-images.githubusercontent.com/93645016/140283721-efdda980-3ffd-4190-b2cd-9b2968158e9b.png)

I tried to update ruleset with  "/var/ossec/bin/update_ruleset", but nothing changes.

When i remove these sid, rules not match in alert.json.

**Comment by PafPif22** [comment]
Ok, I copied the ruleset from " https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0585-win-application_rules.xml ", imported on wazuh master and worker, restart the wazuh services.
Everything works, the services start well and the alert is generated

Thanks for your help
