### ISSUE TITLE
Refactor `core/common.py` module

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#10711]
We need this module to be refactored since we're using it to store a lot of commonly used variables, constants and methods in despite of where this module is called from.

What we can do here:
* Split this module into more than one.
* Move variables and constants to the related core module.

We should investigate and analyze each scenario, or propose another solution. 

Regards,
Alexis

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-5b4dd684c93e4717b2160eea/issues/wazuh/wazuh/10711?planning-poker) with ZenHub @Kondent @mcarmona99 @vicferpoy

**Comment by Kondent** [comment]
## Issue Update
After we discussed this situation with the team, we decided that we need a refactor in this file but without splitting it into separated modules.

I'm currently designing and organizing the module, reviewing if all methods or variables are being used in wazuh.
