### ISSUE TITLE
Monitor comands in the Windows CMD or PowerShell

### ISSUE THREAD

**Issue by oliveiralive** [wazuh/wazuh#10712]
|Wazuh version| Component | Action type |
|4.2----------------| --- | --- |

Hi, i wold like to know if is possible monitor comands in the windows CMD or PowerShell
For Exemple:
`C:Windows\system32\vssadmin.exe delete shadows /all quiet`
`C:Windows\system32\wbem\wmic.exe shadowcopy delete`

I got monitor comands in linux agent with linux audit, 

In this faq says that is possible but  i'n not finded anyone step by step to windows
https://documentation.wazuh.com/current/user-manual/capabilities/command-monitoring/command-faq.html#what-are-the-command-monitoring-capabilities

Thanks

**Comment by xrisbarney** [comment]
Hi @oliveiralive,

Thank you for using Wazuh.

You can monitor powershell commands by listening for powershell events in the windows event channel. This can be done by adding the configuration below to your ossec.conf file on the agents.

```
<localfile>
    <location>Microsoft-Windows-PowerShell/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```

- Restart the agent to load the new configuration and you should begin receiving powershell events.
- You can proceed to write custom rules for these events based on what you intend to monitor.
- Here is a guide on creating custom rules https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

Please let me know if this helps. Best.

**Comment by oliveiralive** [comment]
Hi @xrisbarney, thanks for your time
I see the logs in windows event like below
![image](https://user-images.githubusercontent.com/35010493/140191046-67cde028-4bb7-489f-afae-66d1004d9f68.png)


I beliave thats now i need to create a custom rule thath take this event, but my rules while not work

![image](https://user-images.githubusercontent.com/35010493/140191214-bbc58c34-1a18-4c4d-8f28-bcb73c0b9651.png)
the `<field name="win.system.eventID">^4104$|^4688$</field>` its correct?
I beliave that the path `win.system.eventID`it's wrong

**Comment by xrisbarney** [comment]
Hi @oliveiralive ,

yes, the field name win.system.eventID is correct.

- We recommend you start your custom rules from 100000 to 120000
- Can you please confirm that the localfile configuration has been added?
- This is a link to the documentation for rules https://documentation.wazuh.com/current/user-manual/ruleset/index.html which include:
  - creating custom rules https://documentation.wazuh.com/current/user-manual/ruleset/custom.html, 
  - rules syntax https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/index.html

Please confirm that the localfile configuration has been added and let me know if this helps. Best.

**Comment by oliveiralive** [comment]
Hi @xrisbarney, i'm analizing the problem and i check that the log are not sending to manager
This is my agent localfile
![image](https://user-images.githubusercontent.com/35010493/140319534-52b7a300-dea3-410f-ab6f-104360931711.png)

This is the event that i want to get
![image](https://user-images.githubusercontent.com/35010493/140319647-b03696b3-34fa-40f1-bd37-a8b4fa9f1ea5.png)


But when i check the manager log we not can see any log comming
![image](https://user-images.githubusercontent.com/35010493/140320015-5c2fe082-c6ca-4936-a37c-50ba03581412.png)
 i can get other events normaly

do you have any idea?
Thanks a lot

**Comment by xrisbarney** [comment]
Hi @oliveiralive,

Please check if you are getting 4104 events in the archives.json

tail -f /var/ossec/logs/archives/archives.json | grep 4104

This is to be sure the events are getting sent to the manager.

**Comment by oliveiralive** [comment]
Hi @xrisbarney 
In this folder just exist archive.log
![image](https://user-images.githubusercontent.com/35010493/140333974-8ea5695d-44b1-4f84-8113-703fa62eb592.png)


i'm monitoring but the logs dont come
![image](https://user-images.githubusercontent.com/35010493/140335827-b4b38529-549c-4a8a-86df-d8788fd22ef7.png)


![image](https://user-images.githubusercontent.com/35010493/140335952-3c3afa73-abee-4f1c-adb8-697582f0ddd3.png)

**Comment by xrisbarney** [comment]
Hi @oliveiralive , 

It looks like logs the powershell logs are not being sent to the manager.

- Can you see other logs e.g login and logoff events from this particular agent?
- restart the agent after configuration changes and check for the powershell logs.
- Check the end of the Wazuh agent logs for errors and let me know if there are any.

**Comment by oliveiralive** [comment]
Hi @xrisbarney, thanks for your time,
Yeah, every time after any change i restart the windows wazuh agent, and i received any others logs normally, like login and logoff, or FIM changes, only the` <location>Microsoft-Windows-PowerShell/Operational</location>` not work

I check the agent logs and see the information **Analyzing event log 'Microsoft-Windows-PowerShell/Operational'**
But logs dont appear in the manager
![image](https://user-images.githubusercontent.com/35010493/140514444-5773c811-ce8a-4487-aab5-d913ec72734a.png)

**Comment by xrisbarney** [comment]
Hi @oliveiralive ,

Thank you for providing the log message and other details. 

Please include <logall_json>yes</logall_json> to the global section of your manager's ossec.conf and let me know if you receive logs now. Example:

```
<global>
    .
    .
    .
    <logall_json>yes</logall_json>
  </global>
```

**Comment by zizii1** [comment]
Hello @oliveiralive , do u have a write up or a doc on the steps u followed please? I m following this thread and I got lost and don't know how to troubleshoot.
