### ISSUE TITLE
Some affected items including agent IDs are not sorted in API responses in Wazuh environments without cluster

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10733]
|Wazuh version|Component|
|---|---|
| 4.2.4 | API |

Solving this issue will make `test_active_response_endpoints.tavern.yaml` stop failing in a Wazuh standalone environment.

This error was discovered in issue #10593 and explained in the comment https://github.com/wazuh/wazuh/issues/10593#issuecomment-960624241.

With a Wazuh environment with cluster disabled, the affected items including agent IDs of some API responses are not being sorted. This problem does not appear in all the endpoints' responses since some of them have their affected items sorted in their respective SDK functions.

If the cluster is enabled, the response is sorted even if there is only one Wazuh manager in that cluster configuration.

**Edit**: this error only happens in implicit requests (no agents_list given, or all given). It was discovered when using the `PUT /active-response` endpoint.

As it was said in the related issue's comment,

>This is happening due to the RBAC decorators. After the expansion of the resources, each resource value is a set with the information related to that resource. This value is stored in allow[res_id], being allow a dictionary with key resource id and value that resource value. In the following code snippet, the resource value is assigned to the kwargs that are going to be passed to the function:

> ```
> if target_param != '*':  # No resourceless and not static
> 	if target_param in original_kwargs and original_kwargs[target_param] is not None:
> 	    kwargs[target_param] = list(filter(lambda x: x in allow[res_id],
> 			                       original_kwargs[target_param]))
> 	else:
> 	    kwargs[target_param] = list(allow[res_id])
> ```

	    
>In the first case (distributed function with cluster enabled), the agent_list kwarg is the intersection of the expanded agent_list and the original agent_list passed as a kwarg. This will result in the new agents_list being a sorted list.

>In the second case (cluster disabled), the agent_list kwarg is the expanded agent_list casted to list. Therefore, we are not guaranteeing the list to be sorted, as the value expanded was a set.

The commented above is a possible solution, but we should investigate if the solution is changing that RBAC decorator or sorting the affected items in all SDK functions.

In case of changing the RBAC decorator, we should delete the sort applied to the affected items in the SDK functions only after checking that after that change to the decorator, we ensure that all the responses are being sorted (cluster and no cluster).

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I've been working on this. I got it fixed but I'm currently doing a few tests before opening its PR.
Regards,
Alexis
