### ISSUE TITLE
Add "sysname" field for Windows agents on Syscollector

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#1074]
Hi team!

The app team would like to have the `sysname` field on the `/syscollector/:agent_id/os` API call so we can show different package tables to the user depending on the agent Operating System.

This is due to the fact that the packages have very different information and we can't use the same table for both Linux and Windows packages, and the `sysname` field would help to differentiate.

This might be useful for macOS packages too.

Regards,
Juanjo

**Comment by Zenidd** [comment]
Hi @JuanjiJG,


- This [compatibility matrix](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#operating-system) in our documentation specifies that only agents installed on Linux systems return the syslog field after `/syscollector/:agent_id/os` API call.

- Output example of `/syscollector/:agent_id/os` API call on Linux agent:
```
{
  "error": 0,
  "data": {
    "os": {
      "major": "18",
      "minor": "04",
      "name": "Pop!_OS",
      "platform": "ubuntu",
      "version": "18.04 LTS"
    },
    "scan": {
      "id": 1593883646,
      "time": "2019/05/21 11:08:45"
    },
    "release": "4.18.0-16-generic",
    "architecture": "x86_64",
    "hostname": "pop-os",
    "version": "#17pop0~18.04.1-Ubuntu SMP Fri Mar 8 17:51:15 UTC 2019",
    "sysname": "Linux"
  }
}
```
- When using Windows or macOS, there are other fields that you can find out what operating system it is.


<br></br>
Best regards,

Juan Pablo Sáez
