### ISSUE TITLE
feature request : streamlining OS detection on Linux systems for improved reliability and operations

### ISSUE THREAD

**Issue by commandline-be** [wazuh/wazuh#10750]
|Wazuh version|Component|Install type|Install method|Platform|
|any|wazuh-agent|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Linux systems are easily identified by parsing **/etc/os-release** and using the ID_LIKE=`<id>` key=`<value> `pair.

ID_LIKE has a rather limited set of possible types which almost always match SCA / CIS / OpenScap profiles.

This mostly avoids having to add customisations to ossec.conf to make the unknown distro to work well with wazuh-agent.

**Comment by vikman90** [comment]
Hi @commandline-be,

Thank you for opening this feature request. However, I would need you to be more precise. I don't understand where you need to have `ID_LIKE` available.

SCA provides requirements that allow using any field of the version files (see [cis_rhel8_linux.yml](https://github.com/wazuh/wazuh/blob/bafdb03f2f29ea4791eae32da015c9a70ddcabe7/ruleset/sca/rhel/8/cis_rhel8_linux.yml#L26)). On the other hand, CIS-CAT and OpenSCAP use feed files which we do not maintain.

I wonder if you would find this data useful in the agent data (as shown in Kibana or the API). Could you please give us a use case for your request, in order for us to understand it better?

Best regards.

**Comment by commandline-be** [comment]
Hi, thanks for the follow up.

In my experience the Linux OS/distro detection is not excellent in Wazuh, this in terms of accuracy, it can be improved by reading the ID_LIKE value from /etc/os-release since this will match with the well known Linux systems (Debian, Ubuntu, RHEL FEDORA, etc) see: https://www.linux.org/docs/man5/os-release.html

For example; there is a host which has ID_LIKE=ubuntu but since it does not have Ubuntu in its name yet is based on Ubuntu the Wazuh-Manager identifies as Unix by fallback to the default.

The ID_LIKE field is actually made to address this, reading this value would simply stick to standards and avoid manual corrections to be done. These are required since falling back to the Unix profile also blocked the detection of vulnerabilities.

I hope this is adequate clarification.

**Comment by commandline-be** [comment]
From https://www.freedesktop.org/software/systemd/man/os-release.html

 ID=     A lower-case string (no spaces or other characters outside of 0-9, a-z, ".", "_" and "-") identifying the
           operating system, excluding any version information and suitable for processing by scripts or usage in
           generated filenames. If not set, defaults to "ID=linux". Example: "ID=fedora" or "ID=debian".
 
ID_LIKE= A space-separated list of operating system identifiers in the same syntax as the ID= setting. 

It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional.

Examples: for an operating system with "ID=centos", an assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate.

CPE_NAME= A CPE name for the operating system, in URI binding syntax, following the Common Platform Enumeration Specification as proposed by the NIST. This field is optional.
Example: "CPE_NAME="cpe:/o:fedoraproject:fedora:17""

**Comment by vikman90** [comment]
@commandline-be thank you for your response, I think I understand it better now.

However, as I mentioned, I think that SCA policies now work as you ask. For instance, [cis_ubuntu20-04.yml:26](https://github.com/wazuh/wazuh/blob/6531bb5a3edbf9c71863859f7a9bb56cac5a1221/ruleset/sca/ubuntu/cis_ubuntu20-04.yml#L26):
```yml
rules:
    - 'f:/etc/os-release -> r:Ubuntu'
```

This condition checks that `os-release` contains the word "Ubuntu", no matter it's in `ID=` or `ID_LIKE=`.

Anyway, we will check agents running in derivated versions of Debian or Ubuntu so that we can extend this issue with specific tasks.

Thank you.

**Comment by commandline-be** [comment]
ah, thanks for the clarification, i think i now understand the possible issue at hand why this Ubuntu derivative is not detected as Ubuntu while ID_LIKE=ubuntu

In conclusion, the ID_like=ubuntu not ID_LIKE=Ubuntu for which the lower case one is correct by the documentation shared here https://www.freedesktop.org/software/systemd/man/os-release.html

I assume based on my experience this match is case sensitive ?

```
rules:
    - 'f:/etc/os-release -> r:Ubuntu'
```

**Comment by vikman90** [comment]
@commandline-be good catch! Now, I clearly see the problem:

This is the content of _/etc/os-release_ at Ubuntu 21:10:

```sh
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish
```

Despite we need to check previous versions, "Ubuntu" appears with the first capital letter in `NAME`. On the other hand, values for `ID` and `ID_LIKE` are lowercase.

The statement `condition: all` requires all rules to be satisfied, but we can change the regex to `Ubuntu|ubuntu` , or simply `ubuntu`.

We will check this configuration and write back. Thank you very much.

Best regards.

**Comment by commandline-be** [comment]
this is now well understood and the proposal is adequate, i propose to correct this for all linux distro which adopt /etc/os-release
