### ISSUE TITLE
Please make wazuh-logtest fully reload and use the ossec.conf on disk when it is started (like ossec-logtest)

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#10752]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4 | wazuh-logtest | Manager | na | na |

Formerly, I believe the ossec-logtest tool read in the full ossec.conf configuration which included the loading of decoders, rules, and CDBs every time ossec-logtest was called.  It appears that wazuh-logtest presently just uses the ossec.conf settings as they were loaded during the most recent restart of wazuh-manager.  That means we can't use wazuh-logtest to test the affect of ossec.conf changes on event analysis.  It would be desirable to have wazuh-logtest pull in ossec.conf like before, so that we are really testing the state of the configuration+ruleset on disk rather than the state these things in memory.  Consider cases like changing the `<log_alert_level>` or various settings in the `<ruleset>` section of ossec.conf.  We should be able to test these before putting our changes to such thing into production effect.

This same issue also forces us to restart the wazuh-manager before wazuh-logtest will be able to reflect the effect of newly added CDB lists to event analysis.

Addressing this issue would make the testing experience so much more consistent.

Thanks,
Kevin

**Comment by branchnetconsulting** [comment]
Cool, I'm delighted to hear that!  I presume we'll see this in 4.3 unless any other minor 4.2.x releases appear before then.

Thanks,
Kevin

**Comment by jnasselle** [comment]
My bad! I mean v4.3.0. 

By other hand, we also add log evaluation trace output (PR #9204), also really useful feature during ruleset debugging. I hope you enjoy it!

Regards,
Nico

**Comment by branchnetconsulting** [comment]
Awesome!  I will love it and so will my Wazuh trainees.
