### ISSUE TITLE
Analyze Wazuh API usage by Kibana

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10755]
This issue aims for an exhaustive analysis of the Wazuh API usage by Kibana to try and improve the amount of API requests and use.

To achieve this, we must use an environment with a Wazuh cluster, a few agents reporting and Kibana. Then, we will have to analyze the `api.log` after using Kibana for a certain task and evaluate if the API requests are optimized, can be improved or simply are not needed.

As Kibana has a lot of components to analyze independently, we will separate each component/capability/section in a new issue comment following this format:

```markdown
# <Component/Capability/Section>
Brief description of the task done in Kibana

**Status**: In progress/Done

## Issues found
### <Description of the issue>

- Kibana screenshot -

 ``` extract of the api.log ```

- Improvements and suggestions

  1. First suggestion

  ``` suggested request if necessary ```

```

**Comment by Kondent** [comment]
# Agents
Working with `agents` panel and all related operations.

**Status**: In progress

**Comment by mcarmona99** [comment]
# Management

Reviewing the `management` section: administration items and status and reports

**Status**: In progress

**Comment by mcarmona99** [comment]
# Modules

Reviewing the `modules` section.

**Status**: In progress

**Comment by mcarmona99** [comment]
# Security

Reviewing the `security` section.

**Status**: In progress

**Comment by mcarmona99** [comment]
# Settings

Reviewing the `settings` section.

**Status**: TBR

**Comment by mcarmona99** [comment]
# Healthcheck

Reviewing the healthcheck done every `x` time unit.

**Status**: Done


<details>
<summary>Issue</summary>

```
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/nodes" with parameters {"select": "name"} and body {} done in 0.027s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/nodes" with parameters {"select": "name"} and body {} done in 0.017s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/master-node/stats/remoted" with parameters {"pretty": ""} and body {} done in 0.029s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/master-node/stats/analysisd" with parameters {"pretty": ""} and body {} done in 0.020s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/worker2/stats/remoted" with parameters {"pretty": ""} and body {} done in 0.040s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/worker2/stats/analysisd" with parameters {"pretty": ""} and body {} done in 0.047s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/worker1/stats/remoted" with parameters {"pretty": ""} and body {} done in 0.033s: 200
2021/11/10 10:25:01 INFO: wazuh-wui 172.18.0.17 "GET /cluster/worker1/stats/analysisd" with parameters {"pretty": ""} and body {} done in 0.030s: 200
```

</details>

- Improvements and suggestions

  1. Repeated `GET /cluster/nodes`. Are both of them needed?
  2. The `pretty` parameter is not being used properly in the requests to `GET /cluster/{node_id}/remoted` and `GET /cluster/{node_id}/analysisd` endpoints. Remove the parameter as it is not being used.

**Comment by Desvelao** [comment]
Hi guys, I wanted to tell you did a good job in analyzing the requests done by the Wazuh plugin. Thank you so much!

I was reviewing the analysis and I could see some of the problems you mentioned here. The review was done at https://github.com/wazuh/wazuh-kibana-app/issues/5233.
