### ISSUE TITLE
Migrate agent-group files to wazuh-db

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#10771]
We have to study and propose a solution to migrate current agent-group files information to wazuh-db. 

The current solution using files does not scale well and we are already reaching the limits for cluster environments with a certain size. 

Currently, the agent groups information is stored in files located in `/WAZUH_PATH/queue/agent-groups`. Each agent possesses its own agent-group file, which is a plain text file containing the groups the agent belongs to, separated by a comma. The name of the file is the agent's ID.

In a cluster environment, the master node is in charge of synchronizing these files among all worker nodes. The synchronization in this case occurs in both ways. When an agent connects to a worker node, the agent-group file is created locally, and then sent to the master node as part of the `Integrity sync` task. Later on, the master compares the integrity of its files with those of the different worker nodes and send all missing or changed files to them, ensuring the integrity of the environment. 

When the cluster environment is big (20+ worker nodes, 50k+ agents), the task to calculate the integrity of the files in the master node plus the N integrity synchronizations for the N worker nodes is taking a lot of time, occupying the cluster process almost completely, and causing huge delays.

These delays end up producing problems in other modules, such as API distributed requests timeouts, agents not connecting at the right time because the client.keys file is not synchronized and update in the worker they are connecting to, etc.

By migrating the information and usage of the agent group files information completely to wazuh-db, we can greatly reduce the master load. These files containing agent group information do not change frequently, and so, calculating their content, compressing them in zip files and sending them to all the worker when necessary is very inefficient. With the information stored in the database, we can synchronize the information between databases only when it changes, and without using thousand of files and compress methods.

Tasks:
- Migrate RBAC groups calculation to wazuh-db
- Develop an efficient wazuh-db method to retrieve all agents belonging to a group or all groups (RBAC)
- Synchronize agent-groups information between cluster nodes (new task)
- Migrate usage of agent-group files to wazuh-db

## Branches

**WORKING_BRANCH**: https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db
**WORKING_CLUSTER_BRANCH**: https://github.com/wazuh/wazuh/tree/feature/10771-cluster-api-agent-groups
**WORKING_BRANCH_DOCUMENTATION**: https://github.com/wazuh/wazuh-documentation/tree/dev-10771-agent-groups-files-to-wazuh-db
**TARGET_BRANCH**: `master`

**Comment by pereyra-m** [comment]
I'm closing this because all the issues related to the epic have been completed.
