### ISSUE TITLE
Replace in FIMDB the current Windows and Macos static library with a dynamic one

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#10781]
## Description
Hi team, [working with the FIMDB class](https://github.com/wazuh/wazuh/pull/10605), we have had big problems when it comes to combine the c and c++ code, especially in relation to the creation of a dynamic library in which to contain all the c code to be used easily from c++.

After several talks and investigations, we have managed to generate in Linux a dynamic library that allows us to use all the necessary.
The problem we have found with Windows and MacOS, where it is not possible to make use of the dynamic library. At the moment we have created static libraries that allow us to compile everything without problems, although we believe that to maintain consistency, all systems should work the same.

## Purpose
The goal would be to find a way to have a dynamic library on Windows and MacOS. To do this it would be necessary to organize and take into account everything we may need from the c code part. We can make use of parameter passing in those files where we are going to need c functions, structures or variables compiled in c, etc.

## Errors

When compiling, this is the error we found, lack of symbols and references:

![image](https://user-images.githubusercontent.com/60003131/140909378-bc5fc928-4319-49d5-aa35-8623ee49ac41.png)

## Changes in Makefile and CMakeLists
https://github.com/wazuh/wazuh/blob/8f7a3872963d72c579903a9da9536cff826b6081/src/syscheckd/db/CMakeLists.txt#L75-L88
https://github.com/wazuh/wazuh/blob/8f7a3872963d72c579903a9da9536cff826b6081/src/Makefile#L62-L68

**Comment by antoniomanuelfr** [comment]
In MacOS this change has been done in the following issue https://github.com/wazuh/wazuh/issues/11650

**Comment by chemamartinez** [comment]
We have decided to let the static library in Windows for now.
