### ISSUE TITLE
Create popt external dependencies with CMake

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#10798]
| Related issue |
|---|
| #10473 |

Hi team!

This issue aims to create and tweak popt source code to add it as external deps package:
- [x] Fetch last stable source code. Validate its authenticity
- [x] Remove unnecessary files (documentation) in order to make it lightweight.
- [x] Enable/configure to compile with essential features required from librpm. This will cause a smaller precompiled package
- [x] Create a CMakeLists.txt to compile it as static library. **NOTE*** CMake minimum required version v3.12.4
- [x] Create a `tar.gz` package with the next command : `tar -zcvf <library-name>.tar.gz <source-code-dir> --owner=0 --group=0`
- [x] Post here: 
  - [x] source code version
  - [x] source code original URL
  - [x] git patch with changes made to the source code
  - [x] the final size of source package

Regards,
Nico

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/10798?planning-poker) with ZenHub @jnasselle @RamiroRD

**Comment by RamiroRD** [comment]
Script for downloading, patching, re-taring and compiling package:
```
#!/bin/sh
set -e

# Download original tarball
NAME=popt-1.18
TAR="$NAME.tar.gz"
wget -O $TAR.original https://ftp.osuosl.org/pub/rpm/popt/releases/popt-1.x/popt-1.18.tar.gz
tar -xzf "$TAR.original"
# Remove unused files
cd $NAME
rm -rf autogen.sh ABOUT-NLS README
cd ..

# Prepare stripped tarball
rm -rf upstream
mv "$NAME" upstream
tar -zcf wazuh-$TAR upstream CMakeLists.txt --owner=0 --group=0

# Print original and striped sizes
du -h $TAR.original
du -h wazuh-$TAR

# Build time
rm -rf build
mkdir build
cd build
command time -o build_time /bin/sh -c "cmake .. && make"
```
build_time is 15 seconds.
new tarball size is almost identical for now (560 KiB).
