### ISSUE TITLE
Create zlib external dependencies with CMake

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#10796]
| Related issue |
|---|
| #10473 |

Hi team!

This issue aims to create and tweak zlib source code to add it as external deps package:
- [ ] Fetch last stable source code. Validate its authenticity
- [ ] Remove unnecessary files (documentation) in order to make it lightweight.
- [ ] Enable/configure to compile with essential features required from librpm. This will cause a smaller precompiled package
- [ ] Create a CMakeLists.txt to compile it as static library. **NOTE*** CMake minimum required version v3.12.4
- [ ] Create a `tar.gz` package with the next command : `tar -zcvf <library-name>.tar.gz <source-code-dir> --owner=0 --group=0`
- [ ] Post here: 
  - [ ] source code version
  - [ ] source code original URL
  - [ ] git patch with changes made to the source code
  - [ ] the final size of source package

Regards,
Nico

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/10796?planning-poker) with ZenHub @jnasselle @RamiroRD
