### ISSUE TITLE
Create libmagic external dependencies with CMake

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#10797]
| Related issue |
|---|
| #10473 |

Hi team!

This issue aims to create and tweak libmagic source code to add it as external deps package:
- [x] Fetch last stable source code. Validate its authenticity
- [x] Remove unnecessary files (documentation) in order to make it lightweight.
- [x] Enable/configure to compile with essential features required from librpm. This will cause a smaller precompiled package
- [x] Create a CMakeLists.txt to compile it as static library. **NOTE*** CMake minimum required version v3.12.4
- [x] Create a `tar.gz` package with the next command : `tar -zcvf <library-name>.tar.gz <source-code-dir> --owner=0 --group=0`
- [ ] Post here: 
  - [x] source code version.  **5.41**
  - [x] source code original URL.
    - https://github.com/file/file
    - https://github.com/file/file/archive/refs/tags/FILE5_41.tar.gz
    - https://github.com/file/file/tree/FILE5_41
  - [ ] git patch with changes made to the source code
  - [ ] the final size of source package

Regards,
Nico

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/10797?planning-poker) with ZenHub @jnasselle @RamiroRD
