### ISSUE TITLE
Allowing s3 woodle 'waf' or 'custom' to have cloudtrail directory structure

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#10802]
Hello,

In my s3 bucket I have waf logs under the same directory structure as cloudtrail `aws_account_id/yyyy/mm/dd/...`. Can there be an option to use that dir structure since you already have the code logic?

Thanks,
Tony

**Comment by CarlosRS9** [comment]
Hi @antonisnyc94 ,

You can check the path structure allowed for each of the AWS services and bucket types we support [here](https://documentation.wazuh.com/current/amazon/services/supported-services/index.html).

As you can see WAF, like the other supported S3 buckets, allows the use of a `prefix` value to indicate any custom path where your logs are stored within the bucket:
```
<bucket_name>/<prefix>/<year>/<month>/<day>/<hh>/<hh>
```

Continuing with your example, if you want the module to look for logs in a folder with your `aws_account_id` as its name, you just need to specify it using the `path` tag in the configuration. Here is an example
```
<wodle name="aws-s3">
  
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>

  <bucket type="waf">
    <name>bucket_name</name>
    <path>123456789</path>
    <aws_profile>default</aws_profile>
  </bucket>

</wodle>

```

This configuration will download any log found in `bucket_name/123456789/<year>/<month>/<day>/<hh>`.


It is possible to specify more complex path like the following one:
```
<path>AWSLogs/123456789/WAF/us-west-1</path>
```

Ẁhich will result in the processing of any log in the following path:
```
bucket_name/AWSLogs/123456789/WAF/us-west-1/<year>/<month>/<day>/<hh>/<hh>
```

Take a look to our [reference page](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#wodle-s3) so you can learn more about the different parameters available for this module.



I hope this helps.

**Comment by antonisnyc94** [comment]
Thank you @CarlosRS9 !  I was trying to avoid the issue of having to change the ossec conf everytime i add a new aws account. I guess i will make it work this way. Thanks again!
