### ISSUE TITLE
Use ProcessPoolExecutor in the framework DAPI module

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10803]
As proposed in the investigation of #10789 , this issue is the short term version of #10790 .

This implementation requires a change in the `dapi.py` module to use `ProcessPoolExecutor` limited to 1 worker. This way, everything should work without further changes but performance will increase as the processing will be done by another process instead of a thread (Python GUI limitations with high CPU usage).

For more information about the tasks, check the issues above.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
# Issue update

Development has been finished. The original idea consisted in simply changing the `dapi.py` module to use a *`ProcessPoolExecutor` limited to 1 process* for local requests. However, this implementation alone was not enough. This is due to the actual flow of execution of an API request.

Before trying to obtain a response for the current request, the authentication process takes place, doing a few calls to `dapi.distribute_function()` to validate the token, obtain permissions, etc. All these calls are executed in `dapi.execute_local_request()`, by the child process. This means that if there is anything blocking the child process, distributed and authentication requests will block as well.

We can see this behaviour adding a logger in the `execute_local_request` method:

```shellsession
2021/11/12 12:03:58 INFO: EXECUTE_LOCAL_REQUEST - <function check_token at 0x7f7e56d443a0>
2021/11/12 12:03:58 INFO: EXECUTE_LOCAL_REQUEST - <function get_security_conf at 0x7f7e56d44160>
2021/11/12 12:03:58 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 0.054s: 200
2021/11/12 12:03:58 INFO: EXECUTE_LOCAL_REQUEST - <function check_token at 0x7f7e56d443a0>
2021/11/12 12:03:58 INFO: EXECUTE_LOCAL_REQUEST - <function get_security_conf at 0x7f7e56d44160>
2021/11/12 12:03:58 INFO: EXECUTE_LOCAL_REQUEST - <function get_agents at 0x7f7e56d7dca0>
2021/11/12 12:03:59 INFO: EXECUTE_LOCAL_REQUEST - <function check_token at 0x7f7e56d443a0>
2021/11/12 12:04:05 INFO: EXECUTE_LOCAL_REQUEST - <function get_security_conf at 0x7f7e56d44160>
2021/11/12 12:04:05 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {} and body {} done in 7.054s: 200
2021/11/12 12:04:05 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 6.684s: 200
```

## Implementation

To solve this, I implemented another `ProcessPoolExecutor` to handle authencation operations. The current API process state is:

- **Main process**: Handle requests/responses, communication and forwarding.
  - **Process Pool 1 (1 process)**: Process authentication operations.
  - **Process Pool 2 (1 process)**: Process local requests.


To try this, I added a `sleep` of **7 seconds** to the framework SDK `get_agents()` function. Then, I made 3 requests in order without any delay:

1. `GET /cluster/{node_id}/status` (distributed request)
2. `GET /agents` (local request)
3. `GET /cluster/{node_id}/status` (distributed request)

### Former implementation

```shellsession
2021/11/12 13:05:48 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 0.075s: 200
2021/11/12 13:05:56 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {} and body {} done in 7.077s: 200
2021/11/12 13:05:56 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 6.737s: 200
```

Although `GET /cluster/worker1/status` is done in 0.075s, the second request is blocked until `GET /agents` unblocks the main process.


### New implementation

```shellsession
2021/11/12 13:07:45 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 0.091s: 200
2021/11/12 13:07:45 INFO: wazuh 127.0.0.1 "GET /cluster/worker1/status" with parameters {} and body {} done in 0.044s: 200
2021/11/12 13:07:52 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {} and body {} done in 7.071s: 200
```

We can see how the second request to `GET /cluster/worker1/status` was processed before `GET /agents` ended.


In addition, we can guarantee that no matter what the API is doing, it will be able to provide authentication tokens:

1. `GET /agents` (with a sleep of 7s)
2. `GET /security/user/authenticate`
3. `GET /security/user/authenticate`
4. `GET /security/user/authenticate`
5. `GET /security/user/authenticate`

```shellsession
2021/11/12 13:08:27 INFO: wazuh 172.19.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.326s: 200
2021/11/12 13:08:27 INFO: wazuh 172.19.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.350s: 200
2021/11/12 13:08:28 INFO: wazuh 172.19.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.297s: 200
2021/11/12 13:08:29 INFO: wazuh 172.19.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.305s: 200
2021/11/12 13:08:33 INFO: wazuh 127.0.0.1 "GET /agents" with parameters {} and body {} done in 7.022s: 200
```

## Performance tests

These changes will not provide any significant improvement in raw performance. They are more related to availability. However, I performed some tests using `Locust`.

### Environment settings

- ~60 seconds test
- 10 concurrent users
- Each user will try to obtain his own token on start.
- Every time a user makes an API request, it has a 70% of being a local request (with custom code, a sleep of 3 seconds) and a 30% of being a distributed request.
- The API DOS mechanism has been disabled.

### Test using the former implementation

#### Request statistics

![image](https://user-images.githubusercontent.com/37274979/141485647-651c8a09-01f7-4d3f-a446-a02a8201980a.png)


![image](https://user-images.githubusercontent.com/37274979/141485688-f6fc48bd-a657-4a8e-8d08-90d15c5e505a.png)


#### Response time statistics

![image](https://user-images.githubusercontent.com/37274979/141485728-694bcf97-c2ae-4b43-a03e-10fde2dc7aa2.png)

![image](https://user-images.githubusercontent.com/37274979/141485785-f12e4692-c387-4fce-8f0b-da6e92a64708.png)


### Test using the new implementation

#### Request statistics

![image](https://user-images.githubusercontent.com/37274979/141485876-a9acbacc-4c09-4a05-81c5-aedf6ce42870.png)

![image](https://user-images.githubusercontent.com/37274979/141485916-3a2fdaff-f630-4ead-83b8-b65ca4235aad.png)


#### Response time statistics

![image](https://user-images.githubusercontent.com/37274979/141485941-8c74bf14-bc39-435b-a017-f3b4aefed674.png)

![image](https://user-images.githubusercontent.com/37274979/141485982-a0f494fe-f3a3-4742-b790-31d136702cf2.png)

**Comment by vicferpoy** [comment]
# Issue update

After analyzing the API integration tests and doing some manual testing, we have detected some issues with this implementation:

## BrokenProcessPool error on certain requests

With the API integration tests we noticed there are a few requests that raise a `BrokenProcessPool` error consistently:

```cmd
2021/11/12 15:40:29 ERROR: Error executing API request locally: A process in the process pool was terminated abruptly while the future was running or pending.
concurrent.futures.process._RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 384, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
  File "/var/ossec/framework/python/lib/python3.9/multiprocessing/connection.py", line 256, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'code'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 285, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2021/11/12 15:40:29 INFO: testing 172.20.0.1 "GET /agents/upgrade_result" with parameters {"agents_list": "008"} and body {} done in 0.077s: 500
```

This error immediately kills the child process, making the process pool not usable anymore. An API restart is needed to to work again. 

Further investigating this issue, it has been proven that this exception comes from the task which the child process is running. When **this task raises an exception**, it is considered an unexpected error and the child process terminates abruptly, breaking the pool.


## Shared memory

There are some variables that are loaded by the parent process and then changed by the child process. In examples like the `GET /security/config` endpoint, the API security configuration can be modified without restarting the API. This situation is problematic as that variable is not being shared between processes and if we update it and then try to get the new value, the old one will be loaded instead. This case could be seen in the API integration tests:

```cmd
Source test stage (line 683):
  - name: Get security configuration to check if PUT method worked correctly
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/security/config"
      headers:
        Authorization: "Bearer {test_login_token}"
      method: GET
    response:
      status_code: 200
      json:
        error: !anyint
        data:
          auth_token_exp_timeout: 3000
          rbac_mode: !anystr

Formatted stage:
  name: Get security configuration to check if PUT method worked correctly
  request:
    headers:
      Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM2NzMxNTU2LCJleHAiOjE2MzY3MzQ1NTYsInN1YiI6InRlc3RpbmciLCJydW5fYXMiOmZhbHNlLCJyYmFjX3JvbGVzIjpbMV0sInJiYWNfbW9kZSI6IndoaXRlIn0.ANSj4rc_8b049IJrJwpFVh8Xoy0JDs7KVWK8tj23rxZ42KbOmN6VPFZVaVelu0DrWF-GQBmkOGzNNE29QFl7FAWhAaiAkOjZbBdx4vJmb8UnVIKRlNkLbAJ9G0bPTzJBD62iWpSu13qR_jK1Pj151UGprxsudigI8NUlgkwZbzwqQAXx
    method: GET
    url: 'https://localhost:55000/security/config'
    verify: false
  response:
    json:
      data:
        auth_token_exp_timeout: 3000
        rbac_mode: !anystr ''
      error: !anyint ''
    status_code: 200

Errors:
E   tavern.util.exceptions.TestFailError: Test 'Get security configuration to check if PUT method worked correctly' failed:
    - Key mismatch: (expected["data"]["auth_token_exp_timeout"] = '3000' (type = <class 'int'>), actual["data"]["auth_token_exp_timeout"] = '900' (type = <class 'int'>))
```

We need to decide whether we cover these errors for the short term solution or whether we should begin to work in the long term one as this implementation will require some more time and probably will not be ready for the next release.

**Comment by davidjiglesias** [comment]
Finally, we have to decided to go for the long-term solution in issue #10790. The present issue contains valuable information and some of the constraints @vicferpoy had found during the investigation and testing of the solution.

**Comment by vicferpoy** [comment]
We are reopening this issue to try and solve these errors for the short-term solution in case this implementation is suitable for the next version.

Since the long-term solution will have the same problems, everything that is solved now will be time well spent.

**Comment by vicferpoy** [comment]
# Issue update
Fixes have been implemented and tested, both manually and automatically. As everything seems fine, development is concluded.

To prevent the shared memory issue, the only affected endpoint (`GET /security/config`) has been changed to read from file. This also happens every time we make any request, as it has to read the current configuration to validate the token. As we have planned for the future, the API security configuration will be included within the API configuration, improving the performance as it will only change on restart and we will be able to cache it.

Regards,
Víctor
