### ISSUE TITLE
How to reset the marker for a woodle of an s3 bucket

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#10801]
Hello,

I had a bucket with the following directory structures..  `bucket/waf/account_id/...` . I realized that wazuh doesnt support multiple prefixes for waf and thus changed it to `bucket/waf/`. Now wazuh doesnt process any logs because the market was stuck in the previous directory. Do you know how to reset the market for a specific woodle without resetting the whole thing or changing dir name? Thanks a lot! Tony

```
DEBUG: +++ Debug mode on - Level: 2
DEBUG: +++ Marker: waf/{acount_id}/2021/11/08/11/aws-waf-logs-uat-to-infosec-3-2021-11-08-11-42-19-445a3af1-5f25-4093-88db-411fc85a97
DEBUG: +++ No logs to process in bucket: None/None
DEBUG: +++ DB Maintenance
```

**Comment by antonisnyc94** [comment]
i just needed to set the -o option in aws-s3 woodle

**Comment by antonisnyc94** [comment]
it appears that the pointer remains... can someone assist?

**Comment by antonisnyc94** [comment]
For anyone needing help with this, i had to go into `/var/ossec/wodles/aws/` , run `sqlite3 s3_cloudtrail.db` and `delete from waf;` to delete the parser logs.

**Comment by anjanaradhakrishnan** [comment]
Hey @antonisnyc94 I'm facing the same error while integrating the guardduty with wazuh.
The bucket is having all the logs but not coming to the wazuh.
```
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on ACC_ID - us-east-1
DEBUG: +++ Marker: AWSLogs/ACC_ID/GuardDuty/us-east-1/2024/05/09/xxxx-cf0a-33c5-a04d-xxxxxxxxxxx.jsonl.gz
DEBUG: +++ No logs to process in bucket: ACC_ID/us-east-1
DEBUG: +++ DB Maintenance
```
@antonisnyc94 Need your suggestion on this

**Comment by keerthanap0810** [comment]
did anyone resolve this?
