### ISSUE TITLE
Unable to decode Symantec Log

### ISSUE THREAD

**Issue by jacobmathews2007** [wazuh/wazuh#10819]
hai i am not able to decode the following log.

i followed the wazuh decoder making documentation,but still it dowsnot works. is it some bug or soemthing?

log :
Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.

![image](https://user-images.githubusercontent.com/94116978/141475355-026ae010-ff02-49ff-ba4e-34b26e3f7211.png)

**Comment by AdriiiPRodri** [comment]
Hi @jacobmathews2007,

Actually, there is no known bug related to this, it is possible that the decoder you have written is not working properly.
In this case, the first thing to do is to create a generic decoder to decode the Symantec logs:

```
<decoder name="symantec_decoder">
  <program_name>^SymantecServer</program_name>
</decoder>
```

Then we will need to create a child decoder of the previous one. This will be in charge of extracting the information:

```
<decoder name="symantec_decoder">
  <parent>symantec_decoder</parent>
  <regex>Site: (\.*),Server: (\.*),Client</regex>
  <order>site,server</order>
</decoder>
```

In this case for the log that you provide us, I have extracted the information related to Site: and Server:. You can extract the information you want following the same scheme.

Here you can see an example with the `wazuh-logtest` tool:

```
root@wazuh-master:/# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.4
Type one log per line

Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.

**Phase 1: Completed pre-decoding.
        full event: 'Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.'
        timestamp: 'Nov 11 11:31:58'
        hostname: 'hostname1'
        program_name: 'SymantecServer'

**Phase 2: Completed decoding.
        name: 'symantec_decoder'
        server: 'laboratory'
        site: 'My location'
```

If you have any questions, please do not hesitate to ask.

Regards.

**Comment by jacobmathews2007** [comment]
@AdriiiPRodri still the same.

i made the decoder as per your suggestion. still its not decoding. thats why to confirm whether it is a bug or not

![image](https://user-images.githubusercontent.com/94116978/141523443-452eaad5-223c-42a8-a403-b2279071039c.png)

this is the output.

its not matching the decoder

**Comment by AdriiiPRodri** [comment]
Hello @jacobmathews2007,

To rule out a possible bug in Wazuh version 4.2.0, I have performed all the steps I have described in my previous message. Here you can see the results:

#### Wazuh version
```
root@wazuh-master:/# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.2.0"
WAZUH_REVISION="40212"
WAZUH_TYPE="server"
```

#### local_decoder.xml content
```
root@wazuh-master:/# cat /var/ossec/etc/decoders/local_decoder.xml
<!-- Local Decoders -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015-2020, Wazuh Inc. -->

<!--
  - Allowed static fields:
  - location   - where the log came from (only on FTS)
  - srcuser    - extracts the source username
  - dstuser    - extracts the destination (target) username
  - user       - an alias to dstuser (only one of the two can be used)
  - srcip      - source ip
  - dstip      - dst ip
  - srcport    - source port
  - dstport    - destination port
  - protocol   - protocol
  - id         - event id
  - url        - url of the event
  - action     - event action (deny, drop, accept, etc)
  - status     - event status (success, failure, etc)
  - extra_data - Any extra data
-->

<decoder name="local_decoder_example">
    <program_name>local_decoder_example</program_name>
</decoder>

<decoder name="symantec_decoder">
  <program_name>^SymantecServer</program_name>
</decoder>

<decoder name="symantec_decoder">
  <parent>symantec_decoder</parent>
  <regex>Site: (\.*),Server: (\.*),Client</regex>
  <order>site,server</order>
</decoder>
```

#### wazuh-logtest output
```
root@wazuh-master:/# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line

Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.

**Phase 1: Completed pre-decoding.
        full event: 'Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.'
        timestamp: 'Nov 11 11:31:58'
        hostname: 'hostname1'
        program_name: 'SymantecServer'

**Phase 2: Completed decoding.
        name: 'symantec_decoder'
        server: 'laboratory'
        site: 'My location'
```

Could you check that there is no error in the decoders? These should be as I have indicated. Also, to confirm, the message to be decoded is this one, is it?

`Nov 11 11:31:58 hostname1 SymantecServer: Site: My location,Server: laboratory,Client traffic logs have been swept.`

**Comment by AdriiiPRodri** [comment]
Closed due to inactivity.
