### ISSUE TITLE
Update the MITRE JSON up to version 10

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#10812]
|Wazuh version|Component|Action type|
|---|---|---|
| 4.3.0-rev |MITRE | Add new version's JSON | 

## Description

On October there was a MITRE ATT&CK update, bringing it to version 10, this requires updating our JSON file with the newest one.
### Reason

The main reason is to get the latest MITRE version whose changes can be seen here: https://github.com/mitre/cti/blob/master/CHANGELOG.md
### Current results

The `ruleset/mitre/enterprise-attack.json` file is outdated
### Expected results

Update the `ruleset/mitre/enterprise-attack.json` file with the lastest version, that can be found here: https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

**Comment by 72nomada** [comment]
Moved to #13277
