### ISSUE TITLE
How to monitor the server itself.

### ISSUE THREAD

**Issue by GammaPi** [wazuh/wazuh#1085]
I've installed wazuh successfully on my computer and noticed that it only contains ossec-server meaning that I cannot use ossec-hid to monitor the server itself.

Is there a hybrid mode like ossec that enables me to monitor both remote servers and local computers.

**Comment by GammaPi** [comment]
Well after I get more knowledge about the whole thing, I suddenly understand how to solve my problem.

This link explains everything:
https://documentation.wazuh.com/current/getting-started/architecture.html

Issue closed by myself.

**Comment by effyteva** [comment]
Hi @GammaPi , and chance you could share your insights?
We try getting the agent to work on the server but can't get it to start
