### ISSUE TITLE
Improve cluster healthcheck functions

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10868]
To obtain the response of the API endpoint `GET /cluster/healthcheck` and `bin/cluster_control -i more` (cluster CLI), this function is used:

https://github.com/wazuh/wazuh/blob/f381fc2883555b4a996c4ac6548de7c545c96618/framework/wazuh/core/cluster/control.py#L109-L136

We need to analyze the whole flow of execution of this function and improve it as much as possible. In addition, we must add the datetime calculation to the output.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

I have measured the time spent in the `get_health` function of `wazuh/core/cluster/control.py` in a Wazuh cluster with 3 nodes and 10 agents connected.

- Total time spent: 0.013270378s

  - Time spent in `lc.execute` function: 0.013181686401367188s
  - Time spent loading response as json: 8.869171142578125e-05s


As we can see, the function is most of the time waiting for the response after executing the `get_health` command in the local client:

```
response = await lc.execute(command=b'get_health',
                                data=json.dumps(filter_node).encode(),
                                wait_for_complete=False)
```

This request is processed with a `MasterHandler` class object. The `process_request` method is the one defining the commands received.

As we can see in the `process_request` class method, when the command is `get_health`, the `get_health` method is executed:

```
        elif command == b'get_health':
            cmd, res = self.get_health(json.loads(data))
            return cmd, json.dumps(res,
                                   default=lambda o: "n/a" if isinstance(o, datetime) and o == datetime.fromtimestamp(0)
                                   else (o.__str__() if isinstance(o, datetime) else None)
                                   ).encode()
```

This method calls the `get_health` method of the `Master` class.

This `get_health` method gets the workers' information and the respective agents' information.

Time spent in the function in the same Wazuh cluster (different execution):

- Total time spent: 0.009665489s

  - Time spent getting workers information: 4.291534423828125e-05s
  - Time spent getting agents information: 0.009622573852539062s

The function is most of the time calculating the agents' information. I will try to improve this code to make the function faster.

Code to improve:

```
        for node_name in workers_info.keys():
            workers_info[node_name]["info"]["n_active_agents"] = \
                Agent.get_agents_overview(filters={'status': 'active', 'node_name': node_name})['totalItems']
            if workers_info[node_name]['info']['type'] != 'master':
                workers_info[node_name]['status']['last_keep_alive'] = str(
                    datetime.fromtimestamp(workers_info[node_name]['status']['last_keep_alive']
                                           ).strftime(decimals_date_format))
```

There is a query to the agents' database for each Wazuh cluster node. I have updated this code to make a single query.

Checking if the endpoint is faster...

**Comment by mcarmona99** [comment]
## Issue update

The following table shows the time spent getting workers and agents information, for the same request to `GET /cluster/healthcheck` endpoint from different Wazuh cluster environments. These measurements have been done with and without improvements.

|  WORKERS | AGENTS  | Improvements? | Time getting workers info  | Time getting agents info  |  
|---|---|---|---|---|
| 2  | 1000   | No   |  To complete | To complete  |
| 2  | 1000  | Yes  |  2.5033950805664062e-05s  | 0.09756040573120117s  |
| 10  | 10000  | No  |  To complete |  To complete  |
| 10 | 10000  | Yes  |  6.604194641113281e-05s  | 0.09218859672546387s  |

**Comment by mcarmona99** [comment]
## Issue update

As we can see in the table shown in the last comment, the endpoint has clearly improved, making both the request and the CLI faster in bigger Wazuh environments.

![image](https://user-images.githubusercontent.com/57481331/145863265-d5cf4277-8a5f-4573-b92c-eca8c962e811.png)
