### ISSUE TITLE
Make API log format configurable

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#10867]
To make the API log parsing easier, we should add a new option for the API to write all the log entries in JSON format:

**- Default log format (current)**

```yaml
  log_format: plain
```
**Log file:** `api.log`

**- JSON format**

```yaml
  log_format: json
```

**Log file:** `api.json`

We should consider adding new QA integration tests for this new feature.

**Please notice that `log_format` can be set as `both` too, if we want to log into both files at the same time.**

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core-5b4dd684c93e4717b2160eea/issues/wazuh/wazuh/10867?planning-poker) with ZenHub @Kondent @mcarmona99 @vicferpoy

**Comment by Kondent** [comment]
## Update
Currently, API can be configured to log into `json` or plain text files.
I'm working on this, doing a few tests and reviewing the log output to verify them.

I encountered a few problems too, for instance:
```json
{"date": "2021/11/29 17:59:03", "level": "INFO", "message": HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them}
{"date": "2021/11/29 17:59:03", "level": "INFO", "message": Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key}
{"date": "2021/11/29 17:59:03", "level": "INFO", "message": Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt}
{"date": "2021/11/29 17:59:08", "level": "INFO", "message": Listening on 0.0.0.0:55000..}
{"date": "2021/11/29 17:59:13", "level": "INFO", "message": {"user": "wazuh", "remote_ip": "172.25.0.1", "req_method": "GET /security/user/authenticate", "req_parameters": {}, "req_body": {}, "time": "0.280s", "status_code": 200}}
{"date": "2021/11/29 17:59:13", "level": "INFO", "message": {"user": "wazuh", "remote_ip": "172.25.0.1", "req_method": "GET /agents", "req_parameters": {"offset": "0", "limit": "500"}, "req_body": {}, "time": "0.043s", "status_code": 200}}
```
Simple messages at the `message` value field need to be quoted.
I'm investigating this.

**Comment by Kondent** [comment]
## Update
I got that problem solved. Currently using [`python-json-logger`](https://pypi.org/project/python-json-logger/) package to ease this development.

API JSON LOG:
```json
{"timestamp": "2021/11/30 16:47:05", "levelname": "INFO", "message": "HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them"}
{"timestamp": "2021/11/30 16:47:05", "levelname": "INFO", "message": "Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key"}
{"timestamp": "2021/11/30 16:47:05", "levelname": "INFO", "message": "Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt"}
{"timestamp": "2021/11/30 16:47:10", "levelname": "INFO", "message": "Listening on 0.0.0.0:55000.."}
{"timestamp": "2021/11/30 16:48:20", "levelname": "INFO", "message": {"user": "wazuh", "remote_ip": "172.20.0.1", "request_method": "GET /security/user/authenticate", "request_parameters": {}, "request_body": {}, "time": "0.264s", "status_code": 200}}
{"timestamp": "2021/11/30 16:48:20", "levelname": "INFO", "message": {"user": "wazuh", "remote_ip": "172.20.0.1", "request_method": "GET /agents", "request_parameters": {"offset": "0", "limit": "500"}, "request_body": {}, "time": "0.048s", "status_code": 200}}
```

Tasks I'm performing:
- [ ] API JSON log handling.
- [ ] API log format configurable via `api.yaml`.
- [ ] Review all related tests, modify them if needed.

**Comment by Kondent** [comment]
## Update
* All tests were updated due to the changes of this development.
* I'm working with tracebacks at the moment. I tried to raise errors on my environment on purpose and the review the logs to check its formatting. I'm reviewing why `exc_info` value is not being properly formatted.
```json
{
  "timestamp": "2021/12/01 15:53:57",
  "levelname": "ERROR",
  "message": "Error handling request",
  "exc_info": "Traceback (most recent call last):\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/control.py\", line 56, in get_nodes\n    result = json.loads(response, object_hook=as_wazuh_object)\n  File \"/var/ossec/framework/python/lib/python3.9/json/__init__.py\", line 359, in loads\n    return cls(**kw).decode(s)\n  File \"/var/ossec/framework/python/lib/python3.9/json/decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/ossec/framework/python/lib/python3.9/json/decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/connexion/apis/aiohttp_api.py\", line 50, in problems_middleware\n    response = yield from handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp/web_middlewares.py\", line 110, in impl\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/middlewares.py\", line 140, in response_postprocessing\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/middlewares.py\", line 33, in set_user_name\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/middlewares.py\", line 117, in security_middleware\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/middlewares.py\", line 89, in request_logging\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/middlewares.py\", line 38, in set_secure_headers\n    resp = await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/aiohttp_cache/middleware.py\", line 59, in cache_middleware\n    return await handler(request)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/connexion/decorators/coroutine_wrappers.py\", line 23, in wrapper\n    connexion_response = yield from connexion_response\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/api-4.4.0-py3.9.egg/api/controllers/cluster_controller.py\", line 33, in get_cluster_node\n    nodes = raise_if_exc(await get_system_nodes())\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/control.py\", line 198, in get_system_nodes\n    result = await get_nodes(lc)\n  File \"/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/control.py\", line 58, in get_nodes\n    raise WazuhClusterError(3020) if timeout in response else e\nwazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request"
}
```

**Comment by Kondent** [comment]
## Update
As we discussed with the team, I'm returning to this issue development since there are certain improvements to do regarding on log level.
I'm currently working on it and already got a few changes prepared to get better results in the API log file with the `json` format set.

Regards

**Comment by Kondent** [comment]
## Update
I'm returning to this development due to a new requirement, which is the possibility of log into both files at the same time.

I encountered a few problems related with our log modules structure. I'm currently working on alternatives because there's no clear solution for the moment.

**Comment by Kondent** [comment]
## Update
I found out a new solution with a few modifications on the current schema.
The related pull request is now updated.
