### ISSUE TITLE
SCA RHEL8: Error in check for CIS 4.2.3 "Ensure permissions on all logfiles are configured"

### ISSUE THREAD

**Issue by joar-rasmussen** [wazuh/wazuh#10886]
|Wazuh version| Component | Action type |
|---|---|---|
| 4.2.1-1 | Rules | Error |

## Description
The check returns a "failed" even when all logs files satisfy the requirement.

### Service/Product/Module
RHEL8

### Current results
"failed" in SCA report

### Expected results
"passed" the report, as long as permissions on all log files conform to permissions rules described in requirement.

Note: Issue confirmed by Jose Cruz on #community Slack channel today.

**Comment by 72nomada** [comment]
solved on #11242
