### ISSUE TITLE
Improve time measurements between functions in the cluster code

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#10909]
In the cluster code, it is often useful to know how much time each task has consumed. Nowadays this measurement is done with the time or datetime library. Here we can see an example:

```
 async def file_status_update(self):
    """Asynchronous task that obtain files status periodically.
    It updates the local files information every self.cluster_items['intervals']['worker']['sync_integrity']
    seconds.

    A dictionary like {'file_path': {<MD5, merged, merged_name, etc>}, ...} is created and later
    compared with the one received from the workers to find out which files are different, missing or removed.
    """
    file_integrity_logger = self.setup_task_logger("Local integrity")
    while True:
        before = datetime.now()
        file_integrity_logger.info("Starting.")
        try:
            task = self.loop.run_in_executor(self.task_pool, wazuh.core.cluster.cluster.get_files_status)
            # With this we avoid that each worker starts integrity_check more than once per local_integrity
            self.integrity_control = await asyncio.wait_for(task, timeout=None)
            self.integrity_already_executed.clear()
        except Exception as e:
            file_integrity_logger.error(f"Error calculating local file integrity: {e}")
        file_integrity_logger.info(f"Finished in {(datetime.now() - before).total_seconds():.3f}s. Calculated "
                                    f"metadata of {len(self.integrity_control)} files.")

        await asyncio.sleep(self.cluster_items['intervals']['master']['recalculate_integrity'])
```

As we can see, in this case, we are getting the total number of seconds between two complete dates. This is not quite efficient and above all, it is not as accurate as it should be. The same happens when we use "time()". To solve this, we should use https://docs.python.org/3/library/time.html#time.perf_counter, this time counter is much more accurate than the subtraction of "time()" or "datetime.now()".
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
To be done in #12108
