### ISSUE TITLE
Send Wazuh info to 2 servers at the same time, not first available. 

### ISSUE THREAD

**Issue by influence2006** [wazuh/wazuh#10902]
|Wazuh version 3.13|

| 3.13.1-rev | Wazuh configs | Agent | Centos 7 |

I am trying to have the wazuh agent sent to two different servers. Currently, I am reading that it will sned to first available. Is there any way I can send info from 1 server AND 2nd server?

**Comment by juliancnn** [comment]
Hi @influence2006 ,

Thanks for sharing your question with the Community.
Currently this is not possible, but I couldn't think of a use case where this would be necessary. Could you share with us why you need this? This would help us to better understand the problem and be able to figure out an alternative solution.

The distributed architecture of elastic allows for data redundancy with horizontal scalability, while wazuh cluster would allow for load balancing with high availability:
![image](https://user-images.githubusercontent.com/1891958/142488474-4789d027-36a9-4ab5-8e5f-16a65f9f5ff9.png)



Regards,
Julian

**Comment by influence2006** [comment]
Yes I want to send data to my elasticsearch instance, but also would like
to send specific data to my greylog instance lastly I want to keep data in
an s3 container for back up.

**Comment by juliancnn** [comment]
Hi  @influence2006, 

If you want to generate a backup of elastic and save it in a cloud service, you can follow the elastic guide for this ([here](https://www.elastic.co/guide/en/elasticsearch/reference/current/backup-cluster-data.html)).

In addition to this, Wazuh-Manager can be configured to send alerts to a syslog server in real time with the [syslog_output](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syslog-output.html) option:

```xml
  <syslog_output>
    <server>192.168.0.5</server>
    <level>3</level>
    <format>json</format>
  </syslog_output>
```

For example, in this case, when a level 3 or higher alert is generated, it is sent in json format to the configured syslog server.

Please let me know if you found this helpful.

**Comment by influence2006** [comment]
Sadly, this does not work for me. I already have my elasticsearch search
backing up to s3 buckets. I also have my logs sending to s3 with a custom
script. The goal is to have data sent to multiple places, one example is
for a hot backup site. My team can recover data is needed by we are working
on a way if our main site is down we can switch to another system and not
skip a beat.

**Comment by juliancnn** [comment]
Hi @influence2006 ,

If you want to send the alerts to 2 different places, you could duplicate the filebeat instances, allowing you to send the alerts to 2 different instances of elastic search. This will allow you to have a hot backup.
For this I recommend reading the following issue which explains the procedure and a use case:

 **syslog_output from Wazuh1 to Wazuh2 receiving nothing #8961** 

While this is not exactly the same case, I think you may find it useful to duplicate filebeat instances.

**Comment by juliancnn** [comment]
Hi @influence2006 

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Julian

**Comment by RalphBariz** [comment]
Current UseCase:
- provider observes whole infrastructure
- client observes his infrastructure with multiple provider
- client is interested in audit d logging, provider isn't

**Comment by RalphBariz** [comment]
Current UseCase:

    provider observes whole infrastructure
    client observes his infrastructure with multiple provider
    client is interested in audit d logging, provider isn't

If you tell me where to add such a logic and it is feasible I might come up with a PR
