### ISSUE TITLE
I accidently delete all file  in folder /var/ossec/queue/diff, 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#1091]
I accidently delete all files inside folder `/var/ossec/queue/diff/....` on my wazuh-agent. Now there is nothing left inside that folder. The reasons i delete files inside /diff/..., because it take a lot of space from my hdd about 2.1 GB. Is there any possible crash for the apps because of the deletion ? or maybe malfunction of the apps that make the app's performance going slow ?

I compare it with my other wazuh-agent and looks like the folder store all comparison of monitored files that include in rootcheck, like /etc, /bin, /sbin. How do i retrieve back those files inside that `/diff` folder ?

**Comment by vikman90** [comment]
Hi @gagantous,

That's not a problem. In fact, the folder `diff` is empty when the agent starts by the first time. Also, as of version 3.4, the agent will automatically remove unnecessary files from that folder (i.e. snapshots for files that aren't being monitored anymore by the agent).

Hope it helps.
Best regards.

**Comment by gagantous** [comment]
Thanks @vikman90  for the explanation !
