### ISSUE TITLE
SPIKE - Retake improve log rotation

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#10910]
## Description

This issue aims to research the status of the old improvements to log rotation development (#3072) to find out how much effort will imply resume and finish it.

## DoD
- [x] Investigate the added functionalities in PR #3175.
- [ ] Evaluate the effort required to take up development #3072.
- [x] Update the PR with the master branch.
- [ ] Run analysis tools such as scan-build and valgrind
- [ ] Test the functionalities after the branch update.

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
