### ISSUE TITLE
Wrong ownership and permissions in the ossec.conf file

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#10931]
|Wazuh version|Component|
|---|---|
| 4.2.1-40214 | Wazuh manager |

### Description

After updating the configuration via Kibana using the API, 3 of the 13 workers in the cluster ended up with the wrong ownership and permissions in the `ossec.conf` file:

```
297320    8 -rw-r-----   1 root     root         7275 Nov 20 09:00 /var/ossec/etc/ossec.conf
```

Since we did not manually change the files, we think it may be due to a bug when updating the configuration using the API.

<details>
<summary>API log screenshot</summary>

![image](https://user-images.githubusercontent.com/33484080/143018421-86a1f614-e087-4eb0-8055-2f8d39aa75af.png)

</details>

**Comment by mcarmona99** [comment]
## Issue update


When the backup is generated,

https://github.com/wazuh/wazuh/blob/f4ab39d1f70cd92f18606e229cbc90aec46aa39c/framework/wazuh/manager.py#L310

it is stored in `ossec.conf.backup`.

The ownership set for this file is `ossec:ossec` as `copyfile` copies the content of a file without metadata.

Because of this, the `ossec.conf.backup` file has group and user `ossec:ossec`, as it was generated by the API, which is run by the user `ossec`.

```
root@wazuh-worker1:/# ll /var/ossec/etc/ | grep ossec.conf
-rw-rw---- 1 root  ossec  8381 Dec 24 09:55 ossec.conf
-rw-r--r-- 1 ossec ossec  8381 Dec 24 10:11 ossec.conf.backup
```

If the new file to be updated to is not valid, the backup will be copied to `/var/ossec/etc/ossec.conf`. The permissions them will change to `ossec:ossec`.

```
root@wazuh-worker1:/# ll /var/ossec/etc/ | grep ossec.conf
-rw-r--r-- 1 ossec ossec  8381 Dec 24 10:46 ossec.conf
```

Here there could be the following possibility. If we run the API with `root` permissions, the backup could be copied with `root:root` ownership and them copied back. This way, the ownership could be changed to `root:root` (from `root:ossec`). Well, this statement is false since the API drops privileges to `ossec:ossec`.

Despite the fact that the error could not be replicated, there is a new issue discovered since the backup should never have ownership different to `root:ossec`.

**Comment by mcarmona99** [comment]
### Issue update


The error could not be replicated but the only possibility of changing the ossec.conf file ownership is in the `copyfile` function.

In a python3 interpreter run as **root**, if we use `copyfile`, the ownership is `root:root`:

```
# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shutil import copyfile
>>> copyfile('new_file','old_file')
'old_file'
>>> exit()
```

```
# ll old_file 
-rw-r--r-- 1 root root 0 Jan 12 10:04 old_file
```

```
# ll new_file
-rw-r--r-- 1 example2 example2 0 Jan 12 09:22 new_file
```

In a python3 interpreter run as `example2`, if we use `copyfile`, the ownership is `example2:example2`:

```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from shutil import copyfile
>>> copyfile('new_file','/test/old_file')
'old_file'
>>> exit()
```

```
# ll /test/old_file 
-rw-rw-r-- 1 example2 example2 0 Jan 12 09:33 /test/old_file
```

```
# ll new_file
-rw-r--r-- 1 example2 example2 0 Jan 12 09:22 new_file
```

As we can see, the ownership changed depending on the user using the interpreter.

To avoid this error, we should use an alternative to `copyfile` to copy a file maintaining its metadata.

**Comment by mcarmona99** [comment]
## Issue update

In addition to what I already said in the last comment, I have done an extra test.

**Could the `ossec.conf` be updated via API if its ownership is `root:root`?** At first instance, we could think that this is impossible but let's see this in depth as the truth is that an `ossec.conf` file with `root:root` ownership can be modified and its ownership changes to `ossec:ossec`. 

This statement reinforces the theory that the API hasn't changed the ownership to `root:root`. If we try to update a `root:root` `ossec.conf`, the API will return an error saying that you can't do it BUT the ownership will change to `ossec:ossec` so a new call to this endpoint right after this one will change the `ossec.conf` file successfully.

Trying to update a `root:root` `ossec.conf`, API response:

```
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1126,
          "message": "Error updating ossec configuration",
          "remediation": "Please, ensure `WAZUH_PATH/etc/ossec.conf` has the proper permissions and ownership."
        },
        "id": [
          "master-node"
        ]
      }
    ]
  },
  "message": "Could not update configuration in specified node",
  "error": 1
}
```

Trying to update a `root:root` `ossec.conf` again with the same request, API response:

```
{
  "data": {
    "affected_items": [
      "master-node"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully updated in specified node",
  "error": 0
}
```

As we can see, the configuration was updated despite the `root:root` ownership of the file. How can this be possible? The WazuhError with code 1126 is raised here, when we try to update the configuration.

```python
def write_ossec_conf(new_conf: str):
    """
    Replace the current wazuh configuration (ossec.conf) with the provided configuration.

    Parameters
    ----------
    new_conf: str
        The new configuration to be applied.
    """
    try:
        with open(common.ossec_conf, 'w') as f:
            f.writelines(new_conf)
    except Exception:
        raise WazuhError(1126)
```

The function was called inside the update_ossec_conf function of wazuh/manager.py:

```python
...
    backup_file = f'{common.ossec_conf}.backup'
    try:
        # Check a configuration has been provided
        if not new_conf:
            raise WazuhError(1125)

        # Check if the configuration is valid
        validate_wazuh_xml(new_conf, config_file=True)

        # Create a backup of the current configuration before attempting to replace it
        try:
            copyfile(common.ossec_conf, backup_file)
        except IOError:
            raise WazuhError(1019)

        # Write the new configuration and validate it
        write_ossec_conf(new_conf)
        is_valid = validate_ossec_conf()

        if not isinstance(is_valid, dict) or ('status' in is_valid and is_valid['status'] != 'OK'):
            raise WazuhError(1125)
        else:
            result.affected_items.append(node_id)
        exists(backup_file) and remove(backup_file)
    except WazuhError as e:
        result.add_failed_item(id_=node_id, error=e)
    finally:
        exists(backup_file) and safe_move(backup_file, common.ossec_conf)
...
```

As we can see, the error generated (1126) is handled at the end of the code snippet and right after that; in the finally section, we use safe_move to copy the backup back as an error was raised and the original file must be restored.

Finally, as we said in the last comment, the safe_move function restores the backup with ossec:ossec permissions and this way we have the situation I was talking about at the beginning of this comment: ossec.conf file with `root:root` ownership changed its ownership to `ossec:ossec`.

This investigation will be mentioned in the issues that are going to be opened to fix `save_move` usages and review backups generations.

As I said, this investigation reinforces the summary of the last comment: the API could not change the file permissions and/or ownership so we think that it may have been changed before, by hand possibly.

**Comment by mcarmona99** [comment]
## Issue update


After having a look at the master's `api.log` (11/19/2021), we can see that before the error with code 500, there are a lot of logs showing API requests resulting in 400 error codes. These requests are to the endpoint `GET /cluster/{node_id/stats/analysisd`.


```
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/configuration/validation" with parameters {} and body {} done in 1.012s: 200
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/<node_0>/stats/analysisd" with parameters {} and body {} done in 0.012s: 400
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/<node_1>/stats/analysisd" with parameters {} and body {} done in 0.016s: 400
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/<node_2>/stats/analysisd" with parameters {} and body {} done in 0.050s: 400
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/<node_3>/stats/analysisd" with parameters {} and body {} done in 0.082s: 400
2021/11/19 14:05:22 INFO: <user> <ip> "GET /cluster/<node_4>/stats/analysisd" with parameters {} and body {} done in 0.024s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_5>/stats/analysisd" with parameters {} and body {} done in 0.013s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_6>/stats/analysisd" with parameters {} and body {} done in 0.016s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_7>/stats/analysisd" with parameters {} and body {} done in 0.058s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_8>/stats/analysisd" with parameters {} and body {} done in 0.015s: 200
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_9>/stats/analysisd" with parameters {} and body {} done in 0.015s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_10>/stats/analysisd" with parameters {} and body {} done in 0.017s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_11>/stats/analysisd" with parameters {} and body {} done in 0.015s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_12>/stats/analysisd" with parameters {} and body {} done in 0.015s: 400
2021/11/19 14:05:23 INFO: <user> <ip> "GET /cluster/<node_13>/stats/analysisd" with parameters {} and body {} done in 0.089s: 200
2021/11/19 14:05:25 INFO: <user> <ip> "GET /cluster/status" with parameters {} and body {} done in 0.014s: 200
2021/11/19 14:05:25 INFO: <user> <ip> "GET /cluster/<node_10>/configuration" with parameters {"raw": "true"} and body {} done in 0.018s: 200
2021/11/19 14:05:28 INFO: <user> <ip> "PUT /cluster/<node_10>/configuration" with parameters {} and body {} done in 0.031s: 500
```

The 400 error codes are due to a `WazuhError` when trying to get the **analysisd** stats of a cluster node. The `WazuhError` is raised when catching an `IOError` when trying to read the `analysisd.state` file.

The 500 error could be caused by communication with sockets problems, as I said in the issue's comment https://github.com/wazuh/wazuh/issues/10931#issuecomment-1011196320.

Both errors make us think that the Wazuh service or some daemons could be in a wrong state.

No more errors can be seen in the manager or workers' ossec.log file; or in the master's api.log file.
