### ISSUE TITLE
How can I test for custom rootcheck rule?

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#1094]
Hello, team.

How can I test for custom rootcheck rule?  

Wazuh rootcheck_control. List of available agents:
   ID: 000, Name: localhost.localdomain (server), IP: 127.0.0.1, Active/Local

I restart wazuh-manager locally, but I can't test the rootcheck rule efficiently. I don't know when it run and what is the result.

**Comment by Justangatang** [comment]
I actually just tested a list of custom created Rootcheck rules against a Windows system, the Rootcheck runs every time an agent is restarted or on your defined frequency. Turn off the manager service, add the rules in etc/shared/default and when you turn the manager back on it restarts all the agents and runs the Rootcheck (takes about 5 minutes to complete the syscheck/rootcheck).

**Comment by vikman90** [comment]
Hi @iAklis,

That's the right answer. You may remove the default Rootcheck files from the configuration and leave your custom rules only. That should make your testing easier.

I assume you had no further questions related to this issue. Let me close it. Please reopen it if you have another question.

@Justangatang thanks for your reply.

Best.
