### ISSUE TITLE
Incorporate rotation capabilities for all kind of Wazuh logs 

### ISSUE THREAD

**Issue by alromeros** [wazuh/wazuh#10950]
## Main objective

This issue aims to modify https://github.com/wazuh/wazuh/issues/3072 in order to support rotation for **firewall**, **api**, **cluster**, **integrator**, and **active-response** logs.

## Description

With the refactor described in https://github.com/wazuh/wazuh/issues/3072, the log rotation capabilities in **Wazuh** will be considerably improved, deprecating the old daily rotation model that's been mandatory until now.

However, the current development only allows **alert**, **archive**, and **ossec** logs to be rotated, as shown in this sample configuration block:

```xml
...
  <logging>
    <log>
      <enabled>yes</enabled>
      ...
    </log>
    <alerts>
      <enabled>yes</enabled>
      ...
    </alerts>
    <archives>
      <enabled>yes</enabled>
      ...
    </archives>
  </logging>
...
```

This behavior leaves out certain types of logs which rotation may be useful for certain users, so, as said, the goal of this issue is to allow **firewall**, **api**, **cluster**, **integrator**, and **active-response** logs to also be rotated.

# DOD
- [ ] Enable rotation for `firewall.log` logs
- [ ] Enable rotation for `api.log` logs
- [ ] Enable rotation for `cluster.log` logs
- [ ] Enable rotation for `integrator.log` logs
- [ ] Enable rotation for `active-response.log` logs
- [ ] Modify the configuration-reading function to consider these additional logs.

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
