### ISSUE TITLE
Compare Cluster/API performance metrics: 4.2.5 - 4.3.0

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#10974]
Based on all the improvements made to the Cluster and the API in 4.3, we are going to make a performance comparison against 4.2.5. The issues involved in these improvements are the following:

- https://github.com/wazuh/wazuh/issues/10803 (API)
- https://github.com/wazuh/wazuh/issues/10765 (Cluster)
- https://github.com/wazuh/wazuh/issues/10770 (Cluster)
- https://github.com/wazuh/wazuh/issues/10816 (Cluster)
- https://github.com/wazuh/wazuh/issues/10912 (Cluster)
- https://github.com/wazuh/wazuh/issues/10946 (Cluster)

In this issue, we will compare the performance of the different tasks in the cluster, as well as the differences in resource usage.

#### Configurations

- 25 workers - 50000 agents

**Comment by yanazaeva** [comment]
## Task performance

### 50000 agents - 25 Workers

| v4.3.0 | v4.2.5 |
|-----------------------------------------------|--------------------------------------------|
|![image](https://user-images.githubusercontent.com/67015786/147477042-9e97cc59-f94c-4e7f-94d3-58c1132797db.png)||
|![image](https://user-images.githubusercontent.com/67015786/147477196-bcf38d79-41bd-4ad5-b14e-502985d0f137.png)||
|![image](https://user-images.githubusercontent.com/67015786/147477242-226edca0-5acb-4026-a654-cfbf01387818.png)||


Check the builds for further information:
- [v4.3.0](https://github.com/wazuh/wazuh/files/7780384/50000A-25W-Large.zip)
- v4.2.5

### 50000 agents - 10 Workers

| v4.3.0 | v4.2.5 |
|-----------------------------------------------|--------------------------------------------|
|||
|||
|||


Check the builds for further information:
- v4.3.0
- v4.2.5

**Comment by yanazaeva** [comment]
## Resources usage

### Setup phase - Wazuh clusterd

<table class="default"> 
  <tr>
    <th colspan="3"></th>
    <td colspan="4"><b>v4.3.0</b></td>
    <td><b>v4.2.5</b></td>
  </tr>
<tr>
    <th colspan="3"></th>
    <td><b>Child1</b></td>
    <td><b>Child2</b></td>
    <td><b>Father</b></td>
    <td><b>Total</b></td>
    <td><b>Total</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>59635.52592</td>
    <td></td>
    <td>70575.13043</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>123356.0</td>
    <td></td>
    <td>117064.0</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>647.73241</td>
    <td></td>
    <td>329.06819</td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>101680.32592</td>
    <td></td>
    <td>579796.42236</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>248208.0</td>
    <td></td>
    <td>965296.0</td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>1019.31331</td>
    <td></td>
    <td>5807.37168</td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>2.74074</td>
    <td></td>
    <td>4.58881</td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

**Comment by yanazaeva** [comment]
## Restart time comparison

<table class="default"> 
  <tr>
    <th colspan="2"></th>
    <td><b>Master</b></td>
    <td><b>Worker</b></td>
  </tr>
  <tr>
    <th rowspan="3">4.3.0</th>
    <td>Real</td>
    <td>0m1.265s</td>
    <td>0m1.314s</td>
  </tr>
<tr>
    <td>User</td>
    <td>0m1.221s</td>
    <td>0m1.258s</td>
  </tr>
<tr>
    <td>Sys</td>
    <td>0m0.050s</td>
    <td>0m0.056s</td>
  </tr>
<tr>
    <th rowspan="3">4.2.4</th>
    <td>Real</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td>User</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td>Sys</td>
    <td></td>
    <td></td>
  </tr>
</table>


To perform this comparison for version both versions, we added the lines specified below to the following files:
```
import sys
sys.exit(0)
```
- Right after line 404 in the [`server.py`](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/server.py) file to test it within the Master:
``` 
        self.logger.info(f'Serving on {server.sockets[0].getsockname()}')
        self.tasks.append(server.serve_forever)
        import sys
        sys.exit(0)
```
- And also in [`client.py`](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/client.py) right after line 107, to test it within the Worker: 
```
                self.client = protocol
                import sys
                sys.exit(0)
```

All the outputs can be found here.

**Comment by yanazaeva** [comment]
## Tasks performed during each phase

Using [this tool](https://github.com/wazuh/wazuh-qa/issues/1938), we calculated the time the setup phase takes for both versions:
- Version 4.3.0:
```
{'phases': {'setup_phase': ['2021/12/27 10:52:07', '2021/12/27 11:03:24'], 'stable_phase': ['2021/12/27 11:03:24', '2021/12/27 11:15:40']}, 'worker_nodes': 25}
```
- Version 4.2.4:
```
{'phases': {'setup_phase': ['2021/10/18 11:45:17', '2021/10/18 11:58:42'], 'stable_phase': ['2021/10/18 11:58:42', '2021/10/18 12:15:18']}, 'worker_nodes': 25}
```

### Setup phase
|   | 4.2.4  | 4.3.0  | 
|---|---|---|
| Agent info sync | 1373 | 1540 |
| Integrity check | 1389 | 1665 | 
| Integrity sync | 645 | 1391 |
| Local integrity | 91 | 73 | 

For 4.3.0 the setup phase takes 11:14 minutes meanwhile for version 4.2.4 it takes 13:25 minutes.

### Stable phase
|   | 4.2.4  | 4.3.0  | 
|---|---|---|
| Agent info sync | 902 | 1450 |
| Integrity check | 1397 | 1413 | 
| Local integrity | 71 | 59 | 

During the stable phase, we took into account the first 10 minutes.

**Comment by yanazaeva** [comment]
## File Descriptor comparison

<table class="default">
  <tr>
    <th rowspan="2"></th>
    <td colspan="3"><b>Father</b></td>
    <td colspan="4"><b>Child</b></td>
  </tr>
<tr>
    <td><b>Master</b></td>
    <td><b>Worker1</b></td>
    <td><b>Worker2</b></td>
    <td colspan="2"><b>Master</b></td>
    <td><b>Worker1</b></td>
    <td><b>Worker2</b></td>
  </tr>
  <tr>
    <th>4.2.4</th>
    <td>14</td>
    <td>13</td>
    <td>13</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr>
  <tr>
    <th>4.3.0</th>
    <td>36</td>
    <td>35</td>
    <td>35</td>
    <td>31</td>
    <td>33</td>
    <td>34</td>
    <td>34</td>
  </tr>
</table>

**Comment by yanazaeva** [comment]
## Resources usage

### Setup phase - Wazuh apid

<table class="default"> 
  <tr>
    <th colspan="3" rowspan="2"></th>
    <td colspan="4" style="text-align:center"><b>v4.3.0</b></td>
    <td style="text-align:center"><b>v4.2.5</b></td>
  </tr>
<tr>
    <td><b>Child1</b></td>
    <td><b>Child2</b></td>
    <td><b>Father</b></td>
    <td><b>Total</b></td>
    <td><b>Total</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>57548</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>57548</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>1.719</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>59537</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>60052</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>18.186</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>0.122</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>1.0</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>0.001</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>39</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>39</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>-8.359</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>39.051</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>40</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>0.001</td>
    <td>-</td>
    <td></td>
  </tr>
</table>

### Stable phase - Wazuh clusterd

<table class="default"> 
  <tr>
    <th colspan="3" rowspan="2"></th>
    <td colspan="4"><b>v4.3.0</b></td>
    <td><b>v4.2.5</b></td>
  </tr>
<tr>
    <td><b>Child1</b></td>
    <td><b>Child2</b></td>
    <td><b>Father</b></td>
    <td><b>Total</b></td>
    <td><b>Total</b></td>
  </tr>
  <tr>
    <th rowspan="6">USS(KB)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>57548</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>57548</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>4.696</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>60065</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>60084</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>0.297</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <th rowspan="6">CPU(%)</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>0</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>0.127</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>0.4</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>-4.425</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <th rowspan="6">FD</th>
    <td rowspan="3">Worker</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>39</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>39</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>2.304</td>
    <td>-</td>
    <td></td>
  </tr>
<tr>
    <td rowspan="3">Master</td>
    <td><b>Mean</b></td>
    <td></td>
    <td></td>
    <td>39.013</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Max</b></td>
    <td></td>
    <td></td>
    <td>40</td>
    <td></td>
    <td></td>
  </tr>
<tr>
    <td><b>Reg. cof.</b></td>
    <td></td>
    <td></td>
    <td>-0.000</td>
    <td>-</td>
    <td></td>
  </tr>
</table>
