### ISSUE TITLE
Set maximum zip size for cluster synchronization

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#10980]
|Wazuh version|Component|
|---|---|
| 3.X-4.3 | Wazuh cluster |

## Description

We have found that some things do not work as well as they should when the cluster has to synchronize very large files. This is something that we already detected and reported, in part, here: https://github.com/wazuh/wazuh/issues/10735

### Workflow
When a master has to send missing files to a worker, it first compresses them into a zip, here:
https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/core/cluster/master.py#L696

The worker is then notified that a file is about to be sent to it, which is done here:
https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/core/cluster/master.py#L701

When said worker is notified, he creates a task to wait for the zip that the master is going to send:
https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/core/cluster/worker.py#L712-L713

Finally, the master sends the file:
https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/core/cluster/master.py#L709-L714

### Problem
As it can be seen above, the cluster waits for the file during `self.cluster_items['intervals']['communication']['timeout_receiving_file']` seconds (120 by default). If the compressed file that the master is sending is too big, it could exceed that time and the task would be canceled without processing any files.

As a consequence, the same process will be repeated in each Integrity check/Integrity sync iteration, using resources of both master and worker. And what is worst, the synchronization will never be completed unless the timeout is increased.

### Suggested fix
We should set a maximum size for the resulting zip when compressing files. If the size is exceeded, nothing else would be added to the zip and the Integrity synchronization would be produced with part of the files only (those who fitted in the zip). Probably a warning log should be printed in this case.

With this we will ensure that very large files are not sent from one node to another, reducing the possibility of timeout during synchronization. 

Files that could not be synced in the first iteration will be synced in subsequent iterations.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
## Issue update

I was directly accessing the parameters of the ZipFile object used in the cluster to compress the files, in order to determine the size of each file as it was added. However, the result did not match what the Zip file actually took up afterward.

For this reason, I have decided to directly use the `os.path.getsize(zip_file_path)` function to check the actual size of the zip after adding each of the files. 

In case the specified maximum size is exceeded, no new files are added except the json with metadata. However, in such a case the content of said JSON does not match what is actually compressed. For this reason, all the files that do not fit in the zip after exceeding the maximum size are also removed from the metadata JSON.

I have compared the time it takes for the [compress_file](https://github.com/wazuh/wazuh/blob/a8122d460d3eb8165a4cd90c58ae28fd9e39bc11/framework/wazuh/core/cluster/cluster.py#L288-L330) function to compress 50000 agent-groups before and after changes:

Before changes:
```
3.570443s
3.547452s
3.514274s
3.419010s
```

After changes:
```
3.733069s
3.718031s
3.943082s
3.808906s
```

The times are a bit higher, mainly due to checking the size of the zip after adding each of the 50000 files. However, there is not a very big difference. 

It would be necessary to determine if it is worth using some type of compression. This would help to send the files faster over the network. However, it would take longer to create the zip. Here's an example with compression level 9:
Compressing:
```
TIME USED: 4.826227 | SIZE: 6844871
TIME USED: 4.982539 | SIZE: 6844871 -> 6,5 MB
```
Without compressing:
```
TIME USED: 3.975285 | SIZE: 14466911
TIME USED: 4.008591 | SIZE: 14466911 -> 13,79 MB
```

It can be seen that in these use cases, the time it takes for the parent process to compress the files can be high. We should also study whether it is useful to do this task in a child process.

**Comment by Selutario** [comment]
## Issue update

After a meeting with the team, it was concluded that some more features need to be added:
- A maximum size should be established which can never be exceeded by a single file.
- The maximum size allowed for zips should be dynamic. The more workers connected, the smaller it must be.

This behavior involves measuring the size of each file before compressing it, which as we saw in the previous issue update, makes the process a bit slower.

**Comment by AdriiiPRodri** [comment]
## Status update (WIP)

Based on the times mentioned here https://github.com/wazuh/wazuh/issues/10980#issuecomment-981669468, we have decided to investigate if it is possible to compress the files in a faster way. As for the space occupied by the compressed file, in principle, we are not concerned.

After several tests, we have observed that by compressing the contents of the files using [zlib - Compression compatible with gzip - Python 3.9.9 documentation](https://docs.python.org/3.9/library/zlib.html), the compress function consumes about three times less than the Zipfile implementation.

Since we only compress the content of the files, we have that we do not really maintain the structure of the folders, to solve this, we are going to add the path of each file to the beginning of the content of the same one and we will establish two separators, one to separate the path of the content and another to separate each file. Example:

```
cat /var/ossec/queue/agent-groups/001
default
```

In this case, the compressed file would look something like this (once decompressed):

```
/var/ossec/queue/agent-groups/001-*-CONTENT|@|
```

Where `-*-` is the path separator and `|@|` is the file separator.
Here we can see a comparison between the current version and this implementation:

### Current

```
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 compress_testing.py

[TESTING COMPRESS] Compress time: 4.608377926000685
[SIZE] 17227587

[TESTING DECOMPRESS] Decompress time: 11.785013188000448

```
### ZLIB

```
root@wazuh-master:/# /var/ossec/framework/python/bin/python3 compress_testing.py

[TESTING COMPRESS] Compress time: 1.4265129609993892
[SIZE] 960358

[TESTING DECOMPRESS] Decompress time: 3.3745801339973696

```

As we can see the file size is also about half the size of the current implementation. As for the decompression phase, we see that it is about three times faster with the new implementation.

We are still testing to determine if this is a good solution.

**Comment by Selutario** [comment]
# Issue update

## Dynamic zip size
We decided that the maximum zip size that should be allowed in the cluster should vary in the master depending on the number of connected nodes. 

The reason is that, the more nodes in the cluster, the more zips the master has to send in each iteration. Sending zips can be slow when they are big, so a node may have to wait too long if the master is sending zips to other workers first. If smaller zips are sent, the process should be able to complete in more workers.

Here we can see a graph (generated on [this page](https://arachnoid.com/polysolve/)) with the time it takes to the master to send a zip containing different sizes files:
![image](https://user-images.githubusercontent.com/23361101/144604670-7f30193d-f945-4a8a-a48a-bd65c5ebc565.png)

The X-axis indicates the size of the file in MB and the Y-axis the time it took to complete the submission. The formula of the curve that best fits these points is:

```
f(x) =  1.1278804999999128e+000 * x^0
     +  1.6035317484849293e-002 * x^1
     +  1.0496916666666525e-004 * x^2
```

With it we can estimate how long it would take to send larger files:

|Size (MB)|Time to send file (s)|
|-|-|
|500|35.387831|
|600|48.537971|
|700|63.787494|
|800|81.136401|
|900|100.584691|
|1000|122.132365|

With this data and taking into account that the default maximum time that a worker waits for a file before a timeout is 120 seconds, we can determine that in no case zips greater than 1 GB should be created. You can use this little script to estimate more values: [time_to_send_zip.zip](https://github.com/wazuh/wazuh/files/7649703/time_to_send_zip.zip)

A quick example/proposal would be that the cluster should create zips of 900MB maximum. This should be divided by the total number of nodes connected. For example, if there are 9 workers, the master should create zips of 100MB maximum. Obviously, a minimum size must be established to avoid unsynchronizable files. 

# Problems with zip limitation

The zip size limitation (both static and dynamic) presents some problems that we should study and test carefully before being implemented in production:
- If we want to prevent large files from being compressed, we have to determine their size **before** putting them in the zip. This worsens the performance of the function but one of the requirements was not to make it worse.

- When compressing a file, it includes metadata. Beause of this, the size of each file is not the same as the file of said file when compressed. For instance, a agent-group file is 7 bytes according to `os.path.getsize(file)`. However, when compressing it, the zip increases 61 bytes. This makes it an unreliable feature. 

- If a file does not fit, the master will try to compress it and send it every 9s and it would never succeed. This is an example of the master's logs when that happens:
  ```
  2021/12/03 08:49:28 INFO: [Worker worker1] [Integrity sync] Files to create in worker: 1 | Files to update in worker: 0 | Files to delete in worker: 0 | Files to receive: 0
  2021/12/03 08:49:28 WARNING: [Worker worker1] [Main] The following file is bigger than allowed and won't be compressed: queue/agent-groups/005.
  ```
  And this in the worker, every 9 seconds (the worker was told that sync was required and he received a zip file but it was empty):
  ```
  2021/12/03 08:49:18 INFO: [Worker worker1] [Integrity sync] Files to create: 0 | Files to update: 0 | Files to delete: 0 | Files to send: 0
  ```

- We could add the large files to an excluded list. But who would be responsible in that case to check if their size has changed so they are removed from the list? Should the [get_files_status](https://github.com/wazuh/wazuh/blob/15bb33d03a4612ee084f7fdcbe096f8513c21882/framework/wazuh/core/cluster/cluster.py#L189-L218) function get the size of each file as well?

- If there is a large file but it does not exceed the maximum size, it can cause the synchronization of many almost empty zips. This is because, once the size of a file + the size of the zip being created exceeds the allowed size, no more files are zipped. Since the order of the files to be zipped is different each time (the list comes from a set), it is not ensured that the big file will be the first one to be zipped in the next Integrity sync iteration. The problem, represented in the following image, could therefore be repeated multiple times:
  ![image](https://user-images.githubusercontent.com/23361101/144606704-d2470999-14f3-4b27-b2e7-80cda8e63485.png)

- To avoid the previous problem, if a file was large, we could still check if there are other files that do fit in the zip. However, this also negatively affects performance.

- Partial syncs could occur. For example, that the folder of a multigroup appears in the workers but not its content. There are not enough tests nor can we thoroughly test what the behavior of Wazuh would be in all possible cases.

- It is a dangerous change since any error can interrupt all the Integrity synchronizations of the cluster.

- There have been many changes to the cluster in 4.3 and the more changes we make (especially those that are not currently tested with system tests), the more difficult it will be to ensure that everything works correctly.

**Comment by Selutario** [comment]
The changes in this issue have finally been developed as part of:

- #11184
