### ISSUE TITLE
Review deprecated settings in log rotation

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#11009]
## Description

The objective of this issue is to check the messages and settings regarding deprecated configuration, after changes made in development https://github.com/wazuh/wazuh/issues/3072

After updating the branch of the [PR](https://github.com/wazuh/wazuh/pull/3175) with `master`, it is necessary to check that all the configurations that are involved in old functionalities have been correctly deprecated, so that they remain functional even by setting them in the configuration.

## DoD
- [ ] Review deprecated settings
- [ ] Take a log referring to the deprecated component
- [ ] Keep functionality with old settings

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
