### ISSUE TITLE
Check functionality of modules affected by log rotation

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#11008]
## Description

The objective of this issue is to check and, if necessary modify, the possible modules affected by the changes made in the development https://github.com/wazuh/wazuh/issues/3072

There are some modules that directly read files (`.log` or `.json`) that with the new changes can be rotated, so they can affect their functionality, and it is necessary to contemplate them exhaustively to avoid errors.

Therefore, it would be necessary to consider all the modules that can be affected by rotated files (`archives`, `alerts`, `ossec`...)

Some modules to view can be:
- `Maild`
- `Reportd`

Even so, it would be necessary to check and review all possible cases (especially if files that previously did not rotate are rotated).

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
