### ISSUE TITLE
Hi, I can't display the result of the whoami or hostname command. How can this be done using path like this.      C:\Windows\System32\whoami.exe

### ISSUE THREAD

**Issue by revolverror** [wazuh/wazuh#11014]
|Wazuh version| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

**Comment by FrancoRivero** [comment]
Hi @revolverror, 
Thank you for using Wazuh! 
You should open a new powershell or cmd Windows from your OS, and execute `whoami \ALL`, so you will have the information about your user and your groups.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/whoami

You could ask faster in https://wazuh.slack.com/archives/C0A933R8E
Regards
