### ISSUE TITLE
firewall-drop.sh missing

### ISSUE THREAD

**Issue by bsharin** [wazuh/wazuh#1103]
## Description
From version 3.4 to version 3.5, it seems that `firewall-drop.sh` got left out of the active-response folder located at `/var/ossec/active-response/bin/`

## References
https://documentation.wazuh.com/3.x/user-manual/capabilities/active-response/remediation-configuration.html#add-an-ip-to-the-iptables-deny-list

**Related issue**:
N/A
**Related PR**:
N/A
**Branch**:
3.5
**Documentation**:
Current documentation does not mention any changes to the firewall-drop.sh architecture

**Comment by vikman90** [comment]
Hi @bsharin,

It seems to be an issue in the DEB/RPM packages when selecting the correct firewall-drop script. We will fix it as soon as possible.

In the meantime, this command will fix this problem:
```sh
cp -p /var/ossec/active-response/bin/default-firewall-drop.sh /var/ossec/active-response/bin/firewall-drop.sh
```

Thank you very much for reporting this issue.
Best regards.

**Comment by bsharin** [comment]
Hi @vikman90,

Thanks for the reply.  It looks like `default-firewall-drop.sh` is a different script than `firewall-drop.sh`.  `firewall-drop.sh` uses iptables.  I am not as familiar with `default-firewall-drop.sh`, but looking at the script it appears it is using pfctl.  I have copied `firewall-drop.sh` from an older installation of 3.4 into my 3.5 agent installation and looks like that is working as a stop gap until 3.5 is resolved.

**Comment by vikman90** [comment]
Hi @bsharin,

You are completely right, we have accidentally overwritten the default-drop script for Linux with the OpenBSD's script.

I've fixed it in this PR: https://github.com/wazuh/wazuh/pull/1114. This fix will apply in the next release.

Thank you again for your feedback.
Best regards.
