### ISSUE TITLE
Unable to Index Event to Elasticsearch

### ISSUE THREAD

**Issue by eternalyperplxed** [wazuh/wazuh#1104]
We have a distributed environment that we just stood up.  Wazuh manager 3.5 with Filebeat 6.3.2 going to Logstash 6.3.2 -> Elasticsearch 6.3.2.  The templates were loaded with no errors, however Logstash generates the following error:

[WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2018.08.14", :_type=>"doc", :_routing=>nil}, #<LogStash::Event:0x4dbc215f>], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2018.08.14", "_type"=>"doc", "_id"=>"O84GOmUBhncHY_vB9hi5", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [wazuh-alerts-3.x-2018.08.14] as the final mapping would have more than 1 type: [wazuh, doc]"}}}}

Where is the extra _type mapping coming from since ELK no longer supports document types.

**Comment by JuanjiJG** [comment]
Hello @eternalyperplxed,

I'm sorry you're having problems.

Did you perform an upgrade from a previous version of the Elastic Stack, or is it a fresh-new installation?

Could you please send me your Logstash and Filebeat configuration files?
```
cat /etc/filebeat/filebeat.yml
cat /etc/logstash/conf.d/01-wazuh.conf
```

We'll also need your current Elasticsearch templates and mapping for the Wazuh template. Please, send me the output from these commands:
```
curl -XGET localhost:9200/_cat/indices?v
curl -XGET localhost:9200/_template/wazuh?pretty
```

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @eternalyperplxed,

It's been more than a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you have problems or questions about Wazuh.

Regards,
Juanjo
