### ISSUE TITLE
syscollector catch std::stoi() exception

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh#11079]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.5 | syscollector | Agent | Source | CentOS 7.4 |

I have a CentOS7 agent which can't collector `sys_ports` information.
It looks like an integer overflow problem with the socket inode.

#### wazuh log
```bash
wazuh-modulesd:syscollector[21479] wm_syscollector.c:78 at wm_sys_log(): ERROR: stoi
```
#### /proc/net/tcp

```log
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode 
 121: XXXXXXXX:9996 YYYYYYYY:1A85 01 00000000:00000000 00:00000000 00000000     0        0 4274126910 1 ffff88304d670000 20 4 30 10 169
```

#### code

```cpp
// wazuh\src\data_provider\src\ports\portLinuxWrapper.h
int32_t inode() const override
{
    return std::stoi(m_fields.at(INODE));
}
```

**Comment by Dwordcito** [comment]
Hi @jnasselle 

Please, complete the RCA for this case. Understand that it is necessary to maintain the inode to be able to bind the port with the process that interacts in the future. -> https://github.com/wazuh/wazuh/issues/535

DoD
- [ ] Reproduce with/add unit tests, (must fail to throw exception)
- [ ] Analyze if the entire flow is capable of using uint64 and has no overflow. (local synchro and remote synchro with manager)
- [ ] Apply fix, after team discussion.
- [ ] PR, CI PASS.

**Comment by jnasselle** [comment]
## Reproducing the error
There's no easy/practical way to create a escenario with this problem, but could be done by applying the next patch to sysinfo ports UT
```diff
diff --git a/src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp b/src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp
index 6f1109d000..f37e758312 100644
--- a/src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp
+++ b/src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp
@@ -49,7 +49,7 @@ TEST_F(SysInfoPortTest, Test_SPEC_Data)
     EXPECT_CALL(*mock, remotePort()).Times(1).WillOnce(Return(5));
     EXPECT_CALL(*mock, txQueue()).Times(1).WillOnce(Return(6));
     EXPECT_CALL(*mock, rxQueue()).Times(1).WillOnce(Return(7));
-    EXPECT_CALL(*mock, inode()).Times(1).WillOnce(Return(8));
+    EXPECT_CALL(*mock, inode()).Times(1).WillOnce(Return(4274126910));
     EXPECT_CALL(*mock, state()).Times(1).WillOnce(Return("9"));
     EXPECT_CALL(*mock, pid()).Times(1).WillOnce(Return(10));
     EXPECT_CALL(*mock, processName()).Times(1).WillOnce(Return("11"));
@@ -62,7 +62,7 @@ TEST_F(SysInfoPortTest, Test_SPEC_Data)
     EXPECT_EQ(5, port.at("remote_port").get<int32_t>());
     EXPECT_EQ(6, port.at("tx_queue").get<int32_t>());
     EXPECT_EQ(7, port.at("rx_queue").get<int32_t>());
-    EXPECT_EQ(8, port.at("inode").get<int32_t>());
+    EXPECT_EQ(4274126910, port.at("inode").get<int32_t>());
     EXPECT_EQ("9", port.at("state").get_ref<const std::string&>());
     EXPECT_EQ(10, port.at("pid").get<int32_t>());
     EXPECT_EQ("11", port.at("process").get_ref<const std::string&>());
```
UT execution fails as expected 
```
./sysInfoPort_unit_test 
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from SysInfoPortTest
[ RUN      ] SysInfoPortTest.Test_SPEC_Data
/root/repos/wazuh/src/data_provider/tests/sysInfoPorts/sysInfoPort_test.cpp:65: Failure
Expected equality of these values:
  4274126910
  port.at("inode").get<int32_t>()
    Which is: -20840386
[  FAILED  ] SysInfoPortTest.Test_SPEC_Data (0 ms)
[----------] 1 test from SysInfoPortTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SysInfoPortTest.Test_SPEC_Data

 1 FAILED TEST
```
## Fix analysis
As @Dwordcito, changing `int32_t` to `int64_t` in the ports interface (and implementation obviously) will be enough to handle the number of inodes.

The next items were investigated

:green_circle:  SQlite INTEGER size: `INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.`. [Ref](https://www.sqlite.org/datatype3.html)
:green_circle: Sync between agent mirrored DBs, agent and manager, will be handled using JSON format, which has no limit for integers. [Ref](https://www.json.org/json-en.html)
