### ISSUE TITLE
Only on Agent: "wazuh-modulesd: ERROR: Unknown module 'vulnerability-detector'"

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1107]
Hello,

### Situation
the wodle _vulnerability-detector_ seems to work impeccably on Wazuh _server/manager_ host but not on _agent_ hosts. On server-side the _vulnerability-detector_ is already configured per default with the package installation, on agent-side not, why? Both, on server-side and agent-side the latest release _3.5.0-1_ is installed, both Debian 8 (Jessie) OS (same issue for Debian OS 7 (Wheezy):

**Manager/Server**
`dpkg --list wazuh-manager`
`Desired=Unknown/Install/Remove/Purge/Hold`
`| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend`
`|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)`
`||/ Name                                                  Version                         Architecture                    Description`
`+++-=====================================================-===============================-===============================-===============================================================================================================`
`ii  wazuh-manager                                         3.5.0-1                         amd64                           Wazuh helps you to gain security visibility into your infrastructure by monitoring hosts at an operating system`

**Agent**
`dpkg --list wazuh-agent`
`Desired=Unknown/Install/Remove/Purge/Hold`
`| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend`
`|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)`
`||/ Name                                                  Version                         Architecture                    Description`
`+++-=====================================================-===============================-===============================-===============================================================================================================`
`ii  wazuh-agent                                           3.5.0-1                         amd64                           Wazuh helps you to gain security visibility into your infrastructure by monitoring hosts at an operating system`

**Manager/Server Configuration**
_ossec.conf_ shipped with installation packet:
`<wodle name="vulnerability-detector">`
`    <disabled>no</disabled>`
`    <interval>1h</interval>`
`    <run_on_start>yes</run_on_start>`
`[...]`
`  </wodle>`

The _oval_ files are located below: 
`ls -la /var/ossec/wodles/oscap/content/`
`total 98020`
`drwxr-x--- 2 root ossec     4096 Aug 13 10:53 .`
`drwxr-x--- 3 root ossec     4096 Aug 13 10:53 ..`
`-rw-r----- 1 root ossec 35227575 Aug  9 18:56 cve-debian-8-oval.xml`
`-rw-r----- 1 root ossec 31312202 Aug  9 18:56 cve-debian-9-oval.xml`
`-rw-r----- 1 root ossec 31961324 Aug  9 18:56 cve-ubuntu-xenial-oval.xml`
`-rw-r----- 1 root ossec   623818 Aug  9 18:56 ssg-debian-8-ds.xml`
`-rw-r----- 1 root ossec   597499 Aug  9 18:56 ssg-ubuntu-1404-ds.xml`
`-rw-r----- 1 root ossec   627107 Aug  9 18:56 ssg-ubuntu-1604-ds.xml`

### Agent Configuration
no matter where you palce it in_agent.conf_ or _ossec.conf_, it doesn't work:

`  <wodle name="vulnerability-detector">`
`    <disabled>no</disabled>`
`    <interval>1h</interval>`
`    <run_on_start>yes</run_on_start>`
`  </wodle>`

The _oval_ files are located below: 
`ls -la /var/ossec/wodles/oscap/content/`
`total 98020`
`drwxr-x--- 2 root ossec     4096 Aug 13 10:53 .`
`drwxr-x--- 3 root ossec     4096 Aug 13 10:53 ..`
`-rw-r----- 1 root ossec 35227575 Aug  9 18:56 cve-debian-8-oval.xml`
`-rw-r----- 1 root ossec 31312202 Aug  9 18:56 cve-debian-9-oval.xml`
`-rw-r----- 1 root ossec 31961324 Aug  9 18:56 cve-ubuntu-xenial-oval.xml`
`-rw-r----- 1 root ossec   623818 Aug  9 18:56 ssg-debian-8-ds.xml`
`-rw-r----- 1 root ossec   597499 Aug  9 18:56 ssg-ubuntu-1404-ds.xml`
`-rw-r----- 1 root ossec   627107 Aug  9 18:56 ssg-ubuntu-1604-ds.xml`

### _ossec.log_ Manager/Server
At least the vulnerability scanner starts and ends every hours although with interprocess communication errors obviously between _wazuh-modulesd_ and _wazuh-db_:
`2018/08/15 12:40:56 wazuh-modulesd:vulnerability-detector: INFO: (5452): Starting vulnerability scanning.`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-modulesd:vulnerability-detector: INFO: (5453): Vulnerability scanning `finished.`

The _wazuh-modulesd_ in debug mode shows the following output:
`wazuh-modulesd -t -dd`
`2018/08/15 12:58:41 wazuh-modulesd: DEBUG: Logpath read: /var/log/osquery/osqueryd.results.log`
`2018/08/15 12:58:41 wazuh-modulesd: DEBUG: configPath Readed: /etc/osquery/osquery.conf`

### _ossec.log_ Agent
Here the scanner does not start at all:
`2018/08/15 12:07:46 wazuh-modulesd: ERROR: Unknown module 'vulnerability-detector`

The _wazuh-modulesd_ in debug mode shows the following output:
`wazuh-modulesd -t -dd`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: (1228): Element 'log_format' without any option.`
`2018/08/15 13:01:55 wazuh-modulesd: ERROR: Unknown module 'vulnerability-detector'`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: Calling os_read_agent_profile().`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: os_read_agent_profile() = [debian, debian8, debian8.11]`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: agent_config element does not have any attributes.`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: Logpath read: /var/log/osquery/osqueryd.results.log`
`2018/08/15 13:01:55 wazuh-modulesd: DEBUG: configPath Readed: /etc/osquery/osquery.conf`

**Comment by vikman90** [comment]
HI @juergenc,

Vulnerability Detector is a manager-side component, it compares the data gathered by Syscollector (list of packages installed in the hosts) with the CVE database to determine which applications are vulnerable in your agents.

In other words, please enable Syscollector in the agents, and Vulnerability Detector in the manager only.

This tutorial may help you: [Wazuh Documentation → Track down vulnerable applications](https://documentation.wazuh.com/current/learning-wazuh/vuln-detection.html).

Hope it help. If you run into any other trouble please let us know.
Best regards.

**Comment by juergenc** [comment]
Hello @vikman90 ,

thank you for your quick and comprehensive response. Now, then there is only left the interprocess communication on the manager-side:
`2018/08/15 12:40:56 wazuh-modulesd:vulnerability-detector: INFO: (5452): Starting vulnerability scanning.`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-db: ERROR: at run_worker(): send(34): Broken pipe (32)`
`2018/08/15 12:40:56 wazuh-modulesd:vulnerability-detector: INFO: (5453): Vulnerability scanning finished.`

Does it mean _wazuh-db_ daemon has problems to insert the results into the SqLite databases on the manager?

**Comment by vikman90** [comment]
Hi @juergenc,

Answering your questions:

1. This is a bug: when Vulnerability detector ends scanning an agent, it requests Wazuh DB to update the timestamps of package triaging and closes the connection. But Wazuh DB tries to send a positive confirmation to Vulnerability Detector. Since the connection is closed, it reports that error.

    I've just sent a PR to fix it: https://github.com/wazuh/wazuh/pull/1111. However, it is not serious, you can ignore it so far.

2. Those files are not for Vulnerability Detector but for OpenSCAP. In fact, that is the reason why we designed Vulnerability Detector to run in the manager. Feel free to delete those files if you don't use OpenSCAP.

Thank you for reporting this issue.
Best regards.

**Comment by juergenc** [comment]
Hello @vikman90,

I am  a little bit confused about what you said in your penultimate comment: _"Vulnerability Detector is a manager-side component..."_. What I observed is rather the opposite, the Python script _oscap.py_ and all the other children forked by _wazuh-modulesd_ are started on every agent where vulnerability-detector is configured. And in fact the Python script _oscap.py_ opens the shipped OVAL file on agent-side.

**Comment by albertomn86** [comment]
https://github.com/wazuh/wazuh/pull/1130
