### ISSUE TITLE
Process events from more AWS Services

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1108]
Hello team,

Currently, we are only able to process events from AWS Cloudtrail using an S3 Bucket but an S3 Bucket can also [have events from other AWS Services](https://docs.aws.amazon.com/firehose/latest/dev/what-is-this-service.html) such as:

* Guard Duty
* IAM
* Macie
* VPC Flow
* Inspector
* Cloudtrail

IAM and Inspector events can be used to enrich Cloudtrail events, the rest of the services need their own rules.

Currently defined tasks:
* [x] Refactor actual code to make it easier to add support for other log sources (9b96a831220a6750c761324c53ab055c3aa683ef)
* [x] Add a parser for firehouse events: multiple JSON objects in the same line with no separation (ab9f2fc0ae948056e6b723b4c02f296caa9632f3).
* [x] Add a parser for VPC Flow events: TSV files (ab9f2fc0ae948056e6b723b4c02f296caa9632f3). 
* [x] Add support for zip compression (ab9f2fc0ae948056e6b723b4c02f296caa9632f3).
* [x] Remove "cloudtrail" word from actual configuration (b80308852e483868b9e8dc055c6807a656620ca2).
* [x] Develop [Guard Duty](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings.html#guardduty_working-with-findings) rules. Use [_severity field_](https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_findings.html#guardduty_findings-severity) to define rule levels (a03d720084710fa723cdad2cb0d51691d51a0287 & https://github.com/wazuh/wazuh-ruleset/commit/4430c31d9b946f0d1fbd2f9a9f9fe3d672626943).
* [x] Develop [Macie Alerts](https://docs.aws.amazon.com/macie/latest/userguide/macie-alerts.html#macie-alert-categories) rules. Use [_severity field_](https://docs.aws.amazon.com/macie/latest/userguide/macie-alerts.html#macie-alert-severity) to define rule levels (a03d720084710fa723cdad2cb0d51691d51a0287 & https://github.com/wazuh/wazuh-ruleset/commit/3d5a85f4a94ed47e61f4687be329d9589cd55666 & eb395c4088bcb28da96c438d521362dcc2a92d3d).
* [x] Develop [VPC Flow](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html#flow-log-records) rules. Use _log status_ field to define rules levels (870b3703f4291b205dab25c1539b0e8adef70a67 & https://github.com/wazuh/wazuh-ruleset/commit/a489ad6c629b33f3c9878164205ac124be3bd43c).
* [x] Develop IAM and Inspector rules (https://github.com/wazuh/wazuh-ruleset/commit/993878e0ca065a9b89b45da0e9db80eacc2887f0).
* [x] Add srcip field to all alerts (59582bba5909b114ef0bd5c4998124d83d04f615).

* [ ] Add support for [lambda functions in VPC Flow logs](https://aws.amazon.com/es/blogs/security/how-to-visualize-and-refine-your-networks-security-by-adding-security-group-ids-to-your-vpc-flow-logs/).
* [ ] Add support for snappy compression.
* [ ] Add IAM and Inspector data to Cloudtrail events.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Here's a little update:

### Refactor actual code to make it easier to add support for other log sources
The code was too focused on processing cloudtrail logs:
* The directory structure in the bucket,
* Log filename
* JSON log structure,
* etc

This was a problem when processing firehouse logs, the conditions weren't met. 

To fix this problem, I've made an abstract class which represents a bucket and a subclass which inherits from the abstract one which includes all cloudtrail specific method.
https://github.com/wazuh/wazuh/blob/9b96a831220a6750c761324c53ab055c3aa683ef/wodles/aws/aws-cloudtrail.py#L162-L166
https://github.com/wazuh/wazuh/blob/9b96a831220a6750c761324c53ab055c3aa683ef/wodles/aws/aws-cloudtrail.py#L507-L510

### Parsing Firehouse events
Next, I've added a class for processing firehouse logs. 

#### Format
Documentation: https://docs.aws.amazon.com/firehose/latest/dev/basic-deliver.html#format
Firehouse events files contain multiple events concatenated without separation (by default):
> _Data Firehose concatenates multiple incoming records based on buffering configuration of your delivery stream. [...] You might want to add a record separator at the end of each record before you send it to Kinesis Data Firehose._

As you can read in the cited text above, firehouse logs are just concatenated events without separation. It's not possible to load this kind of file using the `json.load` function, but it's possible to do it using the following:

https://github.com/wazuh/wazuh/blob/ab9f2fc0ae948056e6b723b4c02f296caa9632f3/wodles/aws/aws-cloudtrail.py#L424-L428

The VPC Flow logs are a bit more special since they're stored in TSV format (https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/flow-logs.html#flow-log-records) but they can be easily loaded using Python's CSV library.

#### Filenames
Documentation: https://docs.aws.amazon.com/firehose/latest/dev/basic-deliver.html#s3-object-name
Firehouse S3 objects don't include file type extension. Its structure is as follows:
> _The Amazon S3 object name follows the pattern DeliveryStreamName-DeliveryStreamVersion-YYYY-MM-DD-HH-MM-SS-RandomString, where DeliveryStreamVersion begins with 1 and increases by 1 for every configuration change of the Kinesis Data Firehose delivery stream._

Using this information, I've taken some decisions:
* Check file extension to know type of logs: firehouse logs don't have `.json` extension but cloudtrail ones do:
      https://github.com/wazuh/wazuh/blob/ab9f2fc0ae948056e6b723b4c02f296caa9632f3/wodles/aws/aws-cloudtrail.py#L430-L440
* Using user defined prefix only (in cloudtrail the prefix would be `<user's prefix>AWSLogs/<account_id>/...`):
    https://github.com/wazuh/wazuh/blob/ab9f2fc0ae948056e6b723b4c02f296caa9632f3/wodles/aws/aws-cloudtrail.py#L670-L671

I hope this little summary helps to understand what I'm doing.

Best regards,
Marta

**Comment by UranusBytes** [comment]
@mgmacias95 Wow - this all looks absolutely awesome!  :clap:

I had started down the path of ingesting Trusted Advisor checks in wazuh/wazuh#922 but it would likely be a couple of weeks before I can give this any serious attention.  If you're able to make any progress on the general idea by whatever means you think is best, I think that would be a huge win for Wazuh users.  

I know that Trusted Advisor has limit functionality for AWS users without support contracts, so to expand upon the security checks done by Trusted Advisor, my next thought was to integrate Prowler - https://github.com/toniblyx/prowler .  It can output reports in json, has minimal dependencies, and includes all the CIS benchmarks as well as a large number of other best practices AWS configurations.  Not sure if that is best done as part of the AWS wodle, as a separate wodle, or leave as a command wodle that is parsed with it's own decoder/rules...

Hopefully soon I can get some cycles to help with this again!

Jeremy

**Comment by mgmacias95** [comment]
Hi @UranusBytes,

Thank you so much 😄 !! I'm glad you like this idea of supporting multiple AWS services. It has been developed on top of your work!

About the Trusted Advisor and Prowler, I see that it works completely different from what we have now (analyze S3 buckets) so I'd do it on a separate module. The (almost old) CloudTrail integration has been designed to analyze and report bucket logs. Adding different types of reporting sources would make it more complicated than it already is.

New rules will need to be developed. Since it reports JSON logs, rules will be easily developed. I've done rules for Guard Duty, Macie and VPC Flow in a few days. That's not a problem 😄 .

We can continue this discussion in #922.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Update:

While testing the final version, which has already been merged I found out some rules were not working:
https://github.com/wazuh/wazuh/blob/498832c7defb1e50c705fb6e73e31a315a01ddf5/etc/rules/0350-amazon_rules.xml#L76-L87

The field `responseElements` was expected to be an object but now is a String. That change came from a bug reported and fixed by @UranusBytes in https://github.com/wazuh/wazuh/pull/913#issuecomment-410292092. My proposal to fix this is to make sure those fields are always a dictionary, instead of making sure those fields are always string. 

https://github.com/wazuh/wazuh/blob/3eab5298ac9b9fb6327bcd43470f88e2d68364a1/wodles/aws/aws-s3.py#L582-L587

Best regards,
Marta

**Comment by mgmacias95** [comment]
Update:

I've done a new PR with some fixes for this issue: https://github.com/wazuh/wazuh/pull/1187.

This PR completes this issue, so it's going to be closed.

Best regards,
Marta
