### ISSUE TITLE
CIS-Cat errors on Windows agent 4.3.0

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#11089]
As reported in https://github.com/wazuh/wazuh/issues/11019#issuecomment-980453570 we have found some problems inside Windows Wazuh agent logs related with Cis-Cat module.

```
wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
wazuh-modulesd:ciscat: ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'.
```
The errors were found in:
- [All-except-syscollector](https://github.com/wazuh/wazuh/issues/11046)
- [All-except-syscheck](https://github.com/wazuh/wazuh/issues/11043)
- [All-except-AR](https://github.com/wazuh/wazuh/issues/11035)
- [All-except-sca](https://github.com/wazuh/wazuh/issues/11045)
- [All-except-rootcheck](https://github.com/wazuh/wazuh/issues/11040)
- [All](https://github.com/wazuh/wazuh/issues/11039)

**Comment by alromeros** [comment]
**#11089 update:**

Hi team,

As described in https://github.com/wazuh/wazuh/issues/11019#issuecomment-981848619, this error message is also found in **4.2.5** logs.

This leads us to believe that said error should not be considered stopper for **4.3**.

Best regards.

**Comment by alromeros** [comment]
**#11089 update:**

Hi team

CIS-Cat policies are well known for their long execution periods, exceeding in many cases the defined timeout value. Considering the testing environment's specs, the presence of timeouts in such policies should not be regarded as anomalous behavior.

That is why we have decided to discard this issue as a stopper for **4.3**.

Best regards.
