### ISSUE TITLE
The start_time of linux process is calculated by the wrong way

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh#11114]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.5 | syscollector | Agent | Sources | CentOS 7.9 |

All the  `start_time`(wazuh API) of linux process are wrong.
The  `start_time` field of the `proc_t`(procps) is the time ticks passed since the system boot.
It should divide by sysconf(_SC_CLK_TCK) and add the system boot time(`/proc/stat` btime line).

**Comment by HanesSciarrone** [comment]
Hi @LubinLew 

Thank you for using Wazuh and sharing your question/advicve with Wazuh Team. I'm a developer of Team that implement and improve Syscollector. I'll talk about this with my manager, we 'll check the behavior and take the case. I will keep you informed of progress at all times. 

Best regards
Hanes

**Comment by LubinLew** [comment]
Hi @HanesSciarrone 

I write a [PR](https://github.com/wazuh/wazuh/pull/11227) for this issue, Please review it.
thanks
