### ISSUE TITLE
Logs full?

### ISSUE THREAD

**Issue by killmasta93** [wazuh/wazuh#11128]
Hi,
Currently i got an alert on my server about full disk,
I was checking and got this
My question is how does wazuh clean its logs or where would be the option to save x days of logs?
something similar to curator 

Thank you

```

root@wazuh:~#  sudo du -a  / | sort -n -r  | head -n 20
du: cannot access '/proc/1978/task/1978/fd/4': No such file or directory
du: cannot access '/proc/1978/task/1978/fdinfo/4': No such file or directory
du: cannot access '/proc/1978/fd/3': No such file or directory
du: cannot access '/proc/1978/fdinfo/3': No such file or directory
194834580	/
189652068	/var
120990104	/var/ossec
120230420	/var/ossec/logs
120227236	/var/ossec/logs/alerts
72477664	/var/ossec/logs/alerts/alerts.json
62609500	/var/log
45487764	/var/ossec/logs/alerts/alerts.log
44939876	/var/log/syslog.1
12712968	/var/log/syslog
5918100	/var/lib
5621180	/var/lib/elasticsearch
5621168	/var/lib/elasticsearch/nodes
5621164	/var/lib/elasticsearch/nodes/0
5620428	/var/lib/elasticsearch/nodes/0/indices
4104332	/var/log/journal
4104328	/var/log/journal/8e380a93b1234be2bdd548788c45b1e9
2418804	/usr
2261804	/var/ossec/logs/alerts/2021
2097156	/swapfile
```

**Comment by RamiroRD** [comment]
Hi @killmasta93!
There are some options you can use to automatically rotate some of the logs by size or time.
https://documentation.wazuh.com/current/user-manual/reference/internal-options.html?highlight=rotate
I highlighted the rotation options. Note that it does not apply to all modules, (see https://github.com/wazuh/wazuh/issues/3072).

For those without automatic log deletion, you can set up cronjobs to do the deletion for you.
For example:
```
0 0 * * mon find /var/ossec/logs/alerts/ -type f -mtime +7 -exec rm -f {} ;
0 0 * * mon find /var/ossec/logs/archives/ -type f -mtime +7 -exec rm -f {} ;
```
These cronjobs will delete files older than 7 day on each Monday on the specified directories. These two lines can be added to your crontab by running `crontab -e` as root, this will open a file editor of the crontab file. For more details see [crontab(5)](https://man7.org/linux/man-pages/man5/crontab.5.html)

Hope this helps,

Ramiro

**Comment by killmasta93** [comment]
Thank you so much for the reply,
I tried running the cron job manually 

but i get this
```

root@wazuh:~# find /var/ossec/logs/archives/ -type f -mtime +7 -exec rm -f {}
find: missing argument to `-exec'
```
i was looking at the link if i understood correctly i would go to

` nano /var/ossec/etc/local_internal_options.conf`

but not sure what config i should configure to rotate the logs?
I was looking at 
   `/var/ossec/etc/ossec.conf`

but did not see any option of log rotate or something to say keep information on wazuh for 90 days or so 


Thank you 


![image](https://user-images.githubusercontent.com/13953629/144162645-b7375162-efbc-4ce0-9376-8da1fbb273dd.png)

**Comment by RamiroRD** [comment]
Hi @killmasta93!

The reason the command is failing when you run manually is that it needs a escaped ";" at the end. If you want to test it manually, run 
```
find /var/ossec/logs/archives/ -type f -mtime +7 -exec rm -f {} \;
```
instead.

Just to make sure we are on the same page, log rotation is the process of moving (and sometimes, compressing) the log that was being written to, and then starting to write to a new empty log file. How often this happens is configurable for some of the modules (namely monitord and analysis as per the documentation I pointed out in my previous message). For example, if you wanted to rotate the logs every time the latest log is 50 MiB in size, you should add the following line to your `/var/ossec/etc/local_internal_options.conf` config file. This file is usually not present on a clean install and needs to be created.
```
monitord.size_rotate=30
```
I'm looking into exactly which modules implement log rotation and which don't and I will get back to you. In the mean time, you should be able to use cron for those that already perform log rotation.

**Comment by killmasta93** [comment]
Thank you so much, i did the following and it decreased a bit leaving space 16gigs

i was also checking these two files not sure if its normal this size?

```
root@wazuh:/var/lib/elasticsearch/nodes/0/indices# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.2G     0  7.2G   0% /dev
tmpfs           1.5G  146M  1.3G  10% /run
/dev/sda1       196G  171G   16G  92% /
tmpfs           7.2G     0  7.2G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.2G     0  7.2G   0% /sys/fs/cgroup
tmpfs           1.5G     0  1.5G   0% /run/user/0
```


```

root@wazuh:/var/lib/elasticsearch/nodes/0/indices# ls -l -h  /var/ossec/logs/alerts/2021/Nov/ossec-alerts-30.json
-rw-r----- 1 ossec ossec 96G Nov 30 23:59 /var/ossec/logs/alerts/2021/Nov/ossec-alerts-30.json
root@wazuh:/var/lib/elasticsearch/nodes/0/indices# ls -l -h  /var/ossec/logs/alerts/2021/Nov/ossec-alerts-30.log
-rw-r----- 1 ossec ossec 60G Nov 30 23:59 /var/ossec/logs/alerts/2021/Nov/ossec-alerts-30.log
```

**Comment by RamiroRD** [comment]
Glad I helped! Whether those sizes are normal or not can depend on many factors such as how many agents you have under that manager, how many rules, etc. I suggest you take a look at how many alerts you're getting and if you expect that many.

**Comment by killmasta93** [comment]
just wanted to post back i nuked my wazuh 4.1 and created another one and so far its working with 4.2

**Comment by Bec-k** [comment]
Holy cow! 90GB of events?! How much endpoints do you have?
