### ISSUE TITLE
AD events

### ISSUE THREAD

**Issue by mmbar1986** [wazuh/wazuh#11127]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Hi every body  , 

i want to send specific events from Active directory , so i added this lines on the Agent configuration : 
 
<location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 4720 and EventID != 4722 and 
      EventID != 4723 and EventID != 4724 and EventID != 4725 and EventID != 4726 and 
      EventID != 4740 and EventID != 4624 and EventID != 4625 and EventID != 4627]</query>
  </localfile>

But the events are not sent to the Wazuh , any idea please ? 

Thank you ,

**Comment by jotacarma90** [comment]
Hello @mmbar1986 

In our default Windows configuration, there is a block with those characteristics, here it is:

```
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157]</query>
  </localfile>
```

If you want to add new events, you must do it with this format. 
If you are still having problems, let's look into them for solutions.

Could you show me the agent configuration? (ossec.conf in agent side, or agent.conf in manager side, depending on your installation type and configuration).
Can you check if in the ossec.log there is any warn or error log that could be relevant? If you can, show me also the whole ossec.log file after a Wazuh reboot.
It would also be nice to have some more info about the environment, operating system, Wazuh version, type of installation, etc.

Thank you very much for using Wazuh, Regards!
