### ISSUE TITLE
Function Privsep_GetUser() use wrong macro to get the buffer length

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh#11140]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| all | shared util ? | Agent | Sources | all |

This is a trivial issue.

#### Description

Function `Privsep_GetUser` use `_SC_GETGR_R_SIZE_MAX` to get the buffer length for `getpwnam_r()`. 
It should be `_SC_GETPW_R_SIZE_MAX`.

```c
uid_t Privsep_GetUser(const char *name)
{
    long int len =  sysconf(_SC_GETGR_R_SIZE_MAX);
    ...
     result = w_getpwnam(name, &pw, buffer, len);
    ...
}

gid_t Privsep_GetGroup(const char *name)
{
    long int len = sysconf(_SC_GETGR_R_SIZE_MAX);
    ...
    result = w_getgrnam(name, &grp, buffer, len);
    ...
}
```

the macro in `sysconf()` used to get the buffer length for `getpwnam_r()` and `getgrnam_r()` are different.
| Functions | Macro|
|---|----|
| getpwnam_r() | sysconf(`_SC_GETPW_R_SIZE_MAX`) |
| getgrnam_r() | sysconf(`_SC_GETGR_R_SIZE_MAX`) |

#### PR

Please review my PR https://github.com/wazuh/wazuh/pull/7687.

**Comment by vikman90** [comment]
@LubinLew I've just commented, approved, and merged your PR. Thank you so much for raising this issue and sending us a fix.

Cheers!
