### ISSUE TITLE
Remove or replace "Skipping file with another prefix" message in AWS Custom

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#11148]
| Affected integration |
|---|
| AWS |

## Description

During the #10964 we found every integration that inherits from AWSCustom (KMS, Macie, GuardDuty and WAF) will show the `Skipping file with another prefix` message once for each file detected in the bucket but located in a subdirectory other than the one to be processed. To sum up, if we only want to process the logs from the root directory, this message will appear for each file located elsewhere. This can cause an excessive amount of messages that makes debugging difficult.

<details>
    <summary>Example</summary></summary>

    /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2018-NOV-07 -p dev -d2
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-05-06-6a311d9a-813b-4226-b78e-0854d827bcdf.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-10-56-87185795-271c-41a9-a39f-6bbe403f5f1b.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-16-22-09b86f17-056a-49f7-a45d-eb085a860e02.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-21-47-6d935587-1914-40b6-8833-e5fad306db71.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-27-10-952cba81-c2f4-43f0-892a-53653ba89211.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-32-41-d8cb5629-c605-4555-b9bd-87e4d41f14a7.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-38-05-75a77043-afe5-484b-bf4a-2b055c3610a5.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-43-34-4bff82c9-1409-45eb-9631-2af5d6bfcbef.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-48-58-a48ea8f0-a849-4490-9d55-6b3caa88a522.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-54-21-9ac4580b-e3c5-4e40-ba80-1c26ae2089b7.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/05/firehose_kms-1-2018-11-19-05-59-45-2eddc866-bf9e-418d-b5ba-11733827ef0e.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-05-16-f041433a-9e49-48c0-a888-67e3e62648e4.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-10-39-197fa59f-5840-41d5-a769-4be106d29f56.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-16-14-8689849d-c2bf-4e56-9ac1-3cf212dd54d5.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-22-06-889f1863-1a96-4ece-aae6-97ec40f07469.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-27-28-ed205cd7-a932-4aee-93af-d5a199864137.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/11/19/06/firehose_kms-1-2018-11-19-06-33-03-dab37425-dbfd-4ccc-b9ed-d970acb33d83.zip
</details>

This message should be removed or at least should only be displayed in case of debug mode 3

## Tasks
- [x] Remove the message or change its the debug level
- [x] Test in a manager

**Comment by fdalmaup** [comment]
# Manual Test

## Test details
The following tests have been done in a Wazuh Manager instance. Its version was 4.5.

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

## Custom Bucket - KMS

The following tests have been carried out over the KMS logs bucket but apply to any `AWSCustomBucket` subclass.

### Debug level 2
Run the module using the following command the using 2022-JAN-01 date as only_logs_after. 3 logs should be collected and sent to Analysisd.

Command
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2022-JAN-01 -p dev -d2
```
<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2022-JAN-01 -p dev -d2
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Found new log: 2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Found new log: 2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Found new log: 2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: +++ DB Maintenance

</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.

<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2022-JAN-01 -p dev -d2
    DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Skipping previously processed file: 2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping previously processed file: 2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping previously processed file: 2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: +++ DB Maintenance

</details>

### Debug level 3

Remove the `/var/ossec/wodles/aws/s3_cloudtrail.db` file and run the module using the following command.

Command
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2022-JAN-01 -p dev -d3
```
<details><summary>Command output</summary>

    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Found new log: 2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Reformat message
    DEBUG: {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b", "s3bucket": "wazuh-aws-wodle-kms"}, "eventVersion": "1.05", "userIdentity": {"type": "IAMUser", "principalId": "principalId", "arn": "arn:aws:iam::accountID:user/username", "accountId": "accountID", "accessKeyId": "accessKeyId", "userName": "username", "sessionContext": {"attributes": {"mfaAuthenticated": "false", "creationDate": "2018-11-07T07:53:47Z"}}, "invokedBy": "secretsmanager.amazonaws.com"}, "eventTime": "2018-11-07T17:27:01Z", "eventSource": "kms.amazonaws.com", "eventName": "GenerateDataKey", "awsRegion": "us-east-1", "sourceIPAddress": "secretsmanager.amazonaws.com", "userAgent": "secretsmanager.amazonaws.com", "requestParameters": {"keySpec": "XXXXXX", "encryptionContext": {"SecretARN": "arn:aws:secretsmanager:us-east-1:accountID:secret:XXXXXXXXX", "SecretVersionId": "XXXXXXXXXXXXXX"}, "keyId": "alias/aws/secretsmanager"}, "requestID": "requestID", "eventID": "eventID", "readOnly": true, "resources": {"ARN": "arn:aws:kms:us-east-1:accountID:key/cfc9617a-1a82-4534-86f5-19aef567a45d", "accountId": "accountID", "type": "AWS::KMS::Key"}, "eventType": "AwsApiCall", "vpcEndpointId": "vpcEndpointId", "source": "kms"}}
    DEBUG: ++ Found new log: 2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Reformat message
    DEBUG: {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b", "s3bucket": "wazuh-aws-wodle-kms"}, "eventVersion": "1.05", "userIdentity": {"type": "IAMUser", "principalId": "principalId", "arn": "arn:aws:iam::accountID:user/username", "accountId": "accountID", "accessKeyId": "accessKeyId", "userName": "username", "sessionContext": {"attributes": {"mfaAuthenticated": "false", "creationDate": "2018-11-07T07:53:47Z"}}, "invokedBy": "secretsmanager.amazonaws.com"}, "eventTime": "2018-11-07T17:27:01Z", "eventSource": "kms.amazonaws.com", "eventName": "GenerateDataKey", "awsRegion": "us-east-1", "sourceIPAddress": "secretsmanager.amazonaws.com", "userAgent": "secretsmanager.amazonaws.com", "requestParameters": {"keySpec": "XXXXXX", "encryptionContext": {"SecretARN": "arn:aws:secretsmanager:us-east-1:accountID:secret:XXXXXXXXX", "SecretVersionId": "XXXXXXXXXXXXXX"}, "keyId": "alias/aws/secretsmanager"}, "requestID": "requestID", "eventID": "eventID", "readOnly": true, "resources": {"ARN": "arn:aws:kms:us-east-1:accountID:key/cfc9617a-1a82-4534-86f5-19aef567a45d", "accountId": "accountID", "type": "AWS::KMS::Key"}, "eventType": "AwsApiCall", "vpcEndpointId": "vpcEndpointId", "source": "kms"}}
    DEBUG: ++ Found new log: 2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Reformat message
    DEBUG: {"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b", "s3bucket": "wazuh-aws-wodle-kms"}, "eventVersion": "1.05", "userIdentity": {"type": "IAMUser", "principalId": "principalId", "arn": "arn:aws:iam::accountID:user/username", "accountId": "accountID", "accessKeyId": "accessKeyId", "userName": "username", "sessionContext": {"attributes": {"mfaAuthenticated": "false", "creationDate": "2018-11-07T07:53:47Z"}}, "invokedBy": "secretsmanager.amazonaws.com"}, "eventTime": "2018-11-07T17:27:01Z", "eventSource": "kms.amazonaws.com", "eventName": "GenerateDataKey", "awsRegion": "us-east-1", "sourceIPAddress": "secretsmanager.amazonaws.com", "userAgent": "secretsmanager.amazonaws.com", "requestParameters": {"keySpec": "XXXXXX", "encryptionContext": {"SecretARN": "arn:aws:secretsmanager:us-east-1:accountID:secret:XXXXXXXXX", "SecretVersionId": "XXXXXXXXXXXXXX"}, "keyId": "alias/aws/secretsmanager"}, "requestID": "requestID", "eventID": "eventID", "readOnly": true, "resources": {"ARN": "arn:aws:kms:us-east-1:accountID:key/cfc9617a-1a82-4534-86f5-19aef567a45d", "accountId": "accountID", "type": "AWS::KMS::Key"}, "eventType": "AwsApiCall", "vpcEndpointId": "vpcEndpointId", "source": "kms"}}
    DEBUG: ++ Skipping file with another prefix: kms/2018/11/07/17/firehose_kms-1-2018-11-07-17-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping file with another prefix: kms_compress_encrypted/2018/11/12/08/firehose_kms-1-2018-11-12-08-16-58-975f1ad7-14e4-41ce-a805-3310fdf07f61.zip
    ...
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-09-26-b7d50739-5b81-44a5-9a1a-aca2ff8ade40.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-14-57-a65fd90f-66f7-4ded-8ad2-28caa7e17ef4.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-20-22-fdc84279-3a2b-4d2f-aee2-6adf295b076c.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-25-53-d2b1a5b4-8456-474e-a434-972f34ec4e9c.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-31-03-6722571b-2cc6-4d86-8bef-7ba4937f5231.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-36-06-c9ded56a-daee-42fb-a45e-63bee4330927.zip
    DEBUG: +++ DB Maintenance
    

</details>

Keep the database file and run the same command again to ensure no duplicate logs are processed. Use the same `only_logs_after` parameter.


<details><summary>Command output</summary>

    /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-kms -t custom -s 2022-JAN-01 -p dev -d3
    DEBUG: +++ Debug mode on - Level: 3
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Skipping previously processed file: 2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping previously processed file: 2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping previously processed file: 2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping file with another prefix: kms/2018/11/07/17/firehose_kms-1-2018-11-07-17-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Skipping file with another prefix: kms_compress_encrypted/2018/11/12/08/firehose_kms-1-2018-11-12-08-16-58-975f1ad7-14e4-41ce-a805-3310fdf07f61.zip
    DEBUG: ++ Skipping file with another prefix: kms_compress_encrypted/2018/11/12/08/firehose_kms-1-2018-11-12-08-22-53-164142bf-2a5b-421a-b9f2-9b3f28e414ed.zip
    DEBUG: ++ Skipping file with another prefix: kms_compress_encrypted/2018/11/12/08/firehose_kms-1-2018-11-12-08-28-26-519d543d-9ae8-4576-b84b-f9e06fd6946a.zip
    DEBUG: ++ Skipping file with another prefix: kms_compress_encrypted/2018/11/12/08/firehose_kms-1-2018-11-12-08-33-49-8a5efcc0-c8f5-46ed-b918-b33cca5d6efe.zip
    ...
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-14-57-a65fd90f-66f7-4ded-8ad2-28caa7e17ef4.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-20-22-fdc84279-3a2b-4d2f-aee2-6adf295b076c.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-25-53-d2b1a5b4-8456-474e-a434-972f34ec4e9c.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-31-03-6722571b-2cc6-4d86-8bef-7ba4937f5231.zip
    DEBUG: ++ Skipping file with another prefix: test_prefix/kms_compress_encrypted/2018/12/03/14/firehose_kms-1-2018-12-03-14-36-06-c9ded56a-daee-42fb-a45e-63bee4330927.zip
    DEBUG: +++ DB Maintenance

</details>


## Server Access

### Debug level 2

### Debug level 3

**Comment by fdalmaup** [comment]
# Test setting `ossec.conf`

Run the module adding the following configuration to the `ossec.conf` file

<details><summary>Configuration</summary>
    
    <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="custom">
      <name>wazuh-aws-wodle-kms</name>
      <aws_profile>dev</aws_profile>
      <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="server_access">
      <name>wazuh-aws-wodle-access</name>
      <aws_profile>dev</aws_profile>
      <only_logs_after>2021-NOV-12</only_logs_after>
    </bucket>
  </wodle>

</details>

<details><summary>ossec.log</summary>

    2022/09/26 16:49:12 wazuh-modulesd:aws-s3[10224] wm_aws.c:59 at wm_aws_main(): INFO: Module AWS started
    2022/09/26 16:49:12 wazuh-modulesd:aws-s3[10224] wm_aws.c:81 at wm_aws_main(): INFO: Starting fetching of logs.
    2022/09/26 16:49:12 wazuh-modulesd:aws-s3[10224] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-kms, Type: custom, Profile: dev)
    2022/09/26 16:49:12 wazuh-modulesd:aws-s3[10224] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/09/26 16:49:12 wazuh-modulesd:aws-s3[10224] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-kms --aws_profile dev --only_logs_after 2022-JAN-01 --type custom --debug 2
    2022/09/26 16:49:20 wazuh-modulesd:aws-s3[10224] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    2022/09/26 16:49:20 wazuh-modulesd:aws-s3[10224] wm_aws.c:133 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-access, Type: server_access, Profile: dev)
    2022/09/26 16:49:20 wazuh-modulesd:aws-s3[10224] wm_aws.c:328 at wm_aws_run_s3(): DEBUG: Create argument list
    2022/09/26 16:49:20 wazuh-modulesd:aws-s3[10224] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-access --aws_profile dev --only_logs_after 2021-NOV-12 --type server_access --debug 2
    2022/09/26 16:49:23 wazuh-modulesd:aws-s3[10224] wm_aws.c:483 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    2022/09/26 16:49:24 wazuh-modulesd:aws-s3[10224] wm_aws.c:173 at wm_aws_main(): INFO: Fetching logs finished.
    2022/09/26 16:49:24 wazuh-modulesd:aws-s3[10224] wm_aws.c:77 at wm_aws_main(): DEBUG: Sleeping until: 2022/09/26 16:59:12

</details>


## Conclusions

The module is working as expected. The events are being sent to AnalysisD and no `Skipping file with another prefix...` message was present neither in `archives` nor `ossec.log`.
