### ISSUE TITLE
A lot of false positives

### ISSUE THREAD

**Issue by Sharjeel914** [wazuh/wazuh#11155]
Hi there,

I am using the latest version of Wazuh in Linux and my agent has been installed in Windows Server 2016. **It is showing me a lot of vulnerabilities but actually, none of them exist (upon my research).** My server is updated and it does not have any pending updates. It is showing **"X patch is not installed"** but when I search for that specific patch on Windows Catalog, it doesn't show me anything. 

In some cases, I found out that my server has those missing patches installed but with a different KB number. Please check the attachments. 

![7](https://user-images.githubusercontent.com/95383264/144315089-1e48b7c1-f3d3-436b-bd3c-bc202e2bf438.PNG)

![1(2)](https://user-images.githubusercontent.com/95383264/144315386-174860b2-fe4d-4f25-8dc8-3617d8d0394b.png)

![2](https://user-images.githubusercontent.com/95383264/144315270-219ecde5-f9b8-47f1-9a47-97cf2b4d131d.PNG)

![3(2)](https://user-images.githubusercontent.com/95383264/144315287-62ba7538-efd9-4d1c-88fc-60f02185791f.png)

Please help me out with this.

Kind regards,
Sharjeel

**Update:
I am getting the following error: 2021/12/01 15:11:43 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.**

**Comment by pereyra-m** [comment]
Hi @Sharjeel914 !

Thank you very much for the details provided. 
Can you tell us the Wazuh version of the agent?

The MSU feed provided by Wazuh should contain the information related to cumulative updates. It allows to discard these kind of false positives. Could you please upload your manager's `ossec.conf` file? So we can be sure the vulnerability detector module is configured correctly.

Also, as you are seeing error messages in your logs, can you share the full `ossec.log` file? Maybe, the manager is unable to download the databases to a connectivity issue or it's failing to insert the downloaded data.

Finally, to reproduce this error, we'd need the agent's information exactly as it is saved in the manager. These are the queries required to run in the manager, considering the agent's ID is 001:

- ` sqlite3 queue/db/global.db ".mode csv" "select * from agent where id = 1"`
- `sqlite3 queue/db/001.db ".mode csv" "select * from sys_osinfo"`
- `sqlite3 queue/db/001.db ".mode csv" "select * from sys_hotfixes"`

Regards.

**Comment by Sharjeel914** [comment]
Hello,

Thank you for your comment!
My agent version is 4.2.5

Attached are the required files and the output of those queries

https://filebin.net/7xnx9e9i0y5dm9m0

![1](https://user-images.githubusercontent.com/95383264/144361287-0e284890-9dba-4fba-bd66-ec668ca8c11f.PNG)

Looking forward to your reply.
Thank you!

Kind regards,
Sharjeel

**Comment by Sharjeel914** [comment]
Hi @pereyra-m !

Thank you for looking into this. I have followed your steps and here is the ossec.log (https://pastebin.com/CWGndLm1).
I still have the same number of vulnerabilities. 

Looking forward to your further help.

Kind regards,
Sharjeel

**Comment by pereyra-m** [comment]
Hello @Sharjeel914 !

Thank you for the tests performed and logs provided. Now, we don't see any error in the log. Vulnerability detector seems to be scanning the agent correctly.

You say you still have the same number of vulnerabilities, but how are you visualizing them? According to the screenshots you've provided, if we use a vulnerabilities alerts filter within a certain time range we may find CVEs that are no longer valid and have been discarded in newer scans. Please, use the **Inventory** tab instead, it shows the current vulnerabilities state of the agent.

On the other hand, I was able to confirm that the MSU feed contains the cumulative patches information related to the KB you've shared, so it shouldn't generate false positives.
If the **Inventory** tab shows these vulnerabilities as valid, please run a new scan with the full debug mode enabled:

- Configure temporarily (only for this test) the `<ignore_time>` tag to **1m**. This way, we'll force a full vulnerability scan when the manager restarts
- Add `wazuh_modules.debug=2` to `/var/ossec/etc/local_internal_options.conf` (only for this test)
- Restart the Wazuh manager (for example, `systemctl restart wazuh-manager`)

Then, upload the full log so we can check every step in the detection process for this agent.
Regards.

**Comment by Sharjeel914** [comment]
Hello @pereyra-m !

Thank you for getting back to me. If I set the time range to 1, I am not seeing any vulnerabilities but if I set it to let's say 16 days, I do see all of them again (I installed Wazuh roughly 16 days ago). Why is it like this? 

The inventory tab is not showing any vulnerabilities.

Also, does Wazuh report any third-party application vulnerabilities like adobe, java, etc.? I do not see any in the Wazuh UI but I do have some (reported by a vulnerability detector). 

Looking forward to your reply.

King regards,
Sharjeel

**Comment by pereyra-m** [comment]
Hi @Sharjeel914  !

It's solved then, let me explain to you how vulnerability detector works. You can see more details in the [documentation](https://documentation.wazuh.com/4.2/user-manual/capabilities/vulnerability-detection/how-it-works.html).

Every time a scan ends, all the vulnerable packages found will be reported with an alert. If the package wasn't fixed by the next scan, it will be alerted again. The user can configure [ignore_time](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/vuln-detector.html?highlight=ignore_time#ignore-time) to avoid these repeated alerts for a while, but they will be alerted again when this time expires.

Now, it isn't easy to determine the current vulnerabilities of the agent only with the alerts, that's why you have the inventory tab: all the valid vulnerabilities will be stored there until they get fixed (by an update for example). If the CVE is not listed there, then it is no longer valid.

It happens that two weeks ago, an error in the DB caused these false positives. But now that they were eliminated, you only can see them if you look for old alerts.

Finally, about your last question, Wazuh scans all installed packages to find vulnerabilities. But sometimes the reported name is different from the one used in the feeds. That's why you can check the [CPE helper](https://documentation.wazuh.com/4.2/user-manual/capabilities/vulnerability-detection/cpe-helper.html#cpe-helper) to confirm the software is properly detected and add new entries if you need to.

Regards.

**Comment by Sharjeel914** [comment]
Hello again @pereyra-m !

Thank you so much for helping me to solve the issue! I really appreciate your help!

Could you please elaborate more on the installed packages' vulnerabilities? I had an older version of Adobe Flash Player with a lot of vulnerabilities detected by a vulnerability detector but Wazuh didn't report anything. Where and how can I see installed packages vulnerabilities? 

My end goal is to use Wazuh for vulnerability detection and respond to me via e-mail in case of a breach. Is it possible to set that up? If so, please advise me how.

I am really looking forward to your reply and once again I thank you for all the explanations and for solving the issue!

Kind regards,
Sharjeel

**Comment by pereyra-m** [comment]
Hi again @Sharjeel914 ! 

Glad to help, thanks to you for using Wazuh and posting all your questions.

All the vulnerabilities found will be in the **Vulnerabilities** section, regardless they are from Windows or not. Here you can see an example

![win_example](https://user-images.githubusercontent.com/65046601/145587480-5f750ec2-ebb6-492b-8ee3-0a53742ef5e8.png)

All the elements in the inventory have an alert associated, here I have selected one. The vulnerabilities detected always are reported

![alert_example](https://user-images.githubusercontent.com/65046601/145589885-dea0d721-4fd4-433b-b3a4-9ce310feba13.png)

The case of the CPE helper I mentioned is needed only when vulnerability detector is unable to find any vulnerabilities of that software and a name translation is required.

Finally, you can [Configuring email alerts](https://documentation.wazuh.com/4.2/user-manual/manager/manual-email-report/index.html#configuring-email-alerts) for the vulnerability detector events, but we should open another issue about it to keep every thread organized.

Regards.

**Comment by Sharjeel914** [comment]
Hello @pereyra-m 

Thank you again for helping me out with everything! You may close this thread now.

Kind regards,
Sharjeel

**Comment by pereyra-m** [comment]
Thanks to you for using Wazuh!

Contact us again any time you need.
Regards.
