### ISSUE TITLE
IPv6 support for cluster

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#11170]
|Wazuh Version| Component|
|:--:|:--:|
|4.4.0|Cluster|

## Description

As part of #4243 development, new integration and system tests are being created in https://github.com/wazuh/wazuh-qa/issues/2224.  It is necessary to research if the cluster will support IPv6 to consider the development of new tests for these use cases.

**Comment by davidjiglesias** [comment]
The cluster will not support ipv6 for now
