### ISSUE TITLE
Dynamic fields not working as expected on CDB list

### ISSUE THREAD

**Issue by WallaceCS** [wazuh/wazuh#11176]
|Wazuh version| Component | Action type |
|---| --- | --- |
|4.1.5 | Rules/Decoders | Error/Improve |

## Description

Hello team,  
         I am using Syscollector information to trigger alerts.  When using dynamic fields on a rule with CDB list, the rule doesn't match because the event doesn't load the dynamic fields correctly. 

Attempt 1: 

```
<rule id="100058" level="15">   
  <if_sid>221</if_sid>     
  <decoded_as>syscollector</decoded_as>     
  <field name="netinfo.iface.name">wlp3s0</field>      
  <description>eth0 interface enabled. IP: $(netinfo.iface.ipv4.address)</description>      
</rule>
```

Rule hit, alert log: 

  ```
Rule: 100058 (level 15) -> 'eth0 interface enabled. IP: ["192.168.5.103"]'    
{"type":"network","ID":2129198711,"timestamp":"2021/12/03 15:12:38","iface": {"name":"wlp3s0","type":"ethernet","state":"up","MAC":"0c:96:e6:18:12:79","tx_packets":2797051,"rx_packets":4806531,"tx_bytes":865586878,"rx_bytes":2714770704,"tx_errors":0,"rx_errors":0,"tx_dropped":0,"rx_dropped":0,"MTU":1500,"IPv4":{"address":["192.168.5.103"],"netmask":["255.255.255.0"],"broadcast":["192.168.5.255"],"metric":600,"gateway":"192.168.5.1","DHCP":"enabled"},"IPv6":{"address":["fe80::90a1:ed0c:8d9a:e519"],"netmask":["ffff:ffff:ffff:ffff::"],"DHCP":"enabled"}}}
type: network
netinfo.iface.name: wlp3s0  
``` 

Attempt 2:    

```
<rule id="100059" level="15">
  <if_sid>221</if_sid>
  <decoded_as>syscollector</decoded_as>
  <list field="netinfo.iface.name"  lookup="match_key">etc/list/illegal_connections</list>
  <description>CDB: eth0 interface enabled. IP: $(netinfo.iface.ipv4.address)</description>
</rule>
```

   The CDB list etc/list/illegal_connections  contains the following line: 
`wlp3s0:illegal`

This rule 100059  doesn't seem to be working. 
I referred to the previous issue [#2049](https://github.com/wazuh/wazuh/issues/2049)  and [#201](https://github.com/wazuh/wazuh/issues/201) .

**Comment by JcabreraC** [comment]
Hello WallaceCS,

Currently, the CDBlist is working properly. Remember to add this one to the configuration.

To do this, edit the `/var/ossec/etc/ossec.conf` file and add your CDBlist in the `ruleset` configuration block using the `list` label:
```
<ruleset>
    <!-- Default ruleset -->
    ...
    <!-- User-defined ruleset -->
    ...
    <list>YOUR_CDBLIST_PATH</list>
    ...
   
  </ruleset>
```

With this change, your log will generate the alert.

Regards.

**Comment by WallaceCS** [comment]
> Hello WallaceCS,
> 
> Currently, the CDBlist is working properly. Remember to add this one to the configuration.
> 
> To do this, edit the `/var/ossec/etc/ossec.conf` file and add your CDBlist in the `ruleset` configuration block using the `list` label:
> 
> ```
> <ruleset>
>     
>     ...
>     
>     ...
>     <list>YOUR_CDBLIST_PATH</list>
>     ...
>    
>   </ruleset>
> ```
> 
> With this change, your log will generate the alert.
> 
> Regards.

Thank you for your reply.
You are right. I wrote the wrong path of my CDBlist in the rule. I didn't notice it for a long time, but it's true.
I will close this disgraceful issue immediately.
