### ISSUE TITLE
Modify remoted statistic information to provide bucketized information

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#11187]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | remoted | Manager | Packages/Sources | Any OS |

Hello,

remoted and analysisd statistics information work in different ways. While analysisd shows bucketized information (for instance, the events processed), remoted shows a global count since the binary was executed.

This doesn't provide information about a specific time range as it can't help to create historic information about these metrics.

We should modify the behavior to adopt analysisd behavior.

Regards,

Javier.

**Comment by TomasTurina** [comment]
Solved in https://github.com/wazuh/wazuh/issues/13099
