### ISSUE TITLE
API/Framework doesn't find sqlite library

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#1119]
Hi,

The library _/var/ossec/framework/lib/libsqlite3.so.0_ is no longer installed since v3.5.0. That breaks the API.

**Comment by BraulioV** [comment]
Hi team,

I just added this commit https://github.com/wazuh/wazuh-packages/commit/da9af754e90bd0d5ec00d299549f7de272d5178d to add the SQLite library in the RPM packages.

I'm closing this issue.

Regards,
Braulio.
