### ISSUE TITLE
oscap wodle: tailoring files

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh#112]
openscap supports tailoring files, which can be used to change the behaviour of SCAP content, e.g. the default ssg-* rules. (un-selecting rules, etc)

https://static.open-scap.org/openscap-1.0/oscap_user_manual.html#_how_to_tailor_source_data_stream

perhaps, add the path as attribute to the <content> tag?
https://github.com/wazuh/wazuh/blob/4f0529ddde3a01b90dbe09d83a755bc86099a412/etc/templates/config/debian/8/wodle-openscap.template#L7

**Comment by vikman90** [comment]
Hi @hex2a,

that is a great suggestion, we may add a tag like `<tailor>` to the OpenSCAP content item:

```
<content type="xccdf" path="ssg-rhel6-ds.xml">
  <profile>xccdf_org.ssgproject.content_profile_C2S_customized</profile>
  <tailor>ssg-rhel6-ds-tailoring.xml</tailor>
</content>
```

We will add it to the roadmap. Thank you for your feedback.

Best regards.

**Comment by kaneda-fr** [comment]
Any plan or timeline to implement this feature ?

**Comment by 32bitbradley** [comment]
Any updates to the time scale for this feature @vikman90 ? I think it would be really useful! :)

**Comment by Zenidd** [comment]
Hello @kaneda-fr, @32bitbradley and @hex2a,

sorry for the late response.

We are going to assign this issue to a project and we and start working on it as soon as possible. We will update this thread with more information.
<br></br>
Kind regards,

Juan Pablo Sáez

**Comment by hambuergaer** [comment]
Hey, I would be very happy to see this feature in Wazuh to be able to use own custom Scap tailoring files. Is there any rough estimation when this feature will be available? Or can I somehow support?

**Comment by vikman90** [comment]
@hambuergaer The OpenSCAP module was deprecated in 4.0.0, and it was disabled as of 4.3.0:

- https://github.com/wazuh/wazuh/pull/10900

We have no plans to continue developing the OpenSCAp integration. Let me close this issue.
