### ISSUE TITLE
How could we monitored the mysql query ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#1120]
I am just wondering... is it possible ?

**Comment by Cerv1** [comment]
Hello @gagantous,

As said in #1122, this is a bug and we're working to solve it as soon as possible.

Thanks a lot for reporting this issue!

Best regards,
Cerv1

**Comment by Zenidd** [comment]
Hello @gagantous,

I'm closing this issue as we will use the https://github.com/wazuh/wazuh/issues/1122 to document the fixing process. 

Do not hesitate to open a new issue if you find a bug and you can also contact us through [our mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh) and our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) if you need some guidance.

Greetings, JP Sáez
