### ISSUE TITLE
empty panels since last update

### ISSUE THREAD

**Issue by eglyn** [wazuh/wazuh#11215]
Hi all, 

Since the last update to 4.2.5, a lot of panel is empty, and first one the "Evolution" panel, on agent main window: 
![image](https://user-images.githubusercontent.com/24936778/144855378-4531b5e4-a9d6-4e45-bb0c-59a2c2cacdf7.png)

I see agents online, but when I go into an agent, most of panel are empty: 

![image](https://user-images.githubusercontent.com/24936778/144855449-23113235-26b4-456b-a1f4-ec2bdd1ea5fe.png)

And vulnerability too, before update I had some vulnerabilities, and now that: 

![image](https://user-images.githubusercontent.com/24936778/144855582-234c7d68-4fe4-423e-a239-943cf7954264.png)

We see here if I look on last 90 days the "cut" when I did the update: 

![image](https://user-images.githubusercontent.com/24936778/144866261-33e647f2-956a-41cb-8096-5d641dc95ffb.png)

I don't see anything special in logs only this: 

`Dec 6, 2021 @ 15:18:47  ERROR  Could not check if the index .wazuh exists due to no permissions for create, delete or check`

Any idea ?

**Comment by D1eguitoC9stra** [comment]
How did you fix this problem?
