### ISSUE TITLE
Rework issue #8493 - Detect 4.A - Local and Domain Discovery

### ISSUE THREAD

**Issue by xrisbarney** [wazuh/wazuh#11218]
|Wazuh version|Component|Install type|Install method|Platform|Action type|
|---|---|---|---|---|---|
| 4.3.0 | Rules and Decoders | Manager | Packages | Any | Rework|

|Related issues|Related PR|
|---|---|
| #8493 | #8591  |

|Related PR|
|---|
| -  |

## Description
This issue is has been created as a rework of the rules and decoders added in PR #8591 to close issue #8493. #8591 created WMI discovery rules. 
The aim of this issue is:
- To add a blank line at the EOF.
- To ensure the rules and decoders from the issue work correctly.
- To fix issues regarding indentation, syntax, rule granularity, spellings and ensure the ruleset quality is standard.

## Original Issue
Type: Feed threat emulation.

### Request from #8493

Generate detection rule using the Carbanak [step 4.A](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/carbanak/Emulation_Plan/Scenario_1#step-4---domain-discovery-and-credential-dumping)

- Test environment setup
- Collect relevant logs
- Write appropiate decoders and rules

This step requires full set up of DC managed endpoints

**Comment by xrisbarney** [comment]
All the files in the original PR have been moved/changed. Nothing to rework or revert

**Comment by 72nomada** [comment]
Closing it, it is not needed.
