### ISSUE TITLE
Implement the new database columns in the agent table of global.db to save information related to the groups synchronization status

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#11220]
### Description

As part of the epic #10771, we have the main goal of migrating the agent-group files to wazuh-db. Having said that, a completely new synchronization mechanism for the agents' group information had to be designed. Because of this, we need to add some extra columns to the `global.db` database that will allow us to reflect the information required by the new synchronization logic.

### Requirements

- [X] Two new columns with the names `group_sync_status` and `group_writter` should be added to the `agent` table.
- [X] Both columns shouldn't take null values.
- [X] `group_sync_status` will take `synced` or `unsynced` as possible values.
- [X] `group_sync_status` will take `synced` as the default value.
- [X] `group_writter` will take `YAML` or `manual` as possible values.
- [X] `group_writter` will take `manual` as the default value.
- [X] A new column with the name `priority` should be added to the `belongs` table.
- [X] `priority` will take positive integers as possible values.
- [X] `priority` will take `0` as a default value.
- [X] The new primary key of the `belongs` table will be `id_agent` + `priority`.
- [X] An index of `id_agent` + `groups` should be created.
- [X] All the wazuh-db queries should be updated to return the groups ordered by priority.

### Risks

We should make sure that this change will not impact the priority order of the groups.

### Testing required

- [X] Clean installation and verification that the new database columns exist.
- [X] Upgrade and verification that the new columns are added to the database and properly completed.
- [X] Manual testing of the modified wazuh-db commands (if any).

### DoD

- [X] All the requirements should be implemented.
- [X] All the suggested tests among others should pass successfully.
- [X] The code review should be approved.
- [X] Scan-build execution without errors (if some `C` code is modified).
- [X] Jenkins tests in green (except the UTs that will be implemented altogether at the end).

**Comment by MiguelazoDS** [comment]
## Description
The behavior we expected with this implementation in the `belongs` table, now with a new column, is the following:
- `id_agent` and `id_group` should be unique as these two columns are the PK.
- It is possible to have duplicate tuples (id_group, group_priority) as they may refer to different agents. If the agents were registered with the same groups in the same order the priority should be the same.
- It is NOT possible to have duplicate tuples (id_agent, group_priority) since an agent shouldn't have different groups with the same priority.
