### ISSUE TITLE
Fix docstring format from API and Framework modules

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11222]
We should review our framework and API modules to verify their docstring format.

As we know, we're using [Numpy format](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard) at `wazuh/wazuh` but there are several methods that still have the old docstring format.

For instance:
https://github.com/wazuh/wazuh/blob/15bb33d03a4612ee084f7fdcbe096f8513c21882/framework/wazuh/ciscat.py#L14-L29

---
**WORKING_BRANCH**: `dev-api-framework-docstrings`
**TARGET_WAZUH_BRANCH**: `master`

Latest rebase of `dev-api-framework-docstrings` (working) with `master`: September 09, 2022 - 07:00 UTC

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
Both pull requests https://github.com/wazuh/wazuh/pull/14834 and https://github.com/wazuh/wazuh/pull/14835 are part of the development related to this issue.

The PR closing the issue will be the one merging the development branch (`dev-api-framework-docstrings`) into the target one (`master`).
