### ISSUE TITLE
Migrate agent-group files to wazuh-db - QA plan and execution 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#11240]
## Description

This is a tracking purposes issue to reflect all the work done on QA for the epic https://github.com/wazuh/wazuh/issues/10771. In this issue, we will expose the overall QA plan and the results of all the testing performed as well.

In the next sections, we add details and explain the criteria of all the QA instances.

## Code reviews

For each PR created as part of this epic, the reviewer should take into account the next items.

- **Functional revision**: Make sure that the changes satisfy all the requirements of the issue.
- **Performance**: If the implementation performs a task with some complexity level, evaluate the performance of the implemented algorithm.
- **Memory**: Evaluate the right usage of the memory in the heap and the stack as well.
- **Unit testability**: Evaluate if the implementation will allow the development of unit test cases in an easy and effective way.
- **Mantenibilidad**: Evaluate whether the code will be easy to be modified or extended in the future.
- **Spelling and language**: Evaluate the spelling and gram in the comments.
- **Security**: Evaluate whether the code is secure.
- **Interoperability**: Evaluate whether the change should be coordinated and communicated to other teams.

Each reviewer will leave a comment in the review enumerating the criteria taken into account.

## Static analysis of code

- Each pull request should include the results of the `scan-build` execution.
- After having the epic implemented, a `Coverity` analysis will be executed.

For details, check the issue https://github.com/wazuh/wazuh/issues/11755.

## Unit testing

As part of this epic, the implementation should have 100% of coverage for all the new functions included in the code, as well as the modified functions that already had 100% of coverage

For details, check the issue https://github.com/wazuh/wazuh/issues/11754.

## Exploratory testing

After having the epic implemented, all the team will perform exploratory testing over the implementation. 
Here we have a list of relevant tests collected during the development:

### `global.db` upgrade

|Test ID|Tittle|Validations|Reference link|
|-|-|-|-|
|gdbup1|Upgrade from a legacy `global.db` (lower than 3.10)|A `pre_upgrade` backup should be generated. If the backup is created successfully, a new `global.db` file should be generated. If the backup creation fails, an error log should be logged and the `global.db` should be disabled.|https://github.com/wazuh/wazuh/issues/11240#issuecomment-1030182853|
|gdbup2|Upgrade from a `global.db` of version greater or equal than 3.10|A `pre_upgrade` backup should be generated. If the backup is created successfully, all the schema upgrades should be applied up to version 4. If the backup creation fails, an error log should be logged and the `global.db` should be disabled. On the other hand, if any of the upgrades up to version 4 fails, an error log should be logged and the database should be restored to the original state. If the restoration to the original state doesn't work, the database should be disabled.|https://github.com/wazuh/wazuh/issues/11240#issuecomment-1029256768|
|gdbup3|Error looking for `metadata` table verification|During the upgrade, we handle the case in which `sqlite` fails checking if the `metadata` table exists in the database. This is essentially a `sqlite` error so, we should evaluate whether is possible to force this scenario. If this is possible, an error log should be logged and the `global.db` should be disabled.| https://github.com/wazuh/wazuh/issues/11240#issuecomment-1031416871  |
|gdbup4|Error reading the database version|We handle the case in which fails to read the database version from a no-legacy database, with a `metadata` table and the `version` written in that table. We should evaluate whether is possible to force this scenario. If this is possible, a warning log should be logged and the `global.db` should be disabled.|https://github.com/wazuh/wazuh/issues/11240#issuecomment-1033022103|

### `global.db` backups

|Test ID|Tittle|Validations|Reference link|
|-|-|-|-|
|gdbbak1|Database backup settings|We should verify that having the database backup settings written or not having them written in the configuration file, they takes the correct value. The default values are specified in [the implementation issue](https://github.com/wazuh/wazuh/issues/11389). This should be validated by using the interface implemented as part of the [issue 11732](https://github.com/wazuh/wazuh/issues/11732) in order to also validate that this interface works as expected.|https://github.com/wazuh/wazuh/issues/11240#issuecomment-1029288241|
|gdbbak2|Database backups periodical creation|We should validate that the `global.db` backups are created in the period specified in the settings. In addition, we should verify that the backup creation is informed in the log files.| https://github.com/wazuh/wazuh/issues/11240#issuecomment-1031625397 |
|gdbbak3|Database backups max files|We should verify that when the `global.db` backups are enabled, we only keep the number of backups specified in the `<max_files>` setting. In addition, we should verify that the oldest backup is removed when we create the backup `max_files+1`.| https://github.com/wazuh/wazuh/issues/11240#issuecomment-1031900292 |

### Single manager agent groups management

|Test ID|Tittle|Validations|Reference link|
|-|-|-|-|
|smagm1|Agent group assignment and unassignment|We should verify that having a group created in the manager, we can assign and unassign an agent to this group during the agent registration, using the `agent_groups` tool, and using the Wazuh API. We should also verify that we can't assign an agent to a group that doesn't exist. Even when we specify a single group, or when we specify a list of groups and one of them doesn't exist. Finally, when we unassign agents from groups, we should verify that the agents always belong to a group. For all the cases we should verify the `groups_hash` column.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm2|Agent group assignment limit and name limit|We should verify that during the agent registration, using the `agent_groups` tool, and using the Wazuh API, we can't assign an agent to more than 128 groups. In addition, we should verify that we can't create groups with an invalid name because of the size.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm3|Per-agent groups query|We should verify that using the `agent_groups` tool and the Wazuh API as well, we can query the groups to which an agent is assigned.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm4|Groups priorities|We should verify when an agent is added to more than one group, the last assignment is the one with the higher priority. In addition, we should verify that when having multiple groups to which an agent is assigned, if we unassign the agent from a group with middle-level priority, the remaining groups keep the same priority order.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm5|Groups guessing|We should verify that when an agent registered in the manager and assigned to a group is removed, when it negotiates a new ID and key, in the first communication with the manager, this performs a guessing operation and determines the groups to which the agent was assigned. With **guess_agent_group** disabled (default) the agent will be set to default when connects, with **guess_agent_group** enabled, the last assigned group must be restored.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm6|Repeated group names|We should verify that we cant create groups with the same name. The `group` table should not allow repeated rows.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|smagm7|Multiple agent group creation and assignment with script calling agent-groups|We should verify that performing the task won't corrupt the belongs table.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|

### Cluster agent groups management

|Test ID|Tittle|Validations|Reference link|
|-|-|-|-|
|cagm1|Agent group assignment and unassignment|We should verify that having a group created in the `master`, we can assign and unassign an agent to this group during the agent registration, using the `agent_groups` tool, and using the Wazuh API. This should work even if the agent is in communication with the master and with the workers as well.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|cagm2|Groups priorities in agent communicated with the worker|We should verify when an agent in communication with a worker node is added to more than one group, the last assignment is the one with the higher priority. In addition, we should verify that when having multiple groups to which this agent is assigned, if we unassign the agent from a group with middle-level priority, the remaining groups keep the same priority order.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|cagm3|Groups guessing|We should verify that when an agent registered in the `master` and assigned to a group is removed, when it negotiates a new ID and key, in the first communication with the `worker`, this performs a guessing operation and determines the groups to which the agent was assigned. With **guess_agent_group** disabled (default) the agent will be set to default when connects, with **guess_agent_group** enabled, the last assigned group must be restored. This information should be propagated to the `master` node.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|cagm4|Groups integrity|We should verify that when having groups created in a cluster, and agents in communication with the `master` and others with the `workers` that are assigned to different groups, if we manually modify the agent groups information in the workers, this causes an integrity check failure and triggers an agent groups data synchronization.|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|
|cagm5|Agents recently registered with groups|We should verify that when registering a new agent with groups, the agent information is propagated to the worker before the group's information, allowing the worker to insert successfully the group information and being available when the agent connects with the worker manager|https://github.com/wazuh/wazuh-qa/issues/2504 and https://github.com/wazuh/wazuh/issues/11781|

### Installation and upgrade

|Test ID|Tittle|Validations|Reference link|
|-|-|-|-|
|iu1|Creation of `backup/db` folder and Removal of `backup/groups` folder|During the installation, a new `backup/db` folder should be created to be used by the periodical `global.db` backup creation. We should verify that during clean installations the `backup/groups` folder is no longer created. In addition, during an upgrade, this folder should be removed. |https://github.com/wazuh/wazuh/issues/11240#issuecomment-1032581757|
|iu2|Removal of files in `agent-group` folder|We should verify that during an upgrade, when the manager starts, it properly adds the information in the `agent-group` files to the `global.db`. After this, the `agent-group` folder and its content shouldn't exist.|https://github.com/wazuh/wazuh/issues/11240#issuecomment-1032852137|

**Comment by MiguelazoDS** [comment]
# Issues found

- [ ] Shared download doesn't check the maximum number of groups per agent. 
![image](https://user-images.githubusercontent.com/13010397/145880393-846dc135-ef76-48d5-92e1-454e6e7dfa6c.png)
- [ ] agents `unknown` state after reinstalling manager with shared download configuration enabled that exceeds the maximum number of groups per agent. Using manage_agents -r doesn't fix the issue. 
Related to previous issue?
![image](https://user-images.githubusercontent.com/13010397/145878437-a81d62f4-e19f-4261-87d2-a247a5b71e87.png)

**Comment by palaciosjeremias** [comment]
WDB testing script.
This is a first iteration of the script that will be used for general commands validation with an example testing script for the sync_agent_groups_get com
[WDB_tester.zip](https://github.com/wazuh/wazuh/files/7707529/WDB_tester.zip)
mand.

**Comment by MiguelazoDS** [comment]
# Test ID: gdbup2

## Environment

### Wazuh Manager:
- Wazuh 3.13.3 to 4.4.0 (dev-10771)
- Centos 8
- Wazuh_DB debug level: 2

### Test cases:

#### pre_upgrade backup generated. Upgrade schemas applied.
- Logs.
  ![1](https://user-images.githubusercontent.com/13010397/152400664-90f6c797-40df-42f1-888d-c87c1c158bab.png)
- Pre upgrade backup.
  ![2](https://user-images.githubusercontent.com/13010397/152400671-7bf1749a-ccc9-4ed0-9c5d-55258c33e77e.png)
#### pre_upgrade backup failed.
#### Upgrade schema failed. Restoration success.
#### Upgrade schema failed. Restoration failed.

**Comment by DProvinciani** [comment]
### Test `gdbbak1`

First I did a clean installation of the Wazuh manager using the branch `dev-10771-agent-groups-files-to-wazuh-db`.

![image](https://user-images.githubusercontent.com/5703274/152401216-fb3d6206-d850-46f5-8fe1-ab8a41ed9938.png)

Then I added the next configuration block to the `ossec.conf` file.

![image](https://user-images.githubusercontent.com/5703274/152401731-abad13c6-bcda-4b0f-a97e-576379a9f01a.png)

Finally, I restarted the Wazuh manager and verified the settings by using the new interface implemented as part of https://github.com/wazuh/wazuh/issues/11732.

![image](https://user-images.githubusercontent.com/5703274/152407012-9f580bc5-50b5-4062-89d0-c4344a9529f4.png)

Then I removed the configuration block and restarted the Wazuh manager in order to verify that the settings took a default value.

![image](https://user-images.githubusercontent.com/5703274/152407350-374b6122-e770-4ff7-affb-f531d226f3f5.png)

**Comment by palaciosjeremias** [comment]
### Test `gdbup1`

**Comment by LucioDonda** [comment]
### Test `gdbup3`

- Wazuh 4.4.0 Installed from .deb and started
![Screenshot from 2022-02-07 09-22-07](https://user-images.githubusercontent.com/95248059/152787358-05794fa4-4f76-411e-acb3-2768f643ae5f.png)

- checked global.db presence and metada table correctnes
![Screenshot from 2022-02-07 09-23-50](https://user-images.githubusercontent.com/95248059/152787667-d4ff30dd-69a2-4a06-ac48-241a3555b440.png)

- stop wazuh service and modification of metadata table in order to force error
![Screenshot from 2022-02-07 09-26-12](https://user-images.githubusercontent.com/95248059/152787959-5e611f19-0f97-4b83-90e6-c119b9c20b83.png)

- start manager and error
![Screenshot from 2022-02-07 09-27-54](https://user-images.githubusercontent.com/95248059/152788224-383da6d3-9791-4935-9de4-5538a7add7fb.png)

- check access to global.db (ERROR)
![Screenshot from 2022-02-07 09-29-27](https://user-images.githubusercontent.com/95248059/152788471-ae6a9ad3-a15c-4ca7-8eff-9fd6cc4e6fcb.png)

**Comment by pereyra-m** [comment]
# Test ID: gdbbak3

## Environment

### Wazuh Manager:
- Ubuntu 20.04. Branch `dev-10771`

### Issue found

The **global.db** backup is not created at startup, fixed in https://github.com/wazuh/wazuh/issues/12128

### Test : manual backups creation :green_circle: 

The following settings were used 
```
    <wdb>
        <backup database='global'>
            <enabled>yes</enabled>
            <interval>1d</interval>
            <max_files>3</max_files>
        </backup>
    </wdb>
```

Two manual backups were added

![prev_backups](https://user-images.githubusercontent.com/65046601/152864840-a8b26eeb-ebfc-4913-92cf-bfd4055b7eea.png)

Now that the maximum is reached, a new backup is requested and the oldest is removed

![delete_message](https://user-images.githubusercontent.com/65046601/152865106-f9ca566a-72e7-4aa9-bfe5-da823f240cac.png)

![after_delete](https://user-images.githubusercontent.com/65046601/152865115-b049684a-4dbb-41c8-8273-7971e4f8d5a8.png)

The same happens when the default `<max_files>` is increased and some backups have a tag
```
    <wdb>
        <backup database='global'>
            <enabled>yes</enabled>
            <interval>1d</interval>
            <max_files>5</max_files>
        </backup>
    </wdb>
```

We have the maximum allowed backups

![max_files_increased](https://user-images.githubusercontent.com/65046601/152866641-01e714fc-bce0-496d-9401-8b5209aafcd0.png)

And the oldest is removed when a new one is requested

![max_files_increased_deletion_message](https://user-images.githubusercontent.com/65046601/152866697-688f791b-21e5-40ad-b027-c4d2e2c2209b.png)

![max_files_increased_deleted](https://user-images.githubusercontent.com/65046601/152866704-746463f7-f71f-4b56-a8e7-5c3739bd68d6.png)

Setting again a low limit cleans all the required snapshots when a new one is requested

```
    <wdb>
        <backup database='global'>
            <enabled>yes</enabled>
            <interval>1d</interval>
            <max_files>1</max_files>
        </backup>
    </wdb>
```

![only_one_backup_message](https://user-images.githubusercontent.com/65046601/152867453-3e440c80-29e0-47f9-afc9-3f4b87ed5819.png)

![only_one_backup](https://user-images.githubusercontent.com/65046601/152867459-1af98ba4-e59f-43bc-8bb6-89b0b742a352.png)

### Test : automatic backups creation :green_circle: 

When the automatic backup mechanism reaches to the `<max_files>` limit, the oldest ones are also deleted

```
    <wdb>
        <backup database='global'>
            <enabled>yes</enabled>
            <interval>2s</interval>
            <max_files>10</max_files>
        </backup>
    </wdb>
```

![automatic_mechanism_messages](https://user-images.githubusercontent.com/65046601/152868341-bcbcec07-c7a5-4e54-9728-ce1fd84924ec.png)

![automatic_mechanism](https://user-images.githubusercontent.com/65046601/152868354-b7e946ee-2e24-471e-85fd-4830fdde0c46.png)

**Comment by MiguelazoDS** [comment]
# Test ID: iu1

## Environment

### Wazuh Manager:
- Wazuh 3.13.3 to 4.4.0 (dev-10711)
- Centos 8

### Test case:

- `/var/ossec/backup` directory Wazuh version 3.13.3
![1](https://user-images.githubusercontent.com/13010397/152991554-514abe1b-ca9c-44d4-ae73-b9c84c0c55aa.png)
- groups folder deleted and new db folder created. 
![2](https://user-images.githubusercontent.com/13010397/152991560-77ebaddc-3f82-4471-85b3-9f4ba94dc3a9.png)
- pre-upgrade and first global db backup created and stored inside **db** folder
![3](https://user-images.githubusercontent.com/13010397/152991561-9fee45c5-3b8a-48f2-832c-f78e15ef293a.png)

**Comment by MiguelazoDS** [comment]
# Test ID: iu2

## Environment

### Wazuh Manager:
- Wazuh 4.0.4 to 4.4.0 (dev-10711)
- Centos 8

### Wazuh Agents:
- Wazuh 4.0.4
- ArchLinux
- Ubuntu Bionic

### Test cases:

- Manager Wazuh version.
![1](https://user-images.githubusercontent.com/13010397/153038049-6532283d-208e-490b-84b3-d2fb02b0ac69.png)
- Registered agents.
![2](https://user-images.githubusercontent.com/13010397/153038055-d1071e99-2fb6-4ea1-9acf-9c01f539a91d.png)
- Agent group information.
![3](https://user-images.githubusercontent.com/13010397/153038058-a3abdbc3-f3c5-4ce2-9786-f52a26097108.png)
- Agent group files content.
![4](https://user-images.githubusercontent.com/13010397/153038062-3e5759ff-f069-4bb4-9c9a-eca712021b88.png)

**Comment by MiguelazoDS** [comment]
# Test ID: gdbup4

## Environment

### Wazuh Manager:
- Centos 8
- Wazuh_DB debug level: 2

### Test case:

- Upgrading from a version that have a global DB with metadata table. (count = 1)
![2](https://user-images.githubusercontent.com/13010397/153068177-534a7069-4bd0-4707-902d-3af266a4ba92.png)
![3](https://user-images.githubusercontent.com/13010397/153068180-fb3f59a9-7557-4017-90bb-af1cc6cb1980.png)
- Force an read error by deleting the "metadata" table.
![4](https://user-images.githubusercontent.com/13010397/153068181-88bbe71b-a2c4-4af6-a20e-e4a54b55f623.png)
- Error log.
![5](https://user-images.githubusercontent.com/13010397/153068182-9e4be3f5-c705-409a-8adc-9c39b168dd15.png)

**Comment by DProvinciani** [comment]
Having completed all the QA instances, we close this issue.
