### ISSUE TITLE
[cis_centos8_linux.yml] rule 6591 and rule 6597 are contradictory

### ISSUE THREAD

**Issue by WallaceCS** [wazuh/wazuh#11258]
|Wazuh version| Component | Action type |
|---| --- | --- |
| master | Rules | Error |

## Description

file:  ruleset/sca/centos/8/cis_centos8_linux.yml:    
 - id: 6591   
    title: "Ensure nftables is not enabled"  

 - id: 6597   
    title: "Ensure nftables service is enabled"  

From the description, rule 6591 and rule 6597 are contradictory?

**Comment by jk-olaoluwa** [comment]
The two rules are not contradictory

6591 is intended to prevent conflicts between nftables and firewalld while 6597 is intended to ensure that nftables is enabled.

From the description, 

6591 - Nftables should not be enabled to prevent conflicts with firewalld.
6597 - Nftables service should be enabled to improve the security of the system.
