### ISSUE TITLE
Ossec vs rootcheck

### ISSUE THREAD

**Issue by sulaiman35** [wazuh/wazuh#1126]
Wazuh is using ossec and rootcheck, and they both provide similar results.

Can you please share difference, if its same, then can we stop one of them.

**Comment by chemamartinez** [comment]
Hi @sulaiman35 ,

First of all, Wazuh born as a fork from OSSEC, including new interesting capabilities such as the integration with the Elastic Stack, a Restful API or a vulnerability detector module, among others. You could read more about the Wazuh project here:

https://documentation.wazuh.com/current/index.html

However, both Wazuh and OSSEC are HIDS _(Host-based Intrusion Detection System)_ which are made up of different components. One of these components is `Rootcheck`,  which is in charge of the Rootkit detection and policy monitoring.

To sum up, it doesn't matter you are using Wazuh or OSSEC but each agent will include a `rootcheck` module. If you want to disable this particular module you could change the `disabled` field in the configuration file located at `/var/ossec/etc/ossec.conf`.

```
<rootcheck>
    <disabled>yes/no</disabled>
    ...
</rootcheck>
```

You can also find more information about this module at the following link:

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/rootcheck.html

If you were looking for another kind of information, could you please clarify your question?

Regards,
Chema.

**Comment by sulaiman35** [comment]
Thanks Chema,

and what is difference between openscap and ossec ?

**Comment by chemamartinez** [comment]
Hi again @sulaiman35,

OpenSCAP is an open-source tool to perform security audits to systems. Wazuh includes an integration with this tool which allows us to schedule scans and to report the results in form of alerts.

It works as another component (the same as `Rootcheck`), both modules perform policy monitoring among others tasks. You can find more detailed information about this module here:

https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/index.html

For now, OSSEC doesn't contain an OpenSCAP integration.

Best regards,
Chema.

**Comment by sulaiman35** [comment]
Thanks @chemamartinez , 

Thats what I was lookin for that whether are the same or not but they are same then I am disabling openscap.

 <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
  </wodle>

Regards,
Sulaiman
