### ISSUE TITLE
WPK batch upgrade based on configuration groups

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#11270]
Hello,

right now, the remote upgrade process is a bit cumbersome, especially for big environments, as it is hard to segment it based on the deployed environment distribution/taxonomy.

We already use configuration groups to remotely send configurations to agents, most of the time reflecting the segmentation of the environment. Using these groups to schedule the agents' remote upgrade will ease the process tremendously.

Regards,

Javier.

**Comment by davidjiglesias** [comment]
Already addded in v4.3.0
