### ISSUE TITLE
Compare the agent restart time in v4.2 and v4.3

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh#11287]
|Wazuh version|Component|
|---|---|
| 4.2/4.3 | Wazuh agent |

## Description

The aim of this issue is to compare the time that it takes an agent to restart and reconnect to the master. From the results obtained in RC1 testing for https://github.com/wazuh/wazuh-qa/issues/2283 and https://github.com/wazuh/wazuh-qa/issues/2282 it seems that version 4.3.0 might be taking a longer time than in version 4.2, almost 15 seconds.

**Comment by noise-kngdm** [comment]
## Issue update
To compare both times we prepared a clean environment with one manager and one agent and did the following for both Wazuh `v4.2.5` and `4.3`.
1. Compiling and installing the version tested.
2. For a hundred times:
    1. Registering the timestamp before restarting the agent.
    2. Restarting the agent using `service wazuh-agent restart`.
	3. Checking that the agent is connected with the manager searching for the `Active` string executing `/var/ossec/bin/agent_control -i {agent_id}` in the manager.
	4. Registering the timestamp after checking that the agent is connected to the manager.
	5. Computing the difference between the timestamps and storing it.
3. Computing the mean value from the samples.

The computed mean value for Wazuh `v4.2.5` is `7.067346479892731` seconds.
<details><summary>v4.2.5 samples</summary>

	5.966964960098267
	7.9348061084747314
	5.85348105430603
	6.958738088607788
	7.971719026565552
	6.9284069538116455
	5.851058006286621
	6.886885166168213
	7.9254469871521
	6.944610118865967
	7.890584945678711
	6.92403507232666
	7.911042928695679
	7.877897024154663
	7.9173338413238525
	6.90896201133728
	7.976138114929199
	6.940140008926392
	6.945461988449097
	5.9643731117248535
	6.948630094528198
	5.963160991668701
	6.911429166793823
	6.9127209186553955
	7.902384042739868
	5.860053062438965
	6.9438440799713135
	5.901813983917236
	6.920233964920044
	6.900954961776733
	5.9579479694366455
	6.93511700630188
	6.928992986679077
	5.9440600872039795
	6.90484881401062
	7.982818126678467
	6.9673011302948
	7.942678928375244
	5.947643995285034
	5.839099168777466
	7.983475923538208
	7.954901933670044
	6.919549942016602
	7.020390033721924
	7.914294004440308
	5.986634969711304
	6.902837038040161
	6.975466966629028
	6.893967151641846
	7.929746866226196
	7.925928831100464
	5.898425102233887
	7.894792079925537
	6.939400911331177
	6.920953035354614
	5.884200096130371
	6.9681761264801025
	6.916862964630127
	6.977763891220093
	7.989189147949219
	5.8756749629974365
	6.963099002838135
	5.913421154022217
	7.965498924255371
	7.881069183349609
	5.907220125198364
	6.932286024093628
	7.920533895492554
	5.932890892028809
	7.906135082244873
	7.86051607131958
	6.9260618686676025
	7.8868279457092285
	6.906646966934204
	7.020742893218994
	6.888478994369507
	7.928550958633423
	7.941009044647217
	6.960111141204834
	6.948009014129639
	6.862761974334717
	7.016779184341431
	7.893722057342529
	6.909893035888672
	7.888479948043823
	7.878278017044067
	6.881509065628052
	7.866489887237549
	5.963464021682739
	7.984336853027344
	5.903970003128052
	6.94516396522522
	6.987405061721802
	7.929535865783691
	6.9660351276397705
	7.932383060455322
	6.920695066452026
	6.869114875793457
	7.978006839752197
	6.901063919067383

</details>

The computed mean value for Wazuh `4.3` is `7.153647015094757` seconds.
<details><summary>4.3 samples</summary>

	11.694042921066284
	6.880857944488525
	8.023374080657959
	6.983896017074585
	6.941179990768433
	6.97849702835083
	7.933934926986694
	7.949950933456421
	6.961318016052246
	6.96327805519104
	7.937133073806763
	7.950060844421387
	7.965883016586304
	6.958197116851807
	6.936424970626831
	7.893289089202881
	7.942762136459351
	6.924642086029053
	7.997025012969971
	7.871495962142944
	6.954426050186157
	6.895004034042358
	6.9596710205078125
	7.968415021896362
	7.941728830337524
	7.950477123260498
	5.874369859695435
	6.961721897125244
	6.9806859493255615
	5.946107864379883
	6.979367017745972
	6.8722310066223145
	5.955942153930664
	6.908692121505737
	6.94058895111084
	5.870369911193848
	6.931256055831909
	7.985656023025513
	7.960162878036499
	5.869391202926636
	6.92417311668396
	6.951623201370239
	6.95970892906189
	5.961596965789795
	6.962269067764282
	6.970012187957764
	7.924047231674194
	7.9451329708099365
	6.924322843551636
	5.968835830688477
	6.948920011520386
	6.906842947006226
	6.940917015075684
	7.986944913864136
	6.997053146362305
	5.879601955413818
	7.9580559730529785
	5.852664947509766
	7.932776927947998
	6.0116260051727295
	6.905256986618042
	5.911797046661377
	7.993474960327148
	7.900657892227173
	7.91409707069397
	5.865537881851196
	6.930989980697632
	7.9351818561553955
	6.988521099090576
	6.946477890014648
	7.946702003479004
	6.919960021972656
	6.909345865249634
	5.951546907424927
	6.904238939285278
	5.945713996887207
	6.865257024765015
	7.963709115982056
	7.94054102897644
	7.956973075866699
	6.934182167053223
	6.838137149810791
	5.914354085922241
	7.010756969451904
	5.941667079925537
	6.879405975341797
	7.927600145339966
	7.976936101913452
	6.939766883850098
	7.955317974090576
	7.938923120498657
	6.890181064605713
	6.899728775024414
	6.90217399597168
	6.935740947723389
	7.912577867507935
	6.874053955078125
	5.955686092376709
	7.91551399230957
	6.925382137298584

</details>

### Conclusions
From the results of the tests we can deduce that the agent restart-connect process might be 1.22% slower in version `4.3` than in version `v4.2.5`, however, we'd need a bigger sample set to be able to make a more precise assumption. We'll repeat the test for 1000 executions-per-version and will update the issue with the results soon.
