### ISSUE TITLE
Create a new backup mechanism for Wazuh-DB databases - Design  

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#11317]
### Description 

As part of the changes introduced in the epic #10771, the agents' groups files will be migrated to **global.db**. Until now, this database could be safely removed because it was always recreated with information from other sources. But now it will be the only place where the groups assignation will be stored, so a configurable mechanism should be implemented to store this information regularly.

This is a tracking issue to reflect the analysis and design of the backup mechanism.

### DoD

- [ ] A design proposal should be presented and approved by the team

**Comment by pereyra-m** [comment]
### Proposal

A new set of commands should be created for Wazuh-DB
- `global backup`: this command should dump the current DB status to disk with an appropriate name, considering the current constraints (quantity, etc.) and erasing the older files if necessary 
- `global get backup`: returns a list of the current backups available
- `global restore BACKUP_NAME`: the current database will be replaced for the version identified in the command.

A new configuration block is needed to define the backup mechanism. It will be visible and enabled by default

```
<database_backup>
    <enabled>yes</enabled>
    <backup_every>1d</backup_every>
    <backup_max_files>10</backup_max_files>
</database_backup>
```

Wazuh-DB could have a new thread in charge of reading and sending the backup command. Another option is to delegate this behavior to another daemon, like **monitord**.

The files will be stored in `WAZUH_HOME/queue/db/global_backup` with a name structure like `global.db-backup-UNIXTIMESTAMP`.

The backup process proposed may be done in two different ways.
**Option A**
- Run a [VACUUM INTO](https://www.sqlite.org/lang_vacuum.html#vacuuminto) query to create a backup optimized in size, because the erased data will be removed and the empty spaces will be used (fragmentation)
- Compress the resulting database. This process might not be as space efficient, but the restore process only requires a replacement

**Option B**
- Create a text representation of the database with `.dump` [(Converting An Entire Database To A Text File)](https://sqlite.org/cli.html)
- Then compress the resulting database. This option is more space efficient, but to recreate the database all the file must be read and inserted to a new database

The recover process may be done as following. This process is designed to prevent any write/read operation that was requested before the restore begins to be executed with the new and possible not consistent data: 
- The **global.db** may have a new "recover" table, and we write there the file name of the backup to recover (if it exists). Then, we restart the manager manually (the daemon is unable to perform this operation)
- We add a new step in the open database method. Before the version is confirmed (used for upgrades), the "recover" table is read. If a value is found, the current database is removed (may be saved too), the back-up is recreated in a new file and then the upgrade check continues.

**Comment by FontouraAbreu** [comment]
Do the set of commands mentioned:

- `global backup create`
- `global backup get`
- `global backup restore BACKUP_NAME`

Are still in use?

When I try the `wazuh-db -h` tool I don't see any references to those

**Comment by pereyra-m** [comment]
Please ping @MiguelazoDS

**Comment by FontouraAbreu** [comment]
@MiguelazoDS Could you help me with that?

**Comment by MiguelazoDS** [comment]
Hi @FontouraAbreu, 

Indeed, those commands are still present in the latest release v4.14.5. 

The reason you don't see any reference to those commands it is because the options listed using `wazuh-db -h` are used for managing the wazuh-db binary (/var/ossec/bin/wazuh-db) 

The "global backup create|get|restore", as well many other commands, are commands sent to the wazuh-db exposed socket. You need the wazuh-db binary in a running state to send commands to the wazuh-db socket.
