### ISSUE TITLE
New engine development environment

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#11336]
Create the project scaffolding, branch and tasks to start the development process.
The dev env should resolve:

- [x] Automatic dependency management (vcpkg/cpm/conan)
- [x] Unit testing (google test)
- [x] Unit benchmarking (google benchmark)
- [x] Logging (google log)
- [x] Documentation generation
- [x] IDE integration (go to, contextual help, auto-completion, etc.)
- [x] Building process using CMake with IDE integration
- [x] Linter (astyle, clang-format)
- [ ] Safety checkers (compiler, valgrind, etc.)
- [x] Create README

Some features like test coverage, integrated benchmarks and CI/CD automation will be worked in future issues, in the integration process prior to a release.

**Comment by JavierBejMen** [comment]
Safety checkers using valgrind are not currently implemented, once we start development code and test we will add them.

**Comment by gdiazlo** [comment]
The current environment work for us to start creating the components. We will evolve the environment as needed in the future.
