### ISSUE TITLE
Wazuh unatended instalation doesnt work on RaspberryPI 64bit

### ISSUE THREAD

**Issue by fearx135** [wazuh/wazuh#11338]
Hello I'm trying to install Wazuh in a raspberryPI 64bit using the unatended instalation guide, but I get the error that is for 64 bits system only, but the raspberry is 64bit

```
root@raspberrypi:/home/pi# uname -m
aarch64
root@raspberrypi:/home/pi# curl -so ~/unattended-installation.sh https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/unattended-installation.sh && bash ~/unattended-installation.sh
12/13/2021 16:33:23 ERROR: Uncompatible system. This script must be run on a 64-bit system.
root@raspberrypi:/home/pi#
```

Any idea of how I can solve this?

**Comment by RamiroRD** [comment]
@Hi @fearx135!
I will be taking a look at this problem. I'm going to need the Raspbian version and ideally the Raspberry model as well. 
In the mean time I'll take a look at the installation script.

**Comment by fearx135** [comment]
Hello Raspian release "Debian GNU/Linux 11 (bullseye)" , Model: Raspberry Pi 4 Model B Rev 1.4
```
root@raspberrypi:/home/pi# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
root@raspberrypi:/home/pi# uname -m
aarch64
```
```
root@raspberrypi:/home/pi# cat /proc/cpuinfo | grep 'Revision' | awk '{print $3}'
d03114
root@raspberrypi:/home/pi# cat /proc/device-tree/model
Raspberry Pi 4 Model B Rev 1.4
```
```
root@raspberrypi:/home/pi# cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : d03114
Serial          : 10000000XXXXXXX (I deleted the serial)
Model           : Raspberry Pi 4 Model B Rev 1.4
root@raspberrypi:/home/pi#

```

**Comment by RamiroRD** [comment]
Okay, so I just spoke with the team in charge of the unattended installer and they just confirmed that this installation script does not currently support any architecture other than x86_64. I created an issue (https://github.com/wazuh/wazuh-packages/issues/1073) so it gets fixed at some point.

As to your case, what you could do is simply follow the manual installation steps available [here](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html).

Hope that helped. Let me know how that goes.

**Comment by RamiroRD** [comment]
I'm closing this issue as I created a new one in the repository affected by this problem: https://github.com/wazuh/wazuh-packages/issues/1073.
Please report any other problems you run into in a separate issue.
