### ISSUE TITLE
Catalog component creation for the new engine

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#11337]
The catalog will be in charge of managing the load, update and storage of all the assets needed by the engine.

It should support multiple storage systems and should make versioning easy to manage.
Generally, it will read YAML definitions, but it will use JSON internally, so when loading content from a storage driver a conversion to the internal representation must be done.

- [x] Create a file storage driver
This driver will store all the assets in plain text files in the program folder. Each kind of asset must be placed in a given folder tree. All trees are then processed recursively, searching for files to load.
The store engine must support loading files and write to them.

- [x] Create API to read assets
There should be possible to load all the assets by kind:
  - [x] Decoders
  - [x] Rules
  - [x] Outputs
  - [x] Filters
  - [x] Environments
  - [x] Schemas

- [x] Create schema validation API
We need to validate an asset using a schema from the catalog. The schema validation should happen when an asset is inserted into the catalog, but not when it is recovered through a storage driver, unless it is the plain text file store. 
In this case, we will likely use the validation on load, to ensure possible out-of-band file modifications are still validated against the schema.
We will use an off-the-shelf validation library.

**Comment by gdiazlo** [comment]
Closed by #11385
