### ISSUE TITLE
Wazuh agent consuming too much ressources

### ISSUE THREAD

**Issue by tarekkilani** [wazuh/wazuh#11346]
Hello community, 

I have a wazuh manager server in my information system with installed agents.
After deploying a GPO to install wazuh agent i received many complaints from emloyees saying that the wazuh agent is consuming too much PC ressources as you can see in the screenshot below.
Is there any optimization that could be done to minimize the consumption of ressources?
Thanks in advance.

![image](https://user-images.githubusercontent.com/36234835/145957551-4b848573-1356-4186-8ce2-2d791c0c7d75.png)

**Comment by JoseAntonioMHerrera** [comment]
Hello tarekkilani, I'll need to see the ossec.log of one of your machines to see if some events keep repeating themselves and could be discarded consequently. Also, I'll need to check the ossec.conf on the same machine with the resources problem to see if some options could be removed as well. 

The default wazuh options offer a general solution for windows monitorization, but in some cases depending on the host some options could cause an overflow of events. For example syscheck module comes with a list of registries and directories already set for monitorization and can be edited according to necessities. 

One last question, did you set a shared configuration in the manager to all of your agents (/var/ossec/etc/shared)?  If so, I'll need to check that as well. I'll wait for your reply!

**Comment by tarekkilani** [comment]
Hello @JoseAntonioMHerrera , 

Please find attached ossec.log and ossec.conf of a machine.
Concerning your last question, i didn't use the /var/ossec/etc/shared, but if you want to know if all machines have the same agent configuration or not, the answer is YES because i used a GPO policy in my AD server and the ossec.conf was injected to all windows hosts in my network.

- ossec.log : [osseclog.txt](https://github.com/wazuh/wazuh/files/7711512/osseclog.txt)
- ossec.conf : [ossecconf.txt](https://github.com/wazuh/wazuh/files/7711513/ossecconf.txt)

Best regards.

**Comment by JoseAntonioMHerrera** [comment]
@tarekkilani I see a couple of problems within your ossecconf.txt. First, you can take a look to the following [metrics](https://github.com/wazuh/wazuh-jenkins/issues/3066#issuecomment-990246526) to check what is the expected impact of the agent in a Windows host for versions 4.2.5-4.3. The values you posted are below average, but there is some problems within your ossec.conf that could have a negative impact on the machine resources. 

In general isn't a good practice to monitor all the hard drive (C:/) with whodata/realtime monitorization mode. It has a negative impact on resources if the path contains to many files and they are constantly changing. It seems like this is happening to your agent. If you take a look at the ossec.log you posted, you'll see an specific error about realtime overflow logging constantly. The only path monitored with that mode is **%PROGRAMDATA%\Microsoft\Windows\Start Menu\Programs\Startup**. 

I'll need to check which events are causing the overflow. You can check that under /var/ossec/logs/alerts/alerts.log or u/var/ossec/logs/archives/archives.log in your manager to see if any event from that agent reached the manager before the overflow. I'll wait for your reply!.

**Comment by tarekkilani** [comment]
@JoseAntonioMHerrera i tried to check the link you provided but it seems like the page is not found.
I commented the line below in my ossec.conf agent to disable the monitoring of C:\\ but it didn't resolve the problem as you can see in the screenshot below (we still face the same problem and the agent is consuming too much ressources [especially the disk]).

`#    <directories check_all="yes" whodata="yes" restrict=".exe$|.dll$|.ps1$">C:\\</directories>
`

![37](https://user-images.githubusercontent.com/36234835/146152648-345a88f7-bb55-4966-903d-ff25370791ae.PNG)

Please find attached the /var/ossec/logs/alerts/alerts.log :  [alertslog.txt](https://github.com/wazuh/wazuh/files/7717678/alertslog.txt)

**Comment by JoseAntonioMHerrera** [comment]
@tarekkilani  Hi again, sorry for the late response. In XML comments are added like this . You should wrap the line between  instead of #. Remember to restart the agent after changing the ossec.conf of the agent. Please do that and look if the spikes in consumption lower down.

**Comment by tarekkilani** [comment]
Hi @JoseAntonioMHerrera do you mean that comments should be like this `<!-- comment -->` ?
Concerning file_status.json, When i try to access /var/ossec/queue/logcollector to retreive the file it says "No such file or directory".

**Comment by JoseAntonioMHerrera** [comment]
@tarekkilani Yes, you need to add comments using those closing keywords. Remember to restart after you finish editing the file.

About the other issue, can you please tell me the versions of your manager and agents?

**Comment by tarekkilani** [comment]
@JoseAntonioMHerrera 

Manager : v4.1.4
Agents : v4.2.3

**Comment by JoseAntonioMHerrera** [comment]
@tarekkilani You need to upgrade the manager to have at least the same version as the agents. This is for compatibility reasons, as the agent's version can be older than the manager, but the manager version needs to be at least equal or greater than the agents. To read more about this check the following link: [components compatibility](https://documentation.wazuh.com/current/upgrade-guide/compatibility-matrix/index.html?highlight=compatibility%20matrix#components-compatibility)

Check the following links to read about the upgrade process: https://documentation.wazuh.com/current/upgrade-guide/upgrading-wazuh.html

**Comment by tarekkilani** [comment]
@JoseAntonioMHerrera 

I just followed the documentation you provided to upgrade the wazuh-manager.
The manager version is v4.2.5 now. But when i access to the Kibana UI i get this error.

![image](https://user-images.githubusercontent.com/36234835/146756518-54233acf-4b75-40fa-ad53-12bfe5b5782a.png)

**Comment by tarekkilani** [comment]
@JoseAntonioMHerrera 

I just did the upgrade, now i have wazuh manager v4.2.5.
I will keep an eye on the agents performance and i will let you know the results ASAP.

**Comment by tarekkilani** [comment]
Problem solved by upgrading the wazuh manager. Thanks a lot.
