### ISSUE TITLE
Reduce memory on API child processes after implementing multiprocessing

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#11350]
|Wazuh version|Component|
|---|---|
| 4.3.0 | Wazuh API |

By default, the Wazuh API process pool **forks** child processes, making an exact clone of the parent process and thus using the same amount of memory although it is not needed. It is mandatory to reduce the memory on processes which do not require that much.

![image](https://user-images.githubusercontent.com/37274979/145981077-39127b4a-983b-4230-a093-ab6ce912f43e.png)

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

Provisionally we have generated a custom package with the multiprocessing fix. We are working on getting this fix applied to all Python packages we generate from now on:

Link: https://framework-python.s3.amazonaws.com/deps/15-MPFIX-PSUTILFIX/precompiled_cpython/amd64/cpython.tar.gz

**Comment by vicferpoy** [comment]
# Status update

After doing some manual testing with the custom package @AdriiiPRodri provided, I could obtain basic working version with child processes _spawning_ instead of _forking_. To read more about the differences, check: [multiprocessing context types](https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods)

However, this new implementation creates more child processes and requires of some untested and probably breaking changes to make it fully work.

## New approach

Understanding what `forking` means, child processes will be clones of the parent process from the moment they are created. Analyzing the code, we were forking child processes after loading everything in the parent process. This would end up with (at least for the Wazuh API) 3 Python processes with around 100MB of allocated memory each.

To prevent this, we are going to perform the following steps:

1. Reduce the total amount of allocated memory the parent process uses.
2. Force the child processes from each process pool to fork before the parent process imports modules that they do not need. This way, each child process will only import modules that are required for their own tasks.

This effort will not only improve memory consumption in child processes, but will also improve the existing memory consumption by the Wazuh API before the implementation of multiprocessing.

**Comment by vicferpoy** [comment]
# Status update

## Wazuh API main script profiling

To better understand which sections of the code could be improved, I analyzed all the sections in the `wazuh-apid.py` script, which contains the necessary code to start the Wazuh API. Results may vary slightly from run to run, but are equally valid for memory usage comparison.

> **RES:** Resident memory used by the process. **SHR:** Shared memory used by the process. All data was collected from the parent process.

1. The Wazuh embedded python starts from the following memory metrics:

| RES | SHR | Increment |
|---------|---------|---------------|
|    38568 KB     |     11208 KB    |       -        |

2. Importing the module `connexion`, used as a wrapper for `aiohttp`:

| RES | SHR | Increment |
|---------|---------|---------------|
|    49992 KB     |     12152 KB    |       11424 KB       |

3. Importing the module `alogging`, which contains [python-jose](https://pypi.org/project/python-jose/):

| RES | SHR | Increment |
|---------|---------|---------------|
|    67880 KB     |     13672 KB    |       17888 KB       |

4. Importing necessary modules from the Wazuh framework.

| RES | SHR | Increment |
|---------|---------|---------------|
|    68300 KB     |     13856 KB    |       420 KB       |

5. Loading the OpenAPI specification.

| RES | SHR | Increment |
|---------|---------|---------------|
|    95820 KB     |     15136 KB    |       27520 KB       |

6. AIOHTTP setup and running the web server:

| RES | SHR | Increment |
|---------|---------|---------------|
|    102812 KB     |     15240 KB    |      6992  KB       |


As we can see, the main memory consumers are the modules `connexion`, `python-jose` and loading the OpenAPI specification.

The module imports are necessary for security and integrity reasons, but loading the whole specification (apart from the server itself) as a variable is quite questionable. This is used primarily to increase maintainability but, in my opinion, the trade off is not worth. I will study and try some refactoring ideas and compare the memory stats.

**Comment by vicferpoy** [comment]
# Status update

After refactoring the code and trying different approaches to handle the API specification, we concluded with the following:

1. After using a _lite version_ of the API specification (removing examples, descriptions and other metadata used primarily for the Wazuh documentation), I reduced the memory consumption by ~6 MB and only for the parent process. To achieve this, we would have to maintain another specification file of about half the size. This solution was not good enough to implement.

2. A refactor was made in the `alogging` Wazuh module, reducing the allocated memory by the Wazuh API logger (and thus, by every process, parent or child). With a simpler implementation of the logging user information, we did not only reduced the allocated memory but also improved the logging, adding the user information when there is a `401` (unauthorized) request:

```shellsession
2021/12/16 10:37:06 INFO: vicferpoy 172.23.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.006s: 401
2021/12/16 10:37:12 INFO: wazuh 172.23.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.358s: 200
2021/12/16 10:37:30 INFO: wazuh 172.23.0.1 "GET /agents" with parameters {"wait_for_complete": "true"} and body {} done in 0.049s: 200
```

  Previously, we would get an `unknown_user`.

3. A refactor of the `wazuh-apid` script was made to make process pools initialize on start, forcing the forking of child processes when only the minimum required modules are imported. This will drastically reduce the amount of allocated memory by the child processes. This way, each child process will import only the necessary modules to do their tasks. This also gives us room for improvement in the long term by refactoring the Wazuh SDK modules.

  As a downside, the very first request for each child process (ask for a token and any local request) will have an extra delay as the child process will have to import whatever it needs.

With all these changes, this is the difference in memory consumption in comparison with the current code in `4.3` after asking for a token and making a `GET /agents` request:

| Version            | Resident Memory | Shared Memory |
|--------------------|-----|-----|
| v4.3.0-rc1         |  294760 KB   |   24696 KB  |
| New implementation |   205688 KB  |  32748 KB   |

> Performance wise, the Wazuh API remains the same.
