### ISSUE TITLE
Review absolute paths on API configuration options

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11356]
# Description

There's a problem regarding absolute paths and `os.path.join` that we should review in depth since all paths must be relative to wazuh directory.

Example below:
### API configuration file:
```
logs:
 level: "info"
 path: "/home/api.log"
```

### API log file location:
```
root@c754766e25b8:/# ll /home/
total 12
drwxr-xr-x 1 root  root  4096 Dec 14 12:15 ./
drwxr-xr-x 1 root  root  4096 Dec 14 12:14 ../
-rw-rw---- 1 wazuh wazuh  183 Dec 14 12:15 api.log
```

### `os.path.join` behavior:
```
>>> from os.path import join
>>> path = '/home/api.log'    
>>> wazuh_dir = '/var/ossec'
>>> join(wazuh_dir, path)
'/home/api.log'
```
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
We are finally removing the option to configure log path in https://github.com/wazuh/wazuh/issues/11409
