### ISSUE TITLE
Improve librpm footprint

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#11355]
|Epic|
|---|
| #10324 |

Hi team,

Wazuh footprint is one of the design's key requirements. Adding librpm might have mainly impact on package size, so this issue aims to solve this by grouping all librpm **real** objects (*.o) dependencies into only one static library, rather than including every static library info libwazuhext.

## DoD
- [x] Check if optimization flags were propagated as expected
- [x] Strip unused symbols from deps libraries.
- [x] Identify librpm real dependencies (in terms of objects rather than whole static library). 
- [x] ~Unarchive librpm and archive it again with the real dependencies objects as one single librpm.a static library. See HP-UX external library approach [here](https://github.com/wazuh/wazuh/blob/f4ab39d1f70cd92f18606e229cbc90aec46aa39c/src/Makefile#L1588-L1596).~ EDIT: since the only real dependency is popt (for reading rpm database) this task does not save us footprint.
- [x] ~Add this all-in-one librpm.a static library to libwazuhext.so~
- [x] ~Feasibility to detect if compilation target is rpm-based. This is important to avoid packing librpm into deb packages. EDIT: deeper code source separation should be done to this approach.~
- [x] Generate new deps packages (sources and precompiled) if necessary
- [x] ~Extra: reduce librpm deps source and precompiled packages~. EDIT: librpm and popt (source and precompiled) packages were already trimmed. 

Regards,
Nico

**Comment by jnasselle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/11355?planning-poker) with ZenHub @Dwordcito @HanesSciarrone @RamiroRD

**Comment by Dwordcito** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/11355?planning-poker) with ZenHub @jnasselle

**Comment by jnasselle** [comment]
## Baseline information
Specs based on #11571 commit https://github.com/wazuh/wazuh/pull/11571/commits/5d4e7c02c9bbd79c35cc0fa2216bae9fce5d5563 generated packages

## Comparision
Working on first optimization step
