### ISSUE TITLE
Group assignment exceeds by one the maximum number specified per agent. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#11353]
|Wazuh version|Component|
|---|---|
| 4.4.0 | agent_groups |

As a test, the maximum number of groups an agent can take was changed by 2. 
Using the agent_groups tool is allowed to assign 2 new groups besides the already existent `default` group. 

![image](https://user-images.githubusercontent.com/13010397/146017717-6953948b-166e-4c09-a738-2a3d48033b08.png)

It will throw the assignment error when we try to add a fourth group to the agent.
![image](https://user-images.githubusercontent.com/13010397/146018169-8aa48cc6-5908-4ab3-a974-0f4394ef5052.png)

During the validation here
https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/agent.py#L746

It is not considering the new group assignment. Which one is stored in `multigroup_name` 
https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/agent.py#L743

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by yanazaeva** [comment]
## Issue update

The first change performed was removing the hardcoded number of the maximum groups allowed per multigroups and setting a placeholder for the value. This way, if we change the number of maximum groups allowed, and we exceed it we will see the current max value, and not always 256, which was the hardcoded value. 

Also, after the change made to not exceed the maximum number of agents allowed, we can see that the cluster is working as expected:
```
root@2ca4a31f2fb0:/var/ossec/framework# /var/ossec/bin/agent_groups -s -i 003 
The agent '7fafe937ea72' with ID '003' belongs to groups: default, 1.
root@2ca4a31f2fb0:/var/ossec/framework# /var/ossec/bin/agent_groups -a -i 003 -g 2
Do you want to add the group '2' to the agent '003'? [y/N]: y
Error 1737 - Maximum number of groups per multigroup is 2
root@2ca4a31f2fb0:/var/ossec/framework# /var/ossec/bin/cluster_control -l         
NAME             TYPE    VERSION  ADDRESS          
wd-ar_manager_1  master  4.4.0    wd-ar_manager_1  
ef229c413f30     worker  4.4.0    172.21.0.4       
5f13f19bdd2c     worker  4.4.0    172.21.0.5       
root@2ca4a31f2fb0:/var/ossec/framework# /var/ossec/bin/cluster_control -a
ID   NAME          IP          STATUS  VERSION       NODE NAME        
000  2ca4a31f2fb0  127.0.0.1   active  Wazuh v4.4.0  wd-ar_manager_1  
001  98dfce054d0a  172.21.0.8  active  Wazuh v4.4.0  ef229c413f30     
002  9f1e2b89a35b  172.21.0.6  active  Wazuh v4.4.0  5f13f19bdd2c     
003  7fafe937ea72  172.21.0.7  active  Wazuh v4.4.0  ef229c413f30     

```

**Comment by yanazaeva** [comment]
## Test report
[11353_test_results.zip](https://github.com/wazuh/wazuh/files/7959294/11353_test_results.zip)

## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| wazuh/core/cluster/dapi/tests/test_dapi.py | 30 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_client.py | 15 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_cluster.py | 29 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_common.py | 60 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_control.py | 5 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_local_client.py | 13 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_local_server.py | 23 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_master.py | 42 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_server.py | 19 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_utils.py | 6 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_worker.py | 31 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_active_response.py | 14 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_agent.py | 142 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_cdb_list.py | 38 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_common.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_configuration.py | 35 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_database.py | 13 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_decoder.py | 16 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_exception.py | 3 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_input_validator.py | 3 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_logtest.py | 2 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_manager.py | 15 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_mitre.py | 13 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_pyDaemonModule.py | 5 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_results.py | 40 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_rootcheck.py | 13 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_rule.py | 22 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_sca.py | 12 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_security.py | 12 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_stats.py | 12 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_syscheck.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_syscollector.py | 3 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_task.py | 8 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_utils.py | 228 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_vulnerability.py | 1 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_wazuh_queue.py | 18 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_wazuh_socket.py | 20 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_wdb.py | 24 | 0 | 0 |  | :green_circle: |
| wazuh/core/tests/test_wlogging.py | 8 | 0 | 0 |  | :green_circle: |
| wazuh/rbac/tests/test_auth_context.py | 2 | 0 | 0 |  | :green_circle: |
| wazuh/rbac/tests/test_decorators.py | 105 | 0 | 0 |  | :green_circle: |
| wazuh/rbac/tests/test_default_configuration.py | 55 | 0 | 0 |  | :green_circle: |
| wazuh/rbac/tests/test_orm.py | 54 | 0 | 0 |  | :green_circle: |
| wazuh/rbac/tests/test_preprocessor.py | 11 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_active_response.py | 12 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_agent.py | 117 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_cdb_list.py | 53 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_ciscat.py | 33 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_cluster.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_decoder.py | 35 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_group.py | 8 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_logtest.py | 6 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_manager.py | 36 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_mitre.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_rootcheck.py | 50 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_rule.py | 56 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_sca.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_security.py | 73 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_stats.py | 7 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_syscheck.py | 25 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_syscollector.py | 12 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_task.py | 28 | 0 | 0 |  | :green_circle: |
| wazuh/tests/test_vulnerability.py | 31 | 0 | 0 |  | :green_circle: |
