### ISSUE TITLE
SCA for RHEL false positive for check 5077 on systems with IPv6 disabled

### ISSUE THREAD

**Issue by joar-rasmussen** [wazuh/wazuh#11366]
|Wazuh version| Component | Action type |
| 4.2.1 / Wazuh Cloud | Rules/Decoders | Error |

## Description

In check 5077 "Ensure ICMP redirects are not accepted" on RHEL systems with IPv6 disabled, we get a erroneous "Failed" in our report. 

IPv4 check commands like "sysctl net.ipv4.conf.all.accept_redirects" are OK, returning "net.ipv4.conf.all.accept_redirects = 0"
But IPv6 check commands like "sysctl net.ipv6.conf.all.accept_redirects" instead return "sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory" and this makes the check fail even if the system is CIS compliant.

### Service/Product/Module
RHEL7/8 and possibly 9, with IPv6 disabled as recommended by CIS.

### Current results
Check 5077 is reported as failed even if the system is actually compliant.

### Expected results
An accurate result on the compliance check, no matter if only IPv4, only IPv6, or both, are loaded.

**Comment by 72nomada** [comment]
It is included in SCA for RHEL9. We will review both RHEL9 and RHEL8 SCA for more testing, 
Closing this.
