### ISSUE TITLE
Active-response can not run for all agents

### ISSUE THREAD

**Issue by feitianxuxueyaya** [wazuh/wazuh#11376]
|Wazuh version|Component|
||V4.2.0|wazuh-api|
| X.Y.Z-rev | Wazuh component |

We use wazuh-api for active-response :
[https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.active_response_controller.run_command](url)
```xml
QUERY PARAMETERS:
agents_list: List of agent IDs (separated by comma), all agents selected by default if not specified
```
We use agents_list=001, it is ok, but we remove  agents_list parameter，it is error!!!
As shown below

```xml
curl -k -X PUT -d '{"command": "firewall-drop30", "alert":{"data":{"srcip":"1.1.1.5"}}}' -H 'Content-Type:application/json' 'https://127.0.0.1:55000/**active-response?agents_list=001**'  -H  "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM5NjQ2OTI5LCJleHAiOjE2Mzk2NDc4MjksInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.8_3kLFfoqFtHXZe26fdbYINQh3wIXCVudgWMfZesZoY" 
```
It is ok ,and response:
```xml
{
  "data": {
    "affected_items": [
      "001"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "AR command was sent to all agents",
  "error": 0
}
```
But when we want to for all agent:
```xml
curl -k -X PUT -d '{"command": "firewall-drop30", "alert":{"data":{"srcip":"1.1.1.5"}}}' -H 'Content-Type:application/json' 'https://127.0.0.1:55000**/active-response**'  -H  "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjM5NjQ2OTI5LCJleHAiOjE2Mzk2NDc4MjksInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.8_3kLFfoqFtHXZe26fdbYINQh3wIXCVudgWMfZesZoY" 
```
it is wrong, and response：
```xml
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 4000,
          "message": "Permission denied: Resource type: agent:id",
          "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.2/user-manual/api/rbac/configuration.html"
        },
        "id": [
          "*"
        ]
      }
    ]
  },
  "message": "AR command was not sent to any agent",
  "error": 1
}
```

**Comment by MiguelazoDS** [comment]
Hi @feitianxuxueyaya, 

What I can see is that you're lacking permission to achieve what you want. I tried myself in a dummy environment and the request is not denied with a 4000 error. 

I was thinking something like this.

![1](https://user-images.githubusercontent.com/13010397/146832911-95787088-2045-4d48-babd-f0b92590bc54.png)

I'm not restricting anything in my case. As you can see in the previous image, the action `active-response` is `allowed` in all the agents (resources).

Did you configure some policies in your environment that could be restricting the permissions on some resources or actions? 

All the information related to role-based control access can be found here. 

https://documentation.wazuh.com/current/user-manual/api/rbac/index.html

To be more clear, I think the issue you are experiencing is not related to active-response itself but to the permissions, you have set in your environment. 

Hope we can solve this. Regards!

**Comment by feitianxuxueyaya** [comment]
Hi @MiguelazoDS
Thank you for your reply,  if  I not restricting anything，the action active-response is allowed in all the agents (resources)。

Thanks again

**Comment by MiguelazoDS** [comment]
Hi @feitianxuxueyaya, 

Could you edit the file `/var/ossec/api/configuration/api.yaml` to add more verbosity to logs? 

Uncomment the logs block and change "info" by "debug2"
```yml
logs:
 level: "debug2"
 path: "logs/api.log"
```
Restart your manager and share the output of `/var/ossec/logs/api.log` when you run that command. 

Does this only fail when running without specifying the agents' IDs? 

I thinking if this could be related to a recent issue the API team published.

**Comment by matthew-williams** [comment]
It would be handy to note in documentation that you can no longer user agent_control to manually test active response, that its only possible via api calls now. Following this thread helped me realize that, but I cannot find it anywhere in the documentation.

**Comment by MiguelazoDS** [comment]
Hi matthew-williams, I completely miss this thread, could you provide me an example of what could you did before with agent_control and what it is not possible now?
