### ISSUE TITLE
Create a new backup mechanism for Wazuh-DB databases - Implementation

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#11389]
### Description 

As part of the changes introduced in the epic #10771, the agents' groups files will be migrated to **global.db**. Until now, this database could be safely removed because it was always recreated with information from other sources. But now it will be the only place where the groups assignation will be stored, so a configurable mechanism should be implemented to store this information regularly.

### Requirements

This implementation will be based in the final design described in https://github.com/wazuh/wazuh/issues/11317.

- [x] A new block of configurations should be added for this feature
- [x] A new set of commands for Wazuh-DB should be implemented to manage the database backup and restore 
- [x] The current `wdb_backup_global()` should be analyzed, to determine if it'll be still working the same way and with the same name

### Risks

It is important to analyze different use cases, for example database corruption, full disk, etc. 
Consider the case of restoring a backup DB.

### Testing required

- [x] The new command saves the database correctly 
- [x] The new command restores the selected DB
- [x] The max files setting work as expected
- [x] Wazuh-DB performs the backups according to the defined interval

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11451 was merged.
