### ISSUE TITLE
libstdc++ Centos8 dependency link no longer exists

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#11384]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | All | All | Sources | CentOS8 |

### Description

The libstdc++ package link specified in the INSTALL file no longer exists .
https://github.com/wazuh/wazuh/blob/f4ab39d1f70cd92f18606e229cbc90aec46aa39c/INSTALL#L68

It should be updated by the [8.5.0 version](http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-8.5.0-4.el8_5.x86_64.rpm)

**Comment by Dwordcito** [comment]
Fixed in: https://github.com/wazuh/wazuh-documentation/issues/4712
