### ISSUE TITLE
Review API configuration parameters to match the new standard in affected repositories

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11415]
# Description
### As a part of the epic issue wazuh/wazuh#11414, we should review and modify (if needed) every reference to the API configuration to match the new standard.

This issue will be used for tracking the related issues in other repositories:
* https://github.com/wazuh/wazuh-chef/issues/149
* https://github.com/wazuh/wazuh-ansible/issues/691
* https://github.com/wazuh/wazuh-puppet/issues/436
* https://github.com/wazuh/wazuh-qa/issues/2368

**Comment by davidjiglesias** [comment]
Already tracked in #11414
