### ISSUE TITLE
hostname command fail in OpenSUSE RPM installation

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#11433]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Manager/Agent | Install/Upgrade | OS version |

When installing in OpenSUSE Tumbleweed the installation returns the following error:
```
Additional rpm output:
warning: /var/cache/zypper/RPMS/wazuh-agent-4.3.0-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY
install: cannot create regular file '/etc/init.d/wazuh-agent': No such file or directory
./src/init/shared.sh: line 26: hostname: command not found
./src/init/shared.sh: line 26: hostname: command not found
```

We need to substitute the calls to `hostname` with other command like `uname -n` or `hostnamectl hostname`.

**Comment by fcaffieri** [comment]
### Update report

Investigating a little this error occurs in 2 points of the specs, where the call to `shared.sh` is made on tumbleweed OS:
```
# Generating ossec.conf file
  %{_localstatedir}/packages_files/manager_installation_scripts/gen_ossec.sh conf manager ${DIST_NAME} ${DIST_VER}.${DIST_SUBVER} %{_localstatedir} > %{_localstatedir}/etc/ossec.conf
```
```
# Add default local_files to ossec.conf
  %{_localstatedir}/packages_files/manager_installation_scripts/add_localfiles.sh %{_localstatedir} >> %{_localstatedir}/etc/ossec.conf
fi
```
So the change would be to modify the `hostname` command by `uname`, and test in which OS does not work:

/src/init/shared.sh
```HOST=`hostname` ``` 
to 
```HOST=`uname -n` ```
This will transfer to triage.
