### ISSUE TITLE
Replace the old update agent group method with the new set agent group implementation. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#11446]
**Description**

As part of the changes introduces in epic #10771, a new groups data synchronization mechanism should be implemented for the cluster as the `agent-group` files will no longer exist. For this task is required to replace the wdb_update_agent_group calls to update the group information with the new set group implementation from issue #11006 (wdb_set_agent_groups_csv).

**Requirements:**

- [X] Changes to call the new implementation. 

**Risks**

These changes shouldn't represent any risk, but it is required to verify that the information is written in the databases in a proper fashion. More test cases to cover a cluster environment should be performed after the sync implementation is done.

**Testing required**
- [X] lookfor_agent logic
  - [X] Verify that the information is properly set during the `shared_download` call using the new method.
  - [X] Verify that the information is properly set during the guess logic. 
- [X] Verify that the information is properly set during an agent registration with group information (`authd`).

**Comment by MiguelazoDS** [comment]
# Description:

The test cases mentioned in the issue were not performed due to changes in #10771. Specifically, as now the information is written into a database instead of files, the synchronization between nodes is not possible, ergo the group information is not sent from master to workers. 

A simpler case was done storing into the agent and belongs tables dummy group information as verifying it is not overridden by the guessing method.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11491 was merged.
