### ISSUE TITLE
Release 4.3.0 - Release Candidate 2 - System tests

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11466]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                  |                                                |
| -------------------------------- | ---------------------------------------------- |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/11463    |
| **Version**                      | 4.3.0                                          |
| **Release candidate #**          | RC2                                            |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.3.0-rc2 |
| **Previous system tests issue**  | https://github.com/wazuh/wazuh/issues/10960    |

## Test report procedure
All individual test checks must be marked as:
|       |                                                                                                      |
| ----- | ---------------------------------------------------------------------------------------------------- |
| Pass  | The test ran successfully.                                                                           |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue. |
| Skip  | The test was not run. It must be properly justified and reported in an issue.                        |
| Fail  | The test failed. A new issue must be opened to evaluate and address the problem.                     | 

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions
All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/11466#issuecomment-1000260390).

All tests have passed. I, therefore, conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [x] @davidjiglesias 
- [x] @AdriiiPRodri  
- [x] @vicferpoy

**Comment by Selutario** [comment]
## Test report
[System tests reports]](https://github.com/wazuh/wazuh/files/7769192/system_tests_reports.zip)

## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| test_cluster/test_agent_enrollment/test_agent_enrollment.py | 1 | 0 | 0 |  | :green_circle: |
| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py | 1 | 0 | 0 |  | :green_circle: |
| test_cluster/test_agent_info_sync/test_agent_info_sync.py | 2 | 0 | 0 |  | :green_circle: |
| test_cluster/test_agent_key_polling/test_agent_key_polling.py | 1 | 0 | 0 |  | :green_circle: |
| test_cluster/test_integrity_sync/test_integrity_sync.py | 4 | 0 | 0 |  | :green_circle: |
| test_jwt_invalidation/test_change_rbac_mode.py | 4 | 0 | 0 |  | :green_circle: |
| test_jwt_invalidation/test_change_security_resources.py | 4 | 0 | 0 |  | :green_circle: |
| test_jwt_invalidation/test_disconnected_nodes.py | 1 | 0 | 0 |  | :green_circle: |
| test_jwt_invalidation/test_revoke_endpoint.py | 6 | 0 | 0 |  | :green_circle: |
| test_jwt_invalidation/test_update_password.py | 4 | 0 | 0 |  | :green_circle: |

**Comment by yanazaeva** [comment]
## Issue update

This issue was reopened due to a problem found within the `agent_info_sync` system test, explained in the following [issue](https://github.com/wazuh/wazuh-qa/issues/2298). After the performed fixed, we run this test once again using the `v4.3.0-rc2` tag, obtaining the following results:

||Results|
|:--:|:--:|
|R1| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7780966/result1.zip) |
|R2| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7780970/result2.zip) |
|R3| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7780973/result3.zip) |
|R4| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7780976/result4.zip) |
|R5| [🟢 ](https://github.com/wazuh/wazuh-qa/files/7780978/result5.zip) |
