### ISSUE TITLE
Fix the allowance of binding a loopback IP in Cluster configuration

### ISSUE THREAD

**Issue by Kondent** [wazuh/wazuh#11476]
## Description
There's a bug regarding the possibility of binding a loopback IP different to `127.0.1.1` at Cluster configuration:

https://github.com/wazuh/wazuh/blob/f4ab39d1f70cd92f18606e229cbc90aec46aa39c/framework/wazuh/core/cluster/cluster.py#L55

This should be reviewed and fixed since the loopback IP block is `127.0.0.0/8`.

The current configuration is only reserving the IP `127.0.1.1` but the loopback IP block contains any IP in the range between `127.0.0.1` and `127.255.255.255`.
The cluster shouldn't be able to use any of these IP, otherwise it would be bound to `localhost`.

* Restarting wazuh master with `node` value set as `127.0.1.1`:
`wazuh-clusterd: Configuration error. Exiting`.

* Restarting wazuh master with `node` value set as `127.0.0.1`:
```
...
...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Started wazuh-clusterd...
Completed.
```

Regards

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh/11476?planning-poker) with ZenHub @AdriiiPRodri @Selutario @yanazaeva

**Comment by davidjiglesias** [comment]
Related and duplicated with #12828
