### ISSUE TITLE
Release 4.3.0 - Release Candidate RC2 - Footprint metrics

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#11483]
### Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |  #11463 |
| **Version** | 4.3.0                                    |
| **Release candidate #** | rc2                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.0-rc2                                       |
| **Previous footprint meetrics** | #11019 |

Jenkins build:

- 4h https://devel.ci.wazuh.info/job/Test_stress_tier/128
- 1d https://devel.ci.wazuh.info/job/Test_stress_tier/130/
- 2.5d https://devel.ci.wazuh.info/job/Test_stress_tier/129/ + https://devel.ci.wazuh.info/job/Test_stress/2357/

## Checks
Status | Result | Modules | 4.3.0 Issue (4h) | 4.3.0 Issue (1d) | 4.3.0 Issue (2.5d)  |
|-- | -- | -- | -- | -- | -- | 
| ⚫ | ⚠️ | All [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11629 | #11667 | #11691 | 
| ⚫ | ⚠️ | Vulnerability-Detector [**](https://github.com/wazuh/wazuh/issues/11773) | #11619 | #11661 | #11679 |
| ⚫ | ⚠️ | Vulnerability-Detector-Register  [**](https://github.com/wazuh/wazuh/issues/11773)| #11636 | #11656 | #11684 | 
| ⚫ | ✔️ | Logcollector | #11623 | #11654 | #11690  | 
| ⚫ | ⚠️ | Syscheck [*](https://github.com/wazuh/wazuh/pull/11735) | #11639 | #11653 | #11689 | 
| ⚫ | ✔️ | Rootcheck | #11632 | #11660 | #11692  | 
| ⚫ | ✔️ | SCA | #11625 | #11670 | #11688  | 
| ⚫ | ✔️ | Active-Response | #11628 | #11659 | #11687  | 
| ⚫ | ✔️ | Syscollector | #11630 | #11655 | #11677  | 
| ⚫ | ⚠️ | Azure-logs,CIS-Cat,Osquery,Docker-listener,OpenSCAP | #11626 | #11657 | #11693  | 
| ⚫ | ⚠️ | All-except Logcollector [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11621 | #11671 | #11686 | 
| ⚫ | ⚠️ | All-except Rootcheck [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11637 | #11663  | #11682 |  
| ⚫ | ⚠️ | All-except SCA [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11633 | #11672 | #11683 | 
| ⚫ | ⚠️ | All-except Syscheck [**](https://github.com/wazuh/wazuh/issues/11773) | #11624 |  #11662 | #11675 |  
| ⚫ | ⚠️ | All-except Active-Response [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11638 | #11666  | #11685 | 
| ⚫ | ⚠️ | All-except Syscollector [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11631 | #11664  | #11681 | 
| ⚫ | ⚠️ | All-Except Azure-logs,CIS-Cat,Osquery,Docker-listener,OpenSCAP [*](https://github.com/wazuh/wazuh/pull/11735) [**](https://github.com/wazuh/wazuh/issues/11773) | #11634 | #11668  | #11695 |
| ⚫ | ⚠️ | All-except Vulnerability-Detector [*](https://github.com/wazuh/wazuh/pull/11735) | #11627 |  #11665 | #11694 |
| ⚫ | ✔️ | Logcollector,Syscollector | #11620 | #11658 | #11678 | 
| ⚫ | ✔️ | Logcollector,SCA | #11622 |  #11673 | #11680 | 
| ⚫ | ✔️ | Logcollector,Syscheck | #11635 | #11669 | #11676 |
| ⚫ | ⚫ | macOS-All | --- |  --- | --- | 
| ⚫ | ⚫ | Solaris-All | --- |  --- | --- | 

Result legend:
⚫ - Not launched
🕐 - Pending/In progress
✔️ - Results Ready
⚠️ - Review required

Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

## Auditors validation

In order to close and proceed with release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @santiago-bassett 
- [ ] @alberpilot 
- [ ] @okynos 
- [ ] @rauldpm

**Comment by fcaffieri** [comment]
###Syscheck 4h
[jenkins](https://devel.ci.wazuh.info/job/Test_stress/1577)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to EC2 (JenkinsCloud) - AL2_v11.4_OnDemand (i-0a65fa39109d38b1f)

**Comment by fcaffieri** [comment]
### All-except-SCA
[jenkins](https://devel.ci.wazuh.info/job/Test_stress/1586/console)
```
20:01:12  Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
20:01:12  
20:01:12  
20:01:12  Releasing state lock. This may take a few moments...
20:01:12  
20:01:12  Error: timeout while waiting for plugin to start
```

**Comment by fcaffieri** [comment]
### All-except-Active Response 4h
[jenkins](https://devel.ci.wazuh.info/job/Test_stress/1587/console)
```
20:01:05  Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
20:01:05  
20:01:05  
20:01:05  Releasing state lock. This may take a few moments...
20:01:07  aws_instance.instance[0]: Still destroying... [id=i-0fd4758c258262d21, 1m2s elapsed]
20:01:07  aws_instance.instance[0]: Still destroying... [id=i-0fd4758c258262d21, 1m12s elapsed]
20:01:12  
20:01:12  Error: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: context deadline exceeded"
```

**Comment by rauldpm** [comment]
### Analysis report

- 4h issues closed. They do not show a worse behavior than the 2.5d tests
