### ISSUE TITLE
vulnerability detector  (3.5) not looking for all packages (debian8)

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh#1150]
Hi,

I'm currently trying to compare vulnerability detector (3.5) vs openvas reports,
I have matching openvas security cve not displayed in wazuh.

agent is on a debian jessie, with this packages
https://gist.github.com/aderumier/727b5243e010edcf195e0100da604c34

openvas report cve on some packages
for example :  icu,isc-dhcp,bind9,gcc-4.9, linux,procps,perl,net-snmp

looking at vulnerability detector logs, I don't see theses packages checked.

https://gist.github.com/aderumier/b37a42f62ff48ce4eb094a5b06958424

**Comment by aderumier** [comment]
@crolopez 
thanks to review this.  If needed, I can help for debug/tests.

**Comment by crolopez** [comment]
Hi @aderumier,

Thanks but no need, we have reproduced your case and we are already working to include the solution ASAP. We'll let you know when it's ready. 

Thank you for reporting it.

Best regards.

**Comment by crolopez** [comment]
Hi @aderumie,

The bug that didn't check all packages for debian has been fixed https://github.com/wazuh/wazuh/pull/1166. It will be included in Wazuh 3.6, which will be launched in the next few days.

Let me close the issue.

Best regards.
