### ISSUE TITLE
Wazuh Sysmon rules

### ISSUE THREAD

**Issue by tarekkilani** [wazuh/wazuh#11517]
Hello, 

Please i would like to know if there is any rule files to implement with sysmon to get windows logs information.
I think the file provided here is not enough (https://wazuh.com/blog/using-wazuh-to-monitor-sysmon-events/) 
I tried this project (https://github.com/sametsazak/sysmon) and i want to know if there is any other projects.
I want to detect IOCs like the execution of powershell scripts, the chnage of a user password, the creation of a new user local account ...
I also tried this project (https://github.com/SanWieb/sigWah) but i get errors when i try to install sysmon using the config file provided in the project and error 3013 when trying to save the rules file in wazuh manager.

Thanks in advance.

**Comment by FrancoRivero** [comment]
Hi @tarekkilani,
Thank you for using Wazuh.
This document is a bit old, maybe your needs are covered in the new features. You can check [this document](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html). If you have other needs we can add it like a new feature. In that case, we should add a new issue with your needs however maybe we can solve the problem.
Regards

**Comment by tarekkilani** [comment]
Hello @FrancoRivero 
In the document you provided there is a link talking about sysmon.
Do i need sysmon with wazuh agent to collect windows logs or not ?

**Comment by tarekkilani** [comment]
Hi @FrancoRivero 

I read the document you provided, i understood that sysmon is one of many things that we can activate to monitor windows logs. Is that correct?

I mean, can we put this configuration in our agent.conf to monitor several things?

```
<localfile>
    <location>Application</location>
    <location>Security</location>
    <location>System</location>
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```

Is the syntax correct?

Or is it like this?

```
<localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
</localfile>

<localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
</localfile>

<localfile>
    <location>System</location>
    <log_format>eventchannel</log_format>
</localfile>

<localfile>
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```

**Comment by FrancoRivero** [comment]
Hi @tarekkilani,
You could monitor different sources so if you want to detect threat, for instance, you should configure [Sysmon event collection](https://wazuh.com/blog/learn-to-detect-threats-on-windows-by-monitoring-sysmon-events/) . That depends of what you want to do. Regarding the configuration, the second way is the correct way to activate monitoring on those sources.
Regards

**Comment by tarekkilani** [comment]
Hi, @FrancoRivero 

According to the links you provided there is some predefined rules in Wazuh.

```
Base rules | 60000 - 60099 | 0575-win-base_rules.xml
Security | 60100 - 60599 | 0580-win-security_rules.xml
Application | 60600 - 61099 | 0585-win-application_rules.xml
System | 61100 - 61599 | 0590-win-system_rules.xml
Sysmon | 61600 - 62099 | 0595-win-sysmon_rules.xml
```

I don't know why Sysmon rules don't work unless i define a new SymonRules.xml file like this one : https://github.com/OpenSecureCo/Wazuh/blob/main/sysmon.xml

Are predefined rules activated in wazuh? or i should activate them manually ? if yes, how can i do that?
For example, there is some Sophos-XG firewall predefined rules in `0705-sophos_fw_rules.xml` file. If i forward syslog events of a Sophos-XG firewall to Wazuh manager on port 1515, will be any triggered alerts if i send an event that maches a rule in the `0705-sophos_fw_rules.xml` file ?

**Comment by FrancoRivero** [comment]
Hi @tarekkilani, 
we have [predefined rules](https://github.com/wazuh/wazuh/tree/4.2/ruleset/rules), you should active the alerts necessaries for your case [AR](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/index.html), if you want to add a new rule, you should add the rule and a decoder to generate an alert [see this document](https://documentation.wazuh.com/current/learning-wazuh/replace-stock-rule.html). [Here you will have more information about ruleset](https://documentation.wazuh.com/current/user-manual/ruleset/index.html).
Hope this can help you.
Regards

**Comment by tarekkilani** [comment]
Hi @FrancoRivero 
I'll check the documents and let you know the results, thanks.
One more question, whats the difference between `0330-sysmon_rules.xml` and `0595-win-sysmon_rules.xml` ?

**Comment by FrancoRivero** [comment]
Hi @tarekkilani 
For the first question, the answer is the difference is the place where find the information in the case 0330-sysmon_rules.xml you find the information from Windows Event Log, for other side in the 0595-win-sysmon_rules.xml take the information from Windows Event Channel. You could check this information [here](https://github.com/wazuh/wazuh/blob/4.2/ruleset/decoders/0380-windows_decoders.xml) this is a decoder which matching those rules. 
You should create a new rule and decoder for the case sophos firewall, if you have configured this alert, this should raise an alert when it be generated on port 1515. If you follow t[hese steps ](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html) you would have the alerts when sophos firewall achieve a rule. 
Regards

**Comment by tarekkilani** [comment]
Hi @FrancoRivero 
Can you please explain how to activate a ruleset?
I mean if i want to activate sophos firewall rules or any other ruleset how do i proceed ? should i copy the decoder file in the custom decoders folder and the rules file in the  custom rules folder then forward logs to wazuh manager port 1515? 
is there any documentation for that ?

**Comment by tarekkilani** [comment]
I just followed this document to forward sophos logs to wazuh manager : 

https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

**Comment by tarekkilani** [comment]
I just followed these documents to forward sophos XG logs to wazuh manager but it's not working : 

https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
https://documentation.wazuh.com/current/learning-wazuh/replace-stock-rule.html

I did a copy of the sophos firewall decoder file in the custom decoders folder as you can see here

![image](https://user-images.githubusercontent.com/36234835/147735320-ca126c74-9746-4e7e-a7a4-be8adf640ce5.png)

Then i created a new custom rules file in which i put a copy of the sophos XG predefined rules. (i put the overwrite="yes" to every rule) but it's not working.

Also, logs are sent to wazuh manager successfuly on port 1515 as you can see here 

![image](https://user-images.githubusercontent.com/36234835/147735467-d3a8410b-8e83-478c-8d2f-54e4a91c02ba.png)

Why can't i see any event related to sophos XG firewall ?

![image](https://user-images.githubusercontent.com/36234835/147735635-d9ab7a42-2fb1-41e1-a623-06f4ca6a0437.png)

**Comment by tarekkilani** [comment]
problem solved by adding this code to ossec.conf file of the manager

```
  <remote>
    <connection>syslog</connection>
    <port>1514</port>
    <protocol>UDP</protocol>
    <allowed-ips>subnet/24</allowed-ips>
  </remote>
```
