### ISSUE TITLE
 Error. 3013 - Maximum attempts exceeded for sqlite3 execute: database is locked

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#1152]
Received the following error in the Kibana Wazuh interface: "Overview. Error. 3013 - Maximum attempts exceeded for sqlite3 execute: database is locked"

**Comment by JuanjiJG** [comment]
Hello @alphaDev23,

What is your current Wazuh manager version? In which Wazuh app section did you exactly get that error message?

Let's try something to see if we can fix this. Restart your manager with the following command:
```
systemctl restart wazuh-manager
```
This way, the database will be restarted and all the possible executions will be stopped. Now, we're going to execute an API request to see if it's capable of returning the list of agents:
```
curl -u <API_USER>:<API_PASSWORD> http(s)://<API_URL>:55000/agents?pretty
```
Let me know if you get a proper response from the API (that is, the list of agents).

Thanks for your patience.

Regards,
Juanjo

**Comment by alphaDev23** [comment]
Agents are returned (via curl) after restarting the manager except that this error is re-occuring.  Running in docker.  Not sure if this helps explain the cause.

**Comment by JuanjiJG** [comment]
Hello again @alphaDev23,

In which app section do you get that error message?

Try the following steps on the machine where Wazuh manager is installed:
```
rm -rf /var/ossec/var/db/global.db*
/var/ossec/bin/ossec-control restart
```

This will erase your databases and restart your manager. Don't worry, the databases will be regenerated again.

Let us know if this helps.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @alphaDev23,

It's been more than a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you have problems or questions about Wazuh.

Regards,
Juanjo
