### ISSUE TITLE
Wazuh-db periodic stop

### ISSUE THREAD

**Issue by hantiger** [wazuh/wazuh#11539]
|Wazuh version|Install according to official documentation|Install method|Platform|
|-|-|-|-|-|
|4.2.1|almost all|Manager|Install using the package manager according to the official documentation|ubuntu 18.04

An error occured when the manager running, refer to the ossec.log it seems that the file /queue/db/wdb can not be approached, and then many agents were marked as disconnected. we have nearly 1000+ agents for per manager , so does it due to performance reason or any other?

hope for reply, thanks

Every time the service runs for a period of time, wazuh DB service will stop. Check that the disk space is normal and find out where the problem is. I hope you can help check it. The following is a screenshot of error reporting.
![image](https://user-images.githubusercontent.com/63154152/147429521-5c007de6-1d05-4a7d-9008-00f9d71054f4.png)

this is the ossec.log info:

```
2021/12/27 00:00:12 wazuh-analysisd: ERROR: Error querying Wazuh DB to get the agent's 187945 labels.
2021/12/27 00:00:12 wazuh-analysisd: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
2021/12/27 00:00:13 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 3 seconds to reconnect.
2021/12/27 00:00:13 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 3 seconds to reconnect.
2021/12/27 00:00:13 wazuh-analysisd: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 2 seconds to reconnect.
2021/12/27 00:00:14 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 3 seconds to reconnect.
2021/12/27 00:00:14 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:14 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:14 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
2021/12/27 00:00:15 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 2 seconds to reconnect.
2021/12/27 00:00:15 wazuh-analysisd: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 3 seconds to reconnect.
2021/12/27 00:00:16 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:16 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:16 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
2021/12/27 00:00:16 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:16 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:16 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
2021/12/27 00:00:17 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:17 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:17 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
2021/12/27 00:00:17 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 3 seconds to reconnect.
2021/12/27 00:00:17 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 2 seconds to reconnect.
2021/12/27 00:00:17 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 2 seconds to reconnect.
2021/12/27 00:00:18 wazuh-remoted: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 2 seconds to reconnect.
2021/12/27 00:00:18 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:18 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2021/12/27 00:00:18 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'
2021/12/27 00:00:18 wazuh-analysisd: ERROR: Error querying Wazuh DB to get the agent's 187659 labels.
2021/12/27 00:00:18 wazuh-analysisd: INFO: Cannot connect to 'queue/db/wdb': Connection refused (111). Waiting 1 seconds to reconnect.
```

this is wazuh-db status

```
root@k8s-2:/var/ossec/bin# ./wazuh-control status
wazuh-clusterd is running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db not running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```

**Comment by DProvinciani** [comment]
Hi @hantiger ! Thanks for using Wazuh!

Let's do some troubleshooting to identify what could be happening here. First of all, I would like to check the permissions and owners of some files. The users that are running the daemons would be interesting as well. So, could you share with me the output of the next three commands?

```
ls -las /var/ossec/bin/
ls -las /var/ossec/queue/db/
ps aux | grep wazuh
```

On the other hand, could you share with me the logs of the manager in which the wazuh-db daemon stop running? This would allow me to identify which is the action being done by the manager right at the moment in which wazuh-db gets stopped. (please, remove any sensitive information)
If the daemon doesn't take much time to get stopped, probably would be interesting to run it with the next command:

```
/var/ossec/bin/wazuh-db -fdd
```

Another question is. Is this happening in any of the nodes of your Wazuh cluster? or it is always happening in a particular node?

Finally, it would be good to check in the file `/var/logs/messages` whether the daemon is crashing with a segmentation fault or something like that.

Please, check these things and share with me as many details as possible. I'll be waiting for your comments.

**Comment by hantiger** [comment]
Thank you for your reply.

This is the result of three commands：
[wazuh_result.txt](https://github.com/wazuh/wazuh/files/7786820/wazuh_result.txt)

**Comment by DProvinciani** [comment]
Hi @hantiger! Thanks for sharing all this information with me. Let's see item by item.

- The file permissions for both, the binaries and the sockets seems to be ok.
- All the processes seem to be executed by the right user.
- There is a key point in the logs, basically the line `wazuh-db: CRITICAL: At pthread_mutex_lock(): Invalid argument`

Some months ago we discovered and fixed some potential race conditions in the Wazuh DB module. Basically, in this modules we have threads that interact with the databases and some others responsible of finally committing the data on disk.
The race conditions reported some situations in which we could be operating in a bad way with the mutex that prevent concurrent access. You can find more details here: https://github.com/wazuh/wazuh/issues/8146.

The fix for these race conditions was released on Wazuh `4.2` so, my suggestion is to perform an upgrade in your environment because the Wazuh DB module gets stopped right in the moment when it tries to lock a mutex.

For details on how to perform an upgrade, you can find details in our documentation here: https://documentation.wazuh.com/current/upgrade-guide/index.html

I hope this could be useful for you.

**Comment by hantiger** [comment]
@DProvinciani Thank you for your assistance.
I will operate according to your suggestions. After the operation, I will observe for a period of time. Thank you.

**Comment by DProvinciani** [comment]
As the issue seem not to be happening anymore, we close this issue.
