### ISSUE TITLE
 Release 4.3.0 - Release Candidate 2 - Unit tests 

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#11565]
|Main RC issue|Version|RC|Tag|Previous issue|
|---|---|---|---|---|
|#11463|4.3.0|2|[v4.3.0-rc2](https://github.com/wazuh/wazuh/releases/tag/v4.3.0-rc2)|#11020|

This issue aims to run all `C unit tests` for the current RC and report the results. Any failing test should be properly addressed with a new issue, detailing the error and the possible cause. Then, it will be determined if that fails is to be fixed immediately or marked as expected-fail if there is enough support and approval for it. In case a test is marked as expected-fail, the issue detailing the error should always be used as a reference in the test.

## Auditors validation

In order to close and proceed with release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @santiago-bassett 
- [ ] @vikman90

**Comment by MarcelKemp** [comment]
## Rsync

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|:green_circle:|
|rsync_unit_test|:green_circle:|
|rsync_implementation_unit_test|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|100.0%|:green_circle:|
|Functions|100.0%|:green_circle:|

## Syscollector

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|:green_circle:|
|syscollectorimp_unit_test|:green_circle:|
|sys_normalizer_unit_test|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|100.0%|:green_circle:|
|Functions|100.0%|:green_circle:|

## Utilities

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|:green_circle:|
|utils_unit_test|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|99.2%|:green_circle:|
|Functions|95.5%|:green_circle:|

## DBsync

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|:green_circle:|
|sqlite_unit_test|:green_circle:|
|dbsyncPipelineFactory_unit_test|:green_circle:|
|dbsync_unit_test|:green_circle:|
|fim_integration_test|:green_circle:|
|dbengine_unit_test|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|93.5%|:green_circle:|
|Functions|96.7%|:green_circle:|

## Data provider

### Tests

|Test|Status|
|---|:-:|
|Cppcheck|:green_circle:|
|sysInfoPackagesBerkeleyDB_unit_test|:green_circle:|
|sysInfoPort_unit_test|:green_circle:|
|sysInfoNetworkLinux_unit_test|:green_circle:|
|sysinfo_unit_test|:green_circle:|
|sysInfoPackagesLinuxHelper_unit_test|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|100.0%|:green_circle:|
|Functions|100.0%|:green_circle:|

## Windows agent unit tests

### Tests

|Test|Status|
|---|:-:|
|test_syscom|:green_circle:|
|test_fim_diff_changes|:green_circle:|
|test_run_realtime|:green_circle:|
|test_syscheck_config|:green_circle:|
|test_syscheck|:green_circle:|
|test_fim_sync|:green_circle:|
|test_run_check|:green_circle:|
|test_run_realtime_event|:green_circle:|
|test_run_check_event|:green_circle:|
|test_registry|:green_circle:|
|test_events|:green_circle:|
|test_fim_db|:green_circle:|
|test_fim_db_files|:green_circle:|
|test_fim_db_registries|:green_circle:|
|test_win_whodata|:green_circle:|
|test_list_op|:green_circle:|
|test_file_op|:green_circle:|
|test_integrity_op|:green_circle:|
|test_rbtree_op|:green_circle:|
|test_validate_op|:green_circle:|
|test_string_op|:green_circle:|
|test_expression|:green_circle:|
|test_version_op|:green_circle:|
|test_queue_op|:green_circle:|
|test_queue_linked_op|:green_circle:|
|test_agent_op|:green_circle:|
|test_enrollment_op|:green_circle:|
|test_time_op|:green_circle:|
|test_buffer_op|:green_circle:|
|test_utf8_op|:green_circle:|
|test_log_builder|:green_circle:|
|test_custom_output_search_replace|:green_circle:|
|test_syscheck_op|:green_circle:|
|test_atomic|:green_circle:|
|test_url|:green_circle:|
|test_sysinfo_utils|:green_circle:|
|test_os_xml|:green_circle:|
|test_os_regex|:green_circle:|
|test_os_zlib|:green_circle:|

## Linux Manager unit tests

### Tests

|Test|Status|
|---|:-:|
|test_file_op|:green_circle:|
|test_integrity_op|:green_circle:|
|test_rbtree_op|:green_circle:|
|test_validate_op|:green_circle:|
|test_string_op|:green_circle:|
|test_expression|:green_circle:|
|test_version_op|:green_circle:|
|test_queue_op|:green_circle:|
|test_queue_linked_op|:green_circle:|
|test_agent_op|:green_circle:|
|test_set_agent_group|:green_circle:|
|test_enrollment_op|:green_circle:|
|test_time_op|:green_circle:|
|test_buffer_op|:green_circle:|
|test_utf8_op|:green_circle:|
|test_log_builder|:green_circle:|
|test_custom_output_search_replace|:green_circle:|
|test_bzip2_op|:green_circle:|
|test_schedule_scan|:green_circle:|
|test_rootcheck_op|:green_circle:|
|test_fs_op|:green_circle:|
|test_wazuhdb_op|:green_circle:|
|test_syscheck_op|:green_circle:|
|test_audit_op|:green_circle:|
|test_privsep_op|:green_circle:|
|test_mq_op|:green_circle:|
|test_remoted_op|:green_circle:|
|test_json-queue|:green_circle:|
|test_bqueue|:green_circle:|
|test_atomic|:green_circle:|
|test_url|:green_circle:|
|test_sysinfo_utils|:green_circle:|
|test_os_xml|:green_circle:|
|test_os_regex|:green_circle:|
|test_os_zlib|:green_circle:|
|test_os_net|:green_circle:|
|test_fluentd_forwarder|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|31.8%|27829 of 87595 lines|
|Functions|7.2%|1303 of 18157 functions|
|Branches|20.8%|23202 of 111491 branches|

## Linux agent unit tests

### Tests

|Test|Status|
|---|:-:|
|test_macos_log|:green_circle:|
|test_read_macos|:green_circle:|
|test_execd|:green_circle:|
|test_wm_github|:green_circle:|
|test_wm_office365|:green_circle:|
|test_create_db|:green_circle:|
|test_syscom|:green_circle:|
|test_fim_diff_changes|:green_circle:|
|test_run_realtime|:green_circle:|
|test_syscheck_config|:green_circle:|
|test_syscheck|:green_circle:|
|test_fim_sync|:green_circle:|
|test_run_check|:green_circle:|
|test_fim_db|:green_circle:|
|test_fim_db_files|:green_circle:|
|test_audit_healthcheck|:green_circle:|
|test_audit_rule_handling|:green_circle:|
|test_syscheck_audit|:green_circle:|
|test_audit_parse|:green_circle:|
|test_list_op|:green_circle:|
|test_file_op|:green_circle:|
|test_integrity_op|:green_circle:|
|test_rbtree_op|:green_circle:|
|test_validate_op|:green_circle:|
|test_string_op|:green_circle:|
|test_expression|:green_circle:|
|test_version_op|:green_circle:|
|test_queue_op|:green_circle:|
|test_queue_linked_op|:green_circle:|
|test_agent_op|:green_circle:|
|test_enrollment_op|:green_circle:|
|test_time_op|:green_circle:|
|test_buffer_op|:green_circle:|
|test_utf8_op|:green_circle:|
|test_log_builder|:green_circle:|
|test_custom_output_search_replace|:green_circle:|
|test_syscheck_op|:green_circle:|
|test_audit_op|:green_circle:|
|test_privsep_op|:green_circle:|
|test_mq_op|:green_circle:|
|test_remoted_op|:green_circle:|
|test_atomic|:green_circle:|
|test_url|:green_circle:|
|test_sysinfo_utils|:green_circle:|
|test_os_xml|:green_circle:|
|test_os_regex|:green_circle:|
|test_os_zlib|:green_circle:|
|test_os_net|:green_circle:|
|test_fluentd_forwarder|:green_circle:|

### Coverage

|Coverage type|Percentage|Result|
|---|---|---|
|Lines|21.7%|11646 of 53682 lines|
|Functions|3.7%|634 of 17127 functions|
|Branches|13.7%|9233 of 67579 branches|
