### ISSUE TITLE
Release 4.3.0 - Release Candidate 2 - WPK upgrade

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#11569]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     | https://github.com/wazuh/wazuh/issues/11463                                          |
| **Version**                          | 4.3.0                                           |
| **Release candidate #**              | RC2                                            |
| **Tag**                              | https://github.com/wazuh/wazuh/tree/v4.3.0-rc2                                       |
| **Previous WPK upgrade tests issue** | #11152                                           |

## Tests

To evaluate this feature, it is necessary to test upgrading the agent and also the case when the upgrade fails (rollback). The `tree` command will be used to compare, before and after the upgrade/rollback process, and check that the presence, ownership and permissions of the files and directories are the expected.

Wazuh versions to test (upgrading to 4.3.0):

- 3.13
- 4.0
- 4.1.5
- 4.2.1

Operating Systems to test:

- Linux
  - [Amazon 2]()
  - [CentOS 6]()
  - [CentOS 8]()
  - [Ubuntu 20]()
  - [openSUSE Tumbleweed]()

- Windows
  - [Server 2008 R2]()
  - [Server 2012 R2]()
  - [Server 2016]()
  - [Server 2019]()
  - [Windows 10]()
  - [Server 2022]()
  
  
## Conclusions
The results of the tests are shown in the table below:
 
 ### Linux 

|OS|Version|Upgrade fail|Upgrade OK|
|----|-----------|---------------|------------------|
|Amazon 2|3.13| :white_circle: | :white_circle: |
|Amazon 2|4.0.4| :white_circle: | :white_circle: |
|Amazon 2|4.1.5| :white_circle: | :white_circle: |
|Amazon 2|4.2.5| :white_circle: | :white_circle: |
|Amazon 2|4.3.0| :white_circle: | :white_circle: |
|CentOS 6|3.13| :white_circle: | :white_circle: |
|CentOS 6|4.0.4| :white_circle: | :white_circle: |
|CentOS 6|4.1.5| :white_circle: | :white_circle: |
|CentOS 6|4.2.5| :white_circle: | :white_circle: |
|CentOS 6|4.3| :white_circle: | :white_circle: |
|CentOS 8|3.13| :white_circle: | :white_circle: |
|CentOS 8|4.0| :white_circle: | :white_circle: |
|CentOS 8|4.1.5| :white_circle: | :white_circle: |
|CentOS 8|4.2.5| :white_circle: | :white_circle: |
|CentOS 8|4.3| :white_circle: | :white_circle: |
|Ubuntu 20|3.13| :white_circle: | :white_circle: |
|Ubuntu 20|4.0| :white_circle: | :white_circle: |
|Ubuntu 20|4.1.5| :white_circle: | :white_circle: |
|Ubuntu 20|4.2.5| :white_circle: | :white_circle: |
|Ubuntu 20|4.3 | :white_circle: | :white_circle: |
|openSUSE Tumbleweed|3.13|:white_circle: |:white_circle: |
|openSUSE Tumbleweed|4.0|:white_circle: |:white_circle: |
|openSUSE Tumbleweed|4.1.5|:white_circle: |:white_circle: |
|openSUSE Tumbleweed|4.2.5|:white_circle: |:white_circle: |
|openSUSE Tumbleweed|4.3|:white_circle: |:white_circle: |

### Windows
|OS|Version|Upgrade fail|Upgrade OK|
|----|-----------|---------------|------------------|
|Windows Server 2012 R2|3.5| :white_circle: | :white_circle: |
|Windows Server 2012 R2|3.13| :white_circle: | :white_circle: |
|Windows Server 2012 R2|4.0| :white_circle: | :white_circle: |
|Windows Server 2012 R2|4.1.0| :white_circle: | :white_circle: |
|Windows Server 2012 R2|4.1.5| :white_circle: | :white_circle: |
|Windows Server 2012 R2|4.2.5| :white_circle: | :white_circle: |
|Windows Server 2012 R2|4.3.0| :white_circle: | :white_circle: |
|Windows Server 2016|3.5| :white_circle: | :white_circle: |
|Windows Server 2016|3.13| :white_circle: | :white_circle: |
|Windows Server 2016|4.0.4| :white_circle: | :white_circle: |
|Windows Server 2016|4.1.5| :white_circle: | :white_circle: |
|Windows Server 2016|4.2.5| :white_circle: | :white_circle: |
|Windows Server 2016|4.3.0| [:red_circle:](https://github.com/wazuh/wazuh/issues/11257) | :white_circle: |
|Windows Server 2019|3.5.0|:white_circle: |:white_circle: |
|Windows Server 2019|3.13|:white_circle: |:white_circle: |
|Windows Server 2019|4.0|:white_circle: |:white_circle: |
|Windows Server 2019|4.1.5|:white_circle: |:white_circle: |
|Windows Server 2019|4.2.5|:white_circle: |:white_circle: |
|Windows Server 2019|4.3.0|:white_circle: |:white_circle: |
|Windows 10|3.5| :white_circle: | :white_circle: |
|Windows 10|3.13| :white_circle: | :white_circle: |
|Windows 10|4.0.4| :white_circle: | :white_circle: |
|Windows 10|4.1.5| :white_circle: | :white_circle: |
|Windows 10|4.2.5| :white_circle: | :white_circle: |
|Windows 10|4.3.0| :white_circle: | :white_circle: |
|Windows Server 2022|3.5|:white_circle: |:white_circle: |
|Windows Server 2022|3.13|:white_circle: |:white_circle: |
|Windows Server 2022|4.0.4|:white_circle: |:white_circle: |
|Windows Server 2022|4.1.5|:white_circle: |:white_circle: |
|Windows Server 2022|4.2.5|:white_circle: |:white_circle: |
|Windows Server 2022|4.3.0|:white_circle: |:white_circle: |
|Windows Server 2008|3.5|:white_circle: |:white_circle: |
|Windows Server 2008|3.13|:white_circle: |:white_circle: |
|Windows Server 2008|4.0|:white_circle: |:white_circle: |
|Windows Server 2008|4.1.5|:white_circle: |:white_circle: |
|Windows Server 2008|4.2.5|:white_circle: |:white_circle: |
|Windows Server 2008|4.3.0|:white_circle: |:white_circle: |

## Issues reported

- #11257 

## Auditors validation

In order to close and proceed with release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @santiago-bassett 
- [ ] @vikman90 
- [ ] @alberpilot

**Comment by davidjiglesias** [comment]
Skipped for rc2
