### ISSUE TITLE
Librpm integration - exploratory session.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#11572]
## Description
The objective of this exploratory session is to run a functional tests and E2E of the product that impact on the performance of the collection, synchronization, and use by the vulnerability detector of this information.

## OS
- openSuse Tumbleweed -> NDB -> @jnasselle 
- Fedora 34 -> NDB -> @Dwordcito 
- Centos 8 Stream -> BDB @RamiroRD 
- Centos 8 -> BDB -> @HanesSciarrone 
- Centos 5 -> BDB -> @Dwordcito 
- Amazon Linux 2 -> BDB -> @RamiroRD 

## Tests
- Search for the NO existence of exceptions in ossec.log
- Compare inventory from syscollector (Manager) VS output of RPM, row count, sampling. https://github.com/wazuh/wazuh/issues/11575
- Set an environment variable to test for fallback. RPM_CONFIGDIR
- Verify operation of vulnerability detector.

## Packages

https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit5d4e7c0.el5.i386.rpm
https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit5d4e7c0.el5.x86_64.rpm
https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit5d4e7c0.i386.rpm
https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-agent-4.4.0-0.commit5d4e7c0.x86_64.rpm
https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit5d4e7c0.x86_64.rpm

**Comment by RamiroRD** [comment]
**CentOS 8 Stream**
(Will update as testing progresses)
Installation using provided RPM on CentOS 8 Stream produces the following output:
```
[root@centos-8-stream-agent vagrant]# rpm -i rpm.rpm 
sed: can't read ERROR_PARAM: No such file or directory
sed: can't read ERROR_PARAM: No such file or directory
sed: can't read ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
cat: ERROR_PARAM: No such file or directory
```
and then succeeds.

**Comment by RamiroRD** [comment]
**Amazon Linux 2**
Installation worked normally.
I registered the agent and saw that the output of `rpm -qa` has 438 lines while the Wazuh UI shows 437 packages, this is expected: we purposely don't report `gpg-pubkey` as being installed.
![Screen Shot 2022-01-04 at 13 19 44](https://user-images.githubusercontent.com/6182640/148090069-538a5083-01da-4a40-9fb8-b00fd0021800.png)
![image](https://user-images.githubusercontent.com/6182640/148090203-e80826e1-1af9-4740-9219-70c14bd20de2.png)
`gpg-pubkey` missing as expected:
![image](https://user-images.githubusercontent.com/6182640/148090985-cd7fc0d9-de15-4932-8992-ed0f4b347fed.png)

**Comment by HanesSciarrone** [comment]
CentOS 8

- The installation and synchronization of the manager and agent were successful without any output error.

Manager

![image](https://user-images.githubusercontent.com/58960358/148116492-000185e4-1fd6-40cc-a0ed-8a96fffaf960.png)


Agent

![image](https://user-images.githubusercontent.com/58960358/148116552-5d9b00bb-0bd9-4e50-87f1-8165458a912a.png)


- Inside of `ossec.log` wasn't found any error related to syscollector or wazuh-db 

On the agent side.

![image](https://user-images.githubusercontent.com/58960358/148112603-fca7874c-d4e8-41aa-aecf-5bbf7c65b4ec.png)

On the manager side 

![image](https://user-images.githubusercontent.com/58960358/148114544-e90aee0c-cbeb-47d1-902a-f1d305086b94.png)
 
 - Comparing the data between the manager database and the RPM command, no errors were found. The number of packages in the database and the list of packages in the output RPM command differs by only one package, but this is expected. 

On the agent side 

![image](https://user-images.githubusercontent.com/58960358/148115976-463aa02b-a117-4344-a67b-dee810379c38.png)

On the manager side 

![image](https://user-images.githubusercontent.com/58960358/148116143-bd65b65c-52a2-4735-8363-1479b7a9d6b6.png)

The data on both sides are: 

Agent
```
[vagrant@localhost ~]$ rpm -qi vim-enhanced-8.0.1763-16.el8.x86_64
Name        : vim-enhanced
Epoch       : 2
Version     : 8.0.1763
Release     : 16.el8
Architecture: x86_64
Install Date: Tue 04 Jan 2022 01:34:16 PM UTC
Group       : Unspecified
Size        : 3066075
License     : Vim and MIT
Signature   : RSA/SHA256, Wed 22 Sep 2021 05:21:13 PM UTC, Key ID 05b555b38483c65d
Source RPM  : vim-8.0.1763-16.el8.src.rpm
Build Date  : Wed 22 Sep 2021 11:11:05 AM UTC
Build Host  : x86-02.mbox.centos.org
Relocations : (not relocatable)
Packager    : CentOS Buildsys <bugs@centos.org>
Vendor      : CentOS
URL         : http://www.vim.org/
Summary     : A version of the VIM editor which includes recent enhancements
Description :
VIM (VIsual editor iMproved) is an updated and improved version of the
vi editor.  Vi was the first real screen-based editor for UNIX, and is
still very popular.  VIM improves on vi by adding new features:
multiple windows, multi-level undo, block highlighting and more.  The
vim-enhanced package contains a version of VIM with extra, recently
introduced features like Python and Perl interpreters.

Install the vim-enhanced package if you'd like to use a version of the
VIM editor which includes recently added enhancements like
interpreters for the Python and Perl scripting languages.  You'll also
need to install the vim-common package.

```
Manager
```
sqlite> SELECT * FROM sys_programs WHERE name IS "vim-enhanced";
scan_id|scan_time|format|name|priority|section|size|vendor|install_time|version|architecture|multiarch|source|description|location|triaged|cpe|msu_name|checksum|item_id
0|2022/01/04 15:20:53|rpm|vim-enhanced||Unspecified|3066075|CentOS|1641303256|2:8.0.1763-16.el8|x86_64|||A version of the VIM editor which includes recent enhancements||0|||0881d75a4b435b0d7c8b34b937f29162b8fc4f2c|fa692536703fe4a0eb51864895893dd699fb21be
```

**Comment by Dwordcito** [comment]
## Fedora 34
Agent side
![image](https://user-images.githubusercontent.com/14300208/148166449-3b5d601c-01e2-4b69-80cf-88b729d32d80.png)
![image](https://user-images.githubusercontent.com/14300208/148166877-69caba73-0b82-4842-924e-cb45ce76a892.png)

Manager side.
![image](https://user-images.githubusercontent.com/14300208/148166553-4a4878c1-868e-4ed0-9786-6cc2e90f0a4a.png)

**Comment by Dwordcito** [comment]
## Centos 5
![image](https://user-images.githubusercontent.com/14300208/148167338-73740f78-edd6-430a-8182-fe8fd45b4431.png)

![image](https://user-images.githubusercontent.com/14300208/148167425-67281f9b-bf91-4e4a-8716-5539d91c43cd.png)

**Comment by jnasselle** [comment]
# openSUSE Tumbleweed - Exploratory

## Package retrieving using librpm
### Agent side
- OS info
```
localhost:/home/vagrant # cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20210807"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210807"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210807"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo"
```
- RPM packages comparison
```
localhost:/home/vagrant # rpm -qa | wc -l
352
localhost:/home/vagrant # rpm -qa | grep "gpg-pubkey" | wc -l
4
localhost:/home/vagrant # sqlite3 /var/ossec/queue/syscollector/db/local.db "SELECT COUNT(*) FROM dbsync_packages;"
348
```
- Error Check
```
localhost:/home/vagrant # grep "wazuh-modulesd:syscollector: ERROR:" /var/ossec/logs/ossec.log 
localhost:/home/vagrant # 
```
### Manager side
- Packages inventory using Wazuh App
![image](https://user-images.githubusercontent.com/1791430/148282524-886cc1f5-69d4-43ec-b11b-9c117db9c14c.png)

- Error check
```
[root@wazuh-manager ~]# grep "wazuh-db: ERROR" /var/ossec/logs/ossec.log 
[root@wazuh-manager ~]# 
```
