### ISSUE TITLE
After upgrade to 4.3.0 - Failed include Custom Rules with overwrite="yes" 

### ISSUE THREAD

**Issue by martinzeifang** [wazuh/wazuh#11596]
|Wazuh v4.3.0|Wazuh-Manager|Install Single Server|Linux wazuh-manager 3.10.0-1160.42.2.el7.x86_64

after I updated Wazuh-Manager to v4.3.0 I was unable to start the wazuh-Manager Service. It looks like the Problem is the overwrite option in custom rules. If I delete all custom rules with the overwrite options the system starts just fine. If I add for example: 

    <rule id="60611" level="3" overwrite="yes">
        <if_sid>60609</if_sid>
        <field name="win.system.eventID">^11724$|^1034$</field>
        <options>no_email_alert</options>
        <description>Application Uninstalled $(win.eventdata.data)</description>
        <options>no_full_log</options>
    </rule>

the Service doesn't start. 
The Wazuh-Manager creates the error: 

Could not check validation (1908) - Error validating configuration: Invalid use of overwrite option. Could not overwrite parent rule at rule '60611'., (1220): Error loading the rules: 'etc/rules/xxx_CUSTOM_EmailDisable.xml'.

**Comment by juliancnn** [comment]
Hi @martinzeifang,

In previous versions of wazuh (below v4.2.4), the bug reported in issue #8210, with the overwrite option, was present. To avoid these problems, now, a rule with the overwrite tag does not allow the `if_sid`, `if_group` or `if_level options`.

You could see more details in issue [Custom changes to the ruleset not working properly #7948](https://github.com/wazuh/wazuh/issues/7948) and PR [Fix the working of the overwrite option of the rules #8210](https://github.com/wazuh/wazuh/pull/8210)

Regards,
Julian

**Comment by martinzeifang** [comment]
Hallo Julian, 
thank you for the reply. How can than be reffered to an other sid if if_sid isn't allowed anymore in overwrite="yes". 
For example the vmware rules are old. some rules has to be overwritten to work. 

Regards
Martin

**Comment by juliancnn** [comment]
I understand your concern, but we can use an alternative solution until the vmware rules are updated.
I think there are 2 cases for replacing a rule:
- The rule does not match and should
- The rule matches and should not

The first case is the simplest, since we should create new rules without changing the old ones. 
The second case may be more complex. If the rule matches and it should not, you could create a child rule instead of overwriting it to add new conditions, change the level or the description. For example, instead of replacing rule 60611 we could create a new child rule of this one:

```xml
<rule id="100011" level="3" >
    <if_sid>60611</if_sid>
    <options>no_email_alert</options>
    <description>Application Uninstalled $(win.eventdata.data)</description>
    <options>no_full_log</options>
</rule>
```

Please let me know if you found this helpful.

**Comment by martinzeifang** [comment]
yes I understand. I changed my custom rules from overwrite to new rules. that worked great. Thank you

**Comment by martinzeifang** [comment]
> I understand your concern, but we can use an alternative solution until the vmware rules are updated. I think there are 2 cases for replacing a rule:
> 
> * The rule does not match and should
> * The rule matches and should not
> 
> The first case is the simplest, since we should create new rules without changing the old ones. The second case may be more complex. If the rule matches and it should not, you could create a child rule instead of overwriting it to add new conditions, change the level or the description. For example, instead of replacing [rule 60611](https://github.com/wazuh/wazuh/blob/c66924add18180fbf9629ae72e34129b6b7da277/ruleset/rules/0585-win-application_rules.xml#L104-L109) we could create a new child rule of this one:
> 
> ```
> <rule id="100011" level="3" >
>     <if_sid>60611</if_sid>
>     <options>no_email_alert</options>
>     <description>Application Uninstalled $(win.eventdata.data)</description>
>     <options>no_full_log</options>
> </rule>
> ```
> 
> Please let me know if you found this helpful.

Hi, a follow up to that Problem. there is a third Option: the rule matches but the rule.level for example doesn't. For Example Rule 92090 (a new sysmon rule). It is generating a lot of false positives. The Rule includes a if_group:

`    <rule id="92090" level="15">
        <if_group>sysmon_event_11</if_group>
        <field name="win.eventdata.targetFilename" type="pcre2">(?i)[c-z]:\\\\Users\\\\.+\\\\AppData\\\\Local\\\\Temp\\\\.+\.(exe|bin|dll|vbs|bat|js)</field>
        <description>Executable file dropped in folder commonly used by malware</description>
        <mitre>
            <id>T1105</id>
        </mitre>
    </rule>`

so how would I be able to lower the rule level here?

**Comment by JcabreraC** [comment]
Hello @martinzeifang,

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Juan
