### ISSUE TITLE
Create pid file for API and Cluster child processes

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#11606]
|Wazuh version|Component|
|---|---|
| 4.3 | Wazuh API & Wazuh Cluster |

## Description

Multiprocessing was added to the Wazuh API and cluster in 4.3. This implies the creation of child processes that are independent, like it can be seen here for the cluster process:
```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
...
wazuh       3218 26.8  0.3 267940 49480 ?        Sl   10:22   0:01 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       3221  0.0  0.2 120476 44044 ?        S    10:22   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
wazuh       3224  0.0  0.2 267940 44064 ?        S    10:22   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py
...
```

The processes in Wazuh have a .pid file associated within the `/var/ossec/var/run` folder so that they can be managed correctly:
```
# ls -l /var/ossec/var/run/
total 52
-rw-r----- 1 wazuh wazuh    5 Dec 30 10:18 wazuh-analysisd-1890.pid
-rw-r----- 1 wazuh wazuh 2531 Dec 30 10:26 wazuh-analysisd.state
-rw-r----- 1 root  wazuh    5 Dec 30 10:18 wazuh-authd-1843.pid
-rw-r----- 1 wazuh wazuh    5 Dec 30 10:22 wazuh-clusterd-3218.pid
-rw-r----- 1 wazuh wazuh    5 Dec 30 10:18 wazuh-db-1856.pid
-rw-r----- 1 root  wazuh    5 Dec 30 10:18 wazuh-execd-1879.pid
-rw-r----- 1 root  wazuh    5 Dec 30 10:18 wazuh-logcollector-2064.pid
-rw-r--r-- 1 root  wazuh 1357 Dec 30 10:25 wazuh-logcollector.state
-rw-r----- 1 root  wazuh    5 Dec 30 10:18 wazuh-modulesd-2091.pid
-rw-r----- 1 wazuh wazuh    5 Dec 30 10:18 wazuh-monitord-2082.pid
-rw-r----- 1 wazuh wazuh    5 Dec 30 10:18 wazuh-remoted-2002.pid
-rw-r--r-- 1 wazuh wazuh  511 Dec 30 10:26 wazuh-remoted.state
-rw-r----- 1 root  wazuh    5 Dec 30 10:18 wazuh-syscheckd-1899.pid
```

However, although the parent process of the cluster and the API have their `.pid` file, this is not the case with their child processes. This can lead to problems of various kinds. For example, if the parent process suddenly dies (for example, killing it with `-9` option), its child processes will be left running and forgotten forever and wazuh will not kill them.

For this reason, the child processes must be managed in the same way as the main process:
https://github.com/wazuh/wazuh/blob/95c46146dd0ad8c14972dbc19ecab37e03ea3663/api/scripts/wazuh-apid.py#L172

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Issue update

Reviewing the scripts code to apply the desired changes I noticed that the Wazuh API does not create a PID file when running on foreground mode. As this issue is related, it will be fixed as well.

https://github.com/wazuh/wazuh/blob/15397f1d23b23f561e9a58aa2008645898d71fc1/api/scripts/wazuh-apid.py#L169-L172
