### ISSUE TITLE
Increase logcollector file limit in Windows

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#11618]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | LogCollector | Agent | Packages | Windows |

Hello Team,
## Description
When configuring the windows agent to read logs using wildcards in the filename there is a possibility that LogCollector needs to handle a lot of files. In this case, we are facing the error in the ossec.log that states a limit was reached:
```
2021/12/30 10:24:41 wazuh-agent: WARNING: (1960): File limit has been reached (200).
```
The way of mitigating this in Linux agents (The configuration is present for Windows agents also) is by changing this configuration in the `internal_options.conf` file:
```
# Logcollector - Maximum number of files to be monitored [1..100000]
logcollector.max_files=1000
```
But the default configuration seems to be higher than that number, and changing it does not solve the issue.

## Findings
The limit seems to be a fixed value stored in a constant in the code: https://github.com/wazuh/wazuh/blob/a6e7b5abd4664441fa2da6dedc4ca695c41a46fe/src/logcollector/logcollector.h#L21

## Possible Solutions
Since Windows Executive limits the handles to 16Mi I suggest changing the limit to a configurable value higher than 200 as per the Linux agents.

Thank you in advance!

**Comment by Damian-Mangold** [comment]
Duplicate. The problem will be resolved in this issue --> [Windows Agent: Unable to increase the default file limit(200)](https://github.com/wazuh/wazuh/issues/14144#top)
