### ISSUE TITLE
Active response "expected"

### ISSUE THREAD

**Issue by socencriptia** [wazuh/wazuh#1162]
hello,
I'm trying to pass the agent id to my script through the expected field 
located in the command section.
I have understood in the documentation that only the fields extracted by means of the decoder pass through.
Am I missing something or is not possible?
my ossec.conf
 \<command\>
 \<name\>status\</name\>
 \<executable\>status.sh\</executable\>
   \<expect\>agent.id\</expect\>
   \<timeout_allowed\>no\</timeout_allowed\>
  \</command\>

  \<active-response\>
   \<disabled\>no\</disabled\>
   \<command\>status\</command\>
   \<location\>server\</location\>
   \<rules_id\>90008,90007\</rules_id\>
  \</active-response\>

my script

#!/bin/sh
agent.id=$1
var1=$(/var/ossec/bin/agent_control -i $1 | grep "Status")
echo $1 $var1

Finally, thank you in advance and sorry for the English.

**Comment by TJOSERAFAEL** [comment]
Hi @socencriptia ,

the `<expect>` field only supports the values: **srcip**, **user** and **filename**.

We are going to extend this feature in a future release of Wazuh

Best regards.
