### ISSUE TITLE
Include the NVD as a complementary feed for vulnerability-detector

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1164]
Sometimes the official OVAL files of the supported distributions do not contain all the necessary information. An example of this is the case of Debian, whose vulnerabilities do not include a severity to classify them, or may include a doubtful check: less than 0.

In these cases it would be interesting to supplement the alerts with information from the NVD.

**Comment by aderumier** [comment]
@crolopez 

Could it be also possible to add openvas NVT feed?

http://www.openvas.org/openvas-nvt-feed.html

(It's already aggregate a lof of sources)

**Comment by crolopez** [comment]
Hi @aderumier,

I think that feed is exclusive to openvas. Am I wrong? 

However, if it were possible to access this feed and its use were free, we could integrate it. Although Wazuh only detects host-level vulnerabilities, at the moment.

Best regards.

**Comment by crolopez** [comment]
Perfect, we will study it. Thanks for the feedback!

Best regards.

**Comment by snaow** [comment]
Work in progress.
Closed in favor of https://github.com/wazuh/wazuh/issues/4749
