### ISSUE TITLE
NVD Database Update

### ISSUE THREAD

**Issue by Sharjeel914** [wazuh/wazuh#11652]
Hi there,

My NVD Database Update keeps getting failed. I have the latest version of Wazuh manager and agent. I also tried to delete cve.db but that didn't solve the problem. I get the following errors in my logs: 
2022/01/01 03:04:01 wazuh-modulesd:vulnerability-detector: WARNING: (5522): There was no valid response to 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2022.meta' after '3' attempts.
2022/01/01 03:04:01 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'National Vulnerability Database' database could not be fetched.
2022/01/01 03:04:22 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.

Kindly help me out with this. Thank you!

Kind regards,
Sharjeel

**Comment by MiguelazoDS** [comment]
Hello @Sharjeel914, 

I was not able to reproduce your issue. This is what I get with 4.2.5. 

![image](https://user-images.githubusercontent.com/13010397/147927171-aa94c48b-5a3e-4846-8343-1dee5e190a9d.png)

Are you still experiencing this error? My assumption is that at the time you tried the NVD information was not available yet. 

If the issue still persists I would like to know more about your environment. 

- What installation method did you follow? 
- Could you add the line `wazuh_modules.debug=2` in your `/var/ossec/etc/local_internal_option.conf` file, restart your manager and share the output of those logs when the issue occur?

Regards!

**Comment by zhsc** [comment]
Not sure if this will help, but I just had a similar issue with this file.  In my case it seems my Nexus instance didn't like the certificate being used anymore when proxying the nist.gov site.  After re-adding the certificate it was able to fetch fine.  So, not sure if anything recently changed with any certs, but if you have them pinned it could be something to check.

**Comment by Sharjeel914** [comment]
Hello @MiguelazoDS 

Thank you for getting back to me! Your assumption was right, it is perfectly working now without doing anything.

Please close this thread. Thank you!

Kind regards,
Sharjeel

**Comment by MiguelazoDS** [comment]
Glad to know that @Sharjeel914. Have a good day!
