### ISSUE TITLE
Error when building wazuh-manager from the master branch on centos 7.9: port 55000 is not listening

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#11674]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [master branch(commit id `218787c1487ddf7a3f43d8c4727bd643c456ca8e`)](https://github.com/wazuh/wazuh/commit/218787c1487ddf7a3f43d8c4727bd643c456ca8e) | Wazuh server | Manager | [Sources](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html) | Centos 7.9 |

# master branch(commit id `218787c1487ddf7a3f43d8c4727bd643c456ca8e`))

When build the `wazuh-manager` from SOURCES(`master branch`) on `centos 7.9` following the steps

```shell
yum install make gcc gcc-c++ policycoreutils-python automake autoconf libtool centos-release-scl openssl-devel -y
yum install devtoolset-7 -y
scl enable devtoolset-7 bash

curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz
cd cmake-3.18.3 && ./bootstrap --no-system-curl
make -j$(nproc) && make install
cd ../

yum install -y git
git clone https://github.com/wazuh/wazuh.git
cd wazuh
./install.sh
/var/ossec/bin/wazuh-control start
systemctl start wazuh-manager
```

there is an error when using `restful API` and port `55000` is not listening:

```shell
# curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?pretty"
curl: (7) Failed connect to localhost:55000; Connection refused
# netstat -natl | grep 55000
```

# `4.3.0-rc2` branch

when `git checkout v4.3.0-rc2` to rebuild `wazuh-manager`  following the above steps, the `restful API` is OK and port `55000` is listening.

Could you help me? Thanks.

**Comment by pereyra-m** [comment]
Hi @hustliyilin ! Thanks for using Wazuh.

As we can see in the **README.md**, that branch is always under development

- **master** branch contains the latest code, be aware of possible bugs on this branch.

Like the last release is the **v4.2.5**, the `4.2` branch is the most recent stable branch.
And the **v4.3.0** has not been released yet, is under testing (release candidate 2 at this moment). 

If you need to use the installation from sources and not from packages for any reason, please use the `4.2` branch.

Regards.

**Comment by hustliyilin** [comment]
> the last release

@pereyra-m Thank you very much for your suggestions. For users, both the last release `v4.2.5` and the `4.2` branch can run normally without this bug.

But for community developers, when they contribute their own codes to the master branch, this bug may cause problems for their testing.

**Comment by hustliyilin** [comment]
I `git pull` the newest master branch, this bug is fixed by [patch](https://github.com/wazuh/wazuh/commit/14cd40dccb979eef184f723c2e4d077391b9b46e) ,  close it.  Thanks again @pereyra-m

**Comment by pereyra-m** [comment]
Thank you for your comments and opening this issue!
I'm glad it is solved now.

Regards.
