### ISSUE TITLE
Compilation on s390 failed with /usr/bin/ld: cannot find -lstdc++

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh#11696]
I'am trying to build an RPM with the latest Wazuh Agent 4.2.5 on our s390 Linux (RedHat 8.5) system.

It failed with these message:

make[4]: Entering directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/data_provider/build'
[ 10%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync.cpp.o
[ 14%] Building CXX object CMakeFiles/sysinfo.dir/src/network/networkInterfaceLinux.cpp.o
[ 28%] Building CXX object CMakeFiles/sysinfo.dir/src/osinfo/sysOsParsers.cpp.o
[ 20%] Building CXX object CMakeFiles/dbsync.dir/src/dbsyncPipelineFactory.cpp.o
[ 30%] Building CXX object CMakeFiles/dbsync.dir/src/dbsync_implementation.cpp.o
[ 42%] Building CXX object CMakeFiles/sysinfo.dir/src/sysInfoLinux.cpp.o
[ 40%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_dbengine.cpp.o
[ 57%] Building CXX object CMakeFiles/sysinfo.dir/src/sysInfo.cpp.o
[ 50%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_wrapper.cpp.o
[ 60%] Linking CXX shared library lib/libdbsync.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [CMakeFiles/dbsync.dir/build.make:161: lib/libdbsync.so] Error 1
make[4]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/shared_modules/dbsync/build'
make[3]: *** [CMakeFiles/Makefile2:118: CMakeFiles/dbsync.dir/all] Error 2
make[3]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/shared_modules/dbsync/build'
make[2]: *** [Makefile:101: all] Error 2
make[2]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/shared_modules/dbsync/build'
make[1]: *** [Makefile:1360: build_shared_modules] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 71%] Linking CXX shared library lib/libsysinfo.so
/usr/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
make[4]: *** [CMakeFiles/sysinfo.dir/build.make:145: lib/libsysinfo.so] Error 1
make[4]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/data_provider/build'
make[3]: *** [CMakeFiles/Makefile2:100: CMakeFiles/sysinfo.dir/all] Error 2
make[3]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/data_provider/build'
make[2]: *** [Makefile:101: all] Error 2
make[2]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src/data_provider/build'
make[1]: *** [Makefile:1370: build_sysinfo] Error 2
make[1]: Leaving directory '/root/rpmbuild/BUILD/wazuh-4.2.5/src'
make: *** [Makefile:722: agent] Error 2

I also can't compile from source directly. With works with Version 4.1.5.

The spec-file is quite the same for 4.1.5 and 4.2.5, just changed the sources.....

**Comment by jnasselle** [comment]
Hi @Joeri-MS ,

Thanks for reporting this issue. Wazuh compilation depends on libstdc++-static package, that unfortunately could not be retrieved easily using yum, that's why we store that rpm package in packages.wazuh.com and add it to [Installing Wazuh agent from sources guide](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.html).
By other hand, this uploaded package was compatible with centOS 8.4 libstdc++-devel package, and not with 8.5, and this must be solved by Wazuh.

In the meantime, you could solve this by running the next line before the compilation
```
rpm -i $(rpm --eval http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-8.5.0-4.el8_5.'%{_arch}'.rpm)
```
Hope this helps!

**Comment by Joeri-MS** [comment]
Okay, but this seems complicated with zLinux s390....
There is an Repo from RedHat: codeready-builder-for-rhel-8-s390x-rpms which we had to sync now.
Thanks for the Information.

**Comment by Joeri-MS** [comment]
Now it works.
