### ISSUE TITLE
Agents Preview. Error. 3035 - Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#1173]
Error occurred when selecting 'Agents' from the top menu.  Nothing appeared in the main UI for the circular busy indicator.

**Comment by JuanjiJG** [comment]
Hello @alphaDev23,

We would like to check your current Wazuh app and API versions. Please execute the following commands and paste here the output:
```
cat /usr/share/kibana/plugins/wazuh/package.json | grep revision
curl -XGET -u <api_user>:<api_password> http(s)://<api_address>:55000/version?pretty
```

The `3035` error code means that the app failed when trying to fetch agent data from the API. You can also try the following API requests to see if they're working properly:
```
curl -XGET -u <api_user>:<api_password> http(s)://<api_address>:55000/agents?pretty
curl -XGET -u <api_user>:<api_password> http(s)://<api_address>:55000/agents/summary?pretty
```

Let us know about the results.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @alphaDev23,

It's been more than a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you have problems or questions about Wazuh.

Regards,
Juanjo
