### ISSUE TITLE
Wazuh DB can not create a backup if there are open transactions or statements in cache

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#11738]
### Description

This issue was reported by @MiguelazoDS.

During the implementation of the epic https://github.com/wazuh/wazuh/issues/10771, a backup creation mechanism was added.
When the **global.db** backup creation is requested, sometimes an error message is generated

![image (10)](https://user-images.githubusercontent.com/65046601/148243062-daa427f3-9d64-4ce0-8e4f-52ec4701ca57.png)

This issue must be investigated and solved.

### Risk analysis

- All the modifications proposed must be analyzed to be sure no new hazards are introduced.

### DoD

- [x] The root cause of the issue was identified.
- [ ] The proposed fix solves the issue.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11739 was merged.
