### ISSUE TITLE
[Questions]Two questions about wazuh SCA

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#11740]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Wazuh component | Manager/Agent | Sources | OS version |

Wazuh is a very powerful security platform and is adapted to many OSs. When I use it, I found that the current Wazuh SCA adopts the CIS standard of each OS. There are two questions to ask:

1. Some OSs have completed CIS certification but have not been integrated by wazuh SCA, such as `Fedora`, `Oracle Linux`, `Aliyun Linux` and etc. Does wazuh have plans to support all CIS certified OSs in the future? If other developers want to support these OSs in the Wazuh community, do they need to be authorized by CIS?
2. Some OSs integrated by Wazuh SCA have not completed CIS certification, such as `darwin`. I see that `darwin` uses the CIS of other OS. Does this also need to be authorized by CIS?

Could you help answer my questions? Thank you so much.

**Comment by FrancoRivero** [comment]
Hi @hustliyilin,

Sorry for the delay and thanks for your patience.

We are a open source project so you could add your contribution or your suggestion to improve the project. 
If you want to add change you must:

1. Clone the project
2. Create a branch
3. Add your changes
4. Create a pull-request to master

After that these changes to be review for someone of Wazuh, and if these changes are correct will be added in the some version of Wazuh. 
Regarding the CIS certification from version to version, new OSs will be added, but if you need a new certification for some OS urgently you should add a new issue to be analyzed, estimated and developed by Wazuh development team.
Regards

**Comment by hustliyilin** [comment]
> Hi @hustliyilin,
> 
> Sorry for the delay and thanks for your patience.
> 
> We are a open source project so you could add your contribution or your suggestion to improve the project. If you want to add change you must:
> 
> 1. Clone the project
> 2. Create a branch
> 3. Add your changes
> 4. Create a pull-request to master
> 
> After that these changes to be review for someone of Wazuh, and if these changes are correct will be added in the some version of Wazuh. Regarding the CIS certification from version to version, new OSs will be added, but if you need a new certification for some OS urgently you should add a new issue to be analyzed, estimated and developed by Wazuh development team. Regards

Thank you very much @FrancoRivero. You have answered my question, I will contribute my codes and ideas to wazuh as much as possible, and I sincerely wish the `wazuh` community will become better and better.

By the way, following the steps you provided I initiated a [pull request](https://github.com/wazuh/wazuh/pull/11741) to remove the unused include file the other day. I don't know if the format is correct, I would be very grateful if you could give some review suggestions.

**Comment by FrancoRivero** [comment]
Hi @hustliyilin,
I reviewed your code and approved it, at this time we must await the review by someone with privileges to merge to master. Thank you very much for your contribution and we are very happy that you are part of our community. 
PD: We have a channel in slack to talk about Wazuh I leave a [link](https://wazuh.slack.com/archives/C0A933R8E) to this.
Regards

**Comment by hustliyilin** [comment]
> Hi @hustliyilin, I reviewed your code and approved it, at this time we must await the review by someone with privileges to merge to master. Thank you very much for your contribution and we are very happy that you are part of our community. PD: We have a channel in slack to talk about Wazuh I leave a [link](https://wazuh.slack.com/archives/C0A933R8E) to this. Regards

Hi @FrancoRivero，
Thank you very much for your quick reply.  I will also pay attention to the link you provided.  Now I can close this issue.

**Comment by hustliyilin** [comment]
> After that these changes to be review for someone of Wazuh, and if these changes are correct will be added in the some version of Wazuh.
> Regarding the CIS certification from version to version, new OSs will be added, but if you need a new certification for some OS urgently you should add a new issue to be analyzed, estimated and developed by Wazuh development team.
> Regards

Hi @FrancoRivero , 

As previously communicated, I open pr #11875 to add the `Alibaba Cloud Linux (Aliyun Linux) 2` CIS SCA.  I would be very grateful if you could give some review suggestions.

By the way, CIS `Aliyun Linux 2` Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228) was published
on Aug 16th, 2019. `Aliyun Linux 2` is compatible with `Centos 7` and it's
further renamed as `Alibaba Cloud Linux 2`. Besides, The ID of `Alibaba
Cloud Linux (Aliyun Linux) 2` in /etc/os-release is 'alinux'

I add the `Alibaba Cloud Linux (Aliyun Linux) 2` SCA in the wazuh
according to CIS `Aliyun Linux 2` Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228)

Thanks again.

**Comment by FrancoRivero** [comment]
Hi @hustliyilin,
Sorry for the late reply.
Thank you so much for your contribution to the proyect!
We need to add a new ticket with details about your changes after creating the new issue, you must link it with your pull-request.  This is for a better tracking. Could you close this issue and create other issue with the details about your changes ? Let me know if you need help with that.
Regards

**Comment by hustliyilin** [comment]
> I would be very grateful if you could give some review suggestions.

Hi @FrancoRivero ,

Thanks a lot for telling me this information.  I open the new issue #12052 to track this problem.  And I also linked issue #12052  with my pull request #11875.  

Now I can close this issue.
