### ISSUE TITLE
Deprecate the `agent-group` files usage from the Wazuh manager code

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#11752]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771 we migrated all the data saved in the `agent-group` files to the `global.db` in `wazuh-db`. Having said that, many parts of the Wazuh manager code should be deprecated ad the synchronization of the `agent-group` files will no longer happen.

### Requirements

- Here is a rough summary of functions involved with the `agent-group` files. All this code should be deprecated or, in any case, updated to stop working with the `agent-group` files.
- Apart from the functions in the list, it could be more code related to the `agent-group` files that should be removed.

- [ ] wdb_update_groups()
- [X] wm_clean_dangling_groups()
- [X] wm_inotify_setup()
- [X] wm_inotify_start()
- [X] create_multigroup_dir()
- [ ] wdb_remove_group_db()
- [ ] wdb_update_agent_multi_group()
- [X] w_remove_multigroup()
- [X] wstr_find_in_folder()
- [X] wstr_find_line_in_file()
- [X] wdb_update_agent_group()
- [X] wdb_global_update_agent_group()
- [X] wdb_parse_global_update_agent_group()
- [X] OS_RemoveAgentGroup()

### Risk analysis

We should make sure that as we remove all the usage of the `agent-group` files, we do not have any lack of functionality in the group management. This should work perfectly in single manager scenarios until having the changes are implemented in the cluster.

### Testing required

- [ ] Manual testing of groups creation.
- [ ] Manual testing of groups assigned to the agents.
- [ ] Manual testing of removing agents from groups.

### DoD

- [ ] All the requirements should be implemented.
- [ ] All the required tests should pass successfully.
- [ ] The code review should be approved.
- [ ] Scan-build execution without errors.

**Comment by MiguelazoDS** [comment]
# Notes: 

## Functions that were not deleted nor modified.

- `wdb_update_groups()`: Deletes groups from DB that don't exist in the shared folder, and insert new ones that do exist.  
- `wdb_remove_group_db()`: Deletes entry from belongs table, if success deletes group by name from group table. Called by the previous function.
- `wdb_update_agent_multi_group()`: Receives as a parameter the comma-separated string with group information from a specific agent and updates databases belongs and group from the group table.
- `wdb_global_update_agent_group()`: Updates belongs table with a comma-separated string with group information. 
- `wdb_parse_global_update_agent_group()` is not called internally and it is the only function that calls `wdb_global_update_agent_group()`. Also call `wdb_global_update_agent_groups_hash` but this one is also used in `wdb_global_update_all_agents_groups_hash()`.
