### ISSUE TITLE
issue about windows update 

### ISSUE THREAD

**Issue by themeswordpress** [wazuh/wazuh#11759]
How do you get these updates codes 

I applied the following command get-hotfix but I got 3 codes (3 kb ) but how wazuh get more than 3 codes (7 codes ) 

<img width="1290" alt="Screenshot at Jan 07 22-18-37" src="https://user-images.githubusercontent.com/51072377/148602444-3104dddc-7dd9-4516-9e85-f29b11c6b2e1.png">

**Comment by mdesocio** [comment]
Out of curiosity could it be drivers/optional updates?

**Comment by Dwordcito** [comment]
Hi @themeswordpress I hope you are well!

Get-HotFix commandlet only returns the CBS (Component Based Servicing), as indicated in the microsoft documentation that I indicated below. Given this, Wazuh can recover all hotfixes on the system. For this information to be used accordingly by vulnerability detector. This is the main reason why you see more "Windows Updates" than the command you are running.

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-hotfix?view=powershell-7.1#notes

**Comment by Dwordcito** [comment]
I close the issue, I hope my answer has helped you, if you have a new question or concern please reopen the issue!! Thanks!!
