### ISSUE TITLE
Migrate agent-group files to wazuh-db - Unit Testing

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#11754]
### Description

This is a tracking purposes issue to reflect all the work done on Unit Testing development for the epic https://github.com/wazuh/wazuh/issues/10771. This issue will be closed after having a 100% of coverage of all the affected code by the implementation of the `agent-group` files migration to `wazuh-db`.

### Requirements

The next set of affected components should be tested:

- [x] Settings parser.
  - [x] read_main_elements(): Here we just add the case of `wazuh-db`. Add the coverage if the original function has UTs. **(won't be tested)**
  - [x] eval_bool() **(tested indirectly)**
  - [x] Read_WazuhDB()
  - [x] Read_WazuhDB_Backup()
  - [x] wdb_init_conf() **(tested indirectly)**
  - [x] wdb_free_conf() **(tested indirectly)**

- [x] Authd code.
  - [x] w_auth_add_agent(): Here we just removed a function parameter. Update the function UTs if it has.
  - [x] local_add(): Here we just removed the `agent-group` files read. Update the function UTs if it has.
  - [x] run_dispatcher(): Here we just updated some parameters sent to the agent addition function. Update the function UTs if it has.
  - [x] run_writer(): Here we added a call to `wazuh-db` to insert the agent. Update the function UTs if it has.

- [x] Remoted code.
  - [x] save_controlmsg(): Here we just updated some parameters sent to the `lookfor_agent_group` function. Update the function UTs if it has.
  - [x] c_multi_group(): Here we changes the call to `purge_group` with `wdb_remove_group_db`. Update the function UTs if it has.
  - [x] c_files(): Many changes in this function. Update the UTs if it has.
  - [x] lookfor_agent_group(): Now it works with `wazuh-db`. Implement or update all the necessary UTs.
    - [x] Remove the `__wrap_set_agent_group` wrapper usage and definition as the function `set_agent_group` was deprecated. 
  - [x] Update the `shared_download` UTs if it has.

- [x] wazuh-db global helpers code.
  - [x] wdb_insert_agent(): Update the UTs.
  - [x] wdb_update_agent_belongs(): Update the UTs.
  - [x] wdb_remove_agent(): Update the UTs.
  - [x] wdb_select_group_belong()
  - [x] wdb_set_agent_groups_csv()
  - [x] wdb_set_agent_groups()
  - [x] wdb_create_agent_db()
  - [x] wdb_update_agent_multi_group()
  - [x] wdb_remove_group_db()

- [x] wazuh-db main code.
  - [x] wdb_check_backup_enabled()
  - [x] run_backup(): Evaluate if it is possible as it is a thread loop. **(it won't be tested)**

- [x] wazuh-db wdb code.
  - [x] wdb_exec_stmt_single_column()
  - [x] wdb_close()
  - [x] wdb_finalize_all_statements()
  - [x] wdb_leave()
  - [x] wdb_get_internal_config()
  - [x] wdb_get_config() 

- [x] wazuh-db parser code.
  - [x] `getconfig` command.
  - [x] `select-group-belong` command.
  - [x] `sync-agent-groups-get` command.
  - [x] `set-agent-groups` command.
  - [x] `get-groups-integrity` command.
  - [x] `backup` command.
  - [x] `insert-agent-belong` command.
  - [x] wdb_parse_global_update_agent_group()
  - [x] wdb_parse_global_select_group_belong()
  - [x] wdb_parse_global_insert_agent_belong()
  - [x] wdb_parse_global_set_agent_groups()
  - [x] wdb_parse_global_sync_agent_groups_get()
  - [x] wdb_parse_get_groups_integrity()
  - [x] wdb_parse_global_backup()
  - [x] wdb_parse_global_get_backup()
  - [x] wdb_parse_global_restore_backup()
  - [x] wdb_parse_get_config()
  - [x] wdb_parse_global_get_groups_integrity()

- [x] wazuh-db queries execution code.
  - [x] wdb_global_select_agent_group() **(it was already tested)**
  - [x] wdb_global_update_agent_group() **(wdb_update_agent_group() is deprecated)**
  - [x] wdb_global_update_agent_groups_hash()
  - [x] wdb_global_update_all_agents_groups_hash()
  - [x] wdb_global_select_group_belong()
  - [x] wdb_global_insert_agent_belong()
  - [x] wdb_global_sync_agent_info_get() **(it was already tested)**
  - [x] wdb_global_calculate_agent_group_csv()
  - [x] wdb_global_get_agent_group_csv()
  - [x] wdb_global_set_agent_group_context()
  - [x] wdb_get_groups_integrity()
  - [x] wdb_global_get_agent_max_group_priority()
  - [x] wdb_global_assign_agent_group()
  - [x] wdb_global_set_agent_groups()
  - [x] wdb_global_set_agent_groups_sync_status()
  - [x] wdb_global_sync_agent_groups_get()
  - [x] wdb_global_create_backup() **(Fix mem leak)**
  - [x] wdb_global_remove_old_backups()
  - [x] wdb_global_get_backups()
  - [x] wdb_global_restore_backup()
  - [x] wdb_global_get_most_recent_backup()
  - [x] wdb_global_get_oldest_backup()
  - [x] wdb_is_group_empty
  - [x] wdb_global_delete_tuple_belong
  - [x] wdb_global_unassign_agent_group

- [X] wazuh-db integrity code.
  - [X] wdb_get_global_group_hash()
  - [X] wdb_global_group_hash_cache()

- [x] wazuh-db upgrade code.
  - [x] test_wdb_recreate_global()
  - [x] wdb_upgrade_global()
  - [x] wdb_adjust_global_upgrade()
  - [x] wdb_global_adjust_v4()

- [x] Synchronization module code.
  - [x] wm_database_main(): We only added a check to see if it is a worker node among two function calls that don't modify the execution flow of the function. As it hasn't UTs project, it won't be tested.
  - [x] wm_check_agents(): We only added a check to see if it is a worker node among two function calls. As it hasn't UTs project, it won't be tested.
  - [x] wm_sync_agents(): We only removed code from this function. It only calls other functions without doing any check of the return values. It won't be tested.
  - [x] wm_sync_agents_artifacts(): This is new function, but it is basically a copy of `wm_sync_agents`. Because of the same reasons, it won't be tested.
  - [x] sync_keys_with_wdb(): Although this is a new function, it will be removed in the upcoming epic in which the client keys file will be migrated to global.db.
  - [x] sync_keys_with_agents_artifacts(): Although this is a new function, it will be removed in the upcoming epic in which the client keys file will be migrated to global.db.
  - [x] sync_agents_artifacts_with_wdb(): Although this is a new function, it will be removed with the legacy databases.
  - [x] wm_clean_agent_artifacts(): Although this is a new function, it will be removed with the legacy databases.
  - [x] wm_sync_legacy_groups_files()
  - [x] wm_sync_group_file()
  - [x] wm_sync_file(): We only changed the way in wich the function returns a value. Instead of hardcoding the value, we make use of a variable. It won't be tested.

- [x] Shared code.
  - [x] strarray_size()
  - [x] OS_SHA256_String_sized()
  - [x] OS_SHA256_String(): We just changes the return data type. Update the function UTs if it has.
  - [x] get_agent_group()

### DoD

- [x] Having a PR approved and merged for the unit tests of each item in the list.
- [x] The UTs project execution shouldn't have any memory leak.

**Comment by MiguelazoDS** [comment]
# Findings 

During the implementation of https://github.com/wazuh/wazuh/pull/11873 we found: 

- Test execution errors. 

![3](https://user-images.githubusercontent.com/13010397/150219148-06bf9c93-249d-4180-980c-2ad133eb5086.png)

- Since the `WDB_GENERIC_COMPONENT` is an empty string https://github.com/wazuh/wazuh/blob/dev-10771-agent-groups-files-to-wazuh-db/src/wazuh_db/wdb_integrity.c#L36 the `mdebug1` log in https://github.com/wazuh/wazuh/blob/dev-10771-agent-groups-files-to-wazuh-db/src/wazuh_db/wdb_integrity.c#L80 adds an additional space.

**Comment by MiguelazoDS** [comment]
When restoring a backup we are accepting anything as parameters, and we are logging an "ok" as a response. 

![image](https://user-images.githubusercontent.com/13010397/150814700-4d5872b3-310e-4359-a6d5-741fe2d0e28d.png)

**Comment by DProvinciani** [comment]
Closing the issue as all the functions enumerated in the description were covered by unit test cases.
