### ISSUE TITLE
Granular email-<event_location>-Using wazuh-agent ip does not work

### ISSUE THREAD

**Issue by coollce** [wazuh/wazuh#11772]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2| email-alert| Manager | Packages| centos7.6 |

Hello，team

agent_ip : 192.168.175.132
agent_name: idsagent

I encountered a problem when configuring email alerts. I want to send emails to different mailboxes according to the agent's ip address or network segment. I tested it many times. When I use the following configuration, I attack the agent, but no Trigger alert emails;
<ossec_config>
  <email_alerts>
      <email_to>myemail</email_to>
      <event_location>192.168.175.132</event_location>
  </email_alerts>
</ossec_config>

When I fill in the agent_name in the label <event_location>, it can send emails according to different agent_names, it is successful, the configuration is as follows:
<ossec_config>
  <email_alerts>
      <email_to>myemail</email_to>
      <event_location>idsagent</event_location>
  </email_alerts>
</ossec_config>

I wonder why using agent_ip didn't work
If I want to send emails to different email addresses based on the IP addresses of different agents, how should I configure？
Thanks

**Comment by coollce** [comment]
> Hi @coollce, Thanks for using Wazuh and sorry for the late reply. I assume you read the [documentation] (https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html), however I share it again. You should set up email alerts something like:
> 
> ```
> <ossec_config>
> <email_alerts>
> <email_to>myemail</email_to>
> <event_location>idsagent</event_location>
> </email_alerts>
> <email_alerts>
> <email_to>otheremail</email_to>
> <event_location>otheragent</event_location>
> </email_alerts>
> <email_alerts>
> <email_to>otherdistinctemail</email_to>
> <event_location>otherdistinctagent</event_location>
> </email_alerts>
> </ossec_config>
> ```
> 
> If you have these configuration, could you share me your log file with these errors? Best regards, Franco

**Comment by coollce** [comment]
> Hi @coollce, Thanks for using Wazuh and sorry for the late reply. I assume you read the [documentation] (https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html), however I share it again. You should set up email alerts something like:
> 
> ```
> <ossec_config>
> <email_alerts>
> <email_to>myemail</email_to>
> <event_location>idsagent</event_location>
> </email_alerts>
> <email_alerts>
> <email_to>otheremail</email_to>
> <event_location>otheragent</event_location>
> </email_alerts>
> <email_alerts>
> <email_to>otherdistinctemail</email_to>
> <event_location>otherdistinctagent</event_location>
> </email_alerts>
> </ossec_config>
> ```
> 
> If you have these configuration, could you share me your log file with these errors? Best regards, Franco

       Thank you very much for your reply，I have gone through the documentation carefully。
My configuration is the same as yours。my purpose is want to use ip address instead of hostname in <event_location>,The documentation states that <event_location> supports any single **agent name**, **hostname**, **IP address**, or **log file** ，The problem I'm having is using either the hostname or the log file or the agent name is successful，but when i use **ip ddress** in <event_location> it doesn't work，/var/log/maillog and  /var/ossec/logs/ossec.log  do not have any error messages。

**Comment by coollce** [comment]
@FrancoRivero Thank you very much for your reply，I have gone through the documentation carefully。
My configuration is the same as yours。my purpose is want to use ip address instead of hostname in <event_location>,The documentation states that <event_location> supports any single agent name, hostname, IP address, or log file ，The problem I'm having is using either the hostname or the log file or the agent name is successful，but when i use ip ddress in <event_location> it doesn't work，/var/log/maillog and /var/ossec/logs/ossec.log do not have any error messages。

**Comment by FrancoRivero** [comment]
Hello @coollce, 
I have been investigating email module in detail and I found an interesting detail if an agent is configured like an IP address "any" this agent won't match with the IP address configure in the manager. Is this agent configure with 192.168.175.132 ? You must check in the agent a file called `client.keys` if this have "any" instead "192.168.175.132", this agent is invisible for the manager. Do you check that? 
Regards

**Comment by coollce** [comment]
Hello @FrancoRivero ，
Thank you very much for your method, according to your suggestion, I reset the agent registration method,
./agent-auth -m server_ip -i 192.168.175.132
At this time, the client.keys file is not any but 192.168.175.132
Then successfully solved my mail sending problem, thank you very much.

**Comment by FrancoRivero** [comment]
Hi @coollce,
I'm glad you solved the problem. I hope I have been helpful in solving it.
I will close the ticket, if you have other problem or you want to ask about this topic again let me know!
Regards
PD: We have a [channel](https://wazuh.slack.com/archives/C0A933R8E) on Slack to ask about Wazuh if you need !
