### ISSUE TITLE
Update Framework unittests

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11782]
### Description

After the changes applied in the Framework code for the development of https://github.com/wazuh/wazuh/issues/10771, it is necessary to update the Framework unittests.

Specifically, the tests related to agents, once fixed, it will be necessary to run **all** unittests to confirm that there is no other error.

**Comment by vicferpoy** [comment]
Framework unit tests were updated in the development issue: https://github.com/wazuh/wazuh/issues/11800.
