### ISSUE TITLE
Remove agent-groups from integrity task

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#11786]
### Description

As part of the agent-groups file removal (https://github.com/wazuh/wazuh/issues/10771), we need to modify the cluster file integrity task.

Currently, the file integrity task is in charge of keeping the `agent-groups` files synchronized. Therefore, we need to modify the integrity task so that it stops synchronizing these files, thus reducing the CPU and memory usage of this task.

This issue will eliminate a great part of the memory usage load of the `previous_status` variable which we implemented in https://github.com/wazuh/wazuh/issues/7861.

On the other hand, it will not be necessary to calculate the MD5 of these files which translates into an improvement in CPU consumption and therefore, a greater speed when synchronizing the rest of the files.

In this case, it is possible that we only need to modify the `cluster.json` file, eliminating the section of the agent-groups files:

https://github.com/wazuh/wazuh/blob/525b17cac7df38919d3e91e35f7258c0dab07d5f/framework/wazuh/core/cluster/cluster.json#L69-L78

**Comment by yanazaeva** [comment]
## Issue update

To complete this issue, it was only necessary to remove this block:
https://github.com/wazuh/wazuh/blob/525b17cac7df38919d3e91e35f7258c0dab07d5f/framework/wazuh/core/cluster/cluster.json#L69-L78

Once this was deleted, we can make sure that the cluster is still working properly: 
| Wazuh master | Wazuh worker 1 | Wazuh worker 2 |
| --- | --- | --- |
|<img src="https://user-images.githubusercontent.com/67015786/150804742-ac32d1cc-6ff4-419c-9094-b347b6b47fdb.png" alt="3" width = 350px height = 200px>|<img src="https://user-images.githubusercontent.com/67015786/150804792-538278b1-1e68-4c7c-8cc3-767e6c1e6af0.png" alt="3" width = 350px height = 200px>|<img src="https://user-images.githubusercontent.com/67015786/150804903-5c458287-1ec5-43bb-8d7e-52de2a9572df.png" alt="3" width = 350px height = 200px>|
|<img src="https://user-images.githubusercontent.com/67015786/150805025-171cd0b0-c0ec-46aa-b05b-f8e9fcb1667f.png" alt="3" width = 350px height = 50px>|<img src="https://user-images.githubusercontent.com/67015786/150805063-f35f5bf1-412f-46dc-8ed3-bcc5f3c13cda.png" alt="3" width = 350px height = 50px>|<img src="https://user-images.githubusercontent.com/67015786/150805101-7bb4eb66-e2e0-432a-925a-5cd78d22bcb6.png" alt="3" width = 350px height = 50px>|
|<img src="https://user-images.githubusercontent.com/67015786/150805131-80e33f30-a644-4ae9-9b4e-13c720e2b2e0.png" alt="3" width = 350px height = 50px>|<img src="https://user-images.githubusercontent.com/67015786/150805173-71dd8174-f153-4f34-be93-b099f79d3df9.png" alt="3" width = 350px height = 50px>|<img src="https://user-images.githubusercontent.com/67015786/150805204-1e57b756-2958-4dfb-850d-a4e26f10c1dc.png" alt="3" width = 350px height = 50px>|

Now, if we check inside the `/var/ossec/queue/agent-groups/` directory, we can see that each manager has an agent group file that belongs to the agent they have registered: 

- Wazuh master: 
```
root@9703d1812d78:/var/ossec/queue/agent-groups# ls
001
```
- Wazuh worker 1:
```
root@c76b95f8ce6c:/var/ossec/queue/agent-groups# ls
002
```
- Wazuh worker 2:
```
root@7c75e72ed206:/var/ossec/queue/agent-groups# ls
003
```

If we create a test file inside this folder it won't get synchronized either. Adding a `test` file in the master node, we can see the previously mentioned behavior:
- Wazuh master:
```
root@9703d1812d78:/var/ossec/queue/agent-groups# date
Mon Jan 24 14:59:55 UTC 2022
root@9703d1812d78:/var/ossec/queue/agent-groups# touch test    
root@9703d1812d78:/var/ossec/queue/agent-groups# ls
001  test
```
- Wazuh worker 1:
```
root@c76b95f8ce6c:/var/ossec/queue/agent-groups# date
Mon Jan 24 15:06:27 UTC 2022
root@c76b95f8ce6c:/var/ossec/queue/agent-groups# ls
002
```
- Wazuh worker 2:
```
root@7c75e72ed206:/var/ossec/queue/agent-groups# date
Mon Jan 24 15:04:40 UTC 2022
root@7c75e72ed206:/var/ossec/queue/agent-groups# ls
003
```

Regarding the timings, we can see a comparison below:
|  | With agent-groups | Without agent-groups  | 
|---|---|---|
| Min | 0.003 | 0.003 |
| Max | 0.019 | 0.013 | 
| Mean | 0.006 | 0.007 | 

The logs and script used for this comparison can be found [here.](https://github.com/wazuh/wazuh/files/7927234/logs_and_script.zip)

**Comment by yanazaeva** [comment]
## Test report
[all_tests.zip](https://github.com/wazuh/wazuh/files/7934568/all_tests.zip)


## Test results

---
| | | | | | |
|--|--|--|--|--|--|
| **Test name** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** | **Status** |
| framework/wazuh/core/cluster/dapi/tests/test_dapi.py | 25 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_cluster.py | 19 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_common.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_control.py | 5 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_local_client.py | 1 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_utils.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/cluster/tests/test_worker.py | 6 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_active_response.py | 14 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_agent.py | 142 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_cdb_list.py | 38 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_common.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_configuration.py | 36 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_database.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_decoder.py | 16 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_exception.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_input_validator.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_logtest.py | 2 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_manager.py | 15 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_mitre.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_pyDaemonModule.py | 5 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_results.py | 40 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_rootcheck.py | 13 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_rule.py | 22 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_sca.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_security.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_stats.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_syscheck.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_syscollector.py | 3 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_task.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_utils.py | 228 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_vulnerability.py | 1 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wazuh_queue.py | 18 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wazuh_socket.py | 20 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wdb.py | 24 | 0 | 0 |  | :green_circle: |
| framework/wazuh/core/tests/test_wlogging.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_auth_context.py | 2 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_decorators.py | 105 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_default_configuration.py | 55 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_orm.py | 54 | 0 | 0 |  | :green_circle: |
| framework/wazuh/rbac/tests/test_preprocessor.py | 11 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_active_response.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_agent.py | 117 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_cdb_list.py | 53 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_ciscat.py | 33 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_cluster.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_decoder.py | 35 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_group.py | 8 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_logtest.py | 6 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_manager.py | 36 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_mitre.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_rootcheck.py | 50 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_rule.py | 56 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_sca.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_security.py | 73 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_stats.py | 7 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_syscheck.py | 25 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_syscollector.py | 12 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_task.py | 28 | 0 | 0 |  | :green_circle: |
| framework/wazuh/tests/test_vulnerability.py | 31 | 0 | 0 |  | :green_circle: |

**Comment by yanazaeva** [comment]
## Issue update

The following occurrences will be deleted as well:

- In the `test_utils.py`, as this section was removed from `cluster.json` file:
https://github.com/wazuh/wazuh/blob/61f5cff8b10c2044ca0e54bb62033ae1adfbf614/framework/wazuh/core/cluster/tests/test_utils.py#L145-L148

- This  condition won't be necessary anymore:
https://github.com/wazuh/wazuh/blob/61f5cff8b10c2044ca0e54bb62033ae1adfbf614/framework/wazuh/core/cluster/cluster.py#L171-L175
