### ISSUE TITLE
No error is thrown when "<disabled>" tag is missing (cluster)

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#1178]

**Comment by vikman90** [comment]
Hi @jesusgn90 @jesuslinares @mgmacias95,

According to the rest of components, `<disabled>` should be optional and have this behavior:

- If no `<cluster>` stanza defined, the Cluster is disabled.
- If `<cluster>` is defined, but `<disabled>` is not defined, the default value should be _enabled_.

Please add this default value to the Cluster configuration.

Issue #1854 depends on this.

Thanks!

**Comment by vikman90** [comment]
I found these conditions in the current implementation:

- If `<disabled>` is not defined:
```
Traceback (most recent call last):
  File "/var/ossec/bin/wazuh-clusterd", line 250, in <module>
    if not cluster_config or cluster_config['disabled'] == 'yes':
KeyError: 'disabled'
```

- If `<node_type>` is not defined:
```
2018-11-21 13:28:47,421 ERROR   : [wazuh-clusterd] Exiting. Reason: 'Invalid configuration: 'Error 3004 - Error in cluster configuration: Unspecified key''.
```
