### ISSUE TITLE
Adapt wdb_global_sync_agent_groups_get with the new groups synchronization requirements

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#11791]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to `wazuh-db`. To do this a synchronization mechanism between worker and master DBs must be implemented.
We need to adapt the **wdb_global_sync_agent_groups_get** command to cope with the synchronization requirements of https://github.com/wazuh/wazuh/issues/10857#issuecomment-1010356203.

### Requirements

- [x] Adapt the **condition** parameter logic, now it must work by **sync_status** and **all**. conditions.
- [x] Make last_id an optional parameter. If last_id doesn´t exist, the query must start from 0.
- [x] Add an optional **set_synced** parameter to mark the agents to **synced** when they are obtained.
- [x] Add an optional "get_global_hash" parameter to return the **global_hash** once there isn´t any more group to get. Note: Evaluate if the global_hash must be returned between the last group or in different command execution.

### Complementary tasks

- [x] Eliminate **group_sync_hash** and rename **group_local_hash** to **group_hash**.

### Testing required

- [x] Create a set of tests using the script **WDB_tester.py** and upload the results in the PR.

### DoD

- [x] All the requirements should be implemented.
- [x] All the required tests should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.
- [x] Valgrind execution during the execution of **WDB_tester.py** without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11809 was merged.
