### ISSUE TITLE
Cluster error detected and agent-upgrade error

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh#11794]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.040303 | Wazuh Manager | Manager | Packages | Debian Stretch-Ubuntu Bionic/Xenial-RHEL7-AL2 |

Some errors were found when installing a distributed environment with the new unattended script:

```
2022/01/11 14:10:18 wazuh-modulesd: ERROR: Cluster error detected
2022/01/11 14:10:18 wazuh-modulesd: agent-upgrade: ERROR: (8123): There has been an error executing the request in the task manager
```

The test includes 21 EC2 instances with several OSs and distros. The error was found in 11 instances.
Reviewing the Jenkins pipeline [logs](https://devel.ci.wazuh.info/job/Test_unattended_distributed/136/consoleFull) there was found that some `workers` were being installed and started before the `master` node. This scenario should be reproduced to test if the start order is the cause of the error.

**Comment by vikman90** [comment]
I manager to reproduce this issue:
1. Stop the master manager.
2. Restart the worker node.

This way, Modulesd prints this log:
```
2022/01/13 13:36:14 wazuh-modulesd: ERROR: Cluster error detected
2022/01/13 13:36:14 wazuh-modulesd:agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.
```
While Clusterd shows this error:
```
2022/01/13 13:36:14 ERROR: [Local 854915] [Main] Internal error processing request 'b'sendsync'': Error 3023 - Worker node is not connected to master
2022/01/13 13:36:14 ERROR: [Local 854915] [Main] Error during connection with '854915': [Errno 104] Connection reset by peer.
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
```

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh/11794?planning-poker) with ZenHub @AdriiiPRodri @Selutario @yanazaeva

**Comment by Selutario** [comment]
## Issue update

As seen in the `cluster.log` error shown by Vikman in https://github.com/wazuh/wazuh/issues/11794#issuecomment-1012104318, the problem is:
1. The worker is not connected to the master node.
2. `Modulesd` writes in the cluster socket (on the worker node) a message that should be sent to the master's `task-manager`.
3. Since the worker is not connected, the following error message is returned on the socket: `err --------`.

The problem cannot be solved since, obviously, it is essential that the worker is connected to the master in order to send something to it. However, we should handle the error to return an explanatory code or message on the socket. The format is yet to be decided.

**Comment by Selutario** [comment]
## Issue update

Reviewing the code, I have seen that the cluster already returns, in addition to the error command, a payload in JSON format that contains information about the error itself.
https://github.com/wazuh/wazuh/blob/8e3eaddef59a3f5769015fb74d8bd6b4dfba756a/framework/wazuh/core/cluster/common.py#L661-L673

If the worker is not connected to the master, an exception will be raised on line 662 when trying to send the message. An error command and the payload with information are generated on line 665 and then sent as a response to the socket where the request was performed, on lines 671-673.

Here is a piece of code to show the result when sending these parameters: 
- **command:** `sendsync` 
- **cnt:** 1 (any number)
- **msg:** `{"daemon_name":"task-manager","message":{"origin":{"name":"worker1","module":"upgrade_module"},"command":"upgrade_cancel_tasks","parameters":{}}}`

```PYTHON3
cmd_len = 12
header_len = cmd_len + 8


def send_msg(command, cnt, msg):
    # Send msg
    sock.send(msg_build(command, cnt, msg))

    # Read response: header
    header = sock.recv(header_len)
    _, total, cmd = struct.unpack(f'!2I{cmd_len}s', header)

    # Read response: payload
    payload = sock.recv(total)

    return cmd, json.loads(payload)
```

This is the result (the worker is not connected):
```
(b'err --------', {'__wazuh_exception__': {'__class__': 'WazuhClusterError', '__object__': {'type': 'about:blank', 'title': 'Wazuh Cluster Error', 'code': 3023, 'extra_message': None, 'extra_remediation': None, 'cmd_error': False, 'dapi_errors': {}, 'ids': []}}})
```

**Comment by vikman90** [comment]
Hi @Selutario,

I confirm this behavior on the client-side: when Clusterd delivers an error header, we expect no payload. Thus, we should apply the following changes:

- [ ] Try to receive a payload even when we got an error header. `OS_RecvSecureClusterTCP()` must return `-2` and indicate the payload size.
- [ ] Make sure that clients periodically try to connect to the Cluster again after an error.

Cheers!
