### ISSUE TITLE
Create a group_global_hash get and cache logic.

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#11793]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to `wazuh-db`. To do this a synchronization mechanism between worker and master DBs must be implemented.
We need to create a method capable to calculate and cache the global group hash.

### Requirements

- [x] Create a **wdb_get_global_group_hash** method to be called by **wdb_global_sync_agent_groups_get**.
- [x] The method should obtain all the non-null values from the group_hash column and calculate the global hash of them.
- [x] The hash calculus should be performed with the already existent methods of DB statement calculus **wdb_calculate_stmt_checksum()**. Note: this method accepts a "component" parameter used only for debugging messages, check if we can at least refactor the method to accept a NULL value that doesn´t print anything. Or make it receive a name directly.
- [x] This method should have DEBUG level logs that help the user and the developer in charge of testing.
- [x] The method must make use of a cache logic, to do this we must:
- [x] Find the best place/structure where to add the os_sha string.
- [x] Each time this method is called it must: Check if the cached hash exists (**cache_hash!=""**), if it exists, it must return it. If it doesn´t exist, it must calculate it, insert it in **cache_hash**, and return it.
- [x] Each time set_agent_group is called it must clear it (**cache_hash=""**)
 
### Testing required

- [x] Manual testing to verify that the hashes are being calculated correctly.
- [x] Manual testing using the DEBUG logs to verify that the cache is being used.
- [x] Validation that agents with **group_hash** as **NULL** are being ignored.

### DoD

- [x] All the requirements should be implemented.
- [x] All the required tests should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11810 was merged.
