### ISSUE TITLE
Create a get-groups-integrity command

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#11790]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to `wazuh-db`. To do this a synchronization mechanism between worker and master DBs must be implemented.
We need to create a **get-groups-integrity** command capable to verify if the groups information on the database is synchronized.

### Requirements

- [x] Create a new command parser in **wdb_parser** to handle the new command.
- [x] The command parser must handle a mandatory **hash** parameter that will be used to verify the DB.
- [x] The command must return 3 possible responses: **synreq**, **synced** or **hash_mismatch**. 
- [x] Create method to be called by the parser to execute the actions:
- [x] First of all, the executor method must execute an SQL query to check if there isn´t any group in **syncreq** status. If there is it must return **syncreq**. If there isn´t it must continue with the validations.
- [x] After that, it should call **wdb_get_global_group_hash** to calculate the local global hash of the DB and compare it with the **hash** received as a parameter. If the hashes match, it must return **synced**. If they don´t, it must return **hash_mismatch**. Note: **wdb_get_global_group_hash** is going to be implemented, if it isn´t available yet, create a dummy method that only makes strcmp with a dummy string.

### Testing required

- [x] Create a set of tests using the script **WDB_tester.py** and upload the results in the PR.

### DoD

- [x] All the requirements should be implemented.
- [x] All the required tests should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.
- [x] Valgrind execution during the execution of **WDB_tester.py** without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11807 was merged.
