### ISSUE TITLE
Feature request | Add regex exclusion on agents localfile's config to prevent flooding

### ISSUE THREAD

**Issue by sebastiandbustos** [wazuh/wazuh#11798]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4 | localfile config block | Agent | Packages | RHEL 8 |

Hello team,
I created this issue to add a Feature Request. It would be very useful to have the possibility to filter out file content using the `localfile` module itself to prevent events flooding sent to the manager.

By having this feature, we could filter or exclude events by only setting a pattern or keyword that identifies the events we want (or don't want) to ingest.
By sending only the necessary events to the manager, we can reduce network traffic among other resources that get affected by an event flooding.

This is a very important request since in some occasions event flooding may prevent events to reach the Wazuh Manager, thus, also preventing our users to detect all alerts.

A configuration example could be this one:
```
  <localfile>
    <location>C:\logs\events.log</location>
    <log_format>syslog</log_format>
    <input>^WebAccess\.*</input>
  </localfile>
```
The idea with this module would be to ingest all events from `C:\logs\events.log` that start with `WebAccess`

It would also be useful the possibility of negating the `input`. For example:
```
  <localfile>
    <location>C:\logs\events.log</location>
    <log_format>syslog</log_format>
    <input negate="yes">^WebAccess\.*</input>
  </localfile>
```
The idea here would be to ingest all events from `C:\logs\events.log` that DON'T start with `WebAccess`

**Comment by LubinLew** [comment]
Hi @sebastiandbustos 

Is it possible to add a configuration to decide whether the localfile is collected from beginning or from the time of agent installation.

Thanks.

**Comment by maumrsms** [comment]
Hello @LubinLew,
The purpose of this feature request is to ask for the possibility of filtering events from a single localfile module by adding a pattern or keyword that makes a reference to the events we want to ingest.

For example, I have a log with different event types, for instance, `FAILED` y `ACCESS`. And I only want to ingest the `FAILED` events. Currently, we send ALL data contained in the file, then Wazuh triggers alerts (or not) based on the ruleset it has. If you have `logall_json` enabled, you'd be logging everything the file contains (both FAILED and ACCESS events).

The idea with this, is to only send the `FAILED` events by applying a filter in the `localfile` module itself. This way the Manager will only receive these FAILED events.

**Comment by havidarou** [comment]
Duplicate https://github.com/wazuh/wazuh/issues/5628
