### ISSUE TITLE
Rootkit false positive on diffutils' `diff`

### ISSUE THREAD

**Issue by ajakk** [wazuh/wazuh#11808]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.5 (also) | Rules/Decoders | New/Error/Improve |

## Description

There is a false positive when checking for rootkits on GNU diffutil's `diff`. Building `diff` from [upstream's sources](https://git.savannah.gnu.org/git/diffutils.git) yields a binary that matches the pattern, too:

```
 ~/git/diffutils $ grep -E 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' src/diff
grep: src/diff: binary file matches
```

The exact matching string is `/dev/full`, which comes from bundled gnulib and seems to have been in diffutils for quite a while:

```
 ~/git/diffutils $ strings src/diff | grep -E 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh'
/dev/full
 ~/git/diffutils $ grep -r '/dev/full'
grep: lib/stdopen.o: binary file matches
grep: lib/libdiffutils.a: binary file matches
tests/help-version:    if test -w /dev/full && test -c /dev/full; then
tests/help-version:      env $i --help    >/dev/full 2>/dev/null && fail=1
tests/help-version:      env $i --version >/dev/full 2>/dev/null && fail=1
tests/help-version:        echo "  with --help or --version output redirected to /dev/full" 1>&2
grep: src/sdiff: binary file matches
grep: src/cmp: binary file matches
grep: src/diff: binary file matches
grep: src/diff3: binary file matches
gnulib/lib/fwriteerror.c:/* Name of a file on which writing fails.  On systems without /dev/full,
gnulib/lib/fwriteerror.c:#define UNWRITABLE_FILE "/dev/full"
gnulib/lib/stdopen.c:             have /dev/full, by opening that write-only instead of
gnulib/lib/stdopen.c:          int full_fd = fd == STDIN_FILENO ? open ("/dev/full", mode) : -1;
 ~/git/diffutils $ git log -S'/dev/full'
commit e454c1471aaf8b3e6bead2313838aefebfe97bca
Author: Jim Meyering <meyering@redhat.com>
Date:   Sat Nov 14 10:31:41 2009 +0100

    tests: add the first script; hook up gnulib-tests

    * configure.ac (AC_CONFIG_FILES): Add tests/Makefile and
    gnulib-tests/Makefile.
    * tests/help-version: New file, from coreutils.
    * tests/test-lib.sh: Likewise.
    * tests/Makefile.am: New file, from gzip.
    * Makefile.am (SUBDIRS): Add tests and gnulib-tests.
    * tests/t-local.sh: New, empty(for now) file.
 ~/git/diffutils $ git tag --contains e454c1471aaf8b3e6bead2313838aefebfe97bca
v2.9
v3.0
v3.1
v3.2
v3.3
v3.4
v3.5
v3.6
v3.7
v3.8
```

### Service/Product/Module

https://github.com/wazuh/wazuh/blob/master/ruleset/rootcheck/db/rootkit_trojans.txt#L43

### Current results

In Kibana, I see a rootcheck event: `Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).`

### Expected results

There should be no event, becaues the file is not trojaned.

**Comment by mthbrown** [comment]
Ran into this issue on Ubuntu 22.04 with the binaries:

```
/usr/bin/diff
/bin/diff
```

**Comment by iasdeoupxe** [comment]
Looks like there are multiple issues about the same / similar message open:
- #19000
- #19346
- #13278

Could be possible that all have the same origin and some could be closed as duplicates.

**Comment by iasdeoupxe** [comment]
New PR which could solve this: #25634

**Comment by vikman90** [comment]
Hi all,

This issue has been fixed by @djosip:
- https://github.com/wazuh/wazuh/pull/25634

Best regards.
