### ISSUE TITLE
Review backups generated with the copyfile function

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11802]
This issue reports a wrong behavior found when investigating the issue https://github.com/wazuh/wazuh/issues/10931.

The backups we generate in our framework functions are using the `copyfile` function of the shutil Python library. This function does not copy the files' metadata. This results in backup files with ownership, permissions, time, etc different from the original ones.

For instance and talking about the behavior discovered in #10931, the `update_ossec_conf` function of `wazuh/manager.py` uses the `copyfile` function to copy the `ossec.conf`. This is wrong as the backup will end up with `wazuh:wazuh` ownership (or `root:root` if API is running as **root**). The rest of the file metadata is also compromised.

We should review this and other usages of `copyfile` in our code. Alternatives such as `copy` or `copy2` should be taken into account and investigated in this issue.

Note that there is a function called `delete_file_with_backup` that also uses this function. We need to review these function usages too.

Also, Python unit tests should be modified for all the changes done in this issue.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
This issue will be solved in https://github.com/wazuh/wazuh/issues/11803#issuecomment-1036283973.
