### ISSUE TITLE
error while installing database configuration

### ISSUE THREAD

**Issue by kingtedd** [wazuh/wazuh#11832]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5| Make database | Manager | Sources | RHEL 8.4 |

Hi,

I just reinstalling wazuh manager coz need to configure database output 
I follow this link for new installation from source : 
- https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html 

and this link to configure database : 
- https://documentation.wazuh.com/current/user-manual/manager/manual-database-output.html#manual-database-output

and at step execute command '**make deps && make TARGET=server DATABASE=mysql** '

I've got error like this : 

cd data_provider/ && mkdir -p build && cd build && cmake     .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /root/wazuh-4.2.5/src/data_provider/build
make[2]: Entering directory '/root/wazuh-4.2.5/src/data_provider/build'
make[3]: Entering directory '/root/wazuh-4.2.5/src/data_provider/build'
make[4]: Entering directory '/root/wazuh-4.2.5/src/data_provider/build'
make[4]: Leaving directory '/root/wazuh-4.2.5/src/data_provider/build'
make[4]: Entering directory '/root/wazuh-4.2.5/src/data_provider/build'
**[ 14%] Linking CXX shared library lib/libsysinfo.so
/usr/bin/ld: cannot find -lstdc++**
collect2: error: ld returned 1 exit status
make[4]: *** [CMakeFiles/sysinfo.dir/build.make:148: lib/libsysinfo.so] Error 1
make[4]: Leaving directory '/root/wazuh-4.2.5/src/data_provider/build'
make[3]: *** [CMakeFiles/Makefile2:115: CMakeFiles/sysinfo.dir/all] Error 2
make[3]: Leaving directory '/root/wazuh-4.2.5/src/data_provider/build'
make[2]: *** [Makefile:114: all] Error 2
make[2]: Leaving directory '/root/wazuh-4.2.5/src/data_provider/build'
make[1]: *** [Makefile:1370: build_sysinfo] Error 2
make[1]: Leaving directory '/root/wazuh-4.2.5/src'
make: *** [Makefile:695: server] Error 2

and I have check lib is already installed
[root@SIEM ~]# yum install libstdc++-devel
Updating Subscription Management repositories.
Last metadata expiration check: 3:19:49 ago on Mon 17 Jan 2022 06:43:29 PM WIB.
Package libstdc++-devel-8.5.0-4.el8_5.x86_64 is already installed.

so anyone have solution or clue for this issue? 
thx

**Comment by jnasselle** [comment]
Hi @kingtedd,

Wazuh is linked to `libstdc++-static`, but this package could not be installed directly using `yum`. 
To overcome this situation, we add a specific step into Centos 8  [Installing Wazuh server from sources](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.html)  guide to download and install this dependency depending on the current `libstdc++-devel` minor release version and architecture.
 ```bash
rpm -i $(rpm -q libstdc++-devel --queryformat "http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-%{VERSION}-%{RELEASE}.%{arch}.rpm\n")
```
Hope this helps!
Nico

**Comment by kingtedd** [comment]
Hi @jnasselle 

mm..that is missed information while installed that dependencie, I have got error signature check and after reconfig gpgcheck = 0 and installing success

[root@SIEM etc]# rpm -i $(rpm -q libstdc++-devel --queryformat "http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-%{VERSION}-%{RELEASE}.%{arch}.rpm\n")
warning: /var/tmp/rpm-tmp.4I5lTr: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY
        package libstdc++-static-8.5.0-4.el8_5.x86_64 is already installed

thx alot

**Comment by jnasselle** [comment]
Glad to hear that @kingtedd !

As this is solved I will close the issue. Feel free to create new issues for new concerns. 

Regards,
Nico
