### ISSUE TITLE
Wrong process state when listing processes with sysinfo's test tool

### ISSUE THREAD

**Issue by RamiroRD** [wazuh/wazuh#11855]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0-rc2 | sysinfo | Agent | Sources | macOS 12.1 |

When running the data_provider `sysinfo_test_tool` program with the `--processes` argument, we get a JSON document with all processes and their state. The state of these processes is mostly "R" (running),  which is not correct since the amount of processes that can be in the running state can be at most the number of cores the operating system detects. 

## How to reproduce

1- Check out the v4.3.0-rc2 tag
2- Compile as per usual
3- run `src/data_provider/build/bin/sysinfo_test_tool --processes` and compare the states to the output of `ps aux`.

As an example, here is part the output of the sysinfo_test_tool:
```

{
  "processes": [
    {
      "euser": "ramiro",
      "name": "pbcopy",
      "nice": 0,
      "pid": "9794",
      "ppid": 1789,
      "priority": 31,
      "rgroup": "staff",
      "ruser": "ramiro",
      "state": "R",
      "vm_size": 34172580
    },
    {
      "euser": "ramiro",
      "name": "head",
      "nice": 0,
      "pid": "9793",
      "ppid": 1789,
      "priority": 31,
      "rgroup": "staff",
      "ruser": "ramiro",
      "state": "R",
      "vm_size": 34122680
    },
    {
      "euser": "ramiro",
      "name": "sysinfo_test_tool",
      "nice": 0,
      "pid": "9792",
      "ppid": 1789,
      "priority": 31,
      "rgroup": "staff",
      "ruser": "ramiro",
      "state": "R",
      "vm_size": 34134120
    },
    {
      "euser": "ramiro",
      "name": "mdworker_shared",
      "nice": 0,
      "pid": "9748",
      "ppid": 1,
      "priority": 4,
      "rgroup": "staff",
      "ruser": "ramiro",
      "state": "R",
      "vm_size": 33702864
    },
    {
      "euser": "ramiro",
      "name": "mdworker_shared",
      "nice": 0,
      "pid": "9736",
      "ppid": 1,
      "priority": 4,
      "rgroup": "staff",
      "ruser": "ramiro",
      "state": "R",
      "vm_size": 33693648
    },
[...]

```
Here is the amount of processes that are reportedly in running state:
```
ramiro@Ramiros-Mac-mini bin % sudo ./sysinfo_test_tool --processes | grep  "\"state\": \"R\"" | wc -l
     580
```
This cannot be correct in an 8-core computer.

## Misc
My guess is the [pbi_status](https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/sys/proc_info.h#L65) changes its enum values from version to version.

**Comment by jnasselle** [comment]
Maybe this information is useful
https://github.com/osquery/osquery/blob/9ecb3f0a77566e7cbc9683b1277a78b25efe1483/osquery/tables/system/darwin/processes.cpp#L119-L148

**Comment by RamiroRD** [comment]
An update on this: osquery seems to have the same problem:
![Screen Shot 2022-02-09 at 16.29.55.png](https://images.zenhubusercontent.com/6182981c3edf217de8dd5a4a/fd8d52f6-e18d-47c4-bd17-2728500872ea)
I will look into the GNU top implementation see how they are dealing with this.

**Comment by RamiroRD** [comment]
It looks like what we need to do is go over all the threads for a given process and then take the state with minimum value, where the order is:
Idle (thread was just created)
Running
Sleeping
Stop (trace)
Zombie

**Comment by RamiroRD** [comment]
We need to revamp the way we iterate through process. What Apple's top does is first iterate through kernel tasks, on which it calls `task_for_pid` on to build a map of processes. While building this pid -> process info map, we should set the state of the process to the minimum state of all its threads.

**Comment by RamiroRD** [comment]
We are stopping our efforts to make thread enumeration (needed to compute process state) work (more details on https://github.com/wazuh/wazuh/pull/12299). Instead, we are leaving this field blank.
