### ISSUE TITLE
Adapt wdb_remove_group_db logic to cope with the belongs synchronization by DB

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#11879]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to `wazuh-db`. To do this a synchronization mechanism between worker and master DBs has been implemented. With this new mechanism, it isn´t required to delete the belongs table when a group is eliminated, because the synchronization tasks of the cluster will keep master and worker synced.
But we need to make the **group delete** command safer, so it isn´t possible to eliminate a group if there are still pending agents belonging to it.
### Requirements

- [x] Remove from wdb_remove_group_db the logic of deleting the agent group belonging when the group folder doesn´t exist no more.
- [x] Add a check in the **group delete** command to control if there are still agents belonging to the group.
- [x] Implement a new "remove" mode for set-agent-groups in charge of removing a list of groups from the agent.

### Testing required

- [x] Create a set of tests using the script **WDB_tester.py** and upload the results in the PR.

### DoD

- [x] All the requirements should be implemented.
- [x] All the required tests should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.
- [x] Valgrind execution during the execution of **WDB_tester.py** without errors.

**Comment by palaciosjeremias** [comment]
### WDB_Tester report
[wdb_tests_set.zip](https://github.com/wazuh/wazuh/files/7908896/wdb_tests_set.zip)
[wed_test_remove.zip](https://github.com/wazuh/wazuh/files/7908897/wed_test_remove.zip)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11883 was merged.
