### ISSUE TITLE
Remove call to execvpe()

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1188]
Function `wm_exec()` uses non-standard function `execvpe()`, that does not work on macOS, BSD or CentOS 5.

The environment variables are changed for the CIS-CAT integration. They should be changed in the standard environment of the child process instead of the parent process. This should work for CIS-CAT and make `execvpe()` unnecessary.

**Comment by chemamartinez** [comment]
Solved: https://github.com/wazuh/wazuh/pull/1207
