### ISSUE TITLE
Amazon Linux 2 OS vulnerability scan issue

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#11882]
Hello,

Im trying to utilize amazon linux 2 os vulnerability scanning and Im getting the error  `wazuh-modulesd WARNING Invalid provider name: 'alas'`. Im using wazuh 4.2.2 and you can see the config block below.

```
<vulnerability-detector>
    ...
    <!-- Amazon Linux OS vulnerabilities -->
    <provider name="alas">
      <enabled>yes</enabled>
      <os>amazon-linux</os>
      <os>amazon-linux-2</os>
      <update_interval>1h</update_interval>
    </provider>
    ...
</vulnerability-detector>
```

thanks in advance,
Tony

**Comment by RamiroRD** [comment]
Hello @antonisnyc94! 
The vulnerability detector does not support Amazon Linux 2 in Wazuh version 4.2. Support for it will come in 4.3. In the mean time, you can force Wazuh to treat it as any other RPM distro if you follow these instructions: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html
In your case, you'd have to add this to your ossec.conf within the `<vulnerabilty-detector>` block:
```
    <provider name="redhat">
      <enabled>yes</enabled>
      <os allow="Amazon Linux-2">7</os>
      <update_interval>1h</update_interval>
    </provider>
```

Let me know how that goes!

**Comment by antonisnyc94** [comment]
@RamiroRD 

Thank you for the quick response! I was aware of the `os allow` option but wanted to avoid false positives. I will be waiting for the new version release.

Best,
Tony
