### ISSUE TITLE
Improve belongs update command usage

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#11894]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/10771, we are migrating the information saved in the `agent-group` files to `wazuh-db`. To do this a set of new commands and methods were implemented.
After analyzing the code, the below scenarios where the code should be refactored:
- **wdb_agent_belongs_first_time()** This method has the intention of reading the '**group**' column of the agent table and update the belongs table with its content. Now, we have a more complex mechanism that will read the agent-groups files and update all the groups information (**csv**, **belongs** and **hash**). The following methods and commands can be removed: **wdb_agent_belongs_first_time**, **wdb_update_agent_multi_group**, **wdb_update_agent_belongs**, **WDB_INSERT_AGENT_BELONG** command and its dependencies.
- **get_agent_group()** and **wdb_get_agent_group()** are 2 commands that overlap each other in functionality. **wdb_get_agent_group()** implies a more specific command that only requests for the agent group instead of the whole agent-info. This method should be used in **sync_keys_with_wdb()** and **lookfor_agent_group()**.
- **wdb_global_select_agent_group()** and **wdb_global_get_agent_group_csv()** use the same WDB_STMT_GLOBAL_GROUP_CSV_GET query and **wdb_global_select_agent_group** should replace **wdb_global_get_agent_group_csv()**
### Requirements

- [x] Remove all the deprecated code related to **wdb_agent_belongs_first_time()**.
- [x] Replace **get_agent_group()** with **wdb_get_agent_group()** usage.
- [x] Replace **wdb_global_get_agent_group_csv()** and **wdb_global_select_agent_group()** usage.

### Testing required

- [x] Create a set of tests using the script **WDB_tester.py** and upload the results in the PR.
- [x] Make manual tests of the changes.

### DoD

- [x] All the requirements should be implemented.
- [x] All the required tests should pass successfully.
- [x] The code review should be approved.
- [x] Scan-build execution without errors.
- [x] Valgrind execution during the execution of **WDB_tester.py** without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/11934 was merged.
