### ISSUE TITLE
Release 4.3.0 - Release Candidate 3 - WPK upgrade

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#11891]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|#11857|4.3.0|RC3|[v4.3.0-rc3](https://github.com/wazuh/wazuh/releases/tag/v4.3.0-rc3)|#11152|

## Auditors validation

In order to close and proceed with release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @santiago-bassett 
- [ ] @vikman90 
- [ ] @alberpilot

**Comment by TomasTurina** [comment]
# TEST: Ubuntu 20

## From Wazuh-Agent v3.13

### 🟡: UPGRADE FAIL  

- [] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [] ~Wazuh as service is enabled `chkconfig --list`~ 
- [] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [] Wazuh starts and connects automatically when the system is rebooted.
- [] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

### 🟡: UPGRADE OK

- [] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [] Service starts automatically after rebooting
- [] Agent connects to the manager after rebooting

**Comment by TomasTurina** [comment]
# TEST: openSUSE Tumbleweed

## From Wazuh-Agent v3.13

### :yellow_circle: UPGRADE FAIL  

- [] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [] ~Wazuh as service is enabled `chkconfig --list`~ 
- [] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [] Wazuh starts and connects automatically when the system is rebooted.
- [] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

### :yellow_circle: UPGRADE OK

- [] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [] Service starts automatically after rebooting
- [] Agent connects to the manager after rebooting

**Comment by Nicogp** [comment]
# TEST: CentOS 8

## From Wazuh-Agent v3.13

### 🟠 : UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [x] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

### 🟠 : UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[Downlod report]()



## From Wazuh-Agent v4.0.4
### 🟠 : UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [x] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

### 🟠 : UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[Downlod report]()


## From Wazuh-Agent v4.1.5

### 🟠 : UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [x] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

### 🟠 : UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting


[Download report]()

## From Wazuh-Agent v4.2.5
### 🟠 : UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

### 🟠 : UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[Downlod report]()

## From Wazuh-Agent v4.3 (same version)
### 🟠 : UPGRADE FAIL  

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [x] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

### 🟠: UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[Downlod report]()

**Comment by cborla** [comment]
# TEST: CentOS 6

## From Wazuh-Agent v4.2.5

###  :green_circle:UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

[initial_state.txt](https://github.com/wazuh/wazuh/files/7942688/initial_state.txt)
[final_state.txt](https://github.com/wazuh/wazuh/files/7942687/final_state.txt)


###  :green_circle: UPGRADE FAIL

- [] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [ ] ~The service was enabled (`systemctl is-enabled wazuh-agent.service`)~
- [] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [] Wazuh as service is enabled `chkconfig --list`
- [] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [] Wazuh starts and connects automatically when the system is rebooted.
