### ISSUE TITLE
New Condition for rootkit detection: none

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh#119]
Add an new condition "none" to the rootkit detection so these CIS-Files can be expanded with many more checks.

Example:
```
# 1.1.1.4 Ensure mounting of hfs filesystems is disabled (Scored)
[CIS - SLES11 - 1.1.1.4 - Initial Setup - Filesystem Configuration - Disable unused filesystems - Ensure mounting of hfs filesystems is disabled (Scored) {CIS: 1.1.1.4 SLES11}] [none] [https://benchmarks.cisecurity.org/tools2/linux/CIS_SUSE_Linux_Enterprise_Server_11_Benchmark_v2.0.0.pdf]
f:/etc/modprobe.conf.local -> !r:^# && r:\.*install\.+hfs\.+/bin/true;
d:/etc/modprobe.d -> .conf$ -> !r:^# && r:\.*install\.+hfs\.+/bin/true;
```

**Comment by Joeri-MS** [comment]
Till now i made 2 CIS file for the rootcheck with these new Option.
Here they are.

Based on CIS SUSE Linux Enterprise Server 11 v2.0.0
[cis_sles11_linux_rcl.txt](https://github.com/wazuh/wazuh/files/1018230/cis_sles11_linux_rcl.txt)

Based on CIS Red Hat Enterprise Linux 6 Benchmark v2.0.2
[cis_rhel6_linux_rcl.txt](https://github.com/wazuh/wazuh/files/1018229/cis_rhel6_linux_rcl.txt)

**Comment by vikman90** [comment]
Hi @Joeri-MS,

thank you very much for your contribution. We will review your PR code as soon as possible. I'm looking forward test your new condition and merge it. When we do it, I will invite you to do a PR with these rootcheck files to our ruleset repository.

Thank you again!
Best regards.

**Comment by Joeri-MS** [comment]
Thats sounds great. I'am also working on SLES 12 and RedHat 7 cis-rootchek files.
To generate these files i create an some CSV-Files wich i can use with LibeOffice and then convert it to these rcl-files..... (but that script is realy ugly.... but works).
