### ISSUE TITLE
Syscollector can't collect some inventory data on macOS

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1190]
![image](https://user-images.githubusercontent.com/10536251/44824102-224b3180-ac04-11e8-9e9e-8ab217323aff.png)

Syscollector does not report RAM or CPU.

![image](https://user-images.githubusercontent.com/10536251/44824110-2bd49980-ac04-11e8-8b0e-fb0d554b76e0.png)

Architecture and vendor

**Comment by chemamartinez** [comment]
Hi @vikman90,

I have fixed the ram issue (#1203) for mac OS agents, but other points have their own explanation:

- The CPU information consists of the CPU name, the number of cores and the current frequency of the CPU. The first two fields are the ones shown in the screenshot, the last one is not shown by a design choice (it is a volatile value for each scan).
- The package inventory is collected by reading the `Info.plist` file of each package, these files don't include the desired fields (architecture and vendor).
- In the list of mac OS X applications, typically located at `/Applications`, doesn't appear the Wazuh agent when it is installed.

We should look for a workaround for these points.
