### ISSUE TITLE
FIM DB development - Exploratory testing

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#11935]
### Description

The goal of this issue is to perform exploratory testing of the FIM capabilities after the changes included at #9103.

### Charter

- Test FIM baseline is correctly stored in the database
- Test FIM scan works in scheduled, real-time, and who-data (supported systems)
- Tests registry monitoring (Windows)
- Test FIM synchronization
  - Standard sync
  - Recovery when inconsistencies are detected
- Test retro compatibility with agent 4.2.5

### DoD

- [x] Manual testing in Ubuntu 20
- [x] Manual testing in Ubuntu 16
- [x] Manual testing in CentOS 8
- [x] Manual testing in CentOS 6
- [x] Manual testing in CentOS 5 (whodata not supported)
- [x] Manual testing in Solaris 10
- [x] Manual testing in Solaris 11
- [x] Manual testing in AIX
- [x] Manual testing in HP-UX
- [x] Manual testing in Windows
- [x] Manual testing in Windows Xp / Server 2003
- [x] Manual testing in macOS (In progress)

[FIM template](https://github.com/wazuh/wazuh-qa/blob/3.12/.github/ISSUE_TEMPLATE/test--fim.md) with more detailed use cases.

### How to test every OS

For each OS, we have to fill the following template and paste it in a comment:

**FIM DB exploratory testing template**

- OS: ______

- [ ] Compile the agent without warnings in FIM project

**Scan**
- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

**Synchronization**
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

The following sections will be tested in one Linux and Windows agent only.

**Retrocompatibility**

For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [x] The baseline is properly stored in the manager database
- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [x] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [x] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Rootcheck**
- [x] Run a rootcheck scan

Have the following into account when running the tests:
- Monitor the `ossec.log` looking for unexpected warnings/errors
- Enable debug for `syscheckd` to monitor every process is working as expected

**Comment by chemamartinez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Watchdogs-6039126e30fb7400140030e7/issues/wazuh/wazuh/11935?planning-poker) with ZenHub @Dwordcito @antoniomanuelfr @jotacarma90

**Comment by chemamartinez** [comment]
# Test macOS

- [ ] Compile the agent without warnings in FIM project

### Scan

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

### Retrocompatibility

For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by jotacarma90** [comment]
# Test ubuntu20
- [ ] Compile the agent without warnings in FIM project

### Scan

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

### Retrocompatibility

For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by jotacarma90** [comment]
# Test ubuntu16 agent
- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
 
### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by antoniomanuelfr** [comment]
# Test Windows

- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

### Synchronization

- [X] The sync process runs every interval
- [X] When databases are synced, the sync process is just a message with the checksum verification
- [X] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

### Retrocompatibility

For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by FrancoRivero** [comment]
**Solaris 11 Test**

- OS: Solaris 11

- [ ] Compile the agent without warnings in FIM project

**Scan**
- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [ ] Every alert has the correct fields
 - [ ] The database is properly updated for every change

**Synchronization**
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Retrocompatibility**
For this section install an agent 4.2.x and run the following tests. The goal is to verify the sync process before the development (in charge of FIM) is working with the manager after the change.
- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

Have the following into account when running the tests:
- Monitor the `ossec.log` looking for unexpected warnings/errors
- Enable debug for `syscheckd` to monitor every process is working as expected

**Comment by jotacarma90** [comment]
# Test CentOS 8 agent
- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
 
### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [ ] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by FrancoRivero** [comment]
# Test Solaris 10 agent

- [x] Compile the agent without warnings in FIM project

**Scan**
- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change

**Synchronization**
- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [x] Force an inconsistency by modifying an entry in the manager database. Check that the next sync restores the data.
- [x] Force an inconsistency by deleting the whole `fim_entry` table on the manager side. Check that the next sync restores the data

**Comment by jotacarma90** [comment]
# Test CentOS 5 agent
- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
 
### Synchronization

- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [x] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by jotacarma90** [comment]
# Test CentOS 6 agent
- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
 
### Synchronization

- [x] The sync process runs every interval
- [x] When databases are synced, the sync process is just a message with the checksum verification
- [x] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by jotacarma90** [comment]
# Retrocompatibility
Test old agents using a manager with [9103-replace-fim-db-dbsync](https://github.com/wazuh/wazuh/tree/9103-replace-fim-db-dbsync) branch.

### Windows 7 - Wazuh Agent 4.2.5

- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

### Ubuntu16 - Wazuh Agent 4.2.5

- [ ] The baseline is properly stored in the manager database
- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by chemamartinez** [comment]
# Test AIX agent
- [x] Compile the agent without warnings in FIM project

### Scan

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
 
### Synchronization

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by antoniomanuelfr** [comment]
# Test macOS

- [x] Compile the agent without warnings in FIM project

Warnings found during the package build:
[macOS-warnings.txt](https://github.com/wazuh/wazuh/files/8186400/macOS-warnings.txt)

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [X] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change

### Synchronization

- [X] The sync process runs every interval
- [X] When databases are synced, the sync process is just a message with the checksum verification

- [X] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by antoniomanuelfr** [comment]
# Test Windows XP
We found that after the FIMDB development, Wazuh couldn't start on Windows XP. Related issue https://github.com/wazuh/wazuh/issues/12718
- [x] Compile the agent without warnings in FIM project

### Scan

- [x] Run a baseline and check it is properly synced with the manager
- [x] Run a scheduled scan forcing an insertion/modification/deletion
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [x] Run a registry scan forcing an insertion/modification/deletion (for Windows only)
 - [x] Every alert has the correct fields
 - [x] The database is properly updated for every change

### Synchronization

- [X] The sync process runs every interval
- [X] When databases are synced, the sync process is just a message with the checksum verification
 Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by antoniomanuelfr** [comment]
# Test HP-UX  agent

- [x] Compile the agent without warnings in FIM project

**Scan**
- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change

**Synchronization**

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.
