### ISSUE TITLE
Disable Wazuh API from cluster worker nodes

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#11943]
## Description

We need to implement a mechanism to disable the Wazuh API from a manager if it is a worker node. It will reduce complexity for future developments and will not have any negative implications as distributed requests are executed by the cluster process.

Changing the cluster configuration to become a standalone manager will start the Wazuh API upon restart.

## Tasks

- [ ] Implement this new feature.
- [ ] Implement new system tests.

**Comment by davidjiglesias** [comment]
We are finally not approaching this change.
