### ISSUE TITLE
Wrong cluster logger tag in utils module when using multiprocessing

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#11941]
|Wazuh version|Component|
|---|---|
| 4.3+ | Wazuh cluster |

## Description
The logger instance used inside the `cluster.py` module is obtained like this:
https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/framework/wazuh/core/cluster/cluster.py#L25

However, this doesn't seem to work correctly for tasks that run inside a child process. For example, in the case of file compression on the master node, the task is delegated to a child process:
https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/framework/wazuh/core/cluster/master.py#L704-L706

```PYTHON
def compress_files(name, list_path, cluster_control_json=None):
    """...
    """
    logger.info(f"¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ TEST")
```

As we can see in the following logs, the message appears with the `Local Server` tag even though this is not true:
```
2022/01/25 10:10:51 INFO: [Worker worker1] [Integrity sync] Starting.
2022/01/25 10:10:51 INFO: [Worker worker1] [Integrity sync] Files to create in worker: 1 | Files to update in worker: 0 | Files to delete in worker: 0 | Files to receive: 0
2022/01/25 10:10:51 INFO: [Local Server] [Main] ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ TEST
```

The correct tag and the one that should still be shown is `Worker worker1` (the node from which the message was received), or in any case, `Main`: 
```
2022/01/25 10:11:55 INFO: [Worker worker1] [Integrity sync] Starting.
2022/01/25 10:11:55 INFO: [Worker worker1] [Integrity sync] Files to create in worker: 1 | Files to update in worker: 0 | Files to delete in worker: 0 | Files to receive: 0
2022/01/25 10:11:55 INFO: [Worker worker1] [Main] ¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡ TEST
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Wazuh---Framework-5d8b5184022c8d0001c05f4d/issues/wazuh/wazuh/11941?planning-poker) with ZenHub @AdriiiPRodri @Selutario @yanazaeva
