### ISSUE TITLE
Modify db.cpp and FIMDB to avoid use WIN32 flag inside c++ code

### ISSUE THREAD

**Issue by FrancoRivero** [wazuh/wazuh#11950]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

The goal of this issue is the development some changes to db.cpp and FIMDB class in order to avoid to compile  used the same files for Windows, Linux and other operating systems. It implies:

- [x] Modify initialization on FIMDB to select a different initialization for Windows without using WIN32 flag
- [x] Modify synchronization on FIMDB to select a different way for Windows without using WIN32 flag
- [x] Modify Cmake to avoid select the operating system
- [x] Modify test tool with the new implementation
- [x] Modify unit tests for FIMDB
- [x] Modify component tests in db.cpp 
- [x] Modify CMocka unit tests

**Comment by chemamartinez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Watchdogs-6039126e30fb7400140030e7/issues/wazuh/wazuh/11950?planning-poker) with ZenHub @FrancoRivero @antoniomanuelfr @jotacarma90
