### ISSUE TITLE
Engine MVP acceptance tests

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#11968]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager | - | - |

We need to prepare an environment to compare analysisd against the new engine to check if the overall design will give us what we need. Our acceptance test criteria are:

- [ ] The performance of the MVP and analysisd is similar or better for the MVP when achieving similar outputs
- [ ] The memory usage of the MVP does not grow over time when exercised during 1h-3h periods, and should be comparable to what analysisd uses.
- [ ] The MVP does support the decoding graphs which can be made in the analisysd and more.

We will:
- [x] Create a set of decoders and rules which make analisysd and the new engine behave similarly.
- [ ] Prepare a dataset to be processed by those decoders and rules. 
- [x] Take performance measures while ingesting the data set, in order check the acceptance test criteria
- [x] Create scripts which will automate running these tests regularly in our development environment.

These tests do not pretend to measure the production performance, but the distance between what we have in production now and what we're building.

For each scenario, we need to measure:
* Time to process a given number of events in a given machine (in seconds)
* Memory used while processing (each second)
* CPU used while processing (in % of core-time used)

And we need to implement three scenarios:
* pass-through scenario, a single decoder and a single rule does nothing and the event reach the output file, with an event size of about 512 bytes.
* Light processing scenario: decoder add a field and rule add another field, and the event reach the output file, with an event size of about 1024 bytes.
* Medium processing scenario: same as light scenario, but with big events (10kb)

Events and decoders should be synthetic. We want to be able to pinpoint our bottlenecks and issues quickly.

**Comment by juliancnn** [comment]
## [RESULTS HERE](https://github.com/wazuh/wazuh/pull/12049#issuecomment-1032999925) in the PR
