### ISSUE TITLE
Change exception raised when agent is not active in PUT /agents/reconnect endpoint

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11973]
Right now, the `PUT /agents/reconnect` endpoint is returning a wrong error when an agent of the agent list we want to reconnect is not active.

```
# curl -k -X PUT "https://localhost:55000/agents/reconnect?agents_list=002&prety=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [],
      "total_affected_items": 0,
      "total_failed_items": 1,
      "failed_items": [
         {
            "error": {
               "code": 1757,
               "message": "Error deleting an agent",
               "remediation": "Please check all data fields and try again"
            },
            "id": [
               "002"
            ]
         }
      ]
   },
   "message": "Force reconnect command was not sent to any agent",
   "error": 1
}
```

The right error code should be 1707 and therefore, the whole exception is wrong. We should review the exception raised here. We used to have more than one exceptions to tell the agent to do the specific action is not active. When all the exceptions were unified, this one (1757) was left without any modifications. Consider reviewing all endpoints to see if there is any other "agent not active" exception to be unified.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update

This development is almost done, I'm currently reviewing several endpoints to verify its proper exception handling.
