### ISSUE TITLE
No error is thrown when "<alerts_log>" "<jsonout_output>" tag is missing in Ossec configuration file

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#1198]
If the following configuration variables do not exist in the `ossec.conf` file on the manager, it doesn't log any error. `Ossec-control` also starts without problems.
```

<jsonout_output>...</jsonout_output>
    <alerts_log>...</alerts_log>
    <logall>...</logall>
    <logall_json>...</logall_json>

```
This causes Wazuh does not generate any alerts.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/1208 solves the issue
