### ISSUE TITLE
what happened?

### ISSUE THREAD

**Issue by ckozler** [wazuh/wazuh#1199]
- disregard -

**Comment by jesuslinares** [comment]
Hi @ckozler,

Please, let us know how we can help you.

Thanks.

**Comment by ckozler** [comment]
Issue has been resolved. Thanks!

**Comment by jesusgn90** [comment]
Ok @ckozler , in any case feel free to share your error, it always helps our community, but it's not mandatory of course. And regarding to the issue itself, I'm going to close it since you said it's solved.

Regards!
