### ISSUE TITLE
The global.db didn't initialize

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#1200]
Hello, Team

I upgrade a host from wazuh agent to manager(server) and make it a client(cluster worker@3.6). But I failed to start `./cluster_control`. 

The Exception message
Error 2000 - No such database file.

Follow the stacktrace I found that the `/var/ossec/var/db/global.db` didn't exist.  

And the message changed to:
Error 2003 - Error in database request: no such table: info

I think there should be a migration process here. Have I never had a correct step?
Can I upgrade a server from 3.1, 3.2, 3.3?

Best Regards,
Aklis Chen

**Comment by Skeptor** [comment]
Hello @iAklis 
Sorry for the late response,

I have been trying to reproduce the error, but when I install a manager over an agent, the `global.db` is created and the manager is working fine.
My OS is Ubuntu 18.04 and the agent and manager I installed are version `3.6`.
In case you still have access to the environment, could you please give me more info on the issue? 
I will be pleased to help you.

Best Regards,
Pablo.

**Comment by Skeptor** [comment]
Hi.

I will guess that the problem is solved. Feel free to post your questions/issues and thanks for using Wazuh.

Regards,
Pablo.
