### ISSUE TITLE
Decoder 0380-windows_decoders.xml Whith Sintaxe Error

### ISSUE THREAD

**Issue by oliveiralive** [wazuh/wazuh#12039]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2 | Decoders | Sintaxe Error |

## Description

The Decoder 0380-windows_decoders.xml have a problem, when we create a FTP server on windows, we need to put a name for this server, and the name can be anyone, but in decoder is waiting the name **MSFTPSVC**, for this reason, the decoder did not catch the event, after the change like below the FTP events start to work

```
**OLD**
<decoder name="msftp">
  <parent>windows-date-format</parent>
  <use_own_name>true</use_own_name>
  <prematch offset="after_parent">^\S+ \S+ MSFTPSVC</prematch>
  <regex offset="after_parent">^(\S+) (\S+) \S+ \S+ \S+ </regex>
  <regex>\d+ [\d+](\S+) \S+ \S+ (\d+) </regex>
  <order>srcip,user,action,id</order>
</decoder>
 
**FIXED**
<decoder name="msftp">
  <parent>windows-date-format</parent>
  <use_own_name>true</use_own_name>
  <prematch offset="after_parent">^\d+.\d+.\d+.\d+ \S+ \S+</prematch>
  <regex offset="after_parent">^(\d+.\d+.\d+.\d+) (\S+) \S+ \S+ \S+ </regex>
  <regex>\S+ \S+ (\S+) \S+ \S+ (\S+) </regex>
  <order>srcip,user,action,id</order>
</decoder>
```

I use this documentation for change the decoder
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

### Log examples

In this log exemplo we can see the service name is **FTPSVC2**
21:43:11 177.177.177.11 - FTPSVC2 172.20.20.250 21 USER emerson.test 331 0 0 caddc07e-638f-42eb-a370-b41d50faeb83 - -
2022-01-22 21:49:28 177.177.177.11  WIN-P08E5P97VH4\braga.boy FTPSVC2 172.20.20.250 21 QUIT - 221 0 0 81280663-7883-46f8-9c26-02057d89b0e2 - -

**Comment by juliancnn** [comment]
Hi @oliveiralive,
Thank you very much for your contribution, this helps us to improve Wazuh every day.

I think the problem is a bit more complex as the decoder you share is very generic (One ip followed by 2 words) and could cause unwanted behavior if incorporated in the default ruleset as it could capture logs that it should not.

I have tested the default FTP server configuration in windows 2012R2 and it does not add the service name or host name:

```
...
...
2022-01-31 16:28:41 ::1 - ::1 21 ControlChannelOpened - - 0 0 da30c321-a988-4dd7-8dfc-26c8c88836be -
2022-01-31 16:28:41 ::1 - ::1 21 USER qweqwe 331 0 0 da30c321-a988-4dd7-8dfc-26c8c88836be -
2022-01-31 16:28:41 ::1 - ::1 21 PASS *** 530 1326 41 da30c321-a988-4dd7-8dfc-26c8c88836be -
2022-01-31 16:28:41 ::1 - ::1 21 ControlChannelClosed - - 0 0 da30c321-a988-4dd7-8dfc-26c8c88836be -
```
Then I edited the configuration (following [this microsoft documentation](https://docs.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/ftpserver/logfile)) and added the service name:

![image](https://user-images.githubusercontent.com/1891958/151846756-4af9a583-07a3-4115-962f-d3c623a3509d.png)

Then the logs have a new format (The service name before IPv4/IPv6): 

```
#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2022-01-31 16:30:15
#Fields: date time c-ip cs-username s-sitename s-ip s-port cs-method cs-uri-stem sc-status sc-win32-status sc-substatus x-session x-fullpath
2022-01-31 16:30:15 ::1 - - ::1 21 ControlChannelOpened - - 0 0 9bc09de0-68df-4c33-8a8b-0ba7dd5dcf12 -
2022-01-31 16:30:15 ::1 - FTPSVC1 ::1 21 USER qweqwe 331 0 0 9bc09de0-68df-4c33-8a8b-0ba7dd5dcf12 -
2022-01-31 16:30:15 ::1 - FTPSVC1 ::1 21 PASS *** 530 1326 41 9bc09de0-68df-4c33-8a8b-0ba7dd5dcf12 -
2022-01-31 16:30:15 ::1 - FTPSVC1 ::1 21 ControlChannelClosed - - 0 0 9bc09de0-68df-4c33-8a8b-0ba7dd5dcf12 -
```

Looking at the possibility of format changes and possible changes I think the best option at this time is to use your decoder but be aware that the decoder may match a log that does not correspond to that type in the future.

We will work together with the threat-intel team to improve or find a better solution to this problem.

Regards,
Julian

**Comment by oliveiralive** [comment]
Hi @juliancnn , thanks for your time.
Realy, its nessessary to add the service name in the FTP Windows configuration, i believe that one way to resolved this question is create a documentation in the page "learning wazuh exemples"
https://documentation.wazuh.com/current/learning-wazuh/index.html

I wold like to document that i too need the includ this lines in wazuh agent configurations
```
  <localfile>
    <location>C:\inetpub\logs\LogFiles\FTPNAME\u_ex%y%m%d%.log</location>
    <log_format>iis</log_format>
  </localfile>
```

**Comment by oliveiralive** [comment]
Hi Team, i found another sintaxe error on the same decoder "0380"

The Alert "Multiple web server 400 error codes from same source ip" did not work because it's missing a space between this expressions \.* (\d\d\d) the decoder.

it was necessary to adjust to be the same below

<decoder name="web-accesslog-iis-default">
  <parent>windows-date-format</parent>
  <type>web-log</type>
  <use_own_name>true</use_own_name>
  <prematch offset="after_parent">^\S+ GET |^\S+ POST</prematch>
  <regex offset="after_parent">^\S+ (\w+) (\S+ \S+) (\S+) \S+ (\S+) (\S+) \.* (\d\d\d) </regex>
  <order>action, url, srcport, srcip, user_agent, id</order>
</decoder>

**Comment by juliancnn** [comment]
Hi @oliveiralive ,

The regex `\.* (\d\d\d)` and `\.* (\d\d\d)` work the same for this case. This is because "`\.`" includes the space "` `", so the "`*`"multiplier implies that it can be any character.
Here is an example of the default decoder running with 2 example logs:

```
╰─# /var/ossec/bin/wazuh-logtest                                                                                                                                                                                
Starting wazuh-logtest v4.3.0
Type one log per line

2015-03-11 20:28:21 1.2.3.4 GET /certsrv/Default.asp - 80 - 31.3.3.7 Mozilla/5.0+(compatible;+MSIE+9.0;+Windows+NT+6.1;+WOW64;+Trident/7.0) - 401 2 5 0
2015-03-11 21:59:09 1.2.3.4 GET /console/faces/c
om_sun_web_ui/jsp/version/version_30.jsp - 80 - 31.3.3.7 Sun+Web+Console+Fingerprinter/7.15 - 404 0 2 0
2015-03-11 22:01:58 1.2.3.4 GET /IISADMPWD/aexp.htr - 80 - 31.3.3.7 - - 404 0 2 0**Phase 1: Completed pre-decoding.
        full event: '2015-03-11 20:28:21 1.2.3.4 GET /certsrv/Default.asp - 80 - 31.3.3.7 Mozilla/5.0+(compatible;+MSIE+9.0;+Windows+NT+6.1;+WOW64;+Trident/7.0) - 401 2 5 0'

**Phase 2: Completed decoding.
        name: 'web-accesslog-iis-default'
        parent: 'windows-date-format'
        action: 'GET'
        id: '401'
        srcip: '31.3.3.7'
        srcport: '80'
        url: '/certsrv/Default.asp -'
        user_agent: 'Mozilla/5.0+(compatible;+MSIE+9.0;+Windows+NT+6.1;+WOW64;+Trident/7.0)'

**Phase 3: Completed filtering (rules).
        id: '31101'
        level: '5'
        description: 'Web server 400 error code.'
        groups: '['web', 'accesslog', 'attack']'
        firedtimes: '1'
        gdpr: '['IV_35.7.d']'
        mail: 'False'
        nist_800_53: '['SA.11', 'SI.4']'
        pci_dss: '['6.5', '11.4']'
        tsc: '['CC6.6', 'CC7.1', 'CC8.1', 'CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
**Alert to be generated.


**Phase 1: Completed pre-decoding.
        full event: '2015-03-11 21:59:09 1.2.3.4 GET /console/faces/com_sun_web_ui/jsp/version/version_30.jsp - 80 - 31.3.3.7 Sun+Web+Console+Fingerprinter/7.15 - 404 0 2 0'

**Phase 2: Completed decoding.
        name: 'web-accesslog-iis-default'
        parent: 'windows-date-format'
        action: 'GET'
        id: '404'
        srcip: '31.3.3.7'
        srcport: '80'
        url: '/console/faces/com_sun_web_ui/jsp/version/version_30.jsp -'
        user_agent: 'Sun+Web+Console+Fingerprinter/7.15'

**Phase 3: Completed filtering (rules).
        id: '31101'
        level: '5'
        description: 'Web server 400 error code.'
        groups: '['web', 'accesslog', 'attack']'
        firedtimes: '2'
        gdpr: '['IV_35.7.d']'
        mail: 'False'
        nist_800_53: '['SA.11', 'SI.4']'
        pci_dss: '['6.5', '11.4']'
        tsc: '['CC6.6', 'CC7.1', 'CC8.1', 'CC6.1', 'CC6.8', 'CC7.2', 'CC7.3']'
**Alert to be generated.

```

Fo you have example logs where this decoder does not work but the one you have created does? This will help to know if it is a bug.

Thanks

**Comment by oliveiralive** [comment]
Hello @juliancnn 
I dont know why, but all tests work now, sorry for your time,

I will close this ticket,
Thank you so mutch
