### ISSUE TITLE
[4.3.0][RC3] Research handle increase on Windows agent

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#12038]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-RC3 | Vulnerability-detector/Syscollector | Agent | Packages | Windows Server 2019 |

Hello!

We have detected a handle increase when vulnerability-detector + Syscollector are enabled on Windows agent.
![image](https://user-images.githubusercontent.com/10661307/151794848-445dd10d-f9af-41e6-8813-f4a9056d29aa.png)
We need to research why this increase is produced.

All related configurations and logs can be found here https://github.com/wazuh/wazuh/issues/11917

**Comment by vikman90** [comment]
If we compare this chart with the same test in RC2 (#https://github.com/wazuh/wazuh/issues/11679):

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B2321-3600m/B2321_agent_windows/plots/monitor-winagent-Test_stress_B2321_windows-pre-release_Handles.png)

The ceil of both charts is 278 handles, but in RC3 the count grows more stepwise than in RC2.

Rises appear during some (but not all) Syscollector scans:

### RC2

|Scan date|Behaviour|
|---|---|
|2021/12/31 22:22:43|Grows +1|
|2022/01/01 10:22:38|Constant|
|2022/01/01 22:22:32|Constant|
|2022/01/02 10:22:26|Grows +2|
|2022/01/02 22:22:21|Constant|

### RC3

|Scan date|Behaviour|
|---|---|
|2022/01/21 22:25:59|Grows +1|
|2022/01/22 10:25:59|Grows +1|
|2022/01/22 22:25:59|Grows +1|
|2022/01/23 10:25:59|Constant|
|2022/01/23 22:25:58|Grows +1|

**Comment by rauldpm** [comment]
Requested tests:

- Modules: Vulnerability-Detector + Custom syscollector (interval from 12h to 1m)
- Duration: 3600m
- The results will be added as a comment to this issue
- Jenkins branch: `stress_test_custom_syscollector`
- https://ci.wazuh.info/view/Tests/job/Test_stress/3019/

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #11857                                         |
| **Main footprint metrics issue #** | #11898                                         |
| **Version** | 4.3.0                                      |
| **Release candidate #** | RC3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.0-rc3 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/3019/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/monitor-manager-Test_stress_B3019_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/Test_stress_B3019_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/Test_stress_B3019_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/plots/Test_stress_B3019_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3019_manager_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/logs/ossec_Test_stress_B3019_manager_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B3019_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/data/monitor-manager-Test_stress_B3019_manager-pre-release.csv)
[Test_stress_B3019_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/data/Test_stress_B3019_manager_analysisd_state.csv)
[Test_stress_B3019_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_manager_centos/data/Test_stress_B3019_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/monitor-agent-Test_stress_B3019_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/Test_stress_B3019_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/Test_stress_B3019_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/Test_stress_B3019_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/plots/Test_stress_B3019_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3019_centos_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/logs/ossec_Test_stress_B3019_centos_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B3019_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/data/monitor-agent-Test_stress_B3019_centos-pre-release.csv)
[Test_stress_B3019_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_centos/data/Test_stress_B3019_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/monitor-agent-Test_stress_B3019_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/Test_stress_B3019_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/Test_stress_B3019_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/Test_stress_B3019_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/plots/Test_stress_B3019_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3019_ubuntu_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/logs/ossec_Test_stress_B3019_ubuntu_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B3019_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/data/monitor-agent-Test_stress_B3019_ubuntu-pre-release.csv)
[Test_stress_B3019_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_ubuntu/data/Test_stress_B3019_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/monitor-winagent-Test_stress_B3019_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/Test_stress_B3019_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/Test_stress_B3019_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/Test_stress_B3019_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/plots/Test_stress_B3019_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3019_windows_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/logs/ossec_Test_stress_B3019_windows_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B3019_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/data/monitor-winagent-Test_stress_B3019_windows-pre-release.csv)
[Test_stress_B3019_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.0/B3019-3600m/B3019_agent_windows/data/Test_stress_B3019_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by vikman90** [comment]
Thanks @rauldpm!

The new chart shows the handle count is stable:

![](https://camo.githubusercontent.com/83d5b681db93a2bea150184e296c3fc6b241fbacf5a7e141032423a2d973f1fc/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e332e302f42333031392d333630306d2f42333031395f6167656e745f77696e646f77732f706c6f74732f6d6f6e69746f722d77696e6167656e742d546573745f7374726573735f42333031395f77696e646f77732d7072652d72656c656173655f48616e646c65732e706e67)
