### ISSUE TITLE
Alert/archive output file based on defined criteria

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#12047]
Hello team,

It would be useful if the analysis engine can generate different alert/archive files based on defined criteria. For instance,
being able to generate different alert files based on the alert label can help to define different retention periods depending on the source of information.

This could be included as a new configuration on the Wazuh manager node. For example:

```
<global>
...
    <field match="agent.labels.group">PCI</field>
    <logging_file_path>alerts-pci</logging_file_path>
...
</global
```

Regards,

Miguel Casares

**Comment by gdiazlo** [comment]
The new engine will support this natively. 
- https://github.com/wazuh/wazuh/issues/11339
