### ISSUE TITLE
Solve several warnings during project compilation

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#12045]
|Related issue|
|---|
|#5321|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Compilation process | Manager/Agent | Sources | - |

Hi team!

It would be great to solve the compilation warnings in order to detect and solve potential critical issues while enhancing product quality.

| Warnings survey | Issue |
|----------------------  | ------- |
| Wazuh manager | #12098 |
| Wazuh winagent | #12099 |
| Wazuh agent | #12100 |

Regards,
Nico

**Comment by jnasselle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/12045?planning-poker) with ZenHub @RamiroRD @HanesSciarrone

**Comment by HanesSciarrone** [comment]
Summary of the number of warnings for each type of compilation

| Type | Warnings |
| ------ | ------------- |
| WinAgent | 51 |
| Agent | 45 | 
| Manager | 83 |
