### ISSUE TITLE
Research Modulesd RSS growth on macOS

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#12055]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc3 | Modulesd | Agent | Packages | macOS |

After running the tests at #11928, we've observed a suspicious RSS memory growth in Modulesd:

![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B96-3600m/B96_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B96_macos_agent-pre-release_RSS.png)

We need to:
- Figure out which module is causing this behavior.
- Check if memory usage reaches a ceiling.

**Comment by vikman90** [comment]
As commented at https://github.com/wazuh/wazuh/issues/11928#issuecomment-1024242769, the growth of the memory usage on macOS must be due to the SCA scans, according to the logs. Although memory usage seems to go up uncontrollably, it seems to converge at ~82 MB.

We monitored a system performing 238 SCA scans with a 50-second interval, and this is the memory usage chart during 3:25 hours:

![image](https://user-images.githubusercontent.com/10536251/151590021-bbfba92a-467c-41a9-8583-f17d5f5eb310.png)

- [modulesd_rss.csv](https://github.com/wazuh/wazuh/files/7960523/modulesd_rss.csv)

## Next task

Relaunch the test above, increasing the SCA scan frequency to one per minute.

**Comment by rauldpm** [comment]
Requested tests:

- Modules: ALL-except-VD and osquery in solaris (sca interval from 12h to 1m)
- The results will be added as a comment to this issue
- Jenkins branch: `stress_test_macos_wazuh_12055 `
- [1d] https://ci.wazuh.info/view/Tests/job/Test_stress_Vagrant/33/
- [2d] https://ci.wazuh.info/view/Tests/job/Test_stress_Vagrant/34/

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #11857                                         |
| **Main footprint metrics issue #** | #11898                                         |
| **Version** | 4.3.0                                      |
| **Release candidate #** | RC3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.0-rc3 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/35/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/Test_stress_Vagrant_B35_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/Test_stress_Vagrant_B35_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/plots/Test_stress_Vagrant_B35_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B35_manager_2022-02-02.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/logs/ossec_Test_stress_Vagrant_B35_manager_2022-02-02.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B35_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/data/monitor-manager-Test_stress_Vagrant_B35_manager-pre-release.csv)
[Test_stress_Vagrant_B35_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/data/Test_stress_Vagrant_B35_manager_analysisd_state.csv)
[Test_stress_Vagrant_B35_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_manager_centos/data/Test_stress_Vagrant_B35_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/Test_stress_Vagrant_B35_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/Test_stress_Vagrant_B35_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/Test_stress_Vagrant_B35_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/plots/Test_stress_Vagrant_B35_macos_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B35_macos_2022-02-02.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/logs/ossec_Test_stress_Vagrant_B35_macos_2022-02-02.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/data/monitor-agent-Test_stress_Vagrant_B35_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B35_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_macos/data/Test_stress_Vagrant_B35_macos_agent_agentd_state.csv)



    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/Test_stress_Vagrant_B35_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/Test_stress_Vagrant_B35_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/Test_stress_Vagrant_B35_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/plots/Test_stress_Vagrant_B35_solaris_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B35_solaris_2022-02-02.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/logs/ossec_Test_stress_Vagrant_B35_solaris_2022-02-02.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B35_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B35_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B35-1440m/B35_agent_solaris/data/Test_stress_Vagrant_B35_solaris_agent_agentd_state.csv)



    </details>

</details>

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #11857                                         |
| **Main footprint metrics issue #** | #11898                                         |
| **Version** | 4.3.0                                      |
| **Release candidate #** | RC3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.0-rc3 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/36/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/Test_stress_Vagrant_B36_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/Test_stress_Vagrant_B36_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/plots/Test_stress_Vagrant_B36_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B36_manager_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/logs/ossec_Test_stress_Vagrant_B36_manager_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B36_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/data/monitor-manager-Test_stress_Vagrant_B36_manager-pre-release.csv)
[Test_stress_Vagrant_B36_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/data/Test_stress_Vagrant_B36_manager_analysisd_state.csv)
[Test_stress_Vagrant_B36_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_manager_centos/data/Test_stress_Vagrant_B36_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/Test_stress_Vagrant_B36_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/Test_stress_Vagrant_B36_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/Test_stress_Vagrant_B36_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/plots/Test_stress_Vagrant_B36_macos_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B36_macos_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/logs/ossec_Test_stress_Vagrant_B36_macos_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/data/monitor-agent-Test_stress_Vagrant_B36_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B36_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_macos/data/Test_stress_Vagrant_B36_macos_agent_agentd_state.csv)



    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/Test_stress_Vagrant_B36_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/Test_stress_Vagrant_B36_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/Test_stress_Vagrant_B36_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/plots/Test_stress_Vagrant_B36_solaris_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B36_solaris_2022-02-04.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/logs/ossec_Test_stress_Vagrant_B36_solaris_2022-02-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B36_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B36_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.0/B36-3600m/B36_agent_solaris/data/Test_stress_Vagrant_B36_solaris_agent_agentd_state.csv)



    </details>

</details>

**Comment by vikman90** [comment]
Thanks, @rauldpm. The new test chart is compatible with my research:

![](https://camo.githubusercontent.com/645371de437736555bc166d2cd528c00dbe4cdc12c4db58175a37668324d4b7d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e332e302f4233362d333630306d2f4233365f6167656e745f6d61636f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f56616772616e745f4233365f6d61636f735f6167656e742d7072652d72656c656173655f5253532e706e67)

Despite the first few scans increase the RSS, the memory usage keeps stable later. This reveals a fragmentation problem (addressed at #10107), but there are no memory leaks according to this data.
