### ISSUE TITLE
Encrypt rotated alert and archive files

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#12050]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | - | Manager | - | - |

Hi team,

Right now, the archive and alert files are rotated to a compressed file but they are not encrypted for greater security.

![image](https://user-images.githubusercontent.com/73501120/151865085-1269b52e-73f6-4b14-a52a-8859daac78d1.png)

It would be very useful if the possibility to encrypt alerts and archive files was added as part of the Wazuh manager configuration.

Thank you in advance!

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
