### ISSUE TITLE
Create SCA Policy for  Alibaba Cloud Linux (Aliyun Linux) 2

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#12052]
|Wazuh version| Component | Action type |
|---| --- | --- |
| master | SCA | New |

CIS `Aliyun Linux 2` Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228) was published
on Aug 16th, 2019. `Aliyun Linux 2` is compatible with `Centos 7` and it's
further renamed as `Alibaba Cloud Linux 2`. Besides, The ID of `Alibaba
Cloud Linux (Aliyun Linux) 2` in /etc/os-release is `alinux`

I add the `Alibaba Cloud Linux (Aliyun Linux) 2` SCA in the wazuh
according to CIS `Aliyun Linux 2` Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/2228)

**Comment by hustliyilin** [comment]
I open pr #11875 to add the Alibaba Cloud Linux (Aliyun Linux) 2 CIS SCA

**Comment by 72nomada** [comment]
Hi @hustliyilin, we will include this CIS SCA support in our 4.4.0 version. We will come back to you if we have any questions about your PR. 
Thanks so much.

**Comment by hustliyilin** [comment]
> Hi @hustliyilin, we will include this CIS SCA support in our 4.4.0 version. We will come back to you if we have any questions about your PR. Thanks so much.

Hi @72nomada,

Thank you very much for your reply.  There are many customers who hope to support this CIS SCA function of our own OS (`Alibaba Cloud Linux (Aliyun Linux) 2`).  I also hope to be able to recommend `wazuh` to my customers.

**Comment by hustliyilin** [comment]
> Hi @hustliyilin, we will include this CIS SCA support in our 4.4.0 version. We will come back to you if we have any questions about your PR. Thanks so much.

Hi @72nomada ,

It has been a long time since your last reply.  I noticed that Wazuh 4.3.0 has been released and I guess Wazuh 4.4.0 should be the next release version. You said that you would include this CIS SCA support in the 4.4.0 version. I would be very grateful if you could give some reviews.

Thanks @72nomada , I look forward to your reply.

**Comment by 72nomada** [comment]
Hi @hustliyilin, 4.4.0 will be the next release with many SCA updates, including the ones here. I will keep this updated... We are still with the 4.3.x release.

**Comment by hustliyilin** [comment]
> Hi @hustliyilin, 4.4.0 will be the next release with many SCA updates, including the ones here. I will keep this updated... We are still with the 4.3.x release.

Hi @72nomada ,

Thanks you very much !

**Comment by hustliyilin** [comment]
Hi @72nomada  #11875 is the PR for this issue, I would be very grateful if you could give some review suggestions.

**Comment by 72nomada** [comment]
Hi, we will, it is planned for the next major.

**Comment by hustliyilin** [comment]
> Hi, we will, it is planned for the next major.

Hi @72nomada，

Thanks for your reply. Do you mean you plan to include this CIS SCA support in the Wazuh 4.5.0?  And when will Wazuh 4.5.0 be released？ Besides， What else do I need to do?  Thanks a lot.

**Comment by hustliyilin** [comment]
Close it now.
