### ISSUE TITLE
syscheckd - unexpected message after recording a change to the file

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#12070]
|Wazuh version|Component|
|---|---|
| 4.25| Syscheck |

Hello Wazuh Team,

I struggle with odd error in debug mode for file

```
  <syscheck>
    <disabled>no</disabled>
    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>43200</frequency>
    <scan_on_start>yes</scan_on_start>
    <!-- Directories to check  (perform all possible verifications) -->
    <directories report_changes="yes" realtime="yes">/etc/sudoers</directories>**
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
  </syscheck>
```
Step 1:
1. Enable debug 2 in wazuh-agent in internal_options.conf and set syscheck.debug to 2, then write and close file
next
1. Open visudo
2. Add some new line
3. write changes
4. quit from visudo

After completing these steps, in the /var/ossec/logs/ossec.conf log I can see that the change has been noticed, but after generating it I get the following message:
`
wazuh-syscheckd[15684] run_realtime.c:182 at realtime_process(): DEBUG: (6344): Inotify watch deleted for '/etc/sudoers'
`

I want to emphasize the fact that neither the "/etc/sudoers" nor "/etc" files were deleted

**Comment by FrancoRivero** [comment]
Hi @mradaszewski92, how are you?
Thank you for using Wazuh.
Could you share me your configuration, OS? 
I will try to reproduce this error to analyze if this is a bug or not.
Regards

**Comment by FrancoRivero** [comment]
Closed I cannot reproduce this bug !
