### ISSUE TITLE
Error adding permissions to json alert file in syscheck stress test 4.3.0-rc3

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#12073]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-rc3 | wazuh-analysisd | Manager | Packages | Centos8 |

Analyzing the [Syscheck stress test result](https://github.com/wazuh/wazuh/issues/12007), I have found the following error in the manager log, which is repeated up to 92 times during the test:

```
wazuh-analysisd: ERROR: The new permissions could not be added to the JSON alert.
```

This error has been reported by @Phandora for 4.1.5 from a community and in this google groups thread: https://groups.google.com/g/wazuh/c/ZpNhlU0IDJg (4.1.2)

This bug was attempted to be fixed at https://github.com/wazuh/wazuh/issues/8312 in 4.2

**Comment by rauldpm** [comment]
### Update report

Launched 4h stress test of syscheck module with manager logall enabled (launched manager+windows agent) 

- https://ci.wazuh.info/view/Tests/job/Test_stress/3268/

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #12073                                         |
| **Main footprint metrics issue #** | #12073                                         |
| **Version** | 4.3.4                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.4-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/3270/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/monitor-manager-Test_stress_B3270_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/Test_stress_B3270_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/Test_stress_B3270_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/plots/Test_stress_B3270_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3270_manager_2022-06-13.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/logs/ossec_Test_stress_B3270_manager_2022-06-13.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B3270_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/data/monitor-manager-Test_stress_B3270_manager-pre-release.csv)
[Test_stress_B3270_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/data/Test_stress_B3270_manager_analysisd_state.csv)
[Test_stress_B3270_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_manager_centos/data/Test_stress_B3270_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/monitor-winagent-Test_stress_B3270_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/Test_stress_B3270_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/Test_stress_B3270_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/Test_stress_B3270_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/plots/Test_stress_B3270_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3270_windows_2022-06-13.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/logs/ossec_Test_stress_B3270_windows_2022-06-13.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B3270_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/data/monitor-winagent-Test_stress_B3270_windows-pre-release.csv)
[Test_stress_B3270_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.3.4/B3270-240m/B3270_agent_windows/data/Test_stress_B3270_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.4.0                                      |
| **Release candidate #** | RC                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.4.0-rc |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-pullrequests`
- Package revision: `0.commit950a5c8`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/3296/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/Test_stress_B3296_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/Test_stress_B3296_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/plots/Test_stress_B3296_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3296_manager_2022-06-24.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/logs/ossec_Test_stress_B3296_manager_2022-06-24.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/data/monitor-manager-Test_stress_B3296_manager-warehouse-pullrequests.csv)
[Test_stress_B3296_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/data/Test_stress_B3296_manager_analysisd_state.csv)
[Test_stress_B3296_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_manager_centos/data/Test_stress_B3296_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/Test_stress_B3296_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/Test_stress_B3296_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/Test_stress_B3296_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/plots/Test_stress_B3296_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3296_windows_2022-06-24.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/logs/ossec_Test_stress_B3296_windows_2022-06-24.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/data/monitor-winagent-Test_stress_B3296_windows-warehouse-pullrequests.csv)
[Test_stress_B3296_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.4.0/B3296-240m/B3296_agent_windows/data/Test_stress_B3296_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>
