### ISSUE TITLE
Segfault during a failed Global DB upgrade after database restoration. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#12104]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0| Wazuh-DB | Manager | Packages/Sources | Linux |

# Description
As part of the implementation of #10771 while applying the upgrade schemas for global DB there's a mechanism that restores the DB in case some of those schemas fail. 
 Prior to being restored, the database is closed and removed from the pool. So trying to access after it, causes a SEGFAULT.

![image](https://user-images.githubusercontent.com/13010397/152544022-4228ae62-c19a-4c7f-8081-1808a03f4e8a.png)
![2](https://user-images.githubusercontent.com/13010397/152542131-47a63165-b803-406a-8879-079e34bd0abb.png)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/12111 was merged.
