### ISSUE TITLE
Alerts are generated without the "agent.name" field

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#1212]
After upgrading to Wazuh v3.6.0, the alerts are not containing the `agent.name` field and this has broken some of the visualizations on the Wazuh app.

![bug](https://user-images.githubusercontent.com/10928321/44971258-2e612700-af55-11e8-9284-dec53e4baa05.png)

Regards,
Juanjo

**Comment by vikman90** [comment]
Related comment in Wazuh Lists: [Wazuh Lists/dtsrwCt979I](https://groups.google.com/forum/#!topic/wazuh/dtsrwCt979I).
