### ISSUE TITLE
The new Wazuh-DB backup mechanism doesn't create a backup at startup

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#12128]
### Description

During the development of https://github.com/wazuh/wazuh/issues/10771, a new backup mechanism was created for **global.db**. It was found that if a previous snapshot isn't found, the thread waits the whole `<interval>` time to create the first one.

This isn't the expected behavior and should be fixed.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/12129 was merged.
