### ISSUE TITLE
Bad FSTAB option in Linux Security configuration assessment

### ISSUE THREAD

**Issue by ThomasVIDALUBS** [wazuh/wazuh#12146]
|Wazuh version|Component|
|---|---|
|4.2.5 | Wazuh component |

When looking to Wazuh -> Security configuration assessment -> Linux server
I found an advice of using a specific /tmp partition and to setup it in fstab like
"Configure /etc/fstab as appropriate. Example: tmpfs /tmp tmpfs defaults,rw,nosuid,nodev,noexec,realtime 0 0 ....

FSTAB option is not REALTIME but RELATIME !
With this advice the server won(t be able to boot on the next reboot.....

Please update security configuration assessment (CIS Benchmark for Debian/Linux 10) ....

All the best

Thomas

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by jnasselle** [comment]
Hi @ThomasVIDALUBS,

Thank you for reporting it. This will be fixed in #12155.

Regards,
Nico
