### ISSUE TITLE
Update agent-auth.exe implementation

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#1214]
Hi team, 

the `agent-auth.exe` implementation is a bit old compared with the implementation of agent-auth for Linux based systems. This creates some issues when registering agents using `agent-auth`. 

Also, there are a lot of parameters missing in the `agent-auth.exe`. Most of the parameters that you can find in [here](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-auth.html) don't work in the Windows version of agent-auth.

Regards.

**Comment by vikman90** [comment]
Hi, @BraulioV and @branchnetconsulting,

This issue is duplicated with #1452. Let us continue working on the mentioned one.

Thank you for your feedback.
Best regards.

**Comment by branchnetconsulting** [comment]
Please close this issue.  It has been resolved when issue #1452 was attended to and closed.  Thanks for resolving the Windows agent-auth issue!
