### ISSUE TITLE
Modify the `set-agent-groups` wazuh-db commando to avoid leaving an agent without groups when the `remove` mode is used

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#12168]
### Description

During the testing of the `wazuh-db` commands implemented for the epic https://github.com/wazuh/wazuh/issues/10771 it was detected that using the `set-agent-groups` command in the `remove` mode, it is possible to leave an agent without groups. This is not an expected behavior as the only scenario in which an agent could be without groups, is after the registration and before the first communication.

### Requirements

- [x] Modify the method `wdb_global_set_agent_groups` when it receives the mode `WDB_GROUP_REMOVE` to perform a check after removing the group. If the agent remains unsigned to a group, it should be assigned to `default` making all the required changes in the database (belongs, group column, and hash).

### Testing required

- [x] Provide evidence that the command works when unassigning an agent from a group and it remains assigned to other groups.
- [x] Provide evidence that the command works when unassigning an agent from the unique group that is assigned and it remains assigned to the `default` group.

### DoD

- [x] All the requirements should be implemented.
- [x] Update all the necessary Unit Test cases.
- [x] The code review should be approved.
- [x] All the required test cases should pass successfully.
- [x] A `scan-build` execution without issues.

**Comment by MiguelazoDS** [comment]
During this implementation, two SEGFAULT were found. Both fixed were included as part of this issue.

- When a group is assigned
![12](https://user-images.githubusercontent.com/13010397/153621859-08b1e87a-b584-46d3-995f-bd99abe46565.png)
- When a group is unassigned
![10](https://user-images.githubusercontent.com/13010397/153621852-f730d54f-c19b-443d-ba0c-109a349451d9.png)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/12243 was merged.
