### ISSUE TITLE
Correct docs link for registering agents.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#122]
After installation, the install.sh script tells the user to visit the following link for help with registering agents:

    https://documentation.wazuh.com/agents/registering-agents

Following this link results in a 404 "File not found" error.  The correct link is:

    https://documentation.wazuh.com/current/user-manual/agents/registering-agents/index.html

I have submitted [Pull-Request 121](https://github.com/wazuh/wazuh/pull/121) to correct this issue.

**Comment by pillarsdotnet** [comment]
And it's already merged.  Thanks!

**Comment by jlruizmlg** [comment]
@pillarsdotnet we work fast here! :)
