### ISSUE TITLE
CVE-Vulnerability Processes oscap and xsltproc consume a lot of User Space CPU on Agents

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1222]
Hello,

some CVE vulnerability processes, the `oscap` and `xsltproc` command line tool forked by the `wazuh-modulesd/python/oscap.py` consume a full CPU-core for processing in user space on the agents. Both processes do obviously _heavy_ XML-parsing which is typically very CPU-intensive. For parsing the OVAL file `cve-debian-8-oval.xml`  which has a size of _34 MB_ and _555.600_ lines it is understandable when parser processes consume heavy CPU resources for a longer period of time. The `oscap` process runs for _2 minutes_ with _100%_ user space CPU usage for one core processing the `cve-debian-8-oval.xml` OVAL file. The `xsltproc` runs for _50 minutes_ using _100%_ user space CPU as well processing the previously generated output of the `oscap` process.

As mentioned, the high CPU consume for parsing is probably not solvable however, it contradicts the philosophy, HIDS agents only consume little resources on the to be monitored host.

I am a little bit helpless how to solve the CPU-usage "issue" here, any ideas?

**Comment by vikman90** [comment]
Hi @juergenc,

You're right, the OpenSCAP process (including result processing by _xsltproc_) is a heavy process. However, this process runs in low-priority by process nicing. You can set this value in the internal option: https://github.com/wazuh/wazuh/blob/v3.6.1/etc/internal_options.conf#L226-L227.

This allows OpenSCAP to use as much processor as it needs, as long as another process does not require CPU. I don't know any Linux call to limit the CPU load for a process, we could limit the processor usage by stopping and resuming the process, but IMHO process priority is a good balance for OpenSCAP performance without impacting other applications. We simply let Linux schedule processes.

Best regards.

**Comment by juergenc** [comment]
Hello @vikman90 ,

thank you for your explanation. The only thing which makes me wonder is that the `xsltproc` process runs for **~50 minutes** even if it gets 100% CPU resources. Either there is happening CPU-intensive "magic" inside or it is simply inefficient, the latter strike me.

**Comment by vikman90** [comment]
Hi @juergenc,

I agree 100%. I don't know how _xsltproc_ crosses data to produce the final document. According to the time it takes, it probably does a linear search. This has a significant CPU usage cost. There are methods to optimize the search time in CPU (storing and ordering the data in memory). This improves the CPU cost but obviously impacts the memory usage.

We shall investigate this a little, and probably think about implementing the final document composition on our own. A 100% CPU usage process running for 50 minutes is a very long task.

I appreciate your feedback.
Best regards.

**Comment by juergenc** [comment]
Hello @vikman90 ,

thanks for the appreciation!

One more thing: Another philosophical point is, nothing is evaluated or deeper processed on an agent for security reasons. This is not the case for the OpenSCAP stack like here the CVE vulnerability compliance test with the installed packages on an agent. The information about the installed packages on the agents is collected via syscollector on regular base and stored in SqLite3 databases on the manger, the OS type release as well . Theoretically there is no need to install and process the OVAL files on the agents, all information needed is on the manager. If you decide to shift the entire OpenSCAP processing on the manager-side, the topic discussed here needs _definitly_ reimplemented working much more efficently. One idea might be to implement an **ETL** process which extracts the content from the OVAL files, transforms it and loads it into an SqLite3 database. You do this just _one_ time until the next update of an OVAL file. Performing the CVE vulnerability compliance test on manager-side for e.g. thousand agents however, is another challenge to make it work on scale. This feature is then rather limited to a certain number of agents.

Regards.
