### ISSUE TITLE
Error verify-agent-conf

### ISSUE THREAD

**Issue by Regirv** [wazuh/wazuh#1224]
When I run verify-agent-conf, I get the following error:
verify-agent-conf: Verifying [/var/ossec/etc/shared/test/agent.conf]
2018/09/05 09:56:32 verify-agent-conf: WARNING: (1960): File limit has been reached (0). Please reduce the number of files or increase "logcollector.max_files".
2018/09/05 09:56:32 verify-agent-conf: WARNING: (1960): File limit has been reached (0). Please reduce the number of files or increase "logcollector.max_files".
2018/09/05 09:56:32 verify-agent-conf: WARNING: (1960): File limit has been reached (0). Please reduce the number of files or increase "logcollector.max_files".
2018/09/05 09:56:32 verify-agent-conf: WARNING: (1960): File limit has been reached (0). Please reduce the number of files or increase "logcollector.max_files".
verify-agent-conf: OK

But on the server, in the file local_internal_options.conf the parameter logcollector.max_files = 10000 is specified
There is also an error on the agents in the logs:
WARNING: (1960): File limit has been reached (0). Please reduce the number of files or increase "logcollector.max_files".

How to centrally set the logcollector.max_files parameter for all agents?

**Comment by iancastle** [comment]
Looks like it's some "unfinished" code in src/config/localfile-config.c

There's a new static variable "maximum_files".

int maximum_files;

This is never initialised, but then used in the check

    if (current_files >= maximum_files) {
        mwarn(FILE_LIMIT, maximum_files);
        return 0;
    }

This means that the rest of the code is never executed, so there "Read_Localfile" function doesn't actually do anything.

**Comment by vikman90** [comment]
Hi @Regirv and @iancastle,

You nailed it, this is a bug in the configuration checker. It does not impact in the agent auto-restart but both `verify-agent-conf` and _agentd_ show that message incorrectly.

We have fixed it: https://github.com/wazuh/wazuh/pull/1225. It will be available in the next version (3.6.1) in the upcoming days.

Thank you very much for reporting this bug and your detailed explanation.
Best regards.

**Comment by chemamartinez** [comment]
Hi @Regirv and @iancastle, 

Let me close this issue since it was fixed at #1225. Please, don't hesitate to reopen it whether the issue persists. Thanks a lot for your feedback!

Regards.
