### ISSUE TITLE
to see syslog messages as an Agent

### ISSUE THREAD

**Issue by LucasNelsen** [wazuh/wazuh#12296]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4 | Wazuh component | Manager/Agent/Syslog | Virtual Machine package | Ubuntu 20.04 lts |

Hello,
I recently configured the Wazuh Manager to get Syslog logs from another device. It works just fine, but it isn't visible as an agent, and I can only see the logs. 
I wondered if there is any way that I can change that so it's visible as an agent or something in line with that. 
It would help greatly!
Many thanks. 
Lucas Nelsen

**Comment by JcabreraC** [comment]
Hello @LucasNelsen ,

Unfortunately, it is not possible to view that device as an agent. Getting the logs from an external device is not an agent and therefore does not support the functionalities that these have.

It is possible to filter the logs coming from that device in Kibana through the `location` field, but as I say, you cannot see it as an agent in Wazuh.

Regards !
