### ISSUE TITLE
Wazuh Agent on a Domain Controller

### ISSUE THREAD

**Issue by dwill6413** [wazuh/wazuh#12298]
Wazuh version 3.13.1, Windows Installer, Manual Install | Windows Server 2012R2 16GB of RAM

Hello all, first time posting here. I have a quick question hoping someone can answer. We are using Security Onion and Wazuh agents. We installed the agent on one of our DC's and everything works and logs get sent. However, after a short period, the buffer fills up and the DC/server crashes. We have determined that the reason for the crash is the RAM resources go to 100% utilization and the OS crashes. We then have to manually reboot the server to get it back up. We tried increasing the EPS to the max of 1000 EPS with no improvement, we still get the crash. The question is, I thought the purpose of the Leaky bucket was to prevent the scenario we are experiencing? Do the logs generated build in RAM when the buffer is full? If so, what can be done to make this work? We really want an agent on our DC, for obvious reasons.

**Comment by dwill6413** [comment]
Hello all, first time posting here. I have a quick question hoping someone can answer. We are using Security Onion and Wazuh agents. We installed the agent on one of our DC's and everything works and logs get sent. However, after a short period, the buffer fills up and the DC/server crashes. We have determined that the reason for the crash is the RAM resources go to 100% utilization and the OS crashes. We then have to manually reboot the server to get it back up. We tried increasing the EPS to the max of 1000 EPS with no improvement, we still get the crash. The question is, I thought the purpose of the Leaky bucket was to prevent the scenario we are experiencing? Do the logs generated build in RAM when the buffer is full? If so, what can be done to make this work? We really want an agent on our DC, for obvious reasons.

**Comment by pereyra-m** [comment]
Hello @dwill6413 !
Thanks for using Wazuh.

It seems that Security Onion hasn't updated its Wazuh version yet, the current stable version is **4.2.5**. The project is always improving, incorporating new features and fixing bugs.
But you can't have an agent version higher than the manager's one, so you may not be able to perform an upgrade.

On the other side, the [Anti-flooding mechanism](https://documentation.wazuh.com/4.2/user-manual/capabilities/antiflooding.html) is `designed to prevent large bursts of events on an agent from negatively impacting the network or the manager`. So if the amount of events is too large, some of them are temporary stored in the queue to keep the maximum EPS configured. But if the queue is full, the remaining events will be discarded. You shouldn't experience a total crash.

Please, add `windows.debug=2` to the `/var/ossec/etc/internal_options.conf` file in your DC and restart your agent to enable debug messages. Then, upload the `ossec.log` file of the agent after a crash so we can have more information about the issue.

Regards.

**Comment by dwill6413** [comment]
Thank you for responding Matias, my colleague will be gathering the requested logs. He will respond in this thread. Again, thanks for the assist!

**Comment by dwill6413** [comment]
For an update, we are looking into the possibility that it is NOT the Wazuh agent. It may be the osquery agent that is the culprit. We will update once we confirm.

**Comment by pereyra-m** [comment]
Thank you for the update!

Let me know if we can help.

Regards.

**Comment by dwill6413** [comment]
Matias, you can close this ticket. It is the osquery agent that is causing the spike, not the Wazuh agent. Thanks again for the quick response. Have a great weekend.

**Comment by pereyra-m** [comment]
Thanks to you!

Regards.
