### ISSUE TITLE
Syscollector ports inventory does not collect pid or process name on Linux agents

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#1232]
At least on Wazuh 3.6.0 CentOS 7 agents, the syscollector wodle does not appear to be collecting pid or process name values which would normally be the last two fields in the agents' sys_ports sqlite records.   This leaves us no way to pivot from a listening port to the process doing the listening. 

Example sqlite sys_ports record for a CentOS 7 agent
736806160|2018/09/05 23:04:02|tcp|0.0.0.0|1515|0.0.0.0|0|0|0|3268844|listening||

At least for Wazuh 3.6.0 Windows 2012 R2  agents, these fields are being successfully collected.  Example sqlite record:
947614155|2018/09/05 23:02:14|tcp|0.0.0.0|3389|0.0.0.0|0||||listening|2552|svchost.exe

I presume some simple tweak is needed in the Linux syscollector code.  Thanks for checking on it. 

Kevin

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting,

We are aware of this misfeature. It is contemplated at this issue [#535](https://github.com/wazuh/wazuh/issues/535) and we will include it as soon as possible.

Let me close this issue.

Regards,
Chema.
