### ISSUE TITLE
Remove limitation to add never_connected agents to groups

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12334]
## Description
Up until now, `never_connected` agents could only be added to groups during registration, either using `agent-auth` or `enrollment `configuration. It was not possible to add a `never_connected` agent to any group using the API or CLI tool. The reason behind this limitation is probably related to the non-existence of agent-groups files for said `never_connected` agents.

With the migration of agent-groups files to wazuh-db proposed in https://github.com/wazuh/wazuh/issues/10771, it no longer makes sense to have this limitation. In fact, adding a `never_connected` agent to any group or groups prior to its first connection could be beneficial, as it would eliminate a possible double restart in the agent due to centralized configuration changes, first default group, then the new group/s after they were added.

This issue proposes to completely eliminate any limitation to add groups to agents, including the API and the agent-groups CLI.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Status update
Development has begun. This issue will use [feature/10771-cluster-api-agent-groups](https://github.com/wazuh/wazuh/tree/feature/10771-cluster-api-agent-groups) as its base branch.
