### ISSUE TITLE
Conflict in FIM configuration when two nested directories defined

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1234]
This is an example configuration:

```xml
<directories check_all="yes" recursion_level="2">/etc</directories>
<directories check_all="yes" realtime="yes">/etc/httpd</directories>
```

It's not clear whether a new reported file by the real-time engine would get the first or the second definition. The configuration finder should get the second one since it's the longest (more restrictive) path.

**Comment by bah07** [comment]
After some testing, the functionality is correct.
The options are correctly applied to each directory.
