### ISSUE TITLE
Want to create a custom Script where i want to call my script after one group rule is triggered multiple times on same IP 

### ISSUE THREAD

**Issue by aksha78** [wazuh/wazuh#12345]
Hi, 
I want to create my script which should run after 1 rule group is triggered multiple times can i specify that in my <active-response > tag ?

**Comment by FrancoRivero** [comment]
Hi @aksha78, 
Thank you for using Wazuh!
I think that you want to execute an action in this case, execute a script, after matching with some rule. We have a capability for that, this is [active response](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/how-it-works.html) you should configure active response to do which you want to do, you must configure following [the next guide](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/custom-active-response.html)
Hope this to be useful for you !
Regards
