### ISSUE TITLE
Active Response add/delete using API

### ISSUE THREAD

**Issue by bbkrr** [wazuh/wazuh#12342]
|Wazuh version|Component|
|---|---|
| 4.2.5 | Wazuh API |

I was trying to use Wazuh API to send active response, and as mentioned in the [documention](https://documentation.wazuh.com/current/user-manual/api/reference.html#tag/Active-response) I used `!` to execute a script but was unable to send `delete` command for that script.

`{
    "command": "!firewall-drop",
    "custom": false,
    "alert": {
        "data": {
            "srcip": "xx.xx.xxx.xx",
            "srcuser": "company_name"
        }
    }
}`

It can only send add command along with it, and we don't have any key to send a timeout for the `delete` command to execute by itself. So, is there a way to send `delete` command along with the script using the API ?

I have tested it with ossec.conf and it works fine, but I want to use the same feature using API.

**Comment by sdvendramini** [comment]
Hi @bbkrr 
Thanks for using Wazuh!
It's not possible to send a delete command through the API or a timeout for the add command for now. What can be done is a custom active response to do the delete.

You can see this issue where a workaround with custom active response is described:
https://github.com/wazuh/wazuh/issues/10672

and you can also check the documentation referring to this:
https://documentation.wazuh.com/current/user-manual/capabilities/active-response/custom-active-response.html#custom-active-response-linux-example

I hope this solves your need.
Let me know if you need anything else,
Regards.

**Comment by bbkrr** [comment]
Thank you @sdvendramini
