### ISSUE TITLE
wazuh-modulesd:syscollector: ERROR: stoi

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#12353]
Version v4.2.5, wazuh-agent.service, installed using wazuh-ansible, Ubuntu 20.04.
See 'LOGS' below for error.  Nothing is being reported in ELK.

AGENT:
systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-02-15 19:19:00 MST; 1 day 14h ago
    Process: 3008819 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 53 (limit: 444818)
     Memory: 374.6M
     CGroup: /system.slice/wazuh-agent.service
             ├─3008874 /var/ossec/bin/wazuh-execd
             ├─3009511 /var/ossec/bin/wazuh-agentd
             ├─3010132 /var/ossec/bin/wazuh-syscheckd
             ├─3010732 /var/ossec/bin/wazuh-logcollector
             └─3011405 /var/ossec/bin/wazuh-modulesd

Feb 15 19:18:52 titan2 systemd[1]: Starting Wazuh agent...
Feb 15 19:18:52 titan2 env[3008819]: Starting Wazuh v4.2.5...
Feb 15 19:18:54 titan2 env[3008819]: Started wazuh-execd...
Feb 15 19:18:55 titan2 env[3008819]: Started wazuh-agentd...
Feb 15 19:18:56 titan2 env[3008819]: Started wazuh-syscheckd...
Feb 15 19:18:57 titan2 env[3008819]: Started wazuh-logcollector...
Feb 15 19:18:58 titan2 env[3008819]: Started wazuh-modulesd...
Feb 15 19:19:00 titan2 env[3008819]: Completed.
Feb 15 19:19:00 titan2 systemd[1]: Started Wazuh agent.

PLATFORM:
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

LOGS:
sudo cat /var/ossec/logs/ossec.log
2022/02/17 00:00:10 wazuh-agentd: INFO: Starting new log after rotation.
2022/02/17 00:19:41 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 00:19:42 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 00:19:42 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 01:19:43 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 01:19:43 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 01:19:43 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 02:19:44 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 02:19:45 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 02:19:45 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 03:19:46 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 03:19:46 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 03:19:46 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 04:19:47 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 04:19:48 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 04:19:48 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 05:19:49 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 05:19:50 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 05:19:50 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 06:19:51 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 06:19:51 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 06:19:51 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 07:18:57 sca: INFO: Starting Security Configuration Assessment scan.
2022/02/17 07:18:57 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_debian10.yml'
2022/02/17 07:19:41 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_debian10.yml'
2022/02/17 07:19:41 sca: INFO: Security Configuration Assessment scan finished. Duration: 44 seconds.
2022/02/17 07:19:52 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 07:19:53 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 07:19:53 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 07:19:57 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2022/02/17 07:20:28 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/02/17 07:23:50 rootcheck: INFO: Starting rootcheck scan.
2022/02/17 07:25:25 rootcheck: INFO: Ending rootcheck scan.
2022/02/17 08:19:54 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 08:19:54 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 08:19:54 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/02/17 09:19:55 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/02/17 09:19:56 wazuh-modulesd:syscollector: ERROR: stoi
2022/02/17 09:19:56 wazuh-modulesd:syscollector: INFO: Evaluation finished.

**Comment by Dwordcito** [comment]
Hi @alphaDev23 I hope you are well!

Could turn on debug logs(2: Verbose debug output) for wazuh-modulesd and restart the wazuh service, and send me the logs again?

Here I show you how to do it. 
https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#internal-configuration
https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#wazuh-modules


It is most likely related to this issue, which is fixed in 4.3
https://github.com/wazuh/wazuh/issues/11079

**Comment by alphaDev23** [comment]
Before chasing this potentially fixed issue, I would like to build the docker containers (wazuh-docker) v4.3.0 (these are not on hub.docker.com) and see if this is still an issue.  However, I'm receiving the build error, 'No package wazuh-manager-4.3.0-1 available' after cloning and checking out branch v4.3.0.  This appears to be an issue with the Dockerfile and/or the package is not in the mirror.  How to fix?  Are these containers going to be built and pushed to hub.docker.com (an option to resolve if the build will not work)?

Also, is wazuh-ansible tested with v4.3.0 as this is a well-used deployment tool?

**Comment by Dwordcito** [comment]
This is because version 4.3 is not yet available. Version 4.3 is very close to coming out, we are carrying out final tests.

the latest version available to the public is 4.2.5

**Comment by Dwordcito** [comment]
Hi @alphaDev23 friendly reminder for my request.

**Comment by alphaDev23** [comment]
@Dwordcito I'm probably going to wait until 4.3 but if I have additional time prior to the release, I will post the test the above.

**Comment by jnasselle** [comment]
Hi @alphaDev23 ,

Please let us know if this issue still happens on v4.3

**Comment by Dwordcito** [comment]
Closed due to lack of response, please open it if you see it again.
