### ISSUE TITLE
Monitoring logs using wildcard for folders on Windows

### ISSUE THREAD

**Issue by georgethemarmot** [wazuh/wazuh#12351]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Logcollector | Agent | Packages | All |

Hello,
according to [4.2 documentation](https://documentation.wazuh.com/4.2/user-manual/reference/ossec-conf/localfile.html) and to some testing, the "localfile" configuration allows only wildcard to match a file name.

It could be a nice addition to allow wildcard also for directories.
One case example would be a syslog server dynamically creating paths according to IP / Hostname.
eg.
 C:\Logs\10.0.01\date_10.0.0.1.log
 C:\Logs\10.0.02\date_10.0.0.2.log
 C:\Logs\10.0.03\date_10.0.0.4.log

I could be a nice addition to 'catch' all recursively eg.
```
<localfile>
    <location> C:\Logs\*\*.log</location>
    <log_format>syslog</log_format>
</localfile>
```

@ezequielsvelez mentioned on slack community that the code is using glob to resolve wildcards, 
but even the  ** is currently working:
I've unsuccessfully tried:
C:\Logs\**
C:\Logs\**\*
C:\Logs\**\*.log
C:\Logs\*,recursive=True

Thank you

**Comment by vikman90** [comment]
Hi @georgethemarmot,

I've tried your configuration and confirmed this issue. I consider it a bug as we expect that to work.

### Linux

I have this file: **_/root/test/demo.log_**.

#### Configuration

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/root/*/*.log</location>
</localfile>
```

Logcollector picks it correctly:
```
2022/05/20 10:34:42 wazuh-logcollector[13338] logcollector.c:1384 at check_pattern_expand(): DEBUG: (1957): New file that matches the '/root/*/*.log' pattern: '/root/test/demo.log'.
```

### Windows

I have this file:
_D:\Logs\test\demo.log_

#### Configuration

```xml
<localfile>
  <location>D:\Logs\*\*.log</location>
  <log_format>syslog</log_format>
</localfile>
```

And I get this error:
```
2022/05/20 10:31:42 wazuh-agent: ERROR: Couldn't open directory 'D:\Logs\*' due to: The filename, directory name, or volume label syntax is incorrect.
```

## Rationale

Just as @ezequielsvelez said, Logcollector uses function [`glob()`](https://man7.org/linux/man-pages/man7/glob.7.html) to resolve wildcarded paths, but this works on UNIX systems only (Linux, Solaris, macOS, etc.). In contrast, Logcollector uses a custom implementation of the wildcard expansion. This is why I think this is a bug.

On the other hand, we recently added wildcard expansion in FIM (#8461). We had the same issue and implemented a new custom wildcard expansion function for Windows: [`expand_win32_wildcards()`](https://github.com/wazuh/wazuh/blob/308ac4db442e49b65ff9057dd59a827aefd77f9e/src/shared/file_op.c#L2062-L2163).
I did a rapid test replacing the wildcard expansion in Logcollector with this new function, and I got that working:

```
2022/05/20 10:29:59 wazuh-agent[1392] logcollector.c:1556 at check_pattern_expand(): INFO: (1957): New file that matches the 'D:\Logs\*\*.log' pattern: 'D:\Logs\test\demo.log'.
```

So, let me add this issue to our roadmap to fix it more carefully.

Thanks for reporting this problem.
Best regards!

**Comment by nconder** [comment]
I'm having this issue too with IIS logging. A wildcard in Windows paths would be very helpful with IIS because each site has folder W3SVC1. Site A = W3SVC1 Site B =W3SV2 and so on...

Does not work and returns error: `Glob error. Invalid pattern: 'C:\inetpub\logs\LogFiles\*\u_ex%y%m%d.log' or no files found.`

`	</localfile>
		<localfile>
		<location>%SystemDrive%\inetpub\logs\LogFiles\*\u_ex%y%m%d.log</location>
		<log_format>iis</log_format>
	</localfile>`

**Comment by dami-nicastro** [comment]
Hi team @vikman90 
I have tested this in Wazuh 4.3.11 and 4.4.3 and although the wildcards directories are matched:
```
2023/07/25 20:33:05 wazuh-logcollector[15301] logcollector.c:1356 at check_pattern_expand(): DEBUG: (1957): New file that matches the '/root/*/*' pattern: '/root/wildcard/wildcard'.
```
There is no "analysis" of the file and the content is not sent to `archives.json`:
```
[root@wazuh-server ~]# less /var/ossec/logs/archives/archives.json | grep wildcard
[root@wazuh-server ~]#
```
