### ISSUE TITLE
The `set-agent-groups` command for Wazuh-DB doesn't filter an incorrect mode parameter

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#12371]
### Description

As part of the testing made over the implementation of the epic https://github.com/wazuh/wazuh/issues/10771 , it was found that if an invalid **mode** is sent to the `set-agent-groups` command, the command tries to insert the data without validating the **mode**. This could lead to errors and a check must be added.

### Requirements

- [x] Add a new check for the **mode** parameter of the `set-agent-group` command. If it isn't valid, print the corresponding error message and do not execute the command.
- [x] Update the required unit test cases

### Testing required

- [x] Validate that an invalid **mode** for `set-agent-group` is rejected

### Risk analysis

This fix prevents possible errors, but doesn't introduce any potential hazard.

### DoD

- [x] All the requirements should be implemented.
- [x] Code review approved.
- [x] All the tests should pass successfully.
- [x] Scan-build execution without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/12372 was merged.
