### ISSUE TITLE
decoder failed with regex .*

### ISSUE THREAD

**Issue by kingtedd** [wazuh/wazuh#12377]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.5 | Decoders | Error|

## Description
I need to decode as400 log from powertech and i was created decoder from scratch, I have problem if i used regex .* for grep all message between | , because the message is not consistent 

anyone have a clue to fix that issue, please help
thx

### Service/Product/Module

<pre>
<code>
<-decoder name="as-400">
   <-program_name>CEF<-/program_name>
<-/decoder>

<-decoder name="as-400-parse">
   <-prematch>^\w+\|\D+\|\d.\d\|\w+|.*\|\d\|<-/prematch>   
<-/decoder>

<-decoder name="as-400-parse">
   <-parent>as-400<-/parent> 
   <-regex>^\w+\|\D+\|\d.\d\|(\w+)\|(.*)\|(\d)\|<-/regex>
   <-order>jobid, jobmsg, saverity<-/order>
<-/decoder>

<-decoder name="as-400-parse">
   <-parent>as-400<-/parent>   
   <-regex>src=(\S+) dst=(\S+) \w+=TYPE:(\w+) CLS:(\w+) JJOB:(\w+) JUSER:(\w+) JNBR:(\d+)<-/regex>
   <-order>srcip, dstip, type, cls, jobcmd, jusr<-/order>
<-/decoder>
</code>
</pre>

### Current results

some order value like jobid,jobmdg,saverity not appear on phase 2
<pre>

Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:GUNUNGARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL

**Phase 1: Completed pre-decoding.
        full event: 'Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:GUNUNGARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL'
        timestamp: 'Feb 17 11:08:21'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
        cls: 'AUD'
        dstip: '10.25.19.5'
        jusr: 'GUNUNGARTA'
        jobcmd: 'QPADEV000M'
        srcip: '192.168.10.134'
        type: 'JRN'

**Phase 3: Completed filtering (rules).
        id: '14700'
        level: '0'
        description: 'Grouping of OS400-IBM rules'
        groups: '['syslog', 'as-400']'
        firedtimes: '1'
        mail: 'False'
</pre>

### Expected results
need some order value like jobid,jobmdg,saverity appear on phase 2
<pre>
Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:LINTASARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL

**Phase 1: Completed pre-decoding.
        full event: 'Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:LINTASARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL'
        timestamp: 'Feb 17 11:08:21'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
	<b>jobid: 'TJS0019'
	jobmsg: 'Job QPADEV000M is starting.'
	saverity: '6'</b>
        cls: 'AUD'
        dstip: '10.25.19.5'
        jusr: 'GUNUNGARTA'
        jobcmd: 'QPADEV000M'
        srcip: '192.168.10.134'
        type: 'JRN'

**Phase 3: Completed filtering (rules).
        id: '14700'
        level: '0'
        description: 'Grouping of OS400-IBM rules'
        groups: '['syslog', 'as-400']'
        firedtimes: '1'
        mail: 'False'
</pre>

### Log examples
<pre>
  - Examples:
  
  - Feb 17 11:08:14 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0016|An invalid password was entered for user profile GUNUNGARTA.|5|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:IDS JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:P GUNUNGSARTA QPADEV000M

  - Feb 16 17:27:49 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0017|An attempted signon (user authentication) failed; user profile QSECOFR.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:Q QSECOFR QPADEV000P

  - Feb 16 18:05:53 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0021|An invalid user name was entered for user profile QQSECOFR.|6|src=192.168.10.134 dst=::ffff:10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QZSOSIGN JUSER:QUSER JNBR:148685 PGM:QZSOSIGN OBJECT: LIBRARY: MEMBER: DETAIL:U QQSECOFR

  - Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:GUNUNGARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL:S I   QPADEV000M 
</pre>

**Comment by juliancnn** [comment]
Hi @kingtedd ,

I think you did very well, you just didn't specify the type of regex. 
By default the regex option uses [OS_Regex](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax), on which you can find [here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) the specifications (and syntax). From version 4.1 of Wazuh, [PCRE2](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/pcre2.html), a more complex regex type with more options, was added.

Your decoder works fine if you specify PCRE2 in it. They should look like the following:

```xml
<!--
  Example:
Feb 17 11:08:14 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0016|An invalid password was entered for user profile GUNUNGARTA.|5|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:IDS JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:P GUNUNGSARTA QPADEV000M
Feb 16 17:27:49 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0017|An attempted signon (user authentication) failed; user profile QSECOFR.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:Q QSECOFR QPADEV000P
Feb 16 18:05:53 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0021|An invalid user name was entered for user profile QQSECOFR.|6|src=192.168.10.134 dst=::ffff:10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QZSOSIGN JUSER:QUSER JNBR:148685 PGM:QZSOSIGN OBJECT: LIBRARY: MEMBER: DETAIL:U QQSECOFR
Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:GUNUNGARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL:S I   QPADEV000M 
-->

<decoder name="as-400">
   <program_name>CEF</program_name>
</decoder>

<decoder name="as-400-parse">
   <parent>as-400</parent>
   <regex type="pcre2">^\w+\|\D+\|\d.\d\|(\w+)\|(.*)\|(\d)\|</regex>
   <order>jobid, jobmsg, saverity</order>
</decoder>

<decoder name="as-400-parse">
   <parent>as-400</parent>   
   <regex>src=(\S+) dst=(\S+) \w+=TYPE:(\w+) CLS:(\w+) JJOB:(\w+) JUSER:(\w+) JNBR:(\d+)</regex>
   <order>srcip, dstip, type, cls, jobcmd, jusr</order>
</decoder>
```
Then I tested your logs in logtest, and they seem to have the desired output:

```console
cat ./testlogs.txt | /var/ossec/bin/wazuh-logtest                                                                                                                                                 

Starting wazuh-logtest v4.4.0
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'Feb 17 11:08:14 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0016|An invalid password was entered for user profile GUNUNGARTA.|5|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:IDS JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:P GUNUNGSARTA QPADEV000M'
        timestamp: 'Feb 17 11:08:14'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
        cls: 'IDS'
        dstip: '10.25.19.5'
        jobcmd: 'QINTER'
        jobid: 'TPW0016'
        jobmsg: 'An invalid password was entered for user profile GUNUNGARTA.'
        jusr: 'QSYS'
        saverity: '5'
        srcip: '192.168.10.134'
        type: 'JRN'


**Phase 1: Completed pre-decoding.
        full event: 'Feb 16 17:27:49 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0017|An attempted signon (user authentication) failed; user profile QSECOFR.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QINTER JUSER:QSYS JNBR:116415 PGM:QLESPI OBJECT: LIBRARY: MEMBER: DETAIL:Q QSECOFR QPADEV000P'
        timestamp: 'Feb 16 17:27:49'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
        cls: 'AUD'
        dstip: '10.25.19.5'
        jobcmd: 'QINTER'
        jobid: 'TPW0017'
        jobmsg: 'An attempted signon (user authentication) failed; user profile QSECOFR.'
        jusr: 'QSYS'
        saverity: '6'
        srcip: '192.168.10.134'
        type: 'JRN'

**Phase 3: Completed filtering (rules).
        id: '1002'
        level: '2'
        description: 'Unknown problem somewhere in the system.'
        groups: '['syslog', 'errors']'
        firedtimes: '1'
        gpg13: '['4.3']'
        mail: 'False'


**Phase 1: Completed pre-decoding.
        full event: 'Feb 16 18:05:53 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TPW0021|An invalid user name was entered for user profile QQSECOFR.|6|src=192.168.10.134 dst=::ffff:10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QZSOSIGN JUSER:QUSER JNBR:148685 PGM:QZSOSIGN OBJECT: LIBRARY: MEMBER: DETAIL:U QQSECOFR'
        timestamp: 'Feb 16 18:05:53'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
        cls: 'AUD'
        dstip: '::ffff:10.25.19.5'
        jobcmd: 'QZSOSIGN'
        jobid: 'TPW0021'
        jobmsg: 'An invalid user name was entered for user profile QQSECOFR.'
        jusr: 'QUSER'
        saverity: '6'
        srcip: '192.168.10.134'
        type: 'JRN'



**Phase 1: Completed pre-decoding.
        full event: 'Feb 17 11:08:21 PRDBSD CEF: 0|Powertech|SIEM Agent|4.0|TJS0019|Job QPADEV000M is starting.|6|src=192.168.10.134 dst=10.25.19.5 msg=TYPE:JRN CLS:AUD JJOB:QPADEV000M JUSER:GUNUNGARTA JNBR:149017 PGM:QWTPIIPP OBJECT: LIBRARY: MEMBER: DETAIL:S I   QPADEV000M '
        timestamp: 'Feb 17 11:08:21'
        hostname: 'PRDBSD'
        program_name: 'CEF'

**Phase 2: Completed decoding.
        name: 'as-400'
        cls: 'AUD'
        dstip: '10.25.19.5'
        jobcmd: 'QPADEV000M'
        jobid: 'TJS0019'
        jobmsg: 'Job QPADEV000M is starting.'
        jusr: 'GUNUNGARTA'
        saverity: '6'
        srcip: '192.168.10.134'
        type: 'JRN'


```
Finally, the following decoder that you have created has no utility, maybe you have omitted something?:

```xml

<-decoder name="as-400-parse">
   <-prematch>^\w+\|\D+\|\d.\d\|\w+|.*\|\d\|<-/prematch>   
<-/decoder>
```
I hope this has been useful to you

Regads,
Julian

**Comment by kingtedd** [comment]
Hi @juliancnn,

its work fine julian
thank you so much, this issue fixed
i resolved this issue

Regrads,
tedd
