### ISSUE TITLE
Test multiple groups

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1238]
# Check list

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3708 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

- [ ] For all the checks, test the consistency between the API and `agent_groups` results
- [ ] Do the checks with `authd` running and stopped
- [x] Create a new group
- [x] Add the new group to an agent
- [x] List the groups
- [x] Change the agent.conf file of the new group
- [x] Remove the global.db database
- [x] Remove the new group
- [ ] Add an agent with Authd that contains a multigroup
- [ ] Add an agent with Authd that contains invalid groups
- [ ] Add an agent with Authd that contains a malformed multigroup
- [ ] Remove an agent with manage_agents
- [ ] Remove a multigroup folder
- [ ] Remove .metadata file
- [ ] Remove a group existing in several multigroups, check if is correctly removed
- [ ] Force a replacement of groups for an agent and check that it changed correctly
- [ ] Reassign a deleted agent with `authd` to the manager, check that it belongs to its old groups

## Feature description

The multiple group feature adds the capability to add various groups to an agent. For example you can add the groups` group1, group2, group3` to the agent **001**.

First of all download the RESTful API branch: https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement
# Tests

- ## Create a new group
    - ### How to 
      - `/var/ossec/bin/agent_groups -a -g newgroup`
      - Check if the group is created in the database:
        - `# sqlite3 /var/ossec/var/db/global.db`
        - select * from \`group`
     - ### Expected results 
       - Group is created

- ## Add the new group to an agent
    - ### How to 
      - `/var/ossec/bin/agent_groups -a -i 001 -g newgroup`
      - Check if the group is added to the agent in the database:
         - `# sqlite3 /var/ossec/var/db/global.db`
         - select \`group` from agent where id ='1'
         - select * from belongs
      - Check if the multiple group folder is created
         - `# ls /var/ossec/var/multigroups`
      - Check if the multiple group is ok in agent 001
         - `# cat /var/ossec/queue/agent-groups/001 `
    - ### Expected results 
        - Group is added to the agent 001, you should see **default-newgroup** in `/var/ossec/var/multigroups` and default-newgroup in ` /var/ossec/queue/agent-groups/001`

- ## List the groups
    - ### How to 
      - `/var/ossec/bin/agent_groups -l -g newgroup`
    - ### Expected results 
        -  You must see the following output:
    ```
      1 agent(s) in group 'newgroup':
          ID: 001  Name: TEST. * 
    ```
    The ***** at the end of the agent name indicates that it belongs to multiple groups:

- ## Change the` agent.conf` file of the new group
    - ### How to 
      - `# nano /var/ossec/etc/shared/newgroup/agent.conf`
      - Save the changes:
         - `# sqlite3 /var/ossec/var/db/global.db`
         - select \`group` from agent where id ='1'
         - select * from belongs
      - Check if the new group `agent.conf `is merged with the `default agent.conf`
         - `# cat /var/ossec/var/multigroups/default-newgroup/agent.conf`
      - On the agent **001** check the received the agent.conf file
         - `# cat /var/ossec/etc/shared/agent.conf `
    - ### Expected results 
        - The **agent.conf** file from **default,newgroup** get merged, **the agent must receive this configuration**

- ## Remove the global.db databse
    - ### How to 
      - `# rm /var/ossec/var/db/global.db`
      - Restart the manager:
      - Check if the database and all the tables are created and filled
         - `# sqlite3 /var/ossec/var/db/global.db`
         - select * from agent
         - select * from belongs
         - select * from \`group`
    - ### Expected results 
        - All tables must exists, the belongs table have to be filled  and the group table filled with all the existing groups.

- ## Remove the new group
    - ### How to 
      - `/var/ossec/bin/agent_groups -r -g newgroup`
      - Check if the group is removed from the database:
        - `# sqlite3 /var/ossec/var/db/global.db`
         - select \`group` from agent where id ='1'
         - select * from belongs
      - Check if the multiple group folder is removed
         - `# ls /var/ossec/var/multigroups`
      - Check if the group is ok in agent 001
         - `# cat /var/ossec/queue/agent-groups/001 `
    - ### Expected results 
        - Group is removed, you should **not** see **default-newgroup** in `/var/ossec/var/multigroups` and default-newgroup in ` /var/ossec/queue/agent-groups/001`

- ## Add an agent with **Authd** that contains a multigroup
    - ### How to 
      - `/var/ossec/bin/agent-auth -m MANAGER_IP -G group1,group2,group3`
      - Check if the multiple group folder is created
         - `# ls /var/ossec/var/multigroups`
      - Check if the group is ok in agent 00X
         - `# cat /var/ossec/queue/agent-groups/00X `
    - ### Expected results 
        - Multigroup is created, you should  see **group1,group2,group3** in `/var/ossec/var/multigroups` and group1,group2,group3 in ` /var/ossec/queue/agent-groups/00X`

- ## Add an agent with **Authd** that contains an **invalid (non existing)** group
    - ### How to 
      - `/var/ossec/bin/agent-auth -m MANAGER_IP -G group1,group2,group3,invalidgroup`
      - Check the Authd message
         - `# ERROR: Invalid group: invalidgroup (from manager)`
    - ### Expected results 
        - The agent is not registered because the group does not exists

- ## Add an agent with **Authd** that contains a **malformed** multigroup
    - ### How to 
      - `/var/ossec/bin/agent-auth -m MANAGER_IP -G ,,,default,,,,group1,,,,,group2`
      - Check the Authd message
         - `# ERROR: Invalid multigroup: ,,,default,,,,group1,,,,,group2`
    - ### Expected results 
        - The agent is not registered because the group if malformed

- ## Remove an agent with **manage_agents**
    - ### How to 
      - `/var/ossec/bin/manage_agents`
      - Remove an agent that belongs to a **multigroup**
    - ### Expected results 
        - If the agent removed is the only one that belongs to the multigroup, that folder should be removed from `/var/ossec/var/multigroups`. If not that folder should stay.

- ## Remove a multigroup folder
    - ### How to 
      - `rm -rf /var/ossec/var/multigroups/(HASH)`
    - ### Expected results 
        - When the agent send the ACK, the folder should be created again in `/var/ossec/var/multigroups`

- ## Remove .metadata file
    - ### How to 
      - `rm -rf /var/ossec/var/multigroups/.metadata`
    - ### Expected results 
        - When the agents send the ACK, the file should be created again in `/var/ossec/var/multigroups`

- ## Repeat the tests with real time option enabled
  - ### How to 
      - Set wazuh_database.real_time=1 in `/var/ossec/etc/internal_options.conf`
  - ### Expected results 
        - When adding, creating and removing a group, the changes will apply immediately to the  `/var/ossec/var/db/global.db` database

- ## Repeat the tests with real time option disabled
  - ### How to 
      - Set wazuh_database.real_time=0 in `/var/ossec/etc/internal_options.conf`
  - ### Expected results 
        - When adding, creating and removing a group, the changes will apply every `wazuh_database.interval` (60 by default) seconds to the `/var/ossec/var/db/global.db` database

- ## Repeat the tests with the RESTful API
   - ### How to  
     - Add a group to an agent with `curl -u foo:bar -X PUT "http://localhost:55000/agents/001/group/newgroup?pretty"`
  - ### Expected results 
      - Same results for each test

# Known issues

None

**Comment by vikman90** [comment]
Related development issue: #1396

**Comment by cristgl** [comment]
When deleting groups to which agents belong with `agent_groups -r -g newgroup`, the message shown isn't correct, as it shows that there are no agents affected or it doesn't show all of them. Nevertheless, the functionality is correct, the merged is updated and the group is removed.

The agents with id `1` and `4` belong to `newgroup` group with id `5` as shown in the data base:
```
sqlite> select * from belongs;
1|5
4|2
4|5
```

When removing `newgroup`, the only agent affected is `1`.
```
# /var/ossec/bin/agent_groups -r -g newgroup
Do you want to remove the 'newgroup' group? [y/N]: y
All selected groups were removed
Affected agents: 001.
```

**Comment by Skeptor** [comment]
Adding a group with '-' in his name results in error:
`Do you want to create the group 'default-group'? [y/N]: y`
`Error 1722: Incorrect format for group_id. Characters supported  a-z, A-Z, 0-9, -.=!() Max length is 255.`
Also, characters: ` [ ] @ _ ` are supported but they doesn't appear in the message.

**Comment by Skeptor** [comment]
https://github.com/wazuh/wazuh-api/issues/181

**Comment by Skeptor** [comment]
Got permission denied trying to delete a group
>curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/groups/prueba1?pretty"
>{
 >  "error": 1005,
 >  "message": "Error reading file: [Errno 13] Permission denied: '/var/ossec/var/multigroups/.metadata'"
>}

**Comment by cristgl** [comment]
https://github.com/wazuh/wazuh/issues/1569

**Comment by juan70** [comment]
**Tests performed**

With
- wazuh-manager-3.7.0-0.3708.11102018.37.x86_64
- wazuh-agent-3.7.0-0.3708.11102018.37.x86_64

1. Create a new group
   **=> OK.**

2. Add the new group to an agent
   **=> OK.** The pattern for the name of the subdirectory under `.../multigroups/` has been changed since the creation of this issue. Now this is a hexadecimal hash number (first 8 characters).

3. List the groups
   **=> OK.** The `*` in the output is no longer required.

4. Change the `agent.conf` file of the new group
   **=> OK.** `agent.conf` are merged and sent to the agent.

5. Remove the `global.db` database
   **=> OK.** Tables (the whole database file, actually) recreated, and populated with the same data as initially.

6. Remove the new group
   **=> OK.** Group removed from the database and from the directories..

7. Add an agent with Authd that contains a multigroup
   **=> FAIL or OK?** No subdirectory created under `/var/ossec/var/multigroups/`, but maybe this is the correct behavior under certain circumstances...
   **=> OK.** `/var/ossec/queue/agent-groups/00X` contains the names of the groups added to the agent.

8. Add an agent with Authd that contains an invalid (non existing) group
   **=> OK.** Error message received.

9. Add an agent with Authd that contains a malformed multigroup
   **=> OK.** Error message received.

10. Remove an agent with manage_agents
   **=> FAIL or OK?** When the last agent is removed, the corresponding `.../multigroups/xxxxx` directory is not removed.

11. Remove a multigroup folder
   **=> OK.** The directory is created again.

12. Remove .metadata file
   **=> OK.** The file is created again.

Not done yet: repeat the tests with real time option enabled, disabled, and with the RESTful API.

**Comment by juan70** [comment]
**Tests performed again, with `real time` disabled.**
Option `wazuh_database.real_time=0` in local_internal_options.conf (and restart manager).
Mainly, same results.
Although, for points 10, 11 and 12, the results are slightly different, maybe because these tests were performed after having manipulated the data during the earlier tests. 


10. Remove an agent with manage_agents
    **=> OK?** No subfolder was present in `.../multigroups` (see test 7.), so can't say whether deleted or not...
    **=> OK.** /var/ossec/queue/agent-groups/002 deleted.


11. Remove a multigroup folder
   **=> FAIL?** Folder not created again in `/var/ossec/var/multigroups`. (This was OK before... See point 2.) 
      (Tried restarting the manager, but nothing... Waiting for a few minutes, but still nothing.)


12. Remove .metadata file
    **=> FAIL?** File not created again.
      (Tried restarting the manager, but nothing... Waiting for a few minutes, but still nothing.)

**Comment by juan70** [comment]
Other tests
==
**Remove a group existing in several multigroups, check if is correctly removed**
Two tests
- 2 agents and 1 group
   - create the group
     `/var/ossec/bin/agent_groups -a -g grupo1`
   - associate the 2 agents with the group
     -> both agents in grupo1
   - remove group
     `/var/ossec/bin/agent_groups -r -g grupo1`
   **=> OK.** Group removed. Agents belong to group 'default' only.

- 2 agents and 3 groups
   - create the 3 groups
     `/var/ossec/bin/agent_groups -a -g grupo1`
     `/var/ossec/bin/agent_groups -a -g grupo2`
     `/var/ossec/bin/agent_groups -a -g grupo3`
   - associate the 2 agents with the groups, 1 group is common to both agents
     -> 001: grupo1,grupo3
        `/var/ossec/bin/agent_groups -a -i 001 -g grupo1`
        `/var/ossec/bin/agent_groups -a -i 001 -g grupo3`
     -> 002: grupo2,grupo3
        `/var/ossec/bin/agent_groups -a -i 002 -g grupo2`
        `/var/ossec/bin/agent_groups -a -i 002 -g grupo3`

     -> view info
        `/var/ossec/bin/agent_groups -l -g grupo1`
        `/var/ossec/bin/agent_groups -l -g grupo2`
        `/var/ossec/bin/agent_groups -l -g grupo3`
        `/var/ossec/bin/agent_groups -s -i 001`
        `/var/ossec/bin/agent_groups -s -i 002`
   - remove group
       `/var/ossec/bin/agent_groups -r -g grupo3`
   => **OK.** Group removed. Agents belong to remaining groups.


**Force a replacement of groups for an agent and check that it changed correctly**
- 2 groups
   - associate agent to group1 (001 already belongs to grupo1, from earlier test)
     `/var/ossec/bin/agent_groups -a -i 001 -g grupo1`
   - associate agent to group2 
     `/var/ossec/bin/agent_groups -a -i 001 -f -g grupo2`
   - agent should belong to group2 only
   **=> OK.** 001 belongs only to group2. `/var/ossec/bin/agent_groups -s -i 001`

**Reassign a deleted agent with authd to the manager, check that it belongs to its old groups**
   - agent belongs to 2 groups
     `/var/ossec/bin/agent_groups -s -i 005` --> grupo1,grupo3 (and default too)
   - remove agent
     `/var/ossec/bin/manage_agents -r 005`
   - agent still belongs to groups grupo1, grupo3
     `/var/ossec/bin/agent_groups -s -i 005`
   - register again through agent-auth (-> will give ID 006)
     `/var/ossec/bin/agent-auth -m 192.168.56.103`
     Now, `/var/ossec/bin/agent_groups -s -i 005` says "Agent does not exist"
     And, `/var/ossec/bin/agent_groups -s -i 006` says agent "belongs to groups: Null"
     After restarting the agent, "belongs to groups: grupo1", but not grupo3.
     **=> FAIL.** Agent only reassigned to one group, not all.

**Comment by TJOSERAFAEL** [comment]
Hi @juan70,

the last test that you did:

```
Reassign a deleted agent with authd to the manager, check that it belongs to its old groups

    agent belongs to 2 groups
    /var/ossec/bin/agent_groups -s -i 005 --> grupo1,grupo3 (and default too)
    remove agent
    /var/ossec/bin/manage_agents -r 005
    agent still belongs to groups grupo1, grupo3
    /var/ossec/bin/agent_groups -s -i 005
    register again through agent-auth (-> will give ID 006)
    /var/ossec/bin/agent-auth -m 192.168.56.103
    Now, /var/ossec/bin/agent_groups -s -i 005 says "Agent does not exist"
    And, /var/ossec/bin/agent_groups -s -i 006 says agent "belongs to groups: Null"
    After restarting the agent, "belongs to groups: grupo1", but not grupo3.
    => FAIL. Agent only reassigned to one group, not all.
```

Works fine, please specify the environment and agents that you have connected.

Regards.

**Comment by juan70** [comment]
Hello, @TJOSERAFAEL,

The tests where performed in this environment:

- Manager: CentOS 7 x86_64
    `yum info wazuh-manager` yields:
     ```
        Installed Packages
        Name        : wazuh-manager
        Arch        : x86_64
        Version     : 3.7.0
        Release     : 0.3708.15102018.37.nightly
        Size        : 86 M
        Repo        : installed
        From repo   : wazuh_repo_dev
     ```


  
- Agent: CentOS 7 x86_64
    `yum info wazuh-agent` yields:
     ```
        Installed Packages
        Name        : wazuh-agent
        Arch        : x86_64
        Version     : 3.7.0
        Release     : 0.3708.11102018.37
        Size        : 74 M
        Repo        : installed
        From repo   : wazuh_repo_dev
     ```

  There were 2 agents connected (as far as I remember), same OS, same agent package.

Maybe it's a matter of repeating the whole sequence of tests, including the two earlier. At any rate, the test did result in a fail, maybe because of the data being in a specific state at that moment (and this could be ok), maybe because the program fails, maybe because some specific behavior should be considered depending on the data (this could be ok, too).

Best regards.

**Comment by juan70** [comment]
Same tests, using the RESTful API
==
1. Create a new group
   ```
   curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/groups/grupo4?pretty"
   ```
   **=> OK.** Group created.

2. Add the new group to an agent
   ```
   curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/006/group/grupo4?pretty"
   ```
   **=> OK.** Group added to an agent.

3. List the groups
   ```
   curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/groups?pretty"
   ```
   **=> OK.** All of the existing groups are shown.

4. Change the `agent.conf` file of the new group
   The API cannot do that. Can it?

5. Remove the `global.db` database
   The API cannot do that. Can it?

6. Remove the new group
   ```
   curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/groups/grupo4?pretty"
   /var/ossec/bin/agent_groups -l -g grupo4 
   /var/ossec/bin/agent_groups -s -i 006
   ```
   **=> OK.** Group removed.

7. Add an agent with Authd that contains a multigroup
   The API does not use authd. Does it?

   But we try to kind of mimic this in some way.
   Say we have this agent:
   ```
    # /var/ossec/bin/agent_groups -s -i 004
    The agent 'centosvm2' with ID '004' belongs to groups: default, grupo1, grupo3.
   ```

   - Now, try the registration (although agent already registered)
     ```
     curl -u foo:bar -k -X POST -d '{"name":"centosvm2","ip":"192.168.56.102"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents?pretty"
     ```
     Error 9007, duplicated IP, that's OK.
   - Then, force the registration (field "force")
     ```
     curl -u foo:bar -k -X POST -d '{"name":"centosvm2","ip":"192.168.56.102","force":"0"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents?pretty"
     ```
     Registration OK. ID is incremented 004->005.
     ```
     # /var/ossec/bin/agent_groups -s -i 005
     The agent 'centosvm2' with ID '005' belongs to groups: Null.
     ```
     We need to export/import the new key into the agent, and restart it.
     ```
     # /var/ossec/bin/agent_groups -s -i 005
     The agent 'centosvm2' with ID '005' belongs to groups: default, grupo1, grupo3.
     ```
   **=> OK.**


8. Add an agent with Authd that contains an invalid (non existing) group
   The API does not use authd. Does it?

   Anyway, trying to add the agent (existing) to a non existing group.
   ```
   curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/007/group/dummygroup?pretty"
   ```
   **=> OK.** Error 1710 "The group does not exist: dummygroup".

9. Add an agent with Authd that contains a malformed multigroup
   The API does not use authd. Does it?

   Anyway, trying to add the agent (existing) to a malformed group name.
   ```
   curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/007/group/group,,,,¡?pretty"
   ```
   **=> OK.** Error 601 "Param not valid. Valid characters: a-z, A-Z, 0-9, ., _, -.  Field: group_id"

10. Remove an agent with manage_agents
    The API can remove an agent.
    ```
    curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/001?pretty"
    ```

    Having a look at the agents we have so far:
    ```
    # /var/ossec/bin/agent_groups -s -i 002
    The agent 'centosvm3' with ID '002' belongs to groups: default.
    # /var/ossec/bin/agent_groups -s -i 005
    The agent 'centosvm2' with ID '005' belongs to groups: default, grupo1, grupo3.
    # ll /var/ossec/var/multigroups/
    total 4
    drwxrwx---. 2 ossecr ossec 4096 Oct 16 16:37 c9abebea
    # cat /var/ossec/var/multigroups/.metadata 
    default,grupo1,grupo3

    ```
    Removing the agent:
    ```
    curl -u foo:bar -k -X DELETE "http://127.0.0.1:55000/agents/005?pretty"
    ```
    OK. Agent removed.
    We still can see:
    ```
    # ll /var/ossec/var/multigroups/
    total 4
    drwxrwx---. 2 ossecr ossec 4096 Oct 16 14:42 c9abebea
    # cat /var/ossec/var/multigroups/.metadata 
    default,grupo1,grupo3
       
    ```
    Even after restarting the agent and the manager, the `.../multigroups/c9abebea` directory is not deleted, file `.../multigroups/.metadata` still contains the groups of the deleted agent. Maybe because there is one agent in group  `default`:
    ```
    # /var/ossec/bin/agent_groups -l -g grupo1
    No agents found in group 'grupo1'.
    # /var/ossec/bin/agent_groups -l -g grupo2
    No agents found in group 'grupo2'.
    # /var/ossec/bin/agent_groups -l -g grupo3
    No agents found in group 'grupo3'.
    # /var/ossec/bin/agent_groups -l -g default
    1 agent(s) in group 'default':
      ID: 002  Name: centosvm3. 
    ```
    After removing agent 002, and restarting the agents and the manager, the directory `.../multigroups/c9abebea` is not deleted and the file `.../multigroups/.metadata` is not empty.

    **=> FAIL? OK?**


11. Remove a multigroup folder
    The API cannot access the filesystem and remove a folder. Can it?

12. Remove .metadata file
    The API cannot access the filesystem and remove a file. Can it?

**Comment by juan70** [comment]
After some more testing for points 7 and 10:
- Point 7. seems to be OK, after a new testing session. Don't know whether it is due to some changes carried out in the source code, or because my data were corrupted in some way, or whatever.

- Point 10. still gives some problems. An issue is created for that: https://github.com/wazuh/wazuh/issues/1672.
