### ISSUE TITLE
Reach full coverage in FIM cmocka unit tests

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#12392]
### Description

The goal of this issue is to create unit tests to cover all the flows of the C function affected by development #9103.

## Linux functions

**run_check.c**

- [x] fim_db_remove_validated_path()

**create_db.c**

- [x] fim_calculate_dbsync_difference()
- [x] process_delete_event()
- [x] create_windows_who_data_events()
- [x] fim_db_remove_entry()
- [x] fim_db_process_missing_entry()
- [x] fim_process_missing_entry()
- [x] free_entry()

## Windows functions

**run_check.c**

- [x] fim_db_remove_validated_path()

**create_db.c**

- [x] fim_calculate_dbsync_difference()
- [x] process_delete_event()
- [x] fim_scan (when `db_entry_limit_enabled` is true)
- [x] create_windows_who_data_events()
- [x] fim_db_remove_entry()
- [x] fim_db_process_missing_entry()
- [x] fim_process_missing_entry()
- [x] free_entry()

**registry/events.c**

- [x] fim_calculate_dbsync_difference_key()
- [x] fim_calculate_dbsync_difference_value()
- [x] fim_registry_value_attributes_json()
- [X] fim_registry_value_json_event() (Excluded from the coverage, as this function is ment to be used for whodata monitoring)
- [x] fim_registry_key_attributes_json()
- [X] fim_registry_key_json_event() (Excluded from the coverage, as this function is ment to be used for whodata monitoring)

**registry/registry.c**

- [x] registry_key_transaction_callback()
- [x] registry_value_transaction_callback()
- [x] fim_registry_free_entry()

**Comment by antoniomanuelfr** [comment]
Here is the coverage report for windows:
[coverage.zip](https://github.com/wazuh/wazuh/files/8117704/coverage.zip)
