### ISSUE TITLE
Reduce to 128 the maximum number of groups per multigroup and forbid group names `.` and `..`

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12396]
As part of the development for [Migrate agent-group files to wazuh-db #10771](https://github.com/wazuh/wazuh/issues/10771), we have decided to reduce the maximum number of groups an agent can belong to from 256 to 128. We have also decided to explicitly forbid the creation of groups with names `.` and `..`. 

Currently, the API will respond that those groups already exist, due to the existence of `.` and `..` paths in the directory. We should forbid the creation of such groups expanding the actual [regexes](https://github.com/wazuh/wazuh/blob/62c904098d63b28c62611785bec9c093aec505e5/api/api/validator.py#L22-L23).

Also, there is a different regex being used internally in the [InputValidator](https://github.com/wazuh/wazuh/blob/62c904098d63b28c62611785bec9c093aec505e5/framework/wazuh/core/InputValidator.py#L51) which should be substituted with the one above in `validator.py`.

The length of the group name should be explicitly checked in the API spec and also adapted in the `InputValidator`.
A proper description of the valid group names should be added to POST /groups group_id documentation.

This issue should take care of updating the API, framework and CLIs for any possible changes and adapt it accordingly. 

Any related tests should be updated or created if there is none.

**Comment by vicferpoy** [comment]
## Status update
Development has begun. This issue will use [feature/10771-cluster-api-agent-groups](https://github.com/wazuh/wazuh/tree/feature/10771-cluster-api-agent-groups) as its base branch.
