### ISSUE TITLE
Wazuh CRI-O monitoring support

### ISSUE THREAD

**Issue by evasokolova1f** [wazuh/wazuh#12399]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Wazuh component | Agent | Packages | Ubuntu |

Hi!
Tell me, please, does Wazuh support monitoring through CRI-O (similar to docker)?
https://documentation.wazuh.com/current/docker-monitor/monitoring-containers-activity.html

**Comment by vikman90** [comment]
Hi @evasokolova1f,

I'm afraid the current version of Wazuh supports native containers activity for Docker. In fact, the `docker-listener` module uses the Docker SDK to pick logs.

On the other hand, I can't find any SDK for CRI-O, as it is a Kubernetes runtime interface, as explained at [The differences between Docker, containerd, CRI-O and runc](https://www.tutorialworks.com/difference-docker-containerd-runc-crio-oci). Sorry if I'm wrong. Are you using CRI-O independently from Kubernetes?

As told before, Wazuh does not support native container monitoring for Kubernetes, but I think you can enable auditing logs in Kubernetes ([Kubernetes - Auditing](https://kubernetes.io/docs/tasks/debug-application-cluster/audit)), and set up Wazuh to monitor the output log:

```xml
<localfile>
  <log_format>json</log_format>
  <location>/var/log/kubernetes/audit/audit.log</location>
</localfile>
```

Hope that helps.
Best regards.

**Comment by evasokolova1f** [comment]
Hi @vikman90,

Thank you for your answer! I'll try to use auditd.

Best regards,
Eva Sokolova
