### ISSUE TITLE
Problem with custom rule not matching field correctly 

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [wazuh/wazuh#12401]
|Wazuh version| Component |
|4.2.5| wazuh agent 4.2.5 | 

## Description
We have this two rules for our custom sysmon ruleset

	<rule id="100102" level="0">
		<if_group>sysmon_event1</if_group>
		<field name="win.eventdata.ParentImage">\\WINWORD.EXE||\\EXCEL.EXE||\\POWERPNT.exe||\\MSPUB.exe||\\VISIO.exe</field>
		<description>Mitre ATT&CK T1059, Command and Scripting Interpreter, MS Word - Ms EXCEL run</description>
		<mitre>
		  <id>T1059</id>
		</mitre>		
		<options>no_full_log</options>
	</rule>
	
		<rule id="101310" level="12">
		<if_sid>100102</if_sid>
		<field name="win.eventdata.Image">\\cmd.exe||\\powershell.exe||\\wscript.exe||\\cscript.exe||\\sh.exe||\\bash.exe||\\scrcons.exe||\\schtasks.exe||\\regsvr32.exe||\\hh.exe||\\csc.exe</field>
		<description>Mitre ATT&CK T1059, Execution, Command and Scripting Interpreter, Microsoft Office Product Spawning Windows Shell</description>
		<mitre>
		  <id>T1059</id>
		</mitre>		
		<options>no_full_log</options>
	</rule>

### Log examples

{"timestamp":"2022-02-22T15:55:37.206+0000","rule":{"level":12,"description":"Mitre ATT&CK T1059, Execution, Command and Scripting Interpreter, Microsoft Office Product Spawning Windows Shell","id":"101310","firedtimes":686,"mail":true,"groups":["MITRE ATT&CK_sysmon"]},"agent":{"id":"XXX","name":"XXX","ip":"XXX.XXX.XXX.XXX","labels":{"host":{"os":{"type":"windows"}}}},"manager":{"name":"XXX"},"id":"1645545337.2280857181","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Sysmon","providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","eventID":"1","version":"5","level":"4","task":"1","opcode":"0","keywords":"0x8000000000000000","systemTime":"2022-02-22T15:55:36.173435700Z","eventRecordID":"16979639","processID":"2768","threadID":"5300","channel":"Microsoft-Windows-Sysmon/Operational","computer":"XXX","severityValue":"INFORMATION","message":"\"Process Create:\r\nRuleName: T1059 -43\r\nUtcTime: 2022-02-22 15:55:36.171\r\nProcessGuid: {ad33eaea-0778-6215-ca3f-000000002100}\r\nProcessId: 18516\r\nImage: C:\\Windows\\System32\\conhost.exe\r\nFileVersion: 10.0.17763.2268 (WinBuild.160101.0800)\r\nDescription: Console Window Host\r\nProduct: Microsoft® Windows® Operating System\r\nCompany: Microsoft Corporation\r\nOriginalFileName: CONHOST.EXE\r\nCommandLine: \\??\\C:\\Windows\\system32\\conhost.exe 0xffffffff -ForceV1\r\nCurrentDirectory: C:\\Windows\r\nUser: NT AUTHORITY\\SYSTEM\r\nLogonGuid: {ad33eaea-e8ea-6206-e703-000000000000}\r\nLogonId: 0x3E7\r\nTerminalSessionId: 0\r\nIntegrityLevel: System\r\nHashes: MD5=6B2CB80E2990A6F7A362139DA5F913B8,SHA256=ABB6C10C4F8F62411016F9B560D623CB37B4D051D5CB5760082880933BF87740\r\nParentProcessGuid: {ad33eaea-0778-6215-c93f-000000002100}\r\nParentProcessId: 14128\r\n**ParentImage: C:\\Program Files\\Veeam\\Backup and Replication\\Backup\\Veeam.Backup.Satellite.exe**\r\nParentCommandLine: \"C:\\Program Files\\Veeam\\Backup and Replication\\Backup\\Veeam.Backup.Satellite.exe\" \"SYSTEM_PowerShell_VEEAM19_7dc77706-9e97-4ee1-96cb-4f109737cf8a\"\""},"eventdata":{"ruleName":"T1059 -43","utcTime":"2022-02-22 15:55:36.171","processGuid":"{ad33eaea-0778-6215-ca3f-000000002100}","processId":"18516",**"image":"C:\\\\Windows\\\\System32\\\\conhost.exe**","fileVersion":"10.0.17763.2268 (WinBuild.160101.0800)","description":"Console Window Host","product":"Microsoft® Windows® Operating System","company":"Microsoft Corporation","originalFileName":"CONHOST.EXE","commandLine":"\\\\??\\\\C:\\\\Windows\\\\system32\\\\conhost.exe 0xffffffff -ForceV1","currentDirectory":"C:\\\\Windows","user":"NT AUTHORITY\\\\SYSTEM","logonGuid":"{ad33eaea-e8ea-6206-e703-000000000000}","logonId":"0x3e7","terminalSessionId":"0","integrityLevel":"System","hashes":"MD5=6B2CB80E2990A6F7A362139DA5F913B8,SHA256=ABB6C10C4F8F62411016F9B560D623CB37B4D051D5CB5760082880933BF87740","parentProcessGuid":"{ad33eaea-0778-6215-c93f-000000002100}","parentProcessId":"14128","parentImage":"C:\\\\Program Files\\\\Veeam\\\\Backup and Replication\\\\Backup\\\\Veeam.Backup.Satellite.exe","parentCommandLine":"\\\"C:\\\\Program Files\\\\Veeam\\\\Backup and Replication\\\\Backup\\\\Veeam.Backup.Satellite.exe\\\" \\\"SYSTEM_PowerShell_VEEAM19_7dc77706-9e97-4ee1-96cb-4f109737cf8a\\\""}}},"location":"EventChannel"}

###Error

The alarm is hitting the rule even when neither the ParentImage or Image as you can see from the log we copy in the upper section are the one that are supposed to be the ones that had to match.

It begings to happen when we update agents to version 4.2.5

**Comment by jnasselle** [comment]
Hi @BernaldoPenasAntelo,

The problem seems to be related with your `field name="win.eventdata.ParentImage"` [OS_Regex](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax), specifically double pipes that I guess you are trying to use as OR operator.

This could be validated by using the [wazuh-regex](https://documentation.wazuh.com/current/user-manual/reference/tools/wazuh-regex.html) tool, which always matches when it's not supposed to.
```
/var/ossec/bin/wazuh-regex '\\WINWORD.EXE||\\EXCEL.EXE||\\POWERPNT.exe||\\MSPUB.exe||\\VISIO.exe'
C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
+OSRegex_Execute: C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
+OS_Regex       : C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
+OSMatch_Compile: C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
+OS_Match2      : C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
```
Changing the regex to `\\WINWORD.EXE|\\EXCEL.EXE|\\POWERPNT.exe|\\MSPUB.exe|\\VISIO.exe`, the same test fails as expected
```
/var/ossec/bin/wazuh-regex '\\WINWORD.EXE|\\EXCEL.EXE|\\POWERPNT.exe|\\MSPUB.exe|\\VISIO.exe'                                      
C:\Program Files\Veeam\Backup and Replication\Backup\Veeam.Backup.Satellite.exe
```
But using an expected positive value it work as expected
```
/var/ossec/bin/wazuh-regex '\\WINWORD.EXE|\\EXCEL.EXE|\\POWERPNT.exe|\\MSPUB.exe|\\VISIO.exe'                                      
C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE
+OSRegex_Execute: C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE
+OS_Regex       : C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE
+OSMatch_Compile: C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE
+OS_Match2      : C:\\Program Files\\Microsoft Office\\Office16\\WINWORD.EXE
```
You might change double pipes in both rules to make them work.

Hope this helps!
Regards,
Nico

**Comment by BernaldoPenasAntelo** [comment]
Thanks for your quick response, it looks correct.

**Comment by jnasselle** [comment]
Glad to hear that @BernaldoPenasAntelo!

As this is solved I will close the issue. Feel free to create new issues for new concerns.

Regards,
Nico
