### ISSUE TITLE
Multiple authd daemons

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#1243]
This bug has been reported from our community. An instance of the Wazuh administrator is running multiple authd demons for no reason. They cannot be killed either.

We haven't reproduced it yet.

**Comment by vikman90** [comment]
This issue may occur if any client connects to Authd but does not send data.

**Proposed fix:** Add a timeout to the client sockets. If a client takes more than the selected time to respond, the server shall close the connection.

**Comment by vikman90** [comment]
Working on branch _fix-auth-hand_.

## New internal options:

### `auth.timeout_seconds`

Network timeout (seconds).
Allowed values: 0 to 2147483647.
Default value: 1.

### `auth.timeout_microseconds`

Network timeout (µseconds).
Allowed values: 0 to 999999.
Default value: 0.
