### ISSUE TITLE
Select between CVSS2 vs CVSS3 Vulnerability Scoring 

### ISSUE THREAD

**Issue by mbelsis** [wazuh/wazuh#12462]
The Wazuh Vulnerabilities Management , should allow admins to configure whether the CVSS2 or CVSS3 scoring (_data.vulnerability.cvss.cvss2.base_score_ **vs** _data.vulnerability.cvss.cvss3.base_score_) will be used to calculate a severity level (data.vulnerability.severity)  of the discovered vulnerabilities.

If the VA Finding includes more than one CVE vulnerabilities , the one with the Highest score maybe used to calculate the Severity  

Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.4| Vulnerabilities Management| Manager | Packages/Sources | OS version |

**Comment by mbelsis** [comment]
Hi ,
Sorry for the delayed reply. 
Thank you for this. My only problem is that all the GUI dashboard  / graphs  are based on CVSS3.  So this is any issue.  any plans on making this customizable ?
BR

    On Monday, 14 March 2022, 16:56:53 EET, Matias Pereyra ***@***.***> wrote:  
 
 


Hello @mbelsis !

Thank you very much for your suggestion. The team will analyze it.

Currently, the Vulnerability Detector alerts have both scores but the severity field is calculated prioritizing CVSS3 over CVSS2. The user can't change this behavior right now.
Only if the CVSS3 score isn't present, the string will be generated with the CVSS2 score.

Also, consider that in some special cases (like CentOS/RedHat agents) the severity is taken from the vendor's feed (OVAL) instead of the NVD to avoid some cases where this field would be empty.

I suggest you filter the alerts within certain ranges for each score, this way you'll achieve the same result you are looking for.
Here you have the scales

CVSS2 (data.vulnerability.cvss.cvss2.base_score)
   
   - Low – 0.0 – 3.9
   - Medium – 4.0 – 6.9
   - High – 7.0 – 10.0

CVSS3 data.vulnerability.cvss.cvss3.base_score
   
   - None – 0.0
   - Low – 0.1 – 3.9
   - Medium – 4.0 – 6.9
   - High 7.0 – 8.9
   - Critical – 9.0 – 10.0

If you save the filters, it's easy to switch between score systems.

Regards.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pereyra-m** [comment]
Hello again @mbelsis !

Don't forget you can create your own visualizations and dashboards. See the documentation section [Create a custom dashboard](https://documentation.wazuh.com/current/user-manual/kibana-app/reference/custom-dashboard.html).
Here, for example, I'm showing you a comparison between the default severity and the CVSS2 score

![severity](https://user-images.githubusercontent.com/65046601/159798921-07374a51-0b17-416c-8f6a-e2f5dcf9f51d.png)

The visualization on the left was created with the following filters (use **Lucene** syntax):

- CVSS2 Low: `data.vulnerability.cvss.cvss2.base_score: [0 TO 3.99] OR (NOT _exists_: data.vulnerability.cvss.cvss2.base_score)`
- CVSS2 Medium: `data.vulnerability.cvss.cvss2.base_score: [4 TO 6.99] `
- CVSS2 High: `data.vulnerability.cvss.cvss2.base_score:  [7 TO 9.99] `

![visualization](https://user-images.githubusercontent.com/65046601/159799237-8a2c21cb-6282-498b-8c57-42b35b030d4b.png)

You could use the same filters for the events tab also

![filter_events](https://user-images.githubusercontent.com/65046601/159799879-fa4349b9-70e4-4b4e-bea0-34d0b4d68cc9.png)

Regards.

**Comment by gitmffonseca** [comment]
I think this is all messed up and doesn't make any sense!
Please see the images bellow....


![Screenshot 2022-06-29 at 13 13 46](https://user-images.githubusercontent.com/63270317/176433556-b161d6c2-7638-42a3-b84d-5d4c59da5d91.png)


![image](https://user-images.githubusercontent.com/63270317/176433367-484225c9-36bb-4ee1-a0ab-20a7c4c0a8b8.png)

**Comment by pereyra-m** [comment]
Hello @gitmffonseca !

Could you give me more details about what you are seeing wrong?
What queries are you using to filter the events? What is your Wazuh version?

Also, please consider that starting with Wazuh **4.3.0**, the vulnerability detector will have an individual vulnerabilities inventory for each agent. This prevents the repeated alerts that were generated in previous versions.

It means that the vulnerability detector alerts are no longer the recommended way to obtain this type of information. Please use the **Inventory** tab.

Regards.
