### ISSUE TITLE
Remove `board_serial` field from syscollector API endpoints expected responses (API integration tests)

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#12474]
## Description

As part of the syscollector API integration tests, we expect the `board_serial` field to always be present and this is not the case on every CI machine.

This check should not be part of the integration test between the Wazuh API and the framework, so we need to remove it to prevent false negatives.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Dwordcito** [comment]
Hi @vicferpoy

in which case this does not happen? (we don't have present the serial board.)

**Comment by vicferpoy** [comment]
Hello @Dwordcito ,

It happens randomly with certain instances of the automated API integration tests machines. That is why we cannot take anything for granted. You can find the only details the team could gather here: https://github.com/wazuh/wazuh-jenkins/issues/2415
