### ISSUE TITLE
FIM option: filtering by event type 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#1247]
Hello team

  It could be a great idea if the syscheck options allow indicating what kind of event we want to produce. Something like: 

<directories check_all="yes" whodata="yes" event="added">/myfolder</directories>

An only added file will produce alerts. Filtering by deleted, added or modifying could be a great tool for syscheck. Idea provided by @algonba

**Comment by antoniomanuelfr** [comment]
This functionality could be done by changing the field `level` of the rule that is going to be ignored by 0. 
An example could be: 
```
<rule id="550" level="0" overwrite="yes">
  <category>ossec</category>
  <decoded_as>syscheck_integrity_changed</decoded_as>
  <description>Integrity checksum changed.</description>
  <group>syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,</group>
</rule>

```
This will cause that the modifying alert does not appear.

**Comment by vikman90** [comment]
@antoniomanuelfr thank you!

Pinging @alberpilot and @bah07 to decide whether this issue needs further development or documentation.
