### ISSUE TITLE
API Registered Agent bug

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh#12484]
|Wazuh version|Component|Install type|Install method|Platform|
|3.13.1|Manager|docker|SecurityOnion

Hello,

I'm using a powershell script to register and install the wazuh agent on Windows and for some reason when i run the script first i got the agent but with "any"...
![image](https://user-images.githubusercontent.com/36012515/156342895-2067377f-ae74-416b-937d-2564766a21ab.png)

And if i run it a second time it's register with the proper IP...
I do not understand why..

Any idea why the first time i got any and after it's work?

The script (the end)

![image](https://user-images.githubusercontent.com/36012515/156342841-a1dd9d16-9058-45b4-ba6f-1ae3cc2412d2.png)

I post the question in the securityonion github too :https://github.com/Security-Onion-Solutions/securityonion/issues/7385

**Comment by vikman90** [comment]
Hi, I don't fully understand the script, but I see a double enrollment effort:
- Run `msiexec.exe` with `WAZUH_REGISTRATON_SERVER` asks the installer to request a key. This internally runs `agent-auth.exe`.
- Launch `manage_agents.exe` imports a previously generated key (`$key`).

I wonder if using both methods at the same time might be mixing keys.

On the other hand, the manager will grant new keys with `ip=any` by default, but we can change this behavior:

### Manager side

Set `<use_source_ip>` to `yes` at _etc/ossec-conf_:
```xml
<auth>
  <use_source_ip>no</use_source_ip>
</auth>
```

### Agent side

If you run `agent-auth.exe` manually, enable either the flag `-I <IP>` to set a defined IP, or `-i` to let the manager set the IP according to the agent's connection IP. 

```sh
# Option 1
.\agent-auth.exe -m 192.168.1.1 -I 192.168.1.2
# Option 2
.\agent-auth.exe -m 192.168.1.1 -i
```

If you set up enrollment, for the agent to automatically request a key when it's unable to connect to the manager, use one of the following options. They behave like the options above:
1. Define the agent's IP:
```xml
<client>
  <enrollment>
    <agent_address>192.168.1.2</agent_address>
  </enrollment>
</client>
```
2. Let the manager get the agent's IP:
```xml
<client>
  <enrollment>
    <use_source_ip>192.168.1.2</use_source_ip>
  </enrollment>
</client>
```

Hope this helps.
Best regards.

**Comment by b4b857f6ee** [comment]
Ok thank you. Maybe the Manager side configuration can do the trick.
I'm going to test it.

**Comment by b4b857f6ee** [comment]
> 

On SecurityOnion Docker i don't have the line 

auth>
  <use_source_ip>no</use_source_ip>
</auth>

You think i can add it in the global section ? :)

**Comment by vikman90** [comment]
Absolutely, you can. We changed the default value from `yes` to `now` as of 3.12. So, the current behavior by default is to set the agents' IP to `any`.

On the other hand, as I mentioned before, I suggest you change your script to either:
- Request a new key (using flag `WAZUH_REGISTRATON_SERVER`).
- Import an existing key (calling `agent-auth.exe`).

If you run both actions, the agent will always start with an invalid key, as the manager is creating a new key, and then we're importing an old one.

Best regards.
