### ISSUE TITLE
Test agent configuration querying

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1248]
| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3717 | 3.7 |

## Feature description

This feature allows the user to query the agent configuration from for example: `logcollector, syscheck, rootcheck, wodles`.

First of all download the RESTful API branch: https://github.com/wazuh/wazuh-api/tree/dev-query-config

# Tests

- ## Query logcollector configuration from any agent
    - ### How to 
      - curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/logcollector/localfile?pretty"
    - ### Expected results 
      - You should get a JSON object with all the `localfiles` present on the **agent** `ossec.conf`

- ## Query logcollector configuration from manager
    - ### How to 
      - curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/000/config/logcollector/localfile?pretty"
    - ### Expected results 
      - You should get a JSON object with all the `localfiles` present on the **manager** `ossec.conf`

- ## Query logcollector configuration from a **disconnected** agent
    - ### How to 
      - curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/logcollector/localfile?pretty"
    - ### Expected results 
      - You should get a TIMEOUT response after a while

- ## Query logcollector configuration from a **non-existing** agent
    - ### How to 
      - curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/logcollector/localfile?pretty"
    - ### Expected results 
      - You should get a `Cannot send request` response

- ## Repeat the same tests for syscheck, wodles etc. Repeat with **Windows Agents**

# Known issues

**Comment by Skeptor** [comment]
The API calls:
`analysis/rules`
`analysis/decoders`
fail with error:

>   "error": 1014,
>   "message": "Error communicating with socket: /var/ossec/queue/ossec/analysis"

**Comment by cristgl** [comment]
After registering an agent and before running a scan of Syscheck, the agent reports the next error when querying for the last scan:
```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/syscheck/006/last_scan?pretty"
{
   "error": 1000,
   "message": "'version'"
}
```

**Comment by cristgl** [comment]
Before executing a syscollector scan just after registering the agent, querying for 'netproto' returns the next output, maybe this should show a ND message.
```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/syscollector/010/netproto?pretty&limit=2&sort=type"
{
   "error": 0,
   "data": {
      "totalItems": 0,
      "items": []
   }
}
```

**Comment by cristgl** [comment]
The rootcheck and syscheck queries for consulting the last scan executed report different messages when the agent is disconnected just after registering it. Maybe this should be unified and show the same ND message.

```
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/rootcheck/006/last_scan?pretty"
{
   "error": 0,
   "data": {
      "start": null,
      "end": null
   }
}
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/syscheck/006/last_scan?pretty"
{
   "error": 0,
   "data": {
      "start": "ND",
      "end": "ND"
   }
}
```
