### ISSUE TITLE
Test Multithreaded Analysisd

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1249]
| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3717 | 3.7 |

## Feature description

The **multithreaded** `analysisd` has enhancements like variable number of threads, variable number of queue sizes and a statistical file.

These variables can be modified in` /var/ossec/internal_options.conf`.
```
# Number of event decoder threads
analysisd.event_threads=0
# Number of syscheck decoder threads
analysisd.syscheck_threads=0
# Number of syscollector decoder threads
analysisd.syscollector_threads=0
# Number of rootcheck decoder threads
analysisd.rootcheck_threads=0
# Number of hostinfo decoder threads
analysisd.hostinfo_threads=0
# Number of rule matching threads
analysisd.rule_matching_threads=0
# Decoder event queue size
analysisd.decode_event_queue_size=16384
# Decode syscheck queue size
analysisd.decode_syscheck_queue_size=16384
# Decode syscollector queue size
analysisd.decode_syscollector_queue_size=16384
# Decode rootcheck queue size
analysisd.decode_rootcheck_queue_size=16384
# Decode hostinfo queue size
analysisd.decode_hostinfo_queue_size=16384
# Decode Output queue
analysisd.decode_output_queue_size=16384
# Archives log queue size
analysisd.archives_queue_size=16384
# Statistical log queue size
analysisd.statistical_queue_size=16384
# Alerts log queue size
analysisd.alerts_queue_size=16384
# Firewall log queue size
analysisd.firewall_queue_size=16384
# FTS log queue size
analysisd.fts_queue_size=16384
# Interval for analysisd status file updating (seconds) [0..86400]
# 0 means disabled
analysisd.state_interval=5
```

The 0 value of the threads means that the number will be automatic based on the physical cores of the `CPU`

## Tests

- ### Change the number of threads for:
 - event_threads
 - syscheck_threads
 - syscollector_threads
 - rootcheck_threads
 - hostinfo_threads
 - rule_matching_threads
    - ### How to 
       - Edit the file `/var/ossec/internal_options.conf`
       - Change the value for every variable mentioned
       - Restart the **manager**
    - ### Expected results 
       - It should function normally, processing more **EPS(Events Per Second)** as with one thread. You can compare the EPS by watching the stats file `/var/ossec/var/run/ossec-analysisd.state`

- ### Change the queue size for:
 - decode_event_queue_size
 - decode_syscheck_queue_size
 - decode_syscollector_queue_size
 - decode_rootcheck_queue_size
 - decode_hostinfo_queue_size
 - decode_output_queue_size
 - statistical_queue_size
 - alerts_queue_size
 - firewall_queue_size
 - fts_queue_size

    - ### How to 
       - Edit the file `/var/ossec/internal_options.conf`
       - Change the value for every variable mentioned
       - Restart the **manager**
    - ### Expected results 
       - It should function normally, if a queue size is very low, you should see 100% usage on that queue by watching the stats file `/var/ossec/var/run/ossec-analysisd.state`

- ### Change state file update interval: 
    - ### How to 
       - Edit the file `/var/ossec/internal_options.conf`
       - Change the value for `state_interval` variable mentioned
       - Restart the **manager**
    - ### Expected results 
       - The file `/var/ossec/var/run/ossec-analysisd.state` should be updated every **state_interval** seconds

- ### Check frequency rules: 
    - ### How to 
       - Generate multiple ssh login fail events
       - It should trigger the frequency for example with an active-response
       - Restart the **manager**
    - ### Expected results 
       - The frequency rule should trigger. Test this with another rules.

- ### Check CDB list rules: 
    - ### How to 
       - Create some black white IP
    - ### Expected results 
       - The alert should be triggered on whitelist.

- ### Check FTS decoders: 
    - ### How to 
       - Pick some FTS decoder from ruleset and generate an alert for that rule
    - ### Expected results 
       - The alert should writted into `/var/ossec/queue/fts/fts-queue`

- ### Check alerts in general: 
    - ### How to 
       - Connect some agents with syscheck, osquery and other features enabled.
       - Set those features frequency to a low value like 40 seconds.
       - Watch the alerts.log file 
    - ### Expected results 
       - Alerts should be written to `alerts.log`

- ### Enable: 
 - jsonout_output 
 - logall 
 - logall_json
    - ### How to 
       - Connect some agents with syscheck, osquery and other features enabled.
       - Set those features frequency to a low value like 40 seconds.
       - Watch the alerts.log, alerts.json, archives.log, archives.json
    - ### Expected results 
       - All the files mentioned should get correct content.

# Known issues

**Comment by crolopez** [comment]
Related to:
https://github.com/wazuh/wazuh/issues/1390
https://github.com/wazuh/wazuh/issues/1380
