### ISSUE TITLE
Investigate and fix API integration tests errors related to agents' status

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#12492]
|Component|
|---|
| API Integration Tests |

In the API integration tests result of last nightlies, we have seen some test failures that apparently have the same origin.

These failures are appearing since February 26th. We should consider this as we could have merged something that has broken API integration tests healthchecks or something.

**Failures in `test_active_response_endpoints.tavern.yaml`:**

- First test case: agent 002 is not active. The agent status must be active since the healthcheck checks that every agent is active.

- Second test case: failure caused by a request to agent 002, which is expected to be active. There are no endpoint test cases before this one changing the agent status.

**Failures in `test_rbac_white_agent_endpoints.tavern.yaml`:**

- First test case: "SystemError: Agents ['004'] have a status different to active after restarting". This message is generated by the dynamic healthcheck implemented in healthcheck_agent_restart of tavern_utils.py. After restarting, agentd started but the agent is still shown as non-active. (delay: 20 seconds after agentd started + 25 seconds waiting for the agent to be active)

- Second test case: again agent 004 is not active. Same error as above as this error appears in an endpoint test case right after it.

- Third test case: when trying to restart a list of agents, ProcessLookupError: The wazuh-agentd daemon was not started after requesting the restart. agentd was not restarted because the agent was not active.

- Fourth test case: again ProcessLookupError, same as above.

**Failures in `test_rootcheck_endpoints.tavern.yaml`:**

- Agent with ID 001 is not active when trying to run a rootcheck scan over all agents.

**Failures in `test_agent_GET_endpoints.tavern.yaml`:**

- When filtering by agents with status disconnected, we expect agents 009 and 010. Apart from these two agents, agent 004 is also shown as disconnected.

---

We should investigate and fix these failures. Note that these errors have appeared in the `master` branch. We have performed the API integration tests in `4.3` and `4.2` and they don't appear.

Consider opening new issues if more errors or causes for them are found.

Tests results links:

- active_response, rbac_white_agent : [nightly_1.zip](https://github.com/wazuh/wazuh/files/8170714/nightly_1.zip)

- rootcheck, agent_GET : [nightly_2.zip](https://github.com/wazuh/wazuh/files/8170720/nightly_2.zip)

---

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

After investigating the logs where this error happened, I have seen the following. For instance, for agent 002 in the first error shown in the issue's body (active response test):


Agent 002 `ossec.log`:

```
...
2022/02/25 23:02:31 sca[1680] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 19189; Result: 'passed'
2022/02/25 23:02:31 sca[1680] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 19190; Result: 'passed'
2022/02/25 23:02:31 wazuh-agentd: INFO: Closing connection to server (nginx-lb/172.20.0.5:1514/tcp).
2022/02/25 23:02:31 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.20.0.5:1514/tcp).
2022/02/25 23:02:34 sca[1680] wm_sca.c:2435 at wm_sca_send_summary(): DEBUG: Sending summary event for file: 'cis_ubuntu20-04.yml'
2022/02/25 23:02:34 sca[1680] wm_sca.c:256 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"summary","scan_id":988258774,"name":"CIS benchmark for Ubuntu Linux 20.04 LTS","policy_id":"cis_ubuntu20-04","file":"cis_ubuntu20-04.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Ubuntu Linux 20.04 LTS.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":43,"failed":70,"invalid":78,"total_checks":191,"score":38.053096771240234,"start_time":1645830135,"end_time":1645830151,"hash":"b123a568d651b055108e6bbaa4e694dd0fb92b94bb696d0465c1c474b219123c","hash_file":"c6942553081be2d4e7b55c1b9859926b4b249f33985f33dc9f793bd8ff21d04f","first_scan":1}
2022/02/25 23:02:34 wazuh-modulesd[1680] wait_op.c:117 at os_wait_primitive(): DEBUG: Process locked due to agent is offline. Waiting for connection...
2022/02/25 23:02:41 wazuh-agentd: INFO: Closing connection to server (nginx-lb/172.20.0.5:1514/tcp).
2022/02/25 23:02:41 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.20.0.5:1514/tcp).
2022/02/25 23:02:51 wazuh-agentd: INFO: Closing connection to server (nginx-lb/172.20.0.5:1514/tcp).
2022/02/25 23:02:51 wazuh-agentd: INFO: Trying to connect to server (nginx-lb/172.20.0.5:1514/tcp).
...
```

The agent is trying to connect to server and never connects -> agent disconnected (no more errors in `ossec.log`)


In workers 1 and 2 `ossec.log` files, we can see the following errors:

Logs worker1:

```
2022/02/25 23:01:00 wazuh-analysisd: INFO: (7200): Logtest started
2022/02/25 23:01:18 wazuh-modulesd: ERROR: Cluster error detected
2022/02/25 23:01:18 wazuh-modulesd:agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.
2022/02/25 23:01:38 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
```

Logs worker2:

```
2022/02/25 23:00:54 wazuh-analysisd: INFO: Started (pid: 481).
2022/02/25 23:00:56 wazuh-analysisd: INFO: (7200): Logtest started
2022/02/25 23:01:14 wazuh-modulesd: ERROR: Cluster error detected
2022/02/25 23:01:14 wazuh-modulesd:agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.
```

In worker 2 `cluster.log`, the following error is shown at the beginning of the log file (error is not in worker 1):

```
2022/02/25 23:01:09 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/02/25 23:01:09 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/02/25 23:01:14 ERROR: [Local 302465] [Main] Internal error processing request 'b'sendsync'': Error 3023 - Worker node is not connected to master
2022/02/25 23:01:14 ERROR: [Local 302465] [Main] Error during connection with '302465': [Errno 104] Connection reset by peer.
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)

2022/02/25 23:01:19 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/02/25 23:01:29 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/02/25 23:01:40 INFO: [Worker worker2] [Main] Sucessfully connected to master.
...
```


After a deeper investigation about this error, I have seen that the error log is logged when a `-2` value is returned in the following function:

```c
/* Receive secure TCP Cluster message */
int OS_RecvSecureClusterTCP(int sock, char * ret, size_t length) {
    int recvval;
    const unsigned CMD_SIZE = 12;
    const uint32_t HEADER_SIZE = 8 + CMD_SIZE;
    uint32_t size = 0;
    char buffer[HEADER_SIZE];

    recvval = os_recv_waitall(sock, buffer, HEADER_SIZE);

    switch(recvval){
        case -1:
            return recvval;

        case 0:
            return recvval;

        default:
            if ((uint32_t)recvval != HEADER_SIZE) {
                return -1;
            }
    }

    if (strncmp(buffer+8, "err --------", CMD_SIZE) == 0) {
        return -2;
    }

    size = wnet_order_big(*(uint32_t*)(buffer + 4));
    if (size > length) {
        mwarn("Cluster message size (%u) exceeds buffer length (%u)", (unsigned)size, (unsigned)length);
        return -1;
    }

    /* Read the payload */
    return os_recv_waitall(sock, ret, size);
}
```


In other words, we have received a `err --------` message from the cluster socket.


After talking to the team about this, we have realized that this error was already reported in https://github.com/wazuh/wazuh/issues/11794.

These errors, `Cluster error detected` + `There has been an error executing the request in the tasks manager` in workers' `ossec.log`, and ` Internal error processing request 'b'sendsync'': Error 3023 - Worker node is not connected to master` in workers' `cluster.log` are appearing for all API integration tests failures explained in this issue's body. Therefore, we could confirm that the agents disconnection is happening due to these cluster errors. BUT, taking into account that these cluster errors are present before this API integration test issue was created, why were the API tests failures not occurring before? 

In order to find what changes in master have led to this problem and why, I have performed an API integration test burst in the master branch and before some changes I considered that could be causing these errors.



- API integration test burst in actual `master` branch -> FAILURES

- API integration test burst having reverted changes done in `docker-compose.yml` in commit  https://github.com/wazuh/wazuh/pull/10620/commits/c525afe60618d7b5b54ec4e2262df4624cf3410a of PR https://github.com/wazuh/wazuh/pull/10620:
  - (1/2) -> ALL PASSED
  - (2/2) -> FAILURE (test_agent_GET). Therefore, the removal of services dependencies from `docker-compose.yml` is not causing the test failures
  
I have been investigating the logs of this last test failure and the following is happening:

1.- Agent 003 (which is the one that can't reconnect), connected to the server at 10:58:37.

`2022/03/09 10:58:37 wazuh-agentd: INFO: (4102): Connected to the server ([nginx-lb/172.20.0.3]:1514/tcp).
`

2.- The cluster error happened.

`ossec.log`:

```
2022/03/09 10:58:57 wazuh-modulesd: ERROR: Cluster error detected
2022/03/09 10:58:57 wazuh-modulesd:agent-upgrade: ERROR: (8123): There has been an error executing the request in the tasks manager.
```

`cluster.log`:

```
2022/03/09 10:58:53 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/03/09 10:58:53 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/03/09 10:58:57 ERROR: [Local 862897] [Main] Internal error processing request 'b'sendsync'': Error 3023 - Worker node is not connected to master
2022/03/09 10:58:57 ERROR: [Local 862897] [Main] Error during connection with '862897': [Errno 104] Connection reset by peer.
  File "/var/ossec/framework/python/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)

2022/03/09 10:59:03 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/03/09 10:59:15 INFO: [Worker worker1] [Main] Sucessfully connected to master.
```

3.- A restart was done and after restarting, at 10:59:09, the agent tried to connect to the server and keeps trying with no success.

`2022/03/09 10:59:09 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.20.0.3]:1514/tcp).
`

As we can see, the cluster error happened between the first connection and the connection try done after the agent restart procedure. In other words, due to the cluster error, the agents could not reconnect to the cluster.

Taking this theory into account, the rest of the agents should have reconnected (after restart) BEFORE the cluster error.

Let's see agent 001:

2022/03/09 10:58:37 wazuh-agentd: INFO: (4102): Connected to the server ([nginx-lb/172.20.0.3]:1514/tcp).

2022/03/09 10:59:08 wazuh-agentd: INFO: (4102): Connected to the server ([nginx-lb/172.20.0.3]:1514/tcp).

As we can see, our theory cannot be confirmed as other agents has connected after the cluster error.

I keep investigating about this reconnection problem.

**Comment by mcarmona99** [comment]
## Issue update

I have run more API integration tests to see which commit introduced the error.


**Tests performed in commit: 8612adcf361e66cec62225b6abf89bd3eaf03546, 23 february "Allow API integration tests to be performed ..."**

Rootcheck and active response tests are failing.
Therefore, the change causing the agents disconnections may have been introduced before February 23rd.

**Tests performed in commit: 528ecbba9a65020d8d7116ca7cd8ab107a6a223a, 23 february "Applied requested changes"**

ALL tests have passed (tests that are known to be more likely to fail have been performed 4 times each)
Therefore, the change causing the agents disconnections may have been introduced after this commit.


After these 2 tests, we know that the error was added between commits "Allow API integration tests to be performed ..." and "Applied requested changes"

**Tests performed in comit: ae85dbebb63a6e1a79e56eb71ffe4adef415c1a8, 23 february "Merge pull request #12403 from wazuh/12301-fix-wpk-upgrade-rolling-ver"** 

ALL tests have passed (tests that are known to be more likely to fail have been performed 2 times each)
Therefore, the change causing the agents disconnections may have been introduced in the **"Allow API integration tests to be performed ..."**

The possible conflicting part of that commit could be the removal of the services' dependencies in the docker-compose.yaml file, as I said in the last comment. In fact, I don't think the original problem is that one but it could have helped the problem be seen.

Taking this into account, I have done more tests:

I have done manual tests inside a CI machine. After those tests, I can verify that the error reported in #11794 does not have to do with the error related to agents' disconnections. I can verify it because the cluster error appears in almost all API integration tests executions, so that is why we see them together, but as I said, they are NOT related.


Containers' status when the error occurs:

```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                            PORTS                      NAMES
4527f02669c2        integration_test_wazuh-agent_old   "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent8_1
ffb08eee09e8        integration_test_wazuh-agent_old   "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent7_1
d4dee3bfff22        integration_test_wazuh-agent_old   "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent6_1
147953afb2a3        integration_test_wazuh-agent_old   "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent5_1
18a508776eff        integration_test_wazuh-agent       "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent4_1
709a15ac262a        integration_test_wazuh-agent       "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (health: starting)                              env_wazuh-agent3_1
6884d1b3ba13        integration_test_wazuh-agent       "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent2_1
3f0fbcc68230        integration_test_wazuh-agent       "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-agent1_1
666929637be9        integration_test_wazuh-manager     "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (health: starting)   0.0.0.0:55000->55000/tcp   env_wazuh-master_1
5d8f008d5c42        integration_test_wazuh-manager     "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-worker2_1
ccb7732bdb6d        integration_test_nginx-lb          "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes                      80/tcp                     env_nginx-lb_1
f6c288fc6640        integration_test_wazuh-manager     "/scripts/entrypoint…"   7 minutes ago       Up 7 minutes (healthy)                                       env_wazuh-worker1_1
```


As we can see, the agent that could not reconnect is not healthy. Because of our implementation, 15 will be waited for the agent to connect, after that, the test will be performed and it will fail.


Cluster status:

```
root@wazuh-master:/# /var/ossec/bin/cluster_control -a
ID   NAME           IP           STATUS           VERSION        NODE NAME    
000  wazuh-master   127.0.0.1    active           Wazuh v4.4.0   master-node  
001  wazuh-agent1   172.28.0.6   active           Wazuh v4.4.0   worker2      
002  wazuh-agent2   172.28.0.7   active           Wazuh v4.4.0   worker1      
003  wazuh-agent3   172.28.0.8   disconnected     Wazuh v4.4.0   worker1      
004  wazuh-agent4   172.28.0.9   active           Wazuh v4.4.0   worker1      
005  wazuh-agent5   172.28.0.10  active           Wazuh v3.13.2  master-node  
006  wazuh-agent6   172.28.0.11  active           Wazuh v3.13.2  master-node  
007  wazuh-agent7   172.28.0.12  active           Wazuh v3.13.2  worker1      
008  wazuh-agent8   172.28.0.13  active           Wazuh v3.13.2  worker1      
009  wazuh-agent9   any          disconnected     Wazuh v3.9.2   master-node  
010  wazuh-agent10  any          disconnected     Wazuh v3.9.2   master-node  
011  wazuh-agent11  any          never_connected  unknown        unknown      
012  wazuh-agent12  any          never_connected  unknown        unknown      
```

Agent 003 ossec.log:

```
...
2022/03/10 12:29:34 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:29:44 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: 'nginx-lb/172.28.0.4'.
2022/03/10 12:29:44 wazuh-agentd: WARNING: Unable to connect to any server.
2022/03/10 12:29:44 wazuh-agentd: INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:29:44 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:29:54 wazuh-agentd: INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:29:54 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:30:04 wazuh-agentd: INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:30:04 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
root@wazuh-agent3:/# 
```

I have restarted agent 003 and the connection is not done:

```
...
2022/03/10 12:33:45 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:33:55 wazuh-agentd: INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:33:55 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:34:05 wazuh-agentd: INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 12:34:05 wazuh-agentd: INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
```

We can see the following in the worker1 ossec.log. Worker1 is the worker the agent 003 is trying to connect to.

```
...
2022/03/10 12:37:35 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:37:45 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:37:55 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:38:05 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:38:15 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
```

If we have a look at when these WARNING messages started: 


```
2022/03/10 12:23:52 wazuh-remoted: WARNING: Package dropped. Could not append data into buffer.
2022/03/10 12:23:52 wazuh-remoted: WARNING: Package dropped. Could not append data into buffer.
2022/03/10 12:23:53 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/03/10 12:23:53 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:24:03 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/03/10 12:24:13 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
```

Getting agent 003 information, we can see where it was disconnected and its related information.

```
{
   "data": {
      "affected_items": [
         {
            "os": {
               "arch": "x86_64",
               "codename": "Focal Fossa",
               "major": "20",
               "minor": "04",
               "name": "Ubuntu",
               "platform": "ubuntu",
               "uname": "Linux |wazuh-agent3 |5.4.0-1029-aws |#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020 |x86_64",
               "version": "20.04.1 LTS"
            },
            "version": "Wazuh v4.4.0",
            "dateAdd": "1970-01-01T00:00:00+00:00",
            "name": "wazuh-agent3",
            "status": "disconnected",
            "lastKeepAlive": "2022-03-10T12:23:47+00:00",
            "node_name": "worker1",
            "group": [
               "default",
               "group3"
            ],
            "disconnection_time": "2022-03-10T12:23:52+00:00",
            "ip": "172.28.0.8",
            "id": "003",
            "manager": "wazuh-worker1",
            "registerIP": "any",
            "mergedSum": "x"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected agents information was returned",
   "error": 0
}
```

The agent has the same IP as the one shown in the request response:

```
root@wazuh-agent3:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.28.0.8  netmask 255.255.0.0  broadcast 172.28.255.255
        ether 02:42:ac:1c:00:08  txqueuelen 0  (Ethernet)
        RX packets 2428  bytes 853607 (853.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2519  bytes 801405 (801.4 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 14  bytes 1138 (1.1 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 1138 (1.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Nothing can be seen if we set agentd in debug mode = 2

```
2022/03/10 14:39:46 wazuh-agentd[84788] start_agent.c:54 at connect_server(): INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 14:39:46 wazuh-agentd[84788] start_agent.c:86 at connect_server(): INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 14:39:46 wazuh-agentd[84788] start_agent.c:291 at receive_message(): DEBUG: Connection socket: Success (0)
2022/03/10 14:39:51 wazuh-agentd[84788] state.c:67 at write_state(): DEBUG: Updating state file.
2022/03/10 14:39:56 wazuh-agentd[84788] state.c:67 at write_state(): DEBUG: Updating state file.
2022/03/10 14:39:56 wazuh-agentd[84788] start_agent.c:54 at connect_server(): INFO: Closing connection to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 14:39:56 wazuh-agentd[84788] start_agent.c:86 at connect_server(): INFO: Trying to connect to server ([nginx-lb/172.28.0.4]:1514/tcp).
2022/03/10 14:39:56 wazuh-agentd[84788] start_agent.c:291 at receive_message(): DEBUG: Connection socket: Success (0)
2022/03/10 14:40:01 wazuh-agentd[84788] state.c:67 at write_state(): DEBUG: Updating state file.
```

If I restart worker1, the agent will connect to a different node (master or worker2) properly. If I restart the master node, all the agents will be reassigned to the nodes by nginx-lb and if I force the agent to connect to worker1, the agent will connect properly.

**Comment by davidjiglesias** [comment]
We should launch a couple of test bursts to validate the fixes have been correctly applied in https://github.com/wazuh/wazuh/issues/12776.

**Comment by fdalmaup** [comment]
# Issue Update

In another test burst, the tests `test_manager_endpoints.tavern.yaml` and `test_rootcheck_endpoints.tavern.yaml` have failed. 
We must carry out an in-depth investigation to determine the causes of these failures.

## Test report

[burst_results_4.4_with_failures.zip](https://github.com/wazuh/wazuh/files/9973831/burst_results_4.4_with_failures.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_DELETE_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 93 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_decoder_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_default_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_manager_endpoints.tavern.yaml | 31 | 0 | 0 | 0 | 1 |  | :red_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_vulnerability_endpoints.tavern.yaml | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_all_endpoints.tavern.yaml | 166 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_vulnerability_endpoints.tavern.yaml | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rootcheck_endpoints.tavern.yaml | 3 | 0 | 0 | 0 | 1 | | :red_circle: |
| test_rule_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml | 46 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_GET_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_POST_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_PUT_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscheck_endpoints.tavern.yaml | 35 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscollector_endpoints.tavern.yaml | 159 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_task_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_vulnerability_endpoints.tavern.yaml | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
The investigation related to the failed tests in the previous comment is being carried out in #15344.
