### ISSUE TITLE
sync-agent-groups-get wazuh-db command returns error response on a valid scenario

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#12490]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Wazuh-DB | Manager | Packages/Sources | Linux |

### Description

As part of the implementation in #10771 it was found that the Wazuh-DB command `sync-agent-groups-get` when it attempts to calculate the global hash groups (`"get_global_hash": true`), returns an error response when it is not possible to perform the task due to a lack of data. This is a valid scenario and it shouldn't return an error message. 

### Requirements

- [x] The `sync-agent-groups-get` command should return with `'ok', [{"data":[], "hash": null}]` if the the global hash can't be calculated because the group hash is not found.

### Testing required

- [x] Manual testing verifying that when log: `wdb_get_global_group_hash(): DEBUG: No group hash was found to calculate the global group hash.` shows up, there's no error response.
- [x] Update all the necessary unit test cases.

### DoD

- [x] All the requirements should be implemented.
- [x] Code review approved.
- [x] All the tests should pass successfully.
- [x] Scan-build execution without errors.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/12496 was merged.
