### ISSUE TITLE
Ability to clear disconnected agents without having to wipe client.keys file.

### ISSUE THREAD

**Issue by sc-chad** [wazuh/wazuh#125]
We use AWS with autoscaling, so we have instances coming and going quite often.

Having the ability to remove disconnected hosts via a command line like: http://stackoverflow.com/questions/39981732/how-to-automatically-remove-inactive-ossec-agents-batch

This finds all the hosts but we still need a way to clear them that's more programmatic.

BTW Awesome job on Wazuh 2.0.  Really well done!

**Comment by jlruizmlg** [comment]
HI @sc-chad, actually we don't have any option beside scripts like that to remove the disconnected or never connected.

Something that maybe can help, but only if you have a environment with Static IP's is run ossec-authd with the parameters -if0, info in the following documentation:

https://documentation.wazuh.com/current/user-manual/reference/daemons/ossec-authd.html?highlight=-f%20-i

Where if the requesting agent’s IP address is already registered, in that case the old registration is deleted and avoid the agent duplication.

**Comment by sc-chad** [comment]
Fair enough, I'd love to see it added as a cleanup script or something we can run via cron.  I'm sure others that are using or will be using Wazuh in AWS will need as well.

**Comment by crolopez** [comment]
HI,

It will be considered to include this feature in a future release so as not to depend on external tools. Currently it is possible to delete disconnected agents whose IPs are duplicated using [manage_agents](https://documentation.wazuh.com/current/user-manual/reference/tools/manage_agents.html?highlight=disconnected).

Let me close the issue.

Best regards.
