### ISSUE TITLE
Wazuh manager is not analyzing some logs coming from logcollector with multiline-regex settings

### ISSUE THREAD

**Issue by alejandroorg** [wazuh/wazuh#12502]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5     |Manager&Agent |AllInOne| Packages | Linux Centos 7|

Hello Team, we observed the following issue when trying to receive and analyze some logs from Oracle. The logs are properly read by the Wazuh agent as you can see in this image:

![image](https://user-images.githubusercontent.com/23264276/156736982-280f7df3-8cf5-4ab8-9af8-d51d1a4eb784.png)

There is no errors in `Logcollector`

The configuration used is the following:
```
<localfile>
   <log_format>multi-line-regex</log_format>
    <multiline_regex replace="wspace">^\w{3} \w{3} \d{2} \d{2}:\d{2}:\d{2} \d{4} \S{6}</multiline_regex>
    <location>/<path to your file>/*</location>
  </localfile
```

We checked `remoted` is analyzing the logs with the command `strace`:

```
close(5</u01/app/****/oracle/admin/****/adump>) = 0
lstat("/u01/app/****/oracle/admin/****/adump/****_j001_61443_20220222220007954211086104.aud", {st_mode=S_IFREG|0640, st_size=2709113, ...}) = 0
open("/u01/app/****/oracle/admin/****/adump/****_j001_61443_20220222220007954211086104.aud", O_RDONLY) = read(281</u01/app/****/oracle/admin/****/adump/****_ora_122418_20220223050624626808762906.aud>, "DBA'\nCLIENT USER:[6] 'oracle'\nCL"..., 4096) = 4096
```
However, after enabling the archival data, some logs appear in the archives and other doesn't.

Let me show you an example of it:

```
Wed Dec  1 13:07:20 2021 +05:30
LENGTH : '314'
ACTION :[7] 'CONNECT'
DATABASE USER:[3] 'SYS'
PRIVILEGE :[6] 'SYSDBA'
CLIENT USER:[4] 'root'
CLIENT TERMINAL:[0] ''
STATUS:[1] '0'
DBID:[10] '3320902093'
SESSIONID:[10] '4294967295'
USERHOST:[13] '...'
CLIENT ADDRESS:[54] '(ADDRESS=(PROTOCOL=tcp)(HOST=..)(PORT=..))'
ACTION NUMBER:[3] '100'
```

These seem not to be analyzed as it is not being written in the archives files although we can see it in `strace` `read(281</u01/app/****/oracle/admin/****/adump/****_ora_122418_20220223050624626808762906.aud>, "DBA'\nCLIENT USER:[6] 'oracle'\nCL"..., 4096) = 4096`:

```
Thu Nov 25 13:32:07 2021 +05:30
LENGTH : '160'
ACTION :[7] 'CONNECT'
DATABASE USER:[1] '/'
PRIVILEGE :[6] 'SYSDBA'
CLIENT USER:[6] 'oracle'
CLIENT TERMINAL:[5] 'pts/0'
STATUS:[1] '0'
DBID:[10] '3320902093
```

Let me know if you need more information.

Regards,

Miguel Casares

**Comment by MiguelCasaresRobles** [comment]
false positive
