### ISSUE TITLE
Implement configuration limits

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#12512]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Remoted/Clusterd | Manager | Packages/Sources | Linux |

### Description

The main purpose of this issue is to provide Wazuh Cloud with the ability to limit these parameters via configuration:

- The maximum number of EPS at a node level.

#### EPS limit

1. Set a limit of maximum EPS at a node level (worker node).
2. Know the limit status.
3. Know in real-time the number of EPS at a node level.
4. Events that surpass the limit will be dropped. The drops will not affect the status of the agents.
5. When a node is dropping events, know if it is due to the EPS limit being reached.
~~6. The limit can be disabled or changed on the go.~~
7. Should be possible to restrict access to this limit, so it can not be changed from Kibana/API but it can be retrieved.

**Comment by TomasTurina** [comment]
## New limits for Wazuh Cloud

### Configuration:

- New file in JSON format that includes the new configuration options:
  - `agents_limit` -> Maximum limit of agents that can be registered at the cluster level.
  - `eps_limit` -> Maximum limit of events per second that can be processed at the cluster level.
- This file must be found only on the master node and is read only at startup.
- Initially there are default values ​​for the new options.
- The values ​​can be modified using the API:
  - Upon receipt, the value in the file is updated.
  - The new value takes effect without the need to restart the manager.
- Only an admin user can modify these limits using the API (using RBAC).
- Any user can query these limits using the API.

### Agent limit:

- The master is in charge of registering the agents (current behavior).
- The master keeps track of registered agents and, once the limit is reached, it begins to reject them.
- The agent is notified of the reason why they were unable to register.
- The master must have two counters:
  - A counter of registered agents (already exists).
  - A counter of agents rejected for reaching the limit.

### EPS limit:

- The master must know the status of all nodes in the cluster.
- The EPS applies to time intervals to avoid generating a lot of network traffic with controls every second:
  - A fixed interval of 30 seconds is proposed.
  - The time intervals are controlled by the master node.
- Each node must keep two counters:
  - A global counter of processed messages (already exists). Control messages, which must always be processed, are excluded.
  - A global counter of messages discarded for reaching the EPS limit.
- At the beginning of the first interval:
  - The master sends a message to the nodes to identify them.
  - Each node identifies itself by responding to the master.
  - The master assigns each node a small initial EPS value.
    - A surplus of EPS can be saved in the master.
  - Each node updates its EPS limit and starts counting messages for the current interval.
- At the end of the following intervals:
  - The master sends a message to each node asking for its status.
  - Each node reports its status to the master indicating the total number of messages processed and discarded in the last interval.
    - In case a node does not report its status, it is considered down and its EPS is used in other nodes.
  - The master stores this information to make the decision to increase or decrease the EPS limit of some node.
    - The master can decide to remove the limit from some nodes to keep it as surplus.
    - If it is a new node, it is assigned a small initial value of EPS.
  - Each node updates its limit (if necessary), and restarts the message count for the new interval.
- When a node is close to reaching its limit:
  - It sends a message to the master requesting more limit to avoid starting to discard.
  - The master analyzes the order and, if available, it can assign from the remaining limit that was saved.
  - If available, the node updates its limit but without resetting the counters of the current interval.

**Comment by cborla** [comment]
```
' Copyright (C) 2015-2022, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2
@startuml remotd
    
    participant user
    box "Master" #LightBlue
    participant apid
    participant config
    participant clusterd
    participant authd
    end box

    user -> apid: API set limits
    apid -> config : set node EPS
    apid <-- config : ack
    user <-- apid : ack
    config -> clusterd : reload config
    config -> authd : reload config

@enduml
```
![image](https://user-images.githubusercontent.com/41765669/158262989-d325d0ca-4087-4698-ac95-c908b13e4e18.png)


```
' Copyright (C) 2015-2022, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2
@startuml remotd
    
    box "Master" #LightBlue
    participant clusterd
    end box
    box "Worker" #LightGrey
    participant remoted
    end box
    participant agent

    agent  -> remoted : events to proccess
    clusterd -> remoted : get workers status
    clusterd <-- remoted --++#gold :return counters
    note over clusterd : time period 10 s 
    agent  -> remoted : events to proccess
    clusterd -> remoted --#gold : get workers status
    clusterd <-- remoted --++#gold :return counters
    note over clusterd : time period 10 s 
    agent  -> remoted : events to proccess
    clusterd -> remoted --#gold : get workers status
    clusterd <-- remoted :return counters

@enduml
```
![image](https://user-images.githubusercontent.com/41765669/158263171-53917547-9c2d-44aa-b080-744a7204b948.png)

```
' Copyright (C) 2015-2021, Wazuh Inc.
' Created by Wazuh, Inc. <info@wazuh.com>.
' This program is free software; you can redistribute it and/or modify it under the terms of GPLv2
@startuml remotd
    
    box "Master" #LightBlue
    participant clusterd
    end box
    box "Worker" #LightGrey
    participant remoted
    end box
    participant agent

    loop
    agent  -> remoted : events to proccess
    clusterd -> remoted : get workers status
    clusterd <-- remoted : return counters
    clusterd -> remoted : set new counter limits
    clusterd <-- remoted --++#gold : ack
    agent  -> remoted : events to proccess
    agent  -> remoted : events to proccess
    agent  -> remoted : events to proccess
    clusterd <-- remoted : 90% EPS consumed
    agent  -> remoted : events to proccess
    agent  -> remoted : events to proccess
    agent  -> remoted : events to proccess
    end

@enduml
```
![image](https://user-images.githubusercontent.com/41765669/158263279-9d74e9e7-d4be-41ec-946d-fae62dc8f97e.png)

**Comment by vikman90** [comment]
## Validation of the requirements by the Product Owners

- [ ] @jesuslinares 
- [ ] @santiago-bassett
- [x] @vikman90

The design stage is blocked until the Product Owners sign off the requirements.
