### ISSUE TITLE
Agent is not restarting after received shared files

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#1251]
Found in the development branch 3.7.

When setting a new shared configuration and is pushed to the agent, the agent shows the following errors:

```
2018/09/07 15:50:46 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2018/09/07 15:50:46 ossec-execd: ERROR: WCOM Unrecognized command ''.
```

It is not restarted but the new shared files are stored correctly.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/1293.
