### ISSUE TITLE
Create a baseline of Vulnerability Detector scan results for all the supported OSs

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#12513]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/9220, we should modify the Vulnerability Detector module to allow the user to trigger scans on-demand. This will require many changes in the module that may affect the scan results.

In order to have a way to verify that at the end of the implementation the scanner behaves in the same way as before the implementation, we should create a baseline. The baseline should be made over a set of VMs that shouldn't receive any change during the development of the epic: no new packages nor uptades should be installed.

The list of OSs that should be scanned is:
- MacOS @DProvinciani 
- Centos @pereyra-m 
- Ubuntu @pereyra-m 
- Debian @pereyra-m 
- Arch @pereyra-m 
- ALAS @pereyra-m 
- RHEL @pereyra-m 
- Windows @DProvinciani 

In this issue we should attach all the feeds in order to configure them as offline feeds. In addition, after each scan we should upload the next artifacts for each OS:

- Agent database in the manager.
- Global database of the manager.
- Logs in debug2 for modulesd in the manager.

**Comment by pereyra-m** [comment]
# Baseline for Vulnerability Detector

- Branch: `dev-9220-vuln-det-on-demand`
- Offline feeds: [feeds](https://ufile.io/ejblo9fc). The file must be uncompressed under the `/var/ossec/etc/feeds` folder. 
- Configuration files: [configuration_files.zip](https://github.com/wazuh/wazuh/files/8181102/configuration_files.zip)

The configuration files enable debug logs for vulnerability detector and disable some noisy modules in the manager.

Each vagrant file prevents any box update or Guest Additions installation.

## Centos

- Box url: [CentOS 8](https://app.vagrantup.com/centos/boxes/8/versions/2011.0)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181142/Vagrantfile.zip)

 
## Debian

- Box url: [Debian Bullseye](https://app.vagrantup.com/debian/boxes/bullseye64/versions/11.20211230.1)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181144/Vagrantfile.zip)


## Arch Linux

- Box url: [Arch](https://app.vagrantup.com/archlinux/boxes/archlinux/versions/20220301.49177)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181152/Vagrantfile.zip)


## Ubuntu Focal

- Box url: [Ubuntu 20](https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20220215.1.0)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181153/Vagrantfile.zip)


## Amazon Linux 2

- Box url: [ALAS 2](https://app.vagrantup.com/bento/boxes/amazonlinux-2/versions/1.2.1)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181155/Vagrantfile.zip)


## Red Hat

- Box url: [RHEL8](https://app.vagrantup.com/generic/boxes/rhel8/versions/3.6.8)
- Vagrant file: [Vagrantfile.zip](https://github.com/wazuh/wazuh/files/8181157/Vagrantfile.zip)

**Comment by DProvinciani** [comment]
## Manager artifacts

- [global.db.zip](https://github.com/wazuh/wazuh/files/8185883/global.db.zip)
- [000.db.zip](https://github.com/wazuh/wazuh/files/8185879/000.db.zip)
- [ossec.log.zip](https://github.com/wazuh/wazuh/files/8185886/ossec.log.zip)

## Windows 7

- Box url: Local Virtual Machine
- Vagrant file: -
- Agent 001: **1148** vulnerabilities
- DB: [001.db.zip](https://github.com/wazuh/wazuh/files/8185872/001.db.zip)

## MacOS El Capitan

- Box url: Local Virtual Machine
- Vagrant file: -
- Agent 002: **1735** vulnerabilities
- DB: [002.db.zip](https://github.com/wazuh/wazuh/files/8185874/002.db.zip)

**Comment by DProvinciani** [comment]
Having completed the baseline of scan results, we close this issue.
