### ISSUE TITLE
Check possible implications of agent-group development on Wazuh repos

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#12537]
## Description

As part of the agent-groups development done in #10771, in this issue we are going to investigate the possible implications for all Wazuh repositories. This includes checking if changes need to be made to any of these repos:

- [x] https://github.com/wazuh/wazuh-qa
- [x] https://github.com/wazuh/wazuh
- [x] https://github.com/wazuh/wazuh-ansible
- [x] https://github.com/wazuh/wazuh-puppet
- [x] https://github.com/wazuh/wazuh-packages
- [x] https://github.com/wazuh/wazuh-docker
- [x] https://github.com/wazuh/wazuh-kubernetes

**Comment by Selutario** [comment]
## [Wazuh-qa](https://github.com/wazuh/wazuh-qa)

- [ ] [**test_integrity_sync**](https://github.com/wazuh/wazuh-qa/blob/master/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py) (probably updated in [2479](https://github.com/wazuh/wazuh-qa/issues/2479)): 
  - [ ] Files are created and deleted inside `queue/agent-groups/` (on lines [202](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py#L202-L204), [210](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py#L210), [219](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/system/test_cluster/test_integrity_sync/test_integrity_sync.py#L219)). 
  - [ ] Update docstrings in this test.
- [ ] [**test_agent_files_deletion**](https://github.com/wazuh/wazuh-qa/blob/master/tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py) (probably updated in [2479](https://github.com/wazuh/wazuh-qa/issues/2479)):
  - [ ] Remove agent-groups files path (on line [31](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.py#L31))
  - [ ] Update test [readme](https://github.com/wazuh/wazuh-qa/blob/master/docs/tests/system/test_cluster/test_agent_files_deletion/test_agent_files_deletion.md).
- [ ] [**add_agents_to_default_group**](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/add_agents_to_default_group.py): This script writes to the agent-groups files.
- [ ] [**test_authd_agents_ctx**](https://github.com/wazuh/wazuh-qa/blob/master/tests/integration/test_authd/test_authd_agents_ctx.py): 
  - [ ] Files are created or deleted inside `queue/agent-groups/` (on lines [136](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/integration/test_authd/test_authd_agents_ctx.py#L136), [172](https://github.com/wazuh/wazuh-qa/blob/26ca3fa059549c54d6756ab7a17ba756e855bcf7/tests/integration/test_authd/test_authd_agents_ctx.py#L172))
  - [ ] Update docstrings.

## [Wazuh](https://github.com/wazuh/wazuh)
Searched in [epic](https://github.com/wazuh/wazuh/issues/10771) branch, [dev-10771-agent-groups-files-to-wazuh-db](https://github.com/wazuh/wazuh/tree/dev-10771-agent-groups-files-to-wazuh-db):
- [ ] [**defs.h**](https://github.com/wazuh/wazuh/blob/993cdd6cf3209d077e10457106817ee3a3621146/src/headers/defs.h#L183-L184): `GROUPS_DIR` points to `queue/agent-groups/`. 
  - [ ] [test_wm_database](https://github.com/wazuh/wazuh/blob/dev-10771-agent-groups-files-to-wazuh-db/src/unit_tests/wazuh_modules/database/test_wm_database.c)
  - [ ] [wm_database.c](https://github.com/wazuh/wazuh/blob/dev-10771-agent-groups-files-to-wazuh-db/src/wazuh_modules/wm_database.c)

## [Wazuh-Ansible](https://github.com/wazuh/wazuh-ansible)
No references to agent-groups.

## [Wazuh-Puppet](https://github.com/wazuh/wazuh-puppet)
No references to agent-groups.

## [Wazuh-Packages](https://github.com/wazuh/wazuh-packages)
- [ ] [**wazuh-manager-4.4.0.spec**](https://github.com/wazuh/wazuh-packages/blob/8e15e617b9f0320c5e37a2b041eceeb44a4917f9/rpms/SPECS/4.4.0/wazuh-manager-4.4.0.spec#L699)

## [Wazuh-Docker](https://github.com/wazuh/wazuh-docker)
No references to agent-groups.

## [Wazuh-Kubernetes](https://github.com/wazuh/wazuh-kubernetes)
- [ ] [**upgrade.md**](https://github.com/wazuh/wazuh-kubernetes/blob/master/upgrade.md)
