### ISSUE TITLE
Logcollector is unable to connect to the socket suddenly

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#1254]
While running all the daemons fine, the logcollector module start to fail when connecting to the `analysisd` socket. The log file is flooded by the following log:

```
2018/09/07 03:11:13 ossec-logcollector: ERROR: socketerr (not available).
```

It happened to a manager built from the branch 3.7.

**Comment by crolopez** [comment]
It has been solved in https://github.com/wazuh/wazuh/pull/1267.
