### ISSUE TITLE
Confusing messages when getting agents configuration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#1255]
Related to the issue https://github.com/wazuh/wazuh-api/issues/154

The structure of the configuration queries is something like `.../agents/:agent_id:/config/socket/section?`

We have some cases where the retrieved messages could be confusing:

- Badly formatted query.

```
root@ubuntu:~# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/syscollector?pretty"
{
   "error": 603,
   "message": "The requested URL was not found on this server"
}
```

In this case, it would be useful to retrieve an error like this `The request is not formatted correctly` instead of `The requested URL was not found...`.

- The socket is not available or it not exists:

```
root@ubuntu:~# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/agents/001/config/wazuh/syscollector?pretty"
{
   "error": 1101,
   "message": "Error getting configuration: Maximum attempts exceeded"
}
```

The error shows that it has been attempted to connect to the socket but wasn't possible. It would be better to tell the user that the socket doesn't exist or is not allowed to connect to it. Related to this case, an error is shown on the agent side:

```
2018/09/07 16:32:21 ossec-agentd: ERROR: At req_push(): Target 'wazuh' not allowed
```

It is not an error for the agent, that message should be forwarded to the manager and show nothing on the agent side, or an info/debug message at most.

Finally, remove this debug message.

```
2018/09/07 16:32:07 ossec-agentd: ERROR: SENDING MSG: getconfig client
```

**Comment by TJOSERAFAEL** [comment]
This is fixed
