### ISSUE TITLE
src/wazuh_modules/wm_ciscat.c: support both CIS-CAT Pro V3 and V4

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#12581]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | CIS-CAT | Manager/Agent | Packages/Sources | all OSs |

Currently，the script name of the [CIS-CAT Pro v4](https://workbench.cisecurity.org/files/2151) is `Assessor-CLI.sh`
rather than `CIS-CAT.sh`

![image](https://user-images.githubusercontent.com/6824093/157020905-e7629100-55a0-4e36-b023-4d93f9b4fa89.png)

So it may be an error in [wm_ciscat.c](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/wm_ciscat.c#L431).

**Comment by vikman90** [comment]
@hustliyilin we're aware that the CIS-CAT integration works with CIS-CAT ≤ 3.0.43. Since that version, the CIS-CAT Pro output (XML) produces an unexpected format (#4972). In addition, there is another issue to update the CIS-CAT integration to support CIS-CAT Pro Assessor v4 (#6681).

However, we're deprecating the CIS-CAT integration module, in favor of [SCA](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/what-is-it.html), which perform scans of security policies based on CIS Benchmarks.

Best regards.

**Comment by hustliyilin** [comment]
> @hustliyilin we're aware that the CIS-CAT integration works with CIS-CAT ≤ 3.0.43. Since that version, the CIS-CAT Pro output (XML) produces an unexpected format (#4972). In addition, there is another issue to update the CIS-CAT integration to support CIS-CAT Pro Assessor v4 (#6681).
> 
> However, we're deprecating the CIS-CAT integration module, in favor of [SCA](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/what-is-it.html), which perform scans of security policies based on CIS Benchmarks.
> 
> Best regards.

Hi @vikman90,

Thanks for your reply.  From [CIS-CAT Pro v3](https://workbench.cisecurity.org/files/2255), We can found that 
- CIS-CAT Pro v3 will not be updated any more.
- If CIS-CAT ≤ v3.0.78, CIS-CAT will have a `log4j-core` vulnerability.

![image](https://user-images.githubusercontent.com/6824093/157853771-7c2f0980-33ba-4b78-b3c4-a69f8e5ea7c0.png)

So users will choose to use CIS-CAT Pro v4. Maybe it is better for wazuh to support CIS-CAT Pro v4 to fix the `log4j-core` vulnerability and support more CIS-CAT functions.

As for SCA, different OS systems have different CIS benchmarks. I opened [an issue](https://github.com/wazuh/wazuh/issues/12052) to support `Alibaba Cloud Linux (Aliyun Linux) 2` CIS SCA and pushed the [pr](https://github.com/wazuh/wazuh/pull/11875). But so far I haven't received any reviews. I hope that you can review it and wazuh can support the `CIS Alibaba Cloud Linux 2 benchmark`. 

For the OSs that wazuh doesn't support but CIS supports, The SCA can't be used normally.

Thanks again.

**Comment by vikman90** [comment]
Thank you very much @hustliyilin. I'm sorry you've not received any answer yet. I will ping the Threat Intelligence team to review your proposal.

**Comment by hustliyilin** [comment]
> Thank you very much @hustliyilin. I'm sorry you've not received any answer yet. I will ping the Threat Intelligence team to review your proposal.

Hi @vikman90 ,

Thank you very much for your quick reply. I have always wanted to use the SCA to support our own OSs.

But so far I haven't received any reviews from wazuh, so I changed to use the CIS-CAT function of wazuh. But if wazuh doesn't support CIS-CAT Pro V4 any more,  we don't know how to run wazuh on our own OSs with the CIS SCA or CIS-CAT.

I also thank you very much for your review of my patch, I'll try to support both CIS-CAT v3 and v4 as you suggested.

**Comment by hustliyilin** [comment]
Close this issue Now. Thanks @vikman90 .
