### ISSUE TITLE
Improve the user experience of the Vulnerability Detector inventory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#12580]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.3.0-RC5 | Vulnerability Detector | Manager |

### Description

The goal of this issue is to improve the UX of the new feature for Vulnerability Detector (https://github.com/wazuh/wazuh/issues/7749), whose highlights are:
- Including a vulnerability inventory with the reported CVEs for each agent
- Alerts are now focused on reporting changes in the inventory: when a vulnerability is added or solved

Development branch: [dev-12580-improve-vuln-det](https://github.com/wazuh/wazuh/tree/dev-12580-improve-vuln-det)

**Comment by asteriscos** [comment]
Hi team!

Here's a demo of Vulnerability Detector Inventory enhancement. It includes:

- New visualizations in _Vulnerabilities / Inventory_
- New fields when selecting an item details
- _Status_ field in _Vulnerabilities / Events_

![inventory-dashboard](https://user-images.githubusercontent.com/9343732/159280788-ebbf01f4-ce2d-4f33-b642-7d2ada9affda.gif)

![details](https://user-images.githubusercontent.com/9343732/159280812-e2ea9083-6c77-4bcc-b5c5-e699437e7743.gif)

![events-vulnerability-status](https://user-images.githubusercontent.com/9343732/159280843-e8a60857-f9b6-4622-a717-71ff1ebe0d2c.gif)
