### ISSUE TITLE
Wazuh SCCM mass deployment

### ISSUE THREAD

**Issue by irfaanaikagjee** [wazuh/wazuh#12590]
Hello Wazuh team,

I was suggesting if you could create a blog on how to deploy wazuh agents using Microsoft SCCM like we have for GPO and PDQ. We have some clients using sccm to deploy apps and as we don't have a procedure for this, it was difficult to help the clients.

Thank you

Kind regards,
Irfaan A.

**Comment by FrancoRivero** [comment]
Hi @irfaanaikagjee,
Thank for using Wazuh! 
We have some ways to deploy Wazuh agents for instance, [ansible](https://documentation.wazuh.com/current/deploying-with-ansible/index.html) or [puppet](https://documentation.wazuh.com/current/deploying-with-puppet/index.html) so this is a good suggest thank you for that! I move this suggestion to the content team.
Regards

**Comment by FrancoRivero** [comment]
[There is a issue in order to do this document](https://github.com/wazuh/wazuh-documentation/issues/2982). You could follow this document in that issue. 
Regards

**Comment by XavierBK** [comment]
> [There is a issue in order to do this document](https://github.com/wazuh/wazuh-documentation/issues/2982). You could follow this document in that issue. Regards

All of the photos in that document are currently dead.
