### ISSUE TITLE
Add new API endpoint to show a summary of vulnerabilities' fields from agents

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12620]
As part of the[ effort to improve the quality of the user experience for the vulnerability section in the Wazuh User Interface](https://github.com/wazuh/wazuh/issues/12580), we need to add a new API endpoint to obtain a summary of any of the fields from all vulnerabilities currently present in a selected agent.

The endpoint should be defined as follow:

`GET /vulnerability/{agent_id}/summary/{field}`

With a response like (for instance, using `field=severity`):

```
{
  "data": {
    "severity": {
      "critical": 8,
      "high": 0,
      "medium": 3,
      "low": 0,
    }
  },
  "error": 0
}
```

In addition, this endpoint should:

- Allow a `limit` parameter.
- Return its data in descending order.
- Inherit permissions handling from the main vulnerability endpoint `GET /vulnerability/{agent_id}`.

The work for this issue should also ensure to update everything related to the addition of a new endpoint, including:
- New API integration test cases
- New SDK + neccesary core functions
- New unit tests
- Documentation update in all required sections (https://github.com/wazuh/wazuh-documentation/issues/4908)

**Comment by vicferpoy** [comment]
# Issue update

After discussing this issue with the frontend team, its requirements have changed. Former development was finished but this new endpoint request requires a complete rework of it. Linked pull request will be kept as a draft until the new development is pushed in the same branch.
