### ISSUE TITLE
KVDB API interface

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#12631]
As part of https://github.com/wazuh/wazuh/issues/12481 we need to implement a Key-Value DB engine capable to search for keys and return values with high performance.
This DB should be updated by the user thru an API. We need to provide the entry point where the API command can be handled.
We should decide if this implementation will have it own socket or if it will lead on a generic socket endpoint of the Engine.
We should provide a parser for the commands received thru the socket to call the appropriate method of the KVDB engine.

**Comment by JcabreraC** [comment]
Closed. Development completed at https://github.com/wazuh/wazuh/issues/15274
