### ISSUE TITLE
Generate precompiled dependencies (only Windows) with debug information (-g flag)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#12657]
| Epic |
|---|
| wazuh/wazuh#9913|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0 | External dependencies | Agent | Sources | Windows |

## Description
This issue aims to generate the precompiled external dependencies with the debug information so that they can be extracted in later steps (basically when they are already part of the libwazuhext)

## DoD
- [x] Generate dependencies
  - [x] zlib
  - [x] curl
  - [x] openssl
  - [x] sqlite
  - [x] cJSON
  - [x] libyaml 
  - [x] libpcre2
- [x] Request upload to S3 -> @Dwordcito

**Comment by jnasselle** [comment]
Reopened due #12933
