### ISSUE TITLE
Create new configuration file limits.conf and make daemons reload it

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#12696]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | All | Manager | Packages/Sources | Linux |

### Description

A new configuration file named `limits.conf` needs to be created with the following characteristics:

- It should be in JSON format.
- It should have different sections for every daemon.
- It should be located at `WAZUH_PATH/etc/`.
- Daemons should be able to reload it without restart.

For the development of this issue, it should admit two options:

- `limits.wazuh-analysisd.max_eps` -> Maximum limit of events per second that can be processed at the node level.
- `limits.wazuh-analysisd.timeframe_eps` -> This is the timeframe (in seconds) used to apply the EPS limit.

### Requirements

- New file in JSON format called `limits.conf` that includes the new configuration options:
  - `limits.wazuh-analysisd.max_eps`
  - `limits.wazuh-analysisd.timeframe_eps`
- This file must be located in all the nodes in a cluster.
- Initially there are default values ​​for the new options:
  - `limits.wazuh-analysisd.max_eps` -> 0 (unlimited).
  - `limits.wazuh-analysisd.timeframe_eps` -> 10.
- Daemons should be able to reload their configuration without the need to restart.

### Proposed JSON example

```json
{
    "version": 1,
    "limits": {
        "wazuh-analysisd": {
            "max_eps": 50000,
            "timeframe_eps":30
        }
    }
}
```

### Proposed behavior

![image](https://user-images.githubusercontent.com/11877311/164529849-359f718d-55fc-4f21-8cd6-d5e7a637c5af.png)

**Comment by davidjiglesias** [comment]
Finally, the configuration parameter will be added to ossec.conf, no need to add a new file.
