### ISSUE TITLE
Syscheck: using wildcards cause some issues

### ISSUE THREAD

**Issue by LegitMigue** [wazuh/wazuh#1271]
Using wildcards in the middle of directory paths for syscheck configurations cause syscheck not scanning all the directories until an agent restart is done.
For example: setting syscheck to scan /opt/*/test/ will not scan all the directories and files in the wildcard path until a restart is done.

Is it possible to add some reload time watcher to avoid the need for an agent restart?
Also. About using wildcards in syscheck configuration. Is there a possibility to create some documentation or an expansion of it regarding the good use of wildcards?

**Comment by MiguelCasaresRobles** [comment]
This is issue is duplicated: https://github.com/wazuh/wazuh/issues/2723
