### ISSUE TITLE
How can send email alerts for specific rule/level

### ISSUE THREAD

**Issue by bentech4u** [wazuh/wazuh#12717]
We have installed new system and below are the components:

***Installed components:***
wazuh-manager-4.2.5-1
opendistroforelasticsearch-1.13.2-1
opendistroforelasticsearch-kibana-1.13.2-1
elasticsearch-oss-7.10.2-1
filebeat-7.10.2-1

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5-1 | opendistroforelasticsearch,elasticsearch-os,filebeat | Manager | Packages | Rocky 8.5 |

i would like to send email alerts whenever new incidents like below:

![image](https://user-images.githubusercontent.com/4426408/158327666-80c3b897-a0f2-4177-b0f8-2619ed37153c.png)

**Comment by antoniomanuelfr** [comment]
Hello @bentech4u 

You can use the `wazuh-maild` to send emails notifications based on the alerts that are triggered in the manager.

In the following links you can find more information about setting up the mail daemon:

- https://wazuh.com/blog/how-to-send-email-notifications-with-wazuh/
- https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html

In your case, you will need to use the `rule_id` option to specify which alerts will be sent by email.

```xml
<email_alerts>
  <email_to>you@example.com</email_to>
  <rule_id>5402, 5403</rule_id>
  <do_not_delay />
</email_alerts>
```

**Comment by bentech4u** [comment]
thanks for the update, let me try to do that

**Comment by bentech4u** [comment]
How can i test this, i have done some changes. is there any test email function available over application

**Comment by bentech4u** [comment]
when i added in configuration, i am getting below 

" Error saving configuration

Could not update configuration (1908) - Error validating configuration: (1230): Invalid element in the configuration: 'rule'., (1202): Configuration error at 'etc/ossec.conf'."

![image](https://user-images.githubusercontent.com/4426408/158352949-af1fb1c8-e8f1-4dec-8734-f3cec08ea100.png)

i added like above . and sorry for asking basic things as i am new to this

**Comment by bentech4u** [comment]
NO, i started getting email from all levels, which is not required for me.

**Comment by antoniomanuelfr** [comment]
Hello @bentech4u 

I have been testing the mail daemon behavior, and the `minimum severity level`  takes precedence over the configured `rule_id`

In order to avoid this behavior, I followed the next steps:
- I created a custom rule to catch the rule `5402`. This is because the wazuh rules may be overwritten in the update process, so you will need to configure it again, whether user rules are not overwritten. More info here https://documentation.wazuh.com/current/user-manual/ruleset/index.html. This is the rule that I added in `/var/ossec/etc/rules/local_rules.xml`:
```xml
<!-- Local rules -->
<group name="local,syslog,sshd,">
  <rule id="100001" level="5">
    <if_sid>5402</if_sid>
    <description>Successful sudo to ROOT executed.</description>
    <mitre>
      <id>T1548.003</id>
    </mitre>
    <options>alert_by_email</options>
    <group>pci_dss_10.2.5,pci_dss_10.2.2,gpg13_7.6,gpg13_7.8,gpg13_7.13,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AC.6,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
</group>              
```
- Then I used the following ossec.conf
```xml
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>yes</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>wazuh@example.wazuh.com</email_from>
    <email_to>recipient@example.wazuh.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>

<email_alerts>
  <email_to>you@example.com</email_to>
  <rule_id>5402, 5403</rule_id>
</email_alerts>
  <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>
```
- Finally, to check the behavior, I run the mail binary in debug mode:
```
2022/03/16 10:04:15 wazuh-maild[5601] maild.c:258 at OS_Run(): INFO: Getting alerts in log format.
2022/03/16 10:04:25 wazuh-maild[5601] os_maild_client.c:218 at OS_RecvMailQ(): DEBUG: OS_RecvMailQ: mail->body[
Wazuh Notification.
2022 Mar 16 10:04:24

Received From: ubuntumanager->/var/log/auth.log
Rule: 100001 fired (level 5) -> "Successful sudo to ROOT executed."
User: root
Portion of the log(s):

Mar 16 10:04:22 ubuntumanager sudo:  vagrant : TTY=pts/2 ; PWD=/home/vagrant ; USER=root ; COMMAND=/usr/bin/su
tty: pts/2
pwd: /home/vagrant
command: /usr/bin/su




 --END OF NOTIFICATION


]
```
To run the mail daemon in foreground and in debug mode, follow the next steps:
- Once you have configured the wazuh manager, restart it as normal.
- After that, you need to kill the maild process, you can use the following command: `pkill wazuh-maild`.
- Then, run the mail daemon in the foreground and debug mode: `/var/ossec/bin/wazuh-maild -fdd`. You can find the meaning of the options here https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-maild.html

Hope you find this useful

**Comment by bentech4u** [comment]
HI,

Thanks for the information. I am receiving email as i expected.

**Comment by antoniomanuelfr** [comment]
Nice, if you don't have any doubts, I'm closing this issue.

**Comment by steveytam** [comment]
hello @antoniomanuelfr , I'm currently using wazuh deployed in k8s which consist of 1 wazuh manager master and 2 wazuh manager worker, for this email alert configuration is it enough to configure it in wazuh manager master and restart it? or should it apply the same XML in wazuh manager worker as well? thank you!
