### ISSUE TITLE
Change Makefile to generate/extract symbols files at src/symbols during post-compilation (last step of project build) (only macOS)

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#12711]
| Epic |
|---|
| wazuh/wazuh#9913|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0 | Makefile | Agent | Sources | macOS |

## Description
This issue aims to extract the symbols (strip) once the generation of the binaries is done, this task is done as long as the variable `STRIP_SYMBOLS` is true, the output directory of this is wazuh/src/symbols

The default extension for symbols bundle should be .dSYM

Execute this task, based on the result of this spike: https://github.com/wazuh/wazuh/issues/9910#issuecomment-1064021763

## DoD
- [ ] Execute dsymutil against binaries that will be part of the agent as post generation task     
- [ ] Strip debug information of those binaries if `STRIP_SYMBOLS` is true

**Comment by RamiroRD** [comment]
Currently updating the makefile to use a static pattern rule that automatically generates the .dSYM folders in symbols/ from a list of executables and shared libraries that need to be stripped.
The following commands should be able to find all executables and shared libraries on macOS (they are meant to be run on `<repo root>/src`:
```
find . -maxdepth 1 -type f -not -path "./external/*"  -exec /bin/sh -c "file {} | grep 'bit executable' > /dev/null" \; -print 
find . -type f -not -path "./external/*" -name  "*.dylib" -print 
```
The only executable excluded here would be the sysinfo test tool, which should be fine.
