### ISSUE TITLE
Generate precompiled dependencies (only macOS) with debug information (-g flag)

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#12710]
| Epic |
|---|
| wazuh/wazuh#9913|

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0 | External dependencies | Agent | Sources | macOS |

## Description
This issue aims to generate the precompiled external dependencies with the debug information so that they can be extracted in later steps (basically when they are already part of the libwazuhext)

Ex: `cd src/external && tar -zcf archive.tar.gz --owner=0 --group=0 audit-userspace`

## DoD
- [x] Generate dependencies
- [x] Request upload to S3 -> @Dwordcito 
- [x] Test compilation

**Comment by RamiroRD** [comment]
Ran into an issue where OpenSSL would not compile in macOS (even all the way back to Sierra). We decided we will update the OpenSSL version (since this issue is theirs and also fixed in a later version).

**Comment by RamiroRD** [comment]
Verified that the the compilation process is working on macOS Monterey with Sierra precompiled dependencies.
