### ISSUE TITLE
Add new authd command to reload max_agents limit on demand

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12720]
As part of the development for [Implement configuration limits requested by Wazuh Cloud #12512 ](https://github.com/wazuh/wazuh/issues/12512) we need to add a new command for authd to be able to reload the `max_agents` limit configuration on demand. The Wazuh API should tell authd to reload the configuration after any change is applied to it.

The exact command design is yet to be defined.

**Comment by TomasTurina** [comment]
Won't do.
