### ISSUE TITLE
Migrate agent-group files to wazuh-db - Exploratory after rebase

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#12722]
## Description

After merging the `master` branch in the development branch `dev-10771-agent-groups-files-to-wazuh-db` for the Epic #10771, it is necessary to perform some tests to make sure that all the features still work as expected.

### Wazuh-DB commands

- [x] All the test cases developed for the script `WDB_tester` should pass successfully https://github.com/wazuh/wazuh/issues/12722#issuecomment-1068469226

### Agents management - Single node

https://github.com/wazuh/wazuh/issues/12722#issuecomment-1068506007

- [x] Register agents with and without groups
- [x] Verify that the shared files are delivered to the right agents
- [x] All the groups information is inserted in the DB correctly
- [x] Assign new groups to the agents
- [x] Remove groups for an agent
- [x] Remove all groups for an agent (**default** assignation expected)

## DoD

- [x] All the tests should pass and the corresponding evidence should be documented
- [x] No error nor warning messages should be found in the logs for any test (see update https://github.com/wazuh/wazuh/issues/12722#issuecomment-1071248164)

**Comment by pereyra-m** [comment]
### Agents management - Single node

**Agent registered without group**

The agent was registered manually with the `agent_auth` binary.

```
./bin/agent-auth -A agent2 -m 192.168.0.10
```

Some warnings are generated the first time the agent got connected
```
2022/03/15 18:08:06 wazuh-authd: INFO: New connection from 192.168.0.99
2022/03/15 18:08:06 wazuh-authd: INFO: Received request for a new agent (agent1) from: 192.168.0.99
2022/03/15 18:08:06 wazuh-authd: INFO: Agent key generated for 'agent1' (requested by any)
2022/03/15 18:08:10 wazuh-remoted: WARNING: (1408): Invalid ID 001 for the source ip: '192.168.0.99' (name 'unknown').
2022/03/15 18:08:14 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/03/15 18:08:14 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

But all the information of the agent is properly stored in the DB after it connects with the manager

![agent_with_no_groups](https://user-images.githubusercontent.com/65046601/158473514-96541dde-18f7-4ae5-b835-14584380d346.png)

It should analyzed if the ipv6 IP should be used by default or not.
This is the information of the agent

![ipv6](https://user-images.githubusercontent.com/65046601/158473943-821351e9-f2fb-4e15-899f-1a83dcc9f282.png)

**Agent registered with single/multi group**

A new `group1` was created.
The agent was registered with a single group

```
./bin/agent-auth -A agent2 -m 192.168.0.10 -G group1
```

Some warning messages were generated when the agent connected to the manager
```
2022/03/15 18:17:05 wazuh-remoted: WARNING: Package dropped. Could not append data into buffer.
```

The DB has all the corresponding fields
![agent_registered_with_group](https://user-images.githubusercontent.com/65046601/158474649-1e8f8b35-d4a0-4b64-8e61-5c6b9fd8bf85.png)

A new `group2` was created and the agent was registered again

```
./bin/agent-auth -A agent3 -m 192.168.0.10 -G group1,group2
```

All the corresponding fields were inserted
![registered_multi_groups](https://user-images.githubusercontent.com/65046601/158475081-e48ea66f-1807-4d2d-9bba-6357ce5addf4.png)

**Groups removal**

The agent's groups were removed one by one using the **agents_groups** binary and the agent restarted every time due to the changes in the centralized configuration.
When the last group was removed, the **default** group was assigned automatically.

![default_automatically_assigned](https://user-images.githubusercontent.com/65046601/158475705-57b25f6a-c69e-48db-9eda-14eab2f7a58f.png)

It was noted that even when the environment is single node, the `group_sync_status` column was set to **syncreq** instead of **synced**.

**Groups adding**

When the agent only had the **default** group assigned, the **group1** was added to the agent.
The DB was updated correctly, although the  `group_sync_status` column remains in **syncreq** state

![group_adding](https://user-images.githubusercontent.com/65046601/158476511-e30db784-f724-40a6-95f4-b4d908677448.png)

Some error messages were found
```
2022/03/15 18:31:18 wazuh-remoted: ERROR: No such group 'default,group1' for agent '003'
```

**Shared files**

Some test files were generated in the manager for each group folder (`etc/shared`):
- **group1**: group1_file
- **group2**: group2_file
- **default**: default_file

Then, some combination of groups were tested for the agents and it was confirmed that the right files arrived the `etc/shared` file in the agent. For example: 

![groups_example](https://user-images.githubusercontent.com/65046601/158478067-4094065a-b0bd-40aa-a9d1-26f4407078c1.png)

![centralized_files](https://user-images.githubusercontent.com/65046601/158478059-18d8f84c-7726-4f4d-ad6e-534dd7121849.png)

But many errors were found, they seem related to some race condition

![error_messages](https://user-images.githubusercontent.com/65046601/158478170-b5e15c0b-f4a8-4374-8824-6091595d4296.png)

**Comment by pereyra-m** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Subzero-6038ea078457e2001f8bac2d/issues/wazuh/wazuh/12722?planning-poker) with ZenHub @DProvinciani

**Comment by pereyra-m** [comment]
## Update

The reported messages during the exploratory were analyzed.

### ERROR message

The following error message

```
2022/03/16 18:01:22 wazuh-remoted[99370] manager.c:372 at save_controlmsg(): ERROR: No such group 'default,group1,group2' for agent '001'
```

It is related to a race condition among the `c_files()` method and the first keepalive of the first agent of a multigroup.
The hash of the multigroup is calculated every certain fixed period of time but only if there is at least one agent in that multigroup. Then, if the first agent of that multigroup connects to the manager before the `c_files()` method reads all the groups of the agents, we'll find this ERROR message.

This condition isn't frequent but it doesn't represent any harm. The next time the manager receives a keepalive from that agent, it'll try to find that multigroup in the `multi_groups` list. 

So, it was decided with the team that this message will be DEBUG instead of ERROR.

### WARNING message

The following message

```
2022/03/15 18:08:10 wazuh-remoted: WARNING: (1408): Invalid ID 001 for the source ip: '192.168.0.99' (name 'unknown').
```

It is also related to a race condition between the `client.keys` file read and the first keepalive of a recently registered agent.
Here we can see in another test that the message is only printed if the agent connects to the manager before the keys' file reload

```
2022/03/16 18:48:58 wazuh-remoted[107534] secure.c:488 at HandleSecureMessage(): WARNING: (1408): Invalid ID 008 for the source ip: '192.168.0.99' (name 'unknown').

2022/03/16 18:48:59 wazuh-remoted[107534] sendmsg.c:60 at check_keyupdate(): INFO: (1409): Authentication file changed. Updating.
```

In this case, the manager is notified of a change in `client.keys` immediately, there is no fixed period. Also, we can see above that both timestamps happened almost at the same time. 

This situation only happens if the agent register and connects quickly, the smallest delay between these two steps will give the manager enough time to read the new key.
This message is important for other situations and it was decided not to modify it.

**Comment by DProvinciani** [comment]
With the analysis of the `ERROR`s and `WARNING`s logs, and the fixes implemented for the tests and logs, we close this issue.
