### ISSUE TITLE
Syscheck: duplicate folders with different configurations

### ISSUE THREAD

**Issue by LegitMigue** [wazuh/wazuh#1273]
If I want to monitor a directory for a specific agent and I want to monitor that same directory but using a "restrict" option in a different agent syscheck will show a duplicated directories error.

Example:

```
<agent_config name="agent1">
  <syscheck>
    <directories check_all="yes">/opt/test/</directories>
  </syscheck>
</agent_config>

<agent_config name="agent2">
  <syscheck>
    <directories check_all="yes" restrict="!.log$|.bak$|.backup$">/opt/test/</directories>
  </syscheck>
</agent_config>
```

**Comment by bah07** [comment]
Hi @LegitMigue , from now the remote configuration overwrite a `ossec.conf` directories.

Regards.
