### ISSUE TITLE
WARNING: (XXXX): Unavailable vulnerability data for the agent 'XXX' OS. Skipping it.

### ISSUE THREAD

**Issue by matthew-williams** [wazuh/wazuh#12765]
| Wazuh | Elastic | Rev  | Security |
| ----- | ------- | ---- | -------- |
| 4.2.2   | 7.x     | 40216 | Basic|

| Browser |
| ------- |
| Chrome,Firefox|

**Description**
So, in my troubleshooting of the `vulnerability-detector` I have discovered that it ignores any agent on an AWS linux host and all of the managers/workers in my daemonset return the following error during vulnerability scans:

```
2022/03/16 18:37:17 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '027' vulnerabilities.
2022/03/16 18:37:17 wazuh-modulesd:vulnerability-detector: WARNING: (5575): Unavailable vulnerability data for the agent '027' OS. Skipping it.
```

**Preconditions**
`uname -r`
devops-corp-eks-worker-XXXX:
    5.11.0-1028-aws
devops-corp-eks-worker-XXXX:
    5.11.0-1028-aws

**Steps to reproduce**
1. Have any non debian,ubuntu,redhat,windows agents

**Expected Result**
1. I assumed that because it couldn't resolve the OS as one listed in:

```
<vulnerability-detector>
      <enabled>yes</enabled>
      <interval>1h</interval>
      <ignore_time>36h</ignore_time>
      <run_on_start>yes</run_on_start>

      <!-- Ubuntu OS vulnerabilities -->
      <provider name="canonical">
        <enabled>yes</enabled>
        <os>trusty</os>
        <os>xenial</os>
        <os>bionic</os>
        <os>focal</os>
        <update_interval>1h</update_interval>
      </provider>

      <!-- Debian OS vulnerabilities -->
      <provider name="debian">
        <enabled>no</enabled>
        <os>stretch</os>
        <os>buster</os>
        <update_interval>1h</update_interval>
      </provider>

      <!-- RedHat OS vulnerabilities -->
      <provider name="redhat">
        <enabled>no</enabled>
        <os>5</os>
        <os>6</os>
        <os>7</os>
        <os>8</os>
        <update_interval>1h</update_interval>
      </provider>

      <!-- Windows OS vulnerabilities -->
      <provider name="msu">
        <enabled>yes</enabled>
        <update_interval>1h</update_interval>
      </provider>

      <!-- Aggregate vulnerabilities -->
      <provider name="nvd">
        <enabled>yes</enabled>
        <update_from_year>2010</update_from_year>
        <update_interval>2h</update_interval>
      </provider>

  </vulnerability-detector>
```
it should default to just using the `<!-- Aggregate vulnerabilities -->`

**Actual Result**
1. Instead it just gives up.
2. On ones it does scan, I get no results whatsoever. No negatives, but no confirmation in either the UI that it was scanned:
```
2022/03/16 17:37:16 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '007' vulnerabilities.
2022/03/16 17:37:16 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '007'
```

![image](https://user-images.githubusercontent.com/6619443/158697062-bf9ecaa5-d48f-4bfb-b3fc-faae792b8312.png)

**My actual questions**
1. How does one force non recognized OS's to be scanned, by redhat, cause its the closest OS to AWS (aws is based on redhat)?
2. Does the Aggregate just contain the database that the OS sections use to scan or is it supposed to be a catch all (what I read it as)?
3. Why is there no generation of a passing, clean slate alert? ( I can make that part into a request somewhere I guess)
   a. I assume it only generates logs/alerts on failures, but as a clean scan is one of the necessities for most audits it would be handy to have something more than 0 alerts to show for it.

**Comment by DProvinciani** [comment]
Something else very important to mention here is the fact that we already implemented the support for ALAS in the Vulnerability Detector module. This is going to be released in the upcoming versions.

- https://github.com/wazuh/wazuh/issues/6734

**Comment by matthew-williams** [comment]
This is perfect and thank you for the response I think this solves my issues/answers my questions!!
