### ISSUE TITLE
`Agent-groups` sync task in cluster could go into a loop

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#12780]
## Description

I have come across a situation that could cause the cluster's `Agent-groups recv` task to consume too many resources. 

The problem would occur if a user manually and incorrectly modifies the database or if for some reason wazuh-db does not work as expected. This should not be a common situation, but due to the way it affects the cluster, it is important to make some corrections.

https://github.com/wazuh/wazuh/blob/1d5f8effb89682cdc21d731b7fdb8f42e277099d/framework/wazuh/core/cluster/worker.py#L493-L498

The above functions are executed both when **some** `agent-groups` are received from the master and also when **all** **agent-groups** are received, as part of the security mechanism.

If due to some incorrect use or because of an error in wazuh-db, the database is not updated in the worker, it will start asking for a new db to the master again and again forever and very fast:
```
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.002s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.002s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.002s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.002s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.003s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Finished in 0.002s. Updated 1 chunks.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Starting.
2022/03/18 09:32:16 INFO: [Worker worker1] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
```

It could be related to https://github.com/wazuh/wazuh/issues/12762. The new `recv_agent_groups_entire_information` method should not compare checksums or ask the master for the entire db. It should only be done in `recv_agent_groups_information`.

Otherwise, the worker starts requesting the db many times per second, so even if the problem is only related to agent-groups, the rest of the tasks in the cluster would be affected.

## How to reproduce

1. Update master's `global.db` to change the `group_hash` of an agent: 
  ```
  global sql update agent set \`group\`='test_group', group_hash='1fce4f24', group_config_status='not synced' where id=1
  ```
2. Restart the master.
3. Wait until agent-groups send task is started and check `cluster.log`.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by AdriiiPRodri** [comment]
## Status update

After investigating this bug, we have seen that what happens if in some way not controlled by WDB the checksum of groups of some agent is changed, it will not be recalculated until there is a change in the groups of the agent. Therefore, the following situation occurs:

1.- The master node sends to the worker node the unsynchronized information of its DB together with the global checksum (calculated based on the checksum of each agent).
2.- The worker node receives and processes the information, finally it compares the checksum of its database with the one received from the master.
3.- At this point we have that the master checksum is not valid because something has modified some registry, therefore, the worker requests to the master all the information because its DB does not have the same checksum.
4.- The master node sends all the group information together with the global checksum.
The worker node receives the information and compares again, since the master has not recalculated the committed checksum, we would return to step 2, in this way step 2, 3, 4 would be constantly repeating.

To solve this we have chosen not to compare the checksum when the master sends the whole database, theoretically everything should be the same after this so we will not check the checksum, in case something does not work as it should, the periodic sending of data from master to worker will be in charge of requesting again all the information to the master.

In this way, we have suppressed the checksum sending when we send the whole database from the master to the worker, as the worker does not detect the **hash** key, it omits the checksum comparison.

```
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w''
2022/03/21 14:42:29 INFO: [Worker worker2] [Agent-groups recv] Starting.
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.001107s.
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Agent-groups recv] Obtained 1 chunks of data in 0.000s.
2022/03/21 14:42:29 DEBUG2: [Worker worker2] [Agent-groups recv] There is no data requiring synchronization in the local database.
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7f3fafd37c63ee7e224dc8c099686f3777d22fc6 | Master checksum: 79a32e77abcb36754e3e12e07dd7fc135de87d19.
2022/03/21 14:42:29 INFO: [Worker worker2] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/21 14:42:29 INFO: [Worker worker2] [Agent-groups recv] Finished in 0.008s. Updated 1 chunks.
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Main] Command received: 'b'new_str''
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Main] Command received: 'b'str_upd''
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w_c''
2022/03/21 14:42:29 INFO: [Worker worker2] [Agent-groups recv full] Starting.
2022/03/21 14:42:29 DEBUG: [Worker worker2] [Agent-groups recv full] 1/1 chunks updated in wazuh-db in 0.001083s.
2022/03/21 14:42:29 INFO: [Worker worker2] [Agent-groups recv full] Finished in 0.005s. Updated 1 chunks.
...
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w''
2022/03/21 14:42:39 INFO: [Worker worker2] [Agent-groups recv] Starting.
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.000625s.
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Agent-groups recv] Obtained 1 chunks of data in 0.001s.
2022/03/21 14:42:39 DEBUG2: [Worker worker2] [Agent-groups recv] There is no data requiring synchronization in the local database.
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7f3fafd37c63ee7e224dc8c099686f3777d22fc6 | Master checksum: 79a32e77abcb36754e3e12e07dd7fc135de87d19.
2022/03/21 14:42:39 INFO: [Worker worker2] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/21 14:42:39 INFO: [Worker worker2] [Agent-groups recv] Finished in 0.009s. Updated 1 chunks.
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w_c''
2022/03/21 14:42:39 INFO: [Worker worker2] [Agent-groups recv full] Starting.
2022/03/21 14:42:39 DEBUG: [Worker worker2] [Agent-groups recv full] 1/1 chunks updated in wazuh-db in 0.002178s.
2022/03/21 14:42:39 INFO: [Worker worker2] [Agent-groups recv full] Finished in 0.007s. Updated 1 chunks.
...
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w''
2022/03/21 14:42:49 INFO: [Worker worker2] [Agent-groups recv] Starting.
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.000825s.
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Agent-groups recv] Obtained 1 chunks of data in 0.001s.
2022/03/21 14:42:49 DEBUG2: [Worker worker2] [Agent-groups recv] There is no data requiring synchronization in the local database.
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7f3fafd37c63ee7e224dc8c099686f3777d22fc6 | Master checksum: 79a32e77abcb36754e3e12e07dd7fc135de87d19.
2022/03/21 14:42:49 INFO: [Worker worker2] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/21 14:42:49 INFO: [Worker worker2] [Agent-groups recv] Finished in 0.009s. Updated 1 chunks.
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w_c''
2022/03/21 14:42:49 INFO: [Worker worker2] [Agent-groups recv full] Starting.
2022/03/21 14:42:49 DEBUG: [Worker worker2] [Agent-groups recv full] 1/1 chunks updated in wazuh-db in 0.001346s.
2022/03/21 14:42:49 INFO: [Worker worker2] [Agent-groups recv full] Finished in 0.006s. Updated 1 chunks.
...
2022/03/21 14:42:59 DEBUG: [Worker worker2] [Main] Command received: 'b'syn_g_m_w''
2022/03/21 14:42:59 INFO: [Worker worker2] [Agent-groups recv] Starting.
2022/03/21 14:42:59 DEBUG: [Worker worker2] [Agent-groups recv] 1/1 chunks updated in wazuh-db in 0.000416s.
2022/03/21 14:42:59 DEBUG: [Worker worker2] [Agent-groups recv] Obtained 1 chunks of data in 0.000s.
2022/03/21 14:42:59 DEBUG2: [Worker worker2] [Agent-groups recv] There is no data requiring synchronization in the local database.
2022/03/21 14:42:59 DEBUG: [Worker worker2] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7f3fafd37c63ee7e224dc8c099686f3777d22fc6 | Master checksum: 79a32e77abcb36754e3e12e07dd7fc135de87d19.
2022/03/21 14:42:59 INFO: [Worker worker2] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2022/03/21 14:42:59 INFO: [Worker worker2] [Agent-groups recv] Finished in 0.006s. Updated 1 chunks.
```
