### ISSUE TITLE
Mark atomic operations with transaction flag set to 1.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#12788]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-rev | DBSync| Agent | Packages/Sources | All |

## Description
This issue points to the fact that the `SyncRow` atomic operations mark the transaction's operations identifier field with the status flag.

The reason for this is that atomic operations within a scheduled scan are not removed, nor are they reported.

## DoD
- [ ] Add status flag for atomic operations.
- [ ] Modify unit tests if is necessary.
- [ ] Modify diagrams if is necessary.
- [ ] PR CI Green

**Comment by Damian-Mangold** [comment]
The error cannot be reproduced.

The implementation has been analyzed and in the following [line of code](https://github.com/wazuh/wazuh/blob/12788-atomic-operation/src/shared_modules/dbsync/src/sqlite/sqlite_dbengine.cpp#L274) we can see that the flag is set to 1 when the fields are initialized.

![image](https://user-images.githubusercontent.com/106940255/190438836-c906aae9-2a54-4f44-a6e3-be7620c8beb0.png)


[Added a unit test](https://github.com/wazuh/wazuh/blob/12788-atomic-operation/src/shared_modules/dbsync/tests/interface/dbsync_test.cpp#L1901) to verify that the behavior is correct and to validate that what the issue asks for is already implemented.

![image](https://user-images.githubusercontent.com/106940255/190431185-f988d178-9136-420c-85fb-d6b0755f2fb6.png)

A summary of the steps executed in the test are: a transaction is opened, an element is added with syncTxnRow, an element is added (atomic operations) with syncRow, the transaction is closed and finally it is verified that the two elements exist.
