### ISSUE TITLE
Make the netstat call a command

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1279]
The local file entry for _netstat_ is too long:

```xml
<localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+$
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>
```

This call should be in a script instead of a configuration file.

**Comment by juergenc** [comment]
Hello @vikman90,

you might the suggestions I made into consideration in the tickets:
* #1608 
* #1610

**Comment by vikman90** [comment]
This issue will be tackled during 5.0 development as part of state changes in the inventory module using the new analysis engine's ruleset.
