### ISSUE TITLE
Monitor File System Calls on Windows

### ISSUE THREAD

**Issue by leotant** [wazuh/wazuh#128]
Hi,

I am trying to use my Wazuh server (installed on Ubuntu 16.04) to monitor the system calls on a Windows 7 x64 Professional machine (where my agent is installed). I read the documentation under https://documentation-dev.wazuh.com/user-manual/system-calls-monitoring/index.html 
but it seems like Auditd is only available to monitor events in a linux-based system. 

Ideally, I would like Wazuh to log the system calls that occur in my Windows machine so that I can generate a process tree off of them. Is there any way to do this?

Thanks in advance

**Comment by snaow** [comment]
Hi @leotant,

You are correct, Auditd is only available to monitor events in a linux-based system.
Windows offers us others possibilities, for example "Objects auditing" and GPO's.

Depending on what system calls you want to monitor, we could enable auditing for a certain event and extract information from it using the manager.

Best,
Pedro.
