### ISSUE TITLE
ossec-authd must be enabled by default

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#1280]
Hi all,

For new installations, starting version 3.8, the registration service `ossec-authd` should be enable by default, starting as a daemon with no extra steps required.

On the current version, the following command is required:

`/var/ossec/bin/ossec-control enable auth`

Thanks,
Pedro.

**Comment by albertomn86** [comment]
Merged https://github.com/wazuh/wazuh/pull/2129
