### ISSUE TITLE
OpenSSL dependency can't be compiled on macOS Catalina

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#12807]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0 - master | External dependency | Agent | Sources | macOS Catalina |

## Description
It was found that current OpenSSL version (1.1.1l), updated in #10247, cannot be compiled AT least in macOS Catalina and BigSur (other versions should be validated as well) showing the next error
```
/usr/include/CommonCrypto/CommonRandom.h:35:9: error: unknown type name 'CCCryptorStatus'
typedef CCCryptorStatus CCRNGStatus;
        ^
crypto/rand/rand_unix.c:385:47: error: use of undeclared identifier 'kCCSuccess'
    if (CCRandomGenerateBytes(buf, buflen) == kCCSuccess)
                                              ^
2 errors generated.

```
## Steps
1. Clone the wazuh/wazuh repository
2. Download external deps sources running `make deps -C src EXTERNAL_SRC_ONLY=y TARGET=agent `
3. Try to compile the project running `make -C src TARGET=agent `

## RCA
Seems to be solved in this PR https://github.com/openssl/openssl/pull/16409, part of OpenSSL 1.1.1m release

## DoD
- [ ] Validate that OpenSSL 1.1.1m solves this problem. If true, update it and validate any API change.
- [ ] Upload source package to S3
- [ ] Upload precompiled packages to S3

**Comment by RamiroRD** [comment]
This also happens in 10.12 (Sierra)
![Screen Shot 2022-03-29 at 16 49 08](https://user-images.githubusercontent.com/6182640/160695217-861317ff-fb8f-4c66-a078-4f3040435374.png)

**Comment by RamiroRD** [comment]
We decided to update OpenSSL to the 1.1.1n version. 
To generate the openssl.tar.gz source dependency we are following these steps:
```
wget -c https://www.openssl.org/source/openssl-1.1.1n.tar.gz
tar -zxf openssl-1.1.1n.tar.gz
mv openssl-1.1.1n openssl
sudo chown -R 0:0 openssl
sudo tar -zcpf openssl.tar.gz openssl
```

**Comment by jnasselle** [comment]
Given the fact that the OpenSSL dependency cannot be OOT compiled on any supported version of macOS, upgrading to 1.1.1n is absolutely necessary.
Closing in favor of #12933
