### ISSUE TITLE
Wazuh agent is unable to stop the service until RSYNC finishes

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#12801]
## Description
Hi team, doing some testing of the fimDB change, we have discovered that when stopping the wazuh process, wazuh-syscheckd is waiting for the FIM sync to finish. This can generate too long waits in some cases.

It is not something that is going to affect the databases since when starting the wazuh process again the db will be created from 0, and the next synchronization will fix the manager's one.

**Comment by chemamartinez** [comment]
This issue is handled at https://github.com/wazuh/wazuh/issues/13314
