### ISSUE TITLE
Design the interaction between the Vulnerability Detector module and the Task Manager

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#12803]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/9220 we are implementing a mechanism to manually trigger Vulnerability Detector scans. This will make the module have two sources of tasks: the ones requested by the Wazuh API, and the ones periodically scheduled. For that, a new thread should be designed to perform the scheduling and update the status in the task manager. 

### Requirements

- [x] A new task manager thread that interacts with the task manager and the working thread.
- [x] The task manager thread has to be capable of fetching tasks from the task manager.
- [x] The task manager thread has to schedule on-demand tasks and periodic tasks on a working queue used by the working thread.
- [x] The task manager thread should attempt to register tasks by interval in the task manager. 
- [x] The task manager thread must not cancel to schedule a task by interval if the registration fails.
- [x] The task manager thread has to read messages from a shared queue with the working thread.
- [x] The task manager has to always schedule periodic feeds update. 
- [x] The task manager thread has to avoid:
  - [x] To schedule more than one scan on-demand.
  - [x] To schedule more than one feeds update on-demand.
  - [x] To schedule more than one scan by interval. If a second scan by interval time expires, the scan is skipped and a message is logged.

### Risks analysis

All the possible scenarios should be considered to make sure the pre-existent functionality will be preserved.

### DoD

The definitive design is at the end of the issue https://github.com/wazuh/wazuh/issues/12803#issuecomment-1092197851.

- [x] Propose a design that fulfills all the requirements. It should reflect the interaction that the task manager thread has with the queues and the task manager.
- [x] Discuss with the team the design and get the approval.

**Comment by MiguelazoDS** [comment]
# Design proposal

The task manager thread will be in charge of scheduling tasks by interval and on-demand as well as updating the task manager database.

<details> 
<summary>Click to expand!</summary>

```plantuml
@startuml
' Participants
database Task_Manager #lightyellow
control Task_Manager_Thread #orange
queue Tasks_Queue #lightgreen
queue Messages_Queue #lightgreen

' Sequence
note over Tasks_Queue #lightblue : Empty
/ note over Messages_Queue #lightblue : Empty
loop While 1
  note over Task_Manager_Thread #lightblue : Feeds update\nby interval\ntime expires
  Task_Manager_Thread -> Task_Manager : Register Feeds\nupdate task
  note right #lightblue : Tag: Feeds_update_by_interval
  Task_Manager --> Task_Manager_Thread : Returns task ID
  Task_Manager_Thread -> Tasks_Queue : Enqueues task
  note right #lightblue : Register task even\nwithout ID
  note over Task_Manager_Thread #lightblue : Scan by interval\ntime expires
  Task_Manager_Thread -> Tasks_Queue : Checks there's no\nscan by interval\nscheduled
  alt No scan scheduled
    Task_Manager_Thread -> Task_Manager : Register scan task
    note right #lightblue : Tag: Scan_by_interval
    Task_Manager --> Task_Manager_Thread : Returns task ID
    Task_Manager_Thread -> Tasks_Queue : Enqueues task
    note right #lightblue : Register task even\nwithout ID
  else
    Task_Manager_Thread -> Task_Manager_Thread : Scan skipped and logged
  end
  note over Task_Manager_Thread #lightblue : Checks scheduled\nfeeds update\non demand
  alt No feeds update scheduled
    Task_Manager_Thread -> Task_Manager : Checks feeds\nupdate task
    alt Feed update registered
      Task_Manager --> Task_Manager_Thread : Returns task
      note right #lightblue : Tag: Feeds_update_on_demand
      Task_Manager_Thread -> Tasks_Queue : Enqueues task
    end
  end
  note over Task_Manager_Thread #lightblue : Checks scheduled\nscan on demand
  alt No scan scheduled
    Task_Manager_Thread -> Task_Manager : Checks scan task
    alt
      Task_Manager --> Task_Manager_Thread : Returns task
      note right #lightblue : Tag: Scan_on_demand
      Task_Manager_Thread -> Tasks_Queue : Enqueues task
    end
  end
  note over Task_Manager_Thread #lightblue : Checks messages
  alt There're messages
    Messages_Queue --> Task_Manager_Thread : Returns messages
    Task_Manager_Thread -> Task_Manager : Updates information
  end
end
@enduml
```

</details>

![image](https://user-images.githubusercontent.com/13010397/162304466-e8b38a24-ba21-4348-838c-87bc27e357d2.png)

**Comment by DProvinciani** [comment]
With the last proposal, we close this issue.

**Comment by MiguelazoDS** [comment]
# Update 04 May 2022

Due to some requirements changes, it is worth mentioning some aspects to take into account when reviewing the design.

- There's a retry logic where the scheduler thread will try to communicate with the task manager if it needs a task ID. 
- It won't be possible to schedule feed updates by interval that belongs to the same vendor.
