### ISSUE TITLE
Keep receiving email alerts at all levels while set at 10 , why?

### ISSUE THREAD

**Issue by 2A806** [wazuh/wazuh#1281]
Keep receiving email alerts at all levels while set at 10 , why?

this is my config , please help 

  ```
<global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>xxx@xxx.com</email_from>
    <email_to>xxx@xxx</email_to>
    <email_maxperhour>12</email_maxperhour>
    <queue_size>131072</queue_size>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>10</email_alert_level>
  </alerts>
```

**Comment by TJOSERAFAEL** [comment]
Hi @2A806 ,

can you please tell us what version of **Wazuh Manager** are you using? We are trying to reproduce this issue.

Best regards.

**Comment by 2A806** [comment]
Hi @TJOSERAFAEL ,
the version of Wazuh Manager is 3.5.0

**Comment by 2A806** [comment]
Hi @TJOSERAFAEL ,
problem solved ! the reason i kept receiving email alerts at all levels while set at 10 is because some rule files have option like this 
```
<rule id="31122" level="5">
    <if_sid>31120</if_sid>
    <id>^500</id>
    <options>alert_by_email</options>
    <description>Web server 500 error code (Internal Error).</description>
    <group>system_error,</group>
</rule> 
``` 
and `<options>alert_by_email</options>` means send email alerts disregarding the trigger level you have set .
