### ISSUE TITLE
Release 4.3.0 - Manual tests - Amazon Cloudtrail integration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12871]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                       |                                            |
|-----------------------|--------------------------------------------|
| **Test name**         | Amazon Cloudtrail integration                                           |
| **Category**          | Cloud security                                           |
| **Deployment option** | Quickstart - on Ubuntu                                           |
| **Main release issue** | https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** | RC5                                           |

## Test description
Test different use cases of Amazon Cloudtrail events and see that alerts are generated and make sense.

Test that this blog post still works well with 4.3.0:
- https://wazuh.com/blog/integrating-aws-cloudtrail-in-wazuh/

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. Please attach any documents, screenshots or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/12871#issuecomment-1080637906).

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|:yellow_circle:|Manager installation|Documentation|Opened issue https://github.com/wazuh/wazuh-documentation/issues/4982|
|:red_circle:|Agent installation|Documentation|Opened issue https://github.com/wazuh/wazuh-documentation/issues/4983|
|:red_circle:|AWS dashboard in Wazuh|Documentation|Opened issue https://github.com/wazuh/wazuh-documentation/issues/4988|
|:yellow_circle:|AWS screenshots outdated|Documentation|Opened issue https://github.com/wazuh/wazuh-documentation/issues/4990|
|:yellow_circle:|AWS dashboard with missing information|Kibana|Opened issue https://github.com/wazuh/wazuh-kibana-app/issues/3931|

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias 
- [x] @CarlosRS9

**Comment by Selutario** [comment]
# Test results
## 1. Manager installation
### 1.1 Specs
I created a virtual machine with these specs:
- **RAM:** 4 GB
- **CPU cores:** 2
- **Disk space:** 10 GB
- **SO:** Ubuntu 20.04

### 1.2 Installation error (space not enough)
After that, I run this:
```
curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```


<details>
  <summary>And this was the output. An error was found.</summary>
  
```
28/03/2022 12:26:23 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
28/03/2022 12:26:23 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
28/03/2022 12:26:30 INFO: --- Dependencies ----
28/03/2022 12:26:30 INFO: Installing apt-transport-https.
28/03/2022 12:26:40 INFO: Wazuh development repository added.
28/03/2022 12:26:40 INFO: --- Configuration files ---
28/03/2022 12:26:40 INFO: Generating configuration files.
28/03/2022 12:26:40 INFO: Created wazuh-install-files.tar. It contains Wazuh cluster key, certificates, and passwords necessary for installation.
28/03/2022 12:26:40 INFO: --- Wazuh indexer ---
28/03/2022 12:26:40 INFO: Starting Wazuh indexer installation.
28/03/2022 12:27:23 INFO: Wazuh indexer installation finished.
28/03/2022 12:27:23 INFO: Wazuh indexer post-install configuration finished.
28/03/2022 12:27:23 INFO: Starting service wazuh-indexer.
28/03/2022 12:27:35 INFO: Wazuh-indexer service started.
28/03/2022 12:27:35 INFO: Initializing Wazuh indexer cluster security settings.
28/03/2022 12:27:41 INFO: Wazuh indexer cluster initialized.
28/03/2022 12:27:41 INFO: --- Wazuh server ---
28/03/2022 12:27:41 INFO: Starting the Wazuh manager installation.
28/03/2022 12:28:30 INFO: Wazuh manager installation finished.
28/03/2022 12:28:30 INFO: Starting service wazuh-manager.
28/03/2022 12:28:43 INFO: Wazuh-manager service started.
28/03/2022 12:28:43 INFO: Starting Filebeat installation.
28/03/2022 12:28:52 INFO: Filebeat installation finished.
28/03/2022 12:28:54 INFO: Filebeat post-install configuration finished.
28/03/2022 12:28:54 INFO: Starting service filebeat.
28/03/2022 12:28:55 INFO: Filebeat service started.
28/03/2022 12:28:55 INFO: --- Wazuh dashboard ---
28/03/2022 12:28:55 INFO: Starting Wazuh dashboard installation.
28/03/2022 12:28:58 ERROR: Wazuh dashboard installation failed.
28/03/2022 12:28:58 INFO: --- Removing existing Wazuh installation ---
28/03/2022 12:28:58 INFO: Removing Wazuh manager.
28/03/2022 12:29:07 INFO: Wazuh manager removed.
28/03/2022 12:29:07 INFO: Removing Wazuh indexer.
28/03/2022 12:29:11 INFO: Wazuh indexer removed.
28/03/2022 12:29:11 INFO: Removing Filebeat.
28/03/2022 12:29:14 INFO: Filebeat removed.
28/03/2022 12:29:14 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
```

</details>
This was shown in the `wazuh-install.log` in the log:
```
E: You don't have enough free space in /var/cache/apt/archives/.
```

[Report](https://github.com/wazuh/wazuh/files/8362798/e1_no_space.txt) (wazuh-install.log)

### 1.3 Installation error (space not enough again)
I increased disk space for the Virtual box machine to 20 GB:
![image](https://user-images.githubusercontent.com/23361101/160402575-3d1ac66f-5d4a-4f5b-80d5-d40e6ff3e7ce.png)

Then I deleted everything inside `/var/cache/apt/archives/` and run the script again:
```
curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
```

<details>
  <summary>This was the output. An error was found:</summary>
  
```
root@selu-VirtualBox:/home/selu# curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
28/03/2022 12:37:17 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
28/03/2022 12:37:17 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
28/03/2022 12:37:35 INFO: Wazuh development repository added.
28/03/2022 12:37:35 INFO: --- Configuration files ---
28/03/2022 12:37:35 INFO: Generating configuration files.
28/03/2022 12:37:36 INFO: Created wazuh-install-files.tar. It contains Wazuh cluster key, certificates, and passwords necessary for installation.
28/03/2022 12:37:36 INFO: --- Wazuh indexer ---
28/03/2022 12:37:36 INFO: Starting Wazuh indexer installation.
28/03/2022 12:38:24 INFO: Wazuh indexer installation finished.
28/03/2022 12:38:24 INFO: Wazuh indexer post-install configuration finished.
28/03/2022 12:38:24 INFO: Starting service wazuh-indexer.
28/03/2022 12:38:37 INFO: Wazuh-indexer service started.
28/03/2022 12:38:37 INFO: Initializing Wazuh indexer cluster security settings.
28/03/2022 12:38:43 INFO: Wazuh indexer cluster initialized.
28/03/2022 12:38:43 INFO: --- Wazuh server ---
28/03/2022 12:38:43 INFO: Starting the Wazuh manager installation.
28/03/2022 12:39:31 INFO: Wazuh manager installation finished.
28/03/2022 12:39:31 INFO: Starting service wazuh-manager.
28/03/2022 12:39:46 INFO: Wazuh-manager service started.
28/03/2022 12:39:46 INFO: Starting Filebeat installation.
28/03/2022 12:39:56 INFO: Filebeat installation finished.
28/03/2022 12:39:57 INFO: Filebeat post-install configuration finished.
28/03/2022 12:39:57 INFO: Starting service filebeat.
28/03/2022 12:39:58 INFO: Filebeat service started.
28/03/2022 12:39:58 INFO: --- Wazuh dashboard ---
28/03/2022 12:39:58 INFO: Starting Wazuh dashboard installation.
28/03/2022 12:40:01 ERROR: Wazuh dashboard installation failed.
28/03/2022 12:40:01 INFO: --- Removing existing Wazuh installation ---
28/03/2022 12:40:01 INFO: Removing Wazuh manager.
28/03/2022 12:40:11 INFO: Wazuh manager removed.
28/03/2022 12:40:11 INFO: Removing Wazuh indexer.
28/03/2022 12:40:16 INFO: Wazuh indexer removed.
28/03/2022 12:40:16 INFO: Removing Filebeat.
28/03/2022 12:40:20 INFO: Filebeat removed.
28/03/2022 12:40:20 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
```

</details>

[Report](https://github.com/wazuh/wazuh/files/8362925/e2_no_space.txt) (wazuh-install.log)


### 1.4 Installation successful

I created a new Virtual box machine with more disk space:
- **RAM:** 4 GB
- **CPU cores:** 2
- **Disk space: 20 GB**
- **SO:** Ubuntu 20.04

<details>
  <summary>Now the installation was successful.</summary>
  
```
curl -sO https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/4.3/wazuh-install.sh && sudo bash ./wazuh-install.sh -a

28/03/2022 13:11:23 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
28/03/2022 13:11:23 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
28/03/2022 13:11:33 INFO: --- Dependencies ----
28/03/2022 13:11:33 INFO: Installing apt-transport-https.
28/03/2022 13:11:40 INFO: Wazuh development repository added.
28/03/2022 13:11:40 INFO: --- Configuration files ---
28/03/2022 13:11:40 INFO: Generating configuration files.
28/03/2022 13:11:40 INFO: Created wazuh-install-files.tar. It contains Wazuh cluster key, certificates, and passwords necessary for installation.
28/03/2022 13:11:40 INFO: --- Wazuh indexer ---
28/03/2022 13:11:40 INFO: Starting Wazuh indexer installation.
28/03/2022 13:12:22 INFO: Wazuh indexer installation finished.
28/03/2022 13:12:22 INFO: Wazuh indexer post-install configuration finished.
28/03/2022 13:12:22 INFO: Starting service wazuh-indexer.
28/03/2022 13:12:34 INFO: Wazuh-indexer service started.
28/03/2022 13:12:34 INFO: Initializing Wazuh indexer cluster security settings.
28/03/2022 13:12:40 INFO: Wazuh indexer cluster initialized.
28/03/2022 13:12:40 INFO: --- Wazuh server ---
28/03/2022 13:12:40 INFO: Starting the Wazuh manager installation.
28/03/2022 13:13:46 INFO: Wazuh manager installation finished.
28/03/2022 13:13:46 INFO: Starting service wazuh-manager.
28/03/2022 13:14:00 INFO: Wazuh-manager service started.
28/03/2022 13:14:00 INFO: Starting Filebeat installation.
28/03/2022 13:14:13 INFO: Filebeat installation finished.
28/03/2022 13:14:15 INFO: Filebeat post-install configuration finished.
28/03/2022 13:14:15 INFO: Starting service filebeat.
28/03/2022 13:14:16 INFO: Filebeat service started.
28/03/2022 13:14:16 INFO: --- Wazuh dashboard ---
28/03/2022 13:14:16 INFO: Starting Wazuh dashboard installation.
28/03/2022 13:15:34 INFO: Wazuh dashboard installation finished.
28/03/2022 13:15:34 INFO: Wazuh dashboard post-install configuration finished.
28/03/2022 13:15:34 INFO: Starting service wazuh-dashboard.
28/03/2022 13:15:34 INFO: Wazuh-dashboard service started.
28/03/2022 13:16:00 INFO: Initializing Wazuh dashboard web application.
28/03/2022 13:16:12 INFO: Wazuh dashboard web application initialized.
28/03/2022 13:16:12 INFO: --- Summary ---
28/03/2022 13:16:12 INFO: You can access the web interface https://<wazuh-dashboard-ip>.
    User: admin
    Password: HaGHjFb8MkIOnlzCOXmxDExqXlkdqT7j
28/03/2022 13:16:12 INFO: Installation finished.
```

</details>

## 2. Agent installation
### 2.1 Specs
- **RAM:** 2 GB
- **CPU cores:** 1
- **Disk space:** 20 GB
- **SO:** Ubuntu 20.04

### 2.2 Installation successful
<details>
  <summary>Now the installation was successful.</summary>
  
```
WAZUH_MANAGER="192.168.1.83" apt-get install wazuh-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'sudo apt autoremove' to remove it.
The following NEW packages will be installed:
  wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 6.897 kB of archives.
After this operation, 22,2 MB of additional disk space will be used.
Get:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-agent amd64 4.2.5-1 [6.897 kB]
Fetched 6.897 kB in 1s (11,6 MB/s)
Preconfiguring packages ...
Selecting previously unselected package wazuh-agent.
(Reading database ... 158663 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.2.5-1_amd64.deb ...
Unpacking wazuh-agent (4.2.5-1) ...
Setting up wazuh-agent (4.2.5-1) ...
Processing triggers for systemd (245.4-4ubuntu3.15) ...
```

</details>
