### ISSUE TITLE
Release 4.3.0 - Manual tests - Windows events

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#12896]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                       |                                            |
|-----------------------|--------------------------------------------|
| **Test name**         |  Windows events                                         |
| **Category**          |  Log data analysis                                           |
| **Deployment option** | OVA                                           |
| **Main release issue** | https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** | RC5                                           |

## Test description

- Test that Windows data collection works out of the box. 
- Check that for the same Windows events, the alerts rule ID is the same as in 4.2.5.
- [Install Sysmon and create Wazuh rules as mentioned, to ensure that everything works as intended in the blog post (but using 4.3.0 instead of 4.2.0)](https://wazuh.com/blog/emulation-of-attck-techniques-and-detection-with-wazuh/)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed to check. |
| :yellow_circle:  | There is at least one expected to fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a zip or txt. Please attach any documents, screenshots or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|    :red_circle:    | Test that Windows data collection works out of the box. | Service failure | [In case of editing system date it could produce service stop working](https://github.com/wazuh/wazuh/issues/12923). [If no time system is changed  it works correctly](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1084432076)|
|        :yellow_circle:         |     Install Sysmon and create Wazuh rules as mentioned, to ensure that everything works as intended in the blog post (but using 4.3.0 instead of 4.2.0)        |        Documentation (https://github.com/wazuh/wazuh/issues/12896#issuecomment-1083494316)             |   https://github.com/wazuh/wazuh/issues/12896#issuecomment-1081579943 Signed binary Proxy had the Execution tactic in 4.2, after taking with https://github.com/orgs/wazuh/teams/threat-intel it seems that the correct Tactic is Defense Evasion [attack.mitre.org/techniques/T1218/010](https://attack.mitre.org/techniques/T1218/010/). It is required to change documentation and [blog](https://wazuh.com/blog/emulation-of-attck-techniques-and-detection-with-wazuh/) accordingly             |
| :yellow_circle:  | Check that for the same Windows events, the alerts rule ID is the same as in 4.2.5.| | https://github.com/wazuh/wazuh/issues/12896#issuecomment-1084828251 Critical rule is no longer triggered https://github.com/wazuh/wazuh/issues/12977

All tests have passed and the fails have been reported or justified. I, therefore, conclude that this issue is finished and OK for this release candidate.

###  Detected Issues
- https://github.com/wazuh/wazuh-kibana-app/issues/3923
- https://github.com/wazuh/wazuh-kibana-app/issues/3925
- https://github.com/wazuh/wazuh/issues/12906
- https://github.com/wazuh/wazuh-kibana-app/issues/3927
- https://github.com/wazuh/wazuh-kibana-app/issues/3928
- https://github.com/wazuh/wazuh/issues/12923
-  https://github.com/wazuh/wazuh-packages/issues/1404
- https://github.com/wazuh/wazuh-documentation/issues/4986
- https://github.com/wazuh/wazuh/issues/12977
## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias   
- [x] @vikman90

**Comment by Rebits** [comment]
### 29/03/202

## Detected issues

###  Multiple _The index pattern was refreshed successfully panels_:
![panels](https://user-images.githubusercontent.com/11089305/160623027-0e32ee43-5f77-424f-9783-ea790fffa652.png)

**Steps to reproduce**
- Add a new rule files -> Management > Rules > Add new rule files. For example sysmon rules:
```
<group name="windows,sysmon,">

<rule id="115001" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1053,technique_name=Scheduled Task</field>
  <description>A Newly Scheduled Task has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1053</id>
  </mitre>
</rule>

<rule id="115002" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1073,technique_name=DLL Side-Loading</field>
  <description>DLL Side-Loading Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1073</id>
    <id>T1574.002</id>
  </mitre>
</rule>

<rule id="115003" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1218.010,technique_name=Regsvr32</field>
  <description>Signed Binary Proxy Execution using Regsvr32 Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1218</id>
    <id>T1117</id>
  </mitre>
</rule>

<rule id="115004" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1518.001,technique_name=Security Software Discovery</field>
  <description>Security Software Discovery Attempt has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1518</id>
  </mitre>
</rule>

<rule id="115005" level="10">
  <if_group>windows</if_group>
  <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1548.002,technique_name=Bypass User Access Control</field>
  <description>Privilege Escalation Through Bypass of UAC has been Detected on $(win.system.computer)</description>
  <mitre>
    <id>T1548.002</id>
    <id>T1088</id>
  </mitre>
</rule>

</group>
```
- Save and restart using the interface
-  Modules > Security Events > Events
- Multiple panels of  _The index pattern was refreshed successfully panels_ appears





###  You have no permissions message in the agent panel

Reproduce  `Multiple _The index pattern was refreshed successfully panels_` steps to reproduce and go to the agent's panel.

**Comment by juliamagan** [comment]
## 29/03/2022

### Install

No problems were found during installation using CLI.
```
PS C:\Users\vagrant\Downloads> .\wazuh-agent-4.3.0-1.msi /q WAZUH_MANAGER="172.17.1.30"                                 
PS C:\Users\vagrant\Downloads> NET START WazuhSvc                                                                       The Wazuh service is starting.                                                                                          The Wazuh service was started successfully.                                                                             
```


### Test Windows data collection

We could see that the description doesn't fit with the example:

![image](https://user-images.githubusercontent.com/80041853/160653367-bc9e4ac1-1fb9-4286-9149-d337db4d52ba.png)

It seems to fit with the example below:

![image](https://user-images.githubusercontent.com/80041853/160653654-1d6470ce-2943-4b87-bcc3-ffcefe216472.png)

***

It could be a good idea to add more examples of `query` format since it is not very intuitive. Also, a link to https://documentation-dev.wazuh.com/3865_installation_guide_rework/user-manual/reference/ossec-conf/localfile.html#query could be useful.


### Check that the rules are the same in 4.2.6  and 4.3.0

MS SQL rules moved from `0580-win-security_rules.xml` to `0585-win-application_rules.xml` in https://github.com/wazuh/wazuh/pull/8552/, but ID changes too.

***

MITRE technique changed in https://github.com/wazuh/wazuh/issues/11168, are not correctly attached in the dashboard:

- Separated by a comma:

![image](https://user-images.githubusercontent.com/80041853/160656382-ca47ee55-9a3f-46bd-b492-2b1a835d0d77.png)
![image](https://user-images.githubusercontent.com/80041853/160656850-11189643-f64d-47b1-89a5-85ca382d17f5.png)

- Attached only one part:

![image](https://user-images.githubusercontent.com/80041853/160656974-1df89c0d-5a24-4e9e-814a-470ff65e1db5.png)
![image](https://user-images.githubusercontent.com/80041853/160657059-0115c5c3-b5fd-4f4b-8289-1be1c7a66720.png)

  Expected `T1070.004`:

```
  <rule id="60117" level="9">
    <if_sid>60100</if_sid>
    <field name="win.system.eventID">^1102$</field>
    <options>no_full_log</options>
    <description>Windows audit log was cleared.</description>
    <mitre>
      <id>T1070.004</id>
    </mitre>
    <group>gdpr_IV_35.7.d,gpg13_10.1,hipaa_164.312.b,logs_cleared,nist_800_53_AU.6,pci_dss_10.6.1,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
``` 

***

Attachments not working until we refresh:


https://user-images.githubusercontent.com/80041853/160661646-dbd6bec4-ec9b-4089-ae1c-e4633b9d9f4e.mp4

**Comment by ace-109** [comment]
With Wazuh manager 4.3 and windows agent 4.2.5, I modified the rules to use the new MITRE techniques only as seen here

```
<group name="sysmon-blog-rule,windows,sysmon,">

  <rule id="115001" level="10">
    <if_group>windows</if_group>
    <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1053,technique_name=Scheduled Task</field>
    <description>A Newly Scheduled Task has been Detected on $(win.system.computer)</description>
    <mitre>
      <id>T1053</id>
    </mitre>
  </rule>

  <rule id="115002" level="10">
    <if_group>windows</if_group>
    <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1073,technique_name=DLL Side-Loading</field>
    <description>DLL Side-Loading Detected on $(win.system.computer)</description>
    <mitre>
      <id>T1574.002</id>
    </mitre>
  </rule>

  <rule id="115003" level="10">
    <if_group>windows</if_group>
    <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1218.010,technique_name=Regsvr32</field>
    <description>Signed Binary Proxy Execution using Regsvr32 Detected on $(win.system.computer)</description>
    <mitre>
      <id>T1218</id>
    </mitre>
  </rule>

  <rule id="115004" level="10">
    <if_group>windows</if_group>
    <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1518.001,technique_name=Security Software Discovery</field>
    <description>Security Software Discovery Attempt has been Detected on $(win.system.computer)</description>
    <mitre>
      <id>T1518</id>
    </mitre>
  </rule>

  <rule id="115005" level="10">
    <if_group>windows</if_group>
    <field name="win.eventdata.ruleName" type="pcre2" >technique_id=T1548.002,technique_name=Bypass User Access Control</field>
    <description>Privilege Escalation Through Bypass of UAC has been Detected on $(win.system.computer)</description>
    <mitre>
     <id>T1548.002</id>
    </mitre>
  </rule>

</group>
```
This is the output from the Wazuh manager 4.3

![image](https://user-images.githubusercontent.com/41423652/160895799-68b88505-dbf1-47e1-a0cc-a11e79c9d676.png)

With wazuh manager 4.2.5 and windows agent 4.2.5, using the same rules, the tactics for T1218 still has "Execution", techniques T1548.002 and T1574.002 are missing as seen below
![image](https://user-images.githubusercontent.com/41423652/160900799-35272f42-86bf-423b-8449-e0d4fb80d1a4.png)

It looks like some new MITRE techniques are broken in Wazuh 4.2.5 but works fine in 4.3.0

**Comment by Rebits** [comment]
## Test that Windows data collection works out of the box.
Windows Eventchannel works immediately after the agent starts

https://user-images.githubusercontent.com/11089305/161041989-79c3e49e-3385-4d4f-af89-a307ea0e0685.mp4

**Comment by Rebits** [comment]
## Check that for the same Windows events, the alerts rule ID is the same as in 4.2.5.
For this test case the following checks have been performed:
- **Static Analysis**: https://github.com/wazuh/wazuh/issues/12896#issuecomment-1082106195
- **Dynamic Analysis**: Ensuring that all Windows events generate the same rule in these different versions is not possible in a reasonable amount of time. In this step in we have considered the use of some script to generate multiple Windows events.
Is important to point out that the event generated are not real ones, so results may be analyzed manually.

Tools used in dynamic testing
  - **Windows Event generator**:  [winevt_generator.zip](https://github.com/wazuh/wazuh/files/8391427/winevt_generator.zip)
Generate windows event for different:
    - **channels**:  `channels = ["Security", "Application", "System", "Microsoft-Windows-Sysmon/Operational", "Microsoft-Windows-Windows Defender/Operational", "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall", "File Replication Service", "Microsoft-Windows-TerminalServices", "Microsoft-Windows-PowerShell/Operational"]`
    - **severityValues**: `severityValues = ["INFORMATION", "WARNING", "ERROR", "CRITICAL", "AUDIT_SUCCESS", "AUDIT_FAILURE" ]
`
    - **providerNames**: `["Microsoft-Windows-Kernel-Power", "Microsoft-Windows-Kernel-PnP", "Service Control Manager"
,"Application Management"
,"Microsoft-Windows-LocationProvider"
,"Microsoft-Windows-MSDTC"
,"ESENT"
,"Desktop Window Manager"
,"Microsoft-Windows-WMI"
,"VSS"
,"Microsoft-Windows-Search-ProfileNotify"
,"Microsoft-Windows-Search"
,"LocationNotifications"
,"chromoting"
,"MSExchange Unified Messaging"
,"Service Control Manager"
,"Microsoft-Windows-WMI-Activity"
,"Eventlog"
,"Microsoft-Windows-Eventlog"   
,"McLogEvent"]`
    - **eventIDs**: Every eventID mentioned in the windows ruleset
