### ISSUE TITLE
Ignoring directory log for "sregex" statement

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#1290]
Hi all,

Syscheck is not generating logs about the directories being ignored when using "sregex" ignore type.

- `<ignore type="sregex">temp-write-test$</ignore>`

We should include a log similar to:

> 2018/09/07 10:11:57 ossec-syscheckd: INFO: Ignoring sregex: 'temp-write-test$'

Reported in the mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/NKHTNdpDfOc/rlWcPb9HBQAJ

**Comment by bah07** [comment]
Done!
