### ISSUE TITLE
`Run agent configuration Interface` option does not work correctly

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#12906]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Agent | Agent | Packages | Windows Server 2019 |

### Description 

During [Windows event manual testing](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1081885456), it has been detected that the `Run agent configuration Interface` option does not work correctly in Windows agent installation. 

https://user-images.githubusercontent.com/11089305/160567860-a6707308-49f3-49cf-98f2-a1dca276b70a.mp4

**Comment by ncvicchi** [comment]
Several attempts were made to achieved correct functionality, all attemps failed, either silently or with a newer error.

- Tried executing it from a command line executed as administrator -> succes. It is a permissions issue.

- Adding:
`<Property Id="MSIUSEREALADMINDETECTION" Value="1" />`

Result: silent failure

- Adding:
```
<Package Id="*"
             Description="Desc"
             Keywords="Installer"
             Manufacturer="$(var.Manufacturer)"
             SummaryCodepage="1252"
             InstallerVersion="200"
             Compressed="yes"
             InstallScope="perMachine"
             AdminImage="yes"
             InstallPrivileges="elevated" />
```
Result: silent failure

- try changing folder permissions:

```
<DirectoryRef Id="APPLICATIONFOLDER">
        <Component Id="INSTALLDIR_perm" Guid="EC4352C1-4240-4E6A-9A5E-E31F22702705" Permanent="yes">
            <CreateFolder>
                <!--Everyone gets full permissions to the folder-->
                <util:PermissionEx User="Everyone" GenericAll="yes" />
            </CreateFolder>
        </Component>  
    </DirectoryRef> 

```
Result: silent failure

- Try removing the following lines (a warning was being raised at compile time):

```

 BinaryKey="WixCA"
 DllEntry="WixShellExec"

```
Result: silent failure

- Try requesting elevated permissions:

```
<Property Id="ALLUSERS" Value="1" />    <!--equals to install="permachine" at package element but this element depricated -->
<Property Id="MSIUSEREALADMINDETECTION" Value="1" /> 

<Condition Message="Please Run as Administrator.">
      Privileged
</Condition>

```

Result: silent failure

- Tried changing execute to deferred:

```

        <CustomAction 	Id="LaunchUI"
        				Directory="APPLICATIONFOLDER"
        				ExeCommand="[APPLICATIONFOLDER]win32ui.exe"
        				BinaryKey="WixCA"
        				DllEntry="WixShellExec"
        				Impersonate="no"
        				FileKey="EXE"
        				Execute="deferred" 
        				Return="asyncNoWait" />

```

Result: silent failure

- Tried adding at install execute sequence:

```

<Custom Action="LaunchUI" After='InstallFinalize'>NOT Installed</Custom>

```

Result: silent failure

- Try moving the customAction inside the install sequence:

```
<CustomAction Id="LaunchUI" Directory="APPLICATIONFOLDER" ExeCommand="[APPLICATIONFOLDER]win32ui.exe" Return="asyncNoWait" Impersonate='yes' Execute='commit'/>

```

Result: fails with the following message:


`The installer has encounter an unexpected error installing the package. This may indicate a problem with this package. The error code is 2762`


- Try same attempt but changing impersonate to no.

Result: same error.

- After all these attemps, the [Wix example](https://wixtoolset.org/docs/v3/howtos/ui_and_localization/run_program_after_install/) to execute was tried. It succesfully starts the application after install.

This allowed to compare both folders (the one created by our installer and the one created by the wix example installer):
![image](https://user-images.githubusercontent.com/69121070/225468778-897d6dae-7999-4473-97f4-ca859e732049.png)

With this new information, I asked to cicd about, which led to the [PR](https://github.com/wazuh/wazuh/pull/3593) where these permissions were set.

**Comment by ncvicchi** [comment]
According to that PR, only if the installer is run as administrator the installer can run the UI (which was tested and verified).

I see a few options:

1. Force execution of the installer as an administrator (tried, fail, but maybe there is a valid way)
2. Return to a more open permission scheme
3. Remove the option to open the UI from the installer (maybe adding informaton on how to executing it manually in the installer itsel)

**Comment by ncvicchi** [comment]
The issue has 2 concurrent sources:

1. The installation folder has all access permissions removed by the VB script when creating it. This prevents the user from executing it

2. Wazuh's UI required elevated privileges to be executed. The way the wxs tries to launch the UI does not allow this

Solution: We grant the installer user permission to access the folder when creating it and modified the WXS script to require elevated privileges when executing the UI.
