### ISSUE TITLE
Deadlock in analysisd 3.7

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1291]
There is a `mutex` problem causing the event processing threads to enter a `deadlock` state.

**Comment by TJOSERAFAEL** [comment]
Hi @snaow,
we cant unlock the `mutex` inside the same function because that `rule_group` rule can be deleted by another thread using the `OSList_DeleteOldestNode` function for example. So if any thread is using the rule, it must hold the lock until the loop ends.

Regards

**Comment by vikman90** [comment]
I @snaow,

The thing is that (OSList_GetLastNode_group(rule->group_search)` locks `rule->group_search->mutex`, not `lf_node`. So that, this mutex is unlocked in all the possible execution paths.

Let me close this issue.
Best regards.
