### ISSUE TITLE
Release 4.3.0 - Manual tests - Office365 integration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#12914]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Office365 integration                                          |
| **Category**            | Cloud security                                           |
| **Deployment option**   | Quickstart - on CentOS                                         |
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/10954                                           |
| **Release candidate #** | RC5                                           |

## Test description
- Test different use cases on Office 365 events and see if alerts are generated and make sense.

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|        :green_circle:        |      [Quickstart v2.0 installation](https://github.com/wazuh/wazuh/issues/12914#issuecomment-1084921758)      |   Considerations related to the installation output and the documentation.     | https://github.com/wazuh/wazuh-documentation/issues/5026 & https://github.com/wazuh/wazuh-packages/issues/1436|
|        :green_circle:        |      [Office 365 documentation](https://github.com/wazuh/wazuh/issues/12914#issuecomment-1088605565)      |    Considerations related to the documentation.     | https://github.com/wazuh/wazuh-documentation/issues/5025|
|        :red_circle:        |      [Office 365 configuration](https://github.com/wazuh/wazuh/issues/12914#issuecomment-1088605565)      |    Considerations related to the configuration    | https://github.com/wazuh/wazuh-kibana-app/issues/3951 & https://github.com/wazuh/wazuh/issues/13066|

All tests have failed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and is not OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias

**Comment by havidarou** [comment]
# Quickstart v2.0

<details>

<summary>details</summary>

## Documentation

The hardware requirements section lacks context. It provides details about minimum and recommended, but there's no explanation as to why that jump in requirements. 

Moreover, similar to the paragraph above in the document, where we link to other installation options, we should link to a section dedicated to hardware specs requirements under different scenarios.

![image](https://user-images.githubusercontent.com/5363328/161117259-8dddebeb-ed33-476d-ac62-6a89f53e8236.png)

## Installation output

This is the default output:

```
31/03/2022 17:32:28 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
31/03/2022 17:32:28 INFO: The verbose logging will be redirected to the file: /var/log/wazuh-install.log
31/03/2022 17:32:38 INFO: --- Dependencies ----
31/03/2022 17:32:38 INFO: Installing apt-transport-https.
31/03/2022 17:32:41 INFO: Installing unzip.
31/03/2022 17:33:06 INFO: Wazuh development repository added.
31/03/2022 17:33:06 INFO: --- Configuration files ---
31/03/2022 17:33:06 INFO: Generating configuration files.
31/03/2022 17:33:07 INFO: Created wazuh-install-files.tar. It contains Wazuh cluster key, certificates, and passwords necessary for installation.
31/03/2022 17:33:07 INFO: --- Wazuh indexer ---
31/03/2022 17:33:07 INFO: Starting Wazuh indexer installation.
31/03/2022 17:33:46 INFO: Wazuh indexer installation finished.
31/03/2022 17:33:46 INFO: Wazuh indexer post-install configuration finished.
31/03/2022 17:33:46 INFO: Starting service wazuh-indexer.
31/03/2022 17:33:55 INFO: Wazuh-indexer service started.
31/03/2022 17:33:55 INFO: Initializing Wazuh indexer cluster security settings.
31/03/2022 17:34:00 INFO: Wazuh indexer cluster initialized.
31/03/2022 17:34:00 INFO: --- Wazuh server ---
31/03/2022 17:34:00 INFO: Starting the Wazuh manager installation.
31/03/2022 17:34:37 INFO: Wazuh manager installation finished.
31/03/2022 17:34:37 INFO: Starting service wazuh-manager.
31/03/2022 17:34:53 INFO: Wazuh-manager service started.
31/03/2022 17:34:53 INFO: Starting Filebeat installation.
31/03/2022 17:35:00 INFO: Filebeat installation finished.
31/03/2022 17:35:02 INFO: Filebeat post-install configuration finished.
31/03/2022 17:35:02 INFO: Starting service filebeat.
31/03/2022 17:35:02 INFO: Filebeat service started.
31/03/2022 17:35:02 INFO: --- Wazuh dashboard ---
31/03/2022 17:35:02 INFO: Starting Wazuh dashboard installation.
31/03/2022 17:35:53 INFO: Wazuh dashboard installation finished.
31/03/2022 17:35:53 INFO: Wazuh dashboard post-install configuration finished.
31/03/2022 17:35:53 INFO: Starting service wazuh-dashboard.
31/03/2022 17:35:53 INFO: Wazuh-dashboard service started.
31/03/2022 17:36:07 INFO: Initializing Wazuh dashboard web application.
31/03/2022 17:36:19 INFO: Wazuh dashboard web application initialized.
31/03/2022 17:36:19 INFO: --- Summary ---
31/03/2022 17:36:19 INFO: You can access the web interface https://<wazuh-dashboard-ip>.
    User: admin
    Password: ************************************
31/03/2022 17:36:19 INFO: Installation finished.
```

I'd change `The verbose logging will be redirected to the file` to `Verbose logging will be redirected to`.
I'd change `It contains Wazuh cluster key, certificates, and passwords necessary for installation` to `It contains the Wazuh cluster key, certificates, and passwords necessary for installation`

When we name the service in the output, if the sentence starts with the service name, we are using a capital letter, but I'd say we shouldn't do this. As an example, I'd change `Wazuh-indexer service started` to `wazuh-indexer service started`, even if it is the start of a sentence.

</details>

**Comment by MiguelCasaresRobles** [comment]
# Office 365 documentation

<details>

<summary>details</summary>

The Azure portal looks slightly different from our documentation, it seems the documentation is a bit outdated regarding the account setup procedure.

![image](https://user-images.githubusercontent.com/23264276/161742255-e2395fda-d759-436d-b0de-d52ea264b245.png)
https://documentation-dev.wazuh.com/4.3-rc/office365/monitoring-office365-activity.html

Docu vs Azure portal:
![image](https://user-images.githubusercontent.com/23264276/161744346-34a11174-f73b-4d56-8c2f-6a1c11227a8b.png)
![image](https://user-images.githubusercontent.com/23264276/161744438-13478d18-2ea3-4436-b568-b27579530961.png)

In the certificates and secrets section, we need to add this step:
![image](https://user-images.githubusercontent.com/23264276/161746541-6268e264-6451-4385-a1f6-4da5794dc38c.png)

and we need to say they should use the secret ID later in the configuration (there is a mismatch between concepts in our configuration and Azure)


Here Azure mentions it is optional but you need to select one, we should indicate which one and fill up the default value. 
![image](https://user-images.githubusercontent.com/23264276/161742609-00d7bb3f-d9b0-4538-8a93-be41ce987ce6.png)

We should clarify the differences between application, client, tenant and directory and we are mixing concepts in the documentation

We are mentioning here we need to enable the module in the Wazuh manager (should it be Wazuh server?) but no mention to enable the dashboard in the UI:
https://documentation-dev.wazuh.com/4.3-rc/office365/monitoring-office365-activity.html#wazuh-configuration

Here it is not clear if we can add any subscriptions or we are limited by the following: https://documentation-dev.wazuh.com/4.3-rc/user-manual/reference/ossec-conf/office365-module.html#subscriptions
```
The event types to include:

Audit.AzureActiveDirectory: User identity management.

Audit.Exchange: Mail and calendaring server.

Audit.SharePoint: Web-based collaborative platform.

Audit.General: Includes all other workloads not included in the previous content types.

DLP.All: Data loss prevention workloads
````

**Comment by MiguelCasaresRobles** [comment]
# Office 365 configuration

<details>

<summary>details</summary>

The integration seems only to log info in debug mode:

```
2022/04/05 11:45:57 wazuh-modulesd[4249] main.c:94 at main(): DEBUG: Created new thread for the 'office365' module.
2022/04/05 11:45:57 wazuh-modulesd:office365[4249] wm_office365.c:118 at wm_office365_main(): INFO: Module Office365 started.
2022/04/05 11:45:57 wazuh-modulesd:office365[4249] wm_office365.c:283 at wm_office365_execute_scan(): DEBUG: Scanning tenant: '99339bc6-0969-496f-9db9-536c9c21bbed'
```
