### ISSUE TITLE
Agent does not send events after system time change

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#12923]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Agent | Agent | Packages | Windows Server 2019 |

### Description 

During [Windows event manual testing](https://github.com/wazuh/wazuh/issues/12896#issuecomment-1081885456), it has been detected that when the time system changes (to an earlier date), it will no longer send events to the manager.
This behavior produces that in case of the manager stop while the agent is in this state after the manager restarting, the agent will remain in `Pending` status.

### Video

https://user-images.githubusercontent.com/11089305/160838802-ff6373f8-5d38-4a81-9ded-00978bfc9f92.mp4

**Comment by vikman90** [comment]
The agent uses the calendar clock to calculate the delay between event deliveries ([buffer.c](https://github.com/wazuh/wazuh/blob/b006d1896f7734c4eafa9b28f4b0de8fd5c9ba27/src/client-agent/buffer.c#L234)). If we change the system time to an earlier time, the result turns into a negative number:

```
2022/04/04 13:01:38 wazuh-agent[19372] buffer.c:236 at dispatch_buffer(): DEBUG: Delaying -1509 s. and 551388900 ns.
```

This issue appeared in 3.12 (0e4a56229ec8f52a3d6c1b8f7765ea39b976a46e), and it affects every platform (not Windows only) since this component uses the system clock.

## Possible fixes

- Use the monotonic clock.
- Do not call `delay()` if the argument is negative.

**Comment by vikman90** [comment]
After a meeting with @Rebits, we found a new case.

### Context

The agent performs an immediate regulation of the throughput marked by the EPS setting, for each message:

![image](https://user-images.githubusercontent.com/10536251/164674946-ba6e8169-69da-40bd-a19e-78f043246304.png)

`t_loop` is the time it took to step through the code that pulls an event from the queue and delivers it to the manager. Thus:

![image](https://user-images.githubusercontent.com/10536251/164675293-e78a16b8-1f86-415a-a765-ca0009340ddd.png)

The first problem I found is that it was trying to sleep during a time close to -1 seconds (~63 years in positive). So, I added this guard:

![image](https://user-images.githubusercontent.com/10536251/164676696-45e7cf6f-baea-4430-a8ca-6533d00774a6.png)

### New case

However, in other cases, when changing the hour, it happened that `loop_start > loop_end`, for instance, -1 hour. When applying the formula (subtracting a negative value), the following positive result came out:

![image](https://user-images.githubusercontent.com/10536251/164676025-068bb1c4-510a-42f0-b573-48b34b83a6f9.png)

That is positive and much less than 63 years, but even so, it does not honor the throughput.

### Solution

Apply a double guard:

![image](https://user-images.githubusercontent.com/10536251/164676646-ce90bfcb-fe5a-482c-af87-229a525f2559.png)
