### ISSUE TITLE
The agent registration timestamp is wrong

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#12931]
|Wazuh version|Component|Install type|Install method|Platform|Related issue|
|---|---|---|---|---|---|
| 4.3.0-rc5 | Authd, Cluster & Wazuh DB | Manager | Packages | Ubuntu 20.04 | #12875 |
| 4.3.0-rc5 | Agent-auth | Agent | Packages | macOS Catalina | |

After deploying an agent on macOS Catalina:

```sh
curl -so wazuh-agent-4.3.0.pkg https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.3.0-1.pkg
launchctl setenv WAZUH_MANAGER '35.87.169.68' WAZUH_AGENT_GROUP 'default' && sudo installer -pkg ./wazuh-agent-4.3.0.pkg -target /
/Library/Ossec/bin/wazuh-agent start
```

The agent gets connected to the manager, but the registration time appears as Jan 1, 1970:

![Screenshot 2022-03-29 130320 Timestamp](https://user-images.githubusercontent.com/10536251/160874581-b38a1b64-008a-4c9c-8e80-9031421470d7.JPEG)

However, the file `agents-timestamp` contains this agent's data.

### Agents timestamp file content

```
001 macos-1015 any 2022-03-29 10:55:56
```

### Agent table content

```
select * from agent
```
|id|name|ip|register_ip|internal_key|os_name|os_version|os_major|os_minor|os_codename|os_build|os_platform|os_uname|os_arch|version|config_sum|merged_sum|manager_host|node_name|date_add|last_keepalive|group|sync_status|connection_status|disconnection_time|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|0|ip-172-31-48-31|127.0.0.1|127.0.0.1||Ubuntu|20.04.3 LTS|20|04|Focal Fossa||ubuntu|Linux &#124;ip-172-31-48-31 &#124;5.13.0-1019-aws &#124;#21\~20.04.1-Ubuntu SMP Wed Mar 16 11:54:08 UTC 2022 &#124;x86_64|x86_64|Wazuh v4.3.0|||ip-172-31-48-31|wazuh-1|1648485822|253402300799||synced|active|0|
|1|macos-1015|10.0.2.15|any|...|Mac OS X|10.15.1|10|15|Catalina||darwin|Darwin &#124;macos-1015 &#124;19.0.0 &#124;Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 &#124;x86_64|x86_64|Wazuh v4.3.0|57c402a919ef1c7f4624c3fe159c75fe|e226bf1341f475a2a017f5fdbad8106b|ip-172-31-50-253|wazuh-2|0|1648659773|default|synced|active|0|

### Enrollment flow

![image](https://user-images.githubusercontent.com/10536251/160893080-1f71f0f3-095f-4589-a841-a8dcdb7d3a58.png)

**Comment by alberpilot** [comment]
I was able to reproduce this problem on Windows 2019 server

![image](https://user-images.githubusercontent.com/3830293/196759774-10d9d8ce-17be-4407-9735-e6b358cbccea.png)

The environment was provided to @Dwordcito team

**Comment by MiguelazoDS** [comment]
# Analysis

## Unable to reproduce using UI installer

### Single master

- Manager: Wazuh OVA v4.3.8
- Agent: Windows 10

<details>
<summary>Click to expand</summary>

![1](https://user-images.githubusercontent.com/13010397/197268402-278545d0-5e3a-4475-9c62-b0fe26430d25.png)
![2](https://user-images.githubusercontent.com/13010397/197268409-1e1b4cd2-6cf6-4dcf-be4b-77908f629539.png)
![3](https://user-images.githubusercontent.com/13010397/197268414-6e2e9845-a994-47ee-a550-3771bb1ecce1.png)
![4](https://user-images.githubusercontent.com/13010397/197268416-c57c66af-397f-4574-9952-94910f6ab33c.png)

</details>

### Cluster 

- Master: Wazuh OVA v4.3.8
- Worker: Ubuntu Jammy v4.3.8
- Agent: Windows 10

<details>
<summary>Click to expand</summary>

![1](https://user-images.githubusercontent.com/13010397/197268500-bcb777af-abc7-429e-814c-82755ddda3bc.png)
![2](https://user-images.githubusercontent.com/13010397/197268507-a45046ba-b96b-4417-9726-01451009e2b7.png)
![3](https://user-images.githubusercontent.com/13010397/197268508-5f7bfe5d-19da-4b47-9e8e-a43aec4d1f0d.png)
![4](https://user-images.githubusercontent.com/13010397/197268509-b86a39bd-7ad5-4d39-b698-37e64eb02e58.png)
![5](https://user-images.githubusercontent.com/13010397/197268514-545f979e-59a9-49be-b773-cfdf4262ee1c.png)

</details>

**Comment by MiguelazoDS** [comment]
# Update 12/05/22 

It was found that this issue is not reproducible by adding 15 seconds before creating the agents-timestamp file for releases >4.3.x. In 4.4 the implementation to migrate the agent groups from files to wazuh-db https://github.com/wazuh/wazuh/pull/11753 introduced some changes that fixed this issue. 

Specifically the call of wdb_insert_agent() in the run_writer thread. Since the timestamp information dump into agents-timestamp file and the read of the file before inserting the agent into the database is performed by the same thread, the 15s delay added before updating the agents-timestamp information is harmless regarding this issue.

**Comment by Dwordcito** [comment]
Closed based on the last comment.
