### ISSUE TITLE
Release 4.3.0 - Manual tests - Installation alternatives - Installing Wazuh with Elastic Stack

### ISSUE THREAD

**Issue by MauGaP** [wazuh/wazuh#12936]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Installing Wazuh with Elastic Stack |
| **Category**            | Installation |
| **Deployment option**   |  Unatended |
| **Main release issue**  |https://github.com/wazuh/wazuh/issues/10954|
| **Release candidate #** | RC5 |

## Test description
- [ ] Test1 - Try the latest version of Elastic Stack supported by our interface (Kibana plugin).
- [ ] Test2 - Check that documentation steps work as intended.
- [ ] Test3 - Check the WUI for any error or incorrect data
- [ ] Test4 - Check that creation of new rules from the WUI works correctly
- [ ] Test5 - Check that configuration of the manager from the WUI works correctly
- [ ] Test6 - Check that the configuration/assignment of agent groups from the WUI works correctly 

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the comments of [this issue](#12936).

| **Test** | **Environment** | **Status** | **Comments** | **Issues** |
|---|---|---|---|---|
|  Try the latest version of Elastic Stack supported by our interface (Kibana plugin).  | AIO 		| 🟢| No comments |  none   	|
|  Try the latest version of Elastic Stack supported by our interface (Kibana plugin).  | Distributted | 🟢|  No comments   |  none  	|
|  Check that documentation steps work as intended  | AIO 		|  🟢|  All needed modifications have been discussed on the document |  none   	|
|  Check that documentation steps work as intended  | Distributted  |  🟢|  All needed modifications have been discussed on the document  |  none  	|
|  Check the WUI for any error or incorrect data | AIO 		|  🟢|  The installation manual doesn't include the field `server.publicBaseUrl` is the only toast error we got  |  none   	|
|  Check the WUI for any error or incorrect data | Distributted  |  🟢|   No comments  |  none  	|
|  Check that creation of new rules from the WUI works correctly | AIO 		|  🟢|  No comments   |  none   	|
|  Check that creation of new rules from the WUI works correctly | Distributted |  🟢|   No comments  |  none  	|
|  Check that configuration of the manager from the WUI works correctly | AIO 		|  🟢|  No comments   |  none   	|
|  Check that configuration of the manager from the WUI works correctly | Distributted |  🟢|  No comments   |  none  	|
|  Check that the configuration/assignment of agent groups from the WUI works correctly | AIO 		|  🟢|   No comments  |  none   	|
|  Check that the configuration/assignment of agent groups from the WUI works correctly   | Distributted |  🟢|  No comments   |  none  	|

All tests have passed, and the document has been updated to make it more user-friendly. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @davidjiglesias

**Comment by MauGaP** [comment]
## Execution report 3/29 - 3/30
[x] Creating environments using vagrant, and virtualBox
[x] Installation of Wazuh from scratch using the steps in the documentation.

**Comment by MauGaP** [comment]
## execution report 3/31
### :green_circle: Installation of Wazuh server
### :green_circle: Installation of Wazuh manager
### :green_circle: Installation of Filebeat
### :green_circle: Installation of Kibana
### :green_circle: Configuration of Kibana
### :yellow_circle: Installation of Wazuh Kibana plugin 
minor: I didn't find the packages-dev file for kibana app plugin, started installing with a local compiled one.
will uninstall and install again tomorrow.

**Comment by MauGaP** [comment]
## Execution report 4/01
### :green_circle: Installed everything back again, to capture screenshots for previos steps
### :red_circle: Couldn't connect to the WUI beacuse password set in kibana.yml was wrong, could not create new certificates,

**Comment by MauGaP** [comment]
## Execution report 4/05
 ### :green_circle:

**Comment by mauceballos** [comment]
## Execution report 04/05

### :green_circle: set nodes using vagrant

![Screenshot from 2022-04-05 09-13-36](https://user-images.githubusercontent.com/76791841/161850597-792fe451-a8eb-49c9-a14a-69690eae38eb.png)

### :green_circle: Installation of ElasticSearch 7.17.0-1

![Screenshot from 2022-04-05 18-03-37](https://user-images.githubusercontent.com/76791841/161848997-5938b025-ee62-4088-b37c-0140f9b10969.png)

### :green_circle: Installation of wazuh-kibana-4.3.0_7.17.0-1

### :green_circle: Installation of Kibana 7.17.0

![Screenshot from 2022-04-05 17-27-00](https://user-images.githubusercontent.com/76791841/161849817-3b7abbc9-99f7-464a-98fc-bd88b14aacd1.png)
h

### :green_circle: Installation of filebeat-7.17.0-1
![Screenshot from 2022-04-05 14-14-09](https://user-images.githubusercontent.com/76791841/161850225-69ad3cbf-254d-4e3b-b3a7-783c1835673c.png)

### :green_circle: Installation of wazuh-manager 4.3
![Screenshot from 2022-04-05 14-48-22](https://user-images.githubusercontent.com/76791841/161850430-80d8af1b-3b1e-41c1-99b2-be2fbd5810de.png)

### :red_circle:  Couldn't connect the web interface

> URL: https://192.168.56.3
user: elastic
password: <PASSWORD_elastic>

**Comment by mauceballos** [comment]
Execution report 04/06

### :green_circle: web interface

<details><summary>Details</summary>

![Screenshot from 2022-04-06 08-11-30](https://user-images.githubusercontent.com/76791841/161963640-46ff8281-7991-4180-a204-43c5c8c8b8c3.png)

</details>
