### ISSUE TITLE
Obsolete variable name in `opensearch_dashboards.yml` configuration file

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh#12973]
|Wazuh version |Install type |Platform|
|---|---|---|
| 4.3 | Wazuh-Dashboard | Linux |

# Description
The file that contains the Wazuh-Dashboard configuration `/etc/wazuh-dashboard/opensearch_dashboards.yml` has a variable name that could create confusion.
The name `kibana_read_only` is obsolete because Kibana is no longer used in Wazuh environment.

### File configuration
```
server.host: 0.0.0.0
server.port: 443
opensearch.hosts: ["https://172.18.1.10:9200/","https://172.18.1.11:9200/","https://172.18.1.12:9200/"]
opensearch.ssl.verificationMode: certificate
#opensearch.username:
#opensearch.password:
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: true
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wazuh?security_tenant=global
```

> Note: The `kibana_read_only` variable should be replaced by a name that makes reference to Wazuh dashboard.

**Comment by okynos** [comment]
Hello!

Performing a request on OpenSearch 1.3.1 default installation `curl -k -u admin:admin https://127.0.0.1:9200/_opendistro/_security/api/roles?pretty` we got:
```
  "kibana_read_only" : {
    "reserved" : true,
    "hidden" : false,
    "cluster_permissions" : [ ],
    "index_permissions" : [ ],
    "tenant_permissions" : [ ],
    "static" : false
  },
```

So we can conclude that the `kibana_read_only` role doesn't belong to indexer specific features and it will be solved in a future release.

Thanks!

**Comment by gdiazlo** [comment]
The name of the default roles come from the upstream platform, we cannot change nor modify default roles because we can break other components which expects them.
