### ISSUE TITLE
It is recommended that Wazuh support yara rule syntax for malware detection or support more complex matching patterns 

### ISSUE THREAD

**Issue by cutalk** [wazuh/wazuh#12980]
I think Yara is a good tools for testing  malicious software signature , but when we use Yara  in production enviroments ,  we need to review Yara code and modify some code for system stability. Yara has many rules on the internet, but Yara is only the test tool,not a tool in production enviroments.
So,it is recommended that Wazuh support yara rule syntax for malware detection or support more complex matching patterns . Best regards and thank you.

**Comment by vikman90** [comment]
Hi @cutalk,

We have an open issue to add a module to the agent that supports YARA rules, integrating the YARA library internally: #3357. Unfortunately, it's not finished yet, and it is in the icebox.

Feel free to follow up on that issue, and let me close this ticket as it's a duplicate. Should you have any questions, feel free to reopen it.

Best regards.

**Comment by cutalk** [comment]
Thanks
