### ISSUE TITLE
Improve how Github integration handles some of the internal events

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#12982]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Github integration | Manager/Agent | All | All |

Hello team,

After testing the Github integration I observed we are considering events from Github integration as they were proper events from Github. The same way we are doing with other Cloud integrations.

For instance, when calling the GitHub API and we get a bad credential, we should throw an error in the integration instead of parsing it as a GitHub event:

```
{
  "_index": "wazuh-alerts-4.x-2022.03.31",
  "_type": "_doc",
  "_id": "dHXi338BnPYykzjRKsEB",
  "_version": 1,
  "_score": null,
  "_source": {
    "input": {
      "type": "log"
    },
    "agent": {
      "name": "localhost.localdomain",
      "id": "000"
    },
    "manager": {
      "name": "localhost.localdomain"
    },
    "data": {
      "github": {
        "actor": "wazuh",
        "response": "{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/rest\"}",
        "organization": "test"
      },
      "integration": "github"
    },
    "rule": {
      "firedtimes": 2,
      "mail": false,
      "level": 3,
      "description": "GitHub module internal event, 3 request fail.",
      "groups": [
        "github",
        "git"
      ],
      "id": "91448"
```

The same if the org doesn't exist

```
data": {
      "github": {
        "actor": "wazuh",
        "response": "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#get-audit-log\"}",
        "organization": "hatmen-es"
      },
      "integration": "github"
```

**Comment by TomasTurina** [comment]
Hi @MiguelCasaresRobles,

This alerts was built this way so it can be associated to all the alerts that are produced in the GitHub module. To differentiate and internal alert with the rest of alerts, we used the field `github.actor` to indicate that it was produced internally by `wazuh`. I consider this is not something that needs to be fixed (cc @vikman90).

**Comment by vikman90** [comment]
Hi @MiguelCasaresRobles,

In addition to the alert you showed, the agent prints a warning like this (#13944):

```
2023/01/16 17:32:54 wazuh-modulesd:github: WARNING: Sending GitHub internal message: '{"integration":"github","github":{"actor":"wazuh","organization":"insert_organization_name","event_type":"git","response":"{\"message\":\"Bad credentials\",\"documentation_url\":\"https://docs.github.com/rest\"}"}}'
```

Let me close this issue, feel free to open it back if you want to request any change.

Best!
