### ISSUE TITLE
[Devel] Several "Config on demand" issues and requests

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#1301]
Hello team,

The new "**Query agent/manager configuration on demand**" has several bugs and missing features that I would like to discuss with you.

#### Bugs:
- Some sections are unavailable and the API call throws an `Unable to connect with socket` error.
  - Some of these sections: `mail/alerts`, `mail/global`, `auth/auth`, `integrator/integration`, `labels`, etc.
- Some sections are missing, such as `cluster`, `ruleset`, etc.
- Some sections such as `request/remote` are not showing the complete information.
- The vulnerability detector configuration doesn't show the feeds if these are disabled, but in other configuration blocks, the configuration appears although they're disabled, so this is an inconsistency. The right way would be to always show the configuration present on the `ossec.conf` file.
- There are some inconsistencies between the previous existing API call to get the manager configuration and this new one. For example, it's not 100% clear what sections on the `ossec.conf` can be repeated, or only the last one is read from the manager/agent. For example, `wmodules` and the `command` wodle, which I think can be multiple times on the `ossec.conf` but only appears a single command on the API call.

#### Some requests:
- We would like to have an API call to retrieve all the configuration from an agent/manager at the same time, instead of calling every single component.
- We would like to have a reference about the JSON format used to display the configuration, so we can see what options are arrays, key-value pairs, etc.

Regards,
Juanjo

**Comment by TJOSERAFAEL** [comment]
Maild isn't creating the socket on `/var/ossec/queue/ossec/mail` returning **ENOENT**. 
We are investigating this bug.

**Comment by TJOSERAFAEL** [comment]
Ok we are closing this issue now.

**What remains:**
- Request information about **ruleset**
- Request information about **cluster**
- API call to retrieve all the configuration from an agent/manager at the same time

We are continuing this issue here: https://github.com/wazuh/wazuh/issues/1318
