### ISSUE TITLE
WDB - Unexpected sync-agent-groups-get wdb command response on negative last_id

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#13039]
# Description 

Working on Issue [#2532](https://github.com/wazuh/wazuh-qa/issues/2532) on the `**sync-agent-groups-get**` command, it was found that when passing a negative **`last_id`** value,  you will get a valid response, even though it is expected to fail since there is no valid negative id.

## Details: 

|Wazuh version |Install type| OS type |
|---|---|---|
| 4.4 | Manager | [Wazuh_v4.4.0](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-WDBcommands.x86_64.rpm)|

### Local_internal_options
No local internal options used.

------------

## Steps to reproduce

This steps are the ones being done in case 22 of test module [test_wazuh_db/test_sync_agent_groups_get.py](https://github.com/wazuh/wazuh-qa/blob/it-wazuh-db-migration-of-agent-groups-files/tests/integration/test_wazuh_db/test_sync_agent_groups_get.py), currently located in the QA repo.

1. Add one `agent1`  to de db. command: 
   > global insert-agent {"id":1,"name":"Agent1","date_add":{date}}

2. Add agent1 group data with set-agent-groups: 
   > global set-agent-groups {"mode":"append","sync_status":"syncreq","data":[{"id":1,"groups":["Test_group1"]}]}
3. Add one `agent2`  to de db. command: 
   > global insert-agent {"id":2,"name":"Agent1","date_add":{date}}
   
4. 2. Add agent2 group data with set-agent-groups: 
   > global set-agent-groups {"mode":"append","sync_status":"syncreq","data":[{"id":2,"groups":["Test_group2"]}]}
5. Call the `sync-agent-groups-get`  command with `last_id = -3: 
   > global sync-agent-groups-get {"last_id":-3, "condition":"sync_status"}

#### Expected Results
- An error message for invalid response was expected since there is no valid negative id to look for.
#### Actual Results
- Comand is executed without issue and gives out response: 
   > [{'data': [{'id': 1, 'groups': ['Test_group1']}, {'id': 2, 'groups': ['Test_group2']}]}]

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/13057 with the fix was merged.
