### ISSUE TITLE
Engine - HLP refinements

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#13037]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | - | - |

We need to integrate the logql parsers with the schema and add
additional parsers to support the schema defined types.

Additionally, we need to map the parsing results to JSON easily, and
supporting all the JSON types where appropriate.

These types are defined in  https://github.com/wazuh/wazuh-threatintel/blob/master/assets/schema/field_type.json

- [x] Logql field validation against schema
  - [x] Design a way to validate a logql field against a schema like
  the one referenced above
  - [x] The logql parser should receive the schema information through
  the catalog. Modify the catalog to support these operations.
  - [x] The LogQL parser will need to receive a catalog instance to
  query the schema.
  - [x] Implement the validation.

- [x] Implement additional parsers
  - [x] keyword parser: a parsers which is able to capture data until
  a space is found.
  https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html#keyword-field-type
  see for more context.
  - [x] quoted parser: a parser which will consume a quoted string,
  supporting the escape of quotes. The quote char can be passed as
  a parameter optionally.
  - [x] any parser: a parser which will consume from the current
  point to the end of the buffer
  - [x] number parse: a parser which will return an integer or a
  floating point number as supported in JSON

- [x] LogQL result refinement
  - [x] Support for all JSON types in the result type returned by the
  logql parser execution.
  - [x] Map from the result returned by the logql parser to JSON in
  the operation generated by the builder

**Comment by LucioDonda** [comment]
Pending changes for a next iteration:
- Error message on build asset step:
   - When no parser is found for any field it shouldn't continue
- Error message on configuring catalog.
   - When any of the parsers needed is not yet implemented.
- Add tracer for HLP
- Fix catalog test
- Remove cli tools HLP
- Recheck any parser implementation or explicitly create a to_the_next_token parser
