### ISSUE TITLE
Alert generated has 'vulnerability.references'  field with an incomplete value. 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#13047]
# Description 

Working on Issue [#12902](https://github.com/wazuh/wazuh/issues/12902) , we detected that when an alert has generated the 'vulnerability.references' value contains a URL with dots. 

For us, it isn't correct. 

## Details: 

|Wazuh version |Install type| OS type |
|---|---|---|
| 4.3 | Manager | [AMI - Wazuh_v4.3.0](https://us-east-1.console.aws.amazon.com/ec2/home?region=us-east-1#ImageDetails:imageId=ami-0e062a80bd73a63b6)|

|Wazuh version |Install type |Platform|
|---|---|---|
| 4.3| Agent| Amazon Linux (aws) |

### Local_internal_options

> wazuh_modules.debug=2
> monitord.rotate_log=0

------------

## Steps to reproduce

1. In the manager, edit /`var/ossec/etc/ossec.conf` vulnerability detection section with [Ossec.conf - VD - Manager.txt](https://github.com/wazuh/wazuh/files/8381886/Ossec.conf.-.VD.-.Manager.txt).
2. Registered and connected agent with the manager.
3. Restart Agent and Manager.
4. We detected a vulnerability alert with a package `perl` on `/var/ossec/logs/alerts/alerts.log` on Manager. 
   
 ## Results

  -  `Current Results:` The alert has the vulnerability.references value with a URL incomplete. 
  
      ![imagen](https://user-images.githubusercontent.com/3978434/161742238-810838b5-f191-456b-8694-d334c4adc132.png)

  -  `Expected Results:` The alert has the value of the vulnerability references with a correct URL.

**Comment by pereyra-m** [comment]
Hi @damarisg !

It seems that in this case, the URL is correct. The link points to a valid site

```
https://github.com/Perl/perl5/compare/v5.30.2...v5.30.3
``` 

The dots are used by Github when branches are compared.

Regards.

**Comment by vikman90** [comment]
Hi team, 

Let me close this issue as the alert seems to be correct. Should you have further questions or want to extend this issue, feel free to reopen it.

Best.
