### ISSUE TITLE
Add SCA Policy for CIS Microsoft Windows Enterprise and Server families

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#13086]
| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | New and Improve |  #14358 

## Description

- [x] #13191
- [x] #13087
- [x] #13895

**Comment by fabamatic** [comment]
Removed references to multiple compilations. As stated by CIS the latest benchmark (create for Windows 10 21H2) should be used in older Windows 10 releases
