### ISSUE TITLE
Create SCA Policy for Alibaba Cloud Linux 3

### ISSUE THREAD

**Issue by hustliyilin** [wazuh/wazuh#13093]
|Wazuh version| Component | Action type |
|---| --- | --- |
| master | SCA | New |

CIS Alibaba Cloud Linux 3 Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/8034) was published
on Feb 6th 2022. Alibaba Cloud Linux 3 is compatible with Centos 8.
Besides, The ID of Alibaba Cloud Linux 3 in /etc/os-release is 'alinux'

I add the Alibaba Cloud Linux 3 SCA in the wazuh
according to CIS Alibaba Cloud Linux 3 Benchmark v1.0.0
(https://workbench.cisecurity.org/benchmarks/8034)

**Comment by 72nomada** [comment]
We will add this to the pool of checks. We will have this done soon. 

Related 
#12052

**Comment by hustliyilin** [comment]
Hi @72nomada ,

#13094 is already ready for review. Could you give some review suggestions? Thanks

**Comment by 72nomada** [comment]
Hi, we will, it is planned for the next major.

**Comment by hustliyilin** [comment]
Hi @72nomada ，

Thanks for your reply. Do you mean you plan to include this CIS SCA support in the Wazuh 4.5.0? And when will Wazuh 4.5.0 be released？ Besides， What else do I need to do? Thanks a lot.

**Comment by 72nomada** [comment]
hi @hustliyilin, I would like to have it released sooner than 4.5.0, but we need to review texts and rules, also there is no compliance in your yml file, so we have to add it.

Some commands will not work:

```
  # 1.1.7.3 /home: nosuid
  - id: 31018
    title: "Ensure nosuid option set on /home partition"

    condition: any
    rules:
      - 'c:findmnt --kernel /home | grep nosuid -> r:\s/home\s && !r:nosuid'
      - "c:findmnt --kernel /home -> !r:.*"

 # pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['
...
2023/04/01 12:10:02 sca[925] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'findmnt --kernel /home | grep nosuid', and testing output with pattern 'r:\s/home\s && !r:nosuid'
2023/04/01 12:10:02 sca[925] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'findmnt --kernel /home | grep nosuid' returned code 1
...
```

Let me finish our "guide to building an SCA" and I will share it with you (and all community) so you can modify your yml file if you want. We will take care of it anyway.
Thanks so much for your help, is a failure on our side, and we should have a "how to contribute to SCA" updated and published.

**Comment by hustliyilin** [comment]
Hi @72nomada ，

Thanks  for your reply.  You let me know that there are some bugs within my codes, which is very helpful for me. I will fix, retest, and resubmit it as soon as possible. I am also looking forward to seeing the guide you mentioned soon. I am very happy to cooperate with you, and I also look forward to greater gains in the Wazuh community. Thanks again.

**Comment by hustliyilin** [comment]
Hi @72nomada ,

When I harden the Linux OS(`Alibaba Cloud Linux 3`) and then test with this PR. This is my test result.

![image](https://user-images.githubusercontent.com/6824093/229289952-7dbe07bf-5684-4cd3-98ba-b905793910a4.png)

How Can I get your test log above like this? Thanks a lot.
...
2023/04/01 12:10:02 sca[925] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'findmnt --kernel /home | grep nosuid', and testing output with pattern 'r:\s/home\s && !r:nosuid'
2023/04/01 12:10:02 sca[925] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'findmnt --kernel /home | grep nosuid' returned code 1
...

**Comment by 72nomada** [comment]
Use this command.

````

pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['

````
You should define a policy with one check for easier trace.

**Comment by rain-Qing** [comment]
> hi @hustliyilin, I would like to have it released sooner than 4.5.0, but we need to review texts and rules, also there is no compliance in your yml file, so we have to add it.
> 
> Some commands will not work:
> 
> ```
>   # 1.1.7.3 /home: nosuid
>   - id: 31018
>     title: "Ensure nosuid option set on /home partition"
> 
>     condition: any
>     rules:
>       - 'c:findmnt --kernel /home | grep nosuid -> r:\s/home\s && !r:nosuid'
>       - "c:findmnt --kernel /home -> !r:.*"
> 
>  # pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['
> ...
> 2023/04/01 12:10:02 sca[925] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'findmnt --kernel /home | grep nosuid', and testing output with pattern 'r:\s/home\s && !r:nosuid'
> 2023/04/01 12:10:02 sca[925] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'findmnt --kernel /home | grep nosuid' returned code 1
> ...
> ```
> 
> Let me finish our "guide to building an SCA" and I will share it with you (and all community) so you can modify your yml file if you want. We will take care of it anyway. Thanks so much for your help, is a failure on our side, and we should have a "how to contribute to SCA" updated and published.



> hi @hustliyilin, I would like to have it released sooner than 4.5.0, but we need to review texts and rules, also there is no compliance in your yml file, so we have to add it.
> 
> Some commands will not work:
> 
> ```
>   # 1.1.7.3 /home: nosuid
>   - id: 31018
>     title: "Ensure nosuid option set on /home partition"
> 
>     condition: any
>     rules:
>       - 'c:findmnt --kernel /home | grep nosuid -> r:\s/home\s && !r:nosuid'
>       - "c:findmnt --kernel /home -> !r:.*"
> 
>  # pkill modulesd; /var/ossec/bin/wazuh-modulesd -fdd 2>&1 | grep 'sca\['
> ...
> 2023/04/01 12:10:02 sca[925] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'findmnt --kernel /home | grep nosuid', and testing output with pattern 'r:\s/home\s && !r:nosuid'
> 2023/04/01 12:10:02 sca[925] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'findmnt --kernel /home | grep nosuid' returned code 1
> ...
> ```
> 
> Let me finish our "guide to building an SCA" and I will share it with you (and all community) so you can modify your yml file if you want. We will take care of it anyway. Thanks so much for your help, is a failure on our side, and we should have a "how to contribute to SCA" updated and published.

Hi @72nomada , Excuse me   I got the debug logs based on the command you provided above.
I have two questions to ask you

- How do you judge that the codes are not working based on the logs? Is it because of `return code 1`?
- Additionally, I tested other SCA files in the Wazuh repository, such as
Redhat 9 and Amazon 2, I have seen many times that they have a lot of "return code 1" logs, so I don't know how to judge whether the codes are wrong or not now.

I'm looking forward for your reply. Thanks.

**Comment by 72nomada** [comment]
Hi @rain-Qing 

Well, a `return code 1` is usually a symptom that something is maybe wrong with your rule. You must read the full check debug output to find the real reason. Also, you will need to run the command your try to run directly on the shell to find the expected output and crosscheck with your SCA check debug info. 

If you get a few of `code 1` maybe you can reach me on wazuh slack so we can share details. 
We can give feedback here about the findings.

**Comment by mwbisma09** [comment]
Hi @hustliyilin & @72nomada

I'm wondering when will this issues/pr will be included in a version release?
Really interested to contribute and adopt in as well, appreciate your replies.

**Comment by hustliyilin** [comment]
Sorry, I will close it now.
