### ISSUE TITLE
Unattended Script does not install the wazuh-alerts index

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#13106]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | WUI | Manager / WUI | Unattended Scrip | Rocky Linux 8.5 |

### Description
It was found that after following the unattended installation documentation, the wazuh-alerts-* index is not properly installed, so no information is shown on the WUI.

### Steps taken to reproduce

1. Follow Elastic installation steps [here](https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.html)
2. Follow the Wazuh Cluster Installation steps [here](https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/unattended/unattended-wazuh-cluster-installation.html)
3. Register an Agent to the manager.
4. Open the WUI (On the opening healthcheck an alert of the missing cluster will show).
5. Go to the agent's information: you will get pop up `Error getting alerts from compliances
Your environment may not have any index with Wazuh's alerts.` on the lower right corner of the screen.

### Screenshots
![Captura de pantalla de 2022-04-11 19-51-40](https://user-images.githubusercontent.com/14501079/162847352-ef5068b0-ee8d-4776-96b2-0ff0406ef25b.png)
![Captura de pantalla de 2022-04-11 19-55-26](https://user-images.githubusercontent.com/14501079/162847358-badbe85b-25a0-4814-8fad-54d733ba9572.png)

**Comment by chrisgerman** [comment]
I'm also getting this error too. I have done "Unattended installation" and "Step-by-Step" on a clean install of Ubuntu 22.04 LTS. @Deblintrake09 can you elaborate more on how to fix this issue?
