### ISSUE TITLE
Please add audit.process.ppname to Linux agent FIM whodata collection

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#1310]
We are already getting audit.proccess.id and audit.proccess.name in whodata, plus audit.proccess.ppid for the id of the parent process.  That ppid would be much more valuable if the parent process name were included, perhaps as audit.process.ppname.

**Comment by crolopez** [comment]
Hi @branchnetconsulting,

In linux, Wazuh shows the information that is extracted from Audit, which gives us the id of the parent process but not its path. We will study to include it in a future release.

Best regards.

**Comment by bah07** [comment]
Hi @branchnetconsulting 

We already merge de pull #4782 into 3.13 release.

It includes the fields.

    The current working directory of the process.
    Parent process id.
    The current working directory of the parent process.

Thanks for your contribution. Regards.
