### ISSUE TITLE
Debian wazuh-agent package install errors non-printing characters at end of agent.conf file

### ISSUE THREAD

**Issue by felimwhiteley** [wazuh/wazuh#1314]
Hi there

Setting up wazuh-agent (3.6.1-1) ...
mv: cannot stat '/var/ossec/tmp/installation_files/group/agent.conf': No such file or directory
dpkg: error processing package wazuh-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
Performing an ls on that directory I can see the agent.conf but trying to ls it it doesn't list directly until you use tab completion and can see that there are backslash escaped non-printing characters at the end.
ls -b /var/ossec/tmp/installation_files/group/ | od -cx
0000000   a   g   e   n   t   .   c   o   n   f   \      \n   a   r   .
           6761    6e65    2e74    6f63    666e    205c    610a    2e72

appears to just be whitespace. Renaming the whitespace with mv command cleared the error. I've encountered this on several machines so appears to be an issue in setup script somewhere.

Thanks

**Comment by juan70** [comment]
Hi, felimwhiteley,

We are trying to reproduce the issue.

But we need a bit more of information. For example: Debian or Ubuntu, which version, 32 or 64 bits; you seem to be performing an upgrade, from what version, 3.6.0 or earlier?; where do the packages come from (repository or compiled by you)?; when did you download them? Are you upgrading using apt-get or dpkg? The more information, the better.

Could you please also copy-paste the output of the following command, if possible, with the .../etc/shared directory containing the files *before* upgrading?
`# ls -b /var/ossec/etc/shared/ | od -cx`

Thank you.

**Comment by felimwhiteley** [comment]
Apologies, in my head I'd pasted that in, so it is:

Ubuntu 16.04.4 
Debian package v3.3.1

Unfortunately I don't have any more of the debian packages to upgrade. I do have a bunch of v2.0 tarball agents that need to swap over to the deb package, I'll run that before I upgrade them in case it also occurs. I'll try get one in today or early in the morning (Irish time).

**Comment by juan70** [comment]
Hi, felimwhiteley,

So, if I understand correctly, the file name with a space was sort of added by you (correct me if I'm wrong).
The solution here should be, indeed, to delete the file 'agent.conf ' (with the space character) after copying the configuration to the file 'agent.conf' (without the space character). Or to delete 'agent.conf' and rename 'agent.conf ' as 'agent.conf'.
Nevertheless, we are going to modify our code in order to avoid the interruption of the upgrade process in case this kind of situation happens again.

Thank you.
Best regards.

**Comment by felimwhiteley** [comment]
It was added by me, but the part I'm uncertain about (or even how I possibly would have added the whitespace) is I edited your base agents.conf. So unless in that it somehow saved with a whitespace which I find a little odd (but not impossible I suppose). Anyway if you are updating the installer that's great news. I imagine you don't add your own agents.conf which somehow moved the one I'd written? Most likely a PEBKAC ;-) Cheers for uipdating the installer anyway!

**Comment by rakanskiy** [comment]
So, it would be fixed package with 3.6.2 version or it be in 3.7 release?

**Comment by juan70** [comment]
Hello, @rakanskiy, @felimwhiteley,

A typo in the scripts for the deb packages seems to be the cause. The typo is not present for the rpm packages.

This issue should be fixed now, in version 3.7.1 (PR https://github.com/wazuh/wazuh-packages/pull/96).

Thank you.
Kind regards.

**Comment by felimwhiteley** [comment]
Cheers Juan, thanks for looking into it, I'll be upgrading the lot again to latest release so I'll ping back if encounter it again. Hopefully not! :-)

**Comment by felimwhiteley** [comment]
Confimred, did an upagrade to 3.7.0 and worked perfect. Many thanks
