### ISSUE TITLE
Release 4.3.0 - Release Candidate 6 - Upgrade metrics

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#13159]
### Packages tests metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #13154 |
| **Main packages metrics issue** | #13155 |
| **Version** | 4.3.0                                     |
| **Release candidate #** | RC6                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.0-rc6                                        |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

---

| Version | Build |
| -- | -- |
| 3.5.0 to 4.2.6 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1890 |
| 4.2.6 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1891 |
| 4.2.6 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1903 |
| 4.2.5 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1892 |
| 4.2.5 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1904 |
| 4.2.4 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1893 |
| 4.2.3  |  https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1894 |
| 4.2.3 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1906 |
| 4.2.2  |  https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1895 |
| 4.2.1  | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1896  |
| 4.1.5 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1902 |
| 4.1.3 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1907 |
| 4.1.1 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1908 |
| 4.1.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1901 |
| 4.0.4 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1919 |
| 4.0.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1918 |
| 3.13.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1913 |
| 3.13.2 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1917 |
| 3.12.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1910 |
| 3.12.3 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1916 |
| 3.11.4 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1915 |
| 3.11.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1920 |
| 3.10.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1931 |
| 3.9.5 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1941 |
| 3.9.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1929 |
| 3.8.2 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1934 |
| 3.8.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1930 |
| 3.7.2 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1936 |
| 3.6.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1940 |
| 3.5.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1945 |
| 3.5.0 | https://ci.wazuh.info/view/Tests/job/Test_upgrade_tier/1943 |

---

| System | 3.5.0 | 3.6.0 | 3.6.1 | 3.7.0 | 3.7.2 | 3.8.0 | 3.8.2 | 3.9.0 | 3.9.5 | 3.10.0 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --  |
| CentOS 8                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| CentOS 7                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| CentOS 6                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| CentOS 5                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Debian 11                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Debian 10                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Debian 9                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Fedora 32                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Fedora 31                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Ubuntu Focal                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Ubuntu Bionic                        | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Ubuntu Xenial                        | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Ubuntu Trusty                        | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Amazon Linux 2                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Amazon Linux 1                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Oracle Linux 8                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| OpenSuse Tumbleweed                  | X  | X  | X  | X  | X  | 🟢 | X  | 🟢 | X | 🟢 |
| Redhat 6                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Redhat 7                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |
| Redhat 8                             | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |🟢 |

| System | 3.10.2 | 3.11.0 | 3.11.4 | 3.12.0 | 3.12.3 | 3.13.0 | 3.13.2 | 4.0.0 | 4.0.4 |
| -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
| CentOS 8                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 7                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 6                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| CentOS 5                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Debian 11                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Debian 10                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Debian 9                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Fedora 32                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Fedora 31                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Focal                      | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Ubuntu Bionic                     | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  
| Ubuntu Xenial                     | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  
| Ubuntu Trusty                     | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Amazon Linux 2                    | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Amazon Linux 1                    | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| Oracle Linux 8                    | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 
| OpenSuse Tumbleweed               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  
| Redhat 6                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  
| Redhat 7                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  
| Redhat 8                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |  

| System | 4.1.0 | 4.1.1 | 4.1.2 | 4.1.3 | 4.1.4 | 4.1.5 |
| -- | -- | -- | -- | -- | -- | -- |
| CentOS 8                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 7                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 6                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 5                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 11                           | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 10                           | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 9                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 32                           | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 31                           | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Focal                        | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Bionic                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Xenial                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Trusty                       | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 2                      | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 1                      | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Oracle Linux 8                      | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| OpenSuse Tumbleweed                 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 6                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 7                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 8                            | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |

| System | 4.2.0 | 4.2.1 | 4.2.2 | 4.2.3 | 4.2.4 | 4.2.5 | 4.2.6 |
| -- | -- | -- | -- | -- | -- | -- | -- |
| CentOS 8                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 7                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 6                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| CentOS 5                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 11                              | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 10                              | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Debian 9                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 32                              | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Fedora 31                              | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Focal                           | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Bionic                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Xenial                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Ubuntu Trusty                          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 2                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Amazon Linux 1                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Oracle Linux 8                         | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| OpenSuse Tumbleweed          | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 6                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 7                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |
| Redhat 8                               | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 | 🟢 |

---

| System | MSI Upgrade | Logs | Alerts |
| -- | -- | -- | -- |
| Windows Server 16 | 🟢 | 🟢 | 🟢 |

---

| WPK | 4.2.6 | 4.3.0 (force) |
| -- | -- | -- |
| Linux | 🟢 | 🟢 |
| Windows | 🔴 | 🔴 |
| Macos | x | 🟢 |

*Windows test marked as failed due to process icon. Upgrade successful
---

Legend:
Not supported: x
Test not launched: ⚫
Test failed: 🔴 
Test success: 🟢 
Need review: 🟡

**Comment by fcaffieri** [comment]
All test in red, will be relauhnched, because of this error:

`org.jenkinsci.plugins.workflow.steps.FlowInterruptedException`

**Comment by rauldpm** [comment]
### Analysis report

<details><summary>Macos wpk</summary>

```

```
</details>

<details><summary>Windows wpk</summary>

In manager:

```
root@ubuntu20:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002 -f /home/vagrant/wazuh_agent_v4.3.0_windows.wpk -x upgrade.bat

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.2.6 -> Wazuh v4.3.0
root@ubuntu20:/home/vagrant# /var/ossec/bin/agent_upgrade -a 002 -f /home/vagrant/wazuh_agent_v4.3.0_windows.wpk -x upgrade.bat -F

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.3.0 -> Wazuh v4.3.0
root@ubuntu20:/home/vagrant#
```

In agent:

Before


![image](https://user-images.githubusercontent.com/14913942/164309267-4edb52bf-4cdd-4552-994f-cbd909cc10c4.png)




After

![image](https://user-images.githubusercontent.com/14913942/164309787-e68c42f9-85c0-4853-ad5d-d8347559cd32.png)
![image](https://user-images.githubusercontent.com/14913942/164309871-542664c1-6144-4bd5-b782-20d9c1cf168b.png)

After force upgrade

![image](https://user-images.githubusercontent.com/14913942/164310389-5606ddac-d4de-4bee-8bd8-fa589c0238f6.png)

Wazuh process icon does not change after upgrade to v4.3.0 

</details>

<details><summary>Linux wpk</summary>

In manager:

```
root@ubuntu20:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ubuntu20 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: centos7, IP: any, Active

List of agentless devices:

root@ubuntu20:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001 -f /home/vagrant/wazuh_agent_v4.3.0_linux_x86_64.wpk -x upgrade.sh

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.2.6 -> Wazuh v4.3.0
root@ubuntu20:/home/vagrant# /var/ossec/bin/agent_upgrade -a 001 -f /home/vagrant/wazuh_agent_v4.3.0_linux_x86_64.wpk -x upgrade.sh -F

Upgrading...

Upgraded agents:
	Agent 001 upgraded: Wazuh v4.3.0 -> Wazuh v4.3.0
root@ubuntu20:/home/vagrant#
```


In agent:

```
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.2.6"
WAZUH_REVISION="40221"
WAZUH_TYPE="agent"
[root@centos7 vagrant]# ps aux | grep ossec
root      8037  0.0  0.1  99320  1540 ?        Sl   19:27   0:00 /var/ossec/bin/wazuh-execd
ossec     8049  6.1  0.4 321004  4352 ?        Sl   19:27   0:06 /var/ossec/bin/wazuh-agentd
root      8063  4.8  0.7 265404  7412 ?        SNl  19:27   0:05 /var/ossec/bin/wazuh-syscheckd
root      8076  0.0  0.2 410680  2164 ?        Sl   19:27   0:00 /var/ossec/bin/wazuh-logcollector
root      8094  2.0  2.0 531744 20576 ?        Sl   19:27   0:02 /var/ossec/bin/wazuh-modulesd
root      8839  0.0  0.0  12528   976 pts/0    S+   19:29   0:00 grep --color=auto ossec
[root@centos7 vagrant]# ps aux | grep ossec
root     11864  0.0  0.1  35380  1460 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-execd
wazuh    11876  1.3  0.2 322568  2876 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-agentd
root     11891  8.3  0.5 266720  5368 ?        SNl  19:29   0:04 /var/ossec/bin/wazuh-syscheckd
root     11905  0.0  0.1 412272  2024 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-logcollector
root     11934  0.8  1.2 664680 12592 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-modulesd
root     12607  0.0  0.0  12528   972 pts/0    S+   19:30   0:00 grep --color=auto ossec
[root@centos7 vagrant]# ps aux | grep wazuh
root     11864  0.0  0.1  35380  1460 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-execd
wazuh    11876  1.2  0.2 322568  2876 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-agentd
root     11891  7.7  0.5 266720  5368 ?        SNl  19:29   0:04 /var/ossec/bin/wazuh-syscheckd
root     11905  0.0  0.1 412272  2024 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-logcollector
root     11934  0.7  1.2 664680 12592 ?        Sl   19:29   0:00 /var/ossec/bin/wazuh-modulesd
root     12609  0.0  0.0  12528   976 pts/0    R+   19:30   0:00 grep --color=auto wazuh
[root@centos7 vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.3.0"
WAZUH_REVISION="40309"
WAZUH_TYPE="agent"
[root@centos7 vagrant]#
(after force upgrade)
[root@centos7 vagrant]# ps aux | grep wazuh
root     13291  0.0  0.1  35380  1460 ?        Sl   19:32   0:00 /var/ossec/bin/wazuh-execd
wazuh    13303  0.7  0.4 322568  4896 ?        Sl   19:32   0:00 /var/ossec/bin/wazuh-agentd
root     13318  8.1  0.5 266736  5348 ?        SNl  19:32   0:04 /var/ossec/bin/wazuh-syscheckd
root     13332  0.0  0.1 412272  2024 ?        Sl   19:32   0:00 /var/ossec/bin/wazuh-logcollector
root     13362  0.6  1.2 664680 12868 ?        Sl   19:32   0:00 /var/ossec/bin/wazuh-modulesd
root     14034  0.0  0.0  12528   976 pts/0    S+   19:33   0:00 grep --color=auto wazuh
[root@centos7 vagrant]#
```



</details>

**Comment by rauldpm** [comment]
### Analysis report - Windows Server 2016 upgrade

<details><summary>Installed and connected v4.2.6</summary>

![image](https://user-images.githubusercontent.com/14913942/164314985-1e3cbd87-161e-4637-b94d-2ebe048b729e.png)
![image](https://user-images.githubusercontent.com/14913942/164315032-1d6e6d36-3a7f-480b-921c-df9bcff81e73.png)

</details>
<details><summary>After running v4.3.0-rc6 msi package (needed to close and open task manager to update icons)</summary>

![image](https://user-images.githubusercontent.com/14913942/164315187-40661edb-4616-4733-86bf-af5655ff94ec.png)
![image](https://user-images.githubusercontent.com/14913942/164315213-3082c4d5-fa2b-4647-bc29-8ded729ecf32.png)

</details>

- No errors found
- Alerts received

<details><summary>Alert</summary>

```
** Alert 1650485718.9030727: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2022 Apr 20 20:15:18 (windows) any->sca
Rule: 19003 (level 5) -> 'SCA summary: Benchmark for Windows audit: Score less than 80% (68)'
{"type":"summary","scan_id":218183719,"name":"Benchmark for Windows audit","policy_id":"sca_win_audit","file":"sca_win_audit.yml","description":"This document provides a way of ensuring the security of the Windows systems.","passed":24,"failed":11,"invalid":36,"total_checks":71,"score":68.571426391601563,"start_time":1650485671,"end_time":1650485671,"hash":"c04f6d88f620baacbbcda6d494aa8985bc8098ba3cf1f8f9bf935469dccd365e","hash_file":"da409ead5682c644e5bf9b99c91fc1c1bbc439126696ed406a7c932bc9d5c499","force_alert":"1","force_alert":"1"}
sca.type: summary
sca.scan_id: 218183719
sca.policy: Benchmark for Windows audit
sca.description: This document provides a way of ensuring the security of the Windows systems.
sca.policy_id: sca_win_audit
sca.passed: 24
sca.failed: 11
sca.invalid: 36
sca.total_checks: 71
sca.score: 68
sca.file: sca_win_audit.yml
```

</details>
