### ISSUE TITLE
elasticsearch systemd unit times out on reboot

### ISSUE THREAD

**Issue by rwjack** [wazuh/wazuh#13168]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.6 | Elasticsearch | Manager | Sources | Debian GNU/Linux 11 (bullseye) |

```
● elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Tue 2022-04-19 10:22:26 CEST; 14min ago
       Docs: https://www.elastic.co
    Process: 473 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exite>
   Main PID: 473 (code=exited, status=143)
        CPU: 12.049s

Apr 19 10:21:12 sec systemd[1]: Starting Elasticsearch...
Apr 19 10:22:26 sec systemd[1]: elasticsearch.service: start operation timed out. Terminating.
Apr 19 10:22:26 sec systemd[1]: elasticsearch.service: Failed with result 'timeout'.
Apr 19 10:22:26 sec systemd[1]: Failed to start Elasticsearch.
Apr 19 10:22:26 sec systemd[1]: elasticsearch.service: Consumed 12.049s CPU time.
lines 1-13/13 (END)
```

This happens on every reboot and I have to manually do `systemctl restart elasticsearch`

How can I troubleshoot this more / is there a potential fix for the systemd unit?

**Comment by LucioDonda** [comment]
Hi @rwjack, thanks for using Wazuh.
I'm guessing that the output you've shared is from the systemctl status. You can also get some more information with
`$ journalctl -xe`
and some extra info on the logs:
`less /var/log/elasticsearch/elasticsearch.log | grep -i 'WARN\|ERROR'`
(or checking it without the WARNING or ERRORS.)

Which configuration are you using? is it a distributed deployment? if this is so, then the **instances.yml** would be also helpful.

On the other hand, have you checked [this](https://documentation.wazuh.com/current/installation-guide/requirements.html#requirements) requirements before installation?

Hope with that info we may find the cause of the problem. 

Regards!

**Comment by rwjack** [comment]
I can't reproduce the `journalctl -xe` logs now, but I found this in `journalctl`:

although this is with my changes to the systemd unit, as you can see it forced additional restarts.
```
Apr 19 12:45:29 sec systemd[1]: elasticsearch.service: start operation timed out. Terminating.
Apr 19 12:45:30 sec kibana[492]: {"type":"log","@timestamp":"2022-04-19T10:45:30Z","tags":["error","elasticsearch","data"],"pid":492,"message":"[ConnectionError]: connect ECONNREFUSED 127.0.0.1:9200"}
Apr 19 12:45:31 sec systemd[1]: elasticsearch.service: Failed with result 'timeout'.
Apr 19 12:45:31 sec systemd[1]: Failed to start Elasticsearch.
Apr 19 12:45:31 sec systemd[1]: elasticsearch.service: Consumed 22.514s CPU time.
Apr 19 12:45:31 sec systemd[1]: Started Opendistro for Elasticsearch Performance Analyzer.
Apr 19 12:45:32 sec systemd[1]: elasticsearch.service: Scheduled restart job, restart counter is at 2.
Apr 19 12:45:32 sec systemd[1]: Stopped Elasticsearch.
Apr 19 12:45:32 sec systemd[1]: elasticsearch.service: Consumed 22.514s CPU time.
Apr 19 12:45:32 sec systemd[1]: Starting Elasticsearch...
Apr 19 12:45:32 sec systemd[1]: Stopping Opendistro for Elasticsearch Performance Analyzer...
Apr 19 12:45:32 sec systemd[1]: opendistro-performance-analyzer.service: Succeeded.
```

As for the log file, apparently it doesn't exist:
```
root in sec in ~ took 9s ❯ less /var/log/elasticsearch/elasticsearch.log | grep -i 'WARN\|ERROR'
/var/log/elasticsearch/elasticsearch.log: No such file or directory
root in sec in ~ ❯ find / -name "elasticsearch.log"
root in sec in ~ took 8s ❯
```
Other than that I'm using the All-In-One deployment, and the minimum requirements have been met.

So far I have added the following 3 lines in `/usr/lib/systemd/system/elasticsearch.service`, which seems to be working for the time being.
```
[Unit]
...
StartLimitIntervalSec=60
StartLimitBurst=2`
...
[Service]
...
Restart=always
...
```

**Comment by LucioDonda** [comment]
Focusing on your specific _elasticsearch_ issue I have found some similar solutions on the web, Changing [timeoutStartSec](https://www.codestudyblog.com/cs2112bgc/1222141827.html) and [here ](https://sleeplessbeastie.eu/2020/02/29/how-to-prevent-systemd-service-start-operation-from-timing-out/) the same, all avoiding restarting, but I guess is not that different from you approach.
The thing that makes me think is not having any elasticsearch.logs, does that folder has any content? 
After the installation, did you check the output of 
`curl -XGET https://localhost:9200 -u admin:admin -k` as stated [here](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html#certificates-creation) ?
can you share with us `/etc/elasticsearch/elasticsearch.yml` the `ossec.conf` and maybe also some `ossec.logs` ?
perhaps we could find some strange configuration/behavior that it's causing that time out.
Thanks in advance!

**Comment by rwjack** [comment]
> The thing that makes me think is not having any elasticsearch.logs, does that folder has any content?

Yeah, it has a bunch of gc.log, wazuh-cluster log files, and they all seem up to date.

>did you check the output of
curl -XGET https://localhost:9200 -u admin:admin -k as stated [here](https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html#certificates-creation) ?

Actually I don't remember doing that, although I just did it with the user:pass combo I use to login into the wazuh web UI and got the expected output:
```
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "xxx",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "xxx",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

Although I don't remember setting the JAVA_HOME variable either, and it actually isn't set up. Could this be an issue?

Here's the other files you asked for:
`elasticsearch.yml`:
```
network.host: 0.0.0.0
node.name: node-1
cluster.initial_master_nodes:
        - node-1
#        - node-2
#        - node-3
# discovery.seed_hosts:
#         - <elasticsearch_ip_node1>
#         - <elasticsearch_ip_node2>
#         - <elasticsearch_ip_node3>

cluster.name: wazuh-cluster

opendistro_security.ssl.transport.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch.pem
opendistro_security.ssl.transport.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.transport.resolve_hostname: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: /etc/elasticsearch/certs/elasticsearch.pem
opendistro_security.ssl.http.pemkey_filepath: /etc/elasticsearch/certs/elasticsearch-key.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: /etc/elasticsearch/certs/root-ca.pem
opendistro_security.nodes_dn:
- CN=node-1,OU=Docu,O=Wazuh,L=California,C=US
# - CN=node-2,OU=Docu,O=Wazuh,L=California,C=US
# - CN=node-3,OU=Docu,O=Wazuh,L=California,C=US
opendistro_security.authcz.admin_dn:
- CN=admin,OU=Docu,O=Wazuh,L=California,C=US

opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
node.max_local_storage_nodes: 3

path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
```

As for ossec.conf - It hasn't been changed at all from the vanilla configuration, and as for ossec.log - I only found one in `/var/ossec/logs/ossec.log` but it contains only information from today (nothing important), not sure where to find the archive you're looking for.

**Comment by LucioDonda** [comment]
Hi @rwjack 
another way of getting the logs from systems error for a respective app could be running :
`$ journalctl _SYSTEMD_UNIT=elasticsearch.service`
especially if you manage to do it right after the restart of the service.

When I ask for logs at least inside the directory is in order to find any error (maybe you could find them inside of a .gz file)
but the weird thing is that, as you can see in the configuration file, your` path.logs` it's correctly defined. Searching in [ES discuss](https://discuss.elastic.co/t/cant-find-my-es-logs/14017/2) I find that it could be a permission issue, and that could be causing the service start issue.

Besides that I must say that if your problem can be tackled with that modification in `/usr/lib/systemd/system/elasticsearch.service` it shouldn't be directly related to wazuh and there isn't much more help I could bring you from my side.

Let me know if you found anything else I could help you with.

Have a great day!

**Comment by rwjack** [comment]
> Besides that I must say that if your problem can be tackled with that modification in /usr/lib/systemd/system/elasticsearch.service it shouldn't be directly related to wazuh and there isn't much more help I could bring you from my side.

Now that I think of it you seem to be right, it might not be a wazuh issue since elasticsearch was installed from apt, and wasn't let's say a pre-packed wazuh docker image.

Thank you for your time and advice nevertheless! :)
