### ISSUE TITLE
Config on demand continuing remaining features 

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1318]
This issue continues the missing features:

- [x]  Request information about **ruleset**
- [x]  Request information about **cluster**
- [x]  API call to retrieve all the configuration from an agent/manager at the same time (**not needed**)
- [x]  Request information about **osquery**

**Comment by TJOSERAFAEL** [comment]
This branch https://github.com/wazuh/wazuh/tree/dev-37-query-config-continuation continues the development

**Comment by vikman90** [comment]
Related issue: https://github.com/wazuh/wazuh/issues/941

**Comment by druizz90** [comment]
Hi team,

You can see below a table with the status of the API calls:

Type | Component | Configuration | Tag | Status
------------ | ------------- | ------------- | ------------- | ------------- |
agent | agent | client | `<client>` | OK
agent | agent | buffer | `<client_buffer>` | OK
agent | agent | labels | `<labels>` | OK
agent | agent | internal | agent, monitord, remoted | OK
?? | agentless | agentless | `<agentless>` | KO
manager | analysis | global | `<global>` | OK
manager | analysis | active_response | `<active-response>` | OK
manager | analysis | alerts | `<alerts>` | OK
manager | analysis | command | `<command>` | OK
manager | analysis | rules | `<rule>` | OK
manager | analysis | decoders | `<decoder>` | OK
manager | analysis | internal | analysisd | OK
?? | auth | auth | `<auth>` | KO
agent | com | active-response | `<active-response>` | OK
agent | com | internal | execd | OK
?? | csyslog | csyslog | `<csyslog_output>` | KO
?? | integrator | integration | `<integration>` | KO
agent | logcollector | localfile | `<localfile>` | OK
agent | logcollector | socket | `<socket>` | OK
agent | logcollector | internal | logcollector | OK
agent | mail | global | `<global><email...>` | OK
agent | mail | alerts | `<email_alerts>` | OK
agent | mail | internal | maild | OK
manager | monitor | internal | monitord | OK
manager | request | remote | `<remote>` | OK
manager | request | internal | remoted | OK
agent | syscheck | syscheck | `<syscheck>` | OK
agent | syscheck | rootcheck | `<rootcheck>` | OK
agent | syscheck | internal | syscheck, rootcheck | OK
agent | wmodules | wmodules | `<wodle>` | OK

I hope that all works fine as soon as possible.

Best regards,

Demetrio.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/issues/1318 solves the issue
