### ISSUE TITLE
Implement a mechanism to balance agents' TCP sessions in a clustered environment

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#13195]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Clusterd | Manager | Any | Linux |

### Description

The main purpose of this issue is to provide a new capability to automatically balance the agents' TCP sessions inside a Wazuh cluster.

Using the recently developed reconnect feature for agents, the current development should ensure that the agents' connections are properly balanced inside a Wazuh cluster. This helps to ensure smooth behavior and performance when deploying a large Wazuh clustered environment with thousands of agents connected to it.

This development presumes the Wazuh agents are connected to the Wazuh cluster through a layer 4 (TCP/UDP) load balancer using the `least connections` algorithm.

### Requirements

- Must be configurable in ossec.conf.
- Must be able to use the same set of filters as other agent-related features such as wpk upgrade, restart, delete, etc.
- The balancing algorithm must be robust, ensuring the correct behavior of the agents.
- An agent reconnection must ensure a connection to a different node.
- The specific agents to reconnect must be configurable in the algorithm.
- Failover mechanism against reconnecting failures, stop balancing if it occurs.
- Must ensure the agents reconnect to the worker node with the least current load, stop balancing otherwise.
- The reconnecting time intervals and strategy must ensure a smooth transition of agents between nodes.

### Development

The algorithm should be developed as a new task for Wazuh clusterd in the master node. It should use distributed reconnect calls using framework SDK to select the specific agents to reconnect from the different nodes.

### Testing

Proper unit, integration, and system tests must be designed and implemented for the current development to guarantee product quality and performance.

### Documentation

All new configuration options must be properly documented. The algorithm, together with any new commands and tasks should be added to cluster development documentation.

----

**WORKING BRANCH:** [feature/13195-cluster-agents-reconnect](https://github.com/wazuh/wazuh/tree/feature/13195-cluster-agents-reconnect)

**Comment by AdriiiPRodri** [comment]
## Status update

We have modified the output of the above procedure to the reconnection algorithm. Now the output of the balance check procedure is:
```
{
  'worker2': 
    {
      'agents': ['008', '007', '006'], 'total': 8
    }, 
  'worker1': 
    {
      'agents': [], 'total': 1
    }
}
```

In this case, this environment had 9 agents of which 1 was in the node 'worker1' and the other 8 in the node 'worker2' so the average number of agents per node is 5 (truncated), therefore we send the agents that exceed this average.

In addition, we have added a generic exception control mechanism that allows us to skip the phases where the error occurs:
```
022/07/13 05:22:38 DEBUG: [Master] [Agents reconnect] Current detected nodes: {'master-node', 'worker2'}.
2022/07/13 05:22:38 INFO: [Master] [Agents reconnect] Cluster is ready 3/3. Nodes stability phase finished at 2022-07-13T11:22:38.970073Z.
2022/07/13 05:22:38 ERROR: [Master] [Agents reconnect] Error in get_reconnected_agents: Error 1701 - Agent does not exist
2022/07/13 05:22:38 DEBUG: [Master] [Agents reconnect] Reset all counters.
2022/07/13 05:22:38 INFO: [Master] [Agents reconnect] Skipping current iteration.
2022/07/13 05:22:38 INFO: [Master] [Agents reconnect] Iteration complete. Sleep during 60 seconds.
2022/07/13 05:23:38 DEBUG: [Master] [Agents reconnect] Current detected nodes: {'master-node', 'worker2'}.
2022/07/13 05:23:38 INFO: [Master] [Agents reconnect] Nodes are not stable at this moment. Counter: 1/3.
2022/07/13 05:24:08 DEBUG: [Master] [Agents reconnect] Current detected nodes: {'master-node', 'worker2'}.
2022/07/13 05:24:08 INFO: [Master] [Agents reconnect] Nodes are not stable at this moment. Counter: 2/3.
2022/07/13 05:24:38 DEBUG: [Master] [Agents reconnect] Current detected nodes: {'master-node', 'worker2'}.
2022/07/13 05:24:38 INFO: [Master] [Agents reconnect] Cluster is ready 3/3. Nodes stability phase finished at 2022-07-13T11:24:38.981188Z.
2022/07/13 05:24:38 ERROR: [Master] [Agents reconnect] Error in get_reconnected_agents: Error 1701 - Agent does not exist
2022/07/13 05:24:38 DEBUG: [Master] [Agents reconnect] Reset all counters.
2022/07/13 05:24:38 INFO: [Master] [Agents reconnect] Skipping current iteration.
2022/07/13 05:24:38 INFO: [Master] [Agents reconnect] Iteration complete. Sleep during 60 seconds.
```

**Comment by Selutario** [comment]
This approach was discarded.
