### ISSUE TITLE
Wazzuh manager never receive connection when client as the same hostname

### ISSUE THREAD

**Issue by s23hck** [wazuh/wazuh#13218]
Hi, i installed agent on a debian11 host wich have same hostname as the wazuh manager.

On Wazuh manager, i never receive the connection from the agent.

Wazuh manager hostanme : debian
Wazuh agent hostname : debian

After installation, if i change the hostname on the agent side, the manager display and receive connection from agent.

Tested on latest debian11 stable.

Cheers

**Comment by LucioDonda** [comment]
Hi @s23hck , thanks for using wazuh.
The agent shouldn't match an already enrolled agent name (in this case the manager is treated as one and actually behaves like one). We encourage you to change it as defined [here](https://documentation.wazuh.com/current/user-manual/agent-enrollment/troubleshooting.html#invalid-agent-name-for-enrollment)
As shown there, you may find the same logs on your agent. 
Are you having any problem using another name? After that name change, were you able to use it as intended? 
If there's any other way we can help do not hesitate to reach us again.
Have a great day!

**Comment by s23hck** [comment]
Hi @LucioDonda,
Thanks for reply.
Thanks for this amazing wazuh project :)
I have no problem when changing the hostname, everything seem's fine.

have a great day too !
