### ISSUE TITLE
Vuln-detector - Debian 11 Bullseye compatibility

### ISSUE THREAD

**Issue by s23hck** [wazuh/wazuh#13217]
Hi, according to the documentation page [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html ), the file **agent.conf** inside` /var/ossec/etc/shared/group_name` can't accept the bullseye value: 
Precision:
The `<os>` value inside the `<provider name>` can't accept latest stable debian 11 bullseye.
When do you think it will be possible to add this latest release ?
Cheers

**Comment by MiguelazoDS** [comment]
Hi @s23hck, 

The changes for Bullseye support in the vulnerability detector were implemented as part of this issue https://github.com/wazuh/wazuh/issues/10180 and will be targeted for 4.3

As mentioned in the issue the configuration block to configure this Debian flavor is the following 

```xml
<!-- Debian OS vulnerabilities -->  
<provider name="debian">
   <enabled>no</enabled>
   <os>bullseye</os>
   <update_interval>1h</update_interval>
</provider>
```

Currently, we are in the RC6 but I'm afraid I don't have the information on when Wazuh 4.3 will be released. 

Regards!

**Comment by s23hck** [comment]
Hi @MiguelazoDS,

Thanks for your reply ! 
I passed by the issue you mentioned [#10180](https://github.com/wazuh/wazuh/issues/10180). 
I will be patient and hope the Wazuh 4.3 release will be arrive soon :)

Regards!
