### ISSUE TITLE
Release 4.3.0 - Manual tests - Deployment with Puppet

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13225]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |  Deployment with Puppet |
| **Category**            | Installation  |
| **Deployment option**   | Deployment with Puppet |
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/10954 |
| **Release candidate #** | RC6 |

## Installation procedure
Installation alternatives - Deployment with Puppet

## Test description
Test distributed deployment with Wazuh manager cluster and Wazuh indexer cluster via Puppet.
Test deployment of agent via Puppet.

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :yellow_circle:  | [0. Environment information](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1108499632) | documentation | It might be useful to add an example of how `/etc/hosts` should look like in order to work locally or for non-production setups. https://github.com/wazuh/wazuh-documentation/issues/5126|
| :yellow_circle:  | [2. Installing Puppet agent](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1108529815) | documentation | `Configuration` section is currently a subsection of _Installation on Windows_ although it is required for any OS installation. https://github.com/wazuh/wazuh-documentation/issues/5126|
| :red_circle:   | [3. PuppetDB installation (Optional)](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1108547924) | documentation | PostgreSQL 11.0 should be used instead of 9.4. Already reported in https://github.com/wazuh/wazuh-documentation/issues/4997 |
| :red_circle:   | [4. Setting up Puppet certificates](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1108555175) | documentation | Multiple problems while listing certificates. Using super user is required for it to work, but it is not mentioned in our documentation. https://github.com/wazuh/wazuh-documentation/issues/5126|
| :red_circle:   | [5.1. Install Wazuh module](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1109746061) | documentation | The Wazuh puppet module is not installed where the documentation says, which leads to multiple errors in the deployment.  https://github.com/wazuh/wazuh-documentation/issues/5127 |
| :red_circle:   | [5.2. Install manager via Puppet](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1109746061) | documentation | Active response error in the `wazuh-manager.pp` manifest. Already reported in https://github.com/wazuh/wazuh-documentation/issues/4997  |
| :red_circle:   | [5.2./5.3. Install manager/agent via Puppet](https://github.com/wazuh/wazuh/issues/13225#issuecomment-1109746061) | documentation | `Puppet agent` command must be run with sudo in order to install Manager/agent. Otherwise, `Permission denied` error is raised. https://github.com/wazuh/wazuh-documentation/issues/5128 |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @okynos

**Comment by Selutario** [comment]
# 0. Environment information

Two virtualbox machines used, one for Puppet master and one for puppet agent.

#### Puppet master
- **Disk space:** 20 GB
- **RAM:** 3 GB
- **SO:** Ubuntu 20.04

#### Puppet agent
- **Disk space:** 20 GB
- **RAM:** 2 GB
- **SO:** Ubuntu 20.04

**Comment by Selutario** [comment]
# :yellow_circle: 1. Installing Puppet master
## :green_circle: 1.1 Installation on Debian/Ubuntu
Installation was ok.

## :green_circle: 1.2 Memory Allocation
Configured to use 512 MB. Instrucctions easy to follow.

## :yellow_circle: 1.3 Configuration
Not really sure about what should I write for a local/testing setup according to this part of the documentation:
![image](https://user-images.githubusercontent.com/23361101/165088431-5580a7c5-999c-44c2-83f6-38d20752ca00.png)

However, there are [mentions of local Puppet setups in the Memory Allocation section](https://documentation.wazuh.com/current/deploying-with-puppet/setup-puppet/install-puppet-master.html#memory-allocation):

> if you want to experiment with Puppet Server on a VM, you can safely allocate as little as 512MB of memory.

This is the content of my `/etc/puppetlabs/puppet/puppet.conf` file so far:
```
[server]
vardir = /opt/puppetlabs/server/data/puppetserver
logdir = /var/log/puppetlabs/puppetserver
rundir = /var/run/puppetlabs/puppetserver
pidfile = /var/run/puppetlabs/puppetserver/puppetserver.pid
codedir = /etc/puppetlabs/code

[main]
dns_alt_names = puppet,localhost   
```

The Puppet server was started correctly:
![image](https://user-images.githubusercontent.com/23361101/165090138-158d86de-652f-4013-8aa4-053cb6bab1d8.png)

**Comment by Selutario** [comment]
# :green_circle: 2. Installing Puppet agent
## :green_circle: 2.1 Installation on Debian/Ubuntu
I followed the steps mentioned in the documentation and no errors occured. 

However, I don't know if the installation is working properly since there is no mention of commands or any other way to check it (in this section of the documentation).

**Comment by Selutario** [comment]
# :red_circle: 4. Setting up Puppet certificates
## :red_circle: 4.1. Step one
![image](https://user-images.githubusercontent.com/23361101/165095778-99aa067a-8daa-46ac-b9a8-4feb127b6203.png)

I get this error when running the above command in the puppet agent:
```
Error: Connection to https://puppet:8140/puppet-ca/v1 failed, trying next route: Request to https://puppet:8140/puppet-ca/v1 failed after 0.008 seconds: Failed to open TCP connection to puppet:8140 (getaddrinfo: Temporary failure in name resolution)
Wrapped exception:
Failed to open TCP connection to puppet:8140 (getaddrinfo: Temporary failure in name resolution)
Error: No more routes to ca
Error: Could not run: No more routes to ca
```

## :red_circle: 4.2. Step two
![image](https://user-images.githubusercontent.com/23361101/165095946-81915d31-2f58-4a24-aa0a-fe2bd51ec8dc.png)

I get this error when running the above command in the puppet server:
```
Traceback (most recent call last):
	9: from /opt/puppetlabs/server/apps/puppetserver/cli/apps/ca:5:in `<main>'
	8: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/cli.rb:100:in `run'
	7: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:103:in `run'
	6: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:226:in `get_certs_or_csrs'
	5: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/action/list.rb:226:in `new'
	4: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/certificate_authority.rb:26:in `initialize'
	3: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/certificate_authority.rb:26:in `new'
	2: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:25:in `initialize'
	1: from /opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:156:in `make_store'
/opt/puppetlabs/puppet/lib/ruby/vendor_gems/gems/puppetserver-ca-2.3.6/lib/puppetserver/ca/utils/http_client.rb:156:in `add_file': system lib (OpenSSL::X509::StoreError)
```

**IN PROGRESS**

**Comment by Selutario** [comment]
# :red_circle: 5. Wazuh Puppet module
## :green_circle:  5.1. Install Wazuh module
Wazuh module installation was successful:
```
wget https://github.com/wazuh/wazuh-puppet/tarball/v4.3.0
```
![image](https://user-images.githubusercontent.com/23361101/165290858-163a9fdd-3310-4025-948b-a4ce6d38938d.png)

## :red_circle: 5.2. Install manager via Puppet
I created the file `/etc/puppetlabs/code/environments/production/manifests/wazuh-manager.pp` with this content in the puppet master:
```
node "puppetclient.home" {
  class { 'wazuh::manager':
    ossec_smtp_server => 'localhost',
    ossec_emailto => ['user@mycompany.com'],
  }

  wazuh::command { 'firewallblock':
    command_name       => 'firewall-drop',
    command_executable => 'firewall-drop'
  }

  wazuh::activeresponse { 'blockWebattack':
      command_name => 'firewall-drop',
      ar_level     => 9,
      ar_agent_id  => 123,
      ar_rules_id  => [31153,31151],
      ar_repeated_offenders => '30,60,120'
  }

  wazuh::addlog { 'monitorLogFile':
    logfile => '/var/log/secure',
    logtype => 'syslog'
  }
}
```

But this error is shown in the Puppet agent when running `puppet agent -t`:
![image](https://user-images.githubusercontent.com/23361101/165300667-9848a140-7f5f-4c8a-a326-16b43b19459a.png)

According to the Wazuh documentation, the Wazuh puppet module should have been installed on `/etc/puppetlabs/code/environments/production/modules/`. However, when I installed it, the path where it was placed was `~/.puppetlabs/etc/code/modules/wazuh`, which could be related with the error.

**Comment by teddytpc1** [comment]
## 5.1. Install Wazuh module
I have tested it and the module is installed in `/etc/puppetlabs/code/environments/production/modules`:
```
/etc/puppetlabs/code/environments/production/modules
└── wazuh-wazuh (v4.3.0)
```

**Comment by teddytpc1** [comment]
## 5.2. Install manager via Puppet

>I created the file /etc/puppetlabs/code/environments/production/manifests/wazuh-manager.pp with this content in the puppet master:

This manifest is outdated. The new manifest is in the updated documentation:
```
Create a stack.pp file at /etc/puppetlabs/code/environments/production/manifests/ and put the contents below. puppet-agent-node refers to the hostname or IP of the puppet agent:
node "puppet-agent-node" {
 class { 'wazuh::manager':
 }
 class { 'wazuh::indexer':
 }
 class { 'wazuh::filebeat_oss':
 }
 class { 'wazuh::dashboard':
 }
}
```

> I then run the puppet agent with sudo, but there were another error (E: Version '4.3.0-1' for 'wazuh-manager' was not found):

As Wazuh 4.3.0 is not released yet you will have to update the repositories variables to point to `packages-dev` instead of `packages`.

## 5.3. Install agent via Puppet

Same comments as in `5.2`.

**Comment by teddytpc1** [comment]
## 4.1. Step one
I have added the following `note` to the documentation:
`NOTE: the Puppet Servers’s FQDN should be resolved by the Puppet agent host.`

## 4.2 Step two
I was not able to configure the Puppet environment following the updated documentation.
