### ISSUE TITLE
Occasionally the MSU generator web scraping fails without collecting any Catalog hotfixes

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#13254]
## Description 
It has been detected that in the MSU generation, when web scraping to obtain all the patches that **_replace_** or **_are replaced by_** an update, it occasionally fails, because it cannot obtain the HTML content of the page with the details of the update.

The problem happened when trying to get the content of any page (via a _GET request_ in the script) with the following format:
`https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=_{id}_`

Such as: https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=ba19a6be-55eb-4b25-9881-521c17e75f44

So that when making this GET request, the server would return the content of an error page (like this: [link](https://www.catalog.update.microsoft.com/Error.aspx?id=-1914896368)), instead of the requested page, causing that none of the supersedences could be obtained (affecting especially the most recent updates, since there is no access and therefore cannot know whose supersedence the patch is), causing false positives on Windows that are updated.

### Example of the event on 27/04/2022

In this case, you can see how not being able to collect the Catalog information in the MSU generation during that week and the following week (from 21/04 to 05/05), caused the following incident where false positives appeared:

It appears that there are older cumulative patches that do not relate to the latest cumulative patch that is in effect, because the page containing that information in the Catalog cannot be accessed via a GET request. 
 
An example of a patch affected by this issue is the following: [KB4041691](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4041691).

This patch has all supersedences except the `KB5012596` supersedence, which is the latest one released by Microsoft. And next to the following link, you can see how `KB5012596` is superseded by `KB4041691`, but is not being picked up correctly:
https://www.catalog.update.microsoft.com/Search.aspx?q=KB5012596

To test without having to use any script, I tried running the following command (which performs the same request), getting the same result as in the script, i.e., a redirect to the Error page and getting the contents of this Error page (https://www.catalog.update.microsoft.com/Error.aspx?id=-1914896368):
```bash
wget -q -O- https://www.catalog.update.microsoft.com/ScopedViewInline.aspx\?updateid\=ba19a6be-55eb-4b25-9881-521c17e75f44
```

This actually happens with all the links in the Catalog, but as we have a merged-msu together with a recursion between the cumulative patches, then we preserve the relation between the internal list of patches and the MSU is not empty.
An example is the patch before `KB5012596` -> `KB5011495` ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5011495)), we can see how with the data we had, it has been detected correctly, and it is supersedence of `KB4041691`.

MSU:
```json
          "KB4041691": [
          ...
               "KB5011495",
          ...
          ]
          "KB5011495": [
               "KB5012596",
          ],
```
> KB5012596 is not yet collected (only as supersedence) in the MSU because it is the latest patch available.

![KB5012596](https://user-images.githubusercontent.com/37207742/165567439-02861a41-5aee-4a3f-8a48-cf92db27a7cf.png)

**Comment by chemamartinez** [comment]
Finally, after some research to find alternatives, Microsoft solved the problem on their side.
