### ISSUE TITLE
Release 4.3.0 - Manual tests - Elastic Stack Installation

### ISSUE THREAD

**Issue by noxit0** [wazuh/wazuh#13258]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |  Elastic Stack Installation                                          |
| **Category**            | Installation                                           |
| **Deployment option**   |    Elastic Stack                                        |
| **Main release issue**  |     https://github.com/wazuh/wazuh/issues/10954                                       |
| **Release candidate #** |   RC6                                         |

## Test description
Try latest version of Elastic Stack supported by our interface (Kibana plugin).

- Check that documentaiton steps work as intended.
- Check the WUI for any error or incorrect data
- Check that creation of new rules from the WUI works correctly
- Check that configuration of the manager from the WUI works correctly
- Check that the configuration/assignment of agent groups from the WUI works correctly

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|    :green_circle:            |  [Documentation steps work as intended](https://github.com/wazuh/wazuh/issues/13258#issuecomment-1111591895)        |                     |                |
|    :green_circle:            |  [Creation of New Rules](https://github.com/wazuh/wazuh/issues/13258#issuecomment-1112715801)        |                     |                |
|    :green_circle:            | [Manager configuration ](https://github.com/wazuh/wazuh/issues/13258#issuecomment-1112719279)       |                     |                |
|    :green_circle:            | [Configuration/assignment of agent groups  ](https://github.com/wazuh/wazuh/issues/13258#issuecomment-1112727418)     |                     |                |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @gdiazlo

**Comment by f-galland** [comment]
![DeepinScreenshot_20220427205943](https://user-images.githubusercontent.com/99492720/165650152-26ec43b7-897e-4872-97d9-6facde7f852b.png)


In order to download the wazuh plugin for kibana, I had to use the following URL:

https://packages-dev.wazuh.com/pre-release/ui/kibana/wazuh_kibana-4.3.0_7.17.0-1.zip

Also, the repository for the pre-release version I had to use was:

```
deb https://packages-dev.wazuh.com/pre-release/apt unstable main
```

**Comment by noxit0** [comment]
# Creation of New Rules

<details>

![Rules](https://user-images.githubusercontent.com/67434222/165858625-569427c4-b7b5-44dd-ae4a-8d42a0d08299.png)


</details
![Screenshot_1](https://user-images.githubusercontent.com/67434222/165858772-9d4a4952-3290-4408-9ef7-277243e7d25c.png)
>

**Comment by noxit0** [comment]
# Manager configuration

<details>

![ossec1](https://user-images.githubusercontent.com/67434222/165859271-1c7958a7-7f76-43ce-8a69-3a853799c28f.png)

![ossec2](https://user-images.githubusercontent.com/67434222/165859279-490ae38f-ed2b-4cc4-9812-a4285e3ba1f4.png)

![ossec3](https://user-images.githubusercontent.com/67434222/165859288-8ab17470-b9c8-4bac-ba6c-b3c4b40ac580.png)


</details>

**Comment by noxit0** [comment]
# Configuration/assignment of agent groups

<details>

![agent](https://user-images.githubusercontent.com/67434222/165860784-8c3a32bb-0eb4-4dcd-a50a-97ae37df6835.png)


![agents2](https://user-images.githubusercontent.com/67434222/165860810-ea822013-049f-43a0-8c26-ee60423ba806.png)


![agent3](https://user-images.githubusercontent.com/67434222/165860826-2290f60a-02ab-4992-8e7e-bb4d4e515920.png)



![agent4](https://user-images.githubusercontent.com/67434222/165860836-460b31d5-5f76-4627-909a-aaeb5ef3afb4.png)


</details>

**Comment by gdiazlo** [comment]
Everything worked as expected. We had some issues while saving the configuration for the first time reported here https://github.com/wazuh/wazuh-kibana-app/issues/4071 in other environments. But as we can see, on a default installation does not happen.
