### ISSUE TITLE
Update MITRE ATT&CK database to ATT&CK v11  

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#13277]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3 | MITRE | Improve |

Update current MITRE ATT&CK v9 database to[ ATT&CK v11.](https://attack.mitre.org/resources/updates/updates-april-2022/) 

[MITRE ATT&CK JSON data ](https://github.com/mitre/cti/releases/tag/ATT%26CK-v11.0)

Tasks
- [ ] Update Wazuh MITRE ATT&CK database. 
- [ ] Update deprecated Techniques in current ruleset.
- [ ] Update changelog.

Tests
- [ ] Test Ruleset works and there are no deprecated techniques.
- [ ] Test demo custom Ruleset and there are no deprecated techniques.  
- [ ] Test Wazuh API works. 
- [ ] Test Wazuh Dashboard works.

**Comment by 00willo** [comment]
Possibly close by https://github.com/wazuh/wazuh/pull/13622

**Comment by 00willo** [comment]
Also, with v12 out as of October this issue is also probably invalidated by https://github.com/wazuh/wazuh/issues/15235.

Bearing in mind that ATT&CK v13 is due to drop in around 30days.

**Comment by 72nomada** [comment]
Hi, @00willo  yes, you are right, 4.5.0 will have v13.
