### ISSUE TITLE
Improve MITRE Technique Id mapping in some rules

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#13270]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3.0 | Rules | Improve |

## Description

Some rules that were missing MITRE technique id were identified. Please Improve the rules by adding correct MITRE TID

### Rules

- 5760: sshd: authentication failed.
- 5503: PAM: User login failed.
- 5557: password check failed
- 5710: sshd: Attempt to login using a non-existent user
- 60122: Logon failure - Unknown user or bad password

Rule id | Description | New MITRE T ID
-- | -- | --
5760 | sshd: authentication failed. | T1021.004, T1110.01
5503 | PAM: User login failed. | T1110.01
5557 | password check failed | T1110.01
5710 | sshd: Attempt to login using a non-existent user | T1078,  T1021.004
60122 | Logon failure - Unknown user or bad password | T1078, T1531

**Comment by 72nomada** [comment]
done
