### ISSUE TITLE
Custom rules does not fire an alert for EventChannel

### ISSUE THREAD

**Issue by bbkrr** [wazuh/wazuh#13281]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Server | Manager | Sources | Ubuntu 20.04 |

I am using a custom decoder and rule to capture EventChannel or any log with level 0 as an alert with level 1. Right now I am only able to capture file logs as an alert which uses my custom decoder and rule, but I am not able to capture EventChannel logs with level 0 with the same decoder and rules.

My custom decoder, rules and logs are given below. As you can see, if I use wazuh-logtest then for the same log my custom decoder and rule are used and an alert is generated. So, if the same log is generating an alert using wazuh-logtest and my custom decoder and rules I was hoping to get the same in my alert files.

Custom decoder/rule for EventChannel

Decoders

```
<decoder name="allow_all">
  <parent>allow_all</parent>
  <regex type="pcre2">(?i)(.*)(EventChannel)(.*)</regex>
  <order>data,action,extra_data</order>
</decoder>
```

Rules

```
<group name="custom_event_channel,">
  <rule id="101010" level="1">
    <regex type="pcre2">.*</regex>
    <description>ALlow all logs not caught by inbuilt rules</description>
  </rule>
</group>
```

Log of EventChannel

```
2022 Apr 26 10:08:48 (windows) 10.10.1.1->EventChannel {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4658","version":"0","level":"0","task":"12800","opcode":"0","keywords":"0x8020000000000000","systemTime":"2022-04-26T17:08:46.910726900Z","eventRecordID":"122143","processID":"4","threadID":"3628","channel":"Security","computer":"windows","severityValue":"AUDIT_SUCCESS","message":"\"The handle to an object was closed.\r\n\r\nSubject :\r\n\tSecurity ID:\t\tS-1-5-21-583709415-4138634449-979950088-500\r\n\tAccount Name:\t\tAdministrator\r\n\tAccount Domain:\t\tWINDOWS\r\n\tLogon ID:\t\t0x6DE48\r\n\r\nObject:\r\n\tObject Server:\t\tSecurity\r\n\tHandle ID:\t\t0x1304\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x10bc\r\n\tProcess Name:\t\tC:\\Windows\\explorer.exe\""},"eventdata":{"subjectUserSid":"S-1-5-21-583709415-4138634449-979950088-500","subjectUserName":"Administrator","subjectDomainName":"WINDOWS","subjectLogonId":"0x6de48","objectServer":"Security","handleId":"0x1304","processId":"0x10bc","processName":"C:\\\\Windows\\\\explorer.exe"}}}
```

Result of wazuh-logtest

```
**Phase 1: Completed pre-decoding.
full event: '2022 Apr 26 10:08:48 (windows) 10.10.1.1->EventChannel {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4658","version":"0","level":"0","task":"12800","opcode":"0","keywords":"0x8020000000000000","systemTime":"2022-04-26T17:08:46.910726900Z","eventRecordID":"122143","processID":"4","threadID":"3628","channel":"Security","computer":"windows","severityValue":"AUDIT_SUCCESS","message":"\"The handle to an object was closed.\r\n\r\nSubject :\r\n\tSecurity ID:\t\tS-1-5-21-583709415-4138634449-979950088-500\r\n\tAccount Name:\t\tAdministrator\r\n\tAccount Domain:\t\tWINDOWS\r\n\tLogon ID:\t\t0x6DE48\r\n\r\nObject:\r\n\tObject Server:\t\tSecurity\r\n\tHandle ID:\t\t0x1304\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x10bc\r\n\tProcess Name:\t\tC:\\Windows\\explorer.exe\""},"eventdata":{"subjectUserSid":"S-1-5-21-583709415-4138634449-979950088-500","subjectUserName":"Administrator","subjectDomainName":"WINDOWS","subjectLogonId":"0x6de48","objectServer":"Security","handleId":"0x1304","processId":"0x10bc","processName":"C:\\\\Windows\\\\explorer.exe"}}}'
timestamp: '2022 Apr 26 10:08:48'

**Phase 2: Completed decoding.
name: 'allow_all'
action: 'EventChannel'
data: '10.10.1.1->'
extra_data: ' {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4658","version":"0","level":"0","task":"12800","opcode":"0","keywords":"0x8020000000000000","systemTime":"2022-04-26T17:08:46.910726900Z","eventRecordID":"122143","processID":"4","threadID":"3628","channel":"Security","computer":"windows","severityValue":"AUDIT_SUCCESS","message":"\"The handle to an object was closed.\r\n\r\nSubject :\r\n\tSecurity ID:\t\tS-1-5-21-583709415-4138634449-979950088-500\r\n\tAccount Name:\t\tAdministrator\r\n\tAccount Domain:\t\tWINDOWS\r\n\tLogon ID:\t\t0x6DE48\r\n\r\nObject:\r\n\tObject Server:\t\tSecurity\r\n\tHandle ID:\t\t0x1304\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x10bc\r\n\tProcess Name:\t\tC:\\Windows\\explorer.exe\""},"eventdata":{"subjectUserSid":"S-1-5-21-583709415-4138634449-979950088-500","subjectUserName":"Administrator","subjectDomainName":"WINDOWS","subjectLogonId":"0x6de48","objectServer":"Security","handleId":"0x1304","processId":"0x10bc","processName":"C:\\\\Windows\\\\explorer.exe"}}}'

**Phase 3: Completed filtering (rules).
id: '101010'
level: '1'
description: 'ALlow all logs not caught by inbuilt rules'
groups: '['custom_event_channel']'
firedtimes: '3'
mail: 'False'
**Alert to be generated.
```

Log of a File

`2022 Apr 26 10:19:18 (windows) 10.10.1.1->\Users\Administrator\Documents\test.txt Test3`

Result of wazuh-logtest

```
**Phase 1: Completed pre-decoding.
full event: '2022 Apr 26 10:19:18 (windows) 10.10.1.1->\Users\Administrator\Documents\test.txt Test3'
timestamp: '2022 Apr 26 10:19:18'

**Phase 2: Completed decoding.
name: 'allow_all'

**Phase 3: Completed filtering (rules).
id: '101010'
level: '1'
description: 'ALlow all logs not caught by inbuilt rules'
groups: '['custom_event_channel']'
firedtimes: '1'
mail: 'False'
**Alert to be generated.
```

I have also followed the solution mentioned in the [wazuh-group-channel](https://groups.google.com/g/wazuh/c/qd4E6X0i0CM), but I am not getting any feedbacks after some time.

Is there a way to prioritize my custom rule to get the alerts in the archives.json file ?

**Comment by jotacarma90** [comment]
Hello @bbkrr 

I have been analyzing all the information you have provided, and I have some doubts. If I only add to `local_decoder.xml` and `local_rules.xml` the only rule and decoder that you have passed, the following error appears:
```
2022/05/06 08:53:02 wazuh-analysisd: ERROR: (2101): Parent decoder name invalid: 'allow_all'.
2022/05/06 08:53:02 wazuh-analysisd: ERROR: (2106): Error adding decoder plugin.
2022/05/06 08:53:02 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/decoders/local_decoder.xml'.
```

Do you have some extra decoder added?

I have also been reading the thread you had with my coworker. As she said, the alerts with level 0 will always have preference over the rest. And since EventChannel events come in json format, you need modify the 60000 rule as she said. 

The behavior you are looking for is that all EventChannel related rules, which have level 0, appear with level 1?
Is this correct? 

Regards
Jose

**Comment by juliamagan** [comment]
Hello @bbkrr 

I have updated the [thread](https://groups.google.com/g/wazuh/c/qd4E6X0i0CM/m/UXqo1XKGFwAJ) with more information about how to prioritize your rules and decoders. If you have more questions, feel free to ask.

Regards
Julia

**Comment by bbkrr** [comment]
Hello @jotacarma90,

> Do you have some extra decoder added?

No, I don't have any extra decoder added.

> The behavior you are looking for is that all EventChannel related rules, which have level 0, appear with level 1?
Is this correct?

Yes, I want all of the EventChannel related rules to appear with level 1.

**Comment by bbkrr** [comment]
> Hello @bbkrr
> 
> I have updated the [thread](https://groups.google.com/g/wazuh/c/qd4E6X0i0CM/m/UXqo1XKGFwAJ) with more information about how to prioritize your rules and decoders. If you have more questions, feel free to ask.
> 
> Regards Julia

Hi @juliamagan 

Thank you for the response. I will look into it and let you know if I am stuck again.

Regards,
Bibek
