### ISSUE TITLE
Add option to make decoders accept the full log as input.

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1328]
This is a log example:

```
Sep 17 22:29:33 stretch dhclient[511]: DHCPREQUEST of 192.168.2.137 on eth2 to 192.168.2.1 port 67
^                                      ^
full_log                               log
```

The analysis engine tries to "predecode" the full log and extract the key fields of the syslog header, then the `log` part is the decoder input.

Sometimes the `full_log` does not match a syslog header successfully, so the `log` starting point is not placed properly.

This feature request suggests adding a decoder option to use the `full_log` as decoder input. For instance

```xml
<decoder name="test">
  <prematch offset="beginning">\S\S\S\s+\d+</prematch>
</decoder>
```

Thanks to @branchnetconsulting for this proposal.
Looking forward to seeing it working!

**Comment by feequs** [comment]
lets do this, 6 years waiting

BTW no any option to work with unusual format of logs, that parsed by pre-decoder incorrectly. Pre-decoder behavior can't be changed too.

**Comment by branchnetconsulting** [comment]
If I'm not mistaken, that is planned for Wazuh version 5.  In the mean time, the approach I use when dealing with those really funky log formats that the predecoder can't make good sense of, is to ensure that such logs are being written to a separate file just for their log type, and then in the <localfile> section for that file, add an <out_format> line to force a static prefix on the front of the original full log line, which will cause the whole log line including the extra prefix to be passed through to the decoder without the predecoder interfering with it.  An example of this with funky formatted VMware ESXi logs is illustrated in this Wazuh blog, which you may find helpful:
https://wazuh.com/blog/monitoring-vmware-esxi-with-wazuh/

Regards,
Kevin Branch
(Wazuh Trainer)

**Comment by vikman90** [comment]
@feequs Thank you for your input, and you're absolutely right—this feature request has been long overdue. The pre-decoding phase is an intrinsic part of the analysis process, and unfortunately, it's not something that can be easily bypassed. However, as @branchnetconsulting correctly mentioned, we are currently developing a new engine that will provide much more flexibility in decoder modeling and event management. This will range from working directly with raw events to handling pure JSON:

- https://github.com/wazuh/wazuh/issues/23577

We truly appreciate your patience, and we're confident this new solution will meet your expectations.

Let me close this issue.
Best regards,
