### ISSUE TITLE
Add $hostname as node name and $node_type as node type in cluster

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1329]
Hi team,

Allowing `$hostname` in configuration would allow a node to have its hostname as node name. In addition, the environment variable `$NODE_TYPE` could be used to define the node type.

Proposed by @JPLachance in https://github.com/coveo/wazuh-kubernetes/issues/5#issuecomment-422123865 and https://github.com/coveo/wazuh-kubernetes/issues/5#issuecomment-422383714.

Best regards,
Marta

**Comment by jesuslinares** [comment]
Duplicated: https://github.com/wazuh/wazuh/issues/2249.
