### ISSUE TITLE
Checksum check in realtime.c

### ISSUE THREAD

**Issue by arshad01** [wazuh/wazuh#133]
Hello,

In file syscheckd/run_realtime.c, line 57 has the following check:

``if (strcmp(c_sum, buf + 6) != 0)``

Since there are 8 field being checked (mtime is the new one), I think the check should be:

``if (strcmp(c_sum, buf + 8) != 0)``

buf+8 will skip over all the '+/-/s/n'.  

Thanks
Arshad

**Comment by vikman90** [comment]
Hi @arshad01,

you are right, we added some new fields (modification time and inode) but did not increase that offset. We have just reviewed and fixed it: https://github.com/wazuh/wazuh/commit/8788b0456d1c343d18d4d689cf13e4736010b2e3

Thank you very much for reporting it!

Best regards.
