### ISSUE TITLE
VDT scan does not complete properly on SUSE agent

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#13374]
# VDT scan does not complete properly on SUSE agent

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-agent-4.4.0-suse.22.04.x86_64 | Vuln Detector | Manager | Packages | Centos/8 |

**Wazuh Branch:** 7171-suse-vdt
**Wazuh-QA Branch:** 2792-test-scan-results

## Description
During testing of the SUSE vulnerability detector functionality, it was found that  the vulnerability scan for the agent would not finish properly, and would get stuck on the `...Sending vulnerabilities report for agent...'` message.
During testing, it was checked that the the vulnerability scan starts and the OVAL messages appear for the inserted vulnerabilities, but then the `scan finished` message does not appear.
It was found that the **modulesd** daemon would suddenly stop running sometimes, right after the Sending vulnerabilities message.

## Evidences
**Log Example:** [test_scan_suse_vulnerabilities log with official feed](https://github.com/wazuh/wazuh/files/8631881/con-feed.log).

## Steps to reproduce
It was tested with the following tests:
- [test_scan_suse_vulnerability_removal.py](https://github.com/wazuh/wazuh-qa/blob/2792-test-scan-results/tests/integration/test_vulnerability_detector/test_scan_results/test_scan_suse_vulnerability_removal.py)
- [test_scan_suse_vulnerabilities.py](https://github.com/wazuh/wazuh-qa/blob/2792-test-scan-results/tests/integration/test_vulnerability_detector/test_scan_results/test_scan_suse_vulnerabilities.py)

Both tests take the same steps:
- Mock Suse agent
- Insert Vulnerabilities
- Scan OVAL messages of inserted vulnerabilities
- Wait for the message that signals the scan has ended.

- During the test runs, **modulesd** and **wazuh-db** was monitored using the command `/var/ossec/bin/wazuh-control status |  grep modulesd && /var/ossec/bin/wazuh-control status | grep wazuh-db`
- The command would report that both modules were running, up until the moment where the log stops showing new information, at that moment it **modulesd** stops runing.

In the case of **test_scan_suse_vulnerabilities.py** the latest iteration installs the custom (case1) or official (other cases) OVAL feed during. It was found that sometimes **modulesd** would continue running, but the scan does not finish in either case.

**Comment by MarcelKemp** [comment]
After researching the problem, the cause of the segmentation fault has been found, and it was due to the problem reported in https://github.com/wazuh/wazuh/issues/12921.

The good news is that it is already fixed in this PR https://github.com/wazuh/wazuh/pull/13014, so once the branch has been updated to the base `4.4` branch (https://github.com/wazuh/wazuh/commit/6c31bb6fd18449baabb8ebaf4b2249c68a76eab5), the problem has been mitigated.
