### ISSUE TITLE
Remove framework code for non-cluster setups

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13382]
## Description
As part of epic #7108, the cluster will always be active and will become an essential service. Therefore, certain parts of the framework that distinguish between an enabled or disabled cluster no longer make sense:
https://github.com/wazuh/wazuh/blob/22b0fcb7190057d3116b1bdb8ef75fe19d9b0ffb/framework/wazuh/core/cluster/dapi/dapi.py#L142
https://github.com/wazuh/wazuh/blob/22b0fcb7190057d3116b1bdb8ef75fe19d9b0ffb/framework/wazuh/agent.py#L23-L24

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
As it was said in the related pull request, this issue is blocked by https://github.com/wazuh/wazuh/issues/13351
