### ISSUE TITLE
Sysmon rules for red team emulation

### ISSUE THREAD

**Issue by irfaanaikagjee** [wazuh/wazuh#13380]
Hello Wazuh team,

We did a red team emulation using caldera on a server but Wazuh did not detect anything. After some research, we found and used the following custom rules, **https://github.com/sametsazak/sysmon/blob/master/sysmon_rules.xml** and then some alerts were able to be generated. But it is very limited.

Would it be possible to create a new set of sysmon rules to generate alerts when using caldera to simulate a red team operation? If it was a real attack, we would have missed all of them.

Thank you

Best regards,
Irfaan A.

**Comment by fabamatic** [comment]
Hello @irfaanaikagjee, I am glad to inform you that we are in the process of adding new Sysmon rules. These rules are based on [MITRE's Red Team emulation](https://github.com/center-for-threat-informed-defense/adversary_emulation_library). They should be added in future release but if you need them now please check these pull requests:

- https://github.com/wazuh/wazuh/pull/13594
- https://github.com/wazuh/wazuh/pull/13673
- https://github.com/wazuh/wazuh/pull/13639
- https://github.com/wazuh/wazuh/pull/13637
- https://github.com/wazuh/wazuh/pull/13636
- https://github.com/wazuh/wazuh/pull/13631
- https://github.com/wazuh/wazuh/pull/13630
- https://github.com/wazuh/wazuh/pull/13596
- https://github.com/wazuh/wazuh/pull/13595

Hope these are helpful to you.
