### ISSUE TITLE
Invalid URL used during precompiled deps fetching on HP-UX agent compilation

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13399]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.0 up to master | Makefile - AWS S3 precompiled deps| Agent | Sources | HP-UX 11.31  |

## Description

It seems that PR https://github.com/wazuh/wazuh/pull/8178 change the architecture string used to fetch precompiled dependencies, leading to use the fallback mechanism that download and compile dependencies from sources, having huge impact on time and resources used to compile the agent. The agent is still compiles

* Before v4.3.0
`http://packages.wazuh.com/deps/<DEPS_VERSION>/libraries/hpux/not/<PRECOMPILED_LIB>.tar.gz`

* After v4.3.0
`http://packages.wazuh.com/deps/<DEPS_VERSION>/libraries/hpux/ia64/<PRECOMPILED_LIB>.tar.gz`

## Steps to reproduce
1. Get a provisioned HP-UX environment. See https://github.com/wazuh/wazuh-packages/tree/master/hp-ux
2. Clone wazuh/wazuh repository
3. Download deps: `gmake deps TARGET=agent`
### Expected results
3. Precompiled dependencies are fetched using a URL like `http://packages.wazuh.com/deps/<DEPS_VERSION>/libraries/hpux/not/<PRECOMPILED_LIB>.tar.gz`
### Current result
3. Precompiled dependencies are fetched using a URL like 
`http://packages.wazuh.com/deps/<DEPS_VERSION>/libraries/hpux/not/<PRECOMPILED_LIB>.tar.gz`
This URI does not exist, leading to fallback mechanism and downloading deps sources and compiling them.

**Comment by Dwordcito** [comment]
The name was changed as indicated, now the parent folder of the dependencies is under the IA64 architecture


![image](https://user-images.githubusercontent.com/14300208/168180343-b103cc06-9388-410b-90c2-d7f4e1603b71.png)
