### ISSUE TITLE
Bug in rule 92656 may cause false positives

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#13393]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3.0 | Rules | Error |

## Description
Rule 92656 "User logged using Remote Desktop Connection (RDP) from loopback address" is missing check to detect if the connection has RDP type.
This will cause false positives. To fix this issue the rule needs this field to be added:
`<field name="win.eventdata.logonType" type="pcre2">10</field>`

**Comment by maxim4** [comment]
I have the same issue with servers that are connected to Active Directory.

**Comment by mattvw** [comment]
+1 on this. Getting flooded with alerts for this after upgrading to 4.3.0. Added the overwrite entry in local_rules.xml but would love an official fix.

**Comment by xtrasimplicity** [comment]
Thanks heaps for reporting this - and posting a fix! I noticed this a few days ago and was sent off on a bit of a wild goose chase to identify the cause; thankfully, I hadn't spent too much time investigating before I identified that this was a false positive.

**Comment by gnordli** [comment]
When looking at the sysmon logs it appears to get triggered when group policy objects are being applied

**Comment by EHRETic** [comment]
Had the problem too and reported it in Google groups. 
Jose gave me the solution that I tested successfully! 😉

**Comment by r5r3** [comment]
We still see false positives with the updated rule. This happens whenever `::1` is contained in the IP address. Our last example was an address ending with `::16`. 

Should the regex be `^::1|127\.0\.0\.1$` instead of `::1|127\.0\.0\.1`?
