### ISSUE TITLE
No wazuh-monitoring-* events

### ISSUE THREAD

**Issue by sergiolr100** [wazuh/wazuh#134]
Hi guys,

First of all thanks for this project, really useful. I started using it last week and I am having some problems. 

I have my ELK stack 5.4 with a Elasticsearch cluster, kibana, logstash... I installed Wazuh manager in other server and register some agents and Kibana App too.

Wazuh manager uses Filebeat to send events to my logstash and this one is indexing alerts in ES. Logstash is using the correct logstash.conf: https://github.com/wazuh/wazuh/blob/master/extensions/logstash/01-wazuh.conf
And Kibana show two new index-patterns: `wazuh-alerts-*`and `wazuh-monitoring-*`. The template is loaded too. 

`GET _template/waz*`

```{
  "wazuh": {
    "order": 0,
    "template": "wazuh*",
    "settings": {
      "index": {
        "refresh_interval": "5s"
      }
    },
    "mappings": {
      "agent": {
        "properties": {
          "@timestamp": {
            "format": "dateOptionalTime",
            ...
```

I can see in agents tab the dashboards of my agents, but in Overview tab I have the errors `Saved field parameter is now invalid` and `Visualize: field is a required parameter`. I read about this problems: 

https://groups.google.com/d/msg/wazuh/BC2VzbUc6MI/nIv8OPiPBwAJ
elastic/kibana#9571

I think my problem is related with some visualizations which use `wazuh-monitoring-*` events, and I haven't got these events, this index is empty. Only have my `wazuh-alerts-*`events. How can I index the monitoring events in my cluster. Could you help me?

Thanks in advance.

Sergio L.

**Comment by sergiolr100** [comment]
I can see in my kibana logs:

```
...
{"type":"log","@timestamp":"2017-05-24T07:30:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
{"type":"log","@timestamp":"2017-05-24T07:40:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
{"type":"log","@timestamp":"2017-05-24T07:40:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
{"type":"log","@timestamp":"2017-05-24T07:50:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
{"type":"log","@timestamp":"2017-05-24T07:50:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
{"type":"log","@timestamp":"2017-05-24T08:00:01Z","tags":["wazuh","Wazuh agents monitoring","error"],"pid":18375,"message":"Could not check if the index wazuh-monitoring-2017.05.23 exists."}
...
```

I found the function:

```
       ...
        // Save agent status into elasticsearch, create index and/or insert document
        var saveStatus = function () {
                elasticRequest.callWithInternalUser('indices.exists',{ index: todayIndex }).then(
                        function (result) {
                                if (result) {
                                        insertDocument(todayIndex);
                                } else {
                                        createIndex(todayIndex);
                                }
                        }, function () {
                                server.log([blueWazuh, 'Wazuh agents monitoring', 'error'], 'Could not check if the index ' + todayIndex + ' exists.');
                        }
                );
        };
        ...
```

This is probably the reason why I haven't got any monitoring event... I continue investing... 

Thanks!

Sergio L.

**Comment by snaow** [comment]
Hi @sergiolr100,

Thanks for your feedback, I can see you have been digging into our code and you understand full flow, that is great! Make things easier for us if you have some technical background :D !

You are right about everything, "Saved field error" is prompt by Kibana when a visualization is trying to render fields which don't exit.
As you said, it is because you don't have data in wazuh-monitoring-* indices, it's seems like backend is failing to create those indices.

We are using same mechanism to create wazuh-monitoring indices and wazuh-alerts indices.

It should related to x-pack permissions.

**Comment by snaow** [comment]
@sergiolr100 

Wow! You replied in the meantime I was writing my response.

I am glad you found the problem, I totally agree with you, we need to expand our current documentation for Wazuh App, including needed permissions when using X-Pack.

Thanks for all the feedback and effort.

Cheers,
pedro.

**Comment by mgmacias95** [comment]
Hello @sergiolr100 and @snaow,

It's been more than a year since the last comment on this issue, so I'm closing it.

Don't hesitate to open a new one if you still have questions or problems.

Best regards,
Marta
