### ISSUE TITLE
Some SCA RHEL 8 controls are failing when they should pass.

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#13417]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.3.0 | SCA | Error |

# Description

Controls fail when they should pass. 

5075 - Ensure packet redirect sending is disabled
5076 - Ensure source routed packets are not accepted
5077 - Ensure ICMP redirects are not accepted
5078 - Ensure secure ICMP redirects are not accepted
5079 - Ensure suspicious packets are logged

Related 
- #13770
- #13417

- [x] Review specific controls.  
- [x] Review Other possible failing controls.

**Comment by titleistfour** [comment]
Hi, thanks for opening this.  To give more details, if I put the following sysctl changes in `/etc/sysctl.d/custom.conf`, the above controls fail in SCA.

```
# pci_dss: 2.2.4 - Enable randomly placement of virtual memory regions
kernel.randomize_va_space = 2

# pci_dss: 2.2.4 - An attacker could use a compromised host to send invalid ICMP redirects to other router devices in an attempt to corrupt routing
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# pci_dss: 2.2.4 - Ensure source routed packets are not accepted
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# pci_dss: 2.2.4 - Ensure source routed ICMP packets are not accepted
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0

# pci_dss: 2.2.4 - Ensure secure ICMP redirects are not accepted
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0

# pci_dss: 2.2.4 - Ensure suspicious packets are logged
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# pci_dss: 2.2.3 - Ensure IPv6 router advertisements are not accepted
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0

# pci_dss: 2.2.4 - Ensure Reverse Path Filtering is enabled
net.ipv4.conf.default.rp_filter = 1
```

However, if I move those exact same changes to `/etc/sysctl.conf`, the controls pass.

I'm testing this on RHEL 8.5 with wazuh-agent-4.2.6-1.x86_64.

Thanks

**Comment by ooniagbi** [comment]
- 5075 - Ensure packet redirect sending is disabled: moved to Not Implemented
- 5076 - Ensure source routed packets are not accepted: moved to Not Implemented
- 5077 - Ensure ICMP redirects are not accepted: moved to Not Implemented
- 5078 - Ensure secure ICMP redirects are not accepted: moved to Not Implemented
- 5079 - Ensure suspicious packets are logged: moved to Not Implemented

**Comment by jk-olaoluwa** [comment]
- 5075 - Ensure packet redirect sending is disabled: moved to Not Implemented
- 5076 - Ensure source routed packets are not accepted: moved to Not Implemented
- 5077 - Ensure ICMP redirects are not accepted: moved to Not Implemented
- 5078 - Ensure secure ICMP redirects are not accepted: moved to Not Implemented
- 5079 - Ensure suspicious packets are logged: moved to Not Implemented

The checks wont be implemented as the audits in the pdf are bash scripts
