### ISSUE TITLE
vulnerability model question ！

### ISSUE THREAD

**Issue by myh0st** [wazuh/wazuh#1342]
# test env

kibana 6.3.2 + wazuh app 3.6.1 + wazuh agent 3.4 + wazuh api 3.6.1

# manager vulnerability config

```
  <wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <run_on_start>yes</run_on_start>
  <feed name="redhat-6">
    <disabled>no</disabled>
    <path>/var/ossec/etc/Red_Hat_Enterprise_Linux_6.xml</path>
    <update_interval>1h</update_interval>
  </feed>
  <feed name="redhat-7">
    <disabled>no</disabled>
    <path>/var/ossec/etc/Red_Hat_Enterprise_Linux_7.xml</path>
    <update_interval>1h</update_interval>
  </feed>
  </wodle>
```

# agent config

```
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>
```

# question

Vulnerability scanning is only performed when the agent is restarted, and there are no subsequent scan results. why ？

**Comment by crolopez** [comment]
Hi @myh0st,

Vulnerability-detector runs a scan every time an interval ends, but does not report back vulnerabilities on those packages you have already reported until a timeout defined by the [ignore_time](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-vuln-detector.html#ignore-time) parameter is reached.

In other words, restart will always report all available packages, and will wait a default waiting time of 6 hours to unlock the report on those packages again on the next scan. However, if Syscollector detects that there has been a change in the version of any package, it will automatically be available for reporting.

Best regards.

**Comment by myh0st** [comment]
However, after a few days, there is no data, what is going on?

**Comment by crolopez** [comment]
I can see that you don't have the ignore_time parameter, so the package report is unlocked every 6 hours. You should see alerts with that periodicity.

Can you see alerts when you restart the manager?

**Comment by myh0st** [comment]
![1](https://user-images.githubusercontent.com/26624320/45741437-24644700-bc2a-11e8-9f56-7f7458052354.png)

**Comment by myh0st** [comment]
where is alerts log ？

**Comment by crolopez** [comment]
<install_dir>/logs/alerts/alerts.json 

Can you check that the manager has registered the agent packages?

`curl -u user_api:pass_api -k -X GET "https://127.0.0.1:55000/syscollector/<agent_id>/hardware?pretty"`

**Comment by myh0st** [comment]
> {
   "error": 0,
   "data": {
      "board_serial": "unknown",
      "ram": {
         "total": 32780936,
         "free": 669064
      },
      "cpu": {
         "cores": 1,
         "mhz": 2394.448,
         "name": "Common KVM CPU"
      },
      "scan": {
         "id": 950424414,
         "time": "2018/09/19 16:16:30"
      }
   }
}

**Comment by crolopez** [comment]
Sorry, I sent you the hardware query. The package query is:

curl -u user_api:pass_api -k -X GET "https://127.0.0.1:55000/syscollector/<agent_id>/packages?pretty"

**Comment by myh0st** [comment]
```
{
   "error": 2007,
   "message": "Error retrieving data from Wazuh DB: Error 2007 - Error retrieving data from Wazuh DB."
}
```

**Comment by crolopez** [comment]
It seems that wazuh-db is not returning the information to the API, maybe to Vulnerability-detector either. Can you check if wazuh-db is down with <install_dir>/bin/ossec-control status?

**Comment by myh0st** [comment]
![2](https://user-images.githubusercontent.com/26624320/45743874-a3a84980-bc2f-11e8-92a5-ec5bfd7df40d.png)

status is ok ！

**Comment by myh0st** [comment]
https://github.com/wazuh/wazuh/issues/1202

solved

**Comment by crolopez** [comment]
It's a problem with character encoding. We already have the fix and it will be included in the next release.

**Comment by crolopez** [comment]
You can see the solution [here](https://github.com/wazuh/wazuh/pull/1347) . 

Let me close the issue.

Best regards.

**Comment by myh0st** [comment]
![1](https://user-images.githubusercontent.com/26624320/45856837-c39f5080-bd88-11e8-84c7-b0a1f9ac95ce.png)

The problem of this non-repeating scan report still exists ？

**Comment by crolopez** [comment]
In your case you should receive the alerts again every 6 hours. If this is not happening, and the API package query returns an error code after applying the patch, the issue may be due to an unexpected reason.

Re-open the issue if the problem persists. Do you see errors in the log?

`cat <install_dir>/logs/ossec.log | grep "ERROR:"`
