### ISSUE TITLE
Error creating wazuh-db backup during install

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#13441]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Wazuh DB | Manager| Packages/Sources | OS version |

As part of #10771, a new mechanism to create a backup for `wazuh-db` was added.

However, a bug was added during the new development, as this error has appeared in several test checks recently:

`2022/05/11 14:48:03 wazuh-db: ERROR: Creating Global DB snapshot by interval failed: err SQLite: unable to open database: backup/db/global.db-backup-2022-05-11-14:48:03
`

**Comment by Dwordcito** [comment]
This issue was fixed yesterday by:

https://github.com/wazuh/wazuh-packages/pull/1543
https://github.com/wazuh/wazuh-packages/pull/1542
