### ISSUE TITLE
Could not verify signature while upgrading Agent

### ISSUE THREAD

**Issue by bbkrr** [wazuh/wazuh#13461]
Manager:

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Server | Manager | Sources | Ubuntu 20.04 |

Agent:

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Server | Agent | Source | Windows Server 16 |

Agent to upgrade:

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Server | Agent | Custom WPK | Windows Server 16 |

While upgrading the agent of version `4.2.5` to `4.3.0` using custom wpk file, I am getting the following errors:

In the Manager:

```
2022/05/16 01:51:36 wazuh-modulesd:download: INFO: Module started.
2022/05/16 01:51:36 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2022/05/16 01:51:36 wazuh-modulesd:syscollector: INFO: Module started.
2022/05/16 01:51:36 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/05/16 01:51:36 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_debian10.yml'
2022/05/16 01:51:36 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/05/16 01:51:41 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_debian10.yml'
2022/05/16 01:51:41 sca: INFO: Security Configuration Assessment scan finished. Duration: 5 seconds.
2022/05/16 01:51:49 rootcheck: INFO: Ending rootcheck scan.
2022/05/16 02:00:08 wazuh-modulesd:agent-upgrade: ERROR: (8116): Error response from agent: 'Could not verify signature'
```

In the Windows Agent:

```
2022/05/16 02:00:09 wazuh-agent: ERROR: Error verifying WPK certificate.
2022/05/16 02:00:09 wazuh-modulesd:agent-upgrade: ERROR: (8139): At unsign(): Could not unsign package file 'incoming\AgentX-4.3.0.wpk'
2022/05/16 02:00:09 wazuh-modulesd:agent-upgrade: ERROR: (8131): At upgrade: 'Could not verify signature'
```

I followed the steps provided in the [Generate WPK packages manually](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/create-custom-wpk/generate-wpk-package-manually.html) and [Custom certificates](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/create-custom-wpk/create-wpk-key.html).

Also, I am using Wazuh API to upgrade,
`PUT: {{url}}/agents/upgrade_custom?agents_list=004&file_path=/var/ossec/AgentX-4.3.0.wpk&installer=upgrade.bat`

**Comment by vikman90** [comment]
Hi @bbkrr,

The most common cause of this problem is that your custom certificate is not installed in the agent.

I wonder if you also followed [Installing a custom WPK package](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html). The agent checks the WPK package's certificate (`path/to/wpkcert.pem` in the guide) against the root CA certificate (`wpk_root.key`). Therefore, the root CA must be installed in the agent. Otherwise, you can disable the certificate validation in the agent:

```xml
<agent-upgrade>
    <ca_verification>
        <enabled>no</enabled>
    </ca_verification>
</agent-upgrade>
```

But we recommend following the guide to install the certificate.

Hope that help.
Best regards.

**Comment by bbkrr** [comment]
Hi @vikman90,

Yes, I followed the documentation, but the process was bit confusing. But now I am able to upgrade the agent. 
So, thank you for the response.

Regards,
Bibek Chaudhary
