### ISSUE TITLE
Improve deprecated MITRE mapping in rules

### ISSUE THREAD

**Issue by zados** [wazuh/wazuh#13517]
| Wazuh version | Component | Action type |
| ------------- | ------------- |  ------------- |
|4.3.0| Rules | Improve |

## Description
Rules containing deprecated MITRE technique id were identified. Please improve the rules by adding correct MITRE TID

## Rules
| RuleID  | Description | Old MITRE ID | New MITRE ID
| ------------- | ------------- |  ------------- | ------------- |
| 31105  | XSS (Cross Site Scripting) attempt.  | T1064 | T1059.007   |
| 31154  | Multiple XSS (Cross Site Scripting) attempts  | T1064 | T1059.007   |
| 31505  | TimThumb backdoor access attempt.  | T1108 | T1505.003   |
| 35054  | W32.Beagle.DP is a Worm that drops Trojan.Lodear and opens a back door on the compromised computer.  | T1108 | T1505.003  |
| 35055  | Squid: Multiple attempts to access a non-existent file.  | T1108 | T1505.003   |
| 92021  | Powershell was used to delete files or directories.  | T107.004 | T1070.004   |

I do believe the last one might have been a typo though.

### Log reference
e.g. wazuh-analysisd: WARNING: Mitre Technique ID 'T1064' not found in database.

**Comment by fabamatic** [comment]
Duplicated in https://github.com/wazuh/wazuh/issues/13515
Fixed in https://github.com/wazuh/wazuh/pull/13567
