### ISSUE TITLE
Aws organizations logs ingestion

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#13516]
Hello.

Based on the below site and the logs we receive we came to the conclusion that wazuh Cloudtrail integration monitors ec2 and iam logs alone. Is that correct? If yes can we add the monitoring of AWS organization events as well. It's pretty crucial since this service is the head of the business.

https://documentation.wazuh.com/current/amazon/services/supported-services/cloudtrail.html#amazon-cloudtrail

**Comment by CarlosRS9** [comment]
Hi @antonisnyc94 

Let me clarify this topic about our AWS cloudtrail integration compatiblity.

No, it is not correct that our integration is only able to monitoring EC2 and IAM logs. These are just 2 use cases that we put as examples in our documentation, to give you a quick idea of what CloudTrail integration with Wazuh could be useful for, but is not limited only to these two types of events.

Regarding AWS organization events, yes, our integration supports them. Our integration is able to process any log that has been generated by AWS Cloudtrail. If it can be configured using AWS Cloudtrail and it stored logs in a S3 bucket, it can be processed. In particular, if you take a look at this [official AWS documentation](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_security_incident-response.html#orgs_cloudtrail-integration) page you will see a series of example logs entries for AWS Organizations. Our itnegration is compatible with all the examples shown there.


However, it is important to note that while our integration is compatible with any Cloudtrail event, Wazuh does not include default rules for absolutely all CloudTrail logs that could be processed. You can have a look at the default rules available [here](https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0350-amazon_rules.xml). If Wazuh doesn't have adefault rule for these AWS organization events that you want to process, it simply means that you will have to create your own custom rules for them. Once you create them, Wazuh will consume the logs and generate the corresponding alerts.

Following the examples from the official AWS documentation I mentioned before, if you try to ingest one of these events with our integration and test it using the logtest utility you will see that it only matches our rule `80200`, which is the base rule for all AWS events. This means that for this type of logs you will have to create your own custom rules.

```
/var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.0
Type one log per line

{"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "AWSLogs/166157449999/CloudTrail/us-west-1/2021/12/23/166157441623_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz", "s3bucket": "wazuh-aws-wodle-cloudtrail"}, "eventVersion": "1.06", "userIdentity": {"type": "IAMUser", "principalId": "AIDAMVNPBQA3EXAMPLE", "arn": "arn:aws:iam::111111111111:user/diego", "accountId": "111111111111", "accessKeyId": "AKIAIOSFODNN7EXAMPLE", "userName": "diego"}, "eventTime": "2017-01-18T21:42:44Z", "eventSource": "organizations.amazonaws.com", "eventName": "AttachPolicy", "awsRegion": "us-east-1", "sourceIPAddress": "192.0.2.0", "userAgent": "Mozilla/5.0(Macintosh;IntelMacOSX10_11_6)AppleWebKit/537.36(KHTML,likeGecko)Chrome/55.0.2883.95Safari/537.36", "errorCode": "PolicyTypeNotEnabledException", "errorMessage": "ThegivenpolicytypeServiceControlPolicyisnotenabledonthecurrentview", "requestParameters": {"policyId": "p-examplepolicyid111", "targetId": "ou-examplerootid111-exampleouid111"}, "requestID": "EXAMPLE8-90ab-cdef-fedc-ba987EXAMPLE", "eventID": "EXAMPLE8-90ab-cdef-fedc-ba987EXAMPLE", "eventType": "AwsApiCall", "recipientAccountId": "111111111111", "source": "cloudtrail", "aws_account_id": "166157449999", "source_ip_address": "192.0.2.0"}}

**Phase 1: Completed pre-decoding.

**Phase 2: Completed decoding.
	name: 'json'
	aws.awsRegion: 'us-east-1'
	aws.aws_account_id: '166157449999'
	aws.errorCode: 'PolicyTypeNotEnabledException'
	aws.errorMessage: 'ThegivenpolicytypeServiceControlPolicyisnotenabledonthecurrentview'
	aws.eventID: 'EXAMPLE8-90ab-cdef-fedc-ba987EXAMPLE'
	aws.eventName: 'AttachPolicy'
	aws.eventSource: 'organizations.amazonaws.com'
	aws.eventTime: '2017-01-18T21:42:44Z'
	aws.eventType: 'AwsApiCall'
	aws.eventVersion: '1.06'
	aws.log_info.log_file: 'AWSLogs/166157449999/CloudTrail/us-west-1/2021/12/23/166157441623_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz'
	aws.log_info.s3bucket: 'wazuh-aws-wodle-cloudtrail'
	aws.recipientAccountId: '111111111111'
	aws.requestID: 'EXAMPLE8-90ab-cdef-fedc-ba987EXAMPLE'
	aws.requestParameters.policyId: 'p-examplepolicyid111'
	aws.requestParameters.targetId: 'ou-examplerootid111-exampleouid111'
	aws.source: 'cloudtrail'
	aws.sourceIPAddress: '192.0.2.0'
	aws.source_ip_address: '192.0.2.0'
	aws.userAgent: 'Mozilla/5.0(Macintosh;IntelMacOSX10_11_6)AppleWebKit/537.36(KHTML,likeGecko)Chrome/55.0.2883.95Safari/537.36'
	aws.userIdentity.accessKeyId: 'AKIAIOSFODNN7EXAMPLE'
	aws.userIdentity.accountId: '111111111111'
	aws.userIdentity.arn: 'arn:aws:iam::111111111111:user/diego'
	aws.userIdentity.principalId: 'AIDAMVNPBQA3EXAMPLE'
	aws.userIdentity.type: 'IAMUser'
	aws.userIdentity.userName: 'diego'
	integration: 'aws'

**Phase 3: Completed filtering (rules).
	id: '80200'
	level: '0'
	description: 'AWS alert.'
	groups: '['amazon', 'aws']'
	firedtimes: '1'
	mail: 'False'
```

Check out the following links to learn more about creating and testing custom rules:
- [Custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)
- [Testing decoders and rules](https://documentation.wazuh.com/current/user-manual/ruleset/testing.html)


Finally, if you want to create your own rules for these AWS logs I recommend you to make use of the [logall](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall) option to see exactly what format wazuh is sending your AWS events to be analysed. When this option is enabled, Wazuh stores into `WAZUH_PATH/logs/archives/archives.log` file every event sent to the analysis engine whether they tripped a rule or not. If you enable this and run our AWS integration you could check the `archives.log` file, pick one example of your AWS organization events and use it to develop your custom rules.

After you enable the logall option you will need to restart your wazuh manager to apply it. Also, don't forget to disable the logall option once the troubleshooting has finished. Leaving it enabled could result in high disk space consumption.

**Comment by antonisnyc94** [comment]
Hey @CarlosRS9  the reply does not answer my question but i was able to retrieve the full list of Cloudtrail events processed by wazuh from `/var/ossec/etc/lists/amazon/aws-eventnames` which can help me add more custom events if needed!! Meaning if it's a cloudtrail event i can just add to the list without modifying decoders!

Thank you!
Tony

**Comment by antonisnyc94** [comment]
Also based on this https://docs.aws.amazon.com/organizations/latest/userguide/orgs_security_incident-response.html#orgs_cloudtrail-integration and the list i found. NO AWS ORGANIZATION logs are processed. Which is something that needs to be added from a Security perspective. Maybe we can translate this ticket to feature request? @CarlosRS9

**Comment by CarlosRS9** [comment]
Hi @antonisnyc94. You are right, our `lists/amazon/aws-eventnames` file should be updated. We have created [this issue](https://github.com/wazuh/wazuh/issues/13653) to update it. Our team will add it to the roadmap as soon as possible. You can follow the development using that issue.
