### ISSUE TITLE
Engine - Decode Syscollector events

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#13520]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | any | Linux |

# Description

As part of epic #13038, it is necessary to decode the Wazuh' Syscollector events.

### Syscollector

**Queue: `'d'` / `0x64` / `SYSCOLLECTOR_MQ`**

The [DecodeSyscollector()](https://github.com/wazuh/wazuh/blob/1aebe7d6806786e544044a69f633555036400465/src/analysisd/decoders/syscollector.c#L216) method is in charge of handling the syscollector events, which are identified by the queue id `0x64` ([SYSCOLLECTOR_MQ](https://github.com/wazuh/wazuh/blob/59b90c7a0cf585e01b3f915900adfd5faea499e5/src/headers/mq_op.h#L32)). Every hour, by default, the agents send to the manager information related to their systems which are processed by this decoder. As in SCA, this method receives a json object from where it obtains the event `/type` to determine what to do with it and how to create the wazuhdb query.

Up to Wazuh 4.3, the wazuhdb queries related to syscollector do not enrich the event but its only purpose is to keep the database synchronized. Legacy functions:
- `decode_port`
- `decode_package`
- `decode_hotfix`
- `decode_hardware`
- `decode_osinfo`
- `decode_netinfo`
- `decode_process`

From Wazuh 4.4, the [Decode_dbsync() ](https://github.com/wazuh/wazuh/blob/1aebe7d6806786e544044a69f633555036400465/src/analysisd/decoders/syscollector.c#L2071)method was developed to enrich the incoming event by querying the wazuhdb. The received event only includes the new/modified fields (deltas) instead of the whole data. When doing an Update or Delete operation, the data is fully retrieved to be processed.

**Comment by LucioDonda** [comment]
As defined above, the process was divided into seven yaml decoders (at the end the decoder should be unified).

Tasks:
- [ ]  analyze each case
   - [ ]  issue with error_package and prev_package_id discarded (unnecessary now)
- [ ]  transform every process to the engine language (yml)
   - [ ]  decode_port
   - [ ]  decode_package
   - [ ]  decode_hotfix
   - [ ]  decode_hardware
   - [ ]  decode_osinfo
   - [ ]  decode_netinfo
   - [ ]  decode_process
detected helper functions needed:
   - [ ] create hassh (SHA1) from variable strings as parameters
   - [ ] transform string json array to a single field with each element concatenated with or without a separator)
- [ ]  Unify all decoders to a single (this could create an unreadable long decoder) or find a way to set the first part for a parent and call each one when neccesary
