### ISSUE TITLE
Engine - Decode SCA events

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#13522]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | any | Linux |

# Description

As part of epic #13038, it is necessary to decode the SCA events.

### SCA
**Queue: `'p'` / `0x70` / `SCA_MQ`**

The [DecodeSCA()](https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/src/analysisd/decoders/security_configuration_assessment.c#L168) method is in charge of handling the SCA events, which are identified by the queue id 0x70 (SCA_MQ). Each new incoming message triggers the wazuhdb synchronization and retrieves its previous state to enrich the event.

It seems that only the `FillScanInfo()` and `FillCheckEventInfo()` modify the original event.
When enriching the event, the previous scan is stored on a new field called "sca.check.previous_result". This previous state is then matched with the rules to look for changes.

Issues found while starting to resolve this issue:
- [x]  Handling nested code: causes a complex, long and hard-to-debug piece of code, in order to tackle this a complete analysis has been done
- [x] how to tackle message pushed to CFGA queue (should be applied something like AR in wdbSync)

Discarded:

- How to engage with iterations inside the decoder?
- we need a helper or an engine functionality that allows us to take different field members (basically from an array) applying a helper, map, checking, or any other operation on it each time. This could be applied on a specific range or in all the array.  
- Helper function for cutting string X chars 

Analysis on DecodeSCA function:

![SCA decoder diagram](https://user-images.githubusercontent.com/95248059/176958576-dd9a142e-0205-43cb-b02f-ef0f392d6a70.jpg)

After discussing with the whole team the option of leaving this Decoder as a (not user-reachable function) was contemplated as possible. 
Another option is dividing it into two parts, in the first, the message gets decoded, all necessary fields are taken and separated, and once that it's achieved, all DB queries are made sitting the results that the user needs.
The option of modifying how the db talked it's arguments (not a single key - value but allowing it to take an array or a json directly) was also analyzed. 

The defined final approach was to unify all process inside a single helper function

**Comment by LucioDonda** [comment]
Complete Raw logs obtained from a centos 8 agent for testing purposes:
[DecodeSCA_raw_logs.zip](https://github.com/wazuh/wazuh/files/9253061/DecodeSCA_raw_logs.zip)
This can be taken from the server ossec.log by setting 
`analysisd.debug=1`
And filtering it with 
`grep -hnr "DecodeSCA(): DEBUG: Got " /var/ossec/logs/ossec.log >  /file_path`
