### ISSUE TITLE
Wazuz - Azure AD Slack message

### ISSUE THREAD

**Issue by mirceacroitoru** [wazuh/wazuh#13544]
Hi 

I configured wazuh 4.3 to send message to Slack in case of Azure AD activitity.
I created and then deleted a user in Azure AD and the message i got for both actions was :

Azure: AD
Agent
(000) - [wazuh.xxxx.com](http://wazuh.xxxx.com/)
Location
Azure
Rule ID
87802 (Level 3)

Where can change the format of this message? All the alerts are coming under same rule_id ( 87802 ).
I want to get at least the data.activityDisplayName

**Comment by CarlosRS9** [comment]
Hi @mirceacroitoru,

You can achieve that but it will require to modify the python code of the slack integration.

I suggest you take advantage of Wazuh's ability to execute user-created custom integrations, as described [here](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#custom-integration). You just need to copy the `slack.py` file and create your own `custom-slack.py` from it. This way you will keep the original slack integration intact in case something goes wrong or you just want to go back, plus you will be guaranteed not to lose your changes in future Wazuh updates when the time comes for us to update this module. Take a look to [this](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/) official blogpost to learn more about using custom external integrations.

Regarding the necessary code modifications, what you need to do is to alter the code of the `generate_msg` function. This is where we build the message body and format it. If you take a look at the lines starting with `msg['fields'].append`, you'll see that this is where the different lines of the alert you see in slack are being inserted. So just add the fields you need here. For example, if you want to add an additional field for `activityDisplayName` you would just add a line similar to the following:
```
if 'data' in alert and 'activityDisplayName' in alert['data']:
    msg['fields'].append({"title": "Activity Name", "value": alert['data']['activityDisplayName']})
```

In case you want to expand your slack alerts but you don't know how to access the values you want that are present in the alert message. I suggest you to take a look to the `WAZUH_PATH/logs/alerts/alerts.json` file. Wazuh stores every alert sent to the UI and your custom integrations there, so you just need to look for any Azure alert present there and take a look to its structure.

Finally, remember that the name of your custom integration must start with `custom-`.

Let us know if you need further assistance.

**Comment by mirceacroitoru** [comment]
Thank you very much Carlos.  I will take a look.
