### ISSUE TITLE
Active response Windows Route-Null with error

### ISSUE THREAD

**Issue by oliveiralive** [wazuh/wazuh#13557]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.5 | Windows Active Response | Agent v4.3.1| Sources | Rocky Linux release 8.5|

I'm testing wazuh's active response feature for windows and I've identified some problems
initially  hade an error to find the event srcip, problem that was fixed by updating the client to 4.3.1 \o/

 Now the problem is with the route-null script in /var/ossec/active-response/bin, the route created not work like expected,

bellow the configuration in /var/ossec/etc/ossec.conf
```
  <command>
    <name>win_route-null</name>
    <executable>route-null.exe</executable>
    <timeout_allowed>yes</timeout_allowed>
  </command>

<active-response>
    <command>win_route-null</command>
    <location>local</location>
    <rules_id>60204</rules_id>
    <timeout>900</timeout>
</active-response>
```

Active response test
![image](https://user-images.githubusercontent.com/35010493/169715290-0979adef-bef5-4e83-a446-9e01dbffa8e0.png)

![image](https://user-images.githubusercontent.com/35010493/169715312-e9206380-e55d-4e7e-a6c3-1aeca274b5bd.png)

**The problem its here**, this route its wrong, **the gateway shold to be other**
![image](https://user-images.githubusercontent.com/35010493/169715333-3739db51-52dc-43fc-9c2e-7694dccc9dd2.png)

The gateway of a windows route null shold be a ip of a difetent network, in  exemple below i used ip reserved for documentation and worked
https://datatracker.ietf.org/doc/html/rfc5737

![image](https://user-images.githubusercontent.com/35010493/169715573-7c41ab48-3dca-466d-81b5-14702ac179cc.png)

The Question is:
How a can chenge the script route-null to use the ip 203.0.113.1 as gateway?
![image](https://user-images.githubusercontent.com/35010493/169715827-a6b410dd-35a3-405c-aa6a-3ae464f52661.png)

**Comment by vikman90** [comment]
Hi @oliveiralive,

Thank you for your excellent analysis. As of 4.2, most Active response executors were translated into the C language. For instance, this is the implementation of [route-null](https://github.com/wazuh/wazuh/blob/6bd00693a3909c6498ac71ba02a482c369a56088/src/active-response/route-null.c).

The Windows implementation just uses the default gateway. According to lines [115-121](https://github.com/wazuh/wazuh/blob/6bd00693a3909c6498ac71ba02a482c369a56088/src/active-response/route-null.c#L115-L121), it runs this command;

```
%WINDIR%\system32\ipconfig.exe | %WINDIR%\system32\findstr.exe /R /C:".*Default Gateway.*[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*"
```

If I understood well, the fix would be replacing all the logic to get the gateway with something like this:

```
char gateway[IPSIZE + 1] = "192.0.2.1";
```

Then, build the agent for Windows ([documentation](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html)). You can either install it or just replace `src/win32/route-null.exe` into _C:\Program Files (x86)\ossec-agent\active-response\bin_.

Hope this helps. If you confirm this works, we will apply the fix to the code!

Best regards.

**Comment by oliveiralive** [comment]
Hi @vikman90 , i finishd the tests

I edited the route-null like the documentation above

ORIGINAL 
https://github.com/wazuh/wazuh/blob/6bd00693a3909c6498ac71ba02a482c369a56088/src/active-response/route-null.c#L137-L137



CHANGED
```if (gateway[0]) {
            char *exec_args_add[8] = { ROUTE_PATH, "add", (char *)srcip, "mask", "255.255.255.255", "203.0.113.1", "if 1 -p", NULL };
```


The route start to appear like expected
<img width="547" alt="image" src="https://user-images.githubusercontent.com/35010493/169941825-7ad63345-ab2a-4bdf-9ae9-bce6036d595e.png">


<img width="445" alt="image" src="https://user-images.githubusercontent.com/35010493/169940526-861c21a4-f0fc-46a2-8c92-0c6dea5abb64.png">


But still have a problem
The Server not connect with srcip attacker, but src ip attacker still can connect with server
<img width="755" alt="image" src="https://user-images.githubusercontent.com/35010493/169941993-8ff95f91-1710-45e1-85f1-e3008e3c8c15.png">



Then, its possible conclude that the route-null its not a afetive way to block ip attackers in windows clients :(
Exist other way to do this?

**Comment by Cloud9Networks** [comment]
@oliveiralive 
If the route is set to null, the attacker won't be able to do anything as the reverse path/route is required to establish the connection. There should be a route between Client/Server otherwise the connection won't be established, therefore, in my opinion, the null route is doing its job by not responding to the attacker.

**Comment by oliveiralive** [comment]
@vikman90 , thanks for your time, I'm doing some testing and will get back to you soon

**Comment by oliveiralive** [comment]
Hi @vikman90 , i did many tests and the netsh work perfectly,
one only situation its in enviroments that not had windows firewall enable, in this case, we can use a simple script.cmd that enable windows firewall if nessessary.

 active/response/bin on clients windows

```
@echo off


powershell -command "netsh advfirewall set allprofiles state on; netsh advfirewall firewall add rule dir=in action=allow remoteip=any name=VigilantBlock; exit"
```

:D
![image](https://user-images.githubusercontent.com/35010493/183151343-ce662082-6452-4176-bec2-f3571e1e2040.png)

**Comment by vikman90** [comment]
Thank you very much @oliveiralive. So, I'm going to open a new issue to update `netsh`, to extend compatibility, detect whether Windows Firewall is disabled, and decide how to act in such a case.

Thank you again for your valuable help.
Best regards.

**Comment by walid354** [comment]
> Hi @vikman90 , i finishd the tests
> 
> I edited the route-null like the documentation above
> 
> ORIGINAL
> 
> https://github.com/wazuh/wazuh/blob/6bd00693a3909c6498ac71ba02a482c369a56088/src/active-response/route-null.c#L137-L137
> 
> CHANGED
> 
> ```
>             char *exec_args_add[8] = { ROUTE_PATH, "add", (char *)srcip, "mask", "255.255.255.255", "203.0.113.1", "if 1 -p", NULL };
> ```
> 
> The route start to appear like expected <img alt="image" width="547" src="https://user-images.githubusercontent.com/35010493/169941825-7ad63345-ab2a-4bdf-9ae9-bce6036d595e.png">
> 
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/35010493/169940526-861c21a4-f0fc-46a2-8c92-0c6dea5abb64.png">
> 
> But still have a problem The Server not connect with srcip attacker, but src ip attacker still can connect with server <img alt="image" width="755" src="https://user-images.githubusercontent.com/35010493/169941993-8ff95f91-1710-45e1-85f1-e3008e3c8c15.png">
> 
> Then, its possible conclude that the route-null its not a afetive way to block ip attackers in windows clients :( Exist other way to do this?

Hello @oliveiralive 
I  have the same issue route-null did not work due to the default gateway.
So i did not know how to change route-null.c script from https://github.com/wazuh/wazuh/blob/4.5/src/active-response/route-null.c  and how to make it .exe
