### ISSUE TITLE
FIM event randomly not appearing on Solaris Agent

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#13554]
|Wazuh version|Component|Install type|Install method|Platform| QA Branch |
|---|---|---|---|---|---|
| 4.5.0-0.40500.20220511 | Wazuh Agent | Agent | Packages | Solaris | 2881-solaris-fim-fail |

## Description

During the Nightly run of the Wazuh-QA repo the test `test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py` failed on a Solaris Agent.

While debugging the test it was found that sometimes the expected FIM **`added`** event would not be generated even though the file was created properly. 

The test has been run multiple times with success and the log appearing normally, but sometimes the log is not generated which seems to be an issue on the agent's flaky behavior. 
While trying to reproduce the error through manual testing, causing the error to appear was not achieved, so this would add to the flaky behaviour experienced. 

The manual testing steps are added as guide on what was done, but we advice that the test results and logs are given used as a primary source, since that is where the error was found.

| Result| Type| Notes|
|--|--|--|
| [:green_circle:](https://github.com/wazuh/wazuh/files/8743398/FIM.Solaris.zip) [:red_circle: ](https://github.com/wazuh/wazuh/files/8743396/local-log.zip)  [:green_circle:](https://github.com/wazuh/wazuh/files/8743397/manual.zip)  | Local | 
| [:red_circle: ](https://ci.wazuh.info/view/Tests/job/Test_integration/26614/)| Jenkins|

## Steps taken for manual testing

> 1. Stop Wazuh
> 2. Configure directory for monitoring and 10s interval for scans
> 3. Start Wazuh
> 4. Create File in monitored directory
> 5. wait for 10 secs.
> 6. Modify file
> 7. wait for 10 secs.
> 8. delete file
> 9. wait for 10 secs.

## Local Internal Options

> syscheck.debug=2
> agent.debug=2
> monitord.rotate_log=0
> syscheck.symlink_scan_interval=600

**Comment by FrancoRivero** [comment]
Hi @Deblintrake09 , 
I have reproduced this bug, I have found a problem in a function called `modify_file_inode` that changes the inode in a file inside a library called `fim.py`. I have read about this problem and found that the `os.replace` function does not work well on all systems so we can change `os.replace` to `shutil.move` that function has the same parameters. 
By changing this function this test runs again, this is a test run with this change:

```
root@solaris11:/export/home/vagrant/wazuh-qa/tests/integration# python3 -m pytest -vvx test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py
=============================================================================================== test session starts ===============================================================================================
platform sunos5 -- Python 3.7.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /opt/python3/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.7.6', 'Platform': 'SunOS-5.11-i86pc-i386-32bit-ELF', 'Packages': {'pytest': '6.2.2', 'py': '1.10.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'metadata': '1.8.0', 'testinfra': '5.0.0'}}
rootdir: /export/home/vagrant/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-1.8.0, testinfra-5.0.0
collected 1 item                                                                                                                                                                                                  

test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py::test_realtime_unsupported[get_configuration0] PASSED                                                                         [100%]

================================================================================================ 1 passed in 8.42s ================================================================================================
```
From dev side we closed that issue if you want to reopen it again let me know. 
Regards
