### ISSUE TITLE
Engine - Update design document

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#13575]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | Packages/Sources | OS version |

The design document needs to be revised and updated with respect to the current implementation of the engine. The latest engine updates should be reflected in our document. It will be used to order the content of the document correctly.

## Identified Tasks
- [x] Add appendix with implemented function helpers documentation
- [x] Better structure Asset and the different assets description
- [x] Expand information on HLP and KVDB

**Comment by LucioDonda** [comment]
- Added a list of helper functions plus KVDB helpers with an explanation
- Edits and comments on Databases section
- Edits and comments on Parser section
- Edits and comments  on user manual document

**Comment by JavierBejMen** [comment]
- Wrote Asset section to clarify better what an asset is and all the common parts between different Asset types.
- Rewrote Decoder and Rule section to harmonize with the Asset section.

Ready for review.
