### ISSUE TITLE
Duplicate name, rejecting enrollment. Help

### ISSUE THREAD

**Issue by hexclann** [wazuh/wazuh#13580]
### Discussed in https://github.com/wazuh/wazuh/discussions/13571

<div type='discussions-op-text'>

<sup>Originally posted by **hexclann** May 24, 2022</sup>
Hello, I'm running Wazuh on Ubuntu, I'm getting an error `Duplicate name, rejecting enrollment...` when I try to install the agent twice. I have set the configuration as indicated in https://github.com/wazuh/wazuh/issues/3674. But no luck
My setup information:

#### Wazuh-manager:
v4.3.1
Ubuntu 20.04 LTS
16GB RAM
AMD64 architecture
Running in Digitalocean droplet

#### Wazuh-agent:
v4.3.1
Ubuntu 20.04 LTS
1GB RAM
AMD64 architecture
Running in Digitalocean droplet

#### Manager logs:
```
...
2022/05/24 14:54:02 wazuh-authd: INFO: New connection from 64.x.x.x
2022/05/24 14:54:02 wazuh-authd: INFO: Received request for a new agent (ubuntu-s-1vcpu-1gb-intel-blr1-01) from: 64.x.x.x
2022/05/24 14:54:02 wazuh-authd: WARNING: Duplicate name 'ubuntu-s-1vcpu-1gb-intel-blr1-01', rejecting enrollment. Agent '002' key already exists on the manager.
...
```

#### Agent logs:

```
...
2022/05/24 09:48:13 wazuh-agentd: INFO: Requesting a key from server: test.example.com
2022/05/24 09:48:13 wazuh-agentd: INFO: No authentication password provided
2022/05/24 09:48:13 wazuh-agentd: INFO: Using agent name as: ubuntu-s-1vcpu-1gb-intel-blr1-01
2022/05/24 09:48:13 wazuh-agentd: INFO: Waiting for server reply
2022/05/24 09:48:13 wazuh-agentd: ERROR: Duplicate agent name: ubuntu-s-1vcpu-1gb-intel-blr1-01 (from manager)
2022/05/24 09:48:13 wazuh-agentd: ERROR: Unable to add agent (from manager)
...
```

#### Manager auth config

```
<auth>
    <disabled>no</disabled>
    <port>40272</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>no</use_password>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
 </auth>
```

The ports are changed and updated in the agent config. I can see the new agents in the dashboard but unable to register an existing agent. How can I make the manager register an already existing agent by discarding the old key?</div>

**Comment by Selutario** [comment]
Hello @hexclann,

As described in the warning, it is not possible to register a new agent if its name is identical to another already registered. There are multiple ways to avoid/fix this. I list some of them below:

### Option A. Delete the existing agent
There is already a registered agent with the name `ubuntu-s-1vcpu-1gb-intel-blr1-01`. However, if you no longer need it or you want to re-register it, you should delete it in the first place from the manager. You can do that in different ways.

#### 1. Using the Wazuh API
You can use the Wazuh API to remove an agent based on a given name. To do this, you will need to obtain a token as explained on the [Getting started - RESTful API](https://documentation.wazuh.com/current/user-manual/api/getting-started.html) page of the documentation and use the [DELETE /agents](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.delete_agents) endpoint with the parameters shown below:
> DELETE /agents?agents_list=all&status=all&older_than=0s&name=ubuntu-s-1vcpu-1gb-intel-blr1-01

If all goes well, you should see a response similar to this:
```JSON
{
  "data": {
    "affected_items": [
      "001"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were deleted",
  "error": 0
}
```

Check this out to see another example: [Remove agents using the Wazuh API
](https://documentation.wazuh.com/current/user-manual/agents/remove-agents/restful-api-remove.html)

#### 2. Remove agent using the CLI
You could run this command in your Wazuh Manager to list all your registered agents: 
```
/var/ossec/bin/manage_agents  -l 
```

And then delete the one you need using its ID:
```
/var/ossec/bin/manage_agents -r 003
```

### Option B. Set a different name in the enrollment configuration
This option consists of your new agent registering with auto-enrollment using a different name. To achieve this, you will need to add a `<name></name>` tag with a different name into the `enrollment` section of your agent's `ossec.conf`.
```XML
    <client>
        ...
        <enrollment>
            <agent_name>EXAMPLE_NAME</agent_name>
            ...
        </enrollment>
    </client>
```

Take a look at this documentation page if you need information on how to do it in any OS: [Enrollment via agent configuration](https://documentation.wazuh.com/current/user-manual/agent-enrollment/via-agent-configuration/index.html)

### Option C. Register the agent manually
The last option is to register the agent manually, specifying a different name from the one that already exists. To do this, you'll need to run something similar to this on your agent (using your own values)
```
/var/ossec/bin/agent-auth -m <manager_IP> -A <agent_name>
```

You can find more information about `agent-auth` binary here: [agent-auth - Tools](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-auth.html). You can also see other alternative ways to register your agent here: [Wazuh agent enrollment](https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html).

**Comment by fevtutor-admin** [comment]
I am also experiencing same error on Ubuntu but windows wazuh  agent registered and connected successfully

**Comment by hexclann** [comment]
Hello @Selutario I tried removing the agents using Wazuh CLI:

I followed these steps:

```
root@test:~# /var/ossec/bin/manage_agents  -l

Available agents:
   ID: 003, Name: centos, IP: any
   ID: 004, Name: W2016, IP: any
   ID: 010, Name: W2019, IP: any
   ID: 011, Name: ubuntu-s-1vcpu-1gb-intel-blr1-01, IP: any
```

When I run this command there was a DEBUG message in the manager saying that unable to remove agent DB:

```
2022/05/25 15:02:18 wazuh-authd[245339] local-server.c:153 at run_local_server(): DEBUG: Empty message from local client.
2022/05/25 15:02:18 wazuh-authd[245339] local-server.c:457 at local_remove(): DEBUG: local_remove(id='011', purge=0)
2022/05/25 15:02:18 wazuh-authd[245339] local-server.c:465 at local_remove(): INFO: Agent '011' (ubuntu-s-1vcpu-1gb-intel-blr1-01) deleted (requested locally)
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:808 at run_writer(): DEBUG: Dumping changes into disk.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:830 at run_writer(): DEBUG: [Writer] OS_WriteKeys(): 215 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:840 at run_writer(): DEBUG: [Writer] OS_WriteTimestamps(): 123 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:875 at run_writer(): DEBUG: [Writer] Performing delete([011] ubuntu-s-1vcpu-1gb-intel-blr1-01).
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:880 at run_writer(): DEBUG: [Writer] delete_agentinfo(): 230 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:885 at run_writer(): DEBUG: [Writer] OS_RemoveCounter(): 24 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:890 at run_writer(): DEBUG: [Writer] OS_RemoveAgentGroup(): 61 µs.
2022/05/25 15:02:18 wazuh-authd[245339] wdb_global_helpers.c:908 at wdb_remove_agent(): DEBUG: Unable to remove agent DB: 11 - ubuntu-s-1vcpu-1gb-intel-blr1-01
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:897 at run_writer(): DEBUG: [Writer] wdb_remove_agent(): 514 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:903 at run_writer(): DEBUG: [Writer] wdbc_query_ex(): 41 µs.
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:914 at run_writer(): DEBUG: [Writer] Inserted agents: 0
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:915 at run_writer(): DEBUG: [Writer] Removed agents: 1
2022/05/25 15:02:18 wazuh-authd[245339] main-server.c:916 at run_writer(): DEBUG: [Writer] Loop: 3 ms.
2022/05/25 15:02:24 wazuh-authd[245339] main-server.c:591 at run_dispatcher(): INFO: New connection from x.x.x.x
2022/05/25 15:02:24 wazuh-authd[245339] main-server.c:624 at run_dispatcher(): DEBUG: Request received: <OSSEC A:'ubuntu-s-1vcpu-1gb-intel-blr1-01' G:'default' K:'44e47df886c0dbc064a008467f64002dd305c4d6'

```

After the agent is removed, I restarted the wazuh-agent and the enrollment is rejected again.

```
2022/05/25 15:10:19 wazuh-authd[301124] auth.c:106 at w_auth_parse_data(): INFO: Received request for a new agent (ubuntu-s-1vcpu-1gb-intel-blr1-01) from: x.x.x.x
2022/05/25 15:10:19 wazuh-authd[301124] auth.c:144 at w_auth_parse_data(): DEBUG: Group(s) is: default
2022/05/25 15:10:19 wazuh-authd[301124] auth.c:313 at w_auth_validate_data(): WARNING: Duplicate name 'ubuntu-s-1vcpu-1gb-intel-blr1-01', rejecting enrollment. Agent '012' key already exists on the manager.
```

I tried uninstalling and installing the wazuh-agent but I'm getting the same error.

**Comment by Selutario** [comment]
Hello hexclann,

There are some strange things that we should review. In the first place, check the owner and permissions of the databases to see if it could be related to the `Unable to remove agent DB` error. To do it, run this in your manager and paste the output here: 
```
ls -lh /var/ossec/queue/db/
```

Regarding this comment:

> I tried uninstalling and installing the wazuh-agent but I'm getting the same error.

Please note that the manager won't allow two agents with the same name. If there is an agent registered and, due to any error, it could not be deleted in the manager, the new agent won't connect as long as it uses the same name as the one registered. As a consequence, I would say that (in this case) the problem is not in the agent but in the manager.

Now you can choose one of these two things:
- Option A: Try to unregister/delete the agent again in the manager.
- Option B: Import the agent key from the manager to the agent.

### Option A: Try to unregister/delete the agent again in the manager
You can try to remove the agent again following the same steps that you mentioned [here](https://github.com/wazuh/wazuh/issues/13580#issuecomment-1137037322). You could also try to remove the agent using the API as I explained in my [first message](https://github.com/wazuh/wazuh/issues/13580#issuecomment-1136818566). 

If possible, run the following in the manager right after deleting it to see if it's indeed gone from the `client.keys` file (which contains all registered agents). Make sure nothing is returned:
```
 cat /var/ossec/etc/client.keys | grep ubuntu-s-1vcpu-1gb-intel-blr1-01
```

If the above command doesn't return anything right after deleting the agent on the manager, it means it has been deleted successfully and the next enrollment attempt should be successful. In such a case, run this on your problematic agent and pay attention to see if there are any errors. Let me know if there are:
```
tail -f /var/ossec/logs/ossec.log
```

### Option B: Import the agent key from the manager to the agent.
If the agent was not deleted, instead of trying to delete/unregister it again, you can import that key to your new agent. To do it, get the agent ID again running this in your manager:
```
/var/ossec/bin/manage_agents -l | grep ubuntu-s-1vcpu-1gb-intel-blr1-01
```
Now export its key with this command. Replace `<agent_id>` with the one you got:
```
/var/ossec/bin/manage_agents -e <agent_id>
```

Something similar to this should be printed. Copy the key:
```
Agent key information for '001' is:
MDAxIDE4NWVlNjE1Y2YzYiBhbnkgMGNmMDFiYTM3NmMxY2JjNjU0NDAwYmFhZDY1ZWU1YjcyMGI2NDY3ODhkNGQzMjM5ZTdlNGVmNzQzMGFjMDA4Nw==
```

Go to your agent and run this, replacing `<copied_key>` with your own:
```
/var/ossec/bin/manage_agents -i <copied_key>
```

For instance:
```
/var/ossec/bin/manage_agents -i MDAxIDE4NWVlNjE1Y2YzYiBhbnkgMGNmMDFiYTM3NmMxY2JjNjU0NDAwYmFhZDY1ZWU1YjcyMGI2NDY3ODhkNGQzMjM5ZTdlNGVmNzQzMGFjMDA4Nw==
```

And finally, restart the agent and check the logs to see if everything works fine:
```
service wazuh-agent restart 
tail -f /var/ossec/logs/ossec.log
```

**Comment by hexclann** [comment]
DB permission:
```
root@test:~# ls -lh /var/ossec/queue/db/
total 4.2M
srw-rw---- 1 wazuh wazuh    0 May 25 15:09 wdb
-rw-r----- 1 wazuh wazuh  56K May 25 16:18 global.db
-rw-r----- 1 wazuh wazuh 4.1M May 25 16:34 000.db
```

> Please note that the manager won't allow two agents with the same name.

I'm not trying to add multiple agents with same name. I have removed the agent so the manager should register the agent (even if it is having the same name) next time right?

> If possible, run the following in the manager right after deleting it to see if it's indeed gone from the client.keys file (which contains all registered agents). Make sure nothing is returned:

I have verified that the agent key was deleted when I removed the agent from the CLI.

I'm unable to debug the problem because the manager is refusing to register the agent even after it is removed

**Comment by fevtutor-admin** [comment]
> It's strange, you should have a database for each successfully **connected** (not only registered) agent. In your case you only have a DB for the 000 agent (the manager itself), but not for other agents even when, as you said [here](https://github.com/wazuh/wazuh/issues/13580#issuecomment-1136920617), some of your agents are correctly connected, aren't they?.
Yes only windows agent registered and working successfully. , did not able to register agent on ubunut linux and Oracle linux OS. 

> 
I guess not, but just to make sure, do you have a Wazuh cluster setup?
no Wazuh server  is running  on single node & Wazhu index serves are on  cluster setup (3 nodes)

![image](https://user-images.githubusercontent.com/93752513/170284942-5f6e9129-410e-43e6-986a-1a70c50e342a.png)
![image](https://user-images.githubusercontent.com/93752513/170285158-a0f9962a-f619-4a15-8b57-6f5e3005fef1.png)

**Comment by hexclann** [comment]
> some of your agents are correctly connected, aren't they?.

Yes, but I can connect the agent via IP only but not the domain name. If I try to install the agent via IP I don't get any error. 
However the Windows endpoint can connect to the manager without any issue (via IP and domain).

> I guess not, but just to make sure, do you have a Wazuh cluster setup?

No, I'm using wazuh with my existing ELK setup since v4.0.x. It's not a cluster setup.

**Comment by manc74** [comment]
I'm also seeing the same on all but one Ubuntu boxes (no known difference between them). Windows boxes on the same network connect and register fine.

**Comment by Selutario** [comment]
Hi hexclann,

I've just tested the `auth`/`client` configurations you've shared [here](https://github.com/wazuh/wazuh/issues/13580#issuecomment-1138179266) and it seems correct. At least in my case it worked fine.

Regarding the enrollment rejected log: this part of the message means that the manager, after comparing each name in the `client.keys` with the one offered by the agent, has found that said name is already registered.
```
Duplicate name 'ubuntu-s-1vcpu-1gb-intel-blr1-01', rejecting enrollment.
```

While this other part means that the hash of the 012 agent line in the `client.keys` is the same as the hash of the only line of the agent's `client.keys`:
```
Agent '012' key already exists on the manager.
```

I'm talking about all this with my team. They do not find any explanation at the moment, beyond that perhaps something is being truncated.

Could you please share with us the full line in the manager's `/var/ossec/etc/client.keys` for the agent `ubuntu-s-1vcpu-1gb-intel-blr1-01` (previously it was ID 012 but now it might be different if you've continued testing) and the full line (the only one actually) in the `/var/ossec/etc/client.keys` of the agent itself?

**Comment by HerrStinson** [comment]
I think I may have the same problem, on our freshly installed Wazuh 4.3.1 instance (clustered with one master, 3 nodes ES) installed on Rocky Linux 8 all Windows agents register and report fine. However I am unable to add any of our Linux machines as agents (CentOS7, CentOS8, Rocky Linux 8, Wazuh agents installed from the official yum repo) to the system, they all register but fail to add due to duplicate names.
```
2022/05/25 17:41:05 wazuh-execd: INFO: Started (pid: 4133768).
2022/05/25 17:41:06 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/05/25 17:41:06 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2022/05/25 17:41:06 wazuh-agentd: INFO: Version detected -> Linux |lnxsrv002 |4.18.0-348.12.2.el8_5.x86_64 |#1 SMP Wed Jan 19 17:53:40 UTC 2022 |x86_64 [Rocky Linux|rocky: 8.5 (Green Obsidian)] - Wazuh v4.3.1
2022/05/25 17:41:06 wazuh-agentd: INFO: Started (pid: 4133780).
2022/05/25 17:41:06 wazuh-agentd: INFO: Requesting a key from server: wazuh.fqdn.address
2022/05/25 17:41:06 wazuh-agentd: INFO: No authentication password provided
2022/05/25 17:41:06 wazuh-agentd: INFO: Using agent name as: lnxsrv002
2022/05/25 17:41:06 wazuh-agentd: INFO: Waiting for server reply
2022/05/25 17:41:06 wazuh-agentd: INFO: Valid key received
2022/05/25 17:41:06 wazuh-agentd: INFO: Waiting 20 seconds before server connection
2022/05/25 17:41:07 wazuh-syscheckd: INFO: Started (pid: 4133795).
.
.
2022/05/25 17:41:07 wazuh-syscheckd: INFO: (6000): Starting daemon...
.
.
2022/05/25 17:41:08 wazuh-logcollector: INFO: Started (pid: 4133808).
2022/05/25 17:41:08 wazuh-modulesd: INFO: Started (pid: 4133823).
2022/05/25 17:41:08 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2022/05/25 17:41:08 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2022/05/25 17:41:08 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2022/05/25 17:41:08 sca: INFO: Module started.
2022/05/25 17:41:08 wazuh-modulesd:control: INFO: Starting control thread.
2022/05/25 17:41:08 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2022/05/25 17:41:08 sca: INFO: Starting Security Configuration Assessment scan.
2022/05/25 17:41:08 wazuh-modulesd:syscollector: INFO: Module started.
2022/05/25 17:41:08 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/05/25 17:41:08 sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_centos8_linux.yml': 'Check Centos 8 family platform'
2022/05/25 17:41:08 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/05/25 17:41:26 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2022/05/25 17:41:26 wazuh-agentd: INFO: Using AES as encryption method.
2022/05/25 17:41:26 wazuh-agentd: INFO: Trying to connect to server (wazuh.fqdn.address:1514/tcp).
2022/05/25 17:41:26 wazuh-agentd: ERROR: (1216): Unable to connect to 'wazuh.fqdn.address:1514/tcp': 'Network is unreachable'.
2022/05/25 17:41:36 wazuh-agentd: INFO: Trying to connect to server (wazuh.fqdn.address:1514/tcp).
2022/05/25 17:41:36 wazuh-agentd: ERROR: (1216): Unable to connect to 'wazuh.fqdn.address:1514/tcp': 'Network is unreachable'.
2022/05/25 17:41:46 wazuh-agentd: INFO: Trying to connect to server (wazuh.fqdn.address:1514/tcp).
2022/05/25 17:41:46 wazuh-agentd: ERROR: (1216): Unable to connect to 'wazuh.fqdn.address:1514/tcp': 'Network is unreachable'.
2022/05/25 17:41:56 wazuh-agentd: INFO: Trying to connect to server (wazuh.fqdn.address:1514/tcp).
2022/05/25 17:41:56 wazuh-agentd: ERROR: (1216): Unable to connect to 'wazuh.fqdn.address:1514/tcp': 'Network is unreachable'.
2022/05/25 17:42:06 wazuh-agentd: INFO: Trying to connect to server (wazuh.fqdn.address:1514/tcp).
2022/05/25 17:42:06 wazuh-agentd: ERROR: (1216): Unable to connect to 'wazuh.fqdn.address:1514/tcp': 'Network is unreachable'.
2022/05/25 17:42:06 wazuh-agentd: INFO: Requesting a key from server: wazuh.fqdn.address
2022/05/25 17:42:06 wazuh-agentd: INFO: No authentication password provided
2022/05/25 17:42:06 wazuh-agentd: INFO: Using agent name as: lnxsrv002
2022/05/25 17:42:06 wazuh-agentd: INFO: Waiting for server reply
2022/05/25 17:42:06 wazuh-agentd: ERROR: Duplicate agent name: lnxsrv002 (from manager)
2022/05/25 17:42:06 wazuh-agentd: ERROR: Unable to add agent (from manager)
```
These are the matching lines from the master's log
````
2022/05/25 17:41:06 wazuh-authd: INFO: New connection from 192.168.178.10
2022/05/25 17:41:06 wazuh-authd: INFO: Received request for a new agent (lnxsrv002) from: 192.168.178.10
2022/05/25 17:41:06 wazuh-authd: INFO: Agent key generated for 'lnxsrv002' (requested by any)
.
.
2022/05/25 17:42:06 wazuh-authd: INFO: New connection from 192.168.178.10
2022/05/25 17:42:06 wazuh-authd: INFO: Received request for a new agent (lnxsrv002) from: 192.168.178.10
2022/05/25 17:42:06 wazuh-authd: WARNING: Duplicate name 'lnxsrv002', rejecting enrollment. Agent '039' doesn't comply with the registration time to be removed.
````

The client.keys is populated, hashes match:
````
[root@lnxsrv002:~]#> sudo cat /var/ossec/etc/client.keys
039 lnxsrv002 any ae90f65bc86399cf4427149744d44d8e28ece08d6e4bb1122bed418e3bd5742d
````
````
[root@wazuh:~]#> sudo cat /var/ossec/etc/client.keys | grep lnxsrv002
039 lnxsrv002 any ae90f65bc86399cf4427149744d44d8e28ece08d6e4bb1122bed418e3bd5742d
````

**Comment by HerrStinson** [comment]
I just uninstalled the 4.3.1 agent, removed the agent from master, installed the 4.2.6 agent and it works, the agent registers and is added.

**Comment by HerrStinson** [comment]
Updating the agent to 4.3.1 again works.

**Comment by Selutario** [comment]
Hi guys,

It seems that the error could be related to this one, there are more users reporting the same:
- https://github.com/wazuh/wazuh/issues/13583

I would say that the common factor in all cases is the resolution of the FQDN. The core team is aware of the issue, you can keep an eye on the issue above in case there is any progress. I'll let you know here if we find anything new.

**Comment by snaow** [comment]
Wazuh team is now fully dedicated to addressing this issue, it is considered critical since it affects the agent connectivity.
A patch release will be published once we identify and solve the bug. 

We will update this issue with any progress, thanks all for the feedback/reports and the details on the previous comments, it helps a lot.

**Comment by snaow** [comment]
Please, take a look at the bug confirmed here: https://github.com/wazuh/wazuh/issues/13583#issuecomment-1141994629.
We think the bug is causing the _duplicate name_ scenario that has been reported in this issue. 

The agent is not able to resolve the DNS but it is still able to request a key from the manager, and just cause it is not able to connect, it will try to ask again for a new key causing a duplicated name error.

The release is being prepared as I write, it will be published in the next 3-4h (v4.3.3).


On a different page, feel free to take a look at the new enrollment force options added in v4.3.0: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#force

Looks like the default behavior is now different:
Regarding _Disconnected_ agents:
If the agent hasn't been disconnected for longer than 1h, it won't replace it but reject the new registration (if names are identical).

Regarding _Never Connected_ agents (agents enrolled but never connected):
If the agent was enrolled less than 1h from the new enrollment attempt, it will be rejected (duplicate names).

**Comment by hexclann** [comment]
@snaow Thanks for the quick fix from the Wazuh team and thanks everyone who jumped in on the issue and helping out with the information, logs. Currently 4.3.3 is a pre-release, is there will be a stable release soon?

**Comment by davidjiglesias** [comment]
@hexclann v.4.3.3 is already released

**Comment by snaow** [comment]
@hexclann I hope that the release fixed the problem you were facing.

Let us know if you have some time if it is working properly now, thanks.

**Comment by hexclann** [comment]
@snaow Everything is working on my side. Thanks for the help

**Comment by ExitTrance** [comment]
Hoping to just add something in case anyone runs into this on Version `4.2.5`.

Changing the protocol to be used for the connection to be UDP in the agent `ossec.conf` made it work for us.

**Comment by chandu2035** [comment]
It worked for me with below steps.

Use below command and remove the nodes which are reported as duplicate.
/var/ossec/bin/manage_agents

Once removed, restart the agent and it should work fine

Ref
https://documentation.wazuh.com/current/user-manual/agents/remove-agents/remove.html
