### ISSUE TITLE
Review RBAC ORM module docstrings

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#13584]
Right now, we have a lot of wrong function, class and method descriptions in the RBAC ORM module (`framework/wazuh/rbac/orm.py`).

https://github.com/wazuh/wazuh/blob/master/framework/wazuh/rbac/orm.py

This issue aims to review all of these docstrings and fix typos and wrong descriptions. Also, add missing docstrings and use the same docstring format for all descriptions. Note that there is a mix of Numpy, Google, etc. We should use the Numpy docstring standard. Consider adding types to function parameters to improve docstrings.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
We should also refactor some code that is outdated. For example:

add_policy function in orm.py
