### ISSUE TITLE
wazuh-control error using ps/procps

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#13585]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.1 | wazuh-control | Manager | Packages | RHEL 9 |

Hello team,

We have detected that RHEL 9 container `redhat/ubi9` doesn't come with `procps` package by default. It produce an error at this line https://github.com/wazuh/wazuh/blob/v4.3.1/src/init/wazuh-server.sh#L54

Could we remove such `ps` call? or should we include `procps` as dependency in our installation steps?

**Comment by vikman90** [comment]
Team, we have agreed that we are going to solve this issue with a change in the documentation: specify in the installation guide that the `procps` package (or whatever) should be installed as a dependency for the agent.

Also, open a child issue for the CICD team so they can put the dependency in:
- Installation assistant.
- Rest of the orchestration tools (Ansible, etc.)

**Comment by mjcr99** [comment]
## Issue update:
**(01/02/2024)** Issue moved to block until green light to merge PR and close it.
