### ISSUE TITLE
ossec-authd: DEBUG: Couldn't create some backup files.

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#1359]
Hi, team

There are some problem in my ossec-authd.

```
2018/09/20 16:55:29 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:29 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:29 ossec-authd: DEBUG: Couldn't create some backup files.
2018/09/20 16:55:29 ossec-authd: DEBUG: Couldn't create some backup files.
2018/09/20 16:55:29 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:30 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:30 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:31 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:31 ossec-authd: INFO: New connection from *IP*
2018/09/20 16:55:31 ossec-authd: INFO: Received request for a new agent (*hostname*) from: *IP*
2018/09/20 16:55:31 ossec-authd: INFO: Duplicated IP '*IP*' (2127126). Saving backup.
2018/09/20 16:55:31 ossec-authd: INFO: Agent key generated for '*hostname*' (requested by *IP*)
2018/09/20 16:55:32 ossec-authd: INFO: New connection from *IP*
2018/09/20 16:55:32 ossec-authd: INFO: Received request for a new agent (*hostname*) from: *IP*
2018/09/20 16:55:32 ossec-authd: INFO: Duplicated IP '*IP*' (2127127). Saving backup.
2018/09/20 16:55:32 ossec-authd: INFO: Agent key generated for '*hostname*' (requested by *IP*)
2018/09/20 16:55:33 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:33 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:34 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:34 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:34 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:35 ossec-authd: DEBUG: SSL Error (-1)
2018/09/20 16:55:35 ossec-authd: DEBUG: SSL Error (-1)
```

What should I do? If I could disable SSL check?  There is a lot new agent didn't finish register. 

In Master of cluster, ossec-authd reported it has  `INFO: Agent key generated for '*hostname*' (requested by *IP*)` but the client.keys didn't get the new key from Agent.

Best Regard,
Aklis Chen

**Comment by TJOSERAFAEL** [comment]
Hi @iAklis ,

can you please tell us the **Wazuh manager** version and **Wazuh agent** version that you are using?
Are the agents windows agents?
The ssl error indicates that maybe the agent SSL protocol is obsolete, so it cant read the values received from the agent.

Best regards.

**Comment by iAklis** [comment]
Hi, @TJOSERAFAEL 

The manager is 3.6.2
```
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.6.2"
REVISION="3609"
DATE="Thu Sep 20 13:51:29 CST 2018"
TYPE="server"
```

And the agent is 3.0.0 but I upgrade it to 3.6.2(Agent) didn't work.

Best regard,
Aklis Chen

**Comment by Zenidd** [comment]
Hello @iAklis,

Sorry for the late reply!

Did you manage to solve your problem? Given the situation, updating the manager and agents seems a good option. 

Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi @iAklis,

I'm closing this ticket due to inactivity, i hope your problem has been solved! Don't hesitate to reopen this or a new one whenever you need it.
<br></br>
Regards,

Juan Pablo Sáez
