### ISSUE TITLE
Feature Request | Template to deploy Wazuh in Terraform

### ISSUE THREAD

**Issue by noxit0** [wazuh/wazuh#13598]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.1 | All | Manager/Agent | Terraform  | Any

We found ourselves in need of creating templates in order to deploy Wazuh in Terraform.

These templates should be able to deploy the central components in single-node and multi-node types of architectures.

Templates to deploy the Wazuh agent should be created as well.

Regards.

**Comment by teddytpc1** [comment]
Hi,
To perform this we should:
1. Develop 2 TF templates, one for each deployment.
  1.1. The Single-node template will have the Network related resources already created, so they will be imported as a DataSource. It will deploy the EC2 instance using a [user data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) script to download and execute the `Wazuh installation assistant`.
  1.2. The Multi-node template will also have the Network related resources already created, so they will be imported as a DataSource. It will deploy multiple EC2 instances with different types (as needed) within the same VPC. The Wazuh install will be performed manually using one of the available methods.
  
NOTE: it is not defined if the EC2 instances should be created using a private or public subnet. This deployment does not use a load balancer.

**Comment by davidjiglesias** [comment]
We are finally not approaching this development.
