### ISSUE TITLE
An error occurs when trying to list affected agents after deleting a group

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh#13593]
|Wazuh version| Wazuh version | Component|Install type|Install method|Platform|
|---|---|---|---|---|---|
| 4.3.1 | 40311 |Agent groups | Manager | Packages | CentOS-8 |

## Description

There is an error when deleting a group with `agents_groups ` tool. The error occurs after deleting the group when trying to show on the screen the agents that were affected

## Evidence

![image](https://user-images.githubusercontent.com/37776796/170563525-6a244873-8355-4e0a-84f7-5f1ac9604f77.png)

![image](https://user-images.githubusercontent.com/37776796/170564430-abdbcb31-5b61-432e-a76c-c7fe10cfa71b.png)

## Steps to reproduce

1. Create a group

> [root@centos-manager1 vagrant]# /var/ossec/bin/agent_groups -a -g test_groups -q
> Group 'test_groups' created.

2. List all groups

> [root@centos-manager1 vagrant]# /var/ossec/bin/agent_groups -l
> Groups (2):
>   default (0)
>   test_groups (0)
> Unassigned agents: 0.

3. Delete group

> [root@centos-manager1 vagrant]# /var/ossec/bin/agent_groups -r -g test_groups -q
> Internal error: 'affected_agents'

4. List all groups again

> [root@centos-manager1 vagrant]# /var/ossec/bin/agent_groups -l
> Groups (1):
>   default (0)
> Unassigned agents: 0.
> 

**Current result:** Internal error message
**Expected result:** a message that shows affected agents

Note: 
This Issue was reproduced in 4.4 but in 4.5 works properly

**Comment by vicferpoy** [comment]
Hello,

There is indeed a bug in the code:

https://github.com/wazuh/wazuh/blob/304b5910bce84c6a2f0910020e139d44cb896416/framework/scripts/agent_groups.py#L124-L128

At that point, the dictionary `dikt` is empty:

```python
affected_agents = data['dikt']['affected_agents']
```

We should be accessing `affected_agents` directly instead:

```python
affected_agents = data['affected_agents']
```
