### ISSUE TITLE
Possible false positive in Fedora 25

### ISSUE THREAD

**Issue by marciofoz** [wazuh/wazuh#136]
Hello!
I have this alert in Fedora 25 and believe this false positive may be linked with issue #56 

Host-based anomaly detection event (rootcheck).
Trojaned version of file '/usr/bin/grep' detected. Signature used: 'bash|givemer|/dev/' (Generic).

A whitelist option is available to exclude some files from check ?
Regards

grep --version
grep (GNU grep) 2.27

**Comment by snaow** [comment]
Hi @marciofoz,

You are right, this is related to issue https://github.com/wazuh/wazuh/issues/56.

Quoting @vikman90: 
> We looked into the Grep repository at git.savannah.gnu.org/cgit/grep.git and found the /dev/null string at file grep.c. That text was introduced on May 2nd and was released at version 2.26.

There is no option for whitelisting rootcheck entries, we will add it to our roadmap.

Thanks for the feedback, best regards,
Pedro.
