### ISSUE TITLE
Quick install script does not support Ubuntu 22.04

### ISSUE THREAD

**Issue by m-terlinde** [wazuh/wazuh#13609]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.1 | Quick install | - | Quick install | Ubuntu 22.04|

Dear team,

as per https://github.com/wazuh/wazuh-qa/issues/2803 and https://github.com/wazuh/wazuh/issues/13154 Ubuntu 22.04 seems to be supported by Wazuh.

Currently, the [compatibility matrix](https://documentation.wazuh.com/current/quickstart.html) does not list Ubuntu 22.04 and quick install script aborts with the error `The system is not supported, supported systems are: Red Hat Enterprise Linux 7, 8; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04`.

Is the documentation outdated or have I misinterpreted the mentioned issues?

Thanks,
Matthias

**Comment by rauldpm** [comment]
Hello @m-terlinde 

Regarding Ubuntu 22, yes, we carried out certain tests in the 4.3.0 release but currently we have detected some other problem (already reported by other users through our [Slack channel](https://wazuh.com/community/join-us-on-slack/)) with Filebeat when sending events. Note that the issues you referenced refer to Wazuh Server and Wazuh agent, the installation assistant installs the Wazuh server (manager), Filebeat, Wazuh indexer and Wazuh dashboard packages, so even though Ubuntu 22 can be used by Wazuh server or Wazuh agent, there are other components that have not been fully tested yet

We are currently in the process of adding this system to the list of our recommended systems by running tests on that system, for now, if you want to use the wizard on that system, you can use the -i option to skip that check.

Regards, Raúl.

**Comment by m-terlinde** [comment]
Thanks a lot for the info!

I missed somehow the `-i` option and just rewrote the check code to support Ubuntu 22.

At least for my installation everything works fine now.

I'll close the issue as I think you have it already on your roadmap.

Cheers and thanks,
Matthias
