### ISSUE TITLE
Review AWS error codes

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#13600]
| Affected integration |
|---|
| AWS |

## Description

During a new development we recently removed the AWS error code `10`, leaving a gap in our list of AWS error codes. We should review every exit and error codes available for our AWS module to determine whether they are necessary/useful or not while at the same time attempt to make it consistant with how the rest of our external integration modules handle their error codes.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

Reviewing the exit codes i found that the No. 2, related to SIGINT signal, was not throwing correctly.

Before:

```bash
root@wazuh:/# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-alb -t alb -s 2021-Dec-21 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
^CERROR: SIGINT received.
root@wazuh:/# echo $?
12
```

After:

```bash
root@wazuh:/# /var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-alb -t alb -s 2021-Dec-21 -p dev -d2
DEBUG: +++ Debug mode on - Level: 2
^CERROR: SIGINT received.
root@wazuh:/# echo $?
2
```

**Comment by nico-stefani** [comment]
# Issue Update

I will update the documentation in wazuh/wazuh-documentation#5570
