### ISSUE TITLE
Multigroups files are deleted and re-created

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13603]
|Wazuh version|Component|Install type
|---|---|---|
| <= 4.3 | Wazuh remoted | Manager |

## Description

Multigroup files are regenerated every 10 seconds. To do this, each file is deleted and created again (or at least, that's what is happening in practice).

The above has consequences in cluster environments with many multigroups. For instance, if in a master node with 2075 multigroups we count the total number of `merged.mg` files every 0.01 seconds, the result is different every time:
```
- 2074
- 2070
- 2075
- 2072
- 2074
```

The reason is that some of all those files are in the process of regeneration, which means that some of them were deleted just before being counted (and created again right after). 

The master node and the workers must have the same files. When the master counts its files, if some have just been deleted, it will ask the workers to delete those as well. However, 8 seconds later it starts a new iteration and counts its files again. At this point, many of the files that were deleted already exist again, but only on the master (the workers deleted it). Therefore, the master has to send them again. The steps would be:
1. There are 2000 `merged.mg` files (multigroups).
2. `Remoted` deletes some multigroups (regeneration). Now there are 1995 `merged.mg`.
3. Master reviews the files to sync (Local integrity, every 8 seconds). Workers should have 1995 files.
4. `Remoted` recreates the deleted files, there are 2000 `merged.mg` again.
4. Workers communicate with master, they have 2000 files.
5. Master asks the workers to delete those 5 files. Workers have 1995 `merged.mg`.
6. +8 seconds, master reviews its files again (Local integrity). There are 2000 files.
7. Workers communicate with master, they have 1995 files.
8. Master sends the 5 missing files to workers.

The above process repeats forever, causing the need to constantly sync files even when there are no changes.

The mechanism was improved in 4.4 and `merged.mg` are only recreated when there are actual changes, not every 10 seconds. However, a solution may be needed until then:
- https://github.com/wazuh/wazuh/issues/11054

**Comment by davidjiglesias** [comment]
This issue is being handled in #14733 and #14825
