### ISSUE TITLE
Extend FIM to detect PAN information

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#13613]
Hello team,

I'm opening this ticket to extend Wazuh FIM capabilities to detect PAN patterns as a feature request.

Storing card numbers in files is a widespread practice and we can leverage FIM to detect those numbers in the monitored files and help the users to increase visibility and security in their systems.

For instance, we can add the following option `check_pan=yes` and this will look for the pattern within the configured files. Also, this way it can be easily extended to the rest of the FIM options `restrict`, `ignore`, etc..

Regards,

Miguel Casares

**Comment by vikman90** [comment]
## Status

We need some more information before start a design proposal.
