### ISSUE TITLE
wazuh agent reports not showing on dashbord

### ISSUE THREAD

**Issue by ambadasjagtap2021** [wazuh/wazuh#13620]
### Discussed in https://github.com/wazuh/wazuh/discussions/13619

<div type='discussions-op-text'>

<sup>Originally posted by **ambadasjagtap2021** May 30, 2022</sup>
wazuh agent reports not showing on dashboard.
![Untitled](https://user-images.githubusercontent.com/102735215/171011645-4870cf66-c56f-4641-b006-dfd728ea7bde.png)

</div>

**Comment by jctello** [comment]
Closing as this is a duplicate of the inactive discussion: https://github.com/wazuh/wazuh/discussions/13619
