### ISSUE TITLE
[SSHD_CONFIG] validate time of LoginGraceTime

### ISSUE THREAD

**Issue by DevDorrejo** [wazuh/wazuh#13628]
|Wazuh version|Component|Install type|Install method|Platform|Monitored System|

| 4.3.1-rev | Dashboard | Manager | Packages | Ubuntu 20.04 | openSUSe Leap 15.3|

I am following the recommendation to hardening the sshd_config, but the validation LoginGraceTime like the value of time is not working.

the value on LoginGraceTime are: ## (default seconds), ##m (minuts)

but the system not validate no matter what i put 60 or 1m it said it failed.

i have to put 60s, with the "s" to be validated.

**Comment by jnasselle** [comment]
Hi @DevDorrejo ,

Thanks for reporting this. It seems to be the extra `s` at the end of the regex

https://github.com/wazuh/wazuh/blob/8ee2a5646a12d22bf662b2f59a19c12b4b8d0a4e/ruleset/sca/generic/sca_unix_audit.yml#L123

I'm going to create a PR to fix this.

Regards,
Nico
