### ISSUE TITLE
Wrong rule work

### ISSUE THREAD

**Issue by Regirv** [wazuh/wazuh#1363]
Wazuh does not work out the rule.
**Rele:**
```
<rule id="100007" level="11">
    <if_sid>5104</if_sid>
      <list field="hostname" lookup="match_key">etc/lists/snifserver-bl</list>
      <description>Interface entered in promiscuous(sniffing) mode ignored.</description>
  </rule>
```

**ossec-logtest:**
Sep 20 12:30:01 test01 kernel: device eth0 entered promiscuous mode

**Phase 1: Completed pre-decoding.
       full event: 'Sep 20 12:30:01 test01 kernel: device eth0 entered promiscuous mode'
       timestamp: 'Sep 20 12:30:01'
       hostname: 'test01'
       program_name: 'kernel'
       log: 'device eth0 entered promiscuous mode'

**Phase 2: Completed decoding.
       decoder: 'kernel'

**Phase 3: Completed filtering (rules).
       Rule id: '100007'
       Level: '11'
       Description: 'Interface entered in promiscuous(sniffing) mode ignored.'
**Alert to be generated.

**Wazuh:**
full_log: Sep 20 12:40:01 test01 kernel: device eth0 entered promiscuous mode
rule.description: Interface entered in promiscuous(sniffing) mode.
rule.id: 5104
rule.level: 8

What could be the problem?

**Comment by crolopez** [comment]
Hi @Regirv,

I haven't been able to replicate the issue applying your rule. I can see the alert in ossec-logtest and alerts.log:

```
** Alert 1537779532.77681: - local,syslog,sshd,
2018 Sep 24 10:58:52 test02->/tmp/e/local
Rule: 100007 (level 11) -> 'Interface entered in promiscuous(sniffing) mode ignored.'
Sep 20 12:30:01 test02 kernel: device eth0 entered promiscuous mode
```

Your case is very strange because ossec-logtest uses the same alert generation engine as Wazuh, so you should see the alert on both sides. Can you check if the list is compiled?

`<install_dir>/bin/ossec-makelists
`

What version of Wazuh are you using?

Best regards.

**Comment by crolopez** [comment]
Hi @Regirv,

I am going to close the issue for inactivity. Feel free to reopen it if necessary.

Best regards.
