### ISSUE TITLE
wazuh agent v4.3.1 cannot resolve wazuh manager domain name

### ISSUE THREAD

**Issue by houhuijian** [wazuh/wazuh#13652]
When I install wazuh agent v4.3.1 on the client, when I set the wazuh manager's address to the ip address, the connection is normal, but if I set the wazuh manager's address to the domain name on the wazuh agent, the wazuh agent can't connect to wazuh manager all the time. When I set /etc/hosts, the problem is still not solved. When I copy /etc/hosts to /var/ossec/etc/hosts, the problem still exists. After I commented all the client configuration of the enrollment setting in the v4.3.1 client configuration part, there is no problem using the domain name and ip address to connect. Please seniors look at the reason and how to solve it

**Comment by Selutario** [comment]
I'm closing this issue since [Wazuh v4.3.3](https://github.com/wazuh/wazuh/releases/tag/v4.3.3), which fixes the bug, was released yesterday.

Feel free to reopen it or create a new one if you encounter any problems.
