### ISSUE TITLE
Autoenrollment not working in OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#13661]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.3 | Agent | Install | OpenSUSE Tumbleweed |

### Description

When installing Wazuh agent v4.3.3 on OpenSUSE Tumbleweed, the autoenrollment process is failing. This problem seems to be related with the SSL authentication.

Steps to reproduce:

- Deploy an OpenSUSE Tumbleweed machine. For this, I used the following vagrant box:

> opensuse/Tumbleweed.x86_64

- Install the Wazuh agent. For this, I ran the following command:

> WAZUH_MANAGER="manager-ip" zypper install wazuh-agent-4.3.3-1

- Start the Wazuh agent:

> systemctl start wazuh-agent

- Check the agent log. This is the error that appears:

> 2022/06/01 04:03:19 wazuh-agentd: INFO: Requesting a key from server: 10.0.2.25
> 2022/06/01 04:03:19 wazuh-agentd: INFO: No authentication password provided
> 2022/06/01 04:03:19 wazuh-agentd: ERROR: (4104): Invalid hostname: 'localhost'.

- Check the manager log. This is the error that appears:

> 2022/05/31 23:03:19 wazuh-authd: INFO: New connection from 10.0.2.49
> 2022/05/31 23:03:19 wazuh-authd: ERROR: SSL Error (0)

#### Note

This problem isn't present in Wazuh agent v4.2.7, so it seems to be a new bug introduced in v4.3.

**Comment by snaow** [comment]
Please, confirm that it is failing in 4.3 and not in 4.2, in that case, this will be fixed in 4.3.5.

**Comment by snaow** [comment]
`localhost` is a reserved word that can't be used as an Agent name. That's the reason is not doing the enrollment. Closing.
