### ISSUE TITLE
Merged files generation optimization - Backport to 4.3

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#13675]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.x | wazuh-remoted | Manager | Packages/Sources | Linux |

### Description

Due to some performance issues in Wazuh v4.3 due to the multigroup generation mechanism, it is necessary to backport the changes introduced in #11054, #8593 and #13071 in the 4.3 branch.

### Branch

https://github.com/wazuh/wazuh/tree/backport_merged_optimization

**Comment by jmv74211** [comment]
## QA review

- **Type**: Manual testing
- **Status**: Approved  🟢 
- **Testing issue**: https://github.com/wazuh/wazuh-qa/issues/2967
- **Comments**:  Nothing to highlight
