### ISSUE TITLE
Building Wazuh 4.3 version using USE_GEOIP flag fails.

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#13680]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | GEOIP | Manager | Sources | Ubuntu 20 |

## Description
Building wazuh 4.x version using USE_GEOIP flag fails. 
Running `make TARGET=server USE_GEOIP=yes -j4` command it fails looking for `-lGeoIP` flag.
Wazuh version affected from 4.0 to 4.3.3

As documentation mentions, one of the [available flags](https://documentation.wazuh.com/current/development/makefile.html?highlight=use_geoip#available-flags) to build Wazuh server is `USE_GEOIP`, this functionlity allows complete fields `srcgeoip` and `dstgeoip` with geoip information, as country and city name.

```
root@VirtualBox:/home/user/wazuh/src# make TARGET=server USE_GEOIP=yes -j4
checkmodule -M -m -o selinux/wazuh.mod selinux/wazuh.te
semodule_package -o selinux/wazuh.pp -m selinux/wazuh.mod
make build_sysinfo build_shared_modules build_syscollector
make[1]: Entering directory '/home/tomas/wazuh/wazuh/src'
    CC libwazuhext.so
/usr/bin/ld: missing --end-group; added as last command line option
/usr/bin/ld: cannot find -lGeoIP
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1671: libwazuhext.so] Error 1
make[1]: Leaving directory '/home/tomas/wazuh/wazuh/src'
make: *** [Makefile:705: server] Error 2

```
In case of this functionality will be deprecated, documentation should be updated.

- Makefile options, Available flags [link](https://documentation.wazuh.com/current/development/makefile.html?highlight=use_geoip#available-flags)
- Alerts, use_geoip [link](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html?highlight=use_geoip#use-geoip)
- Rule Syntax, srcgeoip and dstgeoip [link](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=dstgeoip#dstgeoip)

Related issues: [4053](https://github.com/wazuh/wazuh/issues/4053)

**Comment by juliancnn** [comment]
Hi @cborla 

it looks like you forgot to install the dependency.
```
/usr/bin/ld: missing --end-group; added as last command line option
/usr/bin/ld: cannot find -lGeoIP
```
Ubuntu:
```bash
apt install libgeoip-dev
```
Anyway, geoip is broken since this PR 3 weeks ago:

Fixing the use of the overwrite rules for Analysisd #13439
```cmake
    CC analysisd/active-response-test.o
    CC analysisd/fts-test.o
    CC analysisd/lists_list-test.o
    CC analysisd/config-test.o
    CC analysisd/cleanevent-test.o
    CC analysisd/asyscom-test.o
    CC analysisd/logtest-test.o
    CC analysisd/eventinfo-test.o
analysisd/rules_list.c: In function ‘OS_AddRuleInfo’:
analysisd/rules_list.c:323:34: error: ‘ruleinfo’ undeclared (first use in this function); did you mean ‘RuleInfo’?
  323 |             w_free_expression_t(&ruleinfo->srcgeoip);
      |                                  ^~~~~~~~
      |                                  RuleInfo
```
This:

https://github.com/wazuh/wazuh/blob/fd082f6455a47f7a3844ca3e06e90e8b21884fd9/src/analysisd/rules_list.c#L322-L327

Should be:
```cpp
#ifdef LIBGEOIP_ENABLED
            w_free_expression_t(&r_node->ruleinfo->srcgeoip);
            r_node->ruleinfo->srcgeoip = newrule->srcgeoip;
            w_free_expression_t(&r_node->ruleinfo->dstgeoip);
            r_node->ruleinfo->dstgeoip = newrule->dstgeoip;
#endif
```

**Comment by Selutario** [comment]
Hi guys,

By the way, we opened an issue in wazuh-documentation so that the necessary dependencies are specified, both for this and for other installation flags:
- https://github.com/wazuh/wazuh-documentation/issues/5063
