### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - E2E UX tests - Wazuh dashboard

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13693]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Wazuh Dashboard                                           |
| **Category**            | Installation                                           |
| **Main E2E UX test issue**  | https://github.com/wazuh/wazuh/issues/13670                                          |
| **Release candidate #** | RC1                                          |

## Installation procedure
- Wazuh Indexer
  - [Step by step](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html)
- Wazuh Server
  - [Step by step](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html)
- Wazuh Dashboard
  - [Step by step](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html)
- Wazuh Agent
  - [Installing Wazuh agents](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html)

Manager's OS coverage
- Centos 7 @pereyra-m 
- Ubuntu 22.04LTS @HanesSciarrone 
- Centos 8 @MiguelazoDS 
- Amazon Linux 2 @jnasselle 

Agent OS coverage
- Linux @pereyra-m 
- macOS @HanesSciarrone 
- Windows @MiguelazoDS 
- Solaris 10/11 @jnasselle 

## Test description
Best efford to test Wazuh dashboard package. Think critically and at least review/test:
- Wazuh dashboard package specs
- Dashboard package size
- Dashboard package metadata (description)
- Dashboard package digital signature
- Installed files location, size and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)
- Installed service (test that it works correctly)
- Wazuh Dashboard logs when installed
- Wazuh Dashboard configuration (Try to find anomalies compared with 4.2.5)
- Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer
- Basic browsing throguh the WUI
- Basic experience with WUI performance.
Anything else that could have been overlooked when creating the new package"

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :red_circle:  | Install - Basic browsing throguh the WUI | Functional | https://github.com/wazuh/wazuh-kibana-app/issues/4220|
| :red_circle:  | Install - Wazuh Dashboard - Logon design and favicons  | UX | https://github.com/wazuh/wazuh-packages/issues/1620 |
| :yellow_circle:  | Install - Adding the Wazuh repository (APT) | Usability | https://github.com/wazuh/wazuh-documentation/issues/5297 |
| :yellow_circle:  | Install - Checking Wazuh Dashboard logs | Usability | https://github.com/wazuh/wazuh-kibana-app/issues/4203 |
| :yellow_circle:  | Install - Wazuh indexer  | UX | https://github.com/wazuh/wazuh/issues/12945 |
| :yellow_circle:  | Install - Wazuh Dashboard - Deploy a new agent  | UX | https://github.com/wazuh/wazuh-kibana-app/issues/4222 |
| :yellow_circle:  | Install - Wazuh Dashboard - Configuring the Wazuh Dashboard  | UX | https://github.com/wazuh/wazuh-documentation/issues/5317|
| :yellow_circle:  | Install - Wazuh Dashboard - Configuring the Wazuh Dashboard  | UX | https://github.com/wazuh/wazuh-kibana-app/issues/4225|
| :yellow_circle:  | Install - Wazuh Dashboard - Basic experience with WUI performance  | UX | https://github.com/wazuh/wazuh-kibana-app/issues/4226 |
| :yellow_circle:  | Install - Wazuh Dashboard - Basic browsing throguh the WUI  | UX | https://github.com/wazuh/wazuh-documentation/issues/5319 |
| :yellow_circle:  | Install - Wazuh Dashboard - Wazuh Dashboard logs when installed  | UX | https://github.com/wazuh/wazuh/issues/13774 |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @Dwordcito 
- [ ] @davidjiglesias

**Comment by pereyra-m** [comment]
## E2E UX tests: Centos 7 

These are the results of the manual tests for the Wazuh Dashboard on a Centos 7 host.

### Wazuh Indexer Installation

### Wazuh Server Installation

### Wazuh Dashboard Installation 

### Installed service (test that it works correctly)

### Wazuh Dashboard logs when installed

### Wazuh Dashboard configuration (Try to find anomalies compared with 4.2.5)

### Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer

### Basic browsing throguh the WUI

### Basic experience with WUI performance

**Comment by jnasselle** [comment]
# E2E UX tests - Wazuh Dashboard :large_blue_circle:
Environment
- Wazuh Manager on Amazon Linux 2 (https://app.vagrantup.com/gbailey/boxes/amzn2)
- Wazuh Agent on
  - Solaris 10
  - Solaris 11
# Steps
## Wazuh dashboard package specs :large_blue_circle: 
## Dashboard package size :large_blue_circle: 
## Dashboard package metadata (description) :large_blue_circle: 
## Dashboard package digital signature :large_blue_circle: 
## Installed files location, size and permissions :large_blue_circle: 
## Installation footprint :large_blue_circle: 
## Installed service :large_blue_circle: 
## Wazuh Dashboard logs when installed :large_blue_circle: 
## Wazuh Dashboard configuration :large_blue_circle: 
## Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer :large_blue_circle: 
## Basic browsing throguh the WUI :large_blue_circle: 
## Basic experience with WUI performance. :large_blue_circle:

**Comment by MiguelazoDS** [comment]
# E2E UX tests: 

## Environment 

- Wazuh manager: Centos 8
- Wazuh agent: Windows 11 

![14](https://user-images.githubusercontent.com/13010397/171959878-7df21752-3c7a-44dc-9404-028e14ee6e49.png)
![15](https://user-images.githubusercontent.com/13010397/171960251-7f1c666d-99dd-4145-8784-68319a7d78dd.png)

## Wazuh Indexer Installation

Testing wazuh-indexer is working
![6](https://user-images.githubusercontent.com/13010397/171959488-3e677db9-e60b-47cd-bf03-e15f834ac0b1.png)
![7](https://user-images.githubusercontent.com/13010397/171959489-880645eb-2bbe-461e-a400-47ba1ed022a9.png)

## Wazuh Server configuration

Wazuh manager service is working

Filebeat successfully installed
![8](https://user-images.githubusercontent.com/13010397/171959490-8062b1f9-9eb9-49b5-8c00-3e78dd65ac93.png)

## Wazuh Dashboard Installation 

![9](https://user-images.githubusercontent.com/13010397/171959491-10e79f32-c770-47c9-bf49-687585d32a42.png)
![11](https://user-images.githubusercontent.com/13010397/171959497-aa0524f8-4087-4a2a-965d-0914dd5cbee9.png)
![12](https://user-images.githubusercontent.com/13010397/171959499-9abe8f4c-3bdc-48a1-8e7b-87b984b15c0f.png)
![13](https://user-images.githubusercontent.com/13010397/171959500-961f9781-0b7f-42db-a8ad-910dc0063a29.png)

## Tests

### Wazuh dashboard package specs :large_blue_circle:
### Dashboard package size :large_blue_circle:
### Dashboard package metadata (description) :large_blue_circle:
### Dashboard package digital signature :large_blue_circle:
### Installed files location, size and permissions :large_blue_circle:
### Installation footprint :large_blue_circle:
### Installed service :large_blue_circle:
### Wazuh Dashboard logs when installed :large_blue_circle:
### Wazuh Dashboard configuration :large_blue_circle:
### Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer :large_blue_circle:
### Basic browsing throguh the WUI :large_blue_circle:
### Basic experience with WUI performance. :large_blue_circle:

**Comment by HanesSciarrone** [comment]
# E2E UX tests - Wazuh Dashboard

## Enviroment

- Wazuh manager: Ubuntu 22.04

![image](https://user-images.githubusercontent.com/58960358/171967548-1ad699d9-cc4c-447d-89cd-165dfa6b51cb.png)

- Wazuh agent: MacOS Mojave

## Wazuh indexer installation

<details>
<summary>step by step</summary>

1. Certificates creation

To certificates were generated with the following `script` and not using pre-release repository

```
curl -sO https://packages.wazuh.com/4.3/wazuh-certs-tool.sh
curl -sO https://packages.wazuh.com/4.3/config.yml
```
config.yml

![image](https://user-images.githubusercontent.com/58960358/171969719-e3254280-8aef-4b1e-9d2e-3c89ed6e5f9c.png)

![image](https://user-images.githubusercontent.com/58960358/171969759-02659a63-5559-43f2-950f-34d19fbc2674.png)


</details>
