### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - WPK upgrade tests

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#13696]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|https://github.com/wazuh/wazuh/issues/13669|4.3.4|RC1|[v4.3.4-rc1](https://github.com/wazuh/wazuh/tree/v4.3.1-rc1)|-|

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Tests

To evaluate this feature, it is necessary to test upgrading the agent and also the case when the upgrade fails (rollback). The `tree` command will be used to compare, before and after the upgrade/rollback process, and check that the presence, ownership and permissions of the files and directories are expected.

Wazuh versions to test (Upgrade to the current agent version):
### Linux

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----|------|---------------|------------------|
|CentOS 6|3.6|:white_circle: skipped | | | |
|CentOS 6|3.7|:white_circle: skipped | | | |
|CentOS 6|3.13.3|:white_circle: skipped | | | |
|CentOS 6|4.0.4|:white_circle: skipped | | | |
|CentOS 6|4.1.5|:white_circle: skipped | | | |
|CentOS 6|4.2.7|:white_circle: skipped | | | |
|CentOS 6|4.3.3|:white_circle: skipped | | | |
|CentOS 6|4.3.4|:white_circle: skipped | | | |
|CentOS 8|3.6|:white_circle: skipped | | | |
|CentOS 8|3.7|:white_circle: skipped | | | |
|CentOS 8|3.13.3|:white_circle: skipped | | | |
|CentOS 8|4.0.4|:white_circle: skipped | | | |
|CentOS 8|4.1.5|:white_circle: skipped | | | |
|CentOS 8|4.2.7|:green_circle: done |:green_circle: |:green_circle:|
|CentOS 8|4.3.3|:green_circle: done |:green_circle: |:green_circle:|
|CentOS 8|4.3.4|:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 20|3.6|:white_circle: skipped | | | |
|Ubuntu 20|3.7|:white_circle: skipped | | | |
|Ubuntu 20|3.13.3|:white_circle: skipped|  | | |
|Ubuntu 20|4.0.4|:white_circle: skipped|  | | |
|Ubuntu 20|4.1.5|:white_circle: skipped  |||  |
|Ubuntu 20|4.2.7|:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 20|4.3.3 |:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 20|4.3.4|:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 22|3.6|:white_circle: skipped | | | |
|Ubuntu 22|3.7|:white_circle: skipped | | | |
|Ubuntu 22|3.13.3|:white_circle: skipped|  | | |
|Ubuntu 22|4.0.4|:white_circle: skipped|  | | |
|Ubuntu 22|4.1.5|:white_circle: skipped  |||  |
|Ubuntu 22|4.2.7|:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 22|4.3.3 |:green_circle: done |:green_circle: |:green_circle:|
|Ubuntu 22|4.3.4|:green_circle: done |:green_circle: |:green_circle:|
|openSUSE Tumbleweed|3.6|:white_circle: skipped | | | |
|openSUSE Tumbleweed|3.7|:white_circle: skipped | | | |
|openSUSE Tumbleweed|3.13.3|:white_circle: skipped| || |
|openSUSE Tumbleweed|4.0.4|:white_circle: skipped| | ||
|openSUSE Tumbleweed|4.1.5|:white_circle: skipped| | ||
|openSUSE Tumbleweed|4.2.7|:green_circle: done |:green_circle: |:green_circle:|
|openSUSE Tumbleweed|4.3.3|:green_circle: done |:green_circle: |:green_circle:|
|openSUSE Tumbleweed|4.3.4|:green_circle: done |:green_circle: |:green_circle:|
|Amazon Linux 2|3.6|:white_circle: skipped | | | |
|Amazon Linux 2|3.7|:white_circle: skipped | | | |
|Amazon Linux 2|3.13.3|:white_circle: skipped| || |
|Amazon Linux 2|4.0.4|:white_circle: skipped| | ||
|Amazon Linux 2|4.1.5|:white_circle: skipped| | ||
|Amazon Linux 2|4.2.7| :green_circle: done | :green_circle: | :green_circle: | |
|Amazon Linux 2|4.3.3| :green_circle: done | :green_circle: | :green_circle: | 
|Amazon Linux 2|4.3.4| :green_circle: done | :green_circle: | :green_circle: |

### Windows

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----|------|---------------|------------------|
|Server 2008|3.6|:white_circle: skipped | | | |
|Server 2008|3.7|:white_circle: skipped | | | |
|Server 2008|3.13.3|:white_circle: skipped| || |
|Server 2008|4.0.4|:white_circle: skipped| | ||
|Server 2008|4.1.5|:white_circle: skipped| | ||
|Server 2008|4.2.7|:white_circle: skipped| || |
|Server 2008|4.3.3|:white_circle: skipped | |
|Server 2008|4.3.4|:white_circle: skipped | |
|Server 2012 R2|3.6|:white_circle: skipped | | | |
|Server 2012 R2|3.7|:white_circle: skipped | | | |
|Server 2012 R2|3.13.3|:white_circle: skipped| || |
|Server 2012 R2|4.0.4|:white_circle: skipped| | ||
|Server 2012 R2|4.1.5|:white_circle: skipped| | ||
|Server 2012 R2|4.2.7|:white_circle: skipped| || |
|Server 2012 R2|4.3.3|:white_circle: skipped | |
|Server 2012 R2|4.3.4|:white_circle: skipped | |
|Server 2016|3.6| :white_circle: skipped| | | |
|Server 2016|3.7| :white_circle: skipped| | | |
|Server 2016|3.13.3|:white_circle: skipped| || |
|Server 2016|4.0.4|:white_circle: skipped| | ||
|Server 2016|4.1.5|:white_circle: skipped| | ||
|Server 2016|4.2.7| :green_circle: done | :green_circle: | :green_circle: | |
|Server 2016|4.3.3| :green_circle: done | :green_circle: | :green_circle: | |
|Server 2016|4.3.4| :green_circle: done | :green_circle: | :green_circle: | |
|Server 2019|3.6|:white_circle: skipped | | | |
|Server 2019|3.7|:white_circle: skipped | | | |
|Server 2019|3.13.3|:white_circle: skipped| || |
|Server 2019|4.0.4|:white_circle: skipped| | ||
|Server 2019|4.1.5|:white_circle: skipped| | ||
|Server 2019|4.2.7|:green_circle: done |:green_circle: |:green_circle:|
|Server 2019|4.3.3|:green_circle: done |:green_circle: |:green_circle:|
|Server 2019|4.3.4|:green_circle: done |:green_circle: |:green_circle:|
|Windows 10|3.6| :white_circle: skipped| | | |
|Windows 10|3.7|:white_circle: skipped | | | |
|Windows 10|3.13.3|:white_circle: skipped| || |
|Windows 10|4.0.4|:white_circle: skipped| | ||
|Windows 10|4.1.5|:white_circle: skipped| | ||
|Windows 10|4.2.7| :green_circle: done | :green_circle:| :green_circle:|
|Windows 10|4.3.3| :green_circle: done | :green_circle: | :green_circle:|
|Windows 10|4.3.4| :green_circle: done | :green_circle: | :green_circle:|
|Server 2022|3.6|:white_circle: skipped | | | |
|Server 2022|3.7| :white_circle: skipped| | | |
|Server 2022|3.13.3|:white_circle: skipped| || |
|Server 2022|4.0.4|:white_circle: skipped| | ||
|Server 2022|4.1.5|:white_circle: skipped| | ||
|Server 2022|4.2.7|:green_circle: done | :green_circle: | :green_circle: | |
|Server 2022|4.3.3|:green_circle: done | :green_circle: | :green_circle: | |
|Server 2022|4.3.4|:green_circle: done | :green_circle: | :green_circle: | |

### macOS

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----------|--------|-------|------------------|
| Sierra |4.3.0|:white_circle: skipped || | | |
| Sierra |4.3.4|:white_circle: skipped || | | |
| Catalina |4.3.3| :green_circle: done | :green_circle: | :green_circle: | | |
| Catalina |4.3.4| :green_circle: done | :green_circle: | :green_circle: | | |
| Big Sur |4.3.0|:white_circle: skipped || | | |
| Big Sur |4.3.4| :white_circle: skipped|| | | |
| Monterey |4.3.3| :white_circle: skipped|| | | |
| Monterey |4.3.4|:white_circle: skipped || | | |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @vikman90

**Comment by JcabreraC** [comment]
# TEST: CentOS 8

## From Wazuh-Agent v4.2.7

###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting


[Download Report 4.2.7](https://github.com/wazuh/wazuh/files/8619342/report_4.2.6.zip)


## From Wazuh-Agent v4.3.3
###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

[Download Report 4.3.3](https://github.com/wazuh/wazuh/files/8619778/report_4.3.0.zip)

## From Wazuh-Agent v4.3.4
###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

[Download Report 4.3.4](https://github.com/wazuh/wazuh/files/8619778/report_4.3.0.zip)

**Comment by nmkoremblum** [comment]
# TEST: macOS Catalina

## From Wazuh-Agent v4.3.3

### UPGRADE FAIL

- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.

### UPGRADE OK

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.

### Results

**Comment by juliancnn** [comment]
# TEST: openSUSE Tumbleweed

## From Wazuh-Agent v4.2.7

###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting


## From Wazuh-Agent v4.3.3

###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

## From Wazuh-Agent v4.3.4

###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

**Comment by nmkoremblum** [comment]
# TEST: Windows Server 2016

## From Wazuh-Agent v4.2.7

### UPGRADE FAIL  
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.3.4

## From Wazuh-Agent v4.3.3

### UPGRADE FAIL  
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.3.4

## From Wazuh-Agent v4.3.4

### UPGRADE FAIL  
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.3.4

## Results

[ws16_results.zip](https://github.com/wazuh/wazuh/files/8846693/ws16_results.zip)

**Comment by nmkoremblum** [comment]
# TEST: Amazon 2

## From Wazuh-Agent v4.2.7

###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK 

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

## From Wazuh-Agent v4.3.3
###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

## From Wazuh-Agent v4.3.4
###  UPGRADE FAIL

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] ~Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)~
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] ~Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ 
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (DISABLED)

###  UPGRADE OK

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

**Comment by LucioDonda** [comment]
# TEST: Windows 10

## From Wazuh-Agent v4.2.7

### UPGRADE FAIL  
- [X] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [X] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.3.4

[Reports-4.2.7](https://github.com/wazuh/wazuh/files/8855775/4.2.7.zip)


## From Wazuh-Agent v4.3.3

### UPGRADE FAIL  
- [] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [] After the rollback the agent connects to the manager
- [] After reboot, the Wazuh-Agent starts and connects to the manager.
- [] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK

- [] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [] Wazuh service is started and the agent is connected to the manager.
- [] The version shown in the control panel is 4.3.4

Reports

## From Wazuh-Agent v4.3.4

### UPGRADE FAIL  
- [] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [] After the rollback the agent connects to the manager
- [] After reboot, the Wazuh-Agent starts and connects to the manager.
- [] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [] ~A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.~

### UPGRADE OK

- [] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [] Wazuh service is started and the agent is connected to the manager.
- [] The version shown in the control panel is 4.3.4

Reports

It is not a problem, but on successful updates we save the WPK file while on failed updates we do not.
