### ISSUE TITLE
Release 4.3.4 - Release Candidate 1 - E2E UX tests - Wazuh indexer

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#13700]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Wazuh indexer                                           |
| **Category**            | Installation                                           |
| **Main E2E UX test issue**  | https://github.com/wazuh/wazuh/issues/13670                                          |
| **Release candidate #** | RC1                                          |

## Installation procedure
Wazuh indexer:
- Installation: [Installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html)
- Type: - Single node
- OS: Amazon Linux 2

Wazuh server:
- Installation: [Installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html)
- Type: - Single node
- OS: Amazon Linux 2

Wazuh dashboard:
- Installation: [Installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/installation-assistant.html)
- OS: Amazon Linux 2

Wazuh agent:
- Installation: Wazuh WUI one-liner deploy IP GROUP (created beforehand)
- OS: Windows

## Test description
Best efford to test Wazuh indexer package. Think critically and at least review/test:
- Wazuh indexer package specs
- Indexer package size
- Indexer package metadata (description)
- Indexer package digital signature
- Installed files location, size and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)
- Installed services (test that services work well in the different OS)
- Wazuh indexer logs when installed
- Wazuh indexer templates and indices created
- Wazuh indexer configuration (e.g. replicas are expected to be zero by default, how many shards per index,...) Try to find anomalies compared with 4.2.5
- Wazuh indexer cluster node communication and configuration
- Experience when creating certificates, configuring cluster and sending events to the cluster
- Wazuh indexer cluster status
- Wazuh indexer packages uninstallation process

Anything else that could have been overlooked when creating the new packages

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :green_circle:  | [Wazuh indexer package specs](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1147705671) |  |  |
| :green_circle:  | [Indexer package size](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1147706282) |  |  |
| :green_circle:  | [Indexer package metadata (description)](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1147707674) |  |  |
| :green_circle:  | [Indexer package digital signature](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1147710111) |  |  |
| :green_circle:  | [Installed files location, size and permissions](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148301181) |  |  |
| :green_circle:  | [Installation footprint](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148302537) |  |  |
| :green_circle:  | [Installed services](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148302681) |  |  |
| :green_circle:  | [Wazuh indexer logs when installed](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148318310) |  |  |
| :green_circle:  | [Wazuh indexer templates and indices created](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148330282) |  |  |
| :green_circle:  | [Wazuh indexer configuration](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148330545) |  |  |
| :green_circle:  | [Wazuh indexer cluster node communication and configuration](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148330711) |  |  |
| :green_circle:  | [Experience when creating certificates, configuring cluster and sending events to the cluster](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148330927) |  |  |
| :green_circle:  | [Wazuh indexer cluster status](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148331106) |  |  |
| :green_circle:  | [Wazuh indexer packages uninstallation process](https://github.com/wazuh/wazuh/issues/13700#issuecomment-1148331352) |  |  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ]

**Comment by pepitoenpeligro** [comment]
# Wazuh Indexer Package Specs

**Comment by pepitoenpeligro** [comment]
# Indexer Package size

```yaml
Size        : 614 M
```

**Comment by pepitoenpeligro** [comment]
# Indexer package metadata (description)

```yaml
yum -C search wazuh-indexer
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
=========================================================================================== N/S matched: wazuh-indexer ===========================================================================================
wazuh-indexer.x86_64 : Wazuh indexer is a search and analytics engine for security-related data. Documentation can be found at
                     : https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html

  Name and summary matches only, use "search all" for everything.
```

**Comment by pepitoenpeligro** [comment]
# Indexer package digital signature

**Comment by pepitoenpeligro** [comment]
# Installed files location, size and permissions

**Comment by pepitoenpeligro** [comment]
# Installation footprint

**Comment by pepitoenpeligro** [comment]
# Installed services

**Comment by pepitoenpeligro** [comment]
# Wazuh indexer logs when installed


```yaml
07/06/2022 07:43:03 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.4
07/06/2022 07:43:03 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/06/2022 07:43:05 INFO: --- Configuration files ---
07/06/2022 07:43:05 INFO: Generating configuration files.
07/06/2022 07:43:06 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
[root@ip-172-31-32-12 ec2-user]# bash wazuh-install.sh --wazuh-indexer node-1
07/06/2022 07:43:08 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.4
07/06/2022 07:43:08 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/06/2022 07:43:14 INFO: Wazuh development repository added.
07/06/2022 07:43:14 INFO: --- Wazuh indexer ---
07/06/2022 07:43:14 INFO: Starting Wazuh indexer installation.
07/06/2022 07:44:12 INFO: Wazuh indexer installation finished.
07/06/2022 07:44:12 INFO: Wazuh indexer post-install configuration finished.
07/06/2022 07:44:12 INFO: Starting service wazuh-indexer.
07/06/2022 07:44:26 INFO: wazuh-indexer service started.
07/06/2022 07:44:26 INFO: Initializing Wazuh indexer cluster security settings.
07/06/2022 07:44:28 INFO: Wazuh indexer cluster initialized.
07/06/2022 07:44:28 INFO: Installation finished.
[root@ip-172-31-32-12 ec2-user]# less /var/log/wazuh-install.log
[root@ip-172-31-32-12 ec2-user]# cat /var/log/wazuh-install.log
07/06/2022 07:43:08 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.4
07/06/2022 07:43:08 INFO: Verbose logging redirected to /var/log/wazuh-install.log
[wazuh]
gpgcheck=1
gpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-${releasever} - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
07/06/2022 07:43:14 INFO: Wazuh development repository added.
07/06/2022 07:43:14 INFO: --- Wazuh indexer ---
07/06/2022 07:43:14 INFO: Starting Wazuh indexer installation.
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:4.3.4-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                Arch            Version            Repository      Size
================================================================================
Installing:
 wazuh-indexer          x86_64          4.3.4-1            wazuh          361 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 361 M
Installed size: 614 M
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : wazuh-indexer-4.3.4-1.x86_64                                 1/1
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
  Verifying  : wazuh-indexer-4.3.4-1.x86_64                                 1/1

Installed:
  wazuh-indexer.x86_64 0:4.3.4-1

Complete!
07/06/2022 07:44:12 INFO: Wazuh indexer installation finished.
07/06/2022 07:44:12 INFO: Wazuh indexer post-install configuration finished.
07/06/2022 07:44:12 INFO: Starting service wazuh-indexer.
Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service to /usr/lib/systemd/system/wazuh-indexer.service.
07/06/2022 07:44:26 INFO: wazuh-indexer service started.
07/06/2022 07:44:26 INFO: Initializing Wazuh indexer cluster security settings.
07/06/2022 07:44:28 INFO: Wazuh indexer cluster initialized.
07/06/2022 07:44:28 INFO: Installation finished.
```

**Comment by pepitoenpeligro** [comment]
# Wazuh Indexer templates and indices created

**Comment by pepitoenpeligro** [comment]
# Wazuh indexer cluster node communication and configuration

**Comment by pepitoenpeligro** [comment]
Experience when creating certificates, configuring cluster and sending events to the cluster

**Comment by pepitoenpeligro** [comment]
# Wazuh indexer status

**Comment by pepitoenpeligro** [comment]
# Create group != `default` and enroll Windows Agent

### 1. Group creation on Wazuh Server

```yaml
[root@ip-172-31-25-12 ec2-user]# /var/ossec/bin/agent_groups -a -g pepitogrouptesting
Do you want to create the group 'pepitogrouptesting'? [y/N]: y
Group 'pepitogrouptesting' created.
```

![image](https://user-images.githubusercontent.com/14912971/172591387-200dd11b-ca75-4978-a202-e1b52a94541f.png)



### 2. Windows Agent registration

```yaml
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.3.3-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.3.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.3.msi /q WAZUH_MANAGER='172.31.25.12' WAZUH_REGISTRATION_SERVER='172.31.25.12' WAZUH_AGENT_GROUP='pepitogrouptesting' 

NET START WazuhSvc
```

![image](https://user-images.githubusercontent.com/14912971/172591703-32cec1e5-d392-449c-94d0-513614910a0b.png)
 
![image](https://user-images.githubusercontent.com/14912971/172591912-80b34d2b-8a37-4f93-9f66-e9a171db4bb1.png)

![image](https://user-images.githubusercontent.com/14912971/172592033-4df9582f-dcd9-4fd8-955a-6152f2f25649.png)
