### ISSUE TITLE
Feature request: Ability to test Windows Event Logs in Logtest tool  [enhancement] [core/analysisd]

### ISSUE THREAD

**Issue by colleyc-osu** [wazuh/wazuh#13715]
|Wazuh version| Component | Action type |
|---| --- | --- |
| N/A | Rules/Decoders | New |

## Description
The added feature would provide the ability to directly test Windows Event Logs in the Wazuh-Logtest tool - in the web UI, executed on the command line, AND encapsulated in a unit test within `ruleset/testing/tests/`. The log to be tested should be copied as XML from Windows Event Viewer. The added feature MAY require from the user that this XML be squashed onto a single line before working successfully (or it may allow it to be pasted over several lines, but this would require a large reworking of many other Wazuh components). Besides being useful for end users, this added feature would also allow unit tests to be written for the Windows rules.

### Modules
This would primarily require changes to the [Wazuh-Logtest module](https://github.com/wazuh/wazuh/blob/master/src/analysisd/logtest.c). These changes may be able to utilize pre-existing code from the following other modules:

- [src/logcollector/read_win_event_channel.c](https://github.com/wazuh/wazuh/blob/master/src/logcollector/read_win_event_channel.c)
- [src/analysisd/decoders/winevtchannel.c](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/winevtchannel.c)

### Current results
Unable to use Wazuh-Logtest to test Windows Event Logs without workarounds.

### Expected results / Definition of Done
Be able to copy the XML rendering of a log from Windows Event Viewer, squash it into a single line, send it to the Wazuh-Logtest module, and receive accurate information on the steps it goes through to trigger a rule. Triggers the correct rule.

## Potential Issues
A single Event can be processed as either an `eventlog` or an `eventchannel`, which has different decoders and rulesets. Would the tool be able to detect which one a log is meant to be processed as? Would pre-processing need to be added for both the `eventchannel` and the `eventlog`?

### Log source / integration
Windows Event Viewer

### Log reference

Windows `eventlog` : processed by the `windows` decoder, rules in `0220-ms_auth.xml`.
Targets Windows versions older than Vista and older versions of Wazuh (exact number unknown).

Windows `eventchannel` : processed by the general `json` decoder, rules in `0580-win-security_rules.xml`.
Requires additional pre-processing by the modules listed above to be taken by the `json` decoder.
Targets Windows Vista and newer, and newer versions of Wazuh (exact number unknown).

### Log examples

Output of log processing after going through `src/logcollector/read_win_event_channel.c` from the agent, but before being sent to and processed by the manager. 

```
{"Message":"An account failed to log on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nLogon Type:\t\t\t3\r\n\r\nAccount For Which Logon Failed:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\tREDACTED-NAME\r\n\tAccount Domain:\t\tREDACTED-DOMAIN\r\n\r\nFailure Information:\r\n\tFailure Reason:\t\tUnknown user name or bad password.\r\n\tStatus:\t\t\t0xC000006D\r\n\tSub Status:\t\t0xC000006A\r\n\r\nProcess Information:\r\n\tCaller Process ID:\t0x0\r\n\tCaller Process Name:\t-\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\tREDACTED-WORKSTATION\r\n\tSource Network Address:\t0.0.0.0\r\n\tSource Port:\t\t0\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tNtLmSsp \r\n\tAuthentication Package:\tNTLM\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon request fails. It is generated on the computer where access was attempted.\r\n\r\nThe Subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe Logon Type field indicates the kind of logon that was requested. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe Process Information fields indicate which account and process on the system requested the logon.\r\n\r\nThe Network Information fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.","Event":"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-a5ba-3e3b0328c30d}'/><EventID>4625</EventID><Version>0</Version><Level>0</Level><Task>12544</Task><Opcode>0</Opcode><Keywords>0x8010000000000000</Keywords><TimeCreated SystemTime='2022-06-01T03:43:26.6784350Z'/><EventRecordID>1406399</EventRecordID><Correlation ActivityID='{2b4a671c-70aa-0000-5767-4a2baa70d801}'/><Execution ProcessID='976' ThreadID='17180'/><Channel>Security</Channel><Computer>REDACTED-HOST</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-0-0</Data><Data Name='SubjectUserName'>-</Data><Data Name='SubjectDomainName'>-</Data><Data Name='SubjectLogonId'>0x0</Data><Data Name='TargetUserSid'>S-1-0-0</Data><Data Name='TargetUserName'>REDACTED-NAME</Data><Data Name='TargetDomainName'>REDACTED-DOMAIN</Data><Data Name='Status'>0xc000006d</Data><Data Name='FailureReason'>%%2313</Data><Data Name='SubStatus'>0xc000006a</Data><Data Name='LogonType'>3</Data><Data Name='LogonProcessName'>NtLmSsp </Data><Data Name='AuthenticationPackageName'>NTLM</Data><Data Name='WorkstationName'>REDACTED-WORKSTATION</Data><Data Name='TransmittedServices'>-</Data><Data Name='LmPackageName'>-</Data><Data Name='KeyLength'>0</Data><Data Name='ProcessId'>0x0</Data><Data Name='ProcessName'>-</Data><Data Name='IpAddress'>0.0.0.0</Data><Data Name='IpPort'>0</Data></EventData></Event>"}
```

I do not currently have an example of an `eventchannel` log after it is processed by `src/analysisd/decoders/winevtchannel.c` from the manager.

An `eventlog` that is processed suitably that it is successfully taken by the Wazuh-Logtest module and reports back rule 18119:

```
2016 Sep 27 10:48:30 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: AAAABCC: KKKKK: 01.KKKKK.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-1119803419-263072742-1537874043-22758  Account Name:  AAAABCC  Account Domain:  KKKKK  Logon ID:  0x2b111bcc  Logon GUID:  {C609F1DB-667E-654F-AC26-48E1A2C6FA5F}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.12.123  Source Port:  54200  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon session is created. It is generated on the computer that was accessed.
```

This log was taken directly from `0380-windows_decoders.xml` for the `windows` decoder. A raw Event Log would need to be turned into this format to be successfully processed.

## Tests

- [ ] Compilation without errors of Logtest tool and manager on Linux
- [ ] Source installation and upgrade
- [ ] Package installation and upgrade
- [ ] Added unit tests (for new features)

- Added decoder/ruleset unit tests for common Windows eventchannels
   - [ ] Added unit testing files ".ini"
   - [ ] runtests.py executes without error

- Memory tests for Linux
   - [ ] Scan-build report
   - [ ] Coverity
   - [ ] Valgrind
   - [ ] Dr. Memory
   - [ ] AddressSanitizer

## Additional Notes

Community contribution. Interested in working on this feature request.

**Comment by fabamatic** [comment]
Hello @colleyc-osu, from the wording in your issue I guess that you are already aware of the workaround needed to enable wazuh-logtest to parse windows event logs in json format, anyway here is the workaround:
In file 0575-win-base_rules.xml, rule id 60000 remove category tag and change decoded_as tag value for json.
It should look like this
```
  <rule id="60000" level="0">
    <decoded_as>json</decoded_as>
    <field name="win.system.providerName">\.+</field>
    <options>no_full_log</options>
    <description>Group of windows rules.</description>
  </rule>
```
For the time being no feature modification are planed on wazuh-logtest tool as the team is working on a new ruleset engine.
