### ISSUE TITLE
install.sh fails on latest openSUSE Leap 15

### ISSUE THREAD

**Issue by DLGolden** [wazuh/wazuh#1371]
Trying to install wazuh on newly installed openSUSE Leap 15. I have not been able to find a log of the install.sh output, but here are the last few lines of terminal output:

ar: creating libcrypto.a
ranlib libcrypto.a || echo Never mind.
ar  r libssl.a ssl/bio_ssl.o ssl/d1_lib.o ssl/d1_msg.o ssl/d1_srtp.o ssl/methods.o ssl/pqueue.o ssl/record/dtls1_bitmap.o ssl/record/rec_layer_d1.o ssl/record/rec_layer_s3.o ssl/record/ssl3_buffer.o ssl/record/ssl3_record.o ssl/s3_cbc.o ssl/s3_enc.o ssl/s3_lib.o ssl/s3_msg.o ssl/ssl_asn1.o ssl/ssl_cert.o ssl/ssl_ciph.o ssl/ssl_conf.o ssl/ssl_err.o ssl/ssl_init.o ssl/ssl_lib.o ssl/ssl_mcnf.o ssl/ssl_rsa.o ssl/ssl_sess.o ssl/ssl_stat.o ssl/ssl_txt.o ssl/ssl_utst.o ssl/statem/statem.o ssl/statem/statem_clnt.o ssl/statem/statem_dtls.o ssl/statem/statem_lib.o ssl/statem/statem_srvr.o ssl/t1_enc.o ssl/t1_ext.o ssl/t1_lib.o ssl/t1_reneg.o ssl/t1_trce.o ssl/tls_srp.o
ar: creating libssl.a
ranlib libssl.a || echo Never mind.
make[2]: Leaving directory '/home/dgolden/Downloads/wazuh-master/src/external/openssl'
make[1]: Leaving directory '/home/dgolden/Downloads/wazuh-master/src/external/openssl'

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by DLGolden** [comment]
Never mind, I had missing prerequisites. I had trouble finding all of them. I don't know how difficult it would be, but if possible a test of missing prerequisites would be great when running install.sh.

Regards,

Dennis

**Comment by alanmurder** [comment]
@DLGolden ，do you remember which prerequisites missing?
