### ISSUE TITLE
`Logcollector` discard audit message because of invalid syntax

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#13710]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4-rc1 | wazuh-logcollector | Manager | Packages | CentOS 7 (OVA 4.3.4) |

Hello team, testing the OVA package I found a `wazuh-logcollector` error in the Wazuh server log:

```
2022/06/03 12:55:40 wazuh-logcollector: ERROR: Discarding audit message because of invalid syntax.
```

After the error, a restart of the Wazuh server seems to be carried out since it is observed how the daemons report a `Signal terminating`, and then the service is started again.

```
2022/06/03 12:56:07 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

Related logs:

- ossec.log: [ossec.log](https://github.com/wazuh/wazuh/files/8835559/ossec.log)
- audit.log: [audit.log](https://github.com/wazuh/wazuh/files/8835558/audit.log)

Maybe related issues and pull requests:

- https://github.com/wazuh/wazuh/pull/12676
- https://github.com/wazuh/wazuh/issues/3342

**Comment by vikman90** [comment]
Hi @rauldpm,

This is the debug log from Logcollector, where I've added a couple of extra _debug_ logs:

```
2022/06/14 10:52:39 wazuh-logcollector[3017] read_audit.c:65 at read_audit(): DEBUG: Read: '
'...
2022/06/14 10:52:39 wazuh-logcollector[3017] read_audit.c:120 at read_audit(): DEBUG: Extracting: ''...
2022/06/14 10:52:39 wazuh-logcollector[3017] read_audit.c:123 at read_audit(): ERROR: Discarding audit message because of invalid syntax.
2022/06/14 10:52:39 wazuh-logcollector[3017] read_audit.c:153 at read_audit(): DEBUG: Read 1 lines from /root/audit.log
2022/06/14 10:52:41 wazuh-logcollector[3017] read_audit.c:65 at read_audit(): DEBUG: Read: 'type=USER_END msg=audit(16542608'...
2022/06/14 10:52:41 wazuh-logcollector[3017] read_audit.c:120 at read_audit(): DEBUG: Extracting: 'type=USER_END msg=audit(16542608'...
(...)
```

I'm pretty sure the cause of this error is that the first line of your audit.log file is a blank line, which does not match the expected format.

Could you confirm that the original `audit.log` contains a blank line? If so, we should remove the error log. Otherwise, I think there is no bug around here.

In any case, I cannot relate this error with a manager restart.

Best!

**Comment by rauldpm** [comment]
Hello @vikman90, yes, the file contains an empty line at the beginning of the file, the cause of this line has been identified and is being fixed (related to log cleaning). In any case, should logcollector report this as an error or should logcollector ignore it?

**Comment by vikman90** [comment]
Attaching issue #14687.

Requirements:
- If there is a blank line, skip it and do not print an error.
- If a log contains a valid header but an empty message, append that empty string to the final log.
