### ISSUE TITLE
Osquery not start after reboot on macos

### ISSUE THREAD

**Issue by raito9x** [wazuh/wazuh#1373]
Hi team.
I'm using macOS High Sierra and configure osquery start as wazuh-modulesd. But when i reboot my computer, osquery not run
My config
  
  <wodle name="osquery">
    <disabled>no</disabled>
    <run_daemon>yes</run_daemon>
    <log_path>/var/log/osquery/osqueryd.results.log</log_path>
    <config_path>/var/osquery/osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

My log
2018/09/21 09:31:49 agent-auth: INFO: Started (pid: 8565).
2018/09/21 09:31:53 ossec-execd: INFO: (1350): Active response disabled. Exiting.
2018/09/21 09:31:53 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/09/21 09:31:53 ossec-agentd: INFO: Version detected -> Darwin |anonymous.local |17.7.0 |Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 |x86_64 [Mac OS X|darwin: 10.13.6 (High Sierra)] - Wazuh v3.6.1
2018/09/21 09:31:53 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/09/21 09:31:53 ossec-agentd: INFO: Using AES as encryption method.
2018/09/21 09:31:53 ossec-agentd: INFO: Started (pid: 8614).
2018/09/21 09:31:53 ossec-agentd: INFO: Server IP Address: 192.168.137.13
2018/09/21 09:31:53 wazuh-modulesd: INFO: Process started.
2018/09/21 09:31:53 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 09:31:53 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/09/21 09:31:53 wazuh-modulesd:osquery: INFO: Module started.
2018/09/21 09:31:53 wazuh-modulesd:syscollector: INFO: Module started.
2018/09/21 09:31:54 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Started (pid: 8620).
2018/09/21 09:31:57 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/09/21 09:31:57 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/09/21 09:31:57 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/09/21 09:31:57 rootcheck: INFO: Started (pid: 8620).
2018/09/21 09:31:59 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/09/21 09:31:59 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/system.log'.

If i run
/var/ossec/bin/ossec-control restart
osquery start ok

**Comment by raito9x** [comment]
Sorry, this log after i run command /var/ossec/bin/ossec-control restart
Log after boot is
2018/09/21 15:28:43 wazuh-modulesd: INFO: Process started.
2018/09/21 15:28:43 ossec-agentd: INFO: Version detected -> Darwin |localhost |17.7.0 |Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 |x86_64 [Mac OS X|darwin: 10.13.6 (High Sierra)] - Wazuh v3.6.1
2018/09/21 15:28:43 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/09/21 15:28:43 wazuh-modulesd:osquery: INFO: Module started.
2018/09/21 15:28:43 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/09/21 15:28:43 ossec-agentd: INFO: Using AES as encryption method.
2018/09/21 15:28:43 ossec-agentd: INFO: Started (pid: 176).
2018/09/21 15:28:43 ossec-agentd: INFO: Server IP Address: 192.168.137.13
2018/09/21 15:28:43 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 15:28:43 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.137.13': 'Network is unreachable'.
2018/09/21 15:28:44 wazuh-modulesd:syscollector: INFO: Module started.
2018/09/21 15:28:44 wazuh-modulesd:osquery: ERROR: Couldn't execute osquery (osqueryd). Check file and permissions. Sleeping for 10 minutes.
2018/09/21 15:28:45 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Started (pid: 182).
2018/09/21 15:28:47 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/09/21 15:28:47 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/09/21 15:28:48 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/09/21 15:28:48 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/09/21 15:28:48 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/09/21 15:28:48 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/09/21 15:28:48 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/09/21 15:28:48 rootcheck: INFO: Started (pid: 182).
2018/09/21 15:28:49 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/09/21 15:28:49 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/system.log'.
2018/09/21 15:28:49 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq
2018/09/21 15:28:49 ossec-logcollector: INFO: Started (pid: 186).
2018/09/21 15:28:54 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 15:28:54 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.137.13': 'Network is unreachable'.
2018/09/21 15:29:03 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/09/21 15:29:04 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 15:29:04 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.137.13': 'Network is unreachable'.
2018/09/21 15:29:14 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 15:29:14 ossec-agentd: ERROR: (1216): Unable to connect to '192.168.137.13': 'Network is unreachable'.
2018/09/21 15:29:18 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2018/09/21 15:29:25 ossec-agentd: INFO: Trying to connect to server (192.168.137.13:1514/udp).
2018/09/21 15:29:48 ossec-agentd: ERROR: (1210): Queue '/queue/alerts/execq' not accessible: 'Queue not found'.
2018/09/21 15:29:49 ossec-agentd: ERROR: Unable to connect to the active response queue (disabled).
2018/09/21 15:29:52 ossec-agentd: INFO: (4102): Connected to the server (192.168.137.13:1514/udp).
2018/09/21 15:29:56 ossec-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
2018/09/21 15:29:57 ossec-logcollector: INFO: Agent is now online. Process unlocked, continuing...
2018/09/21 15:29:57 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/09/21 15:29:56 rootcheck: INFO: Starting rootcheck scan.
2018/09/21 15:30:12 wazuh-modulesd:syscollector: WARNING: Opened ports inventory is not available for this OS version.
2018/09/21 15:30:12 wazuh-modulesd:syscollector: WARNING: Running processes inventory is not available for this OS version.
2018/09/21 15:30:12 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/09/21 15:30:31 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2018/09/21 15:30:36 ossec-syscheckd: INFO: Ending syscheck scan (forwarding database).

**Comment by TJOSERAFAEL** [comment]
Hi @raito9x ,

`2018/09/21 15:28:44 wazuh-modulesd:osquery: ERROR: Couldn't execute osquery (osqueryd). Check file and permissions. Sleeping for 10 minutes.`

Can you please verify that you have the osquery daemon in the right path? It should be located in `/usr/bin/osqueryd`


Best regards.

**Comment by raito9x** [comment]
No, osqueryd in /usr/local/bin/osqueryd

**Comment by TJOSERAFAEL** [comment]
Hi @raito9x ,

can you please provide your osquery configuration (ossec.conf)? Also try to change
` <bin_path>/usr/bin</bin_path> `
 to
 ` <bin_path>/usr/local/bin</bin_path>`

Best regards.

**Comment by raito9x** [comment]
Hi, this is my config
<ossec_config>
  <client>
    <server>
      <address>192.168.137.13</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <config-profile>darwin, darwin17, darwin17.7</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
  </client>

  <client_buffer>
    
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>

  
  <rootcheck>
    <disabled>no</disabled>
    <check_unixaudit>yes</check_unixaudit>
    <check_files>yes</check_files>
    <check_trojans>yes</check_trojans>
    <check_dev>yes</check_dev>
    <check_sys>yes</check_sys>
    <check_pids>yes</check_pids>
    <check_ports>yes</check_ports>
    <check_if>yes</check_if>

    
    <frequency>7200</frequency>

    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>

    <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt</system_audit>

    <skip_nfs>yes</skip_nfs>
  </rootcheck>

  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
  </wodle>

  
  <wodle name="osquery">
    <disabled>no</disabled>
    <run_daemon>yes</run_daemon>
    <log_path>/var/log/osquery/osqueryd.results.log</log_path>
    <config_path>/var/osquery/osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

  
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>

  
  <syscheck>
    <disabled>no</disabled>

    
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin</directories>

    
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <skip_nfs>yes</skip_nfs>

    
    <remove_old_diff>yes</remove_old_diff>
  </syscheck>

  
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/system.log</location>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -an | grep -e "tcp" -e "udp" | sed -E 's/([[:alnum:]]*)\ *[[:digit:]]*\ *[[:digit:]]*\ *(.*)\.([0-9\*]*)\ +([0-9\.\*]+).+/\1 \2 == \3 == \4/' | sort -k 4 -g | sed 's/ == \(.*\) ==/.\1/'| uniq</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>

  <active-response>
    <disabled>yes</disabled>
    <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
    <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>

  <logging>
    <log_format>plain</log_format>
  </logging>

</ossec_config>

**Comment by TJOSERAFAEL** [comment]
Hi @raito9x ,

sorry for the late response, from the ossec.conf that you posted, you are missing the ` <bin_path>` tag in the osquery wodle. Please add the path to your **osquery** binary and restart the agent.

Best regards.

**Comment by vikman90** [comment]
Hi @raito9x,

Hope you manage to enable Osquery on your agent. I assume you don't need further assistance with this issue, let me close it.

If this problem persists or you need more help, feel free to reopen it.

Best.
