### ISSUE TITLE
Review and resolve SCA for Operating systems without a default policy

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#13757]
|Wazuh target version| Component | Action type |
|---| --- | --- |
| 4.4.0 | SCA | Improvement |

Find and solve missing SCA policies or wrong default ones for OS versions in Wazuh SCA policies 

- Microsoft Windows Desktop Microsoft Windows
- Debian Linux Linux
- Ubuntu Linux Linux
- Amazon Linux Linux
- Aliyun Linux Linux
- CentOS Linux Linux
- Oracle Linux Linux
- Red Hat Enterprise Linux Linux
- SUSE Linux Enterprise Server Linux
- Apple macOS UNIX
- IBM AIX UNIX
- HP UX
- Oracle Solaris UNIX
- Fedora Family Linux Linux
- AlmaLinux OS Linux
- Rocky Linux Linux
- Microsoft Windows Server Microsoft Windows 

This is part of the EPIC #13751

**Comment by uhlhosting** [comment]
@72nomada any updates on this?

**Comment by 72nomada** [comment]
Work in progress. They will be coming in future releases. Hopefully we will speed this up.

**Comment by 72nomada** [comment]
manage by https://github.com/wazuh/wazuh/issues/14358
