### ISSUE TITLE
macOS `wazuh-modulesd` memory usage is half of `wazuh-modulesd` memory used in 4.3.1

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#13752]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4-rc1 | modulesd | Agent | Packages | Macos |

Analyzing the issue https://github.com/wazuh/wazuh/issues/13736, it has been observed that the RSS graph shows an almost linear use of modulesd, after a brief upload at the beginning of the test, it can be seen that it is maintained constant at ~40MB, in 4.3.1, memory usage was ~80MB, by comparison, modulesd seems to have stopped working.

- https://github.com/wazuh/wazuh/issues/13736

![image](https://user-images.githubusercontent.com/14913942/172217038-f90cc80c-4e5d-488b-a7df-db67cb01d24f.png)

- https://github.com/wazuh/wazuh/issues/13483

![image](https://user-images.githubusercontent.com/14913942/172217056-17369dca-883c-4248-8bba-7b7ec3a8974a.png)

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #13669                                         |
| **Main footprint metrics issue #** | #13699                                         |
| **Version** | 4.3.4                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.4-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/48/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/Test_stress_Vagrant_B48_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/Test_stress_Vagrant_B48_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/plots/Test_stress_Vagrant_B48_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B48_manager_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/logs/ossec_Test_stress_Vagrant_B48_manager_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B48_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/data/monitor-manager-Test_stress_Vagrant_B48_manager-pre-release.csv)
[Test_stress_Vagrant_B48_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/data/Test_stress_Vagrant_B48_manager_analysisd_state.csv)
[Test_stress_Vagrant_B48_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_manager_centos/data/Test_stress_Vagrant_B48_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/Test_stress_Vagrant_B48_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/Test_stress_Vagrant_B48_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/Test_stress_Vagrant_B48_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/plots/Test_stress_Vagrant_B48_macos_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B48_macos_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/logs/ossec_Test_stress_Vagrant_B48_macos_agent_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/data/monitor-agent-Test_stress_Vagrant_B48_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B48_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B48-720m/B48_agent_macos/data/Test_stress_Vagrant_B48_macos_agent_agentd_state.csv)



    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #13669                                         |
| **Main footprint metrics issue #** | #13699                                         |
| **Version** | 4.3.1                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.1-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `live`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/50/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B50_manager-live_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/Test_stress_Vagrant_B50_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/Test_stress_Vagrant_B50_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/plots/Test_stress_Vagrant_B50_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B50_manager_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/logs/ossec_Test_stress_Vagrant_B50_manager_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B50_manager-live.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/data/monitor-manager-Test_stress_Vagrant_B50_manager-live.csv)
[Test_stress_Vagrant_B50_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/data/Test_stress_Vagrant_B50_manager_analysisd_state.csv)
[Test_stress_Vagrant_B50_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_manager_centos/data/Test_stress_Vagrant_B50_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/Test_stress_Vagrant_B50_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/Test_stress_Vagrant_B50_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/Test_stress_Vagrant_B50_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/plots/Test_stress_Vagrant_B50_macos_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B50_macos_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/logs/ossec_Test_stress_Vagrant_B50_macos_agent_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B50_macos_agent-live.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/data/monitor-agent-Test_stress_Vagrant_B50_macos_agent-live.csv)
[Test_stress_Vagrant_B50_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/live/4.3.1/B50-720m/B50_agent_macos/data/Test_stress_Vagrant_B50_macos_agent_agentd_state.csv)



    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #13669                                         |
| **Main footprint metrics issue #** | #13699                                         |
| **Version** | 4.3.4                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.3.4-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/49/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/Test_stress_Vagrant_B49_manager_analysisd_state_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/Test_stress_Vagrant_B49_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/plots/Test_stress_Vagrant_B49_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B49_manager_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/logs/ossec_Test_stress_Vagrant_B49_manager_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B49_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/data/monitor-manager-Test_stress_Vagrant_B49_manager-pre-release.csv)
[Test_stress_Vagrant_B49_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/data/Test_stress_Vagrant_B49_manager_analysisd_state.csv)
[Test_stress_Vagrant_B49_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_manager_centos/data/Test_stress_Vagrant_B49_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/Test_stress_Vagrant_B49_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/Test_stress_Vagrant_B49_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/Test_stress_Vagrant_B49_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/plots/Test_stress_Vagrant_B49_macos_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B49_macos_2022-06-08.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/logs/ossec_Test_stress_Vagrant_B49_macos_agent_2022-06-08.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/data/monitor-agent-Test_stress_Vagrant_B49_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B49_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.3.4/B49-720m/B49_agent_macos/data/Test_stress_Vagrant_B49_macos_agent_agentd_state.csv)



    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by chemamartinez** [comment]
Further investigation is needed here to determine why the RSS of `wazuh-modulesd` in the macOS agent present a different behavior. Sometimes it reaches a 80MB peak to continue the rest of the test in ~40MB, in other tests with the same conditions it remains at 80MB during all the test.

The following items have been reviewed from all the cases:
- Agent configuration
- Agent logs
- Logs generated from the different stress scripts
In these three points, we observe the same behavior so we cannot obtain any conclusion from them.

Regarding the impact of this issue, it should not be stopper for 4.3.4 because of the following reasons:
- We have seen this behavior in previous versions such as the footprint test of 4.3.0-RC7 https://github.com/wazuh/wazuh/issues/13303
- Changes introduced in the latest patch versions (from 4.3.1 to 4.3.4) don't affect the agents so the `wazuh-modulesd` operation of the macOS agent neither.
- It is true that the behavior is different in both cases but none of them leads to a bad operation of the agent or a huge impact in the resources usage.
