### ISSUE TITLE
Classify analysisd statistics by component

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#13755]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Analysisd| Manager | Packages/Sources | Linux |

### Description

The purpose of this issue is to extend the statistics for `wazuh-analysisd`:

- Classify the received events by component using the location of the events.
- Classify the dropped events by component using the location of the events.
- Classify the unknown events by component using the location of the events.

New statistics will be added to this issue once the investigation is done.

### Classification

Events classified by queue:

- `SYSLOG_MQ` -> Syslog events.
- `DBSYNC_MQ` -> DBsync events.
- `HOSTINFO_MQ` -> Logcollector `nmapg` events.
- `WIN_EVT_MQ` -> Logcollector `eventchannel` events.
- `SYSCHECK_MQ` -> Syscheck events.
- `ROOTCHECK_MQ` -> Rootcheck events.
- `SYSCOLLECTOR_MQ` -> Syscollector events.
- `CISCAT_MQ` -> CISCAT events.
- `SCA_MQ` -> SCA events.
- `UPGRADE_MQ` -> Upgrade events.

Events classified by location:

- `LOCALFILE_MQ` -> Generic events.
  - `aws-s3` / `Wazuh-AWS` -> AWS wodle events.
  - `azure-logs` / `Azure` -> Azure wodle events.
  - `cis-cat` / `wodle_cis-cat` -> CISCAT wodle events (repeated).
  - `command` / `command_*` -> Command wodle events.
  - `docker-listener` / `Wazuh-Docker` -> Docker wodle events.
  - `gcp-pubsub` / `gcp-bucket` / `Wazuh-GCloud` -> GCloud wodle events.
  - `github` -> GitHub wodle events.
  - `office365` -> O365 wodle events.
  - `open-scap` / `wodle_open-scap` -> Oscap wodle events.
  - `osquery` -> OSquery wodle events.
  - `sca` -> SCA wodle events (repeated).
  - `syscollector` -> Syscollector wodle events (repeated).
  - `agent-upgrade` -> Upgrade wodle events (repeated).
  - `vulnerability-detector` -> Vuln detector wodle events.
  - `wazuh-agent` -> Agentd events.
  - `wazuh-agentlessd` -> Agentless events.
  - `wazuh-monitord` -> Monitord events.
  - `wazuh-remoted` -> Remoted events.
  - `logcollector` / others -> Logcollector events.
  - `rootcheck` -> Rootcheck events (repeated).
  - `syscheck` -> Syscheck events (repeated).
  - `virustotal` -> VirusTotal integration events.
  - `macos` -> Logcollector `macos` events.
  - `WinEvtLog` -> Logcollector `eventlog` events.

**Comment by hitman28594** [comment]
Will these stats be granular to the agent location too or just to individual wazuh components like syscheck, sycollector etc.? 

It would be great if we could also get these stats per agent/agent-location. 

Another useful statistic would be a count of how many logs were undecoded, or didn’t match a rule.
