### ISSUE TITLE
Remoted prints a "too big message" warning log

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#13762]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.3.3 | Remoted | Manager |

We've found this log by Remoted:

```
wazuh-remoted: WARNING: Too big message size from 10.1.2.3 [20].
```

## Rationale

Agent-manager messages follow this format:

```
<message> ::= <header> <payload>
<header> ::= <byte> <byte> <byte> <byte>
```

The `<header>` is a 32-bit unsigned little-endian integer indicating the payload size in bytes. The value range is [0, `OS_MAXSTR`] (up to 65536 bytes). Should any message not honor this constraint, Remoted will print this warning and close the connection.

This does mean a bug in Remoted. The most common causes are:
1. Remoted is receiving any connection from a TCP client that is not a Wazuh agent.
2. An agent below v2.1.1 running on Solaris/SPARC or HP-UX is trying to connect to the manager.

**Comment by crysalis010** [comment]
This happens for any syslog message our Wazuh instance receives. We are unable to collect syslog from any non-agent device seemingly due to this.

**Comment by Darka94** [comment]
Hello, I have problems with this message, I am receiving logs from a firewall through syslog, and I have a spam of this alert in the ossec.log, do I have a way to solve it? such as increasing the size of the log reception or something like that?

`wazuh-remoted:` WARNING: Too big message size from socket [85]`

**Comment by vikman90** [comment]
@Darka94 This warning comes from this code line: [secure.c](https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/src/remoted/secure.c#L290).

As explained above, this means that **a non-agent device is connecting to agent-only port 1514**.

If you have syslog input (something like this):
```xml
<remote>
  <connection>syslog</connection>
  <port>514</port>
</remote>
```

Please make sure your firewall is sending logs to port 514 (or whatever is specified). Prevent firewalls from trying to connect to port 1514, because Wazuh Manager expects only agents to connect there.

Hope that helps.
Best regards.

**Comment by winhigh** [comment]
@vikman90 what if i get "Non standard syslog message (size too large)"
how do i increase size of log message ?
kindly enlighten me on this part, can we edit or add ossec conf to mitigate this issue.

**Comment by shovan777** [comment]
Hi @vikman90, I sent logs to wazuh manager from unauthorized client to 1514 but only got 
```bash
wazuh-remoted: WARNING: Too big message size from 10.45.13.215 [10]
```
instead of the [log](https://github.com/wazuh/wazuh/issues/13762#issuecomment-1288522934) mention above
```bash
wazuh-remoted: WARNING: (1213): Message from 'X.Y.Z.W' not allowed. Cannot find the ID of the agent.
```
