### ISSUE TITLE
The event message of a duplicate directory or registry in Syscheck should be a warning

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1376]
https://github.com/wazuh/wazuh/blob/56d7187fd16cfcacf4178a2118a0e1a225aa2eec/src/config/syscheck-config.c#L613
https://github.com/wazuh/wazuh/blob/56d7187fd16cfcacf4178a2118a0e1a225aa2eec/src/config/syscheck-config.c#L253

It's related to https://github.com/wazuh/wazuh/issues/867.

**Comment by bah07** [comment]
Done!
