### ISSUE TITLE
Rules in sca/cis_rhel8_linux.yml incorrect for most sysctl checks

### ISSUE THREAD

**Issue by richardkhardy** [wazuh/wazuh#13770]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-1 | sca | agent | rpm | RHEL8|

Related - [#13417](https://github.com/wazuh/wazuh/issues/13417)

There are a number of rules in /var/ossec/tmp/sca-4.3.0-1-tmp/rhel/8/cis_rhel8_linux.yml which look like this

    condition: all
    rules:
      - 'c:grep -Rh net.ipv4.conf.all.send_redirects /etc/sysctl.conf /etc/sysctl.d/* -> r:^\s*net.ipv4.conf.all.send_redirects\s*=\s*0'
      - 'c:grep -Rh net.ipv4.conf.default.send_redirects /etc/sysctl.conf /etc/sysctl.d/* -> r:^\s*net.ipv4.conf.default.send_redirects\s*=\s*0'

You can't use a wildcard when not running inside a shell. The following command is forked by modulesd

execve("/sbin/grep", ["grep", "-Rh", "net.ipv4.conf.all.send_redirects", "/etc/sysctl.conf", "/etc/sysctl.d/*"]

and you get a failure like this

4131  openat(AT_FDCWD, "/etc/sysctl.d/*", O_RDONLY|O_NOCTTY) = -1 ENOENT (No such file or directory)

The command exits with status 2, and you get this in the debug logs

2022/06/07 21:50:38 sca[3962] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:grep -Rh net.ipv4.conf.all.send_redirects /etc/sysctl.conf /etc/sysctl.d/* -> r:^\s*net.ipv4.conf.all.send_redirects\s*=\s*0'
2022/06/07 21:50:38 sca[3962] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'grep -Rh net.ipv4.conf.all.send_redirects /etc/sysctl.conf /etc/sysctl.d/*', and testing output with pattern 'r:^\s*net.ipv4.conf.all.send_redirects\s*=\s*0'
2022/06/07 21:50:38 sca[3962] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'grep -Rh net.ipv4.conf.all.send_redirects /etc/sysctl.conf /etc/sysctl.d/*' returned code 2

Which means that it thinks the ruleset has failed. 

The rules should all be like this one

      - 'c:grep -Rh ^kernel\.randomize_va_space /etc/sysctl.conf /etc/sysctl.d -> r:^\s*kernel.randomize_va_space\s*=\s*2$'

**Comment by 72nomada** [comment]
Hi @richardkhardy, thanks for your feedback. We will review and resolve as needed.

**Comment by 72nomada** [comment]
Hi @richardkhardy 

Thanks a lot for your report, It seems that is not just the use of the wildcard; if the folder does not exist, the command will return two too. Using wildcard will work if the folder exists and it is not empty. 

We will rework the commands to resolve the issue. You can track changes in #13843. We will update both RHEL9 and RHEL8 policies. We will close this one when merging the PR in progress. 

I hope it works for you.

##Tests:

### The folder /etc/sysctl.d for testing exists and Is empty; no wildcard
```
[root@localhost sca]# grep -Rh -E -s "^\s{0,}net\.ipv6\.conf\.all\.forwardings" /etc/sysctl.conf /etc/sysctl.d/ /usr/lib/sysctl.d/ /run/sysctl.d/
[root@localhost sca]# echo $?
1
````

### The folder /etc/sysctl.d does not exist; no wildcard
```
[root@localhost sca]# rm -rf /etc/sysctl.d
[root@localhost sca]# grep -Rh -E -s "^\s{0,}net\.ipv6\.conf\.all\.forwardings" /etc/sysctl.conf /etc/sysctl.d/ /usr/lib/sysctl.d/ /run/sysctl.d/
[root@localhost sca]# echo $?
2
```

### The folder /etc/sysctl.d exists and Is empty; no wildcard
``` 
[root@localhost sca]# mkdir /etc/sysctl.d
[root@localhost sca]# grep -Rh -E -s "^\s{0,}net\.ipv6\.conf\.all\.forwardings" /etc/sysctl.conf /etc/sysctl.d/ /usr/lib/sysctl.d/ /run/sysctl.d/
[root@localhost sca]# echo $?
1
```

### The folder /etc/sysctl.d for testing exists and Is empty, using wildcard
```
[root@localhost sca]# grep -Rh -E -s "^\s{0,}net\.ipv6\.conf\.all\.forwardings" /etc/sysctl.conf /etc/sysctl.d/* /usr/lib/sysctl.d/ /run/sysctl.d/
[root@localhost sca]# echo $?
2
````

### The folder /etc/sysctl.d exists and Is not empty, using wildcard
```
[root@localhost sca]# touch /etc/sysctl.d/test
[root@localhost sca]# grep -Rh -E -s "^\s{0,}net\.ipv6\.conf\.all\.forwardings" /etc/sysctl.conf /etc/sysctl.d/* /usr/lib/sysctl.d/ /run/sysctl.d/
[root@localhost sca]# echo $?
1
```
