### ISSUE TITLE
Improve macOS codename retrieving support

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13787]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| up to master | Syscollector  | Agent | Packages/Sources | macOS |

## Description

Currently, Wazuh macOS agent is not capable of retrieving codename directly from the OS, leading to a conversion in the code from version to codename that needs to be constantly updated/maintained

https://github.com/wazuh/wazuh/blob/4ad7e9cddfb31b5e0aea978332d2185f00d94f4c/src/shared/version_op.c#L364-L377
https://github.com/wazuh/wazuh/blob/4ad7e9cddfb31b5e0aea978332d2185f00d94f4c/src/data_provider/src/osinfo/sysOsParsers.cpp#L423-L432

It's desirable to retrieve macOS codename from the OS in order to avoid this situation.

## DoD
- [ ] Research if there's any way to read codename directly from the OS, file-based preferentially.
- [ ] Implement this enhancement
- [ ] Smoke test every macOS supported OS
- [ ] Add/Fix UT
- [ ] QA coverage
- [ ] E2E validation

**Comment by jftuduri** [comment]
[Here](https://github.com/saltstack/salt/issues/53317#issuecomment-497739801) the try with a hardcoded release->codename map and the license file as a fallback.

**Comment by jftuduri** [comment]
### Conclusion

Unfortunately, at this moment, there is no consistent and reliable method to obtain the codename of the macOS version in a way that is local to the agent. The alternatives found give no guarantees of being forward compatible with future versions of macOS, and that was the main goal of this issue.
