### ISSUE TITLE
Check worker stability

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#13796]
Before starting the unbalance detection algorithm and the balancing algorithm itself we need to check that the environment is stable.

Due to the fact that when checking the unbalancing in the cluster we need to know the number of workers, we need to be sure that no new workers are being added to the environment. For it, every X seconds we will check if the environment has suffered changes in the number of workers.

If the environment has not experienced changes we will continue checking until we do this check X times, at which time we will activate the next part of the algorithm. In case the environment suffers modifications during these checks we will restart the iteration counter.

![image](https://user-images.githubusercontent.com/15522808/172833098-05eb8593-6b79-4565-9773-d6c6ed3ef63a.png)

**Comment by Selutario** [comment]
## Expand development
### Description
This is the initial part of the balancing algorithm. It is responsible for verifying that the connected workers have been the same for a period of time before balancing of agents.
![image](https://user-images.githubusercontent.com/23361101/173349033-4062ea03-fb83-4589-8e42-cb73d4e3453e.png)

### Steps
1. **Start:** The algorithm is executed for the first time after starting `wazuh-clusterd`. There is no persistent data in that process, so all counters and data structures are empty at this point.
2. **Check workers stability:** Obtains the name of all the clients (workers) connected to the master node. Said information can be obtained from the [self.client](https://github.com/wazuh/wazuh/blob/3d9e9ac429d439d48506e684eadebd8909727413/framework/wazuh/core/cluster/server.py#L271) attribute.
3. **Same workers?:** Compare the name of the workers obtained in step 2 with the information of previous iterations. The new information is saved in a dictionary, overwriting it.
4. **Reset all counters:** If comparison in step 3 is not successful, all counters are reset and sleep before starting again at step 2.
5. **Setup counter threshold?:** If the comparison was successful, this counter is incremented. If the counter has reached a preset number, [this algorithm](https://github.com/wazuh/wazuh/issues/13794) starts. In this step the counter can only increment. It is never restarted as long as the comparison between workers is successful.

**Comment by AdriiiPRodri** [comment]
## Status update

We have developed the section in charge of controlling the stability of the cluster. For it our function does the following:

1.- It checks the number of workers at a moment X. This way up to 3 times.
2.- If the environment changes between iterations the counter returns to 0.
3.- If no changes are detected the counter is not restarted under any concept.

### Cluster.log
```
2022/06/20 10:43:24 INFO: [Master] [Agents reconnect] Cluster agents reconnection started.
2022/06/20 10:43:24 INFO: [Master] [Agents reconnect] Sleeping 30s before starting the agent-groups task, waiting for the workers connection.
2022/06/20 10:43:54 INFO: [Master] [Agents reconnect - Check workers stability] Workers are not stable at this moment. Counter: 1/3.
2022/06/20 10:44:04 INFO: [Master] [Agents reconnect - Check workers stability] Workers are not stable at this moment. Counter: 2/3.
2022/06/20 10:44:14 INFO: [Master] [Agents reconnect - Check workers stability] Cluster is ready 3/3. Workers stability phase finished at 2022-06-20T10:44:14.500539Z.
2022/06/20 10:44:14 INFO: [Master] [Agents reconnect] Iteration complete. Sleep during 60 seconds.
2022/06/20 10:45:14 INFO: [Master] [Agents reconnect - Check workers stability] Cluster is ready 3/3. Workers stability phase finished at 2022-06-20T10:45:14.505606Z.
2022/06/20 10:45:14 INFO: [Master] [Agents reconnect] Iteration complete. Sleep during 60 seconds.
```


### cluster-control CLI
```
root@wazuh-master:/# /var/ossec/bin/cluster_control -i more
Cluster name: wazuh

Connected nodes (2):

    master-node (wazuh-master)
        Version: 4.4.0
        Type: master
        Active agents: 1
        Status:
            Agents reconnect:
                Current phase: Sleeping.
                Last workers stability check: 2022-06-20T10:49:14.518214Z.
                Last register workers: ['worker1', 'worker2'].
                Worker stability counter: 3.
                Worker stability threshold: 3.

```
