### ISSUE TITLE
ElasticSearch2 template?

### ISSUE THREAD

**Issue by chadfurman** [wazuh/wazuh#138]
https://github.com/wazuh/wazuh/blob/master/extensions/logstash/2.x/01-ossec-singlehost.conf#L28

Up a directory in `logstash/` we see the `wazuh` config has replaced this with ElasticSearch 5 

\0/

**Comment by snaow** [comment]
Hi @chadfurman,

You can find Elasticsearch 2 template at: https://github.com/wazuh/wazuh/tree/master/extensions/elasticsearch

Best regards,
Pedro.
