### ISSUE TITLE
Vulnerability detector - Adapt the packages insertion methods to support new AGENTS column

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13817]
| Epic |
| --- |
| #10633 |

## Description

Modify all the `wm_vuldet_insert_agent_data()` method calls and the corresponding queries to populate the new column according to the type of scan and/or the triaged state of every package. The **FULL** scan, for example, copies all the software as **SCAN** but the **PARTIAL** scans considers the **TRIAGED** column.
- The Wazuh-DB helper method `wm_vuldet_get_software()` is configured to get only triaged software or all packages. This helper and the corresponding Wazuh-DB side counterparts need to be updated. All the software must be always returned but now we need an extra field in the JSON payload that corresponds with the **TRIAGED** value. Consider the case for Linux agents also.
- Use the new returned field as a parameter of `wm_vuldet_insert_agent_data()` and also modify the query to correctly fill the new column.

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
