### ISSUE TITLE
Vulnerability detector - New Windows generic CPE insertion

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13818]
| Epic |
| --- |
| #10633 |

## Description

Generate and insert a new, static, and generic Windows CPE that always will be used for dependencies and never for scans (`cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*`). A correct mapping for all the supported Windows versions must be implemented.
This should happen only during the Windows agents' scan.

- Use the new modified call to ` wm_vuldet_insert_agent_data()` to always insert this generic CPE as a dependency.
- Make sure that the **CPE_INDEX** table has the corresponding match in the **AGENTS** table even when this generic "windows" package isn't installed (because this is necessary for the dependencies matching queries).

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
