### ISSUE TITLE
Vulnerability detector - Adapt scanning methods and queries update

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13819]
| Epic |
| --- |
| #10633 |

## Description

Modify all the queries and methods used during the scan so:
-  The scanning methods only use the packages with the new column enabled (**SCAN** value). The `wm_vuldet_find_nvd_vulnerabilities()` method in the **VU_GET_DICT_CPE** query shouldn't get the packages with the new column set in **DEPENDENCY**.
- The dependencies queries always have to use the complete **AGENTS** table so both **SCAN**/**DEPENDENCY** values are valid. 
- The `wm_vuldet_check_nvd_logical()` method and its queries only need the already known bug fixes and the corresponding logical verification
    - The **VU_GET_MATCHES_AND** query should get the `ID_CPE` value instead of `ID`.
    - The bind of the **VU_GET_CPE_AND** query should be in the STMT `stmt_cpe` and not in `stmt_match`
    - The **VU_GET_AGENTCPE_AND** query can't be prepared because it contains a syntax error. I suggest something like `SELECT CPE_INDEX.ID FROM CPE_INDEX INNER JOIN CPE_INDEX CPEI ON CPEI.VENDOR=? AND CPEI.PRODUCT=? AND CPEI.ID<0 INNER JOIN AGENTS AG ON AG.CPE_INDEX_ID = CPEI.ID AND AG.AGENT_ID=?`

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
