### ISSUE TITLE
CVEs database - add new column in the AGENTS table

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13816]
| Epic |
| --- |
| #10633 |

## Description

This table is used during the scan of the agents. Vulnerability Detector can only see the agents' software that it copies temporarily to this table for the scan.

- It may be called SCAN_OR_USE_AS_DEPENDENCY and its value can only be SCAN or DEPENDENCY.
- It has an inverse relation with the TRIAGED column: when the TRIAGED column for a package is TRUE, it means that the package was already scanned so it must be copied to AGENTS with DEPENDENCY.
- The upgrades don't need to be considered because the cve.db database is deleted after the upgrade.

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
