### ISSUE TITLE
Vulnerability detector is not able to detect CVEs that depends on generic windows version - Exploratory session

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13820]
| Epic |
| --- |
| #10633 |

## Description

This issue aims to make a exploratory session of current #10633 development.
It should be confirmed at least that:

- [ ] The new design doesn't alter the current scanner results. No new false positives/negatives are generated.
- [ ] The CVEs that have dependencies, OS or another packages, are properly reported for both partial and full scans in Windows agents. 
- [ ] The scan in Linux agents isn't altered. Also, even when this epic doesn't fix this type of agents, the current behavior for CVEs with dependencies should be tested.
- [ ] The tests cover many different type of Windows OS.

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
