### ISSUE TITLE
Wazuh API rules endpoint fails to read ruleset if rule present with string match for XML tag

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#13824]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.3 | Wazuh API | Manager | any | any |

If you add this rule to local_rules.xml on a Wazuh manager, the Wazuh web interface will fail to show any rules when you go to Management->Rules.
```
  <rule id="104019" level="5">
    <match>\<abc\></match>
    <description>This breaks Wazuh API ability to read ruleset</description>
  </rule>
```
It is clearly some kind of parsing error.  It triggers this in api.log

`2022/06/10 06:00:12 ERROR: Error executing API request locally: Can't pickle <class 'xml.etree.ElementTree.ParseError'>: it's not the same object as xml.etree.ElementTree.ParseError`

For a richer example rule that breaks the rules endpoint of the Wazuh API but still works for analysis purposes:
```
  <rule id="104008" level="5">
    <if_sid>1002</if_sid>
    <match type="pcre2"> \<Error\> - \[ERRCODE: </match>
    <description>Suricata error</description>
  </rule>
```

```
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.3
Type one log per line

7/6/2022 -- 19:34:30 - <Error> - [ERRCODE: SC_ERR_INVALID_IP_NETBLOCK(16)] - failed to parse

**Phase 1: Completed pre-decoding.
        full event: '7/6/2022 -- 19:34:30 - <Error> - [ERRCODE: SC_ERR_INVALID_IP_NETBLOCK(16)] - failed to parse'

**Phase 2: Completed decoding.
        No decoder matched.

**Phase 3: Completed filtering (rules).
        id: '104008'
        level: '5'
        description: 'Suricata error'
        groups: '['syslog', 'bnc']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.

```

**Comment by davidjiglesias** [comment]
Hello @branchnetconsulting,

The proper way to escape `<` and `>` characters in XML is using `&lt;` and `&gt;` respectively.

If I use:

```
  <rule id="104019" level="5">
    <match>&lt;abc&gt;</match>
    <description>This breaks Wazuh API ability to read ruleset</description>
  </rule>
```
Then the API loads it properly.

I understand there are some differences between the API and analysis validation of the ruleset. We are aware of that and we are looking forward to apply a standard and a proper one-way validation with Wazuh v5.0 and the new engine.

**Comment by davidjiglesias** [comment]
Hello again Kevin,

It looks like you are right about the escaping. The other problem is we really want to run away from the API and framework validating the ruleset creation (rules, decoders, cdb-lists), because as you said, it is not a standard or classic XML validation. We have encountered tons of errors and problems similar to this with the ruleset creation in the past few years, and so we need to have analysisd providing a validation tool so the API can act as a mere bridge between the user and the ruleset.

Every related issue related to that has been currently postponed to be included in the new engine validation tools.

I will track and add this one also.

**Comment by branchnetconsulting** [comment]
Thanks David,

It sounds to me like you all are headed in the right direction on this and the broader issue.

Kevin

**Comment by davidjiglesias** [comment]
The new Engine will be in charge of handling the ruleset files, closing this issue.
