### ISSUE TITLE
Vulnerability detector is not able to detect CVEs that depends on generic windows version - QA

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13822]
| Epic |
| --- |
| #10633 |

## Description

**NOTE** :  this issue must be moved to wazuh/wazuh-qa  when the development has been finished

This issue aims to develop IT related to #10633 development.
See https://github.com/wazuh/wazuh-qa/issues/2941 for reference.

## DoD
TBD

**Comment by sebasfalcone** [comment]
Closed as epic won't be implemented
