### ISSUE TITLE
Additional Wazuh-indexer and Wazuh-dashboard auditing

### ISSUE THREAD

**Issue by dami-nicastro** [wazuh/wazuh#13849]
Hi team!
Currently, the `Wazuh-indexer` and `Wazuh-dashboard` only audits the events described in the link below that correspond to the Out of the Box implementation. This information is stored in the `security_auditlog` indices

 https://opensearch.org/docs/latest/security-plugin/audit-logs/index/#tracked-events
 
We need to be able to audit much more actions like Indices deletion/creation and users creation or removal.

Thanks!

**Comment by AlexRuiz7** [comment]
This functionality needs to come from upstream (OpenSearch). The actions over the indices are already audited. Users creation or removal is not.
