### ISSUE TITLE
Wazuh agents disconnect several times a day 

### ISSUE THREAD

**Issue by skhanum** [wazuh/wazuh#13858]
Hello Team,

We are trying to setup Wazuh environment to monitor our business critical Photon and Ubuntu VMs. This is still in testing phase

So far we have onboarded 6 Photon VMs and 6 Ubuntu  VMs to Wazuh manager

We are seeing several Agent disconnected messages/never_connected status on the manager throughout the day. Sometimes when rechecked after a min, the agents get connected and later disconnected/never_connected

From the agent ossec could see the below 
I happen to remove this VM from Manager, and restarted the services on the agent, it showed "Active" in Manager for few hours and again same issue like below

"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Requesting a key from server: 20.230.232.150"}                                
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Verifying manager's certificate"}                                             
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"error","description":"Unable to verify server certificate"}                                        
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Using password specified on file: etc/authd.pass"}                            
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Using agent name as: vmw-hcs-b9e6c50e-e9fa-495b-b3a0-60abc414311c-3254-0-node-
1"}                                                                                                                                                                 
{"timestamp":"2022/06/09 13:43:25","tag":"wazuh-agentd","level":"info","description":"Waiting for server reply"}                                                    
{"timestamp":"2022/06/09 13:43:26","tag":"wazuh-agentd","level":"error","description":"Duplicate name (from manager)"}                                              
{"timestamp":"2022/06/09 13:43:26","tag":"wazuh-agentd","level":"error","description":"Unable to add agent (from manager)"}                                         
{"timestamp":"2022/06/09 13:43:36","tag":"wazuh-agentd","level":"warning","description":"(4101): Waiting for server reply (not started). Tried: '20.230.232.150'."} 
{"timestamp":"2022/06/09 13:43:36","tag":"wazuh-agentd","level":"warning","description":"Unable to connect to any server."}                                         
{"timestamp":"2022/06/09 13:43:36","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/09 13:43:36","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:43:46","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/09 13:43:46","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:43:56","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/09 13:43:56","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:44:06","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/09 13:44:06","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Requesting a key from server: 20.230.232.150"}                                
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Verifying manager's certificate"}                                             
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"error","description":"Unable to verify server certificate"}                                        
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Using agent name as: vmw-hcs-b9e6c50e-e9fa-495b-b3a0-60abc414311c-3254-0-node-
1"}                                                                                                                                                                 
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"info","description":"Waiting for server reply"}                                                    
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"error","description":"Duplicate name (from manager)"}                                              
{"timestamp":"2022/06/09 13:44:16","tag":"wazuh-agentd","level":"error","description":"Unable to add agent (from manager)"} 

Above is just the example for one of the disconnects

Issue 2: 
Not all agents show up in the Manager list 
When connected to anyone of the Managers, not 12 onboarded VMs appear in the list. ( We are yet to setup the dashboard)

Thanks for the help

**Comment by skhanum** [comment]
Another example

{"timestamp":"2022/06/13 16:14:58","tag":"wazuh-agentd","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                         
{"timestamp":"2022/06/13 16:15:38","tag":"wazuh-agentd","level":"error","description":"(1137): Lost connection with manager. Setting lock."}                         
{"timestamp":"2022/06/13 16:15:38","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:15:38","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:15:38","tag":"wazuh-agentd","level":"warning","description":"Process locked due to agent is offline. Waiting for connection..."}         
{"timestamp":"2022/06/13 16:15:39","tag":"wazuh-syscheckd","level":"warning","description":"Process locked due to agent is offline. Waiting for connection..."}      
{"timestamp":"2022/06/13 16:15:48","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:15:48","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:15:58","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:15:58","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:16:02","tag":"wazuh-logcollector","level":"warning","description":"Process locked due to agent is offline. Waiting for connection..."}   
{"timestamp":"2022/06/13 16:16:08","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:16:08","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Requesting a key from server: 20.230.232.150"}                                 
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Verifying manager's certificate"}                                              
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"error","description":"Unable to verify server certificate"}                                         
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Using agent name as: uag-d8caeb2d-ab1a-48f3-ab24-5bcb17246de8"}                
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Waiting for server reply"}                                                     
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Valid key received"}                                                           
{"timestamp":"2022/06/13 16:16:18","tag":"wazuh-agentd","level":"info","description":"Waiting 20 seconds before server connection"}                                  
{"timestamp":"2022/06/13 16:16:38","tag":"wazuh-agentd","level":"info","description":"(1410): Reading authentication keys file."}                                    
{"timestamp":"2022/06/13 16:16:38","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/13 16:16:38","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                       
{"timestamp":"2022/06/13 16:16:38","tag":"wazuh-agentd","level":"info","description":"(4102): Connected to the server (20.230.232.150:1514/tcp)."}                   
{"timestamp":"2022/06/13 16:16:38","tag":"wazuh-agentd","level":"info","description":"Server responded. Releasing lock."}                                            
{"timestamp":"2022/06/13 16:16:39","tag":"wazuh-syscheckd","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                      
{"timestamp":"2022/06/13 16:16:42","tag":"wazuh-logcollector","level":"info","description":"Agent is now online. Process unlocked, continuing..."}                   
{"timestamp":"2022/06/13 16:16:43","tag":"wazuh-agentd","level":"info","description":"Agent is now online. Process unlocked, continuing..."}

**Comment by xrisbarney** [comment]
Hi @skhanum ,

Thank you for using Wazuh!

Please answer the following questions to help us determine what the cause of this issue may be.

- What versions of Wazuh agent and manager are you using? (Note that the manager and the agent have to have the same versions)
- Do all the nodes you intend to connect to the Wazuh manager have unique hostnames? (All agent names should be unique. you can add the agent enrollment variable in the agent ossec.conf file. This configuration can be found [here](https://documentation.wazuh.com/current/user-manual/agent-enrollment/via-agent-configuration/linux-endpoint.html#linux-unix-endpoint).)
- Are you using any extra security options during enrollment? i.e https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/index.html

I am available to help you through this issue. 

Best.

**Comment by skhanum** [comment]
Hello Chris, 

Thanks for helping me out

What versions of Wazuh agent and manager are you using? (Note that the manager and the agent have to be running the same versions or the agent version has to be lower than the manager version)

> Manager version is v4.2.6 and Agents are on v4.3.1 and above on the new VMs we are onboarding, Followed the same steps as https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html to install the agents on the Photon OS and Ubuntu VMs

Do all the nodes you intend to connect to the Wazuh manager have unique hostnames? (All agent names should be unique. you can add the agent enrollment variable in the agent ossec.conf file and give the agents unique names. This configuration can be found [here](https://documentation.wazuh.com/current/user-manual/agent-enrollment/via-agent-configuration/linux-endpoint.html#linux-unix-endpoint).)


> Yes, they all have unique names

Are you using any extra security options during enrollment? i.e https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/index.html

Yes, we using Using password authentication by creating a authd pass file

**Comment by skhanum** [comment]
Hi Chris,

I will have to test this but as we are using the apt get/apt update commands while installing the agents, the newest available agents get downloaded irrespective of Manager version
The agents that were installed last week are of v4.3.1 and above, but the agents running prior as of Manager's version

Meanwhile, the error messages I am seeing the agent ossec logs regarding the duplicate names is the one we might have to check

**Comment by xrisbarney** [comment]
Are the error messages regarding duplicate names occurring on v4.2.6 agents?

I suggest that you pick an agent or 2 with the duplicate name error and add the agent_name parameter in the agent ossec.conf file. See a sample config below:

 ```
   <client>
        <enrollment>
            <agent_name>EXAMPLE_NAME</agent_name>

        </enrollment>
    </client>
```

**Comment by skhanum** [comment]
Let me try the above and share the results

**Comment by skhanum** [comment]
Hello Chris, 

While I was testing this further, I happened to notice the below

We have 2 set of VMs running has HA pair and both of them are talking to one egress IP
Only one of the agents is able to connect with manager at any given point of time. As these 2 VMs share the same egress IP and that is what causing the issue which I suspect
 
When we run manage_agents the agent shows the egress public IP, that means only one agent can connect from that IP. 
However, when we run cluster_control, the agent is showing the private IP on the VM itself. 

I tried  ‘use_source_ip’ option in both the agent registration options and the manager config to ‘yes’ in both locations and re-registering and re-registered it. No luck
manager - https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html?highlight=any#use-source-ip
agent - https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html?highlight=any#use-source-ip

Do we have any such flag that I can use to force the VM IPs instead of egress IP?

**Comment by skhanum** [comment]
Hello @xrisbarney 

Thanks, Let me try the above and keep posted with results
Please do not close this forum till then

I will share my results by EOD or by tomorrow

**Comment by skhanum** [comment]
Hi @xrisbarney 
I wanted to post that I am also exploring various other scenarios and configurations.
Testing results will be posted soon

**Comment by xrisbarney** [comment]
Hi @skhanum,

No problem. The issue will remain open until we come to a resolution.

**Comment by skhanum** [comment]
Current status: Wazuh Manager cert has been expired, 
I am in the process of regenerating it and updating to all the managers
The ossec.conf for <use_source_ip> has been set to NO on both Manager and agents for testing
Once I have the certs in place, I should be in a position to retest it

Will keep you posted

**Comment by skhanum** [comment]
Hi @xrisbarney 

I have ran into a new issue now after regenerating the manager's cert

I followed the same steps as https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html

generate rootCA.pem along with ssl agent cert and sslagent key
Updated the ossec.conf file with the name and path of rootCA pem
Verified the validity and path

Seeing the below in Managers logs

{"timestamp":"2022/06/16 12:58:37","tag":"wazuh-authd","level":"error","description":"Problem with certificate at depth 0"}
{"timestamp":"2022/06/16 12:58:37","tag":"wazuh-authd","level":"error","description":"issuer =  /C=US/ST=CA/O=VMWare Inc"}
{"timestamp":"2022/06/16 12:58:37","tag":"wazuh-authd","level":"error","description":"subject =  /C=US/ST=CA/L=Palo Alto/O=VMWare Inc/OU=IT"}
{"timestamp":"2022/06/16 12:58:37","tag":"wazuh-authd","level":"error","description":"7:certificate signature failure"}
{"timestamp":"2022/06/16 12:58:39","tag":"wazuh-modulesd:syscollector","level":"info","description":"Starting evaluation."}
{"timestamp":"2022/06/16 12:58:40","tag":"wazuh-modulesd:syscollector","level":"info","description":"Evaluation finished."}
{"timestamp":"2022/06/16 12:58:41","tag":"wazuh-authd","level":"error","description":"Problem with certificate at depth 0"}
{"timestamp":"2022/06/16 12:58:41","tag":"wazuh-authd","level":"error","description":"issuer =  /C=US/ST=CA/O=VMWare Inc"}
{"timestamp":"2022/06/16 12:58:41","tag":"wazuh-authd","level":"error","description":"subject =  /C=US/ST=CA/L=Palo Alto/O=VMWare Inc/OU=IT"}
{"timestamp":"2022/06/16 12:58:41","tag":"wazuh-authd","level":"error","description":"7:certificate signature failure"}

In agent

"}                                                                                                                                                                   
{"timestamp":"2022/06/16 13:02:02","tag":"wazuh-agentd","level":"info","description":"Waiting for server reply"}                                                     
{"timestamp":"2022/06/16 13:02:02","tag":"wazuh-agentd","level":"error","description":"SSL read (unable to receive message)"}                                        
{"timestamp":"2022/06/16 13:02:02","tag":"wazuh-agentd","level":"error","description":"If Agent verification is enabled, agent key and certificates may be incorrect!
"}                                                                                                                                                                   
{"timestamp":"2022/06/16 13:02:12","tag":"wazuh-agentd","level":"warning","description":"(4101): Waiting for server reply (not started). Tried: '20.230.232.150'."}  
{"timestamp":"2022/06/16 13:02:12","tag":"wazuh-agentd","level":"warning","description":"Unable to connect to any server."}

**Comment by xrisbarney** [comment]
Hi @skhanum 

The certificate that expired, I was under the impression that the certificates you are regenerating are the indexer, dashboard and manager certificates i.e https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#certificates-creation
> Current status: Wazuh Manager cert has been expired,
I am in the process of regenerating it and updating to all the managers

From the latest issue, I see you are trying to use the agent verification option. Please do the following:

- Ensure that you are not using the password authentication method (so we can isolate the problem):
```
<auth>
  <use_password>no</use_password>
</auth>
```
- Note that you need to copy the sslagent.cert and sslagent.key to the agents you intend to register and specify their paths as well in the agent ossec.conf. https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html#linux-unix-endpoint
- Restart the agent and let me know if the agent enrolls successfully.

**Note:** There are two [agent verification options](https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html#preparations-on-the-wazuh-manager):
- Wazuh agent verification without host validation: You can reuse the sslagent.cert and sslagent.key generated here on different agents because the certificates are generated without specifying the agent IP address or hostname.
- Wazuh agent verification with host validation: You have to generate a new sslagent.cert and sslagent.key for each agent because in the OpenSSL command used to generate these files, you have to specify the agent IP address or hostname.

Additionally, have you been able to register the two sets of VMs running HA without configuring any additional security options?

**Comment by skhanum** [comment]
@xrisbarney 

I disabled below on all the managers and restarted the services 
On the agent, I again restarted the services 

<auth>
  <use_password>no</use_password>
</auth>

From the agent logs

I happen to place the sslagent cert correctly in the path
I feel there is an issue with the newly generated rootCAs.

I have followed this https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html and generated cert  without host validation



{"timestamp":"2022/06/16 14:49:32","tag":"wazuh-agentd","level":"info","description":"Closing connection to server (20.230.232.150:1514/tcp)."}                     
{"timestamp":"2022/06/16 14:49:32","tag":"wazuh-agentd","level":"info","description":"Trying to connect to server (20.230.232.150:1514/tcp)."}                      
{"timestamp":"2022/06/16 14:49:32","tag":"wazuh-agentd","level":"info","description":"Requesting a key from server: 20.230.232.150"}                                
{"timestamp":"2022/06/16 14:49:32","tag":"wazuh-agentd","level":"error","description":"Unable to read certificate file (not found): /var/ossec/etc/sslagent.cert"}  
{"timestamp":"2022/06/16 14:49:32","tag":"wazuh-agentd","level":"error","description":"Could not set up SSL connection! Check certification configuration."}        
{"timestamp":"2022/06/16 14:49:42","tag":"wazuh-agentd","level":"warning","description":"(4101): Waiting for server reply (not started). Tried: '20.230.232.150'."} 
{"timestamp":"2022/06/16 14:49:42","tag":"wazuh-agentd","level":"warning","description":"Unable to connect to any server."}  

> Additionally, have you been able to register the two sets of VMs running HA without configuring any additional security options?

No, I was asked to use with password verification and it worked if I registered only one node, the issue started when I registered other node from same HA node as the secondary node shared the same egress IP

**Comment by skhanum** [comment]
Hello @xrisbarney 
The certificate part is taken care and we were able to update them succesfully

Now, I am trying to figure out the egress IP and the suggestions posted in the previous comment

**Comment by skhanum** [comment]
Hello @xrisbarney 

For certificate renewal, I had to stop the services on all the other nodes which had same egress IP and test it on one VM and I was able to make it work : https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html

And good news on the egress IP issue.

We had to tweak the ossec.conf on Manager with below

<use_source_ip>no</use_source_ip>
<force_insert>no</force_insert>
.
.
<use_password>yes</use_password>

Agent

No flag/setting was added local agent ossec side
Deleted the client.keys on agent file
Restarted the services on agent
I was able to see the nodes reporting as "any"

Testing is further in progress
We should be able to resolve this by tomorrow :)
