### ISSUE TITLE
Syscollector: installed packages on CentOS with installed dpkg

### ISSUE THREAD

**Issue by fgrosse19** [wazuh/wazuh#1385]
Hi guys,

we have the problem, that on some of our CentOS 7.5 agents the syscollctor cannot detect the installed packages. We receive no error, but the package list and also the database are just empty.

I turned on the debug mode of wazuh-modulesd on one of the agents and I saw this:
> 2018/09/21 10:58:09 wazuh-modulesd:syscollector: DEBUG: Starting installed packages inventory.
> 2018/09/21 10:58:09 wazuh-modulesd:syscollector: DEBUG: sys_deb_packages() sending '{"type":"program_end","ID":1796550848,"timestamp":"2018/09/21 10:58:09"}'
> 2018/09/21 10:58:09 wazuh-modulesd:syscollector: DEBUG: Starting ports inventory.

On an CentOS-Agent, where the syscollector detects all packages, the output looks like this:
> 2018/09/21 11:08:25 wazuh-modulesd:syscollector: DEBUG: Starting installed packages inventory.
> 2018/09/21 11:08:25 wazuh-modulesd:syscollector: DEBUG: sys_rpm_packages() sending '{"type":"program","ID":175656463,"timestamp":"2018/09/21 11:08:25","program":{"format":"rpm","name":"freetype","description":"A free and portable font rendering engine","size":877,"vendor":"CentOS","group":"System Environment/Libraries","architecture":"x86_64","install_time":"2017/09/14 15:12:17","version":"2.4.11-15.el7"}}'

Seems to me that on the agents, where the inventory does not work, the wrong function is called and it searches for deb-packages (and finds none) and not for rpm-packages.

After short search I found this in the code:
> void sys_packages_linux(int queue_fd, const char* LOCATION) {
> 
>     DIR *dir;
> 
>     mtdebug1(WM_SYS_LOGTAG, "Starting installed packages inventory.");
> 
>     if ((dir = opendir("/var/lib/dpkg/"))){
>         closedir(dir);
>         if (sys_deb_packages(queue_fd, LOCATION) < 0) {
>             mterror(WM_SYS_LOGTAG, "Unable to get debian packages due to: %s", strerror(errno));
>         }
>     } else if ((dir = opendir("/var/lib/rpm/"))){
>         closedir(dir);
>         if (sys_rpm_packages(queue_fd, LOCATION) < 0) {
>             mterror(WM_SYS_LOGTAG, "Unable to get rpm packages due to: %s", strerror(errno));
>         }
>     }
> }

If I am right the agents checks if the folder /var/lib/dpkg exists and only if not, it looks for /var/lib/rpm and rpm packages. And if the folder exists it searches only for deb packages.

We have dpkg installed on the CentOS-Agents, where the inventory does not work, because we need it for some of our scripts and because of that the folder /var/lib/dpkg exists and no rpm packages are collected. When we remove dpkg the inventory works fine and all packages are collected but this is no option for our scripts.

Is it possible to make the syscollector also work on our CentOS-agents with dpkg?
Maybe just remove the "else"?

Our agents are running wazuh 3.6.1 installed from repositories.

Please tell me if you need any further information.

Best regards,
Florian

**Comment by chemamartinez** [comment]
Hi @fgrosse19,

Thank you for reporting this misfunction in the package inventory. It is clear is a design issue and it has already fixed at https://github.com/wazuh/wazuh/pull/2168.

It will be included in the next released version.

Thank you for your feedback again.

Best regards,
Chema.
