### ISSUE TITLE
Invalid CPU information retrieved from macOS agents

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#13859]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| up to master | Syscollector - Sysinfo| Agent | Any | macOS |

## Description

Currently, macOS agents are wrongly reporting CPU information, showing the Model Identifier rather than the proper CPU information

### Step to reproduce
1- Install Wazuh Agent on any macOS OS
2- Validate that syscollector wodle is enabled and hardware scan is set to yes
3- Connect the agent to the manager
4- Open Wazuh Dashboard and see the agent's hardware inventory
### Expected behavior 
CPU shows specific information like `Apple M1`
### Current behavior
CPU shows invalid information like `VirtualMac2,1`
### RCA
The problem seems to be that HWMODEL (macOS Model Identifier) is treated like CPU information  https://github.com/wazuh/wazuh/blob/3d9e9ac429d439d48506e684eadebd8909727413/src/data_provider/src/sysInfoCommonBSD.cpp#L43
```
system_profiler SPHardwareDataTypesystem_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: Apple Virtual Machine 1
      Model Identifier: VirtualMac2,1
      Chip: Apple M1 (Virtual)
      Total Number of Cores: 2
      Memory: 2 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3
      Serial Number (system): Z7TKGVKMXJ
      Hardware UUID: E7A5E4FB-F682-5556-A7F7-2A1D5F1BA18F
      Provisioning UDID: 0000FE00-46950F39FF03845E
      Activation Lock Status: Disabled

```

**Comment by mjcr99** [comment]
Hi team,

the issue is still present in 4.8.0, is related to the `cpuName()` method implementation.
