### ISSUE TITLE
Add missing use cases to Microsoft Windows rules

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#13861]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | Wazuh Agent | Agent | Packages | Windows |

Hello team,

I've been asked with a specific use case for the Wazuh Agent for Windows based on next documents from Microsoft:
- https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection#appendix-e--annotated-baseline-subscription-event-query
- https://docs.microsoft.com/en-us/windows/security/threat-protection/use-windows-event-forwarding-to-assist-in-intrusion-detection#appendix-f--annotated-suspect-subscription-event-query

You'll see there that Microsoft provides specific queries to run in order to help with intrusion detection.
I find this **very useful** and I believe Wazuh can benefit from these queries by adding them as rules working alongside the correspondent `localfile` modules, thus improving its intrusion detection capabilities.

Most of the queries, are specific for the `Application`, `Security` and `System` Windows event channels, but there are many for other channels.

As far as I checked, I noticed this situation:
- There are Windows events that trigger a rule with level > 3
- There are Windows events that trigger a rule with level = 0
- There are Windows events that trigger no rule

So in order to implement this, we'll need to:
- Add the `localfile` modules for the remaining channels into a Windows Agent.
- Test which events actually trigger a rule by generating the events.
- Create rules accordingly.

**Comment by hitman28594** [comment]
Just my input on this:

The default windows rules in wazuh are quiet high level. The default localfile configuration for eventchannel don’t capture many channels. 

I have found that scraping the information from the windows event schema(s) provides a summary of all the different “eventchannel+eventID” combinations from windows agents


https://docs.microsoft.com/en-us/windows/win32/wes/eventschema-schema



Wazuh has alot of rules which only specify an eventID which have been seen to cause false positives whenever other channels use the same eventID. 

Scraping the different channels:eventID:descriptions from the above schema makes it much easier to script the creation of rules for specific eventChannels. 
  - this method creates a high level “log management” ruleset. 
  - Threat detection rules can then be created as child rules. 
  
This method makes the windows ruleset structures much more specific, organised and manageable… especially in large complex environments. It also helps wazuh admins to have more control over how to organise the different log events. 

The hunting queries provided by Microsoft can change over time, ideally you would want a reproducible and semi-automated method of creating the relevant rules.

**Comment by fabamatic** [comment]
The queries are useful for hunting but are not threat detections themselves, so these rules would have to be very low level, **only helpful for threat analysts** that know what to look for.
Also the Microsoft document makes clear that most of the baseline queries would work with minimal (default?) logging configuration and that configuration can be implemented across all devices while the suspect queries configuration should only be pushed to devices where unusual activity is detected, generating a much larger volume of logs. If we implement this we should make clear which logging configuration steps are needed to take advantage of the rules.

Will implement baseline first, the aim is to have all related events trigger a rule with level 3.

**Comment by ooniagbi** [comment]
https://github.com/wazuh/wazuh/pull/22328 merged!
