### ISSUE TITLE
Standardize time zone in InstallDate field in Windows package information

### ISSUE THREAD

**Issue by HanesSciarrone** [wazuh/wazuh#13884]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| up to master | Syscollector - Sysinfo| Agent | Any | Windows |

## Description 

Currently, SysInfo in Windows agents is reporting the `install_time` field with the system's local time. It would be great if the time in this field could be in a standard format such as UTC to synchronize with the same time zone the `install_time` field in all agents.

### Step to reproduce

- Download the 7-Zip installer or download Telegram from the Windows Store.
- Install it and check the current time of installation.
- Run the test tool or scan the packages with the agent and validate the `install_time` of the installed package.

### Expected behavior

The `install_time` field shows the time in UTC format

### Current behavior

The `install_time` field shows the system's local time

**Comment by MiguelazoDS** [comment]
Update 05/24/23

Issue https://github.com/wazuh/wazuh-jenkins/issues/5109 was closed but related now to https://github.com/wazuh/wazuh-jenkins/issues/5114

**Comment by MiguelazoDS** [comment]
## Update 06/02/23 

After rebase checks passed.
