### ISSUE TITLE
ARM64 packages of indexer and dashboard

### ISSUE THREAD

**Issue by shoothub** [wazuh/wazuh#13903]
Hello,
I wanted to install Wazuh 4.3.4 all in one on Oracle Cloud with Ampere ARM64 virtual machine on Ubuntu ARM64 using ansible, but found that packages wazuh-indexer and wazuh-dashboard are not available for this platform (only manager and agent are available). Can you please create these packages also for ARM64 platform. OpenSearch has also binary packages (rpm and also yum repository) and docker images for ARM64, so it should be no such big problem to generate them also for Wazuh. Or can I use official opensearch and dashboard packages in the meantime instead of Wazuh's ones?

**Comment by kovalroma** [comment]
Hello, how is your progress? Any luck?

**Comment by kovalroma** [comment]
@shoothub I found this article. [How to install a Wazuh SIEM server on a Raspberry Pi 4B](https://jacobriggs.io/blog/posts/how-to-install-a-wazuh-siem-server-on-a-raspberry-pi-4b-26.html) If am not wrong the CPU on Raspb4 has the same architecture as is in Oracle Cloud.

**Comment by ObJuanK** [comment]
@kovalroma just ran through the article and it is very outdated. Opendistro has ben archived since May 22, may be able to use OpenSearch as an alternative but that's a little beyond my capabilities. Would be nice to get native ARM64 support

**Comment by AlexRuiz7** [comment]
As for now, we won't support ARM64 on Indexer and Dashboard.
