### ISSUE TITLE
Wazuh Manager ossec.conf global configuration won't update all agents

### ISSUE THREAD

**Issue by Evacch** [wazuh/wazuh#13916]
I added FIM realtime configuration in Wazuh manager ossec.conf and got it restart with command "systemctl restart wazuh-agent", I tried to add new files in both Wazuh manager server and one of the Wazuh agent servers, the FIM only detected Wazuh manager server added new file but not for Wazuh agent server.

**Comment by antoniomanuelfr** [comment]
Hello @Evacch 

All the options configured in the manager's `ossec.conf` will only apply to the manager itself, not to the agents connected to that specific manager.
For using the centralized configuration, all the options must be added to the file `/var/ossec/etc/shared/<group>/agent.conf` (replacing `<group>` by the name of the group assigned to that agent).

You can get more information in the following links of the documentation:
- https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html?highlight=centralized
- https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html?highlight=centralized#agent-groups
- https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html?highlight=centralized#agent-groups

**Comment by antoniomanuelfr** [comment]
I'm closing this issue. Don't hesitate to contact us again if you have any question.
