### ISSUE TITLE
AWS-Cloudwatch logs not been shown on dashboard

### ISSUE THREAD

**Issue by usmanaa10** [wazuh/wazuh#13918]
### Discussed in https://github.com/wazuh/wazuh/discussions/13917

<div type='discussions-op-text'>

<sup>Originally posted by **usmanaa10** June 20, 2022</sup>
Hi Friends,
               I have configured aws cloudwatch and didnt see logs on wazuh dashboard..
1) getting no error in ossec.log
2) run wodle manually and got the following output
![cloudwatch](https://user-images.githubusercontent.com/66419518/174558476-3eb8717b-b5e0-4a8b-a9c2-a1e1fb1be6da.png)

Can  anyone take out of this problem. ASAP.. Please?

Regards</div>

**Comment by CarlosRS9** [comment]
This was answered in https://github.com/wazuh/wazuh/discussions/13917
