### ISSUE TITLE
Manual SCA Scan

### ISSUE THREAD

**Issue by ridwansyah15** [wazuh/wazuh#13934]
Hi there..

Is it possible for me to configure manual triggering for Wazuh's SCA Scan?
From the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/sca.html), all I see is automatic scheduling either using interval, day, wday, or time.

If there is a way for it, let me know.
Thank you in advance.

**Comment by 72nomada** [comment]
Hi @ridwansyah15, there are two ways to run SCA: interval or restart wazuh-agent. For manual triggering, the best option is to restart the wazuh-agent. 

I hope this helps.

**Comment by ridwansyah15** [comment]
Thank you so much for your reply sir @72nomada, I really hope for manual scan feature from Wazuh's dashboard in the future. 

For now I'm just following your suggestion.

**Comment by 72nomada** [comment]
Thanks a lot. We will include your request. 

I'm closing this, if you need anything ping me.
