### ISSUE TITLE
Add WARNING log message for API rate limit exceeded for Github and Office365 Integration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#13944]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.5-40317 | Github Integration | Manager | Packages | Centos8 |

Outdated:  https://github.com/wazuh/wazuh/issues/13944#issuecomment-1164168755

## Description

During the testing of the new changes introduced in version `4.3.5` related to the GitHub integration (https://github.com/wazuh/wazuh/pull/13898) it has been detected that no warning is generated in the `ossec.log` when the API rate limit exceeded. 
This event triggers the alert the `91448`, `GitHub module internal event, 3 request fail`. However, it could be desirable to inform of this situation in the `ossec.log`.

## Evidences

**Wazuh-manager ossec.log**

```
2022/06/22 15:09:44 wazuh-modulesd:github[88362] wm_github.c:225 at wm_github_execute_scan(): DEBUG: Scanning organization: 'QATesting123451'
2022/06/22 15:09:44 wazuh-modulesd:github[88362] wm_github.c:273 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'https://api.github.com/orgs/QATesting123451/audit-log?phrase=created:2022-06-22T15:03:04Z..2022-06-22T15:09:14Z&include=git&order=asc&per_page=100'
2022/06/22 15:09:44 wazuh-modulesd:github[88362] wm_github.c:273 at wm_github_execute_scan(): DEBUG: GitHub API URL: 'https://api.github.com/orgs/QATesting123451/audit-log?phrase=created:2022-06-22T15:03:04Z..2022-06-22T15:09:14Z&include=web&order=asc&per_page=100'
```

**Archives log**
```
2022 Jun 22 15:04:35 centos1->github {"integration":"github","github":{"actor":"wazuh","organization":"QATesting123451","event_type":"web","response":"{\"message\":\"API rate limit exceeded for user ID 107986604.\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}"}}
```

**Alert.log**
```
** Alert 1655910275.6099: - github,git,
2022 Jun 22 15:04:35 centos1->github
Rule: 91448 (level 3) -> 'GitHub module internal event, 3 request fail.'
{"integration":"github","github":{"actor":"wazuh","organization":"QATesting123451","event_type":"web","response":"{\"message\":\"API rate limit exceeded for user ID 107986604.\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}"}}
integration: github
github.actor: wazuh
github.organization: QATesting123451
github.event_type: web
github.response: {"message":"API rate limit exceeded for user ID 107986604.","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

# Steps to reproduce

**On Wazuh-manager side**

- `ossec.conf`
```
<github>
    <enabled>yes</enabled>
    <interval>20s</interval>
    <time_delay>30s</time_delay>
    <curl_max_size>1M</curl_max_size>
    <api_auth>
        <org_name>ORG1</org_name>
        <api_token>APITOKEN1</api_token>
    </api_auth>
</github>
```

- `local_internal_ioptions.conf`
```
wazuh_modules.debug=2
```

- Restart the manager to make the changes effective.

  ```
  systemctl restart wazuh-manager
  ```

- Use a custom script to exceed the API rate limit. Something like the following
```
for((i=0;i<15000;i++)) do
    curl -H "Authorization: token TOKEN" --request GET https://api.github.com/orgs/ORGANIZATION/audit-log&order=asc&per_page=100
done
```
- Check in the `ossec.log` that no WARNING has been generated

**Comment by Rebits** [comment]
After talking with @TomasTurina it seems that a warning message is indeed generated when the integration does not succeed.
However, this occurs on the third attempt and it will no longer appear during the manager's uptime.
I suggest including an INFO message, shown when GitHub integration works again after the WARNING message.

**Comment by cborla** [comment]
After talking with @TomasTurina we decide including the message `INFO: API github connection successfully`, for both integration, Github and Office365, shown when the integration works again after the WARNING message.
