### ISSUE TITLE
Wazuh does not start on RHEL9 Docker if PS is not installed

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#13947]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5.0| apid / execd | Manager and Agent | Packages | RHEL9 Docker |

# Description
During Manual Testing issue [#3019](https://github.com/wazuh/wazuh-qa/issues/3019) it was found that when trying to start Wazuh Manager or Agent on a RHEL9 Docker container, it would not start. It would fail to start with the following errors:

### Wazuh Manager
```
Complete!
[10:14] /var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.2...
wazuh-apid: Process 931 not used by Wazuh, removing...
wazuh-apid did not start correctly.
```
### Wazuh Agent
```
/var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.2...
wazuh-execd: Process 816 not used by Wazuh, removing ...
wazuh-execd did not start
```

It was found that the `ps` command was not present in the [base image for rhel 9](https://hub.docker.com/r/redhat/ubi9). This command is needed for starting the affected modules. After installing the module with the command `yum install procps`, Wazuh starts properly.

```
Installed:
  procps-ng-3.3.17-4.el9.x86_64                                                                      

Complete!
[root@1b5352d0a87a ~]# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.3.2...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

It should be checked that if the `ps` command is not present, a clearer error message is shown to the user so this can be fixed.

**Comment by davidjiglesias** [comment]
Related to #18143.

We should do some further investigation as to why some of the QA machines do not have ps.
