### ISSUE TITLE
Wazuh 4.3 - SCA policies manual tests - SCA Ubuntu 22.04 policy

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#13940]
### References: 

- SCA policy:https://raw.githubusercontent.com/wazuh/wazuh/7c82ac74b35a43a70749e948b90a6d50c1b7f474/ruleset/sca/ubuntu/cis_ubuntu22-04.yml
- CIS Benchmark: https://downloads.cisecurity.org/download?u=1655899645
- Ubuntu VM: https://app.vagrantup.com/bento/boxes/ubuntu-22.04

### Resutls:
![image](https://user-images.githubusercontent.com/16334770/175028814-418b1b60-61dd-4192-9a6d-c392694bd995.png)

- Checks output: [cis_ubuntu22-04.csv](https://github.com/wazuh/wazuh/files/8957471/cis_ubuntu22-04.csv)
- Scan duration : `5 seconds` 

### Verification: Day 1

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28500 | Failed |![image](https://user-images.githubusercontent.com/16334770/175030540-76fa5ca9-a2e3-416f-a319-22b5a75f92d7.png) | :heavy_check_mark:  | :heavy_check_mark:  |
| 28501 | Failed |![image](https://user-images.githubusercontent.com/16334770/175030998-42472c4a-3c24-4216-8c68-e992ce0ac02a.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28502 | Failed |![image](https://user-images.githubusercontent.com/16334770/175255942-66a3c27b-63d2-49ab-bfd2-28cca9de5bd5.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28503 | Failed |![image](https://user-images.githubusercontent.com/16334770/175256793-c2abe258-8a04-4eb6-b934-73420f1de295.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28504 | Failed |![image](https://user-images.githubusercontent.com/16334770/175257594-ba85878c-258d-4a25-bf96-42d135f58021.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28505 | Failed |![image](https://user-images.githubusercontent.com/16334770/175259937-07e4d464-33d3-43f2-860e-02d8a6f8eeb4.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28506 | Failed |![image](https://user-images.githubusercontent.com/16334770/175260501-54c97e25-937e-4b60-9b93-6577ab50ffc4.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28507 | Failed |![image](https://user-images.githubusercontent.com/16334770/175262170-aff2f0bb-7672-4e08-afdf-197ce44fd033.png)| :heavy_check_mark:  | :heavy_check_mark:  |
| 28508 | Failed |![image](https://user-images.githubusercontent.com/16334770/175263387-39c54946-f9ec-4076-97c7-d4e37a8e389a.png)| :heavy_multiplication_x:   | :heavy_check_mark:  | 
| 28509 | Failed |![image](https://user-images.githubusercontent.com/16334770/175265588-38dcff3a-72b1-46f2-bbd1-281aa1ca8fb7.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28510 | Failed |![image](https://user-images.githubusercontent.com/16334770/175268131-8e2aa6b8-4ef4-42d5-b592-3430ed2e02ae.png)| :heavy_multiplication_x:    | :heavy_multiplication_x:   |
| 28511 | Passed |![image](https://user-images.githubusercontent.com/16334770/175269308-b978d8de-c5ab-451f-9f46-c1bb6363c3d3.png)| :heavy_check_mark:   | :heavy_check_mark:   |
| 28512 | Passed |![image](https://user-images.githubusercontent.com/16334770/175277505-cb229201-b0ec-41f7-9a5d-ad112f45a56e.png)| :heavy_check_mark:   | :heavy_check_mark:   |
| 28513 | Failed |![image](https://user-images.githubusercontent.com/16334770/175279244-469066e6-b57d-4892-9b03-cf8a7fafebe2.png)| :heavy_check_mark:   | :heavy_check_mark:   |
| 28514 | Failed |![image](https://user-images.githubusercontent.com/16334770/175281046-3cd7ad21-f98c-4662-ba05-32076901bd9e.png)| :heavy_check_mark:   | :heavy_check_mark:   | 
| 28515 | Failed |![image](https://user-images.githubusercontent.com/16334770/175282608-a9cd1cde-21d3-4b4f-a956-67d852d1afcd.png)| :heavy_check_mark:   | :heavy_check_mark:   |
| 28516 | Failed |![image](https://user-images.githubusercontent.com/16334770/175283166-34e9f732-e258-41f0-97c6-86d2f7a06857.png)| :heavy_check_mark:   | :heavy_check_mark:   |
| 28517 | Failed |![image](https://user-images.githubusercontent.com/16334770/175283941-d1c739cc-61bc-4b5c-b8c2-4a9c57f6e63a.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28518 | Failed |![image](https://user-images.githubusercontent.com/16334770/175285553-1a9df423-8909-443f-b5f7-021f034f2042.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28519 | Failed |![image](https://user-images.githubusercontent.com/16334770/175285776-5d05b536-ff24-4e5d-9199-7818752eaf9a.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28520 | Failed |![image](https://user-images.githubusercontent.com/16334770/175285979-47c144e1-4614-47e1-a1d4-9e7bd2c5997b.png)| :heavy_check_mark:   | :heavy_check_mark:  | 
| 28521 | Failed |![image](https://user-images.githubusercontent.com/16334770/175286574-0f844dff-0219-4c30-a0e1-f132622a2c1b.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28522 | Failed |![image](https://user-images.githubusercontent.com/16334770/175288035-3fa8a4f6-bc8c-42c6-92ed-fd0c78eeba7d.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28523 | Passed |![image](https://user-images.githubusercontent.com/16334770/175288582-69cd9e12-51eb-48df-86bc-249dce9081ef.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28524 | Failed |![image](https://user-images.githubusercontent.com/16334770/175289181-18388794-1d16-4107-a2a5-cff4b6d0fece.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28525 | Failed |![image](https://user-images.githubusercontent.com/16334770/175290870-00e7ba87-0e57-4f46-af56-c5a9ab8b47fe.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28526| Failed |![image](https://user-images.githubusercontent.com/16334770/175293033-06d0c71e-97e4-497b-9b72-8ad627d675ae.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28527| Failed |![image](https://user-images.githubusercontent.com/16334770/175293430-84cea979-abde-41fe-910c-763d9b21a0cd.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28528| Failed |![image](https://user-images.githubusercontent.com/16334770/175296085-6b072e1e-56ce-4235-93ba-5c61e6108c3d.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28529| Failed |![image](https://user-images.githubusercontent.com/16334770/175296454-a6480070-d88c-4901-9384-91581fc1e15f.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28530| Passed |![image](https://user-images.githubusercontent.com/16334770/175296731-2618b760-1504-4f66-9e87-2e314297426d.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28531| Failed |![image](https://user-images.githubusercontent.com/16334770/175298787-58bae148-38f2-4a72-98ff-97a2b598197b.png)| :heavy_check_mark:   | :heavy_multiplication_x:  |
| 28532| Passed |![image](https://user-images.githubusercontent.com/16334770/175300489-e0503258-f151-4989-a81b-55f6d85a8849.png)| :heavy_check_mark:   | :heavy_check_mark:  |
| 28533| Failed |![image](https://user-images.githubusercontent.com/16334770/175302521-ea5e9618-9071-4470-be54-6c3a7055c215.png)| :heavy_check_mark:   | :heavy_check_mark:  |

**Comment by 72nomada** [comment]
### check 28531. 

The grep command provides error code 2, which means a folder is empty or doesn't exist for the command.

```
root@jjsrv:/var/ossec/ruleset/sca# grep -Es "^\s*kernel\.randomize_va_space\s*=\s*([0-1]|[3-9]|[1-9][0-9]+)" /etc/sysctl.conf /etc/sysctl.d/*.conf /usr/lib/sysctl.d/*.conf /usr/local/lib/sysctl.d/*.conf /run/sysctl.d/*.conf
root@jjsrv:/var/ossec/ruleset/sca# echo $?
2
```

We will try to reword the rule using _d:_ and _f:_ commands.

**Comment by 72nomada** [comment]
Checks review ( texts commit [13365a9](https://github.com/wazuh/wazuh/pull/13893/commits/13365a92927ca9ee28051df313540e8ec7470cb4), rule commit [100c2f7](https://github.com/wazuh/wazuh/pull/13893/commits/100c2f74f3ea8261395ecb39d4fe25eea3ad078f))

|Check ID| Description |Outcome|Observations|
|---|---|---|---|
|28507|Modified|--| Remediation field changed|
|28508|Modified|--| Changed 'set userid' to 'setuid'| 
|28509|Not changed|--| Can't find the problem, rationale seems to be correct|
|28510|Modified|--| Changed 'tmpfsat' to 'tmpfs at'.|
|||Modified| changed rule to       - 'c:findmnt -n /dev/shm-> r:^/dev/shm\s'|

```
Check 28510

2022/06/24 05:24:31 sca[2096] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:findmnt -n /dev/shm-> r:^/dev/shm\s'
2022/06/24 05:24:31 sca[2096] wm_sca.c:1128 at wm_sca_do_scan(): DEBUG: Running command: 'findmnt -n /dev/shm-> r:^/dev/shm\s'
2022/06/24 05:24:31 sca[2096] wm_sca.c:1619 at wm_sca_read_command(): DEBUG: No pattern given. Returning FOUND.
2022/06/24 05:24:31 sca[2096] wm_sca.c:1131 at wm_sca_do_scan(): DEBUG: Command output matched.
2022/06/24 05:24:31 sca[2096] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:findmnt -n /dev/shm-> r:^/dev/shm\s': 1
2022/06/24 05:24:31 sca[2096] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 28510 'Ensure /dev/shm is configured.' -> 1
2022/06/24 05:24:31 sca[2096] wm_sca.c:479 at wm_sca_read_files(): DEBUG: Calculating hash for scanned results.
2022/06/24 05:24:31 sca[2096] wm_sca.c:2802 at wm_sca_hash_integrity(): DEBUG: Concatenating check results:
2022/06/24 05:24:31 sca[2096] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 28510; Result: 'passed'

```

**Comment by elwali10** [comment]
### Verification: Day 2 

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28534 | Passed |![image](https://user-images.githubusercontent.com/16334770/175495801-8fcbf87e-6ac8-4d84-99e4-fd98b6b66d84.png) | :heavy_check_mark:  | :heavy_check_mark:  |
| 28535 | Passed |![image](https://user-images.githubusercontent.com/16334770/175496696-b543c969-f918-48d1-9700-fd3b7f35460d.png)| :heavy_multiplication_x:  | :heavy_multiplication_x:   |

**Comment by alejandroorg** [comment]
### Verification: Day 2 Starting from the end

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28534 | Passed | | :heavy_check_mark:  | :heavy_check_mark:  |

**Comment by elwali10** [comment]
### Verification: Day 3

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28565 |  | |   |   |

**Comment by elwali10** [comment]
### Verification: Day 4

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28601| Passed |![image](https://user-images.githubusercontent.com/16334770/176103564-6ad689d9-f756-46ba-81e2-fe5170b08862.png)|  :heavy_multiplication_x:  |  :heavy_check_mark:  |

**Comment by alejandroorg** [comment]
### Verification: Day 4 Starting from the end

|Check ID|Check result|Check output|Matching description|Valid outcome|
|---|---|---|---|---|
| 28677 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28676 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28675 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28674 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28673 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28672 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28671 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28670 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28669 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28668 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28667 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
| 28666 |  |  | :heavy_check_mark:  | :heavy_check_mark:  |
