### ISSUE TITLE
Ensure XD/NX support is enabled it is not precise enough

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#13949]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.5-40317 | SCA | Manager | Packages | AmazonLinux2 |

## Description

During the manual testing of the new changes introduced in version `4.3.5` related to the SCA (https://github.com/wazuh/wazuh-qa/issues/3014), it has been detected that check `Ensure XD/NX support is enabled` is not precise enough.

This check uses the following rules under `any` condition:
```
    condition: any
    rules:
      - 'c:sh -c "journalctl | grep \"protection: active\"" -> r:protection: active'
      - 'not c:sh -c "[[ -n $(grep noexec[0-9]*=off /proc/cmdline) || -z $(grep -E -i \" (pae|nx) \" /proc/cpuinfo) || -n $(grep \"\\sNX\\s.*\\sprotection:\\s\" /var/log/dmesg | grep -v active) ]] && echo \"NX Protection is not active\"" -> r:^NX Protection is not active$'
```

However, in we manual disable the XD/NX support, these rules will not effectively evaluate this condition.

## Evidences

Evidence can be found at https://github.com/wazuh/wazuh-qa/issues/3014#issuecomment-1161430155.

## Steps to reproduce

- Disable the XD/NX support

```
grubby --update-kernel=ALL --args="noexec=off"
```

- Reboot the host
- Ensure new kernel parameters are correct:
```
cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-5.10.112-108.499.amzn2.x86_64 root=UUID=008cdb03-aa96-41b3-8e92-b11c5b511efd ro console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 nvme_core.io_timeout=4294967295 rd.emergency=poweroff rd.shell=0 LANG=en_US.UTF-8 noexec=off
```
- Run SCA scan and check that check `20529` do not update as failed.

We can also check manually the commands:

```
journalctl | grep "protection: active" 
Jun 21 09:30:39 localhost kernel: NX (Execute Disable) protection: active
Jun 21 09:39:48 localhost kernel: NX (Execute Disable) protection: active
Jun 21 09:54:44 localhost kernel: NX (Execute Disable) protection: active
```
Those messages fit `r:protection: active` regex. However, if we show full `journalctl` logs:
```
Jun 21 09:30:39 localhost kernel: NX (Execute Disable) protection: active
Jun 21 09:39:48 localhost kernel: NX (Execute Disable) protection: active
Jun 21 10:04:21 localhost kernel: NX (Execute Disable) protection: disabled by kernel command line option
Jun 21 09:54:44 localhost kernel: NX (Execute Disable) protection: active
Jun 21 10:04:21 localhost kernel: NX (Execute Disable) protection: disabled by kernel command line option
```
The current state of the host is the last message, so, NX is disabled, but this regex has not worked correctly for this case.

**Comment by jnasselle** [comment]
Hi @Rebits and @72nomada ,

It seems that using the whole system journalctl might also cause false detections. @sebasfalcone test it [here](https://github.com/wazuh/wazuh/issues/14268#issuecomment-1186279908), and state that any log that contains `\"protection: active\"` could affect the result

A possible solution could be to limit journalctl to kernel events and only since boot by adding parameters `-k --boot`
