### ISSUE TITLE
GitHub Integration - The integration with GitHub is not working

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh#13951]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | Github | Manager | Packages/Sources | CentOS-8 |

## Description
When you try to integrate Wazuh with GitHub an error appears in Wazuh logs and an the alert 91448 is trigerred.

## Evidences

Logs in `/var/ossec/logs/ossec.log`:

 ```
    2022/06/22 16:42:04 wazuh-modulesd:github: WARNING: Sending GitHub internal message: '{"integration":"github","github":{"actor":"wazuh","organization":"testing-wazuh","event_type":"git","response":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#get-audit-log\"}"}}'`
  ```

Logs in `/var/ossec/logs/alerts/alerts.log`: 

  ```
    ** Alert 1655915278.8202643: - github,git,
        2022 Jun 22 16:27:58 centos-manager1->github
        Rule: 91448 (level 3) -> 'GitHub module internal event, 3 request fail.'
        {"integration":"github","github":{"actor":"wazuh","organization":"testing-wazuh","event_type":"web","response":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#get-audit-log\"}"}}
        integration: github
        github.actor: wazuh
        github.organization: testing-wazuh
        github.event_type: web
        github.response: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/orgs#get-audit-log"}
  ```
## Steps to reproduce
1. Generate an Enterprise Cloud account organization
2. Generated a personal token from the account linked to the organization
3. Add the configuration in `/var/ossec/etc/ossec.conf`:
    ```
    <github>
        <enabled>yes</enabled>
        <interval>10s</interval>
        <time_delay>30s</time_delay>
        <curl_max_size>1M</curl_max_size>
        <only_future_events>yes</only_future_events>
        <api_auth>
            <org_name>YOUR-ORGANIZATION</org_name>
            <api_token>API_TOKEN_FROM_PERSONAL_GITHUB_ACCOUNT</api_token>
        </api_auth>
        <api_parameters>
            <event_type>all</event_type>
        </api_parameters>
    </github>
    ```
4. Restart the Wazuh Manager in order to apply changes
5. Wait a couple of seconds and check logs in ossec.log and alerts.log to see the logs describe on evidecnce section

---

**Current Result:** GitHub integration not working

**Expected Result:** The GitHub integration should work correctly

**Comment by CamiRomero** [comment]
This Issue will be closed because we detected that it is a configuration error.

**Comment by rsitro-chrono** [comment]
@CamiRomero what was your configuration error because I am having the same issue

**Comment by Sahil-Nference** [comment]
@CamiRomero @rsitro-chrono 
could you please share your insights on the configuration error. I am in a similar situation here.

**Comment by CauchY75** [comment]
Same issue Here ! We need to learn what is the configuration Error ?

**Comment by Sahil-Nference** [comment]
@CauchY75 Yes,
As per the Wazuh ocumentation, only changing conf file and adding organisation admin token should do, but wazuh is throwing similar rule ID.
