### ISSUE TITLE
Wazuh 4.3 - SCA policies manual tests - SCA Ubuntu 22.04 policy

### ISSUE THREAD

**Issue by DanLarios07** [wazuh/wazuh#13968]
### References: 

- SCA policy: https://raw.githubusercontent.com/wazuh/wazuh/7c82ac74b35a43a70749e948b90a6d50c1b7f474/ruleset/sca/ubuntu/cis_ubuntu22-04.yml
- CIS Benchmark: https://downloads.cisecurity.org/download?u=1655899645
- Ubuntu VM: https://releases.ubuntu.com/22.04/

### Resutls:
![cis](https://user-images.githubusercontent.com/31428149/175344433-ed9d107b-3906-43fc-b981-1210dcab49af.png)

- Checks output: 
[cis_ubuntu22-04.csv](https://github.com/wazuh/wazuh/files/8968925/cis_ubuntu22-04.csv)

- Scan duration: `6 seconds` 

### Verification:

|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28500 | Failed |![28500](https://user-images.githubusercontent.com/31428149/175365589-e2f8b7fa-8032-4453-9d6d-1e249e2bd910.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28501 | Failed |![28501](https://user-images.githubusercontent.com/31428149/175365671-b254d217-ca3a-4aba-bf78-d3f16523931c.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28502 | Failed |![28502](https://user-images.githubusercontent.com/31428149/175377884-59863ad6-f7dd-4310-866d-8b8c733ac774.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28503 | Failed |![28503](https://user-images.githubusercontent.com/31428149/175377904-af44c4ca-23fb-4014-abbe-3c4c277040e2.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28504 | Failed |![28504](https://user-images.githubusercontent.com/31428149/175377936-59e0b4d3-05a2-4c2c-a832-3fd2c854984c.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28505 | Failed |![28505](https://user-images.githubusercontent.com/31428149/175378528-80a9b140-72f4-4886-aaba-6640d1cf53f9.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28506 | Failed |![28506](https://user-images.githubusercontent.com/31428149/175378578-8d5f0299-7a2e-4a01-aa80-e9da6a62e48a.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28507 | Failed |![28507](https://user-images.githubusercontent.com/31428149/175378610-9926f591-2766-4b57-bdcb-ee58b0e48363.png)| :heavy_multiplication_x:  | :heavy_check_mark:  |The last step of the remediation is incorrect.|
| 28508 | Failed |![28508](https://user-images.githubusercontent.com/31428149/175378625-7daecb25-8f6c-4ef5-96d2-3439fb739ff6.png)| :heavy_multiplication_x:  | :heavy_check_mark:  |Misspelled setuid on the rationale and description.|
| 28509 | Failed |![28509](https://user-images.githubusercontent.com/31428149/175378663-e0d23d24-ee12-4b56-a141-cfe4ef105fec.png)| :heavy_multiplication_x:   | :heavy_check_mark:  |Not the right rationale.|
| 28510 | Failed |![28510](https://user-images.githubusercontent.com/31428149/175378692-9dbd0f39-273e-4a5e-ad08-eca085b74da0.png)| :heavy_multiplication_x:  | :heavy_multiplication_x:  |Not the expected output. Missing space at Description "tmpfsat"|
| 28511 | Passed |![28511](https://user-images.githubusercontent.com/31428149/175378713-2634486b-aeaf-491e-8796-4de15244f657.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28512 | Passed |![28512](https://user-images.githubusercontent.com/31428149/175378744-0a42f75f-8eb3-4cdd-9770-f953fd2a223b.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28513 | Failed |![28513](https://user-images.githubusercontent.com/31428149/175378778-695d10fc-0f23-41f4-bf30-18fc0187bef3.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28514 | Failed |![28514](https://user-images.githubusercontent.com/31428149/175378805-5854ac86-5582-4e50-b5d4-015153adb649.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28515 | Failed |![28515](https://user-images.githubusercontent.com/31428149/175378832-fdd3953b-1fdc-428d-90b0-a5972eb27888.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28516 | Failed |![28516](https://user-images.githubusercontent.com/31428149/175378853-ee3d577c-f43f-40de-974d-c4fdf759b5df.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28517 | Failed |![28517](https://user-images.githubusercontent.com/31428149/175378879-db6d59ca-71f0-472d-b06e-b66e2a0eac9e.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28518 | Failed |![28518](https://user-images.githubusercontent.com/31428149/175378905-3280dbf1-f878-4292-aef9-ba2e099774a6.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28519 | Failed |![28519](https://user-images.githubusercontent.com/31428149/175378978-370e8a4d-efb6-4140-9cd9-2d889cc12480.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28520 | Failed |![28520](https://user-images.githubusercontent.com/31428149/175379038-3a3eb6c0-6946-4a08-a415-eb73f67732a2.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|
| 28521 | Failed |![28521](https://user-images.githubusercontent.com/31428149/175379075-b2608ac0-a993-488d-80ed-0a775f28b113.png)| :heavy_check_mark:  | :heavy_check_mark:  |-|

**Comment by 72nomada** [comment]
Checks review 

|Check ID| Description |Outcome|Observations|
|---|---|---|---|---|
|28507|Modified|--| Remediation field|
|28508|Modified|--| 'set userid' to 'setuid'| 
|28509|Not changed|--| Can't find the problem, rationale seems to be correct££|
|28510|Modified|--| 'tmpfsat' to 'tmpfs at'.|
|||Modified| changed rule to       - 'c:findmnt -n /dev/shm-> r:^/dev/shm\s'|

**Comment by DanLarios07** [comment]
### Verification: Day 2 


|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28522 | Failed |![28522](https://user-images.githubusercontent.com/31428149/175566169-f5c25582-d6bc-49ff-9c35-cc81f2096700.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28523 | Passed |![28523](https://user-images.githubusercontent.com/31428149/175566310-1ebbd6ec-bd7c-4214-9087-c12fed1c68c4.png)| :heavy_check_mark: | :heavy_check_mark:  |-|
| 28524 | Failed |![28524](https://user-images.githubusercontent.com/31428149/175566476-3fbdc2e3-3df2-4ada-8204-6c628d1b4b89.png)| :heavy_check_mark: | :heavy_check_mark:  |-|
| 28525 | Passed |![28525](https://user-images.githubusercontent.com/31428149/175566520-012091bb-57c5-425f-8cc9-19453bbfb4f9.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28526 | Passed |![28526](https://user-images.githubusercontent.com/31428149/175566665-e85c4b46-f8a8-4aa7-b232-5aaa4fb50ecb.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28527 | Failed |![28527](https://user-images.githubusercontent.com/31428149/175566771-24537c36-e48f-48d8-be05-a5648a06c957.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28528 | Failed |![28528](https://user-images.githubusercontent.com/31428149/175566799-133cbc88-c088-4f0a-9b84-1c5ee56ea793.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28529 | Failed |![28529](https://user-images.githubusercontent.com/31428149/175566873-0d53097b-eab6-45d6-9a5e-a8bfc936b1fb.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28530 | Failed |![28530](https://user-images.githubusercontent.com/31428149/175566928-e08b0eff-a790-46ed-9b46-0f0618a6332c.png)|:heavy_check_mark:| :heavy_check_mark:  |-|

**Comment by DanLarios07** [comment]
### Verification: Day 3 


|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28562 | Passed |![28562](https://user-images.githubusercontent.com/31428149/175968991-41da85fa-267b-49ca-8f3a-2ca95edfcc1f.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28563 | Passed |![28563](https://user-images.githubusercontent.com/31428149/175969017-729a9ebe-e332-4d09-8bdf-344a4ff8fb28.png)| :heavy_check_mark: | :heavy_check_mark:  |-|

**Comment by DanLarios07** [comment]
### Verification: Day 4


|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28562 | Passed |![28562](https://user-images.githubusercontent.com/31428149/175968991-41da85fa-267b-49ca-8f3a-2ca95edfcc1f.png)|:heavy_check_mark:| :heavy_check_mark:  |-|
| 28563 | Passed |![28563](https://user-images.githubusercontent.com/31428149/175969017-729a9ebe-e332-4d09-8bdf-344a4ff8fb28.png)| :heavy_check_mark: | :heavy_check_mark:  |-|

**Comment by DanLarios07** [comment]
### Verification: Day 5


|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28631 | Failed |![28599](https://user-images.githubusercontent.com/31428149/176212747-d19afe56-f8de-464a-9837-92257e2505ee.png)| :heavy_multiplication_x: | :heavy_check_mark:  | Not the correct title, it should be `Ensure a nftables base chains exists` instead of `Ensure base chains exists` |
| 28632 | Failed |![28600](https://user-images.githubusercontent.com/31428149/176214573-4e0e4933-1810-49ec-8e97-25bcdb13a495.png)| :heavy_multiplication_x: | :heavy_check_mark:  | Not the correct title, it should be `Ensure a nftables loopback traffic is configured` instead of `Ensure loopback traffic is configured` |

**Comment by DanLarios07** [comment]
### Corrections:

|Check ID|Check result|Check output|Matching description|Valid outcome|Observations|
|---|---|---|---|---|---|
| 28509 | Failed |![28509](https://user-images.githubusercontent.com/31428149/175378663-e0d23d24-ee12-4b56-a141-cfe4ef105fec.png)| :heavy_multiplication_x:   | :heavy_check_mark:  |Not the right rationale.|
