### ISSUE TITLE
Test Logcollector

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1398]
# Logcollector test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |
| 3.7.0 | 3719 | 3.7 |

## Configuration

- [x] Add log (syslog and JSON).
- [x] Delete all localfile entries and start Logcollector.
- [x] Test Logcollector internal options.
- [x] Increase both `logcollector.max_files` and `logcollector.rlimit_nofile` and check if everything works with the maximum number of files allowed.

## Logs

- [x] Solve the reading of a file when changing its inode.
- [x] Check that Eventlog logs are read in all supported versions of Windows.
- [x] Truncate file.
- [x] Check for new paths that match a wildcards after starting Logcollector.
- [x] Check **all the tests** changing the order of the parameters in combination with normal and daily wildcards.
- [x] Check that labels are added to JSON files.
- [x] Check that the multi-line logs are taken.
- [x] Check that no duplicate files are scanned (entered multiple times).

## Performance

- [x] Monitor the memory wasted by Logcollector in the previous operations.

## Sockets

- [x] Configure one and multiple sockets output as target. (https://github.com/wazuh/wazuh/pull/395)
- [x] Test the `out_format` option for different socket targets. (https://github.com/wazuh/wazuh/pull/863)

## Commands

- [x] Prevent remote commands, with `command` or `full_command`, if `logcollector.remote_commands` is enabled.
- [x] Check that the output of a command is captured line by line (with `command`) and completely (with `full_command`)
- [x] Check the correct output of *netstat* commands.

**Comment by albertomn86** [comment]
This warning message is repeated in the `ossec.log` file:

```
2018/09/24 17:54:40 ossec-logcollector: WARNING: (1960): File limit has been reached (8). Please reduce the number of files or increase "logcollector.max_files".
2018/09/24 17:54:40 ossec-logcollector: WARNING: (1960): File limit has been reached (8). Please reduce the number of files or increase "logcollector.max_files".
2018/09/24 17:54:40 ossec-logcollector: WARNING: (1960): File limit has been reached (8). Please reduce the number of files or increase "logcollector.max_files".
```

**Comment by Cerv1** [comment]
Found #1589.
Fixed by @albertomn86 in #1594

**Comment by Cerv1** [comment]
Found #1600

**Comment by crolopez** [comment]
https://github.com/wazuh/wazuh/issues/1841
https://github.com/wazuh/wazuh/issues/1842
