### ISSUE TITLE
Test Command

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1400]
# Command test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3700 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

## Linux

- [ ] Run a command in Linux.
- [ ] Check all options (`interval`, `ignore_output`, ...)
- [ ] Run a command that not finish (set a timeout of 0 letting the process to run indefinitely)
- [ ] Run a command that not finish.
Set a timeout other than 0 killing the process when it is reached.
- [ ] Try to run an alias (e.g. `openssl` instead of */usr/bin/openssl*).
- [ ] Verify checksums of the defined command.
- [ ] Check interval runs as expected more than the very first time.
- [ ] Try to run wodle command with `remote_commands=0`.

## Windows

- [ ] Run a command in Windows.
- [ ] Check all options (`interval`, `ignore_output`, ...)
- [ ] Run a command that not finish (set a timeout of 0 letting the process to run indefinitely).
- [ ] Run a command that not finish (set a timeout other than 0 killing the process when it is reached).
- [ ] Try to run an alias (e.g. `ipconfig`).
- [ ] Verify checksums of the defined command.
- [ ] Check interval runs as expected more than the very first time.
- [ ] Try to run wodle command with `remote_commands=0`.

**Comment by cristgl** [comment]
https://github.com/wazuh/wazuh/issues/1603 -> Solved at https://github.com/wazuh/wazuh/pull/1604
