### ISSUE TITLE
Verifying remote configuration blocks as a single configuration produces errors

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1402]
The following configuration for two servers is loaded as a single block, which leads to the false error that the directory is duplicated in Syscheck. Also, in another module it can produce a more serious failure.

```
<agent_config name="server1">
   <syscheck>
		<directories check_all="yes" whodata="yes">/var/www</directories>
   </syscheck>
</agent_config>

<agent_config name="server2">
   <syscheck>
		<directories check_all="yes" whodata="yes">/var/www</directories>
   </syscheck>
</agent_config>
```

Output of verify-agent-conf tool.

```
verify-agent-conf: Verifying [/var/ossec/etc/shared/default/agent.conf]
2018/09/24 11:42:54 verify-agent-conf: ERROR: (1756): Duplicated directory given: '/var/www'.
verify-agent-conf: OK

```

**Comment by bah07** [comment]
For version 3.7 the configuration pushed from the manager overwrites the local configuration directories if the path is the same.

Done in #1740
