### ISSUE TITLE
Test: Agent management

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1404]
# Agent management test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3719 | 3.7 |

## *agent.conf*

- [x] Check if the "verify-agent-conf" tool verifies the agent.conf including all the modules. (1)
- [x] Set a configuration for a non-existent agent, OS, or profile. Try to send it to agents. (1)
- [x] Send by the agent.conf an unrecognizable module for the agent.
- [x] Agents (Linux/Windows) receive the agent.conf, applying the configuration and restarting the agent automatically. (1)
- [x] Agents ignore agent.conf when it is specified in the internal options. (1)

(1) https://documentation.wazuh.com/3.x/user-manual/reference/centralized-configuration.html

## Labels

- [x] Set nested labels for an agent in the "agent.conf". (2)
- [x] Show hidden labels with the internal option of analysisd. (2)
- [x] Use labels in the "localfile" section for a monitored log file in JSON. (3) 

(2) https://documentation.wazuh.com/3.x/user-manual/capabilities/labels.html
(3) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/localfile.html#label

## Groups

- [ ] Create a group, add agents and send them a centralized configuration. (4)
- [ ] Check if an agent is reassigned to its group after registering it with another name or ID. (4)
- [ ] Remove a group, remove agents from a group, and check that they are assigned to the default group. (5)
- [ ] Test multi-groups (Issue: https://github.com/wazuh/wazuh/issues/1238)

(4) https://documentation.wazuh.com/3.x/user-manual/agents/grouping-agents.html
(5) https://documentation.wazuh.com/3.x/user-manual/reference/tools/agent_groups.html#examples

## Leaky bucket

- [x] Change the buffer parameters (eps and queue size) to trigger alerts of flooding. (6)
- [x] Change the threshold levels of the buffer and check that alerts are triggered when they have to. (6)
- [x] Set a less minimum of eps than it is specified in the parameter "agent.min_eps". (7)
- [x] Test the agent modules anti-flooding. You can write in a monitored log by logcollector with an infinite loop to do this. (8)

(6) https://documentation.wazuh.com/3.x/user-manual/capabilities/antiflooding.html#how-it-works-leaky-bucket
(7) https://documentation.wazuh.com/3.x/user-manual/reference/internal-options.html#agent
(8) https://documentation.wazuh.com/3.x/user-manual/capabilities/antiflooding.html#anti-flooding-in-agent-modules

## *agent_control*

- [x] Check that "agent_control" shows agent status in real-time (after 30 minutes). (9)
- [x] Check that the information provided by the API about agents is consistent with the "agent_control" tool. (10)

(9) https://documentation.wazuh.com/3.x/user-manual/reference/tools/agent_control.html
(10) https://documentation.wazuh.com/3.x/user-manual/api/reference.html#get-all-agents

**Comment by Skeptor** [comment]
https://github.com/wazuh/wazuh/issues/1446

**Comment by cristgl** [comment]
When deleting an agent with `manage_agents` appears an ERROR at `ossec.log`:

```
2018/10/11 10:25:48 ossec-authd: INFO: Agent '005' (beta) deleted (requested locally)
2018/10/11 10:25:48 ossec-analysisd: ERROR: Getting stats for agent beta (any). Getting old data.
2018/10/11 10:25:48 wazuh-modulesd:database: ERROR: Couldn't get database status for agent '5'.
```
This message should not appear as the deletion of the agent was intentioned.
