### ISSUE TITLE
Segmentation fault in wazuh-remoted

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#14057]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.7 | wazuh-modulesd | Manager | SaaS | CentOS 7 |

There is a bug in Wazuh 4.2.7. The segmentation fault happens in a manager running in a GCP VM.
This occurs in centOS7 with kernel 3.10.0-1160.66.1

We only have the following message:
`cat /var/log/messages | grep segfault`
```
Jun 12 12:23:47 gcp-manager kernel: wazuh-remoted(15188): segfault at 0 ip 00007fd4137f259c sp 00007fd40b5064e0 error 4 in libc-2.17.so[7fd41377b000+1c4000]
```

Right now the data is insufficient to reproduce the problem.
The next steps would be:
- Obtain the configuration of the failed manager.
- Obtain all Wazuh logs around the time of `seg_fault`
- Enable core dump in the failed environment.

**Comment by vikman90** [comment]
|Address|Binary|Offset|Function|
|---|---|---|---|
|`NULL`|libc-2.17.so|0x7759c|`fseek()`|

The most common call from Remoted to `fseek()` is at `MergeAppendFile()`, but this function checks that `fp` is not null before calling `fseek()`. So, either the call to `fseek()` is via another function, or any race condition (like these described at #12731) is smashing the stack.

**Comment by vikman90** [comment]
@wazuh/watchdogs have checked the wazuh-remoted code and could not find any call to `fseek()` that might pass it a null pointer.

Thus, we block this issue until we get a clone of the VM where this happened.

**Comment by vikman90** [comment]
We stop investigating this issue due to the lack of data.

**Comment by vikman90** [comment]
We have been reported another crash in the same version, although the instruction pointer is different:

|Version|Platform|IP|Function|Line of code|
|---|---|---|---|---|
|4.2.7|CentOS 7|0x485660|`checkBinaryFile()`|[file_op.c:967](https://github.com/wazuh/wazuh/blob/v4.2.7/src/shared/file_op.c#L967)|

## Context (assembly)

```sh
yum install -y wazuh-manager-4.2.7-1
objdump -Dgl /var/ossec/bin/wazuh-remoted | grep -B36 485660:
```

```
00000000004855e0 <checkBinaryFile>:
checkBinaryFile():
  4855e0:       41 54                   push   %r12
  4855e2:       48 8d 35 05 32 06 00    lea    0x63205(%rip),%rsi        # 4e87ee <__func__.31705+0x22c>
  4855e9:       55                      push   %rbp
  4855ea:       48 89 fd                mov    %rdi,%rbp
  4855ed:       53                      push   %rbx
  4855ee:       48 81 ec 30 00 01 00    sub    $0x10030,%rsp
  4855f5:       c6 84 24 10 00 01 00    movb   $0x0,0x10010(%rsp)
  4855fc:       00
  4855fd:       e8 d6 13 f8 ff          callq  4069d8 <fopen@plt>
  485602:       48 85 c0                test   %rax,%rax
  485605:       48 89 c3                mov    %rax,%rbx
  485608:       0f 84 f8 00 00 00       je     485706 <checkBinaryFile+0x126>
  48560e:       48 8d b4 24 20 00 01    lea    0x10020(%rsp),%rsi
  485615:       00
  485616:       48 89 c7                mov    %rax,%rdi
  485619:       4c 8d 64 24 10          lea    0x10(%rsp),%r12
  48561e:       e8 d5 24 f8 ff          callq  407af8 <fgetpos@plt>
  485623:       48 89 df                mov    %rbx,%rdi
  485626:       e8 35 dc ff ff          callq  483260 <w_ftell>
  48562b:       48 89 c5                mov    %rax,%rbp
  48562e:       eb 03                   jmp    485633 <checkBinaryFile+0x53>
  485630:       48 01 c5                add    %rax,%rbp
  485633:       48 89 da                mov    %rbx,%rdx
  485636:       be 01 00 01 00          mov    $0x10001,%esi
  48563b:       4c 89 e7                mov    %r12,%rdi
  48563e:       e8 95 15 f8 ff          callq  406bd8 <fgets@plt>
  485643:       48 85 c0                test   %rax,%rax
  485646:       0f 84 a4 00 00 00       je     4856f0 <checkBinaryFile+0x110>
  48564c:       48 89 df                mov    %rbx,%rdi
  48564f:       e8 0c dc ff ff          callq  483260 <w_ftell>                 # ... w_ftell(fp)
  485654:       48 29 e8                sub    %rbp,%rax                        # rbytes = w_ftell(fp) - offset;
  485657:       48 85 c0                test   %rax,%rax                        # if (rbytes <= 0) {
  48565a:       7e 73                   jle    4856cf <checkBinaryFile+0xef>
  48565c:       4c 8d 48 ff             lea    -0x1(%rax),%r9                   # ... str[rbytes - 1]
  485660:       42 80 7c 0c 10 0a       cmpb   $0xa,0x10(%rsp,%r9,1)            # if (str[rbytes - 1] == '\n') {
```

**Comment by vikman90** [comment]
This issue may be related to:
- #14018
- #14190
