### ISSUE TITLE
Test: Active response

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1406]
# Testing: Active response

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

## Active response

- [x] Insert 2 times same config
- [x] Test active-response from wrong SO
- [x] Test active-response from correct SO
- [x] Check that the execution of the active response respects the location
- [x] Specifies more than one agent_id. **Must fail**
- [x] Check level filter
- [x] Check rules_group filter
- [x] Check rules_id filter
- [x] Check the period of the reverse command (timeout option)
- [ ] Check incremental timeouts (repeated_offenders)

## Command

- [x] Insert 2 times same config
- [x] Configure a command that does not exist
- [x] Same command for multiple active-response
- [ ] Check that the extra_args option works for any field
- [ ] Check that the expect option works for any field
- [x] Verify that the return command can be enabled and disabled (timeout_allowed)
- [x] Set the command below the active response that uses it. **Must fail**
- [x] Test firewall-drop command

## agent_control

- [ ] Send an active-response to an agent using agent_control

## Custom A-R

- [ ] Test custom active-response explained at https://github.com/wazuh/wazuh/issues/1116

**Comment by cristgl** [comment]
Can't run a custom command that writes text to a file on an agent, the script is found but it is not being executed. To send the AR to the agent:

```
# curl -u foo:bar -X PUT -d '{"command":"test.sh", "custom": "True", "arguments": ["ls", "-l"]}' -H 'Content-Type:application/json' "http://localhost:55000/active-response/001?pretty"
{
   "error": 0,
   "data": "Command sent: '(msg_to_agent) [] NNS 001 !test.sh ls -l'."
}
```

The ``ar.conf`` contains:

```
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
test0 - test.sh - 0
```

**Comment by cristgl** [comment]
Repeated offenders is not working, after executing the command established by the AR after the timeout, the next executions are run inmediately, not taking into account the ``repeated_offenders`` field.

The ``ossec.conf`` of the manager contains:
```
<active-response>
  <disabled>no</disabled>
  <command>host-deny</command>
  <location>defined-agent</location>
  <agent_id>001</agent_id>
  <level>3</level>
  <timeout>1</timeout>
</active-response>
```

And the agent's:
```
<active-response>
  <disabled>no</disabled>
  <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
  <ca_verification>yes</ca_verification>
  <repeated_offenders>30,5,10</repeated_offenders>
</active-response>
```
