### ISSUE TITLE
Int overflows in analysisd for JSON messages

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#14064]
|Wazuh version|Component|Install type|Install method|Platform|Reference|
|---|---|---|---|---|---|
| 4.3.4-40316 | Analysisd | Manager | Packages | any |[Google groups message](https://groups.google.com/g/wazuh/c/WWrODnKHcfM)|

Whenever an event processed by the implicit JSON decoder contains an integer with a value above `(2^31)-1` (2,147,483,648) then the object is turned from an int to a number with decimals.

```
# echo '2^31-1' | bc | xargs -I % echo '{"value":%}' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.4
Type one log per line


**Phase 1: Completed pre-decoding.
	full event: '{"value":2147483647}'

**Phase 2: Completed decoding.
	name: 'json'
	value: '2147483647'
```

```
echo '2^31' | bc | xargs -I % echo '{"value":%}' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.4
Type one log per line


**Phase 1: Completed pre-decoding.
	full event: '{"value":2147483648}'

**Phase 2: Completed decoding.
	name: 'json'
	value: '2147483648.000000'
```
Which may lead to events being rejected from being indexed for not matching the type expected by the template.

Furthermore if the value is above `2^53` the decoded value will not always be consistent:
```
echo '2^53+1' | bc | xargs -I % echo '{"value":%}' | /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.4
Type one log per line


**Phase 1: Completed pre-decoding.
	full event: '{"value":9007199254740993}'

**Phase 2: Completed decoding.
	name: 'json'
	value: '9007199254740992.000000'

```
in this case the error is off by one, but the higher values will provide similar discrepancies. 

This is observed not only on `wazuh-logtest` but on real events parsed by analysisd:
```
{
  "timestamp": "2022-06-28T11:03:35.829+0000",
  "rule": {
    "level": 3,
    "description": "Rule for testing",
    "id": "100002",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "test"
    ]
  },
  "agent": {
    "id": "000",
    "name": "managerB0"
  },
  "manager": {
    "name": "managerB0"
  },
  "id": "1656414215.2485232",
  "cluster": {
    "name": "wazuh",
    "node": "master"
  },
  "full_log": "{\"ruletest\":18446744073709551617}",
  "decoder": {
    "name": "json"
  },
  "data": {
    "ruletest": "18446744073709551616.000000"
  },
  "location": "/var/log/messages"
}
```

**Comment by ShehanAT** [comment]
> I see this was also reported in #13425 and although the root cause is found, the bug is not yet fixed, which may still unexpectedly tamper with an event's integrity.

Could you reveal where in the source code the root cause is? I can try looking into this issue.

**Comment by havidarou** [comment]
May be related to https://github.com/wazuh/wazuh/issues/14664
