### ISSUE TITLE
The API does not correctly read the `q` parameter

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh#14080]
|Wazuh version|Component|
|---|---|
| 4.3.5 | Wazuh API |

## Description

A user has reported a problem with the FIM module, reading the file `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\` caused by a syntax error on the SQL query used by Wazuh. The DEBUG logs are:

```log
022/06/29 08:01:55 wazuh-db[1000141] main.c:286 at run_dealer(): DEBUG: New client connected (36).
2022/06/29 08:01:55 wazuh-db[1000141] wdb_parser.c:240 at wdb_parse(): DEBUG: Agent 004 query: sql select count(*) from (select perm as 'perm',sha1 as 'sha1',gid as 'gid',type as 'type',value_type as 'value.type',date as 'date',mtime as 'mtime',value_name as 'value.name',uname as 'uname',md5 as 'md5',gname as 'gname',inode as 'inode',file as 'file',changes as 'changes',size as 'size',sha256 as 'sha256',attributes as 'attributes',uid as 'uid',arch as 'arch' from fim_entry where (file = 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\' collate nocase)  ((type = 'file' collate nocase) or (type = 'registry_key' collate nocase))  )
2022/06/29 08:01:55 wazuh-db[1000141] wdb.c:1149 at wdb_exec(): DEBUG: sqlite3_prepare_v2(): near "(": syntax error
```

The SQL query misses `AND` or `OR` operators between 
```sql
(file = 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters\Interfaces\' collate nocase)
```
and 
```sql
((type = 'file' collate nocase)
```

The regular expression used by the Wazuh API to read the `q` parameter does not read the parameter completely, or correctly, failing to add the logical operators on the required locations at the query mentioned above.

This error could be reproduced, and the request raising the error is:

```json
{
  "method": "GET",
  "path": "/syscheck/004",
  "body": {
    "params": {
      "q": "file=HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\\{4473f692-67de-480d-a481-6de3e4a2813b};(type=file,type=registry_key)"
    }
  },
  "id": "env-1"
}
```

@vicferpoy researched this issue and reported that the `;(type=file,type=registry_key)` is not read correctly.

Here I attach a GIF in order to show how to replicate the error:

![image](https://user-images.githubusercontent.com/15186973/176469070-4cb67b5f-6ec9-4ece-864f-826307cec207.png)

**Comment by vicferpoy** [comment]
As it was reported, the query is not read correctly. In particular, the last characters from the first value are not read and thus, the `AND` operator is not added. This is due to a lack of special characters in our query regex: 

https://github.com/wazuh/wazuh/blob/2a2b88bfb2ea30903728372471b33540a3b3d976/framework/wazuh/core/utils.py#L1236-L1243
