### ISSUE TITLE
ARM Install wazuh

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh#14086]
Dear: ALL 
i am looking for a way to install wazuh on an ARM server. if anyone has a guide please let me know.

**Comment by vncloudsco** [comment]
Dear: @jftuduri 

I want install Wazuh server on ARM, I can't install them on our server

**Comment by jftuduri** [comment]
Hello @vncloudsco

To be able to help you I am going to need a couple of things. 

Can you tell me what installation method you chose?
What error messages have you found?
Do you need to install just the wazuh server or do you also need the indexer and dashboard on ARM? 

The server works on ARM, but we are having some issues with the indexer and dashboard, these are not ready yet. We are working on them on https://github.com/wazuh/wazuh-packages/issues/1637.

I will be waiting for your answer.

**Comment by jftuduri** [comment]
Closed due to inactivity.

**Comment by ChrisMoCa** [comment]
Hello, I wanted to install Wazuh on a ARM Ampere server (Oracle cloud) but I was unable to perform this action.
I ran the following command `curl -sO https://packages.wazuh.com/4.4/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -i` and I get the following output: `ERROR: Uncompatible system. This script must be run on a 64-bit system.`
