### ISSUE TITLE
`wazuh-analysisd` did not start correctly - Error reading XML file

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#14092]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5-1 | wazuh-analysisd | Manager | Packages | Debian 11 |

Installing a Debian 4.3.5 manager package via `dpkg -i`, I have observed the following error when performing `wazuh-control start`:

```
wazuh-analysisd did not start correctly.
```

The ossec.conf file shows:

```
2022/06/30 16:05:26 wazuh-analysisd: ERROR: (1226): Error reading XML file 'ruleset/rules/0030-postfix_rules.xml': XMLERR: Element 'name' not closed. (line 267>
2022/06/30 16:05:26 wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'ruleset/rules/0030-postfix_rules.xml'.
```

Related v4.3.5 and custom branch XML files:

- https://github.com/wazuh/wazuh/blob/v4.3.5/ruleset/rules/0030-postfix_rules.xml
- https://github.com/wazuh/wazuh/blob/msi-remote-commands/ruleset/rules/0030-postfix_rules.xml (package was built using this branch)

When validating the XML file in an online validator, a possible error has been observed:

- https://www.xmlvalidation.com/index.php

![image](https://user-images.githubusercontent.com/14913942/176731235-51ae768f-b502-4337-86d5-ef5857ff12a4.png)

it was not possible to reproduce it, I booted the machine, installed the package with `dpkg -i` and ran `wazuh-control start`.

Regards, Raúl.

**Comment by 72nomada** [comment]
About the XML file itself. There is no extra or hidden char. 

That file has two different XML documents, 

```
<var ...>... </var>
<group ... >...</group>
```

External XML validators may fail due they are expecting a single XML document. removing <var> element, the XML validator parsers as expected. 

Analysisd should not fail to read that file. That XML file has been configured that way for 16 years, and our analysis did not change the parsing XML.

**Comment by vikman90** [comment]
This issue is weird for these reasons:

1. It seems not to be deterministic.
2. The service start process failed on process booting instead of configuration check. If the file was not OK, we should expect this message:
```
wazuh-analysisd: Configuration error. Exiting
```
3. The error description suggests that there is an element `<name>`, which does not exist. Element `<group>` contains attribute `name`, but if the problem were around there, Analysisd would print this log:
```
ERROR: (1226): Error reading XML file 'ruleset/rules/0030-postfix_rules.xml': XMLERR: End of file while reading an attribute. (line 12).
```
