### ISSUE TITLE
[Feature Request]Supports Concurrency for Vulnerability Detector 

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh#14095]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Vulnerability Detector | Manager | Sources | CentOS7.9 |

I installed wazuh-manger on a powerful server (32C/256G) which managed 3000+ agents.
Because vulnerability scans do not support concurrency,  scanning a round need alomost a week.

**Comment by Dwordcito** [comment]
Hi @LubinLew , we are going to completely refactor vulnerability detector, thanks for the suggestion!! soon it will be better!

**Comment by Dwordcito** [comment]
Issue where we'll attack this: Content is the trigger.

https://github.com/wazuh/wazuh/issues/13760
