### ISSUE TITLE
Allow negation in rules

### ISSUE THREAD

**Issue by theflakes** [wazuh/wazuh#141]
Add the ability for "NOT" logic in rules.  Can get around this using two rules and "if_sid" on the second rule.  But would be more readable to allow negations checks.  If there already is one please correct me cause I cannot find it.  thanks

**Comment by jesuslinares** [comment]
Please, could you give us a real example?.

Thanks.

**Comment by theflakes** [comment]
When alerting on processes I want to check and ensure that a process is only running from a specific directory.  Right now I have to first look for the process name in the log and raise the alert to level 13 lets say.  Then I have to write a child rule for that rule that checks for the directory that process is running out of and if it matches lower the alert to level 2 or whatever.  If I do not do this then the rule will alert on other processes.

With negation I could first check for the process name and then have another regex in the same rule to check that the correct parent directory is NOT found.  

Am I over complicating this?

Haven't thought about this one too much, but I think it may help with writing easily adding logic to decrease false positives with other rules.

**Comment by jesuslinares** [comment]
I see your point. You are doing it right. We will add this feature to our roadmap. 

OS_Regex (<regex>) doesn't allow negation, but OS_Match (<match>) allows negation using "!" at the beginning. Try to use it if possible:

**Decoders**
```
<decoder name="test">
    <prematch>test: </prematch>
</decoder>

<decoder name="test">
    <parent>test</parent>
    <regex offset="after_parent">e: "(\S+)", p: "(\S+)"</regex>
    <order>process, parent</order>
</decoder>
```

**Rules**
```
<group name="test,">

  <!--
  test: test: e: "b.exe", p: "/main".
  -->
  <rule id="100001" level="0">
    <decoded_as>test</decoded_as>
    <description>Test: $(process)</description>
  </rule>

  <!--
  test: e: "a.exe", p: "/main".
  test: e: "a.exe", p: "/other".
  -->
  <rule id="100002" level="0">
    <if_sid>100001</if_sid>
    <field name="process">a.exe</field>
    <match>!p: "/main".</match>
    <description>Process $(process): bad parent.</description>
  </rule>

</group>
```

**Test 1**: Process with proper parent (/main)
```
test: e: "a.exe", p: "/main".

**Phase 2: Completed decoding.
       decoder: 'test'
       process: 'a.exe'
       parent: '/main'

**Phase 3: Completed filtering (rules).
       Rule id: '100001'
       Level: '0'
       Description: 'Test: a.exe'
```

**Test 2**: Process with wrong parent (/other)
```
test: e: "a.exe", p: "/other".

**Phase 2: Completed decoding.
       decoder: 'test'
       process: 'a.exe'
       parent: '/other'

**Phase 3: Completed filtering (rules).
       Rule id: '100002'
       Level: '0'
       Description: 'Process a.exe: bad parent.'
```

Regards.

**Comment by vikman90** [comment]
## Objective

Add a new option to the regex-based options in rules that shall negate the match. This is, the condition will match if the event does not meet the regular expression.

The new option consists of a new attribute `negate` in the options, like:

```xml
<rule>
  <regex negate="yes">^Hello world$</regex>
</rule>
```

## Requirements

1. To be able to negate the whole expressions for dynamic and static fields, including `<regex>` and `<match>` (listed below).
2. For negation, we will use the attribute `negate` that shall accept `yes` and `no` as valid values.
3. _ossec-dbd_ is about to be deprecated so we won't extend this daemon.
4. Write the JSON output when requesting `/rule` using the API.
5. As `<regex>` and `<match>` are currently appended, the attribute `negate` will apply to the whole expression. If it appears multiple times, the latest will apply, being the default value `no`.
6. As the regex `.*` matches everything, including an empty string, then `<regex negate="yes">/*</regex>` will never meet.
7. A negated `<field>` lookup means that the field must exist, and the regex must not match.

### Affected options

- `<action>`
- `<dstip>`
- `<extra_data>`
- `<field>`
- `<hostname>`
- `<id>`
- `<location>`
- `<match>`
- `<program_name>`
- `<protocol>`
- `<regex>`
- `<srcip>`
- `<user>`
- `<url>`

## Examples

### Example 1

```xml
<regex negate="yes">A|</regex>
<regex>B|</regex>
<regex>C</regex>
```

That means:
```
¬(A|B|C)
```

### Example 2

```
<regex negate="yes">A|</regex>
<regex>B|</regex>
<regex negate="no">C</regex>
```

That means:
```
A|B|C
```

### Example 3
```
<field name="A" negate="yes">^Hello</field>
```

That means:
- The event contains a field with name "A", and,
- Its value starts with anything but "Hello".

### Example 4 
```xml
<field name="B" negate="yes">.*</field>
```

This will never meet, so the system will not produce an alert with this rule.

**Comment by theflakes** [comment]
The is awesome, thanks all.

This will definitely simplify some rule writing and future rule maintenance.
