### ISSUE TITLE
Test: AWS

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1410]
# Amazon Web Services test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

## RPM (Linux)

- [ ] Configure *ossec.conf* to use cloud-trail wodle and check manager logs.
- [ ] Check wodle related alerts are being stored in *alerts.json*.
- [ ] Configure AWS in Wazuh v3.5 and check it correctly upgrades to the latest version.
- [ ] Configure multiple buckets with multiple types (*custom* and *cloudtrail*).
- [ ] Wazuh app tab shows the alerts.

**Comment by cristgl** [comment]
Using the new configuration found at [AWS Documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html?highlight=aws):

```
<wodle name="aws-s3">
   <disabled>no</disabled>
   <remove_from_bucket>yes</remove_from_bucket>
   <interval>5m</interval>
   <run_on_start>yes</run_on_start>

   <bucket type="cloudtrail">
     <name>s3-dev-bucket</name>
     <access_key>access_key</access_key>
     <secret_key>secret_key</secret_key>
     <only_logs_after>2018-SEP-01</only_logs_after>
   </bucket>
</wodle>
```

The next warning related with permissions appears.
```
2018/09/27 12:41:41 wazuh-modulesd:aws-s3: INFO: Module AWS started
2018/09/27 12:41:41 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2018/09/27 12:41:41 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: s3-dev-bucket
2018/09/27 12:41:42 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 3
2018/09/27 12:41:42 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Bucket s3-dev-bucket access error: An error occurred (403) when calling the HeadBucket operation: Forbidden

2018/09/27 12:41:42 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
```

**Comment by cristgl** [comment]
Removing the 'default' group is not permitted, it shows this message:
```
# /var/ossec/bin/agent_groups -r -g default
Do you want to remove the 'default' group? [y/N]: y
Error 1712: Default group is not removable.
```

Even so, this group is removed from the database, this results in stopping the sharing of the 'default' configuration for every agent.

**Comment by manuasir** [comment]
## AWS testing for Wazuh v3.7.0

#### Configure ossec.conf to use cloud-trail wodle and check manager logs.

First, I tried to run the wodle without installing `boto3` dependency. I obtained the following log warning as expected:

```
2018/10/17 09:42:01 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: wazuh-cloudtrail
2018/10/17 09:42:02 wazuh-modulesd:aws-s3: WARNING: Bucket:(LEGACY)  -  Returned exit code 4
2018/10/17 09:42:02 wazuh-modulesd:aws-s3: WARNING: Bucket:(LEGACY)  -  boto3 module is required.
```


After installing and restarting the wazuh manager, I obtained this:

```
2018/10/17 09:43:56 wazuh-modulesd:aws-s3: INFO: Module AWS started
2018/10/17 09:43:56 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2018/10/17 09:43:56 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: wazuh-cloudtrail

```

#### Check wodle related alerts are being stored in alerts.json.

I executed a `tail -f` to `alerts.log` looking for any `aws` match, and I obtained several forwarded alerts:

```
.....
aws.requestParameters.instanceInitiatedShutdownBehavior: stop
aws.requestParameters.tenancy: default
aws.requestParameters.instancesSet.items.minCount: 2
aws.requestParameters.instancesSet.items.maxCount: 2
aws.requestParameters.instancesSet.items.keyName: testawscf
aws.requestParameters.instancesSet.items.imageId: ----08569b978c----
aws.requestParameters.disableApiTermination: false
aws.requestParameters.instanceType: i3.large
aws.requestParameters.ebsOptimized: true
aws.awsRegion: ap-southeast-1
aws.eventName: RunInstances
aws.source: cloudtrail
aws.userIdentity.userName: wazuh
aws.userIdentity.principalId: ----
aws.userIdentity.accessKeyId: ----
.....
```

#### Wazuh app tab shows the alerts

I checked it in Splunk app for Wazuh, navigated to Overview -> AWS Integration

![](https://i.imgur.com/zd5FBsl.png)

Visualizations were successfully showing alerts information.

#### Configure AWS in Wazuh v3.5 and check it correctly upgrades to the latest version.

First I configured a clean environment with `Wazuh v3.5.0` and setted up the cloudtrail wodle. Checked the logs:

```
2018/10/17 11:08:13 wazuh-modulesd:aws-cloudtrail: INFO: Module AWS-CloudTrail started

```

Then I upgraded wazuh to the latest version:

```
yum upgrade wazuh-manager -y
```

And checked the logs:

```
2018/10/17 11:12:15 wazuh-modulesd:aws-s3: INFO: Module AWS started
2018/10/17 11:12:15 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2018/10/17 11:12:15 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: wazuh-cloudtrail
```

So we can say the upgrading process was successful.
