### ISSUE TITLE
URLs for precompiled dependencies are wrong on Gentoo Linux

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#14109]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | Installation | Manager/Agent | Sources | Gentoo Linux |

## Description
Making the dependencies for agent v4.3.4 on Gentoo Linux the URLs built to download the packages are wrong:
![wrong_url_for_deps_download](https://user-images.githubusercontent.com/7939712/176966367-dfaa4664-8650-4d07-9d10-572a556447de.png)

### Additional Information

The value for uname -p matches the wrong path on the url:

`uname -p -> Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz`
`uname -m -> x86_64`
`uname -s -> Linux`

## QA Coverage

 - https://github.com/wazuh/wazuh-qa/issues/3086

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/14109?planning-poker) with ZenHub @jnasselle @jftuduri

**Comment by jftuduri** [comment]
Our Makefile is using the command `uname -p `to detect the cpu architecture and with this information builds the URLs to download the precompiled dependencies for the correct target. 
In this case the command `uname -p` returned `Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz`, when the expected value to build the URL correctly was `x86_64`. That is the output of `uname -m`.

We should use `uname -m` wherever possible to detect the archicture. The option -p of the command uname is "non-portable."

## Background Information

The [manual of GNU Coreutils](https://www.gnu.org/software/coreutils/manual/html_node/uname-invocation.html) states the following for the '-m' and '-p' options of the uname command:
<pre>
‘-m’
‘--machine’

    Print the machine hardware name (sometimes called the hardware class or hardware type).

‘-p’
‘--processor’

    Print the processor type (sometimes called the instruction set architecture or ISA). 
    Print ‘unknown’ if this information is not available. 
    <b>Note this is non-portable (even across GNU/Linux distributions).</b>
</pre>

In practice, the [default implementation](https://github.com/coreutils/coreutils/blob/1edda5009b1118ee28faa1b30154f5d9011780ba/src/uname.c#L299) of the command uname by calling the [uname syscall](https://man7.org/linux/man-pages/man2/uname.2.html).
OTOH, to get the processor type the command uname relies on optional operating system features not available on Linux (sysinfo, sysctl) and defaults to the value 'unknown'. On some distributions the implementation of uname is patched to output the same value as uname -m. [Example: [Fedora](https://src.fedoraproject.org/rpms/coreutils/blob/rawhide/f/coreutils-8.2-uname-processortype.patch)]. Evidently, on other distributions such as Gentoo Linux this option outputs the full info of the processor ("Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz").

On MacOS we had this problem before and was fixed (#13534) by switching to 'uname -m'.

As a reference, [here is a table](https://en.wikipedia.org/wiki/Uname#Examples) with the output values of the command uname for various platforms.

**Comment by jftuduri** [comment]
### Proposed changes

#### Minimal fix
Change this:
https://github.com/wazuh/wazuh/blob/394f627b3915f64dfc1a5b7ba55f61076159d2d2/src/Makefile#L1160-L1164

for:
`cpu_arch := ${uname_M`}

- If we are switching to uname -m there is no need for the special case for MacOS.

#### Additional improvements

- Remove this:
https://github.com/wazuh/wazuh/blob/394f627b3915f64dfc1a5b7ba55f61076159d2d2/src/Makefile#L1165-L1170

   - The `arch` command "[is equivalent to 'uname -m'](https://www.gnu.org/software/coreutils/manual/html_node/arch-invocation.html)". It is redundant if we use uname -m from the beginning.
   - The second `ifneq` is also redundant.

- Is this fallback correct ?
https://github.com/wazuh/wazuh/blob/394f627b3915f64dfc1a5b7ba55f61076159d2d2/src/Makefile#L1182-L1184
  - At this point `cpu_arch` has the value of `uname -m`. If we could not match that value to one of the precompiled architecture paths the resulting URL will be incorrect. This is what happened on the Gentoo Linux that started this issue.
  - Options (Need to consider how this options affect installing from the install.sh script):
    - Exiting with an error message stating that the architecture could not be detected.
    - Exiting with an error message stating that the architecture could not be detected and suggesting compiling with EXTERNAL_SRC_ONLY=yes.
    - Defaulting to building dependencies from sources (may be with a warning message).
    - Allowing to set PRECOMPILED_ARCH from the command line.
