### ISSUE TITLE
Possible error compiling external libraries

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#14110]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | Installation | Manager/Agent | Sources | Gentoo |

 ## Description

Some external libraries may be relying on other libraries found in the local environment, and this may cause undefined references errors  building wazuh (agent/server).
External libraries should depend only on libc or other libraries deployed by wazuh.

## Evidence 
Installing agent v4.3.4 from sources on Gentoo Linux, due to an error downloading the precompiled libraries(#14109), the install script built all the external libraries from sources. This generated some undefined references and a failed build process.

In this case there were undefined references to nghttp2 and libb2:
```

/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `nghttp2_pack_settings_payload'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `nghttp2_http2_strerror'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `nghttp2_session_callbacks_set_on_invalid_frame_recv_callback'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `nghttp2_submit_request'
```

```
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `blake2sp_update'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `blake2sp_final'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/../../../../x86_64-pc-linux-gnu/bin/ld: /home/vagrant/wazuh-4.3.4/src/libwazuhext.so: undefined reference to `blake2sp_init'
collect2: error: ld returned 1 exit status
```

In this particular case this problem was solved disabling nghttp2 in curl, and libb2 in libarchive:

`	cd $(EXTERNAL_CURL) && CPPFLAGS="-fPIC -I${ROUTE_PATH}/${EXTERNAL_OPENSSL}include" LDFLAGS="-L${ROUTE_PATH}/${EXTERNAL_OPENSSL}" LIBS="-ldl -lpthread" ./configure --disable-ldap --without-libidn2 --without-libpsl --without-brotli --without-nghttp2`

`	cd ${EXTERNAL_LIBARCHIVE} && CPPFLAGS=-fPIC ./configure --disable-acl --without-expat --without-iconv --without-xml2 --without-lz4 --without-lzma --without-zstd --without-bz2lib --without-openssl --without-libb2`

**Comment by chemamartinez** [comment]
Fixed at https://github.com/wazuh/wazuh/pull/15739
