### ISSUE TITLE
crowdstrike json format log not decoded in wazuh

### ISSUE THREAD

**Issue by warezers** [wazuh/wazuh#14116]
I am currently testing the Crowdstike SIEM connector and I received logs in json format

i also used wazuh agent config

```
<localfile> 
        <location>/var/log/crowdstrike/falconhoseclient/output</location>
        <log_format>syslog</log_format>
</localfile>
```

my json format output log in `/var/log/crowdstrike/falconhoseclient/output`

```
{
  "metadata":{
   "customerIDString":"956f887xxxxxx",
   "offset":6068,
   "eventType":"AuthActivityAuditEvent",
   "eventCreationTime":1656862026109,
   "version":"1.0"
  },
  "event":{
   "UserId":"api-client-id:24c6e2395axxxxxxx",
   "UserIp":"101.0.60.100",
   "OperationName":"streamStarted",
   "ServiceName":"Crowdstrike Streaming API",
   "Success":true,
   "UTCTimestamp":1656862026,
   "AuditKeyValues":[
     {
      "Key":"APIClientID",
      "ValueString":"24c6e2395a0c4a2eb2xxxxxxx"
     },
     {
      "Key":"partition",
      "ValueString":"0"
     },
     {
      "Key":"offset",
      "ValueString":"6067"
     },
     {
      "Key":"appId",
      "ValueString":"siem-connect"
     },
     {
      "Key":"eventType",
      "ValueString":"[MobileDetectionSummaryEvent LoginAuditEvent DetectionSummaryEvent FirewallMatchEvent ReconNotificationSummaryEvent IdentityProtectionEvent ScheduledReportNotificationEvent IncidentSummaryEvent CSPMIOAStreamingEvent CustomerIOCEvent XdrDetectionSummaryEvent RemoteResponseSessionEndEvent AuthActivityAuditEvent RemoteResponseSessionStartEvent HashSpreadingEvent CSPMSearchStreamingEvent UserActivityAuditEvent]"
     }
   ]
  }
}
```

I check archives.json and archives.log and the log is received, but it doesn't get the full json format
is received as

```
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ {
..
..
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ "Key":"offset"
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ "Key":"offset"
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ 
"ValueString":"6067"
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ 
 "ValueString":"[MobileDetectionSummaryEvent LoginAuditEvent DetectionSummaryEvent FirewallMatchEvent ReconNotificationSummaryEvent IdentityProtectionEvent ScheduledReportNotificationEvent IncidentSummaryEvent CSPMIOAStreamingEvent CustomerIOCEvent XdrDetectionSummaryEvent RemoteResponseSessionEndEvent AuthActivityAuditEvent RemoteResponseSessionStartEvent HashSpreadingEvent CSPMSearchStreamingEvent UserActivityAuditEvent]"
2022 Jul 02 16:45:25 (test-vm) any->/var/log/crowdstrike/falconhoseclient/output/ {
```

maybe the json format is received wrong?

How to create a decode and create a rule for this json format?

**Comment by ArielIvanOjeda** [comment]
Hi sam,
I hope you are doing well today and thank you for using the Wazuh community!
Regarding your question, I noticed that in the localfile configuration you are sharing the log_format is syslog, if you are writing logs to that file in json format, you should change this option to json, as shown here:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#log-format
This should solve your problem of the json logs not being interpreted correctly.
Please note that the logs need to be a one line log (I don't know if you are using a tool to format the json but it looks like it is a multiline log). Please check the Crowdstrike documentation to see if you can send the logs as a one line json record and if this cannot be done, if they can be sent in syslog format (you should match the localfile log_format option depending on what you are sending).
Also, Wazuh has the option of sending the logs directly to the Manager using syslog:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html
Best regards,
Ariel Ojeda.

**Comment by ArielIvanOjeda** [comment]
Duplicate from a Slack community post.
