### ISSUE TITLE
Engine - Windows events decoder

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#14151]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | any | Linux |

As part of #13803 we want to develop a Windows events decoder.

**Comment by hitman28594** [comment]
Hi,

If the windows decoders are being updated, can we update the field name structure in the eventchannel.c decoder to be more inline with ecs?

Current: win.eventdata.{FIELDNAME}
Update: winlog.event_data.{FIELDNAME}

This would allow Wazuh Opensearch setup to integrate with Sigma rules out of the box!! This would be a huge improvement which would significantly help progress the development of the Wazuh ruleset.

But if that .c decoder isn’t possible to change, nxlog has already mapped windows fields to ecs.

There are many windows fields which are not mapped to ecs fields as part of this commit, many of the missing ones can be scraped from the following documentation:

https://docs.nxlog.co/userguide/integrate/elastic-common-schema.html

**Comment by JavierBejMen** [comment]
Moved conversation to #14262
