### ISSUE TITLE
Test: Installation

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1415]
# Installation test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
|3.7.0 | 3703 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

## RPM (Linux)

- [x] Sucessful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log
- [ ] CentOS5
- [x] Check uninstall (services / files / users)
- [ ] /opt

## DEB (Linux)

- [x] Sucessful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] Check apt-get remove
- [x] Check apt-get purge
- [x] Check uninstall (services / files / users)
- [x] No errors in ossec.log

## MSI (Windows)

- [x] Sucessful instalation
- [x] Install using the package parameters
- [x] WUI doesn't show any strange information
- [x] ossec.conf show correct information

## EXE (Windows)

- [ ] Same behavior as installing by MSI

## Mac OS X

- [ ] Sucessful installation
- [ ] Check version

## Solaris (Intel)

- [ ] Sucessful installation
- [ ] Check version

## Solaris (SPARC)

- [ ] Sucessful installation
- [ ] Check version

## (HP-UX)

- [ ] Sucessful installation
- [ ] Check version

## AIX

- [ ] Sucessful installation
- [ ] Check version

## Sources

- [x] Sucessful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log

**Comment by Cerv1** [comment]
# Installation 

## RPM
| Operative System | Result |
| ------------------------ | ---------|
| CentOS 7 | **✔** | 
| CentOS 6 | **─** |
| CentOS 5 | **─** |


## DEB

| Operative System | Result |
| ------------------------ | ---------|
| Ubuntu 18.04 | **─** |
| Ubuntu 16.04 | **─** |
| Ubuntu 14.04 | **─** |
| Ubuntu 12.04 | **─** |
| Debian 9  | **─** | 
| Debian 8 | **─** |
| Debian 7 | **─** |
