### ISSUE TITLE
MISP INTEGRATION

### ISSUE THREAD

**Issue by aminemirat** [wazuh/wazuh#14168]
hello everyone,

i hope this message finds you well,so how can I integrate misp with Wazuh?

regards

**Comment by FrancoRivero** [comment]
Hi @aminemirat ,
In order to integrate with MISP (and have something similar to the VirusTotal integration), you will need to write a script.
In some cases, it is possible to just edit the ossec.conf configuration with your credentials or API key, but this is only for integrations that we already have a script for.
 These integrations are [Slack](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#slack), [VirusTotal](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#virustotal) and [PagerDuty](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#pagerduty). 
 In fact, if you go this path: `/var/ossec/integrations/`, you should be able to see the corresponding scripts to each tool.
 We also have an example of an integration with Jira in the [following blog](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/), where this integration is used to explain how to write a custom script. 
 In order to integrate with MISP, you will have to follow the steps explained in the blog, but the script will have to be a little bit different. As in the Jira example, you will need to select the file to which all the alerts are arriving (by default, it will be alerts.json). 
 So, we will need to set the group condition. It will look something similar to if "syslog" in alerts["rules"]["groups"], taking into account that the alerts variable is the information from the alerts.json file. Then, making use of the MISP API, you can forward this alert to the MISP tool. In order to add an event to MISC you can follow [the next guide](https://www.misp-project.org/openapi/).
 Once the event is scanned, you can forward the result to Wazuh. Not sure if you will need to write decoders and rules for these events, but in that case, you can follow [the next guide](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html).
Then you can manage the integration by editing the Wazuh manager configuration file:

`/var/ossec/etc/ossec.conf`

and adding the following code block inside the <ossec_config> section:

```
<integration>
  <name> </name>
  <hook_url> </hook_url>
  <api_key> </api_key>   <!-- Optional filters -->
  <rule_id> </rule_id>
  <level> </level>
  <group> </group>
  <event_location> </event_location>
</integration>
```

Then, you should include the MISP API key at api_key field and, in case the API provides it, it's recommended to add the API's URL in hook_url field.
Then, restart the wazuh-manager service:

`systemctl restart wazuh-manager`

Our documentation is our best support in these cases, but if it is not clear enough, you can also take a look at this [blog](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html)

Hope this helps!
Regards,

**Comment by ips972** [comment]
Hi [FrancoRivero](https://github.com/FrancoRivero), thanks for the VERY high level guide.. 

can you please point me to a full guide/answer for us newb's on how to configure this integration. all the way. 
including an example of the parameters  missing here: 
<integration>
  <name> </name>
  <hook_url> </hook_url>
  <api_key> </api_key> 
  <rule_id> </rule_id>
  <level> </level>
  <group> </group>
  <event_location> </event_location>
</integration>


and the custom scripts if needed, how to point to it and there to put it.. 

great thanks in advance!

**Comment by FrancoRivero** [comment]
Hi @ips972, 
sorry for the late answer!
[Here](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/)  there is a good guide to follow in order to configure a new integration so this guide explains how to write a custom script, how to link with wazuh modules and how to test if this integration working fine.
Regarding to the configuration you should write something like:
```
<integration>
  <name>NAME_SCRIPT</name>
  <group>syscheck</group>
  <hook_url>MISP_URL_API</hook_url>
  <api_key>MISP_API</api_key>
  <alert_format>json</alert_format>
</integration>
```
you are integrating MISP with [FIM](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html) module.

Regards

**Comment by FrancoRivero** [comment]
Hi @ips972,
How are you?
Can you solve the problem? I will close this issue if you have other problem you let reopen it !
Regards

**Comment by pleibling** [comment]
@FrancoRivero : Hello Franco, i work on the same.
 **I use the integration block in ossec.conf:**
<integration>
    <name>custom-misp.py</name>
<group>sysmon_event1,sysmon_event3,sysmon_event6,sysmon_event7,sysmon_event_15,sysmon_event_22,syscheck</group>
    <rule_id>616130,100010</rule_id>
    <alert_format>json</alert_format>
  </integration>
**Then in local_rules.xml:**
<group name="windows,sysmon,">
  <rule id="616130" level="3">
    <if_sid>61600</if_sid>
    <field name="win.system.eventID">^22$</field>
    <description>Sysmon - Event 22: DNS Query for $(win.eventdata.queryName) by $(win.eventdata.image)</description>
    <options>no_full_log</options>
    <group>sysmon_event_22,</group>
  </rule>
</group>
**Then in rule misp.xml:**
<group name="misp,">
  <rule id="100620" level="10">
    <field name="integration">misp</field>
    <match>misp</match>
    <description>MISP Events</description>
    <options>no_full_log</options>
  </rule>
  <rule id="100621" level="5">
    <if_sid>100620</if_sid>
    <field name="misp.error">\.+</field>
    <description>MISP - Error connecting to API</description>
    <options>no_full_log</options>
    <group>misp_error,</group>
  </rule>
  <rule id="100622" level="12">
    <field name="misp.category">\.+</field>
    <description>MISP - IoC found in Threat Intel - Category: $(misp.category), Attribute: $(misp.value)</description>
    <options>no_full_log</options>
    <group>misp_alert,</group>
  </rule>
</group>
**Then i use the custom-misp.py:**
#!/var/ossec/framework/python/bin/python3
## MISP API Integration
#
import sys
import os
from socket import socket, AF_UNIX, SOCK_DGRAM
from datetime import date, datetime, timedelta
import time
import requests
from requests.exceptions import ConnectionError
import json
import ipaddress
import hashlib
import re
pwd = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
socket_addr = '{0}/queue/sockets/queue'.format(pwd)
def send_event(msg, agent = None):
    if not agent or agent["id"] == "000":
        string = '1:misp:{0}'.format(json.dumps(msg))
    else:
        string = '1:[{0}] ({1}) {2}->misp:{3}'.format(agent["id"], agent["name"], agent["ip"] if "ip" in agent else "any", json.dumps(msg))
    sock = socket(AF_UNIX, SOCK_DGRAM)
    sock.connect(socket_addr)
    sock.send(string.encode())
    sock.close()
false = False
# Read configuration parameters
alert_file = open(sys.argv[1])
# Read the alert file
alert = json.loads(alert_file.read())
alert_file.close()
# New Alert Output if MISP Alert or Error calling the API
alert_output = {}
# MISP Server Base URL
misp_base_url = "https://192.168.50.252/attributes/restSearch/"
# MISP Server API AUTH KEY
misp_api_auth_key = "pleiblings-api-key"
# API - HTTP Headers
misp_apicall_headers = {"Content-Type":"application/json", "Authorization":f"{misp_api_auth_key}", "Accept":"application/json"}
## Extract Sysmon for Windows/Sysmon for Linux and Sysmon Event ID
event_source = alert["rule"]["groups"][0]
event_type = alert["rule"]["groups"][2]
## Regex Pattern used based on SHA256 lenght (64 characters)
regex_file_hash = re.compile('\w{64}')
if event_source == 'windows':
    if event_type == 'sysmon_event1':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event3' and alert["data"]["win"]["eventdata"]["destinationIsIpv6"] == 'false':
        try:
            dst_ip = alert["data"]["win"]["eventdata"]["destinationIp"]
            if ipaddress.ip_address(dst_ip).is_global:
                wazuh_event_param = dst_ip
            else:
                sys.exit()
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event3' and alert_output["data"]["win"]["eventdata"]["destinationIsIpv6"] == 'true':
        sys.exit()
    elif event_type == 'sysmon_event6':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event7':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event_15':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event_22':
        try:
            wazuh_event_param = alert["data"]["win"]["eventdata"]["queryName"]
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event_23':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event_24':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    elif event_type == 'sysmon_event_25':
        try:
            wazuh_event_param = regex_file_hash.search(alert["data"]["win"]["eventdata"]["hashes"]).group(0)
        except IndexError:
            sys.exit()
    else:
        sys.exit()
    misp_search_value = "value:"f"{wazuh_event_param}"
    misp_search_url = ''.join([misp_base_url, misp_search_value])
    try:
        misp_api_response = requests.get(misp_search_url, headers=misp_apicall_headers, verify=False)
    except ConnectionError:
        alert_output["misp"] = {}
        alert_output["integration"] = "misp"
        alert_output["misp"]["error"] = 'Connection Error to MISP API'
        send_event(alert_output, alert["agent"])
    else:
        misp_api_response = misp_api_response.json()
    # Check if response includes Attributes (IoCs)
        if (misp_api_response["response"]["Attribute"]):
    # Generate Alert Output from MISP Response
            alert_output["misp"] = {}
            alert_output["misp"]["source"] = {}
            alert_output["misp"]["event_id"] = misp_api_response["response"]["Attribute"][0]["event_id"]
            alert_output["misp"]["category"] = misp_api_response["response"]["Attribute"][0]["category"]
            alert_output["misp"]["value"] = misp_api_response["response"]["Attribute"][0]["value"]
            alert_output["misp"]["type"] = misp_api_response["response"]["Attribute"][0]["type"]
            alert_output["misp"]["source"]["description"] = alert["rule"]["description"]
            send_event(alert_output, alert["agent"])
elif event_source == 'linux':
    if event_type == 'sysmon_event3' and alert["data"]["eventdata"]["destinationIsIpv6"] == 'false':
        try:
            dst_ip = alert["data"]["eventdata"]["DestinationIp"]
            if ipaddress.ip_address(dst_ip).is_global:
                wazuh_event_param = dst_ip
                misp_search_value = "value:"f"{wazuh_event_param}"
                misp_search_url = ''.join([misp_base_url, misp_search_value])
                try:
                    misp_api_response = requests.get(misp_search_url, headers=misp_apicall_headers, verify=False)
                except ConnectionError:
                    alert_output["misp"] = {}
                    alert_output["integration"] = "misp"
                    alert_output["misp"]["error"] = 'Connection Error to MISP API'
                    send_event(alert_output, alert["agent"])
                else:
                    misp_api_response = misp_api_response.json()
        # Check if response includes Attributes (IoCs)
                    if (misp_api_response["response"]["Attribute"]):
                # Generate Alert Output from MISP Response
                        alert_output["misp"] = {}
                        alert_output["misp"]["event_id"] = misp_api_response["response"]["Attribute"][0]["event_id"]
                        alert_output["misp"]["category"] = misp_api_response["response"]["Attribute"][0]["category"]
                        alert_output["misp"]["value"] = misp_api_response["response"]["Attribute"][0]["value"]
                        alert_output["misp"]["type"] = misp_api_response["response"]["Attribute"][0]["type"]
                        send_event(alert_output, alert["agent"])
            else:
                sys.exit()
        except IndexError:
            sys.exit()
    else:
        sys.exit()
elif event_source == 'ossec' and event_type == "syscheck_entry_added":
    try:
        wazuh_event_param = alert["syscheck"]["sha256_after"]
    except IndexError:
        sys.exit()
    misp_search_value = "value:"f"{wazuh_event_param}"
    misp_search_url = ''.join([misp_base_url, misp_search_value])
    try:
        misp_api_response = requests.get(misp_search_url, headers=misp_apicall_headers, verify=false)
    except ConnectionError:
        alert_output["misp"] = {}
        alert_output["integration"] = "misp"
        alert_output["misp"]["error"] = 'Connection Error to MISP API'
        send_event(alert_output, alert["agent"])
    else:
        misp_api_response = misp_api_response.json()
    # Check if response includes Attributes (IoCs)
        if (misp_api_response["response"]["Attribute"]):
    # Generate Alert Output from MISP Response
            alert_output["misp"] = {}
            alert_output["misp"]["event_id"] = misp_api_response["response"]["Attribute"][0]["event_id"]
            alert_output["misp"]["category"] = misp_api_response["response"]["Attribute"][0]["category"]
            alert_output["misp"]["value"] = misp_api_response["response"]["Attribute"][0]["value"]
            alert_output["misp"]["type"] = misp_api_response["response"]["Attribute"][0]["type"]
            send_event(alert_output, alert["agent"])
else:
    sys.exit()
**Change the ownership and rights:**
_2497489 12 -rwxr-x---  1 root wazuh 8421 Sep  3 19:17 custom-misp.py_
2497135  8 -rwxr-x---  1 root wazuh 4325 Jun 23 18:05 pagerduty
2497138  4 -rwxr-x---  1 root wazuh 1020 Jun 23 18:05 slack
2497139  4 -rwxr-x---  1 root wazuh 3809 Jun 23 18:05 slack.py
2497136  4 -rwxr-x---  1 root wazuh 1020 Jun 23 18:05 virustotal
2497137  8 -rwxr-x---  1 root wazuh 6439 Jun 23 18:05 virustotal.py
**Create a DNS Event as trigger and get the information in Wazuh, but in the integrations.log i get this message:**
2022/09/05 12:32:13 wazuh-integratord: ERROR: Unable to run integration for custom-misp.py -> integrations
2022/09/05 12:32:13 wazuh-integratord: ERROR: While running custom-misp.py -> integrations. Output: KeyError: 'response'
**When i open the URL in the Browser, i get this message:**
Authentication failed. Please make sure you pass the API key of an API enabled user along in the Authorization header.
In the template vor custom-misp.py is anywhere a setting for User. Can i see, whats going wrong? Or can i see, what is send?
Thanks for your help.

**Comment by andyoulovexy** [comment]
> Content-Type":"application/json", "Authorization":f"{misp_api_auth_key}", "Accept":"application/json"}

sysmon_event_22 rules not in wazuh ,you need create it by yourself!!!

**Comment by pleibling** [comment]
@andyoulovexy: Thanks for your feedback - all the settings was fine. There is an configuration error in my Wazuh. I install a fresh new MSIP and WAZUH. add integration in ossec.conf, rules in local_rules.xml, custom-misp.py (change IP and API Key, rights and ownerschip - like before), change settings in WINDOWS Group of agents and restart Wazuh-manager. In my testeinvironment it works now fine.
![image](https://user-images.githubusercontent.com/112875086/188869331-65338d72-5135-443f-a8f5-6a1205a42c81.png)

**Comment by pleibling** [comment]
I found the Error -  i used in my productive Environment this: https://wazuh.com/blog/monitoring-commonly-abused-windows-utilities/

This rule use the 100622 Number. In the sample Script the use the same ID - i create ranges for custom rules and use an another rule - now it works fine.

E.g.:

Sophos Custom Rules 
![rules](https://user-images.githubusercontent.com/112875086/212651833-5583d85e-eaa9-4c28-b98b-30d1477e40e4.png)

**Comment by Srinivas0rch** [comment]
@pleibling how did you enable cert for https://192.168.50.252/attributes/restSearch/"

I have installed a new MISP instance but am getting the below error.

Something went wrong. stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed stream_socket_client(): Failed to enable crypto stream_socket_client(): unable to connect
