### ISSUE TITLE
Test: Integrator

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1416]
# Integrator test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.0 | 3701 | 3.7 |
| 3.7.0 | 3706 | 3.7 |
| 3.7.0 | 3717 | 3.7 |

### Configuration

- [ ] Configure the VirusTotal integration. (1)
- [ ] Get an alert: "Incorrect API credentials". (1).
- [ ] Get the alert: "Rate limit reached". (1)

### Scan

- [ ] Monitor a folder in real-time, getting "not found" alerts by VT. (1)
- [ ] Monitor a file and scanning it. (1)
- [ ] Monitor a malicious file getting a "positive" alert found by VT. (1)

(1) https://documentation.wazuh.com/3.x/user-manual/capabilities/virustotal-scan/integration.html?highlight=integrator
## Slack

- [ ] Configure the Slack integration and get alerts on Slack. (2)

## PagerDuty

- [ ] Configure the PagerDuty integration. (2)
- [ ] Get alerts on the PagerDuty Dashboard. (2)

(2) https://documentation.wazuh.com/3.x/user-manual/manager/manual-integration.html?highlight=integrator

**Comment by elwali10** [comment]
## PagerDuty

-  I have alerts on my integrations.log file but nothing on the dashboard for alerts  : 

```
> Tue Oct 16 15:11:54 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539702714-1235546918.alert UfuVNCDXBEhPw5gUvWV2 
> Tue Oct 16 15:12:20 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539702740--2138383684.alert UfuVNCDXBEhPw5gUvWV2 
> Tue Oct 16 15:19:46 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539703186-628120445.alert UfuVNCDXBEhPw5gUvWV2 
> Tue Oct 16 15:23:30 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539703410-946160488.alert UfuVNCDXBEhPw5gUvWV2 
> Tue Oct 16 15:25:00 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539703500--2145568122.alert UfuVNCDXBEhPw5gUvWV2 
> Tue Oct 16 15:25:34 UTC 2018 /var/ossec/integrations/pagerduty /tmp/pagerduty-1539703534-737689963.alert UfuVNCDXBEhPw5gUvWV2 
```

## VirusTotal

- "Incorrect API credentials" alert  not triggered when setting wrong API key
