### ISSUE TITLE
Wazuh 4.3.5 not doing basic local rules checks

### ISSUE THREAD

**Issue by oliveiralive** [wazuh/wazuh#14166]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5 | Wazuh Manager | Manager | Packages| Ubuntu 22.04 |

Hi Team, i started to test the Wazuh manager 4.3.5 and i found a problem in local rules,

The local rule is allowing to save 2 rules whith the same ID, its not doing the basic tests

Wazuh v4.3.5
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/35010493/177656498-507eb31d-b293-400e-a80d-1efdddf6941b.png">

In tested the same situation on wazuh 4.2.5 and the check rule its work
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/35010493/177656912-f9a6b41e-bacb-4dc3-a576-836086ac1310.png">

**Comment by oliveiralive** [comment]
Hi guys, sameone check this problem?

i tried in the 4.3.5 and the problem continue

**Comment by oliveiralive** [comment]
Hi @vikman90 
Can you check this?

O believe that's is a high problem in the new versoins

**Comment by vikman90** [comment]
@oliveiralive Sorry for the late response. 4.3.0 introduced a change in the ruleset parser (#10720) that relaxed the restrictions:

- If a rule ID is duplicated, the rule is simply ignored.
- If an `<if_sid>` points to a missing rule ID, that rule is skipped.

For instance, let's use your local_rules.xml file:
```xml
<group name="Firewalls">
  <rule id="115100" level="3">
    <if_sid>70020</if_sid>
    <field name="log_type">Event</field>
    <description>Sophos XG - Event</description>
  </rule>

  <rule id="115100" level="12">
    <if_sid>115000</if_sid>
    <field name="message">logged in successfully to Web Admin Console</field>
    <description>Sophos XG ($message) em $(device_name), SrcIP $(src_ip)</description>
  </rule>

</group>
```

### Behavior in 4.2.x and older

```shell
$ /var/ossec/bin/wazuh-analysisd -t
```

> 2023/07/11 09:40:47 wazuh-analysisd: ERROR: Duplicate rule ID:115100
> 2023/07/11 09:40:47 wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.

### Behavior in 4.3.x and newer

```shell
$ /var/ossec/bin/wazuh-analysisd -t
```

>2023/07/11 09:47:10 wazuh-analysisd: WARNING: (7612): Rule ID '115100' is duplicated. Only the first occurrence will be considered.

Hope it helps. Let me close this issue as it is an expected behavior.

Best regards.
