### ISSUE TITLE
Enable Vulnerability Detector for HP-UX

### ISSUE THREAD

**Issue by j0serca** [wazuh/wazuh#14211]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.5 | Vulnerability Detector | Agent | Packages | HP-UX 11.31 |

## **Description**
Hello team,

I am reaching out to you with this request to enable the `Vulnerability Detector` module for HP-UX 11.31.

The only document related is regarding the use of the [allow option](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html), but after testing it, the VD module is not being enabled on HP-UX agents.

Thank you!

### Evidence

![image](https://user-images.githubusercontent.com/93411185/178355521-9ba39b4e-00a1-435c-94df-7cbafa1d0f4f.png)

![image](https://user-images.githubusercontent.com/93411185/178356451-24936073-0649-4f06-a8f8-27fe9dad3d6f.png)

![image](https://user-images.githubusercontent.com/93411185/178355835-3a8b696b-3899-467e-ae4b-c3d4d88856b9.png)

When I should be able to see the option as shown here:

![image](https://user-images.githubusercontent.com/93411185/178360891-1b44a56a-0988-4a9d-80cc-5146ffa8f801.png)

I'm also attaching some information about HP-UX vulnerabilities:

- https://www.cvedetails.com/vulnerability-list/vendor_id-10/product_id-20/cvssscoremin-5/cvssscoremax-5.99/HP-Hp-ux.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=hp-ux
- https://support.hpe.com/hpesc/public/docDisplay?docId=kc0118533en_us&docLocale=en_US

**Comment by chemamartinez** [comment]
Hi team,

After analyzing the viability of supporting HP-UX in Vulnerability Detector these are the conclusions:
- The package inventory can be collected as the team explains at https://github.com/wazuh/wazuh/issues/14786. This is a requirement to scan HP-UX agents for vulnerabilities.
- Regarding the vulnerability data sources. The NVD is the only reliable source to obtain vulnerabilities of HP-UX. The official vendor doesn't provide any particular feed.
- Focused on the NVD, it contains the necessary vulnerability information to support HP-UX with reliable results.
- The current Vulnerability Detector engine is ready to support HP-UX including small changes. It will follow the same logic as other platforms such as macOS whose packages are evaluated against the NVD.

Changes needed to scan HP-UX agents:
- Create the OS CPE regarding the HP-UX version obtained from the OS inventory
- Once collected the HP-UX inventory, attach HP-UX agents to the NVD analysis engine.
- Analysis of results
