### ISSUE TITLE
Wazuh OpenDashboard

### ISSUE THREAD

**Issue by nathivitas** [wazuh/wazuh#14234]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Hi, could I update Wazuh-Dashboard certificates to a custom cert issued by an internal CA?

Is there a reference guide to applying a change like that? Let me know.

**Comment by TomasTurina** [comment]
Hi @nathivitas.

Have you taken a look at this [documentation](https://documentation.wazuh.com/current/user-manual/certificates.html#certificates-deployment)?

There you will find a way to create your custom certificates. Take a look at this note:

> Additionally, this script allows the use of a pre-existent rootCA certificate. To create all the certificates using a pre-existent rootCA certificate, use option -A and indicate the root-ca certificate and key as follows:
> 
> bash wazuh-certs-tool.sh -A /path/to/root-ca.pem /path/to/root-ca.key

After you have them, you can deploy the certificates by following this [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#deploying-certificates). Here are the key steps:

> mkdir /etc/wazuh-dashboard/certs
> tar -xf ./wazuh-certificates.tar -C /etc/wazuh-dashboard/certs/ ./$NODE_NAME.pem ./$NODE_NAME-key.pem ./root-ca.pem
> mv -n /etc/wazuh-dashboard/certs/$NODE_NAME.pem /etc/wazuh-dashboard/certs/dashboard.pem
> mv -n /etc/wazuh-dashboard/certs/$NODE_NAME-key.pem /etc/wazuh-dashboard/certs/dashboard-key.pem
> chmod 500 /etc/wazuh-dashboard/certs
> chmod 400 /etc/wazuh-dashboard/certs/*
> chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/certs

I hope this information helps.

**Comment by nathivitas** [comment]
"[ConnectionError]: unable to verify the first certificate" after trying
any suggestions?

**Comment by nathivitas** [comment]
There is a bug caused by the opensearch.ssl.verificationMode, you will have
to set it to "none" in order to load non-default certificates after an
installation has been done.
Otherwise, the security plugin will continue to try to validate an internal
CA authority even tho it was added but keeps failing.
