### ISSUE TITLE
Handle exceptions at the lowest level when trying to read files with the Wazuh API

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#14245]
|Wazuh version|Component|
|---|---|
| 4.3.5 | Wazuh API |

## Description

The Wazuh API is not properly handling `UnicodeDecodeError` when reading files. This issue leads to, in addition to undesired `500` responses, the Wazuh UI malfunctioning.

This behavior can be observed during the ruleset listing (`GET /rules`). If one of the rules contains an invalid character, no rule will be returned. What we would expect from this situation is to be able to read every valid rule and obtain a failed item in the response reporting the corrupted file. An example of the traceback would be the following:

```
2022/07/14 14:56:13 ERROR: Error executing API request locally: 'utf-8' codec can't decode bytes in position 139-140: invalid continuation byte
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 243, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.5-py3.9.egg/wazuh/rule.py", line 71, in get_rules
    rules.extend(load_rules_from_file(rule_file['filename'], rule_file['relative_dirname'], rule_file['status']))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.5-py3.9.egg/wazuh/core/rule.py", line 72, in load_rules_from_file
    root = load_wazuh_xml(os.path.join(common.WAZUH_PATH, rule_relative_path, rule_filename))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.5-py3.9.egg/wazuh/core/utils.py", line 786, in load_wazuh_xml
    data = f.read()
  File "/var/ossec/framework/python/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 139-140: invalid continuation byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.5-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 288, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 139-140: invalid continuation byte
2022/07/14 14:56:13 INFO: wazuh 172.21.0.1 "GET /rules" with parameters {} and body {} done in 0.540s: 500
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by GGP1** [comment]
## Status update

Reviewing the status of this issue I noticed that the **Integration API endpoints test** check failed. I ran the failing tests locally to see what was wrong and these were the results:

`test_agent_POST_endpoints` -> All tests passed

`test_agent_PUT_endpoints` -> 1 case failed but it's not related to the changes this PR contains. Logs:
```
test_agent_PUT_endpoints.tavern.yaml::PUT /agents/{agent_id}/upgrade_custom FAILED

'failed_items': [{'error': {'code': 'message': 'Upgrade procedure could not start. Agent already upgrading'}, 'id': ['008']}],
```
> It may be a race condition when upgrading multiple agents, I tried changing the agent id but that didn't help.

`test_cluster_endpoints` -> All tests passed

**Comment by GGP1** [comment]
## Status update

Regarding the failing test `test_agent_PUT_endpoints` , there is an ongoing issue being developed to fix it -> https://github.com/wazuh/wazuh/issues/16347
