### ISSUE TITLE
AWS Amazon Linux - Agent unable to do SCA

### ISSUE THREAD

**Issue by ggacusan** [wazuh/wazuh#14258]
|Wazuh version 4.3.5|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.3.5|SCA|AWS All-in-one Deployment|AWS Marketplace|AWS|

SCA is configured on both the Agent and Wazuh Server.

In the agent, I have mapped the location of the AWS Amazon Linux YML and even have set an interval of one minute. 
The SCA module in the Wazuh server says "No Scans Available"
In the Agent, the error says "sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_amazon_linux_1.yml': 'Check Amazon Linux version.'
Agent OSSEC - SCA enabled and mapped the ruleset "cis_amazon_linux_1.yml"

Please see screenshots attached.

Thanks and I hope somebody can help.

![agent ossec logs](https://user-images.githubusercontent.com/109343824/179185671-a008c73b-aae0-4cab-af48-7f962b0f9df2.png)
![agent ossec sca config](https://user-images.githubusercontent.com/109343824/179185709-a2e4fd97-a462-4f2d-8ab4-880b9a0dcdfc.png)

**Comment by jnasselle** [comment]
Hi @ggacusan ,

I've just run an [Amazon Linux Docker container](https://hub.docker.com/layers/amazonlinux/library/amazonlinux/1/images/sha256-23ff831a5a7a8b479cc3efd50de0fe5d1a49323b05c7fb2eb398f85bc053eeff?context=explore) and validate that the policy's `requirements`  `rules` match the criteria, and it does not.
- Current
```
bash-4.2# cat /etc/system-release
Amazon Linux AMI release 2018.03
```
- Expected
```
bash-4.2# cat /etc/system-release
Amazon Linux AMI release 1
```

Could you please validate this in your environment too?
This seems a bug to me.

**Comment by ggacusan** [comment]
Hi @jnasselle ,

Thanks for your reply. Here's my current

# cat /etc/system-release
Amazon Linux AMI release 2018.03

Does this mean that I need to have a ruleset .yml for Amazon Linux AMI release 2018.03?
