### ISSUE TITLE
Release 4.3.6 - Release Candidate 1 - E2E UX tests - Configuration assessment

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14268]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #14188  |
| **Main E2E UX test issue** | #14260    |
| **Version**                      | 4.3.6 |
| **Release candidate #**          | RC1   |
| **Tag**                          | [v4.3.6-rc1](https://github.com/wazuh/wazuh/tree/v4.3.6-rc1) |
| **Previous modules tests issue** | #12889   |

## Installation procedure
- @sebasfalcone 
  - Wazuh Manager stack:[Installation assistant](https://documentation-dev.wazuh.com/4.3.6-rc/installation-guide/wazuh-server/installation-assistant.html) on Debian 11
  - Wazuh Agent: Wazuh WUI one-liner deploy FQDN on Amazon Linux 2
 - @jftuduri 
   - Wazuh Manager stack:[Step-by-step](https://documentation-dev.wazuh.com/4.3.6-rc/installation-guide/wazuh-indexer/step-by-step.html) on Ubuntu 22.04
   - Wazuh Agent: https://documentation-dev.wazuh.com/4.3.6-rc/installation-guide/wazuh-agent/index.html on Ubuntu 22.04

### Validate issues reported from last E2E test
https://github.com/wazuh/wazuh/issues/13030
https://github.com/wazuh/wazuh/issues/12347
### Validate changes from v4.3.0 to 4.3.6 (only if applies)
https://github.com/wazuh/wazuh/pull/13893
https://github.com/wazuh/wazuh/pull/13905
https://github.com/wazuh/wazuh/pull/13781
https://github.com/wazuh/wazuh/pull/13950
### Validate documentation consistency
https://documentation-dev.wazuh.com/4.3.6-rc/user-manual/capabilities/sec-config-assessment/index.html
### Validate use case
https://documentation-dev.wazuh.com/4.3.6-rc/user-manual/capabilities/sec-config-assessment/use-case.html
## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | Test went as expected. |
| :red_circle:  | Test fails and must be addressed. |
| :yellow_circle:  | Test meet the goal but some improvements must be addressed for UX|

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|:green_circle:|Validate documentation consistency| Functional | |
|:yellow_circle:|Validate issues reported from last E2E test|Functional| Issue wazuh#12347 is not still addressed since v4.3.0|
|:green_circle: |Validate issues reported from last E2E test|Functional| Issue wazuh#13030 solved|
|:yellow_circle:|Validate changes from v4.3.0 to 4.3.6|Functional|wazuh#13949 can be improved. Reopened |
|:yellow_circle:|Validate documentation consistency| Documentation | wazuh/wazuh-documentation#5478|
|:red_circle:|Validate documentation consistency| Functional | SCA checks IDs are not unique #14346|
|:yellow_circle:|Validate use case| Documentation | wazuh/wazuh-documentation#5478|

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by jftuduri** [comment]
## Wazuh Manager stack on Ubuntu 22.04

## Wazuh Agent on Ubuntu 22.04

## Changes from v4.3.0 to 4.3.6 #13893 

## Documentation consistency

## Use case: Getting an alert when a check changes its result value [(link)](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-case.html#id1)

## Wazuh Dasboard SCA scan results

**Comment by sebasfalcone** [comment]
## 🟢 Wazuh install on Amazon linux 2 

For this tests the `wazuh_install.sh` script was used, it was modified to download RC 4.3.6 from the URL `packages-dev.wazuh.com/pre-release`.

### 🟢 Wazuh Manager
- Very clean and descriptive console logs.
- No issue on installer from fresh amazon linux 2

```
🟢wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2022-07-16 19:29:02 UTC; 20min ago
   Process: 7119 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-manager.service
           ├─7428 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─7469 /var/ossec/bin/wazuh-authd
           ├─7486 /var/ossec/bin/wazuh-db
           ├─7511 /var/ossec/bin/wazuh-execd
           ├─7525 /var/ossec/bin/wazuh-analysisd
           ├─7527 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─7530 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─7544 /var/ossec/bin/wazuh-syscheckd
           ├─7561 /var/ossec/bin/wazuh-remoted
           ├─7641 /var/ossec/bin/wazuh-logcollector
           ├─7663 /var/ossec/bin/wazuh-monitord
           └─7685 /var/ossec/bin/wazuh-modulesd
```

### 🟢 Wazuh indexer
``` 
🟢wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2022-07-16 19:29:27 UTC; 20min ago
     Docs: https://documentation.wazuh.com
 Main PID: 7117 (java)
   CGroup: /system.slice/wazuh-indexer.service
           └─7117 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headl...
```

### 🟢 Wazuh dashboard
```
🟢wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Sat 2022-07-16 19:28:28 UTC; 22min ago
 Main PID: 6609 (node)
   CGroup: /system.slice/wazuh-dashboard.service
           └─6609 /usr/share/wazuh-dashboard/bin/../node/bin/node --no-warnings --max-http-header-size=65536 --unhandled-rejections=warn /usr/share/wazuh-dashboard/bin/../src/cli/dist -c /etc/wazuh-dashb...
```

## 🟢Wazuh agent installation on linux

For this test we used the one liner command provided by the wazuh dasboard WUI:
- It was necessary to modify the command because the URL provided for the version 4.3.6 is located on the pre-release state:
		- Provided:\
		`sudo WAZUH_MANAGER='wazuhmanager.com' WAZUH_AGENT_GROUP='default' yum install https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.6-1.x86_64.rpm`
		- Used:\
		`sudo WAZUH_MANAGER='wazuhmanager.com' WAZUH_AGENT_GROUP='default' yum install https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.3.6-1.x86_64.rpm`

🟢 Wazuh Agent installation on linux 2 
- No issue on installer from fresh amazon linux 2

## Extra testing:
- 🟢 Restart the server while agent is connected 

## SCA test:
- 🟢 Ensure sticky bit is set on all world-writable directories.
	- Remove sticky bits from the /tmp directory: `# chmod -t /tmp`
	- Check expected SCA alert is generated:
![image.png](https://images.zenhubusercontent.com/62c2dd4f5a5ef9ee9d59f34e/349a3d24-d966-429d-8258-ea8b57035d63)
- 🟢 Ensure iptables are flushed with nftables.
	- Install nftables: `# yum install nftables`
	- flush iptables and ip6tables rules: 
	```
	# iptables -F
	# ip6tables -F
	```
	- Check that control pass:
	![image.png](https://images.zenhubusercontent.com/62c2dd4f5a5ef9ee9d59f34e/9848f135-64ab-4aa2-bdfd-9718f5049a38)

- 🟢 Policy doesn't create the /dev/null file.
	- After multiple scans, no /dev/null file was created.
	```
	[root@linuxagent user1]# ls /dev/nul*
	/dev/null
	```

- 🔴 Ensure XD/NX support is enabled:
	- XD/NX support is disabled, yet the SCA scan detects it as enable
		```
		[root@linuxagent user1]# journalctl | grep "protection: active"
		Jul 15 18:21:21 localhost kernel: NX (Execute Disable) protection: active
		Jul 15 18:22:34 localhost kernel: NX (Execute Disable) protection: active
		```
![image.png](https://images.zenhubusercontent.com/62c2dd4f5a5ef9ee9d59f34e/18c6a009-35b3-423b-9924-a38f3b079e1d)
	- NOTE: This test was known to fail.
