### ISSUE TITLE
Wildcard (*) usage on Windows Registry Paths for FIM

### ISSUE THREAD

**Issue by Ifex370** [wazuh/wazuh#14321]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4-rev 40316 | FIM/Syscheck | Manager/Agent | Packages/Sources | Windows |

Hi Team,

I was recently carrying out some tests.

Within this test, is an attack that modifies registry keys on a specific Windows registry path.

`Computer\HKEY_USERS\S-1-5-21-3598137877-2702760727-2754458851-1xxx\Control Panel\Desktop`

Since these activities could occur on any user's path, I decided I should use a wildcard like this. (replacing the user above that begins with S-1-5-21... with a wildcard)

`Computer\HKEY_USERS\*\Control Panel\Desktop` - This should allow me to monitor changes for all users within a windows agent

The slight challenge, using the wildcard, I could not get logs. 

The PRs I encountered speak on FIM expansion for wildcard usage on Windows agents (file directories) but may have excluded this feature for Windows registry paths as well.

https://github.com/wazuh/wazuh/pull/8461
https://github.com/wazuh/wazuh/pull/8754

I think this issue is still open and would be a nice feature to add.

## Subtasks

- https://github.com/wazuh/wazuh-qa/issues/3693
- https://github.com/wazuh/wazuh-documentation/issues/5926

**Comment by jotacarma90** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Watchdogs-6039126e30fb7400140030e7/issues/wazuh/wazuh/14321?planning-poker) with ZenHub @antoniomanuelfr @FrancoRivero @MarcelKemp
