### ISSUE TITLE
SCA checks IDs are not unique

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14346]
| Related issue |
|---|
|wazuh/wazuh#14268 |

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.6-rc| SCA policies | Manager | Any | Any |

# Description

Currently there's no uniqueness between SCA checks id as stated in the documentation

![image](https://user-images.githubusercontent.com/1791430/179648743-1fab5dbc-b398-4c73-9452-7518e3cc6d0a.png)

- cis_sqlserver_2017 and cis_sqlserver_2016
- cis_apple_macOS_10.12 and cis_solaris11.4
- cis_apple_macOS_11.1, cis_ubuntu14-04 and cis_ubuntu16-04
- cis_sles12_linux and cis_sles_15_linux

## Repeated checks in format `count id`

2 13000
2 13001
2 13002
2 13003
2 13004
2 13005
2 13006
2 13007
2 13008
2 13009
2 13010
2 13011
2 13012
2 13013
2 13014
2 13015
2 13016
2 13017
2 13018
2 13019
2 13020
2 13021
2 13022
2 18064
2 18065
2 18066
2 18067
2 18068
2 18070
2 18071
2 18072
2 18073
2 18074
2 18075
2 18076
2 18077
2 18078
2 18079
2 18080
2 18081
2 18082
2 18083
2 18084
2 18085
2 18086
2 18087
2 18088
2 18089
2 18090
2 18091
2 18092
2 18093
2 18094
2 18095
2 18096
2 18097
2 18098
2 18099
2 18100
2 18101
2 18102
2 18103
2 18104
2 18105
2 18106
2 18107
2 18108
2 18109
2 18110
2 18111
2 18112
2 18113
2 18114
2 18115
2 18116
2 18117
2 18118
2 18119
2 18120
2 18121
2 18122
2 18123
2 18124
2 18125
2 18126
2 18127
2 18128
2 18129
2 18130
2 18131
2 18132
2 18133
2 18134
2 18135
2 18136
2 18137
2 18138
2 18139
2 18140
2 18141
2 18142
2 18143
2 18144
2 18145
2 18146
2 18147
2 18148
2 18149
2 18150
2 18151
2 18152
2 18153
2 18154
2 18155
2 18156
2 18157
2 18158
2 18159
2 18160
2 18161
2 18162
2 18163
2 18164
2 18165
2 18166
2 18167
2 18168
2 18169
2 18170
2 18171
2 18172
2 18173
2 18174
2 18175
2 18176
2 18177
2 18178
2 18179
2 18180
2 7500
2 7501
2 7502
2 7503
2 7504
2 7505
2 7506
2 7507
2 7508
2 7509
2 7510
2 7511
2 7512
2 7513
2 7514
2 7515
2 7516
2 7517
2 7518
2 7519
2 7520
2 7523
2 7524
2 7525
2 7526
2 7527
2 7528
2 7529
2 7530
2 7531
2 7532
2 7533
2 7534
2 7535
2 7536
2 7537
2 7538
2 7539
2 7540
2 7541
2 7542
2 7543
2 7544
2 7545
2 7546
2 7547
2 7548
2 7549
2 7550
2 7551
2 7552
2 7553
2 7554
2 7555
2 7556
2 7557
2 9000
2 9001
2 9002
2 9003
2 9004
2 9005
2 9006
2 9007
2 9008
2 9009
2 9010
2 9011
2 9012
2 9013
2 9014
2 9015
2 9016
2 9017
2 9018
2 9019
2 9020
2 9021
2 9022
2 9023
2 9024
2 9025
2 9026
2 9027
2 9028
2 9029
3 18000
3 18001
3 18002
3 18003
3 18004
3 18005
3 18006
3 18007
3 18008
3 18009
3 18010
3 18011
3 18012
3 18013
3 18014
3 18015
3 18016
3 18017
3 18018
3 18019
3 18020
3 18021
3 18022
3 18023
3 18024
3 18025
3 18026
3 18027
3 18028
3 18029
3 18030
3 18031
3 18032
3 18033
3 18034
3 18035
3 18036
3 18037
3 18038
3 18039
3 18040
3 18041
3 18042
3 18043
3 18044
3 18045
3 18046
3 18047
3 18048
3 18049
3 18050
3 18051
3 18052
3 18053
3 18054
3 18055
3 18056
3 18057
3 18058
3 18059
3 18060
3 18061
3 18062
3 18063
3 18069
3 7521

**Comment by 72nomada** [comment]
We will add this as part of the SCA rework.

**Comment by 72nomada** [comment]
current SCA IDS 

Top ID | CIS Benchmark|
-- | --
1000 | CIS Benchmark for Debian/Linux 7
1500 | CIS Benchmark for Debian/Linux 8
2000 | CIS Benchmark for Debian/Linux 9
2500 | CIS Benchmark for Debian/Linux 10
3000 | System audit for Unix based systems
3500 | CIS Benchmark for Red Hat Enterprise Linux 5
4000 | CIS Benchmark for Red Hat Enterprise Linux 6
4500 | CIS Benchmark for Red Hat Enterprise Linux 7
5000 | CIS Benchmark for Red Hat Enterprise Linux 8
5500 | CIS Benchmark for CentOS 6
6000 | CIS Benchmark for CentOS 7
6500 | CIS Benchmark for CentOS Linux 8
7000 | CIS SUSE Linux Enterprise 11 Benchmark
7500 | CIS SUSE Linux Enterprise 12 Benchmark
8000 | CIS Benchmark for Oracle Solaris 11
8500 | CIS Apple macOS 10.11 Benchmark"
9000 | CIS Apple macOS 10.12 Benchmark
9500 | CIS Apple macOS 10.13 Benchmark
10000 | CIS Apache HTTP Server 2.4 Benchmark
10500 | CIS Benchmark for Oracle MySQL Community Server 5.6
11000 | CIS Benchmark for Oracle MySQL Enterprise 5.6
11500 | CIS Microsoft SQL Server 2012
12000 | CIS Microsoft SQL Server 2014
12500 | CIS Microsoft SQL Server 2017
13000 | CIS Microsoft SQL Server 2016
13500 | CIS Microsoft SQL Server 2019
14000 | System audit for web-related vulnerabilities
14500 | Benchmark for Windows audit
15000 | CIS Benchmark for Windows 2012 R2
15500 | CIS Benchmark for Windows 10 Enterprise (Release 1803)
16000 | CIS Benchmark for Windows Server 2016
16500 | CIS Benchmark for Windows Server 2019 RTM
17000 | CIS Apple macOS 10.14 Benchmark
17500 | CIS Apple macOS 10.15 Benchmark
18000 | CIS Apple macOS 11.x Benchmark
18500 | CIS benchmark for Ubuntu Linux 18.04 LTS
19000 | CIS benchmark for Ubuntu Linux 20.04 LTS
19500 | CIS benchmark for Ubuntu Linux 14.04 LTS
20000 | CIS Benchmark for Amazon Linux 1
20500 | CIS Benchmark for Amazon Linux 2
21000 | CIS SUSE Linux Enterprise 15 Benchmark
21500 | CIS benchmark for Ubuntu Linux 16.04 LTS
22000 | CIS Benchmark for Microsoft IIS 10
22500 | CIS MongoDB 3.6 Benchmark
23000 | CIS Benchmark for NGINX version 1.14.0
23500 | CIS Benchmark for Oracle Solaris 11.4
24000 | CIS Benchmark for PostgreSQL 13
24500 | CIS Benchmark for Oracle Database 19c
25000 | CIS HP-UX 11i Benchmark
25500 | CIS HP-UX 11i Benchmark Using Bastille
26000 | CIS Microsoft Windows 11 Enterprise Benchmark
26500 | CIS Microsoft Windows 11 Enterprise Benchmark
27000 | CIS Microsoft Windows Server 2022
27500 | CIS Microsoft Windows Server 2022
28000 | CIS Red Hat Enterprise Linux 9
28500 | CIS Ubuntu Linux 22.04
29000 | CIS Apple macOS 12.0 Monterey
29500 | CIS Debian Linux 11
