### ISSUE TITLE
Typo in debian 10 SCA rules file wazuh-ruleset/sca/debian/cis_debian10.yml

### ISSUE THREAD

**Issue by architosch** [wazuh/wazuh#14351]
|Related Issues|
|---|
|#14702|

In line 201, it says 1.1.4, but it's 1.1.5, see attached screenshot from the CIS benchmark.

<img width="370" alt="Bildschirmfoto 2022-07-19 um 10 16 35" src="https://user-images.githubusercontent.com/109212070/179702013-abbddb62-d229-4a9c-b21f-30ae0fd39da3.png">

**Comment by IsExec** [comment]
Solved by https://github.com/wazuh/wazuh/pull/17922
