### ISSUE TITLE
Wazuh Agent modifying files?

### ISSUE THREAD

**Issue by jredford-e2open** [wazuh/wazuh#14418]
I am just wondering what would cause wazuh-agent.exe to try and modify files. Carbon Black has detected wazuh-agent.exe to be trying to modify files. The files are Carbon Black's canary files (bait files for ransomware detection). Is wazuh-agent.exe actually trying to modify them or is it one of the components to wazuh-agent.exe? 

I'm not sure which version of wazuh-agent.exe it is but the hash is e31b2de39afcb681a738b3a660c0a375ad653d833bd370d29eec2d7a60992269

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | Windows Server |

**Comment by gdiazlo** [comment]
You can check the agent version from the Wazuh UI in the agent's tab:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/2181918/180965758-5e3b9690-c5fc-4279-b6a0-2d055251a31b.png">

Or you can check the VERSION file in the installation directory:

```
PS C:\Program Files (x86)\ossec-agent> cat VERSION
v4.3.6
```

Also, we can check a number of other things to know which agent version was installed. You will find clues in event logs for example.

`Get-WinEvent -ProviderName msiinstaller | where id -eq 1033 | select timecreated,message | FL *`

<img width="915" alt="image" src="https://user-images.githubusercontent.com/2181918/180969249-2e7d5fd8-dc27-4074-9f82-2f449e66ff80.png">


The Wazuh agent does open multiple files depending on its configuration. To name a few, it will open:
* All DLLs it needs
* All files & folders related to each [SCA policy](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html)
* All files & folders from the default [FIM policy](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/how-it-works.html) 

and more.

We will be very interested to know what did Carbon Black report exactly, like the exact files and paths involved, and the access type (open, create, read, write, etc.). Could you share it with us?

**Comment by jredford-e2open** [comment]
Thank you for providing that info. Unfortunately I don't have direct access to the machine to find out the version. It's a recent version, I do know that. And Carbon Black basically stated that wazuh-agent.exe was trying to modify a file in c:/users/(one of its canary/bait files) on one particular machine. The wazuh-agent.exe is a legit, signed version of it. Carbon Black puts out canary files, or bait files to detect ransomware. When anything touches these files it thinks it's ransomware because the files are basically unused and have pretty much nothing on them.
