### ISSUE TITLE
Spike - C++ JSON schema validator library

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14411]
| Epic |
| --- |
| #14154 |

# Description
JSON format will be widely used in the content migration process, from configuration loading to third-party information validation.
Using a standardized way to make this possible is desirable, like JSON Schema.

# DoD
- [x] Investigate available C++ libraries that allow JSON schema validation, keeping in mind that nlohmann is our JSON library
- [ ] Pick candidates and evaluate their capabilities
- [ ] Create functional and performance test (CPU and memory) tests based on real cases like NVD content and schema

**Comment by jftuduri** [comment]
### Available C++ JSON schema validation libraries:

At the moment, the [JSON Schema website lists](https://json-schema.org/implementations.html#validator-c++) four C++ libraries for schema validation:

 - [f5-json-schema](https://github.com/KayEss/json-schema) draft-07 (Boost Software License 1.0)
 - [JSON schema validator for JSON for Modern C++](https://github.com/pboettch/json-schema-validator) draft-07 (MIT)
 - [Valijson](https://github.com/tristanpenman/valijson) draft-07 header-only library, works with many JSON parser implementations (BSD-2-Clause)
 - [jsoncons](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md) draft-07 Header-only library (Boost Software License 1.0)

**Comment by jftuduri** [comment]
## JSON schema validator for JSON for Modern C++ ([link](https://github.com/pboettch/json-schema-validator))

- JSON Schema Draft-v7
- Depends on Niels Lohmann's JSON-library.
-

**Comment by jftuduri** [comment]
## Valijson ([link](https://github.com/tristanpenman/valijson))

- JSON Schema Draft-v7
- Header only library.
- Supports several json parsers. We will be using nlohmann's.
-

**Comment by jftuduri** [comment]
### Heap profiling with Massif
#### Case
 - Schema: [NVD CPE Match Feed 1.0 Schema](https://csrc.nist.gov/schema/cpematch/feed/1.0/nvd_cpematch_feed_json_1.0.schema)
 - Input file data: NVD CPE Match Feed from 07/22/2022; 12:18:21 AM
 - Note: the uncompressed input file weights over **712MB**
 - Test consists in reading and parsing the schema, and reading, parsing and validating the input file.

#### JSON Schema Validator
![image](https://user-images.githubusercontent.com/7939712/180567920-b72d347f-da7c-45c2-a043-7f79065f4d29.png)


#### Valijson
![image](https://user-images.githubusercontent.com/7939712/180567991-3ed64192-62cb-4f19-9abb-152734c33968.png)

**Comment by jftuduri** [comment]
### Benchmark

```
2022-07-22T18:42:43-03:00
Running ./benchmark_test
Run on (8 X 3920.61 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 6144 KiB (x1)
Load Average: 1.81, 1.36, 1.53
-------------------------------------------------------------------------
Benchmark                               Time             CPU   Iterations
-------------------------------------------------------------------------
BM_VJ_LoadSchema_Custom            300927 ns       300893 ns         2274
BM_JSV_LoadSchema_Custom           283810 ns       283805 ns         2444
BM_VJ_ValidateJsonFile_Custom      140722 ns       140680 ns         4923
BM_JSV_ValidateJsonFile_Custom      78128 ns        78057 ns         8705
BM_VJ_ValidateJson_Custom           30984 ns        30984 ns        22786
BM_JSV_ValidateJson_Custom          15711 ns        15711 ns        42915
BM_VJ_LoadSchema_CPE               470464 ns       470327 ns         1382
BM_JSV_LoadSchema_CPE              455744 ns       455730 ns         1398
BM_VJ_ValidateJson_CPE               48.9 s          48.9 s             1
BM_JSV_ValidateJson_CPE              27.2 s          27.2 s             1
```

**Comment by jnasselle** [comment]
It seems to be that JSON schema validator for JSON for Modern C++ is the best choice.
IMHO this is the chosen one.
