### ISSUE TITLE
Investigate and test HAProxy load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14429]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of HAProxy as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by vicferpoy** [comment]
# Issue update

## Summary

Everything worked as expected without any remarkable issue. 🟢 

## Configuration

### Environment

- Wazuh cluster with 3 nodes (1 master and 2 workers)
- 6 Wazuh agents
- HAProxy load balancer

### HAProxy configuration

```
frontend wazuh_register
    bind :1515
    mode tcp
    default_backend wazuh_register

backend wazuh_register
    mode tcp
    balance leastconn
    server master_register 172.31.20.123:1515 check
    server worker1_register 172.31.17.201:1515 check
    server worker2_register 172.31.31.19:1515 check

frontend wazuh_cluster
    bind :1514
    mode tcp
    default_backend wazuh_cluster

backend wazuh_cluster
    mode tcp
    balance leastconn
    server  master_cluster 172.31.20.123:1514 check
    server worker1_cluster 172.31.17.201:1514 check
    server worker2_cluster 172.31.31.19:1514 check
```

## Manual test

![image](https://user-images.githubusercontent.com/37274979/181199459-21dd88a7-dd39-4db2-8537-dfa2de53d637.png)

1. HAProxy was configured to balance using the `least connections` algorithm.
2. Both Wazuh workers' services were stopped to force the agents connection to the master node.
3. Both Wazuh workers were enabled and the last 4 agents were forced to reconnect using the `PUT /agents/reconnect` API endpoint.
4. Agents were correctly balanced between workers 1 and 2.
5. Both Wazuh workers' services were stopped again and HAProxy balanced the agents back to the master node.

**Comment by gee456** [comment]
FYI, I tried this and it did not work,. HAProxy thought the wazuh ports were always down. Wazuh also generated a log storm of these events on the managers.

2024/03/14 14:11:12 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:13 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:13 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:14 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:14 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:15 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:15 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:16 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:16 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:17 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:17 wazuh-remoted: WARNING: Too big message size from socket [12].
2024/03/14 14:11:18 wazuh-remoted: WARNING: Unexpected message (hex): '48454144202f20485454502f312e300d0a0d0a'
2024/03/14 14:11:18 wazuh-remoted: WARNING: Too big message size from socket [12].

**Comment by saintcore** [comment]
For me the provided config worked out of the box like a charm tbh :)
