### ISSUE TITLE
Investigate and test NGINX load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14424]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of NGINX as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by AdriiiPRodri** [comment]
# Issue update
## Summary 🟢 
The NGINX load balancer has operated as expected using the "least connections" technique.

## Configuration
```
stream {
    upstream wazuh_cluster {
        least_conn;
        server IP_MASTER:1514;
        server IP_WORKER1:1514;
        server IP_WORKER2:1514;
    }

    upstream register {
        server IP_MASTER:1515;
        server IP_WORKER1:1515;
        server IP_WORKER2:1515;
    }

    server {
        listen 1514;
        proxy_pass wazuh_cluster;
    }

    server {
        listen 1515;
        proxy_pass register;
    }
}
```

## Manual test
To verify the proper functioning of the balancer and the least_conn technique we have followed the following steps:
1. Set up an environment an environment with 6 agents, 3 manager nodes (master and 2 workers) and the NGINX balancer.
2. All agents are connected to the balancer and this one to the manager nodes.
3. Stop the workers nodes to achieve a situation in which all the agents are connected to a single node:
```
[root@ip-172-31-20-123 /]# /var/ossec/bin/cluster_control -a
ID   NAME                           IP             STATUS  VERSION       NODE NAME    
000  ip-172-31-20-123.ec2.internal  127.0.0.1      active  Wazuh v4.4.0  master-node  
002  ip-172-31-92-163.ec2.internal  172.31.92.163  active  Wazuh v4.3.6  master-node  
003  ip-172-31-93-125.ec2.internal  172.31.93.125  active  Wazuh v4.3.6  master-node  
004  ip-172-31-85-9.ec2.internal    172.31.85.9    active  Wazuh v4.3.6  master-node  
005  ip-172-31-88-201.ec2.internal  172.31.88.201  active  Wazuh v4.3.6  master-node  
006  ip-172-31-87-7.ec2.internal    172.31.87.7    active  Wazuh v4.3.6  master-node  
007  ip-172-31-93-86.ec2.internal   172.31.93.86   active  Wazuh v4.3.6  master-node 
```

4. Send the reconnection request to the last 4 agents as the algorithm implemented in the cluster would do and check if the agents have been balanced correctly:
```
[root@ip-172-31-20-123 /]# curl -k -X PUT "https://localhost:55000/agents/reconnect?agents_list=004,005,006,007" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["004", "005", "006", "007"], "total_affected_items": 4, "total_failed_items": 0, "failed_items": []}, "message": "Force reconnect command was sent to all agents", "error": 0}

[root@ip-172-31-20-123 /]# /var/ossec/bin/cluster_control -a
ID   NAME                           IP             STATUS  VERSION       NODE NAME    
000  ip-172-31-20-123.ec2.internal  127.0.0.1      active  Wazuh v4.4.0  master-node  
002  ip-172-31-92-163.ec2.internal  172.31.92.163  active  Wazuh v4.3.6  master-node  
003  ip-172-31-93-125.ec2.internal  172.31.93.125  active  Wazuh v4.3.6  master-node  
004  ip-172-31-85-9.ec2.internal    172.31.85.9    active  Wazuh v4.3.6  worker1      
005  ip-172-31-88-201.ec2.internal  172.31.88.201  active  Wazuh v4.3.6  worker2      
006  ip-172-31-87-7.ec2.internal    172.31.87.7    active  Wazuh v4.3.6  worker1      
007  ip-172-31-93-86.ec2.internal   172.31.93.86   active  Wazuh v4.3.6  worker2
```

5. Finally, stop the worker nodes again to check that the agents are correctly redirected to the still active node, in this case the master node:
```
[root@ip-172-31-20-123 /]# /var/ossec/bin/cluster_control -a
ID   NAME                           IP             STATUS  VERSION       NODE NAME    
000  ip-172-31-20-123.ec2.internal  127.0.0.1      active  Wazuh v4.4.0  master-node  
002  ip-172-31-92-163.ec2.internal  172.31.92.163  active  Wazuh v4.3.6  master-node  
003  ip-172-31-93-125.ec2.internal  172.31.93.125  active  Wazuh v4.3.6  master-node  
004  ip-172-31-85-9.ec2.internal    172.31.85.9    active  Wazuh v4.3.6  master-node  
005  ip-172-31-88-201.ec2.internal  172.31.88.201  active  Wazuh v4.3.6  master-node  
006  ip-172-31-87-7.ec2.internal    172.31.87.7    active  Wazuh v4.3.6  master-node  
007  ip-172-31-93-86.ec2.internal   172.31.93.86   active  Wazuh v4.3.6  master-node
```

## Notes
The machines used for this test are Amazon Linux 2, on this system, for the NGINX "Stream" module to work, it is necessary to install it separately with the following command:
```
yum install nginx-mod-stream
```

**Comment by ThepoisonedApple** [comment]
Hello,
We are using nginx for load balancing since 2021.We have almost 2000 agent in this cluster and have 100m+ alert/day syslog in different cluster.Both using nginx.
We did not encounter any serious problems.
Our conf file.
```
worker_processes  10;
pid	/var/run/nginx.pid;
worker_rlimit_nofile 32768;

events {
  worker_connections  32768;
}

stream {

log_format  custom  '$remote_addr - $time_local - $status';

	access_log	/var/log/nginx/access.log custom;
	error_log	/var/log/nginx/error.log;

    upstream master {
        server wazuh-1:1515;
    }
    upstream mycluster {
    hash $remote_addr consistent;
	server wazuh-1:1514;
        server wazuh-2:1514;
    }
    server {
        listen 1515;
        proxy_pass master;
    }
    server {
        listen 1514;
        proxy_pass mycluster;
    }

    upstream syslog_udp
	{
		server wazuh-1:514;
		server wazuh-2:514;
	}
	
   upstream syslog_tcp
	{
		server wazuh-1:513;
	        server wazuh-2:513;
	}

	server
	{
#		proxy_responses 0;
#		proxy_bind $remote_addr transparent;
		listen 514 udp;
		proxy_pass syslog_udp;
		

	}

	server
	{
#		proxy_responses 0;
#		proxy_bind $remote_addr transparent;
		listen 513;
		proxy_pass syslog_tcp;
	}

}
```
Tips:
1-)
 Using " hash $remote_addr consistent;" is necessary for agents sent logs to same node.
2-) 
```		
proxy_responses 0;
proxy_bind $remote_addr transparent;
```
is necessary to wazuh correctly fill location data.otherwise will fill location data with nlb ip.
we disabled it because of a bug.When this lines set nginx sending all data to one node.

sys-info:
debian-10
nginx/1.20.1

**Comment by daod-arshad** [comment]
I am still experiencing the issue that udp events are being forwarded to only one wazuh-server. I tried adding and removing the transparent parameter in nginx but still no use. I have tested this with nginx 1.20 as well as 1.26 but none the less.
