### ISSUE TITLE
Investigate and test Azure load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14427]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of Azure LBs as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by AdriiiPRodri** [comment]
# Issue update

## Summary 🔴 

Just like AWS and GCP, Azure's TCP balancer does not allow the change of algorithm so it does not meet the requirements of the new development.

More information: https://docs.microsoft.com/en-us/azure/load-balancer/concepts
