### ISSUE TITLE
Investigate and test F5 load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14425]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of F5 as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by vicferpoy** [comment]
# Issue update
## Summary 🟡 

To test this load balancer, an AWS AMI was used. The load balancer was correctly configured and the `least connections` algorithm was present. However, instances net issues and limitations didn't allow to properly test the connection between agent-LB-manager.

There should not be any issues regarding this TCP balancing development on a fully usable and configurable F5 environment, but we cannot assure it for the moment.

## Configuration
![image](https://user-images.githubusercontent.com/37274979/181754735-2db039c0-7ea7-49b6-b975-2ddc1dab87e0.png)

![image](https://user-images.githubusercontent.com/37274979/181754750-565e2b15-d04b-40db-ad06-8f898f76fab8.png)
