### ISSUE TITLE
wazuh-execd left restart.sh as zombie

### ISSUE THREAD

**Issue by pandamasta** [wazuh/wazuh#14435]
Hello,

wazuh-agent v4.2.5 left zombie process, on Linux and Solaris

```
$ ps auxw | grep Z | grep restart
root      139104  0.0  0.0      0     0 ?        Z    Jul04   0:00 [restart.sh] <defunct>

$ pstree -p | grep 139104
           |-wazuh-execd(134408)-+-restart.sh(139104)
```

It's on ~500 nodes on my side

Let me know if you need more details

**Comment by FrancoRivero** [comment]
Hi @pandamasta 
thanks for using Wazuh!
Can you share with me more information about it?
I would like information about your configuration and what operation you are doing with `execd`.
If you consider that I need other information, please let me know.
Regards

**Comment by pandamasta** [comment]
Hi @FrancoRivero 

Sorry for my late, I didn't notice the update.

On machines where I restarted wazuh, no more zombie

Next week I'll restart wazuh on all my nodes.

I purpose to wait until I spot new case, if it rehappen

I use the usual configuration, not more. (I'll post it)

I let you know because it's a task on my side in my corporation 

Thanks
Regards

**Comment by FrancoRivero** [comment]
Hi @pandamasta,
how are you?
OK, no problem, I'll close this issue if you see this error again let me know and reopen the issue!
Thanks for your reply,
Regards
