### ISSUE TITLE
Whodata stops triggering alerts on Windows

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#14434]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | FIM | Agent | Packages/Sources | Windows Server 2012 R2, 2016 and 2019 |

# Description
It has been reported that FIM is not triggering any alerts on monitored directories using whodata after the agent runs for 40 minutes to 1 hour. 
After some investigation, it seems that the EventChannel events that FIM uses to collect the whodata information are not being triggered, causing the agent not to raise any related alert.
The events that FIM uses to trigger the alerts are:
- [4656 ](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4656)
- [4663](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4663)
- [4658](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4658)

# Causes of the problem
## Change in the audit policy
One of the reasons why these events are not triggered is because of a change in the monitored directory audit policy. At this moment, FIM cannot detect a change in the policy leading to possible missing alerts if some of the required permissions are removed. 
After checking this case, it seems that the policy wasn't changed at the time FIM stop reporting the alerts:

![image](https://user-images.githubusercontent.com/22987701/181234386-c0a31beb-dc50-4f97-9e47-6ccab8a15f4c.png)

##  EventChannel overflow
The next possibility is that there was an overflow on EventChannel due to the configuration and the number of events that have been triggered due to the configured directories. 
We are currently investigating this possibility.

# Configuration
```xml
  <!-- File integrity monitoring -->
  <syscheck>

    <disabled>no</disabled>


    <!-- Default files to be monitored. -->
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Program Files</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Program Files (x86)</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">D:\Program Files</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">D:\Program Files (x86)</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Windows</directories>
    <ignore>C:\Program Files (x86)\ossec-agent</ignore>
    <file_limit>
      <enabled>no</enabled>
    </file_limit>

    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```

# Steps to replicate the issue
At the moment, the problem cannot be replicated in a local environment.

**Comment by antoniomanuelfr** [comment]
In order to debug this problem, we have made a list of steps that must be followed in order to get more information:

## Check the active configuration of the affected agent. 
This can be done using the [API or the DevTools ](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_config). 
- Check monitored directories configuration.
- Check the `windows_audit_interval` option. 

## Once FIM is not receiving the events 
- Check the audit policy on the monitored directory.
- Check which events are triggered by EventChannel once FIM is not receiving them.

## Check events from 1100 to 1108:
- Event [1104](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-1104): Event overflow 
- event [1100](https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-1100): Eventlog service has been restarted. This is important, as FIM cannot subscribe to EventChannel if the service has been restarted.  Related issue: https://github.com/wazuh/wazuh/issues/8581
##  Check the Audit Policy Configuration:
- Local Group Policy Editor: Windows Settings -> Security Settings -> Advanced Audit Policy -> System Audit Policies -> Object access: `Audit File System` and `Audit Handle Manipulation` must be configured as: `Not configured` or `success`

**Comment by vikman90** [comment]
## Surrounding the cause of the problem

### Wazuh Agent startup

The agent performs the following steps on startup:

1. Sets up each monitored directory's auditing permissions.
2. Enables the host's notifications for the file system and handle manipulation audit events.
3. Subscribes to file system audit events at the Security event channel.

![2022-07-29 Whodata issue](https://user-images.githubusercontent.com/10536251/181746758-1717f27f-01f4-4cd3-848b-32ea45d46290.png)

### Whodata-based file analysis triggering

- The agent gets notified about changes in the filesystem, along with the user and process information.
- This makes the agent check the related file and deliver an event to the manager, which will produce an alert.

This diagram shows the event notification flow:
![2022-07-29 Whodata issue (1)](https://user-images.githubusercontent.com/10536251/181747341-3896549e-b90b-4113-a500-cb684d9f66fd.png)

### Conclusion

Since we have not found the necessary events to notify a change in the file system, we conclude that the cause of this problem is located **somewhere between the kernel file system and the Event log service**:

- The file system might not be notifying the audit subsystem because the directory's audit properties have changed.
- The auditing events are not arriving in the Event Log due to either a wrong host's audit configuration or some other cause, like event flooding.

### Next step

We need to explore the points around the event notification in order to figure out the cause of this issue.

**Comment by antoniomanuelfr** [comment]
# Update 1

After reviewing all the information collected and executing all the tests again, we have the following conclusions: 

## Active configuration:
There wasn't any wrong configuration: All the expected directories to be monitored were correct and the `windows_audit_interval` is set to the default option (60 second)

## Once FIM is not receiving the events
### Check the audit policy on the monitored directory.
After checking the policy, we saw no changes when FIM stopped receiving events.
### Check events from 1100 to 1108:
No events with these IDs were found.
## Check the Audit Policy Configuration
The policy configuration was set to `Not Configured` (default value)

# New Information
We saw that it seems that when Wazuh stops working, EventChannel starts triggering the expected events.

**Comment by antoniomanuelfr** [comment]
# Update 2

After debugging and looking through the following information, we have detected the root cause of the problem:
- Enabled local audit policies on the system when FIM is working and when FIM stops working.
- Review the security logs looking for the event [4719](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4719)

With this information, we have seen that there is another process that changes the `Handle Manipulation` and `File System` audit policy from `Success` to `No auditing`. This causes EventChannel to not trigger the needed events and FIM stops reporting whodata alerts. 
## Evidence
We captured the local policies using the following command: `auditpol /backup /file:"c:\backup-policies-working"`. 
After comparing both files when FIM works and when it's not, we can see that both policies were changed:

```diff
--- backup-policies-not-working	2022-08-05 19:40:40.000000000 +0200
+++ backup-policies-working	2022-08-05 19:40:42.000000000 +0200
@@ -15,7 +15,7 @@
 some-user,System,Account Lockout,{0CCE9217-69AE-11D9-BED3-505054503030},Failure,,2
 some-user,System,Logoff,{0CCE9216-69AE-11D9-BED3-505054503030},Success and Failure,,3
 some-user,System,Logon,{0CCE9215-69AE-11D9-BED3-505054503030},Success and Failure,,3
-some-user,System,Handle Manipulation,{0CCE9223-69AE-11D9-BED3-505054503030},No Auditing,,0
+some-user,System,Handle Manipulation,{0CCE9223-69AE-11D9-BED3-505054503030},Success,,1
 some-user,System,Central Policy Staging,{0CCE9246-69AE-11D9-BED3-505054503030},Success and Failure,,3
 some-user,System,Removable Storage,{0CCE9245-69AE-11D9-BED3-505054503030},Success and Failure,,3
 some-user,System,Detailed File Share,{0CCE9244-69AE-11D9-BED3-505054503030},No Auditing,,0
@@ -28,7 +28,7 @@
 some-user,System,SAM,{0CCE9220-69AE-11D9-BED3-505054503030},No Auditing,,0
 some-user,System,Kernel Object,{0CCE921F-69AE-11D9-BED3-505054503030},No Auditing,,0
 some-user,System,Registry,{0CCE921E-69AE-11D9-BED3-505054503030},No Auditing,,0
-some-user,System,File System,{0CCE921D-69AE-11D9-BED3-505054503030},No Auditing,,0
+some-user,System,File System,{0CCE921D-69AE-11D9-BED3-505054503030},Success,,1
 some-user,System,Other Privilege Use Events,{0CCE922A-69AE-11D9-BED3-505054503030},No Auditing,,0
 some-user,System,Non Sensitive Privilege Use,{0CCE9229-69AE-11D9-BED3-505054503030},No Auditing,,0
 some-user,System,Sensitive Privilege Use,{0CCE9228-69AE-11D9-BED3-505054503030},No Auditing,,0
```
And checking the `Security` logs we can see that EventChannel stopped reporting the needed events:
![image](https://user-images.githubusercontent.com/22987701/183374157-4bb4c92e-34dc-4490-bccc-96924680b2ba.png)

## Follow up
We need to identify which process/user is performing this change. 

Also, we could add a feature to Whodata in order to identify these changes in policies and change the monitoring to realtime.
FIM will need to:
- Enable the `Audit Policy Change` policy.
- Look for the event [4719](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4719)
- Check the `SubcategoryGuid` and check if the change is performed in `{0CCE9223-69AE-11D9-BED3-505054503030}` (System handle manipulation) or `{0CCE921D-69AE-11D9-BED3-505054503030}` (File System)
- Trigger an alert and change the monitoring to realtime

**Comment by chemamartinez** [comment]
Completed at https://github.com/wazuh/wazuh/pull/14763
