### ISSUE TITLE
Best practices for balancing Wazuh agents communication

### ISSUE THREAD

**Issue by mingo-devsec** [wazuh/wazuh#14442]
Based on Nginx open source project we need to improve Wazuh agents balance

**Current documentation**
https://documentation.wazuh.com/current/user-manual/configuring-cluster/advanced-settings.html#pointing-agents-to-the-cluster-with-a-load-balancer

**Suggested configuration**
```
stream {
    upstream cluster {
        hash $remote_addr consistent;
        server <WAZUH-MASTER-IP>:1514;
        server <WAZUH-WORKER1-IP>:1514;
        server <WAZUH-WORKER2-IP>:1514;
    }
    upstream master {
        server <WAZUH-MASTER-IP>:1515;
    }
    server {
        listen 1514;
        proxy_pass cluster;
    }
    server {
        listen 1515;
        proxy_pass master;
    }
}
```

**Current behavior**
After a cluster restart, agents will connect to the first available worker without ever redistributing again. This sometimes causes risk of resource exhaustion

Thanks in advance!

**Comment by O1ape** [comment]
This is already included in our documentation https://documentation.wazuh.com/current/user-manual/configuring-cluster/advanced-settings.html#load-balancer

**Comment by davidjiglesias** [comment]
This is already included in our documentation https://documentation.wazuh.com/current/user-manual/configuring-cluster/advanced-settings.html#load-balancer
