### ISSUE TITLE
Office365 module works for a random period of time

### ISSUE THREAD

**Issue by kmfreder1** [wazuh/wazuh#14455]
|Wazuh version|Component|OS|
|---|---|---|
| 4.3.2-4303-1 | Office365 Module |Ubuntu 20.04 & 18.04|

I have the Office365 module set up at two customer sites and have experienced the same on both.  I really like the new approach and the set of rules that Wazuh created were insightful. However, we ran into a problem shortly after implementation.

With the initial settings of interval at 1m and the curl max size at 1M, Office365 events flowed into Wazuh fine for 5 days and then completely stopped (on stopped 12 hours shy of 5 days).  

So, once I found the events had stopped flowing, I changed the interval to 10 min and the curl max size to 10M and restarted wazuh-manager.  Logs started flowing again.  This time the module stopped pulling logs after only a few hours.  Once it stops, it does not start back up on its own. 

Here is my current config:

```
  <office365>
    <enabled>yes</enabled>
    <interval>10m</interval>
    <curl_max_size>10M</curl_max_size>
    <only_future_events>yes</only_future_events>
    <api_auth>
        <tenant_id>{Redacted}</tenant_id>
        <client_id>{Redacted}</client_id>
        <client_secret>{Redacted}</client_secret>
    </api_auth>
    <subscriptions>
        <subscription>Audit.General</subscription>
        <subscription>Audit.AzureActiveDirectory</subscription>
        <subscription>Audit.Exchange</subscription>
        <subscription>Audit.SharePoint</subscription>
        <subscription>DLP.All</subscription>
    </subscriptions>
  </office365>
```

So we turned debug logging on in /var/ossec/etc/local_internal_options.conf with this:

```
wazuh_modules.debug=2
```
The logs did not show any errors.  We saw a successful pull and then there was nothing.  No logs saying it tried again after the interval, no logs saying it failed....nothing...

We found no signs of segfault in dmesg and nothing interesting in syslog.  All of the wazuh-manager components are also still running:

```
# /var/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
```
Here is a snippet of the log just before the blobs start to show up:
```
022/07/29 10:51:30 wazuh-modulesd[1814354] main.c:94 at main(): DEBUG: Created new thread for the 'office365' module.
2022/07/29 10:51:30 wazuh-modulesd:office365[1814354] wm_office365.c:123 at wm_office365_main(): INFO: Module Office365 started.
2022/07/29 10:51:30 wazuh-modulesd:office365[1814354] wm_office365.c:289 at wm_office365_execute_scan(): DEBUG: Scanning tenant: '{Redacted}'
```

As I say, after the last blob is pulled in, and the module apparently quietly stops, there is no other reference to it in /var/ossec/logs/ossec.log, nor in dmesg or /var/log/syslog.  This does not appear to be an Office 365 Tenant side issue.  There is no sign that it is trying and failing or being rejected by Office 365. 

If I restart the Wazuh Manager without changing any of the parameters, then the Office365 module starts back up but will fail again after a seemingly random interval of time. 

I am not the only one experiencing this.
  
Any help would be much appreciated.

**Comment by kmfreder1** [comment]
For now, I have pivoted back to the Office365 pull method mentioned in this Wazuh Blog article > https://wazuh.com/blog/monitor-office-365-with-wazuh/

I adapted the script wazuh provided in the above blog article with this sed command to change all references from office_365 to office365 so the Wazuh ruleset would work against the events pulled in via this method.  I confirmed these are a) being pulled properly and b) using "office365" in the field names as the module was doing and as the ruleset is looking for.  

```
sed -i 's/office_365/office365/g' /usr/local/bin/office_365.py
```

**Comment by vikman90** [comment]
@kmfreder1 this issue seems to be related to #13592, which was fixed by #13626 (v4.3.4).

According to our research, the Azure API was stopping responding to a request, causing the module to hang. Please try to upgrade to v4.3.4 and let us know if the problem persists.

Best regards.

**Comment by kmfreder1** [comment]
Thanks @vikman90.  I will give that a shot and report back my findings.

**Comment by kmfreder1** [comment]
I have updated to 4.3.6, pivoted back to the Office365 module and things seem to be now working as expected.  Three days on the one and 2 days on the other.  Looks like that curl timeout issue was indeed what we were running into, from all appearances.  Thanks again @vikman90!

**Comment by vikman90** [comment]
I'm glad to hear!
Best regards.
