### ISSUE TITLE
Investigate and test Imperva load balancer for agent's TCP balancing

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#14453]
As part of the development and implementation of a [mechanism to balance agents' TCP sessions in a clustered environment #13195](https://github.com/wazuh/wazuh/issues/13195) we need to test the behavior of the principal load balancers in the market, as well as the required configurations to ensure a proper behavior with the new functionality.

We need to test and validate the usage of Imperva as the load balancer to balance agent's TCP sessions in the current development. 

We know a primary pre-requisite for the current development is the availability of a least-connections algorithm for the external load balancer. We also need to test the different configurations and document them accordingly.

**Comment by AdriiiPRodri** [comment]
# Issue update

## Summary 🔴 

The load balancer provided by Imperva is based exclusively on layer 7, so it is not suitable for our use case. To interconnect the Wazuh cluster it is necessary that the load balancer is for layer 4.

More information: https://docs.imperva.com/bundle/cloud-application-security/page/introducing/load-balancing-failover.htm
