### ISSUE TITLE
Implement a feature to recycle not used agent IDs

### ISSUE THREAD

**Issue by j0serca** [wazuh/wazuh#14450]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.7 | auth/enrollment | Manager/Agent | Packages/Sources | Cloud |

## Description
Hi team,

We need to have a feature to recycle unused agent IDs. This happens when, if you remove old agents, newly enrolled agents will not take those unused IDs, but will continue with the higher one +1. Meaning you might end up having gaps between agent IDs 001, 002, 005, 011, 012...
It would be useful to have the option to recycle those skipped numbers so that they can be automatically used when future systems come into Wazuh.

Thank you!

### Suggestion

Add this feature to be enabled/disabled on the [force](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#force) option inside `<auth>` section.

**Comment by havidarou** [comment]
Duplicated with https://github.com/wazuh/wazuh/issues/10447
