### ISSUE TITLE
[Feature Request] Option to parse only logs from a specific data onwards for AWS Cloudwatch integration

### ISSUE THREAD

**Issue by DhirajVarma** [wazuh/wazuh#14460]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Latest | AWS module | All | All | All |

## Description
Hi team,

AWS-supported services allow the option `only_logs_after` to start to read the data from a specific date and hence, avoiding analyzing all the data contained in the bucket from the beginning.

Reference: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-only-logs-after

It would be useful if we can develop a similar function for the log streams of AWS Cloudwatch using the timestamp of the logs. Log streams can also contain data from time ago and this affects the performance of our integration.

Thanks!

**Comment by MiguelCasaresRobles** [comment]
This implementation is already done.

Please, disregard
