### ISSUE TITLE
Error when adding an agent to a group if the agent hasn't any group

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#1446]
## Bug report

**Wazuh version**
3.7.0-3701

Bug description
When an agent has the field group of the `global.db` empty, agent_groups fails trying to add the agent to a group.

> if group_id in agent_info["group"].split('-'):
> AttributeError: 'NoneType' object has no attribute 'split'

The problem is that group hasn't split cause group has nothing, so a condition is needed to skip the split when group is null.

**Comment by TJOSERAFAEL** [comment]
Hi @Skeptor ,

this bug is fixed in the branch https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement-hashing

Regards.
