### ISSUE TITLE
Expand information about API endpoints deprecation in the API reference or response headers

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#14480]
## Description

Right now, we are using the following to indicate that an API endpoint is going to be deprecated in a future Wazuh version:

1.- `deprecated` tag in the API spec (`api/api/spec/spec.yaml`):

https://github.com/wazuh/wazuh/blob/1912bc2f7f002ae4a422ee0da74aa584cb15efbb/api/api/spec/spec.yaml#L5888-L5934

https://github.com/wazuh/wazuh/blob/1912bc2f7f002ae4a422ee0da74aa584cb15efbb/api/api/spec/spec.yaml#L14786-L14825

API reference:

![image](https://user-images.githubusercontent.com/57481331/182833151-a6761984-606f-4189-aa1e-8bea0d157812.png)

![image](https://user-images.githubusercontent.com/57481331/182833294-e62324ab-7f78-4c97-9d13-f94c0eeb780f.png)

2.- `deprecate_endpoint` decorator (`api/api/util.py`):

https://github.com/wazuh/wazuh/blob/b8e3d0d948b3b0e5bac07227ab14252046039b8b/api/api/util.py#L327-L349

This decorator adds two new fields to the API response header:

Request (deprecated):

`GET /security/user/authenticate
`

Response header, `Deprecated: true` and `Link: ...` were added:

```
Content-Type: text/plain; charset=utf-8
Deprecated: true
Link: <https://documentation.wazuh.com//user-manual/api/reference.html#operation/api.controllers.security_controller.login_user>; rel="Deprecated"
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: none
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 398
Date: Thu, 04 Aug 2022 11:13:55 GMT
```

We should add more information about the deprecations. With the current information, a user does not know the version where the endpoint will be removed, for instance. Consider investigating possible HTTP response codes used for deprecated endpoints. Also, investigate possible deprecation warnings.

Note that the link added to the API response header is wrong (`https://documentation.wazuh.com//user-manual/api/reference.html#operation/api.controllers.security_controller.login_user`). The `WAZUH_VERSION` variable seems to be empty. Investigate about this possible error. I have used **Insomnia** to see the response header but they can also be seen with `curl -v <request>`

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
We should focus on investigating the expansion of the current deprecated tag to include more information about versions.

**Comment by vicferpoy** [comment]
# Issue update

After further investigation, everything we could add to inform a user that the used endpoint is being deprecated is already implemented.

Any other new feature would only add information after the complete deprecation is done. Thus, I suggest closing this issue.
