### ISSUE TITLE
Make distributed the requests to modify the ruleset

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14496]
| Epic issue |
|--|
| #14492 |

## Description

In order to apply changes to the ruleset (rules, decoders, CDB lists) as quickly as possible, it is necessary to make those requests `distributed_master` instead of `local_master`.

This change will cause the DAPI to modify files in the workers that until now were only modified by the Integrity task of the cluster. To avoid race conditions, it is important that when executing those requests, the change occurs first in the master node and then in the workers.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Finally, we implemented a different approach in https://github.com/wazuh/wazuh/pull/14534
