### ISSUE TITLE
Scanbuild analysis fails during winagent compilation

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14503]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 - 4.5 | Scanbuild analysis | Windows agent | Sources | - |

# Description

Currently `RTR test winagent`, CI step responsible for executing scan-build analysis during winagent compilation, is failing.

- Jenkins job for 4.4 branch https://ci.wazuh.info/job/Test_RTR/1427/
- Jenkins job for master nightly https://ci.wazuh.info/job/Test_RTR/1426/

**Comment by Dwordcito** [comment]
Rejected because it exists in wazuh-jenkins.
