### ISSUE TITLE
Check mtime in cluster files before overwriting them

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14505]
| Epic issue |
|--|
| #14492 |

## Description
Now, the decoders/rules/cdb lists files can be modified in the workers by the Integrity sync task and DAPI. In addition, these tasks are run in parallel by child processes within the cluster.

Possibly this leads to various race conditions that we will have to study and test in the coming days. One of them could be the following:
1. A rule is modified in the master node.
2. Worker receives zip with files to update coming from the master.
3. Worker unzip it and start processing those files.
4. A rule is modified in the cluster (including this worker) through an API distributed request. The worker did not finish processing unzipped files yet.
5. The rule file coming from master in step `2`. is processed and overwrites the file modified in step `4.`

The worker should check if each file's modification date is later than when the zip was received from the master.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Status update

Sometimes, after the changes in this epic, it might happen that the master compresses a file and asks the worker to replace its own even when the compressed version is older than the worker's (for example, if it took very long to be sent).

To avoid this, the master should send the timestamp when the compression occurred. With this, the worker should not replace any files whose modification date is newer than the compression date on the master.

To minimize the number of changes needed in the cluster, the timestamp that was already included in the zip name will be used:
https://github.com/wazuh/wazuh/blob/4bc2711206cd2d10dbb57f1b0355a3c3effbc5f0/framework/wazuh/core/cluster/cluster.py#L315

This is now the output for this use case:
```
2022/08/08 12:50:03 INFO: [Worker worker1] [Integrity sync] Starting.
2022/08/08 12:50:03 INFO: [Worker worker1] [Integrity sync] Files to create: 0 | Files to update: 1 | Files to delete: 0 | Files to send: 0
2022/08/08 12:50:14 WARNING: [Worker worker1] [Integrity sync] The compression date of this master's file is older than its modification date on the current node, so it will not be replaced: /var/ossec/etc/rules/local_rules.xml
2022/08/08 12:50:28 INFO: [Worker worker1] [Integrity sync] Finished in 25.375s.
```

**Comment by davidjiglesias** [comment]
Finally, we implemented a different approach in https://github.com/wazuh/wazuh/issues/14534
