### ISSUE TITLE
Wazuh indexer upgrade to Opensearch 2.1

### ISSUE THREAD

**Issue by alejandroorg** [wazuh/wazuh#14506]
Hello Team,

In the current version of Wazuh Indexer, we don't have some predefined roles of version 2.1 of Open search, for instance, `opensearch_dashboards_read_only` which allows us to access our Dashboards without access to Discover of Kibana, this is useful to have different Dashboards for different clients. 
You can check here the official documentation of Open search that have these predefined roles I'm talking about:
[https://opensearch.org/docs/latest/security-plugin/access-control/users-roles/](url)

**Comment by MiguelCasaresRobles** [comment]
Closed to avoid duplicates: https://github.com/wazuh/wazuh-packages/issues/1723
