### ISSUE TITLE
Linking cumulative patches due to lack of information from the Catalog

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#14523]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5 | Vulnerability Detector | Manager | Packages/Sources | Windows Server 2019 |

## Description

After investigation of issue #14134, we have been able to confirm that the problem mentioned in the [description](https://github.com/wazuh/wazuh/issues/14134#issue-1294436748) is a lack of information from the Catalog, where new patches are not related to patches that are too old (and not even available in the Catalog).

In this way, we can observe several examples that by means of an intermediate cumulative patch (which replaces the old one and is replaced by the new one), we can relate the patches to avoid that vulnerabilities that are mitigated by old patches, are not reported if the new cumulative patches are contained in the system [`A` -> `B` -> `C` -> `D`...].

Examples:

- [[KB4464330](https://support.microsoft.com/en-us/topic/october-9-2018-kb4464330-os-build-17763-55-4c374837-5de0-2ccf-9226-43b293d360f5) -> [KB5011503](https://support.microsoft.com/en-au/topic/march-8-2022-kb5011503-os-build-17763-2686-ccb25c67-8994-41c9-bff2-4903f9a4721d) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5011503)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
- [[KB4464330](https://support.microsoft.com/en-us/topic/october-9-2018-kb4464330-os-build-17763-55-4c374837-5de0-2ccf-9226-43b293d360f5) -> [KB5004947](https://support.microsoft.com/en-us/topic/july-6-2021-kb5004947-os-build-17763-2029-out-of-band-71994811-ff08-4abe-8986-8bd3a4201c5d) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5004947)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
- [[KB4489899](https://support.microsoft.com/en-us/topic/march-12-2019-kb4489899-os-build-17763-379-2a91a5c5-f351-f181-5501-510308a4030f) -> [KB5012647](https://support.microsoft.com/en-au/topic/april-12-2022-kb5012647-os-build-17763-2803-9a10c5c9-e65f-4ae1-a9c4-2db9a8eca4fc) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5012647)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]
- [[KB4512578](https://support.microsoft.com/en-us/topic/september-10-2019-kb4512578-os-build-17763-737-695c1350-93dc-40dc-72c3-5af9743c6340) -> [KB5010351](https://support.microsoft.com/en-us/topic/february-8-2022-kb5010351-os-build-17763-2565-f895d43b-d855-4f6e-b0cc-52c079ae9056) ([Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB5010351)) -> [KB5014692](https://support.microsoft.com/en-gb/topic/june-14-2022-kb5014692-os-build-17763-3046-62fe56c1-a8c0-40e8-a901-677ab9538bf8)]

Given this information, the vulnerabilities reported by the patch list in the research [issue description](https://github.com/wazuh/wazuh/issues/14134#issue-1294436748) (for a _Windows Server 2019_ OS), should be mitigated after implementing the following fix:

- In the script used for the generation of the MSU, at the time that the patches have the supersedence list, it is intended from a patch (`A`), get all its supersedence list and patch by patch (`B`), check in turn its supersedence list, so that by applying a difference between the list of `B` and the list of `A`, only new patches (`C`) that are not found in `A` will appear. In this way, they will be added to the end of `A`'s supersedence list (or in a queue), so that the latter will also be checked for any even newer patches (`D`, `E`, `F`...) that are also supersedence of the old one.

```py
while queue:
  patchCnotInA = supersedenceB.difference(supersedenceA)
  for patchC in patchCnotInA:
    supersedenceA.add(patchC)
    queue.add(patchC)
  queue.pop()
```

**Comment by chemamartinez** [comment]
A new MSU with the fix has been already published. It is available at [https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz](https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.json.gz).

**Comment by jareddewitt** [comment]
Can confirm.  After the MSU was published, the supersedence is working correctly and no false positives are detected.
