### ISSUE TITLE
Analyze and test how much memory EPS limitation occupies

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#14527]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Analysisd | Manager | Sources | Linux |

## Goal

Find out how much memory the new EPS limitation might take.

# Tasks

1. Explain with diagrams how much the peak(stressed) and post-peak consumption would be left in memory in standby.
2. Compare the memory consumption with and without the proposed changes.

> Help yourself with tools like `massif`.

## Components that take a variable amount of memory

- Limits structure.
- Limits semaphore.
- Limits configuration.

## Test conditions

- Several agents have to be connected to a manager generating events.
- Simulate events over the limit and queues not full (start queuing).
- Simulate events over the limit and queues full (start discarding).
- After the stressing stage, leave the manager idle for 10 minutes (at less).

**Comment by cborla** [comment]
# Memory analysis 1

## branch deployed
[dev-cloud-limits](https://github.com/wazuh/wazuh/tree/dev-cloud-limits)

## Manager ossec.conf
EPS Limits enbaled.

```xml
  <global>

    <limits>
      <eps>
        <maximum>10</maximum>
        <timeframe>10</timeframe>
      </eps>
    </limits>

  </global>
```

## Agent ossec.conf

# ossec.conf

```xml
  <localfile>
    <location>C:\Users\asus\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
# Number of events sent
A group of 1.000 events as fast as possible.

# Example log used to decode

```shellsession
2022/03/22 20:20:54 active-response/bin/route-null.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-03-22T20:20:54.827-0300","rule":{"level":5,"description":"sshd: authentication failed from IP 1.1.1.1.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd","authentication_failed"],"pci_dss":["10.2.4","10.2.5"]},"agent":{"id":"001","name":"DESKTOP-U8OHD3A","ip":"192.168.100.72"},"manager":{"name":"chb-VBox"},"id":"1647991254.4959","full_log":"Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2","predecoder":{"program_name":"sshd","timestamp":"Dec 10 01:02:02","hostname":"host"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"1.1.1.1","srcport":"1066","dstuser":"root"},"location":"\\Users\\asus\\test.txt"},"program":"active-response/bin/route-null.exe"}}
```

## Massif graph
![image](https://user-images.githubusercontent.com/41765669/183788619-279275f1-2920-4323-b6fe-177bd55ecc93.png)

## Conclusion
Analysisd memory increased until touch aprox 33 Mb limit. Events where proccessed in blocks of 100 event every 10 seconds,

**Comment by cborla** [comment]
# Memory analysis 2
The goal of this test is take a clear view of how the memory increase when EPS limit is disabled in the manager.

## Manager 

### branch deployed
[dev-cloud-limits](https://github.com/wazuh/wazuh/tree/dev-cloud-limits)

### EPS Limits configuration
ossec.conf
```xml
  <global>

    <limits>
      <eps>
        <maximum>0</maximum>
        <timeframe>10</timeframe>
      </eps>
    </limits>

  </global>
```

## Agent 
For this analysis test where used a Windows Agent to ingest events to Wazuh Manager.

### Agent configuration
ossec.conf
```xml
  <localfile>
    <location>C:\Users\user\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
### Number of events sent
A group of 1.000 events as fast as possible.

### Example log used to decode

```shellsession
2022/03/22 20:20:54 active-response/bin/route-null.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-03-22T20:20:54.827-0300","rule":{"level":5,"description":"sshd: authentication failed from IP 1.1.1.1.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd","authentication_failed"],"pci_dss":["10.2.4","10.2.5"]},"agent":{"id":"001","name":"DESKTOP","ip":"192.168.100.26"},"manager":{"name":"VBox"},"id":"1647991254.4959","full_log":"Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2","predecoder":{"program_name":"sshd","timestamp":"Dec 10 01:02:02","hostname":"host"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"1.1.1.1","srcport":"1066","dstuser":"root"},"location":"\\Users\\asus\\test.txt"},"program":"active-response/bin/route-null.exe"}}
```

## Result

### Memory graph (Massif tool)
![image](https://user-images.githubusercontent.com/41765669/183891868-f190355e-0fc9-4c33-88e2-3e004663a557.png)

### Conclusion
The memory heap increases until touch a 41 Mb peak, events were processed in a lapsus of 6 seconds, as fast as possible, after completed the decoding it staying stable around 38 Mb.

**Comment by cborla** [comment]
# Memory analysis 3, EPS enabled, 50.000 events
The goal of this test is take a clear view of how the memory increase when EPS limit is enabled in the manager.

## Manager 

### branch deployed
[dev-cloud-limits](https://github.com/wazuh/wazuh/tree/dev-cloud-limits)

### EPS Limits configuration
ossec.conf
```xml
  <global>

    <limits>
      <eps>
        <maximum>100</maximum>
        <timeframe>10</timeframe>
      </eps>
    </limits>

  </global>
```

## Agent 
For this analysis test where used a Windows Agent to ingest events to Wazuh Manager.

### Agent configuration
ossec.conf
```xml
  <localfile>
    <location>C:\Users\user\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
### Number of events sent
A group of 50.000 events where added to C:\Users\user\test.txt file. 

### Example log used to decode

```shellsession
2022/03/22 20:20:54 active-response/bin/route-null.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-03-22T20:20:54.827-0300","rule":{"level":5,"description":"sshd: authentication failed from IP 1.1.1.1.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd","authentication_failed"],"pci_dss":["10.2.4","10.2.5"]},"agent":{"id":"001","name":"DESKTOP","ip":"192.168.100.26"},"manager":{"name":"VBox"},"id":"1647991254.4959","full_log":"Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2","predecoder":{"program_name":"sshd","timestamp":"Dec 10 01:02:02","hostname":"host"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"1.1.1.1","srcport":"1066","dstuser":"root"},"location":"\\Users\\asus\\test.txt"},"program":"active-response/bin/route-null.exe"}}
```

## Result

### Memory graph (Massif tool)
![image](https://user-images.githubusercontent.com/41765669/184008706-094638e0-856a-49b7-99b7-faa0e177f526.png)

### Conclusion
The memory heap increases until arrives approx to 87 Mb limit. Events were processed according to EPS limitation, in bunch of 1000 events every 10 seconds, after completed the decoding it staying stable around 85 Mb.

**Comment by cborla** [comment]
# Memory analysis 4, EPS disabled, 50.000 events
The goal of this test is take a clear view of how the memory increase when EPS limit is disabled in the manager.

## Manager 

### branch deployed
[dev-cloud-limits](https://github.com/wazuh/wazuh/tree/dev-cloud-limits)

### EPS Limits configuration
ossec.conf
```xml
  <global>

    <limits>
      <eps>
        <maximum>0</maximum>
        <timeframe>10</timeframe>
      </eps>
    </limits>

  </global>
```

## Agent 
For this analysis test where used a Windows Agent to ingest events to Wazuh Manager.

### Agent configuration
ossec.conf
```xml
  <localfile>
    <location>C:\Users\user\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
### Number of events sent
A group of 50.000 events where added to C:\Users\user\test.txt file. 

### Example log used to decode

```shellsession
2022/03/22 20:20:54 active-response/bin/route-null.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-03-22T20:20:54.827-0300","rule":{"level":5,"description":"sshd: authentication failed from IP 1.1.1.1.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd","authentication_failed"],"pci_dss":["10.2.4","10.2.5"]},"agent":{"id":"001","name":"DESKTOP","ip":"192.168.100.26"},"manager":{"name":"VBox"},"id":"1647991254.4959","full_log":"Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2","predecoder":{"program_name":"sshd","timestamp":"Dec 10 01:02:02","hostname":"host"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"1.1.1.1","srcport":"1066","dstuser":"root"},"location":"\\Users\\asus\\test.txt"},"program":"active-response/bin/route-null.exe"}}
```

## Result

### Memory graph (Massif tool)
![image](https://user-images.githubusercontent.com/41765669/184013419-b37d8a5c-e7d3-4901-a9c4-3752dd807b44.png)

### Conclusion
The memory heap increases until touch a 88.4 Mb peak, after completed the decoding it staying stable around 85 Mb.

**Comment by cborla** [comment]
# Memory analysis 5, No EPS supported, 50.000 events
The goal of this test is take a clear view of how the memory increase manager vesion that not include EPS configuration.

## Manager 

### branch deployed
[4.3](https://github.com/wazuh/wazuh/tree/4.3)

## Agent 
For this analysis test where used a Windows Agent to ingest events to Wazuh Manager.

### Agent configuration
ossec.conf
```xml
  <localfile>
    <location>C:\Users\user\test.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```
### Number of events sent
A group of 50.000 events where added to C:\Users\user\test.txt file. 

### Example log used to decode

```shellsession
2022/03/22 20:20:54 active-response/bin/route-null.exe: {"version":1,"origin":{"name":"node01","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":[],"alert":{"timestamp":"2022-03-22T20:20:54.827-0300","rule":{"level":5,"description":"sshd: authentication failed from IP 1.1.1.1.","id":"100001","firedtimes":1,"mail":false,"groups":["local","syslog","sshd","authentication_failed"],"pci_dss":["10.2.4","10.2.5"]},"agent":{"id":"001","name":"DESKTOP","ip":"192.168.100.26"},"manager":{"name":"VBox"},"id":"1647991254.4959","full_log":"Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2","predecoder":{"program_name":"sshd","timestamp":"Dec 10 01:02:02","hostname":"host"},"decoder":{"parent":"sshd","name":"sshd"},"data":{"srcip":"1.1.1.1","srcport":"1066","dstuser":"root"},"location":"\\Users\\asus\\test.txt"},"program":"active-response/bin/route-null.exe"}}
```

## Result

### Memory graph (Massif tool)
![image](https://user-images.githubusercontent.com/41765669/184021416-73881915-7c45-4ba1-a893-f7980d742f0c.png)

### Conclusion
The memory heap increases until touch a 89 Mb peak, after completed the decoding it staying stable around 89 Mb.

**Comment by cborla** [comment]
# Conclusion
According to memory test results, it's not possible to identify a real difference of memory consumption between test that had EPS functionality enable, and test that had the functionality disabled. Also It's not possible identify a real difference between version 4.3 and EPS version with the functionality disabled.
The real difference when EPS functionality is enabled, is how much time it takes to process or decode the events.
