### ISSUE TITLE
Review and improve the way the cloud modules send their output to the ossec.log

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#14535]
| Affected integration |
|---|
| AWS, GCloud, Azure and DockerListener|

## Description

We should review and update the way we are capturing the output of our cloud modules (Azure, AWS y GCP) as well as the Docker-Listener module.

To better understand why this is necessary, first it is important to know how these modules are implemented. They are made of two different component:

- The core part, written in C, which launches the modules, catches the output and prints it to the ossec.log.
- The module itself, written in python, which executes the integration and generates some output to be shown in the stdout.

The issue here is that the way the output is written and sent to the ossec.log is not consistent between modules. In addition to that, the output of the different modules will be ignored, even if there are warning or error messages, if the debug mode is not enabled, which is disabled by default.

Here is a detailed explanation on how every module works currently:

### AWS

The python module runs and its output, which is written using `print` statements, is caught. However, for the output to be dumped to the ossec.log at least one of the following conditions must be met:

- If there is an internal error in the C part the output will be written to ossec.log if debug mode is 1 or higher.
- If the execution ends with an error code `1` the output will be written to ossec.log if the `Unknown error` string was present.
- If the execution ends with an error code `2` the output will be written to ossec.log if the `aws.py: error:` string was present.
- If the execution ends with an error code `3` or higher the output will be written to ossec.log as a WARNING, regardless of if it was an ERROR.
- If the execution ends successfully with an return value `0` or fails and returns a negative value the output will be written to the ossec.log only if debug mode is set to `2`.

### GCP

The python module runs and its output, which is written using `logging` statements, is caught. However, for the output to be dumped to the ossec.log at least one of the following conditions must be met:

- If debug level is 0 only CRITICAL, ERROR and WARNING messages will be written
- If debug level is 1 it will show INFO messages in addition to the previously listed.
- If debug level is 2 it will show DEBUG messages in addition to the previously listed.

This is done by looking for the `WARNING`, `ERROR`, `INFO` strings present in the output. If not present, the output is skipped.

### Azure

The azure module uses logging in a similar way to how the GCP was implemented. However, the C implementation is not expecting output from this module and it is not processing it, hence nothing will be written into the ossec.log at all. This is because the older implementation wrote its output directly to a custom file and now it is set to send it to the stdout but the core part must be updated to expect and catch this output.

### Docker Listener

There is output written using `print` statements that will be shown only when running the module manually. The module sent his output to the analysis engine in the form of events.

## Proposed solution

We do not want to write directly on the `ossec.log`, as this task is the responsibility of modulesd, but we should keep the logic of determining when a message should be shown and when not depending on the debug level in the modules part. This logic currently already exists. The solution would be to just update the C part to just capture the output it receives as it is, without filtering it at all, and write it to the ossec.log.

This solution involves updating the four modules as well as the core part and their unit testing.

## Related Issues

- https://github.com/wazuh/wazuh/issues/16619
- https://github.com/wazuh/wazuh/issues/16717
- https://github.com/wazuh/wazuh/issues/16737
- https://github.com/wazuh/wazuh/issues/16738
- https://github.com/wazuh/wazuh/issues/16739
- https://github.com/wazuh/wazuh/issues/18906
- https://github.com/wazuh/wazuh/issues/17049
- https://github.com/wazuh/wazuh/issues/16314
- https://github.com/wazuh/wazuh/issues/23843
- https://github.com/wazuh/wazuh/issues/23841

### Branch

- https://github.com/wazuh/wazuh/tree/16717-improve-cloud-modules-logging

**Comment by EduLeon12** [comment]
## Issue Update.

After reviewing with the team an epic based on this issue will be created.

Next Step:

- [ ] Review and analyze the behavior of the [Logging](https://docs.python.org/3/howto/logging.html#logging-basic-tutorial) module to test possible integration with the current module and see how the module reacts to different levels of logging while keeping the output through stdout.

**Comment by GGP1** [comment]
## Update

Rebased the epic branch to 4.9.0 and opened the pull request.

**Comment by GGP1** [comment]
## Update

Rebased the epic branch to 4.9.0, resolved conflicts and opened the pull request.

**Comment by GGP1** [comment]
## Update

Rebased the epic branch to 4.9.0, resolved conflicts and opened the pull request.

> The changes to the AWS module are missing, I'm leaving the issue in progess until we decide how to proceed.

**Comment by GGP1** [comment]
## Update

Included the AWS logging refactor made in the branch [16737-refactor-aws-logs/](https://github.com/wazuh/wazuh/commits/16737-refactor-aws-logs/) to the epic branch.

**Comment by GGP1** [comment]
## Update

Rebased the epic branch to 4.9.0 after the changes in #16314, solved multiple conflicts and made some modifications to the said issue to accomodate with the new logging mechanism.

**Comment by GGP1** [comment]
## Update

Created the issues #23841 and #23843 to introduce some enhancements to the logging messages and to fix the AWS integration test cases that were affected by the changes in the logs formatting. Moving the issue to blocked until they are ready.

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, and the current priorities, the team's efforts for improvements will be directed to the mentioned version, and for the `4.x `versions we will only focus on fixing relevant impact bugs.
