### ISSUE TITLE
Some Microsoft updates are not being collected by the MSU

### ISSUE THREAD

**Issue by mingo-devsec** [wazuh/wazuh#14538]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | Vulnerability Detector | Manager| Packages/Sources | Windows Server 2019|

## Description
Research on the relation between cumulative Windows updates
Vulnerability detected [KB4471332](https://support.microsoft.com/en-us/topic/december-11-2018-kb4471332-os-build-17763-194-033f5756-5e3b-314f-a2e8-531d6fc21325)
Patched by [KB5003711](https://support.microsoft.com/en-us/topic/kb5003711-servicing-stack-update-for-windows-10-version-1809-june-8-2021-cc836592-f55c-4da9-820b-e4d3c5c5c1d1)

![b1e76427-6f9b-4370-93a1-f126a13b733f](https://user-images.githubusercontent.com/74078426/184038781-406c38af-3a28-485b-9e78-2e807454f98e.png)

```
select * from MSU_SUPERSEDENCE where patch = 4471332;
select * from MSU_SUPERSEDENCE where patch = 4471332 AND super = 5003711;
```

We need to fix it since it is generating false positives.

Thanks!!

**Comment by chemamartinez** [comment]
Hi @mingo-devsec,

This seems duplicated from https://github.com/wazuh/wazuh/issues/14134, which is currently being fixed at https://github.com/wazuh/wazuh/issues/14523.

Since this reports a new case with different patches, I am adding this issue to the EPIC so we can verify it is solved when implemented the proposed fix at https://github.com/wazuh/wazuh/issues/14523.

Thanks!

**Comment by mingo-devsec** [comment]
Hi @chemamartinez, 
I need to correct this.

Based on [this](https://support.microsoft.com/en-us/topic/december-11-2018-kb4471332-os-build-17763-194-033f5756-5e3b-314f-a2e8-531d6fc21325) Microsoft support update, I assumed that KB4471332 is patched by KB4470788 instead of KB5003711. Is that correct?
```
sqlite> select * from MSU_SUPERSEDENCE where patch = 4471332 AND super = 4470788;
```
Thanks in advance!

**Comment by chemamartinez** [comment]
Hi @mingo-devsec and team,

After further investigation, we have found that some patches are not appearing in the MSU feed as expected. For example, KB4470788 which is mentioned in this issue.

The Microsoft Catalog Update contains information about this patch, as well as its supersedences.
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=fe6bd8c2-3752-4c8b-ab3e-1a7ed08767ba#PackageDetails

However, the current MSU doesn't gather that information:
```
# cat msu-updates.json | grep KB4470788
#
```

When generating the MSU, the debug logs report that the patch is being processed:
```
Getting the Microsoft Catalog information for KB4470788.
...
Expanding the parent patches of KB4470788.
...
KB4470788 is replaced by {'KB4558997', 'KB4504369', 'KB5005625', 'KB4549947', 'KB4587735', 'KB5003243', 'KB5005568', 'KB5000859', 'KB5006672', 'KB4570332', 'KB4601393', 'KB4577667', 'KB5001404', 'KB4566424', 'KB4598480', 'KB4499728', 'KB4562562', 'KB5006744', 'KB5005102', 'KB5003711', 'KB5005112', 'KB4523204', 'KB5004424', 'KB4539571', 'KB5001407'}
KB4470788 replaces {'KB4465664', 'KB4465477'}
```

Same has been observed for patches KB4465477 and KB5003711.

**Comment by chemamartinez** [comment]
Merged https://github.com/wazuh/wazuh-tools/pull/195. New patches will be available in the official MSU next time it is updated.

Thanks for your feedback @mingo-devsec!
