### ISSUE TITLE
AWS S3 Wodle is skipping long Cloudtrail logs

### ISSUE THREAD

**Issue by ArielIvanOjeda** [wazuh/wazuh#14550]
|Wazuh version|Component|
|---|---|
| 4.2.7-rev 40222 | Wazuh Server |

## Description
When working with the AWS S3 Wodle for Cloudtrail logs I got these errors:

```
“ERROR: Message too long to send to Wazuh.  Skipping message...
DEBUG: +++ ERROR: Message longer than buffer socket for Wazuh.  Consider increasing rmem_max  Skipping message...”
```

There is an issue for this https://github.com/wazuh/wazuh/issues/7048

After doing some research I found some possible alternatives for the short term as a workaround:

- Trimming the information generated by the AWS S3 Wodle
- Splitting the original log in several logs
- Extending the limit beyond 64KB. [#411](https://github.com/wazuh/wazuh/pull/411)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
We have decided not to increase the limit of 64kb per event for now.

**Comment by davidjiglesias** [comment]
We have decided to analyze and approach each case individually, instead of increasing analysisd limit again or discarding all messages without further notice.


I close this issue as we have not been able to receive the log or hints about the issue.
