### ISSUE TITLE
Wazuh - Kibana App Installation for Kibana version 5.4.2

### ISSUE THREAD

**Issue by warunac** [wazuh/wazuh#146]
I installed wazuhapp-2.0_5.4.2 with Kibana 5.4.2 using blow command 
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.4.2.zip
refer https://github.com/wazuh/wazuh-kibana-app/tree/2.0 

When I loading Wasuh app on Kibana there is error like below 

Saved "field" parameter is now invalid. Please select a new field.

When I click on Agent error 
Agents - Preview: Unexpected error. Please, report this error.

**Comment by malbarral** [comment]
Hello warunac,

When you install and uninstall the plugin, it is recommended to remove the "/usr/share/kibana/optimize/bundles" with the command `rm -rf /usr/share/kibana/optimize/bundles`.

And after the installation restart the Kibana service. Let me know if it works.

Best regards.

**Comment by warunac** [comment]
Hi @malbarral 

Thank you for the reply.
Now I can't see previous error when I click Wasuh on Kibana

New error is **Visualize: Zero or negative time interval not supported**

Thank you.

**Comment by malbarral** [comment]
Hi @warunac 

Have you tried to change the time interval by clicking here?
![image](https://user-images.githubusercontent.com/8999208/27625549-4892b4d2-5be5-11e7-9066-5caf7274d8a6.png)

Best regards.

**Comment by warunac** [comment]
Hi @malbarral,

Yes I tried 
![today](https://user-images.githubusercontent.com/27261192/27714529-c6e5499a-5d74-11e7-95c5-5876fb446c66.JPG)

**Comment by warunac** [comment]
I updated Kibana 5.5  and wazuhapp-2.0_5.5.0 
but I can see Visualize: Zero or negative time interval not supported error remaining and  change the time interval  not help to resolve this issue 

`Error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Zero or negative time interval not supported"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"wazuh-alerts-2017.06.28","node":"moXT0Yc1QHekqshS4UbdbQ","reason":{"type":"illegal_argument_exception","reason":"Zero or negative time interval not supported"}}]},"status":400}
    at https://10.3.65.119/bundles/wazuh.bundle.js?v=15382:125:10944
    at Function.Promise.try (https://10.3.65.119/bundles/commons.bundle.js?v=15382:90:27122)
    at https://10.3.65.119/bundles/commons.bundle.js?v=15382:90:26492
    at Array.map (native)
    at Function.Promise.map (https://10.3.65.119/bundles/commons.bundle.js?v=15382:90:26447)
    at callResponseHandlers (https://10.3.65.119/bundles/wazuh.bundle.js?v=15382:125:10560)
    at https://10.3.65.119/bundles/wazuh.bundle.js?v=15382:124:31292
    at processQueue (https://10.3.65.119/bundles/commons.bundle.js?v=15382:38:23621)
    at https://10.3.65.119/bundles/commons.bundle.js?v=15382:38:23888
    at Scope.$eval (https://10.3.65.119/bundles/commons.bundle.js?v=15382:39:4619)
 
`

**Comment by webboy47** [comment]
Hello,
I have installed wazuhapp-2.1.0_5.5.2.zip with ELK (All 5.5.2). However, wazuh alerts are not shown in kibana.

Best Regards,

**Comment by snaow** [comment]
Related @webboy47 issue at https://github.com/wazuh/wazuh-kibana-app/issues/25

Thanks.
