### ISSUE TITLE
Whitespace in AWS wodle config causes Segmentation Fault of wazuh-modulesd

### ISSUE THREAD

**Issue by UranusBytes** [wazuh/wazuh#1461]
## Bug report

**OS**
CentOS 7 - fully patched

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
Manager

**Install method**
RPM Packages

**Log sample**

This is the outcome of manually running wazuh-modulesd in foreground with debug 2 (`bin/wazuh-modulesd -fdd`)
```
2018/09/26 15:33:34 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2018/09/26 15:33:34 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analisys: training (xxxxxxxx1234 )
2018/09/26 15:33:34 wazuh-modulesd:aws-s3: DEBUG: Create argument list
2018/09/26 15:33:34 wazuh-modulesd:aws-s3: DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket myBucketName --iam_role_arn arn:aws:iam::123412341234:role/MY_ROLE_NAME --aws_account_id xxxxxxxx1234  --aws_account_alias training --only_logs_after 2018-SEP-15 --type cloudtrail --debug 2
2018/09/26 15:33:34 wazuh-modulesd: DEBUG: (1751): File client.keys not found or empty.
2018/09/26 15:33:34 wazuh-modulesd:aws-s3: WARNING: Bucket: xxxxxxxx1234 (training)  -  Returned exit code 2
Segmentation fault

```

Bug description
----------------
If any of the config values (tested aws_account_alias, name, and aws_account_id) for the wodle have a whitespace, it causes a segmentation fault of the wazuh-modulesd

The below config caused the initial error, with the whitespace at the end of the aws_account_id value:
```
    <bucket type="cloudtrail">
      <aws_account_alias>training</aws_account_alias>
      <name>myBucketName</name>
      <aws_account_id>xxxxxxxx1234 </aws_account_id>
      <iam_role_arn>arn:aws:iam::123412341234:role/MY_ROLE_NAME</iam_role_arn>
      <only_logs_after>2018-SEP-15</only_logs_after>
    </bucket>
```

**Comment by albertomn86** [comment]
Hi @UranusBytes. 
Thank you for reporting this issue. It will be fixed in the next release.

Best regards.
