### ISSUE TITLE
how to find the installed python libraries on all wazuh agents

### ISSUE THREAD

**Issue by SyedNference** [wazuh/wazuh#14653]
Hi Team,
can you please develop something on wazuh to find out all the installed python libraries from all the wazuh agents.
if possible means we can get all the libraries installed on the agents from wazuh manager

**Comment by FrancoRivero** [comment]
Hi @SyedNference 
Thanks for using Wazuh!
So there are two capabilities that can help to do this we can configure the folder where the python packages are located these would be [FIM](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/index.html) or we can use [system collector](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages) to get this information along with all the packages in their agents. 
With FIM you would be monitoring the changes in the binary or the changes in the directory where the python packages are (with this you would know when a new package was installed), however, with the system collector you would directly have all the packages installed on the system.
Regards

**Comment by FrancoRivero** [comment]
Hi @SyedNference,
Have you been able to solve the problem?
After two weeks with no response we should close the issue! If you need to reopen this issue, let me know. 
Regards
