### ISSUE TITLE
Is there any way to make the changes  (cdb list)  effective without restarting the wazuh manager?

### ISSUE THREAD

**Issue by WallaceCS** [wazuh/wazuh#14655]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
| 4.1.5 | analysisd / cdb list | Manager | Sources | ubuntu 18.04 |

 Currently, the wazuh manager needs to be restarted every time the cdb list is updated.  This may lead to bad user experience.

 Is there any way to make the changes effective without restarting the wazuh manager?  

Or does anyone have any ideas ？Thank you  for reply.

**Comment by CarlosRS9** [comment]
Hi @WallaceCS,

I am afraid it is not possible. Our current implementation requires to restart the manager when applying changes on CDB Lists, decoders or rules because the analysis engine must verify that they are correct and load them, among other design reasons.

Our team is currently looking into the possibility of changing this in a future release, but at this time we cannot confirm if this will be implemented or not, so I encourage you to stay tuned for changes in future major releases.

We are sorry for any inconvenience this may cause.

Regards.

**Comment by WallaceCS** [comment]
> Hi @WallaceCS,
> 
> I am afraid it is not possible. Our current implementation requires to restart the manager when applying changes on CDB Lists, decoders or rules because the analysis engine must verify that they are correct and load them, among other design reasons.
> 
> Our team is currently looking into the possibility of changing this in a future release, but at this time we cannot confirm if this will be implemented or not, so I encourage you to stay tuned for changes in future major releases.
> 
> We are sorry for any inconvenience this may cause.
> 
> Regards.



> Hi @WallaceCS,
> 
> I am afraid it is not possible. Our current implementation requires to restart the manager when applying changes on CDB Lists, decoders or rules because the analysis engine must verify that they are correct and load them, among other design reasons.
> 
> Our team is currently looking into the possibility of changing this in a future release, but at this time we cannot confirm if this will be implemented or not, so I encourage you to stay tuned for changes in future major releases.
> 
> We are sorry for any inconvenience this may cause.
> 
> Regards.

thank you for reply.  Really looking forward to improvement of the great project.

**Comment by WallaceCS** [comment]
> Hi @WallaceCS,
> 
> I am afraid it is not possible. Our current implementation requires to restart the manager when applying changes on CDB Lists, decoders or rules because the analysis engine must verify that they are correct and load them, among other design reasons.
> 
> Our team is currently looking into the possibility of changing this in a future release, but at this time we cannot confirm if this will be implemented or not, so I encourage you to stay tuned for changes in future major releases.
> 
> We are sorry for any inconvenience this may cause.
> 
> Regards.

Thank you for reply. Really looking forward to improvement of the great project.
