### ISSUE TITLE
Improve SCA Ubuntu Linux 22.04 OS version coverage and rules.

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#14663]
| Component | Action type |
| --- | --- |
| SCA | Improve |

This issue will improve the current SCA Ubuntu Linux 22.04 LTS by adding support for other Ubuntu Linux 22.04 versions. 
Also, improved SCA will include text and rules updates. 

We are expecting a new CIS Benchmark document for Ubuntu 22.04 releases. We will keep using CIS Ubuntu Linux 20.04 LTS Benchmark v1.1.0.

**Comment by ricokritzer** [comment]
Thanks for this issue. The current ruleset is skipped, because in the ruleset "Ubuntu 22.04 LTS" is expected. The field in Ubuntu's newest version is filled with "Ubuntu 22.04.1 LTS" so it does not match and the current version of the fileset is skipped.

**Comment by 72nomada** [comment]
The PR is ready. We will merge it ASAP.
