### ISSUE TITLE
Improve logs related to a missing parameter on an eps configuration

### ISSUE THREAD

**Issue by CamiRomero** [wazuh/wazuh#14665]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | wazuh-analysisd | local | package/sources | Centos 8 |

## Description

Due to the testing of the Issue #12512 we note that when the `maximum` field is not present in the configuration
the value by default (0) is set correctly and the EPS limit is disabled. I suggest, adding a Warning log to informing to users that EPS limit is disabled because is missing a maximum field. 

 
## Steps to reproduce

1. Download and install Wazuh 4.4:

    ```
    curl -LO https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/rpm/var/wazuh-manager-4.4.0-0.commit032cc76.x86_64.rpm

    yum install -y wazuh-manager-4.4.0-0.commit032cc76.x86_64.rpm
    
    systemctl daemon-reload
    systemctl enable wazuh-manager
    systemctl start wazuh-manager
    
    ```
2. Add configuration for EPS in `/var/ossec/logs/ossec.log` without `maximum`:

    ```
    <global>
       <limits>
          <eps>
             <timeframe>30</timeframe>
          </eps>
      </limits>
   </global>

    ```
4. Restart Wazuh manager in order to apply changes:

    ```
    systemctl restart wazuh-manager
    ```
6. Check status of daemons:

    ```
    /var/ossec/bin/wazuh-control status
    ```
    Output:
    ```
    wazuh-clusterd not running...
    wazuh-modulesd is running...
    wazuh-monitord is running...
    wazuh-logcollector is running...
    wazuh-remoted is running...
    wazuh-syscheckd is running...
    wazuh-analysisd is running...
    wazuh-maild not running...
    wazuh-execd is running...
    wazuh-db is running...
    wazuh-authd is running...
    wazuh-agentlessd not running...
    wazuh-integratord not running...
    wazuh-dbd not running...
    wazuh-csyslogd not running...
    wazuh-apid is running...
    
    ```
7. Check logs located in `/var/ossec/logs/ossec.log`:

    ```
    2022/08/17 15:08:29 wazuh-analysisd: INFO: EPS limit disabled

    ```

**Comment by TomasTurina** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/13608/commits/87aaf72bbacbde295d700b8e0f3cf928770b54cc
