### ISSUE TITLE
Release 4.3.7 - Release Candidate 1 - E2E UX tests - Configuration assessment

### ISSUE THREAD

**Issue by matiasmoreno876** [wazuh/wazuh#14662]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.
## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #14562  |
| **Main E2E UX test issue** | #14614    |
| **Version**                      | 4.3.7 |
| **Release candidate #**          | RC1   |
| **Tag**                          | [v4.3.7-rc1](https://github.com/wazuh/wazuh/tree/v4.3.7-rc1) |
| **Previous modules tests issue** | #14268   |

## Installation procedure
- @Machi3mfl 
- @matiasmoreno876 
  - Wazuh Manager stack:[Installation assistant](https://documentation-dev.wazuh.com/4.3.7-rc/installation-guide/wazuh-server/installation-assistant.html) on Amazon Linux 2
  - Wazuh Agent: Wazuh WUI one-liner deploy FQDN on Amazon Linux 2
 - @Mayons95 
   - Wazuh Manager stack:[Step-by-step](https://documentation-dev.wazuh.com/4.3.7-rc/installation-guide/wazuh-indexer/step-by-step.html) on Ubuntu 22.04
   - Wazuh Agent: https://documentation-dev.wazuh.com/4.3.7-rc/installation-guide/wazuh-agent/index.html on Ubuntu 22.04

### Validate issues reported from last E2E test
[#5478](https://github.com/wazuh/wazuh-documentation/issues/5478)
[#13949](https://github.com/wazuh/wazuh/issues/13949)
[#14346](https://github.com/wazuh/wazuh/issues/14346)

### Validate changes from v4.3.0 to 4.3.7 (only if applies)
https://github.com/wazuh/wazuh/pull/13893
https://github.com/wazuh/wazuh/pull/13905
https://github.com/wazuh/wazuh/pull/13781
https://github.com/wazuh/wazuh/pull/13950
### Validate documentation consistency
https://documentation-dev.wazuh.com/4.3.7-rc/user-manual/capabilities/sec-config-assessment/index.html
### Validate use case
https://documentation-dev.wazuh.com/4.3.7-rc/user-manual/capabilities/sec-config-assessment/use-case.html
## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | Test went as expected. |
| :red_circle:  | Test fails and must be addressed. |
| :yellow_circle:  | Test meet the goal but some improvements must be addressed for UX|

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results can be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found in the issue updates.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|:green_circle:|Validate documentation consistency| Functional | |
|:green_circle:|Validate issues reported from last E2E test|Documentation| Issue [#5478](https://github.com/wazuh/wazuh-documentation/issues/5478) solved|
|:green_circle:|Validate issues reported from last E2E test|Functional|Issue [#13949](https://github.com/wazuh/wazuh/issues/13949) solved|
|:white_circle: |Validate issues reported from last E2E test|Functional| Issue [#14346](https://github.com/wazuh/wazuh/issues/14346) open |
|:white_circle:|Validate changes from v4.3.0 to 4.3.6|Functional| |
|:white_circle:|Validate documentation consistency| Documentation | |
|:white_circle:|Validate documentation consistency| Functional | |
|:white_circle:|Validate use case| Documentation | |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @vikman90

**Comment by Mayons95** [comment]
<details>
<summary>

## Wazuh Manager stack on Ubuntu 22.04 :green_circle: 
</summary>

 - Indexer installation :green_circle: 
```
root@jammy:/home/vagrant#  curl -k -u admin:admin https://192.168.20.27:9200/_cat/nodes?v
ip            heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
192.168.20.27           19          95   0    0.09    0.07     0.08 dimr      *      node-1
```
 - Server installation :green_circle: 
```
root@jammy:/home/vagrant# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-07-15 14:58:21 -03; 53min ago
      Tasks: 175 (limit: 2240)
     Memory: 251.7M
        CPU: 1min 11.371s
     CGroup: /system.slice/wazuh-manager.service
             ├─76087 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─76126 /var/ossec/bin/wazuh-authd
             ├─76142 /var/ossec/bin/wazuh-db
             ├─76156 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─76159 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─76171 /var/ossec/bin/wazuh-execd
             ├─76185 /var/ossec/bin/wazuh-analysisd
             ├─76282 /var/ossec/bin/wazuh-syscheckd
             ├─76295 /var/ossec/bin/wazuh-remoted
             ├─76327 /var/ossec/bin/wazuh-logcollector
             ├─76350 /var/ossec/bin/wazuh-monitord
             └─76372 /var/ossec/bin/wazuh-modulesd

Jul 15 14:58:19 jammy env[76034]: Started wazuh-modulesd...
Jul 15 14:58:21 jammy env[76034]: Completed.
Jul 15 14:58:21 jammy systemd[1]: Started Wazuh manager.
```
  - Filebeat status: :green_circle: 
```
root@jammy:/home/vagrant#  filebeat test output
elasticsearch: https://192.168.20.27:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 192.168.20.27
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

 - Dashboard :green_circle: 
![dashboard](https://user-images.githubusercontent.com/7939712/179292510-25e995cd-19d9-41c0-9ec7-fa8837caa0c6.png)
</details>

<details>
<summary>

## Wazuh Agent on Ubuntu 22.04 :green_circle: 
</summary>

 - Agent v4.3.6 installation :green_circle: 
![agent4 3 6](https://user-images.githubusercontent.com/7939712/179292834-a3cf272b-2ac8-42b3-b785-c52e9c88b135.png)

</details>

<details>
<summary>

## Changes from v4.3.0 to 4.3.7   :red_circle: _circle: 
</summary>

<details>
<summary>
- Test that an SCA policy check that passed on the first scan generates an alert at a later time when the condition check fails.:green_circle:
  
</summary>

  

</details>

<details>
<summary>
 - In addition, several policies were checked changing their state and verifying the status on the dashboard.:red_circle:
</summary>
   
</details>
</details>

<details>
<summary>

## Use case: Getting an alert when a check changes its result value [(link)](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-case.html#id1) :red_circle: 
</summary>

</details>

<details>
<summary>

## Wazuh Dashboard SCA scan results :red_circle: 
</summary>

- There are not SCA alerts generated on SCA Dashboard for ubuntu 22.0.4.1, related issue: https://github.com/wazuh/wazuh/issues/14663

</details>

**Comment by matiasmoreno876** [comment]
<details>
<summary>

### Wazuh Manager stack on Amazon Linux 2 :green_circle: 

</summary>

#### Indexer installation :green_circle: 
 
![image](https://user-images.githubusercontent.com/49887871/185997566-d3a3c824-90b3-4fe9-bd01-295668fa102d.png)
![image](https://user-images.githubusercontent.com/49887871/185997796-40ccb152-f883-4d17-9303-4efe488755bf.png)
![image](https://user-images.githubusercontent.com/49887871/185998026-8c32faab-6afc-4d20-b953-fcb1b133ebb1.png)


#### Wazuh manager installation :green_circle: 
![image](https://user-images.githubusercontent.com/49887871/185998411-db30a709-4f17-4733-ba5f-891a5c972541.png)
![image](https://user-images.githubusercontent.com/49887871/185998664-0b201ec2-3186-46fb-a624-039b9e78fb59.png)

#### Filebeat status: :green_circle: 
![image](https://user-images.githubusercontent.com/49887871/185998927-ff66313b-c61b-4cec-8dd4-f16db6806410.png)

#### Wazuh Dashboard :green_circle: 
![image](https://user-images.githubusercontent.com/49887871/185999167-c5de996b-ff39-4733-abbb-96e342ab815d.png)
![image](https://user-images.githubusercontent.com/49887871/185999404-594c7a6a-e5e9-472c-be2a-90f947d69608.png)

</details>

<details>
<summary>

### Wazuh Agent on Amazon Linux 2 :white_circle: 

</summary>

 #### Agent v4.3.7 installation :white_circle: 
In progress ...

</details>

<details>
<summary>

### Changes from v4.3.0 to 4.3.7   :white_circle:
</summary>

<summary>
  

</summary>
</details>

<details>
<summary>

### Wazuh Dashboard SCA scan results :white_circle: 
</summary>


</details>
<details>
<summary>

### Use case: Getting an alert when a check changes its result value [(link)](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-case.html#id1) :white_circle: 
</summary>
 
</details>

**Comment by Mayons95** [comment]
<details>
<summary>

### Use case: Getting an alert when a check changes its result value [(link)](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-case.html#id1) :white_circle: 

</summary>

 First Scan Alert

![image](https://user-images.githubusercontent.com/104914131/186227419-e649fffc-b3fa-4d54-a302-1d54d7e7a57d.png)

 First Summary

 
![Screenshot from 2022-08-23 14-43-36](https://user-images.githubusercontent.com/104914131/186228228-5a3d6282-0a6e-413b-917a-f5ac4ad82561.png)

 Alerts on dashboard

![image](https://user-images.githubusercontent.com/104914131/186228457-540db2ee-f156-4ace-a40f-4943aafe46c1.png)

Scan after enabling PermitRootLogin:

![image](https://user-images.githubusercontent.com/104914131/186228787-1f384f25-8c5b-4ded-bdea-31924939a4f1.png)

 Use case comments
1) After execute the command: "sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config"  the Alert was displayed but the result is failed.


</details>
