### ISSUE TITLE
Wazuh 4.3 - SCA running disabled policy 

### ISSUE THREAD

**Issue by Hitamashi** [wazuh/wazuh#14675]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.3.3-40315 | sca | Agent | Packages | Alma Linux 8.6 |

We have updated from wazuh 3.13 to wazuh 4.3.3
The following config working on 3.13 but it's not on 4.3.3. We disabled a policy but it is still evaluated in 4.3.3
We do a quick check on the document and it seems no change is introduced in 4.3 compared to the old version: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/sca.html

```
<sca>
    <enabled>yes</enabled>
    <scan_on_start>no</scan_on_start>
    <interval>1d</interval>
    <skip_nfs>yes</skip_nfs>
    <time>11:00</time>
    <policies>
        <policy enabled="yes">/var/ossec/etc/shared/up-pci-dss.yml</policy>
        <policy enabled="yes">/var/ossec/etc/shared/up-pci-dss-el8.yml</policy>
        <policy enabled="no">/var/ossec/ruleset/sca/cis_rhel7_linux.yml</policy>
    </policies>
</sca>

```

The logs showing it running the disabled policy:
```
2022/08/17 11:00:00 sca: INFO: Starting Security Configuration Assessment scan.
2022/08/17 11:00:00 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_centos7_linux.yml'
2022/08/17 11:00:39 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_centos7_linux.yml'
2022/08/17 11:00:39 sca: INFO: Starting evaluation of policy: '/var/ossec/etc/shared/up-pci-dss.yml'
2022/08/17 11:10:59 sca: INFO: Evaluation finished for policy '/var/ossec/etc/shared/up-pci-dss.yml'
2022/08/17 11:11:08 sca: INFO: Skipping policy '/var/ossec/etc/shared/up-pci-dss-el8.yml': 'Check RHEL8 family platform'
2022/08/17 11:11:08 sca: INFO: Security Configuration Assessment scan finished. Duration: 668 seconds.
```

Could you please help to check it?

**Comment by tsarquis88** [comment]
Hi @Hitamashi, thanks for using Wazuh!

I'm not seeing the policy you've disabled being evaluated in the log provided.

You've disabled: `var/ossec/ruleset/sca/cis_rhel7_linux.yml`
Policies being evaluated: `/var/ossec/ruleset/sca/cis_centos7_linux.yml` and `/var/ossec/etc/shared/up-pci-dss.yml`

**Comment by Hitamashi** [comment]
Thanks you so much.
It's my bad for not checking the log properly. Seems like wazuh 4 introduced a proper ruleset for Centos 7
The policy is disabled with good config now
