### ISSUE TITLE
Add endpoint to restart TCP load balancing mechanism

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14677]
## Description
There are certain situations where the new cluster TCP balancing mechanism is intentionally stopped and remains that way until the master's clusterd process is restarted. 

This could happen, for example, if the agents are still unbalanced after the execution of the algorithm, which could mean that the environment's load balancer is not properly configured. In this case, to avoid sending new reconnection requests to the agents with a useless effect, the algorithm enters the HALT phase until it is restarted.

It is intended to add a command that takes the algorithm out of the HALT phase and makes it run again (https://github.com/wazuh/wazuh/issues/14470). A new endpoint is required to produce the described action by sending the command to the cluster.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
The endpoint should allow restarting and also stopping the mechanism.
