### ISSUE TITLE
Release 4.3.7 - Release Candidate 1 - E2E UX tests - Vulnerability Detector

### ISSUE THREAD

**Issue by sultanovich** [wazuh/wazuh#14683]
## Description

The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                       |                                            |
|-----------------------|--------------------------------------------|
| **Test name**         |  Vulnerability detection       |
| **Category**          |  Vulnerability detection        |
| **Deployment option** | Quickstart                                      |
| **Main release issue** | https://github.com/wazuh/wazuh/issues/14614                                           |
| **Release candidate #** | RC1                                           |

|Components| Instalation |  OS
|---|---|--|
| Wazuh Indexer |[Quickstart ](https://documentation.wazuh.com/current/quickstart.html)| Amazon Linux 2
| Wazuh Dashboard | [Quickstart ](https://documentation.wazuh.com/current/quickstart.html) | Amazon Linux 2
| Wazuh Server | [Quickstart ](https://documentation.wazuh.com/current/quickstart.htmll) |Amazon Linux 2
| Wazuh agent | [Installation from sources](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) | Amazon Linux, Arch Linux, CentOS, Ubuntu, Windows

## Tasks

> 
>  - Use the new UI for vulnerabilities. 
>  - Install vulnerable package to force an alert. 
>  - Patch or uninstall vulnerable packe to force a "solved" alert.

  
- [x] Fresh Install: Patch the vulnerable package to force a "solved" alert. 
    - [x] CentOS
    - [x] Ubuntu
    - [x] Amazon Linux
    - [x] Windows
    - [x] Arch Linux 

- [x] Upgrade 4.3.6 to 4.3.7: Patch the vulnerable package to force a "solved" alert. 
    - [x] CentOS

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|🔵|Test execution in progress|
|⚫|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Conclusions  🟢

- [Comment](https://github.com/wazuh/wazuh/issues/14683#issuecomment-1220220080)

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x]  @jesuslinares 
- [x] @vikman90

**Comment by sultanovich** [comment]
# Upgrade 4.3.6 to 4.3.7: Patch the vulnerable package to force a "solved" alert. 🟢 

<details>
<summary> Upgrade Section</summary>

1. Check our manager with `4.3.7`: 

    > [root@ip-172-31-34-195 ~]# /var/ossec/bin/wazuh-control info -
    > v4.3.7

2. Check our agent with `4.3.6`:

    > [root@b2f4d457af6a /]#  /var/ossec/bin/wazuh-control info -v
    > v4.3.6

3. Check status to agent and manager
   
   Manager:

    > [root@ip-172-31-34-195 ~]# /var/ossec/bin/wazuh-control status
    > wazuh-clusterd not running...
    > wazuh-modulesd is running...
    > wazuh-monitord is running...
    > wazuh-logcollector is running...
    > wazuh-remoted is running...
    > wazuh-syscheckd is running...
    > wazuh-analysisd is running...
    > wazuh-maild not running...
    > wazuh-execd is running...
    > wazuh-db is running...
    > wazuh-authd is running...
    > wazuh-agentlessd not running...
    > wazuh-integratord not running...
    > wazuh-dbd not running...
    > wazuh-csyslogd not running...
    > wazuh-apid is running...
    > [root@ip-172-31-34-195 ~]#

   Agent:

    > [root@b2f4d457af6a /]# /var/ossec/bin/wazuh-control status
    > wazuh-modulesd is running...
    > wazuh-logcollector is running...
    > wazuh-syscheckd is running...
    > wazuh-agentd is running...
    > wazuh-execd is running...
    > [root@b2f4d457af6a /]#

![image](https://user-images.githubusercontent.com/601474/185455291-d19e1a41-f306-4857-b19a-15dce8825aa6.png)


4. Upgrade the agent to `4.3.6` 

5. Verify the correct version was install:

    > [root@ip-172-31-34-195 ~]#  /var/ossec/bin/wazuh-control info
    > WAZUH_VERSION="v4.3.7"
    > WAZUH_REVISION="40319"
    > WAZUH_TYPE="server"
    > [root@ip-172-31-34-195 ~]#
    > 
    > [root@b2f4d457af6a /]# /var/ossec/bin/wazuh-control info
    > WAZUH_VERSION="v4.3.7"
    > WAZUH_REVISION="40319"
    > WAZUH_TYPE="agent"
    > [root@b2f4d457af6a /]#

![image](https://user-images.githubusercontent.com/601474/185456617-f3967e20-7789-4adf-83dc-67332d3ed60b.png)

5. Restart manager and agent. Check status 

    Manager:
      
    > [root@ip-172-31-34-195 ~]# /var/ossec/bin/wazuh-control status
    > wazuh-clusterd not running...
    > wazuh-modulesd is running...
    > wazuh-monitord is running...
    > wazuh-logcollector is running...
    > wazuh-remoted is running...
    > wazuh-syscheckd is running...
    > wazuh-analysisd is running...
    > wazuh-maild not running...
    > wazuh-execd is running...
    > wazuh-db is running...
    > wazuh-authd is running...
    > wazuh-agentlessd not running...
    > wazuh-integratord not running...
    > wazuh-dbd not running...
    > wazuh-csyslogd not running...
    > wazuh-apid is running...
    > [root@ip-172-31-34-195 ~]#
  
     Agent: 
  
    > [root@b2f4d457af6a /]# /var/ossec/bin/wazuh-control status
    > wazuh-modulesd is running...
    > wazuh-logcollector is running...
    > wazuh-syscheckd is running...
    > wazuh-agentd is running...
    > wazuh-execd is running...
    > [root@b2f4d457af6a /]#

</details>

<details>
<summary> Centos - Patch the vulnerable package to force a "solved" alert.</summary>

1. The alert generated is shown on Dashboard.

    ![image](https://user-images.githubusercontent.com/601474/185457694-44b9c704-d9ba-470e-9d85-32e977a55d55.png)

2. Patch the vulnerable package to force a "solved" alert. 

    > yum install curl

3. Restart the agent   
4. The alert solved generated is shown on Dashboard.
  
   ![image](https://user-images.githubusercontent.com/601474/185458115-5339cfec-bded-42db-b597-3f3f4ed40218.png)

</details>

<details>
<summary> Centos - Remove the vulnerable package to force a "solved" alert.</summary>

1. The alert generated is shown on Dashboard.

    ![image](https://user-images.githubusercontent.com/601474/185458994-9ee3a998-5716-452b-9c45-51b8c126a552.png)

2. Patch the vulnerable package to force a "solved" alert. 

    > yum remove openssh

3. Restart the agent   
4. The alert solved generated is shown on Dashboard.
  
   ![image](https://user-images.githubusercontent.com/601474/185460222-3e56a99b-f439-4882-8bdc-52a0abd3499d.png)
   ![image](https://user-images.githubusercontent.com/601474/185460320-2b854c8c-d72b-48c9-a1fb-2de5e70d1673.png)

</details>

**Comment by sultanovich** [comment]
## Conclusion

After testing the cases, we can visualize the generated and resolved alerts with the UI. 
Also, we can see that once the vulnerable package is resolved, it disappears from the Inventory list.

**Comment by jesuslinares** [comment]
The tests look good but the flow was:
- fix package
- restart agent
- check

In the real world, a user fixes the vulnerable package (like curl) but **the Wazuh agent is not restarted.** I understand that the restart was performed in order to force the vulnerability scan, but I'm not sure if we are missing something due to this restart.

@vikman90 what do you think?

**Comment by vikman90** [comment]
Hi @jesuslinares, IMO we should approve this test as it has been executed like the previous one (https://github.com/wazuh/wazuh-qa/issues/3106).

We will extend this case in future releases.
