### ISSUE TITLE
Wazuh in /var

### ISSUE THREAD

**Issue by superpoussin22** [wazuh/wazuh#147]
Coudl it be possible to change the default installation directory  of wazuh to somewhere else like /opt on Contos/Redhat ...  executing software in /var is a bad idea in term of security in particular because it's a good practice to set a noexec on /var 

The rpm can't be relocated , so to install it on antoher location, it's required to compile sources and to install gcc on servers :(

What do you think ?

Thanks in advance

**Comment by jesuslinares** [comment]
Hi,

we will publish packages for /opt as soon as possible. Meanwhile, you can install [Wazuh from sources](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html) and select the installation path.

Thanks for the feedback.
Regards.

**Comment by crolopez** [comment]
As @jesuslinares says, it is possible to install in alternate paths using **install.sh**. In addition, we are working on removing the dependency on the installation path specified at compile time (https://github.com/wazuh/wazuh/issues/785).

Let me close the issue.
