### ISSUE TITLE
CloudWatch Logs raises ThrottlingException

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#14709]
| Wazuh |
| ----- |
| 4.3.7   |

**Description**
Running the [Release 4.3.7 - Release Candidate 1 - E2E UX tests - Demo environment](https://github.com/wazuh/wazuh/issues/14674), we find [some warning messages](https://github.com/wazuh/wazuh/issues/14674#issuecomment-1220000738) in the `Master-env1` and `Master-env2` environments. The messages observed are the following:

```
wazuh-modulesd:aws-s3: WARNING: Service: inspector - Returned exit code 12

wazuh-modulesd:aws-s3: WARNING: Service: inspector - An error occurred (ThrottlingException) when calling the ListFindings operation (reached max retries: 4): Rate exceeded
```

**Steps to reproduce**
To find the warning messages, you need to connect to the `Master-env1` and `Master-env2` environments and run the command: `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`

**Expected Result**
No warning

The same warning was reported in [this issue](https://github.com/wazuh/wazuh/issues/10754) and apparently it was not fully resolved.

**Actual Result**
Warning

**Comment by nico-stefani** [comment]
## Issue Update

Making a quick research the issue isn't in `CloudWatch`. We have the same unhandled exception reported in #10754, but this time is occurring in `Inspector` service.

**Comment by CarlosRS9** [comment]
The way we are handling these Throttling and other related exception in the AWS integration is being reviewed and improved in https://github.com/wazuh/wazuh/issues/14754

**Comment by davidjiglesias** [comment]
Duplicated with https://github.com/wazuh/wazuh/issues/14754.
