### ISSUE TITLE
AWS cloudwatch integration not retrieving data although aws wodle logs don't show any errors

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#14718]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | AWS Cloudwatch | Manager/Agent | Packages | Ubuntu |

Hello team,

We observed the following scenario when using the CloudWatch integration. We applied the following configuration:

**Configuration applied on Wazuh agent 4.3.6. Ubuntu Linux. However, the same happens when configured on a Wazuh manager in the same version and OS**

```
 <agent_config>
    <!-- Shared agent configuration here -->
    <wodle name="aws-s3">
      <disabled>no</disabled>
      <interval>1h</interval>
      <run_on_start>yes</run_on_start>
      <service type="cloudwatchlogs">
        <access_key>_hidden_</access_key>
        <secret_key>_hidden_</secret_key>
        <only_logs_after>2022-Aug-18</only_logs_after>
        <regions>us-east-1</regions>
        <aws_log_groups>/aws/co****/us*****/us-east-1_*****/Re********</aws_log_groups>
      </service>
    </wodle>
  </agent_config>
```

Logs show that the integration is running as expected. In addition to this, the debug logs show the log_groups are being read:

```
DEBUG: Getting log streams for "/aws/co****/us*****/us-east-1_*****/Re********" log group
DEBUG: Found "2022/08/16/[$LATEST]187******" log stream in /aws/co****/us*****/us-east-1_*****/Re********
```
Archival logs show the debug logs that confirm there are data in the log_groups and are being read by the integration:

```
"timestamp":"2022-08-19T06:23:54.940+0000","agent":{"id":"***","name":"","ip":"**"},"manager":{"name":"wazuh-manager-worker-1"},"id":"1660****","cluster":{"name":"j***","node":"wazuh-manager-worker-1"},"full_log":"DEBUG: Getting data from DB for log stream \"*****8\" in log group \"/aws/co****/us******/us-east-1_******/Re***\"","decoder":{},"location":"aws-s3"}
```

However, there are no logs regarding the content of the log_groups in the archival data. If we disable the debug mode, the archival shows nothing.

We used several log streams and all of them contain data.

Regards,

Miguel Casares

**Comment by fdalmaup** [comment]
# Issue Update

After making some tests I would recommend to look for `Wazuh-AWS` on the archives and if it is needed, to process again the logs, removing the `aws_services.db` file. The `aws_services.db` file is one of the keys to get the logs. This database contains information about which logstreams were processed and if it is not removed then the logs won't be processed again. The correct way to check if the logs were processed is looking for `Wazuh-AWS` in the archives, for example, with `grep Wazuh-AWS /var/ossec/logs/archives/archives.log`. This will show the logs sent to Analysisd at any time and won't get the rest of the DEBUG messages regarding the module.
To verify the processing of the logs, one option is to remove the .db file and then restart the Wazuh service or wait for the interval defined in the `<wodle>` section of the configuration file. It is possible that the logs were processed previously, having entries in the database and therefore not being registered in the archives files after enabling  `logall` in the configuration. An alternative to this, is to verify the contents of the .db file with the following command `sqlite3 /var/ossec/wodles/aws/aws_services.db 'select * from cloudwatch_logs'`

**Comment by fdalmaup** [comment]
# Issue Update

It was found that a `ThrottlingException` is being triggered when trying to get the log streams in the `get_log_streams` method of the `AWSCloudWatchLogs` class. This kind of exception has been issued in the past in [#10754](https://github.com/wazuh/wazuh/issues/10754) but it involved code executed after getting the log streams.
It was proved after some changes in the aws-s3.py script, specifically in the following DEBUG message:

`AWSCloudWatchLogs.get_log_streams`
https://github.com/wazuh/wazuh/blob/be15851b8ead7512d9cd4ef1ee18b3b953173211/wodles/aws/aws_s3.py#L3313-L3316
to:
```
except Exception as e:
    debug('++++ The specified "{}" log group does not exist or insufficient privileges to access it. Extra information: {}'.format(
        log_group, e), 0)
```

The results after the execution were:
<details><summary>Debug messages</summary>

    2022/08/26 14:54:01 wazuh-modulesd:aws-s3[21303] wm_aws.c:642 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 3
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: only logs: 1661385600000
    DEBUG: Getting log streams for"/a**/****/************"  log group
    DEBUG: ++++ The specified "/a**/****/************"  log group does not exist or insufficient privileges to access it. Extra information: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "/a**/****/************" log group
    DEBUG: ++++ The specified "/a**/****/************" log group does not exist or insufficient privileges to access it. Extra information: An error occurred (ThrottlingException) when calling the DescribeLogStreams operation (reached max retries: 4): Rate exceeded
    DEBUG: committing changes and closing the DB

</details>

**Comment by CarlosRS9** [comment]
This issue was fixed in https://github.com/wazuh/wazuh/issues/14754 by improving the way we are using the `Retry` option that AWS and Boto3 provides. The documentation on how to configure this option was added in https://github.com/wazuh/wazuh-documentation/pull/5559
