### ISSUE TITLE
The eventlog service is down. Unable to collect logs Windows agent warning

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#14712]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | Logcollector | Agent | Packages/Sources | Windows |

# Description 

During the exploratory testing performed as part of this issue https://github.com/wazuh/wazuh/issues/14674
it was found that the Eventlog service doesn't start. 

`wazuh-agent: WARNING: The eventlog service is down. Unable to collect logs from 'Microsoft-Windows-Windows Defender/Operational' channel.`

`wazuh-agent: WARNING: The eventlog service is down. Unable to collect logs from 'Security' channel.`

`wazuh-agent: WARNING: The eventlog service is down. Unable to collect logs from 'Microsoft-Windows-Sysmon/Operational' channel.`

`wazuh-agent: WARNING: The EventLog service is down. Unable to collect logs from its channels.`

The issue may be related to these previously reported 

- https://github.com/wazuh/wazuh/issues/8580
- https://github.com/wazuh/wazuh/issues/8581

**Comment by vikman90** [comment]
Hi @MiguelazoDS,

I see all these events occurred at the same time, maybe the Eventlog service got restarted. Did you find a log like this later?

```
wazuh-agent: INFO: '...' channel has been reconnected succesfully.
```

**Comment by MiguelazoDS** [comment]
Hi @vikman90, you're right! I downloaded all the logs from that agent. 
Here is the line you mentioned, thanks! 

![image](https://user-images.githubusercontent.com/13010397/186192163-a6d32ff4-1a85-40aa-90f1-a4de36f8f6b5.png)
