### ISSUE TITLE
FIM: Error in LookupAccountSid

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#14713]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.3.7 | FIM | Agent | Packages/Sources | Windows |

# Description 

During the exploratory testing performed as part of this issue https://github.com/wazuh/wazuh/issues/14674 it was found an either on - function get_user() or get_registry_group() in syscheck_op.c 

```wazuh-agent: ERROR: Error in LookupAccountSid.```

**Comment by vikman90** [comment]
Thanks @MiguelazoDS.

The first fix I would apply to this issue is to make the log more descriptive:

```
wazuh-agent: ERROR: Error in LookupAccountSid: ...
```

Cheers!

**Comment by MiguelazoDS** [comment]
Hi team, I downloaded the logs from that agent and I see that the error was logged only on 19/08. 

![image](https://user-images.githubusercontent.com/13010397/186194260-98c015cd-652a-44c6-981c-8be8aee552b5.png)

I compressed the logs if you want to check them more in detail. Regards!

[win_agent_logs.zip](https://github.com/wazuh/wazuh/files/9403810/win_agent_logs.zip)
