### ISSUE TITLE
macOS invalid os name.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#14729]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | Wazuh dataprovider / version_op | Agent | Packages/Sources | macOS |

## Description
This issue aims to resolve the incorrect identification of the OS name, from what we see in the image, a macOS Mojave is shown as "Mac OS X", when it should simply be "macOS"

Actual:
![image](https://user-images.githubusercontent.com/14300208/186585520-e126b9ec-6d62-4aba-84a1-2f48880da2ad.png)
![image](https://user-images.githubusercontent.com/14300208/186586695-e4354b97-8786-42cd-bac3-98ae00449ca0.png)

Expected:
![image](https://user-images.githubusercontent.com/14300208/186586802-2c5c8690-c726-42cf-bf8e-4f575ef4cb7d.png)
![image](https://user-images.githubusercontent.com/14300208/186587029-9d7f297c-29f8-4186-8eec-40a18d8e16c6.png)

## DoD
- [x] Check what is the behavior on Wazuh's supported macOS versions
- [x] Identify where to get the correct OS name.
- [x] Change Implementation.
- [x] Modify unit/component tests.
- [x] Validate the impact of modules that could be consumers of this information
- [x] PR Review
- [x] CI checks
- [ ] QA Manual test https://github.com/wazuh/wazuh-qa/issues/3363
- [ ] QA Automatized test update

**Comment by tsarquis88** [comment]
Wazuh is obtaining the macOS's name from the system command `sw_vers`, whose output is differing between macOS releases. Mojave is not the only case, as the same problem happens with Catalina.

#### Mojave's output:
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
```

#### Catalina's output:
```
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

#### Big Sur's output:
```
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B29
```

**Comment by tsarquis88** [comment]
## Alternative
One possible alternative is `system_profiler SPSoftwareDataType`, as we can extract the OS name from the `System Version` key provided by this command.

### Output of `system_profiler SPSoftwareDataType` 
Below are the `system_profiler` outputs performed in all the macOS releases under virtualbox.

#### Sierra's output:
```
Software:

    System Software Overview:

      System Version: macOS 10.12 (16A323)
      Kernel Version: Darwin 16.0.0
      Boot Volume: sierra
      Boot Mode: Normal
      Computer Name: macos-sierra-vm
      User Name: Tomas Sarquis (macos-sierra-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 minutes
```

#### High Sierra's output:
```
Software:

    System Software Overview:

      System Version: macOS 10.13.6 (17G66)
      Kernel Version: Darwin 17.7.0
      Boot Volume: highsierra
      Boot Mode: Normal
      Computer Name: macos-highsierra-vm
      User Name: Tomas Sarquis (macos-highsierra-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 4 minutes
```

#### Mojave's output:
```
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G103)
      Kernel Version: Darwin 18.7.0
      Boot Volume: mojave
      Boot Mode: Normal
      Computer Name: Tomas’s iMac
      User Name: Tomas Sarquis (macos-mojave-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 minutes
```
#### Catalina's output:
```
Software:

    System Software Overview:

      System Version: macOS 10.15.5 (19F101)
      Kernel Version: Darwin 19.5.0
      Boot Volume: catalina
      Boot Mode: Normal
      Computer Name: Tomas’s iMac (2)
      User Name: Tomas Sarquis (macos-catalina-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 minutes
```
#### Big Sur's output:
```
Software:

    System Software Overview:

      System Version: macOS 11.0.1 (20B29)
      Kernel Version: Darwin 20.1.0
      Boot Volume: bigsur
      Boot Mode: Normal
      Computer Name: Tomas’s iMac
      User Name: Tomas Sarquis (macos-bigsur-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 6 minutes
```
#### Monterey's output:
```
Software:

    System Software Overview:

      System Version: macOS 12.0.1 (21A559)
      Kernel Version: Darwin 21.1.0
      Boot Volume: monterey
      Boot Mode: Normal
      Computer Name: Tomas’s iMac
      User Name: Tomas Sarquis (macos-monterey-vm)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 minutes
```
