### ISSUE TITLE
Remoted process at 100% of CPU usage in a Wazuh master node without agents

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#14733]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6| remoted | Manager | Packages | Ubuntu 20 |

Hello team,

I'm opening this issue because I observed a high CPU usage coming from the `remoted` process in a Wazuh master node.
![image](https://user-images.githubusercontent.com/23264276/186651029-c2c07b74-ba27-4c76-8ade-84c926f8f79f.png)

However, this master node is not processing data coming from agents:
```
# State file for wazuh-remoted
# Updated every 5 seconds.

# Queue size
queue_size='0'

# Total queue size
total_queue_size='131072'

# TCP sessions
tcp_sessions='0'

# Events sent to Analysisd
evt_count='0'

# Control messages received
ctrl_msg_count='0'

# Discarded messages
discarded_count='0'

# Messages queued
queued_msgs='0'

# Total number of bytes sent
sent_bytes='0'

# Total number of bytes received
recv_bytes='4023'

# Messages dequeued after the agent closes the connection
dequeued_after_close='0'
```

The total number of agents is:
```
/var/ossec/bin/cluster_control -a | wc -l
6650
```
And the active number of agents:
```
6484
```
The environment is quite loaded and the cluster synchronization is taking a lot of time to finish. Also, the Wazuh API calls are taking time:
```
GET /cluster/wazuh-manager-worker-1/stats/remoted" with parameters {"pretty": ""} and body {} done in 26.455s: 200
```

The master node has the following specs:
```
            cpu: "4"
            memory: 12Gi
````

We should investigate this problem deeper.

Regards,

Miguel Casares

**Comment by TomasTurina** [comment]
## Update

Analyzing the master logs, there is no log that indicates for sure what the problem with `wazuh-remoted` might have been.

I repeatedly see these logs, as if there were agents that cannot be registered:

```
...
2022/08/23 16:04:33 wazuh-authd: ERROR: Invalid password provided by 10.3.105.131. Closing connection.
2022/08/23 16:04:33 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:33 wazuh-authd: INFO: Received request for a new agent (ANVGAPASITBS01) from: 10.3.105.131
2022/08/23 16:04:33 wazuh-authd: INFO: Duplicate name. Removing old agent 'ANVGAPASITBS01' (id '156330').
2022/08/23 16:04:33 wazuh-authd: INFO: Agent key generated for 'ANVGAPASITBS01' (requested by any)
2022/08/23 16:04:33 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:33 wazuh-authd: ERROR: Invalid password provided by 10.3.105.131. Closing connection.
2022/08/23 16:04:33 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:33 wazuh-authd: ERROR: Invalid password provided by 10.3.105.131. Closing connection.
2022/08/23 16:04:33 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:33 wazuh-authd: ERROR: Invalid password provided by 10.3.105.131. Closing connection.
2022/08/23 16:04:34 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:34 wazuh-authd: INFO: Received request for a new agent (au1pdas108uis01.idm.vcs.prod) from: 10.3.105.131
2022/08/23 16:04:34 wazuh-authd: ERROR: Invalid group: Environment_prd
2022/08/23 16:04:34 wazuh-authd: INFO: New connection from 10.3.105.131
2022/08/23 16:04:34 wazuh-authd: ERROR: Invalid password provided by 10.3.105.131. Closing connection.
...
```

I also see these logs which may indicate that `wazuh-remoted`'s CPU usage may be due to reloading the keystore every time a new agent is registered, though I'm not entirely sure that might be what's leading to CPU max:

```
...
2022/08/23 07:55:21 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 07:55:21 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
2022/08/23 08:09:42 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 08:09:42 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
2022/08/23 08:30:32 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 08:30:32 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
2022/08/23 08:43:52 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 08:43:52 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
2022/08/23 08:49:03 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 08:49:03 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
2022/08/23 09:00:53 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/08/23 09:00:53 wazuh-remoted: INFO: (1410): Reading authentication keys file.
...
```

Regarding the generation of multigroups, I could not identify anything in the logs. I'm going to need you to turn on debug logs to get more information and draw more conclusions, in case the problem recurs.

I think that the problem is due to the reloading of the agent keys rather than a multigroup generation problem, but I am waiting to see if the problem repeats and if the debug logs can be enabled to continue analyzing it.

**Comment by TomasTurina** [comment]
## Update 2

After looking more closely at the `wazuh-remoted` code, I think the CPU usage issue may come from the multigroup generation mechanism.

In the latest improvements, what was done was that the multigroups were not deleted and created in each iteration (by default, every 10 seconds). However, the process of obtaining all the agents and the groups to which they belong and comparing all this information with that stored in memory to detect possible changes in the multigroups is something that needs to be done. I think what may be consuming that CPU is the process of looking for changes between the previous scan and the new one to know whether to regenerate multigroups or not.

I understand that it is an environment with a very large number of multigroups, so the process that I explained above can become a bit heavy. The issue is that we have to do it because otherwise we wouldn't know when something has changed and what has changed to just create/regenerate that.

In this case I would propose, to reduce the load a bit, increase the size of `remoted.shared_reload` so that it does not do it every 10 seconds but every longer.

**Comment by TomasTurina** [comment]
## Update 3

There are many things that can be improved to avoid this CPU usage for long periods of time in the multigroup generation mechanism:

- Convert the `groups` and `multi_groups` variables to hash tables, to speed up group lookup.
- Convert the `f_sum` list of files in each group to hash tables, to speed up file lookup.
- When comparing the old sum of the file with the new one, before calculating the new sum, check if the `mtime` of the file changed:
     - If it changed, calculate the new sum and make the comparison.
     - If it didn't change, the new sum will be the same as the previous one.
- Do not delete multigroup files and folders when restarting a worker node, to reduce the need for file synchronization between cluster nodes.

We will start working on these improvements and all the results will be uploaded here.

**Comment by TomasTurina** [comment]
## Update 4

There is also a situation where there could be a performance issue when synchronizing multigroup files after a master reboot. Since the master deletes all multigroup files after reboot, this could cause a problem if there is a synchronization between file deletion and regeneration. Therefore, it is proposed to also solve this problem by avoiding the deletion of all the multigroup files and to make this mechanism more intelligent to delete/change only those files that have undergone some modification.

**Comment by davidjiglesias** [comment]
Related to https://github.com/wazuh/wazuh/issues/13603

**Comment by TomasTurina** [comment]
# Update

After all the changes introduced and described in the PR https://github.com/wazuh/wazuh/pull/15074, performance of `wazuh-remoted` during groups and multi-groups scans has largely improved.

## Tests

### Environment

- Wazuh manager
  - Ubuntu 22.04
  - 8GB RAM
  - 4 CPUs

### First scenario

- Groups
  - 2500 groups
  - 10000 group files
  - 2500 multi-groups
```
root@tomas-VirtualBox:/home/tomas/wazuh/wazuh/src# find /var/ossec/etc/shared/ -mindepth 1 -type d | wc -l
2500
root@tomas-VirtualBox:/home/tomas/wazuh/wazuh/src# find /var/ossec/etc/shared/ -mindepth 2 -type f | wc -l
10000
root@tomas-VirtualBox:/home/tomas/wazuh/wazuh/src# find /var/ossec/var/multigroups/ -mindepth 1 -type d | wc -l
2500
```

#### Initial scan (create all shared files)

- `master` branch
  - Time of processing: ~3min
  - Total disk usage: 3.9 GB

```
2022/11/09 11:28:22 wazuh-remoted[18496] manager.c:1624 at manager_init(): DEBUG: Running manager_init
2022/11/09 11:28:22 wazuh-remoted[18496] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:31:26 wazuh-remoted[18496] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  18500 be/4 wazuh        12.35 M      3.90 G  ?unavailable?  wazuh-remoted
```

- `14733_optimize_multigroups_cpu` branch
  - Time of processing: 1:40min
  - Total disk usage: 1.9 GB

```
2022/11/09 11:56:53 wazuh-remoted[41026] manager.c:1626 at manager_init(): DEBUG: Running manager_init
2022/11/09 11:56:53 wazuh-remoted[41026] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 11:58:33 wazuh-remoted[41026] manager.c:745 at c_files(): DEBUG: End updating shared files.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  41031 be/4 wazuh       180.00 K   1996.86 M  ?unavailable?  wazuh-remoted
```

#### Scan after restart (without changes)

- `master` branch
  - Time of processing: ~3min
  - Total disk usage: 3.9 GB

```
2022/11/09 11:37:53 wazuh-remoted[23855] manager.c:1624 at manager_init(): DEBUG: Running manager_init
2022/11/09 11:37:56 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:40:44 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  23859 be/4 wazuh        16.29 M      3.91 G  ?unavailable?  wazuh-remoted
```

- `14733_optimize_multigroups_cpu` branch
  - Time of processing: ~1min
  - Total disk usage: 100 MB

```
2022/11/09 12:02:22 wazuh-remoted[44220] manager.c:1626 at manager_init(): DEBUG: Running manager_init
2022/11/09 12:02:22 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:03:28 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  44225 be/4 wazuh         0.00 B    100.79 M  ?unavailable?  wazuh-remoted
```

#### Periodic scans (each 10 seconds)

- `master` branch
  - Time of processing: ~30s
  - Total disk usage: ~0 (only read operations)

```
2022/11/09 11:40:44 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:41:16 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
2022/11/09 11:41:17 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:41:44 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
2022/11/09 11:41:45 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:42:14 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
2022/11/09 11:42:15 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:42:42 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
2022/11/09 11:42:43 wazuh-remoted[23855] manager.c:691 at c_files(): DEBUG: Updating shared files sums.
2022/11/09 11:43:11 wazuh-remoted[23855] manager.c:713 at c_files(): DEBUG: End updating shared files sums.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  26447 be/4 wazuh      1156.00 K      4.00 K  ?unavailable?  wazuh-remoted
```

- `14733_optimize_multigroups_cpu` branch
  - Time of processing: ~4s
  - Total disk usage: ~0

```
2022/11/09 12:03:28 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:03:33 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
2022/11/09 12:03:38 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:03:42 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
2022/11/09 12:03:48 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:03:52 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
2022/11/09 12:03:58 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:04:02 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
2022/11/09 12:04:08 wazuh-remoted[44220] manager.c:723 at c_files(): DEBUG: Updating shared files.
2022/11/09 12:04:13 wazuh-remoted[44220] manager.c:745 at c_files(): DEBUG: End updating shared files.
```
```
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                  
  46091 be/4 wazuh         0.00 B     24.00 K  ?unavailable?  wazuh-remoted
```
