### ISSUE TITLE
Agent upgrade by WPK fails if any scan is running

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#14747]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | agent-upgrade  | Manager | Packages | Centos8 |

# Description

During testing for Issue [#3189](https://github.com/wazuh/wazuh-qa/issues/3189) it was found that when trying to upgrade a wazuh agent using wpk, if the agent that is being upgraded is running a scan (sca, rootcheck, etc), the upgrade process fails with a nondescript error. It would be recommended that the error message is improved to something that explains the actual cause and/or adding a note about this in the documentation.

## Results evidence
```
# /var/ossec/bin/agent_upgrade -a 003 -f /home/qa/wazuh_agent_v4.4.0_linux_x86_64.wpk

Upgrading...

Failed upgrades:
	Agent 003 status: Send open file error
```

**Comment by Nicogp** [comment]
## Update 12/06/2024

I have performed different tests and so far I have not been able to reproduce the error:

```
root@nico-VirtualBox:/home/nico/wazuh# /var/ossec/bin/agent_upgrade -v v4.7.4 -a 002

Upgraded agents:
        Agent 002 upgraded: Wazuh v4.7.0 -> v4.7.4
```
In the wazuh-agent I have configured sca, rootcheck, fim with a 1s period.

**Comment by Nicogp** [comment]
I have done more tests and have not been able to reproduce the error. 

Considering that it was not possible to reproduce the error in a local environment and that the mechanism of how the agent gets the WPK will be totally changed with the new communication protocol in 5.0 ([issue](https://github.com/wazuh/wazuh/issues/22677)), these error messages will be removed so I propose not to implement any change and close the issue.
