### ISSUE TITLE
Migrate cluster Integrity sync enhancements to 4.3

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14742]
## Description

Large environments can see their performance severely affected by timeout errors during file synchronization. 

In those cases, the synchronization task is canceled and started again a little later, but the files continue to be sent even if the worker does not use them because they are associated with a canceled task. Multiple improvements to address this issue were introduced in the following issue:
- https://github.com/wazuh/wazuh/issues/11945

However, these changes will not be applied until Wazuh version v4.4. For said reason, it is intended to migrate everything done in this issue to Wazuh 4.3, so that the problem is solved as soon as possible.

Testing and migrating system tests will be required to ensure the cluster still works properly.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
We have finally decided to keep this development for v4.4.0
