### ISSUE TITLE
`agent_upgrade` error when used in a worker node and with agents connected to a different node

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#14755]
|Wazuh version|Component|
|---|---|
| 4.3 | `agent_upgrade` CLI |

## Description

When we try to upgrade an agent (or an agents list) using the `agent_upgrade` CLI from a worker node, an error will be raised when that agent is connected to a different node.

Error:

```
root@wazuh-worker1:/# /var/ossec/bin/agent_upgrade -a 001

Upgrading...
Internal error: '001'
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 220, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 197, in main
    check_status(affected_agents=result.affected_items, result_dict=agents_versions,
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 160, in check_status
    result_dict[task_result['agent']]['new_version'] = args.version if args.version else agent.version
KeyError: '001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 227, in <module>
    if args.debug:
AttributeError: 'Namespace' object has no attribute 'debug'
```

Despite the error, the agent is upgraded correctly due to the fact that the exception is raised when trying to get the upgrade result.

The origin of the error is in the following function:

https://github.com/wazuh/wazuh/blob/cebdd5708b6759c84cbc409df7a670cf7f351619/framework/scripts/agent_upgrade.py#L52-L74

We cannot use this function because the worker's `global.db` does not contain information about agents connected to different nodes. The version must therefore be obtained with a distributed function.

Note: if the fix's target version is >=4.4, we must use the `forward_function` function (`core/cluster/utils.py`) in order to apply the fix. Note that in that case, we must also use the `forward_function` function instead of the `send_command` function. 

Apart from fixing this error, the issue also aims to review the following code, as there is a possible race condition (the version is obtained after the upgrade procedure started):

https://github.com/wazuh/wazuh/blob/cebdd5708b6759c84cbc409df7a670cf7f351619/framework/scripts/agent_upgrade.py#L186-L194

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Duplicated of https://github.com/wazuh/wazuh/issues/13846
