### ISSUE TITLE
Agent is not raising `integrity_clear` logs

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#14769]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | RSync | Agent | Packages | Linux/WindowsXP |

## Description
Working on the QA issue [3008](https://github.com/wazuh/wazuh-qa/issues/3008) when validating logs I found that the debug logs for the method `integrity_clear` is not appearing even though the method is working properly. This bug did not affect he functionality of the component, only debug logs.\
It was noticed that also the logs of `start sync` are not being raised.

## Evidences

https://user-images.githubusercontent.com/44633633/187469277-30322aab-3aed-4528-a486-739871333b0b.mp4

> Windows agent [ossec.log](https://github.com/wazuh/wazuh/files/9453889/ossec.log)

## Environment details
  | Module | VM Image | Extra Packages | Notes |
  | --------- | -------------- | -------- | -------- |
  | `wazuh-agent` | [dvgamerr/win-xp-sp3](https://app.vagrantup.com/dvgamerr/boxes/win-xp-sp3) | [Hotfix kb4024323](https://catalog.s.download.windowsupdate.com/d/csa/csa/secu/2017/06/windowsxp-kb4024323-x86-custom-enu_edb5a850bcbcc640c2b8c8aad3ab4d36a3b6fb26.exe) | |
  | `wazuh-manager`/`wazuh-agent` | [bento/centos-8](https://app.vagrantup.com/bento/boxes/centos-8) | [sqlite3](https://linuxhint.com/install-sqlite-centos-8/) - [python3](https://linuxize.com/post/how-to-install-python-on-centos-8/) |  |

## Steps to reproduce

<details><summary>Windows XP Hotfix case</summary>

On a Windows XP machine with a wazuh-agent and no hotfixes installed
   1. Edit the file `C:\Program Files\ossec-agent\local_internal_options.conf` to set the debug mode
       ```
      wazuh_modules.debug=2
      windows.debug=2
       ```
   2. Using the wazuh-ui `(C:\Program Files\ossec-agent\win32ui)` stop the wazuh-agent clicking _**manage -> stop**_
   3. Download and install the `hotfix` [`kb4024323`](https://catalog.s.download.windowsupdate.com/d/csa/csa/secu/2017/06/windowsxp-kb4024323-x86-custom-enu_edb5a850bcbcc640c2b8c8aad3ab4d36a3b6fb26.exe) from Microsoft Update [catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=SP3+XP)
   4. Start the wazuh-agent using the wazuh-ui _**manage -> start**_ and check the wazuh-manager database is updated
       >```
       > sql
       > sqlite3 /var/ossec/queue/db/<agentID>.db 'select * from sys_hotfixes;'`
          0|2022/08/26 15:02:59|KB4024323|3dcb55dc0cad431a6d9645475f4eb0a7d5b724e6
       >```
   5. Stop the wazuh-agent again and uninstall the hotfix.
   6. Start the wazuh-agent and check in the wazuh-manager database the hotfix is not listed
       >```
       > sql
       > sqlite3 /var/ossec/queue/db/<agentID>.db 'select * from sys_hotfixes;'`
       > ```
   7. Check in the logs of the wazuh-agent that the `syscollector` debug log of the `integrity_clear` method exists
       >```
       > Look in the file` C:\Program Files\ossec-agent\ossec.log` for a log like this
       > `2022/08/26 17:25:55 wazuh-modulesd:syscollector[55506] wm_syscollector.c:98 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_hotfixes","data":{....},"type":"integrity_check_clear"}`
       >```

</details>
   

<details><summary>Linux Port case</summary>

On a Centos-8 machine with a wazuh-agent installed and no ports opened
   1. Start a http server using the command:
       > python -m http.server
   2. Restart the wazuh-agent with the command `systemctl restart wazuh-agent`
   3. Check in the wazuh-manager database the opened port is listed:
       > use the command`sqlite3 /var/ossec/queue/db/<agentID>.db 'select * from sys_ports;'`
   4. Stop the http server (ctrl+c on the terminal running the server) and restart the wazuh-agent.
   5. Check in the wazuh-manager database the now closed port is not listed.
   6. Check in the logs of the wazuh-agent that the `syscollector` debug log of the `integrity_clear` method exists.
       > Look in the file `/var/ossec/logs/ossec.log` for a log like this:
       > 2022/08/26 17:25:55 wazuh-modulesd:syscollector[55506] wm_syscollector.c:98 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_ports","data":{....},"type":"integrity_check_clear"}

</details>

---
## Results
- **Current Result**
   The debug log of the execution of `integrity_clear` is not apprearing.
- **Expected Result**
   The debug log of the execution of `integrity_clear` should exist
    > Example of the expected log: 2022/08/26 17:25:55 wazuh-modulesd:syscollector[55506] wm_syscollector.c:98 at wm_sys_log(): DEBUG: Sync sent: {"component":"syscollector_ports","data":{....},"type":"integrity_check_clear"}

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/14769?planning-poker) with Zenhub @Damian-Mangold @MiguelazoDS @pereyra-m

**Comment by Dwordcito** [comment]
## DoD
- [ ] Receive callback logger and keep this as a static member.
- [ ] Manual test shutdown correct order.
- [ ] Add log calls for StartSync and Integrity check results.
- [ ] CI Check pass.

**Comment by Dwordcito** [comment]
It is moved to the product backlog until it has the 4.5 triage done.
