### ISSUE TITLE
Implement API endpoint to return restart status of all cluster nodes

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#14776]
|Wazuh version|Component|
|---|---|
| 4.4.0| API |

## Description

When we instruct the user to restart Wazuh because of a change in the configuration, rules, or decoders, we cannot ensure if the nodes reported are already restarted or if something happened during the restart.

For example, we cannot distinguish between a node restarted and a node that never restarted.

Having the reason for the restarting failure to tell the user what happened and how to troubleshoot the situation is important to improve the user experience.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

## Related issues

- https://github.com/wazuh/wazuh-kibana-app/issues/4277

**Comment by davidjiglesias** [comment]
Proper design and solution to be done in https://github.com/wazuh/wazuh/issues/14918
