### ISSUE TITLE
Fedora 34 should not use the RHEL 8 policy

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#14781]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | SCA | Manager/Agent | Packages/Sources | Fedora34 |

We found that Fedora 34 uses the RHEL 8 SCA policies, when it should use the ones from RHEL 9.

Fedora 34 is the base for CentOS Stream 9 on which RHEL 9 is based on, so it should use the same policies. This is indicated in the CentOS Stream 9  release notes:
https://blog.centos.org/2021/12/introducing-centos-stream-9/
![image](https://user-images.githubusercontent.com/19505384/187668068-1e86bad3-5fb0-4c58-add9-b6241852a6ea.png)

**Comment by snaow** [comment]
Fedora 34 should not use any SCA policy which is not fully created and designed and tested for Fedora 34. Not RHEL, not CentOS or any other version or distribution.

**Comment by 72nomada** [comment]
Removed Fedora reference to RHEL9 until there is a Fedora 34 CIS Benchmark. This issue will manage by SCA process 
- https://github.com/wazuh/wazuh/issues/14358

closing this one.
