### ISSUE TITLE
Message when deleting a group

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1478]
## Bug report

**OS**
_Ubuntu18_

**Wazuh version**
_3.7.0-3701_

**Install type**
_manager_

**Install method**
_packages_

Bug description
----------------
The message received at the time a group is deleted with `agent_groups` shows information about which agents are affected by this deletion, but it doesn't show all the agents. For example:

The agents with id `1` and `2` belong to `newgroup` group with id `2` as shown in the database:
```
sqlite> select * from belongs;
1|1
1|2
1|3
2|1
2|2
```

When removing `newgroup`, the only agent affected is `1` when it should show agents `1` and `2`.
```
# /var/ossec/bin/agent_groups -r -g newgroup
Do you want to remove the 'newgroup' group? [y/N]: y
All selected groups were removed
Affected agents: 001.
```

In other cases when only one agent belongs to a group, it describes that there are no agents affected by that group.

**Comment by TJOSERAFAEL** [comment]
Hi @cristgl ,

this is fixed in branch: https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement-hashing

Regards.
