### ISSUE TITLE
Change socket to provide `force_reconnect` response

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14797]
## Description

Right now, when the framework receives a request to reconnect any agent, it sends this message to the `queue/alerts/ar` queue:
```
'(msg_to_agent) [] N!S 001 force_reconnect'
```
In addition, no response is expected, only code `41` is obtained when running the `send(msg)` command:
https://github.com/wazuh/wazuh/blob/c001e5f1e74193a227a914621b2caa7504615b02/framework/wazuh/core/wazuh_queue.py#L75-L80

We are using this feature for the new TCP balancing mechanism in the cluster (#13195), but there is a problem: If the agent shows as active but it is actually disconnected (less than 10 minutes since unexpected disconnection), it is impossible for the framework to determine whether the reconnection request will be received by the agent. That information is needed so the cluster infers whether the mechanism is working correctly or if it should be stopped.
 
This issue proposes to investigate and implement (if feasible) a response that lets the framework know to which agents a reconnection request has actually been sent.

**Comment by TomasTurina** [comment]
This issue will remain on hold until we decide if the framework team needs it, and if so, we'll redesign the implementation to improve solution performance.

**Comment by davidjiglesias** [comment]
This solution is not finally needed.
