### ISSUE TITLE
Default group deleted from database

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1479]
## Bug report

**OS**
_Ubuntu18_

**Wazuh version**
_3.7.0-3701_

**Install type**
_manager_

**Install method**
_packages_

Bug description
--------
The default group can't be deleted as it says in the message received when trying to do so.

```
# /var/ossec/bin/agent_groups -r -g default
Do you want to remove the 'default' group? [y/N]: y
Error 1712: Default group is not removable.
```

Even so, the data contained in the database about this group is erased, the agents stop belonging to this group and the `agent.conf` and other configuration files file are not being sent.

**Comment by TJOSERAFAEL** [comment]
Hi @cristgl,

this bug is fixed in branch https://github.com/wazuh/wazuh/tree/dev-37-multigroup-improvement-hashing

Regards.
