### ISSUE TITLE
Reset admin password for wazuh kubernetes

### ISSUE THREAD

**Issue by akshanshshrivastava** [wazuh/wazuh#14795]
Wazuh version 4.3.6 Kubernetes Cluster

I am following this doc for k8s deployment for eks [](https://documentation.wazuh.com/current/deployment-options/deploying-with-kubernetes/) 

Hi Wazuh Team, 
I tried asking 3 times in slack community but no one is able to help me there so here I am and its my last hope.

Wazuh don't have any document for reseting password for k8s. All the other docs are for all in one deployment or for non-k8s deployments

This is the steps I am following which is working fine for `envs/local-env/` but not in `envs/eks`

1) Obtain hash password into indexer pod
outside pod:
`kubectl exec -it -n wazuh pod/wazuh-indexer-0 -- bash`

inside pod:
`export JAVA_HOME=/usr/share/wazuh-indexer/jdk`
 `bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh`
 
2) Insert new password and create a new hash. Replace admin value with new hash into `wazuh/indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml` file

3) Change value of password parameter into `wazuh/secrets/indexer-cred-secret.yaml` file, you need to encrypt the password with base64:
`echo -n <new_password> | base64`

4) Apply changes into your k8s cluster:
`kubectl apply -k envs/local-env/`

5) Add environment variables and run securityadmin script:
```
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl -arc -h localhost
```
6) After doing this you will be able to login with new password BUT the logs stops coming. For that you need to regenerate dashboard cert and indexer cert from the repository and apply the changes again `kubectl apply -k envs/local-env/`

7) You should be able to get the logs and All should work fine

This setup to reset password for wazuh in k8s works fine for `envs/local-env/`
BUT it doesn’t work for `envs/eks` . 
Doing the exact same steps will make my Master and Worker PODs in CrashLoop.
Please help me there

**Comment by teddytpc1** [comment]
The procedure to change the password is:

1- Obtain hash password in the indexer pod:
  - outside pod:
    ```BASH
    kubectl exec -it -n wazuh pod/wazuh-indexer-0 -- bash
    ```
  - inside pod:
    ```BASH
    export JAVA_HOME=/usr/share/wazuh-indexer/jdk
    bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh
    ```
    
2-  Insert the new password and create a new hash. Replace admin value with new hash into `wazuh/indexer_stack/wazuh-indexer/indexer_conf/internal_users.yml` file.
3- Change value of `password` parameter in the `wazuh/secrets/indexer-cred-secret.yaml` file. You need to encrypt the password with base64:
```BASH
echo -n <new_hash> | base64
```
4- Apply changes into your k8s cluster:
```BASH
kubectl apply -k envs/eks/
```
If this is your first start of the deployment, this is the end of the procedure, otherwise you must continue with the following tasks.

5- Add environment variables and run `securityadmin` script (from the Indexer pod):
```BASH
export INSTALLATION_DIR=/usr/share/wazuh-indexer
export OPENSEARCH_PATH_CONF=${INSTALLATION_DIR}/config
CACERT=$OPENSEARCH_PATH_CONF/certs/root-ca.pem
KEY=$OPENSEARCH_PATH_CONF/certs/admin-key.pem
CERT=$OPENSEARCH_PATH_CONF/certs/admin.pem
export JAVA_HOME=/usr/share/wazuh-indexer/jdk
bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -cd /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/ -nhnv -cacert  $CACERT -cert $CERT -key $KEY -p 9300 -icl
```
6- Restart (delete) the Wazuh manager pods (master and workers).
7- Clear cache and test yout new password
