### ISSUE TITLE
Vulnerability detection results are not synced across cluster nodes.

### ISSUE THREAD

**Issue by pyama86** [wazuh/wazuh#14809]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.6 | wazuh-cluster | Manager | Packages | ubuntu 22 |

I'm running a wazuh-cluster with multiple nodes. I have noticed that when the worker where the agent is housed is changed, the Vulnerability detection results disappear. Is it normal for this information to be out of sync?

**Comment by vikman90** [comment]
Hi @pyama86. Yes, it's designed to work this way.

- The agent synchronizes its inventory (files, SCA checks, installed packages, etc.) with the worker where it's connected.
- Vulnerability Detector runs on all workers and creates a vulnerability inventory for the agents connected to each one, using the installed packages list of each agent.
- API queries referred to agents are forwarded by the Cluster to the worker that had the agent connected most recently.

So, although the agent inventory is not synced across nodes, API calls are expected to return the most updated data.

Hope it helps.
Best regards.

**Comment by pyama86** [comment]
Thank you for your response.
I have one concern: I saw that 4.4 will add a balancing mechanism using least connection, in that case, won't the results of vulnerability scan be lost each time?
https://github.com/wazuh/wazuh/issues/13195

**Comment by vikman90** [comment]
Yes, agents need to resync their data with the worker when they are re-balanced.

Actually, we already set up load balancers with the least-connection algorithm, but sometimes agents get unbalanced, causing a high load in a few workers. This makes agents disconnect or unable to synchronize their data.

As stated at #13195, this development assumes that there is a load balancer set up. The task consists of re-balance agents when the connections are disproportionate. This will make those agents resync their data, but in return, the connections will be more stable.

**Comment by pyama86** [comment]
Thank you for your answer. Okay, I am not sure if my understanding is correct, but if the agent is rebalanced in the least connection, is it correct that the results of the vulnerability scan are not returned in the API or dashboard until the vulnerability scan is run again on the worker? Is that correct?

**Comment by vikman90** [comment]
Yes, sir, you're correct. Agents need to re-sync their data before it's available. Indeed, the goal is for agents to remain connected in a stable manner to the same manager for as long as possible.

Having the information centralized and available to all agents is a challenge that we will face soon: #8737.

**Comment by pyama86** [comment]
Thank you for your response. Thanks to you, I understand now.
