### ISSUE TITLE
Every AWS event read should appear in the archival storage 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#14808]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7| AWS module/Analysis engine | All | All | All |

Hello team,

After testing the Cloudwatch integration I observed that if the logs were read and stored in the AWS DB, these events won't appear in the archives files if we read them again.

This could complicate the troubleshooting of the integration and every event that the analysis engine read should appear in the archival data.

We should review if this is happening with other AWS integrations.

Regards,

Miguel Casares

**Comment by davidjiglesias** [comment]
After discussing with @MiguelCasaresRobles we agreed that this issue is not needed.
