### ISSUE TITLE
Upgrade from 4.2.7 to 4.4 doesn't work correctly in Google cloud VM

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#14833]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.7 and 4.4 | upgrade| Manager | Packages | Centos 7 Google Cloud |

# Description

During testing for Issue [#14018](https://github.com/wazuh/wazuh/issues/14018) it was found that when trying to upgrade a wazuh manager from 4.2.7 Wazuh version to 4.4 Wazuh version it takes between 25 and 40 minutes to be completed. 

## Steps to reproduce:

1- Have a CentOS 7 in Google Cloud.
2- Install Wazuh manager, version 4.2.7
3- Upgrade Wazuh manager to 4.4 (I used this [package](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-08.09.0.withoutmodulesdfix.x86_64.rpm)).
  ```
  curl -O <4.4 package>
  yum install <4.4 package> -y
  ```

4- Wait for the upgrade:
- It takes too long time to be completed 
- If you execute the command `/var/ossec/bin/wazuh-control info` while the upgrade is in progress, the output shows that the wazuh version 4.4 is installed.

## Evidence
<details><summary>Upgrade task</summary>

  ![upgrade 4 2 7 to 4 4 - 3](https://user-images.githubusercontent.com/26927338/189215731-666db713-7d1a-4e10-872c-dea8dcd9d81f.png)

</details>

<details><summary>/var/ossec/bin/wazuh-control info</summary>

  ![upgrade 4 2 7 to 4 4 - 2](https://user-images.githubusercontent.com/26927338/189216521-50d2aee8-c8f3-4e5f-b50f-de34f314547c.png)

</details>

<details><summary>Upgrade task still running after some minutes</summary>

  ![upgrade 4 2 7 to 4 4 - 4](https://user-images.githubusercontent.com/26927338/189217312-2e636049-f596-41f5-bb57-48655ec5d244.png)

  ![upgrade 4 2 7 to 4 4 - 6](https://user-images.githubusercontent.com/26927338/189216930-1e873097-1651-477a-930b-52436d1f6bb5.png)

</details>

<details><summary>Upgrade task completed</summary>

  ![upgrade 4 2 7 to 4 4 - 7](https://user-images.githubusercontent.com/26927338/189217144-185410b5-2b96-4dbd-8adf-9e98969d30a8.png)

</details>

## Notes

- I tested with vagrant VMs  CentOS 7 and CentOS 8 and the upgrade works correctly
- I tested with two packages, 4.4 with this issue changes  https://github.com/wazuh/wazuh/issues/14018 and 4.4 without issue changes

**Comment by vikman90** [comment]
Probably related to #14175.
