### ISSUE TITLE
Add error messages to integration scripts

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1483]
## Bug report

**Wazuh version**
3.7.0-3702

**Install type**
Manager

**Log sample**

```
2018/09/28 16:38:29 ossec-integratord: INFO: Started (pid: 24921).
2018/09/28 16:38:29 ossec-integratord: INFO: Enabling integration for: 'slack'.
```

Bug description
----------------
We must write in the log the errors related to the integration's modules. 

For example, if we don't have installed `request` and we want to run the _Slack_ integration module we **must** execute the script manually to get the error as it's not written on the wazuh's log. This can be confusing for the users because it won't work and they probably won't know why.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/2143 solves the issue
