### ISSUE TITLE
Review and refactor init_db and create_table in AWS module

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#14851]
| Affected integration |
|---|
| AWS|

## Description
The `create_table` and `init_db` methods, defined in the `WazuhIntegration` and `AWSBucket` classes, used for db creation and initialization differ only in the arguments passed to them but not in their behavior. They should be reviewed, as well as their uses, to determine if these methods can be unified in the `WazuhIntegration` class which is the superclass of `AWSBucket` and `AWSService`.

https://github.com/wazuh/wazuh/blob/1270b56bcda5fde39c31cae95c1cd12aad73a5b2/wodles/aws/aws_s3.py#L340-L362

https://github.com/wazuh/wazuh/blob/1270b56bcda5fde39c31cae95c1cd12aad73a5b2/wodles/aws/aws_s3.py#L621-L637

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by nico-stefani** [comment]
# Issue Update

Seeing the actual implementation, it is possible to remove the implementations in the child class (`AWSBucket`) and use those inherited from `WazuhIntegration`.
