### ISSUE TITLE
Upgrading macOS agent via WPK returns timeout

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#14856]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.3.x  | Manager/Agent | Packages | CentOS 8/ macOS Monterey|

## Description

After the testing performed in https://github.com/wazuh/wazuh-qa/issues/3260 we have been able to see that, when we try to update a macOS agent with WPK, we receive:

```
Timeout reached while waiting for the response from the agent
```

However, the update is executed later and hangs, failing to update.

## Evidences

The testing performed for different versions and its result can be found [here](https://github.com/wazuh/wazuh-qa/issues/3260#issuecomment-1242122836).

## Steps to reproduce

1. Prepare an environment with a 4.3.7 manager and a 4.3.x macOS agent.

2. Change the `wpk_root.pem` certificate. The certificate you need can be found [here](https://github.com/wazuh/wazuh/pull/14696).

3. Upgrade the agent using `agent_upgrade` or the API:

  - `/var/ossec/bin/agent_upgrade -a 001 -v v4.3.7`.
  - `curl -k -X PUT "https://localhost:55000/agents/upgrade?agents_list=001&upgrade_version=v4.3.7&pretty=true" -H "Authorization: Bearer $TOKEN" `

4. Check the results and `/Library/Ossec/logs/upgrade.log`.

**Comment by nmkoremblum** [comment]
This could be due to the agent's connectivity slowness, please try increasing the [task-timeout](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/task-manager.html#task-timeout) parameter to "30m" (as by default is 15 minutes).

**Comment by juliamagan** [comment]
We are closing this issue because as @nmkoremblum and @rauldpm  have said, it was a problem with the environment. The results have been updated in https://github.com/wazuh/wazuh-qa/issues/3260#issuecomment-1246565219.
