### ISSUE TITLE
Release 4.3.8 - Release Candidate 1 - Register 

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#14866]
### Packages tests metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |  #14827|
| **Main packages metrics issue** |  #14862 |
| **Version** | 4.3.8                              |
| **Release candidate #** | RC1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.8-rc1 |

---

| Test | AMD64 Build |
| -- | -- |
| Tier | https://ci.wazuh.info/job/Test_registration_tier/ |

---

| System | Test Result | 
| :-- | :--: |
| CentOS 8 | 🟢 | 
| CentOS 7 | 🟢 | 
| CentOS 6 | 🟢 | 
| CentOS 5 | 🟢 |
| Debian 10 | 🟢 |
| Debian 9 | 🟢 | 
| Debian 8 | 🟢 | 
| Debian 7 | 🟢 | 
| Fedora 32 | 🟢 |
| Fedora 31 | 🟢 |
| Ubuntu Focal | 🟢 |
| Ubuntu Bionic | 🟢 |
| Ubuntu Xenial | 🟢 |
| Ubuntu Precise | 🟢 |
| Ubuntu Trusty | 🟢 |
| Amazon Linux 1 | 🟢 |
| Amazon Linux 2 | 🟢
| Oracle Linux 6 | 🟢 |
| Oracle Linux 7 | 🟢 |
| Oracle Linux 8 | 🟢 |
| OpenSuse Tumbleweed  | 🟢 | 
| Redhat 6 | 🟢 |
| Redhat 7 | 🟢 |
| Redhat 8 | 🟢 |

Legend:
Pending/In progress: 🕐 
Test not launched: ⚫
Test failed: 🔴 
Test success: 🟢 
Need review: 🟡

**Comment by rauldpm** [comment]
### Analysis report

- No error found in the tests performed.
- openSUSE Tumbleweed build error is related to wrong revision parameter. Relaunched https://ci.wazuh.info/job/Test_registration/8031/
