### ISSUE TITLE
No SCA rule for Ubuntu 21.04

### ISSUE THREAD

**Issue by hillbun** [wazuh/wazuh#14876]
My OS is Ubuntu 21.04, When  I start wazuh agent , it shows message:

sca: INFO: Skipping policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml': 'Check Ubuntu version.'

there is only one file cis_ubuntu22-04.yml under /var/ossec/ruleset/sca/

Please advice.

**Comment by FrancoRivero** [comment]
Hi @hillbun,
Thanks for using Wazuh !
`Ubuntu 21.04` is not an LTS version of Ubuntu so [CIS](https://www.cisecurity.org/benchmark/ubuntu_linux) does not provide any information about `Ubuntu 21.04`. 
However, we may have a solution to check it with the Ubuntu 22.04 benchmark, so you will be able to use SCA with your system and with the latest information about Ubuntu.
To do this we can modify the rule to change the place where the information is searched, you must follow the following steps to change the rule:

1. Clone the existent rule executing `cp /var/ossec/ruleset/sca/cis_ubuntu22-04.yml  /var/ossec/ruleset/sca/cis_ubuntu21-04.yml`
2. Write a new policy inside `ossec.conf`
``` xml
<sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
    <policies>
           <policy>/var/ossec/ruleset/sca/cis_ubuntu21-04.yml</policy>
    </policies>
</sca>
```
3. Execute `sed -i 's/etc/os-release -> r:Ubuntu 22.04/etc/os-release -> r:Ubuntu 21.04"/g' /var/ossec/ruleset/sca/cis_ubuntu21-04.yml`
4. Execute  `/var/ossec/bin/wazuh-control restart`

With this step you are modifying where to look for the policy and using the Ubuntu 22.04 policy in Ubuntu 21.04.
I hope it works for you ! 
Regards

**Comment by hillbun** [comment]
it works , thanks

**Comment by FrancoRivero** [comment]
Great. Glad to help. We're here for you if you need anything else.
Regards
