### ISSUE TITLE
Release 4.3.8 - Release Candidate 1 - E2E UX tests - Centralized configuration and  Agent groups

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#14884]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |    Centralized configuration - Agent groups               |
| **Category**            |    Configuration                                 |
| **Deployment option**   |  Installation guide                                          |
| **Main release issue**  |   https://github.com/wazuh/wazuh/issues/14827                                           |
| **Main E2E UX issue**  |   https://github.com/wazuh/wazuh/issues/14828                                           |
| **Release candidate #** |  RC1                                         |

## Test description

Test the functionality of agent groups for centralized configuration:
- Try different groups for different OS
- Try tags in the same group, to apply different blocks of configuration to different OS or agents.
- Try creating groups with different files of different types and sizes (try to reach the limits)
- Check if propagation times are acceptable
- Other potential tests

## Installation
- Wazuh Manager (indexer+dashboard+server)
  - Single node Amazon Linux 2 [Installation assistant](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html) 
- Wazuh Agent
  - Wazuh WUI one-liner deploy IP GROUP (created beforehand)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

After testing all thoroughly. Deploying the environment and pushing different configurations to the agents these were the results of the tests: 

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
| :green_circle:  | [Install central components with Installation Assistant ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247085853)(@jftuduri ) | | |
| :green_circle:  | [Wazuh WUI one-liner deploy, predefined group](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247190092) (@jftuduri ) | | |
| :green_circle:  | [Change agent group](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247274349) (@jftuduri ) | | |
| :green_circle:  | [Centralized agent labels ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247284022)(@jftuduri ) | | |
| :green_circle:  | [Wazuh WUI one-liner deploy, predefined group, apply centralized configuration on deployment](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248069268) (@jftuduri ) | | |
| :green_circle:  | [Apply multiple groups centralized configuration](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248309904) (@jftuduri ) | | |
| :green_circle:  | [Watching deletion of var/multigroups/ directory ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248617788)(@jftuduri ) | | |
| :green_circle:  | [Removing agent from groups, removes centralized configuration ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248442727)(@jftuduri ) | | |
| :green_circle:  |[ Install central components with Installation Assistant ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247976326)(@NahuFigueroa97 ) | | |
| :green_circle:  | [Wazuh WUI one-liner deploy, predefined group ](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1247988403)(@NahuFigueroa97) | | |
| :green_circle:  | [Change agent group](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248425750) (@NahuFigueroa97 ) | | |
| :green_circle:  | [Centralized agent labels](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248442675) (@NahuFigueroa97 ) | | |
| :green_circle:  | [Apply multiple groups centralized configuration](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248496822) (@NahuFigueroa97 ) | | |
| :green_circle:  | [Wazuh WUI one-liner deploy, predefined group, apply centralized configuration on deployment](https://github.com/wazuh/wazuh/issues/14884#issuecomment-1248475012) (@NahuFigueroa97 ) | | |

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @vikman90 
- [x] @davidjiglesias
- [x] @jnasselle

**Comment by jftuduri** [comment]
##   :green_circle: Test: Wazuh WUI one-liner deployDeploy a linux agent  with Wazuh WUI one-liner, predefined group

|Component|Installation|Operating system|
|---|---|---|
|Wazuh Agent|Wazuh WUI one-liner|Windows 11|

### Configuration 

Created the group `E2ETest`.

###  Installation steps

- Followed steps on the UI for deploying a Windows agent:
![Screenshot 2022-09-14 at 15-32-50 Wazuh - Wazuh](https://user-images.githubusercontent.com/7939712/190238498-4ea884aa-be24-41a9-94ca-22550fffe719.png)

- Changed the link on the provided command to `pre-release`
`Invoke-WebRequest -Uri https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.8-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.8.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.8.msi /q WAZUH_MANAGER='192.168.31.177' WAZUH_REGISTRATION_SERVER='192.168.31.177' WAZUH_AGENT_GROUP='E2ETest'`
  
3 - Agent started and enrolled successfully: 

![Screenshot from 2022-09-14 15-41-57](https://user-images.githubusercontent.com/7939712/190239857-2c5f0a1a-2e77-4b47-999f-c7dbdf2c8e4b.png)

**Comment by jftuduri** [comment]
##   :green_circle: Test: Change agent group

### Configuration 
Created the group `Windows_Agents`.
As an extra test tried to create another group with the same name. An error message popped up, as expected:
![Create existing group - error ok](https://user-images.githubusercontent.com/7939712/190256639-d16f1dc3-0aa0-4fe8-9047-eb38549547b1.png)
 ### Steps
- Added the Windows agent to the new group:
![Screenshot from 2022-09-14 16-42-51](https://user-images.githubusercontent.com/7939712/190256756-c84211dd-3cd4-42ad-a20c-f01b7802af1c.png)
- The agent belongs to both groups:
![Screenshot from 2022-09-14 16-46-19](https://user-images.githubusercontent.com/7939712/190256836-f75528a9-4d1d-42aa-ac2e-a4a5be94501e.png)
- Then removed the agent from E2ETest and the change is reflected in the dashboard:
![Screenshot from 2022-09-14 16-52-58](https://user-images.githubusercontent.com/7939712/190256966-ed3cc2c4-e049-430f-900d-cfe0ff7ad01c.png)

**Comment by jftuduri** [comment]
##   :green_circle: Test: Centralized agent labels

### Configuration
 Configured a label to the group Windows_Agents, through agent.conf
![Screenshot from 2022-09-14 17-39-38](https://user-images.githubusercontent.com/7939712/190258092-2cd655d4-be9c-4ff9-a7c1-ee0dfa35bf95.png)

### Result
After applying the new configuration to the group, new alerts are labeled correctly:
![image](https://user-images.githubusercontent.com/7939712/190258795-458b7da4-9ab6-4b8b-a489-3ae2c46030f8.png)

**Comment by NahuFigueroa97** [comment]
## :green_circle:  Test 1: Install central components with Installation Assistant

#### Installation script `wazuh-install.sh` was modified in the following way to install the correct packages for this test:
```
readonly repogpg="https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH"
readonly repobaseurl="https://packages-dev.wazuh.com/pre-release"
readonly reporelease="unstable"
readonly filebeat_wazuh_module="${repobaseurl}/filebeat/wazuh-filebeat-0.2.tar.gz"
readonly bucket="packages-dev.wazuh.com"
readonly repository="pre-release"

readonly wazuh_major="4.3"
readonly wazuh_version="4.3.8"
```
#### :green_circle: Indexer Installation ([Documentation](https://documentation-dev.wazuh.com/4.3/installation-guide/wazuh-indexer/installation-assistant.html))
|Component|Installation|Operating system|
|---|---|---|
|Indexer|Installation assistant|Amazon Linux 2|

##### config.yml:

![Captura desde 2022-09-14 21-41-48](https://user-images.githubusercontent.com/63238635/190390499-6fb25993-d8e9-40d3-af16-f7a316459c64.png)

##### Generate config files

![Captura desde 2022-09-15 08-19-09](https://user-images.githubusercontent.com/63238635/190390867-1becf70b-0d46-415b-9937-99954c380d15.png)


##### Install indexer node

![Captura desde 2022-09-15 08-20-09](https://user-images.githubusercontent.com/63238635/190390995-8f11f889-41a5-42a7-814a-b1bb2e314c3c.png)

##### Cluster initialization

![Captura desde 2022-09-15 08-20-56](https://user-images.githubusercontent.com/63238635/190391140-2126e53c-0b6a-4fcc-b620-7c54243a6771.png)


#### :green_circle: Server Installation ([Documentation](https://documentation-dev.wazuh.com/4.3/installation-guide/wazuh-server/installation-assistant.html))
|Component|Installation|Operating system|
|---|---|---|
|Server|Installation assistant|Amazon Linux 2|

![Captura desde 2022-09-15 08-22-07](https://user-images.githubusercontent.com/63238635/190391322-e651660c-3517-4d60-9de3-831e177b76df.png)


#### :green_circle: Dashboard Installation ([Documentation](https://documentation-dev.wazuh.com/4.3/installation-guide/wazuh-dashboard/installation-assistant.html))
|Component|Installation|Operating system|
|---|---|---|
|Dashboard|Installation assistant|Amazon Linux 2|

![Captura desde 2022-09-15 08-23-13](https://user-images.githubusercontent.com/63238635/190391516-5df75ac4-5e9a-4707-9ba8-3e5deccefb2f.png)


<details><summary>

##### Print generated passwords
</summary>

![Captura desde 2022-09-15 08-27-15](https://user-images.githubusercontent.com/63238635/190392319-60de0637-2ff5-4d4f-8ec3-376b977621b0.png)

</details>

##### Dashboard up and running

![Captura desde 2022-09-15 08-30-27](https://user-images.githubusercontent.com/63238635/190392840-df791c34-b163-4b64-a8fa-39b4013c25e3.png)

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Wazuh WUI one-liner deploy, predefined group

|Component|Installation|Operating system|
|---|---|---|
|Wazuh Agent|Wazuh WUI one-liner|Windows 11|

### Configuration 

Created the group `E2ETest`.

###  Installation steps

- Followed steps on the UI for deploying a Windows agent:
![Captura desde 2022-09-14 22-39-36](https://user-images.githubusercontent.com/63238635/190394727-7fb450be-1044-4250-8a7b-c183bdd80459.png)
![Captura desde 2022-09-14 22-40-16](https://user-images.githubusercontent.com/63238635/190394773-a53a9aa2-2d55-42fa-91d5-240b4218a46e.png)


- Changed the link on the provided command to `pre-release`
`Invoke-WebRequest -Uri https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.3.8-1.msi -OutFile ${env:tmp}\wazuh-agent-4.3.8.msi; msiexec.exe /i ${env:tmp}\wazuh-agent-4.3.8.msi /q WAZUH_MANAGER='192.168.31.177' WAZUH_REGISTRATION_SERVER='192.168.31.177' WAZUH_AGENT_GROUP='E2ETest'`
  
3 - Agent started and enrolled successfully, in the correct group: 

![Screenshot from 2022-09-14 15-41-57](https://user-images.githubusercontent.com/7939712/190239857-2c5f0a1a-2e77-4b47-999f-c7dbdf2c8e4b.png)

**Comment by jftuduri** [comment]
##   :green_circle: Test: Wazuh WUI one-liner deploy, predefined group, apply centralized configuration on deployment

**Comment by jftuduri** [comment]
##   :green_circle: Test: Apply multiple groups centralized configuration

### Configuration
 - Agent Id 002 was assigned to groups `E2ETest` and `Windows_Agents`:
![Screenshot from 2022-09-15 12-35-27](https://user-images.githubusercontent.com/7939712/190448993-a7b62829-1919-47d8-ad7e-14c99c2d9e00.png)

- Group `Windows_Agents` was configured with label `Research`:

```
<agent_config>
	<!-- Shared agent configuration here -->
	<labels>
		<label key="area">Research</label>
	</labels>
</agent_config>
```
- Group 'E2ETest' was configured with label `TEST_LABEL`, and file monitoring for folders `C:/e2e_fim_test_1` (realtime) and `C:/e2e_fim_test_2`:
```
<agent_config>
	<!-- Shared agent configuration here -->
	<labels>
		<label key="group">TEST LABEL</label>
	</labels>
	
	<syscheck>
           <disabled>no</disabled>
           <scan_on_start>yes</scan_on_start>
           <frequency>300</frequency>
           <directories check_all="yes" realtime="yes" report_changes="yes">C:/e2e_fim_test_1</directories>
           <directories check_all="yes">C:/e2e_fim_test_2</directories>
        </syscheck>

</agent_config>
```

### Results
- Alerts generated by Agent 002 have both labels correctly applied:
![Screenshot from 2022-09-15 12-54-21](https://user-images.githubusercontent.com/7939712/190450708-a3a9d19f-1595-48af-b9d7-6603034ff091.png)

- Corresponding FIM alerts are generated correctly, with both labels applied:
![Screenshot from 2022-09-15 13-00-32](https://user-images.githubusercontent.com/7939712/190452269-66cab2ae-0f96-48ed-8176-053759d5e23f.png)

![Screenshot from 2022-09-15 13-06-09](https://user-images.githubusercontent.com/7939712/190453180-6fd9e750-6729-49a4-9a7b-52ae3d8ad24a.png)

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Change agent group

### Configuration 
Created the group `Windows_Agents`.
As an extra test tried to create another group with the same name. An error message popped up, as expected:
![Captura desde 2022-09-15 14-57-00](https://user-images.githubusercontent.com/63238635/190476402-ad1e3b01-437d-4b4a-8a49-8ea1db10f5ba.png)

 ### Steps
- Added the Windows agent to the new group:
- The agent belongs to both groups:

- Then removed the agent from E2ETest and the change is reflected in the dashboard:

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Centralized agent labels

### Configuration
 Configured a label to the group Windows_Agents, through agent.conf

### Result
After applying the new configuration to the group, new alerts are labeled correctly:

**Comment by jftuduri** [comment]
##   :green_circle: Test: Removing agent from groups, removes centralized configuration

### Configuration
- Agent id 002 assigned to groups `Windows_Agents` and `E2ETest`
- Group `Windows_Agents` was configured with label `Research`:

```
<agent_config>
	<!-- Shared agent configuration here -->
	<labels>
		<label key="area">Research</label>
	</labels>
</agent_config>
```
- Group 'E2ETest' was configured with label `TEST_LABEL`, and file monitoring for folders `C:/e2e_fim_test_1` (realtime) and `C:/e2e_fim_test_2`:
```
<agent_config>
	<!-- Shared agent configuration here -->
	<labels>
		<label key="group">TEST LABEL</label>
	</labels>
	
	<syscheck>
           <disabled>no</disabled>
           <scan_on_start>yes</scan_on_start>
           <frequency>300</frequency>
           <directories check_all="yes" realtime="yes" report_changes="yes">C:/e2e_fim_test_1</directories>
           <directories check_all="yes">C:/e2e_fim_test_2</directories>
        </syscheck>

</agent_config>
```
- Agent already configured with these settings.

### Test 1 - Remove agent 002 from group Windows_Agents
-Using the WUI remove agent 002 from group Windows_Agents
![Screenshot from 2022-09-15 14-54-26](https://user-images.githubusercontent.com/7939712/190478167-ad2f3fd1-ea8f-4614-a44e-5c026c1653f8.png)
-The agent receives the configuration almost immediately
![Captura de pantalla remove group 1](https://user-images.githubusercontent.com/7939712/190478517-5d15689d-8161-4a39-a794-52e661a56352.png)
-After the agent restarts with the new configuration, the alerts no longer include the label `Research` that corresponded to the group `Windows_Agents`: 
![Screenshot from 2022-09-15 15-13-01](https://user-images.githubusercontent.com/7939712/190479638-940cbdab-f291-43e1-8885-b0e248c62784.png)

**Comment by jftuduri** [comment]
##   :green_circle: Test: Removing agent from group, configuration propagation time

### Configuration
- Agent id 002 assigned to group `E2ETest`


- Group 'E2ETest' was configured with label `TEST_LABEL`, and file monitoring for folders `C:/e2e_fim_test_1` (realtime) and `C:/e2e_fim_test_2`:

```
<agent_config>
	<!-- Shared agent configuration here -->
	<labels>
		<label key="group">TEST LABEL</label>
	</labels>
	
	<syscheck>
           <disabled>no</disabled>
           <scan_on_start>yes</scan_on_start>
           <frequency>300</frequency>
           <directories check_all="yes" realtime="yes" report_changes="yes">C:/e2e_fim_test_1</directories>
           <directories check_all="yes">C:/e2e_fim_test_2</directories>
        </syscheck>

</agent_config>
```

- Agent already configured with these settings.

### Test 1 - Remove agent 002 from group `E2ETest`
- Using the WUI removed agent 002 from group E2ETest at `2022/09/15 15:23:03`
- The agent receives the configuration 3 seconds later:
![Captura de pantalla (6)_cropped (1)](https://user-images.githubusercontent.com/7939712/190483220-2f579011-bef3-4de4-a604-cec8ff0b5d65.png)

- After the agent restarts with the new configuration, the alerts no longer include the label `TEST LABEL` that corresponded to the group `E2ETest`: 

![Screenshot from 2022-09-15 15-29-16](https://user-images.githubusercontent.com/7939712/190483327-0ce0a068-3efc-47ee-b6bf-4349541ce4cd.png)

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Apply multiple groups centralized configuration

### Configuration
 - Agent Id 002 was assigned to groups `E2ETest` and `Windows_Agents`:

- Group `Windows_Agents` was configured with label `Research`:

- Group 'E2ETest' was configured with label `TEST_LABEL`, and file monitoring for folders `C:/e2e_fim_test_1` (realtime) and `C:/e2e_fim_test_2`:

### Results
- Alerts generated by Agent 002 have both labels correctly applied:


- Corresponding FIM alerts are generated correctly, with both labels applied:


- Checking agent 002 labels configuration on the WUI shows the correct labels:

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Apply multiple groups centralized configuration

### Configuration
 - Agent Id 002 was assigned to groups `E2ETest` and `Windows_Agents`:


- Group `Windows_Agents` was configured with label `Research`:
<details><summary><b>Windows_Agents agent.conf</b></summary>


</details>

- Group 'E2ETest' was configured with label `TEST_LABEL`, and file monitoring for folders `C:/e2e_fim_test_1` (realtime) and `C:/e2e_fim_test_2`:

<details><summary><b>E2ETest agent.conf</b></summary>

</details>

### Results
- Alerts generated by Agent 002 have both labels correctly applied:


- Corresponding FIM alerts are generated correctly, with both labels applied:

- Checking agent 002 labels configuration on the WUI shows the correct labels:

**Comment by jftuduri** [comment]
##   :large_blue_circle: Test: Watching `var/multigroups/` directory [in progress]

- According to PR #14184, managers acting as worker nodes should not delete the multi-group files on restart. As the configuration on the current test is a single node (no worker nodes) the multi-group files should be deleted and regenerated on restart.


```
[root@MiWiFi-R4AC-srv ossec]# stat var/multigroups/
  File: ‘var/multigroups/’
  Size: 38              Blocks: 0          IO Block: 4096   directory
Device: 801h/2049d      Inode: 52197864    Links: 4
Access: (0770/drwxrwx---)  Uid: (  994/   wazuh)   Gid: (  992/   wazuh)
Access: 2022-09-13 15:56:49.000000000 +0000
Modify: 2022-09-15 14:49:50.846041255 +0000
Change: 2022-09-15 14:49:50.846041255 +0000
 Birth: -
[root@MiWiFi-R4AC-srv ossec]# bin/wazuh-control restart
2022/09/15 15:20:11 wazuh-remoted[13407] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/09/15 15:20:11 wazuh-remoted[13407] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/09/15 15:20:11 wazuh-remoted[13407] main.c:148 at main(): DEBUG: This is not a worker
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.8 Stopped
Starting Wazuh v4.3.8...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/09/15 15:20:16 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2022/09/15 15:20:20 wazuh-remoted[13740] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/09/15 15:20:20 wazuh-remoted[13740] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/09/15 15:20:20 wazuh-remoted[13740] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
[root@MiWiFi-R4AC-srv ossec]# stat var/multigroups/
  File: ‘var/multigroups/’
  Size: 38              Blocks: 0          IO Block: 4096   directory
Device: 801h/2049d      Inode: 52197864    Links: 4
Access: (0770/drwxrwx---)  Uid: (  994/   wazuh)   Gid: (  992/   wazuh)
Access: 2022-09-13 15:56:49.000000000 +0000
Modify: 2022-09-15 15:20:20.479082750 +0000
Change: 2022-09-15 15:20:20.479082750 +0000
 Birth: -
[root@MiWiFi-R4AC-srv ossec]# date
Thu Sep 15 15:20:36 UTC 2022
```

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Watching deletion of `var/multigroups/` directory

- According to PR #14814, managers acting as worker nodes should not delete the multi-group files on restart. As the configuration on the current test is a single node (no worker nodes) the multi-group files should be deleted and regenerated on restart.

### Steps
- Setup inotifywait to wath `var/multigroups`:
`inotifywait -m --timefmt '%F %T' --format '%T %w%f %e' var/multigroups`
- Restart manager:
```
[root@MiWiFi-R4AC-srv ossec]# bin/wazuh-control restart
2022/09/15 21:33:26 wazuh-remoted[2139] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/09/15 21:33:26 wazuh-remoted[2139] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/09/15 21:33:26 wazuh-remoted[2139] main.c:148 at main(): DEBUG: This is not a worker
wazuh-clusterd not running...
Killing wazuh-modulesd...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.3.8 Stopped
Starting Wazuh v4.3.8...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2022/09/15 21:33:30 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
2022/09/15 21:33:34 wazuh-remoted[2476] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2022/09/15 21:33:34 wazuh-remoted[2476] main.c:130 at main(): DEBUG: Wazuh home directory: /var/ossec
2022/09/15 21:33:34 wazuh-remoted[2476] main.c:148 at main(): DEBUG: This is not a worker
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
Started wazuh-modulesd...
Completed.
```
- The manager was restarting at `2022/09/15 21:33:34`
- inotifywait shows that the contents of var/multigroups get deleted and recreated, in this case there was only one subdirectory, `b9fb424b`:
  - `2022-09-15 21:33:34 var/multigroups/b9fb424b DELETE,ISDIR`
  - `2022-09-15 21:33:34 var/multigroups/b9fb424b CREATE,ISDIR`

<details><summary><b>Full inotify capture</b></summary>

```
[root@MiWiFi-R4AC-srv ossec]# inotifywait -m --timefmt '%F %T' --format '%T %w%f %e' var/multigroups
Setting up watches.
Watches established.
2022-09-15 21:33:26 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:26 var/multigroups/ OPEN,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:26 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:26 var/multigroups/ CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:34 var/multigroups/ OPEN,ISDIR
2022-09-15 21:33:34 var/multigroups/ ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b DELETE,ISDIR
2022-09-15 21:33:34 var/multigroups/ ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/ CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b CREATE,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:34 var/multigroups/ OPEN,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:34 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:34 var/multigroups/ CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:36 var/multigroups/ OPEN,ISDIR
2022-09-15 21:33:36 var/multigroups/ ACCESS,ISDIR
2022-09-15 21:33:36 var/multigroups/ ACCESS,ISDIR
2022-09-15 21:33:36 var/multigroups/b9fb424b OPEN,ISDIR
2022-09-15 21:33:36 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:36 var/multigroups/b9fb424b ACCESS,ISDIR
2022-09-15 21:33:36 var/multigroups/b9fb424b CLOSE_NOWRITE,CLOSE,ISDIR
2022-09-15 21:33:36 var/multigroups/ CLOSE_NOWRITE,CLOSE,ISDIR 
```
</details>

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Watching deletion of `var/multigroups/` directory

- According to PR #14814, managers acting as worker nodes should not delete the multi-group files on restart. As the configuration on the current test is a single node (no worker nodes) the multi-group files should be deleted and regenerated on restart.

### Steps
- Setup inotifywait to wath `var/multigroups`:
`inotifywait -m --timefmt '%F %T' --format '%T %w%f %e' var/multigroups`
- Restart manager:

- The manager was restarting at `2022/09/15 21:33:34`
- inotifywait shows that the contents of var/multigroups get deleted and recreated, in this case there was only one subdirectory, `b9fb424b`:
