### ISSUE TITLE
The "use_geoip" option has no apparent effect.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1489]
## Bug report

**OS**
_n/a_

**Wazuh version**
_master_

**Wazuh API version**
_n/a_

**Install type**
_manager/agent_

Bug description
----------------

When wazuh is compiled with [`LIBGEOIP_ENABLED`](https://github.com/wazuh/wazuh/blob/master/src/config/alerts-config.c#L61) and [`use_geoip`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html#use-geoip) is set to `yes`, the [code](https://github.com/wazuh/wazuh/blob/master/src/config/alerts-config.c#L65) sets   `Config->loggeoip = 1`.

However, that config value does not appear to be referenced anywhere in [wazuh](https://github.com/wazuh/wazuh) or [libgeoip](https://github.com/maxmind/geoip-api-c):

```sh
bobvin@T560:~/github grep -rn loggeoip geoip-api-c wazuh
wazuh/src/config/global-config.h:93:    u_int8_t loggeoip;
wazuh/src/config/alerts-config.c:65:                Config->loggeoip = 1;
wazuh/src/config/alerts-config.c:67:                Config->loggeoip = 0;
bobvin@T560:~/github
```

It would appear, therefore, that setting this option has no effect.

**Comment by vikman90** [comment]
Hi @pillarsdotnet,

You nailed it. There are two implementations of GeoIP:

- 26becc5, 6 years ago. This one introduces:
```xml
<global>
  <geoip_db_path />
  <geoip6_db_path />
</global>
<alerts>
  <use_geoip />
</alerts>
```
All of them are now legacy. They are parsed for compatibility reasons but they are unused.
- a65474f by @dcid and @atomicturtle, 2 years ago. This commit introduces:
```xml
<global>
  <geoipdb />
</global>
```
There is a related issue (#30) where we also introduced some more rules options. You will see there an example of the new configuration.

Hope it helps. Please let us know if you have any issue with this configuration.

Best regards.
