### ISSUE TITLE
wazuh-api not present in /etc/init.d on Debian Wheezy

### ISSUE THREAD

**Issue by copacetic** [wazuh/wazuh#149]
```
hayg@***:$ ls -lah /etc/init.d | grep wazuh
-rwxr-x--x   1 root ossec  947 2017-06-23 19:07 wazuh-manager

hayg@***:$ sudo service wazuh-api start
wazuh-api: unrecognized service
```
I was expecting the above commands to return different results, according to https://documentation.wazuh.com/current/user-manual/api/getting-started.html#starting-and-stopping-the-api

This, coupled with #148, means I can't enroll my production machines with the manager in an automated manner.

EDIT: Adding dpkg output
```
ii  wazuh-manager                               2.0-1wheezy                         i386         Wazuh helps you to gain security visibility into your infrastructure by monitoring hosts at an operating system and application level. It provides the following capabilities: log analysis, file integrity monitoring, intrusions detection and policy and compliance monitoring
```

**Comment by copacetic** [comment]
I found that it was removed from the `wazuh` repo in v1.0.4: https://github.com/wazuh/wazuh/blob/7e2a6a0d4fdf0f62393f137a8bc9eaab94958d69/CHANGELOG.md

Closing this. Might be worth updating the `Getting Started` though.

**Comment by jesuslinares** [comment]
Hi @copacetic ,

the current documentation is for Wazuh manager 2.0 and Wazuh API 2.0.

You can install the API using [packages](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_deb.html#installing-wazuh-api) or [sources](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html#installing-wazuh-api).

We are taking a look into the issue #148.

Let me know if you need help.

Regards.

**Comment by copacetic** [comment]
Thank you Jesus!
