### ISSUE TITLE
[Feature request] Wazuh agent to accept multiple targets as WAZUH_MANAGER

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh#14919]
Just like NTP setup, it would be better if we can define multiple targets so that the load balancing is handled on client level.

The target can be a cluster of HAProxy/Nginx load balancers or a couple of Wazuh manager nodes depending on the setup. Yet, it might help solving the cluster problem with minimal setup, aka no witness node.

**Comment by AdriiiPRodri** [comment]
Hi @zbalkan,

Currently Wazuh agents have a feature called "Failover mode", this feature allows you to indicate several targets for the manager IPs. These targets can be IPs that point to a load balancer or IPs that point directly to the manager nodes.

You can find more information here: https://documentation.wazuh.com/current/user-manual/configuring-cluster/advanced-settings.html#pointing-agents-to-the-cluster-failover-mode

**Comment by zbalkan** [comment]
Hi @AdriiiPRodri,

It turns out it's yet another RTFM issue. Thanks for the links.
