### ISSUE TITLE
Wazuh service unit cannot be enabled in openSUSE

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#14924]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | Installation | Manager/Agent | Production | openSUSE Leap 15.4 |

### Environment information

- **Deployment**: Vagrant (local)
- **Box**: `generic/opensuse15`
- **OS info**:
  - NAME="openSUSE Leap"
  - VERSION="15.4"
  - `uname -m`: x86_64

## Description

An error is thrown while enabling the Wazuh service through `systemd` in openSUSE Leap 15.4.

```Bash
Synchronizing state of wazuh-manager.service with SysV service script with /usr/lib/systemd/systemd-sysv-install.
Executing: /usr/lib/systemd/systemd-sysv-install enable wazuh-manager
ln -sf ../wazuh-manager /etc/init.d/rc2.d/S50wazuh-manager
ln: failed to create symbolic link '/etc/init.d/rc2.d/S50wazuh-manager': No such file or directory
```

⚠️ The problem seems to come from [this line](https://github.com/wazuh/wazuh/blob/v4.3.7/src/init/init.sh#L94-L97) in `src/init/init.sh`.

<details><summary>Check if this problem comes from the OS 🟢 </summary>

<br>

**Conclusion**

> The problem does not come from the OS or a dependency.

1. Try to create a symlink
```Bash
suse2:/home/vagrant # ln -fs bla blabla
suse2:/home/vagrant # echo $?
0
```

2. Try to install another service and enable it
```Bash
suse2:/home/vagrant # zypper install --no-confirm  apache2
suse2:/home/vagrant # systemctl start apache2
suse2:/home/vagrant # systemctl enable apache2
Created symlink /etc/systemd/system/httpd.service → /usr/lib/systemd/system/apache2.service.
Created symlink /etc/systemd/system/apache.service → /usr/lib/systemd/system/apache2.service.
Created symlink /etc/systemd/system/multi-user.target.wants/apache2.service → /usr/lib/systemd/system/apache2.service.
```

</details>

## Steps to reproduce the error

<details><summary>Manager installation</summary>

1. rpm -ivh https://packages.wazuh.com/4.x/yum/wazuh-manager-4.3.7-2.x86_64.rpm
2. systemctl daemon-reload
3. systemctl enable wazuh-manager

</details>

<details><summary>Agent installation</summary>

1. rpm -ivh https://packages.wazuh.com/4.x/yum/wazuh-agent-4.3.7-2.x86_64.rpm
2. systemctl daemon-reload
3. systemctl enable wazuh-agent

</details>

## Expected behavior

The service should be enabled with no errors.

## Actual behavior

An error is thrown while enabling the service through `systemd`.

**Comment by x1ongma0** [comment]
I installed Wazuh manager on a Rocky Linux distro which I know it's not supported.
That said, the issue seems related to the presence of the init script "wazuh-manager" in /etc/rc.d/init.d on a systemd distro. Removing this script should solve the issue. I had also to set chmod u+x on rc.local script, but this could be distro-specific.
Of course, since my distro is not supported, I don't know if this is just some kind of workaround.

**Comment by T100D** [comment]
Nice, removing the scrpt as mantioned solved our problem on Rocky Linux 9, enabeling the service :-)
