### ISSUE TITLE
Response message is not clear enough (restart agent via API)

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#14958]
|Wazuh version|Component|
|---|---|
| 4.4.0 | API |

## Description

When restarting an agent through the `/agents/{AGENT-ID}/restart` endpoint the response message is not clear enough.

## Steps to reproduce

1. `TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")`
2. `curl -k -X PUT "https://localhost:55000/agents/001/restart" -H "Authorization: Bearer $TOKEN"`

## Current result

```
{"data": {"affected_items": ["001"], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Restart command was sent to all agents", "error": 0}
```

## Expected result

Instead of `.."message": "Restart command was sent to all agents"...` the message should detail which agents were restarted.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
The list of agents restarted is included in a list of affected_items
