### ISSUE TITLE
Release 3.13.6 - Release Candidate 1 - Service

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#14961]
### Packages tests metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |  |
| **Main packages metrics issue** |  #14948 |
| **Version** | 3.13.6                              |
| **Release candidate #** | RC1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v3.13.6-rc1 |

---

| System | Test Result | Build |
| :-- | :--: |  :--: |
| CentOS 6 | 🕐 | https://ci.wazuh.info/job/Test_service/4783/ |
| CentOS 7 | 🕐 | https://ci.wazuh.info/job/Test_service/4784/ |
| Ubuntu Trusty | 🕐 | https://ci.wazuh.info/job/Test_service/4785/ |
| Ubuntu Bionic | 🕐 | https://ci.wazuh.info/job/Test_service/4786/ |

Legend:
Pending/In progress: 🕐
Test not launched: ⚫
Test failed: 🔴 
Test success: 🟢 
Need review: 🟡

**Comment by DFolchA** [comment]
Unable to test due to deprecated automation testing process.
