### ISSUE TITLE
Decoder Field 'system_name' is not accepted by '<system_name>' Tag in Rule

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1496]
## Bug report
**OS**
_Debian 8_

**Wazuh version**
_3.6.1_

**Wazuh API version**
_3.6.1_

**Install type**
_manager_

**Install method**
_packages_

Bug description
----------------
I have a Windows event from security event log which generates the following decoder output:
```
**Phase 2: Completed decoding.
       decoder: 'windows'
       type: 'Security'
       status: 'AUDIT_SUCCESS'
       id: '4732'
       extra_data: 'Microsoft-Windows-Security-Auditing'
       dstuser: '(no user)'
       system_name: 'somehost.some.domain'
       subject.security_id: 'S-1-5-18'
       subject.account_name: 'MASTERLPCB01$'
       subject.account_domain: 'SOMEACCDOM'
       subject.logon_id: '0x3e7'
       security_id: 'S-1-5-21-17902591-270493178-740312968-10401'
```
The decoder extracts the field `system_name` which I want to use in a local rule. I use the `<system_name>` tag in a rule definition in local rules file `etc/rules/local_rules.xml` in this way:
 ```XML
<group name="windows,">
  <rule id="110005" level="3">
    <if_sid>18217</if_sid>
    <system_name>somehost.some.domain</system_name>
    <regex> ID:\s+\p*S-1-5-32-544</regex>
    <description>Windows: Administrators Group Changed on some special hosts</description> 
    <group>group_changed,win_group_changed,pci_dss_8.1.2,pci_dss_10.2.5,gpg13_7.10,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
    <info>http://support.microsoft.com/kb/243330</info>
  </rule>
</group>
```
I stored the rule and try to test it with  the `ossec-testrule` tool but it doesn't accept the `:<system_name>` tag:
```
/var/ossec/bin/ossec-logtest -v
2018/10/01 16:02:03 ossec-testrule: ERROR: Invalid option 'system_name' for rule '110005'.
2018/10/01 16:02:03 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'
```
Can't I use this tag?

Next I tried with the `<field>` tag:
 ```XML
<group name="windows,">
  <rule id="110005" level="3">
    <if_sid>18217</if_sid>
    <field name="system_name">somehost.some.domain</field>
    <regex> ID:\s+\p*S-1-5-32-544</regex>
    <description>Windows: Administrators Group Changed on some special hosts</description> 
    <group>group_changed,win_group_changed,pci_dss_8.1.2,pci_dss_10.2.5,gpg13_7.10,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
    <info>http://support.microsoft.com/kb/243330</info>
  </rule>
</group>
```
The `ossec-testrule` tool doesn't accept it and says:
```
/var/ossec/bin/ossec-logtest -v
2018/10/01 15:46:38 ossec-testrule: ERROR: Field 'system_name' is static.
2018/10/01 15:46:38 ossec-testrule: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
```

Bug or did make something wrong?

**Comment by cristgl** [comment]
Hello @juergenc and @Oren-Ya, and sorry for the late reply.

Thank you both for reporting this, we have created an [issue](https://github.com/wazuh/wazuh/issues/3407) where you can follow the development and keep yourselves informed about when will this fix be released.

Kind regards,
Cristina

**Comment by crolopez** [comment]
Hi @juergenc  and @Oren-Ya,

The bug has been fixed in https://github.com/wazuh/wazuh/pull/3591 and will be released soon, so I'm going to close this issue. Do not hesitate to reopen it if you consider it necessary.

Thank you for reporting it!
Best regards.
