### ISSUE TITLE
Engine - Replace yml library

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#14974]
| Wazuh version | Component | Install type | Install method   | Platform   |
| ------------- | --------- | ------------ | ---------------- | ---------- |
| 5.0.0         | Engine    | Manager      | Packages/Sources | OS version |

It is necessary to change the yml library we are using. When converting Yml types to Json it checks if the value can be transformed to the specific type, not if it is of that type. 

If you have a string with a number, as it is first checked if it can be transformed to integer it does it automatically:
https://github.com/wazuh/wazuh/blob/fb6950114987efcd266631933de517cfd22f9af4/src/engine/source/catalog/yml2Json.hpp#L20-L48

This makes it impossible to create a list of strings.

## Example
The string:
```yml
 _tmpSubjUserCodes: ["4657", "4670", "4672", "4673", "4674", "4688", "4689", "4697", "4698", "4699"]
``` 
Becomes:
```json
"_tmpSubjUserCodes": [
        4657,
        4670,
        4672,
        4673,
        4674,
        4688,
        4689,
        4697,
        4698,
        4699
]
```

**Comment by JavierBejMen** [comment]
## Update

After further research, quoted scalar values are tagged with an exclamation symbol. This allows us to handle the ambiguity between numbers and string numbers.

No need to change the library.

Fix:
```c++
constexpr auto QUOTED_TAG = "!";
...
    if (QUOTED_TAG == node.Tag())
    {
        v.SetString(node.as<std::string>().c_str(), allocator);
    }
...
```
