### ISSUE TITLE
Add command to obtain active cluster configuration

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#14983]
## Description

Sometimes it is necessary to obtain the active configuration of a cluster node. Right now there is no way to do it, the only alternative being to manually access the `cluster.json` file:
```
/var/ossec/framework/python/lib/python<PYTHON_VERSION>/site-packages/wazuh-<WAZUH_VERSION>-py<PYTHON_VERSION>.egg/wazuh/core/cluster/cluster.json
```

The problem is that any modification to that file does not take effect until the `clusterd` process is restarted. As a consequence, it is not always possible to know which is the active configuration of the cluster at a given moment.

Therefore, a new command must be implemented in the cluster that allows the API or any client to obtain the active configuration of the local node (the one in which the command is received).

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Status update

Since `cluster.json` file configuration is not global, it could be different in each cluster node. Therefore, the command should be distributed to all through the DAPI and obtain their response. 

In addition, although it should be discussed, creating an API endpoint to consult it will not be necessary since it is not a file that users should modify. Instead, it's probably enough to add a new option in the  `cluster_control` CLI to get the local node configuration. In any case, it should accept a list of nodes as a parameter.

The command name is, for now, `get_cl_conf`, and this would be the response:
```
b'ok ---------', b'{"files": {"etc/": {"permissions": 416, "source": "master", "files": ["client.keys"], "recursive": false, "restart": false, "remove_subdirs_if_empty": false, "extra_valid": false, "description": "client keys file database"}, "etc/shared/": {"permissions": 432, "source": "master", "files": ["all"], "recursive": true, "restart": false, "remove_subdirs_if_empty": true, "extra_valid": false, "description": "shared configuration files"}, "var/multigroups/": {"permissions": 432, "source": "master", "files": ["merged.mg"], "recursive": true, "restart": false, "remove_subdirs_if_empty": true, "extra_valid": false, "description": "shared configuration files"}, "etc/rules/": {"permissions": 432, "source": "master", "files": ["all"], "recursive": true, "restart": true, "remove_subdirs_if_empty": false, "extra_valid": false, "description": "user rules"}, "etc/decoders/": {"permissions": 432, "source": "master", "files": ["all"], "recursive": true, "restart": true, "remove_subdirs_if_empty": false, "extra_valid": false, "description": "user decoders"}, "etc/lists/": {"permissions": 432, "source": "master", "files": ["all"], "recursive": true, "restart": true, "remove_subdirs_if_empty": false, "extra_valid": false, "description": "user CDB lists"}, "excluded_files": ["ar.conf", "ossec.conf"], "excluded_extensions": ["~", ".tmp", ".lock", ".swp"]}, "intervals": {"worker": {"sync_integrity": 9, "sync_agent_info": 10, "sync_agent_groups": 30, "timeout_agent_groups": 40, "keep_alive": 60, "connection_retry": 10, "max_failed_keepalive_attempts": 2, "agent_groups_mismatch_limit": 10}, "master": {"process_pool_size": 2, "sync_agent_groups": 10, "timeout_extra_valid": 40, "recalculate_integrity": 8, "timeout_agent_info": 40, "agent_group_start_delay": 30, "check_worker_lastkeepalive": 60, "max_allowed_time_without_keepalive": 120, "max_locked_integrity_time": 1000}, "communication": {"timeout_cluster_request": 20, "timeout_dapi_request": 200, "timeout_receiving_file": 120, "max_zip_size": 1073741824, "min_zip_size": 31457280, "compress_level": 1, "zip_limit_tolerance": 0.2}}, "distributed_api": {"enabled": true}}'
```

**Comment by davidjiglesias** [comment]
We need to also the active-configuration in the cluster.log when the cluster starts (each node). This will allow and enhance our troubleshooting capabilities.

**Comment by davidjiglesias** [comment]
The documentation changes to https://documentation.wazuh.com/current/user-manual/reference/tools/cluster-control.html?highlight=cluster_control are missing.
