### ISSUE TITLE
High CPU consumption when using whodata on Windows

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#14984]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5-rev | FIM | Agent | Packages/Sources | Windows Server 2012 R2, 2016 and 2019 |

### Description

It has been reported that when configuring Whodata and setting the "Audit Handle Manipulation" and "Audit File system" policies to"Success", the Wazuh agent causes a high CPU consumption:

![image](https://user-images.githubusercontent.com/73501120/191585154-9ddf3816-b052-4fe5-a0e1-5dd147dec1e2.png)

### **Configuration used**

```
  <!-- File integrity monitoring -->
  <syscheck>

    <disabled>no</disabled>


    <!-- Default files to be monitored. -->
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Program Files</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Program Files (x86)</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">D:\Program Files</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">D:\Program Files (x86)</directories>
    <directories recursion_level="3" restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Windows</directories>
    <ignore>C:\Program Files (x86)\ossec-agent</ignore>
    <file_limit>
      <enabled>no</enabled>
    </file_limit>

    <!-- Database synchronization settings -->
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
```
### **Steps to reproduce**

Configure the FIM module using whodata as described in the comment above.

Modify the Advanced Audit Policy Configuration > Audit Policies > Object Access either locally or via GPO:

- Audit File System > Success
- Audit Handle Manipulation > Success

![image](https://user-images.githubusercontent.com/73501120/191586751-9bd58241-bfa0-424f-b0f5-bc56818d6cbf.png)

Apply the policy and restart the Wazuh agent.

### **Behavior**

When restarting the agent, it immediately goes to around 40% usage as it starts the initial scan and also analyzes the volumes.
After about 10 minutes it starts the Real-time/Whodata engine and slows down the CPU to between 2% and 8% CPU. This thus takes approximately 1-2 hours to return to 30-80% usage causing the problem.

**Comment by jotacarma90** [comment]
# Update

Hi @abohorqu 
After a thorough investigation, I have found the reason for the high cpu consumption. It is not an audit or whodata problem. It is exclusive of **having monitored the ossec-agent directory.** **Even with ignore or restrict**.
Here is a short summary of how the problem occurs:

- Configure syscheck with the ossec-agent directory (with some ignore or restrict):
```
    <directories restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\Program Files (x86)\ossec-agent</directories>.
    <directories restrict=".exe$|.bat$|.com$|.cmd$|.dll$" whodata="yes">C:\test</directories>
```

- With whodata running, a file is created (which will be ignored), syscheck will ignore it and will not save it in the db.

- When deleting that file, syscheck detects that the file path is not in its database and processes it (without checking ignore or restrict) treating that path as a directory, in case it is necessary to delete the content of that directory. Code:
https://github.com/wazuh/wazuh/blob/2340c177e5ce9a66873f7e371a4c4937886a6ac1/src/syscheckd/create_db.c#L565-L595

- For this process, temporary files are used, which when created and deleted in `ossec-agent\tmp` (which is being monitored), cause just the same behavior, starting an infinite loop that consumes the cpu.


## Possible solutions
The simplest solution is to modify the configuration to leave ossec-agent out. A simple way to do this would be to specifically configure the ossec-agent directory after Program Files (to overwrite the configuration), making that directory in scheduled mode:
```
    <directories whodata="yes">C:\Program Files (x86)</directories>
    <directories>C:\Program Files (x86)\ossec-agent</directories>
    <ignore>C:\Program Files (x86)\ossec-agent</ignore>
```

On the other hand, in [this development of FIM](https://github.com/wazuh/wazuh/issues/9103) (Wazuh 4.5), temporary files are no longer used, and I have verified that this problem does not exist.

Anyway, we could include a specific fix for this bug if necessary.

Greetings!
