### ISSUE TITLE
Ingest vpc flow logs from 1 centralized s3 bucket containing logs from numerous AWS accounts.

### ISSUE THREAD

**Issue by leo8034** [wazuh/wazuh#14989]
| Affected integration |
| AWS|

## Description

Hi , I'm currently working on a test to integrate all of our AWS account's VPC flow log / CloudTrail / GuardDuty logs into one S3 bucket , then using Wazuh to analyze those events, but seems Wazuh could only ingest the logs for the account same as Wazuh server running.

I'd like to ask is there any mis-config of my setting or anything i missed or it is a issue?

Thanks! 

BR

Leo

And just found a similar issue with me , but I've tried the same config as the issue #11727 , but seems not work.
https://github.com/wazuh/wazuh/issues/11727

My Wazuh Versio
[{"WAZUH_VERSION":"v4.3.6"},
{"WAZUH_REVISION":"40318"},
{"WAZUH_TYPE":"server"}]}

 
 
## Tasks
- [ ] Test in a manager.

**Comment by leo8034** [comment]
Paste my config in ossec.conf here

[20220922.txt](https://github.com/wazuh/wazuh/files/9624195/20220922.txt)

**Comment by CarlosRS9** [comment]
Hi @leo8034 

Allow me to shed some light on this topic.

Our current implementation only process the VPCFlow logs that are in your bucket whose name contains the name of an existing flowlog. That is, if in the environment where you have stored the logs, the flowlogs that generated these files do not exist these log in the S3 bucket will be completely ignored. We are aware that this behavior is not ideal, and that is why we opened issue #10846 to investigate the best way to change this. However, the change has not yet been made and will not be made in the short term as this would be a breaking change. Either we develop a complex migration process for users who are using this old version of our VPCFlow integration or we break backwards compatibility and make our module work in a different way at all. 

You can use this issue to follow the development status. We have pending to resume this development in future versions of Wazuh, but for the moment we have no date as we are currently focused on other priorities. 

Regarding CloudTrail, please note that here it is possible to specify a list of several account IDs for Wazuh to process. To do this you can make use of [aws_account_id](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#bucket-aws-account-id), specifying the values separated by commas:

```
    <bucket type="cloudtrail">
        <name>s3-dev-bucket</name>
        <aws_profile>prod</aws_profile>
        <regions>us-east-1,us-west-1,eu-central-1</regions>
        <aws_account_id>123456789012,999999999999</aws_account_id>
```
This, unfortunately, it's not possible for GuardDuty.

I hope this helps.

**Comment by leo8034** [comment]
Hi @CarlosRS9 

Much appreciate for your reply & information.

I also have another question when testing cloudtrail, i've try to add three bucket in ossec.conf , but seems my server will only execute the analysis on the bucket I config in the top (Pic 1 & Pic2) , is there anything I missed to setup?

And I've try to remove the credential file for trigger the error ,seems works for checking config on those bucket.

Looking forward to your reply, thanks!



Pic1
![image](https://user-images.githubusercontent.com/37360931/192459006-57f778d5-ea87-420c-b577-1d547c457393.png)

Pic2
![image](https://user-images.githubusercontent.com/37360931/192459049-588e3d99-b27c-4914-bc09-f8d9ccf1a52f.png)

Pic3
![image](https://user-images.githubusercontent.com/37360931/192460024-5eff1c41-422d-4c81-a210-8c792366abc8.png)

**Comment by CarlosRS9** [comment]
Hi @leo8034 

It is important to take into account that even though you can configure more than one bucket or AWS service in the same Wazuh node (manager or agent) those will run sequentially. The second picture shows that the processing of the first bucket started. Until this execution finish the rest won't be triggered. You can scale things horizontally allowing the different buckets to run in parallel by configuring the module in different Wazuh nodes, one for each bucket. You could have, for example, an agent for each of your buckets. Remember that this is not mandatory. You can process all your buckets using a single node, but keep in mind that they will be executed sequentially.

Regarding the third picture, this confirms what's happening. Because the executions finish quickly you can see that an attempt has been made to process all 3 buckets.

**Comment by leo8034** [comment]
Hi @CarlosRS9 ,

Thanks for the quick reply &explanation, but I've another wazuh-dashboard run with 4.3.4 version(The other one is 4.3.8) 
Please refer logs in Pic1, I've setup the bucket same as the 4.3.8 one , and the logs are very different and the new logs will appear immediately . I there any different for the analysist between those version?

Thanks

Leo

Pic1
![image](https://user-images.githubusercontent.com/37360931/192498044-6a98448f-05ee-4af2-9b25-47d22b24021d.png)

**Comment by CarlosRS9** [comment]
There are no relevant changes from `4.3.4` to `4.3.8` regarding our AWS integration. What you should keep in mind is that the results, both in terms of time and contents, will depend on the dates you want to process. In your original configuration you used `2022-JUN-20` and `2022-AUG-20` as values for `only_logs_after`. This means that during the first run you will be processing the logs of several months. If you do not specify any value for `only_logs_after` or you have already processed all the logs for those dates the module will only process today's logs or wherever it was left before, respectively. This may explain the behavior you indicate. Under the same circumstances, i.e. same resources for the host, same dates, same buckets and empty databases, both releases behave identically.

**Comment by leo8034** [comment]
Hi @CarlosRS9 ,

Much appreciate for the response of my question , ill wait for the analyzation .

Have another question about the AWS module , as the testing above I've two wazuh manager server receiving AWS cloudtrail logs , and I'd like to have some visualize setup while waiting the log analyze , and just notice that some filed in server 1 are defined as String filed , but the same field in server 2 has defined as Unknown filed , cause those field can't be used in visualization setting, just curious does this also need some time for log analyze? Or is there any way I can manual add those field? 

Sorry for a lots of question here.

![image](https://user-images.githubusercontent.com/37360931/192951346-26c70b95-5cc8-45b7-b763-e735860d879a.png)
