### ISSUE TITLE
Security Configuration Assessment scan impacting RabbitMQ (Windows 2016)

### ISSUE THREAD

**Issue by duncanjread** [wazuh/wazuh#14995]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.5 | Security Configuration Assessment | Agent | Windows agent installer | Windows Server 2016 |

We are having issues with the SCA scan impacting RabbitMQ performance, it took a while to track down, but the times in the ossec logs for this event:

2022/09/13 10:52:20 sca: INFO: Starting Security Configuration Assessment scan.
2022/09/13 10:52:20 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml'
2022/09/13 10:52:23 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\sca_win_audit.yml'
2022/09/13 10:52:23 sca: INFO: Security Configuration Assessment scan finished. Duration: 3 seconds.

match up exactly with issues with our applications being able to connect to RabbitMQ. I can't see exactly how as it's using the default SCA rules which check the registry.

The times stagger across four servers depending on when they were last rebooted, but they always match up.

Have you seen any issues with SCA and RabbitMQ or SCA impacting performancing in general?

Thanks,

Duncan

**Comment by FrancoRivero** [comment]
Hi @duncanjread,
how are you doing?
We are not aware of any problems between RabbitMQ and SCA, but we can see that I'm going to need your help with this.
If you check the SCA policy using for Windows system, i.e. `<agent-installation-folder>\ruleset\sca\sca_win_audit.yml` you could see that SCA for Windows does not run any commands on your system, SCA just reads the logs and compares them with the rules. (to understand this rules you can read [this document](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html)) 
I don't think SCA has any relation with RabbitMQ, however if you want you can enable debug mode in the SCA module for it you should:

1.  Open with some text editor `<agent-installation-folder>\etc\internal_options.conf`
2.  Modify from `modulesd.debug=0` to `modulesd.debug=2`
3.  After that you have to restart Wazuh to have the new settings

This would be to have more details about the SCA scan and to have evidence about the possible failure ([you can follow the following guide to have more information about the issue](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#wazuh-modules).

Regards

**Comment by duncanjread** [comment]
Hi, sorry for the late reply. I'll run this today on the agents and report back. We're also in the process of updating to 4.3.8

Thanks,

**Comment by FrancoRivero** [comment]
Hi @duncanjread, 
Could you solve the problem?
I'm going to close this issue, if you need to reopen it let me know.
Regards
