### ISSUE TITLE
Unhandled error when receiving `dapi_err` command for disconnected client

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15004]
## Description

In a cluster environment, when an error of any kind occurs while processing distributed API calls, the DAPI sends a command and extra information to its peer (master or worker):
https://github.com/wazuh/wazuh/blob/e2b514bef3d148acd4bcae1a1c7fa8783b82ca3a/framework/wazuh/core/cluster/dapi/dapi.py#L696-L700

The problem is that sometimes the client may have been disconnected (as explained in https://github.com/wazuh/wazuh/issues/15003) by the time the `dapi_err` reaches the peer node. Therefore, the `dapi_client` no longer exists in the `clients` dictionary which is being accessed in the snippet below:
https://github.com/wazuh/wazuh/blob/e2b514bef3d148acd4bcae1a1c7fa8783b82ca3a/framework/wazuh/core/cluster/master.py#L227-L230

This error is printed on the node receiving `dapi_err` command:
```
2022/09/26 10:30:14 ERROR: [Local Server] [Keep alive] No keep alives have been received from 349930 in the last minute. Disconnecting
2022/09/26 10:30:22 ERROR: [Worker worker1] [Main] Unhandled error processing request 'b'dapi_err'': '349930'
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.7-py3.9.egg/wazuh/core/cluster/common.py", line 654, in dispatch
    command, payload = self.process_request(command, payload)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.7-py3.9.egg/wazuh/core/cluster/master.py", line 231, in process_request
    asyncio.create_task(self.server.local_server.clients[dapi_client.decode()].send_request(command, error_msg))
KeyError: '349930'
```

And this one appears in the `cluster.log` of the sending command node:
```
2022/09/26 10:30:14 ERROR: [Worker worker1] [D API] Error sending request: timeout expired.
2022/09/26 10:30:22 ERROR: [Worker worker1] [D API] Wazuh Internal Error: '349930'
```

It should be better handled, as it happens with `dapi_res` commands:
https://github.com/wazuh/wazuh/blob/e2b514bef3d148acd4bcae1a1c7fa8783b82ca3a/framework/wazuh/core/cluster/master.py#L382-L386

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

I have been trying to replicate the error without success in order to develop the proposed solution and then test how it handles the error.

**Comment by fdalmaup** [comment]
# Issue Update

The error could not be replicated, yet a possible solution has been developed as suggested in the issue's description:
```python3
        elif command == b'dapi_err':
            dapi_client, error_msg = data.split(b' ', 1)
            if dapi_client in self.server.local_server.clients:
                asyncio.create_task(
                    self.server.local_server.clients[dapi_client.decode()].send_request(command, error_msg))
                return b'ok', b'DAPI error forwarded to worker'
            else:
                raise exception.WazuhClusterError(3032, extra_message=dapi_client)
```

The next step is to achieve getting the expected error and implement the solution in its corresponding branch
