### ISSUE TITLE
Investigate the libraries to update with Python 3.10

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#15048]
## Description

In this issue, we will list all the dependencies that we need to update with the upgrade of Python to 3.10. These updates may be motivated by possible incompatibilities, performance improvements or bug fixes.

It should detail the version to which we will upgrade, its dependency tree and a sample that the upgrade does not cause any bug to the components it affects.

**Comment by CarlosRS9** [comment]
## GCP Dependencies

As we indicated in https://github.com/wazuh/wazuh/issues/15040 we will be able to upgrade our depencencies required by the GCP module once we decided to remove compatibility with Python 3.6. 

This is, at the moment, the complete list of latest version for each GCP dependency while mantaining compatibility with Python 3.7:
```
google-api-core==2.10.1 
google-cloud-core==2.3.2
google-cloud-pubsub==2.13.7 
google-cloud-storage==2.5.0
googleapis-common-protos==1.56.4 
google-resumable-media==2.4.0
grpc-google-iam-v1==0.12.4 
grpcio==1.49.1 
protobuf==4.21.6
proto-plus==1.22.1
```

We have verified that the module works as expected using these depencencies as well as the other ones listed in the [requirements.txt](https://github.com/wazuh/wazuh/blob/master/framework/requirements.txt) and running the unit tests and performing simple manual testing. Both the unit and manual testing used a Python virtual env with those depencencies installed:

<details>
    <summary>pipdeptree</summary>

	aiohttp-cache==2.2.0
	  - aiohttp [required: >=3.6,<4.0, installed: 3.8.1]
	    - aiosignal [required: >=1.1.2, installed: 1.2.0]
	      - frozenlist [required: >=1.1.0, installed: 1.2.0]
	    - async-timeout [required: >=4.0.0a3,<5.0, installed: 4.0.2]
	    - attrs [required: >=17.3.0, installed: 20.3.0]
	    - charset-normalizer [required: >=2.0,<3.0, installed: 2.0.4]
	    - frozenlist [required: >=1.1.1, installed: 1.2.0]
	    - multidict [required: >=4.5,<7.0, installed: 5.1.0]
	    - yarl [required: >=1.0,<2.0, installed: 1.6.3]
	      - idna [required: >=2.0, installed: 2.9]
	      - multidict [required: >=4.0, installed: 5.1.0]
	  - aioredis [required: >=1.3,<2.0, installed: 1.3.1]
	    - async-timeout [required: Any, installed: 4.0.2]
	    - hiredis [required: Any, installed: 1.1.0]
	  - envparse [required: >=0.2.0,<0.3.0, installed: 0.2.0]
	aiohttp-cors==0.7.0
	  - aiohttp [required: >=1.1, installed: 3.8.1]
	    - aiosignal [required: >=1.1.2, installed: 1.2.0]
	      - frozenlist [required: >=1.1.0, installed: 1.2.0]
	    - async-timeout [required: >=4.0.0a3,<5.0, installed: 4.0.2]
	    - attrs [required: >=17.3.0, installed: 20.3.0]
	    - charset-normalizer [required: >=2.0,<3.0, installed: 2.0.4]
	    - frozenlist [required: >=1.1.1, installed: 1.2.0]
	    - multidict [required: >=4.5,<7.0, installed: 5.1.0]
	    - yarl [required: >=1.0,<2.0, installed: 1.6.3]
	      - idna [required: >=2.0, installed: 2.9]
	      - multidict [required: >=4.0, installed: 5.1.0]
	aiohttp-jinja2==1.4.2
	  - aiohttp [required: >=3.6.3, installed: 3.8.1]
	    - aiosignal [required: >=1.1.2, installed: 1.2.0]
	      - frozenlist [required: >=1.1.0, installed: 1.2.0]
	    - async-timeout [required: >=4.0.0a3,<5.0, installed: 4.0.2]
	    - attrs [required: >=17.3.0, installed: 20.3.0]
	    - charset-normalizer [required: >=2.0,<3.0, installed: 2.0.4]
	    - frozenlist [required: >=1.1.1, installed: 1.2.0]
	    - multidict [required: >=4.5,<7.0, installed: 5.1.0]
	    - yarl [required: >=1.0,<2.0, installed: 1.6.3]
	      - idna [required: >=2.0, installed: 2.9]
	      - multidict [required: >=4.0, installed: 5.1.0]
	  - jinja2 [required: >=2.10.1, installed: 2.11.3]
	    - MarkupSafe [required: >=0.23, installed: 1.1.1]
	  - typing-extensions [required: >=3.7.4, installed: 3.10.0.2]
	asn1crypto==1.3.0
	azure-storage-blob==2.1.0
	  - azure-common [required: >=1.1.5, installed: 1.1.25]
	  - azure-storage-common [required: ~=2.1, installed: 2.1.0]
	    - azure-common [required: >=1.1.5, installed: 1.1.25]
	    - cryptography [required: Any, installed: 3.3.2]
	      - cffi [required: >=1.12, installed: 1.14.4]
		- pycparser [required: Any, installed: 2.20]
	      - six [required: >=1.4.1, installed: 1.14.0]
	    - python-dateutil [required: Any, installed: 2.8.1]
	      - six [required: >=1.5, installed: 1.14.0]
	    - requests [required: Any, installed: 2.25.1]
	      - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	      - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	      - idna [required: >=2.5,<3, installed: 2.9]
	      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	boto3==1.17.85
	  - botocore [required: >=1.20.85,<1.21.0, installed: 1.20.85]
	    - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
	    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
	      - six [required: >=1.5, installed: 1.14.0]
	    - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.5]
	  - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
	  - s3transfer [required: >=0.4.0,<0.5.0, installed: 0.4.2]
	    - botocore [required: >=1.12.36,<2.0a.0, installed: 1.20.85]
	      - jmespath [required: >=0.7.1,<1.0.0, installed: 0.9.5]
	      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.1]
		- six [required: >=1.5, installed: 1.14.0]
	      - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.5]
	connexion==2.6.0
	  - clickclick [required: >=1.2, installed: 20.10.2]
	    - click [required: >=4.0, installed: 8.1.3]
	    - PyYAML [required: >=3.11, installed: 5.4.1]
	  - flask [required: >=1.0.4, installed: 1.1.2]
	    - click [required: >=5.1, installed: 8.1.3]
	    - itsdangerous [required: >=0.24, installed: 1.1.0]
	    - Jinja2 [required: >=2.10.1, installed: 2.11.3]
	      - MarkupSafe [required: >=0.23, installed: 1.1.1]
	    - Werkzeug [required: >=0.15, installed: 2.0.2]
	  - inflection [required: >=0.3.1, installed: 0.3.1]
	  - jsonschema [required: >=2.5.1, installed: 2.6.0]
	  - openapi-spec-validator [required: >=0.2.4, installed: 0.2.6]
	    - jsonschema [required: <3, installed: 2.6.0]
	    - pathlib [required: Any, installed: 1.0.1]
	    - PyYAML [required: >=3.13, installed: 5.4.1]
	    - six [required: Any, installed: 1.14.0]
	  - PyYAML [required: >=5.1, installed: 5.4.1]
	  - requests [required: >=2.9.1, installed: 2.25.1]
	    - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	    - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	    - idna [required: >=2.5,<3, installed: 2.9]
	    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	Cython==0.29.21
	defusedxml==0.6.0
	docker==4.2.0
	  - requests [required: >=2.14.2,!=2.18.0, installed: 2.25.1]
	    - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	    - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	    - idna [required: >=2.5,<3, installed: 2.9]
	    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	  - six [required: >=1.4.0, installed: 1.14.0]
	  - websocket-client [required: >=0.32.0, installed: 0.57.0]
	    - six [required: Any, installed: 1.14.0]
	docker-pycreds==0.4.0
	  - six [required: >=1.4.0, installed: 1.14.0]
	docutils==0.15.2
	future==0.17.1
	google-cloud-pubsub==2.13.7
	  - google-api-core [required: >=1.32.0,<3.0.0dev,!=2.7.*,!=2.6.*,!=2.5.*,!=2.4.*,!=2.3.*,!=2.2.*,!=2.1.*,!=2.0.*, installed: 2.10.1]
	    - google-auth [required: >=1.25.0,<3.0dev, installed: 1.28.0]
	      - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
	      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
		- pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
	      - rsa [required: >=3.1.4,<5, installed: 4.7.2]
		- pyasn1 [required: >=0.1.3, installed: 0.4.8]
	      - setuptools [required: >=40.3.0, installed: 58.1.0]
	      - six [required: >=1.9.0, installed: 1.14.0]
	    - googleapis-common-protos [required: >=1.56.2,<2.0dev, installed: 1.56.4]
	      - protobuf [required: >=3.15.0,<5.0.0dev, installed: 4.21.6]
	    - protobuf [required: >=3.20.1,<5.0.0dev, installed: 4.21.6]
	    - requests [required: >=2.18.0,<3.0.0dev, installed: 2.25.1]
	      - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	      - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	      - idna [required: >=2.5,<3, installed: 2.9]
	      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	  - grpc-google-iam-v1 [required: >=0.12.4,<1.0.0dev, installed: 0.12.4]
	    - googleapis-common-protos [required: >=1.56.0,<2.0.0dev, installed: 1.56.4]
	      - protobuf [required: >=3.15.0,<5.0.0dev, installed: 4.21.6]
	    - grpcio [required: >=1.0.0,<2.0.0dev, installed: 1.49.1]
	      - six [required: >=1.5.2, installed: 1.14.0]
	  - grpcio [required: >=1.38.1,<2.0dev, installed: 1.49.1]
	    - six [required: >=1.5.2, installed: 1.14.0]
	  - grpcio-status [required: >=1.16.0, installed: 1.49.1]
	    - googleapis-common-protos [required: >=1.5.5, installed: 1.56.4]
	      - protobuf [required: >=3.15.0,<5.0.0dev, installed: 4.21.6]
	    - grpcio [required: >=1.49.1, installed: 1.49.1]
	      - six [required: >=1.5.2, installed: 1.14.0]
	    - protobuf [required: >=4.21.3, installed: 4.21.6]
	  - proto-plus [required: >=1.22.0,<2.0.0dev, installed: 1.22.1]
	    - protobuf [required: >=3.19.0,<5.0.0dev, installed: 4.21.6]
	  - protobuf [required: >=3.19.0,<5.0.0dev, installed: 4.21.6]
	google-cloud-storage==2.5.0
	  - google-api-core [required: >=1.31.5,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*, installed: 2.10.1]
	    - google-auth [required: >=1.25.0,<3.0dev, installed: 1.28.0]
	      - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
	      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
		- pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
	      - rsa [required: >=3.1.4,<5, installed: 4.7.2]
		- pyasn1 [required: >=0.1.3, installed: 0.4.8]
	      - setuptools [required: >=40.3.0, installed: 58.1.0]
	      - six [required: >=1.9.0, installed: 1.14.0]
	    - googleapis-common-protos [required: >=1.56.2,<2.0dev, installed: 1.56.4]
	      - protobuf [required: >=3.15.0,<5.0.0dev, installed: 4.21.6]
	    - protobuf [required: >=3.20.1,<5.0.0dev, installed: 4.21.6]
	    - requests [required: >=2.18.0,<3.0.0dev, installed: 2.25.1]
	      - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	      - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	      - idna [required: >=2.5,<3, installed: 2.9]
	      - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	  - google-auth [required: >=1.25.0,<3.0dev, installed: 1.28.0]
	    - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
	    - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
	      - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
	    - rsa [required: >=3.1.4,<5, installed: 4.7.2]
	      - pyasn1 [required: >=0.1.3, installed: 0.4.8]
	    - setuptools [required: >=40.3.0, installed: 58.1.0]
	    - six [required: >=1.9.0, installed: 1.14.0]
	  - google-cloud-core [required: >=2.3.0,<3.0dev, installed: 2.3.2]
	    - google-api-core [required: >=1.31.6,<3.0.0dev,!=2.3.0,!=2.2.*,!=2.1.*,!=2.0.*, installed: 2.10.1]
	      - google-auth [required: >=1.25.0,<3.0dev, installed: 1.28.0]
		- cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
		- pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
		  - pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
		- rsa [required: >=3.1.4,<5, installed: 4.7.2]
		  - pyasn1 [required: >=0.1.3, installed: 0.4.8]
		- setuptools [required: >=40.3.0, installed: 58.1.0]
		- six [required: >=1.9.0, installed: 1.14.0]
	      - googleapis-common-protos [required: >=1.56.2,<2.0dev, installed: 1.56.4]
		- protobuf [required: >=3.15.0,<5.0.0dev, installed: 4.21.6]
	      - protobuf [required: >=3.20.1,<5.0.0dev, installed: 4.21.6]
	      - requests [required: >=2.18.0,<3.0.0dev, installed: 2.25.1]
		- certifi [required: >=2017.4.17, installed: 2020.4.5.1]
		- chardet [required: >=3.0.2,<5, installed: 3.0.4]
		- idna [required: >=2.5,<3, installed: 2.9]
		- urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	    - google-auth [required: >=1.25.0,<3.0dev, installed: 1.28.0]
	      - cachetools [required: >=2.0.0,<5.0, installed: 4.1.0]
	      - pyasn1-modules [required: >=0.2.1, installed: 0.2.8]
		- pyasn1 [required: >=0.4.6,<0.5.0, installed: 0.4.8]
	      - rsa [required: >=3.1.4,<5, installed: 4.7.2]
		- pyasn1 [required: >=0.1.3, installed: 0.4.8]
	      - setuptools [required: >=40.3.0, installed: 58.1.0]
	      - six [required: >=1.9.0, installed: 1.14.0]
	  - google-resumable-media [required: >=2.3.2, installed: 2.4.0]
	    - google-crc32c [required: >=1.0,<2.0dev, installed: 1.1.2]
	      - cffi [required: >=1.0.0, installed: 1.14.4]
		- pycparser [required: Any, installed: 2.20]
	  - requests [required: >=2.18.0,<3.0.0dev, installed: 2.25.1]
	    - certifi [required: >=2017.4.17, installed: 2020.4.5.1]
	    - chardet [required: >=3.0.2,<5, installed: 3.0.4]
	    - idna [required: >=2.5,<3, installed: 2.9]
	    - urllib3 [required: >=1.21.1,<1.27, installed: 1.26.5]
	libcst==0.3.20
	  - pyyaml [required: >=5.2, installed: 5.4.1]
	  - typing-extensions [required: >=3.7.4.2, installed: 3.10.0.2]
	  - typing-inspect [required: >=0.4.0, installed: 0.7.1]
	    - mypy-extensions [required: >=0.3.0, installed: 0.4.3]
	    - typing-extensions [required: >=3.7.4, installed: 3.10.0.2]
	more-itertools==8.2.0
	pip==22.2.2
	pipdeptree==2.3.1
	psutil==5.8.0
	pytest==7.1.3
	  - attrs [required: >=19.2.0, installed: 20.3.0]
	  - iniconfig [required: Any, installed: 1.1.1]
	  - packaging [required: Any, installed: 20.9]
	    - pyparsing [required: >=2.0.2, installed: 2.4.7]
	  - pluggy [required: >=0.12,<2.0, installed: 1.0.0]
	  - py [required: >=1.8.2, installed: 1.11.0]
	  - tomli [required: >=1.0.0, installed: 2.0.1]
	python-jose==3.1.0
	  - ecdsa [required: <1.0, installed: 0.16.1]
	    - six [required: >=1.9.0, installed: 1.14.0]
	  - pyasn1 [required: Any, installed: 0.4.8]
	  - rsa [required: Any, installed: 4.7.2]
	    - pyasn1 [required: >=0.1.3, installed: 0.4.8]
	  - six [required: <2.0, installed: 1.14.0]
	python-json-logger==2.0.2
	pytz==2020.1
	secure==0.2.1
	SQLAlchemy==1.3.11
	tabulate==0.8.9
	uvloop==0.15.2
	xmltodict==0.12.0

</details>

#### Unit tests
```
==================================================================== test session starts =====================================================================
platform linux -- Python 3.9.9, pytest-7.1.3, pluggy-1.0.0
rootdir: /repo/wazuh
collected 268 items  

wodles/aws/tests/test_aws.py ......................................                                                                                    [ 14%]
wodles/azure/tests/test_azure.py ....................................................................................................................  [ 57%]
wodles/azure/tests/test_orm.py .......................                                                                                                 [ 66%]
wodles/docker-listener/tests/test_docker_listener.py ...................                                                                               [ 73%]
wodles/gcloud/tests/test_bucket.py .................................                                                                                   [ 85%]
wodles/gcloud/tests/test_gcloud.py .........                                                                                                           [ 88%]
wodles/gcloud/tests/test_integration.py ........                                                                                                       [ 91%]
wodles/gcloud/tests/test_subscriber.py ..............                                                                                                  [ 97%]
wodles/gcloud/tests/test_tools.py ........                                                                                                             [100%]

===================================================================== 268 passed in 2.66s =====================================================================
```
#### PubSub
```
python3 /var/ossec/wodles/gcloud/gcloud.py -p wazuh-dev-258815 -s wazuh-gcloud-v4-5-sub -c /var/ossec/wodles/gcloud/credentials.json -T pubsub -l 2
:gcloud_wodle: - DEBUG - Setting 1 thread to pull 100 messages in total
···
:gcloud_wodle: - INFO - Received and acknowledged 100 messages
```
#### Storage
```
python3 /var/ossec/wodles/gcloud/gcloud.py -T access_logs -b framework-test-bucket -c /var/ossec/wodles/gcloud/credentials.json -l 1 -o 2021-dec-01
:gcloud_wodle: - INFO - Processing test_1_new.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 1", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - The creation time of test_22.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
:gcloud_wodle: - INFO - Processing test_2_new.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 2", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - The creation time of test_3.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
:gcloud_wodle: - INFO - Processing test_3_new.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 3", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - The creation time of test_4.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
:gcloud_wodle: - INFO - The creation time of test_5.txt is older than 2021-12-01 00:00:00+00:00. Skipping it...
:gcloud_wodle: - INFO - Processing test_6.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 6", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - Processing test_7.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 7", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - Processing test_8.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 9", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - Processing test_9.txt
:gcloud_wodle: - DEBUG - Sending msg to analysisd: "b'1:Wazuh-GCloud:{"integration": "gcp", "gcp": {"GOOGLE CLOUD STORAGE TEST": "Log 9", "source": "gcp_bucket"}}'"
:gcloud_wodle: - INFO - Updating previously processed files.
:gcloud_wodle: - INFO - Received 7 messages
```
