### ISSUE TITLE
[Feature Request] | Develop specific Wazuh agent for MacOS M1 chips

### ISSUE THREAD

**Issue by j0serca** [wazuh/wazuh#15055]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Wazuh agent | Agent | Packages/Sources | macOS |

Hi team,
Wazuh-agent package is natively built for Intel and uses translation to support Apple silicon (M1) processors, and it consumes an outstanding amount of CPU. 

![image](https://user-images.githubusercontent.com/93411185/193358450-babf3991-4a3d-47ed-a3e9-ed02cbac493e.png)

So my request would be to consider developing a specific wazuh-agent package that natively supports macOS M1 chips, for enhanced performance.

Thank you!

**Comment by alberpilot** [comment]
This request requires multiple team collaboration: 

- It's necessary to be able to compile the agent in the mentioned architecture. 
- It's needed to create a specific installer for this architecture. 
- Additionally, it will be necessary to check that syscollector retrieve correct data about the system. This check should be done from the Wazuh dashboard. 
- Finally, documentation should be modified accordingly. 

## Tasks
- https://github.com/wazuh/wazuh/issues/16127 @wazuh/core

**Comment by y0d4a** [comment]
Hi, any update on this?

**Comment by vikman90** [comment]
@y0d4a We're currently working on this task, and we expect to release it in the next version (4.4.5).

Best.

**Comment by BirdInFire** [comment]
One question, will it arrive soon ?

**Comment by davidjiglesias** [comment]
@BirdInFire Yes, it will
