### ISSUE TITLE
Research security flaws in components that run commands

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#15052]
This issue aims to search for possible shell injection or path traversal flaws at all points where subprocesses are executed.

|Module|Platform|Manager|Agent|`wpopen`|`popen`|`system`|
|---|---|---|:-:|:-:|:-:|:-:|
|Active Response: Default firewall drop|UNIX|✔️|✔️|✔️|||
|Active Response: disable-account|UNIX|✔️|✔️|✔️|||
|Active Response: firewalld-drop|UNIX|✔️|✔️|✔️|||
|Active Response: ipfw|UNIX|✔️|✔️|✔️|||
|Active Response: Kaspersky (Python)|UNIX|✔️|✔️||✔️|✔️|
|Active Response: Kaspersky|UNIX|✔️|✔️|✔️|||
|Active Response: netsh|Windows|✔️|✔️|✔️|||
|Active Response: npf|BSD||✔️|✔️|||
|Active Response: pf|BSD||✔️|✔️|✔️||
|Active Response: Restart Wazuh|UNIX|✔️|✔️|✔️|||
|Active Response: Restart Wazuh|Windows|✔️|✔️|||✔️|
|Active Response: Route-null|All|✔️|✔️|✔️||✔️|
|Active Response shared code|UNIX|✔️|✔️|✔️|||
|Active Response: Slack|All|✔️|✔️|✔️|||
|Agentd, Auth, DB sync & Logcollector: get UNIX version|UNIX|✔️|✔️||✔️||
|Agentless|Linux|✔️||✔️|||
|Agent service setup|Windows||✔️|||✔️|
|Docker integration|UNIX|✔️|✔️|✔️|||
|Execd: AR launcher|All|✔️|✔️|✔️|||
|Execd: Restarter|All|✔️|✔️|✔️|||
|FIM: file differences|All|✔️|✔️|||✔️|
|FIM: prefilter command for SHA1 & SHA256|All|✔️|✔️|✔️|||
|FIM: prefilter command for SHA1 (unused)|All|✔️|✔️||✔️||
|FIM: Restart Audit|Linux|✔️|✔️|✔️|||
|Integratord|Linux|✔️||✔️|||
|Logcollector: command format|All|✔️|✔️||✔️||
|Logcollector: full_command format|All|✔️|✔️||✔️||
|Logcollector: mac ULS format|macOS||✔️|✔️|||
|Maild|Linux|✔️|||✔️||
|Osquery integration|All|✔️|✔️|✔️|||
|Rootcheck & SCA: get process list|UNIX|✔️|✔️||✔️||
|Rootcheck|UNIX|✔️|✔️||✔️|✔️|
|Syscollector|UNIX|✔️|✔️||✔️||

**Comment by TomasTurina** [comment]
This investigation has already been concluded and all the results have been published internally.
