### ISSUE TITLE
Segmentation fault in wazuh-modulesd

### ISSUE THREAD

**Issue by FahimOstrich** [wazuh/wazuh#15060]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7-40320 | wazuh-modulesd | Manager | DEB | Ubuntu 20.04.3 LTS |

Hello team,
### Description
A segmentation fault occurs in wazuh-modulesd in Wazuh Manager v4.3.7 running on Ubuntu 20.04.3 LTS. 

We identified the following message:
`cat /var/log/messages | grep segfault`
```
Sep 21 06:58:33 vn-wzh-01-uph kernel: [16707940.752409] wazuh-modulesd[3363345]: segfault at b00000002 ip 00007f23fda57345 sp 00007f23f57f99d0 error 4 in libwazuhext.so[7f23fd6f2000+8b1000]
```
Since this segmentation fault, there is a repetitive issue regarding **"No API to connect"** everyday around 7:00 am which temporarily resolves after wazuh-manager service restart.
### Findings
We have checked the ossec.log for September 20 to September 22 to identify any error or warning related to `wazuh-modulesd` and found only these:
```
2022/09/20 10:11:57 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
2022/09/20 10:12:17 wazuh-modulesd: WARNING: Couldn't connect to download module socket 'queue/sockets/download' 
```

We can provide any log or configuration privately if needed to diagnose the issue.

Regards,
Abdullah Al Rafi Fahim

**Comment by adi5353** [comment]
Hi Team,

Please find the logs which you are looking for on this slack thread: https://wazuh-team.slack.com/archives/C038AR25C8N/p1664957909089779

Regards
Aditya Sharma
