### ISSUE TITLE
Delete cluster files when the connection is lost

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15075]
## Description

Currently, when the wazuh-clusterd process is started, all temporary cluster files that might have been left over from previous runs are removed:
https://github.com/wazuh/wazuh/blob/2340c177e5ce9a66873f7e371a4c4937886a6ac1/framework/scripts/wazuh_clusterd.py#L173-L174

The problem is that if the connection between a worker and the master breaks, they will keep all the files they were using until that moment (for example, a half-received zip). In fact, the worker will reconnect to the master as soon as possible but keeping the previous connection files, which are garbage since they will never be used. 

If the connection is unstable and this problem occurs frequently, the files could take up a significant portion of disk space. Therefore, it is proposed to remove these files also when the connection is lost and/or when establishing a new connection (hello command).

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by gonjim967** [comment]
- Try to recreate de error from the issue.
- Look at the code to fix the error.

**Comment by javiersanchz** [comment]
## Description
- Search for information to implement in clean_up function
- Attempt to implement code so that once the worker is restarted it checks for junk files.

**Comment by gonjim967** [comment]
- Investigate and gather information on how to incorporate a "clean_up" function that performs a check for unnecessary files upon worker restart.
- Explore methods to implement code that, when the worker is restarted, conducts a scan for redundant files.

**Comment by javiersanchz** [comment]
## Description

- Attempted code implementation
- Searching for information on alternative ways to fix the issue.

**Comment by javiersanchz** [comment]
##Description
Development of clean_up() method to see if it solves the error

**Comment by javiersanchz** [comment]
##Description
Development of clean_up() method to see if it solves the error

**Comment by javiersanchz** [comment]
##Description

I was able to simulate the issue failure by checking that a file remains undeleted.
Search in code so that the clean_up function performs well even if the connection is lost.

**Comment by javiersanchz** [comment]
## Description 

Implement clean_up function inside connection_lost in master file
Test issue recreation to see the bug and the solution to the bug

**Comment by javiersanchz** [comment]
## Description

Implementation of clean_up function and simulation of operation to see if the problem is reversed

**Comment by javiersanchz** [comment]
## Description

-I ssue modified and fixed
- I'm going to modify and pass the tests

**Comment by javiersanchz** [comment]
## Description 

- Modification of unit test and function test
