### ISSUE TITLE
Is it possible to disable output to alerts.log?

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#151]
Hi,
I'm going through a large volume of alerts and only using `alerts.json` to feed them into an ELK stack.
I can't seem to find a way to disable `alerts.log` as it takes the extra space on the disk. Is that possible?

I can set `custom_alert_output` to empty, but that will still generate empty new lines in the file.

**Comment by rossengeorgiev** [comment]
Oh.. of course. I was looking at the documentation, but `alerts_log` is not mentioned and thinking how can that possibly not be an option. 😃

**Comment by snaow** [comment]
You are right, *alerts_log* is not mentioned in the documentation, let us
work on it and we will add it as soon as possible.

Best regards,
Pedro.
