### ISSUE TITLE
Release 4.3.9 - Release Candidate 1 - Register

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#15108]
### Packages tests metrics information
|||
| --- | --- |
| **Main release candidate issue** | #15090 |
| **Main packages metrics issue** | #15101 |
| **Version** | 4.3.9 |
| **Release candidate** | RC1 |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.9-rc1 |

---

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

| Test | Build |
| :-- | :-- |
| Tier | https://ci.wazuh.info/view/Tests/job/Test_registration_tier/42/ |

---

| System | Status | 
| :-- | :--: |
| CentOS 8            | 🟢 |
| CentOS 7            | 🟢 |
| CentOS 6            | 🟢 |
| CentOS 5            | 🟢 |
| Debian 11           | 🟢 |
| Debian 10           | 🟢 |
| Debian 9            | 🟢 |
| Debian 8            | 🟢 |
| Debian 7            | 🟢 |
| Fedora 32           | 🟢 |
| Fedora 31           | 🟢 |
| Ubuntu Focal        | 🟢 |
| Ubuntu Bionic       | 🟢 |
| Ubuntu Xenial       | 🟢 |
| Ubuntu Precise      | 🟢 |
| Ubuntu Trusty       | 🟢 |
| Amazon Linux 1      | 🟢 |
| Amazon Linux 2      | 🟢 |
| Oracle Linux 6      | 🟢 |
| Oracle Linux 7      | 🟢 |
| Oracle Linux 8      | 🟢 |
| OpenSuse Tumbleweed | 🔴 |
| Redhat 6            | 🟢 |
| Redhat 7            | 🟢 |
| Redhat 8            | 🟢|
| Redhat 9            | 🟢 |

Status legend:
⚫ - Pending/In progress
⚪ - Skipped
🔴 - Rejected
🟢 - Approved

**Comment by rauldpm** [comment]
## Analysis report

#### openSUSE Tumbleweed 

- Found error deploying ECS Task Definition: `amd64-opensuse-tumbleweed-base:1` 
- The ECS Task Definition exists. 
- The ECR image exists.
- Related to timeout (AWS): `Timeout waiting for network interface provisioning to complete.`
- Task `Start Wazuh-manager` failed with `wazuh-modulesd: Process 32233 not used by Wazuh, removing...` error.
- This error was reported at https://github.com/wazuh/wazuh/issues/12445
- Replayed: https://ci.wazuh.info/job/Test_registration/8112/ 

  <details><summary>Task failed output</summary>
  
  ```
  17:05:13  TASK [Start Wazuh-manager] *****************************************************
  17:05:13  fatal: [amd64-opensuse-tumbleweed-base_0]: FAILED! => {
  17:05:13      "changed": true,
  17:05:13      "cmd": [
  17:05:13          "/var/ossec/bin/wazuh-control",
  17:05:13          "start"
  17:05:13      ],
  17:05:13      "delta": "0:00:21.941276",
  17:05:13      "end": "2022-10-07 15:05:12.991268",
  17:05:13      "rc": 1,
  17:05:13      "start": "2022-10-07 15:04:51.049992"
  17:05:13  }
  17:05:13  
  17:05:13  STDOUT:
  17:05:13  
  17:05:13  Starting Wazuh v4.3.9...
  17:05:13  Started wazuh-apid...
  17:05:13  Started wazuh-csyslogd...
  17:05:13  Started wazuh-dbd...
  17:05:13  Started wazuh-integratord...
  17:05:13  Started wazuh-agentlessd...
  17:05:13  Started wazuh-authd...
  17:05:13  Started wazuh-db...
  17:05:13  Started wazuh-execd...
  17:05:13  Started wazuh-analysisd...
  17:05:13  Started wazuh-syscheckd...
  17:05:13  Started wazuh-remoted...
  17:05:13  Started wazuh-logcollector...
  17:05:13  Started wazuh-monitord...
  17:05:13  wazuh-modulesd: Process 32233 not used by Wazuh, removing...
  17:05:13  wazuh-modulesd did not start correctly.
  17:05:13  
  17:05:13  
  17:05:13  STDERR:
  17:05:13  
  17:05:13  2022/10/07 15:04:53 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
  ```
  
  </details>
