### ISSUE TITLE
Release 4.3.9 - Release candidate 1 - SELinux

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#15106]
### Packages tests metrics information
|||
| --- | --- |
| **Main release candidate issue** | #15090 |
| **Main packages metrics issue** | #15101 |
| **Version** | 4.3.9 |
| **Release candidate** | RC1 |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.9-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

Status | System | Build |
| :--: | -- | -- |
| 🟢 | CentOS 7 | https://ci.wazuh.info/view/Tests/job/Test_selinux/5151/ |
| 🟢 | Ubuntu Bionic | https://ci.wazuh.info/view/Tests/job/Test_selinux/5152/ |

Status legend:
⚫ - Pending/In progress
⚪ - Skipped
🔴 - Rejected
🟢 - Approved

**Comment by rauldpm** [comment]
### Analysis report

- The tests do not show abnormal or erroneous behavior.
