### ISSUE TITLE
Release 4.3.9 - Release candidate 1 - Service

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#15110]
### Packages tests metrics information
|||
| --- | --- |
| **Main release candidate issue** | #15090 |
| **Main packages metrics issue** | #15101 |
| **Version** | 4.3.9 |
| **Release candidate** | RC1 |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.3.9-rc1 |

---

| System | Status | Build |
| :-- | :--: |  :--: |
| CentOS 6 | 🟢 | https://ci.wazuh.info/view/Tests/job/Test_service/5053/ |
| CentOS 7 | 🟢 | https://ci.wazuh.info/view/Tests/job/Test_service/5054/ |
| Ubuntu Trusty | 🟢 | https://ci.wazuh.info/view/Tests/job/Test_service/5055/ |
| Ubuntu Bionic | 🟢 | https://ci.wazuh.info/view/Tests/job/Test_service/5056/ |

Status legend:
⚫ - Pending/In progress
⚪ - Skipped
🔴 - Rejected
🟢 - Approved

**Comment by rauldpm** [comment]
## Analysis report

- The tests do not show abnormal or erroneous behavior.
