### ISSUE TITLE
Please make analysisd throw an error when a rule refers to a nonexistent CDB file

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#1513]
No errors are produced on the manager in ossec.log or by ossec-logtest when a Wazuh rule references a nonexistent CDB file.  For example, a rule containing a line like this when there is no file /var/ossec/etc/lists/bad-hosts, throws no error and silently fails to ever fire.

`<list field="hostname" lookup="match_key">etc/lists/bad-hosts</list>`

This applies to Wazuh 3.6.1 and presumably older versions as well.

Please make Wazuh alert about missing CDB files, throwing an error when ossec-logtest is used, and also having analysisd send an error to ossec.log when it encounters the same issue.  This will save users time debugging their rules that use custom CDBs.

Thanks!
Kevin

**Comment by TJOSERAFAEL** [comment]
Hi @branchnetconsulting ,

indeed you are right.We will let you know when it's implemented.
Thanks for submitting this enhancement!.

Regards
