### ISSUE TITLE
List key files to save for Wazh backup

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh#15141]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | Wazuh server + agents | Manager + agent | Packages | Linux |

According to this issue  [The upgrade guide should mention which files to back up #2979 ](https://github.com/wazuh/wazuh-documentation/issues/2979), we are adding to the Wazuh documentation a section on making a backup of the Wazuh installation. This backup may be useful for example to those users willing to move their current installation to another system.

It's necessary then, a list of key files that must be kept in a backup and which are useful to restore the installation without losing data and configurations.

The components that should be considered are:
- Wazuh server (Wazuh manager + Filebeat)
- Wazuh agents (Windows, Linux, macOS, Solaris, AIX, HP-UX)

A draft of the new documentation section can be seen here:
- [Wazuh files backup](https://documentation-dev.wazuh.com/2979-files-to-backup/user-manual/files-backup/index.html)

**Comment by jotacarma90** [comment]
## Backup Manager and Agents
Hello team,
I have been researching and testing the topic of making a full backup for wazuh-manager and wazuh-agent. Here is a list detailing each file.

### Manager
- `/var/ossec/etc/`
   - `/var/ossec/etc/client.keys` Contains the necessary connection keys for each agent registered in the manager
   - `/var/ossec/etc/sslmanager*` Files with the manager's SSL certificates and keys
   - `/var/ossec/etc/*.pem` SSL certificate file
   - `/var/ossec/etc/ossec.conf` Manager global configuration
   - `/var/ossec/etc/internal_options.conf` Manager internal options configuration
   - `/var/ossec/etc/local_internal_options.conf` internal_options file extension that overwrites added options
   - `/var/ossec/etc/rules/local_rules.xml` Custom rules created by users
   - `/var/ossec/etc/decoders/local_decoder.xml` Custom decoders created by users
   - `/var/ossec/etc/lists/<user_cdb_list>.cdb` Custom CDB lists created by users
   - `/var/ossec/etc/shared/*` Centralized configuration files, can contain folders of different agent groups
 
 - `/var/ossec/queue/`
   - `/var/ossec/queue/agent-groups/*` Distribution of agent groups
   - `/var/ossec/queue/agentless/*` Files containing agentless info and config
   - `/var/ossec/queue/agents-timestamp/*` Information about each agent's original registration time
   - `/var/ossec/queue/db/*` Important databases with collected data from agents, should be saved with Wazuh stopped
   - `/var/ossec/queue/fts/*` Files info about "First time seen" alerts when the fts option of a decoder is activated.
   - `/var/ossec/queue/rids/*` Files needed to maintain connection with agents

 - `/var/ossec/logs/*` Log and alerts files from every module in Wazuh

- `/var/ossec/integrations/<custom_integration_script>` It is only necessary to save the custom scripts created by users

- `/var/ossec/api/configuration/*` Configuration files and SSL certificate and key for API

- `/var/ossec/stats/*` Statistics on each agents alerts, needed to show them in dashboard

- `/var/ossec/var/db/agents/*` Databases for old agents (<4.0)

- `/var/ossec/var/multigroups/*` Centralized configuration files when using multigroups

### Linux agents
- `/var/ossec/etc/`
  - `/var/ossec/etc/client.keys` Contains the necessary connection key of the agent
  - `/var/ossec/etc/ossec.conf` Agent global configuration
  - `/var/ossec/etc/internal_options.conf` Agent internal options
  - `/var/ossec/etc/local_internal_options.conf` internal_options file extension that overwrites added options
  - `/var/ossec/etc/*.pem` SSL certificate file

- `/var/ossec/logs/*` Log and alerts files from every module in Wazuh

- `/var/ossec/queue/rids/*` Files needed to maintain connection with manager

### Windows agents
- `C:\Program Files (x86)\ossec-agent`
  - `C:\Program Files (x86)\ossec-agent\client.keys` Contains the necessary connection key of the agent
  - `C:\Program Files (x86)\ossec-agent\ossec.conf` Agent global configuration
  - `C:\Program Files (x86)\ossec-agent\ossec.log` Agent log file
  - `C:\Program Files (x86)\ossec-agent\internal_options.conf` Agent internal options
  - `C:\Program Files (x86)\ossec-agent\local_internal_options.conf` internal_options file extension that overwrites added options
  - `C:\Program Files (x86)\ossec-agent\*.pem` SSL certificate file
  - `C:\Program Files (x86)\ossec-agent\rids\*` Files needed to maintain connection with manager

### Notes
Many of these directories and files may not exist depending on the modules being used in each installation.
By storing all these files with different backup methods, the permissions may be altered. It is necessary to check that the permissions are the same as they were in the initial installation for the correct functioning of Wazuh.
