### ISSUE TITLE
Investigate PUT /agents/restart API request failure

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#15149]
|Wazuh version|Component|
|---|---|
| 4.3.9-rc1 | Wazuh API |

## Description

During the Workload metrics tests performed on https://github.com/wazuh/wazuh/issues/15094 the `/agents/restart` endpoint failed due to timeout. This failure should not be related to the `cluster/restart` failure reported in https://github.com/wazuh/wazuh/issues/8871. It is necessary to investigate the causes of this failure and its impact.

## Environment settings
- Agents: 50000
- Workers: 25
- [Artifacts](https://github.com/wazuh/wazuh/files/9754152/artifacts.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
This is a Known Issue due to big load
