### ISSUE TITLE
Update AWS integration to support VPC Flow logs directory structure

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1516]
Hi team,

I have deployed a new AWS environment and I have realized the directory structure generated for VPC Flow logs is almost identical to CloudTrail:

* Amazon S3detonationlab-s3bucketvpcflow-2ok03g4b33e4/AWSLogs/0000000/vpcflowlogs/us-east-1/2018/10/02
* Amazon S3detonationlab-s3bucketcloudtrail-1wljmgqnaxo8k/AWSLogs/0000000/CloudTrail/us-east-1/2018/10/02

The only difference is the service name just before the region, but it makes Wazuh unable to read VPC Flow logs.

Best regards,
Marta

**Comment by druizz90** [comment]
Hi team,

We can fix this by adapting `AWSLogsBucket` class structure. I think that it may be easy.

Best regards,

Demetrio.
