### ISSUE TITLE
Don't show my new rule for AWS WAFv2

### ISSUE THREAD

**Issue by ramendola** [wazuh/wazuh#15174]
Hi,

i create a rule for my AWS WAF where i try to get the "count" in one type of "rule.id". 

The rule is 

```
  <!-- WAF infosec -->
  <rule id="80445" level="3">
    <match>EXCLUDED_AS_COUNT</match>
    <options>no_full_log</options>
    <description>AWS WAF - Excluded Counted request.</description>
    <group>aws_waf,aws_waf_count,</group>
  </rule>
```

On next i paste the log from the bucket

Log EXCLUDED_AS_COUNT HostingProviderIPList - S3

`{"timestamp":1665739485081,"formatVersion":1,"webaclId":"arn:aws:wafv2:us-east-1:126489512199:regional/webacl/WAF_SD/13f3f2af-4a4e-412e-87ac-a042375e6219","terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","action":"ALLOW","terminatingRuleMatchDetails":[],"httpSourceName":"ALB","httpSourceId":"126489512199-app/sd-02/a117def63d9e5408","ruleGroupList":[{"ruleGroupId":"arn:aws:wafv2:us-east-1:126489512199:regional/rulegroup/Infosec-WAF/1f08bfed-adc6-43ad-8de0-a0a4d09bc0b0","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesAmazonIpReputationList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesAnonymousIpList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":[{"exclusionType":"EXCLUDED_AS_COUNT","ruleId":"HostingProviderIPList","ruleMatchDetails":null}],"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesCommonRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesKnownBadInputsRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesLinuxRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesPHPRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null}],"rateBasedRuleList":[],"nonTerminatingMatchingRules":[],"requestHeadersInserted":null,"responseCodeSent":null,"httpRequest":{"clientIp":"135.125.217.54","country":"FR","headers":[{"name":"Host","value":"3.269.215.258"},{"name":"Connection","value":"keep-alive"},{"name":"Accept-Encoding","value":"gzip, deflate"},{"name":"Accept","value":"*/*"},{"name":"User-agent","value":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"}],"uri":"/.env","args":"","httpVersion":"HTTP/1.1","httpMethod":"GET","requestId":"1-63492add-2f8daa464de29273340996e5"}}`

If i test the ruleset seems to be ok

**Phase 3: Completed filtering (rules).
	id: '80445'
	level: '3'
	description: 'AWS WAF - Excluded Counted request.'
	groups: '["amazon","aws","aws_waf","aws_waf_count"]'
	firedtimes: '1'
	mail: 'false'
**Alert to be generated.

But the alert don't show on events.

I search on alerts.json if the event is in the wazuh and i found this log

Log EXCLUDED_AS_COUNT HostingProviderIPList - Wazuh

`{"timestamp":"2022-10-14T09:27:42.017+0000","rule":{"level":3,"description":"AWS WAF - Allowed request.","id":"80441","firedtimes":1471,"mail":false,"groups":["amazon","aws","aws_waf","aws_waf_allow"]},"agent":{"id":"000","name":"ip-10-0-1-190"},"manager":{"name":"ip-10-0-1-190"},"id":"1665739662.1276899714","decoder":{"name":"json"},"data":{"integration":"aws","aws":{"log_info":{"log_file":"Siem/WAF/2022/10/14/09/aws-waf-logs-Wazuh-6-2022-10-14-09-20-24-e651089d-c154-4a8e-a135-8f1ae36c4f0f","s3bucket":"invgate-infosec"},"timestamp":"1665739485081.000000","formatVersion":"1","webaclId":"arn:aws:wafv2:us-east-1:126489512199:regional/webacl/WAF_SD/13f3f2af-4a4e-412e-87ac-a042375e6219","terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","action":"ALLOW","terminatingRuleMatchDetails":[],"httpSourceName":"ALB","httpSourceId":"126489512199-app/sd-02/a117def63d9e5408","ruleGroupList":[{"ruleGroupId":"arn:aws:wafv2:us-east-1:126489512199:regional/rulegroup/Infosec-WAF/1f08bfed-adc6-43ad-8de0-a0a4d09bc0b0","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesAmazonIpReputationList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesAnonymousIpList","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":[{"exclusionType":"EXCLUDED_AS_COUNT","ruleId":"HostingProviderIPList","ruleMatchDetails":null}],"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesCommonRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesKnownBadInputsRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesLinuxRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null},{"ruleGroupId":"AWS#AWSManagedRulesPHPRuleSet","terminatingRule":null,"nonTerminatingMatchingRules":[],"excludedRules":null,"customerConfig":null}],"rateBasedRuleList":[],"nonTerminatingMatchingRules":[],"httpRequest":{"clientIp":"135.125.217.54","country":"FR","headers":{"Host":"3.269.215.258","Connection":"keep-alive","Accept-Encoding":"gzip, deflate","Accept":"*/*","User-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"},"uri":"/.env","httpVersion":"HTTP/1.1","httpMethod":"GET","requestId":"1-63492add-2f8daa464de29273340996e5"},"source":"waf"}},"location":"Wazuh-AWS"}`

so if i understand well. the event arrive to wazuh but i don't know why i can't saw it.

**Comment by ramendola** [comment]
i just run 2 commands

ubuntu@ip-10-0-1-190:~$ sudo service filebeat status
● filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
     Loaded: loaded (/lib/systemd/system/filebeat.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-09-27 14:50:25 UTC; 2 weeks 3 days ago
       Docs: https://www.elastic.co/products/beats/filebeat
   Main PID: 499 (filebeat)
      Tasks: 11 (limit: 9100)
     Memory: 52.9M
     CGroup: /system.slice/filebeat.service
             └─499 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat >

Sep 27 14:50:25 ip-10-0-1-190 systemd[1]: Started Filebeat sends log files to Logstash or directly to Elasticsearch..
ubuntu@ip-10-0-1-190:~$ sudo filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.2
    dial up... OK
  talk to server... OK
  version: 7.10.2


In the issue [https://github.com/wazuh/wazuh/issues/5262](https://github.com/wazuh/wazuh/issues/5262) the last comment said something about the kibana app for some reason is not receiving information.

**Comment by ramendola** [comment]
i search the same event on alerts.log and found the next log

`{"integration": "aws", "aws": {"log_info": {"aws_account_alias": "", "log_file": "Siem/WAF/2022/10/14/09/aws-waf-logs-Wazuh-6-2022-10-14-09-20-24-e651089d-c154-4a8e-a135-8f1ae36c4f0f", "s3bucket": "invgate-infosec"}, "timestamp": 1665739485081, "formatVersion": 1, "webaclId": "arn:aws:wafv2:us-east-1:129106826746:regional/webacl/Invgate_WAF_SD/13f6f2cd-4a4e-412e-87ac-a042375e6219", "terminatingRuleId": "Default_Action", "terminatingRuleType": "REGULAR", "action": "ALLOW", "terminatingRuleMatchDetails": [], "httpSourceName": "ALB", "httpSourceId": "129106826746-app/shared-024/a117def63d9e5408", "ruleGroupList": [{"ruleGroupId": "arn:aws:wafv2:us-east-1:129106826746:regional/rulegroup/Infosec-WAF/1f02afed-adc6-43ad-8de0-a0a4d09bc0b0", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesAmazonIpReputationList", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesAnonymousIpList", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": [{"exclusionType": "EXCLUDED_AS_COUNT", "ruleId": "HostingProviderIPList", "ruleMatchDetails": null}], "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesCommonRuleSet", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesKnownBadInputsRuleSet", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesLinuxRuleSet", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}, {"ruleGroupId": "AWS#AWSManagedRulesPHPRuleSet", "terminatingRule": null, "nonTerminatingMatchingRules": [], "excludedRules": null, "customerConfig": null}], "rateBasedRuleList": [], "nonTerminatingMatchingRules": [], "httpRequest": {"clientIp": "135.125.217.54", "country": "FR", "headers": {"Host": "3.231.243.182", "Connection": "keep-alive", "Accept-Encoding": "gzip, deflate", "Accept": "*/*", "User-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"}, "uri": "/.env", "args": "", "httpVersion": "HTTP/1.1", "httpMethod": "GET", "requestId": "1-63492add-2f8daa464de29273340996e5"}, "source": "waf"}}`

the ruleset test match with other id

**Phase 3: Completed filtering (rules).
	id: '80441'
	level: '3'
	description: 'AWS WAF - Allowed request.'
	groups: '["amazon","aws","aws_waf","aws_waf_allow"]'
	firedtimes: '1'
	mail: 'false'
**Alert to be generated.

**Comment by ramendola** [comment]
@juliancnn me podras ayudar? se te ocurre que puede ser?

**Comment by juliancnn** [comment]
Hi @ramendola,
To test this, I have generated the same alert you share with us. I used your log, your custom rule and generated the alert manually and then injected it into the alert.json (This allows me to simulate your case). But I have been able to display it in kibana without problems.

![image](https://user-images.githubusercontent.com/1891958/197609869-6b417940-f513-4a57-a942-f02519d1c809.png)

### Reviewing the operation of the Wazuh environment

If you can see the alert in the alerts.json file, it means that you have no problems in the integration, or in wazuh-manager.

![Untitled drawing](https://user-images.githubusercontent.com/1891958/197609296-c508a399-8465-4541-bb23-aa3c8d633d0d.jpg)

Wazuh Manager, receives logs from different sources.
The logs are processed by Wazuh-Analysisd, and in the case of generating alerts, these are stored in the `alert.json` file.
Filebeat, watches the `alert.json` file, reads the alerts and sends them to Elasticsearch.
Finally, Wazuh-App (application inside Kibana), is able to communicate with the manager through its API and also to collect alert data from Elasticsearch.

This is a brief summary, abstracting from details, in order to explain the workaraund (You can learn more about the architecture and operation of wazuh [here](https://documentation.wazuh.com/current/getting-started/architecture.html)).

Are you having problems receiving other alerts? Or does it only happen with Rule 80441 alerts?

**Comment by ramendola** [comment]
Hi @juliancnn so if i understand well seems to be wrong something in the Filebeat or Elasticsearch.

I made 3 custom rules and any of this i can't see in Wazuh, really i don't understand why. Others rules (default rules) like blocked or allow from waf, events from cloudtrail or VPC are fine

Maybe i need to do something on Filebeat to upgrade the rules?

**Comment by ramendola** [comment]
Hi @juliancnn i found in the logs of Filebeat the error "mapper_parsing_exception"

`{"type":"mapper_parsing_exception","reason":"failed to parse field [data.aws.ruleGroupList.excludedRules] of type [keyword] in document with id 'A0MRGoQBz_d01f9hr4va'. Preview of field's value: '{ruleMatchDetails=null, exclusionType=EXCLUDED_AS_COUNT, ruleId=HostingProviderIPList}'","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a START_OBJECT at 1:779"}}`

So i fix seting the field in conflict as string in the index-pattern
