### ISSUE TITLE
The `version` filter from `GET /agents` query is not intuitive

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15173]
|Wazuh version|Component|
|---|---|
| 4.3.9-1 | API |

## Description

Trying to use the query `GET /agents` filtering by agent version, we notice the following:
- The documentation doesn't explain the `version` format. It should be `4.3.8`? `v4.3.8`? Finally, we found `Wazuh v4.3.8` which is probably the most anti-intuitive option. 
- Further, the string `Wazuh v` should not be part of a `version` field. Even though it was explained in the documentation, it's an unnecessary string. 

### Additional
This screenshot shows a specific agent section:
![image](https://user-images.githubusercontent.com/3830293/195913786-34320122-5978-4ffb-b1db-b908348f2646.png)

using `Wazuh v4.3.9` as standard. But if we see the summary agent section:

![image](https://user-images.githubusercontent.com/3830293/195913918-94069090-d7c9-4f34-bf97-7ec6d4231508.png)

If I try to use `PUT /agents/upgrade` with `upgrade_version` with the same `version` format:
```
PUT /agents/upgrade?force=true&agents_list=all&upgrade_version=Wazuh v4.3.8
```

it shows:
```
{
  "error": "3013",
  "message": {
    "title": "Bad Request",
    "detail": "'Wazuh v4.3.8' is not a 'wazuh_version'. Failed validating 'format' in schema: {'format': 'wazuh_version', 'type': 'string'}. On instance: 'Wazuh v4.3.8'"
  }
}
```

it's not consistent.

**Comment by davidjiglesias** [comment]
This issue has already been addressed at https://github.com/wazuh/wazuh/issues/10426
