### ISSUE TITLE
The Arch linux feed can not be parsed due to an URL change

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15180]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9-1 | Vulnerability detector | Manager | Packages | Amazon Linux 2 |

The automated process that monitor the Demo environments health, reported the following error:
```
2022/10/17 06:46:28 wazuh-modulesd:vulnerability-detector: ERROR: (5524): The 'Arch Linux' feed couldn't be parsed from 'tmp/vuln-temp-fitted' file.
2022/10/17 06:46:28 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
```

It looks like the URL `https://security.archlinux.org/all.json` changed.

**Comment by MarcelKemp** [comment]
A workaround while applying the fix would be to use the following configuration:
```xml
    <!-- Arch OS vulnerabilities -->
    <provider name="arch">
      <enabled>yes</enabled>
      <url>https://security.archlinux.org/issues/all.json</url>
      <update_interval>1h</update_interval>
    </provider>
```
