### ISSUE TITLE
Where is "wazuh-events"?

### ISSUE THREAD

**Issue by pirxthepilot** [wazuh/wazuh#152]
This page describes the `wazuh-events` Elasticsearch index which should have all the raw logs collected by Wazuh manager:

https://documentation.wazuh.com/current/getting-started/components.html#elastic-stack

After setting everything up according to the Installation Guide, everything works as expected, except for wazuh-events. I have already configured `ossec.conf` with `logall` set to yes.  Looking at both the logstash and filebeat default configurations, neither has any setting that forwards either archives.log or archives.json.

Is there some additional step I need to do to make this work? Thanks!

**Comment by snaow** [comment]
HI @pirxthepilot,

Let me add here a guide we have prepared for integrating raw output / archives json output with Elastic Stack.
This same guide is mentioned as well in our Mailing List.

### 1.- Wazuh Manager

On the manager, configure /var/ossec/etc/ossec.conf to use JSON logall capabilities:

This option goes under <global> section:

    <logall_json>yes</logall_json>

Then restart the manager with:

    /var/ossec/bin/ossec-control restart

You should have all your log data now in /var/ossec/logs/archives/archives.json. Test with:

    tail -f /var/ossec/logs/archives/archives.json


### 2.- Filebeat

Configure /etc/filebeat/filebeat.yml to read alerts.json and archives.json data. Adding as well a new field "event_type" for "event" or "alert" value:

    filebeat:
      prospectors:
       - input_type: log
         paths:
          - "/var/ossec/logs/alerts/alerts.json"
         fields:
          event_type: alerts
         fields_under_root: true
         document_type: json
         json.message_key: log
         json.keys_under_root: true
         json.overwrite_keys: true

       - input_type: log
         paths:
          - "/var/ossec/logs/archives/archives.json"
         fields:
          event_type: archives
         fields_under_root: true
         document_type: json
         json.message_key: log
         json.keys_under_root: true
         json.overwrite_keys: true
    
         output:
          logstash:
            # The Logstash hosts
            hosts: ["localhost:5000"]
         #   ssl:
         #     certificate_authorities: ["/etc/filebeat/logstash.crt"]   


### 3.- Logstash

Remove "fields" entry from section: filter->mutate->remove_fields:

```
 remove_field => [ "timestamp", "beat",  "input_type", "tags", "count", "@version", "log", "offset", "type"]
```

Set Logstash output configuration to use "event_type" value: 

     output {
         elasticsearch {
             hosts => ["localhost:9200"]
             index => "wazuh-%{event_type}-%{+YYYY.MM.dd}"
             document_type => "wazuh"
             template => "/etc/logstash/wazuh-elastic5-template.json"
             template_name => "wazuh"
             template_overwrite => true
         }
     }

### 4.- Elasticsearch

Check indices

`curl -XGET localhost:9200/_cat/indices/wazuh-archives*`

Expected output:

`green open wazuh-archives-2017.05.31 ZD3z28srRSara_FISH-sQg 5 0 9 0 34kb 34kb`


### 5.- Kibana

Add a new index pattern.

Open Kibana WUI, go to "Management" (Gear icon, left bar).

"Index patterns", create a new one with pattern wazuh-archives-*.

Now you have three index patterns, you could choose to display whatever events you need:

    wazuh-alerts-*
    wazuh-archives-*
    wazuh-monitoring-*

If for some reason, you want to display all the data on same visualizations or discover tab, you could create a new index pattern with pattern "wazuh-*" which will group everything.

   Let me know if it helps.

**Comment by pirxthepilot** [comment]
@snaow this is perfect, thank you! is this something that will be included by default in a future (upcoming?) wazuh version?

**Comment by snaow** [comment]
HI @pirxthepilot,

We will think about it, I am not sure if adding this by default will add some complexity to the general installation and configuration process. I am aware some users want archives functionality but I would say they are not the majority, still, we will study how to do the whole process easier in the future.

Best,
Pedro.

**Comment by pirxthepilot** [comment]
Noted and thanks for the response!

**Comment by markalston** [comment]
For others who follow these instructions note that the elasticsearch index template needs to be loaded manually as wazuh only loads one for wazuh-alerts-* and wazuh-archives-* will not match that template.

I simply piped the alerts template through sed to setup my archives template.

```
 curl https://raw.githubusercontent.com/wazuh/wazuh/3.1/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | sed 's/wazuh-alerts/wazuh-archives/g' | curl -XPUT 'http://elasticsearch:9200/_template/wazuh-archives' -H 'Content-Type: application/json' -d @-
```

**Comment by mjejee** [comment]
Hi,

For those who have a single host architecture and don't need Filebeat, I attach an extract of my Logstash configuration file, that provides the wazuh-archives logs to Elasticsearch with no need for Filebear.

```
input {
   file {
       type => "log"
       path => "/var/ossec/logs/alerts/alerts.json"
       codec => "json"
       tags => ["alerts"]
   }
   file {
       type => "log"
       path => "/var/ossec/logs/archives/archives.json"
       codec => "json"
       tags => ["archives"]
   }
}

filter {
   if "archives" in [tags]{
       mutate {
           add_field => { "[@metadata][tag]" => "${tag:archives}" }
       }
   }
   if "alerts" in [tags]{
       mutate {
           add_field => { "[@metadata][tag]" => "${tag:alerts}" }
       }
   }

   ...

}
output {
   if [@metadata][tag] == "alerts" {
   elasticsearch {
     hosts => ["localhost:9200"]
     index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
     document_type => "wazuh"
   }
 }
 if [@metadata][tag] == "archives" {
   elasticsearch {
     hosts => ["localhost:9200"]
     index => "wazuh-archives-3.x-%{+YYYY.MM.dd}"
     document_type => "wazuh"
   }
 }
}
```

**Comment by xormail** [comment]
I am running Wazuh 4.1. What should I configure to achieve the same (all from archives -> elastic)? Thanks
