### ISSUE TITLE
Error installing Wazuh agent on Windows 11

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#15216]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.7 | Wazuh MSI | Agent | Packages| Windows 11 Pro|

Hello team,

I found the following error installing the Wazuh agent in the aforementioned version on a Windows 11 Pro:
![image](https://user-images.githubusercontent.com/23264276/197470228-cc4beece-e497-4782-9c1e-1a7ccfcb325c.png)

The installation method tried was using the command line with administration permissions. Also, clicking on the package with the administrator user threw the same result.

The errors appear to be the following:
```
MSI (s) (A0:AC) [09:57:51:239]: SOFTWARE RESTRICTION POLICY: Verifying package --> 'C:\Users\Desktop\wazuh-agent-4.3.7-1.msi' against software restriction policy
MSI (s) (A0:AC) [09:57:51:270]: SOFTWARE RESTRICTION POLICY: C:\Users\Desktop\wazuh-agent-4.3.7-1.msi has a digital signature
MSI (s) (A0:AC) [09:58:22:860]: SOFTWARE RESTRICTION POLICY: C:\Users\Desktop\wazuh-agent-4.3.7-1.msi is permitted to run at the 'unrestricted' authorization level.
roduct: Wazuh Agent -- Error 1720. There is a problem with this Windows Installer package. A script required for this install to complete could not be run. Contact your support personnel or package vendor.  Custom action CheckSvcRunning script error -2147217392, SWbemObjectSet: Clase no válida  Line 369, Column 5,  

Error 1720. There is a problem with this Windows Installer package. A script required for this install to complete could not be run. Contact your support personnel or package vendor.  Custom action CheckSvcRunning script error -2147217392, SWbemObjectSet: Clase no válida  Line 369, Column 5,  
Action ended 9:58:36: CheckSvcRunning. Return value 3.
Action ended 9:58:36: INSTALL. Return value 3.
```

According to this message:
```
SWbemObjectSet: Clase no válida  Line 369, Column 5,  
```
The error seems to be related to this line: https://github.com/wazuh/wazuh/blob/d3436911016114c0912cef87df9f19b7a446ffd1/src/win32/InstallerScripts.vbs#L369

And the error seems to appear when this query finds a empty value:
```
Set svc = wmi.ExecQuery("Select * from Win32_Service where Name = '" & SERVICE & "'")
```

Let me know if you need anything else from our side.

Miguel Casares

**Comment by okynos** [comment]
### Research summary
We have been reviewing this problem. There are some points to describe:
- The WMI object provided by Windows 11 host isn't in the expected format
- The way to retrieve service status depends on the system (WMI information)

It's necessary to explain what WMI is. I will attach the official Microsoft explanation of the topic:

>Windows Management Instrumentation (WMI) is the infrastructure for management data and operations on Windows-based operating systems. You can write WMI scripts or applications to automate administrative tasks on remote computers, but WMI also supplies management data to other parts of the operating system and products—for example, System Center Operations Manager (formerly Microsoft Operations Manager (MOM)), or Windows Remote Management ([WinRM](https://learn.microsoft.com/en-us/windows/win32/WinRM/portal)).

https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-start-page

#### WMI return status

Knowing that Wazuh uses WMI information to perform queries to the system and extract current data of the host, then analyze and take decisions based on given data. Specifically, Wazuh uses the `root/cimV2` namespace for WMI queries.
Performing a query to the `cimV2` could vary the results obtained depending on the host status and information. Analyzing the case, we conclude three possible cases to the `cimV2` query `Select * from Win32_Service where Name = 'OssecSvc'`:
- The result is a tuple, value of the `Count` attribute is equal to 1.
- The result is empty (no tuple returned), and the value of the `Count` attribute is 0.
- The result is unexpected. The `Count` has a value different from the integer value. In this case, `Count` ~ `SWbemObjectSet` isn't an integer value making the procedure report an error.

#### Proposed solutions
Solution 1; Modify the `installerScript.vbs` to avoid the usage of WMI. It will improve our system's independence. We propose to change it in favour of manual system management using, for example, a temporal status file that stores the current service status and performs the required action.

Solution 2; Manage WMI errors inside the `installerScript.vbs`. This option is easier but will imply a larger knowledge of WMI alternatives and possible results that could lead to future errors due to changes in WMI management/results or behaviour. It means to include exception management (try/catch or if/else) cases when WMI has an unexpected or different value.

Solution 3; Avoid Checking the running method from `installerScript.vbs`. This option is less elegant but could work in most cases. It consists on to define a default behaviour. We could establish that the agent will always start the service in an upgrade.

**Comment by okynos** [comment]
### Research summary 
We produced a debug script. This script will try to fetch as much information as possible and will be put into the `installerScript.log` file in the same folder where the script run.

The script performs the same two queries as the original `installerScript.vbs` file, then it will only print the results. It won't perform any action on the host.
We will need to execute the script in the failing host to retrieve the information. Anyway, we are developing a solution to the reported problem, but we want to be sure of the host's behaviour.

`debugInstallerScript.vbs`
```
Dim FSO
Set FSO = CreateObject("Scripting.FileSystemObject")
Set outputFile = FSO.CreateTextFile("./installerScript.log", 8, True)
Set wmi = GetObject("winmgmts://./root/cimv2")

outputFile.WriteLine("------ DEBUG TRACE ------")
SERVICE = "OssecSvc"
outputFile.WriteLine("First Query = {Select * from Win32_Service where Name = '" & SERVICE & "'}")

On Error Resume Next
Err.Clear
Set svc = wmi.ExecQuery("Select * from Win32_Service where Name = '" & SERVICE & "'")


outputFile.WriteLine("SVC typeName: " & typeName(svc))
outputFile.WriteLine("SVC.Count typeName: " & typeName(svc.Count))
If typename(svc.Count) <> "Long" Then
  For Each obj in svc.Count
    For Each property In obj.SystemProperties_
      outputFile.WriteLine(vbCrLf & objProperty.Name & ":")
      If Not property.IsArray Then
          outputFile.WriteLine(vbTab & property.Value)
      Else
          For Each strValue In property.Value
              outputFile.WriteLine(vbTab & strValue)
          Next
      End If
    Next
  Next
Else
  outputFile.WriteLine("SVC Count: " & svc.Count)
End If
outputFile.WriteLine("--> Iterating over query results")
For Each obj in svc
  outputFile.WriteLine("Object typeName: " & typeName(obj))
  For Each property In obj.SystemProperties_
    outputFile.WriteLine(vbCrLf & objProperty.Name & ":")
    If Not property.IsArray Then
        outputFile.WriteLine(vbTab & property.Value)
    Else
        For Each strValue In property.Value
            outputFile.WriteLine(vbTab & strValue)
        Next
    End If
  Next
  ' outputFile.WriteLine("Object text: " & obj.SystemProperties_)
  outputFile.WriteLine("Result:")
  outputFile.WriteLine("Name: " & obj.Name)
  outputFile.WriteLine("DisplayName: " & obj.DisplayName)
  outputFile.WriteLine("State: " & obj.State)
  outputFile.WriteLine("ExitCode: " & obj.ExitCode)
  outputFile.WriteLine("ProcessId: " & obj.ProcessId)
  outputFile.WriteLine("StartMode: " & obj.StartMode)
  outputFile.WriteLine("Status: " & obj.Status)
  outputFile.WriteLine("---")
Next
outputFile.WriteLine("<--")
outputFile.WriteLine("")


SERVICE = "WazuhSvc"
outputFile.WriteLine("Second Query = {Select * from Win32_Service where Name = '" & SERVICE & "'}")
Set svc = wmi.ExecQuery("Select * from Win32_Service where Name = '" & SERVICE & "'")

outputFile.WriteLine("SVC typeName: " & typeName(svc))
outputFile.WriteLine("SVC.Count typeName: " & typeName(svc.Count))
If typename(svc.Count) <> "Long" Then
  For Each obj in svc.Count
    For Each property In obj.SystemProperties_
      outputFile.WriteLine(vbCrLf & objProperty.Name & ":")
      If Not property.IsArray Then
          outputFile.WriteLine(vbTab & property.Value)
      Else
          For Each strValue In property.Value
              outputFile.WriteLine(vbTab & strValue)
          Next
      End If
    Next
  Next
Else
  outputFile.WriteLine("SVC Count: " & svc.Count)
End If
outputFile.WriteLine("--> Iterating over query results")
For Each obj in svc
  outputFile.WriteLine("Object typeName: " & typeName(obj))
  For Each property In obj.SystemProperties_
    outputFile.Write(vbTab & property.Name & ": ")
    If Not property.IsArray Then
        outputFile.WriteLine(property.Value)
    Else
        outputFile.WriteLine()
        For Each strValue In property.Value
            outputFile.WriteLine(vbTab & vbTab & strValue)
        Next
    End If
  Next
  ' outputFile.WriteLine("Object text: " & obj.SystemProperties_)
  outputFile.WriteLine("Result:")
  outputFile.WriteLine(vbTab & "Name: " & obj.Name)
  outputFile.WriteLine(vbTab & "DisplayName: " & obj.DisplayName)
  outputFile.WriteLine(vbTab & "State: " & obj.State)
  outputFile.WriteLine(vbTab & "ExitCode: " & obj.ExitCode)
  outputFile.WriteLine(vbTab & "ProcessId: " & obj.ProcessId)
  outputFile.WriteLine(vbTab & "StartMode: " & obj.StartMode)
  outputFile.WriteLine(vbTab & "Status: " & obj.Status)
  outputFile.WriteLine("---")
Next
outputFile.WriteLine("<--")


If Err.Number <> 0 then
  outputFile.WriteLine("Error executing query , error: {")
  outputFile.WriteLine(vbTab & "Error description: " & Err.Description)
  outputFile.WriteLine(vbTab & "Error number: " & Err.Number)
  outputFile.WriteLine(vbTab & "Error number (Hex): " & Hex(Err.Number))
  outputFile.WriteLine(vbTab & "Error source: " & Err.Source)
  outputFile.WriteLine("}")
  Err.clear
End If

outputFile.WriteLine("-------------------------")
set FSO = Nothing
```

The steps to execute the script are the following:
1. Download the code into the host, calling it `debugInstallerScript.vbs`
2. Open a Powershell terminal (With Administrator privileges) and navigate to the script location
3. Execute the script using Linux syntax `./debugInstallerScript.vbs`
4. Retrieve the `installerScript.log` log trace.
5. Paste such trace here (Remember to clean any specific data IPs/Hostnames)

**Comment by dariommr** [comment]
Hello Team,
Here is the output of the `installerScript.log`:
```
------ DEBUG TRACE ------
First Query = {Select * from Win32_Service where Name = 'OssecSvc'}
SVC typeName: SWbemObjectSet
--> Iterating over query results
Object typeName: Empty
Result:
---
<--

Second Query = {Select * from Win32_Service where Name = 'WazuhSvc'}
SVC typeName: SWbemObjectSet
--> Iterating over query results
Object typeName: Empty
Result:
---
<--
Error executing query , error: {
	Error description: Se requiere un objeto
	Error number: 424
	Error number (Hex): 1A8
	Error source: Error de Microsoft VBScript en tiempo de ejecución
}
-------------------------
```
And here you can find the log of the `msi` execution:
[installer.log](https://github.com/wazuh/wazuh/files/9927987/installer.log)

I hope this could be helpful.
Thank you!

**Comment by okynos** [comment]
### Research summary 
We have reviewed the results, and with the given data we couldn't conclude the main error cause. One possible cause could be a permission problem related to WMI and the requesting user. We get the same output as the given one by editing the `root/cimv2` register to prevent users from access to it.
![image](https://user-images.githubusercontent.com/10661307/199773070-a85507b2-5469-42b7-a9ea-a6455191b53f.png)

In the next steps, we will include a validation and a new running process check that could decide in case it couldn't access the WMI register.

**Comment by elwali10** [comment]
Hello team,

The same issue is reported in a `Windows 11 22H2 (build 22621.674)`. Installer log for your reference: 

[installer.log](https://github.com/wazuh/wazuh/files/9950650/installer.log)

Let me know if you require further information.

Wali.

**Comment by okynos** [comment]
### Work report 11/08/2022
After this first development and start the testing phase. We saw a problem in some scenarios that won't manage the error given by the WMI query. Again, we started new research about the matter. Some of the search results were:
- https://wixtoolset.org/docs/v3/xsd/wix/installexecutesequence/
- https://wixtoolset.org/docs/v3/xsd/wix/installexecutesequence/
- https://www.guru99.com/declaring-and-using-variables.html
- https://stackoverflow.com/questions/4100506/check-if-an-object-exists-in-vbscript
- https://social.technet.microsoft.com/Forums/scriptcenter/en-US/e4e19b3c-6508-4a66-8bc2-d0f9ec8bed58/vbscript-finding-out-what-attributes-does-the-object-support
- https://learn.microsoft.com/en-us/windows/win32/wmisdk/swbemservices-execquery
- https://learn.microsoft.com/en-us/previous-versions//sbf5ze0e(v=vs.85)
- https://learn.microsoft.com/en-us/previous-versions//zx9z5h4x(v=vs.85)
- https://learn.microsoft.com/en-us/previous-versions//53f3k80h(v=vs.85)
- https://learn.microsoft.com/en-us/dotnet/framework/unmanaged-api/wmi/execquerywmi
- https://stackoverflow.com/questions/2378723/get-first-record-from-wmi-execquery
- https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/msgbox-function
  
As the previous day, we included a new approach to manage the errors by including some more verifications and fixes.
We included popup messages to concern the users of an error in the system that prevents Wazuh from knowing its own state.

**Comment by okynos** [comment]
### Work report 11/09/2022
We found a way to check manually the WMI query that could bring us a lot of information about the user problem. We refer to this link https://www.codeproject.com/Articles/46390/WMI-Query-Language-by-Example Where it explains how to manage manual queries to WMI to detect problems and returned query results. I defined some steps to test. We will describe below:

- We have to use the binary `wbemtest` that will show up a window with different options.
- In the query field, we should set the value `Select * from Win32_Service where Name = 'WazuhSvc'` to replicate the query as MSI installers do.

We will attach here the screenshots of the procedure.

![image](https://user-images.githubusercontent.com/10661307/201664089-ef8f87f3-4771-4564-b9c2-365f1379fdcd.png)
![image](https://user-images.githubusercontent.com/10661307/201664116-576961fe-7554-4cd0-9c17-c8c68cbf9fb6.png)
![image](https://user-images.githubusercontent.com/10661307/201664130-27c26edd-0fdd-4fc3-b617-ea7411894b82.png)
![image](https://user-images.githubusercontent.com/10661307/201664137-1009decc-695a-4800-8ca8-bdaf86b14318.png)
![image](https://user-images.githubusercontent.com/10661307/201664153-63784e60-de94-47e1-a984-270aac16f5d4.png)
![image](https://user-images.githubusercontent.com/10661307/201664168-52805a64-da13-4794-b40d-e225c6720e9e.png)
![image](https://user-images.githubusercontent.com/10661307/201664180-cfc1d1bb-103c-4396-9d81-fa73d37062e8.png)
![image](https://user-images.githubusercontent.com/10661307/201664195-94a9af85-e0be-4567-a2f5-27121884a7fa.png)


After that results, we started to develop a new way to manage the errors including fixing another query to the WMI to get the system version to another point of failure that could produce the clean installation to fail, not only upgrades. We modified also the WXS file to manage service checking only during the upgrade procedure (We avoid then the WMI query in clean installations).

**Comment by okynos** [comment]
### Work report 11/10/2022
We produced a good result code that could manage the WMI error and install the agent without problems. We will attach such code here:
```
    wmi_ossec_service_message = "The service data could not be fetched from WMI implementation. The installation will continue with the default procedure (Start Wazuh service automatically). Please review your WMI status and permissions. Service name: 'OssecSvc'. "
    wmi_wazuh_service_message = "The service data could not be fetched from WMI implementation. The installation will continue with the default procedure (Start Wazuh service automatically). Please review your WMI status and permissions. Service name: 'WazuhSvc'."
    Set msgErr = Installer.CreateRecord(1)
    Set msgInfo = Installer.CreateRecord(1)
	Set wmi = GetObject("winmgmts://./root/cimv2")

    ' Checking if OssecSvc is defined in the host and if it's running
    SERVICE = "OssecSvc"
    On Error Resume Next
        Set svc = wmi.ExecQuery("Select * from Win32_Service where Name = '" & SERVICE & "'", "WQL", 0)
    
        If Err.Number <> 0 Then
            msgErr.StringData(0) = "CheckSvcRunning: Error querying WMI, Error number: " & CStr(Err.Number) & ", Error description: " & Err.Description
            Session.Message &H04000000, msgErr
            msgInfo.StringData(0) = "CheckSvcRunning: " & wmi_ossec_service_message  
            Session.Message &H04000000, msgInfo
            Session.Property("OSSECRUNNING") = "Stopped"
        Else
            For Each obj in svc
                Session.Property("OSSECRUNNING") = obj.State
                exit For
            Next
        End If
        Err.Clear
    On Error GoTo 0
    
    ' Checking if WazuhSvc is defined in the host and if it's running
    SERVICE = "WazuhSvc"
    On Error Resume Next
        Set svc = wmi.ExecQuery("Select * from Win32_Service where Name = '" & SERVICE & "'", "WQL", 0)

        If Err.Number <> 0 Then
            msgErr.StringData(0) = "CheckSvcRunning: Error querying WMI, Error number: " & CStr(Err.Number) & ", Error description: " & Err.Description
            Session.Message &H04000000, msgErr
            msgInfo.StringData(0) = "CheckSvcRunning: " & wmi_wazuh_service_message  
            Session.Message &H04000000, msgInfo
            Session.Property("WAZUHRUNNING") = "Running"
        Else
            For Each obj in svc
                Session.Property("WAZUHRUNNING") = obj.State
                exit For
            Next
        End If
        Err.Clear
    On Error GoTo 0
```

This code manages errors and provides a default state that could work in all environments. A small problem was on clean installation plus an upgrade before configuring the agent (In a failed WMI environment). This case produces the installer to set `WAZUHRUNNING = 'Running'` causing the agent to start without the right configuration leading to errors in the log file.
We started the research of a better way to do that without using the WMI.

We discovered that we can fetch the system version from the system registry without WMI. Using the `reg` command then, we developed the following code for the `GetVersion` function:
```
Private Function GetVersion()
    Set record = Installer.CreateRecord(1)
    Set shell = CreateObject("WScript.Shell")

    On Error Resume Next
        cmd = "reg query ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion"" /v ""CurrentVersion"""
        Set exec = shell.Exec(cmd)
        ctr = 0
        Do
            ctr = ctr + 1
        Loop While (ctr < 10 AND exec.Status = 0)
        arr = Array(exec.Status, exec.StdOut.ReadAll, exec.StdErr.ReadAll)
        strVersion = Left(Right(Replace(arr(1), vbNewLine, ""), 3), 1)
        GetVersion = CInt(strVersion)

        If Err.Number <> 0 Then
            record.StringData(0) = "(GetVersion): Error getting version, Error: " & CStr(Err.Number) & ", Description: " & Err.Description & ". Will assume default value, installation will continue."
            Session.Message &H01000000, record
            GetVersion = 6
        End If

        Err.Clear
    On Error GoTo 0
End Function
```
In addition, we remove the popups to manage quiet installations to not show any popups during their installation.

I will set here some links used to achieve this code and information:
About logging and popups:
- https://learn.microsoft.com/en-us/windows/win32/msi/session-message
- https://learn.microsoft.com/en-us/windows/win32/msi/record-object
- https://learn.microsoft.com/en-us/windows/win32/msi/installer-createrecord
- https://stackoverflow.com/questions/9429858/wix-vbscript-custom-action-with-session-message-function
- https://learn.microsoft.com/en-us/previous-versions/iis/6.0-sdk/ms524319%28v%3dvs.90%29
- https://learn.microsoft.com/en-us/windows/win32/msi/uilevel
- https://sourceforge.net/p/wix/mailman/message/29706910/
- https://www.itninja.com/question/vbscript-to-set-msi-property
- https://learn.microsoft.com/en-us/windows/win32/msi/installer-uilevel
- https://learn.microsoft.com/en-us/windows/win32/msi/installer-object
- https://learn.microsoft.com/en-us/windows/win32/msi/determining-ui-level-from-a-custom-action
- https://stackoverflow.com/questions/10608151/how-to-access-session-property-productname-in-vbscript-silent-mode-installshield
- https://www.advancedinstaller.com/forums/viewtopic.php?t=39032
- https://learn.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options
- https://stackoverflow.com/questions/17695511/msiexec-not-installing-an-msi-setup-if-quiet-parameter-is-used-to-suppress-the
- https://stackoverflow.com/questions/18839421/condition-for-msiexec-in-quiet-mode (To handle popups in quiet mode)
- https://learn.microsoft.com/en-us/windows/win32/msi/uilevel?redirectedfrom=MSDN
- https://learn.microsoft.com/en-us/windows/win32/api/msiquery/nf-msiquery-msiprocessmessage
- https://learn.microsoft.com/en-us/windows/win32/msi/sending-messages-to-windows-installer-using-msiprocessmessage
- https://stackoverflow.com/questions/2359727/msi-messagebox-custom-action
- https://learn.microsoft.com/en-us/archive/blogs/robmen/vbscript-and-jscript-msi-customactions-suck (Interesting lecture)

About `GetVersion` matter:
  The first approach, reading the `ini` file:
  - https://stackoverflow.com/questions/13190784/way-to-get-windows-version-without-using-wmi-class-win32-operatingsystem
  - https://superuser.com/questions/68452/detect-windows-server-version-32-64-bit-in-cli/267474#267474
  - https://stackoverflow.com/questions/7412439/how-to-read-ini-file-using-vbscript
  - https://www.shellhacks.com/windows-grep-equivalent-cmd-powershell/ 
  - https://stackoverflow.com/questions/1295068/windows-equivalent-of-the-tail-command
  The second approach get it from the registry:
  - https://superuser.com/questions/995591/how-to-get-a-registry-value-and-set-into-a-variable-in-batch
  - https://stackoverflow.com/questions/1564527/is-there-an-equivalent-to-cut-c-in-windows-cmd-exe
  - https://stackoverflow.com/questions/6060876/vbscript-getting-results-from-shell
  - https://www.softwaretestinghelp.com/vbscript-conditional-statements-tutorial-4/
  - https://www.guru99.com/vbscript-looping.html#4
  - https://ss64.com/vb/sleep.html
  - https://stackoverflow.com/questions/15770599/about-using-double-quotes-in-vbscript
  - https://stackoverflow.com/questions/4134115/how-to-substring-text-in-vbscript
  - https://www.w3schools.com/asp/func_replace.asp
  - https://community.spiceworks.com/topic/2178115-get-the-last-characters-after-_-char-in-vbscript-reading-from-right-side
  - https://www.w3schools.com/asp/func_right.asp
  - https://stackoverflow.com/questions/5971056/vbscript-convert-string-to-integer
  - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/icacls

In the meantime, we should test the development in a Windows XP instance so we produced a Vagrant box with all required dependencies and configuration. Some reviewed links about this matter:
- https://yoodley.com/activate-windows-xp-now-that-support-has-ended/
- https://www.techguy.org/threads/solved-win-xp-activation-loop.363300/
- https://www.activpart.com/windows-xp-activation-loop-cant-log-on-to-windows-desktop/
- https://www.youtube.com/watch?v=wzTuHuWhdcY
- https://answers.microsoft.com/en-us/windows/forum/all/date-and-time-keep-changing-in-windows-xp/c8da8b8e-54bd-4628-8c6d-d448bd64bbbe
- https://tothecore.sk/2021/04/08/disable-time-sync-for-virtualbox-virtual-machines/
- https://www.computersecuritystudent.com/WINDOWS/DVW/WXP_IE6/lesson3/index.html
- https://www.wikihow.com/Make-Windows-XP-Genuine-Forever
- https://superuser.com/questions/1502796/how-do-i-activate-windowsxp-now-that-support-has-ended
- https://www.techwalla.com/articles/how-to-activate-windows-xp-without-the-internet-or-phone
- https://www.linuxquestions.org/questions/linux-software-2/openssh-and-windows-xp-923453/
- https://sourceforge.net/projects/sshwindows/files/OldFiles/
- https://itsiti.com/windows-xp-determine-32-bit-or-64-bit-version/
- https://www.efficient-soft.com/certificate-errors-fix-windows-xp/
- https://www.systutorials.com/set-up-ssh-server-on-windows-xp/
- https://shellgeek.com/use-cat-equivalent-type-command-in-windows/
- https://www.tenable.com/plugins/nessus/11837
- https://learn.microsoft.com/en-us/answers/questions/585315/windows-could-not-start-the-openssh-ssh-server-ser.html
- https://support.microsoft.com/en-us/topic/21d87365-20cc-4b32-95a9-8e73961863ed
- https://learn.microsoft.com/en-us/troubleshoot/windows-server/virtualization/vmbus-device-not-load
- https://learn.microsoft.com/en-us/troubleshoot/windows-client/performance/error-1058-displayed-when-service-stops
- https://askubuntu.com/questions/836048/ssh-returns-no-matching-host-key-type-found-their-offer-ssh-dss
- https://stackoverflow.com/questions/45841206/how-to-enable-password-ssh-authentication-for-vagrant-vm
- https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings#config-ssh-extra_args
- https://superuser.com/questions/804214/how-to-enable-vagrants-verbose-mode
- https://developer.hashicorp.com/vagrant/docs/cli/ssh
- https://www.openssh.com/releasenotes.html (Search of supported algorithms)
- https://stackoverflow.com/questions/32686530/whats-openssh-default-kexalgorithms
- https://www.openssh.com/legacy.html
- https://developer.hashicorp.com/vagrant/docs/vagrantfile/ssh_settings
- https://github.com/hashicorp/vagrant/issues/12533
- https://www.man7.org/linux/man-pages/man5/sshd_config.5.html
- https://github.com/openssh/openssh-portable/tree/V_3_7_P1

We used a base Vagrant box called `lluccia/winxp-rm`. We set up the environment with notepad++, SSL certificates in Firefox and other minor fixes. After that, we generated a private box for internal testing only.

**Comment by alberpilot** [comment]
Blocked: it's necessary to define a fix from Core (C service code). Waiting for a meeting and discussion.

**Comment by Panisher** [comment]
I solved this problem (Custom action CheckSvcRunning script error -2147217389) on two hosts by Resetting the WMI Repository (`winmgmt /resetrepository` and restart computer)

**Comment by pabechevb** [comment]
> I solved this problem (Custom action CheckSvcRunning script error -2147217389) on two hosts by Resetting the WMI Repository (`winmgmt /resetrepository` and restart computer)

This worked for me in a Windows Server 2022 Standard.
