### ISSUE TITLE
Engine - Check and improve the description of error messages

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#15210]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0| Engine| Manager| Packages/Sources | OS version |

It is necessary to check all messages reported by the engine to make them consistent and provide useful information for developers and users.

**Comment by nmkoremblum** [comment]
### Covered Files
- [x] api
  - [x] api.hpp
  - [x] registry.hpp
  - [x] wazuhRequest.hpp
  - [x] wazuhResponse.h
  - [x] catalog.cpp
  - [x] commands.cpp
  - [x] yml2Json.hpp
  - [x] catalog.hpp
  - [x] commands.hpp
  - [x] resource.hpp
  - [x] registry.cpp
  - [x] wazuhRequest.cpp
- [x] base
  - [x] baseTypes.hpp
  - [x] error.hpp
  - [x] expression.cpp
  - [x] expression.hpp
  - [x] graph.hpp
  - [x] name.hpp
  - [x] parseEvent.cpp
  - [x] parseEvent.hpp
  - [x] result.hpp
  - [x] logging
    - [x] logging.hpp
  - [x] profile
    - [x] profile.cpp
    - [x] profile.hpp
  - [x] utils
    - [x] baseMacros.cpp
    - [x] baseMacros.hpp
    - [x] getExceptionStack.hpp
    - [x] ipUtils.cpp
    - [x] ipUtils.hpp
    - [x] stringUtils.cpp
    - [x] stringUtils.hpp
    - [x] socketInterface
      - [x] unixDatagram.cpp
      - [x] unixDatagram.hpp
      - [x] unixInterface.cpp
      - [x] unixInterface.hpp
      - [x] unixSecureStream.cpp
      - [x] unixSecureStream.hpp
- [x] builder
  - [x] asset.cpp
  - [x] asset.hpp
  - [x] builder.hpp
  - [x] definitions.cpp
  - [x] definitions.hpp
  - [x] environment.cpp
  - [x] environment.hpp
  - [x] register.hpp
  - [x] registry.cpp
  - [x] registry.hpp
  - [x] syntax.hpp
  - [x] builders
    - [x] baseHelper.cpp
    - [x] baseHelper.hpp
    - [x] opBuilderFileOutput.cpp
    - [x] opBuilderFileOutput.hpp
    - [x] opBuilderHelperActiveResponse.cpp
    - [x] opBuilderHelperActiveResponse.hpp
    - [x] opBuilderHelperFilter.cpp
    - [x] opBuilderHelperFilter.hpp
    - [x] opBuilderHelperMap.cpp
    - [x] opBuilderHelperMap.hpp
    - [x] opBuilderHelperNetInfoAddress.cpp
    - [x] opBuilderHelperNetInfoAddress.hpp
    - [x] opBuilderKVDB.cpp
    - [x] opBuilderKVDB.hpp
    - [x] opBuilderLogParser.cpp
    - [x] opBuilderLogParser.hpp
    - [x] opBuilderSCAdecoder.cpp
    - [x] opBuilderSCAdecoder.hpp
    - [x] opBuilderWdb.cpp
    - [x] opBuilderWdb.hpp
    - [x] operationBuilder.cpp
    - [x] operationBuilder.hpp
    - [x] stageBuilderCheck.cpp
    - [x] stageBuilderCheck.hpp
    - [x] stageBuilderMap.cpp
    - [x] stageBuilderMap.hpp
    - [x] stageBuilderNormalize.cpp
    - [x] stageBuilderNormalize.hpp
    - [x] stageBuilderOutputs.cpp
    - [x] stageBuilderOutputs.hpp
    - [x] stageBuilderParse.cpp
    - [x] stageBuilderParse.hpp
  - [x] interface builder
    - [x] ivalidator.hpp
  - [x] outputs
    - [x] file.hpp
- [x] cmds
  - [x] cmdApiCatalog.hpp
  - [x] cmdApiEnvironment.hpp
  - [x] cmdGraph.hpp
  - [x] cmdKvdb.hpp
  - [x] cmdRun.hpp
  - [x] cmdTest.hpp
  - [x] connection.cpp
  - [x] connection.hpp
  - [x] cmdApiCatalog.cpp
  - [x] cmdApiEnvironment.cpp
  - [x] cmdGraph.cpp
  - [x] cmdKvdb.cpp
  - [x] cmdRun.cpp
  - [x] cmdTest.cpp
  - [x] stackExecutor.cpp
  - [x] stackExecutor.hpp
- [x] hlp
  - [x] hlp.hpp
  - [x] hlp.cpp
  - [x] hlpDetails.cpp
  - [x] hlpDetails.hpp
  - [x] logParser.cpp
  - [x] logParser.hpp
  - [x] specificParsers.cpp
  - [x] specificParsers.hpp
  - [x] tld.hpp
  - [x] date
    - [x] date.h
  - [x] tools
    - [x] example.yml
    - [x] hlpCli.cpp
- [x] json
  - [x] json.hpp
  - [x] json.cpp
- [x] kvdb
  - [x] kvdb.hpp
  - [x] kvdbManager.hpp
  - [x] kvdb.cpp
  - [x] kvdbManager.cpp
- [x] logicExpression
  - [x] logicExpression.hpp
  - [x] logicExpression.cpp
  - [x] logicExpressionEvaluator.hpp
  - [x] logicExpressionParser.cpp
  - [x] logicExpressionParser.hpp
- [x] main.cpp
- [x] router
  - [x] environmentManager.hpp
  - [x] runtimeEnvironment.hpp
  - [x] environmentManager.cpp
  - [x] runtimeEnvironment.cpp
  - ~_router.hpp~
- [x] rxbk
  - [x] rxFactory.hpp
  - [x] rxFactory.cpp
- [x] server
  - [x] engineServer.hpp
  - [x] wazuhStreamProtocol.hpp
  - [x] engineServer.cpp
  - [x] protocolHandler.cpp
  - [x] endpoints
    - [x] apiEndpoint.cpp
    - [x] apiEndpoint.hpp
    - [x] baseEndpoint.cpp
    - [x] baseEndpoint.hpp
    - [x] eventEndpoint.cpp
    - [x] eventEndpoint.hpp
    - ~_datagramSocketEndpoint.cpp~
    - ~_datagramSocketEndpoint.hpp~
    - ~_socketEndpoint.cpp~
    - ~_socketEndpoint.hpp~
    - ~_tcpEndpoint.cpp~
    - ~_tcpEndpoint.hpp~
    - ~_udpEndpoint.cpp~
    - ~_udpEndpoint.hpp~
- [x] store
  - [x] drivers
    - [x] fileDriver.hpp
    - [x] fileDriver.cpp
  - [x] interface store
    - [x] istore.hpp
- [x] wdb
  - [x] wdb.hpp
  - [x] wdb.cpp

**Comment by nmkoremblum** [comment]
Improving Messages printing desing

### Covered Files
- [ ] api
  - [ ] api.hpp
  - [ ] registry.hpp
  - [ ] wazuhRequest.hpp
  - [ ] wazuhResponse.h
  - [ ] catalog.cpp
  - [ ] commands.cpp
  - [ ] yml2Json.hpp
  - [ ] catalog.hpp
  - [ ] commands.hpp
  - [ ] resource.hpp
  - [ ] registry.cpp
  - [ ] wazuhRequest.cpp
- [ ] base
  - [ ] baseTypes.hpp
  - [ ] error.hpp
  - [ ] expression.cpp
  - [ ] expression.hpp
  - [ ] graph.hpp
  - [ ] name.hpp
  - [ ] parseEvent.cpp
  - [ ] parseEvent.hpp
  - [ ] result.hpp
  - [ ] logging
    - [ ] logging.hpp
  - [ ] profile
    - [ ] profile.cpp
    - [ ] profile.hpp
  - [ ] utils
    - [ ] baseMacros.cpp
    - [ ] baseMacros.hpp
    - [ ] getExceptionStack.hpp
    - [ ] ipUtils.cpp
    - [ ] ipUtils.hpp
    - [ ] stringUtils.cpp
    - [ ] stringUtils.hpp
    - [ ] socketInterface
      - [ ] unixDatagram.cpp
      - [ ] unixDatagram.hpp
      - [ ] unixInterface.cpp
      - [ ] unixInterface.hpp
      - [ ] unixSecureStream.cpp
      - [ ] unixSecureStream.hpp
- [ ] builder
  - [ ] asset.cpp
  - [ ] asset.hpp
  - [ ] builder.hpp
  - [ ] definitions.cpp
  - [ ] definitions.hpp
  - [ ] environment.cpp
  - [ ] environment.hpp
  - [ ] register.hpp
  - [ ] registry.cpp
  - [ ] registry.hpp
  - [ ] syntax.hpp
  - [ ] builders
    - [ ] baseHelper.cpp
    - [ ] baseHelper.hpp
    - [ ] opBuilderFileOutput.cpp
    - [ ] opBuilderFileOutput.hpp
    - [ ] opBuilderHelperActiveResponse.cpp
    - [ ] opBuilderHelperActiveResponse.hpp
    - [ ] opBuilderHelperFilter.cpp
    - [ ] opBuilderHelperFilter.hpp
    - [ ] opBuilderHelperMap.cpp
    - [ ] opBuilderHelperMap.hpp
    - [ ] opBuilderHelperNetInfoAddress.cpp
    - [ ] opBuilderHelperNetInfoAddress.hpp
    - [ ] opBuilderKVDB.cpp
    - [ ] opBuilderKVDB.hpp
    - [ ] opBuilderLogParser.cpp
    - [ ] opBuilderLogParser.hpp
    - [ ] opBuilderSCAdecoder.cpp
    - [ ] opBuilderSCAdecoder.hpp
    - [ ] opBuilderWdb.cpp
    - [ ] opBuilderWdb.hpp
    - [ ] operationBuilder.cpp
    - [ ] operationBuilder.hpp
    - [ ] stageBuilderCheck.cpp
    - [ ] stageBuilderCheck.hpp
    - [ ] stageBuilderMap.cpp
    - [ ] stageBuilderMap.hpp
    - [ ] stageBuilderNormalize.cpp
    - [ ] stageBuilderNormalize.hpp
    - [ ] stageBuilderOutputs.cpp
    - [ ] stageBuilderOutputs.hpp
    - [ ] stageBuilderParse.cpp
    - [ ] stageBuilderParse.hpp
  - [ ] interface builder
    - [ ] ivalidator.hpp
  - [ ] outputs
    - [ ] file.hpp
- [ ] cmds
  - [ ] cmdApiCatalog.hpp
  - [ ] cmdApiEnvironment.hpp
  - [ ] cmdGraph.hpp
  - [ ] cmdKvdb.hpp
  - [ ] cmdRun.hpp
  - [ ] cmdTest.hpp
  - [ ] connection.cpp
  - [ ] connection.hpp
  - [ ] cmdApiCatalog.cpp
  - [ ] cmdApiEnvironment.cpp
  - [ ] cmdGraph.cpp
  - [ ] cmdKvdb.cpp
  - [ ] cmdRun.cpp
  - [ ] cmdTest.cpp
  - [ ] stackExecutor.cpp
  - [ ] stackExecutor.hpp
- [ ] hlp
  - [ ] hlp.hpp
  - [ ] hlp.cpp
  - [ ] hlpDetails.cpp
  - [ ] hlpDetails.hpp
  - [ ] logParser.cpp
  - [ ] logParser.hpp
  - [ ] specificParsers.cpp
  - [ ] specificParsers.hpp
  - [ ] tld.hpp
  - [ ] date
    - [ ] date.h
  - [ ] tools
    - [ ] example.yml
    - [ ] hlpCli.cpp
- [ ] json
  - [ ] json.hpp
  - [ ] json.cpp
- [ ] kvdb
  - [ ] kvdb.hpp
  - [ ] kvdbManager.hpp
  - [ ] kvdb.cpp
  - [ ] kvdbManager.cpp
- [ ] logicExpression
  - [ ] logicExpression.hpp
  - [ ] logicExpression.cpp
  - [ ] logicExpressionEvaluator.hpp
  - [ ] logicExpressionParser.cpp
  - [ ] logicExpressionParser.hpp
- [ ] main.cpp
- [ ] router
  - [ ] environmentManager.hpp
  - [ ] runtimeEnvironment.hpp
  - [ ] environmentManager.cpp
  - [ ] runtimeEnvironment.cpp
  - ~_router.hpp~
- [ ] rxbk
  - [ ] rxFactory.hpp
  - [ ] rxFactory.cpp
- [ ] server
  - [ ] engineServer.hpp
  - [ ] wazuhStreamProtocol.hpp
  - [ ] engineServer.cpp
  - [ ] protocolHandler.cpp
  - [ ] endpoints
    - [ ] apiEndpoint.cpp
    - [ ] apiEndpoint.hpp
    - [ ] baseEndpoint.cpp
    - [ ] baseEndpoint.hpp
    - [ ] eventEndpoint.cpp
    - [ ] eventEndpoint.hpp
    - ~_datagramSocketEndpoint.cpp~
    - ~_datagramSocketEndpoint.hpp~
    - ~_socketEndpoint.cpp~
    - ~_socketEndpoint.hpp~
    - ~_tcpEndpoint.cpp~
    - ~_tcpEndpoint.hpp~
    - ~_udpEndpoint.cpp~
    - ~_udpEndpoint.hpp~
- [ ] store
  - [ ] drivers
    - [ ] fileDriver.hpp
    - [ ] fileDriver.cpp
  - [ ] interface store
    - [ ] istore.hpp
- [ ] wdb
  - [ ] wdb.hpp
  - [ ] wdb.cpp
