### ISSUE TITLE
Rootcheck logs are logged under the syscheck name

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#15238]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | Rootcheck | Agent | Packages | macOS |

Hello team!

Just wanted to report that some rootcheck actions are getting logged in `ossec.log` as if they were `syscheck` actions.
I've enabled debug mode for `syscheck` to troubleshoot other issue, and noticed that I was getting events similar to next ones:
```
2022/10/21 20:34:43 wazuh-syscheckd[78456] fs_op.c:88 at IsNFS(): DEBUG: Attempted to check NFS status for '/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/test/test_warnings/data', but we don't know how on this OS.
2022/10/21 20:34:43 wazuh-syscheckd[78456] fs_op.c:119 at skipFS(): DEBUG: Attempted to check FS status for '/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/test/test_warnings/data', but we don't know how on this OS.
2022/10/21 20:34:43 wazuh-syscheckd[78456] fs_op.c:119 at skipFS(): DEBUG: Attempted to check FS status for '/usr/local/Cellar/python@3.9/3.9.15/Frameworks/Python.framework/Versions/3.9/lib/python3.9/test/test_warnings', but we don't know how on this OS.
```

The thing is that syscheck was configured by default (except its `frequency`):
![image](https://user-images.githubusercontent.com/29696136/197904785-2e5e31a4-0b7c-48a2-b302-55e844e443e9.png)
And as you can see, `/usr/local` was not being monitored by `syscheck`.

I then got this tested:
```
2022/10/25 08:56:55 rootcheck[23072] check_rc_sys.c:397 at check_rc_sys(): DEBUG: Starting on check_rc_sys
2022/10/25 08:56:55 wazuh-syscheckd[23072] fs_op.c:91 at IsNFS(): DEBUG: Attempted to check NFS status for '/bin', but we don't know how on this OS.
2022/10/25 08:56:55 wazuh-syscheckd[23072] fs_op.c:122 at skipFS(): DEBUG: Attempted to check FS status for '/bin', but we don't know how on this OS.
```
Here, you can see that when the log is produced in the Rootcheck code (first log), the program name is correct. However, when logging in a shared funcion such as skipFS the program name is wazuh-syscheckd which is the name of the daemon that run Rootcheck.

**Comment by havidarou** [comment]
Closed as not planned.
