### ISSUE TITLE
Update MITRE ATT&CK DB to v13.1

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#15235]
|Wazuh version|Component|Action type|
|---|---|---|---|---|
|4.4.x| Ruleset | Manager | Improve |

New ATT&CK version was released on April 25 2023.
Review new content and update rules and database accordingly.

https://github.com/mitre/cti/releases/tag/ATT%26CK-v13.0

**Comment by 00willo** [comment]
ATT&CK v13 is due in around the end of April as well.

**Comment by ooniagbi** [comment]
# Setup

1. Downloaded the latest available Wazuh OVA.
2. Cloned the branch with the updated `enterprise-attack.json` file.
3. Used the `mitredb.py` script to create a new DB that uses the latest file: `/var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db`.
# Tests
The test were using the Wazuh API and ruleset change with a new MITRE technique ID (`attack-pattern--0042a9f5-f053-4769-b3ef-9ad018dfa298`)

## Wazuh API screenshots
### Old DB
![image](https://github.com/wazuh/wazuh/assets/97736018/4b655f30-2b9c-4948-9766-7f2f8af19c6b)
### New DB
![image](https://github.com/wazuh/wazuh/assets/97736018/2d287df3-ceeb-46dc-9bd2-70a69cc8a372)
## Wazuh ruleset tests
The MITRE ID of this new technique is `T1650`, so I changed an existing rule (`5715`) to use this MITRE ID.
### Screenshot:
![image](https://github.com/wazuh/wazuh/assets/97736018/75054905-0769-4ae2-a00c-229780d56d71)
