### ISSUE TITLE
Wazuh API Syscollector hardware on VM

### ISSUE THREAD

**Issue by ITINVENTBE** [wazuh/wazuh#15234]
The Syscollector API while the agent is installed on a VM, reports the hardware of the physical machine and not of the virtual machine.
I would like the monitor the individual machine's hardware stats like ram free instead of the physical machine.

when polling: `https://ipaddress:55000/syscollector/{$agentID}/hardware`

Returning values are:

```
  [0]=>
  array(2) {
    ["ramfree"]=>int(5675148)
    ["ramtotal"]=>int(16392940)
  }
```
  
  The windows machine this agent is installed on, only has 8GB of ram available, instead it's barebone host has 16GB.
  The free indicator also represents the free memory on the host and not the VM.

**Comment by Dwordcito** [comment]
Hi @ITINVENTBE I hope you are well.

Could you tell me what platform you are using to virtualize? 
I will try to reproduce the problem to identify the problem and analyze the solution.

**Comment by ITINVENTBE** [comment]
Hello @Dwordcito 

Thanks for your message, I'm using Vsphere ESXI 7.2 hypervisor as a barebone host.

**Comment by mjcr99** [comment]
Hi team I have run a quick test using VirtualBox.

The allocated RAM for the VM is as follows:

| VM OS| |
|---|---|
| Ubuntu22 | 3Gb |
| mac OS 10.15 | 3Gb |
| mac OS 10.15 (1) | 4Gb |

An the retrieved information in each case is the following:
| VM OS|board_serial|cpu_name|cpu_cores|cpu_mhz|ram_total|ram_free|ram_usage|checksum|db_status_field_dm|
|---|---|---|---|---|---|---|---|---|---|
|Ubuntu22|0|AMD Ryzen 7 1700 Eight-Core Processor   |2|2995.0|3054124|2731784|11|993af880219310503e0e7fc0e9645f7a514933b7|1|
|mac OS 10.15|0|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz|2|2990.0|3145728|1461808|54|700f952b8a6ef18e7345ce0c93f12e52b46d053d|1|
|mac OS 10.15 (1) |0|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz                             |2|2990.0|4194304|2978428|29|d7bce0d93031ea4d361b088aca9201a248f2d172|1|

Using VirtualBox the allocated and the retrieved amount of ram is the same for the tested OSs.

**Comment by MarcelKemp** [comment]
These same tests have been carried out with a **`WSL v2`** environment, and **`Hyper-V`**, where in both cases the allocated RAM memory and hardware are obtained correctly according to the limitations imposed on each environment.

**Comment by vikman90** [comment]
## Memory Reserved vs. Memory Limited

As I understand it, vSphere ESXi has the following memory parameters:

- **Configured Memory:** This is the amount of memory you set when creating the virtual machine.
- **Reserved Memory:** This is the amount of memory that ESXi guarantees for the virtual machine. If you do not set any reservation, it defaults to zero.
- **Memory Limit:** This is the maximum amount of memory that the virtual machine can use. If you set a limit, this value may be lower than the configured memory.

We are wondering if the parameter you are configuring is configured memory. In any case, the value that the Syscollector API returns for system RAM should match the data that the operating system returns.

If your VM uses Windows, please try this script:

```powershell
$memStatus = Get-WmiObject -Class Win32_OperatingSystem

"Total Physical Memory (MB): " + [math]::round($memStatus.TotalVisibleMemorySize / 1KB, 2)
"Free Physical Memory (MB): " + [math]::round($memStatus.FreePhysicalMemory / 1KB, 2)
"Total Virtual Memory (MB): " + [math]::round($memStatus.TotalVirtualMemorySize / 1KB, 2)
"Free Virtual Memory (MB): " + [math]::round($memStatus.FreeVirtualMemory / 1KB, 2)
"Total Visible Memory (MB): " + [math]::round($memStatus.TotalVisibleMemorySize / 1KB, 2)
"Free Memory (Percentage): " + [math]::round(($memStatus.FreePhysicalMemory / $memStatus.TotalVisibleMemorySize) * 100, 2) + "%"
```
