### ISSUE TITLE
FIM: 'was added' alerts reported at the first iteration

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1524]
## Bug report

**OS**
_Windows8.1_

**Wazuh version**
_3.7.0-3702_

**Install method**
_sources_

Bug description
----------------
After the second scan or after restarting the agent subsequently to the second scan, the file path that ``whodata`` was generating contained a 'C:\' instead of 'c:\', which is the one that is generated when the configuration is read and the alerts generated by realtime.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/1543.
