### ISSUE TITLE
firewall issue

### ISSUE THREAD

**Issue by Noorpa1** [wazuh/wazuh#15256]
2022/09/29 00:00:18 ossec-monitord: No previous sha1 checksum found: '/logs/archives/2022/Sep/ossec-archive-27.log.sum'. Starting over.
2022/09/29 00:00:18 ossec-monitord(1103): ERROR: Could not open file '/logs/archives/2022/Sep/ossec-archive-28.log.sum' due to [(2)-(No such file or directory)].

**Comment by pereyra-m** [comment]
Hello @Noorpa1 !

This doesn't seem a firewall issue but a problem with your logs' folders.
What is your Wazuh version? The date of issue is a month ago, does it keep happening? Could you upload your `ossec.log` file?

The Wazuh daemon `ossec-monitord` is in charge of the logs rotation and it performs these operations at midnight. These logs aren't deleted by default, have you configured an automated task to do so?

Also, we can see in the error that it's talking about the `archives` folder, did you enable the [logall](https://documentation.wazuh.com/4.3/user-manual/reference/ossec-conf/global.html#logall) option? This could make the system run out of space quickly.

Regards.
