### ISSUE TITLE
New API call IS_SYNC

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1526]
We need to implement an API call that let the user know if the agent has the merged file synced.

The call would be like this:

GET /agents/001/group/is_sychronized

**Comment by TJOSERAFAEL** [comment]
This PR solves the issue: https://github.com/wazuh/wazuh-api/pull/180

**Comment by mgmacias95** [comment]
Done in https://github.com/wazuh/wazuh-api/pull/180 and https://github.com/wazuh/wazuh/pull/1527
