### ISSUE TITLE
The wazuh-dbd module causes a service interruption after an INSERT SQL error 

### ISSUE THREAD

**Issue by adilbml** [wazuh/wazuh#15266]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | wazuh-dbd | Manager | Sources | Ubuntu 20.04 |

Hello, I would like to know if it would be possible for you to help me because unfortunately I am trying to outsource the alerts to an external mysql database, the connection is going well as shown in the screenshot, but then it there is an SQL command error "5203" and the connection is interrupted, can you help me investigate the problem? I specify the module "wazuh-dbd" is well started. Thank you

I checked the rights everything is good I manage to connect to the database with the user created and he has all the rights on this database, in fact he manages to connect but an SQL query failed and the connection interrupted, but yet he has all the rights!

Of course I also made sure to fill in the "database_output" tag and the necessary information, no error on the compilation of wazuh with mysql too.

![wazuh-dbd](https://user-images.githubusercontent.com/57867101/199039675-7de5907d-dbe2-4ed1-a1a2-b07a2a2d2310.PNG)

`<database_output>`
  `<hostname>x.x.x.x</hostname>`
  `<username>MySQLadmin</username>`
  `<password>secret1234</password>`
 `<database>Alerts_DB</database>`
  `<type>mysql</type>`
`</database_output>`

**Comment by lameirat** [comment]
hi, any news about this issue?
