### ISSUE TITLE
Wazuh Cluster with two Master VMs 

### ISSUE THREAD

**Issue by skhanum** [wazuh/wazuh#15273]
Hello Team,

We already have a Wazuh Cluster in production with one Master VM and 2 Worker VMs with a Load balancer. For Master HA, We are trying to add another Master VM in the same cluster.
Can we have two active Master VMs, or Active-Passive model for Master VMs, in case if one goes down and other takes it place automatically?

If that's possible, can we have the steps for setting up second active Master node 

 https://documentation.wazuh.com/current/deployment-options/elastic-stack/distributed-deployment/wazuh-cluster/wazuh-multi-node-cluster.html

**Comment by vikman90** [comment]
Hi @skhanum, I think your question is related to task #811, which aims to implement support to define multiple master nodes. That is currently in the icebox.

Best regards.

**Comment by skhanum** [comment]
hi @vikman90 
Yes, I was looking for this configuration to avoid impact if Master goes down.

Do we have any ETA or a release date to support multiple Master nodes for HA

If Master goes down, the agents enrolled on the Master will be moved to worker nodes automatically? Will it impact the new enrollments? Could you also help me with other impacts in case if Master is unavailable?

**Comment by vikman90** [comment]
@skhanum I'm afraid that issue is in the icebox, thus, there is no ETA or target version yet.

Currently, the Wazuh Cluster requires that the master node is available. If not, we won't be able to register agents or make API queries.

Best regards.

**Comment by skhanum** [comment]
Thanks @vikman90 
I am hoping the already registered agents on the Master will be moved to worker nodes if there is any issue with Master and only the new registrations/enrollments will be impacted?

Please correct me if I am wrong

**Comment by vikman90** [comment]
Hi @skhanum,

You're right. Agent registration is always performed on the master node. When agents try to enroll in worker nodes, they forward the request to the master. Then, the cluster syncs the file `etc/client.keys` to the workers. Thus, when workers have the agent key in their `etc/client.keys`, the agent is able to connect to them, produce alerts and synchronize the inventory, even if the master node goes offline.

Best regards.

**Comment by skhanum** [comment]
Thanks for the help @vikman90 
We are good to close

**Comment by vikman90** [comment]
My pleasure @skhanum. So I'm closing this issue.

Best regards.

**Comment by ramzcode** [comment]
So if the Master goes down then API and Dashboard services will be also be unavailable correct ?
