### ISSUE TITLE
Wazuh unable to read data from s3 bucket for aws waf logs.

### ISSUE THREAD

**Issue by codewarriormpl** [wazuh/wazuh#15289]
Wazuh version App version: 4.3.1 

I was following this doc https://documentation.wazuh.com/current/amazon/services/supported-services/waf.html to send amazon waf logs to wazuh but we are currently unable to read data from s3 bucket.

Wazuh is not able to read the data from s3 bucket .

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="waf">
    <name>wazuh-aws-wodle</name>       <!-- PUT HERE THE S3 BUCKET CHOSEN IN STEP 7 -->
    <path>waf</path>                   <!-- PUT HERE THE PREFIX CHOSEN IN STEP 7 -->
    <aws_profile>default</aws_profile>
  </bucket>
</wodle>
```
We followed this and added s3 bucket and also given permission to the aws profile.  Whenever we change  the config to above and restart it, wazuh fails to start and throws error and dashboard also not loading.

**Comment by CarlosRS9** [comment]
Hello @codewarriormpl 

In order to help you better we will need you to share with us that error message.

Also, please make sure that the configuration you are using is identical to the one you have shared, and that there is a `default` profile with valid credentials present in `~/.aws/credentials` as explained [here](https://documentation.wazuh.com/current/amazon/services/prerequisites/credentials.html#profiles).

**Comment by codewarriormpl** [comment]
@CarlosRS9 sorry for delay in response. Yes we are using the same credentials. We tried using both aws default profile and <aws_profile>default</aws_profile> and secret key configuration . attached is SS for the same along with logs and error. 
<img width="1629" alt="Screenshot 2022-11-10 at 1 09 28 PM" src="https://user-images.githubusercontent.com/117352024/201036502-959819b5-1bb4-4694-b0e4-c466c6bd7a3c.png">

<img width="1629" alt="Screenshot 2022-11-10 at 1 19 35 PM" src="https://user-images.githubusercontent.com/117352024/201036528-092026d2-feaf-49d9-b1b0-45f62abea821.png">

<img width="1629" alt="Screenshot 2022-11-10 at 1 24 58 PM" src="https://user-images.githubusercontent.com/117352024/201036536-3e9d175f-508d-44ac-8b5e-86d14c1439e6.png">

**Comment by CarlosRS9** [comment]
@codewarriormpl sorry for the delay in my response too.

That error indicates a problem in the `ossec.conf` configuration parser. Make sure that the whole `wodle` block is inside the main `<ossec_config>` tag, in the same way as the rest of the Wazuh configurations. It should not be outside it. For example:
```
<ossec_config>
	<wodle name="aws-s3">
	  <disabled>no</disabled>
	  <interval>10m</interval>
	  <run_on_start>yes</run_on_start>
	  <skip_on_error>yes</skip_on_error>
	  <bucket type="waf">
	    <name>wazuh-aws-wodle</name>       <!-- PUT HERE THE S3 BUCKET CHOSEN IN STEP 7 -->
	    <path>waf</path>                   <!-- PUT HERE THE PREFIX CHOSEN IN STEP 7 -->
	    <aws_profile>default</aws_profile>
	  </bucket>
	</wodle>
</ossec_config>
```
Let me know if this was the issue.

**Comment by codewarriormpl** [comment]
@CarlosRS9 Thank you very much for the response. I eventually figured out the same. I wish we could update the doc though.
