### ISSUE TITLE
IPv6 address is being displayed for the agents

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh#15306]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Manager | Manager/Agent | Packages | Multiple Linux distros |

**Description**
Agents' section shows the IPv6 address instead of IPv4.
![dashboard_ipv6](https://user-images.githubusercontent.com/33964202/199797301-c7fcd049-5030-4af3-a354-831e111f44b4.png)

**Steps to reproduce**
1. Navigate to Wazuh > Agents
2. The list will display the IPv6 address for the agents.

**Expected Result**
1. Get the IPv4 address for the agents.

**Actual Result**
1. The IPv6 address is being displayed.

**Additional context**
We have seen this in the demo environment. The deployment pipeline and configurations have not changed from 4.3 to 4.4.

I have tested with telnet from the RHEL7 agent to the Manager LB. Here are the results:

- IPv6

```TXT
telnet -6 demoxxxxxxx.xxxx.xxxx.com 1515
telnet: demoxxxxxxx.xxxx.xxxx.com: Name or service not known
demoxxxxxxx.xxxx.xxxx.com: Unknown host
```

- IPv4

```TXT
telnet demoxxxxxxx.xxxx.xxxx.com 1515
Trying <IPv4Address>...
Connected to demoxxxxxxx.xxxx.xxxx.com.
Escape character is '^]'.
```

Additionally, the Manager's load balancer does only have IPv4 enabled.

**Finally we have executed a SQL query to the `global.db` and found that the IP for the agents is IPv6 when it should be the IPv4 one:**

```
sqlite3 /var/ossec/queue/db/global.db "select ip from agent where id=003;"
FE80:0000:0000:0000:0081:87FF:FEC5:0357
```

**Comment by jnasselle** [comment]
It seems to be duplicated from https://github.com/wazuh/wazuh/issues/14988
