### ISSUE TITLE
Regex contradicts with Nano syntax for OpenVPN-Wazuh Custom Decoder 

### ISSUE THREAD

**Issue by rumi-20** [wazuh/wazuh#15309]
Hi,

I am trying to write custom decoder for OpenVPN in Wazuh, as the logs are directly written to the file and not via syslog. The regex is working fine as I am writing/testing it in https://regexlearn.com/playground and https://regex101.com/ before making changes to the local_decoder.xml file. ()For instance, for the log:

![image](https://user-images.githubusercontent.com/59825087/200166536-c1b603eb-bb06-4638-b6df-dcf5ed078185.png)
![image](https://user-images.githubusercontent.com/59825087/200166499-b77c8a4d-e832-428d-92b0-d00e5773a45f.png)
Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]132.32.167.9:60048
OR
Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET6]::ffff:132.32.167.9:60048

I have written a decoder of:

`<decoder name="openvpn-HMAC">
<prematch>AF_INET6?</prematch>
<regex>(::(\S+)?:)?(\d+\.\d+\.\d+\.\d+):(\d+)</regex>
<order>srcip,srcport</order>
</decoder>`

OR

`<decoder name="openvpn-HMAC">
<prematch>AF_INET6?</prematch>
<regex>(?<=])((\S+)?:(\S+)?:(\S+):)?(\d+\.\d+\.\d+\.\d+):(\d+)</regex>
<order>srcip,srcport</order>
</decoder>`

Both regex works fine in above share links for extracting the right values but for the first one Wazuh-manager fails to restart with an error of **ERROR: (1452): Syntax error on regex: '(::(\S+)?:)?(\d+\.\d+\.\d+\.\d+):(\d+)'**

While for the second the '<' changes the code/contradicts with Nano, I assume.
![image](https://user-images.githubusercontent.com/59825087/200166018-2d7673a0-0bb2-4ff4-bfdc-94700263b454.png)

**Update:** I know the regex is quite simple and it can be optimized (which I did for my first simple decoder regex from `(\d+\.\d+\.\d+\.\d+):(\d+) to (\d+\.?)+:(\d+)`). But the update is the decoder I first wrote initially and was working fine, is not extracting the correct fields now, even when i return to (\d+\.\d+\.\d+\.\d+):(\d+). I really don't understand why its happening. 

Will really appreciate some help!

**Comment by nmkoremblum** [comment]
Hi @rumi-20,

Is this address correct?

> ::ffff:132.32.167.9:60048

I will be waiting for your reply,

Mariano Koremblum

**Comment by nmkoremblum** [comment]
Hi @rumi-20!

After analyzing your case I developed the following decoders that you may find useful:

```xml
<decoder name="openvpn-HMAC">
   <prematch type="pcre2">HMAC[^\[]+\[AF_INET[6]*\]</prematch>
</decoder>

<!-- decodes ipv4 -->
<decoder name="openvpn-HMAC-ipv4">
  <parent>openvpn-HMAC</parent>
  <regex offset="after_parent" type="pcre2">(\d+.\d+.\d+.\d+):(\d+)</regex>
  <order>srcip, srcport</order>
</decoder>

<!-- decodes ipv6 -->
<decoder name="openvpn-HMAC-ipv6">
  <parent>openvpn-HMAC</parent>
  <regex offset="after_parent" type="pcre2">\w*:\w*:\w*[:]*(\d+\.\d+\.\d+\.\d+):(\d+)</regex>
  <order>srcip, srcport</order>
</decoder>
```

This would only work for IPV6s of the format that you have provided, if not the regex should be adapted. You can check how does it work by using our tool [wazuh-logtest](https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/index.html) which output is:
```
# /var/ossec/bin/wazuh-logtest                  
Starting wazuh-logtest v4.3.9
Type one log per line

Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]132.32.167.9:60048

**Phase 1: Completed pre-decoding.
	full event: 'Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]132.32.167.9:60048'
	timestamp: 'Oct 14 00:45:55'
	hostname: '2022'

**Phase 2: Completed decoding.
	name: 'openvpn-HMAC'
	srcip: '132.32.167.9'
	srcport: '60048'

**Phase 3: Completed filtering (rules).
	id: '1002'
	level: '2'
	description: 'Unknown problem somewhere in the system.'
	groups: '['syslog', 'errors']'
	firedtimes: '1'
	gpg13: '['4.3']'
	mail: 'False'

Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET6]::ffff:132.32.167.9:60048

**Phase 1: Completed pre-decoding.
	full event: 'Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET6]::ffff:132.32.167.9:60048'
	timestamp: 'Oct 14 00:45:55'
	hostname: '2022'

**Phase 2: Completed decoding.
	name: 'openvpn-HMAC'
	srcip: '132.32.167.9'
	srcport: '60048'

**Phase 3: Completed filtering (rules).
	id: '1002'
	level: '2'
	description: 'Unknown problem somewhere in the system.'
	groups: '['syslog', 'errors']'
	firedtimes: '2'
	gpg13: '['4.3']'
	mail: 'False'
```

In order to make your own rules and decoders I would recommend you to read the following links:

- https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/
- https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
- https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html
- https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html

Please, let us know if this is useful for you!

Mariano Koremblum

**Comment by rumi-20** [comment]
> Hi @rumi-20!
> 
> After analyzing your case I developed the following decoders that you may find useful:
> 
> ```
> <decoder name="openvpn-HMAC">
>    <prematch type="pcre2">HMAC[^\[]+\[AF_INET[6]*\]</prematch>
> </decoder>
> 
> 
> <decoder name="openvpn-HMAC-ipv4">
>   <parent>openvpn-HMAC</parent>
>   <regex offset="after_parent" type="pcre2">(\d+.\d+.\d+.\d+):(\d+)</regex>
>   <order>srcip, srcport</order>
> </decoder>
> 
> 
> <decoder name="openvpn-HMAC-ipv6">
>   <parent>openvpn-HMAC</parent>
>   <regex offset="after_parent" type="pcre2">\w*:\w*:\w*[:]*(\d+\.\d+\.\d+\.\d+):(\d+)</regex>
>   <order>srcip, srcport</order>
> </decoder>
> ```
> 
> This would only work for IPV6s of the format that you have provided, if not the regex should be adapted. You can check how does it work by using our tool [wazuh-logtest](https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/index.html) which output is:
> 
> ```
> # /var/ossec/bin/wazuh-logtest                  
> Starting wazuh-logtest v4.3.9
> Type one log per line
> 
> Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]132.32.167.9:60048
> 
> **Phase 1: Completed pre-decoding.
> 	full event: 'Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET]132.32.167.9:60048'
> 	timestamp: 'Oct 14 00:45:55'
> 	hostname: '2022'
> 
> **Phase 2: Completed decoding.
> 	name: 'openvpn-HMAC'
> 	srcip: '132.32.167.9'
> 	srcport: '60048'
> 
> **Phase 3: Completed filtering (rules).
> 	id: '1002'
> 	level: '2'
> 	description: 'Unknown problem somewhere in the system.'
> 	groups: '['syslog', 'errors']'
> 	firedtimes: '1'
> 	gpg13: '['4.3']'
> 	mail: 'False'
> 
> Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET6]::ffff:132.32.167.9:60048
> 
> **Phase 1: Completed pre-decoding.
> 	full event: 'Oct 14 00:45:55 2022 us=175209 132.32.167.9:60048 TLS Error: cannot locate HMAC in incoming packet from [AF_INET6]::ffff:132.32.167.9:60048'
> 	timestamp: 'Oct 14 00:45:55'
> 	hostname: '2022'
> 
> **Phase 2: Completed decoding.
> 	name: 'openvpn-HMAC'
> 	srcip: '132.32.167.9'
> 	srcport: '60048'
> 
> **Phase 3: Completed filtering (rules).
> 	id: '1002'
> 	level: '2'
> 	description: 'Unknown problem somewhere in the system.'
> 	groups: '['syslog', 'errors']'
> 	firedtimes: '2'
> 	gpg13: '['4.3']'
> 	mail: 'False'
> ```
> 
> In order to make your own rules and decoders I would recommend you to read the following links:
> 
> * https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/
> * https://documentation.wazuh.com/current/user-manual/ruleset/custom.html
> * https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html
> * https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html
> 
> Please, let us know if this is useful for you!
> 
> Mariano Koremblum

Hi @nmkoremblum,

I tried the decoders and they worked perfectly fine. Thank you for the help.

Just one thing though, I still don't understand, and will appreciate an insight on why they were not working as there isn't any apparent issue.  

Thanks again!

**Comment by nmkoremblum** [comment]
You are welcome!! I am glad that it worked :smile:.

The error is probably due to the fact that both the `prematch` and `regex` use `osregex` as the default regex type and some of the symbols that you are using is not supported by it. This situation is described in the links I shared with you before.

Best regards,

Mariano Koremblum

**Comment by nmkoremblum** [comment]
@rumi-20 I am closing this issue, feel free to re-open it if you still have problems with this.

Best regards,

Mariano Koremblum
