### ISSUE TITLE
Windows Installation fails when using multiple words in deployment variables

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#15304]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | MSI| Agent | Packages | Windows |

We were notified by @roronoasins from QA team in this issue:
https://github.com/wazuh/wazuh-qa/issues/3317

That if we use multiple words as authentication password in the deployment variables the MSI installation fails.

**Command:** `.\wazuh-agent-4.4.0-0.msi /q WAZUH_MANAGER="172.31.11.241" WAZUH_REGISTRATION_PASSWORD="123 asd" `
**Output:**
![image](https://user-images.githubusercontent.com/19505384/199972244-ae856e1d-5ec5-4052-a7cd-21ca48e205a2.png)

The error appears because the deployment variables are passed to the MSI and then used to set the arguments for [InstallerScripts.vbs](https://github.com/wazuh/wazuh/blob/master/src/win32/InstallerScripts.vbs) in this line:
https://github.com/wazuh/wazuh/blob/7bc6916eccbae96c57a049a2123cd21a979ed5cc/src/win32/wazuh-installer.wxs#L93

In this process, the words are split causing the VBS script to receive more arguments than expected and provoking a compilation error.

We can avoid this error with a workaround by passing the variables like this:
```
\wazuh-agent-4.4.0-0.msi /q  WAZUH_REGISTRATION_PASSWORD='"123 asd"'
```

**Comment by DFolchA** [comment]
## Update

After investigating this issue we have found that the problem comes from the setting of the `property`, according to Microsoft documentation:
https://learn.microsoft.com/en-us/windows/win32/msi/setting-public-property-values-on-the-command-line

If a `property` contains a space it needs a quote but in our tests, it is necessary to either use `"""` or `'"` to set the property and avoid the error.

We found these threads showing the same problem and similar solutions:
https://www.itninja.com/question/how-to-escape-quotes-when-passing-custom-public-properties-to-an-msi-through-an-exe
https://stackoverflow.com/questions/55176548/msiexec-not-installing-when-property-value-contains-a-space-within-quotes

## Update 2 

After some more investigation we found that this issue only appears when installing from PowerShell if we use cmd to install the package, the command:
```
.\wazuh-agent-4.4.0-0.msi /q WAZUH_MANAGER="172.31.11.241" WAZUH_REGISTRATION_PASSWORD="123 asd" 
```
Works properly.

We found the following thread:
https://stackoverflow.com/questions/44498335/command-line-arguments-for-msiexec-break-on-powershell-if-they-contain-space

**Comment by DFolchA** [comment]
## Update: Powershell Workarround

For this to work in PowerShell if for example, our password is `HELLO WORLD` we need to use:
```
.\wazuh-agent-4.4.0-0.msi /q WAZUH_REGISTRATION_PASSWORD="""HELLO WORLD"""
```

Or
```
.\wazuh-agent-4.4.0-0.msi /q WAZUH_REGISTRATION_PASSWORD='"HELLO WORLD"'
```

To set a password with multiple words using deployment variables.

**Comment by alberpilot** [comment]
Blocked by: https://github.com/wazuh/wazuh-documentation/issues/5738

**Comment by alberpilot** [comment]
This issue doesn't require installer changes, only documentation changes. I proceed to close this issue and only https://github.com/wazuh/wazuh-documentation/issues/5738 is pending.
