### ISSUE TITLE
Feature Request: Vulnerability Filter

### ISSUE THREAD

**Issue by gitbock** [wazuh/wazuh#15308]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9-40322 | Vulnerability-Detector | Manager | Packages | Ubuntu LTS 22 |

For detecting vulnerabilities, one can create rules to adapt behavior of reporting in "discover"/logs. 

However, the vulnerability detector pushes detected vulnerabilities directly into the SQLite DB of an agent without adhering to any rules.

This FR suggests introducing a filter option for detected vulnerabilities. Like this the manager can be configured to put only vulns into the SQLite DB according to the filter.
Facilitating the [ERD schema](https://github.com/wazuh/wazuh/issues/5206#issuecomment-646325880) this should be possible by the fields/columns. E.g. "status"

```
<vulnerability-detector>
    <provider name="canonical">

    <!-- Filter for Status: only packages with fixed status will be reported  -->
    <filter name="status">FIXED</filter>

    <enabled>yes</enabled> 
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <update_interval>1h</update_interval>
    </provider>
  </vulnerability-detector>
```

References: 
https://groups.google.com/g/wazuh/c/mg-PX7CBjoQ

**Comment by Dwordcito** [comment]
I am understanding that you want to add suppressions to the detections made by the vulnerabilities module or exclusions previous of the scanner.

It's a good point, as you can silence some specific CVEs and any packages you want to skip.

I'm going to comment that we are in the middle of refactoring the module, in which we will add the capacity you are indicating. Vulnerability detector will no longer work in the current way but will have a more intuitive behavior.

Epic: https://github.com/wazuh/wazuh/issues/14153
