### ISSUE TITLE
Add protection for untrusted libraries load

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#15327]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-rev | Main process | Agent | Packages/Sources | Windows |

## Description
This issue aims to add protections, to prevent the loading of libraries that are not trusted.

This purpose is due to the fact that a library that proxy the system ones can be loaded in the process and execute code, for which Wazuh is not intended.

The main idea is that we only load libraries that are trusted by a CA, 

This is done by hooking LdrInitDll, which is responsible for making the actual load. At that point, we carry out the verification and give the loading approval.

**Comment by vikman90** [comment]
@Dwordcito @pereyra-m great job!

Thanks for the update, let me give you some feedback:

- #15496 should block this issue.
- In addition to disabling DLL verification on Windows XP and Server 2003 (under Vista), and in view of the problems with the presence of valid CAs on some systems, we propose to divide this development into two phases. The first would only alert that the binaries could not be verified. In a second phase, we would add enforcement to such verification.
- We expect the DLL verification to be enabled by default (when supported). Maybe we can define `IMAGE_TRUST_CHECKS` this way:

|`IMAGE_TRUST_CHECKS`|Default|Description|
|---|:-:|---|
|`0` or undefined||Verification disabled.|
|`1`|✅|Check binaries and warn if verification fails.|
|`2`||Enforce binary check. Stop the agent service if verification fails.|

Cheers!
