### ISSUE TITLE
Avoid handles inheritance when it's not necessary

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#15337]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5 | - | Manager/Agent | Packages/Sources | All |

From the development of [Fail when upgrading a Windows wazuh-agent using WPK](https://github.com/wazuh/wazuh/issues/14857) it was noticed that in the code there are many calls to functions related to files management, execution of new processes/threads and socket handling for which it is not controlled or it is not necessary to inherit the resource handles of the processes. Since this produces a dependency on the resources that can generate problems when, for example, ending a process as in the above case.

That is why this issue is opened. To analyze the code to find out when is not necessary inherit handles with the following functions calls:

- `fopen`: This function call should be replaced with `wfopen` taking into account the `mode` parameter. This parameter will be `O_CLOEXEC` when inheritance is not required for Linux. And it should be checked if the behavior is correct on Windows.
- `wm_exec` and `exec_op`: It will be necessary to check how new processes are managing the handles and how they are communicating with their parents.
- `socket`: Almost all the calls used in the `os_net.c` file. Will be needed check out the `SOCK_CLOEXEC` param and look for others calls in the code outside `os_net.c`.

____________________________________________________________________________________
### Subtask

It is necessary to set the WinApi32 Flag, `HANDLE_FLAG_INHERIT` to zero, using the pair of functions:
`GetHandleInformation`/`SetHandleInformation` 
that sets or provides information about the inheritance status of sockets:
- https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-gethandleinformation
- https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation

I have checked that sockets are being created with the HANDLE_FLAG_INHERIT flag set to one by default in Windows.

- [**See comment**](https://github.com/wazuh/wazuh/issues/15337#issuecomment-1806189953)

**Comment by lsayanes** [comment]
### About socket & os_net.c 
I have found that `SOCK_CLOEXEC` is useful to avoid a race condition between getting a new socket on accept and setting the `FD_CLOEXEC` flag later.

Normally the function `fcntl(fd, F_SETFD, FD_CLOEXEC)` is called after socket() But in a threaded program there is a possibility that a race condition exists between getting that file descriptor and setting the `FD_CLOEXEC` indicator.

This is only for Linux so it would have no effect on a **winagent**

Searching inside **WinApi** I found the pair:
`GetHandleInformation`/`SetHandleInformation` that sets or provides information about the inheritance state of sockets.

- https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-gethandleinformation
- https://learn.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-sethandleinformation 

I have written the function on `os_net.c`:

```
void checkOsSocket(int ossock, const char *ip, int port)
{

    DWORD dwFlags;
    FILE *pLog;

    char strResult[2048];

    SetLastError(0);

    HANDLE hObject = (HANDLE)(void*)ossock;
    if (GetHandleInformation(hObject, &dwFlags))
        sprintf(strResult, "ip:%s port:%d HANDLE_FLAG_INHERIT=%s", ip, port, (dwFlags&HANDLE_FLAG_INHERIT)?"1":"0");
    else
        sprintf(strResult, "GetHandleInformation FAILED LastError %lu", GetLastError());

    pLog = fopen("C:\\wazuh\\FLAG_INHERIT.txt", "a+");
    if(pLog)
    {
        time_t currt = time(NULL);
        fprintf(pLog, "%s - %s\n", ctime(&currt), strResult);
        fclose(pLog);
    }
}
```

and I have called it before each return after a socket has been created using the **socket**() function in this branch only for the compilation of a `Windows (11) agent`

**The result has been:**

<img width="651" alt="Captura de pantalla 2023-11-10 a la(s) 15 01 44" src="https://github.com/wazuh/wazuh/assets/68856625/51a37ec9-b715-466b-879c-229a1c3ea63a">

**Comment by lsayanes** [comment]
# wfopen error
- Searching for the error caused when running the integration test test_office365/test_configuration\test_invalid.py I discovered that the flags by CreateFile and _open_osfhandle in wfopen (only Windows) were wrong in "a" mode, which is why I had to change them
```
dwDesiredAccess = FILE_APPEND_DATA;
dwCreationDisposition = OPEN_ALWAYS;
flags = _O_CREAT | _O_APPEND;
```  
- Fixed error after rebase  : finalfp = fopen(finalpath, mode == OS_BINARY ? "rb" : "r");
_____________________________________
**Fixing wfopen wrapper error in UTs:**

1. 	 test_logcollector
2. 	 test_state
3. 	 test_fim_diff_changes
4. 	 test_audit_healthcheck
5. 	 test_syscheck_audit
6. 	 test_file_op
7. 	 test_version_op
8. 	 test_enrollment_op
9. 	 test_json_op

**Comment by lsayanes** [comment]
I have been changing the fopen for wfopen inside the `unit tests` but I have had several problems to solve some cross definitions, this is taking more time than planned and that is why I have changed the ETA. 

The tests where I have these problems are:
- 	 33 - test_file_op (Failed)
- 	 43 - test_enrollment_op (Failed)
- 	 51 - test_json_op (Failed)

**Comment by lsayanes** [comment]
Debugging I have found that in these _tests_ : 

- 33 - test_file_op (Failed)
- 43 - test_enrollment_op (Failed)
- 51 - test_json_op (Failed)

The `wopen` wrapper function (__wrap_wfopen) is not being called, instead the real wopen function is being called, I don't know why, I have been checking the `CMakeLists.txt` files, these look fine as the rest of the tests are working correctly

**Comment by lsayanes** [comment]
I have changed the ETA because I need more time to find out what is the problem in the Makefile, since the error in these tests is that the real wopen function is linked instead of the mock wfopen function.

The execution error in **33 - test_file_op (Failed)** is:
```
[  ERROR   ] --- No entries for symbol __wrap_fopen.
unit_tests/wrappers/libc/stdio_wrappers.c:78: error: Could not get value to check parameter __filename of function __wrap_fopen
```
and this is because it tries to execute the actual function code:
```
FILE * wfopen(const char * pathname, const char * modes) {
#ifdef WIN32
[...]
#else
    FILE *fp = fopen(pathname, modes);

    if(fp) {
    	w_file_cloexec(fp);
    }

    return fp;

#endif
}
```

**Comment by lsayanes** [comment]
I have been trying with different combinations within the `Makefile` file, only moving the function `wfopen` to another file has worked for me.

**Comment by lsayanes** [comment]
I had to create a new branch `15337-avoid-handles-inheritance-wfopen_op` from `15337-avoid-handles-inheritance` where I have moved the `wfopen` function to another file inside the **shared** folder, the same one that contains `file_op.c`, this new file, **wfopen_op.c**, only contains the wfopen function.

I have also created the same file_op.c rules for wfopen_op.c inside the `Makefile´:

```
shared/file_op_proc.o: shared/file_op.c
	${OSSEC_CC} ${OSSEC_CFLAGS} -fPIC -DCLIENT -DARGV0=\"wazuh-remoted\" -c $^ -o $@

shared/wfopen_op_proc.o: shared/wfopen_op.c
	${OSSEC_CC} ${OSSEC_CFLAGS} -fPIC -DCLIENT -DARGV0=\"wazuh-remoted\" -c $^ -o $@
```


With this the `test_file_op test` calls the mocked wfopen (__wrap_wfope) function and the test works correctly.

**Comment by lsayanes** [comment]
Some tests fail in server build mode:
```
	 59 - test_hmac_op (Failed)
	 60 - test_msgs (Failed)
	 61 - test_keys (Failed)
	 62 - test_sha1_op (Failed)
	 64 - test_md5_op (Failed)
	 67 - test_sha256_op (Failed)
	 73 - test_wm_database (Failed)
	 80 - test_wm_vuln_detector (Failed)
	 94 - test_wm_agent_upgrade_upgrades (Failed)
	114 - test_integrator (Failed)
	115 - test_manage_keys (Failed)
	147 - test_bzip2_op (Failed)
	158 - test_json-queue (Failed)
```
For this reason I have changed the ETA

**Comment by lsayanes** [comment]
I have been able to fix all the tests in server mode in the branch:
- https://github.com/wazuh/wazuh/tree/15337-avoid-handles-inheritance-wfopen_op

### Jenkins
- https://ci.wazuh.info/view/Tests/job/Test_unit/51007/

- [B51007_cmocka_server_unit_tests.txt](https://github.com/wazuh/wazuh/files/13734100/B51007_cmocka_server_unit_tests.txt)

**Comment by lsayanes** [comment]
in this development I have come across an arrester that I can't figure out.
The `test_win_whodata` test (in _Windows Agent_) returns this error at runtime:
```
[==========] wdata_directories_cleanup_tests: 6 test(s) run.
[  PASSED  ] 6 test(s).
[==========] tests: Running 130 test(s).
[  ERROR   ] --- No entries for symbol __wrap_wfopen.
unit_tests/wrappers/wazuh/shared/file_op_wrappers.c:101: error: Could not get value to check parameter filename of function __wrap_wfopen
/home/lsayanes/wazuh/src/unit_tests/syscheckd/whodata/test_win_whodata.c:214: note: Previously declared parameter value was declared here

[  FAILED  ] GROUP SETUP
[  ERROR   ] tests
[==========] tests: 0 test(s) run.
[  PASSED  ] 0 test(s).
```
If I don't get it fixed before the ETA date, set this issue to "on hold" and I will review it with members of the "watchdogs" team in hopes of finding the problem.

**Comment by havidarou** [comment]
After discussing with @davidjiglesias and @Dwordcito we have decided not to proceed with this.
