### ISSUE TITLE
Errors in ReadDecodeXML() function.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1537]
## Bug report

**Wazuh version**
_master_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------

See #1536 

The [code](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L155) for parsing decoder files such as [`/etc/decoder.xml`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/testrule.c#L215) and [`/etc/local_decoder.xml`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/testrule.c#L220) appears to have some errors:

* It requires that each [`decoder`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L239) tag have [`name`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L247) as its first attribute.  An optional second attribute of [`status`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L254) is allowed, but the code wrongly looks for it in the first attribute `node[i]->attributes[0]` rather than in the second `node[i]->attributes[1]`.
* On the other hand, the `status` attribute value is never assigned anywhere, nor does the [`OSDecoderInfo` struct](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decoder.h#L28) contain a status field.  Perhaps the corresponding parsing code should be removed?
* The [code](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L389) to "Get the FTS comment" should copy it to the [ftscomment field](https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decoder.h#L44).

**Comment by chemamartinez** [comment]
Hi @pillarsdotnet, 

Let me close the issue, its associated PR (#1536) is already merged.

Regards,
Chema.
