### ISSUE TITLE
Release 4.3.10 - Release Candidate 1 - E2E UX tests - SAML SSO

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15374]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | SAML SSO |
| **Category**            | Configuration |
| **Deployment option**   | [Quickstart](https://documentation.wazuh.com/current/quickstart.html) |
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/15372 |
| **Release candidate #** | 1 |

## Test description

Deploy Wazuh with the following design:

| Component | Guide | Cluster / Single | OS |
|-------------|------|-----------------|----| 
| indexer | [ quickstart ](https://documentation.wazuh.com/current/quickstart.html)| Single | Centos7 |
| server | [ quickstart ](https://documentation.wazuh.com/current/quickstart.html)| Single | Centos7 |
| dashboard | [ quickstart ](https://documentation.wazuh.com/current/quickstart.html)| Single | Centos7 |
| agent | [ Dashboard command ](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) | Single | Centos7 |

Then, following documentation from Single sign-on:
- [Single sign-on - Wazuh dashboard](https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/single-sign-on/index.html#single-sign-on)

Try the best effort to complete the steps and test the dashboard login using Okta and Azure AD

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here]().

|                |             |                     |                |
|----------------|-------------|---------------------|----------------|
| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|                |             |                     |                |

All tests have passed and the fails have been reported or justified. Therefore, I conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @gdiazlo 
- [ ] @davidjiglesias

**Comment by Selutario** [comment]
## :black_circle: Step 0. Test environment
### 1. Manager setup

I used this Vagrantfile to create a Centos7 machine:
```RUBY
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.59.103"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
  
     # Customize the amount of memory on the VM:
     vb.memory = "4096"
     vb.cpus = "2"
  end

end
```


Once running, I had to create this file to set the IP and restart the box:
```
$ sudo vi /etc/sysconfig/network-scripts/ifcfg-eth1
# The contents below are automatically generated by Vagrant. Do not modify.
NM_CONTROLLED=no
BOOTPROTO=none
ONBOOT=yes
IPADDR=192.168.59.103
NETMASK=255.255.255.0
DEVICE=eth1
PEERDNS=no
```

Then I downloaded the `wazuh-install.sh` script:
```
curl -sO https://packages.wazuh.com/4.3/wazuh-install.sh
```

And replaced this:
```
readonly repogpg="https://packages.wazuh.com/key/GPG-KEY-WAZUH"
readonly repobaseurl="https://packages.wazuh.com/4.x"
readonly reporelease="stable"
readonly filebeat_wazuh_module="${repobaseurl}/filebeat/wazuh-filebeat-0.2.tar.gz"
readonly bucket="packages.wazuh.com"
readonly repository="4.x"

readonly wazuh_major="4.3"
readonly wazuh_version="4.3.9"
```

by this, so it installs the new Wazuh version (v4.3.10) instead of the current one (v4.3.9):
```
readonly development=1
readonly repogpg="https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH"
readonly repobaseurl="https://packages-dev.wazuh.com/pre-release"
readonly reporelease="unstable"
readonly filebeat_wazuh_module="${repobaseurl}/filebeat/wazuh-filebeat-0.2.tar.gz"
readonly bucket="packages-dev.wazuh.com"
readonly repository="pre-release"

readonly wazuh_major="4.3"
readonly wazuh_version="4.3.10"
```

Finally I run the script and the installation was successful:
```
$ sudo bash ./wazuh-install.sh -a
14/11/2022 12:04:46 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.10
14/11/2022 12:04:46 INFO: Verbose logging redirected to /var/log/wazuh-install.log
14/11/2022 12:04:50 INFO: Wazuh development repository added.
14/11/2022 12:04:50 INFO: --- Configuration files ---
14/11/2022 12:04:50 INFO: Generating configuration files.
14/11/2022 12:04:51 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
14/11/2022 12:04:51 INFO: --- Wazuh indexer ---
14/11/2022 12:04:51 INFO: Starting Wazuh indexer installation.
14/11/2022 12:05:58 INFO: Wazuh indexer installation finished.
14/11/2022 12:05:58 INFO: Wazuh indexer post-install configuration finished.
14/11/2022 12:05:58 INFO: Starting service wazuh-indexer.
14/11/2022 12:06:08 INFO: wazuh-indexer service started.
14/11/2022 12:06:08 INFO: Initializing Wazuh indexer cluster security settings.
14/11/2022 12:06:14 INFO: Wazuh indexer cluster initialized.
14/11/2022 12:06:14 INFO: --- Wazuh server ---
14/11/2022 12:06:14 INFO: Starting the Wazuh manager installation.
14/11/2022 12:06:55 INFO: Wazuh manager installation finished.
14/11/2022 12:06:55 INFO: Starting service wazuh-manager.
14/11/2022 12:07:09 INFO: wazuh-manager service started.
14/11/2022 12:07:09 INFO: Starting Filebeat installation.
14/11/2022 12:07:16 INFO: Filebeat installation finished.
14/11/2022 12:07:18 INFO: Filebeat post-install configuration finished.
14/11/2022 12:07:18 INFO: Starting service filebeat.
14/11/2022 12:07:18 INFO: filebeat service started.
14/11/2022 12:07:18 INFO: --- Wazuh dashboard ---
14/11/2022 12:07:18 INFO: Starting Wazuh dashboard installation.
14/11/2022 12:08:18 INFO: Wazuh dashboard installation finished.
14/11/2022 12:08:18 INFO: Wazuh dashboard post-install configuration finished.
14/11/2022 12:08:18 INFO: Starting service wazuh-dashboard.
14/11/2022 12:08:18 INFO: wazuh-dashboard service started.
14/11/2022 12:08:46 INFO: Initializing Wazuh dashboard web application.
14/11/2022 12:08:46 INFO: Wazuh dashboard web application initialized.
14/11/2022 12:08:46 INFO: --- Summary ---
14/11/2022 12:08:46 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: g8GeELoVqLU7I7jCy.sDm1a9v7T8tPbU
14/11/2022 12:08:46 INFO: Installation finished.
```

**Comment by Selutario** [comment]
## :yellow_circle: Check 1. Okta
### Step 1: Create an account on Okta. Request a free trial if you don't have a paid license.
Maybe this doesn't belong to our documentation, but in my case, I wasn't sure which of these two services ([Workforce Identity Cloud](https://www.okta.com/free-trial/) or [Customer Identity Cloud](https://www.okta.com/free-trial/customer-identity/)) I should sign up for, so I think it might be helpful to specify it.

![image](https://user-images.githubusercontent.com/23361101/201674199-de3b2579-00ed-47e6-96a4-f4a03f82b795.png)

### Step 2: Create a new user
Ok.

### Step 3: Create a new group. Navigate to Directory > Groups and add a group.
Ok.

### Step 4: Add the new user to the new group. Navigate to Directory > Groups and select your group. Click on Assign People and add the user to the group created.
Ok.

### Step 5. Create a new app. Configure the SAML settings while you create the app.
This step requires specifying a public hostname to access the dashboard. Since I did the setup on my local machine, I had to open ports and enable port forwarding in the vagrant configuration.

In progress

**Comment by Selutario** [comment]
# Azure
## 1. Azure Active Directory Configuration
### :green_circle: Step 1: Create a Microsoft account or use your own if you already have one.
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1: 
### :green_circle: Step 1:

**Comment by alberpilot** [comment]
Problems reported by @Selutario are already on @wazuh/content hands, they are working on it. 
I proceed to close this issue, as this change is not considered a stopper.
