### ISSUE TITLE
Error in wm_osquery_monitor_read() function. #1499

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1538]
## Bug report

**Wazuh version**
_master_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------

See #1499 

The [error message](https://github.com/wazuh/wazuh/blob/master/src/config/wmodules-osquery-monitor.c#L81) for an invalid attribute of the [`pack`](https://github.com/wazuh/wazuh/blob/master/src/config/wmodules-osquery-monitor.c#L77) tag should mention the invalid attribute, instead of quoting the only **valid** attribute.

**Comment by chemamartinez** [comment]
Hi @pillarsdotnet ,

PR #1499 was already merged.

Regards,
Chema.
