### ISSUE TITLE
`remoted` daemon not running in `info` environment

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15386]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-1 | remoted | Manager | Packages | OS version |

## Problem found
After reviewing the automated Demo monitoring pipeline, we noticed that we have a daemon not running: `wazuh-remoted`. 

This `info` demo environment was started on 07/11/2022. On 2022/11/13 12:25:56 UTC, the agents started to have reporting problems. The `wazuh-remoted` stopped working in all managers (env1 cluster managers and env2 single manager). 

### Evidence

- `ps -xa | grep ossec` doesn't show the `wazuh-remoted` daemon running. 
- All agents started reporting ERROR messages connecting to the manager on 2022/11/13 at 12:25:56 UTC approx. 
- No segfaults were found in `/var/log/messages`. 

Env data (connections, etc) can be found: https://github.com/wazuh/wazuh-automation/issues/965
Still investigating and adding information to this issue.

**Comment by rauldpm** [comment]
## Update report

- Analyzing the 2-day stress test Wazuh server instance in situ, the following amount of descriptors for `wazuh-db`, `wazuh-analysisd`, and `wazuh-remoted` have been observed:

```
[root@ip-172-31-2-32 centos]# ps aux | grep -E "wazuh-db|wazuh-remoted|wazuh-analysisd"
wazuh      12306  2.3  0.5 864640 19412 ?        Sl   Nov16  55:15 /var/ossec/bin/wazuh-db
wazuh      12353 13.6  5.0 1310688 188876 ?      Sl   Nov16 317:42 /var/ossec/bin/wazuh-analysisd
wazuh      12382  4.7  0.1 1200628 7060 ?        Rl   Nov16 111:42 /var/ossec/bin/wazuh-remoted
root     2547087  0.0  0.0 221928  1048 pts/0    R+   13:21   0:00 grep --color=auto -E wazuh-db|wazuh-remoted|wazuh-analysisd
[root@ip-172-31-2-32 centos]# cd /proc/12306/fd
[root@ip-172-31-2-32 fd]# ls -l | wc -l
48758
[root@ip-172-31-2-32 fd]# cd /proc/12353/fd
[root@ip-172-31-2-32 fd]# ls -l | wc -l
24395
[root@ip-172-31-2-32 fd]# cd /proc/12382/fd
[root@ip-172-31-2-32 fd]# ls -l | wc -l
24390
```

After one hour, it has been observed that `wazuh-remoted` was no longer present in the system, since `wazuh-analysisd` has shown in the rest of the tests to have a similar value of descriptors, it can be said that the `wazuh-remoted` descriptors in the time of the stop were around the amount of `24500`

![image](https://user-images.githubusercontent.com/14913942/202727185-084792db-9f98-4650-89f0-a284dbe1aab5.png)

```
[root@ip-172-31-2-32 12353]# ps aux | grep -E "wazuh-db|wazuh-remoted|wazuh-analysisd"
wazuh      12306  2.5  0.5 864640 19212 ?        Sl   Nov16  61:12 /var/ossec/bin/wazuh-db
wazuh      12353 13.3  4.9 1310688 188796 ?      Sl   Nov16 319:04 /var/ossec/bin/wazuh-analysisd
root     2573614  0.0  0.0 221928   992 pts/0    R+   14:13   0:00 grep --color=auto -E wazuh-db|wazuh-remoted|wazuh-analysisd
[root@ip-172-31-2-32 12353]# cd /proc/12353/fd
[root@ip-172-31-2-32 fd]# ls -l | wc -l
24495
```

Looking at the `wazuh-db` descriptors, we can see that at that very moment, they have been halved (`48758` -> `24533`)

```
[root@ip-172-31-2-32 fd]# ps aux | grep -E "wazuh-db|wazuh-remoted|wazuh-analysisd"
wazuh      12306  2.5  0.5 864640 19212 ?        Sl   Nov16  61:12 /var/ossec/bin/wazuh-db
wazuh      12353 13.3  4.9 1310688 188796 ?      Sl   Nov16 319:04 /var/ossec/bin/wazuh-analysisd
root     2576496  0.0  0.0 221928  1096 pts/0    R+   14:17   0:00 grep --color=auto -E wazuh-db|wazuh-remoted|wazuh-analysisd
[root@ip-172-31-2-32 fd]# cd /proc/12306/fd
[root@ip-172-31-2-32 fd]# ls -l | wc -l
24533
```

<details><summary>2-day stress test ossec.log messages</summary>

```
2022/11/18 13:30:38 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 13:33:43 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 13:33:43 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 13:33:43 wazuh-analysisd: ERROR: Bad load query: 'agent 003 rootcheck save 1668778417 Starting rootcheck scan.'.
2022/11/18 13:33:43 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
2022/11/18 13:33:47 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 13:33:47 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 13:33:52 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 13:33:52 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 13:52:22 wazuh-db: ERROR: at run_dealer(): accept(): Too many open files in system
2022/11/18 14:09:03 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 14:09:03 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 14:09:03 wazuh-analysisd: ERROR: Bad load query: 'agent 003 rootcheck save 1668780537 Ending rootcheck scan.'.
2022/11/18 14:09:03 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
2022/11/18 14:09:04 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 14:09:04 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 14:09:04 wazuh-analysisd: ERROR: Bad load query: 'agent 000 rootcheck save 1668780538 Ending Azure-logs scan.'.
2022/11/18 14:09:04 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
2022/11/18 14:09:05 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 14:09:05 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
```

```
2022/11/18 00:36:04 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/11/18 00:36:14 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
2022/11/18 09:46:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:46:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:46:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:46:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:51:13 wazuh-remoted: ERROR: Unable to open file 'etc/shared/default/cis_win2012r2_memberL2_rcl.txt' due to [(23)-(Too many open files in system)].
2022/11/18 09:51:13 wazuh-remoted: ERROR: Invalid shared file 'etc/shared/default/cis_win2012r2_memberL2_rcl.txt' in group 'default'. Ignoring it.
2022/11/18 09:54:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:54:19 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:57:29 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:57:29 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
2022/11/18 09:57:30 wazuh-remoted: ERROR: Unable to connect to socket 'queue/db/wdb'.
```

</details>

Likewise, in the 3-day test Wazuh server instance, it has not been possible to carry out any command, always obtaining this message:

```
[centos@ip-172-31-1-9 ~]$ sudo su
-bash: start_pipeline: pgrp pipe: Too many open files in system
-bash: /usr/bin/sudo: Too many open files in system
```

**Comment by chemamartinez** [comment]
Removing this issue from project Release 4.4.0 since it is duplicated from https://github.com/wazuh/wazuh/issues/15426

**Comment by rauldpm** [comment]
## Update report

The behaviors reported in the previous comment can be reflected in the graphs of the issue comment: https://github.com/wazuh/wazuh-jenkins/issues/4423#issuecomment-1320984282

It is possible to see the exact moment when `wazuh-remoted` stops working (2022-11-18 09:23:52) in the Wazuh server, where `wazuh-db`, `wazuh-remoted` and `wazuh-analysisd` (hidden by `wazuh-remoted`) stop showing growing behavior.

After 12 hours of operation, it can be seen how `wazuh-db` shows a usage drop until it coincides with the amount reported by `wazuh-remoted` and `wazuh-analysisd`.

![image](https://user-images.githubusercontent.com/14913942/203137072-c7e4bf43-ca84-4741-ad65-4e9bb6cc3a51.png)

---

Simultaneously, it is possible to observe low resources usage in the agents in the same period of time, for example, for the CentOS agent, there would be graphs like:

![image](https://user-images.githubusercontent.com/14913942/203137735-2f33b268-d995-4afe-9f89-f57757a66905.png)
![image](https://user-images.githubusercontent.com/14913942/203137757-65f4c82e-3cd0-43ab-a927-b5f468343717.png)
![image](https://user-images.githubusercontent.com/14913942/203137769-6c77bfe0-a8f4-4e60-9bbb-36a67b6636b2.png)
![image](https://user-images.githubusercontent.com/14913942/203137836-a036fcff-8afd-44f7-ba40-8861386a8bae.png)
![image](https://user-images.githubusercontent.com/14913942/203137855-79a71712-fa1b-4a74-ab40-22a9907b2d7b.png)
![image](https://user-images.githubusercontent.com/14913942/203137873-bddd0664-7a40-463f-b1ea-56553fb675bf.png)

**Comment by alberpilot** [comment]
CICD actions completed. Core will continue here: https://github.com/wazuh/wazuh/issues/15426
