### ISSUE TITLE
Remove unreachable code from Read_Global() function.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1539]
## Bug report

**Wazuh version**
_master_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------

See #1498 

The [`Read_Global`](https://github.com/wazuh/wazuh/blob/master/src/config/global-config.c#L121) function has [some code](https://github.com/wazuh/wazuh/blob/master/src/config/global-config.c#L121) that is unreachable and should therefore be removed.

**Comment by chemamartinez** [comment]
Hi @pillarsdotnet,

It has been merged at #1498 and will be released ASAP.

Regards,
Chema.
