### ISSUE TITLE
RSync unit test failure.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#15417]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-rev | RSync | Agent | Packages/Sources | Windows |

This issue aims to identify why this test is not passing in 4.4 when it is compiled in windows, after that identification/analysis, it is necessary to estimate and prioritize based on its severity.

![image](https://user-images.githubusercontent.com/14300208/202365783-6b7fbdd3-5a86-4a21-b10e-34dbc9e8a8ae.png)

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/15417?planning-poker) with Zenhub @Damian-Mangold @MiguelazoDS @pereyra-m @tdrauncieal

**Comment by MiguelazoDS** [comment]
# Finding 

The root cause of this issue seems to be the way std::remove() function behaves on Linux and Windows. 

https://en.cppreference.com/w/cpp/io/c/remove

> Deletes the file identified by character string pointed to by fname.
> 
> If the file is currently open by the current or another process, the behavior of this function is implementation-defined (in particular, POSIX systems unlink the file name, although the file system space is not reclaimed even if this was the last hardlink to the file until the last running process closes the file, Windows does not allow the file to be deleted)
