### ISSUE TITLE
Windows agent does not stop correctly after applying invalid configuration in Syscollector

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#15412]
| Wazuh version | Component | Install type | Install method | Platform
| -- | -- | -- | -- | --
| 4.4.0-40400 | Syscollector | Agent | Packages | Windows

## Description

The Wazuh agent does not stop correctly after applying an invalid configuration and multiple logs are displayed on repeat in the `ossec.log` file.

ℹ️ This behavior could be reproduced only with `syscollector`. I tested with `rootcheck`, `FIM`, and the global configuration, but none of these produce the error.

🗒️ I tested it with different configuration options of Syscollector and the behavior is exactly the same. And I also tested stopping the agent through Powershell and through the UI but the result is the same.

⚠️ **_I also reproduced this bug in production and in a previous version (4.3.4)_**

### Evidence

<details><summary>Invalid configuration applied</summary>

<br>

![image](https://user-images.githubusercontent.com/39094716/202173823-51f89bff-6431-4a24-85d1-e903a106f810.png)

</details>

<details><summary>Configuration error appears in the <code>ossec.log</code> file</summary>

<br>

![image](https://user-images.githubusercontent.com/39094716/202174837-67647a10-26a4-4b65-942d-f5f6a8111fa8.png)

</details>

<details><summary>Error when stopping via Powershell</summary>

<br>

```
PS C:\Windows\system32> net stop WazuhSvc
System error 109 has occurred.

The pipe has been ended.
```

</details>

<details><summary>Errors in EventViewer</summary><blockquote>

<br>

<details><summary>Application Error</summary>

<br>

```
Faulting application name: wazuh-agent.exe, version: 0.0.0.0, time stamp: 0x6373ef09
Faulting module name: msvcrt.dll, version: 7.0.17763.475, time stamp: 0xba51b082
Exception code: 0xc00000fd
Fault offset: 0x0004c121
Faulting process id: 0x1268
Faulting application start time: 0x01d8f9b1cf6a9b5d
Faulting application path: C:\Program Files (x86)\ossec-agent\wazuh-agent.exe
Faulting module path: C:\Windows\System32\msvcrt.dll
Report Id: f4ed05cb-35af-45c0-aea5-d93f983df965
Faulting package full name: 
Faulting package-relative application ID: 
```

</details>

<details><summary>Windows Error Reporting</summary>

<br>

```
Fault bucket 1597215117721465243, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: wazuh-agent.exe
P2: 0.0.0.0
P3: 6373ef09
P4: msvcrt.dll
P5: 7.0.17763.475
P6: ba51b082
P7: c00000fd
P8: 0004c121
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERFFB4.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER63D.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AC.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6AA.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6CA.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_wazuh-agent.exe_c94bf878c5298226f726c7f1383ed758a535845a_af235c07_142c0cf3

Analysis symbol: 
Rechecking for solution: 0
Report Id: f4ed05cb-35af-45c0-aea5-d93f983df965
Report Status: 268435456
Hashed bucket: f2d032f193ba6a28e62a72afe9abf19b
Cab Guid: 0
```

</details>

</details>

<details><summary>Repeated errors in the <code>ossec.log</code> file</summary>

<br>

```
2022/11/16 03:58:44 wazuh-agent: INFO: Received exit signal. Starting exit process.
2022/11/16 03:58:44 wazuh-agent: INFO: Set pending exit signal.
2022/11/16 03:58:44 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2022/11/16 03:58:44 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2022/11/16 03:58:44 wazuh-agent: INFO: Received exit signal. Starting exit process.
2022/11/16 03:58:44 wazuh-agent: INFO: Set pending exit signal.
2022/11/16 03:58:44 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2022/11/16 03:58:44 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2022/11/16 03:58:44 wazuh-agent: INFO: Received exit signal. Starting exit process.
2022/11/16 03:58:44 wazuh-agent: INFO: Set pending exit signal.
2022/11/16 03:58:44 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2022/11/16 03:58:44 wazuh-agent: CRITICAL: At pthread_cond_destroy(): Invalid argument
2022/11/16 03:58:44 wazuh-agent: INFO: Received exit signal. Starting exit process.
2022/11/16 03:58:44 wazuh-agent: INFO: Set pending exit signal.
```

</details>

## Steps

1. With the agent stopped or running, apply an invalid configuration in Syscollector and start/restart
2. Stop the agent (through PS or UI)

## Current result

1. An error appears in the EventViewer
2. `CRITICAL` logs are displayed on repeat in the `ossec.log` for at least 8 seconds until the agent stops

## Expected result

1. No errors must appear in the EventViewer
2. The agent must be stopped correctly

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/15412?planning-poker) with Zenhub @Damian-Mangold @MiguelazoDS @pereyra-m @tdrauncieal

**Comment by MiguelazoDS** [comment]
# Findings

On Linux, the module stops as expected. On Windows systems, the issue occurs after configuring an invalid option in Syscollector, as well as configuring an invalid option in Osquery, etc (both components of Wazuh Modules). 

The point of failure was found on the `wm_sys_stop()` function, which is called after trying to stop the service using the UI, or the CLI through PS as mentioned in the issue. 

It starts in `src/win32/win_service.c#OssecServiceCtrlHandler()` that calls `stop_wmodules()`. Only Syscollector has a handler for that, which is `wm_sys_stop()`.  Then, the error pthread_cond_destroy() occurs during the call of the macro w_cond_destroy()

That implementation is part of the issue: https://github.com/wazuh/wazuh/issues/8739

**Comment by mauromalara** [comment]
### Note

This test should be modified after this issue is fixed.
