### ISSUE TITLE
The default value of the interval field is not set when applying an empty configuration

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#15413]
|Wazuh version |Component |Install type |Install method |Platform
|---|---|--|--|--
| 4.4.0-40400 | Syscollector | Manager/Agent | Packages | Linux, Windows |

## Description

When configuring Sycollector with an empty configuration block, the default values ([the ones specified in the documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html)) are expected to apply, but when doing so, the `interval` field gets the value of **0** instead of **3600**.

⚠️ This behavior occurs in both Manager and Agent, and I tested it on Linux and Windows.

### Evidence

<details><summary>Multiple scans are executed</summary>

<br>

```
2022/11/16 06:26:10 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/11/16 06:26:13 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/11/16 06:26:15 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/11/16 06:26:17 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2022/11/16 06:26:19 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2022/11/16 06:26:20 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

</details>

## Steps
1. Apply the following configuration in Syscollector
```
  <!-- System inventory -->
  <wodle name="syscollector">
  </wodle>
```
2. Configure the following internal options:
```
windows.debug=2
wazuh_modules.debug=2
```
3. Restart the manager/agent

## Current result

1. The interval is set to `0`

```
2022/11/11 08:37:58 wazuh-modulesd:syscollector[26066] wm_syscollector.c:116 at wm_sys_log_config(): DEBUG: {"syscollector":{"disabled":"no","scan-on-start":"yes","interval":0,"network":"yes","os":"yes","hardware":"yes","packages":"yes","ports":"yes","ports_all":"no","processes":"yes","sync_max_eps":10}}
```

## Expected result

1. The expected value for the `interval` field is `3600`

**Comment by Dwordcito** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Core---Data-Pirates-603911cf3cadd10015e69707/issues/wazuh/wazuh/15413?planning-poker) with Zenhub @Damian-Mangold @MiguelazoDS @pereyra-m

**Comment by mauromalara** [comment]
### ⚠️ Note

The test function called `test_syscollector_default_values()`, which was developed in wazuh/wazuh-qa#3584, was marked as **_XFAIL_** because of this issue. So, that test function must be unmarked after this issue is fixed.
