### ISSUE TITLE
Help mattermost integration

### ISSUE THREAD

**Issue by FallenStark** [wazuh/wazuh#15415]
Hello everyone, does anyone have an integration for Mattermost, if not, please help me write an integration for Mattermost to send incidents (for example, like in slack)

Thanks for the answers!

**Comment by jnasselle** [comment]
Hi @FallenStark ,

I'm working on this by following the next documentation/blogs

- https://mattermost.com/blog/mattermost-integrations-incoming-webhooks/
- https://mattermost.com/blog/laymans-guide-to-markdown-on-mattermost/
- https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#custom-integration

I'll keep you posted on the progress!

**Comment by jnasselle** [comment]
Hi @FallenStark ,

Sorry about the delayed response. After checking out Mattermost documentation and current Wazuh Slack Integration, i figure out that they are compatible! The only thing to do is to create de proper [Mattermost incoming webhook](https://mattermost.com/blog/mattermost-integrations-incoming-webhooks/) and set the webhook in manager's `ossec.conf` like if we were using slack

```xml
  <integration>
    <name>slack</name>
    <hook_url>https://xxxxxxxxx.cloud.mattermost.com/hooks/xxxxxxxxxxxxxxxxxxxxxxxxxxx</hook_url>
    <level>3</level>
    <alert_format>json</alert_format>
  </integration>
```

After restarting the manager and forcing a simple alert, those appears in Mattermost channel

![image](https://user-images.githubusercontent.com/1791430/204040340-a6e4d175-43db-4015-8429-71985e79f402.png)

Hope this helps!

**Comment by FallenStark** [comment]
@jnasselle Thank you very much for your answer! You helped me a lot
