### ISSUE TITLE
Improve get_info_attributes() function.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh#1542]
## Bug report

**Wazuh version**
_master_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------

See #1541

The rules parser wrongly allows an [`info`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/rules.c#L401) element with attributes other than [`type`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/rules.c#L1623), and also allows invalid values.

This PR modifies the [`get_info_attributes`](https://github.com/wazuh/wazuh/blob/master/src/analysisd/rules.c#L1609) function to throw an error if an `info` element has an invalid attribute or value.

**Comment by chemamartinez** [comment]
Let me close this issue since PR #1541 was already merged.

Regards,
Chema.
