### ISSUE TITLE
Vulnerabilities not detecting in fedora || Wazuh server

### ISSUE THREAD

**Issue by Shamri04** [wazuh/wazuh#15446]
Vulnerabilities not getting detected in fedora OS agents.
![image](https://user-images.githubusercontent.com/110982013/202976070-fa9f1db6-dd45-4431-8472-31aea6044d8e.png)

**Comment by davidjiglesias** [comment]
Hello @Shamri04,

I would love to help here and the first step would be to reproduce your exact problem. What is the exact OS version you are using?

**Comment by Shamri04** [comment]
The server OS is Ubuntu 20.04.4 LTS and the agents I need to monitor is fedora 33 to 35.

**Comment by Shamri04** [comment]
Hi @davidjiglesias 

I have resolved the issue by custom OS configuration. Now Vulnerabilities detecting for fedora.
Thanks a lot for the quick response and support.

**Comment by aakilo** [comment]
> Hi @davidjiglesias
> 
> I have resolved the issue by custom OS configuration. Now Vulnerabilities detecting for fedora. Thanks a lot for the quick response and support.
Please, tell me the solution to fix this issue .
Thanks;

**Comment by aakilo** [comment]
Hi , I'm facing the same issue with fedora vulnerabilities please tell me how to fix it.
