### ISSUE TITLE
Wazuh is not generating alert for custom rule and decoder

### ISSUE THREAD

**Issue by fiyadeleon** [wazuh/wazuh#15458]
Hi, I'm trying to generate alerts to alert.log if there are logs that satisfies our custom decoder and rule. I have tested our code using wazuh-logtest and seems to be working as expected.

![image](https://user-images.githubusercontent.com/42709435/203198837-45c08623-3b81-44f9-ad05-900647007c3d.png)

Then, to test and ingest a log into the server, I have tried to create a dummy file and include the dummy file's location in the ossec.conf.

But it doesn't generate any alerts in alerts.json or alerts.log.

local_decoder.xml
```
<decoder name="trend_micro_wb">
    <prematch type="pcre2">CEF:0\|Trend Micro\|.*?WB:</prematch>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?dpt=(\S+)</regex>
    <order>server_port</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?act=(\S+)</regex>
    <order>action_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?src=(\d+.\d+.\d+.\d+)</regex>
    <order>source_ip_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cs1=([^\|]+) cs4Label=</regex>
    <order>policy_name</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cs4=(\S+)</regex>
    <order>reason_code</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cs5=(\S+)</regex>
    <order>reason_code_source</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?deviceDirection=(\S+)</regex>
    <order>traffic</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cat=(\S+)</regex>
    <order>blocking_type</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?dvchost=(\S+)</regex>
    <order>dvchost_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?request=(\S+)</regex>
    <order>url_request</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?fname=([^\|]+) request=</regex>
    <order>file_name_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?duser=(\S+)</regex>
    <order>duser_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?shost=(\S+)</regex>
    <order>shost_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cs2=([^\|]+) deviceProcessName=</regex>
    <order>blocking_rule</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?deviceProcessName=([^\|]+) cn3Label=</regex>
    <order>process_name_wb</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?cn3=(\S+)</regex>
    <order>reputation_score</order>
</decoder>
<decoder name="trend_micro_wb_complete">
    <parent>trend_micro_wb</parent>
    <regex type="pcre2">CEF:0\|Trend Micro\|.*?dst=(\d+.\d+.\d+.\d+)</regex>
    <order>dst_wb</order>
</decoder>
```
local_rules.xml
```
<group></group><rule id="100050" level="3">     
    <decoded_as>trend_micro_wb</decoded_as>     
    <field name="action_wb">1</field>     
    <description>Testing rule when action.wb is 1</description> 
</rule></group>
```

**Comment by jftuduri** [comment]
Hello @fiyadeleon!

Could you please attach or paste the contents of the dummy file that you are using to test this?
Also, what version of Wazuh are you using?

**Comment by jftuduri** [comment]
Hi @fiyadeleon,
To be able to test this I am missing the decoder `trend_micro_wb` that you are using as the parent decoder. Wazuh-logtest is showing: `wazuh-analysisd: ERROR: (2101): Parent decoder name invalid: 'trend_micro_wb'.`

Could you please share that decoder?
Sorry for the inconvenience.

**Comment by fiyadeleon** [comment]
Hi @jftuduri my bad I forgot to include the parent decoder. Please see updated xml above.

**Comment by jftuduri** [comment]
Hi @fiyadeleon!

I have tested you decoder and rule with a localfile and the alert is generated correctly.
These are the steps I am using:
 - Just to be sure we are on the same page I attached the local decoder and rules files, but they are the same that you are using:
    - [/var/ossec/etc/rules/local_rules.xml 
](https://github.com/wazuh/wazuh/files/10078798/local_rules.zip)
    - [/var/ossec/etc/decoders/local_decoder.xml](https://github.com/wazuh/wazuh/files/10078800/local_decoder.zip)
 - `wazuh-logtest v4.3.9 `shows decoder and rule are working correctly:
![image](https://user-images.githubusercontent.com/7939712/203636012-f289a8e1-21dd-4bd9-9e24-18f147856f3e.png)
- Add the following block to `/var/ossec/etc/ossec.conf`:
```
 <localfile>
    <location>/home/test.log</location>
    <log_format>syslog</log_format>
 </localfile>
```
 - Restart the manager: `systemctl restart wazuh-manager`
 - Create the test.log file: `touch /home/test.log`
 - Add the test log entry to that file with an `echo` command: 
`echo "Apr 20 2022 15:56:05 [hakusi.manage.trendmicro.com](http://hakusi.manage.trendmicro.com/) CEF:0|Trend Micro|Apex Central|2019|WB:7|7|3|deviceExternalId=38 rt=Nov 15 2017 08:43:57 GMT+00:00 app=17 cntLabel=AggregatedCount cnt=1 dpt=80 act=1 src=10.1.128.46 cs1Label=SLF_PolicyName cs1=External User Policy deviceDirection=2 cat=7 dvchost=ApexOneClient08 fname=test.txt request=[http://www.violetsoft.net/counter/insert.php?dbserver\=db1&c_pcode\=25&c_pid\=funpop1&c_kind\=4&c_mac\=FE-ED-BE-EF-0C-E1](http://www.violetsoft.net/counter/insert.php?dbserver%5C=db1&c_pcode%5C=25&c_pid%5C=funpop1&c_kind%5C=4&c_mac%5C=FE-ED-BE-EF-0C-E1) deviceFacility=Apex One shost=ABC-HOST-WKS12" >> /home/test.log`
 - Check the alerts.log: cat /var/ossec/logs/alerts/alerts.log 
![image](https://user-images.githubusercontent.com/7939712/203637287-6cbbd9fe-a2b8-4615-809c-1b67498d75ab.png)
 - Alert for rule 100050 was generated.

One thing to keep in mind is that wazuh-logcollector, by default, reads the logs that are generated only while it is running. So if you happen to add entries to the test.log file when the logcollector service is stopped, those entries will not be processed when the service is started.

Please tell me if following the same steps I took solves your issue or, if it doesn't, tell me what problems did you encounter.
Regards!

**Comment by jftuduri** [comment]
Check its status with `systemctl status wazuh-manager`:
![image](https://user-images.githubusercontent.com/7939712/203642381-5537928f-9f9a-47d8-b390-ad946210e13c.png)

**Comment by jftuduri** [comment]
Hey @fiyadeleon! good to hear that you found the problem!

I'll close this issue now, if you find any other problem or have any doubts feel free to open a new one. You can also reach on any of the communities channels: https://wazuh.com/community/
