### ISSUE TITLE
Wazuh xml parser fix

### ISSUE THREAD

**Issue by irfaanaikagjee** [wazuh/wazuh#15464]
Hello Wazuh team,

On older wazuh version, whenever we uses duplicate rule in the file local_rules.xml, we get an error while trying to save the file. After upgrading, there are no errors and the file is saved but the duplicated rules does not work and it cost us time to debug.

Could you fix the issue or re-enable the feature if it were removed intentionally?

Thank you in advance

Kind regards,

**Comment by MiguelazoDS** [comment]
Hi @irfaanaikagjee, 

I will take a deeper look at the implementation of this change, but I would like to mention that you still can see a warning log that tells you when a duplicate rule is found. What is the hard part of the debugging you are experiencing? 

You can use grep to find something like this and check for duplicate rules. 

![image](https://user-images.githubusercontent.com/13010397/203322531-1affad55-a6c1-40e9-91ae-31862f330a5c.png)

**Comment by irfaanaikagjee** [comment]
Hello @MiguelazoDS ,

We use the GUI to create the rules using 'management -->rules'. We does not get any warning or error when we click on save while the file has duplicate rule id.

Please check it.

**Comment by MiguelazoDS** [comment]
Hi @irfaanaikagjee, 

The ruleset test feature was added which provides more information than the warning on save you mentioned. Before adding a new rule you can use it to verify everything will work as expected. I did the same as before using the UI. 

![image](https://user-images.githubusercontent.com/13010397/203792311-2f766e4c-a6c5-4337-9078-486994030e4e.png)

The feature was added as part of this release https://documentation.wazuh.com/current/release-notes/release-4-1-0.html

**Comment by irfaanaikagjee** [comment]
Hello @MiguelazoDS ,

We does not use the ruleset test everytime as we does not have the full log on some cases. We just save them. 

Would it be possible to re-enable the warning or error feature in a future release if there is a duplicate rule ID when we click on save?

Thanks in advance

Kind regards,
Irfaan A.

**Comment by MiguelazoDS** [comment]
I'm afraid we are not going back to the previous behavior, that change is part of this implementation https://github.com/wazuh/wazuh/issues/12641. 
Using the ruleset test it is not needed to have any log to decode. The warning message of duplicate ID will appear if that is the case.

**Comment by irfaanaikagjee** [comment]
Ok I tested using random strings and I indeed get the warnings of duplicate rule in the ruleset test. Thank you.

I close the issue.
