### ISSUE TITLE
Remove Syscheck syncronization from DB wodle

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1546]
The DB synchronization module has an option to synchronize the legacy Syscheck databases (_queue/syscheck/*_) towards the SQLite cache databases for the Framework (_var/db/agents/*_).

Since FIM data is natively stored into SQLite databases by Wazuh DB, that synchronization option becomes deprecated.

**Comment by bah07** [comment]
The option to synchronize FIM records with the DDBB of wazuh_db has been disabled.

Done in [8c2a088](https://github.com/wazuh/wazuh/pull/1592/commits/8c2a0883c5af52cf431a8da971dc063a7d44c0a7)
