### ISSUE TITLE
Workers cannot connect to master after starting `clusterd` process if it was already running

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15473]
|Wazuh version|Component|
|---|---|
| 4.4+ | Wazuh cluster |

## Description

In the issue below, the behavior of the wazuh-clusterd binary was changed so that if it is executed while one was already running, it will stop the old process and start a new one.
- #14475

This seems to work fine on the master. Also in the worker if the process had not yet started any tasks before running it again. That is, if the worker had connected to the master less than 9 seconds ago and the `wazuh-clusterd` process was run again, it kills the previous process correctly and reconnects:
- `cluster.log` (worker)
  ```
  2022/11/23 15:22:59 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
  2022/11/23 15:22:59 INFO: [Worker worker1] [Main] Successfully connected to master.
  # /var/ossec/bin/wazuh-clusterd -f
  wazuh-clusterd: Orphan child process 1659 was terminated.
  Starting cluster in foreground (pid: 1669)
  2022/11/23 15:23:02 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
  2022/11/23 15:23:03 INFO: [Worker worker1] [Main] Successfully connected to master.
  ```
- `cluster.log` (master)
  ```
  2022/11/23 15:22:59 INFO: [Worker] [Main] Connection from ('172.28.0.2', 41884)
  2022/11/23 15:23:02 INFO: [Worker worker1] [Main] Cancelling pending tasks.
  2022/11/23 15:23:03 INFO: [Worker] [Main] Connection from ('172.28.0.2', 41900)
  ```

However, if the worker has already performed any task (for example `Integrity check`), when starting the process for the second time it is not able to connect to the master, even though it has killed the previous process successfully:
- `cluster.log` (worker)
  ```
  2022/11/23 15:25:58 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
  2022/11/23 15:25:58 INFO: [Worker worker1] [Main] Successfully connected to master.
  2022/11/23 15:26:07 INFO: [Worker worker1] [Integrity check] Starting.
  2022/11/23 15:26:07 INFO: [Worker worker1] [Integrity check] Finished in 0.032s. Sync not required.
  2022/11/23 15:26:08 INFO: [Worker worker1] [Agent-info sync] Starting.
  2022/11/23 15:26:08 INFO: [Worker worker1] [Agent-info sync] Finished in 0.006s. Updated 0 chunks.
  # /var/ossec/bin/wazuh-clusterd -f
  wazuh-clusterd: Orphan child process 1682 was terminated.
  Starting cluster in foreground (pid: 1695)
  2022/11/23 15:26:09 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
  2022/11/23 15:26:09 ERROR: [Worker worker1] [Main] Could not connect to master: Error 3028 - Worker node ID already exists: worker1.
  2022/11/23 15:26:09 INFO: [Worker worker1] [Main] The master closed the connection
  ```
- `cluster.log` (master)
  ```
  2022/11/23 15:25:58 INFO: [Worker] [Main] Connection from ('172.28.0.2', 60682)
  2022/11/23 15:26:00 INFO: [Master] [Local integrity] Starting.
  2022/11/23 15:26:00 INFO: [Master] [Local integrity] Finished in 0.009s. Calculated metadata of 34 files.
  2022/11/23 15:26:07 INFO: [Worker worker1] [Integrity check] Starting.
  2022/11/23 15:26:07 INFO: [Worker worker1] [Integrity check] Finished in 0.006s. Received metadata of 34 files. Sync not required.
  2022/11/23 15:26:08 INFO: [Master] [Local integrity] Starting.
  2022/11/23 15:26:08 INFO: [Master] [Local integrity] Finished in 0.010s. Calculated metadata of 34 files.
  2022/11/23 15:26:09 INFO: [Worker] [Main] Connection from ('172.28.0.2', 51310)
  2022/11/23 15:26:09 ERROR: [Worker] [Main] Internal error processing request 'b'hello'': Error 3028 - Worker node ID already exists: worker1
  2022/11/23 15:26:09 ERROR: [Worker] [Main] Error during handshake with incoming connection.
  2022/11/23 15:26:09 INFO: [Worker] [Main] Cancelling pending tasks.
  ```

This happens consistently. This is a behavior similar to that which has already been unsuccessfully investigated in https://github.com/wazuh/wazuh/issues/14996. It seems that the connection is closed abruptly in the worker or that the master, for some reason that needs to be investigated, does not trigger the `on_connection_lost` function in charge of removing the disconnected client from the clients' dictionary.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Description

- I was investigating further and it seems that the connection is re-established between master and worker after 2 minutes (too long).
 - I was looking for a way to directly re-establish the connection again with the master, as soon as the previous process is completed.

**Comment by javiersanchz** [comment]
## Description

- I was investigating why it doesn't properly handle the removal of old worker processes when a new process tries to register. The connection_lost function seems to work fine for disconnecting clients, but it doesn't solve this problem.
- I've been trying some options to solve it like using .abort()

**Comment by javiersanchz** [comment]
## Update

- It appears that the error occurs when you restart a process for the second time, and it has already performed some tasks in the running process (in the `background`). The issue occurs when initiating the second process, whether in the `background` or `foreground`.
`cluster.log`(worker)

```
root@wazuh-worker1:/# /var/ossec/bin/wazuh-clusterd
root@wazuh-worker1:/# /var/ossec/bin/wazuh-clusterd
wazuh-clusterd: Orphan child process 12918 was terminated.
```

`cluster.log`(master)

```
2023/09/04 16:50:30 INFO: [Worker worker] [Integrity check] Starting.
2023/09/04 16:50:30 INFO: [Worker worker] [Integrity check] Finished in 0.010s. Received metadata of 34 files. Sync not required.
2023/09/04 16:50:31 INFO: [Worker worker] [Agent-info sync] Starting.
2023/09/04 16:50:31 INFO: [Worker worker] [Agent-info sync] Finished in 0.007s. Updated 1 chunks.
2023/09/04 16:50:37 INFO: [Worker] [Main] Connection from ('172.18.0.2', 45420)
2023/09/04 16:50:37 ERROR: [Worker] [Main] Internal error processing request 'b'hello'': Error 3028 - Worker node ID already exists: b'worker'
2023/09/04 16:50:37 INFO: [Worker] [Main] Cancelling pending tasks.
```

- In summary, the issues appear to be related to process management and how previous processes are handled within the cluster (it seems that in these cases, the master does not trigger the connection_lost function to remove the disconnected client). I am continuing my investigation, but I have not yet been able to pinpoint the root cause of the problem.

**Comment by javiersanchz** [comment]
## Update

- It seems that the issue originates from the `hello` function in the `server`. This is because the clients name is the same as the one already in execution, which triggers the exception. It appears that by checking beforehand if the new clients name is in the dictionary of clients, and if it is, deleting the existing entry and adding the new one, the problem is resolved.

 ```
def hello(self, data: bytes) -> Tuple[bytes, bytes]:
        """Add a client's data to the global clients dictionary.

        Parameters
        ----------
        data : bytes
            Client's name.

        Returns
        -------
        bytes
            Result.
        bytes
            Response message.
        """
        new_name = data.decode()
        
        # Check if the new name is the same as the current name
        if new_name == self.name:
            return b'ok', f'Client {self.name} already added'.encode()
        
        # Check if the new name already exists in the clients dictionary
        if new_name in self.server.clients:
            # Remove the old client with the same name
            old_client = self.server.clients[new_name]
            self.logger.warning(f"Client {new_name} already exists. Disconnecting the old client.")
            old_client.transport.close()
            del self.server.clients[new_name]
        
        # Add the new client to the clients dictionary
        self.server.clients[new_name] = self
        self.name = new_name
        self.tag = f'{self.tag} {self.name}'
        context_tag.set(self.tag)
        
        return b'ok', f'Client {self.name} added'.encode()
```

`cluster.log `(worker)

```
root@wazuh-worker1:/# /var/ossec/bin/wazuh-clusterd
root@wazuh-worker1:/# /var/ossec/bin/wazuh-clusterd -f
wazuh-clusterd: Orphan child process 47671 was terminated.
Starting cluster in foreground (pid: 48054)
2023/09/05 17:11:07 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2023/09/05 17:11:07 INFO: [Worker worker] [Main] Successfully connected to master.
2023/09/05 17:11:16 INFO: [Worker worker] [Integrity check] Starting.
2023/09/05 17:11:16 INFO: [Worker worker] [Integrity check] Finished in 0.040s. Sync not required.
2023/09/05 17:11:17 INFO: [Worker worker] [Agent-info sync] Starting.
2023/09/05 17:11:17 INFO: [Worker worker] [Agent-info sync] Finished in 0.016s. Updated 1 chunks.
2023/09/05 17:11:25 INFO: [Worker worker] [Integrity check] Starting.
2023/09/05 17:11:25 INFO: [Worker worker] [Integrity check] Finished in 0.024s. Sync not required.
2023/09/05 17:11:27 INFO: [Worker worker] [Agent-info sync] Starting.
2023/09/05 17:11:27 INFO: [Worker worker] [Agent-info sync] Finished in 0.014s. Updated 1 chunks.
```
cluster.log (master)

```
2023/09/05 17:11:05 INFO: [Worker worker] [Agent-info sync] Starting.
2023/09/05 17:11:05 INFO: [Worker worker] [Agent-info sync] Finished in 0.007s. Updated 1 chunks.
2023/09/05 17:11:07 INFO: [Worker] [Main] Connection from ('172.18.0.6', 60398)
2023/09/05 17:11:07 WARNING: [Worker] [Main] Client worker already exists. Disconnecting the old client.
2023/09/05 17:11:07 INFO: [Worker] [Main] Cancelling pending tasks.
2023/09/05 17:11:16 INFO: [Worker worker] [Integrity check] Starting.
2023/09/05 17:11:16 INFO: [Worker worker] [Integrity check] Finished in 0.008s. Received metadata of 34 files. Sync not required.
2023/09/05 17:11:17 INFO: [Worker worker] [Agent-info sync] Starting.
2023/09/05 17:11:17 INFO: [Worker worker] [Agent-info sync] Finished in 0.006s. Updated 1 chunks.
```

**Comment by javiersanchz** [comment]
## Update 
- It seems that even though I [connect a new client and the old one with the same name](https://github.com/wazuh/wazuh/issues/15473#issuecomment-1707023976) is removed, it does not perform the agent-groups task correctly. `INFO: [Master] [Local agent-groups] Starting`, launching the following message as if there were no clients connected: `INFO: [Master] [Local agent-groups] No clients connected. Skipping.` This demonstrates that it does not perform the task of removing and adding a new client to the `clusterd` correctly.
