### ISSUE TITLE
Add SQLite flag DSQLITE_ENABLE_DBSTAT_VTAB 

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15474]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [dev-wd-vacuum-4-4](https://github.com/wazuh/wazuh-packages/compare/dev-wd-vacuum-4-4) | Dependencies | Manager - Agent | Packages - Sources | Any |
# Description

We need to include DSQLITE_ENABLE_DBSTAT_VTAB on SQLite build to enable DBSTAT table. due #15440. 

Also, librpm should be updated for linux (not centos5) OSes because it has sqlite as a dependency

# DoD
- [ ] Build the dependencies for each supported platform and architecture.
  - [ ] HPUX 11 [IA64] @jnasselle 
  - [x] AIX 6 [PPC] @jnasselle 
  - [x] MacOS catalina [AMD64] @Nicogp  
  - [x] Centos5 @jnasselle 
    - [x] amd64
    - [x] i386
  - [x] Linux 
    - [x] aarch64  @cborla 
    - [x] amd64 @sdvendramini 
    - [x] arm32 @cborla 
    - [x] i386 @sdvendramini 
    - [x] ppc64le @jnasselle 
  - [x] Solaris 10 
    - [x] i386 @Nicogp 
    - [x] sparc @jnasselle 
  - [x] Windows @cborla 
    - [x] i686 
- [x] Upload the compiled dependencies to S3. -> @vikman90 
- [x] Perform sanity testing to validate that Wazuh works as expected with the new dependencies. -> @wazuh/binary-beasts

**Comment by cborla** [comment]
Requested resources
https://github.com/wazuh/wazuh-automation/issues/977
https://github.com/wazuh/wazuh-automation/issues/978
https://github.com/wazuh/wazuh-automation/issues/979

**Comment by jnasselle** [comment]
@Dwordcito uploaded to AWS S3 DEPS 18 an 19 prebuilt sqlite to HPUX folder.
https://packages.wazuh.com/deps/18/libraries/hpux/ia64/sqlite.tar.gz
https://packages.wazuh.com/deps/19/libraries/hpux/ia64/sqlite.tar.gz
File hash: 5c10c5d33198123420b13fc2e03b99c4
