### ISSUE TITLE
Manager host validation issue in wazuh-authd on proxied connections

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#15484]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| n/a | wazuh-authd | Manager | n/a | n/a |

We've been reported that the agent is rejecting the manager when it's required to verify the manager's certificate.

## Network description

|Network|Router|Purpose|
|---|---|---|
|172.29.234.0/20|172.29.234.1|Manager|
|192.168.33.0/24|192.168.33.1|Agent & proxy|

### Hosts

|Host|Purpose|
|---|---|
|172.29.234.115|Manager|
|192.168.33.27|Proxy|
|192.168.33.26|Agent|

#### /etc/nginx/nginx.conf

```
stream {
    server {
        listen 2831;
        proxy_pass 172.29.234.115:1515;
    }
}
```

#### Manager's certificate

Note we're setting the manager's address to its local IP (172.29.234.115):

```sh
openssl req -x509 -new -nodes -newkey rsa:4096 -keyout rootCA.key -out rootCA.pem -batch -subj "/C=US/ST=CA/O=Wazuh"
openssl req -new -nodes -newkey rsa:4096 -keyout /var/ossec/etc/sslmanager.key -out sslmanager.csr -subj '/C=US/CN=172.29.234.115'
openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out /var/ossec/etc/sslmanager.cert -CAcreateserial

service wazuh-manager restart
```

#### Agent enrollment command 🟢 

```sh
$ agent-auth -m 172.29.234.115 -v /root/rootCA.pem

2022/11/25 11:03:04 agent-auth: INFO: Requesting a key from server: 172.29.234.115
(...)
2022/11/25 11:03:04 agent-auth: INFO: Valid key received
```

#### Agent enrollment command 🔴 

However, if we run `agent-auth` with the proxy's IP, it will reject the operation:

```sh
$ agent-auth -m 192.168.33.27 -p 2831 -v /root/rootCA.pem

2022/11/25 11:20:05 agent-auth: INFO: Requesting a key from server: 192.168.33.27
2022/11/25 11:20:05 agent-auth: ERROR: Unable to verify server certificate
```

### Rationale

The agent is trying to validate a certificate whose defined IP does not match the server IP.

**Comment by vikman90** [comment]
## Fix 1: Replace the manager's IP with the proxy's IP

#### Manager's certificate

We need to set up a new certificate that matches the proxy's IP:

```
openssl req -new -nodes -newkey rsa:4096 -keyout /var/ossec/etc/sslmanager.key -out sslmanager.csr -subj '/C=US/CN=192.168.33.27'
openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out /var/ossec/etc/sslmanager.cert -CAcreateserial

service wazuh-manager restart
```

#### Agent enrollment command 🟢 

```sh
$ agent-auth -m jammy -v /root/rootCA.pem -p 2831

2022/11/25 11:05:21 agent-auth: INFO: Requesting a key from server: 192.168.33.27
(...)
2022/11/25 11:05:21 agent-auth: INFO: Valid key received
```

**Comment by vikman90** [comment]
## Fix 2: Add the proxy's IP as an alternate name

If we need both addresses to work, we will need to set the manager's IP as the common name, and the proxy's IP as an alternate name.

### Request configuration file

#### req.conf

Note that both IPs get now declared

```
[req]
distinguished_name = req_distinguished_name
req_extensions = req_ext
prompt = no
[req_distinguished_name]
C = US
CN = 172.29.234.115
[req_ext]
subjectAltName = @alt_names
[alt_names]
DNS.1 = 192.168.33.27
```

### Manager's certificate

```sh
openssl req -new -nodes -newkey rsa:4096 -keyout /var/ossec/etc/sslmanager.key -out sslmanager.csr -config req.conf
openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out /var/ossec/etc/sslmanager.cert -CAcreateserial -extfile req.conf -extensions req_ext

service wazuh-manager restart
```

### Direct connection

#### Agent enrollment command 🟢

```sh
$ agent-auth -m 172.29.234.115 -v /root/rootCA.pem

2022/11/25 12:14:42 agent-auth: INFO: Requesting a key from server: 172.29.234.115
(...)
2022/11/25 12:14:42 agent-auth: INFO: Valid key received
```

### Proxied connection

#### Agent enrollment command 🟢 

```sh
$ agent-auth -m 192.168.33.27 -p 2831 -v /root/rootCA.pem

2022/11/25 12:15:05 agent-auth: INFO: Requesting a key from server: 192.168.33.27
(...)
2022/11/25 12:15:05 agent-auth: INFO: Valid key received
```

**Comment by jsoliani** [comment]
Thanks, @vikman90 for this, I have a question, I didn't see the issue of a certificate in the logs, only an SSL error, and the network 10.0.130.0 with the NGINX proxy works normally with agents on the same network but agents in the network 10.0.110.0 fail and all are using the same certificate. Maybe this picture helps: 
![image](https://user-images.githubusercontent.com/79342391/203988399-ac3b8fd1-b5a9-45e4-9234-0f7f7484e3d5.png)

**Comment by jsoliani** [comment]
Just to be clear, agents outside the network 172.27.17.0 (10.0.x.y) can't reach the manager on its static IP address, they can only contact the NGINX Proxy (10.0.130.70), so the agent-auth will be pointing to the Proxy and the port is 3128 instead of 1515 for registration.
