### ISSUE TITLE
OR logic in rule between multiple regex/match statements

### ISSUE THREAD

**Issue by theflakes** [wazuh/wazuh#155]
Would like the ability to specify the use or OR logic between multiple  regex/match statements in a single rule.  This would make rules much easier to read and therefore troubleshoot.  I have to often create long regex statements in a rule using multiple "|" operators.

**Comment by snaow** [comment]
Double post or too much related with:
https://github.com/wazuh/wazuh/issues/156

Closing. Thanks for the ideas and feedback.
