### ISSUE TITLE
Coverity reports that Syscollector may sleep while holding a lock

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#15557]
|Wazuh version|Component|Install type|Source|Related PR|
|---|---|---|---|---|
| 4.3.0 | Syscollector | Manager & Agent | #15532 | #10249 |

|CID|Type|Impact|File|
|---|---|---|---|
|1527747|Waiting while holding a lock|Medium|[wm_syscollector.c:73](https://github.com/wazuh/wazuh/blob/adb64ecc5e758fb848017657fb7d7d514c5fe88d/src/wazuh_modules/wm_syscollector.c#L73)|

**Comment by MiguelazoDS** [comment]
This happens here 

https://github.com/wazuh/wazuh/blob/dcb82531821cfef8351283e358729fdb3b7b5e51/src/shared/mq_op.c#L55-L60

**Comment by sebasfalcone** [comment]
@MiguelazoDS Thanks for the forensic!

This "defect" is intentional, it's marked as such on Coverity

This issue can be safely closed
