### ISSUE TITLE
Fix defects found by Coverity in 4.4.0-alpha1

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#15556]
|Wazuh version|Source|
|---|---|
|4.4.0-alpha1|#15532|

|CID|Type|Impact|Component|File|
|---|---|---|---|----|
|1527745|String not null terminated|High|Authd|[key_request.c:256](https://github.com/wazuh/wazuh/blob/9a61bfa86ea2e4fdd318ce7d62a6de98f18dd689/src/os_auth/key_request.c#L256)|
|1527742|Dereference null return value|Medium|Shared library|[md5_sha1_sha256_op.c:67](https://github.com/wazuh/wazuh/blob/9a61bfa86ea2e4fdd318ce7d62a6de98f18dd689/src/os_crypto/md5_sha1_sha256/md5_sha1_sha256_op.c#L67)|
|1527741|Logically dead code|Medium|Database sync module|[wm_database.c:913](https://github.com/wazuh/wazuh/blob/9a61bfa86ea2e4fdd318ce7d62a6de98f18dd689/src/wazuh_modules/wm_database.c#L913)|
|1527739|Time of check time of use|Low|Wazuh DB & sync module|[wdb_global_helpers.c:983](https://github.com/wazuh/wazuh/blob/9a61bfa86ea2e4fdd318ce7d62a6de98f18dd689/src/wazuh_db/helpers/wdb_global_helpers.c#L983)|

**Comment by chemamartinez** [comment]
Merged #15573
