### ISSUE TITLE
Release 4.4.0 - Alpha 1 - E2E UX tests - Wazuh Indexer ISM policies 

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh#15564]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                            |                                             |
|----------------------------|---------------------------------------------|
| **Test name**              | Wazuh Indexer ISM policies                  |
| **Category**               | Index State Management                      |
| **Deployment option**      | [Step by step][1]                           |
| **Main release issue**     | https://github.com/wazuh/wazuh/issues/15505 |
| **Main E2E UX test issue** | https://github.com/wazuh/wazuh/issues/15519 |
| **Release candidate #**    | Alpha 1                                     |

## Test description
Deploy Wazuh with the following design:

| Component | Guide                        | Cluster / Single | OS           |
|-----------|------------------------------|------------------|--------------|
| indexer   | [Step by step][1]            | Multi-node       | Ubuntu 16.04 |
| server    | [Step by step][1]            | Single-node      | Ubuntu 16.04 |
| dashboard | [Step by step][1]            | -                | Ubuntu 16.04 |
| agent     | [Installing Wazuh agents][2] | -                | Ubuntu 18.04 |

Test ISM policies in Wazuh Indexer (specifically related to retention policies, but rollover + alias are nice as well). https://opensearch.org/docs/latest/im-plugin/ism/index/

## Test report procedure

All test results must have one of the following statuses: 
|                 |                                                                         |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | All checks passed.                                                      |
| :red_circle:    | There is at least one failed result.                                    |
| :yellow_circle: | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed, and the results can be found [here](https://github.com/wazuh/wazuh/issues/15564#issuecomment-1334165527).

|            |                                           |                    |                                                                                         |
|------------|-------------------------------------------|--------------------|-----------------------------------------------------------------------------------------|
| **Status** | **Test**                                  | **Failure type**   | **Notes**                                                                               |
| 🟡         | Indexer installation step-by-step         | Warning            | Warning importing GPG-KEY-WAZUH                                                         |
| 🟡         | Indexer installation step-by-step         | Warning            | Warning enabling the service                                                            |
| 🟢         | Wazuh Server installation step-by-step    |                    |                                                                                         |
| 🟢         | Wazuh dashboard installation              |                    |                                                                                         |
| 🔴         | Deploying Wazuh agents on Linux endpoints | Error              | The agent did not enroll to the manager during installation. Manual enroll was required |
| 🔴         | Configure ISM                             | Poor documentation | Could not manage to set a correct alias for ISM rollover                                |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [x] @wazuh/cicd 
- [x] @davidjiglesias 

[1]: https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html "Step by step"
[2]: https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html "Installing Wazug agents"

**Comment by AlexRuiz7** [comment]
# Building the environmnent

I used 2 vagrant `bento/ubuntu:16.04` boxes. The boxes can reach each other:

To ensure the communication between the boxes, their IPs have been defined in 
their Vagrantfile, so they use a static IP.

To make it easier, the following information has been added to the `/etc/hosts` 
file of each box:

```apacheconf
indexer-01    192.168.56.10
indexer-02    192.168.56.11
server        192.168.56.15
dashboard     192.168.56.17
agent         192.168.56.20
```

Using `shh-keygen` and `ssh-copy-id`, we allow ssh connections between the boxes
using public keys instead of passwords.

```bash
# indexer-01
ssh-copy-id vagrant@indexer-02
```

# Installing the Wazuh Indexer step by step


## Certificates generation

1. Download the `wazuh-certs-tool.sh` script and the `wazuh-config.yml` configuration file:

```bash
$cmd curl -sO https://packages-dev.wazuh.com/4.4/wazuh-certs-tool.sh
$cmd curl -sO https://packages-dev.wazuh.com/4.4/config.yml
```

2. Edit the `config.yml`:

```yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-01
      ip: 192.168.56.10
    - name: indexer-02
      ip: 192.168.56.11
    # - name: indexer-3
    #   ip: <indexer-node-ip>
  server:
    - name: wazuh-1
      ip: 192.168.56.15
    #   node_type: master
    # - name: server-2
    #   ip: <server-node-ip>
    #   node_type: worker
    # - name: server-3
    #   ip: <server-node-ip>
    #   node_type: worker
  dashboard:
    - name: dashboard
      ip: 192.168.56.17
    # - name: dashboard-2
    #   ip: <dashboard-node-ip>
    # - name: dashboard-3
    #   ip: <dashboard-node-ip>
```

3. Run the `wazuh-certs-tool.sh`:

```bash
$cmd bash ./wazuh-certs-tool.sh -A
01/12/2022 19:00:20 INFO: Admin certificates created.
01/12/2022 19:00:21 INFO: Wazuh indexer certificates created.
01/12/2022 19:00:21 INFO: Wazuh server certificates created.
01/12/2022 19:00:21 INFO: Wazuh dashboard certificates created.
```

4. Compress the files:

```bash
tar -cvf ./wazuh-certificates.tar -C ./wazuh-certificates/ .
rm -rf ./wazuh-certificates
```
5. Copy the files to Wazuh Indexer, Wazuh Server and Wazuh Dashboard nodes:

```bash
cp wazuh-certificates.tar indexer-01
cp wazuh-certificates.tar indexer-02
cp wazuh-certificates.tar server
cp wazuh-certificates.tar dashboard
```

**Comment by alberpilot** [comment]
Looking at the vagrant files in the section Environment, I see that no assigned memory was mentioned, so vagrant assign 1GB. This doesn't match with the minimum required by documentation and the Wazuh indexer doesn't start because the Xmx and Xms defined in jvm.options are not correct.

**Comment by AlexRuiz7** [comment]
During the installation of Wazuh Dashboard, the [comment](https://documentation-dev.wazuh.com/4.4/installation-guide/wazuh-dashboard/step-by-step.html#installing-package-dependencies) `version 9 or later` is misleading. The version of what?

```bash
apt-get install debhelper tar curl libcap2-bin #debhelper version 9 or later
```

**Comment by alberpilot** [comment]
Regarding the comment here: https://github.com/wazuh/wazuh/issues/15564#issuecomment-1334165527
```
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
```

This is not a bug. The created conf file depends on the local installation and thus may or may not include a keyserver option.
Automatically restarting gpg to read the conf file is too complicated and error-prone. There is a clear warning for this case. Reference: https://dev.gnupg.org/T1244

The start service warnings was explained here:
https://github.com/wazuh/wazuh/issues/15534#issuecomment-1335499550

**Comment by s-ocando** [comment]
@alberpilot @AlexRuiz7 I've reproduced the "Deploying Wazuh agents on Linux endpoints" error using the same machines and  configuration described [here](https://github.com/wazuh/wazuh/issues/15564#issuecomment-1334165527). The enrollment fails because the agent and the manager have the same hostname. 

```
2022/12/07 11:28:11 wazuh-agentd: INFO: Started (pid: 3378).
2022/12/07 11:28:11 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.15
2022/12/07 11:28:11 wazuh-agentd: INFO: No authentication password provided
2022/12/07 11:28:11 wazuh-agentd: INFO: Using agent name as: vagrant
2022/12/07 11:28:11 wazuh-agentd: INFO: Waiting for server reply
2022/12/07 11:28:11 wazuh-agentd: ERROR: Invalid agent name: vagrant (from manager)
2022/12/07 11:28:11 wazuh-agentd: ERROR: Unable to add agent (from manager)
```
