### ISSUE TITLE
Wazuh API allows invalid group names

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#15572]
|Wazuh version|Component|
|---|---|
| 4.4.0-1 | Wazuh API |

## Description

Wazuh API allows invalid group names. This was detected during https://github.com/wazuh/wazuh/issues/15539 using the dashboard.

### Steps to reproduce
- Generate a new API token: `TOKEN=$(curl -u wazuh:wazuh -k -X GET "https//localhost55000/security/user/authenticate?raw=true")`
> Note: Replace the credentials accordingly
- Create a new group with an invalid name using the `groups` endpoint. For example: `curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯科飞 机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将\"}"`
- Notice that the response shows that the group was correctly created
```
[root@ip-172-31-17-26 ec2-user]# curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯科飞 机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将\"}"
{
   "message": "Group '\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de\u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06' created.",
   "error": 0
}
```
- Check the `ossec.log` file for a wazuh-db warning:
```
2022/12/02 11:31:47 wazuh-db: WARNING: Invalid group name. '解放扩大苏联飞机阿斯科飞机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将' contains invalid characters
```
- Check that the group is marked as registered when we perform the same request again
```
[root@ip-172-31-17-26 ec2-user]# curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯科飞 机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将\"}"
{"title": "Bad Request", "detail": "The group already exists: \u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de\u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06", "remediation": "Please, use another group ID", "dapi_errors": {"node01": {"error": "The group already exists: \u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de\u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"}}, "error": 1711}
```

### Video
[bad_validation_group_names.webm](https://user-images.githubusercontent.com/11089305/205284536-730def06-8686-4af5-b7c5-a18fe89ced02.webm)

**Comment by fdalmaup** [comment]
# Issue Update
The steps from the issue's description were followed to reproduce the errors in two different Wazuh versions.

## Reproducing the behavior in v4.4.0
API requests
```
curl -k -X POST "https://localhost:55000/groups?pretty=true" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯科飞 机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将\"}"
{"title": "Bad Request", "detail": "'\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de \u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06' is not a 'group_names' - 'group_id'"}

curl -k -X POST "https://localhost:55000/groups?pretty=true" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯佛教典籍阿克苏将\"}"
{
   "message": "Group '\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06' created.",
   "error": 0
}
```

<details><summary>api.log</summary>

    2022/12/13 09:17:01 INFO: wazuh 172.20.0.1 "POST /groups" with parameters {"pretty": "true"} and body {"group_id": "\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de \u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"} done in 0.013s: 400
    2022/12/13 09:21:38 INFO: wazuh 172.20.0.1 "POST /groups" with parameters {"pretty": "true"} and body {"group_id": "\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"} done in 0.048s: 200

</details>

After the second request that allowed the creation of the invalid group, the `ossec.log` had the following WARNING message:
```
2022/12/13 09:21:38 wazuh-db[136] wdb_global.c:1306 at wdb_global_validate_group_name(): WARNING: Invalid group name. '解放扩大苏联飞机阿斯佛教典籍阿克苏将' contains invalid characters
```

When re-executing the group creation request, the following response was found:
```
{"title": "Bad Request", "detail": "The group already exists: \u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06", "remediation": "Please, use another group ID", "dapi_errors": {"wd_master_1": {"error": "The group already exists: \u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"}}, "error": 1711}
```

And the `api.log` registered it with the `400` status code.
```
2022/12/13 09:25:14 INFO: wazuh 172.20.0.1 "POST /groups" with parameters {"pretty": "true"} and body {"group_id": "\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"} done in 0.023s: 400
```

In conclusion, the reported behavior was checked.

## Reproducing the behavior in v4.3.10
When executing the same requests to a Wazuh v4.3.10 manager, the group was not created and `Bad Request` responses were received.

```
curl -k -X POST "https://localhost:55000/groups?pretty=true" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯科飞 机阿斯洛伐克加大了看似简单法卡斯佛教典籍阿克苏将\"}"
{"title": "Bad Request", "detail": "'\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de \u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06' is not a 'group_names' - 'group_id'"}

curl -k -X POST "https://localhost:55000/groups?pretty=true" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d "{\"group_id\":\"解放扩大苏联飞机阿斯佛教典籍阿克苏将\"}"
{"title": "Bad Request", "detail": "Incorrect format for group_id", "remediation": "Characters supported  a-z, A-Z, 0-9, ., _ and -. Max length is 255", "dapi_errors": {"wd_master_1": {"error": "Incorrect format for group_id"}}, "error": 1722}
```

<details><summary>api.log</summary>

    2022/12/13 09:37:21 INFO: wazuh 172.21.0.1 "POST /groups" with parameters {"pretty": "true"} and body {"group_id": "\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u79d1\u98de \u673a\u963f\u65af\u6d1b\u4f10\u514b\u52a0\u5927\u4e86\u770b\u4f3c\u7b80\u5355\u6cd5\u5361\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"} done in 0.019s: 400
    2022/12/13 09:37:50 INFO: wazuh 172.21.0.1 "POST /groups" with parameters {"pretty": "true"} and body {"group_id": "\u89e3\u653e\u6269\u5927\u82cf\u8054\u98de\u673a\u963f\u65af\u4f5b\u6559\u5178\u7c4d\u963f\u514b\u82cf\u5c06"} done in 0.009s: 400


</details>

## Conclusions

The reported behavior was found only in v4.4.0. In previous Wazuh versions, the endpoint was working as expected, not allowing the creation of invalid groups.

**Comment by fdalmaup** [comment]
# Issue Update

The main difference between `v4.4.0-alpha1` and `v4.3.10` regarding group name validation is the `_group_names` regex used for it. This regex was modified and later used in the `InputValidator` class to verify the `group_name`. Previously, the `group` method from that class used explicitly `r'[A-Za-z0-9.\-_]+'` instead of `_group_names`.

`v4.4.0-alpha1`
https://github.com/wazuh/wazuh/blob/fa57c41be20656d5e596efdaffbd6d3bf89653b4/api/api/validator.py#L24

https://github.com/wazuh/wazuh/blob/fa57c41be20656d5e596efdaffbd6d3bf89653b4/framework/wazuh/core/InputValidator.py#L42-L55

`v4.3.10`
https://github.com/wazuh/wazuh/blob/89530f11c9e592cd2e551432209b0080f08ff8e5/api/api/validator.py#L22

https://github.com/wazuh/wazuh/blob/89530f11c9e592cd2e551432209b0080f08ff8e5/framework/wazuh/core/InputValidator.py#L43-L56
