### ISSUE TITLE
Agent starts with an invalid FIM configuration.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15576]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | FIM | Agent | Packages/Sources | Linux/Windows |

## Description

It was found that the agent starts with a Syscheck configuration error when an invalid option is set. On Linux, the error seems to be the error code returned during the configuration test of the module. 

![image](https://user-images.githubusercontent.com/13010397/205318165-0c09c0fb-99ef-4a5f-a6e8-de24e3703370.png)
 
On Windows the issue is similar. The error does not avoid the agent to start. 

<details>
<summary>Show image</summary>

![image](https://user-images.githubusercontent.com/13010397/205318266-d1562bb8-3642-48c4-862b-7a8ceefb45ae.png)

</details>

A different situation occurs with Active Response, where the agent does not start if we set an invalid option in the configuration file

<details>
<summary>Show image</summary>

![image](https://user-images.githubusercontent.com/13010397/205318815-cc4cc68a-de79-42b6-903b-aa958571739e.png)

</details>

It is required to review whether this behavior is expected and planned on purpose or it is required to unify this for all modules.

**Comment by vikman90** [comment]
@MiguelazoDS thank you for reporting this!

Actually, this behavior is expected. Related tasks:
|Issue|PR|Version|
|---|---|---|
|https://github.com/wazuh/wazuh/issues/4665|https://github.com/wazuh/wazuh/pull/4843|3.13.0|

The most important thing is that the agent shall not restart on an invalid configuration, as I've just tested.

However, we should unify the behavior, as you say. For instance:

- **ossec.conf**
```xml
  <localfile>
    <log_format>none</log_format>
    <location>/var</location>
  </localfile>
```

- Log:
```
2022/12/07 11:18:39 wazuh-logcollector: ERROR: (1235): Invalid value for element 'log_format': none.
2022/12/07 11:18:39 wazuh-logcollector: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
2022/12/07 11:18:39 wazuh-logcollector: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
```

Best!

**Comment by JoseMiguelGD** [comment]
I have tested the different invalid configurations of the Wazuh agent configuration modules.


`Linux Agent`

|MODULE|TYPE OF ERROR|STATUS|
|---|---|---|
|SYSCHECK|ERROR|START|
|ACTIVE-RESPONSE|CRITICAL|---|
|CLIENT|CRITICAL|---|
|CLIENT-BUFFER|CRITICAL|---|
|ROOTCHECK |ERROR|START|
|OSQUERY|ERROR|NO START|
|SYSCOLLECTOR|ERROR|NO START|
|LOCAL FILE|CRITICAL|---|
|SCA|ERROR|NO START|
|SOCKET |CRITICAL|---|
|AGENT-UPGRADE|ERROR|NO START|
|GITHUB|ERROR|NO START|
|LABEL|CRITICAL|---|
|LOGGING|CRITICAL|---|
|OFFICE365|ERROR|NO START|
|FLUENT-FORWARD|ERROR|NO START|
|GCP-PUBSUB|ERROR|NO START|
|GCP-BUCKET|ERROR|NO START|
|GCP-PUBSUB|WARNING CREDENTIALS|NO START|
|GCP-BUCKET|WARNING CREDENTIALS|NO START|

`Windows Agent`

|MODULE|TYPE OF ERROR|STATUS|
|---|---|---|
|SYSCHECK|CRITICAL|---|
|ACTIVE-RESPONSE|CRITICAL|---|
|CLIENT|CRITICAL|---|
|CLIENT-BUFFER|CRITICAL|---|
|ROOTCHECK |NO ERROR|START|
|OSQUERY|ERROR|NO START|
|SYSCOLLECTOR|NO ERROR|START|
|LOCAL FILE|CRITICAL|---|
|SCA|ERROR|NO START|
|SOCKET |CRITICAL|---|
|AGENT-UPGRADE|ERROR|NO START|
|GITHUB|ERROR|NO START|
|LABEL|CRITICAL|---|
|LOGGING|CRITICAL|---|
|OFFICE365|ERROR|NO START|
|FLUENT-FORWARD|ERROR|NO START|
|GCP-PUBSUB|ERROR|NO START|
|GCP-BUCKET|ERROR|NO START|
|GCP-PUBSUB|WARNING CREDENTIALS|NO START|
|GCP-BUCKET|WARNING CREDENTIALS|NO START|
