### ISSUE TITLE
Improve output message for recursive load catalog cases using the engine's API 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#15607]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3636   |         https://github.com/wazuh/wazuh/issues/15312  |

# Description

During testing performed after changes to the upload feature were applied. Improvements are requested in the output messages. It will help the user to understand the possible failure.

More details [here](https://github.com/wazuh/wazuh-qa/issues/3636).

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp 

#  Cases

### Case 1 - Recursive load: <code>decoder</code> 

| Case | Command | Currect Result | Expect Result
|--|--|--|--|
Load existent decoders | **/var/ossec/engine/wazuh-engine catalog load -r decoder ruleset/decoders/** |  _Error: [Catalog] Could not post content [decoder/queue-dbsync/0] in store, [FileDriver::add] File [/var/ossec/engine/store/decoder/queue-dbsync/0] already exists_ |  _Log error clear and less technical._

### Case 2 - Recursive load: <code>schema</code>

| Case | Command | Currect Result | Expect Result
|--|--|--|--|
Recursive load | /var/ossec/engine/wazuh-engine catalog load -r schema ruleset/schemas/ |  _Error: [Catalog] Content name not found_ | _Log error clear and less technical._

  > Note: The recursive load works as expected but there are only two schemas within the current `ruleset/schemas` dir and the `wazuh-environments.json` schema has no `name` field, so it fails. Besides, there are more files that are no schemas like `ecs_types.json`, so they won't load. 

### Case 3 - Recursive load: non-existent <code>item-type</code>

| Case | Command | Currect Result | Expect Result
|--|--|--|--|
load -r option  |  /var/ossec/engine/wazuh-engine catalog load -r atype /tmp | _Invalid collection name: atype_ |  _This log could be improved with `--help` reference and/or expected collection names_

**Comment by roronoasins** [comment]
These changes were tested using the `11334-dev-new-wazuh-engine` branch.

---

The following cases were fixed:
- `Case 1 - Recursive load: decoder`


The changes that remains need to be fixed.

**Comment by JcabreraC** [comment]
The messages have been changed and are more descriptive about the process.
