### ISSUE TITLE
FIM Issue in Windows Agent

### ISSUE THREAD

**Issue by FahimOstrich** [wazuh/wazuh#15619]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | Wazuh agent | Agent | Packages | Windows 10 Pro [Ver: 10.0.19044] |

Hello Team, 

We have observed that Syscheck File Integrity Monitoring Module is not being able to detect any changes when we set a custom `<directories>` configuration for any file or directory. We have added the following line in the `syscheck` configuration section to monitor changes in ‪`C:\Users\Users.txt` file:

`<directories report_changes="yes" check_all="yes" whodata="yes">‪C:\Users\Users.txt</directories>`

However, we got no syscheck alerts for the changes in this file. After enabling syscheck debug in verbose mode (`syscheck.debug=2`) in the agent, we got logs as following:

```
2022/12/02 00:00:43 wazuh-agent[5896] win_whodata.c:1001 at state_checker(): DEBUG: (6022): 'c:\program files (x86)\ossec-agent\‪c:\users\users.txt' has been deleted. It will not be monitored in real-time Whodata mode.
2022/12/02 00:01:43 wazuh-agent[5896] win_whodata.c:1001 at state_checker(): DEBUG: (6022): 'c:\program files (x86)\ossec-agent\‪c:\users\users.txt' has been deleted. It will not be monitored in real-time Whodata mode.
```

The logs are indicating that syscheck is trying to monitor `c:\program files (x86)\ossec-agent\‪c:\users\users.txt` instead of `‪c:\users\users.txt`. This issue happens for both local (`ossec.conf`) and centralized (`agent.conf`) configuration.

Let me know if you need any more information. We can provide any log or configuration privately if needed to diagnose the issue.

Regards,
Abdullah Al Rafi Fahim

**Comment by adi5353** [comment]
Hi Team,

Closing this issue for now as information we got is not correct for now. I will re-open if this issue persist again.
