### ISSUE TITLE
Infinite loop when redirecting the input (log) to the engine's `test` feature using a pipe

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#15612]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3638   |     https://github.com/wazuh/wazuh/issues/15276 |

# Description

During the testing an infinite loop has been found when redirecting the input (log) to the engine's `test` feature using a pipe

```
root@engine:/home/vagrant# echo 'a log' | /var/ossec/engine/wazuh-engine test
Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



.
.
.

Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):



Enter log in single line (Crtl+C to exit):


^C
root@engine:/home/vagrant#
```

## Considerations

More details [here](https://github.com/wazuh/wazuh-qa/issues/3638).

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
To close this issue, the main test, as it was originally configured, no longer exists. This setup was applicable when it was not based on an API. Additionally, the bug in the engine-test has been resolved. On a positive note, the client now functions properly.
