### ISSUE TITLE
Improve output message to the new object mapping cases using the engine's API 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#15611]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3638   |     https://github.com/wazuh/wazuh/issues/15276 |

# Description

The new way in which the objects can be mapped, allows detecting some improvements to be applied in the output messages that will help the user to understand the failure.

More details [here](https://github.com/wazuh/wazuh-qa/issues/3638).

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp 

#  Cases

### Case 1 - Using the new supported mapping

| Command | Currect Result | Expect Result
|--|--|--|
/var/ossec/engine/wazuh-engine catalog update decoder/sca/0 < ruleset/decoders/wazuh-agent/sca/sca.yml  | _Error: [Catalog] Engine validation failed for [decoder/sca/0], [Catalog] Engine validation failed for [decoder/sca/0], exception: Asset::Asset(jsonDefinition, type)] failed to build stage parse exception: [builder::stageBuilderParse(json)] Error building parser [logpar]: bad optional access exception: bad optional access_ | _It should tell the user that there is a syntax error. Then, be more specific about the section it failed._

### Case 2 - RULES information in the test feature
    
1. When no rule is triggered, this empty block appears
    > RULES:
2. It should not be there if it is empty or it should specify that no rule has been triggered. For example:
    > RULES: No rule has been triggered.

**Comment by JcabreraC** [comment]
It doesn't give the necessary information to replicate that error, but logpar has changed a lot since this issue. 

The second case was fixed.
