### ISSUE TITLE
Wrong behavior when connection refused when executing env subcommand

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#15620]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3537|   https://github.com/wazuh/wazuh/issues/11334  |

# Description
During the tests carried out in the [validations of the API option](https://github.com/wazuh/wazuh/issues/11334), it was possible to detect some strange behavior and some recommended improvements. 

## Case 1: -a,--api_socket option - Use a non-existent API socket

1. Execute `/var/ossec/engine/wazuh-engine env -a /tmp get`

    > root@engine:/home/vagrant/engine/wazuh/src/engine/ruleset# /var/ossec/engine/wazuh-engine env -a /tmp get 
    > API Client ErrorEvent: connection refused
    > Error sending request: [Json(jsonString)] Unable to build json document because: The document is empty. at 0

## Case 2: -a,--api_socket option - Use a non-existent path as API socket 

1. Execute `/var/ossec/engine/wazuh-engine env -a /nopath get` 

    > root@engine:/home/vagrant/engine/wazuh/src/engine/ruleset# /var/ossec/engine/wazuh-engine env -a /nopath get 
    > API Client ErrorEvent: no such file or directory
    > Error sending request: [Json(jsonString)] Unable to build json document because: The document is empty. at 0
    > root@engine:/home/vagrant/engine/wazuh/src/engine/ruleset#

### Expected Behaviour for the 2 cases: 

- The program stop when the error appears

    > API Client ErrorEvent: connection refused

- Improve the error log:  _Log error clear and less technical_.

More details [here](https://github.com/wazuh/wazuh-qa/issues/3537#issuecomment-1326380364).

## Considerations 

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
The 'env' command has been deprecated, and now a different error is encountered. When attempting to execute the command:

```bash
./build/main test --api_socket /dev/null session list
```
The error 'Socket communication error: connection refused' is observed. Furthermore, when trying to use an incorrect socket path:

```bash
./build/main test --api_socket /dev/nul2l session list
```
The error 'File does not exist: /dev/nul2l' is reported. Please refer to the '--help' option for more information on proper command usage.
