### ISSUE TITLE
Improve output for CMD parameters and API commands using the engine's API 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#15624]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3537|   https://github.com/wazuh/wazuh/issues/11334  |

# Description

During the tests carried out in the https://github.com/wazuh/wazuh-qa/issues/3537, we recommended improvements to the output messages. It will help the user to understand the possible failure. 

More details [here](https://github.com/wazuh/wazuh-qa/issues/3537).

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp 

# Cases

### Case 1: Missing logging

  The engine does not notify the user when it is started using invalid sockets. 
  
  If we start the engine using a socket that does not exist, it will start without showing any warning or something that warns the user about it. At least a log that warns the user should appear if we want that the engine starts even there.
  
  - `-e,--event_endpoint option` - non-valid socket and it starts
  - `-a,--api_endpoint option` - Using a non-existent API endpoint socket but it starts
  - `-k,--kvdb_path option` - Provide a path with non-existent kvdb

---
### Case 2: Improve the output when a non-existent environment starting

  If you start the engine providing an invalid environment's name, it will start anyways.
  
  The engine'd throw an error like this:
  
>   806297 cmdRun.cpp:158   WRN[4059  ] Error creating default environment [asd]: Invalid environment name  asd

  But you can perform API requests, but it is not logged that any environment has been activated correctly.

---

### Case 3: Add logging when using a non-valid socket

  If we start the engine using an API socket that does not exist, it will start and the logging do not warn about it and logs that the API endpoint has been configured.
  
  > root@engine:/home/vagrant# /var/ossec/engine/wazuh-engine start -a mysocket -l 0
  > 17:11:21.501514 cmdRun.cpp:73    INF[6007  ] Logging initialized
  > 17:11:21.501878 apiEndpoint.cpp:186 INF[6007  ] API endpoint configured: [mysocket]
  > 17:11:21.510890 cmdRun.cpp:89    INF[6007  ] Server configured
  > 17:11:21.510909 cmdRun.cpp:92    INF[6007  ] KVDB initialized
  > 17:11:21.510917 cmdRun.cpp:101   INF[6007  ] Store initialized
  > 17:11:21.510917 cmdRun.cpp:104   INF[6007  ] Builder initialized
  > 17:11:21.522795 cmdRun.cpp:117   INF[6007  ] Catalog initialized
  
  It should not log the API endpoint configured as a info log, it has to warn the user.

---

### Case 4: When no kvdb is provided there are no notifications

When you run the test feature with a path that does not contain a kvdb, it runs normally. The problem is that no notification is provided that warns the user that the provided path (using the `--kvdb-path` option) is not valid. This allows the user running the tool with no kvdb and if a decoder/rule needs the kvdb won't work.

---

### Case 5: The kvdb path is slash sensitive

If you run the test feature providing a kvdb path, it won't work if you do not end the path with a slash (`/`)

```
root@engine:/home/vagrant# /var/ossec/engine/wazuh-engine test -k /var/ossec/etc/kvdb -dd --environment environment/wazuh/1
16:17:50.613326 kvdb.cpp:88      ERR[7529  ] Couldn't create DB [malicious-ip] file, error: [Invalid argument: /var/ossec/etc/kvdbmalicious-ip/CURRENT: does not exist (create_if_missing is false)]
16:17:50.613985 kvdb.cpp:88      ERR[7529  ] Couldn't create DB [malicious-ip] file, error: [Invalid argument: /var/ossec/etc/kvdbmalicious-ip/CURRENT: does not exist (create_if_missing is false)]
16:17:50.614085 kvdbManager.cpp:143 ERR[7529  ] Error initializing db [malicious-ip].
16:17:50.614949 cmdTest.cpp:152  ERR[7529  ] Exception while building environment: [exception: Failed to build asset: rule/source-malicious-ip/0
    exception: [Asset::Asset(jsonDefinition, type)] failed to build stage check
    exception: [builders::operationBuilder(<definition, type>)] Exception building helper [kvdb_match]
    exception: [malicious-ip] DB isn't available for usage
]
```

---

### Case 6: When no rule is triggered the rules string appears with no content

When you run the test feature and no rule is triggered the string `RULES:` appears between the decoders' trace and the output. It could be better to show something like no rule has been triggered or nothing related to the `RULES:` string.

---

### Case 7: The queue parameter information/logging is not enough

When you run the test feature and specify a custom queue, we are not notified that we are allow to use just upto `127` as value. If we try to use a higher value, it just says `Could not convert: --protocol_queue = 128`. This could be improved, specifying the supported values.

---

### Case 8: Improve the output 

| Case | Command | Currect Results | Expected Results
|--|--|--|--|
| List loaded filter  | /var/ossec/engine/wazuh-engine catalog -j list filter | _Error: [Catalog] Could not get content [filter] from store, [FileDriver] File [/var/ossec/engine/store/filter] does not exist_ | _Log error clear and less technical_.
List loaded rule | /var/ossec/engine/wazuh-engine catalog -j list filter | _Error: [Catalog] Could not get content [filter] from store, [FileDriver] File [/var/ossec/engine/store/filter] does not exist_ | _Log error clear and less technical_.
-t,--threads option - Using strings instead of integers | /var/ossec/engine/wazuh-engine start -t a -l 0 | _Could not convert: --threads = a_ | _The log could be more descriptive to the user, instead of showing Could not convert_
-t,--threads option - Using negative integer | /var/ossec/engine/wazuh-engine start -t -1 -l 0 | _Could not convert: --threads = -1_ | _The log could be more descriptive to the user, instead of showing Could not convert_
-f,--file_storage option - Starting the engine using an invalid schema | /var/ossec/engine/wazuh-engine start -l 0 -f /tmp/store/ | _Error initializing modules: exception: [Catalog] Error while getting asset schema: [FileDriver] Could not parse file [/tmp/store/schema/wazuh-asset/0] due to [[Json(jsonString)] Unable to build json document because: Missing a comma or '}' after an object member. at 259]_ | _The log could be improve to the user, like X exists but the json schema is not correctly formatted_
-q,--queue_size option - Negative queue size | /var/ossec/engine/wazuh-engine start -q -1 | _Could not convert: --queue_size = -1_ | _The Could not convert message could be improved, so the user can understand the supported queue size_
Starting the engine using an invalid assets' folder |  /var/ossec/engine/wazuh-engine start -l 0 -f /tmp | _Error initializing modules: exception: [Catalog] Error while getting asset schema: [FileDriver] File [/tmp/schema/wazuh-asset/0] does not exist_ | _X is missing within the assets' folder'_
-f,--file_storage option - Use a non-existent assets' directory | /var/ossec/engine/wazuh-engine graph -f /tmp | _Could not retreive configuration file [schema/wazuh-logpar-types/0] needed by the HLP module, error: [FileDriver] File [/tmp/schema/wazuh-logpar-types/0] does not exist_ |  _Log error clear and less technical_.
Obtain some decoders with non-existing version | `/var/ossec/engine/wazuh-engine catalog -j get decoder/json/22` or `/var/ossec/engine/wazuh-engine catalog -j get decoder/json/𐤌 ` | _Error: [Catalog] Could not get content [decoder/json/22] from store, [FileDriver] File [/var/ossec/engine/store/decoder/json/22] does not exist_ | _The logging could be improved, so the user can identify the error instead of talking about the files_.
Update an uncorrect id or version for a given item-type | /var/ossec/engine/wazuh-engine catalog -j update decoder/js/1 < json.json |  _Error: [Catalog] Invalid content name [decoder/json/1] for decoder [decoder/js/1]_ |  _The given log could be improved so the user can identify that the item defined in the decoder file does not match with the one they're trying to update._
Create a custom decoder that already exists using a json file | /var/ossec/engine/wazuh-engine catalog -j create decoder < json.json  | _Error: [Catalog] Could not post content [decoder/json/1] in store, [FileDriver::add] File [/var/ossec/engine/store/decoder/json/1] already exists_ |  _The log is just talking about files, it could be improved so the user can read that the item already exists._
Create an item using a type that is not expected |  /var/ossec/engine/wazuh-engine catalog -j create atype < json.json | _Error: Invalid collection type [atype]_  | _The log could be improved, also the possible values can be printed or at least reference the help function so the user can get more info._
Try to delete empty item type |  /var/ossec/engine/wazuh-engine catalog -j delete decoder/json/1 | _Error: [Catalog] Could not delete content [decoder/json/1] from store, [FileDriver::erase] File [/var/ossec/engine/store/decoder/json/1] does not exist_ |  _We could improve this log, and tell the user that there are no decoders instead of X file does not exist. We could add a log telling the user how to check the list of the loaded item-type items within the catalog, in case the user do not know the current items that its environment has._
Missing required parameter | /var/ossec/engine/wazuh-engine catalog -j delete | _name is required_ | _We could improve this log, instead of just logging name is required. It could be more like the --help message format item-type[/item-id[/version]]_
Delete non-valid types, ids and versions  | /var/ossec/engine/wazuh-engine catalog -j delete decoder/jsonss | _Error: [Catalog] Could not delete content [decoder/jsonss] from store, [FileDriver::erase] File [/var/ossec/engine/store/decoder/jsonss] does not exist_ |  _Log error clear and less technical_.
Delete non-valid types, ids and versions  | /var/ossec/engine/wazuh-engine catalog -j delete atype | _Error: Invalid collection type [atype]_  |  _Log error clear and less technical_.
Validate a decoder with valid syntax |  /var/ossec/engine/wazuh-engine catalog -j validate decoder/json/1 < json.json  | _OK_ |  _Is there a way to have a trace of the checks that it performs to know if the validate went good? If not, could we add it?_
Validate a decoder with no name section  | /var/ossec/engine/wazuh-engine catalog -j validate decoder/json/1 < json.json  | _Error: [Catalog] Could not validate content, [Catalog] Engine validation failed for [decoder/json/1], exception: [Asset::Asset(jsonDefinition, type)] Asset definition missing string name_ | _It has an extra new line. Log error clear and less technical_
Could not load existing decoders | /var/ossec/engine/wazuh-engine catalog -j load decoder . | Error: [Catalog] Could not post content [decoder/json/1] in store, [FileDriver::add] File [/var/ossec/engine/store/decoder/json/1] already exists | _Log error clear and less technical_
Load some decoders that already exists and other that do not | /var/ossec/engine/wazuh-engine catalog -j load decoder . |  _OK Error: [Catalog] Could not post content [decoder/json/0] in store, [FileDriver::add] File [/var/ossec/engine/store/decoder/json/0] already exists_ | _Log error clear and less technical_
Update a non-existent item-type | /var/ossec/engine/wazuh-engine catalog -j update atype/json/1 < json.json  | _Error: Invalid collection type [atype] for [error_type]_ | _The log received looks not correct, returning error_type and not giving info about expected collection types or a note telling the user to run the --help to get the supported collection values._
-q,--queue_size option - Queue size 0 |  /var/ossec/engine/wazuh-engine start -l 0 -q 0 | _Currently, the engine allows us starting it like this for testing purposes_ | _This will be discussed in the future when the test phase is nearly finished_
Using non-existent API socket path | ./build/main kvdb -a nopath dump -n akvdb | _17:14:02.440035 connection.cpp:28 ERR[3879  ] Engine API Client: no such file or directory. 17:14:02.440405 cmdApiKvdb.cpp:133 ERR[3879  ] Engine "kvdb" command: "kvdbDump" method: JSON document could not be parsed: The document is empty.._ | _It does not stop when it notifies that the provided path does not exist. Also, the logging has an extra final dot: The document is empty.._
Using a path that is not a valid API socket path | ./build/main kvdb -a /tmp dump -n akvdb | _8 ERR[3894  ] Engine API Client: connection refused. 17:16:06.956765 cmdApiKvdb.cpp:133 ERR[3894  ] Engine "kvdb" command: "kvdbDump" method: JSON document could not be parsed: The document is empty.._ | _It looks like there is no parameter validation. It should stop when the connection has been refused and log it in a proper way, like: could not connect to /path/to/socket socket (or some kind of log that the user can make a relation between the real issue and the provided log) Also, the loggin has an extra final dot: The document is empty.._
Update a non-existent item-type | ./build/main catalog update newtype/json/1 < ruleset/decoders/json.yml | _Error: Invalid collection type [newtype] for [error_type]_ | _The log received is not correct, returning error_type and not giving info about expected collection types or a note telling the user to run the --help to get the supported collection values._
Repetitive logging when using more than one thread | ./build/main server --threads 3 start | _The same decoder loading logs are shown the threads number times_ | _The same decoder loading logs appear just once and do not flood the logging_ or _Appear with the threads identifier at least._
Provide a non-existinent configuration file path| ./build/main --config /tmp/nocfg server start | _/tmp/nocfg was not readable (missing?)_ | _The provided configuration file /tmp/nocfg does not exist._

**Comment by JcabreraC** [comment]
The component APIs have been evolving since this issue. After several tests, we can consider these bugs fixed.

For case 6, it is not exactly the same case because before we accepted a number and now a char.
