### ISSUE TITLE
Wazuh-Archives-* / Syslog not showing alerts in Wazuh-App only Kibana Discovery

### ISSUE THREAD

**Issue by AshourAziz** [wazuh/wazuh#1562]
## Bug report

**OS**
CentOS 7

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
Manager

**Install method**
Packages

Bug description
----------------

I came accross this issue (https://github.com/wazuh/wazuh/issues/152) 
and was able to integrate raw output with adding wazuh-archives-* | But the logs from wazuh-archives-* do not show up in the wazuh app's alerts. Although in the Kibana discovery tab the logs show what alert they trigged. The data is coming from syslog, I'm not sure if this is just because the logs are from syslog and not an agent. 

So my question essentially is why are the alerts not showing up in the Wazuh app if they're triggering alerts?

**Comment by TJOSERAFAEL** [comment]
Hi @AshourAziz ,

the file **/var/ossec/logs/archives/archives.log** shows the raw input that the manager is getting. Now the real alerts are stored on **/var/ossec/logs/alerts/alerts.log** or .json. 

If you see the input in the archives file but no alerts are generated on the alerts.log then you need to write your own custom rules to trigger an alert.

Could you please post some of those **syslog** events that you are getting from the **archives.log** file?

Best regards.

**Comment by chickenwing81** [comment]
Hi, i have the same Problem. I added my own Decoder and as well a Ruleset. When I test the Ruleset the result is fine and an Alert should be created. But when the message is received via Syslog it is placed in the archives.log but not showing up in Discover.

`2021 Sep 02 00:11:52 Hostname->192.168.10.1 Sep  2 00:11:52 Hostname suricata[58907]: {"timestamp": "2021-09-02T00:11:52.716108+0200", "flow_id": 1899414823336704, "in_iface": "igb2", "event_type": "alert", "src_ip": "192.168.10.194", "src_port": 48222, "dest_ip": "172.65.200.133", "dest_port": 3380, "proto": "TCP", "alert": {"action": "allowed", "gid": 1, "signature_id": 2826930, "rev": 3, "signature": "ETPRO POLICY XMR CoinMiner Usage", "category": "Potential Corporate Privacy Violation", "severity": 1, "metadata": {"mitre_technique_name": ["Resource_Hijacking"], "mitre_technique_id": ["T1496"], "mitre_tactic_name": ["Impact"], "mitre_tactic_id": ["TA0040"], "updated_at": ["2020_08_19"], "tag": ["Coinminer"], "signature_severity": ["Major"], "former_category": ["COINMINER"], "deployment": ["Perimeter"], "created_at": ["2017_06_28"], "attack_target": ["Client_Endpoint"], "affected_product": ["Linux", "Mac_OSX", "Windows_XP_Vista_7_8_10_Server_32_64_Bit"]}}, "app_proto": "failed", "flow": {"pkts_toserver": 22, "pkts_toclient": 27, "bytes_toserver": 2219, "bytes_toclient": 6507, "start": "2021-09-02T00:08:19.359168+0200"}}`

This is the Log. The Ruleset is a copy of the build in suricata Rules. But the Decoder is the following:

`<decoder name="pfsense-suricata">
  <prematch>Hostname->192.168.10.1 \w\w\w  \d+ \d\d:\d\d:\d\d Hostname suricata[\d+]: </prematch>
</decoder>

<decoder name="pfsense-suricata">
  <parent>pfsense-suricata</parent>
  <prematch>{"</prematch>
  <plugin_decoder offset="after_parent">JSON_Decoder</plugin_decoder>
</decoder>`

Would be great if you have an advice. I know this post is quite old, but hopefully some one will read it. Thanks
