### ISSUE TITLE
ossec-authd: SSL Error (-1)

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1564]
## Bug report

**OS**
_RHEL7_

**Wazuh version**
_3.7.0-3704_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------

ossec-authd shows twice the next error approximately every 25 seconds. However, agents can be registered.

`2018/10/04 16:20:54 ossec-authd: DEBUG: SSL Error (-1)`

**Comment by Cerv1** [comment]
Hi team, I wasn't able to reproduce this issue. 

I've tried using `gdb`, `valgrind` and debug messages and trying to break it using brute force(thousands of parallel messages, deleting client socket...) but without success.

In addition, `ossec-authd` is using only the 4 threads it needs as you can see declared [here](https://github.com/wazuh/wazuh/blob/master/src/os_auth/main-server.c#L67-#L70).
```
top - 12:49:17 up  1:22,  2 users,  load average: 0.07, 0.11, 0.12
Threads:   4 total,   0 running,   4 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.3 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  1882804 total,  1103212 free,   128584 used,   651008 buff/cache
KiB Swap:  1572860 total,  1572860 free,        0 used.  1547484 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND        
13542 root      20   0  243296   6436   3136 S  0.0  0.3   0:00.02 ossec-authd     
13543 root      20   0  243296   6436   3136 S  0.0  0.3   0:00.31 ossec-authd 
13544 root      20   0  243296   6436   3136 S  0.0  0.3   0:00.11 ossec-authd  
13545 root      20   0  243296   6436   3136 S  0.0  0.3   0:00.00 ossec-authd  
```

Regards,
Cerv1
