### ISSUE TITLE
[Bug report] | Wazuh logcollector not merging correctly <localfile> instances in the agent.conf

### ISSUE THREAD

**Issue by j0serca** [wazuh/wazuh#15663]
# Bug Report
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.9 | Logcollector | Agent | Packages/Sources | Windows Server|

## Bug Description
`logcollector` instances are not being merged correctly in the agent's configuration. When adding multiple `<localfile>` instances with the same `<location>`, for example, if the agent belongs to different groups, each one with different `<localfile>`  settings, logcollector overwrites the old ones and only leaves the last one (which, by the way, the order of the group's configs in the `agent.conf` file can't be configured).

So, for example, having an `agent.conf` file like this, where the agent belongs to Group1, Group2, and Group3 :

```
<!-- Source file: Group1/agent.conf -->
  <agent_config>
    <!-- Shared agent configuration here -->
    <localfile>
      <location>Security</location>
      <log_format>eventchannel</log_format>
      <query>
		Event/System[EventID = 5719]
      </query>
    </localfile>
  </agent_config>
<!-- Source file: Group2/agent.conf -->
  <agent_config>
  <!-- Shared agent configuration here -->
    <localfile>
      <location>Security</location>
      <log_format>eventchannel</log_format>
      <query>
		Event/System[EventID = 1102 or EventID = 4610 or EventID = 4611 or
		EventID = 4614 or EventID = 4622 or EventID = 4672 or EventID = 4723 or
		EventID = 4964 or EventID = 4697 or EventID = 4698 or EventID = 4702 or
		EventID = 4719 or EventID = 612 or EventID = 4732 or EventID = 4720 or
		EventID = 4624 or EventID = 4625 or EventID = 5140 or EventID = 4648 or
		EventID = 4661 or EventID = 4688]
      </query>
    </localfile>
    <localfile>
      <location>System</location>
      <log_format>eventchannel</log_format>
      <query>Event/System[EventID = 517 or EventID = 7045 ]</query>
    </localfile>
    <localfile>
      <location>Microsoft-Windows-TerminalServices-LocalSessionManager/Operational</location>
      <log_format>eventchannel</log_format>
      <query>Event/System[EventID = 21 or EventID = 24 or EventID = 25]</query>
    </localfile>
    <localfile>
      <location>Windows PowerShell</location>
      <log_format>eventchannel</log_format>
      <query>Event/System[EventID = 4104]</query>
    </localfile>
  </agent_config>
<!-- Source file: Group3/agent.conf -->
  <agent_config>
    <!-- Shared agent configuration here -->
    <localfile>
      <location>Security</location>
      <log_format>eventchannel</log_format>
      <query>
	    Event/System[EventID = 642]
      </query>
    </localfile>
  </agent_config>

```

This ends up being only:

```
    <localfile>
      <location>Security</location>
      <log_format>eventchannel</log_format>
      <query>
	    Event/System[EventID = 642]
      </query>
    </localfile>
```

Ignoring the other `<localfile>` instances with the same `<location>`, ending in losing visibility in a lot of, in this case, Windows events because the other queries are being ignored.
The groups are necessary as different events are needed for a different set of agents. It is known that this will work if the query is configured with all EventIDs in the same `<localfile>` instance, but this will end in the creation of a single group per agent with a different configuration, which is inconvenient.

There are no errors on the logs, even with debug, as this is technically not an error, so for Wazuh, everything is working as expected. But it is noticeable when the ignored events, because their configuration was overwritten, do not show on the Dashboard.

Thank you in advance!

**Comment by vikman90** [comment]
@j0serca This is the expected behavior of Logcollector: when a `<localfile>` stanza contains a duplicate `<location>` block, the last one overwrites the previous ones. This helps defining precedence in shared configuration groups.
