### ISSUE TITLE
Agent information not showing properly for arm64/arm32 on agent_control tool

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#15672]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-1 | Remoted | Manager/Agent | Packages | Alpine |

# Description

During testing of new alpine package support (https://github.com/wazuh/wazuh-qa/issues/3634) It was found that The agent information shown on the `agent_control` tool is not complete for agents with architectures `aaarch64` and `arm32v7`, and the fields `configuration hash` and `shared file hash` show `(null)` and `x` respectively, instead of the actual hashes.

## Current behavior

```
 # /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: af7ed050cb25
   IP address: any
   Status:     Active

   Operating system:    Linux |af7ed050cb25 |5.10.155-138.670.amzn2.aarch64 |#1 SMP Wed Nov 23 16:51:59 UTC 2022 |aarch64
   Client version:      Wazuh v4.4.0
   Configuration hash:  (null)
   Shared file hash:    x
   Last keep alive:     1670930962

   Syscheck last started at:  Tue Dec 13 11:29:19 2022
   Syscheck last ended at:    Tue Dec 13 11:29:19 2022
```

## Expected Behavior

All fields show the correct information, as it shows in other architectures

```
# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: Alpine_x86
   IP address: any
   Status:     Active

   Operating system:    Linux |22d0c9d2aa93 |5.14.0-1054-oem |#61-Ubuntu SMP Fri Oct 14 13:05:50 UTC 2022 |x86_64
   Client version:      Wazuh v4.4.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1670853680

   Syscheck last started at:  Mon Dec 12 14:01:02 2022
   Syscheck last ended at:    Mon Dec 12 14:01:02 2022
```

**Comment by chemamartinez** [comment]
This issue is already reported at https://github.com/wazuh/wazuh/issues/13754.

Thank you @MarcelKemp and @Deblintrake09 for the research!
