### ISSUE TITLE
Query Wazuh DB for complete scans

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1568]
The Syscheck decoder uses hash tables to store which agents have sent a complete scan mark, in order to enable alerts for new files. This data is also stored in the Wazuh DB.

However, this data is never queried to the Wazuh DB (persistent). Every time the manager is restarted, the data at the hash table is reset.

The Syscheck decoder should find whether there is a previous complete scan in the hash table. If no mark is in the hash table, it may query the Wazuh DB for this data.

**Comment by bah07** [comment]
Done!
