### ISSUE TITLE
RTR - shared_modules/utils saves coverage reports to a place that can not be found.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15691]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | RTR (Syscollector checks) | - | - | - |

## Description

During the run of RTR of `shared_modules` the `utils` folder builds the results on a different folder than the other items in the `shared_modules`, in consequence, important reports like test coverage can not be found by the CI scripts.

- [ ] Unify the build output folder to all elements in `shared_modules`

**Comment by jnasselle** [comment]
This is also happening in 4.4, so retargeting PR will be the best approach
