### ISSUE TITLE
Global database - OS version is not properly parsed for Alpine Linux system 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15698]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 and 4.5.0 | Wazuh-DB | Manager | Sources | Linux |

## Description

As part of the spike done to gather information about the package data on Alpine Linux systems (https://github.com/wazuh/wazuh/issues/13703) it was found that the OS version is not properly shown in the UI.

![image](https://user-images.githubusercontent.com/13010397/208131112-69ba43d0-92dd-49a1-8883-4254dd0660ab.png)

Please check 

https://github.com/wazuh/wazuh/blob/194796ea9fad3714423200e917ed172b980abd97/src/shared/version_op.c#L391

**Comment by BelenValdivia** [comment]
Reproduced in 4.4.0 version
![image](https://user-images.githubusercontent.com/26927338/216339252-1323f853-4ef2-4fcd-809a-42e7a709b81f.png)

**Comment by jnasselle** [comment]
My two cents:
Keepalive message from Wazuh Agent 4.4
```
2023/02/02 13:40:59 wazuh-agentd[14151] notify.c:204 at run_notify(): DEBUG: Sending keep alive: #!-Linux |7c74c91b02e8 |5.15.89-1-MANJARO |#1 SMP PREEMPT Wed Jan 18 20:37:11 UTC 2023 |x86_64 [Linux|linux: 0.0] - Wazuh v4.4.0 / ab73af41699f13fdd81903b5f23d8d00
4a8724b20dee0124ff9656783c490c4e merged.mg
#"_agent_ip":172.17.0.3
```
@MiguelazoDS was right about the root of the problem
