### ISSUE TITLE
OS version is not properly parsed for Alpine Linux system

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15697]
## Description

With the main goal of including the Alpine Linux system to be scanned by Vulnerability detector, a spike was done to gather information about the package data on those systems (https://github.com/wazuh/wazuh/issues/13703) it was found that the OS inventory information does not populate the `os_version` data which will affect the vulnerability scan. 

```json
{
  "os": {
    "architecture": "x86_64",
    "hostname": "alpine38.localdomain",
    "os_name": "Alpine Linux",
    "os_platform": "alpine",
    "release": "4.14.167-0-virt",
    "sysname": "Linux",
    "version": "#1-Alpine SMP Thu Jan 23 10:58:18 UTC 2020"
  }
}
```

Consider take a look at 

https://github.com/wazuh/wazuh/blob/ed299a322189f95e087c7aebc10b8cfe1e04ae5f/src/data_provider/src/sysInfoLinux.cpp#L281

**Comment by matias-braida** [comment]
Blocked due to CI/CD errors
