### ISSUE TITLE
KVDB creation failure leads to an empty database created

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15705]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3663|   https://github.com/wazuh/wazuh/issues/15318  |

# Description

When you create a kvdb using a non JSON file, it fails. Even so, it creates the kvdb (but empty) when failing when it should not

```
root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main kvdb create -p /tmp/mykvdb.txt -n mykvdb2
17:25:22.423090 cmdApiKvdb.cpp:63 ERR[66533 ] Engine "kvdb" command: "kvdbCreate" method: An error occurred while parsing the JSON file "/tmp/mykvdb.txt".
root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main kvdb list -n mykvdb2
Databases available: 1
1/1 - mykvdb2
root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main kvdb dump -n mykvdb2
KVDB "mykvdb2" content:
{"data":[]}
root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main kvdb get -n mykvdb2 -k data
15:19:19.136177 cmdApiKvdb.cpp:194 ERR[4431  ] Engine "kvdb" command: "kvdbGetValue" method: Key "data" could not be found on database "mykvdb2".
root@engine:/home/vagrant/engine/wazuh/src/engine# 
```

If the file load fails, it should not create any kvdb. Also, the log could be more precise about the issue.

Finally, it looks like it is not file extension sensitive, just its content. If you place a json inside, it will work ignoring the file extension. Detailed info can be found within the case here https://github.com/wazuh/wazuh-qa/issues/3663

# Considerations

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed at https://github.com/wazuh/wazuh/issues/16614
