### ISSUE TITLE
Syscollector - the size information on package inventory inconsistent between OS

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15703]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| [branch](https://github.com/wazuh/wazuh/tree/4.5.0) | Syscollector | Agent | Packages/Sources | Linux |

## Description 

As part of the spike done to gather information about the package data on Alpine Linux systems (https://github.com/wazuh/wazuh/issues/13703) it was found that the size information, part of the package inventory is not clear. 

- The actual size information from Ubuntu and Centos is different for the same package. 

![image](https://user-images.githubusercontent.com/13010397/208150946-6c91f59c-279f-4989-9a49-4487c1126ba3.png)
![image](https://user-images.githubusercontent.com/13010397/208150957-0a5a5ee7-7f72-4d25-a71e-c6f3029eacca.png)

According to the documentation the size is considered in bytes

https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages

## DoD 

- [x] Analyze the rest of the systems that have package inventory support.
- [x] Normalize the package size information for all systems.
- [x] If the size will be represented by another unit, reflects the change in the documentation.

**Comment by mjcr99** [comment]
## Update
**(09/07/2024)** Opened PR with the proposed solution. Reviewed every data provider for each supported system in order to verify the rest of the size values are consistently retrieved.
