### ISSUE TITLE
Multiple groups not sharing configuration files

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1570]
## Bug report

**OS**
_Ubuntu 18.04_

**Wazuh version**
_3.7.0-2704_

Bug description
----------------
I have removed the _.metadata_ file and the group folder at _'/var/ossec/var/multigroups'_ with the agent disconnected. Restarting it should have sent the ACK to the manager and recreate the folder and the .metadata file, in this case the only one recreated is the group folder.

Also, in the agent side, some configuration files are missing, showing the following error at _ossec.log_:

```
2018/10/05 08:11:02 rootcheck: ERROR: No rootcheck_files file: '/var/ossec/etc/shared/rootkit_files.txt'
2018/10/05 08:11:02 rootcheck: ERROR: No rootcheck_trojans file: '/var/ossec/etc/shared/rootkit_trojans.txt'
2018/10/05 08:11:04 rootcheck: ERROR: No unixaudit file: '/var/ossec/etc/shared/system_audit_rcl.txt'
2018/10/05 08:11:04 rootcheck: ERROR: No unixaudit file: '/var/ossec/etc/shared/system_audit_ssh.txt'

```
```
# ls /var/ossec/etc/shared/
agent.conf  ar.conf  merged.mg
```

**Comment by TJOSERAFAEL** [comment]
Hi @cristgl ,

the `agent.conf` file is the only file copied for new groups. If the agent belongs only to new groups, the agent wont have rootcheck files. This design flaw will be covered soon.

Regards.
