### ISSUE TITLE
Missing decoders when retrieving the active configuration from the API

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#15716]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-40401 | Analysisd| Manager | Packages | CentOS 8 |

For the [development of statistics](https://github.com/wazuh/wazuh/issues/13099), new integration tests were requested for these statistics and for the configuration of the daemons. However, during the development of the integration test for the active configuration, an unexpected behavior was detected:

- If a decoder has children decoders, the last child won't appear. For example, for [0165-netscreen_decoders.xml](https://github.com/wazuh/wazuh/blob/4.4/ruleset/decoders/0165-netscreen_decoders.xml):

  <details>
  <summary>API response</summary>

  ```json
               {
                   "id":363,
                   "name":"netscreenfw",
                   "children":[
                      {
                         "id":363,
                         "name":"netscreenfw",
                         "parent":"netscreenfw",
                         "order":[
                            "protocol",
                            "action",
                            "srcip",
                            "dstip",
                            "srcport",
                            "dstport"
                         ],
                         "use_own_name":"false",
                         "accumulate":"no",
                         "prematch":{
                            "pattern":"system-notification-00257\\(traffic\\): ",
                            "type":"osregex"
                         },
                         "prematch_offset":"after_parent",
                         "regex":{
                            "pattern":" proto=(\\w+) \\.+action=(\\w+) \\.+src=(\\S+) dst=(\\S+) src_port=(\\d+) dst_port=(\\d+)",
                            "type":"osregex"
                         },
                         "regex_offset":"after_prematch",
                         "type":"firewall"
                      },
                      {
                         "id":363,
                         "name":"netscreenfw",
                         "parent":"netscreenfw",
                         "order":[
                            "action",
                            "id",
                            "srcip"
                         ],
                         "use_own_name":"false",
                         "accumulate":"no",
                         "prematch":{
                            "pattern":"system-critical-\\.+ from |system-alert-\\.+ from |system-emergency-\\.+ From ",
                            "type":"osregex"
                         },
                         "prematch_offset":"after_parent",
                         "regex":{
                            "pattern":"system-(\\w+)-(\\d+): \\.+ from\\.+(\\S+)",
                            "type":"osregex"
                         },
                         "regex_offset":"after_parent",
                         "type":"syslog"
                      }
                   ],
                   "use_own_name":"false",
                   "accumulate":"no",
                   "prematch":{
                      "pattern":"^NetScreen device_id",
                      "type":"osregex"
                   },
                   "program_name":{
                      "pattern":"",
                      "type":"osmatch"
                   },
                   "type":"syslog"
                },
  ```

  </details>

 
- If a decoder has one child, the children list, will be empty. For example, for [0175-ntpd_decoders.xml](https://github.com/wazuh/wazuh/blob/455a2b914d21bf62b91bf61f68e236454a2afa71/ruleset/decoders/0175-ntpd_decoders.xml):

  <details>
  <summary>API Response</summary>

   ```json
               {
                   "id":375,
                   "name":"ntpd",
                   "children":[

                   ],
                   "use_own_name":"false",
                   "accumulate":"no",
                   "program_name":{
                      "pattern":"^ntpd",
                      "type":"osmatch"
                   },
                   "type":"syslog"
                },
  ```

</details>

- The name of the children decoders is the same as the parent's.

This behavior is not new in 4.4.0, it has been reproduced in 4.3.10.

**Comment by vicferpoy** [comment]
Closed in favor of https://github.com/wazuh/wazuh/issues/15996.

**Comment by juliamagan** [comment]
## Testing results

### Reproduce the error in 4.3.10

<details>
<summary><b>Case 1:</b> Check missing rules</summary>
<br>

Check [obtained_rules.txt](https://github.com/wazuh/wazuh/files/10966798/obtained_rules.txt)


- [ ] If a rule has children rules, one child won't appear.
- [ ] If a decoder has one child, the children list, will be empty.
- [ ] Missing rules files.


</details>


<details>
<summary><b>Case 2:</b> Check missing decoders</summary>
<br>

Check [obtained_decoders.txt](https://github.com/wazuh/wazuh/files/10966801/obtained_decoders.txt)


- [ ] If a decoder has children decoders, the last child won't appear.
- [ ] If a decoder has one child, the children list, will be empty.
- [ ] The name of the children decoders is the same as the parent's.

</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API</summary>
<br>

1. Run:

```bash
curl -w\\n -sk -H "Authorization: Bearer $(curl -u wazuh:wazuh -sk -X GET "https://localhost:55000/security/user/authenticate?raw=true")" -XGET "https://localhost:55000/manager/configuration/analysis/rules" | python3 -m json.tool | grep -Eo '\"sigid\": [0-9]+' | cut -d' ' -f2 | sort | uniq > rules.txt

grep "<rule" /var/ossec/ruleset/rules/*.xml | grep -Eo 'id="[0-9]+"' | cut -d\" -f2 | while read i
do
    grep ^$i$ rules.txt > /dev/null || echo WARNING: Missing rule $i
done
```

2. Result:

    [warnings.txt](https://github.com/wazuh/wazuh/files/10966807/warnings.txt)



</details>

### Fresh install

<details>
<summary><b>Case 1:</b> Check missing rules</summary>
<br>



</details>


<details>
<summary><b>Case 2:</b> Check missing decoders</summary>
<br>



</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API</summary>
<br>




</details>



### Upgrade from 4.3.10 to 4.5.0

<details>
<summary><b>Case 1:</b> Check missing rules</summary>
<br>



</details>


<details>
<summary><b>Case 2:</b> Check missing decoders</summary>
<br>



</details>

<details>
<summary><b>Case 3:</b> Check that all rules in XML files are reported by the API</summary>
<br>




</details>
