### ISSUE TITLE
Syntax error consulting group info

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1571]
## Bug report

**Wazuh version**
_3.7.0-3704_

Bug description
----------------

The group "group31)" with just one parenthesis can be created and can contain an agent, but it can't be consulted in the database with _agent_groups_ CLI:

```
# /var/ossec/bin/agent_groups -a -g "group31)"
Do you want to create the group 'group31)'? [y/N]: y
Group 'group31)' created.

# /var/ossec/bin/agent_groups -a -i 001 -g "group31)"
Do you want to add the group 'group31)' to the agent '001'? [y/N]: y
Group 'group31)' added to agent '001'.

# /var/ossec/bin/agent_groups -l -g "group31)"
Error 2003: Error in database request: near ")": syntax error
```

**Comment by mgmacias95** [comment]
Hello @TJOSERAFAEL and @cristgl,

The error doesn't come from the regex defined in utils.py:633. The error comes from the use of `)`. Let me explain why: In SQL queries, `(` and `)` are used to define operator preference and therefore, a syntax error will be thrown if an `)` is found without an opening one.

I think the best solution is to restrict `(` and `)` from group names.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello,

Support for `(` and `)` has finally been removed in #1586.

Best regards,
Marta
