### ISSUE TITLE
osdquery - init.cpp:506] osqueryd Pidfile check failed: Pidfile::Error::Busy

### ISSUE THREAD

**Issue by y0d4a** [wazuh/wazuh#15728]
Hi,

I got stuck with setup osquery on ubuntu.
When i install osquery and enter your example config, without wazuh he is working fine.
When i restart wazuh i am getting error in wazuh: `init.cpp:506] osqueryd Pidfile check failed: Pidfile::Error::Busy` (osquery crashed).
After that, only way is to remove /var/osquery/osquery.db/LOCK and restart osquery to work, but after restart wazuh, he crashed again...  

Andreas M. from slack channel found https://github.com/osquery/osquery/issues/7796 but i am not sure is it related to this case...

What can i do? 
this is out of the box setup, so i think you can replicate this easy...

**Comment by y0d4a** [comment]
and that is only happening on linux, macos working fine

**Comment by mamad-roh** [comment]
I had the same problem. I disabled the osquery service and let the wazuh service run itself. This solved my problem.

`systemctl stop osqueryd.service`
`systemctl disable osqueryd.service`
`systemctl restart wazuh-agent.service`
