### ISSUE TITLE
Include Macports applications in the syscollector (inventory) and vulnerability detector

### ISSUE THREAD

**Issue by fgont** [wazuh/wazuh#15726]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10-1 | syscollector | Manager/agent | Packages | Mac OS  |

I'd like that syscollector be able to learn Macports-pased packages (https://www.macports.org/), and that the package list/versions be employed by the vulnerability detector.

I blieve the issue is similar to the current issues with "brew"?

**Comment by MiguelazoDS** [comment]
# Overview MacPorts package manager

## Environment 

Macos Catalina 10.15.7

## MacPorts package data 
### Database structure

The installed packages (ports in MacPorts slang) are stored in an SQLite database in the following path 

![2022-12-21_16-57](https://user-images.githubusercontent.com/13010397/209000068-a991e8ef-9e71-453b-896c-e0c9033d5791.png)

#### As a quick test, the following packages were installed 

- Neovim
- Ranger 
- Htop

#### The database tables are: 

![image](https://user-images.githubusercontent.com/13010397/209002129-58d801e6-a304-4fa5-941e-0f016e82fbd3.png)

Where the most important is the `ports` table.

The information for those 3 packages is shown below: 

<details>
<summary> Click to expand </summary>

![image](https://user-images.githubusercontent.com/13010397/209002767-c63ec00b-7573-4ee8-a6c1-6e17d43d8c09.png)

</details>

### Syscollector package fields.
<details>
<summary> Click to expand </summary>

name
version
vendor
install_time
location
architecture
groups
description
size
priority
multiarch
source
format
checksum
item_id
db_status_field_dm

</details>

### Translation

<details>
<summary>Click to expand</summary>

|Syscollector package field|ports table attribute|
|-|-|
|name|name|
|version|version|
|vendor|*|
|install_time|date|
|location|location|
|architecture|archs|
|groups|*|
|description|*|
|size|*|
|priority|*|
|multiarch|*|
|source|*|
|format|*|
|checksum|-|
|item_id|-|
|db_status_field_dm|-|

</details>

**Note: The fields represented by "-" are for internal use.**
**Note: format field can be hardcoded as "macports" or similar.**
**Note: There's no vendor information so it is needed to consider the approach followed here https://github.com/wazuh/wazuh/issues/15199**
**Note: TODO: consider other sources where the missing info can be obtained.**

### Table schemas

#### ports table 

<details>
<summary>Click to expand</summary>

```
0|id|INTEGER|0||1
1|name|TEXT|0||0
2|portfile|TEXT|0||0
3|location|TEXT|0||0
4|epoch|INTEGER|0||0
5|version|TEXT|0||0
6|revision|INTEGER|0||0
7|variants|TEXT|0||0
8|requested_variants|TEXT|0||0
9|state|TEXT|0||0
10|date|DATETIME|0||0
11|installtype|TEXT|0||0
12|archs|TEXT|0||0
13|requested|INTEGER|0||0
14|os_platform|TEXT|0||0
15|os_major|INTEGER|0||0
16|cxx_stdlib|TEXT|0||0
17|cxx_stdlib_overridden|INTEGER|0||0
```

</details>

#### sys_programs table 

<details>
<summary>Click to expand</summary>

```
0|scan_id|INTEGER|0||1
1|scan_time|TEXT|0||0
2|format|TEXT|1||0
3|name|TEXT|0||2
4|priority|TEXT|0||0
5|section|TEXT|0||0
6|size|INTEGER|0||0
7|vendor|TEXT|0||0
8|install_time|TEXT|0||0
9|version|TEXT|0||3
10|architecture|TEXT|0||4
11|multiarch|TEXT|0||0
12|source|TEXT|0||0
13|description|TEXT|0||0
14|location|TEXT|0||0
15|triaged|INTEGER(1)|0||0
16|cpe|TEXT|0||0
17|msu_name|TEXT|0||0
18|checksum|TEXT|1||0
19|item_id|TEXT|0||0
```

</details>

#### Attributes data types 

||ports|sys_programs|
|-|-|-|
|name/name|TEXT|TEXT|
|version/version|TEXT|TEXT|
|date/install_time|DATETIME|TEXT|
|location/location|TEXT|TEXT|
|archs/architecture|TEXT|TEXT|

**Note: It must be checked that archs can have multiple values and whether or not that affects the implementation.**
**Note: DATETIME is a numeric data type (https://www.sqlite.org/datatype3.html).**

#### TBD 

The direct manipulation to the database may compromise the integrity, the MacPorts project exposes an API that performs the lock and unlock of the database.

More information here: https://guide.macports.org/

**Comment by Dwordcito** [comment]
The implementation will be covered by:

https://github.com/wazuh/wazuh/issues/15877
