### ISSUE TITLE
Get ossec-agentd.state information from API

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1572]
Hi team!

It would be nice to get information about the file `ossec-agentd.state` using the API. 

This is actually implemented for `ossec-analysisd` and `ossec-remoted` and the API request are the following:

```
curl -k -X GET "https://127.0.0.1:55000/manager/stats/remoted?pretty"
curl -k -X GET "https://127.0.0.1:55000/manager/stats/analysisd?pretty"
```

Regards,
Cerv1

**Comment by vikman90** [comment]
Fixed by #7239.
