### ISSUE TITLE
vulnerability detector  for linux redhat/ubuntu 

### ISSUE THREAD

**Issue by themeswordpress** [wazuh/wazuh#15731]
Dears,

Hope all is well.

How you can detect the vuln for the Linux package for example for RedHat / ubuntu ...etc 

how to can read the oval and parse it, in addition, what is the package format you retrieve from the RedHat system (i.e rpm -a ??)

do you have any python code that can do this? 

and in your code can you share with me the exact code that is doing that? 

and if you have a high-level explanation

**Comment by themeswordpress** [comment]
ت

**Comment by GabrielEValenzuela** [comment]
Hello !

Let me give you a brief summary of how Vulnerability Detector works 🙂 

The module functions using Wazuh’s native integration with external vulnerability feeds indexed by Canonical, Debian, Red Hat, Arch Linux, Amazon Linux Advisories Security (ALAS), Microsoft, and the National Vulnerability Database (NVD).

To detect vulnerabilities, Wazuh agents collect a list of installed applications from monitored endpoints and send it periodically to the Wazuh server. Local SQLite databases in the Wazuh server store this list. Also, the Wazuh server builds a global vulnerability database from publicly available CVE repositories. It uses this database to cross-correlate this information with the application inventory data of the agent. The database location is ```/var/ossec/queue/vulnerabilities/cve.db```, and users can query the database using ```SQLite``` and collects the packages through [Syscollector](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html)

The Vulnerability Detector generates alerts during the baseline scan for every detected vulnerability. You can see this workflow in the diagram below.
![image](https://user-images.githubusercontent.com/27935340/208887335-def5324a-a117-403a-98d0-f7e830200bb6.png)


The Vulnerability Detector also generates alerts when it detects new vulnerabilities or when users fix identified vulnerabilities.
![image](https://user-images.githubusercontent.com/27935340/208887350-04dd0a9f-6ca2-4bdc-b180-bc6bea97bfda.png)

When you have to configure the vulnerability detector, the Wazuh server has this module disabled by default when you install it, while the Wazuh agent has Syscollector enabled by default. The following steps show how to configure the vulnerability detection components:

1. Add the following block of settings to your [shared agent configuration file](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html). You can find the file at /var/ossec/etc/shared/default/agent.conf on the Wazuh server. You can also configure these options in each agent ossec.conf configuration file:

```xlm
<wodle name="syscollector">
   <disabled>no</disabled>
   <interval>1h</interval>
   <os>yes</os>
   <packages>yes</packages>
   <hotfixes>yes</hotfixes>
</wodle>
```
2. Enable the Vulnerability Detector module in the Wazuh server [configuration file](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html) at ```/var/ossec/etc/ossec.conf```. Set the value for the ```<enabled>``` tag to yes for the Vulnerability Detector module and every operating system you intend to scan. We have added a sample below:

```xml
<vulnerability-detector>
   <enabled>yes</enabled>
   <interval>5m</interval>
   <min_full_scan_interval>6h</min_full_scan_interval>
   <run_on_start>yes</run_on_start>

   <!-- Ubuntu OS vulnerabilities -->
   <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <update_interval>1h</update_interval>
   </provider>

   <!-- Debian OS vulnerabilities -->
   <provider name="debian">
      <enabled>yes</enabled>
      <os>buster</os>
      <os>bullseye</os>
      <update_interval>1h</update_interval>
   </provider>

   <!-- RedHat OS vulnerabilities -->
   <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
   </provider>

   <!-- Amazon Linux OS vulnerabilities -->
   <provider name="alas">
      <enabled>yes</enabled>
      <os>amazon-linux</os>
      <os>amazon-linux-2</os>
      <update_interval>1h</update_interval>
   </provider>

   <!-- Arch OS vulnerabilities -->
   <provider name="arch">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
   </provider>

   <!-- Windows OS vulnerabilities -->
   <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
   </provider>

   <!-- Aggregate vulnerabilities -->
   <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
   </provider>
</vulnerability-detector>
```
3. Restart the manager to apply the changes.

About the oval files, if the Wazuh server isn't directly connected to the Internet, it's still possible to keep the vulnerability feeds updated. You can fetch the database files from your local environment or network. The steps include downloading the specific vulnerability files and configuring the Wazuh server to locate them. You can find feeds in a custom location compressed in gz or bzip2 or decompressed in XML or JSON, depending on the original format of the feed. The configuration examples in this section are all set in the Wazuh server ```/var/ossec/etc/ossec.conf``` file. You can find all the OVALs [here](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html) and the operating systems the Vulnerability Detector currently supports and the provider(s) needed for each distribution [here](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix)

This module is defined [here](https://github.com/wazuh/wazuh/tree/803f3a3160fd5e59d3e956496b65637f9fb606a2/src/wazuh_modules/vulnerability_detector) and most of the functions I have told you about are defined here  [here](https://github.com/wazuh/wazuh/blob/803f3a3160fd5e59d3e956496b65637f9fb606a2/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c)

You can find more information in our documentation, [Vulnerability Detector](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html) and [Syscollector](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html) 

If you need anything more, please don't dub to ask. We're here to help 🙂
Have a nice day!
