### ISSUE TITLE
Adapt `GET /sca/{agent_id}/checks/{policy_id}` to changes in `status` and `result` response fields

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#15738]
## Description

Due to changes in https://github.com/wazuh/wazuh/issues/15729, we need to adapt the API endpoint `GET /sca/{agent_id}/checks/{policy_id}` to the changes suffered in the `status` and `result` fields. 

The `status` field is removed from the response, and the `not applicable` value will be included as a possible `result`.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by vicferpoy** [comment]
# Issue update

| Development branch |
| - |
| [feature/15738-sca-response-fields](https://github.com/wazuh/wazuh/tree/feature/15738-sca-response-fields) |

Changes are already implemented in the development branch. Some manual tests were performed modifying the database with the new value, but this issue will remain blocked until the core changes are fully implemented in the main development branch.
