### ISSUE TITLE
Regex problem when creating groups

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1579]
Hi team

Currently the characters supported are the following: `a-z, A-Z, 0-9, -.=!()`.

Some examples:

```
# agent_groups -q -a -g .
Do you want to create the group '.'? [y/N]: y
Group '.' created.

# agent_groups -q -a -g --
Do you want to create the group '--'? [y/N]: y
Group '--' created.
```

But when we try to add a group with multiple `.` in the group name we get the following error:
```
# agent_groups -q -a -g a.b.c
Error 1722: Incorrect format for group_id. Characters supported  a-z, A-Z, 0-9, -.=!() Max length is 255.

# agent_groups -q -a -g "test."
Error 1722: Incorrect format for group_id. Characters supported  a-z, A-Z, 0-9, -.=!() Max length is 255.
```

When we try to use `.`  along others characteres it throws `Error 1722`.

**Comment by mgmacias95** [comment]
Hello @Cerv1,

The regex used to validate group names has been fixed and improved in #1586.

Best regards,
Marta
