### ISSUE TITLE
Wazuh wrapper for OpenSCAP false values 

### ISSUE THREAD

**Issue by tirili** [wazuh/wazuh#158]
The results of an OpenSCAP scan seems to be wrong, when imported into Wazuh.
All the the entrys with the result **passed** appear as result **failed** in  Kibana.
A little change in the **wazuh/wodles/oscap/oscap.py** fixed that problem.
Is this correct  ?

-- oscap.py    2017-07-19 13:17:27.570477283 +0200
+++ oscap.py.bak        2017-04-22 16:40:17.000000000 +0200
@@ -189,9 +189,9 @@
                 if any(x in line for x in class1):
                     if 'result: "false"' in line:
                         total_KO += 1
-                        new_line = new_line.replace('result: "false"', 'result: "pass"')
+                        new_line = new_line.replace('result: "false"', 'result: "fail"')
                     elif 'result: "true"' in line:
-                        new_line = new_line.replace('result: "true"', 'result: "fail"')
+                        new_line = new_line.replace('result: "true"', 'result: "pass"')
                 elif any(x in line for x in class2):
                     if 'result: "true"' in line:
                         total_KO += 1

**Comment by jesuslinares** [comment]
Hi @tirili 

check out the [full code](https://github.com/wazuh/wazuh/blob/master/wodles/oscap/oscap.py#L186):

```
# OVAL SCAN

class1 = ['class: "compliance"', 'class: "patch"', 'class: "inventory"']
class2 = ['class: "vulnerability"']

if any(x in line for x in class1):
	if 'result: "false"' in line:
		total_KO += 1
		new_line = new_line.replace('result: "false"', 'result: "fail"')
	elif 'result: "true"' in line:
		new_line = new_line.replace('result: "true"', 'result: "pass"')
elif any(x in line for x in class2):
	if 'result: "true"' in line:
		total_KO += 1
		new_line = new_line.replace('result: "true"', 'result: "fail"')
	elif 'result: "false"' in line:
		new_line = new_line.replace('result: "false"', 'result: "pass"')
```
I think you want to change the class1:
```
if any(x in line for x in class1):
	if 'result: "false"' in line:
		total_KO += 1
		new_line = new_line.replace('result: "false"', 'result: "pass"')
	elif 'result: "true"' in line:
		new_line = new_line.replace('result: "true"', 'result: "fail"')
```
In OVAL scans, when a check has the type _compliance_, _patch_ or _inventory_, the "false" result means "fail". But if it is a _vulnerability_ check, the "false" result means "pass".

Please, provide an example if you think this is not correct.

Thanks.

**Comment by tirili** [comment]
I made some Screenshots. Screenshots 1 and 2 shows the correct report made directly with the OpenSCAP-Scanner. Nearly everything is green except 12 red ones. This is totally correct.

Without changing the python script every green CVE was shown as a fail (screenshot 3). After changing the script only the correct 12 CVEs from the report are shown.

![1_openscap_report](https://user-images.githubusercontent.com/555159/28376256-fd7f4782-6ca9-11e7-808d-c648045e106b.png)
![2_openscap_report png](https://user-images.githubusercontent.com/555159/28376254-fd76bc84-6ca9-11e7-864a-9581da1dc023.png)
![3_kibanabeforecodechange](https://user-images.githubusercontent.com/555159/28376257-fd816e22-6ca9-11e7-98da-2cdc2512d2ab.png)
![4_kibanaaftercodechange](https://user-images.githubusercontent.com/555159/28376255-fd7f00ec-6ca9-11e7-8a58-8b7d061d4790.png)

**Comment by jesuslinares** [comment]
You are totally right. Checking the [technical specification](https://books.google.es/books?id=gpA5TiMGiSgC&lpg=SA4-PA8&ots=7cvqps62BH):

![oscap-result](https://user-images.githubusercontent.com/1523318/28378355-2a46d9dc-6cb0-11e7-8842-48fdc3a25ba0.png)

So, it looks like a typo in the definition of class1 and class2. We will fix it as soon as possible.

Thank you so much for the feedback.

**Comment by vikman90** [comment]
Hi @tirili and @jesuslinares,

we've fixed this issue just now: https://github.com/wazuh/wazuh/commit/06ab8f58504ce8c1ae2a85ed8e4b0daaba794cc9

Thank you very much for reporting!
Best regards.
