### ISSUE TITLE
Error sending sendsync in Wazuh cluster

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#15802]
|Wazuh version|Component|
|---|---|
| 4.5.0 | Wazuh server cluster |

## Description

An error has been found in a distributed installation of Wazuh. Specifically, the error is reported from several tests of automated tests while executing the distributed installation tests.

```
 @pytest.mark.wazuh_worker

def test_check_cluster_log_errors():
         found_error = False
         with open('/var/ossec/logs/cluster.log', 'r') as f:

             for line in f.readlines():
                 if 'ERROR' in line:
                     found_error = True
                     if get_wazuh_version() == 'v4.5.0':
                         if 'Could not connect to master' in line or 'Worker node is not connected to master' in line or 'Connection reset by peer' in line:
                             found_error = False

                         else:
                           break

       assert found_error == False, line
 E       AssertionError: 2022/12/27 08:28:59 ERROR: [Worker redhat_8-wazuh] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
```

This error in automated tests is produced by the output generated in the `cluster.log` file. This log file snippet shows that the machine fails to connect to its master node but reconnects after some retries.

```
2022/12/21 12:40:22 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/12/21 12:40:22 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/12/21 12:40:32 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
2022/12/21 12:40:42 INFO: [Worker redhat_8-wazuh] [Main] Successfully connected to master.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity check] Starting.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity check] Finished in 0.071s. Sync required.
2022/12/21 12:40:51 INFO: [Worker redhat_8-wazuh] [Integrity sync] Starting.
```

Some pipelines have been executed and it seems this behavior is partially random as some machines fail the test, but Redhat 8 always fails. This unexpected behavior has to be investigated and then, figure out why some machines can not connect on the first try to their master node.

## Steps to reproduce

As commented, this error is produced on a distributed installation of every supported system of the Wazuh cluster. Redhat 8 always fails in this process.
Link to the unattended distributed test: https://ci.wazuh.info/job/Test_unattended_distributed/322

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
After taking a closer look at the 4.6.0 RC1 workload test logs, I see that this error seems much more frequent in 4.6.0 than in 4.5.0:
```
$ grep "Error 3020 - Timeout sending request" 4_6_0_rc1/artifacts/worker_2/logs/cluster.log | wc -l
3637
```

Also, while trying to reproduce the problem in my local env, I found this error in the `cluster.log`:
```
2023/10/11 15:18:37 DEBUG: [Worker worker1] [Main] Command received: 'b'syn_m_c_ok''
2023/10/11 15:18:37 INFO: [Worker worker1] [Integrity check] Finished in 0.011s. Sync not required.
2023/10/11 15:18:37 ERROR: [Worker worker1] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/cluster/common.py", line 45, in read
    await self.received_response.wait()
  File "/var/ossec/framework/python/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/cluster/common.py", line 531, in send_request
    response_data = await asyncio.wait_for(response.read(),
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/cluster/common.py", line 748, in forward_sendsync_response
    await self.get_manager().local_server.clients[client].send_request(b'ok', self.in_str[string_id].payload)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/cluster/common.py", line 537, in send_request
    raise exception.WazuhClusterError(3020, extra_message=command.decode())
wazuh.core.exception.WazuhClusterError: Error 3020 - Timeout sending request: ok
2023/10/11 15:18:38 DEBUG: [Worker worker1] [Agent-info sync] Permission to synchronize granted.
2023/10/11 15:18:38 INFO: [Worker worker1] [Agent-info sync] Starting.
```

What I did was:
1. Created an env with 1 master, 1 worker and  5 agents.
2. Agents connected to the worker, some `Error 3020 - Timeout sending request` appeared.
3. Deleted all the agents and waited until they re-registered. The error above showed up.

**Comment by Selutario** [comment]
## Update

After reproducing the issue, this is what is happening:

1. WORKER receives `sendsync` from `remoted`:
   ```
   2023/10/11 16:09:11 DEBUG: [Local 622820] [Main] Connection received in local server.
   2023/10/11 16:09:11 DEBUG2: [Local 622820] [Main] Command received: b'sendsync'
   ```
2. MASTER receives `sendsync` from worker:
   ```
   2023/10/11 16:09:11 DEBUG: [Worker worker1] [Main] Command received: b'sendsync'
   2023/10/11 16:09:11 DEBUG: [Worker worker1] [SendSync] Received request: b'worker1*622820    {"daemon_name":"authd","message":{"arguments":{"name":"e4a1a4f23f53","ip":"any"},"function":"add"}}'
   2023/10/11 16:09:11 DEBUG: [Master] [SendSync] Receiving SendSync request (authd) from worker1 (622820)
   ```
3. WORKER receives response from master and the local client (remoted) disconnects:
   ```
   2023/10/11 16:09:11 DEBUG: [Worker worker1] [Main] Command received: 'b'new_str''
   2023/10/11 16:09:11 DEBUG: [Worker worker1] [Main] Command received: 'b'str_upd''
   2023/10/11 16:09:11 DEBUG: [Worker worker1] [Main] Command received: 'b'sendsyn_res''
   2023/10/11 16:09:11 DEBUG: [Local 622820] [Main] Disconnected 622820.
   ```
4. WORKER tries to send something else to the client, which is no longer connected. After waiting, an exception is raised:
   ```
   2023/10/11 16:09:23 ERROR: [Worker worker1] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
   ```

The full traceback is printed because the parameter `exc_info=False` is not included in `logger.error()`. 

The bug is probably not new. However, previously `send_request` returned a string when a timeout occurred, so nothing was printed in the `cluster.log` here:
https://github.com/wazuh/wazuh/blob/2c05acb064a71c071c70f369b3b2c81fdeacd457/framework/wazuh/core/cluster/common.py#L745-L750

Now in 4.6.0, an exception is raised instead. This makes the error unhidden, although aesthetically it looks very bad. It is necessary to determine why the cluster is trying to send a second response (if this theory is confirmed) to remoted, and fix it.
