### ISSUE TITLE
Decoder <regex> doesn't work correctly with snort logs.

### ISSUE THREAD

**Issue by maan-alhajjam** [wazuh/wazuh#15813]
Hi Everyone,
I was working on a custom decoder to detect snort logs and I'm not sure where I have the issue.

The monitored command generates the following output:
11/11/22-06:34:12.245678 ,122,12,1,"(http_inspect) PROTOCOL-OTHER HTTP server response before client request ",TCP,19.168.1.1,80,17.1.1.222,2345,1234,Unknown Traffic,3, alert,Allow

So I created the following decoder to capture 12 groups (Date, Time, sup_msg, Protocol, ip_src, port_src, ip_dest, port_dest, msg, alert_Level, type, Logs_stat) with the regex:

<decoder name="Decoder-Test">
    <prematch>(^\S+)-(\w{1,2}:\w{1,2}:\w{1,2})\.\w{6} ,\S+,("\S+ \S+ \S+ \S+ \S+ \S+ \S+ \S+ "),(\w+),(\d+.\d+.\d+.\d+),(\d+),(\d+.\d+.\d+.\d+),(\d+),\d+,(\w+ \w+),(\d+),(\w+),(\w+)</prematch>
</decoder>

<decoder name="Decoder-Test1">
    <parent>Decoder-Test</parent>
    <regex ofset="after_prematch">(^\S+)-(\w{1,2}:\w{1,2}:\w{1,2})\.\w{6} ,\S+,("\S+ \S+ \S+ \S+ \S+ \S+ \S+ \S+ "),(\w+),(\d+.\d+.\d+.\d+),(\d+),(\d+.\d+.\d+.\d+),(\d+),\d+,(\w+ \w+),(\d+),(\w+),(\w+)</regex>

<order>Date, Time, sup_msg, Protocol, ip_src, port_src, ip_dest, port_dest, msg, alert_Level, type, Logs_stat</order>
</decoder>

And I have tested it using https://regex101.com/ and the logic is working fin there

I'm using Wazuh Version:4.3.5

**Comment by maan-alhajjam** [comment]
And this is the Wazuh test result.
**Phase 1: Completed pre-decoding.
	full event:11/11/22-06:34:12.245678 ,122,12,1,"(http_inspect) PROTOCOL-OTHER HTTP server response before client request ",TCP,19.168.1.1,80,17.1.1.222,2345,1234,Unknown Traffic,3, alert,Allow

**Phase 2: Completed decoding.
	name: 'Decoder_Test'

**Comment by MiguelazoDS** [comment]
Hi @maan-alhajjam, 

I had to add an extra "\s+" to match a space character to your regular expression to make it work. Besides that, I was able to get something using your approach 

![image](https://user-images.githubusercontent.com/13010397/210251177-84d95d5d-c203-4d2e-9ad9-06d4c89b7895.png)

The issue is that I have to use "http_inspect" as a prematch, and I think that is not accurate. 

What I suggest is to use the `out_format` option in your localfile configuration to encapsulate the log that has not a syslog format. 

More details can be found here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=out_format#out-format

As a quick example, you can set something like this: 

`<out_format>$(timestamp) $(hostname) snort: $(log)</out_format>`

Where $(log) is the full log you shared and then you can use `<program_name>snort</program_name>` in your decoder.

**Comment by maan-alhajjam** [comment]
Hi @MiguelazoDS 
Thank you so much for your response.
my apologies for my lack of knowledge because I'm new to Wazuh.
but I also tried adding the "\s+" as a space in the regex but this is what comes when I test it.

![image](https://user-images.githubusercontent.com/121604042/210370071-9459b8bd-8724-478e-bd58-de20e14c7c3e.png)

and this is the decoder :



<decoder name="Decoder-Test">
    <program_name>Decoder-Test</program_name>
</decoder>

<decoder name="Decoder-Test1">
    <parent>Decoder-Test</parent>
     <regex>(^\S+)-(\w{1,2}:\w{1,2}:\w{1,2}).\w{6}\s+,\S+,("\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+"),(\w+),(\d+.\d+.\d+.\d+),(\d+),(\d+.\d+.\d+.\d+),(\d+),\d+,(\w+\s+\w+),(\d+),(\w+),(\w+)</regex>
<order>Date, Time, sup_msg, Protocol, ip_src, port_src, ip_dest, port_dest, msg, alert_Level, type, Logs_stat</order>
</decoder>

**Comment by MiguelazoDS** [comment]
Hi @maan-alhajjam, 

The last regular expression you shared is not working for me. The "\s+" I added was to match the space before "alert" word. 

![image](https://user-images.githubusercontent.com/13010397/210380068-29ba1f2a-ef04-43b2-baaf-4e3b549db3ff.png)

How does your `local_decoder.xml` file looks like?

**Comment by maan-alhajjam** [comment]
Hi @MiguelazoDS 

Do you mean this file?
![image](https://user-images.githubusercontent.com/121604042/210518315-baf43a4b-06c0-4649-a0c2-9081ff7fd520.png)

and the rule is working fine now but the decoder now can only read the decoder name and that's it :)
![image](https://user-images.githubusercontent.com/121604042/210518810-17a773f0-f4ed-4682-a9ca-aa59b3bed7c0.png)

Thank you so much for your time, I really appreciate it.

**Comment by MiguelazoDS** [comment]
Hi @maan-alhajjam, 

Not sure about that `offset="after_parent"` attribute in your decoder, since we don't have any parent decoder. I would use something like this 

```xml
<decoder name="snort_decoder">
    <prematch>Allow</prematch>
    <regex type="pcre2">(^\S+)-(\w{1,2}:\w{1,2}:\w{1,2})\.\w{6} ,\S+,("\S+ \S+ \S+ \S+ \S+ \S+ \S+ \S+ "),(\w+),(\d+.\d+.\d+.\d+),(\d+),(\d+.\d+.\d+.\d+),(\d+),\d+,(\w+ \w+),(\d+),\s+(\w+),(\w+)</regex>
    <order>Date,Time,sup_msg,Protocol,ip_src,port_src,ip_dest,port_dest,msg,alert_Level,type,Logs_stat</order>
</decoder>
```
