### ISSUE TITLE
Who Data does not work

### ISSUE THREAD

**Issue by brantcolemanthis** [wazuh/wazuh#1582]
OS
Ubuntu16

Wazuh version
3.6.1

Install type
manager

Install method
packages

> "Integrity checksum changed for: '/etc/hosts.allow'\nSize changed from '414' to '416'\nOld md5sum was: 'd4099925caa1241d739b76f63ea08c58'\nNew md5sum is : 'fd6166325ccde88144f914f5f567048b'\nOld sha1sum was: '79a761eafb242c7bb19c1fb756a93e93021191fa'\nNew sha1sum is : '831ec503278f2f90a654a3651bb43269d2619e28'\nOld sha256sum was: '697772fa24883a42d6ac52b6efeee6f19a1062c1ee3fd9bddf256767842386a7'\nNew sha256sum is : '71b1687bfd2c97021423ebc3c9b953a5fde8272aa1951d459ac1583b2b53c5a7'\n","syscheck":{"path":"/etc/hosts.allow","size_before":"414","size_after":"416","perm_after":"100644","uid_after":"0","gid_after":"0","md5_before":"d4099925caa1241d739b76f63ea08c58","md5_after":"fd6166325ccde88144f914f5f567048b","sha1_before":"79a761eafb242c7bb19c1fb756a93e93021191fa","sha1_after":"831ec503278f2f90a654a3651bb43269d2619e28","sha256_before":"697772fa24883a42d6ac52b6efeee6f19a1062c1ee3fd9bddf256767842386a7","sha256_after":"71b1687bfd2c97021423ebc3c9b953a5fde8272aa1951d459ac1583b2b53c5a7","uname_after":"root","gname_after":"root","mtime_before":"2018-10-06T10:38:47","mtime_after":"2018-10-06T10:40:25","inode_after":2621930,"event":"modified"},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}

Hi Guys, who data does not work, after apply changes in ossec.conf - i restart the wazuh, i check that rules apply in auditd and make some change in  some file in scanning directory, after i get allert from wazuh, and those nothing from auditd information. How to force it work?

**Comment by cristgl** [comment]
Hello @brantcolemanthis,

Whodata works with auditd system go get the information it needs. Install audit with the following command:

```
apt install auditd
```

And after configuring whodata at your `ossec.conf` file, restart Wazuh to apply the changes and later you will get some alerts when modifying a monitored file. If this doesn't solve your problem or you have any question don't hesitate to contact us again.

Kind regards

**Comment by brantcolemanthis** [comment]
i did it earler, and auditd work, any idea?

**Comment by cristgl** [comment]
Hi @brantcolemanthis,

Can you paste your configuration of syscheck at the `ossec.conf` file? Also check your `ossec.log` file to verify that there are no errors reported.

Kind regards

**Comment by brantcolemanthis** [comment]
2018/10/15 09:48:36 ossec-syscheckd: INFO: No socket found at '/var/ossec/queue/ossec/audit'. Restarting Auditd service.
2018/10/15 09:48:37 ossec-syscheckd: ERROR: Cannot connect to socket /var/ossec/queue/ossec/audit
2018/10/15 09:48:37 ossec-syscheckd: WARNING: Audit events reader thread not started.

**Comment by brantcolemanthis** [comment]
> Hi @brantcolemanthis,
> 
> Can you paste your configuration of syscheck at the `ossec.conf` file? Also check your `ossec.log` file to verify that there are no errors reported.
> 
> Kind regards

2018/10/15 09:59:03 ossec-syscheckd: INFO: No socket found at '/var/ossec/queue/ossec/audit'. Restarting Auditd service.
2018/10/15 09:59:03 ossec-syscheckd: ERROR: Cannot connect to socket /var/ossec/queue/ossec/audit
2018/10/15 09:59:03 ossec-syscheckd: WARNING: Audit events reader thread not started.
that's all.
Ossec.conf: 

...
 <directories check_all="yes" whodata="yes">/ttts</directories>
...
when i do: 
# auditctl -l | grep wazuh_fim
i got: 
-w /ttts/ -p wa -k wazuh_fim
any idea?

**Comment by cristgl** [comment]
Hi @brantcolemanthis,
The configuration seems ok, have you checked that `audit` service is running?
```
service auditd status
```
After enabling it, please restart Wazuh. If this doesn't solve your problem, ask us again.

Kind regards

**Comment by brantcolemanthis** [comment]
already restart, all work, nothing to help

**Comment by brantcolemanthis** [comment]
> Hi @brantcolemanthis,
> The configuration seems ok, have you checked that `audit` service is running?
> 
> ```
> service auditd status
> ```
> After enabling it, please restart Wazuh. If this doesn't solve your problem, ask us again.
> 
> Kind regards

already restart, all work, nothing to help

**Comment by cristgl** [comment]
Hi @brantcolemanthis,

Do you have SELinux installed and enforcing? Maybe this is not allowing the creation of the `audit` socket. 

Regards

**Comment by brantcolemanthis** [comment]
> Hi @brantcolemanthis,
> 
> Do you have SELinux installed and enforcing? Maybe this is not allowing the creation of the `audit` socket.
> 
> Regards

Hi! SELinux is not installed.
I tried something - i made socket mannualy, but this error everything else appears:
ERROR: Cannot connect to socket /var/ossec/queue/ossec/audit

**Comment by cristgl** [comment]
Hi @brantcolemanthis, try doing the following:
```
auditctl -D
```

And then restart Wazuh. The problem comes when `syscheck` gets killed, somehow it does not remove the `audit` rule, so when it gets restarted it can't rewrite it again, we are working on this, it will be fixed for the new Wazuh version. Thank you very much for reporting this.

Best regards

**Comment by cristgl** [comment]
Hello @brantcolemanthis,

Did the last answer helped you and solved the problem? Let us know if you had any problem to try helping you.

Best regards

**Comment by brantcolemanthis** [comment]
When i do 
`# auditctl -D`
that print:
`No rules`
and then restart wazuh:
`service wazuh-agent restart`
and then in ossec.log same error:
```
2018/10/30 11:28:08 ossec-syscheckd: INFO: No socket found at '/var/ossec/queue/ossec/audit'. Restarting Auditd service.
2018/10/30 11:28:08 ossec-syscheckd: ERROR: Cannot connect to socket /var/ossec/queue/ossec/audit
2018/10/30 11:28:08 ossec-syscheckd: WARNING: Audit events reader thread not started.
```
It's not help((( please help me

> Hello @brantcolemanthis,
> 
> Did the last answer helped you and solved the problem? Let us know if you had any problem to try helping you.
> 
> Best regards

**Comment by kow777** [comment]
Check the owner/group for /var/ossec/queue/ossec/audit. I needed to manually set it to ossec:ossec.

**Comment by brantcolemanthis** [comment]
> Check the owner/group for /var/ossec/queue/ossec/audit. I needed to manually set it to ossec:ossec.

ossec:ossec, not worked

**Comment by cristgl** [comment]
Hello,

Did you manage to see whodata working? If not, tell me so I can help you with any problem you may have.

Regards,
Cristina

**Comment by Smarre** [comment]
FWIW, I had similar problem. I moved Wazuh to another location and symlinked it back to original one. After restarting Wazuh, the audit socket was not usable, I suppose because auditd was expecting the socket to be in different place. Chowns and chmods did not help. Restarting auditd and Wazuh refreshed the socket and it started to work again.

**Comment by Zenidd** [comment]
Hello @brantcolemanthis,

Did you get whodata to work properly? In case you still have problems, let us know so we can find a solution.


Best regards,

Juan Pablo Sáez

**Comment by tuv7041** [comment]
Hi, any chance to reopen this issue? Having the same problem on wazuh 3.8.1. Using the agent on Ubuntu 18.04.2 LTS, everything works correctly until I enable the who data plugin to see who made changes.  Everything works correctly except for the who data info. Tried everything on this post, and I always end up getting this errors on the log:

```
2019/07/26 17:41:44 ossec-syscheckd: INFO: No socket found at '/var/ossec/queue/ossec/audit'. Restarting Auditd service.
2019/07/26 17:41:44 ossec-syscheckd: ERROR: Cannot connect to socket /var/ossec/queue/ossec/audit
2019/07/26 17:41:44 ossec-syscheckd: WARNING: Audit events reader thread not started.
```
The socket file does not exist, and I dont have selinux installed. Any ideas?

**Comment by Zenidd** [comment]
Hi @tuv7041,

Yes, we are reopening this issue.

I've tried to recreate your environment without success. Could you give me some more details so I can recreate the environment more accurately?

- Both the agent and the manager, are they 3.8.1 version?
- Can you check your auditd version? `dpkg --list auditd`
- Can you see the socket file in the agent on `/var/ossec/queue/ossec`? This is my output for `ll /var/ossec/queue/ossec`
```
drwxrwx--- 2 ossec ossec 4096 Aug  2 11:09 ./
drwxr-x--- 7 root  ossec 4096 Aug  1 11:54 ../
-rw-r--r-- 1 ossec ossec   51 Aug  2 11:09 .agent_info
srw-r----- 1 root  root     0 Aug  2 10:53 audit=   <---- auditd socket
srw-rw---- 1 root  ossec    0 Aug  2 11:09 com=
srw-rw---- 1 root  ossec    0 Aug  2 11:09 logcollector=
srw-rw---- 1 ossec ossec    0 Aug  2 11:09 queue=
srw-rw---- 1 root  ossec    0 Aug  2 11:09 syscheck=
srw-rw---- 1 root  ossec    0 Aug  2 11:09 wmodules=```

Please provide us with this information.

Kind regards, Juan Pablo Sáez

**Comment by tuv7041** [comment]
Hi, we had another issue with a puppet agent overwriting the auditd wazuh's hooks. Not related with wazuh. Sorry for the trouble, feel free to close this.

**Comment by Zenidd** [comment]
Hi @tuv7041,

I'm glad the problem has been solved. Thank you very much for letting us know and don't hesitate to open a new ticket if you need help.

Also, If you want to chat with us directly, please join in our Slack server: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.

Greetings, Juan Pablo Sáez
