### ISSUE TITLE
Create Redis decoder

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15849]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a Redis decoder will be written for this purpose.

In addition, the creation of this decoder will be used to identify those functionalities that need to be expanded or improved for a better writing of the decoders.

There is one kind of events.

1. Redis

## Proposed filename

1. `wazuh/src/engine/ruleset/decoders/redis/redis.yml`
 
## Redis documentation 

- redis-5.0.3.log
- redis-darwin-3.0.2.log
- redis-debian-1.2.6.log
- redis-windows-2.4.6.log

## DoD

- [x] Create decoder files.
- [x] Perform Validation and add to a testing environment.
- [x] Define testing policy. Manual testing.
- [x] Documentation.

**Comment by cborla** [comment]
Field Mapping

| ecs field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| event.category              | "redis"                                                        | event.category              |                                               |
| event.dataset               | "redis.log"                                                    | event.dataset               | Forced   AGENT METADATA                       |
| event.kind                  | "event"                                                        | event.kind                  |                                               |
| event.module                | "redis"                                                        | event.module                | Forced   AGENT METADATA                       |
| event.original              | "26571:M 27 Dec 2018 11:19:18.874 * Synchronization with replica 10.114.208.18:6023 succeeded|    |                                          |
| event.type                  | "info"                                                         | event.type                  |                                               |
| fileset.name                | "log"                                                          | file.name                   | Forced   NO ECS                               |
| input.type                  | "log"                                                          | XXX                         | Forced   NO ECS                               |
| log.level                   | "notice"                                                       | log.level                   | Forced   NO ECS filebeat/agent                |
| log.offset                  | 0                                                              | XXX                         | Forced   NO ECS filebeat/agent                |
| message                     | "Synchronization with replica 10.114.208.18:6023 succeeded     | event.message               | Forced   AGENT METADATA                       |
| process.pid                 | "26571"                                                       | process.pid                 |   Forced   AGENT METADATA                     |
| redis.log.role              | "master"                                                       | XXX                         |   Forced   AGENT METADATA              |
| service.type                | "redis"                                                       | service.type                | Forced   AGENT METADATA                       |

**Comment by NahuFigueroa97** [comment]
Field Mapping

| ecs field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| event.category              | "redis"                                                        | event.category              |                                               |
| event.dataset               | "redis.log"                                                    | event.dataset               | Forced   AGENT METADATA                       |
| event.kind                  | "event"                                                        | event.kind                  |                                               |
| event.module                | "redis"                                                        | event.module                | Forced   AGENT METADATA                       |
| event.original              | "26571:M 27 Dec 2018 11:19:18.874 * Synchronization with replica 10.114.208.18:6023 succeeded|    |                                          |
| event.type                  | "info"                                                         | event.type                  |                                               |
| fileset.name                | "log"                                                          | fileset.name                   | Custom field, should use apache fields schema                               |
| input.type                  | "log"                                                          | input.type                         | Custom field, should use apache fields schema                               |
| log.level                   | "notice"                                                       | log.level                   | Forced   NO ECS filebeat/agent                |
| log.offset                  | 0                                                              | XXX                         | Forced   NO ECS filebeat/agent                |
| message                     | "Synchronization with replica 10.114.208.18:6023 succeeded     | message               | Forced   AGENT METADATA                       |
| process.pid                 | "26571"                                                       | process.pid                 |   Forced   AGENT METADATA                     |
| redis.log.role              | "master"                                                       | redis.log.role                        |   Custom field, should use apache fields schema |
| service.type                | "redis"                                                       | service.type                | Forced   AGENT METADATA                       |
