### ISSUE TITLE
Create F5 decoder

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15848]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a F5 decoder will be written for this purpose.

## DoD

- [x] Create decoder files.
- [x] Perform Validation and add to a testing environment.
- [x] Define testing policy. Manual testing.
- [x] Documentation.

**Comment by JorgeMarinoDev** [comment]
**Mapping Fields**

| ecs field                      | value                    | wazuh field                    | reason       |
| ------------------------------ | ------------------------ | ------------------------------ | ------------ |
| @timestamp | "2016-01-29T06:09:59.000Z" | @timestamp |  |
| destination.bytes   | 2132 | destination.bytes |              |
| destination.geo.country_name   | "umq" | destination.geo.country_name |              |
| destination.ip   | "10.47.99.72" | destination.ip |              |
| destination.nat.ip   | "10.165.201.71" | destination.nat.ip |              |
| destination.nat.port   | 6153 | destination.nat.port |              |
| destination.port   | 2288 | destination.port |              |
| event.action   | "Closed" | event.action |              |
| event.code   | "boNemoe" | event.code |              |
| event.dataset   | "f5.bigipafm" | event.dataset |              |
| event.module   | "f5" | event.module |              |
| event.original   | ... | event.original |              |
| file.directory   | "tseddoei" | file.directory |              |
| file.name   | "mnisist" | file.name |              |
| fileset.name   | "bigipafm" | fileset.name | Custom Field |
| geo.city_name   | string | geo.city_name |              |
| geo.country_name   | string | geo.country_name |              |
| geo.region_name   | string | geo.region_name |              |
| group.name   | string | group.name |              |
| host.ip   | "10.228.193.207" | host.ip |              |
| host.name   | "tatemac3541.api.corp" | host.name |              |
| http.request.referrer   | "https: //internal.example.net/<br />lumquid/oluptat.jpg?equepor=iosamn#erspicia" | http.request.referrer |              |
| input.type   | "log" | input.type | Custom Field |
| log.level   | "low" | log.level |              |
| log.offset   | null | log.offset | Custom Field |
| network.application   | "edquian" | network.application |              |
| network.protocol   | "ipv6" | network.protocol |              |
| observer.product   | "pexe" | observer.product |              |
| observer.type   | "Firewall" | observer.type |              |
| observer.vendor   | "F5" | observer.vendor |              |
| observer.version   | 1.2262 | observer.version |              |
| process.parent.pid   | null | process.parent.pid |              |
| process.pid   | 6446 | process.pid |              |
| related.hosts   | ["tatemac3541.api.corp"] |related.hosts||
| related.ip   | ["10.228.193.207",<br />"10.208.121.85",<br />"10.165.201.71",<br />"10.11.196.142"] |related.ip||
| related.user   | ["billoi"] |related.user||
| rsa.counters.dclass_c1   | 7783 | rsa.counters.dclass_c1 | Custom Field |
| rsa.counters.dclass_c1_str   | "Max Concurrent User Sessions Limit" | rsa.counters.dclass_c1_str | Custom Field |
| rsa.db.index   | "ali" | rsa.db.index | Custom Field |
| rsa.internal.event_desc   | "qui" | rsa.internal.event_desc | Custom Field |
| rsa.internal.messageid   | "BIGIP_AFM" | rsa.internal.messageid | Custom Field |
| rsa.investigations.ec_activity   | "Disable" | rsa.investigations.ec_activity | Custom Field |
| rsa.investigations.ec_subject   | "NetworkComm" | rsa.investigations.ec_subject | Custom Field |
| rsa.investigations.ec_theme   | "Communication" | rsa.investigations.ec_theme | Custom Field |
| rsa.misc.action   | ["Closed"] |rsa.misc.action|Custom Field|
| rsa.misc.category   | "oremipsu" | rsa.misc.category | Custom Field |
| rsa.misc.change_attrib   | "maccu" | rsa.misc.change_attrib | Custom Field |
| rsa.misc.change_new   | "ame" | rsa.misc.change_new | Custom Field |
| rsa.misc.client   | "sSMTP" | rsa.misc.client | Custom Field |
| rsa.misc.context   | "liqua" | rsa.misc.context | Custom Field |
| rsa.misc.disposition   | "Failed" | rsa.misc.disposition | Custom Field |
| rsa.misc.event_type   | "equepor" | rsa.misc.event_type | Custom Field |
| rsa.misc.group   | null | rsa.misc.group | Custom Field |
| rsa.misc.log_session_id   | "runtmoll" | rsa.misc.log_session_id | Custom Field |
| rsa.misc.obj_name   | "odoco" | rsa.misc.obj_name | Custom Field |
| rsa.misc.policy_name   | "ria" | rsa.misc.policy_name | Custom Field |
| rsa.misc.reference_id   | null | rsa.misc.reference_id | Custom Field |
| rsa.misc.result   | "unknown" | rsa.misc.result | Custom Field |
| rsa.misc.result_code   | "iusmodt" | rsa.misc.result_code | Custom Field |
| rsa.misc.rule_name   | "ite" | rsa.misc.rule_name | Custom Field |
| rsa.misc.severity   | "low" | rsa.misc.severity | Custom Field |
| rsa.misc.version   | 1.2262 | rsa.misc.version | Custom Field |
| rsa.network.alias_host   | ["tatemac3541.api.corp"] |rsa.network.alias_host|Custom Field|
| rsa.network.network_port   | null | rsa.network.network_port | Custom Field |
| rsa.network.network_service   | "onsequu" | rsa.network.network_service | Custom Field |
| rsa.network.vlan   | 3810 | rsa.network.vlan | Custom Field |
| rsa.time.event_time   | "2016-06-05T21:33:08.000Z" | rsa.time.event_time | Custom Field |
| rsa.time.event_time_str   | "2016-01-29T06:09:59.000Z" | rsa.time.event_time_str | Custom Field |
| rsa.web.fqdn   | "sist1803.mail.local" | rsa.web.fqdn | Custom Field |
| rule.name   | "ite" | rule.name |              |
| service.name   | null | service.name |              |
| service.type   | "f5" | service.type |              |
| source.bytes   | 2552 | source.bytes |              |
| source.geo.country_name   | "sperna" | source.geo.country_name |              |
| source.ip   | "10.208.121.85" | source.ip |              |
| source.nat.ip   | "10.11.196.142" | source.nat.ip |              |
| source.nat.port   | 5222 | source.nat.port |              |
| source.port   | 884 | source.port |              |
| tags   | ["f5.bigipafm","forwarded"] |tags||
| url.domain   | "www5.example.com" | url.domain |              |
| url.extension   | null | url.extension |              |
| url.fragment   | "metco" | url.fragment |              |
| url.original   | "https://www5e........er.html?rsp=oluptat#metco" | url.original |              |
| url.path   | "/olli/rever.html" | url.path |              |
| url.query   | "rsp=oluptat" | url.query |              |
| url.scheme   | "https" | url.scheme |              |
| user_agent.device.name   | "Other" | user_agent.device.name |              |
| user_agent.name   | "Other" | user_agent.name |              |
| user_agent.original   | "mobmail android 2.1.3.3150" | user_agent.original |              |
| user.name   | "billoi" | user.name |              |
