### ISSUE TITLE
Create Fortinet decoder

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15850]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a Fortinet decoder will be written for this purpose.

In addition, the creation of this decoder will be used to identify those functionalities that need to be expanded or improved for a better writing of the decoders.

There are four kind of events.

1. Client endpoint
2. Firewall
3. Fortimail
4. Fortimanager

## Proposed filenames

1. `wazuh/src/engine/ruleset/decoders/fortinet/fortinet.yml`
2. `wazuh/src/engine/ruleset/decoders/fortinet/client_endpoint.yml`
3. `wazuh/src/engine/ruleset/decoders/fortinet/firewall.yml`
4. `wazuh/src/engine/ruleset/decoders/fortinet/fortimail.yml`
5. `wazuh/src/engine/ruleset/decoders/fortinet/fortimanager.yml`
 
## Fortinet documentation 

- [x] **Client endpoint**
  - generated.log
- [x] **Firewall** 
  - event.log
  - traffic.log
  - utm.log
- [x] **Fortimail**
   - generated.log
- [x] **Fortimanager**
  - generated.log

## DoD

- [x] Create decoder files.
- [x] Perform Validation and add to a testing environment.
- [x] Define testing policy. Manual testing.
- [x] Documentation.

**Comment by soynof** [comment]
**Field Mapping Client endpoint**

| ecs field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| destination.ip              | "10.102.123.34"                                                | destination.ip              |                                               |
| destination.port            | 3994                                                 		   | destination.port            | 							                     |
| event.action                | "deny"                                                         | event.action                |                                               |
| event.code                  | "http"                                                         | event.code                	 |                                               |
| event.dataset               | "fortinet.clientendpoint									   | event.dataset   			 |                                               |
| event.module                | "fortinet"                                                     | event.module                |                                               |
| event.original              | "January 29 06:09:59 boNemoe4402.www.invalid proto=udp service=http status=deny src=10.150.92.220 dst=10.102.123.34 src_port=7178 dst_port=3994 server_app=reeufugi pid=7880 app_name=enderitq traff_direct=external block_count=5286 logon_user=sumdo@litesse6379.api.domain msg=failure"	  | event.original              |                                               |
| event.outcome               | "failure"                                                      | event.outcome               |                                               |
| fileset.name                | "clientendpoint"                                               | fileset.name                |                                               |
| host.name                   | "boNemoe4402.www.invalid"                                      | host.name                   |                                               |
| input.type                  | "log"     													   | input.type                  |                                               |
| log.offset                  | 0                                                       	   | log.offset                  |                                               |
| network.direction           | "external"                                                     | network.direction           |                                               |
| network.protocol            | "udp"                                                          | network.protocol            |                                               |
| observer.product            | "FortiClient"                                                  | observer.product            |                                               |
| observer.type            | "Anti-Virus"                                                          | observer.type            |                                               |
| observer.vendor            | "Fortinet"                                                          | observer.vendor            |                                               |
| process.pid            | 7880                                                          | process.pid            |                                               |
| related.hosts            |                                                           | related.hosts            |                                               |
|             | "10.102.123.34"                                                          |             |                                               |
|             | "10.150.92.220"                                                          |             |                                               |
| related.user            |                                                           | related.user            |                                               |
|             | "sumdo"                                                          |             |                                               |
| rsa.counters.dclass_c1            | 5286                                                          | rsa.counters.dclass_c1            |                                               |
| rsa.counters.dclass_c1_str            | "block_count"                                                          | rsa.counters.dclass_c1_str            |                                               |
| rsa.internal.messageid            | "http"                                                          | rsa.internal.messageid            |                                               |
| rsa.investigations.ec_outcome            | "http"                                                          | rsa.internal.messageid            |                                               |
| rsa.investigations.ec_subject            | "NetworkComm"                                                          | rsa.investigations.ec_subject            |                                               |
| rsa.investigations.ec_theme            | "ALM"                                                          | rsa.investigations.ec_theme            |                                               |
| rsa.misc.action            |                                                          | rsa.misc.action            |                                               |
|             | "deny"                                                          |             |                                               |
| rsa.misc.result            | "failure"                                                          | rsa.misc.result            |                                               |
| rsa.network.alias_host            |                                                          | rsa.network.alias_host            |                                               |
|             | "boNemoe4402.www.invalid"                                                          |             |                                               |
| rsa.network.domain            | "litesse6379.api.domain"                                                          | network.protocol            |                                               |
| rsa.network.network_service            | "http"                                                          | rsa.network.network_service            |                                               |
| server.domain            | "litesse6379.api.domain"                                                          | server.domain            |                                               |
| server.registered_domain            | "api.domain"                                                          | server.registered_domain            |                                               |
| server.subdomain            | "litesse6379"                                                          | server.subdomain            |                                               |
| server.top_level_domain            | "domain"                                                          | server.top_level_domain            |                                               |
| service.type            | "fortinet"                                                          | service.type            |                                               |
| source.ip            | "10.150.92.220"                                                          | source.ip            |                                               |
| source.port            | 7178                                                          | source.port            |                                               |
| tags            |                                                           | tags            |                                               |
|             | "fortinet.clientendpoint"                                                          |             |                                               |
|             | "forwarded"                                                          |             |                                               |
| user.name            | "sumdo"                                                          | user.name            |                                               |

**Comment by soynof** [comment]
<!DOCTYPE html><p cid="n0" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative;"><span md-inline="strong" class="md-pair-s md-expand" style="box-sizing: border-box;"><strong style="box-sizing: border-box;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">Field Mapping Fortinet Firewall</span></strong></span></p><figure class="md-table-fig" cid="n3" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default;">

ecs field | value | wazuh field | reason
-- | -- | -- | --
@timestamp | "2020-04-23T12:32:48.000-05:00" | @timestamp |  
event.action | "FSSO-logon" | event.action |  
event.category |   | event.category |  
  | "authentication" |   |  
event.code | "0102043014" | event.code |  
event.dataset | "fortinet.firewall" | event.dataset |  
event.kind | "event" | event.kind |  
event.module | "fortinet" | event.module |  
event.outcome | "success" | event.outcome |  
event.start | "2020-04-18T12:32:48.439-05:00" | event.start |  
event.timezone | "-0500" | event.timezone |  
event.type |   | event.type |  
  | "start" |   |  
  | "user" |   |  
fileset.name | "firewall" | fileset.name | Custom field, should use apache fields schema
fortinet.firewall.action | "FSSO-logon" | fortinet.firewall.action | Custom field, should use apache fields schema
fortinet.firewall.action | FSSO-logon | fortinet.firewall.action | Custom field, should use apache fields schema
fortinet.firewall.server | "elasticserver" | fortinet.firewall.server | Custom field, should use apache fields schema
fortinet.firewall.subtype | "user" | fortinet.firewall.subtype | Custom field, should use apache fields schema
fortinet.firewall.vd | "root" | fortinet.firewall.vd | Custom field, should use apache fields schema
input.type | "log" | input.type | Custom field, should use apache fields schema
log.level | "notice" | log.level |  
log.offset | 0 | log.offset | Not implemented
message | FSSO-logon event from FSSO_elasticserver: user elasticouser logged on 10.10.10.10 | message |  
network.type | "ipv4" | network.type |  
observer.name | "testswitch3" | observer.name |  
observer.product | "Fortigate" | observer.product |  
observer.serial_number | "someotherrouteridagain" | observer.serial_number |  
observer.type | "firewall" | observer.type |  
observer.vendor | "Fortinet" | observer.vendor |  
related.ip |   | related.ip |  
  | "10.10.10.10" |   |  
related.user |   | related.user |  
  | "elasticouser" |   |  
rule.description | "FSSO logon authentication status" | rule.description |  
service.type | "fortinet" | service.type |  
source.ip | "10.10.10.10" | source.ip |  
source.user.name | "elasticouser" | source.user.name |  
tags |   | tags |  
  | "fortinet-firewall" |   |  
  | "forwarded" |   |  
source.ip | "10.150.92.220" | source.ip |  

</figure>

**Comment by soynof** [comment]
**Field Mapping Fortinet Fortimanager**

| ecs field                       | value                                                        | wazuh field                     | reason        |
| ------------------------------- | ------------------------------------------------------------ | ------------------------------- | ------------- |
| destination.bytes               | 3879                                                         | destination.bytes               |               |
| destination.geo.country_name    | ation                                                        | destination.geo.country_name    |               |
| destination.ip                  | 10.171.204.166                                               | destination.ip                  |               |
| destination.nat.ip              | 10.53.110.111                                                | destination.nat.ip              |               |
| destination.nat.port            | 2549                                                         | destination.nat.port            |               |
| destination.port                | 6668                                                         | destination.port                |               |
| event.action                    | accept                                                       | event.action                    |               |
| event.code                      | atio                                                         | event.code                      |               |
| event.dataset                   | fortinet.fortimanager                                        | event.dataset                   | Forced        |
| event.module                    | fortinet                                                     | event.module                    | Forced        |
| event.timezone                  | CEST                                                         | event.timezone                  |               |
| fileset.name                    | fortimanager                                                 | fileset.name                    | Custom Forced |
| host.name                       | aer445.host                                                  | host.name                       |               |
| http.request.referrer           | https://api.example.org/tamremap/tur.html?radipis=isetq#estqui | http.request.referrer           |               |
| input.type                      | log                                                          | input.type                      | Custom Forced |
| log.level                       | high                                                         | log.level                       |               |
| log.offset                      | 593                                                          | log.offset                      | Custom        |
| network.bytes                   | 10257                                                        | network.bytes                   |               |
| network.direction               | external                                                     | network.direction               |               |
| network.protocol                | TCP                                                          | network.protocol                |               |
| observer.egress.interface.name  | enp0s2581                                                    | observer.egress.interface.name  |               |
| observer.ingress.interface.name | enp0s208                                                     | observer.ingress.interface.name |               |
| observer.product                | FortiManager                                                 | observer.product                | Forced        |
| observer.serial_number          | tur                                                          | observer.serial_number          |               |
| observer.type                   | Configuration                                                | observer.type                   |               |
| observer.vendor                 | Fortinet                                                     | observer.vendor                 | Forced        |
| observer.version                | 1.41                                                         | observer.version                |               |
| related.hosts__001              | aer445.host                                                  | related.hosts__001              | Custom        |
| related.hosts__002              | mvolu                                                        | related.hosts__002              | Custom        |
| related.hosts__003              | pisciv                                                       | related.hosts__003              | Custom        |
| related.ip__001                 | 10.171.204.166                                               | related.ip__001                 | Custom        |
| related.ip__002                 | 10.62.4.246                                                  | related.ip__002                 | Custom        |
| related.user__-                 | oluptas                                                      | related.user__-                 | Custom        |
| rsa.db.index                    | taevi                                                        | rsa.db.index                    | Custom        |
| rsa.internal.event_desc         | com                                                          | rsa.internal.event_desc         | Custom        |
| related.ip__003                 | 10.53.110.111                                                | related.ip__003                 | Custom        |
| rsa.internal.messageid          | generic_fortinetmgr                                          | rsa.internal.messageid          | Forced        |
| rsa.investigations.event_vcat   | eius                                                         | rsa.investigations.event_vcat   | Custom        |
| rsa.misc.OS                     | anonnu                                                       | rsa.misc.OS                     | Custom        |
| rsa.misc.action__001            | accept                                                       | rsa.misc.action__001            | Custom        |
| rsa.misc.action__002            | mol                                                          | rsa.misc.action__002            | Custom        |
| rsa.misc.category               | exe                                                          | rsa.misc.category               | Custom        |
| rsa.misc.client                 | radip                                                        | rsa.misc.client                 | Custom        |
| rsa.misc.context                | nibus                                                        | rsa.misc.context                | Custom        |
| rsa.misc.event_source           | pisciv                                                       | rsa.misc.event_source           | Custom        |
| rsa.misc.event_type             | umexe                                                        | rsa.misc.event_type             | Custom        |
| rsa.misc.fcatnum                | byC                                                          | rsa.misc.fcatnum                | Custom        |
| rsa.misc.filter                 | tinculp                                                      | rsa.misc.filter                 | Custom        |
| rsa.misc.hardware_id            | tur                                                          | rsa.misc.hardware_id            | Custom        |
| rsa.misc.log_session_id         | tNequ                                                        | rsa.misc.log_session_id         | Custom        |
| rsa.misc.obj_name               | uaturQ                                                       | rsa.misc.obj_name               | Custom        |
| rsa.misc.policy_id              | uidolor                                                      | rsa.misc.policy_id              | Custom        |
| rsa.misc.policy_name            | ionofde                                                      | rsa.misc.policy_name            | Custom        |
| rsa.misc.reference_id           | atio                                                         | rsa.misc.reference_id           | Custom        |
| rsa.misc.rule_name              | eumiu                                                        | rsa.misc.rule_name              | Custom        |
| rsa.misc.severity               | high                                                         | rsa.misc.severity               | Custom        |
| rsa.network.domain              | xplicabo4308.www.example                                     | rsa.network.domain              | Custom        |
| rsa.misc.sig_id                 | 6728                                                         | rsa.misc.sig_id                 | Custom        |
| rsa.misc.version                | 1.41                                                         | rsa.misc.version                | Custom        |
| rsa.misc.vsys                   | iatnu                                                        | rsa.misc.vsys                   | Custom        |
| rsa.network.alias_host__-       | aer445.host                                                  | rsa.network.alias_host__-       | Custom        |
| rsa.network.dinterface          | enp0s2581                                                    | rsa.network.dinterface          | Custom        |
| rsa.network.network_service     | emape                                                        | rsa.network.network_service     | Custom        |
| rsa.network.sinterface          | enp0s208                                                     | rsa.network.sinterface          | Custom        |
| rsa.threat.threat_desc          | sum                                                          | rsa.threat.threat_desc          | Custom        |
| rsa.time.duration_time          | 72.226                                                       | rsa.time.duration_time          | Custom        |
| rsa.time.event_time             | 2016-02-12T03:12:33.000Z                                     | rsa.time.event_time             | Custom        |
| server.domain                   | xplicabo4308.www.example                                     | server.domain                   |               |
| server.registered_domain        | www.example                                                  | server.registered_domain        |               |
| server.subdomain                | xplicabo4308                                                 | server.subdomain                |               |
| server.top_level_domain         | example                                                      | server.top_level_domain         |               |
| rsa.time.timezone               | CEST                                                         | rsa.time.timezone               | Custom        |
| rsa.time.event_time_str         | onemul                                                       | rsa.time.event_time_str         | Custom        |
| rsa.web.reputation_num          | 145.047                                                      | rsa.web.reputation_num          | Custom        |
| rsa.web.web_ref_domain          | mvolu                                                        | rsa.web.web_ref_domain          | Custom        |
| rule.name                       | eumiu                                                        | rule.name                       |               |
| service.type                    | fortinet                                                     | service.type                    | Forced        |
| source.bytes                    | 6378                                                         | source.bytes                    |               |
| source.geo.country_name         | tconsec                                                      | source.geo.country_name         |               |
| source.ip                       | 10.62.4.246                                                  | source.ip                       |               |
| source.mac                      | 01:00:5e:84:66:6c                                            | source.mac                      |               |
| source.port                     | 189                                                          | source.port                     |               |
| tags__001                       | fortinet.fortimanager                                        | tags__001                       |               |
| tags__002                       | forwarded                                                    | tags__002                       |               |
| url.domain                      | www.example.net                                              | url.domain                      |               |
| url.extension                   | htm                                                          | url.extension                   |               |
| url.fragment                    | roinBCS                                                      | url.fragment                    |               |
| url.original                    | https://www.example.net/orisn/cca.htm?ofdeF=metcons#roinBCS  | url.original                    |               |
| url.path                        | /orisn/cca.htm                                               | url.path                        |               |
| url.query__001                  | ofdeF=metcons                                                | url.query__001                  |               |
| url.query__002                  | taspe                                                        | url.query__002                  |               |
| url.scheme                      | https                                                        | url.scheme                      |               |
| user.name                       | oluptas                                                      | user.name                       |               |
