### ISSUE TITLE
The `csv` parser breaks when a slash is used within a key

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15856]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3703   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the HLP testing using the `csv` parser, if you try to use the `/` character within the key name, it creates a new key-value pair level.

<details><summary>decoder that was used</summary>

```
name: decoder/custom-json/0

sources:
- decoder/json/0

check:
- event.original: +s_starts/{
- ~json.type: +r_match/^test

parse:
logpar:
    - ~json.testing: <~outField/csv/,/'/akey\/anotherkey/out1/out2/outN>
```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"value1,value2,v,vv,vv,"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"value1,value2,v,vv,vv,\"}"
    },
    "~json": {
        "type": "test",
        "testing": "value1,value2,v,vv,vv,"
    },
    "~outField": {
        ",": "value1",
        "'": "value2",
        "akey": {
            "anotherkey": "v"
        },
        "out1": "vv",
        "out2": "vv",
        "outN": null
    }
}
```

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3703#issuecomment-1368013835.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed in: https://github.com/wazuh/wazuh/issues/23904
