### ISSUE TITLE
The `dsv` parser unescaping is not working

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15854]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3703   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the HLP testing, the `dsv` parser is not unescaping the quoting characters correctly.

<details><summary>decoder that was used</summary>

```
name: decoder/custom-json/0

sources:
- decoder/json/0

check:
- event.original: +s_starts/{
- ~json.type: +r_match/^test

parse:
logpar:
    - ~json.testing: <~outField/dsv/|/"/\\/out1/out2/out3/outN>
```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"\"\\\"value1\\\"\"|value2|value3|valueN"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"\\\"\\\\\\\"value1\\\\\\\"\\\"|value2|value3|valueN\"}"
    },
    "~json": {
        "type": "test",
        "testing": "\"\\\"value1\\\"\"|value2|value3|valueN"
    },
    "~outField": {
        "out1": "\\value1\\",
        "out2": "value2",
        "out3": "value3",
        "outN": "valueN"
    }
}
```

> The unescape value for `out1` should be `\"value1\"`. Looks like the unescaping is not correct.

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3703#issuecomment-1367506757.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Solved: https://github.com/wazuh/wazuh/pull/22688

<details><summary>decoder that was used</summary>

```
name: decoder/custom-json/0

sources:
- decoder/json/0

check:
- event.original: +s_starts/{
- ~json.type: +r_match/^test

parse:
logpar:
    - ~json.testing: <~outField/dsv/|/"/\\/out1/out2/out3/outN>
```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"\"\\\"value1\\\"\"|value2|value3|valueN"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"\\\"\\\\\\\"value1\\\\\\\"\\\"|value2|value3|valueN\"}"
    },
    "~json": {
        "type": "test",
        "testing": "\"\\\"value1\\\"\"|value2|value3|valueN"
    },
    "~outField": {
        "out1": "\"value1\"",
        "out2": "value2",
        "out3": "value3",
        "outN": "valueN"
    }
}
```
