### ISSUE TITLE
Create Sonicwall decoder

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15860]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a Sonicwall decoder will be written for this purpose.

In addition, the creation of this decoder will be used to identify those functionalities that need to be expanded or improved for a better writing of the decoders.

There is one kind of events.

1. Sonicwall Firewall 

## Proposed filenames

1. `wazuh/src/engine/ruleset/decoders/sonicwall/firewall.yml`

## Sonicwall documentation 

- [x] **Firewall**
  - general.log
  - generated.log

## DoD

- [x] Create decoder files.
- [x] Perform Validation and add to a testing environment.
- [x] Define testing policy. Manual testing.
- [x] Documentation.

**Comment by NahuFigueroa97** [comment]
Field Mapping

| ecs field                   | value                                                          | wazuh field                 | reason                                        |
| --------------------------- | -------------------------------------------------------------- | --------------------------- | --------------------------------------------- |
| event.action                 | "accept"                                                        | event.action              |                                               |
| event.code                  | "428"                                                    | event.code              | Forced   AGENT METADATA                       |
| event.dataset               | "sonicwall.firewall"                                                    | event.dataset               | Forced   AGENT METADATA                       |
| event.kind                  | "event"                                                        | event.kind                  |                                               |
| event.module                | "sonicwall"                                                        | event.module                | Forced   AGENT METADATA                       |
| event.original              | "id=quip sn=mporain time=\"2016-12-23 12:09:07\" fw=10.34.161.166 pri=very-high c=sequi m=428 msg=\"rehend\" n=tio src=10.245.200.97:3768:eth4059 dst=10.219.116.137:3452:enp0s3611 srcMac= 01:00:5e:1a:ec:91 dstMac=01:00:5e:e1:73:47 proto=icmp fw_action=\"accept\""| event.original   |                                          |
| destination.ip                  | "10.219.116.137"                                                         | destination.ip                  |                                               |
| destination.port              | "3452"                                                        | destination.port              |                                               |
| destination.mac              | "01:00:5e:e1:73:47"                                                        | destination.mac             |                                               |
| fileset.name              | "firewall"                                                        | fileset.name               |                                               |
| host.ip                | "10.34.161.166"                                                          | host.ip                   | Custom field, should use apache fields schema                               |
| input.type                | "log"                                                          | input.type                  | Custom field, should use apache fields schema                               |
| log.level                  | "very-high"                                                          | log.level                         | Custom field, should use apache fields schema                               |
| log.offset                   | "notice"                                                       | XXX                   | Forced   NO ECS filebeat/agent                |
| network.protocol                  | "icmp"                                                           | network.protocol                         | Not implementedt                |
| observer.egress.interface.name                    | "enp0s3611"    | observer.egress.interface.name              | Forced   AGENT METADATA                       |
| observer.ingress.interface.name                   | "eth4059"     | observer.ingress.interface.name               | Forced   AGENT METADATA                       |
| observer.product                    | "Firewalls"    | observer.product               | Forced   AGENT METADATA                       |
| observer.type                    | "Firewalls"      | observer.type               | Forced   AGENT METADATA                       |
| observer.vendor                    | "Sonicwall"     | observer.vendor               | Forced   AGENT METADATA                       |
| rsa.internal.event_desc                  | "rehend"   | rsa.internal.event_desc              | Forced   AGENT METADATA                       |
| rsa.internal.messageid                  | "428"     | rsa.internal.messageid               | Forced   AGENT METADATA                       |
| rsa.misc.action                    | "accept"     | rsa.misc.action               | Forced   AGENT METADATA                       |
| rsa.misc.category                    | "sequi"    | rsa.misc.category              | Forced   AGENT METADATA                       |
| rsa.misc.serial_number                 | "mporain"  | rsa.misc.serial_number        | Forced   AGENT METADATA                       |
| rsa.misc.severity                    | "very-high"   | rsa.misc.severity               | Forced   AGENT METADATA                       |
| rsa.misc.network.dinterface                   | "enp0s3611" | rsa.misc.network.dinterface        | Forced   AGENT METADATA                       |
| rsa.misc.network.sinterface            | "eth4059"  | rsa.misc.network.sinterface               | Forced   AGENT METADATA                       |
| rsa.misc.time.event_time                    |  "2016-12-23T12:09:07.000Z"  | rsa.misc.time.event_time               | Forced   AGENT METADATA                       |
| rsa.misc.time.date                   | "2016/12/23"  | rsa.misc.time.date              | Forced   AGENT METADATA                       |
| related.ip                    | ["10.245.200.97", "10.219.116.137", "10.34.161.166"]    | related.ip               | Forced   AGENT METADATA                       |
| source.ip                    | "10.245.200.97"     | source.ip              | Forced   AGENT METADATA                       |
| source.mac                    | 3768   | source.mac              | Forced   AGENT METADATA                       |
| source.port                    | "01:00:5e:1a:ec:91"  | source.port               | Forced   AGENT METADATA                       |
| tags                 | ["forwarded","sonicwall.firewall"] | tags                |                      |
| @timestamp              | "2016-12-23T12:09:07.000Z"       | @timestamp                        |   Custom field, should use apache fields schema |
