### ISSUE TITLE
Trailing space on SCA `policy ID 26060` of Windows causing a failed result

### ISSUE THREAD

**Issue by carlosdams** [wazuh/wazuh#15875]
|Wazuh version|Component|Install type|Install method|Platform|file|
|---|---|---|---|---|---|
| 4.3.x | SCA | Manager/Agent | Packages/Sources | Windows 11 | Manager: /var/ossec/ruleset/sca/**cis_win11_enterprise.yml.disabled** / Agent: C:\Program Files (x86)\ossec-agent\ruleset\sca\\**cis_win11_enterprise.yml** |

The SCA scan is reporting as **failed** for `Policy ID 26060: Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'.` 

I checked the file `cis_win11_enterprise.yml` to look for that ID 26060 and noticed there is an space at the end on the second rule before the final single quote `'` that is causing the ID result to fail.

Original:
```
    rules:
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel '
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel -> 5'

```
![image](https://user-images.githubusercontent.com/35348824/212109682-a447c586-85cf-4d4a-9375-7c2b48eefb7c.png)

Fix:
```
    rules:
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa -> LmCompatibilityLevel -> 5'
```

![image](https://user-images.githubusercontent.com/35348824/212109995-8b3bb228-47c8-4090-99fd-8bc9d4e64c45.png)

**Comment by sarog** [comment]
I created a [pull request](https://github.com/wazuh/wazuh/pull/15480) ~2 months to fix these issues (among others) but no dice.
