### ISSUE TITLE
Syscollector - MacPorts package manager inventory support.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#15877]
## Description 

With the purpose of adding support to Syscollector for MacPorts package manager in Mac OS agents, a spike was performed as part of https://github.com/wazuh/wazuh/issues/15726 always having in mind that the main goal is to provide the information needed to Vulnerability Detector to run against those packages (ports in MacPorts slang).

It is required to parse the information from the package manager database (registry.db) which is a SQlite database to get the information from installed packages. 

## DoD 

- [x] Evaluate and implement a way to handle multiple architectures if needed.
- [x] Consider and evaluate the possibility to have multiple versions of the same package.
- [x] Evaluate a proper default value for those key items that are required by the vulnerability detector.
- [x] Unit testing.
- [x] Implement the database parser.
- [x] Verify the proper functioning.
- [x] Add QA test to be executed with GitHub Actions.
- [x] Add QA test specific for macports packages.
- [x] Refactor to move SQLite wrapper implementation.

**Comment by MiguelazoDS** [comment]
# Findings

## Vendor missing 

This implementation (https://github.com/wazuh/wazuh/pull/16089) should fix the issue with MacPorts packages too since they do not report the vendor either.

## Multiple architectures.

It was not found a situation when this happens, anyway for MacOS the architecture is ignored.

## Multiple packages version

Only one package can be active at a time, although multiple packages can be installed. 
![image](https://user-images.githubusercontent.com/13010397/217633625-0b304f5c-020f-4a54-9bc0-799b0cb6f0f6.png)
![image](https://user-images.githubusercontent.com/13010397/217633798-7f1a789b-4049-48c3-b332-5b4ff97c1618.png)

**Comment by pereyra-m** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/16901

**Comment by MiguelazoDS** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/17186 (created after #16901)

**Comment by MiguelazoDS** [comment]
# Update 05/24/23 

After rebase checks passed.
