### ISSUE TITLE
The signature validation log should show the certificate name

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#15873]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Wazuh agent | Agent | MSI | Windows XP and Windows Server 2003 |

## Description

This issue is related to manual testing [#3612](https://github.com/wazuh/wazuh-qa/issues/3612) of the wazuh/wazuh-qa repository.
The error is in the log WARNING or CRITICAL (depending on the IMAGE_TRUST_CHECK flag). The log doesn't show the name of the certificate **DigiCert High Assurance EV Root CA**, so the user does not know what is the certificate not available.

## Step to reproduce

- Install a 4.4.0 signed package with IMAGE_TRUST_CHECK=1 or IMAGE_TRUST_CHECK=2 (Windows XP or Windows 2003)
- Check ossec.conf

## Actual result

```
2023/01/04 04:56:44 wazuh-agent: CRITICAL: The dynamic signature validation is not available because the CA name is not 
available.
```

## Expected result

The log should show the certificate name **DigiCert High Assurance EV Root CA**

**Comment by damarisg** [comment]
Fixed on https://github.com/wazuh/wazuh/pull/15404.
