### ISSUE TITLE
The dollar character can't be used within function helpers as literal

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15879]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3735   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the function helpers' testing, was detected that you can't use the `$` as a literal, but with the same cases for the HLPs it works.

<details><summary>Decoder signatures</summary>

```
map:
      - ~outMap: +parse_csv/$~json.testing/,/'/'/$event/out1/out2/outN

parse:
    logpar:
        - ~json.testing: <~outField/csv/,/'/\//$event/out1/out2/outN>
```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"value1,value2,v,vv,vv,,"}
```

</details>

The character $ is not allowed within the function helpers, if you try to use it without escape it the following error appears
```
15:14:26.509735 cmdApiCatalog.cpp:230 ERR[4522  ] Engine API Catalog: Request error (400): An error occurred while trying to validate "decoder/custom-json/0": Stage block "map" building failed: An error occurred while building the helper function "parse_csv": Invalid parameter type for operation 'parse_csv'.
```

> If we escape it, the name that appears is not the same that if we use it via HLP `<~outField/csv/,/'/\//$event/out1/out2/outN>`

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"value1,value2,v,vv,vv,,\"}"
    },
    "~json": {
        "type": "test",
        "testing": "value1,value2,v,vv,vv,,"
    },
    "~outField": {
        ",": "value1",
        "'": "value2",
        "": {
            "": "v"
        },
        "$event": "vv",
        "out1": "vv",
        "out2": null,
        "outN": null
    },
    "~outMap": {
        ",": "value1",
        "'": "v",
        "\\$event": "vv",
        "out1": "vv",
        "out2": null,
        "outN": null
    }
}
```

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3735#issuecomment-1380754376 within the csv cases.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Tested with the latest changes in the function helper. 
Fixed.
