### ISSUE TITLE
The slash character can't be used as literal within function helpers

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15878]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3735   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the function helpers' testing, was detected that you can't use the slash `/` as a literal, both argument and string within the helpers.

- For example, you can't reproduce the case where dsv delimiter is a slash:
    ```
    map:
        - ~outMap: +parse_dsv/$~json.testing/\\//'/\\/out1/out2/outN
    ```
    The following error is prompted
    ```
    11:07:34.854193 cmdTest.cpp:155  ERR[3490  ] Engine "test" command: An error occurred while building the environment "environment/wazuh/0": Building asset "decoder/custom-json/0" failed: Stage block "map" building failed: An error occurred while building the helper function "parse_dsv": Delim, quote and escape characters must be single characters
    ```

- Another example is that you try to escape the caracter to create a field that contains the slash as a literal:

    ```
    map:
        - ~outMap: +parse_csv/$~json.testing/,/'/akey\/anotherkey/out1/out2/outN
    ```

    With this input
    ```
    {"type":"test","testing":"value1,value2,v,vv,vv,a,"}
    ```

    the parser represents the slash as a new field
    ```
    "~outMap": {
            ",": "value1",
            "'": "value2",
            "akey\\": "v",
            "anotherkey": "vv",
            "out1": "vv",
            "out2": "a",
            "outN": null
        }
    ```

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3735#issuecomment-1380754376 within the dsv and csv cases.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed.

With this input
```json
{"type":"test","testing":"value1,value2,v,vv,vv,a,"}
```

output:
```json
"outMap": {
        ",": "value1",
        "'": "value2",
        "akey": "v",
        "anotherkey": "vv",
        "out1": "vv",
        "out2": "a",
        "outN": ""
    }
```
