### ISSUE TITLE
The kv helper breaks when receiving not well-balanced strings

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15881]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh-qa/issues/3735   |     https://github.com/wazuh/wazuh/issues/15421 |

# Description

During the function helpers' testing, was detected that using non-well balanced strings breaks the `parse_kv` function_helper

<details><summary>Decoder's signature</summary>

```
map:
    - ~outMap: +parse_kv/$~json.testing/=/,/'/'
```

</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'\"}"
    },
    "~json": {
        "type": "test",
        "testing": "key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'"
    },
    "~outMap": {
        "key1": "value=1",
        "key2": "alue''2,key3='value,3",
        "key4": "value=,'4"
    }
}
```

> The key2's value `key2=value''2,key3=` has three special chars and the first `v` is not there anymore.

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3735#issuecomment-1380754376 within the kv cases.

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
This bug is fixed:


</details>

<details><summary>Log input</summary>

```
{"type":"test","testing":"key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'"}
```

</details>

```
OUTPUT:

{
    "wazuh": {
        "queue": 49,
        "origin": "/dev/stdin"
    },
    "event": {
        "original": "{\"type\":\"test\",\"testing\":\"key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'\"}"
    },
    "~json": {
        "type": "test",
        "testing": "key1='value=1',key2=value''2,key3='value,3',key4='value=,''4'"
    },
    "~outMap": {
        "key1": "value=1",
        "key2": "value''2,
        "key3='value,3",
        "key4": "value=,'4"
    }
}
```
