### ISSUE TITLE
Wrong behavior detected during HLP testing

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#15882]
## Description

After the team added some High Level Parsers and function helpers https://github.com/wazuh/wazuh/issues/15421, the following testing was performed:

- https://github.com/wazuh/wazuh-qa/issues/3703
- https://github.com/wazuh/wazuh-qa/issues/3735

## Bugs

The following bugs were reported after the above testing 

- https://github.com/wazuh/wazuh/issues/15854
- https://github.com/wazuh/wazuh/issues/15855
- https://github.com/wazuh/wazuh/issues/15856
- https://github.com/wazuh/wazuh/issues/15879
- https://github.com/wazuh/wazuh/issues/15878
- https://github.com/wazuh/wazuh/issues/15880
- https://github.com/wazuh/wazuh/issues/15881

**Comment by JcabreraC** [comment]
All the tasks of the epic issue completed.
