### ISSUE TITLE
Create Apple decoder

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#15884]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
It is necessary to extend the coverage of our ruleset, so a Apple decoder will be written for this purpose.

In addition, the creation of this decoder will be used to identify those functionalities that need to be expanded or improved for a better writing of the decoders.

Search into module/system/syslog/test

## DoD

- [ ] Create decoder files.
- [ ] Perform Validation and add to a testing environment.
- [ ] Define testing policy. Manual testing.
- [ ] Documentation.

**Comment by Dwordcito** [comment]
This will be done in another epic and under the work of another team.


https://github.com/wazuh/wazuh/issues/23892 and https://github.com/wazuh/wazuh/issues/23893
