### ISSUE TITLE
Wazuh dashboard does not show any results and getting error "There are no results for selected time range. Try another one."

### ISSUE THREAD

**Issue by Kprince-k** [wazuh/wazuh#15890]
Our wazuh agent is configured with 300+ plus agent and it was working well and good. now its showing any results in the dashboard or any events.

Below are the errors logs

Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:32:02  ERROR  Unexpected end of JSON input
Nov 14, 2022 @ 06:33:50  INFO  Wazuh dashboard index: .kibana
Nov 14, 2022 @ 06:33:50  INFO  App revision: 4306
Nov 14, 2022 @ 06:33:50  INFO  Total RAM: 16009MB
Nov 15, 2022 @ 05:29:02  INFO  Report started
Nov 15, 2022 @ 05:29:02  INFO  1 agents for API default
Nov 15, 2022 @ 05:29:02  INFO  Started to sanitize filters
Nov 15, 2022 @ 05:29:02  INFO  Started to render the time range and the filters
Nov 15, 2022 @ 05:29:02  INFO  Format date Mon Nov 14 2022 10:59:00 GMT+0000 (Coordinated Universal Time)
Nov 15, 2022 @ 05:29:02  INFO  Format date Tue Nov 15 2022 10:59:00 GMT+0000 (Coordinated Universal Time)
Nov 15, 2022 @ 05:29:02  INFO  Section agents and tab general, API is default. From 1668403740108 to 1668490140108. Filters manager.name: siem.sboxdc.com AND agent.id: 013. Index pattern wazuh-alerts-*
Nov 15, 2022 @ 05:29:02  INFO  5 visualizations for tab general
Nov 15, 2022 @ 05:29:02  INFO  Item ID Wazuh-App-Agents-General-Top-5-PCI-DSS-Requirements, from agents and tab general
Nov 15, 2022 @ 05:29:02  INFO  Item ID Wazuh-App-Agents-General-Alerts, from agents and tab general
Nov 15, 2022 @ 05:29:02  INFO  Item ID Wazuh-App-Agents-General-Alert-groups-evolution, from agents and tab general
Nov 15, 2022 @ 05:29:02  INFO  Item ID Wazuh-App-Agents-General-Top-5-alerts, from agents and tab general
Nov 15, 2022 @ 05:29:02  INFO  Item ID Wazuh-App-Agents-General-Top-10-groups, from agents and tab general
Nov 15, 2022 @ 05:29:02  INFO  Started to render tables
Nov 15, 2022 @ 05:29:10  INFO  Fetching created reports
Nov 15, 2022 @ 05:29:10  INFO  Fetching created reports
Nov 15, 2022 @ 05:37:40  ERROR  {"title":"Bad Request","detail":"Cluster is not running, it might be disabled in `WAZUH_HOME/etc/ossec.conf`","remediation":"Please, visit the official documentation (https://documentation.wazuh.com/4.3/user-manual/configuring-cluster/index.html) to get more information about how to configure a cluster","error":3013}
Nov 15, 2022 @ 11:54:23  INFO  Wazuh dashboard index: .kibana
Nov 15, 2022 @ 11:54:23  INFO  App revision: 4306
Nov 15, 2022 @ 11:54:23  INFO  Total RAM: 16009MB
Dec 18, 2022 @ 18:00:00  INFO  connect ECONNREFUSED 172.16.248.22:55000
Dec 18, 2022 @ 18:00:00  INFO  connect ECONNREFUSED 172.16.248.22:55000
Dec 18, 2022 @ 18:00:00  ERROR  connect ECONNREFUSED 0.0.0.0:9200
Dec 19, 2022 @ 00:55:01  INFO  Wazuh dashboard index: .kibana
Dec 19, 2022 @ 00:55:01  INFO  App revision: 4306
Dec 19, 2022 @ 00:55:01  INFO  Total RAM: 16009MB
Jan 9, 2023 @ 07:42:36  INFO  Wazuh dashboard index: .kibana
Jan 9, 2023 @ 07:42:36  INFO  App revision: 4306
Jan 9, 2023 @ 07:42:36  INFO  Total RAM: 16009MB

**Comment by Kprince-k** [comment]
I have fixed the issue. issue was with filebeat service

**Comment by nhutphoma** [comment]
> Our wazuh agent is configured with 300+ plus agent and it was working well and good. now its showing any results in the dashboard or any events.
> 
> Below are the errors logs
> 
> Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:32:02 ERROR Unexpected end of JSON input Nov 14, 2022 @ 06:33:50 INFO Wazuh dashboard index: .kibana Nov 14, 2022 @ 06:33:50 INFO App revision: 4306 Nov 14, 2022 @ 06:33:50 INFO Total RAM: 16009MB Nov 15, 2022 @ 05:29:02 INFO Report started Nov 15, 2022 @ 05:29:02 INFO 1 agents for API default Nov 15, 2022 @ 05:29:02 INFO Started to sanitize filters Nov 15, 2022 @ 05:29:02 INFO Started to render the time range and the filters Nov 15, 2022 @ 05:29:02 INFO Format date Mon Nov 14 2022 10:59:00 GMT+0000 (Coordinated Universal Time) Nov 15, 2022 @ 05:29:02 INFO Format date Tue Nov 15 2022 10:59:00 GMT+0000 (Coordinated Universal Time) Nov 15, 2022 @ 05:29:02 INFO Section agents and tab general, API is default. From 1668403740108 to 1668490140108. Filters manager.name: siem.sboxdc.com AND agent.id: 013. Index pattern wazuh-alerts-* Nov 15, 2022 @ 05:29:02 INFO 5 visualizations for tab general Nov 15, 2022 @ 05:29:02 INFO Item ID Wazuh-App-Agents-General-Top-5-PCI-DSS-Requirements, from agents and tab general Nov 15, 2022 @ 05:29:02 INFO Item ID Wazuh-App-Agents-General-Alerts, from agents and tab general Nov 15, 2022 @ 05:29:02 INFO Item ID Wazuh-App-Agents-General-Alert-groups-evolution, from agents and tab general Nov 15, 2022 @ 05:29:02 INFO Item ID Wazuh-App-Agents-General-Top-5-alerts, from agents and tab general Nov 15, 2022 @ 05:29:02 INFO Item ID Wazuh-App-Agents-General-Top-10-groups, from agents and tab general Nov 15, 2022 @ 05:29:02 INFO Started to render tables Nov 15, 2022 @ 05:29:10 INFO Fetching created reports Nov 15, 2022 @ 05:29:10 INFO Fetching created reports Nov 15, 2022 @ 05:37:40 ERROR {"title":"Bad Request","detail":"Cluster is not running, it might be disabled in `WAZUH_HOME/etc/ossec.conf`","remediation":"Please, visit the official documentation (https://documentation.wazuh.com/4.3/user-manual/configuring-cluster/index.html) to get more information about how to configure a cluster","error":3013} Nov 15, 2022 @ 11:54:23 INFO Wazuh dashboard index: .kibana Nov 15, 2022 @ 11:54:23 INFO App revision: 4306 Nov 15, 2022 @ 11:54:23 INFO Total RAM: 16009MB Dec 18, 2022 @ 18:00:00 INFO connect ECONNREFUSED 172.16.248.22:55000 Dec 18, 2022 @ 18:00:00 INFO connect ECONNREFUSED 172.16.248.22:55000 Dec 18, 2022 @ 18:00:00 ERROR connect ECONNREFUSED 0.0.0.0:9200 Dec 19, 2022 @ 00:55:01 INFO Wazuh dashboard index: .kibana Dec 19, 2022 @ 00:55:01 INFO App revision: 4306 Dec 19, 2022 @ 00:55:01 INFO Total RAM: 16009MB Jan 9, 2023 @ 07:42:36 INFO Wazuh dashboard index: .kibana Jan 9, 2023 @ 07:42:36 INFO App revision: 4306 Jan 9, 2023 @ 07:42:36 INFO Total RAM: 16009MB

can you help me fix the same error

RROR {"title":"Bad Request","detail":"Cluster is not running, it might be disabled in WAZUH_HOME/etc/ossec.conf","remediation":"Please, visit the official documentation (https://documentation.wazuh.com/4.3/user-manual/configuring-cluster/index.html) to get more information about how to configure a cluster","error":3013}
Nov 15, 2022 @ 11:54:23 INFO Wazuh dashboard index: .kibana
.......................................................................
Tks
