### ISSUE TITLE
ossec-logcollector stops when reading files

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#1589]
When we increase the file limit for `ossec-logcollector` it suddenly stops without _writing anything_ in the log or giving any error. If we execute `ossec-logcollector` with `gdb` we get the following information.

```
2018/10/08 16:52:40 ossec-logcollector: ERROR: (1103): Could not open file '/var/ossec/etc/internal_options.conf' due to [(24)-(Too many open files)].
2018/10/08 16:52:40 ossec-logcollector: CRITICAL: (2301): Definition not found for: 'wazuh.thread_stack_size'.
[Inferior 1 (process 16058) exited with code 01]
```

It usually dies around **1024 open files** so I think it must be a system limit for the process.

**Comment by albertomn86** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/1594
