### ISSUE TITLE
Release 4.4.0 - Beta 1 - Integration tests

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#15935]
| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `4.4-beta1` | | `v4.4.0-alpha2` | https://github.com/wazuh/wazuh/commit/90134ed0cc7a4479a216af6d10743bd013fe5700  |

We are going to check that the integration tests of the `4.4-beta1` branch of `wazuh-qa` work correctly using the `4.4.0-beta1` version of `wazuh`.

The tests will be performed both in the local environment and in Jenkins using `CentOS` as the manager OS. As for the agents, `Linux`, `Windows` and `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/15891

#### References
|      Color      | Status                                                          |
|:---------------:|:--------------------------------------------------------------- |
|       🟢        | All tests passed successfully                                   |
|       🟡        | All tests passed but there are some warnings, xfails or xpassed |
|       🔴        | Some tests have failures or errors                              |
|       🔵        | Test execution in progress                                      |
|       ⚫        | To Do                                                           |
|       🟠        | Tests failed and passed after relaunching it                    |
| :purple_circle: | All skipped                                                     |
| :brown_circle:  | Provision or Deployment failure                                 |

## Test Integration - Results
<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35556/"> :green_circle:  </a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/35557/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35557/"> :green_circle:  </a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/35558/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35558/"> :green_circle:  </a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35559/"> :green_circle:  </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35560/"> :green_circle:  </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35561/"> :green_circle:  </a></td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/35562/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35562/"> :green_circle:  </a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35563/"> :green_circle:  </a></td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/35558/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35558/"> :green_circle:  </a></td>
<td style="width: 97px;"><a href="https://ci.wazuh.info/job/Test_integration/35565/"> :green_circle:  </a></td>
<td style="width: 97px;" colspan="2"><a href="https://ci.wazuh.info/job/Test_integration/35565/"> :green_circle:  </a></td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35566/"> :green_circle:  </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;"> <a href="https://ci.wazuh.info/job/Test_integration/35568/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35568/"> :green_circle:  </a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35569/"> :green_circle:  </td>
<td style="width: 99px;"><a href="https://ci.wazuh.info/job/Test_integration/35597/"> :green_circle:  </td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35597/"> :green_circle:  </td>
<td style="width: 97px;"><a href="https://ci.wazuh.info/job/Test_integration/35597/"> :green_circle:  </td>
<td style="width: 97px;" colspan="2"><a href="https://ci.wazuh.info/job/Test_integration/35597/"> :green_circle:  </td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35571/"> :green_circle:  </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35572/"> :green_circle:  </a></td>
<td style="width: 79px;"><a href="https://ci.wazuh.info/job/Test_integration/35573/"> :green_circle:  </a></td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35574/"> :green_circle: </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35575/"> :green_circle: </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35576/"> :red_circle: </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35577/"> :red_circle: </a></td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;"><a href="https://ci.wazuh.info/job/Test_integration/35555//"> :green_circle:  </a></td>
<td style="width: 99px;">NA</td>

<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
</tbody>
</table>

**Comment by jmv74211** [comment]
Launched the test suites. Waiting for results...

**Comment by Rebits** [comment]
### Updated 17/01/2023

- **Rootcheck**: Failures from [previous nightly results](https://github.com/wazuh/wazuh-qa/issues/3747). WIP
- **VD**: WIP
- **Agent Logcollector**: Contacted @wazuh/cicd to solve macOS and Solaris agents provision.

**Comment by Rebits** [comment]
### Update 18/01/2023
- @wazuh/cicd solved the deployment error
- Logcollector ITs for agents were relaunched by @c-bordon. All tests pass as expected

**Comment by Rebits** [comment]
### Conclusions :red_circle: 

It has been detected errors in **rootcheck** and **vulnerability detector** modules
Both were related to the reported bug https://github.com/wazuh/wazuh/issues/15897, detected through the integration test report in nightly.

In addition, it has been asserted that IT passes again using the [proposed fix](https://github.com/wazuh/wazuh/pull/15936)
