### ISSUE TITLE
Release 4.4.0 - Beta 1 - WPK upgrade tests

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#15955]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|https://github.com/wazuh/wazuh/issues/15891|4.4.0|Beta 1|[v4.4.0-beta1](https://github.com/wazuh/wazuh/tree/v4.4.0-beta1)| https://github.com/wazuh/wazuh/issues/15529 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail, and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a ZIP or TXT file. This report can be used by the auditors to dig deeper into any possible failures and details.

## Tests

To evaluate this feature, it is necessary to test upgrading the agent and also the case when the upgrade fails (rollback). The `tree` command will be used to compare, before and after the upgrade/rollback process, and check that the presence, ownership, and permissions of the files and directories are expected.

Wazuh versions to test (Upgrade to the current agent version):
### Linux

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments
|----|-----|------|---------------|------------------|---------------|
|CentOS 8 / RHEL 8|3.13.6| ⚪ Skipped | | | |
|[CentOS 8 / RHEL 8](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1385423512)|4.3.10| :green_circle: Done | :green_circle: | :green_circle: | |
|CentOS 8 / RHEL 8|4.4.0| ⚪ Skipped | | | |
|CentOS Stream 9|3.13.6| ⚪ Skipped | | | |
|CentOS Stream 9|4.3.10| ⚪ Skipped | | | |
|CentOS Stream 9|4.4.0| ⚪ Skipped | | | |
|Ubuntu 22|3.13.6| ⚪ Skipped | | | |
|[Ubuntu 22](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1385410865)|4.3.10| :green_circle: Done | :yellow_circle: | :green_circle: | Known Warning https://github.com/wazuh/wazuh/issues/15613|
|Ubuntu 22|4.4.0| ⚪ Skipped | | | |
|openSUSE Tumbleweed|3.13.6| ⚪ Skipped | | | |
|openSUSE Tumbleweed|4.3.10| ⚪ Skipped | | | |
|openSUSE Tumbleweed|4.4.0| ⚪ Skipped | | | |
|Amazon Linux 2|3.13.6| ⚪ Skipped | | | |
|Amazon Linux 2|4.3.10| ⚪ Skipped | | | |
|Amazon Linux 2|4.4.0| ⚪ Skipped | | | |

### Windows

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments|
|----|-----|------|---------------|------------------|---------|
|Server 2012 R2|3.13.6| ⚪ Skipped | | | |
|[Server 2012 R2](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1386020205)|4.3.10| :green_circle: Done | :green_circle: | :green_circle: | |
|[Server 2012 R2](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1386020205)|4.4.0| :green_circle: Done | :green_circle: | :green_circle: | |
|Windows 11|3.13.6| ⚪ Skipped | | | |
|Windows 11|4.3.10| ⚪ Skipped | | | |
|Windows 11|4.4.0| ⚪ Skipped | | | |
|Server 2022|3.13.6| ⚪ Skipped | | | |
|[Server 2022](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1386021677)|4.3.10| :green_circle: Done | :green_circle: | :green_circle: | |
|[Server 2022](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1386021677)|4.4.0| :green_circle: Done | :green_circle: | :green_circle: | |

### macOS

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments
|----|-----------|--------|-------|------------------|----------|
|[Monterey](https://github.com/wazuh/wazuh/issues/15955#issuecomment-1385665812)|4.3.10| :green_circle: Done | :green_circle: | :green_circle: | |
|Monterey|4.4.0| ⚪ Skipped | | | |

## Findings

https://github.com/wazuh/wazuh/issues/15613, known issue found during the rollback in Ubuntu 22.04 due to the use of `chkconfig`, reported at the previous stage.

## Auditors' validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @chemamartinez
- [x] @vikman90 
- [x] @davidjiglesias

**Comment by mjcr99** [comment]
# TEST: Ubuntu 22 🟢 

## From Wazuh-Agent v4.3.10
###  UPGRADE FAIL

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] ~Wazuh as service is enabled `chkconfig --list`~ 
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

###  UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**
[Report.Ubuntu22.v4.3.10.zip](https://github.com/wazuh/wazuh/files/10435301/Report.Ubuntu22.v4.3.10.zip)

**Comment by mjcr99** [comment]
# TEST: CentOS 8 :green_circle:

## From Wazuh-Agent v4.3.10
###  UPGRADE FAIL

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
      - `/`
      - `/var`
      - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
      - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [x] ~Wazuh as service is enabled `chkconfig --list`~ (`chkconfig` unavailable)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [x] Restore SELinux policies (`semodule -l | grep -i wazuh`)

###  UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**
[Report.Centos8.v.4.3.10.zip](https://github.com/wazuh/wazuh/files/10435373/Report.Centos8.v.4.3.10.zip)

**Comment by chemamartinez** [comment]
# TEST: macOS Monterey :green_circle: 

## From Wazuh-Agent v4.3.10

### UPGRADE FAIL

- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.

### UPGRADE OK

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.

**Upgrade reports**
[macOS_wpk_test_v4.4.0-beta1.tar.gz](https://github.com/wazuh/wazuh/files/10437033/macOS_wpk_test_v4.4.0-beta1.tar.gz)

**Comment by GabrielEValenzuela** [comment]
# TEST: Windows Server 2012 R2 🟢 

## From Wazuh-Agent v4.3.10

### UPGRADE FAIL  🟢 
- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.


**Upgrade reports**
[Download v4.3.10 Windows reports](https://github.com/wazuh/wazuh/files/10439198/WSVR2012-Update4.4.0Fail.zip)


### UPGRADE OK 🟢

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.4.0
- [x] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.3.10 Windows reports] (https://github.com/wazuh/wazuh/files/10439201/WSVR2012-Update4.4.0Success.zip)

**Comment by GabrielEValenzuela** [comment]
# TEST: Windows Server 2022 🟢 

## From Wazuh-Agent v4.3.10

### UPGRADE FAIL  🟢 
- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.


**Upgrade reports**
[Download v4.3.10 Windows reports](https://github.com/wazuh/wazuh/files/10439209/WSVR2022-Update4.4.0Fail.zip)

### UPGRADE OK 🟢

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.4.0
- [x] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.3.10 Windows reports](https://github.com/wazuh/wazuh/files/10439212/WSVR2022-Update4.4.0Success.zip)
