### ISSUE TITLE
ossec-authd passwords never match

### ISSUE THREAD

**Issue by mikeshultz** [wazuh/wazuh#160]
Following [the documentation on registering agents using a password](https://documentation.wazuh.com/current/user-manual/agents/registering-agents/register-agent-authd.html) I am not able to get a client to authenticate.  No matter what, I always get this from `ossec-authd`: 

    # /var/ossec/bin/ossec-authd -P
    2017/07/27 05:11:07 ossec-authd: INFO: Started (pid: 7918).
    2017/07/27 05:11:07 Accepting connections. Using password specified on file: /var/ossec/etc/authd.pass
    2017/07/27 05:11:10 ossec-authd: INFO: New connection from 192.168.5.1
    2017/07/27 05:11:10 ossec-authd: ERROR: Invalid password provided by 192.168.5.1. Closing connection.

And this from `agent-auth`:

    # /var/ossec/bin/agent-auth -m 192.168.5.2
    2017/07/27 05:11:10 agent-auth: INFO: Started (pid: 1148).
    INFO: Using password specified on file: /var/ossec/etc/authd.pass
    INFO: Connected to 192.168.5.2:1515
    INFO: Using agent name as: server.example.com
    INFO: Send request to manager. Waiting for reply.
    ERROR: Unable to create key. Either wrong password or connection not accepted by the manager.
    INFO: Connection closed.

The `md5sum` of each `authd.pass` is identical, and yet it still does not work.  Is the server-side password supposed to be hashed or something?

**Comment by vikman90** [comment]
Hi @mikeshultz,

you are right: there are two problems in `agent-auth` when reading passwords from a file:

- The final line-ending is not removed.
- The password in memory is overwritten accidentally by the payload.

These issues were solved in the manager's `ossec-authd` (https://github.com/wazuh/wazuh/commit/992977e16a5533db7bd23cb8ea112ae3fc47a953) but not in the client part. 

We have just applied that fix in the client's `agent-auth` (https://github.com/wazuh/wazuh/commit/0b7b9a8d948d0d43c5da9142edb9baf6db9aabf5) and it will be available in the next version 2.1.

In the meantime, I suggest you to use the client's password authentication by using this command:

```
/var/ossec/bin/agent-auth -m 192.168.5.2 -P $(cat /var/ossec/etc/authd.pass)
```

Thank you very much for your feedback and helping us to catch this bug.
Best regards.
