### ISSUE TITLE
SCA files have fields like title, remediation, etc starting with blank space

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#16004]
As shown in the code snippet below: 
https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/centos/7/cis_centos7_linux.yml#L3494-L3496
the title starts with a blank space and it should be removed. 

It was detected also: 
https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/amazon/cis_amazon_linux_2.yml#L908-L910

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/amazon/cis_amazon_linux_2.yml#L923-L925

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/amazon/cis_amazon_linux_2.yml#L3124-L3126

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/applications/cis_iis_10.yml#L108-L109

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/applications/cis_iis_10.yml#L211-#L212

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/ruleset/sca/applications/cis_iis_10.yml#L246-L247

And a lot more. Instead of enumerating all occurrences, I suggest the person who takes this issue use the searcher and find all occurrences of `title: " ` , ` description: " `, ` rationale: " ` and ` remediation: " `

This has appearance consequences like this

![image](https://user-images.githubusercontent.com/3830293/214557310-a5334612-35f2-433c-bfa0-a7ea9c8b6c1b.png)

**Comment by lchico** [comment]
# Upadate

Most of these changes have already been applied. On the master branch, we only have the following pending changes:

```
Wazuh/Github/platform/app/wazuh [master|…2⚑ 5] 
20:14 $ grep -ir "\"\sEnsure" ruleset/*
ruleset/mitre/enterprise-attack.json:      "description": " Ensure extensions that are installed are the intended ones as many malicious extensions will masquerade as legitimate ones.",
ruleset/sca/applications/cis_iis_10.yml:    title: " Ensure WebDav feature is disabled"
ruleset/sca/applications/cis_iis_10.yml:  #    title: " Ensure 'httpcookie' mode is configured for session state"
ruleset/sca/applications/cis_iis_10.yml:    title: " Ensure global .NET trust level is configured"

```
