### ISSUE TITLE
Update Channel for Windows Terminal Services Gateway Rules

### ISSUE THREAD

**Issue by corvar** [wazuh/wazuh#16014]
|Wazuh version| Component | Action type |
|---| --- | --- |
|   4.3.10-1 | Rules/Decoders | Error |

## Description
Rule ID 64104 lists the channel name for Microsoft Windows TerminalServices Gateway events incorrectly as Microsoft-Windows-TerminalServices, the correct channel should be Microsoft-Windows-TerminalServices-Gateway/Operational

### Service/Product/Module
0620-win-generic_rules.xml
Windows Event Channel logs from provider Microsoft-Windows-TerminalServices-Gateway

### Current results
{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-Gateway","providerGuid":"{4D5AE6A1-C7B8-3E6D-B840-4D8029342E1B}","eventID":"200","version":"0","level":"4","task":"2","opcode":"30","keywords":"0x4020000001000000","systemTime":"2023-01-25T20:56:39.141308000Z","eventRecordID":"84771","processID":"4672","threadID":"1996","channel":"Microsoft-Windows-TerminalServices-Gateway/Operational","computer":"server.domain.com","severityValue":"INFORMATION","message":"\"The user \"DOM\\user\", on client computer \"172.16.63.71\", met connection authorization policy requirements and was therefore authorized to access the RD Gateway server. The authentication method used was: \"NTLM\" and connection protocol used: \"HTTP\".\""},"eventInfo":{"username":"DOM\\\\user","ipAddress":"172.16.93.71","authType":"NTLM","connectionProtocol":"HTTP","errorCode":"0"}}}

**Phase 1: Completed pre-decoding.

**Phase 2: Completed decoding.
        name: 'json'
        win.eventInfo.authType: 'NTLM'
        win.eventInfo.connectionProtocol: 'HTTP'
        win.eventInfo.errorCode: '0'
        win.eventInfo.ipAddress: '172.16.93.71'
        win.eventInfo.username: 'DOM\\user'
        win.system.channel: 'Microsoft-Windows-TerminalServices-Gateway/Operational'
        win.system.computer: 'server.domain.com'
        win.system.eventID: '200'
        win.system.eventRecordID: '84771'
        win.system.keywords: '0x4020000001000000'
        win.system.level: '4'
        win.system.message: '"The user "DOM\user", on client computer "172.16.63.71", met connection authorization policy requirements and was therefore authorized to access the RD Gateway server. The authentication method used was: "NTLM" and connection protocol used: "HTTP"."'
        win.system.opcode: '30'
        win.system.processID: '4672'
        win.system.providerGuid: '{4D5AE6A1-C7B8-3E6D-B840-4D8029342E1B}'
        win.system.providerName: 'Microsoft-Windows-TerminalServices-Gateway'
        win.system.severityValue: 'INFORMATION'
        win.system.systemTime: '2023-01-25T20:56:39.141308000Z'
        win.system.task: '2'
        win.system.threadID: '1996'
        win.system.version: '0'

**Phase 3: Completed filtering (rules).
        id: '60009'
        level: '0'
        description: 'Windows informational event.'
        groups: '['windows']'
        firedtimes: '1'
        mail: 'False'

### Expected results
{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-Gateway","providerGuid":"{4D5AE6A1-C7B8-3E6D-B840-4D8029342E1B}","eventID":"200","version":"0","level":"4","task":"2","opcode":"30","keywords":"0x4020000001000000","systemTime":"2023-01-25T20:56:39.141308000Z","eventRecordID":"84771","processID":"4672","threadID":"1996","channel":"Microsoft-Windows-TerminalServices-Gateway/Operational","computer":"server.domain.com","severityValue":"INFORMATION","message":"\"The user \"DOM\\user\", on client computer \"172.16.63.71\", met connection authorization policy requirements and was therefore authorized to access the RD Gateway server. The authentication method used was: \"NTLM\" and connection protocol used: \"HTTP\".\""},"eventInfo":{"username":"DOM\\\\user","ipAddress":"172.16.93.71","authType":"NTLM","connectionProtocol":"HTTP","errorCode":"0"}}}

**Phase 1: Completed pre-decoding.

**Phase 2: Completed decoding.
        name: 'json'
        win.eventInfo.authType: 'NTLM'
        win.eventInfo.connectionProtocol: 'HTTP'
        win.eventInfo.errorCode: '0'
        win.eventInfo.ipAddress: '172.16.93.71'
        win.eventInfo.username: 'DOM\\user'
        win.system.channel: 'Microsoft-Windows-TerminalServices-Gateway/Operational'
        win.system.computer: 'server.domain.com'
        win.system.eventID: '200'
        win.system.eventRecordID: '84771'
        win.system.keywords: '0x4020000001000000'
        win.system.level: '4'
        win.system.message: '"The user "DOM\user", on client computer "172.16.63.71", met connection authorization policy requirements and was therefore authorized to access the RD Gateway server. The authentication method used was: "NTLM" and connection protocol used: "HTTP"."'
        win.system.opcode: '30'
        win.system.processID: '4672'
        win.system.providerGuid: '{4D5AE6A1-C7B8-3E6D-B840-4D8029342E1B}'
        win.system.providerName: 'Microsoft-Windows-TerminalServices-Gateway'
        win.system.severityValue: 'INFORMATION'
        win.system.systemTime: '2023-01-25T20:56:39.141308000Z'
        win.system.task: '2'
        win.system.threadID: '1996'
        win.system.version: '0'

**Phase 3: Completed filtering (rules).
        id: '64105'
        level: '3'
        description: 'TS Gateway login success'
        groups: '['windows', 'authentication_success']'
        firedtimes: '1'
        gdpr: '['IV_32.2']'
        gpg13: '['7.1', '7.2']'
        hipaa: '['164.312.b']'
        mail: 'False'
        mitre.id: '['T1078']'
        mitre.tactic: '['Defense Evasion', 'Persistence', 'Privilege Escalation', 'Initial Access']'
        mitre.technique: '['Valid Accounts']'
        nist_800_53: '['AU.14', 'AC.7']'
        pci_dss: '['10.2.5']'
        tsc: '['CC6.8', 'CC7.2', 'CC7.3']'
**Alert to be generated.

### Log source / integration
Windows EventChannel

### Log reference
https://github.com/wazuh/wazuh-ruleset/blob/master/decoders/0380-windows_decoders.xml
Even the Wazuh Decoder references the correct channel

### Log examples
{"win":{"system":{"providerName":"Microsoft-Windows-TerminalServices-Gateway","providerGuid":"{4D5AE6A1-C7B8-3E6D-B840-4D8029342E1B}","eventID":"200","version":"0","level":"4","task":"2","opcode":"30","keywords":"0x4020000001000000","systemTime":"2023-01-25T20:56:39.141308000Z","eventRecordID":"84771","processID":"4672","threadID":"1996","channel":"Microsoft-Windows-TerminalServices-Gateway/Operational","computer":"server.domain.com","severityValue":"INFORMATION","message":"\"The user \"DOM\\user\", on client computer \"172.16.63.71\", met connection authorization policy requirements and was therefore authorized to access the RD Gateway server. The authentication method used was: \"NTLM\" and connection protocol used: \"HTTP\".\""},"eventInfo":{"username":"DOM\\\\user","ipAddress":"172.16.93.71","authType":"NTLM","connectionProtocol":"HTTP","errorCode":"0"}}}

### Threats and compliance
None

**Comment by fabamatic** [comment]
Thanks for the detailed report. PR for this issue: https://github.com/wazuh/wazuh/pull/16029

**Comment by ooniagbi** [comment]
Merging to 4.8.2

## Ruleset test results

|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1417   |   4420   |  32.06%  |
| Decoders |   125    |   170    |  73.53%  |


|          File           |  Passed  |  Failed  |  Status  |
|        --------         | -------- | -------- | -------- |
|./tests/proftpd.ini      |    7     |    0     |   ✅    |
|./tests/exim.ini         |    7     |    0     |   ✅    |
|./tests/squid_rules.ini  |    2     |    0     |   ✅    |
|./tests/sysmon_eid_3.ini |    10    |    0     |   ✅    |
|./tests/amazon_sec_lake.ini|    20    |    0     |   ✅    |
|./tests/checkpoint_smart1.ini|    18    |    0     |   ✅    |
|./tests/iptables.ini     |    9     |    0     |   ✅    |
|./tests/sysmon_eid_10.ini|    4     |    0     |   ✅    |
|./tests/SonicWall.ini    |    11    |    0     |   ✅    |
|./tests/panda_paps.ini   |    8     |    0     |   ✅    |
|./tests/fortiauth.ini    |    4     |    0     |   ✅    |
|./tests/openldap.ini     |    9     |    0     |   ✅    |
|./tests/f5_big_ip.ini    |    48    |    0     |   ✅    |
|./tests/sophos.ini       |    8     |    0     |   ✅    |
|./tests/opensmtpd.ini    |    7     |    0     |   ✅    |
|./tests/netscreen.ini    |    4     |    0     |   ✅    |
|./tests/rsh.ini          |    2     |    0     |   ✅    |
|./tests/arbor.ini        |    2     |    0     |   ✅    |
|./tests/web_rules.ini    |    10    |    0     |   ✅    |
|./tests/exchange.ini     |    2     |    0     |   ✅    |
|./tests/vuln_detector.ini|    2     |    0     |   ✅    |
|./tests/win-generic_rules.ini|    1     |    0     |   ✅    |
|./tests/sysmon_eid_7.ini |    6     |    0     |   ✅    |
|./tests/macos.ini        |    11    |    0     |   ✅    |
|./tests/samba.ini        |    4     |    0     |   ✅    |
|./tests/apparmor.ini     |    5     |    0     |   ✅    |
|./tests/test_osmatch_regex.ini|    6     |    0     |   ✅    |
|./tests/test_features.ini|    7     |    0     |   ✅    |
|./tests/pam.ini          |    5     |    0     |   ✅    |
|./tests/apache.ini       |    12    |    0     |   ✅    |
|./tests/fireeye.ini      |    3     |    0     |   ✅    |
|./tests/sysmon.ini       |    25    |    0     |   ✅    |
|./tests/dovecot.ini      |    15    |    0     |   ✅    |
|./tests/web_appsec.ini   |    31    |    0     |   ✅    |
|./tests/nextcloud.ini    |    8     |    0     |   ✅    |
|./tests/kernel_usb.ini   |    6     |    0     |   ✅    |
|./tests/paloalto.ini     |    16    |    0     |   ✅    |
|./tests/sysmon_eid_13.ini|    9     |    0     |   ✅    |
|./tests/ossec.ini        |    5     |    0     |   ✅    |
|./tests/test_osregex_regex.ini|    28    |    0     |   ✅    |
|./tests/cisco_ftd.ini    |    42    |    0     |   ✅    |
|./tests/sysmon_eid_1.ini |    63    |    0     |   ✅    |
|./tests/github.ini       |   324    |    0     |   ✅    |
|./tests/test_pcre2_regex.ini|    33    |    0     |   ✅    |
|./tests/named.ini        |    5     |    0     |   ✅    |
|./tests/powershell.ini   |    32    |    0     |   ✅    |
|./tests/openvpn_ldap.ini |    2     |    0     |   ✅    |
|./tests/sysmon_eid_8.ini |    4     |    0     |   ✅    |
|./tests/cloudflare-waf.ini|    13    |    0     |   ✅    |
|./tests/huawei_usg.ini   |    3     |    0     |   ✅    |
|./tests/eset.ini         |    8     |    0     |   ✅    |
|./tests/test_expr_negation.ini|    56    |    0     |   ✅    |
|./tests/gcp.ini          |    31    |    0     |   ✅    |
|./tests/cpanel.ini       |    7     |    0     |   ✅    |
|./tests/pfsense.ini      |    2     |    0     |   ✅    |
|./tests/cisco_asa.ini    |    88    |    0     |   ✅    |
|./tests/systemd.ini      |    2     |    0     |   ✅    |
|./tests/nginx.ini        |    12    |    0     |   ✅    |
|./tests/sysmon_eid_11.ini|    28    |    0     |   ✅    |
|./tests/cisco_ios.ini    |    17    |    0     |   ✅    |
|./tests/pix.ini          |    22    |    0     |   ✅    |
|./tests/php.ini          |    2     |    0     |   ✅    |
|./tests/office365.ini    |   128    |    0     |   ✅    |
|./tests/fortigate.ini    |    45    |    0     |   ✅    |
|./tests/fortimail.ini    |    6     |    0     |   ✅    |
|./tests/audit_scp.ini    |    8     |    0     |   ✅    |
|./tests/win_application.ini|    0     |    0     |   ✅    |
|./tests/fortiddos.ini    |    3     |    0     |   ✅    |
|./tests/cimserver.ini    |    2     |    0     |   ✅    |
|./tests/freepbx.ini      |    6     |    0     |   ✅    |
|./tests/overwrite.ini    |    10    |    0     |   ✅    |
|./tests/sshd.ini         |    49    |    0     |   ✅    |
|./tests/win_event_channel.ini|    8     |    0     |   ✅    |
|./tests/gitlab.ini       |    27    |    0     |   ✅    |
|./tests/windows_baseline_intrusion_detection.ini|    29    |    0     |   ✅    |
|./tests/glpi.ini         |    3     |    0     |   ✅    |
|./tests/api.ini          |    21    |    0     |   ✅    |
|./tests/dropbear.ini     |    3     |    0     |   ✅    |
|./tests/win_security.ini |    9     |    0     |   ✅    |
|./tests/firewalld.ini    |    2     |    0     |   ✅    |
|./tests/mailscanner.ini  |    1     |    0     |   ✅    |
|./tests/owlh.ini         |    4     |    0     |   ✅    |
|./tests/sysmon_eid_20.ini|    2     |    0     |   ✅    |
|./tests/auditd.ini       |    31    |    0     |   ✅    |
|./tests/mcafee_epo.ini   |    1     |    0     |   ✅    |
|./tests/doas.ini         |    4     |    0     |   ✅    |
|./tests/junos.ini        |    3     |    0     |   ✅    |
|./tests/sudo.ini         |    8     |    0     |   ✅    |
|./tests/syslog.ini       |    6     |    0     |   ✅    |
|./tests/sophos_fw.ini    |    10    |    0     |   ✅    |
|./tests/vsftpd.ini       |    4     |    0     |   ✅    |
|./tests/postfix.ini      |    2     |    0     |   ✅    |
|./tests/modsecurity.ini  |    6     |    0     |   ✅    |
|./tests/su.ini           |    5     |    0     |   ✅    |
|./tests/unbound.ini      |    0     |    0     |   ✅    |
|./tests/aws_s3_access.ini|    10    |    0     |   ✅    |
|./tests/test_static_filters.ini|    28    |    0     |   ✅    |
|./tests/oscap.ini        |    32    |    0     |   ✅    |

**Comment by ooniagbi** [comment]
Merged https://github.com/wazuh/wazuh/pull/22408
