### ISSUE TITLE
Syscheck does not detect integrity changes from some files in the AIX manager

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16025]
|Wazuh version| Component | Install type|Install method|Platform|
|---|---|---|---| ---|
| 3.1  | Syscheck |  Manager | Sources | AIX 7.1 |

| Wazuh QA branch | Development |
|--- | ---- |
| https://github.com/wazuh/wazuh-qa/issues/3678 |  https://github.com/wazuh/wazuh/pull/15959 |

### Description 

During manual testing of the AIX manager, it has been detected that the syscheck module ignores files if a restart is performed during a scan

### Steps to reproduce
In order to make syscheck ignore certain files is required to restart the module when during a scan.

- Configure syscheck module
<details>

<summary> <code> ossec.conf </code> </summary>

```
  <syscheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <directories check_sha1sum="yes" report_changes="yes">/tmp/syscheck-testing</directories>
    <directories check_sha1sum="yes" report_changes="yes">/tmp/syscheck-testing2</directories>
    <directories check_sha1sum="yes" report_changes="yes">/tmp/syscheck-testing3</directories>
    <scan_on_start>yes</scan_on_start>
  </syscheck>
```

</details>

- Create monitored directories and create a file in each one
```
mkdir /tmp/syscheck-testing
mkdir /tmp/syscheck-testing2
mkdir /tmp/syscheck-testing3
echo "Testing" >> /tmp/syscheck-testing/example.log; echo "Testing" >> /tmp/syscheck-testing2/example.log; echo "Testing" >> /tmp/syscheck-testing3/example.log;
```
- Restart the manager
- Wait for the first scan
- Edit all files and wait until syscheck generates expected alerts
```
echo "Testing" >> /tmp/syscheck-testing/example.log; echo "Testing" >> /tmp/syscheck-testing2/example.log; echo "Testing" >> /tmp/syscheck-testing3/example.log;
```

**Alerts**
```
...
Rule: 551 (level 7) -> 'Integrity checksum changed again.'
Integrity checksum changed for: '/tmp/syscheck-testing3/example.log'
....
Rule: 551 (level 7) -> 'Integrity checksum changed again.'
Integrity checksum changed for: '/tmp/syscheck-testing2/example.log'
....
Rule: 551 (level 7) -> 'Integrity checksum changed again.'
Integrity checksum changed for: '/tmp/syscheck-testing/example.log'
```
- Restart the manager
- Wait until syscheck database pre-scan: `Starting syscheck database (pre-scan).`
- Restart again the manager
- Edit again the files
```
echo "Testing" >> /tmp/syscheck-testing/example.log; echo "Testing" >> /tmp/syscheck-testing2/example.log; echo "Testing" >> /tmp/syscheck-testing3/example.log;
```
- Check how only some of them (or none) has triggered an alert

### Evidence
[syscheck_error.webm](https://user-images.githubusercontent.com/11089305/214884865-ccf7a0b8-2519-4558-b274-a5b1c30cbe43.webm)

**Comment by MarcelKemp** [comment]
No development is planned for `v3.1`, as this issue is fixed in more recent versions (such as `v4.3`).
