### ISSUE TITLE
Syscheck shows an invalid size in case of disabling check_size in the AIX manager

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16024]
|Wazuh version| Component | Install type|Install method|Platform|
|---|---|---|---| ---|
| 3.1  | Syscheck |  Manager | Sources | AIX 7.1 |

| Wazuh QA branch | Development |
|--- | ---- |
| https://github.com/wazuh/wazuh-qa/issues/3678 |  https://github.com/wazuh/wazuh/pull/15959 |

### Description 

During manual testing of the AIX manager, it has been detected that the syscheck module shows an incorrect new size value (`0`) when `check_size` is not enabled:

```
** Alert 1674742077.17191: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,
2023 Jan 26 08:07:57 wa-1016-second-try->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/tmp/example/testing-last.log'
Old sha1sum was: '165840936070cc2efcd03e992000aa05cf5e2470'
New sha1sum is : '5ad8932d8e64f111be78d10af6e615421921da97'
What changed:
2a3,4
> dfasf
> dfasf

File: /tmp/example/testing-last.log
New size: 0
New user:  (0)
New group:  (0)
New MD5: xxx
Old SHA1: 165840936070cc2efcd03e992000aa05cf5e2470
New SHA1: 5ad8932d8e64f111be78d10af6e615421921da97
```

### How to reproduce

- Configure syscheck directory monitoring with `check_sha1sum` enabled.

<details>

<summary> <code> ossec.conf </code> </summary>

```
  <syscheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <directories check_sha1sum="yes" report_changes="yes">/tmp/example</directories>
    <scan_on_start>yes</scan_on_start>
  </syscheck>
```
</details>

- Create a file in the monitored directory: `echo "Testing" >> /tmp/example/testing-last.log`
- Restart the manager
- Check that the integrity checksum change alert has a wrong new size value
```
** Alert 1674742077.17191: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,
2023 Jan 26 08:07:57 wa-1016-second-try->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/tmp/example/testing-last.log'
Old sha1sum was: '165840936070cc2efcd03e992000aa05cf5e2470'
New sha1sum is : '5ad8932d8e64f111be78d10af6e615421921da97'
What changed:
2a3,4
> Testing

File: /tmp/example/testing-last.log
New size: 0
New user:  (0)
New group:  (0)
New MD5: xxx
Old SHA1: 165840936070cc2efcd03e992000aa05cf5e2470
New SHA1: 5ad8932d8e64f111be78d10af6e615421921da97
```

**Comment by MarcelKemp** [comment]
No development is planned for `v3.1`, as this issue is fixed in more recent versions (such as `v4.3`).
