### ISSUE TITLE
AIX manager try to open persistently the agent-groups file

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16021]
|Wazuh version| Component | Install type|Install method|Platform|
|---|---|---|---| ---|
| 3.1  | Modulesd |  Manager | Sources | AIX 7.1 |

| Wazuh QA branch | Development |
|--- | ---- |
| https://github.com/wazuh/wazuh-qa/issues/3678 |  https://github.com/wazuh/wazuh/pull/15959 |

### Description 

During manual testing of the AIX manager, it has been detected a persistent modules error:

```
2023/01/26 05:32:25 wazuh-modulesd:database: ERROR: Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.
2023/01/26 05:33:25 wazuh-modulesd:database: ERROR: Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.
2023/01/26 05:34:25 wazuh-modulesd:database: ERROR: Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.
2023/01/26 05:35:25 wazuh-modulesd:database: ERROR: Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.
2023/01/26 05:36:25 wazuh-modulesd:database: ERROR: Couldn't open directory '/var/ossec/queue/agent-groups': No such file or directory.
```

> **Note**
> Authd was disabled at installation time

**Comment by vikman90** [comment]
We decided not to fix this in 3.1 as it works in 4.3.
