### ISSUE TITLE
AIX agent include /boot directory in default syscheck configuration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16022]
|Wazuh version| Component | Install type|Install method|Platform|
|---|---|---|---| ---|
| 3.1  | Syscheck |  Agent | Sources | AIX 7.1 |

| Wazuh QA branch | Development |
|--- | ---- |
| https://github.com/wazuh/wazuh-qa/issues/3678 |  https://github.com/wazuh/wazuh/pull/15959 |
### Description 

During manual testing of the AIX manager, it has been detected the following warning
```
2023/01/23 10:39:21 ossec-syscheckd: WARNING: Error opening directory: '/boot': No such file or directory
```

AIX environment does not have by default /boot directory. This should be removed from the default AIX configuration.

**Comment by vikman90** [comment]
We decided to apply this as an improvement in a production version (> 4.4.1).
