### ISSUE TITLE
Command timeout overtaken with infinite timeout

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1603]
## Bug report

**OS**
_Ubuntu 18.04_

**Wazuh version**
_3.7.0-3704_

**Install type**
_manager_

**Install method**
_packages

Bug description
----------------
Executing a script that contains the next lines:

```
#!/bin/bash

while true; do
        sleep 1
        echo "writing to file" >> /home/user/test/log
        echo "--" >> /home/user/test/log
done
```
with wodle command configured as:
```
<wodle name="command">
  <disabled>no</disabled>
  <tag>test1</tag>
  <command>/bin/bash /home/user/test/test.sh</command>
  <interval>30s</interval>
  <ignore_output>yes</ignore_output>
  <run_on_start>yes</run_on_start>
  <timeout>0</timeout>
</wodle>
```
shows the next message at the `ossec.log` file:
```
2018/10/09 15:14:48 wazuh-modulesd:command: ERROR: test1: Timeout overtaken. You can modify your command timeout at ossec.conf. Exiting...
```

Taking into account that '0' seconds means an infinite timeout, this message should not be shown and the script should have kept running.

**Comment by chemamartinez** [comment]
Fixed at #1604
