### ISSUE TITLE
Implement the metrics module and integrate it with other modules

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16031]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description
The objective of the this task is Implement the structure of the metrics module, and integrate it with other modules, in the engine. 

## DoD
- [x] Implement first iteration of the metrics module.
  - [x] Implement the most convenient method according to what was analyzed in issue #15993, it can be a dependency injection or it can work as a singleton with enabling macros.
  - [x] Define a clear interface in order to be able to implement the indicators in the various modules.
    - Commands:
      - [x] dump
      - [x] enable `<metricName>` [true | false]  - allow to enable or disable acquisition metric.
      - [x] list - print registered metrics with following format, name: `"cont1" status: "enable|disable" type: "counter" value: "12"`
      - [x] get `<metricName>` - print a single metric as pretty json.
  - [x] Able to Collect at least a signal from any module.
- [x] Update Documentation.

**Comment by NahuFigueroa97** [comment]
##   :green_circle: Test: Wazuh WUI one-liner deploy, predefined group

**Comment by soynof** [comment]
##   :green_circle: Metrics module functionality

#### :green_circle: Dump command

- When no measurement has been made using the etrics module, the dump command returns the following.

![Captura desde 2023-03-07 11-51-25](https://user-images.githubusercontent.com/63238635/223458021-818e038e-5207-4260-bb77-5303662bb01d.png)

- We add a metric in some module, in this case in the catalog when a validation is made:

![Captura desde 2023-03-07 11-55-09](https://user-images.githubusercontent.com/63238635/223459217-eb243b55-711d-42e4-81f2-cfbc5d19f595.png)

- If we now execute a query to the actalogue to validate a decoder:

```
/var/ossec/engine/wazuh-engine catalog validate decoder/redis/0 < /home/vagrant/engine/wazuh/src/engine/ruleset/decoders/redis/redis.yml
```
- If we run the dump command again we will now see an increment in the counter:

```
/var/ossec/engine/wazuh-engine metrics dump
[{"scope":"CountExample","schema":"","version":"","records":[{"start_time":"Tue Mar  7 14:46:09 2023","instrument_name":"CountExample_counter","instrument_description":"some description","unit":"some unit","attributes":[{"type":"SumPointData","value":1}]}]}]

```
#### :green_circle: Enable command

- With this command we disable some instrument by its name
```
/var/ossec/engine/wazuh-engine metrics enable "CountExample" false
```

- if the instrument name does not exist it throws an error:
```
/var/ossec/engine/wazuh-engine metrics enable "CountExampleNotExist" true
The Instrument CountExampleNotExist has not been created.

```
