### ISSUE TITLE
can't remove sample Data

### ISSUE THREAD

**Issue by davidalfredjr** [wazuh/wazuh#16041]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Manager | Manager | Packages | Ubuntu 22.04.1 LTS |

WAZUH sample data remove successfully in Dashboard but after changing tab or refreshing it get back

log for successful remove :

Jan 29, 2023 @ 23:46:50  DEBUG  Deleted wazuh-alerts-*sample-security index
Jan 29, 2023 @ 23:46:51  DEBUG  Getting host default
Jan 29, 2023 @ 23:46:51  DEBUG  Getting hosts
Jan 29, 2023 @ 23:46:51  DEBUG  Deleted wazuh-alerts-*sample-auditing-policy-monitoring index
Jan 29, 2023 @ 23:46:52  DEBUG  Getting host default
Jan 29, 2023 @ 23:46:52  DEBUG  Getting hosts
Jan 29, 2023 @ 23:46:52  DEBUG  Deleted wazuh-alerts-*sample-threat-detection index

![Capture](https://user-images.githubusercontent.com/123901751/215353712-425bd665-2db5-4604-a03e-7019d2ee871a.PNG)
![Capture2](https://user-images.githubusercontent.com/123901751/215353715-70a801c8-120f-454a-b5a0-cffcdb73ee25.PNG)

**Comment by s-ocando** [comment]
Hi @davidalfredjr,
 
I've tried to reproduce this behavior without success. To analyze this further, can you please confirm if you are using Wazuh dashboard or Kibana? You can find this information under the main **Wazuh app menu** > **Settings** > **About**.

Also, are you using the default `admin` user or a custom one?

If you're using a custom user then please share the user permissions.

**Comment by davidalfredjr** [comment]
Hi s-ocando

thanks for reply

It's on Wazuh dashbaord

App version: 4.3.10
App revision: 4311
Install date: Jan 27, 2023 @ 13:58:40.635

I use default admin

**Comment by s-ocando** [comment]
Hi @davidalfredjr, 

Try removing the sample data using Dev Tools. Go to the top left menu ☰  and select **Dev Tools** under **Management**.

<img src="https://user-images.githubusercontent.com/61882981/216011925-46026d74-7cda-4ed1-9f2f-60a20536fdca.png" width="300" >


Delete the sample indices:
```
DELETE /wazuh-alerts-4.x-sample-security
DELETE /wazuh-alerts-4.x-sample-auditing-policy-monitoring
DELETE /wazuh-alerts-4.x-sample-threat-detection
```
![image](https://user-images.githubusercontent.com/61882981/216012418-9a9f501e-d669-46e5-b960-325087b330f3.png)


Let us know if this solves the problem. In case you have trouble erasing the indices please share the call output.
