### ISSUE TITLE
Fix wazuh-db race condition

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#16045]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-beta1 | WazuhDB/Remoted | Manager | Packages/Sources | Linux |

### Description
	
It is necessary to know the implications of removing the use of the ```belongs``` and ```group``` tables in the worker nodes in order to limit their operation only in the master node. Avoiding a race condition during cluster synchronization.

After the [analysis made](https://github.com/wazuh/wazuh/issues/16045#issuecomment-1413579864) by the framework team on the database endpoints, it was decided to opt for another path.

Now the deletion of the relationships between agents and groups stored in the table ```belongs``` will be performed by the database through a cascade deletion. Then the ```wazuh-db``` module will be in charge of recalculate the group_hash to update the ```agent``` table.

**Comment by sdvendramini** [comment]
After the research process, it was found that the following queries involve the belongs and group tables used by workers:

- ```[WDB_STMT_GLOBAL_FIND_GROUP] = "SELECT id FROM `group` WHERE name = ?;"```
- ```[WDB_STMT_GLOBAL_SELECT_GROUP_BELONG] = "SELECT name FROM belongs JOIN `group` ON id = id_group WHERE id_agent = ? order by priority;"```
- ```[WDB_STMT_GLOBAL_INSERT_AGENT_GROUP] = "INSERT OR IGNORE INTO `group` (name) VALUES(?);"```
- ```[WDB_STMT_GLOBAL_INSERT_AGENT_BELONG] = "INSERT OR REPLACE INTO belongs (id_group, id_agent, priority) VALUES(?,?,?);"```
- ```[WDB_STMT_GLOBAL_DELETE_AGENT_BELONG] = "DELETE FROM belongs WHERE id_agent = ?;"```
- ```[WDB_STMT_GLOBAL_DELETE_TUPLE_BELONG] = "DELETE FROM belongs WHERE id_group = ? and id_agent = ?;"```
- ```[WDB_STMT_GLOBAL_DELETE_GROUP] = "DELETE FROM `group` WHERE name = ?;"```
- ```[WDB_STMT_GLOBAL_GROUP_BELONG_FIND] = "SELECT 1 FROM belongs WHERE id_group = (SELECT id FROM 'group' WHERE name = ?);"```
- ```[WDB_STMT_GLOBAL_GROUP_BELONG_GET] = "SELECT id_agent FROM belongs WHERE id_group = (SELECT id FROM 'group' WHERE name = ?) AND id_agent > ?;"```
- ```[WDB_STMT_GLOBAL_SELECT_GROUPS] = "SELECT name FROM `group`;"```
- ```[WDB_STMT_GLOBAL_AGENT_GROUPS_NUMBER_GET] = "SELECT count(id_group) groups_number from belongs WHERE id_agent = ?;"```
- ```[WDB_STMT_GLOBAL_GROUP_PRIORITY_GET] = "SELECT MAX(priority) FROM belongs WHERE id_agent=?;"```
- ```[WDB_STMT_GLOBAL_GROUP_CSV_GET] = "SELECT `group` from agent where id = ?;"```
- ```[WDB_STMT_GLOBAL_GROUP_CTX_SET] = "UPDATE agent SET 'group' = ?, group_hash = ?, group_sync_status = ? WHERE id = ?;"```
- ```[WDB_STMT_GLOBAL_GET_GROUPS] = "SELECT DISTINCT `group`, group_hash from agent WHERE id > 0 AND group_hash > ? ORDER BY group_hash;"```

These queries are used by the following modules:
- ```wm_database```: to delete from DB groups and belongs that no longer exist and to update db with data from files. This happens when the module is started and then periodically.
- ```remoted```: to upgrade shared files and delete groups when directories no longer exist. Are used too by guess group feature.
- ```wazuh_db```: to upgrade the DB schema. And there are the following endpoints exposed to be used by framework:
     - ```global select-group-belong```
     - ```global get-group-agents```
     - ```global set-agent-groups```

**Comment by Selutario** [comment]
## Framework

After reviewing the use of each of the `wazuh-db` commands mentioned [here](https://github.com/wazuh/wazuh/issues/16045#issuecomment-1412147589), these are the results:

#### :green_circle: 1. `global select-group-belong` 

The `global select-group-belong` command is used in the following functions and methods of the Wazuh framework. All of those functions are **only used in the master node** when a cluster is deployed, so it can be safely restricted in workers.
```
global select-group-belong  ➜ get_agent_groups() (core/agent.py)   ➜ add_group_to_agent() (core/agent.py)        ➜ assign_agents_to_group() (agent.py)   ➜ put_agent_single_group (agent_controller.py)                   ➜ LOCAL_MASTER
                                                                                                                                                         ↘ put_multiple_agent_single_group (agent_controller.py)          ➜ LOCAL_MASTER
                                                                                                                                                         ↘ set_group() (scripts/agent_groups.py)                          ➜ LOCAL_MASTER
                                                                   ↘ unset_single_group_agent() (core/agent.py)  ➜ remove_agent_from_group() (agent.py)  ➜ delete_single_agent_single_group (agent_controller.py)         ➜ LOCAL_MASTER
                                                                                                                 ↘ remove_agent_from_groups() (agent.py) ➜ delete_single_agent_multiple_groups (agent_controller.py)      ➜ LOCAL_MASTER
                                                                                                                                                         ↘ unset_group() (scripts/agent_groups.py)                        ➜ LOCAL_MASTER
                                                                                                                 ↘ remove_agents_from_group() (agent.py) ➜ delete_multiple_agent_single_group (agent_controller.py)       ➜ LOCAL_MASTER
                                                                                                                                                         ↘ delete_groups (agent.py) ➜ delete_groups (agent_controller.py) ➜ LOCAL_MASTER
                                                                                                                                                                                                                          ↘ remove_group (scripts/agent_groups.py) ➜ LOCAL_MASTER
```

#### :red_circle: 2. `global get-group-agents` 
This command is used to expand the groups in the RBAC decorator. The decorator is executed in any node of the cluster, so the command is **used in the workers** and its use should not be restricted:
```
global get-group-agents     ➜ expand_group() (core/agent.py)  ➜ _expand_resource (rbac/decorators.py) ➜ _black_expansion       ➜ _match_permissions ➜ decorator ➜ expose_resources ➜ * SDK (DISTRIBUTED, USED IN WORKERS)
                                                                                                      ↘ _single_processor      ↗
                                                                                                      ↘ _combination_processor ↗
```

Here we can see the `ossec.log` of a worker:
```
root@wazuh-worker1:/# grep "get-group-agents" /var/ossec/logs/ossec.log 
2023/02/02 10:58:41 wazuh-db[4031] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: get-group-agents new_group last_id 0
```

#### :red_circle: 3. `global set-agent-groups` 
This command is used by the `clusterd` process itself and it's **executed in workers** (when receiving `agent-groups` data from master) so its use should not be restricted:
```
global set-agent-groups     ➜ add_agent_group_relationships() (API integration tests - update_agent_info.py) -> LOCAL_MASTER 
                            ↘ send_entire_agent_groups_information() (cluster/master.py)    ➜ DISTRIBUTED
                            ↘ send_agent_groups_information() (cluster/master.py)           ➜ DISTRIBUTED
                            ↘ set_agent_group_relationship() (core/agent.py)                ➜ add_group_to_agent() (core/agent.py)        ➜ assign_agents_to_group() (agent.py)   ➜ put_agent_single_group (agent_controller.py)                   ➜ LOCAL_MASTER
                                                                                                                                                         ↘ put_multiple_agent_single_group (agent_controller.py)                                   ➜ LOCAL_MASTER
                                                                                                                                                         ↘ set_group() (scripts/agent_groups.py)                                                   ➜ LOCAL_MASTER
                                                                                            ↘ unset_single_group_agent() (core/agent.py)  ➜ remove_agent_from_group() (agent.py)  ➜ delete_single_agent_single_group (agent_controller.py)         ➜ LOCAL_MASTER
                                                                                                                                          ↘ remove_agent_from_groups() (agent.py) ➜ delete_single_agent_multiple_groups (agent_controller.py)      ➜ LOCAL_MASTER
                                                                                                                                                                                  ↘ unset_group() (scripts/agent_groups.py)                        ➜ LOCAL_MASTER
```
