### ISSUE TITLE
Wrong behavior detected during KVDB API testing 

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16052]
## Description

After the team added the KVDB API to be able to manage them in runtime https://github.com/wazuh/wazuh/issues/15274, the following testing was performed:

- https://github.com/wazuh/wazuh-qa/issues/3663

## Bugs

The following bugs were reported after the above testing 

- https://github.com/wazuh/wazuh/issues/15705
- https://github.com/wazuh/wazuh/issues/15706
- https://github.com/wazuh/wazuh/issues/15707
- https://github.com/wazuh/wazuh/issues/15711

During the configuration module testing, this bug was found:

- https://github.com/wazuh/wazuh/issues/16109

**Comment by JcabreraC** [comment]
All tasks of this epic completed.
