### ISSUE TITLE
Load custom osquery extension with wazuh's wodle

### ISSUE THREAD

**Issue by giladreich** [wazuh/wazuh#16062]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | wazuh-modules | Manager & Agent | N/A | All Platforms |

I developed a custom Osquery extension that I would like Wazuh to know about and load it when it starts the Osquery process.

Following Wazuh docs regarding possible options one can configure for the Wodle, I don't see of a possible option passing additional arguments to Osquery: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-osquery.html

Also in code, I understand we only pass it the configurations file using the `--config_path=` flag: https://github.com/wazuh/wazuh/blob/v4.3.10/src/wazuh_modules/wm_osquery_monitor.c#L280-L306

After finding this limitation, I was trying to approach this in another way and making my extension to load via the `osquery.conf` file in `options` section (considering Wazuh already making Osquery load it): https://osquery.readthedocs.io/en/stable/deployment/configuration/#options

However, running `osqueryd --help` I see that all of the `extensions_*` options are CLI options that don't work when settings in the `osquery.conf` file. This is because there are two sections for possible flags:
- `osquery command line flags` 
- `osquery configuration options (set by config or CLI flags)`

And it appears to be that there are no configuration options to specify a custom extension path to be loaded.

Considering Wazuh is running Osquery as a managed child-process, could anyone suggest a possible alternative of loading Osquery extension please?
Maybe as a possible feature, I think it may be useful to add configuration to the Osquery Wodle in Wazuh to pass additional arguments to the Osquery process? That will also make it much more simpler from a design point of view instead of hardcoding each additional argument, as was done for `config_path`. That way administrators can just pass additional arguments to Osquery, even new ones that may be added to future Osquery versions.

**Comment by giladreich** [comment]
Another possible proposal is to provide the Wodle an [osquery.flags](https://osquery.readthedocs.io/en/stable/installation/cli-flags/#flagfile) file:
```xml
<agent_config>
	<wodle name="osquery">
		<disabled>no</disabled>
		<run_daemon>yes</run_daemon>
		<bin_path>/Library/Ossec/osquery/osquery.app/Contents/MacOS</bin_path>
		<log_path>/Library/Ossec/osquery/log/osqueryd.results.log</log_path>
		<flags_file_path>/Library/Ossec/osquery/osquery.flags</config_path>
		<add_labels>yes</add_labels>
	</wodle>
</agent_config>
```
in the `osquery.flags` file one could simply put any startup flags, as well as provide there the `osquery.conf` file (see `osqueryd --help` for more). This means we can also simplify and drop the `config_file` from the Wodle configs. Example of `osquery.flags` newline based delimited file:
```
--config_path=/Library/Ossec/osquery/ext/osquery.conf
--extension=/Library/Ossec/osquery/ext/osqueryd.ext
```

That will make the Wodle not depend anymore on Osquery's future changes, since one could set any startup arguments they want.

Also the Wodle could be simplified further; like the `log_path`, we can drop and simply load it from the `osquery.conf` file. If `osquery.conf` is not provided in the `osquery.flags` file, then use the default osquery's hardcoded paths (see [OSQUERY_LOG_HOME](https://github.com/osquery/osquery/blob/5.7.0/osquery/utils/config/default_paths.h#L23-L51)).

This said; it means we only need two things for Wazuh to know how to handle Osquery's Wodle:
- Path to the `osqueryd` binary
- Path to the `osquery.flags` file

Then all Wazuh will do when it starts `osqueryd` is: `osqueryd --flagfile osquery.flags`

I also suggest being more explicit with how the Wodle configs are named. A `*_path` could be either a file or dir, whilst that is not the case here. I remember when I first looked into this, I read in another place that it was confusing.

Based on the points I mentioned above, here is how my proposal would look like if we would to refactor this behavior:
```xml
<agent_config>
	<wodle name="osquery">
		<disabled>no</disabled>
		<run_daemon>yes</run_daemon>
		<bin_file>/Library/Ossec/osquery/osquery.app/Contents/MacOS/osqueryd</bin_path>
		<flags_file>/Library/Ossec/osquery/osquery.flags</config_path>
		<add_labels>yes</add_labels>
	</wodle>
</agent_config>
```
Simple and manageable IMHO, which will allow everyone to package Osquery in whatever fashion they like.

@vikman90, @chemamartinez, @TomasTurina, @crolopez, @AdriiiPRodri or any Wazuh contributor, what do you think? If this sounds reasonable to you, I may be able to provide a pull-request for this.

**Comment by vikman90** [comment]
Hi @giladreich,

Although I am taking a look at your proposal, to answer your question here, as you yourself saw in the code, the osquery integration only supports the `--config_path` argument right now.

The currently proposed alternative would be to launch osquery as a separate service, and let the agent monitor it without running it as a child process:

```xml
<wodle name="osquery">
  <run_daemon>no</run_daemon>
</wodle>
```

Best regards.

**Comment by vikman90** [comment]
Hi @giladreich,

I've got that, your use case needs some additions in the code to make it usable. If you agree, we will continue talking in the issue of the proposal (#16085).

Best regards.
