### ISSUE TITLE
Add `POST /events` endpoint to Wazuh API

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#16068]
## Description

As part of https://github.com/wazuh/wazuh/issues/16067, we need to develop a new API endpoint with the following requirements:

- **Name:** `POST /events`
- A new **RBAC permission** for this endpoint.
- A **JSON body** with security events is required.
  - The JSON body may have more than one security event (bulk).
 - A new **API configuration parameter** must **limit** the amount of **requests per minute** this endpoint will allow.
 - A **new process pool** must be developed to handle this kind of requests.
 - Currently, the API will only validate the JSON body and return an informative response. No events validation will be implemented.

To be defined:

- EPS of the endpoint
- Max size of the bulk 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
# Issue Update

I was working on the definition of the spec (`api/api/spec/spec.yaml`) for the webhook endpoint.

**Comment by nico-stefani** [comment]
# Issue Update

After the definition of the spec, I have identified the next steps to follow:

- [ ] Create a new model
- [ ] Define a new framework function to forward events to analysisd
- [ ] Define a new controller to handle the request

**Comment by nico-stefani** [comment]
# Issue Update

After developing the main components, Is needed to start testing the main endpoint flow.

**Comment by nico-stefani** [comment]
# Issue Update

I was doing some functional testing in order to validate the proposed implementation. 
The next steps are:
 - [ ] Add new limit rate for the endpoint
 - [ ] Add unit test

**Comment by nico-stefani** [comment]
# Issue Update

I was working on the UT but still I need to test the related framework function.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on some improvements over the socket connection handler and adding unit tests for the framework side.
Before opening the PR I have to fix some tests related to RBAC changes.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on the schema validation for `events_bulk_max_size` parameter which I was missing.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on changes required from the code review. 
I need confirmation on https://github.com/wazuh/wazuh/pull/17023#discussion_r1189534533 before to continue.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on some requested changes from the code review. I need to add test cases before to moving forward.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on replacing the config `max_events_per_request` with a constant value.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on a better implementation for the general and events endpoint rate limiter. Still, I need to do some testing.

**Comment by nico-stefani** [comment]
I finalize the changes for the rate limiter. I need to review and implement the other requested changes.

**Comment by nico-stefani** [comment]
I was working on some minor improvements and mainly on the error handling over the socket send messages functionality. I need to validate some behavior before continuing with the implementation.

**Comment by nico-stefani** [comment]
I was solving some doubts related to the socket messages in the PR. I could not make much progress on the implementation because of a change of priority.

**Comment by nico-stefani** [comment]
I was working on the last requested changes. I need to check some details before requesting the revision again.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on another PR suggested changes.

**Comment by nico-stefani** [comment]
# Issue Update

I started working on https://github.com/wazuh/wazuh/pull/17023/files#diff-674a59a0042b26aca175affc11ef845f15bdf325734bb8ec7075827eff68b93f

**Comment by nico-stefani** [comment]
# Issue Update

I continue working on the requested changes and investigating the socket message size limits.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on a final solution for the socket message size. I need to discuss with the team the proposed implementation before continuing.

**Comment by nico-stefani** [comment]
# Issue Update

I was discussing the possible solution with the team and implementing the improvements.
