### ISSUE TITLE
Design and develop new API integration tests for `POST /events`

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#16077]
## Description

As part of https://github.com/wazuh/wazuh/issues/16067, we need to design new AIT for the proposed endpoint. This development will follow **TDD**, making this issue a blocker for the main developing one.

Since the tests must consider and expect all kind of query parameters, JSON bodies and responses; we need to first design all of them in this issue before implementing them.

## Checks
The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
This is a reply to a query.

**Comment by nico-stefani** [comment]
# Issue Update

## Integration test cases proposal

### Test RBAC permission
* Request with valid permission should be responded to with 2XX code 
* Request with invalid permission should be responded to with 4XX code

### Test request body
* Request with one element inside of bulk should be responded with 2XX code and send one event to analysisd
* Request with multiple elements inside of bulk should be responded with 2XX code and send the correct number of events to analysisd
* Request with an invalid body should be responded to with 4XX code
* Request with a bulk greater than the max size allowed should be responded with 4XX

**Comment by nico-stefani** [comment]
## Issue Update

After validating the cases with the team. I've started with the implementation of the basic structure of the tests.

**Comment by nico-stefani** [comment]
# Issue Update

In order to continue with the development, is necessary to validate the request body and the response from the new endpoint.

- [ ] Validate with the team

**Comment by nico-stefani** [comment]
# Issue Update

After validating the request and response payload with the team. I was working on the utils to catch the messages forwarded to analysisd.

**Comment by nico-stefani** [comment]
# Issue Update

Still, I'm working on the utils mentioned above. The next step is to make working with the dockerized manager.

**Comment by nico-stefani** [comment]
# Issue Update

Finally, I ended with the necessary utils to catch the forwarded events.
The next steps are:
* Complete the proposed  test cases
* Add some configuration files required by each test

**Comment by nico-stefani** [comment]
# Issue Update

I need to review the permission over the socket file before of open the PR, I will work on that.

**Comment by nico-stefani** [comment]
I was working over permissions to bind sockets outside of the container.  
I found the error below because the analysisd module is stopped in order to intercept the messages.

```
Exception: Error obtaining login token: {'title': 'Bad Request', 'detail': 'Some Wazuh daemons are not ready yet in node "master-node" (wazuh-analysisd->stopped)', 'dapi_errors': {'master-node': {'error': 'Some Wazuh daemons are not ready yet in node "master-node" (wazuh-analysisd->stopped)'}}, 'error': 1017}
```

I need to figure out this problem next.

**Comment by nico-stefani** [comment]
# Issue Update

I made some changes after implementing the API endpoint, changing some constant values and test behaviors.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on some requested changes, mainly removing utils, to handle the analysisd socket, which wasn't necessary.

**Comment by nico-stefani** [comment]
I was working on integrating the tests with the latest changes in #16068. Particularly adapting the new response of the endpoint.

**Comment by nico-stefani** [comment]
# Issue Update

I continue working on the final integration of the tests. Today I got progress over the 'Bad Request' tests and also Im currently working on a case to trigger the `max_requests_per_minute` restriction for the endpoint.

**Comment by nico-stefani** [comment]
# Issue Update

I finalize the adjustments over the endpoint tests. The next step is doing the same with the RBAC cases.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on the integration of the RBAC tests with the implemented endpoint. 
I'm having some issues trying to understand the difference between the white and black cases.  I need to talk with the team to resolve this blocker.

**Comment by nico-stefani** [comment]
# Issue Update

I finished adapting the IT to the implementation. I keep this on hold waiting for the merge of the implementation to the development branch.
