### ISSUE TITLE
Vulnerabilities db doesn´t remove after manager update

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh#1607]
## Bug report

**OS**
Centos 7

**Wazuh version**
"v3.7.0-3707"

**Install type**
manager

**Install method**
packages

**Log sample**

```
[root@master_up ~]# date; ll -h /var/ossec/queue/vulnerabilities/cve.db 
mar oct  9 10:44:06 EDT 2018
-rw-rw----. 1 root ossec 5,9M oct  9 10:41 /var/ossec/queue/vulnerabilities/cve.db
[root@master_up ~]# 

```

Bug description
----------------
After updataing the manager, the `cve.db`  file should have been removed or recreated. I found that this isn´t happening, so I would say that this test fails.

**Comment by crolopez** [comment]
Hi @adri9valle,

I couldn't to reproduce the issue, and I don't think it's possible.

You probably didn't see the database removed because you had vulnerability-detector on and it is recreated right after restarting.

Because of this, let me close the issue. Feel free to reopen it.

Best regards.
