### ISSUE TITLE
Use /proc/net/* instead of "netstat -tulpn" for Identification of Network Listener Processes

### ISSUE THREAD

**Issue by juergenc** [wazuh/wazuh#1608]
## Feature request
**Component involved**
_localfile/log_format/full_command_

Description
--------------
### User Story
For the identification of the network listener processes, Wazuh uses the shell command `netstat -tulpn` in property `<log_format>full_command</log_format>` `<localfile>` functionality in agent's local config file `ossec.conf`:
```XML
<localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
</localfile>
```
First, it is **_not a good idea_** to use the command line tool `netstat` for that purpose since the `netstat` binary is one of the replacement candidates of **_rootkits_** hiding _illegal_ network listener processes!

### User Acceptance Criteria
1. Replace the functionality of the command `netstat -tulpn` by an own save implementation reading and interpreting the following files in `/proc/network/* as the `netstat -tulpn` command does:
```
open("/proc/net/tcp", O_RDONLY)         = 3
open("/proc/net/tcp6", O_RDONLY)        = 3
open("/proc/net/udp", O_RDONLY)         = 3
open("/proc/net/udp6", O_RDONLY)        = 3
open("/proc/net/raw", O_RDONLY)         = 3
open("/proc/net/raw6", O_RDONLY)        = 3
open("/proc/net/unix", O_RDONLY)        = 3
open("/proc/net/ipx/socket", O_RDONLY)  = -1 ENOENT (No such file or directory)
open("/proc/net/ipx", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("/proc/net/ax25", O_RDONLY)        = -1 ENOENT (No such file or directory)
open("/proc/net/x25", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("/proc/net/x25", O_RDONLY)         = -1 ENOENT (No such file or directory)
open("/proc/net/nr", O_RDONLY)          = -1 ENOENT (No such file or directory)
```
2. The `syscollector` process seems to be the appropriate process to collect network listener information with an additional tag e.g.
```XML
<network_listener>yes|no</network_listener>
```
or
```XML
<netstat>yes|no</netstat>
```

**Comment by chemamartinez** [comment]
Hi @juergenc,

I agree with you, and it is in our roadmap to change this behavior as soon as possible.

For now, that command is just used to warn when the output of the command has changed (a new port is listening or has been closed). However, this method has some limitations, for example, it can't determine which ones have changed their state.  

As part of the development planned at #742. When Syscollector scans the listening ports and stores them in the database, it will be able to calculate differences between scans and alert about newly opened ports or removed ports from the list.

Best regards,
Chema.
