### ISSUE TITLE
Engine - Event enrichment benchmark

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#16087]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

We want to measure how the enrichment of events with data obtained from KVDBs affects the performance of the engine. In particular, we want to measure the impact of:

- [x] enrich all events with an ECS compatible hosts object, augmenting all events with hosts information
- [x] check all events with an IP address against a KVDB with a list of at least a million IP addresses. The key will be the IP address and the content a JSON object. This object should be something similar to a [threat enrichment indicator](https://www.elastic.co/guide/en/ecs/current/ecs-threat-usage.html).
- [x] test with both at the same time

We want to measure the impact of these activities, so we must set a baseline without it, and then enable the enrichment and measure again. 

We need to include the analysis as a documentation in this issue.

Furthermore, we want to figure out if our current design is enough to implement multiple enrichment features.

**Comment by nmkoremblum** [comment]
| #  | BRANCH                     | COMMIT                                   | INPUT TYPE        | QUEUE | EVTS QTTY | RULESET | IS KVDB FILLED | READS KVDB | WRITES KVDB | USES WDB | NOTES               | EPS   |
|----|----------------------------|------------------------------------------|-------------------|-------|-----------|---------|----------------|------------|-------------|----------|---------------------|-------|
| 1  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT   | 1     | 108000    | minimal | no             | no         | no          | no       |                     | 6880  |
| 2  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT   | 1     | 108000    | minimal | no             | yes        | no          | no       |                     | 6650  |
| 3  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT     | 1     | 100000    | minimal | no             | yes        | no          | no       |                     | 9850  |
| 4  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | minimal | no             | yes        | yes         | yes      |                     | 5700  |
| 5  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT   | 1     | 108000    | minimal | yes            | no         | no          | no       |                     | 6880  |
| 6  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT   | 1     | 108000    | minimal | yes            | yes        | no          | no       |                     | 6200  |
| 7  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT     | 1     | 100000    | minimal | yes            | yes        | no          | no       |                     | 9250  |
| 8  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | minimal | yes            | yes        | yes         | yes      |                     | 5100  |
| 9  | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT   | 1     | 108000    | full    | no             | no         | no          | no       |                     | 1500  |
| 10 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT   | 1     | 108000    | full    | no             | yes        | no          | no       |                     | 1440  |
| 11 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT     | 1     | 100000    | full    | no             | yes        | no          | no       |                     | 3800  |
| 12 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | full    | no             | yes        | yes         | yes      |                     | 4800  |
| 13 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT   | 1     | 108000    | full    | yes            | no         | no          | no       |                     | 1500  |
| 14 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT   | 1     | 108000    | full    | yes            | yes        | no          | no       |                     | 1450  |
| 15 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT     | 1     | 100000    | full    | yes            | yes        | no          | no       |                     | 3750  |
| 16 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | full    | yes            | yes        | yes         | yes      |                     | 4550  |
| 17 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | NON AGENT   | 1     | 108000    | minimal | no             | no         | no          | no       |                     | 7100  |
| 18 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | AGENT   | 1     | 108000    | minimal | no             | no         | no          | no       |                     | 7000  |
| 19 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | DUMMY AGENT EVT     | 1     | 100000    | minimal | no             | no         | no          | no       |                     | 10900 |
| 20 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | KVDB FILL | 5     | 100000    | minimal | no             | no         | no          | yes      |                     | 9600  |
| 21 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | NON AGENT   | 1     | 108000    | full    | no             | no         | no          | no       |                     | 3500  |
| 22 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | AGENT   | 1     | 108000    | full    | no             | no         | no          | no       |                     | 3350  |
| 23 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | DUMMY AGENT EVT     | 1     | 100000    | full    | no             | no         | no          | no       |                     | 9950  |
| 24 | 11334-dev-new-wazuh-engine | 0c605560c2f48c9d0547b2483d043b0469e7a755 | KVDB FILL | 5     | 100000    | full    | no             | no         | no          | yes      |                     | 8400  |
| 25 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | minimal | no             | yes        | yes         | no       | WDB skipped | 9000  |
| 26 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | minimal | yes            | yes        | yes         | no       | WDB skipped | 8400  |
| 27 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | full    | no             | yes        | yes         | no       | WDB skipped | 8700  |
| 28 | 11334-dev-new-wazuh-engine | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL | 5     | 100000    | full    | yes            | yes        | yes         | no       | WDB skipped | 8100  |

**Comment by nmkoremblum** [comment]
Here is a table with some tests results:

| #  | COMMIT                                   | INPUT TYPE      | QUEUE | EVTS QTTY | RULESET | IS KVDB FILLED | READS KVDB | WRITES KVDB | USES WDB | NOTES                | EPS   |
|----|------------------------------------------|-----------------|-------|-----------|---------|----------------|------------|-------------|----------|----------------------|-------|
| 1  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | minimal | no             | no         | no          | no       |                      | 6880  |
| 2  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | minimal | no             | yes        | no          | no       |                      | 6650  |
| 3  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | minimal | no             | yes        | no          | no       |                      | 9850  |
| 4  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | minimal | no             | yes        | yes         | yes      |                      | 5700  |
| 5  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | minimal | yes            | no         | no          | no       |                      | 6880  |
| 6  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | minimal | yes            | yes        | no          | no       |                      | 6200  |
| 7  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | minimal | yes            | yes        | no          | no       |                      | 9250  |
| 8  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | minimal | yes            | yes        | yes         | yes      |                      | 5100  |
| 9  | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | full    | no             | no         | no          | no       |                      | 1500  |
| 10 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | full    | no             | yes        | no          | no       |                      | 1440  |
| 11 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | full    | no             | yes        | no          | no       |                      | 3800  |
| 12 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | full    | no             | yes        | yes         | yes      |                      | 4800  |
| 13 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | full    | yes            | no         | no          | no       |                      | 1500  |
| 14 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | full    | yes            | yes        | no          | no       |                      | 1450  |
| 15 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | full    | yes            | yes        | no          | no       |                      | 3750  |
| 16 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | full    | yes            | yes        | yes         | yes      |                      | 4550  |
| 17 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | NON AGENT       | 1     | 108000    | minimal | no             | no         | no          | no       |                      | 7100  |
| 18 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | AGENT           | 1     | 108000    | minimal | no             | no         | no          | no       |                      | 7000  |
| 19 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | DUMMY AGENT EVT | 1     | 100000    | minimal | no             | no         | no          | no       |                      | 10900 |
| 20 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | KVDB FILL       | 5     | 100000    | minimal | no             | no         | no          | yes      |                      | 9600  |
| 21 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | NON AGENT       | 1     | 108000    | full    | no             | no         | no          | no       |                      | 3500  |
| 22 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | AGENT           | 1     | 108000    | full    | no             | no         | no          | no       |                      | 3350  |
| 23 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | DUMMY AGENT EVT | 1     | 100000    | full    | no             | no         | no          | no       |                      | 9950  |
| 24 | 0c605560c2f48c9d0547b2483d043b0469e7a755 | KVDB FILL       | 5     | 100000    | full    | no             | no         | no          | yes      |                      | 8400  |
| 25 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | minimal | no             | yes        | yes         | no       | WDB query supressed  | 9000  |
| 26 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | minimal | yes            | yes        | yes         | no       | WDB query supressed  | 8400  |
| 27 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | full    | no             | yes        | yes         | no       | WDB query supressed  | 8700  |
| 28 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | KVDB FILL       | 5     | 100000    | full    | yes            | yes        | yes         | no       | WDB query supressed  | 8100  |
| 29 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | minimal | no             | no         | no          | no       | Enrichment supressed | 6860  |
| 30 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | minimal | no             | no         | no          | no       | Enrichment supressed | 6730  |
| 31 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | minimal | no             | no         | no          | no       | Enrichment supressed | 10350 |
| 32 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | NON AGENT       | 1     | 108000    | full    | no             | no         | no          | no       | Enrichment supressed | 1500  |
| 33 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | AGENT           | 1     | 108000    | full    | no             | no         | no          | no       | Enrichment supressed | 1450  |
| 34 | 75ce360520e16ec4c2840cab5c6c8a2d7656191e | DUMMY AGENT EVT | 1     | 100000    | full    | no             | no         | no          | no       | Enrichment supressed | 3700  |

**Comment by nmkoremblum** [comment]
Here are listed some comparisons and conclusions that can be obtained from the tests:

-  EPS @ RULESET FULL / MINIMAL

| EVENT TYPE                    | PC1     | PC2     |
|-------------------------------|---------|---------|
| NON-AGENT                     | -78.20% | -78.52% |
| AGENT                         | -78.35% | -78.72% |
