### ISSUE TITLE
Low performance of 4.3.x agent and 3.1 manager in AIX systems

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16099]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3 | Logcollector/Syscheck | Agent | Packages | AIX7 |
| 3.1 | Logcollector/Syscheck | Manager | Sources | AIX7 |

### Description

It has detected a low performance in the [AIX 3.1 manager](https://github.com/wazuh/wazuh-qa/issues/3679#issuecomment-1408980919). 

It has been estimated that the maximum number of alerts per second that it is capable of handling the AIX 3.1 manager is less than 70. This is common for the syscheck and logcollector modules.

<details>

<summary> Performance results </summary>

![alerts_comparision](https://user-images.githubusercontent.com/11089305/217062389-410d03f6-9f12-4209-a9f4-214c557e298f.png)

![alerts_global](https://user-images.githubusercontent.com/11089305/217062397-01c31ec0-de75-4318-a4cf-288d76a99966.png)

> Logcollector 100 events per second

</details>

In comparison, an Ubuntu local installation could manage more than 800 EPS

<details>

<summary> Ubuntu local Performance results</summary>

![alerts_comparision](https://user-images.githubusercontent.com/11089305/217067804-4198731d-3d94-4caf-95f9-08f0d666c01b.png)

![alerts_global](https://user-images.githubusercontent.com/11089305/217067811-429a5f85-905b-4583-ab9b-6f82c2bff057.png)

> Logcollector 100 events per second

</details>

In comparison, a local Ubuntu server has been able to handle more than 50 EPS:

This condition is not due to a limitation of the server resources, due to CPU usage is insignificant in all cases (less than 5%)

<details>

<summary> AIX CPU usage </summary>

![20230130153945_analysisd_cpu](https://user-images.githubusercontent.com/11089305/217063262-78b289fe-5489-44d8-8fb4-f50146fa2c40.png)
> Logcollector 100 events per second

</details>

It seems related to a limitation in the event queue handling. Also, multiple warning appears during the tests cases:
```
2023/01/30 10:35:55 ossec-logcollector: WARNING: Socket busy, waiting for 1 second.`
```
> **Note**
> These messages were not present in the same tests cases in a Ubuntu Local environment

> **Note**
> This warning message is also produced for the syscheck module: `2023/01/31 11:45:58 ossec-syscheckd: WARNING: Socket busy, waiting for 1 second.`

At @vikman90  request to find out what caused this behavior. it has been used a [custom queue script](https://github.com/wazuh/wazuh-tools/blob/master/utils/queue.py) for in continously event send. In this case, EPS increased exponentially.

<details>

<summary> Custom queue script</summary>

```
#!/usr/bin/env python3
# Print messages on OSSEC queue (analysisd/agentd)
# November 1, 2016
#
# Syntax: queue.py <message>
# Standard message form: <id>:<location>:<log>

from socket import socket, AF_UNIX, SOCK_DGRAM, SO_SNDBUF, SOL_SOCKET
from sys import argv

ADDR = '/var/ossec/queue/sockets/queue'
BLEN = 212992

if len(argv) < 2:
    print("Syntax: {0} [-L] <message>")
    exit(1)

sock = socket(AF_UNIX, SOCK_DGRAM)
sock.connect(ADDR)
oldbuf = sock.getsockopt(SOL_SOCKET, SO_SNDBUF)

if oldbuf < BLEN:
    sock.setsockopt(SOL_SOCKET, SO_SNDBUF, BLEN)
    newbuf = sock.getsockopt(SOL_SOCKET, SO_SNDBUF)
    print("INFO: Buffer expended from {0} to {1}".format(oldbuf, newbuf))


if argv[1] == '-L':
    string = ' '.join(argv[2:])
    i=1
    try:
        while True:
            try:
               sock.send(string.encode())
               i += 1
            except:
               pass
else:
    string = ' '.join(argv[1:])
    sock.send(string.encode())

sock.close()
```

</details>

Likewise, this condition was detected in agent 4.3, to a lesser degree.  Even disabling the `client_buffer` option, it does not reach 500 events per second, losing more than 30% of the alerts.
In agent log's were present similar warning and error messages:
```
2023/02/02 11:38:51 wazuh-logcollector: WARNING: Socket busy, discarding the message.
....
2023/02/02 11:39:25 ossec-logcollector: ERROR: socketerr (not available).
```

**Comment by mateocervilla** [comment]
## About this issue

This happens when logcollector is trying to send several messages through a socket in a short interval of time.
The socket is created as `AF_UNIX` / `SOCK_DGRAM` (`UDP`).

In the code, it happens here:

- `src/logcollector/logcollector.c`:
  - `w_output_thread()`:
``` 
SendMSGtoSCK(logr_queue, message->buffer, message->file, message->queue_mq, message->log_target)
```
Which takes us to:

- `src/os_net/os_net.c`:
  - `OS_SendUnix()`:
```
send(socket, msg, size, 0)
```
And if `errno == ENOBUFS`, the message is discarded.

## Some things I checked:
- If the `O_NONBLOCK` flag is enabled on this socket: It's not.
        Enabling it doesn't change anything.
- Using `select()` function. It checks the specified file descriptors and message queues to see if they are ready for reading (receiving) or writing (sending), or if they have an exceptional condition pending.
        I did some tests and there were no changes at all.
        I've been reading that it may not work with `AF_UNIX` / `SOCK_DGRAM` (`UDP`) sockets. Most examples I've seen were using `SOCK_STREAM` sockets:

[select, sendto and ENOBUFS](https://freebsd-hackers.freebsd.narkive.com/SPCdkxBm/select-sendto-and-enobufs):

> The conclusion being that send, sendto and select will never block on a UDP socket and the man page just doesn't make it too clear. I'm assuming it is the same for raw sockets.
>                 
> This is not a bug, select says "yes there is room in the socket buffer" however datagram protocols do not store anything in the outgoing socket buffer, but, instead hand the packets directly to the driver for the NIC.
> when the NIC fills up it returns ENOBUFS
> this is your cue to do a usleep(1000)  before sending more packets.

[send(2) does not block](https://mail-archive.freebsd.org/cgi/getmsg.cgi?fetch=167319+0+archive/2004/freebsd-hackers/20040125.freebsd-hackers):

> I cannot get send (or sendto which is what is really interests me) to block on FreeBSD 4.9.  When I send as fast as I can to a socket, send rapidly fails with ENOBUFS.  I am not surprised that the kernel is running out of mbufs but I am surprised that send does not block until more become available.
> Select does not block either.  It always says that I can write to the socket and then send fails with ENOBUFS.

- Using `usleep()` and retry to send: It gave good results.
  - With 600 EPS, no messages are lost.
  - With 800 EPS sent 20 times, 1300 messages arrived, and without this change, the number lower to 500.

## Code

- Use of `usleep()` with limited attempts:

```c
int OS_SendUnix(int socket, const char *msg, int size)
{
    if (size == 0) {
        size = strlen(msg) + 1;
    }

    for(int tries = 0; tries < 10; tries++){
        if (send(socket, msg, size, 0) < size)
            usleep(1000);
        else
            return (OS_SUCCESS);
    }
    if (errno == ENOBUFS) {
        return (OS_SOCKBUSY);
    }
    return (OS_SOCKTERR);
}
```

- Use of `select()` without timeout:

```c
int OS_SendUnix(int socket, const char *msg, int size)
{
    if (size == 0) {
        size = strlen(msg) + 1;
    }

    fd_set writefds;
    FD_ZERO(&writefds);
    FD_SET(socket, &writefds);

    if (select(socket + 1, NULL, &writefds, NULL, NULL) < 0) {
        return (OS_SOCKBUSY);
    }

    if (FD_ISSET(socket, &writefds)) {
        if (send(socket, msg, size, 0) < size) {
            if (errno == ENOBUFS) {
                return (OS_SOCKBUSY);
            }
            return (OS_SOCKTERR);
        }
    }
    return (OS_SUCCESS);
}
```

- Use of `O_NONBLOCK` flag

```c
if (socket >= 0) {
    int flags;  
    flags = fcntl(socket, F_GETFL, 0);
    fcntl(socket, F_SETFL, flags | O_NONBLOCK);
}
```

## Performance results

I attach some results executed by the different tests


[No_changes.txt](https://github.com/wazuh/wazuh/files/11579833/No_changes.txt)
[select()_no_timeout.txt](https://github.com/wazuh/wazuh/files/11579845/select._no_timeout.txt)
[select()_timeout_100000.txt](https://github.com/wazuh/wazuh/files/11579846/select._timeout_100000.txt)
[usleep(1000).txt](https://github.com/wazuh/wazuh/files/11579847/usleep.1000.txt)
[usleep(1000)_with_10_attempts.txt](https://github.com/wazuh/wazuh/files/11579848/usleep.1000._with_10_attempts.txt)
[usleep(1000)_with_10000000_attempts.txt](https://github.com/wazuh/wazuh/files/11579849/usleep.1000._with_10000000_attempts.txt)
[usleep(100000).txt](https://github.com/wazuh/wazuh/files/11579850/usleep.100000.txt)
[usleep(300000).txt](https://github.com/wazuh/wazuh/files/11579851/usleep.300000.txt)

**Comment by mateocervilla** [comment]
## Performance and CPU usage

Here are tests of 600 EPS with different values ​​for the `usleep()` function

### Without a fix

Lots of missed events. Low CPU usage.

seconds | epi | num_alerts |    | CPU(%) analisysd | CPU(%) logcollector
-- | -- | -- | -- | -- | --
0 | 600 | 0 |   | 0 | 0
1 | 600 | 0 |   | 0 | 0
2 | 600 | 0 |   | 1.2 | 0.1
3 | 600 | 511 |   | 0.7 | 0.3
4 | 600 | 4 |   | 0.4 | 0.3
5 | 600 | 270 |   | 0.5 | 0.1
6 | 600 | 1 |   | 1.4 | 0.1
7 | 600 | 511 |   | 0.5 | 0.3
8 | 600 | 5 |   | 0.6 | 0.3
9 | 600 | 355 |   | 0.7 | 0.1
10 | 600 | 6 |   | 0.7 | 0.2
11 | 600 | 277 |   | 0.3 | 0.3
12 | 600 | 1 |   | 0.4 | 0.2
13 | 600 | 256 |   | 0.5 | 0.3
14 | 600 | 3 |   | 0.6 | 0.2
15 | 600 | 256 |   | 0.3 | 0.3
16 | 600 | 2 |   | 0.4 | 0.2
17 | 600 | 256 |   | 0.5 | 0.3
18 | 600 | 3 |   | 0 | 0.2
19 | 600 | 511 |   | 1.8 | 0.3
20 | 0 | 5 |   | 0.4 | 0
21 | 0 | 256 |   | 0.5 | 0.4
22 | 0 | 2 |   | 0.2 | 0
23 | 0 | 71 |   | 0.1 | 0
24 | 0 | 6 |   | 0 | 0
Total | 12000 | 3568 | Average | 0.57 | 0.22
Loss |   | 8432 |   |   |  


### usleep(0), usleep(1), usleep(n) > 10000

It doesn't make much difference, EPS don't get better

### usleep(1000)

One of the best tested cases. Loss of events decreases significantly. `analisysd` CPU usage has a relatively low increase. `logcollector` CPU usage doesn't have a significant increase.

seconds | epi | num_alerts |   | CPU(%) analisysd | CPU(%) logcollector
-- | -- | -- | -- | -- | --
0 | 600 | 0 |   | 0 | 0
1 | 600 | 0 |   | 0 | 0
2 | 600 | 0 |   | 2.6 | 0.4
3 | 600 | 0 |   | 1.8 | 0.1
4 | 600 | 1157 |   | 2.6 | 0
5 | 600 | 6 |   | 2.1 | 0.5
6 | 600 | 1198 |   | 2.6 | 0
7 | 600 | 2 |   | 2.4 | 0.5
8 | 600 | 1198 |   | 2.1 | 0.4
9 | 600 | 2 |   | 2.9 | 0.1
10 | 600 | 1198 |   | 2.5 | 0.1
11 | 600 | 3 |   | 2.8 | 0.4
12 | 600 | 1198 |   | 2.5 | 0.3
13 | 600 | 2 |   | 2.5 | 0.2
14 | 600 | 1198 |   | 2.4 | 0.2
15 | 600 | 2 |   | 1.9 | 0.3
16 | 600 | 1071 |   | 2.1 | 0.1
17 | 600 | 6 |   | 2.3 | 0.4
18 | 600 | 1198 |   | 2.2 | 0.2
19 | 600 | 2 |   | 2.2 | 0.2
20 | 0 | 1020 |   | 2.2 | 0.1
21 | 0 | 3 |   | 3 | 0.3
22 | 0 | 1090 |   | 0 | 0
23 | 0 | 5 |   | 0.4 | 0
24 | 0 | 100 |   | 0 | 0
25 | 0 | 5 |   | 0 | 0
Total | 12000 | 11664 | Average | 2.18 % | 0.24 %
Loss |   | 336 |   |   |  

### usleep(500)

Similar to the previous case but in most of the tests, slightly higher values ​​of event losses were seen.

seconds | epi | num_alerts |   | CPU(%) analisysd | CPU(%) logcollector
-- | -- | -- | -- | -- | --
0 | 600 | 0 |   | 0 | 0
1 | 600 | 0 |   | 0 | 0
2 | 600 | 0 |   | 3 | 0.4
3 | 600 | 0 |   | 1.4 | 0.1
4 | 600 | 1142 |   | 2.9 | 0
5 | 600 | 3 |   | 1.3 | 0.4
6 | 600 | 1021 |   | 3.4 | 0.2
7 | 600 | 2 |   | 1.8 | 0.3
8 | 600 | 1198 |   | 3 | 0.4
9 | 600 | 2 |   | 1.9 | 0.1
10 | 600 | 1198 |   | 3.1 | 0
11 | 600 | 3 |   | 1.2 | 0.4
12 | 600 | 1021 |   | 2.9 | 0.1
13 | 600 | 2 |   | 2.4 | 0.3
14 | 600 | 1198 |   | 2.7 | 0.1
15 | 600 | 2 |   | 1.6 | 0.3
16 | 600 | 1021 |   | 0.9 | 0.2
17 | 600 | 2 |   | 3.6 | 0.3
18 | 600 | 1078 |   | 2.3 | 0
19 | 600 | 0 |   | 2 | 0.4
20 | 0 | 1021 |   | 0.4 | 0
21 | 0 | 2 |   | 3.7 | 0.4
22 | 0 | 970 |   | 0.4 | 0
23 | 0 | 1 |   | 0.5 | 0.1
24 | 0 | 227 |   | 0 | 0
25 | 0 | 2 |   | 0 | 0
Total | 12000 | 11116 | Average | 2.11 | 0.20
Loss |   | 884 |   |   |
