### ISSUE TITLE
License URL points to old version in 4.4.0 Beta1

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#16123]
|Wazuh version|Component|
|---|---|
| 4.4.0-beta1 | API |

## Description
Hello,

We have detected a problem related to the `license_url` field in the Wazuh API default reply. An example query was:
```
# curl -k "https://localhost:55000/" -H "Authorization: Bearer $TOKEN"
{"data": {"title": "Wazuh API REST", "api_version": "4.4.0", "revision": 40402, "license_name": "GPL 2.0", "license_url": "https://github.com/wazuh/wazuh/blob/4.3/LICENSE", "hostname": "ubuntu-jammy", "timestamp": "2023-02-09T10:28:49Z"}, "error": 0}
```
The returned `license_url` is `https://github.com/wazuh/wazuh/blob/4.3/LICENSE` when in 4.4.0 the user should receive something like `https://github.com/wazuh/wazuh/blob/4.4/LICENSE` or `https://github.com/wazuh/wazuh/blob/v4.4.0/LICENSE`

In addition, the `spec.yml` file related to the API license has the same error. The detected lines are:
- https://github.com/wazuh/wazuh/blob/master/api/api/spec/spec.yaml#L48
- https://github.com/wazuh/wazuh/blob/master/api/api/spec/spec.yaml#L7079

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Alreay fixed in https://github.com/wazuh/wazuh/commit/916669d9f1890a0b25c271164fb42539a453106e

**Comment by davidjiglesias** [comment]
We should also update https://github.com/wazuh/wazuh/blob/master/tools/bump_version.sh to properly bump the license in spec.yaml.
