### ISSUE TITLE
Allow the Wazuh agent compilation/sources installation in Apple silicon processors

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#16127]
## Description
Epic: https://github.com/wazuh/wazuh/issues/15055
The Wazuh agent should be able to be compiled in Apple silicon M1, M1 pro, M1 max, M2, M2 pro, and M2 max processors. 

## Tasks
- Modify the building process allowing the compilation in the mentioned processors.
- Modify the sources installation process allowing a native installation without Rosseta. 

## Validation
- The agent compiles the mentioned processors.
- The agent can be installed using sources in the mentioned processors.
- Syscollector should be able to retrieve the correct processor.

**Comment by lsayanes** [comment]
### AArch64 is a ARM64
Given that choice, the **_Apple Silicon M1_** (and **_M2_**) chip is an AArch64 architecture.

You can check the architecture of your own computer by opening the `Terminal` application, 
and running the following command: `arch`
On the M1 chip it will display: _**arm64**_
![imagen](https://user-images.githubusercontent.com/68856625/225128046-6e804996-fe51-4203-9492-70c050df9056.png)

### Cross Compile M1 or M2
To do a cross-compile for `M1` or `M2` Apple microchips,  it will be necessary to use a compiler that supports the ARM64 architecture. 

General steps to follow:

1. Install Xcode on Mac. 

    > 
    > Xcode includes the necessary compiler tools for cross-compiling.
    > An apple_id will be required.

2. Install the command line tools for Xcode. Open the Terminal and type the following command:

		`xcode-select –install`

3. Install the `homebrew` package manager. 
               Homebrew makes it easy to install the cross-compiler tools. Type the following command in the Terminal:

      > `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

4. Install the cross-compiler tools. In the Terminal, type the following command:

      > brew install gcc-arm64-binutils

This will install the `GNU Binutils` and `GCC cross-compiler` tools for the _**ARM64 architecture**_.

Possible _Makefile_ or _script_, set the following environment variables:

      > export CC=/usr/local/bin/aarch64-apple-darwin20-clang
      > export CXX=/usr/local/bin/aarch64-apple-darwin20-clang++

_My case:_
![imagen](https://user-images.githubusercontent.com/68856625/225132851-df8528cf-f332-4372-8619-25081b777c16.png)


**Note**: If the project uses third-party libraries or dependencies, It will be necessary to cross-compile those as well.


### macos-arm64-emulation
We found an interesting project on github that emulates Apple's M1 or arm64 (`aarch64`) microchip [here](https://github.com/cylance/macos-arm64-emulation).
_It has been tested on `Ubuntu`_ 
Some dependencies are necessary:

            > sudo apt-get install libxml2-dev
            > sudo apt-get install zlib1g-dev
            > sudo apt-get install pkg-config
            > sudo apt-get install libglib2.0-dev
            > sudo apt-get install libpixman-1-dev
                  


### QEMU
Emulating the Apple **M1** chip with QEMU is possible, but **_may not provide the same level of performance as running on native hardware_**. 

General steps to emulate the Apple `M1` chip with `QEMU`:

1. Download the latest version of QEMU and build it with the target architecture set to `aarch64 `

2. Download the firmware image for the Apple M1 chip. You can try using the firmware image provided by the "macos-arm64" project on GitHub.
 
3. Download an operating system image that is compatible with the Apple M1 chip. This could be an official Apple macOS image or a custom Linux distribution built for the ARM architecture.
 
4. Launch QEMU with the appropriate parameters to emulate the Apple M1 chip, including the path to the firmware image and the operating system image. You will also need to configure the amount of memory and CPU resources to allocate to the virtual machine.

Example command to launch QEMU with the Apple M1 chip emulation:

```
qemu-system-aarch64 \
    -machine virt,accel=hvf,highmem=off \
    -m 4G \
    -cpu cortex-a72 \
    -bios path/to/firmware.bin \
    -drive if=pflash,format=raw,readonly,file=path/to/firmware.bin \
    -drive if=none,file=path/to/os.img,id=hd0 \
    -device virtio-blk-device,drive=hd0 \
    -device virtio-net-device,netdev=net0 \
    -netdev user,id=net0 \
    -device qemu-xhci \
    -device usb-mouse \
    -device usb-kbd \
    -device usb-tablet

```

**Note** that the specific parameters may vary depending on the operating system and hardware configuration you are using. You may need to do additional research to get the emulation working correctly.
Overall, emulating the `Apple M1` chip with `QEMU` can be a useful tool for development and testing purposes, **but it is not a substitute for running on native hardware**.

### QEMU on VM

All efforts to run these tools on a virtual machine end in error: `unsupported machine type`

```
vagrant@ubuntu1:~$ ./run.sh
qemu-system-aarch64: -M macos11-j273-a12z,kernel-filename=kernelcache.release.j273.out,dtb-
filename=DeviceTree.j273aap.im4p.out,ramdisk-filename=arm64eSURamDisk.dmg.out,kern-cmd-args=
kextlog=0xfff cpus=1 rd=md0 serial=2 -noprogress,xnu-ramfb=off: unsupported machine type
Use -machine help to list supported machines
vagrant@ubuntu1:~$
```
