### ISSUE TITLE
remove_from_bucket argument in AWS wodle no functioning as expected

### ISSUE THREAD

**Issue by UranusBytes** [wazuh/wazuh#1618]
## Bug report

**OS**
CentOS 7

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

**Install type**
Manager

**Install method**
RPM Packages

**Log sample**

See below

Bug description
----------------

The `remove_from_bucket` argument doesn't seem to be functioning as expected.

1.  The documentation implies that the `remove_from_bucket` is only a valid option for the wodle (and not the bucket), when the code shows it as a valid option for both the wodle and the bucket.

2.  When the argument 'remove_from_bucket' is added to the wodle config, it doesn't appear to be sent as an argument to the python script. (The `--remove` argument is never added)
```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <remove_from_bucket>no</remove_from_bucket>
    <run_on_start>yes</run_on_start>
    <bucket type="cloudtrail">
      <aws_account_alias>myAlias</aws_account_alias>
      <name>myBucket</name>
      <aws_account_id>123412341234</aws_account_id>
      <iam_role_arn>arn:aws:iam::123412341234:role/myRole</iam_role_arn>
      <only_logs_after>2018-OCT-10</only_logs_after>
    </bucket>
  </wodle>
```

Log:
```
2018/10/10 13:47:12 wazuh-modulesd:aws-s3: DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket myBucket --remove --iam_role_arn arn:aws:iam::123412341234:role/myRole --aws_account_id 123412341234 --aws_account_alias myAlias --only_logs_after 2018-OCT-10 --type cloudtrail --debug 2
```  

If an invalid value (something other than yes/no) is used, it is correctly throwing an error, so the option is getting parsed.
```
2018/10/10 13:39:13 wazuh-modulesd: ERROR: Invalid content for tag 'remove_from_bucket' at module 'aws-s3'.
2018/10/10 13:39:13 wazuh-modulesd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```

3.  When the `remove_from_bucket` option is configured for the bucket, the behavior of the yes/no values seems to be opposite of what is expected.  When the argument `<remove_from_bucket>no</remove_from_bucket>` is added to the wodle config, it adds the `--remove` flag to the python script.  When a value of 'yes' is used, it does not. 

With config of:
```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <bucket type="cloudtrail">
      <aws_account_alias>myAlias</aws_account_alias>
      <remove_from_bucket>no</remove_from_bucket>
      <name>myBucket</name>
      <aws_account_id>123412341234</aws_account_id>
      <iam_role_arn>arn:aws:iam::123412341234:role/myRole</iam_role_arn>
      <only_logs_after>2018-OCT-10</only_logs_after>
    </bucket>
  </wodle>
```

Log:
```
2018/10/10 13:41:39 wazuh-modulesd:aws-s3: DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket myBucket --remove --iam_role_arn arn:aws:iam::123412341234:role/myRole --aws_account_id 123412341234 --aws_account_alias myAlias --only_logs_after 2018-OCT-10 --type cloudtrail --debug 2
```

4.  Lastly, one opinion:
IMO, the default value for remove_from_bucket should be 'no'.  From a security perspective, CloudTrail logs should not be deleted by default, but should be an explicit configuration by the end user

**Comment by UranusBytes** [comment]
Originally reported from https://groups.google.com/d/msg/wazuh/vBEJM9xC9u0/TcyxbuVNBAAJ

**Comment by druizz90** [comment]
Hi team,

I found the error that is causing this behaviour (point 3 of @UranusBytes bug description):
```C
if (strcmp(children[j]->content, "yes")) {
    cur_bucket->remove_from_bucket = 1;
} else if (strcmp(children[j]->content, "no")) {
    cur_bucket->remove_from_bucket = 0;
```
This code needs to be changed by:
```C
if (!strcmp(children[j]->content, "yes")) {
    cur_bucket->remove_from_bucket = 1;
} else if (!strcmp(children[j]->content, "no")) {
    cur_bucket->remove_from_bucket = 0;
```
About points 1 and 2, we should update the documentation (using `remove_from_bucket` parameter out of bucket section is deprecated).

I want to thank to @UranusBytes his work for catching this bug and contribute to improve this wodle.

Best regards,

Demetrio.
