### ISSUE TITLE
Which package does Tencent Tencent OS Server 3.1 Vulnerability need to pull to perform vulnerability scanning?

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16193]
![Uploading image.png…]()
Centos can be configured successfully, but Vulenerabilities of Tencent OS Server 3.1 cannot be installed
![Uploading image.png…]()

**Comment by MiguelazoDS** [comment]
Hi @PhuketIsland, 

I assume you want to use Vulnerability Detector on a Tencent OS, but let me ask some questions. 

> Which package does Tencent Tencent OS Server 3.1 Vulnerability need to pull to perform vulnerability scanning?

What do you mean with package? Could you successfully install Wazuh agent on that OS? Is the agent registered against a Wazuh manager? Is active? 

> Vulenerabilities of Tencent OS Server 3.1 cannot be installed

If you refer to the Vulnerability Detector module, the installation of that module comes with the installation of Wazuh in the manager. Vulnerability detector does not run in your agent. 

As far as I know, Tencent OS is compatible with Centos (as you said), so the option to perform vulnerability detector scans on that system is to use the allow_os option. 

Please take a look here: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html#scanning-unsupported-systems

Regards!

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/218949600-da3e9265-5ce0-4654-aa08-afdd0b6cfb4d.png)
you are right！
It is found that the token cannot be obtained according to the method given in the document
![image](https://user-images.githubusercontent.com/28825226/218949121-3026f283-a416-401d-8828-d307d0f4daf2.png)

![image](https://user-images.githubusercontent.com/28825226/218949500-b662a66f-838d-453a-8382-d4e35d4ddbfc.png)
How should Tencenos be configured for vulnerability scanning
![image](https://user-images.githubusercontent.com/28825226/218949915-c5fda6e7-1833-4d47-94cc-94776a373b19.png)
What should be written in this place？

**Comment by MiguelazoDS** [comment]
Try with `<os allow="Tencent Os-3">8</os>`. According to the webpage of TencentOS the version 3.1 is compatible with Centos 8. 
That will download the RHEL feeds to obtain the vulnerabilities, which may lead to a not very accurate detection since your OS is not natively supported. 

>  It is found that the token cannot be obtained according to the method given in the document

This is another topic not related to vulnerability detector, but here you're using the default credentials, you're being rejected for that reason, you may be using other custom credentials in your API.

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/219260079-e5318d15-5019-4029-aa18-dce9b0442396.png)
<os allow="Tencent Os-3">8</os>.According to your suggestion, the modification will only take effect on the centos system, and has no effect on Tencentos. Is it because Tencentos3 and cnetos8 have different virus seeds?
https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8-including-unpatched.oval.xml.bz2
This is the package of cnetos8 virus seed, but I can't find Tencentos

![image](https://user-images.githubusercontent.com/28825226/219260946-546a9ef4-97fc-427d-85b5-9c408693d3b4.png)
The connection between my agent and manager is set without password

**Comment by MiguelazoDS** [comment]
The setting should work for any non-supported OS based on Centos, but for this particular case Tencent it is not being taken into account as Rocky Linux for example. So let me play a little more with this to find the cause of the rejection. 

The CVE feeds are from RHEL not even from Centos, and many of those unsopported system don't have any feed so we rely on major releases to perform the scan. 

Respecting to the other issue, it works as expected. Something must be wrong with the credentials you're using, it is not related to the connection between agent and manager.

**Comment by MiguelazoDS** [comment]
Anyway, you can check the name of the operating system by querying the database. I misread the operating system name before in my environment. The configuration you should add is this, but please check you have the same. 

`<os allow="TencentOS-3">8</os>`

**Comment by PhuketIsland** [comment]
![image](https://user-images.githubusercontent.com/28825226/219594174-d756b607-3b22-4d0b-83f9-10f8c6b82b03.png)
Thank you very much. This configuration is right. I wish you a happy life

**Comment by MiguelazoDS** [comment]
Glad to know it worked! Regards!. I'm closing this issue now.
