### ISSUE TITLE
CentOS agent stress test shows a drop in memory usage

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16213]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least v4.4.0-rc1| All | Agent | Packages | CentOS 7|

In the analysis of the [DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP](https://github.com/wazuh/wazuh/issues/16179) stress test, a drop in memory usage was found in the `RSS` graph of the `wazuh-logcollector`, `wazuh-execd`, `wazuh-syscheckd`, `wazuh-agentd`, and `wazuh-modulesd` daemons

![image](https://user-images.githubusercontent.com/14913942/219042674-7feb7962-4e03-43a7-b250-6a55e47ee58e.png)

This behavior is not observed in Alpha2 or Beta1 graphs

<details><summary>Alpha2 and Beta1 RSS graphs</summary>

Alpha2
![image](https://user-images.githubusercontent.com/14913942/219042961-1dd2f6b0-99fb-4c14-8b61-6c1dead85be2.png)

Beta1
![image](https://user-images.githubusercontent.com/14913942/219043026-cbec1c08-9b01-44e3-bffe-2cfdde0d0ae1.png)

</details>

Related
- https://github.com/wazuh/wazuh/issues/16179
- https://github.com/wazuh/wazuh/issues/15790
- https://github.com/wazuh/wazuh/issues/15929

**Comment by vikman90** [comment]
After investigating this issue, I could not find any correlation between any event in the log and the memory behavior.

If we pay attention to the USS chart (USS does not count the memory occupied by shared libraries) (#16179), we note that Modulesd has a more fluctuant behavior than the rest of the processes. This may be related to jemalloc.

This chart shows the moving average of the USS (N=21):

![Unique set size](https://user-images.githubusercontent.com/10536251/220999226-44ee2670-d909-4d44-aeb9-1659370616ba.png)

However, this does not reveal any problem in the processes.
