### ISSUE TITLE
Feature to manage agent ID

### ISSUE THREAD

**Issue by FryggFR** [wazuh/wazuh#16212]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Manager | Manager/Agent | Packages | Ubuntu 22.04.1 LTS |

Hello Wazuh Team,

It is possible to add a feature to manage agent ID on dashboard ? Let me explain.
When you delete an agent using API or the CLI, you have a missing ID.

**Exemple**:
List of agent before deleting an agent:

  _001 Agent 
  002 Agent 
  003 Agent 
  004 Agent_ 

If i delete agent 002, the dashboard show me this:

  _001 Agent
  003 Agent
  004 Agent_

It's not really a problem, it's just not pretty to have missing IDs and it can be misleading.

**Comment by vikman90** [comment]
Hi @FryggFR,

I understand the issue, but what is your proposal? IDs must be unique identifiers for agents, we should not change the ID of an agent for two main reasons:
1. The agent ID is shared between the manager and the agent itself. If we changed an agent's ID, the cluster would be unable to synchronize its metadata. Also, the agent would be unable to connect back to the manager.
2. All alerts from an agent get stored in _wazuh-indexer_ with its ID. Changing an ID would make that agent's alerts hard to track.

On the other hand, the manager provides auto-incrementing ID numbers to new agents because it's faster than finding gaps among agent IDs. This also prevents ID collision in alerts.

This is a bit unsightly, especially when a few agents have been deleted, but it's a reliable way to avoid confusion. We were investigating how to solve the maximum ID limit (https://github.com/wazuh/wazuh/issues/6042#issuecomment-1007699405), and one of the proposals was to use UUIDs.

Best regards.

**Comment by FryggFR** [comment]
Hi @vikman90 

I didn't know that the ID had so much impact on the relationship between the agents and the server. When an agent is removed, it is not possible to release the ID at the same time?

Thanks for your answers.

**Comment by vikman90** [comment]
Hi @FryggFR,

Yes, the ID is released when we remove an agent, but that occurs in the cluster only (the set of managers). The manager won't delete the alerts related to that agent in the Indexer. On the other hand, the agent may hold its key and try to connect again.

In fact, you can reuse an ID when adding an agent manually. For instance:

<details><summary>1. Add an agent.</summary>

```shell
-X POST https://localhost:55000/agents \
    -H 'Content-Type: application/json' \
    -d '{"name": "test", "ip": "any"}'
```
```json
{
  "data": {
    "id": "001",
    "key": "MDAxIHRlc3QgYW55IDNiZjMwMzg0ZjY3MGUxMjEyZjc0NmVhYmE0MjJiMDZhNjE4MjdjMzk4M2RmYTk2OGZlYzJjMTRkNDU3ZDBhNTA="
  },
  "error": 0
}
```

</details>

<details><summary>2. Delete that agent.</summary>

```shell
-X DELETE "https://localhost:55000/agents?agents_list=001&status=all&older_than=0"
```
```json
{
  "data": {
    "affected_items": [
      "001"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were deleted",
  "error": 0
}
```

</details>

<details><summary>3. Add a new agent with the same ID.</summary>

```shell
key=$(< /dev/urandom hexdump --no-squeezing -e '/1 "%x"' | head -c 64)
wazuh-api -X POST https://localhost:55000/agents/insert \
    -H 'Content-Type: application/json' \
    -d '{"id": "001", "name": "test", "ip": "any", "key": "'$key'"}'
```
```json
{
  "data": {
    "id": "001",
    "key": "MDAxIHRlc3QgYW55IDczZjY5ZDVlNzFlMjMzZjllZGEwYWMzY2Q4Mzg0NTYwOGU5YTg2ODgyMjU1MjhhNmNmZGVlNTc1YTY0YzE5OTM="
  },
  "error": 0
}
```

Just so you know, we need to provide a random password. I've opened #16350 to let the API create a random one if it's undefined.

</details>

## Find unused IDs

<details><summary>unused-ids.sh</summary>

```shell
#! /bin/bash

id=0

< /var/ossec/etc/client.keys cut -d' ' -f1 | sort | while read i
do
    (( nextid = id + 1 ))
    
    while (( i > nextid ))
    do
        printf "%03d\n" $nextid
        (( nextid++ ))
    done

    (( id = nextid ))
done
```

</details>

### Insert an agent with a reused ID

```shell
id=$(./unused-ids.sh | head -n1)
name=AGENT_NAME
ip=any
key=$(< /dev/urandom hexdump --no-squeezing -e '/1 "%x"' | head -c 64)

wazuh-api -X POST https://localhost:55000/agents/insert \
    -H 'Content-Type: application/json' \
    -d '{"id": "'$id'", "name": "'$name'", "ip": "'$ip'", "key": "'$key'"}'
```

## Caveats

- If the agent that was previously removed produced some alerts, we will be unable to distinguish between the old agent and the new one.
- Such alerts will not be consistent with the new agent's inventory (by its ID).
- Despite the old agent having been decommissioned, it may be still pointing to the cluster. So, it may keep trying to connect and even request a new ID.

All of this is why IDs, despite being integers, are intended to uniquely identify an agent, and we don't recommend reusing them, except for some specific reason (overflowed integers?) and knowing the possible consequences.

I hope this helps.

Best regards.

**Comment by FryggFR** [comment]
Hi @vikman90 

Thanks for reply, i think will stay like this for this moment, that lot of work for not very much.

Thanks for your help.
