### ISSUE TITLE
Wrong behavior detected during Engine testing

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16223]
## Description

The team is working to add a new Engine that replaces analysisd. Since the QA team will [test its behavior](https://github.com/wazuh/wazuh-qa/issues/3619) to verify everything's ok, here will be placed all the issues grouped by component/feature so they can be handled easier.

## Bugs' issues

- Grouped

    - https://github.com/wazuh/wazuh/issues/16110
    - https://github.com/wazuh/wazuh/issues/16052
    - https://github.com/wazuh/wazuh/issues/15961
    - https://github.com/wazuh/wazuh/issues/15882

- Non-grouped

    - https://github.com/wazuh/wazuh/issues/15864
    - https://github.com/wazuh/wazuh/issues/15863
    - https://github.com/wazuh/wazuh/issues/15670
    - https://github.com/wazuh/wazuh/issues/16320
    - https://github.com/wazuh/wazuh/issues/16427
    - https://github.com/wazuh/wazuh/issues/16474
    - https://github.com/wazuh/wazuh/issues/16511
    - https://github.com/wazuh/wazuh/issues/16512
    - https://github.com/wazuh/wazuh/issues/16553
    - https://github.com/wazuh/wazuh/issues/16806
    - https://github.com/wazuh/wazuh/issues/16807
    - https://github.com/wazuh/wazuh/issues/16840
    - https://github.com/wazuh/wazuh/issues/16912
    - https://github.com/wazuh/wazuh/issues/16913
    - https://github.com/wazuh/wazuh/issues/16998
    - https://github.com/wazuh/wazuh/issues/17042
    - https://github.com/wazuh/wazuh/issues/17043
    - https://github.com/wazuh/wazuh/issues/17045

**Comment by JcabreraC** [comment]
All the tasks of the epic issue completed.
