### ISSUE TITLE
Wazuh agent for AIX can't load syscollector

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16220]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0-rc1 | wazuh-modulesd:syscollector | Agent | Packages | AIX 6.1 TL9 |

During the testing of the agent for AIX, the following error message was found:

```
2023/02/15 12:25:00 wazuh-modulesd:syscollector: ERROR: Can't load syscollector.
```

Related:
- https://github.com/wazuh/wazuh/issues/16148#issuecomment-1431860080
- https://github.com/wazuh/wazuh-packages/issues/1387#issuecomment-1084938543

**Comment by Dwordcito** [comment]
List of libraries to be loaded based on the aix search order for all C++ libraries.
```
bash-4.4# ldd /var/ossec/lib/libdbsync.so 
/var/ossec/lib/libdbsync.so needs:
         /var/ossec/lib/libwazuhext.so
         /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6)
         /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libgcc_s.a(shr.o)
         /usr/lib/libpthreads.a(shr_xpg5.o)
         /usr/lib/libc.a(shr.o)
         /unix
         /usr/lib/libpthreads.a(shr_comm.o)
         /usr/lib/libcrypt.a(shr.o)
```

Here we find two things, the first is that the specific library for syscollector is not being deployed(this is a cause of the .a extension in AIX servers.), as added in the feature https://github.com/wazuh/wazuh/pull/14190 and then it is not being established for the search order of the libraries.

Regardless of this problem, I also find that it is compiling with the wrong libstdc++, since it does not have support for pthread as indicated by the dlerror output when trying to load the libsyscollector.so

```
2023/02/15 22:18:25 wazuh-modulesd:syscollector: ERROR: Symbol resolution failed for /var/ossec/lib/librsync.so because:
        Symbol _ZSt11__once_call (number 10) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
        Symbol _ZSt15__once_callable (number 11) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
        Symbol _ZTINSt13__future_base12_Result_baseE (number 20) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
        Symbol _ZTINSt6thread6_StateE (number 21) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
        Symbol __once_proxy (number 27) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
        Symbol _ZNSt6thread4joinEv (number 28) is not exported from dependent
          module /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/libstdc++.a(libstdc++.so.6).
Additional errors occurred but are not reported.
Examine .loader section symbols with the 'dump -Tv' command.


```

**Comment by Dwordcito** [comment]
Technically it's not a problem to ship the library with pthread support for aix, but it's too weight-limiting for the libraries to distribute, and based on how AIX treats dynamic libraries, there's no easy feasibility for this problem.

The solution will come from linking again only for AIX the binaries with the c++ standard library and gcc_s in a static way.

bash-4.4# ls -l /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/pthread/libstdc++.a | awk '/d|-/{printf("%.3fMB %s\n",$5/(1024*1024),$9)}'
39.234MB /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/pthread/libstdc++.a
