### ISSUE TITLE
Exploratory testing: FIM realtime support for macOS and BSD

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#16230]
## Description

This issue will be addressed once the development of FIM real-time support for macOS has finished so we can guarantee that everything works as expected.

### DoD

- [x] Run Coverity (changes doesn't affect code)
- [x] Run FIM stress tests for macOS agents (Jenkins is off)
- [x] Run FIM RTR (pull request checks)
- [x] Run FIM test tool (pull request checks)
- [x] Perform exploratory testing to verify everything works as expected and also which versions we support:
  - [x] macOS Sierra
  - [x] macOS Mojave
  - [x] macOS Monterey or higher
  - [x] FreeBSD
  - [x] OpenBSD (https://github.com/wazuh/wazuh/issues/16388)
  - [x] NetBSD (https://github.com/wazuh/wazuh/issues/16387)
  - [x] Linux

## Template for manual testing 

- [ ] Compile the agent without warnings

**Scan**

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata which must be switched to realtime

**Synchronization**

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by mjcr99** [comment]
## Mac OS 10.12 (Sierra)

- [ ] Compile the agent without warnings

**Scan**

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata which must be switched to realtime

**Synchronization**

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by mjcr99** [comment]
## FreeBSD 13

- [ ] Compile the agent without warnings

**Scan**

- [ ] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [ ] Monitor a folder with whodata which must be switched to realtime

**Synchronization**

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by mjcr99** [comment]
## Ubuntu 22

- [x] Compile the agent without warnings

**Scan**

- [x] Run a baseline and check it is properly synced with the manager
- [ ] Run a scheduled scan forcing an insertion/modification/deletion
  - [ ] Every alert has the correct fields
  - [ ] The database is properly updated for every change
- [x] Monitor a folder with realtime to generate an insertion/modification/deletion (if supported)
  - [x] Every alert has the correct fields
  - [x] The database is properly updated for every change
- [ ] Monitor a folder with whodata which must be switched to realtime

**Synchronization**

- [ ] The sync process runs every interval
- [ ] When databases are synced, the sync process is just a message with the checksum verification
- [ ] Test sync: check both databases are synced, stop agent, add/modify/delete some monitored files, start agent. Databases should be synced again.

**Comment by chemamartinez** [comment]
Everything seems to be good.
