### ISSUE TITLE
Default FIM paths for Windows use capital C as label

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1624]
## Bug report

**OS**
_Windows 10_

**Wazuh version**
_3.7_

**Wazuh API version**
_3.7_

**Install type**
_manager/agent_

**Install method**
_packages_

Bug description
----------------

Default paths monitored by FIM hardcode C:\ with capital letters. They should be transformed to lowercase.

**Comment by cristgl** [comment]
Fixed at https://github.com/wazuh/wazuh/pull/1630.
