### ISSUE TITLE
<different_field> Not working as expected

### ISSUE THREAD

**Issue by federicobaldoni-nextegy** [wazuh/wazuh#16249]
| Wazuh version | OS version|
| Wazuh v4.3.8 | Ubuntu 22.04.1 LTS |

### Description

While trying to create a rule for possible syn scans in combination with suricata, i noticed a weird behaviour with the `<different_field>` label in the wazuh rules syntax.

This is a sample of the suricata logs sent to wazuh:
```
{"timestamp":"2023-02-20T15:27:57.660570+0100","flow_id":546824556188762,"in_iface":"ens32","event_type":"alert","vlan":[80],"src_ip":"192.168.72.66","src_port":51687,"dest_ip":"192.168.80.20","dest_port":601,"proto":"TCP","alert":{"action":"allowed","gid":1,"signature_id":27,"rev":0,"signature":"Data for SYN scan - TMP rule","category":"","severity":3},"flow":{"pkts_toserver":1,"pkts_toclient":0,"bytes_toserver":66,"bytes_toclient":0,"start":"2023-02-20T15:27:57.660570+0100"}}
```

This is the wazuh rule i created: 
```
<rule id="100090" level="12" frequency="5" timeframe="100" ignore="500">
    <if_matched_sid>86601</if_matched_sid>
    <field name="alert.signature">Data for SYN scan - TMP rule</field>
    
    <same_field>src_ip</same_field>
    <same_field>dest_ip</same_field>
    <different_field>dest_port</different_field>
    <description>SYN Scan Detection</description>
</rule>
```

### Expected behaviour
The rule with id `100090` triggers only if:
- There are 5 alerts with id `86601` in a timeframe of 100s;
- Those 5 alerts should have all the same `src_ip` and the same `dest_ip`;
- **Those 5 alerts all have a different `dest_port`**.

### Actual behaviour
The rule with id `100090` triggers if:
- There are 5 alerts with id `86601` in a timeframe of 100s;
- Those 5 alerts should have all the same `src_ip` and the same `dest_ip`;
- **Those 5 alerts have less than 5 different  `dest_port`, but those alternated in the logs**.
   e.g.
   ```
   Logs:
   {....."dest_port":100,...}
   {....."dest_port":101,...} -> any port that is different from 100 will work
   {....."dest_port":100,...} 
   {....."dest_port":101,...} -> any port that is different from 100 will work
   {....."dest_port":100,...}
   {....."dest_port":101,...} -> any port that is different from 100 will work
   {....."dest_port":100,...}
   {....."dest_port":101,...} -> any port that is different from 100 will work
   {....."dest_port":100,...} -> rule 100090 triggered
   ```

**Comment by 72nomada** [comment]
This is related to https://github.com/wazuh/wazuh/issues/8898

**Comment by federicobaldoni-nextegy** [comment]
> This is related to #8898

Thank you
