### ISSUE TITLE
Resume resume Vulnerability Detector Windows help #16247

### ISSUE THREAD

**Issue by externaldeveloper2** [wazuh/wazuh#16256]
Thank you so much for your time and your answer.

I got it, but my next question is what is the next step?

Now I have the MSU JSON file containing the root KB and the Supersed kbs "Superseded by" and I have the installed KB in the Windows OS what is the next step how can I get the missing KB and the Vuln (as vuln i think i know how, when get the missing KB I can get the cves for this vuln)

in other words how you can detect the missing KB

**Comment by MarcelKemp** [comment]
I will close this issue to avoid duplicate questions.
Here is the answer: https://github.com/wazuh/wazuh/issues/16247#issuecomment-1440222152

If you still have questions on the same topic, please ask them in issue https://github.com/wazuh/wazuh/issues/16247.
Thank you for your understanding.
