### ISSUE TITLE
Windows Wazuh agent fails to update or delete wazuh-agentd.state when service stopped

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#16253]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Wazuh Agent | Agent | Packages | Windows |

Based on what appears to be the Linux Wazuh agent's proper handling of **wazuh-agentd.state** in response to the agent service being stopped (deletion of the state file):

```
root@server:~# systemctl stop wazuh-agent
root@server:~# cat /var/ossec/var/run/wazuh-agentd.state
cat: /var/ossec/var/run/wazuh-agentd.state: No such file or directory
```

...it appears that the Windows Wazuh agent is failing to account for the service being stopped with respect to its handling of **wazuh-agentd.state**.  Windows neither changes the "status" line in the state file nor deletes the state file.

```
PS C:\Program Files (x86)\ossec-agent> net stop wazuh

The Wazuh service was stopped successfully.

PS C:\Program Files (x86)\ossec-agent> type wazuh-agent.state
# State file for wazuh-agent

# Agent status:
# - pending:      waiting to get connected.
# - connected:    connection established with manager in the last 10 seconds.
# - disconnected: connection lost or no ACK received in the last 60 seconds.
status='connected'

# Last time a keepalive was sent
last_keepalive='2023-02-20 11:55:58'

# Last time a control message was received
last_ack='2023-02-20 11:55:58'

# Number of generated events
msg_count='81725'

# Number of messages (events + control messages) sent to the manager
msg_sent='97247'

# Number of events currently buffered
# Empty if anti-flooding mechanism is disabled
msg_buffer='0'

```

For scripts running on the agent side that need to evaluate if the agent is truly connected to the Wazuh manager, this gives a false positive claiming that the agent is connected even though the service is not running at all.  

Please make the Windows behavior consistent with the Linux behavior in this area.  The simple addition of a state file deletion upon agent service shutdown should do the trick nicely.

Thanks,
Kevin

**Comment by vikman90** [comment]
Hi @branchnetconsulting,

Thanks for reporting this bug. I've reproduced it from v3.0.0 to 4.3.10. In effect, WPK upgrade removes it just before installing ([do-upgrade.ps1](https://github.com/wazuh/wazuh/blob/36d17b36a732ecc4b4bffda7ddd047d60a3c79ac/src/win32/do_upgrade.ps1#L301)), as it needs to check that the agent creates it again.

Adding this bug to the roadmap. We will keep you posted.

Thank you!
Best regards.

**Comment by j0serca** [comment]
Hi @vikman90 , are there any updates on this? Do you have any estimation of when this bug will be fixed?
Thank you!

**Comment by branchnetconsulting** [comment]
Has this been addressed yet?  It is still broken at least as recently as 4.4.5.

**Comment by vikman90** [comment]
@j0serca @branchnetconsulting this issue is still in the backlog.

**Comment by vikman90** [comment]
## Status change

Working in branch [fix/16253-delete-agent-state](https://github.com/wazuh/wazuh/compare/4.7.1...fix/16253-delete-agent-state).
Target version: TBD.

I've gotten the agent to delete the file on service stop:

|Before|After|
|---|---|
|![Screenshot 2023-11-20 131845](https://github.com/wazuh/wazuh/assets/10536251/922edcb9-41e9-4b2f-a4f6-ab14b8aa9613)|![Screenshot 2023-11-20 131854](https://github.com/wazuh/wazuh/assets/10536251/38773915-7f85-4fd4-99f3-b02489b5c0c1)|

### Next step

- QA integration test.

**Comment by vikman90** [comment]
This issue stays on-hold by https://github.com/wazuh/wazuh/issues/17737.
We're moving ETA to Feb. 23rd.
