### ISSUE TITLE
Integrate API metrics

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16274]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## API metrics
Research and list API metrics. Each metric must be clearly defined and documented, so its meaning and usage is clear. 
These metrics must help the administrator with capacity planning and debugging performance issues:

 - [x] Research and list API metrics.
   - [x] Number of request (Counter).
   - [x] Number of failed responses (Counter).
   - [x] Response latency (Histogram).
   - [x] Connected sockets (updown counter).
  - [x] Implement API metrics.
 - [x] Run and update Unit test.
 - [x] Update the user manual. 

Each module of the engine needs appropriate metrics as well. We must complete each module metrics after carefully considering its value.

**Comment by NahuFigueroa97** [comment]
### :green_circle: API module metrics
```
./main metrics list
 api.ConnectedSockets,UpDownCounter,enabled
 api.ResponseTime,Histogram,enabled
 api.TotalFailedRequest,Counter,enabled
 api.TotalRequest,Counter,enabled
```
