### ISSUE TITLE
Integrate Runtime / functional metrics

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16275]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Runtime / functional metrics
Research and list Runtime / functional metrics. Each metric must be clearly defined and documented, so its meaning and usage is clear. These metrics must help the administrator with capacity planning and debugging performance issues:

 - [ ] Research and list Runtime / functional metrics.
   - For every decoder, rule, filter and output
     - [ ]  Events which have been accepted.
     - [ ]  Events which have been rejected.
   - Environment metrics
     - [ ] Flowchart TD.
 - [ ] Update the design document. 
 - [ ] Update the user manual. 

Each module of the engine needs appropriate metrics as well. We must complete each module metrics after carefully considering its value.

For example, for an environment like this one:

```mermaid
flowchart TD
  input --> decoders

  subgraph decoders
    dec-A --> dec-B
    dec-A -->  dec-C 
    dec-A --> dec-D
  end

 decoders --> rules

  subgraph rules
    rul-A --> rul-B
    rul-A -->  rul-C 
    rul-A --> rul-D
  end

 decoders --> outputs
 rules --> outputs
 
  subgraph outputs
    out-A --> out-B
    out-A -->  out-C 
    out-A --> out-D
  end

```

**Comment by Dwordcito** [comment]
This will be worked on: https://github.com/wazuh/wazuh/issues/24542
