### ISSUE TITLE
Integrate System metrics

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16270]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## System metrics
Research and list System metrics. Each metric must be clearly defined and documented, so its meaning and usage is clear. 
These metrics must help the administrator with capacity planning and debugging performance issues:

 - [ ] Research and list System metrics.
   - [ ] Buffered events in a point of time (gauge counter)
 - [ ] Implement System metrics.
 - [ ] Update the design document. 
 - [ ] Update the user manual. 

Each module of the engine needs appropriate metrics as well. We must complete each module metrics after carefully considering its value.

**Comment by Dwordcito** [comment]
This will be worked on: https://github.com/wazuh/wazuh/issues/24542
