### ISSUE TITLE
Slack notifications per agent group and in alerts list 

### ISSUE THREAD

**Issue by y0d4a** [wazuh/wazuh#16292]
Hi, 
i have two question/request:
1. Is it possible to separate slack alerts per agent groups (i have two env. and would like to separate alerts per agent group)?
2. Can i add comment (looking for owner field) for client name? for example in alerts list to see column with custom filed (i would like to add owner of system manually)..

thank you

**Comment by GabrielEValenzuela** [comment]
Hi y0d4a ! How are you ? 

We are currently working in this feature #14479 that may help you with your customizations. For now, you can only modify the fields described in our documentation, here in the [integrations](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#integration) section.

If you need anything more, please don't dub to ask.
We're here to help 😃 
Have a nice day!

**Comment by y0d4a** [comment]
Hey Gabriel, i am good, which hope you are too :)
It is great that you are working on it, fairly it is great integration for alerting purpose :)
i will wait update, thank you so much on answer and wish you all the best!
