### ISSUE TITLE
FIM issues for Wazuh v3.7.0

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#1631]
## Bug report

**Wazuh version**
3.7.0-3708

FIM is experimenting a weird behavior depending on the `alert_new_files` parameter, when it is set to `yes`, a restart of `analysisd` sometimes generates previous alerts about the stored files in the FIM database, no matter if `syscheck` is running or not.

On the other hand, when `alert_new_files` is set to `no`, every FIM event is discarded showing the following log message:

```
2018/10/11 08:26:08 ossec-analysisd: DEBUG: Alert discarded (alert_new_files = no). File ‘/root/syscheck-realtime/realtime1’
```

## Bug check list

- [x] Discarted modification alerts when `alerts_new_files` is set to `no`. [602751c](https://github.com/wazuh/wazuh/commit/602751c43b8b66ffe9ebbbcc48013450b4e73e20)
- [x] At the first FIM scan, alerts about added files were shown. [0008ada](https://github.com/wazuh/wazuh/commit/0008ada326d609d49de17572bba1b945f3b73bbb)
- [x] Whodata fields are missing in JSON alerts. [396f803](https://github.com/wazuh/wazuh/commit/396f803dfbb2481f15a6971b1ea562d327866489)
- [x] Duplicated alerts about removed files. [d78c514](https://github.com/wazuh/wazuh/commit/d78c51414997f5f9a8385073a8cb8aa397b6d0e3)
- [x] Whodata doesn't work while the frequency scan is running. [2b43d45](https://github.com/wazuh/wazuh/commit/2b43d452a6d51961ae4a6826aa83319f7d7d634e)

**Comment by chemamartinez** [comment]
Working on https://github.com/wazuh/wazuh/tree/fix-fim-newalerts

**Comment by chemamartinez** [comment]
When appearing repeated remove alerts, the second one doesn't contain whodata information:

```
{"timestamp":"2018-10-15T00:54:42.925-0700","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","mail":false,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"]},"agent":{"id":"000","name":"ubuntu"},"manager":{"name":"ubuntu"},"id":"1539590082.7595","full_log":"File '/root/syscheck-realtime/whodata2' was deleted.\n(Audit) User: 'root (0)'\n(Audit) Login user: 'root (0)'\n(Audit) Effective user: 'root (0)'\n(Audit) Group: 'root (0)'\n(Audit) Process id: '17644'\n(Audit) Process name: '/bin/rm'\n","syscheck":{"path":"/root/syscheck-realtime/whodata2","event":"deleted"},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}
{"timestamp":"2018-10-15T00:58:10.442-0700","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","mail":false,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"]},"agent":{"id":"000","name":"ubuntu"},"manager":{"name":"ubuntu"},"id":"1539590290.8000","full_log":"File '/root/syscheck-realtime/whodata2' was deleted.\n","syscheck":{"path":"/root/syscheck-realtime/whodata2","event":"deleted"},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}
```

**Comment by Cerv1** [comment]
> A removed file monitoring in real-time, its corresponding deletion alert is generated. However, in the next frequency scan, it is reported again.

Fixed: https://github.com/wazuh/wazuh/commit/d78c51414997f5f9a8385073a8cb8aa397b6d0e3

**Comment by Skeptor** [comment]
The first scan no longer generate alerts for the scanned files.
Fix : https://github.com/wazuh/wazuh/commit/0008ada326d609d49de17572bba1b945f3b73bbb
