### ISSUE TITLE
Can wuzuh access enterprise WeChat for alarm?

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16311]
I want to notify security personnel of alarms with level greater than 12 through enterprise WeChat. How should I configure this? Are there any documents or examples for reference?

**Comment by TheMuntu** [comment]
Hi @PhuketIsland,
The [Integrator](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#reference-ossec-integration) daemon allows Wazuh to connect to external APIs and alerting tools such as Slack, PagerDuty, and VirusTotal.
Take a look at this [documentation and examples ](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html)on how to integrate Wazuh with external APIs. 

In case of WeChat, you can refer directly to the [custom integration section](https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html?highlight=integration#custom-integration).
You'll need to provide in the configuration field your WeChat Webhook and API key to make it work!

I hope this helps you!

**Comment by PhuketIsland** [comment]
Thank you very much. Is there a link to relevant documents?
