### ISSUE TITLE
Sorting distributed array API calls isn't working when cluster is enabled

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#1632]
Hello team,

When sorting by a nested field in experimental syscollector API calls the following error is shown:
```javascript
$ curl -u foo:bar -k -X GET "https://127.0.0.1:55000/experimental/syscollector/netiface?pretty&limit=2&sort=rx_bytes"
{
   "error": 1403,
   "message": "Sort field invalid: Allowed sort fields: name, tx, scan, rx, mac, mtu, state, agent_id, type. Fields: rx_bytes"
}
```
The error says it is only allowed to sort by _rx_... Why? After forwarding a distributed request to all solver nodes, all received responses are merged:
https://github.com/wazuh/wazuh/blob/38a2aef62d5c0e623917d4b08ed502cd9ee0f16a/framework/wazuh/cluster/dapi/dapi.py#L202

When merging, all received responses are sorted:
https://github.com/wazuh/wazuh/blob/38a2aef62d5c0e623917d4b08ed502cd9ee0f16a/framework/wazuh/cluster/dapi/dapi.py#L306-L308

And when sorting, if the values to sort are dictionaries, their fields are checked:
https://github.com/wazuh/wazuh/blob/38a2aef62d5c0e623917d4b08ed502cd9ee0f16a/framework/wazuh/utils.py#L151-L153

Since the responses came nested from each node, the field names are now the 1st level of nesting in the dictionary. Resulting in a error if the requested sort field is nested (`rx_bytes` and `rx` for example).

Best regards,
Marta

**Comment by JmZero** [comment]
# Status update
## Summary
I have begun to work on this issue. I have been debugging the code to be able to see the current structure of the call because since the issue was opened changes have been made in the code

## Tasks
* [1.5h] Debuggin code
* [1h] Try understand how the call works 

## Difficulties
* Code change

## Pending
* Find out why after the call total items go from 2 to 6 in an environment with 3 agents

**Comment by JmZero** [comment]
During the development of the solution we have encountered the following problems:
- The formatting of the output is done before merging the results of the different nodes, so it's more complex to order it.
- We sort the parameters 2 times, once in each node and once after merging the results.

In case of formatting the answer after merging the results we find more problems:
- If we format, all fields that have the character `_` will be nested, even if they aren't nested fields.
- If we only have 1 node, we couldn't format the response because formatting it could conflict with other calls.

In both cases it would be convenient to use a param that indicates for each call the keys of the nested fields.

**Comment by crd1985** [comment]
That param should be managed at distributed API level, what impacts our current development on 4.0 release.

I suggest doing all this rework directly on 4.0 and put off this issue until then. Otherwise, the job should be done twice...

**Comment by AdriiiPRodri** [comment]
Hi team,

Currently, in the most recent versions of Wazuh (>=4.0.0) this bug is fixed, here we can see an example:
```
adriiiprodri@wazuh curl -k -X GET "https://localhost:55000/experimental/syscollector/netiface?sort=rx.bytes&pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "rx": {
               "bytes": 478605,
               "dropped": 0,
               "errors": 0,
               "packets": 1121
            },
            "scan": {
               "id": 0,
               "time": "2021-05-24T07:28:29Z"
            },
            "tx": {
               "bytes": 66345,
               "dropped": 0,
               "errors": 0,
               "packets": 828
            },
            "mtu": 1500,
            "mac": "02:42:ac:12:00:06",
            "type": "ethernet",
            "state": "up",
            "name": "eth0",
            "agent_id": "001"
         },
         {
            "rx": {
               "bytes": 711490,
               "dropped": 0,
               "errors": 0,
               "packets": 1946
            },
            "scan": {
               "id": 0,
               "time": "2021-05-24T07:37:20Z"
            },
            "tx": {
               "bytes": 2738149,
               "dropped": 0,
               "errors": 0,
               "packets": 2177
            },
            "type": "ethernet",
            "mac": "02:42:ac:12:00:03",
            "state": "up",
            "mtu": 1500,
            "name": "eth0",
            "agent_id": "000"
         }
      ],
      "total_affected_items": 2,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All specified syscollector information was returned",
   "error": 0
}
```

```
adriiiprodri@wazuh curl -k -X GET "https://localhost:55000/experimental/syscollector/netiface?sort=-rx.bytes&pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "rx": {
               "bytes": 711490,
               "dropped": 0,
               "errors": 0,
               "packets": 1946
            },
            "scan": {
               "id": 0,
               "time": "2021-05-24T07:37:20Z"
            },
            "tx": {
               "bytes": 2738149,
               "dropped": 0,
               "errors": 0,
               "packets": 2177
            },
            "type": "ethernet",
            "mac": "02:42:ac:12:00:03",
            "state": "up",
            "mtu": 1500,
            "name": "eth0",
            "agent_id": "000"
         },
         {
            "rx": {
               "bytes": 478605,
               "dropped": 0,
               "errors": 0,
               "packets": 1121
            },
            "scan": {
               "id": 0,
               "time": "2021-05-24T07:28:29Z"
            },
            "tx": {
               "bytes": 66345,
               "dropped": 0,
               "errors": 0,
               "packets": 828
            },
            "mtu": 1500,
            "mac": "02:42:ac:12:00:06",
            "type": "ethernet",
            "state": "up",
            "name": "eth0",
            "agent_id": "001"
         }
      ],
      "total_affected_items": 2,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All specified syscollector information was returned",
   "error": 0
}
```

We close this issue once we have verified the correct functionality of this endpoint.

Best regards,
Adrián Peña
