### ISSUE TITLE
Authentication failures/successes

### ISSUE THREAD

**Issue by anelson97** [wazuh/wazuh#16340]
I'm very new to using Wazuh and it appears that authentication failures/successes are not working. They do work for the wazuh-server. Is there additional rules I need to put in place for authentication failures/successes to be logged for Windows agents?

**Comment by shehrozchishty** [comment]
Wazuh by default handle these authentication failure/success attempts for any endpoint including windows. I've attached windows alerts (Logon - success/failure) and some other alerts. Each alert is associated with a rule id present in the last column of the table.
![wineve](https://user-images.githubusercontent.com/96777711/223628818-feb4c02b-a778-47d7-b80f-c1ccb0178c58.JPG)

**Comment by anelson97** [comment]
This is all that I'm seeing. I have tried logging in and logging off and it is not showing up in the security events.

![image](https://user-images.githubusercontent.com/127221110/223741475-459c6d4e-ae08-485b-8e28-00f8c9812241.png)

**Comment by anelson97** [comment]
I solved this issue. I created a GPO to configure an audit policy for logon/logoff events. Now it works.

**Comment by Nabil-Mohammed** [comment]
Could you please elaborate how you solved the issue?

**Comment by anelson97** [comment]
I configured a GPO to Audit account logon events. In Group Policy Mangement this is found under Computer Configuration - Policies - Windows Settings - Security Settings - Local Policies/Audit Policy

**Comment by Nabil-Mohammed** [comment]
Thanks a lot, it worked
