### ISSUE TITLE
Design implementation to fulfill task requirements for Wazuh integration as a subscriber

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#16352]
# Description
This task aims to design the implementation for Wazuh to become a subscriber to Amazon Security Lake, including establishing cross-account access, setting up proper integration, and testing subscribers' functionality. The design should specify the architecture and components required for integration and consider any potential security or privacy implications.

# Deliverables

- Architecture design and schema
- Used tools and technologies

**Comment by Selutario** [comment]
# 2. Used tools and technologies

WIP

**Comment by FelipeKnudsen** [comment]
![Diagram](https://user-images.githubusercontent.com/80284649/224388847-34372072-3f83-4ce4-a0ea-d0818e543f52.jpg)
