### ISSUE TITLE
Add agent full endpoint won't take the id parameter if the key is undefined

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#16350]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.3 | API | Manager |

<details><summary>1. Add an agent</summary>

```shell
-X POST https://localhost:55000/agents \
    -H 'Content-Type: application/json' \
    -d '{"name": "test", "ip": "any"}'
```
```json
{
  "data": {
    "id": "001",
    "key": "MDAxIHRlc3QgYW55IDNiZjMwMzg0ZjY3MGUxMjEyZjc0NmVhYmE0MjJiMDZhNjE4MjdjMzk4M2RmYTk2OGZlYzJjMTRkNDU3ZDBhNTA="
  },
  "error": 0
}
```

</details>

<details><summary>2. Delete that agent</summary>

```shell
-X DELETE "https://localhost:55000/agents?agents_list=001&status=all&older_than=0"
```
```json
{
  "data": {
    "affected_items": [
      "001"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were deleted",
  "error": 0
}
```

</details>

<details><summary>3. Add a new agent with the same ID</summary>

```shell
-X POST https://localhost:55000/agents/insert \
    -H 'Content-Type: application/json' \
    -d '{"id": "001", "name": "test", "ip": "any"}'
```
```json
{
  "data": {
    "id": "002",
    "key": "MDAyIHRlc3QgYW55IDhlM2ZkZDllYWMyNDc5MDA5YjgzOGIxYTJlYjYwMjA4OTc0ZDU4MDFjZWQ3ZmFhZjMwM2U2NGE0NjVhODNmNjk="
  },
  "error": 0
}
```

</details>

**The new agent has ID 002, though we define ID=001.** This seems to be caused by not having defined a key.

### Alternative

If we do step 3 using Authd directly, it assigns ID 001:

<details><summary>3(b). Add a new agent with the same ID using Authd</summary>

```sh
echo -n '{"function": "add", "arguments": {"id": "001", "ip": "any", "name": "test"}}' | secure-tcp.py /var/ossec/queue/sockets/auth
```

```json
{
  "error": 0,
  "data": {
    "id": "001",
    "name": "test",
    "ip": "any",
    "key": "78107cf327385b85a6418f639b7688af169171c3c9abf82cf929ca28439b77cb"
  }
}
```

</details>

## Expected behavior

- If the `id` is undefined, assign a new one automatically: `max(ID) + 1`.
- If the `key` is undefined, create a random password.

The above points should be independent of each other.

**Comment by GGP1** [comment]
### Technical Analysis

The ID is not being set as an argument in the message sent to authd if no key is provided by the user:

```py
if id and key:
    msg["arguments"].update({"id": id, "key": key})
```

If, for example, we set a key or we change the condition to only check whether an id exists, it includes the id as an argument in the message and the authd service has it into account when creating the agent.

### Versions

I've tested the above change in **4.3** but checking **4.2** and **4.0** the conditions work the same way, so it's probable that the bug is there from that release or even before.

**Comment by GGP1** [comment]
## Update

Created PR with the changes and moved the issue to cross-review.

**Comment by GGP1** [comment]
## Update

Submitted requested changes by reviewer and moved the issue to cross-review.

**Comment by GGP1** [comment]
## Update

Rebased branch to `4.4.1` and changed status to Pending Review.
