### ISSUE TITLE
Detected errors for Red Hat Enterprise Linux 9 SCA policy rework - Checks 1 - 1.1.2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16355]
| Component | Action type           | Main Issue 
| --- | --- | ---
| SCA       | Rework |  #14358 

### Description

Regarding https://github.com/wazuh/wazuh/issues/15461 development, it has been created an automated script to parse the policy PDF file. This parsed policy has been used to check RHEL9 rework CIS policy, detecting some errors missed in https://github.com/wazuh/wazuh-qa/issues/3815 testing. It is proposed the following suggestions:

<details>

<summary> 1.1.5.1 :red_circle: </summary>

- **Compliance**: :red_circle:

Wrong MITRE Techniques

Expected:
```
- mitre_techniques: ["T0005", "T1499", "T1499.001"]
```

Current
```
- mitre_techniques: ["TA0005", "T1499", "T1499.001"]
```

</details>

<details>

<summary> 1.1.8.4 :red_circle: </summary>

**Compliance**:

**Mitre Techniques**

Expected:
```
- mitre_techniques: ["T1548", "T1548.001"]
```

Current:
```
- mitre_techniques: ["T1548, T1548.001"]
```

</details>

<details>

<summary> 1.2.2 :red_circle: </summary>

**Compliance**:

ISO: No expected ISO value for this check 

</details>

**Comment by jk-olaoluwa** [comment]
https://github.com/wazuh/wazuh/issues/16355#issue-1617632064

1.1.5.1 🔴 - We have removed this because it is not a valid technique
1.1.8.4 🔴 - Solved
1.2.2 🔴 - Solved

**Comment by Rebits** [comment]
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/16016/commits/86fc6094f60ecbc45fae42b789507e8ad4b04538 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  RHEL |    9     | Vagrant |    roboxes/rhel9 |


### Tested packages

| `wazuh-manager` |
| --------------- |
| [wazuh-managerv-4.4.0-1](https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.4.0-1.x86_64.rpm)            |

***

## Testing results

<details>

<summary> 1.1.5.1 :green_circle: </summary>


**Compliance**: :green_circle:

</details>


<details>

<summary> 1.1.8.4 :green_circle: </summary>

**Compliance**: :green_circle:

</details>


<details>

<summary> 1.2.2 :green_circle: </summary>

**Compliance**: :green_circle:

</details>
