### ISSUE TITLE
Unsigned Repositories for 2.x Versions

### ISSUE THREAD

**Issue by lcalvarez** [wazuh/wazuh#1637]
## Bug report

**OS**
_Ubuntu18.04/Bionic_

**Wazuh version**
_2.1.1_

**Install type**
_agent_

**Install method**
_packages_

**Log sample**

```
TASK [wazuh-agent : Debian/Ubuntu | Installing repository] *****************************************************************************
fatal: [172.16.255.186]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Connection to 172.16.255.186 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7rzsFp/ansible_module_apt_repository.py\", line 565, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7rzsFp/ansible_module_apt_repository.py\", line 553, in main\r\n    cache.update()\r\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 543, in update\r\n    raise FetchFailedException(e)\r\napt.cache.FetchFailedException: E:Failed to fetch https://packages.wazuh.com/apt/dists/xenial/InRelease  403  Forbidden [IP: <redacted>], E:The repository 'https://packages.wazuh.com/apt xenial InRelease' is no longer signed.\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

Bug description
----------------

I am running an ansible command with the following parameters to generate a repository file in `/etc/apt/sources.list.d`:

```
apt_repository:
    repo: "deb https://packages.wazuh.com/apt xenial main"
    state: present
```

I am following the instructions in [the 2.1 docs](https://documentation.wazuh.com/2.1/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html) to install the wazuh agent and have already installed the key in the proper location, as well.

I am also able to bypass this using an option to not validate certificates but that is a vulnerability that we would like to not expose ourselves to.

Shouldn't these repositories continue to stay signed if there may be users of them?

**Comment by mojojoseph** [comment]
Howdy @lcalvarez I can confirm as well running into this problem on 18.04 with Wazuh 2.1.1:

```
Err:8 https://packages.wazuh.com/apt xenial InRelease
  403  Forbidden [IP: 52.84.33.102 443]
Reading package lists... Done
E: Failed to fetch https://packages.wazuh.com/apt/dists/xenial/InRelease  403  Forbidden [IP: 52.84.33.102 443]
E: The repository 'https://packages.wazuh.com/apt xenial InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

How were you able to bypass this?  I agree with your sentiment; it should be fixed at the repository level, but at the moment this is busting all of my playbooks on 18.04 servers so I'm willing to use a workaround in the short term.  Thanks for any insight.

**Comment by lcalvarez** [comment]
@mojojoseph I was able to use this:

```
- name: Debian/Ubuntu | Installing wazuh repository
  lineinfile:
    create: yes
    path: /etc/apt/sources.list.d/packages_wazuh_com_apt.list
    line: "deb [trusted=true] https://packages.wazuh.com/apt xenial main"
```

You can also get it to work using `apt_repository` with `validate_certs: no` on the above task but not everyone will want that option.

**Comment by kshep** [comment]
Anyone else find it ironic we're installing security tools from an unsigned repository?

**Comment by BraulioV** [comment]
Hi all,

Sorry for the super late response. First of all, the repositories from 2.x versions of Wazuh are legacy repositories and they are guaranteed to work from Debian 7 to 9 and from Ubuntu 12.04 to Ubuntu 17.04. If you want the latest security updates, features and bug fixes and install the package in any Debian based OS, I highly recommend using our latest version of Wazuh. You can find how to install those repositories for .deb packages here: https://documentation.wazuh.com/3.9/installation-guide/installing-wazuh-server/wazuh_server_deb.html. This single repository is compatible with all Debian based OS.

Secondly, you are installing the repository for **Ubuntu Xenial** in an **Ubuntu Bionic**. This is not guaranteed to work in any Debian repository, and in this case, you can see that this isn't working. When you use the Xenial repository in Bionic, `apt` will try to find this file in the repository: https://packages.wazuh.com/apt/dists/xenial/InRelease, which it doesn't exist. So, the `apt-get` version of Ubuntu Bionic can't verify the signature, even if the repository is signed.

If you want to check if the repository is signed, here you can check the signature of the repository: https://packages.wazuh.com/apt/dists/xenial/Release.gpg. In addition, if you want to install these packages in an Ubuntu hosts, you will need to import the GPG key from https://packages.wazuh.com/key/GPG-KEY-WAZUH.

Here you can see an example of adding the Ubuntu Xenial repository in an Ubuntu Xenial host and in an Ubuntu Bionic host:

* Ubuntu Xenial:
```shellsession
root@cf21bb37dfba:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
root@cf21bb37dfba:/# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
OK
root@cf21bb37dfba:/# echo "deb https://packages.wazuh.com/apt xenial main" | tee /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/apt xenial main
root@cf21bb37dfba:/# apt update
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 https://packages.wazuh.com/apt xenial InRelease
Get:6 https://packages.wazuh.com/apt xenial Release [2657 B]
Get:7 https://packages.wazuh.com/apt xenial Release.gpg [819 B]
Get:8 https://packages.wazuh.com/apt xenial/main amd64 Packages [3193 B]
Fetched 6669 B in 0s (7309 B/s)     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
12 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@cf21bb37dfba:/# 
```
* Ubuntu Bionic:
```shellsession
root@0ccabf554525:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@0ccabf554525:/# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
OK
root@0ccabf554525:/# echo "deb https://packages.wazuh.com/apt xenial main" | tee /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/apt xenial main
root@0ccabf554525:/# apt update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                        
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                      
Hit:4 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                      
Err:5 https://packages.wazuh.com/apt xenial InRelease                    
  403  Forbidden [IP: 13.32.90.79 443]
Reading package lists... Done
E: Failed to fetch https://packages.wazuh.com/apt/dists/xenial/InRelease  403  Forbidden [IP: 13.32.90.79 443]
E: The repository 'https://packages.wazuh.com/apt xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@0ccabf554525:/# 
```

And this is the result if you install the repositories for Wazuh 3.x in Ubuntu 18.04:
```shellsession
root@50bff28cd4e3:/# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
root@50bff28cd4e3:/# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
OK
root@50bff28cd4e3:/# echo "deb https://packages.wazuh.com/3.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
deb https://packages.wazuh.com/3.x/apt/ stable main
root@50bff28cd4e3:/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 https://packages.wazuh.com/3.x/apt stable InRelease [5997 B]                                                         
Hit:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                            
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease       
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease       
Get:6 https://packages.wazuh.com/3.x/apt stable/main amd64 Packages [12.4 kB]
Fetched 18.4 kB in 1s (18.6 kB/s)
Reading package lists... Done
root@50bff28cd4e3:/# 
```

As you can see, the 2.x repositories are signed, so I'm closing this issue. If you have any other questions, don't hesitate to reopen it.

Best regards.

**Comment by johnfoxii** [comment]
pertaining to Ubuntu 18.04.2 LTS
please pardon my ignorance.
What is _"deb"_
_"echo "deb https://packages.wazuh.com..."_

**Comment by BraulioV** [comment]
Hi @johnfoxii ,

`deb` is the type of archive. Debian repositories may have `deb` files (binary packages as the ones found in packages.wazuh.com) or `deb-src`, which are packages that contain the source files used to build a binary package. 

The `deb` packages can be installed and ready to go but `deb-src` packages must be compiled first.

Here you can find more info about this: https://wiki.debian.org/SourcesList
