### ISSUE TITLE
Fixed Agent IP issue

### ISSUE THREAD

**Issue by vochanhdai-016** [wazuh/wazuh#1638]
I am configuring cluster as below picture (from docs: https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html)
![image](https://user-images.githubusercontent.com/37267523/46932721-24b1ff80-d07b-11e8-9fcf-d69e9bc55153.png)
When register an agent to master node, should I point to load balancer IP as server and set Any IP for my agent?

**Comment by mgmacias95** [comment]
Hello @vochanhdai-016,

Yes, agents must be configured to point to the load balancer IP, but registered in the master node.

Best regards,
Marta

**Comment by vochanhdai-016** [comment]
@mgmacias95, When using a LB, the cluster nodes will only see the LB’s IP and no the agents’. so must I set the IP of new agent: any?

**Comment by mgmacias95** [comment]
Yes, the agents IP must be any. Also, it's better to configure the agents to use TCP protocol instead of UDP.

**Comment by vochanhdai-016** [comment]
@mgmacias95, thanks for your help.

**Comment by mgmacias95** [comment]
You're welcome 😄! Don't hesitate to reach us again if you need something else.
