### ISSUE TITLE
Error compiling in Alpine Linux

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#16393]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-rc2| Wazuh component | Agent | Sources | Alpine linux |

During the generation of packages for RC2 we found that Alpine Linux packages failed during the compilation. When checking the log we found the following:

```
configure: error: select TLS backend(s) or disable TLS with --without-ssl.

Select from these:

  --with-amissl
  --with-bearssl
  --with-gnutls
  --with-mbedtls
  --with-nss
  --with-openssl (also works for BoringSSL and libressl)
  --with-rustls
  --with-schannel
  --with-secure-transport
  --with-wolfssl

mv -f .deps/emitter.Tpo .deps/emitter.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -fPIC -no-undefined -release 0 -version-info 2:5:0 -Wl,--as-needed -o libyaml.la -rpath /usr/local/lib api.lo reader.lo scanner.lo parser.lo loader.lo writer.lo emitter.lo dumper.lo  
make: *** [Makefile:1031: external/curl/Makefile] Error 1

```

Here we can see the complete compilation log:

[compilation_output.txt](https://github.com/wazuh/wazuh/files/10989613/compilation_output.txt)

**Comment by davidjiglesias** [comment]
There was an error in the sources DEPS 18 used for v4.4.0, after fixing it, the Alpine packages have been built correctly.
