### ISSUE TITLE
Missing option in preloaded-vars to disable syscollector

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#1640]
## Bug report

**OS**
_Any._

**Wazuh version**
_3.7.0_

**Wazuh API version**
_NA_

**Install type**
_manager/agent_

**Install method**
_sources_

Bug description
----------------

There isn't an option in the preloaded-vars.conf file to disable `syscollector` when you execute the `install.sh` script. 

In addition, if you disable `syscollector` using the preloaded-vars.conf file, for example `USER_ENABLE_SYSCOLLECTOR="n"`, `gen_ossec.sh` shouldn't write the configuration block in the `ossec.conf`.

**Comment by cristgl** [comment]
Fixed at https://github.com/wazuh/wazuh/pull/1648.
