### ISSUE TITLE
Release 4.4.0 - Release Candidate 2 - System tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#16422]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |           https://github.com/wazuh/wazuh/issues/16390                                 |
| **Version**                          |                 4.4.0                           |
| **Release candidate #**              |               RC2                             |
| **Tag**                              |                 [v4.4.0-rc2](https://github.com/wazuh/wazuh/tree/v4.4.0-rc2)                          |
| **Previous system tests issue**      |                  https://github.com/wazuh/wazuh/issues/16182                          |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found https://github.com/wazuh/wazuh/issues/16422#issuecomment-1473617421.
All tests have passed and the fails were false positives. I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @jmv74211 
- [x] @davidjiglesias

**Comment by Rebits** [comment]
### Update 20/03/2023

Detected failures in `basic_cluster` environment tests. @juliamagan is double checking this issue.

**Comment by Rebits** [comment]
## Enrollment Cluster :red_circle: 

## `test_assign_agent_group_with_enrollment` 

This failure is a false positive, further information in this section

<details>

<blockquote>


The test was manually performed with success. @juliamagan and I have proposed a new approach to solving this false positive.
Using this approach test seems to work as expected.

```
===================== test session starts =====================
platform linux -- Python 3.10.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/rebits/Wazuh/wazuh-qa/4.4/tests/system, configfile: pytest.ini
plugins: html-3.1.1, metadata-2.0.4, testinfra-5.0.0
collected 1 item                                              

test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py . [100%]

- generated html file: file:///home/rebits/Wazuh/wazuh-qa/4.4/tests/system/test_assign_agent_group_with_enrollment3.html -
================ 1 passed in 158.29s (0:02:38) ================
```

</blockquote>


</details>

**Comment by juliamagan** [comment]
## Basic cluster

The tests were failing because they are environment dependent, and the environment was not being cleaned up properly at the end. When launched individually, they all pass:

| Test | Result |
|--|:--:|
|`test_agent_files_deletion`| [🟢 ](https://github.com/wazuh/wazuh/files/11037759/test_agent_files_deletion.zip) |
|`test_agent_groups_forced_change`| [🟢 ](https://github.com/wazuh/wazuh/files/11037771/test_agent_groups_forced_change.zip) |
|`test_agent_info_sync`| [🟢 ](https://github.com/wazuh/wazuh/files/11037773/test_agent_info_sync.zip)|
|`test_agent_key_polling`| [🟢 ](https://github.com/wazuh/wazuh/files/11037774/test_agent_key_polling.zip)|
|`test_multigroups`| [🟢 ](https://github.com/wazuh/wazuh/files/11037777/test_multigroups.zip)|

An issue will be opened to improve these tests in the future.

**Comment by jmv74211** [comment]
## Closing conclusion 👍🏼  

Everything seems to be correct. Victor will open some issues to improve the execution of the tests and obtain results.
