### ISSUE TITLE
Improve the ingest subcommand help message

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16427]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/15717   |     https://github.com/wazuh/wazuh/pull/15847 |

# Description

During the router testing, the when providing some events using the `ingest` subcommand, it seems a bit confusing if the user does not know about the `ossec` format that is used to ingest events: `queue:location:msg`. For example:

```
1:192.168.1.3:an event
```

As this event appear like this within the alerts

```
{"wazuh":{"queue":49,"origin":"192.168.1.3"},"event":{"original":"an event"}}
```

If the user does not know about this format, they will be confused about using different queue values. A brief about this `ossec` format should be added to its help message which currently seems like this:

```
root@engine:/home/vagrant/engine/wazuh/src/engine# ./build/main router ingest --help
Ingest an event on the specified route.
Usage: ./build/main router ingest [OPTIONS] event

Positionals:
  event TEXT REQUIRED         Event to ingest.

Options:
  -h,--help                   Print this help message and exit

root@engine:/home/vagrant/engine/wazuh/src/engine#
```

## Considerations

More details in the comment within the testing issue https://github.com/wazuh/wazuh-qa/issues/3914#issuecomment-1453899656

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
The OSSEC format is being replaced by a standardized format. Therefore, this issue is no longer relevant and will be closed.
