### ISSUE TITLE
Wazuh vulnerability-detector provider msu not detecting Microsoft Hyper-V Server 20xx

### ISSUE THREAD

**Issue by ndonkersloot** [wazuh/wazuh#16456]
Wazuh version | Component | Install type
-- | -- | -- 
4.3.10 | vulnerability-detector| Docker

The vulnerability-detector does not work for Microsoft Hyper-V Server 20xx. When checking the [compatibility matrix](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#vuln-det-compatibility-matrix) it states that Windows XP and later is supported. When checking the `/var/ossec/queue/vulnerabilities/cve.db` there is no Microsoft Hyper-V Server 20xx product.

I think it should be fine (or at least better) to scan 'Microsoft Hyper-V Server 20xx' with 'Windows Server 20xx (Server Core installation)' information. I'm not sure if and how it is possible to do this with the [allow-os tag](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html) as it states [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html#provider) to not use 'os' tags for the msu provider.

Is there a way to make use of the vulnerability-detector for Microsoft Hyper-V Server 20xx agents?
If not is there a way to make Wazuh detect the agent as 'Windows Server 20xx (Server Core installation)'?

**Comment by MiguelazoDS** [comment]
Hello, sorry for the delay. 

I'm afraid it is not possible, we fill up the cve database with NVD and Microsoft information, but I don't see that version included in any of those sources. Let me look deeper into this and see if we can do something about it.

**Comment by MiguelazoDS** [comment]
Hi again, I was doing some research and I don't see a configurable way to do that. With the CPE helper we can translate packages but not SO information. Also, the reliability of any output in case we can do something with the scan, won't be ensured.

**Comment by ndonkersloot** [comment]
@MiguelazoDS 
That's to bad, thanks for researching this though!
