### ISSUE TITLE
Error assigning a group to a non-existent agent

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16464]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least 4.4.0 rc2 | wazuh-db | Manager | Packages| Amazon Linux 2 (Wazuh v4.4.0 rc2 AMI) |

During the analysis of the [AMI v4.4.0-rc2](https://github.com/wazuh/wazuh/issues/16402), an error log related to `wazuh-db` was found where an error can be observed when assigning a group to an agent that has been eliminated 4 seconds before. It is necessary to determine if this error is expected or if there is an uncontrolled case where it is not checked whether said agent exists or not.

```
2023/03/20 18:28:04 wazuh-authd: INFO: Agent '007' (17f9e740df7a) deleted (requested locally)
2023/03/20 18:28:08 wazuh-db: ERROR: There was an error assigning the groups to agent '007'
2023/03/20 18:28:08 wazuh-db: WARNING: The groups were empty right after the set for agent '007'
2023/03/20 18:28:13 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
```

**Comment by TomasTurina** [comment]
The modules involved will be refactored, so this issue will not be addressed.
