### ISSUE TITLE
CIS Benchmark Tests and how they treat missing registry keys are different between OS versions

### ISSUE THREAD

**Issue by hayesb-emmanuel** [wazuh/wazuh#16479]
|4.3.10|Client/Ruleset|Agent|Winodws Server|

I was not 100% sure which category to submit this in. We recently started working with a vendor that uses Wazuh to help identify weaknesses in our Windows Server configurations. When we upgraded to the 4.3.10 client they switched us from the Windows Betnchmark to the CIS Benchmark tests and I noticed a difference between 2012/2016/2019 and 2022 servers, where the older OS's had a larger number of "Not Applicable" results and the 2022 server had a large number of "Failed" results for the same configuration checks. After researching I identified the differences had to do with how the testing handled a missing registry key.

With the examples below, it shows that the older OS CIS test files will default to "Not Applicable" if the registry key is missing, where as the newer server 2022 test has additional checks to verify the registry path/key exists as well as the value is being set, which then "fails" if the key is missing.

My concern is that with older OS's, it is ignoring a large number of tests when giving the resulting score, and not identifying possible vulnerabilities. I have a 2019 server fully patched with a score in the 80% but it is ignoring 200 of 250 tests, so that 80% is only based on 50 tests, where as I have a 2022 server that had a score of 38% and was only ignoring 3 of 300 tests. We then made registry adjustments per the testing recommendations and pushed that score up. This is likely leading to a more secure 2022 server, but not addressing the older OS.

Example Ruleset Files:
--------------------------
https://github.com/wazuh/wazuh/blob/master/ruleset/sca/windows/cis_win2019.yml
https://github.com/wazuh/wazuh/blob/master/ruleset/sca/windows/cis_win2022.yml

Example Tests from Files (most of the tests in the file have this pattern):
-------------------------
**Ensure 'Continue experiences on this device' is set to 'Disabled'**
```
2019 Check (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp -> 0
===> Not Applicable

2022 Checks (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp -> 0
===> Failed
```

**Ensure 'Configure enhanced anti-spoofing' is set to 'Enabled'**
```
2019 Check (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing -> 1
===> Not Applicable

2022 Checks (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing -> 1
===> Failed
```

**Ensure 'Allow Use of Camera' is set to 'Disabled'.**
```
2019 Check (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera -> 0
===> Not Applicable

2022 Checks (Condition: all)
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera -> 0
===> Failed
```

Would all of the older OS files need their tests updated to include checks for missing path/key's to make them more valid?

Additionally, wouldn't each check have to take into account how the OS handles a missing registry key as its default behavior to determine if it needs to verify the path/key exists to be evaluated?

**Comment by hayesb-emmanuel** [comment]
Not sure if anyone saw this and/or if any of the contributors that update the CIS Benchmark tests are around, but it might be worth checking on this. As it stands right now its possible the older OS's are reporting they are properly configured and secure, when the majority of tests are largely just being ignored.

Also, after speaking with CIS, it seems there really should be 2 levels of benchmarks for each OS, level 1 and 2. One is more strict than the other, and each rule in the benchmark designates which level it should be evaluated at. So there really should be 2 tests, and then the user of the product would decide which level they want to hold their systems too.

**Comment by aleilmago** [comment]
Hello.

Same issue here: Windows Server 2022 has a large number of "Failed" results for the same configuration checks (more than 50%).

So it's unusable.

Thanks.
Kind regards.

**Comment by niek1992** [comment]
Currently testing CIS benchmarks and SCA (or CIS-CAT Pro v4 which has a different issue when coupled with Wazuh) and noticed that a lot of tests are not implemented by default. So one would need to implement them themselfs?

**Comment by 72nomada** [comment]
This will be manage by - https://github.com/wazuh/wazuh/issues/16724

**Comment by ooniagbi** [comment]
> |4.3.10|Client/Ruleset|Agent|Winodws Server|
> 
> I was not 100% sure which category to submit this in. We recently started working with a vendor that uses Wazuh to help identify weaknesses in our Windows Server configurations. When we upgraded to the 4.3.10 client they switched us from the Windows Betnchmark to the CIS Benchmark tests and I noticed a difference between 2012/2016/2019 and 2022 servers, where the older OS's had a larger number of "Not Applicable" results and the 2022 server had a large number of "Failed" results for the same configuration checks. After researching I identified the differences had to do with how the testing handled a missing registry key.
> 
> With the examples below, it shows that the older OS CIS test files will default to "Not Applicable" if the registry key is missing, where as the newer server 2022 test has additional checks to verify the registry path/key exists as well as the value is being set, which then "fails" if the key is missing.
> 
> My concern is that with older OS's, it is ignoring a large number of tests when giving the resulting score, and not identifying possible vulnerabilities. I have a 2019 server fully patched with a score in the 80% but it is ignoring 200 of 250 tests, so that 80% is only based on 50 tests, where as I have a 2022 server that had a score of 38% and was only ignoring 3 of 300 tests. We then made registry adjustments per the testing recommendations and pushed that score up. This is likely leading to a more secure 2022 server, but not addressing the older OS.
> 
> ## Example Ruleset Files:
> https://github.com/wazuh/wazuh/blob/master/ruleset/sca/windows/cis_win2019.yml https://github.com/wazuh/wazuh/blob/master/ruleset/sca/windows/cis_win2022.yml
> 
> ## Example Tests from Files (most of the tests in the file have this pattern):
> **Ensure 'Continue experiences on this device' is set to 'Disabled'**
> 
> ```
> 2019 Check (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp -> 0
> ===> Not Applicable
> 
> 2022 Checks (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System -> EnableCdp -> 0
> ===> Failed
> ```
> 
> **Ensure 'Configure enhanced anti-spoofing' is set to 'Enabled'**
> 
> ```
> 2019 Check (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing -> 1
> ===> Not Applicable
> 
> 2022 Checks (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures -> EnhancedAntiSpoofing -> 1
> ===> Failed
> ```
> 
> **Ensure 'Allow Use of Camera' is set to 'Disabled'.**
> 
> ```
> 2019 Check (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera -> 0
> ===> Not Applicable
> 
> 2022 Checks (Condition: all)
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera
> r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Camera -> AllowCamera -> 0
> ===> Failed
> ```
> 
> Would all of the older OS files need their tests updated to include checks for missing path/key's to make them more valid?
> 
> Additionally, wouldn't each check have to take into account how the OS handles a missing registry key as its default behavior to determine if it needs to verify the path/key exists to be evaluated?

@hayesb-emmanuel we have reviewed this issue and are currently fixing it across our Windows SCAs. You can track the progress here: https://github.com/wazuh/wazuh/issues/21860.

**Comment by ooniagbi** [comment]
This issue will be fixed in the issues below:

Windows 10: https://github.com/wazuh/wazuh/issues/22047
Windows 11: https://github.com/wazuh/wazuh/issues/22195
Windows 2012 R2: https://github.com/wazuh/wazuh/issues/17337
Windows Server 2016: https://github.com/wazuh/wazuh/issues/22194
Windows Server 2019: https://github.com/wazuh/wazuh/issues/16724
Windows Server 2022: https://github.com/wazuh/wazuh/issues/17339
