### ISSUE TITLE
Improve the reliability of the Virustotal integration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#16488]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Integration/VirusTotal | Manager | All | All |

## Description

The goal is to improve the Virustotal integration so we retry sending FIM alerts whose response has not been received from VirusTotal as well as improve the logging of the integration so we have more information about the communication between Wazuh and VirusTotal.

### Requirements

- Include a timeout when waiting for a response from Virustotal.
- When the timeout is reached and no response is received, retry sending the alert so we don't lose any VirusTotal response.
- The number of retries until discard the alert should be configurable.
- Improve the logging into `intregrations.log` so we are able to see when this situation happens.

**Comment by vikman90** [comment]
We're going to continue with the testing implementation after completing https://github.com/wazuh/wazuh-qa/issues/3928.

**Comment by TomasTurina** [comment]
We need to move the original ETA from September 1 to September 15. All high-priority tasks related to 4.5.2 and 4.6.0, as well as urgent issues with some customers that happened in the last two weeks, are the reason for this change.
