### ISSUE TITLE
Improve the i_calc error message when the int is not wihin the supported range

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16511]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/15485   |     https://github.com/wazuh/wazuh/pull/16094 |

# Description

During the `i_calc` testing, when using an integer that is not within the range `[INT_MIN, INT_MAX]` it shows this error in runtime: `Failure: Parameter is not integer: /~0nums/n`. When it should be like, `the integer is not within the supported range [INT_MIN, INT_MAX]`, for example.

> More details within [Scenario Outline 4: +i_calc helper - special cases using references](https://github.com/wazuh/wazuh-qa/issues/4010#issuecomment-1466595738)

## Considerations

More details in the comment within the testing issue that use references https://github.com/wazuh/wazuh-qa/issues/4010

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed. Same as https://github.com/wazuh/wazuh/issues/16474
