### ISSUE TITLE
syscollector data not syncing in manager

### ISSUE THREAD

**Issue by dorkgoogles** [wazuh/wazuh#16518]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-40402 | syscollector | Manager| Sources | Ubuntu 22.04.1 LTS |

VM and Inventory data not working as expected

Thing we have tired so far

- Discarded Connectivity issues
- Restarted the agent
- Registered the agent again.
- Forced a vuln scan.
- Confirmed built from sources 4.4
- The agent id is the same, not restricted to specific agent.
- Local inventory is present and later wiped.

What is happening
After installing an agent it creates a db file locally which contains the syscollector info.
This data is pushed to agent at `/var/ossec/queue/db/` in _agentid.db_ file on subsequent information sent by agent it updates in _agentid.db_ and creates old db file with the initial data where the file is _agentid.db-oldv9-epochtime_ 
Upon analysing all the files it was found that the syscollector resides in one of these _agentid.db-oldv9-epochtime_ files and not stored inthe _agentid.db_ thus causing the manager to not show the system inventory info and do vulnerability management as the _agent.db_ file has no such data.

To Summarise

- _agentid.db-oldv9-epochtime_ is created everytime a new update is pushed by agent.
- _agentid.db_ does not contain syscollector data.
- instead few instances of _agentid.db-oldv9-epochtime_ contains syscollector data.
- Resulting in VM and Inventory data not working as expected.

**Comment by pereyra-m** [comment]
Hello @dorkgoogles !

The official release of Wazuh v4.4.0 will be soon, if you are using a manager built by sources there might be some details yet until the full testing is completed.

It seems that the agent database upgrade from schema version 9 (Wazuh v4.3) to 10 (Wazuh 4.4) is failing, so `wazuh-db` stores the previous data in a backup file with the name format `XXX.db-oldv<VERSION>-<EPOCH>` (see https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_db/wdb_upgrade.c#L253) and creates a new empty DB.

- Can you share your `ossec.log` file? It might contain some related error messages that could help in understanding the cause of the issue
- Can you confirm that this backup file is created every time you perform the upgrade? Is it possible to share an example DB? This way, we could test the upgrade with that same file.

Regards.

**Comment by dorkgoogles** [comment]
Issue Is fixed in the latest stable release of Wazuh

**Comment by pereyra-m** [comment]
Thank you for the update!
