### ISSUE TITLE
Debug Mode Enabling 

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#1653]
## Bug report

**OS**
_Ubuntu16.04.5_LTS (Xenial Xerus)

**Wazuh version**
_3.6.1

**Install type**
agent

**Install method**
sources

Bug description
----------------
 enabling the debug mode in the **local_internal_options.conf** or in the **internal_options.conf**  not working when using 

> agent.debug = 2 

 and works when removing the spaces 

> agent.debug=2

**Comment by vikman90** [comment]
This is not a bug. The required syntax is:

```sh
key1.key2=value
```

No spaces between symbols.
