### ISSUE TITLE
Encountered conflict error while upgrading Wazuh-manager to v4.4 using the Offline-Method

### ISSUE THREAD

**Issue by kjprocess** [wazuh/wazuh#16537]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Wazuh v4.4 | Wazuh Manager | Manager | Offline-method | OS version |

Hello Team,

I tried upgrading  Wazuh-manager using the offline-method to  Wazuh v4.4 from v3.8 in my lab following the guide [here ](https://documentation.wazuh.com/current/deployment-options/offline-installation.html) but I was getting a conflict error message below after running the command `rpm --import ./wazuh-offline/wazuh-files/GPG-KEY-WAZUH
rpm -ivh ./wazuh-offline/wazuh-packages/wazuh-manager*.rpm`.

Please see error below

`	file /var/ossec/framework/python/lib/python3.9/venv/__pycache__/__main__.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/venv/__pycache__/__main__.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/__init__.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/__init__.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/__init__.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/handlers.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/handlers.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/handlers.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/headers.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/headers.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/headers.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/simple_server.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/simple_server.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/simple_server.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/util.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/util.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/util.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/validate.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/validate.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/wsgiref/__pycache__/validate.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/__pycache__/__init__.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/__pycache__/__init__.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/__pycache__/__init__.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/NodeFilter.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/NodeFilter.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/NodeFilter.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/__init__.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/__init__.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/__init__.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/domreg.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/domreg.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/domreg.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/expatbuilder.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/expatbuilder.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/expatbuilder.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minicompat.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minicompat.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minicompat.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minidom.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minidom.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/minidom.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/pulldom.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/pulldom.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/pulldom.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/xmlbuilder.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/xmlbuilder.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/dom/__pycache__/xmlbuilder.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementInclude.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementInclude.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementInclude.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementPath.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementPath.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementPath.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementTree.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementTree.cpython-39.opt-2.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/ElementTree.cpython-39.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file /var/ossec/framework/python/lib/python3.9/xml/etree/__pycache__/__init__.cpython-39.opt-1.pyc from install of wazuh-manager-4.4.0-1.x86_64 conflicts with file from package wazuh-manager-4.3.8-1.x86_64
	file `

Regards

**Comment by kjprocess** [comment]
Hello Team,

The OS used is Centos 8

**Comment by T100D** [comment]
On Centos 8 yum (that is linked to dnf :-) ) or more close dnf is the preferred tool to update packages on these systems.

**Comment by MiguelCasaresRobles** [comment]
Thanks, team.

Closing this request as it was solved.
