### ISSUE TITLE
Enhance the API endpoints to unify the usage related to search bar in the plugin

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#16552]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Description

We (frontend team) are working to redo the search bar that displays suggestions. The approach is based on the usage of `q` parameter. I did an analysis of the current API usage, and we have the following requirements that allow us to implement replacing the current search bar.

Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/4312
API endpoint usage analysis:
> https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1482752361
> https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1484975474

We intend to unify the usage of the search bar and extend it through the plugin.

| Endpoint | Add `q` parameter | Add `distinct` | Add `select` | Comment |
| --- | --- | --- | --- | --- |
| `GET /lists` | yes | yes | - | - |
| `GET /decoders` | - | yes | - | - |
| `GET /decoders/files` | yes | yes | yes | - |
| `GET /manager/configuration?section=ruleset&field=decoder_dir` | no apply (strings) | yes  | no apply (strings) | - |
| `GET /groups` | yes | yes | - | - |
| `GET /groups/{group_name}/agent` | - | yes | - |
| `GET /groups/{group_name}/files` | yes | yes | yes | - |
| `GET /rules` |  | yes | yes | - |
| `GET /rules/files` | yes | yes | yes | - |
| `GET /manager/configuration?section=ruleset&field=rule_dir` | no apply (strings) | yes  | no apply (strings) | - |
| `GET /mitre/groups` | - | yes | - | - |
| `GET /mitre/mitigations` | - | yes | - | - |
| `GET /mitre/software` | - | yes | - | - |
| `GET /mitre/tactics` | - | yes | - | - |
| `GET /mitre/techniques` | - | yes | - | - |
| `GET /sca/{agent_id}` | - | yes | yes | - |
| `GET /syscollector/{agent_id}/netiface` | - | yes| - | - |
| `GET /syscollector/{agent_id}/ports` | - | yes| - | - |
| `GET /syscollector/{agent_id}/netaddr` | - | yes| - | - |
| `GET /syscollector/{agent_id}/netproto` | - | yes| - | - |
| `GET /syscollector/{agent_id}/packages` | - | yes| - | - |
| `GET /syscollector/{agent_id}/processes` | - | yes| - | - |
| `GET /syscollector/{agent_id}/hotfixes` | - | yes| - | - |
| `GET /mitre/tactics` | - | yes | - | - |
| `GET /mitre/techniques` | - | yes | - | - |
| `GET /security/policies` | yes | yes | - | - |
| `GET /security/roles` | yes | yes | - | - |
| `GET /security/rules` | yes | yes | - | - |
| `GET /security/users` | yes | yes | - | - |
| `GET /manager/logs` | - | yes | yes | - |
| `GET /cluster/{node}/logs` | - | yes | yes | - |
| `GET /cluster/nodes` | - | yes | - | - |

**All the distinct should allow filtering by a term.**

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Started reviewing the source code of each one of the endpoints to figure out a unified solution but couldn't make any further progress due to some issues in a higher priority task a teammate and I are working on.

**Comment by GGP1** [comment]
## Update

The blocking issue https://github.com/wazuh/wazuh/issues/16750 is now ready to review. I resume the development of this one.

**Comment by GGP1** [comment]
## Update

All subtasks have been developed and should be ready to review, I left them all "On hold" because there are some checks failing that are unrelated to the changes introduced. I will move this issue to "On hold" as well until we can continue with the regular workflow.

**Comment by Desvelao** [comment]
Hi @GGP1 , I missed an endpoint:

| Endpoint | Add `q` parameter | Add `distinct` | Add `select` | Comment |
| --- | --- | --- | --- | --- |
| `GET /syscollector/{agent_id}/netaddr` | - | yes| - | - |

> I updated the endpoint list of the initial message.

**Comment by GGP1** [comment]
@Desvelao Alright, I will add the `distinct` parameter to the endpoints 
- `GET /syscollector/{agent_id}/netaddr`
- `GET /agents` 
- `GET /groups/{group_name}/agents`

**Comment by Desvelao** [comment]
Hi @GGP1 , we are interested to change a table that displays data about the cluster nodes.

We need:

| Endpoint | Add `q` parameter | Add `distinct` | Add `select` | Comment |
| --- | --- | --- | --- | --- |
| `GET /cluster/nodes` | - | yes| - | - |

> I added this requirement to the initial message. I will add this request to the related issue https://github.com/wazuh/wazuh/issues/16715

**Comment by Desvelao** [comment]
I missed the endpoint request of `GET /security/role_mapping`, it is GET `/security/rules` instead.

If you find some error in the request or there is a problem with some endpoint, we expect to get some notification of this.

**Comment by Desvelao** [comment]
Hi @GGP1, I have been asked about the state of these issues. I have seen some activity in the related issues and pull requests, but we would appreciate a response for this epic issue.

Thank you so much!

**Comment by GGP1** [comment]
Hello @Desvelao,

https://github.com/wazuh/wazuh/issues/16715 and https://github.com/wazuh/wazuh/issues/16716 are ready to be merged.

Regarding https://github.com/wazuh/wazuh/issues/16714, I was just about to contact you because we encountered an issue with the `GET /groups?query=` endpoint. 

Because of our current database SDK design, we cannot query fields that are not part of the `group` table. In this case, we can only query by `name`. Using `mergedSum`, `configSum` or `count` returns an error. 

> I've created and started working on a re-design of the SDK to support more flexible and advanced queries to fix this as soon as possible (https://github.com/wazuh/wazuh/issues/17745). But given the immediacy of the release, we don't have enough time to introduce a fix. 

We do not want to leave the endpoint like this, so we have two options:

- Remove the `query` parameter from `GET /groups`
or
- Replace it with a `name` parameter that is more explicit and clear, and allows querying by group names only

What would you prefer?

**Comment by Desvelao** [comment]
> Hello @Desvelao,
> 
> #16715 and #16716 are ready to be merged (they just need a rebase).
> 
> Regarding #16714, I was just about to contact you because we encountered an issue with the `GET /groups?query=` endpoint.

Thank you so much for the information!

> Because of our current database SDK design, we cannot query fields that are not part of the table that corresponds to the object that the endpoint points to. In this case, we can only query fields that are in the `group` table (`name`). Using `mergedSum`, `configSum` or `count` returns an error.
> 
> > I've created and started working on a re-design of the SDK to support more flexible and advanced queries to fix this as soon as possible (#17745). But given the immediacy of the release, we don't have enough time to introduce a fix.
> 
> We do not want to leave the endpoint like this, so we have two options:
> 
> * Remove the `query` parameter from `GET /groups`
>   or
> * Replace it with a `name` parameter that is more explicit and clear, and allows querying by group names only
> 
> Please let me know what would you prefer.

The `GET /groups` endpoint is used in the section of the Wazuh plugin `Management > Groups` that displays the groups' information. The intention of the new search bar is able to search in each column of the table that is displayed (see screenshot Wazuh plguin v4.4.4).

![image](https://github.com/wazuh/wazuh/assets/34042064/6e2e9e8d-ae24-4848-b9f7-526c9c5bd3c1)

The approach of the new search bar is based on the usage of the `q` query parameter, so we would need the `GET /groups` endpoint supports it.

By your response, I understand that only the `name` field is stored in the database which allows you the usage of the `query`. Where is the rest of the properties coming that can be returned in that endpoint (`mergedSum`, `configSum`, and `count`)? I did some tests and I am not sure if currently it is possible to search in these fields too. If this is the case, then maybe this feature could be added in future issues. In my opinion, I think it would be useful for the user to be able to search for all the properties of the group.

Maybe, in the first iteration, we could restrict the search functionality to the `name` field despite the table displaying more fields/properties, but we would want this can be done through the `q` query parameter too because it is the approach of the new search bar. What do you think?

**Comment by Desvelao** [comment]
> @Desvelao,
> 
> Thanks for explaining the feature in detail.
> 
> The `mergedSum` and `configSum` fields contain the hash of the content from the `/var/ossec/etc/shared/<group>/merged.mg` and `/var/ossec/etc/shared/<group>/agent.conf` files. Here's where they are added
> 
> https://github.com/wazuh/wazuh/blob/299b7ecdb9d1ff5a41f6f544a7dcd0b8017135ef/framework/wazuh/agent.py#L591-L606
> 
> `count` is hardcoded in the database query but is not considered a field from the table, so the user can't query or search values by it neither
> 
> https://github.com/wazuh/wazuh/blob/299b7ecdb9d1ff5a41f6f544a7dcd0b8017135ef/framework/wazuh/core/agent.py#L295-L303
> 
> > As you mentioned, the `search` parameter has the same limitations, `select` as well but there were no cases like this one in that issue
> 
> I agree with you in that we should support all the functionalities to all fields just like the other endpoints. Our intention is to do so and we are working on introducing a new design but I'm afraid we won't be able to release it before `4.6.0`, so I think our best alternative is to remove the `q` parameter and use `groups_list` instead (that takes a list of group names to filter by).
> 
> > I did mention to add a `name` parameter but the endpoint already has `group_list` which is a list of group names that filters the results.
> 
> I will remove the `q` parameter from the `GET /groups` endpoint for the first iteration. Meanwhile, we keep on working to support all fields, we will keep you updated.

Hi @GGP1 , the target release for the new search bar is `v4.6.0`. I would need the `GET /groups` endpoint supports the `q` query parameter if we want to implement the new search bar. I understand the current limitations for the fields: `mergedSum`, `configSum` and `count`, so maybe we could only provide the `name` field until the other fields can be supported by `q`.  It is required because the new search bar is based on the usage of `q` query parameter, it does not use other parameters to filter the data as the suggested one: `group_list`. This is the reason we are asking for the addition of `q` query parameters to endpoints that don't support currently.

Could you inform us when you create the issue related to the `GET /groups` endpoint?

**Comment by GGP1** [comment]
Hi @Desvelao,
 
Sorry, I was not aware that the featrue depended on the `q` parameter. We have decided to change the way in which we access the data and instead of filtering it in the database we will just return everything and filter it afterwards.
 
This allows us to support the `q` parameter for all the fields with the caveat that the performance will be considerably affected when requesting a particular group or list of groups. 

It's not the solution that we were looking for but it meets the requirements of the search bar feature, plus the current performance when all groups are returned is the same. The changes will be introduced in the query parameter issue [PR](https://github.com/wazuh/wazuh/pull/16722).

**Comment by GGP1** [comment]
## Update

Merged the branches from the subtasks 

- https://github.com/wazuh/wazuh/issues/16714
- https://github.com/wazuh/wazuh/issues/16715
- https://github.com/wazuh/wazuh/issues/16716

and resolved all conflict to group them in a single one linked to this issue and extending from `4.6.0`.

The PR is ready to be merged, we just need to merge https://github.com/wazuh/wazuh/pull/17703 in `4.6.0` first.

**Comment by Selutario** [comment]
Moving ETA. Reason: 
- https://github.com/wazuh/wazuh/pull/17865#pullrequestreview-1530213345

**Comment by GGP1** [comment]
## Update

@Desvelao, the issue mentions that the `distinct` parameter should be able to filter by a term, but that is not possible with the features the API has at the moment.

### Rationale

The `distinct` parameter is used to tell SQL to use a `SELECT DISTINCT` for the query instead of just `SELECT`. The problem with this is that SQL does not allow you to specify which fields must be different, but instead returns those results that have at least 1 different field.

A possible solution would be to use `distinct` together with `select` to limit the number of fields that will be part of the query. This way, we would be making the set of fields that are going to be compared smaller. The drawback of this workaround is that there are several endpoints (of those on the list, specifically mitre and sca) that include the ID field by default, so using `select` does not solve it.

Excluding the IDs in the case that `select` has been used is possible theoretically but not feasible in practice (plus it would be a breaking change). The same happens for getting all results and then filtering them.

The only solution that I can think of is that from the client side, the results are filtered by comparing by a specific field.
I don't know how your code works, so I'm not sure if it's doable either.

**Comment by GGP1** [comment]
## Update

Changed the `WazuhDBQuery` logic to not set the `min_select_fields` parameter when `distinct` is specified.

Moving to final review

**Comment by GGP1** [comment]
## Update

- Made the requested changes to exclude `required_fields` when `distinct` is used in `process_array`.
- Added the `select` parameter to `GET /groups` even though it wasn't requested so it can be used with `distinct
- Tested a range of endpoints using both WazuhDBQuery and process_array to filter results and left a couple of examples in the PR's description
- Reviewed the failed Framework unit tests. They pass locally and are not related to the changes introduced

**Comment by GGP1** [comment]
## Update

Added the `required_fields` to the endpoints requested.

**Comment by Selutario** [comment]
ETA postponed to July 27. Reason:
- https://github.com/wazuh/wazuh/pull/17865#pullrequestreview-1538815915
