### ISSUE TITLE
`date` parser is not working as expected

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16553]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16155   |     https://github.com/wazuh/wazuh/pull/16217 |

# Description

During some parsers testing, the `date` parser is not working as expected.

Here we have some examples where the `date` behavior is not correct:

- Date collects strings where there are not only a date

    <details><summary>Decoder</summary>

        name: decoder/custom-json/0

        sources:
        - decoder/json/0

        check:
        - event.original: +s_starts/{
        - ~json.type: +r_match/^test

        parse:
            logpar:
                - ~json.testing: <~date>

    </details>

    <details><summary>Event</summary>

    ```
    {"type":"test","testing":"Jan 3 13:45:36 id=firewall sn=000SERIAL time=\"2007-01-03 14:48:06\" fw=89.160.20.156"}
    ```

    </details>

    <details><summary>Output</summary>

    ```
    "~date": "Jan 3 13:45:36 id=firewall sn=000SERIAL time=\"2007-01-03 14:48:06\" fw=89.160.20.156"
    ```

    </details>

- Date and another parser within the same logpar (I)

    <details><summary>Decoder</summary>

    ```
    name: decoder/custom-json/0

    sources:
    - decoder/json/0

    check:
    - event.original: +s_starts/{
    - ~json.type: +r_match/^test

    parse:
        logpar:
            - ~json.testing: <~date> <~ip>
    ```

    </details>

    <details><summary>Event</summary>

    ```
    {"type":"test","testing":"Jan 3 13:45:36 192.168.1.1"}
    ```

    </details>

    <details><summary>Output</summary>

    ```
    "~date": "Jan",
    "~ip": "3 13:45:36 192.168.1.1"
    ```

    </details>

- Date and another parser within the same logpar (II)

    <details><summary>Decoder</summary>

    ```
    name: decoder/custom-json/0

    sources:
    - decoder/json/0

    check:
    - event.original: +s_starts/{
    - ~json.type: +r_match/^test

    parse:
        logpar:
            - ~json.testing: <~date> <~tmp/kv/=/ /"/'>
    ```

    </details>

    <details><summary>Event</summary>

    ```
    {"type":"test","testing":"Jan 3 13:45:36 id=firewall sn=000SERIAL time=\"2007-01-03 14:48:06\" fw=89.160.20.156"}
    ```

    </details>

    <details><summary>Output</summary>

    ```
    "~date": "Jan",
    "~tmp": {
        "3 13:45:36 id": "firewall",
        "sn": "000SERIAL",
        "time": "2007-01-03 14:48:06",
        "fw": "89.160.20.156"
    }
    ```

    </details>

    > The date is just the month `Jan` and the date is lost being collected with the kv parser    

## Considerations

More details in the `Event's pairs have non-zero offset` case within the `kv` parser scenario https://github.com/wazuh/wazuh-qa/issues/4025#issuecomment-1490516356

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
The test is wrong, the issue is not valid.
The custom fields are not specifying the parser, that's why the error in the parsing.
