### ISSUE TITLE
gcp-pubsub does not appear to actually acknowledge logs

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#16608]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | gcp-pubsub | Manager | Packages | Ubuntu 20.04 |

We recently got Wazuh ingestion of GCP logs working, and one item of concern we have is that while the gcp-pubsub module claims to be receiving and acknowledging GCP log messages, that on the Google side all received messages are reported to never be acknowledged.  This continues to be the case even after changing the Acknowledgement deadline from the default 10 seconds to 60 seconds.  I'm concerned this is going to result in an excessive buildup of messages on the GCP side that are not dropped upon acknowledgment because they are not actually getting acknowledged.

Module configuration:

```
 <gcp-pubsub>
     <pull_on_start>yes</pull_on_start>
     <interval>1m</interval>
     <project_id>my-project</project_id>
     <subscription_name>wazuh-subscription</subscription_name>
     <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
 </gcp-pubsub>
```

Debug log from the module:

```
2023/04/03 21:58:50 wazuh-modulesd:gcp-pubsub[2360632] wm_gcp.c:317 at wm_gcp_pubsub_run(): INFO: - INFO - Received and acknowledged 2 messages
```

All messages received are showing up as unacknowledged and the counts of unACKed messages never go down.

![image](https://user-images.githubusercontent.com/13170654/229640779-46d842c3-6a35-495f-a339-0e100483e6bb.png)

GCP Subscription configuration:

![image](https://user-images.githubusercontent.com/13170654/229641010-735979c2-c5f2-4848-880d-b97d8baf3341.png)

Is there any workaround to get the acknowledgement process working, or am I missing something?

Thanks,
Kevin

**Comment by vikman90** [comment]
@branchnetconsulting thank you for reporting this issue. I've just added it to the roadmap.

Best regards.

**Comment by thejbte** [comment]
The Google cloud is accessible, but the events have not yet been replayable.
(Unconfirmed Messages by Region, Confirmed Message Count by Delivery Type)
![Screenshot from 2023-04-25 10-03-22](https://user-images.githubusercontent.com/17997755/234319753-bf0278d0-6b7f-4f74-9a3b-00f4adb276c8.png)

**Comment by sujeet-98** [comment]
I also got same issue that wazuh is not able to pull all the messages from pub/sub subscription... Can someone guide me through how i can troubleshoot the issue or i should look for another open source tool?

**Comment by fdalmaup** [comment]
# Issue Update

- Setup of a GCP Sub to replicate the described behavior following [our documentation](https://documentation.wazuh.com/current/cloud-security/gcp/prerequisites/pubsub.html).

**Comment by fdalmaup** [comment]
# Issue Update

The following analysis and manual tests were made using the `GCP PubSub` module of branch `master` (currently Wazuh `v4.9.0`).

## Code comparison

The code from the module in Wazuh `v4.3.10` (the one with which this issue was opened) does not have great modifications in regards to the behavior of the module. The latest additions in the GCP Pubsub module-related files are:
- In `wodles/gcloud/pubsub/subscriber.py`, the addition of better exception handling.
- In `wodles/gcloud/gcloud.py`, the code restructuring.
- In `framework/requirements.txt`, which has the dependencies of the module, some of them were updated:
    - `certifi==2022.12.07` updated to ``
    - `` to ``
    - `` to ``
    - `` to ``
    - `` to ``
    - `` to ``
    - `` to ``
Therefore, the behavior between the versions should be the same.

**Comment by EduLeon12** [comment]
## Review Update

Looking at the Issue timeline, I agree with the region metrics not being a reference to determine the acknowledgment of the GCP subscription messages, and looking at the logs the wodle is functioning properly every time messages are pulled.

In conclusion, the module is working as expected. 

LGTM!
