### ISSUE TITLE
Anormal peaks in `RSS_MAXMIN` of Windows agent

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#16612]
## Description

In the testing for Release 4.4.1-RC1, some anomalies have been observed in the **RSS_MAXMIN** graph of the Windows agent (wazuh-agent.exe) compared to the 4.4.0-RC2. This anomaly is also present in the rest of the graphs of RSS.

4.4.1-RC1, https://github.com/wazuh/wazuh/issues/16577:
![image](https://user-images.githubusercontent.com/72193239/229741623-dc21a069-e53f-4e91-93b7-2547003f7189.png)

4.4.0-RC2, https://github.com/wazuh/wazuh/issues/16451: 
![image](https://user-images.githubusercontent.com/72193239/229741655-89bfdac9-7e75-47ec-8df9-8d84df07781b.png)

The 4.4.1-RC1 shows more peaks in MIN and MAX and these peaks take significant periods of time.

It is necessary to investigate this behavior and discuss if we can tolerate this difference.

**Comment by vikman90** [comment]
Hi @davidcr01, in both cases the RSS is oscillating between 22 MB and 30 MB. 

The fact that some peaks are wider can be related to two modules working at the same time, but I don't think it's an anomaly.

Let me close this issue.

Thank you!
