### ISSUE TITLE
Error on lstat during stress test

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#16613]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1| Wazuh component | Manager/Agent | Packages/Sources | OS version |

During the execution of the [stress tests](https://github.com/wazuh/wazuh/issues/16566), we found the following error  log:
```
2023/04/02 04:06:07 wazuh-logcollector: ERROR: Error on lstat '/tmp/logcollector_test/date-2023-04-02-104-276.log' due to [(2)-(No such file or directory)]
```

This error was reported previously during 4.4.0 alpha 2 release testing
https://github.com/wazuh/wazuh/issues/15774

**Comment by vikman90** [comment]
@DFolchA Considering that this bug has already been seen in the past and that it happened during a file deletion, we will mark this issue as a low impact bug.

Thank you!

**Comment by MarcelKemp** [comment]
I proceed to close the issue, so that there are no duplicates, as it is also reported in case 2 of the following issue:
- https://github.com/wazuh/wazuh/issues/18995
