### ISSUE TITLE
Analysis request - Wrong group and permissions in the upgrade test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16615]
From @wazuh/cicd  we need to validate the permissions and the group that must have some specific files that have been reported as errors when performing the upgrade test to version `4.4.1-rc1`, the files to be validated are:

- Version: 4.3.3

```
23:36:56  Different:
23:36:56  /var/ossec/var/start-script-lock [Wrong:  group]
23:36:56  	Expected: root wazuh  0755  # drwxr-xr-x
23:36:56  	Found   : root root  0755  # drwxr-xr-x

```

- Version: 4.0.4

```
02:42:10  Different:
02:42:10  /var/ossec/var/db/.template.db [Wrong:  mode]
02:42:10  	Expected: root wazuh  0640  # -rw-r-----
02:42:10  	Found   : root wazuh  0660  # -rw-rw----

```

- Version: 4.0.0

```
02:42:10  Different:
02:42:10  /var/ossec/var/db/.template.db [Wrong:  mode]
02:42:10  	Expected: root wazuh  0640  # -rw-r-----
02:42:10  	Found   : root wazuh  0660  # -rw-rw----
```

---

Related:
- https://github.com/wazuh/wazuh-jenkins/issues/4957
- https://github.com/wazuh/wazuh/issues/16590

**Comment by GabrielEValenzuela** [comment]
Hi team !

We did some additional testing, creating a script that has only

```bash
mkdir Folder
```

In the attached screenshots, we confirm that the owner and permissions, depends on the user who runs it, so if the installation is done with `root`, it is correct that `start-script-lock` is correct that the group is `root`.

![Screenshot from 2023-04-05 06-20-43](https://user-images.githubusercontent.com/27935340/230044356-b73c5862-4138-41dc-b2b4-400d9337c631.png)

![Screenshot from 2023-04-05 06-21-18](https://user-images.githubusercontent.com/27935340/230044381-4250ad0f-4b76-4de4-b1ff-128d3e595ab0.png)

If you have any questions, please feel free to contact us via Slack. 🙂

**Comment by teddytpc1** [comment]
Thanks for the analysis.
