### ISSUE TITLE
Updating the ossec.conf configuration from within the dashboard

### ISSUE THREAD

**Issue by digital-dev** [wazuh/wazuh#16610]
|Wazuh version|Component|
|---|---|
| 4.4.0-06 | Dashboard |

Request to enable securely updating the ossec.conf configuration from within the dashboard user interface. Currently this doesn't appear to be possible.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by AlexRuiz7** [comment]
Updating the ossec.conf configuration from the dashboard user interface is already possible.
