### ISSUE TITLE
Support for YARA scans

### ISSUE THREAD

**Issue by srikwit** [wazuh/wazuh#1662]
## Feature request

**Compatibility**
agent

Description
--------------
Hello Team,

Similar to how there is an OSQuery support for Wazuh, I was wondering if there is a possibility to add support for YARA binaries as a Wodle. YARA scanning is cross platform and many incident responders/organizations share YARA rules to communicate the presence of an IOC.

I believe this will be a **major** plus for Wazuh.

**Comment by vikman90** [comment]
Hi @srikwit,

Thank you for opening this issue. I agree with you, this will be a great improvement. In fact, a project to integrate YARA and Wazuh is in our roadmap.

We could start with a brainstorm...

## How to integrate YARA

The integration with YARA would be implemented as a Wazuh agent module (_wodle_) to execute YARA periodically and report the results to the manager. Then, we would extend the manager ruleset to match important results and produce an alert.

### Configuration

This is the first idea for the wodle configuration:

```xml
<wodle name="yara">
  <disabled>no</disabled>
  <rule>/path/to/rule</rule>
  <interval>1d</interval>
</wodle>
```

### How to connect with YARA

Integration wodles often require the integrated application to be installed into the agent. I think YARA provides a C API, so we can consider two options in this case:

1. Require YARA to be externally installed into the agent host. The Wazuh agent will run YARA as a subprocess.
2. Provide YARA natively as a C library with the agent. This will prevent the user from installing YARA externally as a dependency.

I am not a YARA expert. I hope the Wazuh Team and you can reach a great solution for this integration.

Best regards.

**Comment by olegzhr** [comment]
Also it can be implemented as active response script, something similar see in https://www.sans.org/reading-room/whitepapers/forensics/paper/35542

**Comment by vikman90** [comment]
Hi @olegzhr,

Thanks for your idea. We're thinking of using requests: they are the messages interchanged between the agent and the manager when sending a WPK package, launching a remote upgrade or requesting the configuration.

Actually, both Active response and requests work similarly, except that AR is a one-way message, and requests provide return data, this is useful to confirm that a message is received and intended.

We could use AR to make a simple integration, but a native module in the agent will let us tune the configuration better.

Anyway, we could implement an API call to run a scan on YARA on demand.

What is your idea of use case? We're open to ideas and requests!

Thank you.
Best regards.

**Comment by olegzhr** [comment]
Hi @vikman90

as far I understand Wazuh is EDR (Endpoint Detection and Response) product now 
and probably for such products "YARA scanning" and "Active Response" are major functionalities.

My use case corresponds to the description listed in Wazuh documentation 
"Active responses perform various countermeasures to address active threats, 
such as blocking access to an agent from the threat source when certain criteria are met."

Below just an example:

1) Wazuh Agent (FIM) detect new file or checksum changing and send an event to Manager
2) Event triggers the specific AR on the Manager,
3) Wazuh Manager send a response to the agent to run a script (Yara) for scanning of the suspicious file
4) If the file is malware according to the result of scan then action: block this file (delete or other action)
5) Agent send a report to Manager about the result of the scan and AR

BTW realization of Yara functional as wodle module is also a good idea

Thanks

**Comment by olegzhr** [comment]
In the documentation for YARA mentioned API for C and Python (I'm not a specialist in YARA)
for example:
int yr_rules_scan_file(YR_RULES* rules, const char* filename, int flags, YR_CALLBACK_FUNC callback, void* user_data, int timeout)

So the logic of my use case can be changed, Wazuh Agent can directly call a YARA API instead of script 

Best regards

**Comment by juergenc** [comment]
Consider also the rule files for YARA, they have to be placed on the _agent side_. So, there is also the mangement of the distribution of new rule files to all agents. Either this is the admin's job to distribute them with its own deployment tool (e.g. ansible, puppet,...) which is not so optimal or it is done by the Wazuh manager. It could be used the same distribution mechansim as we have it for the agent configuration files.

**Comment by olegzhr** [comment]
Of course, if the manager is responsible for the distribution/update of rules it is the optimal variant. Probably, need two repositories for Wazuh YARA rules and users/3rd-party rules.

**Comment by olegzhr** [comment]
However, https://osquery.readthedocs.io/en/stable/deployment/yara/

**Comment by TJOSERAFAEL** [comment]
Hi @olegzhr and @juergenc 

we are going to implement a YARA module for Wazuh, follow this implementation issue https://github.com/wazuh/wazuh/issues/3357

Thank you for your contribution an interest!

Best regards.
