### ISSUE TITLE
Ubuntu 14 | Integration Issue | Tried Multiple Methods

### ISSUE THREAD

**Issue by DaniyalYaseen-ai** [wazuh/wazuh#16633]
**Dear Wazuh Team,**
We are unbale to integrate **Ubuntu 14** to our **Wazuh** by following the official documentation as mentioned below:
https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html

Have opened a case **"Ubuntu 14 | agent Installation | Errors Reported"**, request you to please refer it.

Further I am attaching the error from ossec.log file from agent (Ubuntu 14 end), you are requested to please find a way to resolve the issue, currently network is working fine b/w server and wazuh.
![config](https://user-images.githubusercontent.com/57337996/230051071-ebadfc16-2532-4980-ad8b-e3dd0ec7fa68.png)
![Wazuh-Website](https://user-images.githubusercontent.com/57337996/230050828-7f90b0d8-c594-4ba4-ada0-b1367386322f.png)

![log-error](https://user-images.githubusercontent.com/57337996/230051673-d9105fa5-3dab-4c04-9ff9-93f89fffde27.png)
![image (9)](https://user-images.githubusercontent.com/57337996/230051856-977d76c4-4271-4106-8265-6fcac94dd910.png)

**Comment by vikman90** [comment]
Hi @DaniyalYaseen-ai,

I think `apt-get` is producing the error due to the agent version specified: the package version (`-1`) is missing. Try this:
```sh
WAZUH_MANAGER="..." apt-get install wazuh-agent=4.3.10-1
```

<details><summary>This script should work:</summary>

```sh
apt-get update
apt-get install -y curl
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt-get update
WAZUH_MANAGER="172.27.208.36" apt-get install wazuh-agent=4.3.10
```

Default settings:

```sh
head -n12 /var/ossec/etc/ossec.conf
```

```xml
<!--
  Wazuh - Agent - Default configuration for ubuntu 14.04
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>
  <client>
    <server>
      <address>172.27.208.36</address>
      <port>1514</port>
      <protocol>tcp</protocol>
```

</details>

Regarding the `WARNING` message, I have not been able to reproduce it. I wonder if the manager and the agent have been set up with the same protocol (either TCP (default) or UDP).

Hope this helps.
Best regards.
