### ISSUE TITLE
Anomalous RSS memory decrease in Ubuntu agent

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#16639]
## Description

- An anomalous behavior has been found in the Ubuntu agent RSS memory usage, where it is possible to see that `wazuh-modulesd` decreases in use even when the stress phase has not finished. In [4.4.1-RC1](https://github.com/wazuh/wazuh/issues/16580)

![image](https://user-images.githubusercontent.com/14913942/229628856-f0f637fa-9eab-45d3-af7e-32e66baa26cd.png)

- In [4.4.0-RC2](https://github.com/wazuh/wazuh/issues/16438) this behavior has not been observed.

![image](https://user-images.githubusercontent.com/14913942/229628975-c8b7ec15-2863-4472-84d1-229019ebd319.png)

It is needed to investigate this anomalous behavior and determine if it's something we have to be worried about.

**Comment by vikman90** [comment]
@davidcr01 Memory management is tough to predict, memory management libraries abstract us from all of this.
If it grows in a uniform positive slope, it may indicate a memory leak. If, wherever it is, we notice it above other executions, it may mean that we have made unexpected changes. But if it goes down a bit during the test, it could mean from when the buffers have been freed up to when the fragmentation has gone down.

In this case, this does not mean wrong or worrying behavior IMO.

Let me close this issue.
Cheers!!
