### ISSUE TITLE
Anormal shoot up of `wazuh-logcollector` in the PSS graph

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#16632]
## Description

In the testing for Release 4.4.1-RC1, an anomaly has been observed in the **PSS** graph of the CentOS agent (wazuh-logcollector) compared to the 4.4.0-RC2.

[4.4.1-RC1](https://github.com/wazuh/wazuh/issues/16572):
![image](https://user-images.githubusercontent.com/72193239/230044859-df5e57dc-950b-410c-a7f0-c4f08ee15515.png)

[4.4.0-RC2:](https://github.com/wazuh/wazuh/issues/16160)
![image](https://user-images.githubusercontent.com/72193239/230044968-e58c3231-470c-478e-825b-0eba34dcdbc5.png)

It is shown that the `wazuh-logcollector` shoots up to 10000 PSS in the "Full load" stage, something not present in 4.4.0-RC2. Besides, in 4.4.1-RC1, the `wazuh-logcollector` module starts with 6000 PSS, whereas in 4.4.0-RC2 it starts with 2000 PSS.

It is necessary to investigate this behavior and report an explanation about this issue.

**Comment by vikman90** [comment]
@davidcr01 Let me compare the RSS:

### 4.4.0 RC 2

![image](https://camo.githubusercontent.com/beffee2c250367bad99ddc11a4cd4ed8706f8dc4b61a30ed78bc8025f78e2530/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e302f42333733392d333630306d2f42333733395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333733395f63656e746f732d7072652d72656c656173655f5253532e706e67)

### 4.4.1 RC 1
![image](https://camo.githubusercontent.com/0009665e405e1744165c16771191756d964e99f01e80abb4267ee0208736646d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e312f42333836312d333630306d2f42333836315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42333836315f63656e746f732d7072652d72656c656173655f5253532e706e67)

## Comparison

|Daemon|4.4.0|4.4.1|Increase|
|---|---|---|---|
|Agentd|5.9 MB|9.9 MB|67% ⬆️|
|Execd|4.1 MB|4.1 MB| 0%|
|Logcollector|4.2 MB|12.2 MB|109% ⬆️|
|Modulesd|8.7 MB|8.5 MB|2% ⬇️|
|Syscheckd|9.2 MB|5.2 MB|43% ⬇️|

### Conclusion

There are notable differences in RAM usage despite no changes have been made. I suggest running the 4.4.0 and 4.4.1 tests again.
