### ISSUE TITLE
Mixing SHA1 and MD5 check in FIM

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#16638]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | FIM | Manager/Agent | Packages/Sources | All |

In file `src/syscheckd/src/db/src/file.cpp` it was found a wrong check used to add the MD5 in the FIM event:

```c
    if (ctx->config->options & CHECK_SHA1SUM)
    {
        jsonEvent["data"]["attributes"]["hash_md5"] = data.at("hash_md5");
    }
```

To avoid having events without an MD5 when SHA1 is disabled (`<directories check_sha1="no">`) this has to be fixed.

Also, there should be an integration test for this case and other similar cases.

**Comment by vikman90** [comment]
Hi @TomasTurina, this issue has been also reported in #16625.

Closing this issue as a duplicate. Thank you!
