### ISSUE TITLE
Integration scripts refactor

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16641]
|Component|Install type|
|---|---|
| `wazuh-integratord` | Manager | 

During the development of https://github.com/wazuh/wazuh/issues/15205 I noticed that the scripts used to run the integrations are very similar and most of the code is repeated across them. I believe it would be appropriate to create a class/interface that takes care of the main flow and allows removing duplicated methods.

The new implementation should be capable of running more than one integration at the time and use the same logger in the process. Moreover, the addition of new integrations shouldn't involve more than request and message processing customization.

In order to achieve this, the pagerduty script should be migrated from bash to python as well.

Another thing to consider that is outside of the scope of this issue but that should be changed is that the `wazuh-integratord` component is calling the scripts using the same arguments for every one of them. This is not convenient for some integrations that do not require either a webhook or an API key, and still need to accept them because the integradord would fail otherwise.

**Comment by Selutario** [comment]
After talking with @davidjiglesias, we concluded that it is not worth dedicating extra efforts to these integrations since all integratord will be refactored soon. 

It was a good proposal though, the issue could be reopened in the future if the refactor is delayed longer than desired.
