### ISSUE TITLE
How to find the logs aggregated for wazuh?

### ISSUE THREAD

**Issue by npsoni88** [wazuh/wazuh#1664]
Hey guys, I have a wazuh-manager and an agent setup and working as intended. For my use-case, I need to understand where exactly are the logs getting stored after they get to wazuh-manager as I have to use the same logs for other analysis as well. How can I find its location?

Regards,
Nishant.

**Comment by juergenc** [comment]
* Current daemon log is stored in path `/var/ossec/logs/ossec.log`
* Current alert log, plain text and JSONified id enabled is stored in path `/var/ossec/logs/alerts/`
* Rotated and compressed alert logs are stored in path `/var/ossec/logs/alerts/YYYY/MM/`
* Current event log with the events as they are sent from the agents to the manager are stored in path `/var/ossec/logs/archives/`

**Comment by TJOSERAFAEL** [comment]
Hi @npsoni88 ,

@juergenc explained it very well so I'm going to close the issue.

If you have further questions, feel free to re-open the issue again. 

Thank you!

Best regards.
