### ISSUE TITLE
Policy Editor when running dark mode not readable

### ISSUE THREAD

**Issue by lmdeaton1** [wazuh/wazuh#16643]
|Wazuh Version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Wazuh dashboard | Manager | wazuh-dashboard-4.3.10-1.rpm | Red Hat 7 Enterprise |

using Chrome browser Version 111.0.5563.147

I regularly run my Wazuh instance in dark mode since it looks nicer.   I noticed the other day when making changes to the index policy that the dispaly of the "States" of the policy was almost unreadable in dark mode.  I think the CSS needs to be tweaked slightly to make this readable.  Attached file shows the issue.

![policy_editor_in_dark_mode](https://user-images.githubusercontent.com/15678631/230175392-38c8fad7-de3d-4005-a274-8e4a8b3dc2d4.jpg)

**Comment by AlexRuiz7** [comment]
Solved in newer versions 
![image](https://github.com/user-attachments/assets/155434ba-cfd1-4e05-aee4-7267bd2b3d9d)
