### ISSUE TITLE
the function OSHash_GetIndex will not return -1 as comments said

### ISSUE THREAD

**Issue by lihanhui** [wazuh/wazuh#16654]
|Wazuh version|Component|Install type|Install method|Platform|
|master|shared|NA|Sources|ALL|

As per the function signature, the return value type is int, the real one is defined as unsigned int.

**Comment by vikman90** [comment]
@lihanhui You're right, I've checked the code and it must return `unsigned int`. In addition, the comment is wrong.

I've published #17040 to fix that.

Thank you!
