### ISSUE TITLE
syscollector: Error: [json.exception.type_error.316] invalid UTF-8 byte at index 10:0xD4

### ISSUE THREAD

**Issue by dikar** [wazuh/wazuh#16652]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10| Wazuh Agent | Packages | Docker |WINDOWS 11

start agent and find error in ossec.log

**Comment by Dwordcito** [comment]
Hi, @dikar I Hope you are well!

Regardless of the error in the ossec log, could you tell me which table(process, ports, packages, etc) is one that cannot be seen in the UI? to be able to identify which of the different types of collectors is the one that is giving you problems!

Another option is to pass us the local.db found in the folder queue/syscollector/db/local.db in the Wazuh installation folder (c:/program files (x86/ossec-agent))

Could you install wazuh 4.4?

What language does the operating system have installed?

**Comment by dikar** [comment]
Thank you for your reply.
1：My OS language is zh-cn （chinese）。
2：https://wazuh.com/blog/monitoring-usb-drives-in-windows-using-wazuh/  ，Follow this blog ，I config the USB event monitor，my os is windows 10.0.22621 , but real eventId is 2100 not 6146 , I have both configured，but cannot be seen in UI.
[local.db.zip](https://github.com/wazuh/wazuh/files/11186937/local.db.zip)

**Comment by dikar** [comment]
in windows event viewer，I can find the “USB connect Event” ，the eventId is 2100 2101,2105,2106，
![Uploading eventview.jpg…]()

**Comment by dikar** [comment]
<group name="windows-usb-detect,">
  <rule id="111000" level="3">
    <if_sid>60103</if_sid>
    <field name="win.system.eventID">^2100$</field>
    <match>USBSTOR</match>
    <options>no_full_log</options>
    <description>USB $(win.eventdata.deviceDescription) was connected to $(win.system.computer)</description>
  </rule>
</group>

my rule config

**Comment by MiguelazoDS** [comment]
Hi @dikar, 

I was able to reproduce this. The error comes for the Unicode characters in the package name from the `sys_packages` table.

![image](https://user-images.githubusercontent.com/13010397/231182945-1640b21a-eb9f-4c47-81a1-b83e3b355935.png)

We'll we working on this to figure out where this field is causing this error and propose a fix to be released ASAP. 

Regards!

**Comment by dikar** [comment]
Thank you very much for your work and look forward to the new version
