### ISSUE TITLE
Validate if template files are unused - Fix them otherwise

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#16657]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1 | install.sh | Manager/Agent | Sources | Linux |

# Instroduction
There are multiple template files that seem unused:
- [ossec-agent.conf](https://github.com/wazuh/wazuh/blob/master/etc/ossec-agent.conf)
- [ossec-server.conf](https://github.com/wazuh/wazuh/blob/master/etc/ossec-server.conf)
- [ossec-local.conf](https://github.com/wazuh/wazuh/blob/master/etc/ossec-local.conf)

From these files, the `ossec-local.conf` has a missing `>` so the XML is invalid
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/etc/ossec-local.conf#L20
If turns out that the file is being used, it must be fixed.

# Description
This issue aims to analyze the installation via the [install.sh](https://github.com/wazuh/wazuh/blob/master/install.sh) script and validate if these fails are being used or not

# DoD
- [x] Installation process analyzed
- [x] Unused files removed
- [x] Fixed bad formatted file

**Comment by sultanovich** [comment]
It is also necessary to update the information in the [official documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html) to indicate if the [ossec-local.conf](https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/etc/ossec-local.conf#L20) configuration file is deprecated.

**Comment by sebasfalcone** [comment]
## Other findings
These are some interesting findings that I think could be analyzed in more depth

### Extra character can be removed
https://github.com/wazuh/wazuh/blob/e5d9fd47d96b00e276b3684b47e25b2ef58d4760/src/init/shared.sh#L40

The final semicolon can be removed.

### Unused initialization

`INSTYPE` is initialized on `src/init/shared.sh` as "server" but that value is never used.


## Some fallback options are not checked
The `WriteRootcheck`, `WriteOsquery`, `WriteSyscollector`, `WriteSyscheck`, `WriteConfigurationAssessment` and `WriteCISCAT` functions can receive as argument "agent" or "manager". If no argument is provided there is an error message and a fallback option and this fallback option is not checked. 

Example for the WriteSyscollector function (applies to all other functions):
https://github.com/wazuh/wazuh/blob/bc0b67dc1affdc8838d23eaaa72478d215a3fd22/src/init/inst-functions.sh#L120-L131

If the `wodle-syscollector.template` file is not found there is no check to indicate this.

### Error-prone checks
https://github.com/wazuh/wazuh/blob/bc0b67dc1affdc8838d23eaaa72478d215a3fd22/src/init/inst-functions.sh#L54

These checks should be:
```bash
if [ "X$1" = "Xmanager" ]; then
```
To prevent error due to variables being uninitiated. 
Ditto:
https://github.com/wazuh/wazuh/blob/bc0b67dc1affdc8838d23eaaa72478d215a3fd22/src/init/inst-functions.sh#L263-L265

This is a common practice and is used in the rest of the script.
