### ISSUE TITLE
Specify integrations scripts logging level in wazuh-integratord

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16662]
|Component|Install type|
|---|---|
| `wazuh-integratord` | Manager |

With the development of https://github.com/wazuh/wazuh/issues/15205 the integrations scripts will now allow the user to specify the logging level desired ([supported levels](https://docs.python.org/3/library/logging.html#logging-levels)).

In the old design the last argument accepted `"debug"` for enabling the debug mode or an empty string to disable logging:

```
slack <alerts_file> [api_key] <webhook_url> [debug_enabled]
```

Now, the last argument will accept the logging level name ("NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL") instead, in either lower or uppercase:

```
slack <alerts_file> [api_key] <webhook_url> [logging_level_name]
```

The `wazuh-integratord` is currently executing the scripts with the old format 

https://github.com/wazuh/wazuh/blob/ffa66c34698cb12b52161b022f69e3f5f02a1229/src/os_integrator/integrator.c#L415-L421

We need to change this and analyze if we would like to use other logging level by default (right now is no logging).

This issue's pull request and https://github.com/wazuh/wazuh/pull/16624 should be merged together.

**Comment by Selutario** [comment]
Finally not including these changes in 4.8.0. Reverted in:
- https://github.com/wazuh/wazuh/pull/19743
