### ISSUE TITLE
Enrollment logs changed from 4.3.10 to 4.4.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#16664]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1-rc1| Enrollment | Manager/Agent | Packages | Linux |

After launching the system tests for 4.4.1-rc1, it was found that the enrollment tests failed because the expected logs were not found. These logs are:

- IP address of the server:

  ```
  Server IP Address: ...
  ```

  This log has stopped appearing.

- In cases where DNS is used in the configuration:

  ```
  Requesting a key from server: <DNS>/<IP_ADDR>
  ```

  This log has been changed to:

  ```
  Requesting a key from server: <DNS>
  ```

**Comment by havidarou** [comment]
Increasing the priority for this task as an important system test depends on it.

**Comment by havidarou** [comment]
Closing this in favour of https://github.com/wazuh/wazuh-qa/issues/4383
