### ISSUE TITLE
active-response on manager

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#16672]
Wazuh manager latest version 4.4
Wazuh agent latest version 4.4

I use FIM in Wazuh and i want to add hash value of file to a CDB list on manager.
I tried created a command and active-response that trigger with rule id 550, 554.
![ảnh](https://user-images.githubusercontent.com/82009148/231124325-413f0a96-43c9-4bab-aedc-fdeefff7d0b0.png)
this file test.sh run a script that write a string to a file when active-response work and seem that don't work.
How can i use active-response that run on manager with a specified rule_id?

**Comment by thanvantrong** [comment]
Hi, @vikman90 

With this configuration, it will work but I want run this script when agent (Windows, Linux, ...) is producing alerts with ID 550 and 554.
When agent create log and alert 550, 554 this script run on manager.

Best Regards,

**Comment by thanvantrong** [comment]
Hi,

My purpose that store values from executing this script on manager and save it in manager to a file such as a cdb list.
Anyway may i do this?

Best Regards,

**Comment by traste458** [comment]
Hi,
No working wazuh 4.4.1

!/bin/bash
echo "$(date): Hello world" >> /var/ossec/logs/active-responses.log

![image](https://user-images.githubusercontent.com/116315713/233762122-637c6509-f6ee-4c35-8067-e39ecf7e7f45.png)

Settings
<command>
    <name>web</name>
    <executable>web.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>
  
 <active-response>
   <disabled>no</disabled>
    <command>web</command>
    <location>server</location>
    <rules_id>31101</rules_id>
  </active-response>

**Comment by traste458** [comment]
Best Regards,

**Comment by traste458** [comment]
<command>
    <name>web</name>
    <executable>web.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>
  
 <active-response>
   <disabled>no</disabled>
    <command>web</command>
    <location>server</location>
    <rules_id>31101</rules_id>
  </active-response>

**Comment by traste458** [comment]
`  
  <command>
    <name>web</name>
    <executable>web.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>
  
 <active-response>
   <disabled>no</disabled>
    <command>web</command>
    <location>server</location>
    <rules_id>31101</rules_id>
  </active-response>`

**Comment by traste458** [comment]
```
  
  <command>
    <name>web</name>
    <executable>web.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>
  
 <active-response>
   <disabled>no</disabled>
    <command>web</command>
    <location>server</location>
    <rules_id>31101</rules_id>
  </active-response>
```
