### ISSUE TITLE
Syscollector JSON exception invalid UTF-8 character

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#16682]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10| Syscollector | Agent | Packages/Sources | Windows |

# Description

Reported by a user https://github.com/wazuh/wazuh/issues/16652 the issue is related to https://json.nlohmann.me/home/exceptions/#jsonexceptiontype_error316 where an exception is thrown in the function `getItemChecksum()` due to dump().

https://github.com/wazuh/wazuh/blob/538d72232c20f760903e33c9512070984c8f2dcd/src/wazuh_modules/syscollector/src/syscollectorImp.cpp#L911-L917

The exception triggers when a Chinese package is installed. For testing purposes, the package installed was this (https://www.kdocs.cn/)

But during the Syscollector scan the exception is not related directly to this package

![image](https://user-images.githubusercontent.com/13010397/231497256-bf74cad8-40be-44e5-8222-53e8bae96521.png)

# Steps to reproduce

- Windows simplified Chinese (zh-cn) installation. 

<details>
<summary>Expand image</summary>

![image](https://user-images.githubusercontent.com/13010397/232506093-54f7cb2c-3ab7-40f8-a1ff-40662c3a3ced.png)

</details>

- Install a Chinese package. (i.e. https://www.kdocs.cn/)

- Restart the agent to force a syscollector scan 
- An error is shown in the ossec.log file
![image](https://user-images.githubusercontent.com/13010397/232510323-5244dc7d-fb83-47c5-8ff5-30cb86fd1754.png)

**Note: The issue was not reproducible using the same Chinese package on Windows en-us**

**Comment by MiguelazoDS** [comment]
# New findings

Going further into this issue, the cause is not the package itself, but some processes it starts. 

The `sys_package` inventory is properly filled with the proper information. 

![image](https://user-images.githubusercontent.com/13010397/231505852-d05a06b3-8fd3-456a-89d3-ab352c5090db.png)

**Comment by pereyra-m** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/16901

**Comment by MiguelazoDS** [comment]
Blocked by https://github.com/wazuh/wazuh/issues/17186 (created after #16901)

**Comment by MiguelazoDS** [comment]
Cmocka for Windows agent failed. Issue related

https://github.com/wazuh/wazuh-jenkins/issues/5081
