### ISSUE TITLE
Upgrade hiredis version to >2.1.0

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16680]
The [hiredis python library](https://github.com/redis/hiredis-py) released the `2.1.0` version which added support for the hiredis version `1.1.0` that includes a security fix. The library version we are using is `1.1.0`, we should upgrade it to `2.1.0` or a higher one.

Related issue: https://github.com/redis/hiredis-py/issues/134
Fix: https://github.com/redis/hiredis-py/pull/135

hiredis 1.1.0 release: https://github.com/redis/hiredis/releases/tag/v1.1.0
hiredis 1.1.0-rc1 release (1.1.0 includes rc1): https://github.com/redis/hiredis/releases/tag/v1.1.0-rc1

**Comment by mhamra** [comment]
### UPDATE
Tested hiredis 2.1.0 with python 3.10.11 and source code of the branch fix/16526-rewrite-async-tests-and-abstractclienttest-and-functions from [pr 16545](https://github.com/wazuh/wazuh/pull/16545)

The installation of this hiredis package:
- Does not generate conflicts with other framework packages installed with pip -r framework/requirements.txt and pip -r jenkins_requirements.
- Does not break framework, api and wodles unit tests

**Comment by fdalmaup** [comment]
# Issue Update

The update has been done using hiredis version `2.2.3`. A successful installation was carried out for `amd64`. No warning nor errors were present in the logs. 

The `aarch64` installation is in progress.

**Comment by fdalmaup** [comment]
# Issue Update

The `aarch64` installation was successful. No code modifications were needed. The requirements modifications can be carried out in the epic branch to avoid the need of uploading the new dependencies for this particular issue. This needs to be discussed with the team.

**Comment by fdalmaup** [comment]
# Issue Update

The proposal of adding the dependency update directly in the epic branch was discussed with the team and approved.

**Comment by EduLeon12** [comment]
After reading all the analysis behind the version of the mentioned dependency and testing the upgrade.

I conclude that the analysis was well executed and that the scope of the issue has been fulfilled. Therefore I approve this issue.

LGTM! 👍🏼

**Comment by mhamra** [comment]
I agree with the decision to upgrade the package. 

Package installation was tested by [#13267](https://github.com/wazuh/wazuh/issues/13267) and  [PR 16408].

I approve of this issue. LGTM!
