### ISSUE TITLE
Add a version control mechanism in cve.db for Vulnerability Detector

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#16699]
## Description

The Vulnerability Detector module stores all the external feeds data in the `cve.db`. This DB also has some tables that are temporarily used during the scans.

It lacks any schema upgrade mechanism or version control because this DB is supposed to be deleted during the upgrade.
But this assumption might not be valid in a Docker deployment for example. So, if the tables in the DB have a breaking change in their structure, Vulnerability Detector will fail to read it and the `cve.db` will have to be manually deleted to make the module work again.

See for example
- https://github.com/wazuh/wazuh/issues/4401
- https://wazuh.slack.com/archives/C0A933R8E/p1680543595265869
- https://wazuh.slack.com/archives/C0A933R8E/p1680511376992489

## DoD

- [x] Add a new table in `cve.db` to store the schema version
- [x] Add a mechanism to check the DB version in Vulnerability Detector and recreate the DB in case it isn't compatible
- [x] Remove all the references to the removal of `cve.db` during an upgrade (in all repositories) because this step won't be needed
- [x] Make sure to properly document this change, so every future modification in the schema will be done together with a version change 
- [x] Test the upgrade in different ways: sources, packages, docker, etc.
- [x] All CI tests must pass.

**Comment by Dwordcito** [comment]
Close as not planned because 4.8.0 is coming.
