### ISSUE TITLE
Manager(ossec-remoted) failed to listen

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#1670]
Hi Teams,

## Bug report

**OS**
_CentOS7_

**Wazuh version**
```
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.6.2"
REVISION="3609"
DATE="Sun Sep 16 16:58:32 CST 2018"
TYPE="server"
```

**Install type**
_manager_

**Install method**
_sources_

**Log sample**

```
2018/10/17 12:37:46 ossec-remoted: ERROR: Unable to open agent file. errno: 13
2018/10/17 12:37:46 ossec-remoted: CRITICAL: (1103): Could not open file '/queue/rids/041' due to [(13)-(Permission denied)].
2018/10/17 12:37:47 wazuh-modulesd: ERROR: socketerr (not available).
2018/10/17 12:37:47 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Connection refused)
2018/10/17 12:37:47 wazuh-modulesd: ERROR: socketerr (not available).

```

Bug description
----------------

```
# ls -al ../queue/rids/041 
-rw-r--r-- 1 ossec ossec 0 Oct 17 11:59 ../queue/rids/041

```

I remove all files in `/queue/rids` and failed to solve.

My local_internal_options.conf
```
# Maximum number of file descriptor that Analysisd can open [1024..2147483647]
analysisd.rlimit_nofile=262144

# Maximum number of file descriptor that Remoted can open [1024..2147483647]
remoted.rlimit_nofile=262144

# Maximum pending connections (1..1024)
wazuh_db.sock_queue_size=1024

# Number of worker threads (1..32)
wazuh_db.worker_pool_size=16

wazuh_database.max_queued_events=163840
```

**Comment by iAklis** [comment]
Hi Teams,

I fully reinstall and recovery client.keys and then the `ossec-remoted` dead .

Best Regrads.

**Comment by vikman90** [comment]
Hi @iAklis,

Apologies for the late reply. We have not managed to reproduce this issue on clean installations or a manager upgrade.

This is the correct content of a _rids_ folder:
```
# ls -lh /var/ossec/queue/rids
total 16K
-rw-r--r-- 1 ossecr ossec 7 Nov 26 19:45 001
-rw-r--r-- 1 ossecr ossec 7 Nov 27 14:10 002
-rw-r--r-- 1 ossecr ossec 0 Nov 27 14:13 004
-rw-r--r-- 1 ossecr ossec 7 Nov 27 17:47 008
-rw-r--r-- 1 ossecr ossec 7 Nov 27 17:47 sender_counter
```

Every file must belong to the user `ossecr` (for _ossec-remoted_). The manager would never change the owner of those files.

There are two common causes for this issue:
1. Install a manager over an agent, or install an agent where an agent existed and no clean up performed.
2. Accidental manipulation by a user.

Could you kindly confirm us that none of these cases happened? Have you had this problem again?

Best regards.
