### ISSUE TITLE
Global inventory data dashboard

### ISSUE THREAD

**Issue by pulpon6** [wazuh/wazuh#16706]
I want to make a request for as a future feature, an inventory software

Actually I need to go 1 by 1 on the inventory data to see software installed and version, so this feature can make a dashboard and search a software, version, or vendor and show all the agents that has that specifc software 

An example, I need to check Google Chrome version because some endpoints has a vulnerable version, so I search on that dashboard to see all the endpoints that have Chrome installed and that version

**Comment by TheMuntu** [comment]
Hello @pulpon6,

If you want to gather the software inventory data across different agents my recommendation is to use the [Wazuh API](https://documentation.wazuh.com/current/user-manual/api/reference.html) to create a script that loops over the agent list and retrieve the inventory  information you need from each of them.
These two endpoints would be used following that route:
- https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agents
- https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info

You could store this information in a CSV file and open it using Excel or similar.

Hope this helps!
