### ISSUE TITLE
Initial research on RocksDB (cache replacement policies) 

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16702]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description
Initial research must be conducted on RocksDB capabilities to:

 - [x] Set memory limits.
 - [x] Respond to DB handler inactivity.
 - [x] Modify cache replacement policies.
 
 It is important in this research to determine in which areas these policies can be modified.
 - Column families.
 - DB.
 - Any other.
 
 ## DoD
 - [x] Create a tech spike document with results. [Document](https://docs.google.com/document/d/1a8OuBsXWcWnpDsE1FMC6gpOTvwKuP8zKn5V_JHX6zLs/edit#heading=h.xylwgui9cfjq)

**Comment by soynof** [comment]
Just for tracking purposes: Initial Research document can be found here: https://docs.google.com/document/d/1a8OuBsXWcWnpDsE1FMC6gpOTvwKuP8zKn5V_JHX6zLs/
