### ISSUE TITLE
Design and Write draft of Initial Architecture

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#16704]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

The initial architecture must support or consider:

1. Having a single RocksDB:DB with multiple Column Families (CF)
2. Glossary: From now on a "DB" refers to an abstract Key Value Database that is implemented as point 1. i.e. Host Agent Data is a DB, Malicious IP is a DB, Whitelist IP is a DB, and so on.
3. Removing usage of shared_ptr internals (use_count) to address locking of actions at DB-Level such as DB Delete
4. Runtime identification and reporting of what internal module or component of the Engine is using or locking a DB.

## Iterations DoD

 - [x] Iteration 1
   - [x] Study existing code.
   - [x] Write draft Interface Classes and connect to existing code.
   - [x] Identify KVDBHandler's issues. This was the KEY to start a 2nd iteration. 
   - [x] Propose Abstraction of point 1. (Single DB , Multiple CF)
![image](https://user-images.githubusercontent.com/117848458/236012863-9989dbf4-1b34-4455-8ca1-6b93eb7c2d8b.png)
   - [x] Review design with Engine Team.
     - [x] Propose Design for point 4 and fixing point 3.
     - [x] Obtain approvals from lead team members.

 - [x] Iteration 2
   - [x] Exclude kvdb_bench and testing code from compilation. 
   - [x] Comment out OpBuilder KVDB Helper Functions calls to KVDB Manager.
   - [x] Create isolated module to replace existing KVDBManager
   - [x] Wrap-up architecture adding "User Management" or "Actor figure". Remove locking responsibility from KVDBHandler.
   - [x] Get compiling code from scratch.

**Comment by soynof** [comment]
### Sequence diagram: option 1

![kvdb](https://user-images.githubusercontent.com/87549285/236044830-9e7a26dd-ef3b-4728-90a8-fe97b603a812.png)

### Sequence diagram: option 2

![kvdb-II](https://user-images.githubusercontent.com/87549285/236045049-7c48a897-e826-4da6-9386-098a681febc9.png)
