### ISSUE TITLE
Add select parameter to API endpoints

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16716]
As described in https://github.com/wazuh/wazuh/issues/16552, the frontend team requires the `select` parameter to be added in some endpoints to continue with their search bar improvements.

The endpoints to be updated are:
- [x] `GET /decoders/files`
- [x] `GET /groups/{group_name}/files`
- [x] `GET /rules`
- [x] `GET /rules/files`
- [x] `GET /sca/{agent_id}`
- [x] `GET /manager/logs`
- [x] `GET /cluster/{node}/logs`

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Added the `select` parameter to all the endpoints.

**Comment by GGP1** [comment]
## Update

Updated unit tests, the API specification and opened the PR.

The integration test check is failing as in https://github.com/wazuh/wazuh/issues/16714, the failure is unrelated to the changes. I will pause the development of both issues temporarily and investigate further about these tests.

**Comment by GGP1** [comment]
## Update

The blocking issue https://github.com/wazuh/wazuh/issues/16750 is now pending review, the workflow of this issue is resumed.

**Comment by GGP1** [comment]
## Update

Rebased the branch to master to re-run checks but it seems like there are some of them failing and they are not related to the changes.

**Comment by GGP1** [comment]
## Update

Rebased master to re-run the checks and all of them passed. Updated status to _Pending review_

**Comment by GGP1** [comment]
## Update

- Added the `allowed_select_fields` parameter in the function `process_array` for all endpoints
- Added the AIT for the select field on all endpoints

**Comment by GGP1** [comment]
## Update

Added "Try to" at the start of each stage that was asserting failed items, as requested by the reviewer.

**Comment by Selutario** [comment]
**ETA postponed. Reason:**
- [Fix to AITs in 4.5.0](https://github.com/wazuh/wazuh/issues/17690) has not been ported to other branches yet.
