### ISSUE TITLE
Add distinct parameter to API endpoints

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16715]
As described in https://github.com/wazuh/wazuh/issues/16552, the frontend team requires the `distinct` parameter to be added in some endpoints to continue with their search bar improvements.

The endpoints to be updated are:
- [x] `GET /lists`
- [x] `GET /decoders`
- [x] `GET /decoders/files`
- [x] `GET /manager/configuration?section=ruleset&field=decoder_dir`
- [x] `GET /groups`
- [x] `GET /groups/{group_name}/agent`
- [x] `GET /groups/{group_name}/files`
- [x] `GET /rules`
- [x] `GET /rules/files`
- [x] `GET /manager/configuration?section=ruleset&field=rule_dir`
- [x] `GET /mitre/groups`
- [x] `GET /mitre/mitigations`
- [x] `GET /mitre/software`
- [x] `GET /mitre/tactics`
- [x] `GET /mitre/techniques`
- [x] `GET /sca/{agent_id}`
- [x] `GET /syscollector/{agent_id}/netiface`
- [x] `GET /syscollector/{agent_id}/ports`
- [x] `GET /syscollector/{agent_id}/netaddr`
- [x] `GET /syscollector/{agent_id}/netproto`
- [x] `GET /syscollector/{agent_id}/packages`
- [x] `GET /syscollector/{agent_id}/processes`
- [x] `GET /syscollector/{agent_id}/hotfixes`
- [x] `GET /security/policies`
- [x] `GET /security/roles`
- [x] `GET /security/rules`
- [x] `GET /security/users`
- [x] `GET /manager/logs`
- [x] `GET /cluster/{node}/logs`
- [x] `GET /cluster/nodes`

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Added the `distinct` parameter to multiple endpoints (checked their boxes above), different database objects and the method `process_array`, also updated its unit test with new test cases.

**Comment by GGP1** [comment]
## Update

Added the `distinct` parameter to multiple endpoints (checked their boxes above), different database objects and the method `process_array` (updated its unit test with new test cases).

**Comment by GGP1** [comment]
## Update

Added the `distinct` parameter to multiple endpoints (checked their boxes above), different database objects and the method `process_array` (and updated its unit test with new test cases).

**Comment by GGP1** [comment]
## Update

Updated unit tests, the API specification and opened the PR.

Failed checks are unrelated to the changes introduced. I will leave the issue on hold until they are fixed.

**Comment by GGP1** [comment]
## Update

Initially, when I opened the pull request a few checks failed, all of them related to the Debian build except one which was related to https://github.com/wazuh/wazuh/issues/16714. After being notified that the Debian build was fixed, I requested a re-launch of the checks and now many more tests are failing.

I ran locally the following tests:

- framework unit tests: ❌ (failed in master as well, errors caused by an empty field in the API spec, created the following issue to address it https://github.com/wazuh/wazuh/issues/16918)
- test_agent_POST_endpoints: ✔️
- test_agent_PUT_endpoints: ❌ (related to https://github.com/wazuh/wazuh/issues/16347, still not in master)
- test_rbac_white_agent_endpoints: ❌ (related to https://github.com/wazuh/wazuh/issues/16714)
- test_rbac_black_cdb_list_endpoints: ✔️

**Comment by Desvelao** [comment]
Hi @GGP1, we need to add the `distinct` query parameter to the endpoint
```
GET /syscollector/{agent_id}/netaddr
```
https://github.com/wazuh/wazuh/issues/16552#issuecomment-1534329122

> I updated the initial message of this issue with the requirement.

**Comment by Desvelao** [comment]
The Wazuh plugin uses the endpoint `GET /agents/summary/distinct` to get the distinct values for the fields related to agents. But this endpoint returns data related to the item count that  is not used, so maybe it can make sense to implement the `distinct` query parameter in these endpoints too.

Affected endpoints:
- `GET /agents`
- `GET /groups/{group_name}/agents`

**Comment by GGP1** [comment]
## Update 

Rebased master, added the `distinct` parameter to `GET /syscollector/{agent_id}/netaddr` and `GET /agents` endpoints and squashed commits. 

> In `GET /groups/{group_name}/agents` I added it before.

**Comment by Desvelao** [comment]
Hi @GGP1, related to https://github.com/wazuh/wazuh/issues/16552#issuecomment-1560842385, we need the `distinct` parameter will be added to `GET /cluster/nodes` too.

I changed the initial message of this issue to include this endpoint.

**Comment by GGP1** [comment]
## Update

Added the `distinct` parameter to the `GET /cluster/nodes` as requested by @Desvelao. 

Moving the state to blocked since there are checks failing in master.

**Comment by Desvelao** [comment]
> ## Update
> Added the `distinct` parameter to the `GET /cluster/nodes` as requested by @Desvelao.
> 
> Moving the state to blocked since there are checks failing in master.

Thank you!

**Comment by GGP1** [comment]
## Update

I ran a failed check again and it passed. Updated the status to _Pending review_.

**Comment by GGP1** [comment]
## Update

I ran the failed check again and it passed. Updated the status to _Pending review_.

**Comment by GGP1** [comment]
## Update

Applied requested changes and moved it back to _Pending review_.

**Comment by Desvelao** [comment]
I missed the endpoint request of `GET /security/role_mapping`, it is `GET /security/rules` instead.

**Comment by Desvelao** [comment]
I see there is a pull request and these endpoints are not checked.
- GET /manager/configuration?section=ruleset&field=decoder_dir
- GET /manager/configuration?section=ruleset&field=rule_dir

Is there some problem with these endpoints @GGP1 ?

**Comment by GGP1** [comment]
Hi @Desvelao,

Sorry, I thought `GET /security/role_mapping` was reviewed and disregarded. I will add the parameter to `GET /security/rules`.

The `GET /manager/configuration?section=ruleset&field=decoder_dir` and `rule_dir` endpoints responded with an object when I tried them (decoder_dir and rule_dir), but after reviewing the code I noticed it was because I had changed the configuration, using default values returns an array. I will change this as well.

**Comment by GGP1** [comment]
## Update

Added the `distinct` parameter to the `GET /manager/configuration?section=ruleset&field=decoder_dir`, `GET /manager/configuration?section=ruleset&field=rule_dir` and `GET /security/rules` endpoints. Moved state to _Pending review_.

**Comment by GGP1** [comment]
## Update

- Added API integration tests for the `distinct` field
- Fixed a bug where the distinct field failed for the `GET /groups` endpoints because the WazuhDB `self.select` field was `None` and the default assignation was overwritten.

Changing the status to Pending review in spite of the failed checks since it's known that they do not pass and the ETA is close to this date. I've run the tests locally and they pass.

**Comment by GGP1** [comment]
## Update

- Changed the `distinct` default value from `None` to `False` in a unit test
- Ran AIT and posted the results in the description of the PR
