### ISSUE TITLE
Evaluate the impact of non-UTF8 string in the data provider for all platforms

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#16713]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | Syscollector | Agent | Packages/Sources | Any |

# Description 

As consequence of the fix implemented as part of this issue https://github.com/wazuh/wazuh/issues/16682 we need to evaluate a better way to convert the strings into UTF8 format for all required field in the data provider considering different platforms. 

# DoD 

- [x] Research about some standard function that could do the task for multiple platforms.
- [x] Propose an implementation.
- [x] RTR successful.

**Comment by MiguelazoDS** [comment]
# Findings

For Linux there's no issue with encoding. Some examples with Chinese and Spanish characters. 

![image](https://user-images.githubusercontent.com/13010397/232138754-f8692a4c-e584-4c8c-a0ac-9a4ed87edbcd.png)

**Comment by Dwordcito** [comment]
Thanks, for the analysis @MiguelazoDS
