### ISSUE TITLE
Removing the last agent in a group with manage_agents does not delete the subdirectory /var/ossec/var/multigroups/xxxxxxxx

### ISSUE THREAD

**Issue by juan70** [wazuh/wazuh#1672]
## Bug report

**OS**
CentOS7

**Wazuh version**
3.7.0-0.3708.16102018.37.nightly

**Wazuh API version**
3.7.0

**Install type**
Manager.

**Install method**
Packages

Bug description
----------------
Point 10. of the test suite in https://github.com/wazuh/wazuh/issues/1238
- Remove an agent with manage_agents
  Steps to reproduce:
    - Connect 2 agents to the manager, adding them to a multigroup
      (create the groups in the manager previously)
      `/var/ossec/bin/agent-auth -m 192.168.56.103 -G grupo1,grupo2,grupo3`
    - Check that the agents belong to grupo1, grupo2, and grupo3
      `/var/ossec/bin/agent_groups -s -i 001`
      `/var/ossec/bin/agent_groups -s -i 002`
    - Remove one of the agent
      `/var/ossec/bin/manage_agents -r 001`
    - Remove the second agent
      `/var/ossec/bin/manage_agents -r 002`

  Results:
    - Expected result:
      - the subdirectory `/var/ossec/var/multigroups/xxxxxxxx` is removed
      - the file `/var/ossec/queue/agent-groups/001` is removed
      - the file `/var/ossec/queue/agent-groups/002` is removed
    - Actual result:
      - **FAIL**: the subdirectory `/var/ossec/var/multigroups/xxxxxxxx` is not removed
      - **FAIL**: the file `/var/ossec/queue/agent-groups/001` is not removed, sometimes it is, sometimes not...
      - **OK**: the file `/var/ossec/queue/agent-groups/002` is removed

    - Another problem is also observed:
      - Using a completlety clean install for the manager and for the agents, the registration of the agents includes them also in the `default` group, along with the others (here, in `grupo1`, `grupo2`, `grupo3`). This is OK.
      - But then, after making a clean install only for the manager (remove, rm -rf /var/ossec/, and install), the new registration of the same agents as above (already configured with the manager IP and son on) does not included them in group `default` (only, in `grupo1`, `grupo2`, `grupo3`).
        ```
        # /var/ossec/bin/agent_groups -l
        Groups (4):
          default (0)
          grupo1 (2)
          grupo2 (2)
          grupo3 (2)
        Unassigned agents: 0.                                                                                                   
        ```
      - In that situation, when the agents are removed, `/var/ossec/queue/agent-groups/(001|002)` are also removed (both of them), which is OK; but `/var/ossec/var/multigroups/xxxxxxxx` is not removed, and this is NOT OK.
      - And `/var/ossec/var/multigroups/xxxxxxxx` contains only `agent.conf` and `merged.mg`.

**Comment by chemamartinez** [comment]
Hi Juan,

It is the expected behavior that the directory with the files merged from different groups is not removed after deleting agents, this is mandatory to be able to reassign agents to its correct groups when it is readded to the manager.

We have to investigate the second issue related to agents belonging to the group `default` when reinstalling the manager.

**Comment by TJOSERAFAEL** [comment]
Hello @juan70 

this PR solves the issue https://github.com/wazuh/wazuh/pull/1695. The agents multigroup must be removed from **.metadata** and **/var/multigroups/xxxyyyzz** if not used by any other agents.

Regards.
