### ISSUE TITLE
wazuh-clusterd can't start in CentOS 6

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#1673]
## Bug report

**OS**
_CentOS 6_

**Wazuh version**
_3.7.0-3708_

**Wazuh API version**
_NA_

**Install type**
_manager_

**Install method**
_packages_

**Log sample**

```
[root@localhost vagrant]# service wazuh-manager restart
Stopping OSSEC:                                            [  OK  ]
Starting OSSEC:                                            [FAILED]
[root@localhost vagrant]# cat /var/ossec/logs/ossec.log | grep cluster
[root@localhost vagrant]# /var/ossec/bin/wazuh-clusterd -fdd
Error starting wazuh-clusterd: Error starting wazuh-clusterd. Minimal Python version required is 2.7. Found version is 2.6
[root@localhost vagrant]#
```

Bug description
----------------

If you enable wazuh-cluster in a CentOS 6 node (it doesn't matter if it is a master node or a client), when the wazuh-manager is restarted, it fails because wazuh-clusterd fails. The error is related with the python version, but I installed `python27` using:
```
# yum install -y centos-release-scl
# yum install -y python27
```

In addition, there aren't any logs in ossec.log and cluster.log. Related issue https://github.com/wazuh/wazuh/issues/1411.

**Comment by crolopez** [comment]
You may not have Python 2.7 enabled. Try the following command:

`scl enable python27 bash`

Best regards.
