### ISSUE TITLE
High memory consumption on agent

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#16740]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.1 | modulesd,logcollector | Agent | Packages | Ubuntu 18.04, Ubuntu 22.04, Rocky Linux 8.6  |

## Description

[A user](https://wazuh.slack.com/archives/C0A933R8E/p1681737994506579?thread_ts=1681734581.533439&cid=C0A933R8E) reported massive memory consumption (1.6GB) after enabling the docker-listener wodle. The user also reported that the consumption decreases after a few minutes and sometimes after a restart (I was unable to replicate this last part)

This was replicated on a Ubuntu 22.04 machine with a clean OS and installation. The consumption was 600MB at max.

## Extra information
The user sent the memory usage from the agent on the peak consumption.

Note the message **"This usually indicates unclean termination of a previous run, or service implementation deficiencies."**

```bash
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2023-04-17 13:25:47 UTC; 1s ago
    Process: 1245694 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
      Tasks: 38 (limit: 4676)
     Memory: 1.6G
     CGroup: /system.slice/wazuh-agent.service
             ├─1245716 /var/ossec/bin/wazuh-execd
             ├─1245724 /var/ossec/bin/wazuh-agentd
             ├─1245738 /var/ossec/bin/wazuh-syscheckd
             ├─1245752 /var/ossec/bin/wazuh-logcollector
             ├─1245769 /var/ossec/bin/wazuh-modulesd
             ├─1245780 python3 wodles/docker/DockerListener
             ├─1245850 sh -c journalctl | grep "protection: active"
             ├─1245852 journalctl
             └─1245853 grep protection: active

Apr 17 13:25:41 post.uhlhosting.ch systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Apr 17 13:25:41 post.uhlhosting.ch systemd[1]: Starting Wazuh agent...
Apr 17 13:25:41 post.uhlhosting.ch env[1245694]: Starting Wazuh v4.4.1...
Apr 17 13:25:41 post.uhlhosting.ch env[1245694]: Started wazuh-execd...
Apr 17 13:25:42 post.uhlhosting.ch env[1245694]: Started wazuh-agentd...
Apr 17 13:25:43 post.uhlhosting.ch env[1245694]: Started wazuh-syscheckd...
Apr 17 13:25:44 post.uhlhosting.ch env[1245694]: Started wazuh-logcollector...
Apr 17 13:25:45 post.uhlhosting.ch env[1245694]: Started wazuh-modulesd...
Apr 17 13:25:47 post.uhlhosting.ch env[1245694]: Completed.
Apr 17 13:25:47 post.uhlhosting.ch systemd[1]: Started Wazuh agent.
```

**Comment by uhlhosting** [comment]
Please note this is not only related to docker, in fact just deploying the agent alone on a new server, will produce a spike. The highest I had was 5 GB+ until now.

**Comment by uhlhosting** [comment]
@havidarou can you explain the reason for this?
