### ISSUE TITLE
Invalid root element "rule".Only "group" is allowed error

### ISSUE THREAD

**Issue by c0r3dump3d** [wazuh/wazuh#16761]
|Wazuh version| Component | Action type |
|4.4.0| manager | Suppress a rule |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

## Description

Try to suppress a rule.

### Service/Product/Module

Wazuh manager

### Current results
Following the documentation (https://documentation.wazuh.com/current/user-manual/ruleset/custom.html) I have this error when applied change:

```
023/04/19 11:19:48 wazuh-analysisd: ERROR: rules_op: Invalid root element "rule".Only "group" is allowed
wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'
```

In the /var/ossec/etc/rules/local_rules.xml create the syntax in order to suppress the rule:

```
<rule id="31350" level="0" timeframe="20" frequency="8" overwrite="yes">
    <if_matched_sid>31530</if_matched_sid>
    <same_source_ip />
    <description>High amount of POST requests in a small period of time (likely bot).</description>
   <group>pci_dss_6.5,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SA.11,nist_800_53_SI.4,tsc_CC6.6,tsc_CC7.1,tsc_CC8.1,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
    <mitre>
      <id>T1498</id>
    </mitre>
   </rule>
```

### Expected results

Disable the rule.

**Comment by pereyra-m** [comment]
Hello @c0r3dump3d !

It seems that there is a format issue in your `local_rules.xml` file.
You could share it so we can check the customs rules, but I was able to reproduce this error by removing the general `<group>` tag.

For example, this is a correct file

```xml

<!-- Local rules -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015, Wazuh Inc. -->

<!-- Example -->
<group name="local,syslog,sshd,">

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

</group>

```

But if we remove the tag like this

```xml
<!-- Local rules -->

<!-- Modify it at your will. -->
<!-- Copyright (C) 2015, Wazuh Inc. -->

<!-- Example -->

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>

```

I get the same error when I try to start the manager

```bash
root@eae9d6eaa551:/var/ossec# ./bin/wazuh-control restart
2023/04/20 12:57:17 wazuh-analysisd: ERROR: rules_op: Invalid root element "rule".Only "group" is allowed
2023/04/20 12:57:17 wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
wazuh-analysisd: Configuration error. Exiting
```

Please, add a root group tag and try again.
Regards.

**Comment by c0r3dump3d** [comment]
Thank's for the answer, now it's working, but I don't understand so much why it's working, the documentation it's seems not very clear.

**Comment by pereyra-m** [comment]
Hi gain @c0r3dump3d !

Sorry for the inconveniences. The documentation team was notified about this and a proper note will be added as soon as possible. 
Thank you for helping to improve the project.
