### ISSUE TITLE
getting 404 on wazuh-modulesd:github even after setting the configs correctly

### ISSUE THREAD

**Issue by xetova-technology** [wazuh/wazuh#16772]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.1 | github | aws all in one | server | Linux/Unix, Amazon Linux Amazon Linux 2 (Karoo) |

here is a sample log

Apr 20, 2023 @ 11:20:53.000 wazuh-modulesd:github INFO  Module GitHub started.
Apr 20, 2023 @ 11:22:53.000 wazuh-modulesd:github WARNING  Sending GitHub internal message: '{"integration":"github","github":{"actor":"wazuh","organization":"org-name","event_type":"git","response":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#get-audit-log\"}"}}'
Apr 20, 2023 @ 11:22:53.000 wazuh-modulesd:github WARNING  Sending GitHub internal message: '{"integration":"github","github":{"actor":"wazuh","organization":"org-name","event_type":"web","response":"{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#get-audit-log\"}"}}'

**Comment by vikman90** [comment]
Hi @xetova-technology,

I'm doing some tests. In the meanwhile, these are the most common causes of the _not found_ result:

- The organization (`<org_name>`) is missing or misspelled.
- The provided token does not have the right permissions (_audit_log_).
- The organization is not part of the Enterprise plan.
- The token's account is not an organization owner.

Could you please check the points above so we can rule out the most common problems? You can find more information at [Monitoring GitHub Activity](https://documentation.wazuh.com/current/github/monitoring-github-activity.html).

Best regards.
