### ISSUE TITLE
(FindLastContent class) Find the last version based on the metadata file (downloaded) and compare with rocksdb database -> chain of responsibility

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16794]
## Description

This issue aims to work on the creation of a class in charge of downloading a metadata file from a server, comparing the index value with the one stored in the local database, and storing the result of this comparison.

## Expected

After this issue is completed, we should expect the following:
- A class called `FindLastContent` capable of:
  - Connect to an Amazon S3 server and download a JSON file.
  - Read the content of the downloaded JSON file.
  - Read the last value stored in the [local database](https://github.com/wazuh/wazuh/issues/16793).
  - Compare both values and calculate the difference.
  - Save this value.

## DoD

- [ ] Add Test (unit/component).
- [ ] Update any relevant documentation.

**Comment by Damian-Mangold** [comment]
It was not necessary to develop a stage that executes this action, since there will not always be versioned content, it is preferable that this action be executed by the download stage.
