### ISSUE TITLE
Add a chain of responsibility for the content updater orchestrator

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16791]
## Description

Implement a Chain of Responsibility pattern using the `chainOfResponsibilities.hpp` helper template. This should use other implementations available in this epic, such as download, decompression, publication, and cleanup.

## Expected

The Chain of Responsibility pattern should be implemented and working as expected, with each component in the chain executing its designated task.

## DoD

- [x] Implement the Chain of Responsibility pattern using the `chainOfResponsibilities.hpp` helper template.
- [x] Ensure the download, decompression, publication, and cleanup components are correctly integrated into the chain.
- [x] Verify that each component in the chain executes its designated task as expected.

**Comment by Damian-Mangold** [comment]
Implementation added in the following commit --> https://github.com/wazuh/wazuh/commit/58909dfc8c57ea6dde8ad7fd7a32d4170cfe883f
