### ISSUE TITLE
FactoryDecompressor - Add a factory that allows to create a specific decompressor

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16797]
## Description

This issue aims to work on the creation of a class in charge of creating a factory to perform an instance of a certain decompressor.

## Expected

Once this issue is finished, we should expect the following:

- A class called `FactoryDecompressor` capable of:
  - Make an instance of certain decompressors.
  - Make an instance of a SkipStep class if a decompressor is not needed.
  - Throw an exception if the chosen decompressor is not supported.
- This class must be a stage of an orchestration.
- This class must be independent of the rest of the chain, allowing to test it with unit tests.

## DoD

- [ ] Add Test (unit/component).

**Comment by Damian-Mangold** [comment]
Implementation added in the following commit --> https://github.com/wazuh/wazuh/commit/d4c89b98f71ca09776006e9ba94c1c977f1f8fd6
