### ISSUE TITLE
Implement the `S3Downloader` class

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16796]
## Description

This issue aims to work on the creation of a class in charge of downloading a file from an Amazon S3 server.

## Expected

Once this issue is finished, we should expect the following:

- A class called `S3Downloader` capable of:
  - Connect to an Amazon S3 server and download a file of content.
- This class should be a stage of a sub-orchestration.
- This class should be independent from the rest of the chain, allowing us to test it with unit tests.

## DoD

- [ ] Add Test (unit/component).

**Comment by Damian-Mangold** [comment]
Uploaded a base implementation in this commit --> https://github.com/wazuh/wazuh/commit/c9e236ed532da4b8fe85400cf9bf21d526621fec

**Comment by Damian-Mangold** [comment]
Updated implementation in this commit --> 833c4e8645f2418eecc7186fe1e2c5a1f1809112
