### ISSUE TITLE
Error in Compilation whilst updating

### ISSUE THREAD

**Issue by jamesspi** [wazuh/wazuh#168]
Hi all,

Trying to update a server on Centos 7, getting this after the latest pull and update:

shared.a(syscheck_op.o): In function `sk_fill_event':
syscheck_op.c:(.text+0x576): undefined reference to `ErrorExit'
shared.a(custom_output_search_replace.o): In function `searchAndReplace':
custom_output_search_replace.c:(.text+0x1f8): undefined reference to `ErrorExit'
collect2: error: ld returned 1 exit status
make: *** [ossec-analysisd] Error 1

Any ideas please?

Thanks!
James

**Comment by vikman90** [comment]
Hi @jamesspi,

we replaced every call to `ErrorExit()` for `merror_exit()`. But we can't find any call to the old `ErrorExit()` in the code of branches *stable*, *master*, *2.0*, *2.1* or *3.0*.

Did you `make clean` in the folder `src` before installing the upgrade?

Please make double check and tell us if the problem persists.
Best regards.

**Comment by jamesspi** [comment]
Hi Vik,

Doh, that did the trick! Thanks for that!

James
