### ISSUE TITLE
Add mechanism to trigger offline orchestration with UNIX socket call

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16804]
## Description

Design a mechanism to trigger an orchestration via UnixSocket and HTTP that will search for a file in the filesystem and add it to the subscriber instead of downloading it.

## Expected

The mechanism should be designed and implemented so that it can be triggered via UnixSocket and HTTP, and that it will search for a file in the filesystem and add it to the subscribers.

## DoD

- [ ] Design a mechanism for triggering an orchestration via UnixSocket and HTTP.
- [ ] Implement the mechanism so that it searches for a file in the filesystem and send the data to the subscriber.
- [ ] Verify that the mechanism works as expected when triggered via UnixSocket and HTTP, and that it correctly adds the file to the subscriber

**Comment by Damian-Mangold** [comment]
Design change, implemented here https://github.com/wazuh/wazuh/issues/20498
