### ISSUE TITLE
(CleanUpContent) Removes the temp files and adds them to the sub-chain

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16802]
## Description

This issue aims to work on the creation of a class in charge of deleting all the files used during sub-orchestration.

## Expected

Once this issue is finished, we should expect the following:

- A class called `CleanUpContent` capable of:
  - Delete all files downloaded and created during sub-orchestration.
- This class must be a stage of a sub-orchestration.
- This class must be independent of the rest of the chain, allowing us to test it with unit tests.

## DoD

- [x] Add Test (unit/component).

**Comment by Damian-Mangold** [comment]
Implementation added in the following commit --> https://github.com/wazuh/wazuh/commit/54eb55e622fb9e103179553bc2b953654dcf923d
