### ISSUE TITLE
Add a mechanism if the Delta processor fails, to use a complete content file as a fallback mechanism.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#16803]
## Description

This issue aims to work on the creation of a class in charge of creating a mechanism that downloads the full content file, processes the data, and distributes it.
This mechanism must be implemented by a sub-orchestration and must be executed if for some reason the storage of the delta content in the manager database fails.

## Expected

Once this issue is finished, we should expect the following:

- A class called `FullProcessor` capable of creating a sub-orchestration with the following steps:
  - Connect to an Amazon S3 server and download a compressed file of content.
  - Decompress the downloaded file.
  - Read the decompressed content.
  - Publish the content.
  - Update the local database.
  - Clean all downloaded and unzipped data.

## DoD

- [ ] Add Test (unit/component).
- [ ] Update any relevant documentation.

**Comment by Damian-Mangold** [comment]
Design change. This issue is not valid.
