### ISSUE TITLE
`server.start.policy` is not saved with the expected format

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16806]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16156   |     https://github.com/wazuh/wazuh/pull/16235 |

# Description

During the reorganization API testing the server.start.policy field is not saved with the format that it has before.

When you modify the policy it is transformed into another format

Performing a request like this:

```json
{
    "command": "config",
    "subcommand": "put",
    "parameters": {
        "name": "server.start.policy",
        "content": "default:232:filter/allow-all/0:policy/wazuh/0"
    }
}
```

The policy field within the configuration file is filled like this:

```
server.start.policy=[\"default\", 232, \"filter/allow-all/0\", \"policy/wazuh/0\"]
```

When it should looks like:

```
server.start.policy=\"default:255:filter/allow-all/0:policy/wazuh/0\"
```

## Considerations

More details in the dev-testing report https://github.com/wazuh/wazuh-qa/issues/4040#issuecomment-1513640663

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed in https://github.com/wazuh/wazuh/issues/18990
