### ISSUE TITLE
Update PCI labels on Red Hat Enterprise Linux 9

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#16858]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.4.x | SCA| Improve |

The current label format is: 

```
      - pci_dss_3.2.1: ["8.1.8"]
      - pci_dss_4.0: ["8.2.8"]
```

Has to be modified to: 

```
      - pci_dss_v3.2.1: ["8.1.8"]
      - pci_dss_v4.0: ["8.2.8"]
```

**Comment by jk-olaoluwa** [comment]
Solved - https://github.com/wazuh/wazuh/pull/17412/commits/977bba7f011a53ab05bad2d662ce67e66f7a4b82
