### ISSUE TITLE
Agent sent keepalive failure and reconnection every time!

### ISSUE THREAD

**Issue by Phantasmors** [wazuh/wazuh#16872]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.8 | Wazuh component | Agent | Sources（build on Linux commontest-01 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 13:29:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux） | Linux mjq-k8smjq2gpu-003 5.16.16-1.el7.elrepo.x86_64 #1 SMP PREEMPT Fri Mar 18 09:42:46 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux |

Hello dear wazuh team! 
We are currently experiencing an issue with the deployment of K8S services on the machine, wazuh-agented through get_agent_ip() obtains the agent IP address from wazuh-modules, but each time it takes a long time (about 80 seconds, which can be successfully obtained), resulting in keepalive failure and reconnection every time. I hope you can answer my two questions. Thank you very much. Our wazuh version is 4.3.8.
1. Why is it designed so that the IP address is not directly obtained in the agent?
2. It is for this reason that obtaining the IP takes such a long time?

I discovered the issue of Wazuh constantly reconnecting and added a lot of debugging information. Found that calling here takes 70 seconds. You can see the following pictures:

code:
https://files.slack.com/files-pri/T0A93B42D-F0556Q8S3G9/image.png

log:
https://files.slack.com/files-pri/T0A93B42D-F0556QW7BG9/image.png

**Comment by Phantasmors** [comment]
We have found the specific cause of the problem. The K8S machine has many network interfaces, and each network interface is configured with many network addresses. 

```cpp
nlohmann::json SysInfo::getNetworks() const
{
    nlohmann::json networks;

    std::unique_ptr<ifaddrs, Utils::IfAddressSmartDeleter> interfacesAddress;
    std::map<std::string, std::vector<ifaddrs*>> networkInterfaces;
    Utils::NetworkUnixHelper::getNetworks(interfacesAddress, networkInterfaces);

    for (const auto& interface : networkInterfaces)
    {
        nlohmann::json ifaddr {};

        for (auto addr : interface.second)
        {
            const auto networkInterfacePtr { FactoryNetworkFamilyCreator<OSType::LINUX>::create(std::make_shared<NetworkLinuxInterface>(addr)) };

            if (networkInterfacePtr)
            {
                networkInterfacePtr->buildNetworkData(ifaddr);
            }
        }

        networks["iface"].push_back(ifaddr);
    }

    return networks;
}

```

The above code has been traversed thousands of times, consuming a lot of time. Does the Wazuh team have a good solution to solve these problems.
My initial idea is:
1. Increase IP cache and timed query mechanism
2. Add network interface name filtering code logic
3. Increase the number of nested loops for the same network interface

**Comment by Dwordcito** [comment]
hi @Phantasmors I hope you are well

Thanks for the report, I recently created a new issue, because the team received a lot of comments about some discrepancies around the IP reported.

Based on these comments, the team decided to change this feature definition, to report the source address connected to the manager IP.

Issue:
https://github.com/wazuh/wazuh/issues/16985
