### ISSUE TITLE
Redis Decoder not matching.

### ISSUE THREAD

**Issue by aravindcyberfort** [wazuh/wazuh#16873]
Hi @vikman90 @jctello @pereyra-m @jcruzlp 

Log from my Redis server:

110:M 26 Apr 2023 11:24:33.127 * Background saving started by pid 1882

Log from wazuh server for the same alert: @/var/ossec/logs/archives/archives.json

{"timestamp":"2023-04-26T11:24:34.619+0530","agent":{"id":"004","name":"ubuntu-redis","ip":"192.168.40.59"},"manager":{"name":"wazuh-ML"},"id":"1682488474.123948","full_log":"110:M 26 Apr 2023 11:24:33.127 * Background saving started by pid 1882","decoder":{},"location":"/var/log/redis/redis-server.log"}

Decoder i used: (from github)

<decoder name="redis">
    <prematch>^\d+:\w \d\d \w\w\w \d\d:\d\d:\d\d.\d+ \p </prematch>
</decoder>

<decoder name="redisip">
    <parent>redis</parent>
    <prematch offset="after_parent">^Accepted </prematch>
    <regex offset="after_prematch">^(\S+):(\d+)</regex>
    <order>srcip, dstport</order>
</decoder>

Rules I used: (from github)

<group name="redis,">

    <rule id="81300" level="0">
        <decoded_as>redis</decoded_as>
        <description>Redis messages grouped.</description>
    </rule>

    
    <rule id="81301" level="1">
        <if_sid>81300</if_sid>
        <match>Server started</match>
        <description>Redis: started</description>
        <group></group>
    </rule>

    
    <rule id="81302" level="1">
        <if_sid>81300</if_sid>
        <match>Redis is now ready to exit, bye bye</match>
        <description>Redis: shutdown</description>
        <group></group>
    </rule>

    
    <rule id="81303" level="3">
        <if_sid>81300</if_sid>
        <match>WARNING|can't|not permitted|error|Error|ERROR|Failed</match>
        <description>Redis: Warning / Error</description>
        <group></group>
    </rule>

    
    <rule id="81304" level="3">
        <if_sid>81300</if_sid>
        <match>Accepted </match>
        <regex>\S+:\d+</regex>
        <description>Redis: Client connected</description>
        <group></group>
    </rule>

    
    <rule id="81305" level="3">
        <if_sid>81300</if_sid>
        <match>Client closed connection</match>
        <description>Redis: Client closed connection</description>
        <group></group>
    </rule>

</group>

The issue is these are not matching my logs, help me sort out this, Don't attach the wazuh decoder ruleset webpage link, Just provide me the decoder and rules for my usecase.
Thanks in advance

**Comment by nmkoremblum** [comment]
Hi @aravindcyberfort,

Could you please share with us the complete decoder? Where did you add such a decoder?
Did you test the logs with our [wazuh-logtest tool](https://documentation.wazuh.com/current/user-manual/capabilities/wazuh-logtest/index.html)? What is the output that you get?
