### ISSUE TITLE
Anomalous behavior in the `wazuh-db` descriptors usage

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#16876]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.4.1 - 40406 | wazuh-db | Manager | Packages | CentOS 7 |

Anomalous behavior was found during the Vulnerability Detector Register stress test fix, where it can be seen that in a one-hour test, wazuh-db descriptors grow non-stop: https://github.com/wazuh/wazuh-jenkins/pull/4940#issuecomment-1523414410

![monitor-manager-Test_stress_B3892_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/234591244-c33008fe-3c56-4c47-9265-8aa46bd49eeb.png)

When looking at the test graph of the v4.4.1-rc1 Vulnerability Detector Register test, the following can be seen: https://github.com/wazuh/wazuh/issues/16565

![image](https://user-images.githubusercontent.com/14913942/234592012-d7227c11-f653-4646-a823-dae5c69e633c.png)

The v4.4.1-rc1 general test of Vulnerability Detector shows the following graph: https://github.com/wazuh/wazuh/issues/16578

![image](https://user-images.githubusercontent.com/14913942/234591606-a27d68a7-0061-404d-a6da-2d82e1a57082.png)

A [one-day duration stress test](https://ci.wazuh.info/job/Test_stress/3920/) has been launched to verify this behavior, but a preventive analysis of the behavior of wazuh-db is necessary

This behavior could be related to:

![monitor-manager-Test_stress_B3892_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/234595279-6011eac2-7af1-41e2-bb05-b5d6423fe44d.png)
![monitor-manager-Test_stress_B3892_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/234595309-518a0126-52e2-4ec6-b5c9-42b0fe64de53.png)
![monitor-manager-Test_stress_B3892_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/234595337-5c584a9f-516c-4787-81ea-7cedd499953f.png)

**Comment by rauldpm** [comment]
## Update report

- The one-day stress test does not show abnormal graphs, the descriptors seem to settle when they reach the amount of 93 approximately, @jnasselle comments that this would make sense since the test is based on de-registration and registration of the same agents, which creates multiple databases that are opened and closed, @vikman90 made a contribution indicating that in total there should be a maximum of 64 DDBBs, which was confirmed by analyzing the FDs of the wazuh-db process during the test

![image](https://user-images.githubusercontent.com/14913942/234940839-c341b0ef-1f87-4264-9058-4133a2795978.png)

![image](https://user-images.githubusercontent.com/14913942/234941723-d44f03dc-e707-4695-9cde-eb8c385a726a.png)


- As it is a fix in a stress test, it is necessary for the @wazuh/core team to validate the results and the behavior observed in the graphs obtained

---

## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.4.1                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.4.1-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/3920/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/monitor-manager-Test_stress_B3920_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/plots/Test_stress_B3920_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3920_manager_2023-04-27.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/logs/ossec_Test_stress_B3920_manager_2023-04-27.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B3920_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/data/monitor-manager-Test_stress_B3920_manager-pre-release.csv)
[Test_stress_B3920_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/data/Test_stress_B3920_manager_analysisd_events.csv)
[Test_stress_B3920_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/data/Test_stress_B3920_manager_analysisd_state.csv)
[Test_stress_B3920_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_manager_centos/data/Test_stress_B3920_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/monitor-agent-Test_stress_B3920_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/Test_stress_B3920_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/Test_stress_B3920_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/Test_stress_B3920_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/plots/Test_stress_B3920_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3920_centos_2023-04-27.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/logs/ossec_Test_stress_B3920_centos_2023-04-27.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B3920_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/data/monitor-agent-Test_stress_B3920_centos-pre-release.csv)
[Test_stress_B3920_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_centos/data/Test_stress_B3920_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/monitor-agent-Test_stress_B3920_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/Test_stress_B3920_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/Test_stress_B3920_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/Test_stress_B3920_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/plots/Test_stress_B3920_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3920_ubuntu_2023-04-27.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/logs/ossec_Test_stress_B3920_ubuntu_2023-04-27.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B3920_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/data/monitor-agent-Test_stress_B3920_ubuntu-pre-release.csv)
[Test_stress_B3920_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_ubuntu/data/Test_stress_B3920_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/monitor-winagent-Test_stress_B3920_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/Test_stress_B3920_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/Test_stress_B3920_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/Test_stress_B3920_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/plots/Test_stress_B3920_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B3920_windows_2023-04-27.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/logs/ossec_Test_stress_B3920_windows_2023-04-27.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B3920_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/data/monitor-winagent-Test_stress_B3920_windows-pre-release.csv)
[Test_stress_B3920_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.1/B3920-60m/B3920_agent_windows/data/Test_stress_B3920_windows_agentd_state.csv)



    </details>

</details>

**Comment by vikman90** [comment]
@rauldpm Thanks for launching the new test. The last chart stabilizes a bit after the start of the test, showing itself flat and practically straight.

Those ~90 descriptors should correspond to the 64 databases plus libraries and sockets.

As we were fearing a possible descriptor leak, the new graph allows us to definitively rule it out.

Best!

**Comment by rauldpm** [comment]
Issue closed as completed in https://github.com/wazuh/wazuh-jenkins/pull/4940 (GitHub marked the PR as closed but it was merged)
