### ISSUE TITLE
wazuh-logtest able to decode the cloudwatch mariadb log but there is no decoder in archive.json file for the same log

### ISSUE THREAD

**Issue by karmendra** [wazuh/wazuh#16874]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.1-40406 | Wazuh-Manager | Manager | Packages | Ubuntu 20.04 |

I am trying to push rds mysql logs captured in cloudwatch using the maraidb-audit-log plugin to my wazuh, 
I added following configurations to my ossec.conf file and restarted, but I was not seeing the logs in Wazuh Dashboard (Kibana)

```
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>2m</interval>
    <run_on_start>yes</run_on_start>

    <service type="cloudwatchlogs">
      <aws_profile>default</aws_profile>
      <aws_log_groups>/aws/rds/instance/my-oltp-rds/audit</aws_log_groups>
      <regions>ap-south-1</regions>
      <only_logs_after>2023-APR-25</only_logs_after>
  </service>

  </wodle>
```

I turned on the debugging there were on errors/warning reported in fetching these logs from cloudwatch

Then checked in `archive.json` after enabling logall_json, I see following entry, it suggest the log is received but no decoder picked this log, this is the reason this log in not present in wazuh kibana in dashboard. What is the issue? and how to fix this?

```
{
    "timestamp": "2023-04-25T20:34:32.597+0530",
    "agent": {
        "id": "000",
        "name": "REW-Wazuh"
    },
    "manager": {
        "name": "REW-Wazuh"
    },
    "id": "1682435072.11369736",
    "full_log": "DEBUG: The message is \"20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,\"",
    "decoder": {},
    "location": "aws-s3"
}
```

Further when I run the wazuh-logtest for the same log line it does pick mariadb-syslog decoder and even shows the rule alert trigger.

```
20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,

**Phase 1: Completed pre-decoding.
        full event: '20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,'

**Phase 2: Completed decoding.
        name: 'mariadb-syslog'
        mariadb.action: 'QUERY'
        mariadb.host: '10.1.12.11'
        mariadb.ip: '10-30-0-100'
        mariadb.resource: 'REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,'
        mariadb.username: 'karmendra'

**Phase 3: Completed filtering (rules).
        id: '88100'
        level: '0'
        description: 'MariaDB group messages.'
        groups: '['mariadb']'
        firedtimes: '1'
        mail: 'False'
```
What I missing? Please help.

Thanks

**Comment by karmendra** [comment]
One thing I observed is full log is having this additional text (`DEBUG: The message is `) prefixed to the actual log line. 

Full_log:
```
"DEBUG: The message is \"20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,\""
```

Actual log line:
```
"20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,"
```

Does this have something to do with this issue?

**Comment by nmkoremblum** [comment]
Hi @karmendra,

Just as you have noticed, there is no decoder to decode the log that starts with the prefix `"DEBUG: The message is "`, this breaks the decoding of the `mariadb` event. Do you know if such a prefix can be removed from the source?

**Comment by karmendra** [comment]
From Where is this Additional Prefix added to my log line, is it added by wazuh?

**Comment by nmkoremblum** [comment]
What do you mean that there is no prefix in the `archives.log`? Do you mean that in the `archives.json` it does have the prefix but in the `archives.log` not? What version of the manager are you using? How did you install it?

**Comment by karmendra** [comment]
I used Wazuh Installation assistant and instructions on this https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html, this installation I did on an freshly installed Ubuntu 20.04.6 OS on EC2.

Logs as see in cloudwatch
![image](https://user-images.githubusercontent.com/11293052/234910509-c018c8be-119a-4115-901d-cb27509707ea.png)


Logs as seen in archive.log, here we can see the same log is present twice, once with and once without DEBUG prefix
![image](https://user-images.githubusercontent.com/11293052/234910259-32217e04-83cc-4298-97b7-be6ab2d5151f.png)

Logs as seen in archive.json, But this time the decoder is picked correctly, even with the DEBUG prefix in full_log, also note that previous entry is present but without the DEBUG prefix
![image](https://user-images.githubusercontent.com/11293052/234911060-25be9a47-d6b8-439c-b9f7-29d66619520f.png)

But unlike before decoder is picked this time
```
{
    "timestamp": "2023-04-27T20:36:23.120+0530",
    "rule": {
        "level": 5,
        "description": "RDS Log ",
        "id": "100021",
        "firedtimes": 1394,
        "mail": false,
        "groups": ["mariadb_audit_log"]
    },
    "agent": {
        "id": "000",
        "name": "REW-Wazuh"
    },
    "manager": {
        "name": "REW-Wazuh"
    },
    "id": "1682607983.12991094",
    "full_log": "DEBUG: The message is \"20230427 15:05:20,ip-172-30-2-126,karmendra,10.0.11.160,188624,1242598,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select id,cycle,counter from failover_test',0,,\"",
    "decoder": {
        "name": "mariadb_audit_log"
    },
    "location": "aws-s3"
}
```

Not sure how this time it is able to pick the decoder correctly.

But even now I am unable to see the log in Kibana
![image](https://user-images.githubusercontent.com/11293052/234913137-247cb2bc-9475-42c6-a265-53bf269dab96.png)

Not sure what am I missing, Please guide me here

One thing, I have also turned on `wazuh_modules.debug=2` in `local_internal_options.conf` while taking above screenshots. wondering if that produced the extra debug lines in archive logs

**Comment by karmendra** [comment]
I used Wazuh Installation assistant and instructions on this https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html, this installation I did on an freshly installed Ubuntu 20.04.6 OS on EC2.

In `etc/local_internal_options.conf` i had `wazuh_modules.debug=2`, by any chance is this causing the prefix being added to the Log. after removing this line I am not seeing the debug prefix.

As of now I have this debugging turned off and I am not seeing that prefix anymore.

**Comment by karmendra** [comment]
Now I see in archive.json decode is picked correctly, but then why am i not seeing these logs in Kibana?

**Comment by nmkoremblum** [comment]
Hi @karmendra, nice catch, I think it shouldn't work like that, I will report the problem to the team (the one about the prefix).

About the event not being displayed on the dashboard, it is because its alert level is not high enough to be displayed. As you showed us before, when you test the log you get the following:
```
**Phase 3: Completed filtering (rules).
        id: '88100'
        level: '0'
        description: 'MariaDB group messages.'
        groups: '['mariadb']'
        firedtimes: '1'
        mail: 'False'
```
Here the level is '0'. By default, an event should have a level higher than or equal to '3' to be considered an alert, and thus be displayed on the dashboard. You can either modify the triggering level on the `ossec.conf` file, under the `log_alert_level` label, but this may cause a lot of events to be considered alerts when they should not, that is why this way is not recommended, or you can create a custom rule to risen the alerting level of certain events. To do so, please take a look at the following links:
- https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/
- https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

**Comment by karmendra** [comment]
@nmkoremblum Thanks, Will try this tomorrow morning, I am hopeful it will work after I raise the alert level.

**Comment by karmendra** [comment]
I added following to local_rules.xml to elevate the alert levels. I hope this is what you meant

![image](https://user-images.githubusercontent.com/11293052/234992517-5daf34ec-efd4-419e-b0f2-352e9ee44e41.png)

**Comment by nmkoremblum** [comment]
I've tested it and it does work right. It should work as well in your setup.

```
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.4.1
Type one log per line

20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,

**Phase 1: Completed pre-decoding.
	full event: '20230425 15:03:08,ip-10-30-0-100,karmendra,10.1.12.11,15514,681264,QUERY,REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,'

**Phase 2: Completed decoding.
	name: 'mariadb-syslog'
	mariadb.action: 'QUERY'
	mariadb.host: '10.1.12.11'
	mariadb.ip: '10-30-0-100'
	mariadb.resource: 'REWOLTPDB,'/* ApplicationName=DataGrip 2022.3.2 */ select * from pg_transactions_thin',0,,'
	mariadb.username: 'karmendra'

**Phase 3: Completed filtering (rules).
	id: '88100'
	level: '5'
	description: 'MariaDB group messages.'
	groups: '['mariadb']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.
```

**Comment by karmendra** [comment]
Yes it does work, fine, Thanks for you time and help.

I think I found another issue with timestamp timezone display in Management > Log, I will open another issue for that with more details.

Thanks Again.

**Comment by Meraz78** [comment]
hey if you don't mind can you share your decoder as well

**Comment by karmendra** [comment]
I had not written any custom decoder it uses the inbuilt `mariadb-syslog` decoder and rule.
