### ISSUE TITLE
Wildcards in syscheck/ignore are not being honoured [REGRESSION?]

### ISSUE THREAD

**Issue by rseabra** [wazuh/wazuh#16887]
|Wazuh version|Component|Install type|Install method|Platform|
|4.3.10|syscheck|agent|rpm, Wazuh|RHEL8|

Hi, wildcards in sregex ignore rules are not being honoured, even though they're registered as being OK.

This entry is validated (debug shows it's OK and added to the list of ignore rules) and honoured (Ignoreing file ... due to sregex):
    <ignore type="sregex">/etc/mtab</ignore>

This entry is validated **but not honoured** even though it is fully compliant with the sregex type:
    <ignore type="sregex">/var/account/pacct*</ignore>

As can be seen in the ossec.log (some private info obscured) the rules are validated:
```
(...)
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2408 at process_option_regex(): DEBUG: Found ignore regex node /etc/mtab
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2415 at process_option_regex(): DEBUG: Found ignore regex node /etc/mtab OK?
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2416 at process_option_regex(): DEBUG: Found ignore regex size 0
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2408 at process_option_regex(): DEBUG: Found ignore regex node /var/account/pacct*
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2415 at process_option_regex(): DEBUG: Found ignore regex node /var/account/pacct* OK?
2023/04/27 12:29:45 wazuh-syscheckd[197991] syscheck-config.c:2416 at process_option_regex(): DEBUG: Found ignore regex size 1
(...)
```

And mtab indeed is honoured:
```
2023/04/27 12:29:45 wazuh-syscheckd[197991] main.c:232 at main(): INFO: (6207): Ignore 'file' sregex '/etc/mtab'
2023/04/27 12:36:12 wazuh-syscheckd[197991] create_db.c:1206 at fim_check_ignore(): DEBUG: (6205): Ignoring 'file' '/var/lib/nfs/rmtab' due to sregex '/var/lib'
```

But pacct not:
```
2023/04/27 12:29:45 wazuh-syscheckd[197991] main.c:232 at main(): INFO: (6207): Ignore 'file' sregex '/var/account/pacct*'
```

fim.db (and also the db file on the server) report the files that should have been ignored:
```
sqlite> select path,mode,scanned,options from file_entry where path like '/etc/mtab%';
sqlite> select path,mode,scanned,options from file_entry where path like '/var/account%';
/var/account/pacct-20230328.gz|0|1|131391
/var/account/pacct-20230329.gz|0|1|131391
/var/account/pacct-20230330.gz|0|1|131391
/var/account/pacct-20230331.gz|0|1|131391
/var/account/pacct-20230401.gz|0|1|131391
/var/account/pacct-20230402.gz|0|1|131391
/var/account/pacct-20230403.gz|0|1|131391
/var/account/pacct-20230404.gz|0|1|131391
/var/account/pacct-20230405.gz|0|1|131391
/var/account/pacct-20230406.gz|0|1|131391
/var/account/pacct-20230407.gz|0|1|131391
/var/account/pacct-20230408.gz|0|1|131391
/var/account/pacct-20230409.gz|0|1|131391
/var/account/pacct-20230410.gz|0|1|131391
/var/account/pacct-20230411.gz|0|1|131391
/var/account/pacct-20230412.gz|0|1|131391
/var/account/pacct-20230413.gz|0|1|131391
/var/account/pacct-20230414.gz|0|1|131391
/var/account/pacct-20230415.gz|0|1|131391
/var/account/pacct-20230416.gz|0|1|131391
/var/account/pacct-20230417.gz|0|1|131391
/var/account/pacct-20230418.gz|0|1|131391
/var/account/pacct-20230419.gz|0|1|131391
/var/account/pacct-20230420.gz|0|1|131391
/var/account/pacct-20230421.gz|0|1|131391
/var/account/pacct-20230422.gz|0|1|131391
/var/account/pacct-20230423.gz|0|1|131391
/var/account/pacct-20230424.gz|0|1|131391
/var/account/pacct-20230425.gz|0|1|131391
/var/account/pacct-20230426.gz|0|1|131391
/var/account/pacct-20230427|0|1|131391
/var/account/pacct|0|1|131391
sqlite>
```

This issue may (or may not) be related to https://github.com/wazuh/wazuh/issues/2723 which was fixed in https://github.com/wazuh/wazuh/pull/8461 but maybe broken since its fix in PR https://github.com/wazuh/wazuh/pull/8461

I hope this issue report is helpful in finding the problem, we went through a little embarrassment since this was noticed by the wrong people. :)

**Comment by rseabra** [comment]
From etc/shared/agent.conf:
```
<agent_config>
  <syscheck>
    <frequency>79200</frequency>
    <auto_ignore>no</auto_ignore>
    <disabled>no</disabled>

    <scan_on_start>no</scan_on_start>

<!-- Check All paths -->
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/bin</directories>
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/sbin</directories>
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/usr</directories>
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/lib</directories>
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/etc</directories>
    <directories realtime="no"   check_all="yes" check_md5sum="no" check_sha1sum="no">/var</directories>

<!-- Ignored paths -->
    <ignore type="sregex">/etc/mtab</ignore>
    <ignore type="sregex">/var/account/pacct*</ignore>
(...)
```

Full log and agent.conf attached.
[ossec.log-bugreport.gz](https://github.com/wazuh/wazuh/files/11343637/ossec.log-bugreport.gz)
[agent.conf.txt](https://github.com/wazuh/wazuh/files/11343638/agent.conf.txt)

**Comment by rseabra** [comment]
Hi, ok, I understand your explanation, although it wouldn't help us much in the end as the exclusions are a little bit more complex than that.

Since the documentation is not very explicit, can you please confirm whether it would be valid to specify type="regex" or type="pcre2" ?

**Comment by vikman90** [comment]
Hi @rseabra, the valid values for the `<ignore>`'s `type` attribute are:

|Value|Behavior|
|---|---|
|(none)|Ignore paths that contain the argument (substring)|
|`sregex`|Ignore paths that match the _sregex_ (`^ $ \| !`)|

You're right, the documentation is not clear, as well as the set of available options.

If you find it interesting that FIM supports full-regexes (like rules and decoders) or PCRE2, feel free to open an issue as a feature request, and we will gladly add it to the roadmap.

Best.
