### ISSUE TITLE
Compressed files, can't see the original file name

### ISSUE THREAD

**Issue by Aryeh-Leskin** [wazuh/wazuh#16884]
Hi,

Is there a way to see the original file name when a file is compressed (zipped)? -
In testing Wazuh (App version: 4.4.1) and a windows 10 agent, I compressed a few files using powershell's compress-archive function, I don't see the original name of the file in the Wazuh dashboard or that the original file had any changes, only that the new compressed file was added to the system and then modified - in the modified section I don't see anything about what was modified and there is no syscheck.diff section there

Thank You!
![image](https://user-images.githubusercontent.com/73400014/234819586-0bb68cfe-f281-480d-9df0-3c5325cb495e.png)
![image](https://user-images.githubusercontent.com/73400014/234820002-e406f0fb-cb3f-4e12-aaa6-6fd2d16b7069.png)
![image](https://user-images.githubusercontent.com/73400014/234821467-480b9473-8d8a-43df-bfa9-b1a814fcd97f.png)

**Comment by al10110** [comment]
Yes, I'm using the FIM section, but I'm getting inconsistent results as some file that I zip, do show up with the syscheck.diff filter and the same command with the same main path (i.e C:\Users\User\Desktop) will sometimes not contain the syscheck.diff option
![image](https://user-images.githubusercontent.com/73400014/237048833-85ef2801-2ba3-4694-893d-a80bae119d45.png)

**Comment by sdvendramini** [comment]
Hi! Could you send the configuration related to syscheck and especially the ```directories``` and ```diff``` section? It may also be useful to know the characteristics of the files.

**Comment by al10110** [comment]
[ossec.conf.txt](https://github.com/wazuh/wazuh/files/11440134/ossec.conf.txt)

This is the same configuration that I used in both cases - The only difference is the username and the name of the files that are zipped, I either get both the "Integrity checksum changed" filter and the syscheck.diff filter or I don't get anything at all, 
As you can see in this picture I don't get the events in this test, 
![image](https://github.com/wazuh/wazuh/assets/73400014/871261a5-dca3-487a-85ee-825bbc79bb8a)

But I do in this test - using the same command with the same config just on another file and another user:
![image](https://github.com/wazuh/wazuh/assets/73400014/2b198a69-47da-44ff-bd76-57a7c9da38e5)
![image](https://github.com/wazuh/wazuh/assets/73400014/282e5de5-7ba3-4389-9b91-96ad62a45e8e)

**Comment by sdvendramini** [comment]
Hi! I see that the ```diff``` section is not configured in your ossec.conf file. So the default values are currently configured. Can you check that the limits inside this setting are OK? https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#diff 
Maybe the file is too large or the type of the file is not the correct. The ```report_changes``` setting only support text files at this moments.
