### ISSUE TITLE
Allow to search in the `q` with the same value that is returned in the API responses when including the `+` character

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#16899]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Description

Some data related to date values are returned in the API responses as:
```
YYYY-MM-DDTHH:mm:ss+00:00
```

According to the regular expression for the token value that was commented on here: https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1442091645, the `+` character is not supported in the `q` query. A similar regular expression was implemented in a new search bar that uses it to decompose the query and validate the input, so the `+` character is not valid, and an error is displayed: https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1525813726

By another hand, I tried to do an API request using the `API Console` from the Wazuh plugin or some API rest client with a date value expecting the API throws an error should to the format, but this didn't happen. Moreover, the API logs don't display the `+` character, and this seems to be replaced by a whitespace, that was used in the query.

For example:
Get data of the agents:
![image](https://user-images.githubusercontent.com/34042064/235079091-4e29677a-6780-49b5-b6e7-aa3da9617718.png)

If I want to use the `q` query parameter of the `GET /agents` endpoint whose query is `q=dateAdd=2023-04-27T11:05:57+00:00` (this date is the same `dateAdd` property of the agent 002, see the previous screenshot), the API response doesn't contain the agent I would expect it.

![image](https://user-images.githubusercontent.com/34042064/235079463-b44d3ee9-493e-497c-a6e0-a16187cb6188.png)

The API log to the request is the following:

```
2023/04/28 07:10:38 INFO: wazuh-wui 192.168.56.1 "GET /agents" with parameters {"q": "dateAdd=2023-04-27T11:05:57 00:00"} and body {} done in 0.021s: 200
```

The character `+` seems to be replaced by a whitespace.

Problems:
- I would expect the API would throw an error because the `+` is not supported according to the mentioned regular expression https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1442091645
- I didn't know why the `+` character is replaced by a whitespace. I don't know what is causing this.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
Hello @Desvelao. 

The `+` character has a special meaning in the *query* segment of a URL, it means whitespace: ` `. 

> Here's the list of reserved characters https://en.wikipedia.org/wiki/URL_encoding, please note that they are reserved _in a certain context_ and not always.

To use the `+` sign in the query parameter, you need to encode it to `%2b`.

Try doing `GET /agents?dateAdd=2023-04-27T11:05:57%2b00:00` instead and it will work.

It's not an issue from the API since it already receives the value with the empty space.

**Comment by Desvelao** [comment]
> 

We should review if the encoding should be done by our side. Thank you so much for noting us. I opened an issue in the plugin repository https://github.com/wazuh/wazuh-kibana-app/issues/5786.

For another hand, I tried to query using your suggestion and it seems that doesn't return the expected value.

```console
$ TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   404  100   404    0     0    880      0 --:--:-- --:--:-- --:--:--   880
$ curl -k -X GET "https://localhost:55000/agents?select=dateAdd&pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "id": "000",
            "dateAdd": "2023-08-11T09:43:00+00:00"
         },
         {
            "id": "001",
            "dateAdd": "2023-08-11T13:41:56+00:00"
         }
      ],
      "total_affected_items": 2,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected agents information was returned",
   "error": 0
}
$  curl -k -X GET "https://localhost:55000/agents?select=dateAdd&pretty=true&q=dateAdd=2023-08-11T09:43:00%2b00:00 -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [],
      "total_affected_items": 0,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "No agent information was returned",
   "error": 0
}toni@manjaro-talos:~/wazuh/src/wazuh-kibana-app/docker/osd-dev (4.7.0)$ 
```

API logs:
```
2023/08/16 07:56:19 INFO: wazuh-wui 172.24.0.1 "GET /agents" with parameters {"select": "dateAdd", "pretty": "true", "q": "dateAdd=2023-08-11T09:43:00+00:00"} and body {} done in 0.028s: 200
```

I encoded the `+` to `%2b` and would expect the agent with `id` `000` to be returned, but this is not the case.

Tested with a Wazuh manager 4.6.0 (development).

Could you check this or say where is my error?

**Comment by GGP1** [comment]
Hello @Desvelao, this is expected behaviour since all agents date queries have `id != 000` appended to them as it can be seen here

https://github.com/wazuh/wazuh/blob/3738e16e07e148ee4cd5dd9203a539569afa4f33/framework/wazuh/core/agent.py#L95-L98

I'm not sure what's the rationale behind this decision but it's probably because the agent 000 is not taken into consideration in many places.

**Comment by GGP1** [comment]
Hello @Desvelao, this is expected behaviour since all agents date queries have `id != 0` appended to them as it can be seen here

https://github.com/wazuh/wazuh/blob/3738e16e07e148ee4cd5dd9203a539569afa4f33/framework/wazuh/core/agent.py#L95-L98

I'm not sure what's the rationale behind this decision but it's probably because the agent 000 is not taken into consideration in many places.

**Comment by Desvelao** [comment]
> Hello @Desvelao, this is expected behaviour since all agents date queries have `id != 0` appended to them as it can be seen here
> 
> https://github.com/wazuh/wazuh/blob/3738e16e07e148ee4cd5dd9203a539569afa4f33/framework/wazuh/core/agent.py#L95-L98
> 
> I'm not sure what's the rationale behind this decision but it's probably because the agent 000 is not taken into consideration in many places.

Thank you for the information.

I checked this with a different agent (not `000`) and it is working:

```console
curl -k -X GET "https://localhost:55000/agents?select=id,dateAdd&&q=dateAdd=2023-08-17T07:19:45%2b00:00" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"dateAdd": "2023-08-17T07:19:45+00:00", "id": "001"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
```

**Comment by fdalmaup** [comment]
# Review

The reasons for the behavior found were correctly justified by describing the conversion of the mentioned character and how it should be carried out at the time of making the request so that the API can process it.
