### ISSUE TITLE
Agent-side regex filtering of syslog format log files

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#169]
On my Windows and Linux Wazuh agents, I'd really like to be able to filter out syslog lines that match certain regex patterns.  At present, the only agent-side log filtering I am aware of is for the Windows eventchannel log format with XPath queries.  For syslog format files on Linux or Windows, I don't know of any way to restrict what gets passed along to the Wazuh manager.

Sometimes specific servers are recurrently prone to produce massive streams of a very specific log line pattern that is not worth sending along to the manager at all.  It would really be nice to be able to tune out such items before taxing the network and the Wazuh manager with it.  

Such a feature would nicely complement the new leaky bucket queuing introduced in the Wazuh 2.1.0 agent.  Once I start seeing recurrent leaky bucket flooding alerts from a given agent, I'm going to want to see if there is a specific pattern that the over-logging follows such that I could prevent such log lines from ever being transmitted from the agent at all.  The leaky bucket will protect the network and the manager by limiting the events per second rate for a given over-logging agent, but while a potentially easily profiled high-eps event is creating a flood that spills out of the leaky bucket, many of the other desirable log events from that same agent are at high risk of being sacrificed  while enforcing the eps limit.

Here is how I imagine the filtering might be configured:

```
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
    <exclude_regex>program_x\.*id:(2771|3342)</exclude_regex>
    <exclude_regex>program_y\.*blablabla</exclude_regex>
  </localfile>

```
I got this idea from the way Filebeat lets you exclude certain lines from a log file before passing them along to Logstash/Elasticsearch:

https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#exclude-lines

Just an idea that I think would make a great product even greater,
Kevin Branch

**Comment by snaow** [comment]
Hi @branchnetconsulting, 

Looks like a great idea! In fact, we need this kind of exclusion engine in the agents to use it for other internal purposes (debug level 2 enable + logcollector + collecting ossec.json log file).

Let's label this issue as "enhancement" and we will add it to our roadmap.

Thanks Kevin,
Pedro.

**Comment by branchnetconsulting** [comment]
I sure would love to see this happen at some point.  Though in many cases we can use an rsyslog rule on a Linux agent to exclude certain high-noise/low-signal events from being written to the file system at all, in other cases we really want to retain such events on the local agent.  Also certain Linux log files are written to directly by an application rather than via the syslog facility, which means rsyslog cannot filter its content.  Agent-side event filtering for both Windows and Linux/POSIX agent-types would really make things more complete.  

Thanks for your consideration :)
Kevin

**Comment by Nikkhah** [comment]
> On my Windows and Linux Wazuh agents, I'd really like to be able to filter out syslog lines that match certain regex patterns. At present, the only agent-side log filtering I am aware of is for the Windows eventchannel log format with XPath queries. For syslog format files on Linux or Windows, I don't know of any way to restrict what gets passed along to the Wazuh manager.
> 
> Sometimes specific servers are recurrently prone to produce massive streams of a very specific log line pattern that is not worth sending along to the manager at all. It would really be nice to be able to tune out such items before taxing the network and the Wazuh manager with it.
> 
> Such a feature would nicely complement the new leaky bucket queuing introduced in the Wazuh 2.1.0 agent. Once I start seeing recurrent leaky bucket flooding alerts from a given agent, I'm going to want to see if there is a specific pattern that the over-logging follows such that I could prevent such log lines from ever being transmitted from the agent at all. The leaky bucket will protect the network and the manager by limiting the events per second rate for a given over-logging agent, but while a potentially easily profiled high-eps event is creating a flood that spills out of the leaky bucket, many of the other desirable log events from that same agent are at high risk of being sacrificed while enforcing the eps limit.
> 
> Here is how I imagine the filtering might be configured:
> 
> ```
>   <localfile>
>     <log_format>syslog</log_format>
>     <location>/var/log/messages</location>
>     <exclude_regex>program_x\.*id:(2771|3342)</exclude_regex>
>     <exclude_regex>program_y\.*blablabla</exclude_regex>
>   </localfile>
> ```
> 
> I got this idea from the way Filebeat lets you exclude certain lines from a log file before passing them along to Logstash/Elasticsearch:
> 
> https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#exclude-lines
> 
> Just an idea that I think would make a great product even greater,
> Kevin Branch

Hi
Can I use this feature in wazuh manager? in order to filter out specific logs in wazuh server.

**Comment by weslambert** [comment]
Would really love to see this as an option for `json` formatted logs as well.  I think it's really important to have the ability to filter logs at the source to avoid wasting network bandwidth and other resources to transport data you are going to drop/ignore eventually anyway, and from a raw log perspective, avoid duplicating all of the data from the original log.

**Comment by niek1992** [comment]
I believe this is already possible (albeit not with `sregex`). One could simply create a `<query>` that excludes certain fields of an eventlog entry. I use it to filter out noisy events. Seeing this is an issue dating back to August 2017, i'd assume everyone has already found an solution to their problem. Thought maybe share this because i found this issue when doing some Google-Fu to get a issue of mine fixed.

**Comment by branchnetconsulting** [comment]
Sadly, <query> only works for Windows EventChannel events, not syslog or
json log formats.

Kevin

**Comment by niek1992** [comment]
Hey, my comment is gone. But you still replied to it. Yeah Query only works for Windows Events sadly, but you mentioned Windows so assumed Event related stuff. But you also have filebased logs you'd like to monitor in Windows?

**Comment by branchnetconsulting** [comment]
Yes, I pull file-based logs from Windows agents though not as often as from
Linux agents, and for any OS it would help to be able to have the Wazuh
agent self filter what it sends from specific file-based logs files to the
manager, with a combination of one or both of a regex-based <include> and
<exclude> line.  That would be a very reasonable feature for any log
shipper and is supported for example by Filebeat with its include_lines and
exclude_lines criteria.

Kevin

**Comment by vikman90** [comment]
Hi @branchnetconsulting and everyone.

We've already implemented this request:

- https://github.com/wazuh/wazuh/issues/5628
- https://github.com/wazuh/wazuh/pull/14782

We will release this feature soon. I hope you find it useful.

Best.
