### ISSUE TITLE
The date fields of `q` query parameter don't support some values

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#16902]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Description

In the new search bar we are developing, supports a search mode whose input will be searched in a list of fields.

In the `Agents` section of the Wazuh plugin, there is a table that contains the same properties of the date type. The user can enable or disable the visibility of the columns table.

In the case the user has enabled a column that whose type is a date, we expect if the user uses the search bar to do a search in each visible column of the table, the search term is applied to each visible column, including the date field. This causes an API error ![image](https://user-images.githubusercontent.com/34042064/234258609-cb788614-287b-4843-b69c-e4e8a56ee717.png).

The API query could be something like as:
```
GET /agents?q=id!=000;(name~wazuh,dateAdd~wazuh)
```

Related problem: https://github.com/wazuh/wazuh-kibana-app/issues/4312#issuecomment-1521702778.

How are we supposed to allow the user can execute this type of search?

We found this problem with the date values, but maybe there are more value types that could be causing the same problem. Do you know about more cases?

I am not sure if this is a problem with API, but this causes the search doesn't work as the Wazuh plugin would expect. Maybe we could discuss a better solution.

Some solution to this problem that was commented on by @asteriscos is removing the date fields in the search query, but I think this causes a loss of capabilities because the user could not use this search mode to search in the date fields.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
This is a bit more difficult than it looks, we should have further discussions.

**Comment by Desvelao** [comment]
# Meeting

We got a meeting today to talk about this topic.

According to @davidjiglesias, the date fields are stored in the database as timestamp in seconds, so it makes it difficult to search any string. @davidjiglesias commented the API could remove the type checks, this would solve the error https://user-images.githubusercontent.com/34042064/234258609-cb788614-287b-4843-b69c-e4e8a56ee717.png, but the search could not match due to the date value is stored as timestamp.

For another hand and thinking as the user could expect to work the search, he could type any string that is displayed in the date column and would expect that result would be in the response. The most of dates are formatted using the date format of the platform, which means, the value returned by the API response could be different from the one displayed in the UI.
![image](https://github.com/wazuh/wazuh/assets/34042064/516e79b1-bf14-4d95-b1b2-3fe018dd0297)

# Decision

We will need to do the following tasks:
- plugin:
  - when the user uses a date field in the search bar, this should validate the value to be one of the expected.
  - if the UI element contains a date field, this should not take into account when executing a search term mode.
  - inform the users if a visible field is not included in the search term mode.

**Comment by davidjiglesias** [comment]
To be done in https://github.com/wazuh/wazuh-kibana-app/issues/4312.
