### ISSUE TITLE
Bad API request through `q` query parameter in `GET /agents`

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#16909]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Description

I found a bad request error when trying to do a complex query through the `q` query parameter in the `GET /agents` endpoint.

Request:
```
GET /agents?q=id!=000;(status=active;(group=default2,group=default3))
```

API log:
```
2023/04/28 11:35:10 INFO: wazuh 192.168.56.1 "GET /agents" with parameters {"q": "id!=000;(status=active;(group=default2,group=default3))"} and body {} done in 0.043s: 40
```

Response:
```json
{
  "title": "Bad Request",
  "detail": "Error in wazuhdb request: Cannot execute Global database query; incomplete input",
  "remediation": "Make sure the request is correct",
  "dapi_errors": {
    "node01": {
      "error": "Error in wazuhdb request: Cannot execute Global database query; incomplete input"
    }
  },
  "error": 2003
}
```

I would expect this complex query to work:
- Agent is not a manager (`id!=000`)
- Agent status is `active` and agent group is one of `default2` or `default3`

This was seen testing the new search bar: https://github.com/wazuh/wazuh-kibana-app/issues/4312
![image](https://user-images.githubusercontent.com/34042064/235138020-bde29322-1dd3-4d4e-95ba-27c82ed006aa.png)

I guess this problem could be related to the parse and transformation of `q` language to database language.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [ ] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The issue is related to the first parentheses that wrap the `status` and `group` conditions. 

If we replace

```
id!=000;(status=active;(group=default2,group=default3))
```

with

```
id!=000;status=active;(group=default2,group=default3)
```

it works as expected.

@Desvelao I think the conditions are being parsed incorrectly from the search bar rather than being an API issue.

**Comment by Desvelao** [comment]
Hi @GGP1 , thank you so much for your response.

This query:
```
id!=000;(status=active;(group=default2,group=default3))
```

is caused in the table related to agents that should not display the managers.

For this case, the search bar has defined an implicit query (`id` should not be `000` that excludes to the managers ).

```
id!=000;
```

For another hand, the query defined by the user is wrapped by parenthesis:
Example of user input in the search bar:
```
status=active and ( group=default2 or group=default3 )
```

This is translated to the `q` syntax as:
```
status=active;(group=default2,group=default3)
```

Then, the user query is wrapped by parenthesis:
```
(status=active;(group=default2,group=default3))
```

This approach avoids some problems related to queries that could not return the expected values. The managers should not be returned.

<details>
  <summary>Example forcing no expected results if the API request doesn't use the parenthesis to wrap the user query</summary>
  

  User input:
  ```
  status=active or id=000
  ```
  If the query doesn't wrap the user input between parenthesis, then the query could be translated to:  
  ```
  id!=000;status=active,id=000
  ```

  API request:
  ```console
$ TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
$ curl -k -X GET "https://localhost:55000/agents?q=id!=000;status=active,id=000&select=id" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"id": "000"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
  ```
  > Note the manager (agent with id `000`) is returned, and we need to avoid this can be returned. This is the reason we use the parenthesis and we would expect this works.
</details>

I don't see the problem with the query and I would expect this would work.

Should the mentioned query work?
```
id!=000;(status=active;(group=default2,group=default3))
```

**Comment by GGP1** [comment]
@Desvelao

The query that is being created by the search bar is not valid, our regular expression expects just a single parenthesis

![regex](https://github.com/wazuh/wazuh/assets/51374959/3f92b78f-8d48-437e-8505-e7f6327919e6)

![query_regex](https://github.com/wazuh/wazuh/assets/51374959/6c41d6f0-d8c3-4dd2-b64a-1070288831a5)

Furthermore, the parenthesis are not used to group any conditions but to indicate that the condition between them is of type `OR`.

So, assuming the query was interpreted by the regular expression anyway, if we were to use 

```
(status=active;(group=default2,group=default3))
```

The query would look for values that have either the status `active` or belong to the group `default2` or `default3`, which would be the same as doing

```
(status=active,group=default2,group=default3)
```

**Comment by Desvelao** [comment]
Hi @GGP1,

Thank you for the information.

Reviewing the [documentation](https://documentation.wazuh.com/4.5/user-manual/api/queries.html) for the query syntax of API, the following things are not specified:
> The query that is being created by the search bar is not valid, our regular expression expects just a single parenthesis
> Furthermore, the parenthesis are not used to group any conditions but to indicate that the condition between them is of type OR.

If this is the behavior, I think these clarifications should be added to the documentation.

In the current implementation of the language in the search bar, the user can use any number of parenthesis pairs and can use the `and` (`;`)  operator within parenthesis pairs.

These behaviors were not known when the search bar was designed.

**Comment by Desvelao** [comment]
Regarding this comment: https://github.com/wazuh/wazuh/issues/16909#issuecomment-1680129865

Related to the table displayed with the agents, how are supposed to do the query ensuring the agent with ID `000` will never return? In the comment, I can do a query with unexpected results.

For another hand, I was testing this affirmation:
> Furthermore, the parenthesis are not used to group any conditions but to indicate that the condition between them is of type OR.

And it seems if using the `and` ( `;`) operator instead of `or` (`,`) the results are different, and it returns the expected results in my tests:

```console
$ TOKEN=$(curl -u wazuh-wui:TOKEN=$(curl -u wazuh-wui:wazuh-wui -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
$ curl -k -X GET "https://localhost:55000/agents?select=id,status" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"status": "active", "id": "000"}, {"status": "never_connected", "id": "001"}], "total_affected_items": 2, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
$ curl -k -X GET "https://localhost:55000/agents?q=id!=000;(status=never_connected,id=002)&select=id,status" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"status": "never_connected", "id": "001"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
$ curl -k -X GET "https://localhost:55000/agents?q=id!=000;(status=never_connected;id=002)&select=id,status" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 0, "failed_items": []}, "message": "No agent information was returned", "error": 0}
```

Queries:
- `id!=000;(status=never_connected,id=002)`: use the `or` (`,`) operator within the parenthesis. It returns the expected result (the status of agent with ID `001` is `nevecer_connected`).
- `id!=000;(status=never_connected;id=002)`: use the `and` (`;`) operator within the parenthesis. It returns the expected result (no agents found).

**Comment by GGP1** [comment]
@Desvelao 

> And it seems if using the and ( ;) operator instead of or (,) the results are different, and it returns the expected results in my tests

Sorry, I was not clear here. I meant that the parenthesis were used to create simple (one-level) conditions and not complex ones (indeed, it's possible to group `AND` conditions as well).

However, doing nested queries like `(condition1;(condition2,condition3))` is not supported.

**Comment by GGP1** [comment]
## Update

- Modified the regular expression to support receiving multiple parenthesis in a row
- Implemented the logic to support nested queries

After the changes, some unit tests started failing and I'm reviewing what is the issue

**Comment by GGP1** [comment]
## Update

Added a nested query example to the `Filtering data using queries` section of the documentation.

**Comment by GGP1** [comment]
## Update

- Fixed an issue when processing the query `id!=000;(status=active;(group=default2,group=default3))` that had one parenthesis less than expected.
- Found a query `(status=active;(id!=000,(group=default,group=default2)))` which is using more parenthesis than it should at the start and end of the SQL query. I'm working on the fix.

**Comment by GGP1** [comment]
## Update

- Fixed the logic to support all kind of queries
- Manual testing and addition of integration test cases

**Comment by GGP1** [comment]
## Update

Rebased documentation PR to 4.5.3.
