### ISSUE TITLE
one log trigger one rule?

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#16903]
Hi,

I use wazuh version 4.3.10.

I want to ask that maximun rules can be produced from 1 input log.
I tried but almost 1 rule can be produced from 1 input log, because of some wazuh rule syntax like **_if_sid, if_groups=_**.
May be produce 2 rule from 1 input log with the same **_if_sid or if_group_**.
I tried some rule but it worked with 1 of them.

Best Regards,

**Comment by NahuFigueroa97** [comment]
Hello Thanvantrong! Could you provide me with the example you did? With the if_sid attribute you should be able to create multiple rules (always with ids between 100000 and 120000).

```
<rule id="100001" maxsize="300" level="3">
   <if_sid>100200</if_sid>
   <description>some description</description>
</rule>
```

If the rule matches the id 100200 rule activates and triggers a level 3 alert.

**Comment by thanvantrong** [comment]
Hi,

This alert may generate other alert by **if_group** or **if_sid** but i think with more than alert for 1 log can enrich alert for user.
I think alert with level above 3 should show in dashboard although using **if_sid**, **if_group** or not.
Any one can tell me what file in source code perform for this action?

Regards,
