### ISSUE TITLE
Can't obtain all the routes using the API endpoint

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16912]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16156   |     https://github.com/wazuh/wazuh/pull/16235 |

# Description

During the reorganization API testing the `router.route.get`, you can't obtain all the routes.

While you can obtain all the routes via CLI, like `./build/main router get`, you are not able to do this using the API endpoint.

For example:

```
root@engine:/media/sf_wazuh-qa/deps/wazuh_testing/wazuh_testing/modules/engine# python3 test_api_endpoint.py 
---------

Case: {'command': 'router', 'subcommand': 'get', 'parameters': {}}
Query: {'version': 1, 'origin': {'name': 'engine', 'module': 'api'}, 'command': 'router.route/get', 'parameters': {}}
Response: {"data":{"status":"ERROR","error":"Missing /name"},"error":0}
root@engine:/media/sf_wazuh-qa/deps/wazuh_testing/wazuh_testing/modules/engine#
```

## Considerations

More details in the dev-testing report https://github.com/wazuh/wazuh-qa/issues/4040#issuecomment-1513640663

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
I noticed that the command used in the examples was not correct. To view the list of routes, the command should be ./build/main router table get, instead of ./build/main router get. It's worth noting that the API and CLI use the same command underneath, so it's impossible to display the API differently.

**Comment by roronoasins** [comment]
Now, using the `router.table` command and `get` subcommand, it works.

- cases.json
    ```json
    [
        {
            "command": "router.table",
            "subcommand": "get",
            "parameters": {}
        }
    ]
    ```

```
root@engine:/media/sf_wazuh-qa/deps/wazuh_testing/wazuh_testing/modules/engine# python3 test_api_endpoint.py 
---------

Case: {'command': 'router.table', 'subcommand': 'get', 'parameters': {}}
Query: {'version': 1, 'origin': {'name': 'engine', 'module': 'api'}, 'command': 'router.table/get', 'parameters': {}}
Response: {"data":{"status":"OK","table":[{"name":"default","filter":"filter/allow-all/0","policy":"policy/wazuh/0","priority":33},{"name":"custom","filter":"filter/allow-all/0","policy":"policy/custom/0","priority":123}]},"error":0}
root@engine:/media/sf_wazuh-qa/deps/wazuh_testing/wazuh_testing/modules/engine#
```
