### ISSUE TITLE
How to output the data of nodes to other disks

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#16923]
![企业微信截图_16829150179222](https://user-images.githubusercontent.com/28825226/235439360-fb773db1-704b-403f-93d5-903f78b5b4b4.png)
As shown in the above figure, how to output the data of nodes to the/dev/vdb disk?

**Comment by matias-braida** [comment]
Hello PhuketIsland,
First of all, thanks for using Wazuh.

To change the indexer working directories (indexes and logs), follow the below steps (execute as root user):

1. Stop indexing and perform a flush. Run the following command: 
```
    curl -X POST "https://<indexer_IP>:9200/_flush/synced" -u <username>:<password> -k
```
2. Stop filebeat. Run the following command: 
```
    systemctl stop filebeat
```
3. Stop wazuh-indexer. Run the following command: 
```
    systemctl stop wazuh-indexer
```
4. Move or copy current indexer data (indexes and logs) to the new directories and change ownership.
```
    mv /var/lib/wazuh-indexer/ /<new_folder_lib>/
    mv /var/log/wazuh-indexer/ /<new_folder_log>/
    chown wazuh-indexer:wazuh-indexer -R /<new_folder_lib>/
    chown wazuh-indexer:wazuh-indexer -R /<new_folder_log>/
```
5. Edit indexer configuration file "/etc/wazuh-indexer/opensearch.yml"
6. Change keys "path.data" and "path.logs" to the new directories for indexes and logs respectively
7. Restart the services. 
```
   systemctl daemon-reload
   systemctl start wazuh-indexer
   systemctl restart filebeat
```
Please let me know if this helps.

Regards

**Comment by PhuketIsland** [comment]
Thank you very much. Following your approach, I am currently running normally
