### ISSUE TITLE
Alerts for custom decoder/rules unexpectedly stopped working 

### ISSUE THREAD

**Issue by Verzijl** [wazuh/wazuh#16989]
|Wazuh version| Component | Action type |
|---| --- | --- |
| v4.3.10-40323 | Rules/Decoders | Error |

## Description

Around the beginning of March I added 2 custom rules to my Wazuh installation that will create an alert/email on a failed log in attempt on a Cisco ASA Firewall (VPN connection). This was working until April 10, this is when I have the last log/email showing the correct triggering of the rules.
![image](https://user-images.githubusercontent.com/5962961/235923745-2ba1ae30-85bc-4ac5-a25d-b14a5993aa6b.png)

Last week I noticed that the custom rules are no longer working. There were no changes to the system that would cause the custom rules to stop. 
The default alerts coming from the default decoders/rules are still working correctly (still receiving emails too when the mail level limit is reached).
Using the wazuh-logtest it shows that the decoders/rules are correctly triggered with the log that is created on a failed log in attempt and that an alert would be generated and an email send.
The logs reach the machine correctly (I can see them in the archives).
For my custom rules no more alerts/mails are being generated as they are not shown in the alerts.log/dashboard (and thus not mailed).

Restarting of agent/manager/server did not solve the issue.
Tried debugging modus through wazuh-control, but this did not give me more information.

### Service/Product/Module

Syslog from Cisco ASA 5500 Series Firewall.
https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-101001-to-199021.html

### Current results

When a log containing information about a failed log in attempt reaches the wazuh server it does not trigger an alert which results also in no email being sent and not not showing up in the dashboard.
Using logtest shows that this exact log should trigger an alert and email.

### Expected results

When the log containing information about the failed log in attempt reaches the wazuh server it triggers an alert/email and shows up in the dashboard.

### Log source / integration

Cisco Firewall ---> sends through syslog --> machine with wazuh agent installed (syslog file included in agent config) --> wazuh server/manager

When implementing the custom decoder/rules I followed the documentation:
https://documentation.wazuh.com/4.3/user-manual/ruleset/custom.html

Copied '0064-cisco-asa_decoders.xml' to the correct .../etc/decoders directory.
Excluded the original decoder file in the 'ossec.conf' file:
```
<ruleset>
...
    <decoder_exclude>ruleset/decoders/0064-cisco-asa_decoders.xml</decoder_exclude>
</ruleset>
```

Added the following part to the decoder:
```
<decoder name="cisco-asa-auth-rejected">
    <parent>cisco-asa</parent>
    <prematch offset="after_parent">6-113015</prematch>
    <regex offset="after_parent">(\w+): (\.+) : reason = (\.+) : local database : user = (\S+) : user IP = (\.+)</regex> 
    <order>id, description, reason, username, srcip</order> 
</decoder>
```
The local_rules looks like this (redacted the hostnames):
```
<group name="local,syslog,">

<!-- Failed login on VPN -->
  <rule id="100010" level="10">
    <hostname>123.45.678.910</hostname> 
    <if_sid>64005</if_sid>
    <id>^6-113015</id>
    <description>ASA: VPN $(description) : $(reason) by user: $(username)</description>
    <group>authentication_failed,cisco,cisco-asa</group>
  </rule>

<!-- In case of failed login on gateway -->
  <rule id="100011" level="15">
    <hostname>gateway</hostname>
    <if_sid>64005</if_sid>
    <id>^6-113015</id>
    <description>ASA: VPN $(description) : $(reason) by user: $(username)</description>
    <group>authentication_failed,cisco,cisco-asa</group>
  </rule>

</group>
```
Not sure if interesting or correct, but I noticed that in the dashboard in Management -> Decoders the entries in the excluded decoder still/also show up. 
![image](https://user-images.githubusercontent.com/5962961/235925781-4b2cafca-ad3f-4517-8cdb-21f171c0f676.png)

### Log reference

https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-101001-to-199021.html

### Log examples

```
May  2 10:15:18 123.45.678.910 %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = username1 : user IP = 123.456.789.012
```

logtest (verbose) output (redacted the hostname/IP and username. Removed some non matching lines for clarity):
```
May  2 10:15:18 123.45.678.910 %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = username1 : user IP = 123.456.789.012

**Phase 1: Completed pre-decoding.
	full event: 'May  2 10:15:18 123.45.678.910 %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = username1 : user IP = 123.456.789.012'
	timestamp: 'May  2 10:15:18'
	hostname: '123.45.678.910'

**Phase 2: Completed decoding.
	name: 'cisco-asa'
	parent: 'cisco-asa'
	description: 'AAA user authentication Rejected'
	id: '6-113015'
	reason: 'Invalid password'
	srcip: '123.456.789.012'
	username: 'username1'

**Rule debugging:
	Trying rule: 1 - Generic template for all syslog rules.
		*Rule 1 matched
		*Trying child rules
	Trying rule: 600 - Active Response Messages Grouped
	Trying rule: 650 - Active Response JSON Messages Grouped
	Trying rule: 200 - Grouping of wazuh rules.
	Trying rule: 400 - Rules for Wazuh API events.
...
	Trying rule: 87700 - pfSense firewall rules grouped.
	Trying rule: 87900 - Docker alerts: $(docker.Type)
	Trying rule: 64000 - Grouping of cisco-ASA rules
		*Rule 64000 matched
		*Trying child rules
	Trying rule: 64005 - ASA notification/informational message.
		*Rule 64005 matched
		*Trying child rules
	Trying rule: 100011 - ASA: VPN $(description) : $(reason) by user: $(username)
	Trying rule: 100010 - ASA: VPN $(description) : $(reason) by user: $(username)
		*Rule 100010 matched

**Phase 3: Completed filtering (rules).
	id: '100010'
	level: '10'
	description: 'ASA: VPN AAA user authentication Rejected : Invalid password by user: username1'
	groups: '['local', 'syslog', 'authentication_failed', 'cisco', 'cisco-asa']'
	firedtimes: '1'
	mail: 'True'
**Alert to be generated.
```

### Threats and compliance

--

Any help regarding this issue will be very much appreciated and thanks to anyone for taking the time. Keep up the good work with Wazuh :)

**Comment by s-ocando** [comment]
Hi @Verzijl,

I've tested your use case and it works as expected in my environment.

Do you happen to have multiple managers? If that's the case, the agent might have changed the manager that is reporting to and that could explain why you stopped seeing the custom alerts.

Note that custom rules and decoders are synchronized through the cluster but each manager `ossec.conf` configuration file is independent. If you happen to have multiple managers, make sure to exclude the original decoder file on each manager in your cluster.

Make sure to restart each of the Wazuh managers to apply changes.

Let us know if this solves your issue.

**Comment by Verzijl** [comment]
Hello @s-ocando,

Thank you for taking the time to test it on your environment.

In my system I only have one manager. Also no cluster has been set up.

Is there any (internal) log or process I can check on my server running the manager that could give me more information about how/if the custom rules are checked with logs that are coming in? 

Just to give some more info, there are multiple switches and firewalls sending syslogs to the machine which has the agent installed, all these logs reach the manager correctly and the alerts/emails created by the default decoders/rules are generated correctly too.

I am open to any other suggestions as what might be causing this issue and please let me know if I can provide more information.

**Comment by s-ocando** [comment]
Hi @Verzijl,

To get more information, you can set [analysisd.debug](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#analysisd) option to 1 or 2, depending on the verbose mode you prefer, in the `/var/ossec/etc/internal_options.conf` file.  Remember to restart the manager to apply the change. You can see the logs in: `/var/ossec/logs/ossec.log`.

Also, check the custom rules and decoders file permissions and make sure they're readable by the `wazuh` group.

Regarding your comment that you still see the excluded decoders in your dashboard, I also see them in mine. I found this related issue:  https://github.com/wazuh/wazuh/issues/9073. I'd recommend editing the files from the command line instead of using the graphic interface.

To further test your setup, you can inject the log into a monitored file, for example:
```
echo "May  2 10:15:18 123.45.678.910 %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = username1 : user IP = 123.456.789.012" >> /var/log/messages
```
In my CentOS7 test environment, I injected the log directly into `/var/log/messages`. In your production environment, you may want to create a test file and configure your manager to monitor said file.

To help you debug your case further, can you share your custom rules and decoders files? As well as your manager configuration file. Make sure to redact sensitive information.

**Comment by Verzijl** [comment]
Hi @s-ocando,

### analysis.debug
I set the analysis.debug to 2, but this did not provide me any extra information about the actual analysis. It mostly gives logs like this: `2023/05/10 12:52:48 wazuh-analysisd[8898] state.c:106 at w_analysisd_write_state(): DEBUG: Updating state file.`
And it also shows when it does vulnerabilities scans on the agents.

### Permissions
I checked the rules/decoders files permissions and they are all readable by the `wazuh` group.

> Regarding your comment that you still see the excluded decoders in your dashboard, I also see them in mine. I found this related issue: https://github.com/wazuh/wazuh/issues/9073. I'd recommend editing the files from the command line instead of using the graphic interface.

As long as this only shows in the dashboard that is not an issue. I work mostly with the command line interface, but this was just something that I noticed :)

### Log injections tests
I did 3 tests with the log injection into a monitored file:
1. On the original agent. Created a log file, included it in the (agents) ossec.conf, restarted the agent and injected the log. Still does **not** work. Could be expected as this is basically the same as what happened before, but still good to test separately.
2. On the manager directly. Created a log file, included it in the (managers) ossec.conf, restarted the manager and injected the log. This **does** work! In this case I get the correct alert in the dashboard and the email!
3. On a different agent. Created a log file, included it in the (agents) ossec.conf, restarted the agent and injected the log. Does **not** work. Can see the log reach the manager (see it in archives.log).

To me it is now really unclear why logs coming from an agent do not work, but the same log coming directly from the manager does work...

### Config/decoder/rule files
Here are my managers ossec.conf file and the custom decoder/rule files. (As TXT as Github does not accept xml/conf)
[0064-cisco-asa_decoders.xml.txt](https://github.com/wazuh/wazuh/files/11441314/0064-cisco-asa_decoders.xml.txt)
[local_rules.xml.txt](https://github.com/wazuh/wazuh/files/11441315/local_rules.xml.txt)
[ossec.conf.txt](https://github.com/wazuh/wazuh/files/11441316/ossec.conf.txt)

Thank you for your continuing help!

**Comment by s-ocando** [comment]
Hi @Verzijl, 

The issue seems to be related to the rule `<hostname>` field. When testing directly in the Wazuh manager, the analysis engine uses the pre-decoder hostname information but when the message comes from an agent it uses the agent's information.

Here's an example of the information sent from `remoted` to `analysisd`:
```
test.4960:sendto(5, "1:[001] (AGENT_NAME) any->/var/log/test:May  2 10:15:18 123.45.678.910 %ASA-6-113015: AAA user authentication Rejected : reason = Invalid password : local database : user = username1 : user IP = 123.456.789.012\0", 204, 0, NULL, 0) = 204
```
As you can see, it includes the following agent's information: ID, name, registered IP and log source `1:[001] (AGENT_NAME) any->/var/log/test`

Try changing your custom rule by setting your agent's name in the hostname field `<hostname>AGENT_NAME</hostname>` and it should work as expected.

Let us know if this works for you.
