### ISSUE TITLE
String object has not attribute 'timestamp' in cluster.log

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#16981]
|Wazuh version|Component|
|---|---|
| 4.4.2-rc1 | Wazuh cluster |

## Description

@juliamagan reported this error is being raised in the master node of clusters with version 4.4.2:
```
2023/05/02 14:16:27 ERROR: [Worker wazuh-worker2] [Main] Unhandled error processing request 'b'syn_w_g_e'': 'str' object has no attribute 'timestamp'
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/common.py", line 799, in dispatch
    command, payload = self.process_request(command, payload)
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/master.py", line 264, in process_request
    start_time = self.send_agent_groups_status['date_start'].timestamp()
AttributeError: 'str' object has no attribute 'timestamp'
```

The reason is very possibly related to the changes performed here:
- https://github.com/wazuh/wazuh/pull/16394

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Update

All the status properties inside the `MasterHandler` are saved as a `String` containing the date of the event.
Example:
https://github.com/wazuh/wazuh/blob/13228ade7786495fd6d75f34775efcfc30eeee64/framework/wazuh/core/cluster/master.py#L693-L696

The data from `send_full_agent_groups_status` and `sync_agent_info_status` is used in the `process_request` method as a `start_date`, so it needs to be converted to a `date` type. The following code was added to use a type guard in case the value is an `String` and convert it to the desired `date` type:

https://github.com/wazuh/wazuh/blob/13228ade7786495fd6d75f34775efcfc30eeee64/framework/wazuh/core/cluster/master.py#L262-L277
