### ISSUE TITLE
Fix data type in cluster status dates

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#16995]
## Description

Currently, the default date used in the cluster status variables is a real datetime object:
https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/core/cluster/master.py#L188-L190

That object is transformed to a date string or `n/a` inside `json.dumps` when the cluster state is requested from the API or CLI:
https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/core/cluster/master.py#L280-L284

However, a related change was made in [this PR](https://github.com/wazuh/wazuh/pull/9227) and since then, all dates stored in the status variables are strings:
https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/core/cluster/master.py#L638-L639

So it doesn't make sense for the date to default to a datetime object and then be replaced by strings. It should be a string from the start, which would make testing and maintaining this part of the module much easier.

## To do
Replace this:
https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/core/cluster/master.py#L187-L188

With this:
```PYTHON
        # Sync status variables. Used in cluster_control -i and GET/cluster/healthcheck.
        default_date = 'n/a`
```

Remove date transformation in `json.dumps`. For example (not the only one):
https://github.com/wazuh/wazuh/blob/e958b3c818a25ad1405db11bd17032f8970e1881/framework/wazuh/core/cluster/master.py#L281-L284

Check correct operation after changes and update tests.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

- Changed default date to `'n/a'` 
- Removed the date transformation in `json.dumps()`
- Updated unit tests

Manual testing and integration tests are in progress.

**Comment by GGP1** [comment]
## Update

Tested the changes introduced and opened the pull request with the fix. Moved the state of the issue to pending review.

**Comment by GGP1** [comment]
## Step change

Moving the step to blocked since there are two checks failed. The failures are known and they will be fixed in https://github.com/wazuh/wazuh/pull/16915.

**Comment by GGP1** [comment]
## Update

Fixed the issues that arose after the rebase to master. Moving state to on hold until pull request checks run.

**Comment by GGP1** [comment]
## Update

Checks ran successfully, moved the state to Pending review

**Comment by GGP1** [comment]
## Update

Made the changes requested in the code review and added the commands' start date in the unit tests.

**Comment by GGP1** [comment]
## Update

Made the changes requested, added type hints and updated unit tests.

Moving the status back to final review.
