### ISSUE TITLE
Predecoder doesnt support RFC_5424 format

### ISSUE THREAD

**Issue by ThepoisonedApple** [wazuh/wazuh#16994]
|Wazuh version| Component | Action type |
|all| predecoder | Improve |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

## Description

Wazuh predecoder supports RFC_3164 and we use program_name attiribute in decoders.
But some of our log sources uses RFC_5424 log standart and Wazuh predecoder doesnt support RFC_5424.
It would be great if wazuh predecoder supports this standard as well.

### Service/Product/Module

predecoder

###log sample:
```
1 2023-05-03T10:07:30.610093+03:00 coslat.localdomain 5651sniffer 67701 - - 2023-04-03 11:17:30 AA:BB:CC:DD:EE:F6 10.10.11.12 4989 12345678910 42.51.10.2 443 UDP
```
### Current results
```
**Phase 1: Completed pre-decoding.
	full event: '1 2023-05-03T10:07:30.610093+03:00 coslat.localdomain 5651sniffer 67701 - - 2023-04-03 11:17:30 AA:BB:CC:DD:EE:F6 10.10.11.12 4989 12345678910 42.51.10.2 443 UDP'
```

### Expected results
```
**Phase 1: Completed pre-decoding.
	full event:'1 2023-05-03T10:07:30.610093+03:00 coslat.localdomain 5651sniffer 67701 - - 2023-04-03 11:17:30 AA:BB:CC:DD:EE:F6 10.10.11.12 4989 12345678910 42.51.10.2 443 UDP'
	timestamp: '2023-05-03T10:07:30.610093+03:00'
	hostname: 'coslat.localdomain'
	program_name: '5651sniffer'
```

**Comment by vikman90** [comment]
Hi @ThepoisonedApple.

The current version supports the priority header (RFC 5424) in the Syslog input only (#7381). However, we're working on a replacement of _wazuh-analysisd_, which will mean a redesign of the ruleset and will support more timestamp formats. In addition, it will allow the user to add any header format via regexes. It will not be necessary to implement the support internally.

I hope this can help you.
All the best.

**Comment by ThepoisonedApple** [comment]
Thank you for your quick reply. I'm looking forward to the new version.
