### ISSUE TITLE
ES mappings for timestamp is different for 2.2.x

### ISSUE THREAD

**Issue by systeminsightsbuild** [wazuh/wazuh#17]
To get the mapping to work I had to change te @timestamp format to:

```
      "format": "strict_date_optional_time||epoch_millis"
```

**Comment by santiago-bassett** [comment]
Thank you for letting us know!

**Comment by snaow** [comment]
Hi @systeminsightsbuild,

First of all, thanks for the feedback!

I would like to take a deep look into this, could you tell me if you are using Logstash with our .conf file? ([Wazuh Logstash conf](https://github.com/wazuh/ossec-wazuh/tree/master/extensions/logstash)).

We extract timestamp from OSSEC alerts and match it with Logstash grok filters.
```
date {
        match => ["timestamp", "YYYY MMM dd HH:mm:ss"]
        target => "@timestamp"
    }
```

Then the Elastic mapping has an ISO 8601 compatible date field, _dateOptionalTime_.

Could give me more details about the error?

Use _strict_date_optional_time_ make sense but I am not sure about using _epoch_millis_.

Again thanks for your feedback, we will keep working on improve our ELK Stack integration.

**Comment by systeminsightsbuild** [comment]
I am using the wazuh logstash conf mostly. But ossec is running on nodes that already have logstash configured to deliver logs via rabbitmq the elk cluster. Logstash runs on the elk instances to pull from rabbit and push into elasticsearch. The indices to push to are conditional on the even type.

The only change I made was the elasticsearch mapping. I don't have the error just now, sorry. I'm guessing the "||" means "or" in this context (I'm just learning ES mappings). So probably that bit is not needed like you say?

**Comment by snaow** [comment]
We will study this case in different environments, I think the mapping does not need to change the timestamp type but we will take a deep look into it, maybe you are right, I am not entirely sure.

Thanks for your contribution @systeminsightsbuild !

**Comment by systeminsightsbuild** [comment]
Are you using elasticsearch 2.x? We just upgraded from 1.x and had to do lots of mapping cleanup since 2.x is much stricker about conflicts.

**Comment by snaow** [comment]
Yes, we do, we are using Elastic 2.x.

Like you said, we are trying to adjust the mapping, no conflicts in my labs, I'll keep working on this! Thanks

**Comment by mgmacias95** [comment]
Hello all,

It's been more than two years since the last comment on this issue, so I'm closing it.

Don't hesitate to create a new one if you still have questions or problems.

Thanks,
Marta
