### ISSUE TITLE
Technical debt: Increase code coverage for the data_provider and utils folders in Windows agent

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#17008]
## Description

During the development of #16898, it was found that some modules need more coverage for Windows agent. In particular, the folders **data_provider** and **shared_modules/utils**.

More unit tests should be added to make it possible enabling this check again in the RTR.

## Folders coverage

These are the coverage reports of the RTR for these folders

![2023-05-04_22-14_1](https://user-images.githubusercontent.com/65046601/236360136-81cd5dc6-16eb-4b8a-b1be-0b7c38df8ec3.png)

![2023-05-04_22-14](https://user-images.githubusercontent.com/65046601/236360270-48b08139-f584-4512-a28e-50b93aaa142c.png)

[coverage_report shared_modules-utils winagent.zip](https://github.com/wazuh/wazuh/files/11402652/coverage_report.shared_modules-utils.winagent.zip)
[coverage_report data_provider winagent.zip](https://github.com/wazuh/wazuh/files/11402653/coverage_report.data_provider.winagent.zip)

# DoD

- [ ] Add UT for **data_provider** in Windows agent
- [ ] Add UT for **shared_modules/utils** in Windows agent
- [ ] Remove the `TODO` related section in the RTR
- [ ] Make sure all the CI check pass

**Comment by pereyra-m** [comment]
The issue is moved to "On hold" because #17882 has a higher priority.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
