### ISSUE TITLE
TCP remoted problem

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1701]
## Bug report

**Wazuh version**
_3.7.0_

**Install type**
_manager_

**Log sample**

```
Program received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7f109f942700 (LWP 3413)]
0x00007f10a9744cfb in send () from /lib64/libpthread.so.0
(gdb) frame 1
#1  0x0000000000456d63 in OS_SendSecureTCP (sock=1483, size=405, 
    msg=0x7f109f9310f0) at os_net/os_net.c:521
521        retval = send(sock, buffer, bufsz, 0) == (ssize_t)bufsz ? 0 : OS_SOCKTERR;
```

Bug description
----------------

Remoted malfunctions using TCP when the number of agents/events is high.

**Comment by crolopez** [comment]
The line 521 of **os_net.c** does not contain that code since 3.6.1. Have you been able to replicate it in 3.7?

**Comment by vikman90** [comment]
Possibly related issue: #1715
