### ISSUE TITLE
Improve the RTR to allow a memory test over Windows unit tests

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#17018]
## Description

After the implementation of #16898, it was found that the memory tool Valgrind ins't being executed for the Windows UTs (these tests run with Wine). 

It's required to determine if this is possible and/or a good practice (https://wiki.winehq.org/Wine_and_Valgrind). If it isn't, a proper alternative must be implemented (https://wiki.winehq.org/Wine_and_Valgrind#Alternatives_to_Valgrind).

## DoD

- [ ] Find the best way to implement the memory test with Wine
- [ ] Implement the changes in the RTR
- [ ] Remove the related comment
- [ ] CI Pass

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
