### ISSUE TITLE
Engine - Update filter helper tests

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#17028]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Our current implementation of tests for the builders extensively duplicates code, making small changes in the builders unnecessary mechanical and repetitive work.

We need to improve the test implementation to use parametrized tests with the use cases as input data where applicable.

## Tasks
- [x] Update filter helper tests
- [x] Updated schemval tests

**Comment by JcabreraC** [comment]
ETA delayed due to management request. Time has been dedicated to the construction of new decoders.

**Comment by JavierBejMen** [comment]
Update

Working on common testing framework for all builders

**Comment by JavierBejMen** [comment]
Update
- Implemented common testing framework for builders (map, filter, and transform)
- Added default filter builder and operation tests
- Added default map builder and operation tests

**Comment by JavierBejMen** [comment]
## Update
- Added starts_with and exists builders unit tests
- Improved base tests to include all mockeable interfaces in use cases
- Working on helper unit tests defined in opBuilderHelperFilter.hpp file

**Comment by JavierBejMen** [comment]
## Updates 
- Added int compare tests
- Added string compare tests
- Added regex match/not match tests
- Added ip cidr tests

**Comment by JavierBejMen** [comment]
## Update
- Removed is_true and is_false helpers, a direct value comparison exists.
- Added array_containtes helper tests
- Added all filters by type helper tests
- Added match_value and match_key helper tests
