### ISSUE TITLE
[CDB List] /24-network is sporadically not recognized

### ISSUE THREAD

**Issue by Kompromittiert93** [wazuh/wazuh#17026]
|Wazuh version|Component|Install type|Install method|Platform|
|v4.4.1|Wazuh server|Manager|OS-Repo|AlmaLinux 8|

Problem description:
Wazuh alerts about a login attempt via SSH from a source IP that is actually listed as an allowed IP in a CDB list.

Built rule:
```
<group name="syslog,sshd,">

  <rule id="100000" level="9">
    <if_sid>5715</if_sid>
    <list field="srcip" lookup="not_address_match_key">etc/lists/known-networks</list>
    <description>SSH connection from WAN ($(srcip))</description>
  </rule>

</group>
```

CDB List:
```
10.60.60.10:
10.60.60.11:
10.60.0.:
10.60.7.:
10.60.8.:
10.60.9.:
10.60.93.:
10.60.94.:
10.60.251.:
10.60.252.:
10.60.201.87:
81.X.X.X:
81.X.X.X:
195.X.X.X:
81.X.X.X:
```
*External IPs made unrecognizable

E-Mail Alert:
```
Wazuh Notification.
2023 May 05 01:33:10

Received From: (hostname) any->/var/log/messages
Rule: 100000 fired (level 9) -> "SSH connection from WAN (10.60.94.2)"
Src IP: 10.60.94.2
User: user
Portion of the log(s):

May  5 01:33:09 pbu02 sshd[47294]: Accepted publickey for user from 10.60.94.2 port 39838 ssh2: RSA SHA256:ts51rOWeWe262qkc9sNVOQs/UwrWqpQb5iM92SSDFQY




 --END OF NOTIFICATION
```
Note:
If I run the same line from the alert in the Wazuh web interface in the rule tester, the behaviour is correct. We connect to the systems as a data center (partially automated) more often during the day and only sporadically get this false positive.

Ruleset Test:
```
**Phase 1: Completed pre-decoding.
	full event: 'May  5 01:33:09 hostname sshd[47294]: Accepted publickey for user from 10.60.94.2 port 39838 ssh2: RSA SHA256:ts51rOWeWe262qkc9sNVOQs/UwrWqpQb5iM92SSDFQY'
	timestamp: 'May  5 01:33:09'
	hostname: 'hostname'
	program_name: 'sshd'

**Phase 2: Completed decoding.
	name: 'sshd'
	parent: 'sshd'
	dstuser: 'user'
	srcip: '10.60.94.2'
	srcport: '39838'

**Phase 3: Completed filtering (rules).
	id: '5715'
	level: '3'
	description: 'sshd: authentication success.'
	groups: '["syslog","sshd","authentication_success"]'
	firedtimes: '62'
	gdpr: '["IV_32.2"]'
	gpg13: '["7.1","7.2"]'
	hipaa: '["164.312.b"]'
	mail: 'false'
	mitre.id: '["T1078","T1021"]'
	mitre.tactic: '["Defense Evasion","Persistence","Privilege Escalation","Initial Access","Lateral Movement"]'
	mitre.technique: '["Valid Accounts","Remote Services"]'
	nist_800_53: '["AU.14","AC.7"]'
	pci_dss: '["10.2.5"]'
	tsc: '["CC6.8","CC7.2","CC7.3"]'
```

**Comment by pereyra-m** [comment]
Hello @Kompromittiert93 !

I wasn't able to reproduce this issue locally. When I test the rule locally (using **wazuh-logtest** and also directly with **wazuh-analysisd**) I get the same result than you: the CDB list works as expected.

I'd like to know if you have a single node setup or a cluster. Maybe the CDB list isn't properly synced among the nodes and you receive this false positive sporadically according to the node the agent is reporting to.
Could you confirm which node the agent is connected to when this happens?
Does this happen only with one specific IP?

Regards.

**Comment by Kompromittiert93** [comment]
Hello pereyra-m,

this is a single node setup. The alerts come from various IPs that are listed in the CDB list and thus generate false positives. However, it is currently noticeable that this only affects IPs that are in one of the /24 networks. I have deleted the e-mail box again and will pay more attention to this. However, this will take a few days, since the error occurs very sporadically 0-3 times a day.

**Comment by Kompromittiert93** [comment]
Hello @pereyra-m,

Thanks for the information AND the workaround, that's more than I could have hoped for!

Thanks!

**Comment by pereyra-m** [comment]
Thanks to you @Kompromittiert93 !
