### ISSUE TITLE
Improve catalog endpoint error messages

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#17043]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16156   |     https://github.com/wazuh/wazuh/pull/16235 |

# Description

During the reorganization API testing the `catalog.resource/put` and `catalog.resource/validate`, some error messages seems not correct at all.

For example:

- Create a non-existing item type using json format

    ```
    {
        "command": "router",
        "subcommand": "post",
        "parameters": {
            "type": "none",
            "format": "json",
            "content": "{\"name\":\"decoder/custom/0\",\"metadata\":{\"description\":\"Accept all\"},\"sources\":[\"decoder/integrations/0\"],\"check\":\"+int_equal/wazuh.queue/51\",\"parse\":{\"logpar\":[{\"event.original\":\"hola <~test_route/text>\"}]},\"normalize\":[{\"check\":\"+exists/wazuh.queue\",\"map\":[{\"~env\":\"custom\"}]}]}"
        }
    }
    ```

    The error is the same that appear when the type is missing .The error could be more specific.
    ```
    {"data":{"status":"ERROR","error":"Missing /type parameter or is invalid"},"error":0}
    ```

- Validate an item with wrong name parameter

    ```
    {
        "command": "catalog",
        "subcommand": "validate",
        "parameters": {
            "name": "decoder",
            "format": "json",
            "content": "{\"name\":\"decoder/newdecoder/7\",\"metadata\":{\"description\":\"Accept all\"},\"sources\":[\"decoder/integrations/0\"],\"check\":\"+int_equal/wazuh.queue/51\",\"parse\":{\"logpar\":[{\"event.original\":\"hola <~test_route/text>\"}]},\"normalize\":[{\"check\":\"+exists/wazuh.queue\",\"map\":[{\"~env\":\"custom\"}]}]}"
        }
    }
    ```

    If you provide a `name` that is not the expected, you have the following error msg
    ```
    {"data":{"status":"ERROR","error":"Invalid resource type 'collection' for VALIDATE operation"},"error":0}
    ```

    > The error should show that the name is not the expected from the content but it shows an error with type 'collection' instead.

## Considerations

More details in the dev-testing report https://github.com/wazuh/wazuh-qa/issues/4041

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
This type of message greatly simplifies the API, so there are no plans to change it at this time.

However, we will consider this change in the future as part of the pending API customization.

**Comment by JcabreraC** [comment]
This type of message greatly simplifies the API, so there are no plans to change it at this time.

However, we will consider this change in the future as part of the pending API customization.
