### ISSUE TITLE
Improvements detected during csv and kvmap review

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#17045]
| Target version | Related issue | Related PR/dev branch |
|--------------------|--------------------|-----------------|
|           5.0             |   https://github.com/wazuh/wazuh/issues/16155   |     https://github.com/wazuh/wazuh/pull/16217 |

# Description

During the CSV and KVmap review, some error messages seems not good and some info were missing in the user manual.

Here we have the cases detected:

1. Not an alphanumeric string error

    When you provide a string that is not an alphanumeric one, it says that there is nothing to parse instead of telling that could not be parsed as an alphanumeric or something like that.

    > The error says Nothing to parse when there is a string to parse. It should be like No alphanumeric string found or something like that.

2. Empty input to alphanumeric

    When you provide an empty input to the alphanumeric parser, it throws an EOF error, what is not that bad but here the `Nothing to parse` error seems better.

3. Add all the possible errors to the User Manual, not just the ones related to building or runtime, both should appear within all the possible error list.

4. Add the binary documentation to the User Manual

## Considerations

More details in the dev-testing report https://github.com/wazuh/wazuh-qa/issues/4025

| OS | OS version | Deployment | Image/AMI |
|-- |-- |-- |--|
| Ubuntu | 20.04 | Vagrant | `generic/ubuntu2004` | 

> The dev team provided a vagrantfile with the engine's mvp

**Comment by JcabreraC** [comment]
Fixed in: https://github.com/wazuh/wazuh/issues/23904
