### ISSUE TITLE
Engine Framework API - New endpoints implementation

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17058]
## Description

This issue organizes the development of the new Engine API endpoints. It is divided by module into multiple issues:

- [x] https://github.com/wazuh/wazuh/issues/17343
- [ ] https://github.com/wazuh/wazuh/issues/17059
- [ ] https://github.com/wazuh/wazuh/issues/17060
- [x] https://github.com/wazuh/wazuh/issues/17742
- [ ] https://github.com/wazuh/wazuh/issues/17061
- [ ] https://github.com/wazuh/wazuh/issues/17065
- [ ] https://github.com/wazuh/wazuh/issues/17066
- [ ] https://github.com/wazuh/wazuh/issues/17067

Each of them in charge of:

- Developing the new endpoints
- Testing the changes introduced with unit and integration tests
- Updating the API documentation and specification

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
