### ISSUE TITLE
Engine Framework API - KVDB module endpoints implementation

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#17065]
## Description

This issue is part of the task https://github.com/wazuh/wazuh/issues/17058 and is to implement the API endpoints that will access the resources from the **KVDB** module of the new Engine.

Engine development branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

### Endpoints

| Endpoint | Description | Engine command(s) |
| - | - | - |
| `GET /engine/kvdb` | List all databases | `kvdb.manager/get` |
| `POST /engine/kvdb` | Create a new database | `kvdb.manager/post` |
| `DELETE /engine/kvdb` | Delete a database| `kvdb.manager/delete` |
| `GET /engine/kvdb/entries` | Get all entries or a list of them | `kvdb.db/get, kvdb.manager/dump` |
| `POST /engine/kvdb/entries` | Insert a new entry | `kvdb.db/put` |
| `PUT /engine/kvdb/entries` |Update aentry value| `kvdb.db/put` |
| `DELETE /engine/kvdb/entries` | Delete an entry or a list of them | `kvdb.db/delete` |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):

- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Specification.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Update

- Finished the development of the controllers.
- Started to document the behavior of each one of the. commands and possible error cases.

**Comment by RamosFe** [comment]
## Update
- Added a new endpoint for updating entries value.
- Changed the commands to the correct ones.
- Started developing the unit tests

**Comment by RamosFe** [comment]
## Update
- Added error handling for each endpoint.
- Added unit tests for each new functionality.
- Added docstrings to all the new code related to the KVDB Module.

Development branch: https://github.com/wazuh/wazuh/tree/add/17065-kvdb-module

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
