### ISSUE TITLE
Engine Framework API - Delete deprecated endpoints

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17062]
## Description

This issue organizes the deletion of the API endpoints that will be replaced by the ones from the new Engine described in https://github.com/wazuh/wazuh/issues/17058.

The group of endpoints to delete are:

- https://github.com/wazuh/wazuh/issues/17063
- https://github.com/wazuh/wazuh/issues/17068
- https://github.com/wazuh/wazuh/issues/17069

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
