### ISSUE TITLE
Engine Framework API - Metrics module endpoints implementation

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#17066]
## Description

This issue is part of the task [https://github.com/wazuh/wazuh/issues/17058](https://github.com/wazuh/wazuh/issues/17058) and is to implement the API endpoints that will access the resources from the **Metrics** module of the new Engine.

Engine development branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

### Endpoints

| Endpoint | Description | Engine command(s) |
| - | - | - |
| `GET /engine/instruments` | List all instruments showing its name, status and type | ` metrics/list` |
| `GET /engine/metrics` | List all metrics or all of them as JSON | `metrics/dump, metrics/get` |
| `PUT /engine/instruments/enable` | Enable or disable a specific instrument | `metrics/enable` |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):

- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Specification.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Update

- Development of the skeleton of the Metrics controller.
- Development of a builder to create the requests to the engine.
- Development of an `enum` hierarchy for better representation of the differents commands of the engine related to metrics.
- Added builder to the Metrics controller.
- Separated logic of each endpoint of the Metrics controller in a different function.
- Added the DistributedApi object to each endpoint of the Metrics controller.


All the development is in the branch https://github.com/wazuh/wazuh/tree/add/17066-metrics-module

**Comment by RamosFe** [comment]
## Update

- Added a mock to interact with the Wazuh Engine for the Metrics module.
- Added the pretty parameter to the Metrics endpoints.
- Added errors related to query parameters.
- Added return value using WazuhResults.
- Addition of the endpoints the metrics to the Specs.

**Comment by RamosFe** [comment]
## Update
- Added a hierarchy of classes to handle the different query parameters of the Engine endpoints.
- Added logic to handle the `select` query parameter.
- Added logic to handle the `search` query parameter.
- Added logic to handle the `offset` query parameter.
- Added logic to handle the `limit` query parameter.
- Added class to handle the execution of each transformation to the response message.

**Comment by RamosFe** [comment]
## Update
- Added unit tests for the `EngineRequestMessage`.
- Added unit tests for the `EngineFieldSelector`.
- Fixed bugs related to `EngineFieldSelector`.
- Added unit tests for the `EngineFieldSearch`.
- Fixed bug related to `EngineFieldSearch` and changed in which cases it can be used.
- Added unit tests for the `EngineFieldOffset`.
- Added unit tests for the `EngineFieldLimit`.
- Added unit tests for the `EngineFieldSort`.

**Comment by RamosFe** [comment]
## Update

Created a new `subtask` [17343](https://github.com/wazuh/wazuh/issues/17343) to develop the common library of the Engine endpoints. Due to being common functionalities of the Engine endpoints the development of the following functionalities will continue under the Issue [17343](https://github.com/wazuh/wazuh/issues/17343):

- `EngineRequestMessage`
- `EngineFieldSelector`
- `EngineFieldSearch`
- `EngineFieldOffset`
- `EngineFieldLimit`
- `EngineFieldSort`
- `EngineTransformationSequence`
- `EngineCommand`
- `WazuhMockEngine` and its implementation using the engine socket.

**Comment by RamosFe** [comment]
## Update

Moving the state of this Issue to `blocked` until https://github.com/wazuh/wazuh/issues/17343 is finished. After finishing the mentioned issue, we should rebase the branch to be able to continue with the updated common library.

**Comment by RamosFe** [comment]
## Update

Using the script described in Issue https://github.com/wazuh/wazuh/issues/17343, tested the *Metrics* module requests and response via socket.

### Command: `metrics.manager/list`
```
{'version': 1, 'origin': {'name': 'Origin component', 'module': 'component of module'}, 'command': 'metrics.manager/list', 'parameters': {}}
```

```
{'status': 'OK', 'value': [{'type': 'Counter', 'name': 'ConsumedEvents', 'status': 'enabled', 'scope': 'EventQueue'}, {'status': 'enabled', 'scope': 'EventQueue', 'type': 'Counter', 'name': 'QueuedEvents'}, {'scope': 'EventQueue', 'type': 'UpDownCounter', 'name': 'UsedQueue', 'status': 'enabled'}, {'name': 'ConsumedEventsPerSecond', 'scope': 'EventQueueDelta', 'type': 'Counter', 'status': 'enabled'}, {'status': 'enabled', 'name': 'ConnectedClients', 'type': 'UpDownCounter', 'scope': 'endpointAPI'}, {'type': 'Histogram', 'status': 'enabled', 'scope': 'endpointAPI', 'name': 'QueueSize'}, {'status': 'enabled', 'name': 'ResponseTime', 'scope': 'endpointAPI', 'type': 'Histogram'}, {'scope': 'endpointAPI', 'name': 'TotalRequest', 'type': 'Counter', 'status': 'enabled'}, {'type': 'Counter', 'status': 'enabled', 'scope': 'endpointAPIRate', 'name': 'RequestPerSecond'}, {'status': 'enabled', 'name': 'BytesReceived', 'scope': 'endpointEvent', 'type': 'Counter'}, {'name': 'EventSizeHistory', 'type': 'Histogram', 'status': 'enabled', 'scope': 'endpointEvent'}, {'name': 'BytesReceivedPerSeconds', 'type': 'Counter', 'status': 'enabled', 'scope': 'endpointEventRate'}, {'name': 'EventsReceivedPerSeconds', 'scope': 'endpointEventRate', 'status': 'enabled', 'type': 'Counter'}]}
```

### Command: `metrics.manager/dump`
```
{'version': 1, 'origin': {'name': 'Origin component', 'module': 'component of module'}, 'command': 'metrics.manager/dump', 'parameters': {}}
```

```
{'status': 'OK', 'value': {'endpointAPI': {'QueueSize': {'records': [{'instrument_description': '', 'attributes': [{'buckets': [0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000], 'type': 'HistogramPointData', 'max': 1, 'sum': 10, 'count': 20, 'min': 0, 'counts': [10, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}], 'instrument_name': 'QueueSize', 'start_time': 'Thu Jun  8 18:05:03 2023', 'type': 'Histogram', 'unit': ''}], 'version': '', 'schema': ''}, 'TotalRequest': {'version': '', 'schema': '', 'records': [{'instrument_description': '', 'unit': '', 'instrument_name': 'TotalRequest', 'start_time': 'Thu Jun  8 18:05:03 2023', 'attributes': [{'type': 'SumPointData', 'value': 10}], 'type': 'Counter'}]}, 'ResponseTime': {'schema': '', 'version': '', 'records': [{'unit': '', 'instrument_description': '', 'instrument_name': 'ResponseTime', 'start_time': 'Thu Jun  8 18:05:03 2023', 'type': 'Histogram', 'attributes': [{'counts': [9, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sum': 11, 'buckets': [0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000], 'type': 'HistogramPointData', 'count': 10, 'max': 11, 'min': 0}]}]}, 'ConnectedClients': {'records': [{'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_description': '', 'unit': '', 'attributes': [{'value': 1, 'type': 'SumPointData'}], 'instrument_name': 'ConnectedClients', 'type': 'UpDownCounter'}], 'schema': '', 'version': ''}}, 'endpointEvent': {'EventSizeHistory': {'records': [{'unit': '', 'type': 'Histogram', 'instrument_description': '', 'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_name': 'EventSizeHistory', 'attributes': [{'buckets': [0, 5, 10, 25, 50, 75, 100, 250, 500, 750, 1000, 2500, 5000, 7500, 10000], 'max': 2227, 'sum': 203662, 'count': 776, 'min': 35, 'type': 'HistogramPointData', 'counts': [0, 0, 0, 0, 3, 4, 260, 238, 33, 233, 3, 2, 0, 0, 0, 0]}]}], 'schema': '', 'version': ''}, 'BytesReceived': {'schema': '', 'records': [{'unit': '', 'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_name': 'BytesReceived', 'instrument_description': '', 'attributes': [{'value': 203662, 'type': 'SumPointData'}], 'type': 'Counter'}], 'version': ''}}, 'KVDB': None, 'endpointAPIRate': {'RequestPerSecond': {'records': [{'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_description': '', 'type': 'Counter', 'attributes': None, 'unit': '', 'instrument_name': 'RequestPerSecond'}], 'version': '', 'schema': ''}}, 'endpointEventRate': {'BytesReceivedPerSeconds': {'schema': '', 'version': '', 'records': [{'start_time': 'Thu Jun  8 18:05:03 2023', 'unit': '', 'type': 'Counter', 'instrument_name': 'BytesReceivedPerSeconds', 'attributes': [{'type': 'SumPointData', 'value': 348}], 'instrument_description': ''}]}, 'EventsReceivedPerSeconds': {'records': [{'start_time': 'Thu Jun  8 18:05:03 2023', 'type': 'Counter', 'unit': '', 'instrument_name': 'EventsReceivedPerSeconds', 'attributes': [{'type': 'SumPointData', 'value': 3}], 'instrument_description': ''}], 'version': '', 'schema': ''}}, 'EventQueue': {'ConsumedEvents': {'schema': '', 'version': '', 'records': [{'unit': '', 'attributes': [{'value': 776, 'type': 'SumPointData'}], 'start_time': 'Thu Jun  8 18:05:03 2023', 'type': 'Counter', 'instrument_name': 'ConsumedEvents', 'instrument_description': ''}]}, 'QueuedEvents': {'schema': '', 'records': [{'instrument_description': '', 'attributes': [{'value': 776, 'type': 'SumPointData'}], 'instrument_name': 'QueuedEvents', 'unit': '', 'type': 'Counter', 'start_time': 'Thu Jun  8 18:05:03 2023'}], 'version': ''}, 'UsedQueue': {'records': [{'attributes': [{'type': 'SumPointData', 'value': 0}], 'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_name': 'UsedQueue', 'type': 'UpDownCounter', 'unit': '', 'instrument_description': ''}], 'schema': '', 'version': ''}}, 'EventQueueDelta': {'ConsumedEventsPerSecond': {'records': [{'start_time': 'Thu Jun  8 18:05:03 2023', 'instrument_description': '', 'type': 'Counter', 'instrument_name': 'ConsumedEventsPerSecond', 'attributes': [{'value': 776, 'type': 'SumPointData'}], 'unit': ''}], 'schema': '', 'version': ''}}}}
```

### Command: `metrics.manager/enable`
```
{'version': 1, 'origin': {'name': 'Origin component', 'module': 'component of module'}, 'command': 'metrics.manager/enable', 'parameters': {'scopeName': 'EventQueue', 'instrumentName': 'ConsumedEvents', 'status': 'false'}}
```

```
{'status': 'OK'}
```

**Comment by RamosFe** [comment]
## Update

- Added data normalization for the `metrics.manager/dump` response.
- Updated specs response for all endpoints based on the Engine commands responses.
- Added unit test for all the controllers.
- Added error handling for all the controllers.
- Deleted `engine/metrics/test` due to being a command developed for use internally.
- Updated docstrings to match the format of the project.

**Comment by RamosFe** [comment]
## Update

- Replaced `EngineRequestMessage` with `create_socket_message`.
- Replaced transformations from the Engine library with `process_array`.
- Changed some Unit test due to the changes described.
- Modified specs.
- Added integration test for the `engine/instruments/enable` and `engine/instruments` endpoints.

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
