### ISSUE TITLE
Engine Framework API - Config module endpoints implementation

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17060]
## Description

This issue is part of the task https://github.com/wazuh/wazuh/issues/17058 and is to implement the API endpoints that will access the resources from the **config** module of the new Engine.

Engine development branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

### Endpoints

| Endpoint | Description | Engine command(s) |
| - | - | - |
| `GET /engine/config/runtime` | Get the runtime configuration of the manager | `config.runtime/get` |
| `PUT /engine/config/runtime` | Update the runtime configuration of the manager | `config.runtime/put`, `config.runtime/save` |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):

- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [x] Specification.
- [ ] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

- Compiled the Engine source code
- Compiled protocol buffers for C and Python
- Started trying out engine commands and tested some of them

**Comment by GGP1** [comment]
## Update

- Compiled the Engine source code
- Compiled protocol buffers for C and Python
- Started trying out some engine commands

**Comment by GGP1** [comment]
## Update

Reviewed source code related to the communication between the API and the Engine.

**Comment by GGP1** [comment]
## Update

> 16/05/23

- Re-compiled the engine to solve some issues when using the binary
- Implemented the endpoints' controllers
- Created unit tests to cover the new logic
- Updated the spec

**Comment by GGP1** [comment]
## Update

- Made some corrections in the updates to the spec
- I would prefer to use "key: value" for the configuration values, instead of "name: content" like the engine does.
- Endpoints functions implementation
- Started developing unit tests for the new logic and the mocks for the engine commands

**Comment by GGP1** [comment]
## Update

- Updated the endpoints specification, created a schema for the responses and the Engine tag.
- Added RBAC actions to the spec and controllers (although they will be created in a future issue).
- Moved the new code out of the engine folder previously created, all engine modules will be developed in the same file.

**Comment by GGP1** [comment]
## Update

- Finished the development of the mocks and unit tests
- Met with Fede to share my approach with him, to discuss about mocks, engine commands and the implementation of the parameters we will support
- Read about protocol buffers compilation in Python and their JSON mapping

**Comment by GGP1** [comment]
## Update

- Engine config mock corrections
- Uploaded partial changes to make it easier to build the docker environment
- Created the model for the `PUT /engine/config/runtime` endpoint request body
- Fixed some issues with wazuh-apid when running the Engine changes in a Docker environment

**Comment by GGP1** [comment]
## Update

Started the development of the integration tests that cover the added functionality.

**Comment by GGP1** [comment]
## Update

Started investigating about how to use Vagrant and installed it along with VirtualBox to build and test the Engine. 

I ran into an issue related to the fact that I'm running nested VMs, I tried changing the Vagrant box and some parameters to make it work but without much luck. I'm looking for a solution to this.

**Comment by GGP1** [comment]
## Update

- Continued the Engine installation through Vagrantfile instructions. Ended up with the storage full and having to restore the data to a previous checkpoint. I will continue the development with the mocks until some testing is required.
- Developed integration tests for one of the endpoints
- Discussed with Fede about the Engine commands' outputs
- Implemented the parsing for the `config.runtime/get` command

**Comment by GGP1** [comment]
## Update

- Implemented unit tests for the configuration content parsing
- Added test cases in the integration test

**Comment by GGP1** [comment]
## Update

- Made remaining changes to the API integration tests and the configuration response parsing
- Added the mapping of the integration tests

Before opening the pull request and proceeding with the review, we should integrate the changes from https://github.com/wazuh/wazuh/issues/17343 to this one and probably adjust some things in the unit/integration tests. Moving the status to _On hold_ until the other issue is approved.

**Comment by GGP1** [comment]
## Update

- Added ITs for the parameters `query`, `select`, `sort`, `distinct`.
- Added validation for the name parameter
- Modified the error handling and created a new Wazuh error

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
