### ISSUE TITLE
The directories of multigroups that no longer exist aren't removed on the worker.

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#1709]
**Wazuh version**
3.7.0-3710

**Install method**
Packages: wazuh-manager-3.7.0-0.3710.22102018.37.x86_64.rpm

The multigroups directories created at the master of the cluster are pushed to the worker properly, but when a multigroup cease existing the folder is deleted in the master and it persist in the worker.
In this case, the multigroup no longer exists cause I add another group to the agent, and it was the only agent in the cluster. The new multigroup was correctly created and the configuration was pushed normally.

**Comment by TJOSERAFAEL** [comment]
Hi @Skeptor 

please try with the new generated development packages. It must be resolved.

Regards.

**Comment by TJOSERAFAEL** [comment]
Hi @Skeptor 

this error is still happening with the latest dev packages. Cluster must be revised.

Best regards.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/1732 solves the issue
