### ISSUE TITLE
What should I do if I want to keep only 30 days of data

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#17090]
Hello! I found that my disk is not enough. I only want to save the data for 30 days. How can I modify it?
![image](https://github.com/wazuh/wazuh/assets/28825226/a40a06ce-48e5-4652-8f67-8f0df89d7d9c)

**Comment by s-ocando** [comment]
Hi @PhuketIsland,

To control your disk space, you need to manage both the Wazuh server and the Wazuh indexer data.

In the Wazuh server, alerts are stored under `/var/ossec/logs/alerts/` and compressed each night by default.

To delete alert files older than 30 days, you can set a cron job like the following one:
```
45 0 * * * find /var/ossec/logs/alerts/ -name "*.gz" -type f -mtime +30 -exec rm -f {} \;
```
This cron job deletes all the `.gz` files older than 30 days every day at 12:45 am. 

In case you're storing all events with the [`<logall>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall) or the [`<logall_json>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#logall-json) option, make sure to also delete files under `/var/ossec/logs/archives/`.  

Regarding the Wazuh indexer data, you can create policies to manage your indices and automatically delete old ones. You can find more details in the OpenSearch documentation: [Index State Management](https://opensearch.org/docs/2.6/im-plugin/ism/index/). Note that [Wazuh indexer 4.4.1](https://github.com/wazuh/wazuh-packages#wazuh-indexer) is based on OpenSearch 2.6.0.

Also, check out this blog post that although is a bit old, might still be helpful: [Wazuh index management]( https://wazuh.com/blog/wazuh-index-management/).

Let us know if you have any questions.

**Comment by PhuketIsland** [comment]
@s-ocando hello
Thank you for your answer.
Can the files under /var/lib/wazuh index/nodes/0/indexes be deleted? The files below occupy the most disk capacity.
