### ISSUE TITLE
Rule groups values contain new lines or leading spaces in `GET /rules/groups`

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#17113]
|Wazuh version|Component|
|---|---|
| 4.5.0 | Wazuh component |

## Description

The endpoint `GET /rules/groups` returns group names that contain new lines or leading spaces.
![image](https://github.com/wazuh/wazuh/assets/34042064/e6edf047-ce8f-49a5-8dc7-c2cc6a7ef18d).

Moreover, a group with a new line and leading spaces without an identifier is displayed.
![image](https://github.com/wazuh/wazuh/assets/34042064/2f62c43a-a22d-42b8-8dd1-2857c3148d1d)

I guess this could be a parsing problem and it is not expected the group names contain the new lines or leading spaces.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

- Fixed the issue by replacing `\n`, `\t` and ` ` characters with an empty string
- Created a unit test to cover the new behavior

I would like to discuss with the team about the scenario where the name contains just undesired characters (for example, `\t \n`) before submitting the solution.

**Comment by GGP1** [comment]
## Update

I found that Core is removing the characters `\n`, `\r` and white spaces from XML tags values [here](https://github.com/wazuh/wazuh/blob/5fa2996c20178a7b70d3866e031273ecd6dfca7c/src/os_xml/os_xml.c#L329), so we are going to replicate that behavior.

**Comment by Desvelao** [comment]
This problem could be visible with the suggestions displayed in the new search bar.

I see some problems that should maybe be solved by the Wazuh core.
- group name can contain characters for new lines `\n`
- leading whitespace could not make a sense

For another hand, does the group name `\n    ` (note the whitespaces) make sense? And, should the users be able to search for this group? If yes, how are we supposed to query this? I tried to do a request, enconding the `\n` and whitespace characters and I got an error:

```console
curl -k -X GET "https://localhost:55000/rules?limit=10&q=group~%0A%20%20%20%20" -H "Authorization: Bearer $TOKEN"
```

API logs:
```
2023/08/16 09:11:50 INFO: wazuh-wui 172.24.0.1 "GET /rules" with parameters {"limit": "10", "q": "group~\n    "} and body {} done in 0.843s: 400
```

The goal is the user can do a query using the group name. I am not sure if this needs changes in core or API.

**Comment by GGP1** [comment]
@Desvelao

Core is removing the `\n`, `\r` and ` ` from the rules groups names and we will do the same as I mentioned [here](https://github.com/wazuh/wazuh/issues/17113#issuecomment-1675080152). So the name `\n    ` should not appear anymore and the other names that contained empty lines or whitespaces will no longer have them.

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.5.3.

**Comment by GGP1** [comment]
## Update

Changed the logic and tests to remove leading and trailing whitespaces instead of all of them.
