### ISSUE TITLE
Release 4.4.2 - Release Candidate 2 - Python unit tests

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#17139]
The following issue aims to run all `python unit tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## Python unit tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     | https://github.com/wazuh/wazuh/issues/17004 |
| **Version**                          | 4.4.2 |
| **Release candidate #**              |2|
| **Tag**                              | [v4.4.2-rc2](https://github.com/wazuh/wazuh/tree/v4.4.2-rc2) |
| **Previous python unit tests issue** | [#16979](https://github.com/wazuh/wazuh/issues/16979) |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended test results report must be attached as zip or text. This report can be used by the auditors to dig deeper into any possible failures and details.

As for the coverage results, they must be added and split into modules. Test files must not be included in the coverage report.

All test coverage results must have one of the following statuses: 
|                 |        |
|-----------------|--------|
| :green_square:  | >= 75% |
| :yellow_square: | >= 50% |
| :orange_square: | >= 25% |
| :red_square:    | < 25%  |

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/17139#issuecomment-1549885953).

All of them have passed, I, therefore, conclude that this issue is finished and OK for this release candidate.

|                                        | **Coverage** | **Status** |
|----------------------------------------|--------------|------------|
| **Overall python unit tests coverage** | 85,06% | :green_square: |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted to close this issue.

- [x] @Selutario

**Comment by GGP1** [comment]
[B41927_api_html_report.tar.gz](https://github.com/wazuh/wazuh/files/11489366/B41927_api_html_report.tar.gz)
[B41928_wodles_html_report.tar.gz](https://github.com/wazuh/wazuh/files/11489368/B41928_wodles_html_report.tar.gz)
[B41926_framework_html_report.tar.gz](https://github.com/wazuh/wazuh/files/11489403/B41926_framework_html_report.tar.gz)
