### ISSUE TITLE
FIM not working when removing folders

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1714]
## Bug report

**OS**
_Ubuntu 18, CentOS 7_

**Wazuh version**
_3.7.0-3710_

**Install type**
_manager/agent_

**Install method**
_sources_

**Log sample**

```
ossec.log output:
2018/10/24 05:05:57 ossec-syscheckd: DEBUG: audit_event: uid=root, auid=root, euid=root, gid=root, pid=17065, ppid=15056, path=/root/wazuh/folder_23, pname=/usr/bin/rm
2018/10/24 05:05:57 ossec-syscheckd: DEBUG: audit_event: uid=root, auid=root, euid=root, gid=root, pid=17065, ppid=15056, path=/root/wazuh/folder_22, pname=/usr/bin/rm
2018/10/24 05:05:57 ossec-syscheckd: DEBUG: audit_event: uid=root, auid=root, euid=root, gid=root, pid=17065, ppid=15056, path=/root/wazuh/folder_21, pname=/usr/bin/rm


audit.log output:
type=CWD msg=audit(1540371957.800:10057):  cwd="/root/wazuh"
type=PATH msg=audit(1540371957.800:10057): item=0 name="/root/wazuh" inode=33608681 dev=fd:00 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:user_home_t:s0 objtype=PARENT cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PATH msg=audit(1540371957.800:10057): item=1 name="folder_22" inode=50352535 dev=fd:00 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:user_home_t:s0 objtype=DELETE cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
type=PROCTITLE msg=audit(1540371957.800:10057): proctitle=726D002D69002D7266002F686F6D652F63372F746573742F666F6C6465725F312F666F6C6465725F322F666F6C6465725F332F666F6C6465725F342F666F6C6465725F352F666F6C6465725F362F666F6C6465725F372F666F6C6465725F382F666F6C6465725F392F666F6C6465725F31302F666F6C6465725F31312F666F6C
type=SYSCALL msg=audit(1540371957.800:10058): arch=c000003e syscall=263 success=yes exit=0 a0=4 a1=91c8a8 a2=200 a3=0 items=2 ppid=15056 pid=17065 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=16 comm="rm" exe="/usr/bin/rm" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="wazuh_fim"
```

Bug description
----------------
Audit is not building the correct paths when running rm -rf <folder>.

The **cwd** and **item0** variables contain the current directory (`pwd`), **item1** is the folder that we want to remove. With this information, `auditd` can't build correctly the path, trying to remove the folder and the files contained in it at `/root/wazuh/folder_4` when the correct path is: 
```
/root/wazuh/folder_1/folder_2/folder_3/../folder_21/folder_22
```
In addition, other recursive commands do not work either. For example:
```
root@manager:~# touch -R folder1
```
or 
```
root@manager:~# chown -R root:root folder1
```

This leads to no generation of alerts related to the files contained in this folder.

**Comment by Cerv1** [comment]
Hi team,

After a while researching we've found a solution.

Since with `auditd` we can extract the `inode` information from the file, we will store this information in a hash table after the first scan. Therefore, when we get an incomplete path of an `auditd` event we will be able to consult in this table with the **inode as key** to find the complete path and thus be able to alert correctly.

This development is being done [in this branch](https://github.com/wazuh/wazuh/tree/fix-whodata-linux).

Regards,
Cerv1.

**Comment by vikman90** [comment]
Tracking issue in #1848.
