### ISSUE TITLE
Extend the OS info data for macOS 14

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#17150]
- Parent issue: #17148

Ensure that Syscollector provides the correct name of the new macOS when it's available.

The beta is expected to arrive on June 5th.

**Comment by Dwordcito** [comment]
The next codename is "Sonama"

**Comment by Dwordcito** [comment]
@GabrielEValenzuela backport to 4.5.3

**Comment by GabrielEValenzuela** [comment]
On it
