### ISSUE TITLE
Change 'Ossec' text to 'Wazuh' on the current decoders and rules

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#17168]
|Wazuh version| Component | 
|---| --- | --- |
| 4.4.x | Rules/Decoders |

Currently, the Ossec word appears in the ruleset in different ways: 

### Rules 

- comments
- description
- match
- category
- group
- field
- decoded_as

### Decoders

- comments
- sample logs
- parent
- type
- program_name
- plugin_decoder
- decoder
- prematch 

This issue will manage the change for rules and decoder descriptions to replace Ossec with Wazuh. 
Other Ossec text replacements will require a deeper analysis and mostly will be managed with the new engine as a breaking change in Wazuh v5

**Comment by jnasselle** [comment]
This issue affects some Jenkins tests. The next issue will handle them https://github.com/wazuh/wazuh-jenkins/issues/5186
