### ISSUE TITLE
Upgrade errors. 4.3 to 4.4 and 4.4 to 4.5. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#17174]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4 | - | Manager | Sources | Linux |

# Description 

It was found that upgrading the Wazuh manager from 4.4 to 4.5 raises an error that prevents the upgrade to be completed. Later on, a similar behavior was also found during an upgrade from 4.3 to 4.4. 

### Using Ubuntu Focal to install 4.3 
- `make clean; make clean-deps; rm -rf external/*; make deps`
- `make -j$(nproc) TARGET=server`
- `./install.sh`

  <details>
  <summary>Expand</summary>

  ![image](https://github.com/wazuh/wazuh/assets/13010397/5f55be3f-21a9-43d1-a51d-f0d95a112693)
  
  </details>

### Upgrading to 4.4
- `git checkout 4.4`
- `make clean; make clean-deps; rm -rf external/*; make deps`
- `make -j$(nproc) TARGET=server`
- `./install.sh`

  <details>
  <summary>Expand</summary>
  
  ![image](https://github.com/wazuh/wazuh/assets/13010397/0cc1f099-cbe2-4aa0-90fa-8b1145dcf492)
  ![image](https://github.com/wazuh/wazuh/assets/13010397/1d34cbcf-547a-436f-97cb-49c0e3207d55)
  
  </details>
  
  `journalctl -xeu wazuh-manager.service`
  <details>
  <summary>Expand</summary>
  
  ```
  A stop job for unit wazuh-manager.service has finished.
  
  The job identifier is 1954 and the job result is done.
   19 10:58:58 jammy systemd[1]: wazuh-manager.service: Consumed 37.708s CPU time.
  Subject: Resources consumed by unit runtime
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  The unit wazuh-manager.service completed and consumed the indicated resources.
   19 10:59:05 jammy systemd[1]: Starting Wazuh manager...
  Subject: A start job for unit wazuh-manager.service has begun execution
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  A start job for unit wazuh-manager.service has begun execution.
  
  The job identifier is 2112.
   19 10:59:06 jammy env[27542]: Starting Wazuh v4.4.2...
   19 10:59:18 jammy env[27542]: wazuh-apid did not start correctly.
   19 10:59:18 jammy systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
  Subject: Unit process exited
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  An ExecStart= process belonging to unit wazuh-manager.service has exited.
  
  The process' exit code is 'exited' and its exit status is 1.
   19 10:59:18 jammy systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
  Subject: Unit failed
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  The unit wazuh-manager.service has entered the 'failed' state with result 'exit-code'.
   19 10:59:18 jammy systemd[1]: Failed to start Wazuh manager.
  Subject: A start job for unit wazuh-manager.service has failed
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  A start job for unit wazuh-manager.service has finished with a failure.
  
  The job identifier is 2112 and the job result is failed.
   19 10:59:18 jammy systemd[1]: wazuh-manager.service: Consumed 3.484s CPU time.
  Subject: Resources consumed by unit runtime
  Defined-By: systemd
  Support: http://www.ubuntu.com/support
  
  The unit wazuh-manager.service completed and consumed the indicated resources.
  ```
  
  </details>
    
  The environment start to work again using wazuh-control restart and the following steps.
      
  <details>
  <summary>Expand</summary>
  
  ![image](https://github.com/wazuh/wazuh/assets/13010397/e5f997f4-719a-4e4e-a401-70bb700c7515)
  
  </details>

## Fresh install 4.4 after previous upgrade 

Cleaning previous installation using this guide
https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html#uninstall

Causes an error during installation

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/1291d12f-a5c8-4ba8-ad81-4ea3ac02e306)

</details>

But service starts correctly

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/a0c1e8b0-fea7-4828-ae4a-90097ceca8f3)

</details>
   
### Using Centos 9 to install 4.4
- `make clean; make clean-deps; rm -rf external/*; make deps`
- `make -j$(nproc) TARGET=server`
- `./install.sh`

  <details>
  <summary>Expand</summary>
  
  ![image](https://github.com/wazuh/wazuh/assets/13010397/994c4d6b-5d87-410d-b482-165398086234)
  
  </details>

### Upgrading to 4.5
- `git checkout 4.5`
- `make clean; make clean-deps; rm -rf external/*; make deps`
- `make -j$(nproc) TARGET=server`
- `./install.sh`

  <details>
  <summary>Expand</summary>
  
  ![image](https://github.com/wazuh/wazuh/assets/13010397/8d8497b0-92d7-4d1d-9201-0599338e68c0)
  
  </details>
  
  `journalctl -xe `
  
  <details>
  <summary>Expand</summary>

  ```
  Subject: Unit failed
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  The unit wazuh-manager.service has entered the 'failed' state with result 'exit-code'.
   19 11:56:22 centos9 systemd[1]: Failed to start Wazuh manager.
  Subject: A start job for unit wazuh-manager.service has failed
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  A start job for unit wazuh-manager.service has finished with a failure.
  
  The job identifier is 2381 and the job result is failed.
   19 11:58:08 centos9 systemd[1]: Starting Wazuh manager...
  Subject: A start job for unit wazuh-manager.service has begun execution
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  A start job for unit wazuh-manager.service has begun execution.
  
  The job identifier is 2479.
   19 11:58:08 centos9 env[26642]: Traceback (most recent call last):
   19 11:58:08 centos9 env[26642]:   File "/var/ossec/api/scripts/wazuh-apid.py", line 12, in <module>
   19 11:58:08 centos9 env[26642]:     from api.constants import API_LOG_PATH
   19 11:58:08 centos9 env[26642]: ModuleNotFoundError: No module named 'api'
   19 11:58:08 centos9 env[26626]: wazuh-apid: Configuration error. Exiting
   19 11:58:08 centos9 systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
  Subject: Unit process exited
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  An ExecStart= process belonging to unit wazuh-manager.service has exited.
  
  The process' exit code is 'exited' and its exit status is 1.
   19 11:58:08 centos9 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
  Subject: Unit failed
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  The unit wazuh-manager.service has entered the 'failed' state with result 'exit-code'.
   19 11:58:08 centos9 systemd[1]: Failed to start Wazuh manager.
  Subject: A start job for unit wazuh-manager.service has failed
  Defined-By: systemd
  Support: https://access.redhat.com/support
  
  A start job for unit wazuh-manager.service has finished with a failure.
  
  The job identifier is 2479 and the job result is failed.
  ```

 </details>
 
   Unlike upgrading from 4.3 to 4.4, the environment is not recoverable by performing the same steps. 
   
  <details> 
  <summary>Expand</summary>
  
   ![image](https://github.com/wazuh/wazuh/assets/13010397/eee69c79-9c24-40f9-89e8-4c4ccd86197f)
  
  </details>

## Fresh install 4.4 after the previous upgrade 

Cleaning the previous installation using this guide
https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html#uninstall

Causes a service error after installation

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/b400362c-d67a-40ad-932a-5004b2f6df74)

</details>

**Comment by fdalmaup** [comment]
# Issue Update

Replicated the upgrade error from `4.3` to `4.4` and from `4.4` to `4.5`.

## Analysis and workaround

Both for the installation of the API and framework packages, the command `/var/ossec/framework/python/bin/python3 setup.py clean --all install` is used and, depending on the case, other parameters are added such as `--prefix=` or `--wazuh-version`. The `clean --all` parameter should completely remove the `build` directory generated during package installation, but it does not happen after it (the `install` parameter). Instead, that directory is kept, and when the command is run again while upgrading, the directory is removed, only to search for it again and find that it doesn't exist. So, seeing the `clean --all` does an` os.rmdir` execution (in detail [here](https://github.com/python/cpython/blob/1528b420b33ae5c636b6016ce6c6afb0b09e7694/Lib/distutils/command/clean.py#L49-L76)), one possible solution is to perform `rm -rf framework/build` and `rm -rf api/build` before running `./install.sh` during upgrade.

## Conclusion
The`setuptools` project has stopped maintaining all direct invocations of `setup.py`, and `distutils` is [deprecated](https://peps.python.org/pep-0632/) in favor of invocations via purpose-built and/or standards-based CLI tools like [pip](https://pip.pypa.io/en/stable/), [build](https://pypa-build.readthedocs.io/en/stable/) and [tox](https://tox.wiki/en/latest/). 
We should discuss with the team the installation methods of the `api` and `framework` packages to keep them up to date and to avoid similar issues.

**Comment by fdalmaup** [comment]
# Issue Update

After talking with the team, we have decided to apply the found workaround to a patch version. The changes in the installation methods of the `api` and `framework` packages related to `setup.py` will be analyzed and carried out in a separate issue destined for a minor version.

## Upgrade with the workaround on CentOS 7

Once the workaround is applied in a development branch, when installing Wazuh from sources, the contents of the `framework` and `api` folders are:
```bash
[root@829e216aa613 wazuh]# ll framework/
total 36
drwxr-xr-x 2 root root 4096 Jun 26 13:34 dist
drwxr-xr-x 2 root root 4096 Jun 26 13:30 examples
-rw-r--r-- 1 root root    0 Jun 26 13:30 __init__.py
-rw-r--r-- 1 root root 2082 Jun 26 13:30 Makefile
-rw-r--r-- 1 root root 1655 Jun 26 13:30 requirements.txt
drwxr-xr-x 3 root root 4096 Jun 26 13:30 scripts
-rwxr-xr-x 1 root root 2017 Jun 26 13:30 setup.py
drwxr-xr-x 5 root root 4096 Jun 26 13:30 wazuh
drwxr-xr-x 2 root root 4096 Jun 26 13:34 wazuh.egg-info
drwxr-xr-x 2 root root 4096 Jun 26 13:30 wrappers
[root@829e216aa613 wazuh]# ll api/
total 36
drwxr-xr-x 7 root root 4096 Jun 26 13:30 api
drwxr-xr-x 2 root root 4096 Jun 26 13:34 api.egg-info
drwxr-xr-x 2 root root 4096 Jun 26 13:34 dist
-rwxr-xr-x 1 root root 1503 Jun 26 13:30 Makefile
drwxr-xr-x 2 root root 4096 Jun 26 13:30 scripts
drwxr-xr-x 2 root root 4096 Jun 26 13:30 service
-rwxr-xr-x 1 root root 1357 Jun 26 13:30 setup.py
drwxr-xr-x 3 root root 4096 Jun 26 13:30 test
drwxr-xr-x 2 root root 4096 Jun 26 13:30 wrappers
```

When upgrading Wazuh to a higher version which does not have the workaround, the contents of the mentioned folders are:
```bash
[root@829e216aa613 wazuh]# ll framework/
total 40
drwxr-xr-x 4 root root 4096 Jun 26 13:42 build
drwxr-xr-x 2 root root 4096 Jun 26 13:42 dist
drwxr-xr-x 2 root root 4096 Jun 26 13:30 examples
-rw-r--r-- 1 root root    0 Jun 26 13:30 __init__.py
-rw-r--r-- 1 root root 2082 Jun 26 13:30 Makefile
-rw-r--r-- 1 root root 1655 Jun 26 13:30 requirements.txt
drwxr-xr-x 3 root root 4096 Jun 26 13:37 scripts
-rwxr-xr-x 1 root root 2017 Jun 26 13:37 setup.py
drwxr-xr-x 5 root root 4096 Jun 26 13:37 wazuh
drwxr-xr-x 2 root root 4096 Jun 26 13:42 wazuh.egg-info
drwxr-xr-x 2 root root 4096 Jun 26 13:30 wrappers
[root@829e216aa613 wazuh]# ll api/
total 40
drwxr-xr-x 7 root root 4096 Jun 26 13:37 api
drwxr-xr-x 2 root root 4096 Jun 26 13:42 api.egg-info
drwxr-xr-x 4 root root 4096 Jun 26 13:42 build
drwxr-xr-x 2 root root 4096 Jun 26 13:42 dist
-rwxr-xr-x 1 root root 1503 Jun 26 13:30 Makefile
drwxr-xr-x 2 root root 4096 Jun 26 13:37 scripts
drwxr-xr-x 2 root root 4096 Jun 26 13:30 service
-rwxr-xr-x 1 root root 1357 Jun 26 13:37 setup.py
drwxr-xr-x 3 root root 4096 Jun 26 13:30 test
drwxr-xr-x 2 root root 4096 Jun 26 13:30 wrappers
```
Since the branch of the updated version does not have the workaround, the `build` folders are in the modules' directories and another update process would break if done.

**Comment by XXXLukieDukieXXX** [comment]
<img width="949" alt="image" src="https://github.com/wazuh/wazuh/assets/141261391/cd7b9ff8-c33c-4561-84dc-af19566e07a0">.

Anyone can guide me to solve this error? Thanks
