### ISSUE TITLE
Design new test suite for legacy integration tests

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#17173]
## Description

This issue aims to:

- Investigate the current framework used for legacy integration testing and propose a new design that is better structured, organized, more generic and without dead or redundant code.
- Investigate the current test structure of the legacy integration tests and propose a new design that is better structured, organized, more generic and without duplicate or dead code. For this point, the structure of vulnerability detection tests can be used as a model.

The proposed design will be presented as a result of this issue. Once approved, a new document will be created in which all of this will be documented.

**Comment by QU3B1M** [comment]
## `wazuh-testing` framework
 
The current `wazuh-qa` framework is full of duplicated and/or unused code, also its structure is not really clear, so a new file structure is proposed, it's not so different from the previous but it is cleaner starting from that we are not keeping anything from the `system` or `e2e` tests that were on the previous framework.

### New structure

#### `modules/`
To keep everything organized it is proposed to store all the module specific code inside the path `wazuh_testing/modules/` on a folder with the name of the module, so every function related to that specific module and its services will be store inside it. As example, all the code related to authd and its services must be inside  `wazuh_testing/modules/authd/`

```vim
deps
├── setup.py
└── wazuh_testing
    ...
    ├── modules
    │   ├── authd
    │   │   ├── __init__.py
    │   │   ├── callbacks.py
    │   │   └── ...
    ...
```

#### `constants/`
Previously all the constants were stored in the main `__init__.py` (and also some other places), now the idea is to store all the constants organized inside the path  `wazuh_testing/constants/` and keep everything separated on categories, for now we have `platforms`, `daemons`, &`path` where the `sockets`, `logs`, `configurations` & `binaries` can be found, but more categories could be added when needed. 

```vim
deps
├── setup.py
└── wazuh_testing
    ...
    ├── constants
    │   ├── daemons.py
    │   ├── __init__.py
    │   ├── paths
    │   │   ├── binaries.py
    │   │   ├── configurations.py
    │   │   ├── __init__.py
    │   │   ├── logs.py
    │   │   └── sockets.py
    │   └── platforms.py
    ...
```
#### `utils/`
This is the typical path where we will store our generic utilities that can be used anywhere and are not module specific. A lot of this `utils` were previously stored inside `tools/` 

```vim
deps
├── setup.py
└── wazuh_testing
    ...
    └── utils
        ├── config.py
        ├── file.py
        ├── __init__.py
        ├── services.py
        ├── sockets.py
        └── ...
```

#### `tools/`
In this path we will store all the framework's tools, like the `FileMonitor`and the `AgentSimulator` (this one is not migrated yet) and some other tools that can be added. This path already exists in the previous structure, but it is full of different things.

```vim
deps
├── setup.py
└── wazuh_testing
    ...
    ├── tools
    │   ├── __init__.py
    │   ├── file_monitor.py
    │   └── ...
    ...
```

#### `global_parameters.py`
This file stores all the session's global parameters that could be configured for each test execution.

----

#### General view

```vim
deps
├── setup.py
└── wazuh_testing
    ├── constants
    │   ├── daemons.py
    │   ├── __init__.py
    │   ├── paths
    │   │   ├── binaries.py
    │   │   ├── configurations.py
    │   │   ├── __init__.py
    │   │   ├── logs.py
    │   │   └── sockets.py
    │   └── platforms.py
    ├── global_parameters.py
    ├── __init__.py
    ├── logger.py
    ├── modules
    │   ├── analysisd
    │   │   ├── __init__.py
    │   │   ├── patterns.py
    │   │   ├── callbacks.py
    │   │   └── ...
    │   ├── authd
    │   │   ├── __init__.py
    │   │   ├── patterns.py
    │   │   ├── callbacks.py
    │   │   └── ...
    │   ...
    │   └── __init__.py
    ├── tools
    │   ├── __init__.py
    │   ├── file_monitor.py
    │   └── ...
    └── utils
        ├── config.py
        ├── file.py
        ├── __init__.py
        ├── services.py
        ├── sockets.py
        └── ...
```

**Comment by QU3B1M** [comment]
## Integration tests structure

The ITs current status is a mess, some tests are developed following one structure and some following other, also it has a lot of `xFailed` tests that were never fixed. Anyway the last test structure is not bad at all, its only matter of refactoring the older tests files with the new structure.

### New structure

The idea of ​​this structure is to keep everything in its place and reuse as much as possible avoiding duplicates and confusion about where to store things.

#### `conftest.py`

The conftests is where the `fixture` functions live, a superficial way to understand this functions is that they are in charge of the `setup` and `tear_down` of each test function or module, they can have different scopes and functionalities. For a deeper description and examples, check its [**documentation**](https://docs.pytest.org/en/6.2.x/fixture.html). The idea of the conftest is to group all the fixtures that belongs to the level where the conftest is created, to be clear, if a conftest is on the root of the test suite, it must have all the **generic** fixtures, and if it is on a very specific module test, all the fixtures should be the consumed only in that module.

```vim
tests
├── conftest.py
├── ...
└── test_<MODULE_1>
    ├── conftest.py
    ├── ...
...

```

#### `test_<MODULE>`

The test are separated by modules, so each module folder tests only the correspondent wazuh's component and its services, we could have, for example, the modules `test_authd`, `test_remoted`, etc... 
Inside each `test_module` folder we will find all the features/services related scenarios and some generic data, conftest or tests.

```vim
tests
├── ...
└── test_<MODULE_1>
    ├── conftest.py
    ├── data
    ├── __init__.py
    ├── test_<FEATURE_OR_SERVICE_1>
    │   ├── ...
    └── test_<FEATURE_OR_SERVICE_2>
        ├── ...
```

#### `test_<FEATURE_OR_SERVICE>`

This stores specific services or features test scenarios and its data. The test scenarios code are stored in the `test_<SCENARIO_X>.py` files, those files will use the data that inside `./data/config_templates/config_<SCENARIO_X>.yaml` to grab the configuration to apply for this specific scenario, and the test cases data (`inputs`, `outputs` or any other case data) are picked from the path `./data/test_cases/cases_<SCENARIO_X>.yaml`. Also there could be other extra data inside the `./data/` path to use inside the scenarios.

```vim
tests
├── ...
└── test_<MODULE_1>
    ├── ...
    ├── test_<FEATURE_OR_SERVICE_1>
    │   ├── data
    │   │   ├── config_templates
    │   │   │   └── config_<SCENARIO_1>.yaml
    │   │   └── test_cases
    │   │       └── cases_<SCENARIO_1>.yaml
    │   ├── __init__.py
    │   ├── conftest.py
    │   └── test_<SCENARIO_1>.py
    └── ...
```

#### `test_<SCENARIO>.py` example

- <details><summary><code>test_signature_id/test_valid_signature_id.py</code></summary>

    > This file is in charge to prepare and execute the test and do the assertions

    ```python
    import pytest

    from pathlib import Path

    from wazuh_testing.constants.paths.logs import OSSEC_LOG_PATH
    from wazuh_testing.modules.analysisd import patterns
    from wazuh_testing.utils.config import load_configuration_template, get_test_cases_data
    from wazuh_testing.tools.file_monitor import FileMonitor, generate_callback

    from . import CONFIGS_PATH, TEST_CASES_PATH, RULES_SAMPLE_PATH


    pytestmark = [pytest.mark.server, pytest.mark.tier(level=1)]

    # Configuration and cases data.
    configs_path = Path(CONFIGS_PATH, 'config_signature_id_values.yaml')
    cases_path = Path(TEST_CASES_PATH, 'cases_valid_signature_id.yaml')

    # test configurations.
    config_parameters, metadata, t1_case_ids = get_test_cases_data(cases_path)
    configuration = load_configuration_template(configs_path,
                                                config_parameters,
                                                metadata)


    # Test function
    @pytest.mark.parametrize('configuration, metadata', zip(configuration, metadata), ids=t1_case_ids)
    def test_valid_signature_id(configuration, metadata, set_wazuh_configuration, truncate_monitored_files,
                                prepare_custom_rules_file, restart_wazuh_function):
        '''
        description: Check that when a rule has an valid signature ID value assigned to the if_sid option, the rule is
                    not ignored.

        test_phases:
            - Setup:
                - Set wazuh configuration.
                - Copy custom rules file into manager
                - Clean logs files and restart wazuh to apply the configuration.
            - Test:
                - Check no log for "if_sid not found" is detected
                - Check no log for "empty if_sid" is detected
                - Check no log for "invalid if_sid" is detected
            - Tierdown:
                - Delete custom rule file
                - Restore configuration
                - Stop wazuh

        wazuh_min_version: 4.4.0

        tier: 1

        parameters:
            - configuration:
                type: dict
                brief: Configuration loaded from `configuration_template`.
            - metadata:
                type: dict
                brief: Test case metadata.
            - set_wazuh_configuration:
                type: fixture
                brief: Set wazuh configuration.
            - truncate_monitored_files:
                type: fixture
                brief: Truncate all the log files and json alerts files before and after the test execution.
            - prepare_custom_rules_file:
                type: fixture
                brief: Copies custom rules_file before test, deletes after test.
            - restart_wazuh_function:
                type: fixture
                brief: Restart wazuh at the start of the module to apply configuration.

        assertions:
            - Check that wazuh starts
            - Check ".*Signature ID '(\\d*)' was not found and will be ignored in the 'if_sid'.* of rule '(\\d*)'" event
            - Check ".*wazuh-testrule.*Empty 'if_sid' value. Rule '(\\d*)' will be ignored.*"

        input_description:
            - The `configuration_signature_id_values.yaml` file provides the module configuration for
            this test.
            - The `cases_signature_id_values.yaml` file provides the test cases.
        '''
        # Start monitors
        monitor_not_found = FileMonitor(OSSEC_LOG_PATH, generate_callback(patterns.SID_NOT_FOUND))
        monitor_empty = FileMonitor(OSSEC_LOG_PATH, generate_callback(patterns.EMPTY_IF_SID_RULE_IGNORED))
        monitor_invalid = FileMonitor(OSSEC_LOG_PATH, generate_callback(patterns.INVALID_IF_SID_RULE_IGNORED))

        # Check that no log appears for rules if_sid field pointing to a non existent SID
        assert not monitor_not_found.callback_result
        # Check that no log appears for rules if_sid field being empty string
        assert not monitor_empty.callback_result
        # Check that no log appears for rules if_sid field being invalid
        assert not monitor_invalid.callback_result

    ```

</details>

##### `config_<SCENARIO>.yaml` example

- <details><summary><code>data/config_templates/config_signature_id_values.yaml</code></summary>

    > All this values are configured in the `ossec.conf` so the wazuh component is prepared for the suite.
    ```yaml
    - sections:
        - section: vulnerability-detector
        elements:
            - enabled:
                value: 'no'

        - section: sca
        elements:
            - enabled:
                value: 'no'

        - section: rootcheck
        elements:
            - disabled:
                value: 'yes'

        - section: syscheck
        elements:
            - disabled:
                value: 'yes'

        - section: wodle
        attributes:
            - name: syscollector
        elements:
            - disabled:
                value: 'yes'
    ```
</details>

##### `cases_<SCENARIO>.yaml` example

- <details><summary><code>data/test_cases/cases_invalid_signature_id.yaml</code></summary>

    > All this values are consumed by the test file to do the validations and other actions.
    ```yaml
    - name: Empty signature ID - Rule ignored
    description: Check that if_sid is empty, a rule will be ignored
    configuration_parameters:
    metadata:
        rules_file: empty_signature_id_rules.xml
        is_empty: true

    - name: Invalid signature ID - Rule ignored
    description: Check that if_sid is invalid, a rule will be ignored
    configuration_parameters:
    metadata:
        rules_file: invalid_signature_id_rules.xml
        is_empty: false

    ```

</details>

----

#### General view

```vim
tests
├── conftest.py
├── pytest.ini
├── README.md
└── test_<MODULE_1>
    ├── conftest.py
    ├── data
    ├── __init__.py
    ├── test_<FEATURE_OR_SERVICE_1>
    │   ├── data
    │   │   ├── config_templates
    │   │   │   └── config_<SCENARIO_1>.yaml
    │   │   └── test_cases
    │   │       └── cases_<SCENARIO_1>.yaml
    │   ├── __init__.py
    │   ├── conftest.py
    │   └── test_<SCENARIO_1>.py
    └── test_<FEATURE_OR_SERVICE_2>
        ├── data
        │   ├── config_templates
        │   │   └── config_<SCENARIO_1>.yaml
        │   │   └── config_<SCENARIO_2>.yaml
        │   ├── extra_data
        │   │   ├── extra_data_<SCENARIO_1>.xml
        │   │   └── extra_data_<SCENARIO_2>.xml
        │   └── test_cases
        │       ├── cases_<SCENARIO_1>.yaml
        │       └── cases_<SCENARIO_2>.yaml
        ├── __init__.py
        ├── test_<SCENARIO_1>.py
        └── test_<SCENARIO_2>.py
```
