### ISSUE TITLE
Rework SCA Policy for Ubuntu Linux 20.04

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#17185]
|Wazuh version| Component | 
|---| --- |
| 4.4.x | SCA | 

Rework SCA Policy for Ubuntu Linux 20.04

- [x] Solve typos.
- [x] Increase check coverage. 
- [x] Improve rules implementation.
- [x] Improve texts.
- [x] Solve reported issues:

    - #16861
    - #16862 
    - #16860
    - #16734
    - https://github.com/wazuh/community/issues/4866

**Comment by IsExec** [comment]
Created policy yml template file for Ubuntu 20.04 v2.0.0 to replace v1.1.0

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/faa6c69beef663e541d9da6eade536bf6f86c806

Created rules for Ubuntu SCA 20.04 1.1.1.1 to 1.1.4.1

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/5406c217363e0e3286566e0d56136024cdb1bd21

Completed section 1 of Ubuntu SCA 20.04

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/4b94224bb8b69689de8b9dbee6b150821b51b09f

Ubuntu 20.04 SCA rework checks 2.1.1.1 to 2.1.4.4

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/acd104cd44f01f02646b4c1315f80208c1a1a996

Ubuntu 20.04 SCA rework checks 2.2.1 - 2.2.17

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/7f18fb55ec3d6569a37645e9697b3bd6562d92a4

Ubuntu 20.04 SCA rework checks 2.3.1 - 2.4

https://github.com/wazuh/wazuh/commit/1bebf5e10fb85655a3649768ef1987cc2cc22856

Ubuntu 20.04 SCA rework s 3.1.1 - 3.4.1.6

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/b4ebd43cb90f20e11899a0c5ea103fb65d21fec6

Completed Section 3
Ubuntu SCA rework checks 3.4.1.7 - 3.4.3.3.4

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/f091f434596814503bcde85a476103bfadc49a74

Ubuntu 20.04 SCA rework checks 4.1.1 - 4.2.4

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/0ce5e832cfba1bb2c91ad6587caab6a93481537a

Ubuntu 20.04 SCA rework 4.2.4 - 4.2.22
Ubuntu 20.04 SCA rework 4.3.1 - 4.3.7

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/a17da7f44785b319c730ac28af6f17b80ad0ac31

Ubuntu 20.04 SCA rework 4.4.1 - 4.4.5 
Ubuntu 20.04 SCA rework 4.51 - 4.5.7

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/c5adf46661870c45e1983c5f10f86b7b368a86f7

Ubuntu 20.04 SCA rework 5.1.1.1.1 - 5.1.1.7
Ubuntu 20.04 SCA rework  5.1.2.1 - 5.1.2.7, 5.1.3
Ubuntu 20.04 SCA rework 5.2.1.1 - 5.2.1.4
Ubuntu 20.04 SCA rework 5.2.2.1 - 5.2.2.3
Ubuntu 20.04 SCA rework 5.2.3.1 - 5.2.3.9

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/05e4b29b4b7ab42bf25a5f28e01eabfaae1ee088

Ubuntu 20.04 SCA rework 5.2.3.10 - 5.2.3.21
Ubuntu 20.04 SCA rework 5.2.4.1 - 5.2.4.11

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/commit/e04914bdc0772fb733100723d62349d489410acf

Completed Ubuntu 20.04 SCA S6
