### ISSUE TITLE
Refactor and migrate wazuh-db integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17209]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the wazuh-db tests. The following files are involved:

```
test_wazuh_db
├── conftest.py
├── data
│   ├── agent
│   │   ├── agent_messages.yaml
│   │   ├── fim_messages.yaml
│   │   └── syscollector_deltas_messages.yaml
│   ├── global
│   │   ├── get_groups_integrity_messages.yaml
│   │   ├── global_messages.yaml
│   │   ├── set_agent_groups.yaml
│   │   ├── sync_agent_groups_get.yaml
│   │   ├── wazuh_db_backup_command.yaml
│   │   └── wazuhdb_getconfig.yaml
│   └── wazuh_db_backups_conf.yaml
├── README.md
├── test_agent_database_version.py
├── test_db_backup.py
├── test_get_groups_integrity.py
├── test_set_agent_groups.py
├── test_sync_agent_groups_get.py
├── test_wazuhdb_getconfig.py
├── test_wazuh_db.py
└── test_wdb_backup_configs.py
```

### Tasks:

- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (i.e. internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.

**Comment by mateocervilla** [comment]
## Update
Applied some requested changes. Also, similar required changes from other PRs were made.
The tests are now finished and working.
Latest commits:
- https://github.com/wazuh/wazuh/pull/19463/commits/6ebfda19df279fee9765312f26ec8fec2dcefcaf

- https://github.com/wazuh/qa-integration-framework/pull/43/commits/04fb4203b6e2144bf68e80dc9e47ac97249e3caa

**Comment by mateocervilla** [comment]
## ETA Update

Updated due to pending review

**Comment by mateocervilla** [comment]
## Update
The required changes are being applied.
Due to higher priority issues, this will be kept on hold until they are finished.

**Comment by mateocervilla** [comment]
## Update
- Requested  changes applied.
- Fixed all failing tests.
 
### Ready for review

**Comment by ncvicchi** [comment]
Moved ETA to give time for reviewing

**Comment by mateocervilla** [comment]
ETA updated due to new requested changes, pending review and more priority issues.
