### ISSUE TITLE
Test deployment variables GH action fails to find package

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#17219]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.3 | -- | -- | -- | -- |

We have found that the GH actions that test the deployment variables can sometimes fail to download the package:
![image](https://github.com/wazuh/wazuh/assets/19505384/6561d998-f621-40ad-976e-0620a8d47469)

A race condition with AWS cache may be the cause of this problem, we need to add a retry in this step to avoid this issue in the future.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
