### ISSUE TITLE
Engine | Integrations for sources and vendors target list

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#17210]
# List of integrations to be supported by the new engine. 

### Merged

| Integration name (Decoder) | Status      | Related issue                                        | Total Output Fields | # of ECS fields | # of fields not ECS | # of not implemented fields | Notes |
| -------------------------- | ----------- | ---------------------------------------------------- | ------------------- | --------------- | ------------------- | --------------------------- | ----- |
| apache-access              | Merged | https://github.com/wazuh/wazuh-threatintel/issues/47 | 41,66               | 48              | 28                  |                             |       |
| apache-error               | Merged | https://github.com/wazuh/wazuh-threatintel/issues/47 | 41,66               | 48              | 20                  |                             |       |
| windows-powershell             | Merged | https://github.com/wazuh/wazuh-threatintel/issues/49 | 91,18               | 34              | 3                   |                             |       |
| windows-powershell-operational | Merged | https://github.com/wazuh/wazuh-threatintel/issues/49 | 96,96               | 33              | 1                   |                             |       |
| windows-security               | Merged | https://github.com/wazuh/wazuh-threatintel/issues/49 | 86,66               | 90              | 12                  |                             |       |
| windows-sysmon                 | Merged | https://github.com/wazuh/wazuh-threatintel/issues/49 | 96,96               | 33              | 1                   |                             |       |
| suricata-eve                   | Merged | https://github.com/wazuh/wazuh-threatintel/issues/48 | 67,86%              | 84              | 27                  |                             |       |
| system-syslog                   | Merged |                                             |                     |                 |                     |                             |       |

### In Final Review to be merged

| Integration name (Decoder)     | Status       | Related issue                                        | Total Output Fields | # of ECS fields | # of fields not ECS | # of not implemented fields | Notes |
| ------------------------------ | ------------ | ---------------------------------------------------- | ------------------- | --------------- | ------------------- | --------------------------- | ----- |
| system-auth                     | Final Review |            https://github.com/wazuh/wazuh-threatintel/issues/63                                 |                     |                 |                     |                             |       |

### Next

| Integration name (Decoder)      | Status       | Related issue                                        | Total Output Fields | # of ECS fields | # of fields not ECS | # of not implemented fields | Notes |
| ------------------------------- | ------------ | ---------------------------------------------------- | ------------------- | --------------- | ------------------- | --------------------------- | ----- |
| azure-activitylogs              | Final Review | https://github.com/wazuh/wazuh-threatintel/issues/52 |                     |                 |                     |                             |       |
| azure-auditlogs                 | Final Review | https://github.com/wazuh/wazuh-threatintel/issues/52 |                     |                 |                     |                             |       |
| azure-azure-shared-pipeline.yml | Final Review | https://github.com/wazuh/wazuh-threatintel/issues/52 |                     |                 |                     |                             |       |
| azure-platformlogs              | Final Review | https://github.com/wazuh/wazuh-threatintel/issues/52 |                     |                 |                     |                             |       |
| azure-signinlogs                | Final Review | https://github.com/wazuh/wazuh-threatintel/issues/52 | 86,66               | 30              | 4                   |                             |       |
| cisco-amp                       | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-asa                       | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-estreamer                 | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-ftd                       | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-ios                       | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-meraki                    | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-nexus                     | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-shared                    | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-umbrella                  | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |
| cisco-vpn                       | In Progress  | https://github.com/wazuh/wazuh-threatintel/issues/51 |                     |                 |                     |                             |       |

### Need Modification - Fields output should be updated

| Integration name (Decoder) | Status | Related issue                               | Total Output Fields | # of ECS fields | # of fields not ECS | # of not implemented fields | Notes |
| -------------------------- | ------ | ------------------------------------------- | ------------------- | --------------- | ------------------- | --------------------------- | ----- |
| audit                      | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| aws                        | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| aws-cloudtrail             | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| aws-elb                    | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| aws-s3access               | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| Ciscat                     | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| f5-bigipafm                | Merged | https://github.com/wazuh/wazuh/issues/15848 |                     |                 |                     |                             |       |
| f5-bigipapm                | Merged | https://github.com/wazuh/wazuh/issues/15848 |                     |                 |                     |                             |       |
| fortinet-clientendpoint    | Merged | https://github.com/wazuh/wazuh/issues/15850 |                     |                 |                     |                             |       |
| fortinet-firewall          | Merged | https://github.com/wazuh/wazuh/issues/15850 |                     |                 |                     |                             |       |
| fortinet-fortimail         | Merged | https://github.com/wazuh/wazuh/issues/15850 |                     |                 |                     |                             |       |
| fortinet-fortimanager      | Merged | https://github.com/wazuh/wazuh/issues/15850 |                     |                 |                     |                             |       |
| Nginx access               | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| Nginx error                | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| postgress (csv)            | Merged | https://github.com/wazuh/wazuh/issues/15723 |                     |                 |                     |                             |       |
| redis                      | Merged | https://github.com/wazuh/wazuh/issues/15849 |                     |                 |                     |                             |       |
| sonicwall-firewall         | Merged | https://github.com/wazuh/wazuh/issues/15860 |                     |                 |                     |                             |       |
| sophos-utm                 | Merged | https://github.com/wazuh/wazuh/issues/15851 |                     |                 |                     |                             |       |
| sophos-xg                  | Merged | https://github.com/wazuh/wazuh/issues/15851 |                     |                 |                     |                             |       |

### Not started

| Integration name (Decoder)      | Status      | Related issue                               | Total Output Fields | # of ECS fields | # of fields not ECS | # of not implemented fields | Notes |
| ------------------------------- | ----------- | ------------------------------------------- | ------------------- | --------------- | ------------------- | --------------------------- | ----- |
| apple                           | Not Started | https://github.com/wazuh/wazuh/issues/15884 |                     |                 |                     |                             |       |
| activemq-audit                  | Not Started |                                             |                     |                 |                     |                             |       |
| activemq-log                    | Not Started |                                             |                     |                 |                     |                             |       |
| aws-cloudwatch                  | Not Started |                                             |                     |                 |                     |                             |       |
| aws-ec2                         | Not Started |                                             |                     |                 |                     |                             |       |
| aws-eks-authenticator           | Not Started |                                             |                     |                 |                     |                             |       |
| aws-vpcflow                     | Not Started |                                             |                     |                 |                     |                             |       |
| awsfargate-log                  | Not Started |                                             |                     |                 |                     |                             |       |
| barracuda-spamfirewall          | Not Started |                                             |                     |                 |                     |                             |       |
| barracuda-waf                   | Not Started |                                             |                     |                 |                     |                             |       |
| bluecoat-director               | Not Started |                                             |                     |                 |                     |                             |       |
| cef-log                         | Not Started |                                             |                     |                 |                     |                             |       |
| checkpoint-firewall             | Not Started |                                             |                     |                 |                     |                             |       |
| coredns-log                     | Not Started |                                             |                     |                 |                     |                             |       |
| crowdstrike-falcon              | Not Started |                                             |                     |                 |                     |                             |       |
| cyberarkpas-audit               | Not Started |                                             |                     |                 |                     |                             |       |
| cylance-protect                 | Not Started |                                             |                     |                 |                     |                             |       |
| elasticsearch-audit             | Not Started |                                             |                     |                 |                     |                             |       |
| elasticsearch-deprecation       | Not Started |                                             |                     |                 |                     |                             |       |
| elasticsearch-gc                | Not Started |                                             |                     |                 |                     |                             |       |
| elasticsearch-server            | Not Started |                                             |                     |                 |                     |                             |       |
| elasticsearch-slowlog           | Not Started |                                             |                     |                 |                     |                             |       |
| envoyproxy-log                  | Not Started |                                             |                     |                 |                     |                             |       |
| gcp-audit                       | Not Started |                                             |                     |                 |                     |                             |       |
| gcp-firewall                    | Not Started |                                             |                     |                 |                     |                             |       |
| gcp-vpcflow                     | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-uadmin         | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-uconfig        | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-udrive         | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-ugroups        | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-uingest        | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-ulogin         | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-usaml          | Not Started |                                             |                     |                 |                     |                             |       |
| google_workspace-user_accounts  | Not Started |                                             |                     |                 |                     |                             |       |
| haproxy-log                     | Not Started |                                             |                     |                 |                     |                             |       |
| ibmmq-errorlog                  | Not Started |                                             |                     |                 |                     |                             |       |
| icinga-debug                    | Not Started |                                             |                     |                 |                     |                             |       |
| icinga-main                     | Not Started |                                             |                     |                 |                     |                             |       |
| icinga-startup                  | Not Started |                                             |                     |                 |                     |                             |       |
| iis-access                      | Not Started |                                             |                     |                 |                     |                             |       |
| iis-error                       | Not Started |                                             |                     |                 |                     |                             |       |
| imperva-securesphere            | Not Started |                                             |                     |                 |                     |                             |       |
| infoblox-nios                   | Not Started |                                             |                     |                 |                     |                             |       |
| iptables-log                    | Not Started |                                             |                     |                 |                     |                             |       |
| juniper-junos                   | Not Started |                                             |                     |                 |                     |                             |       |
| juniper-netscreen               | Not Started |                                             |                     |                 |                     |                             |       |
| juniper-srx                     | Not Started |                                             |                     |                 |                     |                             |       |
| kafka-log                       | Not Started |                                             |                     |                 |                     |                             |       |
| kibana-audit                    | Not Started |                                             |                     |                 |                     |                             |       |
| kibana-log                      | Not Started |                                             |                     |                 |                     |                             |       |
| logstash-log                    | Not Started |                                             |                     |                 |                     |                             |       |
| logstash-slowlog                | Not Started |                                             |                     |                 |                     |                             |       |
| microsoft-defender_atp          | Not Started |                                             |                     |                 |                     |                             |       |
| microsoft-dhcp                  | Not Started |                                             |                     |                 |                     |                             |       |
| microsoft-m365_defender         | Not Started |                                             |                     |                 |                     |                             |       |
| misp-threat                     | Not Started |                                             |                     |                 |                     |                             |       |
| mongodb-log                     | Not Started |                                             |                     |                 |                     |                             |       |
| mssql-log                       | Not Started |                                             |                     |                 |                     |                             |       |
| mysql-error                     | Not Started |                                             |                     |                 |                     |                             |       |
| mysql-slowlog                   | Not Started |                                             |                     |                 |                     |                             |       |
| mysqlenterprise-audit           | Not Started |                                             |                     |                 |                     |                             |       |
| nats-log                        | Not Started |                                             |                     |                 |                     |                             |       |
| netflow-dashboards.yml          | Not Started |                                             |                     |                 |                     |                             |       |
| netflow-log                     | Not Started |                                             |                     |                 |                     |                             |       |
| netscout-sightline              | Not Started |                                             |                     |                 |                     |                             |       |
| o365-audit                      | Not Started |                                             |                     |                 |                     |                             |       |
| okta-system                     | Not Started |                                             |                     |                 |                     |                             |       |
| oracle-database_audit           | Not Started |                                             |                     |                 |                     |                             |       |
| osquery-result                  | Not Started |                                             |                     |                 |                     |                             |       |
| panw-panos                      | Not Started |                                             |                     |                 |                     |                             |       |
| pensando-dfw                    | Not Started |                                             |                     |                 |                     |                             |       |
| postgresql-log                  | Not Started |                                             |                     |                 |                     |                             |       |
| proofpoint-emailsecurity        | Not Started |                                             |                     |                 |                     |                             |       |
| rabbitmq-log                    | Not Started |                                             |                     |                 |                     |                             |       |
| radware-defensepro              | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-apex-rest            | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-login-rest           | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-login-stream         | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-logout-rest          | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-logout-stream        | Not Started |                                             |                     |                 |                     |                             |       |
| salesforce-setupaudittrail-rest | Not Started |                                             |                     |                 |                     |                             |       |
| santa-log                       | Not Started |                                             |                     |                 |                     |                             |       |
| snort-log                       | Not Started |                                             |                     |                 |                     |                             |       |
| snyk-audit                      | Not Started |                                             |                     |                 |                     |                             |       |
| snyk-vulnerabilities            | Not Started |                                             |                     |                 |                     |                             |       |
| squid-log                       | Not Started |                                             |                     |                 |                     |                             |       |
| ssh                             | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-abusemalware        | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-abuseurl            | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-anomali             | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-anomalithreatstream | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-malwarebazaar       | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-misp                | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-otx                 | Not Started |                                             |                     |                 |                     |                             |       |
| threatintel-threatq             | Not Started |                                             |                     |                 |                     |                             |       |
| tomcat-log                      | Not Started |                                             |                     |                 |                     |                             |       |
| traefik-access                  | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-capture_loss               | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-connection                 | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-dce_rpc                    | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-dhcp                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-dnp3                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-dns                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-dpd                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-files                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ftp                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-http                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-intel                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-irc                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-kerberos                   | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-modbus                     | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-mysql                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-notice                     | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ntlm                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ntp                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ocsp                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-pe                         | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-radius                     | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-rdp                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-rfb                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-signature                  | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-sip                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-smb_cmd                    | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-smb_files                  | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-smb_mapping                | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-smtp                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-snmp                       | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-socks                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ssh                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-ssl                        | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-stats                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-syslog                     | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-traceroute                 | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-tunnel                     | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-weird                      | Not Started |                                             |                     |                 |                     |                             |       |
| zeek-x509                       | Not Started |                                             |                     |                 |                     |                             |       |
| zookeeper-audit                 | Not Started |                                             |                     |                 |                     |                             |       |
| zookeeper-log                   | Not Started |                                             |                     |                 |                     |                             |       |
| zscaler-zia                     | Not Started |                                             |                     |                 |                     |                             |       |
| zoom-webhook                    | Not Started |                                             |                     |                 |                     |                             |       |

**Comment by davidjiglesias** [comment]
To be continued in the future design and development for the new engine.
