### ISSUE TITLE
rootcheck on AWS False Positive but configurable ignore rules

### ISSUE THREAD

**Issue by garyfeltham** [wazuh/wazuh#173]
Hi guys,

I'm getting a false positive when running a root check as

> Rule: 510 fired (level 7) -> "Host-based anomaly detection event (rootcheck)."
> Portion of the log(s):
> 
> File '/dev/.blkid.tab' present on /dev. Possible hidden file.
> title: File present on /dev.
> file: /dev/.blkid.tab

Configuration is standard as

<rootcheck>
  <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
  <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>
  <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
  <system_audit>/var/ossec/etc/shared/cis_debian_linux_rcl.txt</system_audit>
</rootcheck>

The file /dev/.blkid.tab as I understand, is created by AWS to mount volumes on the device
`<device DEVNO="0xca00" TIME="1503999931.820549" LABEL="cloudimg-rootfs" UUID="**redacted**" TYPE="ext4">/dev/xvda</device>`

it is constantly being updated and therefore has been added as a FIM ignore rule.

The rootkit alert picks up that the file is present howeve as I understand there is no way to add a false positive in configuration.

The source file `src/rootcheck/check_rc_dev.c` seems to have this ability hard coded

```const char *(ignore_dev[]) = {"MAKEDEV", "README.MAKEDEV",
                                  "MAKEDEV.README", ".udevdb",
                                  ".udev.tdb", ".initramfs-tools",
                                  "MAKEDEV.local", ".udev", ".initramfs",
                                  "oprofile", "fd", "cgroup",```

or

```/* Full path ignore */
    const char *(ignore_dev_full_path[]) = {"/dev/shm/sysconfig",
                                            "/dev/bus/usb/.usbfs",
                                            "/dev/shm",
                                            "/dev/gpmctl",
                                            NULL
                                           };
```

It would be nice to be able to configure these in a .txt file or within the ossec.xml.

Am I missing a configuration option?

**Comment by snaow** [comment]
Hi @garyfeltham,

You are right, some rootcheck settings (as directory scanned) are hardcoded, we plan to move them out to a configuration file, it could be a txt file or probably we could use ossec.conf.
Creating a while-list for certain directories will be perfect.

Aside of that, you can create a rule to ignore/silence those alerts, following these steps:

Create a local rule at `/var/ossec/etc/rules/local_rules.xml` like this one:

```
<rule id="100001" level="0">
  <if_sid>510</if_sid>
  <match>/dev/.blkid.tab</match> 
  <description>Ignore /dev/.blkid.tab</description> 
</rule>
```

Let us know if it works.

Best regards,
Pedro.

**Comment by garyfeltham** [comment]
Thanks for the tip, I have applied the silencing rule.

**Comment by Zenidd** [comment]
Hello @garyfeltham,

It seems that they have solved your query, so i'm closing this issue. If you have any other do not hesitate to open another issue.

Kind regards,

Juan Pablo Sáez
