### ISSUE TITLE
3.7 default group worker files

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1731]
## Bug report

**OS**
_Ubuntu16/CentOS7/RHEL7/AIX.._

**Wazuh version**
_3.7.0-10_

**Wazuh API version**
_3.7.0_

**Install type**
_manager/agent_

**Install method**
_packages and sources_

Bug description
----------------

When the default group is part of a multigroup, all the files appear on the worker (only merged.mg must appear)

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/1732 solves the issue

**Comment by vikman90** [comment]
The PR #1732 indeed prevents Remoted from re-creating the merged files on the worker nodes. However, it always prevents Remoted from loading the group information into memory, this makes it unable to send the shared configuration to an agent that belongs to multiple groups.
