### ISSUE TITLE
Create SCA Policy for Debian Linux 12

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#17325]
## Main tasks

- [x] Use the latest CIS benchmark PDF - CIS Debian Linux 12
- [x] Verify IDs numbers.
- [x] Verify texts are correct: Title, Description, Rationale and Remediation.
- [x] Verify Compliance: CIS, CIS_CSC.
- [x] Verify condition and rules:
  - [x] To Pass.
  - [x] To Fail.
 
### Syntax and semantic

- [x] a) ID of each policy must be contiguous.
- [x] b) The order and format set in [Documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html) must be respected.
- [x] c) YML must be valid to avoid errors.

### Content

- [x] a) Compare each check with its analog from CIS Benchmark.
- [x] b) Try maintaining each rule as similar as possible with the `Audit` section from the CIS check.
- [x] c) Check that the commands provide the expected output.
- [x] d) When a failure is discovered, check similar policies to avoid repetition of the issue.

### Unit testing

- [x] a) Output from `ossec.log` after the SCA scan and a raw output of the result of the checks.

```
2023/12/14 12:12:57 sca: INFO: Module started.
2023/12/14 12:12:57 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_debian12.yml'
2023/12/14 12:12:57 sca: INFO: Starting Security Configuration Assessment scan.
2023/12/14 12:12:57 wazuh-modulesd:syscollector: INFO: Module started.
2023/12/14 12:12:57 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/12/14 12:12:57 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_debian12.yml'
2023/12/14 12:12:57 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

<details><summary>Tests results</summary>
<p>

#### Analysisd (server or local)
analysisd.debug=2

#### Auth daemon debug (server)
authd.debug=0

#### Exec daemon debug (server, local, or Unix agent)
execd.debug=0

#### Monitor daemon debug (server, local, or Unix agent)
monitord.debug=0

#### Log collector (server, local or Unix agent)
logcollector.debug=0

#### Integrator daemon debug (server, local, or Unix agent)
integrator.debug=0

#### Unix agentd
agent.debug=2

</p>
</details>

### Deployment

- [x] a) If the policy it's new, it must be added to the `sca.files` templates.
- [x] b) If the OS has many supported SCA policies, a policy must be set as the default policy. ([as example](https://github.com/wazuh/wazuh/blob/master/etc/templates/config/centos/sca.files))

### Documentation

- [x] a) Ensure documentation SCA list includes the created or updated SCA.

**Comment by jk-olaoluwa** [comment]
### Update 28/09/2023

#### Setting up environment for test

#### Downloaded PDF for conversion to YAML

#### Encountered errors with automated YAML generation, troubleshooting errors

**Comment by IsExec** [comment]
## Review Update - 03/11/2023
The Draft PDF is actively been worked on and a number of changes have been made since the start of the creation of the YAML file.

For example: The title for 1.1.1.1 changed from [unknown or deleted] to 'Ensure cramfs kernel module is not available' on the 25th October 2023. https://workbench.cisecurity.org/sections/2287793/recommendations/3661176

The compliance in the current Draft has control version 8 included but the YAML file has only 7

**Comment by IsExec** [comment]
## Review Update - 06/11/2023

## Section 1 🔴
  - <details><summary>1.1.2 Ensure /tmp is configured (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Checks should not be implemented due to the limitation of SCA to check A and (B or C). Or it is implemented with the condition any;
                Expected: - "c:mount -> r:tmpfs on /tmp type tmpfs"
                          - "f:/etc/fstab -> !r:^\s*\t*# && r:tmpfs /tmp tmpfs" 
                          - "c:systemctl is-enabled tmp.mount -> r:^enabled"
    </details>

  - <details><summary>1.1.3 Ensure nodev option set on /tmp partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v "nodev" takes input line by line, and outputs only the lines in which nodev does not appear)
                current: - "c:mount -> r:tmpfs on /tmp type tmpfs && r:nodev"
                Expected: - "not c:mount -> r:\s*/tmp\s && !r:nodev"
    </details>

  - <details><summary>1.1.4 Ensure nosuid option set on /tmp partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v "nosuid" takes input line by line, and outputs only the lines in which nosuid does not appear)
                current: - "c:mount -> r:tmpfs on /tmp type tmpfs && r:nosuid"
                Expected: - "not c:mount -> r:\s*/tmp\s && !r:nosuid"
    </details>

  - <details><summary>1.1.5 Ensure noexec option set on /tmp partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v "noexec" takes input line by line, and outputs only the lines in which noexec does not appear)
                current: - "c:mount -> r:tmpfs on /tmp type tmpfs && r:noexec"
                Expected: - "not c:mount -> r:\s*/tmp\s && !r:noexec"
    </details>

  - <details><summary>1.1.8 Ensure nodev option set on /var/tmp partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v "nodev" takes input line by line, and outputs only the lines in which nodev does not appear)
                current: - 'c:mount -> r:\S+ on /var/tmp type ext4 && r:nodev'
                Expected: - "not c:mount -> r:\s*/var/tmp\s && !r:nodev"
    </details>

  - <details><summary>1.1.10 Ensure noexec option set on /var/tmp partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v "noexec" takes input line by line, and outputs only the lines in which noexec does not appear)
                current: - 'c:mount -> r:\S+ on /var/tmp type ext4 && r:noexec'
                Expected: - 'not c:mount -> r:\s*/var/tmp\s && !r:noexec'
    </details>

  - <details><summary>1.1.14 Ensure nodev option set on /home partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v 'nodev' takes input line by line, and outputs only the lines in which nodev does not appear)
                current: - "c:mount -> r:/dev/xvdf1 on /home type ext4 && r:nodev"
                Expected: - 'not c:mount -> r:\s*/var/tmp\s && !r:nodev'
    </details>

  - <details><summary>1.1.15 Ensure nodev option set on /dev/shm partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v 'nodev' takes input line by line, and outputs only the lines in which nodev does not appear)
                current: - - "c:mount -> r:tmpfs on /dev/shm type tmpfs && r:nodev"
                Expected: - 'not c:mount -> r:\s*/dev/shm\s && !r:nodev'
    </details>

  - <details><summary>1.1.16 Ensure nosuid option set on /dev/shm partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v 'nosuid' takes input line by line, and outputs only the lines in which nosuid does not appear)
                current: - "c:mount -> r:tmpfs on /dev/shm type tmpfs && r:nosuid"
                Expected: - 'not c:mount -> r:\s*/dev/shm\s && !r:nosuid'
    </details>

  - <details><summary>1.1.17 Ensure noexec option set on /dev/shm partition (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
                Due to the grep -v (grep -v 'noexec' takes input line by line, and outputs only the lines in which noexec does not appear)
                current: - "c:mount -> r:tmpfs on /dev/shm type tmpfs && r:noexec"
                Expected: - 'not c:mount -> r:\s*/dev/shm\s && !r:noexec'
    </details>

  - <details><summary>1.3.2 Ensure sudo commands use pty (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🔴 no http reference in the PDF
            - Compliance:     🟢
            - Rules:          🟢
    </details>

  - <details><summary>1.6.4 Ensure core dumps are restricted (Automated)
     🔴  </summary>

            - Commented title: The commented heading should be # 1.6.4 Ensure core dumps are restricted (Automated) and not # 1.6.4 Ensure prelink is disabled (Automated)
            - Id:             
            - Title:          🔴 Current: Ensure prelink is disabled.
                                  Expected: Ensure core dumps are restricted
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
            Check should not be implemented. Rules depend on the logic (A or B) and C and (D or E) as the configuration could be in any of /etc/sysctl.conf or /etc/sysctl.d/*
    </details>

  - <details><summary>1.7.1.1 Ensure AppArmor is installed (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🔴 Different from the PDF
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢 no http reference in the PDF
            - Compliance:     🔴 Wrong complaince (YAML - cis_csc_v7: ["5.1"]; PDF - cis_csc_v7: ["14.6"])
            - Rules:          🟢
    </details>

  - <details><summary>1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
              Current: - 'f:/boot/grub/grub.cfg -> r:apparmor=1'
              Expected: - 'not f:/boot/grub/grub.cfg -> r:\s*linux && !r:apparmor=1'
              Current: - 'f:/boot/grub/grub.cfg -> r:security=apparmor'
              Expected - 'not f:/boot/grub/grub.cfg -> r:\s*linux && !r:security=apparmor'
    </details>

  - <details><summary>1.9 Ensure GDM is removed or login is configured (Automated)
     🔴  </summary>

            - Id:             
            - Title:          🟢
            - Description:    🟢
            - Rationale:      🟢
            - Impact:         🟢
            - Remediation:    🟢
            - References:     🟢
            - Compliance:     🟢
            - Rules:          🔴
              Rule 2: Current:       - 'f:/etc/gdm3/greeter.dconf-defaults -> r:banner-message-enable=true | banner-message-text=\S+ | disable-user-list=true'
              Expected: - 'f:/etc/gdm3/greeter.dconf-defaults -> r:banner-message-enable=true'
                  - 'f:/etc/gdm3/greeter.dconf-defaults -> r:banner-message-text=\S+'
                  - 'f:/etc/gdm3/greeter.dconf-defaults -> r:disable-user-list=true'
    </details>

**Comment by jk-olaoluwa** [comment]
## Update 07/11/2023

Section 1 🔴
1.1.2 Ensure /tmp is configured (Automated) 🔴 - Solved
1.1.3 Ensure nodev option set on /tmp partition (Automated) 🔴 - Solved
1.1.4 Ensure nosuid option set on /tmp partition (Automated) 🔴 - Solved
1.1.5 Ensure noexec option set on /tmp partition (Automated) 🔴 - Solved
1.1.8 Ensure nodev option set on /var/tmp partition (Automated) 🔴 - Solved
1.1.10 Ensure noexec option set on /var/tmp partition (Automated) 🔴 - Solved
1.1.14 Ensure nodev option set on /home partition (Automated) 🔴 - Solved
1.1.15 Ensure nodev option set on /dev/shm partition (Automated) 🔴 - Solved
1.1.16 Ensure nosuid option set on /dev/shm partition (Automated) 🔴 - Solved
1.1.17 Ensure noexec option set on /dev/shm partition (Automated) 🔴 - Solved
1.3.2 Ensure sudo commands use pty (Automated) 🔴 - Solved
1.6.4 Ensure core dumps are restricted (Automated) 🔴 - Solved
1.7.1.1 Ensure AppArmor is installed (Automated) 🔴 - Solved
1.7.1.2 Ensure AppArmor is enabled in the bootloader configuration (Automated) 🔴 - Solved
1.9 Ensure GDM is removed or login is configured (Automated) 🔴 - Solved

**Comment by ooniagbi** [comment]
Reviewed and added two fixes:

1. [Fix duplicate ids](https://github.com/wazuh/wazuh/pull/17565/commits/dabf593443186bd128c997fa3b81a6fabdb83678)
2. [Add Debian 11 and 12](https://github.com/wazuh/wazuh/pull/17565/commits/cddff85038a4ba75460bee8e3fab1df22185f1e5)

**Comment by ooniagbi** [comment]
Merged https://github.com/wazuh/wazuh/pull/17565

**Comment by ooniagbi** [comment]
# Reassign this issue to 4.8.2

## Threat intel team
- [ ] Remove ruleset/sca/debian/cis_debian12.yml file from 4.8.0 branch
- [ ] Remove etc/templates/config/debian/12/sca.files file from 4.8.0 branch
- [ ] Remove changes made to etc/templates/config/generic/sca.manager.files in 4.8.0
- [ ] Reassign issue to the new release

## Core team
- [ ] Remove changes made to wazuh-packages
