### ISSUE TITLE
Rework SCA Policy for Microsoft Windows Server 2016

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#17338]
|Wazuh version| Component | 
|---| --- |
| 4.8.1 | SCA | 

Rework SCA Policy for Microsoft Windows Server 2016 RTM

- [x] Solve typos.
- [x] Increase check coverage. 
- [x] Improve rules implementation.
- [x] Improve texts.
- [ ] Solve reported issues.
    - [ ] https://github.com/wazuh/wazuh/issues/16842 (This is still being researched)
- [x] Fix the check "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'. (Automated)":
- [x] Fix the check "Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only). (Automated)"

**Comment by jk-olaoluwa** [comment]
## Update 07/11/2023

Set up environment for testing
Generated YAML file from CIS PDF

**Comment by ooniagbi** [comment]
To be reviewed by @Johnng007

**Comment by Johnng007** [comment]
**16/01/2024**
Windows Server 2016 Environment Setup for Testing.

**Comment by jk-olaoluwa** [comment]
**Update 22/01/204**

Include The Language Disclaimer 🔴 - solved by @Johnng007 
Format Your SCA File 🔴 - solved by @Johnng007 

1.1.2 (L1) Ensure 'Maximum password age' is set to '365 or fewer days, but not 0'. (Automated) 🔴
1.1.3 (L1) Ensure 'Minimum password age' is set to '1 or more day(s)'. (Automated) - Not Implemented 🔴
1.1.4 (L1) Ensure 'Minimum password length' is set to '14 or more character(s)'. (Automated) - Not Implemented 🔴
18/01/2024

1.2.1 (L1) Ensure 'Account lockout duration' is set to '15 or more minute(s)'. (Automated) - Not Implemented 🔴
1.2.2 (L1) Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0'. (Automated) - Not Implemented 🔴
1.2.4 (L1) Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'. (Automated) - Not Implemented 🔴

**Comment by Johnng007** [comment]
Fix for Issue #21298

`  # (L1) Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'. (Automated)
  - id: 15521
    title: "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'."
    description: "This policy setting determines the maximum allowable age for a computer account password. By default, domain members automatically change their domain passwords every 30 days. If you increase this interval significantly so that the computers no longer change their passwords, an attacker would have more time to undertake a brute force attack against one of the computer accounts. The recommended state for this setting is: 30 or fewer days, but not 0. Note: A value of 0 does not conform to the benchmark as it disables maximum password age. Note #2: Some problems can occur as a result of machine account password expiration, particularly if a machine is reverted to a previous point-in-time state, as is common with virtual machines. Depending on how far back the reversion is, the older machine account password stored on the machine may no longer be recognized by the domain controllers, and therefore the computer loses its domain trust. This can also disrupt non-persistent VDI implementations, and devices with write filters that disallow permanent changes to the OS volume. Some organizations may choose to exempt themselves from this recommendation and disable machine account password expiration for these situations."
    rationale: "In Active Directory-based domains, each computer has an account and password just like every user. By default, the domain members automatically change their domain password every 30 days. If you increase this interval significantly, or set it to 0 so that the computers no longer change their passwords, an attacker will have more time to undertake a brute force attack to guess the password of one or more computer accounts."
    impact: "None - this is the default behavior."
    remediation: "To establish the recommended configuration via GP, set the following UI path to 30 or fewer days, but not 0: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Domain member: Maximum machine account password age."
    references:
      - "https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-member-maximum-machine-account-password-age"
    compliance:
      - cis: ["2.3.6.5"]
      - cis_csc_v8: ["5.2"]
      - cmmc_v2.0: ["IA.L2-3.5.7"]
      - pci_dss_v4.0: ["2.2.2", "8.3.5", "8.3.6", "8.6.3"]
      - soc_2: ["CC6.1"]
    condition: all
    rules:
	
	WRONG RULE
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare <= 30'
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare > 0'
	  
	CORRECT RULE
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge -> 30'
      - 'not r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge -> 0'
	  
	  
	  
	  
  # (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 15509
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - "https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status"
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: any
    rules:
      - 'c:net user guest -> r:Account active\s+No'
      - "c:net user guest -> r:The user name could not be found."`

**Comment by ooniagbi** [comment]
Test result:

```
2024/02/07 15:39:50 sca[924] wm_sca.c:2598 at wm_sca_send_summary(): DEBUG: Sending summary event for file: 'cis_win2016.yml'
2024/02/07 15:39:50 sca[924] wm_sca.c:271 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"summary","scan_id":1460571131,"name":"CIS Microsoft Windows Server 2016 v2.0.0","policy_id":"cis_win2016","file":"cis_win2016.yml","description":"This document provides prescriptive guidance for establishing a secure configuration posture for Microsoft Windows Server 2016.","references":"https://www.cisecurity.org/cis-benchmarks/","passed":47,"failed":277,"invalid":10,"total_checks":334,"score":14.506173133850098,"start_time":1707320364,"end_time":1707320387,"hash":"9f370cdf5387965736561917d2dcc7b43f8e0fe84e60b10827d16a44cdb2927e","hash_file":"efc34735f10612074740a3877a7c9b244674bfca335cd76afed472a67a99c4a6","first_scan":1}
```

**Comment by ooniagbi** [comment]
PR reviewed and merged!
