### ISSUE TITLE
Rework SCA Policy for Microsoft Windows Server 2022

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#17339]
|Wazuh version| Component | 
|---| --- |
| 4.8.1 | SCA | 

Rework SCA Policy for Microsoft Windows Server 2022

- [x] Solve typos.
- [x] Increase check coverage. 
- [x] Improve rules implementation.
- [x] Improve texts.
- [x] Solve reported issues.
- [x] Fix the check "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'. (Automated)":
- [x] Fix the check "Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only). (Automated)"

- https://github.com/wazuh/external-devel-requests/issues/522

**Comment by IsExec** [comment]
## Update - 18/12/2023

https://github.com/wazuh/wazuh/pull/20929/commits/91654ce4a0f450e43c3684dd3828819c1264bd4d
Windows server 2022 SCA rework Policy, requirements and checks without rules

**Comment by ooniagbi** [comment]
To be reviewed by @jk-olaoluwa

**Comment by jk-olaoluwa** [comment]
## Update 16/01/2024
Environment Setup in progress

**Comment by jk-olaoluwa** [comment]
**Update 22/01/2024**
 - completed envoronment setup

**Upate 23/01/2024**

- 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)' (Automated) 🟢 
- 1.1.2 (L1) Ensure 'Maximum password age' is set to '365 or fewer days, but not 0' (Automated) 🟢 
- 1.1.3 (L1) Ensure 'Minimum password age' is set to '1 or more day(s)' (Automated) 🟢 
- 1.1.4 (L1) Ensure 'Minimum password length' is set to '14 or more character(s)' (Automated) 🟢 
- 1.1.5 (L1) Ensure 'Password must meet complexity requirements' is set to 'Enabled' (Automated) 🟢 
- 1.1.6 (L1) Ensure 'Relax minimum password length limits' is set to 'Enabled' (Automated) 🟢

**Comment by IsExec** [comment]
## Fix Update - 24/01/2023

### All Identified issues for 23/01/2023 and 23/01/2024 https://github.com/wazuh/wazuh/issues/17339#issuecomment-1907780364 fixed
https://github.com/wazuh/wazuh/pull/20929/commits/fd74f016ff25cfe1eb4bffd2fa4cb85b921d85c6

**Comment by jk-olaoluwa** [comment]
### ongoing

![image](https://github.com/wazuh/wazuh/assets/69200476/79dc5eda-8f79-4e8a-9c7f-d565056f137c)

**Comment by Johnng007** [comment]
Fix for Issue https://github.com/wazuh/wazuh/issues/21298

  # (L1) Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'. (Automated)
  - id: 15521
    title: "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'."
    description: "This policy setting determines the maximum allowable age for a computer account password. By default, domain members automatically change their domain passwords every 30 days. If you increase this interval significantly so that the computers no longer change their passwords, an attacker would have more time to undertake a brute force attack against one of the computer accounts. The recommended state for this setting is: 30 or fewer days, but not 0. Note: A value of 0 does not conform to the benchmark as it disables maximum password age. Note #2: Some problems can occur as a result of machine account password expiration, particularly if a machine is reverted to a previous point-in-time state, as is common with virtual machines. Depending on how far back the reversion is, the older machine account password stored on the machine may no longer be recognized by the domain controllers, and therefore the computer loses its domain trust. This can also disrupt non-persistent VDI implementations, and devices with write filters that disallow permanent changes to the OS volume. Some organizations may choose to exempt themselves from this recommendation and disable machine account password expiration for these situations."
    rationale: "In Active Directory-based domains, each computer has an account and password just like every user. By default, the domain members automatically change their domain password every 30 days. If you increase this interval significantly, or set it to 0 so that the computers no longer change their passwords, an attacker will have more time to undertake a brute force attack to guess the password of one or more computer accounts."
    impact: "None - this is the default behavior."
    remediation: "To establish the recommended configuration via GP, set the following UI path to 30 or fewer days, but not 0: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Domain member: Maximum machine account password age."
    references:
      - "https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/domain-member-maximum-machine-account-password-age"
    compliance:
      - cis: ["2.3.6.5"]
      - cis_csc_v8: ["5.2"]
      - cmmc_v2.0: ["IA.L2-3.5.7"]
      - pci_dss_v4.0: ["2.2.2", "8.3.5", "8.3.6", "8.6.3"]
      - soc_2: ["CC6.1"]
    condition: all
    rules:
	
	WRONG RULE
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare <= 30'
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare > 0'
	  
	CORRECT RULE
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge -> 30'
      - 'not r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Netlogon\Parameters -> MaximumPasswordAge -> 0'
	  
	  
	  
	  
  # (L1) Ensure 'Accounts: Guest account status' is set to 'Disabled'. (Automated)
  - id: 15509
    title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."
    description: "This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings."
    rationale: "The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data."
    impact: "All network users will need to authenticate before they can access shared resources. If you disable the Guest account and the Network Access: Sharing and Security Model option is set to Guest Only, network logons, such as those performed by the Microsoft Network Server (SMB Service), will fail. This policy setting should have little impact on most organizations because it is the default setting in Microsoft Windows 2000, Windows XP, and Windows Server™ 2003."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status."
    references:
      - "https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/accounts-guest-account-status"
    compliance:
      - cis: ["2.3.1.2"]
      - cis_csc_v8: ["4.7"]
      - cis_csc_v7: ["16.8"]
      - iso_27001-2013: ["A.9.2.1"]
      - pci_dss_v3.2.1: ["2.1", "2.1.1"]
      - pci_dss_v4.0: ["2.2.2", "2.3.1"]
      - soc_2: ["CC6.3"]
    condition: any
    rules:
      - 'c:net user guest -> r:Account active\s+No'
      - "c:net user guest -> r:The user name could not be found."

**Comment by Johnng007** [comment]
Review LGTM.

**Comment by IsExec** [comment]
## Update - 09/02/2024

Fixed a number of issues
https://github.com/wazuh/wazuh/pull/20929/commits/d4689a51736edab92c17da58c222449c5a309ff8

- Reworked to reduce the Not Applicable due to missing registry keys from 3 to 0

![image](https://github.com/wazuh/wazuh/assets/121132106/202081dc-83a7-4814-ad7d-994c740e339c)

![image](https://github.com/wazuh/wazuh/assets/121132106/64a84eaa-593e-48a8-a786-600378e1c61b)

- 1.1.5 (L1) Ensure 'Password must meet complexity requirements' is set to 'Enabled'. (Automated) - Not Implemented

- Regularized ID

**Comment by jk-olaoluwa** [comment]
### Feedback 12/02/2023
 - Reviewed 8 random checks and checks passed and failed according to SCA specifications

**Comment by ooniagbi** [comment]
## Initial test result
![image](https://github.com/wazuh/wazuh/assets/97736018/bcf74764-8643-4b86-891e-63096bb9af75)

**Comment by ooniagbi** [comment]
# Windows server 2022 SCA rework review

- I selected the two checks below for testing.

## 27004 (1.1.6) 🟢 

## 27063 (2.3.11.7) 🟢

New results after changing OS settings to pass the two checks:
![image](https://github.com/wazuh/wazuh/assets/97736018/7d74d61e-8267-42ae-ba54-349dddcf48f3)

**Comment by ooniagbi** [comment]
# Windows server 2022 SCA rework review

## Check that other reported issues have been fixed

-  Fix the check "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'. (Automated)":
Check ID: 27026
CIS: 2.3.6.5
Status: The check does not work as expected 🔴.  It fails when the value is set to 20.

**Comment by IsExec** [comment]
## Update - 15/02/2024

Check 27026 fixed 

[here](https://github.com/wazuh/wazuh/pull/20929/commits/768f666c5962b3a7d0ad36392013515caff490ae)

**Comment by ooniagbi** [comment]
## Retest

- Fix the check "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0' (Automated)":
Check ID: 27026
CIS: 2.3.6.5
Status: Status: The check works as expected 🟢

**Comment by ooniagbi** [comment]
https://github.com/wazuh/wazuh/pull/20929 reviewed and merged to 4.8.1.
