### ISSUE TITLE
Unable to disable active-response using group config

### ISSUE THREAD

**Issue by m49sdgn230n** [wazuh/wazuh#17344]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.10 | Active-Response | Both | Packages | Ubuntu 22.04 |

Hello,

I am using the built in firewall-drop active response, and it's working very well. I am now attempting to _disable_ active-response for specific agents using the centralized configuration. For example, if I create a group with the following config:
```
<agent_config>
  <active-response>
    <disabled>yes</disabled>
  </active-response>
</agent_config>
```
I can see that the agent picks up the change as shown in the agent's /var/ossec/etc/shared/agent.conf file, but the active response still takes place. If, however, I directly edit the /var/ossec/etc/ossec.conf file on the agent like this:
```
  <!-- Active response -->
  <active-response>
    <disabled>yes</disabled>
    <ca_store>etc/wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>
```
Then the response is disabled as expected, with nothing showing in the active-responses.log file. I have checked the agent's /var/ossec/etc/local_internal_options.conf and confirmed agent.remote_conf=0 is not set.

**Comment by matias-braida** [comment]
Hello m49sdgn230n,

The section <active-response> is a section that only is read from the local configuration file "/var/ossec/etc/ossec.conf".
This section is not read from the central configuration file "/var/ossec/etc/shared/agent.conf".
This is done this way to prevent the manager can enable Active Response remotely.

These are the settings available from the central configuration: https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html

Hope this helps.
Regards
