### ISSUE TITLE
Expiring Cert of file libgcc_s_dw2-1.dll at 14/06/2023 - ossec-agent folder - windows - 4.4.2

### ISSUE THREAD

**Issue by senseofdream** [wazuh/wazuh#17365]
Hello,
I've found some problem with a certificate of dll file within Wazuh folder in Windows that will expire at 14/06/2023, 
the cert was valid since 11/06/2020.
the file is libgcc_s_dw2-1.dll
I'm using version 4.4.2.

How can i inform WAZUH team about that file so it wont affect our clients as it was with the certification problem with the upgrade agents module?

also got this error already in few of my agents that wont auto start at boot   :
2023/05/31 07:34:39 wazuh-agent: INFO: Trust verification of a module failed by using the signature method. The signature of file 'C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll' terminated in a root certificate that is not trusted.
2023/05/31 07:34:39 wazuh-agent: INFO: Trust verification of a module failed by using the hash method. CryptCATAdminEnumCatalogFromHash failed with error 1168 for 'C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll': Element not found.
2023/05/31 07:34:39 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll' is not signed or its signature is invalid.

![image](https://github.com/wazuh/wazuh/assets/135104261/78cf2f9e-438f-4b1c-9389-94ca3c590a68)

**Comment by jnasselle** [comment]
Closing this issue since https://github.com/wazuh/wazuh-packages/issues/2227 implementation was finished
