### ISSUE TITLE
Exploratory - Error reading cpu frequency on Apple M1

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17364]
### Description

This issue is focused on testing the issue reported in [#16523](https://github.com/wazuh/wazuh/issues/16523). The issue need to be verified and tested in an exploratory manner to reproduce and validate the fixes. 

### Tasks

- Review the issue mentioned in [#16523](https://github.com/wazuh/wazuh/issues/16523).
- Reproduce and validate the reported problem in an exploratory testing environment.
- Test fixes.
- Document the steps.

### Expected Outcome
-  Hardware information is OK.

### Assignee

Windows:
XP 64-32 bits @tdrauncieal 
10 @pereyra-m 
2016 @MiguelazoDS 
2019 @MiguelazoDS 
11 @MiguelazoDS 
2012 @matias-braida 

Linux
Ubuntu 22.04 @Dwordcito 
Centos 7 @Dwordcito 
archlinux @Dwordcito 

macOS
ventura ARM64 @matias-braida 
monterey ARM64 @matias-braida 

Solaris:
11 @tdrauncieal not implemented yet - PK with space? default values? 
10 @pereyra-m not implemented yet - PK with space? default values?

FreeBSD:
13 @pereyra-m

**Comment by MiguelazoDS** [comment]
# Exploratory
## Environment
### Manager

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/ebcbc02f-6592-4456-9e0b-788d6b2efd68)

</details>

### Agents
Windows Server 2016

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/27e72360-c78b-4993-a1b0-f05017278284)

</details>

Windows Server 2019

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/05f1be38-6f10-4978-839f-e11fa182b060)

</details>

Windows 11

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/07fb9860-4462-4d5c-b8cb-4722b3ab6ab5)

</details>

## Tests
### Compilation

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/ce031aa7-0a75-4f75-9734-1cd435ce58af)
![image](https://github.com/wazuh/wazuh/assets/13010397/bcf5a2d0-dd89-40b3-98f4-38a7ae73aa59)
![image](https://github.com/wazuh/wazuh/assets/13010397/44e78c68-afd6-48ce-8453-6766662afb29)

</details>

Moving systool to Windows agents.
### Windows Server 2016

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/0a5d5b74-43ff-431f-9c23-7bccebf55493)

</details>

### Windows Server 2019

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/0542dd9e-36aa-4a66-866c-f33224c526f2)

</details>

### Windows 11

<details>
<summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/9abd395e-ba08-4324-a797-a8cb70195f4f)

</details>

## Results
|Test|Status|Description|
|-|-|-|
|Wazuh version|:yellow_circle:|Compilation generates a 4.4.3 package|
|Windows Server 2016|:green_circle:||
|Windows Server 2019|:green_circle:||
|Windows 11 21H2|:green_circle:||

**Comment by pereyra-m** [comment]
## Exploratory results

| OS | Status |
|-|-|
|Windows 10 64bits|:green_circle:|
|FreeBSD 13|:yellow_circle:|
|Solaris 10 i686|:green_circle:|

In all cases, a Wazuh `v4.4` manager deployed with Docker was used.

## Details

### Windows 10

<details><summary>Details</summary>
<p>

All the tests were succesfull.
The hardware details are retrieved correctly and match those reported by the agent's OS

![2023-05-31_12-14](https://github.com/wazuh/wazuh/assets/65046601/19634fff-381f-4c6a-b5a6-381eef04aae3)

![2023-05-31_12-14_1](https://github.com/wazuh/wazuh/assets/65046601/a802fe50-f94e-4ffc-ae02-8eb7b6ad3598)

![2023-05-31_12-34](https://github.com/wazuh/wazuh/assets/65046601/8ea7390e-f05b-4a33-9e50-fb1f7b2f0ab6)


</p>
</details> 

### Solaris 10

<details><summary>Details</summary>
<p>

All the tests were successful.
The hardware information for Solaris agents isn't developed yet, it'll be done in the issue #17375

![2023-05-31_12-15](https://github.com/wazuh/wazuh/assets/65046601/2c4c8987-afb1-491f-a188-2e7dd894f6e0)

![2023-05-31_12-15_1](https://github.com/wazuh/wazuh/assets/65046601/db8d4717-8e2f-4aa9-b4f6-c239fdebaaec)

The OS information is correct

![2023-05-31_10-38](https://github.com/wazuh/wazuh/assets/65046601/88d03b59-5a39-4768-b185-c873596eda79)


</p>
</details> 

### FreeBSD

<details><summary>Details</summary>
<p>

The hardware information is properly obtained

![2023-05-31_15-19_1](https://github.com/wazuh/wazuh/assets/65046601/8fa4567f-8fb6-464d-a14c-5c82f1e64d6b)

![2023-05-31_15-20](https://github.com/wazuh/wazuh/assets/65046601/32806999-d26d-4448-9ad3-332396d8b1af)

![2023-05-31_15-19](https://github.com/wazuh/wazuh/assets/65046601/f423ea76-c891-4853-ad88-399e0e67a6e6)

But the free RAM field isn't correct

![2023-05-31_15-29](https://github.com/wazuh/wazuh/assets/65046601/2ae8fc09-ff6e-4dd9-9499-cb445a8959bf)

This behavior is present in `v4.4`, so it wasn't due to this change.

</p>
</details>

**Comment by matias-braida** [comment]
## Exploratory results

| OS | Status |
|-|-|
|Macos Monterey arm64|:green_circle:|
|Macos Ventura arm64|:green_circle:|
|Windows Server 12|:green_circle:|

### Environment 

The manager was installed in Ubuntu 22.04 using the development branch `4.4` to test the fix and the current `v4.4.3` on agents to show the error on macos arm64 agents.

Then on agents changed to branch `16523-error-error-reading-cpu-frequency-on-apple-m1` to test the fix.

## Macos Monterey arm64

**Before the fix**
Powermetrics to show CPU max frequency:
```
ec2-user@ip-172-31-40-120 ~ % sudo /usr/bin/powermetrics -s cpu_power -n 1|grep 'active residency: '
E-Cluster HW active residency:  18.79% (600 MHz:   0% 972 MHz:  77% 1332 MHz: .41% 1704 MHz: 3.8% 2064 MHz:  19%)
CPU 0 active residency:  10.75% (600 MHz:   0% 972 MHz: 2.8% 1332 MHz: .10% 1704 MHz: .19% 2064 MHz: 7.7%)
CPU 1 active residency:   2.76% (600 MHz:   0% 972 MHz: 2.3% 1332 MHz: .00% 1704 MHz: .05% 2064 MHz: .44%)
CPU 2 active residency:   1.44% (600 MHz:   0% 972 MHz: 1.1% 1332 MHz: .01% 1704 MHz: .04% 2064 MHz: .27%)
CPU 3 active residency:   6.27% (600 MHz:   0% 972 MHz: 1.7% 1332 MHz: .09% 1704 MHz: .33% 2064 MHz: 4.2%)
P-Cluster HW active residency:   0.10% (600 MHz:  99% 828 MHz:   0% 1056 MHz:   0% 1284 MHz: .38% 1500 MHz: .39% 1728 MHz:   0% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz: .10% 3096 MHz: .00% 3144 MHz:   0% 3204 MHz: .42%)
CPU 4 active residency:   0.04% (600 MHz: .01% 828 MHz:   0% 1056 MHz:   0% 1284 MHz: .00% 1500 MHz: .01% 1728 MHz:   0% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz: .00% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .02%)
CPU 5 active residency:   0.03% (600 MHz: .00% 828 MHz:   0% 1056 MHz:   0% 1284 MHz:   0% 1500 MHz: .00% 1728 MHz:   0% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz:   0% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .02%)
CPU 6 active residency:   0.03% (600 MHz: .00% 828 MHz:   0% 1056 MHz:   0% 1284 MHz: .02% 1500 MHz: .01% 1728 MHz:   0% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz:   0% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .00%)
CPU 7 active residency:   0.00% (600 MHz: .00% 828 MHz:   0% 1056 MHz:   0% 1284 MHz:   0% 1500 MHz:   0% 1728 MHz:   0% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz:   0% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .00%)
```
sysinfo_tool_test execution:
```
sh-3.2# ./sysinfo_test_tool --hardware
Error getting system information: Error reading cpu frequency.: Unknown error -1

Usage: sysinfo_test_tool [options]
Options:
  <without args>  Prints the complete Operating System information.
  --hardware  Prints the current Operating System hardware information.
  --networks  Prints the current Operating System networks information.
  --packages  Prints the current Operating System packages information.
  --processes   Prints the current Operating System processes information.
  --packages-cb   Prints the current Operating System packages using callbacks to return information.
  --processes-cb  Prints the current Operating System processes using callback to return information.
  --ports   Prints the current Operating System ports information.
  --os    Prints the current Operating System information.
  --hotfixes  Prints the current Operating System hotfixes information.

Examples:
  ./sysinfo_test_tool
  ./sysinfo_test_tool --hardware
  ./sysinfo_test_tool --networks
  ./sysinfo_test_tool --packages
  ./sysinfo_test_tool --processes
  ./sysinfo_test_tool --ports
  ./sysinfo_test_tool --os
  ./sysinfo_test_tool --hotfixes
  ./sysinfo_test_tool --processes-cb
  ./sysinfo_test_tool --packages-cb
sh-3.2# ./sysinfo_test_tool --os
{
  "os": {
    "architecture": "arm64",
    "hostname": "ip-172-31-40-120.ec2.internal",
    "os_build": "21G419",
    "os_codename": "Monterey",
    "os_major": "12",
    "os_minor": "6",
    "os_name": "macOS",
    "os_patch": "3",
    "os_platform": "darwin",
    "os_version": "12.6.3",
    "release": "21.6.0",
    "sysname": "Darwin",
    "version": "Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101"
  }
}
```

**After the fix**
sysinfo_tool_test execution:
```
sh-3.2# ./sysinfo_test_tool --hardware
{
  "hw": {
    "board_serial": "H2WH90M1Q6NY",
    "cpu_cores": 8,
    "cpu_mhz": 3204.0,
    "cpu_name": "Macmini9,1",
    "ram_free": 4257536,
    "ram_total": 16777216,
    "ram_usage": 75
  }
}
sh-3.2# ./sysinfo_test_tool --os
{
  "os": {
    "architecture": "arm64",
    "hostname": "ip-172-31-40-120.ec2.internal",
    "os_build": "21G419",
    "os_codename": "Monterey",
    "os_major": "12",
    "os_minor": "6",
    "os_name": "macOS",
    "os_patch": "3",
    "os_platform": "darwin",
    "os_version": "12.6.3",
    "release": "21.6.0",
    "sysname": "Darwin",
    "version": "Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101"
  }
}
```

API request execution:
![image](https://github.com/wazuh/wazuh/assets/101227434/3653cab1-1aff-478d-86c1-373461c2300c)

## Macos Ventura arm64

**Before the fix**
Powermetrics to show CPU max frequency:
```
ec2-user@ip-172-31-38-217 ~ % sudo /usr/bin/powermetrics -s cpu_power -n 1|grep 'active residency: '
E-Cluster HW active residency: 100.00% (600 MHz:   0% 972 MHz: .00% 1332 MHz: .00% 1704 MHz: .00% 2064 MHz: 100%)
CPU 0 active residency:  47.32% (600 MHz:   0% 972 MHz: .00% 1332 MHz: .00% 1704 MHz: .00% 2064 MHz:  47%)
CPU 1 active residency:  37.61% (600 MHz:   0% 972 MHz: .00% 1332 MHz: .00% 1704 MHz: .00% 2064 MHz:  38%)
CPU 2 active residency:  52.63% (600 MHz:   0% 972 MHz: .00% 1332 MHz: .00% 1704 MHz: .00% 2064 MHz:  53%)
CPU 3 active residency:  35.79% (600 MHz:   0% 972 MHz: .00% 1332 MHz: .00% 1704 MHz: .00% 2064 MHz:  36%)
P-Cluster HW active residency:   0.70% (600 MHz:  98% 828 MHz: .08% 1056 MHz: .17% 1284 MHz: .16% 1500 MHz: .16% 1728 MHz: .25% 1956 MHz:   0% 2184 MHz: .01% 2388 MHz: .15% 2592 MHz: .16% 2772 MHz: .08% 2988 MHz: .09% 3096 MHz: .01% 3144 MHz: .16% 3204 MHz: .36%)
CPU 4 active residency:   0.40% (600 MHz: .00% 828 MHz: .04% 1056 MHz: .08% 1284 MHz: .09% 1500 MHz: .07% 1728 MHz: .08% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz: .00% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .04%)
CPU 5 active residency:   0.36% (600 MHz: .01% 828 MHz: .00% 1056 MHz: .00% 1284 MHz: .03% 1500 MHz: .01% 1728 MHz: .10% 1956 MHz:   0% 2184 MHz: .00% 2388 MHz: .01% 2592 MHz: .03% 2772 MHz: .00% 2988 MHz: .01% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .17%)
CPU 6 active residency:   0.02% (600 MHz: .00% 828 MHz:   0% 1056 MHz:   0% 1284 MHz:   0% 1500 MHz:   0% 1728 MHz: .02% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz:   0% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .00%)
CPU 7 active residency:   0.00% (600 MHz: .00% 828 MHz:   0% 1056 MHz:   0% 1284 MHz:   0% 1500 MHz:   0% 1728 MHz: .00% 1956 MHz:   0% 2184 MHz:   0% 2388 MHz:   0% 2592 MHz:   0% 2772 MHz:   0% 2988 MHz:   0% 3096 MHz:   0% 3144 MHz:   0% 3204 MHz: .00%)
```
sysinfo_tool_test execution:
```
ec2-user@ip-172-31-38-217 bin % ./sysinfo_test_tool --hardware
Error getting system information: Error reading cpu frequency.: Unknown error -1

Usage: sysinfo_test_tool [options]
Options:
  <without args>  Prints the complete Operating System information.
  --hardware  Prints the current Operating System hardware information.
  --networks  Prints the current Operating System networks information.
  --packages  Prints the current Operating System packages information.
  --processes   Prints the current Operating System processes information.
  --packages-cb   Prints the current Operating System packages using callbacks to return information.
  --processes-cb  Prints the current Operating System processes using callback to return information.
  --ports   Prints the current Operating System ports information.
  --os    Prints the current Operating System information.
  --hotfixes  Prints the current Operating System hotfixes information.

Examples:
  ./sysinfo_test_tool
  ./sysinfo_test_tool --hardware
  ./sysinfo_test_tool --networks
  ./sysinfo_test_tool --packages
  ./sysinfo_test_tool --processes
  ./sysinfo_test_tool --ports
  ./sysinfo_test_tool --os
  ./sysinfo_test_tool --hotfixes
  ./sysinfo_test_tool --processes-cb
  ./sysinfo_test_tool --packages-cb
ec2-user@ip-172-31-38-217 bin % ./sysinfo_test_tool --os      
{
  "os": {
    "architecture": "arm64",
    "hostname": "ip-172-31-38-217.ec2.internal",
    "os_build": "22D68",
    "os_codename": "Ventura",
    "os_major": "13",
    "os_minor": "2",
    "os_name": "macOS",
    "os_patch": "1",
    "os_platform": "darwin",
    "os_version": "13.2.1",
    "release": "22.3.0",
    "sysname": "Darwin",
    "version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103"
  }
}
```
**After the fix**
sysinfo_tool_test execution:
```
ec2-user@ip-172-31-38-217 bin % ./sysinfo_test_tool --hardware
{
  "hw": {
    "board_serial": "H2WH91N3Q6NY",
    "cpu_cores": 8,
    "cpu_mhz": 3204.0,
    "cpu_name": "Macmini9,1",
    "ram_free": 7373040,
    "ram_total": 16777216,
    "ram_usage": 57
  }
}
ec2-user@ip-172-31-38-217 bin % ./sysinfo_test_tool --os      
{
  "os": {
    "architecture": "arm64",
    "hostname": "ip-172-31-38-217.ec2.internal",
    "os_build": "22D68",
    "os_codename": "Ventura",
    "os_major": "13",
    "os_minor": "2",
    "os_name": "macOS",
    "os_patch": "1",
    "os_platform": "darwin",
    "os_version": "13.2.1",
    "release": "22.3.0",
    "sysname": "Darwin",
    "version": "Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103"
  }
}
```

API request execution:
![image](https://github.com/wazuh/wazuh/assets/101227434/7bd28c73-a9b8-48b3-adff-723542ac0ff3)

## Windows Server 12

**After the fix**
sysinfo_tool_test execution:
```
PS C:\Users\vagrant\Downloads\wazuh-winagent\wazuh\src\data_provider\build\bin> .\sysinfo_test_tool.exe --hardware
{
  "hw": {
    "board_serial": "0",
    "cpu_cores": 4,
    "cpu_mhz": 2808.0,
    "cpu_name": "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz",
    "ram_free": 1401264,
    "ram_total": 2096692,
    "ram_usage": 33
  }
}
PS C:\Users\vagrant\Downloads\wazuh-winagent\wazuh\src\data_provider\build\bin> .\sysinfo_test_tool.exe --os
{
  "os": {
    "architecture": "x86_64",
    "hostname": "VAGRANT-2012-R2",
    "os_build": "9600.20778",
    "os_display_version": " ",
    "os_major": "6",
    "os_minor": "3",
    "os_name": "Microsoft Windows Server 2012 R2 Standard",
    "os_release": "",
    "os_version": "6.3.9600.20778"
  }
}
```

API request execution:
![image](https://github.com/wazuh/wazuh/assets/101227434/ede12870-80f0-4181-856f-0d0653885cf2)

**Comment by Dwordcito** [comment]
## Exploratory results

| OS | Status |
|-|-|
|Ubuntu 22.04|:green_circle:|
|Centos 7.9|:green_circle:|
|Arch linux|:green_circle:|


All agent connected.

![image](https://github.com/wazuh/wazuh/assets/14300208/b597bb3b-1d79-41b0-a6ab-94db6dd7c78d)


# Ubuntu 22.04
UI OK
![image](https://github.com/wazuh/wazuh/assets/14300208/89463724-67d6-4763-a50d-09f3a09e5734)

Database OK
![image](https://github.com/wazuh/wazuh/assets/14300208/f9ccc9f7-271a-4e09-b53c-5b9e4cd9a3e8)



# Centos7
UI OK
![image](https://github.com/wazuh/wazuh/assets/14300208/3e41af9c-d125-49dc-84eb-f7fa36ca7ea0)


Database OK
![image](https://github.com/wazuh/wazuh/assets/14300208/0921830d-0370-4eab-8396-0c3a5a7a73a6)

# Arch Linux
UI OK
![image](https://github.com/wazuh/wazuh/assets/14300208/3e280e71-7dbb-4bce-80c4-677a10622343)



Database OK

![image](https://github.com/wazuh/wazuh/assets/14300208/b62577bd-bd38-4b96-9a01-a4f5f6b18909)

**Comment by Dwordcito** [comment]
Exploratory OK.
