### ISSUE TITLE
Wazuh rule Syntax info

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#17368]
Hi,
I use Wazuh 4.3.10
In document, when create with field  **<info type="link">** with a link type but when alert in dashboard I can't see field of this link.
This link is merged with **rule.info** like this

![ảnh](https://github.com/wazuh/wazuh/assets/82009148/64bac694-9ce2-425b-91ba-73d2818de645)
--------------------
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/c49bda5c-3310-4669-9903-e4402411180d)
In source, I can find rule.cve, rule.info but no **rule.link**

Best Regards,

**Comment by nmkoremblum** [comment]
Hi @thanvantrong,

What do you mean when you say "In document, when create with field with a link type but when alert in dashboard I can't see field of this link."

I will be waiting for your reply

**Comment by thanvantrong** [comment]
Hi @nmkoremblum

A custom rule
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/b39a302e-0e4e-4495-a7b4-49d74db61da1)
but when alert info type text and link show in one line
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/a17ff499-5576-47d0-bde7-1341f162305c)
It's correct?

Regards,
