### ISSUE TITLE
Remove unnecessary packages from the Wazuh embedded interpreter 

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#17398]
|Wazuh version|Component|
|---|---|
| 4.4 | Wazuh embedded interpreter |

## Description
It was found that when installing Wazuh due to the manual generation of the preinstalled Python, the Wazuh packages installed were not removed. This generates dependency versions 19 and 20 to have two versions of the packages `api` and `wazuh` in case other versions than `v4.4.0` or `v4.4.2` are installed. The old versions are not used after the installation, but they should be removed to avoid confusion or possible bugs.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Correct installation in `amd64` and `aarch64`.
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Done in 
- https://github.com/wazuh/wazuh/issues/18123
