### ISSUE TITLE
Syslogs messages not in alerts.log file

### ISSUE THREAD

**Issue by piyush1337** [wazuh/wazuh#1741]
I have configured switch to send syslogs to manger server and i am receiving the logs in 
/var/ossec/logs/archives/archives.log file but i want to view those in web UI(discover tab) as far as i know the logs should be in alerts.log file so that those can be seen in UI but they are not coming in alerts.log file 

i have changed this 
< log all> yes </log all> (remove spaces)
and 
<log_alert_level>1</log_alert_level>

in ossec.conf file 

but still no logs in alerts.log or alerts.json file 

Please help

**Comment by TJOSERAFAEL** [comment]
Hi @piyush1337 ,

if you don't see the alerts in alerts.log it's because you need to write your own rules/decoders for the events that the switch send to the manager.

Can you please send an example of the messages send by the switch?

Best regards.

**Comment by piyush1337** [comment]
> Hi @piyush1337 ,
> 
> if you don't see the alerts in alerts.log it's because you need to write your own rules/decoders for the events that the switch send to the manager.
> 
> Can you please send an example of the messages send by the switch?
> 
> Best regards.

but i even set the log alert level to 0 and 1 too so that means if the level is 0 or 1 i still should get the logs in alerts.log file isn't it ???

**Comment by TJOSERAFAEL** [comment]
Hi @piyush1337 ,

an alert will fire if and only if a rule is matched no matter what the alert level is. Here you have the entire wazuh-ruleset https://github.com/wazuh/wazuh-ruleset. 

There are no rules that matches the messages you are receiving so you can write your on rules. 
Here you have the documentation with examples on how to write rules: https://documentation.wazuh.com/current/user-manual/ruleset/custom.html?highlight=rules

Best regards.
