### ISSUE TITLE
QA framework migration

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#17427]
# Description

Since each development team will handle the unit/integration test suites, they will be migrated from the QA repository to the corresponding subsystem repository and automated with GitHub Actions.

For instance, the Core team will migrate unit/integration test suites that belong to Wazuh agent and manager to the `wazuh/wazuh` repository.

Additionally, a new integration test framework will be created from the old one and placed in the `wazuh/qa-integration-framework` repository. This framework will be used by all migrated and new tests, which will include all common and generic functions.

# Functional requirements

- All current test suites must be migrated to their corresponding repositories.
- GitHub actions must execute all test suites in their corresponding repositories.
- After the migration, all test suites must pass and have no warnings.
- Tests that fail before the migration and have an associated issue will be marked as xfailed.
- All test suites must use the new framework, which will be created in the `wazuh/qa-integration-framework` repository.
- The `wazuh/qa-integration-framework` must be documented, including its structure and how to define new tests.
- The `wazuh/qa-integration-framework` repository must use the same guidelines/processes followed by the rest of Wazuh repositories, including versioning, branches naming conventions, etc.

# Non-functional requirements

- Clean and well-structured code.
- Avoid duplicating code.
- Make the migrated code as reusable as possible.
- Avoid bad practices and improve code usability.

# Implementation restrictions

- Follow the [defined structure](https://sites.google.com/d/14wlOV8xTh8HiwKOrm6KPpt3MUp3E61x1/p/1GWQrogEM578m9Clg25vb8W1I37mN7Ocw/edit?pli=1).

# Plan

Action plan for migrating and automating integration test suites:

### 1. Create the framework repository:

- Set up the `qa-integration-framework` repository on GitHub under the `wazuh` organization.
- Provide an introductory README explaining the framework's purpose, structure, and guidelines.

### 2. Define framework structure:

- Establish a well-organized directory structure, including sections for common functions, generic functions, and specific subsystems.
- Clearly outline guidelines for developers to follow when adding new tests.

### 3. Migrate test suites:

- Transfer existing test suites from the QA repository to the Core repository (`wazuh/wazuh`).
- Ensure a seamless migration process while adhering to the defined structure.

### 4. Implement GitHub Actions:
- Create multiple GitHub Actions workflows to automate the execution of all test suites using the `qa-integration-framework`.
- Configure workflows to trigger on each push to the main branch and when a pull request is created.

### 5. Handle failing tests before migration:
- Identify and document pre-migration failing tests along with associated issues.
- Mark these tests as xfailed and provide clear links to the relevant issues for tracking and resolution.

### 6. Ensure passing tests after migration:
- Execute GitHub Actions workflows to validate that all tests pass successfully after the migration.
- Address any issues or warnings that may arise during the testing process.

### 7. Document the framework and test suites:
- Develop comprehensive documentation for the `qa-integration-framework` and the migrated test suites.
- Include details on the framework's structure, guidelines for writing new tests, and any specific considerations for the migrated tests.
- Keep the documentation regularly updated to reflect changes.

### 8. Adopt Wazuh repository guidelines:
- Confirm that the `qa-integration-framework` repository aligns with established Wazuh guidelines, including versioning and branch naming conventions.

### 9. Maintain code quality:
- Conduct regular code reviews to ensure the code is clean, well-structured, and adheres to best practices.
- Emphasize the elimination of code duplication and encourage developers to create reusable components.

### 10. wazuh-qa and wazuh-jenkins clean up:
- Remove dead code from wazuh-qa repository.
- Remove dead code from wazuh-jenkisn repository.
- Remove/disable PR_wazuh integration test in Jenkins.
- https://github.com/wazuh/wazuh-jenkins/issues/6361

## Requirements Traceability Matrix (RTM)

| Type           | Responsible(s)             | Description                                                                                                          | Plan Part                                 |
|----------------|----------------------------|----------------------------------------------------------------------------------------------------------------------|-------------------------------------------|
| Functional     | Core/Framework Team        | Migrate current test suites to corresponding repositories                                                             | 3. Migrate test suites                    |
| Functional     | Core/Framework Team        | Execute test suites using GitHub Actions in their respective repositories                                            | 4. Implement GitHub Actions               |
| Functional     | Core/Framework Team        | Ensure migrated test suites pass with no warnings                                                                    | 6. Ensure passing tests after migration   |
| Functional     | Core/Framework Team        | Mark pre-migration failing tests as xfailed                                                                          | 5. Handle failing tests before migration  |
| Functional     | Core/Framework Team        | Utilize the new framework in all test suites                                                                         | 1. Create the framework repository        |
| Functional     | Dev Team Lead              | Document the `qa-integration-framework` repository, including its structure and test definition process              | 7. Document the framework and test suites |
| Functional     | Dev Team Lead              | Ensure the `qa-integration-framework` aligns with Wazuh repository guidelines                                        | 8. Adopt Wazuh repository guidelines      |
| Non-functional | Core/Framework Team        | Maintain clean, well-structured, and reusable code, avoiding code duplication                                       | 9. Maintain code quality                  |
| Non-functional | Core/Framework Team        | Improve code usability and avoid bad practices                                                                       | 9. Maintain code quality                  |
| Implementation | Core/Framework Team        | Adhere to the defined structure for migration and framework development                                               | All Stages                                |
| Implementation | Core/Framework Team        | Ensure smooth integration of the new framework with existing systems and workflows                                    | 2. Define framework structure & 4. Implement GitHub Actions |
| Implementation | Core/Framework Team        | Address any issues or warnings that arise during the migration and testing process                                    | 6. Ensure passing tests after migration   |

# Issues

## Migration process

<details><summary>Migration issues</summary><br>

**Researches**

- [x] https://github.com/wazuh/wazuh/issues/17007
- [x] https://github.com/wazuh/wazuh/issues/17157
- [x] https://github.com/wazuh/wazuh/issues/17173

**Tests migration**

- [x] https://github.com/wazuh/wazuh/issues/17162
- [x] https://github.com/wazuh/wazuh/issues/19081
- [x] https://github.com/wazuh/wazuh/issues/19082
- [x] https://github.com/wazuh/wazuh/issues/17403
- [x] https://github.com/wazuh/wazuh/issues/19083
- [x] https://github.com/wazuh/wazuh/issues/19084
- [x] https://github.com/wazuh/wazuh/issues/17209
- [x] https://github.com/wazuh/wazuh/issues/17426
- [x] https://github.com/wazuh/wazuh/issues/17172
- [x] https://github.com/wazuh/wazuh/issues/17612
- [x] https://github.com/wazuh/wazuh/issues/19085
- [x] https://github.com/wazuh/wazuh/issues/17881
- [x] https://github.com/wazuh/wazuh/issues/17700
- [x] https://github.com/wazuh/wazuh/issues/19086
- [x] https://github.com/wazuh/wazuh/issues/19087
- [x] https://github.com/wazuh/wazuh/issues/17696
- [x] https://github.com/wazuh/wazuh/issues/19088
- [x] https://github.com/wazuh/wazuh/issues/17441
- [x] https://github.com/wazuh/wazuh/issues/17788

</details>

## Maintenance process:

<details><summary>Maintenance issues</summary><br>

**Tests fixes**

- [x] https://github.com/wazuh/wazuh-qa/issues/4112
- [x] https://github.com/wazuh/wazuh-qa/issues/4188
- [x] https://github.com/wazuh/wazuh-qa/issues/4190
- [x] https://github.com/wazuh/wazuh-qa/issues/4126
- [x] https://github.com/wazuh/wazuh-qa/issues/4191

**Framework refactors**

- [x] https://github.com/wazuh/wazuh-qa/issues/4158
- [x] https://github.com/wazuh/wazuh-qa/issues/4159
- [x] https://github.com/wazuh/wazuh-qa/issues/4160
- [x] wazuh/wazuh-qa#4173
- [x] https://github.com/wazuh/wazuh-qa/issues/4184
- [x] https://github.com/wazuh/wazuh-qa/issues/4195
- [x] https://github.com/wazuh/wazuh-qa/issues/4197

**Tests refactors**

- [x] https://github.com/wazuh/wazuh-qa/issues/3218
- [x] https://github.com/wazuh/wazuh-qa/issues/3298
- [x] https://github.com/wazuh/wazuh-qa/issues/4165
- [x] https://github.com/wazuh/wazuh-qa/issues/3425
- [x] https://github.com/wazuh/wazuh-qa/issues/3455
- [x] https://github.com/wazuh/wazuh-qa/issues/3485
- [x] https://github.com/wazuh/wazuh-qa/issues/3552
- [x] https://github.com/wazuh/wazuh-qa/issues/3593
- [x] https://github.com/wazuh/wazuh-qa/issues/3806
- [x] https://github.com/wazuh/wazuh-qa/issues/3963
- [x] https://github.com/wazuh/wazuh-qa/issues/3992
- [x] https://github.com/wazuh/wazuh-qa/issues/4125
- [x] https://github.com/wazuh/wazuh-qa/issues/4153
- [x] https://github.com/wazuh/wazuh-qa/issues/4156
- [x] https://github.com/wazuh/wazuh-jenkins/issues/4984
- [x] https://github.com/wazuh/wazuh-jenkins/issues/4987
- [x] https://github.com/wazuh/wazuh-jenkins/issues/4985
- [x] https://github.com/wazuh/wazuh-qa/issues/4161

</details>

# Approved by

- @havidarou 
- @davidjiglesias 
- @vikman90

**Comment by mauromalara** [comment]
## Important

- The migration **of the ITs** is being developed at: https://github.com/wazuh/wazuh/pull/17443
- The migration **of the testing framework** is being developed at: https://github.com/wazuh/qa-integration-framework/pull/1

**Comment by davidjiglesias** [comment]
Reviewed together with @havidarou, please include RTM
