### ISSUE TITLE
Refactor and migrate GCP integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17442]
## Description
GCloud integration tests will be moved to wazuh/wazuh repository. However, they must be refactored in advance to improve multiple aspects, so little or no changes are required when migrating.

### Current behavior
It seems that some of these tests are unstable and fail randomly. Also, some are testing similar things.

### Expected behavior
- All tests should pass consistently.
- At @mauromalara suggestion, we should review the description of all the tests and eliminate or unify in the same file those that test the same feature, if any. Only those that make sense should remain.
- Global fixtures and tools should be used when possible (for example, to restart services).
- Review whether the structure used in tests like `test_vulnerability_detector` could be applied for the gcloud tests (configuration template, test_cases, etc).

## Related issues
- https://github.com/wazuh/wazuh/issues/18551
- https://github.com/wazuh/wazuh/issues/18566

**Comment by EduLeon12** [comment]
## Issue Update 

Currently investigating the behavior and reason for the failing, skipped, and xfail test.

Also, investigating the [qa-integration-framework](https://github.com/wazuh/qa-integration-framework), to conclude which test should be refactored before the migration.

**Comment by EduLeon12** [comment]
# Issue Update

The issue will be on hold until [AWS ITs](https://github.com/wazuh/wazuh/issues/17788) are migrated.

Doing AWS migration first will give us a better understanding of the framework and migration process since AWS are currently not showing any issue to run.

**Comment by Selutario** [comment]
This will no longer be done as part of the `QA framework migration` objective. Moving it to blocked until deciding which should be its objective.

**Comment by Selutario** [comment]
As tests will not be migrated but re-created, I'm closing this issue in favor of:
- https://github.com/wazuh/wazuh/issues/18551
