### ISSUE TITLE
Migrate API integration tests and refactor them

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17441]
## Description
API integration tests will be moved to the wazuh/wazuh repository. However, they must be refactored to improve multiple aspects.

### Current behavior
Some tests are failing. In addition, the old tag's approach is used so a lot of tests are skipped. More things could arise after being analyzed in this issue:
- https://github.com/wazuh/wazuh/issues/17157

### Expected behavior
- There should be no skipped tests.
- Any failing test reported at https://github.com/wazuh/wazuh/issues/17157 should be fixed.
- Global fixtures and tools should be used when possible (for example, to restart services).
- Review whether the structure used in tests like `test_vulnerability_detector` could be applied for the API (configuration template, test_cases, etc).

### QA framework migration

This issue requires some code from the old QA framework to be moved to the new repository. So, the following issue: https://github.com/wazuh/qa-integration-framework/issues/6 contains those changes that support the migration of THESE tests.

**Comment by mauromalara** [comment]
### Update

- Environment configured
- Develop started
- Modified epic #17427 
  - Created PRs for epic branches to track the team's work

**Comment by mauromalara** [comment]
## Update 08/06/23

- Added `daemons_handler` to the new test suite to standardize the stop/start/restart operations over the daemons and the entire system: https://github.com/wazuh/wazuh/pull/17443/commits/e20b807708de16c4e2bbf3a9e04b140dabbe060a (epic branch)
- Added/changed documentation in several modules in the IT framework (in my branch)
- Added type hints to all functions in the `file` module
- Changed the way the API configuration is applied and changed the fixture to add the configuration

**Comment by mauromalara** [comment]
## Update 09/06/2023

- Finished test_bruteforce refactor and framework refactor
- Worked in a new way to create dynamic regex to avoid code duplication (finished)
- Worked in a new function to apply API configuration (WIP)

**Comment by mauromalara** [comment]
## Update

- Created a function to create_files and a function to delete_files
- Created a fixture to create the files defined in a test module and then clean up the environment

**Comment by mauromalara** [comment]
## Update

- test_cache migrated
- test_cors migrated
- test_DOS migrated

Remaining tests: 16

**Comment by mauromalara** [comment]
## Update

- `test_drop_privileges` migrated
- `test_experimental_features` migrated
- `test_host_port` migrated

**Comment by mauromalara** [comment]
## Update

- `test_https` migrated
- `test_jwt_token_exp_timeout` migrated
- Fix applied in several tests
- Missing docs added in some tests

**Comment by mauromalara** [comment]
## Update

- `test_logs` migrated
- `test_max_upload_size` 50% migrated

**Comment by mauromalara** [comment]
## Update

- [test_statistics](https://github.com/wazuh/wazuh/commit/070edd7f47fb5a32c610d3187b82c2bf2896cd8b) migrated
- Started migrating:
  - test_add_old_user
  - test_add_old_role
  - test_add_old_policy
  - test_add_old_rule

**Comment by mauromalara** [comment]
## Update

- I consider that the current `test_rbac` is not at the integration level (I'll discuss this with @Selutario )
- I migrated `test_add_old_user`

**Comment by mauromalara** [comment]
## Update

Finished migration

**Comment by mauromalara** [comment]
## Update 2023/03/07

- Created a [new branch and opened a new PR](https://github.com/wazuh/wazuh/pull/17733) to remove duplicated commits due to a bad rebase
- Launched tests locally (check PR) to verify that everything works as expected

**Comment by mauromalara** [comment]
## Update 2023/04/07

- I analyzed the code (it took me a long time because I was unfamiliar with Groovy and Jenkins).
- I had doubts, I had a huddle with Raul.
- I made some changes in the Jenkins PR: wazuh/wazuh-jenkins#5345
- I realized that the changes still affected the Nightly and made a sync in a thread Raul opened.
- We had a meeting about the changes affecting the Nightly

**Comment by mauromalara** [comment]
## Update

- I worked in the requested changes

**Comment by mauromalara** [comment]
## Update

- Applied requested changes
- Meeting with Tomas to discuss some changes

**Comment by mauromalara** [comment]
## Update

- Changes applied due to requested changes in the library: https://github.com/wazuh/qa-integration-framework/issues/6
- 3 executions were made
