### ISSUE TITLE
`sca.files` template is empty for Debian and Fedora

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#17458]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4-rev | SCA | Manager/Agent | Packages/Sources | Debian/Fedora |

We were notified of an error installing the agent package in Debian 12:
https://github.com/wazuh/wazuh-packages/issues/2196

After investigating the problem we determined that the root of the issue was that the default template for Debian SCA files was empty.
https://github.com/wazuh/wazuh/blob/4.4.4/etc/templates/config/debian/sca.files

We have also noticed this problem for Fedora systems:
https://github.com/wazuh/wazuh/blob/4.4.4/etc/templates/config/fedora/sca.files

And that there is no default template for Amazon linux:
https://github.com/wazuh/wazuh/tree/4.4.4/etc/templates/config/amzn

**Comment by 72nomada** [comment]
@DFolchA Should we modify package building not to consider this default template for any OS?

**Comment by 72nomada** [comment]
Hi @DFolchA, can we close this?

**Comment by jotacarma90** [comment]
Closing this due to was solved in https://github.com/wazuh/wazuh-packages/issues/2196
