### ISSUE TITLE
Review agent and manager dependencies to anticipate EOL - June

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#17459]
## Description

This issue aims to review all dependencies used in the agent and manager code to identify if there is an EOL announced for any of them, which could become vulnerable packages as they will not receive new patches. In case of positive matches, we must proceed to update the corresponding dependencies to a newer version.

**Comment by Nicogp** [comment]
The EOL analysis of the external dependencies has been completed for the month of June 2023.
