### ISSUE TITLE
Upgrade checkfiles show wrong permissions in `/var/db/template.db`

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#17487]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4-rc1 | wazuhdb | Manager | Packages | All OSs |

During the analysis of the Upgrade Tests the following error was found in checkfiles for the manager all the tested OSs for upgrades from `4.0.x` to `4.4.4`:

```
Namespace(directory='/var/ossec', from_version='4.0.0', ignore='/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python', no_show_ignore_list=True, os='linux', target='manager', test='upgrade', version='4.4.4')
Checking files...

Missing (They are present in the check-files but they are not installed):
/var/ossec/integrations/virustotal.py

Different:
/var/ossec/var/db/.template.db [Wrong:  mode]
	Expected: root wazuh  0640  # -rw-r-----
	Found   : root wazuh  0660  # -rw-rw----



Please, review your files.
```

**Build:** https://ci.wazuh.info/job/Test_upgrade_tier/2078/
**Example**: [checkfiles_upgrade_manager_log_B118597.txt](https://github.com/wazuh/wazuh/files/11681882/checkfiles_upgrade_manager_log_B118597.txt)

**Comment by vikman90** [comment]
@Deblintrake09 This file should not exist anymore since 4.4.0 (PR https://github.com/wazuh/wazuh/pull/11753). 

On the other hand, the installer should be removing that as of 3.2.0 (https://github.com/wazuh/wazuh/commit/a6ac9a4abe7dca1404053ef44aaedc0a39e9543f). This makes me think that the package is not cleaning the file correctly.

I am adding this to the roadmap as a possible package bug.

Thanks!
