### ISSUE TITLE
Errors reported by scan-build in target Server and Agent for windows

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17495]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | VD/config | Manager | Packages/Sources | OS version |

### Description

This issue focuses on addressing the errors reported by `scan-build` in the target server, and agent only for windows. These errors need to be fixed to ensure a clean and error-free build and operation of the Wazuh project.

### Tasks

- Review the errors reported by `scan-build` in the compilation server, and agent for windows.
- Identify the root causes of the reported errors.
- Fix the errors by updating the code or making necessary modifications.
- Test the changes to ensure that the errors have been resolved and that the components build and operate correctly on windows.

### Expected Outcome

The expected outcome of this issue is to resolve the errors reported by `scan-build` in the compilation server and agent components for windows. After the fixes, the components should build without errors and operate correctly on windows.

Server:
![image](https://github.com/wazuh/wazuh/assets/14300208/88d12370-8538-4306-9ce5-488efbbf0445)

[scanview.tar.gz](https://github.com/wazuh/wazuh/files/11683931/scanview.tar.gz)

Agent windows:
![image](https://github.com/wazuh/wazuh/assets/14300208/1099be98-8a96-4f35-837e-d7b4473e944f)
[windows-agent-scan-build-report(2).zip](https://github.com/wazuh/wazuh/files/11745871/windows-agent-scan-build-report.2.zip)

**Comment by jnasselle** [comment]
Hi team,

The scope of this issue is currently only macOS results since agent ones were solved in this PR https://github.com/wazuh/wazuh/pull/17438/
