### ISSUE TITLE
Make use of a compilation cache to speed up the RTR execution

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#17491]
## Description

The **ccache** tool can be used to speed up the compilation process of the Github Actions workflows.
A compilation cache can be generated for every main branch of the repository and it can be used for every RTR run of an open pull request. Then, only the changes should be compiled and not the full repository.

Here we have an example of this:
https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/

## DoD

- [ ] Modify the RTR script and the CMakeLists files (if required) to support the use of a compilation cache
- [ ] Create a workflow that updates the cache for the main branches after every merge
- [ ] Update all the current workflows to download the corresponding cache (if exists) and show the compilation stats
- [ ] Make sure that the cache is properly compressed, and that only one cache per main branch exists
- [ ] Make sure that the existing workflows only compile the minimum required target of the project and update them if required (for example, `make build_syscollector` instead of `make agent`)
- [ ] CI Pass

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
