### ISSUE TITLE
Realtime no working fine

### ISSUE THREAD

**Issue by santi10** [wazuh/wazuh#175]
Hi,

I'm running Wazuh server on Centos (with OVA). I've configured an agent win (win 8) and tested a directory for testing. I want to see all changes on this directory (add, delete, change, etc). I've added this line on file config, this:

<directories report_changes="yes" check_all="yes" realtime="yes">C:\test</directories>

Also I modified the frequency to "60" (this value is seconds)

On Wazuh server I don't see theses alerts always, so one time yes and another time no....I'm hopeless

I see this event time 

Old date: Thu Aug 31 11:40:24 2017
New date: Thu Aug 31 12:01:00 2017

its can't be !!!! You can see more de 20 min!!! I don't know as can be that

Can you help me, please?

Thanks a lot

**Comment by santi10** [comment]
`<directories report_changes="yes" check_all="yes" realtime="yes">C:\test</directories>`

**Comment by jlruizmlg** [comment]
Hi @santi10 , 

This configuration is correct, you need to add this configuration to your ossec.conf in Windows agent and restart it.

The process works in this way:

1 - Windows will do the standard syscheck (if you have the default configuration can take a few min)
2 - Then Rootcheck will run (the same, can take a few min)
3 - After syscheck and rootcheck have finished will start the realtime process.

How check if is correct: 
In your Windows agent, serach in ossec.log something like this:

```
2017/08/31 14:04:05 ossec-syscheckd: INFO: Monitoring directory: 'C:\test', with options perm | size | owner | group | md5sum | sha1sum | realtime | report_changes | mtime | inode.
```
This means that the folder will be monitored in | realtime |

Then after the rootcheck scan finish you will have the "Starting syscheck real-time monitoring" like in the following example:

```
2017/08/31 14:08:25 rootcheck: INFO: Ending rootcheck scan.
2017/08/31 14:08:25 ossec-syscheckd: INFO: Starting syscheck real-time monitoring.
```
All this logs are from the Windows agent of course.

**Comment by santi10** [comment]
Thanks jlruizmlg

I don't see that line "ossec-syscheckd: INFO: Starting syscheck real-time monitoring." in my ossec.conf in my windows agent....

How I can see it?


Thx
Santi

**Comment by santi10** [comment]
For example, I can see all events like "logoff" perfectly but I can't see the events on realtime.

**Comment by santi10** [comment]
Sorry, I see theses evets fine, such us:

"2017/08/31 20:29:56 ossec-agent: INFO: Initializing real time file monitoring engine.
2017/08/31 20:30:02 ossec-agent: INFO: Real time file monitoring engine started."


But this behavior isn't steady...what i can do but fix it, please????


Regards
Santi

**Comment by jlruizmlg** [comment]
Hi @santi10 , the log that you paste is different, you need to wait the following log in the agent log

```2017/08/31 14:08:25 ossec-syscheckd: INFO: Starting syscheck real-time monitoring.```

Are similar but different.

What wazuh version are you using in windows?

**Comment by santi10** [comment]
My windows version is v2.1.0 (Agent Wazuh)

**Comment by jlruizmlg** [comment]
If your windows agent has the line ```<directories report_changes="yes" check_all="yes" realtime="yes">C:\test</directories>```  in the ossec.conf restart your agent and wait for this exactly log:

```ossec-syscheckd: INFO: Starting syscheck real-time monitoring.```, as i told you in the previous post, this can take a few time (10 or 15 min).

**Comment by santi10** [comment]
Wua!! Yes, it was a matter of time!! Thanks for all
