### ISSUE TITLE
Windows 11, Not all installed updates (KB) are listed in invetory (hotfixes)

### ISSUE THREAD

**Issue by tfmotu** [wazuh/wazuh#17508]
Windows 11, Not all installed updates (KB) are listed in invetory (hotfixes)

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.3 | Inventory/Vulnerabilites | Agent | Packages | Windows 11 Home Edition |

Hello, first of all Wazuh is an incredible product.
We are currently experiencing a problem on a Windows 11 Home Edition. 
The problem is that the inventory does not include all the hotfixes actually installed on the computer, so the vulnerability scan reports false positives.
This is the list of hotfixes included in Wazuh's inventory:
`sqlite3 /var/ossec/queue/db/008.db "select * from sys_hotfixes;"
0|2023/04/05 17:17:44|KB2468871|8f99821b9e79bc2258cb56cd14cfcaf9bbeda8e5
0|2023/04/05 17:17:44|KB2478063|8511235ae3ab3b642d8ba429599092634fdde3a8
0|2023/04/05 17:17:44|KB2533523|b8c4cb9a2aeb6a64269e88f6116765420a65cd80
0|2023/04/05 17:17:45|KB2544514|8e468309f00c0f31b8a0f12a6a79d2658652e9e9
0|2023/04/05 17:17:45|KB2600211|cb13c01ba11045aabbb074fc3e61b0a3b2d88dd4
0|2023/04/05 17:17:45|KB2600217|8253af775746f8545784d27edb852281c9a06955
0|2023/04/05 17:17:45|KB5012170|d9e49825d14b5bbbf4b4aa4c499ae7f8121389a3
0|2023/04/05 17:17:45|KB5022497|8d8360100a60d1430dd33259f1f62cc1b168f07f
0|2023/05/04 17:52:09|KB5025305|a0520b66f14994db453671ef805223dbb6584d31
0|2023/05/26 09:16:04|KB5026372|835e2d284ca263809f7f87e64ddfe890484b1bc3
0|2023/05/26 14:01:47|KB5026446|8e19af0e3d35d3dfad3df401bb5e6de81b103f59
`
But as you can see in the attached image (win11_updates.png) there are more hotfixes installed, many of them fix vulnerabilities detected by the vulnerabilities scan.
![win11_updates](https://github.com/wazuh/wazuh/assets/30633798/92b33ee1-794c-48f0-8a54-139f96ad24d4)

I have performed the following actions in order to solve the problem:
1- Disable syscollector in the agent, restart the agent, restart the manager and re-enable syscollector in theagent.
2- Stop the agent, stop the manager, delete the file associated to the agent /var/ossec/queue/db/008.db in the manager, start the manager and finally start the agent.
The result is the same in both cases, in the inventory only part of the hotfixes installed in windows 11 are shown.
Thank you very much in advance, best regards.

**Comment by MiguelazoDS** [comment]
Hello @tfmotu, 

Sorry for the delay, what I see is that you have Windows 11 22H2. Our team already found a solution for those false positives related to that specific version of Win11. The fix is implemented as part of this issue https://github.com/wazuh/wazuh/issues/15160 and will be released with Wazuh 4.4.4. 

Anyway, I'll take a look at those KBs in case there's something we are missing and I'll let you know what I find. Regards!

**Comment by tfmotu** [comment]
Hi MiguelazoDS, 
thanks for the reply. I'll test it.
Regards

**Comment by MiguelazoDS** [comment]
Hello, sorry for the delay. What I see about the KBs is that all the KBs from Windows are superseded by the ones Syscollector reported. For example this **KB5020044** is superseded by this one **KB5025305** 

I have not a date for that release but I hope we can delivery it soon. Regards!

**Comment by tfmotu** [comment]
Hi, thanks. After the upgrade no vulnerabilities are show in W11, corrected for me.
Thanks for your time and work.
Regards.

**Comment by MiguelazoDS** [comment]
Glad to know that! thanks to you for the feedback.
