### ISSUE TITLE
Review the timestamp logs of the RTR 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#17500]
## Description 

It was found that the logs of the RTR shown by Github Actions aren't flushed to the output until the end of the test.
For example:
https://github.com/wazuh/wazuh/actions/runs/5198072535/jobs/9373738111

![2023-06-08_11-18](https://github.com/wazuh/wazuh/assets/65046601/e830f013-4e19-48ab-bbc4-861003f8f67e)

A complete step that lasts 30 minutes has all the corresponding logs printed in the same minute.

It's important to check this behavior to give the developers reliable information analyzing the RTR output.

## DoD

- [x] Make the Python script print the logs unbuffered
- [x] Make sure the issue is fixed

**Comment by pereyra-m** [comment]
The RTR checks aren't working in master. This issue is blocked by #17574

**Comment by davidjiglesias** [comment]
@pereyra-m Block is released
