### ISSUE TITLE
Move scan build static analysis to Github Actions

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17502]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | Wazuh component | Manager/Agent | Sources | OS version |

# Description

This issue involves moving the scan-build static analysis tool to GitHub Actions. Currently, the static analysis is performed locally, which can be time-consuming and cumbersome for contributors. By integrating it into the GitHub Actions workflow, we can automate the analysis process and provide faster feedback to contributors.

### Proposed Solution

The proposed solution is to create a dedicated GitHub Actions workflow that runs the scan-build static analysis tool on the codebase. This workflow should be triggered on every pull request to ensure continuous analysis of the code. The analysis results should be displayed as annotations in the GitHub UI, allowing contributors to easily identify and address any potential issues.

### Tasks

- Create a new GitHub Actions workflow file specifically for scan-build static analysis.
- Configure the workflow to trigger on pull requests.
- Set up the necessary steps to run the scan-build static analysis tool.
- Ensure that the analysis results are displayed as annotations in the GitHub UI.
- Test the workflow on different branches to ensure its functionality and reliability.

### Expected Outcome

After moving the scan-build static analysis to GitHub Actions, contributors will benefit from automated and faster feedback on potential code issues. The analysis results will be readily available in the GitHub UI, allowing for easier identification and resolution of any identified problems.

**Comment by pereyra-m** [comment]
We could close this duplicate issue #17422
