### ISSUE TITLE
Same actions on differents machines but differents rules raised ?

### ISSUE THREAD

**Issue by BlaCkMatiK** [wazuh/wazuh#17511]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.4.3-40409 | Rules/Decoders | New/Error/Improve |

## Description

I have two different Windows 10 Pro machines with the Wazuh agent on it. When i test the rules by trying to errorly connect to RDP, one machine triggers the #18130 event and the other computer triggers the #60122 one.
Here are the differents rules and their files :

#18130 - 0220-msauth_rules.xml
```
<rule id="18130" level="5">
    <if_sid>18106</if_sid>
    <id>^529$|^4625$</id>
    <description>Windows: Logon Failure - Unknown user or bad password.</description>
    <info type="link">https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventid=4625</info>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```

#60122 - 0580-win-security_rules.xml
```
<rule id="60122" level="5">
    <if_sid>60105</if_sid>
    <field name="win.system.eventID">^529$|^4625$</field>
    <options>no_full_log</options>
    <description>Logon failure - Unknown user or bad password.</description>
    <mitre>
      <id>T1078</id>
      <id>T1531</id>
    </mitre>
    <group>authentication_failed,gdpr_IV_32.2,gdpr_IV_35.7.d,gpg13_7.1,hipaa_164.312.b,nist_800_53_AC.7,nist_800_53_AU.14,pci_dss_10.2.4,pci_dss_10.2.5,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```
Why the machines do not raise the sames events and rules, while performing the exact same actions on them ? Thx for help !

![image](https://github.com/wazuh/wazuh/assets/49946898/6e6ec524-5f43-499b-97d8-7fbeb482f5d2)

**Comment by nmkoremblum** [comment]
Hi BlaCkMatiK,

Do you happen to have enabled the `logall_json` option on your `ossec.conf` file? In case you do, you should be able to see such logs in the `archives.json` file

**Comment by BlaCkMatiK** [comment]
Sadly, this option was not enabled. But on the other hand, i was not able to reproduce this. I first thought it was i was trying to RDP on one and directly connect on the other one but it was not this.
Thanks for help !

**Comment by nmkoremblum** [comment]
Ok, good to know :smile:. Can I proceed with closing the issue, or is there anything else you would like to address or test before we consider it resolved?

**Comment by BlaCkMatiK** [comment]
Yes, as i am not able to reproduce this, it's not a problem for me anymore. Thanks ! 😄

**Comment by nmkoremblum** [comment]
Great then, do not hesitate to reach out again whenever you need our help
