### ISSUE TITLE
Audit rules not added by Wazuh

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#1752]
When a directory is configured with _WHODATA_ to be monitored in FIM audit rules are created with the key `wazuh_fim`. If another program or a user manually adds a rule to the same directory, Audit does not overwrite the rule but instead uses the same rule it generated before and applies its corresponding key. 
When FIM receives the audit events, it filters by means of the key with which it has created its rules to discard the events that do not interest it, this causes that the events generated by rules that are not overwritten and that have a different key are discarded.

**Comment by vikman90** [comment]
Related issue: #1613.
