### ISSUE TITLE
Investigate about the API integration tests stability

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17522]
## Description

This issue aims to initiate an investigation into the API integration tests' stability, possible improvements, and refactors. 

We noticed that they are unstable and sporadic. There is often no apparent failure in the logs, and they must be re-run to pass. This happens in `4.5`, `4.6` and in `master`.

The test typically marks many endpoints as failed, sometimes just one that is not repeated across executions.

## Related issues

- https://github.com/wazuh/wazuh/issues/17200
- https://github.com/wazuh/wazuh/issues/17588
- https://github.com/wazuh/wazuh/issues/17654
- https://github.com/wazuh/wazuh/issues/17690
- https://github.com/wazuh/wazuh-jenkins/issues/5323
- https://github.com/wazuh/wazuh-jenkins/issues/5435

#### Merge 4.4.4 into 4.4

Run: https://github.com/wazuh/wazuh/pull/17578/checks?check_run_id=14251322424

Artifacts: [artifacts.zip](https://github.com/wazuh/wazuh/files/11745842/artifacts.zip)

#### Add distinct to multiple endpoints

https://github.com/wazuh/wazuh/pull/16867/checks?check_run_id=14195098445

#### Add query, select and distinct parameters to API endpoints

https://ci.wazuh.info/job/Test_integration_endpoints/3588/

Artifacts: [artifacts.zip](https://github.com/wazuh/wazuh/files/12111531/artifacts.zip)

**Comment by GGP1** [comment]
## Update

We have been investigating the AIT failures in https://github.com/wazuh/wazuh/issues/17588 and we have found two potential issues with them:

- The nginx Docker container entrypoint was using the `service` command to start the server and in the latest version of the official Docker image the command is no longer pre-installed, causing nginx to fail repeteadly at the start of the setup. A fix is being developed in https://github.com/wazuh/wazuh/issues/17690.
- The CPU utilization of the tests reached 100% and crashed the host when running them in EC2 t3a medium instances (the ones Jenkins use) as explained [here](https://github.com/wazuh/wazuh/issues/17200#issuecomment-1607841169). We are analyzing the possibility of increasing the specs of the instances to avoid this in https://github.com/wazuh/wazuh-jenkins/issues/5323

**Comment by mhamra** [comment]
### UPDATE

Results after pushing commits in [PR 17703](https://github.com/wazuh/wazuh/pull/17703):

- [Run 3418](https://ci.wazuh.info/job/Test_integration_endpoints/3418/) : all test succeded.
- [Run  3420](https://ci.wazuh.info/job/Test_integration_endpoints/3420/): all tests succeeded except test_cluster_endpoints. The failure was caused by a call that exceeded the API timeout. We suspect that is caused by low resource environment conditions, not an nginx problem.

**Comment by mhamra** [comment]
### UPDATE

Launched the pipeline using jeninks branch 5323-increase-specs-API-integration-tests


![Image](https://github.com/wazuh/wazuh/assets/2949519/2b96f51c-38a1-420e-9c7f-4d9eb8718c54)

All tests succeeded. 

Artifacts and logs can be found in [Jenkins build 3425](https://ci.wazuh.info/job/Test_integration_endpoints/3425/)

**Comment by GGP1** [comment]
## Update

The last 6 test executions that used the jenkins `master` branch which contains the changes from https://github.com/wazuh/wazuh-jenkins/pull/5536 were successful. The builds contain all the artifacts and no ssh connection errors occured.

Considering that the tests rarely passed before this change, I think it is enough evidence to determine whether the problem has been solved or not (more executions could be observed if necessary), and we should proceed with this issue's review. 

### Artifacts

- [3835.zip](https://github.com/wazuh/wazuh/files/12674929/3835.zip)
- [3837.zip](https://github.com/wazuh/wazuh/files/12674930/3837.zip)
- [3839.zip](https://github.com/wazuh/wazuh/files/12674932/3839.zip)
- [3844.zip](https://github.com/wazuh/wazuh/files/12674936/3844.zip)
- [3846.zip](https://github.com/wazuh/wazuh/files/12674938/3846.zip)
- [3847.zip](https://github.com/wazuh/wazuh/files/12674941/3847.zip)

**Comment by RamosFe** [comment]
LGTM ✅
