### ISSUE TITLE
Removing a Wazuh Agent from CLI not working

### ISSUE THREAD

**Issue by njmulsqb** [wazuh/wazuh#17566]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.4 |Agent Management | Manager  | Ubuntu |

I am trying to delete connected wazuh agents through CLI using command 
`/var/ossec/bin/manage_agents` it works but soon the agent gets listed again on the dashboard with a new ID and all the tags refreshed.
Note, the agent is working fine on the VM and is not disconnected

**Comment by njmulsqb** [comment]
If I set the enrollment to disabled, then what will happen for future deployment of agents? Do I have to add them manually after configuring the agent on the target server?

**Comment by mauromalara** [comment]
@njmulsqb The enrollment option that I mentioned is configured on the agent side. If you want to disable auto-enrollment for **all** agents, you should disable the [`remote_enrollment`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#remote-enrollment) option which is configured on the manager side; if you do so, you shall enroll your agents manually [using the Manager's API](https://documentation.wazuh.com/current/user-manual/agent-enrollment/via-manager-API/index.html).

**Comment by njmulsqb** [comment]
If I had to make this change on agent side, why dont I remove the agent software from the server? Won't it be better?

**Comment by mauromalara** [comment]
@njmulsqb Sorry, I'm not understanding your question or issue here. Could you better explain what your problem/need is?

**Comment by njmulsqb** [comment]
I just want to remove an agent from Wazuh server, I followed the guide but the agent kept coming back. You mentioned that removing process also required changing the conf on agent ( shouldnt it be part of the docs as well? ), so I am saying that what if instead of changing the conf on agent, I remove the wazuh agent software from scratch?

**Comment by mauromalara** [comment]
@njmulsqb

Let me explain it better for you to understand:

If you **do not stop** your agent OR change **one** of the following configurations, the agent will keep connecting to the manager again:

1. The [`enrollment`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enabled) option in the agent (enabled by default)
3. The [`remote_enrollment`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#remote-enrollment) option in the manager (enabled by default)

> **Note**: You **must** restart the manager/agent after applying the configuration. You can do it using systemd: `systemctl restart wazuh-<manager or agent>` or wazuh-control: `/var/ossec/bin/wazuh-control restart` (or via GUI if you're using a Windows agent)

Therefore, if you want to **remove an agent from the manager and not monitor it anymore**, you should:

1. Stop the agent by running:
```Bash
systemctl stop wazuh-agent
```
> Or `/var/ossec/bin/wazuh-control stop`, or via GUI if you have installed it on Windows.
2. Remove it from the manager by running: 
```Bash
/var/ossec/bin/manage_agents -r AGENT-ID
```
3. Uninstall the agent ([Linux guide here](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html#uninstall-a-wazuh-agent), explore how to do it in the rest of OS inside [this section](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html#))

**Comment by fcaffieri** [comment]
This issue is closed due to lack of response. In any case @njmulsqb, you can reopen it without a problem.
