### ISSUE TITLE
Class repetition in the AWS module

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#17569]
|Wazuh version|Component|
|---|---|
| 4.5 | AWS module | 

It was found a repetition of classes, `AWSSQSQueue` and `AWSSLSubscriberBucket`, in the branches `4.5` and `master` in the AWS module file (`wodles/aws/aws_s3.py`) due to the merge of the branch `4.4`.

Here are the occurrences in branch `4.5`:
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3119
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3185
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3305
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3371
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3490
https://github.com/wazuh/wazuh/blob/97532d1acf5324feb3899adce6f2c235f9c3b1fc/wodles/aws/aws_s3.py#L3556

The team has not found any direct issues yet but it should be addressed before the upcoming merges.

**Comment by RamosFe** [comment]
## Update

Deleted repeated occurrences of:
- `AWSSLSubscriberBucket` (Line 3305)
- `AWSSQSQueue` (Line 3371)
- `AWSSLSubscriberBucket` (Line 3490)
- `AWSSQSQueue` (Line 3556)
