### ISSUE TITLE
Timeout with GET /security/user/authenticate in footprint tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#17572]
|Wazuh version|
|---|
| 4.4.4-rc2| 

## Description

During the footprint tests, the following error was seen to appear several times:

```
2023/06/12 16:22:32 ERROR: Timeout executing API request
2023/06/12 16:22:32 INFO: wazuh 127.0.0.1.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.093s: 500
2023/06/12 16:22:44 INFO: wazuh 127.0.0.1.1 "GET /security/user/authenticate" with parameters {} and body {} done in 11.934s: 200
```

We need to investigate if the error is due to environment saturation, or if there is a solution.

[Manager logs](https://github.com/wazuh/wazuh/files/11736078/ossec_Test_stress_B4049_manager_2023-06-12.2.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Investigated here:
- https://github.com/wazuh/wazuh/issues/19221
