### ISSUE TITLE
windows xp sp4, with agent wazup 3.6.1

### ISSUE THREAD

**Issue by julioh** [wazuh/wazuh#1757]
## Bug report

**OS**
_Windows Xp_

**Wazuh version**
agent wazup 3.6.1

**Wazuh API version**
agent wazup 3.6.1

**Install type**
_agent_

Log sample
```
ossec-agent: CRITICAL: Could not get security token from ser
ver. Run ossec-authd with "-a" option and enable RC4 or 3DES cipher.
Bug description
----------------

hi i have windows xp sp4, with agent wazup 3.6.1, and can not login with agent_auth method, the error is:

139955118769920:error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:1404:
2018/10/24 23:51:11 ossec-authd: DEBUG: SSL Error (-1)

when I try login from windows server with:

agent-auth.exe -m 10.xxxx -P xxxxxx
2018/10/24 23:51:47 ossec-agent: CRITICAL: Could not get security token from ser
ver. Run ossec-authd with "-a" option and enable RC4 or 3DES cipher.

**Comment by TJOSERAFAEL** [comment]
Hi @julioh,

as you can see the error 

> Run ossec-authd with "-a" option and enable RC4 or 3DES cipher

 says to enable one of those cipher methods. 

To do this:

1. On your **manager** edit the _/var/ossec/etc/ossec.conf_ file:

```
<auth>
...
<ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
...
</auth>
```

You must remove the **"!"** character from **RC4** or **3DES**. 
Now **restart** your **manager** and your **ossec-authd** daemon.

Tell me if it worked for you.

Best regards.

**Comment by julioh** [comment]
Hi Jose Rafael.
 it's work fine.

Thanks.

Best regards

**Comment by TJOSERAFAEL** [comment]
Hi @julioh ,

I'm going to close this issue.

Best regards.
