### ISSUE TITLE
Maintain production and numbered branches post release v4.4.4

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#17574]
The goal is to complete the following tasks, each task must have a PR associated with this issue. 

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, merge-4.4.4-into-4.4.

Also, all PRs corresponding to the same phase (merge-X-into-Y) must be merged at the same time.

### Wazuh-jenkins Repository

- [x] Merge branch `4.4.4` into `4.4` on wazuh-jenkins repository 
- [x] Merge branch `4.4` into `4.4.5` on wazuh-jenkins repository
- [x] Merge branch `4.4.5` into `4.5` on wazuh-jenkins repository
- [x] Merge branch `4.5` into `master` on wazuh-jenkins repository

### Wazuh-qa Repository

- [x] ~Merge branch `4.4.4` into `4.4` on wazuh-qa repository~ (No 4.4.4 branch in wazuh-qa)
- [x] Merge branch `4.4` into `4.4.5` on wazuh-qa repository
- [x] Merge branch `4.4.5` into `4.5` on wazuh-qa repository
- [x] Merge branch `4.5` into `master` on wazuh-qa repository

### Wazuh-packages Repository

- [x] Merge branch `4.4.4` into `4.4` on wazuh-packages repository
- [x] Merge branch `4.4` into `4.4.5` on wazuh-packages repository
- [x] Merge branch `4.4.5` into `4.5` on wazuh-packages repository
- [x] Merge branch `4.5` into `master` on wazuh-packages repository

### Wazuh Repository (THIS PR needs the above branches to be already created!!!)

- [x] Merge branch `4.4.4` into `4.4` on wazuh repository 
- [x] Merge branch `4.4` into `4.4.5` on wazuh repository
- [x] Merge branch `4.4.5` into `4.5` on wazuh repository
- [x] Merge branch `4.5` into `master` on wazuh repository

**Comment by rauldpm** [comment]
- Created https://github.com/wazuh/wazuh-packages/pull/2232

**Comment by jnasselle** [comment]
- Created https://github.com/wazuh/wazuh-jenkins/pull/5290

**Comment by davidjiglesias** [comment]
- Created https://github.com/wazuh/wazuh/pull/17578

**Comment by jnasselle** [comment]
- Created https://github.com/wazuh/wazuh-jenkins/pull/5294

**Comment by rauldpm** [comment]
- Created https://github.com/wazuh/wazuh-packages/pull/2234/

**Comment by Rebits** [comment]
Created https://github.com/wazuh/wazuh-qa/pull/4235

**Comment by juliamagan** [comment]
- Created https://github.com/wazuh/wazuh-qa/pull/4236

**Comment by Rebits** [comment]
- Created https://github.com/wazuh/wazuh-jenkins/pull/5296

**Comment by verdx** [comment]
- Created https://github.com/wazuh/wazuh-packages/pull/2235

**Comment by davidjiglesias** [comment]
- Created https://github.com/wazuh/wazuh/pull/17592

**Comment by davidjiglesias** [comment]
- Created https://github.com/wazuh/wazuh/pull/17594

**Comment by BelenValdivia** [comment]
- Created https://github.com/wazuh/wazuh-jenkins/pull/5297
