### ISSUE TITLE
Error in manager: couldn't sync agent '001' group

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#17573]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.12.0 | Manager | Packages/Sources | Ubuntu Focal |

During the current RC, we have observed that an error is encountered when updating from version 3.12.0 to 4.4.4. The error message is as follows:

```
Error getting agent's group sync: Error 1701 - Agent does not exist: 001
```

This issue was previously reported and resolved in https://github.com/wazuh/wazuh/issues/2968

> There are no artifacts available to be attached due to the issue reported in https://github.com/wazuh/wazuh-jenkins/issues/5288

> Build: https://ci.wazuh.info/job/Test_upgrade/119660/console

**Comment by TomasTurina** [comment]
The modules involved will be refactored, so this issue will not be addressed.
