### ISSUE TITLE
Rule false positives

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#17585]
Hi,

I update newest rule from wazuh-master repo. when connect agent to manager, i realize that many alerts not corect for my agent.
I call it is false-positives.
Can you have any way help me to filter that rules with a field note some cases that can trigger alert with false-positives, false-positives may be from trust software or activity of administrator ?

Best regards,

**Comment by nmkoremblum** [comment]
Hi @thanvantrong,

Could you please provide more details about the specific alerts that are not correct for your agent? It would be helpful if you could share examples of these false positives and any patterns or scenarios that may trigger them. This will allow us to investigate the issue and help you filter the rules effectively. By providing us with more information, we can work towards finding a suitable solution.

Best regards,

Mariano Koremblum

**Comment by thanvantrong** [comment]
Hi,

Example for this rules
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/20339287-8e6d-4825-aed6-5009c0bec6e3)
https://github.com/wazuh/wazuh/blob/master/ruleset/rules/0945-sysmon_id_10.xml#L22

I received manay alerts with level 12 (high) with this, example when i use Telegram this alert is triggered many time
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/b9d24e41-4664-4f8d-833d-3e80f90b9855)

I know i can fix it with **overwrite** option in rule syntax, but have any advice for other rule if it have false-positives like that.

Best regards,

**Comment by nmkoremblum** [comment]
I am sorry, please correct me if I am wrong. Do you mean that you don't want such events to match the rule? Why do you say it is a false-positive? how is the log?

**Comment by thanvantrong** [comment]
I think i can create new rule with if_sid to solve my problem.

Thanks for your help,
Best regards,
