### ISSUE TITLE
Remoted show `Too big message size from socket` after receiving a Wazuh agent message

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#17596]
|Wazuh version|Component|Install type|Install method|Manager|Agent|
|---|---|---|---|---|---|
| 4.6 (master)| wazuh-remoted | Manager| Packages | CentOS 7 |macOS & CentOS|

# Description

During https://github.com/wazuh/wazuh/pull/17594 checks, it was found that `Install manager on CentOS 7 (amd64) (macos-1015)` fails, showing the next message

```
2023/06/15 16:42:28 wazuh-authd: INFO: New connection from 10.10.0.251
2023/06/15 16:42:28 wazuh-authd: INFO: Received request for a new agent (macos-1015) from: 10.10.0.251
2023/06/15 16:42:28 wazuh-authd: INFO: Agent key generated for 'macos-1015' (requested by any)
2023/06/15 16:42:36 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/06/15 16:42:36 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2023/06/15 16:43:16 wazuh-remoted: WARNING: Too big message size from socket [12].
2023/06/15 16:43:16 wazuh-remoted: ERROR: (2202): Error uncompressing string. Message received from agent '001' at 'any'
2023/06/15 16:43:16 wazuh-remoted: WARNING: Decrypt the message fail, socket 12
```

Jenkins job: https://ci.wazuh.info/job/Test_install/127886

**Comment by vikman90** [comment]
We've seen this message also on CentOS agents: https://github.com/wazuh/wazuh/issues/18937.

**Comment by juliamagan** [comment]
We've seen this message in [4.6.0 AMI](https://github.com/wazuh/wazuh/issues/18869#issuecomment-1711474315), too.

**Comment by rauldpm** [comment]
Seen in Solaris 10 SPARC v4.5.3-rc2: https://github.com/wazuh/wazuh/issues/19322#issuecomment-1742491482

**Comment by vikman90** [comment]
## Status update

Quick win by @santiago-bassett.
Priority: very high.
Target: 4.7.2.

**Comment by vikman90** [comment]
## Update

We suspect that the agent is the source of the bug, not the manager. It seems to be related to some timing condition, but we are still investigating the exact reason for the problem.

### Action items

- Modify the Remoted message to print the log as a warning, and add the first bytes of the message.
- Create a **new issue** to identify and fix the problem. We will provide an ETA and release date once we know the cause of the bug.

**Comment by TomasTurina** [comment]
@vikman90 this is the associated issue: https://github.com/wazuh/wazuh/issues/21014
