### ISSUE TITLE
Engine - Review the fields inserted by Filebeat in the processed events

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#17615]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Currently, in the engine, we are experiencing the insertion of several fields in the events processed by Filebeat. It is crucial that we conduct an investigation into these fields and remove any that do not provide essential information.

**Comment by JavierBejMen** [comment]
Host fields are added by default when using the type log in filebeat configuration, to disable them add the option:
```
publisher_pipeline.disable_host: true
```

Ref: https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-reference-yml.html
