### ISSUE TITLE
active-response is not being executed

### ISSUE THREAD

**Issue by richardkraus-adesso** [wazuh/wazuh#17611]
| Wazuh version | Component       | Install type  | Install method | Platform          |
| ---           | ---             | ---           | ---            | ---               |
| 4.4.4         | Active Response | Manager/Agent | Docker/Package | Kubernetes/Ubuntu |

I cannot get a custom active-response to execute when a rule is being matched.
Im using minimally configured [wazuh-kubernetes](https://github.com/wazuh/wazuh-kubernetes) with a VM from the kubernetes cluster running the agent.

# Description

The basic manager config is extended by
```xml
  <command>
    <name>test</name>
    <executable>test.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>

  <active-response>
    <command>test</command>
    <location>server</location>
    <level>1</level>
  </active-response>
```
which should, as I understand the documentation, execute `/var/ossec/active-response/bin/test.sh` on any rule.
`test.sh` is present and executeable on both agent and master and logs its arguments to a log file (see full setup below):
```sh
#!/bin/bash
{
       echo "$(date --iso=seconds) Testing as "$0" $@:"
       timeout 1s cat -
} >> /tmp/testing.log
echo '{"ok": "cool"}'
```

When using `<location>server</location>`, my custom command is executed exactly three times upon each reboot (2x `rootcheck` and one `wazuh server started`, see below for full input), but not for any other rule matches generated by my own bruteforcing or other means.

When using `<location>local</location>` my custom command is not run at all, or at least I dont see any output in my logfile.
I can trigger the response on the remote agent via the API (see below for script) and can see the output in the logfile.

When enabling the debug options in `/var/ossec/etc/internal_options.conf` I see no comments to either response being routed, even if it is eventually executed on the agent (as is the case when directly using the API):
```ini
remoted.debug=2
analysisd.debug=2
```

I will be grateful for any pointers on how to debug active responses (correctly).

# Reference

## bruteforce
To test the configuration I use [ssb](https://github.com/pwnesia/ssb), which does generate rule matches visible in the dashboard.
```sh
ssb -w /usr/share/dict/rockyou.txt imfriendly@${AGENT_IP:?}
```

## triggering the command via the API

I can successfully trigger the response on the agent, the error should therefore be in the handling of the active-response configuration since the command block seems to be functional.
```sh
#!/bin/bash

HOST="${1:?"Usage: $0 <host>:<port> <agent_id> [<command>]"}"
AGENT="${2:?"Usage: $0 <host>:<port> <agent_id> [<command>]"}"
COMMAND="${3:-!test.sh}"
AUTH='wazuh-wui:MyS3cr37P450r.*-'

TOKEN=$(curl --basic --user "$AUTH" --insecure "https://$HOST/security/user/authenticate?raw=true")
curl --oauth2-bearer "$TOKEN" --insecure -X PUT "https://$HOST/active-response?agents_list=$AGENT" --json '{"arguments": ["apitrigger"], "command": "'"$COMMAND"'"}'
```

## cluster setup

```sh
git clone --depth=1 --branch=stable https://github.com/wazuh/wazuh-kubernetes.git
cd wazuh-kubernetes
# fix wazuh-kubernetes
sed -i '/patches/,$ s/  -/  - path:/' envs/local-env/kustomization.yml
# change storage class to longhorn
sed -i '/^provisioner:/c provisioner: driver.longhorn.io' envs/local-env/storage-class.yaml
# generate certs
./wazuh/certs/indexer_cluster/generate_certs.sh
./wazuh/certs/dashboard_http/generate_certs.sh

kubectl apply -k envs/local-env/

# find ports for agent configuration below
kubectl get -n wazuh services wazuh wazuh-workers
```

### configuring the master
```sh
# kubectl exec -it -n wazuh pods/wazuh-manager-master-0 -- bash

# deploy active response on manager (location: server)
cat > /var/ossec/active-response/bin/test.sh << EOF
#!/bin/bash
{
       echo "\$(date --iso=seconds) Testing as "\$0" \$@:"
       timeout 1s cat -
} >> /tmp/testing.log
echo '{"ok": "cool"}'
EOF
chmod 750 /var/ossec/active-response/bin/test.sh
chown root:wazuh /var/ossec/active-response/bin/test.sh

# make configuration changes idempotent by saving a copy:
cp /var/ossec/etc/ossec.conf{,.original}

# change the configuration, run again from here to change e.g. the location
sed '/^  <!-- Active response -->/c \
  <command>\
    <name>test</name>\
    <executable>test.sh</executable>\
    <timeout_allowed>no</timeout_allowed>\
  </command>\
\
  <active-response>\
    <command>test</command>\
    <location>local</location>\
    <level>1</level>\
  </active-response>\
' /var/ossec/etc/ossec.conf.original > /var/ossec/etc/ossec.conf

/var/ossec/bin/wazuh-control restart
```

## agent setup

```sh
# on agent (ssh user@agent)
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
echo "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt-get update

apt-get install wazuh-agent=4.4.4-1
# configure manually because environment variables didnt work:
# ports and CLUSTER_IP from: kubectl get services -n wazuh
diff -u /var/ossec/etc/ossec.conf{.original,}
# --- /var/ossec/etc/ossec.conf.original  2023-06-20 11:56:22.358903394 +0000
# +++ /var/ossec/etc/ossec.conf   2023-06-20 12:01:43.382499494 +0000
# @@ -7,10 +7,14 @@
#  <ossec_config>
#    <client>
#      <server>
# -      <address>MANAGER_IP</address>
# -      <port>1514</port>
# +      <address>CLUSTER_IP</address>
# +      <port>32533</port>
#        <protocol>tcp</protocol>
#      </server>
# +    <enrollment>
# +      <manager_address>CLUSTER_IP</manager_address>
# +      <port>32263</port>
# +    </enrollment>
#      <config-profile>ubuntu, ubuntu20, ubuntu20.04</config-profile>
#      <notify_time>10</notify_time>
#      <time-reconnect>60</time-reconnect>

echo "password" > /var/ossec/etc/authd.pass

# deploy active response on agent (location: local)
cat > /var/ossec/active-response/bin/test.sh << EOF
#!/bin/bash
{
       echo "\$(date --iso=seconds) Testing as "\$0" \$@:"
       timeout 1s cat -
} >> /tmp/testing.log
echo '{"ok": "cool"}'
EOF
chmod 750 /var/ossec/active-response/bin/test.sh
chown root:wazuh /var/ossec/active-response/bin/test.sh

systemctl daemon-reload
systemctl start wazuh-agent
```

## events logged by the server location

```json
{
  "version": 1,
  "origin": {
    "name": "wazuh-manager-master",
    "module": "wazuh-execd"
  },
  "command": "add",
  "parameters": {
    "extra_args": [],
    "alert": {
      "timestamp": "2023-06-20T12:45:43.869+0000",
      "rule": {
        "level": 7,
        "description": "Host-based anomaly detection event (rootcheck).",
        "id": "510",
        "firedtimes": 1,
        "mail": false,
        "groups": [
          "ossec",
          "rootcheck"
        ],
        "pci_dss": [
          "10.6.1"
        ],
        "gdpr": [
          "IV_35.7.d"
        ]
      },
      "agent": {
        "id": "000",
        "name": "wazuh-manager-master-0"
      },
      "manager": {
        "name": "wazuh-manager-master-0"
      },
      "id": "1687265143.48587",
      "cluster": {
        "name": "wazuh",
        "node": "wazuh-manager-master"
      },
      "full_log": "File '/dev/termination-log' present on /dev. Possible hidden file.",
      "decoder": {
        "name": "rootcheck"
      },
      "data": {
        "title": "File present on /dev.",
        "file": "/dev/termination-log"
      },
      "location": "rootcheck"
    },
    "program": "active-response/bin/test.sh"
  }
}
```
```json
{
  "version": 1,
  "origin": {
    "name": "wazuh-manager-master",
    "module": "wazuh-execd"
  },
  "command": "add",
  "parameters": {
    "extra_args": [],
    "alert": {
      "timestamp": "2023-06-20T12:45:44.166+0000",
      "rule": {
        "level": 7,
        "description": "Host-based anomaly detection event (rootcheck).",
        "id": "510",
        "firedtimes": 2,
        "mail": false,
        "groups": [
          "ossec",
          "rootcheck"
        ],
        "pci_dss": [
          "10.6.1"
        ],
        "gdpr": [
          "IV_35.7.d"
        ]
      },
      "agent": {
        "id": "000",
        "name": "wazuh-manager-master-0"
      },
      "manager": {
        "name": "wazuh-manager-master-0"
      },
      "id": "1687265144.48587",
      "cluster": {
        "name": "wazuh",
        "node": "wazuh-manager-master"
      },
      "full_log": "File '/dev/termination-log' is owned by root and has written permissions to anyone.",
      "decoder": {
        "name": "rootcheck"
      },
      "data": {
        "title": "File is owned by root and has written permissions to anyone.",
        "file": "/dev/termination-log"
      },
      "location": "rootcheck"
    },
    "program": "active-response/bin/test.sh"
  }
}
```
```json
{
  "version": 1,
  "origin": {
    "name": "wazuh-manager-master",
    "module": "wazuh-execd"
  },
  "command": "add",
  "parameters": {
    "extra_args": [],
    "alert": {
      "timestamp": "2023-06-20T12:45:46.465+0000",
      "rule": {
        "level": 3,
        "description": "Wazuh server started.",
        "id": "502",
        "firedtimes": 1,
        "mail": false,
        "groups": [
          "ossec"
        ],
        "pci_dss": [
          "10.6.1"
        ],
        "gpg13": [
          "10.1"
        ],
        "gdpr": [
          "IV_35.7.d"
        ],
        "hipaa": [
          "164.312.b"
        ],
        "nist_800_53": [
          "AU.6"
        ],
        "tsc": [
          "CC7.2",
          "CC7.3"
        ]
      },
      "agent": {
        "id": "000",
        "name": "wazuh-manager-master-0"
      },
      "manager": {
        "name": "wazuh-manager-master-0"
      },
      "id": "1687265146.48915",
      "cluster": {
        "name": "wazuh",
        "node": "wazuh-manager-master"
      },
      "full_log": "ossec: Manager started.",
      "decoder": {
        "name": "ossec"
      },
      "location": "wazuh-monitord"
    },
    "program": "active-response/bin/test.sh"
  }
}
```

**Comment by nmkoremblum** [comment]
Hi @richardkraus-adesso ,
I think the problem is that you are not setting any [rules_group](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html#rules-group) nor [rules_id](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html#rules-id), the `level` filters out the events that match one of these two configurations.

**Comment by nmkoremblum** [comment]
In addition to your other question, to test `active-response` you must enable the `execd` debug

**Comment by richardkraus-adesso** [comment]
I changed the definition of the active response in the manager to include the rules_id field:
```xml
  <command>
    <name>test</name>
    <executable>test.sh</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>

  <active-response>
    <command>test</command>
    <location>local</location>
    <rules_id>5710,</rules_id>
    <level>1</level>
  </active-response>
```
and added `exec.debug=2` to both agent and manager:
```sh
# on manager:
grep -F '.debug=2' /var/ossec/etc/internal_options.conf
# remoted.debug=2
# analysisd.debug=2
# execd.debug=2

# on agent:
grep -F '.debug=2' /var/ossec/etc/internal_options.conf
# execd.debug=2
```

However, the symponts remain unchanged.

Confusingly, I still dont get any hint in the logs towards the rule being processed, only the following is showing up on the manager:
```
# tail -f /var/ossec/logs/ossec/log
2023/06/21 07:59:37 wazuh-remoted[6296] state.c:161 at rem_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:39 wazuh-analysisd[6271] state.c:277 at w_analysisd_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:41 wazuh-remoted[6296] manager.c:764 at c_files(): DEBUG: Updating shared files sums.
2023/06/21 07:59:41 wazuh-remoted[6296] manager.c:786 at c_files(): DEBUG: End updating shared files sums.
2023/06/21 07:59:42 wazuh-remoted[6296] secure.c:374 at rem_keyupdate_main(): DEBUG: Checking for keys file changes.
2023/06/21 07:59:42 wazuh-remoted[6296] state.c:161 at rem_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:44 wazuh-analysisd[6271] state.c:277 at w_analysisd_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:47 wazuh-remoted[6296] state.c:161 at rem_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:49 wazuh-analysisd[6271] state.c:277 at w_analysisd_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:51 wazuh-remoted[6296] manager.c:764 at c_files(): DEBUG: Updating shared files sums.
2023/06/21 07:59:51 wazuh-remoted[6296] manager.c:786 at c_files(): DEBUG: End updating shared files sums.
2023/06/21 07:59:52 wazuh-remoted[6296] secure.c:374 at rem_keyupdate_main(): DEBUG: Checking for keys file changes.
2023/06/21 07:59:52 wazuh-remoted[6296] state.c:161 at rem_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:54 wazuh-analysisd[6271] state.c:277 at w_analysisd_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:57 wazuh-remoted[6296] state.c:161 at rem_write_state(): DEBUG: Updating state file.
2023/06/21 07:59:59 wazuh-analysisd[6271] state.c:277 at w_analysisd_write_state(): DEBUG: Updating state file.
2023/06/21 08:00:01 wazuh-remoted[6296] manager.c:764 at c_files(): DEBUG: Updating shared files sums.
2023/06/21 08:00:01 wazuh-remoted[6296] manager.c:786 at c_files(): DEBUG: End updating shared files sums.
```
while the agent does not output anything.
On the dashboard, the ssh bruteforce attempts do show up and have the rule id `5710` associated with them, as can be seen on the screenshot of a match from the same timeframe (manager is UTC, while the dashboard shows UTC+2):
![image](https://github.com/wazuh/wazuh/assets/136313436/4f96c6c4-1d95-4582-9cfe-4265ca6700f4)

I can also observe the manager still executing the response three times on restart, even with the added `rules_id` option in the active-response configuration.
While the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html#rules-id) is not explicit what happens when only one is specified, it does state that the `level`, `rules_group`, and `rules_id` options are "accumulative, not restrictive".

When triggering via API, I can see the impact in both my and `ossec.log` on the agent:
```
2023/06/21 08:03:26 wazuh-execd[3696637] execd.c:494 at ExecdStart(): DEBUG: Received message: '{"version": 1, "origin": {"name": "wazuh-manager-worker-0", "module": "framework"}, "command": "!test.sh", "parameters": {"extra_args": ["apitrigger"], "alert": {}}}'
2023/06/21 08:03:26 wazuh-execd[3696637] execd.c:256 at ExecdRun(): DEBUG: Executing command 'active-response/bin/test.sh {"version":1,"origin":{"name":"wazuh-manager-worker-0","module":"wazuh-execd"},"command":"add","parameters":{"extra_args":["apitrigger"],"alert":{},"program":"active-response/bin/test.sh"}}'
```

**Comment by richardkraus-adesso** [comment]
Interestingly, the initial configuration seems to work as expected with a [wazuh-docker](https://github.com/wazuh/wazuh-docker) setup.

I did the following on another cluster VM:
```sh
git clone --branch=stable --depth=1 https://github.com/wazuh/wazuh-docker.git
cd wazuh-docker

sudo sysctl -w vm.max_map_count=262144
docker-compose -f multi-node/generate-indexer-certs.yml run --rm generator

# prevent collisions with kubernetes ingress
git diff
# --- a/multi-node/docker-compose.yml
# +++ b/multi-node/docker-compose.yml
# @@ -141,7 +141,7 @@ services:
#      hostname: wazuh.dashboard
#      restart: always
#      ports:
# -      - 443:5601
# +      - 4433:5601

docker-compose -f multi-node/docker-compose.yml up -d
```
before doing the exact same setup steps inside the master container (using `docker exec -it multi-node_wazuh.master_1 bash` instead of `kubectl exec ...`).
I also activated password authentication, but that should be irrelevant.

When reinstalling and configuring the agent the same way as before, but using the IP of the other cluster VM as manager, all rules visible on the dashboard trigger execution on the agent.

It would seem that the issue is related to kubernetes networking, but I honestly dont know how.
As a test I set up a completely separate VM outside of the cluster as an agent, but it behaves exactly like the one that is part of the cluster.

I feel like I am missing the tools to reasonably debug the active-response component since I cant see any logs related to the rules being matched, the resulting active-responses to be executed or the dispatching of remote active responses.

**Comment by richardkraus-adesso** [comment]
Do you have any other ideas I could try, @nmkoremblum ?

**Comment by nmkoremblum** [comment]
Hi again @richardkraus-adesso,

I apologize for the delay. To ensure we cover all possibilities, have you reviewed the logs for `active-response` and the `ossec.log` file? Please check if there are any errors or warnings related to this issue.

Your active-response configuration is set to execute on the "local" machine, meaning the script should be present on the agent that triggered the alert where it will be executed, and it has to have the right execution permissions.

If possible, additionally, please try removing the `level` label.

I look forward to your response.

Best regards,

**Comment by richardkraus-adesso** [comment]
There is nothing in the logs indicating an error of any active response related component.

The script is present and executeable since:
- im using the same script to setup the agent
- i can trigger the active response via API (the issue is the `active-response`, not the `command`)

I dont see what removing the level would do, since the same agent works as expected with a docker-compose configuring ONLY `level`.

I have noticed that kubernetes is apparently using [older configuration files from ubuntu 16](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/wazuh_managers/wazuh_conf/master.conf) (at least as a base), while docker-compose [removed the preamble](https://github.com/wazuh/wazuh-docker/blob/master/multi-node/config/wazuh_cluster/wazuh_manager.conf). However I have not been able to spot a configuration option that would justify the ignored active-response block.

Again, It feels like there should be an option to log active-response **decisions** and not just the final dispatching. I just cant seem to find it.

**Comment by nmkoremblum** [comment]
When you say that you have checked the `active-responses.log` and `ossec.log` log files, do you mean that you have checked on the agent's logs right?

**Comment by nmkoremblum** [comment]
Additionally, did you try copying the configuration from the agent that works to the one that does not?

**Comment by richardkraus-adesso** [comment]
I have checked on the agent as well, but as expected, there are not entries since the manager did not dispatch any responses.

There is no "working/not working" agent, its the same machine configured in the same way except for a different manager (full reinstall/purge).
When using the default docker-compose as manager, the active response is executed.
When using the default kubernetes deployment as manager, the active response is not dispatched.

I will try and use the working docker-compose `ossec.conf` in the kubernetes deployment to maybe find a meaningful difference, but in yesterdays tests the agent was not able to connect at all.

**Comment by richardkraus-adesso** [comment]
Ok, I dont think it is down to a difference in `/var/ossec/etc/ossec.conf`.
I have copied the working docker-compose config into the kubernetes deployment with minimal adjustments(see below) and it behaves the same as the default kubernetes config.

```diff
--- ../docker.xml       2023-06-27 11:50:08.397640304 +0200
+++ wazuh/wazuh_managers/wazuh_conf/master.conf 2023-06-27 11:29:14.148082214 +0200
@@ -329,7 +329,7 @@
     <port>1515</port>
     <use_source_ip>no</use_source_ip>
     <purge>yes</purge>
-    <use_password>no</use_password>
+    <use_password>yes</use_password>
     <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
     <!-- <ssl_agent_ca></ssl_agent_ca> -->
     <ssl_verify_host>no</ssl_verify_host>
@@ -340,13 +340,13 @@

   <cluster>
     <name>wazuh</name>
-    <node_name>manager</node_name>
+    <node_name>wazuh-manager-master</node_name>
     <node_type>master</node_type>
-    <key>c98b6ha9b6169zc5f67rae55ae4z5647</key>
+    <key>123a45bc67def891gh23i45jk67l8mn9</key>
     <port>1516</port>
     <bind_addr>0.0.0.0</bind_addr>
     <nodes>
-        <node>wazuh.master</node>
+        <node>wazuh-manager-master-0.wazuh-cluster.wazuh</node>
     </nodes>
     <hidden>no</hidden>
     <disabled>no</disabled>
```

**Comment by nmkoremblum** [comment]
HI Richard,

How are you copying the AR script to the agent? Please let us know if you have any update.

**Comment by richardkraus-adesso** [comment]
Im pasting the steps from the setup section (see first message) into a shell on the machine (via ssh).
Everything except configuring the master ip and port (which is done by hand) is done as described.

**Comment by richardkraus-adesso** [comment]
I am pasting the commands detailed in the first post into the shell of the agent machine (via ssh)

**Comment by richardkraus-adesso** [comment]
@nmkoremblum I dont have any updates since, as I stated before, I see no way to further debug my issue.

**Comment by nmkoremblum** [comment]
I can only think of two more things by now.
1st: Trying to execute one of the default ARs, instead of a custom one, to check if the problem is the script or not
2nd: Trying to run your custom script on the "manager" instead of "local" to check if the problem is on the AR dispatch

**Comment by richardkraus-adesso** [comment]
1. I would need a reliable way of knowing whether the response ran or not. Also, I assume the AR is working since I can trigger my custom response via API.
2. I have already tried that, as described in the initial post, and the manager only executed a limited amount of responses locally (also described in the inital post)

This lead me to the conclusion that the error is rooted in the active-response routing/triggering decision, not in the dispatch mechanism.
Since I can only debug the dispatch (which simply does not show up in the logs), I have no information which active-responses wazuh is aware of and why it decides to not execute a response.

**Comment by nmkoremblum** [comment]
Do you have a single Manager or do you have many workers?

**Comment by richardkraus-adesso** [comment]
In the wazuh-kubernetes repo there is a single master and a single worker as manager. I can confirm that:
```sh
$ kubectl get pods -n wazuh
NAME                             READY   STATUS    RESTARTS   AGE
wazuh-dashboard-87647b8b-r2xt6   1/1     Running   0          33m
wazuh-indexer-0                  1/1     Running   0          33m
wazuh-manager-master-0           1/1     Running   0          33m
wazuh-manager-worker-0           1/1     Running   0          33m
```

All tests managed above were conducted on the wazuh-manager-master-0

Is there additional configuration required for the manager-workers?
The wazuh-docker setup also has a master and a worker, but did not require that

**Comment by nmkoremblum** [comment]
Can you please check if both master and worker have the same `ossec.conf` configuration?

**Comment by richardkraus-adesso** [comment]
Configuring the worker as well as the master definitely solves this issue, thank you for your help.

I did assume it was not necessary since the docker-compose also has separate configurations and accepts agent connections on the worker container.
Im not sure what causes the docker-compose setup to work by only configuring the master, but I also dont have the time to find out right now.

Thank you again for your help.
