### ISSUE TITLE
Fix API active configuration endpoint for `labels` and `reports`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17610]
| Related issue |
|--|
|https://github.com/wazuh/wazuh-kibana-app/issues/5565|

### Reports
According to the [API reference](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_manager_config_ondemand) for `GET /manager/configuration/{component}/{configuration}` (and also for cluster), `reports` section should be obtained by running `GET /manager/configuration/monitor/internal`: 
![image](https://github.com/wazuh/wazuh/assets/23361101/d164271f-b394-4f24-9d60-4aa5c17be31a)

However, this is the response:
```JSON
{
  "data": {
    "affected_items": [
      {
        "monitord": {
          "day_wait": 10,
          "compress": 1,
          "sign": 1,
          "monitor_agents": 0,
          "keep_log_days": 31,
          "rotate_log": 1,
          "size_rotate": 536870912,
          "daily_rotations": 12,
          "delete_old_agents": 0
        }
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}
```

It would work correctly if the `monitor/reports` combination was supported.

### Labels

A similar thing happens for manager labels. When `GET /manager/configuration/agent/labels` is run, this is the response:
```JSON
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1121,
          "message": "Error connecting with socket: Please verify that the component 'agent' is properly configured",
          "remediation": "Please ensure the selected module is running and properly configured"
        },
        "id": [
          "master-node"
        ]
      }
    ]
  },
  "message": "Could not read active configuration in specified node",
  "error": 1
}
```

The message is being sent to `/var/ossec/queue/sockets/agent`, but the correct destination socket when used in the manager is `/var/ossec/queue/sockets/analysis`

This should be fixed for manager and cluster versions of the endpoint.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

I have been analyzing the code and replicated the mentioned behaviors founding the sections of the code that need to be modified.

In the process of testing the `/monitor/reports` combination by modifying `WAZUH_COMPONENT_CONFIGURATION_MAPPING` in `api/api/validator.py`.

**Comment by fdalmaup** [comment]
# Issue Update

The required modifications were carried out. `/monitor/internal` was changed to `/manual/reports`.Manual tests were performed both for the manager and cluster endpoints:

### `GET /manager/configuration/monitor/reports`
```xml
<ossec_config>
    <reports>
        <title>Auth_Report</title>
        <group>authentication_failed,</group>
        <showlogs>yes</showlogs>
    </reports>
<ossec_config>

```

```json
{
  "data": {
    "affected_items": [
      {
        "reports": [
          {
            "title": "Auth_Report",
            "group": "authentication_failed-",
            "showlogs": "yes"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}
```
### `GET /cluster/{worker-1-id}/configuration/monitor/reports`
```xml
<ossec_config>
    <reports>
        <title>Auth_Report</title>
        <group>authentication_failed_worker,</group>
        <showlogs>yes</showlogs>
    </reports>
<ossec_config>

```

```json
{
  "data": {
    "affected_items": [
      {
        "reports": [
          {
            "title": "Auth_Report",
            "group": "authentication_failed_worker-",
            "showlogs": "yes"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}
```

Regarding the `GET /manager/configuration/agent/labels` endpoint, the used socket was modified to `/var/ossec/queue/sockets/analysis` as mentioned in the issue's description.

### `GET /manager/configuration/agent/labels`
```xml
<ossec_config>
  <labels>
    <label key="custom">customLabel</label>
  </labels>
<ossec_config>

```

```json
{
  "data": {
    "affected_items": [
      {
        "labels": [
          {
            "value": "customLabel",
            "key": "custom",
            "hidden": "no"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}
```

### `GET /cluster/{worker-1-id}/configuration/agent/labels`
```xml
<ossec_config>
  <labels>
    <label key="custom">customWorkerLabel</label>
  </labels>
<ossec_config>

```
```json
{
  "data": {
    "affected_items": [
      {
        "labels": [
          {
            "value": "customWorkerLabel",
            "key": "custom",
            "hidden": "no"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read in specified node",
  "error": 0
}
```

## Unit Tests
<details><summary>Framework</summary>

    pytest framework/
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.9.17, pytest-7.0.1, pluggy-0.13.1
    rootdir: /home/fdalmau/git/wazuh/framework
    plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0, asyncio-0.18.1
    asyncio: mode=auto
    collected 2049 items                                                                                                                                            
    
    framework/scripts/tests/test_agent_groups.py ..............                                                                                               [  0%]
    framework/scripts/tests/test_agent_upgrade.py ...............                                                                                             [  1%]
    framework/scripts/tests/test_cluster_control.py ......                                                                                                    [  1%]
    framework/scripts/tests/test_wazuh_clusterd.py .......                                                                                                    [  2%]
    framework/scripts/tests/test_wazuh_logtest.py ......................                                                                                      [  3%]
    framework/wazuh/core/cluster/dapi/tests/test_dapi.py ................................                                                                     [  4%]
    framework/wazuh/core/cluster/tests/test_client.py ................                                                                                        [  5%]
    framework/wazuh/core/cluster/tests/test_cluster.py ...................................                                                                    [  7%]
    framework/wazuh/core/cluster/tests/test_common.py ...........................................................................                             [ 10%]
    framework/wazuh/core/cluster/tests/test_control.py ......                                                                                                 [ 11%]
    framework/wazuh/core/cluster/tests/test_local_client.py .............                                                                                     [ 11%]
    framework/wazuh/core/cluster/tests/test_local_server.py ........................                                                                          [ 12%]
    framework/wazuh/core/cluster/tests/test_master.py .............................................                                                           [ 15%]
    framework/wazuh/core/cluster/tests/test_server.py ...................                                                                                     [ 16%]
    framework/wazuh/core/cluster/tests/test_utils.py ...........                                                                                              [ 16%]
    framework/wazuh/core/cluster/tests/test_worker.py ....................................                                                                    [ 18%]
    framework/wazuh/core/tests/test_active_response.py ..............                                                                                         [ 19%]
    framework/wazuh/core/tests/test_agent.py ................................................................................................................ [ 24%]
    ..................................                                                                                                                        [ 26%]
    framework/wazuh/core/tests/test_cdb_list.py ......................................                                                                        [ 28%]
    framework/wazuh/core/tests/test_common.py .......                                                                                                         [ 28%]
    framework/wazuh/core/tests/test_configuration.py ......................................................................                                   [ 31%]
    framework/wazuh/core/tests/test_database.py .............                                                                                                 [ 32%]
    framework/wazuh/core/tests/test_decoder.py ................                                                                                               [ 33%]
    framework/wazuh/core/tests/test_exception.py ...                                                                                                          [ 33%]
    framework/wazuh/core/tests/test_input_validator.py ...                                                                                                    [ 33%]
    framework/wazuh/core/tests/test_logtest.py ..                                                                                                             [ 33%]
    framework/wazuh/core/tests/test_manager.py ...............                                                                                                [ 34%]
    framework/wazuh/core/tests/test_mitre.py .............                                                                                                    [ 34%]
    framework/wazuh/core/tests/test_pyDaemonModule.py .....                                                                                                   [ 35%]
    framework/wazuh/core/tests/test_results.py ........................................                                                                       [ 37%]
    framework/wazuh/core/tests/test_rootcheck.py .............                                                                                                [ 37%]
    framework/wazuh/core/tests/test_rule.py ......................                                                                                            [ 38%]
    framework/wazuh/core/tests/test_sca.py ........................                                                                                           [ 40%]
    framework/wazuh/core/tests/test_security.py ............                                                                                                  [ 40%]
    framework/wazuh/core/tests/test_stats.py .................                                                                                                [ 41%]
    framework/wazuh/core/tests/test_syscheck.py .......                                                                                                       [ 41%]
    framework/wazuh/core/tests/test_syscollector.py ...                                                                                                       [ 41%]
    framework/wazuh/core/tests/test_task.py ........                                                                                                          [ 42%]
    framework/wazuh/core/tests/test_utils.py ................................................................................................................ [ 47%]
    ..................................................................................................................................                        [ 54%]
    framework/wazuh/core/tests/test_vulnerability.py ..                                                                                                       [ 54%]
    framework/wazuh/core/tests/test_wazuh_queue.py ....................                                                                                       [ 55%]
    framework/wazuh/core/tests/test_wazuh_socket.py ....................                                                                                      [ 56%]
    framework/wazuh/core/tests/test_wdb.py ...............................                                                                                    [ 57%]
    framework/wazuh/core/tests/test_wlogging.py .........                                                                                                     [ 58%]
    framework/wazuh/rbac/tests/test_auth_context.py ..                                                                                                        [ 58%]
    framework/wazuh/rbac/tests/test_decorators.py ........................................................................................................... [ 63%]
    ..                                                                                                                                                        [ 63%]
    framework/wazuh/rbac/tests/test_default_configuration.py ........................................................                                         [ 66%]
    framework/wazuh/rbac/tests/test_orm.py ......................................................                                                             [ 68%]
    framework/wazuh/rbac/tests/test_preprocessor.py ...........                                                                                               [ 69%]
    framework/wazuh/tests/test_active_response.py ............                                                                                                [ 70%]
    framework/wazuh/tests/test_agent.py ..................................................................................................................... [ 75%]
                                                                                                                                                              [ 75%]
    framework/wazuh/tests/test_cdb_list.py .....................................................                                                              [ 78%]
    framework/wazuh/tests/test_ciscat.py .................................                                                                                    [ 79%]
    framework/wazuh/tests/test_cluster.py ..........                                                                                                          [ 80%]
    framework/wazuh/tests/test_decoder.py ...................................                                                                                 [ 82%]
    framework/wazuh/tests/test_group.py .......                                                                                                               [ 82%]
    framework/wazuh/tests/test_logtest.py ......                                                                                                              [ 82%]
    framework/wazuh/tests/test_manager.py ....................................                                                                                [ 84%]
    framework/wazuh/tests/test_mitre.py .......                                                                                                               [ 84%]
    framework/wazuh/tests/test_rootcheck.py ..................................................                                                                [ 87%]
    framework/wazuh/tests/test_rule.py ........................................................                                                               [ 90%]
    framework/wazuh/tests/test_sca.py ...........                                                                                                             [ 90%]
    framework/wazuh/tests/test_security.py .........................................................................                                          [ 94%]
    framework/wazuh/tests/test_stats.py ...............                                                                                                       [ 94%]
    framework/wazuh/tests/test_syscheck.py .........................                                                                                          [ 96%]
    framework/wazuh/tests/test_syscollector.py ............                                                                                                   [ 96%]
    framework/wazuh/tests/test_task.py ............................                                                                                           [ 98%]
    framework/wazuh/tests/test_vulnerability.py ........................................                                                                      [100%]
    
    ========================================================= 2049 passed, 47 warnings in 249.55s (0:04:09) =========================================================

</details>

<details><summary>API</summary>

    pytest api/api
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.9.17, pytest-7.0.1, pluggy-0.13.1
    rootdir: /home/fdalmau/git/wazuh/api
    plugins: cov-3.0.0, aiohttp-1.0.4, trio-0.7.0, anyio-3.6.2, metadata-2.0.2, html-3.0.0, asyncio-0.18.1
    asyncio: mode=auto
    collected 536 items                                                                                                                                             
    
    api/api/controllers/test/test_active_response_controller.py .                                                                                             [  0%]
    api/api/controllers/test/test_agent_controller.py ...........................................                                                             [  8%]
    api/api/controllers/test/test_cdb_list_controller.py ......                                                                                               [  9%]
    api/api/controllers/test/test_ciscat_controller.py .                                                                                                      [  9%]
    api/api/controllers/test/test_cluster_controller.py ........................                                                                              [ 13%]
    api/api/controllers/test/test_decoder_controller.py .......                                                                                               [ 15%]
    api/api/controllers/test/test_default_controller.py .                                                                                                     [ 15%]
    api/api/controllers/test/test_experimental_controller.py ...............                                                                                  [ 18%]
    api/api/controllers/test/test_manager_controller.py ..................                                                                                    [ 21%]
    api/api/controllers/test/test_mitre_controller.py .......                                                                                                 [ 22%]
    api/api/controllers/test/test_overview_controller.py .                                                                                                    [ 23%]
    api/api/controllers/test/test_rootcheck_controller.py ....                                                                                                [ 23%]
    api/api/controllers/test/test_rule_controller.py ........                                                                                                 [ 25%]
    api/api/controllers/test/test_sca_controller.py ..                                                                                                        [ 25%]
    api/api/controllers/test/test_security_controller.py ...................................................                                                  [ 35%]
    api/api/controllers/test/test_syscheck_controller.py ....                                                                                                 [ 36%]
    api/api/controllers/test/test_syscollector_controller.py .........                                                                                        [ 37%]
    api/api/controllers/test/test_task_controller.py .                                                                                                        [ 37%]
    api/api/controllers/test/test_vulnerability_controller.py ....                                                                                            [ 38%]
    api/api/models/test/test_model.py ...........................                                                                                             [ 43%]
    api/api/test/test_alogging.py ..................                                                                                                          [ 47%]
    api/api/test/test_authentication.py ...........                                                                                                           [ 49%]
    api/api/test/test_configuration.py ..........................................                                                                             [ 56%]
    api/api/test/test_encoder.py ...                                                                                                                          [ 57%]
    api/api/test/test_middlewares.py ............                                                                                                             [ 59%]
    api/api/test/test_uri_parser.py ...                                                                                                                       [ 60%]
    api/api/test/test_util.py ........................................                                                                                        [ 67%]
    api/api/test/test_validator.py .......................................................................................................................... [ 90%]
    ...................................................                                                                                                       [100%]
    
    =============================================================== 536 passed, 18 warnings in 2.43s ================================================================

</details>

**Comment by fdalmaup** [comment]
Blocked until https://github.com/wazuh/wazuh/issues/17690 is merged for the AITs checks to pass.

**Comment by fdalmaup** [comment]
# Issue Update

In the process of developing a test case in the AITs `api/test/integration/test_manager_endpoints.tavern.yaml` and `api/test/integration/test_cluster_endpoints.tavern.yaml` for `monitor/reports`.

**Comment by fdalmaup** [comment]
# Issue Update

The `API Integration Test` checks for the associated PR have been failing after developing the tests. Nevertheless, the introduced changes in the tests are not related to these failures since the errors vary between runs. Also, it was found that the generated output files for the checks were incomplete and the test instances shut down due to a lack of resources that will be increased in wazuh/wazuh-jenkins#5323.

## Tests results
### `test_manager_endpoints.tavern.yaml`
```
pytest -vvvs --disable-warnings test_manager_endpoints.tavern.yaml
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.10, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/fdalmau/venv/integrationtest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.15.0-76-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.11.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'tavern': '1.2.2', 'metadata': '2.0.2'}}
rootdir: /home/fdalmau/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, tavern-1.2.2, metadata-2.0.2
collected 32 items                                                                                                                                                                       

test_manager_endpoints.tavern.yaml::GET /manager/status PASSED
test_manager_endpoints.tavern.yaml::GET /manager/info PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[alerts] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[auth] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cis-cat] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[cluster] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[command] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[global] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[localfile] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[osquery] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[remote] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[rootcheck] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[ruleset] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[sca] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscheck] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[syscollector] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration?{section}[vulnerability-detector] PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration PASSED
test_manager_endpoints.tavern.yaml::GET /manager/daemons/stats PASSED
test_manager_endpoints.tavern.yaml::GET /manager/stats PASSED
test_manager_endpoints.tavern.yaml::GET /manager/stats/hourly PASSED
test_manager_endpoints.tavern.yaml::GET /manager/stats/weekly PASSED
test_manager_endpoints.tavern.yaml::GET /manager/stats/analysisd PASSED
test_manager_endpoints.tavern.yaml::GET /manager/stats/remoted PASSED
test_manager_endpoints.tavern.yaml::GET /manager/logs PASSED
test_manager_endpoints.tavern.yaml::GET /manager/logs/summary PASSED
test_manager_endpoints.tavern.yaml::GET /manager/api/config PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration/validation (OK) PASSED
test_manager_endpoints.tavern.yaml::GET /manager/validation (KO) PASSED
test_manager_endpoints.tavern.yaml::GET /manager/configuration/{component}/{configuration} PASSED
test_manager_endpoints.tavern.yaml::PUT /manager/configuration PASSED
test_manager_endpoints.tavern.yaml::PUT /manager/restart PASSED

====================================================================== 32 passed, 34 warnings in 104.52s (0:01:44) =======================================================================
```

### `test_cluster_endpoints.tavern.yaml`

```pytest -vvvs --disable-warnings test_cluster_endpoints.tavern.yaml
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.8.10, pytest-5.4.3, py-1.11.0, pluggy-0.13.1 -- /home/fdalmau/venv/integrationtest-env/bin/python3
cachedir: .pytest_cache
metadata: {'Python': '3.8.10', 'Platform': 'Linux-5.15.0-76-generic-x86_64-with-glibc2.29', 'Packages': {'pytest': '5.4.3', 'py': '1.11.0', 'pluggy': '0.13.1'}, 'Plugins': {'html': '3.1.1', 'tavern': '1.2.2', 'metadata': '2.0.2'}}
rootdir: /home/fdalmau/git/wazuh/api/test/integration, inifile: pytest.ini
plugins: html-3.1.1, tavern-1.2.2, metadata-2.0.2
collected 49 items                                                                                                                                                                       

test_cluster_endpoints.tavern.yaml::GET /cluster/local/config PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/healthcheck PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/ruleset/synchronization PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/local/info PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[ip] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[name] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[type] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/nodes select[version] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/status PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/configuration/validation PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/api/config PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/configuration/{component}/{configuration} PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/info[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/logs/summary[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/daemons/stats[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/wrong_node/stats PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/analysisd[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/hourly[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/remoted[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/stats/weekly[worker2] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[master-node] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker1] PASSED
test_cluster_endpoints.tavern.yaml::GET /cluster/{node_id}/status[worker2] PASSED
test_cluster_endpoints.tavern.yaml::PUT /cluster/restart PASSED
test_cluster_endpoints.tavern.yaml::PUT /cluster/{node_id}/configuration PASSED

====================================================================== 49 passed, 62 warnings in 482.92s (0:08:02) =======================================================================
```
