### ISSUE TITLE
wazuh-agentd start error on macOS Sonoma

### ISSUE THREAD

**Issue by Tech-dea** [wazuh/wazuh#17635]
Hi,

So I tried to follow the installation method to test the installation for Sonoma, I tried to remove everything and then perform the install again, so far installation successful (macOS Sonoma DB2 (23A5276g)). However, when i attempted to start it, it will show the following error

`Starting Wazuh v4.4.4...
wazuh-execd already running...
wazuh-agentd: Process 4656 not used by Wazuh, removing ..
wazuh-agentd did not start`

I will do another try for disable SIP to run the set up again, but I think this is something that needs to be taking care of. If you need a full log, let me know

**Comment by Dwordcito** [comment]
Hi @Tech-dea I hope you are well.

Thanks for letting us know, I'll try to reproduce the problem to make a diagnosis and identify possible solutions.

**Comment by Tech-dea** [comment]
I think this also happen with macOS 13.4 if I deploy the full script using MDM, once I turn off SIP, I can complete the installation with the script as well. Now going to test with Sonoma

**Comment by Dwordcito** [comment]
Hello, I tried to reproduce it in an environment under the x86-64 architecture and the agent works correctly, maybe you are running it on ARM64 architecture and you do not have Rosetta installed which gives compatibility to run binaries compiled under x86-64 architecture?

In any case, it is very important to mention that we are already working so that we can distribute binaries under the ARM architecture. Which will be available in 4.5.1 most likely.

**Comment by Tech-dea** [comment]
I have Rosetta installed and I tried to remove everything again, and then reinstall again, it gives me and error saying installation failed for 4.4.4 version, so I am pretty sure the issue is not just related to the architecture

**Comment by Tech-dea** [comment]
It looks like the issue somehow was fix in Sonoma Beta 3 (build 23A5286g), will further check again by doing another clean install of the system now

**Comment by Dwordcito** [comment]
ok @Tech-dea , let me know if the agent now runs! In my environment(beta 3) works!

**Comment by Dwordcito** [comment]
We closed the issue due to inactivity, please reopen the issue if you continue with the problem.

Thank you very much for being part of the community and helping us to be better every time!
