### ISSUE TITLE
Enhance argument parsing for Amazon Security Lake Integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#17630]
| Affected integration |
|---|
| AWS Security Lake |

## Description
As mentioned in the [Amazon Security Lake Integrations Test development issue](https://github.com/wazuh/wazuh-qa/issues/4055#issuecomment-1603147444), the module requires a series of modifications to show more descriptive messages when parsing errors arise and to ensure that the mandatory parameters are verified before the execution of the module.
The required behaviors are:
- C parser level:
    - Verify that the `sqs_name` tag is present and does not contain an empty value. Display a descriptive error if empty.
    - Verify that the `iam_role_arn` tag is present and does not contain an empty value. Display a descriptive error if empty.
    - Verify that the `external_id` tag is present and does not contain an empty value. Display a descriptive error if empty.
- Script level:
    - Verify that the `sqs_name` value complies with the minimal AWS requirements for the SQS name (up to 80 characters and the valid values are alphanumeric characters, hyphens (-), and underscores (_)). Show a descriptive message if it is an invalid one.
    - Verify that the `iam_role_arn` value complies with the expected ARN format. A possible regex for this is `^arn:(?P<Partition>[^:\n]*):(?P<Service>[^:\n]*):(?P<Region>[^:\n]*):(?P<AccountID>[^:\n]*):(?P<Ignore>(?P<ResourceType>[^:\/\n]*)[:\/])?(?P<Resource>.*)$`.
    - Verify that the `iam_role_duration` is a numeric value and display a descriptive log message in case it is not.

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update
### Validations in the C parser

`SQS Name`:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/src/config/wmodules-aws.c#L564-L572

`iam_role_arn`:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/src/config/wmodules-aws.c#L582-L590

`External Id`:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/src/config/wmodules-aws.c#L573-L581

### Validations in the Python script
Added validation for checking if  `iam_role_duration`  is numeric:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/wodles/aws/aws_s3.py#L3771-L3773

Added validation for `iam_role_arn `:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/wodles/aws/aws_s3.py#L3783-L3801
Added validation for `sqs_name `:
https://github.com/wazuh/wazuh/blob/dfa5dcdbf82839f63e8fde2c80e8d16afc414e82/wodles/aws/aws_s3.py#L3804-L3823

**Comment by RamosFe** [comment]
## Update

Added validation for the CLI arguments of a subscriber.
https://github.com/wazuh/wazuh/blob/d92e7afd9888ec1a59d1ebad8cdc54110c4ea5b7/wodles/aws/aws_s3.py#L3941-L3947

**Comment by Selutario** [comment]
@RamosFe, open an issue to add unit tests for the new args validators once this issue is completed:
- https://github.com/wazuh/wazuh/issues/13388
