### ISSUE TITLE
Scanning unsupported systems segmentation fault

### ISSUE THREAD

**Issue by KingAmirTheHunter** [wazuh/wazuh#17649]
|Wazuh Version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | Vulnerability detection | Manager | Packages | Oracle Linux 7 |

Hi,
I got segmentation fault error when I want to scan unsupported systems  with vulnerability detector

```
wazuh-modulesd[92060]: segfault at 143230 ip 00007ff43d6b3219 sp 00007ffe14571790 error 4 in libjemalloc.so.2[7ff43d6a4000+8c000]
```

And it is the changed config of ossec .conf file
```
<provider name="redhat">
        <enabled>yes</enabled>
        <os allow="Oracle Linux-7">7</os>
        <os path="/local_path/com.redhat.rhsa-RHEL5.xml.bz2">5</os>
        <os path="/local_path/rhel-6-including-unpatched.oval.xml.bz2">6</os>
        <os path="/local_path/rhel-7-including-unpatched.oval.xml.bz2">7</os>
        <os path="/local_path/rhel-8-including-unpatched.oval.xml.bz2">8</os>
        <os path="/local_path/rhel-9-including-unpatched.oval.xml.bz2">9</os>
        <path>/local_path/rh-feed/redhat-feed[[:digit:]]\+\.json$</path>
        <update_interval>1h</update_interval>
    </provider>
```

**Comment by KingAmirTheHunter** [comment]
Very Nice! thanks for fast response

**Comment by MarcelKemp** [comment]
You are welcome! 
I will reopen the issue to fix the problem, because instead of causing a segfault, it should keep the last duplicate configuration, show the Debug message and finally, correctly free the first block it is not going to use.

**Comment by KingAmirTheHunter** [comment]
ok as you wish thanks again for help and tell me if you need anything

**Comment by KingAmirTheHunter** [comment]
Hi, Again 
How can I detect Centos 7 vulnerabilities in this config addition to oracle Linux 7

**Comment by MarcelKemp** [comment]
Hi again @KingAmirTheHunter,

Using the same configuration I suggested here (https://github.com/wazuh/wazuh/issues/17649#issuecomment-1607687136), it should detect both `Red Hat` and `Oracle Linux` as well as `CentOS` agents.  Because _CentOS_ is officially supported by _Wazuh_ and uses the same feed as _Red Hat_, so you only need to have Red Hat's feed active for CentOS agents to be scanned as well.

Below is the compatibility matrix, showing the officially supported OSes with _Wazuh_ and the corresponding feeds that need to be active for vulnerability detection:
- https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix

I hope you find it useful.

**Comment by KingAmirTheHunter** [comment]
Ok,
Thanks alot

**Comment by lbethancourt-quantic** [comment]
> ## Workaround
> To fix it, you simply need to add the `allow` parameter (_unsupported systems_), together with the `path` parameter (_offline update)_, that allows you to scan both unsupported (Oracle Linux 7) and RedHat 7 agents offline, and avoiding the segmentation fault.

Hello @MarcelKemp, I have been trying to get the vuln scan to work on my Oracle Linux 7 and 8, I have read all your posts and I wonder what version it is that works with this configuration,  I am using version 4.7.2,  and I'm still unable to make the Oracle Linux 7/8 to do the vulnerability reports.

this is my configuration:
```
     <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <os allow="Oracle Linux-7" path="/var/ossec/redhat-feed/rhel-7-including-unpatched.oval.xml.bz2">7</os>
      <os allow="Oracle Linux-8" path="/var/ossec/redhat-feed/rhel-8-including-unpatched.oval.xml.bz2">8</os>
      <os allow="Centos Linux-6">6</os>
      <os allow="Centos Linux-7">7</os>
      <os allow="Centos Linux-8">8</os>
      <update_interval>1h</update_interval>
    </provider>
```
on my logs I only see the ID of the agents that are not Oracle Linux...
```
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '004' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '004'
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '005' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '005'
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '010' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '010'
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '015' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '015'
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '016' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '016'
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '018' vulnerabilities.
2024/01/16 10:08:51 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '018'
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '020' vulnerabilities.
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '020'
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '022' vulnerabilities.
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '022'
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '023' vulnerabilities.
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '023'
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '035' vulnerabilities.
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '035'
2024/01/16 10:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.
```
no errors, just ommiting agents.

Any help will be appreciated.

**Comment by MarcelKemp** [comment]
Hi @lbethancourt-quantic,

The problem lies in the use of the same `<os>` using different `allow`, which causes overwriting.

So to avoid this problem, simply define it once (and if multiple OSes, add `, `), as described in the documentation:
- https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html#configuring-vulnerability-detector-to-include-unsupported-systems

For your specific case, with the following configuration you would scan both `RHEL`, `CentOS,` and `Oracle Linux`:
```xml
     <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os allow="Oracle Linux-7">7</os>
      <os allow="Oracle Linux-8">8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>
```

> CentOS is already included as official support using the same feed as RHEL: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix

**Comment by kbensch** [comment]
Hi
I have tried various permutations of this:
<os allow="Oracle Linux-7">7</os>
<os allow="Oracle Linux-8">8</os>
and none of them are working.
This is my current config:
   
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <os allow="Oracle Linux-5" path="/opt/oval-data/rhel-5-including-unpatched.oval.xml.bz2">5</os>
      <os allow="Oracle Linux-6" path="/opt/oval-data/rhel-6-including-unpatched.oval.xml.bz2">6</os>
      <os allow="Oracle Linux-7" path="/opt/oval-data/rhel-7-including-unpatched.oval.xml.bz2">7</os>
      <os allow="Oracle Linux-8" path="/opt/oval-data/rhel-8-including-unpatched.oval.xml.bz2">8</os>
      <os allow="Oracle Linux-9" path="/opt/oval-data/rhel-9-including-unpatched.oval.xml.bz2">9</os>
      <update_interval>1h</update_interval>
    </provider>

i have also tried it without 
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
but none of it is working.
Can anybody help me please?
