### ISSUE TITLE
Ubuntu too many vulnerabilities detected

### ISSUE THREAD

**Issue by andonovski** [wazuh/wazuh#17650]
|Wazuh version|Component|Install type|Install method|Platform|
|4.4.1|Vulnerability detection|Manager|Virtual Machine (OVA)|CentOS7|

Vulnerability scanner detects over 360 active vulnerabilities in Ubuntu 22.04. The Ubuntu server is fully patched, updates are installed on a weekly basis.
From what I see, there are newer packages versions availaable online, for example curl, libcups, vim, etc. but none of these newer packages are available in Ubuntu repos. Is there a possibility to somehow have Vulnerability scans only against Ubuntu repos? Or just dashboard that show if server is patched using what is actually available on official repos? Some other way to solve this somehow?

This kind of renders Vulnerability dashboard useless, we will not manually install latest packages, only what is in official repos.

**Comment by MiguelazoDS** [comment]
Hi @andonovski, 

Please provide the following information so we can take a closer look. 

Pkgs installed for agent_id: **GET /syscollector/{agent_id}/packages**
Vulnerabilities reported for agent_id: **GET /vulnerability/{agent_id}**

You can use the API console for that purpose or if you prefer in you in your manager with curl. 

Thanks!

**Comment by Dwordcito** [comment]
Closed due to inactivity, If you would like to return to this issue please reopen it.

Thanks for being part of the community.

**Comment by zeethemee** [comment]
I have exactly the same issue. Agent installed on Ubuntu 22.04.3 LTS and approximately 200 false positives on an up date to system. Requested files attached. Any help greatly appreciated.
[package.json](https://github.com/wazuh/wazuh/files/13175066/package.json)
[vulnerability.json](https://github.com/wazuh/wazuh/files/13175074/vulnerability.json)
