### ISSUE TITLE
Update installation commands for API and Framework packages

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#17657]
|Wazuh version|Component|
|---|---|
| 4.5.0 | API and Framework installer |

## Description
As [commented](https://github.com/wazuh/wazuh/issues/17174#issuecomment-1587995511) in #17174, the `setuptools` project has stopped maintaining all direct invocations of `setup.py` showing `SetuptoolsDeprecationWarning`, and `distutils` has been [deprecated](https://peps.python.org/pep-0632/). 
Currently, the Wazuh `api` and `framework` packages are installed with the following commands and should be modified:

https://github.com/wazuh/wazuh/blob/0da24f6a0d6820d97ceff0d20e1dd67bfe927fa7/src/Makefile#L2247-L2253

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Installation of packages without warnings.
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

I replaced `setuptools` with `pip` to install the api and framework packages. Executing them one by one (`make install_api` and `make install_framework`) works as expected but I still have to test the complete installation.

**Comment by GGP1** [comment]
## Update

Executed the installation in a cloud instance with the changes introduced and fixed a couple of warnings.
