### ISSUE TITLE
Check Wazuh compatibility with new version macOS Sonoma 14 [arm64]

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#17679]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the new found version of macOS Sonoma 14 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/17387

NOTE: macOS Sonoma 14 was supposed released on 06/05/2023, just for registered developers, and it's expected to be publicly opened on July 2023

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] O.S. reporting in the interface.
- [ ] WPK installation / upgrade / uninstall / upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [ ] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by lchico** [comment]
Blocked by [issue #255](https://github.com/wazuh/internal-devel-requests/issues/255), We're having some trouble getting a macOS Sonoma 14 instance.

**Comment by lchico** [comment]
# Tested on: arm64 

###   :green_circle:  Agent and server, (enrollment and connectivity with the manager)
![agent_server](https://github.com/wazuh/wazuh/assets/21695385/43cd447f-1d9d-47c2-a95c-86f17ab09398)

### :green_circle: Does not apply:  ~Upgrade using WPK~

###  :green_circle: Correct uninstall after upgrade
I was able to uninstall and reinstall the wazuh-agent [following those stpes](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#:~:text=after%20the%20installation.-,Uninstall%20a%20Wazuh%20agent,-Permalink%20to%20this)

###  :green_circle: FIM: Real-time
![syscollector](https://github.com/wazuh/wazuh/assets/21695385/72b5a9b9-2a64-4e34-bbf8-048b282d9b64)


### :green_circle: Syscollector
![FIM](https://github.com/wazuh/wazuh/assets/21695385/73354ab4-e02f-4a42-9a51-bbcdeaee6e23)


###  :green_circle: Active response
![Active_Response](https://github.com/wazuh/wazuh/assets/21695385/78b624a3-816a-4252-a995-fbb676938af1)

### :green_circle: Log capture (Eventchannel for Windows and ULS for macOS).
![logcollector](https://github.com/wazuh/wazuh/assets/21695385/cf0fc221-4968-44d3-aa93-1c20adf2fff8)

### :green_circle: Vulnerability Detector: Vulnerability support
![Vulnerability_Detector](https://github.com/wazuh/wazuh/assets/21695385/effa075a-7d79-407c-8e6f-1856a518f218)


### :yellow_circle: SCA: Policy support. -> https://github.com/wazuh/wazuh/issues/18306#:~:text=In%20progress-,macOS%2014%20Sonoma,-%F0%9F%94%B4

**Comment by lchico** [comment]
Tested and works as expected.
