### ISSUE TITLE
Check Wazuh compatibility with new version Amazon Linux 2023

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#17677]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of the Amazon Linux 2023 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/17387
Instance request issue: https://github.com/wazuh/internal-devel-requests/issues/48

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK upgrade / uninstall. 
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and ~who-data~(not able to run auditd on docker container)  engines (if available).
- [ ] ~SCA: Policy support.~ -> https://github.com/wazuh/wazuh/issues/15462
- [ ] ~Vulnerability Detector: Vulnerability support.~ -> https://github.com/wazuh/wazuh/issues/17617
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [ ] ~Log capture (Eventchannel for Windows and ULS for macOS).~

**Comment by lchico** [comment]
###  Agent and server, (enrollment and connectivity with the manager)

![amazonLinux2023](https://github.com/wazuh/wazuh/assets/21695385/b422ae4c-280d-4db6-ae7d-a7b399f7199d)

**Comment by jotacarma90** [comment]
LGTM
