### ISSUE TITLE
Add validation for event size before send to analysisd

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#17689]
| Affected integration |
|---|
| AWS, GCloud, Azure, DockerListener|

## Description

Currently, the external modules are forwarding events without doing any validation of the size.

In the case of AWS, it just handles the socket error 90 when the buffer size is exceeded.

https://github.com/wazuh/wazuh/blob/318f1aca5f764b7f4b5608798d83140bd317dfe9/wodles/aws/aws_s3.py#L357-L373

The problem here is that the buffer size of `/var/ossec/queue/sockets/queue` in the kernel is **212992B**, which allows queuing multiple events, and the maximum single event size that analysisd can handle is **65535B**.

If we sent any event greater than **65535B** analysisd will truncate it until the max size and the user never will be alerted about it.

So, we need to review all the integrations (AWS, GCP, Azure, Docker Listener) validate the size of the event, and if this limit is exceeded show a warning to the user alerting them about the situation.

## Tasks
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by RamosFe** [comment]
## Update
- Added validation for Azure.
- Added validation for Google Cloud.
- Added validation for AWS.
- Added validation for Dodcker listener.
