### ISSUE TITLE
Update the scan-build version from 12 to 14

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17686]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.5 | Wazuh RTR | Manager/Agent | Sources | OS version |

## Current behavior
Uses scan-build-12

## Expected
Use the most modern version, scan-build-14

## Motivation
Be aligned with the version used in github actions.

## DoD
- [ ] Update the scan-build version from 12 to 14 in the RTR script.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
