### ISSUE TITLE
Wazuh FIM for other language

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#17692]
Hi,

I use Wazuh 4.3.10.
When i use FIM with diectory contains Vietnamese language, no alert when i tried created file or delete file.
![image](https://github.com/wazuh/wazuh/assets/82009148/d36a5ea8-1326-4b36-9d5f-5680730206d7)
In dashboard i received this
![image](https://github.com/wazuh/wazuh/assets/82009148/5e9e0be8-9320-4e1a-b191-98ff9f0d4955)
that told me that this folder was monitored but no alerts trigger.

How can i solve this issue?

Best Regards,

**Comment by MiguelazoDS** [comment]
Hi @thanvantrong, 

Sorry for the late response, I'm afraid that currently there's no support for unicode characters. 
If you attempt to monitor a folder like that you will get an error message like this. 

`2023/07/11 11:08:42 wazuh-agent[3228] run_realtime.c:682 at realtime_adddir(): DEBUG: (6290): Unable to add directory to real time monitoring: 'c:\users\vagrant\downloads\thư mục mới'`

We have in mind to improve this but there's no ETA yet for that improvement. 

There're other issues reporting the same: https://github.com/wazuh/wazuh/issues/4612

The better fix for this is to use a folder with an english name. 

Apologize for the inconvenience. Regards!

**Comment by Dwordcito** [comment]
Thank you for your report, we will close this issue and you can track progress on that capability in the other issue. https://github.com/wazuh/wazuh/issues/4612
