### ISSUE TITLE
Interface network down in agent windows with active response

### ISSUE THREAD

**Issue by santi10** [wazuh/wazuh#177]
Hi,

Sorry, I'm new on Wazuh and I'm searching information but I've seen several cases with linux but not with windows (I'm sorry if this isn't true).

I would to do disconnect interface or switch off network of my agent windows. is it posible with active response?

For example, a case:

If I've received an alert what says: "Powershell has been executed". Can I do an active response that down network interfaces or switch off network???? Also will do by time, that time frame will be 60 sec and then the interface network willl run or start again, is it posible?

I hope that you understad me. Let me know if you need more info

Thanks

**Comment by mjflve** [comment]
Hi santi10,

Yes, you could run active response scripts in Windows, Wazuh is shipped with some scripts you can see it [here](https://github.com/wazuh/wazuh/tree/master/active-response/win):

- **netsh.cmd:** could be used to block an IP address using netsh windows command.
- **route-null.cmd:** it's like netsh.cmd but using a null route to discard packets from the source ip address.
- **restart-ossec.cmd:** is intended to remotely restart the agent.

Take into account, the rule firing these scripts must have a extracted srcip address field to be used by netsh.cmd and route-null.cmd as a parameter, also a reverse action could be executed in a defined timeout, please review [this](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html#timeout) and our [active-response](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/index.html) documentation,

I hope this could clarify your doubts, regards.

**Comment by santi10** [comment]
Hi mjflve,

This active response I should do on my wazuh-server (ossec.conf), is it ok?

I don't see "srcip" in the logs...Have I create or set some configuration file???


Regards
Santi

**Comment by mjflve** [comment]
Hi,

Yes, you could configure the active response feature from the Wazuh manager, also this feature had some options like `location`. With this you could set on where the script will be executed (agent(s), manager or all), you could see [here](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html) a list of all options regarding this feature.

The fields used by the active response scripts like `srcip` are populated via the triggered alerts, previous to the alert generation a decoder phase is run when the Wazuh manager extract useful data from the receive log line, by example: using `ossec-logtest` binary and a sample log line like `May 21 20:22:28 slacker sshd[21487]: Failed password for root from 192.168.20.185 port 1045 ssh2`:

```
**Phase 1: Completed pre-decoding.
       full event: 'May 21 20:22:28 slacker sshd[21487]: Failed password for root from 192.168.20.185 port 1045 ssh2'
       hostname: 'slacker'
       program_name: 'sshd'
       log: 'Failed password for root from 192.168.20.185 port 1045 ssh2'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'root'
       srcip: '192.168.20.185'
       srcport: '1045'

**Phase 3: Completed filtering (rules).
       Rule id: '5716'
       Level: '5'
       Description: 'sshd: authentication failed.'
**Alert to be generated.
```

As you could see above, the decoding phase extract the `srcip` field from the log line, and will triggred the alert 5716 `sshd: authentication failed.`. The extracted `srcip` it will be used by the configured active response script.

I invite you to our [Wazuh mailing list](https://groups.google.com/forum/#!forum/wazuh), when we gladly respond all your doubts or questions.

I hope it helps.

Regards.

**Comment by santi10** [comment]
Great!! Thanks
