### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17713]
The following issue will gather all the info regarding testing and fixing in order to validate this release stage.

The definition of done for this one is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes implemented, all the below issues must be closed in order to close this one.

## Stage info

|Project|Main issue|Version|Stage|Tag|Previous Stage issue|
|---|---|---|---|---|---|
|[v4.6.0](https://github.com/orgs/wazuh/projects/43)||4.6.0|Pre-Alpha 1|[v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1)||

## QA testing issues

In order to move to a new stage or the GA version, all tests and metrics analyses below must be in Closed status.

| Name                        | Issue                                         | Status      |DRI|
|-----------------------------|-----------------------------------------------|-------------|---|
| C unit | - | ⚪ Skipped |@wazuh/core|
| Python unit | - | ⚪ Skipped |@wazuh/framework|
| Footprint metrics | #17717 | :red_circle:  Completed with failures|@wazuh/qa|
| Workload benchmarks metrics |#18017| :red_circle: Completed with failures  |@wazuh/qa|
| Integration | #18005| :red_circle:   Completed with failures |@wazuh/qa|
| API integration |#17729 | :red_circle: Completed with failures |@wazuh/framework|
| System | #18016 |  :red_circle: Completed with failures| @wazuh/qa|
| External integrations modules | - | ⚪ Skipped | @wazuh/framework|
| Demo uses cases | - | ⚪ Skipped |@wazuh/cicd|
| Packages | #17718 | :red_circle: Completed with failures |@wazuh/qa|
| Coverity scan | - | ⚪ Skipped |@wazuh/core|
| Ruleset | - | ⚪ Skipped |@wazuh/threat-intel|
| Kibana UI regression | - | ⚪ Skipped | @wazuh/frontend|
| Splunk UI regression | - | ⚪ Skipped | @wazuh/frontend|
| WPK Upgrade | - | ⚪ Skipped |@wazuh/core|
| E2E UX | - | ⚪ Skipped |@wazuh|

⚫ _Not started: The tasks didn't start yet._
🟡 _In progress: The team is already working on it._
🟢 _Ready to review: The product owner must audit and validate the results._
⚪ _Skipped:  The task has been deemed not necessary for this stage._
:brown_circle:  _Partially skipped:  Some parts of the task are skipped._
🟣 _Completed: Task finished. Nothing to do here._
🔴 _Completed with failures: Some issues were raised here._

## Auditors' validation

In order to close and proceed with the release or the next stage version, the following auditors must give the green light to this stage.

- [x] @davidjiglesias

**Comment by jnasselle** [comment]
- _Integration test_ task issue was changed from https://github.com/wazuh/wazuh/issues/17739 to https://github.com/wazuh/wazuh/issues/18005

**Comment by jnasselle** [comment]
- _System test_ issue was changed from https://github.com/wazuh/wazuh/issues/17728 to https://github.com/wazuh/wazuh/issues/18016

**Comment by jnasselle** [comment]
- _Workload benchmarks metrics_ task issue was changed from https://github.com/wazuh/wazuh/issues/17716 to https://github.com/wazuh/wazuh/issues/18017

**Comment by Rebits** [comment]
## Summary of reported bugs

### Footprint
- https://github.com/wazuh/wazuh/issues/17927
- https://github.com/wazuh/wazuh/issues/17928
- https://github.com/wazuh/wazuh/issues/17931
