### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - Installation metrics

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17719]
### Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Main packages metrics issue**  | #17718                                                   |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |

---

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

---

| Arquitecture | Build |
| :--         | :--   |
| AMD64        | https://ci.wazuh.info/job/Test_install_tier/620/  |
| ARM64        | https://ci.wazuh.info/job/Test_install_tier/621/   |
| I386         | https://ci.wazuh.info/job/Test_install_tier/622/   |
| ARM32        | https://ci.wazuh.info/job/Test_install_tier/623/   |
 
---

| System              | AMD64 | ARM64 | I386 | ARM32 |
| :--                 | :--:  | :--:  | :--: | :--:  |
| Amazon Linux 1      | :green_circle: | :black_circle:    | :black_circle:   | :black_circle:    |
| Amazon Linux 2      | :green_circle:     | :black_circle:    | :black_circle:   | :black_circle:    |
| CentOS 5            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 6            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 7            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| CentOS 8            | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Debian 7            | :green_circle:    | :green_circle:    | :green_circle:   | :black_circle:    |
| Debian 8            | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Debian 9            | :green_circle:    | :green_circle:    | :green_circle:   | :green_circle:    |
| Debian 10           | :green_circle:    | :black_circle:    | :red_circle:   | :black_circle:    |
| Debian 11           | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Fedora 29           | :green_circle:    | :green_circle:    | :black_circle:   | :green_circle:    |
| Fedora 31           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 32           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 34           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 35           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Fedora 36           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| openSUSE Tumbleweed | :red_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 6      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 7      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Oracle Linux 8      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 6           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 7           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 8           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Red Hat 9           | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Solaris 11          | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Solaris 10          | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Bionic       | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Focal        | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Precise      | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| Ubuntu Trusty       | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Ubuntu Xenial       | :green_circle:    | :black_circle:    | :green_circle:   | :black_circle:    |
| Windows 2016        | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |
| macOS 10.15         | :green_circle:    | :black_circle:    | :black_circle:   | :black_circle:    |

> **Note**:
> Solaris tests were relaunched. More information in https://github.com/wazuh/wazuh/issues/17719#issuecomment-1623847349

---

## macOS specific test

| System                  | Install* | Install** | TCP | UDP | Alerts | Logs | User | Group | Remove |
| :--                     | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |
| macOS 10.12 Sierra      | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
| macOS 10.13 High Sierra | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| macOS 10.14 Mojave      | :red_circle: | :red_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| macOS 10.15 Catalina    | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| macOS 11.00 Big Sur     | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| macOS 12.01 Monterey    | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
| macOS 13.4  Ventura     | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |

- \* Without environment variables
- \*\* With environment variables

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---
## Conclusions

- :red_circle: [Install test on macOS Mojave (10.14)](https://github.com/wazuh/wazuh/issues/17719#issuecomment-1625075093): Action item -> https://github.com/wazuh/wazuh-packages/issues/2261
- :yellow_circle: [OpenSUSE Tumbleweed](https://github.com/wazuh/wazuh/issues/17719#issuecomment-1623847349): Action item -> https://github.com/wazuh/wazuh-jenkins/pull/5405

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [ ] @teddytpc1 
- [x] @jnasselle  

---

**Comment by Rebits** [comment]
### Analysis report


<details><summary>AMD64 - OpenSUSE Tumbleweed</summary>

```
19:44:15  TASK [Download openSUSE Tumbleweed GPG Key] ************************************
19:44:15  fatal: [amd64-opensuse-tumbleweed-base_0]: FAILED! => {
19:44:15      "changed": true,
19:44:15      "checksum_dest": null,
19:44:15      "checksum_src": "42602bcc4db9da783513472a3753d1b4e96e4cdb",
19:44:15      "dest": "/tmp/gpg-pubkey-29b700a4-62b07e22.asc",
19:44:15      "elapsed": 1,
19:44:15      "src": "/tmp/ansible-moduletmp-1686591854.9151192-ql0xk_d1/tmpxbtgg6hn",
19:44:15      "url": "https://build.opensuse.org/projects/openSUSE:Tumbleweed/public_key"
19:44:15  }
19:44:15  
19:44:15  MSG:
19:44:15  
19:44:15  The checksum for /tmp/gpg-pubkey-29b700a4-62b07e22.asc did not match 3908048b3b68231b68572c90fe0d49d4d278901468a8f3580ee0861695e1a98b; it was 06a9cf0f538948f627fcee482d1e1e0e129ef95d46278db98f8a81e3160f9dd2.
```

Error related to: https://github.com/wazuh/wazuh-jenkins/issues/5279 (Change not included in 4.6.0 branch)

</details>

**Comment by Rebits** [comment]
### 06/07/2023
- Launched automatic install tests
- Researched errors

**Comment by Rebits** [comment]
# Install test on macOS Catalina (10.15)

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS Catalina (10.15)

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS Catalina (10.15)

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS Catalina (10.15)

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS Monterey (12.01)

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS BigSur (11) 

<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### Install test on macOS Ventura (13.4)


<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### 07/07/2023
- Installation manual testing of macOS

**Comment by Rebits** [comment]
### Install test on macOS 10.12 Sierra (Blocked)


<details><summary>:black_circle: Installation without env variables</summary>


</details>

<details><summary>:black_circle: Installation with env variables</summary>

</details>

<details><summary>:black_circle: TCP</summary>

</details>

<details><summary>:black_circle: Alerts</summary>

</details>
<details><summary>:black_circle: Logs</summary>

</details>
<details><summary>:black_circle: User and group</summary>

</details>

<details><summary>:black_circle: Removal</summary>

</details>

**Comment by Rebits** [comment]
### 11/07/2023

- Talked with @davidjiglesias. Ventura and Sierra System will not be tested for this Pre-Alpha stage.
- Moving issue from Blocked to Pending Review
