### ISSUE TITLE
Mechanism to releasing unused tcp sockets in remoted

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#17711]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.x | wazuh-remoted/wazuh-monitord | Manager | Packages/Sources | Linux |

From the error commented in this [issue](https://github.com/wazuh/wazuh/issues/17706) it is exposed that the manager side is not closing inactive sockets, causing that resources are not released properly. We believe that there is a need to develop some mechanism that periodically performs a cleaning or release of resources that are not in use, specifically of tcp sockets.

Proposed approach:

In `monitord` there is a feature ([monitor_agents_disconnection](https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/src/monitord/monitor_actions.c#L49)) that sets in the DB as disconnected agents that have not received any keepalive message during a certain period of time. The call to the database function ([wdb_disconnect_agents](https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/src/wazuh_db/helpers/wdb_global_helpers.c#L1073)) returns the ids of all the agents that were marked as disconnected. Taking advantage of this functionality, a call to a new endpoint of the `remoted` communication module ([remcom.c](https://github.com/wazuh/wazuh/blob/master/src/remoted/remcom.c)) could be added in monitord. This new endpoint would be in charge of receiving all these ids of disconnected agents and check inside the [keystore](https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/src/remoted/remoted.c#L22) data structure if there is any socket used by any of these agents and closing the corresponding sockets.

**Comment by vikman90** [comment]
@sdvendramini We expected this issue to be covered as of v3.9.0 by this one:

|Issue|PR|Documentation|
|---|---|---|
|https://github.com/wazuh/wazuh/issues/3078|https://github.com/wazuh/wazuh/pull/3069|https://github.com/wazuh/wazuh-documentation/pull/1124|

This should prevent hang connections from keeping connected to the manager. Can you check that or show a use case that may not be covered by that feature?

Cheers!

**Comment by vikman90** [comment]
Fixed by
- https://github.com/wazuh/wazuh/issues/17706
- https://github.com/wazuh/wazuh/pull/18085
