### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - Packages tests

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17718]
### Packages tests information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |
| **Previous packages metrics**    | #17528                                               |

---

| Status | Test              | Issue              |
| :--:   | :--               | :--:               | 
| :green_circle:     | Installation | #17719 |
| :green_circle:     | Upgrade | #17720      |
| :green_circle:     | SELinux | #17722      |
| :green_circle:     | Register | #17721     |
| :green_circle:     | Service  | #18022      |
| :white_circle:     | Specific systems | #17724     |
| :red_circle:     | Indexer/Dashboard | #17725        |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.
- [x] @jnasselle
- [ ] @davidjiglesias 
- [ ] @teddytpc1 

---

**Comment by Rebits** [comment]
### 06/07/2023
- Packages created for all components except for the dashboard, kibanaapp and dashboardapp
- Launch register, upgrade, install, service, selinux and register tests

**Comment by Rebits** [comment]
### 12/07/2023
- WPK packages were recreated correctly after @DFolchA recreate the ECR: https://ci.wazuh.info/job/Packages_builder/153461/
- Kibana/Dashboard App still failing due to https://github.com/wazuh/wazuh-packages/issues/2247. Blocked by https://github.com/wazuh/internal-devel-requests/issues/75

**Comment by Rebits** [comment]
- Wazuh DashboardApp, KibanaApp, Indexer and dashboard were created correctly.
- We can now proceed with Indexer/Dashboard testing

**Comment by jnasselle** [comment]
- _Service test_ task issue was changed from https://github.com/wazuh/wazuh/issues/17723 to https://github.com/wazuh/wazuh/issues/18022
