### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#17716]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |  #17713                                           |
| **Version**                                   |               4.6.0                             |
| **Release candidate #**                       |              Pre-Alpha1                              |
| **Tag**                                       |             [v4.6.0-pre-alpha1     ](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1)                         |
| **Previous Workload benchmarks metrics issue**|                   -                         |

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|        50000           |         25           |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions :red_circle: 
In summary, the test can be considered satisfactory for the most part, except for the following defects that were found during the API Performance test and are related to the following issues:

### Defects in:
GET /manager/logs #17740 :red_circle: 
PUT /active-response wazuh/wazuh-qa#3665 (Previously described as an xfailed test that needs to be corrected.) :yellow_circle: 
PUT /agents/group wazuh/wazuh-qa#3665 (Previously described as an xfailed test that needs to be corrected.) :yellow_circle: 
DELETE /agents wazuh/wazuh-qa#4296 :red_circle: 

The Performance test is not functioning correctly due to an error caused by variable passing: wazuh/wazuh-qa#4298 :red_circle: 

The Reliability test was executed manually because the Python version needs to be updated to enable automatic execution. This issue is opened: wazuh/wazuh-qa#4299 
Additionally, the Reliability test uncovered issues described in #17889, where the workers experience constant disconnections with the manager according to cluster.log. :red_circle: 

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by pro-akim** [comment]
[Report](https://github.com/wazuh/wazuh/files/11477160/artifacts.zip)

## API performance results

---
|                                  |                                            |                                           |            
|--|--|--|
| **Endpoint test name**  | **Status** | **Issues Ref.** |
| GET /cluster/local/info | :black_circle: | |
| GET /cluster/nodes| :black_circle:  | |
| GET /cluster/healthcheck | :black_circle: | |
| GET /cluster/status | :black_circle: | |
| GET /cluster/local/config | :black_circle: | |
| GET /cluster/api/config | :black_circle: | |
| GET /cluster/configuration/validation | :black_circle: | |
| GET /manager/status | :black_circle: | |
| GET /manager/info | :black_circle: | |
| GET /manager/configuration | :black_circle: | |
| GET /manager/logs | :black_circle: | |
| GET /manager/api/config | :black_circle: | |
| GET /manager/configuration/validation | :black_circle: | |
| GET /mitre/groups | :black_circle: | |
| GET /mitre/metadata | :black_circle: | |
| GET /mitre/mitigations | :black_circle: | |
| GET /mitre/references | :black_circle: | |
| GET /mitre/software | :black_circle: | |
| GET /mitre/tactics | :black_circle: | |
| GET /mitre/techniques | :black_circle: | |
| GET /overview/agents | :black_circle:  | |
| GET /tasks/status | :black_circle: | |
| PUT /active-response | :black_circle: | |
| PUT /rootcheck | :black_circle: | |
| PUT /syscheck | :black_circle: | |
| POST /groups | :black_circle: | |
| POST /security/users | :black_circle: | |
| POST /security/roles | :black_circle: | |
| POST /security/policies | :black_circle: | |
| POST /security/rules | :black_circle: | |
| PUT /agents/group | :black_circle: |  |
| PUT /agents/group/new_test_group/restart | :black_circle: | |
| PUT /agents/restart | :black_circle: |  |
| POST /agents | :black_circle: | |
| POST /agents/insert ​|  :black_circle: | |
| POST /agents/insert​/quick | :black_circle: | |
| GET /agents | :black_circle: | |
| GET /agents/no_group | :black_circle: | |
| GET /agents/outdated | :black_circle: | |
| GET /decoders | :black_circle: | |
| GET /groups | :black_circle: | |
| GET /lists | :black_circle: | |
| GET /rules | :black_circle: | |
| GET /security/users | :black_circle: | |
| GET /security/roles | :black_circle: | |
| GET /security/policies | :black_circle: | |
| GET /security/rules | :black_circle: | |
| DELETE /groups | :black_circle: | |
| DELETE /agents | :black_circle: | |
| DELETE /security/users | :black_circle: | |
| DELETE /security/roles | :black_circle: | |
| DELETE /security/policies | :black_circle: | |
| DELETE /security/rules | :black_circle: | |
| PUT /manager/restart | :black_circle: | |
| PUT /cluster/restart | :black_circle: | |

**Comment by pro-akim** [comment]
## 06/07/2023
Running tests in [263](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/263/)

**Comment by pro-akim** [comment]
# 07/07/2023 Upgrade

It seems that there are some problems with:

- GET /manager/logs
- DELETE /agents

On the other hand the following tests faced problems aswell:
- Performance
- Reliability

Cause will be researched before finish the issue.

**Comment by pro-akim** [comment]
# 12/07/23 Update
## Reliability test results:

### 3/5 tests failed.
### Failures:

- reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py::test_cluster_connection

<details>

Testing: Verify that no worker disconnects from the master once they are connected
The issue is opened in #

```
pytest.fail(f'The following nodes disconnected from master at any point:\n- ' + '\n- '.join(disconnected_nodes))
E           Failed: The following nodes disconnected from master at any point:
E           - worker_21
E           - worker_13
E           - worker_4
E           - worker_6
E           - worker_18
E           - worker_20
E           - worker_11
E           - worker_2
E           - worker_14
E           - worker_3
E           - worker_9
E           - worker_17
E           - worker_22
E           - worker_7
E           - worker_5
E           - worker_19
E           - worker_12
E           - worker_25
E           - worker_8
E           - worker_24
E           - worker_23
E           - worker_10
E           - worker_16
E           - worker_15
E           - worker_1

```
</details>

- reliability/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py::test_cluster_error_logs

<details>
Testing: Check that cluster logs appear in the expected order.

It seems related to:
- https://github.com/wazuh/wazuh/issues/15802

The main difference with the mentioned issue is that this behavior happened during all the activity in all the 25 workers. It was not related to OS.



```
    def test_cluster_error_logs(artifacts_path):
        """Look for any error messages in the logs of the cluster nodes.
    
        Any error message that is not included in the "white_list" will cause the test to fail.
        Errors found are attached to an html report if the "--html=report.html" parameter is specified.
    
        Args:
            artifacts_path (str): Path where folders with cluster information can be found.
        """
        if not artifacts_path:
            pytest.fail('Parameter "--artifacts_path=<path>" is required.')
    
        cluster_log_files = glob(join(artifacts_path, '*', 'logs', 'cluster.log'))
        if len(cluster_log_files) == 0:
            pytest.fail(f'No files found inside {artifacts_path}.')
    
        for log_file in cluster_log_files:
            with open(log_file) as f:
                s = mmap(f.fileno(), 0, access=ACCESS_READ)
                error_lines = re.findall(rb'(^.*?error.*?$)', s, flags=re.MULTILINE | re.IGNORECASE)
                if error_lines:
                    error_lines = [error for error in error_lines if not error_in_white_list(error)]
                    if error_lines:
                        nodes_with_errors.update({node_name.search(log_file)[1]: error_lines})
    
>       assert not nodes_with_errors, 'Errors were found in the "cluster.log" file of ' \
                                      'these nodes: \n- ' + '\n- '.join(nodes_with_errors)
E       AssertionError: Errors were found in the "cluster.log" file of these nodes: 
E         - worker_21
E         - worker_13
E         - worker_4
E         - worker_6
E         - worker_18
E         - worker_20
E         - master
E         - worker_11
E         - worker_2
E         - worker_14
E         - worker_3
E         - worker_9
E         - worker_17
E         - worker_22
E         - worker_7
E         - worker_5
E         - worker_19
E         - worker_12
E         - worker_25
E         - worker_8
E         - worker_24
E         - worker_23
E         - worker_10
E         - worker_16
E         - worker_15
E         - worker_1
E       assert not {'master': [b"2023/07/06 15:16:36 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B263_manager_16] [Main] Error dur...nager_11] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok', ...], ...}
```
</details>

- reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order
/test_cluster_worker_logs_order.py::test_check_logs_order_workers
<details>
Testing: Check that cluster logs appear in the expected order.

This pattern happens in every worker.

```
E            - Log type: Agent-groups recv
E              Expected logs: ['The checksum of both databases match.*Reset the attempt counter.', 'The checksum of both databases match.*', 'Checksum comparison failed. Attempt 10/10.*', 'Checksum comparison failed. Attempt .*', "The master's checksum and the worker's checksum are different. Local checksum:.*| Master checksum:.*."]
E              Found log: 2023/07/06 15:14:50 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B263_manager_1] [Agent-groups recv] The checksum of master (801ec3d0e4e227fe0e7af7f446d4b4c2ebdc057a) and worker (9a30db247cb00a781b4ddb0be0e1cb76c0846847) are different.
```

```
E            - Log type: Agent-info sync
E              Expected logs: ['Sending chunks.*', 'Finished in.*Updated 0 chunks.*']
E              Found log: 2023/07/06 15:17:11 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B263_manager_1] [Agent-info sync] Permission to synchronize granted.
```

If worker state is not stable, clearly this behaviour is related with the connection, affecting the order of logs.

**Comment by mauromalara** [comment]
## Review No.1

Please, check the following items:

1. Summarize the results in the main comment under the "Conclusions" title, including a simple but clear explanation of what is failing and what are the issues opened/linked to fix it.
2. This comment is confusing, please, update it trying to summarize and explain what's going on here.
   2.1. Be as precise as possible so that **anyone** can read and understand the results (include steps, states, issues, etc.)
   2.2. Take **[this](https://github.com/wazuh/wazuh/issues/17719)** as an example.
   2.3. Use 🟢, 🔴, etc. to help understand the results.
3. This issue you [opened](https://github.com/wazuh/wazuh/issues/17889) is not linked to any project when it should be linked to the Core Team project.
   3.1. I recommend grouping the errors into `<details>` tags so that they are more "clean"

**Comment by pro-akim** [comment]
# Update
Review checked.
Conclusions fixed.
The issue https://github.com/wazuh/wazuh/issues/17889 was reported to core team in c-release group to be correctly labeled [here](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1689242018805829)

**Comment by jnasselle** [comment]
Unfortunately, wazuh/wazuh-qa v4.6.0-pre-alpha1 tag was outdated. In consequence, the current analysis could be inaccurate and meaningless.

A new issue will be created to execute the same tasks but with the new fixed tag

**Comment by pro-akim** [comment]
# Update 
https://github.com/wazuh/wazuh-qa/issues/4296 closed due the fact that tests are not valid.
