### ISSUE TITLE
how can we extend the sdb disk to sda1?

### ISSUE THREAD

**Issue by h4m5t** [wazuh/wazuh#17715]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

50G is too small for me, I want to expand sdb to sda1 and become 500G.  What should I do？ Thank you very much !

[root@wazuh-server /]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   50G  0 disk
└─sda1   8:1    0   50G  0 part /
sdb      8:16   0  450G  0 disk
sr0     11:0    1 1024M  0 rom

**Comment by pereyra-m** [comment]
Hello @h4m5t !

Are you trying to increase the size of the Wazuh OVA? Are you using Virtual Box? What is your host OS?
I'll be able to help you better with more details, but here you have a related question to begin with

https://github.com/wazuh/wazuh/issues/11017#issuecomment-979955682

Regards.

**Comment by h4m5t** [comment]
Yes, I want to increase disk space for OVA which is provided by the Wazuh official.  I have read that comment [#11017](https://github.com/wazuh/wazuh/issues/11017#issuecomment-979955682) , But it's different from what I've encountered.
It is ok to expand sda directly, but I can't expand from sdb to sda1.  Do you know how to solve this problem? thank you for your reply ！

**Comment by pereyra-m** [comment]
Hello again, thank you for the details.

As far as I know, sda corresponds to a completely different disk than sdb.
If you want a partition from sda, sda1 in this case, to grow it will never be bigger than sda. And I don't think we could/should mount free space from one disk to another.

Now, this is a virtual machine, so you always can modify the virtual disk size and make it bigger. For example
https://kb.vmware.com/s/article/1004047

After completing this process, then you can increase the partition size.

Finally, consider that the OVA is a test environment that helps you to quickly perform tests in your environment, but it isn't intended to be used in production.
You might choose a more adequate installation option according to your needs.

Regards.

**Comment by h4m5t** [comment]
Thank you for your reply！I will try it in the way you said.
Regards.
