### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - Service

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17723]
### Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Main packages metrics issue**  | #17718                                                   |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |

---

| System        | Status | Build |
| :--           | :--:   | :--  |
| CentOS 6      | :red_circle:     | [#6327](https://ci.wazuh.info/job/Test_service/6327)   |
| CentOS 7      | :red_circle:     | [#6328](https://ci.wazuh.info/job/Test_service/6328) |
| Ubuntu Trusty | :red_circle:     | [#6329](https://ci.wazuh.info/job/Test_service/6329)   |
| Ubuntu Bionic | :red_circle:     | [#6330](https://ci.wazuh.info/job/Test_service/6330/)   |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---
## Conclusion

- It was decided to close and reopen a new issue https://github.com/wazuh/wazuh/issues/17723#issuecomment-1647922586

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [ ] @teddytpc1 
- [x] @jnasselle 

---

**Comment by Rebits** [comment]
### 06/07/2023
- Launched automatic service tests
- Reviewed results

**Comment by pro-akim** [comment]
# 07/07/2023
CentOs 6 Build has been checked, still remains the rest of the systems.

**Comment by pro-akim** [comment]
# 11/07/2023
LGTM

**Comment by jnasselle** [comment]
# Auditors note

The related pipeline depends on QA repository, and given the fact that first v4.6.0-pre-alpha1 tag was outdated, a new test must be executed.
