### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - System tests

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#17728]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |           https://github.com/wazuh/wazuh/issues/17713                       |
| **Version**                          |                 4.6.0                           |
| **Release candidate #**              |               Pre-Alpha 1                             |
| **Tag**                              |                 [v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1)                          |
| **Previous system tests issue**      |                  https://github.com/wazuh/wazuh/issues/17424    

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusion :red_circle: 

After multiple rounds of tests, there are flaky tests that may pass or not (They were marked as green because sometimes they pass, but the ones that never pass are red). Also, the basic cluster environment tests that fail, never pass. 

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by roronoasins** [comment]
The following environments were tested:
- One Manager Agent
- Four Manager Disconnected Node
- Agentless Cluster
- Enrollment Cluster

> The packages path is not the same that we have, some minor changes were applied to the playbooks
> Also, some bugs were fixed so the environments could be created

Tomorrow will continue with the execution.

**Comment by roronoasins** [comment]
All the tests were run, but some of them are unstable:
- manager_agent
- agentless_cluster
> These environments fail when using the marker to run their tests, but if you isolate them, they pass

Besides, the `basic_cluster` environment does not start as expected:

<details><summary><code>ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"package_repository":"packages-dev", "repository": "warehouse/test", "package_version": "4.6.0", "package_revision": "1"}'</code></summary>

```
TASK [roles/manager-role : Start Wazuh] **********************************************************************************************************************************************************************
viernes 07 julio 2023  12:10:44 +0100 (0:00:00.186)       0:00:23.353 ********* 
fatal: [wazuh-manager]: FAILED! => changed=true 
  cmd:
  - /var/ossec/bin/wazuh-control
  - restart
  delta: '0:00:10.605390'
  end: '2023-07-07 13:10:54.871528'
  msg: non-zero return code
  rc: 1
  start: '2023-07-07 13:10:44.266138'
  stderr: |-
    2023/07/07 13:10:44 wazuh-authd: WARNING: The <force_insert> tag is deprecated. Use <force> instead.
    2023/07/07 13:10:44 wazuh-authd: WARNING: The <force_time> tag is deprecated. Use <force> instead.
    2023/07/07 13:10:44 wazuh-execd[1188] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
    2023/07/07 13:10:44 wazuh-execd[1188] main.c:111 at main(): DEBUG: Wazuh home directory: /var/ossec
    2023/07/07 13:10:44 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
    2023/07/07 13:10:45 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
    2023/07/07 13:10:45 wazuh-authd: WARNING: The <force_insert> tag is deprecated. Use <force> instead.
    2023/07/07 13:10:45 wazuh-authd: WARNING: The <force_time> tag is deprecated. Use <force> instead.
    2023/07/07 13:10:47 wazuh-execd[1336] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
    2023/07/07 13:10:47 wazuh-execd[1336] main.c:111 at main(): DEBUG: Wazuh home directory: /var/ossec
    2023/07/07 13:10:49 wazuh-syscheckd: INFO: (6678): No directory provided for syscheck to monitor.
    2023/07/07 13:10:49 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
    2023/07/07 13:10:49 rootcheck: INFO: Rootcheck disabled.
    2023/07/07 13:10:53 wazuh-modulesd: WARNING: The <ignore_time> tag at module 'vulnerability-detector' is deprecated for version newer than 4.3.
    Killed
  stderr_lines: <omitted>
  stdout: |-
    wazuh-clusterd not running...
    wazuh-modulesd not running...
    wazuh-monitord not running...
    wazuh-logcollector not running...
    wazuh-remoted not running...
    wazuh-syscheckd not running...
    wazuh-analysisd not running...
    wazuh-maild not running...
    wazuh-execd not running...
    wazuh-db not running...
    wazuh-authd not running...
    wazuh-agentlessd not running...
    wazuh-integratord not running...
    wazuh-dbd not running...
    wazuh-csyslogd not running...
    wazuh-apid not running...
    Wazuh v4.6.0 Stopped
    Starting Wazuh v4.6.0...
    wazuh-apid: Non existent process 1256, removing from /var/ossec/var/run...
    wazuh-apid: Non existent process 1253, removing from /var/ossec/var/run...
    wazuh-apid: Non existent process 1256, removing from /var/ossec/var/run...
    wazuh-apid: Non existent process 1253, removing from /var/ossec/var/run...
    wazuh-apid: Non existent process 1256, removing from /var/ossec/var/run...
    wazuh-apid: Non existent process 1253, removing from /var/ossec/var/run...
    Started wazuh-apid...
    Started wazuh-csyslogd...
    Started wazuh-dbd...
    Started wazuh-integratord...
    Started wazuh-agentlessd...
    Started wazuh-authd...
    Started wazuh-db...
    Started wazuh-execd...
    Started wazuh-analysisd...
    Started wazuh-syscheckd...
    Started wazuh-remoted...
    Started wazuh-logcollector...
    Started wazuh-monitord...
    Started wazuh-modulesd...
    wazuh-clusterd did not start correctly.
  stdout_lines: <omitted>
```

</details> 

Need to fix this behavior.

**Comment by roronoasins** [comment]
## Test results
> Need to be able to deploy and provision the basic cluster and check with multiple run the flaky tests (the ones marked as red, because with a second run they pass)

| | | | | | | |
|--|--|--|--|--|--|--|
| | **Test name** |  **Status** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** |
| | *One Manager Agent* | 
|1| test_fim/test_files/test_files_cud.py | :green_circle:  | 9 | 0 | 0 |
|2| test_fim/test_synchronization/test_synchronization.py | :green_circle: | 6 | 0 | 0 |  
| | *Four Manager Disconnected Node* |
|3| test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py | :green_circle: | 2 | 0 | 0 |  
| | *Agentless Cluster* |
|4| test_cluster/test_integrity_sync/test_integrity_sync.py | :red_circle: | 3 | 0 | 1 |  
|5| test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py |  :green_circle: | 1 | 0 | 0 | 
|6| test_jwt_invalidation/test_change_rbac_mode.py |  :green_circle: | 4| 0 | 0 |  
|7| test_jwt_invalidation/test_change_security_resources.py | :green_circle: | 4 | 0 | 0 |  
|8| test_jwt_invalidation/test_disconnected_nodes.py |  :green_circle: | 1 | 0 | 0 |   
|9| test_jwt_invalidation/test_revoke_endpoint.py | :green_circle: | 6  | 0 | 0 |   
|10| test_jwt_invalidation/test_update_password.py |  :green_circle: | 4 | 0 | 0 |  
| | *Enrollment Cluster* |
|10| test_cluster/test_agent_enrollment/test_agent_enrollment.py | :green_circle: |  1 | 0 | 0 |   
|11| test_cluster/test_agent_groups/test_agent_default_group_added.py | :green_circle: | 3  | 0 | 0 |  
|12| test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  |  :green_circle: | 1  | 0 | 0 |  
|13| test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py | :green_circle: |  2  | 0 | 0 |   
|14| test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py | :green_circle: | 4 | 0 | 0 |   
|15| test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py |  :green_circle: | 2  | 0 | 0 
|16| test_cluster/test_agent_groups/test_assign_agent_to_a_group.py | :red_circle: | 3 | 0 | 1 |   
|17| test_cluster/test_agent_groups/test_assign_groups_guess.py |  :red_circle: | 11  | 0 | 1 |   
|18| test_cluster/test_agent_groups/test_agent_groups.py | :green_circle: | 1 | 0 | 0 |  
|19| test_cluster/test_agent_groups/test_remove_group.py | :green_circle: | 10  | 0 | 0 | 
| | *Manager Agent* |
|20| test_active_response_log_format/test_active_response_log_format.py | :green_circle: | 0  | 0 | 3 |   
|  | *Basic Cluster*   |
|21| test_cluster/test_agent_info_sync/test_agent_info_sync.py |  :black_circle:  | 2  | 0 | 0 |   
|22| test_cluster/test_agent_key_polling/test_agent_key_polling.py |   :black_circle: |1 | 0 | 0 |  
|23| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py |:black_circle: | 1 | 0 | 0 |  
|24| test_multigroups/test_multigroups.py | :black_circle: | 4  | 0 | 0 | 
|25| test_cluster/test_agent_groups/test_agent_groups_forced_change.py |   :black_circle: | 3  | 0 | 0 |  
| | *Big Cluster 40 Agents* |
|26| test_cluster/test_agent_groups/test_groups_sync_default.py | :black_circle: | 2 |0| 0 |   
|27| test_cluster/test_agent_groups/test_groups_sync_time.py | :black_circle: | 2 | 0 | 0 | 
| | *Basic Environment* |
|28| test_agent_auth/test_agent_auth.py | :green_circle: | 20  | 0 | 0 |
|29| test_enrollment/test_enrollment.py | :red_circle: | 0 | 0 | 20  | #16664 |

**Comment by juliamagan** [comment]
## Review comments

Update the conclusion in the main comment, please.

If the issue will not be opened because the tests are flaky, this should be indicated. Also, if they are flaky, we need some successful execution to prove that they are flaky. If they fail consistently, we should open an issue to investigate and fix it if necessary.

**Comment by pro-akim** [comment]
LGTM

**Comment by jnasselle** [comment]
Unfortunately, wazuh/wazuh-qa v4.6.0-pre-alpha1 tag was outdated. In consequence, the current analysis could be inaccurate and meaningless.

A new issue will be created to execute the same tasks but with the new fixed tag
