### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - Register

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17721]
### Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Main packages metrics issue**  | #17718                                                   |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |

---

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

| Test | Build |
| :--  | :--   |
| Test_registration_tier  | [#84](https://ci.wazuh.info/job/Test_registration_tier/84)   |

---

| System               | Status | 
| :--                  | :--:   |
| CentOS 8             | :yellow_circle:     |
| CentOS 7             | :yellow_circle:     |
| CentOS 6             | :yellow_circle:     |
| CentOS 5             | :yellow_circle:     |
| Debian 11            | :yellow_circle:     |
| Debian 10            | :yellow_circle:     |
| Debian 9             | :yellow_circle:     |
| Debian 8             | :yellow_circle:     |
| Debian 7             | :yellow_circle:     |
| Fedora 32            | :yellow_circle:     |
| Fedora 31            | :yellow_circle:     |
| Ubuntu Focal         | :yellow_circle:     |
| Ubuntu Bionic        | :yellow_circle:     |
| Ubuntu Xenial        | :yellow_circle:     |
| Ubuntu Precise       | :yellow_circle:     |
| Ubuntu Trusty        | :yellow_circle:     |
| Amazon Linux 1       | :yellow_circle:     |
| Amazon Linux 2       | :yellow_circle:     |
| Oracle Linux 6       | :yellow_circle:     |
| Oracle Linux 7       | :yellow_circle:     |
| Oracle Linux 8       | :yellow_circle:     |
| openSUSE Tumbleweed  | :red_circle:     |
| Red Hat 6            | :yellow_circle:     |
| Red Hat 7            | :yellow_circle:     |
| Red Hat 8            | :yellow_circle:     |
| Red Hat 9            | :yellow_circle:     |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Conclusions

- :yellow_circle: [OpenSUSE Tumbleweed](https://github.com/wazuh/wazuh/issues/17721#issuecomment-1624016509): Action item -> https://github.com/wazuh/wazuh-jenkins/pull/5405

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [ ] @teddytpc1 
- [x] @jnasselle 

---

**Comment by Rebits** [comment]
<details><summary>AMD64 - OpenSUSE Tumbleweed</summary>

```
19:44:15  TASK [Download openSUSE Tumbleweed GPG Key] ************************************
19:44:15  fatal: [amd64-opensuse-tumbleweed-base_0]: FAILED! => {
19:44:15      "changed": true,
19:44:15      "checksum_dest": null,
19:44:15      "checksum_src": "42602bcc4db9da783513472a3753d1b4e96e4cdb",
19:44:15      "dest": "/tmp/gpg-pubkey-29b700a4-62b07e22.asc",
19:44:15      "elapsed": 1,
19:44:15      "src": "/tmp/ansible-moduletmp-1686591854.9151192-ql0xk_d1/tmpxbtgg6hn",
19:44:15      "url": "https://build.opensuse.org/projects/openSUSE:Tumbleweed/public_key"
19:44:15  }
19:44:15  
19:44:15  MSG:
19:44:15  
19:44:15  The checksum for /tmp/gpg-pubkey-29b700a4-62b07e22.asc did not match 3908048b3b68231b68572c90fe0d49d4d278901468a8f3580ee0861695e1a98b; it was 06a9cf0f538948f627fcee482d1e1e0e129ef95d46278db98f8a81e3160f9dd2.
```

Error related to: https://github.com/wazuh/wazuh-jenkins/issues/5279 (Change not included in 4.6.0 branch)

</details>

**Comment by Rebits** [comment]
### 06/07/2023
- Launched automatic register tests
- Reviewed results

**Comment by pro-akim** [comment]
# 11/07/2023
LGTM

**Comment by pro-akim** [comment]
# 11/07/2023
Unfortunately, the attached links with evidence have expired, so in order to evaluate whether the solution was implemented correctly, the pipelines will need to be run again.

Regarding the solution provided for the detected issues, I noticed that the issues related to the incorrect path as related with pytest have been addressed. However, I don't see a solution for the problems related to the Local internal options config. Are these also indirectly addressed by the proposed solutions?
