### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - API integration tests

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#17729]
The following issue aims to run all [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) for the current release candidate, report the results, and open new issues for any encountered errors.

## API integration tests information
|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         | [17713](https://github.com/wazuh/wazuh/issues/17713) |
| **Version**                              | 4.6.0 |
| **Release candidate #**                  | Pre-Alpha 1 |
| **Tag**                                  | [v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1) |
| **Previous API integration tests issue** | [17449](https://github.com/wazuh/wazuh/issues/17449) |

## Test report procedure

All individual test checks must be marked as:

| Result                          | Description                                |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 

| Status                          | Description                                |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed "check". |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be appropriately addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended test results report must be attached as a zip or text. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

The overall status is 🔴.

This is because of a [known issue](https://github.com/wazuh/wazuh/issues/17690) affecting multiple tests and will be fixed in the next release.

You can find all the details of the results in [this comment](https://github.com/wazuh/wazuh/issues/17729#issuecomment-1627812567).

> **Note**: All the reports show several warnings.

## Validation of auditors

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias 
- [x] @Selutario 
- [x] @jnasselle

**Comment by mauromalara** [comment]
## Test execution

**Pipeline**: https://ci.wazuh.info/job/Test_integration_endpoints/

**Parameters**:

<img width="130" alt="image" src="https://github.com/wazuh/wazuh/assets/39094716/f9024c20-8d03-47a1-b306-1890c825232e">

## Test report

The following file contains the tests result in HTML format:

## Test results

WIP.

**Comment by pro-akim** [comment]
# Update - Review
test_syscollector_endpoints.tavern.yaml has 159 failed results only.
It does not have 16 passed results.

It is possible to be checked in Test_integration_endpoints_B3486_test_syscollector_endpoints.txt

```
test_syscollector_endpoints.tavern.yaml
================ 159 failed, 173 warnings in 2300.26s (0:38:20) ================


```
The rest LGTM
