### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - Indexer/Dashboard packages

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17725]
### Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Main packages metrics issue**  | #17718                                                   |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |

---

## Checks

System         | Install | Upgrade | Remove | Purge | Service | Systemd | Working (Curl) | Dashboard/Indexer VERSION file |
:--            | :--:    | :--:    | :--:   | :--:  | :--:    | :--:    | :--:           | :--:                           |
CentOS 7       | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
CentOS 8       | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Red Hat 7      | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Red Hat 8      | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Red Hat 9      | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Amazon Linux 2 | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Ubuntu 16.04   | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Ubuntu 18.04   | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Ubuntu 20.04   | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |
Ubuntu 22.04   | :red_circle:      | :red_circle:      | :red_circle:     | :red_circle:    | :red_circle:      | :red_circle:      | :red_circle:             | :red_circle:                             |

- [ ] Include traces of each test in plain text

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Conclusion

- :red_circle: Due to https://github.com/wazuh/wazuh-jenkins/issues/5417, current testing could not be executed

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias
- [ ] @teddytpc1
- [x] @jnasselle  

---

**Comment by Rebits** [comment]
- Launched Stack tier tests: https://ci.wazuh.info/job/Test_stack_tier/54/

**Comment by Rebits** [comment]
After solving https://github.com/wazuh/wazuh-jenkins/issues/5417, new stack tier build was launched from which we detected the following errors:
- https://github.com/wazuh/wazuh-packages/issues/2318
- https://github.com/wazuh/wazuh-packages/issues/2319
