### ISSUE TITLE
Release 4.6.0 - Pre-Alpha1 - SELinux

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17722]
### Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #17713                                     |
| **Main packages metrics issue**  | #17718                                                   |
| **Version**                      | 4.6.0                                                   |
| **Release candidate**            | Pre-Alpha1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1          |

---

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

---

| Status | System         | Build  |
| :--:   | :--            | :--    |
| :green_circle:   | CentOS 7      | [#5452](https://ci.wazuh.info/job/Test_selinux/5452/)   |
| :green_circle:   | Ubuntu Bionic | [#5453](https://ci.wazuh.info/job/Test_selinux/5453/)   |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---
## Conclusions

- :green_circle: Both SELinux test went as expected

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [ ] @teddytpc1 
- [x] @jnasselle 

---

**Comment by Rebits** [comment]
### 06/07/2023
- Launched automatic SELINUX tests
- Reviewed results

**Comment by pro-akim** [comment]
# 11/07/2023
LGTM
