### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - Integration tests 

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#17739]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `4.6` |   | `v4.6.0-pre-alpha1`  |  |

We are going to check that the integration tests of the `4.6`  branch of `wazuh-qa` work correctly using the [v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/17713

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|🔵|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:red_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;">:red_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:orange_circle:</td>
<td style="width: 79px;">:red_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">:red_circle:</td>
<td style="width: 79px;">:red_circle:</td>
<td style="width: 97px;">:orange_circle:</td>
<td style="width: 97px;" colspan="2">:orange_circle:</td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">:orange_circle:</td>
<td style="width: 79px;">:orange_circle:</td>
<td style="width: 97px;">:orange_circle:</td>
<td style="width: 97px;" colspan="2">:orange_circle:</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">:orange_circle:</td>
<td style="width: 99px;">:orange_circle:</td>
<td style="width: 79px;">:orange_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">:orange_circle:</td>
</tr>
</tbody>
</table>

## Evidence

**IT Launcher build**:  https://ci.wazuh.info/job/Test_integration_launcher/176/console

### Stoppers
- https://github.com/wazuh/wazuh-qa/issues/4336
- https://github.com/wazuh/wazuh-qa/issues/4340
- https://github.com/wazuh/wazuh-qa/issues/4335
- https://github.com/wazuh/wazuh-qa/issues/4342
 
### New High impact bugs
- https://github.com/wazuh/wazuh-qa/issues/4333
- https://github.com/wazuh/wazuh-qa/issues/4337
- https://github.com/wazuh/wazuh-jenkins/issues/5436

### Known bugs
- https://github.com/wazuh/wazuh-qa/issues/4231
- https://github.com/wazuh/wazuh-jenkins/issues/3487

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by fcaffieri** [comment]
### Test summary

|Test |	Module	|Error|	Issue|
| :--: | --: | --: |  --: | 
https://ci.wazuh.info/job/Test_integration/41371	|test_syscollector	|`JenkinsException: Wrong parameter valueInvalid value for TESTS_PATH parameter.`	|
https://ci.wazuh.info/job/Test_integration/41395	|test_syscollector	|`JenkinsException: Wrong parameter valueInvalid value for TESTS_PATH parameter.`	|
https://ci.wazuh.info/job/Test_integration/41380/	|test_fim	|`TimeoutError: Did not receive expected "DEBUG: ...: Maximum number of entries to be monitored: ..." event `	|
https://ci.wazuh.info/job/Test_integration/41381/	|test_fim	|may be related to https://github.com/wazuh/wazuh-qa/issues/4325	|
https://ci.wazuh.info/job/Test_integration/41394	|test_wazuh_db	|`Wazuh-db test "connection_status":"never_connected"`	|
https://ci.wazuh.info/job/Test_integration/41373	|test_active_response|	`AssertionError: IP was not added to iptable`	|
https://ci.wazuh.info/job/Test_integration/41377	|test_authd	|`TimeoutError: Expected log does not occured: 'The <force_insert> tag is deprecated since version 4.3.0.'`	|
https://ci.wazuh.info/job/Test_integration/41379/	|test_fim	|`TimeoutError: Did not receive expected "DEBUG: ...: No limit set to maximum number of entries to be monitored" event`	|
https://ci.wazuh.info/job/Test_integration/41385/	|test_logcollector|	`ERROR: (1235): Invalid value for element 'log_format': invalid.`	|
https://ci.wazuh.info/job/Test_integration/41386/	|test_logcollector|	Related to https://github.com/wazuh/wazuh-qa/issues/4325	|
https://ci.wazuh.info/job/Test_integration/41390/	|test_remoted	|Error 1: `TimeoutError: if callback pattern is not found in ossec.log in the expected time.` Error 2: `UnboundLocalError: local variable 'keep_alive_agent' referenced before assignment`	|
https://ci.wazuh.info/job/Test_integration/41393	|test_vulnerability_detector|`Error: OSError: Invalid data stream Ths error seams to be generated when execute this: file.decompress_bz2(bz2_file_path=metadata['path'], dest_file_path=metadata['decompressed_file'])`	|

**Comment by Rebits** [comment]
### Active Response :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41373/
**Report**: [agent_centos_html_report_Test_integration_B41373_20230720122956.zip](https://github.com/wazuh/wazuh/files/12121703/agent_centos_html_report_Test_integration_B41373_20230720122956.zip)
**Failed tests**: 
 - `test_execd_firewall_drop`
 
**Issue**: https://github.com/wazuh/wazuh-qa/issues/4336
***

### Description

The `test_execd_firewall_drop` test check if 'firewall-drop' command of 'active response' is executed correctly. For this purpose, a simulated agent. This could be the root of this failure. Maybe it's related with a known failure in the AR and enrollment module https://github.com/wazuh/wazuh-qa/pull/4205

**Comment by Rebits** [comment]
# Logcollector :red_circle: 

## Agent :orange_circle: 

### Details

**Build**: https://ci.wazuh.info/job/Test_integration/41386/ 
**Jenkins error output**:

<details>


```
12:57:38  Collecting pyyaml==5.4 (from -r requirements.txt (line 26))
12:57:38    Downloading PyYAML-5.4.tar.gz (174 kB)
12:57:38       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.8/174.8 kB 10.1 MB/s eta 0:00:00
12:57:38    Installing build dependencies: started
12:57:38    Installing build dependencies: finished with status 'done'
12:57:38    Getting requirements to build wheel: started
12:57:38    Getting requirements to build wheel: finished with status 'error'
12:57:38  
12:57:38  
12:57:38  STDERR:
12:57:38  
12:57:38    error: subprocess-exited-with-error
12:57:38    
12:57:38    × Getting requirements to build wheel did not run successfully.
12:57:38    │ exit code: 1
12:57:38    ╰─> [62 lines of output]
12:57:38        running egg_info
12:57:38        writing lib3/PyYAML.egg-info/PKG-INFO
12:57:38        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
12:57:38        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
12:57:38        /tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
12:57:38        !!
12:57:38        
12:57:38                ********************************************************************************
12:57:38                The license_file parameter is deprecated, use license_files instead.
12:57:38        
12:57:38                By 2023-Oct-30, you need to update your project and remove deprecated calls
12:57:38                or your builds will no longer be supported.
12:57:38        
12:57:38                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
12:57:38                ********************************************************************************
12:57:38        
12:57:38        !!
12:57:38          parsed = self.parsers.get(option_name, lambda x: x)(value)
12:57:38        Traceback (most recent call last):
12:57:38          File "/opt/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
12:57:38            main()
12:57:38          File "/opt/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
12:57:38            json_out['return_val'] = hook(**hook_input['kwargs'])
12:57:38          File "/opt/python3/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
12:57:38            return hook(config_settings)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
12:57:38            return self._get_build_requires(config_settings, requirements=['wheel'])
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
12:57:38            self.run_setup()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
12:57:38            exec(code, locals())
12:57:38          File "<string>", line 295, in <module>
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
12:57:38            return distutils.core.setup(**attrs)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
12:57:38            return run_commands(dist)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
12:57:38            dist.run_commands()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
12:57:38            self.run_command(cmd)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
12:57:38            super().run_command(command)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
12:57:38            cmd_obj.run()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 314, in run
12:57:38            self.find_sources()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
12:57:38            mm.run()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
12:57:38            self.add_defaults()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
12:57:38            sdist.add_defaults(self)
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
12:57:38            super().add_defaults()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
12:57:38            self._add_defaults_ext()
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
12:57:38            self.filelist.extend(build_ext.get_source_files())
12:57:38          File "<string>", line 201, in get_source_files
12:57:38          File "/tmp/pip-build-env-xb3amzga/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
12:57:38            raise AttributeError(attr)
12:57:38        AttributeError: cython_sources
12:57:38        [end of output]
12:57:38    
12:57:38    note: This error originates from a subprocess, and is likely not a problem with pip.
12:57:38  error: subprocess-exited-with-error
12:57:38  
12:57:38  × Getting requirements to build wheel did not run successfully.
12:57:38  │ exit code: 1
12:57:38  ╰─> See above for output.
12:57:38  
12:57:38  note: This error originates from a subprocess, and is likely not a problem with pip.
```


</details>



**Issue**: https://github.com/wazuh/wazuh-qa/issues/4325

### Description

The installation of the integration test's Python requirements (located in requirements.txt) fails due to the new Cython3 version released. Solved https://github.com/wazuh/wazuh-qa/pull/4326. 4.6.0 was not populated with the fix


## Manager :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41385/
**Report** [manager_html_report_Test_integration_B41385_20230720122842(1).zip](https://github.com/wazuh/wazuh/files/12121941/manager_html_report_Test_integration_B41385_20230720122842.1.zip): 
**Failed Tests**: 
- `test_basic_configuration_log_format`
**Issue**:  https://github.com/wazuh/wazuh-qa/issues/4333


### Description

Failed test ensure that logcollector daemon detects invalid configurations for the 'log_format' tag. However, this seems to be a false positive due to the expected error appear in the manager's logs:
```
2023/07/20 11:41:16 wazuh-logcollector[11890] localfile-config.c:382 at Read_Localfile(): ERROR: (1235): Invalid value for element 'log_format': invalid. 
```

**Comment by Rebits** [comment]
# Vulnerability Detector

## Manager

**Build**: https://ci.wazuh.info/job/Test_integration/41393/
**Report**:  [manager_html_report_Test_integration_B41393_20230720122537.zip](https://github.com/wazuh/wazuh/files/12121969/manager_html_report_Test_integration_B41393_20230720122537.zip)
**Failed tests**
- `test_validate_feed_content`

**Issue**: 
- https://github.com/wazuh/wazuh-qa/issues/4231

### Description
This is error is motivated for the use of outdated URLs in the test (https://people.canonical.com/ instead of the updated https://security-metadata.canonical.com/).

**Comment by Rebits** [comment]
# Analysisd

## Manager

**Build**: https://ci.wazuh.info/job/Test_integration/41375/
**Report**: [manager_html_report_Test_integration_B41375_20230720122502(1).zip](https://github.com/wazuh/wazuh/files/12122044/manager_html_report_Test_integration_B41375_20230720122502.1.zip)
**Failed tests**:
- `test_validate_all_win32_registry_alerts`

**Issue**: To Open


### Description

The `test_validate_all_win32_registry_alerts` test check if the alerts generated by the 'wazuh-analysisd' daemon from Windows registry-related `syscheck' events are valid. It seems that no alerts were triggered for the test use cases. Further research is required

**Comment by Rebits** [comment]
# Authd :red_circle: 

## Manager :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41377/
**Report**: [manager_html_report_Test_integration_B41377_20230720122943(1).zip](https://github.com/wazuh/wazuh/files/12122111/manager_html_report_Test_integration_B41377_20230720122943.1.zip)
**Failed tests**:
- `test_authd_force_options`

**Issue**:
- https://github.com/wazuh/wazuh-qa/issues/4337


### Description
The test `test_authd_force_options` checks that every input message in authd port generates the adequate output. In this case, it fails due to a changed in the expected log. From `The <force_insert> tag is deprecated since version 4.3.0.'` to `The <force_insert> tag is deprecated. Use <force> instead.`

**Comment by Rebits** [comment]
# Enrollment :red_circle: / :orange_circle: 

## Agent

### Details
**Build**: https://ci.wazuh.info/job/Test_integration/41378/
**Report**:  [agent_windows_html_report_Test_integration_B41378_20230720122930(3).zip](https://github.com/wazuh/wazuh/files/12122198/agent_windows_html_report_Test_integration_B41378_20230720122930.3.zip)

> **Note**:
> centOS agent report was not generated

**Failed tests**:
- `test_agent_auth_enrollment`
- `test_agentd_enrollment`

**Issues**:
- https://github.com/wazuh/wazuh-jenkins/issues/3487 (centOS agent error)
-  To open (windows agent error)

### Description

Regarding the agent centos errors, these are related to a known failure that prevent correct finish of the pytest session. Reported https://github.com/wazuh/wazuh-jenkins/issues/3487.

Regarding the failures of windows agent, the failed tests ensure that different configuration generates the adequate enrollment message or the corresponding error log. However, it seems that multiple tests cases fails due to a timeout in the agent_auth exe:

```
E               subprocess.TimeoutExpired: Command '['C:\\Program Files (x86)\\ossec-agent\\agent-auth.exe', '-m', '127.0.0.1']' timed out after 2 seconds
```


Further research is required

**Comment by Rebits** [comment]
# WazuhDB :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41394/
**Report**: [manager_html_report_Test_integration_B41394_20230720122741.zip](https://github.com/wazuh/wazuh/files/12122252/manager_html_report_Test_integration_B41394_20230720122741.zip)
**Failed tests**:
- `test_wazuh_db_messages_global`: 


**Issue**: https://github.com/wazuh/wazuh-qa/issues/4335

### Description

It seems that multiple errors appears:
- `Test: Insert commands`: This test case fail due to response included a new field `status_code` in the response

```
 AssertionError: Failed test case stage 10: global get-agent-info after insert. Expected: ok [{"id":1,"name":"TestName1","ip":"0.0.0.1","register_ip":"0.0.0.1","internal_key":"TopSecret","node_name":"unknown","date_add":1599223378,"group":"TestGroup1","group_sync_status":"synced","sync_status":"synced","connection_status":"never_connected","disconnection_time":0,"group_config_status":"not synced"}]. Response: ok [{"id":1,"name":"TestName1","ip":"0.0.0.1","register_ip":"0.0.0.1","internal_key":"TopSecret","node_name":"unknown","date_add":1599223378,"group":"TestGroup1","group_sync_status":"synced","sync_status":"synced","connection_status":"never_connected","disconnection_time":0,"group_config_status":"not synced","status_code":0}]
E           assert False
```

- `Test: Update commands`, `Test Reset connection status`,`Test get-agents-by-connection-status command`, `Test: disconnect-agents command`: Request seems to include a invalid JSON data
```
E           AssertionError: Failed test case stage 3: global update-connection-status pending success. Expected: ok. Response: err Invalid JSON data, near '{"id":1,"connection_status":"pen'
E           assert False
```

```
E           AssertionError: Failed test case stage 1: global update-connection-status pending success. Expected: ok. Response: err Invalid JSON data, near '{"id":1,"connection_status":"pen'
E           assert False
```

```
E           AssertionError: Failed test case stage 1: global update-connection-status never_connected. Expected: ok. Response: err Invalid JSON data, near '{"id":1,"connection_status":"nev'
E           assert False

```

```
E           AssertionError: Failed test case stage 2: global update-connection-status as active for agent 1 success. Expected: ok. Response: err Invalid JSON data, near '{"id":1,"connection_status":"act'
E           assert False


```  

- `Test: get-all-agents command`: It seems that not all agent was correctly inserted
```
E           AssertionError: Failed test case stage 1: global get-all-agents success. Expected: ok [{"id":0},{"id":1},{"id":2}]. Response: ok [{"id":0},{"id":1}]
E           assert False
```

- `Test: Manager keepalive`: Response include multiple not expected fields:
```
         else:
                match = validate_wazuh_db_response(expected_output, response)
>           assert match, 'Failed test case stage {}: {}. Expected: {}. Response: {}' \
                .format(index + 1, stage['stage'], expected_output, response)
E           AssertionError: Failed test case stage 1: global manager get-agent-info success pre update. Expected: ok [{"id":0,*,"last_keepalive":253402300799,"group_sync_status":"synced","sync_status":"synced","connection_status":"active","disconnection_time":0,"group_config_status":"synced"}]. Response: ok [{"id":0,"name":"ip-172-31-1-203.ec2.internal","ip":"127.0.0.1","register_ip":"127.0.0.1","os_name":"CentOS Linux","os_version":"7.9","os_major":"7","os_minor":"9","os_platform":"centos","os_uname":"Linux |ip-172-31-1-203.ec2.internal |3.10.0-1160.81.1.el7.x86_64 |#1 SMP Fri Dec 16 17:29:43 UTC 2022 |x86_64","os_arch":"x86_64","version":"Wazuh v4.6.0","manager_host":"ip-172-31-1-203.ec2.internal","node_name":"node01","date_add":1689852999,"last_keepalive":253402300799,"group_sync_status":"synced","sync_status":"synced","connection_status":"active","disconnection_time":0,"group_config_status":"synced","status_code":0}]
E           assert False
```

**Comment by Rebits** [comment]
### Syscollector :orange_circle: 

**Build** https://ci.wazuh.info/job/Test_integration/41371/
**Issue**:
- https://github.com/wazuh/wazuh-jenkins/issues/5436


### Description

Syscollector IT module is not supported for 4.6.0

**Comment by Rebits** [comment]
# Remoted :red_circle: 

## Manager :red_circle: 

### Details 
**Build**: https://ci.wazuh.info/job/Test_integration/41390/
**Report**: [manager_html_report_Test_integration_B41390_20230720122806(1).zip](https://github.com/wazuh/wazuh/files/12122732/manager_html_report_Test_integration_B41390_20230720122806.1.zip)
**Failed tests**: 
- `test_push_shared_config`
- `test_agent_remote_configuration`

**Issue**: To Open

**Comment by roronoasins** [comment]
# FIM :red_circle:

## Windows/CentOS Agent :red_circle: 

### CentOS

Build: https://ci.wazuh.info/job/Test_integration/41380
Report: [agent_centos_html_report_Test_integration_B41380_20230720122639.zip](https://github.com/wazuh/wazuh/files/12123341/agent_centos_html_report_Test_integration_B41380_20230720122639.zip)
Failed tests:
- test_file_limit_delete_full: https://github.com/wazuh/wazuh-qa/issues/4346
- test_file_limit_full: https://github.com/wazuh/wazuh-qa/issues/4148
- test_file_limit_default: pending to create
- test_file_limit_no_limit: pending to create
- test_file_limit_values: pending to create
- test_synchronize_integrity_scan: https://github.com/wazuh/wazuh-qa/issues/947

### Windows

Build: https://ci.wazuh.info/job/Test_integration/41380
Report: [agent_windows_html_report_Test_integration_B41380_20230720122639.zip](https://github.com/wazuh/wazuh/files/12123346/agent_windows_html_report_Test_integration_B41380_20230720122639.zip)
Failed tests:
- test_file_limit_delete_full: https://github.com/wazuh/wazuh-qa/issues/4346
- test_file_limit_full: https://github.com/wazuh/wazuh-qa/issues/4148
- test_sync_enabled_win32: https://github.com/wazuh/wazuh-qa/issues/2773

**Comment by jnasselle** [comment]
Unfortunately, wazuh/wazuh-qa v4.6.0-pre-alpha1 tag was outdated. In consequence, the current analysis could be inaccurate and meaningless.

A new issue will be created to execute the same tasks but with the new fixed tag
