### ISSUE TITLE
Error when retrieving plain logs using the API

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17740]
|Wazuh version|Component|
|---|---|
| 4.6.0 | Wazuh API |

## Description
When running [GET /manager/logs](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_log), this is the response obtained:
```JSON
{
  "title": "Wazuh Internal Error",
  "detail": "Could not find any Wazuh log file",
  "remediation": "Please check `WAZUH_HOME/logs`",
  "dapi_errors": {
    "master-node": {
      "error": "Could not find any Wazuh log file",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1020
}
```

It seems there is a bug in the framework function. If no `ossec.json` exists, it will raise an exception if the configured log format is `plain`, which is the [default one](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/logging.html#log-format):
https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/framework/wazuh/core/manager.py#L113-L119

It is important to make sure that the original problem that needed to be addressed is still fixed after these changes:
- https://github.com/wazuh/wazuh/issues/15656

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Description

- Command execution test to display the error

**Comment by javiersanchz** [comment]
## Descrption

- I modified ossec.conf to see the error that arises with GET/manager/logs
- I've been modifying def get_ossec_logs
