### ISSUE TITLE
syscollector does not correctly learn the full version for the Opera web browser

### ISSUE THREAD

**Issue by fernandogont** [wazuh/wazuh#17749]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | syscollector | Agent | MacOS | MacOS 13.4.1 |

It seems that when recording information about the Opera web browser, **only part of the version is learned/recorded.**
For example, I'm running Opera One(version: 100.0.4815.30) (arm64), but syscollector claims that the Opera version is 100.0.

This means that we cannot employ syscollector to double-check that the browser is up to date.

(This issue is **NOT** present for other browsers such as Google Chrome or Firefox, where the full version is recorded)

### DoD
- [x] RCA - ETA 
- [x] Fix issue.
- [x] Add tests.

**Comment by Dwordcito** [comment]
@matias-braida please RCA, try to reproduce in AMD64, If the bug is not reproducible in ARM, request an environment under the known internal process.

**Comment by matias-braida** [comment]
The issue was reproduced in wazuh-agent running in macOS Sierra and Monterey.
![image](https://github.com/wazuh/wazuh/assets/101227434/cefe3a46-0767-4cd0-a3b6-bad4c20c3ac3)
