### ISSUE TITLE
Engine Framework API - Graph module endpoints implementation 

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17742]
## Description

This issue is part of the task https://github.com/wazuh/wazuh/issues/17058 and is to implement the API endpoints that will access the resources from the **graph** module of the new Engine.

Engine development branch: [11334-dev-new-wazuh-engine](https://github.com/wazuh/wazuh/tree/11334-dev-new-wazuh-engine)

### Endpoints

| Endpoint | Description | Engine command(s) |
| - | - | - |
| `GET /engine/graph/resource` | Get a resource from the graph | `graph.resource/get` |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):

- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Specification.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

- Added the endpoint to the spec
- Created controllers, engine framework and core functions
- Mocked the `graph.resource/get` command
- Created unit and integration tests
- Added integration test mapping

Moving to blocked until the Engine is integrated in the Docker development environment.

**Comment by fdalmaup** [comment]
Wazuh 5.0 has been redefined and will follow a different approach related to the current Wazuh API. More information:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
- https://github.com/wazuh/wazuh/issues/22887
- https://github.com/wazuh/wazuh/issues/23577
- https://github.com/wazuh/wazuh-dashboard/issues/164
