### ISSUE TITLE
[Alerts index pattern] No template found for the selected index-pattern title [wazuh-alerts-*]

### ISSUE THREAD

**Issue by JagatheeshMani** [wazuh/wazuh#17751]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | Wazuh component | Manager/Agent | Packages/Sources | UBUNTU 22.4 |

INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Getting list of valid index patterns...
INFO: Valid index patterns found: 1
INFO: Found default index pattern with title [wazuh-alerts-*]: yes
INFO: Checking the app default pattern exists: id [wazuh-alerts-*]...
INFO: Default pattern with id [wazuh-alerts-*] exists: yes
ACTION: Default pattern id [wazuh-alerts-*] set as default index pattern
INFO: Checking the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id exists [wazuh-alerts-*]: yes
INFO: Index pattern id in cookie: yes [wazuh-alerts-*]
INFO: Checking if the index pattern id [wazuh-alerts-*] exists...
INFO: Index pattern id [wazuh-alerts-*] found: yes title [wazuh-alerts-*]
INFO: Checking if exists a template compatible with the index pattern title [wazuh-alerts-*]
INFO: Template found for the selected index-pattern title [wazuh-alerts-*]: no
ERROR: No template found for the selected index-pattern title [wazuh-alerts-*]
INFO: Index pattern id in cookie: [wazuh-alerts-*]
INFO: Getting index pattern data [wazuh-alerts-*]...
INFO: Index pattern data found: [yes]
INFO: Refreshing index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]...
ACTION: Refreshed index pattern fields: title [wazuh-alerts-*], id [wazuh-alerts-*]

Im facing this issue in Check alerts index pattern pannel.

Can someone help me to overcome this

**Comment by matias-braida** [comment]
Hello JagatheeshMani,
First of all, thanks for using Wazuh.

This error message is shown when Filebeat does not push the index template to the Elasticsearch cluster.
This could indicate that there is an issue with the connection from Filebeat to Elasticsearch.

Check that Filebeat is working properly. Please run the command: `filebeat test output`
The output should be something similar to:
```
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

You can also manually add the index by running the following command:
`curl https://raw.githubusercontent.com/wazuh/wazuh/v4.4.4/extensions/elasticsearch/7.x/wazuh-template.json | curl -X PUT "https://localhost:9200/_template/wazuh" -H 'Content-Type: application/json' -d @- -u <elasticsearch_user>:<elasticsearch_password> -k
`

Please take a look at this link: https://documentation.wazuh.com/current/user-manual/elasticsearch/troubleshooting.html#no-template-found-for-the-selected-index-pattern

Please let me know if this helps.
Regards

**Comment by Dwordcito** [comment]
We closed the issue due to lack of response, we thank you very much for your participation in the community, and we always look forward to seeing you!

**Comment by othienorichard** [comment]
Hello @Dwordcito i have the same issue, too sad @matias-braida couldn't respond. however on running this i get this output

 filebeat test output
elasticsearch: https://wazuh.indexer:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 172.18.0.2
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... ERROR 401 Unauthorized: Unauthorized
  
  why is this unauthorized

**Comment by keannan** [comment]
> curl https://raw.githubusercontent.com/wazuh/wazuh/v4.4.5/extensions/elasticsearch/7.x/wazuh-template.json | curl -X PUT "https://localhost:9200/_template/wazuh" -H 'Content-Type: application/json' -d @- -u <elasticsearch_user>:<elasticsearch_password> -k bash: elasticsearch_user: No such file or directory

You need to add your elasticsearch_user and password after -u 
In most cases user is logstash.
