### ISSUE TITLE
Investigate about supporting functionalities for any of the fields present in an endpoint response

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17771]
## Description

During the development of the issue https://github.com/wazuh/wazuh/issues/16714 we wanted to query the values of the `GET /groups` endpoint by any of the fields present in the response but we could only use `name`, since that was the only field that was in the `group` table in SQL.

The current design is limited to filter, sort and select fields that are in an SQL table. It's not possible to include other fields that may be part of the response but that are not in the table.

> In cases where there's no  database query performed, we use `process_array`, which takes any field as long as it's present in the data. The problem is that in order to use `process_array` with a database query, the latter should always return all rows, resulting in a waste of resources.

For example, if we add the `query` parameter to the `GET /groups` endpoint, we can only query by the `name` field and not by `mergedSum` or `configSum` since they are not in the `group` table but added afterwards depending on some conditions.

https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/framework/wazuh/agent.py#L553-L606

https://github.com/wazuh/wazuh/blob/a7b092565dbd3f48e64bcfa77d8d2087431b0fb0/framework/wazuh/core/agent.py#L271-L273

This issue aims to find a way of extending the selection, filtering and sorting functionalities for any fields that are part of the reponse.

**Comment by GGP1** [comment]
## Update

Started investigating about possible solutions to the problem. 

Despite not having arrived to any conclusions yet, I think a potential fix could be to split the fields in two, one part being used by 
the database and the other by the methods that obtain information that is not in the database table.

> The second part would be omitted in the database query

This way, instead of retrieving all results to then filter them, we could obtain just a sub-set. It's important to note that if any field is required to obtain the data that is not in the SQL database, we should always include it.

Lastly, when it's appropiate, I think we should aim to include as much information as possible in the database to make queries as efficient as possible.

**Comment by GGP1** [comment]
## Conclusion

Given that the issue is present in this particular case and that no other endpoint has these requirements, I think we should opt to store the fields `configSum`, `mergedSum` and `count` in the database. There's no point on modifying and adding complexity to the current implementation for the moment.

> If we face the same scenario in the future, it may indicate that the fields should belong in the database

However, if we do find this to be a recurrent problem, I would split the parameters in two groups:

1. Database fields
2. Fields not present in the database

Where the group number 2 would be ommited by the `WazuhDBQuery` class and would be used to filter the results obtained after applying the parameters from group 1. This would allow us to reduce the number of items retrieved from the database while using all parameters.

> This is more efficient than getting all results and then applying the filters.

Here's an example with the `GET /agents` endpoint and the `query` parameter (assuming `configSum` is not a database field):

```py
f_kwargs = {
    query: {
        'db': 'group=default',
       'extra': 'configSum=ab73af41699f13fdd81903b5f23d8d00'
    }
}
...

with WazuhDBQueryAgents(query=q['db']) as db_query:
    data = db_query.run()
...

data = process_array(data['items'], q=q['extra'])

result.affected_items = data
```

The `WazuhDBQueryAgents` class would only apply the `'db'` query and return all agents belonging to the `default` group. Once the results are obtained, they will then go through the second query `extra`, which will discard all the agents with a `configSum` different than the desired.

**Comment by RamosFe** [comment]
## Review

Good Idea. LGTM 🚀

**Comment by Selutario** [comment]
To be done in 
- https://github.com/wazuh/wazuh/issues/19010
