### ISSUE TITLE
Remove deprecated API endpoints

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17781]
## Description
There are multiple endpoints that were deprecated in Wazuh v4.4.0, for example, this one:
- https://github.com/wazuh/wazuh/issues/12365

They are marked with a decorator:
https://github.com/wazuh/wazuh/blob/65c8e7f5615b444b719edb73e36c16ea53a576d5/api/api/controllers/agent_controller.py#L421-L422

All deprecated endpoints should be deleted and any related resource should be removed.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by mhamra** [comment]
### UPDATE

created branch fix/17781-remove-deprecated-endpoints and PR https://github.com/wazuh/wazuh/pull/17815.

**Comment by mhamra** [comment]
### UPDATE

Removed the following artifacts

- Api controllers
  - get_sync_agent
  - get_stats_analysisd_node
  - get_stats_remoted_node
  - get_stats_analysisd
  - get_stats_remoted
  - deprecated_login_user
- Api tests
  - test_get_sync_agent
  - test_get_stats_analysisd_node
  - test_get_stats_remoted_node
  - test_get_stats_analysisd
  - test_get_stats_remoted
- API specs (specs.yaml)
  - AllItemsResponseAgentsSynced component
  - /agents/{agent_id}/group/is_sync
  - /cluster/{node_id}/stats/analysisd
  - /cluster/{node_id}/stats/remoted
  - /manager/stats/analysisd
  - /manager/stats/remoted
- AIT 
  - api/test/integration/test_agent_GET_endpoints.tavern.yaml
    - test_name: GET /agents/{agent_id}/group/is_sync
  - api/test/integration/test_cluster_endpoints.tavern.yaml
    - test_name: GET /cluster/{node_id}/stats/analysisd
    - test_name: GET /cluster/{node_id}/stats/remoted
  - api/test/integration/test_manager_endpoints.tavern.yaml
    - test_name: GET /manager/stats/analysisd
    - test_name: GET /manager/stats/remoted
  - api/test/integration/test_rbac_black_agent_endpoints.tavern.yaml
    - test_name: GET /agents/{agent_id}/group/is_sync
  - api/test/integration/test_rbac_black_manager_endpoints.tavern.yaml
    - test_name: GET /manager/stats/analysisd
    - test_name: GET /manager/stats/remoted
  - api/test/integration/test_rbac_white_agent_endpoints.tavern.yaml
    - test_name: GET /agents/{agent_id}/group/is_sync
  - api/test/integration/test_rbac_white_all_endpoints.tavern.yaml
    - test_name: GET /agents/{agent_id}/group/is_sync
    - test_name: GET /cluster/{node_id}/stats/analysisd
    - test_name: GET /cluster/{node_id}/stats/remoted
    - test_name: GET /manager/stats/analysisd
    - test_name: GET /manager/stats/remoted
  - api/test/integration/test_rbac_white_manager_endpoints.tavern.yaml
    - test_name: GET /manager/stats/analysisd
    - test_name: GET /manager/stats/remoted
- framework
  - stats.deprecated_get_daemons_stats
- framework tests
  - rbac_catalog.yml updated
    - GET /agents/{agent_id}/group/is_sync
    - GET /cluster/{node_id}/stats/analysisd
    - GET /cluster/{node_id}/stats/remoted
    - GET /manager/stats/analysisd
    - GET /manager/stats/remoted
  - test_deprecated_get_daemons_stats

**Comment by mhamra** [comment]
### UPDATE

on-hold until [Update API IT tier 0,1](https://github.com/wazuh/wazuh-qa/issues/4412) implementation.

**Comment by mhamra** [comment]
### UPDATE

- I was learning how to prepare the environment and run integration API tests tier 0 and 1.
- I'm currently working on local environment preparation to run Integrations API tests tier 0 and 1.

**Comment by Selutario** [comment]
To be done as part of any of these epics:
- https://github.com/wazuh/wazuh/issues/22888
- https://github.com/wazuh/wazuh/issues/22677
