### ISSUE TITLE
Missing IPv6 support in host-deny.sh

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#178]
Noticed the following in my active-responses.log today:

```
Fri Sep  1 18:57:44 CEST 2017 Invalid ip/hostname entry: dead:beef:dead:beef:dead:beef:dead:beef
```

Seems the current host-deny.sh shipped with wazuh doesn't support IPv6 addresses:

https://github.com/wazuh/wazuh/blob/v2.1.0/active-response/host-deny.sh#L89 (master as well)

However when checking the OSSEC sources this was added long time ago in e.g. https://github.com/ossec/ossec-hids/commit/d8b9161f015b0091241b2b62d7868bf63a2a182c or https://github.com/ossec/ossec-hids/commit/006192d179c8e8442a9488d7ce35e2639d832e15

Not quite sure why this is missing in the wazuh packages.

**Comment by chemamartinez** [comment]
Hi @kdslkdsaldsal,

Unfortunately, Wazuh doesn't support IPv6 for now. We are working for include this feature as soon as possible.

Best regards.

**Comment by kdslkdsaldsal** [comment]
Mhhh, good to know. Thanks.

I thought there is already IPv6 support as the i'm already getting E-Mail Alerts containing the IPv6 in the Src IP.

**Comment by chemamartinez** [comment]
Hi @ghost, 

The PR #1583 solves this issue so I am closing this issue. Thanks to @iasdeoupxe for the contribution.

Regards.
