### ISSUE TITLE
Testing 4.6.0 - Pre-Alpha 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (3.0d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17849]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #17713                                         |
| **Main footprint metrics issue #** | #17717                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | Pre-Alpha 1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4141/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/monitor-manager-Test_stress_B4141_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/plots/Test_stress_B4141_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4141_manager_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/logs/ossec_Test_stress_B4141_manager_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4141_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/data/monitor-manager-Test_stress_B4141_manager-warehouse-test.csv)
[Test_stress_B4141_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/data/Test_stress_B4141_manager_analysisd_events.csv)
[Test_stress_B4141_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/data/Test_stress_B4141_manager_analysisd_state.csv)
[Test_stress_B4141_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_manager_centos/data/Test_stress_B4141_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/monitor-agent-Test_stress_B4141_centos-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/Test_stress_B4141_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/Test_stress_B4141_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/Test_stress_B4141_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/plots/Test_stress_B4141_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4141_centos_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/logs/ossec_Test_stress_B4141_centos_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4141_centos-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/data/monitor-agent-Test_stress_B4141_centos-warehouse-test.csv)
[Test_stress_B4141_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_centos/data/Test_stress_B4141_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/Test_stress_B4141_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/Test_stress_B4141_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/Test_stress_B4141_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/plots/Test_stress_B4141_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4141_ubuntu_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/logs/ossec_Test_stress_B4141_ubuntu_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4141_ubuntu-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/data/monitor-agent-Test_stress_B4141_ubuntu-warehouse-test.csv)
[Test_stress_B4141_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_ubuntu/data/Test_stress_B4141_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/monitor-winagent-Test_stress_B4141_windows-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/Test_stress_B4141_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/Test_stress_B4141_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/Test_stress_B4141_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/plots/Test_stress_B4141_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4141_windows_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/logs/ossec_Test_stress_B4141_windows_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4141_windows-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/data/monitor-winagent-Test_stress_B4141_windows-warehouse-test.csv)
[Test_stress_B4141_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4141-4320m/B4141_agent_windows/data/Test_stress_B4141_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

**Comment by juliamagan** [comment]
## Analysis report - Logs errors

<details>
<summary>Manager</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5287:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:3348:2023/07/09 00:52:07 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir796': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:3349:2023/07/09 00:52:07 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir3028': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:18165:2023/07/09 03:57:49 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir3639': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:18166:2023/07/09 03:57:49 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir3671': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:18167:2023/07/09 03:57:49 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir3672': No such file or directory
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5284:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:50:2023/07/09 00:06:45 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:53:2023/07/09 00:06:45 wazuh-authd: WARNING: Duplicate IP '172.31.7.39', rejecting enrollment. Agent '003' can't be replaced since it is not disconnected.
```

- Expected logs due to stress test:

```
./var/ossec/logs/ossec.log:439:2023/07/10 00:35:56 sca: WARNING: Interval overtaken.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:7:2023/07/09 00:01:43 wazuh-logcollector: WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files".
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:17:2023/07/09 00:03:18 wazuh-syscheckd: WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.
```


</details>

<details>
<summary>CentOS Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/ossec.log:6:2023/07/10 00:00:48 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
./var/ossec/logs/ossec.log:7:2023/07/10 00:00:48 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
./var/ossec/logs/ossec.log:8:2023/07/10 00:00:49 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml'
./var/ossec/logs/ossec.log:9:2023/07/10 00:01:01 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
./var/ossec/logs/ossec.log:10:2023/07/10 00:01:01 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
./var/ossec/logs/ossec.log:11:2023/07/10 00:01:01 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml'

```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:75:2023/07/07 13:14:30 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:143:2023/07/07 13:14:36 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```


- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12808:2023/07/09 02:29:20 wazuh-agentd: WARNING: Server unavailable. Setting lock.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12811:2023/07/09 02:29:20 wazuh-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12812:2023/07/09 02:29:20 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12813:2023/07/09 02:29:20 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12814:2023/07/09 02:29:22 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12815:2023/07/09 02:29:22 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12816:2023/07/09 02:29:26 wazuh-logcollector: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12817:2023/07/09 02:29:31 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12819:2023/07/09 02:29:49 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
```

- Expected logs due to stress test:

```
./var/ossec/logs/ossec.log:19:2023/07/10 00:01:36 sca: WARNING: Interval overtaken.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12790:2023/07/09 02:28:26 wazuh-agentd: WARNING: Agent buffer at 90 %.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:12791:2023/07/09 02:28:26 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:18690:2023/07/07 21:17:47 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
```

</details>

<details>
<summary>Ubuntu Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:45:2023/07/07 13:15:12 wazuh-modulesd:ciscat: ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:77:2023/07/07 13:15:32 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:89:2023/07/09 00:05:00 wazuh-logcollector: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:90:2023/07/09 00:05:00 wazuh-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:91:2023/07/09 00:05:00 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:92:2023/07/09 00:05:00 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:96:2023/07/09 00:05:01 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:97:2023/07/09 00:05:22 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
```

- Expected logs due to stress test:

```
./var/ossec/logs/ossec.log:257:2023/07/10 00:28:21 sca: WARNING: Interval overtaken.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:3:2023/07/09 00:00:13 wazuh-agentd: WARNING: Agent buffer at 90 %.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:4:2023/07/09 00:00:13 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:28:2023/07/09 00:01:30 wazuh-syscheckd: WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:52:2023/07/09 00:02:53 wazuh-logcollector: WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files".

```


</details>

<details>
<summary>Windows Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./ossec.log:4:2023/07/10 00:23:40 wazuh-modulesd:ciscat: ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'.
./logs/2023/Jul/ossec-07.log:111:2023/07/07 13:17:44 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
./logs/2023/Jul/ossec-07.log:112:2023/07/07 13:17:44 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp\ciscat-report.xml': No such file or directory
./logs/2023/Jul/ossec-07.log:113:2023/07/07 13:17:44 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
```

- Related to:

```
./logs/2023/Jul/ossec-07.log:3:2023/07/07 13:16:34 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\wazuh-agent.exe' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:6:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:9:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libwinpthread-1.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:12:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\dbsync.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:15:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\rsync.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:18:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libstdc++-6.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:21:2023/07/07 13:16:35 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libwazuhext.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:24:2023/07/07 13:16:36 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\sysinfo.dll' is not signed or its signature is invalid.
```

- Expected logs due to stress test:

```
./ossec.log:6:2023/07/10 00:23:40 wazuh-modulesd:ciscat: WARNING: Interval overtaken.

```

</details>

**Comment by juliamagan** [comment]
## Analysis report: Graphs

- Manager:

  - Disk: high usage

- Centos Agent:

  - Disk: high usage
  - Disk_Read/Disk_Written/Read_Ops/Write_Ops: drop to zero
  - PSS: high
  - RSS_MAXMIN/RSS/USS: high

- Ubuntu Agent:

  - Disk: high usage
  - Disk_Read/Disk_Written: high
  - RSS_MAXMIN/RSS/USS: high for syscheck
  - Write_Ops: high 

- Windows Agent:

  - RSS_MAXMIN/RSS/USS/VMS: high
