### ISSUE TITLE
Testing 4.6.0 - Pre-Alpha 1 - Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (3.0d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17858]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #17713                                         |
| **Main footprint metrics issue #** | #17717                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | Pre-Alpha 1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/137/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/Test_stress_Vagrant_B137_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/plots/Test_stress_Vagrant_B137_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B137_manager_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/logs/ossec_Test_stress_Vagrant_B137_manager_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/data/monitor-manager-Test_stress_Vagrant_B137_manager-warehouse-test.csv)
[Test_stress_Vagrant_B137_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/data/Test_stress_Vagrant_B137_manager_analysisd_events.csv)
[Test_stress_Vagrant_B137_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/data/Test_stress_Vagrant_B137_manager_analysisd_state.csv)
[Test_stress_Vagrant_B137_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_manager_centos/data/Test_stress_Vagrant_B137_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/Test_stress_Vagrant_B137_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/Test_stress_Vagrant_B137_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/Test_stress_Vagrant_B137_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/plots/Test_stress_Vagrant_B137_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B137_macos_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/logs/ossec_Test_stress_Vagrant_B137_macos_agent_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/data/monitor-agent-Test_stress_Vagrant_B137_macos_agent-warehouse-test.csv)
[Test_stress_Vagrant_B137_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_macos/data/Test_stress_Vagrant_B137_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/Test_stress_Vagrant_B137_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/Test_stress_Vagrant_B137_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/Test_stress_Vagrant_B137_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/plots/Test_stress_Vagrant_B137_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B137_solaris_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/logs/ossec_Test_stress_Vagrant_B137_solaris_agent_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B137_solaris_agent-warehouse-test.csv)
[Test_stress_Vagrant_B137_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B137-4320m/B137_agent_solaris/data/Test_stress_Vagrant_B137_solaris_agent_agentd_state.csv)

    </details>

</details>

**Comment by roronoasins** [comment]
## Analysis report - Logs errors

> To make this check a bit lighter, I have created the initial script that collects logs matching the following patterns: `ERROR`, `WARN`, `FATAL`, `CRITICAL`

<details><summary><code>get_footprint_logs.py</code></summary>

```python
import re
import os
import gzip
import shutil


ERR_PATTERN = "ERROR"
WARN_PATTERN = "WARNING"
CRIT_PATTERN = "CRITICAL"
FATAL_PATTERN = "FATAL"
OUTPUT_DIR = 'footprint_output_logs'


def get_stress_test_dirs(root_dir='.'):
    footprint_dir_pattern = 'ossec_Test_stress_'
    footprint_dirs = []

    for filename in os.listdir(root_dir):
        if os.path.isdir(os.path.join(root_dir, filename)):
            if footprint_dir_pattern in filename:
                footprint_dirs += [filename]

    return footprint_dirs


def write_content(file_obj, content):
    file_obj.write(content)


def ignore_files(dir, files):
    # https://www.geeksforgeeks.org/python-copy-directory-structure-without-files/
    return [f for f in files if os.path.isfile(os.path.join(dir, f))]


def replicate_dir(src, dst):
    if os.path.exists(dst):
        shutil.rmtree(dst)
    # https://www.geeksforgeeks.org/python-copy-directory-structure-without-files/
    shutil.copytree(src, dst, ignore=ignore_files)


def unzip_gz(src):
    with open(src, 'rb') as input_file, open(f"{src[0:-3]}", 'w', encoding='utf8') as output:
        decom_str = gzip.decompress(input_file.read()).decode('utf-8')
        output.write(decom_str)


def unzip_log_files(dirs):
    # unzip first (os.walk won't be updated with the new files)
    for dir_to_check in dirs:
        for r, d, f in os.walk(dir_to_check):
            for filename in f:
                # unzip the compressed files
                if '.gz' in filename:
                    root_filename = os.path.join(r, filename)
                    print(f"unzip {root_filename}")
                    unzip_gz(root_filename)


def process_log_files(dirs):
    # process the log files within all the dirs
    for dir_to_check in dirs:
        print(f"Processing {dir_to_check} directory")
        ref = re.search(r"B(\d+)_(\S+)_", dir_to_check)
        build, component = ref.groups()
        # recreate dir to place the found logs
        new_dir_path = os.path.join(OUTPUT_DIR, f"footprint_logs_B{build}_{component}")
        replicate_dir(dir_to_check, new_dir_path)

        for r, d, f in os.walk(dir_to_check):
            for filename in f:
                # process the log files
                if ('.log' in filename or '.json' in filename) and '.gz' not in filename:
                    check_path = os.path.join(r, filename)
                    print(f"Checking {check_path} log file")
                    # check_path = f"{dir_to_check}/var/ossec/logs/ossec.log"
                    content_to_check = open(check_path, "r")
                    # content_matches = {}
                    for patrn_type in [ERR_PATTERN, WARN_PATTERN, CRIT_PATTERN, FATAL_PATTERN]:
                        log_write = None
                        file_with_no_extension = re.sub(r'\.[a-z]{3}', '', check_path)
                        output_path = re.sub(r'\S+\d+-\d+-\d+/', f"{new_dir_path}/",
                                             f"{file_with_no_extension}_{patrn_type}.log")

                        for line in content_to_check:
                            if re.search(patrn_type, line):
                                if log_write is None:
                                    log_write = open(output_path, "w+")
                                write_content(log_write, line)

                        if log_write is not None:
                            # close the file if the regex matched
                            log_write.close()

                        # restart the handler pos
                        content_to_check.seek(0)


def main():
    dirs = get_stress_test_dirs()
    unzip_log_files(dirs)
    process_log_files(dirs)


if __name__ == '__main__':
    main()

```

</details>

---

<details>
<summary>Manager</summary>
<br>


- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

    ```
    2023/07/07 14:16:29 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
    ```


- Related to https://github.com/wazuh/wazuh-jenkins/issues/5283:

    ```
    2023/07/07 14:05:50 wazuh-modulesd: WARNING: Ubuntu Precise is no longer supported.
    2023/07/07 14:05:50 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
    2023/07/07 14:05:50 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
    2023/07/07 14:05:50 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
    ```



- Related to https://github.com/wazuh/wazuh/issues/17596:

    ```
    2023/07/09 14:18:47 wazuh-remoted: WARNING: Too big message size from socket [14].
    ```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5284:

    ```
    2023/07/07 14:16:40 sca: WARNING: Interval overtaken.
    ```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

    ```
    2023/07/07 14:16:29 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
    ```

- Expected logs due to stress test:

    ```
    ./var/ossec/logs/ossec.log:439:2023/07/10 00:35:56 sca: WARNING: Interval overtaken.
    2023/07/07 17:19:34 wazuh-modulesd:azure-logs: WARNING: Interval overtaken.
    2023/07/07 14:05:32 wazuh-logcollector: WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
    ```


</details>

<details>
<summary>MacOS Agent</summary>
<br>


- Related to wazuh/wazuh-jenkins#4867:

    ```
    [2023-07-07_21:29:36] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
    2023/07/07 14:16:20 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.10.92]:1514/tcp': 'Connection refused'.
    2023/07/09 14:19:19 wazuh-agentd: WARNING: Server unavailable. Setting lock.
    ```

</details>

<details>
<summary>Solaris Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

    ```
    2023/07/07 14:16:13 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
    ```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

    ```
    2023/07/07 14:11:04 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
    2023/07/07 14:11:30 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
    ```

- Related to wazuh/wazuh-jenkins#4867:

    ```
    2023/07/07 14:16:12 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
    2023/07/07 14:16:12 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.10.92]:1514/tcp': 'Connection refused'.
    2023/07/07 14:16:22 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.10.92]:1514/tcp': 'Connection refused'.
    ```

- Not tracked:

    ```
    2023/07/07 14:11:25 wazuh-modulesd: ERROR: Child process 2450 not found.
    ```

</details>

**Comment by roronoasins** [comment]
## Analysis report: Graphs

- Manager:

  Disk: Higher in the beginning and lower then
  Disk_read: Higher
  PSS/RSS/RSS_MAXMIN: Higher

  > It has higher values when the Read|Written_Ops are equal

- MacOS Agent:

  - Agent_number_of_events_buffered: 3.0 peak 
  - AgentD_Status: tons of disconnections

- Solaris Agent:

  - CPU: Strange agentd peak
