### ISSUE TITLE
Testing 4.6.0 - Pre-Alpha 1 - Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (3.0d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17854]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #17713                                         |
| **Main footprint metrics issue #** | #17717                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | Pre-Alpha 1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/136/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/Test_stress_Vagrant_B136_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/plots/Test_stress_Vagrant_B136_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B136_manager_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/logs/ossec_Test_stress_Vagrant_B136_manager_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/data/monitor-manager-Test_stress_Vagrant_B136_manager-warehouse-test.csv)
[Test_stress_Vagrant_B136_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/data/Test_stress_Vagrant_B136_manager_analysisd_events.csv)
[Test_stress_Vagrant_B136_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/data/Test_stress_Vagrant_B136_manager_analysisd_state.csv)
[Test_stress_Vagrant_B136_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_manager_centos/data/Test_stress_Vagrant_B136_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/Test_stress_Vagrant_B136_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/Test_stress_Vagrant_B136_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/Test_stress_Vagrant_B136_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/plots/Test_stress_Vagrant_B136_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B136_macos_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/logs/ossec_Test_stress_Vagrant_B136_macos_agent_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/data/monitor-agent-Test_stress_Vagrant_B136_macos_agent-warehouse-test.csv)
[Test_stress_Vagrant_B136_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_macos/data/Test_stress_Vagrant_B136_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/Test_stress_Vagrant_B136_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/Test_stress_Vagrant_B136_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/Test_stress_Vagrant_B136_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/plots/Test_stress_Vagrant_B136_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B136_solaris_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/logs/ossec_Test_stress_Vagrant_B136_solaris_agent_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B136_solaris_agent-warehouse-test.csv)
[Test_stress_Vagrant_B136_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/warehouse-test/4.6.0/B136-4320m/B136_agent_solaris/data/Test_stress_Vagrant_B136_solaris_agent_agentd_state.csv)

    </details>

</details>

**Comment by juliamagan** [comment]
## Analysis report - Logs errors

<details>
<summary>Manager</summary>
<br>


- Related to https://github.com/wazuh/wazuh-jenkins/issues/5283:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:70:2023/07/07 13:25:47 wazuh-modulesd: WARNING: Ubuntu Precise is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:71:2023/07/07 13:25:47 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:72:2023/07/07 13:25:47 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:73:2023/07/07 13:25:47 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:185:2023/07/07 13:36:35 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and wazuh/wazuh#9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:188:2023/07/07 13:36:35 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5287:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:2073:2023/07/09 00:39:17 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir1528': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:2074:2023/07/09 00:39:17 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir1754': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:2075:2023/07/09 00:39:17 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir2034': No such file or directory
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:2076:2023/07/09 00:39:17 wazuh-syscheckd: WARNING: (6922): Cannot open '/tmp/syscheck_test/directories/dir2347': No such file or directory
```

- Expected logs due to stress test:

```
./var/ossec/logs/ossec.log:13:2023/07/10 00:00:26 sca: WARNING: Interval overtaken.
./var/ossec/logs/ossec.log:11012:2023/07/10 03:39:17 wazuh-modulesd:azure-logs: WARNING: Interval overtaken.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:69:2023/07/07 13:25:31 wazuh-logcollector: WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:214:2023/07/07 13:37:06 wazuh-remoted: WARNING: Message queue is full (10). Events may be lost.
```


</details>

<details>
<summary>macOS Agent</summary>
<br>

- Expected log because `/var/ossec` doesn't exist in macOS:

```
./tmp/syscheck_test/fim.log:76:[2023-07-07_20:53:20] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./Library/Ossec/logs/wazuh/2023/Jul/ossec-07.log:51:2023/07/07 13:36:27 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.1.147]:1514/tcp': 'Connection refused'.
```


</details>

<details>
<summary>Solaris Agent</summary>
<br>



- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:122:2023/07/07 13:36:19 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:125:2023/07/07 13:36:19 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.1.147]:1514/tcp': 'Connection refused'.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:126:2023/07/07 13:36:20 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:129:2023/07/07 13:36:28 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:131:2023/07/07 13:36:29 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.1.147]:1514/tcp': 'Connection refused'.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:38:2023/07/07 13:30:59 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:104:2023/07/07 13:31:24 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
```




</details>

**Comment by juliamagan** [comment]
## Analysis report: Graphs

- Manager:

  - Disk_Read: high
  - PSS/RSS_MAXMIN/RSS/USS: high for analysisd

- macOS Agent:

  - FD: high for analysisd
  - AgentD_Number_of_events_buffered: high

- Solaris Agent:

  - AgentD_Number_of_events_buffered: none
