### ISSUE TITLE
Testing 4.6.0 - Pre-Alpha 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (3.0d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#17855]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #17713                                         |
| **Main footprint metrics issue #** | #17717                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | Pre-Alpha 1                                        |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4144/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/monitor-manager-Test_stress_B4144_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/plots/Test_stress_B4144_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4144_manager_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/logs/ossec_Test_stress_B4144_manager_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4144_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/data/monitor-manager-Test_stress_B4144_manager-warehouse-test.csv)
[Test_stress_B4144_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/data/Test_stress_B4144_manager_analysisd_events.csv)
[Test_stress_B4144_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/data/Test_stress_B4144_manager_analysisd_state.csv)
[Test_stress_B4144_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_manager_centos/data/Test_stress_B4144_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/monitor-agent-Test_stress_B4144_centos-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/Test_stress_B4144_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/Test_stress_B4144_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/Test_stress_B4144_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/plots/Test_stress_B4144_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4144_centos_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/logs/ossec_Test_stress_B4144_centos_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4144_centos-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/data/monitor-agent-Test_stress_B4144_centos-warehouse-test.csv)
[Test_stress_B4144_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_centos/data/Test_stress_B4144_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/Test_stress_B4144_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/Test_stress_B4144_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/Test_stress_B4144_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/plots/Test_stress_B4144_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4144_ubuntu_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/logs/ossec_Test_stress_B4144_ubuntu_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4144_ubuntu-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/data/monitor-agent-Test_stress_B4144_ubuntu-warehouse-test.csv)
[Test_stress_B4144_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_ubuntu/data/Test_stress_B4144_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/monitor-winagent-Test_stress_B4144_windows-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/Test_stress_B4144_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/Test_stress_B4144_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/Test_stress_B4144_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/plots/Test_stress_B4144_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4144_windows_2023-07-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/logs/ossec_Test_stress_B4144_windows_2023-07-10.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4144_windows-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/data/monitor-winagent-Test_stress_B4144_windows-warehouse-test.csv)
[Test_stress_B4144_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4144-4320m/B4144_agent_windows/data/Test_stress_B4144_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

**Comment by juliamagan** [comment]
## Analysis report - Logs errors

<details>
<summary>Manager</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:152:2023/07/07 14:00:01 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:154:2023/07/07 14:00:01 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5283:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:71:2023/07/07 13:57:20 wazuh-modulesd: WARNING: Ubuntu Precise is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:72:2023/07/07 13:57:20 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:73:2023/07/07 13:57:20 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:74:2023/07/07 13:57:20 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5284:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:166:2023/07/07 14:00:46 wazuh-remoted: WARNING: Agent key already in use: agent ID '003'
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:169:2023/07/07 14:00:46 wazuh-authd: WARNING: Duplicate name 'EC2AMAZ-L273KKC', rejecting enrollment. Agent '003' key already exists on the manager.
```


- Expected logs due to stress test:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:5150:2023/07/09 12:08:08 wazuh-modulesd:azure-logs: WARNING: Interval overtaken.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:3243:2023/07/07 21:13:04 wazuh-remoted: WARNING: Message queue is full (10). Events may be lost.
```


</details>

<details>
<summary>CentOS Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/ossec.log:3:2023/07/10 00:00:19 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
./var/ossec/logs/ossec.log:4:2023/07/10 00:00:19 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
./var/ossec/logs/ossec.log:5:2023/07/10 00:00:19 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml'
./var/ossec/logs/ossec.log:6:2023/07/10 00:00:24 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
./var/ossec/logs/ossec.log:7:2023/07/10 00:00:24 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
./var/ossec/logs/ossec.log:8:2023/07/10 00:00:24 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml'
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:74:2023/07/07 13:58:17 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```


- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:92:2023/07/07 13:59:44 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:95:2023/07/07 13:59:44 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.3.7]:1514/tcp': 'Connection refused'.
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:96:2023/07/07 13:59:45 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:98:2023/07/07 13:59:54 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.3.7]:1514/tcp': 'Connection refused'.
```

- Expected logs due to stress test:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-09.log:26:2023/07/09 00:03:04 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
```

</details>

<details>
<summary>Ubuntu Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:21:2023/07/07 13:59:35 wazuh-modulesd:ciscat: ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/5399 and https://github.com/wazuh/wazuh/issues/9311:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:78:2023/07/07 14:00:08 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-07.log:36:2023/07/07 13:59:52 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.3.7]:1514/tcp': 'Connection refused'.
```

- Expected logs due to stress test:

```
./var/ossec/logs/wazuh/2023/Jul/ossec-08.log:4:2023/07/08 00:01:12 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
```


</details>

<details>
<summary>Windows Agent</summary>
<br>

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4469:

```
./logs/2023/Jul/ossec-07.log:892:2023/07/07 16:05:59 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
./logs/2023/Jul/ossec-07.log:893:2023/07/07 16:05:59 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp\ciscat-report.xml': No such file or directory
./logs/2023/Jul/ossec-07.log:894:2023/07/07 16:05:59 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
./logs/2023/Jul/ossec-07.log:998:2023/07/07 23:36:55 wazuh-modulesd:ciscat: ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'.
```

- Related to https://github.com/wazuh/wazuh-jenkins/issues/4867:

```
./logs/2023/Jul/ossec-07.log:36:2023/07/07 13:59:27 wazuh-agent: ERROR: SSL read (unable to receive message)
./logs/2023/Jul/ossec-07.log:37:2023/07/07 13:59:27 wazuh-agent: ERROR: If Agent verification is enabled, agent key and certificates may be incorrect!
./logs/2023/Jul/ossec-07.log:47:2023/07/07 13:59:53 wazuh-agent: ERROR: (1216): Unable to connect to '[172.31.3.7]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
./logs/2023/Jul/ossec-07.log:110:2023/07/07 14:00:45 wazuh-agent: ERROR: Duplicate agent name: EC2AMAZ-L273KKC (from manager)
./logs/2023/Jul/ossec-07.log:111:2023/07/07 14:00:45 wazuh-agent: ERROR: Unable to add agent (from manager)
./logs/2023/Jul/ossec-07.log:112:2023/07/07 14:00:55 wazuh-agent: WARNING: (4101): Waiting for server reply (not started). Tried: '172.31.3.7'.
./logs/2023/Jul/ossec-07.log:113:2023/07/07 14:00:55 wazuh-agent: WARNING: Unable to connect to any server.
```

- Expected logs because warehouse-test packages are not signed:

```
./logs/2023/Jul/ossec-07.log:3:2023/07/07 13:59:22 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\wazuh-agent.exe' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:6:2023/07/07 13:59:23 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libgcc_s_dw2-1.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:9:2023/07/07 13:59:24 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libwinpthread-1.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:12:2023/07/07 13:59:24 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\dbsync.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:15:2023/07/07 13:59:24 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\rsync.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:18:2023/07/07 13:59:25 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libstdc++-6.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:21:2023/07/07 13:59:25 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\libwazuhext.dll' is not signed or its signature is invalid.
./logs/2023/Jul/ossec-07.log:24:2023/07/07 13:59:25 wazuh-agent: WARNING: The file 'C:\Program Files (x86)\ossec-agent\sysinfo.dll' is not signed or its signature is invalid.
```

- Expected logs due to stress test:

```
./logs/2023/Jul/ossec-07.log:1000:2023/07/07 23:36:55 wazuh-modulesd:ciscat: WARNING: Interval overtaken.

```

</details>
