### ISSUE TITLE
Uploading decoder/rule xml file with no child elements breaks analysisd

### ISSUE THREAD

**Issue by leba-atr** [wazuh/wazuh#17862]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4 | analysisd | Manager | official docker images | n/a |

While I was playing around with the API, I tried uploading an empty XML file as a decoder definition[1] because I didn't have a valid decoder definition at hand which I could use (the exact same also happened with rules files). The API didn't let me do that so I added a comment to the file for it not being empty anymore (`<!-- no content -->`). The API then let my request pass and wrote the file to its destined path on disk. However, after restarting my Docker containers, I noticed that I could not longer use the Wazuh Kibana app because it reported that the API was offline. Inspecting the logs of the manager container, I noticed that the analysisd reported critical errors because of invalid XML files:
```
2023/07/10 14:49:58 wazuh-analysisd: ERROR: (1231): Invalid NULL element in the configuration.
2023/07/10 14:49:58 wazuh-analysisd: CRITICAL: (1202): Configuration error at 'etc/decoders/1000_mydecoders.xml'.
```
Removing the file made analysisd return to normal operation. I see this issue having two reasons: 
* the API doesn't seem to validate XML files the same way analysisd does. This creates a gap which leads to users being able to submit XML files via the API that are invalid to analysisd. 
* analysisd should not completely cease to work if it encounters a custom rules file or a custom decoders file that contains invalid XML. Rather, it should only print a warning/an error and continue by ignoring the broken file(s). 

This issue is not blocking to me since I was able to recover by removing the invalid files. Yet, I'd like to bring this to your attention since similar inconsistencies may be present at more critical parts of the API/configuration (e.g. allowing a user to create and deploy broken agent configs).

[1] `PUT /decoders/files/{filename}` and `PUT /rules/files/{filename}`

**Comment by vikman90** [comment]
Hi @leba-atr,

I've managed to reproduce this issue using the API directly:

```shell
curl -sk \
-H "Authorization: Bearer $TOKEN" \
-X PUT \
https://localhost:55000/rules/files/local_rules.xml?overwrite=true \
--header "Content-Type: application/octet-stream" \
--data "Oops"
```

Result:
```json
{"data": {"affected_items": ["etc/rules/local_rules.xml"], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Rule was successfully uploaded", "error": 0}
```

However, if we run the _wazuh-analysisd_ configuration test, we get:
```shell
/var/ossec/bin/wazuh-analysisd -t
```

```
2023/09/11 08:46:48 wazuh-analysisd: ERROR: (1202): Configuration error at 'etc/rules/local_rules.xml'.
2023/09/11 08:46:48 wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
```

Let me assign this issue as a bug to the @wazuh/framework to check and fix it.

### Proposals

- Improve the XML validation to match the Wazuh internal XML validator: the file must contain one root item at less.
- Run `wazuh-analysisd -t` to validate the user's input.
- Try a dummy log with Logtest.

Thank you very much for reporting this issue.
Best!

**Comment by Selutario** [comment]
@vikman90 Currently, when updating the configuration in `ossec.conf`, the API verifies whether the settings are valid by sending a `check-manager-configuration` command to `queue/sockets/com`. 

Would it be possible to do something similar for rules and decoders? It doesn't make sense for the API to validate whether a rules file is correct, plus the quirks of wazuh XML files force poor quality code to be included in the framework:
https://github.com/wazuh/wazuh/blob/17469f88206a90e54e0d5f6ee81a0a04996ada1f/framework/wazuh/core/utils.py#L1945-L1992

In my opinion, analysisd should offer a way for the API to confirm if the file is valid through a socket instead of running a `wazuh-analysisd -t` command.

**Comment by vikman90** [comment]
@Selutario sure you can! Third option: _Try a dummy log with Logtest._

- Socket: _/var/ossec/queue/sockets/logtest_
- Input:
```json
{ "command": "log_processing", "parameters": { "location": "dummy", "log_format": "syslog", "event": "Hello" } }
```
- Output (OK):
```json
{"error":0,"data":{"messages":["INFO: (7202): Session initialized with token 'ed100a0d'"],"token":"ed100a0d","output":{"timestamp":"2023-09-14T12:24:57.494+0200","agent":{"id":"000","name":"Rocket"},"manager":{"name":"Rocket"},"id":"1694687097.0","full_log":"Hello","decoder":{},"location":"dummy"},"alert":false,"codemsg":0}}
```
- Output (fail):
```json
{"error":0,"data":{"messages":["ERROR: (1226): Error reading XML file 'etc/decoders/local_decoder.xml': XMLERR: Syntax error: 'O' (line 1).","ERROR: (7311): Failure to initializing session"],"codemsg":-1}}
```

**Comment by RamosFe** [comment]
## Update

I continue with the development of the unit tests and integration tests for the changes of PUT `/decoders/files/{filename}` and PUT `/rules/files/{filename}`.

**Comment by RamosFe** [comment]
## Update

After the changes, an error arises when passing an invalid XML file:

`PUT /decoders/files/{filename}`:
```
curl -sk -H "Authorization: Bearer $TOKEN" -X PUT https://localhost:55050/rules/files/local_rules.xml?overwrite=true --header "Content-Type: application/octet-stream" --data "Oops" -v
*   Trying 127.0.0.1:55050...
* Connected to localhost (127.0.0.1) port 55050 (#0)
.....
.....
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1113, "message": "XML syntax error", "remediation": "Please, ensure file content has correct XML"}, "id": ["etc/rules/local_rules.xml"]}]}, "message": "Could not upload rule", "error": 1}
```

`PUT /rules/files/{filename}`
```
curl -sk -H "Authorization: Bearer $TOKEN" -X PUT https://localhost:55050/decoders/files/local_decoders.xml?overwrite=true --header "Content-Type: application/octet-stream" --data "Oops" -v
....
....
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1113, "message": "XML syntax error", "remediation": "Please, ensure file content has correct XML"}, "id": ["etc/decoders/local_decoders.xml"]}]}, "message": "Could not upload decoder", "error": 1}
```

**Comment by leba-atr** [comment]
What happens if you use this command: `curl -sk -H "Authorization: Bearer $TOKEN" -X PUT https://localhost:55050/decoders/files/local_decoders.xml?overwrite=true --header "Content-Type: application/octet-stream" --data "<!-- comment -->" -v`

**Comment by RamosFe** [comment]
@leba-atr 

```
export TOKEN="eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAxMzUxNjI0LCJleHAiOjE3MDEzNTI1MjQsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AYoONb9r40BVNJNJj4321bWC0ksKiBcyY6R8ZpSqZzqI2mRYUuANln4dugsCHqZQUh_-h2k4uj0zebkKOkeMjHo0AKr0CpFKFz7hdPxcxvZ6Doj2dWqKnj3-NB9df6sxi_QTaebg2F9q_3XPYwQkMH_UJ-MYF9ljjdytSZag5Cfhugvt"
federamos@pop-os:~/Documents/Wazuh/Containers/dev$ curl -sk -H "Authorization: Bearer $TOKEN" -X PUT https://localhost:55050/decoders/files/local_decoders.xml?overwrite=true --header "Content-Type: application/octet-stream" --data '<!-- comment -->' -v
*   Trying 127.0.0.1:55050...
* Connected to localhost (127.0.0.1) port 55050 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Wazuh; CN=wazuh.com
*  start date: Nov 30 13:15:52 2023 GMT
*  expire date: Nov 29 13:15:52 2024 GMT
*  issuer: C=US; ST=California; L=San Francisco; O=Wazuh; CN=wazuh.com
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> PUT /decoders/files/local_decoders.xml?overwrite=true HTTP/1.1
> Host: localhost:55050
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer eyJhbGciOiJFUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNzAxMzUxNjI0LCJleHAiOjE3MDEzNTI1MjQsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.AYoONb9r40BVNJNJj4321bWC0ksKiBcyY6R8ZpSqZzqI2mRYUuANln4dugsCHqZQUh_-h2k4uj0zebkKOkeMjHo0AKr0CpFKFz7hdPxcxvZ6Doj2dWqKnj3-NB9df6sxi_QTaebg2F9q_3XPYwQkMH_UJ-MYF9ljjdytSZag5Cfhugvt
> Content-Type: application/octet-stream
> Content-Length: 16
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Strict-Transport-Security: max-age=63072000; includeSubdomains
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Security-Policy: none
< Referrer-Policy: no-referrer, strict-origin-when-cross-origin
< Pragma: no-cache
< Expires: 0
< Cache-control: no-cache, no-store, must-revalidate, max-age=0
< Content-Length: 316
< Date: Thu, 30 Nov 2023 13:40:38 GMT
< 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host localhost left intact
{"data": {"affected_items": [], "total_affected_items": 0, "total_failed_items": 1, "failed_items": [{"error": {"code": 1113, "message": "XML syntax error", "remediation": "Please, ensure file content has correct XML"}, "id": ["etc/decoders/local_decoders.xml"]}]}, "message": "Could not upload decoder", "error"
```

**Comment by RamosFe** [comment]
Thank you for reporting the Issue @leba-atr , any other evidence/case you have is more than welcome. Thank you very much!
