### ISSUE TITLE
3.7 multigroup reassignation 

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1787]
## Bug report

**OS**
_Ubuntu16/CentOS7/RHEL7/AIX.._

**Wazuh version**
_3.7.0-13_

**Wazuh API version**
_3.7.0_

**Install type**
_manager/agent_

**Install method**
_packages/sources_

**Log sample**

```
Log sample
```

Bug description
----------------

Lets say we have 1 agent with the following groups:
- default,group1,group2

So the **/var/ossec/var/multigroups/.metadata** file content is:
default,group1,group2

When we register the agent to reassign a new ID the multigroup default,group1,group2 will be deleted because no more agents are using this. The new group assigned to the new ID will be NULL.

We have two options to fix the issue:
### Option 1:
- If it its a forced registration with new ID, tell the **OS_RemoveAgentGroup** function not to remove the multigroup.

### Option 2:
- Make a new internal_options variable to refresh the multigroup metadata file every X seconds.

**Comment by chemamartinez** [comment]
This issue is outdated, the `.metadata` file no longer exists since #1863.
