### ISSUE TITLE
Engine - KVDB Pagination

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#17877]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

The KVDB Engine's module allows massive storage of data into persistent databases using RocksDB.
Any Module of the Engine is able to store data into this storage, like Decoders, Rules, and so on. 

This means that KVDBs can potentially contain a large number of records. Additionally, the Engine provides a Command Line Interface to operate with the KVDB Module. Within these capabilities, we can obtain a dump of all the data in a KVDB.

Here we have the maximum transfer limits of our API to retrieve responses from the server, and in the opposite direction, we have the limit of the shell in the terminal to ingest parameters to the API.

That is why we need the ability to obtain an extensive listing based on the content of a KVDB, which, while respecting the transfer limits of our API, is also capable of keeping the output of the CLI dump command transparent.

## Goal

Improve KVDB Module and KVDB CLI Handler to support segmented transfers as response. This is also called Pagination. Even though this remains transparent to the user, we need a way to retrieve data from the server by pages.

## Considerations

1. In a first iteration, the use of explicit snapshots to obtain data from the DB will not be contemplated.
2. The data obtained from the DB is arranged in alphanumeric form, therefore it is possible that there are modifications in the results of each page. For example, if keys are inserted or deleted.

## DoD
 - [x] Initial Research and first Approach
 - [x] Modify KVDB Module
 - [x] Modify KVDB CLI Handler
 - [x] Check Clang format.
 - [x] Unit test 
     - [x] Create API tests
     - [x] Verify ctest can be run with multiple jobs. i.e. ctest -j4.
 - [x] Memory leak analysis.
     - [x] Valgrind.
 - [x] Documentation update.
    - [x] [Design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit#)
    - [x] [User manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit)

**Comment by JorgeMarinoDev** [comment]
Initial research. Work in progress. 
[initial research doc](https://docs.google.com/document/d/1xdbsb8I62gsc-rAorBKRaLlMY9G1NoJm8HQM_gNrYF8/edit#heading=h.5thac28dqf55)
