### ISSUE TITLE
Create a Flatbuffer Schema Compatible with CVE5 JSON Schema

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17874]
|Part of Epic| Branch |
|---|---|
|#14153|[dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor)|

### Description

This issue involves creating a Flatbuffer schema that is compatible with the proposed schema in CVE5, which is in JSON format. The goal is to define a Flatbuffer schema that can efficiently represent the data structure described in the CVE5 JSON schema.

### Proposed Solution

The proposed solution is to design and implement a Flatbuffer schema that mirrors the structure and fields of the CVE5 JSON schema. This may require mapping the JSON schema's properties, types, and relationships to the corresponding Flatbuffer definitions. Care should be taken to ensure compatibility and efficient representation of the data.

### Expected Outcome

The expected outcome of this issue is to have a Flatbuffer schema that accurately represents the structure and fields of the CVE5 JSON schema. With this schema in place, the project will be able to efficiently handle and process data following the CVE5 schema.

### DoD

- [x] Analyze the CVE5 JSON schema and identify its structure, properties, and relationships.
- [x] Design a Flatbuffer schema that closely matches the structure and fields of the CVE5 JSON schema.
- [x] Implement the Flatbuffer schema definitions based on the analysis.
- [x] Test the Flatbuffer schema with sample data to ensure compatibility and efficient representation.

Create a folder named schemas in https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner, and develop the schema inner this folder.

**Comment by sebasfalcone** [comment]
## Updates
Is possible to implement the CVEv5 schema as a flatbuffer schema. 

For our use case, we will avoid representing the ["REJECTED" entry types](https://cveproject.github.io/cve-schema/schema/v5.0/docs/#tab-pane_oneOf_i1)

**Comment by sebasfalcone** [comment]
## Now
Testing the generated schema against real data to better understand the json to flatbuffer mapping process

**Comment by sebasfalcone** [comment]
A big constraint of the flatbuffer is that the schema must match exactly each key of the JSON object. This could be a problem if we are using fields that allow regex patterns or custom formatting of the CVEv5 format

For example, for the MSU and alpine feeds, we use the following field
![image](https://github.com/wazuh/wazuh/assets/34063881/2e1eed5c-9ef7-486c-8f6f-5d7e0c3e8ae8)

We must define a schema for this and follow it because it will break the flatbuffer serialization

**Comment by sebasfalcone** [comment]
The conversion from flatbuffer to JSON removes the quotes from the keys:
```json
          }
        },
        {
          format: "CVSS",
          cvssV2_0: {
            version: "2.0",
            vectorString: "AV:N/AC:M/Au:S/C:N/I:P/A:N",
            accessVector: "NETWORK",
            accessComplexity: "MEDIUM",
            authentication: "SINGLE",
            confidentialityImpact: "NONE",
            integrityImpact: "PARTIAL",
            availabilityImpact: "NONE",
            baseScore: 3.5
          }
        }
      ],
      x_remediations: {
        windows: [
```

There is an option on the schema generation tool to force the quotes but I'am not being able to enable it. I will keep investigating it

**Comment by sebasfalcone** [comment]
> **Warning**
By default, the JSON parser provided by the flatbuffers doesn't add the quotes on the keys.

> **Note**
To fix this we must set the strict_json flag on the IDLOptions:
```C++
  flatbuffers::IDLOptions options;
  options.strict_json = true;  // Force quotes on the JSON keys
  
  flatbuffers::Parser parser(options);
```

**Comment by sebasfalcone** [comment]
## Performance

- flatbuffer to JSON (500.000 times):
```
🍄 time ./flatsampletext 500000 samples/cvedata.json 

The FlatBuffer has been parsed from JSON successfully

real	1m5.645s
user	1m5.505s
sys	0m0.042s
```

- JSON to flatbuffer (500.000 times):
```
🍄 time ./flatsampletext 500000 samples/cvedata.json 

The FlatBuffer has been parsed from JSON successfully

real	9m32.239s
user	9m31.735s
sys	0m0.246s
```
