### ISSUE TITLE
Regenerating cURL Precompiled Binaries on macOS from Dependencies v22

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17888]
### Description

This issue involves regenerating the precompiled binaries of cURL on macOS based on the dependencies version 22. 

### Proposed Solution

The proposed solution is to regenerate the cURL precompiled binaries on macOS using the updated dependencies version 22. This process may involve rebuilding cURL from source code, ensuring the correct versions of the dependencies are used, and resolving any compatibility issues that may arise during the build process.

### Tasks

- Identify the current version of cURL and the dependencies used in the precompiled binaries.
- Rebuild cURL from source code, using the updated dependencies.
- Test the regenerated cURL binaries to ensure proper functionality.
- Upload to packages.wazuh.com

### Expected Outcome

After regenerating the cURL precompiled binaries on macOS using dependencies version 22, the project should benefit on building/compilation time.

**Comment by TomasTurina** [comment]
New dependency uploaded in. https://drive.google.com/drive/u/1/folders/1BBijRska3ycfkXIYDvB5Kb6VO50cT62W.

**Comment by TomasTurina** [comment]
Solved after copying latest deps from 21 to 22.
