### ISSUE TITLE
SCA check 27313 CIS Microsoft Windows Server 2022 Benchmark v1.0.0 is using wrong reg key value

### ISSUE THREAD

**Issue by oleKHard** [wazuh/wazuh#17898]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.* | SCA | Agent | cis_win2022.yml | Windows Server 2022 |

Ensure 'Do not use temporary folders per session' is set to 'Disabled'.

Wazuh evaluates this condition:
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services -> PerSessionTempDir -> 0

which is the reg key for "Enabled" (https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.TerminalServer::TS_TEMP_PER_SESSION)

Should be:
r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services -> PerSessionTempDir -> 1

**Comment by vikman90** [comment]
@oleKHard Thank you very much for reporting this problem. That seems to be a typo as it has the correct value in other checks.

I've just created a PR to fix it: #17940.

Thanks!!

**Comment by vikman90** [comment]
HI @oleKHard. I've just merged the PR with the fix. Thank you again!
