### ISSUE TITLE
Define all vulnerability detector scan triggers

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#17901]
### Description

This issue focuses on defining the scan triggers for the vulnerability scanner module. The scanner should be able to initiate scans based on various events and requests, ensuring comprehensive and timely vulnerability assessment. The identified scan triggers include the following:

1. DBSync Events.

2. Wazuh RSync Events.

3. On-Demand Requests.

4. Missed Events Detection.

### Expected

The expected outcome of this issue is a clear definition and implementation plan for the scan triggers in the vulnerability scanner module. The scanner should be able to effectively identify and respond to the specified triggers, ensuring comprehensive vulnerability assessment and timely detection of potential vulnerabilities.

### Definition of Done

- [x] Define the scan triggers based on the identified events and requests.
- [x] Determine the criteria and conditions for initiating scans for each trigger.

**Comment by pereyra-m** [comment]
## Update

During the analysis of the issue #21446, it was defined that Wazuh-DB must report the upgrade of an agent DB as another event. The initial and final schema versions should be present in the message.

**Comment by pereyra-m** [comment]
## Update

The update of content should also trigger a re-scan of all the packages listed in the CVEs that changed.

**Comment by Dwordcito** [comment]
# Windows Vulnerabilities trigger
## First scan
The first scan is triggered when the hotfixes table is fully synced. To realize that we need all information about hotfixes to avoid false positives for a missing hotfix. To check that we need a column family to maintain the agent with the first scan completed.
After that, we need a query to WDB to check if the hotfix information has all the data synced, and if the information is available, then scan the agent with the OS information.
If the information is not synced, move this scan to the delayed scans.



```mermaid
sequenceDiagram
    Participant Remoted
    Participant SyncDispatcher
    Participant Inventory
    Participant OsScanner
    Participant WDB
    
    
    Remoted->>SyncDispatcher: Os Information sync
    SyncDispatcher->>Inventory: Have initial scan?
    alt exist
        Inventory-->>SyncDispatcher: Return agent data
    else not exist
        SyncDispatcher->>OsScanner: Trigger agent scan
        OsScanner->>WDB: Get hotfix data
        WDB-->>OsScanner: Return status or data
        alt status is synced
            OsScanner->>OsScanner: Scan agent
            OsScanner->>Inventory: Add scanner as scanned
        else status not synced
            OsScanner->>OsScanner: Move this scanner to the delayed list
        end
        OsScanner-->>SyncDispatcher: Return 
    end

```
