### ISSUE TITLE
SCA API integration test failing

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#17919]
## Description

The `test_sca_endpoints.tavern.yaml` API integration test is failing in the branches `4.5.1`, `4.6.0` and `master`.

The failed stages are:

- `GET /sca/{agent_id} for agents with Wazuh version >=4.2.0 (001) and <4.2.0 (006)`
- `GET /sca/{agent_id}/checks/{policy_id}`

The output indicates that the error is thrown when parsing the `sca_policy_id` value from the endpoint response that has the value `None`

```console
to_format = '{protocol:s}://{host:s}:{port:d}/sca/001/checks/{sca_policy_id:s}'
box_vars = <Box: {'protocol': 'https', 'host': 'localhost', 'port': 55000, 'user': 'testing', 
'user_auth_context': 'wazuh-wui', 
'...checks/{policy_id} using select and select + distinct (parametrized)[compliance.key] (call)'}}, 
> 'sca_policy_id': None}>

        ...

>       return to_format.format(**box_vars)
E       TypeError: unsupported format string passed to NoneType.__format__

../../../venv/lib/python3.9/site-packages/tavern/util/dict_util.py:52: TypeError
------------------------------ Captured log call -------------------------------
WARNING  tavern.util.dict_util:dict_util.py:46 Formatting 'sca_policy_id' will result in it being coerced to
a string (it is a <class 'NoneType'>)
```

https://github.com/wazuh/wazuh/blob/3030dc726fb8e3feb620b353bf9c9283ceb33fee/api/test/integration/test_sca_endpoints.tavern.yaml#L503-L514

Artifacts:  [Test_integration_endpoints_B3514_test_sca_endpoints.zip](https://github.com/wazuh/wazuh/files/12040114/Test_integration_endpoints_B3514_test_sca_endpoints.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Update

It seems that some of the Ubuntu 20.04 policies are missing content in the `rules` field:
https://github.com/wazuh/wazuh/blob/4ca53de691d9c52b058c04175820a8fc3d3e036d/ruleset/sca/ubuntu/cis_ubuntu20-04.yml#L4793-L4814

As a consequence, those checks are being skipped and no data is available in the API:
```
2023/07/14 11:01:46 sca[89] wm_sca.c:604 at wm_sca_check_policy(): DEBUG: Field 'regex_type' not found in policy header. The OS_REGEX engine shall be used.
2023/07/14 11:01:46 sca[89] wm_sca.c:715 at wm_sca_check_policy(): WARNING: Invalid check 31260: no rules found.
2023/07/14 11:01:46 sca[89] wm_sca.c:397 at wm_sca_read_files(): WARNING: Error found while validating policy file: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'. Skipping it.
```

We can rule out problems in the API or in the tests themself, but I'll keep this issue open until the policies are fixed to confirm whether anything else is required in the tests.

**Comment by IsExec** [comment]
https://github.com/wazuh/wazuh/issues/17919#issuecomment-1635722955 - Solved

https://github.com/wazuh/wazuh/pull/17926

**Comment by Selutario** [comment]
Fixed
