### ISSUE TITLE
Not expected Windows error in Footprint metrics

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#17929]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-40600 | wazuh-logcollector | Agent | Packages | Windows |

During the analysis of the footprint test for 4.6.0 Pre-Alpha 1, we could see that in the [ALL](https://github.com/wazuh/wazuh/issues/17856) test, appear a not expected error log for Windows:

- `logcollectorError.log`

    ```
    [2023-07-09_06:58:51] [ERROR] (write_logs): flood-29-95.log file cannot be deleted.
    ```

We should research this log so we can identify the reason behind it.

**Comment by MarcelKemp** [comment]
### Research

This error is a known issue for Windows agents, which has occurred in previous releases, as shown below:
- https://github.com/wazuh/wazuh/issues/15922#issuecomment-1386273542
- https://github.com/wazuh/wazuh/issues/15917#issuecomment-1386276023
- https://github.com/wazuh/wazuh/issues/11690#issuecomment-1004276451
- There are many more issues...

### Description

This error is a problem with the script that runs the stress test in the _wazuh-jenkins_ repository.

Specifically, the error is found here:
- https://github.com/wazuh/wazuh-jenkins/blob/1f8d4a1b766e92f0e50f9588967e6cfa74468d90/quality/tests/stress/scripts/logcollector.py#L68-L79

And it seems to be a race condition where it tries to delete the file, but can't delete it because it is open by some process (or some similar problem), causing the failure and with it the exception.

#### Related issue
- https://github.com/wazuh/wazuh-jenkins/issues/5287

**Comment by vikman90** [comment]
Thanks @MarcelKemp. It is clear that this is not a new problem in 4.6.0. I'd like to take care of that though, as we don't expect the agent to prevent an outsider from deleting your files.

**Comment by Leoquicenoz** [comment]
Trying to minimize the occurrence of the `[ERROR]: file cannot be deleted` that appears during the analysis of the footprint test, a modification is made in the code to increase the number of times this situation should occur so that the ERROR message is displayed as shown below:

```python
max_attempts = 3

for i in range(0, create_limit):
      file_name = "date-{0}-{1}-{2}.log".format(current_date, iteration, i)
      if os.path.isfile(file_name):
        attempts = 0
        while attempts < max_attempts:
          try:
            os.remove(file_name)
            break
          except Exception as exception:
            attempts += 1
            if attempts == max_attempts:
                lh.write(error_log, strings['common']['delete_error'], (th.date_time(), name, file_name))
            else:
                time.sleep(sleep_rm / 1000)
      else:
        lh.write(error_log, strings['common']['not_file'], (th.date_time(),name,file_name))
``` 

### Tests performed

I tried to replicate the issue locally, executing the part of the code that contains the error (thanks to @MarcelKemp  for the research), so that the file would be open and locked, so when the script that would delete the file was executed, the exception would be given and the ERROR message would be shown in the console.

The tests that were performed without success were the following:

#### Ubuntu

1. Open the file with the `text editor` and while it is open and the script is being modified, the file is deleted and the message we are looking for is not displayed.
2. Open the file with `vim` and while it is open and is being modified the script is executed, the file is deleted and the error message is not shown either.
3. Generate a `Python` script to open and lock the file, and then run the script we are testing, the file was also deleted and the exception was not executed.
4. Based on this [documentation](https://baulderasec.wordpress.com/programando-2/programacion-con-linux/gestion-de-datos/bloqueo-de-archivos/), I tried with some of the cases shown there to try to lock the file so that the exception could be generated and replicate the issue, but this way it was not possible either and the file was deleted without problems.

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | RC                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.6.0-rc |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4551/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/monitor-manager-Test_stress_B4551_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/plots/Test_stress_B4551_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4551_manager_2023-11-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/logs/ossec_Test_stress_B4551_manager_2023-11-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4551_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/data/monitor-manager-Test_stress_B4551_manager-pre-release.csv)
[Test_stress_B4551_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/data/Test_stress_B4551_manager_analysisd_events.csv)
[Test_stress_B4551_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/data/Test_stress_B4551_manager_analysisd_state.csv)
[Test_stress_B4551_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_manager_centos/data/Test_stress_B4551_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/monitor-winagent-Test_stress_B4551_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/Test_stress_B4551_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/Test_stress_B4551_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/Test_stress_B4551_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/plots/Test_stress_B4551_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4551_windows_2023-11-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/logs/ossec_Test_stress_B4551_windows_2023-11-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4551_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/data/monitor-winagent-Test_stress_B4551_windows-pre-release.csv)
[Test_stress_B4551_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4551-3600m/B4551_agent_windows/data/Test_stress_B4551_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by MarcelKemp** [comment]
In the stress tests, we can see how the _`ERROR`_ keeps appearing with the proposed fix, so it is necessary to check what is happening and propose a new fix to avoid the _error_ and keep it working as expected.

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | RC                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.6.0-rc |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4573/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/monitor-manager-Test_stress_B4573_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/plots/Test_stress_B4573_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4573_manager_2023-11-10.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/logs/ossec_Test_stress_B4573_manager_2023-11-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4573_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/data/monitor-manager-Test_stress_B4573_manager-pre-release.csv)
[Test_stress_B4573_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/data/Test_stress_B4573_manager_analysisd_events.csv)
[Test_stress_B4573_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/data/Test_stress_B4573_manager_analysisd_state.csv)
[Test_stress_B4573_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_manager_centos/data/Test_stress_B4573_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/monitor-winagent-Test_stress_B4573_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/Test_stress_B4573_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/Test_stress_B4573_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/Test_stress_B4573_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/plots/Test_stress_B4573_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4573_windows_2023-11-10.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/logs/ossec_Test_stress_B4573_windows_2023-11-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4573_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/data/monitor-winagent-Test_stress_B4573_windows-pre-release.csv)
[Test_stress_B4573_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4573-3600m/B4573_agent_windows/data/Test_stress_B4573_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>
