### ISSUE TITLE
Systemctl runs on an agent even if the service passed is manager

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#17944]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.4.5-40413  | Agent | Packages | CentOS 8 |

## Description

When we run `systemctl <action> wazuh-manager` on an agent, it works.

This has also been reproduced in 4.3.10-40323.

## Steps to reproduce

1. Check agent:

```shell
[root@centos-agent vagrant]# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.4.5"
WAZUH_REVISION="40413"
WAZUH_TYPE="agent"
```

2. Check status:

```shell
[root@centos-agent vagrant]# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

3. Stop agent with `systemctl stop wazuh-manager`:

```shell
[root@centos-agent vagrant]# systemctl stop wazuh-manager
```

   No error is returned.

4. Check agent status:

```shell
[root@centos-agent vagrant]# /var/ossec/bin/wazuh-control status
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
```

**Comment by vikman90** [comment]
@juliamagan Could you please show us the exact steps to reproduce it?

I've not managed to reproduce the issue.

- Using a clean CentOS Stream 8 VM.
- First check:
```shell
find /usr -name "wazuh-*"
```
> No result.
- Install Wazuh Agent 4.4.5:
```shell
yum install wazuh-agent
```
```
=====================================================================================================================================
 Package                           Architecture                 Version                       Repository                        Size
=====================================================================================================================================
Installing:
 wazuh-agent                       x86_64                       4.4.5-1                       wazuh_repo                       8.5 M
```
- Second check:
```shell
find /usr -name "wazuh-*"
```
> /usr/lib/systemd/system/wazuh-agent.service
- Try to start the manager service:
```shell
systemctl start wazuh-manager
```
> Failed to start wazuh-manager.service: Unit wazuh-manager.service not found.

**Comment by juliamagan** [comment]
After checking with another box, I have been able to confirm that the behavior is as expected. The box I was using before is a custom QA box, which seems to be not right, because even if it is clean, it has the manager service:

```
[root@centos-agent vagrant]# find /usr -name 'wazuh-*'
/usr/lib/systemd/system/wazuh-manager.service
/usr/local/bin/wazuh-log-metrics
/usr/local/bin/wazuh-metrics
/usr/local/bin/wazuh-statistics
```

This issue can be closed, sorry for the inconvenience!
