### ISSUE TITLE
Reduce basic suite of API Integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#17942]
## Description

We recently increased the specs of the instances where the API integration tests are launched. This of course comes with a higher cost, which we could reduce a little bit with some simple changes. 

What is requested in this issue is to remove from the basic test suite (the one used when there is no specific match, as in [this PR](https://github.com/wazuh/wazuh/pull/17632/checks?check_run_id=15096230659)) all those that are not testing the agents or the cluster.
![image](https://github.com/wazuh/wazuh/assets/23361101/81dd7eb9-c4ac-4e32-b2f4-7fde58d6db5b)

Still, all the tests are run daily in a build called nightly, so we should be able to detect errors in the product early. The change may have to be made here:
https://github.com/wazuh/wazuh/blob/ffa66c34698cb12b52161b022f69e3f5f02a1229/api/test/integration/mapping/_test_mapping.py#L42-L45

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Description

- I've been testing the basic integration tests of the Api
- I modified the function def calculate_test_mappings(): to launch cluster and agent tests.

**Comment by javiersanchz** [comment]
## Description

- I have been installing the docker-compose and installing dependencies to run the integration tests.
- I was looking at the integrity tests for each endpoint.

**Comment by javiersanchz** [comment]
## Description
 - Delete modified tests in integration_test_api_endpoints.json
