### ISSUE TITLE
Syscollector local.db lost other read permissions during WPK upgrade for macOS agent

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17964]
|Wazuh Version|OS|
|---|---|
|`4.6.0`|`macOS High Sierra`|

### Description

During the investigation of https://github.com/wazuh/wazuh/issues/17720, it was observed that macOS endpoints change the other read permissions of the `/Library/Ossec/queue/syscollector/db/local.db` file after upgrading it from 4.4.5 to 4.6.0 using WPK.
```
Expected
-rw-r--r--  1 root  wazuh  90112 Jul 19 03:22 local.db
Found
-rw-r-----  1 root  wazuh  90112 Jul 19 03:28 local.db
```  

Maybe related with https://github.com/wazuh/wazuh/issues/13510

### Evidences

- [checkfiles_macos1013.zip](https://github.com/wazuh/wazuh/files/12094154/checkfiles_macos1013.zip)

**Comment by TomasTurina** [comment]
Hi @Rebits,

This is expected. This is the PR that introduces this change: https://github.com/wazuh/wazuh/pull/17447

I think the issue can be closed.

cc @davidjiglesias @vikman90 @Dwordcito
