### ISSUE TITLE
Official wazuh arm64 docker installation

### ISSUE THREAD

**Issue by tkbstudios** [wazuh/wazuh#17974]
I would like to know if it was possible of making the wazuh/wazuh docker image also available for arm64, the main point is to get it working on a pi at home.

**Comment by mariot8** [comment]
shouldn't it be reported under https://github.com/wazuh/wazuh-docker?

**Comment by tkbstudios** [comment]
oh wait 💀 sorry guys

**Comment by tkbstudios** [comment]
https://github.com/wazuh/wazuh-docker/issues/923
