### ISSUE TITLE
 os Packages 

### ISSUE THREAD

**Issue by xisafe** [wazuh/wazuh#1797]
## Bug report

**OS**
CentOS7

**Wazuh version**
3.6.1

**Wazuh API version**
3.6.1

1. No results match your search criteria
2. Error while init table - 3013 - Error retrieving data from Wazuh DB: Error 2007 - Error retrieving data from Wazuh DB. - Please refresh your browser.

![image](https://user-images.githubusercontent.com/29724312/47979557-be128580-e0fe-11e8-8d07-608ac5ef140a.png)

**Comment by xisafe** [comment]
https://github.com/wazuh/wazuh/issues/1202

**Comment by xisafe** [comment]
Regards

**Comment by mgmacias95** [comment]
Hello @xisafe,

Have you tried the fix from https://github.com/wazuh/wazuh/issues/1202#issuecomment-417625301? That has worked for most of our Linux users and it's a known bug that is going to be fixed in our next release.

Best regards,
Marta

**Comment by Zenidd** [comment]
Hello @xisafe,

Did you get access to Wazuh alerts from the APP in Kibana? If you still have a problem please contact us and we will work to give you a solution.

Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hello @xisafe,

I'm closing this ticket due to inactivity. Please do not hesitate to open a new ticket in case you see it necessary.

Regards,

Juan Pablo Sáez
