### ISSUE TITLE
Too big message size from socket warning during macOS Catalina manual upgrade 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17973]
| Wazuh Version | OS
| ------------- | ------------- |
| `4.6.0`       | `macOS Catalina`

### Description

During https://github.com/wazuh/wazuh/issues/17720 it has been detected the following errors after macOS Catalina agent manual upgrade:
```
root@ip-172-31-11-22:/home/qa# egrep -iE "error|war|crit" /var/ossec/logs/ossec.log 
2023/07/19 15:31:07 wazuh-remoted: WARNING: Too big message size from socket [19].
2023/07/19 15:31:07 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '007' at 'any'.
2023/07/19 15:31:07 wazuh-remoted: WARNING: Decrypt the message fail, socket 19
```

Despite these errors, the agent was updated correctly.

### Steps to reproduce

- Include the following block to the manager configuration

```
<agent-upgrade>
  <chunk_size>32768</chunk_size>
</agent-upgrade>

<task-manager>
  <task_timeout>1h</task_timeout>
</task-manager>
```

- Install and register a 4.4.5 macOS Catalina agent to the manager
- Wait until the agent is marked as active
- Upgrade manually the macOS agent using the 4.6.0 alpha package https://packages-dev.wazuh.com/warehouse/test/4.6/macos/wazuh-agent-4.6.0-1.pkg
- Check in the manager logs the reported warnings

**Comment by jotacarma90** [comment]
Hi team, while investigating this issue, I have found that the packages that reproduce the problem have been removed and the creation of new packages is encountering some problems. I am extending the estimated ETA for this issue by one more day, it should be closed on Monday.

**Comment by Rebits** [comment]
I attempted to reproduce this issue once more, but unfortunately, I was unable to replicate it successfully. Therefore, I am marking this issue as resolved for now.
