### ISSUE TITLE
Modify VD API tests for NVD 2.0 refactor

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#17983]
|Wazuh version|Component|Install type|Related PR|
|---|---|---|---|
| 4.5.0 | API tests Vuln detector | Manager | https://github.com/wazuh/wazuh/pull/17954 |

## Description

After the following changes in the NVD: https://github.com/wazuh/wazuh/issues/16555, it is necessary to deprecate the tag `update_from_year` and modify the Vulnerability Detector API tests.

Currently, it is not necessary to define the year, because it downloads a single file, which is located at:
- https://feed.wazuh.com/vulnerability-detector/NVD/generated-feeds/complete_nvd_feed.json.gz

## Configurations
The configuration should be similar to the one configured in https://github.com/wazuh/wazuh/pull/17672.

#### Cases found to be changed
- https://github.com/wazuh/wazuh/blob/master/api/test/integration/test_vulnerability_endpoints.tavern.yaml
- https://github.com/wazuh/wazuh/blob/master/api/test/integration/env/configurations/vulnerability/manager/configuration_files/ossec_module.conf
- https://github.com/wazuh/wazuh/blob/master/api/test/integration/env/configurations/vulnerability/manager/configuration_files/nvd_providers.sh
- Check if there are other cases

**Comment by RamosFe** [comment]
## Update

In the following files, the deprecated tag was already removed

- https://github.com/wazuh/wazuh/blob/master/api/test/integration/test_vulnerability_endpoints.tavern.yaml
- https://github.com/wazuh/wazuh/blob/master/api/test/integration/env/configurations/vulnerability/manager/configuration_files/ossec_module.conf

The tag in the following file was removed:
https://github.com/wazuh/wazuh/blob/7dc8fafd5a1b15e3543f00ceaa9bd0d70e001fae/api/test/integration/env/configurations/vulnerability/manager/configuration_files/nvd_providers.sh#L1-L6

**Comment by RamosFe** [comment]
## Update

Deleted `update_from_year` in `api/test/integration/env/configurations/vulnerability/manager/configuration_files/nvd_providers.sh` and `api/test/integration/env/configurations/vulnerability/manager/configuration_files/ossec_module.conf`.
