### ISSUE TITLE
Windows WPK upgrade produces rootcheck errors

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17985]
| Wazuh Version | OS
| ------------- | ------------- |
| `4.6.0`       | `Windows Server 2016`

### Description

During the upgrade process of WPK upgrade of Wazuh agent version 4.5.0 to version 4.6.0 on Windows Server 2016 for https://github.com/wazuh/wazuh/issues/17720, it has been detected the following error during upgrade in the windows agent logs:
```
2023/07/17 09:06:29 rootcheck: ERROR: No winmalware file: './shared/win_malware_rcl.txt'
2023/07/17 09:06:29 rootcheck: ERROR: No winapps file: './shared/win_applications_rcl.txt'
```

Error seems to be a race condition and difficult to replicate

### Steps to replicate
 - Install a Wazuh 4.6.0 manager using the following package: [wazuh-manager_4.6.0-1_amd64.deb](https://packages-dev.wazuh.com/warehouse/test/4.6/deb/var/wazuh-manager_4.6.0-1_amd64.deb).
 - Install a Wazuh 4.5.0 Windows agent and register it to the manager
-  Initiate the upgrade process using the upgrade_custom API endpoint and the custom WPK for version 4.6.0. The WPK file can be downloaded from: [wazuh_agent_v4.6.0_windows.wpk](https://packages-dev.wazuh.com/warehouse/test/4.6/wpk/windows/wazuh_agent_v4.6.0_windows.wpk).
- Check the windows agent logs to ensure the errors appears.

**Comment by vikman90** [comment]
@Rebits Can you share the full agent log?

If the error appears before the upgrade, this issue is known, and recurrent, and it was reported: https://github.com/wazuh/wazuh/issues/8309. It was fixed for 4.6.0.

Best!
