### ISSUE TITLE
macOS Monterey WPK Upgrade fails

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17984]
| Wazuh Version | OS
| ------------- | ------------- |
| `4.6.0`       | `macOS Monterey`

### Description

During the upgrade process of WPK upgrade for Wazuh version 4.5.0 to version 4.6.0 on macOS Monterey for https://github.com/wazuh/wazuh/issues/17720, a couple of issues have been encountered. The first attempt resulted in a "Send open file error" as shown in the response below:
```

root@ip-172-31-13-137:/home/qa# curl -k -X GET "https://localhost:55000/agents/upgrade_result?agents_list=003&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "message": "Success",
            "agent": "003",
            "task_id": 3,
            "node": "node01",
            "module": "upgrade_module",
            "command": "upgrade_custom",
            "status": "Error",
            "error_msg": "Send open file error",
            "create_time": "2023-07-20T12:39:20Z",
            "update_time": "2023-07-20T12:39:21Z"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All upgrade tasks were returned",
   "error": 0
}
```

In the second attempt, the upgrade never completed, and the status remained stuck in "Updating" as shown in the response below:
```
curl -k -X GET "https://localhost:55000/agents/upgrade_result?agents_list=003&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "message": "Success",
            "agent": "003",
            "task_id": 4,
            "node": "node01",
            "module": "upgrade_module",
            "command": "upgrade_custom",
            "status": "Updating",
            "create_time": "2023-07-20T12:39:59Z",
            "update_time": "2023-07-20T12:39:59Z"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All upgrade tasks were returned",
   "error": 0
}
```

Additionally, the upgrade.log file of the agent only shows the following:
```
sh-3.2# cat /Library/Ossec/logs/upgrade.log 
2023/07/20 14:41:04 - Generating Backup.
2023/07/20 14:41:13 - Upgrade started.
``` 

In addition, the agent lost the connection to the manager for a brief moment:
```
2023/07/20 10:51:45 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.13.137]:1514/tcp': 'Connection refused'.
2023/07/20 10:51:55 wazuh-agentd: INFO: Trying to connect to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:51:55 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.13.137]:1514/tcp': 'Connection refused'.
2023/07/20 10:52:05 wazuh-agentd: INFO: Trying to connect to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:05 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:05 wazuh-agentd: INFO: Server responded. Releasing lock.
2023/07/20 10:52:22 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2023/07/20 10:52:22 wazuh-agentd: INFO: Closing connection to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:22 wazuh-agentd: INFO: Trying to connect to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:22 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.13.137]:1514/tcp': 'Connection refused'.
2023/07/20 10:52:27 wazuh-logcollector: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/07/20 10:52:32 wazuh-agentd: INFO: Trying to connect to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:32 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.13.137]:1514/tcp': 'Connection refused'.
2023/07/20 10:52:42 wazuh-agentd: INFO: Trying to connect to server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:42 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.13.137]:1514/tcp).
2023/07/20 10:52:42 wazuh-agentd: INFO: Server responded. Releasing lock.
2023/07/20 10:52:47 wazuh-logcollector: INFO: Agent is now online. Process unlocked, continuing...
```

### Steps to Replicate

To reproduce the issue, follow these steps:

 - Install the Wazuh 4.6.0 manager using the following package: [wazuh-manager_4.6.0-1_amd64.deb](https://packages-dev.wazuh.com/warehouse/test/4.6/deb/var/wazuh-manager_4.6.0-1_amd64.deb).
 - Include the following configuration in the manager:
```
<agent-upgrade>
  <chunk_size>32768</chunk_size>
</agent-upgrade>

<task-manager>
  <task_timeout>1h</task_timeout>
</task-manager>
```
-  Install a Wazuh 4.5.0 macOS Monterey agent and register it to the manager.
-  Initiate the upgrade process using the upgrade_custom API endpoint and the custom WPK for version 4.6.0. The WPK file can be downloaded from: [wazuh_agent_v4.6.0_macos_x86_64.wpk](https://packages-dev.wazuh.com/warehouse/test/4.6/wpk/macos/x86_64/pkg/wazuh_agent_v4.6.0_macos_x86_64.wpk).
- Observe that the upgrade process never completes and remains stuck in the "Updating" status.

Please note that the provided URLs for package downloads are specific to the mentioned versions and may change in the future.

**Comment by Nicogp** [comment]
Hi @Rebits,

I have doubts about the macOS version since at the beginning you name macOS Monterrey and then you install macOS Big Sur, does the error occur in both or in a specific version?
![image](https://github.com/wazuh/wazuh/assets/13004400/842f0282-7cb7-423c-9a76-edfe3236e861)

**Comment by Nicogp** [comment]
Hi @Rebits 

I have performed tests in my local environment and the agent upgraded correctly every time, even with the default configuration of `<task-manager>` and `<agent-upgrade>`. In all the tests I have done it did not take more than 3 minutes to upgrade.

Agent version 4.5:
```
/Library/Ossec/bin/wazuh-control start
Starting Wazuh v4.5.0...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

Agent after upgrade:
```
/Library/Ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40600"
WAZUH_TYPE="agent"
```

Result of the upgrade:
```
curl -k -X GET "https://localhost:55000/agents/upgrade_result?agents_list=010&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "message": "Success",
            "agent": "010",
            "task_id": 1,
            "node": "node01",
            "module": "upgrade_module",
            "command": "upgrade_custom",
            "status": "Updated",
            "create_time": "2023-07-24T14:29:38Z",
            "update_time": "2023-07-24T14:31:44Z"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All upgrade tasks were returned",
   "error": 0
}
```

The error you have had was previously seen in the following issues:
https://github.com/wazuh/wazuh/issues/14856
https://github.com/wazuh/wazuh/issues/17272#issuecomment-1563182999

**Comment by Nicogp** [comment]
To clarify doubts regarding the error "Send open file error", in the upgrade process "lock", "open", "write", "close", "verify", "upgrade command" messages are sent, if the confirmation of the sending of one of these messages is not received in time, the following errors occur respectively:
```
"Send lock restart error"
"Send open file error",
"Send write file error",
"Send close file error",
"Send verify sha1 error",
"Send upgrade command error"
```
and in case a message is not sent, no further attempt is made.
If the environment is low on resources (like the one in this test and the same in the issues I referenced) or an unstable network, one of these errors is likely to occur.

In case more tests are needed I request access to the environment that has conflicts, since in my local environment it was not possible to reproduce the issue.
