### ISSUE TITLE
Changing manager ip on all agents

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#1799]
Hello,
I recently moved to a clustered environment and I need to change the manager IP to the load balancer on all the agents. 
Is there a way to change the manager IP on all the agents from the current manager?
I tried with agent.conf but it didn't work.

Thanks in advance

**Comment by crolopez** [comment]
Hi @agentsofshield,

Unfortunately, it is not possible to make a massive change of the manager's address in all agents unless you use a tool external to Wazuh.

Best regards.
