### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - Integration tests

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#18005]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `v4.6.0-pre-alpha1`| https://github.com/wazuh/wazuh-qa/commit/6b81073733b764fd5c689e450b6a8f1e3a30dcbc | `v4.6.0-pre-alpha1`  |https://github.com/wazuh/wazuh/commit/2ad5be1952c79ffd15cbeed51bc5ccd4af7e633a  |

We are going to check that the integration tests of the `4.6`  branch of `wazuh-qa` work correctly using the [v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/17713

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|🔵|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:red_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:orange_circle:</td>
<td style="width: 79px;">:orange_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">:red_circle:</td>
<td style="width: 79px;">:red_circle:</td>
<td style="width: 97px;">:red_circle:</td>
<td style="width: 97px;" colspan="2">:red_circle:</td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="width: 97px;">:green_circle:</td>
<td style="width: 97px;" colspan="2">:green_circle:</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">:orange_circle:</td>
<td style="width: 99px;">:orange_circle:</td>
<td style="width: 79px;">:orange_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">:orange_circle:</td>
</tr>
</tbody>
</table>

## Evidence

**IT Launcher build**:  https://ci.wazuh.info/job/Test_integration_launcher/177/

## Conclusion

New issues
- https://github.com/wazuh/wazuh-qa/issues/4336
- https://github.com/wazuh/wazuh-jenkins/issues/5450
- https://github.com/wazuh/wazuh-qa/issues/4356
- https://github.com/wazuh/wazuh-qa/issues/4354
- https://github.com/wazuh/wazuh-jenkins/issues/5436

Known issues
- https://github.com/wazuh/wazuh-qa/issues/4231

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias
- [x] @jnasselle

**Comment by roronoasins** [comment]
# Active Response :red_circle: 
https://github.com/wazuh/wazuh/issues/17739#issuecomment-1645229469

**Comment by roronoasins** [comment]
# FIM :orange_circle:

## Agent/Manager
 
### Details

**Builds**:
- https://ci.wazuh.info/job/Test_integration/41429/
- https://ci.wazuh.info/job/Test_integration/41430/
- https://ci.wazuh.info/job/Test_integration/41431/

**Report**: 
```
test_fim/test_registry/test_registry_wildcards/test_registry_wildcards.py:85: in <module>
    t1_configurations = load_configuration_template(configurations_path, t1_configuration_parameters,
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.6.0-py3.10.egg/wazuh_testing/tools/configuration.py:696: in load_configuration_template
    configuration = file.read_yaml(data_file_path)
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.6.0-py3.10.egg/wazuh_testing/tools/file.py:61: in read_yaml
    with open(file_path) as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Test_integration_B41429_20230721162322/tests/integration/test_fim/test_registry/test_registry_wildcards/data/configuration_templates/configuration_registry_wildcards.yaml'
```
### Description
It appears that the tests were not launched due to a missing [configuration template](https://github.com/wazuh/wazuh-qa/blob/v4.6.0-pre-alpha1/tests/integration/test_fim/test_registry/test_registry_wildcards/test_registry_wildcards.py)

**Comment by roronoasins** [comment]
# FIM :orange_circle:

## Agent/Manager
 
### Details

**Builds**:
- https://ci.wazuh.info/job/Test_integration/41429/
- https://ci.wazuh.info/job/Test_integration/41430/
- https://ci.wazuh.info/job/Test_integration/41431/

**Report**: 
```
test_fim/test_registry/test_registry_wildcards/test_registry_wildcards.py:85: in <module>
    t1_configurations = load_configuration_template(configurations_path, t1_configuration_parameters,
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.6.0-py3.10.egg/wazuh_testing/tools/configuration.py:696: in load_configuration_template
    configuration = file.read_yaml(data_file_path)
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.6.0-py3.10.egg/wazuh_testing/tools/file.py:61: in read_yaml
    with open(file_path) as f:
E   FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Test_integration_B41429_20230721162322/tests/integration/test_fim/test_registry/test_registry_wildcards/data/configuration_templates/configuration_registry_wildcards.yaml'
```
### Description
It appears that the tests were not launched due to a missing [configuration template](https://github.com/wazuh/wazuh-qa/blob/v4.6.0-pre-alpha1/tests/integration/test_fim/test_registry/test_registry_wildcards/test_registry_wildcards.py)

**Comment by roronoasins** [comment]
# Logtest :red_circle: 

## Manager

### Details 

**Build**: https://ci.wazuh.info/job/Test_integration/41437/
**Report**: [manager_html_report_Test_integration_B41437_20230721162436(1).zip](https://github.com/wazuh/wazuh/files/12142910/manager_html_report_Test_integration_B41437_20230721162436.1.zip)
**Failed tests**:
- `test_logtest/test_invalid_rule_decoders_syntax/test_invalid_decoder_syntax.py::test_invalid_decoder_syntax[Invalid decoder syntax: invalid offset1]`


### Description
In progress. Reproducing this error

**Comment by Rebits** [comment]
# Vulnerability Detector :red_circle: 

## Manager :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41443/
**Report**:  [manager_html_report_Test_integration_B41443_20230721162346(1).zip](https://github.com/wazuh/wazuh/files/12143826/manager_html_report_Test_integration_B41443_20230721162346.1.zip)


**Failed tests**
- `test_download_feeds`
- `test_validate_feed_content`

**Issue**: 
- https://github.com/wazuh/wazuh-qa/issues/4231

### Description
The test_validate_feed_content error is motivated for the use of outdated URLs in the test (https://people.canonical.com/ instead of the updated https://security-metadata.canonical.com/).
Regarding download_feeds, it seems that it fails for RHEL5 syste. probably due to network error. This can be checked in the manager logs for the failed tests cases, in which we can see it is trying to get the feed from the correct URL `https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2`:
```
2023/07/21 15:50:46 wazuh-modulesd:vulnerability-detector[11163] wm_vuln_detector.c:5259 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Red Hat Enterprise Linux 5' database update.
2023/07/21 15:50:46 wazuh-modulesd:download[11163] wm_download.c:231 at wm_download_dispatch(): DEBUG: Downloading 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2' to 'tmp/req-592445699'
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:282 at wm_sync_agents(): DEBUG: Agents synchronization completed.
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:285 at wm_sync_agents(): DEBUG: wm_sync_agents(): 5.727 ms (20.000 clock ms).
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:423 at wm_sync_legacy_groups_files(): DEBUG: Couldn't open directory 'queue/agent-groups': No such file or directory.
2023/07/21 15:50:47 wazuh-modulesd[11163] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:698 at wm_inotify_setup(): DEBUG: wd_agents='1'
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:728 at wm_inotify_start(): DEBUG: Waiting for event notification...
2023/07/21 15:50:47 wazuh-modulesd:database[11163] wm_database.c:704 at wm_inotify_setup(): DEBUG: wd_shared_groups='2'
2023/07/21 15:50:47 wazuh-modulesd[11163] url.c:152 at wurl_get(): DEBUG: CURL ERROR: The requested URL returned error: 404 Not Found
2023/07/21 15:50:47 wazuh-modulesd:download[11163] wm_download.c:235 at wm_download_dispatch(): DEBUG: Cannot download file 'tmp/req-592445699' from URL: 'https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2'
2023/07/21 15:50:47 wazuh-modulesd[11163] wm_vuln_detector.c:4953 at wm_vuldet_fetch_oval(): DEBUG: (5405): The download cannot be completed. Retrying in '0' seconds.
```

**Comment by Rebits** [comment]
# WazuhDB  :red_circle: 

## Manager :red_circle: 

**Build**: https://ci.wazuh.info/job/Test_integration/41444/
**Report**:  

**Failed tests**
- `test_agent_database_version`

**Issue**: 
- None

### Description

The `test_agent_database_version` has failed due to a recent version update. The specific details can be found in the following issue https://github.com/wazuh/wazuh/issues/12343
As per the latest QA 4.6.0 alpha tag, this particular change has been incorporated. However, it appears that the packages released over the last 3 weeks do not include this update, leading to the expected failure.

**Comment by Rebits** [comment]
# Syscollector :orange_circle: 

### Details
**Build** https://ci.wazuh.info/job/Test_integration/41445/
**Issue**:
- https://github.com/wazuh/wazuh-jenkins/issues/5436


### Description

Syscollector IT module is not supported for 4.6.0
