### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#18017]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |  #17713                                           |
| **Version**                                   |               4.6.0                             |
| **Release candidate #**                       |              Pre-Alpha1                              |
| **Tag**                                       |             [v4.6.0-pre-alpha1     ](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1)                         |
| **Previous Workload benchmarks metrics issue**|                   -                         |

Job https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/267/

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|        50000           |         25           |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

# Conclusions :red_circle:
In summary, the test can be considered satisfactory for the most part, except for the following defects that were found during the testing.

### API Performance :red_circle: 
Defects in:

GET /manager/logs https://github.com/wazuh/wazuh/issues/17740 :red_circle:
PUT /active-response https://github.com/wazuh/wazuh-qa/issues/3665 (Previously described as an xfailed test that needs to be corrected.) :yellow_circle:
PUT /agents/group https://github.com/wazuh/wazuh-qa/issues/3665 (Previously described as an xfailed test that needs to be corrected.) :yellow_circle:

### Performance test :yellow_circle:
The Performance test is not functioning correctly due to an error caused by variable passing: https://github.com/wazuh/wazuh-qa/issues/4298 

### Reliability test :red_circle:
The Reliability test was executed manually because the Python version needs to be updated to enable automatic execution. This issue is opened in the following issue:

- https://github.com/wazuh/wazuh-qa/issues/4299

Additionally, in the Reliability test some ERROR messages were detected in all the workers and it should be investigated in reliability/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py::test_cluster_error_logs being related to:

- https://github.com/wazuh/wazuh/issues/15802

- reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order
/test_cluster_worker_logs_order.py::test_check_logs_order_workers

- https://github.com/wazuh/wazuh-qa/issues/4365

- reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py::test_cluster_connection

- https://github.com/wazuh/wazuh-qa/issues/4364

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by pro-akim** [comment]
[Report](https://github.com/wazuh/wazuh/files/12146067/artifacts.zip)

## API performance results

---
|                                  |                                            |                                           |            
|--|--|--|
| **Endpoint test name**  | **Status** | **Issues Ref.** |
| GET /cluster/local/info | :green_circle: | |
| GET /cluster/nodes| :green_circle:  | |
| GET /cluster/healthcheck | :green_circle: | |
| GET /cluster/status | :green_circle: | |
| GET /cluster/local/config | :green_circle: | |
| GET /cluster/api/config | :green_circle: | |
| GET /cluster/configuration/validation | :green_circle: | |
| GET /manager/status | :green_circle: | |
| GET /manager/info | :green_circle: | |
| GET /manager/configuration | :green_circle: | |
| GET /manager/logs | :green_circle: | |
| GET /manager/api/config | :green_circle: | |
| GET /manager/configuration/validation | :green_circle: | |
| GET /mitre/groups | :green_circle: | |
| GET /mitre/metadata | :green_circle: | |
| GET /mitre/mitigations | :green_circle: | |
| GET /mitre/references | :green_circle: | |
| GET /mitre/software | :green_circle: | |
| GET /mitre/tactics | :green_circle: | |
| GET /mitre/techniques | :green_circle: | |
| GET /overview/agents | :green_circle:  | |
| GET /tasks/status | :green_circle: | |
| PUT /active-response | :yellow_circle: | Endpoint is skipped instead of xfail (https://github.com/wazuh/wazuh-qa/issues/3665). Also: https://github.com/wazuh/wazuh-qa/issues/1266|
| PUT /rootcheck | :green_circle: | |
| PUT /syscheck | :green_circle: | |
| POST /groups | :green_circle: | |
| POST /security/users | :green_circle: | |
| POST /security/roles | :green_circle: | |
| POST /security/policies | :green_circle: | |
| POST /security/rules | :green_circle: | |
| PUT /agents/group | :yellow_circle: |  Endpoint is skipped instead of xfail (https://github.com/wazuh/wazuh-qa/issues/3665). This related issue was opened in the past: https://github.com/wazuh/wazuh/issues/13872|
| PUT /agents/group/new_test_group/restart | :green_circle: | |
| PUT /agents/restart | :red_circle: |  |
| POST /agents | :green_circle: | |
| POST /agents/insert ​|  :green_circle: | |
| POST /agents/insert​/quick | :green_circle: | |
| GET /agents | :green_circle: | |
| GET /agents/no_group | :green_circle: | |
| GET /agents/outdated | :green_circle: | |
| GET /decoders | :green_circle: | |
| GET /groups | :green_circle: | |
| GET /lists | :green_circle: | |
| GET /rules | :green_circle: | |
| GET /security/users | :green_circle: | |
| GET /security/roles | :green_circle: | |
| GET /security/policies | :green_circle: | |
| GET /security/rules | :green_circle: | |
| DELETE /groups | :green_circle: | |
| DELETE /agents | :green_circle: | |
| DELETE /security/users | :green_circle: | |
| DELETE /security/roles | :green_circle: | |
| DELETE /security/policies | :green_circle: | |
| DELETE /security/rules | :green_circle: | |
| PUT /manager/restart | :green_circle: | |
| PUT /cluster/restart | :green_circle: | |

**Comment by pro-akim** [comment]
Some problems with the pipeline. 
It is not being created the artifact.

**Comment by jnasselle** [comment]
# Update

After trying to run several times this tests, we were unable to do it because destroying the resources stage causes some exceptions and does not allow the artifacts to be fetched

**Comment by pro-akim** [comment]
# Update
Using wazuh-proxy instead of elb as a parameter worked creating artifacts in [274](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/274/)

**Comment by pro-akim** [comment]
Performance test:  https://github.com/wazuh/wazuh-qa/issues/4298
Reliability test: https://github.com/wazuh/wazuh-qa/issues/4299

Still, some manual testing should be performed (Reliability test) to finish the issue.

**Comment by pro-akim** [comment]
# Update
## Reliability test results:

### 3/5 tests failed.

### Failures:

- reliability/test_cluster/test_cluster_logs/test_cluster_connection/test_cluster_connection.py::test_cluster_connection

<details>

Testing: Verify that no worker disconnects from the master once they are connected.

```
                if not conn:
>                   pytest.fail(f'Could not find "Sucessfully connected to master" message in the '
                                f'{node_name.search(log_file)[1]}')
E                   Failed: Could not find "Sucessfully connected to master" message in the worker_21
```

However: checking worker_21/cluster.log:
```
2023/07/25 09:27:01 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_21] [Main] Successfully connected to master.
```
And
```
2023/07/25 09:27:16 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_21] [Main] Successfully connected to master.
```

The new issue is opened to fix this issue:

</details>

- reliability/test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py::test_cluster_error_logs

<details>
Testing: Look for any error messages in the logs of the cluster nodes.

It seems related to:
- https://github.com/wazuh/wazuh/issues/15802

The main difference with the mentioned issue is that this behavior happened during all the activity in all the 25 workers. It was not related to OS.



```
>       assert not nodes_with_errors, 'Errors were found in the "cluster.log" file of ' \
                                      'these nodes: \n- ' + '\n- '.join(nodes_with_errors)
E       AssertionError: Errors were found in the "cluster.log" file of these nodes: 
E         - worker_21
E         - worker_13
E         - worker_4
E         - worker_6
E         - worker_18
E         - worker_20
E         - worker_11
E         - worker_2
E         - worker_14
E         - worker_3
E         - worker_9
E         - worker_17
E         - worker_22
E         - worker_7
E         - worker_5
E         - worker_19
E         - worker_12
E         - worker_25
E         - worker_8
E         - worker_24
E         - worker_23
E         - worker_10
E         - worker_16
E         - worker_15
E         - worker_1
E       assert not {'worker_1': [b'2023/07/25 09:03:37 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_1] [Main] Error se...nager_12] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok', ...], ...}

test_cluster/test_cluster_logs/test_cluster_error_logs/test_cluster_error_logs.py:57: AssertionError
```
Detected ERROR was always as the following log:
```
2023/07/25 09:28:04 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_25] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
```
</details>

- reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order
/test_cluster_worker_logs_order.py::test_check_logs_order_workers
<details>
Testing: Check that cluster logs appear in the expected order.

This pattern happens in every worker.

```
E            - Log type: Integrity check
E              Expected logs: ['Sending zip file to master.*']
E              Found log: 2023/07/25 09:03:05 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_21] [Integrity check] Sending zip file.
```

```
E            - Log type: Agent-groups recv
E              Expected logs: ['The checksum of both databases match.*Reset the attempt counter.', 'The checksum of both databases match.*', 'Checksum comparison failed. Attempt 10/10.*', 'Checksum comparison failed. Attempt .*', "The master's checksum and the worker's checksum are different. Local checksum:.*| Master checksum:.*."]
E              Found log: 2023/07/25 09:25:34 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B274_manager_21] [Agent-groups recv] The checksum of master (0107654add85786339eba7c5fa72cee25783dd6c) and worker (4ba9e4d09c32baef1d763fd81e3cf804aa06b607) are different.
```
</details>
It seems that log messages in Integrity check and Agent-groups recv have changed, however, it is clear that the message has the same meaning.
Log messages should be updated following the new conventions.
The new issue opened:

Report is attached in this [file](https://github.com/wazuh/wazuh/files/12161612/report.zip).

**Comment by pro-akim** [comment]
#Update
Test performed.
Report done.
Ready for review.

**Comment by pro-akim** [comment]
# Update
@RamosFe had a different result of test report running Reliability test.
He reported:
<details>

```console
  ~/Doc/W/R/wazuh-qa/t/r/test_cluster on   master ❯ python3 -m pytest test_cluster_logs/test_cluster_connection/test_cluster_connection.py --artifacts_path='/Users/framos/Desktop/artifacts' --html=report.html
================================================================= test session starts ==================================================================
platform darwin -- Python 3.9.6, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/framos/Documents/Wazuh/Repositories/wazuh-qa/tests, configfile: pytest.ini
plugins: testinfra-5.0.0, html-3.1.1, metadata-2.0.4
collected 1 item

test_cluster_logs/test_cluster_connection/test_cluster_connection.py F                                                                           [100%]

======================================================================= FAILURES =======================================================================
_______________________________________________________________ test_cluster_connection ________________________________________________________________

artifacts_path = '/Users/framos/Desktop/artifacts'

    def test_cluster_connection(artifacts_path):
        """Verify that no worker disconnects from the master once they are connected.

        For each worker, this test looks for the first successful connection message
        in its logs. Then it looks for any failed connection attempts after the successful
        connection found above.

        Args:
            artifacts_path (str): Path where folders with cluster information can be found.
        """
        if not artifacts_path:
            pytest.fail("Parameter '--artifacts_path=<path>' is required.")

        cluster_log_files = glob(join(artifacts_path, 'worker_*', 'logs', 'cluster.log'))
        if len(cluster_log_files) == 0:
            pytest.fail(f'No files found inside {artifacts_path}.')

        for log_file in cluster_log_files:
            with open(log_file) as f:
                s = mmap(f.fileno(), 0, access=ACCESS_READ)
                # Search first successful connection message.
                conn = re.search(rb'^.*Successfully connected to master.*$', s, flags=re.MULTILINE)
                if not conn:
                    pytest.fail(f'Could not find "Sucessfully connected to master" message in the '
                                f'{node_name.search(log_file)[1]}')

                # Search if there are any connection attempts after the message found above.
                if re.search(rb'^.*Could not connect to master. Trying.*$|^.*Sucessfully connected to master.*$',
                             s[conn.end():], flags=re.MULTILINE):
                    disconnected_nodes.append(node_name.search(log_file)[1])

        if disconnected_nodes:
>           pytest.fail(f'The following nodes disconnected from master at any point:\n- ' + '\n- '.join(disconnected_nodes))
E           Failed: The following nodes disconnected from master at any point:
E           - worker_2
E           - worker_5
E           - worker_4
E           - worker_3
E           - worker_15
E           - worker_12
E           - worker_24
E           - worker_23
E           - worker_22
E           - worker_25
E           - worker_13
E           - worker_14
E           - worker_6
E           - worker_1
E           - worker_8
E           - worker_9
E           - worker_7
E           - worker_11
E           - worker_16
E           - worker_20
E           - worker_18
E           - worker_19
E           - worker_21
E           - worker_17
E           - worker_10

test_cluster_logs/test_cluster_connection/test_cluster_connection.py:47: Failed
-------------- generated html file: file:///Users/framos/Documents/Wazuh/Repositories/wazuh-qa/tests/reliability/test_cluster/report.html --------------
=============================================================== short test summary info ================================================================
FAILED test_cluster_logs/test_cluster_connection/test_cluster_connection.py::test_cluster_connection - Failed: The following nodes disconnected from ...
================================================================== 1 failed in 0.84s ===================================================================
```

</details>

Therefore, using the same artifact downloaded from [274](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/274/)

And running the same test one more time,

Results of reports are both different
[Previous report](https://github.com/wazuh/wazuh/files/12241616/report.zip)
[New report](https://github.com/wazuh/wazuh/files/12241624/report.zip)

Checking data from logs, it is possible to see that both worked with the same data (dates the same in reliability/test_cluster/test_cluster_logs/test_cluster_worker_logs_order
/test_cluster_worker_logs_order.py::test_check_logs_order_workers)

**Comment by pro-akim** [comment]
# Update
Some relevant inconsistencies were found in reliability test.
It is reported in #4386
