### ISSUE TITLE
Unable to install Wazuh

### ISSUE THREAD

**Issue by chiragnahata** [wazuh/wazuh#18013]
![image](https://github.com/wazuh/wazuh/assets/63905783/31d6a3bf-311c-498d-bafb-84ed4346c444)

**Comment by raghu-007** [comment]
same error I too have!!

**Comment by MiguelazoDS** [comment]
Hi @chiragnahata,

Check you have that python dependency

![image](https://github.com/wazuh/wazuh/assets/13010397/d73ce658-2758-4b22-ae04-e4ee11009efd)

You can install it with 

`pip3 install jsonschema`

![image](https://github.com/wazuh/wazuh/assets/13010397/3b6c7284-0512-44b4-b84e-105b023a4276)

**Comment by Dwordcito** [comment]
closed due to inactivity, thanks for being part of the community! If you continue with the problem or see fit to continue with the thread, please reopen the issue!

Thank you so much!
