### ISSUE TITLE
Release 4.6.0 - Pre-Alpha 1 - System tests

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#18016]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |           https://github.com/wazuh/wazuh/issues/17713                       |
| **Version**                          |                 4.6.0                           |
| **Release candidate #**              |               Pre-Alpha 1                             |
| **Tag**                              |                 [v4.6.0-pre-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-pre-alpha1)                          |
| **Previous system tests issue**      |                  https://github.com/wazuh/wazuh/issues/17424    

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

## Conclusion :red_circle: 

Flakiness can be observed in both tests and environments, often stemming from the variability in available resources during their launch and inadequate environment cleaning practices. However, an unexpected issue has been detected concerning the token revocation process when using the endpoint (check related issue for more information)

## Opened issues
- https://github.com/wazuh/wazuh-qa/issues/4366

**Comment by Rebits** [comment]
## Test results :large_blue_circle: 

<details><summary>Report </summary>




</details>

| | | | | | | |
|--|--|--|--|--|--|--|
| | **Test name** |  **Status** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** |
| | *One Manager Agent* | 
|1| test_fim/test_files/test_files_cud.py | :black_circle:  | 0 | 0 | 0 |
|2| test_fim/test_synchronization/test_synchronization.py | :black_circle: | 0 | 0 | 0 |  
| | *Four Manager Disconnected Node* |
|3| test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py | :black_circle: | 0 | 0 | 0 |  
| | *Agentless Cluster* |
|4| test_cluster/test_integrity_sync/test_integrity_sync.py | :black_circle: | 0 | 0 | 0 |  
|5| test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py |  :black_circle: | 0 | 0 | 0 | 
|6| test_jwt_invalidation/test_change_rbac_mode.py |  :black_circle: | 0| 0 | 0 |  
|7| test_jwt_invalidation/test_change_security_resources.py | :black_circle: | 0 | 0 | 0 |  
|8| test_jwt_invalidation/test_disconnected_nodes.py |  :black_circle: | 0 | 0 | 0 |   
|9| test_jwt_invalidation/test_revoke_endpoint.py | :black_circle: | 0  | 0 | 0 |   
|10| test_jwt_invalidation/test_update_password.py |  :black_circle: | 0 | 0 | 0 |  
| | *Enrollment Cluster* |
|10| test_cluster/test_agent_enrollment/test_agent_enrollment.py | :black_circle: |  0 | 0 | 0 |   
|11| test_cluster/test_agent_groups/test_agent_default_group_added.py | :black_circle: | 0  | 0 | 0 |  
|12| test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  |  :black_circle: | 0  | 0 | 0 |  
|13| test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py | :black_circle: |  0  | 0 | 0 |   
|14| test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py | :black_circle: | 0 | 0 | 0 |   
|15| test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py |  :black_circle: | 0  | 0 | 0 
|16| test_cluster/test_agent_groups/test_assign_agent_to_a_group.py | :black_circle: | 0 | 0 | 0 |   
|17| test_cluster/test_agent_groups/test_assign_groups_guess.py |  :black_circle: | 0  | 0 | 0 |   
|18| test_cluster/test_agent_groups/test_agent_groups.py | :black_circle: | 0 | 0 | 0 |  
|19| test_cluster/test_agent_groups/test_remove_group.py | :black_circle: | 0  | 0 | 0 | 
| | *Manager Agent* |
|20| test_active_response_log_format/test_active_response_log_format.py | :black_circle: | 0  | 0 | 0 |   
|  | *Basic Cluster*   |
|21| test_cluster/test_agent_info_sync/test_agent_info_sync.py |  :black_circle:  | 0  | 0 | 0 |   https://github.com/wazuh/wazuh-qa/issues/4332
|22| test_cluster/test_agent_key_polling/test_agent_key_polling.py |   :black_circle: | 0 | 0 | 0 |  https://github.com/wazuh/wazuh-qa/issues/4332
|23| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py |:black_circle: | 0 | 0 | 0 |  
|24| test_multigroups/test_multigroups.py | :black_circle: | 0  | 0 | 0 | 
|25| test_cluster/test_agent_groups/test_agent_groups_forced_change.py |   :black_circle: | 0  | 0 | 0 |  
| | *Big Cluster 40 Agents* |
|26| test_cluster/test_agent_groups/test_groups_sync_default.py | :black_circle: | 0 |0| 0 |   
|27| test_cluster/test_agent_groups/test_groups_sync_time.py | :black_circle: | 0 | 0 | 0 | 
| | *Basic Environment* |
|28| test_agent_auth/test_agent_auth.py | :black_circle: | 0  | 0 | 0 |
|29| test_enrollment/test_enrollment.py | :black_circle: | 0 | 0 | 0  | #16664 |

**Comment by Rebits** [comment]
- Lauched system tests of the following environments:
  - One Manager Agent
  - Four Manager Disconnected Node
  - Basic Environment tests. 
  
 Pending upload results

**Comment by Rebits** [comment]
- Relaunched Basic Cluster and Basci environment tests
- Research Enrollment Cluster failures

**Comment by roronoasins** [comment]
- Research `test_jwt_invalidation/test_revoke_endpoint.py`
  A 500 internal server error when revoking the jwt token was making the test fail

- Research `test_cluster/test_integrity_sync/test_integrity_sync.py`
  A timeout error appears when waiting for `.*Command received: b'cancel_task'.*` within the `wazuh-master` instance
  
  With a tail it never appears:
  ```
  root@wazuh-master: ~# tail -f /var/ossec/logs/cluster.log | grep "Command received: b'cancel_task"


  ```
It is required to reproduce this
