### ISSUE TITLE
Real-time file integrity monitoring started (Could not launch command No error (0))

### ISSUE THREAD

**Issue by alanshore2** [wazuh/wazuh#18012]
Wazuh 4.4.5 File Integrity

## Hey all, This continues to restart my agent, I'm not sure how to fix it. Running on Windows Server.

9 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\Teredo'
2023/07/22 20:14:29 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\PolicyAgent\Parameters\Cache'
2023/07/22 20:14:29 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx'
2023/07/22 20:14:29 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\ADOVMPPackage\Final'
2023/07/22 20:14:29 wazuh-agent: INFO: (6207): Ignore 'registry' sregex '\Enum$'
2023/07/22 20:14:29 wazuh-agent: INFO: Started (pid: 13840).
2023/07/22 20:14:29 wazuh-agent: INFO: (4102): Connected to the server ([100.79.117.77]:1514/tcp).
2023/07/22 20:14:29 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2023/07/22 20:14:29 sca: INFO: Module started.
2023/07/22 20:14:29 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2023/07/22 20:14:29 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2023/07/22 20:14:29 sca: INFO: Loaded policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml'
2023/07/22 20:14:29 sca: INFO: Starting Security Configuration Assessment scan.
2023/07/22 20:14:29 wazuh-agent: INFO: (6000): Starting daemon...
2023/07/22 20:14:29 wazuh-agent: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2023/07/22 20:14:29 wazuh-agent: INFO: (6008): File integrity monitoring scan started.
2023/07/22 20:14:29 wazuh-modulesd:syscollector: INFO: Module started.
2023/07/22 20:14:29 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/07/22 20:14:29 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml'
2023/07/22 20:14:29 rootcheck: INFO: Starting rootcheck scan.
2023/07/22 20:14:29 wazuh-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2022 Standard [Ver: 10.0.20348.1850] - Wazuh v4.4.5).
2023/07/22 20:14:29 wazuh-agent: INFO: (1951): Analyzing event log: 'Application'.
2023/07/22 20:14:29 wazuh-agent: INFO: (1951): Analyzing event log: 'Security'.
2023/07/22 20:14:29 wazuh-agent: INFO: (1951): Analyzing event log: 'System'.
2023/07/22 20:14:29 wazuh-agent: INFO: (1950): Analyzing file: 'active-response\active-responses.log'.
2023/07/22 20:14:29 wazuh-modulesd:syscollector: INFO: Evaluation finished.
 wazuh-agent: INFO: Started (pid: 13840).
2023/07/22 20:14:30 wazuh-agent: INFO: Active response command not present: 'active-response/bin/restart-ossec.sh'. Not using it on this system.
2023/07/22 20:14:30 wazuh-agent: INFO: Active response command not present: 'active-response/bin/restart-ossec.cmd'. Not using it on this system.
2023/07/22 20:14:30 wazuh-agent: INFO: Active response command not present: 'active-response/bin/restart-ossec.sh'. Not using it on this system.
2023/07/22 20:14:30 wazuh-agent: INFO: Active response command not present: 'active-response/bin/restart-ossec.cmd'. Not using it on this system.
2023/07/22 20:14:30 wazuh-agent: INFO: Active response command not present: 'active-response/bin/restart-wazuh'. Not using it on this system.
2023/07/22 20:14:34 rootcheck: INFO: Ending rootcheck scan.
2023/07/22 20:14:43 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2022.yml'
2023/07/22 20:14:43 sca: INFO: Security Configuration Assessment scan finished. Duration: 14 seconds.
2023/07/22 20:15:01 wazuh-agent: INFO: (6009): File integrity monitoring scan ended.
2023/07/22 20:15:01 wazuh-agent: INFO: (6012): Real-time file integrity monitoring started.
2023/07/22 20:15:04 wazuh-agent: ERROR: (1317): Could not launch command No error (0)
2023/07/22 20:16:07 wazuh-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2023/07/22 20:16:07 wazuh-agent: INFO: (1410): Reading authentication keys file.
2023/07/22 20:16:07 wazuh-agent: INFO: Started (pid: 9612).
2023/07/22 20:16:07 wazuh-agent: INFO: Using AES as encryption method.
2023/07/22 20:16:07 wazuh-agent: INFO: Trying to connect to server ([100.79.117.77]:1514/tcp).
2023/07/22 20:16:07 rootcheck: INFO: Started (pid: 9612).

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by jnasselle** [comment]
Hi @alanshore2 ,

Thanks for reporting this. I have a few questions in order to troubleshoot it

- Windows full version?
- OOTB configuration or custom configuration?
- Installation method?
- Fresh install or Upgrade?

Looking forward to your comments,
Nico

**Comment by jnasselle** [comment]
Hi @alanshore2,

Closed due to inactivity, please re-open this issue if decide to continue with this task.

Thanks for being part of the Wazuh Community.
