### ISSUE TITLE
Failure in test_rootcheck_endpoints of the Integration API

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#18045]
## Description

The nightly test execution failed on the 4.5.0 Integration API endpoints test, specifically the **test_rootcheck_endpoints**.

![Captura desde 2023-07-25 18-26-09](https://github.com/wazuh/wazuh/assets/96108386/790d7814-1bd3-4f40-9752-9fba47bd24b5)

It seems that the second item returned by the endpoint was missing a field (`cis`) that was expected, causing the failure.
![image](https://github.com/wazuh/wazuh/assets/96108386/4737db85-0938-4693-b97a-3433c3c0ac2f)

When calling the endpoint with the same parameters as used by the test, it returns the expected fields.

However, if the "limit=2" parameter is not included, there is an item in the total list that does not have the cis field.
![image](https://github.com/wazuh/wazuh/assets/96108386/74d20a82-fa97-45ac-9853-89ae822eef4c)

Rootcheck results are not guaranteed to contain the CIS field, so this should not be considered an error. As a consequence, the validation in the API tests should be removed to avoid the error.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
## Description 

- I was installing Insomnia and seeing the cis parameter causing the test_rootcheck_endpoints error
- I was looking and modifying code to suppress the parameter

**Comment by javiersanchz** [comment]
## Description

- I have been launching the test_rootcheck_endpoints , modifying the code to fix the bug caused by the cis parameter (deleting it still shows up in the API call, I will check it tomorrow).

**Comment by javiersanchz** [comment]
## Description 
- I have been troubleshooting mapping issues to launch the AITs.
- I have been modifying the test_rootcheck_endpoints tests and running tests.

**Comment by Selutario** [comment]
Removing this issue from release 4.5.2. Reason:
- @javiersanchz will be out of office for some days.

**Comment by javiersanchz** [comment]
## Description 

- I've been going through the problem again and looking at the changes I've made.

**Comment by javiersanchz** [comment]
## Update

It appears that the error is related to the environment:

`E   subprocess.CalledProcessError: Command 'docker inspect env_wazuh-master_1 -f '{{json .State.Health.Status}}'' returned non-zero exit status 1.`

When run locally, there are no failures related to the mentioned error. Also, with the modifications made in the issue, there shouldn't be a conflict with the failures reported by the checks.

An issue was opened regarding this on Wazuh Jenkins, informing about the problem:
https://github.com/wazuh/wazuh-jenkins/issues/5884
