### ISSUE TITLE
Engine - KVDB - Prefix Search

### ISSUE THREAD

**Issue by JorgeMarinoDev** [wazuh/wazuh#18046]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description

Enable usage of RocksDB's Prefix Search feature to drive a secondary index for keys in a single KVDB (Column Family). 
This way we could have grouped keys under certain prefix inside the same KVDB.
 
## DoD
 - [x] Initial Research and first Approach
 - [x] Modify KVDB Module
 - [x] Modify API
 - [x] Modify KVDB CLI Handler
 - [x] Check Clang format.
 - [x] Unit test 
     - [x] Create KVDB tests
     - [x] Create API tests
     - [x] Verify ctest can be run with multiple jobs. i.e. ctest -j4.
 - [ ] Memory leak analysis.
     - [ ] Thread sanitizer. 
     - [x] Valgrind.
     - [ ] Massif.
 - [x] Documentation update.
    - [x] [Design document](https://docs.google.com/document/d/125d8tpj192MNdggLcNjk_R0tQWEuhjBEmtjONHbUkHo/edit#)
    - [x] [User manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit)

**Comment by soynof** [comment]
Initial research: https://docs.google.com/document/d/1_9KVS0HFu4ws-y5skICQWUb2MYe04Kp5Ksbn9OY5jRM
