### ISSUE TITLE
Import JSON

### ISSUE THREAD

**Issue by bombasters** [wazuh/wazuh#18043]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.4.4-rev | Rules/Decoders | Error |

Tell me how I can import my own JSON file with events so that I can view it in the dashboard. It has its own fields that Wazuh does not process. I will be grateful for a prompt response. Thanks!

**Comment by nmkoremblum** [comment]
Hi Bombasters,

Do you mean that you have events in JSON format and you want Wazuh to process them?
