### ISSUE TITLE
Release 4.5.0 - Alpha 1 - Packages tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18078]
### Packages tests information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #18058                                     |
| **Version**                      | 4.5.0                                                   |
| **Release candidate**            | Alpha 1                                                     |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.5.0-alpha1          |
| **Previous packages metrics**    | #17078                                               |

---

| Status | Test              | Issue              |
| :--:   | :--               | :--:               | 
| :yellow_circle:     | Installation | #18069 |
| :yellow_circle:     | Upgrade | #18070      |
| :yellow_circle:     | SELinux | #18072      |
| :yellow_circle:     | Register | #18071     |
| :yellow_circle:     | Service  | #18073     |
| :yellow_circle:     | Specific systems | #18074     |
| :yellow_circle:    | Indexer/Dashboard | #18075        |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [ ] @teddytpc1 

---

**Comment by davidjiglesias** [comment]
LGTM!
