### ISSUE TITLE
Release 4.5.0 - Alpha 1 - E2E UX tests - Deployment on Docker

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#18081]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           | Deployment on Docker |
| **Category**            | Installation |
| **Deployment option**   | Deployment on Docker |
| **Main release issue**  | https://github.com/wazuh/wazuh/issues/18058 |
| **Release candidate #** | https://github.com/wazuh/wazuh/issues/18057 |

## Test description

Test deployment of Docker repository in both ways: _single-node and multi-node installation_.

> **Note:** Change the passwords in the process

It is necessary to follow some guidelines to execute this test manually:
- Follow the development documentation
- Must test in the operative systems in the "Test template" sheet
- Generate an event in the agent, check if the expected alert is generated by the manager, and check if it appears in the UI (end-to-end generated alert)

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. 

An extended report of the test results must be attached as a ZIP or TXT file. Please attach any documents, screenshots, or tables to the issue update with the results. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results of:
- Single-node installation can be found [here](https://github.com/wazuh/wazuh/issues/18081#issuecomment-1652272231).
- Multi-node installation can be found [here](https://github.com/wazuh/wazuh/issues/18081#issuecomment-1652450780).

The OS used were:
- ALAS 2 and ALAS 2023 - x86_64 (for central components)
- Debian 11 - ARM64 (for agents)

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴 | Change default passwords | No documentation to follow | Existing issue: wazuh/wazuh-documentation#6279 |
| 🟡 | Wazuh stack deployment using Docker (_step: Generate certificates_) | Typos and some opportunities to enhance the product | Created issue: https://github.com/wazuh/wazuh-docker/issues/911 |
| 🟡 | Wazuh stack deployment using Docker (_step: Check for errors/warnings in Wazuh Manager_) | Expected and common errors are not mentioned in the documentation | Created issue: https://github.com/wazuh/wazuh-documentation/issues/6282

## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias 
- [x] @wazuh/cicd

**Comment by mauromalara** [comment]
## Single-node deployment 🔵 

<details><summary>Install required software and set-up the environment 🟢</summary><br>

1. Increase max_map_count on your host (Linux)
```shell
# sudo sysctl -w vm.max_map_count=262144
vm.max_map_count = 262144

# sudo sysctl vm.max_map_count
vm.max_map_count = 262144
```
2. Check architecture
```shell
# uname -r
5.10.184-175.749.amzn2.x86_64
```
3. Install the Docker engine
```shell
# sudo yum update -y && sudo yum install -y docker
.
.
Installed:
  docker.x86_64 0:20.10.23-1.amzn2.0.1                                                                                                                        

Dependency Installed:
  containerd.x86_64 0:1.6.19-1.amzn2.0.1       libcgroup.x86_64 0:0.41-21.amzn2       pigz.x86_64 0:2.3.4-1.amzn2.0.1       runc.x86_64 0:1.1.7-1.amzn2      

Complete!
```
4. Start the Docker engine
```shell
# sudo systemctl start docker
```
5. Install `docker-compose`
```shell
# sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# sudo chmod +x /usr/local/bin/docker-compose

# sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# sudo docker-compose --version
Docker Compose version v2.12.2
```

</details>





<details><summary>Wazuh Docker deployment</summary><br>

1. Clone the `wazuh-docker` repository
```shell
# git clone https://github.com/wazuh/wazuh-docker.git -b v4.5.0-alpha1
```
2. Get into the `single-node` folder
```shell
# cd wazuh-docker/single-node
```
3. Generate certificates
```
# sudo docker-compose -f generate-indexer-certs.yml run --rm generator
[+] Running 1/0
 ⠿ Network single-node_default  Created                                                                                                   0.0s
[+] Running 5/5
 ⠿ generator Pulled                                                                                                                       1.7s
   ⠿ d7bfe07ed847 Pull complete                                                                                                           1.0s
   ⠿ a6023cfa8265 Pull complete                                                                                                           1.4s
   ⠿ 6135753eefe9 Pull complete                                                                                                           1.5s
   ⠿ 9aaf0dae5d3f Pull complete                                                                                                           1.5s
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26847  100 26847    0     0  2016k      0 --:--:-- --:--:-- --:--:-- 2016k
Cert tool exists in Packages bucket
26/07/2023 18:00:47 INFO: Admin certificates created.
26/07/2023 18:00:48 INFO: Wazuh indexer certificates created.
26/07/2023 18:00:48 INFO: Wazuh server certificates created.
26/07/2023 18:00:48 INFO: Wazuh dashboard certificates created.
Moving created certificates to destination directory
changing certificate permissions
Setting UID indexer and dashboard
Setting UID for wazuh manager and worker
```
4. 

</details>

**Comment by BelenValdivia** [comment]
LGTM! Please, add the reference to all opened issues and known problems in the Conclusion of the main page.

**Comment by davidjiglesias** [comment]
LGTM!

**Comment by davidcr01** [comment]
LGTM! Good job.
