### ISSUE TITLE
Release 4.5.0 - Revision 1 - Alpha 1 - Footprint Metrics - ALL-EXCEPT-SYSCHECK (6h)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18088]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #18059                                         |
| **Main footprint metrics issue #** | #18068                                         |
| **Version** | 4.5.0                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.5.0-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4202/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/monitor-manager-Test_stress_B4202_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/plots/Test_stress_B4202_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4202_manager_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/logs/ossec_Test_stress_B4202_manager_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4202_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/data/monitor-manager-Test_stress_B4202_manager-pre-release.csv)
[Test_stress_B4202_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/data/Test_stress_B4202_manager_analysisd_events.csv)
[Test_stress_B4202_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/data/Test_stress_B4202_manager_analysisd_state.csv)
[Test_stress_B4202_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_manager_centos/data/Test_stress_B4202_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/monitor-agent-Test_stress_B4202_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/Test_stress_B4202_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/Test_stress_B4202_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/Test_stress_B4202_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/plots/Test_stress_B4202_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4202_centos_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/logs/ossec_Test_stress_B4202_centos_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4202_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/data/monitor-agent-Test_stress_B4202_centos-pre-release.csv)
[Test_stress_B4202_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_centos/data/Test_stress_B4202_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/plots/monitor-agent-Test_stress_B4202_ubuntu-pre-release_Write_Ops.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4202_ubuntu_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/logs/ossec_Test_stress_B4202_ubuntu_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4202_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_ubuntu/data/monitor-agent-Test_stress_B4202_ubuntu-pre-release.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/monitor-winagent-Test_stress_B4202_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/Test_stress_B4202_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/Test_stress_B4202_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/Test_stress_B4202_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/plots/Test_stress_B4202_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4202_windows_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/logs/ossec_Test_stress_B4202_windows_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4202_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/data/monitor-winagent-Test_stress_B4202_windows-pre-release.csv)
[Test_stress_B4202_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4202-360m/B4202_agent_windows/data/Test_stress_B4202_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

**Comment by fcaffieri** [comment]
## Analysis report: Logs errors

<details><summary>Wazuh manager</summary>

Reported in: url


```
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
wazuh-modulesd:vulnerability-detector: ERROR: (5524): The 'National Vulnerability Database' feed couldn't be parsed from 'tmp/vuln-temp-fitted' file.
wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
```

</details>

<details><summary>Wazuh agent - CentOS</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.11.139]:1514/tcp': 'Connection refused'.
wazuh-agentd: ERROR: Connection socket: Connection reset by peer (104)
wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml'
wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

</details>

<details><summary>Wazuh agent - Ubuntu</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.11.139]:1514/tcp': 'Connection refused'.
wazuh-modulesd:ciscat: ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'.
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

</details>

<details><summary>Wazuh agent - Windows</summary>

Reported in: url


```

wazuh-agent: ERROR: Duplicate IP: 172.31.4.92 (from manager)
wazuh-agent: ERROR: Unable to add agent (from manager)
wazuh-agent: INFO: (1141): Glob error. Invalid pattern: 'C:\tmp\logcollector_test\date*.log' or no files found.
wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
windows/logcollectorError.log:[2023-07-26_15:19:56] [ERROR] (create_delete_logs): date-2023-07-26-5-160.log file cannot be deleted.
```

</details>

**Comment by juliamagan** [comment]
OpenSCAP related issues are:
- https://github.com/wazuh/wazuh-jenkins/issues/5399
- https://github.com/wazuh/wazuh/issues/9311

**Comment by davidjiglesias** [comment]
LGTM!
