### ISSUE TITLE
Release 4.5.0 - Revision 1 - Alpha 1 - Footprint Metrics - ALL-EXCEPT-SYSCOLLECTOR (6h)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18096]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #18059                                         |
| **Main footprint metrics issue #** | #18068                                         |
| **Version** | 4.5.0                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.5.0-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4206/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/monitor-manager-Test_stress_B4206_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/plots/Test_stress_B4206_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4206_manager_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/logs/ossec_Test_stress_B4206_manager_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4206_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/data/monitor-manager-Test_stress_B4206_manager-pre-release.csv)
[Test_stress_B4206_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/data/Test_stress_B4206_manager_analysisd_events.csv)
[Test_stress_B4206_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/data/Test_stress_B4206_manager_analysisd_state.csv)
[Test_stress_B4206_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_manager_centos/data/Test_stress_B4206_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/monitor-agent-Test_stress_B4206_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/Test_stress_B4206_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/Test_stress_B4206_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/Test_stress_B4206_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/plots/Test_stress_B4206_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4206_centos_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/logs/ossec_Test_stress_B4206_centos_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4206_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/data/monitor-agent-Test_stress_B4206_centos-pre-release.csv)
[Test_stress_B4206_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_centos/data/Test_stress_B4206_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/monitor-agent-Test_stress_B4206_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/Test_stress_B4206_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/Test_stress_B4206_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/Test_stress_B4206_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/plots/Test_stress_B4206_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4206_ubuntu_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/logs/ossec_Test_stress_B4206_ubuntu_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4206_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/data/monitor-agent-Test_stress_B4206_ubuntu-pre-release.csv)
[Test_stress_B4206_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_ubuntu/data/Test_stress_B4206_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/monitor-winagent-Test_stress_B4206_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/Test_stress_B4206_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/Test_stress_B4206_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/Test_stress_B4206_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/plots/Test_stress_B4206_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4206_windows_2023-07-26.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/logs/ossec_Test_stress_B4206_windows_2023-07-26.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4206_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/data/monitor-winagent-Test_stress_B4206_windows-pre-release.csv)
[Test_stress_B4206_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4206-360m/B4206_agent_windows/data/Test_stress_B4206_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### Graphs

No abnormal behavior was found 

### Logs

All the found errors are expected, no new errors were collected.

- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/5399
- https://github.com/wazuh/wazuh/issues/9311
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/12073
- https://github.com/wazuh/wazuh-jenkins/issues/5284
- https://github.com/wazuh/wazuh/issues/17572
- https://github.com/wazuh/wazuh-jenkins/issues/5469
- https://github.com/wazuh/wazuh-jenkins/issues/5283
- https://github.com/wazuh/wazuh-puppet/issues/706
- https://github.com/wazuh/wazuh-docker/issues/909

**Comment by fcaffieri** [comment]
## Analysis report: Logs errors

<details><summary>Wazuh manager</summary>

Reported in: url


```
ERROR: Timeout executing API request
wazuh-analysisd: ERROR: The new permissions could not be added to the JSON alert.
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
wazuh-modulesd:vulnerability-detector: ERROR: (5524): The 'National Vulnerability Database' feed couldn't be parsed from 'tmp/vuln-temp-fitted' file.
wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
```

</details>

<details><summary>Wazuh agent - CentOS</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.0.115]:1514/tcp': 'Connection refused'.
wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml'
wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
wazuh-syscheckd: ERROR: (6704): Couldn't get path of '/tmp/syscheck_test/files/fimStress.1460421'
```

</details>

<details><summary>Wazuh agent - Ubuntu</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.0.115]:1514/tcp': 'Connection refused'.
wazuh-modulesd:ciscat: ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'.
wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
wazuh-syscheckd: ERROR: (6704): Couldn't get path of '/tmp/syscheck_test/files/fimStress.1349004'
```

</details>

<details><summary>Wazuh agent - Windows</summary>

Reported in: url


```

wazuh-agent: ERROR: (6613): Real time Windows callback process: 'Access is denied.' (5).
wazuh-agent: ERROR: (6704): Couldn't get path of '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\RestrictedServices\\Configurable\\System:47d92fca-a13e-405e-ba2f-2dce501eb3aa'
wazuh-agent: ERROR: (6716): Could not open handle for 'c:\tmp\syscheck_test\files\fimstress.1004264'. Error code: 2
wazuh-agent: ERROR: GetSecurityInfo error = 0
wazuh-agent: INFO: (1141): Glob error. Invalid pattern: 'C:\tmp\logcollector_test\date*.log' or no files found.
wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
windows/fimError.log:[2023-07-26_14:09:36] [ERROR] (create_delete): files\fimStress.81414 file cannot be deleted.
```

</details>

**Comment by juliamagan** [comment]
Please add the conclusions of the graph analysis and the reported issues.

**Comment by davidjiglesias** [comment]
LGTM!
