### ISSUE TITLE
Make Authd write the metadata file for multigroups

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#1810]
## Feature request

**Compatibility**
_manager_

**Component involved**
_Authd/Framework..._

Description
--------------

When we add a group to an agent, the framework creates de metadata file doing the handling itself.We need to make an unified way for doing this, making **Authd** responsible for writing the metadata file.

**Steps**

- Make the framework write and read from an exclusive Authd socket.
- Authd reads the socket and writes the metadata file.

**Comment by vikman90** [comment]
Issue #1863 will remove the file `.metadata`.
