### ISSUE TITLE
Remove duplicated log in AWS integration after merging branches

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#18110]
## Description

[This](https://github.com/wazuh/wazuh/commit/7b1fd2c0d4f9237a04a9cd26e7b8a5ce25274ea6#diff-2515da91f432a6483ca9ff54d00de56d4ee32b54d82a9470a930f5134fb07085R3176) was included in master (which was 4.6.0):

![image](https://github.com/wazuh/wazuh/assets/23361101/5dd20690-df6f-4371-8101-24ec31fa7e83)

But it was later included in 4.5.1 [here](https://github.com/wazuh/wazuh/pull/17748/files#diff-2515da91f432a6483ca9ff54d00de56d4ee32b54d82a9470a930f5134fb07085R3307-R3308):

![image](https://github.com/wazuh/wazuh/assets/23361101/e5a701ea-97e0-4e80-b49d-a91b8ee93027)

So now, after merging 4.5.1 in 4.6.0, it is duplicated and AWS ITs will fail. It needs to be fixed for 4.6.0.

![image](https://github.com/wazuh/wazuh/assets/23361101/26f9900e-136c-4781-beab-b7af5ce19493)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

Applied the removal of the message. Analyzing if there are other messages to remove. AWS Integration Tests will be run to verify no other problems have arisen from the merge.

**Comment by fdalmaup** [comment]
# AWS Integration Tests
The `wazuh-qa` branch used for the tests was the one to be merged in https://github.com/wazuh/wazuh-qa/pull/4278 since the Wazuh `4.6.0` version contains modifications to the `AWSCloudWatchLogs` class. 
 
```bash
root@server:/wazuh# git branch
* fix/18110-remove-duplicated-logs

root@server:/wazuh# 
/var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40600"
WAZUH_TYPE="server"

root@server:/wazuh-qa# git branch
* 17388-aws-services-discard-regex-its


```
<details><summary>Results</summary>

    pytest -vvx tests/integration/test_aws/
    ====================================================================== test session starts ======================================================================
    platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.2.0 -- /usr/bin/python3
    cachedir: .pytest_cache
    metadata: {'Python': '3.10.12', 'Platform': 'Linux-5.19.0-1029-aws-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.1.2', 'pluggy': '1.2.0'}, 'Plugins': {'testinfra': '5.0.0', 'html': '3.1.1', 'metadata': '3.0.0'}}
    rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
    plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
    collected 198 items                                                                                                                                             
    
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[cloudtrail_defaults] PASSED                                                                [  0%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[vpc_defaults] PASSED                                                                       [  1%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[config_defaults] PASSED                                                                    [  1%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[alb_defaults] PASSED                                                                       [  2%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[clb_defaults] PASSED                                                                       [  2%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[nlb_defaults] PASSED                                                                       [  3%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[kms_defaults] PASSED                                                                       [  3%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[macie_defaults] PASSED                                                                     [  4%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[trusted_advisor_defaults] PASSED                                                           [  4%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[guardduty_defaults] PASSED                                                                 [  5%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[native_guardduty_defaults] PASSED                                                          [  5%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[waf_defaults] PASSED                                                                       [  6%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[server_access_defaults] PASSED                                                             [  6%]
    tests/integration/test_aws/test_basic.py::test_bucket_defaults[cisco_umbrella_defaults] PASSED                                                            [  7%]
    tests/integration/test_aws/test_basic.py::test_service_defaults[cloudwatchlogs_defaults] PASSED                                                           [  7%]
    tests/integration/test_aws/test_basic.py::test_inspector_defaults[inspector_defaults] PASSED                                                              [  8%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[cloudtrail_discard_regex] PASSED                                              [  8%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[vpc_discard_regex] PASSED                                                     [  9%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[config_discard_regex] PASSED                                                  [  9%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[alb_discard_regex] PASSED                                                     [ 10%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[clb_discard_regex] PASSED                                                     [ 10%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[nlb_discard_regex] PASSED                                                     [ 11%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[kms_discard_regex] PASSED                                                     [ 11%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[macie_discard_regex] PASSED                                                   [ 12%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[trusted_advisor_discard_regex] PASSED                                         [ 12%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[guardduty_discard_regex] PASSED                                               [ 13%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[native_guardduty_discard_regex] PASSED                                        [ 13%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[waf_discard_regex] PASSED                                                     [ 14%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[server_access_discard_regex] PASSED                                           [ 14%]
    tests/integration/test_aws/test_discard_regex.py::test_bucket_discard_regex[cisco_umbrella_discard_regex] PASSED                                          [ 15%]
    tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_json[cloudwatch_discard_regex_json] PASSED                                [ 15%]
    tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_simple_text[cloudwatch_discard_regex_simple_text] PASSED                  [ 16%]
    tests/integration/test_aws/test_discard_regex.py::test_inspector_discard_regex[inspector_discard_regex] PASSED                                            [ 16%]
    tests/integration/test_aws/test_log_groups.py::test_log_groups[cloudwatchlogs_log_groups_with_data] PASSED                                                [ 17%]
    tests/integration/test_aws/test_log_groups.py::test_log_groups[cloudwatchlogs_inexistent_log_group] PASSED                                                [ 17%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[cloudtrail_without_only_logs_after] PASSED                        [ 18%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[vpc_without_only_logs_after] PASSED                               [ 18%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[config_without_only_logs_after] PASSED                            [ 19%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[alb_without_only_logs_after] PASSED                               [ 19%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[clb_without_only_logs_after] PASSED                               [ 20%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[nlb_without_only_logs_after] PASSED                               [ 20%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[kms_without_only_logs_after] PASSED                               [ 21%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[macie_without_only_logs_after] PASSED                             [ 21%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[trusted_advisor_without_only_logs_after] PASSED                   [ 22%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[guardduty_without_only_logs_after] PASSED                         [ 22%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[native_guardduty_without_only_logs_after] PASSED                  [ 23%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[waf_without_only_logs_after] PASSED                               [ 23%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[server_access_without_only_logs_after] PASSED                     [ 24%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_without_only_logs_after[cisco_umbrella_without_only_logs_after] PASSED                    [ 24%]
    tests/integration/test_aws/test_only_logs_after.py::test_service_without_only_logs_after[cloudwatchlogs_without_only_logs_after] PASSED                   [ 25%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[cloudtrail_with_only_logs_after] PASSED                              [ 25%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[vpc_with_only_logs_after] PASSED                                     [ 26%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[config_with_only_logs_after] PASSED                                  [ 26%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[alb_with_only_logs_after] PASSED                                     [ 27%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[clb_with_only_logs_after] PASSED                                     [ 27%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[nlb_with_only_logs_after] PASSED                                     [ 28%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[kms_with_only_logs_after] PASSED                                     [ 28%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[macie_with_only_logs_after] PASSED                                   [ 29%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[trusted_avisor_with_only_logs_after] PASSED                          [ 29%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[guardduty_with_only_logs_after] PASSED                               [ 30%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[native_guardduty_with_only_logs_after] PASSED                        [ 30%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[waf_with_only_logs_after] PASSED                                     [ 31%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[server_access_with_only_logs_after] PASSED                           [ 31%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_with_only_logs_after[cisco_umbrella_with_only_logs_after] PASSED                          [ 32%]
    tests/integration/test_aws/test_only_logs_after.py::test_cloudwatch_with_only_logs_after[cloudwatchlogs_with_only_logs_after] PASSED                      [ 32%]
    tests/integration/test_aws/test_only_logs_after.py::test_inspector_with_only_logs_after[inspector_with_only_logs_after] PASSED                            [ 33%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[cloudtrail_only_logs_after_multiple_calls] PASSED                          [ 33%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[vpc_only_logs_after_multiple_calls] PASSED                                 [ 34%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[config_only_logs_after_multiple_calls] PASSED                              [ 34%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[alb_only_logs_after_multiple_calls] PASSED                                 [ 35%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[clb_only_logs_after_multiple_calls] PASSED                                 [ 35%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[nlb_only_logs_after_multiple_calls] PASSED                                 [ 36%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[kms_only_logs_after_multiple_calls] PASSED                                 [ 36%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[macie_only_logs_after_multiple_calls] PASSED                               [ 37%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[trusted_advisor_only_logs_after_multiple_calls] PASSED                     [ 37%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[guardduty_only_logs_after_multiple_calls] PASSED                           [ 38%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[native_guardduty_only_logs_after_multiple_calls] PASSED                    [ 38%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[waf_only_logs_after_multiple_calls] PASSED                                 [ 39%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[server_access_only_logs_after_multiple_calls] PASSED                       [ 39%]
    tests/integration/test_aws/test_only_logs_after.py::test_bucket_multiple_calls[cisco_umbrella_only_logs_after_multiple_calls] PASSED                      [ 40%]
    tests/integration/test_aws/test_only_logs_after.py::test_inspector_multiple_calls[inspector_only_logs_after_multiple_calls] XFAIL                         [ 40%]
    tests/integration/test_aws/test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls] PASSED                  [ 41%]
    tests/integration/test_aws/test_parser.py::test_bucket_and_service_missing[parser_bucket_and_service_missing] PASSED                                      [ 41%]
    tests/integration/test_aws/test_parser.py::test_type_missing_in_bucket[parser_type_missing_in_bucket] PASSED                                              [ 42%]
    tests/integration/test_aws/test_parser.py::test_type_missing_in_service[parser_type_missing_in_service] PASSED                                            [ 42%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_type_in_bucket] PASSED                                                [ 43%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_name_in_bucket] PASSED                                                [ 43%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_only_logs_after_in_bucket] PASSED                                     [ 44%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_regions_in_bucket] PASSED                                             [ 44%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_path_in_bucket] PASSED                                                [ 45%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_bucket[parser_empty_path_suffix_in_bucket] PASSED                                         [ 45%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_service[parser_empty_type_in_service] PASSED                                              [ 46%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_service[parser_empty_log_groups_in_service] PASSED                                        [ 46%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_service[parser_empty_only_logs_after_in_service] PASSED                                   [ 47%]
    tests/integration/test_aws/test_parser.py::test_empty_values_in_service[parser_empty_regions_in_service] PASSED                                           [ 47%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_type_in_bucket] PASSED                                            [ 48%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_name_in_bucket] PASSED                                            [ 48%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_only_logs_after_in_bucket] PASSED                                 [ 49%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_regions_in_bucket] PASSED                                         [ 50%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_in_bucket] PASSED                                            [ 50%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_path_suffix_in_bucket] PASSED                                     [ 51%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_bucket[parser_invalid_remove_from_bucket_in_bucket] PASSED                              [ 51%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_service[parser_invalid_type_in_service] PASSED                                          [ 52%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_service[parser_invalid_log_groups_in_service] PASSED                                    [ 52%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_service[parser_invalid_only_logs_after_in_service] PASSED                               [ 53%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_service[parser_invalid_regions_in_service] PASSED                                       [ 53%]
    tests/integration/test_aws/test_parser.py::test_invalid_values_in_service[parser_invalid_remove_log_stream_in_service] PASSED                             [ 54%]
    tests/integration/test_aws/test_parser.py::test_multiple_bucket_and_service_tags[parser_mutiple_bucket_and_service_tags] PASSED                           [ 54%]
    tests/integration/test_aws/test_path.py::test_path[cloudtrail_path_with_data] PASSED                                                                      [ 55%]
    tests/integration/test_aws/test_path.py::test_path[cloudtrail_path_without_data] PASSED                                                                   [ 55%]
    tests/integration/test_aws/test_path.py::test_path[cloudtrail_inexistent_path] PASSED                                                                     [ 56%]
    tests/integration/test_aws/test_path.py::test_path[vpc_path_with_data] PASSED                                                                             [ 56%]
    tests/integration/test_aws/test_path.py::test_path[vpc_path_without_data] PASSED                                                                          [ 57%]
    tests/integration/test_aws/test_path.py::test_path[cisco_umbrella_path_with_data] PASSED                                                                  [ 57%]
    tests/integration/test_aws/test_path.py::test_path[cisco_umbrella_path_without_data] PASSED                                                               [ 58%]
    tests/integration/test_aws/test_path.py::test_path[vpc_inexistent_path] PASSED                                                                            [ 58%]
    tests/integration/test_aws/test_path.py::test_path[config_path_with_data] PASSED                                                                          [ 59%]
    tests/integration/test_aws/test_path.py::test_path[config_path_without_data] PASSED                                                                       [ 59%]
    tests/integration/test_aws/test_path.py::test_path[config_inexistent_path] PASSED                                                                         [ 60%]
    tests/integration/test_aws/test_path.py::test_path[alb_path_with_data] PASSED                                                                             [ 60%]
    tests/integration/test_aws/test_path.py::test_path[alb_path_without_data] PASSED                                                                          [ 61%]
    tests/integration/test_aws/test_path.py::test_path[alb_inexistent_path] PASSED                                                                            [ 61%]
    tests/integration/test_aws/test_path.py::test_path[clb_path_with_data] PASSED                                                                             [ 62%]
    tests/integration/test_aws/test_path.py::test_path[clb_path_without_data] PASSED                                                                          [ 62%]
    tests/integration/test_aws/test_path.py::test_path[clb_inexistent_path] PASSED                                                                            [ 63%]
    tests/integration/test_aws/test_path.py::test_path[nlb_path_with_data] PASSED                                                                             [ 63%]
    tests/integration/test_aws/test_path.py::test_path[nlb_path_without_data] PASSED                                                                          [ 64%]
    tests/integration/test_aws/test_path.py::test_path[nlb_inexistent_path] PASSED                                                                            [ 64%]
    tests/integration/test_aws/test_path.py::test_path[kms_path_with_data] PASSED                                                                             [ 65%]
    tests/integration/test_aws/test_path.py::test_path[kms_path_without_data] PASSED                                                                          [ 65%]
    tests/integration/test_aws/test_path.py::test_path[kms_inexistent_path] PASSED                                                                            [ 66%]
    tests/integration/test_aws/test_path.py::test_path[macie_path_with_data] PASSED                                                                           [ 66%]
    tests/integration/test_aws/test_path.py::test_path[macie_path_without_data] PASSED                                                                        [ 67%]
    tests/integration/test_aws/test_path.py::test_path[macie_inexistent_path] PASSED                                                                          [ 67%]
    tests/integration/test_aws/test_path.py::test_path[trusted_advisor_path_with_data] PASSED                                                                 [ 68%]
    tests/integration/test_aws/test_path.py::test_path[trusted_advisor_path_without_data] PASSED                                                              [ 68%]
    tests/integration/test_aws/test_path.py::test_path[trusted_advisor_inexistent_path] PASSED                                                                [ 69%]
    tests/integration/test_aws/test_path.py::test_path[guardduty_path_with_data] PASSED                                                                       [ 69%]
    tests/integration/test_aws/test_path.py::test_path[guardduty_path_without_data] PASSED                                                                    [ 70%]
    tests/integration/test_aws/test_path.py::test_path[guardduty_inexistent_path] PASSED                                                                      [ 70%]
    tests/integration/test_aws/test_path.py::test_path[native_guardduty_path_with_data] PASSED                                                                [ 71%]
    tests/integration/test_aws/test_path.py::test_path[native_guardduty_path_without_data] PASSED                                                             [ 71%]
    tests/integration/test_aws/test_path.py::test_path[native_guardduty_inexistent_path] PASSED                                                               [ 72%]
    tests/integration/test_aws/test_path.py::test_path[waf_path_with_data] PASSED                                                                             [ 72%]
    tests/integration/test_aws/test_path.py::test_path[waf_path_without_data] PASSED                                                                          [ 73%]
    tests/integration/test_aws/test_path.py::test_path[waf_inexistent_path] PASSED                                                                            [ 73%]
    tests/integration/test_aws/test_path.py::test_path[server_access_path_with_data] PASSED                                                                   [ 74%]
    tests/integration/test_aws/test_path.py::test_path[server_access_path_without_data] PASSED                                                                [ 74%]
    tests/integration/test_aws/test_path.py::test_path[server_access_inexistent_path] PASSED                                                                  [ 75%]
    tests/integration/test_aws/test_path.py::test_path[cisco_umbrella_inexistent_path] PASSED                                                                 [ 75%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[cloudtrail_path_suffix_with_data] PASSED                                                 [ 76%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[cloudtrail_path_suffix_without_data] PASSED                                              [ 76%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[cloudtrail_inexistent_path_suffix] PASSED                                                [ 77%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[vpc_path_suffix_with_data] PASSED                                                        [ 77%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[config_path_suffix_with_data] PASSED                                                     [ 78%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[vpc_path_suffix_without_data] PASSED                                                     [ 78%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[config_path_suffix_without_data] PASSED                                                  [ 79%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[vpc_inexistent_path_suffix] PASSED                                                       [ 79%]
    tests/integration/test_aws/test_path_suffix.py::test_path_suffix[config_inexistent_path_suffix] PASSED                                                    [ 80%]
    tests/integration/test_aws/test_regions.py::test_regions[cloudtrail_region_with_data] PASSED                                                              [ 80%]
    tests/integration/test_aws/test_regions.py::test_regions[cloudtrail_regions_with_data] PASSED                                                             [ 81%]
    tests/integration/test_aws/test_regions.py::test_regions[cloudtrail_inexistent_region] PASSED                                                             [ 81%]
    tests/integration/test_aws/test_regions.py::test_regions[vpc_region_with_data] PASSED                                                                     [ 82%]
    tests/integration/test_aws/test_regions.py::test_regions[config_region_with_data] PASSED                                                                  [ 82%]
    tests/integration/test_aws/test_regions.py::test_regions[alb_region_with_data] PASSED                                                                     [ 83%]
    tests/integration/test_aws/test_regions.py::test_regions[vpc_regions_with_data] PASSED                                                                    [ 83%]
    tests/integration/test_aws/test_regions.py::test_regions[config_regions_with_data] PASSED                                                                 [ 84%]
    tests/integration/test_aws/test_regions.py::test_regions[alb_regions_with_data] PASSED                                                                    [ 84%]
    tests/integration/test_aws/test_regions.py::test_regions[vpc_inexistent_region] PASSED                                                                    [ 85%]
    tests/integration/test_aws/test_regions.py::test_regions[config_inexistent_region] PASSED                                                                 [ 85%]
    tests/integration/test_aws/test_regions.py::test_regions[alb_inexistent_region] PASSED                                                                    [ 86%]
    tests/integration/test_aws/test_regions.py::test_regions[clb_region_with_data] PASSED                                                                     [ 86%]
    tests/integration/test_aws/test_regions.py::test_regions[clb_regions_with_data] PASSED                                                                    [ 87%]
    tests/integration/test_aws/test_regions.py::test_regions[clb_inexistent_region] PASSED                                                                    [ 87%]
    tests/integration/test_aws/test_regions.py::test_regions[nlb_region_with_data] PASSED                                                                     [ 88%]
    tests/integration/test_aws/test_regions.py::test_regions[nlb_regions_with_data] PASSED                                                                    [ 88%]
    tests/integration/test_aws/test_regions.py::test_regions[nlb_inexistent_region] PASSED                                                                    [ 89%]
    tests/integration/test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_region_with_data] PASSED                                               [ 89%]
    tests/integration/test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_regions_with_data] PASSED                                              [ 90%]
    tests/integration/test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_inexistent_region] PASSED                                              [ 90%]
    tests/integration/test_aws/test_regions.py::test_inspector_regions[inspector_region_with_data] PASSED                                                     [ 91%]
    tests/integration/test_aws/test_regions.py::test_inspector_regions[inspector_regions_with_data] PASSED                                                    [ 91%]
    tests/integration/test_aws/test_regions.py::test_inspector_regions[inspector_inexistent_region] PASSED                                                    [ 92%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[cloudtrail_remove_from_bucket] PASSED                                      [ 92%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[vpc_remove_from_bucket] PASSED                                             [ 93%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[config_remove_from_bucket] PASSED                                          [ 93%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[alb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region) [ 94%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[clb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region) [ 94%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[nlb_remove_from_bucket] SKIPPED (ALB, CLB and NLB integrations are removing older logs from other region) [ 95%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[kms_remove_from_bucket] PASSED                                             [ 95%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[macie_remove_from_bucket] PASSED                                           [ 96%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[trusted_advisor_remove_from_bucket] PASSED                                 [ 96%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[guardduty_remove_from_bucket] PASSED                                       [ 97%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[native_guardduty_remove_from_bucket] PASSED                                [ 97%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[waf_remove_from_bucket] PASSED                                             [ 98%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[server_access_remove_from_bucket] PASSED                                   [ 98%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_from_bucket[cisco_umbrella_remove_from_bucket] PASSED                                  [ 99%]
    tests/integration/test_aws/test_remove_from_bucket.py::test_remove_log_stream[cloudwatchlogs_remove_from_bucket] PASSED                                   [100%]
    
    ==================================================== 194 passed, 3 skipped, 1 xfailed in 4063.18s (1:07:43) =====================================================


</details>
