### ISSUE TITLE
Release 4.5.0 - Alpha 1 - Integration tests

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#18114]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `v4.5.0-alpha1`| https://github.com/wazuh/wazuh-qa/commit/ede149c9ab767d23d3d4f9ca461186dc660e45a6 | `v4.5.0-alpha1`  |https://github.com/wazuh/wazuh/commit/39df1e74bfd035fea8948191ae195fc17eb7e2f3  |

We are going to check that the integration tests of the `4.5`  branch of `wazuh-qa` work correctly using the [v4.5.0-alpha1](https://github.com/wazuh/wazuh/tree/v4.5.0-alpha1) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/18058

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|:large_blue_circle:|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🟢</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🟢</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;">🟢 </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🟢</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🟢</td>
<td style="width: 97px;">🟢</td>
<td style="width: 97px;" colspan="2">🟢</td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🟢</td>
<td style="width: 97px;">🟢</td>
<td style="width: 97px;" colspan="2">🔴</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;">🔴</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">🟢</td>
<td style="width: 99px;">🟢</td>
<td style="width: 79px;">🔴</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">🟢</td>
</tr>
</tbody>
</table>

## Evidence
**IT Launcher build**:  https://ci.wazuh.info/job/Test_integration_launcher/180/

## Conclusion :red_circle: 

Some tests failed, and a known issue was reported

- https://github.com/wazuh/wazuh-qa/issues/4230

leading to the creation of some new issues.

- https://github.com/wazuh/wazuh-jenkins/issues/5468
- https://github.com/wazuh/wazuh-qa/issues/4370

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias
- [ ] @jnasselle

**Comment by roronoasins** [comment]
Some of them failed. After a quick review a few are expected(vd, logcollector, syscollector). Tomorrow all the reports will be added

**Comment by roronoasins** [comment]
# FIM :red_circle:  
  
## Agent
 
### Details

**Build**: https://ci.wazuh.info/job/Test_integration/41715/
**Report**:  

**Failed tests**: 
 - `test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py::test_realtime_unsupported[get_configuration0]`
 
**Issue**: 
- https://github.com/wazuh/wazuh-qa/issues/2881

### Description

The `test_execd_firewall_drop` test aims to verify if the current OS platform falls to the 'scheduled' mode when 'realtime' is not available. To achieve this, the test performs a CUD set of operations to a file with 'realtime' mode set as, but the test fails due to a TimeoutError.

```
        regular_file_cud(directory_str, log_monitor, file_list=[test_file], time_travel=False, triggers_event=True,
>                        event_mode="scheduled", min_timeout=15)

test_fim/test_files/test_basic_usage/test_basic_usage_realtime_unsupported.py:144: 
```

```
                        logger.error(error_message)
                        logger.error(f"Results accumulated: "
                                     f"{len(result) if isinstance(result, list) else 0}")
                        logger.error(f"Results expected: {accum_results}")
>                   raise TimeoutError(error_message)
E                   TimeoutError: TimeoutError was raised because a single 'added' event was expected for ['/dir/testfile.txt'] but was not detected.
```

**Comment by roronoasins** [comment]
# Logcollector :orange_circle:  
  
## Agent
 
### Details

**Build**: https://ci.wazuh.info/job/Test_integration/41720/
**Report**:  

**Issue**: 
- https://github.com/wazuh/wazuh-jenkins/issues/5464

### Description

The wazuh-qa repo is not installed as expected during the Test_Integration pipe run

**Comment by roronoasins** [comment]
# Vulnerability Detector :red_circle:  
  
## Manager
 
### Details

**Build**: https://ci.wazuh.info/job/Test_integration/41727/
**Report**:  [manager_html_report_Test_integration_B41727_20230727102433.zip](https://github.com/wazuh/wazuh/files/12193014/manager_html_report_Test_integration_B41727_20230727102433.zip)

**Failed tests**: 
- `test_vulnerability_detector/test_feeds/test_download_feeds.py`
    - `SUSE Linux Enterprise Server 11`
    - `SUSE Linux Enterprise Server 12`
    - `SUSE Linux Enterprise Server 15`
    - `SUSE Linux Enterprise Desktop 15`
 
**Issue**: 
- https://github.com/wazuh/wazuh-qa/issues/4370

### Description

The `test_execd_firewall_drop` test aims to verify if modulesd downloads successfully the feeds from different providers and os, and check that. the feed update date does not exceed a set limit. A timeout is raised like

```
>                   raise TimeoutError(error_message)
E                   TimeoutError: Could not find SUSE Linux Enterprise Server 12 feed finished log                  TimeoutError: TimeoutError was raised because a single 'added' event was expected for ['/dir/testfile.txt'] but was not detected.
```



It could be related to a download that exceeds the timeout

**Comment by roronoasins** [comment]
# Syscollector :orange_circle: 

Same as https://github.com/wazuh/wazuh/issues/18005#issuecomment-1647534916

### Details
**Build** https://ci.wazuh.info/job/Test_integration/41729/ https://ci.wazuh.info/job/Test_integration/41705/
**Issue**:
- https://github.com/wazuh/wazuh-jenkins/issues/5436


### Description

Syscollector IT module is not supported for 4.5.0

**Comment by pro-akim** [comment]
# Update
Moved to on hold, 
Will be retested. Pipeline was launched with Jenkins_reference in master

**Comment by pro-akim** [comment]
LGTM

**Comment by davidjiglesias** [comment]
The conclusion is not updated in the main page. This is mandatory so the reviews can be performed in a fast and efficient manner.

**Comment by davidjiglesias** [comment]
LGTM!
