### ISSUE TITLE
Release 4.5.0 - Alpha 1 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#18113]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |https://github.com/wazuh/wazuh/issues/18058|
| **Version**                                   |4.5.0|
| **Release candidate #**                       |Alpha 1|
| **Tag**                                       |[v4.5.0-alpha1](https://github.com/wazuh/wazuh/tree/v4.5.0-alpha1)|
| **Previous Workload benchmarks metrics issue**|https://github.com/wazuh/wazuh/issues/16975|

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|50000|25|

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/18113#issuecomment-1657894781).

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario

**Comment by Selutario** [comment]
[Report]()

## API performance results

---
|                                  |                                            |                                           |            
|--|--|--|
| **Endpoint test name**  | **Status** | **Issues Ref.** |
| GET /cluster/local/info | :green_circle: | |
| GET /cluster/nodes| :green_circle:  | |
| GET /cluster/healthcheck | :green_circle: | |
| GET /cluster/status | :green_circle: | |
| GET /cluster/local/config | :green_circle: | |
| GET /cluster/api/config | :green_circle: | |
| GET /cluster/configuration/validation | :green_circle: | |
| GET /manager/status | :green_circle: | |
| GET /manager/info | :green_circle: | |
| GET /manager/configuration | :green_circle: | |
| GET /manager/logs | :green_circle: | |
| GET /manager/api/config | :green_circle: | |
| GET /manager/configuration/validation | :green_circle: | |
| GET /mitre/groups | :green_circle: | |
| GET /mitre/metadata | :green_circle: | |
| GET /mitre/mitigations | :green_circle: | |
| GET /mitre/references | :green_circle: | |
| GET /mitre/software | :green_circle: | |
| GET /mitre/tactics | :green_circle: | |
| GET /mitre/techniques | :green_circle: | |
| GET /overview/agents | :green_circle:  | |
| GET /tasks/status | :green_circle: | |
| PUT /active-response | :yellow_circle: | https://github.com/wazuh/wazuh-qa/issues/1266 |
| PUT /rootcheck | :green_circle: | |
| PUT /syscheck | :green_circle: | |
| POST /groups | :green_circle: | |
| POST /security/users | :green_circle: | |
| POST /security/roles | :green_circle: | |
| POST /security/policies | :green_circle: | |
| POST /security/rules | :green_circle: | |
| PUT /agents/group | :yellow_circle: | Endpoint is not being tested (https://github.com/wazuh/wazuh-qa/issues/3665). This related issue was opened in the past: https://github.com/wazuh/wazuh/issues/13872 |
| PUT /agents/group/new_test_group/restart | :green_circle: | |
| PUT /agents/restart | :green_circle: |  |
| POST /agents | :green_circle: | |
| POST /agents/insert​|  :green_circle: | |
| POST /agents/insert​/quick | :green_circle: | |
| GET /agents | :green_circle: | |
| GET /agents/no_group | :green_circle: | |
| GET /agents/outdated | :green_circle: | |
| GET /decoders | :green_circle: | |
| GET /groups | :green_circle: | |
| GET /lists | :green_circle: | |
| GET /rules | :green_circle: | |
| GET /security/users | :green_circle: | |
| GET /security/roles | :green_circle: | |
| GET /security/policies | :green_circle: | |
| GET /security/rules | :green_circle: | |
| DELETE /groups | :green_circle: | |
| DELETE /agents | :green_circle: | |
| DELETE /security/users | :green_circle: | |
| DELETE /security/roles | :green_circle: | |
| DELETE /security/policies | :green_circle: | |
| DELETE /security/rules | :green_circle: | |
| PUT /manager/restart | :green_circle: | |
| PUT /cluster/restart | :green_circle: | |

## Cluster

There is only one error in the cluster logs:
```
2023/07/28 15:06:58 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B280_manager_1] [Integrity sync] Found errors: 0 overwriting, 0 creating and 1 removing
```

There is already a fix for the error, which will be released in v4.6.0:
- https://github.com/wazuh/wazuh/issues/15983

Also, cluster synchronization seems to be working correctly and the `Agent-groups send full` task has not been triggered. Most of the agents were connected at some point as it can be seen in the coordinator logs below (~49500 out of 50k):
```
2023/07/28 14:57:17 DEBUG:    [Main]      Current backend stats: {'CLUSTER-Workload_benchmarks_metrics_B280_manager_1': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_3': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_11': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_18': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_22': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_6': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_14': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_10': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_4': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_12': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_13': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_15': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_9': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_16': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_23': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_21': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_24': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_20': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_17': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_5': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_19': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_7': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_8': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_2': 1980, 'CLUSTER-Workload_benchmarks_metrics_B280_manager_25': 1980}
```

They were active and sending info, the master was receiving 30 chunks of data per worker:
```
2023/07/28 15:06:54 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B280_manager_17] [Agent-info sync] Finished in 1.059s. Updated 30 chunks.
2023/07/28 15:06:55 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B280_manager_24] [Agent-info sync] Finished in 1.092s. Updated 30 chunks.
2023/07/28 15:06:55 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B280_manager_5] [Agent-info sync] Finished in 1.287s. Updated 30 chunks.
2023/07/28 15:06:55 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B280_manager_19] [Agent-info sync] Finished in 1.263s. Updated 30 chunks.
```

**Comment by Selutario** [comment]
## Cluster tasks 

Cluster tasks duration looks good:
```JSON
{
    "setup_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_17", 0.11050714285714285),
                    "max": ("worker_5", 1.665),
                },
                "master": {
                    "mean": ("master", 0.006150457665903892),
                    "max": ("master", 0.131),
                },
            }
        },
        "integrity_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_1", 0.038142857142857145),
                    "max": ("worker_19", 0.095),
                },
                "master": {
                    "mean": ("master", 0.2447886550777676),
                    "max": ("master", 1.702),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_16", 0.20836290322580645),
                    "max": ("worker_14", 1.841),
                },
                "master": {
                    "mean": ("master", 0.09664717741935484),
                    "max": ("master", 1.287),
                },
            }
        },
    },
    "stable_phase": {
        "integrity_check": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_1", 0.009072727272727274),
                    "max": ("worker_3", 0.011),
                },
                "master": {
                    "mean": ("master", 0.0035047204066811916),
                    "max": ("master", 0.005),
                },
            }
        },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_4", 0.0019400000000000003),
                    "max": ("worker_8", 0.023),
                },
                "master": {"mean": ("master", 0.002), "max": ("master", 0.002)},
            }
        },
    },
}
```

**Comment by davidjiglesias** [comment]
LGTM!
