### ISSUE TITLE
Release 4.5.0 - Alpha 1 - Shuffle Integration Testing

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#18121]
# Shuffle integration testing

## Modules tests information
|                                      |                                                |
|--------------------------------------|------------------------------------------------|
| **Main module tests issue**          | #18066                                        |
| **Version**                          | 4.5.0                                          |
| **Release candidate #**              | Alpha 1 |
| **Tag**                              | [v4.5.0-alpha1](https://github.com/wazuh/wazuh/tree/v4.5.0-alpha1)       |
| **Previous modules tests issue**     | -                                         |

## Test report procedure

All test results must have one the following statuses: 
|                 |                                                                         |
|-----------------|-------------------------------------------------------------------------|
| :green_circle: | The test passed successfully.                                            |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the [Release 4.5.0 project](https://github.com/orgs/wazuh/projects/41/) for triage.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

Every test will be performed on a Manager unless otherwise specified.

## Test results
| Test | Result | Issue ref. |
|------|--------|------------|
| Test using ossec.conf in a manager | :green_circle:   | - |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @Selutario
- [x] @fdalmaup

**Comment by fdalmaup** [comment]
# Test Results

The test assumes there is a functional Shuffle instance with an available webhook.

A test is considered valid if the following conditions are met:

- The expected result described in the test itself is met.
- The expected output was present in the `{wazuh_path}/logs/integrations.log` and `{wazuh_path}/logs/ossec.log` file.


## Test using ossec.conf in a manager

The following configuration has to be added to `ossec.conf`
```
<integration>
     <name>shuffle</name>
     <hook_url>http://<IP>:3001/api/v1/hooks/<HOOK_ID></hook_url>
     <level>3</level>
     <alert_format>json</alert_format>
 </integration>
```

Also, the configuration `integrator.debug=2` to `local_internal_options.conf `.

Restart the Wazuh Manager.

<details><summary>ossec.log</summary>
    
    2023/07/28 16:51:51 wazuh-integratord[25242] integrator.c:142 at OS_IntegratorD(): DEBUG: sending new alert.
    2023/07/28 16:51:51 wazuh-integratord[25242] integrator.c:276 at OS_IntegratorD(): DEBUG: file /tmp/shuffle-1690563111--571810694.alert was written.
    2023/07/28 16:51:51 wazuh-integratord[25242] integrator.c:403 at OS_IntegratorD(): DEBUG: Running: integrations /tmp/shuffle-1690563111--571810694.alert  http://<IP>:3001/api/v1/hooks/<HOOK_ID> debug
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # Starting
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # Webhook
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: http://<IP>:3001/api/v1/hooks/<HOOK_ID>
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # File location
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: /tmp/shuffle-1690563111--571810694.alert
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # Processing alert
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: {'timestamp': '2023-07-28T16:51:50.919+0000', 'rule': {'level': 3, 'description': 'Wazuh server started.', 'id': '502', 'firedtimes': 1, 'mail': False, 'groups': ['ossec'], 'pci_dss': ['10.6.1'], 'gpg13': ['10.1'], 'gdpr': ['IV_35.7.d'], 'hipaa': ['164.312.b'], 'nist_800_53': ['AU.6'], 'tsc': ['CC7.2', 'CC7.3']}, 'agent': {'id': '000', 'name': '7c0d1a61a137'}, 'manager': {'name': '7c0d1a61a137'}, 'id': '1690563110.733094', 'full_log': 'ossec: Manager started.', 'decoder': {'name': 'ossec'}, 'location': 'wazuh-monitord'}
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # Generating message
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: {"severity": 1, "pretext": "WAZUH Alert", "title": "Wazuh server started.", "text": "ossec: Manager started.", "rule_id": "502", "timestamp": "2023-07-28T16:51:50.919+0000", "id": "1690563110.733094", "all_fields": {"timestamp": "2023-07-28T16:51:50.919+0000", "rule": {"level": 3, "description": "Wazuh server started.", "id": "502", "firedtimes": 1, "mail": false, "groups": ["ossec"], "pci_dss": ["10.6.1"], "gpg13": ["10.1"], "gdpr": ["IV_35.7.d"], "hipaa": ["164.312.b"], "nist_800_53": ["AU.6"], "tsc": ["CC7.2", "CC7.3"]}, "agent": {"id": "000", "name": "7c0d1a61a137"}, "manager": {"name": "7c0d1a61a137"}, "id": "1690563110.733094", "full_log": "ossec: Manager started.", "decoder": {"name": "ossec"}, "location": "wazuh-monitord"}}
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # Sending message
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # In send msg
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:412 at OS_IntegratorD(): DEBUG: integratord: Fri Jul 28 16:51:51 UTC 2023: # After send msg: <Response [200]>
    2023/07/28 16:51:52 wazuh-integratord[25242] integrator.c:425 at OS_IntegratorD(): DEBUG: Command ran successfully.

</details>


### Conclusions
The integration works as expected, sending the alerts to Shuffle.

**Comment by davidjiglesias** [comment]
LGTM!
