### ISSUE TITLE
Python from 4.4.2 remains in the following versions

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#18123]
|Wazuh version|Component|
|---|---|
|4.5.0-40500 |Framework |

## Description

During the execution of the system tests in [4.4.5 - Alpha 1](https://github.com/wazuh/wazuh/issues/18061), it was found that the `test_integrity_sync` test was failing. This test checks the size of the files to be synchronized and waits for the next message:

```
E                   TimeoutError: Did not found the expected callback in wazuh-master: .*File too large to be synced: /var/ossec/etc/rules/test_file_too_bige
```

The problem comes from the fact that when the test looks for the `cluster.json` file inside `/var/ossec/framework/python` it finds the following two:

```
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.5.0-py3.9.egg/wazuh/core/cluster/cluster.json
```

The test modifies the first one it finds, the one in 4.4.2, so the necessary configuration is not applied. 

We should fix this so that each version has its own python and not previous ones.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Is this something that reproduces in v4.4.3-v4.4.5?

**Comment by juliamagan** [comment]
Yes, this also happens in v4.4.3-v4.4.5:

```
root@wazuh-master: ~# find /var/ossec/ -name cluster.json
/var/ossec/framework/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.3-py3.9.egg/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/cluster.json
```

```
root@wazuh-master: ~# find /var/ossec/ -name cluster.json
/var/ossec/framework/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.4-py3.9.egg/wazuh/core/cluster/cluster.json
```

```
root@wazuh-master: ~# find /var/ossec/ -name cluster.json
/var/ossec/framework/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.5-py3.9.egg/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.2-py3.9.egg/wazuh/core/cluster/cluster.json
```

**Comment by EduLeon12** [comment]
## Issue Update

amd package file has already been created and tested currently testing aarch to ensure packages are ready to be uploaded.

**Comment by davidjiglesias** [comment]
LGTM!

We updated DEPS 20 and the results look good:

![image](https://github.com/wazuh/wazuh/assets/48716145/ca5817a6-25eb-4cac-b659-004fd406fb06)
