### ISSUE TITLE
Add integration test for Microsoft graph integration

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#18132]
### Description

This issue focuses on enhancing the codebase of MSGraph by introducing integration tests that will validate the functionality of the module in a real-world scenario. The goal is to ensure the proper integration of MSGraph with external components and to catch any potential issues that may arise when interacting with other services or dependencies. These integration tests will be automated using GitHub Actions, allowing for continuous testing and validation.

### Integration Tests

Integration tests are designed to evaluate the interoperability of MSGraph with external systems and services. The tests will simulate real-world scenarios where MSGraph interacts with various components to perform its functionalities. Examples of integration test scenarios include:

- Configuration
- Making API calls to external APIs and verifying the responses.

### Test Suite Similar to #17666

The integration test suite will be inspired by the tests recently added in issue #17666. The structure and approach of those tests will be used as a reference to create the new integration tests for MSGraph. The lessons learned from that issue will be leveraged to improve the test coverage and effectiveness for MSGraph.

**Comment by Dwordcito** [comment]
# Use Cases

### Use Case 1: Retrieval of Future Events
- **Primary Actor**: Event Scheduling System
- **Precondition**: The system is enabled and the 'only_future_events' setting is on 'yes'.
- **Main Flow**: The system correctly requests and retrieves future events from the Microsoft Graph API and manages them as expected.

### Use Case 2: API Authentication
- **Primary Actor**: API Authentication System
- **Precondition**: The API authentication credentials ('client_id', 'tenant_id', 'secret_value') are valid.
- **Main Flow**: The system successfully authenticates with the Microsoft Graph API using the provided credentials.

### Use Case 3: Execution at Start Based on Configuration
- **Primary Actor**: System Initialization
- **Precondition**: 'run_on_start' is set to 'yes'.
- **Main Flow**: When the system starts, predefined actions based on the 'run_on_start' setting are executed and the system starts operations successfully.

### Use Case 4: Non-Execution at Start Based on Configuration
- **Primary Actor**: System Initialization
- **Precondition**: 'run_on_start' is set to 'no'.
- **Main Flow**: When the system starts, the predefined actions based on the 'run_on_start' setting are not executed, and the system starts without performing those operations.

### Use Case 5: Exceeding Maximum Request Size
- **Primary Actor**: Data Sending System
- **Precondition**: The size of the request exceeds the limit specified in 'curl_max_size'.
- **Main Flow**: The system attempts to send a request to the Microsoft Graph API, but the operation fails because the request size exceeds the maximum limit.

### Use Case 6: Retrieval of Events When System Is Disabled
- **Primary Actor**: Event Scheduling System
- **Precondition**: The 'enabled' setting is on 'no'.
- **Main Flow**: The module not start.

### Use Case 7: API Authentication with Invalid Credentials
- **Primary Actor**: API Authentication System
- **Precondition**: One or more of the API authentication credentials ('client_id', 'tenant_id', 'secret_value') are invalid.
- **Main Flow**: The system attempts to authenticate with the Microsoft Graph API using the provided credentials, but fails due to invalid credentials.

### Use Case 8: Using an Incorrect API Version
- **Primary Actor**: API Authentication System
- **Precondition**: The API version indicated in 'version' is incorrect or incompatible.
- **Main Flow**: The system attempts to connect to the Microsoft Graph API using the specified version, but the connection fails due to an incompatible version.

### Use Case 9: Retrieval of All Events
- **Primary Actor**: Event Scheduling System
- **Precondition**: The system is enabled and the 'only_future_events' setting is on 'no'.
- **Main Flow**: The system correctly requests and retrieves all events (past, present, future) from the Microsoft Graph API and manages them as expected.

### Use Case 10: Security Resource Interaction
- **Primary Actor**: Security Management System
- **Precondition**: The 'resource' setting includes the 'security' name.
- **Main Flow**: The system correctly interacts with the 'security' resource through the Microsoft Graph API, successfully retrieving the related 'alerts_v2' and 'incidents' information.

### Use Case 11: Incorrect Resource Interaction
- **Primary Actor**: Resource Interaction System
- **Precondition**: The 'resource' setting includes a non-existent or unauthorized resource name.
- **Main Flow**: The system attempts to interact with the specified resource through the Microsoft Graph API, but the operation fails due to an invalid or unauthorized resource.

**Comment by mateocervilla** [comment]
This issue was delayed due to problems configuring to correctly execute the [`API Proxy`](https://github.com/microsoft/m365-developer-proxy) that we are using to mock the tests, which is now resolved and working.
