### ISSUE TITLE
Add Debian bookworm vulnerabilties scanner

### ISSUE THREAD

**Issue by eglyn** [wazuh/wazuh#18136]
Wazuh Version: 4.4.5

Hi :)

I try to add to the vulnerabilties scanner the Debian 12 Bookworm, but I have this error: 

![image](https://github.com/wazuh/wazuh/assets/24936778/31354ff9-dbee-49ef-b25b-1e4dd81140dc)

My config: 
```   
<!-- Debian OS vulnerabilities -->  
    <provider name="debian">
      <enabled>yes</enabled>
      <os>stretch</os>
      <os>buster</os>
      <os>bullseye</os>
      <os>bookworm</os>
      <update_interval>1h</update_interval>
    </provider>
```

Did I miss something ?

**Comment by MiguelazoDS** [comment]
Hi @eglyn, Debian 12 is not supported yet, there's a general issue to track what's needed to add Bookworm as a supported system here https://github.com/wazuh/wazuh/issues/17767. Regards!

**Comment by Dwordcito** [comment]
tracked in another issue, thank you for being a part of the Wazuh community.
