### ISSUE TITLE
Release 4.5.0 - Revision 1 - Alpha 1 - Footprint Metrics - VULNERABILITY-DETECTOR (6h)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18147]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #18059                                         |
| **Main footprint metrics issue #** | #18068                                         |
| **Version** | 4.5.0                                      |
| **Release candidate #** | Alpha 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.5.0-alpha1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4215/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/monitor-manager-Test_stress_B4215_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/plots/Test_stress_B4215_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4215_manager_2023-07-29.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/logs/ossec_Test_stress_B4215_manager_2023-07-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4215_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/data/monitor-manager-Test_stress_B4215_manager-pre-release.csv)
[Test_stress_B4215_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/data/Test_stress_B4215_manager_analysisd_events.csv)
[Test_stress_B4215_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/data/Test_stress_B4215_manager_analysisd_state.csv)
[Test_stress_B4215_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_manager_centos/data/Test_stress_B4215_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/monitor-agent-Test_stress_B4215_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/Test_stress_B4215_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/Test_stress_B4215_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/Test_stress_B4215_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/plots/Test_stress_B4215_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4215_centos_2023-07-29.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/logs/ossec_Test_stress_B4215_centos_2023-07-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4215_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/data/monitor-agent-Test_stress_B4215_centos-pre-release.csv)
[Test_stress_B4215_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_centos/data/Test_stress_B4215_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/monitor-agent-Test_stress_B4215_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/Test_stress_B4215_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/Test_stress_B4215_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/Test_stress_B4215_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/plots/Test_stress_B4215_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4215_ubuntu_2023-07-29.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/logs/ossec_Test_stress_B4215_ubuntu_2023-07-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4215_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/data/monitor-agent-Test_stress_B4215_ubuntu-pre-release.csv)
[Test_stress_B4215_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_ubuntu/data/Test_stress_B4215_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/monitor-winagent-Test_stress_B4215_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/Test_stress_B4215_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/Test_stress_B4215_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/Test_stress_B4215_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/plots/Test_stress_B4215_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4215_windows_2023-07-29.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/logs/ossec_Test_stress_B4215_windows_2023-07-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4215_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/data/monitor-winagent-Test_stress_B4215_windows-pre-release.csv)
[Test_stress_B4215_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4215-360m/B4215_agent_windows/data/Test_stress_B4215_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

**Comment by Rebits** [comment]
# Analysis report

## Logs

**Manager**:
- Errors

```
2023/07/29 00:05:56 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
```

- Warnings
```
2023/07/28 21:36:55 wazuh-logcollector: WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2023/07/28 21:37:13 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
2023/07/28 21:37:13 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
2023/07/28 21:37:13 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
2023/07/28 21:38:54 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
2023/07/28 21:38:54 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
2023/07/28 21:38:54 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
2023/07/28 21:39:06 wazuh-modulesd: WARNING: Debian Wheezy is no longer supported.
2023/07/28 21:39:06 wazuh-modulesd: WARNING: Debian Stretch is no longer supported.
2023/07/28 21:39:06 wazuh-modulesd: WARNING: Debian Jessie is no longer supported.
2023/07/29 00:03:48 wazuh-modulesd:vulnerability-detector: WARNING: (5575): Unavailable vulnerability data for the agent '002' OS. Skipping it.
2023/07/29 00:04:40 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 5' database could not be fetched.
2023/07/29 00:05:56 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Red Hat Enterprise Linux 5' database could not be fetched.
2023/07/29 00:06:56 wazuh-modulesd:vulnerability-detector: WARNING: (5575): Unavailable vulnerability data for the agent '002' OS. Skipping it.
2023/07/29 00:10:37 wazuh-modulesd:vulnerability-detector: WARNING: (5575): Unavailable vulnerability data for the agent '002' OS. Skipping it.
```
 

**centOS agent**

- Errors

```
2023/07/28 21:38:49 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2023/07/28 21:38:49 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.6.2]:1514/tcp': 'Connection refused'.
2023/07/28 21:38:59 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.6.2]:1514/tcp': 'Connection refused'.
```

**Ubuntu agent**
- Errors
2023/07/28 21:38:51 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.6.2]:1514/tcp': 'Connection refused'.
2023/07/28 21:39:01 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.6.2]:1514/tcp': 'Connection refused'.


**Windows agent**
```
2023/07/28 21:39:00 wazuh-agent: ERROR: SSL read (unable to receive message)
2023/07/28 21:39:00 wazuh-agent: ERROR: If Agent verification is enabled, agent key and certificates may be incorrect!
```

**Comment by davidjiglesias** [comment]
LGTM!
