### ISSUE TITLE
Discrepancies between 4.4.4 and 4.5.0 in modulesd memory usage

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18189]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | Modulesd | Agent | Packages | centOS 7 |

### Description

During [4.5.0 footprint testing](https://github.com/wazuh/wazuh/issues/18068),  it has been detected some discrepancies regarding the use of memory used by modulesd for 4.5.0.
An analysis comparing the memory usage of Modulesd version 4.5.0 with 4.4.4, reveals a significant differences between versions.
For SCA footprint we can see a significant increase of the used memory. However for rootcheck footprint testing this scenario is inverted, using modulesd a lot fewer resources than the previous version.

### Evidences
For the comparison we are reviewing the SCA footprint for [4.5.0](https://github.com/wazuh/wazuh/issues/18090) and [4.4.4](https://github.com/wazuh/wazuh/issues/17541) and SCA rootcheck for [4.5.0](https://github.com/wazuh/wazuh/issues/18094) and [4.4.4](https://github.com/wazuh/wazuh/issues/17559)

**SCA**

- 4.5.0
![4 5 0](https://github.com/wazuh/wazuh/assets/11089305/3a290a66-507d-409f-b0da-53ceeb2d7981)

**CSV**: [monitor-agent-Test_stress_B4193_centos-pre-release.csv](https://github.com/wazuh/wazuh/files/12228463/monitor-agent-Test_stress_B4193_centos-pre-release.csv)

- 4.4.0
![4 4 4](https://github.com/wazuh/wazuh/assets/11089305/a840f8f4-5998-4996-b519-a7b92639e2f3)
CSV: [monitor-agent-Test_stress_B4038_centos-pre-release.csv](https://github.com/wazuh/wazuh/files/12228467/monitor-agent-Test_stress_B4038_centos-pre-release.csv)

**Rootcheck**

- 4.5.0

![rootcheck450](https://github.com/wazuh/wazuh/assets/11089305/3a1e1805-b9f1-435e-91e0-f3985fe9417f)

CSV: [monitor-agent-Test_stress_B4192_centos-pre-release.csv](https://github.com/wazuh/wazuh/files/12229224/monitor-agent-Test_stress_B4192_centos-pre-release.csv)

- 4.4.4
![rootcheck444](https://github.com/wazuh/wazuh/assets/11089305/cb5225c9-a2f6-4ca0-aaaa-3eee830411eb)
CSV: [monitor-agent-Test_stress_B4037_centos-pre-release.csv](https://github.com/wazuh/wazuh/files/12229227/monitor-agent-Test_stress_B4037_centos-pre-release.csv)

**Comment by nbertoldo** [comment]
## SCA
We've run _wazuh-modulesd_ 5 times enabling SCA to compare the USS usage:

|4.5.0|4.4.5|
|---|---|
| 12904 KB | 12916 KB |
| 12952 KB | 15664 KB |
| 12896 KB | 14960 KB |
| 13068 KB | 14964 KB |
| 12892 KB | 12912 KB |

![Average USS](https://github.com/wazuh/wazuh/assets/117279646/d76d0831-7e15-415f-967b-4fea99e4dc2a)

![USS samples comparison](https://github.com/wazuh/wazuh/assets/117279646/2d5a5e2e-841b-4553-b3ab-6fbe21c1900e)

### Conclusions

- There is some scatter in the USS data among samples of the same versions.
- According to our test, the USS has decreased (but this is only coincidental).

## Rootcheck
We've run _wazuh-modulesd_ 5 times enabling rootcheck to compare the USS usage:

|4.5.0|4.4.5|
|---|---|
| 2604 KB | 4504 KB |
| 2436 KB | 4524 KB |
| 2440 KB | 6684 KB |
| 4468 KB | 4512 KB |
| 2440 KB | 4496 KB |

![Average USS_rootcheck](https://github.com/wazuh/wazuh/assets/117279646/89026beb-6c1e-46be-9151-0c094202642c)

![USS samples comparison_rootcheck](https://github.com/wazuh/wazuh/assets/117279646/fe501305-66c0-4545-b627-9e5a6362b23c)

### Conclusions

- There is some scatter in the USS data among samples of the same versions.
- According to our test, the USS has decreased (but this is only coincidental).
