### ISSUE TITLE
The CPU has increased during resources allocation in 4.5.0 - syscheckd

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#18195]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | Syscheckd | Agent | Packages | centOS 7 |

### Description

During [4.5.0 footprint testing](https://github.com/wazuh/wazuh/issues/18068), it has been detected some discrepancies regarding `CPU` increase by syscheckd for 4.5.0.

### Evidences
For the comparison we are reviewing the `CPU` footprint test for [4.5.0](https://github.com/wazuh/wazuh/issues/18100) and [4.4.4](https://github.com/wazuh/wazuh/issues/17561)

- 4.5.0
![4 5 0](https://camo.githubusercontent.com/89bd5c9b9f0c5d22dd72543b7cefa5d5d5460162d0d893463c2c0e9b7242865a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e302f42343230372d3336306d2f42343230375f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343230375f63656e746f732d7072652d72656c656173655f4350552e706e67)

    **CSV**: [monitor-agent-Test_stress_B4207_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4207-360m/B4207_agent_centos/data/monitor-agent-Test_stress_B4207_centos-pre-release.csv)

- 4.4.0
![4 4 4](https://camo.githubusercontent.com/19edceab1cf588cd16d2c6c08a76e47a1176ed838e27d6ca71bbbdea0c6d030c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e342f42343035342d3336306d2f42343035345f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343035345f63656e746f732d7072652d72656c656173655f4350552e706e67)
    CSV: [monitor-agent-Test_stress_B4054_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4054-360m/B4054_agent_centos/data/monitor-agent-Test_stress_B4054_centos-pre-release.csv)

**Comment by vikman90** [comment]
@roronoasins If we calculate the accumulated CPU time:

> ∑ (CPU usage) ÷ 100 [%] ÷ 5 [seconds / sample)

|4.4.5|4.5.0|Difference|
|---|---|---|
|202.7636 | 207.3494| 2 % ⬆️|

Both versions evolve in the same way, with one minor difference (which I don't think we can put down to any change):

![wazuh-syscheckd accumulated CPU time](https://github.com/wazuh/wazuh/assets/10536251/6022a16b-470c-4420-835b-96070034a0ad)

Those peaks seen at the beginning of 4.5.0 execution are irrelevant IMHO.

Let me close this issue.
Best!
