### ISSUE TITLE
Wazuh Issue Ticket going untouched & unsupported.

### ISSUE THREAD

**Issue by anthony-pepe** [wazuh/wazuh#18193]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Trying to resurface ticket (https://github.com/wazuh/wazuh/issues/17773).

We need some assistance resolving our issue before we proceed wtih another SIEM solution.

Any assistance would be greatly appreciated.

**Comment by pereyra-m** [comment]
Closing this issue.
@efahnle solved it at https://wazuh.slack.com/archives/C0A933R8E/p1689087176707779
