### ISSUE TITLE
OVA Publish 4.4.5 release

### ISSUE THREAD

**Issue by teddytpc1** [wazuh/wazuh#18190]
#### Build OVA packages 
The package is already built: https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/vm/wazuh-4.4.5.ova

### Testing stage
The OVA was tested here: https://github.com/wazuh/wazuh/issues/18115

### Release tasks
- [x] `wazuh-jenkins` tasks (QA):
    - [x] Merge `4.4.5` into `4.4` (using a new branch from `4.4.5`) with `4.4` as shared libraries branch. https://github.com/wazuh/wazuh-jenkins/pull/5491
    - [x] Create a new branch from `4.4.5`, bump shared libraries to `v4.4.5`.
    - [x] Open a PR from the previously created branch to `4.4.5` and merge it. https://github.com/wazuh/wazuh-jenkins/pull/5493
    - [x] Create tag `v4.4.5` (from branch `4.4.5`).
    - [x] Delete branch `4.4.5`.
- [x] `wazuh-packages` tasks (CICD):
    - [x] Merge `4.4.5` into `4.4`. https://github.com/wazuh/wazuh-packages/pull/2327
    - [x] Create `v4.4.5` tag  (from branch `4.4`). 
    - [x] Delete branch `4.4.5`.
- [x] Publish OVA: manually copy OVA and checksum from `packages-dev/pre-release` to `packages`. (CICD) 

### Post-release tasks
- [x] Validate that the OVA has been updated in the `packages.wazuh.com` bucket. (CICD) https://github.com/wazuh/wazuh/issues/18190#issuecomment-1662687564
- [x] Merge Documentation PR: https://github.com/wazuh/wazuh-documentation/pull/6287 (Docu)

**Comment by pro-akim** [comment]
# Update
CICD will performed the Publish process. https://github.com/wazuh/wazuh/issues/18203 closed

**Comment by c-bordon** [comment]
## Update report


I was testing with the published [OVA](https://packages.wazuh.com/4.x/vm/wazuh-4.4.5.ova) and everything works correctly:

![image](https://github.com/wazuh/wazuh/assets/64099752/22c847d0-5801-439e-aaae-6894e5f94887)

![image](https://github.com/wazuh/wazuh/assets/64099752/76da6e4c-e98c-4a15-8672-08c3eb8f0759)

![image](https://github.com/wazuh/wazuh/assets/64099752/f9e8ca92-5fac-4133-9750-e4d99de87f7c)
