### ISSUE TITLE
PSS/RSS/USS increase for 4.5.0 - analysisd

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#18194]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0 | Analysisd | Manager | Packages | centOS 7 |

### Description

During [4.5.0 footprint testing](https://github.com/wazuh/wazuh/issues/18068), it has been detected some discrepancies regarding `PSS/RSS/RSS_MAXMIN/USS` by analysisd for 4.5.0. These values have increased since the last footprint metrics.

### Evidences
For the comparison we are reviewing the `LOGCOLLECTOR,SYSCOLLECTOR` footprint test for [4.5.0](https://github.com/wazuh/wazuh/issues/18100) and [4.4.4](https://github.com/wazuh/wazuh/issues/17561)

- 4.5.0
![4 5 0](https://camo.githubusercontent.com/5b85e3d45a5fa41b98ae371787474fa0f0d748196a90529fcb548abe7ef16537/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e302f42343139362d3336306d2f42343139365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343139365f6d616e616765722d7072652d72656c656173655f5253532e706e67)

    **CSV**: [monitor-manager-Test_stress_B4196_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4196-360m/B4196_manager_centos/data/monitor-manager-Test_stress_B4196_manager-pre-release.csv)

- 4.4.0
![4 4 4](https://camo.githubusercontent.com/680bf91e772b7d73f9f017b36aff2f7372a149b5ceefc19224042af83191271f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e342f42343034332d3336306d2f42343034335f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343034335f6d616e616765722d7072652d72656c656173655f5253532e706e67)
    CSV: [monitor-manager-Test_stress_B4043_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4043-360m/B4043_manager_centos/data/monitor-manager-Test_stress_B4043_manager-pre-release.csv)

> This also happens with `PSS/RSS/RSS_MAXMIN/USS`

**Comment by vikman90** [comment]
We've run _wazuh-analysisd_ 5 times to compare the RSS usage:

|4.4.5|4.5.0|
|---|---|
| 52.5 MiB | 58.8 MiB|
| 50.3 MiB | 41.3 MiB|
| 42.3 MiB | 43.1 MiB|
| 44.4 MiB | 42.9 MiB|
| 46.3 MiB | 43.0 MiB|


![Average RSS](https://github.com/wazuh/wazuh/assets/10536251/bbf304e6-e3ab-4b08-9a39-b049cfd6df90)

![Sample comparison](https://github.com/wazuh/wazuh/assets/10536251/ea595e27-dfe5-4e0e-9919-fec693b9536a)

## Conclusions

- There is some scatter in the RSS data among samples of the same versions.
- According to our test, the RSS has decreased (but this is only coincidental).

We can close this issue IMO.

**Comment by davidjiglesias** [comment]
LGTM!
