### ISSUE TITLE
Filebeat unknown parameter [_type] compatibility.override causes no events in dashboard

### ISSUE THREAD

**Issue by arcreigh** [wazuh/wazuh#18191]
| Wazuh 4.4.5-2 | Unknown | Manager | N/A | Ubuntu 20.04.6 LTS | 

Good morning Wazuh team!

I am working through the SOCFortress stack implementation and have discovered an incompatibility between graylog and wazuh due to.
compatibility.override_main_response_version: true

It appears that filebeat requires this to be set in order for Wazuh to be able to display events in it's dashboard. 
In doing so graylog is unable to push data to wazuh. It is a catch 22 scenario where I can only use one or the other when having both would give me added benefits. 

The archives.log state the following on repeat:

```2023 Aug 01 13:08:03 ids-01->/var/log/syslog Aug  1 13:08:02 ids-01 filebeat[935]: 2023-08-01T13:08:02.359Z#011ERROR#011[publisher_pipeline_output]#011pipeline/output.go:180#011failed to publish events: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"}],"type":"illegal_argument_exception","reason":"Action/metadata line [1] contains an unknown parameter [_type]"},"status":400}```

Is there some configuration item I may have missed that would allow both of these stacks to co-exist?

**Comment by gdiazlo** [comment]
I'll close this. Please reopen it if you have more inquiries related to this question

**Comment by arcreigh** [comment]
hey @gdiazlo I actually was hoping to setup graylog using the existing wazuh-indexer instead of another OpenSearch instance as wazuh-indexer is using OpenSearch under the hood as well. So graylog does successfully create it's own indexes and such but I can't use both graylog and wazuh on the wazuh-indexer opensearch cluster. 

I do apologize for missing your initial response around that time I got a new federal job and was quite busy learning the ropes. 

Now I have some spare time to come back to this.
