### ISSUE TITLE
Update schema for sys_programs table: remove format restrictions and add fields to the primary key

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#18219]
### Description

This issue aims to enhance the schema of the `sys_programs` table by removing the existing restrictions on the `format` field and adding two new columns, `location` and `format`, as part of the primary key. These changes will improve the flexibility and efficiency of the table when managing program-related data and allow for better data integrity.

### Remove Format Restrictions

Currently, the `format` field in the `sys_programs` table has certain restrictions on the types of formats that can be stored. This limitation hinders the flexibility to accommodate various program formats that may be encountered. The proposed solution is to remove these restrictions and allow for more diverse program formats to be stored in the database.

### Add fields to the primary key

The primary key will consist of six columns: `scan_id`, `name`, `version`, `architecture`, `location`, and `format`. This addition will uniquely identify each program entry and provide a faster lookup when accessing program-related data.

### Definition of Done (DoD)

- [x] The restrictions on the `format` field have been removed successfully, allowing for more diverse program formats.
- [x] The columns, `location` and `format`, have been added to the `sys_programs` table as part of the primary key.
- [x] Review logic of empty validation for pks in dbsync and rsync from the manager side perspective.
- [x] Make changes to syscollector schema
- [x] Review data provider field population
- [x] Test / CI Green

### Exploratory

Make sure that the QA tests pass and that the agents upgrade and packages insertions/removal work as expected in the following OSs:

- [x] macOS Catalina
- [x] Windows 10
- [x] FreeBSD
- [x] CentOS 9
- [x] Solaris 10
- [x] Arch Linux
- [x] Debian Bullseye

**Comment by MiguelazoDS** [comment]
Propose in PR. Checks are failing due to Curl 

![image](https://github.com/wazuh/wazuh/assets/13010397/bd683d7f-c228-49d0-8676-ef3f29242fe6)

**Comment by MiguelazoDS** [comment]
# Exploratory

### QA tests for the non-existent platforms on GitHub actions. 

- Centos 9 (RedHat based - rpm)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/374d23c5-31a3-4fd1-9c12-62a902e03e2a)

</details>

- ArchLinux (pacman)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/2d9ac1a0-3fca-4c69-a97d-cb0ff8c981df)

</details>

- Solaris (pkg)

<details><summary> Expand </summary>



</details>

- FreeBSD (pkg)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/4cc194d7-357e-4df7-8d56-5669f671ea67)

</details>

### Syscollector Deltas / Upgrade

#### Version 4.4.5 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/d2aff09e-5d46-4058-b13c-6f90152263f1)

</details>

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/5f5cd9bf-cbc6-491d-ba88-e13f5c984a64)

</details>

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/e5813f47-458c-41ff-9740-a4a6729e0707)

</details>

Before installing Firefox 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/32093359-7c54-455a-9f20-e45f36473142)
![image](https://github.com/wazuh/wazuh/assets/13010397/de3dfa0f-fcb9-4d3b-b7f4-7b4b4a9f0bd6)

</details>

After installing Firefox

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/becb5acf-122b-4183-998d-636c84271ffe)
![image](https://github.com/wazuh/wazuh/assets/13010397/3cde7e16-3ab8-4047-b59a-5ee9655c341d)
![image](https://github.com/wazuh/wazuh/assets/13010397/a0d6de86-42b9-43e7-b866-06acc32252ee)
![image](https://github.com/wazuh/wazuh/assets/13010397/e2e19ba3-b80d-46f5-ac41-7da2a46d2132)

</details>

#### Upgrade Manager 4.5.2 (updated 08/18)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/d9e02286-97ee-45d5-b09e-87c09d317aac)
![image](https://github.com/wazuh/wazuh/assets/13010397/bbd58376-9259-44b4-8938-10e29f738320)
**Note: Nothing related to Syscollector or Wdb upgrade** 
![image](https://github.com/wazuh/wazuh/assets/13010397/2fee73d1-3acb-4da1-98fd-d75482547631)
![image](https://github.com/wazuh/wazuh/assets/13010397/8d93d98f-8a09-408f-b876-c1a5e4d6a863)
**Note: Nothing related to Syscollector or Wdb upgrade** 
![image](https://github.com/wazuh/wazuh/assets/13010397/b8764a3f-601b-4151-b43e-6a1669a5e346)

</details>

Before the upgrade, we have a location field null that will be part of the PK once the table is updated to a new version.

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/e9f09c22-67f0-4202-b4e9-8cf32eaed87e)

</details>

<details><summary> Expand </summary>



</details>

#### Upgrade agents 4.5.2 

Before upgrade 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/a8fc9d00-6de6-40b2-8315-073100a447fb)
![image](https://github.com/wazuh/wazuh/assets/13010397/8c29d0d1-d206-45bd-a542-f0b21cedd7cf)
![image](https://github.com/wazuh/wazuh/assets/13010397/3a8d7961-b126-4963-b53e-53c6bdff1f58)

</details>

After upgrade

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/67ad01ee-9f8a-41ae-bb00-153015f9eca7)
![image](https://github.com/wazuh/wazuh/assets/13010397/5b47b2b2-31bd-4681-8e15-be67deef3e64)
![image](https://github.com/wazuh/wazuh/assets/13010397/eb023490-e78a-4fc4-b8ab-a4152ebc6a74)

New item_id
![image](https://github.com/wazuh/wazuh/assets/13010397/013f1ccb-c95b-4452-bd8b-34572ab4757e)
![image](https://github.com/wazuh/wazuh/assets/13010397/2017177c-9c0c-424d-be7a-928b5da08827)
![image](https://github.com/wazuh/wazuh/assets/13010397/dd5994af-3746-42fd-a8b6-96f13c3cb3d9)

</details>

**Comment by MiguelazoDS** [comment]
# Exploratory

## Environment 
- Wazuh manager (Ubuntu Jammy)
- Wazuh agents (FreeBSD and ArchLinux)

## QA tests for the non-existent platforms on GitHub actions. 

- Archlinux (Pacman package manager)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/29f6cfbb-7e5b-4a9b-b85a-3791ea20bdb5)

</details>

- Freebsd (pkg package manager)

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/9bbceb92-df64-46a7-9868-47ac1ebb41c9)

</details>

## Syscollector Deltas / Upgrade (FreeBSD and ArchLinux)

### Version 4.4.5 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/80e8c826-3b90-49d4-ab63-b106a458a780)

</details>

**Before installing Firefox and Neovim**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/426a82da-4a76-4bb1-a919-7de2b2836529)

</details>

**After installing Firefox and Neovim**

FreeBSD

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/57243a29-5a69-431f-a676-43f9466f8e68)
![image](https://github.com/wazuh/wazuh/assets/13010397/1f3f6954-079a-4b5d-8514-beff29dc05eb)
![image](https://github.com/wazuh/wazuh/assets/13010397/ca12122c-9f0b-44a0-b9aa-9ce4a07b4d5c)

</details>

ArchLinux

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/4dad2f52-541c-45dc-a676-5886f812f755)
![image](https://github.com/wazuh/wazuh/assets/13010397/977ebf0c-afd9-4550-8a96-ffa2e5010dcc)
![image](https://github.com/wazuh/wazuh/assets/13010397/e24e21ff-9958-438e-bd19-fba2cc5c3bb5)

</details>

### Upgrade Manager 4.5.2

**Schema successfully modified**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/08a961e9-f78a-4f93-9640-d2e301fc4c58)

</details>

**Note: No warnings related to Syscollector or Wdb upgrade** 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/0af460cf-5685-42ce-a95f-8dbf73364251)

</details>

**Same package number**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/8c2d7b60-7392-489f-a76b-a06f1f038f6c)

</details>

**Now the packages have an empty string as location**

<details><summary> Expand </summary>

FreeBSD
![image](https://github.com/wazuh/wazuh/assets/13010397/bab42aff-38bd-442f-9f83-d91abcf7dcf5)

ArchLinux
![image](https://github.com/wazuh/wazuh/assets/13010397/3034c59e-5539-4465-9d03-31b3dcb80e7c)

</details>

**Uninstalling Firefox and Neovim. The same package number before installing the packages.**

<details><summary> Expand </summary>

FreeBSD
![image](https://github.com/wazuh/wazuh/assets/13010397/52465d2e-d687-448c-9610-648ceec65439)
![image](https://github.com/wazuh/wazuh/assets/13010397/ae7e6b3e-8d6b-42cd-b7a4-2c88c86e8130)

ArchLinux
![image](https://github.com/wazuh/wazuh/assets/13010397/247e7e0a-b353-429b-af08-4c882e050f97)
![image](https://github.com/wazuh/wazuh/assets/13010397/afbf5782-01a5-4389-8098-7f4b33da7056)

</details>

**Re-installing Firefox and Neovim. The same package number after installing the packages.**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/7d3009be-5112-4731-8a0d-75b1e32b115e)

</details>

### Upgrade agent 4.5.2 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/3546a444-071b-4d2f-81dc-57af09157282)

</details>

**Same package number after installing packages. Location now is a space string**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/16653bab-8212-489c-a378-0d02d2934338)
![image](https://github.com/wazuh/wazuh/assets/13010397/e09bbb12-81bb-4a46-a045-b22220601aba)
![image](https://github.com/wazuh/wazuh/assets/13010397/2acf7eb0-a781-4f76-ae64-4179bb3fa4bc)

</details>

**Uninstalling packages. Same package number before installing packages**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/792a9342-c744-4917-be40-532eb2183a2d)

</details>

**Re-installing packages. Check synchronization issues.**

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/4dedbac3-8174-4086-813f-af581216b547)
![image](https://github.com/wazuh/wazuh/assets/13010397/e44d9451-605f-4836-b07e-8cb856db1cd6)

</details>

**Removing agent and re-register it** 

<details><summary> Expand </summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/77b3ce8b-04e5-48aa-a15b-69c867cccb95)
![image](https://github.com/wazuh/wazuh/assets/13010397/2c747f19-83fc-4f79-8bbb-731f9b2da087)
![image](https://github.com/wazuh/wazuh/assets/13010397/4086a97e-e913-4cb0-a10d-635a939b252e)
![image](https://github.com/wazuh/wazuh/assets/13010397/837fddc4-4868-40d2-9a30-b42f4f1ad535)

</details>

**Comment by pereyra-m** [comment]
# Exploratory

These are tests covered in the exploratory:
- The `data_provider` QA tests
- The upgrade of the agent
- The correct synchronization of the packages table with the manager
- The installation and removal of packages
- The fresh installation of the agent

Environment:
- Wazuh manager v4.4.5 -> v4.5.2 : Ubuntu Jammy
- Wazuh agent v4.4.5 -> v4.5.2 : Windows 10
- Wazuh agent v4.4.5 -> v4.5.2 : Solaris 10

## Windows 10 :white_circle: 

### QA tests :yellow_circle: 

These tests already run in Github Actions but it was run in a local VM.
It was found that some packages come without the required `groups` field, but this isn't related to this development and will be solved in another issue

<details><summary>Details</summary>
<p>

![2023-08-24_18-00](https://github.com/wazuh/wazuh/assets/65046601/b7b09d66-21d9-4712-9773-6a283c5b65fc)


[win_packages.txt](https://github.com/wazuh/wazuh/files/12433289/win_packages.txt)

</p>
</details> 

## Solaris 10 :white_circle:

### QA tests :green_circle: 

The `sysinfo_testtool` was run in the Solaris VM and the result was moved to another machine. Then, the packages test was modified to read the data from it instead of running the tool.
The test passed.

<details><summary>Details</summary>
<p>

![2023-08-24_18-15](https://github.com/wazuh/wazuh/assets/65046601/a43afd3c-0ec4-4307-9688-fb8ee5c09618)

[solaris_packages.txt](https://github.com/wazuh/wazuh/files/12433380/solaris_packages.txt)


</p>
</details>
