### ISSUE TITLE
Remove downgrade reference in agent_upgrade binary

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18227]
|Wazuh version|Component|
|---|---|
| 4.4| Agent Upgrade |

### Description

Agent downgrade is not officially supported. However, the [agent_upgrade binary -F option](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-upgrade.html?highlight=downgrade), states the following:
```
Allows reinstalling the same version and downgrading the version.
```

This could lead to confusion among users, potentially resulting in the creation of unstable environments.
For this reason we should remove any reference to downgrade in the binary and documentation

**Comment by GGP1** [comment]
## Update

Corrected the command help message and documentation to go in line with what the [agent upgrade module documentation](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/agent-upgrade-module.html#upgrade-request-api-cli) states.

### Pull requests

wazuh: https://github.com/wazuh/wazuh/pull/18432
wazuh-documentation: https://github.com/wazuh/wazuh-documentation/pull/6345

**Comment by GGP1** [comment]
## Update

Rebased both related branches to `4.5.3`.
