### ISSUE TITLE
No items found when using the `@` character in a API query through `q` query parameter

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#18221]
|Wazuh version|Component|
|---|---|
| 4.6.0 | Wazuh component |

## Description

The following request is not returning the expected results:
```
GET /mitre/groups?q=name=admin@338
```
Evidence the entry exists:
![image](https://github.com/wazuh/wazuh/assets/34042064/dc5de313-96bc-4297-a204-f8eb2fe03404)

> We don't know if this problem could be affecting other endpoints.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

- Added support for the at symbol in query parameter values
- Updated unit test
- Added a stage in the integration test to cover this functionality

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.5.3  (release type is `patch`)
