### ISSUE TITLE
Sync information about vulnerability scans and results in Wazuh Cluster

### ISSUE THREAD

**Issue by Sht1n** [wazuh/wazuh#18236]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.3 | vulnerability-detector| Manager| Packages | Centos7|

Hello everybody.
I think it is Future request. 
Information about founded vulnerabilities and agents scans metrics like  _min_full_scan_interval_ aren't shared between workers in Wazuh cluster, so that could be some problems in big Wazuh infrastructure in case of wazuh agents changing worker connects to. I founded 2 thing which is important for us:

1. Wazuh worker look only on his "_last vulnerability scan date"_ of agent when calculate <min_full_scan_interval> to decide to start scan or no. 
For example: <min_full_scan_interval>= 2d. _Worker A_ done vulnerability scan of _Agent A_ yesterday, today _Agent A_ connect to _Worker B_. _Worker B_ dosn't know that Worker A has already done scan yesterday, it look only when he did scan of _Agent A_, so most probably will start another scan
2. Wazuh Application doesn't show (or receive) results of vulnerability scan of Agent, if Agent disconnected from Worker before the end of a scan. 
For example: _Agent A_ connected to _Worker A._ _Worker A_ starts vulnerability scan for all connected agents. _Agent A_ disconnects form _Worker A_ and connects to Worker B. _Worker A_ finishes vulnerability for Agent A, sends alerts about founded CVE, **BUT** this results will not appear in Wazuh Application GUI. Some screens showing this:

![Founded_vulns](https://github.com/wazuh/wazuh/assets/10332491/755e4d5a-a249-4f7a-b5a5-b74268db0d00)
![Scans stats](https://github.com/wazuh/wazuh/assets/10332491/f4904696-9d63-467a-acfb-c2ba5a3e7938)

Also some details could be found here in google group, where I asked about this behavior and @ooniagbi  helped me. https://groups.google.com/g/wazuh/c/iH-U89CLvS8

**Comment by MiguelazoDS** [comment]
HI @Sht1n, 

Thanks for your report, in fact, the vulnerability detector is not aware of a cluster setup, it only runs in a manager without considering if it is a master or a worker. 
It will scan only directly connected (and active) agents. 

For those reasons and many others, we are working on a complete rework of the module https://github.com/wazuh/wazuh/issues/14153 

I'm afraid that any big change like this one won't be addressed in the current module, but it will be considered for the new implementation.

**Comment by Dwordcito** [comment]
We close since it coincides with what to develop in #14153

Thank you for being part of the community.
