### ISSUE TITLE
Rules field <Same_field name=""> for dynamic fields

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#1824]
## Feature request

**Compatibility**
_manager_

**Component involved**
Analysisd

Description
--------------
Hi team,

We would like to use dynamic fields to correlate rules the same way we can use the labels `<same_id> <same_user> <same_location> ...` 

https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#same-id

This would be a very useful implementation, that will allow us to create more complex and detailed rules.

Kind regards,
Miguel

**Comment by chemamartinez** [comment]
Hi @migruiz4,

This request has been developed at #2689 and it will be available in the next Wazuh version.

Let me close the issue.

Regards.
