### ISSUE TITLE
Release 4.5.1 - Alpha 1 - WPK upgrade tests

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#18248]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|#18224|4.5.1|Alpha 1|[v4.5.1-alpha1](https://github.com/wazuh/wazuh/tree/v4.5.1-alpha1)| #18107 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail, and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a ZIP or TXT file. This report can be used by the auditors to dig deeper into any possible failures and details.

## Tests

To evaluate this feature, it is necessary to test upgrading the agent and also the case when the upgrade fails (rollback). The `tree` command will be used to compare, before and after the upgrade/rollback process, and check that the presence, ownership, and permissions of the files and directories are expected.

Wazuh versions to test (Upgrade to the current agent version):
### Linux

Skipped by definition https://github.com/wazuh/wazuh/issues/18224#issuecomment-1664232565
> |OS|Version|Status|Upgrade fail|Upgrade OK|Comments
> |----|-----|------|---------------|------------------|---------------|
> |CentOS 8 / RHEL 8|3.13.6| :white_circle:  |  |  ||
> |CentOS 8 / RHEL 8|4.4.5|:white_circle: | :white_circle: |:white_circle: ||
> |CentOS 8 / RHEL 8|4.5.0|:white_circle: | :white_circle: |:white_circle: ||
> |CentOS Stream 9|3.13.6| :white_circle:  |  |  ||
> |CentOS Stream 9|4.4.5|:white_circle: | :white_circle: |:white_circle: ||
> |CentOS Stream 9|4.5.0|:white_circle: | :white_circle: |:white_circle: ||
> |Ubuntu 22|3.13.6| :white_circle: | :white_circle: | :white_circle: ||
> |Ubuntu 22|4.4.5|:white_circle: | :white_circle: |:white_circle: ||
> |Ubuntu 22|4.5.0|:white_circle: | :white_circle: |:white_circle: ||
> |openSUSE Tumbleweed|3.13.6| :white_circle:  |  |  ||
> |openSUSE Tumbleweed|4.4.5| :white_circle: | :white_circle: |:white_circle: ||
> |openSUSE Tumbleweed|4.5.0| :white_circle: | :white_circle: |:white_circle: ||
> |Amazon Linux 2|3.13.6| :white_circle:  |  | ||
> |Amazon Linux 2|4.4.5| :white_circle: | :white_circle: |:white_circle: ||
> |Amazon Linux 2|4.5.0| :white_circle: | :white_circle: |:white_circle: |  |

### Windows

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments|
|----|-----|------|---------------|------------------|---------|
|Server 2012 R2|4.5.0 -> 4.5.1| :green_circle: | :green_circle: | :green_circle: |https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|
|Server 2012 R2|4.5.1 -> 4.5.1| :green_circle: | :green_circle: | :green_circle: |https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|
|Windows 11|4.5.0 -> 4.5.1| :green_circle:  | :green_circle: | :green_circle:|https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|
|Windows 11|4.5.1 -> 4.5.1| :green_circle: | :green_circle: | :green_circle: |https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|
|Server 2022|4.5.0 -> 4.5.1| :green_circle:  | :green_circle: |:green_circle: |https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|
|Server 2022|4.5.1 -> 4.5.1| :green_circle: | :green_circle: | :green_circle: |https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440|

### macOS

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments
|----|-----------|--------|-------|------------------|----------|
| Monterey|4.5.0 -> 4.5.1|  :yellow_circle:  |  :yellow_circle: |  :yellow_circle: | | ||
| Monterey|4.5.1 -> 4.5.1 (Force)|  :yellow_circle: | :yellow_circle: |  :yellow_circle: | | ||
| Ventura|4.5.0 -> 4.5.1| :green_circle:  | 🟢 | :green_circle: | | ||
| Ventura|4.5.1 -> 4.5.1 (Force)| :green_circle: | :green_circle: |  :green_circle: | | ||

## Findings

- The use of WPK update in Windows (Windows11 and WindowsServer12R2) has shown the occurrence of a timeout message during execution. However, what has been observed is that the execution actually takes place, effectively demonstrating the expected upgrade in the agent (or in case it's an upgrade failure, causing it to fail). The situation was described https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440 and the following issue was created https://github.com/wazuh/wazuh/issues/18329
- macOS WPK upgrade fails erratically due to timeout, probably this is produced by  the limited resources of the testing environment. Already reported here https://github.com/wazuh/wazuh/issues/14856

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @nmkoremblum
- [ ] @vikman90
- [ ] @davidjiglesias

**Comment by jnasselle** [comment]
# Update

Packages to test failure in progress - WIP

- Windows
- macOS
  - intel64
  - arm64

**Comment by jnasselle** [comment]
# TEST: Windows Server 2022

## From Wazuh-Agent v4.5.0-rc1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.0-rc1 Windows reports]()



### UPGRADE OK - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.0-rc1 Windows reports]()

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.5.1-alpha1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.1-alpha1 Windows reports]()



### UPGRADE OK  - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.1-alpha1 Windows reports]()

**Comment by pro-akim** [comment]
# TEST: Windows 11

## From Wazuh-Agent v4.5.1-alpha1
###  UPGRADE FAIL: :black_circle:

- [ ]  Wazuh-Agent folder tree: No files are lost after the rollback. The logs of the failed upgrade (ossec.log) are kept.
- [ ]  After the rollback the agent connects to the manager
- [ ]  After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ]  The correct Wazuh-Agent version is shown in the list of Windows' programs and features.
- [ ]  A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade report**
Report


###  UPGRADE OK: :black_circle:

- [ ] Message Upgrade finished successfully. is shown in upgrade.log file.
- [ ]  Wazuh service is started and the agent is connected to the manager.
- [ ]  The version shown in the control panel is 4.5.0
- [ ]  The new SCA policy is added and executed

**Upgrade report**
Report



## From Wazuh-Agent v4.5.1-alpha1
###  UPGRADE FAIL: :black_circle:

- [ ]  Wazuh-Agent folder tree: No files are lost after the rollback. The logs of the failed upgrade (ossec.log) are kept.
- [ ]  After the rollback the agent connects to the manager
- [ ]  After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ]  The correct Wazuh-Agent version is shown in the list of Windows' programs and features.
- [ ]  A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade report**
Report


###  UPGRADE OK: :black_circle:

- [ ] Message Upgrade finished successfully. is shown in upgrade.log file.
- [ ]  Wazuh service is started and the agent is connected to the manager.
- [ ]  The version shown in the control panel is 4.5.0
- [ ]  The new SCA policy is added and executed

**Upgrade report**
Report

**Comment by roronoasins** [comment]
# TEST: Windows Server 2012 R2

## From Wazuh-Agent v4.5.0-rc1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.0-rc1 Windows Server 2012 R2 reports]()



### UPGRADE OK - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.0-rc1 Windows Server 2012 R2 reports]()

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.5.1-alpha1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.1-alpha1 Windows Server 2012 R2 reports]()



### UPGRADE OK  - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.1-alpha1 Windows Server 2012 R2 reports]()

**Comment by verdx** [comment]
# TEST: macOS Monterey

## From Wazuh-Agent v4.5.0-rc1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.0-rc1 Windows Server 2012 R2 reports]()



### UPGRADE OK - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.0-rc1 Windows Server 2012 R2 reports]()

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.5.1-alpha1 - WIP

### UPGRADE FAIL  - WIP
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[Download v4.5.1-alpha1 Windows Server 2012 R2 reports]()



### UPGRADE OK  - WIP

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.5.1
- [ ] The new SCA policy is added and executed

**Upgrade reports**
[Download v4.5.1-alpha1 Windows Server 2012 R2 reports]()

**Comment by mauromalara** [comment]
# TEST: macOS Ventura (Intel) 🔵

## From Wazuh-Agent v4.5.0-rc1 🔵
 
### UPGRADE FAIL 🔵
- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - `/Library/LaunchDaemons/` `/Library/StartupItems/` `/Library/StartupItems/WAZUH/` `/Library/LaunchDaemons/` 
- [ ] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)


**Upgrade reports**
[Download v4.5.0-rc1 macOS Ventura reports]()



### UPGRADE OK ⚫

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting


**Upgrade reports**
[Download v4.5.0-rc1 macOS Ventura reports]()

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.5.1-alpha1 ⚫

### UPGRADE FAIL ⚫

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - `/Library/LaunchDaemons/` `/Library/StartupItems/` `/Library/StartupItems/WAZUH/` `/Library/LaunchDaemons/` 
- [ ] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
**Upgrade reports**
[Download v4.5.1-alpha1 macOS Ventura reports]()



### UPGRADE OK  ⚫

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting


**Upgrade reports**
[Download v4.5.1-alpha1 macOS Ventura reports]()

**Comment by damarisg** [comment]
LGTM
