### ISSUE TITLE
Windows agent doesn't start due to CryptAcquireContext error

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#1825]
## Bug report

**OS**
Windows Server 2012

**Wazuh version**
v3.2.1

**Install type**
agent

**Install method**
packages

**Log sample**

```
2018/11/07 09:22:40 ossec-agent: ERROR: CryptAcquireContext: (8009001a)
```

Bug description
----------------
The agent starts and then it is stopped automatically due to the previous error.

**Comment by Skeptor** [comment]
Hi @jesuslinares 
I just reproduce the error in a clean system inserting non-UTF8 characters in the key located at:
C:\ProgramData\Application Data\Microsoft\Crypto\RSA\S-1-5-18
This error: `CryptAcquireContext: (8009001a)` means that the key is corrupted, so Wazuh can't generate secure random numbers.
The solution is to delete the key. The Wazuh agent will generate a clean key at the next start.

Regards,
Pablo
