### ISSUE TITLE
Release 4.5.0 - RC 1 - System tests 

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#18260]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |          https://github.com/wazuh/wazuh/issues/18059            |
| **Version**                          |                 4.5.0                           |
| **Release candidate #**              |               RC 1                             |
| **Tag**                              |                 [v4.5.0-rc1](https://github.com/wazuh/wazuh/tree/v4.5.0-rc1)                          |
| **Previous system tests issue**      |                https://github.com/wazuh/wazuh/issues/18061 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

# Conclusion :green_circle: 

Expected Fail was found in test_enrollment/test_enrollment related to https://github.com/wazuh/wazuh/issues/16664
test_cluster/test_agent_enrollment/test_agent_enrollment.py in Enrollment Cluster presented an unstable behavior and a new issue was opened: https://github.com/wazuh/wazuh-qa/issues/4407
However, no abnormal behavior was detected

**Comment by pro-akim** [comment]
Working with @verdx on this issue

@verdx 

- enrollment_cluster
- basic_environment
- one_manager_agent
- basic_cluster
- agentless_cluster
- manager_agent

@pro-akim 

- one_manager_agent
- basic_cluster
- enrollment_cluster
- four_manager_disconnected_node
- enrollment_cluster
- big_cluster_40_agents

**Comment by pro-akim** [comment]
## Test results
   
<details>
<summary><b>Reports</b></summary> 
<br> 

- [agentless_cluster_env.zip]()
- [basic_cluster_env.zip](https://github.com/wazuh/wazuh/files/11692650/basic_cluster_env.zip)
- [basic_environment_env.zip]()
- [basic_four_manager_disconnected_node_env.zip]()
- [big_cluster_40_agents_env.zip]()
- [enrollment_cluster_env.zip]()
- [manager_agent_env.zip]()
- [one_manager_agent_env.zip]()


</details>


***

| | | | | | | |
|--|--|--|--|--|--|--|
| | **Test name** |  **Status** | **Pass** | **XFail/Skip** | **Fail** | **Issues Ref.** |
| | *One Manager Agent* | 
|1| test_fim/test_files/test_files_cud.py | :black_circle:  | 0 | 0 | 0 |
|2| test_fim/test_synchronization/test_synchronization.py | :black_circle: | 0| 0 | 0 |  
| | *Four Manager Disconnected Node* |
|3| test_cluster/test_agent_groups/test_agent_groups_new_cluster_node.py | :black_circle: | 0| 0 | 0 |  
| | *Agentless Cluster* |
|4| test_cluster/test_integrity_sync/test_integrity_sync.py | :black_circle: | 0 | 0 | 0 |  
|5| test_cluster/test_ruleset_sync_status/test_ruleset_sync_status.py |  :black_circle: | 0 | 0 | 0 | 
|6| test_jwt_invalidation/test_change_rbac_mode.py |  :black_circle: | 0| 0 | 0 |  
|7| test_jwt_invalidation/test_change_security_resources.py | :black_circle: | 0 | 0 | 0 |  
|8| test_jwt_invalidation/test_disconnected_nodes.py |  :black_circle: | 0 | 0 | 0 |   
|9| test_jwt_invalidation/test_revoke_endpoint.py | :black_circle: | 0  | 0 | 0 |   
|10| test_jwt_invalidation/test_update_password.py |  :black_circle: | 0 | 0 | 0 |  
| | *Enrollment Cluster* |
|10| test_cluster/test_agent_enrollment/test_agent_enrollment.py | :black_circle: |  0 | 0 | 0 |   
|11| test_cluster/test_agent_groups/test_agent_default_group_added.py | :black_circle: | 0  | 0 | 0 |  
|12| test_cluster/test_agent_groups/test_assign_agent_group_with_enrollment.py  |  :black_circle: | 0  | 0 | 0 |  
|13| test_cluster/test_agent_groups/test_assign_agent_never_connected_to_group.py | :black_circle: |  0  | 0 | 0 |   
|14| test_cluster/test_agent_groups/test_assign_agent_to_a_group_api.py | :black_circle: | 0 | 0 | 0 |   
|15| test_cluster/test_agent_groups/test_assign_agent_to_a_group_by_tool.py |  :black_circle: | 0  | 0 | 0 
|16| test_cluster/test_agent_groups/test_assign_agent_to_a_group.py | :black_circle: | 0| 0 | 0 |   
|17| test_cluster/test_agent_groups/test_assign_groups_guess.py |  :black_circle: | 0  | 0 | 0 |   
|18| test_cluster/test_agent_groups/test_agent_groups.py | :black_circle: | 0 | 0 | 0 |  
|19| test_cluster/test_agent_groups/test_remove_group.py | :black_circle: | 0  | 0 | 0 | 
| | *Manager Agent* |
|20| test_active_response_log_format/test_active_response_log_format.py | :black_circle: | 0  | 0 | 0 |   
|  | *Basic Cluster*   |
|21| test_cluster/test_agent_info_sync/test_agent_info_sync.py |  :black_circle:  | 0  | 0 | 0 |   
|22| test_cluster/test_agent_key_polling/test_agent_key_polling.py |   :black_circle: |0 | 0 | 0 |  
|23| test_cluster/test_agent_files_deletion/test_agent_files_deletion.py |:black_circle: |0 | 0 | 0 |  
|24| test_multigroups/test_multigroups.py | :black_circle: | 0  | 0 | 0 | 
|25| test_cluster/test_agent_groups/test_agent_groups_forced_change.py |   :black_circle: | 0  | 0 | 0 |  
| | *Big Cluster 40 Agents* |
|26| test_cluster/test_agent_groups/test_groups_sync_default.py | :black_circle: | 0 |0| 0 |   
|27| test_cluster/test_agent_groups/test_groups_sync_time.py | :black_circle: | 0 | 0 | 0 | 
| | *Basic Environment* |
|28| test_agent_auth/test_agent_auth.py | :black_circle: | 0  | 0 | 0 |
|29| test_enrollment/test_enrollment.py | :black_circle: | 0 | 0 | 0  |

**Comment by damarisg** [comment]
LGTM!

**Comment by BelenValdivia** [comment]
LGTM!
