### ISSUE TITLE
Treat the default agent (ID: 000) the same as all other agents

### ISSUE THREAD

**Issue by melroy89** [wazuh/wazuh#18274]
This feature request is about adding the default agent (with ID 000) to the web interface components/ to all the components that make sense. **Basically treat agent 000 the same as other agents.**

See the listed below but not limited to:

- Homepage: Add agent 000 part of the "Total agents"
- Agents module: Agent 000 is part of the agent listing, and you are able to click on it.
- Vulnerability module: During "Select agent" be able to select agent 000
- In all Events tags: Make the agent 000 (server name) clickable just like normal agents. 
- ... You get the point.

Feel free to split this feature request into smaller chunks if you wish.

**Comment by MiguelazoDS** [comment]
Hi, 

Thanks for the request, it is something that we have discussed before but there's no ETA for implementation yet. As we may have several agents 000 we need first to address that differentiation. 

Regards!

**Comment by MiguelazoDS** [comment]
If we have a cluster environment, we have a master and at least one worker. If we decide to show the information to the master manager, probably it would be desirable to also consider the information of workers, but this is just a vague idea, there's no roadmap yet to address this kind of change, I'll talk to my team to know if there's something I not aware of.

**Comment by Dwordcito** [comment]
Closed due to inactivity, please re-open this issue if decide to continue with this task.

Thanks for being part of the Wazuh Community.

**Comment by melroy89** [comment]
Not cool to close it.
