### ISSUE TITLE
Release 4.5.1 - Alpha 1 - Integration tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18286]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `v4.5.1-alpha1`| https://github.com/wazuh/wazuh-qa/commit/b51f4ad6913a3f7d0922df0604660ebb0ef6ad77 |  `v4.5.1-alpha1`  |   | 

We are going to check that the integration tests of the `4.5`  branch of `wazuh-qa` work correctly using the [v4.5.1-alpha1](https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-alpha1) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/18224

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|:large_blue_circle:|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"> :green_circle:   </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;"> :green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"> :green_circle: </td>
<td style="width: 79px;">:red_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"> :green_circle:  </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;"> :green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;"> :green_circle:</td>
<td style="width: 97px;"> :green_circle:</td>
<td style="width: 97px;" colspan="2">:green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:green_circle: </td>
<td style="width: 97px;">:green_circle: </td>
<td style="width: 97px;" colspan="2">:green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"> :red_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:red_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">:green_circle: </td>
</tr>
</tbody>
</table>

## Evidence
**Build:** https://ci.wazuh.info/view/Tests/job/Test_integration_launcher/184/

## Conclusion  :red_circle: 

The following tests failed:
- Windows Agentd tests failed with new Issue reported: https://github.com/wazuh/wazuh-qa/issues/4403
- Vulnerability Detector tests failed with known issue https://github.com/wazuh/wazuh-qa/issues/4370. The Issue is not related to the application but is dependent on the feed providers.
- Syscollector Windows agent failed with known Issue https://github.com/wazuh/wazuh-qa/issues/4230 
   - [Evidence](https://github.com/wazuh/wazuh/files/12285562/agent_windows_html_report_Test_integration_B42122_20230807202612.zip)
- While trying to launch IT tests in a macOS Arm system, the wazuh-qa framework and dependencies failed to install properly, and tests could not be launched. This has been reported in https://github.com/wazuh/wazuh-qa/issues/4411

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @damarisg / @fcaffieri

**Comment by damarisg** [comment]
### Suggestions

- Could you try to run the ITs on the macOS arm, please? It will help us to know the possible problems.

**Comment by Deblintrake09** [comment]
Tried to run tests on a MacOS ARM64 Monterey endpoint. was unable to set up the wazuh repository and run the tests. This was with Python3.9 and Python3.10. On both instances the same issues where found:
- It would fail to install `cryptography` library.
```
 build/temp.macosx-12-arm64-cpython-310/_openssl.c:575:10: fatal error: 'openssl/opensslv.h' file not found
      #include <openssl/opensslv.h>
               ^~~~~~~~~~~~~~~~~~~~
      1 error generated.
      
          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation.html for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq.html
          =============================DEBUG ASSISTANCE=============================
      
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
```
   -  tried to fix by updating pip, wheel and setuptools as possible dependencies. 
   - Installing OpenSSL that is a dependency for cryptography. 

- dependencies `filetype`, `lockfile`, `numpydoc`, `py`, `html-reporter`, `pyyaml` would not be installed, but where required for the tests. Installed manually.
- When trying to launch the tests, they would fail due to the `html-reporter` dependency, that needed to be installed as well. After installing, it tests would still fail to run and not be executed.
```

sh-3.2# python3.10 -m pytest test_syscollector/
======================================= test session starts ========================================
platform darwin -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /Users/vagrant/wazuh-qa/tests/integration
configfile: pytest.ini
plugins: testinfra-8.1.0
collected 27 items                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/_pytest/main.py", line 270, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/_pytest/main.py", line 334, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/_pytest/main.py", line 671, in perform_collect
INTERNALERROR>     self.config.pluginmanager.check_pending()
INTERNALERROR>   File "/opt/homebrew/lib/python3.10/site-packages/pluggy/_manager.py", line 339, in check_pending
INTERNALERROR>     raise PluginValidationError(
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_html_results_summary' in plugin <module 'conftest' from '/Users/vagrant/wazuh-qa/tests/integration/conftest.py'>

====================================== no tests ran in 0.05s =======================================
``

**Comment by damarisg** [comment]
Good job! A new problem to cover by QA. 
You could open an issue to include support on arm64.

**Comment by damarisg** [comment]
LGTM!
