### ISSUE TITLE
Release 4.5.0 - RC 1 - GCP Module testing

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18287]
# GCP module testing

## Modules tests information
|||
|----------------------------------|------ |
| **Main release candidate issue** | #18235   |
| **Version**                      | 4.5.0 |
| **Release candidate #**          | RC 1   |
| **Tag**                          | [v4.5.0-rc1](https://github.com/wazuh/wazuh/tree/v4.5.0-rc1) |
| **Previous modules tests issue** | #18119 |

The GCP module testing includes both `gcp-bucket` and `gcp-pubsub` integrations.

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                                        |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | The test passed successfully. 										    |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply to the given bucket type or service.            |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the [Release 4.5.0 project](https://github.com/orgs/wazuh/projects/41/) for triage.

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

## Test results

| Feature           |  Status | Issue ref.     |
|-------------------|---------|----------------|
| Test using ossec.conf in a manager with Python 3.9 | 🟢   |  |
| Test using ossec.conf in an agent with Python 3.7 | 🟢  |  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario

**Comment by Selutario** [comment]
I compared this testing with the one made in 4.4.0 and have some questions:

### 1. Different configuration
The first one is, looking at the configuration used for 4.4.0:
```XML
<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1d</interval>
    <project_id>wazuh-dev-123456</project_id>
    <subscription_name>wazuh-framework-subscription</subscription_name>
    <num_threads>4</num_threads>
    <logging>info</logging>
    <max_messages>50</max_messages>
    <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
</gcp-pubsub>

<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1m</interval>
    <logging>info</logging>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
    </bucket>

    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
        <only_logs_after>2022-Jul-01</only_logs_after>
        <path>test_prefix</path>
    </bucket>
</gcp-bucket>
```

And the one used here:
```XML
<gcp-pubsub>
     <pull_on_start>yes</pull_on_start>
     <interval>1m</interval>
     <project_id>wazuh-dev-123456</project_id>
     <subscription_name>wazuh-test-subscription</subscription_name>
     <num_threads>4</num_threads>
     <max_messages>50</max_messages>
     <credentials_file>/var/ossec/etc/credentials.json</credentials_file>
</gcp-pubsub>

<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1d</interval>
    <bucket type="access_logs">
        <name>test-bucket</name>
        <credentials_file>/var/ossec/etc/credentials.json</credentials_file>
        <only_logs_after>2022-Jul-01</only_logs_after>
        <path>test_prefix</path>
    </bucket>
</gcp-bucket>
```

Is there any reason not to test the `test-bucket` or other resources? 

### 2. Acknowledged messages
I see in the configuration that `max_messages` is set to 50, however, this log is printed:
```
INFO: Received and acknowledged 40 messages
```
How many messages were pushed to GCP? Why would only 40 of them be acknowledged? 

### 3. Integration options
Comparing it to the testing done in this issue:
- https://github.com/wazuh/wazuh/issues/14437

I see some settings like `only_logs_after` or `max_messages` not being tested. Could you check them out?

**Comment by EduLeon12** [comment]
## Issue Update

All test results were edited to include the previous configuration asked. 
Changes were:

- Added more information about the publication of messages for the pubsub to properly test the `max_messages` parameter.
- Added new bucket config to test the `only_logs_after` parameter.
- Edited ossec.log outputs to display the results.

**Comment by BelenValdivia** [comment]
LGTM!
