### ISSUE TITLE
Update_from_year option cannot be used for nvd provider error message still appears in performance testing

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18298]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0-rc1 | Wazuh-modulesd | Manager | Packages | Centos |

After solving the following 2 issues:
- https://github.com/wazuh/wazuh-puppet/issues/706
- https://github.com/wazuh/wazuh-docker/issues/909

Running a footprint performance test https://github.com/wazuh/wazuh/issues/18271:
The following log was found:
```
./var/ossec/logs/ossec.log:75:2023/07/26 13:16:06 wazuh-modulesd: WARNING: 'update_from_year' option cannot be used for 'nvd' provider.
```
Further research will be required.

**Comment by jnasselle** [comment]
Closing this issue because it was created based on a wrong and old analysis.

Sorry about the inconvenience.
