### ISSUE TITLE
Research and development for WPK macOS new architecture arm

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#18291]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1 | Agent Upgrade | Manager/Agent | Packages/Sources | MacOS |

## Description
Hello team,

After the changes made to include the new architecture supported by the macOS operating systems:
https://github.com/wazuh/wazuh-jenkins/issues/5255

It is necessary to modify the Wazuh code so that the upgrades of macOS agents with different architectures work correctly.
When executing the `agent_upgrade` we must be able to differentiate between macOS architectures and send the correct WPK.

**Comment by TomasTurina** [comment]
Duplicated of https://github.com/wazuh/wazuh/issues/18541.
