### ISSUE TITLE
Missing security events due to journalctl migration on certain OSs

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#18299]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.0-40500 | Agent | Agent | Packages | Debian 12 |

We executed [manual tests in v4.5.0-rc1](https://github.com/wazuh/wazuh/issues/18258) in which we attempted to generate SSH alerts ("Permission denied") to check the correct communication between components.

**While testing we found that those alerts were not generated.**

The main cause was in the agent, which was installed in Debian 12. So, with further research, we realized that Wazuh was not collecting several logs (ssh, kernel, firewall, etc.) **because** the OS had not rsyslog installed by default.

As you can see in the agent's `ossec.conf` file there is no `auth.log` file being monitored by Wazuh: [agent-debian-12-ossec.conf.zip](https://github.com/wazuh/wazuh/files/12284805/debian-12-ossec.conf.zip)

With Debian 12, there was a notable change in the priority of the "rsyslog" package, transitioning it from 'important' to 'optional.' Consequently, this package is no longer installed by default.

This adjustment was prompted by the reconfiguration of journald in Debian Bullseye, whereby logs were now being persisted to disk rather than memory. As a result, the decision was made in Debian 12 to forgo the default installation of rsyslog, preventing unnecessary duplication of logs to disk.

## Steps to reproduce

1. Install Wazuh Manager (ALAS 2) and start it
2. Install Wazuh Agent (Debian 12)
3. Configure the Agent for it to connect to the Manager
4. Start the Agent
5. Make 8 invalid login attempts through SSH

## Expected result

- Wazuh Agent should send this kind of significant event to the manager
- Wazuh Manager should trigger an alert with level 10 (Brute force attack)

## Current result

- Wazuh Agent is not collecting this kind of event causing alerts not to be generated

**Comment by vikman90** [comment]
Hi team, this is a duplicate of https://github.com/wazuh/wazuh/issues/12862.
