### ISSUE TITLE
Wazuh-monitord's CPU usage peak was detected in footprint testing

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18294]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0-rc1 | wazuh-monitord | Manager | Packages | Centos |

A footprint test was performed in 4.5.0-rc1 Release making possible to detect a big peak of CPU usage in "wazuh-monitord"  at timestamp 2023-08-05 at 00:02:55.

![image](https://github.com/wazuh/wazuh/assets/125690423/700c7f9d-7962-4e16-b0e4-99cfc16b1b84)

The logs do not show any errors or warnings in the records related to "monitord."

It could be a peak of uncertain or insignificant meaning, but to determine that, its cause should be investigated.

**Comment by TomasTurina** [comment]
@pro-akim this happened at midnight when `wazuh-monitord` executes some operations, for example log rotation. Besides, this happened after the stress test finished. I think this is expected and not a problem at all.
cc @vikman90
