### ISSUE TITLE
Wazuh-modulesd and Wazuhdb are not showing disk consumption during footprint test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18304]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0-rc1 | Wazuh-modulesd and wazuhdb | Manager| Packages | CentOS|

Seems that in CentOS Manager wazuh-modulesd and wazuhdb are not reading the disk during the test meanwhile old versions do it.

4.5.0 RC 1 (Current)
![image](https://github.com/wazuh/wazuh/assets/125690423/0947652a-b05a-4680-83c0-35e063509299)

4.5.0 Alpha 1
![image](https://github.com/wazuh/wazuh/assets/125690423/eb456030-19f4-46a3-b292-1e1cac3f0671)

4.4.4 RC 2
![image](https://github.com/wazuh/wazuh/assets/125690423/85a16259-a6ea-49d3-a94d-98d95229d9c4)

Research is required to check if this behavior is expected

**Comment by Rebits** [comment]
@pro-akim, this behavior occurred in all the footprint tests https://github.com/wazuh/wazuh/issues/18249. It's important to note that this occurrence isn't tied to the behavior of the modulesd. Detailed analysis of the indexed graphics reveals that this module's disk operations are consistent with previous versions, dispelling any concerns about its performance.

The disparities in the graphics can be attributed to the monitord module, not modulesd. The footprint analysis was conducted over a span of two days, which led to a noticeable surge in resource-intensive operations for the monitord daemon, generating the depicted graphics.

To mitigate this, it would be prudent to introduce specific logic within the stress tests. This would effectively prevent inadvertent log rotation operations during footprint tests spanning less than a day, streamlining the analysis process and enhancing the accuracy of results.
