### ISSUE TITLE
The Modulesd disk read pattern in the Release 4.5.0-rc1 footprint test for Wazuh-CentOS-Manager is distinct from the patterns observed in the prior analyses.

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18307]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0-rc1| Wazuh modulesd | Manager | Packages| CentOS |

Running [Release 4.5.0 - Revision 1 - Release Candidate RC1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (6h) ](https://github.com/wazuh/wazuh/issues/18271)

Modulesd Disk_read pattern is different from the previous tests.

[4.5.0-rc1](https://github.com/wazuh/wazuh/issues/18271)
![image](https://github.com/wazuh/wazuh/assets/125690423/38c175ac-0e6c-49a9-bfd1-bfaea656fe29)

[4.5.0-alpha1](https://github.com/wazuh/wazuh/issues/18091)
![image](https://github.com/wazuh/wazuh/assets/125690423/be7a03c1-9940-4e1d-bfe4-cc219410e0ca)

[4.4.4-rc1](https://github.com/wazuh/wazuh/issues/17475)
![image](https://github.com/wazuh/wazuh/assets/125690423/43515db6-5899-47e0-a9b5-9a2e2ffbf415)

No relevant records have been found in the logs to attribute this absence of disk reads.

**Comment by vikman90** [comment]
This is related to https://github.com/wazuh/wazuh/issues/18294. There is some disk activity due to log rotation and compression by wazuh-monitord.

Closing this issue.
