### ISSUE TITLE
Engine - Restructuring of API Tests

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#18316]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description:
The goal of this task is to enhance the organization of API tests within the Wazuh codebase. This reorganization aims to improve maintainability and clarity by aligning the location of API tests with their respective code modules. Additionally, the task involves distinguishing between unit and component tests while adhering to the established naming conventions within the Wazuh project.

Proposed Steps:
- [x] Relocation of API Tests: The API tests, currently located in the "test" directory, will be moved to the corresponding API module. This change ensures that the tests are co-located with the code they are validating, simplifying future updates and contributions.
- [x] Categorization of Tests: During the reorganization, special attention will be given to categorizing tests into distinct units and components. This categorization is essential for maintaining a clear separation of concerns and facilitating targeted testing.
- [x] Nomenclature Consistency: The existing naming conventions within the Wazuh project will be strictly followed to name the reorganized API tests. This ensures consistency across the project and helps developers easily identify the purpose and scope of each test.

Expected Benefits:
- Improved Organization: The restructured layout will streamline the development process by providing a logical arrangement of tests, reducing the effort required to locate and manage them.
- Enhanced Maintenance: With API tests residing alongside the relevant code, future updates and code changes can be comprehensively tested, minimizing the risk of regressions.
- Clearer Testing Strategy: Distinguishing between unit and component tests enables a more targeted testing approach, allowing for focused validation of specific functionalities.

By executing these steps, we aim to optimize the API testing framework within Wazuh, ultimately contributing to a more efficient and structured codebase.

**Comment by vikman90** [comment]
Extending the ETA one week.
