### ISSUE TITLE
Agent did not appear at dashboard

### ISSUE THREAD

**Issue by zulk85** [wazuh/wazuh#18313]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.5 | Wazuh Agent | Agent | Installing Wazuh agents on Windows endpoints | Win10 64 bit |

Hello..i already install wazuh server at my vm with ip 192.168.1.194
Manage to ping the wazuh server from my laptop
![image](https://github.com/wazuh/wazuh/assets/80100404/c3c01f43-f97f-4e21-938a-4d17be2c723f)

My wazuh server successfully installed
.
![image](https://github.com/wazuh/wazuh/assets/80100404/28fbedd5-90ea-4073-8122-11dd97f50ebb)

The problem is the agent did not appear to dashboard after i installed the agent from here:
.
![image](https://github.com/wazuh/wazuh/assets/80100404/8681f760-6a18-4e44-b9bf-6b0ad108e39e)
.
.
Feel weird since all the guides i already follow guideline
.
.
Also when i start the services,after couple of second,it stop again.

![image](https://github.com/wazuh/wazuh/assets/80100404/7d9442cb-0656-40cc-8a76-a27c178cb90a)

Not sure what is the issue,since i'm new with Wazuh...Please advice

**Comment by zulk85** [comment]
I'm not sure about the log..
Here is the log i can get
![image](https://github.com/wazuh/wazuh/assets/80100404/d7d81c5d-3f71-4438-8c0d-099909350c18)

**Comment by MiguelazoDS** [comment]
Hi, 

Both manager and agent are 4.4.5? is the agent connected to the manager. 
Inside the manager what is the output of this command `agent_control -l`

**Comment by zulk85** [comment]
Hi...thanks for reply..

Here is my manager version:
![image](https://github.com/wazuh/wazuh/assets/80100404/8deb83a9-d301-47f6-bbd2-b9df4426402b)
.
.
Here is my agent version:
![image](https://github.com/wazuh/wazuh/assets/80100404/ec54a228-b090-4eb2-91bf-299c924b53e5)
.
.
Please advice...thanks

**Comment by zulk85** [comment]
How to verify both?

1)is the agent connected to the manager.?
2)Inside the manager what is the output of this command agent_control -l

please advice..thanks

**Comment by MiguelazoDS** [comment]
Hi @zulk85, 

In your manager type that command. In my case, the agent is disconnected. But it should appear in the dashboard with that state. 
![image](https://github.com/wazuh/wazuh/assets/13010397/6a816832-c439-402e-ae82-8656318a8702)

If you only see agent 000 information is because the agent wasn't even register against that manager. 

Did you configure the manager IP in the `/var/ossec/etc/ossec.conf` file in you agent?

**Comment by zulk85** [comment]
> Hi @zulk85,
> 
> In your manager type that command. In my case, the agent is disconnected. But it should appear in the dashboard with that state. ![image](https://user-images.githubusercontent.com/13010397/259770205-6a816832-c439-402e-ae82-8656318a8702.png)
> 
> If you only see agent 000 information is because the agent wasn't even register against that manager.
> 
> Did you configure the manager IP in the `/var/ossec/etc/ossec.conf` file in you agent?

Hi mate....

Thanks again for reply me...
Here is my host result after run the command,i'm using ubuntu 20.04 lts..
![image](https://github.com/wazuh/wazuh/assets/80100404/64d87736-eb59-41ad-94db-37a47cacdbf9)
.
.
.
Here is my `/var/ossec/etc/ossec.conf
[_var_ossec_etc_ossec.txt](https://github.com/wazuh/wazuh/files/12318238/_var_ossec_etc_ossec.txt)
.
.
Quick note:I follow the installation guide at quickstart guide) - https://documentation.wazuh.com/current/quickstart.html

**Comment by zulk85** [comment]
> Hi zulk85,
> 
> That's the ossec.conf file for your manager, you need to edit the ossec.conf for your agent. Specifically this line
> 
> `<manager_address>MANAGER_IP</manager_address>`
> 
> Did you follow this section after deploying the manager? https://documentation.wazuh.com/current/quickstart.html#next-steps You need to deploy a Wazuh agent in another machine/VM.
> 
> The issue with the command "agent_control" must be related to the env variable. Try this
> 
> `/var/ossec/bin/agent-control -l`

Hello...thanks for reply...will follow the document and will revert back if any issue occured

**Comment by Dwordcito** [comment]
Thank you for being part of the community, we closed the issue due to inactivity, in case you return please reopen the issue!
