### ISSUE TITLE
Query for `condition` field and `all` value through the `q` in Security Configuration Assessment checks gives an error

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#18314]
|Wazuh version|Component|
|---|---|
| 4.6.0 | Wazuh component |

## Description

Using the `all` value to search through the `q` query parameter for the `condition` field in the Security Configuration Assessment checks gives an error.

Endpoint: `GET /sca/{agent_id}/checks/{policy_id}`

Example:

![image](https://github.com/wazuh/wazuh/assets/34042064/157c127b-b019-49d1-809a-71ad9a625b22)
![image](https://github.com/wazuh/wazuh/assets/34042064/29bc3669-d422-4f5b-ac45-febafa38ee43)
![image](https://github.com/wazuh/wazuh/assets/34042064/4fe0415c-cef6-44c0-a384-f9a60f793536)
![image](https://github.com/wazuh/wazuh/assets/34042064/8fdefaf9-be9c-40a3-b822-8f81c3946d47)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Fixed the issue by keeping the filters with a `condition` field that were previously being skipped by the database SDK

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.5.3  (release type is `patch`)
