### ISSUE TITLE
Wazuh Manager won't start

### ISSUE THREAD

**Issue by 443ca** [wazuh/wazuh#1831]
This is my first attempt at CentOS and Wazuh.  I loaded it offline and initially configured it using DHCP. I changed the IP today.   Since then, I have not been able to get any agents to register.

When I view the status, I receive the following - 
[root@localhost ~]# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-11-07 21:30:52 EST; 16s ago
  Process: 4628 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=1/FAILURE)

Nov 07 21:30:52 localhost.localdomain systemd[1]: Starting Wazuh manager...
Nov 07 21:30:52 localhost.localdomain env[4628]: Starting Wazuh v3.6.1 (maintained by Wazuh Inc.)...
Nov 07 21:30:52 localhost.localdomain env[4628]: OSSEC analysisd: Testing rules failed. Configuration error. Exiting.
Nov 07 21:30:52 localhost.localdomain systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
Nov 07 21:30:52 localhost.localdomain systemd[1]: Failed to start Wazuh manager.
Nov 07 21:30:52 localhost.localdomain systemd[1]: Unit wazuh-manager.service entered failed state.
Nov 07 21:30:52 localhost.localdomain systemd[1]: wazuh-manager.service failed.
[root@localhost ~]#

When I first logged into Kibana, I had to change the IP address of the API.  I did that and then attempted a reboot as well.  Any thoughts?

**Comment by 443ca** [comment]
GNU nano 2.3.1                                             File: /var/ossec/logs/ossec.log

2018/11/07 00:00:10 ossec-monitord: INFO: Starting new log after rotation.
2018/11/07 00:05:17 rootcheck: INFO: Ending rootcheck scan.
2018/11/07 00:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 00:41:21 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 01:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 01:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 02:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 02:41:21 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 03:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 03:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 04:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 04:41:21 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 05:40:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 05:41:21 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 06:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 06:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 07:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 07:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 08:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 08:41:23 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 09:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 09:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 10:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 10:41:23 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 11:41:00 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/11/07 11:41:22 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/11/07 11:47:08 ossec-syscheckd: INFO: Starting syscheck scan.
2018/11/07 11:49:08 ossec-syscheckd: INFO: Ending syscheck scan.
2018/11/07 12:05:18 rootcheck: INFO: Starting rootcheck scan.
2018/11/07 12:13:46 rootcheck: INFO: Ending rootcheck scan.
2018/11/07 12:39:17 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 21:16:10 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 21:30:52 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 21:47:46 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 21:58:05 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 22:04:19 ossec-testrule: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).
2018/11/07 22:06:36 ossec-testrule: ERROR: (1226): Error reading XML file 'etc/decoder.xml': XMLERR: File 'etc/decoder.xml' not found. (line 256).
2018/11/07 22:06:36 ossec-testrule: CRITICAL: (1202): Configuration error at '/etc/decoder.xml'.
2018/11/07 22:14:46 ossec-testrule: ERROR: (1226): Error reading XML file 'etc/decoder.xml': XMLERR: File 'etc/decoder.xml' not found. (line 256).
2018/11/07 22:14:46 ossec-testrule: CRITICAL: (1202): Configuration error at '/etc/decoder.xml'.
2018/11/07 22:20:20 ossec-testrule: ERROR: (1226): Error reading XML file 'etc/decoder.xml': XMLERR: File 'etc/decoder.xml' not found. (line 256).
2018/11/07 22:20:20 ossec-testrule: CRITICAL: (1202): Configuration error at '/etc/decoder.xml'.
2018/11/07 22:29:35 ossec-testrule: ERROR: (1230): Invalid element in the configuration: 'rules'.
                                                                                     [ Read 54 lines ]
^G Get Help                    ^O WriteOut                    ^R Read File                   ^Y Prev Page                   ^K Cut Text                    ^C Cur Pos
^X Exit                        ^J Justify                     ^W Where Is                    ^V Next Page                   ^U UnCut Text                  ^T To Spell

**Comment by TJOSERAFAEL** [comment]
Hi @443ca ,

as you can see on the log, the **ossec.conf** file has errors, maybe its a typo or a bad label. Could you please post your **ossec.conf**?

Best regards.

**Comment by 443ca** [comment]
I was able to fix this issue (somewhat).   I ended up changing the ossec.conf file to have nothing in it other than the start and stop of the XML    The issue ended up being that there was no decoder.xml file.  I ended up finding the file online and manually creating the file.    

Now my issue is that my agents won't fully register.   On the agent ossec.conf file, I see them reaching out to the server.   On the server doing a TCP dump, I see the agent talking to the server but the server never sends anything back.

**Comment by vikman90** [comment]
Hi @443ca,

Apologies for not answering your last question. Did you manage to register your agents?

You will find the documentation to set up agents here: [Docs » User manual » Registering agents](https://documentation.wazuh.com/current/user-manual/registering/index.html).

Please let us know if you need further assistance with this issue, otherwise, let us close it.

Best regards.

**Comment by TJOSERAFAEL** [comment]
Let me close this issue. Feel free to reopen it if you need further assistance.
