### ISSUE TITLE
Vulnerability Scanner - Create an RTR that runs the same test as in GitHub Actions

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#18328]
|Part of Epic| Branch |
|---|---|
|#14153|[dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor)|

## Description
Currently, [tests and checks](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/.github/workflows/vulnerability-scanner-tests.yml) are run for the Vulnerability Scanner module, but the development team does not have the capability to run the same checks locally.

## Expected
Create an RTR that runs the same test as in GitHub Actions.
- Both runs should have the same results.
- GitHub Action and the RTR must use the same configuration file to avoid divergence.

## DoD
- [x] Test for different scenarios
- [x] Both runs should have the same results
- [x] CI pass

**Comment by sebasfalcone** [comment]
I will give a try to the [act](https://github.com/nektos/act) CLI tool
