### ISSUE TITLE
Vulnerability Scanner - Publish the results of tests and checks in artifact

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#18327]
|Part of Epic| Branch |
|---|---|
|#14153|[dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor)|

## Description
Currently, [tests and checks](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/.github/workflows/vulnerability-scanner-tests.yml) are run for the Vulnerability Scanner module, but the reports are not accessible.

## Expected
Publish in artifact the reports in case some of the checks fail, except for the coverage reports that must be published at each run.

## Examples
- https://github.com/wazuh/wazuh/blob/master/.github/workflows/rtr_syscheck.yml#L39
- https://github.com/wazuh/wazuh/actions/runs/5809891724

## DoD
- [x] Test for different scenarios
- [x] CI pass

**Comment by sebasfalcone** [comment]
## Testing

- [Failed Clang-format](https://github.com/wazuh/wazuh/actions/runs/5823992852)
- [Failed doxygen](https://github.com/wazuh/wazuh/actions/runs/5824108519)
- [Coverage](https://github.com/wazuh/wazuh/actions/runs/5824007989)
  - Only tested against failed coverage but the final result is the same
