### ISSUE TITLE
Maintain production and numbered branches post release v4.5.0

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#18336]
|||
| :--                             | :--                                                |
| **Version**                     | 4.5.0                                      |
| **Related issue**                     | https://github.com/wazuh/wazuh/issues/18077                              |

The goal is to complete the following tasks, each task must have a PR associated with this issue. 

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, merge-4.5.0-into-4.5.

Also, all PRs corresponding to the same phase (merge-X-into-Y) must be merged at the same time.

### Wazuh-qa -> @wazuh/qa 

Working on: https://github.com/wazuh/wazuh-qa/issues/4414

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-qa repository 
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-qa repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-qa repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-qa repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-qa repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-qa repository 

### Wazuh-jenkins -> @wazuh/qa 

Working on: https://github.com/wazuh/wazuh-jenkins/issues/5523

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-jenkins repository  
- [x] Delete branch `4.5.0` 
- [x] Merge branch `4.5` into `4.5.1` on wazuh-jenkins repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-jenkins repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-jenkins repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-jenkins repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-jenkins repository 

### Wazuh-automation -> @wazuh/cicd  

Working on: https://github.com/wazuh/wazuh-automation/issues/1218

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-automation repository  
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-automation repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-automation repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-automation repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-automation repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-automation repository 

### Wazuh-packages -> @wazuh/core

Working on: https://github.com/wazuh/wazuh-packages/issues/2339

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-packages repository  
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-packages repository  
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-packages repository  
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-packages repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-packages repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-packages repository 

### Wazuh -> @wazuh/core

Working on: https://github.com/wazuh/wazuh/issues/18343

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh repository
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh repository  
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh repository  
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh repository 
- [x] Merge branch `4.7.0` into `master` on wazuh repository 

### Wazuh-ansible -> @wazuh/cicd

Working on: https://github.com/wazuh/wazuh-ansible/issues/981

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-ansible repository 
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-ansible repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-ansible repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-ansible repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-ansible repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-ansible repository 

### Wazuh-docker -> @wazuh/cicd

Working on: https://github.com/wazuh/wazuh-docker/issues/932

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-docker repository 
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-docker repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-docker repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-docker repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-docker repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-docker repository 

### Wazuh-puppet -> @wazuh/cicd

Working on: https://github.com/wazuh/wazuh-puppet/issues/731

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-puppet repository 
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-puppet repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-puppet repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-puppet repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-puppet repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-puppet repository 

### Wazuh-kubernetes -> @wazuh/cicd

Working on: https://github.com/wazuh/wazuh-kubernetes/issues/424

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-kubernetes repository 
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-kubernetes repository 
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-kubernetes repository 
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-kubernetes repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-kubernetes repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-kubernetes repository 

### Wazuh-kibana-app -> @wazuh/frontend

Working on: https://github.com/wazuh/wazuh-kibana-app/issues/5771

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-kibana-app repository
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-kibana-app repository
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-kibana-app repository
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-kibana-app repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-kibana-app repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-kibana-app repository 

### Wazuh-splunk -> @wazuh/frontend

Working on: https://github.com/wazuh/wazuh-splunk/issues/1451

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-splunk repository
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-splunk repository
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-splunk repository
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-splunk repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-splunk repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-splunk repository 

### Wazuh-documentation -> @wazuh/documentation

Working on: https://github.com/wazuh/wazuh-documentation/issues/6328

- [x] Merge tag `v4.5.0` into `4.5` (fast-forward) on wazuh-documentation repository
- [x] Delete branch `4.5.0`
- [x] Merge branch `4.5` into `4.5.1` on wazuh-documentation repository
- [x] Merge branch `4.5.1` into `4.5.2` on wazuh-documentation repository
- [x] Merge branch `4.5.2` into `4.6.0` on wazuh-documentation repository 
- [x] Merge branch `4.6.0` into `4.7.0` on wazuh-documentation repository 
- [x] Merge branch `4.7.0` into `master` on wazuh-documentation repository

**Comment by BelenValdivia** [comment]
LGTM
