### ISSUE TITLE
Decoder regexp can't match logs correctly ossec-logtest

### ISSUE THREAD

**Issue by blacksper** [wazuh/wazuh#1833]
## Bug report

**OS**
Ubuntu16

**Wazuh version**
3.6.1

**Install type**
_manager

Bug description
----------------

I writing a decoder for my custom logs. When I have been doing this I noticed strange behavior and have no success with found any reasons for this.

My decoder is below

```
<decoder name="local_decoder_example">
    <prematch>^\d\d\d\d-\d\d-\d\d (\d\d:\d\d:\d\d)\p</prematch>
    <regex offset="after_prematch">(\w+)</regex>
    <order>one.one</order>
</decoder>
```
I run /var/ossec/bin/ossec-logtest and put my log string there

```
ossec-testrule: Type one log per line.
2018-10-31 13:38:11,Site

**Phase 1: Completed pre-decoding.
       full event: '2018-10-31 13:38:11,Site'
       timestamp: '2018-10-31 13:38:11,Si'
       hostname: 'wazuh-manager'
       program_name: '(null)'
       log: 'e'

**Phase 2: Completed decoding.
       No decoder matched.
```

As you can see, "No decoder matched". But when I delete 1 symbol in the "Site" word, I will have matched word.
```
ossec-testrule: Type one log per line.
2018-10-31 13:38:11,Sit


**Phase 1: Completed pre-decoding.
       full event: '2018-10-31 13:38:11,Sit'
       timestamp: '(null)'
       hostname: 'wazuh-manager'
       program_name: '(null)'
       log: '2018-10-31 13:38:11,Sit'

**Phase 2: Completed decoding.
       decoder: 'local_decoder_example'
       one.one: 'Sit'
```
But when I use another delimiter ";" I don't have any problems
```
ossec-testrule: Type one log per line.
2018-10-31 13:38:11;Veryverylongstring


**Phase 1: Completed pre-decoding.
       full event: '2018-10-31 13:38:11;Veryverylongstring'
       timestamp: '(null)'
       hostname: 'wazuh-manager'
       program_name: '(null)'
       log: '2018-10-31 13:38:11;Veryverylongstring'

**Phase 2: Completed decoding.
       decoder: 'local_decoder_example'
       one.one: 'Veryverylongstring'
```

I can't use another delimiter in my production logs and because of that I ask for help :)

**Comment by cristgl** [comment]
Hello @blacksper,
Your log is matching with a default decoder from the core, the only thing you can do is trying not to write logs that could match with the next samples:
```
     -   Dec 29 10:00:01 
     -   2015 Dec 29 10:00:01
     -   2007-06-14T15:48:55-04:00 for syslog-ng isodate
     -   2009-05-22T09:36:46.214994-07:00 for rsyslog
     -   2015-04-16 21:51:02,805 (proftpd 1.3.5)
```
Yours is matching with the last one. This decoders extract the fields `timestamp`, `hostname`, `program_name`, etc... Because of that we cannot help you with this, the only solution would be to have a different delimiter. Thank you for understanding.

Best regards

**Comment by cristgl** [comment]
Hello @blacksper,

As it has been so long that this issue was opened and it is not used anymore, I am going to proceed and close it. Do not hesitate to reopen it, open a new one or write a mail to our mailing list if you have any doubts left.

Best regards,
Cristina

**Comment by coopjab** [comment]
> 
> 
> Hello @blacksper,
> 
> As it has been so long that this issue was opened and it is not used anymore, I am going to proceed and close it. Do not hesitate to reopen it, open a new one or write a mail to our mailing list if you have any doubts left.
> 
> Best regards,
> Cristina

can u open this one i have doubt
