### ISSUE TITLE
Investigate possible modularization of core repository framework integration tests 

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18355]
## Description

During the migration of the [AWS QA integration tests 
](https://github.com/wazuh/wazuh/issues/17788) it was found that a lot of tests follow the same behavior when configuring the tests before running it. 

For example AWS test start following this configuration:

```
MODULE = 'discard_regex_test_module'
TEST_DATA_PATH = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'data')
CONFIGURATIONS_PATH = os.path.join(TEST_DATA_PATH, TEMPLATE_DIR, MODULE)
TEST_CASES_PATH = os.path.join(TEST_DATA_PATH, TEST_CASES_DIR, MODULE)

# ---------------------------------------------------- TEST_PATH -------------------------------------------------------
configurations_path = os.path.join(CONFIGURATIONS_PATH, 'configuration_discard_regex.yaml')
cases_path = os.path.join(TEST_CASES_PATH, 'cases_discard_regex.yaml')

configuration_parameters, configuration_metadata, case_ids = get_test_cases_data(cases_path)
configurations = load_configuration_template(
    configurations_path, configuration_parameters, configuration_metadata
)
```

Also, after analyzing other tests such as FIM and GCloud tests follow the same configuration behavior. 

Another optimization that should be analyzed is the one mentioned [here](https://github.com/wazuh/wazuh-qa/pull/4278#pullrequestreview-1571798153) regarding the unification of similar test cases declared in the YAML files into a single test to avoid code repetition.

The scope of the issue is to determine if this configuration before all tests can be modularized and optimized to define a testing behavior for better scalability or if there is a specific reason why the test behavior is the way it is.

**Comment by Selutario** [comment]
Closing this for now since it has been partially included in the AWS IT migration and because it does not fit into any current objective.
