### ISSUE TITLE
Release 4.5.1 - Release Candidate 1 - WPK upgrade tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18409]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|https://github.com/wazuh/wazuh/issues/18366|4.5.1|RC 1|[v4.5.1-rc1](https://github.com/wazuh/wazuh/tree/v4.5.1-rc1)| https://github.com/wazuh/wazuh/issues/18248 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail, and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check result. |
| :yellow_circle:  | There is at least one expected failure or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a ZIP or TXT file. This report can be used by the auditors to dig deeper into any possible failures and details.

## Tests

- Ensure that when upgrading an agent in macOS (ARM) through WPK using an Intel package nothing is broken in the current environment.
- Ensure that the upgrade task fails with a clear message.

### macOS

|OS|Version|Status|Upgrade fail|Upgrade OK|Comments
|----|-----------|--------|-------|------------------|----------|
| Monterey|4.5.1 (arm) -> 4.5.1 (intel) | 🔴 |  🔴 |  🔴 | | ||
| Ventura |4.5.1 (arm) -> 4.5.1 (intel) | 🔴 |  🔴 |  🔴 | | ||

## Conclusions

After conducting tests, the following observations were made:
1. The error message that appears when attempting to upgrade from a macOS (arm64) agent using an intel64 WPK package lacks clarity for the user (issue created: https://github.com/wazuh/wazuh/issues/18436)
2. The instructions about installing the macOS agent leave the service as "not running" (issue created: https://github.com/wazuh/wazuh-documentation/issues/6348)

## Validation of auditors

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted to close this issue.

- [ ] @damarisg 
- [ ] @fcaffieri

**Comment by mauromalara** [comment]
## TEST: macOS Monterey (Intel package -> Intel package) 🔵

### From 4.5.0 (intel) -> 4.5.1 (intel) 🔵 


#### UPGRADE FAIL 🔵

- [ ] The wazuh home backup is restored correctly (no traces of the installation, only the `.tar.gz` backup, and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - [ ] `/Library/LaunchDaemons/`
  - [ ] `/Library/StartupItems/` 
  - [ ] `/Library/StartupItems/WAZUH/` 
  - [ ] `/Library/LaunchDaemons/`
- [ ] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)

**Upgrade report:** [Download macOS Monterey - fail upgrade report]()

**Comment by mauromalara** [comment]
# TEST: macOS Ventura (ARM package -> Intel package) 🔵

## From 4.5.1 (ARM) -> 4.5.1 (Intel) [Force] 🔵

<details><summary>Parameters to create the package to force failure</summary></br>

<img width="159" alt="image" src="https://github.com/wazuh/wazuh/assets/39094716/b623982b-e1bd-4492-931b-1a73ad1ef8e2"> <img width="184" alt="image" src="https://github.com/wazuh/wazuh/assets/39094716/c65b31e3-27fb-47ca-821a-6049e218740b"> <img width="171" alt="image" src="https://github.com/wazuh/wazuh/assets/39094716/a7a265bd-f644-4356-bb06-707472182ac1"> <img width="185" alt="image" src="https://github.com/wazuh/wazuh/assets/39094716/a1156568-36b5-421d-9c6b-fee8c6d284a7">


</details>

- Branch used to generate package: [v4.5.1-rc1-wpk-fail](https://github.com/wazuh/wazuh/tree/v4.5.1-rc1-wpk-fail)
- Target package (case: Upgrade fail) [intel64]: [wazuh-agent-4.5.1-rc1.wpk.fail.intel64.pkg](https://packages-dev.wazuh.com/warehouse/test/4.5/macos/wazuh-agent-4.5.1-rc1.wpk.fail.intel64.pkg)

### UPGRADE FAIL 🔵

---

**Conclusions**

WIP.

**Upgrade report:** [Download macOS Ventura - fail upgrade report]()


---

**Steps**

<details><summary>Pre-requirements (Manager)</summary></br>

1. Download the manager (4.5.1)
```bash
curl -sO https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.5.1-1_amd64.deb
```

2. Install the manager
```bash
dpkg -i wazuh-manager_4.5.1-1_amd64.deb

systemctl daemon-reload

systemctl enable wazuh-manager

systemctl start wazuh-manager
```

3. Download the necessary package to test the failure in the upgrade process
```bash
curl -sO https://packages-dev.wazuh.com/warehouse/test/4.5/macos/wazuh-agent-4.5.1-rc1.wpk.fail.intel64.pkg
```

4. Backup `ossec.log` before failure
```
cp /var/ossec/logs/ossec.log ./ossec.log.before.fail
```

</details>





<details><summary>Pre-requirements (Agent)</summary></br>

1. Install `tree` in macOS (as a non-root user)
```bash
brew install tree
```

2. Download the agent (4.5.1)
```bash
curl -sO https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.5.1-1.arm64.pkg
```

3. Install the agent
```bash
echo "WAZUH_MANAGER='IP'" > /tmp/wazuh_envs && installer -pkg wazuh-agent-4.5.1-1.arm64.pkg -target /
```

4. Start the agent
```bash
/Library/Ossec/bin/wazuh-control start
```

6. Check connection with the manager (**from the manager**)
```bash
/var/ossec/bin/agent_control -l

```

7. Create needed scripts
```bash
sh-3.2# nano get_initial_state.sh
sh-3.2# nano get_final_state.sh
```

8. Backup the `ossec.log` file
```bash
cp /Library/Ossec/logs/ossec.log ./ossec.log.agent.before.fail
```

</details>




<details><summary>Test steps</summary></br>

(From the Agent)

1. Run the `get_initial_state.sh` script
```bash
bash get_initial_state.sh
```

(From the Manager)

2. Try the upgrade with a failure
```bash
/var/ossec/bin/agent_upgrade -a 001 -f /home/ubuntu/wazuh-agent-4.5.1-rc1.wpk.fail.intel64.pkg -F

```

3. Backup the `ossec.log` file
```
cp /var/ossec/logs/ossec.log ./ossec.log.after.failure
```

(From the Agent)

4. Run the `get_final_state.sh` script
```bash
bash get_final_state.sh
```

5. Get the `ossec.log` file after the upgrade fail
```bash
cp /Library/Ossec/logs/ossec.log ./ossec.log.agent.after.fail
```

6. Get the `upgrade.log` file after the upgrade fails (As the upgrade fails, the result is expected)
```bash
$ cp /Library/Ossec/logs/upgrade.log ./upgrade.log.agent.after.fail
cp: /Library/Ossec/logs/upgrade.log: No such file or directory
```

7. Compress all the results in a `.zip` file
```
mkdir upgrade_fail_report
mv final_state.txt initial_state.txt ossec.log.agent.* upgrade_fail_report/
zip -r upgrade_fail_report.zip upgrade_fail_report/
```

(From your local machine) - Remember to change the permissions of the zip file to copy them without any problems through SCP

9. Collect the evidence from the remote VM
```
scp host@ip:/Users/vagrant/upgrade_fail_report.zip .
```

</details>


**Checks after test execution**

- [ ] The wazuh home backup is restored correctly (no traces of the installation, only the `.tar.gz` backup, and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - [ ] `/Library/LaunchDaemons/`
  - [ ] `/Library/StartupItems/` 
  - [ ] `/Library/StartupItems/WAZUH/` 
  - [ ] `/Library/LaunchDaemons/`
- [ ] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)


</br>


### UPGRADE OK 🔵

---

**Conclusions**


WIP.


**Upgrade report:** [Download macOS Ventura - upgrade ok report]()


---

**Steps**

<details><summary>Pre-requirements (Manager)</summary></br>

1. Download the manager (4.5.1)
```bash
curl -sO https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.5.1-1_amd64.deb
```

2. Install the manager
```bash
dpkg -i wazuh-manager_4.5.1-1_amd64.deb

systemctl daemon-reload

systemctl enable wazuh-manager

systemctl start wazuh-manager
```

3. Download the necessary package to test the the upgrade process
```bash
curl -sO https://packages-dev.wazuh.com/pre-release/wpk/macos/x86_64/pkg/wazuh_agent_v4.5.1_macos_x86_64.wpk
```

4. Backup the `ossec.log` file
```
cp /var/ossec/logs/ossec.log ./ossec.log.before.upgrade
```

</details>





<details><summary>Pre-requirements (Agent)</summary></br>

1. Install `tree` in macOS (as a non-root user)
```bash
brew install tree
```

2. Download the agent (4.5.1)
```bash
curl -sO https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.5.1-1.arm64.pkg
```

3. Install the agent
```bash
echo "WAZUH_MANAGER='IP'" > /tmp/wazuh_envs && installer -pkg wazuh-agent-4.5.1-1.arm64.pkg -target /
```

4. Start the agent
```bash
/Library/Ossec/bin/wazuh-control start
```

6. Check connection with the manager (**from the manager**)
```bash
/var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: macos-12, IP: any, Active
```

7. Create needed scripts
```bash
sh-3.2# nano get_initial_state.sh
sh-3.2# nano get_final_state.sh
```

8. Backup the `ossec.log` file
```bash
cp /Library/Ossec/logs/ossec.log ./ossec.log.agent.before.fail
```

</details>




<details><summary>Test steps</summary></br>

(From the Agent)

1. Run the `get_initial_state.sh` script
```bash
bash get_initial_state.sh
```

(From the Manager)

2. Try the upgrade
```bash
/var/ossec/bin/agent_upgrade -a 001 -f /home/ubuntu/wazuh_agent_v4.5.1_macos_x86_64.wpk -F

```

3. Backup the `ossec.log` file
```
cp /var/ossec/logs/ossec.log ./ossec.log.after.upgrade
```

(From the Agent)

4. Run the `get_final_state.sh` script
```bash
bash get_final_state.sh
```

5. Get the `ossec.log` file after the upgrade fail
```bash
cp /Library/Ossec/logs/ossec.log ./ossec.log.agent.after.fail
```

6. Get the `upgrade.log` file after the upgrade
```bash
cp /Library/Ossec/logs/upgrade.log ./upgrade.log.agent.after.fail
```

7. Compress all the results in a `.zip` file
```
mkdir upgrade_ok_report
mv final_state.txt initial_state.txt ossec.log.agent.* upgrade_ok_report/
zip -r upgrade_ok_report.zip upgrade_ok_report/
```

(From your local machine) - Remember to change the permissions of the zip file to copy them without any problems through SCP

9. Collect the evidence from the remote VMs
```
scp host@ip:/Users/vagrant/upgrade_ok_report.zip .
```

</details>


**Checks after test execution**

- [ ] The wazuh home backup is restored correctly (no traces of the installation, only the `.tar.gz` backup, and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - [ ] `/Library/LaunchDaemons/`
  - [ ] `/Library/StartupItems/` 
  - [ ] `/Library/StartupItems/WAZUH/` 
  - [ ] `/Library/LaunchDaemons/`
- [ ] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)

**Comment by juliamagan** [comment]
LGTM

**Comment by fcaffieri** [comment]
LGTM
