### ISSUE TITLE
Release 4.5.1 - RC 1 - API integration tests

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18415]
The following issue aims to run all [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) for the current release candidate, report the results, and open new issues for any encountered errors.

## API integration tests information
|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         |           https://github.com/wazuh/wazuh/issues/18366                           |
| **Version**                              |                           4.5.1                 |
| **Release candidate #**                  |            RC 1                                |
| **Tag**                                  |                   [v4.5.1-rc1](https://github.com/wazuh/wazuh/tree/v4.5.1-rc1)                         |
| **Previous API integration tests issue** |                           https://github.com/wazuh/wazuh/issues/18079                 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/18415#issuecomment-1677656526) and [here](https://github.com/wazuh/wazuh/issues/18415#issuecomment-1678785541).

All tests have passed and the fails have been reported or justified. I, therefore, conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @nico-stefani 
- [ ]  @damarisg

**Comment by EduLeon12** [comment]
## Build Parameters

| Field | Value |
| -- | -- |
| Source reference | v4.5.1-rc1 |
| Jenkins reference | 4.5.1 |
| Pytest args | -v --tb=short |
| Test list | * |
| Verbosity | -- | 
| Checkrun reference | -- |
| Label | integration_burst |

**Comment by EduLeon12** [comment]
## Test Results

[Test-Artifacts](https://github.com/wazuh/wazuh/files/12337324/archive.zip)

**Comment by EduLeon12** [comment]
## Test report

[test_artifacts_2](https://github.com/wazuh/wazuh/files/12343676/archive.2.zip)

## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_agent_DELETE_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_manager_endpoints.tavern.yaml | 32 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_agent_endpoints.tavern.yaml | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by damarisg** [comment]
LGTM!
