### ISSUE TITLE
Error when compiling the provided selinux-parts into a policy.

### ISSUE THREAD

**Issue by AdmiraalA** [wazuh/wazuh#18428]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
4.5.0                  Selinux                      Agent                  Sources                  RHEL 9.2

curl -sO https://raw.githubusercontent.com/wazuh/wazuh-documentation/4.5/resources/selinux/agent/wazuhT.te
curl -sO https://raw.githubusercontent.com/wazuh/wazuh-documentation/4.5/resources/selinux/agent/wazuhT.fc
make -f /usr/share/selinux/devel/Makefile

Gives : 
Compiling targeted wazuhT module
wazuhT.te:57:ERROR 'Class process would have too many permissions to fit in an access vector with permission read' at token '}' on line 3453:
role unconfined_r;
class process { transition getattr getpgid getsession setrlimit setsched signull open read};
/usr/bin/checkmodule:  error(s) encountered while parsing configuration
make: *** [/usr/share/selinux/devel/include/Makefile:157: tmp/wazuhT.mod] Error 1

**Comment by pereyra-m** [comment]
Hi @AdmiraalA 

Thank you for reporting this.
We've confirmed the policy requires an update, it'll be tracked at this issue
- https://github.com/wazuh/wazuh-documentation/issues/7916

A workaround was shared but **it hasn't** been tested.
For a production environment, it is better to wait for the development of a new one.

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
