### ISSUE TITLE
Setting a long admin password breaks the Wazuh Server

### ISSUE THREAD

**Issue by RobertBrown3** [wazuh/wazuh#18435]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.4.5|            wazuh-manager(?)|      Single Node    |         Docker Compose        |            Ubuntu V22.04

I installed the standard Wazuh single- node system on my server and successfully started it. I then performed the procedure for changing the password described in the link below:

[Change Password](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-pwd-existing-usr)

I followed those instructions to the letter, but in line with my security policy, I created a randomized 30- character password.  I created the hash, then placed the hash and password into their appropriate YML files. After restarting, I exec'd into the indexer and performed the security steps.

Once I logged into the mWazuh web page, I got the following failures on initialization:

` [API connection] Wazuh API is down
[Alerts index pattern] No template found for the selected index-pattern title [wazuh-alerts-*]

`
 
Please refer to [Issue #18320](https://github.com/wazuh/wazuh/issues/18320) for more information about this failure.

After I posted Issue #18320 it occurred to me that the hash was rather long due to the length of my password. I thought that perhaps Wazuh might not be reading the hash or the password properly because of the length of the password. As a result, I redid the password change procedure, only this time I changed the password to a randomized set of 14 characters (14 is the length of the default "SecretPassword").

Wazuh now starts up without failures.

There is clearly a limit to the number of characters that should go into a password. I do not know what that limit is, but it is certainly somewhere between 14 and 30 characters. Beyond that limit, the indexer and manager apparently cannot communicate with each other and Wazuh fails to function. It is unclear whether the failure is due to the password being too long or if the generated hash gets truncated.

Either a fix needs to be applied that allows users to use longer passwords, or a warning needs to be put into the documentation letting people know the limits on password length.

**Comment by AlexRuiz7** [comment]
Hello @RobertBrown3 

I tried to replicate the issue, and I was able to use a 30 characters long password (`jU7#pT!sR2@lY$8#fE6&mG4^qZ9*wA`) using a Docker compose project of 2 indexer nodes and 1 dashboard nodes.

I've been reviewing the `wazuh-manager` logs you shared and looks like the problem might be on the API/Manager side, as per this log line:

```
single-node-wazuh.manager-1    | Exiting: error loading config file: yaml: line 17: did not find expected key
```

I'll transfer this issue to the appropriate team so they can continue the troubleshooting process.

**Comment by datdamnzotz** [comment]
Might need to have the special characters escaped?

YAML doesn't require quoting most strings but you'll want to quote special characters if they fall within a certain list of characters. Use quotes if your value includes any of the following special characters: {, }, [, ], &, *, #, ?, |, -, <, >, =, !, %, @, : also ` and ,

From
https://stackoverflow.com/questions/37015652/how-does-yaml-interpret-special-characters

Did you try it with just Alpha numeric? [a-Z][0-9]? at longer lengths

**Comment by AlexRuiz7** [comment]
Closed by https://github.com/wazuh/wazuh-documentation/pull/7321
