### ISSUE TITLE
Logcollector floods with information messages when a file is removed

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1843]
Logcollector periodically checks if the deleted files have reappeared in order to monitor them again. The problem is that it displays one information message at a time. The checking frequency depends on the value of **logcollector.vcheck_files**.

> 2018/11/09 11:46:10 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:13 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:16 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:19 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:22 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:25 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:28 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.
> 2018/11/09 11:46:31 ossec-logcollector: INFO: (1959): File '/tmp/t2.log' does not exist. Forgetting.

There is no need to inform with every check a file still does not exist. It would be more convenient to include a debug message.

**Seen in Wazuh 3.7.**

**Comment by chemamartinez** [comment]
Fixed at #1893
