### ISSUE TITLE
Drop SCA events have an increase in 4.5.1 footprint test - SCA

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18445]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-RC1 | SCA | Manager | Packages | CentOS |

Running footprint test - SCA (https://github.com/wazuh/wazuh/issues/18399#issuecomment-1680215182), it was possible to see that number of Drops of SCA events has increased compared to previous versions.
Logs do not show relevant abnormalities, however, it requires further investigation.

**Comment by vikman90** [comment]
@pro-akim comparing:

- https://github.com/wazuh/wazuh/issues/18266
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.0/B4229-360m/B4229_manager_centos/plots/Test_stress_B4229_manager_analysisd_state_Queues_state.png)
- https://github.com/wazuh/wazuh/issues/18399
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4243-3600m/B4243_manager_centos/plots/Test_stress_B4243_manager_analysisd_state_Queues_state.png)


4.5.0 has SCA queue peaks up to ~9% during 4:13:31 hours. If we see the first 4:13 hours of the 4.5.1 test, the peaks are similar. They grow up to ~27 % just after that time, but we don't have data enough to consider this as a bug.

Best!

**Comment by rauldpm** [comment]
## Update report

- With the analysis of the issue https://github.com/wazuh/wazuh/issues/18666, it can be seen that the loss of events is repeated
- When comparing the latest 2.5d tests that we have, it is observed that in 4.4.1 it does not happen

![image](https://github.com/wazuh/wazuh/assets/14913942/81381a95-cfa2-496a-82a6-c382dfe77879)
![image](https://github.com/wazuh/wazuh/assets/14913942/46738790-14eb-468b-bd91-c7669a22b54f)
![image](https://github.com/wazuh/wazuh/assets/14913942/af4b836f-4eec-4e93-90ca-174af8ba3bdd)

- It is necessary to determine again if we are facing abnormal behavior or not

**Comment by TomasTurina** [comment]
The analysis is quite similar to what @vikman90 did [before](https://github.com/wazuh/wazuh/issues/18445#issuecomment-1680405005). This is the state of the queue:

<img width="1504" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/fa5d2231-bdea-48bb-a45a-371e639c2f80">

The behavior of the queue is similar.

On the other hand, we can see that only 10/11 events were dropped in the total duration of the test, which was 2.5 days.

I don't consider this as a bug (again). It would be convenient to define some tolerance parameters, 10 events dropped (or even a little more) in a test of this duration can be circumstantial and is not a problem. We can close this issue.
