### ISSUE TITLE
Engine - Enhanced Syntax for Windows Decoder

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#18458]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Engine | Manager| - | - |

## Description:
In light of the latest advancements in the engine, we are undertaking changes to refine the syntax used in our Windows decoders. These updates are aimed at enhancing readability and ensuring user-friendliness.

Key objectives for this update include:

- [ ] Enhanced Event.Original Handling: We will be revisiting the handling of event.original within the system decoders. Going forward, this field will consistently reflect the original event as captured by the agent, as opposed to its representation after being sent by the agent.

- [ ] Check Stages: Our team will be working to update the check stages within the decoders. This entails optimizing the process to ensure smoother and more efficient checks for various conditions.

- [ ] Syntax and Visualization Improvements: During this process, we will meticulously review the arrangement of stages, spacing between expressions, and field names. The aim is to create a more intuitive and comprehensible visual structure for users, making it easier to interpret the decoding process.

We believe that these changes will significantly contribute to a more seamless experience when working with the engine.

**Comment by juliancnn** [comment]
Merged!
