### ISSUE TITLE
Modulesd has different write-ops activity in 4.5.1 to previous version in Ubuntu Agent

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18453]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-RC1 | Modulesd | Agent | Packages | Ubuntu |

Running 4.5.1 RC1 - Footprint test - ALL-EXCEPT-SYSCHECK (https://github.com/wazuh/wazuh/issues/18400), it was possible to see a different pattern of write-ops activity of Modulesd 4.4.2-RC2 

No abnormalities were detected in logs and Ubuntu Agent activity, however, further research should be performed.

Attached:
[CSV and Logs](https://github.com/wazuh/wazuh/files/12361384/csv.and.logs.zip)

**Comment by nmkoremblum** [comment]
This might be related to #18451

**Comment by TomasTurina** [comment]
Closing since it is related to https://github.com/wazuh/wazuh/issues/18446.
