### ISSUE TITLE
Logcollector does not check files that did not exist when Wazuh started

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1846]
If a file that logcollector was monitoring disappears, it is checked periodically to resume monitoring when it appears again. This does not happen if the file did not exist from the first moment.

**Comment by Skeptor** [comment]
Hi @crolopez 
We read your issue and we are going to change the behavior of Logcollector to unify the results.
From now, a localfile will have a number of attempts to be opened according the internal options.
If it couldn't be opened after those tries it would be ignored.
Regards,
Pablo

**Comment by chemamartinez** [comment]
Fixed at #1893
