### ISSUE TITLE
Fix API integration tests mapping file

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#18469]
## Description
The mapping file for API IT contains which tests should be run depending on which files are modified in a PR. This JSON file is generated using the `_test_mapping.py` script that can be found [here](https://github.com/wazuh/wazuh/tree/master/api/test/integration/mapping).

However, in the development of the new `POST /events` endpoint, the file was modified manually:
https://github.com/wazuh/wazuh/blob/a272f03d698ad355fcdcb7ad5f7a37a693da54bb/api/test/integration/mapping/integration_test_api_endpoints.json#L397-L403

The problem with manual modifications is that they are not kept if the JSON file needs to be regenerated (for example, when a new module is included). The file should always be the result of running `python3 _test_mapping.py`. But for it to work correctly, the test and the related modules should contain the same name. For example, if a new module `framework/wazuh/event.py` was included, the AIT should be
```
test_event_endpoints.tavern.yaml
```
instead of
```
test_webhook_endpoints.tavern.yaml
```

Similarly, if a new models file was created, it should be
```
api/models/event_ingest_model.py
```
instead of
```
api/models/events_ingest_model.py
```

All new modules included in this PR https://github.com/wazuh/wazuh/pull/17670 should be reviewed and, when necessary, also renamed to fix the problem. Then, a new mapping file needs to be created.  
## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Fixed a typo

**Comment by GGP1** [comment]
## Update

Solved a conflict and rebased master.

Moved to on hold until the check `Build Windows i386 agent package` passes.

**Comment by GGP1** [comment]
## Update

Rebased master because it was outdated and that caused some checks to fail.

**Comment by GGP1** [comment]
## Update

Updated the base branch to pull the fix to the failed API integration test.

**Comment by GGP1** [comment]
## Update

The AIT check has failed tests due to the following issues https://github.com/wazuh/wazuh/issues/19722 and https://github.com/wazuh/wazuh/issues/19724. I'm blocking this issue until they fixed.

**Comment by GGP1** [comment]
## Update

Rebased master to fetch AIT fixes and re-run the checks.

**Comment by GGP1** [comment]
## Update

Rolled-back a RBAC policy change and fixed a mapping to the integration tests pointing to the `rbac/event` folder.
