### ISSUE TITLE
JSON syslog output very high CPU percentage

### ISSUE THREAD

**Issue by lsayanes** [wazuh/wazuh#18471]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | wazuh-csyslogd | Manager | os_csyslogd | Linux |

Using `syslog_output` with JSON format `wazuh-csyslogd` raises CPU usage above **90%**

Example configuration in _ossec.conf_:
```
<syslog_output>
    <server>10.211.55.7</server>
    <level>7</level>
    <format>json</format>
</syslog_output>
```
Top:

![csyslog](https://github.com/wazuh/wazuh/assets/68856625/a1604ff4-b2a7-4715-b823-4b1ea413eb68)

**Comment by leba-atr** [comment]
This was already reported months ago in https://github.com/wazuh/wazuh/issues/17604. Just mentioning it here so that people get credited.
