### ISSUE TITLE
Release 4.5.1 - RC 2 - Integration tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18492]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `v4.5.1-rc2`|  https://github.com/wazuh/wazuh-qa/releases/tag/v4.5.1-rc2 |  `v4.5.1-rc2`  | https://github.com/wazuh/wazuh/commit/18ad05746eadc817f4d2db0b35287d463b210ad1  | 

We are going to check that the integration tests of the `4.5`  branch of `wazuh-qa` work correctly using the [v4.5.1-rc2](https://github.com/wazuh/wazuh/tree/v4.5.1-rc2) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

- https://github.com/wazuh/wazuh/issues/18475

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|:large_blue_circle:|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"> :green_circle:   </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;"> :green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"> :green_circle: </td>
<td style="width: 79px;">:green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"> :green_circle:  </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;"> :green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;"> :green_circle:</td>
<td style="width: 97px;"> :green_circle:</td>
<td style="width: 97px;" colspan="2">:green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:green_circle: </td>
<td style="width: 97px;">:green_circle: </td>
<td style="width: 97px;" colspan="2">:green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"> :red_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">:green_circle: </td>
<td style="width: 99px;">:green_circle: </td>
<td style="width: 79px;">:red_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">:green_circle: </td>
</tr>
</tbody>
</table>

## Evidence
- Test Launcher: https://ci.wazuh.info/view/Tests/job/Test_integration_launcher/186/

## Conclusion  :green_circle: 

All tests passed with the exception of the tests that will be detailed below. The errors were known Issues and were expected to fail.

- Vulnerability Detector  failed due to known Issue https://github.com/wazuh/wazuh-qa/issues/4370
- Syscollector Windows Agent failed due to known Issue https://github.com/wazuh/wazuh-qa/issues/4230

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @damarisg / @fcaffieri

**Comment by Rebits** [comment]
Relaunched Syscollector macOS tests here https://ci.wazuh.info/job/Test_integration/42543/console

**Comment by Deblintrake09** [comment]
## Detected Failures

### Vulnerability Detector

The test `test_feeds/test_download_feeds` failed on the SUSE feed cases as the Feed was not downloaded before the test's timeout occurred. This is a common occurrence related to the SUSE FTP connection speed.

- [Evidence](https://ci.wazuh.info/job/Test_integration/42508/)
```
  
        # Check that the feed update has started
        evm.check_provider_database_update_start_log(metadata['provider_name'])
        # Check that the feed has been updated successfully
>       evm.check_provider_database_update_finish_log(provider_name=metadata['provider_name'],
                                                      timeout=metadata['download_timeout'])

test_vulnerability_detector/test_feeds/test_download_feeds.py:139: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.5.1-py3.10.egg/wazuh_testing/modules/vulnerability_detector/event_monitor.py:144: in check_provider_database_update_finish_log
    check_vuln_detector_event(file_monitor=log_monitor, timeout=timeout,
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.5.1-py3.10.egg/wazuh_testing/modules/vulnerability_detector/event_monitor.py:54: in check_vuln_detector_event
    file_monitor.start(timeout=timeout, update_position=update_position, accum_results=accum_results,
/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.5.1-py3.10.egg/wazuh_testing/tools/monitoring.py:202: in start
    self._result = monitor.start(timeout=timeout, callback=callback, accum_results=accum_results,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wazuh_testing.tools.monitoring.QueueMonitor object at 0x7f37df87e110>
timeout = 360
callback = <function make_vuln_callback.<locals>.<lambda> at 0x7f37df9316c0>
accum_results = 1, update_position = True, timeout_extra = 0
error_message = 'Could not find SUSE Linux Enterprise Desktop 15 feed finished log'

    def start(self, timeout=-1, callback=_callback_default, accum_results=1, update_position=True, timeout_extra=0,
              error_message=''):
        """Start the queue monitoring until the stop method is called."""
        if not self._continue:
            self._continue = True
            self._abort = False
            result = None
    
            while self._continue:
                if self._abort:
                    self.stop()
                    if error_message:
                        logger.error(error_message)
                        logger.error(f"Results accumulated: "
                                     f"{len(result) if isinstance(result, list) else 0}")
                        logger.error(f"Results expected: {accum_results}")
>                   raise TimeoutError(error_message)
E                   TimeoutError: Could not find SUSE Linux Enterprise Desktop 15 feed finished log

/usr/local/python-3.10/lib/python3.10/site-packages/wazuh_testing-4.5.1-py3.10.egg/wazuh_testing/tools/monitoring.py:470: TimeoutError
---------------------------- Captured stderr setup -----------------------------
2023/08/17 21:10:47 wazuh-modulesd[12476] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2023/08/17 21:10:47 wazuh-modulesd[12476] main.c:77 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/08/17 21:10:47 wazuh-modulesd[12476] wmodules-vuln-detector.c:654 at wm_vuldet_read_provider(): DEBUG: Added suse (15-desktop) feed. Interval: 3600s | Path: 'none' | Url: 'none' | Timeout: 300s
----------------------------- Captured stderr call -----------------------------
2023-08-17 21:16:48,526 - wazuh_testing - ERROR - Could not find SUSE Linux Enterprise Desktop 15 feed finished log
2023-08-17 21:16:48,526 - wazuh_testing - ERROR - Results accumulated: 0
2023-08-17 21:16:48,526 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call -------------------------------
ERROR    wazuh_testing:monitoring.py:466 Could not find SUSE Linux Enterprise Desktop 15 feed finished log
ERROR    wazuh_testing:monitoring.py:467 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:469 Results expected: 1
- generated html file: file:///tmp/Test_integration_B42508_20230817210954/report.html -
=========================== short test summary info ============================
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[SUSE Linux Enterprise Server 11]
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[SUSE Linux Enterprise Server 12]
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[SUSE Linux Enterprise Server 15]
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[SUSE Linux Enterprise Desktop 12]
FAILED test_vulnerability_detector/test_feeds/test_download_feeds.py::test_download_feeds[SUSE Linux Enterprise Desktop 15]
======= 5 failed, 238 passed, 2 skipped, 2 xfailed in 8957.06s (2:29:17) =======
```

> **Note**
> This is related to Known Issue https://github.com/wazuh/wazuh-qa/issues/4370

### Syscollector

Syscollector Windows agent failed with known Issue https://github.com/wazuh/wazuh-qa/issues/4230

```
>                   raise TimeoutError(error_message)
E                   TimeoutError: Could not find this event in None: DEBUG: Ending hotfixes scan

C:\Python37\lib\site-packages\wazuh_testing-4.5.1-py3.7.egg\wazuh_testing\tools\monitoring.py:470: TimeoutError
---------------------------- Captured stdout setup ----------------------------
The Wazuh service is starting.

The Wazuh service was started successfully.



---------------------------- Captured stderr setup ----------------------------
2023-08-18 10:38:52,762 - wazuh_testing - DEBUG - Wazuh control set to True
2023-08-18 10:38:52,762 - wazuh_testing - DEBUG - Ignore error set to True
2023-08-18 10:38:52,762 - wazuh_testing - DEBUG - Restarting wazuh using wazuh-control
----------------------------- Captured log setup ------------------------------
DEBUG    wazuh_testing:conftest.py:960 Wazuh control set to True
DEBUG    wazuh_testing:conftest.py:964 Ignore error set to True
DEBUG    wazuh_testing:conftest.py:973 Restarting wazuh using wazuh-control
---------------------------- Captured stderr call -----------------------------
2023-08-18 10:39:04,985 - wazuh_testing - ERROR - Could not find this event in None: DEBUG: Ending hotfixes scan
2023-08-18 10:39:04,985 - wazuh_testing - ERROR - Results accumulated: 0
2023-08-18 10:39:04,985 - wazuh_testing - ERROR - Results expected: 1
------------------------------ Captured log call ------------------------------
ERROR    wazuh_testing:monitoring.py:466 Could not find this event in None: DEBUG: Ending hotfixes scan
ERROR    wazuh_testing:monitoring.py:467 Results accumulated: 0
ERROR    wazuh_testing:monitoring.py:469 Results expected: 1
- generated html file: file://C:\tmp\Test_integration_B42543_20230818111126\report.html -
=========================== short test summary info ===========================
FAILED test_syscollector/test_syscollector_configuration.py::test_syscollector_scanning[check_syscollector_scan]
============= 1 failed, 25 passed, 1 xfailed in 228.28s (0:03:48) =============
```

**Comment by damarisg** [comment]
LGTM!
