### ISSUE TITLE
Error deploying Wazuh Manager in Docker

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh#1850]
## Bug report

**OS**
Docker FROM phusion/baseimage:latest

**Wazuh version**
3.7.0

**Wazuh API version**
3.7.0

**Install type**
Manager

**Install method**
Packages

**Log sample**
wazuh_1          | Installing api/configuration
wazuh_1          | Installing etc/client.keys
wazuh_1          | Installing etc/decoders
wazuh_1          | Installing etc/lists
wazuh_1          | Installing etc/local_internal_options.conf
wazuh_1          | Installing etc/localtime
wazuh_1          | Installing etc/ossec.conf
wazuh_1          | Installing etc/ossec-init.conf
wazuh_1          | Installing etc/rootcheck
wazuh_1          | Installing etc/rules
wazuh_1          | Installing etc/shared
wazuh_1          | Installing etc/sslmanager.cert
wazuh_1          | Installing etc/sslmanager.key
wazuh_1          | Installing logs
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.
wazuh_1          | Installing queue/syscheck
wazuh_1          | Error executing command: 'cp -pr /var/ossec/queue/syscheck-template /var/ossec/data/queue/syscheck'.
wazuh_1          | Exiting.

Bug description
----------------

After the container try to run the first starting we got an exit 1 because the previous logs.

**Comment by vikman90** [comment]
Hi @jlruizmlg,

I think this error is because Wazuh 3.7 no longer has the directory `queue/syscheck`. Instead, FIM data will be stored in `queue/db`.

Please take a look at branch [3.7.0_6.4.3](https://github.com/wazuh/wazuh-docker/compare/3.7.0_6.4.3), it should fix this issue.

Thank you. Your feedback is very valuable for us.

Cheers!

**Comment by jlruizmlg** [comment]
Works nice, Docker repository updated! thanks.
