### ISSUE TITLE
Release 4.5.1 - Revision 1 - Release Candidate 2 - Footprint Metrics - VULNERABILITY-DETECTOR (2.5d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18513]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #18475                                         |
| **Main footprint metrics issue #** | #18481                                         |
| **Version** | 4.5.1                                      |
| **Release candidate #** | RC2                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.5.1-rc2 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4261/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/monitor-manager-Test_stress_B4261_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/plots/Test_stress_B4261_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4261_manager_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/logs/ossec_Test_stress_B4261_manager_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4261_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/data/monitor-manager-Test_stress_B4261_manager-pre-release.csv)
[Test_stress_B4261_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/data/Test_stress_B4261_manager_analysisd_events.csv)
[Test_stress_B4261_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/data/Test_stress_B4261_manager_analysisd_state.csv)
[Test_stress_B4261_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_manager_centos/data/Test_stress_B4261_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/monitor-agent-Test_stress_B4261_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/Test_stress_B4261_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/Test_stress_B4261_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/Test_stress_B4261_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/plots/Test_stress_B4261_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4261_centos_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/logs/ossec_Test_stress_B4261_centos_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4261_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/data/monitor-agent-Test_stress_B4261_centos-pre-release.csv)
[Test_stress_B4261_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_centos/data/Test_stress_B4261_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/monitor-agent-Test_stress_B4261_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/Test_stress_B4261_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/Test_stress_B4261_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/Test_stress_B4261_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/plots/Test_stress_B4261_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4261_ubuntu_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/logs/ossec_Test_stress_B4261_ubuntu_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4261_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/data/monitor-agent-Test_stress_B4261_ubuntu-pre-release.csv)
[Test_stress_B4261_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_ubuntu/data/Test_stress_B4261_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/monitor-winagent-Test_stress_B4261_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/Test_stress_B4261_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/Test_stress_B4261_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/Test_stress_B4261_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/plots/Test_stress_B4261_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4261_windows_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/logs/ossec_Test_stress_B4261_windows_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4261_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/data/monitor-winagent-Test_stress_B4261_windows-pre-release.csv)
[Test_stress_B4261_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4261-3600m/B4261_agent_windows/data/Test_stress_B4261_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### Conclusion :red_circle: 

The following warning seems to be recurrent since 4.5.1:
- https://github.com/wazuh/wazuh/issues/18447

Reported issue was closed due to this was related to network errors to fetch the databases. However, this was not reported in the previous versions. Further research is required.

**Comment by Rebits** [comment]
# Analysis report

## Graphs

### Windows

- No abnormal behavior detected.

### centOS

- PSS: Small increase. Not relevant
- RSS: Small increase. Not relevant
- USS: Small increase. Not relevant
- VMS: Small increase. Not relevant

### Ubuntu

- VMS: Small decrease. Not relevant

### Manager

- No abnormal behavior detected.



## Logs


<details><summary>Windows</summary>

No errors detected.

</details>



<details><summary>Centos</summary>

```json
{
    "ossec-17.log": {
        "ERROR": {
            "wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.": {
                "count": 1
            },
            "wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.0.15]:1514/tcp': 'Connection refused'.": {
                "count": 2
            }
        }
    }
}
```

</details>



<details><summary>Ubuntu</summary>

```json
{
    "ossec-17.log": {
        "ERROR": {
            "wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.": {
                "count": 1
            },
            "wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.0.15]:1514/tcp': 'Connection refused'.": {
                "count": 2
            }
        }
    }
}
```

</details>



<details><summary>Manager</summary>

```json
{
    "ossec.log": {
        "ERROR": {
            "wazuh-modulesd:vulnerability-detector ERROR: (5513): CVE database could not be updated.": {
                "count": 8
            }
        },
        "WARNING": {
            "wazuh-modulesd:vulnerability-detector WARNING: (5500): The 'Debian Buster' database could not be fetched.": {
                "count": 14
            }
        }
    },
    "ossec-19.log": {
        "ERROR": {
            "wazuh-modulesd:vulnerability-detector ERROR: (5513): CVE database could not be updated.": {
                "count": 11
            }
        },
        "WARNING": {
            "wazuh-modulesd:vulnerability-detector WARNING: (5500): The 'Debian Buster' database could not be fetched.": {
                "count": 18
            }
        }
    },
    "ossec-17.log": {
        "WARNING": {
            "wazuh-modulesd WARNING: Debian Wheezy is no longer supported.": {
                "count": 9
            }
        }
    }
}
```

</details>

**Comment by rauldpm** [comment]
## Review notes

### Windows agent

- Disk usage: in RC1 the drop appears at the third stage when the stress scripts are not working, but in RC2, the drop occurs in the middle of the full stress phase

![image](https://github.com/wazuh/wazuh/assets/14913942/4b2772fc-3f40-47a4-8a40-f945f7ea5731)
![image](https://github.com/wazuh/wazuh/assets/14913942/77b28f7a-57ac-432b-8af9-2a1c54a54c5d)

- RSS: RC1 memory usage seems to be more stable than RC2 although the maximum usage is the same

![image](https://github.com/wazuh/wazuh/assets/14913942/395aa26f-8fc0-4b1a-b5c0-4f9591af69df)
![image](https://github.com/wazuh/wazuh/assets/14913942/10fed074-d21b-4076-97ff-c259c4985c5d)

**Comment by fcaffieri** [comment]
LGTM
