### ISSUE TITLE
Release 4.5.1 - Revision 1 - Release Candidate 2 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#18512]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #18475                                         |
| **Main footprint metrics issue #** | #18481                                         |
| **Version** | 4.5.1                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.5.1-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4262/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/monitor-manager-Test_stress_B4262_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/plots/Test_stress_B4262_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4262_manager_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/logs/ossec_Test_stress_B4262_manager_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4262_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/data/monitor-manager-Test_stress_B4262_manager-pre-release.csv)
[Test_stress_B4262_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/data/Test_stress_B4262_manager_analysisd_events.csv)
[Test_stress_B4262_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/data/Test_stress_B4262_manager_analysisd_state.csv)
[Test_stress_B4262_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_manager_centos/data/Test_stress_B4262_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/monitor-agent-Test_stress_B4262_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/Test_stress_B4262_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/Test_stress_B4262_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/Test_stress_B4262_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/plots/Test_stress_B4262_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4262_centos_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/logs/ossec_Test_stress_B4262_centos_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4262_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/data/monitor-agent-Test_stress_B4262_centos-pre-release.csv)
[Test_stress_B4262_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_centos/data/Test_stress_B4262_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/monitor-agent-Test_stress_B4262_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/Test_stress_B4262_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/Test_stress_B4262_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/Test_stress_B4262_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/plots/Test_stress_B4262_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4262_ubuntu_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/logs/ossec_Test_stress_B4262_ubuntu_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4262_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/data/monitor-agent-Test_stress_B4262_ubuntu-pre-release.csv)
[Test_stress_B4262_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_ubuntu/data/Test_stress_B4262_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/monitor-winagent-Test_stress_B4262_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/Test_stress_B4262_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/Test_stress_B4262_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/Test_stress_B4262_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/plots/Test_stress_B4262_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4262_windows_2023-08-20.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/logs/ossec_Test_stress_B4262_windows_2023-08-20.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4262_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/data/monitor-winagent-Test_stress_B4262_windows-pre-release.csv)
[Test_stress_B4262_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4262-3600m/B4262_agent_windows/data/Test_stress_B4262_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :green_circle: 

No abnormal behavior detected. The disconnections are related to the stress test itself

**Comment by Rebits** [comment]
Agent Status Drops are expected for the Vulnerability Detector Register Test. This specific test aims to assess full scans performed by new agents. Consequently, a stress script will be employed to remove and subsequently register the existing agent, inducing the agent's disconnection status.

In light of the details above, kindly revise the concluding remarks.

**Comment by Rebits** [comment]
LGTM

**Comment by fcaffieri** [comment]
## Analysis report: Logs errors

<details><summary>Wazuh manager</summary>

Reported in: url


```
wazuh-logcollector: WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
wazuh-modulesd: WARNING: The 'hotfixes' option is only available on Windows systems. Ignoring it.
wazuh-remoted: WARNING: (1408): Invalid ID 004 for the source ip: '172.31.15.178' (name 'unknown').
```

</details>

<details><summary>Wazuh agent - CentOS</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.1.17]:1514/tcp': 'Connection refused'.
```

</details>

<details><summary>Wazuh agent - Ubuntu</summary>

Reported in: url

```

wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.1.17]:1514/tcp': 'Connection refused'.
```

</details>

<details><summary>Wazuh agent - Windows</summary>

Reported in: url


```

```

</details>

**Comment by fcaffieri** [comment]
LGTM
