### ISSUE TITLE
Improve FIM alerts description 

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1852]
## Bug report

**Log sample**

```
rule.description: Integrity checksum changed.
full_log: File 'my_file_path' was added.

OR 

rule.description: Integrity checksum changed.
full_log: File 'my_file_path' was deleted.
```

Bug description
----------------

If you create or delete a file the **rule.description** for the alert is "Integrity checksum changed.".

We should create more specific rules every FIM alert type.

**Comment by juergenc** [comment]
Hello @havidarou,

double check this with:
```XML
<syscheck>
   <alert_new_files>yes|no</alert_new_files>
...
```
in agent's conf.
See also #1338, implemented in release _3.7.0_
