### ISSUE TITLE
MinIO Vulnerabilities are not detected

### ISSUE THREAD

**Issue by VicSilva13** [wazuh/wazuh#18536]
[{"WAZUH_VERSION":"v4.4.1"},{"WAZUH_REVISION":"40406"},{"WAZUH_TYPE":"server"}]

I have a Wazuh Server running with the above-mentioned version, which I deployed using the OVA provided here: https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html

I have a VM running SLES 15 SP2, that has the Wazuh agent installed. On that system I also installed an RPM for MinIO version  0:20221212192727.0.0-1.
Wazuh is able to pick up the MinIO installation. I can see this in the "Packages" section of the "Inventory Data" of my agent.
However, there are no vulnerabilities reported related to this MinIO installation. Given that there are more than one vulnerability in MinIO that came after the version I installed, I assumed that Wazuh would check the installed MinIO version and alert me to the fact, that it is a vulnerable version... but it does not do so.
I have done an SQL lookup on NVD_CVE on my Wazuh-Server's console and I can indeed see MinIO vulnerabilities there, so it is not a problem of Wazuh being unaware of this vulnerabilities.
Is this a bug or am I missing something?

<img width="1235" alt="image" src="https://github.com/wazuh/wazuh/assets/90424914/99d9a621-21fc-4cae-8348-d5a16aac188f">

<img width="1245" alt="image" src="https://github.com/wazuh/wazuh/assets/90424914/3a2a08bf-8076-4b72-bb7c-9a1530b0daa4">

**Comment by MiguelazoDS** [comment]
Let me discuss this with the team and I'll back with the feedback, thank you for the report!

**Comment by VicSilva13** [comment]
Hi @MiguelazoDS, any update on this as of yet?

**Comment by MiguelazoDS** [comment]
Hi, 

I checked that the version is reported differently for different operating systems. The package using Arch Linux seems to be compliant with the format NVD uses. We will address this issue according to our roadmap priorities, but this is not high at the moment. 

Regards!

**Comment by VicSilva13** [comment]
Thank you for the quick feedback! :)

**Comment by Dwordcito** [comment]
This will be part of the vulnerability detector refactor in #14153
