### ISSUE TITLE
I have many successful agents connected but one that keeps getting stuck - Connection refused by manager. Maybe the port specified is incorrect

### ISSUE THREAD

**Issue by Lats7** [wazuh/wazuh#18546]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.0| Wazuh component | Manager/Agent | Packages/Sources | Windows 11 Home |

Error in the Agent ossec logs 

"SSL Error (5) Connection refused by manager. Maybe the port specified is incorrect" This directly follows about 30 seconds of successfully logging messages such as "ignore registry entry HKEYXYZxcxxx" "Monitoring"
  

Wazuh Manager logs 
root@wazuh:/var/ossec/bin# tail -f /var/ossec/logs/ossec.log
2023/08/23 04:56:11 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:56:12 wazuh-authd: INFO: Client timeout from 192.168.2.150
2023/08/23 04:56:30 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:56:31 wazuh-authd: INFO: Client timeout from 192.168.2.150
2023/08/23 04:57:49 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:57:50 wazuh-authd: INFO: Client timeout from 192.168.2.150
2023/08/23 04:58:08 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:58:09 wazuh-authd: INFO: Client timeout from 192.168.2.150
2023/08/23 04:59:27 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:59:29 wazuh-authd: INFO: Client timeout from 192.168.2.150
2023/08/23 04:59:47 wazuh-authd: INFO: New connection from 192.168.2.150
2023/08/23 04:59:48 wazuh-authd: INFO: Client timeout from 192.168.2.150

**Comment by nmkoremblum** [comment]
Hi @Lats7.

Could you please share with us your manager and agent's `ossec.conf` files? Be careful not to share sensitive information
