### ISSUE TITLE
GCP integration tests

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#18551]
|Objective | Development branch | 
|--------------|-----------------------------|
|https://github.com/wazuh/wazuh/issues/22732| TBC |

As explained in https://github.com/wazuh/wazuh/issues/22732, we need to create new integration tests for the GCP module while meeting the listed requirements.

1. Preliminary Analysis
   1. https://github.com/wazuh/wazuh/issues/18555
   2. https://github.com/wazuh/wazuh/issues/23669
2. Develop GCP IT
   1. https://github.com/wazuh/wazuh/issues/23670
   2. https://github.com/wazuh/wazuh/issues/18552
      1. https://github.com/wazuh/wazuh/issues/23671
      2. https://github.com/wazuh/wazuh/issues/23676
      3. https://github.com/wazuh/wazuh/issues/23674 
   3. GCP Storage Buckets integration tests
      1. Review resources and permissions required for GCP Storage Buckets integration tests
      2. Develop GCP Storage Buckets integration tests
      3. Resources setup and teardown for GCP Storage Buckets integration tests
   4. https://github.com/wazuh/wazuh/issues/18554

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
