### ISSUE TITLE
wazuh-agent 3.7.0 Ubuntu post installation script not working

### ISSUE THREAD

**Issue by fgrosse19** [wazuh/wazuh#1855]
## Bug report

**OS**
Ubuntu 14.04, 16.04 and 18.04

**Wazuh version**
3.7.0

**Wazuh API version**
3.7.0

**Install type**
Agent (wazuh-agent (3.7.0-1))

**Install method**
wazuh repository

**Log sample**

apt install wazuh-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/9632 kB of archives.
After this operation, 108 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package wazuh-agent.
(Reading database ... 127151 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_3.7.0-1_amd64.deb ...
Unpacking wazuh-agent (3.7.0-1) ...
Processing triggers for systemd (229-4ubuntu21.6) ...
Processing triggers for ureadahead (0.100.0-19) ...
Setting up wazuh-agent (3.7.0-1) ...
mv: cannot stat '/var/ossec/packages_files/agent_config_files/group/agent.conf': No such file or directory
mv: cannot stat '.save': No such file or directory
dpkg: error processing package wazuh-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)

--------
ls /var/ossec/packages_files/agent_config_files/group/
agent.conf .save
cis_debian_linux_rcl.txt.save
cis_rhel6_linux_rcl.txt.save
cis_sles12_linux_rcl.txt.save
cis_win2012r2_memberL2_rcl.txt.save
system_audit_rcl.txt.save
win_malware_rcl.txt.save
agent.conf.save
cis_mysql5-6_community_rcl.txt.save
cis_rhel7_linux_rcl.txt.save
cis_win2012r2_domainL1_rcl.txt.save
merged.mg.save
system_audit_ssh.txt.save
ar.conf.save
cis_mysql5-6_enterprise_rcl.txt.save
cis_rhel_linux_rcl.txt.save
cis_win2012r2_domainL2_rcl.txt.save
rootkit_files.txt.save
win_applications_rcl.txt.save
cis_apache2224_rcl.txt.save
cis_rhel5_linux_rcl.txt.save
cis_sles11_linux_rcl.txt.save
cis_win2012r2_memberL1_rcl.txt.save
rootkit_trojans.txt.save
win_audit_rcl.txt.save

Bug description
----------------
An Update of wazuh-agent to the new Version 3.7.0 fails on Ubuntu within the post-installation script.
The Agent is installed and works if the configuration is correct but because of the error our puppet is struggeling. It tries to install the agent on every run because it never finishes correctly.

The error only appears on Ubuntu, on CentOS the update works fine.

**Comment by juan70** [comment]
Hello, @fgrosse19,

This issue should be fixed now with PR https://github.com/wazuh/wazuh-packages/pull/96.

Thank you for your bug report.

Kind regards.

**Comment by fgrosse19** [comment]
Hi @juan70 ,
thanks for the fix. Now the installation works.
