### ISSUE TITLE
Investigate existing GCP ITs to evaluate refactor or do over of tests

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18566]
| Affected integration |
|---|
| GCloud|

## Description

As part of #18551 and #17442, current GCP ITs are in need of a refactor and/or update as well as a migration to wazuh core repository.

This issue tends to investigate the current state of GCP ITs and conclude whether is a good idea or not to refactor current tests or if it's simpler to do the integration tests from the beginning.

To achieve this task and come up with a conclusion the following analysis needs to be made:

- [x] Analyze the stability of the tests and coupling to the current qa framework.
- [x] Analyze migration workload.

**Comment by EduLeon12** [comment]
## Issue Update

After a discussion with the team and analyzing the proposed design cases it was found that the same issue had already been discussed and concluded that since the current state of the GCP ITs is not optimal and the tests currently found in wazuh-qa don't cover enough uses cases a refactor would only create a bigger workload the best solution is to re-do the GCloud integration tests utilizing the designed test cases.

However, the proposed cases need to be reviewed just to confirm that there is no update/upgrade or change in the service to be tested since the design was made almost a year ago.

Finally, the design of the framework (qa-integration-framework) needs to be designed and implemented along with the test cases to create a solid structure for future updates.

**Comment by GGP1** [comment]
## Review

I believe the GCP integration tests are really unstable and need to be built from scratch to improve their reliability and stability. I agree with the statements made in the issue update about the steps to follow for this and I approve the investigation.
