### ISSUE TITLE
Realtime and whodata don't work until the first period if scan_on_start=no

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#1857]
## Bug report

**OS**
_CentOS 6_

**Wazuh version**
_3.7.1-3720_

Bug description
----------------
Both modes depend on the first scan to start themselves. This should not be the case since the **scan_on_start** option does not refer to whodata or realtime.

**Comment by vikman90** [comment]
Hi @crolopez.

We have designed the whodata engine to work this way, in this version. Let me close this issue so far.
