### ISSUE TITLE
Customizing windows event log

### ISSUE THREAD

**Issue by piyush1337** [wazuh/wazuh#1858]
Please help me in minimising the windows event logs. I know that wazuh is fetching more details than any other tool but i just want an event message of 4 words or say event name only ..the same way we get in Arcsight like for example :- 

"An account was successfully logged on." and other fields of telling more data.

But in wazuh i get it event in "full_log" field which is just too much for normal user..

2018 Nov 12 18:06:12 WinEvtLog: Security: AUDIT_SUCCESS(4624): Microsoft-Windows-Security-Auditing: NAME$: NOIDA: user.domain.com: An account was successfully logged on. Subject:  Security ID:  S-1-0-0  Account Name:  -  Account Domain:  -  Logon ID:  0x0  Logon Type:   3  New Logon:  Security ID:  S-1-5-21-2728577665-982335224-2456254214-6667  Account Name: name  Account Domain:  Place  Logon ID:  0x42ba0a0d  Logon GUID:  {18CAB35D-7D2E-C9CC-2848-03F9FB3596F2}  Process Information:  Process ID:  0x0  Process Name:  -  Network Information:  Workstation Name:   Source Network Address: 192.168.1.2  Source Port:  55006  Detailed Authentication Information:  Logon Process:  Kerberos  Authentication Package: Kerberos  Transited Services: -  Package Name (NTLM only): -  Key Length:  0  This event is generated when a logon session is created. It is generated on the computer that was accessed.

^^ see when i export it to excel its just too much i want just "An account was sucessfully logged on" like in arcsight and talking about other data account name and all i can get it from different fields but this full_log field has the log but its not good for monitoring. So, Please just help me to minimise it to only event name "An account was successfully logged on." <-- only this. 

Thanks

**Comment by juergenc** [comment]
Hello @piyush1337,

you can do this on your own if you customise your own `decoder` for the Windows EventLog. Consult the chapter _Decoder/Rules_ in the documentation. Contemplate the delivered Windows `decoder` for digging in to this topic and make the beginning easier. It's not that complicated and it's worth it cause soner or later you may probably feel the need to customise also other events/alerts.

**Comment by piyush1337** [comment]
> Hello @piyush1337,
> 
> you can do this on your own if you customise your own `decoder` for the Windows EventLog. Consult the chapter _Decoder/Rules_ in the documentation. Contemplate the delivered Windows `decoder` for digging in to this topic and makes the get-into-it easier. It's not that complicated and it's worth it cause sooner or later you may probably feel the need to customise also other events/alerts.

thanks, I was also thinking the same i check it

**Comment by piyush1337** [comment]
> Hello @piyush1337,
> 
> you can do this on your own if you customise your own `decoder` for the Windows EventLog. Consult the chapter _Decoder/Rules_ in the documentation. Contemplate the delivered Windows `decoder` for digging in to this topic and makes the get-into-it easier. It's not that complicated and it's worth it cause sooner or later you may probably feel the need to customise also other events/alerts.

hey i searched more so what exactly i want is that the log which i wrote above was "full_log" field so is there any way to just customize it to the log i want like reducing its length or selecting the text i want. I can see the "full_log" field in index pattern of template and looking if something can be done there rather customizing the whole decoder.

**Comment by juergenc** [comment]
No, there isn't as far as I know. I don't know what you mean with _"customising the whole decoder"_. For the login and logoff Eventlog lines you have a separate `decoder`, so contemplating these `decoder` definitions and the consultation of the documentation will help here. Use the `ossec-logtest` tool for the customisation of your `decoder`, it is of big help.

**Comment by piyush1337** [comment]
> No, there isn't as far as I know. I don't know what you mean with _"customising the whole decoder"_. For the login and logoff Eventlog lines you have a separate `decoder`, so contemplating these `decoder` definitions and the consultation of the documentation will help here. Use the `ossec-logtest` tool for the customisation of your `decoder`, it is of big help.

yeah i know that and by "customising the whole decoder" i meant why to edit a decoder file of windows if there is way to edit the "full_log" field to display because at the end i want the output to excel sheet to be exact log not full log. 

yeah i used ossec-logtest tool but that is good for rule/decoder testing for the alert because i don't get that exact whole log in tool which comes in wazuh template(GUI). So its of not much use for me here but yeah if i edit decoders then its ok.

**Comment by piyush1337** [comment]
> No, there isn't as far as I know. I don't know what you mean with _"customising the whole decoder"_. For the login and logoff Eventlog lines you have a separate `decoder`, so contemplating these `decoder` definitions and the consultation of the documentation will help here. Use the `ossec-logtest` tool for the customisation of your `decoder`, it is of big help.

So when it came to decoder then there is 0380-windows-decoder.xml file in /var/ossec/ruleset/decoders location. In this file there is decoder named windows like :- 
<decoder name="windows">
  <type>windows</type>
  <program_name>^WinEvtLog</program_name>
</decoder>

you can see the program name where it specifies the starting of the string from windows event log to the end. Can you help me in regex to end to just logged on/off.

**Comment by Zenidd** [comment]
Hello @piyush1337,

first of all, sorry for the late reply.

Did you manage to reduce the size of the logs to the message you wanted? If not, please let us know and we'll work on it until we get the output you want. 


<br></br>
Kind regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi again @piyush1337,

I'm closing this ticket due to inactivity. Please reopen this thread or create a new one in case you need it.

Regards,

Juan Pablo Sáez
