### ISSUE TITLE
"Invalid 'wazuh-app-version' header" error message in Wazuh 2.1.0 OVA

### ISSUE THREAD

**Issue by raqocy** [wazuh/wazuh#186]
Downloaded https://packages.wazuh.com/vm/wazuh2.1.0_5.5.1.ova and imported it into VMware Fusion on Mac, no problems so far.

But after going to http://<IP-ADDRESS>:5601/ and clicking Wazuh on the menu, the following error messages are shown (see the attached screenshot):

```
Manager - Status: Wazuh API returned an error message. Error: Invalid 'wazuh-app-version' header. Expected version '2.1.x', and found '2.0.x'.
Agents - Preview: Wazuh API returned an error message. Error: Invalid 'wazuh-app-version' header. Expected version '2.1.x', and found '2.0.x'.
```
![wazuh_errors](https://user-images.githubusercontent.com/31692526/30108042-63baff66-9309-11e7-90ab-5528b83fc8e4.png)

Also, https://documentation.wazuh.com/current/installation-guide/virtual-machine.html contains link to previous OVA image (https://packages.wazuh.com/vm/wazuh2.0.1_5.5.0.ova), not the current one.

**Comment by malbarral** [comment]
Hello @raqocy,

This OVA does not have the latest version of Wazuh Kibana App. We have to update it before publish it.

You can update the Wazuh Kibana App with the following commands:
```
systemctl stop kibana
/usr/share/kibana/bin/kibana-plugin remove wazuh
rm -rf /usr/share/kibana/optimize/bundles
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.5.1.zip
systemctl start kibana
```
Best regards,
Manuel

**Comment by raqocy** [comment]
Hi @malbarral, that did the trick. Muchas gracias!
