### ISSUE TITLE
Release 4.5.2 - RC 1 - Packages tests

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#18620]
# Packages tests information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/18618                     |
| **Version**                      | 4.5.2                                                   |
| **Release candidate**            | RC 1                                                      |
| **Tag**                          | [v4.5.2-rc1](https://github.com/wazuh/wazuh/tree/v4.5.2-rc1)          |
| **Previous packages metrics**    | https://github.com/wazuh/wazuh/issues/18482  |

---
# Tasks

| Status | Test              | Issue              |
| :--:   | :--               | :--:               | 
| :purple_circle: | Installation | https://github.com/wazuh/wazuh/issues/18623 |
| :purple_circle:  | Upgrade | https://github.com/wazuh/wazuh/issues/18625 |
| :purple_circle: | SELinux | https://github.com/wazuh/wazuh/issues/18624  |
| :purple_circle: | Register | https://github.com/wazuh/wazuh/issues/18626  |
| :purple_circle:  | Service  |https://github.com/wazuh/wazuh/issues/18627 |
| :purple_circle:| Specific systems |  https://github.com/wazuh/wazuh/issues/18628 |
|:purple_circle:  | Indexer/Dashboard | https://github.com/wazuh/wazuh/issues/18621 |

> :black_circle: Not Started: The tasks didn't start yet.
> :yellow_circle: In progress: The team is already working on it.
> :green_circle: Ready to review: The auditors must validate the results.
> :white_circle: Skipped: The task has been deemed not necessary for this stage.
> :brown_circle:  Partially skipped:  Some parts of the task are skipped._
> :purple_circle: Completed: Task finished. Nothing to do here.
> :red_circle: Completed with failures: Some issues were raised here.

---

# Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @mauromalara / @davidjiglesias

**Comment by verdx** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
