### ISSUE TITLE
Release 4.5.2 - RC 1 - Installation metrics 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#18623]
# Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/18618 |
| **Main packages metrics issue**  | https://github.com/wazuh/wazuh/issues/18620 |
| **Version**                      | 4.5.2                                                   |
| **Release candidate**            | RC1                                                      |
| **Tag**                          | [v4.5.2-rc1](https://github.com/wazuh/wazuh/tree/v4.5.2-rc1)  |

---

# Packages information
|||
| :--                              | :--                                                             |
| Repository | `packages-dev.wazuh.com`
| Package path | `pre-release`
| Package revision | `1`

---
# Tasks 

- [x] Launch [Test_install_tier](https://ci.wazuh.info/view/Tests/job/Test_install_tier) for each architecture
- [x] Check the test results of each build.

# Checks 

  | Arquitecture | Build |
  | :--         | :--   |
  | AMD64        | [682 ](https://ci.wazuh.info/job/Test_install_tier/682/)|
  | ARM64        |  [683](https://ci.wazuh.info/job/Test_install_tier/683/)|
  | I386         | [684](https://ci.wazuh.info/job/Test_install_tier/684/)|
  | ARM32        | [685](https://ci.wazuh.info/job/Test_install_tier/685/)|
  | ARM64 (macOS 13) | [138974](https://ci.wazuh.info/view/Tests/job/Test_install/138974/)
  | ARM64 (macOS 12) |[139006](https://ci.wazuh.info/view/Tests/job/Test_install/139006/)
  | Solaris | [687](https://ci.wazuh.info/view/Tests/job/Test_install_tier/687)
---

  | System              | AMD64 | ARM64 | I386 | ARM32 |
  | :--                 | :--:  | :--:  | :--: | :--:  |
  | Amazon Linux 1      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Amazon Linux 2      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | CentOS 5            | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | CentOS 6            | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | CentOS 7            | :green_circle:    | :green_circle:    | :green_circle:   | :white_circle:    |
  | CentOS 8            | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Debian 7            | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | Debian 8            | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | Debian 9            | :green_circle:    | :green_circle:    | :green_circle:   | :green_circle:    |
  | Debian 10           | :green_circle:    | :white_circle:    | :red_circle:  | :white_circle:    |
  | Debian 11           | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | Fedora 29           | :green_circle:    | :green_circle:    | :white_circle:   | :green_circle:    |
  | Fedora 31           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Fedora 32           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Fedora 34           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Fedora 35           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Fedora 36           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | openSUSE Tumbleweed | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Oracle Linux 6      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Oracle Linux 7      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Oracle Linux 8      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Red Hat 6           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Red Hat 7           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Red Hat 8           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Red Hat 9           | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Solaris 11          | :green_circle:      | :white_circle:    | :white_circle:   | :white_circle:    |
  | Solaris 10          | :green_circle:      | :white_circle:    | :white_circle:   | :white_circle:    |
  | Ubuntu Jammy | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Ubuntu Bionic       | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Ubuntu Focal        | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Ubuntu Precise      | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | Ubuntu Trusty       | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | Ubuntu Xenial       | :green_circle:    | :white_circle:    | :green_circle:   | :white_circle:    |
  | Windows 2016        | :green_circle:    | :white_circle:    | :white_circle:   | :white_circle:    |
  | macOS 10.15         | :green_circle:      | :white_circle:    | :white_circle:   | :white_circle:    |
  | macOS 12.01       | :white_circle:  | :green_circle:  | :white_circle:  | :white_circle: 
  | macOS 13.4        | :white_circle: | :green_circle:  | :white_circle:  | :white_circle: 

---

## macOS specific test
  
  | System      | Architecture            | Install* | Install** | TCP | UDP | Alerts | Logs | User | Group | Remove |
  | :--:|:--:| :--:| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |
  | macOS 10.15 Catalina | Intel64    | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
  | macOS 12.01 Monterey | ARM    |:white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
  | macOS 13.4  Ventura | ARM     |:white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
  | macOS 12.01 Monterey | intel64   | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
  | macOS 13.4  Ventura | intel64 | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: | :white_circle: |
  
  - \* Without environment variables
  - \*\* With environment variables

> :black_circle: Not Started: The tasks didn't start yet.
> :yellow_circle: In progress: The team is already working on it.
> :green_circle: Completed: Task finished. Nothing to do here.
> :white_circle: Skipped: The task has been deemed not necessary for this stage.
> :brown_circle:  Partially skipped:  Some parts of the task are skipped._
> :red_circle: Completed with failures: Some issues were raised here.

---
## Conclusion

The results were successful, except for a bug obtained in Debian 10. A new bug "[Debian Buster repos update fails due to migration to oldoldstable](https://github.com/wazuh/wazuh-jenkins/issues/5581)" was created to work on it.  
 
To verify that we don't have a problem installing Wazuh on Debian 10, we tested it manually. It works successful. [details](https://github.com/wazuh/wazuh/issues/18623#issuecomment-1697505348)

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias / @mauromalara 

---

**Comment by davidjiglesias** [comment]
We should test Debian 10 installation manually since it failed in https://github.com/wazuh/wazuh-jenkins/issues/5581.

**Comment by BelenValdivia** [comment]
### Install Debian 10 -- WIP

- Check status after installation: `systemctl status wazuh-agent`

```
root@debian-10:/home/vagrant# systemctl status  wazuh-agent
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2023-08-29 13:31:59 UTC; 25min ago
  Process: 10639 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
    Tasks: 31 (limit: 4915)
   Memory: 202.9M
   CGroup: /system.slice/wazuh-agent.service
           ├─11239 /var/ossec/bin/wazuh-execd
           ├─11251 /var/ossec/bin/wazuh-agentd
           ├─11264 /var/ossec/bin/wazuh-syscheckd
           ├─11277 /var/ossec/bin/wazuh-logcollector
           └─11320 /var/ossec/bin/wazuh-modulesd

Aug 29 13:31:52 debian-10 systemd[1]: Starting Wazuh agent...
Aug 29 13:31:52 debian-10 env[10639]: Starting Wazuh v4.5.2...
Aug 29 13:31:53 debian-10 env[10639]: Started wazuh-execd...
Aug 29 13:31:54 debian-10 env[10639]: Started wazuh-agentd...
Aug 29 13:31:55 debian-10 env[10639]: Started wazuh-syscheckd...
Aug 29 13:31:56 debian-10 env[10639]: Started wazuh-logcollector...
Aug 29 13:31:57 debian-10 env[10639]: Started wazuh-modulesd...
Aug 29 13:31:59 debian-10 env[10639]: Completed.
Aug 29 13:31:59 debian-10 systemd[1]: Started Wazuh agent.

```

- Check the modules status: `/var/ossec/bin/wazuh-control status`


```
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

**Comment by davidjiglesias** [comment]
LGTM!
