### ISSUE TITLE
Release 4.5.2 - RC 1 - Upgrade metrics 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#18625]
# Packages tests metrics information

|||
| :--                              | :--                                                             |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/18618 |
| **Main packages metrics issue**  | https://github.com/wazuh/wazuh/issues/18620 |
| **Version**                      | 4.5.2                                                   |
| **Release candidate**            | RC1                                                      |
| **Tag**                          | [v4.5.2-rc1](https://github.com/wazuh/wazuh/tree/v4.5.2-rc1)  |

# Packages information
|||
| :--                              | :--                                                             |
| Repository | `packages-dev.wazuh.com`
| Package path | `pre-release`
| Package revision | `1`

--- 
# Tasks 

- [x] Launch `Test_upgrade_tier` for each architecture https://ci.wazuh.info/job/Test_upgrade_tier/2105/
- [x] Check the test results of each build.

# Checks 

| Versions |System|Build|
|:--:|:--:|:--:|
| ALL | ALL| [2105  ](https://ci.wazuh.info/job/Test_upgrade_tier/2105)|
| 4.1.3 | CentOS 7 | [128136](https://ci.wazuh.info/job/Test_upgrade/128136/)
| 3.12.3 | Ubuntu Bionic | [128141](https://ci.wazuh.info/job/Test_upgrade/128141/)
| 3.13.6 | Ubuntu Bionic | [128140](https://ci.wazuh.info/job/Test_upgrade/128140/)
| 3.13.6 | Ubuntu Focal | [128142](https://ci.wazuh.info/job/Test_upgrade/128142/)
|3.12.0 | CentOS 6 | [128138](https://ci.wazuh.info/job/Test_upgrade/128138/)
| 3.12.0 | Ubuntu Bionic | [128137](https://ci.wazuh.info/job/Test_upgrade/128137/)
---

|System|3.12.0|3.12.3|
|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|

|System|3.13.0|3.13.6|
|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|

|System|4.0.0|4.0.4|
|:--|:--|:--|
|CentOS 8| :yellow_circle:  |:yellow_circle:|
|CentOS 7|:yellow_circle:|:yellow_circle:|
|CentOS 6|:yellow_circle:|:yellow_circle:|
|CentOS 5|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:yellow_circle:|:yellow_circle:|
|Debian 10 (buster)|:yellow_circle:|:yellow_circle:|
|Debian 9 (strech)|:yellow_circle:|:yellow_circle:|
|Fedora 36|:yellow_circle:|:yellow_circle:|
|Fedora 35|:yellow_circle:|:yellow_circle:|
|Fedora 34|:yellow_circle:|:yellow_circle:|
|Fedora 32|:yellow_circle:|:yellow_circle:|
|Fedora 31|:yellow_circle:|:yellow_circle:|
|Ubuntu Focal|:yellow_circle:|:yellow_circle:|
|Ubuntu Bionic|:yellow_circle:|:yellow_circle:|
|Ubuntu Xenial|:yellow_circle:|:yellow_circle:|
|Ubuntu Trusty|:yellow_circle:|:yellow_circle:|
|Amazon Linux 2|:yellow_circle:|:yellow_circle:|
|Amazon Linux 1|:yellow_circle:|:yellow_circle:|
|Oracle Linux 8|:yellow_circle:|:yellow_circle:|
|openSUSE Tumbleweed|:yellow_circle:|:yellow_circle:|
|Red Hat 6|:yellow_circle:|:yellow_circle:|
|Red Hat 7|:yellow_circle:|:yellow_circle:|
|Red Hat 8|:yellow_circle:|:yellow_circle:|
|Red Hat 9|:yellow_circle:|:yellow_circle:|

|System|4.1.0|4.1.1|4.1.2|4.1.3|4.1.4|4.1.5|
|:--|:--|:--|:--|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|

|System|4.2.0|4.2.1|4.2.2|4.2.3|4.2.4|4.2.5|4.2.6|4.2.7|
|:--|:--|:--|:--|:--|:--|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|

|System|4.3.0|4.3.1|4.3.2|4.3.3|4.3.4|4.3.5|4.3.6|4.3.7|4.3.8|4.3.9|4.3.10|4.3.11|
|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:yellow_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|

|System|4.4.0|4.4.1|4.4.2|4.4.3|4.4.4|4.4.5|
|:--|:--|:--|:--|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|:green_circle:|

|System|4.5.0|4.5.1|
|:--|:--|:--:|
|CentOS 8|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|
|CentOS 6|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|

---

|System|MSI Upgrade 4.5.1 -> 4.5.2|Logs|Alerts|
|:--|:--:|:--:|:--:|
|Windows Server 16| :white_circle: | :white_circle: | :white_circle: |

---

|System|WPK 4.5.1 -> 4.5.2|WPK Force 4.5.2 -> 4.5.2|
|:--|:--:|:--:|
|Linux|:white_circle:|:white_circle:|
|Windows|:white_circle:|:white_circle:|

---

|System|Architecture|Upgrade*|Upgrade**|TCP|UDP|Alerts|Logs|User|Group|PID changed|Remove|
|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|macOS 1015 Catalina |Intel64|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey|ARM|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura|ARM|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey|intel64|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura|intel64|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
- \* Without environment variables
- \** With environment variables

> :black_circle: Not Started: The tasks didn't start yet.
> :yellow_circle:   Completed with known issues: Task finished.
> :green_circle: Completed: Task finished. Nothing to do here.
> :white_circle: Skipped: The task has been deemed not necessary for this stage.
> :red_circle: Completed with failures: Some issues were raised here.

---

## Conclusion 🟢 

Everything works as expected. The failures are known issues.
Some pipelines were relaunched because we have flaky test. These will be improve in the future.

Known issues:
- https://github.com/wazuh/wazuh/issues/17892
- https://github.com/wazuh/wazuh/issues/17487
- https://github.com/wazuh/wazuh-packages/issues/1933
--- 
In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.
- [x] @davidjiglesias / @mauromalara 

---

**Comment by fcaffieri** [comment]
Added tag qa_known.
LGTM

**Comment by davidjiglesias** [comment]
LGTM
