### ISSUE TITLE
Ignore attribute for rules may silent a granular alert

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1862]
Let's consider a rule that combines `frequency` and `ignore`:

```xml
<rule id="5712" level="10" frequency="8" timeframe="120" ignore="60">
  <if_matched_sid>5710</if_matched_sid>
</rule>
```

The system would produce this alert if rule 5712 matched 8 times in the latest 120 seconds, but this rule would only appear once per minute.

If an input log matches the rule 5710 16 times in the last minute, the system would produce 14 alerts for rule 5710 and one for rule 5710. No alert would come for the last input, due to the `ignore` option.

In this particular case, ignoring a rule should let the "child" rule produce an alert.

Related issue: #1716. Please take a look at it, maybe a patch could fix them together.

**Comment by chemamartinez** [comment]
Hi @vikman90, 

The PR #1874 solves this issue.

I have also studied the issue #1716 to try to face it simultaneously with this issue. However, I consider it a different use case which requires a more complex solution in the rule matching algorithm. Is that why we should discuss it separately.

Regards.
