### ISSUE TITLE
Release 4.5.2 - RC 1- Register

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#18626]
# Packages tests metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/18618 |
| **Main packages metrics issue**  | https://github.com/wazuh/wazuh/issues/18620 |
| **Version**                      | 4.5.2                                                   |
| **Release candidate**            | RC1                                                      |
| **Tag**                          | [v4.5.2-rc1](https://github.com/wazuh/wazuh/tree/v4.5.2-rc1)  |

---

# Packages information
|||
| :--                              | :--                                                             |
| Repository | `packages-dev.wazuh.com`
| Package path | `pre-release`
| Package revision | `1`

---
# Tasks 

- [x] Launch [Test_registration_tier](https://ci.wazuh.info/view/Tests/job/Test_registration_tier) for each architecture
- [x] Check the test results of each build.

# Checks 

| Test | Build |
| :--  | :--   |
| Test_registration_tier  |   [90](https://ci.wazuh.info/view/Tests/job/Test_registration_tier/90/)|
| Debian 11 | [9349](https://ci.wazuh.info/job/Test_registration/9349/)
---

| System               | Status | 
| :--                  | :--:   |
| CentOS 8             | :green_circle:     |
| CentOS 7             | :green_circle:     |
| CentOS 6             | :green_circle:     |
| CentOS 5             | :green_circle:     |
| Debian 11            | :green_circle:     |
| Debian 10            | :green_circle:     |
| Debian 9             | :green_circle:     |
| Debian 8             | :green_circle:     |
| Debian 7             | :green_circle:     |
| Fedora 32            | :green_circle:     |
| Fedora 31            | :green_circle:     |
| Ubuntu Focal         | :green_circle:     |
| Ubuntu Bionic        | :green_circle:     |
| Ubuntu Xenial        | :green_circle:     |
| Ubuntu Precise       | :green_circle:     |
| Ubuntu Trusty        | :green_circle:     |
| Amazon Linux 1       | :green_circle:     |
| Amazon Linux 2       | :green_circle:     |
| Oracle Linux 6       | :green_circle:     |
| Oracle Linux 7       | :green_circle:     |
| Oracle Linux 8       | :green_circle:     |
| openSUSE Tumbleweed  | :green_circle:     |
| Red Hat 6            | :green_circle:     |
| Red Hat 7            | :green_circle:     |
| Red Hat 8            | :green_circle:     |
| Red Hat 9            | :green_circle:     |

---
> :black_circle: Not Started: The tasks didn't start yet.
> :yellow_circle: In progress: The team is already working on it.
> :green_circle: Completed without failures: Task finished. Nothing to do here.
> :white_circle: Skipped: The task has been deemed not necessary for this stage.
> :brown_circle:  Partially skipped:  Some parts of the task are skipped._
> :red_circle: Completed with failures: Some issues were raised here.

---
### Conclusion

It works successfully without errors.

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @mauromalara / @davidjiglesias 
---

**Comment by rauldpm** [comment]
The artifacts (log file) of each system should be shared here, we need to discuss a new approach with the artifacts as they are widely dispersed and not centralized

**Comment by mauromalara** [comment]
LGTM.

> Note: We should create an issue to modify the pipeline so that it collects the necessary results in just a few minutes, instead of manually completing the task within an hour.
