### ISSUE TITLE
Agents Not Showing, Held on Pending Status

### ISSUE THREAD

**Issue by sv3t0sl4v** [wazuh/wazuh#18645]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.1 | All Wazuh components | Manager/Agent | Assistant Install | Ubuntu 20.04 |

Just installed on a laptop and also installed agent on 4 servers to test. Opened all required ports, agents running, manager doe snot show any agents. 

```
#Wazuh
iptables -t filter -A OUTPUT -p tcp --dport 1514 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 1514 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 1514 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 1514 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 1515 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 1515 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 1516 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 1516 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 514 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 514 -j ACCEPT
iptables -t filter -A OUTPUT -p udp --dport 514 -j ACCEPT
iptables -t filter -A INPUT -p udp --dport 514 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 55000 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 55000 -j ACCEPT
iptables -t filter -A OUTPUT -p tcp --dport 9300:9400 -j ACCEPT
iptables -t filter -A INPUT -p tcp --dport 9300:9400 -j ACCEPT
```
The following is shown on all 4 servers, except time active being a bit different.
```
systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/lib/systemd/system/wazuh-agent.service; enabled; vendor p>
     Active: active (running) since Sun 2023-08-27 11:45:17 UTC; 25min ago
    Process: 3938325 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start >
      Tasks: 65 (limit: 38426)
     Memory: 56.2M
     CGroup: /system.slice/wazuh-agent.service
             ├─3938357 /var/ossec/bin/wazuh-execd
             ├─3938368 /var/ossec/bin/wazuh-agentd
             ├─3938388 /var/ossec/bin/wazuh-syscheckd
             ├─3938418 /var/ossec/bin/wazuh-logcollector
             └─3938440 /var/ossec/bin/wazuh-modulesd
```
All 4 servers return status being "penidng". Dashboard on laptop doe snot show any agents. 
```
sudo grep ^status /var/ossec/var/run/wazuh-agentd.state
status='pending'
```
![Screenshot 2023-08-27 at 15-39-08 Wazuh - Wazuh](https://github.com/wazuh/wazuh/assets/56256300/651b9e8d-b2eb-4773-a3b7-294da6aa869e)

What am I missing here?

**Comment by pereyra-m** [comment]
Hello @sv3t0sl4v !

Could you share the `ossec.log` file from both the agent and the manager?
Any error message related to the connectivity will be reflected there.

Another useful test is to verify if the manager is reachable from the agents with this command

```bash
nc -z -v <MANAGER-IP> 1515 1514
```

Also, please make sure that the agents have a Wazuh version equal to or lower than the manager to ensure compatibility. 

Regards.

**Comment by sv3t0sl4v** [comment]
ERROR: (1208): Unable to connect to enrollment service at '[clientIP]:1515'

**Comment by sv3t0sl4v** [comment]
That is weird, indeed. I checked with `iptables -n -L` and the ports are there and open. Nothing else should make them unreachable.

**Comment by pereyra-m** [comment]
Hi again @sv3t0sl4v !

Please, keep me updated about the ISP answer.
In the meantime, remember that both ports can be changed in the configuration.

**Manager**
Registration
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#port

Connection
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#port

**Agent**

Registration
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment-manager-port

Connection
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#server-port

**Comment by sv3t0sl4v** [comment]
> Please, keep me updated about the ISP answer.

They claim they are not blocking ports. Will try with some custom ports these days when more free time available.

**Comment by Dwordcito** [comment]
Thank you for being part of the community, We closed the issue due to inactivity if you had any questions! please reopen the issue!

**Comment by ljubo9** [comment]
I have the same problem and can't resolve it :

This is from the agent.
ERROR: (1208): Unable to connect to enrollment service at '[clientIP]:1515'

This is from the manager.

nc -zv 10.201.0.20 1514 1515 55000

Connection to 10.201.0.20 1514 port [tcp/*] succeeded!
Connection to 10.201.0.20 1515 port [tcp/*] succeeded!
Connection to 10.201.0.20 55000 port [tcp/*] succeeded!
