### ISSUE TITLE
Let agent group guessing by Remoted be optional

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1864]
Remoted has a group guessing feature, that auto-assigns a group (or multigroup) for an agent if:

- The agent group is undefined (empty).
- The agent was previously registered and has a valid merged.mg file.

In this case, Remoted finds the previous agent's group by matching the MD5 hash of its _merged.mg_ file.

We need to make this feature optional, by adding an internal option.

### `remoted.guess_agent_group`

- Allowed values: `0` (disabled) and `1` (enabled).
- Default value: `0` (disabled).

**Comment by juan70** [comment]
Quick test
--
- Install manager (from sources)
- Install agent (from package)

- Register agent
    ```
    # agent
    sed -i 's/MANAGER_IP/192\.168\.1\.51/' /var/ossec/etc/ossec.conf
    /var/ossec/bin/agent-auth -m 192.168.1.51
    systemctl restart wazuh-agent
    ```
    ```
    # manager
    /var/ossec/bin/agent_groups -l
    /var/ossec/bin/agent_groups -s -i 001
    ```
    **=> OK.** Agent in no group (not even `default`)

- Add option with value `1`, restart manager
    ```
    sed -i '$aremoted.guess_agent_group=1' /var/ossec/etc/local_internal_options.conf
    systemctl restart wazuh-manager
    /var/ossec/bin/agent_groups -l
    /var/ossec/bin/agent_groups -s -i 001
    ```
    **=> OK.** Agent in group default

- Roll back to default behaviour, by setting option to `0`
    ```
    sed -i 's:\(remoted.guess_agent_group=\)1:\10:' /var/ossec/etc/local_internal_options.conf
    systemctl restart wazuh-manager
    ```

- Create new group: `test-group-1`
    ```
    /var/ossec/bin/agent_groups -a -g test-group-1
    ```

- Move agent to group `test-group-1`
    ```
    /var/ossec/bin/agent_groups -a -f -i 001 -g test-group-1
    /var/ossec/bin/agent_groups -l
    /var/ossec/bin/agent_groups -s -i 001
    ```
    **=> OK.** Agent not in `default` anymore, only in `test-group-1`

- Remove agent
    ```
    /var/ossec/bin/manage_agents -r 001
    ```

- Register agent again
    ```
    /var/ossec/bin/agent_groups -l
    /var/ossec/bin/agent_groups -s -i 002
    ```
  **=> OK.** Agent not included in any group

- Remove agent again
    ```
    /var/ossec/bin/manage_agents -r 002
    ```

- Change option to `1`, restart manager
    ```
    sed -i 's:\(remoted.guess_agent_group=\)0:\11:' /var/ossec/etc/local_internal_options.conf
    systemctl restart wazuh-manager
    ```

- Register agent once again
    ```
    /var/ossec/bin/agent_groups -l
    /var/ossec/bin/agent_groups -s -i 003
    ```
  **=> OK.** Agent added automatically to its former group: `test-group-1` and not in `default`
