### ISSUE TITLE
Release 4.5.2 - RC 1 - E2E UX tests - Demo environment

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18674]
The following issue aims to run the specified test for the current release candidate, report the results, and open new issues for any encountered errors.

## Test information
|                         |                                            |
|-------------------------|--------------------------------------------|
| **Test name**           |Demo environment|
| **Category**            |Wazuh App|
| **Deployment option**   |Demo environment|
| **Previous testing issue**  |       None                          |
| **Main release issue**  |  https://github.com/wazuh/wazuh/issues/18617 |
| **Main E2E UX test issue** | https://github.com/wazuh/wazuh/issues/18616|
| **Release candidate #** |                RC 1                          |

## Test description

- [x]  (**T1**): - No errors or warnings found in logs
- [x]  (**T2**): - The daemons are running with the correct user
- [x]  (**T3**): - The status of the Wazuh Indexer clusters is as expected.
- [x]  (**T4**): - No errors in the browser's developer console when browsing the App
- [x]  (**T5**): - Alerts are being generated for each of the modules configured for this purpose
- [x]  (**T6**): - No warning symbols in Discover when expanding a document
- [x]  (**T7**): - Alert generated
- [x] (**T8**): - Search works without specifying a field and using `*`

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed result. |
| :yellow_circle:  | There is at least one expected failure or one warning found or one test skipped and no failures. |

## Conclusions

<table class="default">
  <tr>
    <td>Status</td>
    <td>Test</td>
    <td>Notes</td>
    <td>Issues detected </td>    
  </tr>
  <tr>
    <td>:yellow_circle:</td>
    <td>No errors or warnings found in logs</td>
    <td>Found some known issues in the indexers and on managers.</td>
    <td>Comment about issues found:
       <ol>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh-packages/issues/2139</li>
            <li>KNOWN ISSUE - https://github.com/opensearch-project/security-analytics/pull/203</li>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh-packages/issues/1511</li>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh/issues/18593</li>
  </tr>
  <tr>
    <td>:green_circle:</td>
    <td>The daemons are running with the correct user</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td>:green_circle:</td>
    <td>The status of the Wazuh Indexer clusters is as expected</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td>:red_circle:</td>
    <td>No errors in the browser's developer console when browsing the App </td>
    <td> Found some known Issues and new issue in the console while browsing.</td>
    <td>Comment about issues found:
       <ol>
            <li>NEW ISSUE - https://github.com/wazuh/wazuh-kibana-app/issues/5821</li>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh-kibana-app/issues/5745</li>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh-kibana-app/issues/4092</li>
            <li>KNOWN ISSUE - https://github.com/wazuh/wazuh-kibana-app/issues/4074</li>
       </ol>
    </td>    
  </tr>
    <tr>
    <td>:yellow_circle:</td>
    <td>Alerts are being generated for each of the modules configured for this purpose</td>
    <td>Some modules do not generate alerts, but it is known to happen from previous versions.</td>
    <td>Known Issue found https://github.com/wazuh/wazuh-kibana-app/issues/5749</td>    
  </tr>
    <tr>
    <td>:green_circle:</td>
    <td>No warning symbols in Discover when expanding a document</td>
    <td> </td>
    <td> </td>    
  </tr>
    <tr>
    <td>:green_circle:</td>
    <td>Generate an alert and check it in the web UI</td>
    <td> </td>
    <td> </td>    
  </tr>
  <tr>
    <td>:green_circle:</td>
    <td>Search works without specifying a field and using `*`</td>
    <td></td>
    <td>
       
   </td>       
  </tr>
  
</table>

## Auditors' validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @teddytpc1 
- [ ] @davidjiglesias

**Comment by Deblintrake09** [comment]
Waiting for demo enviroment to be available

**Comment by Deblintrake09** [comment]
## T1 - No errors or warnings found in logs 

### Agents

<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check agent's version
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.5.2"
WAZUH_REVISION="40504"
WAZUH_TYPE="agent"
```

2. Check the general status: `systemctl status wazuh-agent -l` 🟢 
```
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since vie 2023-08-25 20:30:53 UTC; 2 days ago
  Process: 10498 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 10794 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-agent.service
           ├─12161 /var/ossec/bin/wazuh-execd
           ├─12173 /var/ossec/bin/wazuh-agentd
           ├─12188 /var/ossec/bin/wazuh-syscheckd
           ├─12202 /var/ossec/bin/wazuh-logcollector
           └─12224 /var/ossec/bin/wazuh-modulesd

ago 25 20:30:47 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Starting Wazuh v4.5.2...
ago 25 20:30:47 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-execd...
ago 25 20:30:48 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-agentd...
ago 25 20:30:49 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-syscheckd...
ago 25 20:30:50 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-logcollector...
ago 25 20:30:51 ip-10-0-1-32.us-west-1.compute.internal crontab[10982]: (root) LIST (root)
ago 25 20:30:51 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-modulesd...
ago 25 20:30:53 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Completed.
ago 25 20:30:53 ip-10-0-1-32.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
ago 25 20:31:00 ip-10-0-1-32.us-west-1.compute.internal crontab[11361]: (root) LIST (root)
```


    
3. Check the modules status: `/var/ossec/bin/wazuh-control status` 🟢 

```
root@xxxx# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```


4. Check the service status: `journalctl -xe -u wazuh-agent.service`  🟢 
    
```
ago 25 20:30:47 ip-10-0-1-32.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
-- Subject: Unit wazuh-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has begun starting up.
ago 25 20:30:47 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Starting Wazuh v4.5.2...
ago 25 20:30:47 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-execd...
ago 25 20:30:48 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-agentd...
ago 25 20:30:49 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-syscheckd...
ago 25 20:30:50 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-logcollector...
ago 25 20:30:51 ip-10-0-1-32.us-west-1.compute.internal crontab[10982]: (root) LIST (root)
ago 25 20:30:51 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Started wazuh-modulesd...
ago 25 20:30:53 ip-10-0-1-32.us-west-1.compute.internal env[10794]: Completed.
ago 25 20:30:53 ip-10-0-1-32.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
-- Subject: Unit wazuh-agent.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has finished starting up.
-- 
-- The start-up result is done.
ago 25 20:31:00 ip-10-0-1-32.us-west-1.compute.internal crontab[11361]: (root) LIST (root)



```


5. Check for errors in logs: `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`  🟢

    ```

    ```

  
</details>

**Comment by Deblintrake09** [comment]
## T2 - The daemons are running with the correct user 

### Agents

<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root     12161  0.0  0.3  38356  3352 ?        Sl   ago25   0:05 /var/ossec/bin/wazuh-execd
wazuh    12173  0.0  0.6 264352  6020 ?        Sl   ago25   0:50 /var/ossec/bin/wazuh-agentd
root     12188  0.0  0.8 204440  8708 ?        SNl  ago25   1:02 /var/ossec/bin/wazuh-syscheckd
root     12202  0.0  0.5 480808  5156 ?        Sl   ago25   0:24 /var/ossec/bin/wazuh-logcollector
root     12224  0.0  1.6 742708 16520 ?        Sl   ago25   0:28 /var/ossec/bin/wazuh-modulesd
```
</details>
<details>
<summary>Redhat 9.2  🟢 </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root       59171  0.0  0.1  23992  6092 ?        Sl   Aug25   0:05 /var/ossec/bin/wazuh-execd
wazuh      59183  0.0  0.2 245604  9776 ?        Sl   Aug25   1:13 /var/ossec/bin/wazuh-agentd
root       59198  0.0  0.3 468808 13812 ?        SNl  Aug25   3:01 /var/ossec/bin/wazuh-syscheckd
root       59211  0.0  0.2 466424  8304 ?        Sl   Aug25   0:39 /var/ossec/bin/wazuh-logcollector
root       59231  0.0  1.1 1022172 42308 ?       Sl   Aug25   1:33 /var/ossec/bin/wazuh-modulesd
```
</details>
<details>
<summary>Ubuntu 22.04  🟢 </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root        8745  0.0  0.2  24072  2356 ?        Sl   Aug25   0:10 /var/ossec/bin/wazuh-execd
wazuh       8756  0.0  0.4 245800  4176 ?        Sl   Aug25   0:45 /var/ossec/bin/wazuh-agentd
root        8771  0.0  0.5 189964  4844 ?        SNl  Aug25   1:09 /var/ossec/bin/wazuh-syscheckd
root        8785  0.0  0.2 466528  2828 ?        Sl   Aug25   0:34 /var/ossec/bin/wazuh-logcollector
root        8804  0.0  1.2 728412 12052 ?        Sl   Aug25   0:34 /var/ossec/bin/wazuh-modulesd
```
</details>

<details>
<summary>CentOs 8.4  🟢 </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root        9023  0.0  0.2  43472  1888 ?        Sl   ago25   0:05 /var/ossec/bin/wazuh-execd
wazuh       9035  0.0  0.3 280548  3212 ?        Sl   ago25   0:37 /var/ossec/bin/wazuh-agentd
root        9050  0.0  0.6 220124  5412 ?        SNl  ago25   1:21 /var/ossec/bin/wazuh-syscheckd
root        9064  0.0  0.3 485892  3124 ?        Sl   ago25   0:24 /var/ossec/bin/wazuh-logcollector
root        9083  0.0  2.3 758852 19168 ?        Sl   ago25   0:31 /var/ossec/bin/wazuh-modulesd
```
</details>
<details>
<summary>Debian 11  🟢 </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root        8724  0.0  0.3  24236  3252 ?        Sl   Aug25   0:08 /var/ossec/bin/wazuh-execd
wazuh       8735  0.0  0.7 246120  7764 ?        Sl   Aug25   0:44 /var/ossec/bin/wazuh-agentd
root        8749  0.0  1.0 189908  9968 ?        SNl  Aug25   0:59 /var/ossec/bin/wazuh-syscheckd
root        8765  0.0  0.4 466644  4508 ?        Sl   Aug25   0:33 /var/ossec/bin/wazuh-logcollector
root        8782  0.0  1.6 728552 16500 ?        Sl   Aug25   0:28 /var/ossec/bin/wazuh-modulesd
root       38567  0.1  0.8  14276  8616 ?        Ss   13:53   0:00 sshd: wazuh-user [priv]
```
</details>

<details>
<summary>Windows  🟢 </summary>

1. Check the user: `tasklist /svc | Select-String "wazuh"` 🟢
![imagen](https://github.com/wazuh/wazuh/assets/14501079/3f719e81-af46-41dd-8bce-709d02a7fcdc)

</details>

---

### Managers

<details>
<summary>Master env 1  :green_circle: </summary>

1. Check the user: `ps -aux | grep wazuh`
```
wazuh    21770  0.0  3.0 851092 121196 ?       Sl   ago25   2:17 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    21795  0.0  0.1  39152  4384 ?        Sl   ago25   0:31 /var/ossec/bin/wazuh-integratord
root     21815  0.2  0.1 260368  5588 ?        Sl   ago25  10:16 /var/ossec/bin/wazuh-authd
wazuh    21832  0.1  0.6 850416 25172 ?        Sl   ago25   4:01 /var/ossec/bin/wazuh-db
wazuh    21845  0.0  1.7 332276 69728 ?        S    ago25   0:05 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    21848  0.0  1.8 481928 72932 ?        S    ago25   3:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root     21863  0.0  0.0  39192  3516 ?        Sl   ago25   0:05 /var/ossec/bin/wazuh-execd
wazuh    21878  4.8  3.8 1294604 153876 ?      Sl   ago25 188:40 /var/ossec/bin/wazuh-analysisd
root     21890  0.0  0.2 336064  8580 ?        SNl  ago25   1:14 /var/ossec/bin/wazuh-syscheckd
wazuh    21910  0.4  0.2 925588  9208 ?        Sl   ago25  19:01 /var/ossec/bin/wazuh-remoted
root     21944  0.0  0.1 481588  5224 ?        Sl   ago25   0:24 /var/ossec/bin/wazuh-logcollector
wazuh    21964  0.0  0.1  39224  4768 ?        Sl   ago25   3:09 /var/ossec/bin/wazuh-monitord
root     22015  2.5  0.7 917204 30072 ?        Sl   ago25 100:51 /var/ossec/bin/wazuh-modulesd
wazuh    22150  0.2  1.6 466024 65520 ?        Sl   ago25   8:33 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    22178  0.0  1.3 299804 53672 ?        S    ago25   1:07 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    22179  0.0  1.3 301264 55724 ?        S    ago25   1:07 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
root     31429  0.1  0.2 152672  8868 ?        Ss   13:51   0:00 sshd: wazuh-user [priv]
wazuh-u+ 31437  0.0  0.1 152672  4580 ?        S    13:51   0:00 sshd: wazuh-user@pts/0
wazuh-u+ 31438  0.3  0.1 124896  4088 pts/0    Ss   13:51   0:00 -bash
root     31475  0.0  0.0 119448   992 pts/0    S+   13:51   0:00 grep --color=auto wazuh
```
</details>

<details>
<summary>Worker env 1 :green_circle:  </summary>

1. Check the user: `ps -aux | grep wazuh`

```
wazuh    21373  0.0  2.7 840604 110324 ?       Sl   ago25   1:44 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    21396  0.0  0.1  39148  4040 ?        Sl   ago25   0:31 /var/ossec/bin/wazuh-integratord
root     21418  0.2  0.1 194832  6212 ?        Sl   ago25  10:17 /var/ossec/bin/wazuh-authd
wazuh    21435  0.0  0.5 784880 21620 ?        Sl   ago25   3:22 /var/ossec/bin/wazuh-db
root     21460  0.0  0.0  39188  3552 ?        Sl   ago25   0:05 /var/ossec/bin/wazuh-execd
wazuh    21462  0.0  1.7 332284 68596 ?        S    ago25   0:05 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    21465  0.0  1.8 481844 73012 ?        S    ago25   3:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    21481  4.5  3.4 1294420 136908 ?      Sl   ago25 178:33 /var/ossec/bin/wazuh-analysisd
root     21493  0.0  0.2 336068  8372 ?        SNl  ago25   1:14 /var/ossec/bin/wazuh-syscheckd
wazuh    21514  0.1  0.2 925060  9140 ?        Sl   ago25   7:05 /var/ossec/bin/wazuh-remoted
root     21549  0.0  0.1 481588  5124 ?        Sl   ago25   0:25 /var/ossec/bin/wazuh-logcollector
wazuh    21570  0.0  0.1  39228  4540 ?        Sl   ago25   3:06 /var/ossec/bin/wazuh-monitord
root     21622  2.2  0.8 919764 33496 ?        Sl   ago25  86:06 /var/ossec/bin/wazuh-modulesd
wazuh    21740  0.0  1.4 447992 57720 ?        Sl   ago25   1:21 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    21744  0.0  1.3 299936 53588 ?        S    ago25   0:52 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    21745  0.0  1.3 299800 53560 ?        S    ago25   0:52 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
root     25596  0.1  0.2 152672  8876 ?        Ss   13:50   0:00 sshd: wazuh-user [priv]
wazuh-u+ 25604  0.0  0.1 152672  4496 ?        S    13:50   0:00 sshd: wazuh-user@pts/0
wazuh-u+ 25605  0.2  0.1 124896  4064 pts/0    Ss   13:50   0:00 -bash
root     25642  0.0  0.0 119448   920 pts/0    S+   13:50   0:00 grep --color=auto wazuh
```

</details>

<details>
<summary>Master env 2 :green_circle:  </summary>


1. Check the user: `ps -aux | grep wazuh`
```
root     11828  0.0  0.2 152672  9208 ?        Ss   13:44   0:00 sshd: wazuh-user [priv]
wazuh-u+ 11836  0.0  0.1 152672  4508 ?        S    13:44   0:00 sshd: wazuh-user@pts/0
wazuh-u+ 11837  0.0  0.1 124896  4000 pts/0    Ss   13:44   0:00 -bash
root     11966  0.0  0.0 119448   952 pts/0    S+   13:50   0:00 grep --color=auto wazuh
wazuh    17584  0.0  2.7 760940 108084 ?       Sl   ago25   0:14 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    17616  0.0  0.1  39148  4468 ?        Sl   ago25   0:09 /var/ossec/bin/wazuh-integratord
wazuh    17626  0.0  0.6 850392 26368 ?        Sl   ago25   3:29 /var/ossec/bin/wazuh-db
root     17652  0.0  0.0  39184  3864 ?        Sl   ago25   0:05 /var/ossec/bin/wazuh-execd
wazuh    17667  0.0  2.7 1294360 110672 ?      Sl   ago25   2:09 /var/ossec/bin/wazuh-analysisd
wazuh    17668  0.0  1.6 325348 66380 ?        S    ago25   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
wazuh    17671  0.0  1.7 414468 68916 ?        S    ago25   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root     17685  0.0  0.2 270592  8820 ?        SNl  ago25   1:07 /var/ossec/bin/wazuh-syscheckd
wazuh    17706  0.2  0.2 794072  8272 ?        Sl   ago25   8:36 /var/ossec/bin/wazuh-remoted
root     17738  0.0  0.1 481564  5468 ?        Sl   ago25   0:24 /var/ossec/bin/wazuh-logcollector
wazuh    17759  0.0  0.1  39164  5040 ?        Sl   ago25   0:11 /var/ossec/bin/wazuh-monitord
root     17810  2.6  0.7 865984 29992 ?        Sl   ago25 104:02 /var/ossec/bin/wazuh-modulesd
wazuh    17954  0.1  1.6 608032 63916 ?        Sl   ago25   7:29 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    18131  0.0  1.3 307576 55340 ?        S    ago25   1:44 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
wazuh    18909  0.0  1.3 460180 55568 ?        S    ago25   0:00 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh_clusterd.py
```
</details>

---

### Wazuh Indexer

<details>
<summary>Node 1  :green_circle: </summary>

1. Check the user: `ps -aux | grep wazuh` :green_circle: 

```
```


</details>


<details>
<summary>Node 2  :green_circle: </summary>

1. Check the user: `ps -aux | grep wazuh` :green_circle: 

```

```

</details>

<details>
<summary>Node 3 :green_circle:  </summary>

1. Check the user: `ps -aux | grep wazuh` :green_circle: 

```

```

</details>

---


### Wazuh dashboard

<details>
<summary>wazuh-indexer :green_circle: </summary>

1. Check the user: `ps -aux | grep wazuh`
```

```



</details>


<details>
<summary>wazuh-dashboard :green_circle:  </summary>

1. Check the user: `ps -aux | grep wazuh`
```
```


</details>

**Comment by Deblintrake09** [comment]
## T3 - The status of the Wazuh Indexer clusters is as expected

<details>
<summary>wazuh-indexer :green_circle: </summary>

1. Check nodes: `curl -k -u ADMIN_USER:PASS https://indexer_IP:9200/_cat/nodes?v` 

```
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
X.X.X.X            44          79   0    0.01    0.01     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-3
Y.Y.Y.Y            27          89   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-7
Z.Z.Z.Z            38          84   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-2
T.T.T.T            9          84   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-1
```

</details>

**Comment by Deblintrake09** [comment]
## T4 - No errors in the browser's developer console when browsing the App 

New bug reported:
- https://github.com/wazuh/wazuh-kibana-app/issues/5821

Bugs reported previously: 
- https://github.com/wazuh/wazuh-kibana-app/issues/5745
- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-kibana-app/issues/4074

**Comment by Deblintrake09** [comment]
## T7: Generate an alert and check it in the web UI  🟢 

1. Generate alert
```
ssh invalid-user@centos.wazuh.info
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
Permission denied, please try again.
invalid-user@centos.wazuh.info's password: 
invalid-user@centos.wazuh.info: Permission denied 
```
2. Check if the alerts are in the Dashboard


    ![4-5-2 brute force](https://github.com/wazuh/wazuh/assets/14501079/b16798ad-676a-416f-874f-f8515088adad)
)


<details>
<summary>Alert information</summary>

```
{
  "_index": "wazuh-alerts-4.x-env-1-2023.08.28",
  "_id": "-M6HPYoBtAj9_jtT1uwR",
  "_version": 1,
  "_score": null,
  "_source": {
    "predecoder": {
      "hostname": "ip-x-x-x-x",
      "program_name": "sshd",
      "timestamp": "Aug 28 19:03:42"
    },
    "cluster": {
      "node": "worker_01",
      "name": "wazuh1"
    },
    "agent": {
      "ip": "10.0.1.140",
      "name": "Centos",
      "id": "003"
    },
    "previous_output": "Aug 28 19:03:38 ip-x-x-x-x sshd[22812]: Failed password for invalid user invalid-user from 45.178.1.177 port 31623 ssh2\nAug 28 19:03:33 ip-x-x-x-x sshd[22812]: Failed password for invalid user invalid-user from 45.178.1.177 port 31623 ssh2\nAug 28 19:03:29 ip-x-x-x-x sshd[22812]: Invalid user invalid-user from 45.178.1.177 port 31623\nAug 28 19:03:26 ip-x-x-x-x sshd[22810]: Failed password for invalid user invalid-user from 45.178.1.177 port 31623 ssh2\nAug 28 19:03:21 ip-x-x-x-x sshd[22810]: Failed password for invalid user invalid-user from 45.178.1.177 port 31623 ssh2\nAug 28 19:03:18 ip-x-x-x-x sshd[22810]: Failed none for invalid user invalid-user from 45.178.1.177 port 31623 ssh2\nAug 28 19:03:15 ip-x-x-x-x sshd[22810]: Invalid user invalid-user from 45.178.1.177 port 31623",
    "data": {
      "srcuser": "invalid-user",
      "srcip": "45.178.1.177"
    },
    "manager": {
      "name": "wazuh-manager-worker-0"
    },
    "rule": {
      "mail": false,
      "level": 10,
      "hipaa": [
        "164.312.b"
      ],
      "pci_dss": [
        "11.4",
        "10.2.4",
        "10.2.5"
      ],
      "tsc": [
        "CC6.1",
        "CC6.8",
        "CC7.2",
        "CC7.3"
      ],
      "description": "sshd: brute force trying to get access to the system. Non existent user.",
      "groups": [
        "syslog",
        "sshd",
        "authentication_failures"
      ],
      "nist_800_53": [
        "SI.4",
        "AU.14",
        "AC.7"
      ],
      "frequency": 8,
      "gdpr": [
        "IV_35.7.d",
        "IV_32.2"
      ],
      "firedtimes": 1,
      "mitre": {
        "technique": [
          "Brute Force"
        ],
        "id": [
          "T1110"
        ],
        "tactic": [
          "Credential Access"
        ]
      },
      "id": "5712"
    },
    "decoder": {
      "parent": "sshd",
      "name": "sshd"
    },
    "full_log": "Aug 28 19:03:42 ip-x-x-x-x sshd[22812]: Failed password for invalid user invalid-user from 45.178.1.177 port 31623 ssh2",
    "input": {
      "type": "log"
    },
    "location": "/var/log/secure",
    "id": "1693249423.755468",
    "GeoLocation": {
      "city_name": "San Luis",
      "country_name": "Argentina",
      "region_name": "San Luis",
      "location": {
        "lon": -66.354,
        "lat": -33.299
      }
    },
    "timestamp": "2023-08-28T19:03:43.904+0000"
  },
  "fields": {
    "timestamp": [
      "2023-08-28T19:03:43.904Z"
    ]
  },
  "highlight": {
    "cluster.name": [
      "@opensearch-dashboards-highlighted-field@wazuh1@/opensearch-dashboards-highlighted-field@"
    ],
    "agent.id": [
      "@opensearch-dashboards-highlighted-field@003@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1693249423904
  ]
}
```

</details>

**Comment by Deblintrake09** [comment]
## T8: Search works without specifying a field and using `*`  🟢 

1. `*`
  
   ![1](https://github.com/wazuh/wazuh/assets/14501079/487b8a95-5005-4fb8-8f47-1694dd681cdb)

2. `aw*`


    ![2](https://github.com/wazuh/wazuh/assets/26927338/964eac77-cb0f-4b52-a4ec-afe520eb6d87)



3. `*squer*`

  
    ![3](https://github.com/wazuh/wazuh/assets/14501079/71ab3096-f9c8-4126-a009-7559b9bc216d)


4. `*shd`

   ![4](https://github.com/wazuh/wazuh/assets/14501079/ba5e314b-5d7c-4c4a-ac32-f7bbcc8d7428)

**Comment by davidcr01** [comment]
After analyzing https://github.com/wazuh/wazuh-kibana-app/issues/5821:
- First error: `TypeError: a.default.detectStore(...) is undefined h1-check.js:1:1301`
 This error means that the variable `a.default.detectStore` is undefined. This variable is used to detect the store in the Wazuh application. The most likely reason for this error is that the `a` variable is not defined. This could be because the `a` variable is not declared in the code, or it is defined but has a different value

- Second error: `window.controllers/Controllers está desaprobado. No lo use para detectar el agente de usuario. osd-ui-shared-deps.js:382:921390`
 This error means that the window.controllers/Controllers object is deprecated and should not be used to detect the user agent. The most likely reason for this error is that the code is trying to use an old version of the Wazuh application.

- Third error: `TypeError: location.href.split(...)[1] is undefined core.entry.js:15:547032`
 This error means that the variable `location.href` is undefined. This variable is used to get the current URL of the page. The most likely reason for this error is that the code is trying to access the `location.href` variable before the page has loaded completely.

- Fourth error: `Error: Unauthorized`
 This error means that the user is not authorized to access the requested resource. The most likely reason for this error is that the user does not have the correct permissions to access the resource.

These errors are not related to the Demo environment but to the Wazuh dashboard. 
LGTM.

**Comment by davidjiglesias** [comment]
I do not understand this reference:

![image](https://github.com/wazuh/wazuh/assets/48716145/705e2de5-48fd-41e9-902a-c9dc0d36bd4c)

**Comment by teddytpc1** [comment]
@davidjiglesias to add further information regarding the modules. Not every module is configured and not every module is enabled. So, it's expected to have alerts in some of them.

**Comment by davidjiglesias** [comment]
LGTM!
