### ISSUE TITLE
Error in Footprint test: Ftell function failed due to [(9)-(Bad file descriptor)] 

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18689]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Logcollector | Agent | Packages | Windows |

Jenkins build: https://ci.wazuh.info/job/Test_stress/4281/
Test issue: [Release 4.5.2 - Revision 1 - Release Candidate RC1 - Footprint Metrics - ALL-EXCEPT-SCA (2.5d) ](https://github.com/wazuh/wazuh/issues/18671)

Performing footprint test a new error is present in logs of Windows Agent:
```
ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
ERROR: (1115): Could not read from file 'C:\tmp\logcollector_test\flood-8-11.log' due to [(9)-(Bad file descriptor)].
```

Further research is required

**Comment by JorgeMarinoDev** [comment]
Further research :

```
28156-2023/08/26 13:55:31 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
28157-2023/08/26 13:55:31 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
28158:2023/08/26 13:55:31 wazuh-agent: ERROR: (1115): Could not read from file 'C:\tmp\logcollector_test\flood-8-11.log' due to [(9)-(Bad file descriptor)].
```



**Is the file present and has a valid name?**

Yes. 

```
28128:2023/08/26 13:55:31 wazuh-agent: INFO: (1957): New file that matches the 'C:\tmp\logcollector_test\flood*.log' pattern: 'C:\tmp\logcollector_test\flood-8-11.log'.
```

The file was detected and has a valid name.

**Is the file an edge case of antiflooding system?**

No. It's normal. It belongs to flood-8-* series. Not even the first in the series or the last one. Also between flood-7-* and flood-9-* ranges.

**Was the error displayed after the file was deleted?**

No.

Line 28158  13:55:31 

```
28158:2023/08/26 13:55:31 wazuh-agent: ERROR: (1115): Could not read from file 'C:\tmp\logcollector_test\flood-8-11.log' due to [(9)-(Bad file descriptor)].
```

Line 39075 15:03:38

```
30975:2023/08/26 15:03:38 wazuh-agent: INFO: (1959): File 'C:\tmp\logcollector_test\flood-8-11.log' no longer exists.
```

**Was the error displayed for any other file?**

No. 1 file out of 3800 files.

```
grep -i 'ERROR: ' *.log -n | grep Bad
ossec-26.log:28156:2023/08/26 13:55:31 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
ossec-26.log:28157:2023/08/26 13:55:31 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
ossec-26.log:28158:2023/08/26 13:55:31 wazuh-agent: ERROR: (1115): Could not read from file 'C:\tmp\logcollector_test\flood-8-11.log' due to [(9)-(Bad file descriptor)].
```

```
grep -i 'New file that matches' *.log -n | grep flood | wc -l
3800
```



**logcollector.c**

https://github.com/wazuh/wazuh/blob/7bf32df3a3a11433260feb60c0ce1dd744d3a8ae/src/logcollector/logcollector.c#L2266

Bad file descriptor; for example, I/O on a descriptor that has been closed or reading from a descriptor open only for writing (or vice versa).



Some thoughts:

As far the occurrence ratio is this low (1/3800), this might likely be related to a very particular OS concurrence issue. 

The source code is protected with mutex for internal operations, but relying on OS capabilities to open a file for reading while other process can write to the same file. This only happens in Windows agent.

No logs found related to retrying to open the same file or retries attempts.
