### ISSUE TITLE
Error in Footprint test: Couldn't get the content of the 'Debian Bullseye' feed from 'tmp/vuln-temp' file.

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18690]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Wazuh | Manager | Packages | CentOS |

Jenkins build: https://ci.wazuh.info/job/Test_stress/4281/
Test issue: [Release 4.5.2 - Revision 1 - Release Candidate RC1 - Footprint Metrics - ALL-EXCEPT-SCA (2.5d) ](https://github.com/wazuh/wazuh/issues/18671)

Performing footprint test a new error is present in the logs of CentOS Manager:
```
ERROR: (5523): Couldn't get the content of the 'Debian Bullseye' feed from 'tmp/vuln-temp' file.
```

Further research is required

**Comment by QU3B1M** [comment]
During the metrics analysis of the issue https://github.com/wazuh/wazuh/issues/18654 I found a similar log, it seems to be related.
```log
wazuh-modulesd:vulnerability-detector: ERROR: (5523): Couldn't get the content of the 'Debian Buster' feed from 'tmp/vuln-temp' file.
```

**Comment by cborla** [comment]
Duplicated of https://github.com/wazuh/wazuh/issues/18447
