### ISSUE TITLE
Anomalous behavior of `wazuh-modulesd` in the stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#18693]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.2-rc1| wazuh-modulesd | Manager | packages | CentOS 7 |

- During the review of the issue https://github.com/wazuh/wazuh/issues/18655, an anomalous behavior has been detected in - the use of RSS memory of Wazuh manager, where it is observed that the memory usage of wazuh-modulesd does not match the behavior of previous tests
- An analysis would be necessary to determine if the behavior of wazuh-modulesd is acceptable or not, and what may have caused such use.

![image](https://github.com/wazuh/wazuh/assets/14913942/01c36afb-ed21-40b1-bde5-b6b4ccb044e2)

<details><summary>RSS plots</summary>

![image](https://github.com/wazuh/wazuh/assets/14913942/fff670bd-6319-4294-960e-d802a7ba0bda)
![image](https://github.com/wazuh/wazuh/assets/14913942/04c9d13c-91ca-4cb6-b904-d457a410c374)
![image](https://github.com/wazuh/wazuh/assets/14913942/97112baa-0b71-4171-9a07-d6911509a7db)
![image](https://github.com/wazuh/wazuh/assets/14913942/630a0b9d-1e62-4eec-8cb2-7e3ed027a426)
![image](https://github.com/wazuh/wazuh/assets/14913942/ffd33911-7889-492c-93e8-03fad679a72b)

</details>

**Comment by QU3B1M** [comment]
Just to add some more info about this behavior, on the issue https://github.com/wazuh/wazuh/issues/18668 we can also observe the same increase of usage in two plots: 
 - Manager: `USS plot`![image](https://github.com/wazuh/wazuh/assets/44633633/7d823659-2d40-41b4-ab85-1026d240ec9e)

 - Wazuh agent - Centos: `CPU plot`![image](https://github.com/wazuh/wazuh/assets/44633633/897c6bf8-a520-4905-b57b-75aaa63096fc)

**Comment by verdx** [comment]
In issue https://github.com/wazuh/wazuh/issues/18662, a very important increase in the modulesd disk readings has been seen. 

- Disk_Read: Increase in `wazuh-modulesd` from almost 0 to 1.2*1e6 .
  - Previous graph:
  - ![image](https://github.com/wazuh/wazuh/assets/61122643/20497ad3-908e-4fd1-8fee-0910bf2f1c6e)
  - Current graph: 
  - ![image](https://github.com/wazuh/wazuh/assets/61122643/18c6c85f-0cde-46ae-9a76-067ebe0d204a)

**Comment by LucioDonda** [comment]
As mentioned in the main issue and also in the comments, there's an increment of the memory used by `wazuh-modulesd` process (RSS, USS) after the full load part of the stress test finishes.
* Altough this is an actual increase in memory, in our opinion, is still acceptable. At the end of the test, we can see that the average value of the memory starts decreasing to its normal values.
![263810459-fff670bd-6319-4294-960e-d802a7ba0bda (1)](https://github.com/wazuh/wazuh/assets/95248059/1ab84080-e46d-438f-a951-48c518f4394c)

* While analysisd is at full load, some communication processes are blocked and waiting for it to respond. This can cause an increase in memory taking place after the full load finishes. Examples of this behavior are:
  * `Resending scan results in 5 seconds.`  and `wazuh-syscheckd: WARNING: Real-time inotify kernel queue is full`   messages till Full load ends (27/08 at 22:53).
  * Modulesd **read_ops** still increasing after that moment (and during resource release).  
![readOps](https://github.com/wazuh/wazuh/assets/95248059/2cc15bec-faec-4a0e-9473-7267009edf27)
  * Sca EDPS's is the only one increasing during release.  
![EDPS](https://github.com/wazuh/wazuh/assets/95248059/5ce88bd0-ec30-492c-94d1-4b2ef088675f)
* Comparing this test results with other on the same version ([ALL except `syscheck`](https://github.com/wazuh/wazuh/issues/18660)) we haven't noticed this increase, as a matter of fact in some cases it diminishes compared to the previous versions.
* Besides that, and bearing in mind that the increase is not to worry about, we think that the best approach is analyzing this issue on the next footprint test or directly closing this issue as it doesn't comprise any other wazuh module or functionality.
c.c. @cborla
