### ISSUE TITLE
never see any vulnerabilities and scan record of agent 

### ISSUE THREAD

**Issue by cha01an** [wazuh/wazuh#18703]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.5 | Wazuh Agent| Manager/Agent | Packages|  CentOS Linux 7.9 |

I have deploy wazuh agent through rpm on CentOS Linux 7.9, but I can not see can not see any vulnerabilities and scan record of agent in the dashboard until now more than a week. The time of last scan is show "-" as follow.

![image](https://github.com/wazuh/wazuh/assets/49859825/a380ff11-1f97-4f13-afc2-53af1bd07d5d)

And the configuration file of ossec.conf is as as bellow.

![image](https://github.com/wazuh/wazuh/assets/49859825/ce79732b-a9d0-46c5-8131-77a57a9f4731)

I'd like to know what the problem is.

**Comment by cha01an** [comment]
The document I referenced is [Configuring and running scans](https://documentation.wazuh.com/4.4/user-manual/capabilities/vulnerability-detection/configuring-scans.html).

**Comment by MiguelazoDS** [comment]
Hi @cha01an, 

Let's see if all the requirements needed for the scan are met.

- Check the package inventory is populated. 
Ejecute this query in your manager: `sqlite3 /var/ossec/queue/db/001.db 'select count(*) from sys_programs'`
(Change the agent id for the right one) 
- Check if the CVE database is populated. 
Ejecute this query in your manager `sqlite3 /var/ossec/queue/vulnerabilities/cve.db 'select target,count(*) from vulnerabilities group by target'`
- Is your agent connected to the manager? 
Ejecute this command in your manager: `agent_control -l`

**Comment by cha01an** [comment]
> Hi @cha01an,
> 
> Let's see if all the requirements needed for the scan are met.
> 
> * Check the package inventory is populated.
>   Ejecute this query in your manager: `sqlite3 /var/ossec/queue/db/001.db 'select count(*) from sys_programs'`
>   (Change the agent id for the right one)
> * Check if the CVE database is populated.
>   Ejecute this query in your manager `sqlite3 /var/ossec/queue/vulnerabilities/cve.db 'select target,count(*) from vulnerabilities group by target'`
> * Is your agent connected to the manager?
>   Ejecute this command in your manager: `agent_control -l`

Thank you for your support.
- Check the package inventory is populated.
When I finished execute the query `sqlite3 /var/ossec/queue/db/001.db 'select count(*) from sys_programs'`. It has returned `1101.`
![image](https://github.com/wazuh/wazuh/assets/49859825/93e761d8-d99c-41bf-90a1-b00751f22d0d)
- Check if the CVE database is populated.
I execute the query and it doesn't return anything. And this path has the file `cve.db`.
![image](https://github.com/wazuh/wazuh/assets/49859825/58afe6d0-2015-49a0-804d-ee8b41be2d79)
-  Is your agent connected to the manager?
Yes, the agent is active.
![image](https://github.com/wazuh/wazuh/assets/49859825/f78095ff-5cb0-4bc9-906d-7dcf0e626a45)

**Comment by MiguelazoDS** [comment]
Hi @cha01an, 

The configuration is ok, but for some reason, it is not downloading the feeds (or it is downloading but not inserting in the DB).
Please set `wazuh_modules.debug=2` in your `/var/ossec/etc/internal_options.conf` file and restart your manager. 

Then grep the log file and share the output. 

grep -E "ERR|WARN" /var/ossec/logs/ossec.log

**Comment by cha01an** [comment]
> Hi @cha01an,
> 
> The configuration is ok, but for some reason, it is not downloading the feeds (or it is downloading but not inserting in the DB). Please set `wazuh_modules.debug=2` in your `/var/ossec/etc/internal_options.conf` file and restart your manager.
> 
> Then grep the log file and share the output.
> 
> grep -E "ERR|WARN" /var/ossec/logs/ossec.log

Hi, @MiguelazoDS.

The log is showed as follow. [ossec.log](https://github.com/wazuh/wazuh/files/12494124/ossec.log)

Thanks!

**Comment by MiguelazoDS** [comment]
HI @cha01an, 

Does your manager have internet connection? I see some curl errors. Your manager can not download the feeds, that's why the first warnings, it has nothing in the CVE database. 
You can also use Vulnerability Detector with offline feeds https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html 

Regards!

**Comment by cha01an** [comment]
> HI @cha01an,
> 
> Does your manager have internet connection? I see some curl errors. Your manager can not download the feeds, that's why the first warnings, it has nothing in the CVE database. You can also use Vulnerability Detector with offline feeds https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html
> 
> Regards!

Hi, @MiguelazoDS ,

It was indeed the network that caused the problem, I did an offline update with reference to your method and it is work now. 

Thank you very much!
