### ISSUE TITLE
Increased number of dropped events in the footprint test for Syscheck

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18711]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Syscheck | Manager | Packages/Sources | OS version |

When reviewing the [Syscheck footprint tests](https://github.com/wazuh/wazuh/issues/18657) for `4.5.2-rc1`, a very large increase has been seen in the plot for dropped events compared to version `4.5.1`. In `4.5.1` the dropped events were around `8000` and in `4.5.2` they were in the 63000s.

<details><summary>4.5.1</summary>

![image](https://github.com/wazuh/wazuh/assets/61122643/4475be02-5102-43ad-a40d-35afd553ae96)

</details>

<details><summary>4.5.2</summary>

![image](https://github.com/wazuh/wazuh/assets/61122643/58874da3-60cc-48a7-81b2-d15c7b2ae05c)

</details>

Previous values are the following(when a 6 hour test has been run, the value is not comparable)

|Version|Value|
|-|-|
|4.4.0 | No plot(it wasn't being produced)
|4.4.1 | 18k
|4.4.2 rc1 | 27k
|4.4.2 rc2 | 11k
|4.4.3, 4.4.4 | 6h
|4.4.5 | 27k
|4.5.0 | 6h
|4.5.1 | 7.5k
|4.5.2 | 63k

**Comment by nmkoremblum** [comment]
@verdx  What does the `6h` in the table mean?

**Comment by nmkoremblum** [comment]
Could you also please share the links to the referred tests?

**Comment by verdx** [comment]
@nmkoremblum Sorry, the test is the following: https://github.com/wazuh/wazuh/issues/18397 and the 6h means, as mentioned in the comment, that that test was run only for 6 hours and so the results are not comparable.

**Comment by verdx** [comment]
# Update

Error also seen in another Footprint test.

During the Footprint test `DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)`, https://github.com/wazuh/wazuh/issues/18662, there has been an important increase in events dropped, the peak per unit of time is the same but the overall number of times events have dropped has increased. The generated number of events has, at the same time, decreased a little bit, so it doesn't seem as a normal increase in the dropped ones.

<details><summary>Dropped events graphs</summary>

- Previous graph:
- ![image](https://github.com/wazuh/wazuh/assets/61122643/08742fbe-1a74-4ef8-b2e6-469f2aa9e49c)
- Current graph:
- ![image](https://github.com/wazuh/wazuh/assets/61122643/306eb6dc-9b4f-4a3f-ba2d-48fa8cffed96)

</details>

<details><summary>Generated events graphs</summary>

- Previous graph:
- ![image](https://github.com/wazuh/wazuh/assets/61122643/29eb78dd-9f21-48f8-86c2-25bae9fab70c)
- Current graph:
- ![image](https://github.com/wazuh/wazuh/assets/61122643/ae393fdd-20d4-4b5f-a74a-0293d3faeb35)

</details>

The logs and configurations of the agent are the following: https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4276-3600m/B4276_agent_ubuntu/logs/ossec_Test_stress_B4276_ubuntu_2023-08-28.zip

**Comment by nmkoremblum** [comment]
> # Update
> 
> Error also seen in another Footprint test.
> 
> During the Footprint test `DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)`, #18662, there has been an important increase in events dropped, the peak per unit of time is the same but the overall number of times events have dropped has increased. The generated number of events has, at the same time, decreased a little bit, so it doesn't seem as a normal increase in the dropped ones.
> Dropped events graphs
> Generated events graphs
> 
> The logs and configurations of the agent are the following: https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4276-3600m/B4276_agent_ubuntu/logs/ossec_Test_stress_B4276_ubuntu_2023-08-28.zip

This is not related to this particular issue, but, by just seeing the input events, it can be inferred that the tests are not comparable as the second test (`4.5.2`) receives many more events than the first one (`4.5.1`), in any case please open a new issue.

**Comment by verdx** [comment]
> This is not related to this particular issue, but, by just seeing the input events, it can be inferred that the tests are not comparable as the second test (4.5.2) receives many more events than the first one (4.5.1), in any case please open a new issue.

@nmkoremblum I have created a new issue for this problem: https://github.com/wazuh/wazuh/issues/18735
