### ISSUE TITLE
Different plot patterns for wazuh-modulesd [Disk usage, PSS, RSS-MAX and USS, Read_Ops] and execd [Disk read]

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18715]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | wazuh-modulesd | Manager | Packages/Sources | CentosOS |

**Test Issue:** https://github.com/wazuh/wazuh/issues/18660
**Jenkins Build:** https://ci.wazuh.info/job/Test_stress/4279/

An increase in usage was found on the Manager on the `wazuh-modulesd` daemon as well as an increase on disk_read from `wazuh-execd`.

- Disk: Overall disk usage increased from around 50 in 4.5.1 to around 80 in 4.5.2
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_Disk.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_Disk.png)

- Disk_Read: Up 25% from 8.5 to around 10.5 for `wazuh-execd`
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_Disk_Read.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_Disk_Read.png)

- Read_Ops: Down near 50% for `wazuh-modulesd`
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_Read_Ops.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_Read_Ops.png)

- PSS: Initial peak up from around 260k to 360k (33% increase) for `wazuh-modulesd`. Overall peaks are higher as well.
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_PSS.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_PSS.png)

- RSS-MAXMIN: Peaked higher from ~270k to ~380k (around 33% increase) for `wazuh-modulesd`
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_RSS_MAXMIN.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_RSS_MAXMIN.png)

- USS: Peaked higher from around 260k to around 360k (around 33% increase) for `wazuh-modulesd`
   - 4.5.1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.1/B4253-3600m/B4253_manager_centos/plots/monitor-manager-Test_stress_B4253_manager-pre-release_USS.png)
   - 4.5.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4279-3600m/B4279_manager_centos/plots/monitor-manager-Test_stress_B4279_manager-pre-release_USS.png)

**Comment by JorgeMarinoDev** [comment]
Research Results. (Special note regarding Disk Usage at the end)

Comparing RAW values from CSV. 

* 4.5.1
  * monitor-manager-Test_stress_B4253_manager-pre-release.csv
* 4.5.2
  * monitor-manager-Test_stress_B4279_manager-pre-release.csv



Disk_Read: Up 25% from 8.5 to around 10.5 for `wazuh-execd`

* 4.5.1 : 131072 Bytes
* 4.5.2 : 131072 Bytes
* Conclusion : No increase



Read_Ops: Down near 50% for `wazuh-modulesd`

* 4.5.1 : 5.597.918.576  with Read Bytes : 27.488.758.272
* 4.5.2 : 2.130.848.686  with Read Bytes : 32.434.126.848
* Conclusion : Read even more bytes with less operations. It's even a good thing, not an issue. Check for changes in any of the enabled modules.



PSS: Initial peak up from around 260k to 360k (33% increase) for `wazuh-modulesd`. Overall peaks are higher as well.

* Plots have different vertical scales. Not comparable straightforward.
* Both plots show the same tendencies. Same slowly rising ramp during resource release phase.
* No other considerable ramps showing a leak or incorrect buffering techniques.
* Even though there is a 33% increase in ONE peak, we are talking about around 100KiB. Disregard.



RSS-MAXMIN: Peaked higher from ~270k to ~380k (around 33% increase) for `wazuh-modulesd`

* Same behavior described above. Disregard. 
* This could be entirely related to reducing the Read_Ops. 



USS: Peaked higher from around 260k to around 360k (around 33% increase) for `wazuh-modulesd`

* Same behavior described above. Disregard.

To illustrate, corrected scales and overlapped the USS plots. They are pretty much the same. Disregard.
![image](https://github.com/wazuh/wazuh/assets/117848458/47b0bea2-ad15-4ba3-ba54-3e288e8173b5)


**About Disk Usage**
Meaning of the metric DISK% : 80% of Disk Usage **DOES NOT MEAN** that the HD is at 80% of it's capacity.
We can see in the source code of the monitor script [monitor.py](https://github.com/wazuh/wazuh-jenkins/blob/master/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py)
The metric DISK% tells how much a process is involved in the R/W Operations system wide. 
For example : 50%, means that i.e. `wazuh-modulesd` is responsible for the 50% of the RW operations in the disk at that specific moment when measured.
On the other hand, we would need to compare a long term behavior, checking ramps and so on.
Checking the source code, and the doc of the function used to compute the % [psutil](https://psutil.readthedocs.io/en/latest/#psutil.disk_io_counters). The 100% has all the read and written bytes SYSTEM WIDE. This is why all the plots of Disk Usage show an hyperbolic behavior, towards 0 in the end, asymptotic. We can not rely on this metric IMHO.
No conclusions regarding to this. 80% vs 50% does not mean much if we can't analyze the long term run.

**Comment by cborla** [comment]
LGTM
