### ISSUE TITLE
Vulnerability Detector warning in Footprint test. Bullseye database not found in 4.5.2

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#18713]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | Vulnerability detector | Manager | Packages/Sources | OS version |

A warning has appeared in the stress tests again for the Vulnerability Detector in the RC 1 stage of the `4.5.2` release. It appeared previously and it was issued https://github.com/wazuh/wazuh/issues/18447. 

The warning is the following:
```
wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Debian Bullseye' database could not be fetched.
```

Example:
- https://github.com/wazuh/wazuh/issues/18672
Log:
[ossec_Test_stress_B4271_manager_2023-08-28.zip](https://github.com/wazuh/wazuh/files/12465956/ossec_Test_stress_B4271_manager_2023-08-28.zip)

**Comment by TomasTurina** [comment]
Duplicated of https://github.com/wazuh/wazuh/issues/18447
