### ISSUE TITLE
Syscollector `packages` deltas from previous version does not have effect and cause Rsync sync

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#18714]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.2-rc1 | wazuh-db| Manager | Any | Any |

Found as part of https://github.com/wazuh/wazuh-qa/issues/4472
Related to changes developed here https://github.com/wazuh/wazuh/issues/18219

# Description

It was found that changes introduced as part of  https://github.com/wazuh/wazuh/issues/18219 implementation is not actually taking advantage of Syscollector delta mechanism and forcing a Rsync synchronization when Wazuh agent is older than 4.5.2-rc1 i.e 4.4.5

# Steps to reproduce

- Download 4.5.2-rc1 OVA https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.5.2.ova
  - Enable wazuh_db.debug=2 on local_internal_options.conf
  - Restart the manager
- On a Ubuntu 22.04 OS, 
  1. Install Wazuh Agent 4.4.5. 
  2. Enable only OS and Packages scan and set scan frequency to 5 minutes (this gives a better testing environment)
  3. Make sure 7zip package (sample package for testing purposes) is not installed on the system
  4. Start the agent
  5. Wait until the first syscollector scan ends
  6. Install 7zip package (apt install 7zip)
  7. Wait until the second syscollector scan ends

# Expected results

5- On the manager side, an initial Rsync does not show any 7zip package being sync (search on ossec.log)
7- On the manager side, on insertion Delta handle the 7zip information and no Rsync is necessary

# Current results
5- On the manager side, an initial Rsync does not show any 7zip package being sync (search on ossec.log)
7- On the manager side, on insertion Delta handle the 7zip information but also Rsync is executed and 7zip is updated, meaning that delta was not properly handled into the database or some inconsistency

```
2023/08/29 17:03:39 wazuh-db[22172] wdb_parser.c:263 at wdb_parse(): DEBUG: Agent 002 query: dbsync packages INSERTED {"architecture":"amd64","checksum":"69d774cf970b11a6cac9c87f9792a1de1e9049fa","description":"7-Zip file archiver with a high compression ratio","format":"deb","groups":"utils","item_id":"569f6ff9040271f10542b6ca7e8afd8055b7a7de","multiarch":null,"name":"7zip","priority":"optional","scan_time":"2023/08/29 17:03:38","size":2396,"source":null,"vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","version":"21.07+dfsg-4"}
2023/08/29 17:03:42 wazuh-db[22172] wdb_parser.c:263 at wdb_parse(): DEBUG: Agent 002 query: syscollector_packages save2 {"attributes":{"architecture":"amd64","checksum":"69d774cf970b11a6cac9c87f9792a1de1e9049fa","description":"7-Zip file archiver with a high compression ratio","format":"deb","groups":"utils","item_id":"569f6ff9040271f10542b6ca7e8afd8055b7a7de","multiarch":null,"name":"7zip","priority":"optional","scan_time":"2023/08/29 17:03:42","size":2396,"source":null,"vendor":"Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>","version":"21.07+dfsg-4"},"index":"569f6ff9040271f10542b6ca7e8afd8055b7a7de","timestamp":""}
```

# Extra information
- v4.5.2-rc1 agent and manager pair works does not have this issue.
- v4.4.5 agent and v4.5.1 manager works OK, meaning that the problem resides on v4.5.2-rc1

**Comment by MiguelazoDS** [comment]
After discussing with the team, the null pk fields for all data providers will be replaced by "" (empty string)
