### ISSUE TITLE
Check Wazuh compatibility with new version Debian 13 trixie

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#18726]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the new found version of Debian 13 trixie operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/18710

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] O.S. reporting in the interface.
- [x] WPK installation / upgrade / uninstall / upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [ ] ~SCA: Policy support.~
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by ncvicchi** [comment]
Debian trixie is no yet available and no release date has been established yet

**Comment by lchico** [comment]
I need to continue working on a higher-priority task.

**Comment by lchico** [comment]
Updating the ETA due to the higher priority of a new task that has come up.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/cbb841b0-a447-47c1-b216-7cec603fa530" alt="Con_dash">
</details>


<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/a93e43b5-c3b8-470b-84dc-9b7656bc345f" alt="Console">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ee233440-5f9b-4097-9546-3c4cb11ba056">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ba02f102-37ab-40ab-8338-226a4542214d">
</details>

## :red_circle: FIM Whodata

<details>
<summary>Configuration on the agent</summary>

  ```
    <directories whodata="yes">/testwhodata</directories>
  ```
</details>

<details>
<summary>Alerts</summary>

  ```
/var/ossec/logs/ossec.log:687820:2023/10/19 00:44:00 wazuh-syscheckd[235944] syscheck_audit.c:330 at audit_init(): WARNING: (6924): Who-data engine cannot start because Auditd is not running.
/var/ossec/logs/ossec.log-687821-2023/10/19 00:44:00 wazuh-syscheckd[235944] main.c:286 at main(): WARNING: (6913): Who-data engine could not start. Switching who-data to real-time.

--
root@de1d40ea1c2a:~# auditctl -w /etc -p wa -k wazuh_fim
You must be root to run this program.

  ```
</details>

Although alerts are received, there are just real-time alerts, with no whodata information.
<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/42fbef7d-ad98-4b60-a507-379ed1e2631d">
</details>


## :green_circle: Upgrade using WPK
WPK was downloaded from [here](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/wpk-list.html) and [this](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html#run-the-upgrade) procedure was follow (from step 2)

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/41576e3e-894f-4fb7-a9a6-93da77c45af2">
</details>


## :yellow_circle: SCA support
No official SCA policies are available (check [this list](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html)).

## :green_circle: Vulnerability detector


<details>
<summary>Manager Config</summary>

  ```
    <!-- Debian OS vulnerabilities -->
    <provider name="debian">
        <os allow="Debian GNU/Linux-0">bullseye</os>
      <enabled>yes</enabled>
      <os>buster</os>
      <os>bullseye</os>
      <update_interval>1m</update_interval>
    </provider>
  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/d46e6abb-a898-492a-96ee-46d35bcf0e36">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>


<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/0fdb15d1-7209-4f4b-ba76-4e04070c896f">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/b470b055-700b-4a18-a6a6-48df1caa3821">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/67a2c34d-8cff-4d6a-9f4a-7c1dd84b8d75">

</details>

**Comment by ncvicchi** [comment]
Moved ETA 1 day for reviewing

**Comment by jotacarma90** [comment]
LGTM

**Comment by DFolchA** [comment]
LGTM

**Comment by ncvicchi** [comment]
LGTM!
