### ISSUE TITLE
Migrate code analysis scan tool to Wazuh core repository

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18729]
Description

As part of the Wazuh-qa migration, the code analysis scan tool will be migrated to Wazuh core repository as well.

The [current code analysis tool](https://github.com/wazuh/wazuh-qa/tree/master/tests/scans/code_analysis) needs to be updated and migrated to ensure scalability for every wazuh update. For this task should be:

- Review current code.
- Upgrade flaws mapping.
- Test the tool.

Also, All necessary methods to run the scan used in [current wazuh-qa framework](https://github.com/wazuh/wazuh-qa/tree/master/deps/wazuh_testing/wazuh_testing) need to be updated and migrated to [qa-integration-framework repository ](https://github.com/wazuh/qa-integration-framework).

**Comment by Selutario** [comment]
Bandit action was enabled instead, done in:
- https://github.com/wazuh/wazuh/issues/19875
