### ISSUE TITLE
Increase in disk usage by `wazuh-modulesd` in 4.5.2 footprint test

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18728]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-rc1 | wazuh-modulesd | Agent | Packages/Sources | Ubuntu |

During the footprint tests for `4.5.2-rc1`, in issue https://github.com/wazuh/wazuh/issues/18662, an increase in `wazuh-modulesd` from almost 0 to 1.2*1e6 has been noted. It may have to do with issue https://github.com/wazuh/wazuh/issues/18693
  - Previous graph:
  - ![image](https://github.com/wazuh/wazuh/assets/61122643/20497ad3-908e-4fd1-8fee-0910bf2f1c6e)
  - Current graph: 
  - ![image](https://github.com/wazuh/wazuh/assets/61122643/18c6c85f-0cde-46ae-9a76-067ebe0d204a)

Logs and configurations of the agent: https://ci.wazuh.com/data/Test_stress/pre-release/4.5.2/B4276-3600m/B4276_agent_ubuntu/logs/ossec_Test_stress_B4276_ubuntu_2023-08-28.zip

**Comment by cborla** [comment]
## Analysis

As can be seen in the graphs, the increase in disk usage in reads is given in 5 stages, making a total sum of about 1.3 MB, the enabled integrations that can read are:
- cis-cat
- os-quer

Analyzing the agent's log at the time of the first increment, the following messages are found
```
2023/08/27 09:33:21 wazuh-modulesd:osquery: INFO: osqueryd is already running with pid 18957. Will run again in 10 minutes.
2023/08/27 09:33:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 09:34:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 09:35:49 wazuh-agentd: WARNING: Agent buffer is full: Events may be lost.
2023/08/27 09:35:50 wazuh-agentd: INFO: Agent buffer is under 70 %. Working properly again.
2023/08/27 09:35:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 09:36:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 09:37:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
2023/08/27 09:38:59 wazuh-modulesd:ciscat: INFO: Evaluation finished.
```

Everything appears to be normal, considering that the environment is under stress.

Comparing with the graphs of other operating systems, we see that they also have similar increases. [Centos](https://camo.githubusercontent.com/c19738c707b5a5384e228963f4ab181575015680cfb42cbd24c70bca523df40f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343237362d333630306d2f42343237365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343237365f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67)

## Conclusion
There is no reason that this represents an error of the agent, or of a module of the same, we are talking about a test of 2.5 days and the reading is 1.3 MB, moreover, I consider that the test is not stressing the modules correctly.

cc @vikman90
