### ISSUE TITLE
Vulnerability scanner

### ISSUE THREAD

**Issue by Henryera** [wazuh/wazuh#18734]
Good Morning,

I installed Wazuh ova. installed a few agents enabled vulnerability but getting this errors in the log.

|App version:4.5.1|Wazuh-OVA| on vmware

Aug 31, 2023 @ 12:22:41.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'Microsoft Security Update' database update.
Aug 31, 2023 @ 12:22:44.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'Microsoft Security Update' feed finished successfully.
Aug 31, 2023 @ 12:22:58.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Aug 31, 2023 @ 12:22:58.000 wazuh-modulesd:vulnerability-detector ERROR  (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
Aug 31, 2023 @ 12:27:58.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Aug 31, 2023 @ 12:27:58.000 wazuh-modulesd:vulnerability-detector ERROR  (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
Aug 31, 2023 @ 12:32:58.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Aug 31, 2023 @ 12:32:58.000 wazuh-modulesd:vulnerability-detector ERROR  (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
Aug 31, 2023 @ 12:37:58.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Aug 31, 2023 @ 12:37:58.000 wazuh-modulesd:vulnerability-detector ERROR  (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
Aug 31, 2023 @ 12:42:58.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'National Vulnerability Database' database update.

**Comment by davidcr01** [comment]
Hello.

I tested this behavior in the Wazuh OVA 4.5.1 and everything worked as expected:

```
23/09/04 07:52:41 wazuh-modulesd:vulnerability-detector: INFO (5430): The update of the 'National Vulnerability Database' feed finished successfully.
23/09/04 07:52:41 wazuh-modulesd:vulnerability-detector: INFO (5431): Starting vulnerability scan.
23/09/04 07:52:41 wazuh-modulesd:vulnerability-detector: INFO (5450): Analyzing agent '000' vulnerabilities.
23/09/04 07:52:41 wazuh-modulesd:vulnerability-detector: INFO (5471): Finished vulnerability assessment for agent '000'
23/09/04 07:52:42 wazuh-modulesd:vulnerability-detector: INFO (5472): Vulnerability scan finished.
```

Maybe you had an internet issue at the exact moment as the Wazuh OVA intended to receive the NVD feed.
Please:
- Make sure you have an internet connection. You can check this by executing the command `ping www.google.es`.
- Ensure you have the `vulnerability-detector` option enabled in the `/var/ossec/etc/ossec.conf` file.
- Ensure you have the `enabled` option set to `yes` in the `provider name="alas"` part, in the `/var/ossec/etc/ossec.conf` file.
- Restart the Wazuh server by executing the command `systemctl restart wazuh-manager`.

Hope it helps. Regards.
David.
