### ISSUE TITLE
Use of special characters from another supported languages ​​in wodle-commands by agents

### ISSUE THREAD

**Issue by tdrauncieal** [wazuh/wazuh#18743]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | wazuh-modulesd | Agent | Packages/Sources | All supported OS |

## Description
Due to the report that arose due to a misbehavior of the `wodle commands`, in relation to the special characters used in the various supported languages.

The user have all their Windows agents using the French version and they are trying to implement the system performance monitoring commands as explained in this [blog](https://wazuh.com/blog/monitoring-windows-resources-with-performance-counters/).

They tried implementing it using the English version of the commands (as stated on the blog) but they always got the following errors:
```
wazuh-modulesd:command: WARNING: Command 'WinServices' returned exit code 1.
wazuh-modulesd:command: WARNING: Command 'MEMUsage' returned exit code 1.
wazuh-modulesd:command: WARNING: Command 'DiskUsage' returned exit code 1.
wazuh-modulesd:command: WARNING: Command 'CPUUsage' returned exit code 1.
``` 
After further troubleshooting we found that the issue was due to their French Windows version, so we tried translating the commands from the original English:
``` 
	<wodle name="command">
		<disabled>no</disabled>
		<tag>MEMUsage</tag>
		<command>Powershell -c "@{ winCounter = (Get-Counter '\Memory\Available MBytes').CounterSamples[0] } | ConvertTo-Json -compress"</command>
		<interval>5m</interval>
		<ignore_output>no</ignore_output>
		<run_on_start>yes</run_on_start>
		<timeout>0</timeout>
	</wodle>
	<wodle name="command">
		<disabled>no</disabled>
		<tag>CPUUsage</tag>
		<command>Powershell -c "@{ winCounter = (Get-Counter '\Processor(_Total)\% Processor Time').CounterSamples[0] } | ConvertTo-Json -compress"</command>
		<interval>5m</interval>
		<ignore_output>no</ignore_output>
		<run_on_start>yes</run_on_start>
		<timeout>0</timeout>
	</wodle>
	<wodle name="command">
		<disabled>no</disabled>
		<tag>DiskUsage</tag>
		<command>Powershell -c "@{ winCounter = (Get-Counter -Counter '\LogicalDisk(C:)\% Free Space').CounterSamples[0]} | ConvertTo-Json -compress"</command>
		<interval>10m</interval>
		<ignore_output>no</ignore_output>
		<run_on_start>yes</run_on_start>
		<timeout>0</timeout>
	</wodle>
``` 
To the French version:
``` 
  <agent_config>
    <!-- Shared agent configuration here -->
    <wodle name="command">
      <disabled>no</disabled>
      <tag>Utilisation_Memoire</tag>
      <command>Powershell -c "@{ winCounter = (Get-Counter '\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"</command>
      <interval>5m</interval>
      <ignore_output>no</ignore_output>
      <run_on_start>yes</run_on_start>
      <timeout>0</timeout>
    </wodle>
    <wodle name="command">
      <disabled>no</disabled>
      <tag>Utilisation_CPU</tag>
      <command>Powershell -c "@{ winCounter = (Get-Counter '\processeur(_total)\% temps processeur').CounterSamples[0] } | ConvertTo-Json -compress"</command>
      <interval>5m</interval>
      <ignore_output>no</ignore_output>
      <run_on_start>yes</run_on_start>
      <timeout>0</timeout>
    </wodle>
    <wodle name="command">
      <disabled>no</disabled>
      <tag>Utilisation_Disque</tag>
      <command>Powershell -c "@{ winCounter = (Get-Counter -Counter '\disque logique(C:)\% d''espace libre').CounterSamples[0]} | ConvertTo-Json -compress"</command>
      <interval>10m</interval>
      <ignore_output>no</ignore_output>
      <run_on_start>yes</run_on_start>
      <timeout>0</timeout>
    </wodle>
  </agent_config>
``` 
After performing this change, all the commands started working correctly but this one:
```shell
Powershell -c "@{ winCounter = (Get-Counter '\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"
``` 
that continues generating the same error log:
``` 
wazuh-modulesd:command: INFO: Starting command 'Utilisation_Memoire'.
wazuh-modulesd:command: WARNING: Command 'Utilisation_Memoire' returned exit code 1.
``` 
Even though, when run manually, works without any issues:

```shell 
PS C:\Windows\system32> Powershell -c "@{ winCounter = (Get-Counter '\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress" {"winCounter":{"Path":"\\\\as6\\mémoire\\mégaoctets disponibles","InstanceName":null,"CookedValue":1663,"RawValue":1663,"SecondValue":0,"MultipleCount":1,"CounterType":6592,"Timestamp":"\/Date(1689107684745)\/","Timestamp100NSec":133335668847450000,"Status":0,"DefaultScale":0,"TimeBase":10000000}}
``` 
I've tested the same configuration on a Windows 10 French version, and I get the same error (even with debugging on, there's no extra info). My guess is that probably Wazuh can't handle the special character é on the command; we also tried escaping the command using the \ character, but got the same error:

```shell 
Powershell -c "@{ winCounter = (Get-Counter '\m\émoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"</command>
``` 
![image](https://github.com/wazuh/wazuh/assets/93778492/eb5dc87d-2c51-46da-92b2-ec26b96af71f)

As part of the solution, preliminary research was carried out that concluded the need to expand the capabilities offered, as can be seen in the following:

* Accented and other similar characters are found to cause this misbehavior since the saved settings are encoded as UTF-8 when retrieved
* Regarding the possibility of escaping these characters using the XML standard, as has been tried in the previous tests,
It is not currently available since the Parser that processes this data does not consider it as such.
* Similarly, it is not possible to set the encoding using the tools that XML has.
* It is not possible, in the current scenario, to favor any workaround except preventing commands from having these special characters.

As a possible improvement, the recognition of escape characters  
* `&#value;` 
* `u{value}`

## Workaround proposed
As a temporary solution, it is feasible to create an `intermediary script` that allows processing the command without special characters in the name.

```
<wodle name="command">
	<disabled>no</disabled>
	<tag>Test Command</tag>
	<command>Powershell -c C:\path\to\script.ps1</command>
	<interval>5m</interval>
	<ignore_output>no</ignore_output>
	<run_on_start>yes</run_on_start>
	<timeout>0</timeout>
</wodle>
``` 
<details><summary>script.ps1</summary>
<p>

```shell
Powershell -c "@{ winCounter = (Get-Counter -Counter '\LogicalDisk(C:)\% Free Space').CounterSamples[0]} | ConvertTo-Json -compress"
``` 
</p>
</details>
 
#### Related issues and information sources
* https://github.com/wazuh/wazuh/pull/15868

## DoD
- [x] Evaluate a possible implementation to `escape` special characters
- [x] Add the new feature analyzed
- [ ] Test on supported OS and languages
- [ ] Add Documentation of new features
- [ ] All test must be passed

**Comment by vikman90** [comment]
@tdrauncieal I've checked the code, and the agent tries to execute exactly the exact string we've set up in the configuration.

> Powershell -c "@{ winCounter = (Get-Counter '\mémoire\mégaoctets disponibles').CounterSamples[0] } | ConvertTo-Json -compress"

Might it work if we convert the command string to Unicode before running the subprocess?

Best!

**Comment by tdrauncieal** [comment]
The effort necessary to add UT to the `wm_exec()` function, related to the minimal changes made and taking into account that it is legacy code, seems in principle excessive such that there is no existing code.
I leave this for consideration @MarcelKemp.
