### ISSUE TITLE
Add new endpoint to retrieve available update information 

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#18757]
## Description

This issue aims to develop a new API endpoint to retrieve the information about the last update available.
The requirements are:
* The method and path of the new endpoint will be `GET /manager/version/check`
* The endpoint will not need authentication to be used, similar to `GET /`
* The data of the available update will be obtained from a global dictionary, defined in #18756
* The endpoint can be consulted on demand. However, the version information returned will be the one stored in the dictionaty mentioned above
* The output must be in JSON format and will follow the `WazuhResult` pattern (not `AffectedItemsWazuhResult`). It will include:
  * `title`. For example, `Wazuh v1.0.1 release`.
  * `tag`. For example, `v1.0.1`.
  * `description`.
  * `semver`. For example, `{"major": 1, "minor": 0, "patch": 1}`
  * `published_date` of the release. For example, 2015-12-15T22:11:05Z
  * `last_check_date`. It shows when was the last time that the Update check system obtained the available versions. For example, `2015-12-16T12:42:50Z`

## To be defined
* Definiteve path of the endpoint

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Unit Tests.
- [x] API Integration Tests
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by nico-stefani** [comment]
# Update

After discussing with the team, we decided to make some changes to the proposed endpoint response.

* Include the actual version of Wazuh in the format `vX.Y.Z`
* Include the last available version for each category (`major`, `minor`, `patch`)

So, the proposed response is:

```json
{
  "last_check_date": "2023-10-04T14:52:07.319561Z",
  "actual_version": "v4.8.0",
  "last_available_major": {
    "tag": "v5.0.0",
    "description": "Highlights of release 5.0.0",
    "title": "Wazuh 5.0.0",
    "published_date": "2023-10-03T10:44:00Z",
    "semver": {
      "minor": 0,
      "patch": 0,
      "major": 5
    }
  },
  "last_available_minor": {
    "tag": "v4.9.1",
    "description": "Highlights of release 4.9.1",
    "title": "Wazuh 4.9.1",
    "published_date": "2023-09-30T10:44:00Z",
    "semver": {
      "minor": 9,
      "patch": 1,
      "major": 4
    }
  },
  "last_available_patch": {
    "tag": "v4.8.3",
    "description": "Highlights of release 4.8.3",
    "title": "Wazuh 4.8.3",
    "published_date": "2023-09-22T10:44:00Z",
    "semver": {
      "minor": 8,
      "patch": 3,
      "major": 4
    }
  },
  "error": 0
}
``` 

Any suggestions are welcome.

@Selutario @Tostti @asteriscos @lucianogorza @gdiazlo

**Comment by Selutario** [comment]
## OK responses
@nico-stefani it looks good to me! I would just wrap the response inside a `data` key, similar to `POST /agents` and other endpoints:
```JSON
{
  "data": {
    "id": "002",
    "key": "MDAyIHRlc3RfYWdlbnQxIGFueSA3ODY1Yzg3OTkxZGY1NzhlMzdjYTU2MzExOTc2MmMwMWQ2MzUyYTI5Y2JiMTkzODg3NGFhOTFiYjcyNWJlZGMx"
  },
  "error": 0
}
``` 

<details>
<summary>Example</summary>

```JSON
{
  "data": {
    "last_check_date": "2023-10-04T14:52:07.319561Z",
    "current_version": "v4.8.0",
    "last_available_major": {
      "tag": "v5.0.0",
      "description": "Highlights of release 5.0.0",
      "title": "Wazuh 5.0.0",
      "published_date": "2023-10-03T10:44:00Z",
      "semver": {
        "minor": 0,
        "patch": 0,
        "major": 5
      }
    },
    "last_available_minor": {
      "tag": "v4.9.1",
      "description": "Highlights of release 4.9.1",
      "title": "Wazuh 4.9.1",
      "published_date": "2023-09-30T10:44:00Z",
      "semver": {
        "minor": 9,
        "patch": 1,
        "major": 4
      }
    },
    "last_available_patch": {
      "tag": "v4.8.3",
      "description": "Highlights of release 4.8.3",
      "title": "Wazuh 4.8.3",
      "published_date": "2023-09-22T10:44:00Z",
      "semver": {
        "minor": 8,
        "patch": 3,
        "major": 4
      }
    }
  },
  "error": 0
}
```

</details>

## Error responses
### Disabled
This `404` code is the API response when Experimental features are disabled and an experimental endpoint is used:
```JSON
{
  "title": "Resource Not Found",
  "detail": "Experimental features are disabled",
  "remediation": "Experimental features can be enabled in WAZUH_PATH/api/configuration/api.yaml or using API endpoint https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.put_api_config or https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.put_api_config",
  "error": 1122
}
```

Something similar should be returned when the Update check service is disabled.

### Error

For example, a `500 Internal server error` is returned when the API cannot connect with `wazuh-db`:
```JSON
{
  "title": "Wazuh Internal Error",
  "detail": "Could not connect to wdb socket: [Errno 111] Connection refused",
  "dapi_errors": {
    "master-node": {
      "error": "Could not connect to wdb socket: [Errno 111] Connection refused",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 2005
}
```

We could do the same for any error (for example, connecting to the CTI).

**Comment by nico-stefani** [comment]
# Update

I was working on the implementation of the controller and trying to pass the application context through the DAPI.

**Comment by nico-stefani** [comment]
# Update

I was working on the productization of the endpoint controller and the API spec.

**Comment by nico-stefani** [comment]
A requirement was given when the update check system was `disabled`.

Currently, we are responding with `404`:

```json
{
  "title": "Resource Not Found",
  "detail": "Experimental features are disabled",
  "remediation": "Experimental features can be enabled in WAZUH_PATH/api/configuration/api.yaml or using API endpoint https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.put_api_config or https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.put_api_config",
  "error": 1122
}
```

Instead of that, the response should be something similar to:

```json
{
  "data": {
    "last_check_date": "",
    "current_version": "v4.8.0",
    "update_check": false,
    "last_available_major": {},
    "last_available_minor": {},
    "last_available_patch": {}
  },
  "error": 0
}
```

Will include a new boolean field `update_check`, that always be present, indicating if the service is enabled or not.
Still, we are talking about the final implementation, but this is a first approach.

**Comment by nico-stefani** [comment]
# Update

I have been making progress on:
* Refactor the logic to make the CTI requests moving it to the framework
* Adding a query parameter to the endpoint to force the query on demand

**Comment by nico-stefani** [comment]
I have been making progress on:
* Implement a 404 response when the request isn't made on the master node
* Unit tests for API and framework functions
* Defining API integration test cases
