### ISSUE TITLE
wazuh-agent package missing dependency chkconfig

### ISSUE THREAD

**Issue by juresaht2** [wazuh/wazuh#18778]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4-1 | Wazuh | Agent | Packages | RHEL9 |

As mentioned in #14888 , when installing the agent in the recommended way (as indicated in the "Add agent" interface on the dashboard) on RHEL 9 compatible systems, the dependency chkconfig is not installed and so the agent fails to start.

**Comment by vzz1x2** [comment]
Instructions in the "Add agent" page should at least mention that 
`dnf install chkconfig`
Is needed in order to enable wazuh-agent with systemctl

**Comment by damarisg** [comment]
The "chkconfig" dependency was removed for 4.4.5 at https://github.com/wazuh/wazuh-packages/pull/2257
