### ISSUE TITLE
Vulnerability scan won't work

### ISSUE THREAD

**Issue by siaiwnl** [wazuh/wazuh#18779]
Hello!

I am trying to scan my hosts for vulnerabilities, and i have also edited configuration for enabling the scan. I have both restarted my manager and agents, but it still will not conclude any scans. I am not sure why. Does anyone have an idea why?

![vuln1](https://github.com/wazuh/wazuh/assets/144135103/5c181791-9983-454c-8169-015c01b4129f)

I had the scans working before, but had to reconfigure my setup, since i needed my manager to have a static IP address. After i reconfigured, and sat my agents up again, it will just not scan anymore. Not sure why :(

![image](https://github.com/wazuh/wazuh/assets/144135103/ba1c1dfe-8fa7-4a6e-8032-8d06d2782cd9)

I have the OVA installation in VMware and have a windows agent connected. 

Thanks in advance :)

**Comment by davidcr01** [comment]
Hello. Yes, you should be able to connect other machines of other networks, as long as the network is reachable to the other network.

When you want to access a service from outside your local network, you need to forward that request from your public IP to your private IP.
One way can be through port forwarding, configured in your router. Another way can be using SSH tunnels, such as `ngrok` (ngrok.com) or similar.

Also, you can check the connectivity using telnet to the IP you are requesting, and the following port.
