### ISSUE TITLE
Investigate why `wazuh/core/wazuh.json` is malformed 

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#18785]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.8.0 | framework | Manager | 

# Description

The file `wazuh/core/wazuh.json`  is being created with invalid data. After installing Wazuh 4.8.0 from sources the content is

```json
{"install_type": null, "wazuh_version": null, "installation_date": "Tue Sep 05 19:53:07 UTC 2023"}
```

This caused an error during the installation that broke `mitredb.py` and `wazuh-apid.py`

```
[notice] To update, run: /var/ossec/framework/python/bin/python3 -m pip install --upgrade pip
cd ../tools/mitre && /var/ossec/framework/python/bin/python3 mitredb.py -d /var/ossec/var/db/mitre.db
Traceback (most recent call last):
  File "/wazuh/tools/mitre/mitredb.py", line 25, in <module>
    import wazuh.core.utils as core_utils
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/__init__.py", line 11, in <module>
    from wazuh.core.wdb import WazuhDBConnection
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/wdb.py", line 16, in <module>
    from wazuh.core.exception import WazuhInternalError, WazuhError
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/exception.py", line 12, in <module>
    DOCU_VERSION = 'current' if WAZUH_VERSION == '' else '.'.join(WAZUH_VERSION.split('.')[:2]).lstrip('v')
AttributeError: 'NoneType' object has no attribute 'split'
make: *** [Makefile:2281: install_mitre] Error 1
Generating self-signed certificate for wazuh-authd...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
server
Traceback (most recent call last):
  File "/var/ossec/api/scripts/wazuh-apid.py", line 12, in <module>
    from api.constants import API_LOG_PATH
  File "/var/ossec/framework/python/lib/python3.9/site-packages/api/constants.py", line 7, in <module>
    from wazuh.core import common
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/__init__.py", line 11, in <module>
    from wazuh.core.wdb import WazuhDBConnection
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/wdb.py", line 16, in <module>
    from wazuh.core.exception import WazuhInternalError, WazuhError
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh/core/exception.py", line 12, in <module>
    DOCU_VERSION = 'current' if WAZUH_VERSION == '' else '.'.join(WAZUH_VERSION.split('.')[:2]).lstrip('v')
AttributeError: 'NoneType' object has no attribute 'split'
wazuh-apid: Configuration error. Exiting
```

## Steps to reproduce

* Install Wazuh from sources, this first time works ok
* Remove Wazuh `/var/ossec/bin/wazuh-control stop && rm -rf /var/ossec`
* Try to install it again

**Comment by mhamra** [comment]
### INVESTIGATION UPDATE
I've installed from sources a wazuh server, cloning the repo from the wazuh master branch. (v4.8.0) in an Ubuntu 22.04 container. The installation worked fine, but I could reproduce the reported problem. Once the /var/ossec is removed and the installation is started again, the reported failure occurs, and the content of the framework/core/wazuh.json file is similar to what was informed in this issue.
 
The setuptools package version is 65.5.1
<details>

```
/var/ossec/framework/python/bin/python3 -m pip show setuptools
Name: setuptools
Version: 65.5.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License:
Location: /var/ossec/framework/python/lib/python3.9/site-packages
Requires:
Required-by: google-api-core, google-auth
```
</details>

**Comment by mhamra** [comment]
### UPDATE
After a conversation with @Selutario, we removed the --config-options parameters, making them hardcoded values. The WAZUH_VERSION variable will be updated by the bump_version.sh script.

The wheel installation method installs the package in a different folder than the egg installation method. I must investigate if this change has side effects in other wazuh repositories.

**Comment by mhamra** [comment]
## INVESTIGATION - NEW INSTALLATION FOLDER SIDE EFFECTS

Result of investigating each wazuh repository. I searched the '.egg' and 'site-package' strings on the files and assessed if the findings were relevant to this issue.

### wazuh-jenkins
dockers/repositories/wazuh/framework_python/get_framework_python.sh
quality/tests/generic/common_files/linux/check_files/check_files_data.json

### wazuh-qa
No relevant files found

### wazuh-tools
framework/environments/dev/docker-compose.yml
