### ISSUE TITLE
Add the Application Verifier tool to the Windows tests

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#18789]
## Description

Considering that the issue #18739 was found using App Verifier (https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/application-verifier), it would be useful to add this tool to a testing pipeline that helps us to enhance the quality and reliability of the Windows agent. 

These are some of the issues that the tool is able to detect:
- Basics
- Compatibility
- Cuzz (The Concurrency Fuzzing)
- Low Resource Simulation
- LuaPriv (Limited User Account Privilege Predictor)
- Miscellaneous
- Networking
- NTLM
- Printing
- Webservices
- Services
- Perf
- Hangs

## DoD

- [ ] Find the best way to include the tool in a test pipeline (consider that it works better with a debugger like Windbg)
- [ ] Fix any warning/crash that arises

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
