### ISSUE TITLE
wazuh services shutdown randomly

### ISSUE THREAD

**Issue by jonoinnz** [wazuh/wazuh#18792]
Hi Wazuh Team,

Firstly, thank you for a great product.

|4.5.0-1|agent|Install type|offline|Ubuntu 22.04.2 LTS|

We are experiencing a problem where our agent just dies with:

2023/08/22 13:08:21 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2023/08/22 13:08:21 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/08/22 13:08:21 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/08/22 13:08:21 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/08/22 13:08:21 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...

What could be stopping the services?

Regards,
Jonathan

**Comment by jonoinnz** [comment]
Some additional info:

2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep  6 09:25:01 mcon-web-epayment-admin-01 CRON[590162]: pam_uni'...
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep  6 09:25:01 mcon-web-epayment-admin-01 CRON[590162]: pam_lim'...
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep  6 09:25:01 mcon-web-epayment-admin-01 CRON[590162]: pam_lim'...
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep  6 09:25:01 mcon-web-epayment-admin-01 CRON[590162]: pam_uni'...
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:148 at read_syslog(): DEBUG: Read 4 lines from /var/log/auth.log
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:104 at read_syslog(): DEBUG: Reading syslog message: 'Sep  6 09:25:01 mcon-web-epayment-admin-01 CRON[590164]: (root) '...
2023/09/06 09:25:02 wazuh-logcollector[589073] read_syslog.c:148 at read_syslog(): DEBUG: Read 1 lines from /var/log/syslog
2023/09/06 09:25:12 wazuh-logcollector[589073] logcollector.c:475 at LogCollectorStart(): DEBUG: Performing file check.
2023/09/06 09:25:38 wazuh-execd[589039] execd.c:92 at ExecdShutdown(): INFO: (1314): Shutdown received. Deleting responses.
2023/09/06 09:25:38 wazuh-execd[589039] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/09/06 09:25:38 wazuh-logcollector[589073] sig_op.c:49 at HandleSIG(): INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/09/06 09:25:38 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2023/09/06 09:25:38 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...

**Comment by jonoinnz** [comment]
Restarting agent:

/var/ossec/logs# /var/ossec/bin/wazuh-control restart
2023/09/06 12:06:16 wazuh-execd[592479] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/09/06 12:06:16 wazuh-execd[592479] main.c:111 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/09/06 12:06:16 wazuh-logcollector[592482] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/09/06 12:06:16 wazuh-logcollector[592482] main.c:126 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/09/06 12:06:16 wazuh-logcollector[592482] agent_op.c:219 at os_read_agent_profile(): DEBUG: Calling os_read_agent_profile().
2023/09/06 12:06:16 wazuh-logcollector[592482] agent_op.c:238 at os_read_agent_profile(): DEBUG: os_read_agent_profile() = [ubuntu, ubuntu22, ubuntu22.04]
2023/09/06 12:06:16 wazuh-logcollector[592482] config.c:424 at ReadConfig(): DEBUG: agent_config element does not have any attributes.
Deleting PID file '/var/ossec/var/run/wazuh-modulesd-589093.pid' not used...
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
Wazuh v4.5.0 Stopped
Starting Wazuh v4.5.0...
2023/09/06 12:06:17 wazuh-execd[592510] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/09/06 12:06:17 wazuh-execd[592510] main.c:111 at main(): DEBUG: Wazuh home directory: /var/ossec
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
2023/09/06 12:06:20 wazuh-logcollector[592547] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/09/06 12:06:20 wazuh-logcollector[592547] main.c:126 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/09/06 12:06:20 wazuh-logcollector[592547] agent_op.c:219 at os_read_agent_profile(): DEBUG: Calling os_read_agent_profile().
2023/09/06 12:06:20 wazuh-logcollector[592547] agent_op.c:238 at os_read_agent_profile(): DEBUG: os_read_agent_profile() = [ubuntu, ubuntu22, ubuntu22.04]
2023/09/06 12:06:20 wazuh-logcollector[592547] config.c:424 at ReadConfig(): DEBUG: agent_config element does not have any attributes.
2023/09/06 12:06:20 wazuh-logcollector[592547] main.c:175 at main(): ERROR: Could not set resource limit for file descriptors to 1100: Operation not permitted (1)
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.

**Comment by pereyra-m** [comment]
Hello @jonoinnz !

Reading the logs above, there are two that might give us a clue

> Deleting PID file '/var/ossec/var/run/wazuh-modulesd-589093.pid' not used...

This one suggests that there was a problem with `wazuh-modulesd`, a crash for example, and a dangling thread was removed by `wazuh-control`. There could be more information in the system logs, what is the output of `grep "segfault\|wazuh" /var/log/syslog` ?

And this one

> 2023/09/06 12:06:20 wazuh-logcollector[592547] main.c:175 at main(): ERROR: Could not set resource limit for file descriptors to 1100: Operation not permitted (1)

Suggests a permissions issue. This shouldn't happen in a normal installation. 

How did you install the agent? Does this happen with another host?

Please, follow the next troubleshooting steps

- Stop the agent: `/var/ossec/bin/wazuh-control stop`
- Make sure there isn't any process running with `/var/ossec/bin/wazuh-control status` and `ps -aux | grep wazuh`
- Open many terminals, and in each of them launch a daemon in foreground

1. `/var/ossec/bin/wazuh-agentd -fdd`
2. `/var/ossec/bin/wazuh-execd -fdd`
3. `/var/ossec/bin/wazuh-logcollector -fdd`
4. `/var/ossec/bin/wazuh-modulesd -fdd`
5. `/var/ossec/bin/wazuh-syscheckd -fdd`

Wait to see if any of them fail, and upload all the information collected so we can analyze it.

Regards.

**Comment by jonoinnz** [comment]
> Hello @jonoinnz !
> 
> Reading the logs above, there are two that might give us a clue
> 
> > Deleting PID file '/var/ossec/var/run/wazuh-modulesd-589093.pid' not used...
> 
> This one suggests that there was a problem with `wazuh-modulesd`, a crash for example, and a dangling thread was removed by `wazuh-control`. There could be more information in the system logs, what is the output of `grep "segfault\|wazuh" /var/log/syslog` ?
> 
> And this one
> 
> > 2023/09/06 12:06:20 wazuh-logcollector[592547] main.c:175 at main(): ERROR: Could not set resource limit for file descriptors to 1100: Operation not permitted (1)
> 
> Suggests a permissions issue. This shouldn't happen in a normal installation.
> 
> How did you install the agent? Does this happen with another host?
> 
> Please, follow the next troubleshooting steps
> 
> * Stop the agent: `/var/ossec/bin/wazuh-control stop`
> * Make sure there isn't any process running with `/var/ossec/bin/wazuh-control status` and `ps -aux | grep wazuh`
> * Open many terminals, and in each of them launch a daemon in foreground
> 
> 1. `/var/ossec/bin/wazuh-agentd -fdd`
> 2. `/var/ossec/bin/wazuh-execd -fdd`
> 3. `/var/ossec/bin/wazuh-logcollector -fdd`
> 4. `/var/ossec/bin/wazuh-modulesd -fdd`
> 5. `/var/ossec/bin/wazuh-syscheckd -fdd`
> 
> Wait to see if any of them fail, and upload all the information collected so we can analyze it.
> 
> Regards.

[...]

Hi Matias,

Thank you for the reply and process to troubleshoot this, Interestingly enough, when I used "/etc/init.d/wazuh-agent restart" the agent would die, or /var/ossec/bin/wazuh-control restart, the same issue, but when I used systemctl restart wazuh-agent the agent's been connected for over a week now without disconnecting. We keep on monitoring and if it dies again I will troubleshoot with the steps provided. 

Regards.

**Comment by pereyra-m** [comment]
Thank you for the update @jonoinnz !

**Comment by Dwordcito** [comment]
Thank you for being part of the community, if the problem arises again, please reopen the problem and we will try to help you so that you can use the product.

Greetings.
