### ISSUE TITLE
Little suggestion for ossec.conf

### ISSUE THREAD

**Issue by rwagner-inf** [wazuh/wazuh#188]
Hey guys!

I have modified the netstat command in my ossec.conf agents files, it is very annoying to search and compare the ports without ordering. Then I set the netstat command to the following:
`netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sed 's/:/ : /' | sort -k6 -g | sed 's/ : /:/'`

In this way, sorting will be done by the LISTENING ports in ascending order, making viewing easier.

![image](https://user-images.githubusercontent.com/24550871/30213097-edc79d0c-947d-11e7-8dbe-5152c2ff20f7.png)

And it will also not change the order, if there is any modification in another column, example **Recv-Q** or **Send-Q**

What do you think? Could you adopt this modification in the next versions?

**Comment by vikman90** [comment]
Hi @rwagner-inf,

cool proposition! We are trying to solve also the issue https://github.com/wazuh/wazuh/issues/179, but we have also to deal with IPv6 connections. In this case we have a result like this:

```
netstat -tuln | sed "s/:\([[:digit:]]\+\) / : \1 /" | sort -k 6 -g | sed "s/ : \([[:digit:]]\+\) /:\1 /"
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN
tcp6       0      0 :::25                   :::*                    LISTEN
udp        0      0 127.0.0.53:53           0.0.0.0:*
udp        0      0 0.0.0.0:68              0.0.0.0:*
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
udp        0      0 0.0.0.0:514             0.0.0.0:*
udp6       0      0 :::514                  :::*
udp        0      0 0.0.0.0:1514            0.0.0.0:*
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN
tcp6       0      0 :::5355                 :::*                    LISTEN
udp        0      0 0.0.0.0:5355            0.0.0.0:*
udp6       0      0 :::5355                 :::*
tcp6       0      0 :::55000                :::*                    LISTEN
```

We are working on it. Thank you for your feedback!

Best regards.

**Comment by kdslkdsaldsal** [comment]
Coming from https://github.com/wazuh/wazuh/issues/179 i'm also not quite sure if the netstat output should contain the ``Program name`` but should strip away the ``PID``?

Reason: It could be useful to trigger an alert if e.g. a service named ``foo`` listening on e.g. 8080 was killed and replaced by another service ``bar`` listening on the same port. But i guess if some one gets at this level he could also rename the binary from ``foo`` to ``bar`` to avoid triggering an alert.

**Comment by rwagner-inf** [comment]
Hi guys!
Returning the discussion.

  > Reason: It could be useful to trigger an alert if e.g. a service named foo listening on e.g. 8080 was killed and replaced by another service bar listening on the same port. But i guess if some one gets at this level he could also rename the binary from foo to bar to avoid triggering an alert.
I agree with what the xiruliru said. I do not know about the need to show the name of the program that is in listening.

I also do not like the display of the Recv-Q Send-Q columns, which generate unnecessary alerts. Since the focus of this monitoring is on new ports in LISTENING mode, and the connection queue issue does not make much sense here.

I made some more filters, considering what xiruliru 2 said about the IPv6 problem, I disabled the IPv6 on the hosts, so I did not consider it in the filters (so I created a vm with IPV6 for the tests), but with the filters that I did will only show the protocol column and the column of ip: port, sorting through the ports, which is what I think would be useful in monitoring. 

![image](https://user-images.githubusercontent.com/24550871/30499839-6ce16b04-9a32-11e7-9be4-9c29e7112a5a.png)


Or we just leave the column with IP: Port.
I did not really like how it got organized, but it's sort.

![image](https://user-images.githubusercontent.com/24550871/30500665-c1d7d7ee-9a35-11e7-8e76-b87a87c3c23c.png)


I'd like to know what you think.

**Comment by vikman90** [comment]
Hi @rwagner-inf,

we have implemented the opened port list order by port number as you proposed. The commit is https://github.com/wazuh/wazuh/commit/e1d8bcbf053427a54cfa1aa4a1312b8cfe5b5dd6 and we are discussing this in https://github.com/wazuh/wazuh/issues/179#issuecomment-331103152.

Let me close this issue. Please continue discussing this in the referred issue.

Thanks for your feedback.
Best regards.
