### ISSUE TITLE
Refactor the migrate_date RBAC method and extend it's unit test coverage

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#18808]
|Wazuh version|Component|
|---|---|
| 4.6.0| Manager |

## Description

During the development of https://github.com/wazuh/wazuh/issues/18771, It was found that currently, the [migrate_data](https://github.com/wazuh/wazuh/blob/88f03b2c6eac9dd2c80cb2d020d4b3fe7784f25d/framework/wazuh/rbac/orm.py#L2775) method is very extensive because it needs to migrate all entities related to RBAC (roles, rules, users and policies).

Also, the mentioned method does not have the necessary test coverage to test that the migration inner methods are being executed properly throughout more use cases. 

This issue should be addressed to:

- [x] Investigate whether the method should be refactored to avoid coupling and make it more scalable, extendable, and readable.
- [x] Develop unit tests to extend the coverage to further test the method, especially the migration of rules, roles, and policies.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
# Update

Created the `migrate_ddata` method for each of the `RBACManager`. Now I continue with the development of each unit test.

**Comment by RamosFe** [comment]
## Update

Added unit test for `AuthenticationManager`, `RolesManager`, `PoliciesManager`, `UserRolesManager`.

**Comment by RamosFe** [comment]
## Update

I start to investigate the changes made to `orm.py` in `master` to fix the merge conflict with master.

**Comment by RamosFe** [comment]
## Update

Continue to add the changes proposed in the CR.
