### ISSUE TITLE
Prevent false positives about new files in FIM

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#1881]
File integrity monitoring may produce some incoherences due to dropped packages:

- If the scan end mark is lost, new files in next scans won't be reported.
- If some files are lost in the first scan, but the scan end mark is received, then those files will be reported as new in the next scan.

The network may drop some messages (UDP), or the manager may discard some events in case of overload. But this should not produce data incoherences.

Related issue: #1766

**Comment by Lopuiz** [comment]
Hi team,

I am going to close this issue because new FIM solves it

Regards,
Eva
