### ISSUE TITLE
Release 4.6.0 - Alpha 1 - E2E UX tests - Wazuh dashboard

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18828]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-alpha1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, or Docker) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Communicate these to QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/frontend team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html) | Single node | Amazon Linux 2023 x86_64 |
| Server | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-server/installation-assistant.html) | Single node | Amazon Linux 2023 x86_64 |
| Dashboard | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-dashboard/installation-assistant.html) | - | Amazon Linux 2023 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.6.0-alpha1/_images/deploy-new-agent-from-ui1.png) | - | Amazon Linux 2023 x86_64 |

## Test description

Best effort to test Wazuh dashboard package. Think critically and at least review/test:
- Wazuh dashboard package specs
- Dashboard package size
- Dashboard package metadata (description)
- Dashboard package digital signature
- Installed files location, size and permissions
- Installation footprint (check that no unnecessary files are modified/broken in the file system. For example that operating system files do keep their right owner/pemissions and that the installer did not break the system.)
- Installed service (test that it works correctly)
- Wazuh Dashboard logs when installed
- Wazuh Dashboard configuration (Try to find anomalies compared with previous version)
- Wazuh Dashboard (included the Wazuh WUI) communication with Wazuh manager API and Wazuh indexer
- Basic browsing throguh the WUI
- Basic experience with WUI performance.
- Cache
Anything else that could have been overlooked when creating the new package

## Known issues

- https://github.com/wazuh/wazuh-packages/issues/1749
- https://github.com/wazuh/wazuh-packages/issues/1414
- https://github.com/wazuh/wazuh/issues/13013
- https://github.com/wazuh/wazuh/issues/12973
- https://github.com/wazuh/wazuh-kibana-app/issues/4226

## Conclusion

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|Wazuh dashboard package specs|
|:yellow_circle:|OpenSearch information |Non useful information still visible|https://github.com/wazuh/wazuh/issues/12973|
|:green_circle:|Dashboard package size|||
|:green_circle:|Dashboard package metadata |||
|:green_circle:|Dashboard package digital signature|||
|Installation process|
|:green_circle:|Installed files location, size and permissions & Installation footprint|||
|:red_circle: |Installed service|Packages and Os version recommendations|https://github.com/wazuh/wazuh-packages/issues/2432, https://github.com/wazuh/wazuh-packages/issues/2436, https://github.com/wazuh/wazuh-packages/issues/2430, https://github.com/wazuh/wazuh-packages/issues/2434|
|:green_circle:|Wazuh Dashboard logs when installed|||
|WUI browsing experiece|
|:red_circle:|Basic browsing through the WUI & Basic experience with WUI performance |Logs are not working|https://github.com/wazuh/wazuh/issues/18939|
|Cache memory|
|:green_circle:|Cache|||
|Additional test|
|:green_circle:|Agent-Central components connection|||

The test was performed many times because the specification of hardware requirements, and the network configuration were not 100% clear.

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?

It was clear generally talking. Specific test requirements were not visible so https://github.com/wazuh/wazuh/issues/18387  was used as reference.

- Did you face any challenges not covered by the guideline?

Configuring network, EC2: The test should be performed many times because the specification of hardware requirements, and the network configuration were not 100% clear.

- Suggestions for improvement:

Add specifications regarding the hardware requirements.
There could be specific explanations on how to configure the key and the network on AWS for the EC2.
Add preconditions and expected values in each step of the test.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/frontend

**Comment by pro-akim** [comment]
# Environment installation :red_circle: 

Each component was installed using the `Installation assistant`.

## Wazuh indexer

```shellsession
[root@ip-172-31-38-157 ec2-user]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
[root@ip-172-31-38-157 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.6/wazuh-install.sh
[root@ip-172-31-38-157 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.6/config.yml
[root@ip-172-31-38-157 ec2-user]# nano ./config.yml 
[root@ip-172-31-38-157 ec2-user]# cat config.yml 
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 0.0.0.0
    #- name: node-2
    #  ip: <indexer-node-ip>
    #- name: node-3
    #  ip: <indexer-node-ip>

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: 0.0.0.0
    #  node_type: master
    #- name: wazuh-2
    #  ip: <wazuh-manager-ip>
    #  node_type: worker
    #- name: wazuh-3
    #  ip: <wazuh-manager-ip>
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 0.0.0.0
[root@ip-172-31-38-157 ec2-user]# bash wazuh-install.sh --generate-config-files
07/09/2023 14:10:01 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
07/09/2023 14:10:01 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/09/2023 14:10:05 INFO: --- Dependencies ---
07/09/2023 14:10:05 INFO: Installing curl.
07/09/2023 14:10:05 ERROR: Cannot install dependency: curl.

```

**Comment by pro-akim** [comment]
## Wazuh dashboard :red_circle:


```shellsession
[root@ip-172-31-37-148 ec2-user]# yum install curl --allowerasing
Last metadata expiration check: 1:42:23 ago on Fri Sep  8 08:40:13 2023.
Dependencies resolved.
======================================================================================================
 Package                Architecture     Version                          Repository             Size
======================================================================================================
Installing:
 curl                   x86_64           8.2.1-1.amzn2023.0.2             amazonlinux           341 k
Removing dependent packages:
 curl-minimal           x86_64           8.2.1-1.amzn2023.0.2             @System               269 k

Transaction Summary
======================================================================================================
Install  1 Package
Remove   1 Package

Total download size: 341 k
Is this ok [y/N]: y
Downloading Packages:
curl-8.2.1-1.amzn2023.0.2.x86_64.rpm                                  2.8 MB/s | 341 kB     00:00    
------------------------------------------------------------------------------------------------------
Total                                                                 1.8 MB/s | 341 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                              1/1 
  Installing       : curl-8.2.1-1.amzn2023.0.2.x86_64                                             1/2 
  Erasing          : curl-minimal-8.2.1-1.amzn2023.0.2.x86_64                                     2/2 
  Running scriptlet: curl-minimal-8.2.1-1.amzn2023.0.2.x86_64                                     2/2 
  Verifying        : curl-8.2.1-1.amzn2023.0.2.x86_64                                             1/2 
  Verifying        : curl-minimal-8.2.1-1.amzn2023.0.2.x86_64                                     2/2 

Installed:
  curl-8.2.1-1.amzn2023.0.2.x86_64                                                                    
Removed:
  curl-minimal-8.2.1-1.amzn2023.0.2.x86_64                                                            

Complete!


[root@ip-172-31-37-148 ec2-user]# bash wazuh-install.sh --generate-config-files --ignore-check
08/09/2023 10:23:29 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 10:23:29 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 10:23:38 WARNING: Hardware and system checks ignored.
08/09/2023 10:23:38 INFO: --- Configuration files ---
08/09/2023 10:23:38 INFO: Generating configuration files.
08/09/2023 10:23:40 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.

[root@ip-172-31-37-148 ec2-user]# bash wazuh-install.sh --wazuh-dashboard dashboard
08/09/2023 10:24:49 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 10:24:49 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 10:24:53 ERROR: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04. The current system does not match this list. Use -i|--ignore-check to skip this check.

[root@ip-172-31-37-148 ec2-user]# bash wazuh-install.sh --wazuh-dashboard dashboard --ignore-check
08/09/2023 10:25:10 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 10:25:10 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 10:25:19 WARNING: Hardware and system checks ignored.
08/09/2023 10:25:19 INFO: Wazuh web interface port will be 443.
08/09/2023 10:25:20 INFO: --- Dependencies ---
08/09/2023 10:25:20 INFO: Installing gnupg2.
08/09/2023 10:25:20 ERROR: Cannot install dependency: gnupg2.
[root@ip-172-31-37-148 ec2-user]# yum install gnupg2 --allowerasing
Last metadata expiration check: 1:45:41 ago on Fri Sep  8 08:40:13 2023.
Dependencies resolved.
======================================================================================================
 Package                    Architecture   Version                          Repository           Size
======================================================================================================
Installing:
 gnupg2                     x86_64         2.3.7-1.amzn2023.0.4             amazonlinux         2.5 M
Installing dependencies:
 libksba                    x86_64         1.6.3-1.amzn2023.0.2             amazonlinux         159 k
 libsecret                  x86_64         0.20.4-2.amzn2023.0.2            amazonlinux         158 k
 libusbx                    x86_64         1.0.24-2.amzn2023.0.2            amazonlinux          73 k
 pcsc-lite                  x86_64         1.9.1-1.amzn2023.0.3             amazonlinux          92 k
 pcsc-lite-libs             x86_64         1.9.1-1.amzn2023.0.3             amazonlinux          28 k
 polkit                     x86_64         0.117-11.amzn2023                amazonlinux         146 k
 polkit-libs                x86_64         0.117-11.amzn2023                amazonlinux         8.3 M
 polkit-pkla-compat         x86_64         0.1-19.amzn2023.0.2              amazonlinux          45 k
Installing weak dependencies:
 gnupg2-smime               x86_64         2.3.7-1.amzn2023.0.4             amazonlinux         249 k
 pcsc-lite-ccid             x86_64         1.4.34-1.amzn2023.0.3            amazonlinux         300 k
 pinentry                   x86_64         1.2.0-1.amzn2023.0.5             amazonlinux          99 k
Removing dependent packages:
 gnupg2-minimal             x86_64         2.3.7-1.amzn2023.0.4             @System             917 k

Transaction Summary
======================================================================================================
Install  12 Packages
Remove    1 Package

Total download size: 12 M
Is this ok [y/N]: y
Downloading Packages:
(1/12): pcsc-lite-libs-1.9.1-1.amzn2023.0.3.x86_64.rpm                321 kB/s |  28 kB     00:00    
(2/12): polkit-0.117-11.amzn2023.x86_64.rpm                           1.4 MB/s | 146 kB     00:00    
(3/12): pcsc-lite-ccid-1.4.34-1.amzn2023.0.3.x86_64.rpm               2.7 MB/s | 300 kB     00:00    
(4/12): libusbx-1.0.24-2.amzn2023.0.2.x86_64.rpm                      1.0 MB/s |  73 kB     00:00    
(5/12): pcsc-lite-1.9.1-1.amzn2023.0.3.x86_64.rpm                     728 kB/s |  92 kB     00:00    
(6/12): libsecret-0.20.4-2.amzn2023.0.2.x86_64.rpm                    3.1 MB/s | 158 kB     00:00    
(7/12): pinentry-1.2.0-1.amzn2023.0.5.x86_64.rpm                      1.0 MB/s |  99 kB     00:00    
(8/12): polkit-pkla-compat-0.1-19.amzn2023.0.2.x86_64.rpm             1.4 MB/s |  45 kB     00:00    
(9/12): libksba-1.6.3-1.amzn2023.0.2.x86_64.rpm                       1.9 MB/s | 159 kB     00:00    
(10/12): gnupg2-2.3.7-1.amzn2023.0.4.x86_64.rpm                       9.3 MB/s | 2.5 MB     00:00    
(11/12): gnupg2-smime-2.3.7-1.amzn2023.0.4.x86_64.rpm                 3.1 MB/s | 249 kB     00:00    
(12/12): polkit-libs-0.117-11.amzn2023.x86_64.rpm                      36 MB/s | 8.3 MB     00:00    
------------------------------------------------------------------------------------------------------
Total                                                                  20 MB/s |  12 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                              1/1 
  Installing       : polkit-libs-0.117-11.amzn2023.x86_64                                        1/13 
  Running scriptlet: polkit-0.117-11.amzn2023.x86_64                                             2/13 
  Installing       : polkit-0.117-11.amzn2023.x86_64                                             2/13 
  Running scriptlet: polkit-0.117-11.amzn2023.x86_64                                             2/13 
  Installing       : polkit-pkla-compat-0.1-19.amzn2023.0.2.x86_64                               3/13 
  Installing       : libksba-1.6.3-1.amzn2023.0.2.x86_64                                         4/13 
  Installing       : libsecret-0.20.4-2.amzn2023.0.2.x86_64                                      5/13 
  Installing       : pinentry-1.2.0-1.amzn2023.0.5.x86_64                                        6/13 
  Installing       : libusbx-1.0.24-2.amzn2023.0.2.x86_64                                        7/13 
  Installing       : pcsc-lite-libs-1.9.1-1.amzn2023.0.3.x86_64                                  8/13 
  Installing       : pcsc-lite-1.9.1-1.amzn2023.0.3.x86_64                                       9/13 
  Running scriptlet: pcsc-lite-1.9.1-1.amzn2023.0.3.x86_64                                       9/13 
Created symlink /etc/systemd/system/sockets.target.wants/pcscd.socket → /usr/lib/systemd/system/pcscd.socket.

  Installing       : pcsc-lite-ccid-1.4.34-1.amzn2023.0.3.x86_64                                10/13 
  Running scriptlet: pcsc-lite-ccid-1.4.34-1.amzn2023.0.3.x86_64                                10/13 
  Installing       : gnupg2-smime-2.3.7-1.amzn2023.0.4.x86_64                                   11/13 
  Installing       : gnupg2-2.3.7-1.amzn2023.0.4.x86_64                                         12/13 
  Erasing          : gnupg2-minimal-2.3.7-1.amzn2023.0.4.x86_64                                 13/13 
  Running scriptlet: gnupg2-minimal-2.3.7-1.amzn2023.0.4.x86_64                                 13/13 
  Verifying        : pcsc-lite-ccid-1.4.34-1.amzn2023.0.3.x86_64                                 1/13 
  Verifying        : polkit-0.117-11.amzn2023.x86_64                                             2/13 
  Verifying        : pcsc-lite-libs-1.9.1-1.amzn2023.0.3.x86_64                                  3/13 
  Verifying        : pcsc-lite-1.9.1-1.amzn2023.0.3.x86_64                                       4/13 
  Verifying        : gnupg2-2.3.7-1.amzn2023.0.4.x86_64                                          5/13 
  Verifying        : libusbx-1.0.24-2.amzn2023.0.2.x86_64                                        6/13 
  Verifying        : pinentry-1.2.0-1.amzn2023.0.5.x86_64                                        7/13 
  Verifying        : libsecret-0.20.4-2.amzn2023.0.2.x86_64                                      8/13 
  Verifying        : libksba-1.6.3-1.amzn2023.0.2.x86_64                                         9/13 
  Verifying        : polkit-pkla-compat-0.1-19.amzn2023.0.2.x86_64                              10/13 
  Verifying        : polkit-libs-0.117-11.amzn2023.x86_64                                       11/13 
  Verifying        : gnupg2-smime-2.3.7-1.amzn2023.0.4.x86_64                                   12/13 
  Verifying        : gnupg2-minimal-2.3.7-1.amzn2023.0.4.x86_64                                 13/13 

Installed:
  gnupg2-2.3.7-1.amzn2023.0.4.x86_64               gnupg2-smime-2.3.7-1.amzn2023.0.4.x86_64          
  libksba-1.6.3-1.amzn2023.0.2.x86_64              libsecret-0.20.4-2.amzn2023.0.2.x86_64            
  libusbx-1.0.24-2.amzn2023.0.2.x86_64             pcsc-lite-1.9.1-1.amzn2023.0.3.x86_64             
  pcsc-lite-ccid-1.4.34-1.amzn2023.0.3.x86_64      pcsc-lite-libs-1.9.1-1.amzn2023.0.3.x86_64        
  pinentry-1.2.0-1.amzn2023.0.5.x86_64             polkit-0.117-11.amzn2023.x86_64                   
  polkit-libs-0.117-11.amzn2023.x86_64             polkit-pkla-compat-0.1-19.amzn2023.0.2.x86_64     
Removed:
  gnupg2-minimal-2.3.7-1.amzn2023.0.4.x86_64                                                          

Complete!

[root@ip-172-31-37-148 ec2-user]# bash wazuh-install.sh --wazuh-dashboard dashboard --ignore-check
08/09/2023 10:26:07 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
08/09/2023 10:26:07 INFO: Verbose logging redirected to /var/log/wazuh-install.log
08/09/2023 10:26:16 WARNING: Hardware and system checks ignored.
08/09/2023 10:26:16 INFO: Wazuh web interface port will be 443.
08/09/2023 10:26:17 INFO: Wazuh development repository added.
08/09/2023 10:26:17 INFO: --- Wazuh dashboard ----
08/09/2023 10:26:18 INFO: Installing chrome.
08/09/2023 10:27:08 INFO: --- Dependencies ---
08/09/2023 10:27:08 INFO: Installing xorg-x11-fonts-100dpi.
08/09/2023 10:27:10 INFO: Installing xorg-x11-fonts-75dpi.
08/09/2023 10:27:12 INFO: Installing xorg-x11-utils.
08/09/2023 10:27:14 INFO: Installing xorg-x11-fonts-cyrillic.
08/09/2023 10:27:15 INFO: Installing xorg-x11-fonts-Type1.
08/09/2023 10:27:16 INFO: Installing xorg-x11-fonts-misc.
08/09/2023 10:27:19 INFO: Starting Wazuh dashboard installation.
08/09/2023 10:28:58 INFO: Wazuh dashboard installation finished.
08/09/2023 10:28:58 INFO: Wazuh dashboard post-install configuration finished.
08/09/2023 10:28:58 INFO: Starting service wazuh-dashboard.
08/09/2023 10:28:59 INFO: wazuh-dashboard service started.
08/09/2023 10:30:10 INFO: Initializing Wazuh dashboard web application.
08/09/2023 10:32:11 ERROR: Cannot connect to Wazuh dashboard.


```

**Comment by pro-akim** [comment]
## Update

It should be retested with a t3.large Ec2.
It has been started, but some failures were detected, and further research should be done.

**Comment by pro-akim** [comment]
## Update
After executing it in t3.large Ec2, Wazuh-indexer was successfully installed, then the following issue was closed:
- https://github.com/wazuh/wazuh-packages/issues/2435

**Comment by pro-akim** [comment]
## Agent Registration :gree_circle:

<details> <summary> Amazon Linux 2023 </summary>

### Wazuh Agent addition Command :green_circle:

Manager
```shellsession

[root@ip-172-31-94-20 ec2-use/var/ossec/bin/agent_groups -a -g test
Do you want to create the group 'test'? [y/N]: y
Group 'test' created.
[root@ip-172-31-94-20 ec2-user]# /var/ossec/bin/agent_groups -l
Groups (2):
  default (0)
  test (0)
Unassigned agents: 0.

[root@ip-172-31-94-20 ec2-user]# nslookup  44.201...
72.77.201.44.in-addr.arpa	name = ec2-44-201..compute-1.amazonaws.com.

Authoritative answers can be found from:
```

Agent

```shellsession
[root@ip-172-31-91-95 ec2-user]# curl -o wazuh-agent-4.6.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.6.0-1.x86_64.rpm && sudo WAZUH_MANAGER='ec2-44-201-77-72.compute-1.amazonaws.com' WAZUH_AGENT_GROUP='test' rpm -ihv wazuh-agent-4.6.0-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9179k  100 9179k    0     0  10.2M      0 --:--:-- --:--:-- --:--:-- 10.2M
warning: wazuh-agent-4.6.0-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-agent-4.6.0-1              ################################# [100%]
uavc:  op=setenforce lsm=selinux enforcing=0 res=1uavc:  op=load_policy lsm=selinux seqno=6 res=1

[root@ip-172-31-91-95 ec2-user]# ls
wazuh-agent-4.6.0-1.x86_64.rpm  wazuh-install-files.tar  wazuh-install.sh
[root@ip-172-31-91-95 ec2-user]# systemctl status wazuh-agent
○ wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; disabled; prese>
     Active: inactive (dead)
lines 1-3/3 (END)

[root@ip-172-31-91-95 ec2-user]# cat /var/ossec/etc/ossec.conf 
<!--
  Wazuh - Agent - Default configuration for amzn 1
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>
  <client>
    <server>
      <address>ec2-44-201-77-72.compute-1.amazonaws.com</address>
      <port>1514</port>
      (...)
```
![3 dashboard wazuh initialed](https://github.com/wazuh/wazuh/assets/125690423/03ebe546-fe06-43cd-8d09-7b4e3151e516)


### Activating wazuh Agents :green_circle:

Agent

```shellsession
[root@ip-172-31-91-95 ec2-user]# sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /usr/lib/systemd/system/wazuh-agent.service.
[root@ip-172-31-91-95 ec2-user]# sudo systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; preset>
     Active: active (running) since Mon 2023-09-11 10:39:57 UTC; 1min 17s ago
    Process: 34188 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (cod>
      Tasks: 32 (limit: 9349)
     Memory: 39.5M
        CPU: 10.680s
     CGroup: /system.slice/wazuh-agent.service
             ├─34407 /var/ossec/bin/wazuh-execd
             ├─34420 /var/ossec/bin/wazuh-agentd
             ├─34436 /var/ossec/bin/wazuh-syscheckd
             ├─34466 /var/ossec/bin/wazuh-logcollector
             └─34516 /var/ossec/bin/wazuh-modulesd

Sep 11 10:39:53 ip-172-31-91-95.ec2.internal systemd[1]: Starting wazuh-agent.ser>
Sep 11 10:39:53 ip-172-31-91-95.ec2.internal env[34188]: Starting Wazuh v4.6.0...
Sep 11 10:39:53 ip-172-31-91-95.ec2.internal env[34188]: Started wazuh-execd...
Sep 11 10:39:54 ip-172-31-91-95.ec2.internal env[34188]: Started wazuh-agentd...
Sep 11 10:39:54 ip-172-31-91-95.ec2.internal env[34188]: Started wazuh-syscheckd.>
Sep 11 10:39:54 ip-172-31-91-95.ec2.internal env[34188]: Started wazuh-logcollect>
Sep 11 10:39:55 ip-172-31-91-95.ec2.internal env[34188]: Started wazuh-modulesd...
Sep 11 10:39:57 ip-172-31-91-95.ec2.internal env[34188]: Completed.
Sep 11 10:39:57 ip-172-31-91-95.ec2.internal systemd[1]: Started wazuh-agent.serv>
lines 1-23/23 (END)
```

Manager

```shellsession
[root@ip-172-31-94-20 ec2-user]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-94-20.ec2.internal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-172-31-91-95.ec2.internal, IP: any, Active

List of agentless devices:
```
![5 agent added](https://github.com/wazuh/wazuh/assets/125690423/ff567873-e551-4dda-8498-283d9551c8c5)

</details>

**Comment by pro-akim** [comment]
## Basic browsing through the WUI & Basic experience with WUI performance :red_circle:

<details> <summary> Views </summary> 

- Login :green_circle:
![1 dashboard login](https://github.com/wazuh/wazuh/assets/125690423/9defacd1-8aa8-4780-8ce8-d873d031e2a8)

- Login processing :green_circle:
![2 dashboard login process](https://github.com/wazuh/wazuh/assets/125690423/d4a977f0-0664-4f2f-8373-bdc29f81a27b)

- Dashboard initialized :green_circle:
![3 dashboard wazuh initialed](https://github.com/wazuh/wazuh/assets/125690423/7ee1a6d4-fa3d-41fa-b336-a0a309e5d590)

- Modules :green_circle:
![5 agent added](https://github.com/wazuh/wazuh/assets/125690423/464db6f6-042c-4956-8442-867ea3eec720)

- Agents :green_circle:
![6 agent info](https://github.com/wazuh/wazuh/assets/125690423/961a32e6-7346-4bae-9064-6c7b195836c4)

- Security Events and Alerts :green_circle:
![7 agent events](https://github.com/wazuh/wazuh/assets/125690423/1038c3b0-dd96-4a1e-9b2a-d2f157dc8915)
![8 agent alerts](https://github.com/wazuh/wazuh/assets/125690423/c99458bd-21cf-4cd5-9495-bac031abee0e)


- Logs :red_circle:
![9 agent logs](https://github.com/wazuh/wazuh/assets/125690423/1034400f-4b71-40a4-969e-d0cd4fd4148f)
![10 agent logs details](https://github.com/wazuh/wazuh/assets/125690423/1760e682-5cad-49c9-ba7a-bb234343b7fa)

</details>

**Comment by pro-akim** [comment]
## Final summary (issues)


## Reported
### Related to packages

- https://github.com/wazuh/wazuh-packages/issues/2432 
- https://github.com/wazuh/wazuh-packages/issues/2436 

Both related to:
- https://github.com/wazuh/wazuh-packages/issues/2430

### Related to Dashboard Logs Failure
- https://github.com/wazuh/wazuh/issues/18939

### Related to recommended OS to install Wazuh
- https://github.com/wazuh/wazuh-packages/issues/2434

## Previous reported issues
- https://github.com/wazuh/wazuh-packages/issues/1749 it was not replicated.
- https://github.com/wazuh/wazuh-packages/issues/1414 it was not replicated.
- https://github.com/wazuh/wazuh-kibana-app/issues/4226 it was not replicated.
- https://github.com/wazuh/wazuh/issues/12973 no changes have been observed.
- https://github.com/wazuh/wazuh/issues/13013 it was not replicated, however, after reinstalling the indexer, dashboard did not work. a new issue was opened: 
- https://github.com/wazuh/wazuh-kibana-app/issues/5877

**Comment by pro-akim** [comment]
## Update
The requested changes were performed.
Moved back to pending review

**Comment by mauromalara** [comment]
@pro-akim a Good job! But it requires some extra changes that we talked about in a meeting.

**Comment by pro-akim** [comment]
### Update
Discussed changes done.

**Comment by mauromalara** [comment]
LGTM.

**Comment by davidjiglesias** [comment]
LGTM!
