### ISSUE TITLE
Release 4.6.0 - Alpha 1 - E2E UX tests - Deployment on docker

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18824]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-alpha1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, or Docker) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Communicate these to QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/cicd team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Deployment on docker](https://documentation-dev.wazuh.com/v4.6.0-alpha1/deployment-options/docker/wazuh-container.html) | Single node and multi node | - |
| Server | [Deployment on docker](https://documentation-dev.wazuh.com/v4.6.0-alpha1/deployment-options/docker/wazuh-container.html) | Single node and multi node | - |
| Dashboard | [Deployment on docker](https://documentation-dev.wazuh.com/v4.6.0-alpha1/deployment-options/docker/wazuh-container.html) | - | - |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.6.0-alpha1/_images/deploy-new-agent-from-ui1.png) | - | Amazon Linux 2 aarch64 |

## Test description

Test deployment of Docker repository.
- Test the installation guide in detail for both a single-node and a multi-node Wazuh cluster
- Test changing the passwords

Documentation: https://documentation-dev.wazuh.com/v4.6.0-alpha1/deployment-options/docker/index.html

## Known issues

- https://github.com/wazuh/wazuh/issues/12862
- https://github.com/wazuh/wazuh/issues/18299

## Conclusions :red_circle: 

Errors detected

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|🔴|[Clone the wazuh-docker repository](https://github.com/wazuh/wazuh/issues/18824#issuecomment-1710692071)|Generate custom images and start Wazuh using docker-compose|https://github.com/wazuh/wazuh-docker/issues/984|

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - Yes, The guidance is clear and the steps correct, but the test failed at the beginning so this answer is biased.
- Did you face any challenges not covered by the guideline?
  - Yes, inside the steps to execute that appear in the documentation, I had to add an extra step because it is a custom version, the command is: `Generate custom images (because it is a development release) and start Wazuh using docker-compose.
` It is at the end of the tests performed.
- Suggestions for improvement:
  - Perhaps develop a separate section/mensage within the issue where to place comments/conclusions, so as not to edit the description section which has so much sensitive data and information.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/cicd

**Comment by cborla** [comment]
## Single-node deployment :red_circle: 

<details><summary>Install required software and set-up the environment :green_circle: </summary><br>

1. Increase max_map_count on your host (Linux)
```shell
# sudo sysctl -w vm.max_map_count=262144 
vm.max_map_count = 262144

# sudo sysctl vm.max_map_count
vm.max_map_count = 262144
```

2. Check architecture
```shell
# uname -r
5.15.0-83-generic
# uname -2
5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

3. Install the Docker engine
```shell
# curl -sSL https://get.docker.com/ | sh
```
4. Start the Docker engine
```shell
# sudo systemctl start docker
```


5. Install `docker-compose`
```shell
# curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# chmod +x /usr/local/bin/docker-compose

# docker-compose --version

Docker Compose version v2.12.2

```

</details>



<details><summary>Wazuh stack deployment using Docker :red_circle:</summary><br>

1. Clone the `wazuh-docker` repository
```shell
# git clone https://github.com/wazuh/wazuh-docker.git -b v4.6.0-alpha1

Cloning into 'wazuh-docker'...
fatal: Remote branch v4.6.0 not found in upstream origin

```

</details>

**Comment by cborla** [comment]
## Multi-node deployment :red_circle: 

<details><summary>Install required software and set-up the environment :green_circle: </summary><br>

1. Increase max_map_count on your host (Linux)
```shell
# sudo sysctl -w vm.max_map_count=262144 
vm.max_map_count = 262144

# sudo sysctl vm.max_map_count
vm.max_map_count = 262144
```

2. Check architecture
```shell
# uname -r
5.15.0-83-generic
# uname -2
5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

3. Install the Docker engine
```shell
# curl -sSL https://get.docker.com/ | sh
```
4. Start the Docker engine
```shell
# sudo systemctl start docker
```


5. Install `docker-compose`
```shell
# curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# chmod +x /usr/local/bin/docker-compose

# docker-compose --version

Docker Compose version v2.12.2

```

</details>



<details><summary>Wazuh stack deployment using Docker :red_circle:</summary><br>

1. Clone the `wazuh-docker` repository
```shell
# git clone https://github.com/wazuh/wazuh-docker.git -b v4.6.0-alpha1

Cloning into 'wazuh-docker'...
fatal: Remote branch v4.6.0 not found in upstream origin

```

</details>

**Comment by cborla** [comment]
## Single-node deployment :red_circle: 

<details><summary>Install required software and set-up the environment :green_circle: </summary><br>

1. Increase max_map_count on your host (Linux)
```shell
# sudo sysctl -w vm.max_map_count=262144 
vm.max_map_count = 262144

# sudo sysctl vm.max_map_count
vm.max_map_count = 262144
```

2. Check architecture
```shell
# uname -r
5.15.0-83-generic
# uname -2
5.15.0-83-generic #92~20.04.1-Ubuntu SMP Mon Aug 21 14:00:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

3. Install the Docker engine
```shell
# curl -sSL https://get.docker.com/ | sh
```
4. Start the Docker engine
```shell
# sudo systemctl start docker
```


5. Install `docker-compose`
```shell
# curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# chmod +x /usr/local/bin/docker-compose

# docker-compose --version

Docker Compose version v2.12.2

```
</details>


<details><summary>Wazuh stack deployment using Docker 🔴 </summary><br>

1. Clone the `wazuh-docker` repository
```shell
# git clone https://github.com/wazuh/wazuh-docker.git -b v4.6.0-alpha1
```
2. Get into the `single-node` folder
```shell
# cd wazuh-docker/single-node
```
3. Generate certificates
```

# docker-compose -f generate-indexer-certs.yml run --rm generator

[+] Running 1/0
 ⠿ Network single-node_default  Created                                                                                                                                                                       0.1s
[+] Running 5/5
 ⠿ generator Pulled                                                                                                                                                                                          31.3s
   ⠿ edaedc954fb5 Pull complete                                                                                                                                                                              23.7s
   ⠿ 573f4d11a520 Pull complete                                                                                                                                                                              26.5s
   ⠿ 8f200922197d Pull complete                                                                                                                                                                              26.5s
   ⠿ 55a86de68c5c Pull complete                                                                                                                                                                              26.6s
The tool to create the certificates exists in the in Packages bucket
08/09/2023 14:17:21 INFO: Admin certificates created.
08/09/2023 14:17:21 INFO: Wazuh indexer certificates created.
08/09/2023 14:17:21 INFO: Wazuh server certificates created.
08/09/2023 14:17:21 INFO: Wazuh dashboard certificates created.
Moving created certificates to the destination directory
Changing certificate permissions
Setting UID indexer and dashboard
Setting UID for wazuh manager and worker

# ls -l config/wazuh_indexer_ssl_certs/


# ls -l config/wazuh_indexer_ssl_certs/
total 48
-r-------- 1 ubuntu-user             ubuntu-user             1704 sep  8 11:17 admin-key.pem
-r-------- 1 ubuntu-user             ubuntu-user             1119 sep  8 11:17 admin.pem
-r-------- 1 ubuntu-user             ubuntu-user             1704 sep  8 11:17 root-ca.key
-r-------- 1 systemd-resolve systemd-journal 1704 sep  8 11:17 root-ca-manager.key
-r-------- 1 systemd-resolve systemd-journal 1204 sep  8 11:17 root-ca-manager.pem
-r-------- 1 ubuntu-user             ubuntu-user             1204 sep  8 11:17 root-ca.pem
-r-------- 1 ubuntu-user             ubuntu-user             1704 sep  8 11:17 wazuh.dashboard-key.pem
-r-------- 1 ubuntu-user             ubuntu-user             1261 sep  8 11:17 wazuh.dashboard.pem
-r-------- 1 ubuntu-user             ubuntu-user             1708 sep  8 11:17 wazuh.indexer-key.pem
-r-------- 1 ubuntu-user             ubuntu-user             1257 sep  8 11:17 wazuh.indexer.pem
-r-------- 1 ubuntu-user             ubuntu-user             1704 sep  8 11:17 wazuh.manager-key.pem
-r-------- 1 ubuntu-user             ubuntu-user             1257 sep  8 11:17 wazuh.manager.pem

```


4. Generate custom images (because is a development release) and start Wazuh using `docker-compose`
```shell
# cd ../ && sudo build-docker-images/build-images.sh && cd -

[+] Building 4.8s (17/76)                                                                                                                                                                                          
 => [wazuh/wazuh-indexer:4.6.0 internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 2.38kB                                                                                                                                                                        0.0s
 => [wazuh/wazuh-manager:4.6.0 internal] load build definition from Dockerfile                                                                                                                                0.0s
 => => transferring dockerfile: 2.24kB                                                                                                                                                                        0.0s
 => [wazuh/wazuh-dashboard:4.6.0 internal] load build definition from Dockerfile                                                                                                                              0.0s
 => => transferring dockerfile: 3.43kB                                                                                                                                                                        0.0s
 => [wazuh/wazuh-indexer:4.6.0 internal] load .dockerignore                                                                                                                                                   0.1s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [wazuh/wazuh-dashboard:4.6.0 internal] load .dockerignore                                                                                                                                                 0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [wazuh/wazuh-manager:4.6.0 internal] load .dockerignore                                                                                                                                                   0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [wazuh/wazuh-dashboard:4.6.0 internal] load metadata for docker.io/library/ubuntu:focal                                                                                                                   4.5s
 => [wazuh/wazuh-manager:4.6.0  1/18] FROM docker.io/library/ubuntu:focal@sha256:33a5cc25d22c45900796a1aca487ad7a7cb09f09ea00b779e3b2026b4fc2faba                                                             0.2s
 => => resolve docker.io/library/ubuntu:focal@sha256:33a5cc25d22c45900796a1aca487ad7a7cb09f09ea00b779e3b2026b4fc2faba                                                                                         0.0s
 => => sha256:33a5cc25d22c45900796a1aca487ad7a7cb09f09ea00b779e3b2026b4fc2faba 1.13kB / 1.13kB                                                                                                                0.0s
 => => sha256:3246518d9735254519e1b2ff35f95686e4a5011c90c85344c1f38df7bae9dd37 424B / 424B                                                                                                                    0.0s
 => => sha256:6df89402372646d400cf092016c28066391a26f5d46c00b1153e75003465484d 2.30kB / 2.30kB                                                                                                                0.0s
 => [wazuh/wazuh-manager:4.6.0 internal] load build context                                                                                                                                                   0.1s
 => => transferring context: 25.03kB                                                                                                                                                                          0.0s
 => ERROR [wazuh/wazuh-manager:4.6.0] https://raw.githubusercontent.com/wazuh/wazuh/4.6/extensions/elasticsearch/7.x/wazuh-template.json                                                                      0.8s
 => [wazuh/wazuh-indexer:4.6.0 internal] load build context                                                                                                                                                   0.1s
 => => transferring context: 20.13kB                                                                                                                                                                          0.0s
 => [wazuh/wazuh-dashboard:4.6.0 internal] load build context                                                                                                                                                 0.0s
 => => transferring context: 13.44kB                                                                                                                                                                          0.0s
 => [wazuh/wazuh-indexer:4.6.0 stage-1  2/14] RUN getent group wazuh-indexer || groupadd -r -g 1000 wazuh-indexer                                                                                             1.1s
 => CANCELED [wazuh/wazuh-dashboard:4.6.0 builder  2/17] RUN apt-get update && apt install curl libcap2-bin xz-utils -y                                                                                       1.3s
 => [wazuh/wazuh-manager:4.6.0  2/18] RUN rm /bin/sh && ln -s /bin/bash /bin/sh                                                                                                                               1.1s
 => CANCELED [wazuh/wazuh-indexer:4.6.0 builder 2/9] RUN apt-get update -y && apt-get install curl openssl xz-utils -y                                                                                        1.4s
 => CANCELED [wazuh/wazuh-dashboard:4.6.0 stage-1  2/11] RUN apt update && apt install -y libnss3-dev fonts-liberation libfontconfig1                                                                         1.3s
 => CANCELED [wazuh/wazuh-indexer:4.6.0 stage-1  3/14] RUN useradd --system             --uid 1000             --no-create-home             --home-dir /usr/share/wazuh-indexer             --gid wazuh-inde  0.9s
------                                                                                                                                                                                                             
 > [wazuh/wazuh-manager:4.6.0] https://raw.githubusercontent.com/wazuh/wazuh/4.6/extensions/elasticsearch/7.x/wazuh-template.json:
------
failed to solve: failed to load cache key: invalid response status 404

```


</details>

**Comment by davidjiglesias** [comment]
LGTM!
