### ISSUE TITLE
Release 4.6.0 - Alpha 1 - E2E UX tests - Configuration assessment

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#18833]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-alpha1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, or Docker) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Communicate these to QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html) | Multi node | Fedora 38 x86_64 |
| Server | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html) | Single node | Fedora 38 x86_64 |
| Dashboard | [Installation assistant](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html) | - | Fedora 38 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using FQDN](https://documentation-dev.wazuh.com/v4.6.0-alpha1/_images/deploy-new-agent-from-ui1.png) | - | Windows server 2016 x86_64, Debian 10 x86_64, Fedora 38 x86_64, macOS Ventura arm|

## Test description

For the selected Wazuh Agent OS:
- Check that their respective SCA policies are applied properly
- Use and activate a custom policy for any of them
- Disable an used policy and confirm it is not used anymore
- Push SCA config through centralized config and check it applies properly

## Known issues

- https://github.com/wazuh/wazuh-packages/issues/1422
- https://github.com/wazuh/wazuh/issues/12347

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟡 | macOS Ventura agent installation with Wazuh WUI one-liner deploy using FQDN | The `WAZUH_MANAGER` variable did not work on the installation | #18933  |
| :yellow_circle:  | Push SCA config through centralized config and check it applies properly with Fedora | Fedora operating system does not have an SCA policy | #18306  |
| :yellow_circle:  | Push SCA config through centralized config and check it applies properly with Windows Server 2016 | Failure when attempting to create an SCA policy with Windows Server 2016 | #18981   |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  Everything was clear and without any ambiguity
- Did you face any challenges not covered by the guideline?
   No
- Suggestions for improvement:

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [ ] @wazuh/security-warriors

**Comment by javiersanchz** [comment]
# Environment

Set up the environment with `Vagrant` and `VirtualBox`, for the `macOS Ventura ARM` agent (not found in the Vagrantfile), I requested the CICD team to create a VM in this [issue](https://github.com/wazuh/internal-devel-requests/issues/220) with the corresponding operating system and architecture.

<details>
  <summary>Vagrantfile</summary>

```
Vagrant.configure("2") do |config|
  config.vm.define "indexer" do |instance|
    instance.vm.box = "fedora/38-cloud-base"
    instance.vm.hostname = "indexer"
    instance.vm.network "private_network", ip: "192.168.56.9"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "4096"
      pmv.cpus = 2
      pmv.name = "E2E_indexer"
    end
  end

  config.vm.define "manager" do |instance|
    instance.vm.box = "fedora/38-cloud-base"
    instance.vm.hostname = "manager"
    instance.vm.network "private_network", ip: "192.168.56.11"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "2048"
      pmv.cpus = 2
      pmv.name = "E2E_manager"
    end
  end

  config.vm.define "dashboard" do |instance|
    instance.vm.box = "fedora/38-cloud-base"
    instance.vm.hostname = "dashboard"
    instance.vm.network "private_network", ip: "192.168.56.12"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "2048"
      pmv.cpus = 2
      pmv.name = "E2E_dashboard"
    end
  end

  config.vm.define "agent-ubuntu2204" do |instance|
    instance.vm.box = "ubuntu/bionic64"
    instance.vm.hostname = "agent-ubuntu2204"
    instance.vm.network "private_network", ip: "192.168.56.13"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "4096"
      pmv.cpus = 2
      pmv.name = "E2E_agent-ubuntu2204"
    end
  end

  config.vm.define "agent-debian" do |instance|
    instance.vm.box = "debian/buster64"
    instance.vm.hostname = "agent-debian"
    instance.vm.network "private_network", ip: "192.168.56.14"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "2048"
      pmv.cpus = 2
      pmv.name = "E2E_agent-debian"
    end
  end

  config.vm.define "agent-fedora" do |instance|
    instance.vm.box = "fedora/38-cloud-base"
    instance.vm.hostname = "agent-fedora"
    instance.vm.network "private_network", ip: "192.168.56.15"
    instance.vm.provider "virtualbox" do |pmv|
      pmv.memory = "2048"
      pmv.cpus = 2
      pmv.name = "E2E_agent-fedora"
    end
  end
end
```

**Comment by javiersanchz** [comment]
# Install environment

## Wazuh Indexers

<details>
  <summary>Initial configuration</summary>

**Comment by javiersanchz** [comment]
# :green_circle: Check 2. Use and activate a custom policy for any of them

## :green_circle: Wazuh agent - Ubuntu 22.04
I created a custom policy in `/var/ossec/ruleset/sca/custom_policy.yml` with the following content:
```
policy:
  id: "custom_policy"
  file: "custom_policy.yml"
  name: "Custom policy for SCA test."
  description: "Review whether SCA is working as expected"

checks:
  - id: 20000
    title: "File should contain expected line"
    description: "Check that test_file contains specific line"
    condition: all
    rules:
      - 'f:/home/vagrant/test_file -> Expected line'
```

This policy only has a check that ensure the `/home/vagrant/test_file` contains the text `Expected line`.

Then, I created a the `/home/vagrant/test_file` with the following content:

```
First line
Second line
Expected line
Forth line
```

**Comment by javiersanchz** [comment]
# Check 3. Disable an used policy and confirm it is not used anymore

## :green_circle: Wazuh agent-Debian

**Comment by javiersanchz** [comment]
# Check 4. Push SCA config through centralized config and check it applies properly

## Wazuh agent- Ubuntu 22.04

I created a new agent group through the UI called `debian_agents` and added the agent:

![image](https://github.com/wazuh/wazuh/assets/96108386/deff3da2-6202-41b4-af38-33fb6f3da04f)
![image](https://github.com/wazuh/wazuh/assets/96108386/23c374db-4dad-4ed5-a549-f03c4430ae28)
![image](https://github.com/wazuh/wazuh/assets/96108386/74559858-02be-486f-9ebc-7cdc072f8969)

**Comment by MarcelKemp** [comment]
There are a few typos that need to be corrected, but otherwise, LGTM!
> - `Wazuh WUI usando FQDN` -> `Wazuh WUI using FQDN`
> - `Restart de agent` -> `Restart the agent`
> Among other typos

And according to the last failure, after a test I was not able to replicate it (except in the case that there was no such file in the directory). But well, we will continue with the tests on the open issue:
- https://github.com/wazuh/wazuh/issues/18981

**Comment by MarcelKemp** [comment]
After verifying the problem with the following comment:
- https://github.com/wazuh/wazuh/issues/18981#issuecomment-1716180196

I consider that as it is a mistake of the tester, it should not be considered as a failure.
I change it to known issue :yellow_circle:, although it could be considered as working correctly :green_circle:.

**Comment by davidjiglesias** [comment]
Agents deployment was not done using FQDN.

macOS agent deployed with an incorrect architecture, as the deployment section mentioned using ARM.

Please, correct the typos mentioned by @MarcelKemp here: https://github.com/wazuh/wazuh/issues/18833#issuecomment-1716164054

**Comment by javiersanchz** [comment]
Corrected typographical errors!

**Comment by davidjiglesias** [comment]
LGTM!
