### ISSUE TITLE
Release 4.6.0 - Alpha 1 - WPK upgrade tests

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#18875]
The following issue aims to run `upgrade WPK tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## WPK upgrade tests information

|Main RC issue|Version|Release candidate|Tag|Previous issue|
|---|---|---|---|---|
|#18858|4.6.0|Alpha 1|https://github.com/wazuh/wazuh/tree/v4.6.0-alpha1|#18503|

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Tests

To evaluate this feature, it is necessary to test upgrading the agent and also the case when the upgrade fails (rollback). The `tree` command will be used to compare, before and after the upgrade/rollback process, and check that the presence, ownership and permissions of the files and directories are expected.

Wazuh versions to test (Upgrade to the current agent version):
### Linux

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----|------|---------------|------------------|
|CentOS 8|3.13.6| 🔴 | 🟡  |🔴 |
|CentOS 8|4.5.2 | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8|4.6.0 | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22|3.13.6|🔴| ⚪ Skipped |🔴| 
|Ubuntu 22|4.5.2 | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22|4.6.0 | :green_circle: | :green_circle: | :green_circle: |
|openSUSE Tumbleweed| 3.13.6 |⚪ Skipped| ⚪ Skipped|⚪ Skipped|
|openSUSE Tumbleweed| 4.5.2 | :green_circle: | :green_circle: | :green_circle: |
|openSUSE Tumbleweed| 4.6.0 | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2|3.13.6|⚪ Skipped|⚪ Skipped| ⚪ Skipped|
|Amazon Linux 2|4.5.2| :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2|4.6.0 | :green_circle: | :green_circle: | :green_circle: |

### Windows

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----|------|---------------|------------------|
|Server 2012 R2|3.13.6|⚪ Skipped| ⚪ Skipped | ⚪ Skipped | 
|Server 2012 R2|4.5.2| :green_circle: | :green_circle: | :green_circle: |  
|Server 2012 R2|4.6.0| :green_circle: | :green_circle: | :green_circle: |
|Windows 11|3.13.6|⚪ Skipped| ⚪ Skipped | ⚪ Skipped |
|Windows 11|4.5.2| :green_circle:|:green_circle:| :green_circle:|
|Windows 11|4.6.0| :green_circle:|:green_circle: | :green_circle:|
|Server 2022|3.13.6| :yellow_circle: | :yellow_circle: | :green_circle: |
|Server 2022|4.5.2| :green_circle: | :green_circle: | :green_circle: |
|Server 2022|4.6.0| :green_circle: | :green_circle: | :green_circle: |

### macOS

|OS|Version|Status|Upgrade fail|Upgrade OK|
|----|-----------|--------|-------|------------------|
| Ventura |4.5.2| :green_circle: | :green_circle: | :green_circle: |
| Ventura |4.6.0| :green_circle: | :green_circle: | :green_circle: |

## Findings

The 🟡 results when testing the upgrade failure from 3.13.6 to 4.6.0 are because of the same issue that has been already reported at https://github.com/wazuh/wazuh/issues/15587.

This is not a critical one, the rollback is working as expected but the manager doesn't receive the last ACK so the upgrade procedure gets stuck until the timeout is reached or the upgrade is interrupted.

## Conclusions

All tests have been executed and the results can be found here.

| **Status** | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴 | [CentOS 8 / RHEL 8 : Upgrade OK, From Wazuh-Agent 3.13.6](https://github.com/wazuh/wazuh/issues/18875#issuecomment-1712120748) |  | [New issue](https://github.com/wazuh/wazuh/issues/18965) |
| 🔴 | [Ubuntu 22 : Upgrade OK, From Wazuh-Agent 3.13.6](https://github.com/wazuh/wazuh/issues/18875#issuecomment-1712120748) |  | [New issue](https://github.com/wazuh/wazuh/issues/18965) |
| 🟡  | [Windows Server 2022 : Windows Server 2022, From Wazuh-Agent 3.13.6](https://github.com/wazuh/wazuh/issues/18875#issuecomment-1712050506) | | [Known Issue](https://github.com/wazuh/wazuh/issues/15587) |

## Test feedback

- Was the testing guideline clear? Were there any ambiguities?
  - There is not official guideline yet.
- Did you face any challenges not covered by the guideline?
  - There is not official guideline yet
- Suggestions for improvement.
   - It would be nice to have a guideline specifying exactly what and how it is expected to be tested in every particular case.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @vikman90
- [x] @davidjiglesias

**Comment by nmkoremblum** [comment]
# TEST: openSUSE Tumbleweed

## From Wazuh-Agent v4.5.2
###  UPGRADE FAIL :green_circle: 

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ (`chkconfig` unavailable)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] ~Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)~
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [ ] ~Restore SELinux policies (`semodule -l | grep -i wazuh`)~ (Disabled)

###  UPGRADE OK :green_circle: 

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**


## From Wazuh-Agent v4.6.0
###  UPGRADE FAIL

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] ~Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)~
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] ~Init file runs ossec-control (`cat /etc/rc.d/init.d/wazuh-agent`)~
- [ ] ~Wazuh as service is enabled `chkconfig --list`~ (`chkconfig` unavailable)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] ~Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/ossec-agentd.state`)~
- [x] Wazuh starts and connects automatically when the system is rebooted.
- [ ] ~Restore SELinux policies (`semodule -l | grep -i wazuh`)~ (Disabled)

###  UPGRADE OK

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**

**Comment by LucioDonda** [comment]
# TEST: Windows 11

## From Wazuh-Agent v4.5.2 🟢

### UPGRADE FAIL  🟢
- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**
[FailedCase452.zip](https://github.com/wazuh/wazuh/files/12561234/FailedCase452.zip)


### UPGRADE OK 🟢

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.4.0
- [x] The new SCA policy is added and executed

**Upgrade reports**
[SuccessCase452.zip](https://github.com/wazuh/wazuh/files/12561240/SuccessCase452.zip)


----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.6.0 

### UPGRADE FAIL  
- [ ] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [ ] After the rollback the agent connects to the manager
- [ ] After reboot, the Wazuh-Agent starts and connects to the manager.
- [ ] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [ ] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Upgrade reports**


### UPGRADE OK

- [ ] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [ ] Wazuh service is started and the agent is connected to the manager.
- [ ] The version shown in the control panel is 4.4.0
- [ ] The new SCA policy is added and executed

**Upgrade reports**

**Comment by nbertoldo** [comment]
# TEST: Windows Server 2022

## From Wazuh-Agent 3.13.6
###  UPGRADE FAIL: 🟡

- [x]  Wazuh-Agent folder tree: No files are lost after the rollback. The logs of the failed upgrade (ossec.log) are kept.
- [x]  After the rollback the agent connects to the manager
- [x]  After reboot, the Wazuh-Agent starts and connects to the manager.
- [x]  The correct Wazuh-Agent version is shown in the list of Windows' programs and features.
- [x]  A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

**Note** Found same strange behavior as:
https://github.com/wazuh/wazuh/issues/15529#issuecomment-1335136549

###  UPGRADE OK: 🟢 

- [x] Message Upgrade finished successfully. is shown in upgrade.log file.
- [x]  Wazuh service is started and the agent is connected to the manager.
- [x]  The version shown in the control panel is 4.6.0
- [x]  The new SCA policy is added and executed

**Upgrade reports**
[report_Windows_Server_2022_v3.13.6.zip](https://github.com/wazuh/wazuh/files/12561839/report_Windows_Server_2022_v3.13.6.zip)


## From Wazuh-Agent 4.5.2
###  UPGRADE FAIL: 🟢

- [x]  Wazuh-Agent folder tree: No files are lost after the rollback. The logs of the failed upgrade (ossec.log) are kept.
- [x]  After the rollback the agent connects to the manager
- [x]  After reboot, the Wazuh-Agent starts and connects to the manager.
- [x]  The correct Wazuh-Agent version is shown in the list of Windows' programs and features.
- [x]  A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

###  UPGRADE OK: 🟢

- [x] Message Upgrade finished successfully. is shown in upgrade.log file.
- [x]  Wazuh service is started and the agent is connected to the manager.
- [x]  The version shown in the control panel is 4.6.0
- [x]  The new SCA policy is added and executed

**Upgrade reports**
[report_Windows_Server_2022_v4.5.2.zip](https://github.com/wazuh/wazuh/files/12562309/report_Windows_Server_2022_v4.5.2.zip)


## From Wazuh-Agent 4.6.0
###  UPGRADE FAIL: 🟢

- [x]  Wazuh-Agent folder tree: No files are lost after the rollback. The logs of the failed upgrade (ossec.log) are kept.
- [x]  After the rollback the agent connects to the manager
- [x]  After reboot, the Wazuh-Agent starts and connects to the manager.
- [x]  The correct Wazuh-Agent version is shown in the list of Windows' programs and features.
- [x]  A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

###  UPGRADE OK: 🟢

- [x] Message Upgrade finished successfully. is shown in upgrade.log file.
- [x]  Wazuh service is started and the agent is connected to the manager.
- [x]  The version shown in the control panel is 4.6.0
- [x]  The new SCA policy is added and executed

**Upgrade reports**
[report_Windows_Server_2022_v4.6.0.zip](https://github.com/wazuh/wazuh/files/12562627/report_Windows_Server_2022_v4.6.0.zip)

**Comment by LucioDonda** [comment]
# TEST: CentOS 8 / RHEL 8

## From Wazuh-Agent 3.13.6
###  UPGRADE FAIL: 

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs ossec-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] Wazuh as service is enabled `chkconfig --list` (`chkconfig` unavailable)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (Disabled)

**Upgrade reports**


###  UPGRADE OK: 

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

**Upgrade reports**


----------------------------------------------------------------------------------------------------------



## From Wazuh-Agent 4.5.2
###  UPGRADE FAIL: 

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] Wazuh as service is enabled `chkconfig --list` (`chkconfig` unavailable)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (Disabled)

**Upgrade reports**


###  UPGRADE OK: 

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

**Upgrade reports**


----------------------------------------------------------------------------------------------------------


## From Wazuh-Agent 4.6.0
###  UPGRADE FAIL: 

- [ ] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [ ] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [ ] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [ ] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [ ] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [ ] Wazuh as service is enabled `chkconfig --list` (`chkconfig` unavailable)
- [ ] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [ ] Wazuh starts and connects automatically when the system is rebooted.
- [ ] Restore SELinux policies (`semodule -l | grep -i wazuh`) (Disabled)

**Upgrade reports**

###  UPGRADE OK: 

- [ ] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [ ] Service starts automatically after rebooting
- [ ] Agent connects to the manager after rebooting

**Upgrade reports**

**Comment by nbertoldo** [comment]
# TEST: Ubuntu 22

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.5.2
###  UPGRADE FAIL :green_circle: 

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/init.d/wazuh-agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

###  UPGRADE OK :green_circle: 

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**
[report_Ubuntu_22_v4.5.2.zip](https://github.com/wazuh/wazuh/files/12563727/report_Ubuntu_22_v4.5.2.zip)

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.6.0
###  UPGRADE FAIL :green_circle: 

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/init.d/wazuh-agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

###  UPGRADE OK :green_circle: 

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**
[report_Ubuntu_22_v4.6.0.zip](https://github.com/wazuh/wazuh/files/12563991/report_Ubuntu_22_v4.6.0.zip)

**Comment by LucioDonda** [comment]
**Centos 8 issue:**


**Upgrade Failed:**
In the failed case the scenario is very similar as in the previous upgrades, the manager side takes a long time to receive any confirmation from the agent, and in the agent side the process end as it should, with only a single difference, altough the service is running and the agent connected to the manager when checking the status it prints:
```
[root@vm-centos8 vagrant]# systemctl status wazuh-agent.service 
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2023-09-08 18:41:33 UTC; 14min ago
   CGroup: /system.slice/wazuh-agent.service
           ├─52208 /var/ossec/bin/ossec-execd
           ├─52220 /var/ossec/bin/ossec-agentd
           ├─52234 /var/ossec/bin/ossec-syscheckd
           ├─52249 /var/ossec/bin/ossec-logcollector
           └─52292 /var/ossec/bin/wazuh-modulesd

Sep 08 18:41:33 vm-centos8 systemd[1]: Failed to start Wazuh agent.
Sep 08 18:42:03 vm-centos8 groupadd[37609]: group added to /etc/group: name=ossec, GID=987
Sep 08 18:42:03 vm-centos8 groupadd[37609]: group added to /etc/gshadow: name=ossec
Sep 08 18:42:03 vm-centos8 groupadd[37609]: new group: name=ossec, GID=987
Sep 08 18:42:04 vm-centos8 useradd[37619]: new user: name=ossec, UID=991, GID=987, home=/var/ossec, shell=/sbin/nolog>
Sep 08 18:42:04 vm-centos8 useradd[37619]: add 'ossec' to group 'ossec'
Sep 08 18:42:04 vm-centos8 useradd[37619]: add 'ossec' to shadow group 'ossec'
Sep 08 18:42:16 vm-centos8 userdel[52078]: delete user 'wazuh'
Sep 08 18:42:16 vm-centos8 userdel[52078]: removed group 'wazuh' owned by 'wazuh'
Sep 08 18:42:16 vm-centos8 userdel[52078]: removed shadow group 'wazuh' owned by 'wazuh'
```
```
[root@vm-centos8 vagrant]# journalctl -xe
Sep 08 18:42:04 vm-centos8 useradd[37619]: add 'ossec' to shadow group 'ossec'
Sep 08 18:42:16 vm-centos8 userdel[52078]: delete user 'wazuh'
Sep 08 18:42:16 vm-centos8 userdel[52078]: removed group 'wazuh' owned by 'wazuh'
Sep 08 18:42:16 vm-centos8 userdel[52078]: removed shadow group 'wazuh' owned by 'wazuh'
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  Converting 760 SID table entries...
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability network_peer_controls=1
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability open_perms=1
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability extended_socket_class=1
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability always_check_network=0
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability cgroup_seclabel=1
Sep 08 18:42:47 vm-centos8 kernel: SELinux:  policy capability nnp_nosuid_transition=1
Sep 08 18:42:47 vm-centos8 dbus-daemon[671]: [system] Reloaded configuration
Sep 08 18:43:06 vm-centos8 chronyd[4379]: Selected source 168.96.251.195 (2.centos.pool.ntp.org)
Sep 08 18:43:06 vm-centos8 chronyd[4379]: System clock wrong by 234.670745 seconds
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  Converting 760 SID table entries...
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability network_peer_controls=1
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability open_perms=1
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability extended_socket_class=1
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability always_check_network=0
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability cgroup_seclabel=1
Sep 08 18:43:18 vm-centos8 kernel: SELinux:  policy capability nnp_nosuid_transition=1
Sep 08 18:43:18 vm-centos8 dbus-daemon[671]: [system] Reloaded configuration
Sep 08 18:43:18 vm-centos8 systemd[1]: Reloading.
Sep 08 18:43:18 vm-centos8 systemd[1]: Reloading.
Sep 08 18:43:18 vm-centos8 systemd[1]: Reloading.
Sep 08 18:43:18 vm-centos8 systemd[1]: Reloading.
Sep 08 18:48:29 vm-centos8 chronyd[4379]: Selected source 162.159.200.123 (2.centos.pool.ntp.org)
Sep 08 19:01:01 vm-centos8 CROND[52770]: (root) CMD (run-parts /etc/cron.hourly)
Sep 08 19:01:01 vm-centos8 run-parts[52773]: (/etc/cron.hourly) starting 0anacron
Sep 08 19:01:01 vm-centos8 anacron[52781]: Anacron started on 2023-09-08
Sep 08 19:01:01 vm-centos8 anacron[52781]: Will run job `cron.daily' in 27 min.
Sep 08 19:01:01 vm-centos8 anacron[52781]: Will run job `cron.weekly' in 47 min.
Sep 08 19:01:01 vm-centos8 anacron[52781]: Will run job `cron.monthly' in 67 min.
Sep 08 19:01:01 vm-centos8 anacron[52781]: Jobs will be executed sequentially
Sep 08 19:01:01 vm-centos8 run-parts[52783]: (/etc/cron.hourly) finished 0anacron

```
**Upgrade OK:**

In this case the process is exactly the same, (being done with the same wpk file that was used in the other versions tests).
The ack is never received and also the agent doesn't gets updated.
The process continues with the agent still being connected without any problem beside what was named above, the status of the service says failed.

**Comment by nmkoremblum** [comment]
# TEST: Amazon Linux 2

## From Wazuh-Agent 4.5.2

###  UPGRADE FAIL: :green_circle:

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

**Note** comment:
If some comment

###  UPGRADE OK: :green_circle:

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**

[test_logs_4_5_2.zip](https://github.com/wazuh/wazuh/files/12572272/test_logs_4_5_2.zip)

## From Wazuh-Agent 4.6.0

###  UPGRADE FAIL: :green_circle:

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/`
  - `/var`
  - `/usr`, `/usr/lib/`, `/usr/lib/systemd/`, `/usr/lib/systemd/system/`
  - `/etc`, `/etc/systemd/`, `/etc/systemd/system/`, `/etc/rc.d`, `/etc/initd.d/`, `/etc/initd.d/rc.d/`
- [x] Wazuh service runs wazuh-control (`systemctl cat wazuh-agent.service`)
- [x] The service was enabled (`systemctl is-enabled wazuh-agent.service`)
- [x] Init file runs wazuh-control (`cat /etc/rc.d/init.d/wazuh-agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

###  UPGRADE OK: :green_circle:

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**

[test_logs_4_6_0.zip](https://github.com/wazuh/wazuh/files/12572274/test_logs_4_6_0.zip)

**Comment by nmkoremblum** [comment]
# TEST: macOS Ventura (13.5)

## From Wazuh-Agent 4.5.2
###  UPGRADE FAIL: :green_circle:

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/Library/LaunchDaemons/` `/Library/StartupItems/` `/Library/StartupItems/WAZUH/` `/Library/LaunchDaemons/` 
- [x] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

###  UPGRADE OK: :green_circle:

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**

[tests_results_4_5_2.zip](https://github.com/wazuh/wazuh/files/12573129/tests_results_4_5_2.zip)

---

## From Wazuh-Agent 4.6.0
###  UPGRADE FAIL: :green_circle:

- [x] The wazuh home backup is restored correctly (no traces of the installation, but only the `.tar.gz` backup and the logs).
- [x] The permissions and owners of the following directories did NOT change:
  - `/Library/LaunchDaemons/` `/Library/StartupItems/` `/Library/StartupItems/WAZUH/` `/Library/LaunchDaemons/` 
- [x] Wazuh service is enabled and active (`launchctl print system/com.wazuh.agent`)
- [x] Wazuh starts and connects when the backup is restored (`cat /var/ossec/var/run/wazuh-agentd.state`)
- [x] Wazuh starts and connects automatically when the system is rebooted.

###  UPGRADE OK: :green_circle:

- [x] Upgrade is performed successfully (agent connects to the manager after upgrading)
- [x] Service starts automatically after rebooting
- [x] Agent connects to the manager after rebooting

**Upgrade reports**

[tests_results_4_6_0.zip](https://github.com/wazuh/wazuh/files/12573131/tests_results_4_6_0.zip)

**Comment by nbertoldo** [comment]
# TEST: Windows Server 2012 R2

## From Wazuh-Agent v4.5.2 🟢

### UPGRADE FAIL  🟢
- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK 🟢

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.6.0
- [x] The new SCA policy is added and executed

**Upgrade reports**
[report_WindowsServer_2012_v4.5.2.zip](https://github.com/wazuh/wazuh/files/12577627/report_WindowsServer_2012_v4.5.2.zip)

----------------------------------------------------------------------------------------------------------

## From Wazuh-Agent v4.6.0 🟢

### UPGRADE FAIL  🟢
- [x] Wazuh-Agent folder tree:  No files are lost after the rollback. The logs of the failed upgrade (`ossec.log`) are kept.
- [x] After the rollback the agent connects to the manager
- [x] After reboot, the Wazuh-Agent starts and connects to the manager.
- [x] The correct Wazuh-Agent version is shown in the list of Windows' `programs and features`.
- [x] A new version of Wazuh-Agent can be manually installed via MSI after the rollback process.

### UPGRADE OK 🟢

- [x] Message `Upgrade finished successfully.` is shown in `upgrade.log` file.
- [x] Wazuh service is started and the agent is connected to the manager.
- [x] The version shown in the control panel is 4.6.0
- [x] The new SCA policy is added and executed

**Upgrade reports**
[report_WindowsServer_2012_v4.6.0.zip](https://github.com/wazuh/wazuh/files/12578225/report_WindowsServer_2012_v4.6.0.zip)

**Comment by davidjiglesias** [comment]
LGTM!
