### ISSUE TITLE
Release 4.6.0 - Alpha 1 - External Integration Modules 

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#18879]
The following issue aims to perform all the required testing for the current release candidate to ensure the modules (AWS, GCP, Azure, DockerListener and Shuffle) works as expected, report the results, and open new issues for any encountered errors.

## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #18858    |
| **Version**                      | 4.6.0 |
| **Release candidate #**          | Alpha 1   |
| **Tag**                          | [v4.6.0-alpha1](https://github.com/wazuh/wazuh/tree/v4.6.0-alpha1) |
| **Previous modules tests issue** |  https://github.com/wazuh/wazuh/issues/18295   |

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                                        |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | The test passed successfully. 										    |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

The resulting logs for the tests must be included in the status report so it can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

| **Module**      |  **Status**  |**Notes**|
|-----------------|-------------|---------|
| AWS             | 🟡 |  One of the integration test cases was marked as XFAIL. Related issue: https://github.com/wazuh/wazuh/issues/16303  |
| Azure           | 🟢 |  -  |
| GCP             | 🟡  | The configuration displayed in the documentation required some changes to work. Related issue: https://github.com/wazuh/wazuh-documentation/issues/5699. Moreover, when creating a new service account I couldn't access Pub/sub nor buckets, I had to create the credentials in an existing one, related issue: https://github.com/wazuh/wazuh-documentation/issues/4996  |
| Docker Listener | :white_circle: | Skipped  |
| Shuffle | :white_circle: | Skipped  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [x] @davidjiglesias
- [x] @Selutario

**Comment by GGP1** [comment]
# AWS Test results

A test is considered valid if the following conditions are met:

- The expected result described in the test itself is met.
- The expected amount of events were sent to `analysisd`.
- The expected output was present in the `{wazuh_path}/logs/ossec.log` file.

The data available in our Wazuh-dev environment for each of these supported services will be used. Additional logs may be created if they are necessary or there is insufficient data for testing.

## Test results

| Bucket/Service type            | Status                  | Issue ref. |
|--------------------------------|-------------------------|------------|
| Test using ossec.conf in a manager |   | -          |
| Test using ossec.conf in an agent (Python 3.7)   |   | -          |

## Test using ossec.conf in a manager

<details>
    <summary>Configuration</summary>

    <wodle name="aws-s3">
        <disabled>no</disabled>
        <remove_from_bucket>no</remove_from_bucket>
        <interval>10m</interval>
        <run_on_start>yes</run_on_start>
        <skip_on_error>no</skip_on_error>

        <bucket type="cloudtrail">
            <aws_profile>dev</aws_profile>
            <name>wazuh-aws-wodle-cloudtrail</name>
            <only_logs_after>2022-MAR-21</only_logs_after>
        </bucket>

        <bucket type="custom">
            <aws_profile>dev</aws_profile>
            <name>wazuh-aws-wodle-macie</name>
            <only_logs_after>2022-JAN-01</only_logs_after>
        </bucket>

        <service type="cloudwatchlogs">
            <aws_profile>dev</aws_profile>
            <aws_log_groups>4_4_test</aws_log_groups>
            <only_logs_after>2022-DEC-01</only_logs_after>
            <regions>us-east-1</regions>
        </service>
    </wodle>
</details>

<details><summary>Output</summary>

```console

```
    
</details>


#### Conclusions



## Test using ossec.conf in an agent

Deploy a CentOS 8 agent and install the required dependencies described in the official Wazuh documentation, then run the module adding the following configuration to the `ossec.conf` using Python 3.6:

<details>
    <summary>Configuration</summary>

```xml
<wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="cloudtrail">
        <name>wazuh-aws-wodle-cloudtrail</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2023-APR-01</only_logs_after>
    </bucket>

    <bucket type="config">
        <name>wazuh-aws-wodle-config</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2022-NOV-01</only_logs_after>
    </bucket>

    <bucket type="alb">
        <name>wazuh-aws-wodle-alb</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2023-FEB-01</only_logs_after>
    </bucket>

    <bucket type="clb">
        <name>wazuh-aws-wodle-clb</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="nlb">
        <name>wazuh-aws-wodle-nlb</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="guardduty">
        <name>wazuh-aws-wodle-guardduty</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="waf">
        <name>wazuh-aws-wodle-waf</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="server_access">
        <name>wazuh-aws-wodle-access</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="cisco_umbrella">
        <name>wazuh-aws-wodle-umbrella</name>
        <aws_profile>dev</aws_profile>
        <path>XXXXXXXXX/dnslogs</path>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="cisco_umbrella">
        <name>wazuh-aws-wodle-umbrella</name>
        <aws_profile>dev</aws_profile>
        <path>XXXXXXXXX/iplogs</path>
        <only_logs_after>2022-FEB-01</only_logs_after>
    </bucket>

    <bucket type="cisco_umbrella">
        <name>wazuh-aws-wodle-umbrella</name>
        <aws_profile>dev</aws_profile>
        <path>XXXXXXXXX/proxylogs</path>
        <only_logs_after>2021-DEC-01</only_logs_after>
    </bucket>

    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-kms</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-macie</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-trusted-advisor</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <service type="cloudwatchlogs">
        <aws_profile>dev</aws_profile>
        <aws_log_groups>4_5_test</aws_log_groups>
        <only_logs_after>2022-JAN-01</only_logs_after>
        <regions>us-east-1</regions>
    </service>

    <subscriber type="security_lake">
        <sqs_name>AmazonSecurityLake-f38b8aff-Main-Queue</sqs_name>
        <external_id>wazuh-external-id</external_id>
        <iam_role_arn>AmazonSecurityLake-f38b8aff-Main-Queue</iam_role_arn>
    </subscriber>

</wodle>
```
</details>

<details><summary>Output</summary>

```console

```
   
</details>


#### Conclusions

**Comment by GGP1** [comment]
# Test Security Lake as a subscriber integration :green_circle: 

- Set up the Security Lake Service with a Subscriber in order to fetch notifications from an SQS Queue and get logs in parquet format from related buckets.


<details><summary>ossec.conf</summary>

    <wodle name="aws-s3">
        <disabled>no</disabled>
        <interval>1h</interval>
        <run_on_start>yes</run_on_start>
        <subscriber type="security_lake">
            <sqs_name>AmazonSecurityLake-f38b8aff-Main-Queue</sqs_name>
            <external_id>wazuh-external-id</external_id>
            <iam_role_arn>arn:aws:iam::xxx:role/AmazonSecurityLake-f38b8aff-Main-Queue</iam_role_arn>
        </subscriber>
    </wodle>

</details>

<details><summary>ossec.log</summary>

```console
root@ip-172-31-24-105:/var/ossec/etc# /var/ossec/wodles/aws/aws-s3 --subscriber security_lake --queue AmazonSecurityLake-f38b8aff-Main-Queue --external_id wazuh-external-id --iam_role_arn arn:aws:iam::xxx:role/AmazonSecurityLake-f38b8aff-Main-Queue --debug 2
2023/09/07 15:56:45 wazuh-modulesd:aws-s3[53416] wm_aws.c:62 at wm_aws_main(): INFO: Module AWS started
2023/09/07 15:56:45 wazuh-modulesd:aws-s3[53416] wm_aws.c:84 at wm_aws_main(): INFO: Starting fetching of logs.
2023/09/07 15:56:45 wazuh-modulesd:aws-s3[53416] wm_aws.c:196 at wm_aws_main(): INFO: Executing Subscriber fetch: (Type and SQS: security_lake AmazonSecurityLake-f38b8aff-Main-Queue
...
DEBUG: Found 6 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/d2c537ab2c6c2a49249340f5dd84eadc.gz.parquet
DEBUG: 6 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/00c537bd7c92b42b07699676378bc696.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 8 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/00c537bd7c92b42b07699676378bc696.gz.parquet
DEBUG: 8 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/eec537c211fe467b5604dc3816c9ba62.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 5 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/eec537c211fe467b5604dc3816c9ba62.gz.parquet
DEBUG: 5 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=567970947422/eventDay=20230907/3ac537cb38829d6c17ee17cf3432dad8.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 5 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/3ac537cb38829d6c17ee17cf3432dad8.gz.parquet
DEBUG: 5 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/64c537cfce6e642cfb34710a7a280005.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 1 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/64c537cfce6e642cfb34710a7a280005.gz.parquet
DEBUG: 1 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/66c537d8f4350fc56267f26e040e5b26.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 10 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/66c537d8f4350fc56267f26e040e5b26.gz.parquet
DEBUG: 10 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/68c537dd88d3a520160a713354c7da66.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 1 events in file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/68c537dd88d3a520160a713354c7da66.gz.parquet
DEBUG: 1 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/a8c537e46403a5033155ccddbd6ac4e1.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 7 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/a8c537e46403a5033155ccddbd6ac4e1.gz.parquet
DEBUG: 7 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/c6c537ed8cbc208e40640ebb41670387.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 2 events in file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/c6c537ed8cbc208e40640ebb41670387.gz.parquet
DEBUG: 2 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/aac537efda264290082baf27073176e7.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 9 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/aac537efda264290082baf27073176e7.gz.parquet
DEBUG: 9 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Retrieving messages from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/18c537f46bdc5a9c766e4054804951e9.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 8 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/18c537f46bdc5a9c766e4054804951e9.gz.parquet
DEBUG: 8 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
DEBUG: Processing file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/3cc537fd9322049ed16bd9e5c8d578c8.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
DEBUG: Found 1 events in file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=xxx/eventDay=20230907/3cc537fd9322049ed16bd9e5c8d578c8.gz.parquet
DEBUG: 1 events sent to Analysisd
DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
...
2023/09/07 16:02:30 wazuh-modulesd:aws-s3[53416] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.
2023/09/07 16:02:30 wazuh-modulesd:aws-s3[53416] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2023/09/07 16:56:45
```


</details>

### Conclusions

The module worked as expected, the sum of the events described in the logs corresponds to the ones sent to Analysisd.

**Comment by GGP1** [comment]
# GCP Test results

No data must be modified or removed unless it was specified for the test.

The tests assume there is a valid authentication file located at `/var/ossec/wodles/gcloud/credentials.json`.

A test is considered valid if the following conditions are met:

- The expected result described in the test itself is met.
- The expected amount of events were sent to `analysisd`.
- The expected output was present in the `{wazuh_path}/logs/ossec.log` file.

## Test results

| Bucket/Service type            | Status                  | Issue ref. |
|--------------------------------|-------------------------|------------|
| Test using ossec.conf in a manager |   | -          |
| Test using ossec.conf in a agent (Python 3.7)   |   | -          |

## Environment details

To test Pub/Sub integration we developed a script able to publish any number of messages in the testing topic so we can ensure there always will be data available for the tests. This was required because of how Pub/Sub is designed as the messages are consumed once they are pulled.


## Test using ossec.conf in a manager

Run the module using the following `ossec.conf` configuration:

<details><summary>ossec.conf</summary>
```xml
<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1d</interval>
    <project_id>wazuh-dev-123456</project_id>
    <subscription_name>wazuh-framework-subscription</subscription_name>
    <num_threads>4</num_threads>
    <logging>info</logging>
    <max_messages>50</max_messages>
    <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
</gcp-pubsub>

<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1d</interval>
    <logging>info</logging>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
    </bucket>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
        <only_logs_after>2022-Jul-01</only_logs_after>
        <path>test_prefix</path>
    </bucket>
</gcp-bucket>
```
</details>

<details>
    <summary>Ossec.log output</summary>

```console

```

### Conclusions
The module worked as expected, 50 events were sent to `analysisd`.


## Test using ossec.conf in an agent with Python 3.6 

Run the module using the following `ossec.conf` configuration:

<details><summary>ossec.conf</summary>

```xml
<gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1d</interval>
    <project_id>wazuh-dev-123456</project_id>
    <subscription_name>wazuh-framework-subscription</subscription_name>
    <num_threads>4</num_threads>
    <logging>info</logging>
    <max_messages>50</max_messages>
    <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
</gcp-pubsub>

<gcp-bucket>
    <run_on_start>yes</run_on_start>
    <interval>1d</interval>
    <logging>info</logging>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
    </bucket>
    <bucket type="access_logs">
        <name>framework-test-bucket</name>
        <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
        <only_logs_after>2022-Jul-01</only_logs_after>
        <path>test_prefix</path>
    </bucket>
</gcp-bucket>
```

</details>

<details>
    <summary>Ossec.log output</summary>

```console

```

</details>

### Conclusions
The module worked as expected, 50 events were sent to `analysisd`.

**Comment by GGP1** [comment]
# Azure Test results

The following tests must be performed in sequential order. No data must be modified or removed unless it was specified for the test. 

The tests assume there is a valid authentication file located at `{wazuh_path}/wodles/azure/credentials`.

A test is considered valid if the following conditions are met:

- The expected result described in the test itself is met.
- The expected amount of events were sent to `analysisd`.
- The expected output was present in the `{wazuh_path}/logs/azure-logs.log` file.

## Test results

| Bucket/Service type            | Status                  | Issue ref. |
|--------------------------------|-------------------------|------------|
| Test using ossec.conf in a manager |   | -          |
| Test using ossec.conf in a agent (Python 3.7)   |   | -          |

## Test using ossec.conf in a manager

Remove the database file and run the module using the following configuration. Check the output and the database status.

<details><summary>ossec.conf</summary>

```xml

```

</details>


<details><summary>ossec.log output</summary>

```console

```

</details>


<details><summary>database status after the test</summary>
    
```console

```

</details>

#### Conclusions

## Test using ossec.conf in a agent with Python 3.6

Remove the database file and run the module using the following configuration. Check the output and the database status.

<details><summary>ossec.conf</summary>

```xml

```

</details>


<details><summary>ossec.log output</summary>

```console

```

</details>


<details><summary>database status after the test</summary>

```console

```

</details>

#### Conclusions

**Comment by davidjiglesias** [comment]
LGTM!
