### ISSUE TITLE
Improve field order of the settings/Custom Branding Dashboard section

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#18899]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | installation | Manager/Indexer/Dashboard | Packages/Sources | Rocky Linux V8 |

I used the Dashboard settings section to customize the Dashboard and the PDF report logos and texts.

The order of the fields in the user interface could be improved. The current field order is shown in the following screenshot:

![image](https://github.com/wazuh/wazuh/assets/2949519/9d4ed468-9563-436e-bdeb-dde004f27f25)

### Suggested order could be:

1. App main logo
2. Healthcheck log
3. Navigation drawer logo
4. PDF report logo
5. Report header (**NOTE**: This title should be Report header in singular)
6. Reports footer (**NOTE**: This title should be Report footer in singular)

**Comment by gdiazlo** [comment]
This is ordered alphabetically by the setting name. The order is not hard-coded. We might work in the feature in the future.
