### ISSUE TITLE
Rule 83201 generating false positives

### ISSUE THREAD

**Issue by whizoun** [wazuh/wazuh#189]
Hi,

The rule 83201 (from 0435-ms_logs_rules.xml) is generating false positives on our platform, as it appears to be detecting Windows events 1040 and 1042 as if they were event 104.

Please, can you have a look at it?

These are the events that have triggered the rule, edited to remove sensitive information:

2017 Sep 13 07:51:01 WinEvtLog: Application: INFORMATION(**1040**): MsiInstaller: username: DOMAIN: hostname: \\path_to_some_msi_file 3600 (NULL) (NULL) (NULL) (NULL)  

2017 Sep 13 07:47:16 WinEvtLog: Application: INFORMATION(**1042**): MsiInstaller: SYSTEM: NT AUTHORITY: hostname: \\path_to_some_msi_file 2448 (NULL) (NULL) (NULL) (NULL)

thank you
regards

**Comment by vikman90** [comment]
Hi @whizoun,

there was indeed a problem when comparing the event ID. I have just fixed it in the ruleset repository: https://github.com/wazuh/wazuh-ruleset/commit/44f80be3ee9bffab10e5cd23cf98cd9a55542dca

We'll make it available on the next release.

Thank you very much for reporting!
Best regards.

**Comment by whizoun** [comment]
Thanks for your quick reply.

Best regards.
