### ISSUE TITLE
Add support for Amazon Linux 1, and Amazon Linux 2023 in dist-detect.sh

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#18905]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | dist-detect | dist-detect | Unattended | Amazon Linux 2023 |

We need to add support to Amazon Linux 2023 in dist-detect.sh script:

https://github.com/wazuh/wazuh/blob/17469f88206a90e54e0d5f6ee81a0a04996ada1f/src/init/dist-detect.sh#L24

## Subtasks

- https://github.com/wazuh/wazuh-packages/issues/2612
- https://github.com/wazuh/internal-devel-requests/issues/489

**Comment by vikman90** [comment]
We've decided that neither this task nor https://github.com/wazuh/wazuh-packages/issues/2430 should target 4.6.0.

**Comment by JorgeMarinoDev** [comment]
Since this must be a coordinated merge process, a new issue in CICD was created https://github.com/wazuh/internal-devel-requests/issues/489.
Branch contains the necessary changes.

**Comment by nmkoremblum** [comment]
This issue is set "on hold" in favor of https://github.com/wazuh/wazuh/issues/21385 which has a higher priority
