### ISSUE TITLE
AWS wodle shows abnormal behavior with the number of generated alerts

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#18901]
|Wazuh version|Component|
|---|---|
| 4.6.0 | wazuh-aws-wodle |

## Description

During the analysis of the issue https://github.com/wazuh/wazuh/issues/18843 an error was found when the Wazuh manager master nodes started showing errors due to lack of space, with up to 16GiB of alerts

```
[root@wazuh-manager-master-0 wazuh-user]# du -sh /var/ossec/logs/alerts
16G /var/ossec/logs/alerts
```

Performing an analysis, @vcerenu has detected that too many alerts like the following are being registered:

```
{"timestamp":"2023-09-08T17:43:00.769+0000","rule":{"level":3,"description":"AWS VPC Flow: [ACCEPT] - Interface: eni-xxx - Protocol : 6.","id":"80401","firedtimes":1078390,"mail":false,"groups":["amazon","aws","aws_vpcflow"]},"agent":{" id":"000","name":"wazuh-manager-master-0"},"manager":{"name":"wazuh-manager-master-0"},"id":"1694194980.9868307968", "cluster":{"name":"wazuh1","node":"master"},"decoder":{"name":"json"},"data":{"integration":"aws"," aws":{"log_info":{"log_file":"vpc/AWSLogs/xxxx/vpcflowlogs/us-west-1/2020/12/22/166157441623_vpcflowlogs_us-west-1_fl-04d16c61b3339cdf6_202031222T 35Z_7b747144.log.gz","s3bucket" :"wazuh-aws-wodle"},"version":"2","account_id":"xxxx","interface_id":"eni-xxxx","srcaddr":"10.0.1.34","dstaddr": "xxxx","srcport":"22","dstport":"47916","protocol":"6","packets":"18","bytes":"5241","start": "2020-12-22T13:35:47Z","end":"2020-12-22T13:36:47Z","action":"ACCEPT","log_status":"OK","source":"vpc ","aws_account_id":"xxxx"}},"location":"Wazuh-AWS"}
```

This is confirmed by looking at the alerts in the WUI as there are `13,371,724` alerts from `wazuh-aws-wodle` out of a total of `13,402,731`. These are too many alerts for an environment of a day and a half, plus @teddytpc1 has commented that this does not happen in the 4.5.2 demo environment

It is necessary to investigate why so many alerts are being generated in such a short period of time for said integration.

**Comment by nico-stefani** [comment]
# Issue Update

I was analyzing the configured integrations in the demo environment and I found that the `vpcflow` one is iterating twice over each log file. This is because there are defined two `FlowLogs` and the module isn't filtered by the id in the filename.

```
root@wazuh-master:/var/ossec# wodles/aws/aws-s3 -t vpcflow -b wazuh-aws-wodle -l vpc -p prod -d 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Working on XXXXXXXXXXX - us-east-1
DEBUG: +++ Working on XXXXXXXXXXX - us-east-2
DEBUG: +++ Working on XXXXXXXXXXX - us-west-1
DEBUG: +++ Marker: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1910Z_73001e30.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1915Z_55aba566.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1915Z_b36607b1.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1920Z_49015d6e.log.gz
DEBUG: +++ DB Maintenance
DEBUG: +++ Marker: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1910Z_73001e30.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1915Z_55aba566.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1915Z_b36607b1.log.gz
DEBUG: ++ Found new log: vpc/AWSLogs/XXXXXXXXXXX/vpcflowlogs/us-west-1/2023/09/11/XXXXXXXXXXX_vpcflowlogs_us-west-1_fl-0bb6085e*****_20230911T1920Z_49015d6e.log.gz
DEBUG: +++ DB Maintenance
```

<details><summary>Configured FlowLogs</summary>
<p>

```json
{
    "FlowLogs": [
        {
            "CreationTime": "2023-09-06T13:33:07.035000+00:00",
            "DeliverLogsStatus": "SUCCESS",
            "FlowLogId": "fl-0281479749*****",
            "FlowLogStatus": "ACTIVE",
            "ResourceId": "eni-062665ce*****",
            "TrafficType": "ALL",
            "LogDestinationType": "s3",
            "LogDestination": "arn:aws:s3:::wazuh-aws-wodle/vpc",
            "LogFormat": "${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}",
            "Tags": [
                {
                    "Key": "wazuh_monitoring_version",
                    "Value": "4.5.2"
                },
                {
                    "Key": "service_name",
                    "Value": "demo-environment"
                },
                {
                    "Key": "team",
                    "Value": "DevOps"
                }
            ],
            "MaxAggregationInterval": 600,
            "DestinationOptions": {
                "FileFormat": "plain-text",
                "HiveCompatiblePartitions": false,
                "PerHourPartition": false
            }
        },
        {
            "CreationTime": "2023-09-07T13:00:07.187000+00:00",
            "DeliverLogsStatus": "SUCCESS",
            "FlowLogId": "fl-0bb6085e*****",
            "FlowLogStatus": "ACTIVE",
            "ResourceId": "eni-0babba88b******",
            "TrafficType": "ALL",
            "LogDestinationType": "s3",
            "LogDestination": "arn:aws:s3:::wazuh-aws-wodle/vpc",
            "LogFormat": "${version} ${account-id} ${interface-id} ${srcaddr} ${dstaddr} ${srcport} ${dstport} ${protocol} ${packets} ${bytes} ${start} ${end} ${action} ${log-status}",
            "Tags": [
                {
                    "Key": "wazuh_monitoring_version",
                    "Value": "4.6.0"
                },
                {
                    "Key": "service_name",
                    "Value": "demo-environment"
                },
                {
                    "Key": "team",
                    "Value": "DevOps"
                }
            ],
            "MaxAggregationInterval": 600,
            "DestinationOptions": {
                "FileFormat": "plain-text",
                "HiveCompatiblePartitions": false,
                "PerHourPartition": false
            }
        }
    ]
}
```

</p>
</details> 

I will continue investigating to determine if this is new in 4.6 or if present in older versions.

**Comment by nico-stefani** [comment]
# Issue Update

I can confirm the abnormal behavior was introduced in #16721. I will continue with the fix.

**Comment by nico-stefani** [comment]
# Issue Update

I was working on the solution. Still I need to perform some test before open the PR.

**Comment by nico-stefani** [comment]
# Issue Update

I propose a solution for skip log files that don't present the `flowlog_id` in the filename.

For future releases, we need to discuss if makes sense to keep the reference of `flow_log_id` or if just we can process the files in a bucket like the other types.

https://github.com/wazuh/wazuh/blob/59b883f3f75414dde85fa2e046b1cfdfe6292029/wodles/aws/aws_s3.py#L1794-L1800

**Comment by nico-stefani** [comment]
# Issue Update

Checking the processed events by the configured AWS integrations on the demo environment, we found that for `cloudtrail` one there are differences between rules matching compared with `4.5.2`. This is generating more alerts in the `alerts.json`.

The event in question

```json
{"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}
```

The log test for `4.5.2`

```
root@wazuh:/var/ossec# bin/wazuh-logtest
Starting wazuh-logtest v4.5.2
Type one log per line

{"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}

**Phase 1: Completed pre-decoding.

**Phase 2: Completed decoding.
        name: 'json'
        aws.awsRegion: 'us-west-1'
        aws.aws_account_id: 'XXXXXXXXXXX'
        aws.eventCategory: 'Management'
        aws.eventID: '99493820-0d91-4c9d-978a-342d4af8fe03'
        aws.eventName: 'ListGroups'
        aws.eventSource: 'resource-groups.amazonaws.com'
        aws.eventTime: '2023-09-15T01:07:49Z'
        aws.eventType: 'AwsApiCall'
        aws.eventVersion: '1.08'
        aws.log_info.log_file: 'AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz'
        aws.log_info.s3bucket: 'wazuh-aws-wodle'
        aws.managementEvent: 'true'
        aws.readOnly: 'true'
        aws.recipientAccountId: 'XXXXXXXXXXX'
        aws.requestID: 'bacd8338-2f8f-4ebb-afbc-71379c7fc15e'
        aws.source: 'cloudtrail'
        aws.sourceIPAddress: 'ssm.amazonaws.com'
        aws.userAgent: 'ssm.amazonaws.com'
        aws.userIdentity.accessKeyId: 'ASIASNL6BL*********'
        aws.userIdentity.accountId: 'XXXXXXXXXXX'
        aws.userIdentity.arn: 'arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory'
        aws.userIdentity.invokedBy: 'ssm.amazonaws.com'
        aws.userIdentity.principalId: 'AROASNL6BLJL*********:SSMInventory'
        aws.userIdentity.sessionContext.attributes.creationDate: '2023-09-15T01:07:49Z'
        aws.userIdentity.sessionContext.attributes.mfaAuthenticated: 'false'
        aws.userIdentity.sessionContext.sessionIssuer.accountId: 'XXXXXXXXXXX'
        aws.userIdentity.sessionContext.sessionIssuer.arn: 'arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
        aws.userIdentity.sessionContext.sessionIssuer.principalId: 'AROASNL6BLJL*********'
        aws.userIdentity.sessionContext.sessionIssuer.type: 'Role'
        aws.userIdentity.sessionContext.sessionIssuer.userName: 'AWSServiceRoleForAmazonSSM'
        aws.userIdentity.type: 'AssumedRole'
        integration: 'aws'

**Phase 3: Completed filtering (rules).
        id: '80200'
        level: '0'
        description: 'AWS alert.'
        groups: '['amazon', 'aws']'
        firedtimes: '1'
        mail: 'False'
```

The log test for `4.6.0`

```
root@wazuh-master:/var/ossec# bin/wazuh-logtest
Starting wazuh-logtest v4.6.0
Type one log per line

{"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}

**Phase 1: Completed pre-decoding.

**Phase 2: Completed decoding.
        name: 'json'
        aws.awsRegion: 'us-west-1'
        aws.aws_account_id: 'XXXXXXXXXXX'
        aws.eventCategory: 'Management'
        aws.eventID: '99493820-0d91-4c9d-978a-342d4af8fe03'
        aws.eventName: 'ListGroups'
        aws.eventSource: 'resource-groups.amazonaws.com'
        aws.eventTime: '2023-09-15T01:07:49Z'
        aws.eventType: 'AwsApiCall'
        aws.eventVersion: '1.08'
        aws.log_info.log_file: 'AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz'
        aws.log_info.s3bucket: 'wazuh-aws-wodle'
        aws.managementEvent: 'true'
        aws.readOnly: 'true'
        aws.recipientAccountId: 'XXXXXXXXXXX'
        aws.requestID: 'bacd8338-2f8f-4ebb-afbc-71379c7fc15e'
        aws.source: 'cloudtrail'
        aws.sourceIPAddress: 'ssm.amazonaws.com'
        aws.userAgent: 'ssm.amazonaws.com'
        aws.userIdentity.accessKeyId: 'ASIASNL6BL*********'
        aws.userIdentity.accountId: 'XXXXXXXXXXX'
        aws.userIdentity.arn: 'arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory'
        aws.userIdentity.invokedBy: 'ssm.amazonaws.com'
        aws.userIdentity.principalId: 'AROASNL6BLJL*********:SSMInventory'
        aws.userIdentity.sessionContext.attributes.creationDate: '2023-09-15T01:07:49Z'
        aws.userIdentity.sessionContext.attributes.mfaAuthenticated: 'false'
        aws.userIdentity.sessionContext.sessionIssuer.accountId: 'XXXXXXXXXXX'
        aws.userIdentity.sessionContext.sessionIssuer.arn: 'arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
        aws.userIdentity.sessionContext.sessionIssuer.principalId: 'AROASNL6BLJL*********'
        aws.userIdentity.sessionContext.sessionIssuer.type: 'Role'
        aws.userIdentity.sessionContext.sessionIssuer.userName: 'AWSServiceRoleForAmazonSSM'
        aws.userIdentity.type: 'AssumedRole'
        integration: 'aws'

**Phase 3: Completed filtering (rules).
        id: '80202'
        level: '3'
        description: 'AWS Cloudtrail: resource-groups.amazonaws.com - ListGroups.'
        groups: '['amazon', 'aws', 'aws_cloudtrail']'
        firedtimes: '1'
        gdpr: '['IV_35.7.d']'
        hipaa: '['164.312.b']'
        mail: 'False'
        nist_800_53: '['AU.6']'
        pci_dss: '['10.6.1']'
        tsc: '['CC7.2', 'CC7.3']'
**Alert to be generated.
```

@wazuh/core Do you have any idea what might be happening?

**Comment by nico-stefani** [comment]
> # Issue Update
> Checking the processed events by the configured AWS integrations on the demo environment, we found that for `cloudtrail` one there are differences between rules matching compared with `4.5.2`. This is generating more alerts in the `alerts.json`.
> 
> The event in question
> 
> ```json
> {"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}
> ```
> 
> The log test for `4.5.2`
> 
> ```
> root@wazuh:/var/ossec# bin/wazuh-logtest
> Starting wazuh-logtest v4.5.2
> Type one log per line
> 
> {"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}
> 
> **Phase 1: Completed pre-decoding.
> 
> **Phase 2: Completed decoding.
>         name: 'json'
>         aws.awsRegion: 'us-west-1'
>         aws.aws_account_id: 'XXXXXXXXXXX'
>         aws.eventCategory: 'Management'
>         aws.eventID: '99493820-0d91-4c9d-978a-342d4af8fe03'
>         aws.eventName: 'ListGroups'
>         aws.eventSource: 'resource-groups.amazonaws.com'
>         aws.eventTime: '2023-09-15T01:07:49Z'
>         aws.eventType: 'AwsApiCall'
>         aws.eventVersion: '1.08'
>         aws.log_info.log_file: 'AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz'
>         aws.log_info.s3bucket: 'wazuh-aws-wodle'
>         aws.managementEvent: 'true'
>         aws.readOnly: 'true'
>         aws.recipientAccountId: 'XXXXXXXXXXX'
>         aws.requestID: 'bacd8338-2f8f-4ebb-afbc-71379c7fc15e'
>         aws.source: 'cloudtrail'
>         aws.sourceIPAddress: 'ssm.amazonaws.com'
>         aws.userAgent: 'ssm.amazonaws.com'
>         aws.userIdentity.accessKeyId: 'ASIASNL6BL*********'
>         aws.userIdentity.accountId: 'XXXXXXXXXXX'
>         aws.userIdentity.arn: 'arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory'
>         aws.userIdentity.invokedBy: 'ssm.amazonaws.com'
>         aws.userIdentity.principalId: 'AROASNL6BLJL*********:SSMInventory'
>         aws.userIdentity.sessionContext.attributes.creationDate: '2023-09-15T01:07:49Z'
>         aws.userIdentity.sessionContext.attributes.mfaAuthenticated: 'false'
>         aws.userIdentity.sessionContext.sessionIssuer.accountId: 'XXXXXXXXXXX'
>         aws.userIdentity.sessionContext.sessionIssuer.arn: 'arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
>         aws.userIdentity.sessionContext.sessionIssuer.principalId: 'AROASNL6BLJL*********'
>         aws.userIdentity.sessionContext.sessionIssuer.type: 'Role'
>         aws.userIdentity.sessionContext.sessionIssuer.userName: 'AWSServiceRoleForAmazonSSM'
>         aws.userIdentity.type: 'AssumedRole'
>         integration: 'aws'
> 
> **Phase 3: Completed filtering (rules).
>         id: '80200'
>         level: '0'
>         description: 'AWS alert.'
>         groups: '['amazon', 'aws']'
>         firedtimes: '1'
>         mail: 'False'
> ```
> 
> The log test for `4.6.0`
> 
> ```
> root@wazuh-master:/var/ossec# bin/wazuh-logtest
> Starting wazuh-logtest v4.6.0
> Type one log per line
> 
> {"integration":"aws","aws":{"log_info":{"log_file":"AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz","s3bucket":"wazuh-aws-wodle"},"eventVersion":"1.08","userIdentity":{"type":"AssumedRole","principalId":"AROASNL6BLJL*********:SSMInventory","arn":"arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory","accountId":"XXXXXXXXXXX","accessKeyId":"ASIASNL6BL*********","sessionContext":{"sessionIssuer":{"type":"Role","principalId":"AROASNL6BLJL*********","arn":"arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM","accountId":"XXXXXXXXXXX","userName":"AWSServiceRoleForAmazonSSM"},"attributes":{"creationDate":"2023-09-15T01:07:49Z","mfaAuthenticated":"false"}},"invokedBy":"ssm.amazonaws.com"},"eventTime":"2023-09-15T01:07:49Z","eventSource":"resource-groups.amazonaws.com","eventName":"ListGroups","awsRegion":"us-west-1","sourceIPAddress":"ssm.amazonaws.com","userAgent":"ssm.amazonaws.com","requestID":"bacd8338-2f8f-4ebb-afbc-71379c7fc15e","eventID":"99493820-0d91-4c9d-978a-342d4af8fe03","readOnly":"true","eventType":"AwsApiCall","managementEvent":"true","recipientAccountId":"XXXXXXXXXXX","eventCategory":"Management","source":"cloudtrail","aws_account_id":"XXXXXXXXXXX"}}
> 
> **Phase 1: Completed pre-decoding.
> 
> **Phase 2: Completed decoding.
>         name: 'json'
>         aws.awsRegion: 'us-west-1'
>         aws.aws_account_id: 'XXXXXXXXXXX'
>         aws.eventCategory: 'Management'
>         aws.eventID: '99493820-0d91-4c9d-978a-342d4af8fe03'
>         aws.eventName: 'ListGroups'
>         aws.eventSource: 'resource-groups.amazonaws.com'
>         aws.eventTime: '2023-09-15T01:07:49Z'
>         aws.eventType: 'AwsApiCall'
>         aws.eventVersion: '1.08'
>         aws.log_info.log_file: 'AWSLogs/XXXXXXXXXXX/CloudTrail/us-west-1/2023/09/15/XXXXXXXXXXX_CloudTrail_us-west-1_20230915T0110Z_u0nLl6wmhPkdhoez.json.gz'
>         aws.log_info.s3bucket: 'wazuh-aws-wodle'
>         aws.managementEvent: 'true'
>         aws.readOnly: 'true'
>         aws.recipientAccountId: 'XXXXXXXXXXX'
>         aws.requestID: 'bacd8338-2f8f-4ebb-afbc-71379c7fc15e'
>         aws.source: 'cloudtrail'
>         aws.sourceIPAddress: 'ssm.amazonaws.com'
>         aws.userAgent: 'ssm.amazonaws.com'
>         aws.userIdentity.accessKeyId: 'ASIASNL6BL*********'
>         aws.userIdentity.accountId: 'XXXXXXXXXXX'
>         aws.userIdentity.arn: 'arn:aws:sts::XXXXXXXXXXX:assumed-role/AWSServiceRoleForAmazonSSM/SSMInventory'
>         aws.userIdentity.invokedBy: 'ssm.amazonaws.com'
>         aws.userIdentity.principalId: 'AROASNL6BLJL*********:SSMInventory'
>         aws.userIdentity.sessionContext.attributes.creationDate: '2023-09-15T01:07:49Z'
>         aws.userIdentity.sessionContext.attributes.mfaAuthenticated: 'false'
>         aws.userIdentity.sessionContext.sessionIssuer.accountId: 'XXXXXXXXXXX'
>         aws.userIdentity.sessionContext.sessionIssuer.arn: 'arn:aws:iam::XXXXXXXXXXX:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM'
>         aws.userIdentity.sessionContext.sessionIssuer.principalId: 'AROASNL6BLJL*********'
>         aws.userIdentity.sessionContext.sessionIssuer.type: 'Role'
>         aws.userIdentity.sessionContext.sessionIssuer.userName: 'AWSServiceRoleForAmazonSSM'
>         aws.userIdentity.type: 'AssumedRole'
>         integration: 'aws'
> 
> **Phase 3: Completed filtering (rules).
>         id: '80202'
>         level: '3'
>         description: 'AWS Cloudtrail: resource-groups.amazonaws.com - ListGroups.'
>         groups: '['amazon', 'aws', 'aws_cloudtrail']'
>         firedtimes: '1'
>         gdpr: '['IV_35.7.d']'
>         hipaa: '['164.312.b']'
>         mail: 'False'
>         nist_800_53: '['AU.6']'
>         pci_dss: '['10.6.1']'
>         tsc: '['CC7.2', 'CC7.3']'
> **Alert to be generated.
> ```
> 
> @wazuh/core Do you have any idea what might be happening?

I compared it again with a fresh Wazuh 4.5.2 and now they are generating the same number of alerts.
* 4.5.2
```
root@aa93320690ff:/var/ossec# bin/wazuh-control info
WAZUH_VERSION="v4.5.2"
WAZUH_REVISION="40505"
WAZUH_TYPE="server"
root@aa93320690ff:/var/ossec# wc -l logs/alerts/alerts.json
175 logs/alerts/alerts.json
```

* 4.6.0
```
root@wazuh-master:/var/ossec# bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40600"
WAZUH_TYPE="server"
root@wazuh-master:/var/ossec# wc -l logs/alerts/alerts.json
175 logs/alerts/alerts.json
```

**Comment by Selutario** [comment]
After using a script created by @nico-stefani, these are all the alerts found on the `alerts.json` of _2023-09-09_, whose uncompressed size is 6.2 GB (the biggest of the currently existent):
```
================= Rule count result =================
[('80401', 4398043), ('80402', 1923409), ('5706', 3)]
```

Almost all of them are from VPC Flow, so we can rule out any other problem that day:
https://github.com/wazuh/wazuh/blob/b8e5c4beebdf2d5ec7bed1bb41227273588780cb/ruleset/rules/0350-amazon_rules.xml#L348-L362
