### ISSUE TITLE
Module docker-listener not executed every <interval> it stays blocked in wpopenl

### ISSUE THREAD

**Issue by thejbte** [wazuh/wazuh#18906]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5 | Wazuh-modulesd | Manager | Source | Ubuntu 22.04 |

## Description:
When the docker module is configured, the logs shown in ossec.log only appear the first time after restarting wazuh-server, the module scans fine and the commands are seen in archives.json, but `wm_docker_main()` is not executed every `<interval>30s</interval>` https://github.com/wazuh/wazuh/blob/cc01438f4e941b6decd6bb76c7cfd68fd4199e10/src/wazuh_modules/wm_docker.c#L63 

*Note:* This issue was encountered while developing https://github.com/wazuh/wazuh/issues/17049

## Configurations:
Add to ossec.conf:
```xml
<wodle name="docker-listener">
    <interval>30s</interval>
    <attempts>5</attempts>
    <run_on_start>no</run_on_start>
    <disabled>no</disabled>
</wodle>
```
Set debug options `wazuh_modules.debug=2`

## Logs:
This log only appear after restarting wazuh-server:
```xml
2023/09/07 17:29:58 wazuh-modulesd:docker-listener[2117421] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2023/09/07 17:29:58 wazuh-modulesd:docker-listener[2117421] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2023/09/07 17:29:58 wazuh-modulesd:docker-listener[2117421] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2111073   10317  0 17:23 pts/2    00:00:00 grep --color=auto wm_docker
```

Log with modified code:
```xml
thejbte@julian-A15-FA506QM:~/Documents/wazuh-master/src$ sudo tail -f /var/ossec/logs/ossec.log | grep wm_docker

2023/09/08 13:22:37 wazuh-modulesd:docker-listener[2369871] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2023/09/08 13:22:37 wazuh-modulesd:docker-listener[2369871] wm_docker.c:56 at wm_docker_main(): DEBUG: Sleeping until: 2023/09/08 13:23:07
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
thejbte  2369189   10317  0 13:22 pts/2    00:00:00 grep --color=auto wm_docker
2023/09/08 13:23:07 wazuh-modulesd:docker-listener[2369871] wm_docker.c:60 at wm_docker_main(): INFO: Starting to listening Docker events.
2023/09/08 13:23:07 wazuh-modulesd:docker-listener[2369871] wm_docker.c:64 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

The C code crashes here, when the command tries to execute  (`wodles/docker/DockerListener`) which calls `DockerListener.py`.:
https://github.com/wazuh/wazuh/blob/cc01438f4e941b6decd6bb76c7cfd68fd4199e10/src/wazuh_modules/wm_docker.c#L65

Perhaps the crash is in `DockerListener.py`.

**Comment by EduLeon12** [comment]
## Issue Update

After investigating and performing some tests to fully understand the behavior of the module, a meeting has been set with the team leader to plan the next steps.

**Comment by EduLeon12** [comment]
## Issue Update

After reviewing and analyzing the module it was found that the issue reported is not a bug. It is the intended behavior of the module.

The standard behavior of the wodles are: 

- First, the modulesd (core) is started based on the configuration found in the ossec.conf making it execute a bash command.
- Then, the bash command executes the Python script for the wodle.
- The Python script captures all logs from its execution and sends them to the standard output. 
-  Lastly, modulesd (core) prints all logs found in standard output into ossec.log.

The difference between the cloud and docker modules, is that the Python script for the docker-listener module creates a thread to process docker events in a neverending loop. Therefore, the Python script never ends resulting in the modulesd (core) never getting to the point to read the logs.

That's why when executing the module manually all events and prints can be seen. 

For example:
```
{"integration": "docker", "docker": {"Wodle event": "Started"}}
Docker service was started.
{"integration": "docker", "docker": {"Wodle event": "Connected to Docker service"}}
{"integration": "docker", "docker": {"status": "exec_create: /bin/sh -c grep \"INFO: (4102): Connected to the server\" /var/ossec/logs/ossec.log || exit 1", "id": "0377a3fa6e3c9b6ee3cc99dd5c01efb3caf424a1d5fb98c6e6f0aa088fbee7ba", "from": "dev-wazuh-agent", "Type": "container", "Action": "exec_create: /bin/sh -c grep \"INFO: (4102): Connected to the server\" /var/ossec/logs/ossec.log || exit 1", "Actor": {"ID": "0377a3fa6e3c9b6ee3cc99dd5c01efb3caf424a1d5fb98c6e6f0aa088fbee7ba", "Attributes": {"com.docker.compose.config-hash": "a9f87e8a7fafc648ce7ddcbe8218640c097fe6e8a735c7e668818531264989c9", "com.docker.compose.container-number": "1", "com.docker.compose.oneoff": "False", "com.docker.compose.project": "dev", "com.docker.compose.project.config_files": "/home/eduardoleon/git/wazuh-tools/framework/environments/dev/docker-compose.yml", "com.docker.compose.project.working_dir": "/home/eduardoleon/git/wazuh-tools/framework/environments/dev", "com.docker.compose.service": "wazuh-agent", "com.docker.compose.version": "1.29.2", "execID": "25a4b974cf8139b97bd4f9c760724db4bf383e80ad6fb89ee48c709d1d3ac82d", "image": "dev-wazuh-agent", "name": "dev_wazuh-agent_1", "org.opencontainers.image.ref.name": "ubuntu", "org.opencontainers.image.version": "22.04"}}, "scope": "local", "time": 1695835927, "timeNano": 1695835927558472079}}

```
  
And in the ossec.log only the messages defined in the macros.

For example:

```
2023/09/27 15:02:38 wazuh-modulesd:docker-listener[102908] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
```

**Comment by GGP1** [comment]
## Review

The `docker-listener` wodle functionality description is correct and the difference between it and the cloud modules was outlined and explained in detail.

Since there's no plans to change this behavior, I consider this issue ready for final review.
