### ISSUE TITLE
Remoted warning too big message in Footprint tests

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18937]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-apha1 | Remoted | Manager | Packages and Sources | CentOS |

Analyzing footprint test https://github.com/wazuh/wazuh/issues/18922 a new warning has been seen, related to remoted and saying a message size is too big. A similar error has been reported in https://github.com/wazuh/wazuh/issues/17596, but in that case just for macOS, which isn't the case here.

The warning:

```
wazuh-remoted WARNING: Too big message size from socket [22].
```

**Comment by vikman90** [comment]
@verdx Let's extend #17596 to report that the same message has been seen from CentOS agents.
