### ISSUE TITLE
Deployment variable `WAZUH_MANAGER` not working on macOS Ventura x86

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#18933]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 |  | Agent | Installation command | MacOS 13.5.2 Ventura |

## Description
During E2E testing, on https://github.com/wazuh/wazuh/issues/18832 the `WAZUH_MANAGER` variable did not work on the installation. 

```console
sh-3.2# \curl -so wazuh-agent.pkg https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.6.0-1.intel64.pkg && echo -e "WAZUH_MANAGER='192.168.0.99'\nWAZUH_AGENT_GROUP='testgroup2,testgroup1,default'\nWAZUH_AGENT_NAME='testmacOS'\n" > /tmp/wazuh_envs && sudo installer -pkg ./wazuh-agent.pkg -target / 
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# sudo /Library/Ossec/bin/wazuh-control start
2023/09/09 17:22:42 wazuh-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
2023/09/09 17:22:42 wazuh-agentd: ERROR: (1215): No client configured. Exiting.
wazuh-agentd: Configuration error. Exiting

```

Tested several times, the issue always happened. The variables `WAZUH_AGENT_GROUP` and `WAZUH_AGENT_NAME` worked as expected.

The generated `/tmp/wazuh_envs` during the process:
```
WAZUH_MANAGER='192.168.0.99'
WAZUH_AGENT_GROUP='testgroup2,testgroup1,default'
WAZUH_AGENT_NAME='testmacOS'
```

**Comment by nmkoremblum** [comment]
Hi, please try without using the `-e` flag on the `echo`

**Comment by jnasselle** [comment]
This issue should be closed in favor of https://github.com/wazuh/wazuh-kibana-app/issues/5886, since the problem resides on a misalignment between https://github.com/wazuh/wazuh-kibana-app/issues/4205 implementation and original changes on https://github.com/wazuh/wazuh-packages/issues/2205
