### ISSUE TITLE
Update embedded cpython version for dependencies 23

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#18949]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Wazuh component |

## Description

[Issue 2154](https://github.com/wazuh/wazuh-packages/issues/2154), which is being solved at [PR 2164](https://github.com/wazuh/wazuh-packages/pull/2164), was tested to generate packages with cpython library from file 21-16279.zip, which was added to dependencies 23 for testing purposes. 

When generating packages using DEPS=22, packages are being build successfully. When using a PR with only DEPS=23 as a change, the following errors occur:

```
cd ../framework && /var/ossec/framework/python/bin/python3 -m pip install . --use-pep517 --prefix=/var/ossec/framework/python --config-settings="--wazuh-version=v4.8.0" --config-settings="--install-type=server" && rm -rf build/

Usage:   
  /var/ossec/framework/python/bin/python3 -m pip install [options] <requirement specifier> [package-index-options] ...
  /var/ossec/framework/python/bin/python3 -m pip install [options] -r <requirements file> [package-index-options] ...
  /var/ossec/framework/python/bin/python3 -m pip install [options] [-e] <vcs project url> ...
  /var/ossec/framework/python/bin/python3 -m pip install [options] [-e] <local project path> ...
  /var/ossec/framework/python/bin/python3 -m pip install [options] <archive url/path> ...

no such option: --config-settings
make: *** [install_framework] Error 2
chcon: can't apply partial context to unlabeled file '/var/ossec/lib/libjemalloc.so.2'
```

and finally:

```
Processing files: wazuh-manager-4.8.0-1.x86_64
error: File not found: /build_wazuh/rpmbuild/BUILDROOT/wazuh-manager-4.8.0-1.x86_64/var/ossec/var/db/mitre.db
```

Apparently, the embedded cpython library used at dependencies 23 is out of date, and has a pip version which doesn't recognize --config-settings option.

We would need the cpython version to be updated at dependencies 23 and the new zip file to be provided.

Regards!

**Comment by ncvicchi** [comment]
We would need the correct and tested to compile package in order to go forward. Can you provide it?

**Comment by Selutario** [comment]
Deps 22 and 23 are the same, folder 23 will be deleted according to the core team.
