### ISSUE TITLE
 Release 4.6.0 - Alpha 1 - Integration tests

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#18941]
|||
| :--                                   | :--                                                       |
| **Main release issue**                | https://github.com/wazuh/wazuh/issues/18858 |
| **Main release candidate issue**      | https://github.com/wazuh/wazuh/issues/18859                               |
| **Version**                           | 4.6.0                                             |
| **Release candidate**                 | Alpha 1                                                |
| **wazuh/wazuh tag**                   | https://github.com/wazuh/wazuh/tree/v4.6.0-alpha1    |
| **wazuh/wazuh-qa tag**                | https://github.com/wazuh/wazuh/tree/v4.6.0-alpha1    |
| **Previous release testing issue**    | https://github.com/wazuh/wazuh/issues/18622 |
| **Build**                             | https://ci.wazuh.info/job/Test_integration_launcher/193/ |

</br>

<details><summary>Parameters</summary></br>

- `PKG_VERSION`: 4.6.0
- `PKG_REVISION`: 1
- `TARGET_REPOSITORY`: pre-release
- `QA_REFERENCE`: v4.6.0-alpha1
- `JENKINS_REFERENCE`: v4.6.0-alpha1
- `LINUX_OS`: CentOS
- `MODULES`: All except WPK

</details>

</br>

# Conclusion :red_circle:

Some issues were found during the testing and one of them is a known issue.

|State | Suite | Target | OS | Issues |
|--|--|--|--|--
| :yellow_circle:  | Syscollector | Agent | Windows | Known issue: https://github.com/wazuh/wazuh-qa/issues/4230 |
| :red_circle: | Syscollector | Agent | Windows | https://github.com/wazuh/wazuh/issues/18957 |
| :red_circle: | Syscollector | Agent | Windows | https://github.com/wazuh/wazuh/issues/18968 |
| :red_circle: | * | Agent | Windows | https://github.com/wazuh/wazuh/issues/18952 |
| :red_circle: | Active Response | Agent | Windows | https://github.com/wazuh/wazuh-qa/issues/4512 |
| :yellow_circle:  | Active Response | Agent | Windows | Known issue: https://github.com/wazuh/wazuh/issues/18179 |
| :red_circle: | Active Response | Agent | Windows | https://github.com/wazuh/wazuh-qa/issues/4516 |
| :yellow_circle:  | Vulnerability Detector | Manager | CentOS | Known issue: https://github.com/wazuh/wazuh-qa/issues/4370 |
| :red_circle: | Agentd | Agent | Windows| https://github.com/wazuh/wazuh-qa/issues/4513|
| :red_circle: | Agentd | Agent | Windows| https://github.com/wazuh/wazuh/issues/18957 |
| :red_circle: | Agentd | Agent | Windows|  https://github.com/wazuh/wazuh/issues/18968 |
| :red_circle:  | FIM | Agent | Linux | https://github.com/wazuh/wazuh-qa/issues/4514 |
| :red_circle:  | FIM | Agent | Windows | https://github.com/wazuh/wazuh-qa/issues/4515|
| :red_circle:  | FIM | Agent | Windows | https://github.com/wazuh/wazuh-qa/issues/4518 |
| :red_circle:  | Other (Test) | -- | -- | https://github.com/wazuh/wazuh-qa/issues/4517 |

## Description

The objective of this issue is to check that the integration tests pass successfully against the `4.6.0` version of Wazuh.

## Results of the integration tests

<details><summary>Results</summary></br>

<div class="tg-wrap"><table>
<thead>
  <tr>
    <th>Test suite</th>
    <th>Target</th>
    <th>Linux</th>
    <th>Windows</th>
    <th>Solaris</th>
    <th>macOS</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>Syscollector</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577163/manager_tests_Test_integration_B42953_20230911131544.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Office365</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577216/office365-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Logtest</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577223/logtest-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>GitHub</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577444/github-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>RIDS</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577603/rids-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Wazuh DB</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580004/wazuh-db-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Active Response</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580016/ar-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Rootcheck</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580029/rootcheck-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>GCloud</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580030/gcloud-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>API</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580540/api-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>FIM</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581473/fim-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Remoted</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581482/remoted-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Logcollector</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581534/logcollector-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Authd</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581542/authd-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Analysisd</td>
    <td>Manager</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581567/analysisd-manager.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Vulnerability Detector</td>
    <td>Manager</td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12581594/vd-manager.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>GitHub</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577461/github-agent.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Office365</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12577490/office365-agent.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Active Response</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580272/ar-agent-linux.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12580273/ar-agent-windows.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Enrollment</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580532/enrollment-agent-linux.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580531/enrollment-agent-windows.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Syscollector</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580694/syscollector-agent-linux.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12580689/syscollector-agent-windows.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12580693/syscollector-agent-macos.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
  </tr>
  <tr>
    <td>FIM</td>
    <td>Agent</td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12588383/agent_centos_html_report_Test_integration_B42938_20230911131814.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12588382/agent_windows_html_report_Test_integration_B42938_20230911131814.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581552/fim-agent-solaris.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581553/fim-agent-macos.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
  </tr>
  <tr>
    <td>Agentd</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12588344/centos_agent_tests_Test_integration_B42932_20230911132044.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/12588811/agent_windows_html_report_Test_integration_B42932_20230911132044.zip" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>N/A</td>
    <td>N/A</td>
  </tr>
  <tr>
    <td>Logcollector</td>
    <td>Agent</td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581613/centos_agent_tests_Test_integration_B42944_20230911131723.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12588365/centos_agent_tests_Test_integration_B42944_20230911131723.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581611/solaris_agent_tests_Test_integration_B42944_20230911131723.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
    <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/12581612/macos_agent_tests_Test_integration_B42944_20230911131723.txt" target="_blank" rel="noopener noreferrer">Artifact</a></td>
  </tr>
</tbody>
</table></div>

</details>

</br>

> |Color|Status |
> |:--:|:--|
> | :green_circle: | All tests passed successfully |
> | :yellow_circle: | Known issues |
> | :red_circle: | Found new errors, failures or defects |
> | :black_circle: | Pending/In Progress

## Validation of the auditors

The Definition of Done is the corresponding validation of the results from all the auditors.

To close this issue, both checks must be marked:

- [ ] @davidjiglesias
- [x] @wazuh/qa

**Comment by rauldpm** [comment]
## Analysis report - Logcollector Agent

**Comment by rauldpm** [comment]
## Analysis report - Active Response - Agent - Windows

- Reported Timeout error in test at: https://github.com/wazuh/wazuh-qa/issues/4512

**Comment by rauldpm** [comment]
## Analysis report - Agentd - Windows

**Comment by rauldpm** [comment]
## Analysis report - FIM - Agent

**Comment by mauromalara** [comment]
## Analysis report - Active Response - Windows

Regarding this failure:
```
.
.
.
>                   raise TimeoutError(error_message)
E                   TimeoutError
```

It was introduced by a fix in this PR: https://github.com/wazuh/wazuh-qa/pull/4360. In which we modified a library that affected another test in Windows. In that PR we did not execute the affected test, causing that we did not detect this error.

- The failure was reported here: https://github.com/wazuh/wazuh-qa/issues/4512
- The failure was fixed in: https://github.com/wazuh/wazuh-qa/pull/4511

**Comment by damarisg** [comment]
LGTM
