### ISSUE TITLE
Error while Installing of Wazuh Agent on Arch Linux 

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh#18943]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.6.0-alpha1	|Agent|Deplyoing Wazuh agent via dashboard and installation sources|Deplyoing Wazuh agent via dashboard and installation sources|Arch Linux|

During E2E testing on [#18841  ](https://github.com/wazuh/wazuh/issues/18841), I could use any of the deployment options on the Wazuh dashboard as the packages available are not supported natively on Arch Linux. 

![image](https://github.com/wazuh/wazuh-documentation/assets/108103499/9098205d-c3e4-4fd4-b37a-dc29bdea3c62)

```
[arch@ip-172-31-25-195 ~]$ wget https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.6.0-1_amd64.deb && sudo WAZUH_MANAGER='xx.xx.xx.xx' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='Wazuh-Agent' dpkg -i ./wazuh-agent_4.6.0-1_amd64.deb
--2023-09-10 07:44:35--  https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.6.0-1_amd64.deb
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving packages-dev.wazuh.com (packages-dev.wazuh.com)... 18.238.192.15, 18.238.192.114, 18.238.192.110, ...
Connecting to packages-dev.wazuh.com (packages-dev.wazuh.com)|18.238.192.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9204258 (8.8M) [binary/octet-stream]
Saving to: ‘wazuh-agent_4.6.0-1_amd64.deb.1’

wazuh-agent_4.6.0-1_amd64.deb 100%[=================================================>]   8.78M  --.-KB/s    in 0.05s

2023-09-10 07:44:36 (185 MB/s) - ‘wazuh-agent_4.6.0-1_amd64.deb.1’ saved [9204258/9204258]

sudo: dpkg: command not found

[arch@ip-172-31-25-195 ~]$ curl -o wazuh-agent-4.6.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.6.0-1.x86_64.rpm && sudo WAZUH_MANAGER='54.176.14.197' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='Wazuh-Agent' rpm -ihv wazuh-agent-4.6.0-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9179k  100 9179k    0     0  72.9M      0 --:--:-- --:--:-- --:--:-- 73.4M
sudo: rpm: command not found
[arch@ip-172-31-25-195 ~]$ sudo curl -o wazuh-agent-4.6.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.6.0-1.x86_64.rpm && sudo WAZUH_MANAGER='54.176.14.197' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='Wazuh-Agent' rpm -ihv wazuh-agent-4.6.0-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9179k  100 9179k    0     0  84.1M      0 --:--:-- --:--:-- --:--:-- 84.5M
sudo: rpm: command not found
```

Based on this fact, I tried using installation from sources, and I could not proceed further when I tried to install the dependencies using the command `pacman --noconfirm -Syu curl gcc make sudo wget expect gnupg perl-base perl fakeroot python brotli automake autoconf libtool gawk libsigsegv nodejs base-devel inetutils cmake`

![image](https://github.com/wazuh/wazuh-documentation/assets/108103499/50e38a31-c18a-4a9b-bcca-c06c5000e3a9)

**Comment by vikman90** [comment]
@thony4uu I think this issue is related to @wazuh/frontend.

**Comment by AlexRuiz7** [comment]
`rpm` and `dpkg` tools are not found in the target operative system. Arch Linux uses [pacman](https://wiki.archlinux.org/title/pacman) as a package manager

```sh
docker run -it --rm archlinux bash
Unable to find image 'archlinux:latest' locally
latest: Pulling from library/archlinux
87df56ae4a93: Pull complete 
7171264b9dde: Pull complete 
Digest: sha256:b29dab0d5f362cfe2ed4662c46f27855681d56fb548fd2f6d927fd573131178a
Status: Downloaded newer image for archlinux:latest
[root@cbaa7824199f /]# apk
bash: apk: command not found
[root@cbaa7824199f /]# rpm
bash: rpm: command not found
[root@cbaa7824199f /]# dpkg
bash: dpkg: command not found
[root@cbaa7824199f /]# apt
bash: apt: command not found
[root@cbaa7824199f /]# yum
bash: yum: command not found
[root@cbaa7824199f /]# pacman
warning: database file for 'core' does not exist (use '-Sy' to download)
warning: database file for 'extra' does not exist (use '-Sy' to download)
error: no operation specified (use -h for help)
```

I think this should be considered an exception and addressed via documentation. This corner case is not taken in consideration in the documentation when installing from sources, but not using packages.

![image](https://github.com/wazuh/wazuh/assets/15186973/a2da2923-224e-4e29-ad70-e8588b118103)

**Comment by gdiazlo** [comment]
It is expected to use the documentation when the wizard does not support explicitly the package manager an OS uses. In the wizard, there is a note indicating to refer to the documentation.

If the documentation does not address the combination shown in the test, either it is a flaw in the test, or we should open an issue to support the mentioned OS by adding the relevant section to the documentation, and supporting and maintaining the OS.
