### ISSUE TITLE
Windows agent library not signed on Footprint tests

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18952]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | wazuh-agent | Agent | Packages | Windows |

When analyzing the Footprint tests for Alpha 1 for 4.6.0, a new warning has been encountered, saying dynamic library `libfimdb.dll` is not signed in the package.

It has appeared on the following footprint tests for now:
- https://github.com/wazuh/wazuh/issues/18930
- https://github.com/wazuh/wazuh/issues/18919
- https://github.com/wazuh/wazuh/issues/18915

The complete warning is the following:
```
wazuh-agent WARNING: The file 'C:\\Program Files (x86)\\ossec-agent\\libfimdb.dll' is not signed or its signature is invalid.
```

**Comment by vikman90** [comment]
This issue is related to https://github.com/wazuh/wazuh-packages/issues/2440.

**Comment by GabrielEValenzuela** [comment]
# Update

## Summary
We are currently working on creating a digital signature for the DLL. Tests are in progress to ensure the signing process is successful.

## Next Steps
- Continue testing the signing process.
- Verify that the signed DLL functions correctly in the application.

## Deadline
There is no specific deadline set for this issue at the moment, but we aim to complete this issue as soon as possible.
