### ISSUE TITLE
An empty DB is created by `wazuh-db` when a new agent is registered

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#18955]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least 4.5, it could be earlier | wauzh-db | Manager | Packages/Sources | Linux |

## Description

It was found that sometimes, when a new agent is registered, `wazuh-db` creates an empty DB that can't be used

```
root@ubuntu-jammy:/var/ossec# ls -la queue/db/
total 23292
drwxr-x---  2 wazuh wazuh    4096 Sep  9 05:31 .
drwxr-x--- 15 root  wazuh    4096 Sep  9 05:26 ..
-rw-r-----  1 wazuh wazuh 3375104 Sep  9 05:31 000.db
-rw-r-----  1 wazuh wazuh 1478656 Sep  9 00:33 001.db
-rw-r-----  1 wazuh wazuh 4333568 Sep  9 00:49 002.db
-rw-r-----  1 wazuh wazuh 5804032 Sep  9 01:05 003.db
-rw-r-----  1 wazuh wazuh 4648960 Sep  9 05:11 004.db
-rw-r-----  1 wazuh wazuh 4116480 Sep  9 05:22 005.db
-rw-r--r--  1 root  root        0 Sep  9 05:18 006.db
-rw-r-----  1 wazuh wazuh   81920 Sep  9 05:27 global.db
srw-rw----  1 wazuh wazuh       0 Sep  9 05:26 wdb
```

As it can be seen above, the `006.db` has a size 0 and different pemissions. 

This generates the following error messages

```
2023/09/09 05:27:02 wazuh-db: ERROR: DB(006) sqlite3_prepare_v2() stmt(102): no such table: pm_event
2023/09/09 05:27:02 wazuh-db: ERROR: DB(006) Cannot cache statement
2023/09/09 05:27:02 wazuh-db: ERROR: DB(006) Error updating rootcheck PM tuple on SQLite database
2023/09/09 05:27:03 wazuh-db: ERROR: DB(006) sqlite3_prepare_v2() stmt(46): no such table: scan_info
2023/09/09 05:27:03 wazuh-db: ERROR: DB(006) Cannot cache statement
2023/09/09 05:27:03 wazuh-analysisd: ERROR: FIM decoder: Bad response from database: Cannot save fim control message
2023/09/09 05:27:08 wazuh-remoted: WARNING: Agent key already in use: agent ID '006'
2023/09/09 05:27:18 wazuh-db: ERROR: DB(006) sqlite3_prepare_v2() stmt(102): no such table: pm_event
2023/09/09 05:27:18 wazuh-db: ERROR: DB(006) Cannot cache statement
2023/09/09 05:27:18 wazuh-db: ERROR: DB(006) Error updating rootcheck PM tuple on SQLite database
2023/09/09 05:27:20 rootcheck: INFO: Ending rootcheck scan.
2023/09/09 05:27:21 wazuh-db: ERROR: DB(006) sqlite3_prepare_v2() stmt(46): no such table: scan_info
2023/09/09 05:27:21 wazuh-db: ERROR: DB(006) Cannot cache statement
2023/09/09 05:27:21 wazuh-analysisd: ERROR: FIM decoder: Bad response from database: Cannot save fim control message
2023/09/09 05:27:24 wazuh-db: ERROR: DB(006) sqlite3_prepare_v2() stmt(102): no such table: pm_event
2023/09/09 05:27:24 wazuh-db: ERROR: DB(006) Cannot cache statement
2023/09/09 05:27:24 wazuh-db: ERROR: DB(006) Error updating rootcheck PM tuple on SQLite database
```

This behavior happened in an Ubuntu manager v4.5.3 and v4.8.0.
It could be related to a failure in`wdb_create_agent_db2()` or `wdb_create_profile()`.

## How to reproduce

The issue isn't easy to reproduce, it happens once in a while when a new agent is registered.

## DoD

- [ ] Find the root cause of the issue and describe it in a comment
- [ ] Make the required changes to fix it
- [ ] Make all the required tests to make sure the issue won't happen again

**Comment by nmkoremblum** [comment]
Hi @pereyra-m,

Do we have any other information regarding the Manager and Agent's configurations, OS types, or other relevant information that might be useful?

**Comment by pereyra-m** [comment]
Hi @nmkoremblum !
I opened this issue a long time ago, and I made sure that it happened more than once before creating the issue.
I'll share with you some more data.

**Comment by nmkoremblum** [comment]
On hold in favor of https://github.com/wazuh/wazuh/issues/23043

**Comment by cborla** [comment]
This issue is blocked until we obtain information from:
- [Replicate error sqlite3_prepare_v2() : no such table in Jenkins pipeline.](https://github.com/wazuh/wazuh-qa/issues/5309)
