### ISSUE TITLE
Syscheck event ignored in Footprint tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#18967]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | Syscheck | Agent | Packages/Sources | Windows |

 ## Description

During testing of Release 4.6.0 Alpha 1, in the Footprint tests for syscheck module (https://github.com/wazuh/wazuh/issues/18915), an unexpected error was detected on the Windows Agent.

```
wazuh-agent WARNING: (6954): Entry 'c:\\tmp\\syscheck_test\\files\\fimstress.11999586' does not have any modified fields. No event will be generated.
```

**Comment by ncvicchi** [comment]
This is the expected behaviour. It's a way to avoid false positives when dbsync found changes only at `last_event` field. We will move the message to a debug2 level in order to avoid it in productive environments.
