### ISSUE TITLE
Footprint test- Read ops increased

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#18978]
Detected that the manager's Read ops increased on the results of footprint tests https://github.com/wazuh/wazuh/issues/18914 running all except syscheck.

Compared with: https://github.com/wazuh/wazuh/issues/18660

- 4.5.2 graph:

![image](https://github.com/wazuh/wazuh/assets/26927338/7eea7a6f-d45d-4787-a69f-6f75de1e22c8)

- 4.6.0 Alpha 1 graph:

![image](https://github.com/wazuh/wazuh/assets/26927338/0ed3c02e-3311-40cb-a574-8f7f5cbb72cc)

**Comment by nmkoremblum** [comment]
After analyzing the issue, it appears that the increase in disk read operations compared to the previous version may not be of relevance. Disk read operations can exhibit non-deterministic behavior, and upon comparing the total amount of bytes read, it can be seen that there is a minor increase which comes in hand with an increase in processing power compared to the previous version. This suggests that the software's behavior is consistent with expectations.

![Normalized performance comparison](https://github.com/wazuh/wazuh/assets/75255206/93c1b101-67a8-41a0-a643-78cf9186e1a6)
