### ISSUE TITLE
Vulnerability detector cannot update Debian database

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#18983]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 |  | Vulnerability detector |  |  |

## Description
During E2E testing, on https://github.com/wazuh/wazuh/issues/18832, the manager wasn't able to fetch the Debian vulnerability databases. Always showed the same error

```log
2023/09/12 12:22:33 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Debian Bookworm' database update.
2023/09/12 12:52:43 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Debian Bookworm' database could not be fetched.
```
Tested several times on 09-12-2023. It may be a temporary issue with the servers.

After a day, the issue remains. A ping to `debian.org` can be done without issues.

```console
[root@rhel2 ~]# tail -100 /var/ossec/logs/ossec.log | grep vuln
2023/09/13 10:40:33 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Debian Bookworm' database update.
2023/09/13 11:00:43 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'Debian Bookworm' database could not be fetched.
2023/09/13 11:00:43 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2023/09/13 11:00:43 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2023/09/13 11:00:49 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.
2023/09/13 11:01:14 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '000'
2023/09/13 11:01:14 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.
2023/09/13 11:05:44 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Debian Bookworm' database update.
[root@rhel2 ~]# ping debian.org
PING debian.org (151.101.66.132) 56(84) bytes of data.
64 bytes from 151.101.66.132 (151.101.66.132): icmp_seq=1 ttl=57 time=20.7 ms
64 bytes from 151.101.66.132 (151.101.66.132): icmp_seq=2 ttl=57 time=19.8 ms
64 bytes from 151.101.66.132 (151.101.66.132): icmp_seq=3 ttl=57 time=19.3 ms

```

**Comment by Tostti** [comment]
Doing further research, concluded that the issue was not Wazuh related. Instead, the ISP from the machines where the tests were made was blocking the access to the database URL. 

After changing the network, it worked as expected.

**Comment by MarcelKemp** [comment]
Thank you, @Tostti!
We have also verified this:
- https://www.isitdownrightnow.com/debian.org.html
- `2023/09/13 15:20:25 wazuh-modulesd:vulnerability-detector[494] wm_vuln_detector.c:5349 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Debian Bookworm' feed finished successfully.`

I shall therefore close the issue.
