### ISSUE TITLE
Index State Management default policy

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#18999]
Currently, Wazuh alerts are indexed into Wazuh Indexer using daily indices, but we do not provide any solution for those indices' management over time.

Using Index State Management policies will allow us to define the lifecycle for an index from the ingestion stage to deletion. Enabling us to optimize the cluster performance and establishing a retention policy for our data.

### Why is it a problem for Indexer?

With the current default configuration, creating two daily indices (monitoring and alerts) with 3 shards per index would generate 2190 active shards after a year. Without the proper management tools, that could cause a cluster failure and performance issues.
New indices should not be created based on "elapsed time" (or at least not only cause that) but must be based on index size, shard size, and document weight.

### What is an ISM policy?

Extracted from OpenSearch documentation: https://opensearch.org/docs/latest/im-plugin/ism/index/

Index State Management (ISM) is a plugin that lets you automate these periodic, administrative operations by triggering them based on changes in the index age, index size, or number of documents. Using the ISM plugin, you can define policies that automatically handle index rollovers or deletions to fit your use case.

### Goal 

Create an ISM policy, template, and everything required in order to ensure that indices are in good shape with no manual management over time. Rollover policy based on index total size, using indices alias.
It should be included out of the box.

### Non-functional

- Easy to upgrade from previous versions. Meaning, no breaking changes
- Indexing/Searching performance must be equal or better, never worse
- Since no breaking changes are allowed, Filebeat 7.10.2 must be the connector manager<>indexer
- No extra or minimum extra steps at the installation process (step by step @ documentation)
- Must be compatible with Wazuh Cloud (stay on same page, no major discordances between Cloud config and on-prem config)
- Easy to customize.
- Optionally, not modifiable by certain users (Cloud).

### Functional

- Index pattern value for policy definition: `wazuh-alerts-*` and `wazuh-archives-*`
- Index template name: `rollover_policy`
- Rollover alias: `wazuh-alerts` and `wazuh-archives`
- Priority: 50
- Minimum primary shard size: 25 GB
- Minimum index age: 7 days
- Minimum document count: 200M documents per index

### Implementation restrictions

- Compatible with Filebeat 7.10.2
- Compatible with Filebeat 7.10.2 custom plugins (Wazuh plugin)

## Plan

- [x] https://github.com/wazuh/wazuh/issues/19818
- [x] https://github.com/wazuh/wazuh-packages/issues/2567
- [x] https://github.com/wazuh/wazuh-packages/issues/2552
- [x] https://github.com/wazuh/wazuh-documentation/issues/6683
- [x] https://github.com/wazuh/wazuh-indexer/issues/53
- [x] Update QA tests and wokflows
      - https://github.com/wazuh/internal-devel-requests/issues/440

## Teams and product components affected 

- Documentation (@wazuh/documentation): New extra steps may be added to the installation steps. Moreover, it is possible that new files could be required to download. 

- Indexer (@wazuh/indexer): Main policy/ISM developers. 

- Cloud (@wazuh/cloud): As described before, there is already an ISM policy in place running in Cloud envs, both policies, on-prem and Cloud one, must be analyzed to verify they are compatible and they both make sense.

- QA (@wazuh/qa), Cloud (@wazuh/cloud): Cloud team approval and review

- Frontend (@wazuh/frontend): Not sure how it works nowadays but if the Dashboards visualizations are pulling from (`wazuh-alerts-*`) indices for sure this work will break every single visualization/table in our Dashboards.

**Comment by rwjack** [comment]
I have been using Wazuh for 2 years.

After the first 6 months I stopped getting any logs because of the issue described here. (I missed a month worth of logs).

The solution was so complicated to come by, (confusing documentation + google groups?? Who tf uses google groups??) I ended up reinstalling Wazuh completely and losing all logs.

I researched a bit and thought I found a solution, creating indice policies. It felt so good solving the problem, knowing I won't ever have this issue again.

Although not really. today I noticed I haven't been receiving logs for the past 2 months, even with the following policy:

```
{
    "policy_id": "hq_log_retention",
    "description": "Wazuh index state management for OpenDistro to move indices into a cold state after 3 months and delete them after a year.",
    "last_updated_time": 1666855400821,
    "schema_version": 12,
    "error_notification": null,
    "default_state": "hot",
    "states": [
        {
            "name": "hot",
            "actions": [
                {
                    "retry": {
                        "count": 3,
                        "backoff": "exponential",
                        "delay": "1m"
                    },
                    "replica_count": {
                        "number_of_replicas": 0
                    }
                }
            ],
            "transitions": [
                {
                    "state_name": "warm",
                    "conditions": {
                        "min_index_age": "32d"
                    }
                }
            ]
        },
        {
            "name": "warm",
            "actions": [],
            "transitions": [
                {
                    "state_name": "cold",
                    "conditions": {
                        "min_index_age": "92d"
                    }
                }
            ]
        },
        {
            "name": "cold",
            "actions": [
                {
                    "retry": {
                        "count": 3,
                        "backoff": "exponential",
                        "delay": "1m"
                    },
                    "read_only": {}
                }
            ],
            "transitions": [
                {
                    "state_name": "delete",
                    "conditions": {
                        "min_index_age": "366d"
                    }
                }
            ]
        },
        {
            "name": "delete",
            "actions": [
                {
                    "retry": {
                        "count": 3,
                        "backoff": "exponential",
                        "delay": "1m"
                    },
                    "delete": {}
                }
            ],
            "transitions": []
        }
    ],
    "ism_template": [
        {
            "index_patterns": [
                "wazuh-statistics*",
                "wazuh-alerts*",
                "wazuh-monitoring*"
            ],
            "priority": 100,
            "last_updated_time": 1661940491734
        }
    ]
}
```

It's really amazing how something so CRUCIAL to the core functioning and stability of this piece of software, hasn't been implemented yet.

Good luck.

**Comment by AlexRuiz7** [comment]
### Rollover and alias configuration

Applied an ISM policy for rollover as follows:

1. Pipeline modification

    Note: The steps in this section must be executed in every Wazuh manager in the environment.

    * Stop the Wazuh manager:

        ```bash
        systemctl stop wazuh-manager
        ```

    * Edit `/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json` and replace the following block:

        ```json
        {
          "date_index_name": {
            "field": "timestamp",
            "date_rounding": "d",
            "index_name_prefix": "{{fields.index_prefix}}",
            "index_name_format": "yyyy.MM.dd",
            "ignore_failure": false
          }
        }
        ```

        with this other one:

        ```json
        {
          "set": {
            "field": "_index",
            "value": "wazuh-alerts"
          }
        }
        ```

2. Template modification

    Note: The steps in this section must be executed in every Wazuh manager in the environment.

    * Edit `/etc/filebeat/wazuh-template.json` and add the following line inside the `settings` block:

        ```json
        "index.plugins.index_state_management.rollover_alias": "wazuh-alerts"
        ```

3. Pushing the new pipeline and template

    Push the pipeline and template (you can run this from any of the Wazuh servers in the environment):

    ```bash
    filebeat setup --pipelines
    filebeat setup --index-management
    ```

    ⚠️ `--.begin`
   `filebeat setup --index-management` raises the following output:
    ```
    ILM policy and write alias loading not enabled.

    Index setup finished.
    ```
    
    Setting `setup.ilm.enable: true` in `/etc/filebeat/filebeat.yml` throws this output:
    ```
    Exiting: ILM is not supported by the Elasticsearch version in use
    ```

   During the tests performed here, the default configuration is used, which is `setup.ilm.enable: false`. The ISM policy seems to work correctly, as we'll see later.

   ⚠️ `--.end` 

4. ISM rollover and alias policy

    * Push ISM policy to the Wazuh indexer cluster:
     
        > `"min_size": "1gb"` for testing purposes only

        ```bash
        curl -k -u admin:admin_password -X PUT "https://wazuh_indexer_ip_or_dns:9200/_plugins/_ism/policies/wazuh_rollover_policy?pretty" -H 'Content-Type: application/json' -d'
        {
          "policy": {
            "description": "Wazuh rollover and alias policy",
            "default_state": "rollover",
            "states": [
              {
                "name": "rollover",
                "actions": [
                  {
                    "rollover": {
                      "min_size": "1gb",
                    }
                  }
                ],
                "transitions": []
              }
            ],
            "ism_template": {
              "index_patterns": ["wazuh-*"],
              "priority": "50"
            }
          }
        }'
        ```

    * Create initial index and quickstart the rolling process:

        ```bash
        curl -k -u admin:admin_password -X PUT "https://wazuh_indexer_ip_or_dns:9200/%3Cwazuh-alerts-4.x-%7Bnow%2Fd%7D-000001%3E?pretty" -H 'Content-Type: application/json' -d'
        {
          "aliases": {
            "wazuh-alerts": {
              "is_write_index": true
            }
          }
        }
        '
        ```

5. Start the Wazuh cluster

    Note: The steps in this section must be executed in all of the Wazuh managers in the environment.

    * Start the Wazuh manager:

        ```bash
        systemctl start wazuh-manager
        ```


### Managed indices

In the UI, we can check the ISM policy and its managed indices inside the ISM plugin.

![image](https://github.com/wazuh/wazuh/assets/15186973/4925704e-a4f9-4b3a-91d0-21d1849222a1)
Screenshot 1 .- _Active_ ISM policies_

![image](https://github.com/wazuh/wazuh/assets/15186973/3c3fefa5-60c5-4d00-b33d-14251a9b2874)
Screenshot 2 .- _`wazuh-ism` policy details_

![image](https://github.com/wazuh/wazuh/assets/15186973/7af17516-595c-4c17-965a-333a91f9b405)
Screenshot 3 .- _Managed indices by the `wazuh-ism` policy_

```json
{
    "message": "Pending rollover of index [index=wazuh-alerts-4.x-2023.09.22-000001]",
    "conditions": {
        "min_size": {
            "condition": "1gb",
            "current": "29.2kb"
        }
    }
}
```
_Additonal info about the managed index_

### Forcing / testing the rollover

Using the `wazuh-alerts-generator` tool developed by the @wazuh/frontend (kudos to @Desvelao), we can index data into the indices to test the ISM policy. The rollover should be triggered automatically when the current index (`wazuh-alerts-4.x-2023.09.22-000001`) reaches 1GB.

**Comment by AlexRuiz7** [comment]
![Uploading image.png…]()

**Comment by AlexRuiz7** [comment]
```json
{
    "message": "Successfully rolled over index [index=wazuh-alerts-4.x-2023.09.25-000001]",
    "conditions": {
        "min_size": {
            "condition": "250mb",
            "current": "267mb"
        }
    }
}
```

**Comment by AlexRuiz7** [comment]
Temporarily pausing this issue due to priorities.

The ISM policy for rollover seems to work as expected. However, there are several things left to define:

- Whether to apply this policy to other indices: `wazuh-monitoring`, `wazuh-statistics`, ...
- Whether to keep the date of creation in the index name.
- Policy's lifecycle: what happens during an upgrade.
- Appropriate index's size condition for rollover.
- Appropriate sharding.

**Comment by AlexRuiz7** [comment]
I did some tests to check if it was possible to enable **rollover using Filebeat**. The test proved this method to be **ineffective**.

These are the settings used in the `filebeat.yml` file:

```yaml
setup.ilm.overwrite: true
setup.ilm.enabled: auto
setup.ilm.rollover_alias: 'wazuh-alerts'
setup.ilm.policy_name: 'wazuh-ism'
setup.ilm.policy_file: '/etc/filebeat/wazuh-ism.json'
```

Where the content of `wazuh-ism.json` file is:

```json
{
  "policy": {
    "description": "Wazuh rollover and alias policy",
    "default_state": "rollover",
    "states": [
      {
        "name": "rollover",
        "actions": [
          {
            "rollover": {
              "min_size": "250mb"
            }
          }
        ],
        "transitions": []
      }
    ],
    "ism_template": {
      "index_patterns": ["wazuh-alerts-*"],
      "priority": "50"
    }
  }
}
```

Reloaded Filebeat with:

```bash
filebeat setup --pipelines
filebeat setup --index-management
```

Kicked-off the rollover with:

```bash
curl -k -u admin:admin_password -X PUT "https://wazuh_indexer_ip_or_dns:9200/%3Cwazuh-alerts-4.x-%7Bnow%2Fd%7D-000001%3E?pretty" -H 'Content-Type: application/json' -d'
{
  "aliases": {
    "wazuh-alerts": {
      "is_write_index": true
    }
  }
}
'
```

These are the logs:

```log
[root@rhel7 vagrant]# tail -f /var/log/filebeat/filebeat
2023-10-02T12:40:05.717Z        INFO    [index-management]      idxmgmt/std.go:184      Set output.elasticsearch.index to 'wazuh-alerts' as ILM is enabled.
2023-10-02T12:40:05.719Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://127.0.0.1:9200
2023-10-02T12:40:05.719Z        INFO    [publisher]     pipeline/module.go:113  Beat name: rhel7.localdomain
2023-10-02T12:40:05.722Z        INFO    beater/filebeat.go:117  Enabled modules/filesets: wazuh (alerts),  ()
2023-10-02T12:40:05.723Z        INFO    eslegclient/connection.go:99    elasticsearch url: https://127.0.0.1:9200
2023-10-02T12:40:05.744Z        INFO    [esclientleg]   eslegclient/connection.go:314   Attempting to connect to Elasticsearch version 7.10.2
2023-10-02T12:40:05.749Z        INFO    template/load.go:183    Existing template will be overwritten, as overwrite is enabled.
2023-10-02T12:40:05.796Z        INFO    template/load.go:117    Try loading template wazuh to Elasticsearch
2023-10-02T12:40:05.857Z        INFO    template/load.go:109    template with name 'wazuh' loaded.
2023-10-02T12:40:05.857Z        INFO    [index-management]      idxmgmt/std.go:298      Loaded index template.
```

And this is the result:

![image](https://github.com/wazuh/wazuh/assets/15186973/70fc6844-aa47-4a46-9dbc-b783f19fede8)


**Summary:** Filebeat and ISM are not compatible. The ISM policy must be created as described in the comments above.

**Comment by AlexRuiz7** [comment]
I had a meeting with @wazuh-cloud-cicd leaders to chat about this feature, as they are using ISM policies for automatic rollover of the indices in cloud environments for a long time.

From that meeting, we extracted the following requirements and rollover conditions:

- Rollover conditions (in cloud environments):
  - `min_shard_primary_size: 25gb`
  - `min_index_age: 7d`
  - `min_doc_count: 2100000000`

The rollover action will be triggered if one of the primary shards of the index reaches 25gb, if the index reached 2 billion documents or if it is 7 days old, whatever that happens first. The shard size matches the initial requirement of the ISM. Additionally, Cloud organizes the indexes by weeks instead of days. This condition makes sense to me so, I will add it too. Finally, the 2.1 billion documents condition is due to a limitation of OpenSearch / ElasticSearch, as this is the maximum value of documents allowed. This condition is quite unlikely to happen, but it represents an edge case that can lead to a critical failure of the Indexer, so we'll add it just in case.

- Additional requirements:
  - Easy to customize.
  - Not modifiable by clients (cloud users).

This is a functional requirement for Cloud, however, although it's very desirable, and it's a good practice to provide this flexibility, the conditions explained above are unlikely to change. This represents a non-functional requirement for this feature, and will be taken into account during the design.
Moreover, the second requirement is perfectly possible using [roles](https://opensearch.org/docs/latest/security/access-control/permissions/#index-state-management-permissions). This also represents a non-functional requirement as it's not directly related with the ISM policy, but to a Cloud specific condition. We'll carefully study and document the required roles and permissions to achieve this, so it can be used both by Cloud and by on-premise users.

**Comment by AlexRuiz7** [comment]
### ISM policy prototype 

```
{
  "policy": {
    "description": "Wazuh rollover and alias policy",
    "default_state": "active",
    "states": [
      {
        "name": "active",
        "actions": [
          {
            "rollover": {
              "min_primary_shard_size": "${SHARD_SIZE}gb",
              "min_index_age": "${MIN_INDEX_AGE}",
              "min_doc_count": "${rollover_min_docs}"
            }
          }
        ]
      }
    ],
    "ism_template": {
      "index_patterns": ${ISM_INDEX_PATTERNS},
      "priority": "${ISM_PRIORITY}"
    }
  }
}
```

where the capitalized values come from a settings file in `yml` format for easy customization of the ISM policy.

```yml
---
version: '0.1'
name: Wazuh ISM policy for auto-rollover 
settings:
  - name: MIN_INDEX_AGE
    value: '7d'
  - name: SHARD_SIZE
    value: '25'
  - name: DOCS_PER_SHARD
    value: '2100000000'
  - name: ISM_INDEX_PATTERNS
    value: '["wazuh-alerts*","wazuh-archives*","-wazuh-alerts-4.x-sample*"]'
  - name: ISM_PRIORITY
    value: '50'
  - name: ISM_HISTORY_RETENTION
    value: '7d'
```

Finally, `rollover_min_docs = DOCS_PER_SHARD * shards`. As explained before, each shard can store up to 2³1 documents, so we multiply this value by the number of shards in the index (`wazuh-alerts` use [3 shards](https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json#L9) by default).

**Comment by AlexRuiz7** [comment]
### Fine-grained access control

As stated before, the access to the ISM plugin can be controlled using [permissions](https://opensearch.org/docs/latest/security/access-control/permissions/#index-state-management-permissions).

We'll provide a new role to manage ISM policies, so users can simply map internal users to this role to grant access to the ISM plugin. The ISM plugin itself cannot be hidden, as there is [no such feature](https://github.com/opensearch-project/security-dashboards-plugin/issues/857) in OpenSearch Dashboards.

This role will be shipped with the official package, which is currently managed by the @wazuh/cicd team. The @wazuh/frontend will need this role in order to upload the ISM policy during the app's start, and @wazuh-cloud-cicd will probably require this role as well to control the access to ISM.

### Pre-built role 

We'll create a role to grant permissions to all the ISM API permissions: `cluster:admin/opendistro/ism/*`

Note: the internal user currently used by the app (`kibanaserver`), does not have permissions to access the ISM API.

<details><summary>Details</summary>
<p>


```bash
curl -X GET https://localhost:9200/_plugins/_ism/explain/wazuh-alerts-* -k -u "kibanaserver:Dc.8NC4CKLsnJzHfkX20AyJGZIjcN3Pm"
```
```json
{
    "error": {
        "root_cause": [
            {
                "type": "security_exception",
                "reason": "no permissions for [cluster:admin/opendistro/ism/managedindex/explain] and User [name=kibanaserver, backend_roles=[], requestedTenant=null]"
            }
        ],
        "type": "security_exception",
        "reason": "no permissions for [cluster:admin/opendistro/ism/managedindex/explain] and User [name=kibanaserver, backend_roles=[], requestedTenant=null]"
    },
    "status": 403
}
```

</p>
</details> 


The new role will fix this problem.

#### Using the UI

1. Go to the Security plugin.
2. Click on `Create new role`.
3. Name it `manage_ism`.
4. In `Cluster permissions`, Click on `Create new permission group`
5. A new tab will open. Click on `Create action group`, then `Create from blank`. Name if, for example, `manage_ism` and then type `cluster:admin/opendistro/ism/*` in the permissions text box. Click on create.
6. Assign the new permission group to the role.
7. Click on create.
8. In the recently created role's view, click on `Mapped users`, then on `Manage mapping and map the `kibanaserver` user to the role. Click on `Map`.

Now, the `kibanaserver` user has permissions to use the ISM API.

<details><summary>Details</summary>
<p>


```bash
curl -X GET https://localhost:9200/_plugins/_ism/explain/wazuh-alerts-* -k -u "kibanaserver:Dc.8NC4CKLsnJzHfkX20AyJGZIjcN3Pm"
```

```json
{
  "wazuh-alerts-4.x-2023.10.23":
    {
      "index.plugins.index_state_management.policy_id": "wazuh_rollover_policy",
      "index.opendistro.index_state_management.policy_id": "wazuh_rollover_policy",
      "index": "wazuh-alerts-4.x-2023.10.23",
      "index_uuid": "3-tCW-SnQ7Wz0ZEy7DZFdA",
      "policy_id": "wazuh_rollover_policy",
      "policy_seq_no": -2,
      "policy_primary_term": 0,
      "rolled_over": false,
      "index_creation_date": 1698055160679,
      "state": { "name": "active", "start_time": 1698055509949 },
      "action":
        {
          "name": "rollover",
          "start_time": 1698055931551,
          "index": 0,
          "failed": true,
          "consumed_retries": 3,
          "last_retry_time": 1698056388264,
        },
      "step":
        {
          "name": "attempt_rollover",
          "start_time": 1698055931552,
          "step_status": "failed",
        },
      "retry_info": { "failed": false, "consumed_retries": 0 },
      "info":
        {
          "message": "Missing rollover_alias index setting [index=wazuh-alerts-4.x-2023.10.23]",
        },
      "enabled": false,
    },
  "wazuh-alerts-4.x-2023.10.22":
    {
      "index.plugins.index_state_management.policy_id": null,
      "index.opendistro.index_state_management.policy_id": null,
      "enabled": null,
    },
  "total_managed_indices": 1,
}
```

</p>
</details> 

#### Using the API

1. Create the action group
```
PUT _plugins/_security/api/actiongroups/test2
{
  "allowed_actions": [
    "cluster:admin/opendistro/ism/*"
  ]
}
```
3. Create the role
4. Create 


#### Using the YAML files (not recommended)

This method is useful only for initial configuration.

**Comment by AlexRuiz7** [comment]
We've found a race condition. See .

**Comment by AlexRuiz7** [comment]
### E2E testing

<details><summary>Vagrantfile</summary>
<p>

```ruby
Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "4"
    end

    config.vm.define "node1" do |node1|
        node1.vm.box = "generic/rhel7"
        node1.vm.synced_folder ".", "/vagrant"
        node1.vm.network "private_network", ip: "192.168.56.10"
        
        node1.vm.provision "shell", inline: <<-SHELL
            # Disable firewall
            systemctl stop firewalld
            systemctl disable firewalld
        SHELL
    end
    
    config.vm.define "node2" do |node2|
        node2.vm.box = "generic/rhel7"
        node2.vm.synced_folder ".", "/vagrant"
        node2.vm.network "private_network", ip: "192.168.56.11"

        node2.vm.provision "shell", inline: <<-SHELL
            # Disable firewall
            systemctl stop firewalld
            systemctl disable firewalld
        SHELL
    end
end
```

</p>
</details> 


1. Create `wazuh-install.sh` from the 4.8.0 branch

    ```console
    git checkout 4.8.0
    bash unattended_installer/builder.sh -i -d staging
    ```

2. Create rpm package from the 4.8.0 branch

    ```console
    bash stack/indexer/rpm/build_package.sh -s /tmp
    ```

3. Generate config files

    ```console
     bash wazuh-install.sh --generate-config-files
    10/11/2023 13:44:02 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
    10/11/2023 13:44:02 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    10/11/2023 13:44:14 INFO: Verifying that your system meets the recommended minimum hardware requirements.
    10/11/2023 13:44:14 INFO: --- Configuration files ---
    10/11/2023 13:44:14 INFO: Generating configuration files.
    10/11/2023 13:44:15 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
    ```

4. Install indexer node-1

    ```console
    bash wazuh-install.sh --wazuh-indexer node-1
    10/11/2023 13:47:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
    10/11/2023 13:47:33 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    10/11/2023 13:47:44 INFO: Verifying that your system meets the recommended minimum hardware requirements.
    10/11/2023 13:47:47 INFO: Wazuh development repository added.
    10/11/2023 13:47:48 INFO: --- Wazuh indexer ---
    10/11/2023 13:47:48 INFO: Starting Wazuh indexer installation.
    10/11/2023 13:50:45 INFO: Wazuh indexer installation finished.
    10/11/2023 13:50:45 INFO: Wazuh indexer post-install configuration finished.
    10/11/2023 13:50:45 INFO: Starting service wazuh-indexer.
    10/11/2023 13:51:29 INFO: wazuh-indexer service started.
    10/11/2023 13:51:29 INFO: Initializing Wazuh indexer cluster security settings.
    10/11/2023 13:51:29 INFO: Wazuh indexer cluster initialized.
    10/11/2023 13:51:29 INFO: Installation finished.
    ```

5. Install indexer node-2

    ```console
    bash wazuh-install.sh --wazuh-indexer node-2
    10/11/2023 13:49:48 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
    10/11/2023 13:49:48 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    10/11/2023 13:50:00 INFO: Verifying that your system meets the recommended minimum hardware requirements.
    10/11/2023 13:50:03 INFO: Wazuh development repository added.
    10/11/2023 13:50:04 INFO: --- Wazuh indexer ---
    10/11/2023 13:50:04 INFO: Starting Wazuh indexer installation.
    10/11/2023 13:53:10 INFO: Wazuh indexer installation finished.
    10/11/2023 13:53:10 INFO: Wazuh indexer post-install configuration finished.
    10/11/2023 13:53:10 INFO: Starting service wazuh-indexer.
    10/11/2023 13:53:24 INFO: wazuh-indexer service started.
    10/11/2023 13:53:24 INFO: Initializing Wazuh indexer cluster security settings.
    10/11/2023 13:53:24 INFO: Wazuh indexer cluster initialized.
    10/11/2023 13:53:24 INFO: Installation finished.
    ```

6. Initialize cluster

    ```console
    bash wazuh-install.sh --start-cluster
    10/11/2023 14:04:27 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
    10/11/2023 14:04:27 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    10/11/2023 14:04:39 INFO: Verifying that your system meets the recommended minimum hardware requirements.
    10/11/2023 14:04:51 INFO: Wazuh indexer cluster security configuration initialized.
    10/11/2023 14:04:53 INFO: The Wazuh indexer cluster ISM initialized.
    10/11/2023 14:05:55 INFO: Updating the internal users.
    10/11/2023 14:05:57 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
    10/11/2023 14:06:06 INFO: Wazuh indexer cluster started.
    ```

7. Check rollover policy

```console
curl -X GET https://192.168.56.11:9200/_plugins/_ism/explain?pretty -k -u admin:xA*XezzKolMmhRBofw?*kOFA.Frr7BGt
{
  "wazuh-alerts-4.x-2023.11.10-000001" : {
    "index.plugins.index_state_management.policy_id" : "rollover_policy",
    "index.opendistro.index_state_management.policy_id" : "rollover_policy",
    "index" : "wazuh-alerts-4.x-2023.11.10-000001",
    "index_uuid" : "aZwswJFxQI2kQT5c_p55sw",
    "policy_id" : "rollover_policy",
    "policy_seq_no" : -2,
    "policy_primary_term" : 0,
    "rolled_over" : false,
    "index_creation_date" : 1699625093269,
    "state" : {
      "name" : "active",
      "start_time" : 1699625441488
    },
    "action" : {
      "name" : "rollover",
      "start_time" : 1699625783263,
      "index" : 0,
      "failed" : false,
      "consumed_retries" : 0,
      "last_retry_time" : 0
    },
    "step" : {
      "name" : "attempt_rollover",
      "start_time" : 1699625783265,
      "step_status" : "condition_not_met"
    },
    "retry_info" : {
      "failed" : false,
      "consumed_retries" : 0
    },
    "info" : {
      "message" : "Pending rollover of index [index=wazuh-alerts-4.x-2023.11.10-000001]",
      "conditions" : {
        "min_primary_shard_size" : {
          "condition" : "25gb",
          "current" : "0b",
          "shard" : 0
        },
        "min_index_age" : {
          "condition" : "7d",
          "current" : "57.5m",
          "creationDate" : 1699625093269
        },
        "min_doc_count" : {
          "condition" : 200000000,
          "current" : 0
        }
      }
    },
    "enabled" : true
  },
  "wazuh-archives-4.x-2023.11.10-000001" : {
    "index.plugins.index_state_management.policy_id" : "rollover_policy",
    "index.opendistro.index_state_management.policy_id" : "rollover_policy",
    "index" : "wazuh-archives-4.x-2023.11.10-000001",
    "index_uuid" : "O9VRPfz8TwaROAO-tB6pDw",
    "policy_id" : "rollover_policy",
    "policy_seq_no" : -2,
    "policy_primary_term" : 0,
    "rolled_over" : false,
    "index_creation_date" : 1699625093593,
    "state" : {
      "name" : "active",
      "start_time" : 1699625427540
    },
    "action" : {
      "name" : "rollover",
      "start_time" : 1699625866044,
      "index" : 0,
      "failed" : false,
      "consumed_retries" : 0,
      "last_retry_time" : 0
    },
    "step" : {
      "name" : "attempt_rollover",
      "start_time" : 1699625866044,
      "step_status" : "condition_not_met"
    },
    "retry_info" : {
      "failed" : false,
      "consumed_retries" : 0
    },
    "info" : {
      "message" : "Pending rollover of index [index=wazuh-archives-4.x-2023.11.10-000001]",
      "conditions" : {
        "min_primary_shard_size" : {
          "condition" : "25gb",
          "current" : "0b",
          "shard" : 0
        },
        "min_index_age" : {
          "condition" : "7d",
          "current" : "55m",
          "creationDate" : 1699625093593
        },
        "min_doc_count" : {
          "condition" : 200000000,
          "current" : 0
        }
      }
    },
    "enabled" : true
  },
  "total_managed_indices" : 2
}
```

**Comment by AlexRuiz7** [comment]
The feature will be rolled back for 4.8.0 and be revisited on 5.0.0.

The effort to roll back the feature will be tracked in https://github.com/wazuh/internal-devel-requests/issues/781.
