### ISSUE TITLE
Custom decoder is not working

### ISSUE THREAD

**Issue by 23uk** [wazuh/wazuh#18994]
|Wazuh version| Component | Action type |
| v4.5.2 | Decoders | Error |

Hello,
When adding a new decoder, decoding does not occur.

/var/ossec/etc/decoders/local_decoder.xml contains:

\<decoder name="yum-decoder"\>
    \<prematch\>^\w\w\w \d\d \d\d:\d\d:\d\d Installed|\</prematch\>
    \<prematch\>^\w\w\w \d\d \d\d:\d\d:\d\d Erased\</prematch\>
    \<regex\>^\w\w\w \d\d \d\d:\d\d:\d\d (\S+):\s(\S+)\</regex\>
    \<order\>yum_status, package\</order\>
\</decoder\>

/var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.5.2
Type one log per line

Sep 13 12:28:56 Installed: zip-3.0-11.el7.x86_64

**Phase 1: Completed pre-decoding.
        full event: 'Sep 13 12:28:56 Installed: zip-3.0-11.el7.x86_64'
        timestamp: 'Sep 13 12:28:56'
        hostname: 'Installed:'
        program_name: 'Installed'

**Phase 2: Completed decoding.
        No decoder matched.

but I expect successful decoding... I also checked the correctness of the regular expression:

root@wazuh:/var/ossec/ruleset/decoders# /var/ossec/bin/wazuh-regex '^\w\w\w \d\d \d\d:\d\d:\d\d (\S+):\s(\S+)'
Sep 13 12:28:56 Installed: zip-3.0-11.el7.x86_64
+OSRegex_Execute: Sep 13 12:28:56 Installed: zip-3.0-11.el7.x86_64
 -Substring: Installed
 -Substring: zip-3.0-11.el7.x86_64
+OS_Regex       : Sep 13 12:28:56 Installed: zip-3.0-11.el7.x86_64

All my old decoding rules stopped working too. Has anyone encountered a similar problem?

**Comment by 23uk** [comment]
it works with parent decoder:

<decoder name="yum-decoder">
    <program_name>Installed|Erased</program_name>
</decoder>

<decoder name="yum-decoder-child">
    <prematch>^\w\w\w \d\d \d\d:\d\d:\d\d Installed|</prematch>
    <prematch>^\w\w\w \d\d \d\d:\d\d:\d\d Erased</prematch>
    <regex>^\w\w\w \d\d \d\d:\d\d:\d\d (\S+):\s(\S+)</regex>
    <order>yum_status, package</order>
</decoder>

**Comment by EstebanAA019** [comment]
I have a similar problem in Wazuh, referring to the level 2 rule, I made a decoder that seeks to extract the data from the full_log, since I can only see that data in Discover, but not in a table of Visualize for example, since I don't even see the "full_log" option in the Buckets part. So I made a decoder like this: 
<decoder>
  <group>firewall_logs</group>
  <decode>
    <type>key_value</type>
    <field>full_log</field>
    <separator>"</separator>
    <kv_sep>=</kv_sep>
    <ignore_fields>log_occurrence</ignore_fields> 
  </decode>
</decoder>

When I test it in the decoder test I get this: 

**Phase 1: Completed pre-decoding.
	full event: 'device_name="SFW" timestamp="2024-11-06T17:43:58-0300" device_model="" device_serial_id="" log_id="010202601001" log_type="Firewall" log_component="Invalid Traffic" log_subtype="Denied" log_version=1 severity="Information" fw_rule_id="N/A" nat_rule_id="0" fw_rule_type="NETWORK" ether_type="IPv4 (0x0800)" in_interface="vxlan7.100" src_mac="" src_ip="" src_country="R1" dst_ip="" dst_country="R1" protocol="TCP" src_port=55768 dst_port=443 hb_status="No Heartbeat" message="Invalid packet." app_resolved_by="Signature" app_is_cloud="FALSE" qualifier="New" in_display_interface="vxlan7.100" log_occurrence="1"'

**Phase 2: Completed decoding.
	No decoder matched.

**Phase 3: Completed filtering (rules).
	id: '1002'
	level: '2'
	description: 'Unknown problem somewhere in the system.'
	groups: '["syslog","errors"]'
	firedtimes: '1'
	gpg13: '["4.3"]'
	mail: 'false'
**Alert to be generated.
