### ISSUE TITLE
Need better message to identify auto-provisioned agents

### ISSUE THREAD

**Issue by mathieupythian** [wazuh/wazuh#190]
Situation:

When doing auto-provisioning of Wazuh Agents, if for whatever reason the agent is using an invalid key, then you'll get this message in the Wazuh Manager logs: "ERROR: (1408): Invalid ID 002 for the source ip: 'x.x.x.x'"

This message is useful in many cases, however when the IP is a load balancer (masking the real IP of the agent), then it is not possible to know which machine or agent is mis-configured.  And when you have 100s of machines, then it can be a daunting task to figure out which one it is.

A solution could be to add the 'name' of the agent (which, as far as I can tell, is in the message that is being tossed away). In which case, the code could be modified to decrypt the message and retrieve the name before logging the message. (src/remoted/secure.c)

Other people affected by this?

Are there other ways to easily identify the mis-configured agent(s) that try to call home?

Wazuh is great!

**Comment by crolopez** [comment]
Hi @mathieupythian,

We understand your situation and will add that feature in a future release.

Thanks for the suggestion!
Best regards.

**Comment by crolopez** [comment]
Hi @mathieupythian,

The agent name has already been added. You can see the commit in: https://github.com/wazuh/wazuh/commit/837caba54c0602194032e794fca7b7b44e8fad7d

Best regards.
