### ISSUE TITLE
/bin/diff file falsely recognized as malicious

### ISSUE THREAD

**Issue by paivao** [wazuh/wazuh#19000]
On working with Wazuh, I found out that /bin/diff is repeatedly recognized as infected by rootkit.
Analysing the regex on the rule below, i found out what is the problem.

https://github.com/wazuh/wazuh/blob/17469f88206a90e54e0d5f6ee81a0a04996ada1f/ruleset/rootcheck/db/rootkit_trojans.txt#L43C34-L43C34

The problem is that new version of diff contain a reference to the `/dev/full` pseudo-device. And the rule triggers if any `/dev` file are on the executable, except by those starting by **n**, probably by referencing `/dev/null`.

My suggestion is to modify the rule from:
`bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh`
to:
`bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]|^/bin/.*sh`

**Comment by iasdeoupxe** [comment]
Looks like there are multiple issues about the same / similar message open:
- #19346
- #13278
- #11808

Could be possible that all have the same origin and some could be closed as duplicates.

**Comment by iasdeoupxe** [comment]
New PR which could solve this: #25634

**Comment by vikman90** [comment]
Hi all,

This issue has been fixed by @djosip:
- https://github.com/wazuh/wazuh/pull/25634
