### ISSUE TITLE
Refactor and migrate test_agentd_state

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#19005]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the agentd tests. The following files are involved:

```
test_agentd/
   ├── conftest.py
   └── test_agentd_state
                       ├──── data
                       |        └── config_templates
                       │        │           └── wazuh_conf.yaml
                       |        └── test_cases
                       │                    └── wazuh_state_tests.yaml
                       └── test_agentd_state.py

```

### Tasks:
- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (ie: internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.

### Current status - BLOCKED
Finished pending finish the other agents tests. Affected by: https://github.com/wazuh/wazuh/issues/17696#issuecomment-1784578288

**Comment by QU3B1M** [comment]
### RemotedSimulator improvement

A new PR directly to the `main` branch was created as hotfix for the `RemotedSImulator`, this PR includes the required changes to be able to get the message sent from the agent to the simulator and do the correspondent validations. 
- https://github.com/wazuh/qa-integration-framework/pull/35

**Comment by MarcelKemp** [comment]
- Done at https://github.com/wazuh/wazuh/issues/17696
