### ISSUE TITLE
Refactor and migrate test_agentd_state_config

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#19004]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the agentd tests. The following files are involved:

```
test_agentd/
   ├── conftest.py
   └── test_agentd_state_config
                       ├──── data
                       |        └── config_templates
                       │        │           └── wazuh_conf.yaml
                       |        └── test_cases
                       │                    └── wazuh_state_tests.yaml
                       └── test_agentd_state_config.py

```

### Tasks:
- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (ie: internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.

### Current status - BLOCKED
Note: In the implementation of this test, the fixture configure_local_internal_options, has been changed as discussed in this [thread](https://wazuh-team.slack.com/archives/C05LD04A1EE/p1691163200267009). Due to this modification, we should change this fixture call in other tests, to reduce the number of executions of it. 

Affected by https://github.com/wazuh/wazuh/issues/17696#issuecomment-1784578288

**Comment by MarcelKemp** [comment]
- Done at https://github.com/wazuh/wazuh/issues/17696
