### ISSUE TITLE
Compute and store group's shared folder file hashes

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#19010]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | core | Manager| Packages/Sources | All |

After investigating the source cause of the issues reported by the 4.6.0-alpha1 E2E tests documented in #18897, I detected two API endpoints that compute the md5 file hash of the files on the shared group's folders. These API endpoints also compute the "merged.mg" file hash value, and its file size depends on the files found in the same group's shared folder. The API endpoint response time is severely affected when large files are found in these folders and when the "merged.mg" files are large.

The feature request involves computing and storing the shared group's folder file hashes in advance. This new feature will improve the response time of the API endpoints that are currently calculating the md5 hash values on each request. 

The md5 hashes must be maintained in an SQLite DB or text file for each group's shared folder. The API endpoints will use these computed values to prepare the API response.

**Comment by Selutario** [comment]
Related: 
- https://github.com/wazuh/wazuh/issues/20942

In order for the dashboard to search for a field over all existing groups (efficiently), all fields must be stored in the DB. Currently, the DB only stores the name of each group:
```SQL
select * from `group` LIMIT 5;
id|name
1|default
2|test_group_0
3|test_group_1
4|test_group_2
5|test_group_3
```

The rest of the information displayed when using the API (mergedSum and configSum) is calculated on demand and during the call to the endpoint.

> `GET /groups`

```JSON
{
  "data": {
    "affected_items": [
      {
        "name": "test_group_0",
        "count": 0,
        "mergedSum": "ea7e13d92b38a038effbf29029b65967",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00"
      }
    ],
    "total_affected_items": 30001,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected groups information was returned",
  "error": 0
}
```

To search for a group with a specific mergedSum (for example), or sort the results based on some field, the API would have to obtain the entire list of groups, calculate all the hashes and search over this result, which is highly inefficient (+42s when there are 30k groups).

**Comment by davidjiglesias** [comment]
Since we believe this change will incorporate a bigger load to wazuh-db, we have decided to discard it.

**Comment by davidjiglesias** [comment]
We reopen the issue, which will only be continued if we can guarantee the same or better performance for wazuh-db after the changes. A specific benchmark and load test plan must be incorporated to accomplish that.

**Comment by LucioDonda** [comment]
After some reading of the issue and a sort-of superficial analysis I've come up with some doubts:
* Should we monitor, from now on, all shared directories and it's content and with each change also update the DB?
* To achieve this a possible approach would be to apply a directory monitoring, watching in real-time any change made in it? 
* With this approach both API endpoints [GET Groups](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_list_group) and [GET /groups/{groupname}/files](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_group_files) should now simply query the db. The only important point here is when will the checksum be calculated / updated. If this is done in real time we shouldn't worry by fetching outdated results, but if the approach is with a periodic update it will.
* Regarding **wazuh-db** load, If this can be implemented in a real-time approach, shared directory files are not normally modified, so this shouldn't change wdb performance very much. Bearing in mind the above case-scenario with 30k groups, this could affect the size of the DB itself.

Will continue investigating this.

c.c. @vikman90 @cborla

**Comment by LucioDonda** [comment]
As named above, there are two options to develop this issue:

## Periodic update:

Everytime **_share_reload_** interval ( by default 10 secconds) **_proccess_groups_** gets called:

`Remoted -> update_shared_files() -> c_files -> process_groups()`


``` diff
+++ b/src/remoted/manager.c
@@ -891,43 +891,45 @@ STATIC void process_groups() {
             continue;
         }
 
         group_t *group = NULL;
         if (group = OSHash_Get_ex(groups, entry->d_name), !group) {
             // New group
             os_calloc(1, sizeof(group_t), group);
             if (OSHash_Add_ex(groups, entry->d_name, group) != 2) {
                 os_free(group);
                 merror("Couldn't add group '%s' to hash table 'groups'", entry->d_name);
             } else {
                 group->name = strdup(entry->d_name);
                 c_group(entry->d_name, &group->f_time, &group->merged_sum, SHAREDCFG_DIR, !logr.nocmerged, false);
                 group->has_changed = true;
                 group->exists = true;
+                Insert_group_hash(group);
             }
         } else {
             OSHash *old_time = group->f_time;
             group->f_time = NULL;
             c_group(entry->d_name, &group->f_time, &group->merged_sum, SHAREDCFG_DIR, false, false);
             if (ftime_changed(old_time, group->f_time)) {
                 // Group has changed
                 if (!logr.nocmerged) {
                     OSHash_Clean(group->f_time, free_file_time);
                     c_group(entry->d_name, &group->f_time, &group->merged_sum, SHAREDCFG_DIR, true, false);
                 }
                 group->has_changed = true;
                 mdebug2("Group '%s' has changed.", group->name);
+                Update_group_hash(group);
             } else {
                 // Group didn't change
                 group->has_changed = false;
             }
             OSHash_Clean(old_time, free_file_time);
             group->exists = true;
         }
 
         free_strarray(subdir);
     }
 
     closedir(dp);
     return;
 }
 
```

In this function we can access the group names, the md5-sum and the _**merge.mg**_.
This would be a simpler approach and will leed us to avoid any additional implementation for directory scanning in real-time. Insert_group_hash(group): will, as it says, insert the md5-sum value to a new column
and Update_group_hash(group) will only refresh this value. 
The group argument already contains all the needed fields for this purpose and in both cases the _**merge.mg**_ value should be updated.

Some doubts regarding this approach:
* Should we return all the type of hash algorithms defined by this argument in the [api docs](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_list_group):
![image](https://github.com/wazuh/wazuh/assets/95248059/01ddc8ee-6720-424d-b8c9-1b7dd5fada60)
* We should reuse the group table on the global.db. Can this affect any other module by adding X columns (each one for the hash type needed) ?
* Should the same be implemented for multigroups?

Possible Issue:
* As named in the previous comment, fetching a hash value for a group in between the time period of time_reload right after changing any file on the shared directory will result in non-real values. But in those cases the hash will be updated alongside the agents memeber of that group. Worst case scenario (under the default values) will take 10secconds.

## Real-time update:

_WIP_

**Comment by vikman90** [comment]
Closing this issue.
