### ISSUE TITLE
Wazuh rule for specific group of agent

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#19019]
Hi,

Is it possible to add and modify existent rules for groups of agents? Suppose I want to create a group for each client. Where do I specify the rules for each client group?

Best regards,

**Comment by davidcr01** [comment]
Unfortunately, it is not possible to filter rules by agent group at the moment as the rule engine has no awareness of agent groups. Here are some options with which you can achieve something similar:

- Use labels: It is possible to add labels to the agent's groups that will be applied to every alert triggered by those agents. To do that you can apply a centralized configuration to set up the label for each specific group.
- Once that is done you can verify the new alerts from those agents and confirm that the label is applied. Then create custom rules to trigger matching labels.
- Use a specific field: If you have a specific field in the alert that is common to all the agents of a group, you can edit the rules only to be triggered when that field is expected. 

For example: if all the agent hostnames of the group "lab" start with "lab-" and you want to filter the rule 5701, you can create a child rule similar to this:
```
  <rule id="100002" level="8">
     <if_sid>5701</if_sid>
     <hostname type="PCRE2">lab-.+</hostname>
     <description>sshd: Possible attack on the ssh server </description>
     <description>(or version gathering). - Known agetn</description>
  </rule>
```
This way the rule will only be triggered when the agent hostname starts with "lab-".

Setting the label: 
![image](https://github.com/wazuh/community/assets/72193239/4a439c3d-2616-4fbb-9dc4-2dd9e6008855)


Checking the alerts with the label: 
![image](https://github.com/wazuh/community/assets/72193239/ff015c09-c64a-4b55-91b4-12921ef191e7)


As you can see in the previous image, agents starting with "lab-" trigger the custom rule, while agents that don't start with "lab-" trigger the original rule.
You can find more information about labels and custom rules on the following links:

- [Rules syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html)
- [Agent labels](https://documentation.wazuh.com/current/user-manual/capabilities/labels.html)
- [Creating decoders and rules from scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/)

**Comment by thanvantrong** [comment]
Hi,

I read the document in rule syntax, that **hostname** is descripted below
![image](https://github.com/wazuh/wazuh/assets/82009148/541203d0-0439-4d95-ae4f-1f1c105a7c7d)
It means that **hostname** is value of **agent_name** in _ossec.conf_ in agent side.
![image](https://github.com/wazuh/wazuh/assets/82009148/0a25e942-23a5-44b3-8680-4c88e0b9be37)


Best Regards,
