### ISSUE TITLE
Using agent.id or agent.lables in custom rules

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#19020]
Hi,

I want create some custom rules for specific agent_id or agent_id with specific labels
How can i solve this problem?

Best Regards,

**Comment by davidcr01** [comment]
Hello.

For custom rules for an agent, you can try using the `<location>` tag. This tag is sort of a hydrid header that contains not just where the logs is coming from but also other data like hostname and IP address. Take a look at the example below,
```
<rule id="2502" level="10">
    <match>more authentication failures;|REPEATED login failures</match>
    <description>syslog: User missed the password more than one time</description>
    <var name="agnt">agent1</var>
    <location>$agnt</location>
    <mitre>
      <id>T1110</id>
    </mitre>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.8,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
``` 

This rule will therefore work for only agent - agent1. 
You can get more information about the `<location>` tag in the following documentation: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#location
