### ISSUE TITLE
"Error 0x2.  You must be root to use this script" when attempting to install agent on Haiku

### ISSUE THREAD

**Issue by Coldfirex** [wazuh/wazuh#19036]
4.5.2 agent source
Haiku hrev57257
Ran ./install.sh
Error 0x2.  You must be root to use this script

whoami returns: user

This user has full admin permissions.

**Comment by pereyra-m** [comment]
Hello @Coldfirex !

Please, try `sudo ./install.sh`

Regards.

**Comment by pereyra-m** [comment]
Hi again @Coldfirex !

In that case, you can try removing these lines from `install.sh` as a workaround

https://github.com/wazuh/wazuh/blob/dbe37047128509cbf6b909ef7aa15feba42048d8/install.sh#L840-L842

**Comment by Coldfirex** [comment]
That worked, thanks!

**Comment by Dwordcito** [comment]
We hope we have helped you, your collaboration with the community is very important, if you have another question/problem we hope for a new issue!
