### ISSUE TITLE
Implement a read interface to get vulnerability description information.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#19042]
## Description

This issue focuses on implementing a read interface to retrieve data from the vulnerability manager feed. The vulnerability manager feed contains the stored vulnerability data that needs to be accessed by other components or systems. A read interface should be implemented to query and retrieve vulnerability descriptions to enable seamless access to this data.

## Expected

After completing this issue, the following outcomes are expected:

- Implement a read interface in the vulnerability feed manager to get vulnerabilities descriptions.
- A well-defined set of methods or functions that allow users to query and retrieve package translation data.
- Proper handling of data retrieval requests, including error handling and response formatting.
- Comprehensive testing of the read interface to ensure its functionality and reliability.

Interface:
VulnerabilityDescription getVulnerabiltyDescriptiveInformation(std::string_view cveId)

Schema flat buffer:
```
namespace VulnerabilityDescription;

table VulnerabilityDescription {
  classification: string;
  description: string;
  severity: string;
  scoreVersion: string;
  scoreBase: float;
  reference: string;
}

root_type VulnerabilityDescription;
```

#### Database information
Key: CVEID
Value: FlatBuffer
Search/select-> CVEID

## DoD (Definition of Done)

To consider this issue completed, the following tasks should be accomplished:

- [x] Implement the necessary methods or functions to retrieve that descriptive information.
- [x] Perform thorough testing to ensure the correctness and reliability of the read interface.
- [x] Handle any potential errors or exceptions during data retrieval.

**Comment by matias-braida** [comment]
Working on the DatabaseFeedManager::getVulnerabiltyDescriptiveInformation method.
Have to read about flatbuffers and rocksdb since it is the first issue using them.
