### ISSUE TITLE
Add data to the database feed manager of the translation of package name candidates.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#19047]
## Description

Implement an interface with the capability to create or modify CPE translations for packages that do not have a standard name (for now this seems to affect only Windows systems)

## Expected

After completing this issue, the following outcomes are expected:

- Implement an interface to store CPE translations.
- Proper handling of data retrieval requests, including error handling and response formatting.
- Comprehensive testing of the read interface to ensure its functionality and reliability.

## DoD (Definition of Done)

To consider this issue completed, the following tasks should be accomplished:

- [x] Implement the necessary methods or functions to store CPE translations.
- [x] Perform thorough testing to ensure the correctness and reliability.
- [x] Handle any potential errors or exceptions during data retrieval.

**Comment by MiguelazoDS** [comment]
## Conclusions after team call 

### RocksDB entries

From the current dictionary used to translate CPEs from system inventory to NVD, we have for example.

<details><summary>Expand</summary>

```json 
        {
            "target": "windows",
            "source": {
                "vendor": [
                    "Microsoft Corporation"
                ],
                "product": [
                    "Microsoft Edge"
                ],
                "version": []
            },
            "translation": {
                "vendor": [
                    "microsoft"
                ],
                "product": [
                    "edge_chromium"
                ],
                "version": []
            },
            "action": [
                "replace_vendor",
                "replace_product"
            ]
        }
```

</details>

<details><summary>Expand</summary>

```json 
 {
            "target": "windows",
            "source": {
                "vendor": [
                    "www\\.wireshark\\.org"
                ],
                "product": [
                    "Wireshark"
                ],
                "version": []
            },
            "translation": {
                "vendor": [
                    "wireshark"
                ],
                "product": [
                    "wireshark"
                ],
                "version": []
            },
            "action": [
                "replace_vendor",
                "replace_product"
            ]
        }
```

</details>

We define a flatbuffer as follows 

<details><summary>Expand</summary>

```
namespace NSVulnerabilityScanner;

table TranslationInfo {
  vendor:[string];
  product:[string];
  version:[string];
}

table TranslationEntry {
  action:[string];
  source:TranslationInfo;
  target:string;
  translation:TranslationInfo;
}

root_type TranslationEntry;

```

</details>

Each entry will be stored in a RocksDB database using an identifier (i.e WT-x)

### Create and update entries 

#### Create 

<details><summary>Expand</summary>

```json
{
  "data": [
    {
      "offset": 5,
      "type": "create",
      "version": 1,
      "context": "translation",
      "resource": "WT-3",
      "payload": {
        "target": "windows",
        "source": {
          "vendor": [
            "^The Apache Software"
          ],
          "product": [
            "^Apache Tomcat.*"
          ],
          "version": []
        },
        "translation": {
          "vendor": [
            "apache"
          ],
          "product": [
            "tomcat"
          ],
          "version": []
        },
        "action": [
          "replace_vendor",
          "replace_product"
        ]
      }
    }
  ]
}
```

</details>

#### Update 

<details><summary>Expand</summary>

```json
{
  "resource": "WT-1",
  "operations": [
    {
      "op": "replace",
      "path": "/source/version/0",
      "value": "^Microsoft ASP.NET Core"
    },
    {
      "op": "replace",
      "path": "/source/product/0",
      "value": "^Microsoft ASP.NET Core"
    }
  ]
}
```

</details>

**Comment by MiguelazoDS** [comment]
# Redefinitions 

After a call with the team the keys "vendor", "version", and "product" are no longer arrays, just a single string. 

So this 

```
table TranslationInfo {
  vendor:[string];
  product:[string];
  version:[string];
}
```

Became this 

```
table TranslationInfo {
  vendor:string;
  product:string;
  version:string;
}
```

CC: @GabrielEValenzuela @Dwordcito
