### ISSUE TITLE
Add data to the database feed manager of vulnerability description information.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#19045]
## Description

The database feed management is responsible for receiving the newly published content and keeping the local data synced with the new changes.
This issue requires that all the "description" fields of the CVE 5.0 data are properly stored in the corresponding DB.

## Expected

After completing this issue, the following outcomes are expected:

- Both the new data and the modifications related to the "description" of the vulnerability are stored in the expected DB
- Refer to the issue #17905 for more details about the structure of the expected data
- Make sure that the implemented mechanism is similar to the other ones 

## DoD (Definition of Done)

- [x] Implement the upsert functionality in the database feed manager code for the "description" fields.
- [x] Perform thorough testing to ensure the correctness and efficiency of the upsert mechanism.
- [x] Handle any potential errors or exceptions that may occur during the upsert process.

**Comment by MiguelazoDS** [comment]
# CVSS Version 

According to the CVE5 schema [LINK](https://cveproject.github.io/cve-schema/schema/v5.0/docs/#oneOf_i0_containers_cna_metrics_items_cvssV2_0) we can see that CVSSV3.0 and CVSSV3.1 both have the required fields to fill up our description flatbuffer. Those fields are: 
- Version
- BaseScore
- BaseSeverity 

For CVSSV2.0 there is not BaseSeverity field but we based our implementation according to NVD convention [LINK](https://nvd.nist.gov/vuln-metrics/cvss) 

![image](https://github.com/wazuh/wazuh/assets/13010397/cf0f66ee-d72e-421e-bd2f-6c08e2318827)
