### ISSUE TITLE
Bug in Syscollector storing network data

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#1904]
## Bug report

**OS**
_Ubuntu16/CentOS7/RHEL7/AIX.._

**Wazuh version**
_3.7.0_

**Install type**
_manager_

**Install method**
_packages/sources_

**Log sample**

```
# ifconfig

intaaa: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.1.222  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:0e:14:9a:7b  txqueuelen 0  (Ethernet)

intbbb: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.1.222  netmask 0.0.0.0  broadcast 0.0.0.0
        ether 00:0c:29:44:f4:15  txqueuelen 1000  (Ethernet)


 wazuh-db: ERROR: at wdb_netaddr_insert(): sqlite3_step(): UNIQUE constraint failed: sys_netaddr.scan_id, sys_netaddr.proto, sys_netaddr.address
```

Bug description
----------------
With a configuration like the one described (two network interfaces with the same IP) the _Syscollector_ scan cannot store the second because of a duplicate key failure. 
We need to store the interface name as a key to differentiate both.

**Comment by chemamartinez** [comment]
Merged #1928.
Waiting for [#260](https://github.com/wazuh/wazuh-api/pull/260).
