### ISSUE TITLE
Engine - Rules Using Sysmon Events

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#19051]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Wazuh Engine | Manager | Packages/Sources | any |

**Description:**

As we embark on enhancing the Wazuh Engine, our initial focus is on the rules component. To ensure a robust and effective implementation, we've chosen Sysmon events as our primary dataset for the first iteration. This will allow us to validate the operation of the rules and gain a deeper understanding of their functionality.

**Objective:**

1. **Implement Initial Set of Rules:** Develop a preliminary set of rules specifically tailored for Sysmon event analysis.
2. **Testing & Validation:** Conduct tests to ensure these rules correctly process and analyze Sysmon events.
3. **Feedback & Iteration:** Based on the testing results, gather feedback and make necessary adjustments to improve rule efficiency and accuracy.

**Tasks:**

1. **Rule Development:** Design and implement an initial set of rules targeting Sysmon events.
2. **Sysmon Event Collection:** Gather a diverse set of Sysmon events to serve as test data.
3. **Rule Testing:** Test the newly implemented rules against the Sysmon event dataset, ensuring accurate event analysis.
4. **Feedback Loop:** Engage with the development team to gather feedback on rule performance and any potential anomalies.
5. **Adjustments & Refinement:** Based on feedback and test results, refine the rules to enhance their accuracy and efficiency.

**Expected Outcomes:**

1. A set of Wazuh Engine rules specifically designed for Sysmon event analysis.
2. Comprehensive test results showcasing the performance and accuracy of the rules.
3. Feedback and insights from the development team, leading to refined and optimized rules.

**Comment by skywalkerisnull** [comment]
This feature set is super interesting. Would you also be looking to be able to expand on threat hunting by creating a graph representation of the sysmon events?

Somewhat similar to this: https://github.com/SecSamDev/sysmon-arangodb in OpenSearch using something similar to https://www.elastic.co/guide/en/kibana/current/xpack-graph.html
