### ISSUE TITLE
Modify Makefile and upload the new dependencies structure to production.

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19056]
## Description

As part of https://github.com/wazuh/wazuh/issues/16882, a new directory layout should be created for agent and manager dependencies to make it easier to update them individually.

This issue aims to apply all the changes necessary to pull the dependencies from the new paths (in the Makefile) and upload the new structure into production.

**Comment by vikman90** [comment]
## Status change

Blocked by https://github.com/wazuh/wazuh/issues/16882.

**Comment by vikman90** [comment]
Closing until we retake the epic task.
