### ISSUE TITLE
Propose a new directory structure for dependencies.

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19054]
## Description

As part of https://github.com/wazuh/wazuh/issues/16882, a new directory layout should be created for agent and manager dependencies to make it easier to update them individually.

This issue will include the proposed design, which will later be applied.

**Comment by sdvendramini** [comment]
After researching and analyzing how to improve wazuh's dependency management, we came to the conclusion that the best option is to have a folder tree with the following structure:

- Pre-compiled: 	`RESOURCES_URL_BASE/deps/libraries/LibName/LibVersion/LibName_SO_arch.tar.gz`

- Source code: 	`RESOURCES_URL_BASE/deps/libraries/LibName/LibVersion/LibName_src.tar.gz`

For example, in the case of openssl it would look like this:

- `https://packages.wazuh.com/deps/libraries/openssl/1.1.1l/openssl_linux_amd64.tar.gz`

- `https://packages.wazuh.com/deps/libraries/openssl/1.1.1l/openssl_windows_amd64.tar.gz`

- `https://packages.wazuh.com/deps/libraries/openssl/1.1.1l/openssl_src.tar.gz`


Although these changes imply that each library will have its own code to know which file to download, it simplifies a lot the management of the repository where the dependencies are located and makes the folder tree simpler.

We propose to store directly inside each folder of each version of the library the compressed files of each precompiled and the source code of the library for that version.

In the makefile, the version of each library must be defined to link the wazuh version to the library version and then the name of the file to download for each of the dependencies must be correctly concatenated regarding OS version and architecture or source code if the libraries will be compiled.

- `LibName + src + tar.gz`

or

- `LibName + OS + arch + tar.gz`
