### ISSUE TITLE
Support new Wazuh version 4.7.1

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19067]
# Description

This issue attempts to support a new version 4.7.1 in the Wazuh system. It includes tracking the generation of issues, projects, and numbered branches across all repositories.

# Tasks
Each task must be completed sequentially based on numbering. Tasks within the same subsection might be parallelized.

## 1. Open release tracking project  -> @havidarou
- [x] Release 4.7.1

### wazuh-qa -> @wazuh/qa
- https://github.com/wazuh/wazuh-qa/issues/4532
### wazuh-jenkins -> @wazuh/qa
- https://github.com/wazuh/wazuh-jenkins/issues/5664
### wazuh-automation -> @wazuh/cicd
- https://github.com/wazuh/wazuh-automation/issues/1299
### wazuh-packages -> @wazuh/core
- https://github.com/wazuh/wazuh-packages/issues/2467
### wazuh -> @wazuh/core
- https://github.com/wazuh/wazuh/issues/19066
### wazuh-ansible -> @wazuh/cicd
- https://github.com/wazuh/wazuh-ansible/issues/1035
### wazuh-docker -> @wazuh/cicd
- https://github.com/wazuh/wazuh-docker/issues/1002
### wazuh-puppet -> @wazuh/cicd
- https://github.com/wazuh/wazuh-puppet/issues/771
### wazuh-kubernetes -> @wazuh/cicd
- https://github.com/wazuh/wazuh-kubernetes/issues/458
### wazuh-kibana-app -> @wazuh/frontend
- https://github.com/wazuh/wazuh-kibana-app/issues/5904
### wazuh-documentation -> @wazuh/documentation
- https://github.com/wazuh/wazuh-documentation/issues/6528

## 3. Create AWS resources  -> @wazuh/qa

- [x] All AWS resources should be regenerated using the Procedure_ecs_task_tier pipeline on branches that have been modified/bumped.
  - [x] 4.7.1

**Comment by juliamagan** [comment]
### Create AWS resources

- Launched ECS resources generation: https://ci.wazuh.info/job/Procedure_ecs_task_tier/48/
