### ISSUE TITLE
Support new Wazuh version 4.7.1 in wazuh repository

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19066]
## Description

This issue attempts to support a new version 4.7.1 in the wazuh repository.

## Tasks

- [x] Create numbered branch for version (4.7.1) using branch 4.7.0 on wazuh repository.
- [x] Bump 4.7.1 branch to 4.7.1 version on wazuh repository, including revision and changelog.

**Comment by vikman90** [comment]
New branch: [4.7.1](https://github.com/wazuh/wazuh/tree/4.7.1).
