### ISSUE TITLE
An increase in the DBSYNC activity has been detected

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#19074]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | Syscheck / Dbsync | Manager | any | Linux |

While analyzing issue #17928 related to the footprints test, we've observed that in version `4.6.0`, there is an increase in `dbsync` activity, which continues processing events at the EDPS limit persistently, even after the stress load has been completed. The difficulty of processing `dbsync` events may be the root cause of the manager reaching its processing capacity and, given this situation, more agents getting disconnected.

This could be related to `FIM`/`syscheck`, as evidenced by the `syscheck-solo` tests, where the increase in the `dbsync` activity is visible, just as in every test that enables `syscheck`. That can be seen by comparing the EDPS plots:
### Syscheck only
![image](https://github.com/wazuh/wazuh/assets/75255206/1147afb1-d32b-414f-8359-47ba8cf62a5d)
![image](https://github.com/wazuh/wazuh/assets/75255206/96f6df21-4f14-4b43-898d-419447812be5)
### All except Syscheck
![image](https://github.com/wazuh/wazuh/assets/75255206/47fb745f-02dd-4a07-8253-1bba94f2f7c4)
![image](https://github.com/wazuh/wazuh/assets/75255206/8503b6cb-f2d2-4a35-9662-145b2e85445f)

To compare the behaviors of the components please refer to the following tests:
[Syscheck solo test @ 4.5.2](https://github.com/wazuh/wazuh/issues/18657)
[Syscheck solo test @ 4.6.0](https://github.com/wazuh/wazuh/issues/18915)
[All-except-Syscheck test @ 4.5.2](https://github.com/wazuh/wazuh/issues/18660)
[All-except-Syscheck test @ 4.6.0](https://github.com/wazuh/wazuh/issues/18914)

**Comment by jotacarma90** [comment]
## Extra info

Hello team, 
I link here a couple of PRs that are very related to this topic in case it helps to get information.
- PR of syscheck performance check related to dbsync change: https://github.com/wazuh/wazuh/issues/10223
- PR with some changes related to the sync settings (there is a sequence diagram explaining how the sync works in detail): https://github.com/wazuh/wazuh/pull/14105

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | RC                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.6.0-rc |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-pullrequests`
- Package revision: `0.commit2cdb1b0`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4470/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/plots/Test_stress_B4470_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4470_manager_2023-10-19.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/logs/ossec_Test_stress_B4470_manager_2023-10-19.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/data/monitor-manager-Test_stress_B4470_manager-warehouse-pullrequests.csv)
[Test_stress_B4470_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/data/Test_stress_B4470_manager_analysisd_events.csv)
[Test_stress_B4470_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/data/Test_stress_B4470_manager_analysisd_state.csv)
[Test_stress_B4470_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_manager_centos/data/Test_stress_B4470_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/Test_stress_B4470_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/Test_stress_B4470_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/Test_stress_B4470_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/plots/Test_stress_B4470_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4470_centos_2023-10-19.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/logs/ossec_Test_stress_B4470_centos_2023-10-19.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/data/monitor-agent-Test_stress_B4470_centos-warehouse-pullrequests.csv)
[Test_stress_B4470_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_centos/data/Test_stress_B4470_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/Test_stress_B4470_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/Test_stress_B4470_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/Test_stress_B4470_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/plots/Test_stress_B4470_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4470_ubuntu_2023-10-19.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/logs/ossec_Test_stress_B4470_ubuntu_2023-10-19.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/data/monitor-agent-Test_stress_B4470_ubuntu-warehouse-pullrequests.csv)
[Test_stress_B4470_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_ubuntu/data/Test_stress_B4470_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/Test_stress_B4470_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/Test_stress_B4470_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/Test_stress_B4470_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/plots/Test_stress_B4470_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4470_windows_2023-10-19.zip](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/logs/ossec_Test_stress_B4470_windows_2023-10-19.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/data/monitor-winagent-Test_stress_B4470_windows-warehouse-pullrequests.csv)
[Test_stress_B4470_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-pullrequests/4.6.0/B4470-1440m/B4470_agent_windows/data/Test_stress_B4470_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by Dwordcito** [comment]
The fix worked as expected, basically at the intersection of the orange and blue lines, they both relax. This means that as soon as realtime events stop arriving, the rsync synchronization results in the synchronization being carried out correctly, therefore it does not continue to grow.

![image](https://github.com/wazuh/wazuh/assets/14300208/aebf6425-dfbd-41bb-ad27-13188013aa6d)
Apart from this, the number of dbsync events is equivalent to that of 4.5.3
