### ISSUE TITLE
Refactor and migrate authd integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19083]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the authd tests. The following files are involved:

```
test_authd/
├── conftest.py
├── data
│   ├── api_agent_registration_cases.yaml
│   ├── authd_key_hash.yaml
│   ├── configuration_template
│   │   └── config_authd_use_password_invalid.yaml
│   ├── enroll_messages.yaml
│   ├── enroll_ssl_options_tests.yaml
│   ├── key_request_worker_messages.yaml
│   ├── local_enroll_messages.yaml
│   ├── test_authd_use_password.yaml
│   ├── test_authd_use_source_ip.yaml
│   ├── test_authd_valid_name_ip.yaml
│   ├── test_cases
│   │   └── cases_authd_use_password_invalid.yaml
│   ├── test_key_request_exec_path.yaml
│   ├── test_key_request_limits.yaml
│   ├── test_key_request_messages.yaml
│   ├── wazuh_authd_configuration.yaml
│   └── worker_messages.yaml
├── files
│   ├── fetch_keys.py
│   └── fetch_keys_sleep.py
├── force_options
│   ├── data
│   │   ├── template_configuration.yaml
│   │   └── test_cases
│   │       ├── invalid_config
│   │       │   └── invalid_configs.yaml
│   │       └── valid_config
│   │           ├── after_registration_time.yaml
│   │           ├── disconnected_time.yaml
│   │           ├── enablement_force_options.yaml
│   │           └── key_mismatch.yaml
│   ├── test_authd_force_options_invalid_config.py
│   └── test_authd_force_options.py
├── test_api_agent_registration.py
├── test_authd_agents_ctx.py
├── test_authd_key_hash.py
├── test_authd_key_request_exec_path.py
├── test_authd_key_request_func.py
├── test_authd_key_request_limits.py
├── test_authd_key_request_worker.py
├── test_authd_local.py
├── test_authd.py
├── test_authd_ssl_certs.py
├── test_authd_ssl_options.py
├── test_authd_use_password_invalid.py
├── test_authd_use_password.py
├── test_authd_use_source_ip.py
├── test_authd_valid_name_ip.py
├── test_authd_worker.py
└── test_remote_enrollment.py
```

### Tasks:

- [ ] Apply new format to tests.
- [ ] Ensure that each test configures all it needs (ie: internal options).
- [ ] Move everything related to the test environment configuration to fixtures.
- [ ] Make sure tests clean up the environment after execution.
- [ ] Place fixtures in `conftest.py` files.
- [ ] Use generic functions of the new QA framework.
- [ ] Make sure there is no duplicate code.

**Comment by mateocervilla** [comment]
## Latest updates
I ran into some issues during the migration which I'm working on. Adding to the fact that the migration was larger than expected, this issue will be delayed.

### Some errors:

- `test_authd_key_hash.py`:
    - ConnectionRefusedError: [Errno 111] Connection refused

- `test_authd.py`:
    - ConnectionRefusedError: [Errno 111] Connection refused

- `test_authd_worker.py`:
    - AssertionError: assert 'OSSEC K:' in 'ERROR: Cannot comunicate with master'

- `test_remote_enrollment.py`:
    - AssertionError: assert 'OSSEC K:' in 'ERROR: Cannot comunicate with master'

**Comment by mateocervilla** [comment]
## Latest updates
The migration is almost completed. All tests and files have been refactored and the mentioned errors have been solved, but at the moment there are two tests failing.

### Failing tests:

- `test_authd_ssl_certs.py`:
    - Failed cases `(4/8)`:
        - `[VALID CERT - Verify Host NO]`
        - `[INCORRECT HOST - Verify Host NO]`
        - `[VALID CERT - Verify Host YES]`
        - `[INCORRECT HOST - Verify Host YES]`
    - Error:
        - ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:1007)

- `test_authd_key_request_func.py`:
    - Failed case `(1/5)`:
        - `[Error duplicate agent 001]`
    - Error:
        - Error event not detected: `"Duplicate ID. Removing old agent 'wazuh_agent1' (id '001')."`

> Note: The original test `test_authd_key_request_func.py` of the `wazuh-qa` repository (before migration) fails completely, but this fail can be solved by adding the function `configure_sockets_environment_function` to the fixtures, which was already done in this refactor.

**Comment by mateocervilla** [comment]
This issue was delayed because the `test_authd_ssl_certs.py` issue was still present at the time. There's also extra time for the PRs review.

**Comment by mateocervilla** [comment]
## Update
Most of the PR requested changes to the tests were made, but many of them involve replacing functions related to the execution of the daemons, which is causing the tests to stop working correctly. I am currently fixing these errors.

**Comment by mateocervilla** [comment]
## Update
The tests are now finished and working.
Latest commits:
- https://github.com/wazuh/wazuh/pull/19871/commits/9e57a5bc7573986b098c2b95ded38246c01fc658
- https://github.com/wazuh/wazuh/pull/19871/commits/8472bb673d36396b881c8ba6d267e42f53991115
- https://github.com/wazuh/wazuh/pull/19871/commits/4d8238ea90f7e949264b266987c3e52322e1f277

- https://github.com/wazuh/qa-integration-framework/pull/48/commits/25a6758c1a35fa03fa73a9df5964d09ac53240d1

**Comment by mateocervilla** [comment]
## ETA Update

Updated due to pending review
