### ISSUE TITLE
Refactor and migrate logtest integration tests from QA repository to Core repository

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19082]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the logtest tests. The following files are involved:

```
test_logtest/
├── conftest.py
├── test_configuration
│   ├── data
│   │   └── wazuh_conf.yaml
│   ├── test_configuration_file.py
│   └── test_get_configuration_sock.py
├── test_invalid_rule_decoders_syntax
│   ├── data
│   │   ├── custom_decoder_0.xml
│   │   ├── custom_decoder_10.xml
│   │   ├── custom_decoder_11.xml
│   │   ├── custom_decoder_1.xml
│   │   ├── custom_decoder_2.xml
│   │   ├── custom_decoder_3.xml
│   │   ├── custom_decoder_4.xml
│   │   ├── custom_decoder_5.xml
│   │   ├── custom_decoder_6.xml
│   │   ├── custom_decoder_7.xml
│   │   ├── custom_decoder_8.xml
│   │   ├── custom_decoder_9.xml
│   │   ├── custom_rule_0.xml
│   │   ├── custom_rule_10.xml
│   │   ├── custom_rule_11.xml
│   │   ├── custom_rule_12.xml
│   │   ├── custom_rule_13.xml
│   │   ├── custom_rule_14.xml
│   │   ├── custom_rule_1.xml
│   │   ├── custom_rule_2.xml
│   │   ├── custom_rule_3.xml
│   │   ├── custom_rule_4.xml
│   │   ├── custom_rule_5.xml
│   │   ├── custom_rule_6.xml
│   │   ├── custom_rule_7.xml
│   │   ├── custom_rule_8.xml
│   │   ├── custom_rule_9.xml
│   │   ├── invalid_decoder_syntax.yaml
│   │   └── invalid_rules_syntax.yaml
│   ├── test_invalid_decoder_syntax.py
│   └── test_invalid_rules_syntax.py
├── test_invalid_socket_input
│   ├── data
│   │   └── invalid_socket_input.yaml
│   └── test_invalid_socket_input.py
├── test_invalid_token
│   ├── data
│   │   └── invalid_session_token.yaml
│   └── test_invalid_session_token.py
├── test_log_process_options
│   ├── data
│   │   ├── rules_verbose.xml
│   │   └── rules_verbose.yaml
│   └── test_rules_verbose.py
├── test_remove_old_sessions
│   ├── data
│   │   └── wazuh_conf.yaml
│   ├── test_remove_old_session_for_inactivity.py
│   └── test_remove_old_sessions.py
├── test_remove_session
│   ├── data
│   │   └── remove_session.yaml
│   └── test_remove_session.py
├── test_rules_decoders_load
│   ├── data
│   │   ├── custom_ruleset
│   │   │   ├── custom_decoders_1.xml
│   │   │   ├── custom_decoders_2.xml
│   │   │   ├── custom_rules_1.xml
│   │   │   └── custom_rules_2.xml
│   │   └── load_rules_decoders.yaml
│   └── test_load_rules_decoders.py
└── test_ruleset_refresh
    ├── data
    │   ├── cdb_list.yaml
    │   ├── custom_alert_rule_default.xml
    │   ├── custom_alert_rule_level_8.xml
    │   ├── custom_cdb_list
    │   ├── custom_cdb_rules.xml
    │   ├── custom_decoder_0.xml
    │   ├── custom_decoder_1.xml
    │   ├── custom_decoder_2.xml
    │   ├── custom_decoder_3.xml
    │   ├── custom_rule_0.xml
    │   ├── custom_rule_1.xml
    │   ├── custom_rule_2.xml
    │   ├── custom_rule_3.xml
    │   ├── decoder_list.yaml
    │   ├── log_alert_level.yaml
    │   └── rule_list.yaml
    ├── test_alert_labels.py
    ├── test_cdb_labels.py
    ├── test_decoder_labels.py
    └── test_rule_labels.py
```

### Tasks:

- [ ] Apply new format to tests.
- [ ] Ensure that each test configures all it needs (ie: internal options).
- [ ] Move everything related to the test environment configuration to fixtures.
- [ ] Make sure tests clean up the environment after execution.
- [ ] Place fixtures in `conftest.py` files.
- [ ] Use generic functions of the new QA framework.
- [ ] Make sure there is no duplicate code.

**Comment by mateocervilla** [comment]
## Update
Working on migrating tests to the new format:
- https://github.com/wazuh/wazuh/pull/19929/commits/90af6bbc0f84d5c29cb2cba899d0d58147f82403
- https://github.com/wazuh/wazuh/pull/19929/commits/ba0ed37486255aa60b4d42206941580f1b0a4557
- https://github.com/wazuh/wazuh/pull/19929/commits/c7fb9ffde54258c460d8f102f53a2039247835bc
- https://github.com/wazuh/wazuh/pull/19929/commits/2be609dae36deb0f296af9139d52262a19be4529
- https://github.com/wazuh/wazuh/pull/19929/commits/865792fb412aff7fef01ce53b811d5937b969be2

**Comment by mateocervilla** [comment]
## Update
Finished on migrating tests to the new format:
- https://github.com/wazuh/wazuh/pull/19929/commits/5557af2bc12e3ba81f6159d09006ecc309c2427c
- https://github.com/wazuh/wazuh/pull/19929/commits/87840fd59aa58e76912c43c61165b0c22d58d899
- https://github.com/wazuh/wazuh/pull/19929/commits/4a492a8875f6e2898120c6b5378bc376757b84ec

**Comment by mateocervilla** [comment]
## ETA update
The ETA was delayed because the review is still pending

**Comment by mateocervilla** [comment]
## Update
Due to recent changes required on similar issues, this PR has been reviewed and similar changes are being applied

**Comment by mateocervilla** [comment]
## Update
Applied some requested changes from other similar PRs.
The tests are now finished and working.
Latest commits:
- https://github.com/wazuh/wazuh/pull/19929/commits/439d82894709c8bb27ac4e10f774288f941ae8e2
- https://github.com/wazuh/wazuh/pull/19929/commits/47ef2ba9b509aefb8e7d19df9ecb30fb5d699e63
- https://github.com/wazuh/wazuh/pull/19929/commits/c4d04eb21a158bebdd51c6a0d011ba3d2f6af4d6

- https://github.com/wazuh/qa-integration-framework/pull/47/commits/de1183572c27dce09809372fb1e6464a9734ef29
- https://github.com/wazuh/qa-integration-framework/pull/47/commits/750fac3ed7542357008343955f0295394b6cd379

## ETA Update

Updated due to pending review

**Comment by mateocervilla** [comment]
## Update
- Requested  changes applied.
 
### Ready for review

**Comment by ncvicchi** [comment]
Moved ETA to give time for reviewing
