### ISSUE TITLE
Review settings in ossec.conf

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1909]
## Bug report

**Install type**
_manager/agent_

Bug description
----------------

Review settings in ossec.conf, both for manager and agents to check how it behaves when removing parts altogether.

**Comment by snaow** [comment]
Check what is the minimal `ossec.conf` configuration the Manager can work properly with.
Orchestration tools as Puppet or Chef do not use the out of the box configuration file which has all the setting blocks already defined.

**Comment by DaveVG1** [comment]
Minimal configuration for agent
-------------------------------------
```
<ossec_config>
  <client>
    <server>
      <address>VALID_IP</address>
    </server>
  </client>
</ossec_config>
```
Minimal configuration for manager
---------------------------------------
```
<ossec_config>
  <ruleset>
    <!-- Default ruleset -->
    <decoder_dir>ruleset/decoders</decoder_dir>
  </ruleset>
</ossec_config>
```
Tasks
----------------------------------------

- We should change default values to make both manager and agent work with empty configuration. Note that agent will fail to work if it's never been connected to a manager giving the next error:

```                       
             ossec-agentd: CRITICAL: (1751): File client.keys not found or empty.
```

- It would be good to change the info messages related to missing configurations (rootcheck, syscheck, etc.), in order to show them somewhere else than the status (before the daemon starts).

**Comment by DaveVG1** [comment]
The next table indicates the messages displayed if some configuration modules are deleted in `ossec.conf`. It's also indicated where the message is displayed (ossec log or status) and the installation type (manager, agent or both).

| Module  | Message| Where | Installation |
| :--- | ------- | :---| :--- | 
| **Global**  |  ``` Dec 10 10:21:59 vm-ubuntu16 env[30015]: 2018/12/10 10:21:58 ossec-maild: INFO: E-Mail notification disabled. Clean Exit. ```   | Status | Manager
| **Rootcheck**  | ``` 2018/12/10 10:38:01 rootcheck: INFO: Rootcheck disabled. ```  | Status/Log | Manager/Agent
| **Syscheck**  | ``` Dec 10 10:40:09 vm-ubuntu16 env[8984]: 2018/12/10 10:40:09 ossec-syscheckd: INFO: (1702): No directory provided for syscheck to monitor. ``` ``` Dec 10 10:40:09 vm-ubuntu16 env[8984]: 2018/12/10 10:40:09 ossec-syscheckd: INFO: Syscheck disabled. ``` | Status/Log | Manager/Agent
| **Localfile**  | ``` Dec 10 10:46:54 vm-ubuntu16 env[12819]: 2018/12/10 10:46:54 ossec-logcollector: INFO: (1905): No file configured to monitor. ``` | Status | Manager/Agent
| **Ruleset**  | ``` Dec 05 13:57:11 vm-centos7 env[8940]: 2018/12/05 13:57:11 ossec-analysisd: ERROR: (1226): Error reading XML file '/etc/decoder.xml': XMLERR: File '/etc/decoder.xml' not found. (line 0). ```  ``` Dec 05 13:57:11 vm-centos7 env[8940]: 2018/12/05 13:57:11 ossec-analysisd: CRITICAL: (1202): Configuration error at '/etc/decoder.xml'. ``` | Status | Manager
| **Active-response**  | ``` 2018/12/10 11:05:45 ossec-execd: INFO: No option <ca_store> defined. Using Wazuh default CA (/var/ossec/etc/wpk_root.pem). ``` | Log | Agent
| **Client**  | ``` Dec 05 14:48:20 vm-ubuntu3 env[13205]: 2018/12/05 14:48:20 ossec-agentd: ERROR: (4105): No valid server IP found. ``` ``` Dec 05 14:48:20 vm-ubuntu3 env[13205]: 2018/12/05 14:48:20 ossec-agentd: CRITICAL: (1215): No client configured. Exiting. ``` | Status | Agent
| **Remote**  | ``` 2018/12/05 14:23:16 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused ``` | Log | Agent
