### ISSUE TITLE
Refactor and migrate test_agentd_reconnection

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#19094]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the agentd tests. The following files are involved:

```
test_agentd/
   ├── conftest.py
   └── test_agentd_state_reconnection
                       ├──── data
                       |        └── config_templates
                       │        │           └── wazuh_conf.yaml
                       |        └── test_cases
                       │                    └── wazuh_state_tests.yaml
                       │
                       └── test_agentd_connection_retries_pre_enrollment.py
                       │
                       └── test_agentd_initial_enrollment_retries.py
                       │
                       └── test_agentd_reconection_enrollment_no_keys_file.py
                       │
                       └── test_agentd_reconection_enrollment_no_keys.py
                       │
                       └── test_agentd_reconection_enrollment_with_keys.py
```

### Tasks:
- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (ie: internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.

### Current status - BLOCKED
The test cases using TCP protocol are running fine, but UDP ones fail due RemotedSimulator can not mock the connection correctly. Report: https://github.com/wazuh/wazuh/issues/17696#issuecomment-1784578288

**Comment by MarcelKemp** [comment]
- Done at https://github.com/wazuh/wazuh/issues/17696
