### ISSUE TITLE
ERROR: Invalid option 'frequency' for rule

### ISSUE THREAD

**Issue by SouthWind017** [wazuh/wazuh#19090]
|Wazuh version|Component|Install type|Install method|Platform|
|4.2|---|---|Quickstart|centos 7.8|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

<rule id="100200" level="5">
    <if_group>web|attack|attacks</if_group>
    <description>Web or attack event.</description>
</rule>

<rule id="100201" level="10">
    <if_matched_sid>100200</if_matched_sid>
    <description>Multiple web or attack events from the same IP in 5 minutes.</description>
    <group>firewalldrop,</group>
</rule>
Where are the trigger drop rules configured here? If there are too many accesses from the same source IP within a certain period of time, it will be dropped.

<rule id="100200" level="5">
    <if_group>web|attack|attacks</if_group>
    <description>Web or attack event.</description>
</rule>

When I use the following configuration, I get an error。
<rule id="100201" level="10">
    <if_matched_sid>100200</if_matched_sid>
    <description>Multiple web or attack events from the same IP in 5 minutes.</description>
    <frequency>4</frequency>
    <timeframe>300</timeframe>
    <group>firewalldrop,</group>
</rule>

2023/09/21 14:24:16 wazuh-analysisd: INFO: (1305): Timeout not allowed for command: 'firewall-drop'.
2023/09/21 14:24:17 wazuh-analysisd: ERROR: Invalid option 'frequency' for rule '100201'.
2023/09/21 14:24:17 wazuh-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.

How should I custom configure the drop rules instead of triggering the rules.

**Comment by SouthWind017** [comment]
<rule id="100200" level="5">
    <if_group>web|attack|attacks</if_group>
    <description>Web or attack event.</description>
</rule>

<rule id="100201" level="10">
    <if_matched_sid>100200</if_matched_sid>
    <description>Multiple web or attack events from the same IP in 5 minutes.</description>
    <frequency>4</frequency>
    <timeframe>300</timeframe>
    <group>firewalldrop,</group>
</rule>

**Comment by SouthWind017** [comment]
> |Wazuh version|Component|Install type|Install method|Platform| |4.2|---|---|Quickstart|centos 7.8| | X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
> ```
<rule id="100200" level="5">
    <if_group>web|attack|attacks</if_group>
    <description>Web or attack event.</description>
</rule>

<rule id="100201" level="10">
    <if_matched_sid>100200</if_matched_sid>
    <description>Multiple web or attack events from the same IP in 5 minutes.</description>
    <frequency>4</frequency>
    <timeframe>300</timeframe>
    <group>firewalldrop,</group>
</rule>
```
> How should I custom configure the drop rules instead of triggering the rules.

**Comment by juliancnn** [comment]
Hi @SouthWind017 , 

It seems there's an issue with the configuration in your `local_rules.xml`. The errors you're seeing suggest that there's a problem with the `frequency`.

To better assist you, could you please share the complete content of the rule in your `local_rules.xml`? This will help pinpoint the exact issue and provide a more accurate solution.

Remember, when customizing rules, it's essential to ensure that the rule structure and options are correctly defined to avoid conflicts or errors during rule processing.

Looking forward to your response!
