### ISSUE TITLE
Missing files in latest version installation

### ISSUE THREAD

**Issue by wayneworkman** [wazuh/wazuh#191]
Hi all, I just dove into Wazuh yesterday - very neat - my brains are pretty scrambled from it all. I did a fresh install on CentOS 7 fully updated - and logstash kept restarting over and over because this file was missing:
`/etc/logstash/wazuh-elastic5-template.json`

So I grabbed a copy of that file from here and put it into place and then logstash stopped cycling: 
https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/wazuh-elastic5-template.json

I still don't think things are working right - there's no output in the Kibana console anywhere, it just says no data / not found everywhere I look.  I do have 5 test agents connected to the server successfully - they all show as active. 

I don't really have any idea what I'm doing with this, just stumbling through it really.

**Comment by havidarou** [comment]
Hi,

you could test whether or not elasticsearch is receiving alerts.

First of all, try a command like 'sudo su' so you generate an alert
(although you probably have some already).

And then: 'curl localhost:9200/_cat/indices?v'

You should get something like

health status index                       uuid                   pri
rep docs.count docs.deleted store.size pri.store.size
yellow open   wazuh-alerts-2017.09.13     RbEp4CSNQHSmGJRIkaXxTQ   5
1      17744            0     14.1mb         14.1mb

This means logstash is effectively feeding elasticsearch with alerts.

If you don't see the index, it probably means logstash or
elasticsearch are not working properly.

My advice would be to assure you are installing and configuring
elasticsearch before logstash and kibana.

Let me know if you keep having problems.

Regards.

**Comment by wayneworkman** [comment]
@havidarou Logstash is now feeding elasticsearch with alerts! I guess I was impatient? Not sure. Either way, what is supposed to put `/etc/logstash/wazuh-elastic5-template.json` into place? Is it purposely left out of the installation process?

**Comment by havidarou** [comment]
@wayneworkman glad it's working! 

Yes, you need to tell logstash what template to use when feeding data to elasticsearch.

**Comment by wayneworkman** [comment]
But I don't understand why there can't just be a default template placed by the installer? This seems like a trivial thing that the installer can handle.

**Comment by jlruizmlg** [comment]
Hi @wayneworkman the guide include this step:

In the following link, take a look the step 2:)
https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#logstash

The command:

```
curl -so /etc/logstash/wazuh-elastic5-template.json https://raw.githubusercontent.com/wazuh/wazuh/2.0/extensions/elasticsearch/wazuh-elastic5-template.json
```

download wazuh-elastic5-template.json in ```/etc/logstash/wazuh-elastic5-template.json```

**Comment by DaveVG1** [comment]
Hi @wayneworkman 

I hope the answers we gave were helpful to you. I'm going to close this issue, please feel free to re-open it if you have any further troubles and we will certainly help you.

Kind regards.
