### ISSUE TITLE
Vulnerability detector issues

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#1910]
## Bug report

**Wazuh version**
_3.7.0_

Bug description
----------------

Review how the module behaves when certain settings are not present in the configuration. For example, ignore time or update interval.

Also, improve documentation on feeds for certain common OS such as Amazon Linux.

**Comment by havidarou** [comment]
Also, `update_interval` default value for vulnerability detector is not documented.

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/pull/1932.

**Comment by crolopez** [comment]
> Also, `update_interval` default value for vulnerability detector is not documented.

Added in https://github.com/wazuh/wazuh-documentation/pull/658.
