### ISSUE TITLE
Release 4.5.3 - RC 1  -  Footprint metrics

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#19119]
### Footprint metrics information
|||
| :--                              | :--                                                             |
| **Main release candidate issue** | #19111                                      |
| **Version**                      | 4.5.3                                                   |
| **Release candidate**            | RC1                                                      |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.5.3-rc1          |
| **Previous footprint metrics**   | https://github.com/wazuh/wazuh/issues/18631 |

---

| Test | Url |
| -    | -   |
| ALL 2.5d  | https://ci.wazuh.info/job/Test_stress_tier/94 |

---

## Checks
Status | Modules                                         | 4.5.3 Issue (2.5d)  |
| :--: | :--                                             | :--:                        | 
| :red_circle:   | All                                             |https://github.com/wazuh/wazuh/issues/19179|
| :red_circle:   | Vulnerability-detector                          |https://github.com/wazuh/wazuh/issues/19190|
| :red_circle:   | Vulnerability-detector-Register                 |https://github.com/wazuh/wazuh/issues/19176|
| :red_circle:   | All-except-Vulnerability-detector               |https://github.com/wazuh/wazuh/issues/19187|
| :white_circle:   | Logcollector                                    |--|
| :yellow_circle:   | Syscheck                                        |https://github.com/wazuh/wazuh/issues/19178|
| :yellow_circle:   | Rootcheck                                       |https://github.com/wazuh/wazuh/issues/19181|
| :yellow_circle:   | SCA                                             |https://github.com/wazuh/wazuh/issues/19183|
| :red_circle:   | Active Response                                 |https://github.com/wazuh/wazuh/issues/19180|
| :yellow_circle:   | Syscollector                                    |https://github.com/wazuh/wazuh/issues/19191|
| :red_circle:    | Docker,Ciscat,Osquery,Azure,Openscap           |https://github.com/wazuh/wazuh/issues/19177|
| :red_circle:   | All-except-Logcollector                         |https://github.com/wazuh/wazuh/issues/19209|
| :white_circle:   | All-except-Syscheck                             |--|
| :red_circle:   | All-except-Rootcheck                            |https://github.com/wazuh/wazuh/issues/19208|
| :red_circle:   | All-except-SCA                                  |https://github.com/wazuh/wazuh/issues/19185|
| :yellow_circle:   | All-except-Active Response                      |https://github.com/wazuh/wazuh/issues/19184|
| :red_circle:   | All-except-Syscollector                         |https://github.com/wazuh/wazuh/issues/19189|
| :red_circle:   | All-except-Docker,Ciscat,Osquery,Azure,Openscap |https://github.com/wazuh/wazuh/issues/19186|
| :yellow_circle:   | Logcollector-Syscollector                       |https://github.com/wazuh/wazuh/issues/19207|
| :yellow_circle:   | Logcollector-SCA                                |https://github.com/wazuh/wazuh/issues/19182|
| :yellow_circle:   | Logcollector-Syscheck                           |https://github.com/wazuh/wazuh/issues/19188|
| :yellow_circle:   | macOS-All                                       |https://github.com/wazuh/wazuh/issues/19192|
| :yellow_circle:   | Solaris-All                                     |https://github.com/wazuh/wazuh/issues/19192|
---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Completed with failures
:yellow_circle: - Completed with known issues
:green_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @juliamagan 

---

**Comment by verdx** [comment]
# Update

5 of the tests have failed from the tier:

### All-except-Syscheck
Link: https://ci.wazuh.info/job/Test_stress/4326/

Error:
```
22:57:04  TASK [Stop powershell process] *************************************************
22:57:04  task path: /home/ec2-user/workspace/Test_stress/quality/tests/stress/playbooks/get_data_files.yaml:45
22:57:04  fatal: [Test_stress_B4326_windows]: FAILED! => {
22:57:04      "changed": false,
22:57:04      "rc": 4294967295
22:57:04  }
22:57:04  
22:57:04  MSG:
22:57:04  
22:57:04  MODULE FAILURE
22:57:04  See stdout/stderr for the exact error
22:57:04  
22:57:04  
22:57:04  MODULE_STDERR:
22:57:04  
22:57:04  #< CLIXML
```

```
22:39:36  Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature not yet current: 20230924T210020Z is still later than 20230924T205436Z (20230924T203936Z + 15 min.)
22:39:36  	status code: 403, request id: 22e6c1f4-85ca-4a78-a127-2f3a2b2510f9
22:39:36  
22:39:36    on provider.tf line 1, in provider "aws":
22:39:36     1: provider "aws" {
22:39:36  
22:39:36  
22:39:36  
22:39:36  Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature not yet current: 20230924T210019Z is still later than 20230924T205436Z (20230924T203936Z + 15 min.)
22:39:36  	status code: 403, request id: ffdc755a-29d4-429a-b097-986f2aa019ac
22:39:36  
22:39:36    on provider.tf line 1, in provider "aws":
22:39:36     1: provider "aws" {
22:39:36  
22:39:36  
22:39:36  
22:39:36  Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature not yet current: 20230924T210019Z is still later than 20230924T205436Z (20230924T203936Z + 15 min.)
22:39:36  	status code: 403, request id: a4c51a99-2c88-4d34-98c3-f09e22354a99
22:39:36  
22:39:36    on provider.tf line 1, in provider "aws":
22:39:36     1: provider "aws" {
22:39:36  
22:39:36  
22:39:37  
22:39:37  Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: SignatureDoesNotMatch: Signature not yet current: 20230924T210019Z is still later than 20230924T205435Z (20230924T203935Z + 15 min.)
22:39:37  	status code: 403, request id: 819c9e2a-984e-4984-8856-b40eb0ac81a2
22:39:37  
22:39:37    on provider.tf line 1, in provider "aws":
22:39:37     1: provider "aws" {
22:39:37  
```

### Logcollector

Link: https://ci.wazuh.info/job/Test_stress/4314/

Same errors as in the previous one

### All-except-logcollector
Link: https://ci.wazuh.info/job/Test_stress/4325/

The pipeline has run correctly, the error has happened on the GitHub pipeline to create the issue, https://ci.wazuh.info/job/Test_stress_gh/1336/.

The test has been run correctly, and the GitHub pipeline could probably be rerun.

### All-except-rootcheck
Link: https://ci.wazuh.info/job/Test_stress/4327/

Same as previous with https://ci.wazuh.info/job/Test_stress_gh/1333/

### LOGCOLLECTOR,SYSCOLLECTOR
Link: https://ci.wazuh.info/job/Test_stress/4321/


Same as previous with https://ci.wazuh.info/job/Test_stress_gh/1334/

**Comment by juliamagan** [comment]
LGTM
