### ISSUE TITLE
Release 4.5.3 - Testing

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19112]
## Description
Main issue tracking all the tasks regarding the release testing for Wazuh version 4.5.3.
This issue might be closed only after the release is published.

## Stages

Following our release workflow, in order to publish, one or more release stages are tested. In the links below we can check the status and evolution of each of these stages.

- https://github.com/wazuh/wazuh/issues/19111
- https://github.com/wazuh/wazuh/issues/19300
- https://github.com/wazuh/wazuh/issues/19446

## Tests
All the test results for this release can be found in the [v4.5.3 project](https://github.com/orgs/wazuh/projects/64/views/4).

**Comment by davidjiglesias** [comment]
LGTM!
