### ISSUE TITLE
Version mismatch in ruleset

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#1912]
## Bug report

**Wazuh version**
_3.7.1-3720_

**Install type**
_manager_

**Install method**
_packages_

**Log sample**

```
assert '3.7.1' in 'RULESET_VERSION="v3.7.0" REVISION="3702"'
```

Bug description
----------------
Hi team,

I launch installation tests and ruleset check fails due to version mismatch with current package, please bump version and revision with the current wazuh-ruleset repository 
`VERSION=v3.7.1`
`REVISION=3703`

**Comment by vikman90** [comment]
Done: 1224822c5affb61f72f74d431dfc074af71058f5
