### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh repository - Fortnight #18

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19120]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.5.3-into-4.6.0`.

### 4.5.3
- [x] Update changelog.
- [x] Merge branch `4.5.3` into branch `4.6.0`.
### 4.6.0
- [x] Update changelog.
- [x] Merge branch `4.6.0` into branch `4.7.0`.
### 4.7.0
- [x] Update changelog.
- [x] Merge branch `4.7.0` into branch `4.7.1`.
### 4.7.1
- [x] Update changelog.
- [x] Merge branch `4.7.1` into branch `master`.
### 4.8.0 (master)
- [ ] Update changelog.

**Comment by vikman90** [comment]
Blocked by a failure in PR https://github.com/wazuh/wazuh/pull/19196.
We're waiting for access to a development environment to debug the issue.
