### ISSUE TITLE
Release 4.6.0 - Beta 1 - E2E UX tests - Demo environment

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19157]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.6.0-beta1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/cicd team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer |  |  |  |
| Server |  |  |  |
| Dashboard |  | - |  |
| Agent |  | - |  |

## Test description

Test demo.wazuh.info environment:
  - [x] Check that there are no errors in the manager, agent, cluster, indexer, and dashboard logs.
  - [x] Check that wazuh daemons are running with the expected user.
  - [x] Check that the status of the indexer cluster is the expected.
  - [x] Check that there are no errors in the browser's developer console when browsing the App.
  - [x] Check that no warning symbols appear in the browser's developer console when browsing the App
  - [x] Check that there are alerts for each of the modules configured.
  - [x] Generate an alert and check that this alert appears in the dashboard (end to end)
  - [x] Check that the search engine works without specifying a field and using *

To access the demo environment, please contact @cicd-team.

## Known issues

- https://github.com/wazuh/wazuh-kibana-app/issues/4108
- https://github.com/wazuh/wazuh-kibana-app/issues/4092
- https://github.com/wazuh/wazuh-packages/issues/1749
- https://github.com/wazuh/wazuh/issues/13253
- https://github.com/wazuh/wazuh/issues/5214
- https://github.com/wazuh/wazuh/issues/8580
- https://github.com/wazuh/wazuh/issues/8581
- https://github.com/wazuh/wazuh-kibana-app/issues/4406
- https://github.com/wazuh/wazuh-kibana-app/issues/4407
- https://github.com/wazuh/wazuh/issues/14710
- https://github.com/wazuh/wazuh-kibana-app/issues/4232
- https://github.com/wazuh/wazuh-kibana-app/issues/4074
- https://github.com/wazuh/wazuh-kibana-app/issues/5745
- https://github.com/wazuh/wazuh-packages/issues/2139
- https://github.com/wazuh/wazuh/issues/18593
- https://github.com/wazuh/wazuh-kibana-app/issues/5821
- https://github.com/wazuh/wazuh-automation/issues/1113
- https://github.com/wazuh/wazuh-kibana-app/issues/5749
- https://github.com/wazuh/wazuh-kibana-app/issues/5750

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :red_circle:  | Check that there are no errors in the manager, agent, cluster, indexer, and dashboard logs. | Found issues in the Dashboard and on managers. | <ul><li>Known Issue https://github.com/wazuh/wazuh/pull/19217</li><li>Known issue https://github.com/wazuh/wazuh-packages/issues/2094</li><li>Known issue https://github.com/opensearch-project/security-analytics/pull/203</li><li>New Issue https://github.com/wazuh/wazuh-kibana-app/issues/5958</li> |
| :green_circle: | The daemons are running with the correct user |  | |
| :green_circle: | The status of the Wazuh Indexer clusters is as expected ||
| :yellow_circle: | Check that there are no errors in the browser's developer console when browsing the App. | Found multiple known Issues | Comment about issues found: <ul><li>https://github.com/wazuh/wazuh-kibana-app/issues/5821</li><li>https://github.com/wazuh/wazuh-kibana-app/issues/5745</li><li>https://github.com/wazuh/wazuh-kibana-app/issues/4092</li><li>https://github.com/wazuh/wazuh-kibana-app/issues/4074</li></ul> |
| :green_circle: | Check that no warning symbols appear in the browser's developer console when browsing the App | ||
| :yellow_circle: | Alerts are being generated for each of the modules configured for this purpose | Some modules do not generate alerts, but it is known to happen from previous versions. |Known Issue found https://github.com/wazuh/wazuh-kibana-app/issues/5749
| :green_circle: |Generate an alert and check that this alert appears in the dashboard (end to end)
| :green_circle: | Search works without specifying a field and using *

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
- Did you face any challenges not covered by the guideline?
- Suggestions for improvement:

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @havidarou
- [x] @wazuh/cicd

**Comment by Deblintrake09** [comment]
## T1 - No errors or warnings found in logs 

### Agents

<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check agent's version
```
# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40601"
WAZUH_TYPE="agent"
```

2. Check the general status: `systemctl status wazuh-agent -l` 🟢 
```
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since lun 2023-09-25 14:12:41 UTC; 2 days ago
  Process: 5790 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 5926 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-agent.service
           ├─3831 /var/ossec/bin/wazuh-execd
           ├─3843 /var/ossec/bin/wazuh-agentd
           ├─3858 /var/ossec/bin/wazuh-syscheckd
           ├─3874 /var/ossec/bin/wazuh-logcollector
           └─3891 /var/ossec/bin/wazuh-modulesd

sep 25 14:12:37 ip-10-0-1-199.us-west-1.compute.internal env[5926]: Started wazuh-syscheckd...
sep 25 14:12:38 ip-10-0-1-199.us-west-1.compute.internal env[5926]: Started wazuh-logcollector...
sep 25 14:12:39 ip-10-0-1-199.us-west-1.compute.internal env[5926]: Started wazuh-modulesd...
sep 25 14:12:41 ip-10-0-1-199.us-west-1.compute.internal env[5926]: Completed.
sep 25 14:12:41 ip-10-0-1-199.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
sep 25 14:32:02 ip-10-0-1-199.us-west-1.compute.internal crontab[4019]: (root) LIST (root)
```


    
3. Check the modules status: `/var/ossec/bin/wazuh-control status` 🟢 

```
root@xxxx# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```


4. Check the service status: `journalctl -xe -u wazuh-agent.service`  🟢 
    
```
-- Subject: Unit wazuh-agent.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has begun starting up.
sep 25 14:12:34 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Starting Wazuh v4.6.0...
sep 25 14:12:35 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Started wazuh-execd...
sep 25 14:12:36 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Started wazuh-agentd...
sep 25 14:12:37 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Started wazuh-syscheckd...
sep 25 14:12:38 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Started wazuh-logcollector...
sep 25 14:12:39 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Started wazuh-modulesd...
sep 25 14:12:41 ip-xx.xx.xx.xx.xxxxx.compute.internal env[5926]: Completed.
sep 25 14:12:41 ip-xx.xx.xx.xx.xxxxx.compute.internal systemd[1]: Started Wazuh agent.
-- Subject: Unit wazuh-agent.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit wazuh-agent.service has finished starting up.
-- 
-- The start-up result is done.
sep 25 14:32:02 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[4019]: (root) LIST (root)
sep 26 02:32:01 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[9420]: (root) LIST (root)
sep 26 14:32:01 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[14416]: (root) LIST (root)
sep 27 02:32:01 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[20501]: (root) LIST (root)
sep 27 14:32:02 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[25704]: (root) LIST (root)
```


5. Check for errors in logs: `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`  🟢
    ```
    ```
</details>

<details>
<summary>CentOS 🟢  </summary>

1. Check agent's version
```
WAZUH_VERSION="v4.6.0"
WAZUH_REVISION="40601"
WAZUH_TYPE="agent"
```

2. Check the general status: `systemctl status wazuh-agent -l` 🟢 
```
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2023-09-25 14:13:56 UTC; 2 days ago
  Process: 8015 ExecStop=/usr/bin/env /var/ossec/bin/wazuh-control stop (code=exited, status=0/SUCCESS)
  Process: 8110 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUCCESS)
    Tasks: 32 (limit: 4668)
   Memory: 218.0M
   CGroup: /system.slice/wazuh-agent.service
           ├─9449 /var/ossec/bin/wazuh-execd
           ├─9461 /var/ossec/bin/wazuh-agentd
           ├─9476 /var/ossec/bin/wazuh-syscheckd
           ├─9492 /var/ossec/bin/wazuh-logcollector
           └─9510 /var/ossec/bin/wazuh-modulesd
```


    
3. Check the modules status: `/var/ossec/bin/wazuh-control status` 🟢 
```
root@xxxx# /var/ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```


4. Check the service status: `journalctl -xe -u wazuh-agent.service`  🟢 
```
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-agent.service has finished shutting down.
sep 25 14:13:49 ip-xx.xx.xx.xx.xxxxx.compute.internal systemd[1]: Starting Wazuh agent...
-- Subject: Unit wazuh-agent.service has begun start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-agent.service has begun starting up.
sep 25 14:13:49 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Starting Wazuh v4.6.0...
sep 25 14:13:50 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Started wazuh-execd...
sep 25 14:13:51 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Started wazuh-agentd...
sep 25 14:13:52 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Started wazuh-syscheckd...
sep 25 14:13:53 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Started wazuh-logcollector...
sep 25 14:13:54 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Started wazuh-modulesd...
sep 25 14:13:56 ip-xx.xx.xx.xx.xxxxx.compute.internal env[8110]: Completed.
sep 25 14:13:56 ip-xx.xx.xx.xx.xxxxx.compute.internal systemd[1]: Started Wazuh agent.
-- Subject: Unit wazuh-agent.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
-- 
-- Unit wazuh-agent.service has finished starting up.
-- 
-- The start-up result is done.
sep 25 14:14:03 ip-xx.xx.xx.xx.xxxxx.compute.internal crontab[8567]: (root) LIST (root)
```


5. Check for errors in logs: `egrep -i "ERROR|WARNING" /var/ossec/logs/ossec.log`  🟢
    ```

    ```
</details>

**Comment by Deblintrake09** [comment]
## T2 - The daemons are running with the correct user 

### Agents

<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```
root      3831  0.0  0.3  38384  3068 ?        Sl   sep25   0:07 /var/ossec/bin/wazuh-execd
wazuh     3843  0.0  0.5 260204  4848 ?        Sl   sep25   0:35 /var/ossec/bin/wazuh-agentd
root      3858  0.0  0.9 230648  8608 ?        SNl  sep25   1:08 /var/ossec/bin/wazuh-syscheckd
root      3874  0.0  0.4 480836  4316 ?        Sl   sep25   0:26 /var/ossec/bin/wazuh-logcollector
root      3891  0.0  1.2 749056 11532 ?        Sl   sep25   0:14 /var/ossec/bin/wazuh-modulesd
```
</details>

<details>
<summary>CentOS 🟢  </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢
```
root        9449  0.0  0.2  43444  1920 ?        Sl   sep25   0:04 /var/ossec/bin/wazuh-execd
wazuh       9461  0.0  0.6 274248  5168 ?        Sl   sep25   0:29 /var/ossec/bin/wazuh-agentd
root        9476  0.0  1.0 373340  8316 ?        SNl  sep25   1:20 /var/ossec/bin/wazuh-syscheckd
root        9492  0.0  0.3 486000  3064 ?        Sl   sep25   0:20 /var/ossec/bin/wazuh-logcollector
root        9510  0.0  2.6 759144 21488 ?        Sl   sep25   0:14 /var/ossec/bin/wazuh-modulesd
```
</details>

<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```

```
</details>


<details>
<summary>Amazon Linux 2 🟢  </summary>

1. Check the user: `ps -aux | grep wazuh` 🟢

```

```
</details>

**Comment by Deblintrake09** [comment]
# T3 - The status of the Wazuh Indexer clusters is as expected

<details><summary>wazuh-indexer 🟢</summary>

-  Check nodes: `curl -k -u ADMIN_USER:PASS https://indexer_IP:9200/_cat/nodes?v`

```
ip         heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                                        cluster_manager name
X.X.X.X            29          89   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-3
Y.Y.Y.Y           54          90   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client *               node-1
Z.Z.Z.Z           21          90   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-2
T.T.T.T           15          92   0    0.00    0.00     0.00 dimr      cluster_manager,data,ingest,remote_cluster_client -               node-7
```
</details>

**Comment by Deblintrake09** [comment]
## T5 - Alerts are being generated for each of the modules configured for this purpose

### Modules in ENV 1 🟢 

<details>
<summary> Alerts </summary>

1. The modules show events when they are activated.
   
   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/bd56747d-9c53-4c2f-93d3-78b0ac97b8ed)

2. GitHub and Office365 are not activated, so they have not generated alerts.
    _Note: Amazon AWS is configured. I attach details._
  
   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/b70a0ea6-dd17-414f-a624-3a53e2e9791c) 
   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/a78f7171-a5bc-4323-8731-2a15d744437b)

</details>

### Modules in ENV 2 🟢 

<details>
<summary> Alerts </summary>

1. The modules show events except Docker Listener, VirusTotal, and System Auditing.

   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/2551c5f7-4a1e-479f-9925-2d6534397241)

   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/02e0424e-e60f-4d50-b545-33423122cbe0)


- Note: Expected behavior https://github.com/wazuh/wazuh-kibana-app/issues/5749

2. GitHub, Office365, Google Cloud Platform and Osquery are not activated, so they have not generated alerts.

   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/f405ed5e-a4e8-41d1-b8b0-25c7c5a45f22)

   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/c4680893-6728-47d2-9e78-a8a06d721421)

</details>

**Comment by Deblintrake09** [comment]
## T7: Generate an alert and check it in the web UI  🟢 

1. Generate alert
```
ssh fake-user@amazon-agent-ip
fake-user@amazon-agent-ip's password: 
dasdasdPermission denied, please try again.
fake-user@amazon-agent-ip's password: 
Permission denied, please try again.
fake-user@amazon-agent-ip's password: 
fake-user@amazon-agent-ip: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```
2. Check if the alerts are in the Dashboard

   
   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/67debd8f-fc7e-423b-be6e-9ba6e0392c5d)
   

<details>
<summary>Alert information</summary>

```
{
  "_index": "wazuh-alerts-4.x-env-2-2023.09.27",
  "_id": "o1ev2IoBhyp-9nnP8PlE",
  "_version": 1,
  "_score": null,
  "_source": {
    "predecoder": {
      "hostname": "ip-10-0-1-199",
      "program_name": "sshd",
      "timestamp": "Sep 27 22:08:39"
    },
    "cluster": {
      "node": "master",
      "name": "wazuh2"
    },
    "agent": {
      "ip": "10.0.1.199",
      "name": "Amazon",
      "id": "001"
    },
    "data": {
      "srcuser": "fake-user",
      "srcip": "45.178.1.193"
    },
    "manager": {
      "name": "wazuh-manager-master-0"
    },
    "rule": {
      "mail": false,
      "level": 5,
      "hipaa": [
        "164.312.b"
      ],
      "pci_dss": [
        "10.2.4",
        "10.2.5",
        "10.6.1"
      ],
      "tsc": [
        "CC6.1",
        "CC6.8",
        "CC7.2",
        "CC7.3"
      ],
      "description": "sshd: Attempt to login using a non-existent user",
      "groups": [
        "syslog",
        "sshd",
        "authentication_failed",
        "invalid_login"
      ],
      "nist_800_53": [
        "AU.14",
        "AC.7",
        "AU.6"
      ],
      "gdpr": [
        "IV_35.7.d",
        "IV_32.2"
      ],
      "firedtimes": 4,
      "mitre": {
        "technique": [
          "Password Guessing",
          "SSH"
        ],
        "id": [
          "T1110.001",
          "T1021.004"
        ],
        "tactic": [
          "Credential Access",
          "Lateral Movement"
        ]
      },
      "id": "5710",
      "gpg13": [
        "7.1"
      ]
    },
    "decoder": {
      "parent": "sshd",
      "name": "sshd"
    },
    "full_log": "Sep 27 22:08:39 ip-10-0-1-199 sshd[29313]: Failed password for invalid user fake-user from 45.178.1.193 port 11115 ssh2",
    "input": {
      "type": "log"
    },
    "location": "/var/log/secure",
    "id": "1695852521.169752175",
    "GeoLocation": {
      "city_name": "San Luis",
      "country_name": "Argentina",
      "region_name": "San Luis",
      "location": {
        "lon": -66.354,
        "lat": -33.299
      }
    },
    "timestamp": "2023-09-27T22:08:41.854+0000"
  },
  "fields": {
    "timestamp": [
      "2023-09-27T22:08:41.854Z"
    ]
  },
  "highlight": {
    "cluster.name": [
      "@opensearch-dashboards-highlighted-field@wazuh2@/opensearch-dashboards-highlighted-field@"
    ],
    "GeoLocation.city_name": [
      "@opensearch-dashboards-highlighted-field@San Luis@/opensearch-dashboards-highlighted-field@"
    ],
    "agent.name": [
      "@opensearch-dashboards-highlighted-field@Amazon@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1695852521854
  ]
}
```

</details>

**Comment by Deblintrake09** [comment]
![imagen](https://github.com/wazuh/wazuh/assets/14501079/889f6769-7e46-4451-af93-c9827d259e9e)
![imagen](https://github.com/wazuh/wazuh/assets/14501079/443ea508-4f2c-40a1-a0cd-9d933d2afe22)



```xml
[-](https://github.com/wazuh/wazuh/issues/19157#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/wazuh/wazuh/issues/19157#) <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="16384">7036</EventID> 
  <Version>0</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2023-09-25T14:40:37.161807300Z" /> 
  <EventRecordID>109146</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="596" ThreadID="4020" /> 
  <Channel>System</Channel> 
  <Computer>EC2AMAZ-PR2CC4P</Computer> 
  <Security /> 
  </System>
[-](https://github.com/wazuh/wazuh/issues/19157#) <EventData>
  <Data Name="param1">Wazuh</Data> 
  <Data Name="param2">running</Data> 
  <Binary>570061007A00750068005300760063002F0034000000</Binary> 
  </EventData>
  </Event>
```

**Comment by Deblintrake09** [comment]
## T7:  Generate an alert and check that this alert appears in the dashboard (end to end)  🟢 

1. Generate alert
```
ssh fake-user@amazon-agent-ip
fake-user@amazon-agent-ip's password: 
dasdasdPermission denied, please try again.
fake-user@amazon-agent-ip's password: 
Permission denied, please try again.
fake-user@amazon-agent-ip's password: 
fake-user@amazon-agent-ip: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
```
2. Check if the alerts are in the Dashboard

   
   ![imagen](https://github.com/wazuh/wazuh/assets/14501079/67debd8f-fc7e-423b-be6e-9ba6e0392c5d)
   

<details>
<summary>Alert information</summary>

```
{
  "_index": "wazuh-alerts-4.x-env-2-2023.09.27",
  "_id": "o1ev2IoBhyp-9nnP8PlE",
  "_version": 1,
  "_score": null,
  "_source": {
    "predecoder": {
      "hostname": "ip-10-0-1-199",
      "program_name": "sshd",
      "timestamp": "Sep 27 22:08:39"
    },
    "cluster": {
      "node": "master",
      "name": "wazuh2"
    },
    "agent": {
      "ip": "10.0.1.199",
      "name": "Amazon",
      "id": "001"
    },
    "data": {
      "srcuser": "fake-user",
      "srcip": "45.178.1.193"
    },
    "manager": {
      "name": "wazuh-manager-master-0"
    },
    "rule": {
      "mail": false,
      "level": 5,
      "hipaa": [
        "164.312.b"
      ],
      "pci_dss": [
        "10.2.4",
        "10.2.5",
        "10.6.1"
      ],
      "tsc": [
        "CC6.1",
        "CC6.8",
        "CC7.2",
        "CC7.3"
      ],
      "description": "sshd: Attempt to login using a non-existent user",
      "groups": [
        "syslog",
        "sshd",
        "authentication_failed",
        "invalid_login"
      ],
      "nist_800_53": [
        "AU.14",
        "AC.7",
        "AU.6"
      ],
      "gdpr": [
        "IV_35.7.d",
        "IV_32.2"
      ],
      "firedtimes": 4,
      "mitre": {
        "technique": [
          "Password Guessing",
          "SSH"
        ],
        "id": [
          "T1110.001",
          "T1021.004"
        ],
        "tactic": [
          "Credential Access",
          "Lateral Movement"
        ]
      },
      "id": "5710",
      "gpg13": [
        "7.1"
      ]
    },
    "decoder": {
      "parent": "sshd",
      "name": "sshd"
    },
    "full_log": "Sep 27 22:08:39 ip-10-0-1-199 sshd[29313]: Failed password for invalid user fake-user from 45.178.1.193 port 11115 ssh2",
    "input": {
      "type": "log"
    },
    "location": "/var/log/secure",
    "id": "1695852521.169752175",
    "GeoLocation": {
      "city_name": "San Luis",
      "country_name": "Argentina",
      "region_name": "San Luis",
      "location": {
        "lon": -66.354,
        "lat": -33.299
      }
    },
    "timestamp": "2023-09-27T22:08:41.854+0000"
  },
  "fields": {
    "timestamp": [
      "2023-09-27T22:08:41.854Z"
    ]
  },
  "highlight": {
    "cluster.name": [
      "@opensearch-dashboards-highlighted-field@wazuh2@/opensearch-dashboards-highlighted-field@"
    ],
    "GeoLocation.city_name": [
      "@opensearch-dashboards-highlighted-field@San Luis@/opensearch-dashboards-highlighted-field@"
    ],
    "agent.name": [
      "@opensearch-dashboards-highlighted-field@Amazon@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1695852521854
  ]
}
```

</details>

**Comment by Deblintrake09** [comment]
# T8: Search works without specifying a field and using * :green_circle: 

- `*`
![*](https://github.com/wazuh/wazuh/assets/14501079/2c4fc82a-dd0e-45f2-9165-ec25c3f49f6c)

- `aw*`
![aw*](https://github.com/wazuh/wazuh/assets/14501079/ac70d568-25bb-4d8c-beac-583a066c50c7)

- `*squer*`
![*squer*](https://github.com/wazuh/wazuh/assets/14501079/d7e43c0e-eeb4-46f5-bc79-70a7aa6cf304)

- `*shd`
![*shd](https://github.com/wazuh/wazuh/assets/14501079/f1abba46-fc20-459b-a3ab-08f547454f9a)

**Comment by fcaffieri** [comment]
LGTM

**Comment by davidcr01** [comment]
LGTM

**Comment by juliamagan** [comment]
LGTM
