### ISSUE TITLE
Release 4.6.0 - Beta 1

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19166]
The following issue will gather all the info regarding testing and fixing in order to validate this release stage.

The definition of done for this task is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes, all the issues from below must be closed.

## QA testing issues

In order to move to a new stage or the GA version, all tests and metrics analyses below must be in Closed status.

| Name                          | Issue | Status                      |DRI                  |
|-------------------------------|-------|-----------------------------|---------------------|
| C unit                        | https://github.com/wazuh/wazuh/issues/19248   | :purple_circle: Completed| @wazuh/core         |
| Python unit                   | https://github.com/wazuh/wazuh/issues/19197     | :purple_circle: Completed | @wazuh/framework    |
| Footprint metrics             | https://github.com/wazuh/wazuh/issues/19172     | :red_circle: Completed with failures | @wazuh/qa           |
| Workload benchmarks metrics   |  https://github.com/wazuh/wazuh/issues/19202     | :red_circle: Completed with failures | @wazuh/framework    |
| Integration                   | https://github.com/wazuh/wazuh/issues/19198    | :red_circle: Completed with failures | @wazuh/qa           |
| API integration               | https://github.com/wazuh/wazuh/issues/19201| :purple_circle: Completed | @wazuh/framework    |
| System                        | https://github.com/wazuh/wazuh/issues/19255    |  :purple_circle: Completed | @wazuh/qa           |
| External integrations modules | -     | :white_circle: Skipped     | @wazuh/framework    |
| Demo uses cases               | #19223     |:purple_circle: Completed | @wazuh/cicd         |
| Packages                      | https://github.com/wazuh/wazuh/issues/19211   | :red_circle: Completed with failures | @wazuh/qa           |
| Coverity scan                 | https://github.com/wazuh/wazuh/issues/19250   | :purple_circle: Completed  | @wazuh/core         |
| Ruleset                       | #19214     | :purple_circle: Completed | @wazuh/threat-intel |
| Wazuh UI regression          | https://github.com/wazuh/wazuh-kibana-app/issues/5937    | :purple_circle: Completed | @wazuh/frontend     |
| WPK Upgrade                   | #19213 |  :purple_circle: Completed | @wazuh/core         |
| E2E UX | https://github.com/wazuh/wazuh/issues/19165 | :red_circle: Completed with failures | @wazuh |

:white_circle: Skipped: The task has been deemed unnecessary for this stage.
:brown_circle:  Partially skipped:  Some parts of the task are skipped.
:black_circle: Not finished: The tasks haven't been finished yet.
:purple_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.

**Comment by damarisg** [comment]
# Summary: All except E2E UX

## New Issues:
- https://github.com/wazuh/wazuh-qa/issues/4557
- https://github.com/wazuh/wazuh-qa/issues/4556
- https://github.com/wazuh/wazuh-jenkins/issues/5720
- https://github.com/wazuh/wazuh-jenkins/issues/5695
- https://github.com/wazuh/wazuh-packages/issues/2489
- https://github.com/wazuh/wazuh/issues/19251

## Known Issues: 

### wazuh
- https://github.com/wazuh/wazuh/issues/17945
- https://github.com/wazuh/wazuh/issues/14664
- https://github.com/wazuh/wazuh/issues/18895
- https://github.com/wazuh/wazuh/issues/17025
- https://github.com/wazuh/wazuh/issues/17957
- https://github.com/wazuh/wazuh/issues/18598
- https://github.com/wazuh/wazuh/issues/17596
- https://github.com/wazuh/wazuh/issues/8263
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- 
- 
- 
- 

### wazuh-jenkins
- https://github.com/wazuh/wazuh-jenkins/issues/5694
- 
- 

### wazuh-qa
- https://github.com/wazuh/wazuh-qa/issues/4230

### wazuh-packages
- https://github.com/wazuh/wazuh-packages/issues/2139
- https://github.com/wazuh/wazuh-packages/issues/2099
-

**Comment by damarisg** [comment]
# Summary: All except E2E UX

## New Issues:
- https://github.com/wazuh/wazuh-qa/issues/4557
- https://github.com/wazuh/wazuh-qa/issues/4556
- https://github.com/wazuh/wazuh-jenkins/issues/5720
- https://github.com/wazuh/wazuh-jenkins/issues/5695
- https://github.com/wazuh/wazuh-packages/issues/2489
- https://github.com/wazuh/wazuh/issues/19251
- https://github.com/wazuh/wazuh/issues/19222
- https://github.com/wazuh/wazuh/issues/19310

## Known Issues: 

### wazuh
- https://github.com/wazuh/wazuh/issues/17945
- https://github.com/wazuh/wazuh/issues/14664
- https://github.com/wazuh/wazuh/issues/18895
- https://github.com/wazuh/wazuh/issues/17025
- https://github.com/wazuh/wazuh/issues/17957
- https://github.com/wazuh/wazuh/issues/18598
- https://github.com/wazuh/wazuh/issues/17596
- https://github.com/wazuh/wazuh/issues/8263
- https://github.com/wazuh/wazuh/issues/12074
- https://github.com/wazuh/wazuh/issues/9311
- https://github.com/wazuh/wazuh/issues/17927
- https://github.com/wazuh/wazuh/issues/18179
- https://github.com/wazuh/wazuh/issues/17928
- 

### wazuh-jenkins
- https://github.com/wazuh/wazuh-jenkins/issues/5694
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5538


### wazuh-qa
- https://github.com/wazuh/wazuh-qa/issues/4230

### wazuh-packages
- https://github.com/wazuh/wazuh-packages/issues/2139
- https://github.com/wazuh/wazuh-packages/issues/2099
-
