### ISSUE TITLE
unable to configure Wazuh Email alerts based on the rule ID's guidance please?

### ISSUE THREAD

**Issue by muhammadyasir0906** [wazuh/wazuh#19171]
Because Wazuh have 16 level of email alerts with a lot of rule ID's. I want to create and receive email alerts on particular rule ID's . Waiting for guidance, support & help.

**Comment by muhammadyasir0906** [comment]
Thank you the guidance in this scenario issue has been resolved.
Now we have another issue that same email do not send for more than 1 email
address. Receive email error on the configured email account.

**Comment by jftuduri** [comment]
Ok, I'll ask you for some more information to better understand the situation:
- Wazuh version
- Please share your email-related wazuh configuration from `ossec.conf`:
  - `<global>`
  - `<email_alert_level>`
  - `<email_alerts>`
- If you have created/modified any rule regarding the email alert please share them.

Remember to obfuscate any sensitive information, like email addresses, before posting the data here.

> Now we have another issue that same email do not send for more than 1 email
address.

If I understand this correctly you are expecting to receive the same alert **in more than 1** email address, but you are only receiving the alert in one address. Is this correct?

> Receive email error on the configured email account.

Please post this error message.

Regards!

**Comment by muhammadyasir0906** [comment]
Dear Support,
Happy to answer you.

   - Wazuh version = wazuh-4.4.2(in testing environment but have to
   implement 4.5.2 latest version in production.)

<ossec_config>
  <global>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    ***@***.***</email_from>
    ***@***.***</email_to>
    <email_maxperhour>12</email_maxperhour>
  </global>
  <alerts>
    <email_alert_level>12</email_alert_level>
  </alerts>
</ossec_config>

If I understand this correctly you are expecting to receive the same alert *in
more than 1* email address, but you are only receiving the alert in one
address. Is this correct?

Yes exactly.

<ossec_config>
  <global>

    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    ***@***.***</email_from>
    ***@***.***</email_to>
    <email_maxperhour>12</email_maxperhour>
  </global>

  <alerts>
    <email_alert_level>9</email_alert_level>
  </alerts>

</ossec_config><ossec_config>

  <global>

    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    ***@***.***</email_from>
    ***@***.***</email_to>
    <email_maxperhour>12</email_maxperhour>
  </global>

  <alerts>
    <email_alert_level>9</email_alert_level>
  </alerts>


If I understand this correctly you are expecting to receive the same
alert *in more than 1* email address, but you are only receiving the
alert in one address. Is this correct?

</ossec_config>

**Comment by jftuduri** [comment]
Hi!
It is not too clear what is the configuration that you are using.
Are you repeating the `<global>` block?

You can set [multiple emails](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#email-to)(`<email_to>test@test.com</email_to>`) inside the `<global>` tag in `ossec.conf` and Wazuh will send an alert to those mail based on `<email_alert_level>`
For example:

```
<ossec_config>
    <global>
        <email_notification>yes</email_notification>
        <email_to>address_1@test.com</email_to>
        <email_to>address_2@test.com</email_to>
        <email_to>address_3@test.com</email_to>
        <smtp_server>mail.test.com</smtp_server>
        <email_from>wazuh@test.com</email_from>
    </global>
    ...
</ossec_config>
```

Could you try with a configuration in that style?

Also, you mention that you are getting an error. Can you paste that error here, please? Where do you see that error?

**Comment by muhammadyasir0906** [comment]
Dear Support Team
this is case.

<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    ***@***.***</email_from>
    <email_maxperhour>100</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>3</email_alert_level>
  </alerts>

  <email_alerts>
    ***@***.***</email_to>
    <rule_id>5760</rule_id>
    <do_not_delay />
  </email_alerts>

  <email_alerts>
    ***@***.***</email_to>
    <rule_id>5760</rule_id>
    <do_not_delay />
  </email_alerts>
</ossec_config>

If we try to send an email alert of the same rule to more than 01 emails,
we get this below error.

This is the mail system at host wazuh-server.localdomain.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to the postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

< ***@***.***>: host smtp.gmail.com[74.125.130.108] said: 550-5.7.1
This
    message is not RFC 5322 compliant. There are multiple To headers.
550-5.7.1
    To reduce the amount of spam sent to Gmail, this message has been
550-5.7.1
    blocked. Please visit 550 5.7.1
    https://support.google.com/mail/?p=RfcMessageNonCompliant
    s4-20020a170902a50400b001b567bbe82dsm10585660plq.150 - gsmtp (in reply
to
    end of DATA command)

< ***@***.***>: host smtp.gmail.com[74.125.130.108] said: 550-5.7.1
    This message is not RFC 5322 compliant. There are multiple To headers.
    550-5.7.1 To reduce the amount of spam sent to Gmail, this message has
been
    550-5.7.1 blocked. Please visit 550 5.7.1
    https://support.google.com/mail/?p=RfcMessageNonCompliant
    s4-20020a170902a50400b001b567bbe82dsm10585660plq.150 - gsmtp (in reply
to
    end of DATA command)



---------- Forwarded message ----------
From: Wazuh ***@***.*** ***@***.***>>
To: < ***@***.***>,< ***@***.***>
Cc:
Bcc:
Date: Tue, 26 Sep 2023 10:24:46 +0000
Subject: Wazuh notification - wazuh-server - Alert level 5

Wazuh Notification.
2023 Sep 26 10:24:44

Received From: wazuh-server->/var/log/secure
Rule: 5760 fired (level 5) -> "sshd: authentication failed."
Src IP: 192.
User: wazuh-user
Portion of the log(s):

Sep 26 10:24:44 wazuh-server sshd[12628]: Failed password for wazuh-user
from 192. port 6211 ssh2




 --END OF NOTIFICATION

**Comment by jftuduri** [comment]
After seeing the error message that you are receiving I've found that this problem has already been reported here:

[https://github.com/wazuh/wazuh/issues/14824](https://github.com/wazuh/wazuh/issues/14824)

You can take a look at that issue to confirm that you are in the same situation, and you can add your case for future reference.

Indeed, in some situations, there is a problem in the way that the recipients of the email message are constructed that makes it not compliant with the standard, and some servers, like Gmail, are validating that and rejecting the messages.

Regards!

**Comment by muhammadyasir0906** [comment]
Yeah facing the same so what is solution or the alternative?

**Comment by jftuduri** [comment]
Hi!
As an alternative you may consider these options:

- Wazuh's integration with external APIs: https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html
  - Please take a look at the Slack and/or Shuffle integration to receive alert notifications.
- Wazuh's custom integration capability: https://documentation.wazuh.com/current/user-manual/manager/manual-integration.html#custom-integration
  - You can develop a script that sends the email notifications or communicates with your API.
  - You can take a look at this script to get started: https://github.com/jctello/JCT-Wazuh/blob/main/integrations/custom-email-alerts. It will probably need some customization on your part.
- You can configure the email alerts using only one email address and then automatically forward these alerts to the other email addresses.
  - If you are using gmail you can create a filter for the Wazuh alerts that forwards the message to the other addresses: https://support.google.com/mail/answer/6579?sjid=2984082458683992271-SA

I realize these options are not as simple as just configuring the email addresses on the ossec.conf, but they may also provide more flexibility.
Sorry for the inconvenience.

Regards!

**Comment by muhammadyasir0906** [comment]
Thanks, I'll check them out.
