### ISSUE TITLE
Check Wazuh compatibility with new version macOS Sonoma 14 [x86_64]

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#19205]
# Description
This issue is to check the full compatibility of Wazuh on the new found version of macOS Sonoma 14 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/17387

NOTE: macOS Sonoma 14 was supposed released on 06/05/2023, just for registered developers, and it's expected to be publicly opened on July 2023

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] O.S. reporting in the interface.
- [x] WPK installation / upgrade / uninstall / upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Just scheduled mode (realtime and whodata not available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by lchico** [comment]
# Tested on: arm64 

###   :green_circle:  Agent and server, (enrollment and connectivity with the manager)
![enrollment_connectivity](https://github.com/wazuh/wazuh/assets/21695385/f9dc68eb-9863-42a1-91ff-83e8d1d2f348)

###  :green_circle: Correct uninstall after upgrade
I was able to uninstall and reinstall the wazuh-agent [following those stpes](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#:~:text=after%20the%20installation.-,Uninstall%20a%20Wazuh%20agent,-Permalink%20to%20this)

###  :green_circle: FIM: Real-time 
Configuration:
```
    <directories realtime="yes">/var/log/testrealtime</directories>
    <directories whodata="yes">/var/log/testwhodata</directories>
```
![fim_realtime](https://github.com/wazuh/wazuh/assets/21695385/65263f52-cd52-4fbe-9f14-21f8c5ad4f83)
![fim_whodata](https://github.com/wazuh/wazuh/assets/21695385/295fa70d-c221-4f6a-9cf5-a39c4d757bc5)

### :green_circle: Syscollector
![syscollector](https://github.com/wazuh/wazuh/assets/21695385/59e0da34-ff02-4a54-8074-56d2c83f8332)

###  :green_circle: Active response
![active_response](https://github.com/wazuh/wazuh/assets/21695385/6ed73611-47d3-4db0-b6cf-0a0e7fe1e035)

### :green_circle: Log capture (Eventchannel for Windows and ULS for macOS).
![log_capture](https://github.com/wazuh/wazuh/assets/21695385/2053216c-8836-4206-88d1-229a191438ed)

### :green_circle: Vulnerability Detector: Vulnerability support
![vulnerabilities](https://github.com/wazuh/wazuh/assets/21695385/caf540fd-6dae-440b-8471-121909b4c95e)

### :red_circle: Upgrade using WPK
![wpk](https://github.com/wazuh/wazuh/assets/21695385/33bc61c5-0d7c-4fde-8294-b62ec0ef9646)

### :green_circle:  ~SCA: Policy support~: Does not apply until 4.8.0 -> https://github.com/wazuh/wazuh/issues/18306

**Comment by lchico** [comment]
I created this issue https://github.com/wazuh/wazuh/issues/19308 for the WPK bug.

**Comment by lchico** [comment]
Blocked by issue https://github.com/wazuh/internal-devel-requests/issues/255.

**Comment by jotacarma90** [comment]
LGTM
