### ISSUE TITLE
Release 4.6.0 - Beta 1 - API integration tests

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#19201]
The following issue aims to run all [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) for the current release candidate, report the results, and open new issues for any encountered errors.

## API integration tests information
|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         | [19116](https://github.com/wazuh/wazuh/issues/19166) |
| **Version**                              | 4.6.0 |
| **Release candidate #**                  | Beta1 |
| **Tag**                                  | [v4.6.0-beta1](https://github.com/wazuh/wazuh/tree/v4.6.0-beta1) |
| **Previous API integration tests issue** | [17449](https://github.com/wazuh/wazuh/issues/17729) |

## Test report procedure

All individual test checks must be marked as:

| Result                          | Description                                |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one of the following statuses: 

| Status                          | Description                                |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed "check". |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be appropriately addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate's main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended test results report must be attached as a zip or text. The auditors can use this report to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/19201#issuecomment-1733614621).

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Validation of auditors

All checks from below must be accepted to close this issue.

- [x] @Selutario

**Comment by damarisg** [comment]
LGTM!
