### ISSUE TITLE
The new permissions could not be added to the JSON alert

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19219]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3 RC 1| wazuh-analysisd | Manager | Packages | CentOS 7 |

## Description

In the analysis of the issue https://github.com/wazuh/wazuh/issues/19179 the following error was found:

```
manager/var/ossec/logs/ossec.log:2023/09/24 00:29:56 wazuh-analysisd: ERROR: The new permissions could not be added to the JSON alert.
```

This error was reported in the past and fixed for 4.5.0

## Related

- https://github.com/wazuh/wazuh/issues/12073

**Comment by vikman90** [comment]
@rauldpm This issue is related to https://github.com/wazuh/wazuh/issues/12073, fixed in 4.6.0.
