### ISSUE TITLE
Release 4.6.0 - Beta 1 - Ruleset

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#19214]
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #19166 |
| **Version** | 4.6.0                               |
| **Release candidate #** | Beta 1                                   |
| **Tag** | [v4.6.0-beta1](https://github.com/wazuh/wazuh/tree/v4.6.0-beta1) |
| **Previous ruleset  test** | #18880 |

**Comment by Johnng007** [comment]
# Test results


|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1375   |   4370   |  31.46%  |
| Decoders |   125    |   170    |  73.53%  |

**Comment by ooniagbi** [comment]
LGTM!

**Comment by juliamagan** [comment]
LGTM
