### ISSUE TITLE
Disk_Read significantly reduced in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19220]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc1 | Modulesd and agentd | Agent | Packages| OS version |

In stress test : https://github.com/wazuh/wazuh/issues/19177
It was possible to see a big change of pattern of use of disk_read of modulesd and agentd

4.5.3-rc1
![image](https://github.com/wazuh/wazuh/assets/125690423/b777ea8a-4ad1-40b9-8e70-833f293130c6)

4.5.2-rc1
![image](https://github.com/wazuh/wazuh/assets/125690423/ba61ee05-9ee6-4be3-b3d2-f52c30689d9b)

Further research should be done

**Comment by nmkoremblum** [comment]
I am sorry, I do not understand, the graphs do not match the description. What are you comparing? Managers? Agents? Which agents?

**Comment by nmkoremblum** [comment]
On the other hand, when we look at the 'disk_read' curves, it's not clear how they relate to the stress section. This might be because there are external factors at play that the test can't control. So, comparing these curves in the tests might not be very useful, as they aren't predictable within the testing environment.

**Comment by cborla** [comment]
The 4.5.2-rc1 graph is:

![image](https://github.com/wazuh/wazuh/assets/41765669/d7e21fbe-c4e3-4b92-82e9-3dd38a3ba403)

Comparing the disk reading between 4.5.2 and 4.5.3 we find that the reading is considerably reduced.

Version 4.5.2 ->more than 1,200,000 disk reads.
Version 4.5.3 ->more than 15,000 disk reads.

To the best of my knowledge there is no disk reading problem in the new version.
