### ISSUE TITLE
Error decoding windows events with spaced usernames

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#1922]
## Bug report

**OS**
_Windows_

**Wazuh version**
_3.7.0_

**Install type**
_agent_

**Install method**
_packages/sources_

**Log sample**

```
ossec-analysisd: ERROR: at fim_db_search: Agent '001' Couldn't decode fim sum '438:33206:S-1-5-20::e98746d49fd117e95fc4a6726a640b85:1b326b7bb37f20ddee068b54c40e801b1e0a8309:Servicio' from file 'de red::1542715243:0:1ed7fe7d8023892c755b2daf7cf6643f6d762b29912cf150772626ac2b46edb1!::::::::::: c:\windows\ServiceProfiles\NetworkService\AppData\LocalLow\Microsoft\CryptnetUrlCache\MetaData\6BADA8974A10C4BD62CC921D13E43B18_D9817BD5013875AD517DA73475345203'.

```

Bug description
----------------
On Windows systems, you can get usernames with spaces. This causes the FIM event decoder to malfunction. The expected string only contains one space (not escaped) that separates the checksum from the path.
```
size:permision:uid:gid:md5:sha1:uname:gname:mtime:inode:sha256!w:h:o:d:a:t:a:tags filename\nreportdiff"
^^^^^^^^^^^^^^^^^^^^^^^^^^^checksum^^^^^^^^^^^^^^^^^^^^^^^^^^^!^^^^extradata^^^^^ ^^path^^\n^^^diff^^^'
```
We need to escape the spaces in the `uname` field.

**Comment by snaow** [comment]
Work in progress.
Branch: https://github.com/wazuh/wazuh/compare/3.7...fix-win-username
Assigning to current week milestone and project 3.7.1.
