### ISSUE TITLE
HP-UX Wazuh agent package size increased considerably

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#19251]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|v4.6.0-beta1 | Wazuh agent package | Agent | Packages | HP-UX|

# Description

During https://github.com/wazuh/wazuh/issues/19212, it was found that HP-UX Wazuh Agent size has the next increase
- https://packages-dev.wazuh.com/pre-release/hp-ux/wazuh-agent-4.6.0-1-hpux-11v3-ia64.tar 53MB
- https://packages.wazuh.com/4.x/hp-ux/wazuh-agent-4.5.2-1-hpux-11v3-ia64.tar is 21MB (last production version)

Size is related to packaging the next libraries

![image](https://github.com/wazuh/wazuh/assets/1791430/5fcd2634-f50a-4bc0-8156-4c57d1af7244)

# DoD

- [x] Make sure that those libraries are deployed/installed as wanted
- [x] Research if there's any tweak to improve package size

**Comment by MiguelazoDS** [comment]
The behavior also occurs with AIX, but since the package is a RPM the compression does not let us see the difference in size with the addition of libstdc++6.so 

![image](https://github.com/wazuh/wazuh/assets/13010397/60f924a5-1f9f-4fb1-bf47-dcd7b7a0391d)
![image](https://github.com/wazuh/wazuh/assets/13010397/87ee7b88-688a-4127-a185-2c8557593b36)

**Comment by MiguelazoDS** [comment]
- Compilation error found

![image](https://github.com/wazuh/wazuh/assets/13010397/404e14f8-98b0-4ab7-b95f-c7771f6d7db4)

Minimal example to reproduce the issue with `<algorithm>` 

```cpp
#include <algorithm>
#include <iostream>
#include <vector>

int main(int argc, char** argv) {
  int myints[] = {10, 20, 30, 40};
  int* p;

  p = std::find(myints, myints + 4, 30);
  if (p != myints + 4)
    std::cout << "Element found in myints: " << *p << '\n';
  else
    std::cout << "Element not found in myints\n";

  // using std::find with vector and iterator:
  std::vector<int> myvector(myints, myints + 4);
  std::vector<int>::iterator it;

  it = find(myvector.begin(), myvector.end(), 30);
  if (it != myvector.end())
    std::cout << "Element found in myvector: " << *it << '\n';
  else
    std::cout << "Element not found in myvector\n";

  return 0;
}
```

**Comment by sebasfalcone** [comment]
Moved ETA -> Waiting for final review

**Comment by jnasselle** [comment]
@MiguelazoDS ,

Friendly reminder: if anything release-related is changed, make sure to search it in the whole Wazuh organization

New issue https://github.com/wazuh/wazuh-jenkins/issues/6345
