### ISSUE TITLE
Engine - Enhancements in the Windows Decoder

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#19268]
| Wazuh version | Component   | Install type | Install method | Platform |
|---------------|-------------|--------------|----------------|----------|
| 5.0           | Wazuh Engine| Manager      | Packages/Sources| any      |

### Description
There is a need to enhance and fix the Windows decoder in the Wazuh project. This set of changes aims to address various identified issues in the Windows decoder. The proposed fixes and improvements include:

- [x] **Unnecessary Single Quotes Used**: Remove the single quotes from the mentioned lines in the `windows-security.yml` file.
   - Line 38-39: Remove single quotes from around `kvdb_decode_bitmask`.
   - Line 46: Remove single quotes from around `kvdb_decode_bitmask`.
   - Line 104: Remove single quotes from around `kvdb_decode_bitmask`.

- [x] **Review/Remove TODO Comments**:
   - Line 37 and 45: Review these comments and replace "TODO" with the specific field name if it's known. If not, remove the comments.
   - Line 333: Decide whether this TODO comment is still relevant. If not, remove it.
   - Line 334: Remove this line if it's no longer necessary.

- [x] **Empty Fields Are Being Indexed**:
   - Investigate where the empty fields like "input" or "log.file" are coming from and address the issue. It might be related to system decoders or Filebeat.

- [ ] **Remove "fields" Field (Out of _source Object)**:
   - Identify why the "fields" field is present in indexed documents. If it's related to Filebeat configuration, address it by removing redundant fields.

- [x] **We Are Missing the Message Field of Windows Events**:
   - Investigate how Winlogbeat translates Windows event IDs into human-readable messages and whether it can be done using a KVDB for Wazuh.
   - Consider adding a short description of the event to the message field.
   - Explore the possibility of using a translation table for Windows event IDs, such as the one provided in the example, and remove variables like %1 or %2.
   - Check for an official and up-to-date source for event descriptions.

- [x] **Stop Working With Numbers for the Queues**:
   - Consider creating a translation configuration file for queue names to make it more intuitive for users.
   - Ensure that users don't need to know numeric values for queues, even when debugging at a low level.
   - Modify the test command to use a more intuitive queue name, e.g., "windows" instead of "-q f."
   - Consider renaming the field to "wazuh.queue: windows" for clarity.

**Comment by JavierBejMen** [comment]
## Remove field `fields` from dashboard events

The field `fields` is added by filebeat, but cannot be removed with a drop_fields processor as it is added at a later stage. More research is needed to see if it can be dropped or prevented by a filebeat configuration setting. Currently, in the engine, we do not use any filebeat module, as opposed to the current Wazuh implementation where it is dropped.
