### ISSUE TITLE
Unable to delete agents from Wazuh Dashboard

### ISSUE THREAD

**Issue by uaSandy** [wazuh/wazuh#19289]
Hi Team,

I am using Wazuh Saas version. I am unable to deploy an agent due to duplicate name. Hence I would like to delete agents from the dashboard. I am getting error while deleting the agents through API console. Could you please help me out.

Error : Agent only belongs to 'default' and it cannot be unassigned from this group

Note : Please note i do not wish to Unassigned an agent , i am looking out for deleting the same so that i can redeploy the agent

**Comment by AlexRuiz7** [comment]
Are you using this API endpoint? 

https://documentation.wazuh.com/current/user-manual/api/reference.html#tag/Agents
