### ISSUE TITLE
GCP dependencies install fail in Ubuntu 18.04

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19284]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-beta1| GCP wodle | Manager/Agent | Packages | Ubuntu 18.04 |

In the testing issue https://github.com/wazuh/wazuh/issues/19147, a problem was found installing the necessary Python dependencies on Ubuntu 18.

The documentation states that Python 3.7 or higher is required, but this system installs version 3.6 as the most up-to-date, having to resort to external methods to install the required version. This means that if version 3.7 is installed there would be two situations:

1. It is necessary to change the python3 binding to point to python3.7, this affects the entire system which can break the user's environment if they have something that uses python3.6 and that is not compatible with python3.7
2. It is necessary to change the references of all Python files in `/var/ossec` that use python3, which means that for the GCP wodle to work, other components are affected, such as the Azure wodle

These two cases are not viable due to the following reasons:

1. Modifying the version of Python at the system level can cause the system to crash due to external dependencies on other programs
2. Modifying the wodles scripts should not be the responsibility of the user, in addition to the fact that it is a modification of the native installation

In the case of using the system's native version of Python (3.6), the installation of the dependencies has failed:

```
Attempting uninstall: pyasn1-modules
     Found existing installation: pyasn1-modules 0.2.1
ERROR: Cannot uninstall 'pyasn1-modules'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

This assumes that the GCP wodle offers partial compatibility on the recommended systems, since the next recommended version is Ubuntu 20, which contains Python 3.8, it is necessary to evaluate the impact of the Python 3.7 version requirement with respect to the recommended systems and apply one of the following initial options:

- [ ] Allow the use of Python 3.6 in order to support at least Ubuntu 18, Ubuntu 16, and other systems that do not have Python 3.7
- [ ] Explicitly indicate in the documentation that the wodle does not work on systems that do not support 3.7 and that this includes some recommended systems
- [ ] TBD

**Comment by Selutario** [comment]
After discussing this with @havidarou, it was decided that since the minimum required Python version is clearly specified in the documentation, we do not need to make any additional changes. The responsibility of using an appropriate system to run wodles falls on the users.
