### ISSUE TITLE
Release 4.5.3 - RC 2 - E2E UX tests - macOs

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#19297]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.5.3-rc2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/early-birds team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.5.3-rc2/quickstart.html) | - | RHEL 7 x86_64 |
| Server | [Quickstart](https://documentation-dev.wazuh.com/v4.5.3-rc2/quickstart.html) | - | RHEL 7 x86_64 |
| Dashboard | [Quickstart](https://documentation-dev.wazuh.com/v4.5.3-rc2/quickstart.html) | - | RHEL 7 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.5.3-rc2/installation-guide/wazuh-agent/index.html) | - | macOS Sonoma x86_64, macOS Sonoma arm |

## Test description

Test that macOs data collection works out of the box. 
Test that macOs vulnerability works out of the box.
Test that macOs file integrity monitoring works out of the box.  
Test that macOs security configuration assesment works out of the box.  

## Known issues

- https://github.com/wazuh/wazuh/issues/15580
- https://github.com/wazuh/wazuh/issues/19205
- https://github.com/wazuh/wazuh/issues/19308
- https://github.com/wazuh/wazuh/issues/17151
- https://github.com/wazuh/wazuh/issues/8602

## Conclusions

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢  | Indexer | - | - |
| 🟢  | Server | - | -  |
| 🟢  | Dashboard | - | - |
| 🔴 | Agent (x86_64) | syscheck and vulnerability detector do not work | #17151 #8602 |
| 🔴 | Agent (arm) | syscheck and vulnerability detector do not work | #17151 #8602  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
- Did you face any challenges not covered by the guideline?

> Performing the tests was complicated as we had to share the VMs with other teams.

- Suggestions for improvement:

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias 
- [x] @wazuh/early-birds

**Comment by nmkoremblum** [comment]
```
[root@ip-172-31-71-198 ec2-user]# cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
```

**Comment by nmkoremblum** [comment]
### Agent (macOS Sonoma INTEL) :red_circle: 

Installation of the agent on macOS Sonoma Intel was successful

```         
sh-3.2# echo "WAZUH_MANAGER='44.192.72.98'" > /tmp/wazuh_envs && installer -pkg /Users/dwordcito/wazuh.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```

```
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd not running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

Agent cannot connect to the manager
```
2023/09/29 07:24:23 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2023/09/29 07:24:23 wazuh-agentd: INFO: Using AES as encryption method.
2023/09/29 07:24:23 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:25:34 wazuh-agentd: INFO: Closing connection to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:25:34 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:26:44 wazuh-agentd: INFO: Closing connection to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:26:44 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:27:54 wazuh-agentd: INFO: Closing connection to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:27:54 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:29:05 wazuh-agentd: INFO: Closing connection to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:29:05 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:30:05 wazuh-agentd: INFO: Requesting a key from server: 44.192.72.98
2023/09/29 07:30:05 wazuh-agentd: INFO: No authentication password provided
2023/09/29 07:30:05 wazuh-agentd: INFO: Using agent name as: dwordcitos-iMac-Pro-3.local
2023/09/29 07:30:05 wazuh-agentd: INFO: Waiting for server reply
2023/09/29 07:30:06 wazuh-agentd: ERROR: Duplicate agent name: dwordcitos-iMac-Pro-3.local (from manager)
2023/09/29 07:30:06 wazuh-agentd: ERROR: Unable to add agent (from manager)
2023/09/29 07:30:16 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '44.192.72.98'.
2023/09/29 07:30:16 wazuh-agentd: WARNING: Unable to connect to any server.
2023/09/29 07:30:16 wazuh-agentd: INFO: Closing connection to server ([44.192.72.98]:1514/tcp).
2023/09/29 07:30:16 wazuh-agentd: INFO: Trying to connect to server ([44.192.72.98]:1514/tcp).
```

From the manager's side:

- ossec.log
```
2023/09/29 14:24:03 wazuh-authd: INFO: New connection from 181.90.143.45
2023/09/29 14:24:03 wazuh-authd: INFO: Received request for a new agent (dwordcitos-iMac-Pro-3.local) from: 181.90.143.45
2023/09/29 14:24:03 wazuh-authd: INFO: Agent key generated for 'dwordcitos-iMac-Pro-3.local' (requested by any)
2023/09/29 14:24:06 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2023/09/29 14:24:06 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2023/09/29 14:24:24 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:25:34 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:26:44 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:27:55 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:29:05 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:30:06 wazuh-authd: INFO: New connection from 181.90.143.45
2023/09/29 14:30:06 wazuh-authd: INFO: Received request for a new agent (dwordcitos-iMac-Pro-3.local) from: 181.90.143.45
2023/09/29 14:30:06 wazuh-authd: WARNING: Duplicate name 'dwordcitos-iMac-Pro-3.local', rejecting enrollment. Agent '001' doesn't comply with the registration time to be removed.
2023/09/29 14:30:16 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:31:26 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:32:37 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:33:47 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:34:58 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:35:58 wazuh-authd: INFO: New connection from 181.90.143.45
2023/09/29 14:35:58 wazuh-authd: INFO: Received request for a new agent (dwordcitos-iMac-Pro-3.local) from: 181.90.143.45
2023/09/29 14:35:58 wazuh-authd: WARNING: Duplicate name 'dwordcitos-iMac-Pro-3.local', rejecting enrollment. Agent '001' doesn't comply with the registration time to be removed.
2023/09/29 14:36:09 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:37:19 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:38:29 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
2023/09/29 14:39:39 wazuh-remoted: WARNING: Invalid message from agent: 'dwordcitos-iMac-Pro-3.local' (001)
```

```
[root@ip-172-31-71-198 ec2-user]# /var/ossec/bin/manage_agents 

****************************************
* Wazuh v4.5.3 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: L

Available agents: 
   ID: 001, Name: dwordcitos-iMac-Pro-3.local, IP: any

** Press ENTER to return to the main menu.
```

**Comment by nmkoremblum** [comment]
### Agent (macOS Sonoma ARM) 🟢

Installation of the agent on macOS Sonoma ARM was successful

```
sh-3.2# curl https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.5.3-1.arm64.pkg -o wazuh.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5209k  100 5209k    0     0  2439k      0  0:00:02  0:00:02 --:--:-- 2450k
sh-3.2# pwd
/Users/w
sh-3.2# echo "WAZUH_MANAGER='44.192.72.98'" > /tmp/wazuh_envs && installer -pkg /Users/w/wazuh.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd not running...
wazuh-logcollector not running...
wazuh-syscheckd not running...
wazuh-agentd not running...
wazuh-execd not running...
sh-3.2# launchctl start com.wazuh.agent
sh-3.2# /Library/Ossec/bin/wazuh-control status
wazuh-modulesd is running...
wazuh-logcollector is running...
wazuh-syscheckd is running...
wazuh-agentd is running...
wazuh-execd is running...
```

![image](https://github.com/wazuh/wazuh/assets/75255206/e29bf71c-2b27-4e5e-ba21-5b5af4a39056)

![image](https://github.com/wazuh/wazuh/assets/75255206/f83fc4d0-7bc7-47ed-9b8f-5f4c3301aa8f)

**Comment by nmkoremblum** [comment]
The same observed errors were reported previously on https://github.com/wazuh/wazuh/issues/19107

**Comment by Dwordcito** [comment]
@juliamagan @damarisg everything is ready on our side.

**Comment by davidjiglesias** [comment]
LGTM!
