### ISSUE TITLE
Error: 1210 on Ubuntu 16.04

### ISSUE THREAD

**Issue by PleaseTakeItEasy** [wazuh/wazuh#193]
I installed the .deb 2.1.0 package on Ubuntu through Ansible using the command dpkg -i wazuh.deb. It seemed to install fine but when I try to start Wazuh it says 

2017/09/18 09:37:14 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/18 09:37:14 rootcheck: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/18 09:37:22 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/18 09:37:22 rootcheck: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/18 09:37:35 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2017/09/18 09:37:35 rootcheck: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
ossec-syscheckd did not start

According to Ossec documentation that means that ossec-analysisd is not started. I can't bee able to get very far in the troubleshooting and would like some assistance.

**Comment by vikman90** [comment]
Hi,

did you install a manager or an agent? In the latter case, have you set up an agent key?

That error usually happens when an agent was installed but no key was configured.

Hope it help.

**Comment by PleaseTakeItEasy** [comment]
You were exactly right. It was an issue with the client key. Now it is working.
