### ISSUE TITLE
FIM whodata monitoring is not working on Debian 12 aarch64.

### ISSUE THREAD

**Issue by ace-109** [wazuh/wazuh#19305]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 beta 1 | Wazuh component | Manager/Agent | Packages/Sources | OS version |

The tests carried out in this [issue](https://github.com/wazuh/wazuh/issues/19149) discovered that whodata monitoring is not working correctly on debian 12.

The agent log showed it is in whodata mode

```
root@X.X.X.X:/home/admin# tail -50 /var/ossec/logs/ossec.log | grep "whodata"
2023/09/27 16:45:41 wazuh-syscheckd: INFO: (6003): Monitoring path: '/home/admin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | whodata'.
```

However, on the dashboard, the information shows it is in realtime mode and there was no audit information.

![image](https://github.com/wazuh/wazuh/assets/41423652/8196d71a-6d24-4cfb-a35f-545c124ebaab)

Here is the test information: [#19149 ](https://github.com/wazuh/wazuh/issues/19149#:~:text=Debian%2012%20aarch64-,Who%20data%20mode,-%F0%9F%94%B4)

**Comment by jotacarma90** [comment]
## Problem found

During the execution of the whodata healthcheck (functionality that checks that everything is working correctly), there are problems in identifying the test messages that are made. Therefore, whodata is disabled, and everything is switched to realtime mode.

Reviewing the code of whodata healthcheck I see that to identify the test events, the value of the syscall of the audit message is used:

`type=SYSCALL msg=audit(1695990141. 455:212): arch=c000003e syscall=257 success=yes exit=8 a0=ffffffff9c a1=7ffffc11f9e320 a2=241 a3=1b6 items=2 ppid=1 pid=2404 auid=1000 uid=0 gid=0 euid=0 euid=0 suid=0 fsuid=0 egid=110 sgid=110 fsgid=110 tty=(none) ses=5 comm="wazuh- syscheckd" exe="/var/ossec/bin/wazuh-syscheckd" subj=unconfined key="wazuh_hc "ARCH=x86_64 SYSCALL=openat AUID="vagrant" UID="root" GID="wazuh" EUID="root" SUID="root" FSUID="root" FSUID="root" EGID="wazuh" SGID="wazuh" FSGID="wazuh" FSGID="wazuh"`

In this case 257 for amd64 architecture. However for aarch64 architecture it is 56.


`type=SYSCALL msg=audit(1695830895. 451:32): arch=c00000b7 syscall=56 success=yes exit=8 a0=ffffffffffffffffffffffff9c a1=ffffffffdde22980 a2=241 a3=1b6 items=2 ppid=1 pid=9251 auid=4294967295 uid=0 gid=0 gid=109 euid=0 euid=0 suid=0 fsuid=0 egid=109 sgid=109 fsgid=109 tty=(none) ses=4294967295 comm="wazuh- syscheckd" exe="/var/ossec/bin/wazuh-syscheckd" subj=unconfined key="wazuh_hc "ARCH=aarch64 SYSCALL=openat AUID="unset" UID="root" GID="wazuh" EUID="root" SUID="root" FSUID="root" FSUID="root" EGID="wazuh" SGID="wazuh" FSGID="wazuh"`


This is the function that detects those events, we need to add the syscall values of the new architectures:

https://github.com/wazuh/wazuh/blob/7c5867a85f52ccfe5c54d1ef98f0341895a664c6/src/syscheckd/src/whodata/audit_parse.c#L956-L977
