### ISSUE TITLE
Release 4.5.3 - RC 2 - Integration tests

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#19325]
# Description

| Wazuh QA: Branch | Wazuh QA: Commit | Wazuh: Tag | Wazuh: Commit |
|:--:|:--:|:--:|:--:|
| `v4.5.3-rc2`|  https://github.com/wazuh/wazuh-qa/tree/v4.5.3-rc2 |  `v4.5.3-rc2`  |  https://github.com/wazuh/wazuh/tree/v4.5.3-rc2 | 

We are going to check that the integration tests of the `v4.5.3-rc2`  branch of `wazuh-qa` work correctly using the [v4.5.3-rc2](https://github.com/wazuh/wazuh/tree/v4.5.3-rc2) version of `wazuh`.

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### Main RC issue

https://github.com/wazuh/wazuh/issues/19300

#### References

|Color|Status |
|:--:|:--|
|🟢|All tests passed successfully|
|🟡|All tests passed but there are some warnings|
|🔴|Some tests have failures or errors|
|:large_blue_circle:|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results 

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"> :green_circle:  </td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;"> :green_circle: </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"> :green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"> :green_circle: </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">&nbsp;NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;"> :green_circle: :</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;"> :green_circle:</td>
<td style="width: 97px;"> :green_circle:</td>
<td style="width: 97px;" colspan="2"> :green_circle:  </td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;"> :green_circle:  </td>
<td style="width: 79px;">  :green_circle:  </td>
<td style="width: 97px;"> :green_circle:  </td>
<td style="width: 97px;" colspan="2"> :green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"> :red_circle:   </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;"> :green_circle:  </td>
<td style="width: 79px;"> :red_circle: :  </td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2"> :green_circle: : </td>
</tr>
</tbody>
</table>

## Evidence
- Test Launcher: https://ci.wazuh.info/job/Test_integration_launcher/202/
- Replays
  - FIM: https://ci.wazuh.info/job/Test_integration/43441/ from  :orange_circle: to :green_circle: due to https://github.com/wazuh/wazuh-jenkins/issues/5539
  - Syscollector: https://ci.wazuh.info/job/Test_integration/43439/ from   :orange_circle: to :orange_circle: due to https://github.com/wazuh/wazuh-jenkins/issues/5539
  - Syscollector: https://ci.wazuh.info/job/Test_integration/43446/from   :orange_circle: to :red_circle:  due to https://github.com/wazuh/wazuh-qa/issues/4230 
  - Logcollector: https://ci.wazuh.info/job/Test_integration/43440 from :orange_circle: to :red_circle: (flaky)
  - Logcollector: https://ci.wazuh.info/job/Test_integration/43447/ from :red_circle: to :green_circle: (flaky)

## Conclusion

- Known issues
  - https://github.com/wazuh/wazuh-qa/issues/4429 
  - https://github.com/wazuh/wazuh-jenkins/issues/5539
  - https://github.com/wazuh/wazuh-qa/issues/4568
  - https://github.com/wazuh/wazuh-qa/issues/4230
## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @damarisg

**Comment by jnasselle** [comment]
# Syscollector, logcollector, fim, 

Job https://ci.wazuh.info/job/Test_integration/43387/console

```
20:53:32  Bringing machine 'macos-1015' up with 'virtualbox' provider...
20:53:32  ==> macos-1015: Importing base box 'development/macos-catalina'...
20:53:32  
Progress: 10%
Progress: 90%
20:53:32  
20:53:32  
20:53:32  STDERR:
20:53:32  
20:53:32  There was an error while executing `VBoxManage`, a CLI used by Vagrant
20:53:32  for controlling VirtualBox. The command and stderr is shown below.
20:53:32  
20:53:32  Command: ["import", "/var/root/.vagrant.d/boxes/development-VAGRANTSLASH-macos-catalina/0/virtualbox/box.ovf", "--vsys", "0", "--vmname", "new_box_macos_fim_test_1582644530271_78262_1695944892230_28501", "--vsys", "0", "--unit", "12", "--disk", "/Users/jenkins/VirtualBox VMs/new_box_macos_fim_test_1582644530271_78262_1695944892230_28501/box-disk001.vmdk"]
20:53:32  
20:53:32  Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
20:53:32  Interpreting /var/root/.vagrant.d/boxes/development-VAGRANTSLASH-macos-catalina/0/virtualbox/box.ovf...
20:53:32  OK.
20:53:32  0%...10%...
20:53:32  Progress state: NS_ERROR_INVALID_ARG
20:53:32  VBoxManage: error: Appliance import failed
20:53:32  VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
20:53:32  VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg *)" at line 1119 of file VBoxManageAppliance.cpp
20:53:32  
```

Related to  https://github.com/wazuh/wazuh-jenkins/issues/5539

Checking this out with @wazuh/cicd

**Comment by jnasselle** [comment]
# Update

macOS-related errors due to infrastructure will be blocked until https://github.com/wazuh/internal-devel-requests/issues/303 is closed of its intel resources released

**Comment by jnasselle** [comment]
# Update

## API tests

Replay : https://ci.wazuh.info/job/Test_integration/43433/

**Comment by Deblintrake09** [comment]
LGTM! GJ! :rocket:

**Comment by davidjiglesias** [comment]
LGTM!
