### ISSUE TITLE
Incorrect opensearch causes Wazuh dashboard server is not ready yet

### ISSUE THREAD

**Issue by Is3x** [wazuh/wazuh#19337]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-beta1 | wazuh-dashboard | Ansible | Packages/Sources | Oracle Linux9 |

 I could not access the dashboard on a web browser. Even after successfully installing all components

On going through the logs for the dashboard, an error message stood out
"dial up... ERROR dial tcp :127.0.0.1:9200: connect: connection refused"

I was able to fix this by editing the opensearch_dashboard.yml file and changing the address 127.0.0.1:9200 to the address of the endpoint.

```jsx
opensearch.hosts:
  - https://192.168.115.14:9200
```

### Related
- https://github.com/wazuh/wazuh/issues/19154

**Comment by teddytpc1** [comment]
The playbook used to deploy was requested to @Is3x.
