### ISSUE TITLE
Release 4.5.3 - RC 2 - Ruleset

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#19330]
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #19300 |
| **Version** | 4.5.3                               |
| **Release candidate #** | RC 2                                   |
| **Tag** | [v4.5.3-rc2](https://github.com/wazuh/wazuh/tree/v4.5.3-rc2) |
| **Previous ruleset  test** | #19125 |

**Comment by Johnng007** [comment]
|Component |  Tested  |  Total   | Coverage |
| -------- | -------- | -------- | -------- |
|  Rules   |   1375   |   4285   |  32.09%  |
| Decoders |   125    |   170    |  73.53%  |

**Comment by ooniagbi** [comment]
LGTM!
