### ISSUE TITLE
Spike - Determine memory usage of the CVEv5 flatbuffers

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#19342]
|Part of Epic| Branch |
|---|---|
|#14153|[dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor)|

### Description

Given that the generated data from the [intelligence-platform tools](https://github.com/wazuh/intelligence-platform) tends to have a considerable size, it is essential to determine the memory required when operating with their corresponding flatbuffers.

To determine this I will use a big subset (all 2023 CVEs) of the generated data from the above-mentioned tools and convert them to their flatbuffers counterpart.

For more information about flatbuffers:
- #17874

### DoD
- [x] Raise metrics related to our use-case of the flatbuffers

**Comment by sebasfalcone** [comment]
The following chart is a comparison of:
- The size of a JSON file on the disk
- Memory usage of the same file reader as binary data
- Memory usage of the same file converted to Flatbuffer

| JSON file [MB] | JSON binary data [MB] | Flatbuffer [MB] |
|----------------|-----------------------|-----------------|
|            3.3 |                  2.87 |            2.38 |
|            3.3 |                  2.80 |            2.40 |
|            2.0 |                  1.30 |            1.37 |
|            1.5 |                  0.95 |            0.63 |
|            1.1 |                  0.65 |            0.25 |


![image](https://github.com/wazuh/wazuh/assets/34063881/a1962ec5-aecb-46fb-b10f-42493fe836c9)
![image](https://github.com/wazuh/wazuh/assets/34063881/bd5dcb97-79ae-46a1-8c10-acbe0b32eba0)

### DB dump conversion
If we convert the DB dump into flatbuffer, we obtain a 562 MB¹ file. Compressing this file with XZ at its maximum level gives us a 28 MB file.

> **1**: 75108 CVEs (40%) are not compliant with the flatbuffer schema so they are discarded (resulting in a smaller file overall).

**Comment by sebasfalcone** [comment]
## Non-compliant CVEs
From all the CVEs there are many that are not compliant with the flatbuffer schema. There are three reasons:

### unknown field: attackComplexity
Further investigation is needed. It could be an error in the schema implementation.

### unknown field: description
This is a bug in the content_merge tool. [This PR](https://github.com/wazuh/intelligence-platform/pull/1024) supposedly fixed this issue, but the generated content doesn't present these fixes.

### unknown field: rejectedReasons
This is okay, the schema does not support rejected CVEs.

**Comment by Damian-Mangold** [comment]
Thanks for the analysis @sebasfalcone.

@Dwordcito, do you consider that the analysis is finished or is there something else to evaluate?

**Comment by Dwordcito** [comment]
Thanks for the analysis.

LGTM.
