### ISSUE TITLE
Agent installation for server - tar/write.c:37:10: fatal error: attr/xattr.h: No such file or directory

### ISSUE THREAD

**Issue by D3vil0p3r** [wazuh/wazuh#19347]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | Wazuh Agent for Server | Agent | Sources | Arch Linux rolling |

I'm using Arch Linux and I'm installing the Wazuh agent in hybrid mode by following the [official docs](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html) and referring to **pacman** tab. I run the **./install** and I'm able to run the Wazuh manager systemd service correctly by this installation script.

When it asks me to build for the agent for the server, during the compiling I get:
```makefile
gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/usr/local/ssl\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -DNDEBUG  -MMD -MF crypto/mem.d.tmp -MT crypto/mem.o -c -o crypto/mem.o crypto/mem.c
  CC       tar/bsdtar-write.o
tar/write.c:37:10: fatal error: attr/xattr.h: No such file or directory
   37 | #include <attr/xattr.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:7811: tar/bsdtar-write.o] Error 1
make[2]: Leaving directory '/home/athena/wazuh-4.5.2/src/external/libarchive'
make[1]: *** [Makefile:3819: all] Error 2
make[1]: Leaving directory '/home/athena/wazuh-4.5.2/src/external/libarchive'
make: *** [Makefile:1077: external/libarchive/.libs/libarchive.a] Error 2
make: *** Waiting for unfinished jobs....
```
and at the end:
```makefile
 Error 0x5.
 Building error. Unable to finish the installation.
```
In Arch Linux, I'm not sure that **<attr/xattr.h>** exists... The header file that exists is **<sys/xattr.h>**. Could you give a look to it?

**Comment by pereyra-m** [comment]
Hello @D3vil0p3r !

It seems that the compilation fails during the compilation of the external dependency `libarchive`.
I'd try first to download the pre-compiled external dependencies to avoid this problem:

```bash
make -C src clean
make -C src clean-deps
rm -rf src/external/*
make deps -C src TARGET=agent 
make build -C src TARGET=agent
./install.sh
```

You can replace `TARGET=agent` by `TARGET=server` for the Wazuh manager.

Regards.

**Comment by pereyra-m** [comment]
Hi again @D3vil0p3r !

Please, share the results of the suggested steps.
Is it working now?

Regards.

**Comment by Dwordcito** [comment]
We closed due to inactivity, we understand that this is for a reason beyond Wazuh's control and that it will be resolved when the package vendor corrects.

Thank you very much for being part of the community.

**Comment by D3vil0p3r** [comment]
Hey. Sorry for late answer @pereyra-m . It works now. Thank you very much!

**Comment by pereyra-m** [comment]
Great news, thank you for the update @D3vil0p3r !
