### ISSUE TITLE
Fix logs name format for API and Cluster

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#19377]
|Wazuh version|Component|
|---|---|
| 4.4.0 | API/Cluster |

## Description

The cloud team reported an error in the API and cluster log files path.  
![image](https://github.com/wazuh/wazuh/assets/23361101/f6d5acb0-09b7-4e2a-a452-291e14d1d433)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by javiersanchz** [comment]
# Update

Researching the output format change for log rotation introduced in https://github.com/wazuh/wazuh/pull/13197.

![image](https://github.com/wazuh/wazuh/assets/96108386/ead1973e-14f6-46bd-ad3f-cb52599f8b68)

This change was made by introducing the `SizeBasedFileRotatingHandler` rotation method, ensuring both methods shared the same output format

![image](https://github.com/wazuh/wazuh/assets/96108386/7d45e27f-510f-49fa-98ae-505c9c893d61)

In this issue https://github.com/wazuh/wazuh/issues/12615#issuecomment-1143210872, it's also mentioned that a new configuration option was added. This option allows switching from `Time`  rotation to `Size` rotation when the former is disabled

## Conclusion

For now, the decision has been made to keep the current format, ensuring that both rotation systems have the same format and that the mentioned configuration functions as expected.

**Comment by Selutario** [comment]
Some versions have already been released including this change, which also seems to be intentional. Therefore, the least bad option is to keep it that way.
