### ISSUE TITLE
`wazuh-analysisd` RSS memory increase without stabilization

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19381]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc2| wazuh-analysisd | Manager | Packages | Jenkins Stress Test Vagrant macOS + Solaris Agent |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/19373, an increase without stabilization of RSS memory has been found in the stage when the stress ends through scripts (lowers the stress level of the components)

![image](https://github.com/wazuh/wazuh/assets/14913942/12a234c1-00c8-4d09-b55a-1cd267c8360f)

This increase is not seen in the graphs that we have from previous versions.

- [4.5.1](https://github.com/wazuh/wazuh/issues/18534)

![image](https://github.com/wazuh/wazuh/assets/14913942/284906eb-98a7-4a46-8375-ca4fc41da775)

- [4.5.0](https://github.com/wazuh/wazuh/issues/18106)

![image](https://github.com/wazuh/wazuh/assets/14913942/b614174c-cfb1-4a41-bb35-9dc7403ee91b)

It is necessary to determine the cause of this rise and rule out a malfunction or leak.

## Additional

In the Rootcheck test, this increase has been found, which is observed in previous tests, although in version 4.5.0 the increase does not stabilize

- https://github.com/wazuh/wazuh/issues/19355

![image](https://github.com/wazuh/wazuh/assets/14913942/5b2be8fc-96a7-4d5b-8596-fec47fb7f413)

- https://github.com/wazuh/wazuh/issues/18094

![image](https://github.com/wazuh/wazuh/assets/14913942/d62749cc-d2ab-4e58-aaee-c58b41dec16a)

**Comment by Dwordcito** [comment]
@JcabreraC please Analyze, RCA, and ETA if needed.

**Comment by juliancnn** [comment]
## Investigation Overview:

Upon a thorough examination, this issue seems reminiscent of past observations. Specifically, a similar behavior was noted during a 2.5-day test in release 4.4.0, as documented in [#16454](https://github.com/wazuh/wazuh/issues/16454). This test involved both a macOS agent and a Solaris agent, and the observed behavior was consistent with the current issue:

![image](https://github.com/wazuh/wazuh/assets/1891958/fa13373d-f772-4e05-ac0f-6a584a003899)

## Memory Analysis of Wazuh-Manager:

- The memory scaling is evident during the phases of resource allocation and release, but remains stable during the full load phase.
- This scaling exhibits a periodic pattern, approximately every 2 hours and 20 minutes. This periodicity might explain why it's not observed in the 6-hour tests, given that 1 hour is dedicated to resource allocation and another hour for resource release.
- Each memory increment is consistent, with a size of 264 bytes.
- During the stress test, memory utilization remains within a fixed range.
- Notably, within the aforementioned 2-hour 20-minute period, there's a noticeable jump in memory during the last 15 minutes.

![image](https://github.com/wazuh/wazuh/assets/1891958/a9e79f36-08a7-4cb3-bbe5-8251ffa893ac)
![image](https://github.com/wazuh/wazuh/assets/1891958/3e218f92-1d44-451a-ac5f-79635cd27d41)

## Analysis of Agent-Sent Events:

With only two agents connected (Solaris and macOS), there are some notable differences in their behavior:

- The macOS agent appears to adhere to the expected load times, transmitting events solely during the full load phase:
![image](https://github.com/wazuh/wazuh/assets/1891958/dfbc848f-3e53-4657-a221-df33efb82a62)
- Contrarily, the Solaris agent doesn't exhibit this disciplined behavior. It consistently sends a similar volume of events before, during, and after the load phase:
![image](https://github.com/wazuh/wazuh/assets/1891958/751fa099-3916-4c6b-acd0-7b58b8217bce)

It's plausible that during the full load phase, the events received from the macOS agent help in clearing the unreleased memory from the Solaris agent's messages. To further investigate this hypothesis, a test focusing solely on the Solaris agent's events will be conducted.

**Comment by JorgeMarinoDev** [comment]
Adding some further analysis on this. 

My main concern was trying to relate the memory ramp to the queues. Even though not final, I don't think it's related to the queues. Mainly because the PR modifying the queue initialization place.

In the next image I overlapped the RSS memory with the queues states. There is no direct relationship at first sight.
Vertical lines in different colors are the different queues usage.
Even more, there is no single color related to the ramp, so we may conclude that it's an analysisd internal if it happens again.

![image](https://github.com/wazuh/wazuh/assets/117848458/f97897bc-6d72-4101-86e7-ed330e6b2ee8)

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.5.3                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.5.3-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/179/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/Test_stress_Vagrant_B179_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/plots/Test_stress_Vagrant_B179_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B179_manager_2023-10-05.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/logs/ossec_Test_stress_Vagrant_B179_manager_2023-10-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B179_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/data/monitor-manager-Test_stress_Vagrant_B179_manager-pre-release.csv)
[Test_stress_Vagrant_B179_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/data/Test_stress_Vagrant_B179_manager_analysisd_events.csv)
[Test_stress_Vagrant_B179_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/data/Test_stress_Vagrant_B179_manager_analysisd_state.csv)
[Test_stress_Vagrant_B179_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_manager_centos/data/Test_stress_Vagrant_B179_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/Test_stress_Vagrant_B179_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/Test_stress_Vagrant_B179_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/Test_stress_Vagrant_B179_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/plots/Test_stress_Vagrant_B179_solaris_agent_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B179_solaris_2023-10-05.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/logs/ossec_Test_stress_Vagrant_B179_solaris_agent_2023-10-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B179_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B179_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.5.3/B179-480m/B179_agent_solaris/data/Test_stress_Vagrant_B179_solaris_agent_agentd_state.csv)



    </details>

</details>

**Comment by JorgeMarinoDev** [comment]
Hello, I am providing an update on the status of this issue: [link](https://github.com/wazuh/wazuh/issues/19381).

This is a summary, compiling everything that has been worked on so far. I apologize for the length; I wanted to be as detailed as possible within my capabilities.

1. I spoke with @jnasselle . He briefed me on what they discussed with @juliancnn.
    1. We are now aware of an issue in Jenkins with the Stress agent on Solaris that sends events continuously, not respecting the test stages.
    1. Julián suspects a circular buffer in analysisd due to the periodicity of the ramp.
        1. This is because they couldn't find any periodic external request that matches the ramp times. So, Julián adds that it may be that events or something causing a realloc occur during that period, which coincides more with time, with a byte size of a buffer. They mention a factor of 9x (something like 264 bytes x 9, 2376 bytes).
    1. Nico confirms that the stress tests are launched in 2 batches. One for Linux agents and another for macOS and Solaris.
        1. macOS and Solaris agents in that playbook are virtualized on macOS Intel via Vagrant on a physical Mac Mini of Wazuh.
2. I spoke with @sdvendramini  regarding the incorporation of stats and metrics into analysisd. He was working with @TomasTurina . It's a significant task.
    1. Link to epic: [here](https://github.com/wazuh/wazuh/issues/13099)
    1. They decided to combine the Core and Framework work into a single PR, this one: [here](https://github.com/wazuh/wazuh/pull/13713).
        1. They did this because one was Core development, and the other was API support and Python fwk.
    1. It's unclear whether anything related to these new metrics was added to the Jenkins Stress Test playbooks. This is to investigate if the stress test makes periodic requests for metrics. There is no evidence yet.
3. The elements of my research work hypothesis are as follows:
    1. Stress tests were executed only with Solaris [here](https://github.com/wazuh/wazuh/issues/19381#issuecomment-1749600406) at Julián's request.
        i. The same ramp is observed.
    2. The Solaris agent sends events during all Stress stages. But when analysisd processes Solaris together with MacOS, the ramp is not evident.
        1. Something causes analysisd not to show the ramp when both agents (macOS and Solaris) are present during the Stress stage.
        2. It doesn't happen in Allocation and Release.
    3. The increments are fixed: 264 bytes.
        1. This leads me to analyze at a lower level than the queues (the origin of a specific queue has already been ruled out [HERE](https://github.com/wazuh/wazuh/issues/19381#issuecomment-1749523401)).
        2. In addition to the fact that macOS and Solaris are virtualized, communication is via a virtual bridge.
        3. It could be some residue in the de-marshall in the socket transfer layer to the queues.
4. I continue to investigate the code and changesets with a focus on special treatment in Solaris but in the layer of queue ingestion from the FDs.

**Comment by JorgeMarinoDev** [comment]
Just for the record. Created a new issue in JK repo. https://github.com/wazuh/wazuh-jenkins/issues/5782
Clearly seen, Solaris Agent is sending events during unexpected stages of the stress test.

**Comment by davidjiglesias** [comment]
This increase has not been seen from 4.6.0 to 4.7.0 footprint tests
