### ISSUE TITLE
Create OpenSUSE Leap 15.5 SCA policies

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#19398]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | SCA | Both| Packages/Sources | OpenSUSE Leap 15.5 |

This issue is created as a consequence of testings performed in [issue #17676](https://github.com/wazuh/wazuh/issues/17676).

During these tests, it was confirmed that SCA works with default policies, but no custom policies exists for openSUSE Leap 15.5 or any other previous versions.

**Comment by ooniagbi** [comment]
OpenSUSE Leap 15.5 does not have a CIS benchmark at the moment. We will continue to monitor this but for now, we are closing this issue.

**Comment by ncvicchi** [comment]
@ooniagbi this kind of issues will keep on showing every 2 weeks for NEW OSs as part of the OS release periodic check. Should we not create these kind of issues?

**Comment by ooniagbi** [comment]
Hi, you can create the issue if it covers a new OS that you haven't opened an issue for beforehand. The Threat Intel team will review it and if there is a CIS benchmark, then we will add it to the roadmap. If there is no CIS benchmark, then we have no option but to close it. You can confirm that an OS has a CIS benchmark from https://downloads.cisecurity.org/#/ (maybe this helps your process).
