### ISSUE TITLE
Agents forcibly disconnect from the manager in stress tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#19401]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc2 | Agentd | Agent | Packages | Windows Server 2019 |

### Description

During the [footprint test](https://github.com/wazuh/wazuh/issues/19363) the Windows agent was forcibly disconnected:
```
2023/09/29 03:16:46 sca: INFO: Security Configuration Assessment scan finished. Duration: 11 seconds.
2023/09/29 03:16:47 wazuh-agent: ERROR: Connection socket: An existing connection was forcibly closed by the remote host. (10054)
2023/09/29 03:16:47 wazuh-agent: ERROR: (1137): Lost connection with manager. Setting lock.
2023/09/29 03:16:47 wazuh-agent: INFO: Closing connection to server ([172.31.14.73]:1514/tcp).
2023/09/29 03:16:47 wazuh-agent: INFO: Trying to connect to server ([172.31.14.73]:1514/tcp).
2023/09/29 03:16:51 wazuh-agent: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/09/29 03:24:13 wazuh-agent: INFO: Using notify time: 10 and max time to reconnect: 60
```

It seems that the connection was reset by the manager abruptly. No relevant logs were found in the manager side.

Could be related to https://github.com/wazuh/wazuh/issues/9171

### Evidences

- [**Manager Logs**](https://github.com/wazuh/wazuh/files/12801356/ossec_Test_stress_B4377_manager_2023-10-01.2.zip)

- [**Windows Logs**](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4377-3600m/B4377_agent_windows/logs/ossec_Test_stress_B4377_windows_2023-10-01.zip)

**Comment by jotacarma90** [comment]
After an investigation, we have not been able to find out anything. There is no clue to follow, so we are asking to repeat the stress test (long enough to see if it reproduces), and if possible with the logs in debug mode to look for more clues.

**Comment by Rebits** [comment]
Relaunched stress tests with `windows.debug` option set to 2. We have chosen a duration of 4 hours for this test, as the reported issue appeared after 3 hours and 30 minutes.

**Build**: https://ci.wazuh.info/job/Test_stress/4400/
