### ISSUE TITLE
FIM whodata not working on Alpine Linux 3.18.4

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#19412]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | FIM | Agent | Packages| Alpine Linux 3.18.4 |

This issue is closed by [6871](https://github.com/wazuh/wazuh-documentation/pull/6871)

From [#17680](https://github.com/wazuh/wazuh/issues/17680) issue tests, it was determined that FIM with whodata is not working even after installing auditd.

Analysis should be performed in order to determine the cause and fix it if it is possible.

**Comment by ncvicchi** [comment]
Blocked by #19585

**Comment by ncvicchi** [comment]
ETA was not accomplished. Gave 3 more days to solve it

**Comment by ncvicchi** [comment]
Analysis is not satisfactory, no PR is provided with a solution or conclusive proof of no possibility for Whodata to work on Alpine or excessive work needed to accomplish such functionality.

Conclusions are not correct, for example, is clear why the audisp-af_unix is not found (paths are different).

**Comment by ncvicchi** [comment]
Move to In Progress again

**Comment by ed108206** [comment]
An issue was created to update documentation
https://github.com/wazuh/wazuh-documentation/issues/6833)

**Comment by ncvicchi** [comment]
LGTM!

**Comment by lchico** [comment]
LGTM!

**Comment by ncvicchi** [comment]
Although analysis is done, documentation has not yet been updated. Reopening until issue is solved.

**Comment by ncvicchi** [comment]
Moved ETA since issue was reopened

**Comment by jotacarma90** [comment]
Blocked by:
https://github.com/wazuh/wazuh-documentation/pull/6859

**Comment by ncvicchi** [comment]
It was finally determined that the problem was the same as in [this issue](https://github.com/wazuh/wazuh/issues/19585), along with a the audisp af_unix plugin not being installed in the expected directory. 

The documentation will be updated in order to reflect both situation when installing the Auditd daemon and allow whodata to work on Alpine Linux systems.

**Comment by ncvicchi** [comment]
This issue is closed by [6871](https://github.com/wazuh/wazuh-documentation/pull/6871)

**Comment by ncvicchi** [comment]
Merged!
