### ISSUE TITLE
No SCA policies are available for Alpine Linux 3.18.4

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#19414]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | SCA | Agent | Packages| Alpine Linux 3.18.4 |

From https://github.com/wazuh/wazuh/issues/17680 issue tests, it was determined that no SCA policies are available for Alpine Linux 3.18.4.

SCA policies should be created to fully support this OS

**Comment by ooniagbi** [comment]
Alpine Linux 3.18.4 does not have a CIS benchmark at the moment. We will continue to monitor this but for now, we are closing this issue.
