### ISSUE TITLE
Syscollector is not working on Alpine Linux 3.18.4

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#19415]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2 | Syscollector | Agent | Packages| Alpine Linux 3.18.4 |

From https://github.com/wazuh/wazuh/issues/17680 issue tests, it was determined that Syscollector is not working properly, since no inventory is received.

Analysis should be performed in order to determine the cause and fix it if it is possible.

**Comment by vikman90** [comment]
Setting the objective to _High-impact bugs_ as a key functionality is not working properly.

**Comment by jnasselle** [comment]
@ncvicchi Based on what [this comment](https://github.com/wazuh/wazuh/issues/17680#issuecomment-1747673636) shows:

- Syscollector inventory is not only packages. It also includes processes, network, osinfo, hwinfo and ports. 
- Syscollector package support for Alpine was merged in 4.7.0 https://github.com/wazuh/wazuh/issues/15699

**Comment by ncvicchi** [comment]
Thanks @jnasselle !

Since packages were not present but other inventories did, I wrote in the description as "not working properly" instead of not working at all.

We had no information or list of supported OSs for syscollector, and we have a "go/no go" policy for the tests.

Actually, on the [Alpine Linux following version were Wazuh's 4.7.0 was used](https://github.com/wazuh/wazuh/issues/20626), Syscollector worked properly.

I'm closing this issue.
