### ISSUE TITLE
False positive in the rootcheck in /usr/sbin/sendmai

### ISSUE THREAD

**Issue by AT-SGAI-CSIC** [wazuh/wazuh#19418]
|Wazuh version|Component|Install type|Install method|Platform|
|4.4.3-1|wazuh-agent|dnf install| dnf install|**AlmaLinux 8.8**|

Hi, we have detected what appears to be a false positive in the rootcheck in /usr/sbin/sendmail in AlmaLinux 8 system:

![imagen](https://github.com/wazuh/wazuh/assets/139878963/a0153f64-dcdf-495b-9b3b-7ad74bf4b1ad)

We see that` /usr/sbin/sendmail `it's a symbolic link to` /etc/alternatives/mta` which in turn is a symbolic link to bash shell script to /usr/bin/esmtp-wrapper

![imagen](https://github.com/wazuh/wazuh/assets/139878963/a6da3d0a-3ec5-429c-9425-097271ff340b)

**Comment by phxyz12** [comment]
Hi,

I am having the same issue on Rocky Linux systems. This issue is marked as "completed" - how did you actually solve the problem?

Thanks and cheers,

Pascal
