### ISSUE TITLE
Test: Active response

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1945]
# Testing: Active response

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## Active response

- [x] Insert 2 times same config
- [x] Test active-response from wrong SO
- [x] Test active-response from correct SO
- [x] Check that the execution of the active response respects the location
- [x] Specifies more than one agent_id
- [x] Check level filter
- [x] Check rules_group filter
- [x] Check rules_id filter
- [x] Check the period of the reverse command (timeout option)
- [x] Check incremental timeouts (repeated_offenders)

## Command

- [x] Insert 2 times same config
- [x] Configure a command that does not exist
- [x] Same command for multiple active-response
- [x] Check that the extra_args option works for any field
- [x] Check that the expect option works for any field
- [x] Verify that the return command can be enabled and disabled (timeout_allowed)
- [x] Set the command below the active response that uses it
- [x] Test firewall-drop command

## agent_control

- [x] Send an active-response to an agent using agent_control

## Custom A-R

- [x] Test custom active-response explained at https://github.com/wazuh/wazuh/issues/1116

**Comment by Skeptor** [comment]
Insert 2 times the same config:
· Active-Response: The command is executed twice in a row.
· Command: The first command in the `ossec.conf` is the one used.
There is no logs in any situtation
