### ISSUE TITLE
Wazuh Agent's application title is confusing

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19464]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.2-40505 | Wazuh Agent | Agent | Packages | Windows Server 22 (and others too) |

## Description

The title of the application in Windows is confusing. It seems that it refers to the management of Wazuh Agent, but as we have a software called "Wazuh Manager" the title is confusing.

## Evidence

![image](https://github.com/wazuh/wazuh/assets/39094716/f7bb56e2-c22e-4fec-aebd-766a02d80f46)

## Expected

- The title should be "Wazuh Agent" or "Wazuh Agent Management"

**Comment by GabrielEValenzuela** [comment]
@sebasfalcone 

We need also to update the image in the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-windows.html)

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela Please generate the corresponding PR on the documentation repository

**Comment by sebasfalcone** [comment]
Documentation was fixed at:
- https://github.com/wazuh/wazuh-documentation/issues/7240
