### ISSUE TITLE
Memory increase of `wazuh-modulesd` in macOS agent

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#19513]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.5.3-rc3 | Modulesd | Agent | Packages| macOS |

## Description

During the footprint test performed on #19509, an increase in the memory of `wazuh-modulesd` in the macOS agent could be observed, compared to previous versions.

- **4.5.3-rc3**:

![image](https://github.com/wazuh/wazuh/assets/80041853/1ac30805-f450-471e-83be-9ec1bb5529ae)

![image](https://github.com/wazuh/wazuh/assets/80041853/3b91878e-50e2-4d0e-aec2-a7724de98f14)

![image](https://github.com/wazuh/wazuh/assets/80041853/bfab34ae-8d38-4931-bd58-3d40e02ebe78)

- **4.5.3-rc2**:

![image](https://github.com/wazuh/wazuh/assets/80041853/957be9cf-eee3-4473-b273-7cda951cbf58)

![image](https://github.com/wazuh/wazuh/assets/80041853/4bdd3a9e-f641-484e-aca5-a192f52cc206)

![image](https://github.com/wazuh/wazuh/assets/80041853/5d2551a7-d78d-42a0-b652-065b3b6067e6)

**Comment by ncvicchi** [comment]
After thoroughly comparing differences between [RC2 and RC3](https://github.com/wazuh/wazuh/compare/v4.5.3-rc2...v4.5.3-rc3) we have not found any change that would justify such behavior. All changes apply to Windows platform, none that we could find should affect macOS. 

Nevertheless, we have required a [macOS 10.15 machine](https://github.com/wazuh/internal-devel-requests/issues/353) to perform local tests to analyze this issue further.

**Comment by ncvicchi** [comment]
@juliamagan can the RC3 test be repeated?

**Comment by mauromalara** [comment]
In `4.6.0-rc2` ([issue link](https://github.com/wazuh/wazuh/issues/19935)) this is not observed:

`RSS_MAXMIN`:

<img src="https://camo.githubusercontent.com/34a2bf043eab3fa4e971bfc1c9acd08180cdfe4f7a938d8b0c9b7397f845bd06/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138362d333630306d2f423138365f6167656e745f6d61636f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f56616772616e745f423138365f6d61636f735f6167656e742d7072652d72656c656173655f5253535f4d41584d494e2e706e67" />

**Comment by jotacarma90** [comment]
We can close this issue, no more reproduced
