### ISSUE TITLE
wazuh-authd: ERROR: Invalid request for new agent

### ISSUE THREAD

**Issue by HelterSkelter5** [wazuh/wazuh#19517]
So this is happening - any idea what causes it?

The same issue is reported on both the manager and the client without any further explanation.  No other errors in the logs leading up to this which would indicate an issue in the agent registration process.

Device isn't a duplicate and the name doesn't already exist.

TIA

**Comment by MiguelazoDS** [comment]
Hi @HelterSkelter5, 

- Please set `authd.debug=2` in your `/var/ossec/etc/internal_options.conf` and restart your manager. 
- Reproduce the error and share the logs that match with `OSSEC PASS:`  or `OSSEC A:`

My guess is that you have configured authd pass and you are not setting a password so when the manager tries to parse the information it is not receiving the expected message from the agent.

**Comment by Dwordcito** [comment]
It closed due to inactivity.

Thanks for being part of the community, please reopen the issue if you decide to continue with this question.

Your help makes the product better! thank you!

**Comment by jeremybusk** [comment]
Make sure you have enable password authentication on manager too from "no" to "yes".

nano /var/ossec/etc/ossec.conf
```
<auth>
  <use_password>yes</use_password>
</auth>
```
restart service
```
systemctl restart wazuh-manager
```

Clearly explained in these wonderful docs
https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/using-password-authentication.html

This is an excellent project. Thank you!

**Comment by daryltamo** [comment]
I have the same issue. Here is a sample log segment from /var/ossec/logs/ossec.log
main-server.c:708 at run_dispatcher(): INFO: New connection from <IP>
2024/07/11 15:51:24 wazuh-authd[3302] main-server.c:751 at run_dispatcher(): DEBUG: Request received: <OSSEC PASS: <PASSWORD> OSSEC A:'<AGENT_NAME>' V:'v4.7.3' K:'7021138a48c5e0f64bdeeccb427468915666xxxx'
2024/07/11 15:51:24 wazuh-authd[3302] auth.c:119 at w_auth_parse_data(): ERROR: Invalid request for new agent from: <IP>

Can someone help me identify how to proceed with this? I have read the code of auth.c from your repo but I can't quite figure it out.
