### ISSUE TITLE
Test: Cluster

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1952]
# Cluster test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## Installation

- [x] Installation by default: Run `/var/ossec/bin/wazuh-clusterd -f`
- [x] Installation by default: Run `python3 /var/ossec/bin/wazuh-clusterd -f`
- [x] Installation by default - centos6: Run `/var/ossec/bin/wazuh-clusterd -f`

## Configuration

- [x] Python 2:
    - [x] Configure cluster: No key.
    - [x] Configure cluster: Wrong key.
    - [x] Configure cluster: Wrong node type.
    - [x] Configure cluster: Wrong master node IP.
- [x] Python 3:
    - [x] Configure cluster: No key.
    - [x] Configure cluster: Wrong key.
    - [x] Configure cluster: Wrong node type.
    - [x] Configure cluster: Wrong master node IP.

## Cluster

- [ ] Python 2:
    - [x] Start the master before/after the clients.
    - [x] Change path to opt in master and var in clients.
    - [x] Synchronization process when one of the clients is down.
    - [x] Stop master and start it after some time.
    - [x] Disconnect worker node internet connection and check it disconnects after 2 minutes. Check the master node removes that node. Connect the node to the internet again and check it reconnects to the master node without restarting (https://github.com/wazuh/wazuh/pull/1482).
    - [x] Disconnect worker and reconnect it again to the internet in less than 2 minutes. Check it keeps working as usual (https://github.com/wazuh/wazuh/pull/1482).
    - [ ] File level tests: Run automatic tests and review KO files.
- [ ] Python 3:
    - [x] Start the master before/after the clients.
    - [ ] Change path to opt in master and var in clients.
    - [x] Synchronization process when one of the clients is down.
    - [x] Stop master and start it after some time.
    - [x] Disconnect worker node internet connection and check it disconnects after 2 minutes. Check the master node removes that node. Connect the node to the internet again and check it reconnects to the master node without restarting (https://github.com/wazuh/wazuh/pull/1482).
    - [x] Disconnect worker and reconnect it again to the internet in less than 2 minutes. Check it keeps working as usual (https://github.com/wazuh/wazuh/pull/1482).
    - [ ] File level tests: Run automatic tests and review KO files.

## Cluster control
- [x] Master
    - [x] Python 2:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
    - [x] Python 3:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
- [x] Worker
    - [x] Python 2:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
    - [x] Python 3:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`

## Agents

- [x] Python 2:
    - [x] Register an agent in master and point it to a client.
    The *client.keys* must be propagated and the agent must be reporting. Then, if the agents are listed in the master, it must be Active.
    - [x] `cluster-control -a` must show the agents information and the manager.
    - [x] Connect the previous agent to a different client and review logs/alerts. It must be transparent for the user.
    - [x] Remove an agent in master. It must be removed in all the clients.
- [x] Python 3:
    - [x] Register an agent in master and point it to a client.
    The *client.keys* must be propagated and the agent must be reporting. Then, if the agents are listed in the master, it must be Active.
    - [x] `cluster-control -a` must show the agents information and the manager.
    - [x] Connect the previous agent to a different client and review logs/alerts. It must be transparent for the user.
    - [x] Remove an agent in master. It must be removed in all the clients.

## Groups

- [ ] Python 2:
    - [x] Create a new group.
    - [x] Create a file in a group.
    - [x] Modify a file in a group.
    - [x] Remove a file in a group.
    - [x] Remove group.
    - [x] Re-create a removed group.
    - [x] Assign agent to a group.
    - [x] Unassign agent group.
    - [ ] Assign a group in a client using md5. Then, check if it is propagated to the master.
- [ ] Python 3:
    - [x] Create a new group.
    - [x] Create a file in a group.
    - [x] Modify a file in a group.
    - [x] Remove a file in a group.
    - [ ] Remove group.
    - [ ] Re-create a removed group.
    - [x] Assign agent to a group.
    - [x] Unassign agent group.
    - [ ] Assign a group in a client using md5. Then, check if it is propagated to the master.

## Ruleset

- [x] Python 2:
    - [x] Modify a file in the rules/decoders/lists directory.
    - [x] Add a file in the rules/decoders/lists directory.
    - [x] Remove a file in the rules/decoders/lists directory.
- [x] Python 3:
    - [x] Modify a file in the rules/decoders/lists directory.
    - [x] Add a file in the rules/decoders/lists directory.
    - [x] Remove a file in the rules/decoders/lists directory.

## Performance

- [ ] Python 2:
    - [ ] 1 master, 10 clients, 100k agent-info and agent-groups.
- [ ] Python 3:
    - [ ] 1 master, 10 clients, 100k agent-info and agent-groups.

**Comment by manuasir** [comment]
The cluster service won't start. Related issue: https://github.com/wazuh/wazuh-api/issues/244

**Comment by DaveVG1** [comment]
Related issue #2028
