### ISSUE TITLE
Release 4.6.0 - RC 1 Ruleset

### ISSUE THREAD

**Issue by jk-olaoluwa** [wazuh/wazuh#19520]
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | #19471|
| **Version** | 4.6.0                               |
| **Release candidate #** | RC 1                                   |
| **Tag** | [v4.6.0-rc1](https://github.com/wazuh/wazuh/releases/tag/v4.6.0-rc1) |
| **Previous ruleset  test** | #19214|

**Comment by ooniagbi** [comment]
LGTM!

**Comment by damarisg** [comment]
LGTM!
