### ISSUE TITLE
Release 4.6.0- RC 1 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#19523]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |                 https://github.com/wazuh/wazuh/issues/19471                           |
| **Version**                                   |                     4.6.0                       |
| **Release candidate #**                       |                    RC 1                        |
| **Tag**                                       |                         [v4.6.0-rc1](https://github.com/wazuh/wazuh/tree/v4.6.0-rc1 )                  |
| **Previous Workload benchmarks metrics issue**|               https://github.com/wazuh/wazuh/issues/18874                             |

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|   50000                |         25           |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/19523#issuecomment-1753412272).

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Related issues
- https://github.com/wazuh/wazuh/issues/15802

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario 
- [ ] @davidjiglesias

**Comment by RamosFe** [comment]
## API performance results

---
|                                  |                                            |                                           |            
|--|--|--|
| **Endpoint test name**  | **Status** | **Issues Ref.** |
| GET /cluster/local/info | :green_circle: | |
| GET /cluster/nodes| :green_circle:  | |
| GET /cluster/healthcheck | :green_circle: | |
| GET /cluster/status | :green_circle: | |
| GET /cluster/local/config | :green_circle: | |
| GET /cluster/api/config | :green_circle: | |
| GET /cluster/configuration/validation | :green_circle: | |
| GET /manager/status | :green_circle: | |
| GET /manager/info | :green_circle: | |
| GET /manager/configuration | :green_circle: | |
| GET /manager/logs | 🟢 : | |
| GET /manager/api/config | :green_circle: | |
| GET /manager/configuration/validation | :green_circle: | |
| GET /mitre/groups | :green_circle: | |
| GET /mitre/metadata | :green_circle: | |
| GET /mitre/mitigations | :green_circle: | |
| GET /mitre/references | :green_circle: | |
| GET /mitre/software | :green_circle: | |
| GET /mitre/tactics | :green_circle: | |
| GET /mitre/techniques | :green_circle: | |
| GET /overview/agents | :green_circle:  | |
| GET /tasks/status | :green_circle: | |
| PUT /active-response | :yellow_circle: | https://github.com/wazuh/wazuh-qa/issues/1266 |
| PUT /rootcheck | :green_circle: | |
| PUT /syscheck | :green_circle: | |
| POST /groups | :green_circle: | |
| POST /security/users | :green_circle: | |
| POST /security/roles | :green_circle: | |
| POST /security/policies | :green_circle: | |
| POST /security/rules | :green_circle: | |
| PUT /agents/group | :yellow_circle: | Endpoint is not being tested (https://github.com/wazuh/wazuh-qa/issues/3665). This related issue was opened in the past: https://github.com/wazuh/wazuh/issues/13872 |
| PUT /agents/group/new_test_group/restart | :green_circle: | |
| PUT /agents/restart | :green_circle: |  |
| POST /agents | :green_circle: | |
| POST /agents/insert​|  :green_circle: | |
| POST /agents/insert​/quick | :green_circle: | |
| GET /agents | :green_circle: | |
| GET /agents/no_group | :green_circle: | |
| GET /agents/outdated | :green_circle: | |
| GET /decoders | :green_circle: | |
| GET /groups | :green_circle: | |
| GET /lists | :green_circle: | |
| GET /rules | :green_circle: | |
| GET /security/users | :green_circle: | |
| GET /security/roles | :green_circle: | |
| GET /security/policies | :green_circle: | |
| GET /security/rules | :green_circle: | |
| DELETE /groups | :green_circle: | |
| DELETE /agents | :green_circle: | |
| DELETE /security/users | :green_circle: | |
| DELETE /security/roles | :green_circle: | |
| DELETE /security/policies | :green_circle: | |
| DELETE /security/rules | :green_circle: | |
| PUT /manager/restart | :green_circle: | |
| PUT /cluster/restart | :green_circle: | |

**Comment by RamosFe** [comment]
# Cluster

No errors were found in the `cluster.log` file in the master, but some were found in the workers:
```
Searching for errors in /Users/framos/Desktop/artifacts/master/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_1/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_10/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_11/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_12/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_13/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_14/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_15/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_16/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_17/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_18/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_19/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_2/logs/cluster.log:
2023/10/09 08:13:19 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_2] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_20/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_21/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_22/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_23/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_24/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_25/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_3/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_4/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_5/logs/cluster.log:
2023/10/09 08:13:19 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_5] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_6/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_7/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_8/logs/cluster.log:
-------------------------------------------
Searching for errors in /Users/framos/Desktop/artifacts/worker_9/logs/cluster.log:
-------------------------------------------
``` 

These results were obtained using the following script:
```bash
#!/bin/bash

# Define the base directory where you want to search for logs
base_directory="/Users/framos/Desktop/artifacts"

# Find all folders containing a "logs/cluster.log" file
folders_with_logs=$(find "$base_directory" -type f -name "cluster.log" -exec dirname {} \; | sort -u)

# Loop through each folder and execute the 'cat' and 'grep' commands
for folder in $folders_with_logs; do
    log_file="$folder/cluster.log"
    if [ -f "$log_file" ]; then
        echo "Searching for errors in $log_file:"
        cat "$log_file" | grep "error"
        echo "-------------------------------------------"
    fi
done
```

**Comment by Selutario** [comment]
There are many errors in the log that have gone unnoticed because `grep` did not include the `-i` flag to ignore case. Those errors are all like these:
```
2023/10/09 07:49:56 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
2023/10/09 07:55:50 ERROR: [Worker CLUSTER-Workload_benchmarks_metrics_B307_manager_20] [Main] Error sending sendsync response to local client: Error 3020 - Timeout sending request: ok
```

It was a problem already reported in 4.5.0 but the number of errors in 4.6.0 seems much higher. I have added an update to the following issue analyzing the problem:
- https://github.com/wazuh/wazuh/issues/15802

As a summary, it seems that the problem comes from previous versions but in 4.6.0, due to a change, it is no longer hidden. The operation seems correct in any case, although aesthetically it looks bad.

**Comment by damarisg** [comment]
LGTM!
