### ISSUE TITLE
Previously unnoticed peaks in resource consumption during a stress test.

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19531]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc3 | Wazuh Manager | Manager | Package | CentOS |

In the Footprint test [VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/19494), previously unnoticed fluctuations (peaks) in the manager's RSS, RSS, USS graphs can be observed. These peaks are related to the modulesd process and reach relatively high values.

rc2
![image](https://github.com/wazuh/wazuh/assets/125690423/60516353-2af1-4039-a56c-dad8f7100a68)
rc3
![image](https://github.com/wazuh/wazuh/assets/125690423/59e30fd6-1b95-4b75-a992-edda80de6451)

rc2
![image](https://github.com/wazuh/wazuh/assets/125690423/f1f1934d-66e5-4a6e-a5d4-e4f7d0b95c5d)
rc3
![image](https://github.com/wazuh/wazuh/assets/125690423/9100bbc4-5c89-4ef9-8a3b-130e1fa4cb3d)

rc2
![image](https://github.com/wazuh/wazuh/assets/125690423/8b9d3f8e-863a-4f59-9985-731decd2ef21)
rc3
![image](https://github.com/wazuh/wazuh/assets/125690423/e3d27537-8c41-4244-a723-435fbfa9bc04)

**Comment by MarcelKemp** [comment]
Hi @pro-akim,

As mentioned in this comment:
- https://github.com/wazuh/wazuh/issues/19222#issuecomment-1743444224

The problem is known, because for every update of the SLES/SLED 15 feed (because SUSE has added new vulnerability information, and the feed has to be reparsed and inserted), it is going to increase the memory to the maximum peak (similar to the first one), because it loads in memory the whole feed, instead of parsing and inserting it by chunks.

**Comment by Dwordcito** [comment]
Based on the previous comment and then identifying the operations developed and evidenced in the log, the conclusion is drawn that the only thing that affects the peak is that SLES has been added. While it downloads every one minute, it does not process every 1 minute.

**Comment by mauromalara** [comment]
Those peaks seem to disappear in 4.6.0 (RC 1):

<img src="https://camo.githubusercontent.com/7a786f038ef3e96d36738b61ab32b5fcc68b39487a1e0ce5216d1c1976f07d34/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343435362d333630306d2f42343435365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343435365f6d616e616765722d7072652d72656c656173655f5053532e706e67" />
