### ISSUE TITLE
Several disconnections in Windows Agent

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19568]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc3 | wazuh-agentd | Agent | Packages | Microsoft Windows Server 2019 Datacenter [Ver: 10.0.17763.1999] |

## Description

During https://github.com/wazuh/wazuh/issues/19502 we've detected an increase in the number of disconnections in the Windows Agent.

- There is a difference between the number of disconnections in `4.5.2` and `4.5.3-rc3`.

|`4.5.2`|`4.5.3-rc3`|
|--|--
| <img src="https://camo.githubusercontent.com/1359dc9c005fcdaa9a9363e723a66b890279947bab3c42f97a5940b3b20554a4/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6167656e745f77696e646f77732f706c6f74732f546573745f7374726573735f42343238325f77696e646f77735f6167656e74645f73746174655f4167656e74445f5374617475732e706e67" /> | <img src="https://camo.githubusercontent.com/f30fd397c11dce52d323b009eb60edc229b3b4157a94c339b88fe72b730c1b66/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6167656e745f77696e646f77732f706c6f74732f546573745f7374726573735f42343433365f77696e646f77735f6167656e74645f73746174655f4167656e74445f5374617475732e706e67" />

### Windows Agent

**Logs and configuration**
[ossec_Test_stress_B4436_windows_2023-10-08.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_agent_windows/logs/ossec_Test_stress_B4436_windows_2023-10-08.zip)

**CSVs**
[monitor-winagent-Test_stress_B4436_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_agent_windows/data/monitor-winagent-Test_stress_B4436_windows-pre-release.csv)
[Test_stress_B4436_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_agent_windows/data/Test_stress_B4436_windows_agentd_state.csv)

### Manager

**Logs and configuration**
[ossec_Test_stress_B4436_manager_2023-10-08.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/logs/ossec_Test_stress_B4436_manager_2023-10-08.zip)

**CSVs**
[monitor-manager-Test_stress_B4436_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/monitor-manager-Test_stress_B4436_manager-pre-release.csv)
[Test_stress_B4436_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_events.csv)
[Test_stress_B4436_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_state.csv)
[Test_stress_B4436_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_remoted_state.csv)

**Comment by davidjiglesias** [comment]
ALready seen in 4.5.2. It is also being threated for 4.6.0: https://github.com/wazuh/wazuh/issues/17928#issuecomment-1724801533
https://github.com/wazuh/wazuh/issues/17928
