### ISSUE TITLE
Make SAX Json parser static

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#19561]
## Description

The shared component SAX JSON parser added on https://github.com/wazuh/wazuh/issues/19472 has the function `parse()` that must be declared as `static`. Otherwise, linking errors occur when including the `jsonArrayParser.hpp` from different translation units.

## Expected

The header file  `jsonArrayParser.hpp` can be included from different `.cpp` files without errors.

**Comment by Damian-Mangold** [comment]
What is requested in the issue is already applied.
