### ISSUE TITLE
Check Wazuh compatibility with new version Windows 11 (22H2)

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#19565]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Windows 11 (22H2), release date: 9/20/2022 operating system.

OSs checks https://github.com/wazuh/wazuh/issues/19559

For this, it is necessary to perform the following tests to check that everything works as expected:

- [ ] Agent and server (if possible) installations.
- [ ] O.S. reporting in the interface.
- [ ] WPK upgrade / uninstall. 
- [ ] Enrollment and connectivity with the manager.
- [ ] FIM: Real-time and who-data engines (if available).
- [ ] SCA: Policy support.
- [ ] Vulnerability Detector: Vulnerability support.
- [ ] Syscollector: Complete inventory.
- [ ] Active Response: port blocking.
- [ ] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by ncvicchi** [comment]
Start checks on this OS. Will update this comment once results are available

**Comment by ncvicchi** [comment]
Finally this issue was discarded because it was not a new release, but just a new Microsoft KB, which did not deserved a whole OS check.
