### ISSUE TITLE
Check Wazuh-Agent compatibility with new version Ubuntu 23.10

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#19562]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Ubuntu 23.10 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/19559

Important: This new release includes the new 6.5 Linux kernel that brings [many new features](https://discourse.ubuntu.com/t/mantic-minotaur-release-notes/35534#:~:text=Intel%E2%80%99s%20%E2%80%9CTopology%20Aware,support%20new%20hardware.).

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture .

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/a447d5d9-465c-4ab4-99bd-f08f778120f1" alt="Con_dash">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/10bf9cf8-8987-44f9-b05f-7784a1e0191f" alt="Console">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/0fb100ee-341e-416a-b3c4-861c1ddff0c2">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/a1a7b3b1-390f-4603-86cb-66303b9c80ad">
</details>

## :green_circle: PENDING: FIM Whodata
I had to follow [these steps](https://wazuh.com/blog/monitoring-root-actions-on-linux-using-auditd-and-wazuh/#:~:text=First%20steps%20with%20Linux%20Audit%20system) and add auditctl to the PATH since it wasn't included by default in order to make it work.

<details>
<summary>Configuration on the agent</summary>

  ```
    <directories check_all="yes" whodata="yes">/testwhodata</directories>
  ```
</details>

<details>
<summary>Alerts</summary>

 <img src="https://github.com/wazuh/wazuh/assets/21695385/47a6a246-bed5-4153-9f04-4a2558188385">
</details>

## :green_circle: Upgrade using WPK
WPK was downloaded from [here](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/wpk-list.html) and [this](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html#run-the-upgrade) procedure was follow (from step 2)

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/41576e3e-894f-4fb7-a9a6-93da77c45af2">
</details>


## :yellow_circle: SCA support
No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>

  ```
** Alert 1698330254.1425785: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2023 Oct 26 14:24:14 (6ddeb5033df0) any->sca
Rule: 19007 (level 7) -> 'SCA use case: Keyword check: Ensure password is disabled in the test configuration file'
{"type":"check","id":722175884,"policy":"SCA use case: Keyword check","policy_id":"keyword_check","check":{"id":10000,"title":"Ensure password is disabled in the test configuration file","description":"Password is enabled in the test configuration file.","rationale":"Password is considered weak for the custom test application. Threat actors can brute-force your password.","remediation":"Disable password by setting the value of the password_enabled option to no.","rules":["f:/usr/share/testfile.txt -> r:^password_enabled: yes$"],"condition":"none","file":"/usr/share/testfile.txt","result":"failed"}}
sca.type: check
sca.scan_id: 722175884
sca.policy: SCA use case: Keyword check
sca.check.id: 10000
sca.check.title: Ensure password is disabled in the test configuration file
sca.check.description: Password is enabled in the test configuration file.
sca.check.rationale: Password is considered weak for the custom test application. Threat actors can brute-force your password.
sca.check.remediation: Disable password by setting the value of the password_enabled option to no.
sca.check.file: ["/usr/share/testfile.txt"]
sca.check.result: failed

** Alert 1698330261.1427197: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2023 Oct 26 14:24:21 (6ddeb5033df0) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":722175884,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1698330249,"end_time":1698330249,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1"}
sca.type: summary
sca.scan_id: 722175884
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml

  ```
</details>
<details>
<summary>Agent log:</summary>

  ```
/var/ossec/logs/ossec.log:46:2023/10/26 16:00:42 sca: INFO: Module started.
/var/ossec/logs/ossec.log:47:2023/10/26 16:00:42 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
/var/ossec/logs/ossec.log:48:2023/10/26 16:00:42 sca: INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'
  ```
</details>

<details>
<summary>Inventory:</summary>

 <img src="https://github.com/wazuh/wazuh/assets/21695385/4ea1381e-67e3-447f-a7ef-ece9709aac7d">
</details>

## :green_circle: Vulnerability detector


<details>
<summary>Manager Config</summary>

  ```
    <!-- Ubuntu OS vulnerabilities -->
    <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <os allow="Ubuntu-23">jammy</os>
      <update_interval>10s</update_interval>
    </provider>

  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/f104a8a3-4513-4ad5-a94e-f3189b6f01a6">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>002</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>


<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/96801512-0bc4-4886-9209-4199e5c9abd9">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e10e5a6f-70e6-402a-8a16-733fbfe7bbbc">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/1c7dc478-0a25-4aba-8a6b-2f7f635e75d8">
</details>

**Comment by lchico** [comment]
Moved ETA 2 day for reviewing

**Comment by ncvicchi** [comment]
Moved ETA for some changes were required
