### ISSUE TITLE
Check Wazuh compatibility with new version Amazon Linux 2023.2.20231030-1

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#19564]
# Description

Note: This issue was created for the 2023.2.20231002.0 version of Amazon Linux and since at time of testing there was a new one, we use the latest 2023.2.0.20231020.1. However the downloaded file did not prove to be the required one, we prefer to use AWS VMs. (2) provide by [@cicd-team](https://wazuh-team.slack.com/admin/user_groups) ([issue](https://github.com/wazuh/internal-devel-requests/issues/463))

Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of the Amazon Linux 2023 - 2023.2.20231002 operating system.

OSs checks https://github.com/wazuh/wazuh/issues/19559

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK upgrade / uninstall. 
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by ed108206** [comment]
Switch to the latest version of Amazon Linux 2023

**Comment by ed108206** [comment]
# Testing

###   :green_circle:  Agent and server, (enrollment and connectivity with the manager)

The Amazon Linux 2023 was implemented in a virtual machine ussing the [os-images](https://cdn.amazonlinux.com/os-images/2.0.20231020.1/) 
provide by AWS, and following the steps established in [the documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/amazon-linux-2-virtual-machine.html). 
By [this guide](https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html) the Agent was installed in the Amazon Linux 2023 machine

Manager runs on Wazuh OVA version 4.6.0.

**Comment by ed108206** [comment]
Status change due to new testing approach. 
Issue: https://github.com/wazuh/internal-devel-requests/issues/463

**Comment by jotacarma90** [comment]
LGTM
