### ISSUE TITLE
FIM and wazuh-modulesd have increased its amount of disk read

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19566]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-40508 | FIM | Manager | Packages | CentOS 7 |

## Description

During https://github.com/wazuh/wazuh/issues/19502 we've detected an increase in Disk Read.

History:
- In `4.4.2` FIM reached the maximum of `~1.5 x 1e11` (Bytes) in Disk Read
  - `wazuh-modulesd` reached the maximum of `~0.8 x 1e11` (Bytes)
<details><img src="https://camo.githubusercontent.com/f8a4b77eb258c67546aaa4cf69bca8e0e07b78d6cea26f0173dacc4326c45e22/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e342e322f42333936322d333630306d2f42333936325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42333936325f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67"/></details>

- In `4.5.1` FIM reached the maximum of `~1.2 x 1e11` (Bytes) in Disk Read [DECREASED]
  - `wazuh-modulesd` reached the maximum of `~0.4 x 1e11` (Bytes) [DECREASED]
<details><img src="https://camo.githubusercontent.com/6668e8ed49226bcdb9b894741bb187a3dde0feaae3d09768d95d5ee99d4c1513/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e312f42343235362d333630306d2f42343235365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343235365f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67"/></details>

- In `4.5.2` (last production version) FIM reached the maximum of `~1.1 x 1e11` (Bytes) [DECREASED]
  - `wazuh-modulesd` reached the maximum of `~0.5 x 1e11` (Bytes) [**INCREASED**]
<details><img src="https://camo.githubusercontent.com/a50959e7a1a9aea804ceea1fb013b50637871b87a25caefdf30e4c45e80b31b3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343238325f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67"/></details>

- **Now**, in `4.5.3-rc3` we can see that this value increased again reaching a max of `~1.5 x 1e11` (Bytes)
  - `wazuh-modulesd` reached the maximum of `~1.2 x 1e11` (Bytes) [**INCREASED**]
<img src="https://camo.githubusercontent.com/cae5d09139675dd0aa876d8710d67162cb8c497b72d991fd2d8e3246fffc4616/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433365f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67"/>

***

No related errors were found in the logs.

We should research why this value increased again.

**Comment by mauromalara** [comment]
## Evidence


### Logs

[ossec_Test_stress_B4436_manager_2023-10-08.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/logs/ossec_Test_stress_B4436_manager_2023-10-08.zip)

### CSVs
[monitor-manager-Test_stress_B4436_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/monitor-manager-Test_stress_B4436_manager-pre-release.csv)
[Test_stress_B4436_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_events.csv)
[Test_stress_B4436_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_state.csv)
[Test_stress_B4436_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_remoted_state.csv)

**Comment by mauromalara** [comment]
In the Ubuntu agent, we can also see an increase of this value.

**Comment by jotacarma90** [comment]
## Update

Hi team, I have been analyzing this in depth.
One of the things I have checked, is to look at all the stress test graphs that contain syscheck in their tests.
These are the graphs of all the tests where syscheck is active:

![1](https://github.com/wazuh/wazuh/assets/60003131/8bebf396-0e3a-4e49-b8f9-fecc8f4929eb)
![2](https://github.com/wazuh/wazuh/assets/60003131/87cf3a76-bf76-4393-a7a1-39338c8bd1a5)
![3](https://github.com/wazuh/wazuh/assets/60003131/09b90f59-841c-4ddc-b455-f5e74b32c6e6)
![4](https://github.com/wazuh/wazuh/assets/60003131/8280583d-7475-4b6e-a533-4269459dc61c)
![5](https://github.com/wazuh/wazuh/assets/60003131/9866fc1a-d955-4d94-9686-29112d1a1eb8)
![6](https://github.com/wazuh/wazuh/assets/60003131/2ff9fdd0-8e40-4f89-9a90-a0445fd78700)
![7](https://github.com/wazuh/wazuh/assets/60003131/cfae8a06-8160-49d1-8560-ca6e79ffdc95)

## Conclusions
As you can see there is an oscillation in disk usage read from 1e11 to 1.7e11.
I also put an example of the previous release 4.5.2, where you can see this high value (the same oscillation appears between different tests).

![old](https://github.com/wazuh/wazuh/assets/60003131/88c1bc18-de68-4599-8ed3-5f3c69ab3e9e)

## Extend
Finally, I have seen that in the ONLY syscheck test graphs the value of the read disk used by syscheck is up to 20 times lower, which makes me wonder if these values of the other graphs really correspond to syscheck.
![8](https://github.com/wazuh/wazuh/assets/60003131/f46fa073-4c43-4865-8a87-94ee381b70c9)
