### ISSUE TITLE
Test: Installation

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1956]
# Installation test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## RPM (Linux)

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log
- [x] CentOS5
- [x] Check uninstall (services / files / users)
- [x] /opt

## DEB (Linux)

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] Check apt-get remove
- [x] Check apt-get purge
- [x] Check uninstall (services / files / users)
- [x] No errors in ossec.log

## Mac OS X

- [x] Successful installation
- [x] Check version

## Solaris (Intel)

- [x] Successful installation
- [x] Check version

## Solaris (SPARC)

- [x] Successful installation
- [x] Check version

## (HP-UX)

- [x] Successful installation
- [x] Check version

## AIX

- [x] Successful installation
- [x] Check version

## Sources

- [x] Successful installation
- [x] Check version
- [x] Check ruleset version
- [x] Service is running after installation
- [x] Service status
- [x] Running processes
- [x] No errors in ossec.log

**Comment by juan70** [comment]
# Manager Install From Packages
## RPM
### CentOS 7
  - Successful installation
    - `yum -v --rpmverbosity=debug install wazuh-manager 2>&1 | tee zzinstall.txt`
    - No error while installing
    - `/var/ossec/` populated
- Check version (`cat /etc/ossec-init.conf`)
  - v3.7.1 (rev 3721)
- Check ruleset version (`cat /var/ossec/ruleset/VERSION`)
  - v3.7.1 (rev 3703)
- Service is running after installation (`systemctl status wazuh-manager`)
  - active
- Service status (`service wazuh-manager status`)
  ```
  wazuh-clusterd not running...
  wazuh-modulesd is running...
  ossec-monitord is running...
  ossec-logcollector is running...
  ossec-remoted is running...
  ossec-syscheckd is running...
  ossec-analysisd is running...
  ossec-maild not running...
  ossec-execd is running...
  wazuh-db is running...
  ```
- Running processes (`ps -ef`)
  ```
  UID        PID  PPID  C STIME TTY          TIME CMD
  ossec    19834     1  0 Nov26 ?        00:00:00 /var/ossec/bin/wazuh-db
  root     19848     1  0 Nov26 ?        00:00:00 /var/ossec/bin/ossec-execd
  ossec    19854     1  0 Nov26 ?        00:00:00 /var/ossec/bin/ossec-analysisd
  root     19859     1  3 Nov26 ?        00:00:13 /var/ossec/bin/ossec-syscheckd
  ossecr   19865     1  0 Nov26 ?        00:00:00 /var/ossec/bin/ossec-remoted
  root     19869     1  0 Nov26 ?        00:00:00 /var/ossec/bin/ossec-logcollector
  ossec    19873     1  0 Nov26 ?        00:00:00 /var/ossec/bin/ossec-monitord
  root     19877     1  0 Nov26 ?        00:00:00 /var/ossec/bin/wazuh-modulesd
  ```
- No errors in ossec.log (`grep -v INFO /var/ossec/logs/ossec.log`)
  - check
- `/opt`
  - nothing related to wazuh or ossec
- Check uninstall (services / files / users)
  - `yum -v --rpmverbosity=debug remove wazuh-manager 2>&1 | tee zzuninstall.txt`
  - `tree /var/ossec`
    ```
    /var/ossec/etc/
    ├── ossec.conf.rpmsave
    ├── shared.save
    │   ├── ar.conf
    │   └── default
    │       └── merged.mg
    ├── sslmanager.cert.save
    └── sslmanager.key.save
    ```
  - `ls /etc/*wazuh*` => no file
  - `ls /etc/*ossec*` => no file
  - `systemctl status wazuh-manager` 
    - service could not be found
  - `service wazuh-manager status`
    - service could not be found
  - `ps -ef`
    - none of them
  - `grep ossec /etc/passwd`
    - no result
  - `grep ossec /etc/group`
    - no result

**=> OK.**

### CentOS 5 (32bits)
CentOS 5 has reached EOL and is not updated anymore. The `Vault` repository should be used `http://vault.centos.org`:
https://www.ndchost.com/wiki/centos5/cannot-find-a-valid-baseurl-error-fix
- for 32-bit systems, use: http://vault.centos.org/5.11/os/i386/
- for 32-bit systems, use: http://vault.centos.org/5.11/updates/i386/
- for 32-bit systems, use: http://vault.centos.org/5.11/extras/i386/
- for 64-bit systems, use: http://vault.centos.org/5.11/os/x86_64/ 
- for 64-bit systems, use: http://vault.centos.org/5.11/updates/x86_64/ 
- for 64-bit systems, use: http://vault.centos.org/5.11/extras/x86_64/ 
- for epel: https://archives.fedoraproject.org/pub/archive/epel/5/i386/

`yum clean all; yum update`

Error with Wazuh pre-release repo, for both i386 and x86_64 versions of CentOS 5:
  ```
  Loaded plugins: fastestmirror, security
  Determining fastest mirrors
  base                                                                                            | 1.1 kB     00:00     
  base/primary                                                                                    | 996 kB     00:00     
  base                                                                                                         2791/2791
  epel                                                                                            | 3.6 kB     00:00     
  epel/primary_db                                                                                 | 2.4 MB     00:02     
  extras                                                                                          | 2.1 kB     00:00     
  extras/primary_db                                                                               | 164 kB     00:00     
  updates                                                                                         | 1.9 kB     00:00     
  updates/primary_db                                                                              | 904 kB     00:00     
  wazuh_pre_release                                                                               | 3.4 kB     00:00     
  wazuh_pre_release/primary_db                                                                    |  65 kB     00:00     
  https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/repodata/96bafd607acde4623cc5b06a4eaad6a7c59a176edacefca4bfc29cd5bdb5def1-primary.sqlite.bz2: [Errno -3] Error performing checksum
  Trying other mirror.
  wazuh_pre_release/primary_db                                                                    |  65 kB     00:00     
  https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/repodata/96bafd607acde4623cc5b06a4eaad6a7c59a176edacefca4bfc29cd5bdb5def1-primary.sqlite.bz2: [Errno -3] Error performing checksum
  Trying other mirror.
  Error: failure: repodata/96bafd607acde4623cc5b06a4eaad6a7c59a176edacefca4bfc29cd5bdb5def1-primary.sqlite.bz2 from wazuh_pre_release: [Errno 256] No more mirrors to try.
  ```

**=> FAIL**

### Fedora 29
  - Successful installation
    - `yum -v --rpmverbosity=debug install wazuh-manager 2>&1 | tee zzinstall.txt`
    - No error while installing
    - `/var/ossec/` populated
- Check version (`cat /etc/ossec-init.conf`)
  - v3.7.1 (rev 3721)
- Check ruleset version (`cat /var/ossec/ruleset/VERSION`)
  - v3.7.1 (rev 3703)
- Service is running after installation (`systemctl status wazuh-manager`)
  - active
- Service status (`service wazuh-manager status`)
  ```
  wazuh-clusterd not running...
  wazuh-modulesd is running...
  ossec-monitord is running...
  ossec-logcollector is running...
  ossec-remoted is running...
  ossec-syscheckd is running...
  ossec-analysisd is running...
  ossec-maild not running...
  ossec-execd is running...
  wazuh-db is running...
  ```
- Running processes (`ps -ef`)
  ```
  UID        PID  PPID  C STIME TTY          TIME CMD
  ossec     3636     1  0 00:47 ?        00:00:00 /var/ossec/bin/wazuh-db
  root      3650     1  0 00:47 ?        00:00:00 /var/ossec/bin/ossec-execd
  ossec     3656     1  0 00:47 ?        00:00:00 /var/ossec/bin/ossec-analysisd
  root      3665     1  9 00:47 ?        00:00:09 /var/ossec/bin/ossec-syscheckd
  ossecr    3667     1  0 00:47 ?        00:00:00 /var/ossec/bin/ossec-remoted
  root      3671     1  0 00:47 ?        00:00:00 /var/ossec/bin/ossec-logcollector
  ossec     3675     1  0 00:47 ?        00:00:00 /var/ossec/bin/ossec-monitord
  root      3679     1  0 00:47 ?        00:00:00 /var/ossec/bin/wazuh-modulesd
  ```
- No errors in ossec.log (`grep -v INFO /var/ossec/logs/ossec.log`)
  - no errors, but plenty of warnings (1161) such as
  ```
  2018/11/27 00:48:56 ossec-syscheckd: WARNING: Unable to add inode to db: /boot/grub2/i386-pc/fat.mod (136)
  ```
- `/opt`
  - nothing related to wazuh or ossec
- Check uninstall (services / files / users)
  - `yum -v --rpmverbosity=debug remove wazuh-manager 2>&1 | tee zzuninstall.txt`
  - `tree /var/ossec`
    ```
    /var/ossec
    └── etc
        ├── ossec.conf.rpmsave
        ├── shared.save
        │   ├── ar.conf
        │   └── default
        │       └── merged.mg
        ├── sslmanager.cert.save
        └── sslmanager.key.save
    ```
  - `ls /etc/*wazuh*` => no file
  - `ls /etc/*ossec*` => no file
  - `systemctl status wazuh-manager` 
    - service could not be found
  - `service wazuh-manager status`
    - service could not be found
  - `ps -ef`
    - none of them
  - `grep ossec /etc/passwd`
    - no result
  - `grep ossec /etc/group`
    - no result

**=> OK.**

### OpenSuse 15.0

Differences compared to CentOS and Fedora:
  1. Install `yum` first.
  2.  The path to `yum.repos.d` must be `yum/repos.d`
  echo -e '[wazuh_pre_release]\ngpgcheck=1\ngpgkey=https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum/repos.d/wazuh_pre.repo

  - Successful installation
    - `yum -v --rpmverbosity=debug install wazuh-manager 2>&1 | tee zzinstall.txt`
    - No error while installing, but a message (not tagged as an error or a warning...):
      `Rpmdb checksum is invalid: dCDPT(pkg checksums)` 
    - `/var/ossec/` populated
- Check version (`cat /etc/ossec-init.conf`)
  - v3.7.1 (rev 3721)
- Check ruleset version (`cat /var/ossec/ruleset/VERSION`)
  - v3.7.1 (rev 3703)
- Service is running after installation (`systemctl status wazuh-manager`)
  - active
- Service status (`service wazuh-manager status`)
  - active too. Same output as `systemctl`.
- Running processes (`ps -ef`)
  ```
  UID        PID  PPID  C STIME TTY          TIME CMD
  ossec     7764     1  0 10:12 ?        00:00:00 /var/ossec/bin/wazuh-db
  root      7778     1  0 10:12 ?        00:00:00 /var/ossec/bin/ossec-execd
  ossec     7784     1  0 10:12 ?        00:00:00 /var/ossec/bin/ossec-analysisd
  root      7788     1  1 10:12 ?        00:00:05 /var/ossec/bin/ossec-syscheckd
  ossecr    7796     1  0 10:12 ?        00:00:00 /var/ossec/bin/ossec-remoted
  root      7797     1  0 10:12 ?        00:00:00 /var/ossec/bin/ossec-logcollector
  ossec     7817     1  0 10:12 ?        00:00:00 /var/ossec/bin/ossec-monitord
  root      7821     1  0 10:12 ?        00:00:00 /var/ossec/bin/wazuh-modulesd
  ```
- No errors in ossec.log (`grep -v INFO /var/ossec/logs/ossec.log`)
  - no errors, but a few warnings (20) such as
  ```
  2018/11/27 10:12:52 ossec-syscheckd: WARNING: Unable to add inode to db: /bin/pkill (6015)
  ```
- `/opt`
  - nothing related to wazuh or ossec
- Check uninstall (services / files / users)
  - `yum -v --rpmverbosity=debug remove wazuh-manager 2>&1 | tee zzuninstall.txt`
  - `tree /var/ossec`
    ```
    /var/ossec
    └── etc
        ├── ossec.conf.rpmsave
        ├── shared.save
        │   ├── ar.conf
        │   └── default
        │       └── merged.mg
        ├── sslmanager.cert.save
        └── sslmanager.key.save
    ```
  - `ls /etc/*wazuh*` => no file
  - `ls /etc/*ossec*` => no file
  - `systemctl status wazuh-manager` 
    - service could not be found
  - `service wazuh-manager status`
    - no such service
  - `ps -ef`
    - none of them
  - `grep ossec /etc/passwd`
    - no result
  - `grep ossec /etc/group`
    `ossec:x:478:`

**=> OK?** Group `ossec` not completely removed, no user belongs to this group.



## DEB
### Debian 9
  - Successful installation
    - `apt install wazuh-manager`
    - No error while installing
    - `/var/ossec/` populated
- Check version (`cat /etc/ossec-init.conf`)
  - v3.7.1 (rev 3721)
- Check ruleset version (`cat /var/ossec/ruleset/VERSION`)
  - v3.7.1 (rev 3703)
- Service is running after installation (`systemctl status wazuh-manager`)
  - active
- Service status (`service wazuh-manager status`)
  Same output as `systemctl`.
- Running processes (`ps -ef`)
  ```
  UID        PID  PPID  C STIME TTY          TIME CMD
  ossec     3487     1  0 11:57 ?        00:00:00 /var/ossec/bin/wazuh-db
  root      3501     1  0 11:57 ?        00:00:00 /var/ossec/bin/ossec-execd
  ossec     3507     1  0 11:57 ?        00:00:00 /var/ossec/bin/ossec-analysisd
  root      3512     1  2 11:57 ?        00:00:04 /var/ossec/bin/ossec-syscheckd
  ossecr    3519     1  0 11:57 ?        00:00:00 /var/ossec/bin/ossec-remoted
  root      3523     1  0 11:57 ?        00:00:00 /var/ossec/bin/ossec-logcollector
  ossec     3527     1  0 11:57 ?        00:00:00 /var/ossec/bin/ossec-monitord
  root      3532     1  0 11:57 ?        00:00:00 /var/ossec/bin/wazuh-modulesd
  ```
- No errors in ossec.log (`grep -v INFO /var/ossec/logs/ossec.log`)
  - no errors, but a few warnings (7) such as
  ```
  2018/11/27 11:58:12 ossec-syscheckd: WARNING: Unable to add inode to db: /bin/bzip2 (393624) 
  
  ```
- `/opt`
  - nothing related to wazuh or ossec
- Check apt-get remove
  ```
  find / | grep -i wazuh
  /etc/systemd/system/wazuh-manager.service
  /etc/init.d/wazuh-manager
  (also files related to the repo)
  ```

  ```
  tree /var/ossec
  /var/ossec
  ├── etc
  │   ├── client.keys.save
  │   ├── decoders
  │   │   └── local_decoder.xml.save
  │   ├── lists
  │   │   ├── amazon
  │   │   │   ├── aws-eventnames.cdb.save
  │   │   │   ├── aws-eventnames.save
  │   │   │   ├── aws-sources.cdb.save
  │   │   │   └── aws-sources.save
  │   │   ├── audit-keys.cdb.save
  │   │   └── audit-keys.save
  │   ├── local_internal_options.conf.save
  │   ├── ossec.conf.save
  │   ├── rootcheck
  │   │   ├── cis_apache2224_rcl.txt.save
  (...)
  │   │   └── win_malware_rcl.txt.save
  │   ├── rules
  │   │   └── local_rules.xml.save
  │   └── shared
  │       ├── ar.conf.save
  │       └── default
  │           ├── agent.conf.save.save
  │           └── merged.mg.save
  └── logs
      ├── alerts
      (...)
      │   ├── alerts.json
      │   └── alerts.log
      ├── archives
      (...)
      │   └── archives.log
      └── firewall
      (...)
          └── firewall.log
  ```

- Check apt-get purge
  ```
  find / | grep -i wazuh
  (only files related to the repo)
  ```
  ```
  find / | grep -i ossec
  (no output, no file/directory found)
  ```
- Check uninstall (services / files / users)
  - `ls /etc/*wazuh*` => no file
  - `ls /etc/*ossec*` => no file
  - `systemctl status wazuh-manager` 
    - service could not be found
  - `service wazuh-manager status`
    - service could not be found
  - `ps -ef`
    - none of them
  - `grep ossec /etc/passwd`
    - no result
  - `grep ossec /etc/group`
    - no result

**=> OK.**

Note: when installing and removing/purging several times in a row, a message is thrown:
```
sh: 0: getcwd() failed: No such file or directory
```
4 messages while installing, and 2 while removing/purging.


### Ubuntu 18
  - Successful installation
    - `apt install wazuh-manager`
    - No error while installing
    - `/var/ossec/` populated
- Check version (`cat /etc/ossec-init.conf`)
  - v3.7.1 (rev 3721)
- Check ruleset version (`cat /var/ossec/ruleset/VERSION`)
  - v3.7.1 (rev 3703)
- Service is running after installation (`systemctl status wazuh-manager`)
  - active
- Service status (`service wazuh-manager status`)
  Same output as `systemctl`.
- Running processes (`ps -ef`)
  ```
  UID        PID  PPID  C STIME TTY          TIME CMD
  ossec    23521     1  0 12:36 ?        00:00:00 /var/ossec/bin/wazuh-db
  root     23535     1  0 12:36 ?        00:00:00 /var/ossec/bin/ossec-execd
  ossec    23541     1  0 12:36 ?        00:00:00 /var/ossec/bin/ossec-analysisd
  root     23545     1 12 12:36 ?        00:00:09 /var/ossec/bin/ossec-syscheckd
  ossecr   23554     1  0 12:36 ?        00:00:00 /var/ossec/bin/ossec-remoted
  root     23555     1  0 12:36 ?        00:00:00 /var/ossec/bin/ossec-logcollector
  ossec    23577     1  0 12:36 ?        00:00:00 /var/ossec/bin/ossec-monitord
  root     23580     1  0 12:36 ?        00:00:00 /var/ossec/bin/wazuh-modulesd
  ```
- No errors in ossec.log (`grep -v INFO /var/ossec/logs/ossec.log`)
  - no errors, but a few warnings (6) such as
  ```
  2018/11/27 12:37:07 ossec-syscheckd: WARNING: Unable to add inode to db: /bin/bzip2 (131809) 
  
  ```
- `/opt`
  - nothing related to wazuh or ossec
- Check apt-get remove
  ```
  find / | grep -i wazuh
  /etc/systemd/system/wazuh-manager.service
  /etc/init.d/wazuh-manager
  (also files related to the repo)
  (and also many in /sys/kernel/slab/)
  ```

  ```
  tree /var/ossec
  /var/ossec
  ├── etc
  │   ├── client.keys.save
  │   ├── decoders
  │   │   └── local_decoder.xml.save
  │   ├── lists
  │   │   ├── amazon
  │   │   │   ├── aws-eventnames.cdb.save
  │   │   │   ├── aws-eventnames.save
  │   │   │   ├── aws-sources.cdb.save
  │   │   │   └── aws-sources.save
  │   │   ├── audit-keys.cdb.save
  │   │   └── audit-keys.save
  │   ├── local_internal_options.conf.save
  │   ├── ossec.conf.save
  │   ├── rootcheck
  │   │   ├── cis_apache2224_rcl.txt.save
  (...)
  │   │   └── win_malware_rcl.txt.save
  │   ├── rules
  │   │   └── local_rules.xml.save
  │   └── shared
  │       ├── ar.conf.save
  │       └── default
  │           ├── agent.conf.save.save
  │           └── merged.mg.save
  └── logs
      ├── alerts
      (...)
      │   ├── alerts.json
      │   └── alerts.log
      ├── archives
      (...)
      │   └── archives.log
      └── firewall
      (...)
          └── firewall.log
  ```

- Check apt-get purge
  ```
  find / | grep -i wazuh
  (only files related to the repo, and /sys/kernel/slab/)
  ```
  ```
  find / | grep -i ossec
  (no output, no file/directory found)
  ```
- Check uninstall (services / files / users)
  - `ls /etc/*wazuh*` => no file
  - `ls /etc/*ossec*` => no file
  - `systemctl status wazuh-manager` 
    - inactive after `remove`
    - service could not be found after `purge`
  - `service wazuh-manager status`
    - inactive after `remove`
    - service could not be found after `purge`
  - `ps -ef`
    - none of them
  - `grep ossec /etc/passwd`
    - no result
  - `grep ossec /etc/group`
    - no result

**=> OK.**


### Quick Summary
- CentOS 5: Problem with the dev repo.
- Debian 9: A weird message when installing/removing/purging several times.
- Others: Sometimes a warning is present in `ossec.log` after installation.

**Comment by juan70** [comment]
# Manager Install From Sources

## CentOS7
No errors in `ossec.log, only several warnings similar to this one:
  ```
  2018/11/27 05:49:05 ossec-syscheckd: WARNING: Unable to add inode to db: /boot/initramfs-3.10.0-862.14.4.el7.x86_64.img (70)
  ```

**=> OK**

## CentOS5 (32bits)
- Problem accessing external packages. Error returned on `make deps`. Compilation fails.

**=> FAIL**

## Fedora 29
- Many warning during compilation.
- No errors in `ossec.log`, but many warnings.

**=> OK**

## OpenSuse 15.0
- Many warning during compilation (less than on Fedora29, though).
- Also some warnings in `ossec.log`, but no errors.

**=> OK**

## Debian 9
- Also some warnings in `ossec.log` (very few), but no errors.

**=> OK**

## Ubuntu 18
- Also some warnings in `ossec.log` (very few), but no errors.

**=> OK**

## Quick Summary
- Cannot compile on CentOS 5.
- Many warning during compilation on Fedora 29.

**Comment by juan70** [comment]
# Agent Install from Packages

## RPM
### CentOS 7
Just a warning while uninstalling:
```
warning: /var/ossec/etc/ossec.conf saved as /var/ossec/etc/ossec.conf.rpmsave
```
which is OK.


**=>OK.**

### CentOS 5
Error while executing `yum update`:
```
wazuh_pre_release                                                                               | 3.4 kB     00:00     
wazuh_pre_release/primary_db                                                                    |  65 kB     00:00     
https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/repodata/df0e22165631501812f48c3c4333d21850aad897822a29ce6a10b07a54006504-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
wazuh_pre_release/primary_db                                                                    |  65 kB     00:00     
https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/repodata/df0e22165631501812f48c3c4333d21850aad897822a29ce6a10b07a54006504-primary.sqlite.bz2: [Errno -3] Error performing checksum
Trying other mirror.
Error: failure: repodata/df0e22165631501812f48c3c4333d21850aad897822a29ce6a10b07a54006504-primary.sqlite.bz2 from wazuh_pre_release: [Errno 256] No more mirrors to try.
```

**=> FAIL**

### Fedora 29
While uninstalling, same warning as for CentOS 7, which is OK.

**=> OK.**

### OpenSuse 15.0
While uninstalling, same warning as for CentOS 7, which is OK.

**=> OK.**

## DEB
### Debian 9
**=> OK.**

### Ubuntu 18
**=> OK.**

## Others
### Windows
Uninstallation leaves `local_internal_options.conf.save` and `ossec.conf.save`. This is correct.

**=> OK.**

**Comment by juan70** [comment]
# Agent Install from Sources

## RPM
### CentOS 7
**=> OK.**

### CentOS 5
Compilation fails:
```
4- Installing the system

 - Running the Makefile

curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/3.7/cJSON.tar.gz
make: *** [external/cJSON.tar.gz] Error 35
Makefile:636: *** No external directory found. Run "make deps" before compiling external libraries.  Stop.
```

```
# wget https://packages.wazuh.com/deps/3.7/cJSON.tar.gz
--2018-11-28 09:59:59--  https://packages.wazuh.com/deps/3.7/cJSON.tar.gz
Resolving packages.wazuh.com... 52.85.51.96, 52.85.51.166, 52.85.51.12, ...
Connecting to packages.wazuh.com|52.85.51.96|:443... connected.
OpenSSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Unable to establish SSL connection.
```

**=> FAIL**

### Fedora 29
Many warnings during compilation, similar to this:
```
addagent/manage_agents.c:345:45: warning: ‘%s’ directive output may be truncated writing up to 257 bytes into a region of size between 55 and 65 [-Wformat-truncation=]
```

**=> OK**

### OpenSuse 15.0
(The compilation warnings seen on Fedora 29 do not appear here.)

**=> OK**

## DEB
### Debian 9

**=> OK**

### Ubuntu 18

**=> OK**
