### ISSUE TITLE
wazuh-modulesd presents some peaks and increases in memory usage

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19567]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-40508 | FIM | Manager | Packages | CentOS 7 |

## Description

- During https://github.com/wazuh/wazuh/issues/19502 we've detected an increase in PSS.

- Compared with `4.5.2` this RC presents some increases and abnormal peaks during the test.

- Checking the logs we don’t see it's related to anything but with the Azure module, but it's necessary a further research.

- Those peaks are not present in `4.4.2` or `4.5.1`

### PSS

| `4.5.2` | `4.5.3-rc3`|
|--|--|
| <img src="https://camo.githubusercontent.com/60d3eb7555658ee56b8a897435342b1cb1155303e5cb4a535eec68ba01be6130/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343238325f6d616e616765722d7072652d72656c656173655f5053532e706e67" /> | <img src="https://camo.githubusercontent.com/c9f0e4b565e26840d18bdd3a2e190da9a503dbf056ce81832edf56f77a00e8e8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433365f6d616e616765722d7072652d72656c656173655f5053532e706e67" />

### RSS (MAX-MIN)

| `4.5.2` | `4.5.3-rc3`|
|--|--|
| <img src="https://camo.githubusercontent.com/5d1a3867bb3e77ba18173e39f65e1d06aec7129d093ffa33be662fd877167f97/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343238325f6d616e616765722d7072652d72656c656173655f5253535f4d41584d494e2e706e67" /> | <img src="https://camo.githubusercontent.com/94009af58a8bb1bf2ea14536b350dcf5a1f7a45f59c2e73cd99a951660d8b228/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433365f6d616e616765722d7072652d72656c656173655f5253535f4d41584d494e2e706e67" />

### RSS

| `4.5.2` | `4.5.3-rc3`|
|--|--|
| <img src="https://camo.githubusercontent.com/71d375706d42439dae4e5dffa62e511bed93ea01b1abd35a6780d876d27c1428/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343238325f6d616e616765722d7072652d72656c656173655f5253532e706e67" /> | <img src="https://camo.githubusercontent.com/5e9243641fb608160c4333a9b876fe320103e037e6e08cfb57841dd4fed33468/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433365f6d616e616765722d7072652d72656c656173655f5253532e706e67" />

### USS

| `4.5.2` | `4.5.3-rc3`|
|--|--|
| <img src="https://camo.githubusercontent.com/52e681b23ad41f85a508a8aa99da113ab4b0cb2c83e2473503e41381d2c79453/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e322f42343238322d333630306d2f42343238325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343238325f6d616e616765722d7072652d72656c656173655f5553532e706e67" /> | <img src="https://camo.githubusercontent.com/832bf2e54f2af261c4bb6299bb0f88ac4d378d6c58898d3fe91f79e6fe3d0d39/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433362d333630306d2f42343433365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433365f6d616e616765722d7072652d72656c656173655f5553532e706e67" />

### Evidence

**Logs**

[ossec_Test_stress_B4436_manager_2023-10-08.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/logs/ossec_Test_stress_B4436_manager_2023-10-08.zip)

**CSVs**

[monitor-manager-Test_stress_B4436_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/monitor-manager-Test_stress_B4436_manager-pre-release.csv)
[Test_stress_B4436_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_events.csv)
[Test_stress_B4436_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_analysisd_state.csv)
[Test_stress_B4436_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4436-3600m/B4436_manager_centos/data/Test_stress_B4436_manager_remoted_state.csv)

**Comment by mauromalara** [comment]
### Update

We don’t observe this behavior in agents.

**Comment by davidjiglesias** [comment]
This is duplicate with https://github.com/wazuh/wazuh/issues/19531
