### ISSUE TITLE
Increased Modulesd disk usage on manager 4.6.0-rc1

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#19579]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc1 | modulesd | Manager | Packages/Sources | Centos |

# Description

 During Footprint tests https://github.com/wazuh/wazuh/issues/19553, an increase in disk usage by `wazuh-modulesd`  has been found on the manager, in comparison with `4.5.3-rc1`
 
 - Increased overall `Disk Usage` with higher sustained peak of ~120  up from ~80.
    - 4.6.0
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4447-3600m/B4447_manager_centos/plots/monitor-manager-Test_stress_B4447_manager-pre-release_Disk.png)
    - 4.5.3
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4425-3600m/B4425_manager_centos/plots/monitor-manager-Test_stress_B4425_manager-pre-release_Disk.png)

 - Increased Disk read with peaks that show earlier and with a level of 6.0, up from 1.0
    - 4.6.0
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4447-3600m/B4447_manager_centos/plots/monitor-manager-Test_stress_B4447_manager-pre-release_Disk_Read.png)
    - 4.5.3
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4425-3600m/B4425_manager_centos/plots/monitor-manager-Test_stress_B4425_manager-pre-release_Disk_Read.png)

 - Disk written highest valuein the timeframe of event generation doubled from 1.0 to 2.0
    - 4.6.0
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4447-3600m/B4447_manager_centos/plots/monitor-manager-Test_stress_B4447_manager-pre-release_Disk_Written.png)
    - 4.5.3
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4425-3600m/B4425_manager_centos/plots/monitor-manager-Test_stress_B4425_manager-pre-release_Disk_Written.png)

 - Write Operations highest value in the timeframe of event generation doubled from 1.0 to 2.0
    - 4.6.0
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4447-3600m/B4447_manager_centos/plots/monitor-manager-Test_stress_B4447_manager-pre-release_Write_Ops.png)
    - 4.5.3
       ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4425-3600m/B4425_manager_centos/plots/monitor-manager-Test_stress_B4425_manager-pre-release_Write_Ops.png)

**Comment by cborla** [comment]
Similar than [17927](https://github.com/wazuh/wazuh/issues/17927)

**Comment by Deblintrake09** [comment]
Detected in https://github.com/wazuh/wazuh/issues/19551

<details><summary>Manager</summary>
- Increased disk usage
  - 4.6.0
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_manager_centos/plots/monitor-manager-Test_stress_B4446_manager-pre-release_Disk.png)
  - 4.5.3
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_manager_centos/plots/monitor-manager-Test_stress_B4424_manager-pre-release_Disk.png)
- Disk write increased for modulesd
  - 4.6.0
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_manager_centos/plots/monitor-manager-Test_stress_B4446_manager-pre-release_Disk_Written.png)
  - 4.5.3
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_manager_centos/plots/monitor-manager-Test_stress_B4424_manager-pre-release_Disk_Written.png)
- Write_Ops increased for modulesd
  - 4.6.0
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_manager_centos/plots/monitor-manager-Test_stress_B4446_manager-pre-release_Write_Ops.png)
  - 4.5.3
  ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_manager_centos/plots/monitor-manager-Test_stress_B4424_manager-pre-release_Write_Ops.png)
</details>

<details><summary>Centos Agent</summary>
- Increased disk usage
   - 4.6.0
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_agent_centos/plots/monitor-agent-Test_stress_B4446_centos-pre-release_Disk.png)
   - 4.5.3
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_agent_centos/plots/monitor-agent-Test_stress_B4424_centos-pre-release_Disk.png)
- Write_Ops increased for modulesd
   - 4.6.0
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_agent_centos/plots/monitor-agent-Test_stress_B4446_centos-pre-release_Write_Ops.png)
   - 4.5.3
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_agent_centos/plots/monitor-agent-Test_stress_B4424_centos-pre-release_Write_Ops.png)
</details>

<details><summary>Ubuntu Agent</summary>
- Increased disk usage
   - 4.6.0
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_agent_ubuntu/plots/monitor-agent-Test_stress_B4446_ubuntu-pre-release_Disk_Read.png)
   - 4.5.3
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_agent_ubuntu/plots/monitor-agent-Test_stress_B4424_ubuntu-pre-release_Disk.png)
- Write_Ops increased for modulesd
   - 4.6.0
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4446-3600m/B4446_agent_ubuntu/plots/monitor-agent-Test_stress_B4446_ubuntu-pre-release_Write_Ops.png)
   - 4.5.3
   ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.5.3/B4424-3600m/B4424_agent_ubuntu/plots/monitor-agent-Test_stress_B4424_ubuntu-pre-release_Write_Ops.png)
</details>

**Comment by pereyra-m** [comment]
Hello @Deblintrake09 !

I have a question about these plots

> Increased Disk read with peaks that show earlier and with a level of 6.0, up from 1.0

I'd say that in v4.6.0 the final value after the full load period is lower than v4.5.3.
Do you consider that the behavior is worse now?

**Comment by pereyra-m** [comment]
@Deblintrake09 , about these plots

> Increased overall Disk Usage with higher sustained peak of ~120 up from ~80.

I think that the final result is the same for both plots. And I wouldn't be particularly worried about that temporary burst.  But if we want to have an accurate measure of the beginning, I'd disable `syscollector` in the `vulnerability-detector` tests to make the plots more reliable. Both modules live in `wazuh-modulesd`

https://github.com/wazuh/wazuh-jenkins/blob/97179cea978401494d176382fd674a93efe63fe9/quality/tests/stress/configuration/linux/vulnerability_detector_manager.yaml#L5

Also, if the `syscollector` test presents differences in the disk usage

https://github.com/wazuh/wazuh/issues/19551#issuecomment-1756158029

We shouldn't use this issue to report them but to create a different one.

**Comment by pereyra-m** [comment]
@Deblintrake09 , about these plots

> Disk written highest valuein the timeframe of event generation doubled from 1.0 to 2.0

> Write Operations highest value in the timeframe of event generation doubled from 1.0 to 2.0

I'm taking them together because they are closely related.
I've found some differences in the configuration of both stress tests, the v4.6.0 test has fewer providers enabled, so the feeds' fetching phase shouldn't be causing this difference.

Also, the main difference in the code is the addition of support for ALMA, ALAS 2022 and Debian 12. We aren't testing these agents or downloading those feeds so this shouldn't be a problem.

What I want to know **if this test is reliable and/or meaningful.**
Consider the case for write operations. In this issue we've seen this variation (2x)
\[1 x 1e9\](v4.5.3r40508) -> \[2 x 1e9\](v4.6.0r40602)

Recent tests show these values

\[1.2 x 1e9\](v4.6.0r40600)
https://github.com/wazuh/wazuh/issues/18930

\[1 x 1e9\](v4.6.0r40601)
https://github.com/wazuh/wazuh/issues/19238

We can see that v4.6.0-rc1(r40602) has two times more operations than v4.6.0-beta1(r40601).
But the `vulnerability-detector` code hasn't changed at all, so I doubt about the reliability of these measures
https://github.com/wazuh/wazuh/compare/v4.6.0-beta1...v4.6.0-rc1

**Comment by Deblintrake09** [comment]
> Hello @Deblintrake09 !
> 
> I have a question about these plots
> 
> > Increased Disk read with peaks that show earlier and with a level of 6.0, up from 1.0
> 
> I'd say that in v4.6.0 the final value after the full load period is lower than v4.5.3. Do you consider that the behavior is worse now?

Yo seem to be correct. regarding this and could be disregarded.

**Comment by Deblintrake09** [comment]
> @Deblintrake09 , about these plots
> 
> > Disk written highest valuein the timeframe of event generation doubled from 1.0 to 2.0
> 
> > Write Operations highest value in the timeframe of event generation doubled from 1.0 to 2.0
> 
> I'm taking them together because they are closely related. I've found some differences in the configuration of both stress tests, the v4.6.0 test has fewer providers enabled, so the feeds' fetching phase shouldn't be causing this difference.
> 
> Also, the main difference in the code is the addition of support for ALMA, ALAS 2022 and Debian 12. We aren't testing these agents or downloading those feeds so this shouldn't be a problem.
> 
> What I want to know **if this test is reliable and/or meaningful.** Consider the case for write operations. In this issue we've seen this variation (2x) [1 x 1e9](v4.5.3r40508) -> [2 x 1e9](v4.6.0r40602)
> 
> Recent tests show these values
> 
> [1.2 x 1e9](v4.6.0r40600) #18930
> 
> [1 x 1e9](v4.6.0r40601) #19238
> 
> We can see that v4.6.0-rc1(r40602) has two times more operations than v4.6.0-beta1(r40601). But the `vulnerability-detector` code hasn't changed at all, so I doubt about the reliability of these measures [v4.6.0-beta1...v4.6.0-rc1](https://github.com/wazuh/wazuh/compare/v4.6.0-beta1...v4.6.0-rc1)

- Relaunched the  tests as requested in execution https://ci.wazuh.info/job/Test_stress/4464/  to validate reliability of the test.

**Comment by pereyra-m** [comment]
## Update

Thank you for the update @Deblintrake09. I'll summarize the new results here.

The test was run again, but the syscollector module is still enabled:
- I can see it in the attached configuration file
- The logs related to that module can be seen 

What is interesting about this replay, is that with the same conditions, the manager behaves differently, reinforcing the idea that **_these stress tests aren't reliable at all_**.

**Disk usage**

Now, the curve is under %100 and really similar to v4.5.3
 
![monitor-manager-Test_stress_B4464_manager-pre-release_Disk](https://github.com/wazuh/wazuh/assets/65046601/17379029-4ddc-41d6-af0c-d85ed7f986e5)

But still it isn't clear why the replay "fixed" the impossible measurement of %120 without any change in the environment, configuration or test.

**Write Ops**
The new test ends the stress phase with a value of almost 1.3 x 1e9

![monitor-manager-Test_stress_B4464_manager-pre-release_Write_Ops](https://github.com/wazuh/wazuh/assets/65046601/92191b95-dc6c-4ac0-8a93-da9090a4ede5)

The value for v4.5.3 is 1.0 x 1e9, so we could think that now we have %30 more operations.
But the last run for v4.6.0 has a value of almost 2.0 x 1e9 (%100 more). If the configuration hasn't changed, then how we could trust two consecutive measurements with the same conditions if they have such a difference?

**Disk Written**

We arrive to a similar conclusion here

![monitor-manager-Test_stress_B4464_manager-pre-release_Disk_Written](https://github.com/wazuh/wazuh/assets/65046601/45f2d01a-567d-4e1c-93c2-3f1b82324925)

The last test has a value of 1.5 x 1e12, which seems more than we had in v4.5.3 (1.0 x 1e12).
But the previous run of v4.6.0 with the same conditions is 1.8 x 1e12, so we still have too much difference between two consecutive measurements to obtain useful conclusions.

**Comment by Dwordcito** [comment]
Unfortunately, this test is not reliable, we will continue to look at this in future runs to see if it is a pattern, but here we cannot move forward with the sample provided on each execution.
