### ISSUE TITLE
Generate final tag and publish draft release for 4.5.3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#19571]
## Description

This issue attempts to publish draft release and generate final tag for version 4.5.3 in the wazuh repository.

## Tasks

- [x] Generate final tag v4.5.3 from branch 4.5.3 on wazuh repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh/releases) from [tag v4.5.3](https://github.com/wazuh/wazuh/tree/v4.5.3).

**Comment by DFolchA** [comment]
LGTM
