### ISSUE TITLE
High memory usage by wazuh-syscheckd and wazuh-agentd

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19580]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-40602 | wazuh-syscheckd/wazuh-agentd | Agent | Packages | CentOS 7/ Ubuntu 20.04.4 / Windows Server 2019 |

## Description

While analyzing the results in #19555 we noticed that this RC consumes more memory than `4.5.3`.

- 🔍 Further research is required
- 👀 If this is caused by a new feature or change it must be **justified**, otherwise a fix must be **proposed**.
- ⚠️ At the same time `wazuh-modulesd` presents a decrease in its memory usage **in some cases**.

<details><summary>Check the following results (CentOS agent):</summary></br>

| Variable | 4.5.3 | 4.6.0-40602 |
|-- |-- |--
| PSS | <img src="https://camo.githubusercontent.com/223d7e951502020d4d41c011ec8ad4c0c65ae9c96a3feba1d5e477bdfc4d0980/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f63656e746f732d7072652d72656c656173655f5053532e706e67" /> | <img src="https://camo.githubusercontent.com/69898bcdebf244b2a916560777fe2b4daa01c88d78c882376df732534853676e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f63656e746f732d7072652d72656c656173655f5053532e706e67" />
| RSS (MAX-MIN) | <img src="https://camo.githubusercontent.com/bc900691c79de79d97a381b76fb0da682805f99364206122d1ed5c83ef39f99e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f63656e746f732d7072652d72656c656173655f5253535f4d41584d494e2e706e67" /> | <img src="https://camo.githubusercontent.com/bb00f71292018a4d0aaa7f7d93eaca4c135f331b4a7200dafbd78e820ca9f2a9/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f63656e746f732d7072652d72656c656173655f5253535f4d41584d494e2e706e67" />
| RSS | <img src="https://camo.githubusercontent.com/013ab5979940b5ae61b54ef10650de8d3b25c1acc5ccf77ae9b54018b998c5fc/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f63656e746f732d7072652d72656c656173655f5253532e706e67" /> | <img src="https://camo.githubusercontent.com/259d462cd1027c8f7991596e887df9c40d6f620f580f88c527c31ea96a11e8a5/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f63656e746f732d7072652d72656c656173655f5253532e706e67" />
| USS | <img src="https://camo.githubusercontent.com/76edeac56583210fc221c9e0cc13686caac16c8d1a2c3709fa4ba2ec705c976f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f63656e746f732d7072652d72656c656173655f5553532e706e67" /> | <img src="https://camo.githubusercontent.com/1f9f4e5c90017732794d40ccd99e06fa2bdf5d60dbe22af3f1780a86f4bb2410/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f63656e746f732d7072652d72656c656173655f5553532e706e67" />
| VMS | <img src="https://camo.githubusercontent.com/e10dbe8d9058438be176fdc4314bf32fcf4420fbd5b7338c8c40a515a02e8e94/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f63656e746f732d7072652d72656c656173655f564d532e706e67" /> | <img src="https://camo.githubusercontent.com/9ce47bb656e5b6635d80bd57ead010ddcdfd700876da211108a98c451de75bb3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f63656e746f732d7072652d72656c656173655f564d532e706e67" />

</details>

### CentOS agent

**Logs and configuration**
[ossec_Test_stress_B4443_centos_2023-10-09.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_centos/logs/ossec_Test_stress_B4443_centos_2023-10-09.zip)

**CSV**
[monitor-agent-Test_stress_B4443_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_centos/data/monitor-agent-Test_stress_B4443_centos-pre-release.csv)
[Test_stress_B4443_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_centos/data/Test_stress_B4443_centos_agentd_state.csv)

### Ubuntu agent

**Logs and configuration**
[ossec_Test_stress_B4443_ubuntu_2023-10-09.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_ubuntu/logs/ossec_Test_stress_B4443_ubuntu_2023-10-09.zip)

**CSV**
[monitor-agent-Test_stress_B4443_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_ubuntu/data/monitor-agent-Test_stress_B4443_ubuntu-pre-release.csv)
[Test_stress_B4443_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4443-3600m/B4443_agent_ubuntu/data/Test_stress_B4443_ubuntu_agentd_state.csv)

**Comment by mauromalara** [comment]
## Update

### Ubuntu Agent

In this case (VMS) `wazuh-modulesd` increase its memory usage:

| `4.5.3` | `4.6.0`|
|--|--
| <img src="https://camo.githubusercontent.com/5059e81a433d807774d76d3bc4d3d81b6c5d640e15d473ea97d38e984a3cfd77/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343432312d333630306d2f42343432315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343432315f7562756e74752d7072652d72656c656173655f564d532e706e67" /> | <img src="https://camo.githubusercontent.com/cdbf40163b6aaa5295cc8088378bc122a57c6b7ad673ff978b6f4b10b345a5fb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343434332d333630306d2f42343434335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343434335f7562756e74752d7072652d72656c656173655f564d532e706e67" />

**Comment by mauromalara** [comment]
# Update

## Windows Agent

In Windows is already reported here: https://github.com/wazuh/wazuh/issues/19310

**Comment by jotacarma90** [comment]
## Conclusions

Hi team, I have been analyzing the different stress tests and the conclusion is this memory increase related to syscheck:
| Versión   | syscheck on -- rootcheck on | syscheck off -- rootcheck on | syscheck on -- rootcheck off | syscheck off -- rootcheck off |
|-----------|-----------------------------|-----------------------------|----------------------------|----------------------------|
| 4.6.0 RC1 | 400                         | 125                         | 350                        | 50                        |
| 4.6.0 beta1 | 400                       | 125                         | 350                        | 50                        |
| 4.5.2 RC1 | 350                         | 100                         | 280                        | 30                        |

As you can see, there is a stable memory increase. This increase is due to the introduction of the new FIM functionality with the rsync and dbsync libraries, because during the development some libraries for the new c++ code of syscheck had to be included.

Here we made a comparison after implementing the changes, you can see a very similar increase to the one found in the current graphs:
https://github.com/wazuh/wazuh/issues/10223#issuecomment-1156421435
![image](https://github.com/wazuh/wazuh/assets/60003131/8b75b734-902d-43aa-89c6-3aa6b129631b)
