### ISSUE TITLE
Release 4.6.0 - RC 1 - AWS Module testing

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#19598]
# AWS module testing

## Modules tests information
|                                      |                                                |
|--------------------------------------|------------------------------------------------|
| **Main module tests issue**          | #19590                                          |
| **Version**                          | 4.6.0                                          |
| **Release candidate #**              | RC 1 |
| **Tag**                              | [v4.6.0-rc1](https://github.com/wazuh/wazuh/tree/v4.6.0-rc1)   |
| **Previous modules tests issue**     | #18879                                         |

## Test report procedure

All test results must have one the following statuses: 
|                 |                                                                         |
|-----------------|-------------------------------------------------------------------------|
| :green_circle: | The test passed successfully.                                            |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

The resulting logs for the tests must be included in the status report so it can be used by the auditors to dig deeper into any possible failures and details.

## Test results
| Test | Result | Issue ref. |
|------|--------|------------|
| AWS Integration tests | :green_circle: | - |
| Test Security Lake as a subscriber integration | :green_circle:  | - |
| Test using ossec.conf in an agent with Python 3.7 | :green_circle:   | - |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario 
- [ ] @davidjiglesias

**Comment by fdalmaup** [comment]
# AWS Integration tests
[HTML Report](https://github.com/wazuh/wazuh/files/12870510/HTML.Report.zip)

<details><summary>Test output</summary>

    /wazuh-qa/tests/integration# pytest --disable-warnings test_aws/ --html=report.html
    ================================================================ test session starts ================================================================
    platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
    rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
    plugins: testinfra-5.0.0, html-3.1.1, metadata-3.0.0
    collected 198 items                                                                                                                                 
    
    test_aws/test_basic.py ................                                                                                                       [  8%]
    test_aws/test_discard_regex.py .................                                                                                              [ 16%]
    test_aws/test_log_groups.py ..                                                                                                                [ 17%]
    test_aws/test_only_logs_after.py .............................................x.                                                                          [ 41%]
    test_aws/test_parser.py ..........................                                                                                                        [ 54%]
    test_aws/test_path.py ..........................................                                                                                          [ 75%]
    test_aws/test_path_suffix.py .........                                                                                                                    [ 80%]
    test_aws/test_regions.py ........................                                                                                                         [ 92%]
    test_aws/test_remove_from_bucket.py ...sss.........                                                                                                       [100%]
    
    ---------------------------------------------- generated html file: file:///wazuh-qa/tests/integration/report.html ----------------------------------------------
    ==================================================== 194 passed, 3 skipped, 1 xfailed in 4077.07s (1:07:57) =====================================================

</details>


| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_aws/test_basic.py | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_discard_regex.py | 17 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_log_groups.py | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_only_logs_after.py | 46 | 0 | 0 | 1 | 0 | https://github.com/wazuh/wazuh/issues/16303  | 🟡  |
| test_aws/test_parser.py | 26 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_path.py | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_path_suffix.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_regions.py | 24 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_remove_from_bucket.py | 12 | 0 | 3 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
# Test Security Lake as a subscriber integration 🟢

- Set up the Security Lake Service with a Subscriber in order to fetch notifications from an SQS Queue and get logs in parquet format from related buckets.

<details><summary>ossec.conf</summary>

    <wodle name="aws-s3">
        <disabled>no</disabled>
        <interval>1h</interval>
        <run_on_start>yes</run_on_start>
        <subscriber type="security_lake">
            <sqs_name>AmazonSecurityLake-f38b8aff-Main-Queue</sqs_name>
            <external_id>wazuh-external-id</external_id>
            <iam_role_arn>arn:aws:iam::xxx:role/AmazonSecurityLake-f38b8aff-Main-Queue</iam_role_arn>
        </subscriber>
    </wodle>

</details>

<details><summary>ossec.log</summary>

    2023/10/11 10:55:30 wazuh-modulesd:aws-s3[4978] wm_aws.c:62 at wm_aws_main(): INFO: Module AWS started
    2023/10/11 10:55:30 wazuh-modulesd:aws-s3[4978] wm_aws.c:84 at wm_aws_main(): INFO: Starting fetching of logs.
    2023/10/11 10:55:30 wazuh-modulesd:aws-s3[4978] wm_aws.c:196 at wm_aws_main(): INFO: Executing Subscriber fetch: (Type and SQS: security_lake AmazonSecurityLake-f38b8aff-Main-Queue)
    2023/10/11 10:55:30 wazuh-modulesd:aws-s3[4978] wm_aws.c:724 at wm_aws_run_subscriber(): DEBUG: Create argument list
    2023/10/11 10:55:30 wazuh-modulesd:aws-s3[4978] wm_aws.c:790 at wm_aws_run_subscriber(): DEBUG: Launching Security Lake Subscriber Command: wodles/aws/aws-s3 --subscriber security_lake --queue AmazonSecurityLake-f38b8aff-Main-Queue --external_id wazuh-external-id --iam_role_arn arn:aws:iam::xxx:role/AmazonSecurityLake-f38b8aff-Main-Queue --debug 2
    2023/10/11 11:01:35 wazuh-modulesd:aws-s3[4978] wm_aws.c:831 at wm_aws_run_subscriber(): DEBUG: Subscriber: security_lake AmazonSecurityLake-f38b8aff-Main-Queue  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
    DEBUG: Created Config object using profile: 'default' configuration
    DEBUG: The SQS queue is: https://queue.amazonaws.com/123456789123/AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Retries parameters found in user profile. Using profile 'default' retries configuration
    DEBUG: Created Config object using profile: 'default' configuration
    DEBUG: Retrieving messages from: AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Processing file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/84c58df585c90a316aa01165b261a05d.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
    DEBUG: Found 2 events in file aws/LAMBDA_EXECUTION/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/84c58df585c90a316aa01165b261a05d.gz.parquet
    DEBUG: 2 events sent to Analysisd
    DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Processing file aws/ROUTE53/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/3ec58df5c9b989f64d705ec081903c62.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
    DEBUG: Found 2 events in file aws/ROUTE53/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/3ec58df5c9b989f64d705ec081903c62.gz.parquet
    DEBUG: 2 events sent to Analysisd
    DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/aec58dfecea1d0bf7968af5c40cfc2a8.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
    DEBUG: Found 21 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=123456789123/eventDay=20231010/aec58dfecea1d0bf7968af5c40cfc2a8.gz.parquet
    DEBUG: 21 events sent to Analysisd
    DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
    ...
    DEBUG: Processing file aws/ROUTE53/1.0/region=us-east-1/accountId=123456789123/eventDay=20231011/72c58f7862bac39cc189bf67577237e6.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
    DEBUG: Found 70 events in file aws/ROUTE53/1.0/region=us-east-1/accountId=123456789123/eventDay=20231011/72c58f7862bac39cc189bf67577237e6.gz.parquet
    DEBUG: 70 events sent to Analysisd
    DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Processing file aws/S3_DATA/1.0/region=us-east-1/accountId=123456789123/eventDay=20231011/76c58f81ad7943fb1be95e76f2b1884a.gz.parquet in aws-security-data-lake-us-east-1-gbxqof17tcdrj8qkkk1rbchg3rhig0
    DEBUG: Found 76 events in file aws/S3_DATA/1.0/region=us-east-1/accountId=123456789123/eventDay=20231011/76c58f81ad7943fb1be95e76f2b1884a.gz.parquet
    DEBUG: 76 events sent to Analysisd
    DEBUG: Message deleted from: AmazonSecurityLake-f38b8aff-Main-Queue
    DEBUG: Retrieving messages from: AmazonSecurityLake-f38b8aff-Main-Queue
    2023/10/11 11:02:04 wazuh-modulesd:aws-s3[4978] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.
    2023/10/11 11:02:04 wazuh-modulesd:aws-s3[4978] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2023/10/11 11:55:30

</details>

## Conclusions

The module worked as expected, the sum of the events described in the logs corresponds to the ones sent to Analysisd.

**Comment by fdalmaup** [comment]
# Test using ossec.conf in an agent with Python 3.7 :green_circle: 

Deploy an Ubuntu 18 agent and install the required dependencies described in the official Wazuh documentation, then run the module adding the following configuration to the `ossec.conf` using Python 3.7:

<details><summary>ossec.conf</summary>

    <wodle name="aws-s3">
        <disabled>no</disabled>
        <remove_from_bucket>no</remove_from_bucket>
        <interval>1h</interval>
        <run_on_start>yes</run_on_start>
        <skip_on_error>no</skip_on_error>
    
        <bucket type="cloudtrail">
            <name>wazuh-aws-wodle-cloudtrail</name>
            <aws_profile>dev</aws_profile>
            <only_logs_after>2022-JAN-01</only_logs_after>
        </bucket>
    
        <bucket type="config">
            <name>wazuh-aws-wodle-config</name>
            <aws_profile>dev</aws_profile>
            <only_logs_after>2022-NOV-01</only_logs_after>
        </bucket>
    
        <bucket type="guardduty">
            <name>wazuh-aws-wodle-guardduty-native</name>
            <aws_profile>dev</aws_profile>
            <only_logs_after>2022-AUG-01</only_logs_after>
        </bucket>
    
        <bucket type="custom">
            <aws_profile>dev</aws_profile>
            <name>wazuh-aws-wodle-kms</name>
            <only_logs_after>2022-JAN-01</only_logs_after>
        </bucket>
    
        <bucket type="custom">
            <aws_profile>dev</aws_profile>
            <name>wazuh-aws-wodle-trusted-advisor</name>
            <only_logs_after>2022-JAN-01</only_logs_after>
        </bucket>
    
        <service type="cloudwatchlogs">
            <aws_profile>dev</aws_profile>
            <aws_log_groups>4_6_test</aws_log_groups>
            <only_logs_after>2023-JAN-01</only_logs_after>
            <regions>us-east-1</regions>
        </service>
    </wodle>

</details>

<details><summary>ossec.log</summary>

    2023/10/11 14:30:03 wazuh-modulesd:aws-s3[24982] wm_aws.c:62 at wm_aws_main(): INFO: Module AWS started
    2023/10/11 14:30:03 wazuh-modulesd:aws-s3[24982] wm_aws.c:84 at wm_aws_main(): INFO: Starting fetching of logs.
    2023/10/11 14:30:03 wazuh-modulesd:aws-s3[24982] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-cloudtrail, Type: cloudtrail, Profile: dev)
    2023/10/11 14:30:03 wazuh-modulesd:aws-s3[24982] wm_aws.c:376 at wm_aws_run_s3(): DEBUG: Create argument list
    2023/10/11 14:30:03 wazuh-modulesd:aws-s3[24982] wm_aws.c:491 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-cloudtrail --aws_profile dev --only_logs_after 2022-JAN-01 --type cloudtrail --debug 2
    2023/10/11 14:30:08 wazuh-modulesd:aws-s3[24982] wm_aws.c:531 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Working on 123123456789 - us-west-1
    DEBUG: +++ Marker: AWSLogs/123123456789/CloudTrail/us-west-1/2022/01/01
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/01/25/123123456789_CloudTrail_us-west-1_20220125T0000Z_HASDOtJxgfdNInHa.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/02/11/123123456789_CloudTrail_us-west-1_20220211T0000Z_HASDOtJxgfdNInHa.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/03/30/123123456789_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/03/30/123123456789_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdNInHa.json.zip
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/03/30/123123456789_CloudTrail_us-west-1_20220330T0000Z_HASDoKlxgfdkdIOa.json.txt
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2022/03/30/123123456789_CloudTrail_us-west-1_20220330T0002Z_HASDoKlxgfdNInHa.json.zip
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2023/04/06/123123456789_CloudTrail_us-west-1_20230406T0002Z_HASDoKlxgfdNInHa.json
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2023/04/06/123123456789_CloudTrail_us-west-1_20230406T0002Z_HASDoKlxgfdNInHb.json
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2023/04/11/123123456789_CloudTrail_us-west-1_20230411T1755Z_2CqtXDyI0zFiYm1J.json
    DEBUG: ++ Found new log: AWSLogs/123123456789/CloudTrail/us-west-1/2023/09/06/123123456789_CloudTrail_us-west-1_20230906T1755Z_2CqtXDyI0zFiYm1J.json
    DEBUG: +++ DB Maintenance
    DEBUG: +++ Working on 789123123456 - us-west-1
    DEBUG: +++ Marker: AWSLogs/789123123456/CloudTrail/us-west-1/2022/01/01
    DEBUG: +++ No logs to process in bucket: 789123123456/us-west-1
    DEBUG: +++ DB Maintenance
    DEBUG: +++ Working on 123456789123 - us-west-1
    DEBUG: +++ Marker: AWSLogs/123456789123/CloudTrail/us-west-1/2022/01/01
    DEBUG: ++ Found new log: AWSLogs/123456789123/CloudTrail/us-west-1/2023/01/25/123123456789_CloudTrail_us-west-1_20211223T0000Z_HASDOtJxxxxxxxxx.json.gz
    DEBUG: +++ DB Maintenance
    
    2023/10/11 14:30:08 wazuh-modulesd:aws-s3[24982] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-config, Type: config, Profile: dev)
    2023/10/11 14:30:08 wazuh-modulesd:aws-s3[24982] wm_aws.c:376 at wm_aws_run_s3(): DEBUG: Create argument list
    2023/10/11 14:30:08 wazuh-modulesd:aws-s3[24982] wm_aws.c:491 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-config --aws_profile dev --only_logs_after 2022-NOV-01 --type config --debug 2
    2023/10/11 14:30:11 sca[24982] wm_sca.c:271 at wm_sca_send_alert(): DEBUG: Sending event: {"type":"check","id":998270266,"policy":"CIS Ubuntu Linux 18.04 LTS Benchmark v2.0.1","policy_id":"cis_ubuntu18-04","check":{"id":18550,"title":"Ensure updates, patches, and additional security software are installed.","description":"Periodically patches are released for included software either due to security flaws or to include additional functionality.","rationale":"Newer patches may contain security enhancements that would not be available through the latest full update. As a result, it is recommended that the latest software patches be used to take advantage of the latest functionality. As with any software installation, organizations need to determine if a given update meets their requirements and verify the compatibility and supportability of any additional software against the update revision that is selected.","remediation":"Use your package manager to update all packages on the system according to site policy. Notes: Site policy may mandate a testing period before install onto production systems for available updates.","compliance":{"cis":"1.9","cis_csc":"3.4,3.5","pci_dss":"5.2","nist_800_53":"AU.6,SI.4","gpg_13":"4.2","gdpr_IV":"35.7.d","hipaa":"164.312.b","tsc":"A1.2"},"rules":["c:apt -s upgrade -> r:^The following packages will be upgraded"],"condition":"none","command":"apt -s upgrade","result":"failed"}}
    2023/10/11 14:30:11 wazuh-modulesd:aws-s3[24982] wm_aws.c:531 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Working on 123123456789 - us-east-1
    DEBUG: +++ Marker: AWSLogs/123123456789/Config/us-east-1/2022/11/1
    DEBUG: ++ Found new log: AWSLogs/123123456789/Config/us-east-1/2022/11/1/123123456789_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220216T004303Z_20220216T025123Z_1.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/Config/us-east-1/2022/11/22/123123456789_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220216T004303Z_20220216T025123Z_1.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/Config/us-east-1/2022/2/11/123123456789_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220211T004303Z_20220211T025123Z_1.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/Config/us-east-1/2022/2/16/123123456789_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220216T004303Z_20220216T025123Z_1.json.gz
    DEBUG: ++ Found new log: AWSLogs/123123456789/Config/us-east-1/2022/8/22/123123456789_Config_us-east-1_ConfigHistory_AWS Config ResourceCompliance_20220216T004303Z_20220216T025123Z_1.json.gz
    DEBUG: +++ DB Maintenance
    
    2023/10/11 14:30:11 wazuh-modulesd:aws-s3[24982] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-guardduty-native, Type: guardduty, Profile: dev)
    2023/10/11 14:30:11 wazuh-modulesd:aws-s3[24982] wm_aws.c:376 at wm_aws_run_s3(): DEBUG: Create argument list
    2023/10/11 14:30:11 wazuh-modulesd:aws-s3[24982] wm_aws.c:491 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-guardduty-native --aws_profile dev --only_logs_after 2022-AUG-01 --type guardduty --debug 2
    2023/10/11 14:30:18 wazuh-modulesd:aws-s3[24982] wm_aws.c:531 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Working on 123456789123 - us-east-1
    DEBUG: +++ Marker: AWSLogs/123456789123/GuardDuty/us-east-1/2022/08/01
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/09d41cb2-dc23-3ec6-a59d-b77625c6ddd8.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/2642d6b9-c0c0-30e4-a7cb-ce1983c53e1b.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/388203f4-4d6b-3be7-8790-843978860f98.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/4b6c54fe-fb15-357a-b7d9-20099bea7999.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/4bc69a8c-53b8-30bd-9f1d-11bf615b5cbd.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/566c9fde-c2bf-34eb-b1f0-dc37f0665c6f.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/a54d242d-0200-3fcc-a321-3ff67887047d.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/ba106b79-a888-3dab-bc58-f929860d3776.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/c65747f2-c625-3972-b9b6-222172434149.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/09/20/d995abe7-81df-397d-8a0a-b1033a4058af.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/10/21/4ca2d459-4b27-34f9-9f96-0689041ab45b.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/10/21/b67b5cbd-cf37-3c91-97ad-2ab367d01eab.jsonl.gz
    DEBUG: ++ Found new log: AWSLogs/123456789123/GuardDuty/us-east-1/2022/10/21/ec7b0b8c-5ec8-32ec-8e77-c738515b4f6f.jsonl.gz
    DEBUG: +++ DB Maintenance
    
    2023/10/11 14:30:18 wazuh-modulesd:aws-s3[24982] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-kms, Type: custom, Profile: dev)
    2023/10/11 14:30:18 wazuh-modulesd:aws-s3[24982] wm_aws.c:376 at wm_aws_run_s3(): DEBUG: Create argument list
    2023/10/11 14:30:18 wazuh-modulesd:aws-s3[24982] wm_aws.c:491 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-kms --aws_profile dev --only_logs_after 2022-JAN-01 --type custom --debug 2
    2023/10/11 14:30:24 wazuh-modulesd:aws-s3[24982] wm_aws.c:531 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Table does not exist; create
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Found new log: 2022/01/15/12/firehose_kms-1-2022-01-15-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Found new log: 2022/01/16/12/firehose_kms-1-2022-01-16-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Found new log: 2022/01/17/12/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: ++ Found new log: 2023/01/25/firehose_kms-1-2022-01-17-12-27-26-756d81b8-7031-4a07-a50c-db292e6db64b
    DEBUG: +++ No logs to process in bucket: wazuh-aws-wodle-kms
    DEBUG: +++ No logs to process in bucket: wazuh-aws-wodle-kms
    DEBUG: +++ No logs to process in bucket: wazuh-aws-wodle-kms
    DEBUG: +++ No logs to process in bucket: wazuh-aws-wodle-kms
    DEBUG: +++ DB Maintenance
    
    2023/10/11 14:30:24 wazuh-modulesd:aws-s3[24982] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuh-aws-wodle-trusted-advisor, Type: custom, Profile: dev)
    2023/10/11 14:30:24 wazuh-modulesd:aws-s3[24982] wm_aws.c:376 at wm_aws_run_s3(): DEBUG: Create argument list
    2023/10/11 14:30:24 wazuh-modulesd:aws-s3[24982] wm_aws.c:491 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket wazuh-aws-wodle-trusted-advisor --aws_profile dev --only_logs_after 2022-JAN-01 --type custom --debug 2
    2023/10/11 14:30:26 wazuh-modulesd:aws-s3[24982] wm_aws.c:531 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: +++ Marker: 2022/01/01
    DEBUG: ++ Found new log: 2022/01/16/12/firehose_trustedadvisor-1-2022-01-16-12.gz
    DEBUG: ++ Found new log: 2022/01/17/12/firehose_trustedadvisor-1-2022-01-17-12.gz
    DEBUG: +++ DB Maintenance
    
    2023/10/11 14:30:26 wazuh-modulesd:aws-s3[24982] wm_aws.c:171 at wm_aws_main(): INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: dev)
    2023/10/11 14:30:26 wazuh-modulesd:aws-s3[24982] wm_aws.c:555 at wm_aws_run_service(): DEBUG: Create argument list
    2023/10/11 14:30:26 wazuh-modulesd:aws-s3[24982] wm_aws.c:659 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile dev --only_logs_after 2023-JAN-01 --regions us-east-1 --aws_log_groups 4_6_test --debug 2
    2023/10/11 14:30:29 wazuh-modulesd:aws-s3[24982] wm_aws.c:700 at wm_aws_run_service(): DEBUG: Service: cloudwatchlogs  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
    DEBUG: +++ Getting alerts from "us-east-1" region.
    DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
    DEBUG: only logs: 1672531200000
    DEBUG: +++ Table does not exist; create
    DEBUG: Getting log streams for "4_6_test" log group
    DEBUG: Found "test_stream" log stream in 4_6_test
    DEBUG: Getting data from DB for log stream "test_stream" in log group "4_6_test"
    DEBUG: Token: "None", start_time: "None", end_time: "None"
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_6_test" using token "None", start_time "1672531200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: The message is "Test log 1 - 2023-10-11 1697034277"
    DEBUG: The message is "{     "networkInterfaces": [         {             "networkInterfaceId": "eni-networkInterfaceId",             "subnetId": "subnet-subnetId",             "vpcId": "vpc-vpcId",             "privateDnsName": "ip-0-0-0-0.ec2.internal",             "privateIpAddress": "0.0.0.0",             "privateIpAddresses": [                 {                     "privateDnsName": "ip-0-0-0-0.ec2.internal",                     "privateIpAddress": "0.0.0.0"                 }             ],             "publicDnsName": "ec2-0-0-0-0.compute-1.amazonaws.com",             "publicIp": "0.0.0.0",             "ipv6Addresses": [],             "securityGroups": [                 {                     "groupName": "groupName0",                     "groupId": "sg-groupId0"                 },                 {                     "groupName": "groupName1",                     "groupId": "sg-groupID1"                 }             ]         }     ] }"
    DEBUG: +++ Sent 2 events to Analysisd
    DEBUG: Getting CloudWatch logs from log stream "test_stream" in log group "4_6_test" using token "f/37845130705427473799337751980731932628024887641841139712/s", start_time "1672531200000" and end_time "None"
    DEBUG: +++ Sending events to Analysisd...
    DEBUG: +++ There are no new events in the "4_6_test" group
    DEBUG: Saving data for log group "4_6_test" and log stream "test_stream".
    DEBUG: The saved values are "{'token': 'f/37845130705438624169885428644998897094653155370011164671/s', 'start_time': 1672531200000, 'end_time': 1697034353270}"
    DEBUG: Purging the BD
    DEBUG: Getting log streams for "4_6_test" log group
    DEBUG: Found "test_stream" log stream in 4_6_test
    DEBUG: committing changes and closing the DB
    2023/10/11 14:30:29 wazuh-modulesd:aws-s3[24982] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.
    2023/10/11 14:30:29 wazuh-modulesd:aws-s3[24982] wm_aws.c:80 at wm_aws_main(): DEBUG: Sleeping until: 2023/10/11 15:30:03


</details>


## Conclusions
The module worked as expected. Events were sent to Analysisd.

**Comment by damarisg** [comment]
LGTM!
