### ISSUE TITLE
Test: Maild

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1959]
# Maild test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## Send reports

- [x] Configure the mail alerts and receive an alert in your email.

## Configuration

- [x] Check the typical settings such as `email_reply_to`.

## Filters

- [x] Check filters: `email_maxperhour`, `level`, `group`, etc...

**Comment by adri9valle** [comment]
MAILD TEST
***

- Configure the mail alerts and receive an alert in your email. (**Success**)

- Check the typical settings such as *email_reply_to*.(**Failed**)

- Email_alert_level(**Failed**) Always works fine except when the manager is reset, for example, although the minimum level rule was 10, the manager always send `Rule: 502 fired (level 3) -> "Ossec server started."`

- Check filters:
  - Email_maxperhour.(**Failed**) Always sends one less than the number configured, for example, if the *email_maxpehour* is 1, then never send an email.
  - Level(**Success**)
  - Group(**Success**)
  - Rule_id(**Success**)
  - Format(**Success**)

**Comment by chemamartinez** [comment]
Hi @adri9valle,

About the failed checks:

- Check the typical settings such as email_reply_to.(Failed)

Could you open an issue describing the failed settings on this test?

- Email_alert_level(Failed)

There are some alerts with the option `alert_by_email`, this option makes that rule to be triggered always without consider the alert level defined. This is the case of rule 502:

```
<rule id="502" level="3">
    <if_sid>500</if_sid>
    <options>alert_by_email</options>
    <match>Ossec started</match>
    <description>Ossec server started.</description>
    <group>pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
  </rule>
```

- Email_maxperhour.(Failed)

This is why the last email of that count is sent at the end of the hour, containing the remaining alerts accumulated after the counter reaches `email_maxperhour - 1`, as it is explained in the documentation:

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#email-maxperhour

**Comment by adri9valle** [comment]
Hi @chemamartinez

You're right!

The email_reply_to functionality works fine. Also, email_maxperhour, I have tried again this test and as you said when the hour past send all the alerts in a single mail.

Thanks!
