### ISSUE TITLE
Release 4.6.0 - RC 1 - External Integrations modules

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#19590]
The following issue aims to perform all the required testing for the current release candidate to ensure the modules (AWS, GCP, Azure, DockerListener and Shuffle) works as expected, report the results, and open new issues for any encountered errors.

## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #19471     |
| **Version**                      | 4.6.0 |
| **Release candidate #**          | RC 1   |
| **Tag**                          | [v4.6.0-rc1](https://github.com/wazuh/wazuh/tree/v4.6.0-rc1) |
| **Previous modules tests issue** | https://github.com/wazuh/wazuh/issues/18879  |

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                                        |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | The test passed successfully. 										    |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

The resulting logs for the tests must be included in the status report so it can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

| **Module**      | **Testing issue** | **Status**  |**Notes**|
|-----------------|-------------------|-------------|---------|
| AWS             | #19598  | :green_circle: Completed  |  |
| Azure           | #19599  |  :green_circle: Completed   |  |
| GCP             | #19601  |   :green_circle: Completed   |   |
| Docker Listener | #19597  | :green_circle: Completed  |  |
| Shuffle | #19602 | :yellow_circle: Completed |  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [ ] @davidjiglesias 
- [x] @fdalmaup

**Comment by damarisg** [comment]
LGTM!

> Note: Each number created per module must contain a conclusion.
