### ISSUE TITLE
new feature on wazuh v2.1 doesnt find field account name and account domain

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh#196]
hey guys!
How are you?
I install wazuh and just doesnt have anymore the fields: account_name and account_domain
I need help with this... 

Tks

**Comment by albertomn86** [comment]
Hi @borbelyau,

How did you upgrade the ruleset? Have you used the 2.1 branch or the stable branch? Take in account that the 2.1 branch is a developing branch.

We renamed these fields to **account.name** and **account.domain** in the developing branch.

Regards.

**Comment by borbelyau** [comment]
I installed from scratch, did not upgrade, just installed version 2.1... but i found the error ... the problem is that they installed windows in portuguese ... and from what I saw the string changes!

I think, that I have to change or put some new fields in Portuguese on logstash... 
or have another way to do that?

**Comment by borbelyau** [comment]
yes I upgrade the ruleset...

**Comment by albertomn86** [comment]
Hi,

Windows decoders are designed to parse logs in English language. If you have installed Windows in other language, some decoders could not work.

Sometimes is a good idea to install Windows in English and later install a language pack. By this way the logs will be generated in English.

However, you can modify the decoders to extract information in other language.

Regards.

**Comment by borbelyau** [comment]
Tks
