### ISSUE TITLE
Windows Agent Disk Pattern has changed in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19605]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc1 | Wazuh Agent | Agent | Packages | Windows |

Testing [ALL-EXCEPT-SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/19541)
Windows Agent Disk Plot has changed dramatically comparing 4.6.0-rc1 to 4.5.3-rc3

4.6.0-rc1
![image](https://github.com/wazuh/wazuh/assets/125690423/9e7b7c80-9835-4f38-b87b-ebfc43b25f24)

4.6.0-beta1
![image](https://github.com/wazuh/wazuh/assets/125690423/6ef45670-75de-4371-9840-9387cc495f88)

4.6.0-alpha1

![image](https://github.com/wazuh/wazuh/assets/125690423/486dbccb-3bbb-4bd1-b796-f5199a409244)

4.5.3-rc3
![image](https://github.com/wazuh/wazuh/assets/125690423/c2dfd0bf-4a50-48fc-babd-c0361e7d75c2)

Further research should be performed.

**Comment by vikman90** [comment]
Ignoring this issue as the peak in 4.6.0 is lower than in 4.5.3.

**Comment by LucioDonda** [comment]
While still searching causes for this change, I can say that the disk Pattern change is actually a good thing:
* All 4.6.0 graphs shown a lower peak than the previous ones.
* While on the full load this usage isn't increasing.
* There's a slight increase after full load.
