### ISSUE TITLE
Build failure when installing from sources with ZeroMQ enabled

### ISSUE THREAD

**Issue by bbkrr** [wazuh/wazuh#19600]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3 | Server | Manager | Sources | Ubuntu 20.04 |

gcc version:
```
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
```

g++ version:
```
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
```

When installing from sources to enable ZeroMQ, I get an error.

Steps followed:

```
apt-get update
apt-get install python gcc g++ make libc6-dev curl policycoreutils automake autoconf libtool libssl-dev

curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 && ./bootstrap --no-system-curl && make -j$(nproc) && make install
cd .. && rm -rf cmake-*

curl -Ls https://github.com/wazuh/wazuh/archive/v4.5.3.tar.gz | tar zx

cd wazuh-4.5.3/src

make clean-internals
make deps
make TARGET=server USE_ZEROMQ=yes
```

This gave me the following error:

<img width="675" alt="Screenshot 2023-10-11 at 17 13 43" src="https://github.com/wazuh/wazuh/assets/85162559/8f95c058-286f-4232-bb5d-55e9a800b6ca">

---

So, I installed `libczmq-dev`.

And then ran the following commands:

```
cd wazuh-4.5.3/src

make clean-internals
make clean-deps
make clean

make deps
make TARGET=server USE_ZEROMQ=yes
```

Now, I am getting this new error,

![Screenshot 2023-10-11 at 16 06 27](https://github.com/wazuh/wazuh/assets/85162559/7ceef27e-27d4-44d1-97b0-c21409f06de0)

---

Building from sources with ZeroMQ enabled was working for `v4.3.5`.
Has something changed or I am missing some steps ?

---

**Comment by pereyra-m** [comment]
Hello @bbkrr !

I'd like to make sure when this issue was introduced.
I've made some local tests, but it'd be helpful if you do the same with different versions: I'm able to build the last v4.3.x successfully, but starting from v4.4.x I have the same error message.

This could be related to this development 
https://github.com/wazuh/wazuh/pull/13608

The addition of a new file with the name `limits.h` might be interfering with the compilation because the required constants can't be found.

As a workaround, please try the following:
- Perform a full clean of the compilation
- Rename `src/analysisd/limits.c` to `src/analysisd/w_limits.c`  
- Rename `src/analysisd/limits.h` to `src/analysisd/w_limits.h`  
- Replace `#include "limits.h"` by `#include "w_limits.h"` at `src/analysisd/state.c`
- Replace `#include "limits.h"` by `#include "w_limits.h"` at `src/analysisd/analysisd.c`
- Compile again

Regards.

**Comment by pereyra-m** [comment]
Hello again @bbkrr !

I missed a detail, sorry.

In the new `w_limits.c` file, also replace `#include "limits.h"` by `#include "w_limits.h"`.

I was able to compile Wazuh successfully this way.

Regards.

**Comment by pereyra-m** [comment]
## Update

As @Nicogp points out, this should be fixed in v4.7.0 by #16346

**Comment by bbkrr** [comment]
Hi @pereyra-m,

Thank you for your assistance. It worked, and I can see the logs in the ZeroMQ socket. I have a question regarding the following issue: even though we are receiving the logs in the ZeroMQ socket, why does this problem occur?

```
2023/10/13 04:29:24 wazuh-analysisd: ERROR: Unable to bind the ZeroMQ Socket: tcp://*:5050.
E: 23-10-13 04:29:25 [6697]dangling 'PUB' socket created at analysisd/output/zeromq.c:61
```

The same issue has been mentioned at https://github.com/wazuh/wazuh/issues/11391#issuecomment-1010210782

Furthermore, I've noticed that in ZeroMQ, we only receive alert logs and not other events present in archives.json. 

We had a discussion about this on https://github.com/wazuh/wazuh/issues/13280, and it was determined to be added as an enhancement. Do you think this could also be considered in the upcoming release?

Regards.

**Comment by pereyra-m** [comment]
Hello @bbkrr !

Glad to know the compilation worked.
But to keep the repository organized, this issue should only be about the compilation error:
- All the details related to the feature request correspond to #13280
- If the error message is the same than #11391, you could re-open it or create a new one

Regards.

**Comment by Dwordcito** [comment]
@bbkrr  Thanks for being part of the community! 

We hope we have helped you, your collaboration with the community is very important, if you have another question/problem we hope for a new issue!

**Comment by Nicogp** [comment]
Due to the changes related to issue #20168, this compilation failure with the ZeroMQ flag could happen again.

**Comment by jnasselle** [comment]
@Nicogp is right
```
    CC analysisd/output/zeromq.o
In file included from /usr/include/czmq_library.h:23,
                 from /usr/include/czmq.h:37,
                 from analysisd/output/zeromq.h:17,
                 from analysisd/analysisd.c:51:
/usr/include/czmq_prelude.h:408:5: error: #error "Cannot compile: must change definition of 'byte'."
  408 | #   error "Cannot compile: must change definition of 'byte'."
      |     ^~~~~
/usr/include/czmq_prelude.h:411:6: error: #error "Cannot compile: must change definition of 'dbyte'."
  411 | #    error "Cannot compile: must change definition of 'dbyte'."
      |      ^~~~~
/usr/include/czmq_prelude.h:414:6: error: #error "Cannot compile: must change definition of 'qbyte'."
  414 | #    error "Cannot compile: must change definition of 'qbyte'."
      |      ^~~~~
    CC analysisd/alerts/log.o
    CC analysisd/cdb/cdb.o
    CC analysisd/cdb/cdb_hash.o
make[1]: *** [Makefile:2247: analysisd/analysisd-live.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /usr/include/czmq_library.h:23,
                 from /usr/include/czmq.h:37,
                 from analysisd/output/zeromq.h:17,
                 from analysisd/output/zeromq.c:13:
/usr/include/czmq_prelude.h:408:5: error: #error "Cannot compile: must change definition of 'byte'."
  408 | #   error "Cannot compile: must change definition of 'byte'."
      |     ^~~~~
/usr/include/czmq_prelude.h:411:6: error: #error "Cannot compile: must change definition of 'dbyte'."
  411 | #    error "Cannot compile: must change definition of 'dbyte'."
      |      ^~~~~
/usr/include/czmq_prelude.h:414:6: error: #error "Cannot compile: must change definition of 'qbyte'."
  414 | #    error "Cannot compile: must change definition of 'qbyte'."
      |      ^~~~~
```

**Comment by mulderr** [comment]
Still on master as of today:

```
In file included from /usr/include/czmq_library.h:23,
                 from /usr/include/czmq.h:37,
                 from analysisd/output/zeromq.h:17,
                 from analysisd/analysisd.c:51:
/usr/include/czmq_prelude.h:408:5: error: #error "Cannot compile: must change definition of 'byte'."
  408 | #   error "Cannot compile: must change definition of 'byte'."
      |     ^~~~~
/usr/include/czmq_prelude.h:411:6: error: #error "Cannot compile: must change definition of 'dbyte'."
  411 | #    error "Cannot compile: must change definition of 'dbyte'."
      |      ^~~~~
/usr/include/czmq_prelude.h:414:6: error: #error "Cannot compile: must change definition of 'qbyte'."
  414 | #    error "Cannot compile: must change definition of 'qbyte'."
      |      ^~~~~
```

Applying the workaround described above by @pereyra-m makes it compile successfully. In that case, why call it a workaround and not a fix? Are there reasons the file *must* be named `limits.h`?

**Comment by bbkrr** [comment]
@vikman90 

Any specific reason on why this issue is not planned for a fix ? Is it working in the new version or we don't want this change ?
