### ISSUE TITLE
Requesting Wazuh to be able to send syslog via TCP instead of UDP.

### ISSUE THREAD

**Issue by Alexustandsbj** [wazuh/wazuh#19635]
|Wazuh version| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

**Comment by davidcr01** [comment]
Hello. Currently, Wazuh supports sending `syslog` logs via TCP and UDP protocols. As specified in the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/syslog.html)

```
<protocol> is the protocol used to listen for incoming syslog
 messages from endpoints. The allowed values are either tcp or udp.
```

Besides, in the `ossec.conf` [reference](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#protocol), it is specified that:

```
It is now possible to configure both UDP and TCP protocols to work 
simultaneously in the secure connections, this can be achieved by writing in 
the same configuration block the accepted protocols separated with a comma. 
For syslog connections, multiple protocols support require multiple 
configuration blocks since only one protocol per block is allowed.
```

So please, change the `ossec.conf` file and specified the desired protocol for sending `syslog` logs.

Hope it helps.
