### ISSUE TITLE
Test: SCAP

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1965]
# SCAP test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## OpenSCAP

- [x] Launch a scan on Ubuntu 16.
XCCDF and OVAL. Check the generated alerts. (1)
- [x] Launch a scan on Fedora 24.
XCCDF and OVAL. Check the generated alerts. (1)
- [x] Launch a scan on CentOS 7.
XCCDF and OVAL. Check the generated alerts. (1)
- [x] Launch a scan on Debian.
XCCDF and oval. Check the generated alerts. (1)
- [x] Set several content sections and launch a scan. (1)
- [x] Set an non-existent benchmark, incorrect path and wrong type. **Must fail** (1)

(1) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/wodle-openscap.html#content

## CIS-CAT

- [x] Launch a scan (XCCDF) and check the generated alerts. (2)
- [x] Set CIS-CAT path, Java path and benchmark path with absolute and relative paths. (2)
- [x] Launch a scan with incorrect parameters (incorrect benchmarks). **Must fail** (2)
- [x] Launch a scan with incorrect parameters (incorrect CIS-CAT path and JAVA path). **Must fail** (2)
- [x] Launch a scan with incorrect parameters (incorrect profile). **Must fail** (2)
- [x] Set several content sections and launch a scan. (2)
- [x] Check that main results of the scans are saved into the table `ciscat_results` of the DB of each agent.

(2) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/wodle-ciscat.html

**Comment by chemamartinez** [comment]
Please, test again the failed check with the packages with revision 3725.

**Comment by Cerv1** [comment]
Hi team,

I've tested again the failed check and it's fixed.

```
# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.1"
REVISION="3725"
DATE="Mon Dec  3 10:38:11 CET 2018"
TYPE="server"

# sqlite3 /var/ossec/queue/db/000.db "select * from ciscat_results;"
1|2058253322|2018-12-03T10:43:39.473+01:00|CIS Ubuntu Linux 16.04 LTS Benchmark|xccdf_org.cisecurity.benchmarks_profile_Level_2_-_Server|102|81|0|36|1|55
```

Thanks @chemamartinez !
