### ISSUE TITLE
debian12  installed  wazuh-manager , it can‘t  scan  itself  vulnerability

### ISSUE THREAD

**Issue by yysf1949** [wazuh/wazuh#19681]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
|null|wazuh-modulesd:vulnerability-detector|Manager 4.3.11|Packages|debian12|

2023/10/16 17:29:26 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
2023/10/16 17:29:26 wazuh-modulesd:vulnerability-detector: INFO: (5435): The analysis can not be launched because there are no target agents.
2023/10/16 17:29:26 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.

**Comment by MiguelazoDS** [comment]
Hi @yysf1949, 

The support for Debian 12 is intended to be released in 4.6.0. Here you can see the details https://github.com/wazuh/wazuh/issues/18516

4.3.11 is an old version. 

You can check here also the new features added to each version https://documentation.wazuh.com/current/release-notes/index.html

**Comment by yysf1949** [comment]
Easy to answer, when will the update be pushed 4.6.0?

**Comment by yysf1949** [comment]
> Hi @yysf1949,
> 
> The support for Debian 12 is intended to be released in 4.6.0. Here you can see the details #18516
> 
> 4.3.11 is an old version.
> 
> You can check here also the new features added to each version https://documentation.wazuh.com/current/release-notes/index.html

thank you.
