### ISSUE TITLE
Test: Upgrade

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1969]
# Upgrade test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3721 | branch |

## RPM (Linux)

- [x] Install new version.
- [x] Check_files.
- [x] Check that the databases are purged.
- [x] Check that the service are restarted.

## DEB (Linux)

- [x] Install new version.
- [x] Check_files.
- [x] Check that the databases are purged.
- [x] Check that the service are restarted.

## macOS

- [x] Install new version.
- [x] Check_files.
- [x] Check that the service are restarted.

## Solaris (Intel)

- [ ] Install new version.
- [ ] Check_files.
- [ ] Check that the service are restarted.

## Solaris (SPARC)

- [ ] Install new version.
- [ ] Check_files.
- [ ] Check that the service are restarted.

## HP-UX

- [ ] Install new version.
- [ ] Check_files.
- [ ] Check that the service are restarted.

## AIX

- [ ] Install new version.
- [ ] Check_files.
- [ ] Check that the service are restarted.

## Sources

- [x] Check the upgrade building the source code.
- [x] Check that the databases are purged.

## Remote upgrades (WPK)

- [x] Upgrade an agent remotely (Linux and Windows) and check the _upgrade.log_  (Use UDP and TCP).
- [x] Upgrade an agent with a custom WPK.
- [x] Upgrade an agent without CA verification.
- [x] Downgrade an agent (option `-F`).

**Comment by juan70** [comment]
# Manager upgrade from packages
## RPM
### CentOS 7
**=> OK.**
### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**
## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

**Comment by juan70** [comment]
# Agent upgrade from packages
## RPM
### CentOS 7
**=> OK.**
### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**

## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

**Comment by juan70** [comment]
# Manager upgrade from sources
## RPM
### CentOS 7
**=> OK.**
### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**

## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

**Comment by juan70** [comment]
# Agent upgrade from sources
## RPM
### CentOS 7
**=> OK.**
### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**

## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

**Comment by juan70** [comment]
# Agent upgrade with WPK
## RPM
### CentOS 7
**=> OK.**

### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**

## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

## Windows
**=> OK.**

**Comment by juan70** [comment]
# Agent upgrade with WPK
## RPM
### CentOS 7
**=> OK.**

### Fedora 29
**=> OK.**
### OpenSuse 15.0
**=> OK.**

## DEB
### Debian 9
**=> OK.**
### Ubuntu 18.04
**=> OK.**

## Windows
**=> OK.**
