### ISSUE TITLE
Expecting disconnection reason to be returned in `/agents`

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#19721]
|Wazuh version|
|---|
| 4.7.0 | 

## Description
During the test of 4.7.0, we found a problem in the issue https://github.com/wazuh/wazuh-dashboard-plugins/issues/5051 . The Dashboard is expecting a parameter  `status_code` to be returned for the agents in the `/agents` endpoint. It should contain a number according to the [status](https://github.com/wazuh/wazuh/blob/v4.7.0-alpha1/src/wazuh_db/wdb.h#L55-L61).

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Added the `status_code` field to the agent model, spec, and updated unit and integration tests.
