### ISSUE TITLE
full_log not found when using ZeroMQ

### ISSUE THREAD

**Issue by bbkrr** [wazuh/wazuh#19733]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5 | Server | Manager | Sources | Ubuntu 20.04 |

I'm using ZeroMQ to subscribe to Wazuh events. To ensure data consistency, I conducted a comparison between the logs received via ZeroMQ and those stored in the archives.json file.

While checking the logs in both ZeroMQ and archives.json, I observed some differences. 

In a few instances, the 'full_log' field was absent in ZeroMQ but present in the archives.json file. I'm wondering if there are specific conditions or settings that could cause these variations in ZeroMQ?

I will attach the logs received from both ZeroMQ and archives.json.

[zmq_archives_comparison_sample.txt](https://github.com/wazuh/wazuh/files/13038450/zmq_archives_comparison_sample.txt)

**Comment by nmkoremblum** [comment]
Hi @bbkrr,

Where exactly is ZeroMQ taking the events from?

**Comment by bbkrr** [comment]
Hi @nmkoremblum,

It is taking the events from Windows server 2016.

**Comment by nmkoremblum** [comment]
Hi again,

Wazuh does indeed pre-process, modify, and adapt the original Windows events given its original format for various reasons, including normalization, enrichment, and such. This can lead to variations in the logs you see between different sources, such as ZeroMQ and the `archives.json` file.

Wazuh performs these modifications to standardize the data and make it more suitable for analysis, detection, and alerting. As a result, you may encounter differences in the 'full_log' field or maybe other event details.

If you have specific concerns about the differences you've observed, I recommend checking the Wazuh documentation and configuration settings to understand the pre-processing and enrichment steps that are applied to the events. This will help you gain a deeper understanding of why variations occur and how to work with the data effectively.

Feel free to reach out if you have more questions or if you need further assistance in configuring Wazuh to meet your specific requirements.

**Comment by cborla** [comment]
LGTM
