### ISSUE TITLE
Fix type hint error shown in AWS wodle when using Python3.7 as interpreter

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#19745]
| Affected integration |
|---|
| AWS|

## Description

As explained in #19039 and fixed in #19332. during the enhancement of the AWS module a type hint was introduced causing an error during the execution of the AWS module when using the minimum Python version (3.7) as an interpreter, it was first thought that the fix was introduced in 4.8.0 and the fix was released for said version. However, during the [Release 4.7.0 - Alpha 1 - External Integration Modules #19698](https://github.com/wazuh/wazuh/issues/19698), it was found that the tested version still has the bug. 

This issue tends to perform the same fix as #19039 but for version 4.7.0 to ensure AWS wodle works as expected for Python 3.7

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by GGP1** [comment]
## Update

Fixed list type hints and an error type that did not exist in python 3.7.
