### ISSUE TITLE
Vulnerabilitie Scanner does not detect Libre Office Vulnerabilities 

### ISSUE THREAD

**Issue by CharonEJ** [wazuh/wazuh#19755]
Hi there,

I am experiencing some issues with the vulnerability scanner. I tested the vulnerability scanner with older software to check if it would find known vulnerabilities. Unfortunately, it does not detect any vulnerabilities in LibreOffice, regardless of the version. For example, in version 6.0.0.1, no vulnerabilities are detected.

Does anyone else have the same problem or any thoughts on this?

[ossecConfOnMyServer.txt](https://github.com/wazuh/wazuh/files/13047380/ossecConfOnMyServer.txt)
[ossecOnMyAgent.txt](https://github.com/wazuh/wazuh/files/13047381/ossecOnMyAgent.txt)

**Comment by MiguelazoDS** [comment]
Hi @CharonEJ, 

Is your agent running Windows? please share the package inventory information. Let's check if the name and vendor in the inventory match the cpe in the NVD.

**Comment by CharonEJ** [comment]
Yes, my agent is running on Windows. I downloaded the inventory data report. Is this the right one?
[wazuh-agent-inventory-001-1697837246.pdf](https://github.com/wazuh/wazuh/files/13058777/wazuh-agent-inventory-001-1697837246.pdf)

**Comment by MiguelazoDS** [comment]
Hi, 

This must be related to a missing translation, take a look at this section of the documentation 
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html

According to the NVD (the feed for Windows) the name and product for Libre Office is "libreoffice"

https://nvd.nist.gov/products/cpe/search/results?keyword=cpe:2.3:a:libreoffice:libreoffice:*:*:*:*:*:*:*:*&status=FINAL,DEPRECATED&orderBy=CPEURI&namingFormat=2.3

**Comment by Dwordcito** [comment]
Thank you for being part of the community, we closed the issue due to inactivity, please if you have any other questions regarding this topic, reopen the issue!

Thank you very much, the community's contribution is important.
