### ISSUE TITLE
Add New 'cti-url' Configuration Option to Manager

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#19780]
## Description

This issue aims to enhance the configuration options of the Wazuh Manager by introducing a new setting under the 'global' tag. The new configuration option is named 'cti-url' and is intended to specify the default URL for CTI data. By adding this configuration, users will have greater flexibility in customizing the CTI source URL to fit their specific requirements.

### User Stories

- As a system administrator, I want to provide a default 'cti-url' in the Manager configuration, which can be customized as needed.
- As a developer, I will implement the 'cti-url' configuration option to enable users to set their preferred CTI data source.

### Tasks

1. Update Configuration Parser:
   - Modify the configuration parser in the Manager to recognize and handle the 'cti-url' configuration option.

!!! **Don't update the default configuration** !!!

### Definition of Done

- The 'cti-url' configuration option is successfully implemented in the Manager.
- The default 'cti-url' is set to 'cti.wazuh.com'.
- Code changes are reviewed, tested, and integrated into the main codebase.
- Quality assurance checks confirm the functionality of the 'cti-url' configuration.
- Test with localhost:55000/manager/configuration endpoint.

**Comment by MiguelazoDS** [comment]
# Comments

`localhost:55000/manager/configuration` does not get active configuration, only settings present in the `ossec.conf` file.
