### ISSUE TITLE
Remove duplicated get_component_stats function from api.agent_controller

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#19805]
|Wazuh version|Component|
|---|---|
| master | API |

## Description
The get_component_stats function is duplicated.
https://github.com/wazuh/wazuh/blob/dd354194d55f4ad116631cadf5399808a8034613/api/api/controllers/agent_controller.py#L869
https://github.com/wazuh/wazuh/blob/dd354194d55f4ad116631cadf5399808a8034613/api/api/controllers/agent_controller.py#L905

The first one must be removed.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Already done in 
- https://github.com/wazuh/wazuh/issues/18594
