### ISSUE TITLE
Check Wazuh compatibility with new version macOS Ventura 13.5 (AMD64)

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#19804]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the new found version of macOS Ventura 13.5 amd64 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/17387
Instance request issue: https://github.com/wazuh/internal-devel-requests/issues/49

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) instalations.
- [x] O.S. reporting in the interface.
- [x] WPK upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Schedule mode.
- [ ] ~SCA: Policy support.~
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by ncvicchi** [comment]
LGTM!
