### ISSUE TITLE
Vulnerability detector - Issabel

### ISSUE THREAD

**Issue by pabloforato** [wazuh/wazuh#19806]
Hello everyone,

I'm new to Wazuh and I'm trying to configure the vulnerability detector to run on an Issabel PBX system. I've followed the steps outlined in the documentation provided in this link: 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html

The output from my system is as follows:

   "os": {
      "major": "7",
      "name": "Issabel PBX"
   }

With this information, I edited my ossec.conf as follows:

    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os allow="Issabel PBX">7</os>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>

The log shows:

    2023/10/23 13:27:54 wazuh-modulesd: ERROR: Invalid OS entered in vulnerability-detector: Issabel PBX
    2023/10/23 13:27:54 wazuh-modulesd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.

Is there any way to run the vulnerability detector on Issabel systems?

Thanks.

**Comment by MiguelazoDS** [comment]
Hi @pabloforato, 

I'm not aware of what is that OS, but if it is a redhat distro based it should work using 
```
...
  <os allow="Issabel PBX-7">7</os>
...
```

**Comment by Dwordcito** [comment]
Thank you for being part of the community, if the problem arises again please reopen the issue, for now given the inactivity I will close the issue.
