### ISSUE TITLE
Add Enhancement to MS Graph Ruleset

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#19820]
|Related issue|
|---|
|#16312|

|Linked Solution|
|---|
|#19676|

## Description

As a part of #17021 a set of Microsoft Graph related rules were added to Wazuh. This PR seeks to significantly enhance this initial ruleset, which was lacking the MITRE integration and state-awareness of the new ruleset. This state-awareness involves, for instance, decreasing the resulting level of an alert if the log shows the alert to already be resolved, or if it is associated with expected admin activity (like with a scheduled vulnerability scan).

Better support has also been added for the custom/manual categorization of alerts, which will override automatic detection ratings. The levels of alerts have also been redone in a manner that should result in fewer instances of "crying wolf" and more accurately reflects the internal meaning of the rule levels within Wazuh.

## Logs/Alerts example

![MicrosoftTeams-image (8)](https://github.com/wazuh/wazuh/assets/89558443/1226efaf-64b3-46df-963e-fdff88d6be5d)

![MicrosoftTeams-image (9)](https://github.com/wazuh/wazuh/assets/89558443/9ceb49a0-fd25-42da-bfe7-9803db349e32)

![MicrosoftTeams-image (10)](https://github.com/wazuh/wazuh/assets/89558443/a7d191cc-7219-4762-9a9e-dc26d58633bf)

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
- [ ] Source installation
- [ ] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language

- Decoder/Rule tests
  - [ ] runtests.py executed without errors

cc: @S-Bryce

**Comment by IsExec** [comment]
## Review Update - 15/02/2024

**There is no ruleset test file. Review will be based on:**

- Rule level
- MITRE ATTACK
- Compliance
- And manual test of selected rules

**Comment by Johnng007** [comment]
21-02-2024

  - <details><summary>Rule Level
     🟢  </summary>

            - :             
            - Rule level          🟢
    </details>

  - <details><summary>Mitre Technique
     🟢  </summary>

            - :             
            - Mitre          🟢
    </details>

**Comment by Johnng007** [comment]
**22-02-2024**
General Review Completed

  - <details><summary>Rule Level
     🟢  </summary>

            - :             
            - Rule level          🟢
    </details>

  - <details><summary>Mitre Technique
     🟢  </summary>

            - :             
            - Mitre          🟢
    </details>

**Comment by ooniagbi** [comment]
Reviewed rule 99500 - 99560

**Comment by ooniagbi** [comment]
Merged to 4.8.2
