### ISSUE TITLE
Release 4.6.0 - RC 2 - External Integration Modules 

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#19846]
The following issue aims to perform all the required testing for the current release candidate to ensure the modules (AWS, GCP, Azure, DockerListener and Shuffle) works as expected, report the results, and open new issues for any encountered errors.

## Modules tests information

|||
|----------------------------------|------ |
| **Main release candidate issue** | #19833      |
| **Version**                      | 4.6.0 |
| **Release candidate #**          | RC 2   |
| **Tag**                          |  [v4.6.0-rc2](https://github.com/wazuh/wazuh/tree/v4.6.0-rc2)          |
| **Previous modules tests issue** |  https://github.com/wazuh/wazuh/issues/19590  |

## Test report procedure

All test results must have one the following statuses: 
|                                  |                                                        |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | The test passed successfully. 										    |
| :yellow_circle: | The test passed but some enhancements need to be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

The resulting logs for the tests must be included in the status report so it can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

| **Module**      |  **Status**  |**Notes**|
|-----------------|-------------|---------|
| AWS             | 🟡    | #19730  |
| Azure           | ⚪   |  _Skipped_  |
| GCP             | ⚪   | _Skipped_  |
| Docker Listener | ⚪   | _Skipped_  |
| Shuffle | ⚪  |  _Skipped_  |

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.
- [ ] @wazuh/qa-management 
- [x] @fdalmaup

**Comment by EduLeon12** [comment]
# AWS Module Testing 

## Test results
| Test | Result | Issue ref. |
|------|--------|------------|
| AWS Integration tests | | - |
| Test Security Lake as a subscriber integration |  | - |
| Test using ossec.conf in an agent with Python 3.7 |    | - |

## AWS Integration tests 

<details><summary>Test output</summary>

```python

```

</details>


| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_aws/test_basic.py | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_discard_regex.py | 17 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_log_groups.py | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_only_logs_after.py | 46 | 0 | 0 | 1 | 0 | https://github.com/wazuh/wazuh/issues/16303  | 🟡  |
| test_aws/test_parser.py | 25 | 0 | 0 | 0 | 1 | https://github.com/wazuh/wazuh/issues/19730 | 🔴  |
| test_aws/test_path.py | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_path_suffix.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_regions.py | 24 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_remove_from_bucket.py | 12 | 0 | 3 | 0 | 0 |  | :green_circle: |


## Test Security Lake as a subscriber integration 

- Set up the Security Lake Service with a Subscriber in order to fetch notifications from an SQS Queue and get logs in parquet format from related buckets.

<details><summary>ossec.conf</summary>

```xml
    <wodle name="aws-s3">
        <disabled>no</disabled>
        <interval>1h</interval>
        <run_on_start>yes</run_on_start>
        <subscriber type="security_lake">
            <sqs_name>AmazonSecurityLake-f38b8aff-Main-Queue</sqs_name>
            <external_id>wazuh-external-id</external_id>
            <iam_role_arn>arn:aws:iam::xxx:role/AmazonSecurityLake-f38b8aff-Main-Queue</iam_role_arn>
        </subscriber>
    </wodle>
```

</details>

<details><summary>ossec.log</summary>

```console


```

</details>

## Conclusions

The module worked as expected.

## Test using ossec.conf in an agent with Python 3.7 

Run the module using the following `ossec.conf` configuration:

<details><summary>Python version</summary>

```console
root@27e70bb041e6:/var/ossec# python3.7 --version
Python 3.7.5
root@27e70bb041e6:/var/ossec# which python3.7
/usr/bin/python3.7
root@27e70bb041e6:/var/ossec# head -1 wodles/aws/aws-s3
#!/usr/bin/env python3.7

```

</details>

<details><summary>ossec.conf</summary>

```xml

<wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>

    <bucket type="cloudtrail">
        <name>wazuh-aws-wodle-cloudtrail</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="config">
        <name>wazuh-aws-wodle-config</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2022-NOV-01</only_logs_after>
    </bucket>

    <bucket type="guardduty">
        <name>wazuh-aws-wodle-guardduty-native</name>
        <aws_profile>dev</aws_profile>
        <only_logs_after>2022-AUG-01</only_logs_after>
    </bucket>

    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-kms</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <bucket type="custom">
        <aws_profile>dev</aws_profile>
        <name>wazuh-aws-wodle-trusted-advisor</name>
        <only_logs_after>2022-JAN-01</only_logs_after>
    </bucket>

    <service type="cloudwatchlogs">
        <aws_profile>dev</aws_profile>
        <aws_log_groups>4_6_test</aws_log_groups>
        <only_logs_after>2023-JAN-01</only_logs_after>
        <regions>us-east-1</regions>
    </service>
</wodle>

```

</details>


<details>
    <summary>ossec.log output</summary>

```console

```

</details>

### Conclusions

**Comment by fdalmaup** [comment]
LGTM!

**Comment by damarisg** [comment]
LGTM!
