### ISSUE TITLE
Engine - Implement GitHub Actions Workflow for Verifying Asset Functionality

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#19863]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Latest | Wazuh Engine | Manager | GitHub Actions | any |

**Description:**

To ensure the integrity and functionality of our assets, especially decoders and rules, we aim to implement a GitHub Actions workflow. This workflow will verify the correct functioning of the assets by comparing the generated outputs against expected outputs.

**Task Details:**

1. **Python Script Creation:**
   - Traverse the integrations directory.
   - Access the "test" folder of each integration.
   - Extract input files following the naming convention: `assetname_input.extension` (e.g., `powershell-operational_input.xml`).
   - Run these inputs in the test engine ("engine-test") to generate an output.
   - Compare the generated output with the corresponding expected file, named as `assetname_expected.extension` (e.g., `powershell-operational_expected.json`).

2. **Error Handling:**
   - If an asset's generated output does not match its expected output, list the asset as a failed test.
   - Once all assets have been tested, if any have failed, return an error code.

3. **Execution Script Modification:**
   - Update the execution script ("run") to execute this new "health test" in addition to the existing integration tests.

4. **Environment Configuration Script Modification:**
   - Adjust the script that sets up the environment to load the necessary integrations and policies for the test session.

5. **GitHub Actions Workflow:**
   - The workflow should be triggered on every `push` event.
   - If any asset tests fail, the workflow should list the failed assets.
   - For detailed examination of differences, local testing using tools like `diff` is recommended.

**Comment by NahuFigueroa97** [comment]
Blocked for https://github.com/wazuh/wazuh/issues/19761
