### ISSUE TITLE
How do I use wazuh-agent to recognize web root directory?

### ISSUE THREAD

**Issue by Stanley3** [wazuh/wazuh#1989]
I want use Wazuh to check webshell, so the first thing I think is to recognize web root directory. How should I do that?

**Comment by TJOSERAFAEL** [comment]
Hi @Stanley3,

if you want to detect file changes, additions you can use syscheck to monitor your folder. 
For example in your **ossec.conf** file find the `syscheck` section :

```
<syscheck>
    <directories check_all="yes" realtime="yes">/your_webshell_path</directories>
</syscheck>
```

Restart your agent. When the first scan finishes, you will start to see files that have been added, modified or deleted.

The complete **syscheck** configuration guide can be found here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html

If you have any questions please don't hesitate to ask.

Best regards.
