### ISSUE TITLE
Lower fluctuation density of different parameters observed during stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19914]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | Wazuh component | Agent | Packages | CentOS, Ubuntu, Windows |

Testing [VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/19890)

Lower fluctuation density of FD, PSS, RSS, USS, and VMS observed during stress test in CentOS, Ubuntu and Windows.
In Windows, the fluctuation density of CPU, Disk, Disk_read, Handles, and Read_Ops has also been affected.

Between sub-versions of 4.6.0, the same fluctuation pattern is observed.

Example Centos:

FD
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/dce7e247-3013-4cdc-b4f4-70ff6f4ccd35)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/1fa89d46-0280-4f6e-bb96-9a32c8eafe8f)
 
PSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/ad860e64-ecbd-48d0-882b-8d845855a33d)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/28d0d400-2165-49ac-a0cd-2570928679b1)

RSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/927f099f-d0a8-49df-bd3f-e228be2c4e9d)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/d57f987b-1377-497d-b9d4-55d4073e8d11)

USS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/257d9068-8b60-481b-88a3-1ca2d15156fe)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/281d3a76-a780-46b4-9856-8d88a585ae81)

Windows:
CPU
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/dfc64c81-dadf-422f-9663-00a6bed9f856)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/42d0c0a3-8bf9-4fa1-9ffa-659ca6e3a4a4)

Disk
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/802c565b-c4c2-494e-905d-268e9669d5fb)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/2e43978b-bec1-4ec3-9bf5-85fad0eff21f)

Disk_read
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/eb1a2b49-e77a-4cc7-a917-c84629cf9f85)
4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/dbfcaa0d-d137-4765-a51c-6018a3f1e9c0)

**Comment by JorgeMarinoDev** [comment]
#### Manager Plots ####

**FD, PSS, RSS, USS**

The CSV data of both tests were compared and double checked.
There are not less fluctuation density in the data, but it is a plot generation artifact.
For some reason, you can check in 4.5.2 plots, that the z-order of some daemon's lines, are hiding the rest of them.
The 4.5.2 stress test are not available in jenkins anymore, to check the plot generation pipeline steps.
Disregard. Just a plot generation artifact with bad z-ordering.

#### Windows Plots ####

WIP
