### ISSUE TITLE
Increase of number of fluctuations of agentd in CentOS CPU in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19913]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | Wazuh component | Agent | Packages | CentOS |

Testing [Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/19890), there is an increase of number of fluctuations of agentd in CentOS CPU

4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19890
![image](https://github.com/wazuh/wazuh/assets/125690423/c384536c-53fe-46bb-bcb2-cb77dbc0efc3)

4.6.0-rc1 https://github.com/wazuh/wazuh/issues/19552
![image](https://github.com/wazuh/wazuh/assets/125690423/0c975170-cc33-4789-8036-12fb2e2d746a)

4.5.3-rc2 https://github.com/wazuh/wazuh/issues/19365
![image](https://github.com/wazuh/wazuh/assets/125690423/0bc8aa51-555d-4fd9-8ed0-c2e6855c0d81)

**Comment by nmkoremblum** [comment]
Hi team,

After analyzing the issue, there doesn't appear to be any significant cause for concern. The agent continues to function correctly. It's worth noting that the new version does show an increased frequency of CPU usage, but the actual usage remains considerably lower (2% compared to the previous 10%). No errors related to this behavior were identified in the logs, and there were no differences found in the configuration. Additionally, a similar issue was previously reported, I invite you to take a look at #19938 for further insights.

Best regards

**Comment by cborla** [comment]
Also, measuring it in an indirect way we see that the % of CPU usage is higher for version 4.5.3 than for version 4.6.0.

| 4.5.3 | 4.6.0 |
|------|------|
| ![image](https://github.com/wazuh/wazuh/assets/41765669/b4aec00c-1910-4856-9152-1975531a80cb) | ![image](https://github.com/wazuh/wazuh/assets/41765669/2a4bc57f-f4d9-413e-b711-6a6f2bd74f12) |
