### ISSUE TITLE
Changes observed in the pattern and amplitude of resource usage fluctuations in the Windows agent during the stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#19917]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | Wazuh component | Agent | Packages | Windows |

Testing [Footprint Metrics - SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/19891)

RSS, USS, VMS fluctuations have increased showing different pattern compared to 4.5.3-rc3. compared to 4.6.0-rc1 there are fewer visible peaks

RSS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/d75f60d7-b709-4719-b3db-7365ff0300ed)

4.6.0-rc1 https://github.com/wazuh/wazuh/issues/19550
![image](https://github.com/wazuh/wazuh/assets/125690423/b197cc8a-f6cb-416f-9004-97ce0094476f)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/066ecb70-34fb-4fd0-9230-05b50960e10e)

USS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/ac8d7d69-8bd9-4074-8088-5976d3d8da9e)

4.6.0-rc1 https://github.com/wazuh/wazuh/issues/19550
![image](https://github.com/wazuh/wazuh/assets/125690423/179fdccd-68e6-4715-83ff-e8fc45d2a669)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/db1a328a-d4f3-49eb-8be0-c7f285261b7c)

VMS
4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19891
![image](https://github.com/wazuh/wazuh/assets/125690423/9da412e0-b6f5-44a0-ad93-a0f4a7eb8d0c)

4.6.0-rc1 https://github.com/wazuh/wazuh/issues/19550
![image](https://github.com/wazuh/wazuh/assets/125690423/c7027362-6925-4d04-b1a2-7017e0381ec5)

4.5.3-rc3 https://github.com/wazuh/wazuh/issues/19500
![image](https://github.com/wazuh/wazuh/assets/125690423/d7264f48-3881-4447-8fd0-4064405ee925)

**Comment by QU3B1M** [comment]
## Same behavior found on `wazuh-manager`

In the analysis of https://github.com/wazuh/wazuh/issues/19899, we can see that _PSS, RSS, RSS_MAXMIN, USS_ show a decrease in this case on `modulesd`. It's required to validate if both anomalies are related, or we need to create a new issue to track this behavior on `wazuh-manager`.

PSS
- 4.6.0-rc2 ![image](https://github.com/wazuh/wazuh/assets/44633633/71b49c64-89ae-4c35-ba2c-a150b5779b08)
- 4.6.0-rc1 ![image](https://github.com/wazuh/wazuh/assets/44633633/31cb7175-ade0-4585-9434-5407af8e37f6)

RSS
- 4.6.0-rc2 ![image](https://github.com/wazuh/wazuh/assets/44633633/2985b6e5-3733-4bcb-8861-3b86a059bc6e)
- 4.6.0-rc1 ![image](https://github.com/wazuh/wazuh/assets/44633633/b502bad1-5de9-4367-a140-a7324edbc4ab)

RSS_MAXMIN
- 4.6.0-rc2 ![image](https://github.com/wazuh/wazuh/assets/44633633/3a36ddd1-5870-41a8-a588-2b76ee1170f2)
- 4.6.0-rc1 ![image](https://github.com/wazuh/wazuh/assets/44633633/3ee54e2e-14c4-4a25-9d3c-d859a8031d57)

USS
- 4.6.0-rc2 ![image](https://github.com/wazuh/wazuh/assets/44633633/bfd88d27-60ca-41d4-bad0-7c28674617af)
- 4.6.0-rc1  ![image](https://github.com/wazuh/wazuh/assets/44633633/57f44bbd-fd12-4d2f-bb9b-ec3b4b78df95)

**Comment by Dwordcito** [comment]
Closed based on what was described by the development team.
