### ISSUE TITLE
Error setting limit for file descriptors in HP-UX

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1991]
## Bug report

**OS**
_HP-UX 11.31_

**Wazuh version**
_3.7.0_

**Wazuh API version**
_x.y.z_

**Install type**
_agent_

**Install method**
_packages/sources_

**Log sample**

```
2018/11/28 04:31:40 ossec-logcollector: ERROR: Could not set resource limit for file descriptors to 0: Invalid argument (22)
```

Bug description
----------------
Error setting limit for file descriptors for logcollector.

**Comment by vikman90** [comment]
Possibly fixed here: #2030
