### ISSUE TITLE
Changes observed in the pattern of `AgentD_Number_of_events_buffered` in the Windows agent on Footprint

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#19926]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | Wazuh component | Agent | Packages | Windows |

Observed during the analysis of [Footprint Metrics - LOGCOLLECTOR,SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/19891)

_AgentD_Number_of_events_buffered_ showing different pattern compared to 4.5.3-rc3. compared to 4.6.0-rc1, the plot shows a less stable _Number of events buffered_

- `4.6.0-rc2` https://github.com/wazuh/wazuh/issues/19899
![image](https://github.com/wazuh/wazuh/assets/44633633/cdea1cf5-87cf-4c28-b9e2-d577ff44c8dc)

- `4.6.0-rc1` https://github.com/wazuh/wazuh/issues/19548
![image](https://github.com/wazuh/wazuh/assets/44633633/2f29b015-5503-4206-926b-f6df158e3e9a)

- `4.5.3-rc3` https://github.com/wazuh/wazuh/issues/19497
![image](https://github.com/wazuh/wazuh/assets/44633633/798aa814-8691-4320-b02f-308e6f250c7e)

**Comment by nmkoremblum** [comment]
It surprises me that a change in the number of events buffered is reported but not the actual amount of generated events which is about half as in previous tests. This could come along with the fact that syscheck events are now limited by configuration which is not the case in previous tests, where now syscheck is limited to 60 EPS. So, tests are not comparable and I think that is the reason why the pattern of buffered events has changed.

**Comment by Dwordcito** [comment]
Closed based on what was described by the development team.
