### ISSUE TITLE
Check Wazuh-Manager compatibility with new version Ubuntu 23.10

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#19921]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Ubuntu 23.10 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/19559

Important: This new release includes the new 6.5 Linux kernel that brings [many new features](https://discourse.ubuntu.com/t/mantic-minotaur-release-notes/35534#:~:text=Intel%E2%80%99s%20%E2%80%9CTopology%20Aware,support%20new%20hardware.).

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Schedule and Real-time
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture (Eventchannel for Windows and ULS for macOS).

**Comment by lchico** [comment]
Do some research on a higher-priority task.

**Comment by lchico** [comment]
# Testing

<details>
<summary>Ubuntu 23.10 manager</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e87d7d21-ced8-47fc-a17f-6b4862bea975">
</details>

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/6d866907-3b96-46fd-983c-68cde3a8bb34">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/b5bdb162-15d5-432e-a034-b80108244d6a">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/49fb13fd-ec39-4a73-8164-bb7ae2637bbf">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/43093d48-cc27-47f9-a064-072c4093a8b8">
</details>

## :green_circle: Upgrade using WPK
WPK was downloaded from [here](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/wpk-list.html) and [this](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html#run-the-upgrade) procedure was follow (from step 2)

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/b114cffb-d993-419d-b7e9-a37724147dcf">
</details>


## :yellow_circle: SCA support
No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/4470b214-7de4-405f-b1e6-0a1348959083">

</details>
<details>
<summary>Agent log:</summary>

  ```
1458856:2023/11/13 22:43:11 sca[294279] wm_sca.c:152 at wm_sca_main(): INFO: Module started.
1458857-2023/11/13 22:43:11 wazuh-modulesd[294279] main.c:95 at main(): DEBUG: Created new thread for the 'sca' module.
1458859:2023/11/13 22:43:11 sca[294279] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
1458860:2023/11/13 22:43:11 sca[294279] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'
1458869-2023/11/13 22:43:11 sca[294279] wm_sca.c:329 at wm_sca_start(): INFO: Starting Security Configuration Assessment scan.
  ```
</details>

<details>
<summary>Inventory:</summary>

 <img src="https://github.com/wazuh/wazuh/assets/21695385/4ea1381e-67e3-447f-a7ef-ece9709aac7d">
</details>

## :green_circle: Vulnerability detector


<details>
<summary>Manager Config</summary>

  ```
    <!-- Ubuntu OS vulnerabilities -->
    <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <os allow="Ubuntu-23">jammy</os>
      <update_interval>10s</update_interval>
    </provider>

  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/37864204-3274-4dbc-8f77-9b7f2550a217">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/9ef8c06c-10d0-43c1-82e4-4f40a1cd754e">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/184c80b1-4325-481c-8de2-2a45d28427db">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/a6e51fef-d343-4604-9cdb-79446df57f20">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/164b1392-0c5a-4c9e-aa67-98468625f79e">
</details>

**Comment by ed108206** [comment]
LGTM

**Comment by ncvicchi** [comment]
LGTM!
