### ISSUE TITLE
Release 4.6.0 - Revision 1 - Release Candidate RC2 - Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19935]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #19833                                         |
| **Main footprint metrics issue #** | #19834                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | RC2                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.6.0-rc2 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/186/

:warning: This test corresponds to a c5a.large instance type and does not match the rest of the stress tests instance types, changes may appears in the Plots

- This issue is the same as: https://github.com/wazuh/wazuh-jenkins/issues/5882

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/Test_stress_Vagrant_B186_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/plots/Test_stress_Vagrant_B186_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B186_manager_2023-10-29.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/logs/ossec_Test_stress_Vagrant_B186_manager_2023-10-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B186_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/data/monitor-manager-Test_stress_Vagrant_B186_manager-pre-release.csv)
[Test_stress_Vagrant_B186_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/data/Test_stress_Vagrant_B186_manager_analysisd_events.csv)
[Test_stress_Vagrant_B186_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/data/Test_stress_Vagrant_B186_manager_analysisd_state.csv)
[Test_stress_Vagrant_B186_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_manager_centos/data/Test_stress_Vagrant_B186_manager_remoted_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/Test_stress_Vagrant_B186_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/Test_stress_Vagrant_B186_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/Test_stress_Vagrant_B186_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/plots/Test_stress_Vagrant_B186_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B186_macos_2023-10-29.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/logs/ossec_Test_stress_Vagrant_B186_macos_agent_2023-10-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/data/monitor-agent-Test_stress_Vagrant_B186_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B186_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_macos/data/Test_stress_Vagrant_B186_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/Test_stress_Vagrant_B186_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/Test_stress_Vagrant_B186_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/Test_stress_Vagrant_B186_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/plots/Test_stress_Vagrant_B186_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B186_solaris_2023-10-29.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/logs/ossec_Test_stress_Vagrant_B186_solaris_agent_2023-10-29.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B186_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B186_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.6.0/B186-3600m/B186_agent_solaris/data/Test_stress_Vagrant_B186_solaris_agent_agentd_state.csv)

    </details>

</details>

## Conclusion 🔴

No abnormal behavior was detected.

### Logs

- Known issues:
  - https://github.com/wazuh/wazuh-jenkins/issues/4469
  - https://github.com/wazuh/wazuh-jenkins/issues/5399
  - https://github.com/wazuh/wazuh/issues/15701
  - https://github.com/wazuh/wazuh-jenkins/issues/4867
  - https://github.com/wazuh/wazuh-jenkins/issues/5538

### Plots

- New issue: https://github.com/wazuh/wazuh/issues/19958 (_Possibly related to a known issue_: https://github.com/wazuh/wazuh/issues/19381)

> Note: This known issue **was not observed** in the current testing session: https://github.com/wazuh/wazuh/issues/19513

**Comment by mauromalara** [comment]
## Analysis report: Logs errors

<details><summary>Wazuh manager</summary>

- Expected errors in stress tests
```
2023/10/29 00:00:12 sca: WARNING: Interval overtaken.

2023/10/29 05:21:04 wazuh-modulesd:azure-logs: WARNING: Interval overtaken.

2023/10/27 10:52:52 wazuh-logcollector: WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.

```
- Reported in: 

```
2023/10/27 11:03:46 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
 
```



- Reported in: 

```
2023/10/27 11:03:46 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
 
```



- Reported in: 

```
2023/10/27 19:04:04 wazuh-remoted: WARNING: Message queue is full (10). Events may be lost.
 
```



- Reported in: 

Issue not foud

```
2023/10/27 23:04:31 wazuh-remoted: WARNING: Too big message size from socket [14].
 
```



- Reported in: 

```
2023/10/27 23:04:31 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '002' at 'any'.
 
```



- Reported in: 

Issue not foud

```
2023/10/27 23:04:31 wazuh-remoted: WARNING: Decrypt the message fail, socket 14
 
```




</details>

<details><summary>Wazuh solaris</summary>

- Reported in: 

```
2023/10/27 10:58:38 wazuh-modulesd:ciscat: WARNING: No evals defined. Exiting...
 
```



- Reported in: 

```
2023/10/27 11:03:30 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
 
```



- Reported in: 

   - https://github.com/wazuh/wazuh/issues/18122

```
2023/10/27 11:03:30 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
 
```



- Reported in: 

Issue not foud

```
2023/10/27 11:03:30 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.14.172]:1514/tcp': 'Connection refused'.
 
```




</details>

<details><summary>Wazuh macos</summary>

- Expected errors in stress tests
```
2023/10/27 19:29:06 sca: WARNING: Interval overtaken.

```
- Reported in: 

Issue not foud

```
2023/10/27 11:03:39 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.14.172]:1514/tcp': 'Connection refused'.
 
```



- Reported in: 

Issue not foud

```
2023/10/27 23:04:27 wazuh-agentd: ERROR: Connection socket: Connection reset by peer (54)
 
```



- Reported in: 

```
2023/10/27 23:04:27 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
 
```



- Reported in: 

   - https://github.com/wazuh/wazuh/issues/18122

```
2023/10/27 23:04:27 wazuh-modulesd: WARNING: Process locked due to agent is offline. Waiting for connection...
 
```



- Reported in: 

Issue not foud

```
[2023-10-27_17:04:58] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
 
```




</details>

**Comment by QU3B1M** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
LGTM!
