### ISSUE TITLE
SAX parser for translations and CVEs for the VD database

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#19939]
## Description

This issue focuses on enhancing the efficiency and reliability of parsing files received from the content updater, as well as the translation. Currently, these files are processed using traditional parsing methods, which can be resource-intensive and may not scale well with larger files. To address this, we propose the implementation of Nlohmann's SAX (Simple API for XML) parser, known for its speed and low memory consumption.

### User Stories

- As a developer, I want to improve the parsing process of files from the content updater and translation files to make it more efficient and resource-friendly.
- As a system administrator, I want to ensure that the system can handle large files without performance degradation.
- As a user, I want a smooth experience when using the content updater and working with translation files.

### Task

1. Use the implementation of nlohmann SAX Parser helper:
   - Integrate nlohmann SAX Parser helper into the file parsing process for content updater files and translation files.
   - Ensure that the parser handles these files correctly and efficiently.

2. Test the Implementation:
   - Create test cases to verify that the new SAX parser performs parsing tasks correctly.
   - Measure and compare the performance of the SAX parser with the previous parsing method.

### Definition of Done

- Nlohmann's SAX parser is successfully implemented for parsing content updater files and translation files.
- The SAX parser passes all relevant test cases and demonstrates improved efficiency.

**Comment by MiguelazoDS** [comment]
# Overview 

Using a simple script that loads a JSON with 1000 elements and then compares the result with the databaseFeedManaget testtool with the same JSON object.

# Before using SAX parsing 
## We have a peak of 78MB using the script.

<details><summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/b9f03f05-e809-4eb5-941f-c5dac672e34f)

</details>

## DatabaseFeedManager Testtool

Size and number of elements in RocksDB database after storing candidates.

<details><summary>Expand</summary>

![2023-11-13_09-35](https://github.com/wazuh/wazuh/assets/13010397/c0ec369a-ec28-4660-b2aa-8831d262067c)
![2023-11-13_09-35_1](https://github.com/wazuh/wazuh/assets/13010397/da06ca75-a506-4d6f-b20c-bb7146a20d96)

</details>

### Heaptrack analysis 

[heaptrack_before.zip](https://github.com/wazuh/wazuh/files/13335011/heaptrack_before.zip)

Peak of ~120MB 
<details><summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/7d8c594b-f612-4ca6-8bf8-324d3bdc2f45)

</details>

# After using SAX parsing 
## The peak was reduced to the maximum size of a single element in the array using the script

<details><summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/ef4e1d51-0d3c-40b1-8302-75dea6ca29a4)

</details>

## DatabaseFeedManager Testtool

Size and number of elements in RocksDB database after storing candidates.

<details><summary>Expand</summary>

![2023-11-13_09-33](https://github.com/wazuh/wazuh/assets/13010397/4422ca74-94c3-472d-89a6-a6b132917f2c)
![2023-11-13_09-34](https://github.com/wazuh/wazuh/assets/13010397/701e3c26-f4ef-4f67-81a2-dc3bd74dc1a6)

</details>

### Heaptrack analysis 

[heaptrack_after.zip](https://github.com/wazuh/wazuh/files/13335014/heaptrack_after.zip)

Peak slightly over 40MB. 
<details><summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/78cd6c9f-a145-493b-925a-796212b56b7c)

</details>

## Finding 

<details><summary>Expand</summary>

It seems that some duplicates are introduced if we run the testtool more than once.
![2023-11-13_09-37](https://github.com/wazuh/wazuh/assets/13010397/df39e70b-4b3d-43b5-ac86-8d2117dc2597)

details

**Comment by pereyra-m** [comment]
## Update about the finding

It was found that the DB isn't corrupt after running the `databaseFeedManager` test tool, but the version used of `ldb` was too old.
Compiling the tool from sources with the same version used by the wrapper works as expected.
