### ISSUE TITLE
CPU usage decreases in the `Docker-Listener`, `CIS-CAT`, `Osquery`, `Azure-Logs`, and `OpenSCAP` stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19938]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | wazuh-agentd<br>wazuh-modulesd| Agent | Packages | CentOS 7<br>Ubuntu 20 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/19895 it has been detected that the CPU usage of the CentOS agent has decreased from `10%` to a range between `2% and 4%`

- 4.6.0-rc2 issue: https://github.com/wazuh/wazuh/issues/19895
- 4.5.3-rc2 issue: https://github.com/wazuh/wazuh/issues/19491

It can be seen that in 4.6.0 the CPU usage is constant in the three stages of the stress test, increasing only during the second phase (configuration+script stress) from 2% to 4%

![image](https://github.com/wazuh/wazuh/assets/14913942/0dcb92f9-fffc-4474-aeb6-06fa29684d6e)

This differs from 4.5.3 since it can be seen that there is a stable use of 10% throughout the test, with certain components having less use (or none) during the first and third stages (configuration stress).

![image](https://github.com/wazuh/wazuh/assets/14913942/eb7effb7-a667-41d1-97dc-1de17ac2bbb2)

Regarding the configuration, the only difference lies in the value of `max_eps`, which goes from `100` in 4.5.3 to `50` in 4.6.0

---

It is necessary to determine if this behavior is valid and if the components are working correctly.

**Comment by nbertoldo** [comment]
### Conclusion

After comparing the results of both tests, everything indicates that there would be no problems in the operation and performance of the agent. 
Although we see that there is a decrease in the maximum values of disk usage from `10%` in `4.5.3` to a range between `2%` and `4%` in `4.6.0`, it is also observed that in `4.6.0` the disk usage is more constant. There are also no values outside this range (peaks), which could indicate that something is wrong.
The logs were also checked and there are no error messages different from those seen in previous tests.
One point to take into account is that at the end of the stress stage, in `4.6.0`, events are still being generated, unlike in `4.5.3`. This could explain the difference in the disk usage values in this last stage of the test. Nevertheless, there is a clear decrease compared to the stress stage.

- 4.5.3
![4 5 3_generated_events](https://github.com/wazuh/wazuh/assets/117279646/4074ff5e-908e-496c-b2ef-bebd501fc9c3)

- 4.6.0
![4 6 0_generated_events](https://github.com/wazuh/wazuh/assets/117279646/621dcbd5-fd82-4281-a926-8efa81a17482)

**Comment by Dwordcito** [comment]
Closed based on what was described by the development team.
