### ISSUE TITLE
The number of events buffered has decreased

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19933]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | `wazuh-agentd` | Agent | Packages | Ubuntu |

## Description

A decrease in the number of events buffered was observed in the Wazuh Agent (Ubuntu) in `4.6.0-rc2` (**[here](https://github.com/wazuh/wazuh/issues/19906)**) compared to `4.5.3` (**[here](https://github.com/wazuh/wazuh/issues/19499)**).

### Evidence

| Variable | `4.5.3` | `4.6.0-rc2` |
|--|--|--
| Events buffered | ![buffered1](https://github.com/wazuh/wazuh/assets/39094716/82e10549-7b15-4110-bc1d-318b6f9aad01) | ![buffered2](https://github.com/wazuh/wazuh/assets/39094716/7374b343-ceac-4686-9c2e-f62342e98be4) |

**Comment by nmkoremblum** [comment]
Given the performance tests comparison where there is a decrease in buffered events on the Ubuntu agent and after analyzing various parameters, it seems that there are no significant issues. However, there is a 20% increase in the number of messages sent to the manager (AgentD_number_of_message) and a roughly 3% decrease in the number of generated events (AgentD_number_of_generated_events).

This decrease in the number of generated events seems relatively insignificant and could be attributed to casual variations in hardware performance from one test to another. There is no indication that there might be a problem with event processing, and the agent seems to be in good health.

Therefore, it appears that the Ubuntu agent is functioning well, and these minor variations in performance metrics are likely not cause for concern.

**Comment by Dwordcito** [comment]
Closed based on what was described by the development team.
