### ISSUE TITLE
Content Manager - Updating Content Manager orchestration capabilities

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#19947]
|Component|
|---|
| [content_manager](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/content_manager) |

## Description

Make the following changes to the content manager orchestration

- Remove the creation of the RocksDB database. The database given by the `databasePath` configuration parameter will be used.

- Eliminate the initialization of the RocksDB database. The last value contained in the database given by the `databasePath` configuration parameter will be taken as offset of each execution.

**Comment by tsarquis88** [comment]
Blocked until the [test coverage problem](https://github.com/wazuh/wazuh/actions/runs/6705374640) is solved.

**Comment by Damian-Mangold** [comment]
Design change. These changes will not be applied. The content manager will continue to create and initialize the DB.
