### ISSUE TITLE
Refactor and migrate  test_agentd_multi_server

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#19951]
## Description

As part of wazuh/wazuh#17427, we need to refactor and migrate all legacy integration tests from the QA repository to the Core repository.

This issue aims to do this with the agentd tests. The following files are involved:

```
test_agentd/
   ├── conftest.py
   └── test_agentd_multi_server
                       ├──── data
                       |        └── config_templates
                       │        │           └── wazuh_conf.yaml
                       |        └── test_cases
                       │                    └── wazuh_state_tests.yaml
                       │
                       └──test_agentd_multi_server.py
```

### Tasks:
- [x] Apply new format to tests.
- [x] Ensure that each test configures all it needs (ie: internal options).
- [x] Move everything related to the test environment configuration to fixtures.
- [x] Make sure tests clean up the environment after execution.
- [x] Place fixtures in `conftest.py` files.
- [x] Use generic functions of the new QA framework.
- [x] Make sure there is no duplicate code.

### Current status - BLOCKED

**Comment by mjcr99** [comment]
Development stopped by higher priority Issue: https://github.com/wazuh/wazuh/issues/19994

**Comment by jotacarma90** [comment]
ETA delayed due to higher priority issues.

**Comment by mjcr99** [comment]
## Issue updates
**(30/11/2023)** - First test case format migrated, simplifying test sources.

**Comment by MarcelKemp** [comment]
- Done at https://github.com/wazuh/wazuh/issues/17696
