### ISSUE TITLE
Differences in memory usage

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19958]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-rc2 | wazuh-analysisd, wazuh-remoted, wazuh-db | Manager | Packages | CentOS |

## Description

During the analysis of [this test](https://github.com/wazuh/wazuh/issues/19935) the following findings were reached:
- An **increase** 📈 in `wazuh-analysisd`'s memory usage was observed
- A **decrease** 📉 in `wazuh-remoted`'s memory usage was observed
- A **decrease** 📉 in `wazuh-db`'s memory usage was observed

| Variable | `4.5.3` | `4.6.0-rc2`
|--|--|--
| PSS | <img src="https://camo.githubusercontent.com/2681a6b6028a80f3c7538d10711cb50bf23b5fc1fd1539b68a4cd14fbdb4507b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e352e332f423138302d333630306d2f423138305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138305f6d616e616765722d7072652d72656c656173655f5053532e706e67" /> | <img src="https://camo.githubusercontent.com/4e8ae490369e3e81ce06d25820895337a876684ca18ac9a9130f4cf8b827f199/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138362d333630306d2f423138365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138365f6d616e616765722d7072652d72656c656173655f5053532e706e67" />
| RSS | <img src="https://camo.githubusercontent.com/651a8eec78f2d4510bc6eee8460aa646be5d176c3fcdabe68e96af2fbf5d4ad5/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e352e332f423138302d333630306d2f423138305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138305f6d616e616765722d7072652d72656c656173655f5253532e706e67" /> | <img src="https://camo.githubusercontent.com/eb770705eb7abd91f943fd13dc59f5c138b86b755f79678e65f745d395c04111/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138362d333630306d2f423138365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138365f6d616e616765722d7072652d72656c656173655f5253532e706e67" />
| USS | <img src="https://camo.githubusercontent.com/ed3090fcb808446558d657f81ea46ad8a953398bc59c5a307c1513eadb3d3519/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e352e332f423138302d333630306d2f423138305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138305f6d616e616765722d7072652d72656c656173655f5553532e706e67" /> | <img src="https://camo.githubusercontent.com/b179a59a107b471e128708c5233a75047db1cbf78d58aa911cf5ce8f81d542c9/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138362d333630306d2f423138365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138365f6d616e616765722d7072652d72656c656173655f5553532e706e67" />
| VMS | <img src="https://camo.githubusercontent.com/c4e74843404997ab35fd126bbaf800c74bed0b2666c984e7132af111b12148c6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e352e332f423138302d333630306d2f423138305f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138305f6d616e616765722d7072652d72656c656173655f564d532e706e67" /> | <img src="https://camo.githubusercontent.com/53543600e3f375c0e075eb0f0abf71f2ee2593b158dc2850aa7e1798184049f5/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e362e302f423138362d333630306d2f423138365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423138365f6d616e616765722d7072652d72656c656173655f564d532e706e67" />

**Comment by mauromalara** [comment]
Possibly related with: https://github.com/wazuh/wazuh/issues/19381

**Comment by JorgeMarinoDev** [comment]
**Key Findings**

1. **Memory Analysis:** It is imperative to disregard any emerging anomalies in memory usage that are unrelated to the known [issue](https://github.com/wazuh/wazuh/issues/19381). Such anomalies could potentially be indicative of a memory leak or issues with the test setup. No concrete evidence supporting this concern has been discovered.

2. **Known Issue (#19381):** Solaris agents, especially during stress testing, persist in generating events even in the release stage, despite the adjustments made in [version 4.6.0 rc2](https://github.com/wazuh/wazuh/releases/tag/v4.6.0-rc2). It may be necessary to reassess the stress test protocol involving Solaris agents. For further analysis and context, please refer to the corresponding discussion [here](https://github.com/wazuh/wazuh/issues/19381#issuecomment-1747480362).

**Comment by Dwordcito** [comment]
Closed based on what was described by the development team.
