### ISSUE TITLE
Investigate and improve the use of the pool mutex in wazuh-db

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#19960]
## Description

The process `wazuh-db` stores all its open databases in a pool, using a mutex to protect them when any read/write operation occurs.

We suspect that the use of this mutex may be causing many unnecessary locks in `wazuh-db`, not only locking the database being used but all databases, making `wazuh-db` unusable when this mutex is taken by a thread that doesn't release it in a short period of time. In other words, when a thread takes this mutex, `wazuh-db` works as a single thread process, so we must be especially careful at those points where the mutex is needed and make sure not to block it for longer than necessary.

This issue aims to investigate the use of this mutex and add the necessary changes to improve the performance of `wazuh-db` overall.

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.6.0                                      |
| **Release candidate #** | RC                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.6.0-rc |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `0.mutex`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4548/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/monitor-manager-Test_stress_B4548_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/plots/Test_stress_B4548_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4548_manager_2023-11-04.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/logs/ossec_Test_stress_B4548_manager_2023-11-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4548_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/monitor-manager-Test_stress_B4548_manager-warehouse-test.csv)
[Test_stress_B4548_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/Test_stress_B4548_manager_analysisd_events.csv)
[Test_stress_B4548_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/Test_stress_B4548_manager_analysisd_state.csv)
[Test_stress_B4548_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/Test_stress_B4548_manager_remoted_state.csv)
[Test_stress_B4548_manager_wazuh_db_stats.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/Test_stress_B4548_manager_wazuh_db_stats.csv)
[Test_stress_B4548_manager_wazuh_remoted_stats.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_manager_centos/data/Test_stress_B4548_manager_wazuh_remoted_stats.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/monitor-agent-Test_stress_B4548_centos-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/Test_stress_B4548_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/Test_stress_B4548_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/Test_stress_B4548_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/plots/Test_stress_B4548_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4548_centos_2023-11-04.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/logs/ossec_Test_stress_B4548_centos_2023-11-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4548_centos-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/data/monitor-agent-Test_stress_B4548_centos-warehouse-test.csv)
[Test_stress_B4548_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_centos/data/Test_stress_B4548_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/Test_stress_B4548_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/Test_stress_B4548_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/Test_stress_B4548_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/plots/Test_stress_B4548_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4548_ubuntu_2023-11-04.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/logs/ossec_Test_stress_B4548_ubuntu_2023-11-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4548_ubuntu-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/data/monitor-agent-Test_stress_B4548_ubuntu-warehouse-test.csv)
[Test_stress_B4548_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_ubuntu/data/Test_stress_B4548_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/monitor-winagent-Test_stress_B4548_windows-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/Test_stress_B4548_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/Test_stress_B4548_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/Test_stress_B4548_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/plots/Test_stress_B4548_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4548_windows_2023-11-04.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/logs/ossec_Test_stress_B4548_windows_2023-11-04.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4548_windows-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/data/monitor-winagent-Test_stress_B4548_windows-warehouse-test.csv)
[Test_stress_B4548_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.6.0/B4548-3600m/B4548_agent_windows/data/Test_stress_B4548_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by vikman90** [comment]
Working on branch: https://github.com/wazuh/wazuh/compare/4.6...fix/19960-wazuh-db-mutex.
