### ISSUE TITLE
Test Windows JSON eventchannel on Kibana 

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#1997]
Hi team, 

The new Windows JSON eventchannel needs to be tested at an app, Kibana or Splunk, this is the related issue: https://github.com/wazuh/wazuh/issues/905. Some of the most usual logs are these ones:

```
2018 Nov 28 13:38:14 (win) any->WinEvtChannel  {"WinEvtChannel":{"System":{"ProviderName":"Service Control Manager","ProviderGuid":"{555908d1-a6d7-4695-8e1e-26931d2012f4}","EventSourceName":"Service Control Manager","EventID":"1102","Version":"0","Level":"4","Task":"0","Opcode":"0","Keywords":"0x8080000000000000","SystemTime":"2018-11-27T13:03:51.594213100Z","EventRecordID":"8453","ProcessID":"608","ThreadID":"1296","Channel":"System","Computer":"hffg","Message":"A service was installed in the system.","SeverityValue":"INFORMATION"},"EventData":{"SubjectUserSid":"S-1-5-21-571","SubjectUserName":"HFFG$","SubjectDomainName":"WORKGROUP","SubjectLogonId":"0x3e7","TransactionId":"{D2399FF4-F177-11E8-82BA-08002750D7C5}","NewState":"52","ResourceManager":"{7D5F0E1F-ABCB-11E8-A2E2-D5514FE2B72B}","ProcessId":"0x3f8","ProcessName":"C:\\Windows\\System32\\svchost.exe"}}}
```

```
2018 Nov 28 13:38:14 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"Microsoft-Windows-Security-Auditing","ProviderGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","EventID":"4658","Version":"0","Level":"0","Task":"12800","Opcode":"0","Keywords":"0x8020000000000000","SystemTime":"2018-11-28T12:38:13.485779400Z","EventRecordID":"1527865","ProcessID":"4","ThreadID":"3972","Channel":"Security","Computer":"hffg","Message":"The handle to an object was closed.","SeverityValue":"AUDIT_SUCCESS"},"EventData":{"SubjectUserSid":"S-1-5-18","SubjectUserName":"HFFG$","SubjectDomainName":"WORKGROUP","SubjectLogonId":"0x3e7","ObjectServer":"Security","HandleId":"0xbd8","ProcessId":"0x3fc","ProcessName":"C:\\Windows\\System32\\svchost.exe"}}}
```

```
2018 Nov 28 13:38:00 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"Microsoft-Windows-Security-Auditing","ProviderGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","EventID":"4985","Version":"0","Level":"0","Task":"12800","Opcode":"0","Keywords":"0x8020000000000000","SystemTime":"2018-11-28T12:37:59.133994500Z","EventRecordID":"1527772","ProcessID":"4","ThreadID":"3972","Channel":"Security","Computer":"hffg","Message":"The state of a transaction has changed.","SeverityValue":"AUDIT_SUCCESS"},"EventData":{"SubjectUserSid":"S-1-5-18","SubjectUserName":"HFFG$","SubjectDomainName":"WORKGROUP","SubjectLogonId":"0x3e7","TransactionId":"{19B4CE16-F32D-11E8-82C6-08002750D7C5}","NewState":"48","ResourceManager":"{7D5F0E1F-ABCB-11E8-A2E2-D5514FE2B72B}","ProcessId":"0x3b4","ProcessName":"C:\\Windows\\System32\\svchost.exe"}}}
```

```
2018 Nov 28 13:24:13 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"Microsoft-Windows-Kernel-General","ProviderGuid":"{A68CA8B7-004F-D7B6-A698-07E2DE0F1F5D}","EventID":"16","Version":"0","Level":"4","Task":"0","Opcode":"0","Keywords":"0x8000000000000000","SystemTime":"2018-11-28T12:24:12.870972000Z","EventRecordID":"8857","ProcessID":"3816","ThreadID":"264","Channel":"System","Computer":"hffg","Message":"The access history in hive \\??\\C:\\Users\\aa\\AppData\\Local\\Packages\\SonicWALL.MobileConnect_cw5n1h2txyewy\\Settings\\settings.dat was cleared updating 3 keys and creating 1 modified pages.","SeverityValue":"INFORMATION"},"EventData":{"HiveNameLength":"98","HiveName":"\\??\\C:\\Users\\aa\\AppData\\Local\\Packages\\SonicWALL.MobileConnect_cw5n1h2txyewy\\Settings\\settings.dat","KeysUpdated":"3","DirtyPages":"1"}}}
```

```
2018 Nov 28 13:26:11 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"Microsoft-Windows-DistributedCOM","ProviderGuid":"{1B562E86-B7AA-4131-BADC-B6F3A001407E}","EventSourceName":"DCOM","EventID":"10016","Version":"0","Level":"2","Task":"0","Opcode":"0","Keywords":"0x8080000000000000","SystemTime":"2018-11-28T12:26:09.997648000Z","EventRecordID":"8861","ProcessID":"692","ThreadID":"2584","Channel":"System","Computer":"hffg","Message":"The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID ","SeverityValue":"ERROR"},"EventData":{"param1":"application-specific","param2":"Local","param3":"Activation","param4":"{D63B10C5-BB46-4990-A94F-E40B9D520160}","param5":"{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}","param6":"NT AUTHORITY","param7":"SYSTEM","param8":"S-1-5-18","param9":"LocalHost (Using LRPC)","param10":"Unavailable","param11":"Unavailable"}}}
```

```
2018 Nov 28 13:26:09 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"NetBT","EventID":"4321","Level":"2","Task":"0","Keywords":"0x80000000000000","SystemTime":"2018-11-28T12:26:08.513626000Z","EventRecordID":"8860","Channel":"System","Computer":"hffg","Message":"The name \"WORKGROUP      :1d\" could not be registered on the interface with IP address 10.0.3.15. The computer with the IP address 10.0.3.2 did not allow the name to be claimed by this computer.","SeverityValue":"ERROR"},"EventData":{"Data":"","Data":"WORKGROUP      :1d","Data":"10.0.3.15","Data":"10.0.3.2","Binary":"000000000400320000000000E11000C001010000010000C009000000000000000000000000000000"}}}
```

## Fields information

Some of the fields are not static, it is possible that they don't appear in every log. Here I explain some info about each of them:

- The field `System` is mainly static, but some fields inside it may be variant, they are the next ones:
    - EventSourceName
    -  Opcode
    - ProcessID
    - ThreadID
- The main field `EventData` may be empty, for example in the next log:
```
2018 Nov 28 13:31:10 (win) any->WinEvtChannel {"WinEvtChannel":{"System":{"ProviderName":"Microsoft-Windows-LocationProvider","ProviderGuid":"{EAAB4D92-5199-46C4-A779-9721CE323D46}","EventID":"2001","Version":"0","Level":"4","Task":"1","Opcode":"0","Keywords":"0x2000000000000001","SystemTime":"2018-11-28T12:31:09.394337300Z","EventRecordID":"15202","Correlation":"","ProcessID":"5640","ThreadID":"5712","Channel":"Application","Computer":"hffg","Message":"The Windows Location Provider has successfully started","SeverityValue":"INFORMATION"},"EventData":{}}}
```
   The fields inside `EventData` are not the same in every log, sometimes they are `Data`, sometimes they are `param1, param2...paramn`, they use to change.

**Comment by medlynx** [comment]
Not enough important data in alerts.

Example, json-alert:
`{
  "_index": "wazuh-alerts-3.x-2018.12.03",
  "_type": "wazuh",
  "_id": "n-cJdWcBfGylGbeSRM44",
  "_version": 1,
  "_score": null,
  "_source": {
    "id": "1543856800.221480100",
    "@timestamp": "2018-12-03T17:06:40.389Z",
    "manager": {
      "name": "srv-ossec"
    },
    "path": "/var/ossec/logs/alerts/alerts.json",
    "agent": {
      "id": "328",
      "name": "WS3015"
    },
    "data": {
      "WinEvtChannel": {
        "System": {
          "ProviderGuid": "{5770385F-C22A-43E0-BF4C-06F5698FFBD9}",
          "SeverityValue": "INFORMATION",
          "Correlation": "",
          "Version": "5",
          "Level": "4",
          "Message": "Process Create:",
          "Task": "1",
          "EventID": "1",
          "SystemTime": "2018-12-03T17:06:39.945000000Z",
          "Channel": "Microsoft-Windows-Sysmon/Operational",
          "ProviderName": "Microsoft-Windows-Sysmon",
          "Computer": "ws-3050-1",
          "Opcode": "0",
          "ThreadID": "5904",
          "EventRecordID": "162346",
          "Keywords": "0x8000000000000000",
          "ProcessID": "9492"
        },
        "EventData": {
          "Description": "Обработчик команд Windows",
          "Product": "Операционная система Microsoft® Windows®",
          "UtcTime": "2018-12-03 17:06:39.944",
          "ProcessGuid": "{7F09EA5E-629F-5C05-0800-0010E5635313}",
          "Image": "C:\\Windows\\SysWOW64\\cmd.exe",
          "FileVersion": "6.1.7601.17514 (win7sp1_rtm.101119-1850)",
          "RuleName": "",
          "ProcessId": "20040",
          "CommandLine": "C:\\Windows\\system32\\cmd.exe /c wmic process where processID=25232 get Name",
          "Company": "Microsoft Corporation"
        }
      }
    },
    "rule": {
      "level": 12,
      "groups": [
        "sysmon",
        "sysmon_event1"
      ],
      "id": "255004",
      "description": "Sysmon - Event 1:  Process Create: : C:\\Windows\\system32\\cmd.exe /c wmic process where processID=25232 get Name. Execution: C:\\Windows\\SysWOW64\\cmd.exe",
      "mail": true,
      "firedtimes": 47
    },
    "location": "WinEvtChannel",
    "decoder": {
      "name": "json"
    }
  },
  "fields": {
    "@timestamp": [
      "2018-12-03T17:06:40.389Z"
    ],
    "data.WinEvtChannel.System.SystemTime": [
      "2018-12-03T17:06:39.945Z"
    ]
  },
  "highlight": {
    "data.WinEvtChannel.EventData.CommandLine": [
      "@kibana-highlighted-field@C:\\Windows\\system32\\cmd.exe /c wmic process where processID=25232 get Name@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1543856800389
  ]
}`

This log in windows event:
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Sysmon" Guid="{5770385F-C22A-43E0-BF4C-06F5698FFBD9}" /> 
  <EventID>1</EventID> 
  <Version>5</Version> 
  <Level>4</Level> 
  <Task>1</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2018-12-03T17:06:39.957000000Z" /> 
  <EventRecordID>162347</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="9492" ThreadID="5904" /> 
  <Channel>Microsoft-Windows-Sysmon/Operational</Channel> 
  <Computer>ws-3050-1</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <EventData>
  <Data Name="RuleName" /> 
  <Data Name="UtcTime">2018-12-03 17:06:39.956</Data> 
  <Data Name="ProcessGuid">{7F09EA5E-629F-5C05-0800-0010C9655313}</Data> 
  <Data Name="ProcessId">15744</Data> 
  <Data Name="Image">C:\Windows\SysWOW64\wbem\WMIC.exe</Data> 
  <Data Name="FileVersion">6.1.7600.16385 (win7_rtm.090713-1255)</Data> 
  <Data Name="Description">WMI Commandline Utility</Data> 
  <Data Name="Product">Microsoft® Windows® Operating System</Data> 
  <Data Name="Company">Microsoft Corporation</Data> 
  <Data Name="CommandLine">wmic process where processID=25232 get Name</Data> 
  <Data Name="CurrentDirectory">C:\Program Files (x86)\ossec-agent\</Data> 
  <Data Name="User">NT AUTHORITY\система</Data> 
  <Data Name="LogonGuid">{7F09EA5E-5F67-5BA9-0000-0020E7030000}</Data> 
  <Data Name="LogonId">0x3e7</Data> 
  <Data Name="TerminalSessionId">0</Data> 
  <Data Name="IntegrityLevel">System</Data> 
  <Data Name="Hashes">MD5=A03CF3838775E0801A0894C8BACD2E56,SHA256=132AA270790F56A7524CAB968927ED5E1D91B9A26D4BADCB24E450E7DECC5F81</Data> 
  <Data Name="ParentProcessGuid">{7F09EA5E-629F-5C05-0800-0010E5635313}</Data> 
  <Data Name="ParentProcessId">20040</Data> 
  <Data Name="ParentImage">C:\Windows\SysWOW64\cmd.exe</Data> 
  <Data Name="ParentCommandLine">C:\Windows\system32\cmd.exe /c wmic process where processID=25232 get Name</Data> 
  </EventData>
  </Event>`


in the issue:
- No User
- No CurrentDirectory
- No ParentImage
- and some other data..
