### ISSUE TITLE
Bug in FIM with simbolic and hard links

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#1999]
An incorrect functioning has been found when FIM monitors directories that contain symbolic links. Those are added to the database as regular files.

In case of finding such files the behavior should be:
- If the link points to a directory, go through that content and insert the corresponding records in the database.
- If the link points to a file, insert the record with the attributes of the file it points to.
- If the link is removed, delete the corresponding records in the database.
- If the link is modified, add the new content and delete the previous one.

We have to review the behavior with hard links in Linux and replicate a similar behavior in Windows systems.

**Comment by juergenc** [comment]
Hello @bah07,

_"If the link points to a file, insert the record with the attributes of the file it points to."_
If you _follow_ the symlink as described here, keep the following corner case in mind: what if the symling and the file where it points to it are in the same directory?
```
$ touch file
$ ln -s file symlink
```

1. FIM monitor detects `symlink`, follows it to `file` and registers the attribute of `file` in the FIM database
1. FIM monitor detects `file` and registers the attribute of `file` a second time in the FIM database

**Comment by DaveVG1** [comment]
Documentation related issue: https://github.com/wazuh/wazuh-documentation/issues/749
