### ISSUE TITLE
report on wazuh

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh#200]
Hey guys!
How are you?

I need help... 
I'm lost in how to send a report by email, automatically by wazuh

System: CentOS7
Email alert: Gmail <postfix>

**Comment by changux** [comment]
Hi,
You need to configure three separate things:
Install software
Debian based distros
# apt-get install ssmtp mailutils postfix
Redhat based distros
# yum install ssmtp mailutils postfix
Send messages through Gmail.
Configure your /etc/ssmtp/ssmtp.conf:
root=YOUR_GMAIL_ACCOUNT
AuthUser=YOUR_GMAIL_ACCOUNT
AuthPass=YOUR_GMAIL_PASSWORD
UseSTARTTLS=YES
rewriteDomain=gmail.com
hostname=localhost
FromLineOverride=YES
TLS_CA_File=/etc/ssl/certs/ca-certificates.crt
On Redhat based systems, you must replace the last line by:
TLS_CA_File=/etc/pki/tls/certs/ca-bundle.crt
And also, your /etc/ssmtp/revaliases.conf
root:YOUR_GMAIL_ACCOUNT:smtp.gmail.com:587
localusername:YOUR_GMAIL_ACCOUNT:smtp.gmail.com:587
Don`t forget to enable less secure apps on Gmail
Wazuh's Configuration
Edit /var/ossec/etc/ossec.conf:
<global>
   <email_notification>yes</email_notification>
   <email_to>YOUR_GMAIL_ACCOUNT</email_to>
   <smtp_server>localhost</smtp_server>
   <email_from>YOUR_GMAIL_ACCOUNT</email_from>
</global>
And restart wazuh.
At this point, you must have enabled your email alerts.
For detailed information about email alerts, please check:
https://documentation.wazuh.com/2.0/user-manual/manager/output-options/manual-email-report/index.html
Hope it helps.

**Comment by borbelyau** [comment]
Tks @changux

**Comment by karthigaadass** [comment]
when i try to take report ,its showing this below error.

Reporting. 5029 - Reporting was aborted (Cannot read property '2' of undefined)

**Comment by nikhilsingh42** [comment]
Hi ,

My report config is attached for this config i am not getting the daily report.
Please let me know what is the mistake i am doing.
Is it possible to change the timing of daily report.
![image](https://user-images.githubusercontent.com/47519186/52776678-23fc9a80-3068-11e9-85ae-b516968050da.png)


Regards
Nikhil
