### ISSUE TITLE
Release 4.7.0 - Alpha 2 - Integration tests

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#20038]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/20019|
| **Version**                      | 4.7.0                                                   |
| **Release stage**            | Alpha 2                                                      |
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.7.0-alpha2          |
| **Wazuh QA: Branch**    | `v4.7.0-alpha2`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.7.0-alpha2         |
| **Wazuh: Branch**    | `v4.7.0-alpha2` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

#### References

|Color|Status |
|:--:|:--|
|:green_circle:|All tests passed successfully|
|:yellow_circle:|Known issues|
|:red_circle:|Some tests have failures or errors|
|:large_blue_circle:|Test execution in progress|
|:black_circle:|To Do|
|🟠|Jenkins provision fails|
|:purple_circle:| All skipped |

## Test Integration - Results 

<table>
<thead>
<tr>
<th style="width: 175px;">Name</th>
<th style="width: 499px;" colspan="6">Jenkins</th>
</tr>
</thead>
<tbody>
<tr>
<td style="width: 175px;">OS</td>
<td style="width: 208px;" colspan="2">Linux</td>
<td style="width: 79px;">Windows</td>
<td style="width: 97px;">Solaris</td>
<td style="width: 97px;" colspan="2">macOS</td>
</tr>
<tr>
<td style="width: 175px;">Target</td>
<td style="width: 103px;">Manager</td>
<td style="width: 99px;">Agent</td>
<td style="width: 79px;">Agent</td>
<td style="width: 97px;">Agent</td>
<td style="width: 97px;" colspan="2">Agent</td>
</tr>
<tr>
<td style="width: 175px;"><strong>active_response</strong></td>
<td style="width: 103px;"> :green_circle: </td>
<td style="width: 99px;"> :green_circle:  </td>
<td style="width: 79px;"> :green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>agentd</strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;"> :green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>analysisd</strong></td>
<td style="width: 103px;"> :green_circle:  </td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>api</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>authd</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>enrollment<br/></strong></td>
<td style="width: 103px;">NA</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>fim</strong></td>
<td style="width: 103px;"> :green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">:green_circle:</td>
<td style="width: 97px;">:green_circle:</td>
<td style="width: 97px;" colspan="2"> :green_circle: </td>
</tr>
<tr>
<td style="width: 175px;"><strong>gcloud<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>github<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logcollector</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;"> :green_circle: </td>
<td style="width: 79px;"> :green_circle:</td>
<td style="width: 97px;"> :green_circle:</td>
<td style="width: 97px;" colspan="2">:green_circle:</td>
</tr>
<tr>
<td style="width: 175px;"><strong>logtest<br/></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>office365<br /></strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">:green_circle:</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>remoted</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rids</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>rootcheck</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>vulnerability_detector</strong></td>
<td style="width: 103px;"> :red_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>wazuh_db</strong></td>
<td style="width: 103px;">:green_circle:</td>
<td style="width: 99px;">NA</td>
<td style="width: 79px;">NA</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">NA</td>
</tr>
<tr>
<td style="width: 175px;"><strong>syscollector</strong></td>
<td style="width: 103px;"> :green_circle:  </td>
<td style="width: 99px;"> :green_circle:</td>
<td style="width: 79px;"> :red_circle:</td>
<td style="text-align: center; width: 97px;">NA</td>
<td style="text-align: center; width: 97px;" colspan="2">:green_circle:</td>
</tr>
</tbody>
</table>

## Evidence
- Test Launcher: https://ci.wazuh.info/job/Test_integration_launcher/222/
> Several tests have failed in the first execution, so were executed again.
> - FIM - MacOS: https://ci.wazuh.info/job/Test_integration/44470/  
> - Active Response - Windows https://ci.wazuh.info/job/Test_integration/44469/
> - Active Response - Linux agent: https://ci.wazuh.info/job/Test_integration/44469/
> - Agentd - Linux agent: https://ci.wazuh.info/job/Test_integration/44474/
> - Agentd - Windows: https://ci.wazuh.info/job/Test_integration/44475/
> - Logcollector - MacOS: https://ci.wazuh.info/job/Test_integration/44476/
> - Syscollector - Windows: https://ci.wazuh.info/job/Test_integration/44481/
> - Vulnerability Detector - Linux manager: https://ci.wazuh.info/job/Test_integration/44480/

## Conclusion 🟡  

The tests: `test_vulnerability_detector` on `wazuh-manager` and `test_syscollector` on `winagent` have failed with errors, both cases were reported previously. 
- https://github.com/wazuh/wazuh-qa/issues/4230
- https://github.com/wazuh/wazuh-qa/issues/4429

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [ ] @davidjiglesias

**Comment by QU3B1M** [comment]
### Failing test execution: Syscollector - Windows agent

```shellsession
```

**Comment by damarisg** [comment]
GJ!
