### ISSUE TITLE
Release 4.7.0 - Alpha 2 - Footprint Metrics - ALL-EXCEPT-OSQUERY,VULNERABILITY-DETECTOR (2.5d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#20073]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #20019                                         |
| **Main footprint metrics issue #** | #20020                                         |
| **Version** | 4.7.0                                      |
| **Release stage #** | Alpha 2                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.7.0-alpha2 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/188/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/Test_stress_Vagrant_B188_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/plots/Test_stress_Vagrant_B188_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B188_manager_2023-11-06.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/logs/ossec_Test_stress_Vagrant_B188_manager_2023-11-06.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B188_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/data/monitor-manager-Test_stress_Vagrant_B188_manager-pre-release.csv)
[Test_stress_Vagrant_B188_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/data/Test_stress_Vagrant_B188_manager_analysisd_events.csv)
[Test_stress_Vagrant_B188_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/data/Test_stress_Vagrant_B188_manager_analysisd_state.csv)
[Test_stress_Vagrant_B188_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_manager_centos/data/Test_stress_Vagrant_B188_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/Test_stress_Vagrant_B188_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/Test_stress_Vagrant_B188_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/Test_stress_Vagrant_B188_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/plots/Test_stress_Vagrant_B188_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B188_macos_2023-11-06.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/logs/ossec_Test_stress_Vagrant_B188_macos_agent_2023-11-06.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/data/monitor-agent-Test_stress_Vagrant_B188_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B188_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_macos/data/Test_stress_Vagrant_B188_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/Test_stress_Vagrant_B188_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/Test_stress_Vagrant_B188_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/Test_stress_Vagrant_B188_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/plots/Test_stress_Vagrant_B188_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B188_solaris_2023-11-06.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/logs/ossec_Test_stress_Vagrant_B188_solaris_agent_2023-11-06.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B188_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B188_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B188-3600m/B188_agent_solaris/data/Test_stress_Vagrant_B188_solaris_agent_agentd_state.csv)

    </details>

</details>
## Notes
https://github.com/wazuh/wazuh-jenkins/issues/5882 used as reference

### Plots

No abnormalities were found

#### New issue

- https://github.com/wazuh/wazuh/issues/20082

#### Known issues

- https://github.com/wazuh/wazuh-jenkins/issues/5538
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5399
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh/issues/15701
- https://github.com/wazuh/wazuh/issues/17596

**Comment by pro-akim** [comment]
# Analysis report

## Graphs :green_circle:

### Manager
No abnormalities were found

### MacOS
VMS: small decrease of agentd

### Solaris
No abnormalities were found

## Logs :red_circle:


<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2023/11/03 13:25:32 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.12.241]:1514/tcp': 'Connection 
2023/11/03 13:26:19 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2023/11/03 13:26:19 wazuh-agentd ERROR: Connection socket: Connection reset by peer (54)
2023/11/05 13:27:49 wazuh-agentd WARNING: Process locked due to agent is offline. Waiting for connection...
2023/11/05 13:27:49 wazuh-agentd ERROR: Connection socket: Operation timed out (60)
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5538 - Known issue
```
[2023-11-03_19:27:54] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
```

- Reported: https://github.com/wazuh/wazuh/issues/20082 - New issue
```
2023/11/05 13:27:41 wazuh-syscheckd WARNING: Socket busy, discarding message.
```

</details>

<details><summary>MacOS</summary>

- Expected in stress test
```
2023/11/04 06:40:50 wazuh-modulesd:azure-logs WARNING: Interval overtaken.
2023/11/06 00:00:13 sca WARNING: Interval overtaken.
2023/11/03 13:14:29 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2023/11/03 13:25:58 wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5399 - Known issue
```
2023/11/03 13:25:40 wazuh-modulesd:oscap ERROR: Internal error. Exiting...
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2023/11/03 13:25:39 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

- Reported: https://github.com/wazuh/wazuh/issues/15701 - Known issue
```
2023/11/03 13:26:21 wazuh-remoted WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '002' at 'any'.
```

- Reported: https://github.com/wazuh/wazuh/issues/17596 - Known issue
```
2023/11/03 13:26:21 wazuh-remoted WARNING: Too big message size from socket [14].
```

</details>


<details><summary>Solaris</summary>

- Expected in stress test
```
2023/11/03 13:25:22 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
```

2023/11/03 13:20:43 wazuh-modulesd ERROR: Child process 2725 not found.

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2023/11/03 13:25:23 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.12.241]:1514/tcp': 'Connection refused'.
2023/11/03 13:25:23 wazuh-syscheckd WARNING: Process locked due to agent is offline. Waiting for connection...
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2023/11/03 13:20:22 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

</details>

**Comment by pro-akim** [comment]
# Analysis report

## Graphs :green_circle:

### Manager
No abnormalities were found

### MacOS
VMS: small decrease of agentd

### Solaris
No abnormalities were found

## Logs :red_circle:


<details><summary>MacOS</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2023/11/03 13:25:32 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.12.241]:1514/tcp': 'Connection 
2023/11/03 13:26:19 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2023/11/03 13:26:19 wazuh-agentd ERROR: Connection socket: Connection reset by peer (54)
2023/11/05 13:27:49 wazuh-agentd WARNING: Process locked due to agent is offline. Waiting for connection...
2023/11/03 13:26:19 wazuh-agentd ERROR: Connection socket: Operation timed out (54)
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5538 - Known issue
```
[2023-11-03_19:27:54] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
```

- Reported: https://github.com/wazuh/wazuh/issues/20082 - New issue
```
2023/11/05 13:27:41 wazuh-syscheckd WARNING: Socket busy, discarding message.
```

</details>

<details><summary>Manager</summary>

- Expected in stress test
```
2023/11/04 06:40:50 wazuh-modulesd:azure-logs WARNING: Interval overtaken.
2023/11/03 13:25:48 sca WARNING: Interval overtaken.
2023/11/03 13:14:29 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2023/11/03 13:25:58 wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5399 - Known issue
```
2023/11/03 13:25:40 wazuh-modulesd:oscap ERROR: Internal error. Exiting...
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2023/11/03 13:25:39 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

- Reported: https://github.com/wazuh/wazuh/issues/15701 - Known issue
```
2023/11/03 13:26:21 wazuh-remoted WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '002' at 'any'.
```

- Reported: https://github.com/wazuh/wazuh/issues/17596 - Known issue
```
2023/11/03 13:26:21 wazuh-remoted WARNING: Too big message size from socket [14].
```

</details>


<details><summary>Solaris</summary>

- Expected in stress test
```
2023/11/03 13:25:22 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
```

2023/11/03 13:20:43 wazuh-modulesd ERROR: Child process 2725 not found.

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2023/11/03 13:25:23 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.12.241]:1514/tcp': 'Connection refused'.
2023/11/03 13:25:23 wazuh-syscheckd WARNING: Process locked due to agent is offline. Waiting for connection...
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2023/11/03 13:20:22 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

</details>

**Comment by QU3B1M** [comment]
LGTM!
