### ISSUE TITLE
Release 4.7.0 - Alpha 2 - Demo use cases

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#20074]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release candidate issue** |  #20019                                   |
| **Version**                      | 4.7.0                                                   |
| **Release candidate**            | Alpha 2                                                     |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.7.0-alpha2          |
| **Previous Demo use cases**      | #19701                                                   |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:green_circle:     | Audit                  |        |
:green_circle:     | AWS Wodle              |        | 
:green_circle:     | Brute force            |        |
:green_circle:     | Docker                 |        |
:green_circle:     | Emotet                 |   | 
:green_circle:     | FIM                    |        |
:green_circle:     | IP Reputation          |        | 
:green_circle:     | Netcat                 |        | 
:green_circle:     | Osquery                |        | 
:green_circle:     | Shellshock             |        |  
:green_circle:     | SQL Injection          |        | 
:green_circle:     | Slack                  |        | 
:green_circle:     | Suricata               |        |   
:green_circle:     | Trojan                 |        |
:green_circle:     | Virustotal             |        | 
:green_circle:     | Vulnerability Detector |        |
:green_circle:     | Yara                   |        | 
:green_circle:     | Windows Defender       |  | 

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Conclusion
The deployment succeeded and the Emotet test was validated manually.

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [x] @davidcr01

**Comment by davidcr01** [comment]
### Deployment
The deployment succeeded: [JenkinsJob](https://ci.wazuh.info/job/Procedure_deploy_demo/240/consoleFull).

The tests were passed correctly.

### Emotet

The Emotet UC was manually validated and it is not working:

![Screenshot from 2023-11-06 11-06-52](https://github.com/wazuh/wazuh/assets/72193239/09e8b83e-0df0-4fc3-bd32-6d267e1e8958)


![image](https://github.com/wazuh/wazuh/assets/72193239/08c7a1f3-0428-46c9-ba68-86b316663734)

**Comment by vcerenu** [comment]
LGTM

**Comment by damarisg** [comment]
This issue should contain evidence about slack and VD testing. Could you add it, please?

**Comment by damarisg** [comment]
LGTM!
