### ISSUE TITLE
Differences in the pattern and density of resource usage fluctuations in Windows agent in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20088]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh | Agent | Packages | Windows |

[Testing Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/20069)

RSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20069
![image](https://github.com/wazuh/wazuh/assets/125690423/e91e4444-ee45-4df6-9797-0bc651e86ba1)
![image](https://github.com/wazuh/wazuh/assets/125690423/0c44683a-d9f8-4a14-ad26-337bcf3bd02f)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5881
![image](https://github.com/wazuh/wazuh/assets/125690423/c7521a76-6e21-4c2f-b120-4bead22df868)
![image](https://github.com/wazuh/wazuh/assets/125690423/f5ac2615-4317-433c-b2fd-42e07971658c)

USS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20069
![image](https://github.com/wazuh/wazuh/assets/125690423/07937b05-7233-4ad0-a790-d330eeb42aca)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5881
![image](https://github.com/wazuh/wazuh/assets/125690423/66af2c63-028e-4f02-bf4a-a869b9e99213)

VMS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20069
![image](https://github.com/wazuh/wazuh/assets/125690423/550befee-5da9-4539-9f7a-42bcf839a9a9)
4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5881
![image](https://github.com/wazuh/wazuh/assets/125690423/f7e0533f-8b80-42f4-b6a6-4a57443ab80e)

Further research should be done

**Comment by vikman90** [comment]
RSS maximums are similar. The progress is not relevant.
