### ISSUE TITLE
Wazuh-syscheckd warning message `Socket busy, discarding message` found in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20082]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh | Agent | Packages | macOS |

A new WARNING message in Wazuh manager was discovered in stress testing [ALL-EXCEPT-OSQUERY,VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/20073)

```
2023/11/05 13:27:41 wazuh-syscheckd WARNING: Socket busy, discarding message.
```

Further research should be performed

**Comment by cborla** [comment]
## Syscheck Analysis.

### Agent 

#### Error message

``` console
2023/11/05 13:27:41 wazuh-syscheckd WARNING: Socket busy, discarding message.
```

#### Agent Configuration:

Agent `ossec.conf`: 

```
  <syscheck>
    <disabled>no</disabled>
    <frequency>43200</frequency>
    .
    .
    .
  </syscheck>
```

The syscheck scan runs every 12 hours. 


#### Agent log:


```
2023/11/05 13:27:27 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2023/11/05 13:27:41 wazuh-syscheckd: WARNING: Socket busy, discarding message.
2023/11/05 13:27:49 wazuh-agentd: ERROR: Connection socket: Operation timed out (60)
2023/11/05 13:27:49 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2023/11/05 13:27:49 wazuh-agentd: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/11/05 13:27:49 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/11/05 13:27:49 wazuh-agentd: INFO: Closing connection to server ([172.31.12.241]:1514/tcp).
2023/11/05 13:27:49 wazuh-agentd: INFO: Trying to connect to server ([172.31.12.241]:1514/tcp).
2023/11/05 13:28:17 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.12.241]:1514/tcp).
2023/11/05 13:28:17 wazuh-agentd: INFO: Server responded. Releasing lock.
2023/11/05 13:28:19 wazuh-agentd: INFO: Agent is now online. Process unlocked, continuing...
2023/11/05 13:28:19 wazuh-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
```

In the event extract you can see that the agent starts the syscheck scan and after a few seconds tries to send the event, having the buffer busy, ```Socket busy, discarding message ```, 9 seconds after the WARNING message appeared, you can see the event `ERROR: Connection socket: Operation timed out (60)` indicating that the connection with the manager has expired, or that the manager has not responded to the agent for more than 60 seconds, so the agent closes the connection and re-establishes it after a few minutes.

The WARNING message is given for a race condition, in which syscheck tried to send its event, but the socket was not available, it is not an erroneous behavior of syscheck but it should be analyzed why the socket was not available. We can also verify this theory by analyzing the graphs of [agent status](https://camo.githubusercontent.com/ab26a46feff9fbf98c25b13e52d50c0cd8948e6522c27fe0082da7e63c4497c1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e372e302f423138382d333630306d2f423138385f6167656e745f6d61636f732f706c6f74732f546573745f7374726573735f56616772616e745f423138385f6d61636f735f6167656e745f6167656e74645f73746174655f4167656e74445f5374617475732e706e67) (connected or not) and [buffered events](https://camo.githubusercontent.com/e1a875d39a80d5e738ad5663eab95231e9b0698fab0f8ac1b0017d76643f3098/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e372e302f423138382d333630306d2f423138385f6167656e745f6d61636f732f706c6f74732f546573745f7374726573735f56616772616e745f423138385f6d61636f735f6167656e745f6167656e74645f73746174655f4167656e74445f4e756d6265725f6f665f6576656e74735f62756666657265642e706e67).

### Manager

#### Error messages at 13:27 on 2023/11/05
The following processes are launched within the same minute in which the agent is disconnected.

syscheckd:
``` console
2023/11/05 13:27:46 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2023/11/05 13:27:49 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
```
rootcheck:
``` console
2023/11/05 13:27:01 rootcheck: INFO: Starting rootcheck scan.
2023/11/05 13:27:14 rootcheck: INFO: Ending rootcheck scan.
```
azure:
``` console
2023/11/05 13:27:01 wazuh-modulesd:azure-logs: INFO: Starting fetching of logs.
2023/11/05 13:27:01 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/11/05 13:27:08 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for request 'azure-activity'.
2023/11/05 13:27:08 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/11/05 13:27:08 wazuh-modulesd:azure-logs: INFO: Starting Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
2023/11/05 13:27:09 wazuh-modulesd:azure-logs: INFO: Finished Graphs log collection for request 'azure-active_directory'.
2023/11/05 13:27:09 wazuh-modulesd:azure-logs: INFO: Finished Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
```

syscollector (4 times)
``` console
2023/11/05 13:27:21 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/11/05 13:27:26 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```
sca (8 times)
``` console
2023/11/05 13:27:05 sca: INFO: Starting Security Configuration Assessment scan.
2023/11/05 13:27:05 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2023/11/05 13:27:13 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2023/11/05 13:27:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 8 seconds.
2023/11/05 13:27:13 sca: WARNING: Interval overtaken.
```

But nothing indicates a possible disconnection error in the manager.

## Conclusion
The agent disconnection appears to be a socket error.
The behavior of the agent is adequate according to its configuration, it disconnects after 60 seconds without response and reconnects, successfully.
On the manager side there is no problem in the logs.
In general there are no anomalies or general failures, the severity of the message is according to the event that will be discarded.
