### ISSUE TITLE
Increased `modulesd` usage in stress test

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#20095]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh | Manager & Agent | Packages | CentOS Manager / Ubuntu & CentOS Agent |

During the analysis of [Footprint Metrics - LOGCOLLECTOR,SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/20057#top) an `modulesd` increase was detected in `disk` and `VMS` plots. 

<details><summary>Disk</summary>

- Manager 4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20057
  ![image](https://github.com/wazuh/wazuh/assets/44633633/60bb834d-4861-4714-9de5-9bb28d041f8f)

- Manager 4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19892
  ![image](https://github.com/wazuh/wazuh/assets/44633633/079ed00d-268d-4efb-af25-55e581460c9e)

- CentOS agent 4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20057
  ![image](https://github.com/wazuh/wazuh/assets/44633633/e18a5f7b-8de2-44b1-bfee-38b9eb1833c0)

- CentOS agent  4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19892
  ![image](https://github.com/wazuh/wazuh/assets/44633633/02af4285-c5ba-43c1-aaed-c4bcc0b11347)

- Ubuntu agent 4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20057
  ![image](https://github.com/wazuh/wazuh/assets/44633633/9dd14e28-a996-402b-8779-822a68c33d2a)

- Ubuntu agent  4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19892
  ![image](https://github.com/wazuh/wazuh/assets/44633633/9ee36d6f-77b0-4057-9dda-c2a06327fef7)
</details>

<details><summary>VMS</summary>

> This can be observed only in _ubuntu agent_.
- Ubuntu agent 4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20057
  ![image](https://github.com/wazuh/wazuh/assets/44633633/9b23a93c-3b9e-4768-8432-b0e1ad13f1c6)

- Ubuntu agent 4.6.0-rc2 https://github.com/wazuh/wazuh/issues/19892
  ![image](https://github.com/wazuh/wazuh/assets/44633633/e7bfb50d-84c5-4c8b-bc72-b5673d4a3c21)
</details>

Further research should be done

**Comment by nmkoremblum** [comment]
First of all, I want to emphasize that disk usage is inherently non-deterministic, as has been reiterated many times in previous test reports.
The observed variations in disk usage, while apparent, are relatively insignificant in the broader context of system performance.
It's noteworthy that these fluctuations primarily occur during the configuration loading process and do not persist beyond this specific phase.
Furthermore, there are no other discernible indicators suggesting any errors or issues with the agent's overall functionality.
Identifying the specific code changes responsible for the changes in the disk usage pattern is really hard as there have been many changes on `4.7.0`.

**Comment by nmkoremblum** [comment]
Respecting the increase in the VMS in `4.7.0`, there is indeed a ~12% increase in comparison to `4.6.0`. Just as said before, such a value is not deterministic and after reviewing the code changes there are none related to `syscollector`, which is the only module that is enabled under the scope of `modulesd`. Apart from this, the configuration is the same.
