### ISSUE TITLE
Failed to start Wazuh manager.

### ISSUE THREAD

**Issue by thoufik786** [wazuh/wazuh#20097]
Ubuntu 18.04.6 | and wazuh v4.6.0. 

Hi All,

I created new custom decoders and rules for my use cases for the first time in my Wazuh manager. After that, my Wazuh manager didn't start and it shows below error.

lab@lab-Standard-PC-Q35-ICH9-2009:~$ sudo systemctl restart  wazuh-manager.service
Job for wazuh-manager.service failed because the control process exited with error code.
See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.

lab@lab-Standard-PC-Q35-ICH9-2009:~$ sudo systemctl status wazuh-manager.service
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2023-11-07 11:47:23 IST; 21s ago
  Process: 6067 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)

Nov 07 11:47:22 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: Starting Wazuh manager...
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: ERROR: (1230): Invalid element in the config
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: ERROR: (1202): Configuration error at 'etc/o
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'et
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: wazuh-csyslogd: Configuration error. Exiting
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: Failed to start Wazuh manager.

lab@lab-Standard-PC-Q35-ICH9-2009:~$ sudo journalctl -xe
Nov 07 11:45:24 lab-Standard-PC-Q35-ICH9-2009 opensearch-dashboards[822]: {"type":"response","@timestamp":"2023-11-07T06:15:24Z","tags":[
Nov 07 11:45:24 lab-Standard-PC-Q35-ICH9-2009 opensearch-dashboards[822]: {"type":"response","@timestamp":"2023-11-07T06:15:24Z","tags":[
Nov 07 11:45:26 lab-Standard-PC-Q35-ICH9-2009 opensearch-dashboards[822]: {"type":"response","@timestamp":"2023-11-07T06:15:26Z","tags":[
Nov 07 11:47:22 lab-Standard-PC-Q35-ICH9-2009 sudo[6064]:      lab : TTY=pts/0 ; PWD=/home/lab ; USER=root ; COMMAND=/bin/systemctl resta
Nov 07 11:47:22 lab-Standard-PC-Q35-ICH9-2009 sudo[6064]: pam_unix(sudo:session): session opened for user root by lab(uid=0)
Nov 07 11:47:22 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: Starting Wazuh manager...
-- Subject: Unit wazuh-manager.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit wazuh-manager.service has begun starting up.
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: ERROR: (1230): Invalid element in the config
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: ERROR: (1202): Configuration error at 'etc/o
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: 2023/11/07 11:47:23 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'et
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 env[6067]: wazuh-csyslogd: Configuration error. Exiting
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 systemd[1]: Failed to start Wazuh manager.
-- Subject: Unit wazuh-manager.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit wazuh-manager.service has failed.
--
-- The result is RESULT.
Nov 07 11:47:23 lab-Standard-PC-Q35-ICH9-2009 sudo[6064]: pam_unix(sudo:session): session closed for user root
Nov 07 11:47:26 lab-Standard-PC-Q35-ICH9-2009 systemd-timesyncd[565]: Timed out waiting for reply from [185.125.190.57:123](http://185.125.190.57:123/) ([ntp.ubuntu.com](http://ntp.ubuntu.com/)
Nov 07 11:47:37 lab-Standard-PC-Q35-ICH9-2009 systemd-timesyncd[565]: Timed out waiting for reply from [91.189.91.157:123](http://91.189.91.157:123/) ([ntp.ubuntu.com](http://ntp.ubuntu.com/))
Nov 07 11:47:44 lab-Standard-PC-Q35-ICH9-2009 sudo[6251]:      lab : TTY=pts/0 ; PWD=/home/lab ; USER=root ; COMMAND=/bin/systemctl statu
Nov 07 11:47:44 lab-Standard-PC-Q35-ICH9-2009 sudo[6251]: pam_unix(sudo:session): session opened for user root by lab(uid=0)
Nov 07 11:47:46 lab-Standard-PC-Q35-ICH9-2009 sudo[6251]: pam_unix(sudo:session): session closed for user root
Nov 07 11:47:47 lab-Standard-PC-Q35-ICH9-2009 systemd-timesyncd[565]: Timed out waiting for reply from [185.125.190.58:123](http://185.125.190.58:123/) ([ntp.ubuntu.com](http://ntp.ubuntu.com/)
Nov 07 11:47:57 lab-Standard-PC-Q35-ICH9-2009 systemd-timesyncd[565]: Timed out waiting for reply from [185.125.190.56:123](http://185.125.190.56:123/) ([ntp.ubuntu.com](http://ntp.ubuntu.com/)
Nov 07 11:47:59 lab-Standard-PC-Q35-ICH9-2009 sudo[6344]:      lab : TTY=pts/0 ; PWD=/home/lab ; USER=root ; COMMAND=/bin/journalctl -xe
Nov 07 11:47:59 lab-Standard-PC-Q35-ICH9-2009 sudo[6344]: pam_unix(sudo:session): session opened for user root by lab(uid=0)

Can anyone help me on the same?

**Comment by nmkoremblum** [comment]
Hi @thoufik786,

If you remove such a custom rules and decoders, does it start as expected?
