### ISSUE TITLE
Dynamic fields not working on list or field rule options

### ISSUE THREAD

**Issue by KALRONG** [wazuh/wazuh#201]
Hi,

Im using the latest Wazuh docker images and have been tryint to use CDB list to match md5 on files created on the hosts, im using a test cdb list like this:

8b6742f65664caabe5e3f2bef207fb31:malware

And Im doing test with this two rules:

```
<group name="attack,">
  <rule id="69001" level="15">
    <if_sid>554</if_sid>
    <list field="syscheck.md5_after" lookup="match_key">etc/lists/md5-keys</list>
    <description>New file matches malware IOC.</description>
    <group>malware,</group>
  </rule>
  <rule id="69002" level="16">
    <if_sid>554</if_sid>
    <field name="syscheck.md5_after">8b6742f65664caabe5e3f2bef207fb31</field>
    <description>File encrypted by ramsonware detected.</description>
  </rule>
</group>
```

First one is fort testing using the CDB and the second intended for a more direct approach.

None of this rules seems to work, but if I change the field/list option for a match one the alerts trigger. I actually tried a negative lookup but didn't trigger either.

After checking the code in rules.c looks like there are some differences between OSSEC and Wazuh and I was told that this exact rules work in OSSEC's current version.

First I thought it was an issue with the CDB but looks more like a problem with the rules being tested against dynamic field are just ignored or not working as expected.

I will keep providing more information as I discover new things, if anything else is needed, please, let me know.

Thanks in advance!

**Comment by albertomn86** [comment]
Hi @KALRONG ,

I've made an example using a CDB list to check if the MD5 belongs to a list of hashes. 
First of all I've made a CDB list with the list of MD5 hashes and I've compiled it using **ossec-makelist**.

_etc/lists/md5-keys_

> a992c07980ab70422c1f3e82a0517fff:

I've used the following rules:

```
<group name="attack,">
   <rule id="69001" level="15">
      <category>ossec</category>
      <decoded_as>syscheck_new_entry</decoded_as>
      <list field="md5" lookup="match_key">etc/lists/md5-keys</list>
      <description>New file matches malware IOC.</description>
      <group>malware,</group>
   </rule>
  
   <rule id="69002" level="15">
     <category>ossec</category>
     <decoded_as>syscheck_integrity_changed</decoded_as>
     <list field="md5" lookup="match_key">etc/lists/md5-keys</list>
     <description>New file matches malware IOC.</description>
     <group>malware,</group>
   </rule>
</group>
```

The field used is _'md5',_ corresponding to the field _'md5_before'_.

Then I've added a new file with the specified MD5 and I've obtained the expected alert:

> ** Alert 1506355643.224444: mail  - attack,malware,
> 2017 Sep 25 18:07:23 ubuntu->syscheck
> Rule: 69001 (level 15) -> 'New file matches malware IOC.'
> New file '/etc/malware' added to the file system.
> File: /etc/malware
> New size: 22
> New permissions: 100644
> New user: root (0)
> New group: root (0)
> New MD5: a992c07980ab70422c1f3e82a0517fff
> New SHA1: d37c3dcfad7da300115c78c5af6a5fa72e49fe94
> New date: Mon Sep 25 18:07:22 2017
> New inode: 804370


I hope it helps.

Regards.

**Comment by KALRONG** [comment]
Looks like the issue was with the field name, I have tested with just md5 and different rule configurations and is working like a charm. It would be great to have a list of fields used by syscheck on the documentation so we can create custom rules for them and avoid this kind of problems.

**Comment by albertomn86** [comment]
I’m glad I was able to help.
We will consider your suggestion about adding the list of fields used by syscheck on the documentation.

Best regards.
