### ISSUE TITLE
Increase of amplitude of fluctuation of Agentd in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20109]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh component | Agent | Packages | Centos, Windows, Ubuntu|

Testing  [ALL-EXCEPT-SCA (2.5d) ](https://github.com/wazuh/wazuh/issues/20067)

The following pattern could be found, where the amplitude of fluctuation in USS, RSS, PSS plots:

Centos Agent

<details>

RSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/db569c5c-27a8-41d0-a7e7-5a56bc120ddc)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/cd0cc8ef-1b79-47ea-ab10-6a4be2140647)

PSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/04a32418-53d4-4c72-917a-2e679834a83d)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/d077a4df-2790-47d1-9a32-3e972574898b)

USS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/142cf841-1e50-4873-9fcf-0f185c30b66f)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/356a8e6e-0d54-41a0-9e0d-179857f0b7ba)
</details>

Ubuntu Agent

<details>

RSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/795f5b7a-1ecb-40c7-8e19-b4807529240c)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/4c7c3475-2f0b-4c24-907e-fa16138dc223)

PSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067.
![image](https://github.com/wazuh/wazuh/assets/125690423/961033e1-320f-4f52-b90a-df92b3c25b1a)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/59d3d863-69ff-4c06-b737-4b447717ef98)

USS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/bc43bc12-038f-424d-9aa7-e10c11aa9af9)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/c2b83aa5-2c50-49ab-aa1a-5e60f7f3e53a)

</details>

Windows Agent

<details>

USS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/f5e09e21-e55e-4ef0-aedd-c5562c9084c8)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/dfcf1550-11b9-483f-b7e1-2be05e5fba14)

RSS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/eca7b0c6-d496-40b6-a975-36f8a564b668)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/e7a612aa-8f35-4892-b01d-45ef5d3f4761)

VMS
4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20067
![image](https://github.com/wazuh/wazuh/assets/125690423/c95a78ef-a22e-433d-9a83-004005dfc1e4)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5869
![image](https://github.com/wazuh/wazuh/assets/125690423/cfd267cd-361e-4878-8687-e78505e74549)

</details>

**Comment by vikman90** [comment]
The memory peaks (memory required) are lower in 4.7 than in 4.6. The amplitude is not relevent.
