### ISSUE TITLE
Deprecate API /vulnerability endpoints

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20115]
## Description

This issue aims to mark as deprecated the endpoint `PUT /vulnerability` and all other vulnerability endpoints. 

The reason behind this is the [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153) that will change the module's behavior by doing unnecessary keep this endpoint.

In 4.8.0, we'll remove the code and references.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Deprecated `/vulnerability` endpoints and their RBAC resources in the documentation.

**Comment by RamosFe** [comment]
LGTM!

**Comment by GGP1** [comment]
## Update

Executed the AIT using the 4.7.0 jenkins shared library and rebased the documentation PR to 4.8.0
