### ISSUE TITLE
Decrease of number of Agentd_number_of_events_buffered fluctuations density in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20117]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | Wazuh | Agent | Packages | CentOS, Ubuntu, Windows |

Different density in the number of fluctuations of Agentd_number_of_events_buffered in all the agents in test: [Footprint Metrics - LOGCOLLECTOR,SCA (2.5d)](https://github.com/wazuh/wazuh/issues/20064)

CentOS

<details>

4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20064
![image](https://github.com/wazuh/wazuh/assets/125690423/a2e07051-4166-45d8-97e4-4db5fdec40e3)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5865
![image](https://github.com/wazuh/wazuh/assets/125690423/cc48ce7d-4020-4ded-a7e9-e081c8b7f93e)

</details>

Ubuntu

<details>

4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20064
![image](https://github.com/wazuh/wazuh/assets/125690423/67f3d64e-814e-44f4-909c-8cdab8e0965a)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5865
![image](https://github.com/wazuh/wazuh/assets/125690423/99ca3704-11dc-4461-9e7b-53c69239f150)

</details>

Windows

<details>

4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20064
![image](https://github.com/wazuh/wazuh/assets/125690423/452e1b96-3cad-49af-9e7a-e00a4a16f17f)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5865
![image](https://github.com/wazuh/wazuh/assets/125690423/5da89bfc-f744-4d0d-b526-6bc829ab8205)

</details>

**Comment by pro-akim** [comment]
It could be related to: https://github.com/wazuh/wazuh/issues/20113

**Comment by pro-akim** [comment]
## Update

In https://github.com/wazuh/wazuh/issues/20056
It could be found the same pattern, however, different ranges of fluctuations were found at the initial and final stage of the test.

- https://github.com/wazuh/wazuh/issues/20056
![image](https://github.com/wazuh/wazuh/assets/125690423/bf4fa7b2-344c-4952-baa3-a20d4d3a0733)

- https://github.com/wazuh/wazuh-jenkins/issues/5876
![image](https://github.com/wazuh/wazuh/assets/125690423/af2588eb-032f-4234-bb9d-e830694bce7f)

**Comment by JorgeMarinoDev** [comment]
After discussing with the team, we've found this issue related to [AgentD_Number_of_events_buffered fluctuations has fluctuations between almost fixed values in stress test #20113 ](https://github.com/wazuh/wazuh/issues/20113). 

There was a major change in 4.7.0 regarding agent's buffer behavior [16346](https://github.com/wazuh/wazuh/pull/16346).

To avoid redundancy, we can link this issue to this [analysis](https://github.com/wazuh/wazuh/issues/20113#issuecomment-1802697117).
