### ISSUE TITLE
CPU usage decrease in the Syscheck stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#20120]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2 | wazuh-syscheckd<br>wazuh-agentd | Agent | Packages | Ubuntu 20<br>Windows 2019 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20060, a decrease in CPU usage has been detected in Ubuntu and Windows agents

In the Ubuntu agent, it has been detected that the CPU usage has had drops in usage during the first and third phases, from 100% to ~25%, no drop in usage has been observed during the second phase of the test

![image](https://github.com/wazuh/wazuh/assets/14913942/7f3e539d-004f-4a20-8870-abb26e910a7e)
![image](https://github.com/wazuh/wazuh/assets/14913942/2f8ae777-5670-4ab9-975c-31bb7f6a145e)

These decreases in usage can be seen in the FD plot

![image](https://github.com/wazuh/wazuh/assets/14913942/8149556c-a5d0-4c9f-92c1-395041c64e28)

In the case of the Windows agent, it can be seen that CPU usage decreased significantly during the second phase of the test, barely showing a difference in usage between the other phases.

![image](https://github.com/wazuh/wazuh/assets/14913942/6c6f2c45-f1e9-4fd8-8e94-aba41afb54b5)
![image](https://github.com/wazuh/wazuh/assets/14913942/d8ee792c-930d-4a81-bf90-c7943abeb835)

Previous tests show more intensive CPU usage in Windows

![image](https://github.com/wazuh/wazuh/assets/14913942/b5b7b955-a7ce-4baa-a08c-5e86303b7073)

**Comment by cborla** [comment]
## Analysis

It remains to be analyzed why the test exceeds the value 100, when we are talking about percentages

Anyway, making a graphical comparison of the 2 versions, 4.6.0 and 4.7.0, we can clearly see the release of CPU by the syscheck module in version 4.7.0.

### Data CPU compare

|Version|CPU time|Average|Max|
|---|---|---|---|
|[4.6.0-rc2](https://github.com/wazuh/wazuh/issues/19891)|2027.98 sec |5.59 %|63.90 %|
|[4.7.0-alpha2](https://github.com/wazuh/wazuh/issues/20060)|1938.30 sec. ⬇️|4.99 % ⬇️|22.00 % ⬇️|

The percentage of cpu usage differs by 0.6 % between versions. This is not a cause for concern.
To my understanding this may be related to [the way in which the buffered events are being managed,](https://github.com/wazuh/wazuh/pull/16346) in 4.7.0 a new way of control was implemented, in the graphs of buffered events you can see moments without events, in which it can be presumed that they are idle moments for the cpu.

**Comment by vikman90** [comment]
@cborla I agree, the difference from 4.6 to 4.7 is 4.4%. There is no reason to worry here.
