### ISSUE TITLE
CIS-CAT is not saving results into the table ciscat_results of the DB

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2012]
The events of CIS-CAT are not being decoded with the [CIS-CAT decoder](https://github.com/wazuh/wazuh/blob/v3.6.1/src/analysisd/analysisd.c#L800). This decoder is missing in the last version of `analysisd` and because of this, the results are not being saved into the DB.

Regards,
Cerv1.

**Comment by snaow** [comment]
Fixed here: https://github.com/wazuh/wazuh/pull/2014
Pending for further releases: Create a custom thread for decoding CIS-CAT events.
