### ISSUE TITLE
Fix code scanning alert - Call to requests with verify=False disabling SSL certificate checks, security issue.

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20127]
Tracking issue for:
- [ ] https://github.com/wazuh/wazuh/security/code-scanning/2499

**Comment by GGP1** [comment]
There is an issue in pending review that addresses this https://github.com/wazuh/wazuh/issues/19604

**Comment by nico-stefani** [comment]
Already fixed in #19604
