### ISSUE TITLE
Significant increase of Agentd Write_Ops in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20124]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-alpha2| Wazuh | Agent | Packages| Ubuntu/Centos |

Working in [Footprint Metrics - LOGCOLLECTOR,SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/20063), the following patterns of Write_Ops be found where Agentd increased its use significantly.

Centos
<details>

4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20063
![image](https://github.com/wazuh/wazuh/assets/125690423/48501043-8dff-4dce-a56a-46647ce699d4)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5872
![image](https://github.com/wazuh/wazuh/assets/125690423/343c5414-ce70-4b2b-8305-4d958471bcf7)

</details>

Ubuntu
<details>

4.7.0-alpha2 https://github.com/wazuh/wazuh/issues/20063
![image](https://github.com/wazuh/wazuh/assets/125690423/d10a98aa-e96b-4e99-80bf-4d8b2e29b5ea)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5872
![image](https://github.com/wazuh/wazuh/assets/125690423/a0857122-cbcc-4286-83aa-924c0f6eada7)

</details>

Further research should be done

**Comment by nmkoremblum** [comment]
The increase in the Write Operations comes with the increase in the amount of generated events and messages, which should be obvious at this point. I do not find such a situation wrong, on the contrary, a higher number of generated events/messages may indicate a better performance of the agents than in previous versions.

**Comment by nmkoremblum** [comment]
### Ubuntu
| Metric                    | 4.6.0 | 4.7.0 | Percentage Variation |
|---------------------------|-------------|-------------|-----------------------|
| Write Ops                 | 4.1e6       | 8e6         | +95.12%               |
| Agentd Generated Events   | 6.5e7       | 6.1e7       | -6.15%                |
| Agentd Number of Messages | 4e6         | 7.6e6       | +90.00%               |
### CentOS
| Metric                    | 4.6.0 | 4.7.0 | Percentage Variation |
|---------------------------|-------------|-------------|-----------------------|
| Write Ops                 | 3.5e6       | 8e6         | +128.57%              |
| Agentd Generated Events   | 4.1e7       | 4.7e7       | +14.63%               |
| Agentd Number of Messages | 3.25e6      | 7.6e6       | +134.62%              |

**Comment by cborla** [comment]
The agent conditions have changed with respect to 4.6.0, the comparison is not quite correct, this behavior will be analyzed in the next stress test of 4.7.0.
