### ISSUE TITLE
Wazuh agents uninstalled when updating to v4.6.0 using GPO

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#20138]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.6.0| Windows upgrade| Agent | GPO | Windows 10 / Windows 11 |

After the 4.6.0 release, a user at the [Wazuh mailing list](https://groups.google.com/g/wazuh/c/kXOGg9nB3KY/m/2AbFEFJfBQAJ) reported that when trying to upgrade the Wazuh agents to 4.6.0 all agents were uninstalled.

The OP reported the following versions:
- `Windows 10 (10.0.19045.xxxx)`
- `Windows 11 (10.0.22621.xxxx)`

Weeks ago he installed the Wazuh agents using GPO and everything worked properly.

After discussing the issue with the team, it was suggested that perhaps a rollback was attempted and if the hosts were rebooted at that moment, the Wazuh agent may end up being uninstalled.

This behavior has not been reproduced, it is only a possible assumption.

**Comment by ncvicchi** [comment]
Changed ETA waiting for external response

**Comment by lchico** [comment]
# Update:

I responded to the community on the [mailing list](https://groups.google.com/g/wazuh/c/kXOGg9nB3KY/m/2AbFEFJfBQAJ), asking for information that might explain the uninstall during the upgrade. One of the package properties is 'Uninstall this application when it falls out of the scope of management configuration,' and this option is checked. (In my configuration, which I attached, I don't have it selected.)

![Screenshot from 2024-01-30 12-00-09](https://github.com/wazuh/wazuh/assets/21695385/05a10f1f-0289-4220-b29e-853e2b7b9403)

To verify this, should go to your Group Policy and edit it:

`Computer Configuration -> Software Settings -> Software Installation -> Wazuh agent (the upgrade one) -> go to Properties -> Deployment`

**Comment by MarcelKemp** [comment]
Since the user does not reply, and we do not have enough information to know what happened, nor any way to replicate it, I am closing the issue.

If the problem reoccurs, please feel free to reopen this issue.
