### ISSUE TITLE
local_rules rules referencing rules in other custom rule files in if_sid does not work

### ISSUE THREAD

**Issue by dominictory** [wazuh/wazuh#20146]
| v4.5.2 | Rules | Error |

## Description

When creating rules in `local_rules.xml` that use custom rules in other files (in `/var/ossec/etc/rules`) for `if_sid`, the rules do not work and we see the following `analysisd` errors:

```
2023/10/31 11:21:29 wazuh-analysisd: WARNING: (7617): Signature ID '101214' was not found and will be ignored in the 'if_sid' option of rule '100003'.
2023/10/31 11:21:29 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '100003' will be ignored.
```

101214 is a custom rule in our custom Sysmon rules file, and 100003 is a rule in `local_rules.xml`, using 101214 in the `if_sid`, to create an override of the custom rule. Using `overwrite` unfortunately does not solve this:

```
2023/11/08 15:12:03 wazuh-analysisd: WARNING: (7613): Rule ID '101214' does not exist but 'overwrite' is set to 'yes'. Still, the rule will be loaded.
2023/11/08 15:12:03 wazuh-analysisd: WARNING: (7612): Rule ID '101214' is duplicated. Only the first occurrence will be considered.
```

We see no issue with the rule file permissions, as the custom rule files do match appropriately and generate alerts.

We create custom rule files on Github, and use git pull to add them across our many client Wazuh instances. When we want to create overrides on specific clients for our custom rules, we want to use local_rules on that client to override the custom rule rather than editing it globally, particularly when it only applies to a single client (e.g. they use a custom script that is triggering a high enough alert to send an email alert to the client).

### Service/Product/Module

None in particular, happens when referencing any rule in a custom rule file.

### Current results

```
2023/10/31 11:21:29 wazuh-analysisd: WARNING: (7617): Signature ID '101214' was not found and will be ignored in the 'if_sid' option of rule '100003'.
2023/10/31 11:21:29 wazuh-analysisd: WARNING: (7619): Empty 'if_sid' value. Rule '100003' will be ignored.
2023/11/08 15:12:03 wazuh-analysisd: WARNING: (7613): Rule ID '101214' does not exist but 'overwrite' is set to 'yes'. Still, the rule will be loaded.
2023/11/08 15:12:03 wazuh-analysisd: WARNING: (7612): Rule ID '101214' is duplicated. Only the first occurrence will be considered.
```

### Expected results

Child rule using custom rule as parent should mean child rule takes precedence in rule order.

### Log source / integration

Example shows a custom Sysmon rule, however any custom rule can be used.

**Comment by dominictory** [comment]
![image](https://github.com/wazuh/wazuh/assets/124377454/5775a007-d050-4298-823b-0546029f05a5)

We were able to change some custom rules to be overwritten default rules, however we cannot do this with all custom rules so the issue still stands for us.

**Comment by nmkoremblum** [comment]
Hi @dominictory,

Could you please share with us the custom rules and decoders that you have designed? And please specify in which file you have included them with its relative directory to the `ossec` path

**Comment by dominictory** [comment]
> Hi @dominictory,
> 
> Could you please share with us the custom rules and decoders that you have designed? And please specify in which file you have included them with its relative directory to the `ossec` path

No custom decoder here, just using the existing Windows event channel logging for Sysmon events. We have a `sysmon_rules.xml` file located in `/var/ossec/etc/rules/sysmon_rules.xml`. We created our own rules based on [these rules](https://github.com/socfortress/Wazuh-Rules/blob/main/Windows_Sysmon/100100-MITRE_TECHNIQUES_FROM_SYSMON_EVENT1.xml).

**Comment by nmkoremblum** [comment]
Hi @dominictory,

I am sorry for the delay, please share with us your custom rules

**Comment by dominictory** [comment]
> Hi @dominictory,
> 
> I am sorry for the delay, please share with us your custom rules

Absolutely, parent rule I wish to reference, located in `/var/ossec/etc/rules/sysmon_rules.xml`:

```
<rule id="101214" level="13">
    <if_sid>61603</if_sid>
    <field name="win.eventdata.image">powershell.exe$|pwsh.exe$</field>
    <field name="win.eventdata.commandLine">ExecutionPolicy Bypass</field>
    <description>Sysmon - Event 1: PowerShell Execution Policy Bypass detected.</description>
    <mitre>
      <id>T1548</id>
      <id>T1059</id>
    </mitre>
    <options>no_full_log</options>
    <group>sysmon_event1,windows_sysmon_event1,sysmon_anomaly,</group>
</rule>
```

Rule example in `/var/ossec/etc/local_rules.xml`:

```
<rule id="100001" level="13">
    <if_sid>101214</if_sid>
    <field name="win.eventdata.image">powershell.exe$|pwsh.exe$</field>
    <field name="win.eventdata.commandLine">ExecutionPolicy Bypass</field>
    <field name="win.eventdata.parentImage" negate="yes">wazuh-agent.exe$</field>
    <description>Sysmon - Event 1: PowerShell Execution Policy Bypass detected.</description>
    <mitre>
      <id>T1548</id>
      <id>T1059</id>
    </mitre>
    <options>no_full_log</options>
    <group>sysmon_event1,windows_sysmon_event1,sysmon_anomaly,</group>
</rule>
```

I'm aware I could exclude certain images in Sysmon config rather than rules, however this would be difficult to roll out to our clients in a timely manner.

**Comment by nmkoremblum** [comment]
The rule `101214` you are referencing is not part of our default ruleset, so it was probably manually added. I would suggest moving the custom rules to `/var/ossec/etc/rules/` and modifying the rule IDs so that the father rule has a lower ID than its child (the one that invokes the `ìf_sid`)

**Comment by dominictory** [comment]
> The rule `101214` you are referencing is not part of our default ruleset, so it was probably manually added. I would suggest moving the custom rules to `/var/ossec/etc/rules/` and modifying the rule IDs so that the father rule has a lower ID than its child (the one that invokes the `ìf_sid`)

Correct, these are custom rules, which appears to be what is causing the issue. As stated above, all are located in `/var/ossec/etc/rules/`. I have tried setting the child rule to a higher rule ID, however the same issue occurred.

**Comment by nmkoremblum** [comment]
Are you sure there are no other errors apart from the one that you have shared before?

**Comment by dominictory** [comment]
> Are you sure there are no other errors apart from the one that you have shared before?

Yes, we only get an error stating that the `if_sid` cannot be found. This was replicated by Nazmur Sakib in the screenshot above.

**Comment by nmkoremblum** [comment]
Alright, I conducted some tests on my local machine, and it appears that the issue is linked to the order in which the files are being loaded. Best practice dictates grouping related rules within the same file. Hence, there are two potential solutions. First, consider renaming the file to ensure it appears alphabetically before the 'local rules' file. This can be achieved by starting its name with a number or any letter between 'a' to 'k'. Alternatively, another approach would be consolidating all the rules into a single file and organizing them based on their IDs.

**Comment by dominictory** [comment]
> Alright, I conducted some tests on my local machine, and it appears that the issue is linked to the order in which the files are being loaded. Best practice dictates grouping related rules within the same file. Hence, there are two potential solutions. First, consider renaming the file to ensure it appears alphabetically before the 'local rules' file. This can be achieved by starting its name with a number or any letter between 'a' to 'k'. Alternatively, another approach would be consolidating all the rules into a single file and organizing them based on their IDs.

Much appreciated. Conversely, if we rename `local_rules.xml` such that it appears last in the list, will this resolve potential issues with other custom rule files?

**Comment by nmkoremblum** [comment]
It should, just be careful that no other rules on such a file are affected

**Comment by dominictory** [comment]
> It should, just be careful that no other rules on such a file are affected

Thanks, renaming `local_rules.xml` to `zzz_local_rules.xml`, thus putting it at the bottom, allows it to see our other custom rule files and we no longer get the error.
