### ISSUE TITLE
Investigate failure in integration tests for API 

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20172]
## Description

Developing #18725 we found some errors in the [Integration tests for API](https://github.com/wazuh/wazuh/actions/workflows/integration-tests-api-tier-0-1.yml) pipeline.

We need to investigate the problem and fix it. Here is an example of the failure:

```
ValueError: Error when executing restart in daemon None. Exit status: 1
```

* https://github.com/wazuh/wazuh/actions/runs/6801939072/job/18493891975

The changes introduced in [dev-14153-vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor) could be one of the reasons.

**Comment by Selutario** [comment]
Delaying ETA to Nov 20. Reason:
- The reviewer is out of office.
