### ISSUE TITLE
Indexer Connector - Understanding the module

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#20175]
|Component|
|---|
| [indexer_connector](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/indexer_connector) |

## Description

The objective of this issue is to understand how the module works and to see what changes are necessary for its correct operation.

## Expected

- Understand how the module works
- Identify what changes are necessary for the module to work properly
- Propose improvements if any

**Comment by kevin-mcm** [comment]
## Update API used by [Monitoring.h](https://github.com/wazuh/wazuh/blob/8eafaec2d53df81289b744eb394804a3498a7a0a/src/shared_modules/indexer_connector/src/monitoring.hpp#L119)
Currently, the indexer connector is not correctly using the `_cat/health` API, the `_cat/health?v` API should be used instead
```shell
curl -XGET http://192.168.40.128:9300/_cat/health
1700077329 19:42:09 opensearch-cluster green 2 2 true 11 6 0 0 0 0 - 100.0%
```
```shell
curl -XGET http://192.168.40.128:9200/_cat/health?v
epoch      timestamp cluster            status node.total node.data discovered_cluster_manager shards pri relo init unassign pending_tasks max_task_wait_time active_shards_percent
1700075000 19:03:20  opensearch-cluster green           2         2                       true     10   5    0    0        0             0                  -                100.0%
```

## OpenSearch Authentication 

Add authentication to the [Monitoring class](https://github.com/wazuh/wazuh/blob/8eafaec2d53df81289b744eb394804a3498a7a0a/src/shared_modules/indexer_connector/src/monitoring.hpp#L66) using the [SecureCommunication](https://github.com/wazuh/wazuh-http-request/blob/39ec8537e59348a47c43132427e3f53a098cb96b/include/secureCommunication.hpp#L31) from the [wazuh-http-request](https://github.com/wazuh/wazuh-http-request/tree/dev-14153-vulndet-refactor) library.

**Comment by kevin-mcm** [comment]
# Observations and improvements 

1. Refactor functions and classes.
2. Implement unit tests for the module's classes and functions.
3. Verify the availability of nodes/servers at the module's initiation. Currently, it is assumed that all nodes/servers are available before the monitoring interval. Consider adding a retry mechanism to check the status of nodes/servers at the module's startup, with a specified number of attempts.
4. Add a mechanism to preserve data when no nodes/servers are available.

**Comment by Damian-Mangold** [comment]
Thank you for the analysis, Kevin. We will look into the proposed improvements.
