### ISSUE TITLE
Logcollector prevents vmhgfs from synchronizing the inode

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2018]
|Branch|
|---|
|[3.7-logcollector-force-reload](https://github.com/wazuh/wazuh/compare/3.7...3.7-logcollector-force-reload)|

Logcollector periodically performs file and size checkings for every monitored file. It the daemon detects that the file was reduced or rotated, it reloads the file.

The vmhgfs file system (for VMware shared folders) synchronizes the file inode number from the host to the guest, but it can only do that if no process has the file open. In other words, Logcollector prevents the file system from updating the file inode.

If Logcollector is monitoring a file in a shared folder, and that file is rotated —replaced by another file with the same name— in the host machine, the vmhgfs file system can't update the inode number, then Logcollector does not detect the file rotation.

## Proposed fix

We should introduce a feature in Logcollector that forces file reloading although no size or inode change is detected. This feature may be switched by a global option, like:

### `logcollector.force_reload`

|Allowed values|Default value|
|---|---|
|`0` (disabled) and `1` (enabled)|`0` (disabled)|

### `logcollector.reload_interval`

File reloading interval, in seconds.

|Allowed values|Default value|
|---|---|
|Any integer between `1` (second) and `86400` (one day).|`60` (one minute)|

#### Conditions 

- This parameter only applies if `force_reload` is set to `1`.
- `reload_interval` must be greater or equal than `vcheck_files`.

### `logcollector.reload_delay`

File reloading delay (between close and open), in milliseconds.

|Allowed values|Default value|
|---|---|
|`0` (disabled) .. `30000` (half a minute)|`1000` (one second)|

## Notes

If Logcollector performs a file reloading, it should also re-check the inode number. If the inode has changed now, Logcollector should report that the file has been rotated.

**Comment by irctrakz** [comment]
The frequency of the reload should be independently configurable, so as to help avoid continual file reloading - a resource expensive task.

Additionally, the position of the file needs to be maintained across reload, to avoid re-processing the same data over and over.

**Comment by snaow** [comment]
Final implementation can be found here https://github.com/wazuh/wazuh/pull/2022

As `internal_options.conf` shows, default assigned related values are:

```
# Logcollector file loop timeout (check every 2 seconds for file changes)
logcollector.loop_timeout=2

# Logcollector - File checking interval (seconds) [0..1024]
logcollector.vcheck_files=64

# Logcollector - Maximum number of lines to read from the same file [1..1000000]
# 0. Disable line burst limitation
logcollector.max_lines=10000

# Force file handler reloading: close and reopen monitored files
# 0: Disabled
# 1: Enabled
logcollector.force_reload=0

 # File reloading interval, in seconds, if force_reload=1 [1..86400]
# This interval must be greater or equal than vcheck_files.
logcollector.reload_interval=64

 # File reloading delay (between close and open), in milliseconds [0..30000]
logcollector.reload_delay=1000
```

The default values set a read limit of 5000 lines per second and 64 seconds wait until the file is reloaded.
Please, adjust the values according to each use case, it is recommended to decrease the reload time if the log files grow fast.
