### ISSUE TITLE
Wazuh Docker behind Traefik

### ISSUE THREAD

**Issue by bremoi** [wazuh/wazuh#20183]
Hi,

I'm not able to deploy Wazuh behind Traefik Proxy.
I tried at first to expose through Traefik only the dashboard (port 5601) and it doesn't work.

Regards

**Comment by Brettdah** [comment]
Hello there,
Can you share your configuration ?
Like your docker-compose.yml or traefik dynamic config for this app ? 
Without context it will be a bit hard to help you ;)

best regards

**Comment by bremoi** [comment]
Hi @Brettdah,

You are right :)

# Portainer.yml
command:
  - --entrypoints.wm1514.address=:1514
  - --entrypoints.wm1515.address=:1515
  - --entrypoints.wm514.address=:514/udp
  - --entrypoints.wm55000.address=:55000
  - --entrypoints.wi9200.address=:9200
  - --entrypoints.wd5601.address=:5601
ports:
  - "1514:1514"
  - "1515:1515"
  - "514:514/udp"
  - "55000:55000"
  - "9200:9200"
  - "5601:5601"

# Wazuh.yml
version: '3.7'
services:
  wazuh-manager:
    image: wazuh/wazuh-manager:4.6.0
    hostname: wazuh.manager
    [...]
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.wm1514.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.tcp.routers.wm1514.entrypoints=wm1514"
      - "traefik.tcp.services.wm1514.loadbalancer.server.port=1514"
      - "traefik.tcp.routers.wm1514.service=wazuh-manager"
      - "traefik.tcp.routers.wm1515.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.tcp.routers.wm1515.entrypoints=wm1515"
      - "traefik.tcp.services.wm1515.loadbalancer.server.port=1515"
      - "traefik.tcp.routers.wm1515.service=wazuh-manager"
      - "traefik.udp.routers.wm514.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.udp.routers.wm514.entrypoints=wm514"
      - "traefik.udp.services.wm514.loadbalancer.server.port=514"
      - "traefik.udp.routers.wm514.service=wazuh-manager"
      - "traefik.http.routers.wm55000.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.http.routers.wm55000.entrypoints=wm55000"
      - "traefik.http.services.wm55000.loadbalancer.server.port=55000"
      - "traefik.http.routers.wm55000.service=wazuh-manager"
    networks:
      - traefik
      - wazuh

  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.6.0
    hostname: wazuh.indexer
    [...]
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wi9200.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.http.routers.wi9200.entrypoints=wi9200"
      - "traefik.http.services.wi9200.loadbalancer.server.port=9200"
      - "traefik.http.routers.wi9200.service=wazuh-indexer"
    networks:
      - traefik
      - wazuh

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.6.0
    hostname: wazuh.dashboard
    [...]
    deploy:
      mode: replicated
      replicas: 1
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wd5601.rule=Host(`wazuh.xxxx.tld`)"
      - "traefik.http.routers.wd5601.entrypoints=wd5601"
      - "traefik.http.services.wd5601.loadbalancer.server.port=5601"
      - "traefik.http.routers.wd5601.service=wazuh-dashboard"
    depends_on:
      - wazuh-indexer
      - wazuh-manager
    networks:
      - traefik
      - wazuh
[...]

Thanks in advance.

Regards

**Comment by bremoi** [comment]
Hi,

During troubleshooting, it appears into Traefik the following error.
```
the service "wazuh-dashboard@docker" does not exist
```

Thanks in advance.

Regards

**Comment by Brettdah** [comment]
So first I'm not using portainer yet (it's planned, more or less, but I need an upgrade on the hardware side)
so I will try to help with your configuration.
I thinck the first thing I would rule out is a wazuh problem :

- Did you try to by pass traefik to look at your app state ?
for exemple by opening a port on your config so you can access it by `https://IP:Port`

on the dashboard you can do
```yml
wazuh-dashboard:
  ports:
    - 8085:3000
  [...]
```

> Then you can join the wazuh service on the port 8085 (you should be able to put any port greater than 1024.
> If you are using it on an online host (in contrast of in your home / internal network) be sure to only othorise you, yourself and only your IP to access this port ;)
> Or  shut down the app after you saw it's online and working (meaning try a connexion there are few tests that will be executed everything should be checked with a green "V"ish symbol) ;) 

Usualy when I do that I'm using a static configuration for traefik instead of labels I can show you that part later if ever there is still something wrong after checking a few more things ;)

Ok it's not started / not green ?

Did you look on the wazuh-[indexer/manager/dashboard] container logs ?
Or if the wazuh indexer and manager are ready ?

wazuh-indexer should return :

``` bash
curl  https://localhost:9200/_cluster/health?pretty -k -u admin:@no7h3r$3cr37P@$$w0rdTh@tID0N07U$e
{
  "cluster_name" : "opensearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 66,
  "active_shards" : 66,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```
> number may change what's important is the **"status": "green"**


`docker container logs wazuh-manager-1`  

> wazuh-manager-1 Or whatever is your manager name
> Look for any ERROR or FATAL

```bash
docker container logs wazuh-manager-1 > ~/manager.log
cat ~/manager.log | grep -v INFO
```

> Logs now displayed should realy mater or be the container "OS" logs

At first I had many errors there about certificates not matching or  indexer unreachable things like that

Oh and another thing I saw you are using dash naming (wazuh-[indexer/manager/dashboard]
In my configuration I had to edit a file in the dashboard container : 
**data/wazuh/config/wazuh.yml**
the line URL seems hard coded so I edited it relacing the dot by a dash

```yml
hosts:
  - 1513629884013:
      url: "https://wazuh-manager"
      port: 55000
      username: wazuh-wui
      password: "My$up3r$7r0nGP@$$w0rd!"   # <-- just in case this is not my real password ^^
      run_as: false
```
it was this:
url: "https://wazuh.manager"
that I replaced by that:
url: "https://wazuh-manager"

now every thing seems to work perfectly... exept some benchmark comparison that should give a green light when I use my eyes and that are still failed, and before you ask other failed at first are going green when I apply the remediation. But, apart from that, on my side and using it localy without traefik, for now, everything seems to work !

So here are some investigation roads hope that will help :)

**Comment by LaancX** [comment]
So I am having the same error and following this thread and some tips I got some more extra information.

I will share my compose here as well:

[...] - Manager
ports:
      - "1514"
      - "1515"
      - "514/udp"
      - "55000"
[...]

[...] - Indexer
ports:
      - "9200"
[...] 

[...] - Dashboard
ports:
      - "5601:5601"
labels:
      - "traefik.enable=true"
      - "traefik.http.services.wazuh-dashboard.loadbalancer.server.port=5601"
                              #-------- Secure --------
      - "traefik.http.routers.wazuh-dashboard-secure.rule=Host(`wazuh.${DOMAIN}`)"
      - "traefik.http.routers.wazuh-dashboard-secure.entrypoints=websecure"
      - "traefik.http.routers.wazuh-dashboard-secure.tls=true"
      - "traefik.http.middlewares.wazuh-dashboard-https-redirect.redirectscheme.scheme=https"

[...]

I cannot access the container when I omit the port on the host. My webpage shows "bad gateway" (https://wazuh.{domain})

If I try to access through the port on the host (https://10.0.0.3:5601) I get the Wazuh dashboard, just fine.

My access log doesn't help that much as well. When requesting the page I get:
10.0.0.77 - - [11/Dec/2023:20:28:13 +0000] "GET / HTTP/2.0" 502 11 "-" "-" 368 "wazuh-dashboard-secure@docker" "http://172.22.0.19:5601" 4ms

I think we do not need to expose the ports on the indexer and manager to get traefik working

For what I could think is that traefik is requesting the wazuh on http://172.22.0.19:5601 but wazuh only responds on https. 
Issuing the command curl inside the host I get:
curl: (52) Empty reply from server

**Comment by LaancX** [comment]
Howdy.

I was testing my hypothesis today and I kinda got it to work properly.

You just need to add the server url on the traefik dynamic config to recognize the https call

``` yaml
services:
    wazuh-dashboard:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://172.22.0.19:5601" # This is my wazuh server, you should change to reflect yours
```

**Comment by bremoi** [comment]
Hi @Brettdah,

Thanks a lot for all your explainations. Unfortunately it doesn't still work. I have "404 page not found" when I try to reach Wazuh dashboard through Treafik.
I'm able to bypass Traefik and in this case Wazuh works.
The wazuh-indexer logs return "status:green" and the wazuh-manager logs return no ERROR or FATAL.

@LaancX thanks for you comment, but it also doesn't work. You are exposing Wazuh without passing through Traefik, so I'm not sure your configuration is working through Treafik. Also, it is necessary to expose at least the manager through Traefik for agent communication.

Hope we'll find the problem :)

Regards.

**Comment by LaancX** [comment]
> Hi @Brettdah,
> 
> Thanks a lot for all your explainations. Unfortunately it doesn't still work. I have "404 page not found" when I try to reach Wazuh dashboard through Treafik. I'm able to bypass Traefik and in this case Wazuh works. The wazuh-indexer logs return "status:green" and the wazuh-manager logs return no ERROR or FATAL.
> 
> @LaancX thanks for you comment, but it also doesn't work. You are exposing Wazuh without passing through Traefik, so I'm not sure your configuration is working through Treafik. Also, it is necessary to expose at least the manager through Traefik for agent communication.
> 
> Hope we'll find the problem :)
> 
> Regards.

On my first compose I purposely exposed wazuh to investigate if the application was working just as expected, and it did. On my second reply, my wazuh was not exposed anymore but I could reach it through traefik. 

It seems your error is related to the network and not the config. If you visit the traefik dashboard, can you see the HTTP router and HTTP service of the wazuh container? 

My suggestion is to enable the [access log](https://doc.traefik.io/traefik/observability/access-logs/#configuration) on traefik to investigate further.

After that:` docker logs -f <traefik_container>` and try to request wazuh to see what is going on.

Let me know what you got

**Comment by Brettdah** [comment]
@bremoi :
so if everything is green wazuh side it may be traefik side like @LaancX said a problem with the network.
if you go in your traefik container :

# display your running containers
docker container ls
# inter Traefik container
docker exect -it <ID or name of traefik container> /bin/sh

can ping your wazuh container ?
ping <CompleteName of wazuh-dashboard container>

on my side when I try to ping the container name of a  db  (that traefik should not be able to access :
ping: bad address 'stack-app_db'

Otherwise with the short name I can ping an IP and the long another one...
> I am using docker swarm so as far as I know the name parameter is not used
> **long name** = stack-name_service.#.ID
> **short name** = stack-name_service
> - stack-name: is given by the cmd docker stack deploy -c compose-file.yml <stack-name>
> - service: is writen in the compose file
> - # : number of the container meaning if your have more than one you can have 1 to n
> - ID: If I understand correctly swarm is giving an ID to identify the container more precisely...

I tryed to curl on the `container-name:port#` but it does not seems to workl (may be my security is triggered like I should try to authenticate my self on authelia before... I'm trying to investigate... I think we should be able to have curl say Ok I can join the website or no...

**Comment by bremoi** [comment]
Hi,

I have no more the error message from Traefik by changing the Traefik service name (wd5601) with the same container name (wazuh-dashboard).
```
labels:
  - "traefik.enable=true"
  - "traefik.http.routers.wazuh-dashboard.rule=Host(`wazuh.xxxx.tld`)"
  - "traefik.http.routers.wazuh-dashboard.entrypoints=wd5601"
  - "traefik.http.services.wazuh-dashboard.loadbalancer.server.port=5601"
  - "traefik.http.routers.wazuh-dashboard.service=wazuh-dashboard"
```

Unfortunately I have "404 page not found" and the following doesn't take effect.
`- "traefik.http.services.wazuh-dashboard.loadBalancer.servers.url=https://wazuh.dashboard:5601"`

**Comment by LaancX** [comment]
> Hi,
> 
> I have no more the error message from Traefik by changing the Traefik service name (wd5601) with the same container name (wazuh-dashboard).
> 
> ```
> labels:
>   - "traefik.enable=true"
>   - "traefik.http.routers.wazuh-dashboard.rule=Host(`wazuh.xxxx.tld`)"
>   - "traefik.http.routers.wazuh-dashboard.entrypoints=wd5601"
>   - "traefik.http.services.wazuh-dashboard.loadbalancer.server.port=5601"
>   - "traefik.http.routers.wazuh-dashboard.service=wazuh-dashboard"
> ```
> 
> Unfortunately I always have "404 page not found" and the "servers.url" `- "traefik.http.services.wazuh-dashboard.loadBalancer.servers.url=https://wazuh.dashboard:5601"` doesn't take effect.
> 
> ```
> labels:
>   - "traefik.enable=true"
>   - "traefik.http.routers.wazuh-dashboard.rule=Host(`waz.xxxx.tld`)"
>   - "traefik.http.routers.wazuh-dashboard.entrypoints=wd5601"
>   - "traefik.http.services.wazuh-dashboard.loadBalancer.servers.url=https://wazuh.dashboard:5601"
>   - "traefik.http.services.wazuh-dashboard.loadbalancer.server.port=5601"
> ```
> 
> Also, how could I install ping into Wazuh containers?

The error 404 is because the wazuh container is not on the same network as the traefik. From what I've seen your compose has 2 networks declared; wazuh and traefik. You should check if that is right. On my compose I don't have the network declared this way, at the end of the file I have:

``` yaml
networks:
  default:
    external: true
    name: traefik
```
For the router part, you cannot declare the server URL this way, you should create a YAML file with the configuration for traefik to read. Check out the link I gave you in my last response.

Try to focus on the network part first and then apply the dynamic config for the router afterwards.  

I hope this helps.

**Comment by bremoi** [comment]
Thanks a lot @LaancX.

The network seems good.
```
networks:
  traefik:
    external: true
  wazuh:
    name: wazuh
    driver: overlay
```
The only think that I see strange is the URL pointed by Traefik that is http://10.0.14.73:5601. As you can see it is in HTTP instead of HTTPS. Could the error can from this? If yes, How could force redirection to HTTPS?

Thank you.

**Comment by LaancX** [comment]
> Thanks a lot @LaancX.
> 
> The network seems good. I can ping all containers with each other, e.g. `ping wazuh.dashboard` from Traefik and also run a successfully `curl https://wazuh.indexer:9200/_cluster/health?pretty -k -u USERNAME:PASSWORD` from wazuh.dashboard.
> 
> ```
> networks:
>   traefik:
>     external: true
>   wazuh:
>     name: wazuh
>     driver: overlay
> ```
> 
> The only think I see strange is the URL pointed by Traefik that is http://10.0.14.73:5601. As you can see it is in HTTP instead of HTTPS. Could the error come from this? If yes, How could I force redirection to HTTPS?
> 
> Thank you.

Yep, thats the deal.

Make sure you insert the router information on the dynamic YAML I told you to create. You should have something like this:

``` yaml
services:
    wazuh-dashboard: # Change it to your container name
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: "https://172.22.0.19:5601" # This is my wazuh server, you should change it to reflect yours
```

**Comment by bremoi** [comment]
Can I do something like this? I don't know and use dynamic YAML.
```
labels:
  - "traefik.enable=true"
  - "traefik.http.routers.wd5601.rule=Host(`wazuh.xxxx.tld`)"
  - "traefik.http.routers.wd5601.entrypoints=wd5601"
  - "traefik.http.routers.wd5601.service=wd5601"
  - "traefik.http.services.wd5601.loadbalancer.server.port=5601"
  - "traefik.http.services.wd5601.loadbalancer.serversTransport=insecureTransport"
  - "traefik.http.services.wd5601.loadbalancer.servers.url=https://wazuh.dashboard:5601"
```

**Comment by LaancX** [comment]
On your traefik compose you should have some bindings, like this:

``` yaml
volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${CONTAINER_PATH}/traefik/letsencrypt/acme.json:/acme.json"
      - "${CONTAINER_PATH}/traefik/config.yml:/config.yml:ro" # This is the dynamic config
      - "${CONTAINER_PATH}/traefik/traefik.yml:/traefik.yml:ro" # This is the static one
```
Put that snippet I sent previously with your configs on the dynamic file

**Comment by bremoi** [comment]
Thanks a lot @LaancX, but I don't know where to bind and what to put in place of ${CONTAINER_PATH}.

Is there not a way to use labels instead?

**Comment by LaancX** [comment]
> Thanks a lot @LaancX, but I don't know where to bind and what to put in place of ${CONTAINER_PATH}.
> 
> Is there not a way to use labels instead?

You can put it wherever you want. ${CONTAINER_PATH} is just my folder where I keep my container configs, like. /home/laancx/containers

Unfortunately, the server URL cannot be labeled as the other configs.

**Comment by bremoi** [comment]
Ok, I did the following, but unfortunately always it doesn't work.

```
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
  - "./config.yml:/config.yml:ro"
 ```
```
services:
  wazuh-dashboard:
    loadBalancer:
      serversTransport: insecureTransport
      servers:
        - url: "https://wazuh.dashboard:5601"
```

**Comment by LaancX** [comment]
> - url: "https://wazuh.dashboard:5601"

That is an internal call, it should be the container's IP if I am not mistaken.

Try to follow the traefik access log to see what traefik is calling internally and replace the call for the URL field in the dynamic config.

On your host, check if you can also curl the internal wazuh container, to make sure.

See if that works.

**Comment by bremoi** [comment]
Always not, Traefik Dashboard shows "http://IP:5601/" instead of HTTPS.

**Comment by bremoi** [comment]
By adding the following, Traefik Dashboard now shows "https://10.0.14.130:5601/" which is good, but I have always "404 page not found".
```
- "traefik.http.services.wd5601.loadbalancer.server.port=5601"
- "traefik.http.services.wd5601.loadbalancer.server.scheme=https"
```

**Comment by bremoi** [comment]
Hi,

An important information to specify which may help. My target service handles certificates by itself, so I tried the following, but without success.
```
- "traefik.enable=true"
- "traefik.tcp.routers.wd5601.rule=HostSNI(`wazuh.xxxx.tld`)"
- "traefik.tcp.routers.wd5601.entrypoints=wd5601"
- "traefik.tcp.routers.wd5601.service=wd5601"
- "traefik.tcp.services.wd5601.loadbalancer.server.port=5601"
- "traefik.tcp.routers.wd5601.tls.passthrough=true"
```

**Comment by bremoi** [comment]
Hi,

The following works fine.
```
- "traefik.enable=true"
- "traefik.tcp.routers.wd5601.rule=HostSNI(`*`)"
- "traefik.tcp.routers.wd5601.entrypoints=wd5601"
- "traefik.tcp.routers.wd5601.service=wd5601"
- "traefik.tcp.services.wd5601.loadbalancer.server.port=5601"
- "traefik.tcp.routers.wd5601.tls.passthrough=true"
```

Thank you very much for all your help.

Regards

**Comment by jg1000c** [comment]
anyone here have a working config in github I can look at for using traefik with wazuh?
