### ISSUE TITLE
Update the database feed manager of the new vulnerability detector for the new translations field

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#20210]
## Descriptions

The translations required for the scanner to properly create the CPE of the applications in Windows agents will be included in a custom field inside the same CVE 5.0 document.

It's required to adapt all the required methods to properly read and process this information.

## DoD

- [x] The `cve5.fbs ` flatbuffer schema must be updated to allow the custom field `x_translations`
- [x] The `databaseFeedManager` module and the methods in `upsertTranslation.hpp` must be modified according to this requirements
- [x] Add UT
- [x] Manual test of the component (testtool, E2E, etc.)
- [x] CI Pass

**Comment by MiguelazoDS** [comment]
## Update 12/04/2023 

The requirements changed, now the translation feed won't be embedded in each CVE5 entry, they will be a separate feed but processed by the same piece of code, so we need to identify if the JSON file we're receiving is a CVE5 or a translation information.

**Comment by MiguelazoDS** [comment]
# Update 12/14 

The flatbuffer schema for translation must be as follow. Where there is only one entry for source and one entry for translation.

```
namespace NSVulnerabilityScanner;

table TranslationInfo {
  vendor: string;
  product: string;
  version: string;
}

table TranslationEntry {
  action:[string];
  source:TranslationInfo;
  target:string;
  translation:[TranslationInfo];
}

root_type TranslationEntry;
```

**Comment by MiguelazoDS** [comment]
## Update 12/18/23
