### ISSUE TITLE
Cannot delete agents via API

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#2023]
## Bug report

**OS**
_CentOS7_

**Wazuh version**
_3.7.1-3725_

**Wazuh API version**
_3.7.1_

**Install type**
_manager_

**Install method**
_sources_

**Log sample**
I have two registered agents:
![image](https://user-images.githubusercontent.com/10210567/49369163-0ff3fe80-f6f1-11e8-8186-154deb7c341f.png)

Then I try to delete the `002` agent:
![image](https://user-images.githubusercontent.com/10210567/49369185-200bde00-f6f1-11e8-9f1b-336bf6a26d39.png)
Which gets removed successfully.
But then, I try to remove the `001` agent:

![image](https://user-images.githubusercontent.com/10210567/49369222-39148f00-f6f1-11e8-8a9e-4852c3080afb.png)

Which apparently was successfully removed, but I can still fetch data of it.

Bug description
----------------

When I try to delete my  `001` agent, the API returns a confirmation but actually, it's never been removed. I realized that the API returns a message where the operation was successful, but I can still perform requests to that agent. Additionally, I checked that the `client.keys` file is empty.

Thanks

**Comment by jesuslinares** [comment]
It is not failing in the current version.
