### ISSUE TITLE
Sanitize Syscollector decoder input

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#20249]
|Wazuh version|Component|Install type|
|---|---|---|
| 3.2.0 | wazuh-analysisd | Manager|

We've found multiple cases in the Syscollector decoder at _wazuh-analysisd_ where the JSON input is not properly sanitized.

That contains some assumptions:
- The expected fields exist.
- The expected fields have the right type (_number_ or _string_).

## DoD

- [x] Sanitize every access to the input JSON fields.
- [x] Extend the unit test coverage.

**Comment by ncvicchi** [comment]
This issue might be related to [this issue](https://github.com/wazuh/wazuh/issues/16669) (Analyze and fix cJSON integer validations)
