### ISSUE TITLE
Add ITs related to legacy agents to check retrocompatibility

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#20247]
# Description
Hello team,
After work on this issue:
https://github.com/wazuh/wazuh/issues/20152

We have detected some errors when generating alerts coming from older Windows agents (manager `>=4.6.0`, agent `<4.6.0`).
Therefore, we want in the future to consider the possibility of having integration tests to verify that this backward compatibility works correctly. At least for the FIM alerts (although we could consider the possibility of covering other areas), since the alerts contain a `version` field that indicates the compatibility with the decoders and the functions of the wdb itself in the manager.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
