### ISSUE TITLE
Multiple wrong versions of Mozilla Firefox are detected

### ISSUE THREAD

**Issue by TijZwa** [wazuh/wazuh#20248]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.4 | Wazuh agent syscollector | Agent | Packages | Windows server 2019 |

I've a server with only Mozilla Firefox 119.0.1 installed. However, a bunch of other versions get detected.
If I remove `queue/syscollector/db/local.db` and restart the agent, the records are recreated immediately. 
I cant find any other version of Firefox in the control panel or registry, but it keeps getting detected.

Can you tell me where to start investigating the issue?

![image](https://github.com/wazuh/wazuh/assets/19667394/70d0089a-1c59-4125-ac88-3d0fa13c199b)

**Comment by MiguelazoDS** [comment]
Hi @TijZwa, 

Please share the complete information for those Firefox packages, my guesses without any context may be that syscollector is collecting packages from different architecture since they are located in different places in Windows registry, another guess is that some Firefox package was installed through Microsoft Store. 

Please share the output of this command. 

`sqlite3 /var/ossec/queue/db/<agent_id>.db 'select * from sys_programs where name like "%firefox%"'`

Where `agent_id` is the ID of your Windows agent.

**Comment by TijZwa** [comment]
`0|2023/11/10 12:35:52|win|Mozilla Firefox (x64 nl)| | |0|Mozilla| |119.0.1|x86_64|| | |C:\Program Files\Mozilla Firefox|1|||42e3df54337a01a57e2038dc70c59fc71dd54066|49af18a0ac4d7b84bf8b4391921a13004312d23d
0|2023/11/21 12:43:50|win|Mozilla Firefox (x64 nl)| | |0|Mozilla| |94.0.2| || | |C:\Program Files\Mozilla Firefox|0|||26f0986333e56662ea425ed602e71ae838e48e9e|e9980595f32933fadc7e0b729b167fba96dd53d1
`

**Comment by TijZwa** [comment]
`0|2023/11/10 12:35:52|win|Mozilla Firefox (x64 nl)| | |0|Mozilla| |119.0.1|x86_64|| | |C:\Program Files\Mozilla Firefox|1|||42e3df54337a01a57e2038dc70c59fc71dd54066|49af18a0ac4d7b84bf8b4391921a13004312d23d`

`0|2023/11/21 12:43:50|win|Mozilla Firefox (x64 nl)| | |0|Mozilla| |94.0.2| || | |C:\Program Files\Mozilla Firefox|0|||26f0986333e56662ea425ed602e71ae838e48e9e|e9980595f32933fadc7e0b729b167fba96dd53d1`

**Comment by MiguelazoDS** [comment]
Hi, 

sorry for the late response, I see that one of the entries does not have the architecture. As I initially thought it getting the information from two different registry entries. 

The first one ver 119.0.1 seems to be obtained from here 
`HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall`

And the second one from here 
`HKEY_CURRENT_USER\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall`

Could you check that? 

From here I think it is reading the registry for multiple users. Do you have several users in your Windows agent with different versions of the browser? 

https://github.com/wazuh/wazuh/blob/a8f413c81c0e3f7b1a79b1bf08ffbcd5bbcbaa01/src/data_provider/src/sysInfoWin.cpp#L919-L923

**Comment by TijZwa** [comment]
Thanks! That's it.
We are running Terminal Server / MS RDS, so the results depends on the currently logged on users. This clarifies **a lot** for us.

**Comment by MiguelazoDS** [comment]
That's great! have a good day!
