### ISSUE TITLE
Ansible playbook got stuck at 'Set the kibanaserver user password' step.

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20261]
| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.7.0-rc1/deployment-options/deploying-with-ansible/index.html) | Multi node | Oracle Linux 9 x86_64 |
| Server | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.7.0-rc1/deployment-options/deploying-with-ansible/index.html) | Multi node | Oracle Linux 9 x86_64 |
| Dashboard | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.7.0-rc1/deployment-options/deploying-with-ansible/index.html) | - | Oracle Linux 9 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using FQDN and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.7.0-rc1/_images/deploy-new-agent-from-ui1.png) | - | Alma Linux 9 x86_64 |

## Description
During E2E testing, on #20203, Running the the playbook for Wazuh cluster was failing. 
The playbook got stuck at the step `TASK [../roles/wazuh/wazuh-indexer : Set the kibanaserver user password]`, of one of the indexers and don't continue.

```jsx
ansible-playbook -i ~/git/e2e_ansible/hosts wazuh-production-ready.yml -b
...
TASK [../roles/wazuh/wazuh-indexer : Set the Admin user password] ***************************************************************************************************************************************************
changed: [wi3]

TASK [../roles/wazuh/wazuh-indexer : Hash the kibanaserver role/user pasword] ***************************************************************************************************************************************
changed: [wi3]

TASK [../roles/wazuh/wazuh-indexer : Hash the kibanaserver role/user pasword] ***************************************************************************************************************************************
changed: [wi1]

TASK [../roles/wazuh/wazuh-indexer : Restart Wazuh indexer with security configuration] *****************************************************************************************************************************
changed: [wi2]

TASK [../roles/wazuh/wazuh-indexer : Set the kibanaserver user password] ********************************************************************************************************************************************
changed: [wi1]

TASK [../roles/wazuh/wazuh-indexer : Set the kibanaserver user password] ********************************************************************************************************************************************
changed: [wi3]

TASK [../roles/wazuh/wazuh-indexer : Copy the Opensearch security internal users template] **************************************************************************************************************************
changed: [wi2]

TASK [../roles/wazuh/wazuh-indexer : Hashing the custom admin password] *********************************************************************************************************************************************
changed: [wi2]

TASK [../roles/wazuh/wazuh-indexer : Set the Admin user password] ***************************************************************************************************************************************************
changed: [wi2]

TASK [../roles/wazuh/wazuh-indexer : Hash the kibanaserver role/user pasword] ***************************************************************************************************************************************
changed: [wi2]

TASK [../roles/wazuh/wazuh-indexer : Set the kibanaserver user password] ********************************************************************************************************************************************
changed: [wi2]
[ERROR]: User interrupted execution
```

**Comment by c-bordon** [comment]
Hi @nico-stefani please check if firewalld is on.

reference: https://github.com/wazuh/wazuh/issues/20089#issuecomment-1802279714

**Comment by c-bordon** [comment]
I was reviewing the environment configuration deployed by @nico-stefani and I was able to detect that there was an error in the configuration of the security group of the machines, this configuration was made and the test progressed correctly

**Comment by andrja15** [comment]
> I was reviewing the environment configuration deployed by @nico-stefani and I was able to detect that there was an error in the configuration of the security group of the machines, this configuration was made and the test progressed correctly

I have the same problem on Debian 12, which error in the configuration of the security group have you found, or how can i fix it.

**Comment by madleeen** [comment]
Hi, I have exactly the same problem. 
I tried to stop firewall on the wi2 machine where it gets stucked, but no difference. Any other thougts, please?
