### ISSUE TITLE
Unable to suppress Docker Overlay2 rootcheck events

### ISSUE THREAD

**Issue by baubie** [wazuh/wazuh#20279]
|Wazuh version|Component|Install type|Install method|Platform|
|4.6.0|rootcheck|Agent/Manager|Agent from script shown in manager|Ubuntu 22.04.3|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Whenever rootcheck runs on my Ubuntu agents with docker, I am flooded with thousands of events that look like the JSON below.

I have tried everything to prevent this.  My agent.conf (which is on the agent systems so is being pushed correctly) tries to ignore with the following:

### agent.conf on my agents
```json
<agent_config>
  <rootcheck>
    <ignore>/var/lib/docker/overlay2/</ignore>
  </rootcheck>
</agent_config>
```

### Example event
```json
{
  "agent": {
    "ip": "10.162.0.1",
    "name": "agent-name",
    "id": "002"
  },
  "manager": {
    "name": "wazuh"
  },
  "data": {
    "file": "/var/lib/docker/overlay2/38e0cf60d77fff40d33fba04bacafe2c80ffc86055ca432bc604d0f8c915bb7c/diff/server/app/geoservice.py",
    "title": "File is owned by root and has written permissions to anyone."
  },
  "rule": {
    "firedtimes": 1837,
    "mail": false,
    "level": 7,
    "pci_dss": [
      "10.6.1"
    ],
    "description": "Host-based anomaly detection event (rootcheck).",
    "groups": [
      "ossec",
      "rootcheck"
    ],
    "id": "510",
    "gdpr": [
      "IV_35.7.d"
    ]
  },
  "decoder": {
    "name": "rootcheck"
  },
  "full_log": "File '/var/lib/docker/overlay2/38e0cf60d77fff40d33fba04bacafe2c80ffc86055ca432bc604d0f8c915bb7c/diff/server/app/geoservice.py' is owned by root and has written permissions to anyone.",
  "input": {
    "type": "log"
  },
  "@timestamp": "2023-11-16T16:00:04.759Z",
  "location": "rootcheck",
  "id": "1700150404.206193374",
  "timestamp": "2023-11-16T16:00:04.759+0000",
  "_id": "Z9Tc2IsBdHKMNotOboQK"
}
```

**Comment by MiguelazoDS** [comment]
# Analysis 

## Docker agent: 

* Info

<details><summary>Expand</summary>

![image](https://github.com/wazuh/wazuh/assets/13010397/45a72525-77fe-4968-ba23-88d6b4e531fa)
![image](https://github.com/wazuh/wazuh/assets/13010397/b8fa8f1e-006e-4069-9312-171fb8840cec)

</details>

* Dockerfile

<details><summary>Expand</summary>

```Dockerfile
FROM ubuntu
RUN apt-get update && \
apt-get install -y curl gnupg2 && \
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add - && \
echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list && \
apt-get update && \
apt-get install -y wazuh-agent && \
rm -rf /var/lib/apt/lists/* && \
sed -i "s/MANAGER_IP/192.168.33.70/" /var/ossec/etc/ossec.conf
CMD /var/ossec/bin/wazuh-control start && tail -f /dev/null
```

</details>

## Manager (Ubuntu Jammy) 

![image](https://github.com/wazuh/wazuh/assets/13010397/896c317f-87e5-489d-a1b1-e618b8fa27cc)
![image](https://github.com/wazuh/wazuh/assets/13010397/7f5a17ca-c676-47e9-9427-b6ceccfe5a1a)

:red_circle:  Not reproducible

**Comment by baubie** [comment]
Is it possible that these overlay2 files are being caught by a different rule?  The rule I'm hitting is 510 - perhaps there's something else about them?

**Comment by MiguelazoDS** [comment]
Is there any change if you use this?

```xml
<agent_config>
  <rootcheck>
    <ignore>/var/lib/docker/overlay2</ignore>
  </rootcheck>
  </agent_config>
```
Note that I removed the last "/" in the ignore tag.

**Comment by baubie** [comment]
> Note that I removed the last "/" in the ignore tag.

That did it.  Thank you!

**Comment by MiguelazoDS** [comment]
Thanks to you @baubie, apologize for the delay I misunderstood the issue, it was not the same alert I thought it was. Regards!
