### ISSUE TITLE
Audit Rules not generating Email

### ISSUE THREAD

**Issue by HireLabs** [wazuh/wazuh#2027]
I am trying to generate an email whenever any of the below rules is true, I am able to see logs in kibana, but emails are not generating.

<email_alerts>
  <email_to>xxxxxx@yahoo.com</email_to>
 <rule_id>80701, 80702, 80703, 80704, 80705, 80710, 80711, 80712, 80713, 80715, 80716, 80717, 80718, 80719, 80720, 80721, 80722, 80723, 80724, 80726, 80730, 80731, 80732, 80740, 80741, 80742, 80780, 80781, 80782, 80783, 80784, 80785, 80786, 80787, 80788, 80789, 80790, 80791</rule_id>
</email_alerts>

Please help

**Comment by cristgl** [comment]
Hello @HireLabs,

Have you configured the email options as stated at the [email documentation](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?highlight=email#generic-email-options) with that account?
You should have also followed the steps at [Postfix](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/smtp_authentication.html?highlight=smtp%20server). The sixth point of that link sends a test email to the account you have set. Let me know if this helps you and you received the email.

Best regards

**Comment by HireLabs** [comment]
Dear @cristgl ,

I am getting all other emails which I have setup separately, but only this rule is not triggering.

Best Regards

**Comment by cristgl** [comment]
Hello @HireLabs,

Can you check the `email_maxperhour` option at the _ossec.conf_ file? This value is 12 by default, maybe you have received that 12 emails and not anymore since you have this threshold.
Another possible problem could be at your yahoo email, can you check if its SMTP server blocks the access from less secure apps?

Kind regards,
Cristina

**Comment by cristgl** [comment]
Hi @HireLabs,

I am closing this issue now, if you need further assistance do not hesitate to reopen it.

Best regards,
Cristina
