### ISSUE TITLE
Can't find wazuh-indexer

### ISSUE THREAD

**Issue by rickmacgillis** [wazuh/wazuh#20272]
|Wazuh version|Component|Install type|Install method|Platform|
|4.6|wazuh-indexer|Manager|Packages|Ubuntu 22.04|

I've followed the installation instructions at https://documentation/.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html No matter what I do, it always says it can't find wazuh-indexer on your repo. Reading package lists... Building dependency tree... Reading state information... E: Unable to locate package wazuh-indexer How do I fix this issue?

**Comment by rickmacgillis** [comment]
Any updates on this? It seems like a popular issue.

**Comment by davidcr01** [comment]
Hello. I followed the related steps of the documentation in a Ubuntu 22 system, and no errors were generated.

The Wazuh repository is added correctly and the `wazuh-indexer` package is correctly fetched:

```console
root@ubuntu22:/home/vagrant# bash wazuh-install.sh --generate-config-files
20/11/2023 09:44:22 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
20/11/2023 09:44:22 INFO: Verbose logging redirected to /var/log/wazuh-install.log
20/11/2023 09:45:00 INFO: --- Configuration files ---
20/11/2023 09:45:00 INFO: Generating configuration files.
20/11/2023 09:45:02 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
root@ubuntu22:/home/vagrant# bash wazuh-install.sh --wazuh-indexer node-1
20/11/2023 09:45:17 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
20/11/2023 09:45:17 INFO: Verbose logging redirected to /var/log/wazuh-install.log
20/11/2023 09:45:33 INFO: --- Dependencies ----
20/11/2023 09:45:33 INFO: Installing apt-transport-https.
20/11/2023 09:45:38 INFO: Wazuh repository added.
20/11/2023 09:45:39 INFO: --- Wazuh indexer ---
20/11/2023 09:45:39 INFO: Starting Wazuh indexer installation.
20/11/2023 09:51:26 INFO: Wazuh indexer installation finished.
20/11/2023 09:51:26 INFO: Wazuh indexer post-install configuration finished.
20/11/2023 09:51:26 INFO: Starting service wazuh-indexer.
20/11/2023 09:51:49 INFO: wazuh-indexer service started.
20/11/2023 09:51:49 INFO: Initializing Wazuh indexer cluster security settings.
20/11/2023 09:51:51 INFO: Wazuh indexer cluster initialized.
20/11/2023 09:51:51 INFO: Installation finished.
root@ubuntu22:/home/vagrant# apt list --installed | grep wazuh-indexer

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

wazuh-indexer/stable,now 4.6.0-1 amd64 [installed]
```

As a recommendation, I would execute the `bash wazuh-install.sh -u` command. This command uninstalls all the Wazuh central components, so be careful about this. Also, this execution will remove the Wazuh repository.
Then, retry to perform the installation.

**Comment by rickmacgillis** [comment]
I decided not to put it on the Opi 5 plus, and instead use Docker to install it on the Zimaboard. Hopefully this keeps going smoothly. This time wazuh-indexer installed fine, but there wasn't a repo nor shell script at play.

**Comment by IvanCastillo1986** [comment]
I'm definitely having this issue now as well. I followed all of the instructions step-by-step:
sudo apt-get -y install wazuh-indexer

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package wazuh-indexer

**Comment by Elnadrion** [comment]
Had the same problem.
I wanted to play with wazuh locally and it took me some time to realize, that there's no `wazuh-indexer` built for `arm64`
arm64:
![image_2024-03-13_16-37-42](https://github.com/wazuh/wazuh/assets/33313896/b1d4562e-40ba-4ef1-a750-baedbc385d35)
amd64:
![image_2024-03-14_13-18-20](https://github.com/wazuh/wazuh/assets/33313896/391fa3f3-5a6a-4316-b2f6-0db97fe538f9)

**Comment by davidcr01** [comment]
Hello, in this case, we do not support ARM64 package building for the Wazuh indexer and Wazuh dashboard components, so it is expected that the package manager can not find these packages.

For more information about our packages, please visit the following link: https://documentation.wazuh.com/current/installation-guide/packages-list.html.

Please, make sure you have the correct architecture before installing Wazuh.
