### ISSUE TITLE
Wazuh Agent Centos (client)

### ISSUE THREAD

**Issue by borbelyau** [wazuh/wazuh#203]
Hey guys...
I need some direction... 
Here I have 1 Centos7 who has syslog... and I install the agent... but I dont find where I put the manager IP address... And how I send  /var/log/messages (the file who has the syslog information)

**Comment by vikman90** [comment]
Hi @borbelyau,

if you have just installed the agent, it should have created a monitoring configuration for /var/log/messages.

The configuration is at `/var/ossec/etc/ossec.conf`.

*Manager IP*

You may set the manager IP by modifying this configuration:

```
<client>
  <server-ip>1.2.3.4</server-ip>
</client>
```

Regarding the _messages_ file monitoring, please check that this configuration exists:

```
<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/messages</location>
</localfile>
```

If you need some more information please take a look at https://documentation.wazuh.com/current/index.html.

Best regards.

**Comment by jlruizmlg** [comment]
Also you need to register the agent with the manager, probably you did already but if not you can follow the next guide:
https://documentation.wazuh.com/current/user-manual/agents/command-line/register.html#command-line-register

**Comment by borbelyau** [comment]
Guys I dont know why but I dont receive the /var/log/messsages (All this I had done before)
It is only bringing messages from the system itself and not from syslog.... Do I need to enable json in ossec.conf?
Tks guys

**Comment by borbelyau** [comment]
[agent.txt](https://github.com/wazuh/wazuh/files/1333150/agent.txt)
[manager.txt](https://github.com/wazuh/wazuh/files/1333151/manager.txt)

**Comment by chemamartinez** [comment]
Hi @borbelyau,

Could you confirm that the agent is connected with the manager using the following command in the manager side?

```
root@centos:~# agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centos (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: Ubuntu16, IP: 192.168.1.114, Active
```

And also, you could check if the logcollector daemon is running in the agent which is collecting syslog information.

You should see something like this:

```
[root@centos src]# /var/ossec/bin/ossec-control status
ossec-logcollector is running...
ossec-syscheckd is running...
ossec-agentd is running...
ossec-execd is running...
wazuh-modulesd is running...
```

If you see that the agent is connected and logcollector is running, please send us the `ossec.log` file located at `/var/ossec/log/` in order to trace the cause of your problem.

Regards.

**Comment by borbelyau** [comment]
![first](https://user-images.githubusercontent.com/10618785/30914528-6246f4e8-a36a-11e7-88b0-cb3228af6c56.png)
![second](https://user-images.githubusercontent.com/10618785/30914535-67e26054-a36a-11e7-9017-5e314be2e991.png)
![third](https://user-images.githubusercontent.com/10618785/30914541-6fbe57e2-a36a-11e7-8988-287f34e211de.png)
tks alot

**Comment by borbelyau** [comment]
![first](https://user-images.githubusercontent.com/10618785/30914790-2d22a888-a36b-11e7-9485-a608932be5e6.png)
![second](https://user-images.githubusercontent.com/10618785/30914798-3220f93e-a36b-11e7-898d-c1ef00ec86b1.png)
![third](https://user-images.githubusercontent.com/10618785/30914800-363d6188-a36b-11e7-8c8d-126b05b88f2e.png)
tks alot

**Comment by borbelyau** [comment]
client side 
![bazinga](https://user-images.githubusercontent.com/10618785/30915327-d513e2a4-a36c-11e7-94bf-5a534420c34f.png)

ossec.log
[client-agent.txt](https://github.com/wazuh/wazuh/files/1337253/client-agent.txt)

**Comment by chemamartinez** [comment]
It seems everything is working fine, try to visualize your agent events in the `archives` file.

For doing this, set the following configuration in the manager:

```
<global>
    ...
    <logall>yes</logall>
    ...
</global>
```
Then, restart the manager and you should be able to see all the events received in the file `/var/ossec/log/archives/archives.log`. 

If you can see events received from syslog in this file, the manager is storing correctly that information.

**Comment by borbelyau** [comment]
modulesd is not working on client side that is a problem?

**Comment by chemamartinez** [comment]
Modulesd is not related to the log data collection. For running modulesd daemon it should be enabled the Openscap module in `ossec.conf`.

In any case, if you want to enable it please take a look at https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-openscap.html.

Hope it helps.

**Comment by borbelyau** [comment]
@chemamartinez  I do not know how it still does not send the syslog log...

**Comment by borbelyau** [comment]
tks for all...

**Comment by borbelyau** [comment]
It was solved ... thanks to all who helped me...
The error was found on firewall(rule)... and the syslog was solved  with logall
