### ISSUE TITLE
Release 4.7.0 - RC 1 - Footprint Metrics - ALL-EXCEPT-OSQUERY,VULNERABILITY-DETECTOR (2.5d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#20309]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #20208                                         |
| **Main footprint metrics issue #** | #20215                                         |
| **Version** | 4.7.0                                      |
| **Release stage #** | RC 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.7.0-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/189/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/Test_stress_Vagrant_B189_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/plots/Test_stress_Vagrant_B189_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B189_manager_2023-11-16.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/logs/ossec_Test_stress_Vagrant_B189_manager_2023-11-16.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B189_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/data/monitor-manager-Test_stress_Vagrant_B189_manager-pre-release.csv)
[Test_stress_Vagrant_B189_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/data/Test_stress_Vagrant_B189_manager_analysisd_events.csv)
[Test_stress_Vagrant_B189_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/data/Test_stress_Vagrant_B189_manager_analysisd_state.csv)
[Test_stress_Vagrant_B189_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_manager_centos/data/Test_stress_Vagrant_B189_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/Test_stress_Vagrant_B189_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/Test_stress_Vagrant_B189_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/Test_stress_Vagrant_B189_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/plots/Test_stress_Vagrant_B189_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B189_macos_2023-11-16.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/logs/ossec_Test_stress_Vagrant_B189_macos_agent_2023-11-16.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/data/monitor-agent-Test_stress_Vagrant_B189_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B189_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_macos/data/Test_stress_Vagrant_B189_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/Test_stress_Vagrant_B189_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/Test_stress_Vagrant_B189_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/Test_stress_Vagrant_B189_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/plots/Test_stress_Vagrant_B189_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B189_solaris_2023-11-16.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/logs/ossec_Test_stress_Vagrant_B189_solaris_agent_2023-11-16.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B189_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B189_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.7.0/B189-3600m/B189_agent_solaris/data/Test_stress_Vagrant_B189_solaris_agent_agentd_state.csv)

    </details>

</details>

## Notes:
Plots compared to: https://github.com/wazuh/wazuh-jenkins/issues/5882

### Plots
No abnormalities were found

#### Known issues

- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5538
- https://github.com/wazuh/wazuh/issues/20082

**Comment by pro-akim** [comment]
# Analysis report :yellow_circle:

## Graphs :green_circle:

### Centos
No abnormalities were found

### Ubuntu
No abnormalities were found

### Windows
No abnormalities were found

### Manager
USS, RSS, USS: small dip at the initial stage of the plot is not present anymore

## Logs :yellow_circle:

<details><summary>Manager</summary>

- Expected in stress test
```
wazuh-modulesd:oscap ERROR: Internal error. Exiting...
sca WARNING: Interval overtaken.
wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
wazuh-modulesd:azure-logs WARNING: Interval overtaken.
wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

</details>             

<details><summary>MacOs</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.13.154]:1514/tcp': 'Connection
wazuh-agentd ERROR: Connection socket: Operation timed out (60)
wazuh-syscheckd WARNING: Process locked due to agent is offline. Waiting for 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5538 - Known issue
```
[2023-11-14_15:07:04] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'\n
```

- Reported: https://github.com/wazuh/wazuh/issues/20082 - Known issue
```
wazuh-syscheckd WARNING: Socket busy, discarding message.
```

</details>

<details><summary>Solaris</summary>

- Expected in stress test
```
wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.13.154]:1514/tcp': 'Connection refused'.
wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

</details>

**Comment by juliamagan** [comment]
LGTM
