### ISSUE TITLE
DLL hijack tests are unstable. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#20322]
# Description 

It was found that the tests in charge to verify that we are not vulnerable to DLL hijacking are failing occasionally. 

The error log can be found here. 
https://github.com/wazuh/wazuh/actions/runs/6893312810/job/18752905293?pr=20278

## DoD 

- [ ] Find the cause of the failing checks and report it.
- [ ] Find a solution and implement it.

**Comment by pereyra-m** [comment]
## Update

It seems that a large backing file hangs the process monitor

https://social.technet.microsoft.com/Forums/en-US/bc2d5ad4-41dd-4420-be51-a21b495b7cd0/process-monitor-fails-to-terminate-when-there-is-a-large-backing-file?forum=procmon

We could update the .pmc configuration file to reduce the captured data.
