### ISSUE TITLE
Increase of number of dropped_events in Wazuh Manager in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20321]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-r1 | Wazuh component | Manager | Packages | CentOS |

Testing: [Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/20305)
Increase of number of dropped_events of sca in Wazuh Manager in stress test

4.7.0-rc1https://github.com/wazuh/wazuh/issues/20305
![image](https://github.com/wazuh/wazuh/assets/125690423/93b88ff5-a743-4629-8793-495a3bd8a0e9)

4.6.0-rc2 https://github.com/wazuh/wazuh-jenkins/issues/5881
![image](https://github.com/wazuh/wazuh/assets/125690423/9c6d9340-6269-42fa-b9c2-18f502a08aca)

**Comment by nmkoremblum** [comment]
We observe on the logs, about the time when the logs are dropped, the following:

> 2023/11/15 14:26:35 wazuh-analysisd: WARNING: Security Configuration Assessment decoder queue is full.

This means that probably all the dropped logs are from SCA. This could have been a coincidence at a particular moment when many SCA events arrived at the manager. No other errors/warnings are seen that may infer there is a bug.

On the other hand, we see that `4.7.0` decodes ~30M SCA events which increased ~3% against the ~29M decoded on `4.6.0`. The difference of about 1M decoded events is much bigger than the 30 dropped events, so I don't think it is a reason to worry about.
