### ISSUE TITLE
Change in CPU usage pattern from wazuh-syscheckd during allocation time

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#20330]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-rc1 | `wazuh-syscheckd` | Agent | Packages| CentOS/Ubuntu |

## Description

While analyzing the [results of the footprint tests in `4.7.0-rc1`](https://github.com/wazuh/wazuh/issues/20306) we've found some differences compared to this issue: https://github.com/wazuh/wazuh-jenkins/issues/5872 (production version)

Also, there are no remarkable differences in the number of generated/decoded/dropped events.

### Ubuntu Agent

| Variable | 4.6.0 (current production version) | 4.7.0-rc1 |
|--|--|--
| CPU | <img src="https://camo.githubusercontent.com/f7309955116099ee6c8e28406bc29ba5e38c167e52d0bcf3e3f13968b8c50487/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343533302d333630306d2f42343533305f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343533305f7562756e74752d7072652d72656c656173655f4350552e706e67"/> | <img src="https://camo.githubusercontent.com/978691fd361b23def7ac9d7aece7bf2d0414f21f45366c63831ff47ff11ad141/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343538362d333630306d2f42343538365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343538365f7562756e74752d7072652d72656c656173655f4350552e706e67"/>

**Comment by vikman90** [comment]
## Comparing performance

|Version|CPU time|Average usage|Max usage|Average RSS|Max RSS|
|---|---|---|---|---|---|
|[4.6.0](https://github.com/wazuh/wazuh-jenkins/issues/5872)|22722.23 sec.|58.56 %|143.4 %|9876.67 KiB|12952.0 KiB|
|[4.7.0-RC2](https://github.com/wazuh/wazuh-jenkins/issues/58720)|22011.53 sec. (3 % ⬇️)| 56.73 % | 136.8 % |9599.69 KiB | 12748.0 KiB|

Regardless of the peaks, the CPU time in 4.7.0 is slightly lower, which denotes lower computational cost.
