### ISSUE TITLE
Relevant decrease of use of Disk of CentOS Manager in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20341]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0-r1 | Wazuh component | Manager | Packages | CentOS |

Testing: [DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20298)

It was possible to evidence a significant fall (>50%) of Analsysd disk use in the Manager

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20298
![image](https://github.com/wazuh/wazuh/assets/125690423/00169b89-a077-4582-890d-0c052775d0cc)

4.6.0-rc2  https://github.com/wazuh/wazuh-jenkins/issues/5867
![image](https://github.com/wazuh/wazuh/assets/125690423/e771c83c-ae1b-42fe-818b-281ce6040c4b)

Same level of fall to https://github.com/wazuh/wazuh/issues/20306

Further research should be done

**Comment by rafabailon** [comment]
I have observed the same behavior at https://github.com/wazuh/wazuh/issues/20290 for Ubuntu Agent

![image](https://github.com/wazuh/wazuh/assets/54536265/2690bc80-36b8-46bd-8c0f-5b7dcbfe33d3)

![image](https://github.com/wazuh/wazuh/assets/54536265/ecb267b7-4703-4cf6-9ff4-60126fa6744d)

**Comment by cborla** [comment]
## Disk usage analysis in manger centos

To determine the reason for the decrease in disk usage, several test plots were analyzed.

- Disk read
  - About the same
- Disk written
  - About the same	
- Dropped events
  - Zero for both
- Events decoded per second:
  - At this point we can find a difference, in version 4.6.0 the manager starts decoding many more events than in version 4.7.0, in the following graph we can see the difference at the beginning of the test. (the graph represents total EDPS)
  
![image](https://github.com/wazuh/wazuh/assets/41765669/dd2a3b3c-1296-48a3-9037-d749b87dfa5e)

This behavior may justify the difference at the beginning of the test, where the percentage of disk usage in 4.6.0 reaches 1.5 % and in version 4.7.0 it barely exceeds 1 %.

| Version | Total % | Samples | %CPU/sec |
|---|---|---|---|
|4.6.0|51765|37804|0.27|
|4.7.0|47488|37619|0.25|
