### ISSUE TITLE
AWS woodle unable to parse profiles in ~/.aws/config file

### ISSUE THREAD

**Issue by malvery** [wazuh/wazuh#20352]
| Affected integration |
|---|
| AWS|

## Description
Wazuh 4.6.0 broke ~/.aws/config file parsing. 

The issue related to the this [function](https://github.com/wazuh/wazuh/blob/4.6/wodles/aws/aws_s3.py#L365) call.

It cannot find any profile defined in this file, because variable [profile](https://github.com/wazuh/wazuh/blob/4.6/wodles/aws/aws_s3.py#L361) will have defined in  aws-s3 woodle *aws_profile* value. However, AWS requires to define profiles by *[profile user1]* directive, as described [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html#cli-configure-files-format).

This patch to the https://github.com/wazuh/wazuh/blob/4.6/wodles/aws/aws_s3.py  fixes issue:
```
361c361
<             profile = profile if profile is not None else 'default'
---
>             profile = f"profile {profile}" if profile is not None else 'default'
```

<details><summary><SERVICE> logs</summary>

<p>

```
[root@wazuh-server aws]# /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py --bucket *** --aws_profile soc-cloudtrail_logs --aws_organization_id *** --type cloudtrail --debug 2 --skip_on_error
DEBUG: +++ Debug mode on - Level: 2
No profile named: 'soc-cloudtrail_logs' was found in the user config file

[root@wazuh-server aws]# cat ~/.aws/config 
[profile soc]
region = ap-southeast-1

[profile soc-cloudtrail_logs]
role_arn = arn:aws:iam::***:role/***
source_profile = soc
```
</p>

</details>

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by GGP1** [comment]
## Update

Updated the documentation and modified the AWS configuration profiles name formatting to comply with the AWS requirements. Started testing the solution.

**Comment by GGP1** [comment]
## Update

Tested the changes in both a manager and an agent and updated the corresponding unit test.

**Comment by GGP1** [comment]
## Update

Removed the `profile` prefix for reading the configuration values and added two notes to the documentation clarifying how the configuration is interpreted.

**Comment by GGP1** [comment]
## Update

Made the changes suggested in the code review.

**Comment by GGP1** [comment]
## Update

Applied the code review suggestions to the documentation.

**Comment by GGP1** [comment]
## Update

Applied changes to read the configuration with the provided profile with an without the `profile` prefix.
