### ISSUE TITLE
Remove ssl_protocol from the API configuration.

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20376]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description
The allowed protocols 
```
allowed_ssl_protocols = {
                'tls': ssl.PROTOCOL_TLS,
                'tlsv1': ssl.PROTOCOL_TLSv1,
                'tlsv1.1': ssl.PROTOCOL_TLSv1_1,
                'tlsv1.2': ssl.PROTOCOL_TLSv1_2
            }
```

Used in the API have been deprecated since Python version 3.6. The protocol that should be used is `ssl.PROTOCOL_TLS_SERVER`, so this configuration is not needed anymore.

## Checks
The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
To be done in:
- https://github.com/wazuh/wazuh/issues/20396
