### ISSUE TITLE
Centralized configuration not working after update to 4.6.0 on Docker Installation

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#20398]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.6.0 | Centralized configuration | Manager&Agent | wazuh-docker | Ubuntu |

## Description

The centralized configuration stops working after the Docker installation is updated, to resume its correct functionality the agents groups must be changed.

### Steps to reproduce

1. Install Wazuh docker v4.5.4 -> [wazuh-container](https://documentation.wazuh.com/4.5/deployment-options/docker/wazuh-container.html)
2. Connect agents to the `wazuh-server` running on docker
3. Add the agents to a group and edit the `agent.conf` of that group -> [agent-groups-and-centralized-configuration](https://wazuh.com/blog/agent-groups-and-centralized-configuration/)
4. Upgrade the Wazuh docker installation -> [upgrading-wazuh-docker](https://documentation.wazuh.com/current/deployment-options/docker/upgrading-wazuh-docker.html)
5. Upgrade the agents -> [upgrading-agent](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/upgrading-agent.html)
6. Update the `agent.conf` of the agents group with another configuration.
7. Check the `agent.conf` of the agents it is not updated.

**Comment by thejbte** [comment]
It replicated once, but in several attempts it doesn't replicate anymore, it works fine.
I tried with manager (4.5.4, 4.6.0 4.7.3) deployed from docker.

**Comment by TomasTurina** [comment]
The modules involved will be refactored, so this issue will not be addressed.
