### ISSUE TITLE
Geolocation in AWS WAF

### ISSUE THREAD

**Issue by abacao** [wazuh/wazuh#20426]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.6.0_1 | AWS Module | Manager | all-in-one AMI image | Amazon Linux 2 |

Hello Wazuh team,

I was looking the data AWS WAF provides an I tried to create a setting to have events on the map.

Looking at the Cloudtrail Events, I tried 2 approaches

```
     {
        "set": {
          "field": "data.aws.httpRequest.clientIp",
          "value": "{{data.aws.httpRequest.clientIp}}",
          "override": false,
          "ignore_failure": true
        }
      },
```
The above didn't work so I also tried the following:
```
      {
        "geoip": {
          "field": "data.aws.httpRequest.clientIp",
          "target_field": "GeoLocation",
          "properties": ["city_name", "country_name", "region_name", "location"],
          "ignore_missing": true,
          "ignore_failure": true
        }
      },
```
And this also didn't work.

All other AWS tools (ex: guardduty) could be configured by default if the AWS module is enabled.

Before opening this issue, I tried chat [here](https://wazuh.slack.com/archives/C0A933R8E/p1700737703887549).

Is there a way to enable AWS WAF "dots" in the Geolocation map?

Thank you

**Comment by Selutario** [comment]
Similar to https://github.com/wazuh/wazuh/issues/16198
