### ISSUE TITLE
Investigate and fix concurrency flaws in API and Framework

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20439]
|Wazuh version|Component|
|---|---|
| master | API, Framework |

## Description
With the upgrade of the Connexion package to version 3.0, the underlying ASGI server can launch several processes to attend to incoming HTTP requests.

Launching several processes can raise potential concurrency problems that should be addressed and fixed. For example, the middleware that blocks IPs that exceed the maximum number of requests per minute is implemented with a simple Python dictionary and should be changed to a shared data structure synchronized between processes.

## Checks
The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Closing for now as it does not fit any current objective.
