### ISSUE TITLE
Release 4.7.1 - RC 1 - E2E UX tests - macOS

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20459]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.1-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/early-birds team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Nov 29, 2023 and notify the @wazuh/early-birds team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/early-birds team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Nov 30, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 01, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Installation assistant](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-indexer/installation-assistant.html) | Single node | RHEL 9 x86_64 |
| Server | [Installation assistant](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-server/installation-assistant.html) | Multi node | RHEL 9 x86_64 |
| Dashboard | [Installation assistant](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-dashboard/installation-assistant.html) | - | RHEL 9 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.7.1-rc1/_images/deploy-new-agent-from-ui1.png) | - | macOS Sonoma x86_64, macOS Sonoma arm
 

## Test description

Test that macOs log data collection works out of the box. 
Test that macOs vulnerability works out of the box.
Test that macOs file integrity monitoring works out of the box.  
Test that macOs security configuration assesment works out of the box.  

## Known issues

- https://github.com/wazuh/wazuh/issues/15580
- https://github.com/wazuh/wazuh/issues/8602
- https://github.com/wazuh/wazuh/issues/16226

## Conclusions 🟢 

Everything work successfully. Illustrate using the table below. 

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|  🟢 |  Wazuh Indexer | | |
| 🟢 |  Wazuh Sever | | |
| 🟢 |  Wazuh Dashboard| | |
| 🟢 |  Wazuh Agent | | |
| 🟢 |  Data collection works out of the box | | |
| 🟢 |  Vulnerability works out of the box | | |
| 🟡   |  FIM works out of the box | | https://github.com/wazuh/wazuh/issues/8602 https://github.com/wazuh/wazuh/issues/16226|
| 🟢 | SCA works out of the box | | |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - It was clear.
- Did you face any challenges not covered by the guideline?
  - None
- Suggestions for improvement:
    - Create the entire environment with AWS machines. It will reduce the problems. 
    - Request the machines specifying the minimum requirements. 
    - To setup the environment you need to use the private IPs.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/early-birds

**Comment by damarisg** [comment]
## Environment Setup

 <details> <Summary>Wazuh Indexer 🟢 </Summary>

### Initial Configuration  🟢

1. Download the Wazuh installation assistant and the configuration file.
 
 ```   
    [root@rhel9 vagrant]#  curl -sO https://packages-dev.wazuh.com/4.7/wazuh-install.sh
    [root@rhel9 vagrant]# curl -sO https://packages-dev.wazuh.com/4.7/config.yml
```
2. Edit `./config.yml`.

  ```
      [root@rhel9 vagrant]# cat config.yml
      nodes:
        # Wazuh indexer nodes
        indexer:
          - name: r91
            ip: 192.168.0.10
          #- name: node-2
          #  ip: "<indexer-node-ip>"
          #- name: node-3
          #  ip: "<indexer-node-ip>"
      
        # Wazuh server nodes
        # If there is more than one Wazuh server
        # node, each one must have a node_type
        server:
          - name: r92
            ip: 192.168.0.11
            node_type: master
          - name: r93
            ip: 192.168.0.12
            node_type: worker
          #- name: wazuh-3
          #  ip: "<wazuh-manager-ip>"
          #  node_type: worker
      
        # Wazuh dashboard nodes
        dashboard:
          - name: r94
            ip: 192.168.0.13
  ```  
          
3. Run the assistant to generate the Wazuh cluster key, certificates, and passwords necessary for installation:

  ```  
     [root@rhel9 vagrant]# bash wazuh-install.sh --generate-config-files
     28/11/2023 13:32:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
     28/11/2023 13:32:34 INFO: Verbose logging redirected to /var/log/wazuh-install.log
     28/11/2023 13:32:46 INFO: --- Configuration files ---
     28/11/2023 13:32:46 INFO: Generating configuration files.
     28/11/2023 13:32:49 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
  ```  

---

### Indexer nodes installation 🟢

1. Run the assistant 

  ```  
    bash wazuh-install.sh --wazuh-indexer r91
    28/11/2023 14:00:00 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
    28/11/2023 14:00:00 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    28/11/2023 14:00:13 WARNING: The system has Firewalld enabled. Please ensure that traffic is allowed on these ports: 9200, 9300.
    28/11/2023 14:00:17 INFO: Wazuh development repository added.
    28/11/2023 14:00:18 INFO: --- Wazuh indexer ---
    28/11/2023 14:00:18 INFO: Starting Wazuh indexer installation.
    28/11/2023 14:04:42 INFO: Wazuh indexer installation finished.
    28/11/2023 14:04:42 INFO: Wazuh indexer post-install configuration finished.
    28/11/2023 14:04:42 INFO: Starting service wazuh-indexer.
    28/11/2023 14:05:17 INFO: wazuh-indexer service started.
    28/11/2023 14:05:17 INFO: Initializing Wazuh indexer cluster security settings.
    28/11/2023 14:05:21 INFO: Wazuh indexer cluster initialized.
    28/11/2023 14:05:21 INFO: Installation finished.
  ```  
---

###  Cluster initialization 🟢

1. Run the assistant 

  ```  
    [root@rhel9 vagrant]# bash wazuh-install.sh --start-cluster
    28/11/2023 14:09:53 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
    28/11/2023 14:09:53 INFO: Verbose logging redirected to /var/log/wazuh-install.log
    28/11/2023 14:10:15 INFO: Wazuh indexer cluster security configuration initialized.
    28/11/2023 14:11:28 INFO: Wazuh indexer cluster started.
  ```  

--- 

###  Testing the cluster installation 🟢

1. Run the following command to get the admin password:
  ```  
    [root@rhel9 vagrant]# tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'admin\'" -A 1
     indexer_username: 'admin'
     indexer_password: 'xxxx'
  ```  
  
2. Run the following command to confirm that the installation is successful. 

  ```  
      curl -k -u admin:<ADMIN_PASSWORD> https://<WAZUH_INDEXER_IP>:9200
      
      {
    "name" : "r91",
    "cluster_name" : "wazuh-indexer-cluster",
    "cluster_uuid" : "75iDO_56RDKefpCshxTVzg",
    "version" : {
      "number" : "7.10.2",
      "build_type" : "rpm",
      "build_hash" : "db90a415ff2fd428b4f7b3f800a51dc229287cb4",
      "build_date" : "2023-06-03T06:24:25.112415503Z",
      "build_snapshot" : false,
      "lucene_version" : "9.6.0",
      "minimum_wire_compatibility_version" : "7.10.0",
      "minimum_index_compatibility_version" : "7.0.0"
    },
    "tagline" : "The OpenSearch Project: https://opensearch.org/"
  }
  ```  
  
3. Check if the cluster is working correctly:

  ```  
    [root@rhel9 vagrant]# curl -k -u admin:4ZqL26mTTIRIcaf2J20lBDpUogem*GPz https://192.168.0.10:9200/_cat/nodes?v
    ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                               cluster_manager name
    192.168.0.10           11          76   0    0.08    0.05     0.07 dimr      data,ingest,master,remote_cluster_client *               r91
    [root@rhel9 vagrant]#
  ```  
  
  
 </details>

**Comment by damarisg** [comment]
I moved the matter to "on hold" until I have the instances from Sonoma.

**Comment by damarisg** [comment]
<details><Summary>Data collection works out of the box 🟢 </Summary>

1. Check connection

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/14bed4fb-e1c8-463d-9520-325ca93bf1e5)

---

## Sonoma x86_64 🟢 

2. Check data collection

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/1ffee301-9987-4104-b9ed-32d97f2da82a)


3. Check dashboard 

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/e870e86c-3d40-48c8-b2f1-dcca7a8358b2)

4. Check Events

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/66e4d249-60e0-47b9-8629-476ac059f7ce)


5. Check Inventory data

    ![Uploading imagen.png…]()

---

## Sonoma ARM 🟢 

2. Check data collection

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/09506ad3-f8ec-4563-8330-8878a9ca722e)

3. Check dashboard 

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/7447adf3-a296-46e8-8513-66e84cba3e9b)

4. Check Events

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/6d0ce7ab-5d42-479b-bc35-333ebe13eaae)

5. Check Inventory data

    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/a1993f56-c250-4933-860b-7a9130fd787c)


</details>

**Comment by damarisg** [comment]
## Vulnerability works out of the box 🟢 

_Note: Enable Vulnerability Detection section on Wazuh Server._

<details><Summary> Sonoma x86_64 🟢 </Summary>

1. Check vulnerabilities on Server are working

   ```   
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '000'
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '001' vulnerabilities.
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '001'
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '002' vulnerabilities.
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '002'
      2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.
   ```   

2. Check Dashboard. 

    There are not vulnerabilities.
    
    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/69462c40-537c-444f-85b2-b94cb8102a37)

</details>


<details><Summary>  Sonoma ARM 🟢 </Summary>

1. Check vulnerabilities on Server are working

     ```   
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '000' vulnerabilities.
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '000'
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '001' vulnerabilities.
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '001'
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5450): Analyzing agent '002' vulnerabilities.
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5471): Finished vulnerability assessment for agent '002'
        2023/11/30 13:40:31 wazuh-modulesd:vulnerability-detector: INFO: (5472): Vulnerability scan finished.
     ```   
 
2. Check Dashboard. 

    There are not vulnerabilities 
    
    ![imagen](https://github.com/wazuh/wazuh/assets/3978434/d8d27c4d-db10-4bf1-9b05-b854aedc6283)

</details>

**Comment by cborla** [comment]
LGTM!

**Comment by davidjiglesias** [comment]
Why is the "FIM works out of the box" section accepted without alerts? @damarisg @cborla

**Comment by damarisg** [comment]
Doubts clarified.
