### ISSUE TITLE
Release 4.7.1 - RC 1 - E2E UX tests - Security Configuration Assessment

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#20460]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.1-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/security-warriors team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Nov 29, 2023 and notify the @wazuh/security-warriors team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/security-warriors team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Nov 30, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 01, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.7.1-rc1/quickstart.html) | - | RHEL 9 x86_64 |
| Server | [Quickstart](https://documentation-dev.wazuh.com/v4.7.1-rc1/quickstart.html) | - | RHEL 9 x86_64 |
| Dashboard | [Quickstart](https://documentation-dev.wazuh.com/v4.7.1-rc1/quickstart.html) | - | RHEL 9 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.7.1-rc1/installation-guide/wazuh-agent/index.html) | - | Windows server 2016 x86_64, Debian 10 x86_64, Fedora 38 x86_64, macOS Ventura arm |

## Test description

For the selected Wazuh Agent OS:
- Check that their respective SCA policies are applied properly
- Use and activate a custom policy for any of them
- Disable an used policy and confirm it is not used anymore
- Push SCA config through centralized config and check it applies properly

## Known issues

- https://github.com/wazuh/wazuh-packages/issues/1422
- https://github.com/wazuh/wazuh/issues/12347

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢|  Deploy Wazuh components|  |  | 
| 🟢|  Wazuh agent installation on Debian 10| |  | 
| 🟢|  Wazuh agent installation on Ubuntu 22| |  | 
| 🟢|  Wazuh agent installation on Windows Server 2016| |  | 
| 🟢|  Wazuh agent installation on macOS | | | 
| 🟢|  Check that their respective SCA policies are applied properly| | Work fine for all the endpoints | 
| 🟢| Use and activate a custom policy for any of them| |  | 
| 🟢|  Disable an used policy and confirm it is not used anymore| |  | 
| 🟢|  Push SCA config through centralized config and check it applies properly| |  Worked for all the endpoints but we found a typo in the documentation for Windows endpoints. I am currently creating an issue for it for the documentation team| 

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  -  Yes
- Did you face any challenges not covered by the guideline?
  - Yes
- Suggestions for improvement:
  - Modify the path for shared configuration for Windows endpoints in the documentation

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/security-warriors

**Comment by TheMuntu** [comment]
## 1. Deploy environment


<details>
<summary>🟢 Wazuh components installation </summary>

```


```

</details>


<details>
<summary>🟢 Wazuh agent installation on Debian 10 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on Fedora 38 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on Windows server 2016</summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on macOS Ventura arm </summary>


```


```

</details>

**Comment by adavinchi** [comment]
## 1. Install environment


<details>
<summary>🟢 Wazuh components installation </summary>

Installation was done using quickstart

```shellsession

[root@ip-172-31-5-130 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
29/11/2023 09:48:51 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
29/11/2023 09:48:51 INFO: Verbose logging redirected to /var/log/wazuh-install.log
29/11/2023 09:49:00 INFO: --- Dependencies ---
29/11/2023 09:49:00 INFO: Installing lsof.
29/11/2023 09:49:12 ERROR: Your system does not meet the recommended minimum hardware requirements of 4Gb of RAM and 2 CPU cores. If you want to proceed with the installation use the -i option to ignore these requirements.
[root@ip-172-31-5-130 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.7/wazuh-install.sh && sudo bash ./wazuh-install.sh -a -i
29/11/2023 09:51:05 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.1
29/11/2023 09:51:05 INFO: Verbose logging redirected to /var/log/wazuh-install.log
29/11/2023 09:51:15 WARNING: Hardware and system checks ignored.
29/11/2023 09:51:15 INFO: Wazuh web interface port will be 443.
29/11/2023 09:51:18 INFO: Wazuh development repository added.
29/11/2023 09:51:18 INFO: --- Configuration files ---
29/11/2023 09:51:18 INFO: Generating configuration files.
29/11/2023 09:51:20 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
29/11/2023 09:51:20 INFO: --- Wazuh indexer ---
29/11/2023 09:51:20 INFO: Starting Wazuh indexer installation.
29/11/2023 09:53:13 INFO: Wazuh indexer installation finished.
29/11/2023 09:53:13 INFO: Wazuh indexer post-install configuration finished.
29/11/2023 09:53:13 INFO: Starting service wazuh-indexer.
29/11/2023 09:53:28 INFO: wazuh-indexer service started.
29/11/2023 09:53:28 INFO: Initializing Wazuh indexer cluster security settings.
29/11/2023 09:53:38 INFO: Wazuh indexer cluster initialized.
29/11/2023 09:53:38 INFO: --- Wazuh server ---
29/11/2023 09:53:38 INFO: Starting the Wazuh manager installation.
29/11/2023 09:54:33 INFO: Wazuh manager installation finished.
29/11/2023 09:54:33 INFO: Starting service wazuh-manager.
29/11/2023 09:54:50 INFO: wazuh-manager service started.
29/11/2023 09:54:50 INFO: Starting Filebeat installation.
29/11/2023 09:54:57 INFO: Filebeat installation finished.
29/11/2023 09:54:58 INFO: Filebeat post-install configuration finished.
29/11/2023 09:54:58 INFO: Starting service filebeat.
29/11/2023 09:54:59 INFO: filebeat service started.
29/11/2023 09:54:59 INFO: --- Wazuh dashboard ---
29/11/2023 09:54:59 INFO: Starting Wazuh dashboard installation.
29/11/2023 09:56:40 INFO: Wazuh dashboard installation finished.
29/11/2023 09:56:40 INFO: Wazuh dashboard post-install configuration finished.
29/11/2023 09:56:40 INFO: Starting service wazuh-dashboard.
29/11/2023 09:56:40 INFO: wazuh-dashboard service started.
29/11/2023 09:57:10 INFO: Initializing Wazuh dashboard web application.
29/11/2023 09:57:11 INFO: Wazuh dashboard web application initialized.
29/11/2023 09:57:11 INFO: --- Summary ---
29/11/2023 09:57:11 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: LvNXUe******************
29/11/2023 09:57:11 INFO: Installation finished.
[root@ip-172-31-5-130 ec2-user]#

[root@ip-172-31-5-130 ec2-user]# rpm -q wazuh-manager
wazuh-manager-4.7.1-1.x86_64
[root@ip-172-31-5-130 ec2-user]# rpm -q wazuh-dashboard
wazuh-dashboard-4.7.1-1.x86_64
[root@ip-172-31-5-130 ec2-user]# rpm -q wazuh-indexer
wazuh-indexer-4.7.1-1.x86_64
[root@ip-172-31-5-130 ec2-user]#



```

<img width="951" alt="image" src="https://github.com/wazuh/wazuh/assets/120424104/af7abefa-20b5-4ee8-b0c0-ec27f524a698">

</details>


<details>
<summary>🟢 Wazuh agent installation on Debian 10 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on Fedora 38 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on Windows server 2016</summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent installation on macOS Ventura arm </summary>


```


```

</details>

**Comment by adavinchi** [comment]
## 3. Check 2: Use and activate a custom policy for any of them

<details>
<summary>🟢 Wazuh agent on Debian 10 </summary>


```shellsession


```

</details>

<details>
<summary>🟢 Wazuh agent  on Fedora 38 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent on Windows server 2016</summary>



</details>

<details>
<summary>🟢 Wazuh agent  on macOS Ventura arm </summary>


```


```

</details>

**Comment by adavinchi** [comment]
## 5. Check 3: Disable an used policy and confirm it is not used anymore

<details>
<summary>🟢 Wazuh agent on Debian 10 </summary>


```shellsession


```

</details>

<details>
<summary>🟢 Wazuh agent  on Fedora 38 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent on Windows server 2016</summary>



</details>

<details>
<summary>🟢 Wazuh agent  on macOS Ventura arm </summary>


```


```

</details>

**Comment by adavinchi** [comment]
## 6. Check 4: Push SCA config through centralized config and check it applies properly

<details>
<summary>🟢 Wazuh agent on Debian 10 </summary>


```shellsession


```

</details>

<details>
<summary>🟢 Wazuh agent  on Fedora 38 </summary>


```


```

</details>

<details>
<summary>🟢 Wazuh agent on Windows server 2016</summary>



</details>

<details>
<summary>🟢 Wazuh agent  on macOS Ventura arm </summary>


```


```

</details>

**Comment by MarcelKemp** [comment]
## Review

On the one hand, **`Ubuntu x86_64`** has been tested, when the issue says to test **`Fedora 38 x86_64`**. 

In this case, I would say that this is not a problem to retest, as the status of **_Fedora 38_** is that it does not have official SCA policies, as seen in previous E2E issues:
- https://github.com/wazuh/wazuh/issues/18833#issuecomment-1714394298
- https://github.com/wazuh/wazuh/issues/18306
> No official SCA policies are available ([check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).
> Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

Still, be careful not to miss it in future issues.


On the other hand, I see that for `v4.7.1`, **_macOS 14 (Sonoma)_** SCA policies have been included, so it would be good to test it to verify that the new policies work correctly:
- https://github.com/wazuh/wazuh/pull/20371

For the rest, LGTM.

**Comment by davidjiglesias** [comment]
LGTM!
