### ISSUE TITLE
Release 4.7.1 - Release Candidate 1 - Demo use cases

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#20486]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release candidate issue** |  #20463                                   |
| **Version**                      | 4.7.1                                                   |
| **Release candidate**            | RC 1                                                     |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.7.1-rc1          |
| **Previous Demo use cases**      | #20074                                                   |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:green_circle:     | Audit                  |        |
:green_circle:     | AWS Wodle              |        | 
:green_circle:     | Brute force            |        |
:green_circle:     | Docker                 |        |
:green_circle:     | Emotet                 |   | 
:green_circle:     | FIM                    |        |
:green_circle:     | IP Reputation          |        | 
:green_circle:     | Netcat                 |        | 
:green_circle:     | Osquery                |        | 
:green_circle:     | Shellshock             |        |  
:green_circle:     | SQL Injection          |        | 
:green_circle:     | Slack                  |        | 
:green_circle:     | Suricata               |        |   
:green_circle:     | Trojan                 |        |
:green_circle:     | Virustotal             |        | 
:green_circle:     | Vulnerability Detector |        |
:green_circle:     | Yara                   |        | 
:green_circle:     | Windows Defender       |  | 

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Conclusion

The demo environment and its related tests were successful.

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias 
- [x] @teddytpc1

**Comment by damarisg** [comment]
LGTM!
