### ISSUE TITLE
How to view what changed in the wazuh app web interface

### ISSUE THREAD

**Issue by wafabenhamouda** [wazuh/wazuh#2051]
# [Syscheck] How to view what changed in the wazuh app web interface

| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | rev | branch |

Hello every body,

I have a little problem. In fact, I could not see **what changed** in the wazuh web interface.
I just can see that the integrity cheksum changed but I want to see what changed in the file as I can see it in the /var/ossec/logs/alerts/alerts.log file.

For example, I have this output in the alerts.log file:
** Alert 1544431445.3221536: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Dec 10 09:44:05 (TUNTRUST-TEST) 192.168.130.31->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/etc/hosts' checksum changed.
Size changed from '638' to '621'
Old md5sum was: '0cab53ee4281b278a4f67afc61c552c7'
New md5sum is : '49747c064c0f17592fdab6fcd3130216'
Old sha1sum was: '702a76ae1a2499df27692c65b3062a4a8b04b109'
New sha1sum is : '8853e29ca8b1a008c18d94222bc66d706383c55d'
Old sha256sum was: 'ab438181334dd39028887bd6efeeb1ee0b88a39a127074ce561703e50ddcab6b'
New sha256sum is : 'b408363112a2bf37b9cb0fd9e85a732d6fc19623b6b9526487b6c37f0dedad72'
Old modification time was: 'Mon Dec 10 07:49:00 2018', now it is 'Mon Dec 10 09:06:42 2018'
What changed:
15d14
< ################

Attributes:
 - Size: 621
 - Permissions: 100644
 - Date: Mon Dec 10 09:06:42 2018
 - Inode: 2228255
 - User: root (0)
 - Group: root (0)
 - MD5: 49747c064c0f17592fdab6fcd3130216
 - SHA1: 8853e29ca8b1a008c18d94222bc66d706383c55d
 - SHA256: b408363112a2bf37b9cb0fd9e85a732d6fc19623b6b9526487b6c37f0dedad72

My goal is to see all this details in the web interface.
You will find attached the web interface that I currently see.
![wazuh app](https://user-images.githubusercontent.com/45624257/49720658-ae87de80-fc60-11e8-89c5-705822c89b39.PNG)

Any help is appreciated.

BR,
Wafa Ben Hamouda

**Comment by Cerv1** [comment]
Hello @wafabenhamouda, 

If you want to get further details on a particular alert, you need to go to the **dicover tab**.

![image](https://user-images.githubusercontent.com/11405177/50211401-ce15ba00-0378-11e9-83d9-64fae216b7aa.png)

Once you're here, you can open your FIM event and get the following information.

![image](https://user-images.githubusercontent.com/11405177/50211610-5bf1a500-0379-11e9-8df8-49a37368e219.png)

If this doesn't solve your problem or you have any question, don't hesitate to contact us again.

Best regards,
Cerv1.

**Comment by wafabenhamouda** [comment]
Hello,

Thank yyou.

BR,
