### ISSUE TITLE
Support ISO characters in Basic Authentication 

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20526]
|Wazuh version|Component|
|---|---|
| master | API |

## Description
The current API does not support ISO characters in the user and password fields of the Basic Authentication method.

It is possible to add support to the API by developing a custom Authorization class based on the BasicAuthentication class provided by the Connexion 3.0 package.

## Checks
The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
We will not do this for now since it is not a requirement requested by users or the dashboard team.
