### ISSUE TITLE
Missing available regions in AWS module

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#20539]
| Affected integration |
|---|
| AWS|

## Description

A user has reported that the AWS integration does not detect the region as valid, but we can see from the [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) that it is, although it is an Opt-in region. Also, there is no indication in the [module documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html#service-regions) that there is any limitation on regions.

In addition, we can see in the integration that the list of available regions is shorter than the AWS one:

https://github.com/wazuh/wazuh/blob/eb29da47d7253bedd10e34a281cccf221a5839eb/wodles/aws/aws_s3.py#L107-L110

<details><summary>AWS configuration</summary>

<p>

```xml
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>5m</interval>
  <run_on_start>yes</run_on_start>
  <service type="cloudwatchlogs">
    <aws_profile>default</aws_profile>
    <aws_log_groups>XXXXX</aws_log_groups>
    <regions>ap-south-2</regions>
  </service>
</wodle>
```
</p>

</details>

<details><summary>AWS logs</summary>

<p>

```
2023/11/30 19:02:46 wazuh-modulesd:aws-s3[258461] wm_aws.c:662 at wm_aws_run_service(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --service cloudwatchlogs --aws_profile default --regions ap-south-2 --aws_log_groups XXXXX --debug 2
2023/11/30 19:02:46 wazuh-modulesd:aws-s3[258461] wm_aws.c:677 at wm_aws_run_service(): WARNING: Service: cloudwatchlogs  -  Returned exit code 22
2023/11/30 19:02:46 wazuh-modulesd:aws-s3[258461] wm_aws.c:696 at wm_aws_run_service(): WARNING: Service: cloudwatchlogs  -  The region 'ap-south-2' is not a valid one.
```
</p>

</details>

## Tasks
- [ ] Test in a manager.
- [ ] Test in an agent.
- [ ] Unit tests without failures. Updated if there are any relevant changes.
- [ ] Integration tests without failures. Updated if there are any relevant changes.
- [ ] Update the documentation if necessary.
- [ ] Add entry to the changelog if necessary.

**Comment by amichel-vp** [comment]
There is also a problem with the regex to check the aws region format line 3836 : 

```diff
-        if not re.match(r'^([a-z]{2}(-gov)?)-([a-z]{4,7})-\d$', arg_region):
+       if not re.match(r'^([a-z]{2}(-gov)?)-([a-z]+)-\d$', arg_region):
           raise argparse.ArgumentTypeError(
                f"WARNING: The region '{arg_region}' has not a valid format.'"
            )
 ```
