### ISSUE TITLE
Packages for postgresql/mysql

### ISSUE THREAD

**Issue by roboneci** [wazuh/wazuh#20538]
Hello,

if we want to use database output we need to compile whole wazuh from sources.
It is possible to create packages wazuh-psql and wazuh-mysql so we can use package manager for wazuh and not source code?

Thank you.

**Comment by juliancnn** [comment]
Hello @robonecim,

Thank you for reaching out with your query about using database output with Wazuh. You're correct that to enable specific features like database output, you may need to compile Wazuh from the source with the appropriate flags.

Regarding your suggestion for creating separate packages like `wazuh-psql` and `wazuh-mysql`, it's an interesting idea. While we currently don't offer these as pre-compiled packages, you can indeed generate custom packages yourself. We have detailed documentation that guides you through the process of packaging Wazuh. With some basic Bash scripting skills, you can modify the script to include the compile flags for database support. You can find this guide here:

🔗 [Wazuh Packaging Documentation](https://documentation.wazuh.com/current/development/packaging/index.html)

Additionally, I recommend keeping an eye on an open issue related to `wazuh-dbd`, which might be relevant to your interests. You can follow the discussion and updates here:

🔗 [GitHub Issue - Wazuh-DBD](https://github.com/wazuh/wazuh/issues/14081)

If you have any more questions or need further assistance, feel free to ask!
