### ISSUE TITLE
Content Manager - Implement the `CtiSnapshotDownloader` class

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#20536]
|Component|
|---|
| [content_manager](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/content_manager) |

## Description

This issue aims to work on the creation of a class in charge of downloading the snapshot file from the CTI API.

## Expected

Once this issue is finished, we should expect the following:

- A class called `CtiSnapshotDownloader` capable of:
  - Download the snapshot file from the CTI API.
  - Save the content on disk.
- This class should be a stage of an orchestration.
- This class should be independent from the rest of the chain, allowing us to test it with unit tests.
- Add this stage to the related factory.

## DoD

- [x] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [x] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [x] Add or Update any relevant documentation to reflect the changes made.

**Comment by tsarquis88** [comment]
## Update

PR on draft: #20543 

Missing tests and documentation.
