### ISSUE TITLE
Preload dynamic labels from Wazuh DB

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2055]
|Main task|Component|
|---|---|
|#1004|Analysisd|

Analysisd will store Syscollector inventory data on the memory in order to enrich alerts and archives with automatic labels.

When the manager starts, there is no inventory data on the memory, then the produced alerts won't include automatic labels until the agents send a Syscollector report.

So Analysisd must query Wazuh DB the first time it tries to get the cached data for each agent.

## Subtasks

- [x] Implement a new call in Wazuh DB to query Syscollector data for an agent.
- [x] Implement a condition in the label composer to query Wazuh DB if there is no cached data and this function has no previously queried such data. This will prevent Analysisd from continuously querying Wazuh DB when it does not also has inventory data for that agent.

**Comment by Skeptor** [comment]
The condition to query Wazuh DB just one time and only if there is no cached data is in this commit: https://github.com/wazuh/wazuh/commit/28df451254f31de760aee7088edee661cf1fb51e
