### ISSUE TITLE
Increase in the disk usage for logcollector

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#20578]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.7.1-rc1 |  Agent | Packages | Ubuntu  |

Testing: https://github.com/wazuh/wazuh/issues/20554

It was possible to evidence a significant increase in the disk usage for logcollector in the Ubuntu agent

- 4.7.1-rc1: #20554 

![image](https://github.com/wazuh/wazuh/assets/80041853/c6cd3ef1-032b-434c-8139-0a1d3d81dd84)

- 4.7.0-rc1: #20304
![image](https://github.com/wazuh/wazuh/assets/80041853/710a998a-4bb9-43c8-b7c3-74e11bfc4ef8)

**Comment by LucioDonda** [comment]
Based on those graphs it seems to be an issue but searching further I've found:
* Disk Read bytes have been changing significantly with each version.
* In the last logcollector footprint tests, the peak values tend to reach 2E7 (which is the value shown on the last one).
* The previous test that was used for comparison doesn't look coherent with previous cases, especially while analyzing the logcollector daemon (in almost all the tests it shows `0`)

Last footprint tests comparison chart (using average values taken from the plots and metrics on Bytes scaled by 1E7):
| Test - Daemon | 4.7.1 RC1     | 4.7.0 RC1     | 4.7.0 Alpha2     |4.6.0 RC2     | 4.6.0 RC2     |   4.6.0 RC1    | 
|------------|------------|------------|------------|------------|------------|------------ | 
| Disk Read - Agentd | 2 | 1.2 | [4-5] | 2 | 2.6  | 2.5 | 
| Disk Read - logcollector  | 2 | 0 | 2.5  | 0.75 | 1.7  | 1.8 |
