### ISSUE TITLE
`wazuh-modulesd` increases disk usage when stressing `SCA`

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#20579]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.7.1-rc1 | wazuh-modulesd | Agent | Packages | Ubuntu 20 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20560, a considerable disk increase has been found compared to lower versions

- [v4.7.1-rc1](https://github.com/wazuh/wazuh/issues/20560)

![image](https://github.com/wazuh/wazuh/assets/14913942/e74f815f-d7a0-49d8-b655-0904a98fd788)

- [4.7.0-rc1](https://github.com/wazuh/wazuh/issues/20305)

![image](https://github.com/wazuh/wazuh/assets/14913942/41eff203-3c44-4e50-b6c9-9a6cc2162f95)

In versions prior to 4.7.1, stability has been observed with values around 120-150

It does not seem that the disk reading or writing acts according to these plots, since they have similar values in said phase

It is necessary to determine the cause of this behavior.

**Comment by cborla** [comment]
## Disk usage analysis in Ubuntu agent

### Graph Analysis
To determine the reason for the decrease in disk usage, some test plots were analyzed.
- Disk read
  - About the same
- Disk written
  - About the same	

### % Disk 
The following table shows the percentage differences in disk usage between versions 4.7.0 and 4.7.1, analyzing only the area prior to the start of the stress test.

| Version | Percentage Accumulated | Samples analyzed | %Disk usage/sec |
|---|---|---|---|
|4.7.0|270700|19894|2.72|
|4.7.1|399810|19564|4.08|

### Conclusion
- The graphs described do not denote any problem in the use of the disk, no leaks are visible.
- The average percentage difference between the 2 versions is arround 50%.
