### ISSUE TITLE
Wrong config when upgrading to v4.8 prevents manager from starting

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#20581]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8 | - | Manager | Sources | - |

# Description
When upgrading from version 4.7 to version 4.8 using the `install.sh` script, the manager `v4.8` ([vulndet-refactor](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor) branch) fails to start:

```
2023/11/30 17:02:36 wazuh-csyslogd: ERROR: (1230): Invalid element in the configuration: 'vulnerability-detector'.
2023/11/30 17:02:36 wazuh-csyslogd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
2023/11/30 17:02:36 wazuh-csyslogd: CRITICAL: (1202): Configuration error at 'etc/ossec.conf'.
```
The problem was that the `ossec.conf` remained with the deprecated `vulnerability-detector` config block and was also missing the new   `vulnerability-detection` and `indexer` blocks.

After manually fixing the `ossec.conf` file the manager started correctly.

# Expected

The purpose of this issue is to add the `indexer` configuration in the `ossec.conf` file, without needing user intervention.

> [!NOTE]  
> The error related to the `vulnerability-detector` configuration will be resolved in another issue: https://github.com/wazuh/wazuh/issues/20952

# DoD
- [x] These changes only apply in case of an upgrade.
- [x] These changes do not affect a new installation.

**Comment by kevin-mcm** [comment]
# Update

- Trying to replicate in a local environment.
- Seems to be a problem with the scripts `install.sh` and `update.sh`
- Debugging and doing some tests

**Comment by kevin-mcm** [comment]
# Update

- Debugging and doing some tests with changes in `install.sh` and `update.sh`

**Comment by kevin-mcm** [comment]
# Update

- Changes in the script `install.sh` and `update.sh` when there's and update of wazuh-manager
- Doing some tests with the latest changes

**Comment by kevin-mcm** [comment]
# Update
- Add documentation in the `replace_vulnerability_detector.sh` script
- Refactor and move `VULN_TEMPLATE` and `INDEXER_TEMPLATE` as parameter

**Comment by sebasfalcone** [comment]
# Update

- Proposal to align with sh on [this branch](https://github.com/wazuh/wazuh/tree/fixes-20581-upgrade-vulnerability-detector-to-vulnerability-detection)

**Comment by kevin-mcm** [comment]
# Update

- Refactor and move logic to `wazuh.sh`
- Add case for versions without VD less than wazuh v4.8

**Comment by kevin-mcm** [comment]
# Update

- Implemented new logic to add a new `<ossec_config>` block with the `indexer` configuration.
