### ISSUE TITLE
ossec.log not rotated in VDR stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#20588]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| At least v4.7.1-rc1 | wazuh-agentd | Agent | Packages | CentOS 7<br>Ubuntu 20 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20562 it has been found that the rotations of the ossec.log file have not been carried out for 3 days, this file containing the logs of said days.

This behavior has been detected in [v4.7.1-rc1](https://github.com/wazuh/wazuh/issues/20562) and [v4.7.0-rc1](https://github.com/wazuh/wazuh/issues/20295), but not in [v4.7.0-alpha2](https://github.com/wazuh/wazuh/issues/20070), where there are rotated files, it is necessary to determine the reason why said log is not rotating

**Comment by Dwordcito** [comment]
It is because of the rotation. Infrequent.
