### ISSUE TITLE
Update documentation for `reference` field

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#20597]
## Description
The current documentation inaccurately mentions a `reference` field when referring to `item_id`. This discrepancy causes confusion and potentially leads to incorrect usage. The proposed solution is to update the documentation to accurately reflect the use of `item_id` without referencing a non-existent `reference` field.

## DoD
- [x] Correct documentation.
- [ ] Pass review from the documentation team.

## Subtasks
- [x] Development -> 12/05
- [ ] Tests/review -> TBD

**Comment by Dwordcito** [comment]
Merged.
