### ISSUE TITLE
Upgrade Werkzeug version to 3.0.1 or a version <=2.3.8

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#20602]
|Wazuh version|Component|
|---|---|
| 4.9.0 | Embedded python | 

During the [Weekly vulnerability scan](https://github.com/wazuh/internal-devel-requests/issues/529), It was found that the Werkzeug version currently used in the Python embedded version (2.2.3) contains a vulnerability that is fixed in version 3.0.1, version 2.3.8 and higher

The issue tends to investigate the package to determine a version to target and upgrade the package.

<details><summary> Vulnerability report </summary>

```json
        {
            "package_name": "werkzeug",
            "package_version": "2.2.3",
            "package_affected_version": "<2.3.8",
            "vuln_description": "Werkzeug 3.0.1 and 2.3.8 include a security fix: Slow multipart parsing for large parts potentially enabling DoS attacks.\r\nhttps://github.com/pallets/werkzeug/commit/b1916c0c083e0be1c9d887ee2f3d696922bfc5c1",
            "safety_id": "62019"
        }
```

 </details>

**Comment by nico-stefani** [comment]
I've been investigating if it's possible to include this update in the release `4.7.2`.

**Comment by nico-stefani** [comment]
Currently, we have a limitation in upgrading this dependency because the version of connexion, `2.14.2`, that we are using in `4.8.0` specifies [Wekzeug<2.3](https://github.com/spec-first/connexion/blob/e8408406f6381657c7f0dc18b34bfd7efd980d91/setup.py#L28) in his dependencies.
So, we must wait until we complete #16504 to upgrade.

**Comment by mhamra** [comment]
### UPDATE
Connexion==3.0.5 requires werkzeug > 2.2.1 and Flask==2.2.5 requires werkzeug >= 2.2.2

**Comment by RamosFe** [comment]
## Update

After updating `connexion` in Issue https://github.com/wazuh/wazuh/issues/20795, this is the dependency tree:
```
connexion==3.0.5
├── asgiref [required: >=3.4, installed: 3.8.1]
│   └── typing_extensions [required: >=4, installed: 4.5.0]
├── httpx [required: >=0.23, installed: 0.27.0]
│   ├── anyio [required: Any, installed: 4.3.0]
│   │   ├── exceptiongroup [required: >=1.0.2, installed: 1.2.0]
│   │   ├── idna [required: >=2.8, installed: 2.9]
│   │   ├── sniffio [required: >=1.1, installed: 1.3.1]
│   │   └── typing_extensions [required: >=4.1, installed: 4.5.0]
│   ├── certifi [required: Any, installed: 2023.7.22]
│   ├── httpcore [required: ==1.*, installed: 1.0.4]
│   │   ├── certifi [required: Any, installed: 2023.7.22]
│   │   └── h11 [required: >=0.13,<0.15, installed: 0.14.0]
│   ├── idna [required: Any, installed: 2.9]
│   └── sniffio [required: Any, installed: 1.3.1]
├── inflection [required: >=0.3.1, installed: 0.3.1]
├── Jinja2 [required: >=3.0.0, installed: 3.1.3]
│   └── MarkupSafe [required: >=2.0, installed: 2.1.2]
├── jsonschema [required: >=4.0.1, installed: 4.20.0]
│   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   ├── jsonschema-specifications [required: >=2023.03.6, installed: 2023.12.1]
│   │   └── referencing [required: >=0.31.0, installed: 0.31.1]
│   │       ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │       └── rpds-py [required: >=0.7.0, installed: 0.18.0]
│   ├── referencing [required: >=0.28.4, installed: 0.31.1]
│   │   ├── attrs [required: >=22.2.0, installed: 23.1.0]
│   │   └── rpds-py [required: >=0.7.0, installed: 0.18.0]
│   └── rpds-py [required: >=0.7.1, installed: 0.18.0]
├── python-multipart [required: >=0.0.5, installed: 0.0.9]
├── PyYAML [required: >=5.1, installed: 5.3.1]
├── requests [required: >=2.27, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   ├── idna [required: >=2.5,<4, installed: 2.9]
│   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.18]
├── starlette [required: >=0.27,<0.33, installed: 0.32.0.post1]
│   └── anyio [required: >=3.4.0,<5, installed: 4.3.0]
│       ├── exceptiongroup [required: >=1.0.2, installed: 1.2.0]
│       ├── idna [required: >=2.8, installed: 2.9]
│       ├── sniffio [required: >=1.1, installed: 1.3.1]
│       └── typing_extensions [required: >=4.1, installed: 4.5.0]
├── typing_extensions [required: >=4, installed: 4.5.0]
└── Werkzeug [required: >=2.2.1, installed: 2.2.3]
    └── MarkupSafe [required: >=2.1.1, installed: 2.1.2]

```

We should update `Werkzeug` to `3.0.1`.

**Comment by RamosFe** [comment]
## Update

The package was upgraded in Issue https://github.com/wazuh/wazuh/issues/20795. The conclusion is the same for this issue and is described in the following comment https://github.com/wazuh/wazuh/issues/20795#issuecomment-2037780949.

**Comment by fdalmaup** [comment]
# Review

As the objective of this issue is being fulfilled in the https://github.com/wazuh/wazuh/issues/20795 issue (check the [requirements.txt](https://github.com/wazuh/wazuh/pull/22680/files#diff-ac0d503454a85f64c8021ded91db3e9afddcc51dd88864ca250ac0e199da797aR75) file) as mentioned above, we can close this one without linking it to the #22680 PR.

LGTM!
