### ISSUE TITLE
getting wazuh-analysisd: ERROR: dbsync and  wazuh-db: ERROR: DB

### ISSUE THREAD

**Issue by piyush151993** [wazuh/wazuh#20606]
Wazuh manager Version : 4.2

We are getting the below error logs in /var/ossec/log/ossec.log
======================

023/12/04 14:22:16 wazuh-db: ERROR: DB(20745) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-db: ERROR: DB(20745) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(20745) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-db: ERROR: DB(21550) fim/save request with no file path argument.
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck
2023/12/04 14:22:16 wazuh-analysisd: ERROR: dbsync: Bad response from database: Cannot save Syscheck

======================

I have already try to remove all the db file from /var/ossec/queue/db/* and /var/ossec/var/db/* and reinstall the wazuh manager but not getting any success.

So kindly help me to resolve the issue.

**Comment by piyush151993** [comment]
Hi pereyra-m

Thanks for your update but still we are not able to understand that why Wazuh api stops working in every half hours kindly refer to the attached screenshot for the same.

![wazuh](https://github.com/wazuh/wazuh/assets/152854350/c8a76cf8-8131-453c-9959-2cb76417e18a)

**Comment by piyush151993** [comment]
Hi MiguelazoDS,

As I checked and found that some of the agents are on 4.5 version and wazuh manger is on 4.2 version so might be due to this we are getting the db synced issue.

But our concern in why Wazuh api stops working in every half an hour.

**Comment by piyush151993** [comment]
HI MiguelazoDS 

Kindly find the below result for the mention command:
![api](https://github.com/wazuh/wazuh/assets/152854350/2609fa55-6255-4fc8-8a4f-f1f7bc2cb8fc)

**Comment by MiguelazoDS** [comment]
The error code was not really helpful, my bad there. 

![image](https://github.com/wazuh/wazuh/assets/13010397/96fb9958-663b-403c-9e24-ea51571eed61)

I just wanted to be sure you can use the API in the command line. For example with something like this

curl -k -X GET "https://localhost:55000/manager/status" -H "Authorization: Bearer $TOKEN"

I reproduced the most common error which is changing the credentials for API and not updating them in the UI. But the error code is not the same. 

Please expand the tab marked with a red circle.

![image](https://github.com/wazuh/wazuh/assets/13010397/38f4487f-333e-4b79-a749-3df98886a6e0)

You said this happens every half an hour, how do you fix this each time?
