### ISSUE TITLE
Fix code scanning alert - Use of possibly insecure function - consider using safer ast.literal_eval.

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#20604]
During the [48th Weekly vulnerability scan](https://github.com/wazuh/internal-devel-requests/issues/529), It was found that the framework code has a possible insecure function. 

This issue tends to investigate the function make a conclusion on the function insecurity and fix it.

Tracking issue for:
- [x] https://github.com/wazuh/wazuh/security/code-scanning/622

**Comment by GGP1** [comment]
## Update

Replaced `eval()` with `ast.literal_eval()` and validated that everything worked correctly after the changes.

**Comment by GGP1** [comment]
## Closing

Using `ast.literal_eval` would only work for the known exceptions that are encoded to JSON, unknown exceptions are passed as plain strings and that causes `ast.literal_eval` to panic, a more detailed explanation can be found [here](https://github.com/wazuh/wazuh/pull/20640#discussion_r1422385752).

Considering the input data is generated by ours and cannot be manipulated by the user, we decided to keep `eval` in this specific scenario.
