### ISSUE TITLE
Windows Agent connection socket error: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20608]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1-rc1 | Agentd | Agent | Packages | Windows Server 2016 |

## Description

During the [v4.7.1-rc1 LOGCOLLECTOR, SYSCOLLECTOR Footprint test](https://github.com/wazuh/wazuh/issues/20567), the following errors were observed in the Windows agent:

```plaintext
2023/11/28 10:39:42 wazuh-agent: WARNING: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.
2023/11/28 10:39:42 wazuh-agent: ERROR: Connection socket: An established connection was aborted by the software in your host machine. (10053)
2023/11/28 10:39:42 wazuh-agent: ERROR: (1137): Lost connection with manager. Setting lock.
```

These errors lead to the disconnection of the agent.

Possibly related to: [wazuh-jenkins #4867](https://github.com/wazuh/wazuh-jenkins/issues/4867)

## Evidences

- [Windows Agent Logs](https://github.com/wazuh/wazuh/files/13544326/ossec_Test_stress_B4605_windows_2023-11-30.1.zip)
- [Windows Agent metrics](https://github.com/wazuh/wazuh/files/13544329/monitor-winagent-Test_stress_B4605_windows-pre-release.csv)
- [Windows Agentd State](https://github.com/wazuh/wazuh/files/13544324/Test_stress_B4605_windows_agentd_state.csv)

**Comment by nbertoldo** [comment]
By checking the logs, it can be seen that these error messages appear only once at the beginning of the test, when the agent starts.
At this moment there is a restart because the agent receives from the manager the centralised configuration. This is an expected behaviour.
```
2023/11/28 10:39:39 wazuh-agent: WARNING: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.
2023/11/28 10:39:40 wazuh-agent: WARNING: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.
2023/11/28 10:39:41 wazuh-agent: WARNING: (1218): Unable to send message to 'server': An established connection was aborted by the software in your host machine.
2023/11/28 10:39:41 wazuh-agent: INFO: Agent is restarting due to shared configuration changes.
2023/11/28 10:39:42 wazuh-agent: INFO: Received exit signal. Starting exit process.
```
After that, the agent connects to the manager without problems and there are no disconnections at any time during the test.
```
2023/11/28 10:39:53 wazuh-agent: INFO: Trying to connect to server ([172.31.11.49]:1514/tcp).
2023/11/28 10:39:53 wazuh-agent: INFO: (4102): Connected to the server ([172.31.11.49]:1514/tcp).
```
![image](https://github.com/wazuh/wazuh/assets/117279646/ce564429-a748-44f2-8705-8db74a39cc02)
