### ISSUE TITLE
Add timeouts to Wodle API (requests) calls

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#20603]
## Description

During the [48th Weekly vulnerability scan](https://github.com/wazuh/internal-devel-requests/issues/529), It was found that the Wodles and the integrations code has some requests without timeouts these should be applied to avoid infinite delays and resource exhaustion and other security considerations.  

Tracking issue for:
- [x] https://github.com/wazuh/wazuh/security/code-scanning/3070
- [x] https://github.com/wazuh/wazuh/security/code-scanning/3072
- [x] https://github.com/wazuh/wazuh/security/code-scanning/3074
- [x] https://github.com/wazuh/wazuh/security/code-scanning/2498
- [x] https://github.com/wazuh/wazuh/security/code-scanning/2501

**Comment by GGP1** [comment]
## Update

Added timeouts to multiple requests to avoid indefinite hangouts while awaiting a response.

**Comment by GGP1** [comment]
## Update

Added timeouts to multiple requests to avoid indefinite hangouts while awaiting a response and tested the changes with the Slack integration.

**Comment by GGP1** [comment]
## Update

Added the timeout to the requests affected and updated the unit tests.

**Comment by GGP1** [comment]
## Update

Rebased branch to `4.9.0`.
