### ISSUE TITLE
Cluster: Performance analysis and define cluster specifications

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2061]
Performance analysis and define cluster specifications

**Comment by mgmacias95** [comment]
Hello team,

The following table shows the time required to do API calls, comparing actual cluster implementation and the one that is being developed in [`dev-cluster-performance`](https://github.com/wazuh/wazuh/tree/dev-cluster-performance) branch:

| From   | To     | Call                                                   | Curr implementation (Python 2.7) | Curr implementation (Python 3.6) | New implementation (Python 3.7) |
|:------:|:------:|:------------------------------------------------------:|:--------------------------------:|:--------------------------------:|:-------------------------------:|
| Master | Master | GET /cluster/:node_id/info                             | 0.176                            | 0.24                             | 0.239                           |
| Master | Worker | GET /cluster/:node_id/info                             | 0.881                            | 0.871                            | 0.207                           |
| Master | Master | GET /cluster/:node_id/status                           | 0.176                            | 0.243                            | 0.187                           |
| Master | Worker | GET /cluster/:node_id/status                           | 1.816                            | 0.926                            | 0.201                           |
| Master | Master | GET /cluster/:node_id/configuration                    | 0.172                            | 0.255                            | 0.22                            |
| Master | Worker | GET /cluster/:node_id/configuration                    | 2.746                            | 0.868                            | 0.201                           |
| Master | Master | GET /cluster/:node_id/stats/analysisd                  | 2.879                            | 1.082                            | 0.198                           |
| Master | Worker | GET /cluster/:node_id/stats/analysisd                  | 2.786                            | 1.098                            | 0.206                           |
| Master | Master | GET /cluster/:node_id/logs                             | 0.235                            | 0.322                            | 0.309                           |
| Master | Worker | GET /cluster/:node_id/logs                             | 2.784                            |                                  | 0.312                           |
| Master | Master | GET /rootcheck/:agent_id?offset=0&limit=10             | 0.181                            | 0.251                            | 0.188                           |
| Master | Worker | GET /rootcheck/:agent_id?offset=0&limit=10             | 2.701                            | 1.104                            | 0.203                           |
| Master | Master | GET /rootcheck/:agent_id/last_scan                     | 0.181                            | 0.251                            | 0.188                           |
| Master | Worker | GET /rootcheck/:agent_id/last_scan                     | 0.969                            | 0.897                            | 0.197                           |
| Master | Master | GET /syscheck/:agent_id?offset=0&limit=10              | 0.177                            | 0.27                             | 0.191                           |
| Master | Worker | GET /syscheck/:agent_id?offset=0&limit=10              | 2.719                            | 1.062                            | 0.206                           |
| Master | Master | GET /syscheck/:agent_id/last_scan                      | 0.185                            | 0.254                            | 0.209                           |
| Master | Worker | GET /syscheck/:agent_id/last_scan                      | 0.895                            | 0.942                            | 0.208                           |
| Master | Master | GET /agents/:agent_id/config/:component/:configuration | 0.181                            | 0.259                            | 0.194                           |
| Master | Worker | GET /agents/:agent_id/config/:component/:configuration | 2.691                            | 0.887                            | 0.206                           |
| Master | Master | GET /agents/:agent_id/restart                          | 0.178                            | 0.253                            | 0.181                           |
| Master | Worker | GET /agents/:agent_id/restart                          | 0.887                            | 0.898                            | 0.219                           |
| Master | Master | PUT /syscheck/:agent_id                                | 0.18                             | 0.258                            | 0.185                           |
| Master | Worker | PUT /syscheck/:agent_id                                | 0.918                            | 0.938                            | 0.197                           |
| Master | Master | GET /syscollector/:agent_id/os                         | 0.184                            | 0.298                            | 0.188                           |
| Master | Worker | GET /syscollector/:agent_id/os                         | 1.756                            | 0.91                             | 0.209                           |
| Master | Master | GET /syscollector/:agent_id/packages                   | 0.254                            | 0.322                            | 0.259                           |
| Master | Worker | GET /syscollector/:agent_id/packages                   | 2.831                            | 2.745                            | 0.244                           |
|                                                                                                                                                                                  |
| Worker | Master | GET /cluster/:node_id/info                             |                                  |                                  | 0.244                           |
| Worker | Master | GET /cluster/:node_id/status                           |                                  |                                  | 0.21                            |
| Worker | Master | GET /cluster/:node_id/configuration                    |                                  |                                  | 0.211                           |
| Worker | Master | GET /cluster/:node_id/stats/analysisd                  |                                  |                                  | 0.225                           |
| Worker | Master | GET /cluster/:node_id/logs                             |                                  |                                  | 0.311                           |
| Worker | Master | GET /rootcheck/:agent_id?offset=0&limit=10             |                                  |                                  | 0.203                           |
| Worker | Master | GET /rootcheck/:agent_id/last_scan                     |                                  |                                  | 0.202                           |
| Worker | Master | GET /syscheck/:agent_id?offset=0&limit=10              |                                  |                                  | 0.2                             |
| Worker | Master | GET /syscheck/:agent_id/last_scan                      |                                  |                                  | 0.217                           |
| Worker | Master | GET /agents/:agent_id/config/:component/:configuration |                                  |                                  | 0.211                           |
| Worker | Master | GET /agents/:agent_id/restart                          |                                  |                                  | 0.206                           |
| Worker | Master | PUT /syscheck/:agent_id                                |                                  |                                  | 0.205                           |
| Worker | Master | GET /syscollector/:agent_id/os                         |                                  |                                  | 0.207                           |
| Worker | Master | GET /syscollector/:agent_id/packages                   |                                  |                                  | 0.275                           |

As you can see, local requests (the ones from master to master) have the same execution time in all versions, no cluster is involved in the process of those requests. However, a huge improvement has been achieved in distributed API calls (from worker to master, from master to worker): these requests are quite slow right now but they will feel like a local request with the new implementation. This means the new distributed API has very little overhead over the request, providing a better user experience for users.

Furhter and more detailed performance analysis must be done in the future, when the implementation is finished. But I think this table can show the effort migrating to asyncio and Python 3.7 is worth it.

Best regards,
Marta

**Comment by jesuslinares** [comment]
Awesome!. Thanks for the information.
