### ISSUE TITLE
Add coverage for uploading configuration via API

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#20610]
| Target version | Development issue| Development PR |Test planning|
|--------------------|--------------------|-----------------|------------|
|        4.4.0                |         https://github.com/wazuh/wazuh/issues/16419               |                 https://github.com/wazuh/wazuh/pull/16455|https://github.com/wazuh/wazuh-qa/issues/4046|

## Description

This issue aims to implement new tests for `PUT /manager/configuration` API endpoint.

## Proposed test cases

  <details>
  <summary><b>Case 1:</b> Upload configuration with one <code>ossec_config</code> block</summary>
  <br>

  - **Test name**: Upload one block config
  - **Test type**: Integration
  - **Tier**: 0
  - **Component**: Manager
  - **OS plarforms**: Linux
  - **Modules**: API
  - **Description**:

        **Given** one configuration file with one `ossec_config` block
         **And** permissions configured in `api.yaml`
        **When** uploading the configuration via API
        **Then** configuration is uploaded correctly

  </details>

  <details>
  <summary><b>Case 2:</b> Upload configuration with two <code>ossec_config</code> block (default ossec.conf)</summary>
  <br>

  - **Test name**: Upload two blocks config
  - **Test type**: Integration
  - **Tier**: 0
  - **Component**: Manager
  - **OS plarforms**: Linux
  - **Modules**: API
  - **Description**:

        **Given** one configuration file with two `ossec_config` block
        **And** permissions configured in `api.yaml`
        **When** uploading the configuration via API
        **Then** configuration is uploaded correctly

  </details>

## Status

- [x] Case 1: Upload one block config
- [x] Case 2: Upload two blocks config

**Comment by GGP1** [comment]
## Update

Added the tests validating the configuration uploads and added a new endpoint to the QA framework.

**Comment by GGP1** [comment]
## Update

Applied the changes suggested to the test comments.

**Comment by GGP1** [comment]
## Update

Updated the QA framework change log
