### ISSUE TITLE
Increased Disk Usage for db

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#20620]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.7.1-rc1 |  Manager | Packages | -  |

Testing: https://github.com/wazuh/wazuh/issues/20550

It was possible to evidence a significant increase in the disk  usage for `db` in the Manager

- **4.7.1-rc1:** https://github.com/wazuh/wazuh/issues/20550

![image](https://github.com/wazuh/wazuh/assets/54536265/e0388bea-abbf-4c1b-b2e9-b760d90e821c)

- **4.7.0-rc1:** https://github.com/wazuh/wazuh/issues/20301

![image](https://github.com/wazuh/wazuh/assets/54536265/70c7b609-6d5a-4e21-8f46-4a7ec8383c27)

**Comment by JorgeMarinoDev** [comment]
Stress Test Issues :

1. Disk Usage metrics are not reliable.
2. Disk Read Bytes metrics were not collected here. Showing 0 bytes. Although +17.000 read operations. Odd behavior. Please review monitor.py.
	
Version | Commit | Timestamp | Daemon | CPU(%) | RSS(KB) | VMS(KB) | FD | Read_Ops | Write_Ops | Disk_Read(B) | Disk_Written(B) | Disk(%) | USS(KB) | PSS(KB) | SWAP(KB)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4.7.0 | pre-release | 2023-11-16 20:48:13 | wazuh-db | 0 | 13268 | 798976 | 27 | 177298 | 553585 | 0 | 1301913600 | 1.77481752125152 | 10484 | 11025 | 0
4.7.1 | pre-release | 2023-11-30 22:38:03 | wazuh-db | 0 | 15328 | 798976 | 28 | 173984 | 553571 | 0 | 1301872640 | 1.6888743674127 | 12540 | 13061 | 0

Conclusion: R/W ops and W Bytes are pretty much similar. No increase there.
Disregard.
