### ISSUE TITLE
`wazuh-modulesd` decreases disk written

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#20625]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.7.1-rc1 | wazuh-modulesd | Agent | Packages | Ubuntu 20 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/20563, a considerable disk written decrease has been found compared to lower versions

- [v4.7.1-rc1](https://github.com/wazuh/wazuh/issues/20563)

![image](https://github.com/wazuh/wazuh/assets/89791732/bc480ccd-c107-4e6c-bbee-024546ba6445)

- [4.7.0-rc1](https://github.com/wazuh/wazuh/issues/20290)

![image](https://github.com/wazuh/wazuh/assets/89791732/e4b61571-b3b5-4ecf-9eeb-51b50a08cfe4)

In versions prior to 4.7.1, has been observed a peak around 2.5 e10 and now the values are 56% lower, reaching the peak of 1.4 e10

It is necessary to determine the cause of this behaviour.

**Comment by JorgeMarinoDev** [comment]
After analysis of actual CSV Values of stress tests results.
We can see there's actually a decrease in Disk Written in 4.7.1 for CentOs.

![image](https://github.com/wazuh/wazuh/assets/117848458/a2547a6c-aabc-4d9a-ab4c-723e45504163)

Conclusion: 

* This should be considered positive. Disregard Issue.
* How can we improve Ubuntu versions to get closer to CentOs?
* Same tests parameters and pretty close number of Events.

Please disregard, and focus on improving Ubuntu agent's written bytes under same conditions.
