### ISSUE TITLE
FIM failed to show the user name in the permissions field

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#20629]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | FIM | Agent | Packages | Windows Server 2022 |

@santiago-bassett has found a FIM alert from a Windows agent containing user IDs. However, we expect FIM to convert the user IDs into user names.

|Expected|Found|
|---|---|
|![image](https://github.com/wazuh/wazuh/assets/10536251/c6310648-f6d6-40df-82f5-770a89689689)|![image](https://github.com/wazuh/wazuh/assets/10536251/da7336bc-fa13-4ae0-b32e-ff0837ebeb58)|

**Comment by lchico** [comment]
# Update

I performed the test using VirtualBox on Windows Server 2022, using Wazuh Agent version 4.7.5, and it appears that the issue has already been resolved.

![image](https://github.com/wazuh/wazuh/assets/21695385/6152f8c0-f943-4a9f-97b4-9ad4f12d6691)


![image](https://github.com/wazuh/wazuh/assets/21695385/8e64bfb7-aee2-47c1-8354-75178085cc1f)


![permissions_field](https://github.com/wazuh/wazuh/assets/21695385/de999cb1-3b78-4590-9ce3-4be273c44ee8)

**Comment by lchico** [comment]
[06-13-2024] I started doing some research.

**Comment by vikman90** [comment]
After a thorough review, we have confirmed that the user's name consistently appears in the `name` field. This behavior has been observed in the current implementation.

To ensure compatibility and identify any discrepancies, we will also review this behavior in Wazuh Agent version 5.0.
