### ISSUE TITLE
Decreased VMS Values

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#20621]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.7.1-rc1 |  Agent | Packages | Windows |

Testing: https://github.com/wazuh/wazuh/issues/20550

It was possible to evidence some decreasing peaks in the `VMS` chart for Windows Agent

- **4.7.1-rc1:** https://github.com/wazuh/wazuh/issues/20550

![image](https://github.com/wazuh/wazuh/assets/54536265/8fbf3ed5-8b17-487b-b340-db4fbe6c1da3)

- **4.7.0-rc1:** https://github.com/wazuh/wazuh/issues/20301

![image](https://github.com/wazuh/wazuh/assets/54536265/b3513533-9f28-4ba9-a889-7c3c3a08b957)

**Comment by nbertoldo** [comment]
### Conclusion
The reports have been analysed, focusing on the moments when the decrease in VMS values occurs. No anomalies have been detected, nor changes in the code or in the test configuration that could cause differences between versions. Therefore, it is assumed that this is a circumstantial behaviour that does not negatively affect the agent's performance.
