### ISSUE TITLE
Content Manager - Implementing controlled termination for Content Manager orchestration

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#20633]
|Component|
|---|
| [content_manager](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/content_manager) |

## Description

Currently, the execution of the orchestration process of the content manager cannot be stopped on demand, as it only concludes when all orchestration stages are completed. This limitation makes it difficult to effectively manage interruptions and to manage stage-specific completion conditions.

## Expected

 - Use the [m_schedulerRunning](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/shared_modules/content_manager/src/action.hpp#L105) variable as the primary flag to control the execution of orchestration stages.
 - Convert `m_schedulerRunning` to an atomic variable and store a reference to it in the context of the content manager.
 - Use the reference to `m_schedulerRunning` to determine if a specific stage should be stopped during execution.
 - Implement a mechanism to gracefully handle the interruption of the [CtiOffsetDownloader](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/shared_modules/content_manager/src/components/CtiOffsetDownloader.hpp#L29) stage. Ensure that, in the event of an interruption, subsequent execution continues smoothly and that the content that was intended to be processed at the time of the interruption is processed.

## DoD

- [x] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [x] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

**Comment by tsarquis88** [comment]
# Update

PR already created: #20634

I had yet to fix some bad-referencing problems. The on-demand action test has to be fixed as well.
