### ISSUE TITLE
Cluster: Testing new implemented cluster

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2063]
Test the new implemented cluster (asyncio):

- [x] Manual tests
- [x] Performance tests

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

I have done tests in two environments:
* Local vagrant environment with 4 agents and 2 nodes.
* Deployed environment in AWS with 5 nodes and 1000 agents.

I have found several bugs today and I have fixed them in commits these commits: a9fe6d5d9aedf2ee79467ed5f23b415d8be9d0a8 c5eaf6f8daeab57a0e1d2fe68fe3ff011e9c00c1 985bc53a0ccc20995df502cf3305f548549cea14 fe057970980a0aa9fa5ab1c30679ca2bdadb5511

I need to run all tests again to make sure no new bugs have appeared.

Regarding performance, some metrics measured from a worker node:
* 0.329s -> `cluster_control -a` having 1000 agents
* 0.201s ->`cluster_control -l` having 5 nodes
* 0.214s -> `cluster_control -i`.
* 0.524s -> `curl -u foo:bar "localhost:55000/syscheck/100?pretty"`
* 6.440s -> `curl -u foo:bar "localhost:55000/experimental/syscollector/os?pretty"`
* 0.583s -> `curl -u foo:bar "localhost:55000/syscollector/100/os?pretty"`

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

After testing cluster's functionality, I have been helping @BraulioV to test Python in all supported OS for the Wazuh manager. The tests we did are detailed in https://github.com/wazuh/wazuh/issues/2400#issuecomment-459822367.

Best regards,
Marta
