### ISSUE TITLE
Upload the new OpenSSL 3.0.x library to production.

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#20661]
## Description

As part of https://github.com/wazuh/wazuh/issues/17295, we need to update our OpenSSL dependency from 1.1.1 to 3.0.x since it has reached its EOL.

This issue aims to upload the new library into production. Besides, all precompiled packages related to this library need to be generated and uploaded to production.

**Comment by sdvendramini** [comment]
## Precompiled dependencies:
- Centos5 i386 :green_circle: 
- Centos5 amd64 :green_circle:

**Comment by jr0me** [comment]
Precompiled dependencies:
- Linux i386 :green_circle: 
- Linux amd64 :green_circle:

**Comment by sdvendramini** [comment]
## Precompiled dependencies:
- macOS amd64 :green_circle:

**Comment by jr0me** [comment]
## Update

Agent compilation successful on PPC64LE Debian 9 (stretch)

**Comment by jr0me** [comment]
## Precompiled dependencies:
- ppc64le :green_circle:

**Comment by sdvendramini** [comment]
## Precompiled dependencies:
- Solaris 10 i386 :green_circle: 
- Solaris 10 sparc :green_circle:

**Comment by jr0me** [comment]
## Precompiled dependencies:
- AIX ppc :green_circle:

**Comment by sdvendramini** [comment]
## Precompiled dependencies:
- HP-UX ia64  :green_circle:

**Comment by TomasTurina** [comment]
### Precompiled dependencies:

- Linux aarch64 :green_circle:
- Linux arm32 :green_circle: 

### Other tests:

- macOS ARM :green_circle:
- alpine :green_circle:
- wpk 🟡 (https://github.com/wazuh/wazuh-packages/issues/2779)
- solaris 11
