### ISSUE TITLE
Release 4.8.0 - Alpha 1 - E2E UX tests 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#20670]
## Description
The following issue will track all the E2E UX tests for this release stage.

The definition of done for this task is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes, all the issues from below must be closed.

## QA issues

| Name                        | Issue                                         | Status      |DRI|Reviewer|
|-----------------------------|------------------------------------------|--------------|------|------------|
| Deployment on Docker | | :black_circle: Not finished| @wazuh/qa | @wazuh/cicd |
| Deployment with Puppet | | :black_circle: Not finished| @wazuh/framework | @wazuh/cicd |
| Deployment with Ansible |  | :black_circle: Not finished | @wazuh/frontend | @wazuh/cicd |
| Deployment on Kubernetes |  |:black_circle: Not finished | @wazuh/core | @wazuh/cicd |
| Wazuh Dashboard | | :black_circle: Not finished| @wazuh/qa | @wazuh/frontend |
| Wazuh Indexer |  | :black_circle: Not finished| @wazuh/core | @wazuh/indexer |
| Demo environment | | :black_circle: Not finished | @wazuh/qa | @wazuh/cicd |
| Windows events || :black_circle: Not finished| @wazuh/qa | @wazuh/binary-beasts |
| macOs |  | :black_circle: Not finished | @wazuh/frontend | @wazuh/early-birds |
| Vulnerability Detection | | :white_circle: Skipped | - | @wazuh/data-pirates |
| Active response | - | :white_circle: Skipped | - | @wazuh/early-birds |
| Security Configuration Assessment | - | :white_circle: Skipped | - | @wazuh/security-warriors |
| File Integrity Monitoring | | :black_circle: Not finished| @wazuh/cloud | @wazuh/watchdogs |
| Monitoring Docker | - | :white_circle: Skipped | - | @wazuh/framework |
| Configuring email alerts | - | :white_circle: Skipped | - | @wazuh/watchdogs |
| MITRE | - | :white_circle: Skipped | - | @wazuh/threat-intel |
| Wazuh Indexer ISM policies | - |:black_circle: Not finished | @wazuh/content  | @wazuh/indexer |
| Centralized configuration - Agent groups | - |:black_circle: Not finished | @wazuh/content | @wazuh/binary-beasts |
| SAML SSO | - | :white_circle: Skipped | - | @wazuh/frontend |
| Change custom logos | - | :white_circle: Skipped | - | @wazuh/frontend |
| RBAC | - | :white_circle: Skipped | - | @wazuh/framework |
| GCP integration | - | :white_circle: Skipped | - | @wazuh/framework |
| Amazon Cloudtrail integration | | :black_circle: Not finished| @wazuh/core | @wazuh/framework |
| Amazon Cloudwatch Logs integration | - | :white_circle: Skipped | - | @wazuh/framework |
| Office365 integration | - | :white_circle: Skipped | - | @wazuh/drop-table |
| Github integration | - | :white_circle: Skipped | - | @wazuh/drop-table |
| Azure integration |  | :black_circle: Not finished| @wazuh/documentation | @wazuh/framework |
| Amazon security lake | - | :white_circle: Skipped | - | @wazuh/framework |
| Microsoft Graph security API | - | :white_circle: Skipped | - | @wazuh/drop-table |
| Integration with external APIs: Virustotal | |:black_circle: Not finished| @wazuh/qa | @wazuh/drop-table |
| Integration with external APIs: Slack and Pagerduty | | :black_circle: Not finished| @wazuh/documentation | @wazuh/drop-table |
| Integration with external APIs: Shuffle and Maltiverse | | :black_circle: Not finished| @wazuh/qa | @wazuh/framework |
| Elastic integration | - | :black_circle: Not finished | @wazuh/content | @wazuh/frontend |
| Splunk integration | - | :black_circle: Not finished | @wazuh/content | @wazuh/frontend |
| Opensearch integration | - |:black_circle: Not finished | @wazuh/content | @wazuh/frontend |

:white_circle: Skipped: The task has been deemed not necessary for this stage.
:black_circle: Not finished: The tasks haven't been finished yet.
:purple_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.

## Fixes
All the fixes for those issues detected in for this version can be found in the [v4.7.0 project](https://github.com/orgs/wazuh/projects/51/views/1).

**Comment by davidjiglesias** [comment]
Skipped for Alpha 1
