### ISSUE TITLE
Release 4.8.0 - Alpha 1 - Integration tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20686]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/20667|
| **Version**                      | 4.8.0                                                   |
| **Release stage**            | Alpha 1                                                      |
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.8.0-alpha1          |
| **Wazuh QA: Branch**    | `v4.8.0-alpha1`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.0-alpha1      |
| **Wazuh: Branch**    | `v4.8.0-alpha1` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

### Build

***Build evidence:*** https://ci.wazuh.info/job/Test_integration_launcher/238/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45287/manager_html_report_Test_integration_B45287.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45288/agent_centos_html_report_Test_integration_B45288.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45288/agent_windows_html_report_Test_integration_B45288.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45289/agent_centos_html_report_Test_integration_B45289.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45289/agent_windows_html_report_Test_integration_B45289.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>analysisd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45290/manager_html_report_Test_integration_B45290.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>api</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45291/manager_html_report_Test_integration_B45291.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45292/manager_html_report_Test_integration_B45292.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45293/agent_centos_html_report_Test_integration_B45293.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45293/agent_windows_html_report_Test_integration_B45293.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45294/manager_html_report_Test_integration_B45294.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45295/agent_centos_html_report_Test_integration_B45295.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45295/agent_windows_html_report_Test_integration_B45295.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45296/agent_macos_html_report_Test_integration_B45296.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45296/agent_solaris_html_report_Test_integration_B45296.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45297/manager_html_report_Test_integration_B45297.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45298/manager_html_report_Test_integration_B45298.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45299/agent_centos_html_report_Test_integration_B45299.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45300/manager_html_report_Test_integration_B45300.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45301/agent_centos_html_report_Test_integration_B45301.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45301/agent_windows_html_report_Test_integration_B45301.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45301/agent_macos_html_report_Test_integration_B45301.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45301/agent_solaris_html_report_Test_integration_B45301.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45302/manager_html_report_Test_integration_B45302.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45303/manager_html_report_Test_integration_B45303.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45304/agent_centos_html_report_Test_integration_B45304.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45305/manager_html_report_Test_integration_B45305.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45306/manager_html_report_Test_integration_B45306.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rootcheck</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45307/manager_html_report_Test_integration_B45307.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>vulnerability_detector</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45308/manager_html_report_Test_integration_B45308.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45309/manager_html_report_Test_integration_B45309.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45310/manager_html_report_Test_integration_B45310.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45311/agent_centos_html_report_Test_integration_B45311.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45311/agent_windows_html_report_Test_integration_B45311.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45311/agent_macos_html_report_Test_integration_B45311.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

### New Issues
- https://github.com/wazuh/wazuh-qa/issues/4758
- https://github.com/wazuh/wazuh-qa/issues/4759

### Known Issues

- https://github.com/wazuh/wazuh-qa/issues/4230
- https://github.com/wazuh/wazuh-qa/issues/4429

**Comment by Deblintrake09** [comment]
## Update

- Vulnerability Detector IT failure related to https://github.com/wazuh/wazuh-qa/issues/4429
- Syscollector fails related to https://github.com/wazuh/wazuh-qa/issues/4230
- Reported https://github.com/wazuh/wazuh-qa/issues/4758
- Reported https://github.com/wazuh/wazuh-qa/issues/4759

**Comment by Rebits** [comment]
Vulnerability Detector failure is also related with https://github.com/wazuh/wazuh/issues/20573. Changes not included in Alpha 1 stage

**Comment by Rebits** [comment]
LGTM

**Comment by damarisg** [comment]
LGTM!
