### ISSUE TITLE
 Support new stage RC 2 for 4.7.1 in wazuh repository #20635 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#20688]
## Description

This issue attempts to support a new stage RC 2 for 4.7.1 in the wazuh repository.

## Tasks

- [x] Ensure changelog is updated for 4.7.1(if applicable).
- [x] Bump revision for branch 4.7.1 on wazuh repository.
- [x] Create tag v4.7.1-rc2 from branch 4.7.1 on wazuh repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh/releases/tag/v4.7.1-rc2.

**Comment by jnasselle** [comment]
LGTM
