### ISSUE TITLE
Add internal documentation related to pre-commit

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20759]
## Description

This issue aims to create some internal documentation explaining:
* How to get up and running the pre-commit hook
* How to integrate the ruff, linter, and formatter, with the code editors. This is optional but It can be helpful to the new comers.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Added an internal documentation file with information on how to configure and install the CI tools.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
