### ISSUE TITLE
 Framework code sanitization

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#20755]
> [!NOTE]
> To be done after #20758 

# Description

This issue aims to sanitize the code of the framework module to pass correctly the pre-commit hooks validations.

### Steps

* Apply the Ruff configuration defined in #20753 into the `.ruff.toml` file into the root of wazuh.
* Run the command `ruff check --config .ruff.toml --fix framework` to solve the problems that can be fixed automatically.
* Fix manually the errors that can not be fixed automatically.
* Run the command `ruff format --config .ruff.toml framework/` to format the codebase.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Blocked until bigger framework developments are upward merged.
