### ISSUE TITLE
Auto causes copy defect at shared modules

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#20772]
|Version|Component|
|---|---|
|≤ 4.8.0|Syscollector & data provider|

The following optimization defects have been detected by Coverity:

https://github.com/wazuh/wazuh/blob/bb0dd20252ee2f0c902d8e3a4bce3efcdfd8c17a/src/data_provider/src/osinfo/sysOsParsers.cpp#L29

https://github.com/wazuh/wazuh/blob/bb0dd20252ee2f0c902d8e3a4bce3efcdfd8c17a/src/data_provider/src/sysInfoLinux.cpp#L524

https://github.com/wazuh/wazuh/blob/bb0dd20252ee2f0c902d8e3a4bce3efcdfd8c17a/src/wazuh_modules/syscollector/src/syscollectorImp.cpp#L1312

https://github.com/wazuh/wazuh/blob/bb0dd20252ee2f0c902d8e3a4bce3efcdfd8c17a/src/wazuh_modules/syscollector/src/syscollectorImp.cpp#L1336

**Comment by sebasfalcone** [comment]
Including these defects on this issue:
- 1584340 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584339 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584338 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584337 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584336 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584335 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584333 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584331 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584330 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584329 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector
- 1584327 -> COPY_INSTEAD_OF_MOVE -> Vulnerability Detector

**Comment by sebasfalcone** [comment]
Unit tests are failing, investigation will take place in:
- https://github.com/wazuh/wazuh/issues/22571
