### ISSUE TITLE
Vulnerability Detector Refactor: NVD and canonical candidates queues do not exists

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20789]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - `dev-14153-vulndet-refactor ` | Modules: Vulnerability Scanner | Manager | Packages | Ubuntu 22 |

| Related Issue| 
| --- |
| https://github.com/wazuh/wazuh/issues/20785 |

### Description

During testing iteration specified in https://github.com/wazuh/wazuh/issues/20785, it was not possible to generate vulnerability alert. Regarding this module the following errors appears in the manager logs:
```
2023/12/13 11:16:45 wazuh-modulesd:vulnerability-scanner: ERROR: ScanOrchestrator::run::Exception: Database queue/vd/candidates/canonical does not exist
2023/12/13 11:16:45 wazuh-modulesd:vulnerability-scanner: ERROR: ScanOrchestrator::run::Exception: Database queue/vd/candidates/nvd does not exist
```

### Evidences and Environment

The evidences and the environment used for this testing can be found in https://github.com/wazuh/wazuh/issues/20785

**Comment by pereyra-m** [comment]
## RCA

This error happens because of two different causes:
- The scanner isn't handling the exception when CNA database doesn't exist (will be fixed in a PR to this issue)
- There isn't an internal mechanism to pause the scanner until the databases are completely downloaded (will be fixed in another issue)

**Comment by Rebits** [comment]
It has recently also detected the following error message:
`2023/12/14 11:52:41 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing message: Invalid message`

Probable related with this issue
