### ISSUE TITLE
Benchmark vulnerability detector performance before the refactor

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#20780]
## Description

As a part of https://github.com/wazuh/wazuh/issues/20776, we need to benchmark the performance and scalability of the vulnerability detection module before the refactor that is being carried out in https://github.com/wazuh/wazuh/issues/14153. The version used should be `4.7.x`.

The tests should include:

- A deployment with indexer nodes.
- Environment and processes footprints during the tests including CPU, RAM and file descriptors.
- Workload benchmark metrics executions with 10 workers and 10,000 agents, and 25 workers and 50,000 agents.

**Comment by Rebits** [comment]
Following our recent meeting, it has been decided not to proceed with the comparison between versions. The inherent differences between them would pose challenges and make an accurate comparison difficult.
Closing this issue as not planned
