### ISSUE TITLE
Vulnerability Detector Refactor: Several errors in analysisd

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20791]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - `dev-14153-vulndet-refactor ` | Analysisd | Manager | Packages | Ubuntu 22 |

| Related Issue| 
| --- |
| https://github.com/wazuh/wazuh/issues/20785 |

### Description

During testing iteration specified in https://github.com/wazuh/wazuh/issues/20785, appears the following errors related to analysisd and rootcheck in the master node:

```
2023/12/13 10:33:14 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
2023/12/13 10:33:14 wazuh-analysisd: ERROR: FIM decoder: Cannot communicate with database.

2023/12/13 10:33:14 wazuh-analysisd: ERROR: Bad load query: 'agent 000 rootcheck save 1702463588 Starting rootcheck scan.'.
2023/12/13 10:33:14 wazuh-analysisd: ERROR: Rootcheck decoder unexpected result: ''
2023/12/13 10:33:14 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2023/12/13 10:33:14 wazuh-analysisd: ERROR: Unable to connect to socket 'queue/db/wdb'.
2023/12/13 10:33:14 wazuh-analysisd: ERROR: Bad load query: 'agent 000 rootcheck save 1702463588 Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).'.
```

### Evidences and Environment

The evidences and the environment used for this testing can be found in https://github.com/wazuh/wazuh/issues/20785

**Comment by Dwordcito** [comment]
This will be fixed in this issue: https://github.com/wazuh/wazuh/issues/20424

Duplicated.
