### ISSUE TITLE
Feature Request: Make Windows Wazuh agent send events as JSON to Wazuh manager for auto-decoding of Windows fields

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#208]
**Problem:** 

The human-readable Windows event log messages are a mess to decode into relevant fields.  Because of this, the Wazuh decoders only pick up certain Windows fields, leaving rich analysis of Windows events out of reach at this time.

**Proposed solution:** 

As we discussed offline today, since Windows Vista and newer do actually store a rich breakdown of event fields, it would seem within reach of the Windows Wazuh agent to acquire events from the Windows Event Log API rendered as XML which would be pretty easy to automatically convert to JSON before feeding it up to the Wazuh manager.  Then the Wazuh manager, which starting in Wazuh 3.0 is capable of auto-decoding incoming JSON fields, should be able to hand these richly decoded events over to ElasticStack with little to no traditional Wazuh decoder involvement.  We would still need to hold on to the human readable log message as [full_log] since the broken out fields do not always stand alone in conveying a clear picture of what an event is about.

I think a feature like this would profoundly increase the amount of insight we could get out of Windows events, making smarter Windows HIDS rules possible, as well as opening up much more powerful analytics on Windows events via ElasticStack.

Thanks,
Kevin

**Comment by branchnetconsulting** [comment]
Please let me encourage getting this onto the roadmap.  Winlogbeat is leaving us in the dust here with the way it sends Windows log events in structured format to Elasticsearch such that the full set of Windows log fields are dynamically separated out for viewing/analysis in Kibana.  Wazuh could provide the double benefit of the same quality of dynamic parsing plus Wazuh HIDS analysis of the log events.  That would be compellingly valuable in my opinion.

**Comment by V1D1AN** [comment]
Yes , this is a excellent idea :)

**Comment by branchnetconsulting** [comment]
Thanks for your fine work on this!  I am very happy we now receive JSON records from Windows Wazuh agents using the eventchannel log format.  I'm sure that was not trivial to pull off.
