### ISSUE TITLE
Changes in the pattern and height of modulesd during stress testing

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20858]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component | Manager | Packages | CentOS  |

Testing:

Footprint Metrics - [ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20814)

It was possible to see a different pattern of modules in PSS, RSS, USS

4.8.0-alpha1 https://github.com/wazuh/wazuh/issues/20814
![image](https://github.com/wazuh/wazuh/assets/125690423/bab5a91f-0b8b-4a75-949c-00fb1c18e75f)
![image](https://github.com/wazuh/wazuh/assets/125690423/a99452d0-2b0e-4e82-beac-9a83692828d0)
![image](https://github.com/wazuh/wazuh/assets/125690423/aa53c46e-a3b0-4f6b-b7e4-93115a4fc56c)

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20308
![image](https://github.com/wazuh/wazuh/assets/125690423/bd6bc63b-c06b-42ca-b135-6183b97aa191)
![image](https://github.com/wazuh/wazuh/assets/125690423/20fb8e43-41cf-4eb0-9d0f-13c7be2dbe17)
![image](https://github.com/wazuh/wazuh/assets/125690423/0943995d-b603-4d6c-ad6f-e26753135b0f)

Further research should be done

**Comment by LucioDonda** [comment]
Analyzing the different plots, there's a significant change in shape and size. Almost all the _**modulesd**_ plots (from 4.7.0 and before) tend to show more and higher peaks. The base line is in all the cases at a similar height.
But in my opinion, showing lower peaks isn't something to worry about; if the results are the same and there are no additional errors on the test, it would mean that less memory is used in the same process.
Besides that, a better analysis can be done using the max-min plots:

**4.8.0:**
![MaxMin480](https://github.com/wazuh/wazuh/assets/95248059/ce3bfff0-ffaf-4f5a-8dd4-80afca10974d)


**4.7.1:**
![MaxMin471](https://github.com/wazuh/wazuh/assets/95248059/b175947a-e15c-42f3-a566-f15107285276)

Peaks are reduced by 20% on average.

A cause can be searched for (maybe some process simplification in the new version), but in my opinion, this shouldn't be treated as a possible issue.
