### ISSUE TITLE
Rule 62123 is not triggered properly due to space in the field name

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh#20856]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7 | Wazuh manager | Manager | N/A | N/A  |

## Summary
The rule [62123](
https://github.com/wazuh/wazuh/blob/4b5682d4a2fed8c02f330a5ade5a68485e55b804/ruleset/rules/0600-win-wdefender_rules.xml#L239) (below) uses fields `win.eventdata.severityName` and `win.eventdata.processName`.

```xml
  <!-- Event ID 1116 -->
  <rule id="62123" level="12">
      <if_sid>62101</if_sid>
      <field name="win.system.eventID">^1116$</field>
      <description>Windows Defender: Antimalware platform detected $(win.eventdata.severityName) potentially unwanted software ($(win.eventdata.processName))</description>
      <options>no_full_log</options>
      <group>pci_dss_5.1,pci_dss_5.2,pci_dss_10.6.1,pci_dss_11.4,gpg13_4.2,gdpr_IV_35.7.d,hipaa_164.312.b,nist_800_53_SI.3,nist_800_53_AU.6,nist_800_53_SI.4,tsc_A1.2,tsc_CC7.2,tsc_CC7.3,tsc_CC6.1,tsc_CC6.8,</group>
  </rule>
```

But the fields are parsed with spaces between words in field names, missing the field values defined in the rule:
![image](https://github.com/wazuh/wazuh/assets/39981909/21366b8d-9b7d-4089-856b-c0f7e5026837)

## Expected behavior

For the event in the screenshot the expected value should be:
```yml
Windows Defender: Antimalware platform detected High potentially unwanted software (C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell_ise.exe)
```

## Actual behavior

```yml
Windows Defender: Antimalware platform detected  potentially unwanted software ()
```

Or

![image](https://github.com/wazuh/wazuh/assets/39981909/a0eb692b-fb55-44c9-9886-4298c9cd09b6)

## Steps to reproduce

```powershell
Invoke-WebRequest -Uri "https://github.com/magicsword-io/LOLDrivers/raw/main/drivers/73c98438ac64a68e88b7b0afd11ba140.bin" -OutFile "C:\windows\temp\capcom.sys"
Start-Process "sc.exe" -ArgumentList "create capcom.sys binPath=C:\windows\temp\capcom.sys type=kernel" -NoNewWindow -Wait
Start-Process "sc.exe" -ArgumentList "start capcom.sys" -NoNewWindow -Wait
```

**Comment by PiRomant** [comment]
There are absolutely no rules with spaces in the fields. Most likely, the decoder is broken.

**Comment by zbalkan** [comment]
There's no decoder for Windows event channel. The logs are parsed by the `logcollector`: https://github.com/wazuh/wazuh/blob/master/src/logcollector/read_win_event_channel.c

The issue is a regression.

**Comment by zbalkan** [comment]
Hi team,

Would it be possible to check the normalization?

Since the module is now moved to [wazuh-agent repo](https://github.com/wazuh/wazuh-agent/blob/56a3571dc27119147a1d227d78cbba1367d6384a/src/modules/logcollector/src/read_win_event_channel.c), should I move it there as well?

**Comment by zbalkan** [comment]
Closing as I moved the issue to wazuh-agent repository.
https://github.com/wazuh/wazuh-agent/issues/174
