### ISSUE TITLE
Add `limit_eps` API configuration field coverage

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#20854]
| Target version | Development issue| Development PR |Test planning|
|--------------------|--------------------|-----------------|------------|
|        4.9.0                |         https://github.com/wazuh/wazuh/issues/16419               |                 https://github.com/wazuh/wazuh/pull/16455|https://github.com/wazuh/wazuh-qa/issues/4046|

## Description

This issue aims to implement new integration tests for the `limit_eps` API configuration field.

## Proposed test cases

<details>
  <summary><b>Case 1:</b> Upload configuration with <code>limit_eps</code> in one <code>ossec_config</code> block - Not allowed</summary>
  <br>

  **Given** one configuration file with one `ossec_config` block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change

  </details>

  <details>
  <summary><b>Case 2:</b> Upload configuration with <code>limit_eps</code> in one <code>ossec_config</code> block - Allowed</summary>
  <br>

  **Given** one configuration file with one `ossec_config` block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>

  <details>
  <summary><b>Case 3:</b> Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the first block - Not allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the first block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change

  </details>

  <details>
  <summary><b>Case 4:</b> Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the first block - Allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the first block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>

  <details>
  <summary><b>Case 5:</b> Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the second block - Not allowed</summary>
  <br>

  **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the second block
  **And** `limit_eps` is not allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration didn't change

  </details>

  <details>
  <summary><b>Case 6:</b> Upload configuration with two <code>ossec_config</code> block and <code>limit_eps</code> in the second block - Allowed</summary>
  <br>

    **Given** one configuration file with two `ossec_config` block
  **And** `limit_eps` configuration is in the second block
  **And** `limit_eps` is allowed to change
  **When** uploading the configuration via API
  **Then** configuration is uploaded correctly
  **And** `limit_eps` configuration changed

  </details>
 

## Status

- [x] Case 1: One config block, `limit_eps` not allowed
- [x] Case 2: One config block, `limit_eps` allowed
- [x] Case 3: Two config blocks, `limit_eps` not allowed in the first block
- [x] Case 4: Two config blocks, `limit_eps` allowed in the first block
- [x] Case 5: Two config blocks, `limit_eps` not allowed in the second block
- [x] Case 6: Two config blocks, `limit_eps` allowed in the second block

**Comment by RamosFe** [comment]
# Update

I continue with the development of the IT using the data described in https://github.com/wazuh/wazuh/issues/16419 and https://github.com/wazuh/wazuh/pull/16541.

**Comment by RamosFe** [comment]
## Update

I continue with the migration to `qa-integration-framework`. I continue to debug a problem caused by invalid xml after the first test pass.

**Comment by RamosFe** [comment]
## Update
The 6 cases ran without any errors after the migration:

```
(venv) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh/tests/integration$ sudo -E python3 -m pytest test_api/test_config/test_limit_eps/test_limit_eps.py -xs
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-0.13.1
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, html-3.1.1, asyncio-0.15.1, cov-2.12.0
collected 6 items                                                                                                                                                                                                                       

test_api/test_config/test_limit_eps/test_limit_eps.py ......

========================================================================================================== 6 passed in 43.28s ===========================================================================================================
``

**Comment by RamosFe** [comment]
Migrated to the `wazuh` repository.
