### ISSUE TITLE
Big increase of disk use of modulesd in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#20859]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component | Manager/Agent | Packages | CentOS/Ubuntu/CentOS  |

Testing:

Footprint Metrics - [ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/20814)

It was possible to see a different big increase of disk use of modulesd (from 80 to 140) in the Manager

4.8.0-alpha1 https://github.com/wazuh/wazuh/issues/20814

![image](https://github.com/wazuh/wazuh/assets/125690423/67594b3f-4461-446d-bf02-647c3411a100)

4.7.0-rc1 https://github.com/wazuh/wazuh/issues/20308

![image](https://github.com/wazuh/wazuh/assets/125690423/85c7d553-2bcb-450f-8a5b-8078470f3e2b)

Further research should be done

**Comment by pro-akim** [comment]
## Update
In https://github.com/wazuh/wazuh/issues/20812, same amount of increase but in ubuntu's Agent

**Comment by JorgeMarinoDev** [comment]
Analysis of CSV. Please disregard Disk Usage % . It's not accurate. [Jenkins 5656](https://github.com/wazuh/wazuh-jenkins/issues/5656). [Related comment](https://github.com/wazuh/wazuh/issues/20620#issuecomment-1841591654)

![image](https://github.com/wazuh/wazuh/assets/117848458/210a9e32-e6e8-4186-a93e-6714e72b43a5)

![image](https://github.com/wazuh/wazuh/assets/117848458/1cd134fd-221a-4558-ba84-6af685d81e75)

![image](https://github.com/wazuh/wazuh/assets/117848458/90a1fd0a-9766-44d1-b4a3-3234200e4ef9)

No alarming increase detected. Disregard.
