### ISSUE TITLE
WPK Upgrade Fail in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by JorgeMarinoDev** [wazuh/wazuh#20852]
Found issue in WPK upgrade test information #20717

|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         | #20701 |
| **Version**                              | 4.7.1 |
| **Release candidate #**                  | RC 2 |
| **Tag**                                  | v4.7.1-rc2 |
| **Previous WPK upgrade tests issue** | #19527 |

|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Operating System**         | openSUSE (20230917) Tumbleweed  |
| **Upgrade from**         | v4.5.4 & v4.7.1-rc2 |
| **Upgrade WPK type**         | Forcing Failed Upgrade |
| **Manager**         | v4.7.1-rc2 Ubuntu 20.04.5 LTS |

## Description
1. The agent being upgraded reports in upgrade.log the following problem:
`./var/upgrade/src/init/pkg_installer.sh: line 324: ./bin/ossec-control: No such file or directory`
2. The upgrade tool in the manager stalls after default 15min timeout and is not responsive.
3. The /var/ossec/bin directory in agent is empty.

[454_471_fail.zip](https://github.com/wazuh/wazuh/files/13674012/454_471_fail.zip)

**Comment by cborla** [comment]
Upgrade log final section

```
2023/12/13 23:40:49 - Installation result = 0
2023/12/13 23:40:49 - Waiting connection... Remaining attempts: 30.
2023/12/13 23:40:50 - Status = connected. 
2023/12/13 23:40:50 - Upgrade failed. Restoring...
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.7.1 Stopped
2023/12/13 23:40:51 - Deleting upgrade files...
2023/12/13 23:40:51 - Restoring backup....
./var/upgrade/src/init/pkg_installer.sh: line 324: ./bin/ossec-control: No such file or directory
```

**Comment by vikman90** [comment]
@JorgeMarinoDev @cborla thank you for this report.

I'm pretty sure that this is due to the recent addition of a call to rsync:

https://github.com/wazuh/wazuh/blob/v4.7.1-rc2/src/init/pkg_installer.sh#L153

**Comment by TomasTurina** [comment]
## Update

Solution proposed: use `tar` instead of `rsync`.

First tests in Linux and macOS: everything seems to be working as expected.

Next: generate Linux and macOS WPKs to continue testing.

PR: https://github.com/wazuh/wazuh/pull/20867
