### ISSUE TITLE
Increased CPU usage by `wazuh-syscheckd` in Manager

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#20860]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1| syscheck| Manager | Packages/Sources | Centos |

# Description

 During Footprint tests https://github.com/wazuh/wazuh/issues/20819, an increase in CPU usage by `wazuh-syscheckd` has been found on the manager, in comparison with [4.7.0-rc1](https://github.com/wazuh/wazuh/issues/20288)
 
_Note: No anomalies were found in the logs._
 
I have attached plots with versions.
 
![imagen](https://github.com/wazuh/wazuh/assets/3978434/520dabac-481f-4976-a131-f5e891c55d8c)

**Comment by cborla** [comment]
## Analysis
Making a graphical comparison of the 2 versions, 4.7.0 and 4.8.0, we can clearly see the increase in CPU usage by the syscheck module in version 4.8.0.

### Data CPU compare

|Version|CPU %/sample|
|---|---|
|4.7.0| 10.59 % |
|4.8.0| 11.17 % |

The difference in CPU use is 0.58 %, so the difference between versions is arround 5%. 
It is true that there is an increase in 4.8.0 but it is not considered worrisome, and the difference in the graph may depend on the time at which the sample is taken. This is not a cause for concern.
