### ISSUE TITLE
Decrease in CPU usage by `wazuh-syscheckd` and `wazuh-modulesd`

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#20868]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | wazuh-syscheckd , wazuh-modulesd | Manager/Agent | Packages/Sources | OS version |

During [this stress test](https://github.com/wazuh/wazuh/issues/20800#top), we noticed a notable decrease in CPU usage by `wazuh-syscheckd` and `wazuh-modulesd` compared with https://github.com/wazuh/wazuh/issues/20293

| 4.7.0 | 4.8.0-alpha1
|--|--
| <img src="https://camo.githubusercontent.com/37bb248e421ba6bf3e6afb5a0b34b60fc6b89e76e060a406902d78d0d64c2295/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343539312d333630306d2f42343539315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343539315f6d616e616765722d7072652d72656c656173655f4350552e706e67"/> | <img src="https://camo.githubusercontent.com/6d600c2f3a01f7b8bd6fae6292b4c1a0e30441ee99fde7d154eb3db7918bdeb8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343638312d333630306d2f42343638315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343638315f6d616e616765722d7072652d72656c656173655f4350552e706e67" />

Possibly related:
- Disk read decreased by wazuh-modulesd
- Read operations decreased considerably by wazuh-modulesd
- Write operations decreased by wazuh-modulesd also

**Comment by mauromalara** [comment]
Hello @wazuh/core team,

I was looking at the issue that 4.8.0-alpha1 **[was compared against](https://github.com/wazuh/wazuh/issues/20293)** (from 4.7.0). This last issue was compared with **[4.6.0](https://github.com/wazuh/wazuh-jenkins/issues/5870)** and I observed that the CPU and other values had also increased compared to that version without having been reported/analyzed (I don't know if it was expected or not).

So, the values of 4.8.0-alpha1 seem to be back to normal compared to 4.6.0 and **[4.5.3](https://github.com/wazuh/wazuh/issues/19501)**.

Therefore, we can dismiss this issue and close it as "not planned" after your observations.

Thank you.

**Comment by nmkoremblum** [comment]
I agree with @mauromalara, It seems that the increase just happened in `4.7.0`, no other strange behaviors are observed.
