### ISSUE TITLE
Increase in Values for `Decoded_Events`, `Written_Stats` and `Number_Events` Graphs

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#20875]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.8.0-alpha1 |  Manager | Packages | -  |

I have detected a very high increase in the values of the `Decoded_Events`, `Written_Stats` and `Number_Events` graphs. I think they could be related. Although the comparison is with 4.7.0-rc1, I have also compared the graphics with 4.7.1-rc1.

> Testing: https://github.com/wazuh/wazuh/issues/20802

<details>
   <summary>Decoded_Events</summary>
   <br/>

Increase in `Decoded from Vulnerability`

- https://github.com/wazuh/wazuh/issues/20802

![image](https://github.com/wazuh/wazuh/assets/54536265/394cd9c9-8b17-4c44-b63d-d5dbb52ba6f3)

- https://github.com/wazuh/wazuh/issues/20299

![image](https://github.com/wazuh/wazuh/assets/54536265/c0aa3e12-b2ff-41b0-8e96-f158a24204cd)

</details>

<details>
   <summary>Written_Stats</summary>
   <br/>

Increase in `Written Alerts`

- https://github.com/wazuh/wazuh/issues/20802

![image](https://github.com/wazuh/wazuh/assets/54536265/e6349277-5924-4447-9d8f-8cdbce9ceab9)

- https://github.com/wazuh/wazuh/issues/20299

![image](https://github.com/wazuh/wazuh/assets/54536265/e04ed027-10bd-4b2c-9ba3-bf0b940de85e)

</details>

<details>
   <summary>Number_Events</summary>
   <br/>

Increase in `Events Received`, `Events Processed` and `Alerts Written`

- https://github.com/wazuh/wazuh/issues/20802

![image](https://github.com/wazuh/wazuh/assets/54536265/e221f39e-8a55-4168-a822-5d679cbb2a79)

- https://github.com/wazuh/wazuh/issues/20299

![image](https://github.com/wazuh/wazuh/assets/54536265/d50e90e1-341e-42ce-80c2-92dfa87f2008)

</details>

**Comment by nmkoremblum** [comment]
The whole `vulnerability detector` module [is being refactored](https://github.com/wazuh/wazuh/issues/14153) and will be merged into `4.8.x` in a future release stage, we agree that there must be some error in the code related to some of the following issues:
- https://github.com/wazuh/wazuh/issues/13354
- https://github.com/wazuh/wazuh/issues/20774
- https://github.com/wazuh/wazuh/issues/20499
But, as the code will change a lot, and after consulting @davidjiglesias, we will disesteem this issue.

**Comment by cborla** [comment]
Related to https://github.com/wazuh/wazuh/issues/20774#issuecomment-1854338885
