### ISSUE TITLE
Increase in Disk Written and Write operations in Manager on stress tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20874]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.1-alpha1 | Wazuh component | Manager  | Packages| Centos Manager |

## Description

An increase of Disk_Written and Write_ops can be detected in Manager, 

- 4.8.0 Manager  - https://github.com/wazuh/wazuh/issues/20811
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4675-3600m/B4675_manager_centos/plots/monitor-manager-Test_stress_B4675_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4675-3600m/B4675_manager_centos/plots/monitor-manager-Test_stress_B4675_manager-pre-release_Write_Ops.png)

- 4.7.0 Manager - https://github.com/wazuh/wazuh/issues/20290
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4585-3600m/B4585_manager_centos/plots/monitor-manager-Test_stress_B4585_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4585-3600m/B4585_manager_centos/plots/monitor-manager-Test_stress_B4585_manager-pre-release_Write_Ops.png)

Further research is required

**Comment by JorgeMarinoDev** [comment]
Research in progress. Just a quick update here.

![image](https://github.com/wazuh/wazuh/assets/117848458/ad524902-ccad-4d7e-bf07-09bbb94b4468)

Although Ops and Bytes are related, and very close ~15% increase. We must confirm this is acceptable.

* Run Conditions are the same. (time, events, drops, etc)
* Changelog is Huge. Requesting assistance to Core team.

**Comment by JorgeMarinoDev** [comment]
Although ETA for this task is Dec 21 2023. Putting this on Hold since we need some assistance from Core Team in order to disregard this increase or file a new issue. Work In Progress.

**Comment by JorgeMarinoDev** [comment]
Adding more information.

Focus on checking is SCA is responsible.

Comparing :
[Build #4682 [pre-release][4.8.0-alpha1][ALL-EXCEPT-SCA][2.5d]](https://ci.wazuh.info/job/Test_stress/4682/)
[Build #4703 [pre-release][4.7.1-rc2][ALL-EXCEPT-SCA][2.5d]](https://ci.wazuh.info/job/Test_stress/4703/)

Analysis of CSV Without SCA Module

![image](https://github.com/wazuh/wazuh/assets/117848458/26fec676-7961-4e04-9dad-f791c72638a5)

Further research is needed.

**Comment by LucioDonda** [comment]
Taking the above analysis to another footprint test ([ Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/20815)) we have found a similar behavior and value:
![image](https://github.com/wazuh/wazuh/assets/95248059/9dd6beb4-3067-436c-9161-2898ca025355)
Part of that is also supported on several graphs of the same test, the only module writing to disk is modulesd (sca):
Events Decoded:
4.8.0
![decodedFromSca480](https://github.com/wazuh/wazuh/assets/95248059/13671b9b-f6ad-4e39-bfdd-f962f1e5abcf)

4.7.0
![decodedFromSca470](https://github.com/wazuh/wazuh/assets/95248059/24a57468-d500-4d7b-b20d-03978064a618)

Write Ops:
4.8.0
![WriteOps480](https://github.com/wazuh/wazuh/assets/95248059/fa03f204-ec50-4306-a08b-f4774674a8cc)

4.7.0
![WriteOps470](https://github.com/wazuh/wazuh/assets/95248059/7eda3ae8-202a-4598-9a7e-4eda744c6a45)

Based on that we can say that there are some probes that the main cause of this increase are the last changes of SCA merged in 4.8.0, to name a few files modified:
![image](https://github.com/wazuh/wazuh/assets/95248059/8b81be5a-7f29-478f-a22e-a366e4e57877)

*[source](https://github.com/wazuh/wazuh/compare/v4.7.0...v4.8.0-alpha1)
