### ISSUE TITLE
Increment of Values in the `Disk_Read` Graph

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#20899]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.8.0-alpha1 |  Manager | Packages | -  |

I have found similar values for `wazuh-modulesd` but I have not found the behavior of `wazuh-syscheckd` in previous graphs. 

> Testing: https://github.com/wazuh/wazuh/issues/20802

<details>
   <summary>4.8.0 - Alpha 1</summary>
   <br/>

> Testing: https://github.com/wazuh/wazuh/issues/20802

![image](https://github.com/wazuh/wazuh/assets/54536265/940eadbb-268c-4f53-aaef-af8c6b6136b0)

</details>

<details>
   <summary>4.7.1 - RC 2</summary>
   <br/>

> https://github.com/wazuh/wazuh/issues/20823

![image](https://github.com/wazuh/wazuh/assets/54536265/ea8d99a1-5f34-443c-b78a-38c9a21e4736)

</details>

<details>
   <summary>4.7.1 - RC 1</summary>
   <br/>

> https://github.com/wazuh/wazuh/issues/20558

![image](https://github.com/wazuh/wazuh/assets/54536265/f75f89a5-ce31-411a-95e3-372ab5c69937)

</details>

<details>
   <summary>4.7.0 - RC 1</summary>
   <br/>

> https://github.com/wazuh/wazuh/issues/20299

![image](https://github.com/wazuh/wazuh/assets/54536265/46f2d05b-e67d-4226-b340-b1958f53ceb7)

</details>

<details>
   <summary>4.7.0 - Alpha 2</summary>
   <br/>

> https://github.com/wazuh/wazuh/issues/20058

![image](https://github.com/wazuh/wazuh/assets/54536265/b33d42bd-070e-44a1-8cd3-7c9f24ad39cb)

</details>

**Comment by JorgeMarinoDev** [comment]
Report Quick Fix

>>> I have found similar values for wazuh-modulesd but I have not found the behavior of wazuh-syscheckd in previous graphs.

It's not wazuh-syscheckd but wazuh-monitord that shows an increase here. Research in progress.

**Comment by JorgeMarinoDev** [comment]
**Read GBs Comparisson**

![image](https://github.com/wazuh/wazuh/assets/117848458/b7cc5871-bef0-4c1b-80bc-0449aa8aaf38)

**Conclusions for 2.5 Days stress tests Read Bytes**
* There is a significant decrease in Read Bytes in **wazuh-modulesd** in 4.8.0. (~1800GB total / ~30GB hourly ) 
* There is an increase in Read Bytes in **wazuh-monitord** in 4.8.0 (900 GB) (+ ~16GB hourly)
* Taking into account the total Read Bytes by these modules we end up with a decrease of 30% (~814GB / ~13GB Hourly).
* This volume of Disk Read Operations do not represent any harm to be considered in 4.8.0.
* Please Disregard. Disk Read Operations may have impact on Memory or CPU but not on Disk Usage.
