### ISSUE TITLE
Enable Wazuh client to work through explicit proxy

### ISSUE THREAD

**Issue by theflakes** [wazuh/wazuh#209]
This would be beneficial for deploying Wazuh in more restrictive networks where the server sits outside of the proxy the clients are using.  

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384075(v=vs.85).aspx

**Comment by snaow** [comment]
Thanks @theflakes, we will take note of it,  Windows agent should take into account proxy settings in Windows OS.
