### ISSUE TITLE
audit.key isn't decoded properly

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2091]
Hi team,

I've found a problem in the `audit` decoders. Currently, the value for an auditd key can contain characters such as `-`, `:` or `.` among others. 

The problem is that we decode the key with the following regular expression:

```
<regex offset="after_regex">key=\p(\S+)\p</regex>
```

So if we found a character that matches `\p` defined [here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) we stop reading the rest of the key.

## Example
Our audit key is `audit-wazuh-w` as defined in [our CDB list](https://github.com/wazuh/wazuh/blob/3.8/etc/lists/audit-keys). Because of this problem, the decoded field `audit.key` is `audit` and not `audit-wazuh-w`. 

Therefore, the rule matched is
```
<rule id="80700" level="0">
   <decoded_as>auditd</decoded_as>
   <description>Audit: messages grouped.</description>
</rule>
```

instead of 

```
<rule id="80780" level="3">
    <if_sid>80700</if_sid>
    <list field="audit.key" lookup="match_key_value" check_value="write">etc/lists/audit-keys</list>
    <description>Audit: Watch - Write access</description>
    <group>audit_watch_write,gdpr_IV_30.1.g,</group>
</rule>
```

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
Hi team, 

We're reopening this issue because we found a log where this regex doesn't work as expected.

### Log

```
type=SYSCALL msg=audit(1546510049.132:1054841): arch=c000003e syscall=59 success=yes exit=0 a0=cc7e30 a1=ca09b0 a2=c9aae0 a3=7ffc7498b760 items=2 ppid=9927 pid=13384 auid=1001 uid=1001 gid=1001 euid=1001 suid=1001 fsuid=1001 egid=1001 sgid=1001 fsgid=1001 tty=pts0 ses=1627 comm="ping" exe="/usr/bin/ping" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="audit-wazuh-c"
```

We found that this regex only fails when the key isn't followed by any space.

### Test with ossec-regex without space
```
# ossec-regex 'key="(\S+)"'
key="test"
+OSRegex_Execute: key="test"
 -Substring: test"  <----- 
+OS_Regex       : key="test"
```
### Test with ossec-regex with space

```
# ossec-regex 'key="(\S+)"'
key="test" 
+OSRegex_Execute: key="test" 
 -Substring: test  <----- 
+OS_Regex       : key="test" 
```

**Comment by vikman90** [comment]
Please check that we extract all these fields:

```shellsession
$ egrep -o ' .[^=]+' /var/log/audit/audit.log | egrep -o '\S+' | sort | uniq
a0
a1
a2
a3
acct
addr
algo
arch
audit_backlog_limit
audit_failure
auid
cipher
cmd
comm
default-context
direction
egid
euid
exe
exit
format
fp
fsgid
fsuid
gid
gpg_res
grantors
hostname
id
items
kernel
key
key_enforce
kind
ksize
laddr
list
lport
mac
msg
new-level
old
old-auid
old-ses
op
pfs
pid
ppid
proctitle
res
root_dir
rport
selected-context
ses
sgid
size
spid
subj
success
suid
sw_type
syscall
terminal
tty
uid
ver
```

**Comment by vikman90** [comment]
The bug is fixed now. We will extend the field support in #2240.
