### ISSUE TITLE
Vulnerability Detector refactor: syscollector-packages component has more than one element with the same PK value

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20912]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - `dev-14153-vulndet-refactor ` |   | Manager | Packages | Ubuntu 22 |

| Related Issue| 
| --- |
| https://github.com/wazuh/wazuh/issues/20785 |

### Description

During testing iteration specified in https://github.com/wazuh/wazuh/issues/20785, it has been detected the following error in the master node:

```
2023/12/15 09:10:49 wazuh-db: WARNING: DB(000) syscollector-packages component has more than one element with the same PK value '9594accc64340409f16c73f07d68a193a02ed68e'.
2023/12/15 09:10:49 wazuh-db: WARNING: DB(000) syscollector-packages component has more than one element with the same PK value 'ac609c5c98040d8656460b3045f0bbfe3eeca71c'.
```

### Steps to reproduce
- Deploy a cluster environment
- Init the cluster environment
- Restart the worker and the master node during the syscollector scan

**Comment by Dwordcito** [comment]
This issue is related to the fix: https://github.com/wazuh/wazuh/issues/20499

When this issue was tested, the rebase was not yet there and that is why it was visible.
