### ISSUE TITLE
Vulnerability Detector: There was an error assigning the groups to agent

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20915]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - `dev-14153-vulndet-refactor ` |   | Manager | Packages | Ubuntu 22 |

| Related Issue| 
| --- |
| https://github.com/wazuh/wazuh/issues/20785 |

### Description

During the testing iteration outlined in https://github.com/wazuh/wazuh/issues/20785, it has been detected the following errors after deleting an agent
``` 
2023/12/18 12:25:28 wazuh-authd: INFO: Agent '002' (ip-172-31-3-206.ec2.internal) deleted (requested locally)
2023/12/18 12:25:33 wazuh-db: ERROR: There was an error assigning the groups to agent '002'
2023/12/18 12:25:33 wazuh-db: WARNING: The groups were empty right after the set for agent '002'
``` 

### Steps to reproduce
- Deploy a Wazuh cluster environment.
- Initialize the cluster environment.
- Register an agent to the worker node 
- Remove the agent intermediately using the CLI in the manager
- Observe the following error in the master log files
```
2023/12/18 12:25:28 wazuh-authd: INFO: Agent '002' (ip-172-31-3-206.ec2.internal) deleted (requested locally)
2023/12/18 12:25:33 wazuh-db: ERROR: There was an error assigning the groups to agent '002'
2023/12/18 12:25:33 wazuh-db: WARNING: The groups were empty right after the set for agent '002'\
```

**Comment by Dwordcito** [comment]
This is related to the blocking in wazuh-db/remoted/modulesd -> fixed in https://github.com/wazuh/wazuh/issues/20424
