### ISSUE TITLE
Changes in Agentd and Modulesd activity in Ubuntu agent in footprint tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20911]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha 1 | Agentd and Modulesd | Agent | Packages | Ubuntu |

## Description

During research of https://github.com/wazuh/wazuh/issues/20813 increased activity levels for Agentd `RSS`, `PSS `and `VMS `as well a big decrease in Modulesd `VMS`. The changes can be detected in relation to 4.7.0 and 4.6.0.

### Evidence

- 4.8.0-alpha1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4668-3600m/B4668_agent_ubuntu/plots/monitor-agent-Test_stress_B4668_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4668-3600m/B4668_agent_ubuntu/plots/monitor-agent-Test_stress_B4668_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4668-3600m/B4668_agent_ubuntu/plots/monitor-agent-Test_stress_B4668_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4668-3600m/B4668_agent_ubuntu/plots/monitor-agent-Test_stress_B4668_ubuntu-pre-release_VMS.png)

- 4.7.0-rc1
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4578-3600m/B4578_agent_ubuntu/plots/monitor-agent-Test_stress_B4578_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4578-3600m/B4578_agent_ubuntu/plots/monitor-agent-Test_stress_B4578_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4578-3600m/B4578_agent_ubuntu/plots/monitor-agent-Test_stress_B4578_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4578-3600m/B4578_agent_ubuntu/plots/monitor-agent-Test_stress_B4578_ubuntu-pre-release_VMS.png)

Further research is required

**Comment by nmkoremblum** [comment]
This is the comparison of the maximum values of the reported metrics:

Module | Metric | 4.7.1 Value (KB) | 4.8.0 Value (KB) | Difference (KB) | Percentage Change
-- | -- | -- | -- | -- | --
wazuh-modulesd | RSS | 6440 | 6536 | 96 | +1.49%
wazuh-modulesd | PSS | 3865 | 4012 | 147 | +3.81%
wazuh-modulesd | USS | 2968 | 3104 | 136 | +4.58%
wazuh-agentd | RSS | 5820 | 6028 | 208 | +3.57%
wazuh-agentd | PSS | 3239 | 3324 | 85 | +2.62%
wazuh-agentd | USS | 2864 | 2916 | 52 | +1.81%

The maximum increase is about 5% (136kb difference) and the maximum total difference is about 208kb.

Tracking back these memory increases to the code is very difficult as there have been many changes in the new release, but I don't think this is a concern unless other anomalies are observed.

I do find it strange that `syscheck` is the module that consumes the most memory, even though this module is disabled. This happens in older tests as well.
