### ISSUE TITLE
Decreased events and Read/Write Operations on Linux Agents in stress tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#20913]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Wazuh component | Agent | Packages| Linux |

## Description

During Issue https://github.com/wazuh/wazuh/issues/20808 it was detected a big decrease (around 50%) of `Read_Ops` and `Write_Ops`, as well of  a 33% decrease of generated events on Linux Agents. Further research is required.

- 4.8.0-alpha 1 Ubuntu Agent
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_ubuntu/plots/monitor-agent-Test_stress_B4670_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_ubuntu/plots/monitor-agent-Test_stress_B4670_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_ubuntu/plots/Test_stress_B4670_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
- 4.7.0-rc1 Ubuntu Agent https://github.com/wazuh/wazuh/issues/20294
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_ubuntu/plots/monitor-agent-Test_stress_B4580_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_ubuntu/plots/monitor-agent-Test_stress_B4580_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_ubuntu/plots/Test_stress_B4580_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)

- 4.8.0-alpha1 CentosAgent
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_centos/plots/monitor-agent-Test_stress_B4670_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_centos/plots/monitor-agent-Test_stress_B4670_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_centos/plots/Test_stress_B4670_centos_agentd_state_AgentD_Number_of_generated_events.png)

- 4.7.0-rc1 Centos Agent https://github.com/wazuh/wazuh/issues/20294
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_centos/plots/monitor-agent-Test_stress_B4580_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_centos/plots/monitor-agent-Test_stress_B4580_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_centos/plots/Test_stress_B4580_centos_agentd_state_AgentD_Number_of_generated_events.png)

**Comment by cborla** [comment]
## Analysis

As mentioned in the issue, the reported problem is clear, there is a decrease in the number of events generated by the agent, thus decreasing the number of writes and reads.

Analyzing the graph, there is a clear inflection point which impacts all 3 graphs, agreeing with the theory that the decrease in the number of events generated is the cause of the drop in `Read_Ops` and `Write_Ops`.

![image](https://github.com/wazuh/wazuh/assets/41765669/8a371a6a-a525-44c2-b9bf-02cf50882c7e)

Investigating the performance of the test, it is observed that the number of times alerts are triggered differs considerably from test to test.

From :
- 4.8.0: Ubuntu Agent: [ossec_Test_stress_B4670_ubuntu_2023-12-13.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4670-3600m/B4670_agent_ubuntu/logs/ossec_Test_stress_B4670_ubuntu_2023-12-13.zip)
- 4.7.0: Ubuntu Agent: [ossec_Test_stress_B4580_ubuntu_2023-11-16.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.0/B4580-3600m/B4580_agent_ubuntu/logs/ossec_Test_stress_B4580_ubuntu_2023-11-16.zip)

Compare from file `/tmp/test_active_response.log`

|Version| Test Fired times| 
|---|---|
|4.8.0| 124041 |
|4.7.0| 206421 |

## Conclusion
The difference in the number of times the test was run between the versions is considerable, 82,380, approximately 50% less events generated by the test for version 4.8.0. 
It should be analyzed why the test failed on those agents, and not the agents themselves.
