### ISSUE TITLE
Race Condition Error Agent Registration on Master Restart

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#20914]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - `dev-14153-vulndet-refactor ` |   | Manager | Packages | Ubuntu 22 |

| Related Issue| 
| --- |
| https://github.com/wazuh/wazuh/issues/20785 |

### Description

During the testing iteration outlined in https://github.com/wazuh/wazuh/issues/20785, a issue was identified in the agent registration process when the master node is restarted under specific circumstances.

If the master node is restarted precisely when the worker node is in the process of handling the 'Dispatching request to master node' event, the registration request becomes stuck in an endless loop. Consequently, this results in the worker node being authd blocked, preventing successful agent registration.

It is crucial to address this timing-sensitive scenario to ensure seamless agent registration even in the event of master node restarts during the mentioned processing phase.

### Steps to reproduce
- Deploy a Wazuh cluster environment.
- Initialize the cluster environment.
- Configure an agent with the worker node IP.
- Simultaneously start the agent and the master node.
- Observe the behavior to verify that the worker node is in a waiting state for the specified event.

```
2023/12/18 12:01:34 wazuh-authd: INFO: Dispatching request to master node`
```
- Check that the agent is never registered and the worker node is blocked for a few minutes
- Check that the agent finally is registered. However, it appears as duplicated

### Evidences 
[Environment Logs](https://github.com/wazuh/wazuh/files/13703600/envlogs.zip)

**Comment by pereyra-m** [comment]
Hi @Rebits !

I've working on this issue, let me share with you the results from my tests in both the development branch and `4.8.0`. The new vulnerability detector doesn't change the registration process, that's why I made the comparison. 

The message `WARNING: Cluster error detected` doesn't give enough details to find the cause behind it.
I've added some extra messages and every time the worker tries to connect with the master and it's down we'll see it.
The real error code is

```
2023/12/21 23:02:37 wazuh-authd: WARNING: Message received: {"__wazuh_exception__": {"__class__": "WazuhClusterError", "__object__": {"type": "about:blank", "title": "Wazuh Cluster Error", "code": 3023, "extra_message": null, "extra_remediation": null, "cmd_error": false, "dapi_errors": {}}}}
```

In `framework/wazuh/core/exception.py` we see that
```
 3023: {'message': 'Worker node is not connected to master', ...
```

This happens in both branches.
Also, remember that only the master is allowed to generate a new key, so every registration request in the worker node is always forwarded. A warning is expected.

What is certainly a race condition and an unexpected situation is an endless loop where the agent keeps requesting a key and the manager denies it, but only if it's the first registration of the agent. If it isn't, this situation could happen.
In the manager logs we see many messages like this one

```
2023/12/18 12:15:28 wazuh-authd: WARNING: Duplicate name 'ip-172-31-3-206.ec2.internal', rejecting enrollment. Agent '001' doesn't comply with the registration time to be removed.
```

This means that the agent is unable to connect and requests a new key, but there is a recently connected agent with the same name and the `force` options block is preventing the replacement of the old agent.

This issue could be investigated more in-depth, but it doesn't seem related to the development branch.

**Comment by Dwordcito** [comment]
Based on the analysis https://github.com/wazuh/wazuh/issues/20914#issuecomment-1867192538, this bug is not from the VD development branch.

**Comment by JorgeMarinoDev** [comment]
Just a quick update here. 
Starting to deploy environment locally. 

Red Hat Enterprise Linux release 8.9

| Component          | IP Address    |
|--------------------|---------------|
| Wazuh dashboard   | 192.168.1.170 |
| Wazuh indexer     | 192.168.1.171 |
| Wazuh server 1    | 192.168.1.172 |
| Wazuh server 2    | 192.168.1.173 |
| Wazuh agent       | 192.168.1.174 |

**Comment by Rebits** [comment]
It seems that after fixing https://github.com/wazuh/wazuh/issues/20790, it is not possible to replicate this issue.
However, it has been detected new warnings:
``` 
2024/01/08 17:49:15 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '018' at 'any'.
2024/01/08 17:49:15 wazuh-remoted: WARNING: Decrypt the message fail, socket 28
2024/01/08 17:49:15 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2024/01/08 17:49:15 wazuh-syscheckd: INFO: FIM sync module started.
2024/01/08 17:49:17 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2024/01/08 17:49:17 sca: INFO: Security Configuration Assessment scan finished. Duration: 9 seconds.
2024/01/08 17:49:20 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '018' at 'any'.
2024/01/08 17:49:20 wazuh-remoted: WARNING: Decrypt the message fail, socket 28
2024/01/08 17:49:25 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '018' at 'any'.
2024/01/08 17:49:25 wazuh-remoted: WARNING: Decrypt the message fail, socket 28
``` 

This seems to not be related with original issue reported, so I suggest to open a new issue to track it.

**Comment by JorgeMarinoDev** [comment]
@Rebits 

Briefing:

- [ ] @pereyra-m @Dwordcito could not reproduce this in this VD specific branch.
- [ ] @nbertoldo could not reproduce this in 4.7.0 from packages.
- [ ] @JorgeMarinoDev could not reproduce this in 4.8.0 from packages.
- [ ] @Rebits could not reproduce this either after fixing #20790

We could:

1. @wazuh/qa Add a specific test in the next testing stages.
2. Find solid evidence that #20790 fixes this. (Can't be backed up unless we could repro this before the fix)

Please @wazuh/qa determine what's the best way to deal with this incident. 
On the technical side's POV we could not reproduce it. Therefore it might just have been an isolated non-deterministic behavior related to the testing instance in the first place.

Putting this On-Hold until clear definitions and consensus is reached.

Thank you.

**Comment by nbertoldo** [comment]
**Update:**
I have been trying to reproduce both the [initial issue](https://github.com/wazuh/wazuh/issues/20914#issue-2046552841) and the [new issue](https://github.com/wazuh/wazuh/issues/20914#issue-2046552841) from 4.8.0 packages, following the steps described, and I have not been able to reproduce either of them. Any details I might be missing?

**Comment by JorgeMarinoDev** [comment]
> **Update:** I have been trying to reproduce both the [initial issue](https://github.com/wazuh/wazuh/issues/20914#issue-2046552841) and the [new issue](https://github.com/wazuh/wazuh/issues/20914#issue-2046552841) from 4.8.0 packages, following the steps described, and I have not been able to reproduce either of them. Any details I might be missing?

No worries @nbertoldo . It looks like it's a non deterministic scenario. Let's just wait until @wazuh/qa determines  the next move here. Thank you! Good job btw!

**Comment by Rebits** [comment]
Due to the non deterministic condition of this issue and the impossibility to replicate after https://github.com/wazuh/wazuh/issues/20790 I suggest to close this issue for now until new evidences emerges.


Open Issue to track [reported error](https://github.com/wazuh/wazuh/issues/20914#issuecomment-1881601291): https://github.com/wazuh/wazuh/issues/21297

**Comment by vikman90** [comment]
Thank you all,

We agreed to close this issue as non-reproducible for the time being. Anyway, this should not be related to 4.8.0.
