### ISSUE TITLE
 WPK Upgrade Fail in Fedora 38

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#20924]
Found issue in WPK upgrade test information #20898

|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         | #20898 |
| **Version**                              | 4.7.1 |
| **Release candidate #**                  | RC 3 |
| **Tag**                                  | v4.7.1-rc3 |
| **Previous WPK upgrade tests issue** | #20701 |

|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Operating System**         | Fedora 38 |
| **Upgrade from**         | v4.7.0 |
| **Upgrade WPK type**         | Forcing Failed Upgrade |
| **Manager**         | v4.7.1-rc3 Ubuntu 22 |

## Description

```sh
# cat -f /var/ossec/logs/upgrade.log
2023/12/18 20:21:55 - Generating Backup.
xargs: tar: No such file or directory
2023/12/18 20:21:56 - Error creating the Backup, interrupting upgrade.
```

This condition was found on the following vagrant boxes:
- generic/fedora38
- generic-x64/fedora38

**Comment by ncvicchi** [comment]
Hello @nmkoremblum! 

Could you please provide more details about this issue? Link to the package used, steps to reproduce, commands used, expected behavior, and actual results?

Regards!

**Comment by ncvicchi** [comment]
Hello @nmkoremblum!

Do we have any update on this?

**Comment by ncvicchi** [comment]
Hello @nmkoremblum!

Do we have any update on this?
