### ISSUE TITLE
Comparison error in the password changing script

### ISSUE THREAD

**Issue by micsinyei** [wazuh/wazuh#20935]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7 | Wazuh indexer? | All-in-one | Puppet | Ubuntu latest LTS |

I tried to install wazuh via puppet and since it comes with default credentials I wanted to change them. I tried this:
`class { 'wazuh::filebeat_oss':
    #filebeat_oss_elastic_user => $wazuh_user,
    #filebeat_oss_elastic_password => $wazuh_pw,
  }`
But it did not work, then I tried to execute the password changing file and then I noticed it has a comparison error in the `passwords_getNetworkHost()` function. The code look like this:
`
function passwords_getNetworkHost() {

    IP=$(grep -hr "network.host:" /etc/wazuh-indexer/opensearch.yml)
    NH="network.host: "
    IP="${IP//$NH}"

    #allow to find ip with an interface
    if [[ ${IP} =~ _.*_ ]]; then
        interface="${IP//_}"
        IP=$(ip -o -4 addr list "${interface}" | awk '{print $4}' | cut -d/ -f1)
    fi

    if [ "${IP}" == "0.0.0.0" ]; then
        IP="localhost"
    fi}
`
The issue is in the `opensearch.yml` the network host is defined with quotes and when the comparison comes it will be like this:
`
+ passwords_getNetworkHost
++ grep -hr network.host: /etc/wazuh-indexer/opensearch.yml
+ IP='network.host: "0.0.0.0"'
+ NH='network.host: '
+ IP='"0.0.0.0"'
+ [[ "0.0.0.0" =~ _.*_ ]]
+ '[' '"0.0.0.0"' == 0.0.0.0 ']'

`
Therefore the ip will not be changed to localhost and in the next step the script will fail.
I believe the script should be changed and not the deployment but I am open to discussions.

**Comment by davidcr01** [comment]
It seems like you've identified a potential issue in the script where the network host is retrieved from the opensearch.yml file and compared. The fact that the network host is defined with quotes in the opensearch.yml file could indeed lead to unexpected behavior in the comparison.

To address this issue, you can modify the `passwords_getNetworkHost()` function to handle the quotes in the comparison. One way to do this is by removing the quotes from the extracted IP before the comparison. Here's an updated version of the function:

```bash
function passwords_getNetworkHost() {

    IP=$(grep -hr "^network.host:" /etc/wazuh-indexer/opensearch.yml)
    NH="network.host: "
    IP="${IP//$NH}"

    # Remove surrounding double quotes if present
    IP="${IP//\"}"

    # Allow finding IP with an interface
    if [[ ${IP} =~ _.*_ ]]; then
        interface="${IP//_}"
        IP=$(ip -o -4 addr list "${interface}" | awk '{print $4}' | cut -d/ -f1)
    fi

    if [ "${IP}" == "0.0.0.0" ]; then
        IP="localhost"
    fi
}
```
With this modification, the function should handle cases where the network host is defined with quotes in the opensearch.yml file. The `IP="${IP//\"}"` line removes any double quotes surrounding the IP address before the comparison.

After making this change, you can test the script again to ensure that it correctly handles the network host comparison and updates the IP address as needed.

From Wazuh, we will perform a development to fix this issue and merge the changes when corresponding.

**Comment by davidcr01** [comment]
It seems like you've identified a potential issue in the script where the network host is retrieved from the opensearch.yml file and compared. The fact that the network host is defined with quotes in the opensearch.yml file could indeed lead to unexpected behavior in the comparison.

To address this issue, you can modify the `passwords_getNetworkHost()` function to handle the quotes in the comparison. One way to do this is by removing the quotes from the extracted IP before the comparison. Here's an updated version of the function:

```bash
function passwords_getNetworkHost() {

    IP=$(grep -hr "^network.host:" /etc/wazuh-indexer/opensearch.yml)
    NH="network.host: "
    IP="${IP//$NH}"

    # Remove surrounding double quotes if present
    IP="${IP//\"}"

    # Allow finding IP with an interface
    if [[ ${IP} =~ _.*_ ]]; then
        interface="${IP//_}"
        IP=$(ip -o -4 addr list "${interface}" | awk '{print $4}' | cut -d/ -f1)
    fi

    if [ "${IP}" == "0.0.0.0" ]; then
        IP="localhost"
    fi
}
```
With this modification, the function should handle cases where the network host is defined with quotes in the opensearch.yml file. The `IP="${IP//\"}"` line removes any double quotes surrounding the IP address before the comparison.

After making this change, you can test the script again to ensure that it correctly handles the network host comparison and updates the IP address as needed.

From Wazuh, we will perform a development to fix this issue and merge the changes when corresponding.
