### ISSUE TITLE
Research and decide how to run the `HAProxy helper` in cluster

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#20937]
| Epic | 
|--|
|https://github.com/wazuh/wazuh/issues/20887|

## Description
The HAProxy helper is being migrated to the wazuh manager. Since enabling it makes only sense in cluster environments, it should be placed under the [cluster folder](https://github.com/wazuh/wazuh/tree/master/framework/wazuh/core/cluster), inside its own new folder (same as [dapi](https://github.com/wazuh/wazuh/tree/master/framework/wazuh/core/cluster/dapi)).

However, we still must investigate and choose between alternatives for its execution. For example:
- Should it be run as a separate process?
- Should it be run as a child process of the cluster? And in that case:
  - The coordinator usually spends most of its time sleeping. Is it possible to adapt the code to run asynchronously and do other tasks in the meantime or should a process keep doing only this?
  - If we dedicate a child process only for the execution of the coordinator, should we increase the number of processes? What would happen in those cases where the [number of child processes](https://github.com/wazuh/wazuh/blob/8cbe309cdd4577853f257183d84ab87b8eff90e6/framework/wazuh/core/cluster/cluster.json#L95) is set to be 0? It should also work in these cases, for which it should be asynchronous.

In this issue, an answer to these questions is expected. Also, analyzing and understanding the coordinator's code for its inclusion in the manager and determining if it is possible to transform it into asynchronous tasks.

**Comment by nico-stefani** [comment]
# Update

I've been looking at the involved code, cluster, and coordinator.

**Comment by nico-stefani** [comment]
Most of the logic of the coordinator consists of HTTP requests, to the Wazuh API and HAProxy. This can be easily adapted to an asynchronous schema.
Using a library with async support can we transform all the requests and adapt the functions/methods and callbacks. A good option to do this is [httpx](https://www.python-httpx.org/async/).

**Comment by nico-stefani** [comment]
# Conclusion

As I mentioned before, the current coordinator code consists mainly of HTTP requests. Given is I/O bound program, is a good use case to go with asyncio.

The best way to integrate the HAProxy helper is to include it in the `LocalServerMaster` as a new task, as we are doing with the DAPI processes.

https://github.com/wazuh/wazuh/blob/037ede2424c1c4402068bc0a1651836f732ccc70/framework/wazuh/core/cluster/local_server.py#L355

During the migration can we refactor the [coordinator script](https://github.com/wazuh/wazuh-tools/blob/dev-wazuh-coordinator/framework/wazuh_coordinator/wazuh_coordinator/scripts/coordinator.py) to be included into the main loop as a new coroutine.

With this approach, we avoid handling child processes and we give the control of the execution to the async loop.

**Comment by mhamra** [comment]
### PEER REVIEW
I agree with @nico-stefani that the coordinator may run as an async task. All the calls made by the coordinator task to the `httpx` coroutines must be awaited to avoid blocking the process event loop.

A critical thing to define is how to schedule the coordinator's task. The current coordinator runs periodically, and the wait time is defined in a configuration file.

A simple design could be:
- At cluster startup, the cluster script reads the configuration file.
- The cluster script runs the coordinator task. The task receives the `wait_time_in_sec` parameter and runs an infinite loop. In the endless loop, the task executes the logic of the coordinator and, after finishing, calls the `asyncio.sleep(wait_time_in_sec)` to wait for the next iteration.

The drawback of this method is that any potential non-managed exception can stop the coordinator. 

It will also be good to have an option to stop and start the coordinator task manually. The task can be canceled using the `task.cancel()` method. To restart the task and schedule it again, there must be some checks to avoid running multiple coordinator tasks simultaneously. 

New endpoints GET /coordinator/start,  GET /coordinator/stop, and GET /coordinator/status may be developed to control and get information from the coordinator task.

**Comment by Selutario** [comment]
LGTM @nico-stefani and @mhamra. I agree with most of the proposed, except for this paragraph:

> We also need to consider that the current coordinator script must be restarted when the configuration changes (for example, when a new node is added to or removed from the cluster). The same thing can be achieved by modifying the configuration and restarting the coordinator task in the cluster.

As we discussed afterward, restarting the coordinator when changing the `ossec.conf` file won't be necessary since none of the configurations listed there is hot applied. Therefore, users must keep restarting the whole manager to apply any changes instead of offering new endpoints or doing any `task.cancel()`
