### ISSUE TITLE
Accidential 4.8.0 release?

### ISSUE THREAD

**Issue by greenaar** [wazuh/wazuh#20945]
I see a 4.8.0 agent (debian) released, with mentions of 4.8.0 manager (file not found).

I also see 4.7.1-1 was released today - was the release of 4.8.0 an accident?

**Comment by csoc-technik** [comment]
There is a wazuh-agent-4.8.0 package available. **This should not be there.** Please quickly remove the package from the repository.

apt list --upgradable
...
wazuh-agent/stable 4.8.0-python310 amd64 [aktualisierbar von: 4.7.0-1]

**Comment by joe-rh** [comment]
I'm currently experiencing the following:

```
Err:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-manager amd64 4.8.0-python310
  404  Not Found [IP: 99.86.229.76 443]
E: Failed to fetch https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.8.0-python310_amd64.deb  404  Not Found [IP: 99.86.229.76 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by joe-rh** [comment]
Temporary workaround for `wazuh-manager`, in `/etc/apt/preferences`:

```
Package:  wazuh-manager
Pin:  version 4.7.0-1
Pin-Priority: 1001
```

`apt update`, `apt upgrade` etc.

**Comment by rauldpm** [comment]
Hello, we are aware of the existence of this problem, and we are already acting to return the service to normal operation as soon as possible, thank you for the notice.

**Comment by rauldpm** [comment]
Hello, the problem should be solved now, can you check again?

**Comment by greenaar** [comment]
Confirmed, though i did have to manually clear /var/lib/apt/lists to get apt to stop insisting there was an update. After purging that dir, apt update no longer shows 4.8.0.

Thanks!

**Comment by csoc-technik** [comment]
Is there an automated option so that you don't have to intervene manually?
Otherwise the error will persist on many systems. Since this Wazuh version 4.8.0-python310 is not downloadable, will all future updates of the Wazuh Agent fail?

**Comment by dariosusman** [comment]
I couldn't find any. I could just do this, without impacting anything else:

```rm /var/lib/apt/lists/packages.wazuh.com_4.x_apt_dists_stable_*```
