### ISSUE TITLE
Share middleware global variables between processes

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#20943]
|Component|
|---|
| API |

## Description
With the introduction of Connexion 3.0 and Uvicorn, the API can run multiple parallel worker processes. The current middleware code uses the following global variables:

https://github.com/wazuh/wazuh/blob/bb9986d7c5d9f63459b419057a03f60ab70856a9/api/api/middlewares.py#L43-L48

These variables must be shared between processes with synchronized access. The API code must be modified to:

- Create and initialize a shared structure with all these variables in the main process.
- Pass the shared structure to the worker processes.
- Access and update the shared structure with the same existing logic but with synchronized access.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Closing for now as it does not fit any current objective.
