### ISSUE TITLE
Vulnerability detection is triggering duplicate alerts.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#20958]
# Description 

It was found during the vulnerability detection exploratory that the alerts are duplicate. 

![image](https://github.com/wazuh/wazuh/assets/13010397/a25a98db-567f-46e5-8a67-1fb1bbb63c80)
![image](https://github.com/wazuh/wazuh/assets/13010397/b016e57f-d0ce-4cd0-811e-3f32eac062b7)

These 3 for xxd package only differ in the timestamp and id (Not CVE ID)

![image](https://github.com/wazuh/wazuh/assets/13010397/51a5aecb-b66d-42ec-b241-8eecb365df85)

There are only 5 new vulnerable packages 

![image](https://github.com/wazuh/wazuh/assets/13010397/6dd6fff6-bb85-4709-a07c-f34268f634fd)

## DoD 

- [ ] RCA of this behavior
- [ ] Propose a fix

**Comment by MiguelazoDS** [comment]
# Update 

This behavior was not possible to reproduce again. The issue was created because if this was a real case, it could also affect the indexing of vulnerabilities, but some steps could have been performed badly and created the illusion this was a failure. 

In addition, another behavior was found where matches, alerts, and indexed vulnerabilities do not match, but in any case, there were duplicate alerts. 

https://github.com/wazuh/wazuh/issues/21020

**Comment by Dwordcito** [comment]
LGTM
