### ISSUE TITLE
Handling VD configuration in upgrade scenarios to v4.8

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#20952]
## Description

With the introduction of Wazuh v4.8, significant modifications have been made to the Vulnerability Detector (VD) configuration block. Consequently, in upgrade scenarios from previous versions, the existing VD configuration may become obsolete, leading to processing issues with the new version.

## Expected
Incorporate a mechanism to seamlessly manage the transition of VD configurations during the upgrade process, ensuring a smooth experience for the user.

### Use Cases

- Activated Old VD Configuration
  - Check for the existence of the previous VD configuration.
  - If activated, enable the current VD using default configurations.
  - Notify the user to update the VD configuration to the new version.

- Deactivated Old VD Configuration:
  - Check for the existence of the previous VD configuration.
  - If deactivated, ensure that the current VD does not initiate.
  - Notify the user to update the VD configuration to the new version.

- Presence of Both Configurations:
  - If both the old and new configurations exist, prioritize the configuration of the current VD.
  - Ensure the VD is configured according to version 4.8 specifications, disregarding the old configuration.

- Absence of Old Configuration:
  - If no old configuration is found, take no additional action.

## DoD

- [x] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [ ] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

**Comment by tsarquis88** [comment]
# Update

PR requirements were met: #20954.

Reviews were requested.
