### ISSUE TITLE
Internal error while ordering the vulnerability events 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#20959]
## Description

During the E2E test, it was found that ordering the alerts using a vulnerability field in the Threat Hunting panel,  generated an internal error

![2023-12-19_17-52](https://github.com/wazuh/wazuh/assets/65046601/cefe413e-3e9d-4ee0-b511-5cc28e8c6990)

![2023-12-19_17-52_1](https://github.com/wazuh/wazuh/assets/65046601/bb6be80a-9486-4cc7-b04b-a5220d6b3d0c)

```
unsupported_operation_exception
null
Error: Internal Server Error
    at fetch_Fetch.fetchResponse (https://demo-480-ct-wazuh-db177eddeaa0c3f6.elb.us-west-1.amazonaws.com/48001/bundles/core/core.entry.js:15:177223)
    at async interceptResponse (https://demo-480-ct-wazuh-db177eddeaa0c3f6.elb.us-west-1.amazonaws.com/48001/bundles/core/core.entry.js:15:172641)
    at async https://demo-480-ct-wazuh-db177eddeaa0c3f6.elb.us-west-1.amazonaws.com/48001/bundles/core/core.entry.js:15:175121
```

Related to this problem, the events panel of the new vulnerability detector section doesn't show any vulnerability alert

![2023-12-19_17-58](https://github.com/wazuh/wazuh/assets/65046601/3faf19e7-4526-479b-943c-83a8d193c991)

## DoD

- [ ] Find root cause of the issue and fix it
- [ ] Make sure the problem has been solved

**Comment by gdiazlo** [comment]
We have reproduced this on the platform Discover as well.

**Comment by jbiset** [comment]
## Research
Only in a demo environment have these problems been reproduced. In the development environment it has not been possible to reproduce these problems. Evidence is added below the tests in the demo environment. We have found that it does not only happen with fields in the vulnerabilities module.
The origin of this difference between the development environment and the demo continues to be investigated.

## Evidences

<details>
<summary>
 Ordering `data.vulnerability.cve` field on Events tab in Vulnerability detection :green_circle: 
</summary>

![Test_DEMO_1](https://github.com/wazuh/wazuh/assets/43619595/406ead22-a49d-4b2d-af6c-05b06246ec28)

![Test_DEMO_1_B](https://github.com/wazuh/wazuh/assets/43619595/ef43827c-c5d4-41fb-a9ca-5d4480fc0687)

![Test_DEMO_1_C](https://github.com/wazuh/wazuh/assets/43619595/f23dfc12-e750-4d8b-87e8-114fadc8a603)

</details>

<details>
<summary>
 Ordering `data.vulnerability.status` field on Events tab in Vulnerability detection :red_circle: 
</summary>

![Test_DEMO_2](https://github.com/wazuh/wazuh/assets/43619595/0d0212ea-3caf-423c-bb81-73ebb5b19d60)

![Test_DEMO_2_B](https://github.com/wazuh/wazuh/assets/43619595/5027f13d-d370-4fa4-8677-10cbea04720d)

![Test_DEMO_2_C](https://github.com/wazuh/wazuh/assets/43619595/887860e2-c5c3-416a-8de0-e09c0b820eef)

</details>

<details>
<summary>
 Ordering `data.win.system.message` field on Events tab in MITRE ATT&CK :red_circle: 
</summary>

![Test_DEMO_3](https://github.com/wazuh/wazuh/assets/43619595/4c97e69a-f6e4-48cd-83db-62bf990bca41)

![Test_DEMO_3_B](https://github.com/wazuh/wazuh/assets/43619595/cb260b20-6a93-45ee-ad32-8d5b022dfdaf)

</details>

<details>
<summary>
 Ordering `data.win.evendata.logonProcessName` field on Discover :red_circle:  
</summary>

![Test_DEMO_4](https://github.com/wazuh/wazuh/assets/43619595/24c5c9e5-8203-4b14-9cac-73d73e251a16)

</details>

**Comment by asteriscos** [comment]
We have been unable to replicate this issue in other environments. We believe this error comes from the pre-alpha environment it was tested on.
