### ISSUE TITLE
Add solved alerts to vulnerability detector

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#20965]
## Description

The old vulnerability detector has two types of vulnerabilities:
- Active: generated when a new vulnerability is found and added to the inventory
- Solved: generated when a vulnerability is removed from the inventory

However, only the active type of alert is implemented right now.

## DoD

- [x] Send the corresponding report when the vulnerability is removed from the inventory
- [x] Manual tests of the fix
- [x] Add UT
- [x] CI Pass

**Comment by MiguelazoDS** [comment]
# Update 12/29

Waiting for changes in the development branch to rebase.
