### ISSUE TITLE
The new vulnerability detector isn't subscribed to the RSync deleted events

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#20964]
## Description

During the E2E test it was found that when RSync deletes a package in the manager, the event isn't handled by vulnerability detector. The subscription to the `rsync-deleted` topic is missing.

## DoD

- [ ] Add the new subscription in the scanner and handle the corresponding events
- [ ] Make sure the issue has been solved
- [ ] Add UT
- [ ] CI PAss

**Comment by Dwordcito** [comment]
Solved by https://github.com/wazuh/wazuh/pull/20967/commits/bfffe9a34c6a9c6a5f5fa58deb983f6c7d33a959
