### ISSUE TITLE
Disabling the packages scan in syscollector doesn't remove the vulnerabilities in the inventory

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#20963]
## Description

During the E2E test it was found that the `integrity_clear` message isn't parsed by the new vulnerability detector.
When the packages scan is disabled in the agent, the agent's inventory is cleared but the vulnerabilities are still present.

## DoD

- [x] Handle the described situation properly
- [x] Add UT
- [x] CI Pass

**Comment by GabrielEValenzuela** [comment]
Re-open, comment in PR

**Comment by GabrielEValenzuela** [comment]
Segfault found, re open to fix it
