### ISSUE TITLE
Wazuh integration with fluentd?

### ISSUE THREAD

**Issue by c0r3dump3d** [wazuh/wazuh#2097]
## Feature request

**Compatibility**
_manager

**Component involved**
_Logcollector

Description
--------------
We have a fluentd installation with ELK stack and we would like to send our Wazuh events to this infrastructure, Is it possible to integrate Wazuh with fluentd? We have made some attempts but  without success.

Thank you.

**Comment by TJOSERAFAEL** [comment]
Hi @c0r3dump3d ,

yes it is possible to integrate it. You need to set up a socket configuration for **fluentd** on your manager. To do this edit the file **/var/ossec/etc/ossec.conf** and add the following block:
```xml
<socket>
  <name>fluentbit</name>
  <mode>udp</mode>
  <location>/var/run/fluent-bit.sock</location>
  <prefix>\<13\></prefix>
</socket>
```

Note that location is where your **fluentd** daemon creates the designated socket.

Now we need to tell logcollector to send the readed data the the fluentd socket, so edit the  **/var/ossec/etc/ossec.conf** file again on your manager:

```xml
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/syslog</location>
    <target>fluentbit</target>
  </localfile>
```

Now all our **syslog** events are send to the **fluentd** socket. Now it's up to your **fluentd** configuration to handle the output. If you need more information don't hesitate to ask.

Best regards.

**Comment by c0r3dump3d** [comment]
Thank you very much for the answer, we will test it.

**Comment by TJOSERAFAEL** [comment]
Hi @c0r3dump3d ,

we have integrated a new Wazuh module called `fluent-forward` that allows forwarding messages directly to a `fluentd` server.

The module reads the messages from a dedicated unix domain socket (which you can specify the path for) and forwards them to the `fluentd` server.

- A configuration minimal example:

```xml
 <fluent-forward>
      <enabled>yes</enabled>
      <socket_path>/var/run/fluent.sock</socket_path>
      <address>your-fluentd-address</address>
      <port>your-fluentd-port</port>
 </fluent-forward>
```

It will start reading from the socket located at `/var/run/fluent.sock` and forwarding the messages. 

- Another example using TLS:

```xml
<fluent_forward>
      <enabled>yes</enabled>
      <socket_path>/var/run/fluent.sock</socket_path>
      <address>your-fluentd-address</address>
      <port>your-fluentd-port</port>
      <shared_key>secret_string</shared_key>
      <ca_file>/root/certs/fluent.crt</ca_file>
      <user>foo</user>
      <password>bar</password>
</fluent_forward>
```

I'm going to close this issue. Feel free to reopen it again if you have to!

Best regards.

**Comment by c0r3dump3d** [comment]
Thank you very much !!! We will try.

**Comment by candlerb** [comment]
I am interested in the opposite configuration: getting fluentd stack to forward logs to wazuh for scanning.

ISTM this would require either:

* fluent protocol listener for wazuh
* UDP output for fluentd

It could also be possible to get fluentd to write to plain files, and wazuh to pick up from that.

**Comment by rverma-jm** [comment]
@candlerb did you ever find a solution for this? I see this ticket is closed but couldn't find any relevant docs

**Comment by candlerb** [comment]
No sorry.
