### ISSUE TITLE
Create GA pipeline for AWS integration tests

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#20975]
| Affected integration |
|---|
| AWS|

## Description

As part of epic https://github.com/wazuh/wazuh/issues/17788, GitHub Action pipeline for the launch of the AWS integration tests needs to be created to automatize future executions. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):

- [ ] Successful launch and execution of pipeline

**Comment by fdalmaup** [comment]
# Issue Update

- Created the `.github/workflows/integration-tests-aws-tier-0-1.yml` workflow file (branch `enhancement/20975-add-aws-it-ga-workflow`).
- Before testing the workflow, the #23419 needs to be merged in the epic branch, and the AWS ITs secrets need to be generated for the workflow to make use of it. Moving the issue to Blocked until then.

**Comment by fdalmaup** [comment]
# Issue Update

After reviewing the used `boto3` methods, the first set of minimum permissions that the test execution profile should have is:
- S3 related
    ```
        "s3:CreateBucket",
        "s3:DeleteBucket",
        "s3:PutObject",
        "s3:DeleteObject",
        "s3:ListBucket",
        "s3:GetObject",
        "s3:PutBucketNotification"
    ```
- EC2 related:
    ```
        "ec2:CreateVpc", 
        "ec2:CreateSubnet", 
        "ec2:DescribeAvailabilityZones",
        "ec2:CreateRouteTable", 
        "ec2:CreateRoute", 
        "ec2:AssociateRouteTable", 
        "ec2:ModifyVpcAttribute",
        "ec2:DeleteFlowLogs",
        "ec2:DeleteVpc",
        "ec2:DeleteRouteTable",
        "ec2:DeleteRoute",
        "ec2:CreateFlowLogs",
        "ec2:DescribeFlowLogs"
    ```

- CloudWatch related:
    ```
        "logs:GetLogEvents",
        "logs:PutLogEvents"
        "logs:CreateLogStream",
        "logs:DescribeLogStreams",
        "logs:CreateLogGroup",
        "logs:DeleteLogGroup",
        "logs:DeleteLogStream"
    ```

- SQS related:
    ```
        "sqs:ReceiveMessage",
        "sqs:CreateQueue",
        "sqs:DeleteMessage",
        "sqs:DeleteQueue",
        "sqs:SetQueueAttributes",
        "sqs:GetQueueAttributes",
        "sqs:GetQueueUrl"
    ```

- Inspector related:
    ```
        "inspector:ListFindings",
        "inspector:DescribeFindings"
    ```

**Comment by fdalmaup** [comment]
# Issue Update

- The changes to the workflow using the conditionals have been made, and the `README` file update with the permissions was carried out. Before opening the PR, the last step is testing the GitHub workflow with the generated credentials.
