### ISSUE TITLE
Failure to unzip the compiled Windows agent

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#20999]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2 | Builder | Winagent | Packages | - |

### Description

In the following PR checks, the Windows builder check failed, not allowing to build and install the Windows agent due to a failure to unzip the compiled Windows' agent package:
- PR: https://github.com/wazuh/wazuh/pull/20993/
  - Check: https://github.com/wazuh/wazuh/pull/20993/checks?check_run_id=19856995042
  - Jenkins job: https://ci.wazuh.info/job/Packages_builder_win/16328/console

The error seems to be caused by the merge changes in the following PR:
- https://github.com/wazuh/wazuh/pull/18567#top

#### Error
```
Error unzipping 'C:\tmp\Packages_builder_win_B16328_20231221112621\windows_agent_0.commit346120a.zip' to 'C:\tmp\Packages_builder_win_B16328_20231221112621\agent'!. Method: System.IO.Compression.ZipFile, Exception: Exception calling "ExtractToFile" with "3" argument(s): "Could not find a part of the path 'C:\tmp\Packages_builder_win_B16328_20231221112621\agent\wazuh-346120a997407150d07eb6d1f15845de5824cc6f\tests\integration\test_vulnerability_detector\test_vulnerability_inventory\data\configuration_templates\configuration_vulnerability_inventory_baseline_scan.yaml'."
```

It would be necessary to apply some changes to fix this problem and get the Windows agent builder working properly again.

**Comment by TomasTurina** [comment]
This should be fixed with https://github.com/wazuh/wazuh/pull/21011/commits/f0427426f189399c8267fd59610253277eb48b05
