### ISSUE TITLE
Add flatbuffer verifiers before accessing data from DBs

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21017]
## Description

The internals DBs used by the new vulnerability detector use flatbuffers. The access to the fields of these structures is fast but if the binary data is malformed, the offset would point to anywhere and there are high chances of a segmentation fault.

Even when it adds a small overhead, it's much safer to add verifiers after reading data from the DBs in case the data is corrupt.
Some examples of these lack of sanity checks are:
- `getVulnerabilitiesCandidates()` (src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp)
- `processEvent()` (src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/eventDecoder.hpp)

There could be some other places where the sanity check is required.

## DoD

- [x] Find all the places where a potentially corrupt flatbuffer could be read and generate a crash
- [x] Implement the verifications
- [x] Manual tests
- [x] Add UT
- [x] CI Pass

**Comment by Dwordcito** [comment]
Call verify everywhere.
