### ISSUE TITLE
Mismatch between `vendor` field in SUSE OS family and CVE `vendor` information

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21016]
### Description
In the SUSE OS family, the `vendor` field contains wrong information and is sent to the `vulnerability detection` system. This produces a mismatch between the `vendor` information sent by `syscollector` and the corresponding CVE `vendor` information. This inconsistency is causing issues in accurately identifying and assessing vulnerabilities.

### Expected Behavior
The `vendor` field in the SUSE OS family should align correctly with the CVE `vendor` information to ensure accurate vulnerability detection and assessment. For all SUSE OS family (OpenSuse, SUSE, etc) it should be `suse` the right value read by `syscollector`

#### Story 1: As a System Administrator
- **I want the `syscollector` to read the correct `vendor` information from the SUSE OS family.**
- **I want the `syscollector` to send the accurate `vendor` information to the `vulnerability detection` system.**

#### Story 2: As a Security Analyst
- **I want the `vulnerability detection` system to receive and process the correct `vendor` information from the SUSE OS family.**
- **I want the CVE information to match the `vendor` field for accurate vulnerability identification.**

### DoD

- [ ] Root Cause Analysis:
  - [ ] Identify where the wrong value is generated.
  - [ ] Understand the information, instruction, and error flow of the algorithm.

- [ ] Code Review:
  - [ ] Code has been reviewed by at least one team member.
  - [ ] All code review feedback has been addressed.

- [ ] Unit Testing & QA:
  - [ ] Unit tests have been written and cover relevant code paths.
  - [ ] All unit tests pass successfully.
  - [ ] All QA checks pass successfully.

**Comment by Dwordcito** [comment]
Modify https://github.com/wazuh/wazuh/blob/36365013e312da8c734dd575cd94e5ae11ff5c69/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp#L501 to make this comparison in lower case.
