### ISSUE TITLE
Investigate and fix a possible race condition when agentd fails to send a message

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#21014]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Agentd | Agent | Packages/Sources | All |

## Description

As part of https://github.com/wazuh/wazuh/issues/17596, it was identified that the manager receives (under uncertain conditions) messages whose reported size does not correspond to the bytes received. This can cause the received data to be misread, producing an unexpected error and closing the connection with that agent.

It is suspected that the agent may have a race condition that causes this. This is because when an agent sends a message to the manager, if that send fails, the manager may receive a partial message. In this situation, the agent closes the connection immediately; however, there is a possibility that a new message may be sent before this happens due to a race condition between two threads.

This issue aims to investigate whether this issue really exists and provide a solution to avoid this unexpected error.

**Comment by Nicogp** [comment]
I started the investigation, I was able to replicate the problem with dockerized agents.
After being able to replicate the error, I started debugging to try to find the cause of the issue.
So far I have not found the cause of the error.

**Comment by Nicogp** [comment]
I continued with the analysis.
I created a custom package and dockerized agents were raised to reproduce the problem, it was identified that the last events sent to the manager prior to disconnection correspond to sca. So the following tests were performed:

- Disabling the sca module: the error "Too big message" was not obtained.
- Decrease the sca scanning time: errors were obtained more frequently.

**Comment by Nicogp** [comment]
I continued with the analysis.
The newly added log message was used to compare with the message sent by the agent, here it was seen that the sent and received messages partially match.
Tests are still in progress.

**Comment by Nicogp** [comment]
I continued with the analysis.
Further tests were carried out and it was discovered that the problem may be in the following line:
https://github.com/wazuh/wazuh/blob/master/src/remoted/netbuffer.c#L113

After that memcpy "sockbuf->data" may be pointed to an erroneous value, this generates that in the next message the error "Too big message" is logged.

Tests are still in progress.

**Comment by Nicogp** [comment]
The cause of the problem was found, it is in the memcpy function, this function has an undefined behavior when the source object and the target object overlap:
`memcpy(sockbuf->data, sockbuf->data + i, sockbuf->data_len - i);`
https://github.com/wazuh/wazuh/blob/master/src/remoted/netbuffer.c#L113

https://pubs.opengroup.org/onlinepubs/7908799/xsh/memcpy.html

We switch to memmove instead of memcpy, since memmove does not have this problem:
https://cplusplus.com/reference/cstring/memmove

Tests were carried out with this change and the results were satisfactory, as the error did not reappear.

**Comment by Nicogp** [comment]
The proposed change was implemented. The PR was created and some UT cases are being added.
