### ISSUE TITLE
Release 4.7.2 - RC 1 - E2E UX tests - Windows events

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21044]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.2-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/binary-beasts team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Dec 27, 2023 and notify the @wazuh/binary-beasts team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/binary-beasts team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Dec 28, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 29, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Oracle Linux 8 x86_64 |
| Server | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Oracle Linux 8 x86_64 |
| Dashboard | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Oracle Linux 8 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-agent/index.html) | - | Windows Server 2022 x86_64, Windows 11 x86_64 |

## Test description

Test that Windows data collection works out of the box. 
Check that for the same Windows events, the alerts rule ID are the same as in previous version.
Test the following blog post:
https://wazuh.com/blog/emulation-of-attck-techniques-and-detection-with-wazuh/
Install sysmon and create Wazuh rules as mentioned, to ensure that everything works as intended in the blog post (use current release under test instead of 4.2.0)
Use the blogpost as a mere guide for testing some Windows events and the use cases, do not report issues with the blogpost itself, outdated commands, etc.

## Known issues

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/3925
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/3927
- https://github.com/wazuh/wazuh-documentation/issues/4986
- https://github.com/wazuh/wazuh/issues/12977
- https://github.com/wazuh/wazuh-documentation/issues/5672

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|   🟡  | Test: Quickstart installation |  Documentation  |  For not recommend systems need to use `-i` flag to ignore check. This is not completely clear in the documentation  |
| 🟢  |Test: Agent installation (Windows Server 2022 x86_64) | | |
| 🟢  |Test: Agent installation (Windows 11 x86_64) | | |
| 🟢  | Test: Attack emulation with ART|   |   |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - The test guideline was clear. There were no ambiguities 
- Did you face any challenges not covered by the guideline?
  - The testing guideline did not contain instruction on how to modify links to access the dev packages.
- Suggestions for improvement:
  - Include information on how to access dev packages

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/binary-beasts

**Comment by natcastillo** [comment]
# Wazuh central components installation

**Comment by natcastillo** [comment]
# Wazuh central components installation

<details> <summary> Quickstart installation   </summary>


```command


```



```command


```

</details>

<details> <summary> Verify installation   </summary> 

```command

```

</details>

<details> <summary>Manager verification   </summary> 

```command


```

</details>

<details> <summary> Dashboard  verification  </summary>




 </details>

**Comment by natcastillo** [comment]
## Agents installation 🟢 

<details> <summary> Windows server  2022 GUI 🟢  </summary>

- OS Information:



 </details>


<details> <summary> Windows 11 CMD 🟢  </summary> 

- OS information 



</details>

**Comment by natcastillo** [comment]
# Blogpost Testing 


<details> <summary> Windows 11  </summary> 

## Sysmon config 🟢

```cmd
sysmon.exe -accepteula -i sysmonconfig.xml


System Monitor v15.11 - System activity monitor
By Mark Russinovich and Thomas Garnier
Copyright (C) 2014-2023 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.60
Sysmon schema version: 4.90
Configuration file validated.
Sysmon installed.
SysmonDrv installed.
Starting SysmonDrv.
SysmonDrv started.
Starting Sysmon..
Sysmon started.
```

## Atomic Red Team installation

Using the command found in the blog the installation and the `ART` module import was successful.



</details>

**Comment by natcastillo** [comment]
# Blogpost Testing

<details>
<summary> Windows server 2022  </summary>

## Sysmon config 🟢

```powershell
PS C:\Users\vagrant\Downloads\Sysmon>sysmon.exe -accepteula -i sysmonconfig.xml


System Monitor v15.11 - System activity monitor
By Mark Russinovich and Thomas Garnier
Copyright (C) 2014-2023 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.
Sysinternals - www.sysinternals.com

Loading configuration file with schema version 4.60
Sysmon schema version: 4.90
Configuration file validated.
Sysmon installed.
SysmonDrv installed.
Starting SysmonDrv.
SysmonDrv started.
Starting Sysmon..
Sysmon started.
```

## Atomic Red Team installation 🟢

### ART Execution Framework and Atomics folder installation 🟢

```powershell
PS C:\Users\vagrant\Downloads\Sysmon> IEX (IWR 'https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1' -UseBasicParsing);
PS C:\Users\vagrant\Downloads\Sysmon> Install-AtomicRedTeam -getAtomics
Installation of Invoke-AtomicRedTeam is complete. You can now use the Invoke-AtomicTest function
See Wiki at https://github.com/redcanaryco/invoke-atomicredteam/wiki for complete details
```

### Importing the ART module 🟢

```powershell
PS C:\Users\vagrant\Downloads\Sysmon> Import-Module "C:\AtomicRedTeam\invoke-atomicredteam\Invoke-AtomicRedTeam.psd1" -Force
PS C:\Users\vagrant\Downloads\Sysmon> 
```

### Get details of a particular technique 🟢

```powershell
PS C:\Users\vagrant\Downloads\Sysmon> Invoke-AtomicTest T1548.002 -ShowDetailsBrief                                     PathToAtomicsFolder = C:\AtomicRedTeam\atomics
T1548.002-1 Bypass UAC using Event Viewer (cmd)
T1548.002-2 Bypass UAC using Event Viewer (PowerShell)
T1548.002-3 Bypass UAC using Fodhelper
T1548.002-4 Bypass UAC using Fodhelper - PowerShell
T1548.002-5 Bypass UAC using ComputerDefaults (PowerShell)
T1548.002-6 Bypass UAC by Mocking Trusted Directories
T1548.002-7 Bypass UAC using sdclt DelegateExecute
T1548.002-8 Disable UAC using reg.exe
T1548.002-9 Bypass UAC using SilentCleanup task
T1548.002-10 UACME Bypass Method 23
T1548.002-11 UACME Bypass Method 31
T1548.002-12 UACME Bypass Method 33
T1548.002-13 UACME Bypass Method 34
T1548.002-14 UACME Bypass Method 39
T1548.002-15 UACME Bypass Method 56
T1548.002-16 UACME Bypass Method 59
T1548.002-17 UACME Bypass Method 61
T1548.002-18 WinPwn - UAC Magic
T1548.002-19 WinPwn - UAC Bypass ccmstp technique
T1548.002-20 WinPwn - UAC Bypass DiskCleanup technique
T1548.002-21 WinPwn - UAC Bypass DccwBypassUAC technique
T1548.002-22 Disable UAC admin consent prompt via ConsentPromptBehaviorAdmin registry key
T1548.002-23 UAC Bypass with WSReset Registry Modification
T1548.002-24 Disable UAC - Switch to the secure desktop when prompting for elevation via registry key
```

### Check/Get prerequisites of a technique 🟢

<img width="847" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/50216f55-beee-4f94-ac5f-c39f6d65d404">
<img width="857" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/dcc59e90-9cb2-4778-94c4-4f81ad07f3e4">
<img width="851" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/74ceedfc-bdd9-4de3-aba4-b0a07c9271fd">

Some prerequisites were not met

<img width="854" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/f000640f-c625-4cec-9e71-89a03d33b1fa">
<img width="853" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/8732189e-6f90-43ff-ac4a-bed6f1eb9f1b">
<img width="852" alt="image" src="https://github.com/wazuh/wazuh/assets/73660701/2b0abecc-e7eb-43c4-ac4b-f41a8574b473">


### Run the test for a particular technique 🟢

```powershell
PS C:\Users\vagrant\Downloads\Sysmon> Invoke-AtomicTest T1548.002
PPathToAtomicsFolder = C:\AtomicRedTeam\atomics
EExecuting test: T1548.002-1 Bypass UAC using Event Viewer (cmd)
The operation completed successfully. 
```

### Clean-up on completion of the test 🟢

```shell
PS C:\Users\vagrant\Downloads\Sysmon> Invoke-AtomicTest T1548.002 -Cleanup                                            PPathToAtomicsFolder = C:\AtomicRedTeam\atomics                                                                                                                                                                                                Executing cleanup for test: T1548.002-1 Bypass UAC using Event Viewer (cmd)                                           DDone executing cleanup for test: T1548.002-1 Bypass UAC using Event Viewer (cmd)                                      EExecuting cleanup for test: T1548.002-2 Bypass UAC using Event Viewer (PowerShell)                                    DDone executing cleanup for test: T1548.002-2 Bypass UAC using Event Viewer (PowerShell)                               EExecuting cleanup for test: T1548.002-3 Bypass UAC using Fodhelper                                                    DDone executing cleanup for test: T1548.002-3 Bypass UAC using Fodhelper                                               EExecuting cleanup for test: T1548.002-4 Bypass UAC using Fodhelper - PowerShell                                       DDone executing cleanup for test: T1548.002-4 Bypass UAC using Fodhelper - PowerShell                                  EExecuting cleanup for test: T1548.002-5 Bypass UAC using ComputerDefaults (PowerShell)                                DDone executing cleanup for test: T1548.002-5 Bypass UAC using ComputerDefaults (PowerShell)                           EExecuting cleanup for test: T1548.002-6 Bypass UAC by Mocking Trusted Directories                                     DDone executing cleanup for test: T1548.002-6 Bypass UAC by Mocking Trusted Directories                                EExecuting cleanup for test: T1548.002-7 Bypass UAC using sdclt DelegateExecute                                        DDone executing cleanup for test: T1548.002-7 Bypass UAC using sdclt DelegateExecute                                   EExecuting cleanup for test: T1548.002-8 Disable UAC using reg.exe                                                     TThe operation completed successfully.                                                                                  Done executing cleanup for test: T1548.002-8 Disable UAC using reg.exe                                                EExecuting cleanup for test: T1548.002-9 Bypass UAC using SilentCleanup task                                           DDone executing cleanup for test: T1548.002-9 Bypass UAC using SilentCleanup task                                      EExecuting cleanup for test: T1548.002-10 UACME Bypass Method 23                                                       DDone executing cleanup for test: T1548.002-10 UACME Bypass Method 23                                                  EExecuting cleanup for test: T1548.002-11 UACME Bypass Method 31                                                        Done executing cleanup for test: T1548.002-11 UACME Bypass Method 31                                                  Executing cleanup for test: T1548.002-12 UACME Bypass Method 33                                                        Done executing cleanup for test: T1548.002-12 UACME Bypass Method 33                                                   Executing cleanup for test: T1548.002-13 UACME Bypass Method 34                                                        Done executing cleanup for test: T1548.002-13 UACME Bypass Method 34
Executing cleanup for test: T1548.002-14 UACME Bypass Method 39
Done executing cleanup for test: T1548.002-14 UACME Bypass Method 39
Executing cleanup for test: T1548.002-15 UACME Bypass Method 56
Done executing cleanup for test: T1548.002-15 UACME Bypass Method 56
Executing cleanup for test: T1548.002-16 UACME Bypass Method 59
Done executing cleanup for test: T1548.002-16 UACME Bypass Method 59
Executing cleanup for test: T1548.002-17 UACME Bypass Method 61
Done executing cleanup for test: T1548.002-17 UACME Bypass Method 61
Executing cleanup for test: T1548.002-18 WinPwn - UAC Magic
Done executing cleanup for test: T1548.002-18 WinPwn - UAC Magic
Executing cleanup for test: T1548.002-19 WinPwn - UAC Bypass ccmstp technique
Done executing cleanup for test: T1548.002-19 WinPwn - UAC Bypass ccmstp technique
Executing cleanup for test: T1548.002-20 WinPwn - UAC Bypass DiskCleanup technique
Done executing cleanup for test: T1548.002-20 WinPwn - UAC Bypass DiskCleanup technique
Executing cleanup for test: T1548.002-21 WinPwn - UAC Bypass DccwBypassUAC technique
Done executing cleanup for test: T1548.002-21 WinPwn - UAC Bypass DccwBypassUAC technique
Executing cleanup for test: T1548.002-22 Disable UAC admin consent prompt via ConsentPromptBehaviorAdmin registry key
Done executing cleanup for test: T1548.002-22 Disable UAC admin consent prompt via ConsentPromptBehaviorAdmin registry key
Executing cleanup for test: T1548.002-23 UAC Bypass with WSReset Registry Modification
Done executing cleanup for test: T1548.002-23 UAC Bypass with WSReset Registry Modification
Executing cleanup for test: T1548.002-24 Disable UAC - Switch to the secure desktop when prompting for elevation via registry key
Done executing cleanup for test: T1548.002-24 Disable UAC - Switch to the secure desktop when prompting for elevation via registry key
```

</details>

**Comment by damarisg** [comment]
LGTM!

Next time, add agent installation details. (steps)
