### ISSUE TITLE
Release 4.7.2 - RC 1 - E2E UX tests - RBAC

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21048]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.2-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Dec 27, 2023 and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/framework team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Dec 28, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 29, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Red Hat Enterprise Linux 8 |
| Server | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Red Hat Enterprise Linux 8 |
| Dashboard | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Red Hat Enterprise Linux 8 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-agent/index.html) | - | Red Hat Enterprise Linux 8 |

## Test description

Follow and complete the documentation steps and the examples, ensuring the access is adequate based on each requirement:

https://documentation-dev.wazuh.com/v4.7.2-rc1/user-manual/user-administration/rbac.html?highlight=RBAC

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      | **Comment Link** |
|----------------|-------------|---------------------|----------------|-------------------------|
| 🟢 | Wazuh indexer installation | NA | NA | [Initial Setup Status](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1869668975) |
| 🟢 | Wazuh server installation | NA | NA | [Initial Setup Status](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1869668975)  |
| 🟢 | Wazuh dashboard installation | NA | NA | [Initial Setup Status](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1869668975)  |
| 🟢 | Wazuh agent installation | NA | NA | [Initial Setup Status](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1869668975)  |
| 🟢 | Creating and setting a Wazuh admin user | NA | NA | [link]( https://github.com/wazuh/wazuh/issues/21048#issuecomment-1870306128) |
| 🟢 | Creating and setting a Wazuh read-only user | NA | NA | [link](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1870358405) | 
| 🟢 | Creating an internal user and mapping it to Wazuh | NA | NA | disregarded. works ok with specific cases |
| 🟢 | Use case: Give a user permissions to read and manage a group of agents | NA | NA | [link](https://github.com/wazuh/wazuh/issues/21048#issuecomment-1870394819) | 

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities? :red_circle: 
  - It  was not clear in the last use case. Grouping agents.
- Did you face any challenges not covered by the guideline? :red_circle: 
  - YES. The **Give a user permissions to read and manage a group of agents** use case does not give details on the method of creating groups and assigning agents to those groups. There is no clear definition. It can be done through the master's node via agent_group CLI or as a centralized config. It's not clear at all as a E2E guideline, although it's ok as a general open documentation.
- Suggestions for improvement:
  - Improve Deployment requirements
    - Add another extra agent node connecting to the cluster. So we can have one agent per group and later on test the group use case.
    - Add a new paragraph in the documentation at the beginning of **Give a user permissions to read and manage a group of agents**. Along with forwarding the user to the full doc, include simple instructions using the **agent_group** CLI in the master node to create groups and assign the agents to them. 
    - :red_circle: :warning:  Mandatory. Fix instructions [**Give a user permissions to read and manage a group of agents**](https://documentation-dev.wazuh.com/v4.7.2-rc1/user-manual/user-administration/rbac.html#use-case-give-a-user-permissions-to-read-and-manage-a-group-of-agents) at step 7, **Role Mapping** to highlight the need of adding the previously created role along with **cluster_readonly** role. That step is very easy to overlook; please improve the wording.
    - :warning: Step **Creating an internal user and mapping it to Wazuh** must be disregarded. Since it's a generic use case, useful in documentation, but does not apply to E2E tests. We have no clear expected results or conditions to compare. 
    - :warning: In general terms, we might have to add some notes to the **Test Description** stating disregarding of previous step or writing custom instructions where clear expected results can be proven with evidence.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/framework

**Comment by JorgeMarinoDev** [comment]
Work Log

1. Setting up environment WIP
2. Reference to previous test [4.6 RBAC](https://github.com/wazuh/wazuh/issues/19469)

**Comment by JorgeMarinoDev** [comment]
## Creating and setting a Wazuh admin user :green_circle: 


![image](https://github.com/wazuh/wazuh/assets/117848458/4466e8b3-d3f7-4c74-a95c-7e98b71d5d3d)

Created Duplicate role of all access

![image](https://github.com/wazuh/wazuh/assets/117848458/39c1c0bd-0db0-4fdb-a096-897826834d76)

Mapping role to internal user

![image](https://github.com/wazuh/wazuh/assets/117848458/e5ee76fd-849d-4579-b591-0809dda786b0)

Restarted Dashboard, enabled run_as, logged in as new user

![image](https://github.com/wazuh/wazuh/assets/117848458/174a883c-0014-49a3-816d-21bd1c0d98b3)

**Comment by JorgeMarinoDev** [comment]
## Creating and setting a Wazuh read-only user

Created internal user 
![image](https://github.com/wazuh/wazuh/assets/117848458/3a73a217-3e40-4a43-8c68-230ec36e1326)

Created Role
![image](https://github.com/wazuh/wazuh/assets/117848458/53535488-a00b-4df3-9193-c2f6f1a4af07)

Mapped Role to User
![image](https://github.com/wazuh/wazuh/assets/117848458/7b045474-ea26-4c44-be24-42e4cff8cf46)

Mapping it to Wazuh. Created Role
![image](https://github.com/wazuh/wazuh/assets/117848458/7e01bbe7-d716-4c38-b5e1-9f41e8d39bc9)

Assigned Map to internal user
![image](https://github.com/wazuh/wazuh/assets/117848458/44054dd6-c60b-4a2b-8b11-4f8d401aacfa)

Test Login with RO user
![image](https://github.com/wazuh/wazuh/assets/117848458/dc263e97-5de8-43f4-b97d-72ec8ee58f51)

Testing access restrictions
![image](https://github.com/wazuh/wazuh/assets/117848458/c1879ca3-f535-40d5-aaa8-c81783e74e97)

## Result 🟢

**Comment by JorgeMarinoDev** [comment]
## Use case: Give a user permissions to read and manage a group of agents

Added a new agent to the cluster
new Amazon Linux 2 Agent
![image](https://github.com/wazuh/wazuh/assets/117848458/4d3c3e1b-47eb-4296-8f82-3e940a9ef31d)

**Comment by fdalmaup** [comment]
# Review

Good work @JorgeMarinoDev. Please, feel free to open any issue that you consider necessary to enhance the documentation at [wazuh-documentation](https://github.com/wazuh/wazuh-documentation/issues/new). Afterward, please add it/them to this issue's description.

**Comment by JorgeMarinoDev** [comment]
Hello @fdalmaup Why is this on-hold? Is it something on our end? We did not find any release blockers btw. Just pending doc issues. Please review or clarify new state reasons.

**Comment by fdalmaup** [comment]
Hi @JorgeMarinoDev. Since it is mentioned that there are mandatory fixes to be made but no documentation issues have been created yet to carry them out as indicated in the issue's description ([check Reporting New Issues](https://github.com/wazuh/wazuh/issues/21048#issue-2054130320)), the issue is `On Hold` until these are created and added to the description to give another review.

**Comment by JorgeMarinoDev** [comment]
Regarding Improvements in documentation.
Created a new issue [here](https://github.com/wazuh/wazuh-documentation/issues/6893)

**Comment by fdalmaup** [comment]
LGTM

**Comment by Rebits** [comment]
LGTM
