### ISSUE TITLE
Release 4.7.2 - RC 1 - E2E UX tests - Amazon security lake

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21050]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.2-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Dec 27, 2023 and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/framework team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Dec 28, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 29, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-indexer/step-by-step.html) | Single node | Alma Linux 8 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-server/step-by-step.html) | Multi node | Alma Linux 8 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-dashboard/step-by-step.html) | - | Alma Linux 8 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.7.2-rc1/_images/deploy-new-agent-from-ui1.png) | - | Alma Linux 8 x86_64 |

## Test description

Configure AWS security lake in a Wazuh Manager and a Wazuh Agent. 
Ensure the events are correctly displayed on the dashboard.

Test the sample configuration provided in this documentation page:
https://documentation-dev.wazuh.com/v4.7.2-rc1/cloud-security/amazon/services/supported-services/security-lake.html#amazon-security-lake

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :green_circle: | Wazuh Server deployment step-by-step (Master) | - | - |
| :green_circle: | Wazuh Server deployment step-by-step (Worker) | - | - |
| :green_circle: | Wazuh Indexer deployment step-by-step | - | - |
| :green_circle: | Wazuh Dashboard deployment step-by-step | - | - |
| :green_circle: | Wazuh WUI one-liner deploy using IP (Agent) | - | - |
| :green_circle: | Configuring AWS Security Lake in Wazuh Manager | - | - |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - Testing guideline was clear and useful. Did not face any ambiguities.
- Did you face any challenges not covered by the guideline?
  - Guideline is clear, full of examples and well-structured. Did not find any challenge not explained in the guideline.
- Suggestions for improvement:
  - None.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/framework

**Comment by efahnle** [comment]
# Environment installation :green_circle: 

All components were installed following the `step-by-step` guides. 

| Component | OS Version | IP |
| --- | --- | --- | 
Wazuh manager master | Alma Linux 8.9 | 172.31.5.127
Wazuh manager worker | Alma Linux 8.9 | 172.31.4.208
Wazuh indexer | Alma Linux 8.9 | 172.31.11.78
Wazuh dashboard | Alma Linux 8.9 | 172.31.7.43
Agent | Alma Linux 8.9 | 172.31.6.57

## Wazuh Versions
### Managers
```console
[root@ip-172-31-5-127 ec2-user]# /var/ossec/bin/cluster_control -l
NAME     TYPE    VERSION  ADDRESS       
wazuh-1  master  4.7.2    172.31.5.127  
wazuh-2  worker  4.7.2    172.31.4.208 
```

### Indexer
```console
[ec2-user@ip-172-31-11-78 ~]$ sudo yum list installed | grep indexer
wazuh-indexer.x86_64               4.7.2-1                                           @wazuh 
```

### Dashboard
```console
[root@ip-172-31-7-43 ec2-user]# yum list installed | grep dashboard
wazuh-dashboard.x86_64             4.7.2-1                                           @wazuh 
```

### Agent
```console
[root@ip-172-31-6-57 ec2-user]# /var/ossec/bin/wazuh-control info -v
v4.7.2
```

## OS Versions
### Master
```console
[root@ip-172-31-5-127 ec2-user]# cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```
### Worker
```console
[ec2-user@ip-172-31-4-208 ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

### Indexer
```console
[ec2-user@ip-172-31-11-78 ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

### Dashboard
```console
[ec2-user@ip-172-31-7-43 ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

```


### Agent
```console
[ec2-user@ip-172-31-6-57 ~]$ cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.9 (Midnight Oncilla)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.9 (Midnight Oncilla)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

**Comment by efahnle** [comment]
# Configuring AWS Security Lake in Wazuh Manager :green_circle: 

Followed the [v4.7.2-rc1 dev documentation](https://documentation-dev.wazuh.com/v4.7.2-rc1/cloud-security/amazon/services/supported-services/security-lake.html), which was clear enough and didn't show any ambiguities.

1. CICD team provided access to security lake in [this issue](https://github.com/wazuh/internal-devel-requests/issues/624) and provided the following configuration:
```xml
    <subscriber type="security_lake">
        <sqs_name>AmazonSecurityLake-f38b8aff-fec5-****-Main-Queue</sqs_name>
        <iam_role_arn>arn:aws:iam::5679***:role/AmazonSecurityLake-f38b8aff-****</iam_role_arn>
        <iam_role_duration>1300</iam_role_duration>
        <external_id>wazuh-external-id</external_id>
    </subscriber>
```
2. Created `/root/.aws/credentials` file, following the [Configuring AWS Credentials](https://documentation-dev.wazuh.com/v4.7.2-rc1/cloud-security/amazon/services/prerequisites/credentials.html#amazon-credentials) guide and configured keys corresponding to the user provided by CICD:
```console
[root@ip-172-31-5-127 ec2-user]# cat /root/.aws/credentials 
[default]
region=us-east-1
aws_access_key_id=AKIA***
aws_secret_access_key=G6YQ***
```
3. Included the config provided by CICD mentioned in step 1 in a bigger Security Lake section, and placed it in `ossec.conf`, as stated in [the docs](https://documentation-dev.wazuh.com/v4.7.2-rc1/cloud-security/amazon/services/supported-services/security-lake.html#wazuh-configuration)
```xml
<ossec_config>
...
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <subscriber type="security_lake">
        <sqs_name>AmazonSecurityLake-f38b8aff-fec5-****-Main-Queue</sqs_name>
        <iam_role_arn>arn:aws:iam::5679***:role/AmazonSecurityLake-f38b8aff-****</iam_role_arn>
        <iam_role_duration>1300</iam_role_duration>
        <external_id>wazuh-external-id</external_id>
    </subscriber>
  </wodle>
...
</ossec_config>
```
4. Restarted the service
```console
systemctl restart wazuh-manager
```
5. Checked `/var/ossec/logs/ossec.log` for details
```console
[root@ip-172-31-5-127 ec2-user]# tail -f /var/ossec/logs/ossec.log 
2023/12/27 13:57:15 sca: INFO: Starting Security Configuration Assessment scan.
2023/12/27 13:57:15 wazuh-modulesd:aws-s3: INFO: Module AWS started
2023/12/27 13:57:15 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2023/12/27 13:57:15 wazuh-modulesd:aws-s3: INFO: Executing Subscriber fetch: (Type and SQS: security_lake AmazonSecurityLake-f38b8aff-fec5-4705-a05a-3d62abdfc439-Main-Queue)
2023/12/27 13:57:15 wazuh-modulesd:control: INFO: Starting control thread.

```
6. Security Lake integration is working and events show up in dashboard
![Screenshot from 2023-12-27 11-14-26](https://github.com/wazuh/wazuh/assets/31556780/14fa0f82-4480-4688-a04f-299bbfa80017)
![Screenshot from 2023-12-27 11-14-45](https://github.com/wazuh/wazuh/assets/31556780/6502cdb9-d0c8-43e7-8f36-74c5660f9f45)
![Screenshot from 2023-12-27 11-15-17](https://github.com/wazuh/wazuh/assets/31556780/6c951fdd-bc02-48fa-a0e9-cba5eb1f3788)

**Comment by fdalmaup** [comment]
LGTM!

**Comment by damarisg** [comment]
Next time, add each installation step. 

Regards.
