### ISSUE TITLE
Change of modulesd pattern in disk_read plot in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21096]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rc1 | Wazuh component | Manager | Packages | CentOS |

Testing [Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/21080)

It was possible to see in the manager's plot changes in the pattern of modulesd (It is not gradually increasing), it is stable around 0.6 while in 4.7.1-rc2 it increased up to 1.75

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21080
![image](https://github.com/wazuh/wazuh/assets/125690423/b974883b-25fe-40a4-94a8-54a0c6455b52)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20839
![image](https://github.com/wazuh/wazuh/assets/125690423/2e4d9357-876d-41c1-955b-1a1abb4aefbd)

4.7.1-rc1 https://github.com/wazuh/wazuh/issues/20562
![image](https://github.com/wazuh/wazuh/assets/125690423/529b4892-9a44-40a2-ac35-1143509effda)

Further research should be done.

**Comment by pro-akim** [comment]
## Update
Similar pattern was found in https://github.com/wazuh/wazuh/issues/21070

**Comment by nbertoldo** [comment]
### Conclusion
After researching, we can see in the logs that the steps that appear in the disk_read graph of the previous tests (4.7.1 - RC1 and 4.7.1 - RC2) occurs when the Vulnerability Detector module downloads new information from the 'National Vulnerability Database' feed. The module tries to update every hour but as we can see in the logs, there is not always new information to download, so the update ends instantly.
```
2023/12/12 00:51:15 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2023/12/12 00:51:15 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
2023/12/12 01:51:16 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2023/12/12 01:51:16 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
2023/12/12 02:51:17 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2023/12/12 02:51:17 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
```
Instead, when there is new information to download, the update process takes longer and matches the steps in the disk read (and write) graph.
```
2023/12/12 15:51:53 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
2023/12/12 15:55:54 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
```
![disk_read](https://github.com/wazuh/wazuh/assets/117279646/5f3b480f-c785-4bf4-9dd9-f0fe57f68a03)
![disk_written](https://github.com/wazuh/wazuh/assets/117279646/69edf3ea-9177-4546-b383-76cef13de793)
This is part of the normal operation of the module.

**Comment by cborla** [comment]
LGTM!
