### ISSUE TITLE
Release 4.7.2 - RC 1 - Integration tests 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#21099]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/21052|
| **Version**                      | 4.7.2                                                   |
| **Release stage**            | Release Candidate 1                                                      |
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.7.2-rc1          |
| **Wazuh QA: Branch**    | `v4.7.2-rc1`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.7.2-rc1      |
| **Wazuh: Branch**    | `v4.7.2-rc1` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows` , `Solaris`, `macOS` will be used as required.

## Results of the integration tests

- Build: https://ci.wazuh.info/job/Test_integration_launcher/242/

  Re-Launch failures:
  - Active Response- Windows: https://ci.wazuh.info/job/Test_integration/45644/
  - Active Response - CentOS: https://ci.wazuh.info/job/Test_integration/45645/
  - FIM - MacOS, Solaris: https://ci.wazuh.info/job/Test_integration/45646/
  
  
## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45620/manager_html_report_Test_integration_B45620.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://ci.wazuh.info/job/Test_integration/45645/artifact/agent_centos_html_report_Test_integration_B45645_20231226192936.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://ci.wazuh.info/job/Test_integration/45644/artifact/agent_windows_html_report_Test_integration_B45644_20231226192233.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45622/agent_centos_html_report_Test_integration_B45622.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45622/agent_windows_html_report_Test_integration_B45622.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>analysisd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45623/manager_html_report_Test_integration_B45623.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>api</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45624/manager_html_report_Test_integration_B45624.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45625/manager_html_report_Test_integration_B45625.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45626/agent_centos_html_report_Test_integration_B45626.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45626/agent_windows_html_report_Test_integration_B45626.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45627/manager_html_report_Test_integration_B45627.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45628/agent_centos_html_report_Test_integration_B45628.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45628/agent_windows_html_report_Test_integration_B45628.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://ci.wazuh.info/job/Test_integration/45646/artifact/agent_macos_html_report_Test_integration_B45646_20231226193453.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://ci.wazuh.info/job/Test_integration/45646/artifact/agent_solaris_html_report_Test_integration_B45646_20231226193453.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45630/manager_html_report_Test_integration_B45630.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45631/manager_html_report_Test_integration_B45631.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45632/agent_centos_html_report_Test_integration_B45632.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45633/manager_html_report_Test_integration_B45633.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45634/agent_centos_html_report_Test_integration_B45634.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45634/agent_windows_html_report_Test_integration_B45634.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45634/agent_macos_html_report_Test_integration_B45634.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45634/agent_solaris_html_report_Test_integration_B45634.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45635/manager_html_report_Test_integration_B45635.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45636/manager_html_report_Test_integration_B45636.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45637/agent_centos_html_report_Test_integration_B45637.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45638/manager_html_report_Test_integration_B45638.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45639/manager_html_report_Test_integration_B45639.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rootcheck</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45640/manager_html_report_Test_integration_B45640.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>vulnerability_detector</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45641/manager_html_report_Test_integration_B45641.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45642/manager_html_report_Test_integration_B45642.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45643/manager_html_report_Test_integration_B45643.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45619/agent_centos_html_report_Test_integration_B45619.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45619/agent_windows_html_report_Test_integration_B45619.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45619/agent_macos_html_report_Test_integration_B45619.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

-----

## Conclusion 🟢 

Everything works as expected. There are no new errors.

### Known issues
- https://github.com/wazuh/wazuh-qa/issues/4429
- https://github.com/wazuh/wazuh-qa/issues/4230

**Comment by QU3B1M** [comment]
LGTM!
