### ISSUE TITLE
local installation

### ISSUE THREAD

**Issue by knzudgt** [wazuh/wazuh#211]
I just discovered the wazuh project while reading documentation on OSSEC.
My intention was to install OSSEC from source because I would need OSSEC on a stand alone web server in a Ubuntu 16.04 (xenial) machine, and there are deb packages only for server and agent, while installing from source I can choose to make a `local` installation, for monitoring the server that OSSEC is installed on.

Does wazuh have Ubuntu packages for a corresponding `local` installation (server/agent)?

**Comment by erseco** [comment]
Hello, we don't have yet `wazuh-local` packages for Ubuntu, but any manager can work as local editing the `/var/ossec/etc/ossec.conf` file.

You only need to remove `<auth>...</auth>` and `<remote>...</remote>` sections from this file and restart the manager.

Best regards!
