### ISSUE TITLE
Relevant changes in the disk use of stress test ALL-EXCEPT-VULNERABILITY-DETECTOR

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21109]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rc1 | Wazuh component | Manager & Agent | Packages | Windows and Manager  |

Testing [Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21078)

Changes in the use of disk pattern could be found in comparison to 4.7.1-rc2

Manager

Disk: Relevant changes of modulesd, wazuhdb, clusterd pattern and use
Disk_written: increase of analysis

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21078
![image](https://github.com/wazuh/wazuh/assets/125690423/73e803cd-d292-4267-acc6-a46495ce5a95)
![image](https://github.com/wazuh/wazuh/assets/125690423/fe0e492d-79ea-4e77-8322-b640d5dba7fd)
4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20843
![image](https://github.com/wazuh/wazuh/assets/125690423/67abdb94-07ab-4836-bb38-e29ff9129fe2)
![image](https://github.com/wazuh/wazuh/assets/125690423/3024452a-1899-449c-9bcd-9b14f7c6f97f)

Windows

Disk: Relevant decrease of agent.exe

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21078
![image](https://github.com/wazuh/wazuh/assets/125690423/c6f2f88b-7b20-4ea3-85db-5ceb3352a8c9)
4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20843
![image](https://github.com/wazuh/wazuh/assets/125690423/6e41eda3-beeb-42dc-bbe5-200e8258782e)

Further research is required

**Comment by cborla** [comment]
Related to https://github.com/wazuh/wazuh/issues/21110#issuecomment-1871262546
