### ISSUE TITLE
Relevant changes in disk use of different nodes in LOGCOLLECTOR and DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP  stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21105]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-r1 | Wazuh component | Manager and Agent | Packages | CentOS manager, Ubuntu Agent |

Testing [Footprint Metrics - LOGCOLLECTOR (2.5d) (2.5d)](https://github.com/wazuh/wazuh/issues/21079)

It was possible to see in the manager and ubuntu plot, changes of use of Disk. (increases around 100% and decreases around 50%)

Manager
4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21079
![image](https://github.com/wazuh/wazuh/assets/125690423/588e7159-3d2b-4d0b-9f56-d3ded3e4067f)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20828
![image](https://github.com/wazuh/wazuh/assets/125690423/bc81ece9-088a-4b55-85cb-f3f0ffe0a1aa)

Ubuntu

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21079
![image](https://github.com/wazuh/wazuh/assets/125690423/617f0225-1b70-4963-81fd-5c74f595bedd)
 

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20828
![image](https://github.com/wazuh/wazuh/assets/125690423/2dba2882-0027-4d55-b847-0c124ce0214a)

On the other hand:

Testing [DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/21075)

Manager

Disk: relevant increase of use of analysisd (around 10 times) and wazuhdb

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21075
![image](https://github.com/wazuh/wazuh/assets/125690423/f67d534f-9fbc-4f5a-b98e-8a7d7d854a96)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20837
![image](https://github.com/wazuh/wazuh/assets/125690423/1a7cd6bf-b1b6-42a0-96c1-53a4ba9857a2)

Ubuntu

Disk: relevant decrease of agentd (50% of decrement)

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21075
![image](https://github.com/wazuh/wazuh/assets/125690423/bdeb615d-e749-4fc3-ae71-144ed1d3f604)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20837
![image](https://github.com/wazuh/wazuh/assets/125690423/afa494f0-5677-4880-99d5-634b3bd9fb00)

Further research should be done

**Comment by Rebits** [comment]
As elucidated by @JorgeMarinoDev in https://github.com/wazuh/wazuh-jenkins/issues/5656, it has been pointed out that the Disk Usage Metrics in the Footprint tests lack accuracy. Therefore, it is advisable to perform a comparison of both Read/Write (R/W) operations and the Disk Usage metric for a comprehensive analysis.

Upon scrutiny, no significant changes were observed in these metrics. However, there was a slight increase noted in the disk read operations of the agentd.

|Metric | 4.7.2| 4.8.0  |
| ---| ---| --- | 
| Read Ops| ![IMAGE](https://camo.githubusercontent.com/ee14a1b235a8513d323c411ca6f7fc9a2115b3ce5fe598b37cda1405157f2a63/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343731362d333630306d2f42343731365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343731365f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |   ![IMAGE](https://camo.githubusercontent.com/6a1cdd862ce61cb1f9a52a4de9c8a24788f01b6fc9634b7c7b33ca467ad42048/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343638382d333630306d2f42343638385f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343638385f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | 
| Write Ops|![IMAGE](https://camo.githubusercontent.com/34397c84a7a59aa32365e4f1e1443136759f265f8350d21ea7e0b67a9ede5419/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343731362d333630306d2f42343731365f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343731365f7562756e74752d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)| ![IMAGE](https://camo.githubusercontent.com/e9cc1f7d060fcde6d8f73b77649a129add2dc50fb877bdaf647d497307aae0a1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343638382d333630306d2f42343638385f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343638385f7562756e74752d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |

**Comment by JorgeMarinoDev** [comment]
Totally agree with @Rebits , Disk % metrics are not reliable.
Nevertheless, as part of Footprint Analysis, we checked actual CSV Values on the Manager.

* Manager I/O Bytes Comparisson (Y Values in Log10 Scale)
![image](https://github.com/wazuh/wazuh/assets/117848458/b9416d30-1233-49d9-aa21-66342ceb0fdf)

**Result** :green_circle: No big differences were found. Disregard in Manager.

**Comment by JorgeMarinoDev** [comment]
## Conclusion :green_circle: 

Although plots of Disk Usage % reveal anomalies, we did not find any accumulative metric of I/O Bytes related to a possible issue. 
Please Disregard. Everything is working under normal conditions.

**Comment by cborla** [comment]
LGTM!

**Comment by TomasTurina** [comment]
Closing since it doesn't seem to be a problem!
