### ISSUE TITLE
Engine - Research and Enhance Suricata Integration Coverage for ECS Compliance

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#21114]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description

The objective of this issue is to conduct a thorough analysis of the current Suricata integration decoders within Wazuh to ensure comprehensive field extraction in alignment with the Elastic Common Schema (ECS). Additionally, we aim to identify and document any significant fields that are not currently represented within ECS but are deemed valuable for security analysis and incident response.

### Objectives

- Evaluate the existing Suricata integration decoders to determine ECS compliance.
- Identify all fields extracted by the decoders and map them to their corresponding ECS fields.
- List any important fields that are currently not part of ECS and provide a rationale for their inclusion.

**Comment by NahuFigueroa97** [comment]
Update:

- Enhancement suricata default and suricata alert decoder
- Add examples

**Comment by NahuFigueroa97** [comment]
Update:

- Add mapping for TLS and DNS

**Comment by NahuFigueroa97** [comment]
Update:

- Unify TLS, DNS and Alert in a only decoder
- Add test cases for Alert, Dns, Metadata etc
- Add helper for map number to string

**Comment by NahuFigueroa97** [comment]
Update:

- PR Review with team
- Corrections

**Comment by NahuFigueroa97** [comment]
Update:

- Completing all the missing cases in the decoder form
- Investigating the implementation of a library to extract the top level domain from a url
- Try to map fields in the root path

**Comment by NahuFigueroa97** [comment]
Update:

- Add corrections requested in decoder
