### ISSUE TITLE
Relevant increase of use of resources in DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21116]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-r1 | Wazuh component | Agent | Packages | CentOS  Agent |

Testing [DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP (2.5d)](https://github.com/wazuh/wazuh/issues/21075)

It is possible to see in RSS, USS, PPS arelevant increase of modulesd

CentOS Agent
4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21075
![image](https://github.com/wazuh/wazuh/assets/125690423/cf15d0a5-5296-41f8-8657-715bb9cfed52)
![image](https://github.com/wazuh/wazuh/assets/125690423/b27dee9b-c4e6-417c-90fa-e9b1a1e8ba79)
![image](https://github.com/wazuh/wazuh/assets/125690423/963beba7-4c67-4599-a2b6-45edf2db5343)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20837
![image](https://github.com/wazuh/wazuh/assets/125690423/e3cb82c1-5019-49c5-9b69-6f5707b98b96)
![image](https://github.com/wazuh/wazuh/assets/125690423/538515d6-4b3a-4df0-8955-a1036184b627)
![image](https://github.com/wazuh/wazuh/assets/125690423/45332ac5-8567-4f1c-8f9a-5862b2649432)

Further research should be done

**Comment by nbertoldo** [comment]
The reports have been analysed, and although there is a clear increase in the use of `modulesd` resources, the values remain (since the beginning of the test) within a reasonable range of values and there are no anomalies in the operation of the module. Neither have there been any changes between versions that could cause these differences. Therefore, it is assumed that this is a circumstantial behaviour that does not affect the agent's performance.

**Comment by nbertoldo** [comment]
## Analysis
The report was further analysed and the reason for this increase was not detected. We can highlight the following points:
- Graphs of earlier and later versions (4.8.0) were analysed and no such increases were detected.
- Other tests of the same version were analysed in which this behaviour is not found, although they include the same modules and other extra modules. [PSS - Centos Agent - Test ALL](https://camo.githubusercontent.com/7ac6a4b7cd483fa65d6b6033bafe15bb6c4fb29c9ee5522d60952c4352919473/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732372d333630306d2f42343732375f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732375f63656e746f732d7072652d72656c656173655f5053532e706e67)
- The memory allocation is given before starting the test, so we understand that it is the allocation of resources that the operating system has given to the processes.
- There is no indiscriminate increase in memory at any time during the test, but the values are proportional to the ones in other tests.
- 
## Conclusion
Considering the above points and the following [comment](https://github.com/wazuh/wazuh/issues/20861#issuecomment-1863971904), we can assume that there is nothing that could affect the product in this report.
