### ISSUE TITLE
Changes in modulesd's fluctuations of PSS, RSS, USS in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21111]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rc1 | Wazuh component | Manager  | Packages | Manager  |

Testing [Footprint Metrics - ALL-EXCEPT-VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21078)

Changes in modulesd's fluctuations of PSS, RSS, USS could be found in comparison to 4.7.1-rc2

Manager

PSS, RSS, USS: changes in the fluctation pattern of modulesd

4.7.2-rc1 https://github.com/wazuh/wazuh/issues/21078
![image](https://github.com/wazuh/wazuh/assets/125690423/909a5c55-cdba-4fda-b30b-54855ae61086)
![image](https://github.com/wazuh/wazuh/assets/125690423/07d92338-5079-4ae5-bb87-dd47925684ee)
![image](https://github.com/wazuh/wazuh/assets/125690423/86387f78-097f-4627-80dc-a6ab64351e3b)

4.7.1-rc2 https://github.com/wazuh/wazuh/issues/20843
![image](https://github.com/wazuh/wazuh/assets/125690423/3c7b7bfd-ba95-4f98-ab39-6caf90d28b51)
![image](https://github.com/wazuh/wazuh/assets/125690423/37322164-5832-49b0-a794-429b9c9dd0b8)
![image](https://github.com/wazuh/wazuh/assets/125690423/60e21684-1be8-4c32-9805-6aaf5ecf1607)

Further research is required

**Comment by cborla** [comment]
Related to https://github.com/wazuh/wazuh/issues/21110#issuecomment-1871262546
