### ISSUE TITLE
Increment of Values in the `Disk_Writen` Graph

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#21125]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.7.2-rc1 |  Manager | Packages | -  |

The values of `wazuh-modulesd` are considerably higher than in previous graphs.

> Testing: https://github.com/wazuh/wazuh/issues/21067

<details>
   <summary>4.7.2 - RC 1</summary>
   <br/>

![image](https://github.com/wazuh/wazuh/assets/54536265/4b9a462c-57cc-4ea9-88e4-36fc8e0c2c6f)

</details>

<details>
   <summary>4.7.1 - RC 2</summary>
   <br/>

![image](https://github.com/wazuh/wazuh/assets/54536265/935786a2-201f-47ac-acf0-072c09fd944d)

</details>

<details>
   <summary>4.7.0 - RC 1</summary>
   <br/>

![image](https://github.com/wazuh/wazuh/assets/54536265/0f764b57-87cd-496d-aa64-ff3d7c69e0d2)

</details>

**Comment by Rebits** [comment]
This increase has also been detected in https://github.com/wazuh/wazuh/issues/21065 for centOS agent:

| Metric |4.7.2 | 4.7.1| 
| --- | ---- | ---- |
| Disk Read | ![image](https://camo.githubusercontent.com/e80370fae6ed6f34f69ad5f9e790f2a57b6de0976e5180ffc214b5b73b16337b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732342d333630306d2f42343732345f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732345f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) | ![image](https://camo.githubusercontent.com/9a7e88e1b3a34db8a260b4c48aa523054f08ea0782bca8b8df65b55a6a2d76c1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343639362d333630306d2f42343639365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343639365f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) |
| Disk Written | ![image](https://camo.githubusercontent.com/7b7edd9759fd5151e69e46be091b2e2c361408d83175d7461075fdafc38c2892/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732342d333630306d2f42343732345f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732345f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |  ![image](https://camo.githubusercontent.com/8743165b28403fb4eb19e8cf96303be4ba5d5c9ce948bf847d2decbd4ae65111/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343639362d333630306d2f42343639365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343639365f63656e746f732d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)

**Comment by JorgeMarinoDev** [comment]
Analysis of the following stress tests:

1. [Build #4730 [pre-release][4.7.2-rc1][ALL-EXCEPT-ROOTCHECK][2.5d]](https://ci.wazuh.info/job/Test_stress/4730/)
2. [Build #4702 [pre-release][4.7.1-rc2][ALL-EXCEPT-ROOTCHECK][2.5d]](https://ci.wazuh.info/job/Test_stress/4702/)
3. [Build #4681 [pre-release][4.8.0-alpha1][ALL-EXCEPT-ROOTCHECK][2.5d]](https://ci.wazuh.info/job/Test_stress/4681/)

![image](https://github.com/wazuh/wazuh/assets/117848458/718e5680-8fb7-4690-895e-0a1b3b48ff63)

* Running parameters are the same

**Comment by JorgeMarinoDev** [comment]
Update checking [ChangeLog](https://github.com/wazuh/wazuh/compare/v4.7.1...v4.7.2-rc1) no detected relevant commits so far.

**Comment by cborla** [comment]
### Analysis
Comparing version 4.7.2 with version 4.7.0, the difference is about 30 GB between these two versions.

| Graph |4.7.2 | 4.7.0| 
| --- | ---- | ---- |
| Disk Written | ![image](https://private-user-images.githubusercontent.com/54536265/293027032-4b9a462c-57cc-4ea9-88e4-36fc8e0c2c6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTA1NzAsIm5iZiI6MTcwNDI5MDI3MCwicGF0aCI6Ii81NDUzNjI2NS8yOTMwMjcwMzItNGI5YTQ2MmMtNTdjYy00ZWE5LTg4ZTQtMzZmYzhlMGMyYzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDEzNTc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0M2U2MTdhZjM3NDM1YTY3ZGJlMjI0NzcxMTU0NTNmMTdmMGY3NWI4ZTllMTY1Zjg3NGU4ZGRjMTE0MGJiZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.txQlCTnY5uB8rcPMiIQeD4-suB9-Yyf9nXWDJCQeudI) |  ![image](https://camo.githubusercontent.com/c3107fbb7d3029ddd0896499df6307d0ebc43b753effdae750ce7ede64d4d21a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e302f42343539312d333630306d2f42343539315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343539315f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |

| Version | Disk Writeen (GB)|
|---|---|
|4.7.0| 80 |
|4.7.2| 110 |

It can be interpreted as an expected increase in line with changes in the SCA rules. [Similar case for 4.8.0](https://github.com/wazuh/wazuh/issues/20874#issuecomment-1866790436) (where SCA changes are also included).

### Conclusion

- The increase between 4.7.2 and 4.7.0 can be associated with changes in SCA.
- The difference observed between 4.7.2 and 4.7.1 RC2 is not correct, the issue of that [test was closed as unplanned](https://github.com/wazuh/wazuh/issues/20838), I think the comparison is not valid.
- The graphs are similar, no possible memory leaks or errors are seen.

**Comment by JorgeMarinoDev** [comment]
An interesting fact was found actually after digging deeper into logs.
4.7.2 shows a remarkable increase of VD logs regarding DB updates.

i.e.
`2023/11/16 20:33:46 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux 7' database update.`

* Configuration is the same for both tested scenarios.
[vd_section_ossec.zip](https://github.com/wazuh/wazuh/files/13824855/vd_section_ossec.zip)

| Version | DB Update Logs |
| ------- | -------------- |
| 4.7.0   | 10.182         |
| 4.7.2   | 26.909         |

This is probably the most related change to disk increase. Almost 3x more DB updates.

**Comment by Dwordcito** [comment]
@cborla @JorgeMarinoDev please create an issue to fix this invalid behavior.

**Comment by Dwordcito** [comment]
@MarcelKemp take a look on this issue please.

**Comment by cborla** [comment]
## Analysis

- The feeds are being scanned every minute, which by the `update_interval` would be correct.
- National Vulnerability Database
  - 4.7.2 - On the 23rd day it has 667 update appearances, which although it appears many times, theoretically it is correct.
  - In 4.7.0 and 4.7.1, this occurrence is normally ~200 occurrences.

Above difference is because in these two cases 4.7.0 and 4.7.1, there was a problem with the synchronization of Syscollector: [16640](https://github.com/wazuh/wazuh/issues/16640). The error message in 4.7.0 and 4.7.1 is `WARNING: (5515): Agent '00X' software could not be requested`.
This caused that when trying to scan the agents, a timeout was added and I understand that for this reason there are many less appearances. The case of 4.7.2 is correct. 
Which justifies the increase in disk writes.

**Comment by Dwordcito** [comment]
LGTM
