### ISSUE TITLE
Increase of modulesd pattern in the disk plot for the ALL_EXCEPT_SYSCHECK stress test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#21124]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rc1 | Wazuh component |Agent | Packages | Ubuntu |

Testing [Release 4.7.2 - RC 1 - Footprint Metrics - ALL-EXCEPT-SYSCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/21071#top)

Changes in the use of disk pattern could be found in comparison to 4.7.1-rc2.

Ubuntu:
Disk: relevant increase of modulesd.

4.7.2-rc1 #21071
![2023-12-27_11-35](https://github.com/wazuh/wazuh/assets/101177239/f97e898b-d86d-4ef8-a771-f778d84c5c77)

4.7.1-rc2 #20825
![2023-12-27_11-38](https://github.com/wazuh/wazuh/assets/101177239/35da4905-5a86-4221-9611-8ff289ad9384)

When examining past versions, the behavior is as follows:

4.7.1-rc1 #20551
![2023-12-27_11-40](https://github.com/wazuh/wazuh/assets/101177239/804ad636-1135-4982-90df-ada92f5f7394)

4.7.0-rc1 #20303
![2023-12-27_11-41](https://github.com/wazuh/wazuh/assets/101177239/18b11835-b589-47a1-beff-5fe443ffde8b)

Further research is required

**Comment by nbertoldo** [comment]
As explained in https://github.com/wazuh/wazuh-jenkins/issues/5656, the Disk Usage Metrics in the Footprint tests are not accurate. Therefore, the operations and number of bytes read/written to disk are analysed. 

<google-sheets-html-origin>
Version | Read_Ops | Write_Ops | Disk_Read(B) | Disk_Written(B)
-- | -- | -- | -- | --
4.7.1 - RC2 | 45919036 | 3025135 | 307916800 | 8665022464
4.7.2 - RC1 | 46820484 | 3102060 | 270172160 | 8885227520

No significant increases detected.

**Comment by TomasTurina** [comment]
Closing since it doesn't seem to be a problem!
