### ISSUE TITLE
Adding Transactional Content Publication Capability to RocksDB Wrapper

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#21137]
|Component|
|---|
| [utils](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/shared_modules/utils) |

## Description:

**Context:**
In certain scenarios, it is crucial that writing to a database occurs transactionally to prevent the publication of content in the event of errors during information processing.

**Problem:**
Currently, the capability to perform transactional writes in RocksDB is not implemented in the corresponding wrapper.

## Expected
Enhance the [RocksDB Wrapper](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/shared_modules/utils/rocksDBWrapper.hpp) to support transactional writes during content publication, ensuring database integrity in the face of potential errors.

**Proposed Changes:**

1. **Implementation of Transactional Writes:**
   - Improve the RocksDB wrapper to enable transactional writing of content to the database.
   - Ensure that, in the event of errors during processing, the transaction is aborted, preventing the publication of incomplete or incorrect content.

**Use Cases:**

1. **Successful Processing:**
   - The transaction is initiated before writing content to the database.
   - Processing succeeds, and the transaction is committed, allowing the publication of content.

2. **Error during Processing:**
   - A transaction is initiated before writing content to the database.
   - If an error occurs during processing, the transaction is rolled back, preventing the publication of incorrect or incomplete content.

## DoD

- [ ] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [ ] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

**Comment by Dwordcito** [comment]
This issue will be done in: https://github.com/wazuh/wazuh/issues/21134
