### ISSUE TITLE
Bump aiohttp version in Framework requirements file

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#21151]
|Wazuh version|Component|
|---|---|
| 4.8.0 | Wazuh embedded Python interpreter |

## Description
In #20586, the team upgraded the `aiohttp` dependency version from `3.8.1` to `3.9.1`. For the `4.8.0` Wazuh version, said dependency was previously updated to `3.8.5` but it is needed to bump it in the `framework/requirements.txt` file to the latest available since the packages have already been updated in #20857.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Bumped the `aiohttp` dependency version and installed Wazuh from sources to verify that it works as expected.
