### ISSUE TITLE
Investigate about AWS Security Hub

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#21165]
# Description

As part of the [AWS Security Hub integration epic](https://github.com/wazuh/wazuh/issues/21209), it is necessary to carry out exhaustive research related to the [service](https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html) before initiating efforts to support it. The result of the investigation should be clear enough to establish what a basic configuration would be like in the AWS Console according to the requirements presented.

## Key features to research
- How to [enable it](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-settingup.html): permissions and policies required, steps, etc.
- How to configure it:
    - Considering [Central configuration](https://docs.aws.amazon.com/securityhub/latest/userguide/central-configuration-intro.html) and AWS GovCloud regions we currently support.
- How to store events in S3 as we currently do for Cloudtrail and other services: if there is a native mechanism to send these directly to buckets or if using another service such as Kinesis is required.

**Comment by fdalmaup** [comment]
# Issue Update

## AWS Config Prerequisite

It is kind of a prerequisite to enable AWS Config along with AWS Security Hub since it uses service-linked AWS Config rules to perform security checks for most controls. 

To support these controls, AWS Config must be enabled on all accounts in each AWS Region where Security Hub is enabled. In addition, for each enabled standard AWS Config must be configured to record resources that are required for enabled controls.

It is recommended to turn on resource recording in AWS Config before enabling Security Hub standards. If Security Hub tries to run security checks when resource recording is turned off, the checks return errors.

## Enabling Security Hub

There are two ways to enable AWS Security Hub:
- By integrating with AWS Organizations: strongly recommend for multi-account and multi-region environments.
- Manually: for standalone accounts, or if the integration with AWS Organizations is unnecessary.

The AWS managed policy called [`AWSSecurityHubFullAccess`](https://docs.aws.amazon.com/securityhub/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-awssecurityhubfullaccess) must be attached to the IAM identity to access the Security Hub console and API operations. The policy called [`AWSSecurityHubOrganizationsAccess`](https://docs.aws.amazon.com/securityhub/latest/userguide/security-iam-awsmanpol.html#security-iam-awsmanpol-awssecurityhuborganizationsaccess) should also be attached to enable and manage the Security Hub through the Organizations integration.

When integrating Security Hub and Organizations, there is the option to use a feature called [central configuration](https://docs.aws.amazon.com/securityhub/latest/userguide/central-configuration-intro.html) to set up and manage Security Hub for the organization. It is strongly recommended to use central configuration because it lets the administrator customize security coverage for the organization. Where appropriate, the delegated administrator can allow a member account to configure its security coverage settings.

### Enabling security standards and security controls

After enabling Security Hub, it is recommended to enable the [security standards and security controls ](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards.html) according to the user's security needs. We should consider this as part of the configuration.

AWS Security Hub consumes, aggregates, and analyzes security findings from various supported AWS and third-party products.

Security Hub also generates its findings by running automated and continuous security checks against rules. The rules are represented by **security controls**. The controls may, in turn, be enabled in one or more **security standards**. The controls help determine whether the requirements in a standard are being met.

**Comment by fdalmaup** [comment]
# Issue Update

AWS Security Hub was successfully set and log files are being sent to the development test bucket:
![image](https://github.com/wazuh/wazuh/assets/26691145/5b396e4f-8313-4a7a-944f-b0414386010f)

The steps to achieve this were:
1. Configure Kinesis and EventBridge: due to the reasons exposed in the last update, the used approach on the AWS side for the AWS Security Hub findings was the same being used for other Wazuh-supported services that do not have a native way to send their events to S3, e.g.,[ Trusted Advisor](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/trusted-advisor.html#amazon-trusted-advisor). 
The EventBridge section was set like this:
![Event-Bridge-Sec-Hub](https://github.com/wazuh/wazuh/assets/26691145/c61d8e28-a164-48f2-8154-bf031a83c4f8)

2. Configure AWS Config: resource recording is required by AWS Security Hub, and rules must be defined for the service to perform security checks.
3. Configure AWS Security Hub
    - Initial setup
    
![Sec-Hub-set-up](https://github.com/wazuh/wazuh/assets/26691145/230999e4-86b6-48ad-9daa-a3f910193375)
As it can be seen, in case the user did not configure it, the reminder regarding AWS Config setup is displayed.

**Comment by nico-stefani** [comment]
# Review

The analysis was correct and clear, going through all the proposed topics. 
LGTM!

**Comment by Selutario** [comment]
Great analysis @fdalmaup. I have just one question regarding the rules for routing findings to EventBridge. 

In the examples shown in the AWS documentation and your research, only the `Security Hub Findings - Imported` event type pattern is used, however, `Security Hub Findings - Custom Action` and `Security Hub Insight Results` are also mentioned here: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-event-formats.html

Would additional rules be needed for those event types?

**Comment by fdalmaup** [comment]
Correct @Selutario. Up next are the steps required for the other event types following the [Using custom actions to send findings and insight results to EventBridge guide](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-custom-actions.html).

## Security Hub Findings - Custom Action
 
- Custom Action:
![CustomAction](https://github.com/wazuh/wazuh/assets/26691145/f11b80e0-dab0-4064-93a2-b2087d7b1c21)
- Rule creation in EventBridge according to the [Defining a rule in EventBridge](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-custom-actions.html#securityhub-cwe-define-rule) guide:
![CustomActionEventPattern](https://github.com/wazuh/wazuh/assets/26691145/88490c50-2bee-4a84-b86d-52f0fd01438d)
- Action application over the Findings to manually send the results to EventBridge:
![CustomActionFindings](https://github.com/wazuh/wazuh/assets/26691145/16dff376-c405-448e-af77-e3c8380667df)

The results were several logs found in the test bucket containing the expected format for `Security Hub Findings - Custom Action`:
```json
{
  "version": "0",
  "id": "1a1111a1-b22b-3c33-444d-5555e5ee5555",
  "detail-type": "Security Hub Findings - Custom Action",
  "source": "aws.securityhub",
  "account": "111122223333",
  "time": "2019-04-11T18:43:48Z",
  "region": "us-west-1",
  "resources": [
    "arn:aws:securityhub:us-west-1:111122223333:action/custom/custom-action-name"
  ],
  "detail": {
    "actionName":"custom-action-name",
    "actionDescription": "description of the action",
    "findings": [
      {
        <finding content>
      }
    ]
  }
}
```

## Security Hub Insight Results

- Using the same defined Custom Action as before.
- Rule creation in EventBridge according to the [Defining a rule in EventBridge](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-custom-actions.html#securityhub-cwe-define-rule) guide:
![InsightResultsEventPattern](https://github.com/wazuh/wazuh/assets/26691145/243686c2-a3e9-4070-8dbc-c6aa1d2ba8fe)
- Action application over selected Insights to manually send the results to EventBridge
![Insights](https://github.com/wazuh/wazuh/assets/26691145/5629e84d-f39b-4b10-a192-99334eac0c3d)

The results were several logs found in the test bucket containing the expected format for `Security Hub Insight Results`:

```json
{ 
  "version": "0",
  "id": "1a1111a1-b22b-3c33-444d-5555e5ee5555",
  "detail-type": "Security Hub Insight Results",
  "source": "aws.securityhub",
  "account": "111122223333",
  "time": "2017-12-22T18:43:48Z",
  "region": "us-west-1",
  "resources": [
      "arn:aws:securityhub:us-west-1:111122223333::product/aws/macie:us-west-1:222233334444:test/trigger/1ec9cf700ef6be062b19584e0b7d84ec/alert/f2893b211841"
  ],
  "detail": {
    "actionName":"name of the action",
    "actionDescription":"description of the action",
    "insightArn":"ARN of the insight",
    "insightName":"Name of the insight",
    "resultType":"ResourceAwsIamAccessKeyUserName",
    "number of results":"number of results, max of 100",
    "insightResults": [
        {"result 1": 5},
        {"result 2": 6}
    ]
  }
}
```


## Conclusion

The logs for the `Security Hub Findings - Imported`, `Security Hub Findings - Custom Action`, and `Security Hub Insight Results` types can be obtained inside the S3 bucket. These follow the format shown [here](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cwe-event-formats.html) for each `detail-type`, therefore having differences in the fields inside the `detail` key.

**Comment by Selutario** [comment]
Understood, thanks @fdalmaup, GJ :+1:
