### ISSUE TITLE
Add integration tests for AWS Security Hub Integration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#21167]
# Description

New AWS module integration tests need to be included for the development carried out as part of the [AWS Security Hub epic](https://github.com/wazuh/wazuh/issues/21209). These must be developed in the [`wazuh/tests/integration` folder](https://github.com/wazuh/wazuh/tree/master/tests/integration) taking into account the migration carried out in https://github.com/wazuh/wazuh/issues/17788 and its structure.

**Comment by Selutario** [comment]
Moving to on hold as the [tests migration](https://github.com/wazuh/wazuh/issues/17788) is almost ready.
