### ISSUE TITLE
Content Manager - Update the behavior of the `XZDecompressor` class and add tests

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#21168]
|Component|
|---|
| [content_manager](https://github.com/wazuh/wazuh/tree/dev-14153-vulndet-refactor/src/shared_modules/content_manager) |

## Description

Align the behavior of the `XZDecompressor` class with the other downloaders and add the [missing tests](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/shared_modules/content_manager/tests/unit/XZDecompressor_test.cpp).

## DoD

- [x] Compliance with:
  - [x] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [x] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [x] Add or Update any relevant documentation to reflect the changes made.

**Comment by tsarquis88** [comment]
# Update

Started working on this.

Draft PR raised.

**Comment by tsarquis88** [comment]
# Update

Moving this to RTR.
