### ISSUE TITLE
Segmentation fault in Vulnerability Detector Refactor

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21176]
| Wazuh version                      | Commit | 
| ---------------------------------- | ------ |
| 4.8.0 - `dev-14153-vulndet-refactor` |  https://github.com/wazuh/wazuh/commit/937acfc87d50ca867a75f163b957a461fd5ddef1      |

### Packages

- **Agent**: https://packages-dev.wazuh.com/warehouse/test/4.8/rpm/var/wazuh-agent-4.8.0-qa.vr.vd.testing.03012024.x86_64.rpm
- **Manager**: https://packages-dev.wazuh.com/warehouse/test/4.8/deb/var/wazuh-manager_4.8.0-qa.vr.vd.testing.03012024_amd64.deb
- **Indexer**: https://packages-dev.wazuh.com/warehouse/test/4.8/deb/wazuh-indexer_4.8.0-qa.vr.vd.testing.03012024_amd64.deb

### Environment

```yaml
manager1:
    roles: [manager, filebeat, indexer]
    os: ubuntu_22
    type: master

manager2:
    roles: [manager, filebeat]
    os: ubuntu_22
    type: worker

agent1:
    roles: [agent]
    os: centos_7
    manager: manager1
```

### Description

It has been detected a segfault in [Vulnerability Detector refactor](https://github.com/wazuh/wazuh/issues/14153)

```log
Jan  3 10:32:28 ip-172-31-10-97 kernel: [ 2962.050478] show_signal_msg: 23 callbacks suppressed
Jan  3 10:32:28 ip-172-31-10-97 kernel: [ 2962.050482] wazuh-modulesd[81362]: segfault at 0 ip 00007fc631f6e2ae sp 00007fc616fda4e0 error 4 in libvulnerability_scanner.so[7fc631c00000+4fe000]
Jan  3 10:32:28 ip-172-31-10-97 kernel: [ 2962.050492] Code: 48 89 c7 e8 c4 88 f7 ff 84 c0 74 07 b8 01 00 00 00 eb 05 b8 00 00 00 00 c9 c3 55 48 89 e5 48 83 ec 10 48 89 7d f8 48 8b 45 f8 <8b> 00 89 c7 e8 59 8f f6 ff c9 c3 90 55 48 89 e5 48 83 ec 10 48 89
```

```json
{"timestamp":"2024-01-03T10:32:30.730+0000","rule":{"level":5,"description":"Process segfaulted.","id":"1010","firedtimes":2,"mail":false,"groups":["syslog","errors","service_availability"],"gdpr":["IV_35.7.d"]},"agent":{"id":"000","name":"ip-172-31-10-97"},"manager":{"name":"ip-172-31-10-97"},"id":"1704277950.1608387","cluster":{"name":"wazuh","node":"master"},"full_log":"Jan  3 10:32:28 ip-172-31-10-97 kernel: [ 2962.050482] wazuh-modulesd[81362]: segfault at 0 ip 00007fc631f6e2ae sp 00007fc616fda4e0 error 4 in libvulnerability_scanner.so[7fc631c00000+4fe000]","predecoder":{"program_name":"kernel","timestamp":"Jan  3 10:32:28","hostname":"ip-172-31-10-97"},"decoder":{"name":"kernel"},"location":"/var/log/kern.log"}
```

No vulnerability alerts were generated in the environment

### Steps to replicate

- Enable vulnerability detector in the manager
- Start the manager
- Segfault should appear after manager feed is finished

```
2024/01/03 10:30:55 wazuh-modulesd:content-updater: INFO: Starting scheduled action for 'vulnerability_feed_manager'
2024/01/03 10:30:55 wazuh-modulesd:content-updater: INFO: Action for 'vulnerability_feed_manager' started
2024/01/03 10:30:55 wazuh-modulesd:content-updater: INFO: Action for 'vulnerability_feed_manager' finished
```

<details>

<summary> Manager configuration </summary>

```
  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://<INDEXER-IP>:9200</host>
    </hosts>
    <username>USER</username>
    <password>PASSWORD</password>
    <ssl>
      <certificate_authorities>
        <ca>/etc/pki/filebeat/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/pki/filebeat/node-2.pem</certificate>
      <key>/etc/pki/filebeat/node-2-key.pem</key>
    </ssl>
  </indexer>


<vulnerability-detection>
    <enabled>yes</enabled>
    <index-status>yes</index-status>
    <feed-update-interval>10h</feed-update-interval>
</vulnerability-detection>
```
</details>

**Comment by pereyra-m** [comment]
Might be related to #21174

**Comment by GabrielEValenzuela** [comment]
Hi @Rebits ! How are you?

As @pereyra-m  says, this issue could be related to a bug in the `integrity_clear` message, we solved this inconvenience, and now branch `dev-14153-vuln-refactor` should be able to run all necessary tests. 

If you want to test again and check, please let me know if this solution works or if we need to do a deep research about the root cause analysis.

Nice day!

**Comment by Rebits** [comment]
Closed for now due to it seems related with https://github.com/wazuh/wazuh/issues/20963
