### ISSUE TITLE
Allow the vendor and CNA data to be managed in databaseFeedManager by content

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21233]
## Description

The alerts generated and not generated by both the legacy vulnerability detector and the refactored one were compared. See https://github.com/wazuh/wazuh/issues/21012 for more details. Also, this situation was described here #21232.

Currently, the `databaseFeedManager` holds a fixed table in the code with the mapping of the package vendor field and the corresponding CNA to scan.

This information and some other similar should be obtained from the content, stored in RocksDB and/or kept in memory to allow
- Fast package scanning
- The possibility to update this and another type of mapped data with the content without a product update

## DoD

- [x] Create the DB to store this type of content considering how it will be published
- [x] Make the corresponding mechanism to update the copy in memory with the new content, update the DB and use a default map in case there isn't any data
- [x] Add UT
- [x] CI Pass

**Comment by sebasfalcone** [comment]
Moved ETA, the block will be removed once is closed
- https://github.com/wazuh/intelligence-platform/issues/1354
