### ISSUE TITLE
Manager Doesn't Start Scan

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21238]
### Problem Description
From #21012. We notice that the `manager` is currently unable to initiate a scan, preventing the scanning process from starting. This issue is impacting the timely identification of vulnerabilities and potentially leaving the system exposed. Investigating and resolving this problem is crucial for maintaining a secure environment.

### Expected Behavior
The manager should be able to start a scan successfully, and the scanning process should initiate without errors. After the database was created successfully

#### Story 1: As a Security Operator
- **I want the manager to successfully initiate a scan so that vulnerabilities can be identified and addressed promptly.**
- **I want to receive timely scan results to ensure the security posture of the system.**

#### Story 2: As a System Administrator
- **I want to identify and resolve the issue preventing the manager from starting a scan to maintain the security of the system.**
- **I want to ensure the scanning process is reliable and can be initiated when needed.**

### Steps to Reproduce
1. Attempt to start a scan using the manager.
3. Review logs and relevant information to identify the root cause of the issue.

### Definition of Done Checklist

- [ ] Identify the root cause of the issue preventing the manager from starting a scan.
- [ ] Implement the necessary changes or fixes to enable successful scan initiation.
- [ ] Verify that the manager can start a scan without errors.
- [ ] Conduct testing to ensure the reliability of the scanning process.

### Additional Information
A possible root cause analysis could be related to the concurrency model the update process of the databasefeedManager creates a `mutual exclusion` where, meanwhile the database is filled, and any agent including the manager can access the data of the database. After of await until the next syscollector scan, the manager doesn't trigger any scan because the syscollector database already exists. 
This problem could be fixed using a concurrent model like a `monitor` design pattern, creating a thread per agent or in a first approach per task to be performed, that makes the scan include the manager and taking the approach of the `mutual exclusion`, notifying to thread where can perform the scan.
For more  information, please check this [link](https://www.modernescpp.com/index.php/monitor-object/)

A representative block diagram could be

![image](https://github.com/wazuh/wazuh/assets/27935340/189c292a-f5fb-4cef-93cb-ec8db766311c)

### Deadline
TBD

**Comment by Dwordcito** [comment]
I didn't see this case, could you provide the steps of reproduction and the impact of this issue?

Discard messages not are expected.

**Comment by Dwordcito** [comment]
related to the trigger issue: https://github.com/wazuh/wazuh/issues/17901
