### ISSUE TITLE
Random error messages generated during Scan

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21240]
### Problem Description
Some error messages are being generated during the scanning process, causing disruptions and potentially impacting the accuracy and reliability of the scan results. It is essential to investigate and resolve these error messages to ensure a smooth and effective scanning process.

### Expected Behavior
The scanning process should occur without generating error messages. Any issues encountered during the scan should be appropriately handled, and error messages should provide meaningful information for troubleshooting.

#### Story 1: As a Security Operator
- **I want the scanning process to occur without generating error messages to ensure the reliability of scan results.**
- **I want clear and meaningful error messages in case issues arise, aiding in efficient troubleshooting.**

#### Story 2: As a System Administrator
- **I want to identify and resolve the root cause of error messages during the scan to maintain the integrity of the scanning process.**
- **I want to ensure that error messages provide actionable information for troubleshooting and resolution.**

### Steps to Reproduce
1. Initiate a scan.
2. Monitor the scanning process for any error messages.
3. Document the error messages generated during the scan.

### Definition of Done Checklist

- [x] Identify the root cause of error messages during the scan.
- [x] Implement the necessary changes or fixes to prevent the generation of error messages.
- [x] Ensure that any issues encountered during the scan are appropriately handled without disrupting the process.
- [x] Update error messages to provide meaningful information for troubleshooting.

### Additional Information
Some errors are:

```bash
2024/01/06 17:18:31 :router: ERROR: Error sending message to provider: Error parsing message, 1: 278: error: unknown field: dhcp
2024/01/06 16:04:22 wazuh-modulesd:vulnerability-scanner[48599] osDataCache.hpp:129 at getOsData(): DEBUG: Error quering Wazuh-DB: Empty response from Wazuh-DB
```

### Possible Solution
One possible solution is to review the scanning logic, error handling mechanisms, and dependencies to identify and address the root cause of error messages.

### Deadline
TBD

**Comment by Dwordcito** [comment]
I saw this error in Windows agents. This could help you in the RCA.

**Comment by MiguelazoDS** [comment]
# Analysis 

There are no errors during the vulnerability scanner database update. But there are some during the scanning of the agents.

None of them are the ones reported in this issue. Many of them are related to the versionObject creation.

[errors.txt](https://github.com/wazuh/wazuh/files/13941606/errors.txt)

**Comment by Dwordcito** [comment]
@MiguelazoDS @sebasfalcone  please re-estimate this issue.

**Comment by sebasfalcone** [comment]
Changed ETA to give time for review and testing

**Comment by sebasfalcone** [comment]
Changed ETA:
- Waiting for final review
