### ISSUE TITLE
Missing Packages During Scan Process

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21255]
### Problem Description
Certain packages are not being detected or included in the scan results, leading to incomplete vulnerability assessments. It is essential to investigate and resolve the issue of missing packages during the scan process to ensure comprehensive coverage and accurate identification of vulnerabilities.

### Expected Behavior
All installed packages should be properly detected and included in the scan results. The scan process should cover all relevant packages to provide a thorough assessment of the system's security posture.

#### Story 1: As a Security Operator
- **I want all installed packages to be properly detected during the scan process to ensure a comprehensive vulnerability assessment.**
- **I want to identify and address the issue of missing packages for accurate security insights.**

#### Story 2: As a System Administrator
- **I want to investigate and resolve the root cause of missing packages during the scan process to maintain the integrity of vulnerability assessments.**
- **I want to ensure that the scanning process provides complete and accurate information about the installed packages.**

### Steps to Reproduce
1. Initiate a scan.
2. Connect for example an agent Ubuntu22

### Definition of Done Checklist

- [ ] Identify the root cause of missing packages during the scan process.
- [ ] Implement the necessary changes or fixes to ensure the inclusion of all installed packages in the scan results.
- [ ] Verify that the scan process now includes all relevant packages for a comprehensive vulnerability assessment.
- [ ] Conduct testing to ensure the accuracy and completeness of the scan results.

### Additional Information
Package `glibc` in Docker Ubuntu22 is vulnerable [reference](https://hub.docker.com/layers/library/ubuntu/jammy/images/sha256-bbf3d1baa208b7649d1d0264ef7d522e1dc0deeeaaf6085bf8e4618867f03494?context=repo&tab=vulnerabilities), and appears to be in the `syscollector` database

```bash
sqlite3 queue/db/001.db "select * from sys_programs" | grep "glibc"
0|2024/01/06 18:05:16|deb|libc-bin|required|libs|2538|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>| |2.35-0ubuntu3.5|amd64|foreign|glibc|GNU C Library: Binaries| |0|||6e1f59f84813ab110b34ff96d31c4c2373649899|85a83bef925e0793cf397832cb2aeba732d68606
0|2024/01/06 18:05:17|deb|libc6|required|libs|13593|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>| |2.35-0ubuntu3.5|amd64|same|glibc|GNU C Library: Shared libraries| |0|||00f6eb1f3fe5f4ac558ac2e4ec785c063cb6e95a|9d952bcbab51a6505dd88f92e4d11abe4895f971
```

But no registry in the log about scanning this package was found

```bash
grep "Initiating a vulnerability scan for package 'glibc' on Agent 'agent_ubuntu_22' \(ID: '001', Version: ''\)\." | wc -l /var/ossec/logs/ossec.log
```
 

### Possible Solution
See if there is a relation with the database or issue #21229. This example is for `Ubuntu22` but could extend to another OS.

### Deadline
TBD

**Comment by Dwordcito** [comment]
Analyze to check this.
