### ISSUE TITLE
The host server should be a selectable agent

### ISSUE THREAD

**Issue by mara2374** [wazuh/wazuh#21284]
to see logs from the server running Wazuh you have to poke around instead of it being listed as an agent. Even though it's logs have an "agent name" which is the hostname of the server.

**Comment by pereyra-m** [comment]
Hi @mara2374 !

The server is at the same time an agent and in a cluster scenario every node would have the same ID. That's the reason the agent `000` behaves differently.
Other users have requested this before (#14135) and the team already has this in backlog
- #8695

There isn't a confirmed release date for this feature yet, sorry for the inconvenience.
Regards.

**Comment by mara2374** [comment]
Thanks for reaching out,

I noticed also when it comes to vulnerabilities you can't select the host as an agent so you don't get the dashboard.

You have to:

[cid:ff66739d-c386-427e-8e6b-5d92b4329162]

Go to "Events"

[cid:6d0c5b9b-72f5-4e3c-bf79-6736f1a9afb9]


To find the vulnerabilities for the host, and no dash for them like you would have for any other box.


All the best,


Thomas



Thomas Olmsted

Security Engineer



[SPHERE Technology Solutions]



M: 508-740-9881

E: ***@***.******@***.***>

W: www.spheretechnologysolutions.com<http://www.spheretechnologysolutions.com/>

Stay connected with SPHERE
***@***.***?anonymous&ep=bwmEmailSignature>             Book time to meet with ***@***.***?anonymous&ep=bwmEmailSignature>
________________________________

**Comment by pereyra-m** [comment]
Hello again @mara2374 !

The vulnerability detector module is being refactored and you should be able to see all the vulnerabilities of the environment indexed in future Wazuh versions

- #14153
