### ISSUE TITLE
VMS usage increment in the Wazuh CentOS agent `Logcollector,SCA` stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#21293]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rc2 | wazuh-modulesd | Agent | Packages | CentOS 7 |

In the analysis of the issue https://github.com/wazuh/wazuh/issues/21263 it has been detected that the VMS plot of the CentOS agent has had an increase of approximately 100MB, while the RSS and USS memory remains the same, Such a broad change has not been found in previous versions, the largest value being 4.6.0

![image](https://github.com/wazuh/wazuh/assets/14913942/99d053b0-89e9-4120-9696-721a6d370e78)
![image](https://github.com/wazuh/wazuh/assets/14913942/d3f46f21-7c4e-40b9-8010-24b50d0dfb3e)

It is necessary to validate that this increase is safe and acceptable

**Comment by vikman90** [comment]
@rauldpm per this comment:

- https://github.com/wazuh/wazuh/issues/20861#issuecomment-1863971904

We are not concerned about VMS.

Despite _wazuh-logcollector_ requests more than 600 MB VMS, it's actually using less than 20 MB (RSS):

- ![](https://camo.githubusercontent.com/6302c5b572d883c5ba59d0cb19ddb9f035f58954b64c3e6fc941bff7060ea751/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343734362d333630306d2f42343734365f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343734365f63656e746f732d7072652d72656c656173655f5253532e706e67)
