### ISSUE TITLE
False Positives for Windows 10 SCA

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21298]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | SCA| Agent | Packages/Sources | Windows 10|

## Description

It has been detected that some Windows 10 rules are failing, even when the configured value is the expected passing value. Rules must be checked to determine what is causing this failure.

- Rule 15511: Guest Accounts are disabled as expected
```
{"timestamp":"2024-01-09T09:34:51.444+0000","rule":{"level":3,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'Accounts: Guest account status' is set to 'Disabled'.","id":"19008","firedtimes":72,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["2.3.1.3"],"cis_csc":["4.7"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792891.798813","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15511","title":"Ensure 'Accounts: Guest account status' is set to 'Disabled'.","description":"This policy setting determines whether the Guest account is enabled or disabled. The Guest account allows unauthenticated network users to gain access to the system. The recommended state for this setting is: Disabled. Note: This setting will have no impact when applied to the Domain Controllers organizational unit via group policy because Domain Controllers have no local account database. It can be configured at the domain level via group policy, similar to account lockout and password policy settings.","rationale":"The default Guest account allows unauthenticated network users to log on as Guest with no password. These unauthorized users could access any resources that are accessible to the Guest account over the network. This capability means that any network shares with permissions that allow access to the Guest account, the Guests group, or the Everyone group will be accessible over the network, which could lead to the exposure or corruption of data.","remediation":"To establish the recommended configuration via GP, set the following UI path to Disabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Accounts: Guest account status","compliance":{"cis":"2.3.1.3","cis_csc":"4.7"},"command":["net user guest"],"result":"passed"}}},"location":"sca"}
```
![15511](https://github.com/wazuh/wazuh/assets/14501079/209af2bf-c454-46a6-af04-5646807600d1)

- Rule 15523:  Password age is set to 30 days
```
{"timestamp":"2024-01-09T09:34:51.844+0000","rule":{"level":7,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'.","id":"19007","firedtimes":120,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["2.3.6.5"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792891.850191","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15523","title":"Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0'.","description":"This policy setting determines the maximum allowable age for a computer account password. By default, domain members automatically change their domain passwords every 30 days. If you increase this interval significantly so that the computers no longer change their passwords, an attacker would have more time to undertake a brute force attack against one of the computer accounts. The recommended state for this setting is: 30 or fewer days, but not 0. Note: A value of 0 does not conform to the benchmark as it disables maximum password age. Note #2: Some problems can occur as a result of machine account password expiration, particularly if a machine is reverted to a previous point-in-time state, as is common with virtual machines. Depending on how far back the reversion is, the older machine account password stored on the machine may no longer be recognized by the domain controllers, and therefore the computer loses its domain trust. This can also disrupt non-persistent VDI implementations, and devices with write filters that disallow permanent changes to the OS volume. Some organizations may choose to exempt themselves from this recommendation and disable machine account password expiration for these situations.","rationale":"In Active Directory-based domains, each computer has an account and password just like every user. By default, the domain members automatically change their domain password every 30 days. If you increase this interval significantly, or set it to 0 so that the computers no longer change their passwords, an attacker will have more time to undertake a brute force attack to guess the password of one or more computer accounts.","remediation":"To establish the recommended configuration via GP, set the following UI path to 30 or fewer days, but not 0: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Domain member: Maximum machine account password age","compliance":{"cis":"2.3.6.5"},"command":["net.exe accounts"],"result":"failed"}}},"location":"sca"}
```
![15523](image" src="https://github.com/wazuh/wazuh/assets/14501079/cf59a8a0-752c-4613-96be-195d8da3ea77)

- Rule 15560: LAN Manager authentication level is configured to `Send NTLMv2 response only. Refuse LM & NTLM`
```
{"timestamp":"2024-01-09T09:34:53.146+0000","rule":{"level":7,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'.","id":"19007","firedtimes":137,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2","4.1"],"nist_800_53":["CM.1","SC.8"],"tsc":["CC7.1","CC7.2","CC6.1","CC6.7","CC7.2"],"cis":["2.3.11.7"],"cis_csc":["3.10"],"hipaa":["164.312.a.2.IV","164.312.e.1","164.312.e.2.I","164.312.e.2.II"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792893.1004651","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15560","title":"Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM'.","description":"LAN Manager (LM) was a family of early Microsoft client/server software (predating Windows NT) that allowed users to link personal computers together on a single network. LM network capabilities included transparent file and print sharing, user security features, and network administration tools. In Active Directory domains, the Kerberos protocol is the default authentication protocol. However, if the Kerberos protocol is not negotiated for some reason, Active Directory will use LM, NTLM, or NTLMv2. LAN Manager authentication includes the LM, NTLM, and NTLM version 2 (NTLMv2) variants, and is the protocol that is used to authenticate all Windows clients when they perform the following operations: -Join a domain -Authenticate between Active Directory forests -Authenticate to down-level domains -Authenticate to computers that do not run Windows 2000, Windows Server 2003, or Windows XP -Authenticate to computers that are not in the domain. The Network security: LAN Manager authentication level setting determines which challenge/response authentication protocol is used for network logons. This choice affects the level of authentication protocol used by clients, the level of session security negotiated, and the level of authentication accepted by servers. The recommended state for this setting is: Send NTLMv2 response only. Refuse LM & NTLM.","rationale":"Windows 2000 and Windows XP clients were configured by default to send LM and NTLM authentication responses (Windows 95-based and Windows 98-based clients only send LM). The default settings in OSes predating Windows Vista / Windows Server 2008 (non- R2) allowed all clients to authenticate with servers and use their resources. However, this meant that LM responses - the weakest form of authentication response - were sent over the network, and it was potentially possible for attackers to sniff that traffic to more easily reproduce the user's password. The Windows 95, Windows 98, and Windows NT operating systems cannot use the Kerberos version 5 protocol for authentication. For this reason, in a Windows Server 2003 domain, these computers authenticate by default with both the LM and NTLM protocols for network authentication. You can enforce a more secure authentication protocol for Windows 95, Windows 98, and Windows NT by using NTLMv2. For the logon process, NTLMv2 uses a secure channel to protect the authentication process. Even if you use NTLMv2 for older clients and servers, Windows-based clients and servers that are members of the domain will use the Kerberos authentication protocol to authenticate with Windows Server 2003 or newer Domain Controllers. For these reasons, it is strongly preferred to restrict the use of LM & NTLM (non-v2) as much as possible.","remediation":"To establish the recommended configuration via GP, set the following UI path to: Send NTLMv2 response only. Refuse LM & NTLM: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Local Policies\\Security Options\\Network security: LAN Manager authentication level","compliance":{"cis":"2.3.11.7","cis_csc":"3.10","pci_dss":"4.1","hipaa":"164.312.a.2.IV,164.312.e.1,164.312.e.2.I,164.312.e.2.II","nist_800_53":"SC.8","tsc":"CC6.1,CC6.7,CC7.2"},"registry":["HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Lsa"],"result":"failed"}}},"location":"sca"}

```
![15560](https://github.com/wazuh/wazuh/assets/14501079/c58746d4-7386-4e4b-a2e9-63570f1f9cf1)

-  Rule 15581: Network adapters have disabled shared access
```
{"timestamp":"2024-01-09T09:34:54.007+0000","rule":{"level":7,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'Internet Connection Sharing (ICS) (SharedAccess)' is set to 'Disabled'.","id":"19007","firedtimes":150,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["5.8"],"cis_csc":["4.8"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792894.1088478","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15581","title":"Ensure 'Internet Connection Sharing (ICS) (SharedAccess)' is set to 'Disabled'.","description":"Provides network access translation, addressing, name resolution and/or intrusion prevention services for a home or small office network. The recommended state for this setting is: Disabled.","rationale":"Internet Connection Sharing (ICS) is a feature that allows someone to 'share' their Internet connection with other machines on the network - it was designed for home or small office environments where only one machine has Internet access - it effectively turns that machine into an Internet router. This feature causes the bridging of networks and likely bypassing other, more secure pathways. It should not be used on any enterprise-managed system.","remediation":"To establish the recommended configuration via GP, set the following UI path to: Disabled. Computer Configuration\\Policies\\Windows Settings\\Security Settings\\System Services\\Internet Connection Sharing (ICS)","compliance":{"cis":"5.8","cis_csc":"4.8"},"registry":["HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\SharedAccess"],"result":"failed"}}},"location":"sca"}
```
![15581](https://github.com/wazuh/wazuh/assets/14501079/a7fd8706-9adb-44b6-b5e7-a083362faf6d)
![15581-2](https://github.com/wazuh/wazuh/assets/14501079/aae58bb2-4c98-458f-8651-28ce3c31920a)

- Rule 15673
```
{"timestamp":"2024-01-09T09:34:56.697+0000","rule":{"level":7,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'.","id":"19007","firedtimes":214,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2","2.2.5"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2","CC6.3"],"cis":["18.1.1.2"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792896.1382151","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15673","title":"Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'.","description":"Disables the lock screen slide show settings in PC Settings and prevents a slide show from playing on the lock screen. The recommended state for this setting is: Enabled.","rationale":"Disabling the lock screen slide show extends the protection afforded by the lock screen to slide show contents.","remediation":"To establish the recommended configuration via GP, set the following UI path to Enabled: Computer Configuration\\Policies\\Administrative Templates\\Control Panel\\Personalization\\Prevent enabling lock screen slide show. Note: This Group Policy path may not exist by default. It is provided by the Group Policy template ControlPanelDisplay.admx/adml that is included with the Microsoft Windows 8.1 & 2012 R2 Administrative Templates (or newer).","compliance":{"cis":"18.1.1.2","pci_dss":"2.2.5","tsc":"CC6.3"},"registry":["HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Personalization"],"result":"failed"}}},"location":"sca"}
```
![15673](https://github.com/wazuh/wazuh/assets/14501079/0525ff3d-973a-4314-98e9-1d47c014f359)

- Rule 15691: IP source routing protection level Set to enabled
```
{"timestamp":"2024-01-09T09:34:57.173+0000","rule":{"level":7,"description":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0: Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'.","id":"19007","firedtimes":228,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2","1.3.3"],"nist_800_53":["CM.1","SC.8"],"tsc":["CC7.1","CC7.2","A1.1","CC6.1","CC7.2"],"cis":["18.4.3"],"cis_csc":["4.8"],"hipaa":["164.312.a.2.IV","164.312.e.1","164.312.e.2.I","164.312.e.2.II"]},"agent":{"id":"001","name":"DESKTOP-RNG5T20","ip":"10.0.2.15"},"manager":{"name":"debian11.localdomain"},"id":"1704792897.1469460","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"309451598","policy":"CIS Microsoft Windows 10 Enterprise Benchmark v1.12.0","check":{"id":"15691","title":"Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'.","description":"IP source routing is a mechanism that allows the sender to determine the IP route that a datagram should take through the network. It is recommended to configure this setting to Not Defined for enterprise environments and to Highest Protection for high security environments to completely disable source routing. The recommended state for this setting is: Enabled: Highest protection, source routing is completely disabled.","rationale":"An attacker could use source routed packets to obscure their identity and location. Source routing allows a computer that sends a packet to specify the route that the packet takes.","remediation":"To establish the recommended configuration via GP, set the following UI path to Enabled: Highest protection, source routing is completely disabled: Computer Configuration\\Policies\\Administrative Templates\\MSS (Legacy)\\MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing). Note: This Group Policy path does not exist by default. An additional Group Policy template (MSS-legacy.admx/adml) is required.","compliance":{"cis":"18.4.3","cis_csc":"4.8","pci_dss":"1.3.3","hipaa":"164.312.a.2.IV,164.312.e.1,164.312.e.2.I,164.312.e.2.II","nist_800_53":"SC.8","tsc":"A1.1,CC6.1,CC7.2"},"registry":["HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters"],"result":"failed"}}},"location":"sca"}
```

**Comment by Johnng007** [comment]
Issue: `Rule 15511: Guest Accounts are disabled as expected`
Response: The rule works fine and the check is valid.
Current Check:
```
    condition: all
    rules:
      - 'c:net user guest -> r:Account active\s+No'
```
<img width="619" alt="image" src="https://github.com/wazuh/wazuh/assets/30580457/2dc7dabc-9776-459a-b42d-f0a5d37d41bd">
Note: The json response posted for this rule shows that the rule passed, please confirm.

Issue: `Rule 15523: Password age is set to 30 days`
Response: The rule works fine and the check is valid.
Current Check:
```
    condition: all
    rules:
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare <= 30'
      - 'c:net.exe accounts -> n:Maximum password age (days):\s+(\d+) compare > 0'
```
<img width="450" alt="image" src="https://github.com/wazuh/wazuh/assets/30580457/8cab3f1a-5c29-466d-98a6-7fe09b07df26">

Issue: `Rule 15560: LAN Manager authentication level is configured to Send NTLMv2 response only. Refuse LM & NTLM`
Response: Rule has an extra space bug which has been fixed in later versions of the SCA/Wazuh

Issue: `Rule 15581: Network adapters have disabled shared access`
Response: The user is doing the wrong check, the correct CIS check is for the status of the Internet Connection Sharing Service as shown in the picture below.
<img width="628" alt="image" src="https://github.com/wazuh/wazuh/assets/30580457/d7ad9241-01e4-4186-bcc5-f27945eea215">

Issue: Rule 15673
Response: Rule has an extra space bug which has been fixed in later versions of the SCA/Wazuh

Issue: Rule 15691: IP source routing protection level Set to enabled
Response: Rule has an extra space bug which has been fixed in later versions of the SCA/Wazuh

**Comment by Deblintrake09** [comment]
LGTM! Thanks for the response!

**Comment by ooniagbi** [comment]
Closing this for now.

**Comment by giacatluong** [comment]
For fule Rule 15523, what version did you tested?  I tested 4.7.1 and it not working

**Comment by Johnng007** [comment]
@giacatluong , 
For Rule 15523: Can you paste here a snipe of the rule you have in your SCA file.
For Rule 15511: The check is to "title: "Ensure 'Accounts: Guest account status' is set to 'Disabled'."" 
                          We are strictly sticking to the CIS baseline, until otherwise advised.
                          You can however make the below additional changes to meet your requirement.

    condition: any
    rules:
      - 'c:net user guest -> r:Account active\s+No'
      - 'c:net user guest -> r:The user name could not be found.'

**Comment by giacatluong** [comment]
This is what I think after digging it deeper:
The condition for rule 15523 is wrong. (It should not use the net accounts output because this net output is for different rule 15501.  It should check for the MaximumPasswordAge value under the registry key instead:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters

For rule 15511, It's a bug.. 
the solution you provided about is correct.
condition: any
rules:
  - 'c:net user guest -> r:Account active\s+No'
  - 'c:net user guest -> r:The user name could not be found.' 

I hope this will be fixed in next release

Regards,

**Comment by Johnng007** [comment]
To be fixed in 4.8.0
**Windows 10:**
- Issue: https://github.com/wazuh/wazuh/issues/17329
- Pull: https://github.com/wazuh/wazuh/pull/19515
**Windows 11:**
- Issue: https://github.com/wazuh/wazuh/issues/17330
- Pull: https://github.com/wazuh/wazuh/pull/20044

**Comment by giacatluong** [comment]
this one broken too:
  - id: 15673
    title: "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled'."
    description: "Disables the lock screen slide show settings in PC Settings and prevents a slide show from playing on the lock screen. The recommended state for this setting is: Enabled."
    rationale: "Disabling the lock screen slide show extends the protection afforded by the lock screen to slide show contents."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Enabled: Computer Configuration\\Policies\\Administrative Templates\\Control Panel\\Personalization\\Prevent enabling lock screen slide show. Note: This Group Policy path may not exist by default. It is provided by the Group Policy template ControlPanelDisplay.admx/adml that is included with the Microsoft Windows 8.1 & 2012 R2 Administrative Templates (or newer)."
    compliance:
      - cis: ["18.1.1.2"]
      - pci_dss: ["2.2.5"]
      - tsc: ["CC6.3"]
    condition: all
    rules:
      - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization'
      - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization -> NoLockScreenSlideshow '
      - 'r:HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Personalization -> NoLockScreenSlideshow -> 1'
     

the 2nd has the space after the NoLocakScreenSlideShow, so it always fail

**Comment by giacatluong** [comment]
the same for rule 15691

  - id: 15691
    title: "Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing)' is set to 'Enabled: Highest protection, source routing is completely disabled'."
    description: "IP source routing is a mechanism that allows the sender to determine the IP route that a datagram should take through the network. It is recommended to configure this setting to Not Defined for enterprise environments and to Highest Protection for high security environments to completely disable source routing. The recommended state for this setting is: Enabled: Highest protection, source routing is completely disabled."
    rationale: "An attacker could use source routed packets to obscure their identity and location. Source routing allows a computer that sends a packet to specify the route that the packet takes."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Enabled: Highest protection, source routing is completely disabled: Computer Configuration\\Policies\\Administrative Templates\\MSS (Legacy)\\MSS: (DisableIPSourceRouting) IP source routing protection level (protects against packet spoofing). Note: This Group Policy path does not exist by default. An additional Group Policy template (MSS-legacy.admx/adml) is required."
    compliance:
      - cis: ["18.4.3"]
      - cis_csc: ["4.8"]
      - pci_dss: ["1.3.3"]
      - hipaa: ["164.312.a.2.IV", "164.312.e.1", "164.312.e.2.I", "164.312.e.2.II"]
      - nist_800_53: ["SC.8"]
      - tsc: ["A1.1", "CC6.1", "CC7.2"]
    condition: all
    rules:
      - 'r:HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
      - 'r:HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters -> DisableIPSourceRouting '
      - 'r:HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters -> DisableIPSourceRouting -> 2'


the space after DisableIPSourceRouting  fail the rule

**Comment by Johnng007** [comment]
Hello @giacatluong 
The issues raised has been fixed in the SCAs contained in Wazuh v4.8.0
https://github.com/wazuh/wazuh/tree/master/ruleset/sca/windows

I would advice you upgrade to the latest version or update your SCA files from the master branch.

**Comment by giacatluong** [comment]
I cannot figure out why this rule fail:
  - id: 15505
    title: "Ensure 'Relax minimum password length limits' is set to 'Enabled'."
    description: "This policy setting determines whether the minimum password length setting can be increased beyond the legacy limit of 14 characters. For more information please see the following Microsoft Security Blog. The recommended state for this setting is: Enabled. Note: This setting only affects local accounts on the computer. Domain accounts are only affected by settings on the Domain Controllers, because that is where domain accounts are stored."
    rationale: "This setting will enable the enforcement of longer and generally stronger passwords or passphrases where MFA is not in use."
    remediation: "To establish the recommended configuration via GP, set the following UI path to Enabled: Computer Configuration\\Policies\\Windows Settings\\Security Settings\\Account Policies\\Password Policy\\Relax minimum password length limits. Note: This setting is only available within the built-in OS security template of Windows 10 Release 2004 and Server 2022 (or newer), and is not available via older versions of the OS, or via downloadable Administrative Templates (ADMX/ADML). Therefore, you must use a Windows 10 Release 2004 or Server 2022 system (or newer) to view or edit this setting with the Group Policy Management Console (GPMC) or Group Policy Management Editor (GPME)."
    compliance:
      - cis: ["1.1.6"]
      - cis_csc: ["5.2"]
    condition: all
    rules:
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SAM'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SAM -> RelaxMinimumPasswordLengthLimits'
      - 'r:HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SAM -> RelaxMinimumPasswordLengthLimits -> 1'


Here is the data inside the registry:
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SAM]
"RelaxMinimumPasswordLengthLimits"=dword:00000001

Thanks

**Comment by Johnng007** [comment]
@giacatluong 
The rule is correct, you can check the group policy settings so be sure its enabled so its not overwriting the registry values.
![image](https://github.com/wazuh/wazuh/assets/30580457/3d95db5a-6c8c-4c6c-a5bc-d9f3556d50f7)

**Comment by giacatluong** [comment]
I know it is correct, but I dont understand why it still reported as fail
________________________________

**Comment by IsExec** [comment]
LGTM!

**Comment by zbalkan** [comment]
## Renamed account / disabled account problem for Guest

You are missing a point when the user account is renamed, your check for disabled fails as you don't know the new name. If the Guest is renamed, you will get:
```batch
net user guest
The user name could not be found.

More help is available by typing NET HELPMSG 2221.
```

But if you check the Guest account by active status, you are querying for the wrong account name. You can query the members `Guests` group to get the actual `Guest` user:
```batch
net localgroup guests

Alias name     GUESTs
Comment        Guests have the same access as members of the Users group by default, except for the Guest account which is further restricted

Members

-------------------------------------------------------------------------------
<guest name>
The command completed successfully.
```

But this is not reliable as the user may cleaned up groups or renamed. Names are not reliable. The most reliable way is to query by [SID](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids):

```batch
wmic useraccount where "sid like 's-1-5-21-%-501'" get name,status

Name      Status
<guest name> Degraded
```

Then you can get the actual Guest account with it's status. If it is enabled, you'll get "OK" and if it is disabled, you'll get "Degraded".

## Localization problem for Administrator:

The second problem with the checks is that the check is limited by language. If the Windows system is installed in any language other than English, you'll get a false negative as [built-in account names differ by language.](https://social.technet.microsoft.com/wiki/contents/articles/13813.localized-names-for-administrator-account-in-windows.aspx) Since the commands are run under SYSTEM user context, user locale does not matter. SYSTEM uses the language selected during Windows installation. So, you need to compare against all possible default Administrator account names.

You can use the same `wmic` command here:
```batch
wmic useraccount where "sid like 's-1-5-21-%-500'" get name,status

Name      Status
<administator name> Degraded
```

**Comment by giacatluong** [comment]
Exactly.  I was trying to say those four rules (2 to administrator and 2 for Guest) are invalidOn Jan 24, 2024, at 8:12 AM, Zafer Balkan ***@***.***> wrote:﻿
Renamed account / disabled account problem for Guest
You are missing a point when the user account is renamed, your check for disabled fails as you don't know the new name. If the Guest is renamed, you will get:
net user guest
The user name could not be found.

More help is available by typing NET HELPMSG 2221.
But if you check the Guest account by active status, you are querying for the wrong account name. You can query the members Guests group to get the actual Guest user:
net localgroup guests

Alias name     GUESTs
Comment        Guests have the same access as members of the Users group by default, except for the Guest account which is further restricted

Members

-------------------------------------------------------------------------------
<guest name>
The command completed successfully.
But this is not reliable as the user may cleaned up groups or renamed. Names are not reliable. The most reliable way is to query by SID:
wmic useraccount where "sid like 's-1-5-21-%-501'" get name,status

Name      Status
<guest name> Degraded
Then you can get the actual Guest account with it's status. If it is enabled, you'll get "OK" and if it is disabled, you'll get "Degraded".
Localization problem for Administrator:
The second problem with the checks is that the check is limited by language. If the Windows system is installed in any language other than English, you'll get a false negative as built-in account names differ by language. Since the commands are run under SYSTEM user context, user locale does not matter. SYSTEM uses the language selected during Windows installation. So, you need to compare against all possible default Administrator account names.
You can use the same wmic command here:
wmic useraccount where "sid like 's-1-5-21-%-500'" get name,status

Name      Status
<administator name> Degraded

**Comment by zbalkan** [comment]
In [r/Wazuh](https://old.reddit.com/r/Wazuh), there was someone who was suffering from the SCA issuse, related to the point: https://old.reddit.com/r/Wazuh/comments/198t2jc/sca_not_reflecting_changes/

**Comment by ooniagbi** [comment]
- Merged https://github.com/wazuh/wazuh/pull/21584
- All new issues can be opened under new issues/asked on the community channel.
- Closing this issue because the originally identified checks have been fixed/will be fixed in future versions.
