### ISSUE TITLE
Bad syscollector network iface values handling 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#21296]
# Description 

As a consequence of the error found 

`2024/01/04 13:51:53 :router[138953] logging_helper.c:25 at taggedLogFunction(): ERROR: Error sending message to provider: Error parsing message, 1: 573: error: invalid number: "-956995642", constant does not fit [0; 4294967295]`

and addressed here https://github.com/wazuh/wazuh/issues/21194 

After a little investigation, we found several mishandling values for some Syscollector fields 

- There's an implicit conversion from uint to int that causes invalid information stored in the Syscollector database for network iface provider. This specific case was discovered because of the log shared above. 

![image](https://github.com/wazuh/wazuh/assets/13010397/cdfb9834-58f1-4f09-8d42-7c342095bd12)

- The value stored in the manager database after a delta event does not match the one found with the testtool.

<details><summary>Expand</summary>

Agent
![image](https://github.com/wazuh/wazuh/assets/13010397/bd36ea35-50c6-4fe6-b464-ac048c17f09d)
Manager
![image](https://github.com/wazuh/wazuh/assets/13010397/baf41bd3-ccfb-45a5-9608-92402902b28c)

</details>

- The uint data type is easy to overpass when we are talking about "bytes" for any interface and the value ends up containing wrong information.

The maximum size of a uint value is = 4294967295, which in bytes is almost 4GB. We can reach that number easily by downloading a single ISO file.

- Also the MTU may be negative according to the issue studied here https://github.com/wazuh/wazuh/issues/21340#issuecomment-1887287776

# DoD 

- [x] Avoid implicit conversion from uint to int 
- [x] Fix delta event wrong value 
- [x] Evaluate the uint data type. Probably using long would be a better option even though the negative values will not be used.

**Comment by Dwordcito** [comment]
This change is for the major version.

**Comment by MiguelazoDS** [comment]
# Analysis 
 
This issue is strongly related to this one https://github.com/wazuh/wazuh/issues/21194. This was not properly solved because it was so intrusive, but as a workaround, we changed the flatbuffer schema data type to allow negative values, which are a consequence of the bad data type conversion on the agent side. That leads to invalid values stored in the syscollector local database, and those are sent as sync messages to the manager, causing the issue we described above. 

Also as part of the same issue, because of a delta message, we experience something similar. The value is casted somehow and the value ends up showing incorrect information on the manager side. 

We need to mention this issue as well https://github.com/wazuh/wazuh/issues/21340.

**Comment by sebasfalcone** [comment]
## Issue blocked
Due to the update of the CTI content, which is handled in 4.8.0, some tests will continue to fail

We will wait until 4.8.0 is merged in this branch
