### ISSUE TITLE
Data race conditions at FIM's run_check

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#21309]
The following defect related to FIM's run_check have been reported by Coverity:

	
- **CID 1575419**: Data race condition (BAD_CHECK_OF_WAIT_COND)
wait_cond_improperly_checked: The wait condition prompting the wait upon fps_mutex is not checked correctly. If a spurious wakeup occurs, the thread could continue its task before the wait condition is satisfied.

https://github.com/wazuh/wazuh/blob/b28ebb9172d16e417ddc78ba9e73e2fc2a901418/src/syscheckd/src/run_check.c#L178

**Comment by mjcr99** [comment]
## Update
**(29/08/2024)** Started working on this issue. Researched the problem cause and opened PR with the proposed solution.
