### ISSUE TITLE
Remove all references of the legacy vulnerability detector module

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21303]
## Description

The vulnerability detector module has been refactored and the code of the legacy module has been removed.
Nevertheless, there are still some references to the old module that should be removed.
Here are some items but a deep search should be done during the development of the issue in case some references are missing:

- `wazuh-db`: the `vuln_cves` table in `schema_agents.sql` and any query related to this table, the triggers of `sys_programs` table in `schema_agents.sql`, the **triaged** column of `sys_programs` and any query related to this column; and any reference to `vuln_cves` in the code and tests.
- Defines and log messages: all the messages related to the legacy module defined at `src/error_messages/debug_messages.h`, `src/error_messages/information_messages.h`, and `src/error_messages/error_messages.h`
- The legacy mechanism to run a vulnerability detector scan on demand (`src/wazuh_modules/wmcom.c` and related)
- Rules related to the legacy module (rule **515** at `ruleset/rules/0015-ossec_rules.xml` and related)
- All the references related to the framework (talk with the corresponding team)
- Analyze the counters related to vulnerability detector events (`w_inc_modules_vulnerability_decoded_events()` and related)
- The feeds related to offline feeds generation in `tools/vulnerability-detector` 

**Note**: if we remove the old vulnerabilities inventory, a user that performs an upgrade from v4.7.x to v4.8.0 would lose all the data but wouldn't see the results of the new scanner because the **syscollector** agent DBs are completely synced. This behavior must be confirmed with the product owner and a mechanism to re-scan the agents after the upgrade could be considered.

## DoD

- [x] #21564
- [x] Remove all the dangling references to the old module of the code.
- [x] Make sure everything keeps working as expected.
- [x] CI Pass

**Comment by pereyra-m** [comment]
## Update

The issue was moved to blocked:
- Waiting the approval of the PR https://github.com/wazuh/wazuh-qa/pull/4872
- Waiting the development of the issue https://github.com/wazuh/wazuh/issues/21461

**Comment by Dwordcito** [comment]
@pereyra-m we have any news around this issue? Is still pending review?

@Rebits could you help here? -> PR review : https://github.com/wazuh/wazuh-qa/pull/4872

**Comment by pereyra-m** [comment]
The issue #21461 is on hold and assigned to @Selutario and @mhamra.
Its ETA is Jan 24, so I'll use the same date for this issue.

**Comment by pereyra-m** [comment]
Now that the tasks in framework and QA seem ready, moving the issue from blocked.

**Comment by sebasfalcone** [comment]
testing
