### ISSUE TITLE
Syscollector Support Dropped for Agents Pre-4.2 in Vulnerability Detector Refactor

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21319]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-Alpha 2| Syscollector | Manager/Agent | Packages | Ubuntu 22 |

### Description

In version 4.8.0, we introduced a refactor of the vulnerability detector module, resulting in a breaking change that impacts the compatibility between Wazuh agents and the Wazuh manager. Prior to this change, the Syscollector's message format had been altered in the 4.2 version, and although agents from earlier versions were supported, the recent refactor no longer accommodates agents predating version 4.2.

### Impact

Agents Pre-4.2 will no longer be supported. Removing the full compatibility between agents and managers since the agent version is less than the manager

Currently, agents Pre-4.2 will generate a large amount of error messages in the manager:
```
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 124: error: unknown enum value: process
2024/01/10 10:27:04 :router: ERROR: Error sending message to provider: Error parsing message, 1: 128: error: unknown enum value: process_end
```

### Documentation

This breaking change is not currently reflected in the documentation. The documentation suggests full compatibility between the Wazuh agent and the Wazuh manager when the Wazuh manager version is equal to or later than that of the Wazuh agent. However, with this recent change, that guarantee is no longer valid.

https://github.com/wazuh/wazuh-documentation/blob/c104e23a7dde8a1a435d86fae24ff450e5bdcc47/source/installation-guide/wazuh-agent/index.rst?plain=1#L109C1-L109C166

**Comment by pereyra-m** [comment]
I'd also add a note saying that after the upgrade, all the legacy vulnerabilities inventory will be removed and all the agents will be scanned again.

**Comment by davidjiglesias** [comment]
@Dwordcito Approved and accepted by @santiago-bassett, we can continue.

**Comment by Dwordcito** [comment]
Closed, this behavior is expected by design.
