### ISSUE TITLE
Wazuh Agent installation failed in FreeBSD. gmake not found.

### ISSUE THREAD

**Issue by VenoVeno** [wazuh/wazuh#21313]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | Wazuh component | Agent | Sources | FreeBSD - 13.1-RELEASE |

I have to install Wazug Agent in FreeBSD. Before trying it out. 
Does Wazuh Agent installation is supported in FreeBSD?.

When i tried to run install.sh.

```
DIR="/var/ossec"
 - Running the Makefile

./install.sh: gmake: not found
./install.sh: gmake: not found

 Error 0x5.
 Building error. Unable to finish the installation.
```

I tried to install gmake with `pkg install gmake`.

pkg: No packages available to install matching 'gmake' have been found in the repositories

I also checked `/etc/pkg/FreeBSD.conf`:
```
FreeBSD: {
        url: "http://z-image/FreeBSD13/PKG/puppet",
}
```

I couldn't find any gmake repo in the mentioned URL. 
Can anyone please help. Thanks in advance.

**Comment by jnasselle** [comment]
Hi @VenoVeno ,

I was able to compile and install the agent on https://app.vagrantup.com/generic/boxes/freebsd13 after installing `gmake`

```
[root@freebsd13 /usr/home/vagrant/wazuh/src]# pkg gmake
pkg: unknown command: gmake

For more information on available commands and options see 'pkg help'.
[root@freebsd13 /usr/home/vagrant/wazuh/src]# pkg install gmake
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	gmake: 4.3_2

Number of packages to be installed: 1

The process will require 2 MiB more space.
416 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching gmake-4.3_2.pkg: 100%  416 KiB 212.9kB/s    00:02    
Checking integrity... done (0 conflicting)
[1/1] Installing gmake-4.3_2...
[1/1] Extracting gmake-4.3_2: 100%

```

```
[root@freebsd13 /usr/home/vagrant/wazuh]# cat /etc/pkg/FreeBSD.conf
# $FreeBSD$
#
# To disable this repository, instead of modifying or removing this file,
# create a /usr/local/etc/pkg/repos/FreeBSD.conf file:
#
#   mkdir -p /usr/local/etc/pkg/repos
#   echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
#

FreeBSD: {
  url: "pkg+http://pkg.FreeBSD.org/${ABI}/quarterly",
  mirror_type: "srv",
  signature_type: "fingerprints",
  fingerprints: "/usr/share/keys/pkg",
  enabled: yes
}

```
Please check your `/etc/pkg/FreeBSD.conf`

**Comment by jnasselle** [comment]
Hi @VenoVeno ,

This is not related to Wazuh compilation procedure and should not be an issue since the problem is with your environment. Install gmake using whatever mechanism you want and you will be able to compile and install the Wazuh Agent.

Regards,
Nicolas
