### ISSUE TITLE
Outdated python dependencies for Cloud Security Section

### ISSUE THREAD

**Issue by ace-109** [wazuh/wazuh#21350]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.1 | Wazuh component | Manager/Agent | Packages | Ubuntu 22.04 |

Hello Team

While reworking the Cloud security monitoring documentation, we noticed that the Python dependencies needed for the integration to work are outdated. We list them below

### AWS Integration
In the [AWS pip dependencies](https://documentation.wazuh.com/current/cloud-security/amazon/services/prerequisites/dependencies.html#aws-pip-dependencies) section, we have several packages with outdated versions
```
pip3 install boto3==1.17.85 botocore==1.20.85 jmespath==0.9.5 python-dateutil==2.8.1 six==1.14.0 urllib3==1.26.5 s3transfer==0.4.2 pyarrow==8.0.0 pyarrow_hotfix==0.5
```
Boto3 and botocore for example, are both on version 1.34.16. 

Are there any plans to test more recent versions of these dependencies?

**Comment by Selutario** [comment]
Hello @ace-109,

The version of the dependencies listed in the documentation is the same as the version installed in the Python embedded in the managers (link to [requirements](https://github.com/wazuh/wazuh/blob/master/framework/requirements.txt) files). Using the same version helps us to ensure that Cloud security integrations work correctly and in the same way for both agents and managers. 

The process of updating dependencies in embedded Python is not always simple, so it is only carried out when a vulnerability is found during the weekly scan or when we want to add new features to the integration (if using more recent versions is required).
