### ISSUE TITLE
Wazuh-agent fails to get the message for events in "Forwarded Events" log on Windows

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#2136]
## Bug report

**OS**: Windows 10
**Wazuh version**: 2.1.1 (I suspect is the same on latest version, not tested yet)

`full_log` in elastic:
```
2018 Dec 18 12:22:16 WinEvtLog: Security: AUDIT_SUCCESS(4672): Microsoft-Windows-Security-Auditing: (no user): no domain: SERVER-01.mydomain.local: (no message)
```
Event XML in `Forwarded Events` log:
```xml
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" /> 
  <EventID>4672</EventID> 
  <Version>0</Version> 
  <Level>0</Level> 
  <Task>12548</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8020000000000000</Keywords> 
  <TimeCreated SystemTime="2018-12-18T12:22:16.277302600Z" /> 
  <EventRecordID>275782849</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="456" ThreadID="1276" /> 
  <Channel>Security</Channel> 
  <Computer>SERVER-01.mydomain.local</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data Name="SubjectUserSid">S-1-5-18</Data> 
  <Data Name="SubjectUserName">SERVER-01$</Data> 
  <Data Name="SubjectDomainName">MYDOMAINLOCAL</Data> 
  <Data Name="SubjectLogonId">0x46edd03</Data> 
  <Data Name="PrivilegeList">SeSecurityPrivilege SeBackupPrivilege SeRestorePrivilege SeTakeOwnershipPrivilege SeDebugPrivilege SeSystemEnvironmentPrivilege SeLoadDriverPrivilege SeImpersonatePrivilege SeEnableDelegationPrivilege SeTcbPrivilege</Data> 
  </EventData>
- <RenderingInfo Culture="en-US">
  <Message>Special privileges assigned to new logon. Subject: Security ID: S-1-5-18 Account Name: SERVER-01$ Account Domain: MYDOMAINLOCAL Logon ID: 0x46EDD03 Privileges: SeSecurityPrivilege SeBackupPrivilege SeRestorePrivilege SeTakeOwnershipPrivilege SeDebugPrivilege SeSystemEnvironmentPrivilege SeLoadDriverPrivilege SeImpersonatePrivilege SeEnableDelegationPrivilege SeTcbPrivilege</Message> 
  <Level>Information</Level> 
  <Task>Special Logon</Task> 
  <Opcode>Info</Opcode> 
  <Channel>Security</Channel> 
  <Provider>Microsoft Windows security auditing.</Provider> 
- <Keywords>
  <Keyword>Audit Success</Keyword> 
  </Keywords>
  </RenderingInfo>
  </Event>
```

# The use case

Multiple windows hosts send their logs into a single host. The event are all gathered in `Forwarded Events`. Wazuh-agent is installed on that single host and is setup to read all events from `Forwarded Events` log.

**Comment by rossengeorgiev** [comment]
Hi @Cerv1, thanks for the information. I will be happy to test this out. Are there any steps available that I can follow to build the install file?

**Comment by Cerv1** [comment]
Hi @rossengeorgiev,

You need to download the repository and compile the manager and the Windows agent. 

**`WARNING: This feature is still in development.`**

You can follow these steps to install the manager:

### Install dependencies

#### For RPM-based distributions:
```
# yum install make gcc policycoreutils-python automake autoconf libtool git
```
#### For Debian-based distributions:
```
# apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git
```

### Install wazuh-manager
```
$ git clone https://github.com/wazuh/wazuh.git
$ cd wazuh
$ git checkout fix-windows-dec
$ sudo ./install.sh
```

### Install wazuh-agent on Windows
Since it is much more complicated to generate the Windows agent, I attach one to make it easier for you to perform the tests. You only have to install it in the host where you want to do the tests. 

You can download the custom agent [here](https://github.com/wazuh/wazuh/files/2695148/wazuh-custom-agent.zip).

Remember, it is a non-stable branch and is not recommended to be used in production systems.

Let me know if this helps.

Best regards,
Cerv1.

**Comment by rossengeorgiev** [comment]
Thanks, I will test this after I rebuild my lab.

**Comment by Cerv1** [comment]
Hi @rossengeorgiev,

I just wanted to let you know  that this feature is now merged in Wazuh 3.8 (66e4bb60d28b4ca8b6faff054e5252672a2a6c0d) so it will be included in the next realease. Can I close this issue now?

Best regards,
Cerv1

**Comment by rossengeorgiev** [comment]
hi @Cerv1, haven't had to chance to test it out yet. I will try to give it a try soon. Quick question, what is the purpose of `etc/lists/security-eventchannel`?

**Comment by Cerv1** [comment]
Hi @rossengeorgiev,

The `security-eventchannel` list contains the ID of the Windows `Security` channel events to be obtained, either by alerts or as logs in the `archives.log` file.

Best regards,
Cerv1.

**Comment by cristgl** [comment]
Hi @rossengeorgiev,

I'm closing this issue as it has no new answers since January. Feel free to reopen it if you have any more questions.

Kind regards,
Cristina

**Comment by rossengeorgiev** [comment]
Hi @cristgl, this works on the lastest version of wazuh. EvenChannels are able to read the forwardevent log file
