### ISSUE TITLE
Release 4.8.0 - Alpha 2 - Integration tests

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#21399]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/21386|
| **Version**                      | 4.8.0                                                   |
| **Release stage**            | Alpha 2                                                      |
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.8.0-alpha2          |
| **Wazuh QA: Branch**    | `v4.8.0-alpha2`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.0-alpha2      |
| **Wazuh: Branch**    | `v4.8.0-alpha2` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build evidence:*** https://ci.wazuh.info/job/Test_integration_launcher/244/

**Re-launch failures:**
   - active_response (CentOS, Windows): https://ci.wazuh.info/job/Test_integration/45849
   - enrollment (CentOS, Windows): https://ci.wazuh.info/job/Test_integration/45850/
   - fim (CentOS, Windows): https://ci.wazuh.info/job/Test_integration/45851/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

| Test suite | Target | CentOS | Ubuntu | Windows | macOS | Solaris |
|--|--|--|--|--|--|--|
| active_response | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45809/manager_html_report_Test_integration_B45809.zip) | N/A | N/A | N/A | N/A |
| active_response | Agent | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45849/agent_centos_html_report_Test_integration_B45849.zip) | N/A | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45849/agent_windows_html_report_Test_integration_B45849.zip) | N/A | N/A |
| agentd | Agent | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45811/agent_centos_html_report_Test_integration_B45811.zip) | N/A | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45811/agent_windows_html_report_Test_integration_B45811.zip) | N/A | N/A |
| analysisd | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45812/manager_html_report_Test_integration_B45812.zip) | N/A | N/A | N/A | N/A |
| api | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45813/manager_html_report_Test_integration_B45813.zip) | N/A | N/A | N/A | N/A |
| authd | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45814/manager_html_report_Test_integration_B45814.zip) | N/A | N/A | N/A | N/A |
| enrollment | Agent | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45850/agent_centos_html_report_Test_integration_B45850.zip) | N/A | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45850/agent_windows_html_report_Test_integration_B45850.zip) | N/A | N/A |
| fim | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45816/manager_html_report_Test_integration_B45816.zip) | N/A | N/A | N/A | N/A |
| fim | Agent | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45851/agent_centos_html_report_Test_integration_B45851.zip) | N/A | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45851/agent_windows_html_report_Test_integration_B45851.zip) | N/A | N/A |
| fim | Agent | N/A | N/A | N/A | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45818/agent_macos_html_report_Test_integration_B45818.zip) | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45818/agent_solaris_html_report_Test_integration_B45818.zip) |
| gcloud | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45819/manager_html_report_Test_integration_B45819.zip) | N/A | N/A | N/A | N/A |
| github | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45820/manager_html_report_Test_integration_B45820.zip) | N/A | N/A | N/A | N/A |
| github | Agent | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45821/agent_centos_html_report_Test_integration_B45821.zip) | N/A | N/A | N/A | N/A |
| logcollector | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45822/manager_html_report_Test_integration_B45822.zip) | N/A | N/A | N/A | N/A |
| logcollector | Agent | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45823/agent_centos_html_report_Test_integration_B45823.zip) | N/A | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45823/agent_windows_html_report_Test_integration_B45823.zip) | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45823/agent_macos_html_report_Test_integration_B45823.zip) | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45823/agent_solaris_html_report_Test_integration_B45823.zip) |
| logtest | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45824/manager_html_report_Test_integration_B45824.zip) | N/A | N/A | N/A | N/A |
| office_365 | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45825/manager_html_report_Test_integration_B45825.zip) | N/A | N/A | N/A | N/A |
| office_365 | Agent | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45826/agent_centos_html_report_Test_integration_B45826.zip) | N/A | N/A | N/A | N/A |
| remoted | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45827/manager_html_report_Test_integration_B45827.zip) | N/A | N/A | N/A | N/A |
| rids | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45828/manager_html_report_Test_integration_B45828.zip) | N/A | N/A | N/A | N/A |
| rootcheck | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45829/manager_html_report_Test_integration_B45829.zip) | N/A | N/A | N/A | N/A |
| vulnerability_detector | Manager | ⚫ | N/A | N/A | N/A | N/A |
| wazuh_db | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45830/manager_html_report_Test_integration_B45830.zip) | N/A | N/A | N/A | N/A |
| syscollector | Manager | 🟢 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45831/manager_html_report_Test_integration_B45831.zip) | N/A | N/A | N/A | N/A |
| syscollector | Agent | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45808/agent_centos_html_report_Test_integration_B45808.zip) | N/A | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45808/agent_windows_html_report_Test_integration_B45808.zip) | 🔴 [Download Evidence](https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B45808/agent_macos_html_report_Test_integration_B45808.zip) | N/A |

---

### New Issues

- https://github.com/wazuh/wazuh-qa/issues/4839
- https://github.com/wazuh/wazuh-qa/issues/4840

### Known Issues

- https://github.com/wazuh/wazuh-qa/issues/4230

**Comment by rafabailon** [comment]
##Notes

### Errors in Tests

The `vulnerability_detector` test has not been performed. The pipeline has not launched the test. I have tried running a pipeline just for the `vulnerability_detector` test and it did not work. It requires research.

Some tests have failed because they could not connect to the `Windows Agent` machine. I think it could be solved by relaunching the failed tests.

**Comment by pro-akim** [comment]
## Review Notes
LGTM

**Comment by juliamagan** [comment]
LGTM
