### ISSUE TITLE
OpenSCAP processes getting stuck

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#2139]
## Bug report

**OS**
_CentOS7_

**Wazuh version**
_3.7.0_

**Install type**
_agent_

**Install method**
_packages_

**Log sample**

```
ps aux|grep open
root       1365  0.2  2.1 1067484 695388 ?      SN   Dec06  23:42 /usr/libexec/openscap/probe_file
root       3564  0.1  2.1 1067484 716836 ?      SN   Dec01  23:42 /usr/libexec/openscap/probe_file
root       8773  0.0  0.0 1067484  384 ?        SN   Sep26  22:37 /usr/libexec/openscap/probe_file
root      10966  0.2  2.2 1133020 726812 ?      SN   Dec07  23:52 /usr/libexec/openscap/probe_file
root      29738  0.0  0.0 1133020 14000 ?       SN   Nov18  24:24 /usr/libexec/openscap/probe_file
root      33076  0.0  0.0 1067484 2284 ?        SN   Oct24  23:45 /usr/libexec/openscap/probe_file
root      50004  0.0  0.0 1067484 1212 ?        SN   Oct16  23:33 /usr/libexec/openscap/probe_file
root      54729  0.0  2.0 1067484 679632 ?      SN   Nov26  23:36 /usr/libexec/openscap/probe_file
root      78028  0.0  0.0 1067484 1212 ?        SN   Oct09  23:49 /usr/libexec/openscap/probe_file
```

Bug description
----------------
In an installation that times out every time `openscap` is run (due to many files), sometimes there will be a lingering `probe_file` process that remains consuming memory until system reboot.

It seems the [SIGTERM signal sent](https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/wm_exec.c#L394-L398) on timeout is not successfully killing all `openscap` processes. 

Although this may be due to a third-party misbehaviour by `OpenSCAP` it may be advisable to adjust the way it is handled by Wazuh to achieve the expected `timeout` behaviour.

**Comment by jctello** [comment]
An user with a homemade database which consisted of a folder structure with millions of files found that there were several lingering `probe_file` processes running:
```
root       1365  0.2  2.1 1067484 695388 ?      SN   Dec06  23:42 /usr/libexec/openscap/probe_file
root       3564  0.1  2.1 1067484 716836 ?      SN   Dec01  23:42 /usr/libexec/openscap/probe_file
root       8773  0.0  0.0 1067484  384 ?        SN   Sep26  22:37 /usr/libexec/openscap/probe_file
root      10966  0.2  2.2 1133020 726812 ?      SN   Dec07  23:52 /usr/libexec/openscap/probe_file
root      29738  0.0  0.0 1133020 14000 ?       SN   Nov18  24:24 /usr/libexec/openscap/probe_file
root      33076  0.0  0.0 1067484 2284 ?        SN   Oct24  23:45 /usr/libexec/openscap/probe_file
root      50004  0.0  0.0 1067484 1212 ?        SN   Oct16  23:33 /usr/libexec/openscap/probe_file
root      54729  0.0  2.0 1067484 679632 ?      SN   Nov26  23:36 /usr/libexec/openscap/probe_file
root      78028  0.0  0.0 1067484 1212 ?        SN   Oct09  23:49 /usr/libexec/openscap/probe_file
root      89229  0.0  0.0 1067484 1212 ?        SN   Oct10  23:31 /usr/libexec/openscap/probe_file
root     101953  0.0  0.0 1067484 1212 ?        SN   Oct11  23:26 /usr/libexec/openscap/probe_file
root     103943  0.0  0.0 1133020 6232 ?        SN   Nov15  24:01 /usr/libexec/openscap/probe_file
root     109576  0.0  0.0 103328   868 pts/0    S+   15:01   0:00 grep open
root     113376  0.0  0.0 1067484 1212 ?        SN   Oct12  23:24 /usr/libexec/openscap/probe_file
root     118020  0.0  1.1 1133020 367612 ?      SN   Nov22  24:40 /usr/libexec/openscap/probe_file
root     123584  0.0  0.0 1133020 4256 ?        SN   Oct20  23:55 /usr/libexec/openscap/probe_file
```

Further investigation determined that the scan was never finishing and it was remedied by changing the policy file to not be recursive in the instructions that concerned the root `/` folder. 

However this revealed that the wodle was not correctly delivering the [SIGTERM signal](https://github.com/wazuh/wazuh/blob/3.7/src/wazuh_modules/wm_exec.c#L394-L398) which should be caused by the timeout. The issue has not been reproduced yet.

**Comment by DarkMatterCore** [comment]
After setting up OpenSCAP, integrating it with a Wazuh installation compiled from `3.9` under a CentOS 7 VM and setting it up to scan several bogus files (~1KiB each, around 100 thousand) with random data, I have been unable to reproduce this problem.

According to the logfile from the user that reported this issue, the timeout event is properly fired up because its corresponding message does appear on it, but these `probe_file` processes are not terminated.

The problem most likely has something to do with the `kill()` call, but it's hard to know without reproducing the problem. Its output is never analyzed, and it may as well be returning an error.

**Comment by albertomn86** [comment]
This issue could not be reproduced and will be closed. Feel free to reopen it if you find this issue again.
