### ISSUE TITLE
Make agent_control validate active response names instead of accepting just anything

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#214]
Right now, if in Wazuh 2.1.1 manager I correctly use agent_control to manually fire off an active response on an agent, it looks like this:

```
/var/ossec/bin/agent_control -b 3.4.5.6 -f win_route-null -u 005

Wazuh HIDS agent_control: Running active response "null-route′" n: 005
```
However, it also accepts the command and treats it as valid even if the active response to which I refer does not exist.  For example:

```
/var/ossec/bin/agent_control -b 3.4.5.6 -f NON-EXISTENT-ACTIVE-RESPONSE -u 005

Wazuh agent_control: Running active response 'NON-EXISTENT-ACTIVE-RESPONSE' on: 005
```

The agent id is properly validated and a nonexistent id will throw an error.  Please do the same for nonexistent active responses.  It would be helpful feedback to know when we are trying to use an active response that is not there.

Thanks!
Kevin Branch

**Comment by PSanchezR** [comment]
Hello branchnetconsulting,

First of all, thank you for your contribution. We have corrected this problem by displaying a message when the selected AR does not exist, you can find it at https://github.com/wazuh/wazuh/commit/81a768a1f4eac44404eb545f15f1b5c0be85d7a1 

Best regards.

Pablo Sánchez
