### ISSUE TITLE
Error remote upgrading agent 3.7.2

### ISSUE THREAD

**Issue by hregis** [wazuh/wazuh#2140]
## Bug report

**OS**
Debian 9

**Wazuh version**
3.7.2

**Wazuh API version**
3.7.2

**Install type**
manager

**Install method**
package

**Log sample**

```
Log sample
```

Bug description
----------------
Hello,

I just updated Wazuh Manager and Wazuh API from 3.7.1 to 3.7.2 (and kibana and others in 6.5.3)
when I ask the list of agents to update I see the list of Windows Servers in 3.7.1

`/var/ossec/bin/agent_upgrade -l`

but when I want to update a Windows agent I have this error message:

`/var/ossec/bin/agent_upgrade -a 018`

﻿﻿Error 1716: Error upgrading agent: Agent ver: v3.7.1 / Agent new ver: v3.7.1

Thanks

**Comment by hregis** [comment]
in fact, by listing the directory,

`/var/ossec/var/upgrade/`

I realized that the linux WPK has been updated, but not Windows,

```
wazuh_agent_v3.7.1_windows.wpk
wazuh_agent_v3.7.2_linux_x86_64.wpk

```
I downloaded it here and it works again.

https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/wpk-list.html

I close this ticket.

**Comment by hregis** [comment]
it's ok with this command line : 

`/var/ossec/var/upgrade# /var/ossec/bin/agent_upgrade -a 017 -f /var/ossec/var/upgrade/wazuh_agent_v3.7.2_windows.wpk -x upgrade.bat`

but the new WPK package is not detect automaticaly ?

Thanks for your help

**Comment by alberpilot** [comment]
Hello @hregis 

  You're right, we had an error in the file which manages the versions and now it's fixed. Please verify. 

Best regards,

**Comment by hregis** [comment]
@alberpilot 
thank you !
