### ISSUE TITLE
Vulnerability-detector can keep its database open between runs

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2141]
The following error has occurred between updates. Apparently, the database was in use when the update started.

> 2018/12/19 07:51:50 wazuh-modulesd:vulnerability-detector: INFO: (5452): Starting vulnerability scanning.
> 2018/12/19 07:51:50 wazuh-modulesd:vulnerability-detector: ERROR: (5405): SQL error: database is locked
> 2018/12/19 07:51:50 wazuh-modulesd:vulnerability-detector: ERROR: (5429): The agents information could not be processed.

**Comment by crolopez** [comment]
The real issue was because global.db is blocked while other processes write on it. For this reason, vulnerability-detector shows this error when trying to consult it to get information from the agents.

Currently it only makes one attempt before showing error.

**Comment by albertomn86** [comment]
Solved in https://github.com/wazuh/wazuh/pull/2148
