### ISSUE TITLE
 Service: inspector  -  Could not connect to the endpoint URL Warning message In Wazuh Manager

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21419]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager | Packages | AmazonLinux 

Testing [E2E Ux tests - Demo Enviroment](https://github.com/wazuh/wazuh/issues/21356)
It was found the following log in 2 Manager clusters [WazuhMasterEnv1, WazuhMasterEnv2] :

```
2024/01/12 00:15:26 wazuh-modulesd:aws-s3: WARNING: Service: inspector  -  Returned exit code 12
2024/01/12 00:15:26 wazuh-modulesd:aws-s3: WARNING: Service: inspector  -  Could not connect to the endpoint URL: "https://inspector.af-south-1.amazonaws.com/"|
```

Further research should be done

**Comment by GGP1** [comment]
## Update

I started analyzing what might be causing the issue

**Comment by GGP1** [comment]
## Update

I started analyzing what might be causing the issue and the source code related.

**Comment by GGP1** [comment]
## Update

I started analyzing what might be causing the issue and the source code related to the AWS wodle.

**Comment by GGP1** [comment]
## Update

The error is related to the fact that the AWS inspector service is not available in the region that the user configured

```console
gasti@pop-os:~/work/wazuh$ curl https://inspector.af-south-1.amazonaws.com
curl: (6) Could not resolve host: inspector.af-south-1.amazonaws.com
```

Given that the AWS CLI version 2 has a command [inspector2](https://docs.aws.amazon.com/cli/latest/reference/inspector2/) I tried modifying the address

```console
gasti@pop-os:~/work/wazuh$ curl https://inspector2.af-south-1.amazonaws.com
{"message":"Unable to determine service/operation name to be authorized"}
```

but it requires authorization and it isn't what we are using.

To check which regions have the service available, I created the following bash script

<details><summary>script</summary>

```bash
#/bin/bash

declare -a AWS_REGIONS=('af-south-1' 'ap-east-1' 'ap-northeast-1' 'ap-northeast-2'
                        'ap-northeast-3' 'ap-south-1' 'ap-south-2'
                        'ap-southeast-1' 'ap-southeast-2' 'ap-southeast-3'
		       	'ap-southeast-4' 'ca-central-1' 'eu-central-1'
                        'eu-central-2' 'eu-north-1' 'eu-south-1' 'eu-south-2'
		       	'eu-west-1' 'eu-west-2' 'eu-west-3' 'il-central-1'
                        'me-central-1' 'me-south-1' 'sa-east-1' 'us-east-1' 'us-east-2'
		       	'us-west-1' 'us-west-2'
                        )

printf "| Region | Status code |\n|---|---|\n"

for region in "${AWS_REGIONS[@]}"
do
	echo "| $region | $(curl -s https://inspector.$region.amazonaws.com) |"
done
```

</details>

### Results

The results indicate that the regions supported are the ones we had before https://github.com/wazuh/wazuh/issues/20539.

> Empty status codes mean that the host is not reachable.

| Region | Status code |
|---|---|
| af-south-1 | |
| ap-east-1 | |
| ap-northeast-1 | 200 |
| ap-northeast-2 | 200 |
| ap-northeast-3 | |
| ap-south-1 | 200 |
| ap-south-2 | |
| ap-southeast-1 |  |
| ap-southeast-2 | 200 |
| ap-southeast-3 | |
| ap-southeast-4 | |
| ca-central-1 | |
| eu-central-1 | 200 |
| eu-central-2 | |
| eu-north-1 | 200 |
| eu-south-1 | |
| eu-south-2 | |
| eu-west-1 | 200 |
| eu-west-2 | 200 |
| eu-west-3 | |
| il-central-1 | |
| me-central-1 | |
| me-south-1 | |
| sa-east-1 | |
| us-east-1 | 200 |
| us-east-2 | 200 |
| us-west-1 | 200 |
| us-west-2 | 200 |

We should either remove support for these regions from the inspector service or remove them entirely if we can't provide the functionality for them.

**Comment by GGP1** [comment]
## Update

The list of supported endpoints for the AWS **inspector** services is detailed [here](https://docs.aws.amazon.com/general/latest/gr/inspector.html#inspector_region). 

The **inspector2** service is supported in many more regions, [here](https://docs.aws.amazon.com/general/latest/gr/inspector2.html#inspector2_region) is the list. The regions that do not have an endpoint are:

- ap-south-2
- ap-southeast-4
- eu-south-2
- il-central-1
- me-central-1

We should aim to migrate to the version 2 of this service to support most regions.

I updated the aws-s3 script to reject regions that are not supported when using the inspector service.
