### ISSUE TITLE
Remove XFail mark due to XPassed test on endpoint `GET /manager/version/check` for the `test_manager_endpoint` test

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#21417]
|Wazuh version|Component|
|---|--- |
| 4.8.0 | API |

### Description

During the [Release 4.8.0 - Alpha 2 - API integration tests #21408](https://github.com/wazuh/wazuh/issues/21408) it was found that the test `test_manager_endpoint` had an XPass for the endpoint `GET /manager/version/check`.

These tests were merged in this [PR](https://github.com/wazuh/wazuh/pull/19978) and were marked as XFailed due to the CTI being unreachable. Having an Xpass means that the CTI is reachable and working as expected. 

Issue should tend to change the XFail mark to an XPass mark.

**Comment by GGP1** [comment]
## Update

Removed the `xfail` mark from the `GET /manager/version/check` test case and ran the test to verify that everything works as expected.
