### ISSUE TITLE
Incorrect installation link clarification

### ISSUE THREAD

**Issue by SeyiSoneye** [wazuh/wazuh#21424]
Hello team, 

I am working on  Release 4.8.0 - Alpha 2 - E2E UX tests - Wazuh Indexer [#21354 ](https://github.com/wazuh/wazuh/issues/21354) and I encountered the following issues and require some clarification to successfully proceed with testing:

1. I encounter the following error when trying to Install the Wazuh module for Filebeat (during Wazuh server installation).
```
root@server1:/home/vagrant# curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.4.tar.gz | tar -xvz -C /usr/share/filebeat/module

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
I checked and the error is from the URL to grab the gzip. 
```
root@server2:/home/vagrant# curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.4.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>4.x/filebeat/wazuh-filebeat-0.4.tar.gz</Key><RequestId>0CFHGQ0ZZHHN7QSK</RequestId><HostId>6YLzx/K5sVnV9S0MdlmvhRPdVfDR1i6aoiHFWeZZi+yfR2Ix1KvsgceewOID4jyTMBEAvncONXI=</HostId></Error>
```
same when trying packages-dev
```
root@server2:/home/vagrant# curl -s https://packages-dev.wazuh.com/4.x/filebeat/wazuh-filebeat
-0.4.tar.gz
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>4.x/filebeat/wazuh-filebeat-0.4.tar.gz</Key><RequestId>PQA5BJ0JZ7F89P2W</RequestId><HostId>dR67TG80hqKAivfzlTeqN1LaOv1Lx9qQ5+hSHZlU2muYqdlALMRVjPjvmCrvjEGcYWBdX2fuc/Q=</HostId></Error>
```

Additionally, I want to confirm I can update the linked step-by-step guide for the indexer installation to https://documentation-dev.wazuh.com/v4.8.0-alpha2/installation-guide/wazuh-indexer/step-by-step.html under deployment requirements.

**Comment by SeyiSoneye** [comment]
Error

**Comment by rauldpm** [comment]
@SeyiSoneye I see that you changed the issue status from Done to Blocked, are all of your questions clear? If so, change the status to Done again, please
