### ISSUE TITLE
Please add msg_dropped metric to wazuh-agentd.state file to account for event drops due to agent send buffer full

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#21427]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| any | agent state file | Agent | na| any |

While the `wazuh-agentd.state` file on Wazuh agents includes some counters like `msg_count` and `msg_sent`, a counter for dropped messages is conspicuously absent.  We have drop counters in other state files like `wazuh-logcollector.state` on agent/manager, and on manager they are present in `wazuh-remoted.state` and `wazuh-analysisd.state`.  Without the ability to account for agent-side event drops due to send buffer being full, we really cannot measure how reliably our agents are able to convey their events to the Wazuh manager for analysis.  Looking at the underlying code, it does not appear it would be difficult to introduce a `msg_dropped` metric to the `wazuh-agentd.state` file.  Please do so.

See this Slack community thread on the topic:
https://wazuh.slack.com/archives/C0A933R8E/p1704322027385819

Thank you for considering this request,
Kevin Branch

**Comment by vikman90** [comment]
Hi @branchnetconsulting, I've just added this task to the roadmap.

Thank you for reporting that!

Best regards.

**Comment by havidarou** [comment]
This will be address in this issue https://github.com/wazuh/wazuh/issues/22677
