### ISSUE TITLE
Wrong sudoers check in Debian 12 SCA

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#21421]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | SCA | Manager/Agent | Packages | At least Debian, all systems should be checked |

## Description

An SCA bug has been found in the https://github.com/wazuh/wazuh/issues/21361 testing as a SCA policy is being marked as Not Applicable

![image](https://github.com/wazuh/wazuh/assets/14913942/916865c6-a80a-461f-8fe0-f4c89de02c25)

The /etc/sudoers is a file and not a directory, the directory should be /etc/sudoers.d/ but the Checks sections use the file

![image](https://github.com/wazuh/wazuh/assets/14913942/ee3a0a0d-0ab8-43d9-aa97-1c1b04bd1005)

- https://github.com/wazuh/wazuh/blob/v4.8.0-alpha2/ruleset/sca/debian/cis_debian12.yml#L562-L578

The 33026 rule also checks the wrong file, thanks @jnasselle for the reference

- https://github.com/wazuh/wazuh/blob/v4.8.0-alpha2/ruleset/sca/debian/cis_debian12.yml#L559-L560

Also, should this rule be cataloged as Not applicable instead of Failed?

> [!NOTE]
> This is also present in 4.7.2

**Comment by jk-olaoluwa** [comment]
This issue has been resolved here - https://github.com/wazuh/wazuh/pull/21463/commits/345ff81d33a2716c049bf877004c73080c063862

**Comment by ooniagbi** [comment]
LGTM!
