### ISSUE TITLE
CentOS7 not gettgin results for Vulnerability scan

### ISSUE THREAD

**Issue by 4lph40iii** [wazuh/wazuh#21433]
I have installed Wazuh OVS package and onboarded mix of Windows, ubuntu and CentOS. In CentOS Agent was added and in active status but still no results in the vulnerability scan. 

Can you please help me on this ?

**Comment by 4lph40iii** [comment]
Hi Thanks for the reply,

I was able to sort out the issue after enable the RHEL.

Thanks again for your help.

Best regards ,

Rajith

**Comment by MiguelazoDS** [comment]
Hi @4lph40iii, 

I missed this comment. Glad it worked, regards!
