### ISSUE TITLE
Inconsistency in SCA macOS version filename

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#21440]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | SCA | Agent | Packages| macOS Sonoma 14.1.2 |

Source issue: https://github.com/wazuh/wazuh/issues/21361

It has been detected that the SCA macOS Darwin 23 policy specifies `14.0`, this is not correct since macOS Sonoma is currently in version `14.1.2`, which implies a version inconsistency, this file should be renamed to `14.x` like it is done in the Darwin 22 directory or add policies for each patch/minor

- https://github.com/wazuh/wazuh/blob/master/ruleset/sca/darwin/22/cis_apple_macOS_13.x.yml
- https://github.com/wazuh/wazuh/blob/master/ruleset/sca/darwin/23/cis_apple_macOS_14.0.yml

**Comment by Johnng007** [comment]
LGTM
