### ISSUE TITLE
Amazon CloudWatch Integration Error - NOT WORKING

### ISSUE THREAD

**Issue by SamsonIdowu** [wazuh/wazuh#21467]
Hello, kindly look into the Amazon CloudWatch integration as CloudWatch logs are not being fetched.

Below are logs from the Wazuh manager showing that the logs are not ingested by the Wazuh manager and as well as the Wazuh agent, despite all configurations, dependencies being properly set as stated in the [documentation](https://documentation-dev.wazuh.com/v4.8.0-alpha2/cloud-security/amazon/services/supported-services/cloudwatchlogs.html):

<details>
<summary>ossec.log:</summary>
<pre>
[root@wazuh-server ~]# tail -f /var/ossec/logs/ossec.log
2024/01/16 16:51:00 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/01/16 16:51:00 wazuh-modulesd:aws-s3: INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: default)
2024/01/16 16:54:52 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2024/01/16 16:54:52 wazuh-modulesd:aws-s3: WARNING: Interval overtaken.
2024/01/16 16:54:52 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/01/16 16:54:52 wazuh-modulesd:aws-s3: INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: default)
2024/01/16 16:59:02 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2024/01/16 16:59:02 wazuh-modulesd:aws-s3: WARNING: Interval overtaken.
2024/01/16 16:59:02 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/01/16 16:59:02 wazuh-modulesd:aws-s3: INFO: Executing Service Analysis: (Service: cloudwatchlogs, Profile: default)
</pre>
</details>

<details>
<summary>archives.log:</summary>
<pre>
[root@wazuh-server ~]# tail -f /var/ossec/logs/archives/archives.log
udp6 :::5355 :::* 749/systemd-resolve
tcp6 127.0.0.1:9200 :::* 18346/java
tcp6 ::1:9200 :::* 18346/java
tcp6 127.0.0.1:9300 :::* 18346/java
tcp6 ::1:9300 :::* 18346/java
udp6 :::47066 :::* 56926/avahi-daemon
udp 0.0.0.0:47944 0.0.0.0:* 56926/avahi-daemon
tcp 0.0.0.0:55000 0.0.0.0:* 67787/python3
2024 Jan 18 11:12:18 wazuh-server->/var/log/audit/audit.log type=SERVICE_START msg=audit(1705572738.159:2243): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
2024 Jan 18 11:12:28 wazuh-server->/var/log/audit/audit.log type=SERVICE_STOP msg=audit(1705572748.249:2244): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
2024 Jan 18 11:12:34 wazuh-server->/var/log/audit/audit.log type=SERVICE_START msg=audit(1705572754.006:2245): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
2024 Jan 18 11:12:44 wazuh-server->/var/log/audit/audit.log type=SERVICE_STOP msg=audit(1705572764.074:2246): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
2024 Jan 18 11:14:17 (fedora) any->/var/log/audit/audit.log type=SERVICE_START msg=audit(1705572856.399:1865): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-dispatcher comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'UID="root" AUID="unset"
^C
[root@wazuh-server ~]#
</pre>
</details>

More details about the issue can be found in [Release 4.8.0 - Alpha 2 - E2E UX tests - Amazon Cloudwatch Logs integration #21373](https://github.com/wazuh/wazuh/issues/21373#issue-2076963856).

**Comment by javiersanchz** [comment]
## Update 

<details>

<summary>Vagrant structure</summary>

```console
Vagrant.configure("2") do |config|
  # Configuración de la máquina virtual
  config.vm.box = "bento/ubuntu-22.04" 
  config.vm.network "private_network", type: "dhcp"  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"  
    vb.cpus = 4  
  end
end
```
</details>

<details>

<summary>Wazuh server</summary>

```console
vagrant@vagrant:~$ ip a && cat /etc/os-release
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:3b:cf:90 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.0.2.15/24 metric 100 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86288sec preferred_lft 86288sec
    inet6 fe80::a00:27ff:fe3b:cf90/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:53:11:0f brd ff:ff:ff:ff:ff:ff
    altname enp0s8
    inet 192.168.56.5/24 metric 100 brd 192.168.56.255 scope global dynamic eth1
       valid_lft 488sec preferred_lft 488sec
    inet6 fe80::a00:27ff:fe53:110f/64 scope link 
       valid_lft forever preferred_lft forever
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

**Comment by GGP1** [comment]
## Review

The investigation demonstrates that the CloudWatchLogs service works as expected in **4.8.0**. The error must have been caused by a misconfiguration or lack of permissions. LGTM!

> Since this issue did not focus on the dashboard, we should validate that the events are appearing in the UI in https://github.com/wazuh/wazuh/issues/21472

**Comment by Selutario** [comment]
LGTM

**Comment by Meraz78** [comment]
can someone please provide the decoders and rules for this integration
