### ISSUE TITLE
Remove all references of the legacy vulnerability detector module - Framework /API changes

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21461]
## Description

Related issue #21303.

The vulnerability detector module has been refactored and the code of the legacy module has been removed.
Nevertheless, there are still some references to the old module that should be removed.
Here are some items but a deep search should be done during the development of the issue in case some references are missing:

- api/api/spec/spec.yaml (references to `vuln_cves`)

## DoD

- [x] Remove all the dangling references to the old module of the code.
- [x] Make sure everything keeps working as expected.
- [x] CI Pass

**Comment by pereyra-m** [comment]
## Update

Here is an example of a test that fails due to these changes

https://github.com/wazuh/wazuh/actions/runs/7550651708/job/20556615366?pr=21454

**Comment by mhamra** [comment]
### UPDATE
The following [PR comment](https://github.com/wazuh/wazuh/pull/21542#issuecomment-1904953319) shows the test_api tier 0-1 execution results using the `wazuh_testing` package version without references to vulnerability detector. All tests passed successfully.

**Comment by Selutario** [comment]
ETA was postponed after requesting some changes. New ETA: 25/01/2024.
