### ISSUE TITLE
shibabarma863@gmli.com

### ISSUE THREAD

**Issue by Bapi1982** [wazuh/wazuh#21465]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Bapi1982** [comment]
![Uploading 405818420_759912475970133_3832316198895029077_n.jpg…]()

**Comment by Dwordcito** [comment]
Please make the issue more descriptive! thank you! reopen if necessary.
