### ISSUE TITLE
fix and improve corrupted_rules_file AIT tests

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#21484]
|Component|
|---|
| API |
## Description
These tavern files call the PUT /rules/files/{filename}, setting the data parameter with `api/test/integration/common.yaml.corrupted_rules_file` content.

- `api/test/integration/test_manager_endpoints.tavern.yaml`
- `api/test/integration/test_cluster_endpoints.tavern.yaml`

These tests are not checking if an error is returned. The function `framework/wazuh/core/utils.validate_wazuh_xml` is called inside the `framework/wazuh/rule.upload_rule_file` function, but does not raise an exception.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The tests are purposefully uploading a corrupted rule file to trigger and error when validating the manager/cluster configuration. The file is a valid XML that has an invalid level `XXX`, thus the [validate_wazuh_xml()](https://github.com/wazuh/wazuh/blob/cdc44097c91876950185faddbff7e6902a0ee5e1/framework/wazuh/core/utils.py#L1971) does not return an error but [validate_ossec_conf()](https://github.com/wazuh/wazuh/blob/cdc44097c91876950185faddbff7e6902a0ee5e1/framework/wazuh/core/manager.py#L174) does. 

<details><summary><code>PUT /rules/files/new-rules_corrupted.xml</code></summary>

Body: 

```xml
<!-- Local rules -->
 <group name="local,">
 <!--   NEW RULE    -->
   <rule id="111111" level="XXX">
       <if_sid>5716</if_sid>
       <srcip>1.1.1.1</srcip>
       <description>sshd: authentication failed from IP 1.1.1.1.</description>
       <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
    </rule>
</group>
```

Response:

```json
{
    "data": {
        "affected_items": [
            "etc/rules/new-rules_corrupted.xml"
        ],
        "total_affected_items": 1,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "Rule was successfully uploaded",
    "error": 0
}
```

</details>


<details><summary><code>GET /manager/configuration/validation</code></summary>

```json
{
    "data": {
        "affected_items": [],
        "total_affected_items": 0,
        "total_failed_items": 1,
        "failed_items": [
            {
                "error": {
                    "code": 1908,
                    "message": "Error validating configuration: No rule id or level specified for rule '0'., (1220): Error loading the rules: 'etc/rules/new-rules_corrupted.xml'.",
                    "remediation": "Please, fix the corrupted files"
                },
                "id": [
                    "master-node"
                ]
            }
        ]
    },
    "message": "Could not check validation in any node",
    "error": 1
}
```

</details>

This behavior is expected and shouldn't be modified. I just made some modifications so both manager and cluster tests are equal.
