### ISSUE TITLE
Increase of values in FD Plot in Manager in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21512]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager | Packages | CentOS Manager |

Testing: [Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP ](https://github.com/wazuh/wazuh/issues/21502)

It was possible to see in CentOS Manager & Ubuntu Agent
Increase of values in FD Plot in Manager in stress test:

### Manager
v4.8.0-alpha2 https://github.com/wazuh/wazuh/issues/21502
![image](https://github.com/wazuh/wazuh/assets/125690423/968ce5e7-7d06-4ecb-ae11-0068854e7e22)

v4.7.2-rc2 https://github.com/wazuh/wazuh/issues/21268
![image](https://github.com/wazuh/wazuh/assets/125690423/1d650958-59b6-4bf1-8cbb-b50f5770b52f)

It should be assessed whether this behavior is expected and whether it affects the proper functioning of the product or not.

**Comment by JorgeMarinoDev** [comment]
## Analysis :green_circle: 

  - [ ] Checked config files are identical.
 
## Some Resuilts

![image](https://github.com/wazuh/wazuh/assets/117848458/e01aa8db-5da4-4d46-a737-a869ed4d00db)

## Conclusion

Nothing reflected here means that FD increase is a problem.
Disregard.
