### ISSUE TITLE
CPU usage increase in Manager Syscheck 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21513]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager| Packages | centOS Manager |

### Description

During [Syscheck footprint testing](https://github.com/wazuh/wazuh/issues/21503) it has been detected an increase in the CPU usage for syscheck module. Achieving 120% peaks.
 
We can see this increase comparing to the last release 4.7.2

| 4.8.0 | 4.7.2-RC1 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/5bf17c257053b2c864b5e38409734bedb4279963a5d671ee143a8d7dca7dc1bb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343736382d333630306d2f42343736385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343736385f6d616e616765722d7072652d72656c656173655f4350552e706e67) | ![IMAGE](https://camo.githubusercontent.com/bb086dbb0e8c8237588e9f4c905bdbe4e98f446bfe471579520e23006012343c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343731352d333630306d2f42343731355f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343731355f6d616e616765722d7072652d72656c656173655f4350552e706e67) |
 

### Evidences
- [Logs and Configurations](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4768-3600m/B4768_manager_centos/logs/ossec_Test_stress_B4768_manager_2024-01-17.zip)
- [CSV Manager process data](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4768-3600m/B4768_manager_centos/data/monitor-manager-Test_stress_B4768_manager-pre-release.csv)

**Comment by Dwordcito** [comment]
@vikman90 which team will analyze this issue? I return it to triage.
