### ISSUE TITLE
`wazuh-manager` Error sending message to provider

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#21519]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.8.0-alpha2 | Wazuh | Manager | Packages | CentOS Manager |

Testing: 

- [Footprint Metrics - SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21486)
- [Footprint Metrics - VULNERABILITY-DETECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21488)

This error has appeared in the logs: 

```console
:router ERROR: Error sending message to provider: Error parsing message, 1: 585: error: invalid number: "-1", constant does not fit [0; 4294967295]
```

---

Testing:

- [Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/21495)

This error has appeared in the logs: 

```console
:router ERROR: Error sending message to provider: Error parsing message, 1: 286: error: unknown field: dhcp
```

> Analysis is required

**Comment by MiguelazoDS** [comment]
Hi @rafabailon 

The first log error was fixed here 

https://github.com/wazuh/wazuh/issues/21340

The second log error has a WA here

https://github.com/wazuh/wazuh/issues/21240

and will be addressed here 

https://github.com/wazuh/wazuh/issues/21459
