### ISSUE TITLE
Fall in the second part of the graphs for VMS, USS, and RSS values

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#21511]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Agent| Packages | CentOS & Ubuntu Agent |

Testing: [Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS,OPEN-SCAP ](https://github.com/wazuh/wazuh/issues/21502)

It was possible to see in CentOS & Ubuntu Agent
The following fall in the values of VMS, USS, and RSS in the second part of the plot:

### CentOS Agent
v4.8.0-alpha2 https://github.com/wazuh/wazuh/issues/21502
![image](https://github.com/wazuh/wazuh/assets/125690423/7c8633d5-87c6-4e21-93aa-62f8841bff76)
![image](https://github.com/wazuh/wazuh/assets/125690423/b8f5e9d7-b472-49dc-8bce-c3656146cbf2)
![image](https://github.com/wazuh/wazuh/assets/125690423/2fb4b27d-bb29-4abe-95e7-d3d78f0f8620)

v4.7.2-rc2 https://github.com/wazuh/wazuh/issues/21268
![image](https://github.com/wazuh/wazuh/assets/125690423/bd0d55d0-e933-42b2-943d-33e5e6525f98)
![image](https://github.com/wazuh/wazuh/assets/125690423/0c498086-fc0e-4de6-bec5-a0de67ffb038)
![image](https://github.com/wazuh/wazuh/assets/125690423/f941f1f9-7557-4e83-87e5-c6f45370cdab)

### Ubuntu Agent
v4.8.0-alpha2 https://github.com/wazuh/wazuh/issues/21502
![image](https://github.com/wazuh/wazuh/assets/125690423/88417060-7863-4ed0-bc32-2d106d3bc7a8)
![image](https://github.com/wazuh/wazuh/assets/125690423/487990da-905f-4fe9-a994-cd5240b2e50b)
![image](https://github.com/wazuh/wazuh/assets/125690423/61cb967e-74fc-44ed-8bf0-b3f77002f5c7)

v4.7.2-rc2 https://github.com/wazuh/wazuh/issues/21268
![image](https://github.com/wazuh/wazuh/assets/125690423/3bf76504-2292-4557-bc83-aeacabde7e28)
![image](https://github.com/wazuh/wazuh/assets/125690423/ff939b09-3f62-4e14-b517-3dd2a989bbe9)
![image](https://github.com/wazuh/wazuh/assets/125690423/da77bf25-6614-441b-a1a9-5b9a354ef4f8)

It should be assessed whether this behavior is expected and whether it affects the proper functioning of the product or not.

**Comment by nbertoldo** [comment]
After analysing the reports, the drop in memory usage in the second part of the test seems to be related to a drop in the number of events generated.  The graph shows a change in the slope at this stage of the test:

![generated_events](https://github.com/wazuh/wazuh/assets/117279646/47a8e0f3-2a57-4129-a130-43bb8f20adcf)

The same for the buffered events:

![buffered_events](https://github.com/wazuh/wazuh/assets/117279646/b63abaa1-a700-4a82-ac94-a38203e4c96f)

With the available evidence, it is not possible to identify the reason for this decrease, nor is there any sign of a performance issue with the agent.

**Comment by nbertoldo** [comment]
Continuing with the [previous analysis](https://github.com/wazuh/wazuh/issues/21511#issuecomment-1908893292), it can be seen in `docker.log` a decrease in the number of times this test is executed during the same period in which the memory usage (and the generation of events) falls. 

<google-sheets-html-origin>
 Stage | Start | End | Minutes | Time % | Test Runs | Runs %
-- | -- | -- | -- | -- | -- | --
1 | 2024-01-15 17:40:26 | 2024-01-16 22:51:26 | 1751 | 69.48 | 146568 | 78.57
2 | 2024-01-16 22:51:27 | 2024-01-17 11:40:36 | 769 | 30.52 | 39974 | 21.43

And considering that in this test most of the events generated correspond to `osquery` and `docker`, a decrease in total event generation and memory usage is expected.
