### ISSUE TITLE
Decrease of `wazuh-modulesd` Pattern in the `Disk` Plot for `ALL` Stress Test

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#21528]
| Wazuh Version | Install Type | Install Method | Platform |
| --- | --- | --- | --- |
| 4.8.0-alpha2 | Manager | Packages | CentOS |

## Description

During the analysis carried out in the stress test of [ALL](https://github.com/wazuh/wazuh/issues/21495) it has been observed, in comparison with the same test in [4.7.2 RC 2 ](https://github.com/wazuh/wazuh/issues/21280), that the values of `wazuh-modulesd` have decreased a lot in the manager.

- **4.8.0-alpha2**:

![image](https://github.com/wazuh/wazuh/assets/54536265/51426cfe-df8f-4e2a-885e-e04ade92539f)

![image](https://github.com/wazuh/wazuh/assets/54536265/f9e120e4-c40d-47bf-963a-cf05aa530bed)

![image](https://github.com/wazuh/wazuh/assets/54536265/806c9ab4-01c7-4a48-bd49-d1a078315c84)

- **4.7.2-rc2**:

![image](https://github.com/wazuh/wazuh/assets/54536265/2c4d25a4-f306-4cc6-af58-b41e9a2ee851)

![image](https://github.com/wazuh/wazuh/assets/54536265/9674870b-4a30-4df7-b10d-613c7818264a)

![image](https://github.com/wazuh/wazuh/assets/54536265/2b4b544a-12e2-43ea-9907-3c77e6772276)

**Comment by Dwordcito** [comment]
@wazuh/data-pirates time box of 2 days ETA for this issue analysis.

**Comment by pereyra-m** [comment]
These findings can also be explained by https://github.com/wazuh/wazuh/issues/21521#issuecomment-1915920299

**Comment by Dwordcito** [comment]
LGTM
