### ISSUE TITLE
Disk, Disk_Read - decrease - on Linux Agents on 4.8.0-Alpha2 

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21527]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh component | Agent | Packages | Centos & Ubuntu |

## Description

During testing issue https://github.com/wazuh/wazuh/issues/21494, a decrease in `Disk_Read` was detected in both linux agents. Also an overall Disk usage decrease was detected in Centos agent.

- Centos Agent
   - 4.7.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4745-3600m/B4745_agent_centos/plots/monitor-agent-Test_stress_B4745_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4745-3600m/B4745_agent_centos/plots/monitor-agent-Test_stress_B4745_centos-pre-release_Disk_Read.png) 
   - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4776-3600m/B4776_agent_centos/plots/monitor-agent-Test_stress_B4776_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4776-3600m/B4776_agent_centos/plots/monitor-agent-Test_stress_B4776_centos-pre-release_Disk_Read.png)

- Ubuntu Agent
   - 4.7.2
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.7.2/B4745-3600m/B4745_agent_ubuntu/plots/monitor-agent-Test_stress_B4745_ubuntu-pre-release_Disk_Read.png)
   - 4.8.0
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4776-3600m/B4776_agent_ubuntu/plots/monitor-agent-Test_stress_B4776_ubuntu-pre-release_Disk_Read.png)

**Comment by Rebits** [comment]
These discrepancies were also observed in https://github.com/wazuh/wazuh/issues/21499 for manager host

We can see that Disk read/write operations decreased in comparison with 4.7.2-rc1


|  Metric | 4.8.0 | 4.7.2-RC1 |
| --- | --- | --- |
| Disk Read | ![IMAGE](https://camo.githubusercontent.com/cb4877e1af645abd01a315f02f1ee812e694c6f3798ce38d572784f0835031d6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) | ![IMAGE](https://camo.githubusercontent.com/441199555adad4e2f5de0d00ad222e65f7c2dfade9d296ac5079c279f50149e1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) | 
| Disk Write | ![IMAGE](https://camo.githubusercontent.com/09d8a4ab156e60f5d5e19c535acefa7bf6fd5e1712b2fc5bebbbade2a68891cc/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) | ![IMAGE](https://camo.githubusercontent.com/609fd7752ba68f464fafc74b28fe356b8acc970e4e688f9decce5955ec3d006f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67) |

**Comment by cborla** [comment]
## Analysis

### Events decoded by versions
![image](https://github.com/wazuh/wazuh/assets/41765669/c1da4270-9a8f-4bcf-9728-5e4c74da1c5f)
As can be seen in the spreadsheet, there is not a big difference between the decoded events between the 2 versions, it is only observed that in 4.8.0 less agent events were droppedpearon than in 4.7.2.
Therefore, the decrease in disk usage is not associated with the number of events processed.

**Comment by cborla** [comment]
> These discrepancies were also observed in #21499 for manager host
> 
> We can see that Disk read/write operations decreased in comparison with 4.7.2-rc1
> 
> Metric	4.8.0	4.7.2-RC1
> Disk Read	![IMAGE](https://camo.githubusercontent.com/cb4877e1af645abd01a315f02f1ee812e694c6f3798ce38d572784f0835031d6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67)	![IMAGE](https://camo.githubusercontent.com/441199555adad4e2f5de0d00ad222e65f7c2dfade9d296ac5079c279f50149e1/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67)
> Disk Write	![IMAGE](https://camo.githubusercontent.com/09d8a4ab156e60f5d5e19c535acefa7bf6fd5e1712b2fc5bebbbade2a68891cc/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)	![IMAGE](https://camo.githubusercontent.com/609fd7752ba68f464fafc74b28fe356b8acc970e4e688f9decce5955ec3d006f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f4469736b5f5772697474656e2e706e67)
> At the same time, we can see a decrease of read and write operations
> 
> Metric	4.8.0	4.7.2-RC1
> Read Ops	![IMAGE](https://camo.githubusercontent.com/941a1bee78a2900dac294e9d03f0ece336829c1ca91f5fe44853470a051a3e8f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f526561645f4f70732e706e67)	![IMAGE](https://camo.githubusercontent.com/eee46744352477d186ab3d49248af1a9f8123aefeb1efafc4c251646a49bdfed /68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f526561645f4f70732e706e67)
> Write Ops	![IMAGE](https://camo.githubusercontent.com/17547e4e48225321c78768471c82245d959cb7530dca43d72d9e7a1aca6ad709/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343738315f6d616e616765722d7072652d72656c656173655f57726974655f4f70732e706e67)	![IMAGE](https://camo.githubusercontent.com/934adef7d9a0cd627e5f22e184bceb42aeddc018e2d0b5fdbbf2db3f59898ac5/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343732385f6d616e616765722d7072652d72656c656173655f57726974655f4f70732e706e67)

Any observation of decreased events, disk read/write and cpu usage, made on the manager, can be attributed to the case that vulnarability detector is not being stressed as of 4.8.0 alpha 2. Related [comment](https://github.com/wazuh/wazuh/issues/21523#issuecomment-1911103432)
