### ISSUE TITLE
Engine - Update core helper tests

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#21537]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Our current implementation of tests for the builders extensively duplicates code, making small changes in the builders unnecessary mechanical and repetitive work.

We need to improve the test implementation to use parametrized tests with the use cases as input data where applicable.

## Tasks
- [x] Internal helper
- [x] KVDB
- [x] IP
- [x] Transform array

**Comment by JavierBejMen** [comment]
## Update
Added str transform helper tests

**Comment by JavierBejMen** [comment]
## Update
- Added int calc helper tests
- Added json transformation helper tests
- Added regex extrac helper tests

**Comment by JavierBejMen** [comment]
## Update
- Added hash map helper tests
- Added get key/value helper tests
- Added ip version helper tests
- Added epoch helper tests
- Added array split string helper tests

**Comment by JcabreraC** [comment]
This issue has been divided by the size of the issue.
#21708

**Comment by JavierBejMen** [comment]
## Update
- Added kvdb decode bitmask test
- Minor fix in string split and rename helper
- Added active response helper tests
- Added upgrade confirmation helper tests
- Working on injected builder dependencies on tests (gmock leak)
