### ISSUE TITLE
DroppedEvents - decrease - on Manager on 4.8.0 - Alpha2

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21533]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh | Manager| Packages | centOS Manager |

### Description

During [All-Except-Logcollector footprint testing](https://github.com/wazuh/wazuh/issues/21499#) it has been detected an decrease in the dropped events in relation with the 4.7.2-RC1 results

| Metric | 4.8.0 | 4.7.2-RC1 |
| --- | --- | --- |
| Dropped Events | ![IMAGE](https://camo.githubusercontent.com/69606997f1c5379ff2d40b95be35825f5810595651e26bef51ce20e2ff0d6b6e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343738312d333630306d2f42343738315f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343738315f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67) | ![IMAGE](https://camo.githubusercontent.com/8d780098a30d529dd162de91fecc41281b37f2ab3eb179e520fde159709d5203/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732382d333630306d2f42343732385f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343732385f6d616e616765725f616e616c79736973645f6576656e74735f44726f707065645f6576656e74732e706e67) |

### Evidences

- [Configurations and Logs](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4781-3600m/B4781_manager_centos/logs/ossec_Test_stress_B4781_manager_2024-01-17.zip)
- [Monitoring Data](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B4781-3600m/B4781_manager_centos/data/Test_stress_B4781_manager_analysisd_events.csv)

**Comment by LucioDonda** [comment]
A decrease in dropped events is a good thing. Is it necessary to find what could have caused this, even though this is an objective of almost every new feature?
c.c. @Rebits @vikman90

**Comment by vikman90** [comment]
@LucioDonda This issue can be ignored, but let us keep it in mind in case we hear more concerns about an eventual increase in the number of dropped events. I mean, could this have been a coincidence?
