### ISSUE TITLE
router: ERROR: Error sending message to provider: Error parsing message 1: 563: error: invalid number: "-1960568724"

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21539]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha1 | Vulnerability Detector | Manager | Packages | Ubuntu 22 |

### Description

During https://github.com/wazuh/wazuh-qa/issues/4369, it has been detected the following error in the manager
```
2024/01/17 17:52:11 :router: ERROR: Error sending message to provider: Error parsing message, 1: 563: error: invalid number: "-1960568724", constant does not fit [0; 4294967295]
```

This was produced intermediately after installing nmap package in a centOS 7 agent ([nmap-640](https://download.cf.centos.org/centos/7/os/x86_64/Packages/nmap-6.40-19.el7.x86_64.rpm))
After error, no vulnerability alerts were triggered in the environment

Maybe solved by https://github.com/wazuh/wazuh/pull/21348

### Steps to reproduce
- Deploy an environment with a manager and a centOS 7 agent
- Enable Vulnerability detector
- Register and start the agent
- Wait until first syscollector scan
- Install nmap package
- Error should appear in the manager log

**Comment by MiguelazoDS** [comment]
There was a WA for that behavior here https://github.com/wazuh/wazuh/pull/21292

This is a consequence of a wrong binding when storing the values in the local database 

There's an issue to address that here https://github.com/wazuh/wazuh/issues/21296
