### ISSUE TITLE
 Wazuh agents are skipping over centralized agent configuration files received from the manager via merged.mg if they are in a subdirectory of the agent group shared directory.

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#21549]
Hello team,

**The issue was reported by @branchnetconsulting.**

I have run into what appears to be a bug introduced sometime after Wazuh 4.5.4.  It appears that starting with 4.6. Here the steps to replicate it.

On a Wazuh 4.7.1 manager, I created a directory `/var/ossec/etc/shared/default/below/` and put a file in it called `lower.conf`.  I set the ownership of the new directory and file to `wazuh:wazuh`.  
Moments later you will find a reference to `below/lower.conf` in the `/var/ossec/etc/shared/default/merged.mg` file and you will see that this `merged.mg` file is propagated out to whatever online agents you have that are membered into the default agent group.  

When you inspect their `/var/ossec/etc/shared/merged.mg` file, you will see the `below/lower.conf` reference in it but you will also see that no `/var/ossec/etc/shared/below/` directory was created and thus no `lower.conf` file was put anywhere.  All other files in `merged.mg` will have been successfully unpacked into `/var/ossec/etc/shared/` on the agent, but the "below" subdirectory is conspicuously missing along with the file that should have been put in it.

Regards,

**Comment by vikman90** [comment]
Thank you for reporting this bug. I confirm that we can reproduce it:

### Manager

```shell
:/var/ossec/etc/shared/default# mkdir dir1

:/var/ossec/etc/shared/default# echo "Content" > dir1/file1

:/var/ossec/etc/shared/default# ls -ld dir1{,/*}
drwxr-xr-x 2 root root 4096 Jan 31 09:59 dir1
-rw-r--r-- 1 root root    8 Jan 31 09:59 dir1/file1
```

### Agent

```shell
:/var/ossec/etc/shared# cat merged.mg | grep -A1 dir1
!8 dir1/file1
Content

:/var/ossec/etc/shared# ls -ld dir1
ls: cannot access 'dir1': No such file or directory
```

We should investigate the problem's cause and provide a solution. Let's add this task to the backlog.

Thank you again!

**Comment by havidarou** [comment]
This will be addressed in this issue https://github.com/wazuh/wazuh/issues/22677

**Comment by branchnetconsulting** [comment]
Please review if correcting this bug is a good fit for rolling into #22677 which sounds like a massive undertaking not to be completed until the release of version 5.

This bug does not appear to have anything to do with agent/manager communications, but rather the agent upon receiving merged.mg from the manager is simply skipping over files in merged.mg that are marked to be located in a directory below shared/ .  I presume there is simply some logic missing to make sure to create subdirectories before putting files in them.  The files getting skipped really are being put into merged.mg and shipped to the agent.  It's just the unpacking of the files where the bug expresses itself.

**Comment by xmlijhu** [comment]
We are having the same issue in v4.9.2 as we recently upgrade from 4.4.3

As with @branchnetconsulting, the bug should not be related the agent/manager communication, as we can see all the file/dir structure in the merged.mg file. Somewhere in the wazuh agent somewhat has issue when restore files the merged.mg file. 

While we restored wazuh-agent to 4.4.3, it works as before.

**Comment by branchnetconsulting** [comment]
It looks very much like a simple flaw in the way the Wazuh agent unpacks the merged.mg file it receives from the manager.   All the files are indeed in the merged.mg received by the agent.  It sure looks like it simply is failing to create subdirectories before trying to unpack files into them.  I wish I were better at C.  I bet the flaw would not be hard to spot by a developer.

**Comment by xmlijhu** [comment]
Hello @vikman90 @havidarou Any possible to fix it in 4.x? It prevents us from upgrade wazuh-agent to new version ( currently, stay in v4.4.3 which can restore the sub-folder and contents correctly), while our managers are v4.9.2. 

Tried latest version of 4.x, and this issue still there.

**Comment by xmlijhu** [comment]
I traced and found the issue, it looks like the agent will unmerged the directory and created the files under it correctly, however it will delete the folder in the end.

The code is here: 
https://github.com/wazuh/wazuh/blob/main/src/shared/file_op.c#L863-L882
https://github.com/wazuh/wazuh/blob/main/src/client-agent/receiver.c#L292

Looks like if the final_name is like directory/filename, then the 'directory' will be saved to file_name, others will be cleared

**Comment by xmlijhu** [comment]
https://github.com/wazuh/wazuh/issues/31150
