### ISSUE TITLE
Ensure JSON for Vulnerability Inventory Indexing Contains No Empty Fields

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21543]
#### Description

This issue focuses on improving the quality of the JSON data used to index the vulnerability inventory into Wazuh indexer. Currently, there are instances where fields within this JSON structure may contain empty values. To enhance data consistency and integrity, it is essential to ensure that the JSON data being indexed contains no empty fields.

#### User Stories

- As a data consumer, I want to receive well-structured JSON data with no empty fields to avoid issues with data processing.
- As a developer, I want to enhance the quality of data indexed into Wazuh Indexer by eliminating empty fields.

#### Tasks

1. **Identify Empty Fields:**
   - Analyze the existing code responsible for constructing the JSON used for indexing the vulnerability inventory.
   - Identify cases where fields may have empty or null values.

2. **Field Validation:**
   - Implement validation checks to ensure that fields within the JSON structure do not contain empty values.
   - Handle scenarios where empty fields are encountered, either by providing default values or excluding them from the JSON.

#### Definition of Done

- The code responsible for constructing the JSON data for vulnerability inventory indexing has been updated to prevent empty fields.
- Validation checks have been implemented and tested to ensure no empty fields are present in the JSON.

**Comment by GabrielEValenzuela** [comment]
# Research Update

Upon conducting an in-depth analysis of the `detailsAugmentation.hpp` file, we have identified certain missing data that require our attention. We should talk about whether to use generic information or incorporate the missing data directly into the source.

## Incomplete Package Information

In the code snippet provided, several essential fields within the 'package' data structure currently lack values. These fields include:

- `build_version`: It appears that this field may only be relevant for specific operating systems. Should we populate it, or consider its necessity based on the OS in use?

- `checksum`: Currently empty; we need to determine how to calculate and populate this field correctly.

- `install_scope`: Similar to `build_version`, this field might be dependent on the operating system. We should decide whether to include it and under what circumstances.

- `license`: Like the previous fields, it seems that the 'license' field may be conditional based on the operating system. We should discuss how to handle this.

- `reference`: Similar to the 'license' field, 'reference' may also be OS-specific. We should decide whether to add it and when it's applicable.

## Unspecified OS Family

In the code snippet, the 'os' data structure contains a 'family' field that is currently empty. We need to determine the specific operating system family to populate this field accurately.

To proceed, we should identify the relevant information and specify the correct operating system family for this particular case. This will ensure that our data is complete and accurate.

## Missing Vulnerability Report ID

Within the 'ecsData' data structure, the 'vulnerability' section includes a 'report_id' field that is currently empty. To maintain comprehensive vulnerability information, we must populate this field with the appropriate report ID.

Let's determine how to obtain or generate the relevant report ID and ensure that it is correctly assigned to this field for a complete and well-documented record of vulnerabilities.

## Conclusion


In conclusion, our analysis of the code and data structures has revealed several areas where essential information is missing. These gaps pertain to fields such as 'build_version,' 'checksum,' 'install_scope,' 'license,' 'reference,' 'os family,' and 'vulnerability report_id.'

To ensure the completeness and accuracy of our data, we must engage in a discussion to decide on the appropriate actions for each of these fields. We should determine whether they are OS-specific and, if so, under what circumstances they should be populated. Additionally, we need to identify how to obtain or generate values for certain fields like 'checksum' and 'vulnerability report_id.'

**Comment by Dwordcito** [comment]
@GabrielEValenzuela two things.

1- Remove all assignments when the field couln´t be populated.
ex, json["key"] = "" //TODO

2- Create a helper function to populate all fields.
Ex
```cpp
template<typename T>
void populateField(nlohmann::json& json, const nlohmann::json::json_pointer& key, T&& value)
{
    if(std::is_same<T,std::string>::value)
    {
        if (value.empty())
        {
             return;
        }
    }
    json[key] = value;
}
```
https://godbolt.org/z/bjcvxYnWe
