### ISSUE TITLE
Wazuh dashboard server is not ready yet

### ISSUE THREAD

**Issue by junniorcarlos** [wazuh/wazuh#21555]
|Wazuh Version|Operating System|
| --- | --- |
| 4.7 | Ubuntu 20.04 |

I have successfully installed Wazuh, and initially, the access to the interface via the browser was smooth. However, I am now encountering an issue where every time I attempt to access the application, the browser displays the message: "Wazuh dashboard server is not ready yet."

In an attempt to troubleshoot and identify the root cause, I have performed the following steps:

1. Checked the logs at `/usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log`, which returned the following relevant entries:

```json
{"date":"2024-01-11T01:12:50.176Z","level":"error","location":"monitoring:getApiInfo","message":"Request failed with status code 401"}
```

Despite cleaning browser cookies and retrying, the issue persists.

2. Reviewed the `opensearch_dashboard.yml` for potential misconfigurations, confirming the following settings:

```yml
server.host: 0.0.0.0
opensearch.hosts: https://<wazuh-indexer-ip>:9200
server.port: 443
```

3. Executed `curl -v telnet https://<wazuh-indexer-ip>:9200`, receiving the error message: "curl: (7) Failed to connect <wazuh-indexer-ip> to port 9200: Connection refused."

4. Checked the system status with `systemctl status wazuh-dashboard`, revealing an active running service with the following error:

```json
{"type":"log","@timestamp":"2024-01-20T13:45:21Z","tags":["error","opensearc>,"data"],"pid":708,"message":"[ConnectionError]: connect ECONNREFUSED <wazuh-indexer-ip>:9200"}
```

Even after restarting the system, the issue persists, and I have confirmed that there are no firewall rules blocking port 9200.

I am seeking assistance in resolving this scenario. Any guidance or suggestions would be greatly appreciated.

**Comment by ricardonunesskyonesolutions** [comment]
Do you get any solution for this issue?

**Comment by AlexRuiz7** [comment]
Check that the credentials for the indexer are correct. Status code 401 means Unauthorized request.

Using curl you will need to add the credentials with `-u user:password`. Option `-k` is probably required as well if you don't want to provide a TSL certificate.
