### ISSUE TITLE
Error in Setup single sign-on with administrator role - Microsoft Entra ID

### ISSUE THREAD

**Issue by lsayanes** [wazuh/wazuh#21551]
|Wazuh version|Component|Install method|Platform|
|---|---|---|---|
| 4.8.0 |  Microsoft | Quickstart | Any  |

Working on this issue https://github.com/wazuh/wazuh/issues/21368 I have been trying to configure Microsoft Entra ID according to the guide: 
- https://documentation-dev.wazuh.com/v4.8.0-alpha2/user-manual/user-administration/single-sign-on/administrator/microsoft-entra-id.html

I was unable to complete step 3 "Create an application in Microsoft Entra ID." of the document because the "Create your own application." page item was disabled: 

![Captura de pantalla 2024-01-16 a la(s) 22 49 43](https://github.com/wazuh/wazuh/assets/68856625/cfc5ffe8-74a2-4aa4-bb53-74dffd4cca67)

I created a new account in Microsoft azure but I got the same problem and I can't figure out what the problem is.
I have tried yahoo and gmail accounts.

<img width="995" alt="Captura de pantalla 2024-01-18 a la(s) 18 21 30" src="https://github.com/wazuh/wazuh/assets/68856625/a40ad7f3-55f9-42ef-a19f-4bd47359a048">

**Comment by rauldpm** [comment]
Probably related to missing permissions, I propose to close this issue as the source test has finished and will be closed
