### ISSUE TITLE
The cpu usage of wazuh-agent is particularly high

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#21558]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7和4.6 | Wazuh component | Agent | Packages/Sources | Centos 7.9 |
There is currently a problem. I don’t know if it’s because I upgraded from 4.3 to 4.6 or 4.7. Recently, our online business always needs to urgently upgrade the CPU because the agent’s CPU is too high.
Now to continue with a method to reduce this problem, you cannot restrict the agent so that it checks less frequently or only checks at night.
希望能帮帮我，感谢！

**Comment by pereyra-m** [comment]
Hello @PhuketIsland !

To find out the root cause behind the high CPU usage, I'd need more information.
Could you please upload the configuration file `ossec.conf` and the log file `ossec.log` from the agent ? What modules do you have enabled?

Also, you can run some diagnosis tool (like `htop`) in the agent to find out what Wazuh daemon is responsible for this (`agentd`, `modulesd`, etc.).

Regards.

**Comment by PhuketIsland** [comment]
Hello @pereyra-m !

Thank you very much for your answer. I can upload these files, but the problem I need to solve most now is how to reduce the frequency of the wazuh-syscheckd process, or run this process within the specified time.
![企业微信截图_17056549218504](https://github.com/wazuh/wazuh/assets/28825226/231a3342-221e-44e6-b64b-2f28377f69b2)

**Comment by PhuketIsland** [comment]
Hello @pereyra-m !
[ossec.log](https://github.com/wazuh/wazuh/files/14017189/ossec.log)
[ossec-21.log.gz](https://github.com/wazuh/wazuh/files/14017190/ossec-21.log.gz)
[ossec-22.log.gz](https://github.com/wazuh/wazuh/files/14017192/ossec-22.log.gz)


ossec.conf


<ossec_config>
  <client>
    <server>
      <address>172.xx.xx.76</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>centos, centos7, centos7.6</config-profile>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
    <crypto_method>aes</crypto_method>
    <enrollment>
      <enabled>yes</enabled>
      <groups>default</groups>
    </enrollment>
  </client>

  <client_buffer>
    
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>

  
  <rootcheck>
    <disabled>no</disabled>
    <check_files>yes</check_files>
    <check_trojans>yes</check_trojans>
    <check_dev>yes</check_dev>
    <check_sys>yes</check_sys>
    <check_pids>yes</check_pids>
    <check_ports>yes</check_ports>
    <check_if>yes</check_if>

    
    <frequency>43200</frequency>

    <rootkit_files>etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>etc/shared/rootkit_trojans.txt</rootkit_trojans>

    <skip_nfs>yes</skip_nfs>
  </rootcheck>

  <wodle name="cis-cat">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <java_path>wodles/java</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>
  </wodle>

  
  <wodle name="osquery">
    <disabled>yes</disabled>
    <run_daemon>yes</run_daemon>
    <log_path>/var/log/osquery/osqueryd.results.log</log_path>
    <config_path>/etc/osquery/osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

  
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>

    
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>

  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>

  
  <syscheck>
    <disabled>no</disabled>

    
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>

    
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>

    
    <ignore type="sregex">.log$|.swp$</ignore>

    
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>
    <skip_dev>yes</skip_dev>
    <skip_proc>yes</skip_proc>
    <skip_sys>yes</skip_sys>

    
    <process_priority>10</process_priority>

    
    <max_eps>100</max_eps>

    
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>

  
  <localfile>
    <log_format>command</log_format>
    <command>df -P</command>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>last -n 20</command>
    <frequency>360</frequency>
  </localfile>

  
  <active-response>
    <disabled>no</disabled>
    <ca_store>etc/wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>

  
  <logging>
    <log_format>plain</log_format>
  </logging>

</ossec_config>

<ossec_config>
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/httpd/error_log</location>
  </localfile>

  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/httpd/access_log</location>
  </localfile>

  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>

</ossec_config>

**Comment by pereyra-m** [comment]
Hi again @PhuketIsland !

Thank you for the information provided. But the configuration has lost its format and it's hard to read, could you upload the `ossec.conf` file?

Nevertheless, if the high CPU usage comes from `wazuh-syscheckd`, we should check:
- The number of folders and directories configured
- The frequency of the scan
- Some options like real-time

Here you have the documentation sections related to this module
https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/basic-settings.html
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html

> Thank you very much for your answer. I can upload these files, but the problem I need to solve most now is how to reduce the frequency of the wazuh-syscheckd process, or run this process within the specified time.

To configure the scans less often, you need to increase the `<frequency>` value for **syscheck**.
You could also set [scan_time](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#reference-ossec-syscheck-scan-time) to specify the exact time of the scan.

**Comment by PhuketIsland** [comment]
Hello @pereyra-m !

Thank you very much for your answer.
![image](https://github.com/wazuh/wazuh/assets/28825226/9661ca63-d58f-4fc3-85c5-2d2c17f76c41)
[ossec.txt](https://github.com/wazuh/wazuh/files/14031569/ossec.txt)
Due to upload restrictions, I changed the conf suffix to txt suffix.

**Comment by pereyra-m** [comment]
Thank you for the configuration file @PhuketIsland .

Please, increase the value of `frequency` or set a `scan_time` as suggested above.
If this isn't enough, we can try to check if all configured folders are really important.

**Comment by PhuketIsland** [comment]
Hello @pereyra-m !
![image](https://github.com/wazuh/wazuh/assets/28825226/41be3f49-17da-46b1-8d1b-65334bdc758b)
![image](https://github.com/wazuh/wazuh/assets/28825226/a4bcc2d7-dd0a-40ba-a9c7-379a12118e18)
We found that the CPU was extremely high every time we did this scan.

**Comment by pereyra-m** [comment]
@PhuketIsland 

The `sca` module runs in `wazuh-moduled`, not `wazuh-syscheckd`. If the high CPU usage is during that scan then we are modifying the wrong settings.

Here you can see an example configuration block for `sca` where you can set a specific moment of the day to run the scan
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/sca.html#configuration-example

But this isn't expected, could you share the hardware specifications of the agent that is having this issue?

**Comment by PhuketIsland** [comment]
Thank you very much for your answer.
