### ISSUE TITLE
Drop support for Blowfish encryption method

### ISSUE THREAD

**Issue by jr0me** [wazuh/wazuh#21569]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 |  | Manager,Agent | Sources | All |

We have decided to drop support for Blowfish as an encryption method in our application. Our primary encryption method is AES, which is widely regarded as more secure and robust. The decision to phase out Blowfish is driven by two primary factors: the use of deprecated OpenSSL functions in its implementation, during it's migration it wasn't possible to ensure backwards compatibility without greater efforts, and the general discouragement of its use in current security protocols.

Deprecated functions in `bf_op.h`:

* `BF_set_key`
* `BF_cbc_encrypt`

#### Logged warnings from building server

<details>
<summary>Click to expand</summary>

```
os_crypto/blowfish/bf_op.c: In function ‘OS_BF_Str’:
os_crypto/blowfish/bf_op.c:34:5: warning: ‘BF_set_key’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   34 |     BF_set_key(&key, (int)strlen(charkey), (const uchar *)charkey);
      |     ^~~~~~~~~~
In file included from os_crypto/blowfish/bf_op.c:19:
external/openssl/include/openssl/blowfish.h:50:28: note: declared here
   50 | OSSL_DEPRECATEDIN_3_0 void BF_set_key(BF_KEY *key, int len,
      |                            ^~~~~~~~~~
os_crypto/blowfish/bf_op.c:36:5: warning: ‘BF_cbc_encrypt’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   36 |     BF_cbc_encrypt((const uchar *)input, (uchar *)output, (long)size,
      |     ^~~~~~~~~~~~~~
In file included from os_crypto/blowfish/bf_op.c:19:
external/openssl/include/openssl/blowfish.h:57:28: note: declared here
   57 | OSSL_DEPRECATEDIN_3_0 void BF_cbc_encrypt(const unsigned char *in,
      |                            ^~~~~~~~~~~~~~
```

</details>

See also [OpenSSL migration guide: Deprecated function mappings](https://www.openssl.org/docs/man3.2/man7/migration_guide.html#Deprecated-function-mappings)

**Comment by vikman90** [comment]
We may want to develop this task as part of #15430.
