### ISSUE TITLE
Integratord scripts need to return exit code

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#2156]
## Bug report

**OS**
_Ubuntu16/CentOS7/RHEL7/AIX.._

**Wazuh version**
_3.7.2_

**Install type**
_manager/agent_

**Install method**
_packages/sources_

Bug description
----------------

The **slack** and **virustotal** scripts that ships inside the integrations folder, are returning 0 in some scenarios were a different value should be returned.

**Comment by chemamartinez** [comment]
Fixed at 15e612a0ad5dd6699b871ab928d00fdcdf87b767
