### ISSUE TITLE
Add interface and static libkeystore.a library in the CMake project build process

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21575]
### Description

This issue is focused on enhancing the project by adding methods that enable the insertion or update of key-value pairs within a specified column family. It also involves integrating the project into the root CMake configuration and adding a dependency on the indexer connector module. Below are the key aspects of this issue:

#### Add interfaces
The project requires the implementation of methods that facilitate the insertion or updating of key-value pairs in a specific column family. For instance, a sample method might be:

```cpp
/**
 * Insert or update a key-value pair in the specified column family.
 *
 * @param columnFamily The target column family.
 * @param key The key to be inserted or updated.
 * @param value The corresponding value.
 */
void put(const std::string& columnFamily, const std::string& key, const rocksdb::Slice& value);
```

```cpp
/**
 * Get the key value in the specified column family.
 *
 * @param columnFamily The target column family.
 * @param key The key to be inserted or updated.
 * @param value The corresponding value to be returned.
 */
void get(const std::string& columnFamily, const std::string& key, rocksdb::PinnableSlice& value);
```
#### Project Integration with CMake

To ensure seamless integration with the project build system, it is necessary to create CMakelists files and include the project using add_subdirectory. This ensures that the project can be easily built and managed as part of the larger codebase.

#### Dependency Indexer Connector

The indexer connector module depends of this library. Therefore, the necessary dependencies and linkage should be added to enable seamless interaction with this module.

### Definition of done
- Add interfaces.
- Successful project integration with CMake using add_subdirectory.
- Appropriate dependencies and linkage added for interaction with the indexer connector module.

## Project structure

```tree
|-- src
    |-- shared_modules
        |-- keystore
            |-- include
                 |-- keyStore.hpp
            |-- src
                 |-- keyStore.cpp
            |-- tests
                 |-- unit
                     |-- unitTestFile_test.hpp
                     |-- unitTestFile_test.cpp
                 |-- component
                     |-- componentTestFile_test.hpp
                     |-- componentTestFile_test.cpp
```

**Comment by mateocervilla** [comment]
## Update

- Create branch [`21575-libkeystore-lib-interface`](https://github.com/wazuh/wazuh/tree/21575-libkeystore-lib-interface)
- Create project tree
- Add headers and definitions
- Create `CMakelists.txt`
- Test if library works
- Fix CMake for github actions builds
- Fix CMake for github actions Ubuntu 20 build
    - Here we can see a difference between the same compilation in different Ubuntu versions, where Ubuntu 22 uses C++17 or later by default.
        - [vulnerability-scanner-modules-asan (ubuntu-20.04)](https://github.com/wazuh/wazuh/actions/runs/7644653811/job/20830624671)
        - [vulnerability-scanner-modules-asan (ubuntu-latest)](https://github.com/wazuh/wazuh/actions/runs/7644653811/job/20830624414)
