### ISSUE TITLE
Implement put method and create a tool for the keystore management

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21576]
### Description

This issue is focused on developing a command-line tool that allows users to exercise the keystore `put` method within the project. The tool should provide a convenient way to insert key-value pairs into the database with the specified column family, key, and value.

#### Tool Functionality

The tool should support the following command-line flags:

- `-f`: Specifies the target column family for the insertion.
- `-k`: Specifies the key for the key-value pair.
- `-v`: Specifies the value associated with the key.

Ex: https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_scanner/testtool/scanner/argsParser.hpp

The tool should perform the following tasks:

1. Accept user-provided input for the column family, key, and value.
2. Utilize the project's `put` method to insert the provided key-value pair into the specified column family.
3. Provide appropriate feedback to the user, such as success or failure messages.

#### Security Note

It is crucial to ensure that this tool does not exercise the `get` method, as accessing certain data may be restricted for security reasons. The focus of this tool is solely on the insertion of data.

### Example Usage

Here's an example of how the tool could be used:

```bash
# Insert a key-value pair into the "indexer" column family
$ ./wazuh-keystore -f indexer -k user -v admin
$ ./wazuh-keystore -f indexer -k password -v pwd123
```

### Put method implementation definition.
```mermaid
sequenceDiagram
    Testtool->> keyStore: Insert user/password in the key store
    keyStore->> rsaHelper: Encrypt Value
    rsaHelper->>FileSystem: Read sslmanager.cert and sslmanager.key
    rsaHelper->>rsaHelper: Encrypt value using the RSA algorithm
    keyStore->> rocksDB: Open Rocksdb in write mode
    keyStore->> rocksDB: Save in a column family the key with the value encrypted
```
rocksdb path: queue/keystore

#### extra points
- create a helper with the name rsaHelper.hpp inner shared_modules/utils with two methods, encrypt y decrypt
- use the rocksDBWrapper.hpp inner shared_modules/utils

### Definition of Done
- The tool is implemented and functional.-
- It accepts user input for the column family, key, and value.
- It utilizes the project's put method to insert key-value pairs.
- Appropriate success/failure messages are displayed to the user.
- The tool does not exercise the get method for security reasons.

**Comment by mateocervilla** [comment]
## Update

- Added command line parser
- Created executable
- CMake config
- Implemented put method
- DB insertion
- Get key from file
- Error handling
- Added OpenSSL to CMake

**Comment by ncvicchi** [comment]
LGTM! Merged!
