### ISSUE TITLE
Revise the use case for reporting on open ports

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#21570]
Agents have included this Logcollector setting to track changes in open ports since their early versions:

```xml
<localfile>
  <log_format>full_command</log_format>
  <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
  <alias>netstat listening ports</alias>
  <frequency>360</frequency>
</localfile>
```

Every six minutes, the agent carries out the command. Next, using rule 533, the manager determines whether any content has changed.

https://github.com/wazuh/wazuh/blob/6d59398bd3647d7cf07d9b8457b943fc5b28dc05/ruleset/rules/0015-ossec_rules.xml#L195-L201

On some systems, `ss` has taken the position of `netstat`. It is not certain that any of these tools will be installed on the host, though. However, we wish to move to Syscollector to handle this use case since it already records changes on open ports on all supported platforms.

## Key requirements

- Disable the Logcollector setting that is currently used to perform `netstat`.
- The user may proceed with configuring Logcollector to execute `netstat`: maintain rule 533.
- Include a default rule that reports inventory changes for the open ports.
- Examine if you can live with the hourly latency of the Syscollector.

## Related issues

- #3903
- #3695
- #3487
- #3071
- #1608
- #1279
- #730

**Comment by havidarou** [comment]
This issue will be tackled during 5.0 development as part of state changes in the inventory module using the new analysis engine's ruleset.
