### ISSUE TITLE
Adapt the indexer connector to use the keystore database.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21577]
### Description

This issue aims to integrate the `get` method within the project to retrieve the required authentication credentials (user and password) from the indexer. These credentials will be used for authentication within the indexer connector module.

#### Method Functionality

The `get` method should be designed to retrieve the following authentication credentials:

- **User**: The username required for authenticating with the indexer.
- **Password**: The password associated with the specified user.

#### Integration Process

The integration process should include the following steps:

1. Implement the `get` method within the project's codebase. (Data is encripted with RSA algorithm using the sslmanager.cert and sslmanager.key)
2. Ensure that the method can successfully retrieve the user and password information from the indexer configuration.
3. Store the retrieved credentials in secure memory or variables to prevent exposure.

### Definition of Done

- The `get` method is successfully implemented and functional.
- It retrieves the user and password from the indexer configuration.
- The retrieved credentials are securely stored or handled.
- Appropriate error handling is in place for any potential issues during retrieval.

### Notes.
- Rocksdb is used as database. Path: queue/keystore
- Open rocksdb instance to queue/keystore as readonly.

**Comment by ncvicchi** [comment]
LGTM! Merged!
