### ISSUE TITLE
Remove user and password tags from indexer configuration

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21574]
### Description

This issue aims to remove the parsing processes currently used to load the user and password configuration of the 'indexer' tag from the ossec.conf file. This change is part of the larger effort to transition to using the Wazuh keystore for secure configuration management.

### User Story

As a developer, I want to remove the load of the user and password fields from the  'indexer' tag in ossec.conf. This simplification is a preliminary step towards implementing the use of the Wazuh keystore for more secure and efficient configuration management.

### Proposed Solution

The proposed solution involves the following key steps:

1. **Remove Parsing Code:**
   - Identify and remove the parsing code responsible for extracting the user and password from the 'indexer' tag configuration if necessary, and modify unit tests.

2. **Default configuration:**
   - Identifiy and remove fields from the default configuration. -> https://github.com/wazuh/wazuh/blob/master/etc/templates/config/generic/wodle-indexer.manager.template

### Definition of Done

- Parsing code for user and password in the 'indexer' tag configuration has been removed if necessary.
- Remove from the default configuration.

**Comment by Leoquicenoz** [comment]
## Update

1. Remove the username and password fields referring to the indexer in all files containing it, including default configuration (templates) and Unit tests.
2. It compiles without any problem.
3. It remains to be seen if the UTs pass

**Comment by Leoquicenoz** [comment]
## Update

1. Changes are made to some unit tests that had not been modified before and then it is verified that they all pass, the coverage is not modified.
2. PR created and changes uploaded.

**Comment by ncvicchi** [comment]
Reopen to address several situations that we realized that should be taken into account

**Comment by ncvicchi** [comment]
Changed ETA to give time to resolve new situations

**Comment by Leoquicenoz** [comment]
We closed the issue again since it was reopened thinking that the modification of the `wazuh-install.sh` file was included here and that we had overlooked it, but in issue [#2794](https://github.com/wazuh/wazuh-packages/issues/2794) this modification is being carried out.
