### ISSUE TITLE
 Inconsistencies in the wazuh-db code after the merge from 4.7.1 to 4.8

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh#21589]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| >= 4.8 | wazuh-db | Manager | Packages/Sources | OS version |

I noticed some inconsistencies in the wazuh-db code after the merge from `4.7.1` to `4.8`.
In version `4.7.1` this [PR](https://github.com/wazuh/wazuh/pull/20178) was introduced that changed the use of rwlock_lock_read/write instead of phtread_mutex when locking the open database pool(pool_mutex) in wazuh-db, while in 4.8 this [PR](https://github.com/wazuh/wazuh/pull/18476) was introduced that makes use of pool_mutex, this part of the code has been left using w_mutex_lock/w_mutex_unlock when it should use rwlock_lock_write/unlock:
![image](https://github.com/wazuh/wazuh/assets/13004400/d274cc68-6577-42d5-84ec-554809fa74a5)
![image](https://github.com/wazuh/wazuh/assets/13004400/b208dbbd-6c4d-4805-a596-62ca1f2e550c)

https://github.com/wazuh/wazuh/blob/4.8.0/src/wazuh_db/wdb_parser.c#L764
https://github.com/wazuh/wazuh/blob/4.8.0/src/wazuh_db/wdb_parser.c#L1407

This generates a warning at compile time, and possibly a crash if that part of the code is executed.

**Comment by vikman90** [comment]
This issue is new in 4.8.0, ergo it must be a stopper.

**Comment by Nicogp** [comment]
The code was analyzed, it was only necessary to make changes in the lines of code indicated in the issue description.
The changes were applied and manual tests were performed.
Tomorrow the UTs will be executed and the PR will be created.
