### ISSUE TITLE
Engine - Update specific helper tests

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#21587]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Our current implementation of tests for the builders extensively duplicates code, making small changes in the builders unnecessary mechanical and repetitive work.

We need to improve the test implementation to use parametrized tests with the use cases as input data where applicable.

## Tasks
- [x] wazuhDB
- [x] HLP
- [x] SCA
- [x] Windows

**Comment by JavierBejMen** [comment]
## Update
- Implemented base tests for helpers with other modules as dependencies without mock leaks
- Updated upgrade confirmation tests
- Updated active response tests
- Working on updating kvdb tests

**Comment by JavierBejMen** [comment]
## Update 
- Updated kvdb helper tests to avoid mock leak
- Working on wazuh db helper tests

**Comment by JavierBejMen** [comment]
## Update
- Added windows helper tests
- Working on hlp and sca
- Removed deprecated netinfoAdress helpers

**Comment by JavierBejMen** [comment]
## Update
- Added hlp helper tests
- Added sca helper tests
- Removed unused code
