### ISSUE TITLE
Issue Upgrading Wazuh Manager 4.6.0 to 4.7.2 that was Initially Installed from Sources

### ISSUE THREAD

**Issue by shegzon** [wazuh/wazuh#21583]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-03 | Wazuh Manager | Manager/Agent | Sources | Centos Stream 8 |

Hello Team,

I successfully installed Wazuh 4.6.0  from sources to a custom path **/var/ossec/manager** using the [official guide](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html#installing-the-wazuh-manager-from-sources). I tried to use sources to upgrade to version 4.7.2 and I received a prompt **"You already have Wazuh installed. Do you want to update it? (y/n):"** which I selected yes (screenshot attached below):

![Screenshot of Error encountered upgrading Wazuh manager from sources2.](https://github.com/wazuh/wazuh/assets/15922108/2cd8b8dc-0ddf-4d57-896b-d0de42712971)

During the upgrade, I encountered an error as identified in the screenshot below:
![Screenshot of Error encountered upgrading Wazuh manager from sources.](https://github.com/wazuh/wazuh/assets/15922108/9b7ea5db-8f18-492d-82ca-912626cdc4d1)

**Comment by rauldpm** [comment]
Maybe related:

- https://github.com/wazuh/wazuh-qa/issues/4592
- https://github.com/wazuh/wazuh/issues/19671

**Comment by Dwordcito** [comment]
Probably this is related to an old version of GCC and G++, @shegzon could you execute `gcc --version` and `g++ --version` ?

**Comment by shegzon** [comment]
Hello @Dwordcito, below is output of both commands:

![Screenshot of GCC and G++ commands](https://github.com/wazuh/wazuh/assets/15922108/b9e3ebc2-c986-478f-8ec3-a4a1ff4fce25")

**Comment by Dwordcito** [comment]
Wazuh requires GCC and G++ 9.x to compile the project! Update your gcc/g++ version and tell me if the problem continues!

**Comment by shegzon** [comment]
Hello @Dwordcito, after updating gcc and g++, with command `curl -OL http://packages.wazuh.com/utils/gcc/gcc-9.4.0.tar.gz && tar xzf gcc-9.4.0.tar.gz  && cd gcc-9.4.0/ && ./contrib/download_prerequisites && ./configure --enable-languages=c,c++ --prefix=/usr --disable-multilib --disable-libsanitizer && make -j$(nproc) && make install && ln -fs /usr/bin/g++ /bin/c++ && ln -fs /usr/bin/gcc /bin/cc && cd .. && rm -rf gcc-* && scl enable devtoolset-7 bash`, I was able to upgrade the Wazuh manager from 4.6 to 4.7 from sources. Why I initially didn't run the command was because I was using CentOS 8 and that command was peculiar to CentOS 6/7 as indicated in the documentation below:

![Sceenshot of updating gcc and g++](https://github.com/wazuh/wazuh/assets/15922108/24490ab6-0bdc-42f5-843a-823c34f3d57b)

Thanks a lot for the support.

**Comment by Dwordcito** [comment]
@seba
