### ISSUE TITLE
Forward Log Synology to Wazuh

### ISSUE THREAD

**Issue by bausastra** [wazuh/wazuh#21599]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2 | Wazuh component | Manager & Agent | Packages | Ubuntu 22.04.2 LTS |

How to Forward Log Synology to Wazuh ? Are there any references that can help me? 
Thank You

**Comment by juliancnn** [comment]
Hello,

Integrating Synology with Wazuh for log forwarding depends on whether your Synology device supports syslog forwarding. Here's how you can approach this:

1. **Check Synology Capabilities**:
   - First, verify if your Synology device can be configured to send syslog messages. This information can typically be found in the Synology documentation or control panel settings.
   - If syslog forwarding is supported, you can configure your Synology device to send logs to the IP address and port of your Wazuh manager.

2. **Configure Wazuh for Syslog**:
   - If Synology supports syslog, on the Wazuh manager side, you'll need to set up to receive and process syslog messages.
   - Detailed instructions for configuring Wazuh to collect syslog data can be found in our documentation: [Wazuh Syslog Collection](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/syslog.html).

3. **Testing and Verification**:
   - After setting up the configurations, it's important to test and ensure that the logs are being correctly received by your Wazuh manager.
   - Check the Wazuh manager's logs for incoming messages from your Synology device to confirm successful integration.
