### ISSUE TITLE
Create a persistent queue for the alerts reported by the new vulnerability detector

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#21600]
## Description

The class in charge of reporting the alerts to **analysisd** currently contains a blocking call to the socket and a sleep

https://github.com/wazuh/wazuh/blob/c2bd49cdee860c8bd8e38ab4935627aeb303aec3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/sendReport.hpp#L78-L81

We need to refactor this section and create a RocksDB queue to store these messages, to reduce the required time to complete a scan, and to handle properly the case when the socket isn't available.

## DoD

- [x] Implement all the required changes to decouple the **analysisd** socket communication from the scanner's  main thread
- [x] Manual tests to verify the correct behavior of the development (socket delay, socket not found, manager restart, etc.)
- [x] Add UT
- [x] CI Pass

**Comment by pereyra-m** [comment]
@sebasfalcone , I propose moving the ETA to at least 1 or 2 of February.

**Comment by sebasfalcone** [comment]
Changed ETA to give time for review and testing
