### ISSUE TITLE
Duplicated localfile error on logcollector

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2161]
## Bug report

**Wazuh version**
_3.7.2_

**Install type**
_manager_

**Install method**
_packages/sources_

**Config sample**

```
<localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
</localfile>

<localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
</localfile>
```

Bug description
----------------

If two identical `<localfile>` blocks are defined in the configuration, `ossec-logcollector` crashes.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/2154 solves the issue
