### ISSUE TITLE
CDB list are prebuilt instead of building them when installing the manager

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2163]
CDB lists are built by `ossec-makelists` only when running the tool manually, so default lists are prebuilt hosted in the Wazuh repository.

It is more logical to build them when installing the manager, even though when it is restarted. This way we could remove the compiled lists from the repository.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/2167 solves the issue.

**Comment by chemamartinez** [comment]
This PR https://github.com/wazuh/wazuh-ruleset/pull/249 adds the corresponding ruleset changes
