### ISSUE TITLE
Update Azure Log Analytics documentation

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#21630]
## Description

Azure has introduced some changes to its services interfaces, causing the [Using Azure Log Analytics](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/services/log-analytics.html) documentation to be outdated.

Similar to what we did in https://github.com/wazuh/wazuh/issues/21548, we should follow the documentation, update any instruction or image that is not up-to-date and validate that the wodle is configured correctly and works as expected.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [x] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
# Issue Update

With the aid of @teddytpc1, I was able to set up a new application in `App registration`, giving permissions to it and access to the `Log Analytics API` following the current documentation.

![image](https://github.com/wazuh/wazuh/assets/26691145/329ffa06-5752-48e0-b645-ef90c5310d46)

<details><summary>AuditLogs query in Azure</summary>

![image](https://github.com/wazuh/wazuh/assets/26691145/dd5568d6-c616-4c31-9229-48e9851fa851)

</details>

<details><summary>Manager information</summary>

```console
root@25b3a850da54:/# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.0"
WAZUH_REVISION="40802"
WAZUH_TYPE="server"
```

</details>

<details><summary>ossec.conf</summary>

```xml
<wodle name="azure-logs">
    <disabled>no</disabled>
    <run_on_start>yes</run_on_start>
    <interval>5m</interval>
    <log_analytics>
      <auth_path>/var/ossec/analytics-credentials.txt</auth_path>
      <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
      <request>
        <query>AuditLogs</query>
        <workspace>WORKSPACE-ID</workspace>
        <time_offset>1d</time_offset>
      </request>
    </log_analytics>
  </wodle>
```

</details>


<details><summary>Credentials</summary>

```console
root@25b3a850da54:/# cat /var/ossec/analytics-credentials.txt
application_id = ******************-****-************
application_key = ****************************************
```

</details>

<details><summary>Module execution - ossec.log</summary>

```log
2024/01/30 16:09:19 wazuh-modulesd:azure-logs[1834] wm_azure.c:54 at wm_azure_main(): INFO: Module started.
2024/01/30 16:09:19 wazuh-modulesd:azure-logs[1834] wm_azure.c:74 at wm_azure_main(): INFO: Starting fetching of logs.
2024/01/30 16:09:19 wazuh-modulesd:azure-logs[1834] wm_azure.c:81 at wm_azure_main(): INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2024/01/30 16:09:19 wazuh-modulesd:azure-logs[1834] wm_azure.c:120 at wm_azure_log_analytics(): DEBUG: Creating argument list.
2024/01/30 16:09:19 wazuh-modulesd:azure-logs[1834] wm_azure.c:172 at wm_azure_log_analytics(): DEBUG: Launching command: wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/analytics-credentials.txt --la_tenant_domain wazuh.onmicrosoft.com --la_tag request_1863774189 --la_query "AuditLogs" --workspace WORKSPACE-ID --la_time_offset 1d --debug 2
2024/01/30 16:09:24 wazuh-modulesd:azure-logs[1834] wm_azure.c:189 at wm_azure_log_analytics(): INFO: Finished Log Analytics collection for request 'request_1863774189'.
2024/01/30 16:09:24 wazuh-modulesd:azure-logs[1834] wm_azure.c:83 at wm_azure_main(): INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2024/01/30 16:09:24 wazuh-modulesd:azure-logs[1834] wm_azure.c:100 at wm_azure_main(): DEBUG: Fetching logs finished.
2024/01/30 16:09:24 wazuh-modulesd:azure-logs[1834] wm_azure.c:70 at wm_azure_main(): DEBUG: Sleeping until: 2024/01/30 16:14:19
```

</details>


<details><summary>Log Analytics database</summary>

```console
root@25b3a850da54:/# sqlite3 /var/ossec/wodles/azure/azure.db "select * from log_analytics;"
63daf76c0c6951a249570d1a0c0a2201|AuditLogs|2024-01-29T19:09:22.324711Z|2024-01-30T16:26:12.866569Z
```

</details>
