### ISSUE TITLE
Default? Level 12 or above alerts: Wazuh dashboard

### ISSUE THREAD

**Issue by ITPIRNE** [wazuh/wazuh#21645]
Hi,

Hope you all are doing well.

I don't know if this is an issue or just a discussion. Is there by any change that I could change or edit the value of level of alerts below 12? Or this one is by default? I just want to make sure I could monitor low level alerts on my dashboard.

![Screenshot 2024-01-28 144448](https://github.com/wazuh/wazuh/assets/157944547/e1ada472-ab2d-4a47-8fde-33a18d90f66b)

Let me know if this is possible. Thank you in advance!

**Comment by davidcr01** [comment]
Hello.

You could just remove that filter that says `rule.level: 12 to +inf` by click in on the `X` button of the filter. Then, you could add a new filter that displays all the alerts with the condition you want. A following example could be:

- Click on the `+ Add filter` button next to the filter bar.
- Select the field you want to filter by. In this case, the field is `rule.level`
- Select the correct operator. If you want an interval, choose the `is between` operator
- Insert the minimum and the maximum values of the range. In this case, the range I created is from 1 to 15 rule levels.
- Click on the `Save` button.
![image](https://github.com/wazuh/community/assets/72193239/2e09f04b-8526-4c50-b8b3-de9c7d78b8b2)

Now, the alerts that are displayed in the dashboard are between those two values. 
Hope it helps

**Comment by ITPIRNE** [comment]
Hi,

Thank you for your response. I tried your guide, and it works for me.

But when I add a filter on `+ Add filter ` button and save it, why is my saved filter is gone when I go to other tabs then go back to dashboard. So, my understanding is that every time I want to add filter, I have to do it again?

**Comment by davidcr01** [comment]
Hello again.

You can save your query, in order words, you can save your search and the filters you applied on the search.

To perform this, in the same page of the Security Events, when you create the filter I mentioned you, click on the left button of the Search bar and click "Save query":
![Image](https://github.com/wazuh/community/assets/72193239/7658c41e-9879-436e-8c1e-703b6e3d07f8)

Then, specify a name for this saved query and an optional description:
![Image](https://github.com/wazuh/community/assets/72193239/4032bf01-bf5b-48ee-ae01-7662f96fe687)


Now, every time you enter this window, you can load the query you saved by clicking on the button on the left of the Search bar and load the query you created, without specifying the filter again.
![Image](https://github.com/wazuh/community/assets/72193239/7d1179a6-a31e-4f9b-a127-f4169cc88dee)

Hope this helps.
