### ISSUE TITLE
Review defects present at Vulnerability Detector

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#21640]
|Wazuh version|Component|Install type|Source|
|---|---|---|--|
| 4.8.0 Alpha 2 | Vulnerability Detector | Manager | #21510|

The following defects reported by Coverity are expected to be fixed by #21294 on branch _4.8.0_. However, they were not marked as solved:

|CID|Name|
|--|--|
|1575836|COPY_INSTEAD_OF_MOVE|
|1575800|COPY_INSTEAD_OF_MOVE|
|1575795|COPY_INSTEAD_OF_MOVE|
|1575794|Use of auto that causes a copy|
|1575776|COPY_INSTEAD_OF_MOVE|
|1575761|COPY_INSTEAD_OF_MOVE|
|1575749|Use of auto that causes a copy|

**Comment by pereyra-m** [comment]
Might be duplicate of #21808.
There are different CIDs but the warnings seem the same.
