### ISSUE TITLE
FIPS 140-2 compliance

### ISSUE THREAD

**Issue by hades-ngai** [wazuh/wazuh#21658]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | All | Manager & Agent | Sources | Official K8s yaml |

Hello Wazuh dev,

I am currently working on FedRAMP compliance, so all connections of our app servers must encrypted by `FIPS 140-2` standard. But Wazuh agent registration only support communicate by TCP currently. Therefore, may I request a feature that in the future Wazuh agent registration can use TLS protocol(FIPS) to connect?
Thank you very much!

Best Regards,
Hades

**Comment by vikman90** [comment]
Hi @hades-ngai, 

We've done some study on the several related reports that we received. We are aware of the numerous benefits that using TLS would offer in terms of usability, security, and maintainability even if we do not perceive any security flaws in the communication between agents and managers.

In this regard, we have an issue that we will address later on:

- https://github.com/wazuh/wazuh/issues/15430

Kind regards.
