### ISSUE TITLE
Error connection from Wazuh agent to Ossec server

### ISSUE THREAD

**Issue by crakerkai** [wazuh/wazuh#2165]
Hello,

I need your help. I want to connect from windows wazuh agent to ossec server but I meet the issue like that:
agent log:
2018/12/24 15:57:20 ossec-agent[13816] win_agent.c:155 at local_start(): DEBUG: Reading agent configuration.
2018/12/24 15:57:20 ossec-agent[13816] win_agent.c:169 at local_start(): INFO: Using notify time: 10 and max time to reconnect: 60
2018/12/24 15:57:20 ossec-agent[13816] win_agent.c:172 at local_start(): DEBUG: Reading logcollector configuration.
2018/12/24 15:57:20 ossec-agent[13816] config.c:194 at ExecdConfig(): DEBUG: Added CA store 'wpk_root.pem'.
2018/12/24 15:57:20 ossec-agent[13816] win_execd.c:86 at WinExecd_Start(): INFO: Started (pid: 13816).
2018/12/24 15:57:20 ossec-agent[13816] win_agent.c:220 at local_start(): INFO: (1410): Reading authentication keys file.
2018/12/24 15:57:20 ossec-agent[13816] msgs.c:79 at OS_StartCounter(): DEBUG: OS_StartCounter: keysize: 1
2018/12/24 15:57:20 ossec-agent[13816] msgs.c:121 at OS_StartCounter(): DEBUG: No previous counter available for 'wazuh-agent'.
2018/12/24 15:57:20 ossec-agent[13816] msgs.c:135 at OS_StartCounter(): DEBUG: Assigning counter for agent wazuh-agent: '0:0'.
2018/12/24 15:57:21 ossec-agent[13816] msgs.c:130 at OS_StartCounter(): DEBUG: Assigning sender counter: 0:552
2018/12/24 15:57:21 ossec-agent[13816] msgs.c:145 at OS_StartCounter(): DEBUG: Stored counter.
2018/12/24 15:57:21 ossec-agent[13816] start_agent.c:85 at connect_server(): INFO: Trying to connect to server (192.168.112.128:1514/udp).
2018/12/24 15:57:21 ossec-agent[13816] state.c:31 at state_main(): DEBUG: State file updating thread started.
2018/12/24 15:57:21 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:21 ossec-agent[13816] win_agent.c:248 at local_start(): DEBUG: Creating thread mutex.
2018/12/24 15:57:21 ossec-agent[13816] buffer.c:59 at buffer_init(): DEBUG: Agent buffer created.
2018/12/24 15:57:21 ossec-agent[13816] win_agent.c:55 at skthread(): INFO: Starting syscheckd thread.
2018/12/24 15:57:21 ossec-agent[13816] buffer.c:137 at dispatch_buffer(): DEBUG: Agent buffer empty.
2018/12/24 15:57:21 ossec-agent[13816] rotate_log.c:40 at w_rotate_log_thread(): DEBUG: Log rotating thread started.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:101 at Start_win32_Syscheck(): DEBUG: Starting ...
2018/12/24 15:57:21 ossec-agent[13816] config.c:54 at Read_Syscheck_Config(): DEBUG: Reading Configuration [ossec.conf]
2018/12/24 15:57:21 ossec-agent[13816] config.c:62 at Read_Syscheck_Config(): DEBUG: Reading Client Configuration [ossec.conf]
2018/12/24 15:57:21 rootcheck[13816] rootcheck.c:184 at rootcheck_init(): DEBUG: Starting ...
2018/12/24 15:57:21 rootcheck[13816] rootcheck.c:201 at rootcheck_init(): INFO: Started (pid: 13816).
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\batfile'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\cmdfile'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\comfile'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\exefile'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\piffile'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\AllFilesystemObjects'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Directory'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Folder'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Security'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\KnownDLLs'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\winreg'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:165 at Start_win32_Syscheck(): INFO: Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components [x64]'.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\regedit.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system.ini', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\win.ini', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\at.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\attrib.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\cacls.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\cmd.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\drivers\etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\eventcreate.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\ftp.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\lsass.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\net.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\net1.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\netsh.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\reg.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\regedt32.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\regsvr32.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\runas.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\sc.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\schtasks.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\sethc.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\subst.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\wbem\wmic.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\windowspowershell\v1.0\powershell.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\sysnative\winrm.vbs', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\at.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\attrib.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\cacls.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\cmd.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\drivers\etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\eventcreate.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\ftp.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\net.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\net1.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\netsh.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\reg.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\regedit.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\regedt32.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\regsvr32.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\runas.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\sc.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\schtasks.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\sethc.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\subst.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\wbem\wmic.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\windowspowershell\v1.0\powershell.exe', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\windows\system32\winrm.vbs', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:173 at Start_win32_Syscheck(): INFO: Monitoring directory: 'c:\programdata\microsoft\windows\start menu\programs\startup', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | realtime | mtime | inode.
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:187 at Start_win32_Syscheck(): INFO: Ignoring sregex: '.log$|.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$'
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:192 at Start_win32_Syscheck(): INFO: Ignoring registry: 'HKEY_LOCAL_MACHINE\Security\Policy\Secrets'
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:192 at Start_win32_Syscheck(): INFO: Ignoring registry: 'HKEY_LOCAL_MACHINE\Security\SAM\Domains\Account\Users'
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:197 at Start_win32_Syscheck(): INFO: Ignoring registry sregex: '\Enum$'
2018/12/24 15:57:21 ossec-agent[13816] syscheck.c:209 at Start_win32_Syscheck(): INFO: Started (pid: 13816).
2018/12/24 15:57:26 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:26 ossec-agent[13816] wait_op.c:71 at os_wait(): DEBUG: Process locked due to agent is offline. Waiting for connection...
2018/12/24 15:57:31 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:36 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:41 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:42 ossec-agent[13816] start_agent.c:237 at start_agent(): WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.112.128'.
2018/12/24 15:57:44 ossec-agent[13816] start_agent.c:85 at connect_server(): INFO: Trying to connect to server (192.168.112.128:1514/udp).
2018/12/24 15:57:46 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:51 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:57:56 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:58:01 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:58:05 ossec-agent[13816] start_agent.c:237 at start_agent(): WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.112.128'.
2018/12/24 15:58:06 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:58:11 ossec-agent[13816] state.c:66 at write_state(): DEBUG: Updating state file.
2018/12/24 15:58:16 ossec-agent[13816] start_agent.c:85 at connect_server(): INFO: Trying to connect to server (192.168.112.128:1514/udp).

I disabled firewalld on ossec.server
[root@localhost etc]# systemctl status firewalld.service 
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)
[root@localhost etc]# 

And:
[root@localhost etc]# netstat -ntlup | grep ossec
udp6       0      0 :::1514                 :::*                                57457/ossec-remoted 
[root@localhost etc]# 

Please help me know where is error?
Thanks

**Comment by crakerkai** [comment]
Dear Sergio,

Sorry for late reply. I have a windows 10 machine which installed wazuh
agent and I want to connect to Redhat machine which installed ossec server.
But in Redhat machine, I can't see windows machine in manage list of
ossec server. So I pre-built more Redhat machine and install wazuh server
to manager and it's successful.
Initially, I wanna install ossec agent in windows 10 but I see it isn't
compatible (because we already had ossec server is available). So I turned
ideal into wazuh agent in other to be compatible with windows 10.

Thanks for your help,

*Huỳnh Đạt Nghĩa (Pm)*
*Phone*: *01882259775*
*FB: **https://www.facebook.com/langtudota.peterhuynh
<https://www.facebook.com/langtudota.peterhuynh>*
*Linkedin:* https://www.linkedin.com/in/ngh%C4%A9a-hu%E1%BB%B3nh-8aa532161/

**Comment by Cerv1** [comment]
Hi @crakerkai,

So, It's everything okay or you need some help? If so, please paste here the output of the commands I sent you and I'll be glad to help you.

Best regards,
Cerv1.
