### ISSUE TITLE
Check Wazuh agent compatibility with the new version of Fedora 40

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#21652]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of Fedora 40 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/21649

- Docker image: https://hub.docker.com/_/fedora (`40`)

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/faad7034-0b83-4216-aa07-73f0acee43b7" alt="Con_dash">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/f451946b-b7f9-46b2-a98c-cf21021317e7" alt="Console">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e378f71b-1034-46d5-81b6-7e823605c186">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e6072e3f-4539-420a-8281-a230b455e4b4">
</details>



## :green_circle: Vulnerability detector


<details>
<summary>Manager Config</summary>

  ```
    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <os allow="Fedora Linux-40">9</os>
      <update_interval>1m</update_interval>
    </provider>
  ```
</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/4887a143-6aae-436e-ac1f-597795eb2cba">
</details>

## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>012</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/ec30979f-1f3e-4c96-9381-9da6f916377b">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e9018b60-5af2-4667-86be-e7643eafcfbe">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ef526ee9-b7b9-47c1-b194-bb4155a743b8">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/ae252f8c-4f26-48b2-9443-70f52fdf2703">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/cdea520c-f9ef-46ef-bcaa-d2f8e9f66706">
</details>

**Comment by MarcelKemp** [comment]
LGTM!

**Comment by mjcr99** [comment]
LGTM
