### ISSUE TITLE
Improve wazuh-apid function definition structure

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh#21654]
|Wazuh version|Component|
|---|---|
| 4.9 | api |

## Description
The current `wazuh-apid` script defines functions like `start`, `configure_ssl`, and many others before the `if __name__ == '__main__'` block. In this block there are many imports required by those functions, causing the linter to mark errors because the imports are not made before the declaration.

A possible solution is to move those functions to a new file, reducing the script size and code complexity, and making it easier to develop unit tests for those functions.

The `alogging.py` file is also a candidate to be moved away from the API module, because it is only used by the `wazuh-api` script.

If functions are moved to a different module, new unit tests should be added for them. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Updated

Started reading and understanding the `wazuh-apid` script for the refactor.

**Comment by RamosFe** [comment]
Blocked until https://github.com/wazuh/wazuh/pull/20428 is finished!

**Comment by Selutario** [comment]
Please @RamosFe, as part of this development, also replace these `print()` with `logger.error()`: 
https://github.com/wazuh/wazuh/blob/ea9c847ba306cb488ae20cc2fb723c44806f8855/api/scripts/wazuh-apid.py#L428-L433

There are failures when starting the API that cannot be read in the logs because of this.

**Comment by Selutario** [comment]
We won't do this as part of the Connexion 3.0 API epic:
- https://github.com/wazuh/wazuh/issues/20748

**Comment by Selutario** [comment]
This won't be done for now as there are bigger priorities. It might be reopened in the future if needed.
