### ISSUE TITLE
Wazuh Manager single CPU utilisation 

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#2166]
Hi Team,

We are running wazuh on docker. This is the virtual machine and the hardware specialisation are;
CPU: 8 core
RAM: 32 GB
The wazuh module process is using 100% cpu  **/var/ossec/bin/wazuh-modulesd** . 
I have define the above we  have assign total 8 cpu for server but why it is using only one core cpu.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

we need to check your **ossec.conf** file in order to detect whats happening. Its normal to have a 100% CPU usage for wazuh-modulesd when starting the manager because if you have **syscollector** enabled, it will process all the packages received. 

The same applies for all wazuh agents reporting syscollector packages to the manager. Also having vulnerability detector enabled consumes a lot of CPU when processing all the packages.

Best regards.

**Comment by gyanprakashsahu** [comment]
Hi @TJOSERAFAEL ,

We have assign total 8 cpu to the vm. My point is why wazuh-modulesd is using single cpu.
let me know if wazuh is single core application.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

wazuh-modulesd creates **one thread per module** defined in your ossec.conf file. If you need more information please let us know.

Best regards.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

the operating system should do it for you. Right now there isn't any feature for explicitly assigning a thread to a cpu core without modifying wazuh's source code.

Can you please post all the wodles that you have in your ossec.conf?

Best regards.

**Comment by gyanprakashsahu** [comment]
Hi @TJOSERAFAEL ,
I understand, I am using many application on vm and the most application have self process distribution according to assigned cpu. If application is single core based then it should use only single cpu.

Please find here wodles configuration.
 
```/wo
  <wodle name="vulnerability-detector">
    <disabled>no</disabled>
    <interval>24h</interval>
    <run_on_start>yes</run_on_start>
    <feed name="ubuntu-18">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
    <feed name="redhat-7">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
    <feed name="debian-9">
      <disabled>yes</disabled>
      <update_interval>1h</update_interval>
    </feed>
  </wodle>

  </wodle>

  <wodle name="vulnerability-detector">
    <disabled>no</disabled>
    <interval>24h</interval>
    <run_on_start>yes</run_on_start>
    <feed name="ubuntu-18">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
    <feed name="redhat-7">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
    <feed name="debian-9">
      <disabled>yes</disabled>
      <update_interval>1h</update_interval>
    </feed>
  </wodle>

    <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>

   <wodle name="cis-cat">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>
    <java_path>wodles/java</java_path>
    <ciscat_path>wodles/ciscat</ciscat_path>
  </wodle>

  <!-- Osquery integration -->
  <wodle name="osquery">
    <disabled>yes</disabled>
    <run_daemon>yes</run_daemon>
    <log_path>/var/log/osquery/osqueryd.results.log</log_path>
    <config_path>/etc/osquery/osquery.conf</config_path>
    <add_labels>yes</add_labels>
  </wodle>

   <wodle name="docker-listener">
    <disabled>no</disabled>
  </wodle>

  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-centos-7-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>

  </wodle>```

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

thank you for submitting your configuration. As i said above syscollector takes huge part of the CPU usage. If you have many agents reporting packages, that could be the root cause of the problem. 

Is **wazuh-modulesd** 100% all the time?

Best regards.

**Comment by gyanprakashsahu** [comment]
Hi @TJOSERAFAEL ,

Most of time 100% usages. My point is if i have assign 8 cpu for the wazuh manager then why it is not using other one. 
I think wazuh manager is single core application.

**Comment by vikman90** [comment]
Hi @gyanprakashsahu,

Could you let us know if you still have this problem?

Let me clarify a bit this point:

Indeed, Modulesd is a multi-thread process: it deploys one thread per module. Depending on the particular design of each module, they may create secondary threads.

According to your configuration:
- Vulnerability Detector appears twice in the configuration, the second stanza will overwrite the first one.
- Syscollector is enabled.

Both Vulnerability Detector and Syscollector are single-threaded modules. So, Modulesd may reach a peak of 200% CPU usage.

Syscollector is expected to run quick scans every day (24h). Each scan should take a few seconds. This is an example:
```
2019/02/02 19:37:58 wazuh-modulesd:syscollector: INFO: Module started.
2019/02/02 19:37:59 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2019/02/02 19:38:07 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

On the other hand, Vulnerability Detector performs vulnerability database fetching and synchronization, and vulnerability matching against the software list of each agent. This module may consume 100% of CPU for a long time, but it's currently designed as a single-thread module.

Please take a look at your logs to confirm us that Syscollector is not taking too much time to complete. If so, then Vulnerability Detector is using 100% CPU most of the time.

Can you take a look at your logs for Vulnerability Detector? The most CPU-intensive stage is the agent software matching, it takes about one second per agent.

Hope it helps.
Best regards.

**Comment by vikman90** [comment]
Closing issue due to lack of response.
