### ISSUE TITLE
Modify install file to deploy the 'wazuh-keystore' tool

### ISSUE THREAD

**Issue by tdrauncieal** [wazuh/wazuh#21668]
### Description

This issue involves modifying the installation of  `wazuh-keystore` tool, which will be located in the `bin` directory. This tool is essential for managing the keystore within the Wazuh environment.

This issue is related to [#2791](https://github.com/wazuh/wazuh-packages/issues/2791) which complies with the necessary changes in [wazuh-packages](https://github.com/wazuh/wazuh-packages)

#### Changes Required

The following changes are necessary to achieve this:

1. Update the installation script to add the new `wazuh-keystore` tool. 

### Definition of Done

- The `wazuh-keystore` tool is correctly placed in the `bin` directory during installation.
- The changes are tested and verified to work seamlessly with the existing installation process for RPM and DEB packages.

**Comment by ncvicchi** [comment]
LGTM!
