### ISSUE TITLE
Implementing a Full Clean Feature for Inventory Management

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21661]
### Problem Description
Currently, the process of cleaning the inventory requires obtaining IDs from the Wazuh-DB orchestration, which can be cumbersome and inefficient. A need has been identified for a 'full clean' feature that can remove all items from the inventory directly, without the need to interact with the Wazuh-DB for IDs. This feature would streamline the process of resetting or refreshing the inventory, making it more efficient and user-friendly.

### Expected Behavior
The system should provide a 'full clean' functionality that allows users to clear the entire inventory with a single action. This process should bypass the need to retrieve IDs from the Wazuh-DB orchestration, thus simplifying and speeding up inventory management.

#### Story 1: As a System Administrator
- **I want to be able to perform a full clean of the inventory with a single command or action**, so that **I can quickly reset or refresh the inventory without complex procedures.**

#### Story 2: As a Security Analyst
- **I want a straightforward way to clear the inventory**, so that **I can efficiently manage and update the system's data without unnecessary steps.**

### Steps to Reproduce
N/A - This is a feature request for new functionality.

### Definition of Done Checklist
- [ ] Design and implement the 'full clean' feature for inventory management.
- [ ] Ensure the feature removes all items from the inventory without needing IDs from Wazuh-DB.
- [ ] Conduct thorough testing to confirm the feature works as expected under various scenarios.
- [ ] Update system documentation to include instructions and guidelines for using the new 'full clean' feature.

### Additional Information
Feedback from system administrators and security analysts who have experienced challenges with the current inventory cleaning process will be considered in the development of this feature.

### Possible Solutions
The development of a direct command or API endpoint that triggers the full clean process is a potential solution. This command should have safeguards to prevent accidental usage, such as confirmation prompts or the need for specific user permissions.

### Deadline
To be determined (TBD)

---

**Comment by sebasfalcone** [comment]
This feature will be implemented here:
- https://github.com/wazuh/wazuh/pull/21446
