### ISSUE TITLE
App and API version mismatched

### ISSUE THREAD

**Issue by sghorshine** [wazuh/wazuh#21673]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2 | API | Manager/Agent | Packages/Sources | Ubuntu 20.04 |

I have installed wazuh agent and wazuh manager of same version. And also all the indexer, dashboard, manager are of same version. Here is the output of the commands executed...

root@wazuh:/var/ossec/bin# apt show wazuh-manager | grep Version
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Version: **4.7.2-1**
root@wazuh:/var/ossec/bin# apt show wazuh-dashboard | grep Version
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Version: **4.7.2-1**
root@wazuh:/var/ossec/bin# apt show wazuh-indexer | grep Version
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Version: **4.7.2-1**
root@wazuh:/var/ossec/bin#

But still when I start my wazuh dashboard I have encountered the APP version and API version mismatched error during health-check.

**Comment by AlexRuiz7** [comment]
Clear your browser's cache and try again.
