### ISSUE TITLE
Vulnerability Scanner - Add `match` Function to enable version compatibility checking

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#21675]
## Description

To facilitate the reuse of the implemented logic in [versionMatcher](https://github.com/wazuh/wazuh/tree/4.8.0/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/versionMatcher) across multiple projects, there is a need to introduce a new function that allows checking if a version is compatible with a specific versioning type.

## Expected

The objective of this issue is to add a function named `match` to the `versionMatcher` module. This function should take a version (string) and a version type (VersionObjectType) as parameters and perform the matching. In case of a positive match, the function should return true.

**Use Cases:**

1. **Version Compatibility Check:**
   - Call the `match` function with a version string and a specified version type.
   - Confirm that the function returns true if the version is compatible with the specified version type.
   - Confirm that the function returns false if the version is not compatible with the specified version type.

## DoD

- [x] Add or Update Unit and Component.
- [ ] Compliance with:
  - [ ] [RTR](https://github.com/wazuh/wazuh/blob/dev-14153-vulndet-refactor/src/wazuh_modules/vulnerability_scanner/doc/rtr.md)
  - [x] [GitHub Actions](https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-tests.yml)
- [ ] Add or Update any relevant documentation to reflect the changes made.

**Comment by Damian-Mangold** [comment]
During the implementation of this functionality, a bug was identified in the matching logic for Amazon Linux versioning. The problem observed is that it always returns a positive result, preventing a full set of tests for the new functionality.

The issue has been reported and development has been blocked until the fix is implemented.

- [ ] https://github.com/wazuh/wazuh/issues/21686

**Comment by Damian-Mangold** [comment]
The ETA is updated to February 8 taking into account the ETA of the blocking issue.

**Comment by tsarquis88** [comment]
# Update

Issue not more blocked. Missing tests were added. Moving to RTR.
