### ISSUE TITLE
MacPorts github workflow test is unstable. 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#21699]
# Description 

It was found that often the port (MacPorts package) installation fails https://github.com/wazuh/wazuh/actions/runs/7747879778/job/21129329585?pr=21446. It is necessary to find what is causing this. 
It was successful in another PR https://github.com/wazuh/wazuh/actions/runs/7747046868/job/21126638661?pr=21688 

![image](https://github.com/wazuh/wazuh/assets/13010397/28ae175a-9153-49b7-9d39-6f73d6666cf0)

![image](https://github.com/wazuh/wazuh/assets/13010397/e8233290-d063-4d80-abec-90d28d5d912b)

![image](https://github.com/wazuh/wazuh/assets/13010397/65044615-0dcc-44e7-9b32-1b9245056267)

# Dod 

- [ ] Investigate the issue. 
- [ ] Propose and implement a fix.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
