### ISSUE TITLE
Update VD content file permissions

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#21693]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | Github Actions | Manager | - | - |

## Description
It was found an error in the `check_files` of the `Test_upgrade_tier`
- https://github.com/wazuh/wazuh-jenkins/issues/6191

This is due to the permission of the generated VD content:
https://github.com/wazuh/wazuh/blob/f03b42dc0e8ffc9c47216f948e6ecd585323f4bf/.github/workflows/vulnerability-scanner-generate-database.yml#L90

## DoD
- [ ] The content has the right permissions

**Comment by MiguelazoDS** [comment]
# Testing 
Analyzing solution with @LucioDonda .
