### ISSUE TITLE
Addressing Technical Debt for Unit Tests in New Orchestrations of VD

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21718]
### Problem Description
The new orchestrations included in the Virtual Device (VD) currently lack comprehensive Unit Tests (UTs), leading to technical debt that can impact the reliability and maintainability of the system. There is a critical need to implement UTs to cover these new orchestrations, ensuring that they function correctly and are resilient to changes and updates.

### Expected Behavior
All new orchestrations within the VD should have corresponding Unit Tests that validate their functionality and performance under various conditions. This will not only reduce technical debt but also enhance the overall stability and quality of the system.

#### Story 1: As a Developer
- **I want to ensure that all new orchestrations in the VD are covered by Unit Tests**, so that **I can confidently make changes and know that the core functionalities remain unaffected.**

#### Story 2: As a Quality Assurance Engineer
- **I want comprehensive UT coverage for the new VD orchestrations**, so that **I can identify and address potential issues early in the development cycle, ensuring a higher quality product.**

### Steps to Reproduce
N/A - This issue focuses on the implementation of new tests rather than reproducing a specific bug.

### Definition of Done Checklist
- [x] Identify all new orchestrations in the VD that are currently lacking UT coverage.
- [x] Develop and implement Unit Tests for these orchestrations, ensuring comprehensive coverage.
- [x] Integrate the new UTs into the continuous integration process to automatically verify the integrity of the orchestrations on future changes.
- [x] Review and refine existing testing strategies to prevent similar technical debt from occurring in the future.

### Additional Information
Documentation on the specific functionalities of the new orchestrations, along with any existing testing frameworks and guidelines, will be provided to assist in the UT development process.

### Possible Solutions
- Adopting a Test-Driven Development (TDD) approach for future features to ensure that UTs are considered at the outset.
- Allocating dedicated time and resources for the development and maintenance of UTs to address and prevent technical debt.

### Deadline
To be determined (TBD)

---

**Comment by pereyra-m** [comment]
## Update

In particular, we are talking about the new classes added at #21446:
- src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/CleanUpData.hpp
- src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/fetchAllAgentsFromGlobalDb.hpp
- src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/queryAllPackages.hpp

**Comment by MiguelazoDS** [comment]
# Update 02/26 
## Multiple errors analysis 

They seem not related to the UTs, several errors were found during vulnerability scan execution 

https://github.com/wazuh/wazuh/pull/22013/checks?check_run_id=21979395255

**Comment by MiguelazoDS** [comment]
# Update 02/26 
## Multiple errors analysis 

Not related to the UTs, several errors were found during vulnerability scan execution.

https://github.com/wazuh/wazuh/pull/22013/checks?check_run_id=21979395255
