### ISSUE TITLE
Enable the debug information generation by default with all optimizations

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21731]
### Description

This issue aims to modify the Makefile to enable compilation with debug symbols while maintaining optimizations for Linux, Windows, and macOS platforms. Debug symbols are essential for debugging issues, and we want to ensure our project is built efficiently across all supported environments.

### Proposed Changes

The following changes will be made to the Makefile:

1. **Debug Symbols:** Add flags to include debug symbols during compilation. This is crucial for debugging issues in the code.

2. **Optimizations:** Ensure that the project is compiled with optimizations appropriate for each platform (Linux, Windows, macOS) while retaining debug symbols.

### Implementation Steps

The following steps will be taken to implement the proposed changes:

1. **Review Makefile:** Examine the existing Makefile to understand the current compilation process.

2. **Add Debug Flags:** Modify the Makefile to add the necessary debug flags for each platform.

3. **Optimizations:** Configure the Makefile to apply optimizations suitable for Linux, Windows, and macOS.

4. **Testing:** Verify the modified Makefile by building the project on each platform and checking for correct debug symbols and optimizations.

### Impact

Detail any potential impacts of this change, such as increased binary size or compilation time. Also, mention any benefits related to debugging and performance improvements.

### Definition of Done

- The Makefile is modified to include debug symbols without compromising platform-specific optimizations, this includes the CMake projects(main CMakeLists and the syscollector projects (dataprovider, dbsync, rsync, syscollector)), which need to set `-DCMAKE_BUILD_TYPE=RelWithDebInfo` during the project building.
- The project successfully compiles on Linux, Windows, and macOS with the intended settings.
- A test build is performed to verify the correctness of debug symbols and optimizations.

**Comment by Leoquicenoz** [comment]
## Update

1. Research about software to generate debugging symbols files.
2. Take a look at the Makefile, understand code and try to determine what changes should be made.

**Comment by Leoquicenoz** [comment]
## Update

Continue researching about Makefile and start adding code.

**Comment by Leoquicenoz** [comment]
## Update

1. Add in the `/src/Makefile` the compilation `-DCMAKE_BUILD_TYPE=RelWithDebInfo` as follows: 

```
SHARED_MODULES_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
GTEST_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSCOLLECTOR_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSINFO_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSCHECK_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
WAZUH_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
``` 
It is evident that once this change is made, there is an increase in the compilation time of about 25 seconds, the binaries that are generated with the normal compilation and with these changes are compared and it is determined that there are no major changes in them, so you should try something different (the size of the binaries also had no changes).

2. The following is changed in the `/src/wazuh_modules/syscollector/CMakeLists.txt` file: 

```
set(CMAKE_CXX_FLAGS_DEBUG "-g")
if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  set(CMAKE_CXX_FLAGS_RELEASE "-O2")
else()
  set(CMAKE_CXX_CXX_FLAGS_RELEASE "-O2 -s")
endif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
```
This is because the `-DCMAKE_BUILD_TYPE=RelWithDebInfo` compilation, according to research, resembles the `-O2` optimization, so we wanted to do this test and see what results were obtained.
In this case the compilation time also increased about 5 seconds and the size of the wazuh-modulesd binary increased a little, but it is not the expected behavior.

**Comment by Leoquicenoz** [comment]
## Update

Another modification is made to the file `/src/Makefile`:

```
SHARED_MODULES_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
GTEST_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSCOLLECTOR_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSINFO_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
SYSCHECK_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo
WAZUH_RELEASE_TYPE=-DCMAKE_BUILD_TYPE=RelWithDebInfo

OSSEC_CFLAGS+=-g
AR_LDFLAGS+=-g
``` 

This causes the compilation to add the debug symbols, so the binaries increase in size, for example the binary obtained from wazuh-modulesd goes from `923 kB` to `3.4 MB` in size. 

![Screenshot from 2024-02-14 18-34-53](https://github.com/wazuh/wazuh/assets/106568370/65035821-80b2-480a-9f33-6d9835da866c)

![Screenshot from 2024-02-15 11-17-09](https://github.com/wazuh/wazuh/assets/106568370/03528180-d5e4-4886-a682-76076de1ed39)


Using objdump, we have been analyzing and comparing the binaries obtained when compiling with and without the `-DCMAKE_BUILD_TYPE=RelWithDebInfo` flag, significant differences are observed when executing the commands: `objdump -e wazuh-modulesd` or `objdump -g wazuh-modulesd`.

```
-g, --debugging Display debug information in object file
-e, --debugging-tags Display debug information using ctags style
``` 

What seems strange to me is that when running `objdump -t wazuh-modulesd` (display the contents of the symbol table), should appear "**no symbols**" for a normal compilation, but in the case of compilation with and without `-DCMAKE_BUILD_TYPE=RelWithDebInfo`, I get the same table (here is a sample of the table obtained):

```
SYMBOL TABLE:
0000000000000000 l    df *ABS*	0000000000000000              Scrt1.o
000000000000038c l     O .note.ABI-tag	0000000000000020              __abi_tag
0000000000000000 l    df *ABS*	0000000000000000              main.c
000000000000aff0 l     F .text	0000000000000088              wm_help
000000000000b080 l     F .text	000000000000004d              wm_cleanup
000000000009a298 l     O .rodata	000000000000000b              __func__.1
000000000000b0d0 l     F .text	000000000000007e              wm_handler
000000000009a288 l     O .rodata	000000000000000b              __func__.0
00000000000cc36c l     O .bss	0000000000000004              flag_foreground
000000000009a2b1 l     O .rodata	0000000000000005              __func__.3
000000000009a2a8 l     O .rodata	0000000000000009              __func__.2
0000000000000000 l    df *ABS*	0000000000000000              crtstuff.c
000000000000af30 l     F .text	0000000000000000              deregister_tm_clones
000000000000af60 l     F .text	0000000000000000              register_tm_clones
000000000000afa0 l     F .text	0000000000000000              __do_global_dtors_aux
00000000000cc368 l     O .bss	0000000000000001              completed.0
00000000000caa18 l     O .fini_array	0000000000000000              __do_global_dtors_aux_fini_array_entry
000000000000afe0 l     F .text	0000000000000000              frame_dummy
00000000000caa10 l     O .init_array	0000000000000000              __frame_dummy_init_array_entry
0000000000000000 l    df *ABS*	0000000000000000              wmcom.c
000000000009a610 l     O .rodata	0000000000000010              __func__.3
000000000009a620 l     O .rodata	000000000000000f              __func__.4
000000000009a600 l     O .rodata	000000000000000b              __func__.2
000000000009a5f0 l     O .rodata	000000000000000b              __func__.1
000000000009a5e0 l     O .rodata	000000000000000b              __func__.0
0000000000000000 l    df *ABS*	0000000000000000              wm_exec.c
000000000000b980 l     F .text	000000000000019c              reader
000000000009aa86 l     O .rodata	0000000000000007              __func__.3
00000000000cc3a0 l     O .bss	0000000000000028              wm_children_mutex
000000000009aaa0 l     O .rodata	0000000000000016              __func__.5
00000000000cc380 l     O .bss	0000000000000020              wm_children
000000000009aa78 l     O .rodata	000000000000000e              __func__.2
000000000009aa68 l     O .rodata	000000000000000e              __func__.1
000000000009aa90 l     O .rodata	0000000000000008              __func__.4
000000000009aa50 l     O .rodata	0000000000000011              __func__.0
0000000000000000 l    df *ABS*	0000000000000000              wmodules.c
00000000000cc3e0 l     O .bss	0000000000000004              wm_gid
00000000000cb2c0 l     O .data.rel.ro	0000000000000018              default_modules
000000000009ae70 l     O .rodata	000000000000001e              __func__.8
000000000009ae60 l     O .rodata	0000000000000009              __func__.7
000000000009ae40 l     O .rodata	000000000000001c              __func__.6
000000000009ae30 l     O .rodata	000000000000000c              __func__.5
000000000009ae20 l     O .rodata	0000000000000010              __func__.4
000000000009ae08 l     O .rodata	000000000000000b              __func__.3
000000000009adf8 l     O .rodata	000000000000000e              __func__.2
000000000009ade0 l     O .rodata	0000000000000011              __func__.1
000000000009adc0 l     O .rodata	0000000000000014              __func__.0
0000000000000000 l    df *ABS*	0000000000000000              wm_router.c
000000000000dbb0 l     F .text	0000000000000005              wm_router_destroy
000000000000dbc0 l     F .text	000000000000012e              wm_router_main
000000000009afe8 l     O .rodata	000000000000000f              __func__.1
000000000000dd40 l     F .text	0000000000000071              wm_router_stop
000000000009aff8 l     O .rodata	000000000000000f              __func__.2
000000000009afd8 l     O .rodata	000000000000000f              __func__.0
0000000000000000 l    df *ABS*	0000000000000000              md5_op.c
0000000000000000 l    df *ABS*	0000000000000000              sha1_op.c
000000000009b0c0 l     O .rodata	0000000000000022              __func__.0
0000000000000000 l    df *ABS*	0000000000000000              sha256_op.c
0000000000000000 l    df *ABS*	0000000000000000              debug_op.c
```

**Comment by Leoquicenoz** [comment]
## Update

1. The branch [enhancement/21731-enable-debug-symbols](https://github.com/wazuh/wazuh/tree/enhancement/21731-enable-debug-symbols) is created, in which the `CMakeLists.txt` files are modified so that the compile flag is applied by default: 

```
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE RelWithDebInfo)
endif()
``` 

2. Using `gdb` to perform an analysis on the binaries and try to visualize the debug symbols that were added in the compilation, using the commands: `info types` , `info functions` , `info variables` , yields a lot of information, for example:

```
Non-debugging symbols:
0x0000000000007000  _init
0x0000000000008520  free@plt
0x0000000000008530  __cxa_finalize@plt
0x0000000000008540  OPENSSL_sk_num@plt
0x0000000000008550  fsetpos@plt
0x0000000000008560  chmod@plt
0x0000000000008570  cJSON_PrintUnformatted@plt
0x0000000000008580  BIO_new_mem_buf@plt
0x0000000000008590  SSL_connect@plt
0x00000000000085a0  seteuid@plt
0x00000000000085b0  chdir@plt
0x00000000000085c0  fileno@plt
0x00000000000085d0  pthread_join@plt
0x00000000000085e0  dirname@plt
0x00000000000085f0  cJSON_ParseWithOpts@plt
0x0000000000008600  dup2@plt
0x0000000000008610  pthread_cond_destroy@plt
0x0000000000008620  SSL_set_bio@plt
0x0000000000008630  cJSON_IsObject@plt
0x0000000000008640  X509_STORE_load_locations@plt
0x0000000000008650  EVP_DigestInit@plt
0x0000000000008660  BF_set_key@plt
0x0000000000008670  ERR_print_errors_fp@plt
0x0000000000008680  mktime@plt
0x0000000000008690  memset@plt
0x00000000000086a0  ftell@plt
0x00000000000086b0  getgid@plt

Non-debugging symbols:
0x000000000000038c  __abi_tag
0x0000000000086000  _IO_stdin_used
0x0000000000086290  __func__.0
0x00000000000862a0  __func__.1
0x00000000000862b0  __func__.2
0x00000000000862b9  __func__.3
0x00000000000865f0  __func__.0
0x0000000000086600  __func__.1
``` 

Then I use the `file` command to obtain information from the binaries and find the following difference when comparing the resulting binaries with and without the `-DCMAKE_BUILD_TYPE=RelWithDebInfo flag`

- Output of the binary resulting from the compilation including the flag:

```
wazuh-modulesd: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=98b22209523de63ef90b2a25d050cd985a1fea00, for GNU/Linux 3.2.0, with debug_info, not stripped
``` 

- Output of the binary resulting from normal compilation

```
wazuh-modulesd: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=1561feb818a600f9fbf6b7d107fc9978775addf1, for GNU/Linux 3.2.0, not stripped
``` 
So we can be sure that if we are adding debug information.

I also tried to generate an `RPM` package from this branch (using information found on the web such as: https://byte-mind.net/como-construir-tu-propio-paquete-rpm/, it was not successful, so I also tried using Jenkins, also without success. But through the command `debug_symbols/development_branch/wazuh# ./install.sh` I was able to install a manager without any problem or warning or error message.

3. The compilation of Linux and Windows agents are executed and it is verified that the compilation is successful.

**Comment by Leoquicenoz** [comment]
## Update

1. The `.exe` files resulting from the compilation of windows agents are analyzed with `gdb` and the outputs are as follows: 

```
File win32/win_agent.c:
35:	void agent_help();
48:	int main(int, char **);

File win32/win_service.c:
103:	int CheckServiceRunning();
132:	int InstallService(char *);
253:	void OssecServiceCtrlHandler@4(DWORD);
307:	void OssecServiceStart@8(DWORD, LPTSTR *);
208:	int UninstallService();
285:	void WinSetError();
291:	int os_WinMain(int, char **);
39:	int os_start_service();
68:	int os_stop_service();

File win32/win_utils.c:
395:	int MQReconnectPredicated(const char *, _Bool (*)());
366:	int SendMSG(int, const char *, const char *, char);
310:	int SendMSGAction(int, const char *, const char *, char);
372:	int SendMSGPredicated(int, const char *, const char *, char, _Bool (*)());
389:	int StartMQ(const char *, short, short);
378:	int StartMQWithSpecificOwnerAndPerms(const char *, short, short, uid_t, gid_t, mode_t);
400:	char *get_agent_ip_legacy_win32();
63:	int local_start();
38:	DWORD skthread@4(LPVOID);
52:	void stop_wmodules();

Non-debugging symbols:
0x004014f0  __gcc_register_frame
0x004015a0  __gcc_deregister_frame
0x004c0a5c  yaml_parser_set_input_file
0x004c0a6c  yaml_parser_load
0x004c0a7c  yaml_parser_initialize
0x004c0a8c  yaml_parser_delete
0x004c0a9c  yaml_document_get_root_node
0x004c0aac  yaml_document_get_node
0x004c0abc  yaml_document_delete
0x004c0acc  uncompress
0x004c0adc  pcre2_match_data_free_8
0x004c0aec  pcre2_match_data_create_from_pattern_8
0x004c0afc  pcre2_match_8
0x004c0b0c  pcre2_get_ovector_pointer_8
0x004c0b1c  pcre2_compile_8
0x004c0b2c  pcre2_code_free_8
0x004c0b3c  gzwrite
0x004c0b4c  gzread
0x004c0b5c  gzopen
0x004c0b6c  gzerror
0x004c0b7c  gzeof
0x004c0b8c  gzclose
0x004c0b9c  curl_slist_free_all
0x004c0bac  curl_slist_append
0x004c0bbc  curl_easy_strerror
0x004c0bcc  curl_easy_setopt
0x004c0bdc  curl_easy_perform
0x004c0bec  curl_easy_init
0x004c0bfc  curl_easy_getinfo
0x004c0c0c  curl_easy_cleanup
0x004c0c1c  compress2
0x004c0c2c  cJSON_free@4
0x004c0c3c  cJSON_SetNumberHelper@12
0x004c0c4c  cJSON_ReplaceItemInObject@12
0x004c0c5c  cJSON_PrintUnformatted@4
0x004c0c6c  cJSON_Print@4
0x004c0c7c  cJSON_ParseWithOpts@12
``` 
It is also evident the change in the compilation flags according to the changes made in the code. 

![image](https://github.com/wazuh/wazuh/assets/106568370/a8539e53-f7d3-4a9e-862d-3a8bd10d0cbf)

2. A request is made to the `CICD` team for a `MacOS Ventura` instance, to perform the compilation tests on it and by analyzing the binaries with gdb I get: 

```
File wazuh_modules/wm_syscollector.c:
45:	const wm_context WM_SYS_CONTEXT;
36:	const char *WM_SYS_LOCATION;
41:	_Bool need_shutdown_wait;
70:	int queue_fd;
43:	_Bool shutdown_process_started;
42:	pthread_mutex_t sys_reconnect_mutex;
39:	pthread_cond_t sys_stop_condition;
40:	pthread_mutex_t sys_stop_mutex;
55:	void *syscollector_module;
56:	syscollector_start_func syscollector_start_ptr;
57:	syscollector_stop_func syscollector_stop_ptr;
69:	long syscollector_sync_max_eps;
58:	syscollector_sync_message_func syscollector_sync_message_ptr;

File wazuh_modules/wm_task_general.c:
39:	const char *task_manager_commands_list[8];
14:	const char *task_manager_json_keys[19];
50:	const char *task_manager_modules_list[2];
55:	const char *task_statuses[7];

File wazuh_modules/wmodules.c:
19:	int wm_task_nice;
18:	wmodule *wmodules;
30:	static const void *default_modules[2];
20:	static gid_t wm_gid;

Non-debugging symbols:
0x00000001000cc000  Read_Authd.xml_disabled
0x00000001000cc008  Read_Authd.xml_port
0x00000001000cc010  Read_Authd.xml_ipv6
0x00000001000cc018  Read_Authd.xml_use_source_ip
0x00000001000cc020  Read_Authd.xml_force_insert
0x00000001000cc028  Read_Authd.xml_force_time
0x00000001000cc030  Read_Authd.xml_force
0x00000001000cc038  Read_Authd.xml_purge
0x00000001000cc040  Read_Authd.xml_use_password
0x00000001000cc048  Read_Authd.xml_limit_maxagents
0x00000001000cc050  Read_Authd.xml_ciphers
0x00000001000cc058  Read_Authd.xml_ssl_agent_ca
0x00000001000cc060  Read_Authd.xml_ssl_verify_host
0x00000001000cc068  Read_Authd.xml_ssl_manager_cert
0x00000001000cc070  Read_Authd.xml_ssl_manager_key
0x00000001000cc078  Read_Authd.xml_ssl_auto_negotiate
0x00000001000cc080  Read_Authd.xml_remote_enrollment
0x00000001000cc088  Read_Authd.xml_agents
0x00000001000cc090  w_read_force_config.xml_enabled
0x00000001000cc098  w_read_force_config.xml_key_mismatch
0x00000001000cc0a0  w_read_force_config.xml_disconnected_time
0x00000001000cc0a8  w_read_force_config.xml_after_registration_time
0x00000001000cc0b0  Read_Cluster.disabled
0x00000001000cc0b8  Read_Cluster.cluster_name
0x00000001000cc0c0  Read_Cluster.node_name
0x00000001000cc0c8  Read_Cluster.node_type
0x00000001000cc0d0  Read_Cluster.key
0x00000001000cc0d8  Read_Cluster.socket_timeout
0x00000001000cc0e0  Read_Cluster.connection_timeout
0x00000001000cc0e8  Read_Cluster.interval
0x00000001000cc0f0  Read_Cluster.nodes
0x00000001000cc0f8  Read_Cluster.hidden
0x00000001000cc100  Read_Cluster.port
0x00000001000cc108  Read_Cluster.bind_addr
0x00000001000cc110  Read_Cluster.C_VALID
0x00000001000cc170  get_paths_from_env_variable[DELIM]
0x00000001000cc82c  wm_sca_read_files.first_scan
0x00000001000ccb00  OS_BF_Str.cbc_iv
0x00000001000ccb10  OS_AES_Str.iv
0x00000001000ccbc8  randombytes[fh]
0x00000001000ccc80  get_unix_version[pattern]
0x00000001000ccc88  get_unix_version.pattern
0x00000001000ccc90  get_unix_version.pattern
0x00000001000ccc98  get_unix_version.pattern
0x00000001000ccca0  get_unix_version.pattern
0x00000001000ccca8  get_unix_version.pattern
0x00000001000cccb0  get_unix_version.pattern
0x00000001000cccb8  get_unix_version.pattern
0x00000001000cccc0  get_unix_version.pattern
0x00000001000cccc8  get_unix_version.pattern
0x00000001000cccd0  os_wait_primitive.just_unlocked
0x00000001000ccdf4  Read_Log.reported
0x00000001000cd3a0  getuname[muname]
0x00000001000cd5b0  log_builder_update_host_ip.host_ip
0x00000001000cd5e0  log_builder_update_host_ip.last_update
0x00000001000cd5f0  SendMSGAction.reported
0x00000001000cd6fc  current_files
0x00000001000cd700  maximum_files
0x00000001000cd704  total_files
0x00000001000cd708  w_logtest_conf
0x00000001000cd720  wm_debug_level
0x00000001000cd724  wm_kill_timeout
0x00000001000cd728  wm_max_eps
0x00000001000cd72c  sock_fail_time
0x00000001000cd730  bio_err
0x00000001000cd738  fp_pos
``` 
![Screenshot from 2024-02-20 18-23-43](https://github.com/wazuh/wazuh/assets/106568370/f4b95b4a-8f58-4a7e-9e6a-0324232c0169)

Comparing the binaries generated with and without the `-DCMAKE_BUILD_TYPE=RelWithDebInfo` compilation flag shows an increase in size: 

![image](https://github.com/wazuh/wazuh/assets/106568370/6cb8809d-7a99-411f-a7e4-26d96c986268)

**Comment by Leoquicenoz** [comment]
## Update

Changes are made to the code according to the requirements and optimizations are retained, some checks failed in its execution and it was determined that the reason why they failed is due to an incompatibility between the flags: `AR_LDFLAGS+=-g` and `IMAGE_TRUST_CHECKS=2`.

For the moment the `AR_LDFLAGS+=-g` flag was removed but we will investigate the reason for this behavior and if there is a different way to solve it.

**Comment by Leoquicenoz** [comment]
## Update

The ITs of branch `4.9.0` (base branch) are executed in Windows and Linux, looking to make a comparison with the ITs of the checks in the [PR](https://github.com/wazuh/wazuh/pull/22011), in Windows they all pass and in Linux they fail quite a lot. This gives us a quite different result than the one obtained with the enc32 branch, since in this one different tests fail.

<details><summary>Windows</summary>
<p>

![Screenshot from 2024-02-28 12-44-15](https://github.com/wazuh/wazuh/assets/106568370/801060b3-1968-443d-b8b9-66d6989059ca)

![Screenshot from 2024-02-28 12-45-07](https://github.com/wazuh/wazuh/assets/106568370/5b2098dc-2608-4e7c-b441-36b50e9e64cf)

![Screenshot from 2024-02-28 13-16-25](https://github.com/wazuh/wazuh/assets/106568370/42db5b41-6297-4cf6-a6a1-01ed79fb737e)

</p>
</details>

<details><summary>Linux</summary>
<p>

![Screenshot from 2024-02-28 16-56-36](https://github.com/wazuh/wazuh/assets/106568370/c8f1996e-a5ab-4b98-b178-6e6570c53767)

![Screenshot from 2024-02-28 16-56-07](https://github.com/wazuh/wazuh/assets/106568370/6dfbb792-583f-4f01-8b80-ba8acbdccbe0)

</p>
</details>

**Comment by Leoquicenoz** [comment]
## Update

After making some changes in the test environment, the `test_agentd` ITs are executed again, which are some of the ones that are failing in the PR and have an erratic behavior, sometimes they fail, sometimes they pass, sometimes only one fails and sometimes several.

![Screenshot from 2024-02-29 14-23-57](https://github.com/wazuh/wazuh/assets/106568370/985762a9-e2f2-47ac-9d0f-902161b83f78)

![Screenshot from 2024-02-29 15-52-02](https://github.com/wazuh/wazuh/assets/106568370/7bf8ac0c-e897-4257-8014-99025c0d4ad7)

**Comment by Leoquicenoz** [comment]
## Update

In all the tests performed, it has been evidenced that the execution of the test `test_agentd_state_config`, does not have a standard behavior and there is a factor (still unknown) that is influencing it to fail or not to fail, I have been based on the workflow determined for this test:

- https://github.com/wazuh/wazuh/blob/4.9.0/.github/workflows/integration-tests-agentd-tier-0-1-win.yml

And the steps are being followed correctly, but in spite of this the test results are different in each case

What has been observed is that they all have in common that they fail because the daemon cannot be stopped.

```
___ ERROR at teardown of test_agentd_state_config[Negative_state_interval] ____

request = <SubRequest 'daemons_handler' for <Function test_agentd_state_config[Negative_state_interval]>>

    @pytest.fixture()
    def daemons_handler(request: pytest.FixtureRequest) -> None:
        """Wrapper of `daemons_handler_implementation` which contains the general implementation.
    
        Args:
            request (pytest.FixtureRequest): Provide information about the current test function which made the request.
        """
>       yield from daemons_handler_implementation(request)

conftest.py:281: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
conftest.py:266: in daemons_handler_implementation
    services.control_service('stop')
``` 
The functions I am concentrating on are:

`daemons_handler_implementation` in the `/wazuh/tests/integration/conftest.py file`.

`control_service` in the file `/qa-integration-framework/src/wazuh_testing/utils/services.py`.
