### ISSUE TITLE
Document the dump generation process.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21738]
|Related issue|
|-|
|#9910|
|[#7278](https://github.com/wazuh/wazuh-documentation/issues/7278#top)|

## Description

This issue aims to update the documentation to explain how to generate the dump generation process, how to enable or disable the dump generation process in Wazuh after installation, and how to use the debug symbols to perform a post-mortem analysis.

## Goals
For every platform (Windows, macOS and Linux):
- Document the dump generation process
- Document how to enable or disable Wazuh's dump generation as well as core-dump automatic object upload
- Document how to perform a post-mortem analysis of a crash core-dump

## Plan

NOTE: WIP - Might be 1 documentation for all platform in one or all cases

- [ ] [Document the dump generation process for Windows](Link)
- [ ] [Document the dump generation process for macOS](Link)
- [ ] [Document the dump generation process for Linux](Link)
- [ ] [Document how to enable or disable Wazuh's dump generation as well as core-dump automatic object upload for Windows](Link)
- [ ] [Document how to enable or disable Wazuh's dump generation as well as core-dump automatic object upload for macOS](Link)
- [ ] [Document how to enable or disable Wazuh's dump generation as well as core-dump automatic object upload for Linux](Link)
- [ ] [Document how to perform a post-mortem analysis of a crash core-dump in macOS](Link)
- [ ] [Document how to perform a post-mortem analysis of a crash core-dump in Windows](Link)
- [ ] [Document how to perform a post-mortem analysis of a crash core-dump in Linux](Link)

**Comment by tdrauncieal** [comment]
This issue was replaced with the related one [#7278](https://github.com/wazuh/wazuh-documentation/issues/7278) in the [wazuh-documentation](https://github.com/wazuh/wazuh-documentation) project.
