### ISSUE TITLE
Mismatch in Agent ID Field Between VD Scans and Re-scans

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21744]
### Problem Description
There is a discrepancy in the `agentid` field format between the initial scan performed by the Vulnerability Detector (VD) and subsequent re-scans that fetch version information from the global database. The initial scan prefixes the version with `Wazuh - x.y.z`, whereas the re-scan does not include the `Wazuh - ` prefix. This inconsistency could potentially impact the functionality and performance of the indexer by causing mismatches or errors in version tracking and data aggregation.

### Expected Behavior
The `version` field format should be consistent across all scans and re-scans conducted by the VD, ensuring that data integrity and consistency are maintained in the system's database and that the indexer can accurately process and aggregate data without errors or mismatches.

### Steps to Reproduce
1. Perform a normal scan with the VD and note the `version` field format.
2. Execute a re-scan that retrieves version information from the global database and compare the `version` field format.
3. Observe any discrepancies and potential impacts on the indexer.

### Definition of Done Checklist
- [ ] Identify the root cause of the `version` field format discrepancy between scans and re-scans.
- [ ] Assess the impact of this discrepancy on the indexer's functionality and performance.
- [ ] Implement a solution to ensure consistency in the `version` field across all scans.
- [ ] Validate the solution through testing to confirm that the indexer processes data accurately.
- [ ] Update documentation to reflect the standardized format for the `version` field.

### Additional Information
Examples of version formats from both scans and re-scans, along with logs or reports from the indexer detailing any issues encountered due to the current discrepancy, will be helpful in addressing this issue.

![image](https://github.com/wazuh/wazuh/assets/27935340/6f80ed41-4e54-48c2-b493-dbc5660a3c05)

### Possible Solutions
- Standardizing the `version` field format at the source, ensuring that both scans and re-scans prepend the `Wazuh - ` prefix to the version number.
- Implementing a normalization process in the indexer or the data ingestion pipeline to align the `version` field formats before processing.

### Deadline
To be determined (TBD)

---

**Comment by pereyra-m** [comment]
@sebasfalcone I'll begin with the analysis, but this issue depends on the re-scans feature that is added by #21446 and it's blocked right now.

**Comment by sebasfalcone** [comment]
@pereyra-m #21446 now in progress waiting for rebase

**Comment by pereyra-m** [comment]
## RCA

There are at least two identified differences between the vulnerabilities reported after a synchronization event and a re-scan:
- Agent ID: the `agent` table in `global.db` has this field as an integer but **remoted** considers it as a string (it's read from `client.keys`). So the information added to the sync events has for example a `001` ID when the DB has `1`.
- Agent version: the agent keepalive sends the version with the word `Wazuh` added and it isn't removed before being inserted in the `version` field of the `agent` table. So the re-scan reports it with `Wazuh v4.8.0` and the sync event reports it with `v4.8.0`

## Proposed solutions 

### Agent ID

- One option is to add all the required `0` characters to the agent ID when it's converted to string after being collected from the `global.db`. This change adds a custom logic but only affects the re-scan events.
- Another option is to remove all the trailing `0` from the strings that **remoted** adds to the synchronization events. This would be a breaking change if the new vulnerability detector had been released, but we are still on time for this change, and this is the most logic approach.

### Agent version

- We could read the version field when it's collected from the `global.db` and remove the `Wazuh` word if found.

**Comment by pereyra-m** [comment]
@sebasfalcone 
I'm now re-taking this issue
