### ISSUE TITLE
Inconsistent Update of `ossec.conf` During Upgrade to 4.8.0

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21752]
### Problem Description
When upgrading from version 4.7.2 to 4.8.0, the `ossec.conf` file is not automatically updated to include the `vulnerability-detection` section. This oversight leads to the new version being inconsistent with the expected new format of the configuration, and as a result, the Vulnerability Detection (VD) module is disabled by default. This issue poses a significant risk to system security and functionality, as users may unknowingly operate without critical vulnerability detection capabilities.

### Expected Behavior
The upgrade process to version 4.8.0 should automatically update the `ossec.conf` file, incorporating the `vulnerability-detection` section to ensure the VD module is enabled by default. This will align the system configuration with the new version's features and security enhancements.

#### Story 1: As a System Administrator
- **I want the `ossec.conf` file to be automatically updated during the upgrade**, so that **all new features and configurations are correctly applied without manual intervention.**

#### Story 2: As a Security Analyst
- **I want to ensure that the VD module is enabled by default after an upgrade**, so that **the system's security posture is not inadvertently weakened.**

### Steps to Reproduce
1. Start with a system running version 4.7.2.
2. Upgrade the system to version 4.8.0 following the standard upgrade procedure.
3. Check the `ossec.conf` file for the presence of the `vulnerability-detection` section.

### Definition of Done Checklist
- [ ] Diagnose why the `ossec.conf` file is not being updated to include the `vulnerability-detection` section during the upgrade process.
- [ ] Develop a fix to ensure the `ossec.conf` file is correctly updated during the upgrade to version 4.8.0.
- [ ] Implement comprehensive testing to verify that the upgrade process correctly applies all configuration changes.
- [ ] Update the upgrade documentation to reflect any necessary steps or checks related to the configuration file update.

### Additional Information
Feedback from users who have encountered this issue, along with logs and system reports from the upgrade process, will be invaluable in identifying and resolving the problem.

### Possible Solutions
- Adjusting the upgrade script to include a step that specifically checks for and updates the `ossec.conf` file with the necessary `vulnerability-detection` section.
- Providing a patch or utility tool that users can run post-upgrade to ensure their configuration files are in line with version 4.8.0’s requirements.

### Deadline
To be determined (TBD)

---

**Comment by pereyra-m** [comment]
This is issue is related #20954

**Comment by sebasfalcone** [comment]
> This is issue is related https://github.com/wazuh/wazuh/pull/20954

Indeed, and this is the expected behaviour. Closing the issue
