### ISSUE TITLE
 `modulesd` stops working when a malformed message is received in `sync-database` subscriber

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21751]
### Problem Description
During the testing phase of issue #21446, it was observed that certain messages within the `sync-database` could lead to the freezing of `modulesd`, and in some cases, cause a segmentation fault (`segfault`) if the messages do not adhere to the expected standard format. This issue highlights a critical vulnerability in the system's resilience to malformed or unexpected input, potentially affecting stability and reliability.

### Expected Behavior
The system should robustly handle non-standard or malformed messages within the `sync-database`, ensuring that `modulesd` continues to operate correctly without freezing or crashing. This may involve dropping messages with incorrect formats and/or implementing stop mechanisms for threads handling database update events.

### Steps to Reproduce
1. Send a `sync-database` message with a non-standard format to the system.

For example:

```bash
cp $PATH_TESTTOOL /var/ossec/
./router_test_tool -m publisher -t sync-database
Send: {"agent_info":

{"agent_id":"001",

"agent_version":"4.8.0",

"agent_name":"test_agent_name",

"agent_ip":"10.0.0.1",

"node_name":"test_node_name"},

"action":"cleanupAgent"}
```

2. Observe the behavior of `modulesd`, noting any freeze or `segfault`.
3. Repeat with various malformed message formats to assess consistency of the issue.

### Possible Solutions
- Introducing message format validation at the entry point of the `sync-database` message processing pipeline.
- Implementing a watchdog mechanism that monitors `modulesd` for unresponsive behavior, with the ability to restart the process or thread safely.
- Developing a comprehensive testing suite to simulate a wide range of malformed messages and assess the system's response.

---

### Definition of Done Checklist
- [x] Investigate the root cause of `modulesd` freezing or crashing due to non-standard `sync-database` messages.
- [x] Implement a mechanism to validate `sync-database` messages before processing, dropping those with incorrect formats.
- [x] Conduct thorough testing with a range of message formats to ensure resilience to malformed inputs.

**Comment by pereyra-m** [comment]
## Update

Here we have an example of one of the segmentation fault generated

```
Rule: 1010 (level 5) -> 'Process segfaulted.'
Feb  5 17:32:32 pr-test kernel: [26996.046324] wazuh-modulesd[282526]: segfault at 7f0182adf791 ip 00007f0106011d3c sp 00007f01029fc7b0 error 4 in libvulnerability_scanner.so[7f0105f4b000+1ba000] likely on CPU 2 (core 2, socket 0)
```

**Comment by MiguelazoDS** [comment]
# Comments 

As mentioned in the issue the single line valid message expected is 

`{"agent_info":  {"agent_id":"001",  "agent_version":"4.8.0",  "agent_name":"test_agent_name",  "agent_ip":"10.0.0.1",  "node_name":"test_node_name"},  "action":"cleanupAgent"}`

**Comment by sebasfalcone** [comment]
Issue blocked by
- https://github.com/wazuh/wazuh/pull/21446
