### ISSUE TITLE
Conflict with master node configuration in Wazuh cluster using Kubernetes

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh#2175]
## Bug report

**OS**
_Amazon Linux_

**Wazuh version**
_3.7.2_

**Wazuh API version**
_3.7.2_

**Install type**
_manager_

**Install method**
_packages/Kubernetes_

**Log sample**

```
ERROR: Error 3004 - Error in cluster configuration: Master IP not valid. Valid ones are: 11.22.33.44
```

Bug description
----------------

Hello team, 

We reference issue [#83](https://github.com/wazuh/wazuh-docker/issues/83).

When deploying the Wazuh cluster using Kubernetes we have a problem in the master node, which does not know how to solve the pod "hostname" in the cluster configuration in `ossec.conf`. 

ConfigMap: https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh_managers/wazuh-master-conf.yaml#L325

```
        <nodes>
            <node>wazuh-manager-master-0.wazuh-cluster.wazuh.svc.cluster.local</node>
        </nodes>
```

Error:

`ERROR: Error 3004 - Error in cluster configuration: Master IP not valid. Valid ones are: 11.22.33.44`

Cause: https://github.com/wazuh/wazuh/blob/v3.7.2/framework/wazuh/cluster/cluster.py#L87-L88

We are going to implement an alternative solution in Docker. 

Regards,

Alfonso Ruiz-Bravo

**Comment by jesuslinares** [comment]
Related: https://github.com/wazuh/wazuh/pull/2204.
