### ISSUE TITLE
Release 4.8.0 - Beta 1 - E2E UX tests - MITRE

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21767]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.8.0-beta1/index.html). Be careful because some of the description steps might refer to a current version in production; always navigate using the current development documentation for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and URLs for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate at least one end-to-end alert, irrespective of test type, from the agent to the dashboard.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), and add the `Release testing` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests; here you have an example: https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/threat-intel team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Feb 07, 2024, and notify the @wazuh/threat-intel team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/threat-intel team will assign a reviewer and add it to the `review_assignee` field in the project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Feb 08, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Feb 09, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Offline installation](https://documentation-dev.wazuh.com/v4.8.0-beta1/deployment-options/offline-installation.html) | Single node | Ubuntu 20.04 x86_64 |
| Server | [Offline installation](https://documentation-dev.wazuh.com/v4.8.0-beta1/deployment-options/offline-installation.html) | Single node | Ubuntu 20.04 x86_64 |
| Dashboard | [Offline installation](https://documentation-dev.wazuh.com/v4.8.0-beta1/deployment-options/offline-installation.html) | - | Ubuntu 20.04 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.8.0-beta1/installation-guide/wazuh-agent/index.html) | - | Windows server 2019 x86_64 |

## Test description

Follow and complete the documentation steps and the examples:

https://documentation-dev.wazuh.com/v4.8.0-beta1/user-manual/ruleset/mitre.html

## Known issues

There are no known issues.

## Conclusions
I could not complete the E2E on the first try, I've found problems with the indexer. After reinstalling the indexer, I completed the E2E successfully. Mi overall result for the E2E is 🟢.

Errors detected

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴 | Indexer install | Indexer installation step failed | https://github.com/wazuh/wazuh-packages/issues/2770 (Already created, reopened)|
| 🔴 | Server install | The indexer-connector is not working because the documentation doesn't mention changing the asset.conf configuration | https://github.com/wazuh/wazuh-documentation/issues/7018 (Already created, reopened)|
| 🔴 | MITRE ATT&CK  | The Dashboard doesn't show MITRE tabs as expected. This error was solved after reinstalling the wazuh-indexer | A new issue opened: https://github.com/wazuh/wazuh-packages/issues/2817|
| 🔴 | MITRE ATT&CK  | When the indexer server is not working, the MITRE ATT&CK framework tab shows pop-up errors when the user presses the refresh button, but it doesn't alert that the indexer service is not working as expected| A new issue opened https://github.com/wazuh/wazuh-dashboard/issues/143 |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - Yes, it was a clear guideline.
- Did you face any challenges not covered by the guideline?
  - Some necessary steps were not documented, and I had to ask for help. Configuring the indexer IP address in the `ossec.conf` configuration file is crucial to completing this E2E.
  - I had to investigate and diagnose that the root cause that did not allow me to complete the E2E was that the indexer wasn't working correctly. The wazuh dashboard never alerted me that the problem was an underlying component. Only shows errors accessing the MITRE ATT&CK Framework Tab. It would be good if the Dashboard would alert you that the wazuh-indexer is not running as expected.
- Suggestions for improvement:
  - The customization section of the MITRE documentation mentioned a Windows 11 agent setup, but I was asked to install a Windows 2019 server agent. I could complete this guide with the Windows 2019 agent.

## Reviewers validation

The criteria for completing this task are based on all reviewers' validation of the conclusions and test results.

All the checkboxes below must be marked to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/threat-intel

**Comment by mhamra** [comment]
### Environment setup

<details>
<summary>Download the packages and configuration files :green_circle:</summary>
1. Download packages

```console
vagrant@server-1:~$ sudo su
root@server-1:/home/vagrant# curl -sO https://packages-dev.wazuh.com/4.8/wazuh-install.sh
root@server-1:/home/vagrant# ls
wazuh-install.sh
root@server-1:/home/vagrant# chmod 744 wazuh-install.sh
root@server-1:/home/vagrant# ./wazuh-install.sh -dw deb
07/02/2024 14:32:50 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
07/02/2024 14:32:50 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/02/2024 14:33:47 INFO: Verifying that your system meets the recommended minimum hardware requirements.
07/02/2024 14:33:48 INFO: --- Download Packages ---
07/02/2024 14:33:48 INFO: Starting Wazuh packages download.
07/02/2024 14:33:48 INFO: Downloading Wazuh deb packages for x86_64.
07/02/2024 14:35:31 INFO: The manager package was downloaded.
07/02/2024 14:35:41 INFO: The filebeat package was downloaded.
07/02/2024 14:50:24 INFO: The indexer package was downloaded.
07/02/2024 14:54:44 INFO: The dashboard package was downloaded.
07/02/2024 14:54:45 INFO: The packages are in wazuh-offline/wazuh-packages
07/02/2024 14:54:45 INFO: Downloading configuration files and assets.
07/02/2024 14:54:49 INFO: The resource https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH was downloaded.
07/02/2024 14:54:55 INFO: The resource https://packages-dev.wazuh.com/4.8/tpl/wazuh/filebeat/filebeat.yml was downloaded.
07/02/2024 14:54:59 INFO: The resource https://raw.githubusercontent.com/wazuh/wazuh/4.8.0/extensions/elasticsearch/7.x/wazuh-template.json was downloaded.
07/02/2024 14:55:08 INFO: The resource https://packages-dev.wazuh.com/pre-release/filebeat/wazuh-filebeat-0.4.tar.gz was downloaded.
07/02/2024 14:55:09 INFO: The configuration files and assets are in wazuh-offline.tar.gz

Message from syslogd@vagrant at Feb  7 15:03:03 ...
 kernel:[ 7351.229164] watchdog: BUG: soft lockup - CPU#1 stuck for 405s! [gzip:14348]
07/02/2024 15:04:01 INFO: You can follow the installation guide here https://documentation.wazuh.com/current/deployment-options/offline-installation.html
```

</details>

**Comment by mhamra** [comment]
## MITRE ATT&CK E2E

### 1. INTELLIGENCE TAB
<details>
<summary>1. Intelligence tab page</summary>

<img width="960" alt="image" src="https://github.com/wazuh/wazuh/assets/2949519/e6708372-7049-45ef-8af4-2138f972b8a9">

</details>

<details>
<summary>2. Framework tab page 🔴</summary>

- Nothing is shown in this page
   <img width="960" alt="image" src="https://github.com/wazuh/wazuh/assets/2949519/bc76f788-c8e9-4d9a-96b0-707ad5dea361">

- After Pressing the refresh button

   <img width="960" alt="image" src="https://github.com/wazuh/wazuh/assets/2949519/cf570415-986a-4620-83a2-a8eb762a6e29">

- Pressing the see the full error button
   <img width="960" alt="image" src="https://github.com/wazuh/wazuh/assets/2949519/4bfb5925-1710-4ba4-a407-016a9989563f">

**Comment by mhamra** [comment]
## UPDATE
I've investigated the environment and found that the indexer was not working. 

I've destroyed the virtual machine and followed all the steps in the indexer installation guide. The only thing I've changed is the configuration of the opensearch.yml; I've left the configuration parameter `network.host: "0.0.0.0"` instead of `network.host: "192.168.56.8"`. 

I've successfully executed the command `/usr/share/wash-indexer/bin/indexer-init.sh -I 192.168.56.8` on the first try.

```console
PS C:\Users\marce\OneDrive\Documentos\wazuh\e2emitre> vagrant destroy indexer-1
    indexer-1: Are you sure you want to destroy the 'indexer-1' VM? [y/N] y
==> indexer-1: Destroying VM and associated drives...
PS C:\Users\marce\OneDrive\Documentos\wazuh\e2emitre> vagrant up indexer-1
Bringing machine 'indexer-1' up with 'virtualbox' provider...
==> indexer-1: Importing base box 'bento/ubuntu-20.04'...
==> indexer-1: Matching MAC address for NAT networking...
==> indexer-1: Checking if box 'bento/ubuntu-20.04' version '202401.31.0' is up to date...
==> indexer-1: Setting the name of the VM: e2emitre_indexer-1_1707410233826_7068
==> indexer-1: Fixed port collision for 22 => 2222. Now on port 2200.
==> indexer-1: Clearing any previously set network interfaces...
==> indexer-1: Preparing network interfaces based on configuration...
    indexer-1: Adapter 1: nat
    indexer-1: Adapter 2: hostonly
==> indexer-1: Forwarding ports...
    indexer-1: 22 (guest) => 2200 (host) (adapter 1)
==> indexer-1: Running 'pre-boot' VM customizations...
==> indexer-1: Booting VM...
==> indexer-1: Waiting for machine to boot. This may take a few minutes...
    indexer-1: SSH address: 127.0.0.1:2200
    indexer-1: SSH username: vagrant
    indexer-1: SSH auth method: private key
    indexer-1: Warning: Connection reset. Retrying...
    indexer-1: Warning: Connection aborted. Retrying...
    indexer-1: Warning: Connection reset. Retrying...
    indexer-1:
    indexer-1: Vagrant insecure key detected. Vagrant will automatically replace
    indexer-1: this with a newly generated keypair for better security.
    indexer-1:
    indexer-1: Inserting generated public key within guest...
    indexer-1: Removing insecure key from the guest if it's present...
    indexer-1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> indexer-1: Machine booted and ready!
==> indexer-1: Checking for guest additions in VM...
==> indexer-1: Setting hostname...
==> indexer-1: Configuring and enabling network interfaces...
PS C:\Users\marce\OneDrive\Documentos\wazuh\e2emitre> vagrant ssh indexer-1
Welcome to Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-170-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

  System information as of Thu 08 Feb 2024 05:48:58 PM UTC

  System load:  0.25               Processes:             152
  Usage of /:   12.1% of 30.34GB   Users logged in:       0
  Memory usage: 3%                 IPv4 address for eth0: 10.0.2.15
  Swap usage:   0%                 IPv4 address for eth1: 192.168.56.8


This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento
vagrant@indexer-1:~$ sudo su
root@indexer-1:/home/vagrant# ls wazuh-certificates/
admin-key.pem  dashboard-key.pem  node-1-key.pem  root-ca.key  wazuh-1-key.pem
admin.pem      dashboard.pem      node-1.pem      root-ca.pem  wazuh-1.pem
root@indexer-1:/home/vagrant# vagrant@indexer-1:~$ tar xf wazuh-offline.tar.gz
bash: vagrant@indexer-1:~$: command not found
root@indexer-1:/home/vagrant# tar xf wazuh-offline.tar.gz
root@indexer-1:/home/vagrant# dpkg -i ./wazuh-offline/wazuh-packages/wazuh-indexer*.deb
Selecting previously unselected package wazuh-indexer.
(Reading database ... 41410 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_4.8.0-1_amd64.deb ...
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
Unpacking wazuh-indexer (4.8.0-1) ...
Setting up wazuh-indexer (4.8.0-1) ...
Created opensearch keystore in /etc/wazuh-indexer/opensearch.keystore
Processing triggers for systemd (245.4-4ubuntu3.23) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
root@indexer-1:/home/vagrant# NODE_NAME=node-1
root@indexer-1:/home/vagrant# mkdir /etc/wazuh-indexer/certs
root@indexer-1:/home/vagrant# mv -n wazuh-certificates/$NODE_NAME.pem /etc/wazuh-indexer/certs/indexer.pem
root@indexer-1:/home/vagrant# mv -n wazuh-certificates/$NODE_NAME-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
root@indexer-1:/home/vagrant# mv wazuh-certificates/admin-key.pem /etc/wazuh-indexer/certs/
root@indexer-1:/home/vagrant# mv wazuh-certificates/admin.pem /etc/wazuh-indexer/certs/
root@indexer-1:/home/vagrant# cp wazuh-certificates/root-ca.pem /etc/wazuh-indexer/certs/
root@indexer-1:/home/vagrant# chmod 500 /etc/wazuh-indexer/certs
root@indexer-1:/home/vagrant# chmod 400 /etc/wazuh-indexer/certs/*
root@indexer-1:/home/vagrant# chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
root@indexer-1:/home/vagrant# nano /etc/wazuh-indexer/opensearch.yml
root@indexer-1:/home/vagrant# nano /etc/wazuh-indexer/opensearch.yml
root@indexer-1:/home/vagrant# nano /etc/wazuh-indexer/opensearch.yml
root@indexer-1:/home/vagrant# systemctl daemon-reload
root@indexer-1:/home/vagrant# systemctl enable wazuh-indexer
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /lib/systemd/system/wazuh-indexer.service.
root@indexer-1:/home/vagrant# systemctl enable wazuh-indexer
root@indexer-1:/home/vagrant# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: enabled)
     Active: inactive (dead)
       Docs: https://documentation.wazuh.com
root@indexer-1:/home/vagrant# systemctl start wazuh-indexer

root@indexer-1:/home/vagrant#
root@indexer-1:/home/vagrant# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-02-08 18:09:18 UTC; 18s ago
       Docs: https://documentation.wazuh.com
   Main PID: 14206 (java)
      Tasks: 77 (limit: 9426)
     Memory: 1.2G
     CGroup: /system.slice/wazuh-indexer.service
             └─14206 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networ>

Feb 08 18:07:33 indexer-1 systemd[1]: Starting Wazuh-indexer...
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: A terminally deprecated method in java.lang.System has been called
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap>
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bo>
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager will be removed in a future release
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: A terminally deprecated method in java.lang.System has been called
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap>
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bo>
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager will be removed in a future release
Feb 08 18:09:18 indexer-1 systemd[1]: Started Wazuh-indexer.
root@indexer-1:/home/vagrant# /usr/share/wazuh-indexer/bin/indexer-init.sh -i 192.168.56.8
Executing Wazuh indexer security init script...
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.10.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/wazuh-indexer/opensearch-security/
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/wazuh-indexer/opensearch-security/roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/wazuh-indexer/opensearch-security/internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/wazuh-indexer/opensearch-security/action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/wazuh-indexer/opensearch-security/tenants.yml
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/wazuh-indexer/opensearch-security/nodes_dn.yml
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/wazuh-indexer/opensearch-security/whitelist.yml
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/wazuh-indexer/opensearch-security/audit.yml
   SUCC: Configuration for 'audit' created or updated
Will update '/allowlist' with /etc/wazuh-indexer/opensearch-security/allowlist.yml
   SUCC: Configuration for 'allowlist' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success
Executing Wazuh indexer ISM init script...
Will create 'wazuh' index template
 SUCC: 'wazuh' template created or updated
Will create 'ism_history_indices' index template
 SUCC: 'ism_history_indices' template created or updated
Will disable replicas for 'plugins.index_state_management.history' indices
 SUCC: cluster's settings saved
Will create index templates to configure the alias
 SUCC: 'wazuh-alerts' template created or updated
 SUCC: 'wazuh-archives' template created or updated
Will create the 'rollover_policy' policy
  SUCC: 'rollover_policy' policy created
Will create initial indices for the aliases
  SUCC: 'wazuh-alerts' write index created
  SUCC: 'wazuh-archives' write index created
SUCC: Indexer ISM initialization finished successfully.
root@indexer-1:/home/vagrant# curl -XGET https://192.168.56.8:9200 -u admin:admin -k
{
  "name" : "node-1",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "2EpTtHjBRCaO7vk9m2JKHg",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "eee49cb340edc6c4d489bcd9324dda571fc8dc03",
    "build_date" : "2023-09-20T23:54:29.889267151Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
root@indexer-1:/home/vagrant# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2024-02-08 18:09:18 UTC; 3min 4s ago
       Docs: https://documentation.wazuh.com
   Main PID: 14206 (java)
      Tasks: 74 (limit: 9426)
     Memory: 1.3G
     CGroup: /system.slice/wazuh-indexer.service
             └─14206 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networ>

Feb 08 18:07:33 indexer-1 systemd[1]: Starting Wazuh-indexer...
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: A terminally deprecated method in java.lang.System has been called
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap>
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bo>
Feb 08 18:07:52 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager will be removed in a future release
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: A terminally deprecated method in java.lang.System has been called
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap>
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bo>
Feb 08 18:08:00 indexer-1 systemd-entrypoint[14206]: WARNING: System::setSecurityManager will be removed in a future release
Feb 08 18:09:18 indexer-1 systemd[1]: Started Wazuh-indexer.
```

**Comment by ooniagbi** [comment]
LGTM!
