### ISSUE TITLE
Release 4.8.0 - Beta 1 - E2E UX tests - SAML SSO

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21768]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.8.0-beta1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/frontend team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Feb 07, 2024 and notify the @wazuh/frontend team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/frontend team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Feb 08, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Feb 09, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.8.0-beta1/quickstart.html) | - | CentOS 8 x86_64 |
| Server | Same as indexer, all-in-one | - | - |
| Dashboard | Same as indexer, all-in-one | - | - |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.8.0-beta1/installation-guide/wazuh-agent/index.html) | - | Fedora 38 x86_64 |

## Test description

Following documentation from Single sign-on https://documentation-dev.wazuh.com/v4.8.0-beta1/user-manual/user-administration/single-sign-on/index.html, try the best effort to complete the steps and test the dashboard login using Okta and Microsoft Entra ID

## Known issues

- https://github.com/opensearch-project/security-dashboards-plugin/issues/828

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢    | Quickstart | Outdated OS caused issue on installation  | https://github.com/wazuh/wazuh-documentation/issues/7019 |
| 🟢   | Agent installation |  |  |
| 🟢   | Okta |  |  |
| 🟢     | ME-ID |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - All screenshots on the documentation regarding the configuration are done using private IPs and no notes or warnings mention this, it can be misleading when configuring both Okta, ME-ID, and Wazuh sides when operating on external servers that require setting up using public IPs.
  
- Did you face any challenges not covered by the guideline?
  - No, documentation was straightforward.
  
- Suggestions for improvement:
  -  I think the documentation can be improved by adding a couple of screenshots on the last step of every integration showing the expected results.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/frontend

**Comment by EduLeon12** [comment]
## Environment details

<details> <summary> Server installation </summary> 

- OS details.

```command
[root@localhost var]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

- Wazuh installation assistant

```command

[root@localhost /]# curl -sO https://packages-dev.wazuh.com/4.8/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
07/02/2024 11:59:33 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
07/02/2024 11:59:33 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/02/2024 11:59:36 INFO: --- Dependencies ---
07/02/2024 11:59:36 INFO: Installing lsof.
07/02/2024 11:59:37 INFO: Verifying that your system meets the recommended minimum hardware requirements.
07/02/2024 11:59:37 INFO: Wazuh web interface port will be 443.
07/02/2024 11:59:37 WARNING: Cannot find lsof. Port checking will be skipped.
07/02/2024 11:59:38 INFO: Wazuh development repository added.
07/02/2024 11:59:38 INFO: --- Configuration files ---
07/02/2024 11:59:38 INFO: Generating configuration files.
07/02/2024 11:59:38 INFO: Generating the root certificate.
07/02/2024 11:59:39 INFO: Generating Admin certificates.
07/02/2024 11:59:39 INFO: Generating Wazuh indexer certificates.
07/02/2024 11:59:39 INFO: Generating Filebeat certificates.
07/02/2024 11:59:39 INFO: Generating Wazuh dashboard certificates.
07/02/2024 11:59:39 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
07/02/2024 11:59:39 INFO: --- Wazuh indexer ---
07/02/2024 11:59:39 INFO: Starting Wazuh indexer installation.
07/02/2024 11:59:40 ERROR: Wazuh indexer installation failed.
07/02/2024 11:59:40 INFO: --- Removing existing Wazuh installation ---
07/02/2024 11:59:40 INFO: --- Dependencies ---
07/02/2024 11:59:40 INFO: Removing lsof.

```

After investigating it was found that the error was due to packages not being updated due to centOs-8 mirror list not being found, an [issue](https://github.com/wazuh/wazuh-documentation/issues/7019) has been opened with more information.

Installation was retried on another server.

- New server OS details

```command
[root@ip-172-31-34-69 /]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

```

- Wazuh installation assistant.

```command
[root@ip-172-31-34-69 /]# curl -sO https://packages-dev.wazuh.com/4.8/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
07/02/2024 21:48:09 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
07/02/2024 21:48:09 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/02/2024 21:48:21 INFO: --- Dependencies ---
07/02/2024 21:48:21 INFO: Installing lsof.
07/02/2024 21:48:25 INFO: Verifying that your system meets the recommended minimum hardware requirements.
07/02/2024 21:48:25 INFO: Wazuh web interface port will be 443.
07/02/2024 21:48:28 INFO: Wazuh development repository added.
07/02/2024 21:48:28 INFO: --- Configuration files ---
07/02/2024 21:48:28 INFO: Generating configuration files.
07/02/2024 21:48:28 INFO: Generating the root certificate.
07/02/2024 21:48:28 INFO: Generating Admin certificates.
07/02/2024 21:48:29 INFO: Generating Wazuh indexer certificates.
07/02/2024 21:48:29 INFO: Generating Filebeat certificates.
07/02/2024 21:48:29 INFO: Generating Wazuh dashboard certificates.
07/02/2024 21:48:29 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
07/02/2024 21:48:30 INFO: --- Wazuh indexer ---
07/02/2024 21:48:30 INFO: Starting Wazuh indexer installation.
07/02/2024 21:50:49 INFO: Wazuh indexer installation finished.
07/02/2024 21:50:49 INFO: Wazuh indexer post-install configuration finished.
07/02/2024 21:50:49 INFO: Starting service wazuh-indexer.
07/02/2024 21:51:13 INFO: wazuh-indexer service started.
07/02/2024 21:51:13 INFO: Initializing Wazuh indexer cluster security settings.
07/02/2024 21:51:25 INFO: Wazuh indexer cluster security configuration initialized.
07/02/2024 21:51:28 INFO: The Wazuh indexer cluster ISM initialized.
07/02/2024 21:51:28 INFO: Wazuh indexer cluster initialized.
07/02/2024 21:51:28 INFO: --- Wazuh server ---
07/02/2024 21:51:28 INFO: Starting the Wazuh manager installation.
07/02/2024 21:55:04 INFO: Wazuh manager installation finished.
07/02/2024 21:55:04 INFO: Wazuh manager vulnerability detection configuration finished.
07/02/2024 21:55:04 INFO: Starting service wazuh-manager.
07/02/2024 21:55:23 INFO: wazuh-manager service started.
07/02/2024 21:55:23 INFO: Starting Filebeat installation.
07/02/2024 21:55:38 INFO: Filebeat installation finished.
07/02/2024 21:55:39 INFO: Filebeat post-install configuration finished.
07/02/2024 21:55:39 INFO: Starting service filebeat.
07/02/2024 21:55:39 INFO: filebeat service started.
07/02/2024 21:55:39 INFO: --- Wazuh dashboard ---
07/02/2024 21:55:39 INFO: Starting Wazuh dashboard installation.
07/02/2024 21:57:41 INFO: Wazuh dashboard installation finished.
07/02/2024 21:57:41 INFO: Wazuh dashboard post-install configuration finished.
07/02/2024 21:57:41 INFO: Starting service wazuh-dashboard.
07/02/2024 21:57:42 INFO: wazuh-dashboard service started.
07/02/2024 21:57:46 INFO: Updating the internal users.
07/02/2024 21:57:54 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
07/02/2024 21:58:51 INFO: Initializing Wazuh dashboard web application.
07/02/2024 21:58:53 INFO: Wazuh dashboard web application initialized.
07/02/2024 21:58:53 INFO: --- Summary ---
07/02/2024 21:58:53 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: a####
    Password: ################
07/02/2024 21:58:53 INFO: --- Dependencies ---
07/02/2024 21:58:53 INFO: Removing lsof.
07/02/2024 21:58:55 INFO: Installation finished.

```


### Conclusion 

Installation was successful on the second server without needing to update mirror-list urls.

</details>

<details> <summary> Agent </summary>
- OS details

```command
root@ip-172-31-31-174:/# cat etc/os-release
NAME="Fedora Linux"
VERSION="39.20240112.3.0 (CoreOS)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora CoreOS 39.20240112.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='39.20240112.3.0'
```

 </details>

**Comment by EduLeon12** [comment]
## Okta

<details> <summary> Okta configuration </summary>

- New group creation 🟢 

![image](https://github.com/wazuh/wazuh/assets/60372646/775d3c0c-1f78-4a79-8c07-f45be67d10e6)

- Add user to group 🟢 

![image](https://github.com/wazuh/wazuh/assets/60372646/1a5e3c85-4f27-47a8-aa52-d6203767c62e)

- App creation and configuration 🟢 

![image](https://github.com/wazuh/wazuh/assets/60372646/e4cf0053-aa0f-45e8-91d3-f289fd2fef0e)

![image](https://github.com/wazuh/wazuh/assets/60372646/7142fcdc-157f-45ee-a6af-955ab8a0721e)

![image](https://github.com/wazuh/wazuh/assets/60372646/21f71fec-693b-493f-a9c6-cfc7914afea8)

- App creation summary 🟢 

![image](https://github.com/wazuh/wazuh/assets/60372646/365abe20-a014-460a-b91f-452519d0d565)

- Add app to group 🟢 

![image](https://github.com/wazuh/wazuh/assets/60372646/868ab39c-d18b-447c-b818-80ffc95f45d4)

 </details>
<details> <summary> Wazuh indexer configuration  </summary> </details>
<details> <summary> Wazuh dashboard configuration </summary> </details>

**Comment by EduLeon12** [comment]
## Microsoft Entra ID 

<details> <summary> </summary> </summary>

<details> <summary> </summary> </summary>

<details> <summary> </summary> </summary>

<details> <summary> </summary> </summary>

<details> <summary> </summary> </summary>

<details> <summary> </summary> </summary>

**Comment by Tostti** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM
