### ISSUE TITLE
Release 4.8.0 - Beta 1 - Vulnerability Detector E2E Tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21789]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |             https://github.com/wazuh/wazuh/issues/21774                               |
| **Main Vulnerability Detection tests issue**     |             https://github.com/wazuh/wazuh/issues/21788                               |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                    Beta 1                        |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta1                                |
| **Previous E2E Vulnerability tests issue**      |        None                                    |

### Description

The following issue aims to run all [Vulnerability Detector E2E](https://github.com/wazuh/wazuh-qa/issues/4369) tests for the current release candidate, report the results, and open new issues for any encountered errors.

### Instruction

Run the vulnerability detector tests using the [Test_e2e_system](https://ci.wazuh.info/job/Test_e2e_system/) pipeline

### Conclusion :red_circle: 

- https://github.com/wazuh/wazuh-jenkins/issues/6234
- https://github.com/wazuh/wazuh-qa/issues/4931
- https://github.com/wazuh/wazuh-qa/issues/4930
- https://github.com/wazuh/wazuh-qa/issues/4935
- https://github.com/wazuh/wazuh-qa/issues/4936
- https://github.com/wazuh/wazuh-qa/issues/4937
- https://github.com/wazuh/intelligence-platform/issues/1334
- https://github.com/wazuh/wazuh/issues/10633
- https://github.com/wazuh/wazuh/issues/21811
- https://github.com/wazuh/wazuh-qa/issues/4938
- https://github.com/wazuh/wazuh-qa/issues/4939
- https://github.com/wazuh/wazuh-qa/issues/4943

**Comment by Rebits** [comment]
Several issues were detected during the Vulnerability Detector E2E tests:

### Provisioning 

**Missing dependency in Jenkins node**:
- https://github.com/wazuh/wazuh-jenkins/issues/6234

**Missing filebeat**
- Issue: To be open
- Build: https://ci.wazuh.info/job/Test_e2e_system/232/

**macOS provisioning fail due to missing handler**
- Issue: To be open
- Build: https://ci.wazuh.info/job/Wazuh_QA_environment/916/consoleFull


### E2E Tests

**Changed configuration in indexer module in favor of keystore**

- Issue: To be opened
- Development Issue: https://github.com/wazuh/wazuh/issues/21576
- Tests were not updated accordingly

**Bug in file modification System method**
Work in progress


**Monitoring method does not handle correctly never appearing logs**
Work in progress

**Comment by juliamagan** [comment]
LGTM

**Comment by davidjiglesias** [comment]
LGTM!
