### ISSUE TITLE
Release 4.8.0 - Beta 1 - Vulnerability Detector tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21788]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |             https://github.com/wazuh/wazuh/issues/21774                               |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                    Beta 1                        |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta1                                |
| **Previous Vulnerability tests issue**      |        None                                    |

## Description

The primary goal of this issue is to conduct thorough vulnerability tests on the current release candidate. The process involves executing all vulnerability tests, analyzing the outcomes, and promptly reporting any identified issues. Additionally, new issues will be opened for encountered errors, contributing to the continuous improvement of the Vulnerability Detection module and the utilized vulnerability feed.

*** 

| Status | Test              | Issue              |
| :--:   | :--               | :--:               |
| :red_circle:     |  E2E Vulnerability Detection tests| https://github.com/wazuh/wazuh/issues/21789  |
| :red_circle:     | E2E Not covered Cases tests | https://github.com/wazuh/wazuh/issues/21790      |
| :red_circle:     | Feed Comparison | https://github.com/wazuh/wazuh-qa/issues/4898      |

---

:white_circle: Skipped: The task has been deemed unnecessary for this stage.
:black_circle: Not finished: The tasks haven't been finished yet.
:green_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.
:yellow_circle: Completed with accepted known issues (new): Some issues were raised here, they were deemed non-stopper.

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @davidjiglesias

---

**Comment by Rebits** [comment]
Adjusting the estimated time of arrival to accommodate the final review process.

**Comment by davidjiglesias** [comment]
LGTM!
