### ISSUE TITLE
Release 4.8.0 - Beta 1 - Vulnerability Detector E2E Extra cases

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21790]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |             https://github.com/wazuh/wazuh/issues/21774                               |
| **Main Vulnerability Detection tests issue**     |             https://github.com/wazuh/wazuh/issues/21788                               |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                    Beta 1                        |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta1                                |
| **Previous E2E Vulnerability tests issue**      |        None                                    |

### Description

The following issue aims to run some extra cases not covered in the [Vulnerability Detector E2E](https://github.com/wazuh/wazuh-qa/issues/4369) tests for the current release candidate, report the results, and open new issues for any encountered errors.

#### **Installation of a vulnerable package when agent is offline**

- Deploy a Wazuh cluster and two agents.
- Enable vulnerability detector in the managers.
- Register the agents to each manager host.
- Wait until feeds are updated.
- Wait until first scan is performed.
- Stop agents.
- Install a vulnerable package in both agents.
- Start agents.
- Wait until the next scan is performed.
- Check that the vulnerable package is detected in both agents

#### **Enable vulnerability detector when some agents are already registered**

- Deploy a Wazuh cluster and two agents.
- Disable vulnerability detector in the managers.
- Register the agents to each manager host.
- Enable vulnerability detector in the managers.
- Check that the agents are scanned and the vulnerable packages are detected.

#### **Change agents' manager and install a vulnerable package**

- Deploy a Wazuh cluster and two agents.
- Enable vulnerability detector in the managers.
- Register the agents to each manager host.
- Wait until feeds are updated.
- Wait until first scan is performed.
- Check that the agents are scanned and the vulnerable packages are detected.
- Change the manager of the agents.
- Install a vulnerable package in both agents.
- Wait until the next scan is performed.
- Check that the vulnerable package is detected in both agents

> [!NOTE]
> Test design created, cloned from the issue #4914 on https://github.com/wazuh/wazuh-qa

### Conclusion :red_circle: 

- https://github.com/wazuh/wazuh/issues/21185

> [!NOTE]
> We should consider increase increase manual test coverage in future stages in order to check configuration validation, offline feed and other features

**Comment by Rebits** [comment]
### Change agents' manager and install a vulnerable package :large_blue_circle:

**Comment by Rebits** [comment]
Enable vulnerability detector when some agents are already registered :large_blue_circle:

**Comment by davidjiglesias** [comment]
LGTM!
