### ISSUE TITLE
Make cluster configuration optional

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#218]
- Add installer option to switch on cluster options.
- Add preload variable for unattended installation.
- Do not show empty cluster object in JSON alerts.

**Comment by jesuslinares** [comment]
By default, a manager is a cluster (only one node). So, the cluster configuration must be included by default. Also, the cluster information in the JSON alert (Wazuh App requires it).

Preload variables are necessary.

**Comment by jesuslinares** [comment]
1. If there is no cluster configuration, the _cluster.name_ field of the JSON alert must be _wazuh_.
2. Add a new option to skip the cluster.name in the alert. This will prevent the user to use the Wazuh app properly but it will save space.

**Comment by albertomn86** [comment]
Done!

https://github.com/wazuh/wazuh/pull/224
