### ISSUE TITLE
API not starting

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#21803]
|Wazuh version|Component|
|---|---|
| 4.8.0-beta1 | RESTful API |

## Description

During [Release 4.8.0 - Beta 1 - API integration tests #21795](https://github.com/wazuh/wazuh/issues/21795), the API integration tests failed because the log `Listening on` is not present in the `api.log` file. The testing environment healthchecks  timed out waiting for this specific line.

```console
E   Failed: Timeout on API callback. Could not find 'Listening on'
```

After executing the API in foreground mode, we can see that the error is originated because the module `jose` is not present.

```console
root@wazuh-worker1:/# /var/ossec/bin/wazuh-apid -f
Starting API in foreground
2024/02/07 15:17:49 INFO: Checking RBAC database integrity...
2024/02/07 15:17:49 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/02/07 15:17:49 INFO: RBAC database integrity check finished successfully
Failed to add operation for GET /
Internal error when trying to start the Wazuh API. No module named 'jose'
```

[Artifacts](https://github.com/wazuh/wazuh/files/14195160/Test_integration_endpoints_B4307_test_agent_GET_endpoints_logs.zip)

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

After the CPython dependencies versions were updated in AWS, the error is no longer present and the API starts successfully.

```console
root@wazuh-master:/# /var/ossec/bin/wazuh-apid -f
wazuh-apid: Orphan child process 188 was terminated.
wazuh-apid: Orphan child process 194 was terminated.
wazuh-apid: Orphan child process 73 was terminated.
wazuh-apid: Orphan child process 191 was terminated.
Starting API in foreground
2024/02/07 18:50:46 INFO: Checking RBAC database integrity...
2024/02/07 18:50:46 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/02/07 18:50:46 INFO: RBAC database integrity check finished successfully
2024/02/07 18:50:49 INFO: Listening on 0.0.0.0:55000..
2024/02/07 18:50:49 INFO: Getting installation UID...
2024/02/07 18:50:49 INFO: Getting updates information...
======== Running on https://0.0.0.0:55000/ ========
(Press CTRL+C to quit)
```

The tests should now execute without this issue.

**Comment by GGP1** [comment]
## Update

The API integration tests have executed successfully after the dependencies versions changes in AWS. We can consider this issue as resolved.

Results: https://github.com/wazuh/wazuh/issues/21795#issuecomment-1933766562
Artifacts: [artifacts.zip](https://github.com/wazuh/wazuh/files/14207579/artifacts.zip)
Build: https://ci.wazuh.info/job/Test_integration_endpoints/4318

**Comment by fdalmaup** [comment]
# Review

As correctly explained, the error was due to the dependencies update carried out in #21662, which removed the `python-jose` and `ecdsa` packages, after creating the `v4.8.0-beta1` tag and thus breaking the API installation.

LGTM!
