### ISSUE TITLE
Defer Decompression of Vulnerability Detector Content

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21800]
### Description

This issue aims to defer the decompression of vulnerability detector content during installation to the first execution of the module. Currently, the content is decompressed during installation, leading to increased image sizes, especially in Docker containers. By deferring the decompression, we can reduce the initial image size and improve resource efficiency.

### Proposed Changes

The following changes will be made:

1. **Modify Installation Process:** Update the installation process to skip decompression of vulnerability detector content.
Remove from:
- https://github.com/wazuh/wazuh-packages/blob/0bdc5d82a27178a981de4104dcfaf25facbed62f/debs/SPECS/wazuh-manager/debian/postinst#L75
- https://github.com/wazuh/wazuh-packages/blob/0bdc5d82a27178a981de4104dcfaf25facbed62f/rpms/SPECS/wazuh-manager.spec#L309
- https://github.com/wazuh/wazuh-packages/blob/0bdc5d82a27178a981de4104dcfaf25facbed62f/rpms/SPECS/wazuh-manager.spec#L25C8-L25C23
- https://github.com/wazuh/wazuh-packages/blob/0bdc5d82a27178a981de4104dcfaf25facbed62f/debs/SPECS/wazuh-manager/debian/control#L11

2. **Implement Lazy Decompression:** Modify the vulnerability detector module to decompress the content on its first execution instead of during installation.

Use -> https://github.com/wazuh/wazuh/blob/master/src/shared_modules/utils/xzHelper.hpp

### Impact

- **Reduced Image Size:** Deferring decompression will lead to smaller initial image sizes, which is particularly beneficial for Docker containers and environments with limited resources.
- **Improved Resource Efficiency:** By postponing decompression until the module's first execution, we can optimize resource usage during installation.

### Definition of Done

- The installation process is updated to skip the decompression of vulnerability detector content.
- Remove xz as dependency for the rpm and deb installers.
- The vulnerability detector module successfully decompresses the content upon its first execution.
- Thorough testing is conducted to validate the functionality and efficiency of the deferred decompression approach.

### Sequence diagram
```mermaid
sequenceDiagram
    actor User
    participant Installer
    participant Modulesd
    participant VD
    participant XZ-Decompressor
    User->>Installer: Install package.
    Installer->>Installer: Decompress vd_x.x.x_vd_z.z.z.tar.xz to /var/ossec/tmp
    User->>Modulesd: Start wazuh services
    Modulesd->>VD: Create VD thread
    VD-->>Modulesd: return
    Modulesd-->>User: Notify wazuh started
    alt vd_x.x.x_vd_z.z.z.tar.xz exist in /var/ossec/tmp
        VD->>XZ-Decompressor: decompress file in queue folder
        XZ-Decompressor-->>VD: decompress success
        VD->>VD: check permissions and remove vd_x.x.x_vd_z.z.z.tar.xz
    end
    VD->>VD: Continue submodule start
```
### TLDR
It is not necessary to create any thread, you should only do this as soon as the vulnerabilityScannerFacade entry point is called

**Comment by MiguelazoDS** [comment]
# Comments 

It was possible to decompress using the xzHelper already implemented to get a single file of .tar format that contains the desired database. We now need to find a way to implement that. 

The time is about 20 seconds (Ubuntu Jammy VBox 12GB 8 cores)

![2024-02-07_16-44](https://github.com/wazuh/wazuh/assets/13010397/13be7d08-9d6d-4f83-8e94-c25bd4a940e8)
![2024-02-07_16-47](https://github.com/wazuh/wazuh/assets/13010397/2c6812a9-d2ef-4556-b683-b88e13d00724)

**Comment by Dwordcito** [comment]
## Definition changes based on the issue https://github.com/wazuh/wazuh-docker/issues/1205

```mermaid
sequenceDiagram
    actor User
    participant Installer
    participant Modulesd
    participant VD
    participant XZ-Decompressor
    participant vd_db
    User->>Installer: Install package.
    Installer->>Installer: Decompress vd_x.x.x_vd_z.z.z.tar.xz to /var/ossec/tmp
    User->>Modulesd: Start wazuh services
    Modulesd->>VD: Create VD thread
    VD-->>Modulesd: return
    Modulesd-->>User: Notify wazuh started
    
    VD->>vd_db: Open or create KV rocksdb
    alt WAZUH_VERSION not exist in vd_db
        VD->>XZ-Decompressor: decompress file in queue folder
        XZ-Decompressor-->>VD: decompress success
        VD->>VD: check permissions
        VD->>vd_db: Add kv, key: WAZUH_VERSION, value: TRUE
        VD->>VD remove vd_x.x.x_vd_z.z.z.tar.xz
    end
    VD->>VD: Continue submodule start
```

**Comment by sebasfalcone** [comment]
Moved ETA to give time for the review, that will take place on monday

**Comment by MiguelazoDS** [comment]
# Comments 

Related to the diagram above, we are going to use the same database implemented here https://github.com/wazuh/wazuh/pull/21446/files with a key `installed_content` that reports the current `wazuh_version`.  We need to request that value and react accordingly. 

We need to pay attention to information we do not have to replace during the download of the content database. 

A sort of filter was implemented to extract only needed information.

**Comment by sebasfalcone** [comment]
Pending final review - Moved ETA
