### ISSUE TITLE
Detecting Nmap port scan attack with Suricata not working

### ISSUE THREAD

**Issue by ImGyba** [wazuh/wazuh#21804]
Hello,

I am using Wazuh 4.7.2 and trying to detect a port scan attack for a Windows endpoint. 

My setup is:
- Wazuh Manager is a .ova VM
- Wazuh agent (target) is on my Windows laptop where the .ova VM is also running
- Suricata installed on the same laptop as the Wazuh agent
- Kali Machine (attacker) is on my Windows laptop, different VM 

I followed the documentation from this link: https://wazuh.com/blog/responding-to-network-attacks-with-suricata-and-wazuh-xdr/

Nevertheless, even if I see other Suricata-generated alerts, I cannot see the Nmap scan. Also, as a result, the IP of my Kali machine is not getting blocked as it should happen according to the documentation. 

Any ideas on what I should check/modify? 

Thank you.

**Comment by jnasselle** [comment]
Hi @ImGyba ,

The idea is changing from CentOS to Windows as victim endpoint, am i right?

**Comment by jnasselle** [comment]
Closed due to inactivity, If you would like to return to this issue please reopen it.

Thanks for being part of the community.
