### ISSUE TITLE
Errors indexing alerts

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#21814]
# Description
During the test https://github.com/wazuh/wazuh/issues/21761, found an error that caused the logs to go to the index `wazuh-alerts` instead of  `wazuh-alerts-4.x-<date>` in one of the tests, and to not to be indexed at all in a second test. 

The output of `filebeat test output` was ok, and alerts were generated in the manager in both cases

```console
[root@puppet-agent1 vagrant]# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
[root@puppet-agent1 vagrant]# tail -1 /var/ossec/logs/alerts/alerts.json 
{"timestamp":"2024-02-07T21:16:21.918+0000","rule":{"level":3,"description":"Auditd: SELinux permission check.","id":"80730","firedtimes":18,"mail":false,"groups":["audit","audit_selinux"],"gdpr":["IV_30.1.g","IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6"],"pci_dss":["10.6.1"],"tsc":["CC7.2","CC7.3"]},"agent":{"id":"001","name":"puppet-agent2","ip":"192.168.56.6"},"manager":{"name":"puppet-agent1"},"id":"1707340581.9490069","full_log":"type=AVC msg=audit(1707340580.189:1565): avc:  denied  { ioctl } for  pid=1880 comm=\"VBoxService\" path=\"/dev/vboxguest\" dev=\"devtmpfs\" ino=442 ioctlcmd=0x5607 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:xserver_misc_device_t:s0 tclass=chr_file permissive=1","decoder":{"name":"auditd"},"data":{"audit":{"type":"AVC","id":"1565","pid":"1880","command":"VBoxService"}},"location":"/var/log/audit/audit.log"}

```

**Comment by vikman90** [comment]
I wonder if this might be related to https://github.com/wazuh/wazuh/pull/19819.

**Comment by Tostti** [comment]
# Research
Working with @AlexRuiz7 we've been able to reproduce the issue. We recreated the puppet agent several times (using the same VM specifications) and in one case it didn't fail. 

We found out that apparently the securityadmin is not executed when it fails (not showing any type of logs). 

Logs when it works: 
```
...
Notice: /Stage[indexerdeploy]/Wazuh::Indexer/Service[wazuh-indexer]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[indexerdeploy]/Wazuh::Indexer/Service[wazuh-indexer]: Unscheduling refresh on Service[wazuh-indexer]
Notice: /Stage[securityadmin]/Wazuh::Securityadmin/Exec[Initialize the Opensearch security index and ISM Polciy in Wazuh indexer]/returns: executed successfully
Notice: /Stage[manager]/Wazuh::Manager/Package[wazuh-manager]/ensure: created
...
``` 

Logs when it doesn't work: 
```
...
Notice: /Stage[indexerdeploy]/Wazuh::Indexer/Service[wazuh-indexer]/ensure: ensure changed 'stopped' to 'runnin
g'
Info: /Stage[indexerdeploy]/Wazuh::Indexer/Service[wazuh-indexer]: Unscheduling refresh on Service[wazuh-in
dexer]
Notice: /Stage[manager]/Wazuh::Manager/Package[wazuh-manager]/ensure: created 
...
``` 

This script also sets up the template, so https://github.com/wazuh/wazuh/issues/21815 may be related to the same problem. 

Additionally, it apparently doesn't configure Filebeat on the first attempt. 

The manifest used for all the tests was
```
$discovery_type = 'single-node'
stage { 'certificates': }
stage { 'repo': }
stage { 'indexerdeploy': }
stage { 'securityadmin': }
stage { 'dashboard': }
stage { 'manager': }
Stage[certificates] -> Stage[repo] -> Stage[indexerdeploy] -> Stage[securityadmin] -> Stage[manager] -> Stage[dashboard]
Exec {
timeout => 0,
}
node "puppet-master" {
class { 'wazuh::certificates':
  indexer_certs => [['node-1','127.0.0.1']],
  manager_certs => [['master','127.0.0.1']],
  dashboard_certs => ['127.0.0.1'],
  stage => certificates,
}
}
node "puppet-agent" {
class { 'wazuh::repo':
stage => repo,
}
class { 'wazuh::indexer':
  stage => indexerdeploy,
}
class { 'wazuh::securityadmin':
stage => securityadmin
}
class { 'wazuh::manager':
  stage => manager,
}
class { 'wazuh::filebeat_oss':
  stage => manager,
}
class { 'wazuh::dashboard':
  stage => dashboard,
}
}

```

**Comment by davidcr01** [comment]
# Update Report

I have investigated this issue and I could not reproduce the problem. Maybe the deployment with Puppet was done in several intervals, and Filebeat created the indices before the Wazuh indexer.

In a clean machine with the correct configuration, the deployment was completed successfully, the alerts were generated correctly and all indices were in a green state:

![Screenshot from 2024-02-18 22-55-30](https://github.com/wazuh/wazuh/assets/72193239/96baac2d-44ad-4943-9315-7b63c1dcd616)
![Screenshot from 2024-02-18 22-59-25](https://github.com/wazuh/wazuh/assets/72193239/2bb903e1-dceb-48c6-992d-13f599eb80d7)
![Screenshot from 2024-02-18 22-59-43](https://github.com/wazuh/wazuh/assets/72193239/939e6f60-9489-4b58-956e-d41fe899565c)
