### ISSUE TITLE
Premature `IndexerConnector` warnings generated

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#21829]
## Description

Related: https://github.com/wazuh/wazuh/issues/21799
In the mentioned issue, it has been found some errors related to the Vulnerability Detection and the Wazuh indexer connection:

```console
2024/02/08 14:38:46 indexer-connector: WARNING: Error initializing IndexerConnector: Problem with the local SSL certificate, we will try again after 2 seconds.
2024/02/08 14:38:48 indexer-connector: WARNING: Error initializing IndexerConnector: Problem with the local SSL certificate, we will try again after 4 seconds.
2024/02/08 14:38:52 indexer-connector: WARNING: Error initializing IndexerConnector: Problem with the local SSL certificate, we will try again after 8 seconds.
2024/02/08 14:39:01 indexer-connector: WARNING: Error initializing IndexerConnector: Problem with the local SSL certificate, we will try again after 16 seconds.

2024/02/08 14:39:17 indexer-connector: INFO: IndexerConnector initialized.


2024/02/08 14:42:39 indexer-connector: WARNING: Error initializing IndexerConnector: HTTP response code said error: 401, we will try again after 2 seconds.
2024/02/08 14:42:41 indexer-connector: WARNING: Error initializing IndexerConnector: HTTP response code said error: 401, we will try again after 4 seconds.
2024/02/08 14:42:47 indexer-connector: WARNING: Error initializing IndexerConnector: HTTP response code said error: 401, we will try again after 8 seconds.

2024/02/08 14:42:56 indexer-connector: INFO: IndexerConnector initialized.
```

:warning: It seems that the Wazuh manager can not connect to the Wazuh indexer, and some warnings are generated. After some time, the connection is established. Then, when the service is restarted, the warnings are generated again, and then the connection is established again.

:heavy_check_mark: This is not a real problem because the connection is successful, but these warning messages are generated in the logs.

## Tasks

It should be necessary to change the handling of this process or take this behavior as a "Known issue".

**Comment by sebasfalcone** [comment]
@Dwordcito What do you think?

We could throw different custom exceptions depending the scenario:

https://github.com/wazuh/wazuh/blob/323708e1e0548aa5c9ac905c7663e1b418ae0f14/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L246-L249

https://github.com/wazuh/wazuh/blob/323708e1e0548aa5c9ac905c7663e1b418ae0f14/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L262-L265


Catch them and have different logs accordingly:

https://github.com/wazuh/wazuh/blob/323708e1e0548aa5c9ac905c7663e1b418ae0f14/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L205-L211

But I think this should be addressed in another time
