### ISSUE TITLE
Possible To Disable Specific Log Pullbacks Using agent.conf File?

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#2182]
**OS**
Manager Debian / Agent CentOS

**Wazuh version**
3.7.2

**Log sample**
```
{"timestamp":"2018-12-28T11:53:54.209-0600","rule":{"level":5,"description":"Squid: Forbidden: Attempt to access forbidden file or directory.","id":"35005","firedtimes":872,"mail":false,"groups":["squid"],"pci_dss":["10.2.4"],"gdpr":["IV_35.7.d"]},"agent":{"id":"9999","name":"TEST"},"manager":{"name":"test.com"},"id":"1546019634.84503205","full_log":"1546019633.886      0 10.10.10.10 TCP_DENIED/403 4150 CONNECT test.com:443 - HIER_NONE/- text/html","predecoder":{"timestamp":"1546019633.886     "},"decoder":{"name":"squid-accesslog"},"data":{"action":"TCP_DENIED","srcip":"10.10.10.10","id":"403","url":"test.com:443"},"location":"/var/log/squid/access.log"}
```

Description
----------------
I'm looking to disable the squid proxy access log pullbacks to the manager for a specific agent system, coming from (/var/log/squid/access.log).

I've created a new group on the manager, added this specific agent within it, and created it's own agent.conf configuration, but I'm not able to stop the squid proxy logs pullback. 

I don't have any localfile checks for this folder/file in the agent.conf. Is there a way I can set the agent.conf configuration to ignore pulling back this file, even if it's enabled in the specific agent's local ossec.conf file?

There are cases where the agent was installed, and I don't have access to change their local ossec.conf file anymore without contacting the system owner. I'm looking to disable this from the manager central configuration agent.conf.

**Comment by chemamartinez** [comment]
Hi @Justangatang,

I am afraid is not possible to disable the log collection remotely for certain log files. However, we are constantly working on improving the remote management to centralize it as much as possible, so we will take this use case into account.

Meanwhile, I think you can avoid the Squid related alerts on the manager side by setting a very simple custom rule as follows:

```
<rule id="100001" level="0">
    <if_sid>35000</if_sid>
    <description>No alert about squid logs</description>
</rule>
```

By adding this rule to the local rules file (generally located at `/var/ossec/etc/rules/local_rules.xml`), it will silence all events read from Squid, which go through the rule 35000 as first step. 

I hope it helps.

Best regards,
Chema.

**Comment by chemamartinez** [comment]
Hi @Justangatang,

Let me close the issue. Feel free to reopen it if you have any other doubt.

Regards.
