### ISSUE TITLE
`GET /manager/version/check` test failing for unpublished Wazuh versions

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#21822]
|Wazuh version|Component|
|---|---|
| 4.8.1+ | Wazuh API |

# Description

The following failing check was found in [Merge 4.8.0 into 4.8.1 #21802](https://github.com/wazuh/wazuh/pull/21802/checks?check_run_id=21346627612):
```
test_manager_endpoints.tavern.yaml::GET /manager/version/check FAILED    [ 91%]
```

The error is this:
```
2024/02/08 02:52:18 ERROR: Error in CTI service request: f8611378-e2b8-4b78-9369-e77d6dcc93b7, v4.8.1
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 239, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/manager.py", line 421, in get_update_information
    raise WazuhInternalError(2100, extra_message=extra_message)
wazuh.core.exception.WazuhInternalError: Error 2100 - Error in CTI service request: f8611378-e2b8-4b78-9369-e77d6dcc93b7, v4.8.1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 285, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
wazuh.core.exception.WazuhInternalError: Error 2100 - Error in CTI service request: f8611378-e2b8-4b78-9369-e77d6dcc93b7, v4.8.1
2024/02/08 02:52:18 INFO: testing 172.18.0.1 "GET /manager/version/check" with parameters {} and body {} done in 0.031s: 500
```

The reason is probably because the manager is querying for a version (4.8.1) that has not yet been published in the CTI, which returns a code other than 200:
https://github.com/wazuh/wazuh/blob/f98fbf1ba427f45147afd59dc4073996adc768f6/framework/wazuh/manager.py#L419-L421

Strangely, in the same `api.log` there are requests to the endpoint that did not fail:
```
2024/02/08 02:53:13 INFO: testing 172.18.0.1 "GET /manager/version/check" with parameters {} and body {} done in 0.720s: 200
2024/02/08 02:53:13 INFO: testing 172.18.0.1 "GET /manager/version/check" with parameters {"force_query": "true"} and body {} done in 0.025s: 200
```

[Test_integration_endpoints_B4319_test_manager_endpoints_logs.zip](https://github.com/wazuh/wazuh/files/14207175/Test_integration_endpoints_B4319_test_manager_endpoints_logs.zip)

## To do
It will be necessary to investigate whether the failure is for the reason suggested above and why some requests did not fail. 

We may have to mark the endpoint as xfail [again](https://github.com/wazuh/wazuh/issues/21417) or modify the test so that it considers both an error code 0 and 2100 as correct (since the test can be run for published or unpublished versions).

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Modified the function in charge of validating the last check update response to take into account whenever the test is run in a branch that is not yet released and where the CTI service is not available.

**Comment by GGP1** [comment]
## Update

Updated the modified function's docstring.
