### ISSUE TITLE
Track and solve reported issues for Microsoft Windows SCA policies

### ISSUE THREAD

**Issue by IsExec** [wazuh/wazuh#21860]
This issue will track and solve reported issues for only Microsoft Windows SCA based on the CIS benchmarks for the affected OS.

S/N | Summary | Issue | Affected   Windows OS | Status
-- | -- | -- | -- | --
1 | Non-English Windows   OS | https://github.com/wazuh/wazuh/issues/16842     https://github.com/wazuh/wazuh/issues/17977 | All | Not Started
2 | Powershell query   returns false | https://github.com/wazuh/wazuh/issues/17598 | All | In progress
3 | How missing registry   key is treated | https://github.com/wazuh/wazuh/issues/16479 | All | In Progress
4 | New SCA | https://github.com/wazuh/wazuh/issues/17336 | Windows 8   Workstations | Not Started
5 | New SCA | https://github.com/wazuh/wazuh/issues/17332 | Windows 7   Workstations | Not Started
6 | New SCA | https://github.com/wazuh/wazuh/issues/17335 | Windows Server 2003 | Not Started
7 | New SCA | https://github.com/wazuh/wazuh/issues/17336 | Windows Server 2008 | Not Started
8 | New SCA | https://github.com/wazuh/wazuh/issues/17340 | Windows XP |
9 | False positive in Windows 10 SCA | https://github.com/wazuh/wazuh/issues/21298 | All | Completed

**Comment by ooniagbi** [comment]
https://github.com/wazuh/wazuh/issues/16479 fixed in Windows server 2022 SCA (https://github.com/wazuh/wazuh/issues/17339).

**Comment by ooniagbi** [comment]
Closing this issue because we will track the fixing of the listed issues using Threat Intel objectives.
