### ISSUE TITLE
Upgrade external dependencies

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#21883]
## Dependencies

|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|
|8.5.0|10.41|3.7.2|4.19.1|3.45.0|1.3.1|

### Tier 1

<details open><summary><b>Intel</b></summary>

|OS|Platform|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|--|--|
|CentOS 6|amd64|🟩|🟩|🟩|🟩|🟩|🟩|
|CentOS 6|i386|🟩|🟩|🟩|🟩|🟩|🟩|
|macOS|amd64|🟩|🟩|||🟩|🟩|
|Windows|i686|🟩|🟩|||🟩|🟩|

</details>

<details open><summary><b>ARM</b></summary>

|Platform|OS|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|--|--|
|CentOS 6|aarch64|🟩|🟩|🟩|🟩|🟩|🟩|
|CentOS 6|armv7hl|🟩|🟩|🟩|🟩|🟩|🟩|

~|macOS|arm|🟨|🟨|||🟨|🟨|~

</details>

<details open><summary><b>Other</b></summary>

|OS|Platform|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|--|--|
|CentOS 7|ppc64le|🟩|🟩|🟩|🟩|🟩|🟩|

</details>

### Tier 2

<details open><summary><b>Intel</b></summary>

|OS|Platform|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|--|--|
|CentOS 5| amd64|🟩|🟩|🟩|🟩|🟩|🟩|
|CentOS 5| i386|🟩|🟩|🟩|🟩|🟩|🟩|

</details>

<details open><summary><b>Other</b></summary>

|Platform|OS|CURL|PCRE2|libarchive|rpm|SQLite|zlib|
|--|--|--|--|--|--|--|--|
|Solaris|i386|🟩|🟩|||🟩|🟩|
|Solaris|SPARC|🟩|🟩|||🟩|🟩|
|AIX 6.1|PPC|🟩|🟩|||🟩|🟩|
|HP-UX|IA64|🟩|🟩|||🟩|🟩|
</details>

### Legend

| 🟨 Pending |🟩 Built|🟪 Ready|
|--|--|--|

## Subtasks

- https://github.com/wazuh/wazuh/issues/19338
- https://github.com/wazuh/wazuh/issues/17741
- https://github.com/wazuh/wazuh/issues/21614
- https://github.com/wazuh/wazuh/issues/21615
- https://github.com/wazuh/wazuh/issues/21616
- https://github.com/wazuh/wazuh/issues/21617

**Comment by MarcelKemp** [comment]
## Update
- Tier 1 completed.
- Tomorrow we start with Tier 2. As the provisioning of these machines is necessary, the following issue has been created:
  - https://github.com/wazuh/internal-devel-requests/issues/765

**Comment by TomasTurina** [comment]
Related to: https://github.com/wazuh/wazuh/issues/21956

**Comment by TomasTurina** [comment]
Delayed.

Reason: https://github.com/wazuh/wazuh/issues/21956

**Comment by TomasTurina** [comment]
Resuming this task.

We need to generate new precompiled dependencies for Linux systems to finish this task.
