### ISSUE TITLE
Already registered agent tries to re-register

### ISSUE THREAD

**Issue by csocTseul** [wazuh/wazuh#21897]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.4 | - | Agent | - | Windows 10 |

We are currently experiencing an issue where an already registered client tries to re-register at the wazuh registration server. After the initial registration the authd.pass file remains in the wazuh directory which probably causes the agent to start the registration process again. This fails however due to the agent already beeing connected.

Also is the authd.pass file supposed to stay in the wazuh directory after the initial registration? Since the file contains the registration password in plain text this is not the safest option. Is there a way to make sure that the file gets deleted after registration or should this already be set by default?

**Comment by pereyra-m** [comment]
Hello @csocTseul !

The presence of the file `authd.pass` won't make the agent try to register again.
Could you upload the `ossec.log` file from the agent and manager? (Remember to remove any sensitive data).
Consider that even when the agent is already registered, it might request a new key if it loses the connectivity with the manager, just in case an invalid key is the reason that prevents the proper communication. 

If this behavior isn't adequate for your environment, you can disable the auto-enrollment in the agent configuration
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html#enrollment

On the other hand, you can delete the `authd.pass` file after the registration. There isn't an option to do it automatically, but it is already protected by its permissions.
Another option would be to use certificates instead for enrollment, see these sections for more details

https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/manager-identity-verification.html

https://documentation.wazuh.com/current/user-manual/agent-enrollment/security-options/agent-identity-verification.html

Regards.

**Comment by sebasfalcone** [comment]
Closed due to inactivity - @csocTseul if further assistance is needed re-open this issue
