### ISSUE TITLE
Check Wazuh agent compatibility with the new version of MacOS 14.4 Beta 2

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#21892]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of MacOS 14.4 Beta 2 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/21888

- Release notes: https://developer.apple.com/documentation/macos-release-notes/macos-14_4-release-notes

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response:  restart agent.
- [x] Log capture.

**Comment by lchico** [comment]
# Update

Request macOS Sonoma 14.4 instance on devel request.
Configuring the wash-agent.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/2bcab33c-1020-41b0-b56d-aff1a0f9d64e" alt="dashboard">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/7322378f-7a28-4624-9b08-bbfbe26a5d86" alt="Console">
</details>


<details>
<summary>Agent log after rebooot</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/8ebb8436-53c9-4cba-8a3c-aa3bd851db5e">
</details>


### :green_circle: FIM scheduled

<details>
<summary>Agent:</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/b4e90dd8-d507-49a0-97cf-0248c50d60d7">
</details>


<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/dc5526b8-4c47-4562-99e1-140c281e2261">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/b9d03ed4-37db-4338-83b5-f50a075d030a">
</details>

## :green_circle: Upgrade using WPK
Using a custom WPK and [this](https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/install-custom-wpk.html#run-the-upgrade) procedure was follow (from step 2)

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/150ef5e2-ef23-484f-94ca-b67d7c0b79b0">
</details>


## :green_circle: SCA support
<details>
<summary>Dashboard:</summary>

 <img src="https://github.com/wazuh/wazuh/assets/21695385/c2369b22-7199-444e-9505-e5ccb9ff4c1f">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/5e186451-c3be-474d-a8c7-0cb0ac2ece5d">
</details>

## :green_circle: Vulnerability detector
I downloaded Google Chrome version 119.0.6045.123 from the following site: https://google-chrome.en.uptodown.com/mac/versions and installed it using the following command:
  ```
  sudo installer -pkg google-chrome-119-0-6045-123.pkg -target /Applications/Google\ Chrome
  ```

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/de063646-469f-4e3c-aa05-241af67899ef">
</details>


## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>002</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/d41701e0-1af0-43c4-ad5e-f95ad12ef756">
</details>


## :green_circle: Log Capture ULS
By following the instructions in this [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/configuration.html#macos), I successfully configured the agent and achieved results similar to what is demonstrated [here](https://wazuh.com/blog/enhancing-macos-protection/#:~:text=%25%20sudo%20%2Di-,Wazuh%20dashboard,-Click%20on%20the).

<details>
<summary>Agent configuration:</summary>

```
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">(process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd")</query>
</localfile>

# Restart the agent and run
sudo su
```
</details>
<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/f2c58c72-4196-4abd-8047-6ca726c8a70a">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/548ee463-201c-4f02-85b3-a283cfb75336">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/7e9303d3-69b3-4036-888a-de89f67a6050">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/1216b35b-bf26-42a7-a82b-7f71ca32e8cc">
</details>

**Comment by mjcr99** [comment]
LGTM

**Comment by MarcelKemp** [comment]
LGTM.
