### ISSUE TITLE
Discrepancies in vulnerabilities reported for the same environment with 4.7.2 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#21902]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.8.0-beta1 | Vulnerability Detector | Manager/Agent | Packages | Ubuntu 22, Windows 11, RHEL 9, Amazon Linux 2023, macOS Sonoma |

## Description

During the testing performed on https://github.com/wazuh/wazuh-qa/issues/4898, it was found that for two identical environments (same clean box), the vulnerabilities reported by Vulnerability Detector in 4.7.2 and 4.8.0 are not the same:

OS|Box |4.7.2 Vulnerabilities|4.8.0 Vulnerabilities|
----| ---| ---- | ---| 
macOS Sonoma|macos_1400 (WazuhQAEnviroment)|[99](https://github.com/wazuh/wazuh-qa/files/14260796/macos-clean-vulns.json)| [2](https://github.com/wazuh/wazuh-qa/files/14239580/vulnerabilities_inventory-2024-02-12T14.35.09.298Z.csv) | 
Windows 11 | windows_11 (WazuhQAEnviroment)|[523](https://github.com/wazuh/wazuh-qa/files/14261249/win-clean-vulns.json)| 0 | 
Amazon Linux 2023 |gbailey/al2023| [0](https://github.com/wazuh/wazuh-qa/files/14223808/alas23-clean-vulns.json)|  [1500](https://github.com/wazuh/wazuh/files/14281621/vulnerabilities_inventory-2024-02-14T15.24.16.353Z.csv) |   
Ubuntu 22.04 |ubuntu/jammy64 | [178](https://github.com/wazuh/wazuh-qa/files/14223809/ubuntu-clean-vulns.json) | [34](https://github.com/wazuh/wazuh-qa/files/14238245/vulnerabilities_inventory-2024-02-12T12.17.00.564Z.csv) | 
RHEL 9 | AWS AMI |[62](https://github.com/wazuh/wazuh-qa/files/14278889/rhel-clean-vulns.json)| [2318](https://github.com/wazuh/wazuh-qa/files/14278892/vulnerabilities_inventory-2024-02-14T10.52.18.497Z.csv) |

**Comment by Dwordcito** [comment]
@juliamagan do you have the 2828 cves from Amazon Linux?

**Comment by juliamagan** [comment]
Amazon Linux vulnerabilities updated by @Rebits
