### ISSUE TITLE
Add manager name value to vulnerabilities indexes

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh#21913]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-40803 | Vulnerability | Manager | - | - |

## Description

Wazuh Dashboard needs to pre-filter the vulnerability documents using the selected API information because the user can have different environments configured.

**The environment selected can either have cluster mode enabled or disabled.** If the cluster mode is enabled we will use the `wazuh.cluster.name` to filter the selected cluster, but if the cluster mode is disabled we need a field with the selected manager value.

## Task

- Add the manager name value to be able to filter the alerts when the cluster mode is disabled 

> [!WARNING]  
> It's important to consider the case where a "manager mode" environment _(which already has alerts)_ is upgraded
> to a cluster mode environment (_enables the cluster mode_)
> Will the new cluster configuration be able to get the old alerts?

## Screenshots

![image](https://github.com/wazuh/wazuh/assets/9343732/06f5d7b9-51ab-4732-a2d1-385d3f759243)

![image](https://github.com/wazuh/wazuh/assets/9343732/eef82b13-3f08-46e3-a6d0-afaa8a9e1e32)

**Comment by Dwordcito** [comment]
Indexer changes:
- [ ] Extend vulnerability states template for a new field in wazuh.manager.name

Manager/core changes:
- [ ] Populate wazuh.manager.name field on each scan

**Comment by Dwordcito** [comment]
Removed from the project.

This will be catch in https://github.com/wazuh/wazuh-indexer/issues/157 for the wazuh-indexer side, and https://github.com/wazuh/wazuh/issues/21953 for the wazuh/wazuh side.
