### ISSUE TITLE
Dashboard Vulnerability Accumulation Due to Missing Agent Deletion Mechanism

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#21921]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta1| Vulnerability Detection/Indexer Integration | Manager | Packages | Any |

### Description

Following the recent [vulnerability detector refactor](https://github.com/wazuh/wazuh/issues/14153), the dashboard now provides a comprehensive overview of vulnerabilities across our environment. However, an oversight exists: there's currently no mechanism to remove vulnerabilities associated with deleted agents. Consequently, these vulnerabilities persist under the same agent ID or name, complicating navigation and understanding of the environment's vulnerabilities.

### Steps to Reproduce
- Deploy an All-in-one.
- Enable the vulnerability detection module and the indexer integration.
- Deploy an agent.
- Register the agent to the manager using the name "testing".
- Wait until the agent is scanned.
- Delete the agent.
- Restart the manager.
- In a different environment, deploy another agent using the same name "testing".
- Wait until the agent is scanned.
- Navigate to the dashboard and observe the vulnerabilities.

The vulnerabilities associated with the first agent will now accumulate under the second agent, impeding navigation and understanding of the actual vulnerabilities in the environment.

### Expected Behavior

Upon deleting an agent, the vulnerabilities linked to that agent should be automatically removed from the dashboard. These vulnerabilities become irrelevant to the environment and should not be displayed.

Subsequently deploying a new agent with the same name should not result in the accumulation of vulnerabilities from the previously deleted agent. Each agent should maintain its own set of vulnerabilities, ensuring accurate navigation and understanding of vulnerabilities in the environment.

### Impact

The accumulation of vulnerabilities from deleted agents can lead to confusion and misinterpretation of the environment's vulnerabilities. This can result in incorrect prioritization of vulnerabilities and potential oversight of security risks.

In environments with a high agent turnover rate, this issue can lead to a significant buildup of irrelevant vulnerabilities, hindering navigation and understanding of the environment's vulnerabilities.

### Workaround

To address this issue, we should implement a mechanism for easily deleting the vulnerabilities of deleted agents. Alternatively, we can document a manual workaround for users to remove these vulnerabilities.

### Screenshot

We can see, for the same agent ID, multiple OS detected

![image](https://github.com/wazuh/wazuh/assets/11089305/2ce6a118-7a97-48ab-9042-550bff251574)

**Comment by Dwordcito** [comment]
The idea is to send a notification to all wazuhdb subscribers after the successful deletion of an agent.

Function:
wdb_parse_global_delete_agent
