### ISSUE TITLE
Compare wazuh-db stats in loaded env

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#21937]
## Description

We are investigating whether there has been a decrease in wazuh-db performance, especially in 4.7.2, which could be causing problems such as those described here where agents go to pending status frequently:
- https://github.com/wazuh/wazuh/issues/17737

One of the hypotheses is that the loss of performance is due to a greater number of FIM queries. To rule out or confirm this, we aim to obtain statistics from wazuh-db and other services in an environment like the following:

**Edit:** The env parametrization is now different.
- 50k agents, 25 managers
- With [API load simulation](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/scripts/simulate_api_load.py):
  - KIBANA_API_REQUESTS enabled ([link to requests performed](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/data/api_kibana_template.yaml))
  - EXTRA_LOAD_API_REQUESTS enabled, 30%. ([link to requests performed](https://github.com/wazuh/wazuh-qa/blob/master/deps/wazuh_testing/wazuh_testing/data/api_extra_load_template.yaml)).
  - TEST_PERFORMANCE_API_ENDPOINTS **disabled**.
- Hybrid mode
- MANAGER_INSTANCES and AGENT_INSTANCES: c5xlarge
- EPS:
  - 1: FIM_EPS
  - 1: FIM_INTEGRITY_EPS
  - 1: WINDOWS_EVENT_EPS
  - 1: SYSCOLLECTOR_EPS
  - 0: ROOTCHECK_EPS
  - 0: SCA_EPS
  - 0: HOST_INFO_EPS
- TEST_TIME: 3600s
- Version to test: 4.7.2 for now (later, 4.7.3)
- MANAGER_MONITORING_PROCESSES:
  - wazuh-remoted
  - wazuh-db
  - wazuh-apid
  - wazuh-analysisd
  - wazuh_clusterd
- MANAGER_MONITORING_STATS:
  - Remote
  - Analysis
  - Logcollector
  - **Wazuh-db** <- Most important

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
## Update

Here are the stats of the 4.7.2 manager running for 30 minutes:
- [stats_472.zip](https://github.com/wazuh/wazuh/files/14314234/stats_472.zip)

There were some errors in the pipeline when using version 4.5.4, so the comparison cannot yet be made.

**Comment by Selutario** [comment]
We decided to run a different parametrization for the test. We will need the changes being developed here to be ready and merged before continuing. Moving to blocked in the mean time:
- https://github.com/wazuh/wazuh-qa/pull/4970

**Comment by fdalmaup** [comment]
# Issue Update

Run the tests according to the described parameters for `v4.7.2`. Here are the artifacts of said build, containing the statistics for `wazuh-db` in the `<node>/data/stats/wazuhdbd` folders (_due to the size of the compressed file, it was divided into three parts_):

[artifacts4.7.2-I.zip](https://github.com/wazuh/wazuh/files/14389733/artifacts4.7.2-I.zip)
[artifacts4.7.2-II.zip](https://github.com/wazuh/wazuh/files/14389741/artifacts4.7.2-II.zip)
[artifacts4.7.2-III.zip](https://github.com/wazuh/wazuh/files/14389751/artifacts4.7.2-III.zip)

A new build for `4.7.3` is in progress to contrast the results.

**Comment by fdalmaup** [comment]
# Issue Update

The build for the `4.7.3` branch was successful. A script was developed to parse the CSV files from both versions and to obtain the difference in the obtained statistics. Currently, the output of the script has the following format:
```json
{
    "node": {
        "4.7.2":  {<values ​​obtained from the final 'Interval (Timestamp-Uptime)' number closest to its homonymous of `4.7.3`>},
        "4.7.3":  {<values ​​obtained from the final 'Interval (Timestamp-Uptime)' number closest to its homonymous of `4.7.2`>},
        "diff": {
            "value":  {<difference between the values of 4.7.2 and 4.7.3>},
            "percentage": { <percentage difference between the values of 4.7.2 and 4.7.3>}
        }
    },
   ...
}
```
An enhancement of the script is being carried out to obtain a more user-friendly and simpler to analyze output.

**Comment by Selutario** [comment]
# Issue Update

Although @fdalmaup's script is still in development, there is some interesting data we can read by using it. The information shown below is the percentage change in 4.7.3 compared to 4.7.2. Some managers' stats return `NaN` when processed by the script, so they have been excluded for now.

First of all, if we review the **number of queries received in wazuh-db**, we see that in general terms it has remained the same. Each line represents a different manager (as I said before, these are only 12 of the 25 managers).
```
$ grep "Received queries" perct_change.json 
                "Received queries": 7.318130631375469,
                "Received queries": -0.3554369835779857,
                "Received queries": -2.864032880032446,
                "Received queries": -4.327315964202278,
                "Received queries": 1.0817438395916212,
                "Received queries": 0.08604827154375977,
                "Received queries": 2.7927693588311544,
                "Received queries": -1.811122526081125,
                "Received queries": 0.25234002366533853,
                "Received queries": 3.90189605345461,
                "Received queries": -0.43476125346479916,
                "Received queries": -4.834000638868269,
```

Despite receiving the same number of queries, if we read the **wazuh-db execution time** stat, we can see that it decreases (in most cases) between 40 and 50%. In other words, comparing a 4.7.2 and 4.7.3 environment, with the same number of agents, test time, resources, requests to wazuh-db, etc., the execution time is ~40% lower in 4.7.3.
```
$ grep "Total Execution Time" perct_change.json 
                "Total Execution Time": -34.71932539523704,
                "Total Execution Time": -42.60232926787482,
                "Total Execution Time": -48.09903870767681,
                "Total Execution Time": -48.64511314925159,
                "Total Execution Time": -42.84705575714259,
                "Total Execution Time": -42.33412335736733,
                "Total Execution Time": -41.09948479414704,
                "Total Execution Time": -48.28319914855067,
                "Total Execution Time": -40.52888755575768,
                "Total Execution Time": -44.04810211870779,
                "Total Execution Time": -43.07399522497184,
                "Total Execution Time": -51.52132241851235,
```

If we break down the execution time by category, we see that the decrease in execution time related to `Agent ExecTIme` is between 40 and 55%:
```
$ grep "Agent ExecTime" perct_change.json 
                "Agent ExecTime": -39.356410551779746,
                "Agent ExecTime": -46.86436947858587,
                "Agent ExecTime": -52.06631378516069,
                "Agent ExecTime": -52.34023548802658,
                "Agent ExecTime": -46.8971548653507,
                "Agent ExecTime": -46.29122326986959,
                "Agent ExecTime": -45.386536498121835,
                "Agent ExecTime": -51.709088015179326,
                "Agent ExecTime": -44.973258248177956,
                "Agent ExecTime": -48.094662746647245,
                "Agent ExecTime": -47.22032342256089,
                "Agent ExecTime": -55.77982492544372,
```

Something similar happens for **Syscheck** stats:
```
$ grep "Table Syscheck.1" perct_change.json 
                "Table Syscheck.1": -30.713933252295732,
                "Table Syscheck.1": -36.68392970131807,
                "Table Syscheck.1": -45.13066202090592,
                "Table Syscheck.1": -44.34226474401958,
                "Table Syscheck.1": -39.2734107645812,
                "Table Syscheck.1": -37.146885220388484,
                "Table Syscheck.1": -37.69123610348912,
                "Table Syscheck.1": -44.26213990119695,
                "Table Syscheck.1": -36.560679223600204,
                "Table Syscheck.1": -37.34693039004363,
                "Table Syscheck.1": -39.66948927114737,
                "Table Syscheck.1": -46.67050932054701,
``` 

While even better results are found for **Syscheck file** table:
```
$ grep "Table Syscheck file.1" perct_change.json 
                "Table Syscheck file.1": -80.0,
                "Table Syscheck file.1": -78.26086956521739,
                "Table Syscheck file.1": -81.37254901960785,
                "Table Syscheck file.1": -82.6086956521739,
                "Table Syscheck file.1": -78.3132530120482,
                "Table Syscheck file.1": -83.0,
                "Table Syscheck file.1": -81.63265306122449,
                "Table Syscheck file.1": -77.55102040816327,
                "Table Syscheck file.1": -76.34408602150538,
                "Table Syscheck file.1": -84.95575221238938,
                "Table Syscheck file.1": -79.46428571428571,
                "Table Syscheck file.1": -81.0,
```


We should review this again once we have data for all managers, and do deeper research on more stats.

**Comment by fdalmaup** [comment]
# Issue Update

After some fixes on the script here are the results of the recollection:

## Nodes data per version

<details><summary>master</summary>

|                             |   4.7.2 |   4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|--------:|--------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |     817 |     819 |           -2 |          0.244798 |
| Received queries            |  103328 |  109191 |        -5863 |          5.67416  |
| Total Execution Time        |  154253 |  166154 |       -11901 |          7.71525  |
| Agent ExecTime              |     214 |     149 |           65 |        -30.3738   |
| Table Syscheck.1            |      10 |       7 |            3 |        -30        |
| Table Syscheck file.1       |      28 |       9 |           19 |        -67.8571   |

</details>
<details><summary>worker_1</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4684           |   4678           |            6 |         -0.128096 |
| Received queries            |      2.12866e+07 |      2.18811e+07 |      -594485 |          2.79277  |
| Total Execution Time        |      2.00541e+06 |      1.1812e+06  |       824214 |        -41.0995   |
| Agent ExecTime              |      1.67291e+06 | 913633           |       759275 |        -45.3865   |
| Table Syscheck.1            | 805418           | 501846           |       303572 |        -37.6912   |
| Table Syscheck file.1       |     98           |     18           |           80 |        -81.6327   |

</details>
<details><summary>worker_10</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4687           |   4662           |     25           |          -0.53339 |
| Received queries            |      2.19906e+07 |      2.15923e+07 | 398277           |          -1.81112 |
| Total Execution Time        |      2.2982e+06  |      1.18856e+06 |      1.10964e+06 |         -48.2832  |
| Agent ExecTime              |      1.90997e+06 | 922340           | 987626           |         -51.7091  |
| Table Syscheck.1            | 897948           | 500497           | 397451           |         -44.2621  |
| Table Syscheck file.1       |     98           |     22           |     76           |         -77.551   |

</details>
<details><summary>worker_11</summary>

|                             |          4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|---------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) | 4678           |   4667           |     11           |         -0.235143 |
| Received queries            |    2.12176e+07 |      2.2298e+07  |     -1.08041e+06 |          5.09206  |
| Total Execution Time        |    2.56922e+06 |      1.25252e+06 |      1.3167e+06  |        -51.249    |
| Agent ExecTime              |    2.15106e+06 | 975666           |      1.17539e+06 |        -54.6425   |
| Table Syscheck.1            |    1.00656e+06 | 533042           | 473513           |        -47.0429   |
| Table Syscheck file.1       |  106           |     19           |     87           |        -82.0755   |

</details>
<details><summary>worker_12</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4682           |   4670           |           12 |         -0.256301 |
| Received queries            |      2.14354e+07 |      2.16673e+07 |      -231876 |          1.08174  |
| Total Execution Time        |      2.20225e+06 |      1.25865e+06 |       943598 |        -42.8471   |
| Agent ExecTime              |      1.83636e+06 | 975161           |       861202 |        -46.8972   |
| Table Syscheck.1            | 875185           | 531470           |       343715 |        -39.2734   |
| Table Syscheck file.1       |     83           |     18           |           65 |        -78.3133   |

</details>
<details><summary>worker_13</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4757           |   4742           |           15 |         -0.315325 |
| Received queries            |      2.16426e+07 |      2.16972e+07 |       -54613 |          0.25234  |
| Total Execution Time        |      2.06698e+06 |      1.22926e+06 |       837724 |        -40.5289   |
| Agent ExecTime              |      1.73829e+06 | 956526           |       781767 |        -44.9733   |
| Table Syscheck.1            | 831891           | 527746           |       304145 |        -36.5607   |
| Table Syscheck file.1       |     93           |     22           |           71 |        -76.3441   |

</details>
<details><summary>worker_14</summary>

|                             |            4.7.2 |            4.7.3 |        diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|------------------:|------------------:|
| Interval (Timestamp-Uptime) |   4751           |   4744           |       7           |         -0.147337 |
| Received queries            |      2.16401e+07 |      2.20607e+07 | -420523           |          1.94326  |
| Total Execution Time        |      2.3205e+06  |      1.27875e+06 |       1.04174e+06 |        -44.8932   |
| Agent ExecTime              |      1.96075e+06 | 988475           |  972274           |        -49.5869   |
| Table Syscheck.1            | 938524           | 540263           |  398261           |        -42.4348   |
| Table Syscheck file.1       |    117           |     18           |      99           |        -84.6154   |

</details>
<details><summary>worker_15</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4759           |   4740           |           19 |        -0.399244  |
| Received queries            |      2.20583e+07 |      2.20767e+07 |       -18475 |         0.0837555 |
| Total Execution Time        |      2.19304e+06 |      1.26208e+06 |       930965 |       -42.4509    |
| Agent ExecTime              |      1.85681e+06 | 981492           |       875316 |       -47.1409    |
| Table Syscheck.1            | 845060           | 538509           |       306551 |       -36.2756    |
| Table Syscheck file.1       |     92           |     18           |           74 |       -80.4348    |

</details>
<details><summary>worker_16</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4684           |   4668           |     16           |         -0.341588 |
| Received queries            |      2.11667e+07 |      2.27157e+07 |     -1.54900e+06 |          7.31813  |
| Total Execution Time        |      2.07363e+06 |      1.35368e+06 | 719950           |        -34.7193   |
| Agent ExecTime              |      1.7362e+06  |      1.05289e+06 | 683306           |        -39.3564   |
| Table Syscheck.1            | 830890           | 575691           | 255199           |        -30.7139   |
| Table Syscheck file.1       |     95           |     19           |     76           |        -80        |

</details>
<details><summary>worker_17</summary>

|                             |            4.7.2 |            4.7.3 |        diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|------------------:|------------------:|
| Interval (Timestamp-Uptime) |   4659           |   4668           |      -9           |          0.193175 |
| Received queries            |      2.13172e+07 |      2.2149e+07  | -831776           |          3.9019   |
| Total Execution Time        |      2.3806e+06  |      1.33199e+06 |       1.04861e+06 |        -44.0481   |
| Agent ExecTime              |      1.99217e+06 |      1.03404e+06 |  958126           |        -48.0947   |
| Table Syscheck.1            | 900489           | 564184           |  336305           |        -37.3469   |
| Table Syscheck file.1       |    113           |     17           |      96           |        -84.9558   |

</details>
<details><summary>worker_18</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4759           |   4738           |     21           |         -0.441269 |
| Received queries            |      2.23362e+07 |      2.16965e+07 | 639717           |         -2.86403  |
| Total Execution Time        |      2.4025e+06  |      1.24692e+06 |      1.15558e+06 |        -48.099    |
| Agent ExecTime              |      2.02353e+06 | 969953           |      1.05358e+06 |        -52.0663   |
| Table Syscheck.1            | 964320           | 529116           | 435204           |        -45.1307   |
| Table Syscheck file.1       |    102           |     19           |     83           |        -81.3725   |

</details>
<details><summary>worker_19</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4685           |   4671           |           14 |         -0.298826 |
| Received queries            |      2.15506e+07 |      2.20879e+07 |      -537288 |          2.49315  |
| Total Execution Time        |      2.2118e+06  |      1.25256e+06 |       959240 |        -43.3693   |
| Agent ExecTime              |      1.85447e+06 | 970360           |       884110 |        -47.6745   |
| Table Syscheck.1            | 876520           | 529248           |       347272 |        -39.6194   |
| Table Syscheck file.1       |     95           |     18           |           77 |        -81.0526   |

</details>
<details><summary>worker_2</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4754           |   4742           |     12           |         -0.252419 |
| Received queries            |      2.23754e+07 |      2.20833e+07 | 292117           |         -1.30553  |
| Total Execution Time        |      2.5796e+06  |      1.2115e+06  |      1.3681e+06  |        -53.0355   |
| Agent ExecTime              |      2.16242e+06 | 942565           |      1.21986e+06 |        -56.4116   |
| Table Syscheck.1            | 988419           | 516791           | 471628           |        -47.7154   |
| Table Syscheck file.1       |    103           |     21           |     82           |        -79.6117   |

</details>
<details><summary>worker_20</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4684           |   4668           |           16 |         -0.341588 |
| Received queries            |      2.15093e+07 |      2.14328e+07 |        76452 |         -0.355437 |
| Total Execution Time        |      2.21804e+06 |      1.2731e+06  |       944935 |        -42.6023   |
| Agent ExecTime              |      1.85845e+06 | 987497           |       870949 |        -46.8644   |
| Table Syscheck.1            | 880301           | 557372           |       322929 |        -36.6839   |
| Table Syscheck file.1       |     92           |     20           |           72 |        -78.2609   |

</details>
<details><summary>worker_21</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4683           |   4662           |     21           |          -0.44843 |
| Received queries            |      2.22533e+07 |      2.17304e+07 | 522881           |          -2.34968 |
| Total Execution Time        |      2.26406e+06 |      1.24936e+06 |      1.01471e+06 |         -44.8179  |
| Agent ExecTime              |      1.90242e+06 | 972675           | 929748           |         -48.8718  |
| Table Syscheck.1            | 904083           | 529843           | 374240           |         -41.3944  |
| Table Syscheck file.1       |     99           |     17           |     82           |         -82.8283  |

</details>
<details><summary>worker_22</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4684           |   4669           |     15           |         -0.320239 |
| Received queries            |      2.18702e+07 |      2.12143e+07 | 655908           |         -2.9991   |
| Total Execution Time        |      2.1955e+06  |      1.17293e+06 |      1.02258e+06 |        -46.5759   |
| Agent ExecTime              |      1.84054e+06 | 911738           | 928807           |        -50.4637   |
| Table Syscheck.1            | 857789           | 493740           | 364049           |        -42.4404   |
| Table Syscheck file.1       |     84           |     20           |     64           |        -76.1905   |

</details>
<details><summary>worker_23</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4687           |   4671           |     16           |          -0.34137 |
| Received queries            |      2.24819e+07 |      2.19211e+07 | 560848           |          -2.49466 |
| Total Execution Time        |      2.405e+06   |      1.1792e+06  |      1.22580e+06 |         -50.969   |
| Agent ExecTime              |      2.0163e+06  | 912630           |      1.10367e+06 |         -54.7373  |
| Table Syscheck.1            | 955479           | 501077           | 454402           |         -47.5575  |
| Table Syscheck file.1       |     89           |     16           |     73           |         -82.0225  |

</details>
<details><summary>worker_24</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4683           |   4673           |           10 |        -0.213538  |
| Received queries            |      2.21271e+07 |      2.21462e+07 |       -19040 |         0.0860483 |
| Total Execution Time        |      2.20036e+06 |      1.26885e+06 |       931501 |       -42.3341    |
| Agent ExecTime              |      1.84053e+06 | 988524           |       852002 |       -46.2912    |
| Table Syscheck.1            | 873866           | 549252           |       324614 |       -37.1469    |
| Table Syscheck file.1       |    100           |     17           |           83 |       -83         |

</details>
<details><summary>worker_25</summary>

|                             |   4.7.2 |            4.7.3 |        diff_value |   diff_percentage |
|:----------------------------|--------:|-----------------:|------------------:|------------------:|
| Interval (Timestamp-Uptime) |     559 |   4671           |   -4112           |          735.599  |
| Received queries            |  160953 |      2.21012e+07 |      -2.19403e+07 |        13631.5    |
| Total Execution Time        |   35167 |      1.1933e+06  |      -1.15814e+06 |         3293.24   |
| Agent ExecTime              |   26663 | 925145           | -898482           |         3369.77   |
| Table Syscheck.1            |    9190 | 512120           | -502930           |         5472.58   |
| Table Syscheck file.1       |      17 |     19           |      -2           |           11.7647 |

</details>
<details><summary>worker_3</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4689           |   4673           |     16           |         -0.341224 |
| Received queries            |      2.24178e+07 |      2.13341e+07 |      1.08368e+06 |         -4.834    |
| Total Execution Time        |      2.44304e+06 |      1.18435e+06 |      1.25869e+06 |        -51.5213   |
| Agent ExecTime              |      2.07226e+06 | 916357           |      1.1559e+06  |        -55.7798   |
| Table Syscheck.1            | 947262           | 505170           | 442092           |        -46.6705   |
| Table Syscheck file.1       |    100           |     19           |     81           |        -81        |

</details>
<details><summary>worker_4</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4691           |   4669           |     22           |         -0.468983 |
| Received queries            |      2.22656e+07 |      2.10045e+07 |      1.26112e+06 |         -5.66398  |
| Total Execution Time        |      2.3461e+06  |      1.27824e+06 |      1.06786e+06 |        -45.5166   |
| Agent ExecTime              |      1.95764e+06 | 996350           | 961292           |        -49.1046   |
| Table Syscheck.1            | 927370           | 541804           | 385566           |        -41.5763   |
| Table Syscheck file.1       |    105           |     18           |     87           |        -82.8571   |

</details>
<details><summary>worker_5</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4686           |   4671           |     15           |         -0.320102 |
| Received queries            |      2.18929e+07 |      2.09455e+07 | 947375           |         -4.32732  |
| Total Execution Time        |      2.38278e+06 |      1.22368e+06 |      1.15911e+06 |        -48.6451   |
| Agent ExecTime              |      1.9973e+06  | 951908           |      1.04539e+06 |        -52.3402   |
| Table Syscheck.1            | 945502           | 526245           | 419257           |        -44.3423   |
| Table Syscheck file.1       |     92           |     16           |     76           |        -82.6087   |

</details>
<details><summary>worker_6</summary>

|                             |            4.7.2 |            4.7.3 |        diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|------------------:|------------------:|
| Interval (Timestamp-Uptime) |   4688           |   4670           |      18           |         -0.383959 |
| Received queries            |      2.17506e+07 |      2.21253e+07 | -374638           |          1.72242  |
| Total Execution Time        |      2.248e+06   |      1.22064e+06 |       1.02736e+06 |        -45.7012   |
| Agent ExecTime              |      1.88498e+06 | 945465           |  939514           |        -49.8421   |
| Table Syscheck.1            | 893580           | 524395           |  369185           |        -41.3153   |
| Table Syscheck file.1       |     99           |     19           |      80           |        -80.8081   |

</details>
<details><summary>worker_7</summary>

|                             |            4.7.2 |            4.7.3 |   diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-------------:|------------------:|
| Interval (Timestamp-Uptime) |   4760           |   4733           |           27 |         -0.567227 |
| Received queries            |      2.18458e+07 |      2.17508e+07 |        94977 |         -0.434761 |
| Total Execution Time        |      2.25842e+06 |      1.28563e+06 |       972790 |        -43.074    |
| Agent ExecTime              |      1.90618e+06 |      1.00607e+06 |       900102 |        -47.2203   |
| Table Syscheck.1            | 902240           | 544326           |       357914 |        -39.6695   |
| Table Syscheck file.1       |    112           |     23           |           89 |        -79.4643   |

</details>
<details><summary>worker_8</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4683           |   4668           |     15           |         -0.320307 |
| Received queries            |      2.20059e+07 |      2.17384e+07 | 267447           |         -1.21534  |
| Total Execution Time        |      2.45888e+06 |      1.22736e+06 |      1.23152e+06 |        -50.0844   |
| Agent ExecTime              |      2.06435e+06 | 949514           |      1.11484e+06 |        -54.0042   |
| Table Syscheck.1            | 937258           | 514778           | 422480           |        -45.0762   |
| Table Syscheck file.1       |     94           |     19           |     75           |        -79.7872   |

</details>
<details><summary>worker_9</summary>

|                             |            4.7.2 |            4.7.3 |       diff_value |   diff_percentage |
|:----------------------------|-----------------:|-----------------:|-----------------:|------------------:|
| Interval (Timestamp-Uptime) |   4758           |   4741           |     17           |         -0.357293 |
| Received queries            |      2.10088e+07 |      2.26363e+07 |     -1.62752e+06 |          7.74687  |
| Total Execution Time        |      2.48702e+06 |      1.27942e+06 |      1.20760e+06 |        -48.5562   |
| Agent ExecTime              |      2.07858e+06 | 999666           |      1.07891e+06 |        -51.9063   |
| Table Syscheck.1            | 983114           | 542042           | 441072           |        -44.8648   |
| Table Syscheck file.1       |     99           |     20           |     79           |        -79.798    |

</details>
