### ISSUE TITLE
Configure email alert based on specific group or agent name

### ISSUE THREAD

**Issue by Sameer484** [wazuh/wazuh#21949]
Is there any method to send email for logs that are generated only from specific agent or agent groups? I tried with <event_location>agent_name_herer</event_location> but it didn't worked as expected. I'm getting emails from other agent too.

**Comment by davidcr01** [comment]
To configure Wazuh to send email alerts for logs generated only from specific agents or agent groups, you can utilize the `<email_alerts>` configuration in the `ossec.conf` file. This configuration allows you to specify the conditions under which email alerts should be sent, including filtering by agent names or groups.

However, the `<event_location>` tag mentioned in the user's query does not directly correspond to filtering by agent names or groups for email alerts. Instead, you should use the `<location>` tag within the `<email_alerts>` configuration to specify the agent names or groups from which you want to receive alerts. Additionally, the `<group>` or `<rule>` tags can be used to further refine the alerts based on specific criteria such as rule groups or rule IDs.

For example, to receive email alerts only from specific agents named "server1", "server2", or "server3", you can configure the `ossec.conf` file as follows:

```xml
<ossec_config>
  <global>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>em...@email.com</email_from>
    <email_maxperhour>15</email_maxperhour>
  </global>
  <email_alerts>
    <email_to>y...@example.com</email_to>
    <level>12</level>
    <location>server1|server2|server3</location>
    <do_not_delay />
  </email_alerts>
</ossec_config>
```

In this configuration, `<email_to>` specifies the recipient's email address, `<level>` specifies the minimum alert level for which emails should be sent, and `<location>` is used to filter alerts originating from specific agents (in this case, "server1", "server2", or "server3"). The `<do_not_delay>` tag ensures that alerts are sent immediately without delay.

It's important to note that the `<location>` tag here is used illustratively to represent how you might attempt to filter by agent names or groups. The actual implementation may require using the agent ID or name as it appears in the alert logs. For precise filtering based on agent names or groups, you may need to customize your alert rules or use external scripting to parse and filter alerts before sending emails.

For more detailed information on configuring email alerts and reports in Wazuh, including the available options and tags, you can refer to the official [Wazuh documentation](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html).

Also, we have a blog page with more information about this: https://wazuh.com/blog/how-to-send-email-notifications-with-wazuh/

**Comment by Sameer484** [comment]
This is not working either. In fact, when i use location tag, the wazuh manager throws error and failed to even start the wazuh-manager.
