### ISSUE TITLE
Unexpected TLS connection closure during the API integration tests

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#21942]
|Wazuh version|Component|
|---|---|
| 4.8.1| RESTful API |

## Description

During the development of https://github.com/wazuh/wazuh/issues/21822, the API integration tests failed because of a TLS/SSL connection error.

```console
E   ConnectionResetError: [Errno 104] Connection reset by peer
...
E   requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
...
E   ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)
```

This failure is sporadic and seems to be caused by the fact that the API didn't start in the master node (it did in the workers). We should investigate the root cause of the issue, fix it and ensure there are no more sporadic connection errors.

Artifacts: [artifacts.zip](https://github.com/user-attachments/files/17281603/artifacts.zip)

<details><summary>API logs</summary>

```console

2024/10/07 14:27:42 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2024/10/07 14:27:43 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2024/10/07 14:27:43 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2024/10/07 14:27:43 INFO: Checking RBAC database integrity...
2024/10/07 14:27:43 INFO: RBAC database not found. Initializing
2024/10/07 14:29:01 INFO: /var/ossec/api/configuration/security/rbac.db database created successfully
2024/10/07 14:29:01 INFO: RBAC database integrity check finished successfully
# "Listening on" message missing
```

</details>

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The error hasn't been found since [Release 4.9.1 - RC 3 - API integration tests #26207](https://github.com/wazuh/wazuh/issues/26207), being executed successfully in the following stages:

- https://github.com/wazuh/wazuh/issues/26347
- https://github.com/wazuh/wazuh/issues/26621
- https://github.com/wazuh/wazuh/issues/26451
- https://github.com/wazuh/wazuh/issues/26809
- https://github.com/wazuh/wazuh/issues/26990
- https://github.com/wazuh/wazuh/issues/27236
- https://github.com/wazuh/wazuh/issues/27349

> [!Note]
> It has been mistakenly mentioned in https://github.com/wazuh/wazuh/issues/26892, the error in that issue is a different one.

We can therefore conclude that it was caused by a bug in a dependency, during the server initialization or in the test environment setup that was resolved after the report.

Moreover, no community/client reports exist about this error, which reinforces what was mentioned above.

**Comment by nico-stefani** [comment]
LGTM

**Comment by fdalmaup** [comment]
LGTM
