### ISSUE TITLE
ERROR: It was not possible to extract the permissions of

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#2194]
## Bug report

**OS**
_Windows 10 Pro._

**Wazuh version**
_3.7.2_

**Install type**
_agent_

**Install method**
_packages_

**Log sample**

```
2019/01/01 14:03:55 ossec-agent: ERROR: It was not possible to extract the permissions of 'c:\programdata\microsoft\windows\start menu\programs\startup\desktop.ini'. Error: -3.
```

Bug description
----------------
Agent shows the above log sample when starting.
That file exists in the file system (it is a protected operating system file).

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/pull/2940.

But it is a Wazuh 3.8.X error.

**Comment by albertomn86** [comment]
Merged.
