### ISSUE TITLE
Syscollector (via Sysinfo library) could wrongly guess the OS main package manager

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#21956]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| up to master | Syscollector - Data Provider (Sysinfo) | Manager - Agent | Any | Linux |

# Description

It was discovered that Syscollector (via the Sysinfo library) could guess that an operating system has a package manager when it does not. 

https://github.com/wazuh/wazuh/blob/a95222fdc6c4b854dda168d866cfa1de1c8baf12/src/data_provider/src/packages/packageLinuxDataRetriever.h#L77-L107

**Examples**
- On a Ubuntu 22.04 system install `rpm` in order to pack any software using rpm.
- GHA Ubuntu 22.04 runner https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md

`rpm` package creates `/var/lib/rpm` dir but without being used (mainly) to install packages, but package any software. This is interpreted as being a package manager and try to parse the packages' database

**Comment by TomasTurina** [comment]
### Update

We decided to update to RPM v4.18.2.

The version v4.19.1 has changed the way the library is compiled and we couldn't make it work.

The library v4.18.2 solves all the [vulnerabilities reported](https://docs.google.com/spreadsheets/d/1m3OOWvKs10OEwWxBwXPaextsM0lumWTqHk4gYrEES50/edit#gid=0) and it's still a [supported release](https://rpm.org/download.html).

We need to generate the precompiled dependencies again for Linux systems. This is the latest remaining task to close this issue.

Considering that the new library used solves this problem alongside this [commit](https://github.com/wazuh/wazuh/pull/21710/commits/ceb59b5572147910a5455412312e3e03a6c04107), I'll proceed to close this issue.
