### ISSUE TITLE
Populate wazuh.manager.name field on each scan

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#21953]
### Description

This issue involves populating the `wazuh.manager.name` field when indexing an element. To achieve this, the Wazuh Manager name will be retrieved from the Wazuh DB by querying agent 000 when the module starts. This name will then be used throughout the lifetime of the process for indexing purposes.

### Proposed Changes

1. **Retrieve Wazuh Manager Name:**
   - Implement a query to retrieve the Wazuh Manager name from the Wazuh DB by querying agent 000 when the module starts.
   - Store the retrieved Wazuh Manager name for later use during indexing.

2. **Populate Field During Indexing:**
   - Utilize the retrieved Wazuh Manager name to populate the `wazuh.manager.name` field when indexing elements.

### Implementation Steps

1. **Retrieve Wazuh Manager Name:**
   - Implement a SQL query to select the Wazuh Manager name from the Wazuh DB using the helper https://github.com/wazuh/wazuh/blob/master/src/shared_modules/utils/wazuhDBQueryBuilder.hpp
   - Execute the query when the module starts.
   - Store the retrieved Wazuh Manager name in memory or as a global variable.

2. **Populate Field During Indexing:**
   - Modify the indexing logic to include the Wazuh Manager name retrieved in step 1.
   - Populate the `wazuh.manager.name` field with the retrieved name during indexing.

### Impact

- **Improved Data Context:** Populating the `wazuh.manager.name` field provides valuable context about the origin of indexed elements, enhancing the overall understanding of the data.
- **Consistency:** Using the Wazuh Manager name consistently throughout the indexing process ensures uniformity in the indexed data.

### Definition of Done

- The Wazuh Manager name is successfully retrieved from the Wazuh DB during module startup.
- The retrieved Wazuh Manager name is utilized to populate the `wazuh.manager.name` field during indexing.
- Testing confirms that the Wazuh Manager name is correctly included in indexed elements.

**Comment by Dwordcito** [comment]
Some questions were made in IM.

`when indexing an element` Where does this happen?
this occurs in resultIndexer.hpp

`when the module starts` What would the module be?
Vulnerability scanner, Use the ScanOrchestrator constructor to get the information.

`from the Wazuh DB by querying agent 000`
Yes

`Store the retrieved Wazuh Manager name in memory or as a global variable.` Is there any global class or place to store the variable?
ScanOrchestrator member variable.

`Modify the indexing logic to include the Wazuh Manager name retrieved in step 1.` Where is this done? 
In detailsAugmentation.hpp the data is populated.

**Comment by mateocervilla** [comment]
## ETA Update
Changed because it will take longer than expected

**Comment by tdrauncieal** [comment]
Working on UT debts
