### ISSUE TITLE
Debain Rootcheck

### ISSUE THREAD

**Issue by ajohnson8503** [wazuh/wazuh#2196]
## Feature request

**Compatibility**
_both_

**Component involved**
_Rootcheck_

Description
--------------
I know that there is cis_debian_linux_rcl.txt, but it looks to be missing some of the items for the newer OS Versions. Is there any plans for rolling out an undated version kind of like cis_debianlinux7-8 from OSSEC, but with Debian9 included?

**Comment by crolopez** [comment]
Hi @ajohnson8503,

You are right, those policy files are outdated. However, we do not plan to include a later version in the installation for Rootcheck.

The reason for this is that we have recently developed [Security Configuration Assessment](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html), which overcomes the limitations of Rootcheck, among other improvements, and includes these same files in YAML format, which makes it more accessible to the user.

Finally, I recommend you to use SCA for the evaluation of these policies.

Tell me if you have any more questions about it.

Best regards.

**Comment by Zenidd** [comment]
Hi @ajohnson8503,

As @crolopez said, we do not plan to include a later policies version on Rootcheck. 

We are currently working on an important refactoring of the SCA module (you can track it [here](https://github.com/wazuh/wazuh/issues/3249)) as well as new policies which be available in v3.10. In addition, it is a new module that will be improved in each version.

On the other hand, these policies are based on CIS and designed for evaluating standard configurations. You always can adapt them to your use case by creating custom policies, and ask us for the help you would need in the process.

We recommend you to use SCA to perform your vulnerabilities and configuration scans.

Considering it answered, i'm closing this ticket. Please, feel free to reopen this or open a new one when needed.

Greetings,

Juan Pablo Sáez
