### ISSUE TITLE
`packageScanner`  is not handling a return of type `INVALID_VERSION_OBJECT_TYPE`

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#21965]
### Problem Description
The `packageScanner` component lacks proper validation for cases when `INVALID_VERSION_OBJECT_TYPE = 0x7FFFFFFF` is returned. This scenario can occur under certain conditions, leading to potential issues in version handling and comparison logic. Without appropriate validation, this could result in erroneous behavior or misinterpretation of package versions, affecting the accuracy and reliability of the scanning process.

### Expected Behavior
`packageScanner` should include a validation mechanism to detect and appropriately handle instances where `INVALID_VERSION_OBJECT_TYPE` is returned.

### Steps to Reproduce
1. Use the UT as reference to create a package with an invalid version, you can use the `scanner` testtool to reproduce this issue.

### Definition of Done Checklist
- [x] Implement validation in `packageScanner` to detect `INVALID_VERSION_OBJECT_TYPE = 0x7FFFFFFF`.
- [x] Create test cases to verify that `INVALID_VERSION_OBJECT_TYPE` is managed correctly across various scenarios.
- [x] Review and validate the enhancement with scenarios that previously led to issues, ensuring the solution is effective.

### Possible Solutions
- Introducing a check early in the scanning process to identify `INVALID_VERSION_OBJECT_TYPE` and apply a predefined

-------

**Comment by sebasfalcone** [comment]
Instead of returning an int, the compare method should use an enum class for this:

```cpp
enum class VersionComparisonResult : int
{
    INVALID,
    A_LESS_THAN_B,
    A_EQUALS_B,
    A_GREATER_THAN_B
};
```

This enum will be defined at `versionMatcher.hpp`

**Comment by sebasfalcone** [comment]
This issue can be addressed at the same time as
- https://github.com/wazuh/wazuh/issues/21943

**Comment by sebasfalcone** [comment]
- Changed size from tiny to medium
  - A refactor must take place in order to handle this scenario
