### ISSUE TITLE
Custom Rule works in test, but isn't used by manager

### ISSUE THREAD

**Issue by mikeh89** [wazuh/wazuh#21981]
|Wazuh version| Component | Action type |
|---| --- | --- |
|4.7.2 | Rules/Decoders | Error |

## Description
I've set up a custom rule to ignore false positives on rule '5104' for devices entering promiscuous mode on some k3s worker nodes, where this behaviour is expected. The rule works as expected when running the ruletest with a related 'full log', but isn't used live (i.e: 5104 is still triggered) 
wazuh-manager.service was restarted after making and testing the changes to local_rules.xml

```  
<rule id="100004" level="0">
    <if_sid>5104</if_sid>
    <hostname type="pcre2">rtd-w\d+|dft-w\d+</hostname>
    <description>ignore network sniffing alerts on k3s workers</description>
    <regex>device \S+ entered promiscuous mode</regex>
 </rule>
```
Also tested with if_sid = 5100 to see if I could trigger this earlier. 

### Service/Product/Module
K3s worker/agent nodes. These are running on nodes with hostnames prefixed with rtd-w or dft-w (e.g rtd-w999)

### Current results
Alert created: 
```
{
  "predecoder": {
    "hostname": "rtd-w999",
    "program_name": "kernel",
    "timestamp": "Feb 20 11:15:00"
  },
  "agent": {
    "ip": "10.255.1.4",
    "name": "RTD-W999",
    "id": "021"
  },
  "manager": {
    "name": "DFT-WAZUH"
  },
  "rule": {
    "mail": true,
    "level": 8,
    "pci_dss": [
      "10.6.1",
      "11.4"
    ],
    "hipaa": [
      "164.312.b"
    ],
    "tsc": [
      "CC7.2",
      "CC7.3",
      "CC6.1",
      "CC6.8"
    ],
    "description": "Interface entered in promiscuous(sniffing) mode.",
    "groups": [
      "syslog",
      "linuxkernel",
      "promisc"
    ],
    "nist_800_53": [
      "AU.6",
      "SI.4"
    ],
    "gdpr": [
      "IV_35.7.d"
    ],
    "firedtimes": 4,
    "mitre": {
      "technique": [
        "Network Sniffing"
      ],
      "id": [
        "T1040"
      ],
      "tactic": [
        "Credential Access",
        "Discovery"
      ]
    },
    "id": "5104",
    "gpg13": [
      "4.13"
    ]
  },
  "decoder": {
    "name": "kernel"
  },
  "full_log": "Feb 20 11:15:00 rtd-w999 kernel: [72024.121482] device veth41e4a1f5 entered promiscuous mode",
  "input": {
    "type": "log"
  },
  "@timestamp": "2024-02-20T10:15:01.796Z",
  "location": "/var/log/kern.log",
  "id": "1708424101.999999",
  "timestamp": "2024-02-20T11:15:01.796+0100",
  "_id": "xxx"
}
```

### Expected results
Alert should not be raised for rule 5104. 

### Log source / integration
K3S Worker node with wazuh-agent installed. 

### Log examples
`Feb 20 11:15:00 rtd-w999 kernel: [72024.121482] device veth41e4a1f5 entered promiscuous mode`

Produces this output via ruletest: 

```
**Messages:
	INFO: (7202): Session initialized with token '209d9557'

**Phase 1: Completed pre-decoding.
	full event: 'Feb 20 11:15:00 rtd-w999 kernel: [72024.121482] device veth41e4a1f5 entered promiscuous mode'
	timestamp: 'Feb 20 11:15:00'
	hostname: 'rtd-w999'
	program_name: 'kernel'

**Phase 2: Completed decoding.
	name: 'kernel'

**Phase 3: Completed filtering (rules).
	id: '100004'
	level: '0'
	description: 'ignore network sniffing alerts on k3s workers'
	groups: '["local","syslog","sshd"]'
	firedtimes: '1'
	mail: 'false'
```

**Comment by vikman90** [comment]
@mikeh89 Mike, this is because the "hostname" field is interpreted differently in agents:

- If the log comes from the **manager**, the "hostname" field corresponds to the text extracted by the pre-decoder: "rtd-w999".
- If the log comes from an **agent**, the "hostname" field corresponds to the agent's name.

This behavior allows the `<hostname>` option of the rule to search in the agent's name, but unfortunately, that case conflicts with yours.

In fact, we see that when the output JSON is generated, the "agent.name" field is inserted using the internal "hostname" field:
https://github.com/wazuh/wazuh/blob/dfaec6682f25df913191d1f6bf7c0d5df92cbb55/src/analysisd/format/json_extended.c#L413

This explains why, when we insert your log into the */var/log/kern.log* file, different results appear:

<details><summary>✅ Event coming from the manager</summary>

```json
{
  "timestamp": "2024-02-22T17:45:20.414+0100",
  "rule": {
    "level": 8,
    "description": "ignore network sniffing alerts on k3s workers",
    "id": "100004",
    "firedtimes": 4,
    "mail": false,
    "groups": [
      "local",
      "syslog",
      "sshd"
    ]
  },
  "agent": {
    "id": "000",
    "name": "Rocket"
  },
  "manager": {
    "name": "Rocket"
  },
  "id": "1708620320.179577",
  "full_log": "Feb 20 11:15:00 rtd-w999 kernel: [72024.121482] device veth41e4a1f5 entered promiscuous mode",
  "predecoder": {
    "program_name": "kernel",
    "timestamp": "Feb 20 11:15:00",
    "hostname": "rtd-w999"
  },
  "decoder": {
    "name": "kernel"
  },
  "location": "/var/log/kern.log"
}
```

</details>

<details><summary>❌ Event coming from an agent</summary>

```json
{
  "timestamp": "2024-02-22T17:44:58.950+0100",
  "rule": {
    "level": 8,
    "description": "Interface entered in promiscuous(sniffing) mode.",
    "id": "5104",
    "mitre": {
      "id": [
        "T1040"
      ],
      "tactic": [
        "Credential Access",
        "Discovery"
      ],
      "technique": [
        "Network Sniffing"
      ]
    },
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "syslog",
      "linuxkernel",
      "promisc"
    ],
    "pci_dss": [
      "10.6.1",
      "11.4"
    ],
    "gpg13": [
      "4.13"
    ],
    "gdpr": [
      "IV_35.7.d"
    ],
    "hipaa": [
      "164.312.b"
    ],
    "nist_800_53": [
      "AU.6",
      "SI.4"
    ],
    "tsc": [
      "CC7.2",
      "CC7.3",
      "CC6.1",
      "CC6.8"
    ]
  },
  "agent": {
    "id": "001",
    "name": "mantic",
    "ip": "10.0.2.15"
  },
  "manager": {
    "name": "Rocket"
  },
  "id": "1708620298.179153",
  "full_log": "Feb 20 11:15:00 rtd-w999 kernel: [72024.121482] device veth41e4a1f5 entered promiscuous mode",
  "predecoder": {
    "program_name": "kernel",
    "timestamp": "Feb 20 11:15:00",
    "hostname": "rtd-w999"
  },
  "decoder": {
    "name": "kernel"
  },
  "location": "/var/log/kern.log"
}
```

</details>

—I raised the rule level to 8 so it could be seen.—

This detail is one of the hidden intricacies of *wazuh-analysisd*, it is one of the reasons why we are reworking to a new engine with consistent and unified behavior, which will be released in 5.0.0:
- #11334

We apologize for any inconvenience caused.

Best regards.
