### ISSUE TITLE
Error when redirecting from the Google SSO

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#22007]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | Wazuh UI | Manager| Packages/Sources | General |

Problems are reported in the integration with Google IdP to authenticate users into the Wazuh platform.
It's not possible to access the dashboard.

![image](https://github.com/wazuh/wazuh/assets/41765669/3261164b-96e4-49ea-875b-8baf4a0dee46)

Error code

`{"statusCode":400, "error": "Bad Request", "message": "Invalid requestId"}`

![image](https://github.com/wazuh/wazuh/assets/41765669/eec57047-5263-43c2-82b8-8e4616c98c9b)

But the url of the dashboard ( a dns with the domain) works fine, they redirects to Google SSO and then to the dashboard.

Also there are some differences in the documentation section:

ACS URL description is:
- ACS URL: https://<WAZUH_DASHBOARD_URL>/_opendistro/_security/saml/acs

Picture URL:
- ACS URL: https://<WAZUH_DASHBOARD_URL>_security/saml/acs

![image](https://github.com/wazuh/wazuh/assets/41765669/3605364c-0d6c-4659-83e4-9867082b20f7)
Triying with both cases the error is bad request.

Thread [link](https://wazuh.slack.com/archives/C0A933R8E/p1707225098680849)

**Comment by jotamesteves** [comment]
Apparently it's working, but the site redirects to open search home.

**Comment by Tostti** [comment]
Noted. We will work to fix that in future versions.

**Comment by Tostti** [comment]
I'm closing this issue as the main problem has been resolved.
