### ISSUE TITLE
Correct the description in Rule 87802

### ISSUE THREAD

**Issue by adavinchi** [wazuh/wazuh#22043]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.7.2 | Rules | Improve |

## Description

The rule with ID `87802` is observed to reference a wrong field in the description. This makes the rule display with incomplete description.

### Service/Product/Module

This rule is related to using Wazuh to monitor Microsoft Entra ID as seen in the [documentation](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/entra/graph.html#:~:text=configuration%20described%20above.-,Wazuh%20Rules,-Permalink%20to%20this)

### Current results

When a Microsoft Entra ID event triggers the rule `87802`, it prints `Azure: AD` as the description which is incomplete as seen in the image below. This is because the description in the rule `<description>Azure: AD $(activity)</description>` references the wrong field `$(activity)` instead of `$(activityDisplayName)`.

<img width="445" alt="image" src="https://github.com/wazuh/wazuh/assets/120424104/5ccf9c64-5080-478b-ad8b-98925913113e">

### Expected results

The rule should display the correct description of the event on the dashboard, considering the log sample below, rather than `Azure: AD` it should display `Azure AD: Add app role assignment grant to user`

### Log source / integration

The logs are retreived from [Wazuh integration](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/entra/index.html) with Microsoft EntraID 

### Log examples

`{"id": "Directory_856062e8-b362-4974-8e4d-0", "category": "UserManagement", "correlationId": "856062e8-b362-4", "result": "success", "resultReason": "", "activityDisplayName": "Add app role assignment grant to user", "activityDateTime": "2023-11-27T20:16:25.9499334Z", "loggedByService": "Core Directory", "operationType": "Assign", "initiatedBy": {"app": null, "user": {"id": "36053d22-7e85-43", "displayName": null, "userPrincipalName": "foo@bar.com", "ipAddress": "1.2.3.4", "userType": null, "homeTenantId": null, "homeTenantName": null}}, "targetResources": [{"id": "e5821434-36ef-44", "displayName": "GraphSample", "type": "ServicePrincipal", "userPrincipalName": null, "groupType": null, "modifiedProperties": [{"displayName": "AppRole.Id", "oldValue": null, "newValue": "\"00000000-0000-0000-0000-000000000000\""}, {"displayName": "AppRole.Value", "oldValue": null, "newValue": "\"\""}, {"displayName": "AppRole.DisplayName", "oldValue": null, "newValue": "\"\""}, {"displayName": "AppRoleAssignment.CreatedDateTime", "oldValue": null, "newValue": "\"2023-11-27T20:16:25.8949279Z\""}, {"displayName": "AppRoleAssignment.LastModifiedDateTime", "oldValue": null, "newValue": "\"2023-11-27T20:16:25.8949279Z\""}, {"displayName": "User.ObjectID", "oldValue": null, "newValue": "\"36053d22-7e85-43eb-a0b6-f4ef7a814981\""}, {"displayName": "User.UPN", "oldValue": null, "newValue": "\"foo_bar.com#EXT#@foobar.onmicrosoft.com\""}, {"displayName": "User.PUID", "oldValue": null, "newValue": "\"100320\""}, {"displayName": "TargetId.ServicePrincipalNames", "oldValue": null, "newValue": "\"560c3d27-08ef-4a4b-99\""}]}, {"id": "36053d22-7", "displayName": null, "type": "User", "userPrincipalName": "foo_bar.com#EXT#@foobar.onmicrosoft.com", "groupType": null, "modifiedProperties": []}], "additionalDetails": [{"key": "User-Agent", "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"}, {"key": "AppId", "value": "560c3d27-08e"}], "azure_tag": "azure-ad-graph", "azure_aad_tag": "microsoft-entra_id"}`

**Comment by beraoudabdelkhalek** [comment]
@adavinchi Hello, can I take this?

**Comment by IsExec** [comment]
# Issue Update

### Observations from Logtest 

- Sample log in `/var/ossec/ruleset/rules/0555-azure_rules.xml` differ from the Log example in the issue.
- The sample log has `activity` field hence it triggered with the correct description as shown below:
```console
activity: 'Update user'
        .
        .
        azure_tag: 'azure-ad-graph'
        category: 'Core Directory'
        componentOrSource: 'null'
        correlationId: 'be508521-5ee8-4de5-b4fc-2013eef65210'
        domainName: 'null'
        id: 'Directory_7EPSJ_94874513'
        internalCorrelationId: 'null'
        source: 'null'
        targets: '[{'@odata.type': '#Microsoft.ActiveDirectory.DataService.PublicApi.Model.Reporting.AuditLog.TargetResourceUserEntity', 'isPrivileged': None, 'name': None, 'objectId': 'ca889c3a-47b3-4424-a7ac-f4c26f3c084c', 'userSource': None, 'userPrincipalName': 'alfonso@wazuh.onmicrosoft.com', 'modifiedProperties': [{'name': 'Included Updated Properties', 'oldValue': None, 'newValue': '""'}, {'name': 'TargetId.UserType', 'oldValue': None, 'newValue': '"Member"'}], 'puid': '10037FFEAB314424', 'targetResourceType': 'User', 'ipAddress': None, 'additionalDetails': None}]'
        tenantGeolocation: 'null'
        tenantId: '13fb6bf6-e9c2-4aeb-9957-f07dc32420e2'
        tenantName: 'null'

**Phase 3: Completed filtering (rules).
        id: '87802'
        level: '3'
        description: 'Azure: AD Update user'
        groups: '['azure']'
        firedtimes: '2'
        mail: 'False'
**Alert to be generated.
```

- The Log example doesn't have the `activity` field hence the unexpected description as shown below. It has activityDisplayName instead.

```console
 'groupType': None, 'modifiedProperties': []}]'

**Phase 3: Completed filtering (rules).
        id: '87802'
        level: '3'
        description: 'Azure: AD '
        groups: '['azure']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.`
```

## Next Step

- Setup the environment to reproduce the issue and ascertain how the logs is processed and the exact field that fits the description.

**Comment by IsExec** [comment]
# Issue Update - 11/09/2024

- Environmental setup (ongoing)

Require admin consent to allow the required application permissions 

![image](https://github.com/user-attachments/assets/3b123728-1dfa-4ee0-b3b6-5e7668b1b7f0)

**Comment by IsExec** [comment]
# Issue Update - 12/09/2024

## Dashboard
The correct field as seen from the dashboard is the `activityDisplayName`. There is no such field as `activity`. 
![microsoft graph](https://github.com/user-attachments/assets/d4a0e7eb-be2d-4740-beb3-f8e766b9f2f2)


## Microsoft Documentation
The expected field in the response to the API call from [Microsoft Documentation](https://learn.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http#response) is `activityDisplayName` as shown below:

```console
HTTP/1.1 200 OK
Content-type: application/json

{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#auditlogs/directoryaudits",
  "value": [{
        "id": "id",
        "category": "UserManagement",
        "correlationId": "da159bfb-54fa-4092-8a38-6e1fa7870e30",
        "result": "success",
        "resultReason": "Successfully added member to group",
        "activityDisplayName": "Add member to group",
        "activityDateTime": "2018-01-09T21:20:02.7215374Z",
        "loggedByService": "Core Directory",
        "initiatedBy": {
            "user": {
                "id": "728309ae-1a37-4937-9afe-e35d964db09b",
                "displayName": "Audry Oliver",
                "userPrincipalName": "bob@wingtiptoysonline.com",
                "ipAddress": "127.0.0.1"
            },
            "app": null
```

# Conclusion

The issue description is confirmed to be true.

# To do

- Change the referenced field in the description of `rule 87802` from `$(activity)` to `$(activityDisplayName)`
- Update the sample logs under `#Graph` in `/rule/0555-azure_rules.xml` to align with this change.

## Reference
https://learn.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http#response-1

**Comment by jk-olaoluwa** [comment]
> # Issue Update - 12/09/2024
> ## Dashboard
> The correct field as seen from the dashboard is the `activityDisplayName`. There is no such field as `activity`. ![microsoft graph](https://private-user-images.githubusercontent.com/121132106/367009874-d4a0e7eb-be2d-4740-beb3-f8e766b9f2f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzQ5OTgsIm5iZiI6MTcyNjY3NDY5OCwicGF0aCI6Ii8xMjExMzIxMDYvMzY3MDA5ODc0LWQ0YTBlN2ViLWJlMmQtNDc0MC1iZWIzLWY4ZTc2NmI5ZjJmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNTUxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjFmMjcwNzZlNDBhODQzMDVlYTNhZmViYzc3NTJiMmQwMWMxZTM0YjBiNmRhMWI0MDA3ODA3YmJlZjczNjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2uxmsrZZ-M53CrdoQV_Z4SpDlcx8wHczNLvtMZg8zYA)
> 
> ## Microsoft Documentation
> The expected field in the response to the API call from [Microsoft Documentation](https://learn.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http#response) is `activityDisplayName` as shown below:
> 
> ```
> HTTP/1.1 200 OK
> Content-type: application/json
> 
> {
>   "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#auditlogs/directoryaudits",
>   "value": [{
>         "id": "id",
>         "category": "UserManagement",
>         "correlationId": "da159bfb-54fa-4092-8a38-6e1fa7870e30",
>         "result": "success",
>         "resultReason": "Successfully added member to group",
>         "activityDisplayName": "Add member to group",
>         "activityDateTime": "2018-01-09T21:20:02.7215374Z",
>         "loggedByService": "Core Directory",
>         "initiatedBy": {
>             "user": {
>                 "id": "728309ae-1a37-4937-9afe-e35d964db09b",
>                 "displayName": "Audry Oliver",
>                 "userPrincipalName": "bob@wingtiptoysonline.com",
>                 "ipAddress": "127.0.0.1"
>             },
>             "app": null
> ```
> 
> # Conclusion
> The issue description is confirmed to be true.
> 
> # To do
> * Change the referenced field in the description of `rule 87802` from `$(activity)` to `$(activityDisplayName)`
> * Update the sample logs under `#Graph` in `/rule/0555-azure_rules.xml` to align with this change.
> 
> ## Reference
> https://learn.microsoft.com/en-us/graph/api/directoryaudit-list?view=graph-rest-1.0&tabs=http#response-1

To do activities have been implemented here - https://github.com/wazuh/wazuh/pull/25776

**Comment by ooniagbi** [comment]
Merged https://github.com/wazuh/wazuh/pull/25777 to 4.9.1. Closing. Issue resolved.
