### ISSUE TITLE
Add Internal Option to Disable Manager Scan in Vulnerability Detection

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#22059]
### Description

This issue involves adding an internal option (`vulnerability-detection.disable_scan_manager`) to the Vulnerability Detection module. When this option is set to 1, the module should refrain from scanning the manager (Agent 000). The default value of this option should be 0 (scan the manager).

Additionally, handling should be implemented for changes in the option's status. When transitioning from active to disabled, the module should perform a clean operation on the agent. Conversely, when transitioning from disabled to active, the module should initiate a scan of agent 000. The state of this option should be persisted using the `vd_states` table to manage configuration changes.

### Proposed Changes

1. **Add Internal Option:**
   - Introduce a new internal option named `vulnerability-detection.disable_scan_manager` in the Vulnerability Detection module's configuration.
   - Set the default value of this option to 0 (indicating that the manager should be scanned by default).

2. **Handle Option Changes:**
   - Implement logic to handle changes in the status of the `disable_scan_manager` option.
   - When the option transitions from active to disabled:
     - Perform a clean operation on the manager agent to remove any existing vulnerabilities.
   - When the option transitions from disabled to active:
     - Initiate a scan of the manager agent to identify vulnerabilities.

3. **Persist Option State:**
   - Utilize the `vd_states` rocksdb to persist the state of the `disable_scan_manager` option.
   - Update the option's state in the database to reflect any changes made to it.

### Implementation Steps

1. **Add Internal Option:**
   - Modify the configuration file of the Vulnerability Detection module to include the `disable_scan_manager` option with a default value of 0.

2. **Handle Option Changes:**
   - Implement logic within the Vulnerability Detection module to monitor changes in the status of the `disable_scan_manager` option.
   - Define actions to be taken when the option's status changes, including performing a clean operation or initiating a scan of the manager agent.

3. **Persist Option State:**
   - Implement database queries to update and retrieve the state of the `disable_scan_manager` option from the `vd_states` table.
   - Ensure that changes to the option's state are accurately reflected in the database.

### Impact

- **Flexibility:** Introducing an internal option provides flexibility in managing whether the manager agent is scanned for vulnerabilities.

### Definition of Done

- The `disable_scan_manager` option is successfully added to the internal_option configuration with a default value of 0.
- Logic is implemented to handle changes in the status of the `disable_scan_manager` option, including performing agent cleanup or initiating scans as necessary.
- The state of the `disable_scan_manager` option is accurately persisted in the `vd_states` table in the Wazuh DB.
- Testing confirms that changes to the option's status result in the expected behavior, including agent cleanup and scan initiation.

### Special considerations.
This will be undocumented.

**Comment by sebasfalcone** [comment]
Moved ETA, code delivery and testing delayed due to
- https://github.com/wazuh/wazuh/issues/22241
