### ISSUE TITLE
Auditd Decoders not working for Rocky 9.3

### ISSUE THREAD

**Issue by austinmarten1** [wazuh/wazuh#22066]
Wazuh Version 4.7.2

## Description
Wazuh is not ingesting data from Rocky Linux 9.3 in regards to Audit logging.

### Service/Product/Module
wazuh-logcollector. Auditd.

Following this guide I was able to get the logtest feature to work. however no logs still appear. 
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

### Current results
Currently i am not seeing any errors in regards to the log ingesting which makes it hard to diagnose and fix. 
Issue we are currently running into is that some Machines are not importing logs from /var/log/audit/audit.log. 

When looking at the ossec.log file with wazuh-logcollector -dddd enabled i get this:
2024/02/23 10:36:44 wazuh-logcollector[2813] read_audit.c:157 at read_audit(): DEBUG: Read 1 lines from /var/log/audit/audit.log

which does not indicate any errors. However when digging deeper i realized that I needed to modify the decoder as the check specifies ^type= which doesnt allow logs that look like such:

node=localhost type=PROCTITLE msg=audit(1708637434.880:672): proctitle="su"

While utilizing the logtest feature inside the managers and some tweaking i am no longer getting errors as shown below:

root@wa-mstr-0:/var/ossec/bin# ./wazuh-logtest
Starting wazuh-logtest v4.7.2
Type one log per line

node=localhost type=PROCTITLE msg=audit(1708637434.880:672): proctitle="su"

**Phase 1: Completed pre-decoding.
    full event: 'node=localhost type=PROCTITLE msg=audit(1708637434.880:672): proctitle="su"'

**Phase 2: Completed decoding.
    name: 'auditd'
    [audit.id](http://audit.id/): '672'
    audit.type: 'PROCTITLE'

**Phase 3: Completed filtering (rules).
    id: '80700'
    level: '0'
    description: 'Audit: Messages grouped.'
    groups: '['audit']'
    firedtimes: '1'
    mail: 'False'

### Expected results
Audit logs ingested into wazuh/opensearch.

![image](https://github.com/wazuh/wazuh/assets/90341928/840c201f-aea6-40bc-b08a-4119e2fafa3f)

### Log reference
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/logging.html

**Comment by vikman90** [comment]
Hello @austinmarten1,

Thank you for bringing the issue to our attention. We've confirmed the bug you reported regarding the recognition of logs starting with "node=". We've proposed a fix for it:

- https://github.com/wazuh/wazuh/pull/22178

We appreciate your contribution to improving our product's quality.

Best regards,
