### ISSUE TITLE
Windows agent error during Windows 2016 Agent Setup

### ISSUE THREAD

**Issue by smtszk** [wazuh/wazuh#221]
Hi,

I'm getting this error during  Windows server 2016 agent installation.

![unnamed](https://user-images.githubusercontent.com/10809726/31761953-6a506c96-b4c2-11e7-8178-6f072b0f774e.png) 

Anyone saw before?

**Comment by erseco** [comment]
Hello, the current **exe wazuh windows installer** is not well working. We generated a new **msi based** one that should solve all these problems and will not show false AV positives

You can download it from this URL: http://packages.wazuh.com/windows/wazuh-agent-2.1.1-1.msi

Please tell us if it solves your problem.

Best regards!

**Comment by smtszk** [comment]
Thank you so much for quick reply.

I will try.

**Comment by rossengeorgiev** [comment]
@erseco somewhat related question, does the MSI installer support unattended installation including setting up the key and manager ip ? If no, what would be the best way to achieve that?

**Comment by erseco** [comment]
Yes, the new msi installer support unattended installation!

Here you can get the command-line parameters reference: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-command-line

Best regards!

**Comment by rossengeorgiev** [comment]
@erseco That is awesome! Another quick question. For a domain joined machine, if I don't specify the agent_name, would it use just the computer name or FQDN?

**Comment by weisst** [comment]
@erseco hi erseco，have some package wazuh msi document, i'm mod some code and try have a msi package, if have doc ,please tell me ,thx

**Comment by erseco** [comment]
Hello, as you can read in this thread you can get the command-line parameter reference here:
https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-command-line

Best regards!
