### ISSUE TITLE
Release 4.8.0 - Beta 2 - E2E UX tests - Wazuh Indexer ISM policies

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#22116]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.8.0-beta2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/indexer team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Feb 27, 2024 and notify the @wazuh/indexer team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/indexer team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Feb 28, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Feb 29, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.8.0-beta2/quickstart.html) | - | Red Hat Enterprise Linux 8 |
| Server | Same as indexer, all-in-one | - | - |
| Dashboard | Same as indexer, all-in-one | - | - |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.8.0-beta2/installation-guide/wazuh-agent/index.html) | - | Red Hat Enterprise Linux 8 x86_64, Windows 11 x86_64 |

## Test description

Follow and read documentation links to test ISM policies in Wazuh Indexer:
- Retention policies
- Rollover + alias

https://documentation-dev.wazuh.com/v4.8.0-beta2/user-manual/wazuh-indexer/index-life-management.html
https://opensearch.org/docs/latest/im-plugin/ism/index/

## Known issues

- https://github.com/wazuh/wazuh-packages/issues/1515

## Conclusions

All tests have been executed and the results can be found here.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
|🟢 | Wazuh Indexer Quick installer | *| * |
|🟢 | Wazuh Server Quick installer | * | * |
|🟢 |Wazuh Dashboard Quick installer | *| *|
|🟢 |Wazuh Agent Installation | *| *|
|🟢 | Retention policies |  | Followed this [documentation](https://documentation-dev.wazuh.com/v4.8.0-alpha2/user-manual/wazuh-indexer/index-life-management.html#index-retention) on configuring retention policy | 
|🟢 | Rollover + alias |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - The testing guide was clear
- Did you face any challenges not covered by the guideline?
  - I have had no problems completing the testing
- Suggestions for improvement:
  - Be clearer about what is being requested. After conducting tests, during the review, they requested some preliminary checks that were not considered or performed in previous issues.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/indexer

**Comment by Zapatannicolas** [comment]
## Environment installation 🟢
### The Wazuh Indexer, Server, and Dashboard were set up using Quick Installer on RHEL 8 🟢

```
[nzapata@localhost ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

---

```
[nzapata@localhost ~]$ curl -sO https://packages-dev.wazuh.com/4.8/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
[sudo] password for nzapata: 
26/02/2024 08:02:29 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
26/02/2024 08:02:29 INFO: Verbose logging redirected to /var/log/wazuh-install.log
26/02/2024 08:02:41 INFO: Verifying that your system meets the recommended minimum hardware requirements.
26/02/2024 08:02:41 INFO: Wazuh web interface port will be 443.
26/02/2024 08:02:43 WARNING: The system has Firewalld enabled. Please ensure that traffic is allowed on these ports: 1515, 1514, 443.
26/02/2024 08:02:46 INFO: Wazuh development repository added.
26/02/2024 08:02:46 INFO: --- Configuration files ---
26/02/2024 08:02:46 INFO: Generating configuration files.
26/02/2024 08:02:46 INFO: Generating the root certificate.
26/02/2024 08:02:46 INFO: Generating Admin certificates.
26/02/2024 08:02:46 INFO: Generating Wazuh indexer certificates.
26/02/2024 08:02:46 INFO: Generating Filebeat certificates.
26/02/2024 08:02:46 INFO: Generating Wazuh dashboard certificates.
26/02/2024 08:02:46 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
26/02/2024 08:02:47 INFO: --- Wazuh indexer ---
26/02/2024 08:02:47 INFO: Starting Wazuh indexer installation.
26/02/2024 08:04:46 INFO: Wazuh indexer installation finished.
26/02/2024 08:04:46 INFO: Wazuh indexer post-install configuration finished.
26/02/2024 08:04:46 INFO: Starting service wazuh-indexer.
26/02/2024 08:05:05 INFO: wazuh-indexer service started.
26/02/2024 08:05:05 INFO: Initializing Wazuh indexer cluster security settings.
26/02/2024 08:05:16 INFO: Wazuh indexer cluster security configuration initialized.
26/02/2024 08:05:16 INFO: Wazuh indexer cluster initialized.
26/02/2024 08:05:16 INFO: --- Wazuh server ---
26/02/2024 08:05:16 INFO: Starting the Wazuh manager installation.
26/02/2024 08:06:58 INFO: Wazuh manager installation finished.
26/02/2024 08:06:59 INFO: Wazuh manager vulnerability detection configuration finished.
26/02/2024 08:06:59 INFO: Starting service wazuh-manager.
26/02/2024 08:07:07 INFO: wazuh-manager service started.
26/02/2024 08:07:07 INFO: Starting Filebeat installation.
26/02/2024 08:07:44 INFO: Filebeat installation finished.
26/02/2024 08:07:52 INFO: Filebeat post-install configuration finished.
26/02/2024 08:07:52 INFO: Starting service filebeat.
26/02/2024 08:07:54 INFO: filebeat service started.
26/02/2024 08:07:54 INFO: --- Wazuh dashboard ---
26/02/2024 08:07:54 INFO: Starting Wazuh dashboard installation.
26/02/2024 08:15:40 INFO: Wazuh dashboard installation finished.
26/02/2024 08:15:40 INFO: Wazuh dashboard post-install configuration finished.
26/02/2024 08:15:40 INFO: Starting service wazuh-dashboard.
26/02/2024 08:15:40 INFO: wazuh-dashboard service started.
26/02/2024 08:15:47 INFO: Updating the internal users.
26/02/2024 08:16:32 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
26/02/2024 08:17:29 INFO: Initializing Wazuh dashboard web application.
26/02/2024 08:17:29 INFO: Wazuh dashboard web application not yet initialized. Waiting...
26/02/2024 08:17:44 INFO: Wazuh dashboard web application not yet initialized. Waiting...
26/02/2024 08:18:02 INFO: Wazuh dashboard web application not yet initialized. Waiting...
26/02/2024 08:18:17 INFO: Wazuh dashboard web application initialized.
26/02/2024 08:18:17 INFO: --- Summary ---
26/02/2024 08:18:17 INFO: You can access the web interface https://<wazuh-dashboard-ip>:443
    User: admin
    Password: XXXXXXXXXXXXXXXXXXXXXXX
26/02/2024 08:18:17 INFO: Installation finished.
```

**All components were running fine.**

```
[nzapata@localhost ~]$ service wazuh-manager status
Redirecting to /bin/systemctl status wazuh-manager.service
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2024-02-26 08:17:12 -03; 12min ago
    Tasks: 190 (limit: 47588)
   Memory: 2.5G
   CGroup: /system.slice/wazuh-manager.service
           ├─19459 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19460 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19463 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19466 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─19508 /var/ossec/bin/wazuh-authd
           ├─19518 /var/ossec/bin/wazuh-db
           ├─19548 /var/ossec/bin/wazuh-execd
           ├─19560 /var/ossec/bin/wazuh-analysisd
           ├─19570 /var/ossec/bin/wazuh-syscheckd
           ├─19584 /var/ossec/bin/wazuh-remoted
           ├─19687 /var/ossec/bin/wazuh-logcollector
           ├─19711 /var/ossec/bin/wazuh-monitord
           └─19721 /var/ossec/bin/wazuh-modulesd

feb 26 08:17:07 localhost.localdomain env[19392]: Started wazuh-analysisd...
feb 26 08:17:07 localhost.localdomain env[19392]: Started wazuh-syscheckd...
feb 26 08:17:08 localhost.localdomain env[19392]: Started wazuh-remoted...
feb 26 08:17:09 localhost.localdomain env[19392]: Started wazuh-logcollector...
feb 26 08:17:09 localhost.localdomain env[19392]: Started wazuh-monitord...
feb 26 08:17:09 localhost.localdomain env[19719]: 2024/02/26 08:17:09 wazuh-modulesd:router: INFO: Loaded rou>
feb 26 08:17:09 localhost.localdomain env[19719]: 2024/02/26 08:17:09 wazuh-modulesd:content_manager: INFO: L>
feb 26 08:17:10 localhost.localdomain env[19392]: Started wazuh-modulesd...
feb 26 08:17:12 localhost.localdomain env[19392]: Completed.
feb 26 08:17:12 localhost.localdomain systemd[1]: Started Wazuh manager.
```
```
[nzapata@localhost ~]$ service wazuh-indexer status
Redirecting to /bin/systemctl status wazuh-indexer.service
● wazuh-indexer.service - Wazuh-indexer
   Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2024-02-26 08:05:05 -03; 24min ago
     Docs: https://documentation.wazuh.com/
 Main PID: 10002 (java)
    Tasks: 105 (limit: 47588)
   Memory: 1.8G
   CGroup: /system.slice/wazuh-indexer.service
           └─10002 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=6>

feb 26 08:04:47 localhost.localdomain systemd[1]: Starting Wazuh-indexer...
feb 26 08:04:49 localhost.localdomain systemd-entrypoint[10002]: WARNING: A terminally deprecated method in j>
feb 26 08:04:49 localhost.localdomain systemd-entrypoint[10002]: WARNING: System::setSecurityManager has been>
feb 26 08:04:49 localhost.localdomain systemd-entrypoint[10002]: WARNING: Please consider reporting this to t>
feb 26 08:04:49 localhost.localdomain systemd-entrypoint[10002]: WARNING: System::setSecurityManager will be >
feb 26 08:04:52 localhost.localdomain systemd-entrypoint[10002]: WARNING: A terminally deprecated method in j>
feb 26 08:04:52 localhost.localdomain systemd-entrypoint[10002]: WARNING: System::setSecurityManager has been>
feb 26 08:04:52 localhost.localdomain systemd-entrypoint[10002]: WARNING: Please consider reporting this to t>
feb 26 08:04:52 localhost.localdomain systemd-entrypoint[10002]: WARNING: System::setSecurityManager will be >
feb 26 08:05:05 localhost.localdomain systemd[1]: Started Wazuh-indexer.
```

```
[nzapata@localhost ~]$ service wazuh-dashboard status
Redirecting to /bin/systemctl status wazuh-dashboard.service
● wazuh-dashboard.service - wazuh-dashboard
   Loaded: loaded (/etc/systemd/system/wazuh-dashboard.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2024-02-26 08:17:13 -03; 12min ago
 Main PID: 19986 (node)
    Tasks: 11 (limit: 47588)
   Memory: 178.7M
   CGroup: /system.slice/wazuh-dashboard.service
           └─19986 /usr/share/wazuh-dashboard/node/bin/node --no-warnings --max-http-header-size=65536 --unha>

feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain opensearch-dashboards[19986]: {"type":"response","@timestamp":"2024-02->
feb 26 08:24:29 localhost.localdomain ope
```

**Comment by damarisg** [comment]
LGTM!
