### ISSUE TITLE
Release 4.8.0 - Beta 2 - Integration tests

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#22125]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/22069 |
| **Version**                      | 4.8.0                                                   |
| **Release stage**            | Beta  2                                                     
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta2          |
| **Wazuh QA: Branch**    | `v4.8.0-beta2`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.0-beta2     |
| **Wazuh: Branch**    | `v4.8.0-beta2` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build evidence:*** https://ci.wazuh.info/job/Test_integration_launcher/248/
   - Relaunched tests in:
      - Syscollector: https://ci.wazuh.info/job/Test_integration/46441/
      - Logcollector: https://ci.wazuh.info/job/Test_integration/46442/ - https://ci.wazuh.info/job/Test_integration/46444/
      - FIM: https://ci.wazuh.info/job/Test_integration/46442/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :black_circle: | The **pipeline** has been executed successfully |
> | :black_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406937/manager_html_report_Test_integration_B46413_20240226124758.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14407565/agent_centos_html_report_Test_integration_B46440_20240226170417.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14407566/agent_windows_html_report_Test_integration_B46440_20240226170417.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405454/agent_centos_html_report_Test_integration_B46415_20240226125202.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405453/agent_windows_html_report_Test_integration_B46415_20240226125202.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>analysisd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405415/manager_html_report_Test_integration_B46416_20240226125342.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>api</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/14405613/manager_html_report_Test_integration_B46417_20240226125357.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405442/manager_html_report_Test_integration_B46418_20240226125145.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406720/agent_centos_html_report_Test_integration_B46419_20240226125128.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406721/agent_windows_html_report_Test_integration_B46419_20240226125128.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405599/manager_html_report_Test_integration_B46420_20240226125325.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46108/agent_centos_html_report_Test_integration_B46108.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46108/agent_windows_html_report_Test_integration_B46108.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/issues/22125#issuecomment-1964543427">Could not run test</a></td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/14408996/agent_solaris_html_report_Test_integration_B46443_20240226171119.zip">Evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406728/manager_html_report_Test_integration_B46423_20240226125053.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406930/manager_html_report_Test_integration_B46424_20240226125252.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406854/agent_centos_html_report_Test_integration_B46425_20240226125036.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405543/manager_html_report_Test_integration_B46426_20240226125021.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14408004/agent_centos_html_report_Test_integration_B46442_20240226170940.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/14409148/agent_windows_html_report_Test_integration_B46444_20240226172538.zip">Evidence</a></td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/issues/22125#issuecomment-1964543427">Could not run tests</a></td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14409149/agent_solaris_html_report_Test_integration_B46444_20240226172538.zip">Evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406991/manager_html_report_Test_integration_B46428_20240226124949.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14407002/manager_html_report_Test_integration_B46429_20240226124916.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406913/agent_centos_html_report_Test_integration_B46430_20240226124932.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14405591/manager_html_report_Test_integration_B46431_20240226125234.zip)">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406843/manager_html_report_Test_integration_B46432_20240226124901.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rootcheck</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406740/manager_html_report_Test_integration_B46433_20240226124845.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14407290/manager_html_report_Test_integration_B46434_20240226124829.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14406984/manager_html_report_Test_integration_B46435_20240226125218.zip">Evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://github.com/wazuh/wazuh/files/14408016/agent_centos_html_report_Test_integration_B46441_20240226170729.zip">Evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/files/14408017/agent_windows_html_report_Test_integration_B46441_20240226170729.zip">Evidence</a></td>
        <td>:red_circle: <a href="https://github.com/wazuh/wazuh/issues/22125#issuecomment-1964543427">Could not run test </a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

## Conclusion  :red_circle: 

- API tests failed due to not being mantained in `wazuh-qa` https://github.com/wazuh/wazuh/issues/22125#issuecomment-1964579653
- New reported Issues:
   - https://github.com/wazuh/wazuh-qa/issues/5033
   - https://github.com/wazuh/wazuh-qa/issues/5034
   - https://github.com/wazuh/wazuh-qa/issues/5035
- macOS Endpoint did not run due to known error https://github.com/wazuh/wazuh-jenkins/issues/5539

**Comment by Deblintrake09** [comment]
## Update

- macOS tests fail to be executed, due to errors in macMini
   -  https://ci.wazuh.info/job/Test_integration/46439
   - https://ci.wazuh.info/job/Test_integration/46438
   - https://ci.wazuh.info/job/Test_integration/46437
- Relaunched tests witout macOS

**Comment by damarisg** [comment]
LGTM!
