### ISSUE TITLE
Vulnerability scanner re-scan on reboot not working due to unexpected message

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#22137]
# Description 

It was found during the implementation of UTs that the vulnerability detector module was not able to start the scanner due to an unexpected message 

`2024/02/26 11:04:47 wazuh-modulesd:vulnerability-scanner: WARNING: Failed to scan package: '', CVE Numbering Authorities (CNA): 'nvd', Error: 'Invalid package/cna name.'`

With a dummy log we can see the "NOT_SYNCED" response message. 
![image](https://github.com/wazuh/wazuh/assets/13010397/29b43288-24fe-438b-8a02-c9a5d3027df8)

We need to evaluate the possible responses from `wdb_parse_packages`

## DoD

- [x] Analyze and evaluate the possibilities to fix this behavior. 
- [x] Enable the failing test in queryAllPackages_test.cpp
- [x] Revise all responses from Wazuh-DB as part of this implementation https://github.com/wazuh/wazuh/pull/21446

**Comment by Dwordcito** [comment]
The fix of the last log is part of https://github.com/wazuh/wazuh/pull/22068

**Comment by MiguelazoDS** [comment]
Hi @Dwordcito, the issue was created for this log 

`2024/02/26 11:04:47 wazuh-modulesd:vulnerability-scanner: WARNING: Failed to scan package: '', CVE Numbering Authorities (CNA): 'nvd', Error: 'Invalid package/cna name.'` 

I'll clarify in the issue.

**Comment by Dwordcito** [comment]
Fixed by:
https://github.com/wazuh/wazuh/pull/22482

**Comment by sebasfalcone** [comment]
Re-open the issue in order to link it with the corresponding PR
