### ISSUE TITLE
Increase in Disk_Read, FD, PSS, RSS_MAXMIN, RSS, USS by All Values

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22133]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.7.3-rc1 | Wazuh Manager | Manager | Packages | CentOS Manager |

### Description

During [Release 4.7.3 - RC 1 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22128) it has been detected an increase of Al Values in Disk_Read, FD, PSS, RSS_MAXMIN, RSS, USS in the manager.

#### Disk_Read

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/88fa282c-2c62-4c01-af86-c76582dbe06e)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/2e1dac4c-011a-4405-bb4f-41da91fa4226)

#### FD

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/7481eec9-1a57-4637-aa69-533e762bb1d3)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/69b67ee5-6fed-4a07-844a-2975396049e8)

### PSS

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/ff938d2f-f57e-4145-89ec-1a2f2ae6c8af)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/1a273957-52d1-4b6e-a4a4-5448b3c45705)

### RSS_MAXMIN

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/10b2b745-f19a-4105-89d1-dde14e181f75)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/5e8f5d42-76d0-4b2d-8364-d6ca3de440b3)

### RSS

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/393aa25b-4b75-482e-8fba-036537dfb88e)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/8ddb17fa-edc3-4cd1-88b4-92d8a2622606)

### USS

- [4.7.3 - RC 1](https://github.com/wazuh/wazuh/issues/22098)

![image](https://github.com/wazuh/wazuh/assets/54536265/5ce3b297-8531-4ee4-89c9-b65eac19284c)

- [4.7.2 - RC 2](https://github.com/wazuh/wazuh/issues/21277)

![image](https://github.com/wazuh/wazuh/assets/54536265/0d8a726a-c6a4-484a-84d5-52c99670156b)

**Comment by cborla** [comment]
Related issue https://github.com/wazuh/wazuh/issues/22130
It is the same test for both issues and the problem is caused by the same cause, the lack of file descriptors closure.
