### ISSUE TITLE
Modulesd osquery results file not available in Demo Environment for 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22145]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | modulesd  | Agent | Demo Environment | RHEL9/Windows Server 2019 |

## Description

During the testing [Release 4.8.0 - Beta 2 - E2E UX tests - Demo environment](https://github.com/wazuh/wazuh/issues/22111) several warnings were found related to osquery, the warnings mentions missing results and configuration file
- Windows logs
    ```shellsession
      2024/02/26 12:08:30 wazuh-modulesd:osquery: WARNING: The configuration file 'C:\Program Files\osquery\osquery.conf' is
      not accessible: No such file or directory (2)
      2024/02/26 12:08:30 wazuh-modulesd:osquery: WARNING: Results file 'C:\Program Files\osquery\log\osqueryd.results.log'
      not available: No such process (3). Retrying in 1 sec.
      2024/02/26 12:08:31 wazuh-modulesd:osquery: WARNING: Results file 'C:\Program Files\osquery\log\osqueryd.results.log'
      not available: No such process (3). Retrying in 2 sec.
    ```
- RHEL9 logs
    ```shellsession
    2024/02/26 12:08:15 wazuh-modulesd:osquery: WARNING: Results file '/var/log/osquery/osqueryd.results.log' not available: No such file or directory (2). Retrying in 1 sec.
    ```

**Comment by davidjiglesias** [comment]
Due to known failures in modulesd during v4.8.0 we (with @Dwordcito) have decided to close this as not planned to be tested again in future stages.
