### ISSUE TITLE
Vulnerability scanner unexpected error processing message

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22147]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Vulnerability Detection | Manager | Packages | Ubuntu 22 |

### Description

It has been detected the following errors during the test

```
2024/02/26 15:56:47 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing message: Error getting CVEv5 Entry object from rocksdb. FlatBuffers verifier failed
...
2024/02/26 16:15:25 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing message: Unable to parse payload: 1: 2700: error: unknown field: source
```

### Steps to reproduce
- Deploy an AIO in an Ubuntu jammy host
- Wait until provided errors appears

### Evidences

- [ossec.log.zip](https://github.com/wazuh/wazuh/files/14409479/ossec.zip)

> [!NOTE]
> Debug mode was not enabled during the occurrence of these errors. We are currently attempting to replicate this issue with the debug option enabled for further investigation.

**Comment by Dwordcito** [comment]
Duplicated of https://github.com/wazuh/intelligence-data/issues/57
