### ISSUE TITLE
Dynamically load the `oscpe` rules

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#22140]
## Description
Currently, the logic to generate the operating systems CPEs:
https://github.com/wazuh/wazuh/blob/1caccf151ec952a1c1b2b77209a54f5dcdc9e967/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp#L153-L162

Is dependent on a hardcoded map:
https://github.com/wazuh/wazuh/blob/1caccf151ec952a1c1b2b77209a54f5dcdc9e967/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp#L62-L88

This map should be obtained from the generated content, based on the [intelligence-data](https://github.com/wazuh/intelligence-data/tree/main/base-rules#oscpe-global) repository. 

The `eventDecoder` class should be able to handle this new resource type, named `OSCPE-GLOBAL`:
https://github.com/wazuh/wazuh/blob/84ddc9e7b9050d5319eb6bd489bdd6d70e031228/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/eventDecoder.hpp#L49-L68

## DoD
- [x] The oscpe rules are obtained from the generated content
- [x] The cpe name is built from this new dynamic information
- [x] Unit testing

**Comment by Dwordcito** [comment]
Don't use flatbuffers for this development, use the jsons.
