### ISSUE TITLE
After running change password script at the end of the install process, you get "Wazuh dashboard server is not ready yet" when trying to login to the dashboard

### ISSUE THREAD

**Issue by khuhges** [wazuh/wazuh#22156]
|Wazuh version v4.7.2|Component|Install type|Install Detailed online procecures|Platform|Ubuntu 22.04
|---|---|---|---|---|
|40711-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by davidcr01** [comment]
Hello.

Sometimes, this is a problem related to the cache of the browser. Could you please try to perform any of the following steps:
- Enter the Wazuh interface from another browser.
- Enter the Wazuh interface from an incognito window.
- Clean the browser cache and try to enter the Wazuh interface.

If this does not work, please share with us the output of the following outputs:

`curl -u admin:<password> -XGET https://<INDEXER_IP>:9200/_cat/indices?v -k`.
Please, replace the password with the one reported when you changed the password, and also replace the `INDEXER_IP` with the IP address where the Wazuh indexer is installed.

Also, share with us the output of the following command:

`systemctl status wazuh-dashboard -l`
