### ISSUE TITLE
Syscollector On Windows 10 Systems - Not Scanning On Start When System Reboots

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#2217]
**OS**
Windows 10 Agents
Debian Manager

**Wazuh version**
Windows Agents 3.7.2 & 3.7.1
Manager 3.7.2

**Wazuh API version**
3.7.2

**Install method**
MSI Package on Agents
DEB Package on Manager

**Log sample**
```
    <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>16h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>
```

Bug description
----------------
When the Windows 10 agent systems restart, Wazuh runs Syscheck & Rootcheck on startup, however it's not running the Syscollector wodle on startup.

The ossec.conf file on these agents only contain the server information, and everything is configured on the agent.conf central configuration file. The agent.conf wodle configuration was provided above.

EDIT** The syscollector does scan on start when first registering, but not when restarting the system.

**Comment by TJOSERAFAEL** [comment]
Hi @Justangatang ,

thank you for reporting this bug. We will take a look at it and tell you when its fixed.

Best regards.

**Comment by Justangatang** [comment]
@TJOSERAFAEL Thank You!

I'm also wondering if there's a way to set different intervals for different syscollector lookups. I'd like to get the packages and processes less frequent than the other lookups.

**Comment by vikman90** [comment]
Hi,

That's a good point. Let me relate this issue to #2203: we propose to lookup inventory data frequently but report incremental data: send only new/removed packages, or new/killed processes to the manager.

Thank you for your feedback.
Best regards.

**Comment by vikman90** [comment]
@Justangatang I've tested this issue again with the latest version (3.12.3) and that seems to work now:

First start:
```
2020/05/11 11:09:41 ossec-agent: INFO: Started (pid: 2732).
2020/05/11 11:09:42 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2020/05/11 11:09:44 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

After restarting the agent:
```
2020/05/11 11:10:15 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2020/05/11 11:10:17 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

On the other hand, we are working on a feature that makes the agent synchronize the inventory data with the manager, instead of reporting every scan again and again (https://github.com/wazuh/wazuh/issues/3940).

Hope this helps. Let me close this issue. Should it persist in your environment, don't hesitate to reopen that.

Best regards.
