### ISSUE TITLE
Fix defects at shared_modules found by Coverity

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#22184]
|Wazuh version|Component|Install type|Source|
|---|---|---|--|
| 4.8.0 | shared_modules | Manager | https://github.com/wazuh/wazuh/issues/22138 |

The following new defects have been reported by Coverity:

|Status|CID|Type|Impact|Date|Component|Origin|Notes|
|:-:|---|---|---|---|---|---|---|
|🔴|1583807|Data race condition|Medium|Feb 26, 2024|shared_modules/utils|4.8.0 Beta 2| |
|🔴|1583803|COPY_INSTEAD_OF_MOVE|Low|Feb 26, 2024|shared_modules/content_manager|4.8.0 Beta 2| |
|🔴|1583802|Uninitialized scalar variable|High|Feb 26, 2024|shared_modules/content_manager|4.8.0 Beta 2| |
|🔴|1583725 |Data race condition|Medium|Feb 22, 2024|Wazuh Database|4.8.0 Beta 2| |

It would be necessary to fix them at least for the next stage.

**Comment by sebasfalcone** [comment]
CID 1583802 was a false positive, [see comment](https://scan9.scan.coverity.com/reports.htm#v57701/p12779/fileInstanceId=129974214&defectInstanceId=9804843&mergedDefectId=351089)

**Comment by sebasfalcone** [comment]
@Dwordcito 
I think that 1583725 and 1583807 should be fixed in another PR

They are not related to the VD modules and the changes require more testing than should be done with time and care

**Comment by sebasfalcone** [comment]
CID 1583807 will be fixed on https://github.com/wazuh/wazuh/pull/22360
