### ISSUE TITLE
Changes in usage Disk, Disk_Read, Disk_Written, Read_Ops, Write_Ops on 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22189]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the analysis [Release 4.8.0 - Beta 2 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/22164) we detected differences in the disk usage compared to [4.7.2](https://github.com/wazuh/wazuh/issues/21280)

- Disk _(decrease `modulesd` initial spyke)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/e752146a-9c31-4b7a-ae2c-93a38a95e979) |![image](https://github.com/wazuh/wazuh/assets/44633633/27bf2d8f-0446-4e85-90a0-def1e2cf2655) |

- Disk_Written _(minor decrease in `modulesd`)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/b17eeb18-e41e-4989-8cfb-ddcfd4c42bba) | ![image](https://github.com/wazuh/wazuh/assets/44633633/e24a2e9b-c255-45f9-b4b7-85556d5ca4df) |

- Disk_Read (increase in `wazuhdb`, `modulesd`, `syscheckd`)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/767ae919-0b22-4f25-a75f-bd02bee2874f) | ![image](https://github.com/wazuh/wazuh/assets/44633633/0f0256be-d1d3-4fd0-8e8c-14f9a202bd61) |

- Write_Ops (increase in modulesd, wazuhdb, syscheckd)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/c1c461fd-e727-4b2f-ba26-666d8c8db879) | ![image](https://github.com/wazuh/wazuh/assets/44633633/20289bd1-a2c7-40ea-bdf7-53d8aa4e3791) |

- Read_Ops: (decrease in `modulesd`)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/d2e2a9ee-bf31-4ee6-81cc-79bdcf83a566) | ![image](https://github.com/wazuh/wazuh/assets/44633633/683ca4a1-a419-4207-a62b-8269a7aae723) |

**Comment by QU3B1M** [comment]
The same happens for the agents


- Disk _(decrease `modulesd` initial spyke)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/21e0fb8f-1dac-405f-98a9-9fd2185d4609)|![image](https://github.com/wazuh/wazuh/assets/44633633/95dc98f2-87a7-4aba-85ad-e600f30c317a) |

- Disk_Written _(minor decrease in `modulesd` at the first half of the execution)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/1fd74cb3-6857-4f93-9feb-7a19d11149fe)|![image](https://github.com/wazuh/wazuh/assets/44633633/0de2c06f-aa36-49c7-80d3-a94585022480)|

- Disk_Read (increase in `syscheckd`)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/310f91b5-7351-4e6e-b0ad-55505a20a9c9) |![image](https://github.com/wazuh/wazuh/assets/44633633/034c21e7-0c08-4da1-863b-3d82d141748f) |

- Write_Ops _(Decrease in agentd)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/640d6523-ae62-40f7-80bf-dcf7e2695f2f) | ![image](https://github.com/wazuh/wazuh/assets/44633633/87c1a121-628b-4faa-beef-00c6f4406d71) |

- Read_Ops: (decrease in `modulesd`)
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/56001c9a-08dc-4fb1-aba2-9d0bd733270c) | ![image](https://github.com/wazuh/wazuh/assets/44633633/386f305e-60bc-482e-93a6-498c58151b4e) |

**Comment by cborla** [comment]
### Disk _(decrease `modulesd` initial spyke)_
  | | |
  |---|---|
  | 4.8.0-beta2 | ![image](https://github.com/wazuh/wazuh/assets/44633633/e752146a-9c31-4b7a-ae2c-93a38a95e979) |
  | 4.7.2-RC2 | ![image](https://github.com/wazuh/wazuh/assets/44633633/27bf2d8f-0446-4e85-90a0-def1e2cf2655) |
  | 4.7.1-RC2 | ![image](![image](https://camo.githubusercontent.com/a7c5d5fd113db1d72889acd76bc7de42834ca6d825fd44c70d0c40b36c7699a4/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343730372d333630306d2f42343730375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343730375f6d616e616765722d7072652d72656c656173655f4469736b2e706e67) |
  
  The disk usage graph can be disregarded, the 80% peak would not be an expected case, on the contrary, it may be an eventuality at the beginning of 4.7.2, if we compare with 4.7.1, we see values similar to 4.8.0.

**Comment by cborla** [comment]
### Disk_Written _(minor decrease in `modulesd`)_
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/b17eeb18-e41e-4989-8cfb-ddcfd4c42bba) | ![image](https://github.com/wazuh/wazuh/assets/44633633/e24a2e9b-c255-45f9-b4b7-85556d5ca4df) |
  
 The disk write rate is considerably lower, around 30%.

| Version | Module | Disk Written (B)| Percentaje|
|---|---|---|---|
| 4.7.2 |wazuh-modulesd| 337695084544 | 🔽 32%  less|
| 4.8.0 |wazuh-modulesd| 445985583104 | |

**Comment by cborla** [comment]
## Test observation
  The test description does not include vulnerability detector, if this is a description error it does not affect, but if the test does not really include vulnerability detector stress, then we can consider that the resource usage comparisons are not appropriate.
  | Version | Test description |
  |---|---|
  | 4.8.0-beta2 | ![image](https://github.com/wazuh/wazuh/assets/41765669/74d9df51-8585-47a1-a5ca-a47a3863b8c6) |
  | 4.7.2-RC2 | ![image](https://github.com/wazuh/wazuh/assets/41765669/884d27fc-926f-4a2c-866d-6635a5627d9c)|
