### ISSUE TITLE
Decrease modulesd fluctuations in RSS, RSS_MAXMIN, PSS, USS on 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22190]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the analysis [Release 4.8.0 - Beta 2 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/22164) we detected decrease in the `modulesd` fluctuation compared to [4.7.2](https://github.com/wazuh/wazuh/issues/21280)

- RSS
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/86f984ad-c3ea-4c08-b816-d4d53b2b2851) | ![image](https://github.com/wazuh/wazuh/assets/44633633/6fda094e-e230-461b-a08b-8b6688ff8f03) |

- RSS_MAXMIN
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/9000c1e9-03ee-4789-bdb5-62926c405ebc) | ![image](https://github.com/wazuh/wazuh/assets/44633633/3e590ee2-978f-4817-9ae4-a5136986e838) |

- PSS
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/98698ffb-dc30-4b2c-800a-5393d5c1241f) | ![image](https://github.com/wazuh/wazuh/assets/44633633/b7c25fc5-2924-469c-b18b-9fd21c3f7b60)|

- USS
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/38e7135b-5fa4-4662-87d3-9316592270d2) | ![image](https://github.com/wazuh/wazuh/assets/44633633/0a6eed72-0e6e-42be-89a1-832bdf1cc137) |

**Comment by QU3B1M** [comment]
The same happens for the agents

- PSS
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  | ![image](https://github.com/wazuh/wazuh/assets/44633633/510ed91e-7d72-43d2-836e-f8645d6ca908) | ![image](https://github.com/wazuh/wazuh/assets/44633633/7ff66f47-eb76-467a-a562-b6454d69da33)|

- USS
  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/d45efb6a-9956-4fe8-a0b4-c5b71077c4e7)|![image](https://github.com/wazuh/wazuh/assets/44633633/97ca8e0f-419d-4ec3-a70c-cc1ec54cf39b) |

**Comment by LucioDonda** [comment]
This behaviour is directly related to the same case name in [this comment](https://github.com/wazuh/wazuh/issues/22191#issuecomment-1976596045). The client queue_size and events_per_second where changed.

Agents remains with a similar behavior but for sending less events the manager lowers its memories plots:
Windows:
Metric | 4.7.2 | 4.8.0
--- | --- | ---
Number Of Messages | ![AgentdNumberOfMessages](https://github.com/wazuh/wazuh/assets/95248059/82159b3d-08fb-4fad-b323-a7eff4f7cd56) | ![NumberOfMessages](https://github.com/wazuh/wazuh/assets/95248059/68eaa270-1462-447c-8845-3528a7eae31f)
RSS Max Min | ![RssMaxMin](https://github.com/wazuh/wazuh/assets/95248059/e2f7381c-8c27-4227-b3d1-3ba6d1906d52) | ![RssMaxMin](https://github.com/wazuh/wazuh/assets/95248059/12df5739-3a72-4072-b016-2eef32440b36)
RSS | ![Rss](https://github.com/wazuh/wazuh/assets/95248059/70437899-c414-459d-8d71-dd2e00517036) | ![Rss](https://github.com/wazuh/wazuh/assets/95248059/a9947d75-80dc-40b5-be3c-a731b1218e00)
USS | ![Uss](https://github.com/wazuh/wazuh/assets/95248059/84747288-14f6-47e8-a290-0e920e1cc246) | ![Uss](https://github.com/wazuh/wazuh/assets/95248059/785f9e91-b164-4899-8d01-fb4b1828f058)

Analysisd plot goes from 200K t 150K 
4.8.0 B2
![RssMaxMinManager](https://github.com/wazuh/wazuh/assets/95248059/2a18017b-9995-4ba9-aade-68ba7b606f42)

4.7.2 
![RssMaxMinManager](https://github.com/wazuh/wazuh/assets/95248059/bf128a4e-11e6-405a-9933-e691df51d817)

c.c. @cborla @vikman90

**Comment by cborla** [comment]
In addition to the evidences exposed in the previous comment, we should dismiss the issue according to the following [comment](https://github.com/wazuh/wazuh/issues/22145#issuecomment-1979059452), modulesd has some known bug in 4.8.0.
