### ISSUE TITLE
Add support for rate-limited API

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#22201]
## Description

We want to support rate-limited APIs when downloading vulnerabilities content to be used by the vulnerability scanner.

The current behavior could lead to content starvation, because if the download process is blocked, the downloader will abort, and try again later from the beginning.

We want to avoid this situation, enabling support for this case. 

We must consider the following parameters:

- HTTP status code when blocked: 429 - too many requests
- Blocked time: B seconds
- Retry time: B + O seconds

The blocked time B and the offset seconds O can change depending on the network conditions and configurations. We can set a starting point of B = 60s and O = 30s.

**Comment by tsarquis88** [comment]
# Update

Possible solution implemented on #22228.
More tests are needed to be RTR.
