### ISSUE TITLE
Increase Queues_state fluctuations on footprint metrics for 4.8.0 Beta 2  

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22207]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the analysis [Release 4.8.0 - Beta 2 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22165) we detected an increased amount of spikes (or fluctuations) by the `DBSync` queue on Queue_State graph compared to [4.7.2](https://github.com/wazuh/wazuh/issues/21277)

  | 4.8.0-beta2 | 4.7.2-RC2 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/0f4ad9ed-3483-49e6-bfb1-1b90f231a741) |![image](https://github.com/wazuh/wazuh/assets/44633633/cb4b2bff-a2fd-459e-8bb4-06d79e2a4e94)|

**Comment by LucioDonda** [comment]
This behaviour commes from a previous version. 
[4.8.0 Beta 1](https://camo.githubusercontent.com/8633ecc6ea048ffd64edef8301f840bbe38411a0d4b43544d3df4ce32d3f9a2d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343832372d333630306d2f42343832375f6d616e616765725f63656e746f732f706c6f74732f546573745f7374726573735f42343832375f6d616e616765725f616e616c79736973645f73746174655f5175657565735f73746174652e706e67)

![image](https://github.com/wazuh/wazuh/assets/95248059/ffad4e02-3c13-41df-808b-52ec80822256)

In the present version this shows that the qtty of events can reach 5% of the WdbSync Queue SIze. From the code:
`queue_status.dbsync_queue_usage = ((dispatch_dbsync_input->elements / (float)dispatch_dbsync_input->size));`
Will continue searching for reasons of this behavior but it can be infmluenced by the queue size set on the agent
`    <queue_size>10</queue_size>`
also named [here](https://github.com/wazuh/wazuh/issues/22191#issuecomment-1976596045).

**Comment by LucioDonda** [comment]
An additional comment regarding those changes is the quantity of events handled in each version.
4.80 Beta 2 -> **~1.4E6** at it's peak
![480B2](https://github.com/wazuh/wazuh/assets/95248059/5abe0dbb-a74b-4556-a85b-4335b900eb6f)

4.8.0 Alpha 1 -> **~8E6** at it's peak
![480A2](https://github.com/wazuh/wazuh/assets/95248059/af8462a5-6621-407c-960d-e6d4b3366b96)

4.7.2 RC2 -> **~17.500** at it's peak
![472RC2](https://github.com/wazuh/wazuh/assets/95248059/41dd9a4d-4924-4f3e-a91c-77a3a396e83d)

As stated in the previous comment, having some minor percentage of that queue in the buffer handling that quantity of events won't make a change in the behaviour.

c.c. @cborla @vikman90
