### ISSUE TITLE
Feature Request: Block agents from registering / Authentication method that can be revoked / permanently remove agents

### ISSUE THREAD

**Issue by CyberOverflow** [wazuh/wazuh#22206]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| All | Wazuh Registration/ Auth | Manager/Agent | all |

## Feature Request:
Block agents from registering / Authentication method that can be revoked / permanently remove agents (with no ability to re-register)

## Issue this will solve:
Agents can be installed on devices that are no longer under active management. In these cases those, agents will continue to send data to the manager (potentially private data) that the wazuh admin would not like to be responsible for. Removing the agent will lead to the agent re-registering after X period of time. 

Adding a way to block an agent from registering, or authentication revoke mechanism will solve this.

## Example Case:
Agent is installed on a laptop given to a user. User is removed from the company, and is no longer under company management, but the laptop is kept. Laptop will continue to send non-company data to manager.

**Comment by vikman90** [comment]
@CyberOverflow Thank you for raising this feature request.

This use case indeed presents a significant concern, and your suggestion of using a certificate revocation list appears to be a promising approach. We appreciate your input and will certainly consider incorporating this into our discussions with the team to find the best way to address it and potentially include it in our roadmap.

Your contribution to enhancing the security and management capabilities of our platform is highly valued.

Best regards,

**Comment by davidjiglesias** [comment]
We will revisit this in the future once we revamp the agent-server communication.

**Comment by Santiago-Lorenzo** [comment]
since this was more than a year ago and we have the same request, Are there any ongoing plans to implement at the moment?

**Comment by vikman90** [comment]
@Santiago-Lorenzo This feature will be implemented in version 6.0.0:

- https://github.com/wazuh/wazuh/issues/22677

The new communication protocol will use pure HTTPS, allowing for the definition of custom certificates and revocation lists. This applies to both registration and connection processes, utilizing standard methods for certificate management and validation.

Best.
