### ISSUE TITLE
Empty response from wazuh-db in CI install test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22227]
## Description

- Source issue: https://github.com/wazuh/wazuh-jenkins/issues/6312

An error has been found in the install test claiming about an empty response from wazuh-db, we need to check and validate the origin of this message, as it has not been found as reported yet

```
10:01:36  2024/02/26 13:00:08 wazuh-modulesd:vulnerability-scanner: ERROR: Error handling request: Empty response from Wazuh-DB
```

> [!NOTE]
> The install test has not been adapted to the new configuration and the indexer block is enabled by default
> Wazuh indexer is not used in the install test, so the indexer block will be deactivated

Edit: The install test will not deactivate the indexer module, as not all tests report this error, in principle, we will keep the module enabled and consider the origin issue as a qa_known issue

Also, the message should be reviewed and validated as it is referring to `wazuh-db` as `Wazuh-DB`

**Comment by Dwordcito** [comment]
@sebasfalcone 

Cosmetic log issue, check that.
