### ISSUE TITLE
Invalid iteration over indexer bulk data

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#22224]
### Description

The current implementation of the RocksDB queue is encountering an issue where it incorrectly iterates over elements when processing batches of 50 items. Specifically, it consistently uses the first element in the batch, leading to incorrect processing.

### Root Cause

The root cause of this issue lies in the iteration logic implemented for processing elements in batches.

### Proposed Solution

1. **Update Iteration Logic:**
   - Review and update the iteration logic to ensure that each element in the batch is correctly processed.

2. **Test and Validate:**
   - After updating the iteration logic, thoroughly test the functionality to verify that each element in the batch is processed correctly.

### Implementation Steps

1. **Identify Faulty Iteration Point:**
   - Review the existing codebase to pinpoint the specific location where the incorrect iteration occurs.

2. **Update Iteration Logic:**
   - Modify the iteration logic to correctly iterate over each element in the batch.

3. **Test and Validate:**
   - Execute the tests to validate that the fix resolves the issue and that all elements are processed correctly.

### Impact

- **Correctness:** Resolving this issue ensures that all elements in the RocksDB queue are processed accurately, eliminating the risk of incorrect behavior.
- **Performance:** Improving the iteration logic may lead to enhanced performance and efficiency in processing queue elements.

### Definition of Done

- The iteration logic in the RocksDB queue is updated to correctly process each element in batches.
- Tests confirm that the fix resolves the issue and that all elements are processed accurately.

**Comment by GabrielEValenzuela** [comment]
We found a possible issue related to `popBulk`, and we decided to re-open this issue to fix it.
