### ISSUE TITLE
Increase `analysisd` fluctuations on footprint metrics for 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22222]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the analysis [Release 4.8.0 - Beta 2 - Footprint Metrics - ACTIVE-RESPONSE (2.5d)](https://github.com/wazuh/wazuh/issues/22176) detected an increase of the `analysisd` fluctuations and the usage decreased, compared to [4.7.2](https://github.com/wazuh/wazuh/issues/21066)

- PSS
  | 4.8.0-beta2 | 4.7.2-RC1 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/3246889d-6573-47d3-9f1a-b79d4ebd7901)|![image](https://github.com/wazuh/wazuh/assets/44633633/4eefc216-917d-4b2a-a679-b796e22c5b05)|

- RSS_MAXMIN
  | 4.8.0-beta2 | 4.7.2-RC1 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/a079fc8e-be21-4c62-abc4-e60a4083c245) |![image](https://github.com/wazuh/wazuh/assets/44633633/dfc56593-2f4a-414c-b2b9-5f1195125d98)|

- RSS
  | 4.8.0-beta2 | 4.7.2-RC1 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/efce5dbd-3720-4e5f-b149-af59d2d303e1)|![image](https://github.com/wazuh/wazuh/assets/44633633/730f5a8e-9854-4cd1-b40d-cd9076b35dc0)|

- USS
  | 4.8.0-beta2 | 4.7.2-RC1 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/3de428a3-c1c3-46af-b953-dd675ace223a)|![image](https://github.com/wazuh/wazuh/assets/44633633/c27d248c-3f2a-455d-a4cd-25fde4179c50)|

- FD - Also there is an increase in `remoted` 
  | 4.8.0-beta2 | 4.7.2-RC1 |
  |---|---|
  |![image](https://github.com/wazuh/wazuh/assets/44633633/4775df36-01e6-4c53-acdc-b5bfa20f0677)|![image](https://github.com/wazuh/wazuh/assets/44633633/2b2b746c-523e-4bf8-b4da-dde346d27087)|

**Comment by cborla** [comment]
# Analysis

## Configuration
### ossec.conf
- The manager of version 4.8.0 does not have the vulnerability detector module enabled, unlike version 4.7.2 which does.

![image](https://github.com/wazuh/wazuh/assets/41765669/d8e94cab-c52e-44b4-9e5b-a8743648428e)

- The ossec.conf configuration of the agents does not differ between versions.

### internal_options.conf and local_internal_options.conf

- The only difference in the internal options file is that the 4.7.2 includes the following section, it's involve manaegr and agents configuration:
```
# Vulnerability detector LRUs size
vulnerability-detection.translation_lru_size=2048
vulnerability-detection.osdata_lru_size=1000
```
