### ISSUE TITLE
Vulnerability Detection mismatch in normal scan and re-scan

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#22241]
## Problem Description
A discrepancy has been identified in the Vulnerability Detection (VD) process when comparing the results from the normal scanning flow against queries made directly to the global database. This mismatch is primarily due to the omission of the `format` field of the package in the current query implementation. The absence of the `format` field can lead to inaccurate vulnerability assessments, as the system fails to consider the package format during the detection process, potentially overlooking vulnerabilities specific to certain formats.

### Expected Behavior
The VD process should consistently account for the `format` field of packages, whether the scan is conducted through the normal flow or via direct queries to the global database. This inclusion will ensure accurate vulnerability assessments by considering all relevant package attributes, thereby enhancing the system's reliability and security posture.

### Steps to Reproduce
Clone a 4.8.0 branch and perform a normal scan, delete all information, and make a re-scan.

### Definition of Done Checklist
- [x] Update the VD query mechanism to include the `format` field of packages when querying the global database.
- [x] Perform comprehensive testing to ensure that the updated VD process accurately assesses vulnerabilities across various package formats.

### Possible Solutions
Change this
https://github.com/wazuh/wazuh/blob/098511a487d26a962f8d72dae0647a09d017f3e6/src/wazuh_db/wdb.c#L272

For this

```c
[WDB_STMT_SYS_PROGRAMS_GET] = "SELECT DISTINCT NAME, VERSION, ARCHITECTURE, VENDOR, SOURCE, FORMAT, CPE, MSU_NAME, ITEM_ID FROM SYS_PROGRAMS;",
```

---

**Comment by sebasfalcone** [comment]
Moved ETA - Waiting for final review
