### ISSUE TITLE
Scheduled upward merges for numbered branches in wazuh repository - Fortnight #5

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22266]
## Description

The goal is to complete the following tasks, each task must have a PR associated with this issue.

The branches **must** follow the naming: `merge-<ORIGIN_BRANCH>-into-<DESTINATION_BRANCH>`. For example, `merge-4.8.0-into-4.8.1`.

### 4.7.3
- [x] Update changelog.
- [x] [Merge branch `4.7.3` into branch `4.8.0`. ](https://github.com/wazuh/wazuh/pull/22272)
### 4.8.0
- [x] Update changelog.
- [x] [Merge branch `4.8.0` into branch `4.8.1`. ](https://github.com/wazuh/wazuh/pull/22340)
### 4.8.1
- [x] Update changelog. 
- [x] [Merge branch `4.8.1` into branch `4.8.2`. ](https://github.com/wazuh/wazuh/pull/22358)
### 4.8.2
- [x] Update changelog.
- [x] [Merge branch `4.8.2` into branch `4.9.0`. ](https://github.com/wazuh/wazuh/pull/22376)
### 4.9.0
- [x] Update changelog.
- [[ ] Merge branch `4.9.0` into branch `master`. ](https://github.com/wazuh/wazuh/pull/22410)
### 5.0.0 (master)
- [ ] Update changelog.

**Comment by vikman90** [comment]
## Status update

- We've merged 4.7.3-RC2 into 4.8.0.
- We'll continue the rest of the operations next Monday.

**Comment by JcabreraC** [comment]
These tasks were completed on the issue: https://github.com/wazuh/wazuh/issues/22317
