### ISSUE TITLE
Decrease in PSS, RSS and USS by Wazuh-db

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22275]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3-rc2 | Wazuh component | Manager | Packages | CentOS manager |

## Description

During the testing in [Release 4.7.3 - RC 2 - Footprint Metrics - ROOTCHECK (6h)](https://github.com/wazuh/wazuh/issues/22254#top) it has been detected a relevant decrease of Wazuh-db in PSS, RSS and USS plots.

The plots have been compared to [Release 4.7.2 - RC 2 - Footprint Metrics - ROOTCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/21273#top).

- PSS

| 4.7.3-RC2 | 4.7.2-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/e7c734606d4afc674685e3d4db717d082bd999ed322b00b7161e5cef6d8904fd/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343838342d3336306d2f42343838345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343838345f6d616e616765722d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/0105d5bc6ec08b0e3d9d85a39f798b540f221bd0101d11ae2afa1514f0479c21/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343733392d333630306d2f42343733395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343733395f6d616e616765722d7072652d72656c656173655f5053532e706e67) |

- RSS

| 4.7.3-RC2 | 4.7.2-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/7c20cfd91230d31ea2fb2bad7081f5a2bc942b18b2d6db9004a919745610a95f/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343838342d3336306d2f42343838345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343838345f6d616e616765722d7072652d72656c656173655f5253532e706e67) | ![IMAGE](https://camo.githubusercontent.com/f3ec4980fef28362a093dee5ba9220274dea17884cb32395184629488e71cd6c/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343733392d333630306d2f42343733395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343733395f6d616e616765722d7072652d72656c656173655f5253532e706e67) |

- USS

| 4.7.3-RC2 | 4.7.2-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/80de5efbbedb16dbb6c38e4180719442fcbf4f338dc692e30e79155cb2865051/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343838342d3336306d2f42343838345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343838345f6d616e616765722d7072652d72656c656173655f5553532e706e67) | ![IMAGE](https://camo.githubusercontent.com/0e8b4de167affc2082dc4abfc88d7c9714ab3ec6507ffb7cae84a00519b701ad/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343733392d333630306d2f42343733395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343733395f6d616e616765722d7072652d72656c656173655f5553532e706e67) |

In addition, a more precise comparison with 4.7.2-rc1 has been made and we can also see a considerable decrease of wazuh-db, for example with RSS:

![db_RSS(KB)_comparison](https://github.com/wazuh/wazuh/assets/101177239/7a7eaaff-d5b4-4aac-aad8-3204ac120caa)

**Comment by Rebits** [comment]
Comparing 4.7.3 results with 4.7.1, we can see that results are similar

| 4.7.3-RC2 | 4.7.1-RC1 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/e7c734606d4afc674685e3d4db717d082bd999ed322b00b7161e5cef6d8904fd/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343838342d3336306d2f42343838345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343838345f6d616e616765722d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/c0a1d26bbc9de18b966689b72d74ab5cd359bd42afb5942ffc81000c964202bd/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343539392d333630306d2f42343539395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343539395f6d616e616765722d7072652d72656c656173655f5253532e706e67) |
