### ISSUE TITLE
All agents disconnect after 7-14 days of usage.

### ISSUE THREAD

**Issue by sc-chad** [wazuh/wazuh#223]
I've been using the latest wazuh manager / agent / api configuration for a couple months now. 

Every couple weeks all my agents show as disconnected and there are no new agents able to connect.  My theory is I'm running out of id's I believe in ossec.

Is there a way to increase this or have it reuse existing id's?  I'm running the script to remove disconnected agents but it doesn't seem to help.

Any information I can provide on this to help get it resolved would be great!  The only way I've been able to fix it is to remove wazuh from both the server and reinstall the agents on every instance.

I am using it on Amazon Linux inside AWS on EC2.  Installed via the rpm.

**Comment by vikman90** [comment]
Hi @sc-chad,

we have different options to solve this problem:

1. Increase the number of supported agents. You should compile the manager from sources and overwrite the `MAXAGENTS` parameter before installing:

```
wazuh# make -C src clean
wazuh# make -C src TARGET=server MAXAGENTS=10000
wazuh# ./install.sh
```

I recommend you not to exceed 16.000 agents. Follow the instructions to upgrade the manager. This page from the Wazuh documentation may help you: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/sources_installation.html#installing-wazuh-manager

2. If you use Authd to register agents maybe you could force old agent deletion by executing `ossec-authd -F` or enabling `<force_insert>yes</force_insert>` in the _ossec.conf_. This option makes Authd remove automatically a previously registered agent if the new agent (that is requesting a key) has the same IP or the same name.

Nevertheless I would like to know why the manager is stopping. Please take a look to the log at `/var/ossec/logs/ossec.log` and find any error.

We have introduced some improvements in the future version 3.0 that makes Authd limit the number of registered agents (by `MAXAGENTS` parameter) so it will stop registering agents if the limit is reached.

Some other conditions like opened TCP connections or agent status files by Remoted may cause it to close. If this is the problem we'll help you to increase the limit by the operating system.

Hope it help.
Best regards.

**Comment by iAklis** [comment]
Can I change the `limit_maxagents` from yes to no in the wazuh cluster master that only run as authd? 
```
 <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>no</force_insert>
    <force_time>0</force_time>
    <purge>no</purge>
    <use_password>no</use_password>
    <limit_maxagents>no</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>${INSTALLDIR}/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>${INSTALLDIR}/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
```

**Comment by vikman90** [comment]
Hi @iAklis,

you can change it, but then you must control that limit on your own. If more than `MAXAGENTS` are registered, the manager will refuse to start.

`<limit_maxagents>no</limit_maxagents>` is a good option if you need to provision keys for many agents avoiding error, and then you filter which old agents should be removed prior to starting the manager.

Best regards.
