### ISSUE TITLE
Decrease in Disk_Read by Wazuh-logcollector

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#22324]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3-rc2 | Wazuh Agent | Agent | Packages | Ubuntu |

## Description

During the testing in [Release 4.7.3 - RC 2 - Footprint Metrics - LOGCOLLECTOR, SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/22313) it has been detected a relevant decrease of Wazuh-logcollector in Disk_read on Ubuntu.

The plots have been compared to [Release 4.7.2 - RC 2 - Footprint Metrics - LOGCOLLECTOR, SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21261).

- Disk_Read

| 4.7.3-RC2 | 4.7.2-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/a065930700af8854a7d46df2a6576b8bf3de9f17e4a53354253c13f200afacfb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | ![IMAGE](https://camo.githubusercontent.com/97f00de189ad476a6be927fdb174c4eb7a55df6ae1cb5580c06fd0c93c608189/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343734352d333630306d2f42343734355f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343734355f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |

- Same with other versions

| 4.7.3-RC2 | 4.7.2-RC1 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/a065930700af8854a7d46df2a6576b8bf3de9f17e4a53354253c13f200afacfb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | ![IMAGE](https://camo.githubusercontent.com/97e534a0b31e18fb9204d6c83f90d35c8166935c8e0714526b905d45548ec9be/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343732332d333630306d2f42343732335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343732335f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |

| 4.7.3-RC2 | 4.7.1-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/a065930700af8854a7d46df2a6576b8bf3de9f17e4a53354253c13f200afacfb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | ![IMAGE](https://camo.githubusercontent.com/368a55965d1fb3ca5eac6e066fdc7d925d54c56ae17bd33ab0ec3b8326a79947/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e312f42343639352d333630306d2f42343639355f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343639355f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |

**Comment by cborla** [comment]
## Number of generated events (agentd.state file)
![image](https://github.com/wazuh/wazuh/assets/41765669/7d5e7aed-1ab2-48fa-8f0d-703651ec8b74)

- In 4.7.3, 12% more events were generated.
- The number of messages is practically the same.

## Read Disk difference 
![image](https://github.com/wazuh/wazuh/assets/41765669/bef8bdf1-a12b-425c-811b-7d4b32577e1e)

**Comment by cborla** [comment]
## Related 4.7.3 test

| Test | Graph |
|---|---|
| LOGCOLLECTOR | ![IMAGE](https://camo.githubusercontent.com/6d1db0b9a4b49bc06fd26e888794ae40cccda2ccaeb4400de719cc1e20f540e3/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930342d333630306d2f42343930345f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343930345f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| ALL-EXCEPT-SYSCOLLECTOR | ![IMAGE](https://camo.githubusercontent.com/f836f970aafce099a13ba9d13a40d293e75f46da34d396f89ceebbaab04f3c07/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343932312d333630306d2f42343932315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343932315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| LOGCOLLECTOR,SCA | ![IMAGE](https://camo.githubusercontent.com/0d1e231f6b04f972244e348494f6d19830631e09f50c00ea46adf09821a877f0/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931322d333630306d2f42343931325f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931325f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| LOGCOLLECTOR,SYSCHECK | ![IMAGE](https://camo.githubusercontent.com/e3e413a86fbb928d4bd3f75f20c9922af20d21b0da1c5c76ce7c2db0f319ae4a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931332d333630306d2f42343931335f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931335f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
| ALL | ![IMAGE](https://camo.githubusercontent.com/89f8051c87a445f926ed304a0e35b6c76d6ac661b47486a78894a834022b2a48/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931352d333630306d2f42343931355f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931355f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) |
