### ISSUE TITLE
Add fields to the `GET /agents/outdated` endpoint response

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#22357]
## Description
As part of the [New endpoint management plugin](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6129) issue, the @wazuh/devel-dashboard team requires the use of the `GET /agents/outdated` endpoint to provide information about agents with an outdated Wazuh version in the agents' list. However, this endpoint's response contains a simplified version of the Agent, not fully providing the fields the team requires.

The present issue aims to add the required fields to avoid multiple calls to agent-related endpoints to obtain every required field.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Removed the hardcoded fields from the endpoint handler and added the `select` parameter to its specification.

**Comment by GGP1** [comment]
## Update

Applied changes suggested and updated a field in the AIT that would cause the test to fail if the agent was connected to a different node than `master`.
