### ISSUE TITLE
ossec-remoted does not allow IPv6 syslog

### ISSUE THREAD

**Issue by candlerb** [wazuh/wazuh#2237]
## Bug report

**OS**
Ubuntu 18.04

**Wazuh version**
3.7.2-1

**Wazuh API version**
3.7.2-1

**Install type**
manager

**Install method**
deb packages

**Log sample**
N/A

Bug description
----------------

I am trying to allow native UDP syslog reception on both IPv4 and IPv6.  [Documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#allowed-ips) says that allowed-ips must be set when using syslog protocol.

**Problem 1:** "allowed-ips" does not support IPv6 addresses.

```
  <remote>
    <connection>syslog</connection>
    <allowed-ips>10.0.0.0/8</allowed-ips>
    <allowed-ips>192.0.2.0/24</allowed-ips>
    <allowed-ips>2001:db8::/29</allowed-ips>
  </remote>
```

This gives a failure to startup:

```
Jan 08 16:30:34 ix-wazuh env[22466]: 2019/01/08 16:30:34 ossec-remoted: ERROR: (1237): Invalid ip address: '2001:db8::/29'.
Jan 08 16:30:34 ix-wazuh env[22466]: 2019/01/08 16:30:34 ossec-remoted: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```

Same with square brackets:

```
  <remote>
    <connection>syslog</connection>
    <allowed-ips>10.0.0.0/8</allowed-ips>
    <allowed-ips>192.0.2.0/24</allowed-ips>
    <allowed-ips>[2001:db8::]/29</allowed-ips>
  </remote>
```

Error:

```
Jan 08 16:31:09 ix-wazuh env[22487]: 2019/01/08 16:31:09 ossec-remoted: ERROR: (1237): Invalid ip address: '[2001:db8::]/29'.
Jan 08 16:31:09 ix-wazuh env[22487]: 2019/01/08 16:31:09 ossec-remoted: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
```

**Problem 2:**

If I comment out the IPv6 `allowed-ips` entry, it starts.  However the socket is bound to `0.0.0.0` rather than `::` - that is, it is only listening on IPv4.

```
# netstat -naup
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 0.0.0.0:1514            0.0.0.0:*                           23459/ossec-remoted
udp        0      0 127.0.0.53:53           0.0.0.0:*                           156/systemd-resolve
udp        0      0 0.0.0.0:514             0.0.0.0:*                           23460/ossec-remoted
```

I tried adding `<ipv6>::</ipv6>` and `<ipv6>::1</ipv6>`.  In both cases, the entry was accepted but did not change the behaviour: the socket was still bound to IPv4 only.

**Workaround:** Use rsyslog for UDP reception.  However this masks the true source IP address.

**Comment by candlerb** [comment]
I am amenable to coding a patch for this, but I seek some direction as to how you'd like to proceed.

Firstly, it believe the [documentation is wrong](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#ipv6) for the `<ipv6>` attribute.  It says:

-----

Local ipv6 address to listen for connections.

Default value | n/a
-- | --
Allowed values | Any IPv6 address

-----

However the [code](https://github.com/wazuh/wazuh/blob/master/src/config/remote-config.c#L158) says that this value is a boolean flag.

```
        } else if (strcasecmp(node[i]->element, xml_remote_ipv6) == 0) {
            if (strcasecmp(node[i]->content, "yes") == 0) {
                logr->ipv6[pl] = 1;
            }
```

Setting `<ipv6>yes</ipv6>` does indeed make the socket bind to `::`.  However, as this is an array of attributes, each `<local_ip>` has its own corresponding `<ipv6>` setting.  More on this later.

Secondly, and more importantly, everything in the `allowips` area seems to be tightly bound to struct `os_ip`:

```
/* IP structure */
typedef struct _os_ip {
    char *ip;
    unsigned int ip_address;
    unsigned int netmask;
} os_ip;
```

This in turn is hard-coded to IPv4, since it assumes you can fit an address in an `unsigned int`, and doesn't store the address family.

Would you want to extend `os_ip` so that it handled IPv6 addresses as well, e.g. as a union over a `char[16]`, with an ipv6 flag in it?  Or would you want a separate `os_ip6` structure?  The former could involve changing a lot of functions; but the latter could involve duplicating a whole load of functions too.  Either way it's going to be some big reworking.

I notice that a number of `OS_` functions take just a string representation of the address plus an ipv6 flag, e.g.

```
/* Prototypes */
static int OS_Bindport(u_int16_t _port, unsigned int _proto, const char *_ip, int ipv6);
static int OS_Connect(u_int16_t _port, unsigned int protocol, const char *_ip, int ipv6);
```

Therefore I expect the purpose of `os_ip` is to allow efficient matching of addresses in ACLs.

In other situations, e.g. the `local_ip` configuration of remoted, it is [stored as a string](https://github.com/wazuh/wazuh/blob/master/src/config/remote-config.c#L163) although validated as an IPv4-only address.

```
        } else if (strcasecmp(node[i]->element, xml_remote_lip) == 0) {
            os_strdup(node[i]->content, logr->lip[pl]);
            if (OS_IsValidIP(logr->lip[pl], NULL) != 1) {
                merror(INVALID_IP, node[i]->content);
                return (OS_INVALID);
            }
```

... and yet [later on](https://github.com/wazuh/wazuh/blob/master/src/remoted/remoted.c#L77) it passes this string (which can only be IPv4) along with the separate ipv6 flag:

```
        if ((logr.sock =
                    OS_Bindportudp(logr.port[position], logr.lip[position], logr.ipv6[position])) < 0) {
            merror_exit(BIND_ERROR, logr.port[position], errno, strerror(errno));
```

Therefore at the moment it cannot possibly work to set both `<local_ip>` and `<ipv6>`.  It would be better I think to parse each `<local_ip>` entry, decide for each one whether it is IPv4 or IPv6 based on its content, and set the `ipv6` flag automatically.

Anyway, this is all fixable, but is such an invasive change that I wouldn't want to start it without knowing which way you wanted to go .

Although I already have a number of devices sending syslogs over IPv6, I think for now I might end up switching them back over to IPv4 to dodge this issue :-(

The other option is to put rsyslog in front, which I'm currently doing, but this masks other issues with message decoding which I'd like to have in the open.

-----

Aside: oddly, the function `OS_IsValidIP` allows [between 3 and 6 dots](https://github.com/wazuh/wazuh/blob/master/src/shared/validate_op.c#L341) in an address:

```
        if (dots < 3 || dots > 6) {
            return (0);
        }
```

... although later on it is validated by `inet_addr()`.  Still, this is very IPv4-specific.

**Comment by TomasTurina** [comment]
Duplicated: https://github.com/wazuh/wazuh/issues/4243
