### ISSUE TITLE
Implement debug symbol generation during the build process for Linux - DEB

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#22381]
### Description

Currently, the RPM and DEB packages generated do not include debug symbols, which can hinder debugging efforts when issues arise. This issue aims to implement the necessary steps to generate packages with debug symbols for both RPM and DEB packages.

### Proposed Solution

1. **Update Packaging Scripts:**
   - Modify the scripts responsible for generating RPM and DEB packages to incorporate the inclusion of debug symbols.
   - Implement any necessary logic to ensure that debug symbols are correctly packaged and included.

DEB
1-  set dh_strip in the 'rules' file
```
override_dh_strip:
    dh_strip --dbg-package=wazuh-agent-dbg
```
2- Add this segment in the 'control' file
```
Package: wazuh-agent-dbg / wazuh-manager-dbg
Section: debug
Priority: optional
Architecture: any
Depends: wazuh-agent / wazuh-manager
Description: Debug symbols for [wazuh-agent / wazuh-manager]
 This package contains debug symbols for debugging [wazuh-agent / wazuh-manager].
```
3- Copy dbg the file with build.sh from the docker container to the host machine.
### Impact

    
- **Enhanced Debugging:** Including debug symbols in the packages facilitates easier debugging and troubleshooting of issues encountered by users.
- **Improved Developer Experience:** Developers benefit from having access to debug symbols when investigating issues reported by users.

### Definition of Done
- The packaging process is updated to incorporate the inclusion of debug symbols.

**Comment by tdrauncieal** [comment]
closed due to incorrect project assignment, replaced by
[Implement debug symbol generation during the build process for Linux - DEB #2871](https://github.com/wazuh/wazuh-packages/issues/2871)
