### ISSUE TITLE
Update WPK generation scripts for all missing architectures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#22400]
# Description
Hello team,

As part of the [migration development of the packag](https://github.com/wazuh/wazuh/issues/21755)e generation tools, we have found that in the WPK package generation part, the `aarch64` and `armv7hl` architectures are not working properly.

## Reproduce the problem in `wazuh-packages` 4.9.0
- Command:
`./generate_wpk_package.sh -t linux -b 4.9.0 -d /tmp/wpk -k /tmp/keys -o LinuxAgentarm64.wpk -a aarch64`
- Error:
```
Step 4/8 : RUN curl https://bootstrap.pypa.io/get-pip.py | python3 -
 ---> Running in cac160e412df
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2574k  100 2574k    0     0  5688k      0 --:--:-- --:--:-- --:--:-- 5682k
ERROR: This script does not work on Python 3.6 The minimum supported Python vers
ion is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
The command '/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py | python3 -' r
eturned a non-zero code: 1
```
I have tried to fix the python related bug, but more errors appear later related to the compiler and the lack of `cmocka` (which implies that the scripts are very outdated from the current Wazuh compilation):
```
/bin/sh: cmake: command not found
/bin/sh: cmake: command not found
```

WPKs for those architectures are not created in the documentation either:
![image_720](https://github.com/wazuh/wazuh/assets/60003131/4e25e5e0-6ee9-4b26-9816-7189ce8b1c44)

Nor does Jenkins have any pipeline prepared for it:
https://ci.wazuh.info/job/Packages_builder_tier/3421/
https://ci.wazuh.info/job/Packages_builder_tier/3422/

This issue is to evaluate if updating these scripts to support WPK packages for ARM architectures.

> Note: This issue has been extended to cover all OSs after the changes to send always a package instead of source code in the WPK file were applied (https://github.com/wazuh/wazuh/issues/21152).

**Comment by jr0me** [comment]
### Update

As we are moving towards including packages instead of sources in WPKs (according to https://github.com/wazuh/wazuh/issues/21152) the process of packing the WPK should no longer be architecture dependent.
