### ISSUE TITLE
Fix failed integration tests in 4.9.0

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#22409]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | ITs | Manager/Agent | Packages/Sources | Linux/Windows |

## Description

In the execution of the integration tests that are already migrated in this repository, we have found that there are several failed checks that need to be fixed.
These checks can be found in the following PR:
- https://github.com/wazuh/wazuh/pull/22376

The reason for this should be determined, and the necessary changes implemented so that the ITs are fixed.

### Failed ITs

We found two cases:

#### Wazuh-DB

> - [Integration tests for Wazuh_db](https://github.com/wazuh/wazuh/actions/runs/8179928591/job/22366961548?pr=22376)

These ITs are failing because of the changes that have been made for `4.7.3`:
- https://github.com/wazuh/wazuh/pull/21997
- https://github.com/wazuh/wazuh/pull/21977
```
=========================== short test summary info ============================
FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[Syscollector deltas messages - ports]
FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[Syscollector deltas messages - processes]
FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[Syscollector deltas messages - hotfixes]
FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_messages_agent[Agent messages - Agents' Packages/Hotfixes tables: sys_programs and sys_hotfixes]
FAILED test_wazuh_db/test_wazuh_db.py::test_wazuh_db_range_checksum - Asserti...
============ 5 failed, 121 passed, 1 skipped in 2586.73s (0:43:06) =============
```

#### Windows ITs

The following 3 cases are failing, and they all seem to have the same problem with the use of `.msi`:
- [Integration tests for Execd on Windows](https://github.com/wazuh/wazuh/actions/runs/8179928566/job/22392975877?pr=22376)
- [Integration tests for SCA on Windows](https://github.com/wazuh/wazuh/actions/runs/8179928586/job/22392986963?pr=22376)
- [Integration tests for Syscollector on Windows](https://github.com/wazuh/wazuh/actions/runs/8179928601/job/22393013536?pr=22376)
```
.\wazuh-agent--.msi: D:\a\_temp\26a19e9c-9eba-4373-94a2-1a70057b3800.ps1:3
Line |
   3 |  .\wazuh-agent--.msi /q WAZUH_MANAGER="127.0.0.1"
     |  ~~~~~~~~~~~~~~~~~~~
     | The term '.\wazuh-agent--.msi' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
     | again.
```

**Comment by TomasTurina** [comment]
Wazuh DB tests fixed in https://github.com/wazuh/wazuh/pull/22535.
