### ISSUE TITLE
Job for wazuh-agent.service failed because the control process exited with error code. See "systemctl status wazuh-agent.service" and "journalctl -xeu wazuh-agent.service" for details.

### ISSUE THREAD

**Issue by User-790** [wazuh/wazuh#22431]
Hello, this issue was previously unsolved in [https://github.com/wazuh/wazuh/issues/18791](url) I was hoping it could be solved with over a year worth of updates. Hopefully, some kind of solution has been found. 

I have installed the necessary requirements for adding my Ubuntu machine for the first time, and that worked fine, it was when I used a different device to host the Wazuh server on and attempted to hook up that same Ubuntu box to the new server that Wazuh is on. `Job for wazuh-agent.service failed because the control process exited with error code.
See "systemctl status wazuh-agent.service" and "journalctl -xeu wazuh-agent.service" for details.` I did some digging with 0 percent success.

**Comment by davidcr01** [comment]
Hello. To help you with this problem, I would need more information
- What is the output of `systemctl status wazuh-agent.service` and `journalctl -xeu wazuh-agent.service` commands?
- Could you share the agent files `/var/ossec/etc/ossec.conf` and `/var/ossec/logs/ossec.log` ?
- What is your Ubuntu version?
- What is your Wazuh version installed?

Also, have you followed this guide: [Deploying Wazuh agents on Linux endpoints](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html#deploying-wazuh-agents-on-linux-endpoints)? 
Remember that if you install the agent but you don't configure a manager IP, it won't be able to start. Also, if you changed where Wazuh was installed, maybe you should change the IP address of the manager specified in the `ossec.conf` of the Wazuh agent.

**Comment by vladyslav-yavorskyi** [comment]
HI! I had similar problem. Try to change the IP in /var/ossec/etc/ossec.conf. For some reasons it was written just "MANAGER IP" and after changing it for real ip of my wazuh it worked.

**Comment by olofmagn** [comment]
@vladyslav-yavorskyi. I noticed the same issue. The XML parser, or the application interpreting the configuration file (in this case, OSSEC), interprets the value in `<address>` as a string rather than an IP address.

Changing the field from `MANAGER IP` to the actual target IP-address (server) also resolved my issue.

**Comment by Usernameisalreadytaken5** [comment]
now we live in 2025 and on my rasbery pi 6.6.31+rpt-rpi-v7 SMP Raspbian 1:6.6.31-1+rpt1 

 wazuh-execd: Configuration error. Exiting
Oct 25 05:57:55 NEW-banana systemd[1]: wazuh-agent.service: Control process exited, code=exited, statu>
Oct 25 05:57:55 NEW-banana systemd[1]: wazuh-agent.service: Failed with result 'exit-code'.
Oct 25 05:57:55 NEW-banana systemd[1]: Failed to start wazuh-agent.service - Wazuh agent.

empty logs

**Comment by JakoobCZ** [comment]
Same situation here, even though the IP was correct, the file "ossec.conf" had "manager IP" instead. After changing it to the IP of Wazuh server (in my case 192.168.x.x), the agent started correctly. Thank you guys for you comments :)

**Comment by maryumxx** [comment]
vboxuser@wazuh-agent:~$ systemctl status wazuh-agent.service
× wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/wazuh-agent.service.d
             └─timeout.conf
     Active: failed (Result: exit-code) since Sat 2026-02-21 00:38:36 PKT; 1min 28s ago
    Process: 18158 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILUR>
      Tasks: 2 (limit: 4603)
     Memory: 1.5M (peak: 4.2M)
        CPU: 3.458s
     CGroup: /system.slice/wazuh-agent.service
             └─18180 /var/ossec/bin/wazuh-execd
lines 1-11/11 (END)

vboxuser@wazuh-agent:~$ journalctl -xeu wazuh-agent.service
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.


Can anyone crack this issue?? I've been looping in commands since weeks :))

**Comment by pktsentinel** [comment]
Did you find the issue? I had the same problem and I finally fixed it.

**Comment by olofmagn** [comment]
@pktsentinel Please feel free to share a solution in the comments as it might help others who is stuck =)

**Comment by pktsentinel** [comment]
I faced two distinct issues when starting the Wazuh service on my client:

**1) Duplicate Agent Name error**
I had to force a unique name change using the following:

```
sudo /var/ossec/bin/agent-auth -m 10.10.10.101 -a -A proxmox-agent-01
```

**2) Service failure issue in the ossec.config file**
I erased everything within the file and used the following:

```
<ossec_config>

  <client>

    <server>

      <address>10.10.10.101</address>

      <port>1514</port>

      <protocol>tcp</protocol>

    </server>

    <config-profile>ubuntu, ubuntu24, ubuntu24.04</config-profile>

  </client>

  <logging>

    <log_format>plain</log_format>

  </logging>

  <localfile>

    <log_format>syslog</log_format>

    <location>/var/log/auth.log</location>

  </localfile>

  <localfile>

    <log_format>syslog</log_format>

    <location>/var/log/syslog</location>

  </localfile>

  <localfile>

    <log_format>syslog</log_format>

    <location>/var/ossec/logs/active-responses.log</location>

  </localfile>

</ossec_config>
```

I followed it by running these commands to just to make sure that the system could read the configurations, as I initially didn't have access and kept getting failed service starts:

```
sudo chown root:wazuh /var/ossec/etc/ossec.conf /var/ossec/etc/client.keys
sudo chmod 640 /var/ossec/etc/ossec.conf /var/ossec/etc/client.keys
```

I tested the syntax (didn't get anything back = good):

```
sudo /var/ossec/bin/wazuh-agentd -t
```

Start the service and it worked:

```
sudo systemctl daemon-reload
sudo systemctl restart wazuh-agent
sudo systemctl status wazuh-agent
```
