### ISSUE TITLE
request to set the default kibana index to "wazuh-alerts-3.x-*"

### ISSUE THREAD

**Issue by sonofagl1tch** [wazuh/wazuh#2244]
request to set the kibana default index to "wazuh-alerts-3.x-*" so that it will automatically start ingestion and mapping of data.

Below is my latest attempt to configure the default index as part of the wazuh install script. This command doesnt work yet but it is close to what is needed to be done.

```
ES_URL=${ES_URL:-'http://localhost:9200'}
ES_USER=<TEST>
ES_PASSWORD=<TEST>
curl -s -u ${ES_USER}:${ES_PASSWORD} -XPOST "${ES_URL}/.kibana/index-pattern/wazuh-alerts-3.x-*" -H 'Content-Type: application/json' -H "Accept: application/json" -d'
{
  "title" : "wazuh-alerts-3.x-*",  
  "timeFieldName": "timestamp"
}
'
```

**Comment by jesusgn90** [comment]
Hi @sonofagl1tch,

First of all, sorry for the late response.

We are not planning to include this in the installation guide, but I've added it to the Wazuh app repository wiki: https://github.com/wazuh/wazuh-kibana-app/wiki/Set-default-index-pattern-in-Kibana

Here is the snippet:

```sh
default_index="/tmp/default_index.json"
cat > ${default_index} << EOF
{
  "changes": {
    "defaultIndex": "wazuh-alerts-3.x-*"
  }
}
EOF

curl -POST "http://localhost:5601/api/kibana/settings" -H "Content-Type: application/json" -H "kbn-xsrf: true" -d@${default_index}
rm -f ${default_index}
```

And as a final note I want to say that the ingestion is not related to Kibana, Elasticsearch ingests the data and Logstash/Filebeat sends the data, Kibana just visualizes it.

I'm going to close the ticket, but feel free to re-open it or create a new one if needed.

Best regards,
Jesús
