### ISSUE TITLE
Vulnerability refactor quality detection testing

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#22443]
# Description 

As part of the analysis here https://github.com/wazuh/wazuh/pull/22360#issuecomment-1984329131 and since most of the operating systems are getting support for the new vulnerability detector module, we need to ensure the reliability of the detection. In particular, some difference between the current and the legacy module needs attention. 

As mentioned in the comment above for Windows (mainly Windows Server 2019) we have a huge disparity in the vulnerabilities detected. For this OS using the legacy module, we found the following vulnerabilities 

[001_cves.log](https://github.com/wazuh/wazuh/files/14565279/001_cves.log)
[002_cves.log](https://github.com/wazuh/wazuh/files/14565280/002_cves.log)
[003_cves.log](https://github.com/wazuh/wazuh/files/14565281/003_cves.log)

Where 

![image](https://github.com/wazuh/wazuh/assets/13010397/cba47ecc-919b-4244-8285-f1768826b2f4)

# DoD 

- [x] Evaluate the difference between the two implementations.
- [x] Propose a fix (if needed) if the solution does not require more investigation.
- [x] Add test cases.

**Comment by sebasfalcone** [comment]
## Issues dispatched
- https://github.com/wazuh/intelligence-platform/issues/1440
- https://github.com/wazuh/intelligence-data/issues/69

**Comment by sebasfalcone** [comment]
## Issues related
- https://github.com/wazuh/wazuh/pull/22482
- https://github.com/wazuh/wazuh/issues/22477

**Comment by sebasfalcone** [comment]
Great analysis @MiguelazoDS!

We will continue with the issues that are needed to fix the problems reported

@Dwordcito Ready for your final opinion

**Comment by sebasfalcone** [comment]
Great analysis @MiguelazoDS!

We will continue with the issues that are needed to fix the problems reported
