### ISSUE TITLE
Package versions identified as vulnerable but are already in the latest version of the repository

### ISSUE THREAD

**Issue by FocusOnTheCell** [wazuh/wazuh#22459]
Hello guys,

Currently, we are using Wazuh 4.5.3 to monitor our infrastructure and we are upgrading some machines from Oracle Linux and Red Hat 7 to 8. After this OS upgrade, we noticed that some CVEs were being triggered by the vulnerability-detector saying that a package has a vulnerable version. However, it's the latest available version on the machine repositories. In this case, we can't add extra repositories to the machines so what can we do to fix this?

Let me know if I can provide any other relevant information.

Best regards,
FocusOnTheCell

**Comment by pereyra-m** [comment]
Hello @FocusOnTheCell !

To properly analyze the vulnerabilities reported in your hosts, it'd be required:
- The agents' packages inventory
- The list of detected CVEs

This way, we'll be able to know if they are valid or false positives.
Sometimes there are inaccurate entries in the vendor feeds that need to be corrected and the team is working on this for the refactored vulnerability detector that will be available in v4.8.0.

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
