### ISSUE TITLE
BUG - in Browser Rule Editor HTML / BODY tags

### ISSUE THREAD

**Issue by maikroservice** [wazuh/wazuh#22461]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Wazuh dashboard | Manager/Agent | apt packages | Ubuntu Server 22.04 |

Hello, I found a bug that I have not seen before - when you open custom? rule files through the wazuh dashboard management option before and after the rule html tags are added in the input field:
<img width="468" alt="image" src="https://github.com/wazuh/wazuh/assets/20245897/34b3d45f-d719-493d-a215-fcba01fb7c64">

These are not present in the "real" rule file on the machine but only in the browser
<img width="479" alt="image" src="https://github.com/wazuh/wazuh/assets/20245897/fb135f1f-ab4d-4ac1-96bc-a7a9d7f2bb81">

I tested it both with edge and brave on a Windows10 host and both show the same behavior so I assume this is a frontend/backend issue rather than a client side configuration thing on my end. 

Can you verify that this is an issue?

**Comment by lucianogorza** [comment]
Hi @maikroservice,
We tried to reproduce it in several browsers and operating systems, and we got the same rule that is saved on the server, without <html> and <body> tags.
Could you please share a screenshot of the API request (the same one I attached) to see the backend response?

![image](https://github.com/wazuh/wazuh/assets/103193307/1722328b-3b05-4c99-a02d-c24cca5dd87d)

**Comment by maikroservice** [comment]
Its in the response as well 🤷😅

<img width="847" alt="Screenshot 2024-03-12 at 23 32 13" src="https://github.com/wazuh/wazuh/assets/20245897/7fcce2a7-c3e3-4fe6-ada3-702468dbfad8">

**Comment by lucianogorza** [comment]
@maikroservice Could you please share the manager version and OS, and the installation method?

**Comment by maikroservice** [comment]
<html>
<body>

Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
4.7.3 | Wazuh dashboard | Manager/Agent | apt packages | Ubuntu Server 22.04


</body>
</html>

**Comment by lucianogorza** [comment]
@maikroservice To ensure that you are comparing the same rule files, could you check the API.log on the manager?
You can run the following command:
```
root@wazuh:/var/ossec/logs# cat api.log | grep "mssql.xml"
```
This command will display the API request you made and its parameters. Please check the value of "relative_dirname" and ensure that it matches the location from where you are viewing the rule on the server.

**Comment by maikroservice** [comment]
```
HTTP/1.1 200 OK
Date: Fri, 15 Mar 2024 21:18:36 GMT
Server: Apache/2.4.41 (Ubuntu)
osd-name: ip-10-10-0-31
content-type: text/html;charset=utf-8
cache-control: private, no-cache, no-store, must-revalidate
Vary: Accept-Encoding
Content-Encoding: gzip
set-cookie: security_authentication=Fe26.2**2ae77dedf52a09c3e855a38c94769068ea1d5397d3811e7d227f3dae235026b2*2KSM7TLxtX4oSCju90WhaA*DqVyODQPxw0byeyie3BIChR0mj8SYukECWvBArp_YlmQEMkTDROaU8NJnvMFihJgBJgdrjxKiKt4IcbvlW2AQ7-ERp9D6pCMf8w6QWg_FQ-Nw8AYgYiuhzKAQFrvJVM2_DAfFMwLelX6ELFJ-psTRGyM5uxdLoVRJKjD8Be2dZJJp6-gmdhHB4Oqw8EKme7jrrBnvzSmMoeyvOxCyhv5y4j6tfLp4HDqUgv4AJKXavLyipKthtvyznDP2YIh5x4q**18e64939f4cdb9cd742bf97f5717df0f9b7ccfc2deb22824d421f58dc1e53420*vBYaM_xAUzi8A0L-xij0V2Xq_yz9VOqgRSD8WvLutfo; HttpOnly; Path=/; Secure; SameSite=None
Content-Length: 246
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

**Comment by lucianogorza** [comment]
Thank you for the response.
In the response headers, I noticed a value that caught my attention: `Server: Apache/2.4.41 (Ubuntu)`.
Is the Wazuh Dashboard or the Wazuh Server running behind an Apache server? Please review the Apache configuration; it may be adding those tags.
On another hand, to determine if the issue lies with the Server environment or the Dashboard, could you run these requests directly to the API:
```
wz_api_token=$(curl -u <SERVER_USER>:<SERVER_PASSWORD> -s -k -X POST "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -v -H "Authorization: Bearer ${wz_api_token}" "https://localhost:55000/rules/files/mssql.xml?raw=true&relative_dirname=etc/rules"
```
