### ISSUE TITLE
Release 4.8.0 - Beta 4 - Integration tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22479]
# Description
|| |
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/22457 |
| **Version**                      | 4.8.0                                                   |
| **Release stage**            | Beta  4                                                     
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta24         |
| **Wazuh QA: Branch**    | `v4.8.0-beta4`
| **Wazuh: Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.0-beta4     |
| **Wazuh: Branch**    | `v4.8.0-beta4` |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build:*** https://ci.wazuh.info/job/Test_integration_launcher/249/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46646/manager_html_report_Test_integration_B46646.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46647/agent_centos_html_report_Test_integration_B46647.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46647/agent_windows_html_report_Test_integration_B46647.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46648/agent_centos_html_report_Test_integration_B46648.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46648/agent_windows_html_report_Test_integration_B46648.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>analysisd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46649/manager_html_report_Test_integration_B46649.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>api</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46650/manager_html_report_Test_integration_B46650.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46651/manager_html_report_Test_integration_B46651.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46652/agent_centos_html_report_Test_integration_B46652.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46652/agent_windows_html_report_Test_integration_B46652.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46653/manager_html_report_Test_integration_B46653.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46654/agent_centos_html_report_Test_integration_B46654.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46654/agent_windows_html_report_Test_integration_B46654.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46655/agent_macos_html_report_Test_integration_B46655.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46655/agent_solaris_html_report_Test_integration_B46655.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46656/manager_html_report_Test_integration_B46656.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46657/manager_html_report_Test_integration_B46657.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>github</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46658/agent_centos_html_report_Test_integration_B46658.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46659/manager_html_report_Test_integration_B46659.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46660/agent_centos_html_report_Test_integration_B46660.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46660/agent_windows_html_report_Test_integration_B46660.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46660/agent_macos_html_report_Test_integration_B46660.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46660/agent_solaris_html_report_Test_integration_B46660.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46661/manager_html_report_Test_integration_B46661.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46662/manager_html_report_Test_integration_B46662.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>office_365</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46663/agent_centos_html_report_Test_integration_B46663.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46664/manager_html_report_Test_integration_B46664.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46665/manager_html_report_Test_integration_B46665.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rootcheck</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46666/manager_html_report_Test_integration_B46666.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46667/manager_html_report_Test_integration_B46667.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46668/manager_html_report_Test_integration_B46668.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46645/agent_centos_html_report_Test_integration_B46645.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46645/agent_windows_html_report_Test_integration_B46645.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46645/agent_macos_html_report_Test_integration_B46645.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

### Jenkins IT :red_circle: 
- https://github.com/wazuh/wazuh/issues/22495 (Deprecated in favor of GA)
- https://github.com/wazuh/wazuh/issues/22058 
- https://github.com/wazuh/wazuh/issues/22496
- https://github.com/wazuh/wazuh-qa/issues/5096 

Outdated tests present in Jenkins and qa repository
- https://github.com/wazuh/wazuh-jenkins/issues/6361

### GA :red_circle: 
- https://github.com/wazuh/wazuh/issues/22503
- https://github.com/wazuh/wazuh/issues/22504

**Comment by Rebits** [comment]
IT errors reported in the following issues:
- **API**: https://github.com/wazuh/wazuh/issues/22495

**Comment by Rebits** [comment]
## GA supported in 4.8.0
- API: 
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-api-tier-0-1.yml
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-api-tier-2.yml 
- Analysisd
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-analysisd-tier-0-1.yml 
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-analysisd-tier-2.yml 
- Execd:
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-execd-tier-0-1-lin.yml
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-execd-tier-0-1-win.yml
- Github
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-github-tier-0-1-lin.yml
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-github-tier-0-1-win.yml 
- Office365
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-office365-tier-0-1-lin.yml 
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-office365-tier-0-1-win.yml	
- MSGraph
  - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-msgraph-tier-0-1-lin.yml
- Vulnerability Detection
   - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-vulnerability_detector-tier-0-1.yml
   - https://github.com/wazuh/wazuh/actions/workflows/integration-tests-vulnerability_detector-tier-2.yml

**Comment by Rebits** [comment]
### MSGraph 
- https://github.com/wazuh/wazuh/actions/runs/8264458637

**Comment by MARCOSD4** [comment]
GJ! A minor change is needed in GitHub MSGraph, as the links are upside down.

**Comment by MARCOSD4** [comment]
LGTM

**Comment by juliamagan** [comment]
LGTM
