### ISSUE TITLE
Review and update API `spec.yaml`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22478]
|Component|
|---|
| Wazuh API |

## Description

Some endpoint output examples are currently wrong/outdated in the [API spec](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.delete_multiple_agent_single_group). Something similar happens with the expected `status_code`  and also the [models](https://github.com/wazuh/wazuh/blob/epic/20748-upgrade-to-connexion-3/api/api/spec/spec.yaml#L655-L7035). 

We should review them all and update anything where needed. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

API specification parameters request bodies and permissions validation, requests execution, responses validation and spelling and grammar corrections.

**Comment by GGP1** [comment]
## Update

Finished making corrections and adjusting the API spec to conform with the actual endpoint responses and launched a burst of API integration tests to validate that no issue has been introduced.
