### ISSUE TITLE
Implementing Translation Usage for Content

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#22477]
## Description
The generated content currently lacks synchronization with the information obtained from `syscollector` due to the absence of applied "translations". These translations should be integrated into the `syscollector` data to ensure consistency with vulnerability information.

## Example
For instance, consider the following translation:
```json
{
  "target": "windows",
  "source": {
    "vendor": "Microsoft Corporation",
    "product": "^Microsoft ASP.NET Core ([0-9]\\.*[0-9]*\\.*[0-9]*)",
    "version": "^Microsoft ASP.NET Core ([0-9]\\.*[0-9]*\\.*[0-9]*)"
  },
  "translation": [
    {
      "vendor": "microsoft",
      "product": "asp.net_core",
      "version": ""
    }
  ],
  "action": [
    "replace_vendor",
    "set_version_if_product_matches",
    "replace_product"
  ]
}
```

Corresponding `syscollector` event:
```json
{
  "scan": {
    "id": 0,
    "time": "2023-11-28T21:30:44+00:00"
  },
  "priority": " ",
  "format": "win",
  "architecture": "x86_64",
  "size": 0,
  "description": " ",
  "name": "Microsoft ASP.NET Core 3.1.0 Shared Framework (x64)",
  "vendor": "Microsoft Corporation",
  "install_time": "2023-11-28T21:04:32+00:00",
  "source": " ",
  "location": " ",
  "section": " ",
  "version": "3.1.0.0",
  "agent_id": "001"
}
```

Expect result:
```json
{
  "scan": {
    "id": 0,
    "time": "2023-11-28T21:30:44+00:00"
  },
  "priority": " ",
  "format": "win",
  "architecture": "x86_64",
  "size": 0,
  "description": " ",
  "name": "asp.net_core",
  "vendor": "microsoft",
  "install_time": "2023-11-28T21:04:32+00:00",
  "source": " ",
  "location": " ",
  "section": " ",
  "version": "3.1.0",
  "agent_id": "001"
}
```

## Details

To avoid compiling the translation regex every time we perform a scan and to reduce the number of calls to the database, we could initialize the translations in a caché
```mermaid
sequenceDiagram
  participant databaseFeedManager
  participant RocksDB
  participant TranslationsCache

  databaseFeedManager->>RocksDB: Request translations from RocksDB
  activate RocksDB
  RocksDB-->>databaseFeedManager: Translations data

  databaseFeedManager-->>TranslationsCache: Initialize TranslationsCache
  activate TranslationsCache
  TranslationsCache-->>databaseFeedManager: Initialized
```

> [!NOTE]
> It's important to measure the impact of having this map loaded into memory
>
> Take into account that it will grow in the future

The logic that must take place to apply the translations is the following:
```mermaid
sequenceDiagram
  participant Syscollector
  participant ScanContext
  participant TranslationsCache

  Syscollector->>ScanContext: Event data
  activate ScanContext

  ScanContext-->>TranslationsCache: Check target in TranslationsCache
  activate TranslationsCache
  alt Target Matched
    TranslationsCache-->>ScanContext: Target matched
    ScanContext-->>TranslationsCache: Check product in TranslationsCache
    alt Product Matched
      TranslationsCache-->>ScanContext: Product matched
      ScanContext-->>TranslationsCache: Check vendor in TranslationsCache
      alt Vendor Matched
        TranslationsCache-->>ScanContext: Vendor matched
        ScanContext-->>TranslationsCache: Apply translation
        TranslationsCache-->>ScanContext: Translation applied
        ScanContext-->>ScanContext: Return processed data
      else
        TranslationsCache-->>ScanContext: Vendor not matched
      end
    else
      TranslationsCache-->>ScanContext: Product not matched
    end
  else
    TranslationsCache-->>ScanContext: Target not matched
  end

  deactivate TranslationsCache
  deactivate ScanContext
```
> [!IMPORTANT]
> It's important that the first filter (target) is as robust as possible because it's the cheapest step

## DoD
- [ ] The syscollector data incorporates the translations.
- [ ] The implementation is integrated into the scanContext.
- [ ] The solution demonstrates performance.
- [ ] Regex patterns are efficiently managed to prevent re-compilation, enhancing overall performance.

**Comment by GabrielEValenzuela** [comment]
# Development journey

## 03/15/2024

Start design of the solution, analyzing the current code.

## 03/18/2024

Start implementation after the team discussion, but, I found a block due to an old implementation of the translations in `datbaseFeedManager`. Removing it implies refactoring all tests, if possible, but extending the ETA.
I'm considering also a different approach, using the scanner as a common factor for all messages, and the use of a coordinate cache with the result of the translations. 
Work in progress and pending review with @sebasfalcone  and @Dwordcito

**Comment by sebasfalcone** [comment]
### Moved ETA

The complexity of the problem required a lot of time discussing, planning and investigating. This will be a key part of the scanner and should be developed with care
