### ISSUE TITLE
Release 4.8.0 - Beta 4 - System tests

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22481]
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |   https://github.com/wazuh/wazuh/issues/22457                                         |
| **Version**                          |  4.8.0                                           |
| **Release candidate #**              |  Beta 4                                           |
| **Tag**                              |  https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta4                                            |
| **Previous system tests issue**      |  https://github.com/wazuh/wazuh/issues/22123       |

## Instructions
To run tests in an AWS EC2 virtual environment, the following requirements will need to be met:

| Environment                  | EC2                                       |
|------------------------------|-------------------------------------------|
|Basic_cluster                 |Ubuntu 22.04.2 LTS C5.XLarge 15GB SSD      |
|Big_cluster_40_agents         |Ubuntu 22.04.2 LTS T3.Large 60GB SSD       |
|Agentless_cluster             |Ubuntu 22.04.2 LTS T3.Large 30GB SSD       |
|Four_manager_disconnected_node|Ubuntu 22.04.2 LTS T3.Large 30GB SSD       |
|One_manager_agent             |Ubuntu 22.04.2 LTS T3.Large 30GB SSD       |
|Manager_agent                 |Ubuntu 22.04.2 LTS T3.Large 30GB SSD       |
|Enrollment_cluster            |Ubuntu 22.04.2 LTS T3.Large 30GB SSD       | 
|Basic_environment             |Ubuntu 22.04.2 LTS T3.Large 30GB SSD       |

These requirements should be requested to the @wazuh/cicd team via https://github.com/wazuh/internal-devel-requests.

- Instances requested in https://github.com/wazuh/internal-devel-requests/issues/972

For further information, check https://github.com/wazuh/wazuh-qa/tree/master/tests/system/README.md

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusion :red_circle:

  - https://github.com/wazuh/wazuh-qa/issues/5099
  - https://github.com/wazuh/wazuh-qa/issues/5100
  - https://github.com/wazuh/wazuh-qa/issues/5101
  - https://github.com/wazuh/wazuh-qa/issues/5102

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @juliamagan

**Comment by Rebits** [comment]
Currently launching `basic_environment`, `one_manager_agent`, `manager_agent` and `enrollment_cluster` tests.
Results will be uploaded 13/03/2024


```
cd provisioning/basic_environment
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"package_repository":"packages-dev", "repository": "pre-release", "package_version": "4.8.0", "package_revision": "1", "wazuh_qa_branch":"v4.8.0-beta4"}'
cd ../..
python3 -m pytest -v -m basic_environment_env --html=basic_env.html

cd provisioning/one_manager_agent
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"package_repository":"packages-dev", "repository": "pre-release", "package_version": "4.8.0", "package_revision": "1", "wazuh_qa_branch":"v4.8.0-beta4"}'
cd ../..
python3 -m pytest -v -m one_manager_agent_env --html=one_manager_agent.html

cd provisioning/enrollment_cluster
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"package_repository":"packages-dev", "repository": "pre-release", "package_version": "4.8.0", "package_revision": "1", "wazuh_qa_branch":"v4.8.0-beta4"}'
cd ../..
python3 -m pytest -v -m enrollment_cluster_env --html=enrollment_cluster.html

cd provisioning/manager_agent
ansible-playbook -i inventory.yml playbook.yml --extra-vars='{"package_repository":"packages-dev", "repository": "pre-release", "package_version": "4.8.0", "package_revision": "1", "wazuh_qa_branch":"v4.8.0-beta4"}'
cd ../..
python3 -m pytest -v -m manager_agent_env --html=manager_agent.html

```

**Comment by Rebits** [comment]
## Test results :large_blue_circle:

**Comment by MARCOSD4** [comment]
GJ! Some review notes:

- Missing link to download the report for `one_manager_agent.zip`
- The links of the new issues are missing in the Issues Ref. column of the report.
- the basic_environment.zip file does not contain the assets directory, although it does appear in the file attached to the issue https://github.com/wazuh/wazuh-qa/issues/5102.

**Comment by MARCOSD4** [comment]
LGTM

**Comment by juliamagan** [comment]
LGTM
