### ISSUE TITLE
FIM and Syscollector IT fails for Windows agent due to error deleting old db

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22496]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | FIM/Sycollector | Agent | Packages | Windows Server 2016 |
### Description

FIM and syscollector integration tests fail for Windows agents due to an unexpected error deleting old db.
```
2024/03/12 18:19:48 wazuh-agent[2908] logging_helper.c:53 at loggingFunction(): CRITICAL: Error, id: dbEngine: Error deleting old db.
```

The roster of IT failures includes:
- `test_file_limit_full`
- `test_file_limit_no_limit`
- `test_syscollector_configuration`

### Related Issues
- https://github.com/wazuh/wazuh/issues/18968
- https://github.com/wazuh/wazuh-qa/issues/4556
- https://github.com/wazuh/wazuh/issues/18941

### Evidences
- **Syscollector IT Windows Agent**: https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46645/agent_windows_html_report_Test_integration_B46645.zip
- **FIM IT Windows Agent**: https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46654/agent_windows_html_report_Test_integration_B46654.zip

**Comment by Dwordcito** [comment]
TIMEBOX RCA 19/03/2024

**Comment by MiguelazoDS** [comment]
The issue may be related to this 

https://en.cppreference.com/w/cpp/io/c/remove

> If the file is currently open by any process, the behavior of this function is implementation-defined. POSIX systems unlink the file name (directory entry), but the filesystem space used by the file is not reclaimed while it is open in any process and while other hard links to the file exist. Windows does not allow the file to be deleted in such cases.

**Comment by Dwordcito** [comment]
@MiguelazoDS this is a flaky test ???  Is reproducible in previous versions?

**Comment by MiguelazoDS** [comment]
## Update 04/04 

Unable to reproduce the Syscollector errors 

[syscollector.tar.gz](https://github.com/wazuh/wazuh/files/14872991/syscollector.tar.gz)

![image](https://github.com/wazuh/wazuh/assets/13010397/9c5a704c-feb4-446e-b967-eefc702cc267)

Unable to reproduce the Fim errors 

[fim.tar.gz](https://github.com/wazuh/wazuh/files/14873096/fim.tar.gz)

![image](https://github.com/wazuh/wazuh/assets/13010397/a6d42ec8-d8ec-43a3-8c9d-65691e64d854)

**Comment by Dwordcito** [comment]
Moved to 4.8.2, this part of the code has not changed in 4.8.0, is a pre-existing issue.

**Comment by sebasfalcone** [comment]
We conclude that this issue has to do with the test itself and not with the product, as stated here:
- https://github.com/wazuh/wazuh/issues/18968#issuecomment-1722605988

And also concluded here:
- https://github.com/wazuh/wazuh/issues/18968#issuecomment-1721888322

The issue may be addressed here:
- https://github.com/wazuh/wazuh/issues/17881
