### ISSUE TITLE
Missing vulnerability value in the statistics in API IT 

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22495]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | API | Manager | Packages | centOS7 |

### Description

The integration test for API `test_manager_statistics_format` is failing because the vulnerability statistics are missing from the response.

Upon inspection of the logs, it's evident that the vulnerability scanner module is disabled:

```bash
2024/03/12 18:15:52 wazuh-modulesd:vulnerability-scanner: INFO: Starting vulnerability_scanner module.
2024/03/12 18:15:52 wazuh-modulesd:database: INFO: Module started.
2024/03/12 18:15:52 wazuh-modulesd:download: INFO: Module started.
2024/03/12 18:15:52 wazuh-modulesd:syscollector: INFO: Module disabled. Exiting...
2024/03/12 18:15:52 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2024/03/12 18:15:52 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module is disabled
```

`vulnerability` is a required property of the response even if the module is disabled. This behavior is expected due to other disabled modules like rootcheck are included in the response.

### Evidences
- **Issue**: https://github.com/wazuh/wazuh/issues/22479
- **Report**: https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B46650/manager_html_report_Test_integration_B46650.zip

**Comment by Selutario** [comment]
These API Integration tests were already migrated to wazuh/wazuh:
- https://github.com/wazuh/wazuh/issues/17441

Since then, they are run on `Github Actions` and the version that is still on wazuh-qa has been discontinued. In fact, the CI pipeline was modified so that it does not run these tests in PRs starting with 4.9:
- https://github.com/wazuh/wazuh-jenkins/issues/5779

**Comment by Selutario** [comment]
I'm closing the issue since this is an expected error.
