### ISSUE TITLE
Release 4.8.0 - Beta 4 - Vulnerability Detector comparison

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#22494]
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |             https://github.com/wazuh/wazuh/issues/22457                               |
| **Main Vulnerability Detection tests issue**     |             https://github.com/wazuh/wazuh/issues/22492                               |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                    Beta 4                        |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-beta4                                |
| **Previous Vulnerability tests issue**      |       https://github.com/wazuh/wazuh-qa/issues/4898                                    |

### Description

In version 4.8.0 of the Wazuh, a significant refactor has been implemented in the Vulnerability Detector module (Check [this](https://github.com/wazuh/wazuh/issues/14153) issue for more information). This refactor introduces changes that may impact the detection of vulnerabilities compared to the previous version, 4.7.3.

### Objective

The objective of this testing issue is to perform a thorough analysis to identify any potential discrepancies in vulnerability detection between Wazuh 4.7.3 and 4.8.0. The analysis will be conducted on multiple operating systems.
### Testing Parameters:

**Testing Environment:**
- **Multiple OS**
    - macOS Sonoma
    - Windows 11
    - Amazon Linux 2023
    - Ubuntu 22.04
    - Red Hat Enterprise Linux (RHEL) 9
- **Architecture**
    - AMD

### Testing Procedure
- Deploy Wazuh version 4.7.2 on each specified operating system.
- Deploy Wazuh version 4.8.0 on each specified operating system.
- Execute the vulnerability detection scan on both versions for each operating system.
- Record and compare the results to identify any discrepancies between 4.7.2 and 4.8.0.

#### New issues
- https://github.com/wazuh/wazuh/issues/22518
#### Known issues
- https://github.com/wazuh/wazuh/issues/21854
- https://github.com/wazuh/wazuh/issues/21838

**Comment by juliamagan** [comment]
|Box|4.7.3 Vulnerabilities|4.8.0 Vulnerabilities|
|---|---|---|
|`ubuntu/jammy64`|[166](https://github.com/wazuh/wazuh/files/14586536/ubuntu_clean_4.7.3_vulns.json)| |

**Comment by rafabailon** [comment]
### LGTM
