### ISSUE TITLE
Test: Active response

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2251]
# Testing: Active response

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Active response

- [x] Insert 2 times same config
- [x] Test active-response from wrong SO
- [x] Test active-response from correct SO
- [x] Check that the execution of the active response respects the location
- [x] Specifies more than one agent_id. It must only work the last one.
- [x] Check level filter
- [x] Check rules_group filter
- [x] Check rules_id filter
- [x] Check the period of the reverse command (timeout option)
- [x] Check incremental timeouts (repeated_offenders)
- [x] Check the exec daemon runs when active-response is disabled.

## Command

- [x] Insert 2 times same config
- [x] Configure a command that does not exist
- [x] Same command for multiple active-response
- [x] Check that the extra_args option works for any field
- [x] Check that the expect option works for any field
- [x] Verify that the return command can be enabled and disabled (timeout_allowed)
- [x] Set the command below the active response that uses it
- [x] Test firewall-drop command

## agent_control

- [x] Send an active-response to an agent using agent_control

## Custom A-R

- [x] Test custom active-response explained at https://github.com/wazuh/wazuh/issues/1116

**Comment by branchnetconsulting** [comment]
Skeptor's issue about insufficient and confusing documentation of the **<extra_args>** option appears unresolved to me.  I still find that part of the documentation unclear.  

It sounds like this option is appending more fields to the call to the AR script, after the 5 parameters that are already normally sent.  However that does not seem to have much to do with the example used in the documentation:

 `<extra_args>-arg1 --arg2 arg3 ; cat /etc/passwd</extra_args>`

I do not see any field names in the example, just arg1, arg2, and arg3 with varying numbers of dashes in front of them.  And what is the command doing embedded in there?  Please explain and update the documentation accordingly.

Kevin Branch
