### ISSUE TITLE
Wazuh-DB errors during upgrade 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#22510]
# Description 

As part of the E2E testing https://github.com/wazuh/wazuh/issues/22453 It was found the following errors 

```
2024/03/13 21:06:06 wazuh-db: ERROR: DB(001) sqlite3_prepare_v2() : table sys_osinfo has 20 columns but 19 values were supplied
2024/03/13 21:06:06 wazuh-db: ERROR: (5214): Null statement on internal cache.
```

# DoD 

- [x] Find the root cause of the issue.
- [x] Evaluate, propose and discuss a fix.

**Comment by MiguelazoDS** [comment]
# Update 

Unable to reproduce this behavior installing by sources in Ubuntu Jammy as manager and the same Debian VM as agent. 

The master node logs 

```console
2024/03/13 22:06:14 wazuh-db: ERROR: DB(001) sqlite3_prepare_v2() : table sys_osinfo has 20 columns but 19 values were supplied
2024/03/13 22:06:14 wazuh-db: ERROR: (5214): Null statement on internal cache.
```

The worker node logs 
```console
2024/03/13 21:06:16 wazuh-db: ERROR: DB(002) sqlite3_prepare_v2() : table sys_osinfo has 20 columns but 19 values were supplied
2024/03/13 21:06:16 wazuh-db: ERROR: (5214): Null statement on internal cache.
2024/03/13 21:41:07 wazuh-db: ERROR: DB(000) sqlite3_prepare_v2() : table sys_osinfo has 20 columns but 19 values were supplied
2024/03/13 21:41:07 wazuh-db: ERROR: (5214): Null statement on internal cache.
```

The 002 id may refer to the other agent used in the testing, Windows 11.

I'm not seeing any error in the schema upgrade 13. We have 20 fields for `sys_osinfo` table in 4.7 and for 4.8.0 the `triaged` field was removed. 

The other error is related to delta upsert or delete because the statement is NULL, the cJSON data is NULL or the key value entry that has table info is NULL.

**Comment by sebasfalcone** [comment]
Pending final review, moving ETA
