### ISSUE TITLE
 Discrepancies in vulnerabilities reported for the same environment with 4.7.3 and 4.8.0

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#22518]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.8.0-beta4 | Vulnerability Detector | Manager/Agent | Packages | Ubuntu 22, Windows 11, RHEL 9, Amazon Linux 2023, macOS Sonoma |

## Description

During the testing performed on https://github.com/wazuh/wazuh/issues/22494, it was found that for two identical environments (same clean box), the vulnerabilities reported by Vulnerability Detector in 4.7.3 and 4.8.0 are not the same:

|Box|4.7.3 |4.8.0 |
|---|---|---|
|`ubuntu/jammy64`|[166](https://github.com/wazuh/wazuh/files/14586536/ubuntu_clean_4.7.3_vulns.json)|[7](https://github.com/wazuh/wazuh/files/14590171/ubuntu_clean_4.8.0_vulns.csv) |
|`roboxes/rhel9`|[230](https://github.com/wazuh/wazuh/files/14586828/rhel_clean_4.7.3_vulns.json)|[635](https://github.com/wazuh/wazuh/files/14590160/rhel_clean_4.8.0_vulns.csv) |
| `gbailey/al2023`|[36](https://github.com/wazuh/wazuh/files/14586988/alas23_clean_4.7.3_vulns.json)| [59](https://github.com/wazuh/wazuh/files/14590144/alas23_clean_4.7.3_vulns.csv)|
|macos_1400 (WazuhQAEnviroment)|[105](https://github.com/wazuh/wazuh/files/14601261/macos_clean_4.7.3_vulns.json)|[140](https://github.com/wazuh/wazuh/files/14602784/macos_clean_4.8.0_vulns.csv) | 
| windows_11 (WazuhQAEnviroment)|[561](https://github.com/wazuh/wazuh/files/14601253/win_clean_4.7.3_vulns.json)|[327](https://github.com/wazuh/wazuh/files/14602788/win_clean_4.8.0_vulns.csv)  |

**Comment by sebasfalcone** [comment]
Analyze being performed on:
- https://github.com/wazuh/wazuh/issues/22564
- https://github.com/wazuh/wazuh/issues/22563
- https://github.com/wazuh/wazuh/issues/22562
- https://github.com/wazuh/wazuh/issues/22561
- https://github.com/wazuh/wazuh/issues/22560

**Comment by sebasfalcone** [comment]
Analysis finished
