### ISSUE TITLE
Vulnerability Detection error Vendor map can not be found in DB

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22529]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Vulnerability Detection | Manager | Packages | AlmaLinux 9 |

### Description

Unexpected error in the worker and master node during the vulnerability detection scan of an almalinux endpoint

```
2024/03/14 12:43:13 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing message: Vendor map can not be found in DB.
```

### Steps to replicate

- Deploy an almalinux manager and enable vulnerability detection
- Deploy an almalinux 9 agent and register to the manager
- Check that the error appears after a few minutes

### Evidences

[Master_ossec.log.zip](https://github.com/wazuh/wazuh/files/14612808/Master_ossec.log.zip)

**Comment by Dwordcito** [comment]
@sebasfalcone try to reproduce this consistently. It is probably related to the WAL disabled configuration during transactions.

@Rebits do you have the ossec.log for this?
