### ISSUE TITLE
Windows 11 could not be scanned

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#22521]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0-beta4 | Vulnerability Detector | Agent | Packages| Windows 11|

## Description

During the tests executed for 4.8.0 Beta 4, in https://github.com/wazuh/wazuh/issues/22493, it seems that the operating system could not be scanned correctly, as the following warning appears in the manager logs:

```
2024/03/13 11:03:34 wazuh-modulesd:vulnerability-scanner: WARNING: Failed to scan OS: 'windows_11_22h2', CVE Numbering Authorities (CNA): 'nvd', Error: '[json.exception.out_of_range.403] key 'hotfix' not found'
```

**Comment by MiguelazoDS** [comment]
Found here
https://github.com/wazuh/wazuh/issues/22443

Fixed here
https://github.com/wazuh/wazuh/pull/22482

**Comment by sebasfalcone** [comment]
Closed, as this issue was already fixed
