### ISSUE TITLE
Vulnerability detection error: [json.exception.out_of_range.401] array index 2 is out of range

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22528]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Vulnerability Detection | Manager | Packages | AlmaLinux 9 |

### Description

Unexpected error in the worker and master node during the vulnerability detection scan

```
2024/03/14 12:40:04 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing message: [json.exception.out_of_range.401] array index 2 is out of range
```

### Steps to replicate

- Deploy an almalinux manager and enable vulnerability detection
- Deploy an almalinux 9 agent and register to the manager
- Check that the error appears after a few minutes

**Comment by Dwordcito** [comment]
@sebasfalcone probably related to WAL disable policy.
