### ISSUE TITLE
Test: API

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2253]
# API test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Installation

- [x] Install API in a cluster of two nodes. One of the nodes must be a custom directory install. All agents must report to the worker node.
- [x] Check API status is running in both nodes.

## Configuration

- [x] Custom user, password and https working.

### Certificates and HTTPS

- [x] Install certificates.
- [x] Run query using HTTPS.

### Test mocha

Required tests:

- Agents.
- Decoders.
- Manager.
- Rootcheck.
- Rules.
- Syscheck.
- Syscollector.

Checks:

- [x] Master node:
    - [x] Ubuntu 18 / Python 2.
    - [x] Ubuntu 18 / Python 3.
    - [x] CentOS 7 / Python 2.
    - [x] CentOS 7 / Python 3.
    - [x] CentOS 6 / Python27.

**Comment by bah07** [comment]
About `Check API status is running in both nodes.` at this moment API only works in master node.
