### ISSUE TITLE
Error assigning the groups during agent registration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22530]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Authd/Wazuh-DB | Manager | Packages | AlmaLinux 9 |

### Description

It has been detected during https://github.com/wazuh/wazuh/issues/22452 the following error in the worker node during the registration of an agent:
  
```
2024/03/14 16:00:04 wazuh-db: ERROR: There was an error assigning the groups to agent '001'
2024/03/14 16:00:04 wazuh-db: WARNING: The groups were empty right after the set for agent '001'
```

In cluster logs we can see the following:
``` 
2024/03/14 16:00:04 ERROR: [Worker worker-node] [Agent-groups recv] Wazuh-db response for chunk 1/1 was not "ok": Error 2003 - Error in wazuhdb request: An error occurred during the set of the groups
``` 

### Steps to reproduce
- Deploy a wazuh server cluster
- Deploy a wazuh agent and register to the worker node
- Check in the worker logs that the specified errors appears

### Relates issues:
- https://github.com/wazuh/wazuh/issues/21297
- https://github.com/wazuh/wazuh/issues/16970

**Comment by TomasTurina** [comment]
This is a known issue: https://github.com/wazuh/wazuh/issues/16464

Closing as duplicated.
