### ISSUE TITLE
Test: Wazuh APP

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2254]
# Wazuh App test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Ubuntu

- [x] Clean install.
- [x] Clean install with X-Pack.
- [x] Upgrade install.
- [x] Upgrade install with X-pack.

## CentOS

- [x] Clean install.
- [x] Clean install with X-Pack.
- [x] Upgrade install.
- [x] Upgrade install with X-pack.

**Comment by druizz90** [comment]
I made all the test in Ubuntu. I checked that I can see alerts after upgrade Wazuh from `3.7` to `3.8` (with X-Pack and without X-pack). I found a typo in the documentation which was fixed by App team.

App team are going to make more specific tests.
