### ISSUE TITLE
Windows Server 2019 Scan Error

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22559]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.8.0-beta4 | Vulnerability Detector | Agent | Packages | Windows Server 2019 |

Related to https://github.com/wazuh/wazuh/issues/22467

### Description

During footprints for `4.8.0-beta4`, at https://github.com/wazuh/wazuh/issues/22551, there seems to be a problem scanning `Windows Server 2019`, as the following warning appears in the manager logs:

```console
2024/03/15 00:37:34 wazuh-modulesd:vulnerability-scanner WARNING: Failed to scan OS: 'windows_server_2019', CVE Numbering Authorities (CNA): 'nvd', Error: '[json.exception.out_of_range.403] key 'hotfix' not found'
2024/03/14 02:33:32 wazuh-modulesd:vulnerability-scanner WARNING: Discarded event: Empty response from Wazuh-DB
2024/03/12 17:36:38 wazuh-modulesd:vulnerability-scanner WARNING: The 'feed-update-interval' option at module 'vulnerability-detection' must be at least 1 hour. Automatically set to 60 minutes.
```

**Comment by sebasfalcone** [comment]
Found here
- https://github.com/wazuh/wazuh/issues/22443

Fixed here
- https://github.com/wazuh/wazuh/pull/22482
