### ISSUE TITLE
Test: Azure-logs

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2256]
# Azure module

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

This module collects logs from three Azure APIs (log analytics, graphs and storage).

### Manager (Linux)

- [x] Configure **ossec.conf** to request logs from the three available APIs.
- [x] Check wodle related alerts are being stored in *alerts.json*.
- [x] Try to configure the module in agents. **It should show a descriptive error message.**
- [x] Configure multiple log analytics and graph APIs with multiple requests.
- [x] Configure multiple Storage APIs with multiple containers.

**Comment by Cerv1** [comment]
Hi team,

If we don't have the necessary dependencies installed (like `requests` or `pytz`) the module continues without logging any error but it can't reach any log even though the logs say otherwise as written bellow:

```
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Module started.
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Starting fetching of logs.
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'albertorodriguezwazuh.onmicrosoft.com '.
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for request 'azure-activity'.
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for the domain 'albertorodriguezwazuh.onmicrosoft.com '.
2019/01/11 16:50:53 wazuh-modulesd:azure-logs: INFO: Fetching logs finished.
```

Best regards,
Cerv1
