### ISSUE TITLE
Analyze the behavior of the new VD on MacOS Sonoma

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#22563]
## Description:
The objective of this issue is to analyze the behaviour of the new VD on MacOS Sonoma. We need to validate if we correctly identified:
- Non-vulnerable CVEs
- Vulnerable CVEs

Use 4.7.3 as a guide but always validate against the actual feed:

|Box|4.7.3 |4.8.0 |
|---|---|---|
|macos_1400 (WazuhQAEnviroment)|[105](https://github.com/wazuh/wazuh/files/14601261/macos_clean_4.7.3_vulns.json)|[140](https://github.com/wazuh/wazuh/files/14602784/macos_clean_4.8.0_vulns.csv) |

## Conclusion:

- Non-vulnerable CVEs
  - Status:
- Vulnerable CVEs
  - Status:

**Comment by Dwordcito** [comment]
close not planned, QA team will be continue with this analysis.
