### ISSUE TITLE
Vulnerability Detector module is enabled at the start of the stress test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22565]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Wazuh component | Manager | Packages | CentOS |

During the testing in [Release 4.8.0 - Beta 4 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/22550#top) some warnings related to the vulnerability scanner module have been encountered. After checking the configuration, the vulnerability detection module is disabled but in manager logs we see this module is enabled for a few minutes:

```console
2024/03/12 17:33:10 wazuh-modulesd:vulnerability-scanner: INFO: Starting vulnerability_scanner module.
...
2024/03/12 17:36:19 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module is disabled
```

This happens because at the beginning of the test, it is taking a default Wazuh configuration from a template, which is producing these logs and warnings at the start of the test. 

It significantly impacts the results of the stress tests.

**Comment by rauldpm** [comment]
From `Release testing` to `Very high impact bugs`

This fix will affect the stress test results, we should consider moving it to 4.9.0 instead of 4.8.2
