### ISSUE TITLE
Analyze the behavior of the new VD on AL2023

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#22562]
## Description:
The objective of this issue is to analyze the behaviour of the new VD on AL2023. We need to validate if we correctly identified:
- Non-vulnerable CVEs
- Vulnerable CVEs

Use 4.7.3 as a guide but always validate against the actual feed:

|Box|4.7.3 |4.8.0 |
|---|---|---|
| `gbailey/al2023`|[36](https://github.com/wazuh/wazuh/files/14586988/alas23_clean_4.7.3_vulns.json)| [59](https://github.com/wazuh/wazuh/files/14590144/alas23_clean_4.7.3_vulns.csv)|

## Conclusion:

- Non-vulnerable CVEs
  - Status:
- Vulnerable CVEs
  - Status:

**Comment by Dwordcito** [comment]
close not planned, QA team will be continue with this analysis.
