### ISSUE TITLE
Test: Cluster

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2257]
# Cluster test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Installation

- [x] Installation by default: Run `/var/ossec/bin/wazuh-clusterd -f`
- [x] Installation by default: Run `python3 /var/ossec/bin/wazuh-clusterd -f`
- [x] Installation by default - centos6: Run `/var/ossec/bin/wazuh-clusterd -f`

## Configuration

- [x] Python 2:
    - [x] Configure cluster: No key.
    - [x] Configure cluster: Wrong key.
    - [x] Configure cluster: Wrong node type.
    - [x] Configure cluster: Wrong master node IP.
- [x] Python 3:
    - [x] Configure cluster: No key.
    - [x] Configure cluster: Wrong key.
    - [x] Configure cluster: Wrong node type.
    - [x] Configure cluster: Wrong master node IP.

## Cluster

- [x] Python 2:
    - [x] Start the master before/after the clients.
    - [x] Change path to opt in master and var in clients.
    - [x] Synchronization process when one of the clients is down.
    - [x] Stop master and start it after some time.
    - [x] Disconnect worker node internet connection and check it disconnects after 2 minutes. Check the master node removes that node. Connect the node to the internet again and check it reconnects to the master node without restarting (https://github.com/wazuh/wazuh/pull/1482).
    - [x] Disconnect worker and reconnect it again to the internet in less than 2 minutes. Check it keeps working as usual (https://github.com/wazuh/wazuh/pull/1482).
    - [x] File level tests: Run automatic tests and review KO files.
- [x] Python 3:
    - [x] Start the master before/after the clients.
    - [x] Change path to opt in master and var in clients.
    - [x] Synchronization process when one of the clients is down.
    - [x] Stop master and start it after some time.
    - [x] Disconnect worker node internet connection and check it disconnects after 2 minutes. Check the master node removes that node. Connect the node to the internet again and check it reconnects to the master node without restarting (https://github.com/wazuh/wazuh/pull/1482).
    - [x] Disconnect worker and reconnect it again to the internet in less than 2 minutes. Check it keeps working as usual (https://github.com/wazuh/wazuh/pull/1482).
    - [x] File level tests: Run automatic tests and review KO files.

## Cluster control
- [x] Master
    - [x] Python 2:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
    - [x] Python 3:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
- [x] Worker
    - [x] Python 2:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`
    - [x] Python 3:
        - [x] check `cluster_control -l`
        - [x] check `cluster_control -a`
        - [x] check `cluster_control -i`

## Agents

- [x] Python 2:
    - [x] Register an agent in master and point it to a client.
    The *client.keys* must be propagated and the agent must be reporting. Then, if the agents are listed in the master, it must be Active.
    - [x] `cluster-control -a` must show the agents information and the manager.
    - [x] Connect the previous agent to a different client and review logs/alerts. It must be transparent for the user.
    - [x] Remove an agent in master. It must be removed in all the clients.
- [x] Python 3:
    - [x] Register an agent in master and point it to a client.
    The *client.keys* must be propagated and the agent must be reporting. Then, if the agents are listed in the master, it must be Active.
    - [x] `cluster-control -a` must show the agents information and the manager.
    - [x] Connect the previous agent to a different client and review logs/alerts. It must be transparent for the user.
    - [x] Remove an agent in master. It must be removed in all the clients.

## Groups

- [x] Python 2:
    - [x] Create a new group.
    - [x] Create a file in a group.
    - [x] Modify a file in a group.
    - [x] Remove a file in a group.
    - [x] Remove group.
    - [x] Re-create a removed group.
    - [x] Assign agent to a group.
    - [x] Unassign agent group.
    - [x] Assign a group in a client using md5. Then, check if it is propagated to the master.
- [x] Python 3:
    - [x] Create a new group.
    - [x] Create a file in a group.
    - [x] Modify a file in a group.
    - [x] Remove a file in a group.
    - [x] Remove group.
    - [x] Re-create a removed group.
    - [x] Assign agent to a group.
    - [x] Unassign agent group.
    - [x] Assign a group in a client using md5. Then, check if it is propagated to the master.

## Ruleset

- [x] Python 2:
    - [x] Modify a file in the rules/decoders/lists directory.
    - [x] Add a file in the rules/decoders/lists directory.
    - [x] Remove a file in the rules/decoders/lists directory.
- [x] Python 3:
    - [x] Modify a file in the rules/decoders/lists directory.
    - [x] Add a file in the rules/decoders/lists directory.
    - [x] Remove a file in the rules/decoders/lists directory.

## Performance

- [x] Python 2:
    - [x] 1 master, 10 clients, 100k agent-info and agent-groups.
- [x] Python 3:
    - [x] 1 master, 10 clients, 100k agent-info and agent-groups.

**Comment by juan70** [comment]
On CentOS 6, although having installed Python2.7 as explained in the docs (https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html?running-the-cluster-in-centos-6): 
```
# /var/ossec/bin/wazuh-clusterd -f
Error starting wazuh-clusterd: Error starting wazuh-clusterd. Minimal Python version required is 2.7. Found version is 2.6
```
Python 2.7 is not in the path (neither after rebooting the machine).

**Comment by juan70** [comment]
Couldn't make work the following points, unless it's something related to the VM used:
  - Disconnect worker node internet connection and check it disconnects after 2 minutes. Check the master node removes that node. Connect the node to the internet again and check it reconnects to the master node without restarting (#1482).

Using `ip link set eth2 down` on the worker, the connection with the worker is closed after a couple of minutes: if the worker's IP is xxx.xxx.56.107, the closed connection is xxx.xxx.56.1.
In `cluster.log`:
```
2019-01-10 15:44:57,338 ERROR   : [Master ] Error accepting connection from 192.168.56.1: Incoming connection from '192.168.56.1' rejected: There is already a node with the same ID ('node02') connected.
2019-01-10 15:44:57,339 INFO    : [Master ] Connection with 192.168.56.1 closed.
```

  After `ip link set eth2 up`, the message changes to:
```
2019-01-10 15:46:41,828 ERROR   : [Master ] Error accepting connection from 192.168.56.107: Incoming connection from '192.168.56.107' rejected: There is already a node with the same ID ('node02') connected.
2019-01-10 15:46:41,829 INFO    : [Master ] Connection with 192.168.56.107 closed.
```
  The connection is reestablished only if the master is restarted:
```
2019-01-10 15:49:31,493 INFO    : [Master ] Connection with 192.168.56.107 closed.
2019-01-10 15:49:41,720 INFO    : [Master ] Exiting. Reason: 'Signal [15-Terminated] received.'.
2019-01-10 15:49:44,642 WARNING : [Master ] Cleaning 'API_Requests_Thread' thread. Timeout.
2019-01-10 15:49:47,874 INFO    : [Master ] PID: 30999
2019-01-10 15:49:47,875 INFO    : [Master ] Listening '0.0.0.0:1516'.
2019-01-10 15:49:47,885 INFO    : [Master ] [LocalServer  ]: Ready.
2019-01-10 15:49:57,673 INFO    : [Master ] [node02]: Connected.
```

**Comment by cristgl** [comment]
Hello @juan70,

I have just configured the cluster on CentOS 6 following the steps at the documentation, the cluster is enabled and I can also check this node's state at the master node, also connected and sending the 'keep alive'.

```
[root@centos6 vagrant]# service wazuh-manager restart
Stopping OSSEC:                                            [  OK  ]
Starting OSSEC (EL6):                                      [  OK  ]
[root@centos6 vagrant]# ps aux | grep cluster
ossec    19194  0.6  4.2 529224 21272 ?        Sl   10:30   0:00 python /var/ossec/bin/wazuh-clusterd
root     19221  0.0  0.1 103340   904 pts/0    R+   10:30   0:00 grep cluster
```

I think yours is failing because Python 2.6 is the one enabled by default at the shell, and running the command `/var/ossec/bin/wazuh-clusterd -f` will execute it with that version. You can enable Python 2.7 with the command `scl enable python27 bash`.

**Comment by mgmacias95** [comment]
Hello @juan70,

I have made the test you mentioned in your comment.

This is the cluster control output before turning down the network interface:
```shellsession
# /var/ossec/bin/cluster_control -l
---------------------------------------
Name      Address       Type    Version
---------------------------------------
master    172.17.0.100  master  3.8.0
worker-1  172.17.0.101  worker  3.8.0
---------------------------------------
```

Then, after turning down the network interface I see this log in the worker (after waiting for 2 minutes):
```
2019-01-14 08:52:01,993 ERROR   : [Worker ] [KeepAlive-S  ] Error sending keep alive to master (2): Timeout expired while waiting for a response
2019-01-14 08:52:01,993 CRITICAL: [Worker ] [KeepAlive-S  ] Maximum failed attempts exceeded. Disconnecting worker.
2019-01-14 08:52:02,497 INFO    : [Worker ] Disconnected.
2019-01-14 08:52:02,498 ERROR   : [Worker ] [KeepAlive-S  ]: Result: Error
2019-01-14 08:52:02,498 INFO    : [Worker ] [KeepAlive-S  ]: End. Sleeping: 60s.
2019-01-14 08:52:02,951 ERROR   : [Worker ] Disconnected. Trying to connect again in 10s.
2019-01-14 08:52:05,540 WARNING : [Worker ] Cleaning 'API_Requests_Thread' thread. Timeout.
2019-01-14 08:52:15,556 INFO    : [Worker ] Connecting to 172.17.0.100:1516.
2019-01-14 08:52:15,557 INFO    : [Worker ] Connected.
2019-01-14 08:52:17,557 INFO    : [Worker ] [Integrity-S  ]: Start.
2019-01-14 08:52:17,557 INFO    : [Worker ] [Integrity-S  ]: Asking permission to sync.
2019-01-14 08:52:17,558 INFO    : [Worker ] [AgentInfo-S  ]: Start.
2019-01-14 08:52:17,558 INFO    : [Worker ] [AgentInfo-S  ]: Asking permission to sync.
2019-01-14 08:52:17,558 INFO    : [Worker ] [KeepAlive-S  ]: Start.
2019-01-14 08:52:17,562 INFO    : [Worker ] [Integrity-S  ]: Permission granted.
2019-01-14 08:52:17,563 INFO    : [Worker ] [AgentInfo-S  ]: Permission granted.
```

And this is the cluster control output after that:
```shellsession
# /var/ossec/bin/cluster_control -l
---------------------------------------
Name      Address       Type    Version
---------------------------------------
master    172.17.0.100  master  3.8.0
worker-1  172.17.0.1    worker  3.8.0
---------------------------------------
```

That means the worker restarted itself to reconenct to the master using a different network interface.

Best regards,
Marta

**Comment by juan70** [comment]
For the Python 2 part, the file level test fails.
On the master node, installed in `/opt/ossec` from sources:
```
# python test_cluster_sync.py -m -p /opt/ossec
Executing test for MASTER node...
/etc/
 - Modified 'client.keys' (shared).
/etc/shared/
 - Created directory '/opt/ossec/etc/shared/tests' (missing).
 - Created file '/opt/ossec/etc/shared/tests/merged.mg' (missing).
/etc/rules/
 - Created directory '/opt/ossec/etc/rules/test_rules' (missing).
 - Created file '/opt/ossec/etc/rules/test_rules/test_rule' (missing).
 - Removed file '/opt/ossec/etc/rules/local_rules.xml' (extra).
   (*) Note: There are only one rule and one decoder, the rule is deleted and the decoder is modified.
/etc/decoders/
 - Created directory '/opt/ossec/etc/decoders/test_decoders' (missing).
 - Created file '/opt/ossec/etc/decoders/test_decoders/test_decoder' (missing).
 - Modified file '/opt/ossec/etc/decoders/local_decoder.xml' (shared).
/etc/lists/
 - Created directory '/opt/ossec/etc/lists/tests_lists' (missing).
 - Created file '/opt/ossec/etc/lists/tests_lists/test_file' (missing).
 - Removed directory '/opt/ossec/etc/lists/amazon/' and his content (extra).
```
On the worker node, installed in `/var/ossec` from packages, after waiting a couple of minutes in order to be sure that the data are synchronized on the workers:
```
# python test_cluster_sync.py -c 'master'
Checking missing and shared files...
/etc/shared/
 - Directory '/var/ossec/etc/shared/tests' doesn't exist (X).
 - File '/var/ossec/etc/shared/tests/merged.mg' doesn't exist (X).
/etc/rules/
 - Directory '/var/ossec/etc/rules/test_rules' doesn't exist (X).
 - File '/var/ossec/etc/rules/test_rules/test_rule' doesn't exist (X).
 - File '/var/ossec/etc/rules/local_rules.xml' doesn't exist (OK).
/etc/decoders/
 - Directory '/var/ossec/etc/decoders/test_decoders' doesn't exist (X).
 - File '/var/ossec/etc/decoders/test_decoders/test_decoder' doesn't exist (X).
/etc/lists/
 - Directory '/var/ossec/etc/lists/tests_lists' doesn't exist (X).
 - File '/var/ossec/etc/lists/tests_lists/test_file' doesn't exist (X).
```

The modified `client.keys` file is correctly propagated to the worker, including the change.

Weird behaviour:
- When a file is created in `/opt/ossec/etc/rules` (or `decoders`, or `lists`), it appears automatically on workers after a short while. OK.
- When the file is removed, it is also removed from the workers. OK.
- When a directory containing a file is created in `/opt/ossec/etc/rules`, it is created on the workers. OK.
- When the directory is removed, it is not removed from the workers. FAIL?
- The same applies if the master is installed in `/var/ossec`.

Maybe the utility `test_cluster_sync.py` does not work completely as expected.
(I had to modify a bit the script locally to make it work on any path, be it `/var/ossec` or `/opt/ossec`, because some functions are called without parameters, and the path by default is `/var/ossec`.)

**Comment by juan70** [comment]
As for the `Disconnect ...` tests. Maybe I wasn't being patient enough. I have tried again and it works.

Initial settings:
```
# cluster_control -l
---------------------------------------
Name    Address         Type    Version  
---------------------------------------
node01  192.168.56.113  master  3.8.0    
node02  192.168.56.107  worker  3.8.0    
node03  192.168.56.102  worker  3.8.0    
---------------------------------------
```

Switching off the network device on node02 using `ip link set eth2 down`, this worker is disconnected from the master after two minutes.
In master's cluster.log:
```
2019-01-14 10:49:54,771 CRITICAL: [Master ] [WorkerChecks] [node02]: Last keep alive is higher than allowed maximum. Disconnecting.
```
A bit later, the worker connects through another IP:
```
# cluster_control -l
---------------------------------------
Name    Address         Type    Version  
---------------------------------------
node01  192.168.56.113  master  3.8.0    
node02  192.168.56.101  worker  3.8.0    
node03  192.168.56.102  worker  3.8.0    
---------------------------------------
```
(No device on node02 has this IP.)

When the network device is brought up again using `ip link set eth2 up`, after a while, and after several synchronization requests from the worker to the master, the original IP 192.168.56.107 is seen again.

When the network device is brought down and up within a less than two minutes, the connection is immediately reestablished with the same IP.

So the tests seem OK.
