### ISSUE TITLE
Would like to have underscore support in new versions

### ISSUE THREAD

**Issue by slavaNBA** [wazuh/wazuh#22575]
It would be great top have an ability tio use both dot and underscore in indexes.
For example: wazuh.allerts turns into wazuh_allerts
agent.id string urns into agent_id

**Comment by vikman90** [comment]
Hi @slavaNBA, take a look at the new engine development:

- #11334

Where we're defining a list of fields using dots as you're suggesting:

https://github.com/wazuh/wazuh/blob/e07be190611d2c110623269c778f6e75acc005d0/src/engine/ruleset/schemas/engine-schema.json#L6640-L6643

([engine-schema.json](https://github.com/wazuh/wazuh/blob/11334-dev-new-wazuh-engine/src/engine/ruleset/schemas/engine-schema.json))

Best regards.
