### ISSUE TITLE
Increase in Disk_Read by Wazuh-syscheckd

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22601]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Wazuh Manager | Manager | Packages | CentOS |

During testing in [Release 4.8.0 - Beta 4 - Footprint Metrics - MACOS-SOLARIS (2.5d)](https://github.com/wazuh/wazuh/issues/22556) it has been detected an increase in Disk_Read by Wazuh-syscheckd. This behavior has not been detected in previous versions, but it has been detected in [4.8.0 Beta 3](https://github.com/wazuh/wazuh/issues/22354), although it had not been reported since footprint was not analyzed at that stage. An increase in Wazuh-modulesd can also be seen but this is already reported in this issue https://github.com/wazuh/wazuh/issues/22566

The plots are compared to https://github.com/wazuh/wazuh/issues/22314.

| 4.8.0 | 4.7.3 |
| --- | --- | 
| ![image](https://github.com/wazuh/wazuh/assets/101177239/c7e079fb-f928-4b7a-a1dc-1ab6f16b3e8b) |  ![image](https://github.com/wazuh/wazuh/assets/101177239/168aafdb-c3ca-4e12-813b-19c5f34a19bb) | 

4.8.0 - Beta 3 plot:
![image](https://github.com/wazuh/wazuh/assets/101177239/56564586-3a32-4f65-9f1b-ca48ce3e6848)

**Comment by nbertoldo** [comment]
# Issue update

I have started by analysing the test reports, where the following can be seen:

## 4.7.3

Both the graph and the CSV file show that the disk read value remains at zero from the start until `3/2/2024 11:27:28`. Then it starts to increase to a value of `28*10e6`. 

<details><summary>Graph</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/83185083-be5f-495b-9bd8-47db5a5b6647)

</details> 

<details><summary>CSV file</summary>

![Captura desde 2024-03-25 17-49-34](https://github.com/wazuh/wazuh/assets/117279646/c55e2b3c-d686-48f8-90dc-f846d1b20072)

![Captura desde 2024-03-25 17-55-20](https://github.com/wazuh/wazuh/assets/117279646/7d389193-bb46-44b7-ac22-3448e030b295)

</details> 

## 4.8.0

In both `beta3` and `beta4` the initial value remains almost constant from the beginning to the end of the test. In both cases this value is much higher than in `4.7.3`. 
- `525*10e6` for `beta3` 
- `265*10e6` for `beta4`.

### Beta 3
<details><summary>Graph</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/9f05abc9-3c74-45d4-8094-a59bc06bcbd7)

</details> 

<details><summary>CSV file</summary>

![Captura desde 2024-03-25 18-26-05](https://github.com/wazuh/wazuh/assets/117279646/176c3c52-adf1-4291-963e-a3fb4ba6121c)

</details> 

### Beta 4
<details><summary>Graph</summary>

![image](https://github.com/wazuh/wazuh/assets/117279646/e85ebb65-6c9d-43e9-80c3-d3f6c15d2a43)

</details> 

<details><summary>CSV file</summary>

![Captura desde 2024-03-25 18-30-38](https://github.com/wazuh/wazuh/assets/117279646/2c6d0056-62d2-4e6f-9c8e-465e9635fffc)

</details> 

Something to note is that in all cases, the `syscheck` curve follows the same pattern as `modulesd`, so they are probably related. I will continue with the further analysis.

**Comment by nbertoldo** [comment]
As reported in #22565, Vulnerability Detector is enabled when the test starts (default configuration) and this affects `modulesd` disk read values. 
Although I can't find the relationship, based on the graphs of various tests I've reviewed, this seems to be affecting `syscheck` as well.

Since the `disk read` value is cumulative, we can calculate the difference between the initial and final values :

Module | Version | Initial value | Final value | Difference
-- | -- | -- | -- | --
syscheck | 4.7.3 | 0 | 27963392 | 27963392
  | 4.8.0 - Beta3 | 525189120 | 527110144 | 1921024
  | 4.8.0 - Beta4 | 265097216 | 267681792 | 2584576
modulesd | 4.7.3 | 0 | 12783616 | 12783616
  | 4.8.0 - Beta3 | 106254336 | 127107072 | 20852736
  | 4.8.0 - Beta4 | 146331136 | 167421440 | 21090304

And we can see the following:
- **syscheck:** the value decreases considerably for 4.8.0, being less than 10% of the value in 4.7.3.
- **modulesd:** the value increases by 65% in 4.8.0.

Therefore I propose to re-launch the test with the appropriate configuration so that the Vulnerability detector does not affect the measurement.

**Comment by vikman90** [comment]
I think that comparing the _read_ops_ value would be more accurate, as `read_bytes` implies the storage layer:

|proc|psutil|Meaning|
|--|--|--|
|rchar|:x:|Bytes requested to read|
|wchar|:x:|Bytes requested to write|
|syscr|read_ops|Calls to `read`|
|syscw|write_ops|Calls to `write`|
|read_bytes|read_bytes|Bytes effectively read from the storage layer|
|write_bytes|write_bytes|Bytes effectively written to the storage layer|

Please consider comparing _read_ops_:

|4.7.3|4.8.0|
|--|--|
|![](https://camo.githubusercontent.com/9b77e4e41507183fa60377c6a9fb9e17d088d04e68db30af9437ed452eaa01f6/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e372e332f423230322d333630306d2f423230325f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423230325f6d616e616765722d7072652d72656c656173655f526561645f4f70732e706e67)|![](https://camo.githubusercontent.com/8a5a6826df43fec4afe042551455a5f77dd802f5eb6ba68185df9dddbcb45c3d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573735f56616772616e742f7072652d72656c656173652f342e382e302f423230342d333630306d2f423230345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f56616772616e745f423230345f6d616e616765722d7072652d72656c656173655f526561645f4f70732e706e67)|

## Conclusion

I don't think this represent an issue in the product.
