### ISSUE TITLE
Disk read increased for syscollector test in 4.8.0-beta4

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22600]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta4 | Syscollector | Manager | Packages | centOS 7 |

### Description

During the investigation of https://github.com/wazuh/wazuh/issues/22547, it has been observed that disk reads are occurring across all modules. This behavior appears to have been altered since version 4.8.0 alpha1.

| 4.8.0 | 4.7.3 |
| --- | --- | 
| ![IMAGE](https://camo.githubusercontent.com/677d283fe80c563fecb771c96cc492ff6dcad486bb0f075f8bc8e92f01427b07/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343934392d333630306d2f42343934395f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343934395f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) | ![IMAGE](https://camo.githubusercontent.com/d2e2454dc72be6c694e87e9f7be6effa2573c5286fb07d7029e4c7fb81839a72/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930382d333630306d2f42343930385f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930385f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67) |

**Comment by sebasfalcone** [comment]
This test should be repeated in 4.7.3

It is not possible that 0 disk reads were performed:
- Wazuh-db
- Syscollector
- Logcollector

All of those modules should report some disk reads

**Comment by Rebits** [comment]
I reopened this issue due to the zero disk read behavior does not occur only in 4.7.3 but in all the previous footprint tests:
- [4.7.0](https://github.com/wazuh/wazuh/issues/20055)
- [4.6.0](https://github.com/wazuh/wazuh/issues/19551)
- [4.5.3](https://github.com/wazuh/wazuh/issues/19498)

***

> All of those modules should report some disk reads

Logcollector is not enabled in this test. However, the wazuh-db and the syscollector indeed should report disk read. Further research is required

**Comment by sebasfalcone** [comment]
Hi @Rebits!

Given that 4.8.0 didn't present changes on the syscollector module or the associated configurations, I have a question:
- Did the tests or configurations associated change in some way?

**Comment by rafabailon** [comment]
## Update

I've reviewed the changes in v4.8.0-alpha1 and there doesn't seem to be anything relevant that could have caused the change. The next step is to create a local environment similar to the one used in Footprints and pass the tests to be able to manually check if there is activity on the disk or not.

**Comment by rafabailon** [comment]
## Update

Hi @sebasfalcone,

I have reviewed the [pipeline code](https://github.com/wazuh/wazuh-jenkins/blob/v4.8.0-beta5/jenkins-files/tests/test_stress.groovy) again along with the [scripts](https://github.com/wazuh/wazuh-jenkins/blob/v4.8.0-beta5/quality/tests/stress/playbooks/launch_test.yml) that runs the pipeline. There are some changes in the pipeline but nothing that justifies a change in performance. They are, basically, refactoring. The scripts, for their part, have not changed. The most recent commits are from 7 months ago.

I have tried setting up a local environment with a manager (centos) and an agent (ubuntu). I have run the Footprint scripts and monitored the system resources.

In 4.7.3 there is less activity than in 4.8.0. I have checked the memory usage, CPU usage and disk operations.

<details>
  <summary>4.7.3</summary>
  <br/>

![image](https://github.com/wazuh/wazuh/assets/54536265/9b01a4df-43f3-44c4-ae8c-da9658d4a3ce)

![image](https://github.com/wazuh/wazuh/assets/54536265/fefef9ad-5db4-46d5-bdd2-226fb0398e34)

![image](https://github.com/wazuh/wazuh/assets/54536265/9bf0f82d-175d-49e0-9a1d-07ade0c72dda)

</details>

<details>
  <summary>4.8.0</summary>
  <br/>

![image](https://github.com/wazuh/wazuh/assets/54536265/71d5cba5-5673-4a8d-92c6-406ae9f5d186)

![image](https://github.com/wazuh/wazuh/assets/54536265/6ef162a5-5e20-406d-bef7-8254dfaebec2)

![image](https://github.com/wazuh/wazuh/assets/54536265/a25e62c8-14fb-433c-8ba4-0f6abb5dcd48)

</details>

In 4.7.3 I have only occasionally seen almost negligible disk read access. In 4.8.0 there is reading and writing activity in addition to the rest of the processes having greater activity. I have also tried increasing the load but the result is the same.

**Comment by sebasfalcone** [comment]
It won't be possible for us to analyse this issue further, we still believe that is not possible that 0 disk reads are performed over the use of the module, just reading the configuration files should have some impact on this metric

Also, in the images shown we don't see `modulesd` on the list which is the one required for us to analyse

I will close this issue, please re-open it when comparable metrics of `modulesd` are obtained

**Comment by sebasfalcone** [comment]
EDPS are 0 on the tests performed on 4.7.3:

![image](https://github.com/wazuh/wazuh/assets/34063881/233d22e3-5714-4444-855c-60333d12b99f)

![image](https://github.com/wazuh/wazuh/assets/34063881/609017d7-7a72-44c2-b8c6-14160c62cc33)

This could explain this behaviour
