### ISSUE TITLE
Issue with CIS Script for Ubuntu 22.04 on SCA Scan.

### ISSUE THREAD

**Issue by sakib789** [wazuh/wazuh#22614]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | SCA | Manager/Agent | - | Ubuntu 22.04 |

Hi Team,

While working with this [community](https://github.com/wazuh/community/issues/21265), I've observed an issue with the CIS script for Ubuntu 22.04 on the SCA scan, where it is not functioning correctly, specifically with control 28561, which checks for the presence of Samba. Even when Samba is not installed, the scan marks this control as failed.

For clarity, I've attached some screenshots illustrating the problem. 
![image](https://github.com/wazuh/wazuh/assets/67746422/d7549c91-f5d3-4054-9af7-36e11583bf87)
![image](https://github.com/wazuh/wazuh/assets/67746422/d0ce96e1-e476-4900-9f17-172aa6b99c50)
![image](https://github.com/wazuh/wazuh/assets/67746422/de623154-8699-4183-b482-a414216a5323)

This issue has also been reported by other users, as documented [here](https://github.com/wazuh/wazuh/issues/21622)

Although I've noticed some changes in the upcoming v4.8 update, it seems that the modifications don't address the concerns related to Samba (28561) and ufw (28575). You can view the details of these updates here:

[Pull Request](https://github.com/wazuh/wazuh/pull/17515)
[Commit](https://github.com/wazuh/wazuh/commit/4c840d4619aedd7890cf49ebe7befd6ab631d23f) 
Additionally, I noticed a typo in the section regarding [Samba](https://github.com/wazuh/wazuh/commit/4c840d4619aedd7890cf49ebe7befd6ab631d23f#diff-5f2bfc5c68ab43291f29308cbd47c26d64f82dda1802493e65c35ae0335d0695L1504).

Typo:
   
     - "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching sambad|deinstall|not-installed"

Correct:
   
     - "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching samba|deinstall|not-installed"
     
After correcting the typo on the command the policy check works fine for the Samba (control ID 28561)

I kindly request a review of the policy file and urge for necessary updates to fix this issue promptly.

**Comment by Johnng007** [comment]
The Typo error has been fixed. Albeit the default rule in Wazuh version 4.7.3 works
![image](https://github.com/wazuh/wazuh/assets/30580457/9a3bb69e-307b-4cef-9a93-6a364eef7c31)

within the check we have two rules:
```
    condition: all
    rules:
      - "c:dpkg-query -s samba -> r:package 'samba' is not installed"
      - "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching samba|deinstall|not-installed"
```

The first rule checks if samba is installed using dpkg-query with the -s command to get status of package by name
`dpkg-query -s samba`
The second rule uses the -W "show" and -f "format" options to retrieve further information on the package status.
`dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba`

Expected Output: `samba	unknown ok not-installed	not-installed`
![image](https://github.com/wazuh/wazuh/assets/30580457/bf407a16-9bf4-4830-91ec-397d0fbe2571)

The typo issue on its own does not cause a fail of the check.
Looking the rule critically:
`dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching samba|deinstall|not-installed`

the SCA engine first matches `no packages found matching samba` there is an OR logic then `deinstall` and another OR logic then `not-installed` 

![image](https://github.com/wazuh/wazuh/assets/30580457/d90396bb-4fd8-4004-a7a7-bb55031d1c08)

For check (28575) ufw

This check confirms if ufw is installed, Active and in running state.
```
    condition: all
    rules:
      - "c:systemctl is-enabled ufw.service -> r:^enabled"
      - "c:systemctl is-active ufw -> r:^active"
      - 'c:ufw status -> r:Status:\s+active'
```
The check will fail if any or all of these is returned not true.

**Comment by IsExec** [comment]
Issue is similar to [this](https://github.com/wazuh/wazuh/issues/21622) and has been addressed [here](https://github.com/wazuh/wazuh/pull/22723)

**Comment by ooniagbi** [comment]
Closing because it is solved by https://github.com/wazuh/wazuh/pull/22723
