### ISSUE TITLE
CDB List Rule sometimes triggers false positive

### ISSUE THREAD

**Issue by MarcosBuslaiman** [wazuh/wazuh#22622]
| Wazuh version  | 
| ------------- | 
| v4.4.1  | 

# Descritption
I have created a CDB list with a list of processes, and I want to trigger alerts when it is executed, but I found that it generates some false positives.
Also, I verified that the rule created is sometimes triggered by using the same log. This happens randomly throughout the day.
We configured the command to run every 40 seconds, and it works okay and uses the CDB List correctly. However, every 4/6 hours, we noted that it triggered false positive alerting of a command that exists on the CDB List, so it should not be triggering the alert.
I note this could be generated when many events are being sent from the agent.

app_whitelisting
```
/var/ossec/bin/wazuh-execd:
/var/ossec/bin/wazuh-logcollector:
/usr/sbin/sshd:
/var/ossec/bin/wazuh-syscheckd:
/usr/sbin/rsyslogd:
/usr/lib/polkit-1/polkitd:
```

We triggered the following rules when the agent reported some of that process.
Configuration of the `agent.conf`:

```
  <agent_config>
    <!-- Application monitoring -->
    <localfile>
      <log_format>command</log_format>
      <command>ps -eo ouid,args --sort=ouid | awk '$2 ~ /^\// { $1=$1; print }'</command>
      <frequency>40</frequency>
      <alias>app_monitoring_vnf1</alias>
    </localfile>
  </agent_config>
```

Here are the Rules:

```
<group name="app_whitelisting,">
    <rule id="104505" level="0">
        <if_sid>530</if_sid> 
        <match>'app_monitoring_vnf1'</match>
		<field name="process.cmd">^/\S+</field>
        <description>App monitoring handle</description>
    </rule>
    <rule id="104506" level="6">
        <if_sid>104505</if_sid>
        <list field="process.cmd" lookup="not_match_key">etc/lists/app_whitelisting_vnf1</list>
        <description>New application detected '$(process.cmd)' owned by '$(process.euser)'</description>
    </rule>  
</group> 
```
CDB list:

```
/var/ossec/bin/wazuh-execd:
/var/ossec/bin/wazuh-logcollector:
/usr/sbin/sshd:
/var/ossec/bin/wazuh-syscheckd:
/usr/sbin/rsyslogd:
/usr/lib/polkit-1/polkitd:
```

```
<decoder name="app_monitoring12">
  <parent>ossec</parent>
  <type>ossec</type>
  <prematch offset="after_parent">output: 'app_monitoring\w*':</prematch>
  <regex offset="after_prematch">\s*\t*(\w+)\s*\t*(\S*)\s*\t*(\.*)</regex>
  <order>process.euser, process.cmd, process.args</order>
</decoder>
```

Compressed logs in debug mode:

[ossec.zip](https://github.com/wazuh/wazuh/files/14672749/ossec.zip)

Thanks!

**Comment by nmkoremblum** [comment]
Hi @MarcosBuslaiman, could you please share some example logs with us?

**Comment by vikman90** [comment]
Possible duplicate: https://github.com/wazuh/wazuh/issues/10671
