### ISSUE TITLE
Unable to locate alert field documentation

### ISSUE THREAD

**Issue by Maspital** [wazuh/wazuh#22632]
Hey,

I am currently working with alert datasets containing several different kind of alerts, some of which happen to be Wazuh alerts.
I hope I did not overlook any resources, but I'm failing to find documentation for the contents of those fields.
Sure, most of their meaning can be inferred, but I'd prefer "knowing" to "guessing". Is there something like a "Field Reference", similar to the concept of [ECS](https://www.elastic.co/guide/en/ecs/8.11/index.html), which covers this?
Or are these fields, like `decoder.ftscomment` or `data.alert.metadata.deployment`, just freely defined?

I found the [Rule Syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html) in the documentation, but that only covers, well, the rules.
And even there, I find myself guessing stuff, like what are frames of references for the different rule levels, what distinguishes a level 11 from a level 13 alert, etc.

Kind regards,
Philipp

**Comment by vikman90** [comment]
Hey @Maspital,

As of the current version, Wazuh supports a very limited set of predefined fields within its alert datasets:

user, srcip, dstip, srcport, dstport, protocol, action, id, url, data, extra_data, status, system_name

- `user`
- `srcip`
- `dstip`
- `srcport`
- `dstport`
- `protocol`
- `action`
- `id`
- `url`
- `data`
- `extra_data`
- `status`
- `system_name`

([Docu: **Traditional decoders**](https://documentation.wazuh.com/current/user-manual/ruleset/decoders/dynamic-fields.html#traditional-decoders))

Beyond these, users have the freedom to define additional fields as needed. We acknowledge that having a comprehensive field reference, akin to the Elastic Common Schema (ECS), would be highly beneficial.

Our team is actively working on a redesign of the engine that aims to propose a coherent list of fields, similar to ECS, to standardize and enhance the understanding and interpretation of alert data. This initiative will provide users like yourself with clearer insights into the meaning and context of various fields within Wazuh alerts.

- #11334

Hope this helps.

Best regards,
