### ISSUE TITLE
CryptAcquireContext error

### ISSUE THREAD

**Issue by taylorwalton** [wazuh/wazuh#22630]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | Wazuh component | Agent | Packages/Sources | Windows 2008 R2 Standard 64bit |

Hey Team,

When attempting to start the Wazuh-Agent service, the service is immediately stopped with the bellow error:

![image](https://github.com/wazuh/wazuh/assets/111797488/a70e64c7-365f-4672-87a3-a060ffac0ba8)

I saw a similar issue related here https://github.com/wazuh/wazuh/issues/1825 but am unsure what was meant by `"The solution is to delete the key. The Wazuh agent will generate a clean key at the next start.". I did delete the `client.key`, registered the agent and then attempted to start the service but the same error message appeared.

I did not have the file path `C:\ProgramData\Application Data\Microsoft\Crypto\RSA\S-1-5-18` that @Skeptor reported in the issue but I did have the below:

![image](https://github.com/wazuh/wazuh/assets/111797488/fe1418c9-480c-4155-8157-e48740acc343)

Please let me know your thoughts and any recommended further troubleshooting steps.

Thanks for your help! 

Best Regards,
Taylor

**Comment by pereyra-m** [comment]
Hello @taylorwalton !

This is the section of code that is printing the error
https://github.com/wazuh/wazuh/blob/dabf627a2f2d668f389459aec7b2d339ef9629ed/src/shared/randombytes.c#L30-L35

The Wazuh agent performs some cryptographic operations and this Windows function is required.
When a default container can't be accessed, here are some reasons

https://learn.microsoft.com/en-us/troubleshoot/windows-server/certificates-and-public-key-infrastructure-pki/cryptacquirecontext-troubleshooting#cryptacquirecontext-errors
> NTE_BAD_KEYSET (0x80090016)
> - Key container does not exist.
> - You do not have access to the key container.
> - The Protected Storage Service is not running.

After this error, the container is tried to be created, but it also fails

> NTE_EXISTS (0x8009000F)
The key container already exists, but you are attempting to create it. If a previous attempt to open the key failed with NTE_BAD_KEYSET, it implies that access to the key container is denied.

It seems that the Wazuh agent can't access the default container, maybe it was created by another user, or the same user with a different password, the permissions of the file have changed, etc.

The issue you mention suggests removing the file from the `Microsoft\Crypto\RSA\S-1-5-18` folder (not `client.keys` from the agent), but there are many keys stored there used by other applications. Only the one used by Wazuh must be deleted, the agent will re-create it by itself.

We can determine this using a Windows tool called Process Monitor
https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

We need to create two filters:
- Process name contains Wazuh
- Path contains S-1-5-18

And disable the registry activity.
This way, the key used by Wazuh will be identified. You can then stop the agent and safely delete it

![2024-05-13_20-22](https://github.com/wazuh/wazuh/assets/65046601/8ea8970a-51a0-4ef0-8034-e6ffa25d4ce3)

Don't hesitate to ask for more details about any step of the process described above.
Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
