### ISSUE TITLE
Distinguish between affected resources from Security Hub findings

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#22641]
## Description

After the development to process Security Hub findings and insights carried out in #21166, it was found during the rules creation process, that the `Resources` field part of the fetched finding in `Security Hub Findings - Imported` and `Security Hub Findings - Custom Action` events contains a list that potentially could have up to 32 resource objects according to the [documentation](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-resources.html).

Therefore, this issue aims to analyze and apply the necessary changes to the development to have the `Resources` objects differentiated so that users can create rules that match those processed fields and are not simply an array containing them.

The first proposal is to divide the `Resources` field into multiple `Resource_X` ones, being `X` a number to differentiate between resource objects.

The following items should be analyzed and considered:
- The modifications should not break current functionalities and will be only limited to findings from `Security Hub Findings - Imported` and `Security Hub Findings - Custom Action` events.
- The resource objects should be part of a single event and not divided into multiple ones.
- How the rules will match with these `Resource_X` fields.
- How the indexer will identify the `Resource_X` fields and their type.

In case the first proposal should be discarded, this issue can be used to determine other ones.

**Comment by Selutario** [comment]
After discussing this with @havidarou, we decided not to apply any changes and keep any lists of dictionaries as they are, without unnesting.
