### ISSUE TITLE
VD state field publication and detection date changes

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#22649]
As part of the new VD state index, two changes must be made to the information:

- The current `@timestamp` field must be renamed to `vulnerability.detected_at`. This is a date type of field.
- Add a new date field named `vulnerability.published_at` that refers to the date the vulnerability was published.

**Comment by Dwordcito** [comment]
Related to https://github.com/wazuh/wazuh/pull/22611, @sebasfalcone Do this in parallel to save time.
