### ISSUE TITLE
Add user agent to VD CTI client 

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh#22659]
## Description

To ensure we're in compliance with HTTP standards, we want to add the User-Agent header in our requests from VD to services like CTI.

The RFC 9110 contains the latest definition of valid User-Agents: 

https://www.rfc-editor.org/rfc/rfc9110#name-user-agent

Example:

`User-Agent: Wazuh VulnerabilityDetector/4.8.0`
 
We need to design a user agent string which make sense for our present and future use cases.

**Comment by Damian-Mangold** [comment]
Bloqued by

- https://github.com/wazuh/wazuh/issues/22720

**Comment by tsarquis88** [comment]
# Update

Base implementation finished on #22780.

There is a problem with the version of http-request that the Github Actions workflow is using, as it doesn't have the user agent feature.

**Comment by tsarquis88** [comment]
# Update

After resolving the Actions' problem, PR ready to review.
