### ISSUE TITLE
Wazuh Docker LDAP

### ISSUE THREAD

**Issue by imgecod** [wazuh/wazuh#22651]
Hello,

I'm seeking assistance with my Wazuh setup.

I've installed it in standalone mode using Docker, following the official documentation.

Now, I'm attempting to integrate LDAP authentication, but I'm unsure of the steps to take.

I initially attempted with OpenSearch, but encountered difficulties.

Could anyone offer some guidance, please?

**Comment by imgecod** [comment]
I will close the issue
I found a solution

**Comment by RostKost** [comment]
pls share your solution and results if it's ok for you
