### ISSUE TITLE
Add API option to set whether users can modify the `indexer` section in the `ossec.conf`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22656]
|Component|
|---|
| Wazuh API |

## Description

We need a new development, similar to what was done for the `<limits>` block, to prevent users from modifying the `<indexer>` block ([link](https://documentation-dev.wazuh.com/v4.8.0-beta4/user-manual/reference/ossec-conf/indexer.html))
```XML
<indexer>
   <enabled>yes</enabled>
   <hosts>
      <host>https://0.0.0.0:9200/</host>
   </hosts>
   <ssl>
      <certificate_authorities>
         <ca>/etc/filebeat/certs/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
      <key>/etc/filebeat/certs/filebeat-key.pem</key>
   </ssl>
</indexer>
```

Modifying the section above should only be allowed when it is explicitly disabled in the `api.yaml` (it will be allowed by default). Therefore, a new configuration must be added:
```YAML
# Uploadable Wazuh configuration sections
 upload_configuration:
   indexer:
     allow: yes
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (**unit tests**, API integration tests, [**API configuration IT**](https://github.com/wazuh/wazuh/tree/master/tests/integration/test_api/test_config)).
- [x] **Changelog**.
- [x] **Documentation**.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

> [!NOTE]
> Related issues:
> - https://github.com/wazuh/wazuh/issues/16520
> - https://github.com/wazuh/wazuh/issues/18139

**Comment by GGP1** [comment]
## Update

Added the `indexer` configuration option to the API configuration, updated the tests, tested the desired behaviour and updated the documentation.

**Comment by GGP1** [comment]
## Update

Applied code and documentation changes suggested.

**Comment by GGP1** [comment]
## Update

Applied the changes suggested, updated unit tests, tested the changes and updated the PR description's test section.

**Comment by GGP1** [comment]
## Update

Created the AIT tier 0 and 1 tests and added an endpoint route to the QA integration framework.
