### ISSUE TITLE
Test: Maild

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2266]
# Maild test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Send reports

- [x] Configure the mail alerts and receive an alert in your email.

## Configuration

- [x] Check the typical settings such as `email_reply_to`.
- [x] Test the option `email_log_source` since Wazuh v3.8.0.

## Filters

- [x] Check filters: `email_maxperhour`, `level`, `group`, etc...

**Comment by TJOSERAFAEL** [comment]
Hi @Cerv1 

we need to improve the json field extraction when sending emails. We have two options:

- Extract every new field needed, this causes to improve the code everytime a new field is added to an alert.
- Get the json object and send the raw json string. This would be less readable without a parser but we dont have to change the source code every time.
