### ISSUE TITLE
Bug Fixes for Ubuntu 22.04 SCA

### ISSUE THREAD

**Issue by Johnng007** [wazuh/wazuh#22664]
Some Bugs were raised affecting the Ubuntu 22.04 SCA checks:

S/N | Issue Bug | Affected Sections
-- | -- | --
1 | https://github.com/wazuh/external-devel-requests/issues/1196 | N/A - Referenced SCA is older and a new one already released which addresses the issue
2 | https://github.com/wazuh/wazuh/issues/21622 | 28561, 28570
3 | https://github.com/wazuh/wazuh/issues/22614 | 28561, 28575

**Comment by Johnng007** [comment]
S/N 2:  | 28561 | https://github.com/wazuh/wazuh/issues/21622 | https://github.com/wazuh/wazuh/issues/22614
The default rule in Wazuh version 4.7.3 works
![image](https://github.com/wazuh/wazuh/assets/30580457/9a3bb69e-307b-4cef-9a93-6a364eef7c31)

within the check we have two rules:
```
    condition: all
    rules:
      - "c:dpkg-query -s samba -> r:package 'samba' is not installed"
      - "c:dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching samba|deinstall|not-installed"
```

The first rule checks if samba is installed using dpkg-query with the -s command to get status of package by name
`dpkg-query -s samba`
The second rule uses the -W "show" and -f "format" options to retrieve further information on the package status.
`dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba`
The user's output of the query shows an unexpected result:
Output: `dpkg-query: no packages found matching samba`
Expected: `samba	unknown ok not-installed	not-installed`
![image](https://github.com/wazuh/wazuh/assets/30580457/bf407a16-9bf4-4830-91ec-397d0fbe2571)

This unexpected output could be as a result of the dpkg or another application misrepresenting the -f format request.

Typo issue for the check has been fixed. Albeit the typo issue on its own does not cause a fail of the check.
Looking the rule critically:
`dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' samba -> r:no packages found matching samba|deinstall|not-installed`

the SCA engine first matches `no packages found matching samba` there is an OR logic then `deinstall` and another OR logic then `not-installed` 

![image](https://github.com/wazuh/wazuh/assets/30580457/d90396bb-4fd8-4004-a7a7-bb55031d1c08)

**Comment by Johnng007** [comment]
S/N 3: | 28575 | https://github.com/wazuh/wazuh/issues/22614

This check confirms if ufw is installed, Active and in running state.
```
    condition: all
    rules:
      - "c:systemctl is-enabled ufw.service -> r:^enabled"
      - "c:systemctl is-active ufw -> r:^active"
      - 'c:ufw status -> r:Status:\s+active'
```
The check will fail if any or all of these is returned not true.

**Comment by ooniagbi** [comment]
Duplicate.
