### ISSUE TITLE
Identify and fix points of failure of RPM, DEB and APK packages

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#22670]
### Description

As the epic https://github.com/wazuh/wazuh/issues/21152 requires, we need to improve the WPK process for every OS.

This issue will cover the improve of the Linux package managers we support: RPM, DEB and APK.

These are the items to apply in each of them:

- Investigate possible points of failure: full disk, availability of commands, etc.
- If we can fix these points of failure, apply the necessary changes.
- If we can't fix these points of failure, try to reduce the occurrence of them.
- Always ensure that if a problem during installation/upgrade happens, the user will be clearly notified.

**Comment by jr0me** [comment]
### Update

#### Installation size is checked by each package manager frontend:

* DPKG: The field `Installed-Size` denotes the size required by the package. It's calculated by `debuild` and used by frontend package managers during installation
* RPM: The list of files to be installed in the package specs is used to calculate the size of the package.
* APK: Similar to `dpkg` packages, the package builder calculates the size of the package.

#### Commands availability and dependencies:

Each package spec file has a way a to declare which packages are required, commands that are not commonly found on Linux systems are already declared here.

* `lsb_release, adduser`: declared in spec files.
* `rm, chmod, cp, chown, mv, mkdir, touch, echo, kill, pgrep, find`: these are standard Unix/Linux commands provided by core utilities packages (such as GNU Coreutils).
* `command`: shell builtin in most Bourne compatible shells.
* `getenforce, semodule`: part of the SELinux policy management toolset and available on distributions that support SELinux (such as Fedora, CentOS, RHEL, and others that have SELinux installed and enabled).
* `getent`: is part of the GNU C Library, and also widely available across Linux distros.
* `system management commands (systemctl, service)`: availability is checked before use.

**Comment by vikman90** [comment]
Rescheduling to April 19.
