### ISSUE TITLE
Test: osquery

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2268]
# osquery test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## On Linux

- [x] Enable / disable daemon.
- [ ] Check invalid configuration. The module should log a warning and continue.
- [x] Pack file definitions.
- [x] Pack folder definition: `<pack name="*">/usr/share/osquery/packs/*</pack>`.
- [x] Enrich existing decorators with agent labels.
- [x] Add labels, no previous decorators defined.
- [x] Combine `<add_labels>` and `<pack>` options.
- [x] Invalid permissions (owner) for *osqueryd* binary. It **should log an error and stop**.
- [x] *osqueryd* already running when agent is started. It should log a message every minute.
- [x] If it tries to start *osqueryd* before the previous dies on restart, t should reattempt to run one minute later.
- [x] Try an Invalid path for `<log_path>` or unexisting log file. The module should reattempt up to one minute delay.
- [x] Truncate results log (`echo -n > osquery.results.log`). The module should go back to the file begin, no data lost.
- [x] Remove results log. The module should finish reading the current file and reload the new one, no data lost.
- [x] Add query pack folder to a shared folder. That folder should appear in the agent.
- [x] Agent labels with single quotes: `<label key="node">Node for 'nginx'</label>`. No SQL code injection.
- [x] Insert C/C++ comments to JSON configuration. The module should be able to insert decorators and packs.
- [x] Kill *osqueryd* while being run by the agent. The module should restart it only if it ran during 10 seconds at less.
- [x] Unexisting folder */var/osquery*. The module **should report the error** and the manager should create an alert.
- [x] Declaring osquery module multiple times (*ossec.conf* and another in *agent.conf*). Only the last one applies
- [x] Unexisting configuration with `<add_labels>` disabled and no `<pack>`. The module should log it, wait 10 minutes and retry.

## On Windows

- [x] Invalid permissions (owner) for *osqueryd* binary. It **should log an error and stop**.
- [x] *osqueryd* already running when agent is started. It should log a message every minute.
- [x] If it tries to start *osqueryd* before the previous dies on restart, t should reattempt to run one minute later.
- [x] Truncate results log (`echo -n > osquery.results.log`). The module should go back to the file begin, no data lost.
- [x] Remove *results log*. The module should finish reading the current file and reload the new one, no data lost.
- [x] Add query pack folder to a shared folder. That folder should appear in the agent.
- [x] Kill *osqueryd* while being run by the agent. The module should restart it only if it ran during 10 seconds at less.

**Comment by DaveVG1** [comment]
Rules won't generate alerts (`ossec-logtest` won't match any logs). I've tested it with the documentation example queries in: https://documentation.wazuh.com/current/user-manual/capabilities/osquery.html?highlight=osquery#how-it-works

**Comment by TJOSERAFAEL** [comment]
Hi @DaveVG1 ,
it's working on a clean installation on my machine running Ubuntu 16. We will take a look at your settings.

Best regards.

**Comment by DaveVG1** [comment]
#2318

**Comment by DaveVG1** [comment]
The following test ` Try an Invalid path for <log_path> or unexisting log file. The module should reattempt up to one minute delay.` should say:
` Try an Invalid path for <log_path> or unexisting log file. The module should reattempt (increasing one second each time) up to one minute delay.`
