### ISSUE TITLE
Test: Registration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2269]
# Registration test

| Version | Revision | Branch |
| --- | --- | --- |
| 3.8.0 | 3800 | 3.8 |

## Auth system

- [x] Check the auth daemon is running by default. (Since v3.8.0)
- [x] Check registration with `-m`.
- [x] Check registration with `-m` and `-A`.
- [x] Test force insertion to re-register an agent. (1)
- [x] Check client keys on manager and agent are equal.
- [x] Check registration with `-m wrong-IP`. **Must fail.**
- [x] Assign agent to an existing group.
- [x] Get a descriptive error when trying to assign an agent to an non-existing group.
- [x] Set the agent IP manually by the `-I` option.
- [x] Enable the "use source IP" feature by the `-i` option.
- [x] Mix incompatible options like `-I <IP>` and `-i` to see the error retrieved.
- [x] Register an agent using on Windows with `agent_auth`.

(1) https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/auth.html#force-insert

### Secure methods

- [x] Register an agent using a password. (2)
- [x] Register an agent using SSL. (2)

(2) https://documentation.wazuh.com/3.x/user-manual/registering/use-registration-service.html#secure-methods

## Tool _manage_agents_

- [x] Check same test as using Authd. (3)
- [x] Use -F option to remove duplicated agents. (3)

(3) https://documentation.wazuh.com/3.x/user-manual/reference/tools/manage_agents.html

**Comment by juan70** [comment]
Tested with:
- Debian 9: manager and agent
- CentOS 7: manager and agent
- Fedora 29: manager and agent
- Windows 2016: agent, registration on Debian, CentOS, Fedora
Everything is installed from packages.
Seems OK.

**Comment by juan70** [comment]
Just one weird behaviour:
A group seems to contain an agent, but actually it isn't there.
Maybe due to forcing the registration of an agent using `manage_agents ...... -F 0`.

```
# agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: fed29man (server), IP: 127.0.0.1, Active/Local
   ID: 003, Name: the_dummy_agent, IP: 10.0.2.2, Never connected
   ID: 005, Name: fed29ag, IP: 192.168.56.109, Active

List of agentless devices:

# agent_groups -l
Groups (2):
  default (1)
  the-group1 (1)
Unassigned agents: 1.
# agent_groups -l -g the-group1
No agents found in group 'the-group1'.
# agent_groups -l -g default
1 agent(s) in group 'default':
  ID: 005  Name: fed29ag.
# cd /var/ossec/queue/agent-groups/
# cat 002 
the-group1
# ls -l
total 8
-rw-rw----. 2 ossec  ossec 10 Jan 10 02:34 002
-rw-rw----. 1 ossecr ossec  8 Jan 10 02:50 005
# cat 005 
default
```


The manager's command line history shows:
```
# history
   (...)
   10      /var/ossec/bin/manage_agents -a 192.168.56.109                       <-- first registration => id 001
   11      /var/ossec/bin/manage_agents -a 192.168.56.109 -n the_agent          <-- this fails (ok)
   12      /var/ossec/bin/manage_agents -a 192.168.56.109 -n the_agent -F 1     <-- force => id 002
   (...)
   15      /var/ossec/bin/manage_agents -a 10.0.2.2 -n the_dummy_agent          <-- id 003
   (...)
   17      /var/ossec/bin/agent_groups -a -g the-group1
   18      /var/ossec/bin/agent_groups -l
   19      /var/ossec/bin/agent_groups -a -i 002 -g the-group1                  <-- ID 002 in the-group1
   20      /var/ossec/bin/agent_groups -l
   21      /var/ossec/bin/agent_groups -s -i 002
   22      /var/ossec/bin/agent_groups -a -i 002 -g a-non-existent-group        <-- this fails (ok)
   23      manage_agents -a 192.168.56.109 -n a_fedora_agent                    <-- this fails too (I guess)
   24      manage_agents -a 192.168.56.109 -n a_fedora_agent -F 0               <-- force => id 004, same IP as 002
```
`id 005` was registered using `agent-auth`, that's why it is not present in the history, and replaced `id 004`.
