### ISSUE TITLE
Wazuh Vulnerability Scanner in Windows doesn't report reporting results

### ISSUE THREAD

**Issue by lcabanillaskp** [wazuh/wazuh#22691]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Vulnerability Scanner | Agent | Packages/Sources |  Ubuntu 22.04.4 LTS |

I have 10 windows (server 2016 2008 11, 2022) and 1 linux Centos 7

look like Wazuh is ok, recognize the agents and get and the incidents (in linux and windows), windows are using wazuh-agent-4.7.3

I follow this:
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/configuring-scans.html

But in the case about vulnerabilities It get information only Centos 7, all the windows doesn't show anything

![WazuhEnpoint](https://github.com/wazuh/wazuh/assets/165329913/be042801-8cfb-4625-ac6e-828c97a05c72)
![Wazuh Agent Linux](https://github.com/wazuh/wazuh/assets/165329913/a0f01c66-1894-4670-864e-889ab478157f)
![Wazuh Agent WindowsAgent](https://github.com/wazuh/wazuh/assets/165329913/7962605e-f294-4e1f-975c-a09e17d78baa)

Show
No results
Last full scan
Mar 28, 2024 @ 07:27:36.000Last full scan Mar 28, 2024 @ 07:27:36.000
Last partial scan
Mar 28, 2024 @ 16:07:44.000

IN ossec.conf of Manager:

<vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <min_full_scan_interval>6h</min_full_scan_interval>
    <run_on_start>yes</run_on_start>

    
    <provider name="canonical">
      <enabled>no</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <os>jammy</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="debian">
      <enabled>no</enabled>
      <os>buster</os>
      <os>bullseye</os>
      <os>bookworm</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="redhat">
      <enabled>yes</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="alas">
      <enabled>no</enabled>
      <os>amazon-linux</os>
      <os>amazon-linux-2</os>
      <os>amazon-linux-2022</os>
      <os>amazon-linux-2023</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="suse">
      <enabled>no</enabled>
      <os>11-server</os>
      <os>11-desktop</os>
      <os>12-server</os>
      <os>12-desktop</os>
      <os>15-server</os>
      <os>15-desktop</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="arch">
      <enabled>no</enabled>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="almalinux">
      <enabled>no</enabled>
      <os>8</os>
      <os>9</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>

In /var/ossec/etc/shared/default/agent.conf

<agent_config>
	
	<wodle name="syscollector">
		<disabled>no</disabled>
		<interval>1h</interval>
		<os>yes</os>
		<packages>yes</packages>
		<hotfixes>yes</hotfixes>
	</wodle>
</agent_config>

The log in Wazuh Manager are:

Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '004' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '004'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '005' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '005'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '006' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '006'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '007' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '007'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '008' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '008'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '009' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '009'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '010' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '010'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '011' vulnerabilities.
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '011'
Mar 28, 2024 @ 11:37:46.000 wazuh-modulesd:vulnerability-detector INFO  (5472): Vulnerability scan finished.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector WARNING  (5575): Unavailable vulnerability data for the agent '000' OS. Skipping it.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '001' vulnerabilities.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '001'
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '002' vulnerabilities.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '002'
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '003' vulnerabilities.
Mar 28, 2024 @ 11:37:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '003'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector WARNING  (5575): Unavailable vulnerability data for the agent '000' OS. Skipping it.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '001' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '001'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '002' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '002'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '003' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '003'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '004' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '004'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '005' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '005'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '006' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '006'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '007' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '007'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '008' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '008'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '009' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '009'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '010' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '010'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5450): Analyzing agent '011' vulnerabilities.
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5471): Finished vulnerability assessment for agent '011'
Mar 28, 2024 @ 11:32:45.000 wazuh-modulesd:vulnerability-detector INFO  (5472): Vulnerability scan finished.

/usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log

Mar 28, 2024 @ 07:44:54  ERROR  {"dapi_errors":{"node01":{"error":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)"}},"detail":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)","error":1017,"title":"Bad Request"}
Mar 28, 2024 @ 07:46:07  ERROR  {"dapi_errors":{"node01":{"error":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)"}},"detail":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)","error":1017,"title":"Bad Request"}
Mar 28, 2024 @ 07:46:10  ERROR  {"dapi_errors":{"node01":{"error":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)"}},"detail":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)","error":1017,"title":"Bad Request"}
Mar 28, 2024 @ 07:46:13  ERROR  {"dapi_errors":{"node01":{"error":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)"}},"detail":"Some Wazuh daemons are not ready yet in node \"node01\" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)","error":1017,"title":"Bad Request"}
Mar 28, 2024 @ 07:46:16  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:46:19  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:46:22  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:46:25  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:46:28  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:46:31  ERROR  connect ECONNREFUSED 127.0.0.1:55000
Mar 28, 2024 @ 07:58:26  INFO  Wazuh dashboard index: .kibana
Mar 28, 2024 @ 07:58:26  INFO  App revision: 02
Mar 28, 2024 @ 07:58:26  INFO  Total RAM: 11957MB
Mar 28, 2024 @ 16:15:03  ERROR  {"detail":"Cluster is not running, it might be disabled in `WAZUH_HOME/etc/ossec.conf`","error":3013,"remediation":"Please, visit the official documentation (https://documentation.wazuh.com/4.7/user-manual/configuring-cluster/index.html) to get more information about how to configure a cluster","title":"Bad Request"}

**Comment by MarcelKemp** [comment]
Hi @lcabanillaskp,

According to the Windows agent, I see that it has been scanned correctly, so if no vulnerabilities appear, it is due to the following:

- If your Windows agents have the latest hotfix installed, it is normal that no system vulnerability appears, as the cumulative patches fix all the old vulnerabilities.

> Normally on Windows if you have the latest hotfix offered by Microsoft for your specific OS, no vulnerability should appear, because they usually add new vulnerabilities when they upload their hotfixes.

- If you want, to confirm it, share the following information about the agent:
  - The list of hotfixes
  - The OS information
> To get the [hotfixes list](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_hotfix_info) and [OS info](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info), you can get the information directly from the API, using the following queries:
(for example, from the WUI you can use the following tool to run the queries: `Modules` -> `tools` -> `API console`)
```
GET /syscollector/{agent_id}/hotfixes
GET /syscollector/{agent_id}/os
```
  - Also, you can verify this with the [MSRC](https://msrc.microsoft.com/update-guide/vulnerability/), which is the official source used to generate our MSU.
-------------------
- On the other hand, package vulnerabilities depend on the translations made in the [CPE Helper](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/cpe-helper.html), which is the dictionary that Wazuh uses for some of the most common programs. Without such a translation, the package, not being standardized as on Linux, cannot get the corresponding CPE, so it cannot search and find the vulnerabilities in the NVD.
  - More information about the CPE Helper and add translations in the following thread: https://groups.google.com/g/wazuh/c/HzKJuw8qDgA/m/-3Dr8Mm4AAAJ 


If you have any questions, feel free to ask.
