### ISSUE TITLE
Wazuh REST API "Experimental features are disabled" error has wrong remediation

### ISSUE THREAD

**Issue by TwentyFiveSoftware** [wazuh/wazuh#22692]
|Wazuh version|Component|
|---|---|
| 4.7.3-02 (current Wazuh Cloud version) | Wazuh API REST |

## Description

When issuing a `GET /experimental/syscollector/packages` request (or other requests to experimental endpoints), the API responds with the following error:
```json
{
  "error": "3013",
  "message": {
    "title": "Resource Not Found",
    "detail": "Experimental features are disabled",
    "remediation": "Experimental features can be enabled in WAZUH_PATH/api/configuration/api.yaml or using API endpoint https://documentation.wazuh.com/4.7/user-manual/api/reference.html#operation/api.controllers.manager_controller.put_api_config or https://documentation.wazuh.com/4.7/user-manual/api/reference.html#operation/api.controllers.cluster_controller.put_api_config",
    "error": 1122
  }
}
```
This error is expected, as `experimental_features` has to be enabled in the API config [according to the documentation](https://documentation.wazuh.com/current/user-manual/api/configuration.html).

However, the `remediation` field states, that the experimental features can be enabled using the linked API endpoints, which is not true, as no such endpoints exist.  Both links to the API specification in the `remediation` field are invalid and point to nothing. According to the [current API specification](https://documentation.wazuh.com/current/user-manual/api/reference.html), only an endpoint for querying the current API config exists (`GET /manager/api/config`), but none for updating it.

It would be great if experimental features could be enabled using the API, as there's currently no other way to enable the experimental features in a Wazuh Cloud environment. 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Hello @TwentyFiveSoftware,

Thanks for the report! The ability to update API settings via endpoints was removed in 4.0.4 (https://github.com/wazuh/wazuh/pull/7132) for security reasons, so I'm afraid it won't be included again, at least anytime soon. However, you can request API configuration changes through the `Help` section of your Wazuh Cloud Console.

Note that starting with 4.9.0, syscollector and syscheck information (which was obtained through the API) will be stored in the Wazuh indexer, so it will not be necessary to use the experimental endpoints to obtain data from all agents:
- https://github.com/wazuh/wazuh/issues/20792

In the meantime, we will update the remediation field.

**Comment by GGP1** [comment]
## Update

Updated the affected error remediation message.
