### ISSUE TITLE
Engine - Adjust Event Queue Capacity to Prevent Event Loss

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#22708]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

The current configuration of the event queue in the engine is restricted to a maximum of 1024 elements, a limitation imposed by the settings of the [concurrentqueue](https://github.com/cameron314/concurrentqueue) library that we utilize.

This constraint poses a problem as it leads to the potential loss of numerous events due to the queue's size, particularly when considering the EPS limitation. Therefore, it's imperative that we adjust this value to prevent event drops and ensure efficient event processing.

**Comment by JavierBejMen** [comment]
## Queue capacity
The maximum queue capacity is calculated based on the queue traits, concretely, the BLOCK_SIZE and IMPLICIT_INITIAL_INDEX_SIZE. Where maximum capacity is equal to multiplying both variables. Exact capacity is rounded up to the next BLOCK_SIZE multiple.

This traits affects queue performance, fine tuning for our use cases must be done.
