### ISSUE TITLE
Wazhu API service is not responding and getting 500 error

### ISSUE THREAD

**Issue by syedtest01** [wazuh/wazuh#22718]
1)in my wazuh server iam frequently getting the error as  INFO: wazuh-wui 127.0.0.1 "GET /manager/info" with parameters {} and body {} done in 10.089s: 500
2024/03/21 09:59:54 ERROR: Timeout executing API request
2024/03/21 09:59:54 INFO: wazuh-wui 127.0.0.1 "GET /manager/info" with parameters {} and body {} done in 10.026s: 500

2)i am not able to access the server and due to this multiple agents got disconnected. the actual issue started when i ran the python script to extract all the vulnerabilities of agents from reference : [https://01679260923621869060.googlegroups.com/attach/7c16f155dce66/vulnerabilities_to_csv.py?pa[…]3yGfEMHjAdf3GKTiRukOCSgN-GYFJg1y2nYgCVO0et7F8img6Q](https://01679260923621869060.googlegroups.com/attach/7c16f155dce66/vulnerabilities_to_csv.py?part=0.1&view=1&vt=ANaJVrESfyDjZD50T00BoN2oPF7U8_Y6KmIRk2Vc4JD8mmOO9WMEa2Zl6DjFUAL8mbhr13yGfEMHjAdf3GKTiRukOCSgN-GYFJg1y2nYgCVO0et7F8img6Q)

3)i have restarted all the services and rechecked it but the issue was not resolved, so i upgraded the wazuh server from 4.7.2 to 4.7.3, it just got better but not completely resolved, Now iam not even running the script also but the problem is still there.

4) Attaching the screenshots for reference kindly help in resolving the issue.
![image](https://github.com/wazuh/wazuh/assets/131128548/cb7f663f-ab70-4a54-933c-4151d89867ea)
![image](https://github.com/wazuh/wazuh/assets/131128548/e515db77-f0d3-4cb9-a1ea-1206b58603de)
![image](https://github.com/wazuh/wazuh/assets/131128548/29bbd1d0-2221-4a44-9c2f-cf8d45c29633)

**Comment by syedtest01** [comment]
Hello @GGP1 Thankyou for the response, uploading the required script and the log file.
[ossec.log](https://github.com/wazuh/wazuh/files/14880073/ossec.log)
[original vuln python3.txt](https://github.com/wazuh/wazuh/files/14880078/original.vuln.python3.txt)

no, i have not changed anything in the cluster
currently i have around 280+ agents in attached to cluster and i have assigned 16gb ram and 16 cores.

earlier i had 4.4.3 version running and it was stable, then i upgraded it to 4.7.2 and then to extract the complete consolidate inventory report i ran the python script which is shared above, from then the issue started, then the server was completed inaccessible to resolve this took help from slack portal and also restarted the services and all possible methods. finally i upgraded it again to 4.7.3 version some how it got better and i was able to access the server but in a day the same issue is repeated for 2 to 3 times. and all the added agents go to pending state and request gives 500 error and after restarting the manager again it gets restored.

**Comment by GGP1** [comment]
@syedtest01 It seems to be an issue with the wazuh-db performance on the different cluster nodes. 

To confirm this, could upload the content of the `/var/ossec/logs/cluster.log` file and the responses you get when calling the endpoint `GET /cluster/{node_id}/daemons/stats?daemons_list=wazuh-db` ([doc](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.get_daemon_stats_node)) for each of the nodes in your cluster?

> You can access the cluster's node by calling `GET /cluster/nodes` ([doc](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.get_cluster_nodes)).

**Comment by syedtest01** [comment]
@GGP1 my wazuh server is running on single node there are no cluster nodes, 
![image](https://github.com/wazuh/wazuh/assets/131128548/00932904-e57e-4f67-9721-7e374d335920)

**Comment by GGP1** [comment]
@syedtest01 Thay may be the reason why wazuh-db is struggling to respond in time, since all queries are handled by a single instance. Could you call the endpoint `GET /manager/daemons/stats?daemons_list=wazuh-db` ([doc](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_daemon_stats)) and upload the response so we can check if that's the issue?

**Comment by syedtest01** [comment]
@GGP1  the output of GET /manager/daemons/stats?daemons_list=wazuh-db  is as follows.
 {
  "data": {
    "affected_items": [
      {
        "uptime": "2024-04-07T21:40:32+00:00",
        "timestamp": "2024-04-08T11:43:54+00:00",
        "name": "wazuh-db",
        "metrics": {
          "queries": {
            "received": 2119522,
            "received_breakdown": {
              "agent": 984443,
              "agent_breakdown": {
                "db": {
                  "begin": 0,
                  "close": 0,
                  "commit": 0,
                  "remove": 0,
                  "sql": 5173,
                  "vacuum": 0,
                  "get_fragmentation": 0,
                  "sleep": 0
                },
                "tables": {
                  "ciscat": {
                    "ciscat": 0
                  },
                  "rootcheck": {
                    "rootcheck": 58948
                  },
                  "sca": {
                    "sca": 39589
                  },
                  "sync": {
                    "dbsync": 257602
                  },
                  "syscheck": {
                    "fim_file": 55351,
                    "fim_registry": 251287,
                    "fim_registry_key": 11883,
                    "fim_registry_value": 41778,
                    "syscheck": 24723
                  },
                  "syscollector": {
                    "syscollector_hotfixes": 1683,
                    "syscollector_hwinfo": 1965,
                    "syscollector_network_address": 2297,
                    "syscollector_network_iface": 3051,
                    "syscollector_network_protocol": 2104,
                    "syscollector_osinfo": 1835,
                    "syscollector_packages": 5696,
                    "syscollector_ports": 16931,
                    "syscollector_processes": 133817,
                    "deprecated": {
                      "hardware": 0,
                      "hotfix": 40,
                      "netaddr": 0,
                      "netinfo": 0,
                      "netproto": 0,
                      "osinfo": 2596,
                      "package": 2325,
                      "port": 0,
                      "process": 0
                    }
                  },
                  "vulnerability": {
                    "vuln_cves": 63769
                  }
                }
              },
              "global": 1133691,
              "global_breakdown": {
                "db": {
                  "backup": 0,
                  "sql": 1002,
                  "vacuum": 0,
                  "get_fragmentation": 0,
                  "sleep": 0
                },
                "tables": {
                  "agent": {
                    "delete-agent": 1,
                    "disconnect-agents": 84,
                    "find-agent": 98,
                    "get-agent-info": 14762,
                    "get-agents-by-connection-status": 19636,
                    "get-all-agents": 1,
                    "get-distinct-groups": 5059,
                    "get-groups-integrity": 0,
                    "insert-agent": 1,
                    "reset-agents-connection": 1,
                    "select-agent-group": 500198,
                    "select-agent-name": 286,
                    "set-agent-groups": 1,
                    "sync-agent-groups-get": 165,
                    "sync-agent-info-get": 0,
                    "sync-agent-info-set": 0,
                    "update-agent-data": 500199,
                    "update-agent-name": 1,
                    "update-connection-status": 159,
                    "update-status-code": 1,
                    "update-keepalive": 1400
                  },
                  "belongs": {
                    "get-group-agents": 0,
                    "select-group-belong": 0
                  },
                  "group": {
                    "delete-group": 0,
                    "find-group": 34,
                    "insert-agent-group": 0,
                    "select-groups": 1
                  },
                  "labels": {
                    "get-labels": 90601
                  }
                }
              },
              "mitre": 1328,
              "mitre_breakdown": {
                "db": {
                  "sql": 1328
                }
              },
              "task": 59,
              "task_breakdown": {
                "db": {
                  "sql": 0
                },
                "tables": {
                  "tasks": {
                    "delete_old": 1,
                    "set_timeout": 57,
                    "upgrade": 0,
                    "upgrade_cancel_tasks": 1,
                    "upgrade_custom": 0,
                    "upgrade_get_status": 0,
                    "upgrade_result": 0,
                    "upgrade_update_status": 0
                  }
                }
              },
              "wazuhdb": 1,
              "wazuhdb_breakdown": {
                "db": {
                  "remove": 1
                }
              }
            }
          },
          "time": {
            "execution": 99019091,
            "execution_breakdown": {
              "agent": 98783381,
              "agent_breakdown": {
                "db": {
                  "open": 69103756,
                  "begin": 0,
                  "close": 0,
                  "commit": 0,
                  "remove": 0,
                  "sql": 4692,
                  "vacuum": 0,
                  "get_fragmentation": 0,
                  "sleep": 0
                },
                "tables": {
                  "ciscat": {
                    "ciscat": 0
                  },
                  "rootcheck": {
                    "rootcheck": 2330136
                  },
                  "sca": {
                    "sca": 148117
                  },
                  "sync": {
                    "dbsync": 16396813
                  },
                  "syscheck": {
                    "fim_file": 720795,
                    "fim_registry": 7197734,
                    "fim_registry_key": 384838,
                    "fim_registry_value": 844320,
                    "syscheck": 776805
                  },
                  "syscollector": {
                    "syscollector_hotfixes": 14916,
                    "syscollector_hwinfo": 26381,
                    "syscollector_network_address": 18133,
                    "syscollector_network_iface": 27666,
                    "syscollector_network_protocol": 16677,
                    "syscollector_osinfo": 13953,
                    "syscollector_packages": 258163,
                    "syscollector_ports": 117735,
                    "syscollector_processes": 209392,
                    "deprecated": {
                      "hardware": 0,
                      "hotfix": 508,
                      "netaddr": 0,
                      "netinfo": 0,
                      "netproto": 0,
                      "osinfo": 5918,
                      "package": 57930,
                      "port": 0,
                      "process": 0
                    }
                  },
                  "vulnerability": {
                    "vuln_cves": 107991
                  }
                }
              },
              "global": 232053,
              "global_breakdown": {
                "db": {
                  "open": 61545,
                  "backup": 0,
                  "sql": 1717,
                  "vacuum": 0,
                  "get_fragmentation": 0,
                  "sleep": 0
                },
                "tables": {
                  "agent": {
                    "delete-agent": 0,
                    "disconnect-agents": 27,
                    "find-agent": 8,
                    "get-agent-info": 2316,
                    "get-agents-by-connection-status": 16685,
                    "get-all-agents": 2,
                    "get-distinct-groups": 1257,
                    "get-groups-integrity": 0,
                    "insert-agent": 0,
                    "reset-agents-connection": 79,
                    "select-agent-group": 20240,
                    "select-agent-name": 4,
                    "set-agent-groups": 1,
                    "sync-agent-groups-get": 822,
                    "sync-agent-info-get": 0,
                    "sync-agent-info-set": 0,
                    "update-agent-data": 117736,
                    "update-agent-name": 216,
                    "update-connection-status": 18,
                    "update-status-code": 0,
                    "update-keepalive": 329
                  },
                  "belongs": {
                    "get-group-agents": 0,
                    "select-group-belong": 0
                  },
                  "group": {
                    "delete-group": 0,
                    "find-group": 24,
                    "insert-agent-group": 0,
                    "select-groups": 22
                  },
                  "labels": {
                    "get-labels": 8995
                  }
                }
              },
              "mitre": 835,
              "mitre_breakdown": {
                "db": {
                  "sql": 835
                }
              },
              "task": 2628,
              "task_breakdown": {
                "db": {
                  "sql": 0
                },
                "tables": {
                  "tasks": {
                    "delete_old": 24,
                    "set_timeout": 2604,
                    "upgrade": 0,
                    "upgrade_cancel_tasks": 0,
                    "upgrade_custom": 0,
                    "upgrade_get_status": 0,
                    "upgrade_result": 0,
                    "upgrade_update_status": 0
                  }
                }
              },
              "wazuhdb": 194,
              "wazuhdb_breakdown": {
                "db": {
                  "remove": 194
                }
              }
            }
          }
        }
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Statistical information for each daemon was successfully read",
  "error": 0
}

**Comment by GGP1** [comment]
@syedtest01 the number of requests is pretty high (2.1 million in ~13 hours) and although the average time each query takes is 46 milliseconds, this number of queries could be overloading the SQLite database and causing the API requests to timeout.

To investigate the reason behind this misbehavior, let me ask you some questions:

- How frequent does the script run? Is there any other script running in the background?
- Could you log into the database `sqlite3 /var/ossec/queue/db/global.db` and  upload the results of executing `SELECT * FROM metadata WHERE key in ('last_vacuum_time', 'last_vacuum_value');`?
- Could you set `wazuh_db.debug=2` in the `/var/ossec/etc/local_internal_options.conf` file, restart the manager, let it run for 5 minutes and get the logs?

**Comment by syedtest01** [comment]
Hello @GGP1 currently i am not running the script as i am getting this issue, the plan was to run the script once every week, but without running the script also i am getting that error.
the output of last vacuum value is :-
![image](https://github.com/wazuh/wazuh/assets/131128548/7f25ce86-5e76-4b7f-8076-3047a9570dab)
attaching the log file after making the changes in /var/ossec/etc/local_internal_options.conf, but i don't think that there will be any logs recorded as it is working fine now the issue happens 2 to three times in a day where the server is not accessible and it throws the errors mentioned above.
 
[ossec.log](https://github.com/wazuh/wazuh/files/14926947/ossec.log)

**Comment by GGP1** [comment]
@syedtest01 Understood. The uploaded logs do not contain any message from `wazuh-db`, whereas there should be a lot of them. Did you restart the manager after setting `wazuh_db.debug=2`?

**Comment by syedtest01** [comment]
Hello @GGP1 i have rechecked the configuration for debug, and restarted the services again now there is data regarding the debug logs please checked the attached log file for your reference. 
 
[ossec.zip](https://github.com/wazuh/wazuh/files/14954094/ossec.zip)

**Comment by GGP1** [comment]
@syedtest01 We found some logs indicating that one of the queries (`fim_registry`) is performing poorly

```console
2024/04/12 09:27:43 wazuh-db[402781] wdb_integrity.c:473 at wdbi_query_checksum(): DEBUG: Agent '115' fim_registry range checksum: Time: 2291.635 ms.
2024/04/12 09:31:19 wazuh-db[402781] wdb_integrity.c:473 at wdbi_query_checksum(): DEBUG: Agent '2198' fim_registry range checksum: Time: 3787.163 ms.
2024/04/12 09:34:42 wazuh-db[402781] wdb_integrity.c:473 at wdbi_query_checksum(): DEBUG: Agent '067' fim_registry range checksum: Time: 5999.861 ms.
2024/04/12 09:57:12 wazuh-db[402781] wdb_integrity.c:473 at wdbi_query_checksum(): DEBUG: Agent '060' fim_registry range checksum: Time: 3439.038 ms.
```

We are aware that it suffered a performance degradation in `4.6` but it shouldn't have much impact. 

To confirm that the API timeouts are caused by these delays, it would be useful if you could upload the `api.log` at the same date as the `ossec.log` you uploaded (or new logs with the same date). With this, we will be able to determine the root of the issue.

Thanks for your patience and collaboration!

**Comment by syedtest01** [comment]
@GGP1 sorry for the delay please find the attached API.log file for that day.
[api.log-12.gz](https://github.com/wazuh/wazuh/files/14973733/api.log-12.gz)

**Comment by GGP1** [comment]
@syedtest01 The tasks that took longer to complete were executed in periods of high resource usage (for example, right after the manager was restarted). We suspect the server is struggling to handle all the requests due to a lack of resources. 

To solve this, we would suggest spinning up some workers to set up a cluster so the work is distributed among them. Here is a [guide](https://documentation.wazuh.com/current/user-manual/upscaling/adding-server-node.html#adding-a-wazuh-server-node) on how to add a server node.

Regarding the slow `fim_registry` queries I mentioned in my previous comment, I will derive this issue to the team in-charge so they can investigate more about the wazuh DB performance.

**Comment by syedtest01** [comment]
@GGP1, Thankyou for the help, i will try it with adding some workers and get back to you if issue persists.
