### ISSUE TITLE
Agents in pending status do not switch to disconnected status

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh#22746]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | wazuh-db | Manager | Sources | Ubuntu 22.04 LTS |

## Description

During an analysis of a deployment, 4 agents were detected in pending status, 3 of which had been off for more than a week.

Some agent information:
|Agent number| OS | Version| Status |
|---|---|---|---|
|1 | Windows Server 2016| 4.2.5| Off|
|2 | Windows Server 2019|  4.3.1| Off|
|3 | Windows Server 2019| 4.3.10| On|
|4 | Windows Server 2022| 4.3.11| Off|

None of those agents were connected to the manager or were connected in the last 10 minutes to have pending status.

**Comment by LucioDonda** [comment]
The first step tp find a solution for the possible bug is try to replicate a base case where it happens, to achieve that I've implemented a minimal environment with a 4.7.2 manager and 2 different windows agents (windows 11 and server 22), in both clients, the agents where running on windows hosts.

After that I've tried different ways to force the pending status, none of them with succesfull result. Restarting the VMs, force killing the proccess, locking the ports of communication after a start, among others.
The only real case scenario that I'm not able to replicate in Virtual machines is the suspend case (this is a possible next approach with a real host)

As mentioned above, none of this cases result in a "pending" status. After the time passes, the global DB gets correctly updated with it's disconnected state.
Besides that the only part of the code where directly the status passes to pending is in `manager.c`:

```
if (is_startup) {
    w_mutex_unlock(&lastmsg_mutex);

    agent_id = atoi(key->id);

    result = wdb_update_agent_keepalive(agent_id, AGENT_CS_PENDING, logr.worker_node ? "syncreq" : "synced", wdb_sock);

    if (OS_SUCCESS != result) {
        mwarn("Unable to save last keepalive and set connection status as pending for agent: %s", key->id);
    }
} else if (is_shutdown) {
```

Following the logs this only happens after the correct startup of the agent.
update-agent-data can also change this filed, but in this case it should be indirectly changed (this is, the json that the query passes should have the pending state)

And additional steps besides the named above is to force this field in the DB to check if the agent can recover for an incorrect status.

c.c. @cborla

**Comment by vikman90** [comment]
## Attempt to reproduce

1. Reduce the agents' disconnection time margin:

```shell
pkill -f wazuh-monitord

sed -Ei "s:<agents_disconnection_time>.+</agents_disconnection_time>:<agents_disconnection_time>20</agents_disconnection_time>:" etc/ossec.conf

bin/wazuh-monitord
```

2. Insert three agents:

 ```shell
cd /var/ossec
/bin/wazuh-control stop

echo > /var/ossec/etc/client.keys <<\EOF
001 agent1 any aslkdjalksdj
002 agent2 any asjdoiasjdia
003 agent3 any asjdklasjkdj
\EOF

/bin/wazuh-control start
```

3. Set the connection status, put a future keep-alive for agent 002:

```shell
cat <<\EOF | ./wdb-query.py
global update-keepalive {"id":1,"connection_status":"pending","sync_status":"syncreq"}
global sql UPDATE agent SET connection_status='pending', last_keepalive=253402300799 WHERE id=2
global update-keepalive {"id":3,"connection_status":"active","sync_status":"syncreq"} 
EOF
```

4. Check the connection status, now and within 20 seconds:
```shell
echo "global sql SELECT id, connection_status, last_keepalive FROM agent WHERE id > 0" | ./wdb-query.py
```

### Result

#### Early

```json
[
    {
        "id": 1,
        "connection_status": "pending",
        "last_keepalive": 1712663143
    },
    {
        "id": 2,
        "connection_status": "pending",
        "last_keepalive": 253402300799
    },
    {
        "id": 3,
        "connection_status": "active",
        "last_keepalive": 1712663143
    }
]
```

#### Late

```json
[
    {
        "id": 1,
        "connection_status": "disconnected",
        "last_keepalive": 1712663143
    },
    {
        "id": 2,
        "connection_status": "pending",
        "last_keepalive": 253402300799
    },
    {
        "id": 3,
        "connection_status": "disconnected",
        "last_keepalive": 1712663143
    }
]
```

## Conclusion

It is noted that the agents go "disconnected", whether they were "pending" or "active", after a few seconds. Logically, they do not change state if their keep-alive is in the future.

## Next steps

Go to the system where this problem was reported, and check:

- Date of the master and worker.
- Capture a copy of the _global.db_ file to analyze it.

**Comment by nbertoldo** [comment]
### Update
I repeated the same test @vikman90 did (only with current keep alive, not future) for 50000 agents and the result is the same, once the _agents_disconnection_time_ expired, monitord passes the status of all agents to _disconnected_. 

1. Set _agents_disconnection_time_ to 1 minute.
```shell
cd /var/ossec
pkill -f wazuh-monitord

sed -Ei "s:<agents_disconnection_time>.+</agents_disconnection_time>:<agents_disconnection_time>20</agents_disconnection_time>:" etc/ossec.conf

bin/wazuh-monitord
```

2. Insert 50000 agents:

```shell
cd /var/ossec
pkill -f wazuh-authd
pkill -f wazuh-modulesd

cat /media/sf_OVA/50kClient.keys > /var/ossec/etc/client.keys

bin/wazuh-modulesd
```

3. Set the connection status:

```shell
cat 50kQuery.txt | ./wdb-query-multi.py
```

4. Check the connection status, now and within 1 minute:

- Now:

```json
[
    {
        "id": 1,
        "connection_status": "pending",
        "last_keepalive": 1712662390
    },
    {
        "id": 2,
        "connection_status": "pending",
        "last_keepalive": 1712662390
    },
    {
        "id": 3,
        "connection_status": "pending",
        "last_keepalive": 1712662390
    },
    ...
    {
        "id": 50000,
        "connection_status": "pending",
        "last_keepalive": 1712662390
    }
]
```
- After a minute:

```json
[
    {
        "id": 1,
        "connection_status": "disconnected",
        "last_keepalive": 1712662390
    },
    {
        "id": 2,
        "connection_status": "disconnected",
        "last_keepalive": 1712662390
    },
    {
        "id": 3,
        "connection_status": "disconnected",
        "last_keepalive": 1712662390
    },
    ...
    {
        "id": 50000,
        "connection_status": "disconnected",
        "last_keepalive": 1712662390
    }
]
```

**Comment by cborla** [comment]
Based on the analysis described in this [comment](https://github.com/wazuh/external-devel-requests/issues/1974#issuecomment-2047550805), information obtained from the databases of the environment in which this issue is reported, we found no agents in pending state that exceed the allowed time of 10 minutes, which gives us to understand that the monitord process is working properly.

**Comment by cborla** [comment]
In a second analysis performed on the environment in question, we did not detect any agents in a `pending` state with a keepalive of more than 10 minutes. [evidence](https://github.com/wazuh/external-devel-requests/issues/1974#issuecomment-2052506742)

**Comment by cborla** [comment]
In a third analysis performed on the environment in question, we did not detect any agents in a pending state with a keepalive of more than 15 minutes. [comment](https://github.com/wazuh/external-devel-requests/issues/1974#issuecomment-2059750501)
