### ISSUE TITLE
Connexion 3.0 - Failed IT - Wrong content-type

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#22742]
|Wazuh version|Component|
|---|---|
| 4.9 | API |

## Description

In the run of the tests for Issue https://github.com/wazuh/wazuh/issues/20795 multiple errors related to the `content-type` appeared in multiple tests, as shown here:

```
AssertionError: assert 'application/...charset=utf-8' == 'application/...charset=utf-8'
  - application/xml; charset=utf-8
  ?             ^ ^
  + application/problem+json; charset=utf-8
  ?             ^^^^^^ ^^^^^
```

These error appears in the following endpoints:
- `GET /manager/configuration?{section}`
- `GET /manager/version/check`
- `GET /manager/validation`

**Comment by GGP1** [comment]
## Update

Modified the specification, integration tests and error responses content types.

**Comment by GGP1** [comment]
## Update

Removed the `jwt_error_handler` which wasn't being used in practice.
