### ISSUE TITLE
Refactor and migrate FIM test_moving_files suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22757]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_moving_files suite from the QA repository to the Core repository.

**Comment by Nicogp** [comment]
## Update 06/05/2024

Work has begun on the issue:

- Preparation of the file set.
- Start of migration
