### ISSUE TITLE
Improve Wazuh-DB performance by adjusting SQLite synchronization policy

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#22753]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.8.0 (dev) | Wazuh-DB | Manager |

## Problem
Recently, we have observed a decline in performance within Wazuh-DB, which we suspect is attributed to a change in transaction handling implemented earlier to enhance reliability for operations involving groups of agents.

- https://github.com/wazuh/wazuh/issues/22629

## Proposed solution
Among several ideas, one potential solution is to modify the synchronization policy of SQLite from `FULL` (2) to `NORMAL` (1). This adjustment would entail eliminating the `fsync()` call after each write operation, potentially boosting performance by approximately 16%. However, it's crucial to acknowledge that this change might compromise resilience in the event of a process crash.

## Task
The task involves implementing `PRAGMA synchronous` on the global database upon each opening, similar to how the function `wdb_enable_foreign_keys()` operates.

## Rationale for minimal impact on reliability
While altering the synchronization policy to omit [`fsync()`](https://man7.org/linux/man-pages/man2/fsync.2.html) after writes may seem concerning regarding reliability, it's essential to recognize that the impact is relatively low for several reasons:

1. **Redundant writes**: In many scenarios, the operating system or underlying storage layers already perform their own synchronization and buffering, which redundantly fulfills the purpose of `fsync()`. Hence, the direct invocation of `fsync()` may not significantly contribute to reliability.

2. **Periodic check pointing**: SQLite employs periodic checkpoints to ensure data durability. Even if `fsync()` is not called after every write, the periodic checkpoints can still maintain database consistency and mitigate the risk of data loss.

3. **Minimal window of vulnerability**: The window of vulnerability, where data loss might occur due to process crashes, is relatively small. The likelihood of a crash precisely aligning with a critical write operation is low, especially considering the overall stability of the system.

4. **Trade-off for performance**: The trade-off between performance and reliability is a common consideration in software engineering. By sacrificing a slight degree of reliability, we can achieve substantial performance gains, which might be more beneficial for most operational scenarios.

## Action plan
1. Implement the necessary modifications to incorporate `PRAGMA synchronous` in the **global** database opening process.
2. Conduct thorough testing to validate the performance improvements.

## Conclusion
While adjusting the SQLite synchronization policy to omit fsync() after writes may raise concerns regarding reliability, the anticipated impact is minimal due to various factors such as redundant writes, periodic check pointing, and the inherent trade-off between performance and reliability. By carefully implementing and testing this change, we can significantly enhance Wazuh-DB's performance without compromising its overall reliability.

**Comment by cborla** [comment]
The main [changes ](https://github.com/wazuh/wazuh/pull/22774) are ready, we completed the [performance testing stage](https://github.com/wazuh/wazuh/pull/22774#issuecomment-2040671153), it remains to create and adjust some ut.

**Comment by cborla** [comment]
Second [performance testing stage](https://github.com/wazuh/wazuh/pull/22774#issuecomment-2043954086) is already done.
