### ISSUE TITLE
Failing to connect to API in Web UI after changing API user passwords using wazuh-passwords-tool.sh

### ISSUE THREAD

**Issue by stumpf84** [wazuh/wazuh#22751]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | wazuh-passwords-tool.sh | Manager | Ansible | Ubuntu 22.04 |

Problem:
Changing all passwords, including the API user passwords, using:

`bash wazuh-passwords-tool.sh -a -au wazuh -ap <wazuh_pass>`

results in failing to connect to the API in the health check of the Web UI.
> Could not connect to API id [default]: 3099- ERROR3099 - Invalid credentials

Cause:
The password in /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml is set to the newly created wazuh-wui password but the username is set to 'wazuh'.

Solution:
Changing username in /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml from 'wazuh' to 'wazuh-wui'.

**Comment by CarlosALgit** [comment]
This issue goes "On hold" due to priority to these issues: https://github.com/wazuh/wazuh/issues/23251 https://github.com/wazuh/wazuh/issues/23252

**Comment by teddytpc1** [comment]
## Update
The script should verify what user is configured in the `wazuh.yml` file, and change the password according to that.

For the Wazuh Ansible deployment, we have to open a new issue in the `wazuh-ansible` repository to change the default user from `wazuh` to `wazuh-wui` for the `wazuh.yml` file.
