### ISSUE TITLE
Refactor and migrate FIM test_restrict suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22761]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_restrict suite from the QA repository to the Core repository.

**Comment by thejbte** [comment]
I'm working on it yet, I have problems with some failed cases.

**Comment by thejbte** [comment]
I've finished the test correctly all checks passed.
