### ISSUE TITLE
Refactor and migrate FIM test_report_changes suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22760]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_report_changes suite from the QA repository to the Core repository.

**Comment by Nicogp** [comment]
All tests are passing with the old framework.

![image](https://github.com/wazuh/wazuh/assets/13004400/374a715b-50cc-48c4-b113-1c5e3c16d520)

**Comment by Nicogp** [comment]
## Update 17/05/2024

- I resumed work on the issue.
- I created the directory structure
- I am migrating the first test test_diff_size_limit_configured
