### ISSUE TITLE
Refactor and migrate FIM test_windows_audit_interval suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22763]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_windows_audit_interval suite from the QA repository to the Core repository.

**Comment by TomasTurina** [comment]
These tests are already skipped with this message:
```
refactor required to obtain ACLs on windows 10
```
They won't be migrated as they are not working.
