### ISSUE TITLE
Refactor and migrate FIM test_registry_multiple_registries suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22770]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_registry_multiple_registries suite from the QA repository to the Core repository.

**Comment by TomasTurina** [comment]
All tests are not working right now:

```
test_fim/test_registry/test_registry_multiple_registries/test_multiple_keys.py::test_multiple_keys[get_configuration0-tags_to_apply0] FAILED [ 93%]
test_fim/test_registry/test_registry_multiple_registries/test_multiple_registry_entries.py::test_multiple_entries[get_configuration0-tags_to_apply0] FAILED [ 93%]
```

They won't be migrated. Closing as not planned.
