### ISSUE TITLE
Fix, refactor and add FIM test_registry_report_changes IT suite

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#22772]
|Related Epic   |
|-----------------------|
|  wazuh/wazuh#17881            |

As part of https://github.com/wazuh/wazuh/issues/17881, we need to refactor and migrate test_registry_report_changes suite from the QA repository to the Core repository.

**Comment by TomasTurina** [comment]
These tests are all skipped. They need to be fixed and refactored so they can extend the coverage of the FIM IT suite.

**Comment by vikman90** [comment]
Closing this issue as FIM ITs will change in 5.x.
