### ISSUE TITLE
Release 4.8.0 - Beta 5 - Footprint metrics

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22778]
### Footprint metrics information
|||
| :--                              | :--                                                             |
| **Main release stage issue**     | #22777                                         |
| **Version**                      | 4.8.0                                                   |
| **Release stage**                | Beta 5                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.0-beta5          |
| **Previous footprint metrics**   | #22467                                              |

---

| Test | Url |
| -    | -   |
| 2.5d  | https://ci.wazuh.info/view/Tests/job/Test_stress_tier/121/ |

---

## Checks
Status | Modules                                         | 4.8.0 Issue (2.5d)  |
| :--: | :--                                             | :--:                        |
| :red_circle:    | All                                            | https://github.com/wazuh/wazuh/issues/22803                         |
| :red_circle:   | Vulnerability-detector-Register                 | https://github.com/wazuh/wazuh/issues/22798                         |
| :red_circle:   | Logcollector                                    | https://github.com/wazuh/wazuh/issues/22789                         |
| :red_circle:   | Syscheck                                        | https://github.com/wazuh/wazuh/issues/22794                         |
| :red_circle:   | Rootcheck                                       | https://github.com/wazuh/wazuh/issues/22792                         |
| :red_circle:   | SCA                                             | https://github.com/wazuh/wazuh/issues/22788                         |
| :red_circle:   | Active Response                                 | https://github.com/wazuh/wazuh/issues/22791                         |
| :red_circle:   | Syscollector                                    | https://github.com/wazuh/wazuh/issues/22804                         |
| :red_circle:   | Docker,Ciscat,Osquery,Azure,Openscap            | https://github.com/wazuh/wazuh/issues/22796                         |
| :red_circle:   | All-except-Logcollector                         | https://github.com/wazuh/wazuh/issues/22790                         |
| :red_circle:   | All-except-Syscheck                             | https://github.com/wazuh/wazuh/issues/22800                         |
| :red_circle:   | All-except-Rootcheck                            | https://github.com/wazuh/wazuh/issues/22799                         |
| :red_circle:   | All-except-SCA                                  | https://github.com/wazuh/wazuh/issues/22787                         |
| :red_circle:   | All-except-Active Response                      | https://github.com/wazuh/wazuh/issues/22786                         |
| :red_circle:   | All-except-Syscollector                         | https://github.com/wazuh/wazuh/issues/22795                         |
| :red_circle:   | All-except-Docker,Ciscat,Osquery,Azure,Openscap | https://github.com/wazuh/wazuh/issues/22802                 |
| :red_circle:   | Logcollector-Syscollector                       | https://github.com/wazuh/wazuh/issues/22797                         |
| :red_circle:   | Logcollector-SCA                                | https://github.com/wazuh/wazuh/issues/22793                         |
| :red_circle:   | Logcollector-Syscheck                           | https://github.com/wazuh/wazuh/issues/22801                         |
| :red_circle:   | macOS-All                                       | https://github.com/wazuh/wazuh/issues/22805                         |
| :red_circle:   | Solaris-All                                     | https://github.com/wazuh/wazuh/issues/22805                         |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Known issues
:green_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias

---

**Comment by juliamagan** [comment]
LGTM
