### ISSUE TITLE
Check Wazuh agent compatibility with the new version of macOS Sonoma 14.5 beta

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#22838]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of macOS Sonoma 14.5 beta.

OSs checks issue: https://github.com/wazuh/wazuh/issues/22829

- Release notes: https://developer.apple.com/documentation/macos-release-notes/macos-14_5-release-notes

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] #23401
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture.

**Comment by MarcelKemp** [comment]
LGTM.
