### ISSUE TITLE
Missing vulnerabilities if manager is restarted during vulnerability scan

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22837]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Vulnerability Scan | ManageAgent | Packages | Ubuntu 22 |

### Description

During a vulnerability scan, if the connection with the agent is lost or if the manager undergoes a force stop, certain vulnerabilities may go unreported and become irrecoverably lost.

### Steps to reproduce

- Deploy a manager and an agent
- Wait until feeds are downloaded in the manager
- Just after the agent registration and the vulnerability scanner start for the new agent, restart the manager several times
- Wait until VD finishes to scan the agent
```
2024/04/08 14:19:34 wazuh-modulesd:vulnerability-scanner[89725] osScanner.hpp:336 at handleRequest(): DEBUG: Vulnerability scan for OS 'Ubuntu' on Agent '013' has completed.
2024/04/08 14:19:34 wazuh-modulesd:vulnerability-scanner[89725] scanOrchestrator.hpp:167 at run(): DEBUG: Event type: 3 processed
```
- Check that some vulnerabilities are missing 

### Evidences
![2](https://github.com/wazuh/wazuh/assets/11089305/47106fc8-9992-4e9b-b330-454e6a4d2f0a)

> [!NOTE]
> ubuntu_agent_8 and ubuntu_agent_2 have the same packages. `ubuntu_agent_8` was the agent used for reproducing the issue

- Ubuntu agent 2 and Ubuntu agent 8 vulnerabilities: [VulnsForceStop.zip](https://github.com/wazuh/wazuh/files/14906783/VulnsForceStop.zip)
- Manager Logs: [manager_ossec.zip](https://github.com/wazuh/wazuh/files/14906802/manager_ossec.zip)
- Agent Logs: [agent_ossec.zip](https://github.com/wazuh/wazuh/files/14906800/agent_ossec.zip)

**Comment by Dwordcito** [comment]
Delayed after review comments
