### ISSUE TITLE
Increase in differents metrics by Wazuh-modulesd

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22841]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Wazuh manager | Manager | Packages | CentOS |

### Description

It has been detected a significant increase of `Wazuh-modulesd` in different metrics for all [footprint tests of 4.8.0-beta5](https://github.com/wazuh/wazuh/issues/22778) 

> [!IMPORTANT]
> This uptick isn't directly tied to alterations in the vulnerability detection module, as it's disabled in the majority of the tests affected.

**Related issues**:
- https://github.com/wazuh/wazuh/issues/22566

## Evidences

We've opted for the [SCA footprint test](https://github.com/wazuh/wazuh/issues/22788), yet this enhancement can be observed across all issues related to footprint tests.

Plots compared to https://github.com/wazuh/wazuh/issues/22296

### Memory usage

| Release/Stage | RSS | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/ba5b404843b010eeafee466221266e72f788d57bd5c4a882e5af20a837e21974/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343936372d333630306d2f42343936375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343936375f6d616e616765722d7072652d72656c656173655f5253532e706e67) | https://github.com/wazuh/wazuh/issues/22552| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/f5a766e5d21fb0f0bfbdee1df0b715ffea2e6867c896883f1865bcc2b1a343eb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930362d333630306d2f42343930365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930365f6d616e616765722d7072652d72656c656173655f5253532e706e67) | https://github.com/wazuh/wazuh/issues/22296|

| Release/Stage | PSS | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/bc00ec8f7b0c88144586fc36dfdb66fb5df5c0ae8ea0827052703e3d2f252dcf/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343936372d333630306d2f42343936375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343936375f6d616e616765722d7072652d72656c656173655f5053532e706e67) | https://github.com/wazuh/wazuh/issues/22552| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/8502355f97e448572953f1f38596ab06f290709c10f1ba057654650b4ab1c256/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930362d333630306d2f42343930365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930365f6d616e616765722d7072652d72656c656173655f5053532e706e67) | https://github.com/wazuh/wazuh/issues/22296|

### File descriptors

| Release/Stage | FD | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/5fcea813a679d19405841ed92011c07e914228def0d4e76a4329cf5b9ea8ab3b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343936372d333630306d2f42343936375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343936375f6d616e616765722d7072652d72656c656173655f46442e706e67) | https://github.com/wazuh/wazuh/issues/22788| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/d5c16c32122eb1a3702a28ef6cfb430d02a2bb93027a3e1156eea4a2100a2896/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930362d333630306d2f42343930365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930365f6d616e616765722d7072652d72656c656173655f46442e706e67) | https://github.com/wazuh/wazuh/issues/22296|

**Comment by vikman90** [comment]
Let's compare 4.7.3, 4.8.0-beta4 and 4.8.0-beta5:

### Memory usage

|4.7.3|4.8.0-beta4|4.8.0-beta5|
|--|--|--|
|![](https://camo.githubusercontent.com/f5a766e5d21fb0f0bfbdee1df0b715ffea2e6867c896883f1865bcc2b1a343eb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930362d333630306d2f42343930365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930365f6d616e616765722d7072652d72656c656173655f5253532e706e67)|![](https://camo.githubusercontent.com/baf1558fff30ff44d6e8cbd8f8b99b6fa183818c80460f63a2e159905b7a1935/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343934372d333630306d2f42343934375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343934375f6d616e616765722d7072652d72656c656173655f5253532e706e67)|![](https://camo.githubusercontent.com/ba5b404843b010eeafee466221266e72f788d57bd5c4a882e5af20a837e21974/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343936372d333630306d2f42343936375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343936375f6d616e616765722d7072652d72656c656173655f5253532e706e67)|

The memory usage has decreased from ~8 GiB (4.8.0-beta4) to ~7.5 GiB (4.8.0-beta5). However, it's still far from the ~5 GiB in 4.7.3.

### File descriptors

|4.7.3|4.8.0-beta4|4.8.0-beta5|
|--|--|--|
|![](https://camo.githubusercontent.com/d5c16c32122eb1a3702a28ef6cfb430d02a2bb93027a3e1156eea4a2100a2896/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343930362d333630306d2f42343930365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343930365f6d616e616765722d7072652d72656c656173655f46442e706e67)|![](https://camo.githubusercontent.com/b6176775125a347967b942dd450e4802d999a14c213eb0bb0a2e17e42d6c4bb0/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343934372d333630306d2f42343934375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343934375f6d616e616765722d7072652d72656c656173655f46442e706e67)|![](https://camo.githubusercontent.com/5fcea813a679d19405841ed92011c07e914228def0d4e76a4329cf5b9ea8ab3b/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343936372d333630306d2f42343936375f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343936375f6d616e616765722d7072652d72656c656173655f46442e706e67)|

**Comment by santipadilla** [comment]
Increase of modulesd also noticed in [Release 4.8.0 - Beta 5 - Footprint Metrics - LOGCOLLECTOR,SYSCOLLECTOR](https://github.com/wazuh/wazuh/issues/22797)

| Release/Stage | CentOS Disk_read | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/f64873dde4701a51fe5d0a1bd467bf11242a52cc971f32647aff79a311c28727/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343937312d333630306d2f42343937315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343937315f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) | https://github.com/wazuh/wazuh/issues/22797| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/52ee499bd95875ded0181044c62dc4cf085dc572f8b5dce77c46e297abf39072/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f63656e746f732d7072652d72656c656173655f4469736b5f526561642e706e67) | https://github.com/wazuh/wazuh/issues/22313|

| Release/Stage | CentOS Disk | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/fd8cf9cb6e81b38ce8cc3aac061e428d2f6ec34c0f615bbf5a5eec0f0eefb988/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343937312d333630306d2f42343937315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343937315f63656e746f732d7072652d72656c656173655f4469736b2e706e67) | https://github.com/wazuh/wazuh/issues/22797| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/57d02eee42fcf0e7e64ad20899177ad6d46e55f67a37db799bae3a78fd5be2f0/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f63656e746f732d7072652d72656c656173655f4469736b2e706e67) | https://github.com/wazuh/wazuh/issues/22313|

| Release/Stage | Ubuntu Disk_read | Issue | 
| --- | --- | --- | 
| 4.8.0-Beta5 | ![IMAGE](https://camo.githubusercontent.com/f8c7e8e2abad6b258ae1e447d676105d5b009d8553316665d74f594edd9ec471/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42343937312d333630306d2f42343937315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343937315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | https://github.com/wazuh/wazuh/issues/22797| 
| 4.7.3-RC2 |  ![IMAGE](https://camo.githubusercontent.com/a065930700af8854a7d46df2a6576b8bf3de9f17e4a53354253c13f200afacfb/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f7562756e74752d7072652d72656c656173655f4469736b5f526561642e706e67) | https://github.com/wazuh/wazuh/issues/22313|

**Comment by sebasfalcone** [comment]
Running heaptrack

**Comment by Dwordcito** [comment]
At the initial point the test differ from the 4.7.3, because Vulnerability detection is enabled by default.

```
2024/04/05 17:25:46 wazuh-modulesd:vulnerability-scanner: INFO: Starting vulnerability_scanner module.
2024/04/05 17:25:46 wazuh-modulesd:vulnerability-scanner: INFO: Starting database file decompression.
2024/04/05 17:25:46 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities', retrying until the connection is successful.
2024/04/05 17:26:53 wazuh-modulesd:vulnerability-scanner: INFO: Database decompression finished.
2024/04/05 17:26:54 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started
2024/04/05 17:26:55 wazuh-modulesd:vulnerability-scanner: INFO: Initiating update feed process
2024/04/05 17:26:55 wazuh-modulesd:vulnerability-scanner: INFO: Processing file: queue/vd_updater/tmp/contents/431557-api_file.json
2024/04/05 17:27:27 wazuh-modulesd:vulnerability-scanner: INFO: Processing file: queue/vd_updater/tmp/contents/432557-api_file.json
2024/04/05 17:28:04 wazuh-modulesd:vulnerability-scanner: INFO: Processing file: queue/vd_updater/tmp/contents/433557-api_file.json
2024/04/05 17:28:32 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/04/05 17:28:32 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed
2024/04/05 17:28:54 wazuh-modulesd:vulnerability-scanner: INFO: Starting vulnerability_scanner module.
2024/04/05 17:28:54 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module is disabled
```

**Memory usage.**
As I mentioned previously, VD is enabled, and when this module is active, some write and read cache's are used.
For example to avoid multiple read operations, rocksdb (the database engine for VD) have an LRU cache, to read the information directly from the memory space. This have the benefit of less IO, but have the contra in the memory usage.

The read memory is limited ? YES, 16MBs

For the write operations rocksdb have another cache (Write cache buffer), and this works similar to the read cache.

The write memory is limited ? YES 64, MBs


**File Descriptors**
Also the fds are impacted by VD, Rocksdb works with LSM and the information is partitioned in multiple files, and to read this information we need open multiple files.

The rocksdb open files have some limit? YES, 256.


![](https://www.researchgate.net/publication/358081916/figure/fig2/AS:1179958957346830@1658335546953/Architecture-of-an-LSM-tree-as-implemented-by-RocksDB-taken-from-RocksDB-wiki-11.png)


Closed, this consumption is part of the design and strategy to get more scanner performance.
