### ISSUE TITLE
Race condition in big environments when an agent is removed before sync

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#22855]
|Wazuh version|Component|
|---|---|
| v4.8.0-beta5 | Wazuh Cluster |

## Description

During #22833, a race condition was found when running the API Performance tests for big environments (25 workers, 50000 agents). The problem arises when an agent has already been deleted from the `client.keys` file but its information remains in the corresponding table in `wazuh-db` awaiting synchronization. This results in the following type of error:
```
2024/04/08 16:57:48 wazuh-db: ERROR: There was an error assigning the groups to agent '41019'
2024/04/08 16:57:48 wazuh-db: WARNING: The groups were empty right after the set for agent '41019'
```
For a more detailed analysis, check the `Logs` section of the [test comment](https://github.com/wazuh/wazuh/issues/22833#issuecomment-2043571374).
 

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
This race condition has no real impact on the cluster operations or other services like wazuh-db. Since there is no clear way to solve this problem without affecting performance, it is not worth working on it.
