### ISSUE TITLE
Duplicated vulnerabilities when changing agent manager

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#22867]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Vulnerability Detection and Cluster | Manager| Packages | Ubuntu Jammy |

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/22828, one of the tests to be performed was `Change agents' manager and install a vulnerable package`.  In this test it could be seen that when changing the agent manager, the vulnerabilities were duplicated, indicating the same vulnerabilities for the agent from two managers.

|Agent ID|Vulnerabilities with the original manager | Vulnerabilities after the change | 
|:--:|:--:|:--:|
|001|[001_vulns_before.json](https://github.com/wazuh/wazuh/files/14928731/001_vulns_before.json) | [001_vulns_after.json](https://github.com/wazuh/wazuh/files/14928733/001_vulns_after.json)| 
|002| [002_vulns_before.json](https://github.com/wazuh/wazuh/files/14928736/002_vulns_before.json)| [002_vulns_after.json](https://github.com/wazuh/wazuh/files/14928739/002_vulns_after.json)| 

After installing the vulnerable package we can see that the vulnerabilities expected by the package are only reported once.

### Steps to reproduce

- Deploy a Wazuh cluster and two agents.
- Enable vulnerability detector in the managers.
- Register the agents to each manager host.
- Wait until feeds are updated.
- Wait until first scan is performed.
- Check the reported vulnerabilities.
- Check that the agents are scanned and the vulnerable packages are detected.
- Change the manager of the agents.
- Wait until the next scan is performed.
- Check the reported vulnerabilities.
- Install a vulnerable package in both agents.
- Wait until the next scan is performed.
- Check that the vulnerable package is detected in both agents

**Comment by Dwordcito** [comment]
Agent connection workflow.

```mermaid
sequenceDiagram
    Agent->>RemotedWorker: Connection
    RemotedWorker->>RemotedMaster: Send agent id and worker 
    RemotedMaster->>WazuhDBMaster: Update agent worker name
    WazuhDBMaster-->>RemotedMaster: Response
    RemotedMaster-->>RemotedWorker: Json Response
    RemotedWorker->>Router: Publish agent worker change in "remoted-agent-events"
```

Vulnerability scanner reaction
```mermaid
sequenceDiagram
    Router->>VulnerabilityModule: Receive message through "remoted-agent-events"
    VulnerabilityModule->>VulnerabilityModule: ReScanAgentOrchestration
    VulnerabilityModule->>IndexerConnector: Push message to clean previous elements
```
```json
{
  "agent_info": {
    "agent_id": "000",
    "agent_version": "4.8.0",
    "agent_name": "test_agent_name",
    "agent_ip": "10.0.0.1",
    "node_name": "test_node_name"
  },
  "action": "updateAgentWorker"
}
```

**Comment by Dwordcito** [comment]
The main part of this issue will be resolved by https://github.com/wazuh/wazuh/issues/23058

For the core team, we expect two things:

- Each manager sends a different index. `wazuh-states-vulnerabilities-cluster_name-node_name` change this in: https://github.com/wazuh/wazuh/blob/60a48dc6ac5ff85dd2e4df3c093ec8c2cb00f29e/src/wazuh_modules/vulnerability_scanner/src/policyManager/policyManager.hpp#L118
- You have to wait between consecutive bulks from the same manager. -> Use https://opensearch.org/docs/latest/api-reference/document-apis/bulk/#url-parameters refresh = wait_for
Change this in: https://github.com/wazuh/wazuh/blob/60a48dc6ac5ff85dd2e4df3c093ec8c2cb00f29e/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L166

**Comment by pereyra-m** [comment]
@Dwordcito CC @sebasfalcone 

Now the branch has the requested changes implemented.

It was confirmed that indexes are created with the required names (by default and custom).

**Comment by Dwordcito** [comment]
https://github.com/wazuh/wazuh/tree/fix/22867-duplicated-indexed-vulnerabilities its the branch with the desired changes to test the #23058 development
