### ISSUE TITLE
No vulnerabilities in the index when the agent is already registered

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#22871]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.8.0-beta5 | Vulnerability Detector | Manager/Agent | Packages | Ubuntu Jammy and CentOS 7 |

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/22828, one of the tests to be performed was `Enable vulnerability detector when some agents are already registered`. In this test it could be seen that when enabling Vulnerability Detector when the agents are already registered, vulnerabilities for agent 002 (CentOS 7), which was registered in the master node, didn't generate any vulnerability.

|Agent ID |OS | Manager node| Vulnerabilities|Logs|
|:--:|:--:|:--:|:--:|:--:|
|001|Worker node| Ubuntu Jammy|[001_registered_vulns.json](https://github.com/wazuh/wazuh/files/14929998/001_registered_vulns.json) |[worker_ossec.log](https://github.com/wazuh/wazuh/files/14930026/worker_ossec.log) |
|002|Master node| CentOS 7| [002_registered_vulns.json](https://github.com/wazuh/wazuh/files/14929999/002_registered_vulns.json)| [master_ossec.log](https://github.com/wazuh/wazuh/files/14930027/master_ossec.log)|

### Steps to reproduce

- Deploy a Wazuh cluster and two agents.
- Disable vulnerability detector in the managers.
- Register the agents to each manager host.
- Enable vulnerability detector in the managers.
- Check that the agents are scanned and the vulnerable packages are detected.

**Comment by MARCOSD4** [comment]
During the testing process performed in https://github.com/wazuh/wazuh/issues/22828, we have been able to confirm this behavior, but in addition, we have seen that if we install a vulnerable package (grafana 8.5.5) in the agent, the alerts with the vulnerabilities corresponding to this package appear approximately 20 minutes after the installation of the package. It is important to note that only the vulnerabilities of the package that has been installed (grafana) appear. This has been verified by looking at the agent's inventory in the dashboard.

**Comment by sebasfalcone** [comment]
The changes we attempt to add in this PR:
- https://github.com/wazuh/wazuh/pull/22731

Are a possible solution to this problem

Please repeat this test on RC1 and validate the changes
