### ISSUE TITLE
API IT fails due to missing `wazuh_testing.modules.vulnerability_detector`

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22875]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.8.0-beta5 | API | Agent | Packages | - |

### Description

During [Release 4.8.0 - Beta 5 - Integration tests](https://github.com/wazuh/wazuh/issues/22823) it has been detected that API Integration GA Tests fails.

```console
E   ModuleNotFoundError: No module named 'wazuh_testing.modules.vulnerability_detector'
```

### Evidences

- https://github.com/wazuh/wazuh/actions/runs/8631386015

**Comment by GGP1** [comment]
### Solution

We should modify [this](https://github.com/wazuh/wazuh/blob/560e637606f52c93e5207ab48e20345421c175b1/.github/workflows/integration-tests-api-tier-0-1.yml#L71C1-L77C13) part of the code so it looks for tags as well

```diff
+  if [ "X`git ls-remote --heads --tags https://github.com/wazuh/qa-integration-framework.git ${BRANCH_NAME}`" != "X" ]; then
      QA_BRANCH=${BRANCH_NAME}
+  elif [ "X`git ls-remote --heads --tags https://github.com/wazuh/qa-integration-framework.git ${BRANCH_BASE}`" != "X" ]; then
      QA_BRANCH=${BRANCH_BASE}
  else
      QA_BRANCH="main"
  fi
```

**Comment by GGP1** [comment]
## Update

Modified the integration tests QA framework installation so it fetches both heads and tags.
