### ISSUE TITLE
Rollback SCA rework changes in 4.8.0

### ISSUE THREAD

**Issue by ooniagbi** [wazuh/wazuh#22886]
## Description
This issue will track the removal of changes applied to SCA policies as part of https://github.com/wazuh/wazuh/issues/18306 in 4.8.0.

### SCA policies
- https://github.com/wazuh/wazuh/issues/17355
- https://github.com/wazuh/wazuh/issues/17356
- https://github.com/wazuh/wazuh/issues/17221
- https://github.com/wazuh/wazuh/issues/14704
- https://github.com/wazuh/wazuh/issues/14702
- https://github.com/wazuh/wazuh/issues/17361
- https://github.com/wazuh/wazuh/issues/16946
- https://github.com/wazuh/wazuh/issues/15167
- https://github.com/wazuh/wazuh/issues/17329
- https://github.com/wazuh/wazuh/issues/17330
- https://github.com/wazuh/wazuh/issues/17319

**Comment by jk-olaoluwa** [comment]
**Update 12/04/2024**
**SCA Rollback Update**
CentOS Linux 8 Rollback to 4.7.3 - https://github.com/wazuh/wazuh/commit/f0d7be40f817b2538fd42f43f4c0615706e703c0
RHEL 8 Rollback to 4.7.3 - https://github.com/wazuh/wazuh/commit/794bf40973918d1dcb9ed3c3181e8b9abb2e5a60
RHEL 9 Rollback to 4.7.3 - https://github.com/wazuh/wazuh/commit/590729ca620770ea394a65b4c14653f8af4bad29

**Comment by Johnng007** [comment]
**Update 12/04/2024**
SCA Rollback Update

| S/N | SCA | Rollback | Commit
| -- | -- | -- | --
| 1 | Amazon Linux 2 | 4.7.3 |  https://github.com/wazuh/wazuh/commit/177df59651e369480c2172a78d018e602baba7cb
| 2 | SUSE Linux Enterprise 15 | 4.7.3 | https://github.com/wazuh/wazuh/commit/61b759e5de92f3e64d8442f08c658cac7df8aa8f
| 3 | Microsoft Windows 10 Enterprise | 4.7.3 | https://github.com/wazuh/wazuh/commit/56d746303989e867d3f260050a23d64a33c5e885
| 4 | Microsoft Windows 11 Enterprise | 4.7.3 | https://github.com/wazuh/wazuh/commit/2d45d1dfbf14c78f904b5cfc2c46db51a07fd951
| 5 | Apple MacOS 13 Ventura | 4.7.3 | https://github.com/wazuh/wazuh/commit/538846f3d93a012297a3dd040c3732cad9fea983

**Comment by IsExec** [comment]
Update 12/04/2024
SCA Rollback Update

S/N | SCA | Rollback version | Commit
-- | -- | -- | --
1 | Red Hat Enterprise Linux 7 | 4.7.3 | https://github.com/wazuh/wazuh/commit/ca7e9247c34e96921a5231081263191ac44c5573
2 | Debian Linux 10 | 4.7.3 | https://github.com/wazuh/wazuh/commit/1333c8ca83266b00030b66d29df30656fd440f0f
3 | Ubuntu Linux 18.04 | 4.7.3 | https://github.com/wazuh/wazuh/commit/0463bc9c58fd0d2ca5449e2f412a123c3ff15ae3

**Comment by ooniagbi** [comment]
We also need to rollback:

- CentOS 7: https://github.com/wazuh/wazuh/blob/4.8.0/ruleset/sca/centos/7/cis_centos7_linux.yml @jk-olaoluwa 
- Debian 8: https://github.com/wazuh/wazuh/blob/4.8.0/ruleset/sca/debian/cis_debian8.yml @IsExec

**Comment by jk-olaoluwa** [comment]
**Update 15/04/2024**
**SCA Rollback Update**
CentOS Linux 7 Rollback to 4.7.3 - https://github.com/wazuh/wazuh/commit/60de0d6f58a48431db3bcbdc6b9332bf140b2c2e

**Comment by IsExec** [comment]
Update 15/04/2024
SCA Rollback Update

Rollback Debian Linux 8 SCA to previous version in 4.7.3 - https://github.com/wazuh/wazuh/commit/539d6683ca0767441a879242741173fd9616133e
