### ISSUE TITLE
Bug in `agent-groups` cluster statistics

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#22884]
|Component|
|---|
| Wazuh cluster |

## Description
There is a bug in the cluster statistics. When running `cluster_control -i more`,  we can see that the number of chunks for `Agents-groups` task is 0, and the end date of the last synchronization is unknown too:
```
# /var/ossec/bin/cluster_control -i more
Cluster name: wazuh

Connected nodes (1):

    master-node (wazuh-master)
        Version: 4.7.3
        Type: master
        Active agents: 0

    worker1 (172.16.1.3)
        Version: 4.7.3
        Type: worker
        Active agents: 1
        Status:
            Last keep Alive:
                Last received: 2024-04-11T08:15:15.920712Z.
            Integrity check:
                Last integrity check: 0.008s (2024-04-11T08:15:25.086418Z - 2024-04-11T08:15:25.094491Z).
                Permission to check integrity: True.
            Integrity sync:
                Last integrity synchronization: 0.034s (2024-04-11T08:01:24.912933Z - 2024-04-11T08:01:24.947037Z).
                Synchronized files: Shared: 0 | Missing: 3 | Extra: 0.
            Agents-info:
                Last synchronization: 0.01s (2024-04-11T08:15:27.527871Z - 2024-04-11T08:15:27.537917Z).
                Number of synchronized chunks: 1.
                Permission to synchronize agent-info: True.
            Agents-groups:
                Last synchronization: n/a (2024-04-11T08:15:27.815995Z - n/a).
                Number of synchronized chunks: 0.
            Agents-groups full:
                Last synchronization: 0.004s (2024-04-11T08:01:57.504565Z - 2024-04-11T08:01:57.508995Z).
                Number of synchronized chunks: 1.
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment]
## Update

Passed to `on-hold` due to being with issues with higher priority.

**Comment by RamosFe** [comment]
## Update

Following the execution traceback of the data. The data comes directly as `n/a` from the following part of the code:

https://github.com/wazuh/wazuh/blob/60e2eed3a920efa71ac0461df3ced6d71006a63f/framework/wazuh/core/cluster/local_client.py#L234-L260

I continue with the debugging of the bug.

**Comment by RamosFe** [comment]
## Update 

Moving to `on-hold` due to issue with more priority.

**Comment by fdalmaup** [comment]
Moving to Blocked status to consult the management team about the release in which we will introduce the changes.

**Comment by fdalmaup** [comment]
Removed in https://github.com/wazuh/wazuh/issues/22888
