### ISSUE TITLE
Publish Wazuh coordinator

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#22902]
# Description

We aim to finalize the Wazuh coordinator development efforts to make sure that users can take advantage of it.

The main purpose of this issue is to provide users with the ability to automatically balance the agents' TCP sessions in a Wazuh cluster environment. This helps to ensure smooth behavior and performance when deploying a large Wazuh clustered environment with thousands of agents connected to it.

This development assumes the Wazuh agents are connected to the Wazuh cluster through a layer 4 (TCP/UDP) load balancer using the least connections algorithm.

Most of the work done can be tracked from these two issues:
- https://github.com/wazuh/wazuh-tools/issues/196
- https://github.com/wazuh/wazuh/issues/13195

`Wazuh coordinator` will refer to all of the components listed below:
- **HAProxy helper.** Located in the manager.
- **HAProxy wrapper.** Located in the manager.
- **HAProxy balancer.** Deployment will vary depending on the environment.

# Functional requirements

- Users will be able to configure the Wazuh coordinator on the Wazuh manager side. 
- Users will be able to deploy the Wazuh coordinator following dedicated guides in the Wazuh documentation.
- Users will be able to deploy the HAProxy balancer component via standard packages or docker images provided by HAProxy.
- Users will be able to balance the Wazuh managers input connections using the Wazuh coordinator.
- Users will be agnostic to HAProxy from the Wazuh coordinator configuration perspective. 
- Users will be able to use the HAProxy helper in any of the Wazuh manager OS and architectures available. 

# Non-functional requirements

- This development will ensure that no agent connections are lost because of it.

# Implementation restrictions
- The HAProxy helper component will only run on the master node. 
- The Wazuh coordinator configuration will be part of the `cluster` configuration block.
- The HAProxy helper and wrapper source code will be part of the `wazuh` repository.
- HAProxy balancer will be an external dependency. Wazuh will not host or maintain this component. 
- Every Wazuh version will be tested against a particular HAProxy version. This will be documented in the Wazuh coordinator guide. 
- The HAProxy helper-Haproxy balancer communication configured by the provided guides must also describe how to use `HTTPS`. 
 
<details>
<summary>Configuration proposal</summary>

This would be the complete cluster configuration block, including the HAProxy helper options:
```XML
<cluster>
    <name>wazuh</name>
    <node_name>master-node</node_name>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <node_type>master</node_type>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>

    <haproxy_helper>
      <disabled>yes</disabled>
      <frequency>60</frequency>
      <haproxy_address></haproxy_address>
      <haproxy_port></haproxy_port>
      <haproxy_user></haproxy_user>
      <haproxy_password></haproxy_password>
      <excluded_nodes>
        <node>master</node>
      </excluded_nodes>
      <agent_chunk_size>100</agent_chunk_size>
      <agent_reconnection_time>5</agent_reconnection_time>
      <imbalance_tolerance>10</imbalance_tolerance>
      <remove_disconnected_node_after>60</remove_disconnected_node_after>
</cluster>
```

However, many of these options would not need to be included by default, and could be left like this or even eliminating the entire HAProxy helper block so that the user can include it manually.
```XML
<cluster>
    <name>wazuh</name>
    <node_name>master-node</node_name>
    <key>c98b62a9b6169ac5f67dae55ae4a9088</key>
    <node_type>master</node_type>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>

    <haproxy_helper>
      <disabled>yes</disabled>
      <frequency>60</frequency>
      <haproxy_address></haproxy_address>
      <haproxy_port></haproxy_port>
      <haproxy_user></haproxy_user>
      <haproxy_password></haproxy_password>
    </haproxy_helper>
</cluster>
```

</details>

# Plan
- [x] https://github.com/wazuh/wazuh-tools/issues/268
- [x] https://github.com/wazuh/wazuh/issues/20887 (Framework team).
  - Convert YAML configuration to XML within the `cluster` block.
  - Migrate or remove the HAProxy wrapper and adapt the HAProxy helper.
  - Refactor HAProxy helper to remove communication via `Wauzh API`. Use framework functions instead.
  - Adapt its execution as an independent process or as a child (additional or already existing) of the cluster service.
  - Add unit tests.
  - Manual testing.
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6395 (Framework team)
- [x] https://github.com/wazuh/wazuh-jenkins/issues/6367 (Framework team).
- [x] https://github.com/wazuh/wazuh-documentation/issues/7232 (Framework team, Docu team)
  - Add pages about the operation and configuration of the HAProxy helper.
  - Add pages about deploying and configuring HAProxy balancer through packages and docker images.
- [x] https://github.com/wazuh/wazuh-qa/issues/5453 (QA team).
- [x] ~https://github.com/wazuh/wazuh/issues/17217 (Framework team).~
- [x] Meeting for validation with the Cloud team (Cloud and Framework team).
- [x] https://github.com/wazuh/wazuh-dashboard/issues/175

# Approved by

- @Selutario 
- @havidarou

**Comment by fdalmaup** [comment]
Objective achieved.
