### ISSUE TITLE
Active response does not work if the agent reports to a worker node

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh#22900]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Active Response | Manager/Agent | Packages | Linux (manager), Windows (agent) |

## Description

Thanks to a report from our community, we have found out the Active Response module does not behave as expected when the agent configured in the `ossec.conf` to run the AR script is connected to a manager worker type node. However, it acts as expected if the agents reports to a master type node.

Active Response configuration example:

```
<command>
  <name>custom-script</name>
  <executable>custom-script.exe</executable>
</command>
  
<active-response>
  <disabled>no</disabled>
  <command>custom-script</command>
  <location>defined-agent</location>
  <agent_id>001</agent_id>
  <rules_id>800003</rules_id>
</active-response>
```

![image](https://github.com/wazuh/wazuh/assets/15186973/03dd1233-8635-4bd5-920c-34f733de3cd1)

Link to the community ticket: https://github.com/wazuh/community/issues/23230

**Comment by sdvendramini** [comment]
Just as a comment, it seems that the AR message is not being distributed in the cluster. So the same situation will happen if the alert is generated on a worker and the agent is connected to another worker or directly on the master node.

**Comment by noloseconseguridad** [comment]
Hi, I'm the guy who found the issue. As described in the diagram that I have created, the opnsense when generates the corresponding alert, the windows host wasn't executing the active response if is connected in a different node. I assume that this also will happend in any OS with the agent. If you need something to reproduce the error, tell me.

**Comment by havidarou** [comment]
Wazuh 5.0 will use a different mechanism to achieve active response.
