### ISSUE TITLE
Bump VD database generation changes from master to 4.8.0

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#22913]
## Description
We should add the changes proposed on this issue:
- https://github.com/wazuh/wazuh/issues/22877

To the 4.8.0 branch, to have full green on Github actions

## DoD
- [x] All commits from #22877 are on 4.8.0

**Comment by Dwordcito** [comment]
For some reason, the automatic triggers are not working:

https://github.com/wazuh/wazuh/actions/runs/8669589498

**Comment by sebasfalcone** [comment]
The reason is a typo 😞 

https://github.com/wazuh/wazuh/blob/bc442707d3f542c717d6fc2054f67ba5834e162a/.github/workflows/vulnerability-scanner-generate-database.yml#L24

`github.event == 'schedule'` should be `github.event_name == 'schedule' `

**Comment by Dwordcito** [comment]
Tackled in https://github.com/wazuh/wazuh/issues/22918
