### ISSUE TITLE
Syscollector unable to gather python packages in macOS Ventura

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#22911]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Syscollector | Agent | Packages | macOS Ventura  |

### Description 

It has been detected in [Release 4.8.0 - Beta 5 - E2E UX tests - Vulnerability Detection](https://github.com/wazuh/wazuh/issues/22812) that syscollector is currently unable to collect python packages on macOS Ventura. 

### Steps to reproduce
- Install a manager
- Install and register a macOS Ventura agent
- Install a python package, for example:
```
python3 -m pip install django
```

- Check that the package was correctly installed
```
sh-3.2# python3 -m pip freeze 
asgiref==3.8.1
cffi @ file:///private/tmp/cffi-20231211-41533-ztvmir/cffi-1.16.0
Django==5.0.4
docutils @ file:///private/tmp/docutils-20231211-37909-likvzd/docutils-0.20.1
pycparser @ file:///private/tmp/pycparser-20231211-26022-8sypv1/pycparser-2.21
six==1.16.0
sqlparse==0.4.4
```

- Wait until syscollector scan is finished
```
2024/04/12 10:21:25 wazuh-modulesd:syscollector: INFO: Module started.
2024/04/12 10:21:25 wazuh-modulesd:syscollector: INFO: Starting evaluation.
```
- Check that after a Syscollector scan, python packages are not being collected. 
 
### Evidences

<details>

<summary> Check installed packages in Ventura Agent </summary>

</details>

</details>

The list of the collected packages does not include any of the npm packages

**List of packages**: [packages(2).csv](https://github.com/wazuh/wazuh/files/14959308/packages.2.csv)

Django package is installed in the default path
```
>>> import django
>>> django.__file__
'/usr/local/lib/python3.11/site-packages/django/__init__.py'
```

**Comment by Dwordcito** [comment]
Moved to 4.8.2, pre-existing issue.

**Comment by pereyra-m** [comment]
Moving to on-hold, because the problem is related to https://github.com/wazuh/wazuh/issues/22896#issuecomment-2067401304

**Comment by sebasfalcone** [comment]
Great investigation @pereyra-m 

## Conclusion
Being that this is an expected result of the environment used to build the packages, we conclude that this is not a development issue

There is a re-design taking progress over the package generation, but the building OS will remain the same:
- https://github.com/wazuh/internal-devel-requests/issues/187
