### ISSUE TITLE
Unexpected Vulnerability Detector Warning related to DB in stress tests

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22912]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Wazuh manager | Manager | Packages | CentoS |

### Description

During testing performed in [Release 4.8.0 - Beta 5 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/22798) it has been detected this warning log in the manager:

```console
2024/04/05 17:51:26 wazuh-modulesd:vulnerability-scanner WARNING: Discarded event: DB query not synced
```

The complete configuration and logs can be found here: [ossec_Test_stress_B4970_manager_2024-04-08.zip](https://github.com/wazuh/wazuh/files/14960171/ossec_Test_stress_B4970_manager_2024-04-08.zip)

**Comment by Dwordcito** [comment]
This is not an issue, and will be tackled at: https://github.com/wazuh/wazuh/pull/22731
