### ISSUE TITLE
Confusing name in Vulnerability Detector configuration block

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#22927]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta5 | Wazuh Manager | Manager | Packages | Any |

### Description

During testing in [Release 4.8.0 - Beta 5 - Vulnerability Detector additional test cases](https://github.com/wazuh/wazuh/issues/22828), in particular in the tests related to [Offline Update](https://github.com/wazuh/wazuh/issues/22828#issuecomment-2047876249), it has been found that the name of the `<offline-url>` tag in the vulnerability detector configuration block is confusing as the expected value here is a zip file containing the previously downloaded feeds, and not a url as indicated by the tag.

```console
<vulnerability-detection>
   <enabled>yes</enabled>
   <index-status>yes</index-status>
   <feed-update-interval>60m</feed-update-interval>
   <offline-url>file:///var/path/to/the/cves.file.zip</offline-url>
</vulnerability-detection>
```

**Comment by Dwordcito** [comment]
@MARCOSD4 this is a documentation issue ?

**Comment by MARCOSD4** [comment]
Hi @Dwordcito. No, sorry, I am not referring to a documentation issue, I am referring to the name of the label itself in the configuration block.

**Comment by Dwordcito** [comment]
The name comes from two parts.

1- Offline -> this is for offline use obviously

2- URL, URLs are accepted to point to a specific file.

This follows the RFC schemes https://datatracker.ietf.org/doc/html/rfc1738#section-3

**Comment by Dwordcito** [comment]
please create and change request with the approval of a Senior staff leader with the purpose and the desired tag.
