### ISSUE TITLE
Clean up agents labels during deletion

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#22925]
|Wazuh version|Component|Install type|
|---|---|---|
| ≤ 4.7.3 | Wazuh-DB | Manager/Agent |

We've found that Wazuh-DB stores agent labels after deleting those agents:

```sql
SELECT count(key) FROM labels WHERE id NOT IN (SELECT id FROM agent);
```

## Impact

This is producing a performance degradation, specially during the database backup. This caused a big delay in concurrent queries to the global database as they need to wait until the backup is complete.

## Manual cleaning up

We've manually run the following commands in Wazuh-DB:
```
global sql DELETE FROM labels WHERE id NOT IN (SELECT id FROM agent);
global vacuum
```

### File size

|Before|After|
|--:|--:|
|3 GiB| 20 MiB|

## Proposal

- Clean the `labels` table: delete labels for non-existing agents on upgrade.
- Declare the relationship between `labels.id` and `agent.id` as a foreign key with `DELETE CASCADE` rule.
- Check that no more tables suffer this problem.

## DoD

- [x] When upgrading from 4.7.3 to 4.8.0, Wazuh-DB shall clean the `labels` table as specified above.
- [x] Once upgraded, when deleting an agent, its corresponding tuples at `labels` table should disappear.

**Comment by cborla** [comment]
The manual tests were successfully completed. [link](https://github.com/wazuh/wazuh/pull/22933#issuecomment-2059878707)
