### ISSUE TITLE
vulnerability-detector problem

### ISSUE THREAD

**Issue by Chahira55** [wazuh/wazuh#22948]
- Wazuh version : v4.7.1"
- Component : wazuh-moduled:vulnerability-detector
- Install type : Manager
- Install method :Packages
- Platform : ubuntu 22.04
 **When** : 
grep "Vulnerability Detector" /var/ossec/logs/ossec.log | grep "ERROR

And this is not resolve my prob : 

1. Stop the manager
2. Remove the vulnerabilities database, located at /var/ossec/queue/vulnerabilities/cve.db
3. Set run_on_start to yes in the Vulnerability Detector configuration
4. Restart the manager

![Capture](https://github.com/wazuh/wazuh/assets/101703852/87bd2a05-8c6b-4ba7-880e-4c0eec42d01d)
Help please it's very urgent

**Comment by MiguelazoDS** [comment]
Hi, 

What operating system your agents are running on? Did you enable the desired platform in the provider section? 

Please take a look at 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html

In particular this section 

https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/configuring-scans.html 

Only to mention, the results for your manager won't be visible in the UI if you're only scanning the Ubuntu Jammy Wazuh manager.
