### ISSUE TITLE
Set up an automated process to upload generated debug symbols for RPM to a designated storage location

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#22942]
|Related issue|
|-|
|[#187](https://github.com/wazuh/internal-devel-requests/issues/187)|
|https://github.com/wazuh/wazuh/issues/22080|
|https://github.com/wazuh/wazuh-jenkins/issues/6200|

## Description

This issue aims to automate the upload process to a designated location (development/wazuh/x.y/main/packages, see https://github.com/wazuh/wazuh-jenkins/issues/6200#issuecomment-1977510703)** of the debug symbols generated on the RPM package generation process, both for the agent and for the manager packages.

It must also be considered auto-deletion policies for packages to be applied to debug symbols.

## Goals
For every platform, these goals must be achieved:
- Modify the package upload process workflows to accommodate the upload of its related debug symbols to the designated location (development/wazuh/x.y/main/packages, see https://github.com/wazuh/wazuh-jenkins/issues/6200#issuecomment-1977510703).
- Uploaded symbols should be securely stored and easily accessible for debugging purposes.
- Analyze and modify accordingly the auto-deletion process to comply with auto-deletion policies **_(TBD by management)_**
- Test & verify that these behaviors are satisfied

### DoD
- Debug symbols associated with their corresponding RPM package are automatically uploaded to their designated location.
- Auto-deletion policies are considered and implemented
- Verification of proper behavior is performed

Approval
DRI Name: @ncvicchi 
Objective: Generate debug symbols

**Comment by Leoquicenoz** [comment]
## Update

We analyze the way to generate the packages from github actions according to this [slack thread](https://wazuh-team.slack.com/archives/C038AR25C8N/p1712751120127009), before generating the docker image, the output obtained was the following: 

```
+ base_name=wazuh-agent_4.9.0-test
+ rpm_file=wazuh-agent_4.9.0-test_x86_64_30b258c.rpm
+ /usr/local/bin/rpmbuild --define '_sysconfdir /etc' --define '_topdir /build_wazuh/rpmbuild' --define '_threads 4' --define '_release test' --define '_localstatedir /var/ossec' --define '_debugenabled no' --define '_rpmfilename wazuh-agent_4.9.0-test_x86_64_30b258c.rpm' --target x86_64 -ba /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.9.0.spec
Building target platforms: x86_64
Building for target x86_64
error: parse error in expression:  %{_isstage} == no
error:                             ^
error: /build_wazuh/rpmbuild/SPECS/wazuh-agent-4.9.0.spec:3: bad %if condition:  %{_isstage} == no
+ return 0
+ get_checksum 4.9.0 30b258c no
+ src=no
+ [[ no == \y\e\s ]]
+ [[ no == \y\e\s ]]
+ mv /build_wazuh/rpmbuild/RPMS/wazuh-agent_4.9.0-test_x86_64_30b258c.rpm /var/local/wazuh
mv: cannot stat `/build_wazuh/rpmbuild/RPMS/wazuh-agent_4.9.0-test_x86_64_30b258c.rpm': No such file or directory
+ return 1
+ return 1
+ clean 1
+ exit_code=1
+ find /home/runner/work/wazuh/wazuh/packages/rpms/amd64/agent '(' -name '*.sh' -o -name '*.tar.gz' -o -name 'wazuh-*' ')' '!' -name docker_builder.sh -exec rm -rf '{}' +
+ exit 1
Error: Process completed with exit code 1.
``` 
After generating the [docker image](https://github.com/wazuh/wazuh/actions/runs/8728407137), the output is obtained:

```
Run package_name=$(find /tmp -maxdepth 1 -type f -name "*agent*.rpm" -exec basename {} 2>/dev/null \;)
Installing Wazuh wazuh-agent-debuginfo_4.9.0-test_x86_64_30b258c.rpm.
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Examining /packages/wazuh-agent_4.9.0-test_x86_64_30b258c.rpm: wazuh-agent-4.9.0-test.x86_64
Marking /packages/wazuh-agent_4.9.0-test_x86_64_30b258c.rpm to be installed
Loading mirror speeds from cached hostfile
 * epel: mirror.fcix.net
Resolving Dependencies
--> Running transaction check
---> Package wazuh-agent.x86_64 0:4.9.0-test will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package      Arch    Version     Repository                               Size
================================================================================
Installing:
 wazuh-agent  x86_64  4.9.0-test  /wazuh-agent_4.9.0-test_x86_64_30b258c   37 M

Transaction Summary
================================================================================
Install       1 Package(s)

Total size: 37 M
Installed size: 37 M
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
Warning: RPMDB altered outside of yum.

  Installing : wazuh-agent-4.9.0-test.x86_64                                1/1 

  Verifying  : wazuh-agent-4.9.0-test.x86_64                                1/1 

Installed:
  wazuh-agent.x86_64 0:4.9.0-test                                               

Complete!
The installation could not be completed. The package will not be uploaded.
Error: Process completed with exit code 1.
``` 
[Build rpm wazuh-agent on amd64](https://github.com/wazuh/wazuh/actions/runs/8729672052/job/23952081134)
