### ISSUE TITLE
FR: Rule Tester should also explain what happens after rule match

### ISSUE THREAD

**Issue by ilsaloving** [wazuh/wazuh#22950]
|Wazuh version| Component | Action type |
|---| --- | --- |
|4.7.3 | Rule Tester | Improve |

## Description

The rule tester currently checks the decoder and rules, but does not do any analysis of what happens afterwards.  Being able to see the entire path a log entry takes would be an extremely valuable time saver.

For example, cisco ios rule 4722.  A test log entry matches the rule successfully, but gets dropped because the alert threshold is higher than the rule severity.

**Comment by juliancnn** [comment]
Hi @ilsaloving,

We acknowledge the value of seeing the complete processing path of a log entry within the rule tester. The current version focuses on decoder and rule matching, which leaves a gap for understanding post-matching actions.

The development of the new Wazuh-Engine, intended to replace Wazuh-Analysisd/wazuh-logtest, will address many such limitations. You can find more information on this enhancement in [Issue #11334](https://github.com/wazuh/wazuh/issues/11334).

As we develop the Wazuh-Engine, understanding specific use cases from our community is incredibly helpful. Could you share any particular scenarios or requirements you have in mind? This insight will aid us in evaluating and possibly incorporating these aspects into the new Wazuh-Engine's functionality.

I encourage you to take a look at the epic and share your thoughts with us!

**Comment by ilsaloving** [comment]
> Hi @ilsaloving,
> 
> We acknowledge the value of seeing the complete processing path of a log entry within the rule tester. The current version focuses on decoder and rule matching, which leaves a gap for understanding post-matching actions.
> 
> The development of the new Wazuh-Engine, intended to replace Wazuh-Analysisd/wazuh-logtest, will address many such limitations. You can find more information on this enhancement in [Issue #11334](https://github.com/wazuh/wazuh/issues/11334).
> 
> As we develop the Wazuh-Engine, understanding specific use cases from our community is incredibly helpful. Could you share any particular scenarios or requirements you have in mind? This insight will aid us in evaluating and possibly incorporating these aspects into the new Wazuh-Engine's functionality.

I have not yet had an opportunity to dig deeper with Wazuh, so the only use case I can think of is the one that prompted the ticket.  We were testing sending logs from a network switch to Wazuh.  We performed some very simple operations (eg: login, failed login, etc) and nothing was appearing in wazuh.  

We had no idea what wasn't working, nor where to start investigating, so I ended up painstakingly verifying every step in the process.  I used nc to open port 514 to verify there was nothing on the network blocking the traffic.  Was wazuh opening the port and listening?  etc.

I eventually figured out it was the minimum severity threshold, but that was only after looking through the configuration and rule lists with a fine toothed comb.

**Comment by juliancnn** [comment]
For these cases it is useful to use [wazuh archive](https://documentation.wazuh.com/current/user-manual/manager/wazuh-archives.html), this is generally used for debbugin, since it stores all the logs received by the manager, whether or not it triggers an alert.
When enabled, you can check the archive.json and you will get all the information of the logs received, by the decoders that was decoded and if it triggered or not an alert (no matter the level).

On the other hand this is something that we have better handled in the new wazuh-engine, it will be much easier to deal with cases like this.

I hope this will be useful to you in the future.
