### ISSUE TITLE
The WPK build module workflow fails

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22956]
| Related Issue|
|---|
| https://github.com/wazuh/wazuh/issues/21755 |

## Description

The WPK build workflow has some errors that we should address: https://github.com/wazuh/wazuh/actions/runs/8711560331

```
gh workflow run packages-build-wpk.yml --repo=wazuh/wazuh --ref 'migration/21755-wazuh-packages-redesign' -f revision=999 -f linux_reference=migration/21755-wazuh-packages-redesign -f revision=2 -f is_stage=false -f checksum=true
```

### Case 1

I executed the workflow with GH API call (I only want to build the Linux package) and the workflow ran tasks related to macOS and Windows when it should not, those tasks skipped the execution but they should not be executed since the principle, this leads to mark the stage as success when it does not make sense

![image](https://github.com/wazuh/wazuh/assets/14913942/31ed06d8-d7ac-422b-b210-87f4c8815e2b)

The workflow should only run the desired package tasks

### Case 2

The Linux package build failed with the following error:

![image](https://github.com/wazuh/wazuh/assets/14913942/fde6df52-8059-4cc3-a1d7-8b9da499aaa8)

First, the task should have finished as Failed, not as Success, secondly, the branch used is incorrect and does not match the used branch (check the REFERENCE value

### Case 3

The Linux stage is trying to build the macOS/Windows package, WPK packages should be individual

![image](https://github.com/wazuh/wazuh/assets/14913942/4bf6209a-7bfe-484e-8272-f4d95e314f0d)

---

Check the WPK generation for Linux, macOS, and Windows and ensure that the procedure has the proper control mechanisms in case of failure and that branches are parsed correctly, also, fix the GitHub workflow flow to match the desired task

**Comment by mjcr99** [comment]
## Updates:
**(24/04/2024)**: Opened PR with the proposed solution. Pending its review.
