### ISSUE TITLE
The filebeat build module workflow is missing the  workflow_call item

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#22955]
## Description

The GitHub Action workflow used to build the Filebeat module does not define a `workflow_call` item, this item is needed to be able to use it as a reusable workflow

https://github.com/wazuh/wazuh/blob/migration/21755-wazuh-packages-redesign/.github/workflows/packages-build-manager.yml

The current configuration allows the workflow to be called using the GitHub CLI and the GitHub UI (not yet, we need to merge it)

**Comment by mjcr99** [comment]
## Update
**(17/04/2024)** Opened [PR](https://github.com/wazuh/wazuh/pull/22967) to fix requested changes.
