### ISSUE TITLE
Update idna to version >3.7.0

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#22963]
| Component |
|---|
| Wazuh embedded Python interpreter | 

## Description

During the last scanner of vulnerabilities, it was found that the currently used version of the `idna` package (`2.9`) has a reported vulnerability.

The package should be upgraded to version `3.7` or later to patch it.

**CVEs**:
 - https://github.com/advisories/GHSA-jjg7-2v4v-x38h

**Dependabot alerts**:
- https://github.com/wazuh/wazuh/security/dependabot/44

**Comment by RamosFe** [comment]
# Update

After reading the release history in https://pypi.org/project/idna/3.7/#history, we decided to upgrade from `idna` `2.9` to `3.7`.

**Comment by RamosFe** [comment]
## Update - IT API

All tests passed 🟢 
[archive.zip](https://github.com/wazuh/wazuh/files/15194359/archive.zip)
