### ISSUE TITLE
Modularize API specification

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#22985]
## Description

The [spec.yaml](https://github.com/wazuh/wazuh/blob/master/api/api/spec/spec.yaml) file has over 19K lines and that makes it hard to maintain. Looking for a specific endpoint and going through its parameters and linked schemas is harder than it should, and can only be achieved by either remembering the line number or using the search functionality of the IDE for each one of the objects.

Furthermore, opening the file's blame in the web browser is not possible since it fails with the message `Your blame took too long to compute.`, which makes it difficult to track recent changes.

It would be ideal if we could split the different section into different files to improve its maintainability. We could use a structure based on the specification object types:

```
/api/spec/
    schemas.yaml
    parameters.yaml
    routes.yaml
    responses.yaml
    spec.yaml
```

Or based on how endpoints are organized in the Wazuh API:

```
/api/spec/
    agents/spec.yaml
    groups/spec.yaml
    cluster/spec.yaml
    decoders/spec.yaml
    ...
    spec.yaml
```

Even mixing the two:

```
/api/spec/
    agents/schemas.yaml
    agents/parameters.yaml
    agents/routes.yaml
    agents/responses.yaml
    groups/schemas.yaml
    ...
    spec.yaml
```

We should review if this would affect how the dashboard and documentation teams obtain information about the API and the alternatives we have.

If they require all the information to be in a single file, we could use swagger-cli to put them together.

Related blog: https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
API is probably going to suffer big changes in 5.0. If we do not, we can then retake this issue when it makes sense, but now, it doesn't.
