### ISSUE TITLE
Windows Wazuh Agent should not be deleting queue\diff\file\* on agent start-up

### ISSUE THREAD

**Issue by MalthraxCrypto** [wazuh/wazuh#22984]
|Wazuh version|Component|Install type|Install method|Platform|
-- | -- | -- | -- | --
|4.7.3|syscheck/FIM|Agent|Packages|Windows10|

Trying out Wazuh on Windows, using FIM to monitor and track changes on a single directory of text files, pretty simple

    <directories check_all="yes" whodata="yes" report_changes="yes">C:\monitored</directories>

I'm getting events for file adds/deletes/changes as expected, and the change events DO contain 'diff' info showing what changed... until I restart the agent.  What I'm seeing is on agent START, the contents of `C:\Program Files (x86)\ossec-agent\queue\diff\file` is being erased from the endpoint.

- drag/drop a few dozen files into C:\monitored
- tracking files get created in `C:\Program Files (x86)\ossec-agent\queue\diff\file`
- stop the agent
- `C:\Program Files (x86)\ossec-agent\queue\diff\file` still contains all the diff data
- start the agent
- `C:\Program Files (x86)\ossec-agent\queue\diff\file` is now empty again

Pretty sure this is NOT the intended behavior.

**Comment by MalthraxCrypto** [comment]
Linux agent v4.7.3 is performing the same behavior.  On agent start-up, the contents of /var/ossec/queue/diff are being deleted.

This makes `report_changes` functionally useless, as any time the endpoint is rebooted the diffs are erased, thus preventing changes from being reported.

Unless I'm completely missing the mark here, or there's some hidden option that needs to be configured to persist the data?

**Comment by vikman90** [comment]
@MalthraxCrypto the behavior you've observed is actually expected.

The agent maintains the state of monitored files while it's active. This means that it won't report changes that occurred while it was offline. Upon agent startup, it resets the file database and clears the _C:\Program Files (x86)\ossec-agent\queue\diff_ folder:

https://github.com/wazuh/wazuh/blob/3bf19121e8604c99566fc5e78267648a5161b062/src/syscheckd/src/run_check.c#L246-L261

Hope this helps.
Best regards!
