### ISSUE TITLE
Build in skip_nfs

### ISSUE THREAD

**Issue by justicel** [wazuh/wazuh#23]
Hello, from what I can see it doesn't appear that the skip_nfs flag is compiled in to the latest packages. I get an error like:
./ossec-syscheckd -t
2016/03/15 20:15:53 ossec-config(1230): ERROR: Invalid element in the configuration: 'skip_nfs'.
2016/03/15 20:15:53 ossec-config(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.
2016/03/15 20:15:53 ossec-syscheckd(1202): ERROR: Configuration error at '/var/ossec/etc/ossec.conf'. Exiting.

**Comment by vikman90** [comment]
Hello @justicel. Wazuh repositories provide the version 2.8.3 of OSSEC-HIDS. Regarding the issue https://github.com/ossec/ossec-hids/issues/694, the "skip_nfs" flag isn't compiled until the version 2.9 (beta).

This option is also included in the last stable release of this project. We plan to release packages of OSSEC-Wazuh soon. 

For now, feel free to install OSSEC-Wazuh from GitHub. You can find help to do it from http://wazuh-documentation.readthedocs.org/en/latest/wazuh_installation.html.

Best regards.

**Comment by ddpbsd** [comment]
According to the documentation for skip_nfs, it won't be included until 2.9. http://ossec.github.io/docs/syntax/head_ossec_config.rootcheck.html?highlight=skip_nfs#element-skip_nfs
