### ISSUE TITLE
Wazuh manager unabled to start for unknown reason

### ISSUE THREAD

**Issue by XandorMaker** [wazuh/wazuh#23067]
|WAZUH_VERSION":"v4.7.3" | manager |  single node - server | all in one Package | Ubuntu 22.04 LTS|

Hi everyone, 

My Wazuh installation was working fine for 4 monthes and almost a week ago wazuh manager after a simple server restart was anable to start.
I've checked last Ubuntu updates and nothing is connected to Wazuh. 
Here is the list of latest updates (wazuh stoped working 15 april)
Start-Date: 2024-04-13  06:33:49
Commandline: /usr/bin/unattended-upgrade
Upgrade: libnss3:amd64 (2:3.98-0ubuntu0.22.04.1, 2:3.98-0ubuntu0.22.04.2)
End-Date: 2024-04-13  06:33:50

Start-Date: 2024-04-16  06:31:46
Commandline: /usr/bin/unattended-upgrade
Upgrade: libgnutls30:amd64 (3.7.3-4ubuntu1.4, 3.7.3-4ubuntu1.5)
End-Date: 2024-04-16  06:31:47

Start-Date: 2024-04-18  06:10:02
Commandline: /usr/bin/unattended-upgrade
Upgrade: klibc-utils:amd64 (2.0.10-4, 2.0.10-4ubuntu0.1), libklibc:amd64 (2.0.10-4, 2.0.10-4ubuntu0.1)
End-Date: 2024-04-18  06:10:13

Start-Date: 2024-04-20  06:55:19
Commandline: /usr/bin/unattended-upgrade
Install: linux-modules-6.5.0-1018-gcp:amd64 (6.5.0-1018.18~22.04.1, automatic), linux-headers-6.5.0-1018-gcp:amd64 (6.5.0-1018.18~22.04.1, automatic), linux-gcp-6.5-headers-6.5.0-1018:amd64 (6.5.0-1018.18~22.04.1, automatic), linux-image-6.5.0-1018-gcp:amd64 (6.5.0-1018.18~22.04.1, automatic)
Upgrade: linux-image-gcp:amd64 (6.5.0.1017.17~22.04.1, 6.5.0.1018.18~22.04.1), linux-headers-gcp:amd64 (6.5.0.1017.17~22.04.1, 6.5.0.1018.18~22.04.1), linux-gcp:amd64 (6.5.0.1017.17~22.04.1, 6.5.0.1018.18~22.04.1)
End-Date: 2024-04-20  06:56:04

Start-Date: 2024-04-20  06:56:10
Commandline: /usr/bin/unattended-upgrade
Upgrade: libc6:amd64 (2.35-0ubuntu3.6, 2.35-0ubuntu3.7)
End-Date: 2024-04-20  06:56:12

Start-Date: 2024-04-20  06:56:17
Commandline: /usr/bin/unattended-upgrade
Upgrade: locales:amd64 (2.35-0ubuntu3.6, 2.35-0ubuntu3.7)
End-Date: 2024-04-20  06:56:21

Start-Date: 2024-04-20  06:56:26
Commandline: /usr/bin/unattended-upgrade
Upgrade: libc-bin:amd64 (2.35-0ubuntu3.6, 2.35-0ubuntu3.7)
End-Date: 2024-04-20  06:56:27

Start-Date: 2024-04-20  06:56:32
Commandline: /usr/bin/unattended-upgrade
Remove: linux-headers-6.5.0-1015-gcp:amd64 (6.5.0-1015.15~22.04.1), linux-gcp-6.5-headers-6.5.0-1015:amd64 (6.5.0-1015.15~22.04.1)
End-Date: 2024-04-20  06:56:35

Start-Date: 2024-04-20  06:56:39
Commandline: /usr/bin/unattended-upgrade
Remove: linux-image-6.5.0-1015-gcp:amd64 (6.5.0-1015.15~22.04.1), linux-modules-6.5.0-1015-gcp:amd64 (6.5.0-1015.15~22.04.1)
End-Date: 2024-04-20  06:56:44

Actual wazuh statuses: 

root@wazuh-1:~# systemctl start wazuh-manager
Job for wazuh-manager.service failed because the control process exited with error code.
See "systemctl status wazuh-manager.service" and "journalctl -xeu wazuh-manager.service" for details.
root@wazuh-1:~# journalctl -xeu wazuh-manager.service
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:695 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:695 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:695 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:695 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:695 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:753 at wm_vuldet_read_pr>
Apr 22 16:39:15 wazuh-1 env[4386]: 2024/04/22 16:39:15 wazuh-modulesd[4386] wmodules-vuln-detector.c:753 at wm_vuldet_read_pr>
Apr 22 16:39:16 wazuh-1 env[4356]: Starting Wazuh v4.7.3...
Apr 22 16:39:28 wazuh-1 env[4356]: wazuh-apid did not start correctly.
Apr 22 16:39:28 wazuh-1 systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit wazuh-manager.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Apr 22 16:39:28 wazuh-1 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit wazuh-manager.service has entered the 'failed' state with result 'exit-code'.
Apr 22 16:39:28 wazuh-1 systemd[1]: Failed to start Wazuh manager.
░░ Subject: A start job for unit wazuh-manager.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit wazuh-manager.service has finished with a failure.
░░
░░ The job identifier is 3225 and the job result is failed.
Apr 22 16:39:28 wazuh-1 systemd[1]: wazuh-manager.service: Consumed 5.554s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit wazuh-manager.service completed and consumed the indicated resources.

root@wazuh-1:~# systemctl status wazuh-indexer
● wazuh-indexer.service - Wazuh-indexer
     Loaded: loaded (/lib/systemd/system/wazuh-indexer.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-22 15:36:15 CEST; 1h 7min ago
       Docs: https://documentation.wazuh.com
   Main PID: 497 (java)
      Tasks: 131 (limit: 9506)
     Memory: 5.5G
        CPU: 9min 47.565s
     CGroup: /system.slice/wazuh-indexer.service
             └─497 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.n>

Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwa>
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:>
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.cli.Command.main(Command.java:101)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137)
Apr 22 15:35:49 wazuh-1 systemd-entrypoint[497]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103)
Apr 22 15:36:15 wazuh-1 systemd[1]: Started Wazuh-indexer.

root@wazuh-1:~# systemctl status filebeat
● filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
     Loaded: loaded (/lib/systemd/system/filebeat.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-22 15:57:36 CEST; 46min ago
       Docs: https://www.elastic.co/products/beats/filebeat
   Main PID: 3024 (filebeat)
      Tasks: 8 (limit: 9506)
     Memory: 12.4M
        CPU: 719ms
     CGroup: /system.slice/filebeat.service
             └─3024 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/sha>

Apr 22 15:57:36 wazuh-1 systemd[1]: Started Filebeat sends log files to Logstash or directly to Elasticsearch..

Any ideas would be apritiated

**Comment by pereyra-m** [comment]
Hello @XandorMaker !

I can't find the exact failure reason in the provided information, could you please upload the `ossec.conf`,  `ossec.log` and `api.log` files from the manager? Don't forget to remove any sensitive data.

In this case, I'd try to isolate the problem: try disabling modules like **syscollector**, **vulnerability detector**, etc. one by one and restart the manager each time.

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open if necessary
