### ISSUE TITLE
Treatment of vendor field when using NVD data

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#23078]
## Description
This issue aims to use the vendor field to match as 1:1 during the package scanning when the feed to be used is derived from nvd data.

## Expected behavior
- When the feed to be used is NVD and the package.vendor is not equal to " " or empty, compare 1:1 to match if the application is an affected candidate. If the vendor is equal to " " or empty, avoid the package scanning because you don't have sufficient information, and this will avoid false positives.
- When package.name match with someone's translation, use the derived vendor to realize the 1:1 match with the vulnerability.vendor

### Glosary
- **package** -> syscollector data
- **vulnerability** -> data coming from the vulnerability feed

## DoD
- Add tests
- Reviewer validation with evidence.

**Comment by sebasfalcone** [comment]
## Important considerations
To succeed in the implementation of this issue we will need to take into consideration some implications

### When is the vendor field used
The vendor field should only matter when the cna used is the NVD

### Package information
The information we use on the scanner to match against the right package is passed as a simple argument (packageName):
https://github.com/wazuh/wazuh/blob/e9e6e7193f20d91f9a053d3f9d3ba07a7525a233/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp#L500-L504

https://github.com/wazuh/wazuh/blob/e9e6e7193f20d91f9a053d3f9d3ba07a7525a233/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp#L116-L118

https://github.com/wazuh/wazuh/blob/e9e6e7193f20d91f9a053d3f9d3ba07a7525a233/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp#L522-L523

With the addition of the `packageVendor` now, and other fields like `packageVersion` in future implementations, this won't scale

A possible solution would be to generate a new data structure that holds these values (translated or not) and pass it to the method

### Empty vendor fields
There are some scenarios where the vendor field obtained from syscollector is empty (Grub on macOS)

This is why we should ignore the vendor field if it's empty
