### ISSUE TITLE
Wazuh agent's Windows app not available after installation

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#23070]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3 | Wazuh Agent App | Agent | Packages | Windows 11 |

After installing a Wazuh Agent in Windows 11, the APP is not available among the installed apps:

# Windows Agent deployment
## System information
```
OS Name	Microsoft Windows 11 Enterprise Evaluation
Version	10.0.22631 Build 22631
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	52-W11-AGENT
System Manufacturer	innotek GmbH
System Model	VirtualBox
System Type	x64-based PC
System SKU	Unsupported
Processor	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz, 2112 Mhz, 2 Core(s), 2 Logical Processor(s)
BIOS Version/Date	innotek GmbH VirtualBox, 12/1/2006
SMBIOS Version	2.5
BIOS Mode	UEFI
BaseBoard Manufacturer	Oracle Corporation
BaseBoard Product	VirtualBox
BaseBoard Version	1.2
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\Windows
System Directory	C:\Windows\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.2506"
User Name	52-W11-AGENT\vagrant
Time Zone	Pacific Daylight Time
Installed Physical Memory (RAM)	3.98 GB
Total Physical Memory	3.98 GB
Available Physical Memory	1.71 GB
Total Virtual Memory	5.36 GB
Available Virtual Memory	3.16 GB
Page File Space	1.38 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Audit
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
A hypervisor has been detected. Features required for Hyper-V will not be displayed.	
```
## Agent installation
```bash
PS C:\Users\vagrant\Downloads> .\wazuh-agent-4.7.3-1.msi /q WAZUH_MANAGER="192.168.123.50"
PS C:\Users\vagrant\Downloads> NET START Wazuh
The Wazuh service is starting.
The Wazuh service was started successfully.
```

After installing the Wazuh Agent, I am not able to see the app between the installed apps, but the OSSEC directory:
![image](https://github.com/wazuh/wazuh/assets/75255206/2d771374-e513-4e3e-a303-07127a404317)
![image](https://github.com/wazuh/wazuh/assets/75255206/466d7017-b745-4326-9f06-8382b136ee61)
![image](https://github.com/wazuh/wazuh/assets/75255206/b7b18c56-72b2-4975-b607-dcc06a24756b)

But when checking the Wazuh agent state file, it displays that it is correctly connected:
![image](https://github.com/wazuh/wazuh/assets/75255206/06fce9de-6dbf-4469-976f-d9af8e68a81b)

**Comment by vikman90** [comment]
## Trying to reproduce

I've installed [wazuh-agent-4.8.0-1.msi](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.8.0-1.msi), and I can see both the agent installation and the shortcut in the Start menu:

![image](https://github.com/wazuh/wazuh/assets/10536251/2ca8a61d-a65f-4d15-b5f9-73f6703c611c)

**Comment by nmkoremblum** [comment]
It seems that I was looking in the wrong menu, I get the same results as @vikman90 

![image](https://github.com/wazuh/wazuh/assets/75255206/439edd6b-9fa3-4b9f-b4dc-ba2cf7b8d34f)
