### ISSUE TITLE
Wazuh packages redesign tier 1 - Adapt WPK logic

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23071]
## Description

Due to https://github.com/wazuh/wazuh/issues/21152, the WPK work done in https://github.com/wazuh/wazuh/issues/22321 needs to be done again partially, basically due to:

- Linux WPK logic will change
  - WPK files will store the package instead of compiling it from sources
- Nomenclature must specify if the package is an RPM or DEB package. New requirement: https://github.com/wazuh/internal-devel-requests/issues/187#issuecomment-2069924265

Due to those changes, the current development cannot be adapted while the WPK is being improved

## Tasks

- [x] Adapt WPK logic to the changes done in https://github.com/wazuh/wazuh/issues/21152
- [x] Change and adapt WPK nomenclature (check https://github.com/wazuh/internal-devel-requests/issues/187#issuecomment-2069924265)

**Comment by rauldpm** [comment]
This issue will be blocked until the "Improve WPKs" objective provides the necessary changes

**Comment by rauldpm** [comment]
After speaking with @MarcelKemp, we will face this issue as follows:

- Merge Improve WPKs changes into the development branch
- Check WPK functionality
- Adapt WPK functionality to current requirements

**Comment by rauldpm** [comment]
Changed status to Backlog as the WPK development has been merged

**Comment by MarcelKemp** [comment]
The changes meet the expected requirements. 
It has also been tested for Linux and Windows and works correctly. It remains to be tested on macOS when it is available.
