### ISSUE TITLE
Update aiohttp to version >=3.9.4

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#23089]
| Component |
|---|
| Wazuh embedded Python interpreter | 

## Description

During the last scanner of vulnerabilities, it was found that the currently used version of the `aiohttp` package (`3.9.3`) has a reported vulnerability.

The package should be upgraded to version `3.9.4` or later to patch it.

**CVEs**:
 - https://github.com/advisories/GHSA-7gpw-8wmc-pm8g

**Dependabot alerts**:
- https://github.com/wazuh/wazuh/security/dependabot/45

**Comment by RamosFe** [comment]
## Update

After reading the release history in https://pypi.org/project/aiohttp/3.9.5/#history, we decided to upgrade from `aiohttp` `3.9.3` to `3.9.5`.

**Comment by RamosFe** [comment]
## Update - IT API

Results where described in https://github.com/wazuh/wazuh/issues/22963#issuecomment-2091787448.
