### ISSUE TITLE
Incorrect OS version detected by Wazuh agent on SUSE Linux Enterprise

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#23083]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3| Agentd | Manager | Packages | v4.7.3 |

### Description

A user has reported that the Wazuh agent is inaccurately reporting the version of a Wazuh SUSE 11 Linux agent. In /var/ossec/logs/ossec.log, the following line is observed:
```
2024/04/22 13:17:25 wazuh-agentd: INFO: Version detected -> Linux |HOSTNAME |3.0.101-0.47.106.11-default |#1 SMP Tue Jan 2 10:46:28 UTC 2018 (afabf7c) |x86_64 [Ubuntu|ubuntu: 0.0] - Wazuh v4.7.3
```

We've identified that the version and OS are incorrectly detected as 'Ubuntu: 0.0'. However, the syscollector appears to correctly identify the system's OS

<details>

<summary>  Syscollector OS endpoint </summary>

```
{
   "data": {
      "affected_items": [
         {
            "os": {
               "major": "11",
               "name": "SuSE Linux",
               "platform": "suse",
               "version": "11"
            },
            "scan": {
               "id": 0,
               "time": "2024-04-01T15:49:30+00:00"
            },
            "sysname": "Linux",
            "version": "#1 SMP Tue Jan 2 10:46:28 UTC 2018 (afabf7c)",
            "hostname": "HOSTNAME",
            "architecture": "x86_64",
            "release": "3.0.101-0.47.106.11-default",
            "agent_id": "AGENTID"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All specified syscollector information was returned",
   "error": 0
```

</details>

In addition, the config profile set in the agent was correctly set to suse:
```
<config-profile>suse, suse11, suse11.3</config-profile>
```

### Evidences

<details>

<summary> <code>/etc/SuSE-release</code></summary>

```
WTC-JBC96:~ # cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

</details>

**Comment by Nicogp** [comment]
## Update 25/04/2024

- Preparation of the environment.
- So far it has not been possible to reproduce the error.

`2024/04/25 17:45:31 wazuh-agentd: INFO: Version detected -> Linux |sles11-sp3 |3.0.101-0.47.71-default |#1 SMP Thu Nov 12 12:22:22 UTC 2015 (b5b212e) |x86_64 [SuSE Linux|suse: 11] - Wazuh v4.7.3`

**Comment by Nicogp** [comment]
Hi @Rebits 
Could you get more information about the environment?

1. I need to see the contents of the file `/etc/os-release` and/or `/usr/lib/os-release`
2. Does the file `/etc/lsb-release` exist? What is its content? Was it created manually? (by default it doesn't exist for SuSE)

I suspect it is entering through this part of the code:
https://github.com/wazuh/wazuh/blob/4.7/src/shared/version_op.c#L589
but for that, information should be missing in `/etc/os-release` and/or `/usr/lib/os-release` and `/etc/lsb-release` should exist.

**Comment by Rebits** [comment]
The user has provide the following information
No ` /etc/os-release` or `/usr/lib/os-release` exists in the host, only the provided `/etc/SuSE-release`:
```
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

-  `/etc/lsb-release`:
```
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64"
```

**Comment by vikman90** [comment]
SuSE 11 reached EOL on Jan 11, 2021.

As of SuSE 12, the OS provides `/etc/os-release`:

> 9.2.2.2 Use /etc/os-release Instead of /etc/SuSE-release
>
> Starting with SLE 12, the /etc/SuSE-release file has been deprecated. Do not use it to identify a SUSE Linux Enterprise system anymore. This file will be removed in a future Service Pack or release.
To determine the release, use the file /etc/os-release instead. This file is a cross-distribution standard to identify Linux systems. For more information about the syntax, see the os-release man page (man os-release).

**Comment by Nicogp** [comment]
## Update 30/04/2024

- Changes were made to the code
- Fixed UTs
- PR created
