### ISSUE TITLE
Increase in FD by wazuh-modulesd

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#23082]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta6 | Wazuh Manager | Manager | Packages | CentOS |

During testing in [Release 4.8.0 - Beta 6 - Footprint Metrics - ALL-EXCEPT-LOGCOLLECTOR](https://github.com/wazuh/wazuh/issues/23020) it has been detected a high increase in the FD metric by `wazuh-modulesd`. This pattern has not been detected in any previous version, only in [4.8.0 - Alpha 2](https://github.com/wazuh/wazuh/issues/21499). 

The plots are compared to https://github.com/wazuh/wazuh/issues/22297.

| 4.8.0 | 4.7.3 |
| --- | --- | 
| ![image](https://github.com/wazuh/wazuh/assets/101177239/29b946c6-84e2-4f3c-bee0-ff8de45f44cc)  | ![image](https://github.com/wazuh/wazuh/assets/101177239/97f03b6f-a2ec-4cc8-85c1-9222fc765b3a)|

**Comment by Dwordcito** [comment]
This increase is related to the LSM tree of rocksdb.

I explain this in the beta 5 issue.

https://github.com/wazuh/wazuh/issues/22841#issuecomment-2059826516
