### ISSUE TITLE
Include `opensearch-py` in the embedded Python interpreter

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23097]
## Description
We need to, as part of #23058, include a new Python library in the wazuh embedded interpreter. This new dependency is:
- [**opensearch-py**](https://opensearch.org/docs/latest/clients/python-low-level/)

These are its sub-dependencies:
```
opensearch-py==2.5.0
├── certifi [required: >=2022.12.07, installed: 2023.7.22]
├── python-dateutil [required: Any, installed: 2.8.1]
│   └── six [required: >=1.5, installed: 1.16.0]
├── requests [required: >=2.4.0,<3.0.0, installed: 2.31.0]
│   ├── certifi [required: >=2017.4.17, installed: 2023.7.22]
│   ├── charset-normalizer [required: >=2,<4, installed: 2.0.4]
│   ├── idna [required: >=2.5,<4, installed: 2.9]
│   └── urllib3 [required: >=1.21.1,<3, installed: 1.26.18]
├── six [required: Any, installed: 1.16.0]
└── urllib3 [required: >=1.26.18,<2, installed: 1.26.18]
```

All of them, with the required version, are already included in our interpreter.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by davidjiglesias** [comment]
Due to the algorithmic nature of the new vulnerability detector module, the solution at hand can lead to an unrecoverable scenario. This makes the opensearch package unnecessary.
