### ISSUE TITLE
Unable to initialize IndexerConnector after upgrade

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23092]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta6 | Vulnerability Detection/IndexerConnector| Manager | Packages| Ubuntu Jammy |

## Description

During testing at https://github.com/wazuh/wazuh/issues/23062, it has been found that after upgrading an AIO from 4.7.3 to 4.8.0 Beta 6, IndexerConnector is not able to initialize:

```
2024/04/23 16:32:32 indexer-connector[134487] indexerConnector.cpp:204 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities': No available server. Retrying in 60 seconds.
```

The steps followed have been the same as in the upgrade documentation. Once everything was updated, the manager was configured with the updated `<vulnerability-detection>` configuration and the credentials were added to `wazuh-keystore`:

```shell
# history
  .
  .
  .
  163  egrep -iE "err|warn" /var/ossec/logs/ossec.log 
  164  nano /var/ossec/etc/ossec.conf
  165  systemctl restart wazuh-manager
  166  egrep "WARNING" /var/ossec/logs/ossec.log 
  167  /var/ossec/bin/wazuh-keystore -f indexer -k username -v admin
  168  /var/ossec/bin/wazuh-keystore -f indexer -k password -v changeme
  169  systemctl restart wazuh-manager
  170  egrep "WARNING" /var/ossec/logs/ossec.log 

```

However, the IndexerConnector failed message appears constantly, and in the dashboard we cannot access the Vulnerability Detection module:

![image](https://github.com/wazuh/wazuh/assets/80041853/7ad1901f-49c6-41df-b2cf-e967f2a38c8c)

<details>
<summary>Environment logs</summary>
<br>

- Before upgrade: [473_ossec.zip](https://github.com/wazuh/wazuh/files/15080090/473_ossec.zip)
- After upgrade: [after_upgrade_ossec.zip](https://github.com/wazuh/wazuh/files/15080091/after_upgrade_ossec.zip)

</details>

**Comment by Dwordcito** [comment]
We need the environment to make an RCA for this type of issue.

In development environments, this issue its not reproduced.

**Comment by juliamagan** [comment]
<details>
<summary>Requested logs</summary>
<br>
[indexer-before-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097000/indexer-before-upgrade.tar.gz)
[indexer-after-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097001/indexer-after-upgrade.tar.gz)
[etc-indexer-before-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097002/etc-indexer-before-upgrade.tar.gz)
[etc-indexer-after-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097003/etc-indexer-after-upgrade.tar.gz)
[etc-dashboard-before-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097004/etc-dashboard-before-upgrade.tar.gz)
[etc-dashboard-after-upgrade.tar.gz](https://github.com/wazuh/wazuh/files/15097006/etc-dashboard-after-upgrade.tar.gz)
[usr-share-dashboard-data-before-upgrade.zip](https://github.com/wazuh/wazuh/files/15097031/usr-share-dashboard-data-before-upgrade.zip)
[usr-share-dashboard-data-after-upgrade.zip](https://github.com/wazuh/wazuh/files/15097032/usr-share-dashboard-data-after-upgrade.zip)


</details>

In addition, the original instance has been modified, and a new identical one has been created to give the development team access to the instance with the indexer error.

**Comment by sebasfalcone** [comment]
## Investigation
After investigating the issue, I've found that the problem was due to a misconfiguration of the module.

If we check for the ossec.conf file and search the `<indexer>` block:
```xml
root@ip-172-31-36-133:/etc# cat /var/ossec/etc/ossec.conf | grep "<indexer>" -A12
  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://172.31.83.61:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/pki/filebeat/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/pki/filebeat/node-2.pem</certificate>
      <key>/etc/pki/filebeat/node-2-key.pem</key>
    </ssl>
  </indexer>
--
  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://0.0.0.0:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/filebeat/certs/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
      <key>/etc/filebeat/certs/filebeat-key.pem</key>
    </ssl>
  </indexer>
```

We see that the second configuration block wasn't adapted and it's overwriting the first one. This is the root cause of the problem

>[!IMPORTANT] 
> Is expected that the second configuration block appears, it was introduced at
- https://github.com/wazuh/wazuh-packages/pull/2684
