### ISSUE TITLE
Vulnerability Detector is not generating alerts for NPM packages in Ubuntu 20.04

### ISSUE THREAD

**Issue by nbertoldo** [wazuh/wazuh#23113]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta6 | Vulnerability detector | Manager | Packages | Ubuntu 20.04 x86_64 |

### Description

It has been detected in https://github.com/wazuh/wazuh/issues/23045 that _Vulnerability Detection_ is currently unable to generate alerts for NPM packages on Ubuntu 20.04.

### Steps to reproduce
- Install a manager
- Install and register an Ubuntu 20.04 agent
- Install a NPM package

```console
root@ip-172-31-36-139:/home/ubuntu# npm install -g axios@0.1.0
npm WARN deprecated axios@0.1.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
+ axios@0.1.0
added 2 packages from 2 contributors in 0.556s
root@ip-172-31-36-139:/home/ubuntu# npm list -g
/usr/local/lib
└─┬ axios@0.1.0
  └── es6-promise@1.0.0

```

- Check that after Syscollector scans the package is detected and the vulnerability was included in the inventory but no alert was generated.

**Inventory**

![image](https://github.com/wazuh/wazuh/assets/117279646/e2ca39dc-1172-4324-9e38-2b737a829b50)

**Alerts**

![image](https://github.com/wazuh/wazuh/assets/117279646/53ccf60b-12c5-48d0-8cfc-efae12bdc547)

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela Try to replicate this issue

**Comment by GabrielEValenzuela** [comment]
# Analysis result

## Environment

- Manager installed from source with branch 4.8.0
- Docker agent Ubuntu 20

```xml
<wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1m</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>

    <!-- Database synchronization settings -->
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>
```

## Result

![image](https://github.com/wazuh/wazuh/assets/27935340/106042f6-9b10-419d-b0f2-3fcbbac07742)


Alerts were generated successfully. No update process was taken during this step.

**Comment by sebasfalcone** [comment]
The reported problem may be due to a fluke on the test, closing this issue
