### ISSUE TITLE
Add test coverage for `_conf2json`

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#23119]
|Wazuh version|Component|
|---|---|
| 4.8.0 | API |

## Description

The `_conf2json` is the function in charge of parsing the `ossec.conf` file and converting it to `JSON`, but we don't have any test that gives us a safety net when modifying the logic of it (Except some IT tests). We should create new unit tests to cover the multiple `sections` described in https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html.

This UT could help us avoid bugs like https://github.com/wazuh/wazuh/issues/23095.

**Comment by davidjiglesias** [comment]
ossec.conf almost dissapears in 5.0, not worth it now.
