### ISSUE TITLE
API fails with `Timeout executing API request` when huge list files are in place

### ISSUE THREAD

**Issue by pr3l14t0r** [wazuh/wazuh#23126]
|Wazuh version|Component|
|---|---|
| v4.7.1 | Wazuh API |

## Description

Ahoy! I am having a small problem with the Wazuh Dashboard/ API when i want to open my CDB lists.

I recently added IP-Addresses for a github whitelist, and since Wazuh doesn't support cidr-notation in CDB, the ip addresses need to be expanded. This results in quite large lists

```
[root@wazuh-server bin]# ls -lah /var/ossec/etc/lists/github/ip-whitelists/
total 1.3G
drwxrwx--- 2 wazuh wazuh 4.0K Apr 21 18:03 .
drwxrwx--- 3 wazuh wazuh 4.0K Apr 21 18:00 ..
-rw-rw---- 1 wazuh wazuh 439M Apr 21 18:02 actions
-rw-rw---- 1 wazuh wazuh 881M Apr 21 18:03 actions.cdb
-rw-rw---- 1 wazuh wazuh 183K Apr 21 18:00 api
-rw-rw---- 1 wazuh wazuh 406K Apr 21 18:03 api.cdb
-rw-rw---- 1 wazuh wazuh   72 Apr 21 18:02 dependabot
-rw-rw---- 1 wazuh wazuh 2.2K Apr 21 18:03 dependabot.cdb
-rw-rw---- 1 wazuh wazuh 184K Apr 21 18:00 git
-rw-rw---- 1 wazuh wazuh 406K Apr 21 18:03 git.cdb
-rw-rw---- 1 wazuh wazuh 414K Apr 21 18:00 github_enterprise_importer
-rw-rw---- 1 wazuh wazuh 637K Apr 21 18:03 github_enterprise_importer.cdb
-rw-rw---- 1 wazuh wazuh 203K Apr 21 18:00 hooks
-rw-rw---- 1 wazuh wazuh 425K Apr 21 18:03 hooks.cdb
-rw-rw---- 1 wazuh wazuh  417 Apr 21 18:00 importer
-rw-rw---- 1 wazuh wazuh 2.9K Apr 21 18:03 importer.cdb
-rw-rw---- 1 wazuh wazuh  528 Apr 21 18:00 packages
-rw-rw---- 1 wazuh wazuh 3.1K Apr 21 18:03 packages.cdb
-rw-rw---- 1 wazuh wazuh  129 Apr 21 18:00 pages
-rw-rw---- 1 wazuh wazuh 2.3K Apr 21 18:03 pages.cdb
-rw-rw---- 1 wazuh wazuh 183K Apr 21 18:00 web
-rw-rw---- 1 wazuh wazuh 406K Apr 21 18:03 web.cdb
```

Overall the `../lists` dir has ~1.3GB now:

```text
[root@wazuh-server bin]# du -sh /var/ossec/etc/lists/
1.3G    /var/ossec/etc/lists/
```

When I try to open the CDB Lists from the GUI, the request fails with a timeout. This is what happens in the background, taken from Developer Tools in chrome: 

Request:
```json
{"method":"GET","path":"/lists","body":{"params":{"offset":0,"limit":10,"sort":"+filename"}},"id":"default"}
```

Response:
```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Wazuh API error: ERR_BAD_RESPONSE - Timeout executing API request"
}
```

As you can see, i am no longer able to fetch and open the CDB lists from the dashboard. At the moment i can only maintain them via commandline (ssh). 

I have found [this article](https://groups.google.com/g/wazuh/c/xH8OWNyIE1w) and tried to adjust the setting `timeout_cluster_request` from 20 to 120 in both of these files: 

```text
[root@wazuh-server bin]# find /var/ossec/ -name 'cluster.json'
/var/ossec/framework/wazuh/core/cluster/cluster.json
/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.7.1-py3.9.egg/wazuh/core/cluster/cluster.json
```

...restarted `wazuh-manager` and `wazuh-dashboard` service, but the issue still persists. 

I am not quite sure whether `timeout_cluster_request` since the requests fails after 10 seconds already, which seems to be the expected timeout for API requests according to information from [this](https://github.com/wazuh/wazuh/issues/22718#issuecomment-2037011751) comment in issue #22718 . 

Can somebody help me out here? Is there a setting i can adjust?

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by pr3l14t0r** [comment]
Update: I've started a discussion in [Slack](https://wazuh.slack.com/archives/C0A933R8E/p1714027847337989) as well. 

Meanwhile i have added
```text
timeout: 120000
```

to the dashboard config in file `/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml` . But this also didn't help with my issue. The request still fails with

```json
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "Wazuh API error: ERR_BAD_RESPONSE - Timeout executing API request"
}
```

**Comment by davidjiglesias** [comment]
We do not support these kind of huge files.
