### ISSUE TITLE
Check Wazuh-Agent compatibility with new version AlmaLinux 9.4 Beta

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh#23135]
# Description
Hello team, this issue is to check the full compatibility of Wazuh on the newfound version of AlmaLinux 9.4 Beta operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/23132

For this, it is necessary to perform the following tests to check that everything works as expected:

- [x] Agent and server (if possible) installations.
- [x] O.S. reporting in the interface.
- [x] WPK  upgrade.
- [x] Enrollment and connectivity with the manager.
- [x] FIM: Real-time and who-data engines (if available).
- [x] SCA: Policy support.
- [x] Vulnerability Detector: Vulnerability support.
- [x] Syscollector: Complete inventory.
- [x] Active Response: port blocking.
- [x] Log capture.

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent and server, (enrollment and connectivity with the manager)

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/e296b77d-d7ca-4618-8389-ee8464cef9ae" alt="Con_dash">
</details>

<details>
<summary>Agent Log</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/6ceb703f-8752-4a5a-878c-735d97e35a3b" alt="Console">
</details>

### :green_circle: FIM scheduled

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/1dd08203-b953-4daa-8aa9-12e304aa7f4d">
</details>

## :green_circle: FIM Real-time
<details>
<summary>Configuration on the agent</summary>

  ```
    <frequency>4</frequency>
    <directories realtime="yes">/var/log/testrealtime</directories>
  ```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/60e78f35-4e1d-442d-a2d1-554ff6a82c08">
</details>



## :green_circle: Upgrade using WPK


<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/27791973-e5c7-484d-a1d3-80074c0b46c3">
</details>


## :yellow_circle: SCA support
No official SCA policies are available ( [check](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html) this list).

Since it is not listed at [CIS Benchmarks](https://downloads.cisecurity.org/#/), no issue will be created.

SCA module is tested anyway, with a custom policy.

Configuration

[This usecase](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/use-cases.html#detecting-keyword-in-a-file) is used to test SCA module.

<details>
<summary>Manager log:</summary>

  ```
** Alert 1715040159.2068: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 May 07 00:02:39 (ce84769b410b) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":92309736,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1715040147,"end_time":1715040147,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1"}
sca.type: summary
sca.scan_id: 92309736
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml

** Alert 1715040168.3338: - sca,gdpr_IV_35.7.d,pci_dss_2.2,nist_800_53_CM.1,tsc_CC7.1,tsc_CC7.2,
2024 May 07 00:02:48 (ce84769b410b) any->sca
Rule: 19005 (level 9) -> 'SCA summary: SCA use case: Keyword check: Score less than 30% (0)'
{"type":"summary","scan_id":92309736,"name":"SCA use case: Keyword check","policy_id":"keyword_check","file":"keywordcheck.yml","description":"Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.","references":"https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/index.html,https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html","passed":0,"failed":1,"invalid":0,"total_checks":1,"score":0,"start_time":1715040147,"end_time":1715040147,"hash":"5d28a90f4498a81461efbaf6f628a19d9778390bb5c81a393dd936181cc3d826","hash_file":"a33741eefba60ba75052477564b607cc97bdf36c773194c7ead40f30e356ec4d","force_alert":"1","force_alert":"1"}
sca.type: summary
sca.scan_id: 92309736
sca.policy: SCA use case: Keyword check
sca.description: Guidance for checking for a keyword or phrase in files on Ubuntu endpoints.
sca.policy_id: keyword_check
sca.passed: 0
sca.failed: 1
sca.invalid: 0
sca.total_checks: 1
sca.score: 0
sca.file: keywordcheck.yml

  ```
</details>
<details>
<summary>Agent log:</summary>

  ```
730:2024/05/07 00:32:58 sca[4971] wm_sca.c:152 at wm_sca_main(): INFO: Module started.
732:2024/05/07 00:32:58 sca[4971] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/ruleset/sca/sca_unix_audit.yml'
733:2024/05/07 00:32:58 sca[4971] wm_sca.c:191 at wm_sca_main(): INFO: Loaded policy '/var/ossec/etc/custom-sca-files/keywordcheck.yml'
741:2024/05/07 00:32:58 sca[4971] wm_sca.c:329 at wm_sca_start(): INFO: Starting Security Configuration Assessment scan.
  ```

</details>

<details>
<summary>Inventory:</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/c250b541-e855-4913-8ae9-8285c8f9b59a">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/a01daf4a-17be-4d91-834e-3e692fb22955">
</details>


## :green_circle: Vulnerability detector


<details>
<summary>Manager Config by default</summary>

```
    <!-- Alma Linux OS vulnerabilities -->
    <provider name="almalinux">
      <enabled>yes</enabled>
      <os>8</os>
      <os>9</os>
      <update_interval>1m</update_interval>
    </provider>
```


</details>

<details>
<summary>Dashboard</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/79ae0873-6188-4447-8a65-d4a405238f93">
</details>

## :green_circle: Active response

<details>
<summary>Manager configuration:</summary>

```
<ossec_config>
  <active-response>
    <disabled>no</disabled>
    <command>restart-wazuh</command>
    <location>defined-agent</location>
    <agent_id>001</agent_id>
    <level>7</level>
  </active-response>
</ossec_config>
```
</details>

<details>
<summary>Result:</summary>
<img src="https://github.com/wazuh/wazuh/assets/21695385/8653ae8b-1756-432e-933d-9850ba147488">
</details>


## :green_circle: Log Capture

<details>
<summary>Agent configuration:</summary>

```
  <localfile>
    <location>/var/log/log_capture.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
</details>

<details>
<summary>Result</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/bed340e0-2338-4928-b86e-68df889250fc">
</details>


## :green_circle:  Syscollector


<details>
<summary>Inventory</summary>
 <img src="https://github.com/wazuh/wazuh/assets/21695385/0a2d1275-3e1c-4e5b-9357-ff568ddd7f94">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/4539ff30-2074-479a-b094-b45bc5f3dff6">
 <img src="https://github.com/wazuh/wazuh/assets/21695385/d17c8079-4a18-48b4-9fee-e810a7eeb9e8">
</details>

**Comment by lchico** [comment]
# Update 
Downloaded a vagrant box, and will test it tomorrow.

**Comment by lchico** [comment]
# Update
Here's why I added the :yellow_circle: to the whodata test, according to this documentation and blog:
- [Monitored endpoint](https://documentation.wazuh.com/current/user-manual/capabilities/system-calls-monitoring/audit-configuration.html)
- [First steps with Linux Audit system](https://wazuh.com/blog/monitoring-root-actions-on-linux-using-auditd-and-wazuh/#:~:text=First%20steps%20with%20Linux%20Audit%20system)

The blog mentions that `audispd-plugins` is required for Debian but not for RPM packages. The documentation, however, makes no mention of it being a requirement.

So, should we create an issue and update both documents?

**Comment by MarcelKemp** [comment]
LGTM.
