### ISSUE TITLE
Can't register agent from docker when etc is a docker volume

### ISSUE THREAD

**Issue by web2wire** [wazuh/wazuh#23153]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3-1 | wazuh-agent | Agent | minideb package | Flatcar Container Linux by Kinvolk 3815.2.2 / docker v24  |

Hello all. I am trying to automate the installation and registration of wazuh-agent on small containerised systems based on Flatcar Linux where pretty much everything runs in docker. I have a docker image (based on https://github.com/pyToshka/docker-wazuh-agent with some tweaks) which would appear to work however by default that leaves `/var/ossec/etc` in the internal docker volume and so does not necessarily persist and is not easily accessible from the host for updates and modifications. To get round this I have mounted a host directory on `/var/ossec/etc` on the docker container and the initial registration process copies the original files into this to ensure they are correct. So far so good and initially it is happy.

However I have hit a knotty issue when trying to register the agent with the Wazuh manager. The initialisation script runs `bin/manage-agents` to set up the keys. This creates a temporary key file in `/var/ossec/tmp` and then attempts to "move" it into `/var/ossec/etc`. On Linux this invokes the `rename` system call which fails as the tmp and etc subdirectories are not on the same device as one is a docker mount. I cannot find a way of avoiding this error. I was hoping there might be a way of overriding these paths so it would use two directories on the same device but I can't see a way to do that. From within the container I can't rename or move the etc directory to put a temporary one there either.

Looking at the code I can see that manage-agents uses the `k_import` function from `manage_keys.c` which in turn calls `rename_ex` from `file_op.c` and it is this that ultimately calls `rename` which fails. However also in `file_op.c` is a `OS_MoveFile` function which does a similar thing to `rename_ex` but seems to be a little more pragmatic in that it has a go at renaming the file first and then if that fails then does a bytewise copy to the destination and ultimately deletes the source. This would work across devices but there may be a good (cross-platform?) reason why this function isn't used.

Anyone have any idea how to register the agent and avoid the limitation of the hardcoded paths and device restrictions? Alternatively is there any reason why `k_import` can't use `OS_MoveFile` instead of `rename_ex`?

**Comment by vcerenu** [comment]
Hello @web2wire

Regarding the question about the use of the `OS_MoveFile` function, I have sent it to the development team for verification.

On the topic of mounting the directory inside the container for persistence, when deploying in Docker we use `Docker volumes` for Wazuh's internal directories, which has given us fewer headaches when deploying and making file modifications:
https://github.com/wazuh/wazuh-docker/blob/ec76ea8d92c157357989746b4f1050c18bb379da/single-node/docker-compose.yml#L31-L42
We also have a procedure to handle the persistence of files within the container:
https://github.com/wazuh/wazuh-docker/blob/ec76ea8d92c157357989746b4f1050c18bb379da/build-docker-images/wazuh-manager/config/permanent_data.sh
and the files inside the `/var/ossec/` directory we mount inside another directory and then they are copied to the beginning of the container, this generates fewer permission problems with the files:
https://github.com/wazuh/wazuh-docker/blob/ec76ea8d92c157357989746b4f1050c18bb379da/build-docker-images/wazuh-manager/config/etc/cont-init.d/0-wazuh-init#L134-L142
https://github.com/wazuh/wazuh-docker/blob/ec76ea8d92c157357989746b4f1050c18bb379da/single-node/docker-compose.yml#L46
I hope this helps you, with this we have been able to solve some problems that we had in the deployment of Wazuh manager.
