### ISSUE TITLE
aws-s3.py do not load vpcflowlogs

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh#2315]
## Bug report

**OS**
Ubuntu16

**Wazuh version**
3.8.0-r3801

**Install type**
manager

**Install method**
packages

**Log sample**

```
DEBUG: +++ No regions found for AWS Account 
```

Bug description
----------------
aws-s3.py script works ok with CloudTrail but does not load vpcflowlogs, it simply skips them.

**Comment by druizz90** [comment]
Hi @spartantri, we are going to made some changes for fixing that. At this moment, you can run `VPC` if you add a region in your `~/.aws/credentials` file:
```bash
[default]
aws_access_key_id = XXXXXX
aws_secret_access_key = XXXXXX
region = us-east-1 (or your region)
```

Best regards,

Demetrio.

**Comment by spartantri** [comment]
Hi @druizz90, for now, I'm using an old version of the script as I have several regions.
I will close this as you have the bug on the roadmap already.
Thanks!
