### ISSUE TITLE
Comprehensive Integration Testing of MaxMind Features in Wazuh-Engine

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#23193]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description:
This task focuses on conducting thorough integration testing to ensure the seamless functioning of MaxMind features within the Wazuh-Engine ecosystem. The objective is to validate the integration's reliability, accuracy, and efficiency, guaranteeing that the enriched GeoIP and ASN data are effectively utilized for enhanced event analysis and threat detection.

## Objectives:

-Verify Integration: Test the integration of MaxMind's GeoIP and ASN databases with the Wazuh-Engine to ensure that data retrieval and processing functions as intended.
-Functional Testing: Execute comprehensive functional tests to confirm that the enriched data is accurately incorporated into event analysis and rule matching processes.
-Performance Testing: Assess the performance impact of MaxMind integration on the Wazuh-Engine, including resource usage and processing time, and optimize as necessary.
-Edge Case Testing: Identify and test edge cases to validate the robustness of the integration under various scenarios, such as unusual data formats or network conditions.

## Tasks:

- Develop Test Scenarios: Define a set of test scenarios covering different aspects of MaxMind integration, including data enrichment, rule matching, and automatic database updates.
- Execute Test Cases: Implement test cases based on the defined scenarios and execute them against the integrated system to validate functionality and performance.
- Analyze Test Results: Analyze test results to identify any discrepancies or areas requiring optimization, documenting findings for further refinement.
- Iterative Testing: Iterate on test scenarios and cases based on feedback and findings from initial testing rounds to ensure comprehensive coverage.
- Documentation: Document the testing process, including test scenarios, procedures, results, and any adjustments made, for future reference and transparency.

Acceptance Criteria:

- Successful execution of integration tests covering all defined test scenarios and cases.
- Validation of integration reliability, accuracy, and efficiency in utilizing MaxMind's GeoIP and ASN data.
- Optimization of performance metrics within acceptable thresholds to minimize impact on Wazuh-Engine operation.
- Identification and resolution of any issues or discrepancies found during testing, ensuring a robust integration.
- Comprehensive documentation detailing the testing process and outcomes, facilitating future maintenance and troubleshooting efforts.

**Comment by JavierBejMen** [comment]
## Update
- Updated run.py integration test to add the ability to execute only one feature
- Improved output of run.py
- Working on final integration geo tests
- Fixed error in add geo db lock and shared_ptr checking
