### ISSUE TITLE
Ignoring Alert

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#2320]
Hi Team,

I am trying to ignore alert with 452 status code with below detail but alert appearing again and again.

below is the rule which I have created.
 
  <rule id="40100" level="0">
    <match>^Your App well be BLOCKED after|BLOCKED</match>
    <match>^1:452:</match>
    <match>452</match>
    <match>BLOCKED</match>
    <description>Ignoring BLOCKED Wrong Attempts.</description>
  </rule>

**Comment by Cerv1** [comment]
Hi @HireLabs,

If you've created a custom rule to match this log, you should add the `noalert` label ([reference](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=noalert#rule)) and you won't get any alert related to this rule. 

Please let me know if this works for you.

Best regards,
Cerv1.

**Comment by HireLabs** [comment]
Dear @Cerv1 ,

Tried noalert="1" but still same issue, now trying ignore="20".

Hope it work

**Comment by HireLabs** [comment]
Dear @Cerv1 ,
Tried noalert and ignore but still no luck.

Still need help.

**Comment by Cerv1** [comment]
Hi @HireLabs,

I've just tested this functionality and it works as expected. I need more information in order to help you.

- Did you restart the `wazuh-manager` after making this changes?
- Can you paste here your coustom rule or the default rule of Wazuh you're trying to ignore?

This is a sample of an alert with the `noalert` attribute set:

```
<rule id="XXXX" level="3" noalert="1">
  <if_sid>YYYY</if_sid>
  <match>testing some logs </match>
  <description>Testing rule.</description>
  <group>pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,</group>
</rule>
```

Best regards,
Cerv1.

**Comment by Cerv1** [comment]
Hi @HireLabs,

Is this issue solved? If not, I would like to help you. 

Could you please send me your rule and a full log?

Best regards,
Cerv1.
