### ISSUE TITLE
[V4.7.4][Ubuntu-22.04-LTS] Hard Lock on system

### ISSUE THREAD

**Issue by RicoCarlsson** [wazuh/wazuh#23229]
|Wazuh version|Component|Install type|Install method|Platform|Hosted
|---|---|---|---|---|---|
| 4.7.4 | Wazuh | Manager | Standard Install through quickstart | Ubuntu Server 22.04 LTS | Azure VM 2C-4GB

Been really happy with Wazuh so far. Yesterday the service ran into an issue with a complete hard lock in my VM. 
No webpage, No SSH.

I have added various logs from a few hours before the hardlock on the system. 
[log-journalctl.txt](https://github.com/wazuh/wazuh/files/15197172/log-journalctl.txt)
[log-ossec.log](https://github.com/wazuh/wazuh/files/15197183/log-ossec.log)

Hopefully this will help in some way. Otherwise sorry to waste your time.

**Comment by vikman90** [comment]
Hi @RicoCarlsson,

Given that the logs do not show any errors and considering the characteristics of the virtual machine, I suspect that the issue may be related to a lack of system resources.

I understand that you have installed Wazuh Manager, Indexer, and Dashboard on the same system. According to the **[Installation guide](https://documentation.wazuh.com/current/installation-guide/index.html)**, the [Wazuh Manager](https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html) requires between 2 and 4 GiB of memory; the [Indexer](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/index.html) requires between 4 and 16 GiB; and the [Dashboard](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/index.html) requires between 4 and 8 GiB. My first recommendation is to increase the capacity of your virtual machine to at least 8 GiB if you are testing, and 16 GiB if this is a production environment. Additionally, Wazuh processes, especially the Indexer, require sufficient disk space to operate smoothly.

Please let me know if you need further assistance.

Best regards.
