### ISSUE TITLE
Group assignation removals are not propagated to worker nodes

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#2327]
v3.7.2

It looks like if a group is unassgined from an agent, this change is not propagated to the worker nodes (agent-groups files remain in the worker nodes). It could be due to the _extra_valid_ feature.

Updated:
The issue is removing agents: When an agent is removed, the new client.keys is propagated to the worker nodes, and the framework tries to remove the agent using authd. Since authd only have the initial client.keys in memory, it will not find the agent ID, generating an error.

Related: https://github.com/wazuh/wazuh/issues/2288

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

When an agent is removed in the master, the removal isn't propagated to the worker nodes. I found out the following regex isn't working properly:
https://github.com/wazuh/wazuh/blob/fd6271255f626baf2715a21280dcfb41d5c2354f/framework/wazuh/cluster/cluster.py#L500
I changed it by the following one which works:
```python
    regex = re.compile(r'^-(\d+) \S+ \S+ \S+$')
```

And found out the agent removal isn't still propagated **if `authd` is running in the worker node**:
```
2019/01/14 11:43:03 ossec-authd[23283] local-server.c:377 at local_remove(): DEBUG: local_remove(id='004', purge=0)
2019/01/14 11:43:03 ossec-authd[23283] local-server.c:382 at local_remove(): ERROR: ERROR 9011: Agent ID not found.
2019/01/14 11:43:07 ossec-analysisd: INFO: Cannot get agent-info file for agent agent-1 (172.17.0.201). Using old labels.
2019/01/14 11:43:08 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
2019/01/14 11:43:08 ossec-remoted: INFO: (1410): Reading authentication keys file.
```
As you can read in the previous log, the attempt to remove the agent was done before updating the client keys, so the agent id should still be present in the worker. 

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello again,

After a bit more of research I found out the reason: `authd` stores a copy of the client.keys in memory. To reproduce the issue I did manually the same process done by the cluster:
```shellsession
# echo "003 agent-1 172.17.0.201 4dc1792ce219d04262078c7040751e644403641b9e8f3b2cff9fd26e75a8d41c" >> /var/ossec/etc/client.keys
# curl -u foo:bar -XDELETE "localhost:55000/agents/003?pretty"
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "failed_ids": [
         {
            "id": "003",
            "error": {
               "message": "Agent ID not found",
               "code": 9011
            }
         }
      ],
      "affected_agents": []
   }
}
```
It seems the solution to this issue is to fix the regex and avoid running authd in a worker node.

Best regards,
Marta
