### ISSUE TITLE
Update ossec.conf file when updating/reinstalling on Windows

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#233]
When an agent is updated or reinstalled on Windows the values added using the command line installation are not used. 
The installer should modify the `ossec.conf` file even if it's an update.

**Comment by erseco** [comment]
We will add a FORCE parameter for doing this replace

**Comment by erseco** [comment]
Now in the 3.0.0 msi installer we always modify `ossec.conf` with the given parameters
