### ISSUE TITLE
Increase of memory usage by wazuh-modulesd

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#23304]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc1 | Wazuh component | Manager | Packages | CentOS |

### Description

During testing in [Release 4.8.0 - RC 1 - Footprint Metrics - ALL](https://github.com/wazuh/wazuh/issues/23290) it has been detected a high increase of memory usage by `wazuh-modulesd`. This has been seen in PSS, RSS_MAXMIN, RSS and USS metrics. Increase in `wazuh-modulesd` is expected as indicated [here](https://github.com/wazuh/wazuh/issues/22841#issuecomment-2059826516), but what we are seeing in this case is a much larger increase (more than threefold) so we think it should be investigated.

Plots are compared to https://github.com/wazuh/wazuh/issues/23174.

| Release/Stage | RSS | Issue | 
| --- | --- | --- | 
| 4.8.0-rc1 | ![image](https://github.com/wazuh/wazuh/assets/101177239/9bd94473-c428-45b3-8709-c3a6996125e6) | https://github.com/wazuh/wazuh/issues/23290 | 
| 4.7.4-RC2 | ![image](https://github.com/wazuh/wazuh/assets/101177239/9948a063-7b73-4b8b-bb06-cbdf6d13d6e0) | https://github.com/wazuh/wazuh/issues/23174 |

| Release/Stage | PSS | Issue | 
| --- | --- | --- | 
| 4.8.0-rc1 | ![image](https://github.com/wazuh/wazuh/assets/101177239/e1a8110f-bdaf-4a3b-be9f-8b968ecbb54b) | https://github.com/wazuh/wazuh/issues/23290 | 
| 4.7.4-RC2 | ![image](https://github.com/wazuh/wazuh/assets/101177239/3563255c-6004-4f46-bfab-1d89ecb77b03) | https://github.com/wazuh/wazuh/issues/23174 |

| Release/Stage | USS | Issue | 
| --- | --- | --- | 
| 4.8.0-rc1 | ![image](https://github.com/wazuh/wazuh/assets/101177239/a25d145b-7f73-46e3-a8c7-90cb25df2548) | https://github.com/wazuh/wazuh/issues/23290 | 
| 4.7.4-RC2 | ![image](https://github.com/wazuh/wazuh/assets/101177239/a93adb8e-3a81-49fb-a33f-dd442058dee3) | https://github.com/wazuh/wazuh/issues/23174 |

More information can be found on the issue and in this [comment](https://github.com/wazuh/wazuh/issues/23290#issuecomment-2095534321).

**Comment by Dwordcito** [comment]
Probably related to: https://github.com/wazuh/wazuh/issues/23202

**Comment by Dwordcito** [comment]
The requirements due for the refactor are different in comparison with 4.7.4, the new implementation uses a different cache for high-speed read access.

Furthermore, we change in https://github.com/wazuh/wazuh/issues/23202 the write buffer to prevent high memory allocations. this may decrease the values ​​in the results.
