### ISSUE TITLE
Increase in PSS, RSS, USS by Wazuh-logcollector

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#23302]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc1 | Wazuh Agent | Agent | Packages | centOS |

## Description

During the testing in [Release 4.8.0 - RC 1 - Footprint Metrics - LOGCOLLECTOR, SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/23281) it has been detected a relevant increase of Wazuh-logcollector in RSS, PSS and USS on centOS.

The plots have been compared to [Release 4.7.4 - RC 2 - Footprint Metrics - LOGCOLLECTOR, SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/23160).

- PSS

| 4.8.0-RC1 | 4.7.4-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/41cc1d4711dade43969fd268a13bf2fb0179575fc5674409bfc938f0c6e644b8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42353130392d333630306d2f42353130395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353130395f63656e746f732d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/5c795f9f6325120e20bbc6343235fb17750f1944b86f2fe67234cc0ffd105f2a/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e342f42353038332d333630306d2f42353038335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353038335f63656e746f732d7072652d72656c656173655f5053532e706e67) |

- RSS

| 4.8.0-RC1 | 4.7.4-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/e320b6b8de29b25945ccbc609478303e7cddd1ae62daf3bb4f312541c6838782/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42353130392d333630306d2f42353130395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353130395f63656e746f732d7072652d72656c656173655f5253532e706e67) | ![IMAGE](https://camo.githubusercontent.com/6c034b329d29646747a6906d4c0eabb3991c90688a5d4425f4286def9e956588/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e342f42353038332d333630306d2f42353038335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353038335f63656e746f732d7072652d72656c656173655f5253532e706e67) |

- USS

| 4.8.0-RC1 | 4.7.4-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/7076d1a31254398392b1bf3ed8668b9a654504f69dd5bdb7c03cc0bd385a8d4d/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42353130392d333630306d2f42353130395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353130395f63656e746f732d7072652d72656c656173655f5553532e706e67) | ![IMAGE](https://camo.githubusercontent.com/95a1930b0abbac717f3b126f9e74e58f594ad6665602d07bca4e110dc373e938/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e342f42353038332d333630306d2f42353038335f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353038335f63656e746f732d7072652d72656c656173655f5553532e706e67) |

- Same with other versions

| 4.8.0-RC1 | 4.7.3-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/41cc1d4711dade43969fd268a13bf2fb0179575fc5674409bfc938f0c6e644b8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42353130392d333630306d2f42353130395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353130395f63656e746f732d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/59b7bfae3d6df16c66c8b6f1a7425363e8c82af897d44ff261751b6f78c1f8d8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931312d333630306d2f42343931315f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931315f63656e746f732d7072652d72656c656173655f5053532e706e67) |

| 4.8.0-RC1 | 4.7.2-RC2 |
| --- | --- |
| ![IMAGE](https://camo.githubusercontent.com/41cc1d4711dade43969fd268a13bf2fb0179575fc5674409bfc938f0c6e644b8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e302f42353130392d333630306d2f42353130395f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353130395f63656e746f732d7072652d72656c656173655f5053532e706e67) | ![IMAGE](https://camo.githubusercontent.com/35f4ebcd7d1578477e9138a2ac62b29a57f1cc3a71ff3bdd7de4c5ed10bca699/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e322f42343734352d333630306d2f42343734355f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343734355f63656e746f732d7072652d72656c656173655f5053532e706e67) |

**Comment by TomasTurina** [comment]
No big changes detected for logcolector code: https://github.com/wazuh/wazuh/compare/v4.7.4...4.8.0

Just a change from using `fopen` to use `wfopen`, which is the same in Linux.

<img width="1477" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/542a1691-10e6-4536-ad1a-cb0866ac3312">
<img width="1481" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/5d0878d5-d978-4281-8754-f5dc928fc837">
<img width="1470" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/863490d3-4ad5-4282-9850-dfc9d45aa281">
<img width="1466" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/2358067b-9918-4bee-bec8-2af4245c0f01">
<img width="1469" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/d801650d-f5e7-42c9-bb5d-b670ecb343fa">
<img width="1469" alt="image" src="https://github.com/wazuh/wazuh/assets/11877311/46d6740c-60bc-493c-901d-f3d92924da7c">

Function:
```c
FILE * wfopen(const char * pathname, const char * mode) {
#ifdef WIN32
    ...
#else
    return fopen(pathname, mode);
#endif
}
```
