### ISSUE TITLE
Increase AWS unit test coverage

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#23305]
| Affected integration |
|---|
| AWS |

## Description

- During the release of `4.8.0 - RC 1`, the coverage percentages of the unit tests for the AWS module in `s3_log_handler.py` and `sqs_message_processor.py` are low, as can be seen at https://github.com/wazuh/wazuh/issues/23300#issuecomment-2095636968. We should add test cases to increase it.

- Another script to consider is `wodles/utils.py` with a percentage of 53%.

## Checks

- [x] Unit tests without failures and related coverage reports.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The files mentioned have a higher than 90% coverage as it can be seen in the latest pytest unit tests coverage [report](https://github.com/wazuh/wazuh/actions/runs/9270181114). I added unit tests for the `utils.py` file and removed some unused methods.
