### ISSUE TITLE
Indexer-connector Warning log in Footprint test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#23303]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc1 | Wazuh component | Manager | Packages | CentOS |

### Description

During testing in [Release 4.8.0 - RC 1 - Footprint Metrics - ALL](https://github.com/wazuh/wazuh/issues/23290) it has been detected this warning log related to `indexer-connector`:

```console
2024/05/03 15:18:25 indexer-connector WARNING: Failed to sync agent '000' with the indexer.
```

Evidences: [ossec_Test_stress_B5113_manager_2024-05-06.zip](https://github.com/wazuh/wazuh/files/15218679/ossec_Test_stress_B5113_manager_2024-05-06.zip)

**Comment by Rebits** [comment]
I suggest close this issue. Reason here https://github.com/wazuh/wazuh/issues/23290#issuecomment-2095534321
