### ISSUE TITLE
Increase in `Disk_Read` Values for Manager

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#23315]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.8.0-rc1 | Wazuh Manager | Manager | Packages | CentOS |

## Description

During the `4.8.0-rc1` footprints, I detected an increase in the values of the `Disk_Read` plot in the Manager. The values are similar to those obtained during the 4.8.0 Betas (for example, in Beta 8) but different from those obtained in `4.7.4-rc2`.

- [Release 4.8.0 - RC 1 - Footprint Metrics - ACTIVE-RESPONSE (2.5d)](https://github.com/wazuh/wazuh/issues/23286)

| 4.8.0-rc1 | 4.8.0-beta6 | 4.7.4-rc2 |
| --- | --- | --- |
| ![image](https://github.com/wazuh/wazuh/assets/54536265/05fd401b-fd0a-4470-900f-e1ce69822211) | ![image](https://github.com/wazuh/wazuh/assets/54536265/3fee4256-7c0a-4e6b-919b-9dca8c43bba5) | ![image](https://github.com/wazuh/wazuh/assets/54536265/c9aac0a2-9433-465b-b567-92a88f0355b7) |

- [Release 4.8.0 - RC 1 - Footprint Metrics - ROOTCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/23285)

| 4.8.0-rc1 | 4.8.0-beta6 | 4.7.4-rc2 |
| --- | --- | --- |
| ![image](https://github.com/wazuh/wazuh/assets/54536265/09e8b8e6-ae4e-4e32-9eb1-c79618d0aa04) | ![image](https://github.com/wazuh/wazuh/assets/54536265/cefa613c-90b1-4675-bdee-9278cc01d9fd) | ![image](https://github.com/wazuh/wazuh/assets/54536265/430ccd33-5786-4e8c-a603-188405e0a8a3) |

**Comment by nbertoldo** [comment]
I have analyzed the CSV files of the _4.7.4 - RC2_ tests and I can see that all values of _disk_read_ are zero (for all modules), while the rest of the parameters have reasonable values:  

<details><summary>Active response - 4.7.4-rc2</summary>

![active-response](https://github.com/wazuh/wazuh/assets/117279646/252bc6c8-7167-4470-abde-591fa8093f36)

</details> 

<details><summary>Rootcheck - 4.7.4-rc2</summary>

![rootcheck](https://github.com/wazuh/wazuh/assets/117279646/bb329dbc-2cbc-464a-8516-0dd47251214d)

</details> 

Therefore, this is an issue in the test reading this parameter (_disk_read_), not a product issue.
