### ISSUE TITLE
Puppet module not able to find packages

### ISSUE THREAD

**Issue by Rolly-M** [wazuh/wazuh#23320]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 - RC1 | Wazuh component | Manager/Dasboard/Indexer| Puppet | Amazon linux 2023 |

I am working on the [E2E UX tests - Deployment with Puppet](https://github.com/wazuh/wazuh/issues/23238) for Release 4.8.0 - RC 1 and encountering an error. When running the puppet agent to install the wazuh stack, I get the error below.

```console
Error: Could not update: Execution of '/usr/bin/dnf -d 0 -e 1 -y install wazuh-indexer-4.8.0-1' returned 1: Error: Unable to find a match: wazuh-indexer-4.8.0-1
Error: /Stage[indexerdeploy]/Wazuh::Indexer/Package[wazuh-indexer]/ensure: change from 'purged' to '4.8.0-1' failed: Could not update: Execution of '/usr/bin/dnf -d 0 -e 1 -y install wazuh-indexer-4.8.0-1' returned 1: Error: Unable to find a match: wazuh-indexer-4.8.0-1
```
![image](https://github.com/wazuh/wazuh/assets/99815109/90466da4-fa0e-45bb-a409-7920a9ddbf18)

**Comment by davidcr01** [comment]
This issue can be closed as not planned. The Puppet module was configured to fetch the production packages from the `4.x` repository instead of the `pre-release` repository. That's why the 4.8.0-RC1 packages could not be fetched.
