### ISSUE TITLE
Vulnerability Detector is not generating alerts for NPM packages in Windows

### ISSUE THREAD

**Issue by SeyiSoneye** [wazuh/wazuh#23359]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc1 | Vulnerability detector | Manager | Packages | Windows 11 |

### Description

It has been detected in https://github.com/wazuh/wazuh/issues/23244 that _Vulnerability Detection_ is currently not generating alerts for NPM packages on Windows 11.

### Steps to reproduce
- Install a manager
- Install and register a Windows 11 agent
- Install a NPM package

```console
PS C:\Users\Administrator> npm install -g axios@0.1.0
npm WARN deprecated axios@0.1.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410

added 2 packages in 526ms

PS C:\Users\Administrator> npm list axios
Administrator@ C:\Users\Adminstrator
`-- axios@0.1.0

```

### Check that after Syscollector scans, the package is detected and the vulnerability was included in the inventory but no alert was generated.

Vulnerability detected in Inventory
![image](https://github.com/wazuh/wazuh/assets/56078275/32ec854f-8ab2-4efb-ba9f-77cef12d1554)

No event generated
![image](https://github.com/wazuh/wazuh/assets/56078275/f1315d44-9a14-40ca-b927-88103fa42339)

### Check that after uninstalling the NPM package, the package is no longer detected and the vulnerability was not included in the inventory but no alert was generated.
Vulnerabilities removed from inventory:
![image](https://github.com/wazuh/wazuh/assets/56078275/da3898ad-eb32-48e6-a88c-a9281a57231f)

No events in Events tab
![image](https://github.com/wazuh/wazuh/assets/56078275/484a1522-62ca-44d3-b073-03f59f80c8f6)

**Comment by Dwordcito** [comment]
Probably the same thing reported here:

https://github.com/wazuh/wazuh/issues/23338#issuecomment-2102720524

If you have tested this without restarting the agent, please reopen the issue.
