### ISSUE TITLE
Disable `update_check` in API tavern tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23362]
## Description
Similar to what we did in https://github.com/wazuh/wazuh/issues/23247, we must also update the AIT (tavern) so that `update_check` feature is disabled in all of them. 

There is however one exception. The [test_manager_endpoints.tavern.yaml](https://github.com/wazuh/wazuh/blob/e259a7ca173524e29d2ae4a98086f9ac0950d42f/api/test/integration/test_manager_endpoints.tavern.yaml#L1226-L1476) makes calls to the `GET /manager/version/check` endpoint, so `update_check` should still be enabled in this test. The possibility of mocking the service in any way (for example, using something like https://www.mock-server.com/) must be analyzed.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Set the update check service to disabled by default and created a CTI service mock for specific tests where we want it enabled.

**Comment by GGP1** [comment]
## Update

Resolved a conflict in the test envrionment docker compose file after the base branch was updated.
