### ISSUE TITLE
Yara and sigma rules convert or integrated and gui help to create decoder or rule

### ISSUE THREAD

**Issue by protocolpaladin** [wazuh/wazuh#23379]
Would it be possible to have a built-in converter to easily transform yara or sigma rules into wazuh rules? Or, failing that, to implement these standards natively in the solution?

What's more, it would be interesting for decoders and rules to have a tool via the graphical user interface to help with creation, rather than just testing.

**Comment by vikman90** [comment]
Hi @protocolpaladin, we have plans to support this functionality natively in the future. You can follow the progress and find more details in issue: 

- #3357

We appreciate your patience.

Best regards,
