### ISSUE TITLE
wazuh-modulesd high CPU consumption

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#23399]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | wazuh-modulesd | Manager | Sources | Ubuntu 22.04 |

## Description

A high CPU resource consumption by `wazuh-modulesd` has been noticed while using the [Pyserver development enviornment](https://github.com/wazuh/wazuh-tools/tree/master/framework/environments/dev). Each cluster node is consuming nearly 100% of the CPU resources and sometimes even more than that.

The issue started in 4.9.0 and wasn't experienced before. It can be easily reproduced by modifying the environment's `.env` file and executing `docker compose up`. The same behaviour was observed while using the wazuh-docker repository. 

<details><summary>sample .env</summary>

```
WAZUH_BRANCH=4.9.0
WAZUH_VERSION=4.9.0
WAZUH_PYTHON_VERSION=3.10

WAZUH_LOCAL_PATH=<path_to_the_wazuh_repository> # Not really necessary since it's for mounting the code and doing changes
```

</details>

### CPU usage

<details><summary>docker stats</summary>

![docker-stats](https://github.com/wazuh/wazuh/assets/51374959/535de1a4-85ae-4489-ba02-9b026b18b804)

</details>

<details><summary>top</summary>

![top](https://github.com/wazuh/wazuh/assets/51374959/af612613-5337-4f11-bb90-d4ca2a99db21)

</details>

**Comment by sebasfalcone** [comment]
@GGP1 Do you happen to have the logs of this environment and the steps to reproduce the issue?

**Comment by GGP1** [comment]
@sebasfalcone It can be easily reproduced by running the framework development environment [docker compose](https://github.com/wazuh/wazuh-tools/blob/master/framework/environments/dev/docker-compose.yml) from wazuh-tools or the wazuh-docker environment. The former would only require changing the `.env` file as mentioned in the description.

**Comment by sebasfalcone** [comment]
Thanks! We will try to figure it out

**Comment by pereyra-m** [comment]
Hello @GGP1 !

I've made some tests, and the high consumption in **modulesd** in branches `4.8.0` and above in this docker-compose file is related to the installation by sources of the manager without the vulnerability detector base content. The generation of the whole internal DB takes too much time and it demands CPU.

What you can do is add this line to the `framework/environments/dev/wazuh-manager/preloaded-vars.conf` file

```
DOWNLOAD_CONTENT="y"
```

This way, the installation by sources will download the last available content without having to generate it from scratch.
But consider that sometimes there are still some entries that weren't published in the compressed file and will be processed anyway. This takes much less time, but if still it isn't acceptable for the testing environment, we could disable vulnerability detector by default.

Please, test this approach in your environment and tell us if it worked.

**Comment by GGP1** [comment]
@pereyra-m I've built the environment with the modifications to the `preloaded-vars.conf` and after a few minutes the CPU consumption has remained consistently below 20%, I opened an [issue](https://github.com/wazuh/wazuh-tools/issues/288) to add it to our environment. Thanks!

**Comment by pereyra-m** [comment]
Great news!
Thanks to you!

**Comment by sebasfalcone** [comment]
Thanks @pereyra-m for the investigation! Great catch

Closing this issue, the problem will be fixed in:
- https://github.com/wazuh/wazuh-tools/issues/288
