### ISSUE TITLE
Adapt or create FIM ITs related to new report_changes alerts messages

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23403]
# Description
Hello team

After introducing some new messages in the alerts related to the report_changes mode, 
in this issue: 
- https://github.com/wazuh/wazuh/issues/9448

And this PR: 
- https://github.com/wazuh/wazuh/pull/16487

In order to test these new alerts mentioned, we want to add or modify some ITs of the new QA framework, which are being worked on in this issue:
- https://github.com/wazuh/wazuh/issues/17881

We need to wait for those ITs to be fully migrated before we can test this issue.

**Comment by vikman90** [comment]
This task must start after closing:
- #17881

**Comment by jotacarma90** [comment]
# Update 08/08/2024

- Investigation of the errors found in the ITs related to this issue.
- I start modifying the messages in the TIs.
- Branch: test/23403-its-report-changes
- Pending to check each test running correctly.
