### ISSUE TITLE
Wazuh Agent Compatibility with Ubuntu Installation

### ISSUE THREAD

**Issue by kebalberan** [wazuh/wazuh#23429]
Hi, any idea on how to resolve the issue of installing the Wazuh agent on Ubuntu Dev. When running the last command, to start wazuh agent I always got the same error.

sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent 

![error](https://github.com/wazuh/wazuh-dashboard-plugins/assets/159903706/536c8524-c96e-49b7-b141-f99cca59ce42)

Any idea what should I do?

Note, I only follow Installation guide from the wazuh open on the web interface

**Comment by pereyra-m** [comment]
Hello @kebalberan !

What is your Ubuntu version?

According to the message 
```
sudo: systemctl command not found
```

You should check if `systemctl` is installed in the system. If it isn't, maybe you aren't using **Systemd** and you should follow the instructions under `SysV init` 

https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html#deploy-a-wazuh-agent
```
update-rc.d wazuh-agent defaults 95 10
service wazuh-agent start
```

Or you could even start the agent without any service manager
```
/var/ossec/bin/wazuh-control start
```

About the other error message
```
sudo unable to resolve host
```

You might have a problem with `/etc/hostname` and/or `/etc/hosts` files. Could you share their content?

Regards.

**Comment by sebasfalcone** [comment]
Closed due to inactivity, please fell free to re-open if necessary
