### ISSUE TITLE
Release 4.8.0 - Release Candidate 2 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#23440]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |               https://github.com/wazuh/wazuh/issues/23405                             |
| **Version**                                   |                   4.8.0                         |
| **Release candidate #**                       |                  RC2                          |
| **Tag**                                       |                         [v4.8.0-rc2](https://github.com/wazuh/wazuh/tree/v4.8.0-rc2)                   |
| **Previous Workload benchmarks metrics issue**|             https://github.com/wazuh/wazuh/issues/23268                               |

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|      50000             |          25          |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/23440#issuecomment-2112704935) and [here](https://github.com/wazuh/wazuh/issues/23440#issuecomment-2112789731).

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

### Known issues

- https://github.com/wazuh/wazuh/issues/13872
- https://github.com/wazuh/wazuh-qa/issues/4385
- https://github.com/wazuh/wazuh-jenkins/issues/5814
- https://github.com/wazuh/wazuh/issues/23347
- https://github.com/wazuh/wazuh-qa/issues/1266 (fixed in 4.9.0)

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario

**Comment by GGP1** [comment]
## API Performance Tests :yellow_circle: 

Artifacts: 

### Tests results

| **Endpoint test name**  | **Status** | **Issues Ref.** |
|--|--|--|
| GET /cluster/local/info | :green_circle: | |
| GET /cluster/nodes| :green_circle:  | |
| GET /cluster/healthcheck | :green_circle: | |
| GET /cluster/status | :green_circle: | |
| GET /cluster/local/config | :green_circle: | |
| GET /cluster/api/config | :green_circle: | |
| GET /cluster/configuration/validation | :green_circle: | |
| GET /manager/status | :green_circle: | |
| GET /manager/info | :green_circle: | |
| GET /manager/configuration | :green_circle: | |
| GET /manager/logs | :green_circle:   | |
| GET /manager/api/config | :green_circle: | |
| GET /manager/configuration/validation | :green_circle: | |
| GET /mitre/groups | :green_circle: | |
| GET /mitre/metadata | :green_circle: | |
| GET /mitre/mitigations | :green_circle: | |
| GET /mitre/references | :green_circle: | |
| GET /mitre/software | :green_circle: | |
| GET /mitre/tactics | :green_circle: | |
| GET /mitre/techniques | :green_circle: | |
| GET /overview/agents | 🟡  | https://github.com/wazuh/wazuh/issues/23347 (related to #23319) |
| GET /tasks/status | :green_circle: | |
| PUT /active-response | :yellow_circle: | XFAIL. https://github.com/wazuh/wazuh-qa/issues/1266 |
| PUT /rootcheck | :green_circle: | |
| PUT /syscheck | :green_circle: | |
| POST /groups | :green_circle: | |
| POST /security/users | :green_circle: | |
| POST /security/roles | :green_circle: | |
| POST /security/policies | :green_circle: | |
| POST /security/rules | :green_circle: | |
| PUT /agents/group | :yellow_circle: | XFAIL. https://github.com/wazuh/wazuh/issues/13872 |
| PUT /agents/group/new_test_group/restart | :green_circle: | |
| PUT /agents/restart | 🟡 | https://github.com/wazuh/wazuh/issues/23347 (related to #23319)  |
| POST /agents | :green_circle: | |
| POST /agents/insert​|  :green_circle: | |
| POST /agents/insert​/quick | :green_circle: | |
| GET /agents | :green_circle: | |
| GET /agents/no_group | :green_circle: | |
| GET /agents/outdated | :green_circle: | |
| GET /decoders | :green_circle: | |
| GET /groups | :green_circle: | |
| GET /lists | :green_circle: | |
| GET /rules | :green_circle: | |
| GET /security/users | :green_circle: | |
| GET /security/roles | :green_circle: | |
| GET /security/policies | :green_circle: | |
| GET /security/rules | :green_circle: | |
| DELETE /groups | :green_circle: | |
| DELETE /agents | :green_circle: | |
| DELETE /security/users | :green_circle: | |
| DELETE /security/roles | :green_circle: | |
| DELETE /security/policies | :green_circle: | |
| DELETE /security/rules | :green_circle: | |
| PUT /manager/restart | :green_circle: | |
| PUT /cluster/restart | :green_circle: | |

> [!Note]
> [XFAIL tests list](https://github.com/wazuh/wazuh-qa/blob/9997fc0955e8e416ed04947a25267eee91139f89/tests/performance/test_api/test_api_endpoints_performance.py#L15-L22)

**Comment by Selutario** [comment]
## Review

The tasks' metrics results shown here:
```PYTHON
'agent-info_sync': {
			'time_spent(s)': {
				'workers': {
					'mean': ('worker_9', 1.8368454545454544), 
					'max': ('worker_21', 21.482)
				}, 
				'master': {
					'mean': ('master', 1.6524481311975592), 
					'max': ('master', 21.01)
				}
			}
		}
```

Are clearly higher than in [4.7.3](https://github.com/wazuh/wazuh/issues/23347#issuecomment-2106929250):
```PYTHON
  },
        "agent-info_sync": {
            "time_spent(s)": {
                "workers": {
                    "mean": ("worker_1", 0.20336036036036037),
                    "max": ("worker_11", 1.041),
                },
                "master": {
                    "mean": ("master", 0.08882754759238522),
                    "max": ("master", 0.914),
                },
            }
        },
```

But it is expected and related to the rollback operation described in https://github.com/wazuh/wazuh/issues/23347. However, we must update (decrease) the [thresholds](https://github.com/wazuh/wazuh-qa/blob/master/tests/performance/test_cluster/test_cluster_performance/data/25w_50000a_thresholds.yaml#L2-L43) in the performance test as they are too high now. We can do it in:
- https://github.com/wazuh/wazuh-qa/issues/5390

**Comment by juliamagan** [comment]
LGTM
