### ISSUE TITLE
Exploratory debug symbols & core dump analysis Agent (DEB)

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh#23454]
|Related issue|
|-|
|https://github.com/wazuh/wazuh/issues/21736|
|https://github.com/wazuh/wazuh/issues/21739|

## Description

This issue aims to make a exploratory session of current https://github.com/wazuh/wazuh/issues/9913 phase 1 development for the Agent instance of the DEB package.

Verifications should be performed on the following issues to check end to end the process from generation of symbols to core/crash dump analysis with them.

These verifications must be performed by a different collaborator than the originally assigned to the issue, and a full detail of procedures, logs and results must be provided.
Evidence of success must be provided as well.

## Goals
- Verify that binary and debug symbols packages are correctly generated by following the current documentation
- Verify that binary & debug symbols packages are automatically uploaded to their designated locations.
- Verify that packages perform a successful installation by following the current documentation.
- Verify that the installed agent instance runs successfully.
- Verify that a core dump is generated on simulated failure.
- Verify that debug symbols are suitable to debug/analyze the core dumps.
- Verify that the documentation used during all the exploratory is adequate, correct and complete.
- Verify that core dump generation can be enabled and disabled just by following the proper documentation.

### DoD
- [x] Packages for binaries and debug symbols are generated by following documentation. @ncvicchi 
- [x] Packages are confirmed to be uploaded to their designated location. @jotacarma90 
- [x] Installation is tested and validated.
- [x] Installed agent behaves as expected.
- [x] A simulation of failure is performed and as a result a core dump is generated.
- [x] Core dump is successfully analyzed by using the corresponding debug symbols.
- [x] No documentation errors are found or left uncorrected. @ncvicchi 
- [x] Core dump generation is validated to be enabled or disabled just by following the proper documentation.
- [x] Extensive evidence and documentation of the exploratory is provided

Approval
DRI Name: @ncvicchi 
Objective: Generate debug symbols

**Comment by aritosteles** [comment]
1. Cloned wazuh/wazuh repository:
    - git clone https://github.com/wazuh/wazuh.git
    - checkout enhancement/9913-generate-debug-symbols-epic
    
2. Installed dependencies:
    - Docker: https://documentation.wazuh.com/current/deployment-options/docker/docker-installation.html
    - Gcc, Cmake, etc: https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html

3. Generated rpm packages:
    ./generate_package.sh -t agent --system deb
![1-package-build](https://github.com/wazuh/wazuh/assets/100874572/91f05508-5c1e-403f-85e8-8d64c6841f11)

4. Installed the manager and debug symbols: 
![2-package-installation](https://github.com/wazuh/wazuh/assets/100874572/0a2d6092-56c9-45db-87e7-ef06fb790fd8)

5. Restarted Wazuh:
![3-wazuh-restart](https://github.com/wazuh/wazuh/assets/100874572/b3be06d5-e135-4bc7-a602-6d8b48790217)

6. Configured coredump:
![4-coredump-conf](https://github.com/wazuh/wazuh/assets/100874572/9af7674c-f940-480b-be3a-ab187d7859d1)

7. Restarted systemd-coredump and requested status:
![5-coredump-restart-and-status](https://github.com/wazuh/wazuh/assets/100874572/941c44b1-e95f-4d4d-a40b-b1220d857ce4)

8. Got list of Wazuh processes, generated crash and checked for core dump generation:
![6-kill-process-check-coredump](https://github.com/wazuh/wazuh/assets/100874572/58015541-4946-48d6-961e-dd4c92a1ff45)

9. Unzipped core dump file.

10. Gdb output:
![7-gdb-output](https://github.com/wazuh/wazuh/assets/100874572/3d267776-afec-4226-bfb2-fc1acb6717b3)

**Comment by ncvicchi** [comment]
Blocked until access to wazuh internal repositories is provided

**Comment by Dwordcito** [comment]
@jotacarma90 will check if the debug symbols are uploaded to s3

**Comment by aritosteles** [comment]
Fixed some issues in the workflow and ran successfully:
[Workflow run](https://github.com/wazuh/wazuh-agent-packages/actions/runs/9325579322/job/25672801062)
