### ISSUE TITLE
Wazuh agent package uninstallation protection for Linux

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#23466]
# Description

We need to develop a mechanism to prevent the uninstallation of the Wazuh agent from Linux endpoints. This will enhance security by ensuring that agents are not removed without proper authorization. To achieve this, we will implement a validation process involving the Wazuh manager API.

# Functional Requirements

## Validation endpoint

- A new Wazuh manager API endpoint named `/management_authorization` will be created.
- This endpoint will accept an `action` argument that will be used to validate whether the requesting user permissions contain that action.
- A new action named `agent:uninstall` will be added to the Wazuh manager API, accompanied by a reserved policy, role, and user.

## Uninstallation process

- The uninstallation process will read Wazuh manager API credentials and use them to validate the `agent:uninstall` action via a request to the `/management_authorization` endpoint. These credentials should not be shown in the terminal or user's history.
- If the validation cannot be accomplished the uninstallation will not proceed.
- A new configuration block for the Wazuh agent named `anti_tampering` will be added, and inside it a new setting named `package_uninstallation`. 
- The new configuration block can be pushed via remote configuration.
- The package uninstallation validation will only occur if the `package_uninstallation` is enabled.

# Non-Functional Requirements

- **Security**. Ensure secure communication between the Wazuh agent and the manager API using HTTPS and implement authentication and authorization mechanisms to secure the validation endpoint.

- **Reliability**. The validation endpoint should be highly available and reliable.

- **Performance**. The validation process should introduce minimal latency to the uninstallation process.

- **Scalability**. Ensure the validation endpoint can handle concurrent requests from multiple agents.

# Implementation Restrictions

- **Compatibility**. Ensure the solution is compatible with tier 1 Linux OSs.

- **Minimal changes.** Minimize changes to the existing Wazuh agent and manager codebase.

- **Testing.** E2E testing should be added to QA release testing.
# Plan

## Spike

- https://github.com/wazuh/wazuh/issues/24369
  - Owner: @wazuh/devel-pyserver 
  - Teams involved: @wazuh/devel-pyserver
- https://github.com/wazuh/wazuh/issues/24356
  - Owner: @wazuh/devel-agent 
  - Teams involved: @wazuh/devel-agent 

## MVP implementation

- https://github.com/wazuh/wazuh/issues/24643
  - Owner: @wazuh/devel-pyserver 
  - Teams involved: @wazuh/devel-pyserver
- https://github.com/wazuh/wazuh/issues/24510
  - Owner: @wazuh/devel-agent 
  - Teams involved: @wazuh/devel-agent 

## Feature complete implementation

- https://github.com/wazuh/wazuh/issues/24908
  - Owner: @wazuh/devel-agent 
  - Teams involved: @wazuh/devel-agent 
- https://github.com/wazuh/wazuh-documentation/issues/7533
  - Owner: @wazuh/devel-pyserver 
  - Teams involved: @wazuh/devel-pyserver
- https://github.com/wazuh/wazuh-documentation/issues/7562
  - Owner: @wazuh/devel-agent 
  - Teams involved: @wazuh/devel-agent 

## Acceptance testing

- Test the modified uninstallation process on all tier 1 Linux OSs.
  - Owner: @wazuh/devel-agent 
  - Teams involved: @wazuh/devel-agent

**Comment by vikman90** [comment]
We had a meeting to discuss this issue, and have concluded the following:

- The agent will communicate with the manager's API using HTTPS. This means:
  - The agent must have access to the CA certificate of the manager.
  - The agent must have an option to disable verification of the manager's certificate.
- For this, we rely on an HTTPS client tool: CURL. Therefore, we need to decide between:
  - Using the system's `curl`: implies that the uninstallation of the package depends on `curl`.
  - Implementing an endpoint within the _wazuh-agent_ to read the relevant configuration and make the request to the API.
- If the configuration file does not exist, the option is missing, or there is any other related issue, the default action will be taken: uninstall the agent without verification.
- We need an issue to request the Dashboard team to include reporting of this configuration in the agent's Dashboard.
- This functionality needs to be migrated to the Agent's CLI.

**Comment by MarcelKemp** [comment]
Objective completed, good job team!
