### ISSUE TITLE
Support for multiple accounts in custom buckets (AWS)

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#2346]
Hi team,

I think we should add a column in `custom` buckets with the account ID for giving support to multiple accounts.

Best regards,

Demetrio.

**Comment by jesuslinares** [comment]
Example:
```
<bucket type="custom">
    <name>wazuh-aws-wodle</name>
    <path>kms</path>
    <aws_profile>profile1</aws_profile>
</bucket>
```

```
<bucket type="custom">
    <name>wazuh-aws-wodle</name>
    <path>kms</path>
    <aws_profile>profile2</aws_profile>
</bucket>
```


> account 1: wazuh-aws-wodle/kms/2018/11/07/17
> account 1: wazuh-aws-wodle/kms/2018/11/07/17
