### ISSUE TITLE
Improve the new vulnerability scanner efficacy tests

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#23472]
## Description

The refactored vulnerability scanner has a QA Python test designed to verify the proper behavior of the module with different inputs. The output in case of failure was improved at #23226.

But during the development of new cases at #23225, at least the following weak points were found:
- If new content is required for the tests, the Python script forces to decompress it first
- Each test is independent, but they can't be run on demand, all of them must be executed

To reduce the required time to develop new cases, the test should be improved.

## DoD

- [x] Improve the Python test for the described weak points
- [x] Analyze if there are more aspects to update
- [x] Show the results and document the changes

**Comment by sebasfalcone** [comment]
## Issue blocked
We are waiting for 4.8.0 changes to be merged into 4.9.0 in order to apply this changes

**Comment by sebasfalcone** [comment]
## Issue on hold
Awaiting for in-depth review to apply this changes

A lot of refactor on critical tests were performed, but we considered it necessary

**Comment by sebasfalcone** [comment]
## Issue blocked
@Dwordcito we need to decide if we are going to continue with this development

**Comment by sebasfalcone** [comment]
## Moved ETA
We decided to continue with the implementation of this issue, the ETA was updated because we need to rebase and re-implement many of the changes

**Comment by sebasfalcone** [comment]
## Update
@pereyra-m We are going to proceed with the changes, let's rebase the changes and continue with it

I will update the ETA

**Comment by pereyra-m** [comment]
## Update

I return to the task.
Rebase needed.

**Comment by pereyra-m** [comment]
## Update

I continue with the issue. I’m testing better ways to reflect the PyTest results.

**Comment by pereyra-m** [comment]
## Update

I run again the manual tests and cherry-pick the commits to make the QA tests pass.
