### ISSUE TITLE
Vulnerability scanner - Missing functionality on translations

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#23518]
## Description
Currently, the translation mechanism used on the vulnerability scanner (https://github.com/wazuh/wazuh/issues/22477):

- Doesn't validate that the vendor name matches the one on the translation regex
- Lacks the capability of replacing the version provided by syscollector

### Static version
Replace the version with some fixed value:
```json
{
  "target": [
    "windows"
  ],
  "source": {
    "vendor": "^Microsoft Corporation",
    "product": "^Microsoft Office Professional Plus 2016 - en-us$",
    "version": ""
  },
  "translation": [
    {
      "vendor": "microsoft",
      "product": "office",
      "version": "16.0.0.0"
    }
  ]
}
```

### Dynamic version
Obtain the version information from the package name:
```json
  {
    "scan_id": 0,
    "scan_time": "2024/05/14 14:13:18",
    "format": "win",
    "name": "Java 2 Runtime Environment Standard Edition v1.3.1", <----- VERSION IN NAME
    "version": " ", <----- EMPTY VERSION
    "priority": " ",
    "section": " ",
    "size": 0,
    "vendor": " ",
    "install_time": "2024/05/14 14:12:38",
    "architecture": "i686",
    "multiarch": null,
    "source": " ",
    "description": " ",
    "location": " ",
    "cpe": null,
    "msu_name": null,
    "checksum": "07d6fe0244cbe8abad0cdc83ae6d1f53dcd092da",
    "item_id": "8d91907b799e329bf1c472fe5898abfa946ee746"
  }
```

In this example, we could use the following translation
```json
{
  "target": [
    "windows"
  ],
  "source": {
    "vendor": "^\\s",
    "product": "^Java \\d Runtime Environment Standard Edition v\\d+\\.\\d+\\.\\d+",
    "version": "v(\\d+\\.\\d+\\.\\d+)"
  },
  "translation": [
    {
      "vendor": "oracle",
      "product": "jre",
      "version": ""
    },
    {
      "vendor": "sun",
      "product": "jre",
      "version": ""
    }
  ]
}
```

## Logic
```mermaid
flowchart TD
    A[Start] --> B{source.version empty}
    B -->|No| C[Use version extracted from product name]
    B -->|Yes| E{translation.version empty}
    E -->|No| F[Use translation version]
    E -->|Yes| G[No version to replace]
```

## DoD
- [x] Functionality implemented
- [x] Tests updated

**Comment by pereyra-m** [comment]
## Update

The changes are present temporarily at https://github.com/wazuh/wazuh/tree/enhancement/23518-add-version-replace-on-translations-temp because the target branch `4.9.0` still doesn't have the latest commits.

The QA tests pass locally

![2024-05-22_13-37](https://github.com/wazuh/wazuh/assets/65046601/d8ffa5d1-03c1-43ca-b7f6-5f52a9f70910)

UTs pass

![2024-05-22_14-07](https://github.com/wazuh/wazuh/assets/65046601/0852ffc1-7618-48cc-842e-2ada5720d3c9)

**Comment by pereyra-m** [comment]
## Update

Rebase of PR https://github.com/wazuh/intelligence-data/pull/293 and changes in the review applied

**Comment by pereyra-m** [comment]
## Update

PR rebased after base branch change.

**Comment by pereyra-m** [comment]
## Update

Issue in progress again. Changes by review in both PRs.

**Comment by pereyra-m** [comment]
## Update

Rebase and conflict solving for PR https://github.com/wazuh/wazuh/pull/23727
