### ISSUE TITLE
Utilize `source` field for selecting corresponding feed during package scanning

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#23538]
## Description
This issue aims to use the `source` field during package scanning to select the corresponding feed based on the value of this field. 

A concrete example is for packages installed with Homebrew, where the information provided by syscollector includes:

```
sqlite> select * from sys_programs where name like "%wget%";
     scan_id = 0
   scan_time = 2024/04/24 14:11:13
      format = pkg
        name = wget
    priority =  
     section =  
        size = 0
      vendor =  
install_time =  
     version = 1.24.5
architecture =  
   multiarch = 
      source = homebrew
 description = Internet file retriever
    location = /usr/local/Cellar
         cpe = 
    msu_name = 
    checksum = 16f028c029a9d70dbf517739d642af4ce2e91cad
     item_id = cf15b75fa23de290a28dce697d0455abe1d273f5
```

The goal is to use the `source` field along with [the new type that will be added to the feed global map](https://github.com/wazuh/intelligence-data/issues/276) to utilize the specific feed for Homebrew.

## Expected

- In cases where syscollector does not provide information in the `vendor` field, use the `source` field to determine the feed to be used.
- Implement logic to select the appropriate feed based on the `source` field, ensuring accurate and comprehensive data processing.
- Ensure that the new type added to the feed global map for Homebrew is correctly utilized during the scanning process.

This implementation will enhance the accuracy and relevance of the feeds used for packages.

## DoD
- [x] Add tests
- [x] Reviewer validation with evidence.

**Comment by sebasfalcone** [comment]
## Analysis
I've done a rough check to see how many times these fields are empty

- Source
```
sqlite> SELECT
    SUM(CASE WHEN source IS NULL OR TRIM(source) = '' THEN 1 ELSE 0 END) AS empty_sources,
    SUM(CASE WHEN source IS NOT NULL AND TRIM(source) != '' THEN 1 ELSE 0 END) AS non_empty_sources
FROM
    sys_programs;
1213|2119
```

- Vendor
```
sqlite> SELECT
    SUM(CASE WHEN source IS NULL OR TRIM(vendor) = '' THEN 1 ELSE 0 END) AS empty_sources,
    SUM(CASE WHEN source IS NOT NULL AND TRIM(vendor) != '' THEN 1 ELSE 0 END) AS non_empty_sources
FROM
    sys_programs;
404|2928
```

- Format
```
sqlite> SELECT
    SUM(CASE WHEN source IS NULL OR TRIM(format) = '' THEN 1 ELSE 0 END) AS empty_sources,
    SUM(CASE WHEN source IS NOT NULL AND TRIM(format) != '' THEN 1 ELSE 0 END) AS non_empty_sources
FROM
    sys_programs;
0|3332
```
