### ISSUE TITLE
Vulnerability Scanner - Improve translations performance

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#23544]
## Description
Currently, the translation mechanisms for the vulnerability scanner has a caché mechanism which prevents us from reading, from the database, already compiled translations:
https://github.com/wazuh/wazuh/blob/0fa24cb7936a1580b23a9beec579dfbc82373eca/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp#L95-L97

In case the translation is not in the caché, we read all translations from the database and iterate over all of them in order to find the correct match

But we are no taking into account that most of the packages doesn't have a translation, this degrades the performance of the scanner a lot.

### Solution
To solvent this we could have a second caché wich tracks the already scanned packages, without translation.

## Use cases
We should take into consideration some scenarios

### Feed update
The caché must be flushed because some packages may have a translation now

## DoD
- [x] Solution implemented
- [x] Updated the testing

**Comment by sebasfalcone** [comment]
Another point of improvement, mentioned by @pereyra-m 

We are not checking the return value of the handler: 
https://github.com/wazuh/wazuh/blob/4a074c36391bb7037ca266abe1f82a3a04bbc83b/src/wazuh_modules/vulnerability_scanner/src/databaseFeedManager/databaseFeedManager.hpp#L530-L536

Provided to the forEach method for the cacheLRU, used on the translation caché:
https://github.com/wazuh/wazuh/blob/4a074c36391bb7037ca266abe1f82a3a04bbc83b/src/shared_modules/utils/cacheLRU.hpp#L121-L128

**Comment by GabrielEValenzuela** [comment]
# Development journey

## 6/6
- Starting with a new design to refactor L1 and filter moving to another object.

**Comment by sebasfalcone** [comment]
## Update
- Applying rebase and style changes
