### ISSUE TITLE
Add new FIM IT cases to check for non-UTF8 characters

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23556]
# Description

Hello team,

Working on [this issue](https://github.com/wazuh/wazuh/issues/23354) about some crashes detected in syscheckd, we have decided to include some changes in the FIM code. 
We have introduced a new filter in the `fim_checker` function, to ignore files containing invalid characters (non-UTF8) in the name.
We have also included some try/catch to code to make sure that even if it try to process an invalid name, syscheck does not crash.

This issue is to include new integration tests related to these cases. Working on this PR: https://github.com/wazuh/wazuh/pull/23543
We think it can be included as `basic_usage` cases, simply by adding a file containing an invalid character and expecting an error during its processing of this type:
```
2024/05/22 12:21:45 wazuh-syscheckd: WARNING: (6955): Ignoring file '/root/test/fim/V�ctor' due to unsupported name (non-UTF8).
```

## Test cases
- [x] First scan with an invalid file on Linux.
- [x] Real-time file change on Linux.
- [x] Who-data file change on Linux.
- [x] First scan with an invalid file on Windows.
- [x] Real-time file change on Windows.
- [x] Who-data file change on Windows.
- [x] Registry key change on Windows.
- [x] The synchronization (Rsync) process works after changing an invalid file.

**Comment by jotacarma90** [comment]
# Update 12/06/2024

- Working on FIM integration tests, new files added:
     |───test_invalid_characters
    │   └───data
    │       ├───configuration_templates
    │       └───test_cases
    │   └───__init__.py
    │   └───test_non_utf8_characters.py
- Analyzing the framework and adapting to the use of the new functions.

**Comment by jotacarma90** [comment]
# Update 13/06/2024

- PR wazuh/wazuh: https://github.com/wazuh/wazuh/pull/24081
- PR qa-integration-framwork: https://github.com/wazuh/qa-integration-framework/pull/188
- Working on developing the tests, multiple problems to handle non-UTF-8 invalid characters in python (files and FIM events were being created without problems).

**Comment by jotacarma90** [comment]
# Update 14/06/2024

- I have managed to run the test for both windows and linux/macos.
- Pending to check if there are not better options than using directly the iconv command, since I have not found a way to trigger in windows the function that checks for invalid characters (I guess that python+linux file system reformats it at some point).
- Added tests for synchronization and for windows logs.
- Correct PR checks.

**Comment by jotacarma90** [comment]
# Update 17/06/2024
- Some minor editing and editing fixes introduced in the wazuh/wazuh PR.
- I have tried to investigate further the differences between Windows and Linux when encoding strings in the file system. In summary, Windows uses UTF-16 encoding and Linux UTF-8:
`"Unicode" on Windows is UTF-16LE, and each character is 2 or 4 bytes. Linux uses UTF-8, and each character is between 1 and 4 bytes.`
https://superuser.com/questions/294219/what-are-the-differences-between-linux-and-windows-txt-files-unicode-encoding
- Therefore the test we are performing in the integration test, needs that for Linux we make use of the iconv command to transform the characters to a different encoding to be detected correctly by FIM, otherwise the Linux file system processes the path names with the UTF-8 encoding and we would not be testing correctly the case we want to test.
- PR ready for review again.

**Comment by MarcelKemp** [comment]
- Fixed by https://github.com/wazuh/wazuh/pull/24081 and https://github.com/wazuh/qa-integration-framework/pull/188

**Comment by rpradela** [comment]
Hi,

Do you have some date to fix this problem in windows system?
