### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by Ravichandranravi** [wazuh/wazuh#23552]
|Wazuh version|Component|
|---|---|
| X.Y.Z-rev | Wazuh component |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by MiguelazoDS** [comment]
Hi @Ravichandranravi, 

Sorry for the delay, could you be more specific about your problem?

**Comment by sebasfalcone** [comment]
Inactive thread, closing issue
