### ISSUE TITLE
PFLogs monitoring

### ISSUE THREAD

**Issue by HireLabs** [wazuh/wazuh#2356]
Dear Team, 

I am trying to monitor PFLOGS " /var/log/pflog " via wazuh, but its not working, cause pflog is written in binary tcpdump format.

Can you please share any way to read all pflogs.

**Comment by cristgl** [comment]
Hello @HireLabs,

As this file is written in binary tcpdump format, you can use the `tcpdump` command to filter these logs:

```
tcpdump -n -e -ttt -r /var/log/pflog
```

For monitoring the logs stored at that file, it could be interesting to use `cron` with the command above and redirect the output to a file contained in a monitored folder. An approximation of the `crontab -e` file could look like this:

```
* * * * * tcpdump -n -e -ttt -r /var/log/pflog > monitored_folder/filtered_pflogs.log
```

**Comment by HireLabs** [comment]
Dear @**cristgl** ,

So, wazuh agent and server doesn't read directly " /var/log/pflog " from file without tcpdump ?

**Comment by TJOSERAFAEL** [comment]
Let me close this issue. Feel free to reopen it if you need further assistance.
