### ISSUE TITLE
agent not added in window 11

### ISSUE THREAD

**Issue by vivekyadav012345** [wazuh/wazuh#23569]

**Comment by pereyra-m** [comment]
Hello @vivekyadav012345 !

Could you describe in detail the issue you have?
Were you able to register your agent against the manager? Can you provide the `ossec.log` file of both the agent and manager? Don't forget to remove any sensitive data.

Some basic troubleshooting steps in this case include:
- Make sure the Wazuh manager version is the same or greater than the agent
- The agent can reach the ports 1514 and 1515 of the manager
- The IP of the manager has been configured in the agent's `ossec.conf` file (look for `<address>` tag)

Regards.
