### ISSUE TITLE
wazuh 4.7.4 build fails with gcc 14.1.1 on Archlinux

### ISSUE THREAD

**Issue by afunix** [wazuh/wazuh#23568]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.4 | Installation | Agent | Sources | Archlinux (rolling) |

Build fails for 4.7.4 (used to work for 4.7.2) with:
```
client-agent/receiver.c: In function ‘receive_msg’:
client-agent/receiver.c:280:81: error: passing argument 4 of ‘UnmergeFiles’ from incompatible pointer type [-Wincompatible-pointer-types]
  280 |                                 if (!UnmergeFiles(file, SHAREDCFG_DIR, OS_TEXT, &ignore_list)) {
      |                                                                                 ^~~~~~~~~~~~
      |                                                                                 |
      |                                                                                 char ***
In file included from ./headers/shared.h:256,
                 from client-agent/receiver.c:11:
./headers/file_op.h:221:85: note: expected ‘const char ***’ but argument is of type ‘char ***’
  221 | int UnmergeFiles(const char *finalpath, const char *optdir, int mode, const char ***unmerged_files) __attribute__((nonnull(1)));
      |                                                                       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
client-agent/receiver.c:287:72: error: passing argument 2 of ‘cldir_ex_ignore’ from incompatible pointer type [-Wincompatible-pointer-types]
  287 |                                     if (cldir_ex_ignore(SHAREDCFG_DIR, ignore_list)) {
      |                                                                        ^~~~~~~~~~~
      |                                                                        |
      |                                                                        char **
./headers/file_op.h:346:54: note: expected ‘const char **’ but argument is of type ‘char **’
  346 | int cldir_ex_ignore(const char * name, const char ** ignore);
      |                                        ~~~~~~~~~~~~~~^~~~~~
```

GCC:
```
$ gcc --version
gcc (GCC) 14.1.1 20240507
Copyright (C) 2024 Free Software Foundation, Inc.
```
[wazuh-4.7.4.build_log.txt](https://github.com/wazuh/wazuh/files/15406334/wazuh-4.7.4.build_log.txt)

**Comment by MiguelazoDS** [comment]
Hi @afunix, 

Thanks for reporting this, it seems that some warnings are treated as errors now in GCC 14 

https://gcc.gnu.org/gcc-14/porting_to.html#warnings-as-errors

> The initial ISO C standard and its 1999 revision removed support for many C language features that were widely known as sources of application bugs due to accidental misuse. For backwards compatibility, GCC 13 and earlier diagnosed use of these features as warnings only. Although these warnings have been enabled by default for many releases, experience shows that these warnings are easily ignored, resulting in difficult to diagnose bugs. In GCC 14, these issues are now reported as errors, and no output file is created, providing clearer feedback to programmers that something is wrong.

> Most components of the GNU project have already been fixed for compatibility, but not all of them have had releases since fixes were applied. Programs that bundle parts of [gnulib](https://www.gnu.org/software/gnulib/) or [autoconf-archive](https://www.gnu.org/software/autoconf-archive/) may need to update these sources files from their upstream versions.

> Several GNU/Linux distributions have shared patches from their porting efforts on relevant upstream mailing lists and bug trackers, but of course many programs that exhibit these historic C compatibility issues are dormant today.

I'll tell my my team about this right now to address it ASAP.

**Comment by nem0nic** [comment]
I assume this is the same issue with 4.7.5.  Just tried to install that on arch and the same error.

**Comment by vikman90** [comment]
## GCC version support

|Platform|GCC version|Result|
|--|--|--|
|Fedora 40|14.1.1-4| 🔴 Error|
|Arch Linux (rolling)|14.1.1| 🔴 Error|
|Ubuntu 24.04|13.2.0| 🟡 Warning|
|Rocky Linux 9.3|11.4.1-3| 🟡 Warning|
|AlmaLinux 9.4|11.4.1-3| 🟡 Warning|
|Ubuntu 22.04|11.4.0| 🟡 Warning|

**Comment by vikman90** [comment]
@afunix we've just fixed this issue in branch 4.9.0.

Thank you for reporting this problem.

Best!

**Comment by nem0nic** [comment]
Any ETA on when the fix will roll out?  I've tried compiling every version back as far as 4.6.0 and now have a few arch machines not being monitored which I need to get added.

**Comment by gravityfargo** [comment]
> Any ETA on when the fix will roll out? I've tried compiling every version back as far as 4.6.0 and now have a few arch machines not being monitored which I need to get added.

in `wazuh-4.8.0/src/client-agent/receiver.c` replace line 280 with:

```c
if (!UnmergeFiles(file, SHAREDCFG_DIR, OS_TEXT, (const char ***)&ignore_list)) {
```
and line 287 with:
```c
if (cldir_ex_ignore(SHAREDCFG_DIR, (const char **)ignore_list)) {
```
