### ISSUE TITLE
Check Wazuh compatibility with new version Ubuntu 24.10

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23579]
## Description
Hello team, this issue is to check the full compatibility of Wazuh Agent and Manager on the newfound version of Ubuntu 24.10 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/23524

For this, it is necessary to perform the following tests to check that everything works as expected:
* #23720 @wazuh/devel-devops-div1 @wazuh/devel-devops-div2 
* wazuh/wazuh#23581 @wazuh/devel-agent-div2
* #23706 @wazuh/devel-cppserver
* #23707 @wazuh/devel-indexer 
* wazuh/wazuh#23582 @wazuh/devel-threatintel

**Comment by MarcelKemp** [comment]
Not on the compatibility list, only LTS versions.
