### ISSUE TITLE
Release 4.7.5 - RC 1 - E2E UX tests - Demo environment 

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#23604]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.8.0-rc2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by May 15, 2024 and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-devops team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by May 16, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by May 17, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer |  |  |  |
| Server |  |  |  |
| Dashboard |  | - |  |
| Agent |  | - |  |

## Test description

Test demo.wazuh.info environment:
  - [Check Agent, Dashboard, Indexer, and Manager Logs](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2129984671)
  - [Check Wazuh Users and Processes](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130009350)
  - [Check the Status of the Indexer Cluster](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130037279)
  - [Check Browser's Developer shellsession for Errors While Browsing the App](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130222354)
  - [Check that there are Alerts for each of the Modules Configured](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130278845)
  - [Generate an Alert and Check it appears in Wazuh Dashboard](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130288142)
  - [Check the search engine works using *](https://github.com/wazuh/wazuh/issues/23604#issuecomment-2130295449)

To access the demo environment, please contact @devel-devops.

## Known issues

- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4108
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4092
- https://github.com/wazuh/wazuh-packages/issues/1749
- https://github.com/wazuh/wazuh/issues/13253
- https://github.com/wazuh/wazuh/issues/5214
- https://github.com/wazuh/wazuh/issues/8580
- https://github.com/wazuh/wazuh/issues/8581
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4406
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4407
- https://github.com/wazuh/wazuh/issues/14710
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4232
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/4074
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/5745
- https://github.com/wazuh/wazuh-packages/issues/2139
- https://github.com/wazuh/wazuh/issues/18593
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/5821
- https://github.com/wazuh/wazuh-automation/issues/1113
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/5749
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/5750
- https://github.com/wazuh/wazuh-dashboard-plugins/4121
- https://github.com/wazuh/wazuh-dashboard-plugins/5332
- https://github.com/wazuh/wazuh-dashboard-plugins/6022
- https://github.com/wazuh/wazuh-automation/issues/1369
- https://github.com/wazuh/wazuh-dashboard-plugins/6023
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6182
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6216
- https://github.com/wazuh/wazuh/issues/21829

## Conclusions 🟡 

Several known issues were found. No new abnormal behavior detected

| **Status**     | **Test**    | **Failure Type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟡 | Check Agent, Dashboard, Indexer, and Manager Logs | Error and Warning logs | Known issue: https://github.com/wazuh/wazuh/issues/13253 |
| 🟡 | Check Agent, Dashboard, Indexer, and Manager Logs | Error and Warning logs | Known issue: https://github.com/wazuh/wazuh-packages/issues/2685 |
| 🟡 | Check Agent, Dashboard, Indexer, and Manager Logs | Error and Warning logs | Known issue: https://github.com/wazuh/wazuh/issues/21419 |
| 🟡 | Check Agent, Dashboard, Indexer, and Manager Logs | Error and Warning logs | Known issue: https://github.com/wazuh/wazuh/issues/18593 |
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/4121|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5821|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5332|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/4108|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6022|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/6320|
| 🟡 | Check Browser's Developer shellsession for Errors While Browsing the App | Console Errors and Warnings | Known issue: https://github.com/wazuh/wazuh-dashboard-plugins/issues/5869|

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - Yes, the information has been clear enough.
- Did you face any challenges not covered by the guideline?
  - No
- Suggestions for improvement:
  - I have no suggestions, I think the steps are good and clear enough to follow.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/devel-devops

**Comment by QU3B1M** [comment]
### Available systems

<details><summary>Agents</summary>

- Amazon
- Centos
- Debian
- RHEL9
- Ubuntu
- Windows
</details>

<details><summary>Dashboard</summary>

- WazuhDashboard
</details>


<details><summary>Indexers</summary>

- IndexerBootstrap
- IndexerMasterB
- IndexerMasterC
- WazuhDashboard
</details>

<details><summary>Managers</summary>

- WazuhMasterEnv1
- WazuhMasterEnv2
- WazuhWorker
</details>

**Comment by QU3B1M** [comment]
## Check that there are Alerts for each of the Modules Configured 🟢 

### Modules in ENV-1

<details>
   <summary>Check Activated Modules 🟢</summary>
   <br/>
    
  ![Screenshot 2024-05-24 162816](https://github.com/wazuh/wazuh/assets/44633633/8b8942fd-ef0d-4da3-96a3-7592d605f366)
  ![Screenshot 2024-05-24 162828](https://github.com/wazuh/wazuh/assets/44633633/60c0f75c-5ef3-4294-9c20-4dccc64bff86)
  ![Screenshot 2024-05-24 162843](https://github.com/wazuh/wazuh/assets/44633633/13125ffe-d590-4cab-a9a5-18b8e48b162c)

</details>

<details>
   <summary>Check Alerts from the Activated Modules 🟢 </summary>
   <br/>

- AWS Module
    ![Screenshot 2024-05-24 163445---AWS](https://github.com/wazuh/wazuh/assets/44633633/60babb39-8818-40ef-8c2b-47183c51da7b)

- VirusTotal Module
    ![Screenshot 2024-05-24 163539--VIRUSTOTAL](https://github.com/wazuh/wazuh/assets/44633633/09273b5b-20d6-45ec-adfd-095ba9273fad)

- Docker Listener Module
    ![image](https://github.com/wazuh/wazuh/assets/44633633/720b094a-6598-4f6b-bff4-ee256b836d44)

- GDPR Module
    ![Screenshot 2024-05-24 163732----GDPR](https://github.com/wazuh/wazuh/assets/44633633/a33c394f-b427-4035-9dad-8e30cbb68851)

- HIPAA Module
    ![Screenshot 2024-05-24 163806---HIPAA](https://github.com/wazuh/wazuh/assets/44633633/7b15ad4d-880f-436d-8494-a3ebfb147e68)

- TSC Module
    ![Screenshot 2024-05-24 163854---TSC](https://github.com/wazuh/wazuh/assets/44633633/fa7569b2-dc53-4edc-bc09-f4eac38b1e77)

</details>



### Modules in ENV-2

<details>
   <summary>Check Activated Modules 🟢</summary>
   <br/>

![Screenshot 2024-05-24 164921](https://github.com/wazuh/wazuh/assets/44633633/ec02f0d9-8cbe-478d-a36a-366c076bebde)
![Screenshot 2024-05-24 164931](https://github.com/wazuh/wazuh/assets/44633633/19401c94-8549-42db-adcf-ae995ee5677d)
![Screenshot 2024-05-24 164946](https://github.com/wazuh/wazuh/assets/44633633/80fe8ad7-2ef2-44f8-b229-d313c68dbb8a)

</details>

<details>
   <summary>Check Alerts from the Activated Modules 🟢 </summary>
   <br/>

- AWS Module
    ![image](https://github.com/wazuh/wazuh/assets/44633633/c5c90d03-b190-47fe-8e86-7695d37d95d6)


- VirusTotal Module
    > **Note:** This environment does not have any Windows agent.

    ![image](https://github.com/wazuh/wazuh/assets/44633633/24894095-3901-4402-a58f-7261fa14bffd)



- Docker Listener Module
    > **Note:** Docker is not installed on this environment's agents

    ![image](https://github.com/wazuh/wazuh/assets/44633633/ba5541c6-41c9-41c2-8290-56c9b0241df9)

- GDPR Module
    ![image](https://github.com/wazuh/wazuh/assets/44633633/7fdf50e3-1db3-4497-b577-9765668419a6)

- HIPAA Module
    ![image](https://github.com/wazuh/wazuh/assets/44633633/93b6b1fc-4024-4be1-a04e-4b9c74e61912)

- TSC Module
    ![image](https://github.com/wazuh/wazuh/assets/44633633/9a79d9ed-a90e-43da-a42b-6a75181cdd06)


</details>

**Comment by damarisg** [comment]
GJ! Next Time, don't forget to add Google Cloud tests in the "Check Browser's Developer Console for Errors While Browsing the App" section.
