### ISSUE TITLE
Update check file permissions for 4.7.5 RC 1

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#23623]
|Wazuh version| Type | 
|---|---|
| 4.7.5-rc1 | Upgrade |  

### Description

Working on "[Package - Upgrade](https://github.com/wazuh/wazuh/issues/23590)" testing, we detected a new failure related to permissions. The tests work successfully but we found the following error in each execution: 

<details><Summary>Error details</Summary>

    14:45:14  TASK [test-manager : Run check files tests] ************************************
    14:45:14  task path: /home/ec2-user/workspace/Test_upgrade/quality/tests/generic/03-upgrade/linux/test/conf/test-manager/tasks/configure_test.yaml:77
    14:45:14  fatal: [amd64-opensuse-tumbleweed-manager-4_7_4_0]: FAILED! => {
    14:45:14      "changed": true,
    14:45:14      "cmd": [
    14:45:14          "/usr/testing/bin/python3",
    14:45:14          "./check_files.py",
    14:45:14          "-a",
    14:45:14          "upgrade",
    14:45:14          "-o",
    14:45:14          "linux",
    14:45:14          "-t",
    14:45:14          "manager",
    14:45:14          "-v",
    14:45:14          "4.7.5",
    14:45:14          "-f",
    14:45:14          "4.7.4",
    14:45:14          "-i",
    14:45:14          "/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python",
    14:45:14          "--no_show_ignore_list"
    14:45:14      ],
    14:45:14      "delta": "0:00:08.367265",
    14:45:14      "end": "2024-05-23 17:45:14.230639",
    14:45:14      "rc": 1,
    14:45:14      "start": "2024-05-23 17:45:05.863374"
    14:45:14  }
    14:45:14  
    14:45:14  STDOUT:
    14:45:14  
    14:45:14  Namespace(directory='/var/ossec', from_version='4.7.4', ignore='/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python', no_show_ignore_list=True, os='linux', target='manager', test='upgrade', version='4.7.5')
    14:45:14  Checking files...
    14:45:14  
    14:45:14  Different:
    14:45:14  /var/ossec/queue/db/.template.db [Wrong:  user]
    14:45:14  	Expected: wazuh wazuh  0640  # -rw-r-----
    14:45:14  	Found   : root wazuh  0640  # -rw-r-----
    14:45:14  
    14:45:14  
    14:45:14  
    14:45:14  Please, review your files.
    14:45:14  
    14:45:14  
    14:45:14  MSG:
    14:45:14  
    14:45:14  non-zero return code

</details>

<details><Summary>Expected behavior</Summary>

  - Keep check file permissions up to date. 
  - The pipeline finished successfully without any failure. 
  
</details>

<details><Summary>Steps to reproduce</Summary>

  - 1. Re-launch https://ci.wazuh.info/job/Test_upgrade_tier/2215/
  - 2. Verify that the results do not contain any errors
  
  
</details>

**Comment by vikman90** [comment]
This is a regression related to https://github.com/wazuh/wazuh/pull/23467.
