### ISSUE TITLE
Check Wazuh compatibility with new version Fedora 41

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23659]
## Description
Hello team, this issue is to check the full compatibility of Wazuh Agent and Manager on the newfound version of Fedora 41 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/23524

For this, it is necessary to perform the following tests to check that everything works as expected:
*  #23660 @wazuh/devel-devops-div1 @wazuh/devel-devops-div2 
*  #23661 @wazuh/devel-agent-div2
*  #23708 @wazuh/devel-cppserver
*  #23709 @wazuh/devel-indexer 
*  #23662 @wazuh/devel-dashboard
* #23680 @wazuh/devel-threatintel  
* #23714 @wazuh/devel-qa

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as done.
