### ISSUE TITLE
Add SCA content for Rocky Linux 9.4

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23667]
## Description
As part of the OSs checks issue: https://github.com/wazuh/wazuh/issues/23524 and https://github.com/wazuh/wazuh/issues/23663

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No | Minor |

- [ ] If we need to add support for the agent, we need to make sure that basic OS ruleset and SCA policies are available for the new OS.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as not planned because it is a minor version.
