### ISSUE TITLE
Check Wazuh compatibility with new version Rocky Linux 9.4

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23663]
## Description
Hello team, this issue is to check the full compatibility of Wazuh Agent and Manager on the newfound version of Rocky Linux 9.4 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/23524

For this, it is necessary to perform the following tests to check that everything works as expected:
* wazuh/wazuh-qa#5435 @wazuh/devel-devops-div1 @wazuh/devel-devops-div2 
* wazuh/wazuh#23665 @wazuh/devel-agent-div2 
* #23715 @wazuh/devel-cppserver
* #23716 @wazuh/devel-indexer
* wazuh/wazuh#23666 @wazuh/devel-dashboard
* wazuh/wazuh#23667 @wazuh/devel-threatintel

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as done.
