### ISSUE TITLE
Update Fedora 41 availability in the allocator module

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23660]
## Description
As part of the OSs checks issue: https://github.com/wazuh/wazuh/issues/23524 and https://github.com/wazuh/wazuh/issues/23659

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes| Major |

- [x] If the new OS's version is a major/new family, we need to manually allocate two different accessible machines with the new OS. If it is a minor version, we need to deploy an All In One (in our featured OS, probably Amazon Linux) and allocate an accessible machine with the new OS to test the agent. This is the first step for everything else.

NOTE: We won't perform any additional tasks as the OS version is a pre-release version.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue because it is a pre-release version.
