### ISSUE TITLE
Check all information related to Rocky Linux 9.4 is properly reported in the wazuh-dashboard

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23666]
## Description
As part of the OSs checks issue: https://github.com/wazuh/wazuh/issues/23524 and https://github.com/wazuh/wazuh/issues/23663

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No | Minor |

The main comprobations that must be done are the following:

- [ ] If we need to add support for the central components, add support for the new OS to the GitHub Actions package builder.
- [ ] If we need to add support for the central components, smoke test that the package works, including installation and upgrade.
- [ ] If we need to add support for the agent, we need to test functionality for all stateful modules according to the OS's tier.
- [ ] If we need to add support for the agent, we need to make sure that the agent-related information in the agent list is correct.
- [ ] If we need to add support for the agent, we need to test the deployment one-liner for the new OS.

**Comment by lucianogorza** [comment]
# Server

```console
[root@localhost vagrant]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

**Comment by lucianogorza** [comment]
# Central components

## :green_circle: Wazuh installation assistant

<details>
<summary>Install</summary>

```console

```

</details>

<details>
<summary>Dashboard</summary>

```console

```

</details>

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue because it is a minor version.
