### ISSUE TITLE
Change Vulnerability Detection option in the `internal_options.conf` file

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#23668]
## Description

After talking to @Rebits, we think that the internal variable `vulnerability-detection.disable_scan_manager` should be replaced by `vulnerability-detection.enable_scan_manager` as, due to what it means and the values it takes, it would be more readable and comprehensible.
It is currently defined as follows:

```shell
# Vulnerability detector - Enable or disable the scan manager
# 0. Enabled
# 1. Disabled
vulnerability-detection.disable_scan_manager=0
```

Should this change occur, it should be noted in the documentation, reported in this [issue](https://github.com/wazuh/wazuh-documentation/issues/7336).

**Comment by sebasfalcone** [comment]
This feature won't be documented since it was decided when it was implemented
- https://github.com/wazuh/wazuh/issues/22059

See "special considerations"

**Comment by sebasfalcone** [comment]
This feature won't be documented since it was decided when it was implemented
- https://github.com/wazuh/wazuh/issues/22059

See "special considerations"
