### ISSUE TITLE
Add tools and fixtures for GCP IT

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23670]
|Objective | Epic issue | 
|--------------|-----------------------------|
|https://github.com/wazuh/wazuh/issues/22732| https://github.com/wazuh/wazuh/issues/18551 |

## Description

New GCP integration tests will be added as part of https://github.com/wazuh/wazuh/issues/18551. Taking into account that the tests must create and delete their own resources (this will be done during the development of each test) and that the same has already been done for the AWS tests, in this issue we must add or update any tools and fixes that are common to all GCP (and perhaps AWS) tests and necessary for this work properly.

For example. A [TestConfigurator](https://github.com/wazuh/wazuh/blob/4c0da894b1374c98431204a051f3877a0c5ba4d8/tests/integration/test_aws/configurator.py#L37-L162) was added for setting up all AWS tests. A new one should be created (or the original adapted) for GCP tests.

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
