### ISSUE TITLE
Review resources and permissions required for GCP Pub/Sub integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23671]
|Objective  | Epic issue | 
|--------------|-----------------------------|
|https://github.com/wazuh/wazuh/issues/22732| https://github.com/wazuh/wazuh/issues/18552 |

## Description
We need to review and list which resources are needed for the test cases related to `GCP Pub/Sub` designed in:
- https://github.com/wazuh/wazuh/issues/18555
- https://github.com/wazuh/wazuh/issues/23669

Since the tests must create and destroy the needed resources on each run, we must also list which are the minimum required permissions to perform those actions. Requesting permissions for the development will be part of this issue too.

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
