### ISSUE TITLE
Develop GCP Pub/Sub integration tests

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23676]
## Description

We need to develop integration tests for the use cases of the GCP Pub/Sub module that were proposed here:
- https://github.com/wazuh/wazuh/issues/18555
- https://github.com/wazuh/wazuh/issues/23669

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
