### ISSUE TITLE
Release 4.8.0 - RC 3 - Vulnerability Detection feed comparison

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23677]
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |                      https://github.com/wazuh/wazuh/issues/23684               |
| **Main Vulnerability Detection tests issue**     |        https://github.com/wazuh/wazuh/issues/23678                               |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                   RC 3                       |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-rc3                               |
| **Previous Vulnerability tests issue**      |     https://github.com/wazuh/wazuh/issues/23298                                   |

### Description

In version 4.8.0 of the Wazuh, a significant refactor has been implemented in the Vulnerability Detector module (Check [this](https://github.com/wazuh/wazuh/issues/14153) issue for more information). This refactor introduces changes that may impact the detection of vulnerabilities compared to the previous version, 4.7.5.

### Objective

The objective of this testing issue is to perform a thorough analysis to identify any potential discrepancies in vulnerability detection between Wazuh 4.7.5 and 4.8.0. The analysis will be conducted on multiple operating systems.
### Testing Parameters:

**Testing Environment:**
- **Multiple OS**
    - macOS Sonoma
    - Windows 11
    - Amazon Linux 2023
    - Ubuntu 24
    - Red Hat Enterprise Linux (RHEL) 9
    - CentOS 9 Stream
    - Debian 12
    - Oracle Linux 9
    - SUSE 15
    - Windows Server 2022
    - Fedora 39

### Testing Procedure
- Deploy Wazuh version 4.7.5 on each specified operating system.
- Deploy Wazuh version 4.8.0 on each specified operating system.
- Execute the vulnerability detection scan on both versions for each operating system.
- Record and compare the results to identify any discrepancies between 4.7.5 and 4.8.0.

### Analysis

- [x] https://github.com/wazuh/wazuh/issues/23743
- [x] https://github.com/wazuh/wazuh/issues/23744
- [x] https://github.com/wazuh/wazuh/issues/23745
- [x] https://github.com/wazuh/wazuh/issues/23747
- [x] https://github.com/wazuh/wazuh/issues/23749
- [x] https://github.com/wazuh/wazuh/issues/23750
- [x] https://github.com/wazuh/wazuh/issues/23751
- [x] https://github.com/wazuh/wazuh/issues/23752
- [x] https://github.com/wazuh/wazuh/issues/23753
- [x] https://github.com/wazuh/wazuh/issues/23754
- [x] https://github.com/wazuh/wazuh/issues/23755

**Comment by santipadilla** [comment]
## Test results

|OS|Box|4.7.5 |4.8.0-rc3 | Evidences | 
|---|---|---|---| ---|
|RHEL 9|`roboxes/rhel9`| | |
|AL2023| `gbailey/al2023`|  |  |  | 
|macOS Sonoma|macos_1400 (WazuhQAEnviroment)|  |  | 
|CentOS 9 Stream| | | |
|Debian 12| `debian/bookworm64 `| |  | | 
|Oracle Linux 9|`oraclelinux/9` |  |  |  | 
|SUSE 15|[SLES15-SP2](https://www.suse.com/download/sles/) |  | |  | 
|Fedora 39|`roboxes/fedora39` |  |  |  | 
|Ubuntu 24| |  |  | | 
|Windows 11| |  |  | | 
|Windows Server 2022| |  |  | |

**Comment by MARCOSD4** [comment]
## RHEL 9

**Comment by santipadilla** [comment]
## AL2023

**Comment by rafabailon** [comment]
## CentOS 9

**Comment by MARCOSD4** [comment]
## Oracle Linux 9

**Comment by santipadilla** [comment]
## Fedora 39

<details>
<summary>Agent info</summary>
<br>

```console
uname -r

```

```console
cat /etc/os-release 

```

</details>

<details>
<summary>4.7.5 vulnerabilities</summary>
<br>

Detected: **--**

- CSV: 

- Logs:
  - Manager: 
  - Agent: 
 
- Packages: 

  <details>
  <summary>OS: </summary>
  <br> 
  
```json
  

    
```
  
  </details>

</details>


<details>
<summary>4.8.0 vulnerabilities</summary>
<br>

Detected: **--**

- CSV: 

- Logs:
  - Manager: 
  - Agent: 

- Packages: 

<details><summary> OS: </summary><br> 
  
```json



```
  </details>

</details>

**Comment by rafabailon** [comment]
## Ubuntu 24

**Comment by rafabailon** [comment]
## Windows 11

**Comment by MARCOSD4** [comment]
## SUSE 15

**Comment by santipadilla** [comment]
## Windows 11

**Comment by Rebits** [comment]
LGTM
