### ISSUE TITLE
Resources setup and teardown for GCP Pub/Sub integration tests 

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#23674]
|Objective  | Epic issue | 
|--------------|-----------------------------|
|https://github.com/wazuh/wazuh/issues/22732| https://github.com/wazuh/wazuh/issues/18552 |

## Description

In a similar way to what was done [here](https://github.com/wazuh/wazuh-qa/issues/4714) and [here](https://github.com/wazuh/wazuh/issues/22514), we need to automate the creation and destruction of any of the resources  required for the tests developed here:
- https://github.com/wazuh/wazuh/issues/23676

The resources should be those listed here:
- #23671

**Comment by fdalmaup** [comment]
Due to the changes planned for version 5.0, the analysis that is being carried out regarding the External integrations modules, the team's efforts for improvements will be directed to the mentioned version.
