### ISSUE TITLE
Release 4.8.0 - RC 3 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23683]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |            https://github.com/wazuh/wazuh/issues/23684                              |
| **Version**                          |                   4.8.0                         |
| **Release candidate #**              |                    RC 3                      |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.8.0-rc3                               |
| **Previous Vulnerability tests issue**      |        https://github.com/wazuh/wazuh/issues/23298                                    |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

## Test environment

| Component              | Quantity | Operating System | CPU (cores) | RAM (GB) | Disk (GB) |
|------------------------|----------|------------------|-------------|----------|-----------|
| **Master**             | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Workers**            | 2        | Ubuntu 22        | 4           | 8        | 50        |
| **Load Balancer**      | 1        | Ubuntu 22        | 4           | 8        | 50        |
| **Indexers**           | 2        | Ubuntu 22        | 2           | 4        | 30        |
| **Dashboard**           | 1        | Ubuntu 22        | 2           | 4        | 30        |

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Number of Agents | EPS | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Minimum Activity | Simulate a small, stable environment with low activity | 10 | 10 | 60 | 100 | 3h |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 50 | 10 | 60 | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 200 | 50 | 60 | 100 | 3h |

**Comment by Rebits** [comment]
The template and issue were updated due to `CLUSTER-Workload_benchmarks_metrics` pipeline limitations. The frequency and number of packets have been adjusted to match the default values of the agent simulator script. This approach aligns with the previous issue, even though it wasn't previously communicated. Both templates have been modified to prevent future confusion.

**Comment by Rebits** [comment]
## Tests

- **Low  activity**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/543

**Comment by Rebits** [comment]
Vulnerabilities API stats do not report any vulnerability in the index: 
```
tail -10 wazuh-vulnerabilities_api_stats.csv 
2024-06-03 20:22:23,0
2024-06-03 20:22:28,0
2024-06-03 20:22:33,0
2024-06-03 20:22:38,0
2024-06-03 20:22:43,0
2024-06-03 20:22:48,0
2024-06-03 20:22:54,0
2024-06-03 20:22:59,0
2024-06-03 20:23:04,0
2024-06-03 20:23:09,0
```

Currently researching this issue

**Comment by Rebits** [comment]
Vulnerability messages generator seems to fails genering vulnerability alerts. This seems differs from previous performance testing. This has been reported in https://github.com/wazuh/wazuh-qa/issues/5459

Due to the limitations of the Agent Simulator generating vulnerability detection alerts I suggest to close this issue and continue with performance tests in RC4.
