### ISSUE TITLE
Wodle to run commands asynchronously

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#237]
This module will allow running external commands asynchronously, one in each thread.

Initial features:
- Command line.
- Tag.
- Option to ignore output.
- Interval parameter.
- Option to run on agent start, no matter if it's the time to run.

Tentative configuration:

```
<wodle name="command">
  <tag>myapp</tag>
  <command>/usr/local/bin/myapp --config /var/ossec/etc/shared/myapp.conf</command>
  <interval>60</interval>
  <ignore_output>no</ignore_output>
  <run_on_start>yes</run_on_start>
</wodle>
```

**Comment by vikman90** [comment]
First iteration completed: https://github.com/wazuh/wazuh/commit/eabef6a6eb10da0ce29b76467c4d5fd10f042fee

**Comment by irctrakz** [comment]
Love it!
