### ISSUE TITLE
Support new OSs - Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23724]
Hello team, this issue is to check the full compatibility of Wazuh Agent and Manager on the newfound version of Ubuntu 24.04 operating system.

OSs checks issue: https://github.com/wazuh/wazuh/issues/23311

As this check still corresponds to the old checking way, we are listing the performed check and related work done:

* DevOps: wazuh/wazuh-qa#5425
* Server: #23133
* Agent: #23134 
* Indexer: https://github.com/wazuh/wazuh/issues/23746
* Dashboard: https://github.com/wazuh/wazuh/issues/23583
* ThreatIntel: https://github.com/wazuh/wazuh/issues/23194
* QA: https://github.com/wazuh/wazuh/issues/23748

**Comment by pattersc07** [comment]
https://workbench.cisecurity.org/benchmarks/18959

CIS Benchmark V1 for 24.04 LTS is published now.
