### ISSUE TITLE
Document current Python tests for new Vulnerability Detection - QA

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#23730]
### Description
There is a current gap in our documentation regarding the Python tests that have been implemented for the quality assurance (QA) of the new vulnerability detection system. This documentation is essential for both current and future developers to understand, maintain, and potentially enhance these tests.

### Details
- **Requirement:**
  - Comprehensive documentation of the existing Python tests used in the QA process for the new vulnerability detection system.
  
- **Purpose:**
  - To provide clear, accessible information on how the tests work, what they cover, and how they are structured.
  - To ensure consistency and continuity in the QA process, particularly as team members change or the project scales.

### Expected Documentation
1. **Overview of the Testing Framework:**
   - Explain the setup and teardown processes, if any.

2. **Test Descriptions:**
   - Provide detailed descriptions of each test case.
   - Outline the specific aspects of the vulnerability detection system that each test is designed to verify.

3. **Running the Tests:**
   - Include instructions on how to set up the environment for running the tests.
   - Detail the steps to execute the tests and interpret the results.

4. **Handling Failures:**
   - Explain the procedures for handling test failures.
   - Describe how to report bugs or issues discovered during testing.

5. **Future Considerations:**
   - Discuss potential future improvements or additions to the test suite.
   - Outline how new tests should be integrated into the existing framework.

### Action Required
- [x] Collate all existing information and code related to the current Python tests.
- [x] Draft the documentation, incorporating all the sections outlined above.

-------------------------

**Comment by pereyra-m** [comment]
## Update

I begin with the issue, the start date was updated.
