### ISSUE TITLE
Release 4.7.5 - RC 2 - Packages tests

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#23768]
### Packages tests information
|||
| :--                              | :--                                                             |
| **Main release stage issue**     | #23764|
| **Version**                      | 4.7.5                                                   |
| **Release stage**                | RC 2                                                  |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.7.5-rc2          |
| **Previous packages metrics**    | #23588  |

---

| Status | Test              | Issue              |
| :--:   | :--               | :--:               |
| :green_circle:     | Installation | https://github.com/wazuh/wazuh/issues/23769 |
| :green_circle:     | Upgrade |  https://github.com/wazuh/wazuh/issues/23770   |
| :green_circle:     | SELinux |  https://github.com/wazuh/wazuh/issues/23772 |
| :green_circle:     | Register |    https://github.com/wazuh/wazuh/issues/23771 |
| :green_circle:     | Service  | https://github.com/wazuh/wazuh/issues/23773   |
| ⚪    | Specific systems |     |
| :green_circle:     | Indexer/Dashboard |  https://github.com/wazuh/wazuh/issues/23774  |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:green_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias

---

**Comment by jnasselle** [comment]
LGTM!
