### ISSUE TITLE
Improve installers' naming handling instead of using wildcards

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23777]
# Description

One of the requirements in the development of the Wazuh packages redesign tier 1 objective is:

> The package-building process must log the task result and provide the final package URL.

This objective has not been met since the workflows do not provide the URL (URI) of the installer clearly and directly, but instead delegate to displaying said URL in the output of the commands when uploading the files.

This is incorrect since this requirement has the objective of obtaining said URL clearly and directly, not only by looking at the log but also from other procedures.

Because it has not been developed and in the issue https://github.com/wazuh/wazuh-jenkins/issues/6371 it is necessary to standardize the output to obtain said URI through regex, this requirement is being carried out in said issue by the QA team

Now, the method used to upload the files to S3 is through *agent* or *manager*, so the rest of the nomenclature is assumed, this makes it difficult to obtain a valid URL since there are multiple files

The generated files must be treated individually and not be uploaded in an unattended manner, therefore, it is necessary that each workflow provides a way to use the package nomenclature in a unique and individualized way.

In the future, this will also allow to use and handle other files, like symbols files

## Related

- https://github.com/wazuh/internal-devel-requests/issues/187
- https://github.com/wazuh/wazuh-jenkins/issues/6371

# Tasks

- [x] Modify workflow installers to use the installer name directly in the following subsystems
  - [x] Wazuh manager 
  - [x] Other workflows that use wildcards

**Comment by lchico** [comment]
# Update
PR created and ready to review.
