### ISSUE TITLE
Vulnerabilities are not correctly pulled into the index by activating the Indexer module when the vulnerabilities were already processed.

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#23817]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc3 | Vulnerability Detector | Manager | Packages | Ubuntu 22 |

***

## Description

During [Release 4.8.0 - RC 3 - Vulnerability Detection extra cases](https://github.com/wazuh/wazuh/issues/23682), it has been detected that vulnerabilities are not correctly pulled to the index in the case of enabling the Indexer module when the vulnerabilities were already processed.
<details><summary>Configuration</summary>

```
<vulnerability-detection>
    <enabled>yes</enabled>
    <index-status>no</index-status>
    <feed-update-interval>60m</feed-update-interval>
  </vulnerability-detection>

  <indexer>
    <enabled>no</enabled>
    <hosts>
      <host>https://172.31.5.12:9200</host>
    </hosts>
    <ssl>
     <certificate_authorities>
      <ca>/etc/pki/filebeat/root-ca.pem</ca>
     </certificate_authorities>
     <certificate>/etc/pki/filebeat/node-2.pem</certificate>
     <key>/etc/pki/filebeat/node-2-key.pem</key>
    </ssl>
  </indexer>
```
</details>

<details><summary>Wait until vulnerabilities are detected</summary>

```
2024/05/29 08:00:31 wazuh-modulesd:vulnerability-scanner: INFO: Policy changed. Re-scanning all agents
2024/05/29 08:00:31 wazuh-modulesd:vulnerability-scanner: INFO: Starting database file decompression.
2024/05/29 08:00:31 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/05/29 08:03:12 wazuh-modulesd:vulnerability-scanner: INFO: Database decompression finished.
2024/05/29 08:03:13 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started
2024/05/29 08:03:16 wazuh-modulesd:vulnerability-scanner: INFO: Initiating update feed process
2024/05/29 08:05:08 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update
2024/05/29 08:05:08 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed
```

</details>

<details><summary>Enable indexer module</summary>

```
<vulnerability-detection>
    <enabled>yes</enabled>
    <index-status>yes</index-status>
    <feed-update-interval>60m</feed-update-interval>
  </vulnerability-detection>

  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://172.31.5.12:9200</host>
    </hosts>
    <ssl>
     <certificate_authorities>
      <ca>/etc/pki/filebeat/root-ca.pem</ca>
     </certificate_authorities>
     <certificate>/etc/pki/filebeat/node-2.pem</certificate>
     <key>/etc/pki/filebeat/node-2-key.pem</key>
    </ssl>
  </indexer>
```
</details>

<details><summary>Restart the manager and check that vulnerabilities are correctly pulled</summary>

- Agent
```
<!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>
```

- Manager

```
2024/05/29 08:15:20 wazuh-modulesd:syscollector: INFO: Module started.
2024/05/29 08:15:20 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/05/29 08:15:20 indexer-connector: INFO: IndexerConnector initialized successfully for index: wazuh-states-vulnerabilities-wazuh.
2024/05/29 08:15:20 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/05/29 08:15:20 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started
```

- Check vulnerabilities

```
root@ip-xxx-xx-x-xx:/home/qa# curl -k -u user:pass https://xxx.xx.x.xx:9200/wazuh-states-vulnerabilities-wazuh/_count?pretty=true -H 'Content-Type: application/json'
{
  "count" : 0,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  }
}
```
</details>

>Note: Steps followed:

<details><summary>Steps</summary>

1. Vulnerability detection and indexer module deactivated
2. Agents connected to the manager
3. Enable vulnerability detection and disable indexer module
4. Restart manager
5. Wait until vulnerabilities are detected  for all agents
6. Enable indexer module
7. Restart the manager
8. Vulnerabilities are not correctly pulled to the index
9. Change syscollector agent time from 1h to 1m and restart agent
10. Vulnerabilities are not correctly pulled to the index
11. Delete agent and connect again
12. Vulnerabilities are correctly pulled to the index

</details>

## Evidences

- Manager logs: [ossec.log](https://github.com/user-attachments/files/15510424/ossec.log.zip)
- Agent logs: [ossec.log](https://github.com/user-attachments/files/15510461/ossec.log)
- OS: [OS.json](https://github.com/user-attachments/files/15510497/export.10.json)
- Packages: [Packages.json](https://github.com/user-attachments/files/15510503/export.11.json)

**Comment by havidarou** [comment]
Wazuh 5.0 will supersede this behavior.
