### ISSUE TITLE
Vulnerability Scan not work on Windows server 2019

### ISSUE THREAD

**Issue by ldannunzio** [wazuh/wazuh#23816]
Good morning, I had a troubleshooting session with Javier Bonacci some time ago for a problem. At the end he suggested that I open a ticket on GitHub
So this is the problem:
I have installed, at 3 different customers, a total of 40 Windows Server wazuh agents (2012 R2, 2016, 2019).
The problem is that vulnerability detection works fine for Windows 2012 R2 and 2016 servers. For Win 2019 it stopped working at the beginning of April because vulnerabilities were reported, for many 2019 agents installed at the end of last year, until to the period indicated above. For several Win 2019 servers (about 60 % of the total)  there are updates to install from update manager then some vulnerabilities have not been mitigated. The issue occurs on Wazuh server v4.7.4 and agents versions 4.7.0, 4.7.3 and 4.7.4. 

This is the agent config applied to a group confgured for windows servers:

"<agent_config>
	
	
	<wodle name="syscollector">
		<disabled>no</disabled>
		<interval>2h</interval>
		<scan_on_start>yes</scan_on_start>
		<hardware>yes</hardware>
		<os>yes</os>
		<network>yes</network>
		<packages>yes</packages>
		<hotfixes>yes</hotfixes>
		<ports all="no">yes</ports>
		<processes>yes</processes>
	</wodle>
</agent_config>"
[ossec.log.gz](https://github.com/user-attachments/files/15510265/ossec.log.gz)

The All-in-one wazuh server run on:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS" 

Javier had recommended enabling debug mode and running a full scan. Attached is the log file relating to this operation. The agent ID we are using as a reference is 008
Attached the log file.
[ossec.log.gz](https://github.com/user-attachments/files/15510265/ossec.log.gz)

Is it possible to analyze more in deep  this  problem?

Many thanks in advance.

**Comment by ldannunzio** [comment]
Ok. Many many thanks for you answer.

Regards.

**Comment by Dwordcito** [comment]
@sebasfalcone check this

**Comment by MiguelazoDS** [comment]
# Analysis 

## Environment 

- Manager: Ubuntu Jammy
- Agent 001: Windows 2016 server 
```json
  {
    "scan_id": 0,
    "scan_time": "2024/06/04 17:34:05",
    "hostname": "VAGRANT",
    "architecture": "x86_64",
    "os_name": "Microsoft Windows Server 2016 Standard Evaluation",
    "os_version": "10.0.14393.2791",
    "os_codename": null,
    "os_major": "10",
    "os_minor": "0",
    "os_patch": null,
    "os_build": "14393.2791",
    "os_platform": "windows",
    "sysname": null,
    "release": null,
    "version": null,
    "os_release": "1607",
    "checksum": "1717522445576115400",
    "os_display_version": " ",
    "reference": "abf404b78925886611f1c2d9bde3835bc8d02c11"
  }
```
- Agent 002: Windows 2019 server 
```json
  {
    "scan_id": 0,
    "scan_time": "2024/06/04 17:34:09",
    "hostname": "VAGRANT2019",
    "architecture": "x86_64",
    "os_name": "Microsoft Windows Server 2019 Datacenter Evaluation",
    "os_version": "10.0.17763.1935",
    "os_codename": null,
    "os_major": "10",
    "os_minor": "0",
    "os_patch": null,
    "os_build": "17763.1935",
    "os_platform": "windows",
    "sysname": null,
    "release": null,
    "version": null,
    "os_release": "1809",
    "checksum": "1717522449861176900",
    "os_display_version": " ",
    "reference": "cf8cdc0b7429f590190d4944e83d141bed182c18"
  }
```

##  Vulnerabilities overview 

- Full log 
[ossec.log.tar.gz](https://github.com/user-attachments/files/15568802/ossec.log.tar.gz)

- 798 vulnerabilities total 

### Agent 001 (Windows server 2016) 
- 524 OS vulnerabilities 
- 40 package vulnerabilities 

### Agent 002 (Windows server 2019) 
- 194 OS vulnerabilities 
- 40 package vulnerabilities

## Errors 

```console
DEBUG: Error creating VersionObject (DPKG). Version string doesn't match the specified type. Version string: (4.0)
DEBUG: Error creating VersionObject (DPKG). Version string doesn't match the specified type. Version string: preview_release
DEBUG: Failed to scan package: 'firefox', CVE Numbering Authorities (CNA): 'nvd', Error: 'Unable to compare versions (126.0.1 vs (4.0)).'
DEBUG: Failed to scan package: 'firefox', CVE Numbering Authorities (CNA): 'nvd', Error: 'Unable to compare versions (126.0.1 vs preview_release).'
```

**Comment by sebasfalcone** [comment]
## Conclusion
Action items already identified here:
- https://github.com/wazuh/wazuh/issues/23788#issuecomment-2147932179

New VD works in windows server 2019 🟢

**Comment by Dwordcito** [comment]
Thanks for the report, @ldannunzio your feedback is welcome to improve the product.
