### ISSUE TITLE
Failing tests - Build Linux manager rpm package

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#23831]
## Description
After the changes introduced in https://github.com/wazuh/wazuh/issues/20887, the following checks are failing:
- [Wazuh CI / Build Linux x86_64 manager rpm package](https://github.com/wazuh/wazuh/pull/23828/checks?check_run_id=25663299606)
- [Wazuh CI / Build Linux arm64v8 manager rpm package](https://github.com/wazuh/wazuh/pull/23828/checks?check_run_id=25663606862)

With the message:
```
    Installed (but unpackaged) file(s) found:
   /var/ossec/framework/wazuh/core/cluster/hap_helper/__init__.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/hap_helper.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/proxy.py
   /var/ossec/framework/wazuh/core/cluster/hap_helper/wazuh.py
```

This may be related to the [manager .SPEC](https://github.com/wazuh/wazuh/blob/12af0aa8b31fbb3167b607186b03abd2b77b2e4a/packages/rpms/SPECS/wazuh-manager.spec) file

## DoD
- [ ] Tests are fixed

**Comment by Selutario** [comment]
According to what was described [here](https://wazuh-team.slack.com/archives/C038AR25C8N/p1717414088448139?thread_ts=1717003718.949059&cid=C038AR25C8N), it is expected to fail as `wazuh-packages` is no longer being maintained in 4.9.0 and this should be removed from CI (which is not possible yet).

This was run in a github action workflow and worked fine after a required docker image was updated:
- https://github.com/wazuh/wazuh/actions/runs/9319858112
- [logs_24393524451.zip](https://github.com/user-attachments/files/15815985/logs_24393524451.zip)

I'll close the issue for now, but please reopen this if needed.
