### ISSUE TITLE
No vulnerabilities in the index when the agent is already registered

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#23849]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc3| Vulnerability detection | Manager/Agent | Packages | CentOS, Ubuntu, macOS and Windows |

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/23815 one of the tests to be performed was `vd_disabled_when_agents_registration`. In this test it could be seen that when enabling Vulnerability Detector when the agents are already registered, no vulnerabilities were indexed. Report: [Test_e2e_system_292_test_vulnerability_detector.zip](https://github.com/user-attachments/files/15536263/Test_e2e_system_292_test_vulnerability_detector.zip)

> [!NOTE]
We will launch the tests again with debug enabled, so we can get more information. This issue will be updated with the new report when it is finished.

A similar error was reported previously on https://github.com/wazuh/wazuh/issues/22871.

### Steps to reproduce

- Deploy a Wazuh cluster and two agents.
- Disable vulnerability detector in the managers.
- Register the agents to each manager host.
- Enable vulnerability detection in the managers.
- Check that the agents are scanned and the vulnerable packages are detected.

**Comment by Rebits** [comment]
Currently rerunning the E2E Vulnerability tests in an environment with modulesd.debug enabled. I will upload the results as soon as possible.

**Comment by Rebits** [comment]
Tests fail in the second iteration. No vulnerabilities were detected when agents were previously registered before enabling the vulnerability detection module. The report has been shared internally with the development team.

**Comment by Dwordcito** [comment]
RCA: 

This issue is caused because during the rescan two basic operations are executed, the first one is to clean all previous data, and the second one scans all elements on the inventory, but in clustered mode the indexation of all documents not are immediate, we need to wait to the next agent sync trigger to update the data.

Issue: the first operation is executed immediately when it should be executed in the synchronization agent operation.
