### ISSUE TITLE
Data Provider - Missing python paths locations for macOS

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#23842]
## Description
During the following testing:
- https://github.com/wazuh/wazuh/issues/23702

It was discovered that there are some missing paths for the macOS python data provider. 

When Python is installed using brew (`brew install python3`), the installation path for the packages is `/opt/homebrew/lib/python3.9/site-packages`

We should update the path list, just like we did in:
- https://github.com/wazuh/wazuh/pull/23532/files

## DoD
- [x] Path list updated
- [x] Solution Tested

**Comment by mjcr99** [comment]
## Update:
**(1706/2024)** Opened PR with the proposed solution, requested resources to test it, and tested it.
