### ISSUE TITLE
Review cloud modules logging messages

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#23843]
|Epic branch|
|---|
| [16717-improve-cloud-modules-logging](https://github.com/wazuh/wazuh/tree/16717-improve-cloud-modules-logging) |

## Description

During the development of https://github.com/wazuh/wazuh/issues/14535, I have noticed some inconsistencies and some enhancements in the cloud modules log messages that should be addressed before reaching production.

1. Incorrect logging levels. We shouldn't have a debug message with a `WARNING` or `ERROR` tag. For example, in [aws_s3.py](https://github.com/wazuh/wazuh/blob/d04026de108e2db2e008563efaf1db6f28446af9/wodles/aws/aws_s3.py):

    ```py
    aws_logger.debug("+++ Warning: No regions were specified, trying to get events from supported regions")
    ```
    
    ```py
    aws_logger.debug(f"+++ ERROR: {exc}")
    ```

2. Logs with duplicated level tags. The logs should contain the level tag only once, we shouldn't have multiple tags in the same message. This

    ```py
    2024-05-31T17:19:39.1094609Z DEBUG    wazuh_testing:utils.py:668 :aws_wodle: - DEBUG - +++ DB Maintenance
    ```
    
    Should be
     
    ```py
    2024-05-31T17:19:39.1094609Z DEBUG    wazuh_testing:utils.py:668 :aws_wodle: - DB Maintenance
    ```

3. Plus signs at the start of the message. Messages are already formatted to start with a `-`, so we shouldn't have `+` characters at the start of the messages

    ```py
    aws_logger.debug('+++ Table does not exist; create')
    ```
    
    or they would look like this
    
    ```py
    DEBUG    wazuh_testing:utils.py:668 :aws_wodle: - DEBUG - +++ Table does not exist; create
    ```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
Closing due to the reasons mentioned [here](https://github.com/wazuh/wazuh/issues/14535#issuecomment-2269172002).
