### ISSUE TITLE
Support new OSs - Windows 11 24H2

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23859]
# Description 

This issue aims to add support for Windows 11 24H2.
Related OSs check issue: https://github.com/wazuh/wazuh/issues/23838

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | No | Minor |

# Plan

- **DevOps**
  - https://github.com/wazuh/wazuh/issues/23860
- **Agent**
  - https://github.com/wazuh/wazuh/issues/23861
- **Dashboard**
  - https://github.com/wazuh/wazuh/issues/23863
- **ThreatIntel**
  - https://github.com/wazuh/wazuh/issues/23864
- **QA**
  - https://github.com/wazuh/wazuh/issues/23969

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as done.
