### ISSUE TITLE
Support new OSs - Windows Server 2025

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23858]
# Description 

This issue aims to add support for Windows Server 2025.
Related OSs check issue: https://github.com/wazuh/wazuh/issues/23838

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | No | Major |

# Plan

- **DevOps**
  - https://github.com/wazuh/wazuh/issues/23887
- **CppServer**
  - https://github.com/wazuh/wazuh/issues/23922
- **Agent**
  - https://github.com/wazuh/wazuh/issues/23888
- **Dashboard**
  - https://github.com/wazuh/wazuh/issues/23889
- **ThreatIntel**
  - https://github.com/wazuh/wazuh/issues/23890
- **QA**
  - https://github.com/wazuh/wazuh/issues/23891

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as not planned.
