### ISSUE TITLE
Support new OSs - AlmaLinux 8.10

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23868]
# Description 

This issue aims to add support for AlmaLinux 8.10.
Related OSs check issue: https://github.com/wazuh/wazuh/issues/23838

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No | Minor |

# Plan

- **DevOps**
  - https://github.com/wazuh/wazuh/issues/23869
- **Agent**
  - https://github.com/wazuh/wazuh/issues/23870
- **Dashboard**
  - https://github.com/wazuh/wazuh/issues/23871
- **ThreatIntel**
  - https://github.com/wazuh/wazuh/issues/23872
- **QA**
  - https://github.com/wazuh/wazuh/issues/23971

**Comment by MarcelKemp** [comment]
Done.
