### ISSUE TITLE
Support new OSs - Windows 11 24H2 - Add SCA content

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23864]
## Description
Weekly OS check issue: https://github.com/wazuh/wazuh/issues/23838
Epic issue to check Windows 11 24H2: https://github.com/wazuh/wazuh/issues/23859

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | No | Minor |

# Plan

- [ ] If we need to add support for the agent, we need to make sure that basic OS ruleset and SCA policies are available for the new OS.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.
