### ISSUE TITLE
Support new OSs - Windows 11 24H2 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23865]
## Description
Weekly OS check issue: https://github.com/wazuh/wazuh/issues/23838
Epic issue to check Windows 11 24H2: https://github.com/wazuh/wazuh/issues/23859

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | No | Minor |

# Plan

- [ ] If the new OS's version is a major/new family, we need to add new tests according to the OS's tier.
- [ ] If the new OS's version is a major/new family,  we need to add proper documentation.

**Comment by jotacarma90** [comment]
Close due to not needed, new OS version found is not major/new family

**Comment by MarcelKemp** [comment]
Windows 11 24H2 is equivalent to a minor version.
