### ISSUE TITLE
Support new OSs - AlmaLinux 8.10 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23870]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23868 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No | Minor |

Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success. 
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

**Requested checks by tier:**
|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-| 
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: | :green_circle:|
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | :green_circle:|
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: | :green_circle:| 
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | |
| **SCA** | :white_circle: | :white_circle: | :black_circle: | :yellow_circle: |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Active response** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: |:green_circle: |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | |

**Comment by lchico** [comment]
# Testing

## :green_circle: Agent package install (enrollment and connectivity with the manager)

<details>
<summary>OS information</summary>

```console
bash-4.4# cat /etc/os-release 
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
```

</details>

<details>
<summary>Package install</summary>

```console
dnf update
rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
cat > /etc/yum.repos.d/wazuh.repo << EOF
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
EOF
yum install wazuh-agent-4.7.2-1
```

</details>

<details>
<summary>Agent enrollment and connection</summary>

```console
2024/06/05 03:11:09 wazuh-agentd: INFO: Version detected -> Linux |223dc7f90717 |6.5.0-28-generic |#29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 |x86_64 [AlmaLinux|almalinux: 8.10 (Cerulean Leopard)] - Wazuh v4.7.2
2024/06/05 03:11:09 wazuh-agentd: INFO: Started (pid: 2220).
2024/06/05 03:11:09 wazuh-agentd: INFO: Using AES as encryption method.
2024/06/05 03:11:09 wazuh-agentd: INFO: Trying to connect to server ([192.168.100.250]:1514/tcp).
2024/06/05 03:11:09 wazuh-agentd: INFO: (4102): Connected to the server ([192.168.100.250]:1514/tcp).
```

</details>



## :green_circle: Command monitoring

<details>
<summary>Result</summary>

Following configuration block is added in the agent:

```xml
<localfile>
  <log_format>full_command</log_format>
  <command>free -m | awk 'NR==2{printf "%.2f\t\t\n", $3*100/$2 }'</command>
  <alias>memory_utilization</alias>
  <frequency>120</frequency>
</localfile>
```

Following custom rule is added in the manager's `/var/ossec/etc/rules/local_rules.xml` file:

```xml
<group name="memory_utilization,">
  <rule id="100012" level="6">
    <if_sid>530</if_sid>
    <match>^ossec: output: 'memory_utilization'</match>
    <description>Memory utilization metric.</description>
  </rule>
</group>
```

Server and agent are restarted. Afer this the following alert is generated in the server:
```
** Alert 1717556523.682262: - memory_utilization,
2024 Jun 05 03:02:03 (223dc7f90717) any->memory_utilization
Rule: 100012 (level 6) -> 'Memory utilization metric.'
ossec: output: 'memory_utilization':
22.76
```

</details>

**Comment by lchico** [comment]
# Update
I have performed all the tests, and they are ready for review.

**Comment by mjcr99** [comment]
LGTM! Nice script for inventory testing by the way!
