### ISSUE TITLE
Support new OSs - Rocky Linux 8.10 - Add SCA content

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23878]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23874 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No| Minor |

# Plan

- [ ] If we need to add support for the agent, we need to make sure that basic OS ruleset and SCA policies are available for the new OS.

**Comment by ooniagbi** [comment]
We have a pending issue [here](https://github.com/wazuh/wazuh/issues/13406) with the same problem as Alma Linux. We need a release for this issue before we can state an ETA.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as not planned because it is a minor version.
