### ISSUE TITLE
Support new OSs - RHEL 8.10

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23879]
# Description 

This issue aims to add support for RHEL 8.10.
Related OSs check issue: https://github.com/wazuh/wazuh/issues/23838

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

# Plan

- **DevOps**
  - https://github.com/wazuh/wazuh/issues/23880
- **Agent**
  - https://github.com/wazuh/wazuh/issues/23886
- **CppServer** 
  - https://github.com/wazuh/wazuh/issues/23881
- **Indexer**
  - https://github.com/wazuh/wazuh/issues/23882
- **Dashboard**
  - https://github.com/wazuh/wazuh/issues/23883
- **ThreatIntel**
  - https://github.com/wazuh/wazuh/issues/23884
- **QA**
  - https://github.com/wazuh/wazuh/issues/23970

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as done.
