### ISSUE TITLE
Support new OSs - Rocky Linux 8.10

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23874]
# Description 

This issue aims to add support for Rocky Linux 8.10.
Related OSs check issue: https://github.com/wazuh/wazuh/issues/23838

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No| Minor |

# Plan

- **DevOps**
  - https://github.com/wazuh/wazuh/issues/23875
- **Agent**
  - https://github.com/wazuh/wazuh/issues/23876
- **Dashboard**
  - https://github.com/wazuh/wazuh/issues/23877
- **ThreatIntel**
  - https://github.com/wazuh/wazuh/issues/23878
- **QA**
  - https://github.com/wazuh/wazuh/issues/23972

**Comment by MarcelKemp** [comment]
Done.
