### ISSUE TITLE
Support new OSs - Rocky Linux 8.10 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23876]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23874 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No| Minor |

Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success. 
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

**Requested checks by tier:**
|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-| 
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: | :green_circle: | 
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | - |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | - |
| **SCA** | :white_circle: | :white_circle: | :black_circle: | :yellow_circle: |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Active response** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | - |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | - |

**Comment by mjcr99** [comment]
# Testing

## :green_circle: Agent package install (enrollment and connectivity with the manager)

<details>
<summary>OS information</summary>

```console
[root@linux-rocky vagrant]# cat /etc/os-release 
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
```

</details>

<details>
<summary>Package install</summary>

```console
[root@localhost vagrant]# curl -sO https://packages.wazuh.com/4.x/yum/wazuh-agent-4.7.4-1.x86_64.rpm
[root@localhost vagrant]# rpm -iv wazuh-agent-4.7.4-1.x86_64.rpm
warning: wazuh-agent-4.7.4-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY
Verifying packages...
Preparing packages...
wazuh-agent-4.7.4-1.x86_64
```

</details>

<details>
<summary>Agent enrollment and connection</summary>

```console
2024/06/04 11:00:02 wazuh-agentd: INFO: Started (pid: 35157).
2024/06/04 11:00:02 wazuh-agentd: INFO: Requesting a key from server: 192.168.56.100
2024/06/04 11:00:02 wazuh-agentd: INFO: No authentication password provided
2024/06/04 11:00:02 wazuh-agentd: INFO: Using agent name as: linux-rocky
2024/06/04 11:00:02 wazuh-agentd: INFO: Waiting for server reply
2024/06/04 11:00:02 wazuh-agentd: INFO: Valid key received
2024/06/04 11:00:02 wazuh-agentd: INFO: Waiting 20 seconds before server connection
2024/06/04 11:00:22 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2024/06/04 11:00:22 wazuh-agentd: INFO: Using AES as encryption method.
2024/06/04 11:00:22 wazuh-agentd: INFO: Trying to connect to server ([192.168.56.100]:1514/tcp).
2024/06/04 11:00:22 wazuh-agentd: INFO: (4102): Connected to the server ([192.168.56.100]:1514/tcp).
2024/06/04 11:00:22 wazuh-agentd: INFO: Agent is restarting due to shared configuration changes.
2024/06/04 11:00:25 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/06/04 11:00:28 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2024/06/04 11:00:28 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2024/06/04 11:00:28 wazuh-agentd: INFO: Version detected -> Linux |linux-rocky |4.18.0-513.24.1.el8_9.x86_64 |#1 SMP Thu Apr 4 18:13:02 UTC 2024 |x86_64 [Rocky Linux|rocky: 8.10 (Green Obsidian)] - Wazuh v4.7.5
2024/06/04 11:00:28 wazuh-agentd: INFO: Started (pid: 35367).
2024/06/04 11:00:28 wazuh-agentd: INFO: Using AES as encryption method.
2024/06/04 11:00:28 wazuh-agentd: INFO: Trying to connect to server ([192.168.56.100]:1514/tcp).
2024/06/04 11:00:28 wazuh-agentd: INFO: (4102): Connected to the server ([192.168.56.100]:1514/tcp).
```

</details>

**Comment by MarcelKemp** [comment]
LGTM.
However, I do not close the issue, in case it is necessary to replicate the testing on the machine provided by DevOps.

**Comment by mjcr99** [comment]
## Update
**(10/06/2024)** Updated provided machine state and configuration and enrolled with the testing server.

**Comment by MarcelKemp** [comment]
Done :green_circle:
