### ISSUE TITLE
Support new OSs - RHEL 8.10 - Add SCA content

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23884]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23879 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

# Plan

- **ThreatIntel**
- [x] If we need to add support for the agent, we need to make sure that basic OS ruleset and SCA policies are available for the new OS.

**Comment by ooniagbi** [comment]
SCA content has been updated in 4.9.0 for RHEL8: https://github.com/wazuh/wazuh/issues/17356, so this issue can be closed.
