### ISSUE TITLE
Agent-control tool shows agents as not connected when they are reporting

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2388]
## Bug report

**OS**
_Ubuntu18_

**Wazuh version**
_3.8.0-3802_

**Install type**
_manager_

**Install method**
_sources_

**Log sample**

```
Wazuh agent_control. List of available agents:
   ID: 000, Name: manager (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: agent1, IP: any, Never connected
   ID: 002, Name: agent2, IP: any, Never connected
   ID: 003, Name: agent3, IP: any, Never connected
```

Bug description
----------------

The call to `agent-control -l` shows all agents disconnected if I start Wazuh without Authd running, even though they are reporting correctly.

**Comment by DaveVG1** [comment]
Steps to reproduce
---
- I've managed to reproduce the second error by eliminating the agent **just** after the `rootcheck` scan ends (neither before nor after).
```
2019/03/25 12:28:08 wazuh-modulesd:database: ERROR: (1117): Could not retrieve informations of file '/var/ossec/queue/rootcheck/(AgentTest) 10.0.0.123->rootcheck' due to [(2)-(No such file or directory)].
```

**Comment by DaveVG1** [comment]
Summary
---
- I've been trying to delimit the error and I've discovered that the error happens if the agent is deleted after this line:
https://github.com/wazuh/wazuh/blob/b37ec9ae61839737a7500f9b6fb442fb32685623/src/wazuh_modules/wm_database.c#L1412
Or before this one:
https://github.com/wazuh/wazuh/blob/b37ec9ae61839737a7500f9b6fb442fb32685623/src/wazuh_modules/wm_database.c#L862

- I'm not sure if this is the expected behavior (as the file has certainly been deleted) or if we should change it.

**Comment by DaveVG1** [comment]
I haven't been able to reproduce the first error:
- I deactivated `Authd` and added an agent. When I restart the agent it appears as `Active` in `agent_control -l`:
```
ID: 005, Name: Ubuntu, IP: any, Active
```

**Comment by crolopez** [comment]
The reason for the agents are shown as never connected when they are reporting is that the permissions of the `/var/ossec/queue/agents-info` folder were altered. This means that agent-info files cannot be created

The agent-control tool uses these files to define the agent states.

The necessary permissions for this folder are `ossec:ossec`

**Comment by snaow** [comment]
False positive.
Agent info files must have the correct permissions as the rest of files present on the rest of folders.

User modifications in files and folder permissions cause the binaries and daemons not to work properly, that makes sense.
For example, setting `ossec.conf` permissions to `root:root/400` prevent file reads from any Wazuh daemon.

Closing.
