### ISSUE TITLE
Support new OSs - RHEL 8.10 - Test dashboard package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23883]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23879 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

# Plan

**Dashboard**
- [ ] **Central components**: Add support for the new OS to the GitHub Actions package builder.
- [ ] **Central components**: Smoke test that the package works, including installation and upgrade.
- [ ] **Agent**: Make sure that the agent-related information in the agent list is correct.
- [ ] **Agent**: Test the deployment one-liner for the new OS.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as unplanned because it is a minor version.
