### ISSUE TITLE
Support new OSs - RHEL 8.10 - Test manager package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23881]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23879 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

# Plan

- **CppServer** 
- [ ] If we need to add support for the central components, add support for the new OS to the GitHub Actions package builder.
- [ ] If we need to add support for the central components, smoke test that the package works, including installation and upgrade.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as unplanned because it is a minor version.
