### ISSUE TITLE
Support new OSs - Windows Server 2025 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23888]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23858 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
| Yes | 1 | No | Major|

Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success. 
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

**Requested checks by tier:**
|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-| 
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: | |
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | |
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: | | 
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | |
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | |
| **SCA** | :white_circle: | :white_circle: | :black_circle: | |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | |
| **Active response** | :white_circle: | :white_circle: | :black_circle: | |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: | |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | |

**Comment by vikman90** [comment]
This issue is **blocked** by:

- https://github.com/wazuh/wazuh/issues/23887

(ETA June 18th).

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.
