### ISSUE TITLE
Support new OSs - Windows Server 2025 - Check agent output in Dashboard

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23889]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23858 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
| Yes | 1 | No | Major|

# Plan

- **Dashboard**
- [ ] **Agent**: Make sure that the agent-related information in the agent list is correct.
- [ ] **Agent**: Test the deployment one-liner for the new OS.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.
