### ISSUE TITLE
Engine UX

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#23895]
# Description
This epic focuses on enhancing the user experience (UX) for configuring the engine, customizing rules/decoders with a wizard to guide users, relating decoders and rules, and providing a usable interface for viewing the history of an alert and all its associated elements. These improvements aim to make the system more intuitive, user-friendly, and efficient.

## Functional Requirements
- **Configuration Management**: Provide an intuitive interface for engine configuration changes, allowing users to easily adjust settings.
- **Rule Customization Wizard**: Develop a wizard to guide users through the process of creating and customizing rules, ensuring ease of use and reducing errors.
- **Decoder and Rule Relationship**: Implement features to relate decoders and rules clearly, providing a comprehensive view of how events are processed and alerts are generated.
- **Alert History Visualization**: Design a user-friendly interface to view the history of an alert, including all associated elements and their interactions, to facilitate better understanding and analysis.

## Implementation Restrictions
- **Consistency**: Ensure the new UX features are consistent with the existing design language and user interface of the system.
- **Compatibility**: The UX enhancements must be compatible with the current workchains
- **Accessibility**: The interface must be accessible to users with different levels of expertise.

## Plan
1. **Design Phase**:
    - Conduct user research to understand the needs and pain points related to engine configuration, rule/decoder customization, and alert history visualization.
    - Create prototypes for the new UX features.
    - Review WCS data model compliance with the requested features.
    - Validate designs with stakeholders through usability testing.

2. **Development Phase**:
    - Implement the configuration management interface, ensuring it is intuitive and easy to use.
    - Develop the rule customization wizard, providing step-by-step guidance for users.
    - Integrate features to relate decoders and rules, offering a clear overview of event processing.
    - Build the alert history visualization interface, ensuring it provides comprehensive and usable insights into alert details and their history.

3. **Testing and Validation**:
    - Conduct extensive usability testing to ensure the new UX features meet user needs and expectations.
    - Perform compatibility tests to ensure the new features integrate seamlessly with the engine.
    - Address any issues or feedback identified during testing.

**Comment by JcabreraC** [comment]
Closed in favor of https://github.com/wazuh/wazuh-dashboard/issues/198
