### ISSUE TITLE
Support new OSs - Windows Server 2025 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23891]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23858 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
| Yes | 1 | No | Major|

- **QA**
- [ ] **Major/New family**: Add new tests according to the OS's tier.
- [ ] **Major/New family**: Add proper documentation.
- [ ] **Agent**: Test functionality for all stateful modules according to the OS's tier.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.
