### ISSUE TITLE
Engine - Enforce Helper Builders to be Called Only in Allowed Stages

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#23897]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description:
This issue addresses a necessary enhancement in the Wazuh project to enforce that helper builders are called only during the allowed stages. Specifically, filter builders should be defined only in the 'check' or 'block' stages. If an attempt is made to build the asset outside of these stages, the build should fail.

### Steps to Reproduce:
1. Attempt to define a filter builder outside the 'check' or 'block' stages.
2. Observe that the build does not fail as expected.

### Expected Behavior:
- The system should restrict the definition of filter builders to the 'check' or 'block' stages.
- Any attempt to define filter builders outside these stages should result in a build failure.

### Actual Behavior:
Currently, it is possible to define filter builders outside the allowed stages, leading to potential inconsistencies or errors in the build process.

### Resolution:
- Implement a mechanism to enforce the allowed stages for defining filter builders.
- Ensure that the build process fails if filter builders are defined outside the 'check' or 'block' stages.

### Additional Context:
This enhancement is crucial to maintain the integrity and consistency of the build process, ensuring that all assets are built correctly and in the intended stages. 
This issue will be used to improve the meerkat decoder. The fix for the Suricata decoder will improve the overall stability and functionality of the system.

**Comment by JavierBejMen** [comment]
## Update
- Helper builder base ensures only appropriate helpers are builder based on the parameter passed.
- Added json decoding in the base integration decoder, so integrations can check conditions based on the original json content.
- Rebased 11334
