### ISSUE TITLE
Support new OSs - Windows Server 2025 - Test VD works properly with new OS

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23922]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23858 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
| Yes | 1 | No | Major|

# Plan

**CppServer**
- [ ] **Major/New family**: Make sure that VD works properly according to the OS tier.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.
