### ISSUE TITLE
Emails not sending from wazuh

### ISSUE THREAD

**Issue by RichardProchadzka** [wazuh/wazuh#23929]
Hi, i configured everything correctly and wazuh is not even trying to send email. Not even in a log... just basic alerts... 
Postfix, wazuh-manager... 
Ive setup ossec on two other servers and it was okay same config but wazuh... no luck 100% problem in wazuh or config files...

why ossec have wizard and this not?

```
<global>
    <email_notification>yes</email_notification> when yes and something is bad i should get error or not?
    <email_to>rexample</email_to>
    <smtp_server>localhost</smtp_server> even tried ip
    <email_from>example</email_from>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
    <agents_disconnection_time>10m</agents_disconnection_time>
    <agents_disconnection_alert_time>0</agents_disconnection_alert_time>
  </global>
```

**Comment by vikman90** [comment]
Hello @RichardProchadzka,

The message forwarding system has a minimum alert level, and it might be aggregating alerts.

Please try the following steps to verify if the issue lies with the email server or the Wazuh manager:

1. Start this program on the manager, which creates a simple SMTP server on the local port 25:
```python
#! /usr/bin/env python3

import smtpd
import asyncore

class CustomSMTPServer(smtpd.SMTPServer):
    def process_message(self, peer, mailfrom, rcpttos, data, **kwargs):
        print('Receiving message from:', peer)
        print('Message addressed from:', mailfrom)
        print('Message addressed to  :', rcpttos)
        print('Message length        :', len(data))
        print('Message               :', data.decode('utf-8'))
        return

def run_server():
    server = CustomSMTPServer(('127.0.0.1', 25), None)
    print("SMTP server running on 127.0.0.1:25")
    asyncore.loop()

if __name__ == '__main__':
    run_server()
```

2. Configure granular emails with a minimum level of 3:
```xml
<global>
  <email_notification>yes</email_notification>
  <smtp_server>127.0.0.1</smtp_server>
  <email_from>wazuh@example.wazuh.com</email_from>
  <email_to>recipient@example.wazuh.com</email_to>
  <email_maxperhour>12</email_maxperhour>
  <email_log_source>alerts.log</email_log_source>
</global>

<email_alerts>
  <email_to>recipient@example.wazuh.com</email_to>
  <level>3</level>
  <format>full</format>
  <do_not_delay />
</email_alerts>
```
This should make the SMTP server print all the alerts.

<details><summary>Example</summary>

> SMTP server running on 127.0.0.1:25
> Receiving message from: ('127.0.0.1', 47658)
> Message addressed from: wazuh@example.wazuh.com
> Message addressed to  : ['recipient@example.wazuh.com', 'recipient@example.wazuh.com']
> Message length        : 400
> Message               : To: <recipient@example.wazuh.com>
> From: Wazuh <wazuh@example.wazuh.com>
> To: <recipient@example.wazuh.com>
> Date: Thu, 06 Jun 2024 13:03:42 +0200
> Subject: Wazuh notification - Rocket - Alert level 3
> 
> 
> Wazuh Notification.
> 2024 Jun 06 13:03:40
> 
> Received From: Rocket->ossec
> Rule: 502 fired (level 3) -> "Wazuh server started."
> Portion of the log(s):
> 
> ossec: Manager started.
> 
> 
> 
> 
>  --END OF NOTIFICATION

</details>
I hope this helps.

Best regards.

**Comment by Doral-dev** [comment]
Hii 😁

I uploaded a GitHub repository with several PDFs where I explain how to receive Wazuh alerts in Gmail using a Python script. It is a valid and documented alternative by Wazuh, and it is quite easy to set up, so it might help you.

Repository:  
https://github.com/Doral-dev/Wazuh-alertas-Gmail

If it helped you, I would really appreciate it if you could give my GitHub repository a star 😊
