### ISSUE TITLE
Migrate `bump_version.py` script from wazuh-packages

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#23953]
# Description

Hi team, 

since the SPECS and package creation-related files have been migrated to this repository for the main supported systems, we need to keep updating those files. In the wazuh-packages repository, this task is made using the [bump_version.py](https://github.com/wazuh/wazuh-packages/blob/master/bump_version.py) script. 

To do so, in this repository, we need to migrate this functionality.

The possible contemplated solutions are the following:

- Migrate the script and place it in the tools [folder](https://github.com/wazuh/wazuh/tree/master/tools) with the [bump_version.sh](https://github.com/wazuh/wazuh/blob/master/tools/bump_version.sh) script and make the bump_version.sh script call the other one.

- Combine both scripts in one script, which would require deciding which language to use for this new mixed script, and translate one into the selected language.

**Comment by lchico** [comment]
# Update
I started doing some research.
