### ISSUE TITLE
Engine - Fix and Enhance Schema Recognition and Asset Metadata Integration

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#23952]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description

This issue aims to address and improve the following items in the Wazuh project:

1. Fix vs Schema Helper Pattern to Recognize Latest Format:
- The current schema helper pattern needs to be updated to correctly recognize and process the latest schema format. This is crucial for ensuring that the schema validation and processing work seamlessly with the most recent updates.

2. Change Module to Integration in Asset Metadata:
- Update the asset metadata by changing the terminology from 'module' to 'integration'. This change is aimed at improving clarity and consistency within the codebase, reflecting the intended use and functionality more accurately.

 3. Quality of Life (QoL) Improvements in Engine-Schema Python Script:
- Enhance the engine-schema.py script to improve its usability and maintainability. These improvements should include better error handling, code optimization, and possibly adding more descriptive logging or comments to help future developers understand and work with the script more easily.

Tasks:

- [x] Update the vs schema helper pattern to support the latest schema format.
- [x]  Modify the asset metadata terminology from 'module' to 'integration'.
- [x]  Implement QoL improvements in the engine-schema.py script, focusing on usability, maintainability, and code clarity.
- [x]  Test all changes to ensure they work correctly and do not introduce new issues.
- [x]  Update relevant documentation to reflect the changes made.

**Comment by JavierBejMen** [comment]
## Update
Modified engine-schema python template to update custom and variables in the vscode schema
Changed module to integration in wazuh-asset vscode schema
Fixed helper pattern in engine-schema fields generator

**Comment by JavierBejMen** [comment]
## Update
Fixed end of string in helper and ref pattern
Fixed parse item definition in schema
Ip not included as it will be overkill to create a regex to match all possible IP formats
Float distinction not included as in json only number is available
