### ISSUE TITLE
Support new OSs - Rocky Linux 8.10 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23972]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23874 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 2 | No| Minor |

  - [ ] If we need to add support for the agent, we need to do basic E2E test functionality for all stateful modules according to the OS's tier.
  - [ ] If the new OS's version is a major/new family, we need to add new tests according to the OS's tier.
  - [ ] If the new OS's version is a major/new family,  we need to add proper documentation.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as not planned because it is a minor version.
