### ISSUE TITLE
Support new OSs - RHEL 8.10 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23970]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/23838 | https://github.com/wazuh/wazuh/issues/23879 |

| Agent support | Agent tier | Central components support | OS type |
|-|-|-|-|
|Yes | 1 | Yes | Minor |

- **QA**
- [ ] **Major/New family**: Add new tests according to the OS's tier.
- [ ] **Major/New family**: Add proper documentation.
- [ ] **Agent**: Test functionality for all stateful modules according to the OS's tier.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as unplanned because it is a minor version.
