### ISSUE TITLE
Custom rules do not appear to be working for 4.7.5-1

### ISSUE THREAD

**Issue by dbray925** [wazuh/wazuh#23973]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.7.5-1 | Rules | Error |

## Description
Custom rules do not appear to be working as documented: 
https://documentation.wazuh.com/current/user-manual/ruleset/rules/custom.html

Within /var/ossec/logs/alerts/alerts.log I see:
> ** Alert 1717632001.4462: - syslog,access_control,pci_dss_10.2.5,gdpr_IV_32.2,
> 2024 Jun 06 00:00:01 (ldapserver-01.company.lan) 10.10.10.1->/var/log/ldap.log
> Rule: 2508 (level 3) -> 'OpenLDAP connection open.'
> Src IP: 10.10.10.2
> Dst IP: 0.0.0.0
> Jun  6 00:00:01 ldapserver-01 slapd[9959]: conn=195008 fd=35 ACCEPT from IP=10.10.10.2:48176 (IP=0.0.0.0:636)

So I create the following custom rule:
`sudo find /var/ossec/ruleset/rules -type f -exec grep -H -e 'id="2508"' {} \;`

> /var/ossec/ruleset/rules/0020-syslog_rules.xml:  <rule id="2508" level="3">

`sudo vim -o /var/ossec/ruleset/rules/0020-syslog_rules.xml /var/ossec/etc/rules/local_rules.xml`

Copy, paste, and update the existing entry into local_rules.xml which results in:
```
<group name="syslog,access_control,">
  <rule id="2508" level="0" overwrite="yes">
    <if_sid>2507</if_sid>
    <match>ACCEPT from</match>
    <description>OpenLDAP connection open.</description>
    <group>pci_dss_10.2.5,gdpr_IV_32.2,</group>
  </rule>
</group>
```

`sudo systemctl restart wazuh-manager.service`

Wait a few minutes, but the same "2508 (level 3)" alert shows up. 

Is this a bug, or am I missing something in the documentation?

**Comment by juliancnn** [comment]
Hi @dbray925 ,

The configuration is fine and I have tested the rule and I have no problems. If you want you can share the log file `/var/ossec/logs/ossec.log`, after restarting the manager. This will help us to see if there are any problems with the startup of the analysis engine.

On the other hand, if you want to silence the rule, I recommend a rule like the following. Child of the rule you want to mute and zero level, which will avoid the generation of alerts by rule 2508.

```xml
  <rule id="100010" level="0">
    <if_sid>2508</if_sid>
    <description>ignore rule 2508</description>
    <group>pci_dss_10.2.5,gdpr_IV_32.2,</group>
  </rule>
```

Regards,

**Comment by dbray925** [comment]
Interesting that the documentation doesn't show that method, and instead uses the 'overwrite="yes"' method. So I was under the impression that the overwrite was needed, as I originally had a similar rule as you've shown, but that wasn't working either. That's when I updated it to the overwrite method as documented. Regardless, neither are working. 

Log files are not showing any errors for analysisd:
> 2024/06/07 13:27:47 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
> 2024/06/07 13:27:53 wazuh-analysisd: INFO: Total rules enabled: '6834'
> 2024/06/07 13:27:53 wazuh-analysisd: INFO: Started (pid: 1956833).

I'll look into some debugging options to see if something else shows up in the logs.

For now, I've tried to simplify everything and do a wazuh-logtest. So, this should be working, right?

`sudo cat /var/ossec/etc/rules/local_rules.xml`

```
<!-- /var/ossec/etc/rules/local_rules.xml -->

  <rule id="100001" level="0">
    <if_sid>2508</if_sid>
    <description>Ignore specific alerts</description>
  </rule>

<!-- EOF /var/ossec/etc/rules/local_rules.xml -->
```

```
sudo systemctl restart wazuh-manager.service
sudo /var/ossec/bin/wazuh-logtest
```

Paste in the following line:
>Jun  7 13:30:55 ldapserver-01.company.lan slapd[11952]: conn=183347 fd=33 ACCEPT from IP=10.10.10.2:48284 (IP=0.0.0.0:636)

Unfortunately, the result is:
```
**Phase 1: Completed pre-decoding.
        full event: 'Jun  7 13:30:55 ldapserver-01.company.lan slapd[11952]: conn=183347 fd=33 ACCEPT from IP=10.10.10.2:48284 (IP=0.0.0.0:636)'
        timestamp: 'Jun  7 13:30:55'
        hostname: 'ldapserver-01.company.lan'
        program_name: 'slapd'

**Phase 2: Completed decoding.
        name: 'openldap'
        parent: 'openldap'
        accumulate: '1'
        dstip: '0.0.0.0'
        id: '183347'
        srcip: '10.10.10.2'

**Phase 3: Completed filtering (rules).
        id: '2508'
        level: '3'
        description: 'OpenLDAP connection open.'
        groups: '['syslog', 'access_control']'
        firedtimes: '1'
        gdpr: '['IV_32.2']'
        mail: 'False'
        pci_dss: '['10.2.5']'
**Alert to be generated.
```

I _should_ be seeing rule 100001, correct?

**Comment by dbray925** [comment]
OK, I think I've discovered a reason, using the debug options:

`sudo vim /var/ossec/etc/local_internal_options.conf`

> analysisd.debug=2

```
sudo systemctl restart wazuh-manager.service
sudo grep 'Adding rule:' /var/ossec/logs/ossec.log | grep local
```

This comes back blank. Obviously if I remove the 'grep local' part, then I see all the default 'ruleset/rules' getting added, but I never see anything like:
_wazuh-analysisd[124318] rules-config.c:371 at Read_Rules(): DEBUG: Adding rule: etc/rules/local_rules.xml_

Why isn't the /var/ossec/etc/rules/local_rules.xml getting added? Permissions on the file are correct:
>-rw-r----- 1 wazuh wazuh  329 Jun  7 13:48 local_rules.xml

Very odd.

**Comment by juliancnn** [comment]
Yes, rule 100001 should fire, it does not seem to be loading the custom rule file.

Can you share de rule test configuration from `/var/ossec/etc/ossec.conf` file?

It should be something like the following:
```xml

  <ruleset>
    <!-- Default ruleset -->
    <decoder_dir>ruleset/decoders</decoder_dir>
    <rule_dir>ruleset/rules</rule_dir>
    <rule_exclude>0215-policy_rules.xml</rule_exclude>
    <list>etc/lists/audit-keys</list>
    <list>etc/lists/amazon/aws-eventnames</list>
    <list>etc/lists/security-eventchannel</list>

    <!-- User-defined ruleset -->
    <decoder_dir>etc/decoders</decoder_dir>
    <rule_dir>etc/rules</rule_dir>
  </ruleset>
```

**Comment by dbray925** [comment]
Thank you!!!  That was it. Typos in the ruleset section. Wow, can't believe I missed that. Really appreciate the help with this @juliancnn 

Updating the ossec.conf file finally showed it trying to load up the /var/ossec/etc/rules/local_rules.xml file, and let me know that I needed to add a 'group name="TEST" and closing group tags. 
```

<!-- /var/ossec/etc/rules/local_rules.xml -->
<group name="TEST">
  <rule id="100094" level="0">
    <if_sid>2508</if_sid>
    <description>Ignore: OpenLDAP connection open</description>
  </rule>
</group>
<!-- EOF /var/ossec/etc/rules/local_rules.xml -->
```

_Now_ the test is giving the expected results:
```
**Phase 3: Completed filtering (rules).
        id: '100001'
        level: '0'
        description: 'Ignore: OpenLDAP connection open'
        groups: '['TEST']'
        firedtimes: '1'
        mail: 'False'

```

Really appreciate the help with this. Issue resolved.

**Comment by juliancnn** [comment]
You're welcome, I'm glad to hear that!
Regards
