### ISSUE TITLE
Investigate `scripts` file of packages

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#23988]
## Description

The CPython-generated packages to update dependencies contain the necessary dependency files within the `/lib/python3.10/site-packages/ `directory. However, within this path, a file named `scripts` is also being generated, which wasn't there before. 

This file contains executables and seems to have started generating since we began working with `Python 3.10`

The latest packages generated with `Python 3.9`:

- Update issue: https://github.com/wazuh/wazuh/issues/18984
- If we open those packages, which were the last ones generated with `Python 3.9`, we can observe that within the path, that file does not exist:

![image](https://github.com/wazuh/wazuh/assets/96108386/04de0dfa-bcfc-4500-885f-5ed1b6b81647)

The following packages were generated with `Python 3.10`:
- However, the following packages were already generated with `Python 3.10`, which started generating the mentioned file:
- Update issue: https://github.com/wazuh/wazuh/issues/20354

![image](https://github.com/wazuh/wazuh/assets/96108386/033ae2a1-9944-44f8-8093-a987fb616c8d)

This file is being generated in the pre-installed packages for both architectures (`AMD` and `AARCH`).

## Possible related issues:
- https://github.com/wazuh/wazuh/pull/18466

## Possible tasks to carry out for the investigation:
- Investigate possible changes in the repository
- Investigate if this is being generated manually at any step of the updates
- Check if this file is essential for package generation

**Comment by javiersanchz** [comment]
## Update 

For this research, I will use the latest packages generated for `DEPS_VERSION=30`, related to https://github.com/wazuh/wazuh/issues/24254.

**Comment by javiersanchz** [comment]
## Update

### Test to verify if the file is necessary in the pre-installed

I have set up a test environment following the steps we use for package creation, using the latest source files from https://github.com/wazuh/wazuh/issues/24254: 

```console
[root@518318f95eb5 /]# cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
...
Starting Wazuh...
server
2024/07/03 12:51:57 wazuh-modulesd:router: INFO: Loaded router module.
2024/07/03 12:51:57 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Starting Wazuh v4.9.0...
Started wazuh-apid...
Started wazuh-csyslogd...
Started wazuh-dbd...
2024/07/03 12:51:59 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
Started wazuh-integratord...
Started wazuh-agentlessd...
Started wazuh-authd...
Started wazuh-db...
Started wazuh-execd...
Started wazuh-analysisd...
Started wazuh-syscheckd...
Started wazuh-remoted...
Started wazuh-logcollector...
Started wazuh-monitord...
2024/07/03 12:52:03 wazuh-modulesd:router: INFO: Loaded router module.
2024/07/03 12:52:03 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
Started wazuh-modulesd...
Completed.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com
```

Once the `CPython` has been updated with the latest packages and Wazuh is installed, we can see that the scripts file is located within `/framework/python/lib/python3.10/site-packages/.`, as expected:

```console
[root@518318f95eb5 ossec]# find . -name "scripts"
./api/scripts
./framework/python/lib/python3.10/site-packages/scripts
./framework/python/lib/python3.10/venv/scripts
./framework/scripts
```

When we generate the CPython  for the `pre-installed`, we extract the files related to api and wazuh from `site-packages`, leaving only the dependency files. However, in this case, apart from removing these files, I will also delete the scripts file located inside.

```console
[root@518318f95eb5 site-packages]# find . -name "scripts"
./scripts
[root@518318f95eb5 site-packages]# rm -rf scripts
[root@518318f95eb5 site-packages]# find . -name "scripts"
```

**Comment by javiersanchz** [comment]
## Update

I was doing more research on it and the problem may come from the changes that were made at https://github.com/wazuh/wazuh/pull/19340.

**Comment by javiersanchz** [comment]
## Update

After further investigation, it was found that these files are being generated due to changes made in:

https://github.com/wazuh/wazuh/pull/18466 → where the installation method was changed from `setup.py` to `pip`.
https://github.com/wazuh/wazuh/pull/19340 → where the `setup.py` file was modified.

It was verified that `scripts` file has been included in the package creation since after https://github.com/wazuh/wazuh/issues/18984

This file is not causing any errors in package generation, compilation, installation... and to prevent this file from being included in the `site-packages`, we should revert the changes from two issues.

After discussing with the team, it has been decided to leave it as it currently stands since it does not affect the behavior. If in any future case it is decided that the file should not appear, the issues that need to be reverted are documented

**Comment by GGP1** [comment]
## Review

The investigation correctly determined that the `scripts` folder is included in the packages after the switch to `pip` and proposed potential solutions to get rid of it. LGTM!

**Comment by fdalmaup** [comment]
This issue should be taken into consideration when generating packages for future releases.

LGTM!
