### ISSUE TITLE
Vulnerability detector Empty OS data from Wazuh-DB error

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24023]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc4| Wazuh component | Manager | Packages | CentOS |

## Description

Unexpected error in Vulnerability Detection module during footprint testing in [Release 4.8.0 - RC 4 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER](https://github.com/wazuh/wazuh/issues/24006):
```console
ossec_Test_stress_B5302_manager_2024-06-09/var/ossec/logs/ossec.log:2024/06/09 00:00:31 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::initEventDispatcher: Empty OS data from Wazuh-DB (agent 4358).
```

Previously reported in https://github.com/wazuh/wazuh/issues/23821

### Evidences

**Logs and configurations**: https://ci.wazuh.com/data/Test_stress/pre-release/4.8.0/B5302-3600m/B5302_manager_centos/logs/ossec_Test_stress_B5302_manager_2024-06-09.zip

**Comment by sebasfalcone** [comment]
@Rebits 
- Can we reproduce this with the logs in debug? 
```
wazuh_db.debug=2
wazuh_modules.debug=2
```

**Comment by sebasfalcone** [comment]
# Analysis

## Issue reproduction
If we disable the OS information from syscollector on the agents:
```xml
  <!-- System inventory -->
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1m</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>no</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>

    <!-- Database synchronization settings -->
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>
```

We can reproduce this exact behavior:
```
2024/06/10 12:05:24 wazuh-modulesd:vulnerability-scanner[37979] vulnerabilityScannerFacade.cpp:174 at operator()(): ERROR: VulnerabilityScannerFacade::initEventDispatcher: Empty OS data from Wazuh-DB (agent 023).
2024/06/10 12:30:38 wazuh-modulesd:vulnerability-scanner[37979] vulnerabilityScannerFacade.cpp:174 at operator()(): ERROR: VulnerabilityScannerFacade::initEventDispatcher: Empty OS data from Wazuh-DB (agent 024).
```

After re-enabling the OS information, this error disappears. But the events are lost

## Problem fix
We need to queue the events that fail due to this error to re process them

testing pending

**Comment by sebasfalcone** [comment]
## Update
Investigating failing tests

**Comment by sebasfalcone** [comment]
## Update
- Determined that this issue fixes https://github.com/wazuh/wazuh/issues/24035
- Continue the fix of the failing tests

**Comment by sebasfalcone** [comment]
## Update
- Unable to make the QA tests to pass (unexpected behaviour from changes)
