### ISSUE TITLE
Research items to remove from the repository

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#24037]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/22888

## Description

The goal of this spike is to conduct comprehensive research to identify and document the complete list of executable components, their corresponding files, dependencies (dead code), installers, and outdated documentation that need to be removed from the Wazuh repository. This initiative aligns with the planned removal of specific executable components as outlined in the main issue.

## Functional requirements

1. **Identify executable components for removal:**
   - Review the list of executable components slated for removal as specified in the main issue.
   - Document each executable component and its corresponding files.

2. **Dependencies (dead code):**
   - Identify code dependencies related to the executable components being removed.
   - Document any dead code that can be safely deleted without impacting the functionality of the remaining components.

3. **Installers:**
   - Review and identify installers, particularly those for local and hybrid modes, that reference the executable components to be removed.
   - Document necessary changes to the installers to reflect the removal of these components.

4. **Outdated documentation:**
   - Identify and document any outdated documentation related to the executable components and installers being removed.
   - Provide a summary of why the documentation is no longer needed and suggest updates where applicable.

## Implementation restrictions

1. **Avoid collateral effects:**
   - Ensure that the code which remains continues to function as expected.
   - Confirm that the removal of any item does not disrupt the current functionality of the Wazuh platform.

2. **Minimal changes:**
   - Focus on code removal only, without restructuring existing code.
   - Ensure that this issue is strictly about identifying and documenting items for deletion.

## Plan

1. **Research phase:**
   - Review the entire Wazuh repository, focusing on identifying files, documentation, and code that are candidates for removal based on the list of executable components.
   - Document each identified item with detailed descriptions and reasons for removal.

2. **Provisional code removal:**
   - Temporarily remove the code of the components slated for deletion.
   - Use these changes to identify unnecessary dependencies and dead code that can be safely removed.

3. **Documentation:**
   - Create a comprehensive report detailing all items identified for removal, including reasons, potential impacts, and any replacement plans.
   - Ensure that this report is accessible to all relevant team members.

By following this structured approach, we can ensure that the removal process is thoroughly planned and documented, facilitating a smoother execution phase in the future.

**Comment by Nicogp** [comment]
## Update 14/06/2024

- The analysis has been started.
- A file-by-file analysis is being performed. It has been started with the `src/active-response` directory.
- A document with a report like the following is being created:
```python
src/
↳ active-response/
   ↳ firewalls
       ↳ default-firewall-drop.c : 
              + Contains section of code that only runs if the OS is "FreeBSD", "SunOS", "NetBSD" or "AIX", that part must be deleted.
       ↳ ipfw.c :
              + Completely removed
              + Only contains "FreeBSD" functionality
              + Compilation must be removed in src/Makefile
              + Remove reference in installers src/init/inst-functions.sh and src/init/wazuh/wazuh.sh
              + Reference to ipfw in wazuh-jenkins repository, files: aixTemplateFiles.json and check_files_data.json
              + Reference to ipfw in wazuh-packages repository, file: solaris11/SPECS/template_agent.json
```

**Comment by vikman90** [comment]
## Spike: preserving Git history [WIP]

1. Clone wazuh/wazuh:
```shell
git clone git@github.com:wazuh/wazuh wazuh-origin
cd wazuh-origin
git remote rm origin    # For safety
```

2. Collect the list of directories that we want to preserve:
```shell
find src -type d | sort > ~/dirs.txt
```

3. Rewrite the history, preserving selected files:
```shell
git filter-branch `cat ~/dirs.txt | while read i; do echo -n --subdirectory-filter "$i"" "; done` -- --all
```
git filter-branch --subdirectory-filter

**Comment by vikman90** [comment]
## File migration according to new layout

### FIM

This is a preliminary procedure to adapt the FIM module:

```
cd src
mv syscheckd/CMakeLists.txt modules/fim
mv syscheckd/include/syscheck.h modules/fim/include/fim.h
mv syscheckd/src/syscheck.c modules/fim/src/fim.c
mv syscheckd/src/syscheck.c modules/fim/src/fim.c 
mv syscheckd/src/{db,registry,whodata} modules/fim
mv syscheckd/src/* modules/fim/src/

cd modules/fim/db
mv smokeTests tests/smoke
mv testtool tests

cd ../registry
mkdir include
mv registry.h include
mkdir src
mv *.c src

cd ../whodata/
mkdir include
mv syscheck_audit.h include
mkdir src
mv *.c src

cd ..
mv ../../unit_tests/syscheckd tests/unit
```

**Comment by TomasTurina** [comment]
## Analysis

Source code analysis (`/src`):

Keep the following files (root):
- `build.py`
- `Doxyfile`
- `Makefile`
  - Consider migrating to CMake.
- `CMakeLists.txt`

Folders analysis:

|Folder|File(s)|Keep|Notes|
|---|---|---|---|
|active-response|default-firewall-drop.c| 🟡 | Remove Tier3 code |
||ipfw.c| ❌ | Tier3 code |
||npf.c| ✅ ||
||pf.c| 🟡 | Remove Tier3 code |
||active-responses.h/active-responses.c| ✅ ||
||disable-account.c| 🟡 | Remove Tier3 code |
||firewalld-drop.c| ✅ ||
||host-deny.c| 🟡 | Remove Tier3 code |
||ip-customblock.c| ❌ | Irrelevant, unused |
||kaspersky.c/kaspersky.py| ❌ | Irrelevant, unused |
||netsh.c| ✅ ||
||restart-wazuh.c| ✅ ||
||restart.sh| 🟡 | Remove manager code |
||route-null.c| 🟡 | Remove Tier3 code |
||wazuh-slack.c| ✅ ||
|addagent|| ❌ |Deprecated CLI|
|agentlessd|| ❌ |Deprecated daemon|
|analysisd|| ❌ |Deprecated daemon|
|ci|| ✅ ||
|client-agent|| ❌ |Deprecated daemon|
|config|| ❌ |Config will be migrated to TOML|
|data_provider|| ✅ ||
|error_messages|debug_messages.h| 🟡 | Remove unnecessary logs |
||error_messages.h| 🟡 | Remove unnecessary logs |
||information_messages.h| 🟡 | Remove unnecessary logs |
||warning_messages.h| 🟡 | Remove unnecessary logs |
|headers/shared|agent_messages_adapter.h/agent_messages_adapter.c| ✅ ||
||agent_op.h/agent_op.c| 🟡 | Remove unused functions |
||ar.h| ❌ | Unused functions/defines |
||atomic.h/atomic.c| ✅ ||
||audit_op.h/audit_op.c| ✅ ||
||auth_client.h/auth_client.c| ❌ | Unused functions/defines |
||b64.c| ✅ ||
||binaries_op.h/binaries_op.c| ✅ ||
||bqueue_op.h/bqueue_op.c| ❌ | Unused functions/defines |
||buffer_op.h/buffer_op.c| ❌ | Unused functions/defines |
||bzip2_op.h/bzip2_op.c| ❌ | Unused functions/defines |
||cluster_utils.h/cluster_utils.c| ❌ | Unused functions/defines |
||cryptography.h/cryptography.c| ✅ ||
||custom_output_search.h/custom_output_search.c| ❌ | Unused functions/defines |
||debug_op.h/debug_op.c| 🟡 | Improve functions |
||defs.h| 🟡 | Clean file |
||dll_load_notify.h/dll_load_notify.c| ✅ ||
||enrollment_op.h/enrollment_op.c| ❌ | Unused functions/defines |
||exec_op.h/exec_op.c| ✅ ||
||expression.h/expression.c| 🟡 | Remove unused functions |
||file_op.h/file_op.c| 🟡 | Remove unused functions |
||file-queue.h/file-queue.c| ❌ | Unused functions/defines |
||fs_op.h/fs_op.c| 🟡 | Clean file |
||hash_op.h/hash_op.c| ✅ ||
||help.h/help.c| ❌ | Unused functions/defines |
||integrity_op.h/integrity_op.c| ❌ | Unused functions/defines |
||json_op.h/json_op.c| 🟡 | Remove unused functions |
||json-queue.h/json-queue.c| ❌ | Unused functions/defines |
||labels_op.h/labels_op.c| ❌ | Unused functions/defines |
||list_op.h/list_op.c| ✅ ||
||log_builder.h/log_builder.c| ✅ ||
||logging_helper.h/logging_helper.c| ✅ ||
||math_op.h/math_op.c| ✅ ||
||mem_op.h/mem_op.c| 🟡 | Remove unused functions |
||mq_op.h/mq_op.c| ❌ | Unused functions/defines |
||notify_op.h/notify_op.c| ❌ | Unused functions/defines |
||os_err.h| 🟡 | Clean file |
||os_ip.h| ❌ | Unused functions/defines |
||os_utils.h/os_utils.c| ✅ ||
||privsep_op.h/privsep_op.c| 🟡 | Clean file |
||pthreads_op.h/pthreads_op.c| ❌ | Will be replaced by coroutines |
||queue_linked_op.h/queue_linked_op.c| ✅ ||
||queue_op.h/queue_op.c| ✅ ||
||randombytes.h/randombytes.c| 🟡 | Remove unused functions |
||rbtree_op.h/rbtree_op.c| ✅ ||
||rc.h| ❌ | Unused functions/defines |
||read-agents.h/read-agents.c| 🟡 | Remove unused functions |
||read-alert.h/read-alert.c| ✅ ||
||regex_op.h/regex_op.c| 🟡 | Remove unused functions |
||remoted_op.h/remoted_op.c| ❌ | Unused functions/defines |
||report_op.h/report_op.c| ❌ | Unused functions/defines |
||request_op.h/request_op.c| ❌ | Unused functions/defines |
||rootcheck_op.h/rootcheck_op.c| 🟡 | Move to rootcheck module |
||rules_op.h/rules_op.c| ❌ | Unused functions/defines |
||rwlock_op.h/rwlock_op.c| ✅ ||
||schedule_scan.h/schedule_scan.c| ❌ | Unused functions/defines |
||sec.h| ❌ | Unused functions/defines |
||shared.h| 🟡 | Clean file |
||sig_op.h/sig_op.c| ✅ ||
||store_op.h/store_op.c| ✅ ||
||string_op.h/string_op.c| 🟡 | Remove unused functions |
||sym_load.h/sym_load.c| 🟡 | Remove unused functions |
||syscheck_op.h/syscheck_op.c| 🟡 | Move to syscheck module |
||sysinfo_utils.h/sysinfo_utils.c| ✅ ||
||time_op.h/time_op.c| ✅ ||
||url.h/url.c| ❌ | Will be replaced by http-request |
||utf8_op.h/utf8_op.c| 🟡 | Remove unused functions |
||validate_op.h/validate_op.c| 🟡 | Remove unused functions |
||vector_op.h/vector_op.c| ✅ ||
||version_op.h/version_op.c| 🟡 | Remove unused functions |
||wait_op.h/wait_op.c| ❌ | Unused functions/defines |
||wazuhdb_op.h/wazuhdb_op.c| ❌ | Unused functions/defines |
||yaml2json.h/yaml2json.c| ✅ ||
|init (& win32 scripts)|Install & upgrade scripts| 🟡 | Clean and improve |
||Other scripts| ❌ | Unnecessary scripts (backward compatibility) |
|logcollector|| ✅ | Clean defines |
|monitord|| ❌ |Deprecated daemon|
|os_auth|| ❌ |Deprecated daemon|
|os_crypto|aes| ❌ | Unused functions/defines |
||blowfish| ❌ | Unused functions/defines |
||hmac| ❌ | Unused functions/defines |
||md5| ✅ ||
||md5_sha1| ❌ | Unused functions/defines |
||md5_sha1_sha256| ✅ ||
||sha1| ✅ ||
||sha256| ✅ ||
||sha512| ❌ | Unused functions/defines |
||shared| ❌ | Unused functions/defines |
||signature| ✅ ||
|os_csyslogd|| ❌ |Deprecated daemon|
|os_dbd|| ❌ |Deprecated daemon|
|os_execd|| ✅ | Clean defines |
|os_integratord|| ❌ |Deprecated daemon|
|os_maild|| ❌ |Deprecated daemon|
|os_net|| ❌ |Relocate some functions|
|os_regex|| ❌ |Deprecated library|
|os_xml|| ❌ |Deprecated library|
|os_zlib|| ❌ |Deprecated library (wrapper)|
|remoted|| ❌ |Deprecated daemon|
|reportd|| ❌ |Deprecated daemon|
|rootcheck|| ✅ | Clean defines |
|selinux|| ✅ ||
|shared_modules|common| ✅ ||
||content_manager| 🟠 | All manager code |
||dbsync| ✅ ||
||indexer_connector| 🟠 | All manager code |
||keystore| 🟠 | All manager code |
||router| 🟠 | All manager code |
||rsync| ❌ | Deprecated module |
||utils/benchmark| ❌ | Not necessary |
||utils/flatbuffers| ❌ | Not necessary |
||utils/mocks| ❌ | Not necessary |
||utils/xz| ❌ | Not necessary |
||utils/tests| 🟡 | Remove unused functions tests |
||utils/*.hpp| 🟡 | Remove unused functions |
|syscheckd|| ✅ | Clean defines |
|unit_tests|active-response| ✅ ||
||addagent| ❌ | Not necessary UT |
||analysisd| ❌ | Not necessary UT |
||client-agent| ❌ | Not necessary UT |
||config| ❌ | Not necessary UT |
||config_files| 🟡 | Remove unused files |
||fluent_forwarder| ❌ | Not necessary UT |
||logcollector| ✅ ||
||monitord| ❌ | Not necessary UT |
||os_auth| ❌ | Not necessary UT |
||os_crypto| 🟡 | Remove unnecessary tests |
||os_csyslogd| ❌ | Not necessary UT |
||os_execd| ✅ ||
||os_integrator| ❌ | Not necessary UT |
||os_maild| ❌ | Not necessary UT |
||os_net| ❌ | Not necessary UT |
||os_regex| ❌ | Not necessary UT |
||os_xml| ❌ | Not necessary UT |
||os_zlib| ❌ | Not necessary UT |
||remoted| ❌ | Not necessary UT |
||shared| 🟡 | Remove unnecessary tests |
||syscheckd| ✅ ||
||wazuh_db| ❌ | Not necessary UT |
||wazuh_modules| 🟡 | Remove unnecessary tests |
||win32| ❌ | Not necessary UT |
||wrappers| 🟡 | Remove unnecessary tests |
||agent.cmake| ✅ ||
||winagent.cmake| ✅ ||
||Toolchain-win32.cmake| ✅ ||
||server.cmake| 🟠 | Manager UT |
|util|| ❌ |Deprecated CLIs|
|wazuh_db|| ❌ |Deprecated daemon|
|wazuh_modules|agent_upgrade/agent| ✅ ||
||agent_upgrade/manager| 🟠 | All manager code |
||agent_upgrade/wm_agent_upgrade.*| 🟡 | Remove unnecessary functions |
||syscollector| ✅ ||
||task_manager| ❌ |Deprecated module|
||vulnerability_scanner| 🟠 | All manager code |
||main.c/wmcom.c/wmodules_def.h/wmodules.c/wmodules.h| ✅ ||
||wm_aws.h/wm_aws.c| ✅ ||
||wm_azure.h/wm_azure.c| ✅ ||
||wm_ciscat.h/wm_ciscat.c| ❌ |Deprecated module|
||wm_command.h/wm_command.c| ✅ ||
||wm_content_manager.h/wm_content_manager.c| 🟠 | All manager code |
||wm_control.h/wm_control.c| ❌ |Deprecated module|
||wm_database.h/wm_database.c| ❌ |Deprecated module|
||wm_docker.h/wm_docker.c| ✅ ||
||wm_download.h/wm_download.c| ❌ |Deprecated module|
||wm_exec.c| 🟡 | Clean file |
||wm_fluent.h/wm_fluent.c| ❌ |Deprecated module|
||wm_gcp.h/wm_gcp.c| ✅ ||
||wm_github.h/wm_github.c| ✅ ||
||wm_ms_graph.h/wm_ms_graph.c| ✅ ||
||wm_office365.h/wm_office365.c| ✅ ||
||wm_oscap.h/wm_oscap.c| ❌ |Deprecated module|
||wm_osquery_monitor.h/wm_osquery_monitor.c| ✅ ||
||wm_router.h/wm_router.c| 🟠 | All manager code |
||wm_sca.h/wm_sca.c| ✅ ||
||wm_syscollector.h/wm_syscollector.c| ✅ ||
||wm_task_general.h/wm_task_general.c| ❌ |Deprecated module|
||wm_vulnerability_scanner.h/wm_vulnerability_scanner.c| 🟠 | All manager code |
|win32|| ❌ | Deprecated process (wazuh-agent) |
