### ISSUE TITLE
Different vulnerabilities found depending on whether the agent was previously registered or not

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#24035]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-rc4 | Vulnerability detection | Manager | Packages| Ubuntu Jammy |

## Description

During testing at https://github.com/wazuh/wazuh/issues/2398, it was found that the vulnerabilities differ depending on whether the agents were registered before or after Vulnerability detection was enabled. This has been detected in the `test_consistency_initial_scans` test, which checks that the vulnerabilities indexed are identical in both cases. 

<details open>
<summary>First execution (without debug)</summary>
<br>

- Report: [Test_e2e_system_293_test_vulnerability_detector.zip](https://github.com/user-attachments/files/15784011/Test_e2e_system_293_test_vulnerability_detector.zip)

- Diff: [data.json](https://github.com/user-attachments/files/15784060/data.1.json)

</details>

<details open>
<summary>Second execution (with debug)</summary>
<br>

- Report: Too big, shared via Slack

- Diff: [data.json](https://github.com/user-attachments/files/15784019/data.json)

</details>

**Comment by sebasfalcone** [comment]
## Update
- Started testing over two ubuntu22 machines

**Comment by sebasfalcone** [comment]
## Update
Agent B deleted using the API:
```json
{
  "data": {
    "affected_items": [
      "002"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents were deleted",
  "error": 0
}
```

Indexer cleaned:
![image](https://github.com/wazuh/wazuh/assets/34063881/e1a307ce-cff8-4f3b-a094-3c71e6434adb)


Register agent again:
![image](https://github.com/wazuh/wazuh/assets/34063881/b015299c-f849-42c3-b8be-5c2ad1e9a806)

The same amount of vulnerabilities found

> [!NOTE]
> After repeating the process 5 times I was able to reproduce the issue

The following logs were present when that happened:
```
2024/06/12 19:10:38 wazuh-modulesd:vulnerability-scanner[3499] vulnerabilityScannerFacade.cpp:176 at operator()(): ERROR: VulnerabilityScannerFacade::initEventDispatcher: Empty OS data from Wazuh-DB (agent 004).
```

**Comment by juliamagan** [comment]
After running the test again with the packages created for commit f179e6d46aea316b3340ff37fea408bafd764d7d, we can see that the behavior is the same:

- Report: [Test_e2e_system_297_test_vulnerability_detector.zip](https://github.com/user-attachments/files/15822832/Test_e2e_system_297_test_vulnerability_detector.zip)
- Diff: [data.json](https://github.com/user-attachments/files/15822848/data.2.json)

**Comment by sebasfalcone** [comment]
## Update
- Unable to make the QA tests to pass (unexpected behaviour from changes)

**Comment by sebasfalcone** [comment]
## Conclusion
The underlying issue was not enough time for the indexer connector to sync. In [this PR](https://github.com/wazuh/wazuh/pull/23096) we introduced a synchronization mechanism for the indexer connector, with a 30-minute cooldown. The test wasn't waiting that long

This is the expected behaviour so the test will be fixed here:
- https://github.com/wazuh/wazuh-qa/issues/5501

We are closing this issue
