### ISSUE TITLE
Engine - Update Environment Setup

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24039]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

Update Environment Setup for Engine

## Description:
We need to check and update the environment setup instructions for the Engine. This includes:
- Ensuring the instructions are accurate and complete.
- Adding any new prerequisites or dependencies.
- Ensuring the setup process is clear and easy to follow.

Tasks:
- [x] Review the current environment setup instructions.
- [x] Update with new prerequisites or dependencies.
- [x] Ensure the setup process is clear and easy to follow.

References:

[Environment setup](https://docs.google.com/document/d/1FvBedeyAD1TniSl4yfgskT4aSaxhPs8eKi3ySKUpne8/edit#heading=h.k2r2a39mafs4)

**Comment by JavierBejMen** [comment]
## Update
QoL and added vs code format and remote settings.

**Comment by JcabreraC** [comment]
## Update
- Migrated the document to Google Sites
- Enhanced the guide with proper formatting and images
- Implemented minor corrections and improvements

**Comment by JcabreraC** [comment]
## Update
- Documentation is complete and ready for review.

**Comment by juliancnn** [comment]
LGTM!
