### ISSUE TITLE
rsyslog server to wazuh server logs forwarding issue. 

### ISSUE THREAD

**Issue by romanoff23** [wazuh/wazuh#24048]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.5 | Wazuh component | Manager/Agent | Packages/Sources | Ubuntu 22.04 (aws) |

Hey Community, I have an issue. So we have a rsyslog server which collects logs from the zscaler . Have a wazuh agent installed on this server to perform log forwarding to the wazuh server.  I am unable to forward the logs from the rsyslog server to the wazuh server. From the tcpdump performed on the wazuh server, we can see that the port is open, whitelisted and receiving traffic from the syslog server. Perofomed a packet capture and the server is receiving more number of bytes than the actual file(because of encryption). However, we are unable to view the zscaler logs on the wazuh-manager. 

Any suggestions are highly appreciated . 

Regards

**Comment by romanoff23** [comment]
Hello There, May i know how to disable the TLS temporarily to atleast see the raw logs?

regards,

Sahithi

**Comment by romanoff23** [comment]
Hey There,

No I do not want to bypass the wazuh client and send logs directly. I believe some configuration issues in the syslog server where log forwarding to the wazuh manager should be enabled .

**Comment by juliancnn** [comment]
hi,

I don't understand exactly how you want the log to flow from zscaler to the manager, could you tell us more about it, it's something like this?

1. Zscaler sends a syslog log to a remote syslog server
2. RSyslog receives the log from zscaler and stores it in a file.
3. The same host that receives the log has the agent wazuh . The file is read with a localfile from the agent and sent to the manager.

**Comment by romanoff23** [comment]
I don't understand exactly how you want the log to flow from zscaler to the manager, could you tell us more about it, it's something like this?

Zscaler sends a syslog log to a remote syslog server (Rsyslog)
RSyslog receives the log from zscaler and stores it in a file.
The same host that receives the log has the agent wazuh . The file is read with a localfile from the agent and sent to the manager.

yes.

**Comment by romanoff23** [comment]
Hey , so I am able to push the real time data like today's logs and not the historical data. Could you help me with that please. 
For Example:  If i give today's path in the agent's location conf file, I am able to see the archives.log file populate in wazuh. However, if i give yesterday's log file path in the agent's conf file, I am unable to pull the logs. I only see the audit logs.

**Comment by juliancnn** [comment]
> > RSyslog receives the log from zscaler and stores it in a file.

> yes.

Now that I understand your architecture, we can analyze further. When wazuh starts you should see a message in the log file (`/var/ossec/logs/ossec.log`) like the following: 
```
2024/06/14 14:51:12 wazuh-logcollector: INFO: (1950): Analyzing file: '/path to rsyslog file'.
```
This message indicates that the file is being tracked and that the logs written to it will be sent to the manager. Could you confirm me that you see this log?


>  Hey , so I am able to push the real time data like today's logs and not the historical data. Could you help me with that please.
For Example: If i give today's path in the agent's location conf file, I am able to see the archives.log file populate in wazuh. However, if i give yesterday's log file path in the agent's conf file, I am unable to pull the logs. I only see the audit logs.

Is this something that happens with the rsyslog file? If it is a different problem, please create a new issue or open a thread in the slack channel. Having separate issues makes it easier for the community to find related problems. However, wazuh does not send data from before configuring the file in the agent. You can the new archive logs while the agent was stopped if you have configured the [only-future-events](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#only-future-events) option. If you want to do this you will have to configure the archive and add the events to the archive manually afterwards.

**Comment by romanoff23** [comment]
2024/06/14 14:51:12 wazuh-logcollector: INFO: (1950): Analyzing file: '/path to rsyslog file'.
should this be on the agent or the sevrer?

Is this something that happens with the rsyslog file? If it is a different problem, please create a new issue or open a thread in the [slack channel](https://join.slack.com/t/wazuh/shared_invite/zt-2e0nak5th-o6CoT_SqJA34KWVdbYGfaw). Having separate issues makes it easier for the community to find related problems. However, wazuh does not send data from before configuring the file in the agent. It can send the new logs while the agent was stopped if you have configured the [only-future-events](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#only-future-events) option. If you want to do this you will have to configure the archive and add the events to the archive manually afterwards.


so, no changes were made in the rsyslog file. All this is happening only in the ossec.conf file of the agent. Yes , you are right only the logs that will be pulled post the agent was installed on the syslog server will be pulled into Wazuh. But the catch here is that all the logs are stored in the /log/folder and we tried to access them by using wildcard entries . Then too , only the new logs are being pulled. 

Can you actually confirm that the historical logs like a day before , those need to be added manually to the new files so that the agent can read them? Also , please explain about the only-future-events option more, 

Thanks !!

**Comment by juliancnn** [comment]
Hi romanoff23, sorry for the delay in reply, I have been off for the weekend.

> > 2024/06/14 14:51:12 wazuh-logcollector: INFO: (1950): Analyzing file: '/path to rsyslog file'.
>
> should this be on the agent or the sevrer?

You should see this message in the agent, since it is the agent that collects the logs of the files. This message indicates that wazuh-logcollector, the service in charge of reading the logs of the files, is following that file.

> so, no changes were made in the rsyslog file. All this is happening only in the ossec.conf file of the agent. Yes , you are right only the logs that will be pulled post the agent was installed on the syslog server will be pulled into Wazuh. But the catch here > is that all the logs are stored in the /log/folder and we tried to access them by using wildcard entries . Then too , only the new > logs are being pulled.

When Wazuh-Logcollecor discovers a new file, it always goes to the end of the file and starts reading new logs. It is not possible to change this behavior, we have some open issues related to it currently:
https://github.com/wazuh/wazuh/issues/4220
https://github.com/wazuh/wazuh/issues/4637

> Can you actually confirm that the historical logs like a day before , those need to be added manually to the new files so that the agent can read them? Also , please explain about the only-future-events option more,

The only-future-events option is used when you want to start reading from where you last left wazuh-logcollector. If logcollector was following a file, then the agent was stopped and logs were written to that file, then when the agent starts it will send the logs from the last time the agent was stopped. This would not be useful in your scenario though.
