### ISSUE TITLE
Engine - Update Integration Tutorial

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24041]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages | OS version |

|Epic|
|---|
|https://github.com/wazuh/wazuh/issues/23968|

## Description:
We need to update the integration tutorial to reflect the new features and functionalities of the Engine. This includes:
- New tools like engine-test.
- The use of namespaces.
- The process of developing an integration.

Tasks:
- [x] Review the current integration tutorial.
- [x] Update with new features and functionalities.
- [x] Include information on new tools.
- [x] Explain the use of namespaces.
- [x] Detail the process of developing an integration.
- [x] Move to google sites

**Comment by JavierBejMen** [comment]
## Update
Reviewed content of integration tutorial and updated to the current engine syntax and functionality the whole document.

**Comment by juliancnn** [comment]
## Daily update
- Reviewed and migrated to google sites

**Comment by juliancnn** [comment]
LGTM!
