### ISSUE TITLE
Error in Whodata events with strange characters

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2405]
## Bug report

**OS**
_Windows_

**Wazuh version**
_3.8.0-3804_

**Install type**
_agent_

**Install method**
_packages/sources_

**Log sample**

```
ossec-agent[552] create_db.c:218 at read_file(): DEBUG: Cannot access 'c:\windows\temp\test\garÃ‡onÃ±Ã±Ã±.rtf': it was removed during scan.
```

Bug description
----------------
Problem generating events by monitoring directories in Whodata with path containing strange characters. The path extracted in whodata looks like this:

`c:\windows\temp\test\garÃ‡onÃ±Ã±.rtf'`

When the path is read in frecuency and the hash table is filled in, it codes well:

`at read_file(): DEBUG: File 'c:\windows\temp\test\garÇonñññ.rtf'`

The result is:
a Whodata event is generated, the path does not match when searching for it in the hash table. The agent thinks that the file has been deleted and sends a message with the DELETE event to the manager. 
The manager tries to delete it from his database but the file does not exist, so the file is not monitored with whodata.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/2406.

**Comment by albertomn86** [comment]
Merged
