### ISSUE TITLE
Resource leak detected in Read_Cluster

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#24066]
## Description

The following defect, related to the cluster configuration parser `Read_Cluster`, has been reported by Coverity in #24063:

> CID: 1593415 [Resource leak](https://scan7.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_RESOURCE_LEAK)
> The system resource will not be reclaimed and reused, reducing the future availability of the resource.
> In Read_Cluster: Leak of memory or pointers to system resources ([CWE-404](http://cwe.mitre.org/data/definitions/404.html))

https://github.com/wazuh/wazuh/blob/917794389d2946763a2189cc32e3214cd595830f/src/config/cluster-config.c#L128

We need to investigate and fix the problem.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Similar problem in the past, as a reference: https://github.com/wazuh/wazuh/issues/19518

**Comment by Selutario** [comment]
Seems to be happening yet:
- https://github.com/wazuh/wazuh/issues/24148#issuecomment-2175944955

**Comment by nico-stefani** [comment]
# Update

I've been reviewing the remaining flaws and I needed to consult with the core team to find the best solution.

**Comment by nico-stefani** [comment]
I've tried to execute the scan to check the results after a42739b0b808f5f9e5eb1bf3212a859215d01957 without success.

I will meet with @MarcelKemp to review the problem.
