### ISSUE TITLE
Printf arg count mismatch detected in wm_aws_read

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#24067]
## Description

The following defects, related to the AWS configuration parser `wm_aws_read`, have been reported by Coverity in #24063:

> CID: 1593416 [Printf arg count mismatch](https://scan7.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_PW)
If there are too many arguments, some values will be ignored; if there are too few, undefined behavior may result.
> The number of arguments to printf does not match the format string ([CWE-685](http://cwe.mitre.org/data/definitions/685.html))

> CID: 1593414 [Printf arg count mismatch](https://scan7.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_PW)
If there are too many arguments, some values will be ignored; if there are too few, undefined behavior may result.
> The number of arguments to printf does not match the format string ([CWE-685](http://cwe.mitre.org/data/definitions/685.html))

https://github.com/wazuh/wazuh/blob/917794389d2946763a2189cc32e3214cd595830f/src/config/wmodules-aws.c#L544
https://github.com/wazuh/wazuh/blob/917794389d2946763a2189cc32e3214cd595830f/src/config/wmodules-aws.c#L549

We need to investigate and fix the problems.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Modified the log format to match the number of arguments.
