### ISSUE TITLE
Body content not shown in auth_context API log lines

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#24060]
|Wazuh version|Component|
|---|---|
| 4.9.0 | Wazuh API |

## Description
When using [API auth_context](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.security_controller.run_as_login), a hash is included in the api.log helping to determine which user is performing any future action using the obtained jwt token. 

For example, when logging in the dashboard (while `run_as` is enabled), it will send the API a request to `POST /security/user/authenticate` containing in the body all the information related to the user (username, role, tenants, etc.). The body is hashed and included in the auth log line and also, in all requests using the obtained token. Therefore, if we need to know who performs an action, we can look for the log line where `POST /security/user/authenticate` and the used hash appear:
![image](https://github.com/wazuh/wazuh/assets/23361101/aa87c785-8411-42ec-ac4a-05c10a576d27)

However, in 4.9.0, the body is empty, making this useless and a security problem:
```
2024/06/12 07:43:33 INFO: Listening on 0.0.0.0:55000.
2024/06/12 07:43:40 INFO: wazuh 172.16.1.1 "POST /security/user/authenticate" with parameters {} and body {} done in 0.389s: 200
2024/06/12 07:43:40 INFO: wazuh-wui (2afb9b83f9314e5d029766197f539792) 172.16.1.1 "POST /security/user/authenticate/run_as" with parameters {} and body {} done in 0.367s: 200
2024/06/12 07:43:47 INFO: wazuh-wui 172.16.1.1 "GET /agents" with parameters {"wait_for_complete": "true"} and body {} done in 0.136s: 200
```

We need to fix the logging so it shows the body content for all endpoints where it is required, including `POST /security/user/authenticate`.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

The request body was being accessed in the [security_controller](https://github.com/wazuh/wazuh/blob/917794389d2946763a2189cc32e3214cd595830f/api/api/controllers/security_controller.py#L133) and that caused the internal stream to be consumed, when I tried accessing the stream later it returned the following runtime error

```console
|   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/requests.py", line 242, in json
    |     body = await self.body()
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/requests.py", line 235, in body
    |     async for chunk in self.stream():
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/requests.py", line 218, in stream
    |     raise RuntimeError("Stream consumed")
    | RuntimeError: Stream consumed
```

So I had to parse the json body if it existed before calling the controller so it's stored in the `_json` field form the starlette request and can later be accessed without touching the stream.

Starlette related issue: https://github.com/encode/starlette/issues/493#issuecomment-487566994
