### ISSUE TITLE
Error using wazuh dashboard with domain name

### ISSUE THREAD

**Issue by jorgeimar** [wazuh/wazuh#24077]
Hello, i just upgraded my wazuh install and now i cant use the wazuh dashboard with a domain name, if i use it using the ip directly it works but using a domain i got this error:

Version: 2.10.0
Build: 48012
Error: Definition of plugin "visAugmenter" not found and may have failed to load.
read@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:640597
_callee3$@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:645304
tryCatch@https://wazuh.mydomaina.com.mx/47004/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:349:86027
invoke@https://wazuh.mydomaina.com.mx/47004/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:349:90047
plugin_asyncGeneratorStep@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641043
_next@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641385
@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641529
Promise@[native code]
@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641283
tryCatch@https://wazuh.mydomaina.com.mx/47004/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:349:86027
invoke@https://wazuh.mydomaina.com.mx/47004/bundles/plugin/reportsDashboards/reportsDashboards.plugin.js:349:90047
plugin_asyncGeneratorStep@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641043
_next@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641385
@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641529
Promise@[native code]
@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:641283
_callee$@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:654797
u@https://wazuh.mydomaina.com.mx/47004/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685542
@https://wazuh.mydomaina.com.mx/47004/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:382:1685292
plugins_service_asyncGeneratorStep@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:648789
_next@https://wazuh.mydomaina.com.mx/47004/bundles/core/core.entry.js:15:649149

Do i need to config anything on the new wazuh version to work with a domain?

Thanks in advance

**Comment by jorgeimar** [comment]
Today its working again with domain name,, idk what happend.

**Comment by pereyra-m** [comment]
Hello @jorgeimar !

Glad to know it's working, it's hard to know what happened if you don't see the error now.

Please, come back if you find any problem again.
