### ISSUE TITLE
Spike to identify additional log types that need decoders and prioritize their creation

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24097]
## Description
As we continue to enhance the capabilities of Wazuh, it is essential to identify and create decoders for internal log types generated by Wazuh itself. This spike aims to analyze and list additional log types that need decoders, and to prioritize their creation based on relevance and impact.

## Objectives:

- Conduct a comprehensive analysis of logs being ingested by Wazuh that currently do not have dedicated decoders.
- Identify gaps and potential new log types that would benefit from having decoders.
- Prioritize the creation of these decoders based on factors such as:
  - Frequency of log occurrence
  - Importance of log content for security analysis
  - User and community feedback
- Propose a roadmap for implementing the prioritized decoders.

## Acceptance Criteria:

- A documented list of new log types that need decoders.
- A prioritization matrix detailing the criteria used for prioritization.
- A proposed implementation roadmap for the creation of these decoders.
ization.

## Deliverables:
- Report on the analysis and findings.
- Prioritization matrix and roadmap document.

**Comment by Dwordcito** [comment]
TIME BOX for spike, ETA 21/08 

@JcabreraC assigned

**Comment by JcabreraC** [comment]
## Update
The main decoders of the Wazuh queues have been successfully tested in version 4.7.5. The list of tested decoders is:

- decoder/core-ciscat/0: LOCALFILE_MQ = '1'
- decoder/core-dbsync/0: DBSYNC_MQ = '5'
- decoder/core-hostinfo/0: HOSTINFO_MQ = '3'
- decoder/core-localfile/0: LOCALFILE_MQ = '1'
- decoder/core-rootcheck/0: ROOTCHECK_MQ = '9'
- decoder/core-rsyslog/0: SYSLOG_MQ = '2'
- decoder/core-sca/0: SCA_MQ = 'p'
- decoder/core-secure/0: SECURE_MQ = '4'
- decoder/core-syscheck/0: SYSCHECK_MQ = '8'
- decoder/core-syscollector/0: SYSCOLLECTOR_MQ = 'd'
- decoder/core-upgrade/0: UPGRADE_MQ = 'u'
- decoder/core-wazuh-message/0: See [Wazuh Message Format Documentation](https://documentation.wazuh.com/current/development/message-format.html) for specific details on message formatting.

**Comment by JcabreraC** [comment]
## Update
<details><summary>decoder/core-syscheck/0: SYSCHECK_MQ = '8' 🟢 </summary>

**Queue: `'8'` / `0x38` / `SYSCHECK_MQ`**

In this case, it is identified by the id `'8'` (SYSCHECK_MQ) and will push to the rules queue after being decoded. 
If the agent has 3.1.1 version or older, the event received will be in .log format and handled by "DecodeSyscheck". If not it will be taken by "decode_fim_event".
The format is used to determine the event version, being the later FIM messages on .json.

#### New F.I.M. module:
This is the only one that has a well-documented event format.
Functions used by the wdb module:

- `Fim_db_search`: interactive query mode, it can use previous query results data on new ones, e.g. by using fim_update_date.
- `Fim_get_scantime`: Searchs for scan-time from db.
- `Fim_control_msg`: Query without using the returned value (e.g. delete). 
- `Fim_update_date`: DITTO
- `Fim_database_clean`: DITTO
- `Wdbc_query_ex`: DITTO

<details>
<summary>Message format CLICK ME</summary>

```json
{
   "type":                  "event"
   "data": {
     "path":                string
     "hard_links":          array
     "mode":                "scheduled"|"realtime"|"whodata"
     "type":                "added"|"deleted"|"modified"
     "timestamp":           number
     "changed_attributes": [
       "size"
       "permission"
       "uid"
       "user_name"
       "gid"
       "group_name"
       "mtime"
       "inode"
       "md5"
       "sha1"
       "sha256"
     ]
     "tags":                string
     "content_changes":     string
     "old_attributes": {
       "type":              "file"|"registry"
       "size":              number
       "perm":              string
       "user_name":         string
       "group_name":        string
       "uid":               string
       "gid":               string
       "inode":             number
       "mtime":             number
       "hash_md5":          string
       "hash_sha1":         string
       "hash_sha256":       string
       "win_attributes":    string
       "symlink_path":      string
       "checksum":          string
     }
     "attributes": {
       "type":              "file"|"registry"
       "size":              number
       "perm":              string
       "user_name":         string
       "group_name":        string
       "uid":               string
       "gid":               string
       "inode":             number
       "mtime":             number
       "hash_md5":          string
       "hash_sha1":         string
       "hash_sha256":       string
       "win_attributes":    string
       "symlink_path":      string
       "checksum":          string
     }
     "audit": {
       "user_id":           string
       "user_name":         string
       "group_id":          string
       "group_name":        string
       "process_name":      string
       "cwd":               string
       "audit_uid":         string
       "audit_name":        string
       "effective_uid":     string
       "effective_name":    string
       "parent_name":       string
       "parent_cwd":        string
       "ppid":              number
       "process_id":        number
     }
   }
 }

Scan info "events":
{
  "type":                  "scan_start"|"scan_end"
  "data": {
    "timestamp":           number
  }
}

```

</details>

#### Legacy Syscheck module:
The event is pre-processed before using fim_db_search and fim_control_msg

<details>
<summary>Legacy message format. CLICK ME</summary>

```
Every syscheck message must be in the following format (OSSEC - Wazuh v3.10):
'checksum' 'filename'
 or
 'checksum'!'extradata' 'filename'
 or
                                             |v2.1       |v3.4  |v3.4         |v3.6  |v3.9               |v1.0
                                             |->         |->    |->           |->   |->                  |->
 "size:permision:uid:gid:md5:sha1:uname:gname:mtime:inode:sha256!w:h:o:d:a:t:a:tags:symbolic_path:silent filename\nreportdiff"
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^checksum^^^^^^^^^^^^^^^^^^^^^^^^^^^!^^^^^^^^^^^^^^extradata^^^^^^^^^^^^^^^^ filename\n^^^diff^^^
```

</details>

</details>

  - decoder/core-syscheck/0
  - decoder/fim/0
  - decoder/fim-event/0
  - decoder/fim-scan/0

<details><summary>decoder/core-hostinfo/0: HOSTINFO_MQ = '3' 🟡 </summary>

Process events that have the Hostinfo queue in the standard OSSEC message format.
It does not appear to be used

</details>

  - decoder/core-hostinfo/0

<details><summary>decoder/core-localfile/0: LOCALFILE_MQ = '1' 🟢</summary>

Process events that has the localfile queue in the standard OSSEC message format.
Handles implementation details of Wazuh, not intended for end users.

</details>

  - decoder/core-localfile/0
  - decoder/integrations/0 -> The main entry point from which all the decoders are derived.

<details><summary>decoder/core-rootcheck/0: ROOTCHECK_MQ = '9' 🟢</summary>

Process events that have the Rootcheck queue in the standard OSSEC message format.

</details>


  - decoder/core-rootcheck/0
  - decoder/rootcheck/0

<details><summary>decoder/core-rsyslog/0: SYSLOG_MQ = '2' 🟢</summary>

Process events that have the Rsyslog queue in the standard OSSEC message format.

</details>

  - decoder/core-rsyslog/0
  - decoder/integrations/0 -> The main entry point from which all the decoders are derived.

<details><summary>decoder/core-secure/0: SECURE_MQ = '4' 🟢</summary>

Process events that have the Secure queue in the standard OSSEC message format.
Remoted y monitord

</details>

  - decoder/core-secure/0

<details><summary>decoder/core-upgrade/0: UPGRADE_MQ = 'u'🟢</summary>

Exclusive parent decoder for events from upgrade queue (UPGRADE_MQ)

</details>

  - decoder/core-upgrade/0
  - decoder/upgrade/0 -> Decodes Upgrade confirmation messages

</details>

<details><summary>decoder/core-windows/0 🟢</summary>

Transforms the original Windows event into a json.

</details>

**Comment by JcabreraC** [comment]
## Update:
- Set up the engine environment on version 4.8.0.
- Encountered issues connecting the agent due to socket permissions. This will be resolved in this issue.
- Some decoders stopped working due to changes in the concatenation FH, invalidating previous tests. This will also be addressed in this issue.
- With the fixes, testing of the internal decoders on version 4.8.0 has begun.

**Comment by JcabreraC** [comment]
## Update
The engine has been updated to version 4.8.0. Some issues were present in a few decoders, but they have been resolved to facilitate testing.

The following decoders have been tested:
- decoder/core-wazuh-message/0 🟢
- decoder/core-ciscat/0: LOCALFILE_MQ = '1' 🟢
  -decoder/core-localfile/0
  - decoder/core-ciscat/0
  - decoder/ciscat/0
- decoder/core-dbsync/0: DBSYNC_MQ = '5' 🟢
  - decoder/dbsync-host-data/0
  - decoder/dbsync/0
  - decoder/syscollector-dbsync-host-data/0
  - decoder/syscollector-dbsync/0
- decoder/core-syscollector/0: SYSCOLLECTOR_MQ = 'd' 🟢
  - decoder/core-syscollector/0
  - decoder/syscollector-base/0
  - decoder/syscollector-dbsync-host-data/0
  - decoder/syscollector-dbsync/0
- decoder/core-sca/0: SCA_MQ = 'p' 🔴

**Comment by JcabreraC** [comment]
## Update
The engine has been updated to version 4.8.0. Some issues were present in a few decoders, but they have been resolved to facilitate testing.

The following decoders have been tested:
- decoder/core-syscheck/0: SYSCHECK_MQ = '8' 🟢
  - decoder/core-syscheck/0
  - decoder/fim/0
  - decoder/fim-event/0
  - decoder/fim-scan/0

- decoder/core-hostinfo/0: HOSTINFO_MQ = '3' 🟡
  - decoder/core-hostinfo/0

- decoder/core-localfile/0: LOCALFILE_MQ = '1' 🟢
  - decoder/core-localfile/0
  - decoder/integrations/0 -> The main entry point from which all the decoders are derived.

- decoder/core-rootcheck/0: ROOTCHECK_MQ = '9' 🟢
  - decoder/core-rootcheck/0
  - decoder/rootcheck/0

- decoder/core-rsyslog/0: SYSLOG_MQ = '2' 🟢
  - decoder/core-rsyslog/0
  - decoder/integrations/0 -> The main entry point from which all the decoders are derived.

- decoder/core-secure/0: SECURE_MQ = '4' 🟢
  - decoder/core-secure/0

- decoder/core-upgrade/0: UPGRADE_MQ = 'u'🟢
  - decoder/core-upgrade/0
  - decoder/upgrade/0 -> Decodes Upgrade confirmation messages

- decoder/core-windows/0 🟢

**Comment by JcabreraC** [comment]
## Summary:

Applying the changes from PR: https://github.com/wazuh/wazuh/issues/2412 to get everything working again in version 4.8.0, we have identified the following status for the internal decoders:

### Correctly Implemented:
- Decoder/core-wazuh-message/0 🟢
- Decoder/core-ciscat/0: LOCALFILE_MQ = '1' 🟢
  - Decoder/core-localfile/0
  - Decoder/core-ciscat/0
  - Decoder/ciscat/0

- Decoder/core-dbsync/0: DBSYNC_MQ = '5' 🟢
  - Decoder/dbsync-host-data/0
  - Decoder/dbsync/0
  - Decoder/syscollector-dbsync-host-data/0
  - Decoder/syscollector-dbsync/0

- Decoder/core-syscollector/0: SYSCOLLECTOR_MQ = 'd' 🟢
  - Decoder/core-syscollector/0
  - Decoder/syscollector-base/0
  - Decoder/syscollector-dbsync-host-data/0
  - Decoder/syscollector-dbsync/0

- Decoder/core-syscheck/0: SYSCHECK_MQ = '8' 🟢
  - Decoder/core-syscheck/0
  - Decoder/fim/0
  - Decoder/fim-event/0
  - Decoder/fim-scan/0

- Decoder/core-localfile/0: LOCALFILE_MQ = '1' 🟢
  - Decoder/core-localfile/0
  - Decoder/integrations/0 -> The main entry point from which all the decoders are derived.

- Decoder/core-rootcheck/0: ROOTCHECK_MQ = '9' 🟢
  - Decoder/core-rootcheck/0
  - Decoder/rootcheck/0

- Decoder/core-rsyslog/0: SYSLOG_MQ = '2' 🟢
  - Decoder/core-rsyslog/0
  - Decoder/integrations/0 -> The main entry point from which all the decoders are derived.

- Decoder/core-secure/0: SECURE_MQ = '4' 🟢
  - Decoder/core-secure/0

- Decoder/core-upgrade/0: UPGRADE_MQ = 'u'🟢
  - Decoder/core-upgrade/0
  - Decoder/upgrade/0 -> Decodes Upgrade confirmation messages

- Decoder/core-windows/0 🟢
- WPK
- Syscollector + AR
- Data enrichment

### Needs Improvement:
- Decoder/core-sca/0: SCA_MQ = 'p'
  - This decoder is a non-user accessible function. The entire process has been consolidated into a single helper function.
- Decoder/core-hostinfo/0: HOSTINFO_MQ = '3'
  - Process events that have the Hostinfo queue in the standard OSSEC message format. It does not appear to be used

### Not Implemented:
- Vuln-detector
- ossec-logcollector
- ossec-syscheck-audit: No known usage, no associated rules found.
- ossec-agent / ossec-agent-stop: Potential change with Wazuh protocol update.
- ossec-alert1 and ossec-alert: Indeterminate usage, does not appear to need migration.
- ossec-authd: No associated rules found.

### Rules That Should Be Decoders:
- 501 to 506: Agent startup, shutdown, etc.
- 509 to 521: Rootcheck
- 517: Syscheck audit?
- 520: Duplicate IP (note: protocol-related)
- 530 to 536: Command, full command
- 550 to 560: Syscheckd
- 580 to 581: Old hostinfo
- 591 to 593: File rotation
- 597 to 598: Syscheckd again
- 600 to 607: Active Response

**Comment by Dwordcito** [comment]
Action items after spike needed, re-opened.

**Comment by JcabreraC** [comment]
The investigation on the missing decoders for the new engine in Wazuh has been completed. As a result, new issues have been created to address the specific tasks needed:
- Engine - Migration and Enhancement of the ossec-logcollector decoder [#24309](https://github.com/wazuh/wazuh/issues/24309)
- Engine - Investigation and Implementation of decoders for New Vulnerability Detector Events [#24310](https://github.com/wazuh/wazuh/issues/24310)
- Engine - Investigation and Potential Migration of ossec-alert decoders [#24311](https://github.com/wazuh/wazuh/issues/24311)
- Engine - Migration of Agent and Manager Event Processing from wazuh-analysisd [#24312](https://github.com/wazuh/wazuh/issues/24312)
- Engine - Migration of rootcheck rule events to decoders [#24313](https://github.com/wazuh/wazuh/issues/24313)
 -Engine - Development of a Wazuh-Engine decoder for Syscheck Audit Events [#24314](https://github.com/wazuh/wazuh/issues/24314)
- Engine - Migration of Process Monitoring Rules to decoders [#24315](https://github.com/wazuh/wazuh/issues/24315)
- Engine - Migration of Duplicate IP Detection Rule to decoder [#24316](https://github.com/wazuh/wazuh/issues/24316)
- Engine - Investigation and Development nmap grepable decoder [#24317](https://github.com/wazuh/wazuh/issues/24317)
