### ISSUE TITLE
Remove sync mechanism from the indexer connector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24099]
## Description
This issue aims to remove all sync mechanisms from the indexer connector because the rsync algorithm is deprecated and now the agent will have a persistent queue and attended calls to synchronize the inventory.

## Expected
- Remove code
  - diff() method
  - getAgentDocumentsIds() method
  - abuseControl() method
  - sync() interface
  - remove m_db instance and all related calls for this instance.
- Thread dispatcher for sync mechanism.
- Comment the line in the scan_orchestrator code.
- remove all related test.

**Comment by sebasfalcone** [comment]
## Update
@Dwordcito I would like to have a call to discuss the implementation of this issue

**Comment by sebasfalcone** [comment]
## Re-estimated ETA
We weren't able to start working on this issue, due to release testing and VD issues being tackled

CC: @Dwordcito

**Comment by sebasfalcone** [comment]
## issue blocked
We are going to change the definitions of this issue
