### ISSUE TITLE
errors when compiling agent from sources /external/openssl mips64

### ISSUE THREAD

**Issue by cybert79** [wazuh/wazuh#2410]
Hi all, 

I get these errors when I run the .install script on my device with a mips64 CPU:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
Makefile:635: recipe for target 'crypto/aes/aes_ecb.o' failed
make[2]: *** [crypto/aes/aes_ecb.o] Error 1
make[2]: Leaving directory '/root/wazuh-3.8.0/src/external/openssl'
Makefile:133: recipe for target 'build_libs' failed
make[1]: *** [build_libs] Error 2
make[1]: Leaving directory '/root/wazuh-3.8.0/src/external/openssl'
Makefile:665: recipe for target 'external/openssl/libssl.a' failed
make: *** [external/openssl/libssl.a] Error 2
make: *** Waiting for unfinished jobs....

Anyone know how to fix this?

**Comment by crolopez** [comment]
Hi @cybert79,

This may be because your system doesn't have the libc6 developer library installed. 

Try installing the **libc6-dev-mips64** package. The package name may be different depending on your operating system.

Best regards.

**Comment by crolopez** [comment]
Hi @cybert79,

Let me close this issue. Feel free to reopen it if you still have compile errors.

Best regards.
