### ISSUE TITLE
Unsafe method of provisioning wazuh-keystore

### ISSUE THREAD

**Issue by artur-borys** [wazuh/wazuh#24110]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | Keystore | Wazuh Manager | Packages | all |

Hello, I've noticed the addition of wazuh-keystore in release 4.8.0

I think it has a major issue, because the only way to provide a password to be stored in the keystore, is to pass it via an argument in clear text. This is a bad practice, as the command invocation can be persisted in shell history. Additionally, there might be a short period of time, during which the password can be seen in plain-text in the output of command like ``ps`` or any tool which is monitoring processes, so there's a risk of it being leaked to unauthorized users.

The history can be disabled for the time of command execution, but it doesn't help with hiding the plain-text password on the process list.

Ideally, there should be possibility to provide the password via stdin, similarily to filebeat keystore, i.e:
``` bash
echo 'SecretPassword' | /var/ossec/bin/wazuh-keystore -f indexer -k password
```

In most, if not all, shell implementations, the commands like ``echo`` and ``printf`` are built-ins, which means that they are not visible on the process list. The only thing visible on the process list would be ``/var/ossec/bin/wazuh-keystore -f indexer -k password``, so there's no risk of leaking the password in plain-text.

**Comment by pereyra-m** [comment]
Hello @artur-borys , thank you for your feedback.

Maybe we can analyze it in this issue @Dwordcito https://github.com/wazuh/wazuh/issues/24098

As a workaround, maybe it'd be possible to write the RocksDB `queue/keystore` in a safe environment with the `wazuh-keystore` tool, and then move it to the server.

**Comment by artur-borys** [comment]
Thanks for reply, please also take a look at my other issue related to wazuh-keystore: https://github.com/wazuh/wazuh/issues/24111

**Comment by Dwordcito** [comment]
Known issue, Given the number of calls to curl in the upgrade process, this bad practice does not end with the solution of this issue. ex https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html#upgrading-the-wazuh-indexer


@sebasfalcone this impact the documentation (Upgrade, install, etc)

**Comment by artur-borys** [comment]
Curl can be easily replaced with different, more secure method of running the requests, but currently there's no workaround for wazuh-keystore.

On a side note - indexer admin key and cert can be used for authentication to wazuh-indexer API, instead of username and password

**Comment by Dwordcito** [comment]
We prioritize this task for the next OPEN release that is scheduled for the end of Q3/beginning of Q4, by disabling the history as you propose in a short live process like this one, the risk is not 100% mitigated, but it is contained enough, we will have the fix in 4.10, which today is at the beginning of Q4/end of q3.

**Comment by artur-borys** [comment]
And what about the second issue I've mentioned? About not supporting keys other than RSA

**Comment by Dwordcito** [comment]
> And what about the second issue I've mentioned? About not supporting keys other than RSA #24111

I understand your concern, I will see it asap, let's not mix it up please.

**Comment by pereyra-m** [comment]
## Update

I begin with the implementation.

I'll summarize different alternatives to overcome the problem, and I'll define which is the most suitable for this case. If possible, I'll add more than one.

**Comment by pereyra-m** [comment]
## Update

I have a draft implementation locally, now I'm creating a component QA test that runs the binary with the new parameters and confirms the right behavior.

**Comment by pereyra-m** [comment]
## Update

The testing took more time than expected, because the original approach of reading and decrypting the password directly from the test wasn't working. A small test tool was added to allow testing.

The PR was created and a Github Action test was created.

**Comment by pereyra-m** [comment]
## Update

I create the documentation PR and the manual tests evidences.

**Comment by pereyra-m** [comment]
## Update

I apply new review changes in the documentation PR.

**Comment by sebasfalcone** [comment]
## ETA updated
Updated ETA for final reviewer to review the changes

**Comment by sebasfalcone** [comment]
## ETA updated
Updated ETA for final reviewer to review the changes

**Comment by Dwordcito** [comment]
We need backport to 4.9.1 this issue @sebasfalcone

**Comment by pereyra-m** [comment]
## Update

I create the PR for the backport

**Comment by pereyra-m** [comment]
## Update 

I fix the names of the PRs.
