### ISSUE TITLE
ERROR: DB(7921) sqlite3_prepare_v2() : no such table: after update to 4.8.0

### ISSUE THREAD

**Issue by pormako** [wazuh/wazuh#24122]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|Wazuh v4.8.0|wazuh-db|Wazuh central components|from repo https://packages.wazuh.com/4.x/yum/|Oracle Linux 8|

Its a distributed install (2 wazuh-server, 3 wazuh-indexer, 1 wazuh-dashboard)
Ps Wazuh indexer username and password <- this is not self explanatory as nowhere in indexer setup such name is used, bur You refer to it in wazuh server upgrade instructions. Would be nice to konw exactly what this is (assuming wazuh-indexer user for filebeat?) and what privileges it needs to work (probably opensearch admin is not neccesary for this?)

Im using central components version.
In logs i see:
2024/06/17 12:26:12 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2(): no such table: metadata
2024/06/17 12:29:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:29:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info
2024/06/17 12:34:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:34:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info
2024/06/17 12:39:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:39:24 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info
2024/06/17 12:44:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:44:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info
2024/06/17 12:49:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:49:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info
2024/06/17 12:54:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(87): no such table: sync_info
2024/06/17 12:54:25 wazuh-db: ERROR: DB(7921) sqlite3_prepare_v2() stmt(85): no such table: sync_info

**Comment by MiguelazoDS** [comment]
Hi @pormako, 

There are similar issues to this one, there was a fix in early versions so we are investigating the causes of this. 
From which version did you upgrade to 4.8.0?

**Comment by pormako** [comment]
from wazuh-manager-4.7.3-1.x86_64 to wazuh-manager-4.8.0-1.x86_64

**Comment by MiguelazoDS** [comment]
Hi @pormako, 

Sorry for the inconvenience, this issue was already fixed here https://github.com/wazuh/wazuh/pull/23467 and it was part of 4.7.5, so any upgrade from 4.7.3 will cause this issue. 

Deleting the databases should fix the issue since they are created after a restart. 

Regards!

**Comment by sebasfalcone** [comment]
Inactive thread, feel free to re-open if necessary
