### ISSUE TITLE
Engine - Update Vagrant environment to Wazuh 4.8.0

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24120]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description:
Currently, the engine is running with Wazuh version 4.7.5.We need to update  to Wazuh version 4.8.0 and verify that all internal decoders continue to function correctly.

## Tasks:
Tasks:
1. Upgrade to Wazuh 4.8.0:
   - Update the environment to use Wazuh version 4.8.0.

2. Engine Compatibility Testing:
   - Conduct a full suite of tests to confirm the engine's compatibility and performance with Wazuh 4.8.0.
   - Document any issues or discrepancies that arise during testing.

3. Internal Decoders Validation:
   - Test all internal decoders in Wazuh to ensure they are functioning correctly with version 4.8.0.
   - Verify that there are no changes or regressions in decoder functionality.

4. Reporting:
   - Compile a detailed report of the testing process, findings, and any identified issues.
   - Provide recommendations for addressing any compatibility or functionality issues discovered.

## Expected Outcome:
- The engine should operate seamlessly with Wazuh version 4.8.0.
- All internal decoders in Wazuh should continue to function correctly.
- Comprehensive documentation of the testing results and any necessary corrective actions.

**Comment by JavierBejMen** [comment]
## Update
Updated vagrant to install manage 4.8
Stuck when trying to connect an agent, it stays in never connected. The problems seems to be the manager is not able to communicate with the agent. Tested ports and communication and its all fine.

**Comment by JavierBejMen** [comment]
## Update

Upon enabling the wazuh-db and remoted debug options, we have identified that remoted is unable to connect to the engine socket:

```
2024/06/18 10:02:34 wazuh-remoted[20505] mq_op.c:41 at StartMQWithSpecificOwnerAndPerms(): DEBUG: Can't connect to 'queue/sockets/queue': Permission denied (13). Attempt: 2
```

This behavior should be reported as an error message. The current silent failure makes it challenging to diagnose the issue, especially when the manager agent operates with incorrect permissions on the queue. Addressing this will improve clarity and aid in troubleshooting.

**Comment by JavierBejMen** [comment]
## Identified problems WIP
- Wrong permissions on `/var/ossec/queue/sockets/queue,` expected `root:wazuh`, actual `root:root`.
- Host info enrichment is not working, dbsync type state is never sent, therefore no kvdb with host info is created.

**Comment by JavierBejMen** [comment]
## Update
- Added socket file deletion before initializing the engine.
- Check socket file creation with max retries before changing the permissions.
- Up Vagrant with Wazuh 4.8
- Checked functionality of internal decoders for the manager agent and an ubuntu agent.
- Troubleshooting the agent never connected issue.

**Comment by juliancnn** [comment]
# Update


## :x: [Dashborad] Security events (v4.7) vs Thread hunting (v4.8)

In none of the versions it works, since the index is not added.

## [Dashborad] OpenSearch->Discover (v4.7) vs Explore->Discover (v4.8)

- v4.7 :white_check_mark: 
- v4.8 :x:  Doesn't work, problem with the field @timestsamp in the index pattern.


![Pasted image](https://github.com/wazuh/wazuh/assets/1891958/e9ca2b19-10cd-478c-92f0-986de1959e65)


## Syscheck 

### Dashbord, event and inventoty

- v4.7 :x:  Doesn't work, 
- v4.8 :x:  Doesn't work, 


## Pending
- CISCAT
- Rootcheck
- 


### Decoders

I have been able to generate FIM events but only from files and not from the registry. The events are json, they should not have problems to generate alerts, but the events are not normalized. We should modify the result of the decoder to save the query to the database.- v4.7 :yellow_circle:  Doesn't work, 

```json
{
    "wazuh": {
        "queue": 56,
        "location": "[003] (WIN-U72SUESA8JJ) any->syscheck",
        "isInternal": true,
        "origin": "syscheck",
        "registered_ip": "any",
        "decoders": [
            "core-syscheck",
            "fim",
            "fim-event"
        ],
        "source": "syscheck"
    },
    "event": {
        "original": "{\"data\":{\"attributes\":{\"attributes\":\"ARCHIVE, NOT_CONTENT_INDEXED\",\"checksum\":\"4b1cf172996ee3ba87f5ecfd7380721e4980a299\",\"hash_md5\":\"d41d8cd98f00b204e9800998ecf8427e\",\"hash_sha1\":\"da39a3ee5e6b4b0d3255bfef95601890afd80709\",\"hash_sha256\":\"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\",\"inode\":0,\"mtime\":1718740413,\"perm\":{\"S-1-5-21-3889906281-1130136531-540773895-1000\":{\"name\":\"vagrant\",\"allowed\":[\"delete\"]},\"S-1-5-18\":{\"name\":\"SYSTEM\",\"allowed\":[\"delete\",\"read_control\",\"write_dac\",\"write_owner\",\"synchronize\",\"read_data\",\"write_data\",\"append_data\",\"read_ea\",\"write_ea\",\"execute\",\"read_attributes\",\"write_attributes\"]},\"S-1-5-32-544\":{\"name\":\"Administrators\",\"allowed\":[\"delete\",\"read_control\",\"write_dac\",\"write_owner\",\"synchronize\",\"read_data\",\"write_data\",\"append_data\",\"read_ea\",\"write_ea\",\"execute\",\"read_attributes\",\"write_attributes\"]},\"S-1-5-32-545\":{\"name\":\"Users\",\"allowed\":[\"read_control\",\"synchronize\",\"read_data\",\"read_ea\",\"execute\",\"read_attributes\"]},\"S-1-1-0\":{\"name\":\"Everyone\",\"allowed\":[\"read_control\",\"synchronize\",\"read_data\",\"read_ea\",\"execute\",\"read_attributes\"]}},\"size\":0,\"type\":\"file\",\"uid\":\"S-1-5-32-544\",\"user_name\":\"Administrators\"},\"mode\":\"realtime\",\"path\":\"c:\\\\programdata\\\\microsoft\\\\windows\\\\start menu\\\\programs\\\\startup\\\\test.txt.txt\",\"timestamp\":1718740416,\"type\":\"added\",\"version\":\"2.0\"},\"type\":\"event\"}"
    },
    "agent": {
        "id": "003",
        "name": "WIN-U72SUESA8JJ",
        "type": "wazuh-agent"
    },
    "host": {
        "id": "003"
    },
    "json_event": {
        "data": {
            "attributes": {
                "attributes": "ARCHIVE, NOT_CONTENT_INDEXED",
                "checksum": "4b1cf172996ee3ba87f5ecfd7380721e4980a299",
                "hash_md5": "d41d8cd98f00b204e9800998ecf8427e",
                "hash_sha1": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
                "hash_sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
                "inode": 0,
                "mtime": 1718740413,
                "perm": {
                    "S-1-5-21-3889906281-1130136531-540773895-1000": {
                        "name": "vagrant",
                        "allowed": [
                            "delete"
                        ]
                    },
                    "S-1-5-18": {
                        "name": "SYSTEM",
                        "allowed": [
                            "delete",
                            "read_control",
                            "write_dac",
                            "write_owner",
                            "synchronize",
                            "read_data",
                            "write_data",
                            "append_data",
                            "read_ea",
                            "write_ea",
                            "execute",
                            "read_attributes",
                            "write_attributes"
                        ]
                    },
                    "S-1-5-32-544": {
                        "name": "Administrators",
                        "allowed": [
                            "delete",
                            "read_control",
                            "write_dac",
                            "write_owner",
                            "synchronize",
                            "read_data",
                            "write_data",
                            "append_data",
                            "read_ea",
                            "write_ea",
                            "execute",
                            "read_attributes",
                            "write_attributes"
                        ]
                    },
                    "S-1-5-32-545": {
                        "name": "Users",
                        "allowed": [
                            "read_control",
                            "synchronize",
                            "read_data",
                            "read_ea",
                            "execute",
                            "read_attributes"
                        ]
                    },
                    "S-1-1-0": {
                        "name": "Everyone",
                        "allowed": [
                            "read_control",
                            "synchronize",
                            "read_data",
                            "read_ea",
                            "execute",
                            "read_attributes"
                        ]
                    }
                },
                "size": 0,
                "type": "file",
                "uid": "S-1-5-32-544",
                "user_name": "Administrators"
            },
            "path": "c:\\programdata\\microsoft\\windows\\start menu\\programs\\startup\\test.txt.txt",
            "timestamp": 1718740416,
            "version": "2.0"
        },
        "type": "event"
    }
}
```

## Vulnerability scanner 

:dont'work: Doesn't work.

## SCA

- v4.7: Works
- v4.8: Doesn't work

## Syscollector

- v4.7: Doesn't work
- v4.8: Doesn't work

Problems with the origin field in `decoder/core-syscollector/0` and `decoder/syscollector-base/0`

## Enrichment

- v4.7: Doesn't work
- v4.8: Doesn't work

**Comment by juliancnn** [comment]
## Update


- The first time vagrant was started, wazuh-indexer crashed due to lack of memory, which generated a misdiagnosis of the discovery and SCA section. It was reinstalled and works correctly.
- We focused on the problem of the synchronization of the dbs, this could explain many of the problems and after a study of the messages we detected that the problem was in a helper function and its behavior, so that in some cases the query to the wazuh-db in the dbsync messages was not constructed correctly. This problem was fixed and solved.
  - Syscollector, now can see the agent inventory.
  - Data enhancement, fixed
  - FIM inventory, fixed
- Since AR is used for the integrity check with the agents, then we conclude that its operation remains the same. Although it would be good to test also the helper to generate AR query.
- `core-upgrade` (WPK) Works correctly

### Pending:
- Rootcheck
- CISCAT
- core-hostinfo
- decoder/core-secure/0

**Comment by juliancnn** [comment]
## Update

- After some research, it was decided to skip the `concat` test in the new `helper function testing framework` until the features of issue #24164 are merged. 
- Rootcheck decoder: It was analyzed, problems were identified and solved. Fixed the indexing in wazuh-indexer and corrected the query to the wazuh-db, now with the following events can be reflected the changes in the db.

Test events:
```
9:[002] (202-u20-dev-agent) any->rootcheck:Starting rootcheck scan.
9:[002] (202-u20-dev-agent) any->rootcheck:Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
9:[002] (202-u20-dev-agent) any->rootcheck:Ending rootcheck scan.
```

db state
![image](https://github.com/wazuh/wazuh/assets/1891958/e975610f-c183-4e6f-b28b-90b2bd077c81)


-  Started parsing `decoder/core-secure/0`, the decoder parses the queue where the only events processed are those collected by wazuh-logcollector with log_format `nmapg`: 
  - The only documentation is on [the ossec website](http://www.ossec.net/docs/manual/notes/nmap_correlation.html).
  - Wazuh-Analisisd has a [built-in decoder](https://github.com/wazuh/wazuh/blob/a5f51ad61af5abcf49186cd72d4d73c0c3927021/src/analysisd/decoders/hostinfo.c#L121-L235)
  - Wazuh-Logcollector [has a preprocess](https://github.com/wazuh/wazuh/blob/a5f51ad61af5abcf49186cd72d4d73c0c3927021/src/logcollector/read_nmapg.c#L127-L285) before send the event

### Pending:

core-hostinfo (in progress)
decoder/core-secure/0
CISCAT

**Comment by juliancnn** [comment]
## Update

### Core-hostinfo

After the analysis of this decoder, I created an issue dedicated to the treatment of this decoder: **Engine - Investigation and Development nmap grepable decoder #24317**

### Core-secure

After a thorough analysis, it was determined that wazuh-engine should not receive any messages coming from the secure_mq queue, except for a code error. Therefore, the decoder is left but its description is adjusted.

### Ciscat decoder

After researching and testing events, a bug was found in the formulation of the wazuh-db query and fixed. In addition to this it was established that the events should be indexed, so this was also fixed.

### Minor
Other minor changes, fixes to some decoder descriptions and corrections in the log source

## Pending

Only the Wazuh-Schema adjustment is pending, to add the ciscat fields.

**Comment by juliancnn** [comment]
## Update

- Update schema with ciscat and rootecheck fixes
- Complete the ciscat decoder
- Testing all with windows and ubuntu agent
- Rebase and fix conflics

**Comment by juliancnn** [comment]
## Update

- Change dbsync query
- Minos fixes en concat helper function
