### ISSUE TITLE
vulnerability-detection Debian false positives

### ISSUE THREAD

**Issue by dstr-wpd** [wazuh/wazuh#24123]
|4.8.0|vulnerability-detection|

## Description

after upgrading to 4.8.0 we have false positives:
![image](https://github.com/wazuh/wazuh/assets/74531770/b3047063-1513-49b1-8ee0-f11904a0280c)

seems like nessus has the exact same issue with this package: https://unix.stackexchange.com/questions/761535/nessus-is-reporting-false-positives-for-debian-12

Is this fixable? We did not have this false positive with 4.7.2

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Damian-Mangold** [comment]
Hello @dstr-wpd,

We have created this issue [Vulnerability Detection for libldb2 on Debian](https://github.com/wazuh/wazuh/issues/24306#top) to conduct an in-depth analysis of your report. As we progress with the analysis, we will update this issue with all relevant findings and developments.

Thank you for your patience and collaboration.

**Comment by Damian-Mangold** [comment]
Analysis of the user report has been completed and action will be taken to correct the content.
