### ISSUE TITLE
Support new OSs - SUSE Linux Enterprise 15 SP6 - Add SCA content

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24138]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/24128 | https://github.com/wazuh/wazuh/issues/24134 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Minor |

# Plan

**ThreatIntel**
- [ ] **Agent**: Make sure that basic OS ruleset and SCA policies are available for the new OS.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as not planned because it is a minor version.
