### ISSUE TITLE
Support new OSs - SUSE Linux Enterprise 15 SP6

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24134]
# Description
| Related issue |
|---|
| https://github.com/wazuh/wazuh/issues/24128 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Minor |

# Specific issues

**QA**
- https://github.com/wazuh/wazuh/issues/24135

**DevOps**
- https://github.com/wazuh/wazuh/issues/24136

**Dashboard**
- https://github.com/wazuh/wazuh/issues/24137

**ThreatIntel**
- https://github.com/wazuh/wazuh/issues/24138

**Agent**
- https://github.com/wazuh/wazuh/issues/24139

**Comment by MarcelKemp** [comment]
Done.
