### ISSUE TITLE
Support new OSs - macOS Sequoia 15

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24146]
# Description
| Related issue |
|---|
| https://github.com/wazuh/wazuh/issues/25665 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Specific issues

**QA**
- https://github.com/wazuh/wazuh/issues/24157

**CppServer**
- https://github.com/wazuh/wazuh/issues/24162

**DevOps**
- https://github.com/wazuh/wazuh/issues/24158

**ThreatIntel**
- https://github.com/wazuh/wazuh/issues/24160

**Agent**
- https://github.com/wazuh/wazuh/issues/24161

**Comment by MarcelKemp** [comment]
After changes in the process, all pending issues have been closed. I am therefore closing this epic issue as done.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/
