### ISSUE TITLE
Support new OSs - Oracle Linux 9.4 - Add support in QA procedures

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24141]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/24128 | https://github.com/wazuh/wazuh/issues/24140 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Minor |

# Plan

**QA**
- [ ] **Agent**: Test functionality for all stateful modules according to the OS's tier.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this testing issue as not planned because it is a minor version.
