### ISSUE TITLE
Support new OSs - Oracle Linux 9.4

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24140]
# Description
| Related issue |
|---|
| https://github.com/wazuh/wazuh/issues/24128 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Minor |

# Specific issues

**QA**
- https://github.com/wazuh/wazuh/issues/24141

**DevOps**
- https://github.com/wazuh/wazuh/issues/24142

**Dashboard**
- https://github.com/wazuh/wazuh/issues/24143

**ThreatIntel**
- https://github.com/wazuh/wazuh/issues/24144

**Agent**
- https://github.com/wazuh/wazuh/issues/24145

**Comment by MarcelKemp** [comment]
Done.
