### ISSUE TITLE
Vulnerability scanner shows RocksDB errors during startup

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#24151]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.8.0 | wazuh-modulesd - vulnerability scanner| Manager | Packages | TBD |

# Description

Members of the Wazuh community ([here](https://wazuh.slack.com/archives/C0A933R8E/p1718677840372149) and [here](https://wazuh.slack.com/archives/C0A933R8E/p1718363733719159) ) report some errors related to the Vulnerability Detection module, specifically related to the next logging pattern:

```
wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: Corruption: IO error: No such file or directory
```
or

```
2024/06/14 13:13:43 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: Corruption: IO error: No such file or directory: While open a file for random read: queue/indexer/wazuh-states-vulnerabilities-siem/000113.ldb: No such file or directory in file queue/indexer/wazuh-states-vulnerabilities-siem/MANIFEST-000127
```

More information will be requested from the affected users. @sebasfalcone points to a probable lack of disk space

**Comment by rodolfoarces** [comment]
Comments on the issue from the user:

Regarding disk usage:

`/dev/sda2        91G   42G   45G  49% /`

The user restored a working environment only by renaming the directory and letting Wazuh recreate it:

`mv queue/indexer/wazuh-states-vulnerabilities-siem queue/indexer/wazuh-states-vulnerabilities-siem.bak`

[more info](https://wazuh.slack.com/archives/C0A933R8E/p1718363733719159)

**Comment by sebasfalcone** [comment]
## Extra
Let's investigate the possibility of making the DB logging more verbose

**Comment by pereyra-m** [comment]
## Update

I begin to work in the issue.
The first step is to reproduce the issue and research about the error message.

**Comment by fernandogont** [comment]
FYI, after working quite a bit on the migration to 4.8.0-1, I'm experiencing the same issue.

**Comment by pereyra-m** [comment]
Hello @fernandogont 

Sorry to hear that, but could you please share all the possible details of your environment?
OS, agents, setup, configuration, etc.
It'd be specially useful a copy of the `queue/indexer` folder in the same state it was when it failed.

**Comment by pereyra-m** [comment]
## Update

I created a test environment, with a v4.8.0 manager and almost 200 Docker agents, and added extra debugging details to Rocks DB queues and DBs.
I forced a re-scan of all agents by turning on/off the module, and applied random restarts and process kills in the middle of the scan.

The issue wasn't reproduced naturally.

The only way I was able to force it was by manually removing an `.sst` file from the `queue/indexer` folder.

```
2024/06/20 03:51:41 wazuh-modulesd:vulnerability-scanner[222839] vulnerabilityScannerFacade.cpp:434 at start(): ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: Corruption: IO error: No such file or directory: While open a file for random read: queue/indexer/wazuh-states-vulnerabilities-fb659c773250/000038.ldb: No such file or directory in file queue/indexer/wazuh-states-vulnerabilities-fb659c773250/MANIFEST-000043

```

More time is required to reproduce the issue and find the root cause.

**Comment by Dwordcito** [comment]
@pereyra-m could you investigate around https://github.com/facebook/rocksdb/blob/efba8f5b2730b3fe8f92999cf9416feff3f85cb8/include/rocksdb/db.h#L2160

The agent is probably closing in the middle of a flush or compression, which have separate threads for this.

Possibly the closure is forced by some graceful shutdown problem.


Check rocksdb test:
https://github.com/facebook/rocksdb/blob/efba8f5b2730b3fe8f92999cf9416feff3f85cb8/db/corruption_test.cc

**Comment by fernandogont** [comment]
@pereyra-m : just in case this is of use, this is how I solved the issue:

1. Stop the manager
2. remove the /var/ossec/queue/indexer/wazuh-states-vulnerabilities-siem/ folder
3.  Start the manager

this solved the RocksDB errors.

Then, I know how these errors:
```
2024/06/20 04:50:21 indexer-connector[282936] indexerConnector.cpp:482 at operator()(): WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-siem', retrying until the connection is successful.
2024/06/20 04:50:23 indexer-connector[282936] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-siem': SSL peer certificate or SSH remote key was not OK. Retrying in 4 seconds.
2024/06/20 04:50:27 indexer-connector[282936] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-siem': SSL peer certificate or SSH remote key was not OK. Retrying in 8 seconds.
2024/06/20 04:50:35 indexer-connector[282936] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-siem': SSL peer certificate or SSH remote key was not OK. Retrying in 16 seconds.
2024/06/20 04:50:51 indexer-connector[282936] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-siem': SSL peer certificate or SSH remote key was not OK. Retrying in 32 seconds.
```

This seemed to indicate an issue with the "client certificate" being sent to wazuh-indexer. I couldn't figure out why... particularly when this command:

```
# curl  --cacert /etc/filebeat/certs/root-ca.pem --cert /etc/filebeat/certs/wazuh-server.pem --key /etc/filebeat/certs/wazuh-server-key.pem -X GET "https://SERVER:9200/_cluster/health"  -u USER:PASS
{"cluster_name":"wazuh-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":256,"active_shards":256,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":31,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":89.19860627177701}
```
**was successful**.

So I ended up trying this: I edited the <indexer> tag in /var/ossec/etc/ossec.conf as follows:
```
  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://SERVER:9200</host>
    </hosts>
  </indexer>
```

My rationale was that there was an issue with the certificate that was configured in the <indexer> tag. However, I'm not sure why one would need to specify a certificate here. (hence I removed all the SSL information). an this solved the problem for me.

**Comment by pereyra-m** [comment]
Hi again @fernandogont 

Thank you for sharing the steps you followed.
The module will re-create any deleted folder, but manually removing files can cause data loss. In this case for example, the `queue/indexer` folder contains the elements that haven't yet been synced with the indexer.

Considering that there was an issue with the certificates, maybe there were many elements in the queue and it made it easier for a race condition to happen. I have included this in my tests, but I still can't reproduce the issue.

>  However, I'm not sure why one would need to specify a certificate here

The connection with the Wazuh Indexer requires the right certificates and credentials in the `wazuh-keystore`. The `indexer` module uses the same as Filebeat to index the vulnerabilities found properly.

**Comment by pereyra-m** [comment]
## Update

I've been unable to reproduce the issue, even using similar conditions to the ones reported by the users and many Docker agents. But it's clear that the current implementation can't recover itself from failure and isn't enough verbose to help in the debugging process.

I've been investigating around the RocksDB logging options, and our current settings don't give us enough details in case of failure. I propose updating them as follows (considering that we have to change simultaneously `rocksDBWrapper.hpp` and `rocksDBQueue.hpp`).


<details><summary>Details</summary>
<p>

```c++
            // Setting INFO level for the info log. We'll have up to 10 files of 10MB each.
            options.info_log_level = rocksdb::InfoLogLevel::INFO_LEVEL;
            options.keep_log_file_num = 10;
            options.max_log_file_size = 10 * 1024 * 1024;
            options.recycle_log_file_num = 10;
```

</p>
</details> 

Also, I've made some tests with the `rocksdb::RepairDB()` method.
When I manually remove a `.sst` file from the folder, the system can recover. The downside is that according to the logs, this operation isn't completely safe

<details><summary>Details</summary>
<p>

```
2024/06/26-01:19:39.994567 140080303822400 [db/version_set.cc:5876] Recovered from manifest file:queue/indexer/wazuh-states-vulnerabilities-fb659c773250/MANIFEST-000001 succeeded,manifest_file_number is 1, next_file_number is 3, last_sequence is 0, log_number is 0,prev_log_number is 0,max_column_family is 0,min_log_number_to_keep is 0
2024/06/26-01:19:39.994577 140080303822400 [db/version_set.cc:5891] Column family [default] (ID 0), log number is 0
2024/06/26-01:19:39.994653 140080303822400 [WARN] [table/block_based/block_based_table_reader.cc:837] Tail prefetch size 1324 is calculated based on TailPrefetchStats
2024/06/26-01:19:39.994746 140080303822400 [WARN] [table/block_based/block_based_table_reader.cc:715] At least one SST file opened without unique ID to verify: 76.sst
2024/06/26-01:19:39.995185 140080303822400 [db/repair.cc:619] Table #76: 7025 entries OK
2024/06/26-01:19:40.004229 140080303822400 [db/repair.cc:473] Log #104: 760 ops saved to Table #108 OK
2024/06/26-01:19:40.004287 140080303822400 [db/repair.cc:766] Archiving queue/indexer/wazuh-states-vulnerabilities-fb659c773250/000104.log: OK
2024/06/26-01:19:40.004305 140080303822400 [WARN] [table/block_based/block_based_table_reader.cc:837] Tail prefetch size 1324 is calculated based on TailPrefetchStats
2024/06/26-01:19:40.005994 140080303822400 [db/repair.cc:619] Table #108: 760 entries OK
2024/06/26-01:19:40.006072 140080303822400 [WARN] [db/version_set.cc:4545] [default]CF's epoch numbers are inferred based on seqno
2024/06/26-01:19:40.006172 140080303822400 [db/version_set.cc:5346] Creating manifest 109
2024/06/26-01:19:40.008799 140080303822400 [WARN] [db/repair.cc:234] **** Repaired rocksdb queue/indexer/wazuh-states-vulnerabilities-fb659c773250; recovered 2 files; 1568021 bytes. Some data may have been lost. ****

```

</p>
</details> 

And we'd have to update the wrappers to properly log this type of situations.

So we must decide what behavior we wan't, I propose some alternatives @Dwordcito @sebasfalcone 

### We don't repair the DB

If we aren't willing to accept that after a DB corruption the repair process loses some data, we can leave the current behavior as it is: a corrupted DB can't be opened, and vulnerability detector can't start. Then, the users should disable the module, remove the folders, and enable it again to re-scan all agents to make sure the vulnerability detector's data is consistent.

This approach could include some automated way to perform this full cleanup/reset, although if this happens too often then the module would require too many interventions from the user.

### We repair the DB silently

The fastest approach is to add a similar block to this one when the DB is opened, that tries to recover the DB every time it fails to be opened

<details><summary>Details</summary>
<p>

```c++
        if (const auto status = rocksdb::DB::Open(options, connectorName, &db); !status.ok())
        {
            // If the database is corrupted, try to repair it.
            if (const auto repairStatus {rocksdb::RepairDB(connectorName, options)}; !repairStatus.ok())
            {
                throw std::runtime_error("Failed to repair RocksDB database. Reason: " +
                                         std::string {repairStatus.getState()});
            }

            // Try to open the database again.
            if (const auto reOpenStatus {rocksdb::DB::Open(options, connectorName, &db)}; !reOpenStatus.ok())
            {
                throw std::runtime_error("Failed to re-open RocksDB database." + std::string {" Code: "} +
                                         std::to_string(reOpenStatus.code()) + std::string {". Reason: "} +
                                         std::string {reOpenStatus.getState()});
            }
        }
```


</p>
</details> 

This approach adds a self recovery mechanism that allows any DB used by the module to repair itself and continue automatically. It'll only throw an exception if the repair process fails, or if fails to re-open the DB (leaving the module again in an unrecoverable state).

But we could silently introduce data errors if the recovery process can't restore all entries.
It's possible to update the wrappers and include warnings in these cases, but it's still required to define what should the user do in each case.

**Comment by sebasfalcone** [comment]
## Continuation
@pereyra-m Amazing analysis and report!

We are going to continue with the implementation of the repair mechanism:
- We are going to log a warning message telling the mechanism was in place and that information may be lost during the repair

Also, we will increase the logging level for rocksDB to have better forensic when a user reports this kind of issues

**Comment by pereyra-m** [comment]
## Update

There is a draft implementation at #24333.

Two different ways to apply the same behavior had to be implemented because some utils don't use the RocksDB Wrapper. 
The repair method is called only in case of corruption, and after a successful recovery, a warning message is printed.
All the required tests still have to be implemented.

**Comment by pereyra-m** [comment]
## Update

The PR #24333 has been updated with UT.
Also, a more robust error code handling was added to the implementation. 

Like the issue was moved to another release, a rebase is required and still pending.

**Comment by pereyra-m** [comment]
## Update

I change the base branch, rebase the development branch, perform the manual tests and add the rest of missing UT.

**Comment by sebasfalcone** [comment]
## ETA delayed
Reviewing changes, ETA delayed due to higher priority issues that delayed the review

**Comment by pereyra-m** [comment]
## Update

I upload some review changes.

**Comment by pereyra-m** [comment]
## Update

I implement some changes requested in the review.

**Comment by Dwordcito** [comment]
ETA changed, pending final review.

**Comment by pereyra-m** [comment]
## Update

I perform a rework of the implementation after the PR review.

**Comment by pereyra-m** [comment]
## Update

I keep working in the issue. 
The utils lack of logging, so it's required to add that capability. Some details of this requirement of the issue will be addressed in another issue.
I'm also moving the repair mechanism to the Rocksdb Wrapper default constructor.

**Comment by sebasfalcone** [comment]
## ETA delayed
Due to changes in the requirements and prioritization on other issues, the ETA was delayed

**Comment by pereyra-m** [comment]
## Update

PR rebase, changes rollback, review changes.

**Comment by nobe80** [comment]
Hi togehter,

just upgrade to Wazuh v4.9.1 and have still the same issue:
wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: While opening a file for sequentially reading: queue/vd/event

I dont get fresh data in Vulnerability Tab

regards

**Comment by pereyra-m** [comment]
Hi @nobe80 

The repair feature will be released in v4.10.0.
Until then, could you please create a thread/issue with details about the error and environment? We can share a workaround to refresh the module. This is a closed development issue.

Regards.

**Comment by KmdKeen** [comment]
Hey Guys,

we're in the same boat... upgraded from 4.8.0 to 4.9.0/4.9.1 and the same errors in the logs with some very old findings in the vulnerability inventory. Is there any workaround or step to cleanup the database to have a fresh scan/results? 

Regards!

**Comment by pereyra-m** [comment]
Hi @KmdKeen 

As I commented above, creating another issue with all the information and example logs helps us to provide the right workaround. In general, it consists of disabling the module, removing the local DBs, deleting the index, and re-enabling the module again; but it's important to analyze each case so the module doesn't fall into an inconsistent state.

Regards.

**Comment by dn65** [comment]
Hey @pereyra-m,

I am experiencing the exact same problem. I updated to 4.9 without ever using or even activating the module beforehand.
Now when I do activate it I am getting the known error regarding MANIFEST-000005:

`wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: While opening a file for sequentially reading: queue/vd/event/MANIFEST-000005: No such file or directory.`

I have a 2 machine Cluster set-up, the indexer runs on both machines. I tried renaming every folder within
`/var/ossec/queue/indexer`
 on both machines, then restarting the wazuh-manager with vulnerability-detection turned off and on again.

When turning it back on again the indexer initializes correctly
`indexer-connector: INFO: IndexerConnector initialized successfully for index: wazuh-states-vulnerabilities-wazuh_cluster.`

The vulnerability-scanner creates the db folder, then throws the aformenetioned error regarding MANIFEST-000005. 
I have no collected vulnerability data that could be lost, since the component never ran. Is there a way to fully reset it?

Best regards

**Comment by sebasfalcone** [comment]
## Response to the community
This is for all users experiencing errors related to this fix. We encourage everyone to open a new request in one of our [**community channels**](https://wazuh.com/community/)

> [!IMPORTANT]
> This is a development issue and we will not address inquiries in it
