### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Update allocator module

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24158]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**DevOps**
- [x] No central components: Deploy an All In One (in our featured OS, probably Amazon Linux) and allocate an accessible machine with the new OS to test the agent. This is the first step for everything else.
- [x] Add support in the allocator.
- [ ] ~~Adapt Puppet.~~
- [ ] ~~Adapt Ansible.~~
- [ ] ~~Update AMI, OVA, or Docker images if needed.~~

**Comment by davidcr01** [comment]
# Update Report

- Currently upgrading a VM in the macStadium Intel to macOS Sequoia.
- I could not upgrade the ARM VM because of this: https://kb.parallels.com/128867?clientId=1523989290.1718813093&sessionId=1718813092

> [!WARNING]
> 7. Apple ID: It is currently impossible to sign in with your Apple ID in a macOS Arm VM.

**Comment by davidcr01** [comment]
# Update Report

## ARM

I could download the macOS 15 Beta using the folliwng commands:
```console
sudo defaults write com.apple.MobileAsset MobileAssetAssetAudience -string 77c3bd36-d384-44e8-b550-05122d7da438
sudo defaults write com.apple.MobileAsset MobileAssetServerURL-com.apple.MobileAsset.SoftwareUpdate -string "https://swscan.apple.com/content/catalogs/others/index-14seed-14-13-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz"
sudo killall -HUP mobileassetd
sudo killall -HUP betaenrollmentd
open "x-apple.systempreferences:com.apple.Software-Update-Settings.extension"
```
Then, in the VM, the Software Updates window pops up, and the Sequoia Beta will be available.

This approach was reported here: https://github.com/insidegui/VirtualBuddy/discussions/194#discussioncomment-9731813

After some failed attempts (the VM didn't have enough space and I could not resize the virtual disk), the VM upgraded successfully:

```console
sh-3.2# vagrant ssh macos-14
Last login: Fri Jun 21 04:30:14 2024
vagrant@macos-15 ~ % sw_vers
ProductName:            macOS
ProductVersion:         15.0
BuildVersion:           24A5264n
vagrant@macos-15 ~ % 
```
I changed the hostname in the Settings inside the VM and via terminal:
- In the settings app: https://support.apple.com/es-es/guide/mac-help/mchlp2322/mac#:~:text=local.-,On%20your%20Mac%2C%20choose%20Apple%20menu%20%3E%20System%20Settings%2C%20click,may%20need%20to%20scroll%20down.)&text=Click%20Edit%20in%20the%20%E2%80%9CLocal,Use%20dynamic%20global%20hostname%E2%80%9D%20option.
- Using the `sudo scutil --set HostName macos-15`, and `dscacheutil -flushcache` commands, and rebooting the VM to apply the changes.

**Comment by davidcr01** [comment]
# Update Report

After several attempts, the VM created with the Vagrant box is not working:
![image](https://github.com/wazuh/wazuh/assets/72193239/5b9a73b3-24b1-4117-857f-75d0b5385814)

**Comment by davidcr01** [comment]
# Update Report

The previous error was apparently fixed by creating the `.box` with the base VM powered off. This is the first time I've seen this, so I'm not sure if this was the problem because I have created macOS Vagrant boxes before with the VM running.

Despite that, I could create the Vagrant box successfully and the `vagrant up` does not generate the `Authentication error` warning. This was fixed by replacing the `vagrant_private_key` with the `/private/var/root/.ssh/vagrant_rsa` private key, and by executing the following command (copying the public key to the VM): `ssh-copy-id -i /private/var/root/.ssh/vagrant_rsa vagrant@<VM_IP>`.

Then, the macOS 15 VM can be launched correctly:
```console
sh-3.2# vagrant --name="macos-testing-15" up macos-15Bringing machine 'macos-15' up with 'parallels' provider...
==> macos-15: Registering VM image from the base box 'macos-15'...
==> macos-15: Creating new virtual machine as a full clone of the box image...
==> macos-15: Unregistering the box VM image...
==> macos-15: Setting the default configuration for VM...
==> macos-15: Setting the name of the VM: macos-testing-15
==> macos-15: Preparing network interfaces based on configuration...
    macos-15: Adapter 0: shared
    macos-15: Adapter 1: hostonly
    macos-15: Adapter 2: bridged
==> macos-15: Clearing any previously set network interfaces...
==> macos-15: Running 'pre-boot' VM customizations...
==> macos-15: Booting VM...
==> macos-15: Waiting for machine to boot. This may take a few minutes...
    macos-15: SSH address: 192.168.64.10:22
    macos-15: SSH username: vagrant
    macos-15: SSH auth method: private key
==> macos-15: Machine booted and ready!
==> macos-15: Checking for Parallels Tools installed on the VM...
==> macos-15: Setting hostname...
==> macos-15: Configuring and enabling network interfaces...
sh-3.2# vagrant ssh macos-15
Last login: Tue Jun 25 07:52:50 2024
vagrant@macos-15 ~ % sw_vers    
ProductName:            macOS
ProductVersion:         15.0
BuildVersion:           24A5264n
vagrant@macos-15 ~ % 
```

The box is imported as `macos-15` in the `root` user. The generated box is placed in `/Users/jenkins/vagrant_boxes/macos15.box`.

**Comment by davidcr01** [comment]
The Sequoia ARM and the AMI were provisioned.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by c-bordon** [comment]
## Update report

VMs provisioned, connection data shared privately with @jotacarma90

**Comment by davidcr01** [comment]
Moved to 4.9.1-RC2

**Comment by mjcr99** [comment]
Hi team, 
[macOS Sequoia 15.1](https://developer.apple.com/documentation/macos-release-notes/macos-15_1-release-notes) has been released, we should consider updating the image to the new one when possible.

**Comment by c-bordon** [comment]
@mjcr99 We need a new issue for update the AMIs and the Vagrant box to macOS sequoia 15.1
