### ISSUE TITLE
Upgrade 4.7 to 4.8 - Vulnerability Detection/IndexerConnector unable to initialize wazuh-states-vulnerabilities-* indexes

### ISSUE THREAD

**Issue by pf-jaimie-livingston** [wazuh/wazuh#24155]
|Wazuh version|Component|Install type|Install method|Platform|
|4.8|Vulnerability Detection/IndexerConnector|Manager|Upgrade,RPM|RockyLinux|

Environment:
Clustered, 1 Manager, 3 Workers, 5 Indexers, 2 Dashboards

_This is more of a "we found this" than a "please fix this"._

Post upgrade from 4.7 to 4.8, the Vulnerability Detection indexes and dashboards would not initialize.
The error appearing in the ossec.log is:
`indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-central-logger', retrying until the connection is successful.`

We used [this documentation](https://documentation.wazuh.com/4.8/user-manual/capabilities/vulnerability-detection/configuring-scans.html) reference for the changes to the vulnerability detection module from v4.7 to v4.8. This issue is generally well reported and has been addressed in several other issue reports.
For example: 
* https://github.com/wazuh/wazuh/issues/23092
* https://github.com/wazuh/wazuh/issues/24074

We would like to add the following:

For the distributed cluster we have in production, we found that having more than one `ca` property in the `certificate_authorities` section of the `indexer` block was the ultimate cause of our issue. 

We were unable to determine whether or not multiple SSL `ca` properties are allowed in the ossec.conf `indexer` block, but ultimately, using a single `ca` property that points to a PEM formatted ca chain file resolved the issue for our use case.

Here is the failing `ssl` section from the `indexer` block of `ossec.conf`. Note the two `ca` properties.

```
<ssl>
      <certificate_authorities>
        <ca>/etc/pki/tls/private/private-root-ca.pem</ca>
        <ca>/etc/pki/tls/private/private-subca-crt.pem</ca>
      </certificate_authorities>
      <certificate>/etc/pki/tls/private/host141-crt.pem</certificate>
      <key>/etc/pki/tls/private/host141-key.pem</key>
</ssl>
```

Here is the complete `indexer` block from `ossec.conf` that works, with a single `ca` property referencing the ca chain file:

```
 <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://10.1.2.5:9200</host>
      <host>https://10.1.2.6:9200</host>
      <host>https://10.1.2.7:9200</host>
      <host>https://10.1.2.8:9200</host>
      <host>https://10.1.2.9:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/pki/tls/private/private-ca-chain.pem</ca>
      </certificate_authorities>
      <certificate>/etc/pki/tls/private/hostlocal-crt.pem</certificate>
      <key>/etc/pki/tls/private/hostlocal-key.pem</key>
    </ssl>
  </indexer>

```

YMMV.
Thank you for your hard work.

Cheers,
Jaimie Livingston

**Comment by MiguelazoDS** [comment]
Hi @pf-jaimie-livingston, 

Thanks for the review!, indeed the configuration only works for a single CA

https://github.com/wazuh/wazuh/blob/70c40f2006adf55b563c378d8d6b0eaafafc00d0/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L45

But I'll discuss this with the team because there were some thoughts about this distributed environment case. 

I'll be back once I have new information, thanks again. Regards!

**Comment by Dwordcito** [comment]
Hi @pf-jaimie-livingston 

How do you have filebeat configured?

**Comment by pf-jaimie-livingston** [comment]
Filebeat is provisioned pretty simply.
Here is the basic config from the Wazuh Manager.


<pre>
# Wazuh Manager + Filebeat
# /etc/filebeat/filebeat.yml
################################################################################

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false

# Send events directly to Wazuh indexer
output.elasticsearch:
  hosts:
  - 10.1.2.5:9200
  - 10.1.2.6:9200
  - 10.1.2.7:9200
  - 10.1.2.8:9200
  - 10.1.2.9:9200

  username: admin
  password: "ThisIsMySecret"
  protocol: https
  ssl.certificate_authorities:
    - "/etc/pki/tls/private/private-root-ca.pem"
    - "/etc/pki/tls/private/private-subca-crt.pem"
  ssl.certificate: "/etc/pki/tls/private/host141-crt.pem"
  ssl.key: "/etc/pki/tls/private/host141-key.pem"

logging.metrics.enabled: false

seccomp:
  default_action: allow
  syscalls:
  - action: allow
    names:
    - rseq
</pre>

Cheers,

Jaimie Livingston

**Comment by sebasfalcone** [comment]
This issue will be addressed at:
- https://github.com/wazuh/wazuh/issues/24295

**Comment by sebasfalcone** [comment]
We will close this thread, as it will be tracked by the expressed issue
