### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Test agent package

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24161]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**Agent**
Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.
Result code:
:green_circle: Completed: Test finished with success.
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.
- **Requested checks by tier:**

| | Tier 1 | Tier 2 | Tier 3 | Result - x86_64 | ARM |
|-|-|-|-|-|-|
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: |🟢|🟢|
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | 🟢|🟢|
| **Log collection - Command execution** | :white_circle: | :white_circle: | :white_circle: | 🟢|🟢|
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | 🟢| 🟢|
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | 🟡|🟡|
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | 🟡|🟡|
| **SCA** | :white_circle: | :white_circle: | :black_circle: | 🟡|🟡|
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | 🟢|🟢|
| **Active response** | :white_circle: | :white_circle: | :black_circle: | 🟢|🟢|
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | 🟢|🟡|
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: | 🟢|🟢|
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | 🟢|🟢|

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by MarcelKemp** [comment]
# Testing - macOS 15 x86_64

## 🟢 Agent package install (enrollment and connectivity with the manager)

<details>
<summary>OS information</summary>

```console
sh-3.2# uname -a
Darwin macos-15 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:30 PDT 2024; root:xnu-11215.1.10~2/RELEASE_X86_64 x86_64
sh-3.2# cat /System/Library/CoreServices/SystemVersion.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildID</key>
	<string>A2BB314E-6BC0-11EF-9288-D6EF2EB7C8EA</string>
	<key>ProductBuildVersion</key>
	<string>24A335</string>
	<key>ProductCopyright</key>
	<string>1983-2024 Apple Inc.</string>
	<key>ProductName</key>
	<string>macOS</string>
	<key>ProductUserVisibleVersion</key>
	<string>15.0</string>
	<key>ProductVersion</key>
	<string>15.0</string>
	<key>iOSSupportVersion</key>
	<string>18.0</string>
</dict>
</plist>
```

</details>

<details>
<summary>Package installation</summary>

```bash
echo "WAZUH_MANAGER='172.X.X.X'" > /tmp/wazuh_envs && installer -pkg wazuh-agent-4.9.0-1.intel64.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```
</details>

<details>
<summary>Agent enrollment and connection</summary>

```bash
Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh-server (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: macos-15, IP: any, Active
   ID: 002, Name: macos15arm, IP: any, Active
```
</details>

## 🟢 Log files

<details>
<summary>Configuration</summary>

```xml
  <localfile>
    <location>/Users/vagrant/test/testing.log</location>
    <log_format>syslog</log_format>
  </localfile>
```

</details>

<details>
<summary>Test</summary>

File `testing.log`:
```
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928

```

</details>

<details>
<summary>Result</summary>

```log
** Alert 1726758493.152362: - syslog,sshd,authentication_failed,gdpr_IV_35.7.d,gdpr_IV_32.2,gpg13_7.1,hipaa_164.312.b,invalid_login,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_AU.6,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_10.6.1,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,
2024 Sep 19 15:08:13 (macos-15) any->/Users/vagrant/test/testing.log
Rule: 5710 (level 5) -> 'sshd: Attempt to login using a non-existent user'
Src IP: 18.18.18.18
Src Port: 48928
Oct 15 21:07:00 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928
```

</details>

## 🟢 System events

<details>
<summary>Configuration</summary>

> https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/configuration.html#collecting-macos-uls-logs-with-the-wazuh-agent

```xml
<localfile>
  <location>macos</location>
  <log_format>macos</log_format>
  <query type="trace,log,activity" level="info">(process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd")</query>
</localfile>
```

</details>

<details>
<summary>Test</summary>

```sh
$ sudo su
```

</details>

<details>
<summary>Result</summary>

```log
** Alert 1726748144.127892: - syslog,sudo,
2024 Sep 19 12:15:44 (macos-15) any->macos
Rule: 5403 (level 4) -> 'First time user executed sudo.'
2024-09-19 05:15:43.614719-0700  localhost sudo[10869]: (libsystem_info.dylib) Created Activity ID: 0x2bed0, Description: Retrieve User by ID
```

</details>

## Command execution

<details>
<summary>Test</summary>

```sh
$ sudo su
```

</details>

<details>
<summary>Result</summary>

```log

```

</details>

## Command monitoring

<details>
<summary>Configuration</summary>

```xml
  <localfile>
    <log_format>full_command</log_format>
    <command>ps auxw | grep -i [A]ppleCredentialManager</command>
    <alias>check_apple_credential_manager_status</alias>
    <frequency>120</frequency>
  </localfile>
```

</details>

<details>
<summary>Result</summary>

```log
** Alert 1726759782.166737: - process_monitor,
2024 Sep 19 15:29:42 (macos-15) any->check_apple_credential_manager_status
Rule: 100014 (level 6) -> 'Apple Credential Manager is running.'
ossec: output: 'check_apple_credential_manager_status':
root               133   0,0  0,1 33655768   2696   ??  Ss   mié06AM   0:00.05 /System/Library/PrivateFrameworks/AppleCredentialManager.framework/AppleCredentialManagerDaemon
```

</details>


## SCA support

<details>
<summary>Manager log:</summary>

</details>

### FIM scheduled

<details>
<summary>Agent configuration</summary>


</details>

<details>
<summary>Test</summary>

</details>

<details>
<summary>Result</summary>

</details>




## Active response

<details>
<summary>Manager configuration:</summary>


</details>

<details>
<summary>Result:</summary>


</details>






## Inventory

<details>
<summary>Script to get the first 5 rows of each table</summary>

```bash
#!/bin/bash

db_path="/var/ossec/queue/syscollector/db/local.db"

for table in $(sqlite3 /var/ossec/queue/syscollector/db/local.db ".tables"); do
  TMP_FILE=$(mktemp)

  # Execute the query and store output in temporary file
  sqlite3 /var/ossec/queue/syscollector/db/local.db ".headers on" "select * from $table"|head -n5 > $TMP_FILE

  # Check if query execution was successful
  if [[ $? -ne 0 ]]; then
    echo "Error executing query!"
    exit 1
  fi
  
  # Build markdown table header
  HEADER_ROW=$(head -n 1 "$TMP_FILE" | tr ',' '\t')
  echo "| ${HEADER_ROW// /|} |"
  max_col=$(tr -cd '|' <<< "$HEADER_ROW" | wc -c)
  for i in $(seq 0 $max_col); do  echo -n "|---"; done ; echo "|"
  
  # Build markdown table body with separators
  tail -n +2 "$TMP_FILE" | tr ',' '\t' | while IFS= read -r line; do
    echo "| $line |"
  done
  
  # Clean up temporary file
  rm "$TMP_FILE"
  
  echo "Markdown table generated! $table"
done
```
</details>


<details>
<summary>Inventory</summary>

</details>

**Comment by jotacarma90** [comment]
LGTM

**Comment by mjcr99** [comment]
LGTM
