### ISSUE TITLE
Support new OSs - macOS Sequoia 15 - Add SCA content

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24160]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/25665 | https://github.com/wazuh/wazuh/issues/24146 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**ThreatIntel**
- [ ] Define a plan to support the new OS, particularly with regard to SCA policies. If there's no official CIS policy for that OS version, we either use an existing draft or we adapt a previous version.

**Comment by MarcelKemp** [comment]
Due to the change in the process, I am closing this issue as not planned because it is a pre-release version.

**Comment by jotacarma90** [comment]
Reopened due to release date for macOS 15 Sequoia is here:
https://9to5mac.com/2024/09/09/macos-sequoia-release-date/

**Comment by jk-olaoluwa** [comment]
## Update 19/09/2024

 - Commenced creation of SCA file from CIS Draft  document - https://github.com/wazuh/wazuh/pull/25792/commits/47e6db28fbabb4472dda84a433f66e7cea3116a5

**Comment by jk-olaoluwa** [comment]
## Update 20/09/2024

 - Commenced creation of SCA file from CIS Draft  document - https://github.com/wazuh/wazuh/pull/25792/commits/47e6db28fbabb4472dda84a433f66e7cea3116a5

**Comment by jk-olaoluwa** [comment]
## Update 25/09/2024

 - CIS SCA for macOS 15 - Sections 2.3.1.1 - 2.3.3.12 https://github.com/wazuh/wazuh/commit/b66d33539b1652d1cc3106f5d5792d3e0079d370

**Comment by jk-olaoluwa** [comment]
## Update 26/09/2024

 - CIS SCA for macOS 15 - Sections 2.3.4.1 - 2.6.1.1 https://github.com/wazuh/wazuh/commit/56e364d41cd1e930726b8d97168ae746b727f5fb

**Comment by jk-olaoluwa** [comment]
## Update 27/09/2024

 - CIS SCA for macOS 15 - Sections 2.6.1.2 - 2.9.3

**Comment by jk-olaoluwa** [comment]
## Update 28/09/2024

 - CIS SCA for macOS 15 - Sections 2.10.1 - 2.19.1 - https://github.com/wazuh/wazuh/commit/f97a89c0cf9cedb6ece86869c1964dd91f79bf28

**Comment by jk-olaoluwa** [comment]
## Update 02/10/2024

 - CIS SCA for macOS 15 - Sections 3.1 - 4.3 - https://github.com/wazuh/wazuh/commit/abb67894bd302249e292bf7aacec26e372076248

**Comment by jk-olaoluwa** [comment]
## Update 03/10/2024

 - CIS SCA for macOS 15 - Sections 5.1.1 - 6.4.1 - https://github.com/wazuh/wazuh/commit/9d585897ffa45b9f398a9ad767a07265a16c8d8c

**Comment by Johnng007** [comment]
# MacOS 15 Sequoia SCA testing report

## Agent running on macOS 14 SCA

### Endpoint spec
<details>
<summary>CPU</summary>

````
sh-3.2# sysctl -a | grep machdep.cpu
machdep.cpu.mwait.linesize_min: 4096
machdep.cpu.mwait.linesize_max: 4096
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 544
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 0
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 0
machdep.cpu.thermal.core_power_limits: 1
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 1
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.xsave.extended_state: 7 832 832 0
machdep.cpu.xsave.extended_state1: 3 832 0 0
machdep.cpu.arch_perf.version: 0
machdep.cpu.arch_perf.number: 0
machdep.cpu.arch_perf.width: 0
machdep.cpu.arch_perf.events_number: 0
machdep.cpu.arch_perf.events: 127
machdep.cpu.arch_perf.fixed_number: 0
machdep.cpu.arch_perf.fixed_width: 0
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 4
machdep.cpu.cache.size: 256
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.small_level1: 64
machdep.cpu.address_bits.physical: 36
machdep.cpu.address_bits.virtual: 48
machdep.cpu.tsc_ccc.numerator: 266
machdep.cpu.tsc_ccc.denominator: 2
machdep.cpu.max_basic: 22
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
machdep.cpu.family: 6
machdep.cpu.model: 158
machdep.cpu.extmodel: 9
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 10
machdep.cpu.feature_bits: 18445110247204584447
machdep.cpu.leaf7_feature_bits: 9177003 0
machdep.cpu.extfeature_bits: 1241917688064
machdep.cpu.signature: 591594
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH MMX FXSR SSE SSE2 SS HTT SSE3 PCLMULQDQ MON SSSE3 FMA CX16 SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES VMM PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 SMEP BMI2 ERMS INVPCID RDSEED ADX CLFSOPT
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI
machdep.cpu.logical_per_package: 2
machdep.cpu.cores_per_package: 2
machdep.cpu.microcode_version: 0
machdep.cpu.processor_flag: 0
machdep.cpu.core_count: 2
machdep.cpu.thread_count: 2

````

</details>

<details>
<summary>RAM</summary>

````
sh-3.2# sysctl hw.memsize
hw.memsize: 4294967296
````

</details>

<details>
<summary>Disk</summary>

````
sh-3.2# df -h
Filesystem                                                    Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk1s5s1                                                95Gi   9.9Gi    78Gi    12%    407k  818M    0%   /
devfs                                                        189Ki   189Ki     0Bi   100%     654     0  100%   /dev
/dev/disk1s2                                                  95Gi   2.2Gi    78Gi     3%    1.4k  818M    0%   /System/Volumes/Preboot
/dev/disk1s4                                                  95Gi   1.0Mi    78Gi     1%       1  818M    0%   /System/Volumes/VM
/dev/disk1s6                                                  95Gi   2.4Mi    78Gi     1%      27  818M    0%   /System/Volumes/Update
/dev/disk1s1                                                  95Gi   3.0Gi    78Gi     4%     43k  818M    0%   /System/Volumes/Data
/dev/disk0s3                                                 161Gi   288Mi   161Gi     1%     104  4.3G    0%   /Volumes/Untitled
map auto_home                                                  0Bi     0Bi     0Bi   100%       0     0     -   /System/Volumes/Data/home
//guest:@Shared%20Folders._smb._tcp.local/Shared%20Folders   4.0Ti     0Bi   4.0Ti     0%      -2  1.1G   -0%   /Volumes/SharedFolders
````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/user-attachments/assets/33fc16de-49c9-4024-b6df-cc41acfc3cc4)

![disk_percent_plot](https://github.com/user-attachments/assets/1c6ad849-4299-46a1-8876-8eb20f986eec)

![disk_used_(mb)_plot](https://github.com/user-attachments/assets/4fd0f4e1-7af8-435f-b93c-9af430463744)

![memory_percent_plot](https://github.com/user-attachments/assets/db7dfdc3-a49f-4e91-b6d7-9e3a9c1baa7e)

![memory_used_(mb)_plot](https://github.com/user-attachments/assets/ed8fbea2-b588-403a-920f-a9e732c10f3e)

![ProcessesCPU](https://github.com/user-attachments/assets/d96a1c01-abe7-4951-8323-27b5006f4908)

![ProcessesCPU_Change_Point](https://github.com/user-attachments/assets/9bc54d81-45ba-4c4b-a694-d6502b69af55)

![ProcessesCPUlegend](https://github.com/user-attachments/assets/c91e84a5-53a0-41ba-b9ec-3a36ff834536)

![ProcessesRAM](https://github.com/user-attachments/assets/0f9a6284-d5bc-47c8-99b2-4ca95ffea92f)

![ProcessesRAM_Change_Point](https://github.com/user-attachments/assets/069abc61-01a7-4004-b203-b86bec1d4d45)

![ProcessesRAMlegend](https://github.com/user-attachments/assets/1764c622-e585-43f1-93ab-731705e1c902)

![swap_percent_plot](https://github.com/user-attachments/assets/b52ab92d-ee6c-4edb-b55d-de8636092384)

![swap_used_(mb)_plot](https://github.com/user-attachments/assets/aac42840-9a21-4cc1-9394-00f40e5ae67b)

</details>

<details>
<summary>SCA logs</summary>

````
sh-3.2# tail -f -n +1 /Library/Ossec/logs/ossec.log
2024/10/08 17:01:59 sca: INFO: Module started.
2024/10/08 17:01:59 sca: INFO: Loaded policy '/Library/Ossec/ruleset/sca/cis_apple_macOS_15.x.yml'
2024/10/08 17:01:59 sca: INFO: Starting Security Configuration Assessment scan.
2024/10/08 17:02:10 sca: INFO: Evaluation finished for policy '/Library/Ossec/ruleset/sca/cis_apple_macOS_15.x.yml'
2024/10/08 17:02:10 sca: INFO: Security Configuration Assessment scan finished. Duration: 11 seconds.

````

</details>

[metrics.zip](https://github.com/user-attachments/files/17300569/metrics.zip)



## Agent running MacOS 15 SCA

###  Endpoint spec

<details>
<summary>CPU</summary>

````
sh-3.2# sysctl -a | grep machdep.cpu
machdep.cpu.mwait.linesize_min: 4096
machdep.cpu.mwait.linesize_max: 4096
machdep.cpu.mwait.extensions: 3
machdep.cpu.mwait.sub_Cstates: 544
machdep.cpu.thermal.sensor: 1
machdep.cpu.thermal.dynamic_acceleration: 0
machdep.cpu.thermal.invariant_APIC_timer: 1
machdep.cpu.thermal.thresholds: 2
machdep.cpu.thermal.ACNT_MCNT: 0
machdep.cpu.thermal.core_power_limits: 1
machdep.cpu.thermal.fine_grain_clock_mod: 0
machdep.cpu.thermal.package_thermal_intr: 1
machdep.cpu.thermal.hardware_feedback: 0
machdep.cpu.thermal.energy_policy: 0
machdep.cpu.xsave.extended_state: 7 832 832 0
machdep.cpu.xsave.extended_state1: 3 832 0 0
machdep.cpu.arch_perf.version: 0
machdep.cpu.arch_perf.number: 0
machdep.cpu.arch_perf.width: 0
machdep.cpu.arch_perf.events_number: 0
machdep.cpu.arch_perf.events: 127
machdep.cpu.arch_perf.fixed_number: 0
machdep.cpu.arch_perf.fixed_width: 0
machdep.cpu.cache.linesize: 64
machdep.cpu.cache.L2_associativity: 4
machdep.cpu.cache.size: 256
machdep.cpu.tlb.inst.large: 8
machdep.cpu.tlb.data.small: 64
machdep.cpu.tlb.data.small_level1: 64
machdep.cpu.address_bits.physical: 36
machdep.cpu.address_bits.virtual: 48
machdep.cpu.tsc_ccc.numerator: 266
machdep.cpu.tsc_ccc.denominator: 2
machdep.cpu.max_basic: 22
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
machdep.cpu.family: 6
machdep.cpu.model: 158
machdep.cpu.extmodel: 9
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 10
machdep.cpu.feature_bits: 18445110247204584447
machdep.cpu.leaf7_feature_bits: 9177003 0
machdep.cpu.extfeature_bits: 1241917688064
machdep.cpu.signature: 591594
machdep.cpu.brand: 0
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH MMX FXSR SSE SSE2 SS HTT SSE3 PCLMULQDQ MON SSSE3 FMA CX16 SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES VMM PCID XSAVE OSXSAVE TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 SMEP BMI2 ERMS INVPCID RDSEED ADX CLFSOPT
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI
machdep.cpu.logical_per_package: 2
machdep.cpu.cores_per_package: 2
machdep.cpu.microcode_version: 0
machdep.cpu.processor_flag: 0
machdep.cpu.core_count: 2
machdep.cpu.thread_count: 2

````

</details>

<details>
<summary>RAM</summary>

````
sh-3.2# sysctl hw.memsize
hw.memsize: 4294967296
````

</details>

<details>
<summary>Disk</summary>

````
sh-3.2# df -h
Filesystem                                                    Size    Used   Avail Capacity iused ifree %iused  Mounted on
/dev/disk1s5s1                                                95Gi   9.9Gi    78Gi    12%    407k  818M    0%   /
devfs                                                        189Ki   189Ki     0Bi   100%     654     0  100%   /dev
/dev/disk1s2                                                  95Gi   2.2Gi    78Gi     3%    1.4k  818M    0%   /System/Volumes/Preboot
/dev/disk1s4                                                  95Gi   1.0Mi    78Gi     1%       1  818M    0%   /System/Volumes/VM
/dev/disk1s6                                                  95Gi   2.4Mi    78Gi     1%      27  818M    0%   /System/Volumes/Update
/dev/disk1s1                                                  95Gi   3.0Gi    78Gi     4%     43k  818M    0%   /System/Volumes/Data
/dev/disk0s3                                                 161Gi   288Mi   161Gi     1%     104  4.3G    0%   /Volumes/Untitled
map auto_home                                                  0Bi     0Bi     0Bi   100%       0     0     -   /System/Volumes/Data/home
//guest:@Shared%20Folders._smb._tcp.local/Shared%20Folders   4.0Ti     0Bi   4.0Ti     0%      -2  1.1G   -0%   /Volumes/SharedFolders
````
</details>


### Footprint test results
<details>
<summary>Metrics</summary>

![cpu_percent_plot](https://github.com/user-attachments/assets/f6d16f30-8124-4c1b-ad32-af404709f691)
![disk_percent_plot](https://github.com/user-attachments/assets/d2a43589-5d33-48f6-8324-ee215edda0d5)
![disk_used_(mb)_plot](https://github.com/user-attachments/assets/58921a6a-8334-4f8e-b58e-578a305a18e2)
![memory_percent_plot](https://github.com/user-attachments/assets/04b4c08c-4a65-4017-bccc-a53d7112fd54)
![memory_used_(mb)_plot](https://github.com/user-attachments/assets/1cdffd81-eb94-4c5f-bba2-560cc902f688)
![ProcessesCPU](https://github.com/user-attachments/assets/cd985eb3-4dda-4f1e-b424-5aaed4acba8a)
![ProcessesCPU_Change_Point](https://github.com/user-attachments/assets/db43c67e-ab19-42c5-8e9b-67718638e393)
![ProcessesCPUlegend](https://github.com/user-attachments/assets/5e682252-90a9-4335-af65-b455fcd8d845)
![ProcessesRAM](https://github.com/user-attachments/assets/029318d7-540a-44de-a3b6-77744c649e8f)
![ProcessesRAM_Change_Point](https://github.com/user-attachments/assets/fd9a859c-9a55-419c-8e6c-1e8f0f290496)
![ProcessesRAMlegend](https://github.com/user-attachments/assets/d1ebabdd-ffb7-48c0-8291-697b9a9bccaa)
![swap_percent_plot](https://github.com/user-attachments/assets/fa85cd64-7552-418b-9af7-3380e3dac094)
![swap_used_(mb)_plot](https://github.com/user-attachments/assets/8430dc66-2db3-4057-b6c3-eaca5d254c58)


</details>

<details>
<summary>SCA logs</summary>

````
sh-3.2# tail -f -n +1 /Library/Ossec/logs/ossec.log
2024/10/08 18:09:35 sca: INFO: Module started.
2024/10/08 18:09:35 sca: INFO: Loaded policy '/Library/Ossec/ruleset/sca/cis_apple_macOS_15.x.yml'
2024/10/08 18:09:35 sca: INFO: Starting Security Configuration Assessment scan.
2024/10/08 18:09:35 sca: INFO: Starting evaluation of policy: '/Library/Ossec/ruleset/sca/cis_apple_macOS_15.x.yml'
2024/10/08 18:09:45 sca: INFO: Evaluation finished for policy '/Library/Ossec/ruleset/sca/cis_apple_macOS_15.x.yml'
2024/10/08 18:09:45 sca: INFO: Security Configuration Assessment scan finished. Duration: 10 seconds.


````

</details>

[metrics.zip](https://github.com/user-attachments/files/17300850/metrics.zip)



## Analysis
|                                      | Old SCA | New SCA | Difference |
|--------------------------------------|---------|---------|------------|
| CPU                                  |         |         |            |
| `wazuh-modulesd` average CPU percent | 1.39    | 1.40    | 0.01      |
| Overall average CPU percent          | 0.20    | 0.21    | 0.01     |
| Overall peak CPU percent             | 3.9      | 4.6    | -12.3       |
| Memory                               |         |         |            |
| `wazuh modulesd` average memory (MB) | 0.05    | 0.05    | 0.00       |
| Overall average memory used (MB)     | 1815.1     | 1823.7     | 8.60        |
| Overall peak memory used peak (MB)   | 1820.7     | 1831.3     | 10.60        |
| Disk                                 |         |         |            |
| Overall average disk used (MB)       | 10174.5    | 10174.5    | 0.00        |
| Overall peak disk used (MB)          | 10174.5    | 10174.5    | 0.00        |
| Overall average disk read bytes      | 5339.3   | 5478.9     | 139.60       |
| Overall peak disk read bytes         | 5339.3    | 5479.0     | 139.7       |
| Overall average disk write bytes     | 9217.8     | 9281.6    | 63.80      |
| Overall peak disk write bytes        | 9221.5     | 9285.2    | 63.70     |
