### ISSUE TITLE
Inconsistent Versioning for Microsoft Products on MacOS

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#24174]
## Description

Upon analyzing the vulnerabilities reported in[ this issue](https://github.com/wazuh/wazuh/issues/24167), it was identified that the versioning format for Microsoft products installed on MacOS does not match the versioning format reported by NVD (National Vulnerability Database). 

For example, PowerPoint installed on MacOS is recorded as version `16.86.24060916`, whereas NVD reports it as version `2002`.

VD information:
![image](https://github.com/wazuh/wazuh/assets/106940255/87f5f008-65e5-4f75-ac3d-6833202be6c2)

NVD information:
![image](https://github.com/wazuh/wazuh/assets/106940255/576fbed8-e35b-43ed-b6ea-e11c9e34fc30)

### Context

Accurate versioning is crucial for effective vulnerability detection and management. Discrepancies between the version formats used by software vendors and vulnerability databases can lead to incorrect vulnerability reports, missed detections, or false positives. This issue aims to address the inconsistency in versioning formats to ensure the reliability and accuracy of the vulnerability detector.

## Expected Outcome

- [x] Analyze the discrepancy between the versioning formats used by Microsoft for MacOS products and those reported by NVD.
- [x] Define a solution to harmonize these versioning formats to ensure accurate vulnerability reporting.

**Comment by sebasfalcone** [comment]
## Delayed ETA
Issue delayed due to higher priority ones, we are going to tackle this in 4.10.0 release

**Comment by sebasfalcone** [comment]
## Investigation
Given the great disparity between syscollector and the NVD, I've started to investigate the actual versions recognized by Microsoft

It was difficult to find a comprehensive list of releases to version, we can use [this wiki](https://en.wikipedia.org/wiki/Microsoft_Office#cite_note-version-106) as a reference for the investigation


> [!NOTE]
> Versions are not the same in macOS and Windows

### Windows

| Office version | Version number |
|----------------|----------------|
| 2000           | 9.0            |
| XP             | 10.0           |
| 2003           | 11.0           |
| 2007           | 12.0           |
| 2010           | 14.0           |
| 2013           | 15.0           |
| 2016           | 16.0           |
| 2019           | 16.0           |
| 2021           | 16.0           |
| 2024           | TBA            |

### macOS

| Office version | Version number |
|----------------|----------------|
|           2004 | 11.0           |
|           2008 | 12.0           |
|           2011 | 14.0           |
|           2016 | 15.0 – 16.16.x |
|           2019 | 16.17 – 16.52  |
|           2021 | 16.53+         |
|           2024 | TBA            |

**Comment by sebasfalcone** [comment]
## Conclusion
We are going to pursue the first solution (Solve the problem in the content)

**Comment by sebasfalcone** [comment]
## Resolution
The solution will be implemented in the content itself:
- https://github.com/wazuh/intelligence-platform/issues/1623

We are closing this issue

**Comment by pereyra-m** [comment]
Hi @George-Nat 

The team is working to sanitize these NVD entries that contain too generic expressions.
When the vulnerabilities content is updated, the managers will download it and you'll see the fix without upgrading the Wazuh manager.
