### ISSUE TITLE
Whodata for Windows does not detect folder renames

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2418]
## Bug report

**OS**
_Windows_

**Wazuh version**
_3.8.0-3802_

**Wazuh API version**
_None_

**Install type**
_agent_

**Install method**
_sources_

Bug description
----------------
When renaming a monitored subdirectory with whodata, two alerts should be generated for each file contained in it: one for deletion and one for addition with the new path.

This has never worked.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/2888.

**Comment by albertomn86** [comment]
Merged
