### ISSUE TITLE
Release 4.9.0 - Alpha 2 - E2E UX tests

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#24233]
## Description
The following issue will track all the E2E UX tests for this release stage.

The definition of done for this task is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes, all the issues from below must be closed.

## QA issues

| Name                        | Issue                                         | Status      |DRI|Reviewer|
|-----------------------------|------------------------------------------|--------------|------|------------|
| Deployment on Docker | #24195 | :white_circle: Skipped | @wazuh/devel-agent | @wazuh/devel-devops |
| Deployment with Puppet | #24196 |:white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-devops |
| Deployment with Ansible | #24197 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-devops |
| Deployment on Kubernetes | #24198 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-devops |
| Wazuh Dashboard | #24199 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-dashboard |
| Wazuh Indexer | #24200 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-indexer |
| Central components upgrade | #24201 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-qa |
| Demo environment | #24202 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-devops |
| Windows events | #24203 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-agent-div1 |
| macOS | #24204 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-agent-div3 |
| Vulnerability Detection | #24205 |:white_circle: Skipped| @wazuh/devel-qa | @wazuh/devel-cppserver-div1 |
| Active response | #24206 | :white_circle: Skipped | @wazuh/devel-indexer | @wazuh/devel-agent-div3 |
| Security Configuration Assessment | #24207 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-agent-div3 |
| File Integrity Monitoring | #24208 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-agent-div2 |
| Monitoring Docker | #24209 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-pyserver |
| Configuring email alerts | #24210 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-cppserver-div2 |
| MITRE | #24211 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-threatintel |
| Wazuh Indexer ISM policies | #24212 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-indexer |
| Centralized configuration - Agent groups | #24213 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-agent-div1 |
| SAML SSO | #24214 | :white_circle: Skipped | @wazuh/devel-devops | @wazuh/devel-dashboard |
| Change custom logos | #24215 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-dashboard |
| RBAC | #24216 | :white_circle: Skipped | @wazuh/devel-threatintel  | @wazuh/devel-pyserver |
| GCP integration | #24217 | :white_circle: Skipped | @wazuh/devel-agent | @wazuh/devel-pyserver |
| Amazon Cloudtrail integration | #24218 | :white_circle: Skipped | @wazuh/devel-qa | @wazuh/devel-pyserver |
| Amazon Cloudwatch Logs integration | #24219 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-pyserver |
| Office365 integration | #24221 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-agent-div2 |
| Github integration | #24222 | :white_circle: Skipped | @wazuh/devel-indexer | @wazuh/devel-agent-div2 |
| Azure integration | #24223 | :white_circle: Skipped | @wazuh/devel-cppserver | @wazuh/devel-pyserver |
| Amazon security lake | #24224 | :white_circle: Skipped | @wazuh/devel-agent | @wazuh/devel-pyserver |
| Microsoft Graph security API | #24225 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-agent-div2 |
| Integration with external APIs: Virustotal | #24226 | :white_circle: Skipped | @wazuh/devel-agent | @wazuh/devel-cppserver-div2 |
| Integration with external APIs: Slack and Pagerduty | #24227 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-cppserver-div2 |
| Integration with external APIs: Shuffle and Maltiverse | #24228 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-pyserver |
| Elastic integration | #24229 | :white_circle: Skipped | --- | --- |
| Splunk integration | #24230 | :white_circle: Skipped | --- | --- |
| Opensearch integration | #24231 | :white_circle: Skipped | ---| --- |
| Amazon Security Hub | #24222 | :white_circle: Skipped | @wazuh/devel-agent | @wazuh/devel-pyserver |
| HAProxy Helper | #24220 | :white_circle: Skipped | @wazuh/devel-cloud | @wazuh/devel-pyserver |

:white_circle: Skipped: The task has been deemed not necessary for this stage.
:black_circle: Not finished: The tasks haven't been finished yet.
:purple_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.
:yellow_circle: Completed with accepted known issues (new): Some issues were raised here, they were deemed non-stopper.

## Fixes
All the fixes for those issues detected in for this version can be found in the [v4.9.0 project](https://github.com/orgs/wazuh/projects/71/views/1).

**Comment by rauldpm** [comment]
Skipped until Alpha 3 so we have 4.8.1 RC 4 changes
