### ISSUE TITLE
RPM legacy packages do not find the Git reference when using tags

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#24249]
# Description

The generation of RPM legacy packages fails because it cannot find a GitHub reference when using the v4.9.0-alpha1 tag, we need to correct this to generate the packages.

```
 + docker run -t --rm -v /tmp:/var/local/wazuh:Z -e SYSTEM=rpm -e BUILD_TARGET=agent -e ARCHITECTURE_TARGET=i386 -e INSTALLATION_PATH=/var/ossec -e IS_STAGE=yes -e WAZUH_BRANCH= -v /home/runner/work/wazuh-agent-packages/wazuh-agent-packages:/wazuh-local-src:Z pkg_rpm_legacy_builder_i386:4.9.0 1.el5 2 no yes no yes no
+ '[' '!' -d /wazuh-local-src ']'
+ '[' yes = no ']'
+++ cat /wazuh-local-src/.git/HEAD
+++ cut '-d ' -f2
++ cat /wazuh-local-src/.git/d51c99141f272e07a8cba70814b9b42bfbbc29fb
cat: /wazuh-local-src/.git/d51c99141f272e07a8cba70814b9b42bfbbc29fb: No such file or directory
+ hash_commit=
+ return 1
```

# Tasks

- [x] Fix package generation
  - It should work using commits, branches, and tag

Issue reported by @rauldpm.

**Comment by mjcr99** [comment]
Hi team,

A possible solution would be to modify the conditional block where the `hash_commit` is obtained for legacy cases. When we use a branch the `.git/HEAD` contains a white space and its content looks as follows: `ref: refs/heads/4.9.0`, but for the tag case, the content is the `d51c99141f272e07a8cba70814b9b42bfbbc29fb` the found hash_commit.

We could find for the white space present for the branch cases, if its found, we are in the branch case, if not, we are in the tag case. In this else block: https://github.com/wazuh/wazuh/blob/a5f51ad61af5abcf49186cd72d4d73c0c3927021/packages/build.sh#L94

we could add the following check:

```
      if grep -q " " /wazuh-local-src/.git/HEAD; then
        hash_commit=$(cat /wazuh-local-src/.git/$(cat /wazuh-local-src/.git/HEAD|cut -d" " -f2))
      else
        hash_commit=$(cat /wazuh-local-src/.git/HEAD)
      fi
      short_commit_hash="$(cut -c 1-11 <<< $hash_commit)"
```
