### ISSUE TITLE
Upgrade urllib to >= 1.26.19

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#24254]
| Component |
|---|
| Wazuh embedded Python interpreter | 

## Description

During the last vulnerabilities scanner, we found that the currently used version of  the `urllib3` (`1.26.18`) package have reported vulnerabilities.

The packages should be upgraded to: 
* urllib3 >= 1.26.19

**CVEs**:
 - https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf

**Dependabot alerts**:
- https://github.com/wazuh/wazuh/security/dependabot/53

**Comment by RamosFe** [comment]
## Update

This upgrade is included in https://github.com/wazuh/wazuh/issues/23908 for `4.9.0` and `4.8.1` int https://github.com/wazuh/wazuh/issues/24329.
