### ISSUE TITLE
ERROR: Cannot initialize Wazuh indexer cluster.

### ISSUE THREAD

**Issue by Pinchinium** [wazuh/wazuh#24253]
4.8 Wazuh-Indexer All-In-One automated  Ubuntu 22.04

Wazuh automated installation break at wazuh-indexer initialization.
![Снимок экрана 2024-06-21 142944](https://github.com/wazuh/wazuh/assets/70957059/9186b064-78d9-4960-8042-47bae11d570b)

**Comment by davidcr01** [comment]
Hello. This errors appears when the Wazuh indexer cat not be initialized. In order to help you with this problem, follow these steps:

1. Enter the `wazuh-install.sh` script.
2. Go to line 1617 and add the following command: `read -p "Waiting."`. This command will stop the execution of the script at that line, and will wait for a keyboard input. Do not enter any keyboard input as the installation will continue.
3. Open another terminal, and run the following command: `curl -XGET https://<INDEXER_NODE_IP>:9200/ -uadmin:admin -k`. Replace the `INDEXER_NODE_IP` string with the IP you are using to install the Wazuh indexer.
4. Also, in the new terminal, run the `systemctl status wazuh-indexer` and `journalctl -u wazuh-indexer`. 
5. You can also check the logs of the Wazuh indexer with the following command: `cat /var/log/wazuh-indexer/wazuh-cluster.log | grep -i -E "error|warn"`.
6. Now, with the information collected, in the stopped terminal, you can enter any keyboard input and the installation will continue.

Now, to help you with the problem, please share the information you collected.

Hope it helps. Regards.

**Comment by Pinchinium** [comment]
Thank you for your answer. 
Required info (curl and log as files, and journalctl screenshot)
[curl.txt](https://github.com/user-attachments/files/15972789/curl.txt)
[log.txt](https://github.com/user-attachments/files/15972790/log.txt)
![photo_2024-06-25_17-10-45](https://github.com/wazuh/wazuh/assets/70957059/a4c0f80d-d041-4872-9345-00da138f8394)

**Comment by davidcr01** [comment]
Yes, that's the expected result. If the `curl` command output to the Wazuh indexer is "OpenSearch Security not initialized", it means that the Wazuh indexer is working properly, waiting to be initialized.

A quick question, did you continue the installation? If the answer is yes, you encountered the same error?

Hope it helps.

**Comment by Pinchinium** [comment]
Yes, I try to continue installation and encountered the same error
![Снимок экрана 2024-06-26 095124](https://github.com/wazuh/wazuh/assets/70957059/30bd7a6e-8684-4c27-804e-2647126db9b0)

**Comment by davidcr01** [comment]
Hello. Your behavior is quite strange. I tried to reproduce your problem without success. As you can see, in a Ubuntu 22.04 machine I can install the Wazuh indexer correctly.

```console
root@ip-172-31-91-242:/home/ubuntu# bash wazuh-install.sh -a -i -v
26/06/2024 08:27:05 DEBUG: Checking root permissions.
26/06/2024 08:27:05 DEBUG: Checking sudo package.
26/06/2024 08:27:05 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
26/06/2024 08:27:05 INFO: Verbose logging redirected to /var/log/wazuh-install.log
26/06/2024 08:27:05 DEBUG: APT package manager will be used.
26/06/2024 08:27:05 DEBUG: Checking system distribution.
26/06/2024 08:27:05 DEBUG: Detected distribution name: ubuntu
26/06/2024 08:27:05 DEBUG: Detected distribution version: 22
26/06/2024 08:27:05 DEBUG: Checking Wazuh installation.
26/06/2024 08:27:05 DEBUG: Checking system architecture.
26/06/2024 08:27:05 WARNING: Hardware and system checks ignored.
26/06/2024 08:27:05 DEBUG: Installing check dependencies.
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1528 kB]
Get:7 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [262 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [11.4 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1941 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [331 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [520 B]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [860 kB]
Get:14 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 c-n-f Metadata [286 kB]
Get:15 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:16 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [167 kB]
Get:18 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 c-n-f Metadata [8372 B]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [16.8 kB]
Get:20 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1769 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [37.2 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [7588 B]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [260 B]
Get:24 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [322 kB]
Get:25 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [16.1 kB]
Get:26 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [2057 kB]
Get:27 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [350 kB]
Get:28 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [520 B]
Get:29 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1088 kB]
Get:30 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [251 kB]
Get:31 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [22.1 kB]
Get:32 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [43.3 kB]
Get:33 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [10.8 kB]
Get:34 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [472 B]
Get:35 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [67.1 kB]
Get:36 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main Translation-en [11.0 kB]
Get:37 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 c-n-f Metadata [388 B]
Get:38 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 c-n-f Metadata [116 B]
Get:39 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [27.2 kB]
Get:40 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [16.3 kB]
Get:41 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [644 B]
Get:42 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 c-n-f Metadata [116 B]
Fetched 32.0 MB in 3s (9721 kB/s)
Reading package lists...
26/06/2024 08:27:18 INFO: Wazuh web interface port will be 443.
26/06/2024 08:27:18 DEBUG: Checking ports availability.
26/06/2024 08:27:19 DEBUG: Installing prerequisites dependencies.
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists...
26/06/2024 08:27:21 INFO: --- Dependencies ----
26/06/2024 08:27:21 INFO: Installing apt-transport-https.
Reading package lists... Building dependency tree... Reading state information... The following NEW packages will be installed: apt-transport-https 0 upgraded, 1 newly installed, 0 to remove and 203 not upgraded. Need to get 1510 B of archives. After this operation, 170 kB of additional disk space will be used. Get:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.12 [1510 B] Fetched 1510 B in 0s (121 kB/s) S NEEDRESTART-VER: 3.5 NEEDRESTART-KCUR: 5.19.0-1025-aws NEEDRESTART-KEXP: 5.19.0-1025-aws NEEDRESTART-KSTA: 1
26/06/2024 08:27:27 DEBUG: Checking curl tool version.
26/06/2024 08:27:27 DEBUG: Adding the Wazuh repository.
gpg: keyring '/usr/share/keyrings/wazuh.gpg' created
gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 96B3EE5F29111145: public key "Wazuh.com (Wazuh Signing Key) <support@wazuh.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:4 https://packages.wazuh.com/4.x/apt stable InRelease [17.3 kB]
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Get:6 https://packages.wazuh.com/4.x/apt stable/main amd64 Packages [41.3 kB]
Fetched 58.5 kB in 0s (190 kB/s)
Reading package lists...
26/06/2024 08:27:28 INFO: Wazuh repository added.
26/06/2024 08:27:28 INFO: --- Configuration files ---
26/06/2024 08:27:28 INFO: Generating configuration files.
26/06/2024 08:27:28 DEBUG: Creating Wazuh certificates.
26/06/2024 08:27:28 DEBUG: Reading configuration file.
26/06/2024 08:27:28 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:28 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:28 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:28 INFO: Generating the root certificate.
26/06/2024 08:27:29 INFO: Generating Admin certificates.
26/06/2024 08:27:29 DEBUG: Generating Admin private key.
26/06/2024 08:27:29 DEBUG: Converting Admin private key to PKCS8 format.
26/06/2024 08:27:29 DEBUG: Generating Admin CSR.
26/06/2024 08:27:29 DEBUG: Creating Admin certificate.
26/06/2024 08:27:29 INFO: Generating Wazuh indexer certificates.
26/06/2024 08:27:29 DEBUG: Creating the certificates for wazuh-indexer indexer node.
26/06/2024 08:27:29 DEBUG: Generating certificate configuration.
26/06/2024 08:27:29 DEBUG: Creating the Wazuh indexer tmp key pair.
26/06/2024 08:27:30 DEBUG: Creating the Wazuh indexer certificates.
26/06/2024 08:27:30 INFO: Generating Filebeat certificates.
26/06/2024 08:27:30 DEBUG: Generating the certificates for wazuh-server server node.
26/06/2024 08:27:30 DEBUG: Generating certificate configuration.
26/06/2024 08:27:30 DEBUG: Creating the Wazuh server tmp key pair.
26/06/2024 08:27:30 DEBUG: Creating the Wazuh server certificates.
26/06/2024 08:27:30 INFO: Generating Wazuh dashboard certificates.
26/06/2024 08:27:30 DEBUG: Generating certificate configuration.
26/06/2024 08:27:30 DEBUG: Creating the Wazuh dashboard tmp key pair.
26/06/2024 08:27:30 DEBUG: Creating the Wazuh dashboard certificates.
26/06/2024 08:27:30 DEBUG: Cleaning certificate files.
26/06/2024 08:27:30 DEBUG: Generating password file.
26/06/2024 08:27:30 DEBUG: Generating random passwords.
26/06/2024 08:27:30 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
26/06/2024 08:27:30 DEBUG: Extracting Wazuh configuration.
26/06/2024 08:27:30 DEBUG: Reading configuration file.
26/06/2024 08:27:30 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:30 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:30 DEBUG: Checking if 127.0.0.1 is private.
26/06/2024 08:27:30 INFO: --- Wazuh indexer ---
26/06/2024 08:27:30 INFO: Starting Wazuh indexer installation.
Reading package lists... Building dependency tree... Reading state information... The following NEW packages will be installed: wazuh-indexer 0 upgraded, 1 newly installed, 0 to remove and 203 not upgraded. Need to get 759 MB of archives. After this operation, 1050 MB of additional disk space will be used. Get:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-indexer amd64 4.8.0-1 [759 MB] Fetched 759 MB in 14s (53.0 MB/s) Selecting previously unselecte NEEDRESTART-VER: 3.5 NEEDRESTART-KCUR: 5.19.0-1025-aws NEEDRESTART-KEXP: 5.19.0-1025-aws NEEDRESTART-KSTA: 1
26/06/2024 08:28:38 DEBUG: Checking Wazuh installation.
26/06/2024 08:28:39 DEBUG: There are Wazuh indexer remaining files.
26/06/2024 08:28:39 INFO: Wazuh indexer installation finished.
26/06/2024 08:28:39 DEBUG: Configuring Wazuh indexer.
26/06/2024 08:28:39 DEBUG: Copying Wazuh indexer certificates.
26/06/2024 08:28:39 INFO: Wazuh indexer post-install configuration finished.
26/06/2024 08:28:39 INFO: Starting service wazuh-indexer.
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service → /lib/systemd/system/wazuh-indexer.service.
26/06/2024 08:28:51 INFO: wazuh-indexer service started.
26/06/2024 08:28:51 INFO: Initializing Wazuh indexer cluster security settings.
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.10.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /etc/wazuh-indexer/opensearch-security/
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update '/roles' with /etc/wazuh-indexer/opensearch-security/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '/internalusers' with /etc/wazuh-indexer/opensearch-security/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update '/actiongroups' with /etc/wazuh-indexer/opensearch-security/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Will update '/tenants' with /etc/wazuh-indexer/opensearch-security/tenants.yml 
   SUCC: Configuration for 'tenants' created or updated
Will update '/nodesdn' with /etc/wazuh-indexer/opensearch-security/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' created or updated
Will update '/whitelist' with /etc/wazuh-indexer/opensearch-security/whitelist.yml 
   SUCC: Configuration for 'whitelist' created or updated
Will update '/audit' with /etc/wazuh-indexer/opensearch-security/audit.yml 
   SUCC: Configuration for 'audit' created or updated
Will update '/allowlist' with /etc/wazuh-indexer/opensearch-security/allowlist.yml 
   SUCC: Configuration for 'allowlist' created or updated
SUCC: Expected 10 config types for node {"updated_config_types":["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"],"updated_config_size":10,"message":null} is 10 (["allowlist","tenants","rolesmapping","nodesdn","audit","roles","whitelist","internalusers","actiongroups","config"]) due to: null
Done with success
26/06/2024 08:29:02 INFO: Wazuh indexer cluster security configuration initialized.
26/06/2024 08:29:02 INFO: Wazuh indexer cluster initialized.
```

In order to help you with the issue, I need more information about your environment:
- Please, share your system distribution by running the `cat /etc/os-release` command.
- Please, tell me from where you downloaded the Wazuh installation assistant.
- Please, tell me the commands you are using to install the Wazuh indexer.

Also, to see what's happening, I request you to debug the code. To do this, follow these instructions:
1. Enter to the `wazuh-install.sh` script. 
2. In the 1613 line, introduce the `set -x` command.
3. In the 1617 line, introduce the `set +x` command.
3. Save the changes.
4. Run the script again.

Hope it helps. I'm looking forward to hearing back from you.

**Comment by Pinchinium** [comment]
Thank you, that tips really help me
But I've been catch new trouble on the next step with WazuhAPI
![Uploading Снимок экрана 2024-06-26 095124.png…]()

**Comment by Pinchinium** [comment]
![wazuh (1)](https://github.com/wazuh/wazuh/assets/70957059/2cfb13e1-20ff-44ab-a24e-85d08f5d8def)
![wazuh (2)](https://github.com/wazuh/wazuh/assets/70957059/644e50d3-00bf-4002-901d-cf504a9ae445)

**Comment by Pinchinium** [comment]
Okay

I enter this command:    bash wazuh-install.sh -a -v
I download that script with     curl -sO https://packages.wazuh.com/4.8/wazuh-install.sh
I didn't change any files. My operation system:
![wazuh](https://github.com/wazuh/wazuh/assets/70957059/eda18be0-5b4a-4204-8a47-9023f5f9f6bc)

**Comment by Pinchinium** [comment]
[wazuh-install.log](https://github.com/user-attachments/files/15987368/wazuh-install.log)

**Comment by davidcr01** [comment]
Hello again. Thank you for the information you provided. It seems that the Wazuh installation assistant is having some trouble fetching the Wazuh API users. To investigate what's happening, I would need to execute the following steps:

1. In the directory where you have located the `wazuh-install.sh`, you should have a TAR file called `wazuh-install-files.tar`
2. Decompress this TAR file with the `tar -xv wazuh-install-files.tar`
3. Now, in the same directory you should have a new folder called `wazuh-install-files`
4. Move to that folder by running `cd wazuh-install-files`.
5. Run the following command: `grep api_username: wazuh-passwords.txt | awk '{ print substr( $2, 1, length($2) ) }' | sed -e "s/[\'\"]//g"`

After running this command, you should get the following output:
```console
wazuh
wazuh-wui
```

If you don't get this output, please let me know and I'll try to solve your problem as soon as possible. 

After these steps, you can remove the `wazuh-install-files` folder safely by running the `rm -rf wazuh-install-files` command.

Hope it helps.

**Comment by Pinchinium** [comment]
Hello, thank you for support! 
I get this output after the command running
![wazuh2](https://github.com/wazuh/wazuh/assets/70957059/c7b89785-9545-43f5-89cf-03af30025686)

**Comment by davidcr01** [comment]
Hello again. Thank you for the information you provided. With that check we can confirm that the users are contained in the passwords file. We continue debugging the code in order to guess what's happening.

I request you to follow these instructions:
- Edit the `wazuh-install.sh` file.
- Go to line 2103 and add the `set -x` command.
- Go to line 2166, insert a new line and add the `set +x` to that line.
- Run the script again.

Now please, share the log of the Wazuh installation assistant in a file as you have done in your previous responses. Thank you very much for your cooperation.

**Comment by davidcr01** [comment]
Hello. Thank you for sharing your log. However, I can not see the debug logs.
Maybe I was incorrect about the previous steps. You should add the `set -x` command in the 2103 line, and add a new line in the 2116, and it that new line insert the `set +x` command. Please make sure you save the changes in the file before executing the script. Please share with me again the logs.

Looking forward to seeing the results.

**Comment by Pinchinium** [comment]
That's new debug strings. Thank You!

+ for j in "${!fileapiusers[@]}"
+ supported=false
+ '[' false = false ']'
+ '[' -n 'wazuh-indexer/stable,now 4.8.0-1 amd64 [installed]' ']'
+ common_logger -e 'The Wazuh API user wazuh does not exist'
++ date '+%d/%m/%Y %H:%M:%S'
+ now='27/06/2024 11:57:38'
+ mtype=INFO:
+ debugLogger=
+ nolog=
+ '[' -n -e ']'
+ '[' -n -e ']'
+ case ${1} in
+ mtype=ERROR:
+ shift 1
+ '[' -n 'The Wazuh API user wazuh does not exist' ']'
+ case ${1} in
+ message='The Wazuh API user wazuh does not exist'
+ shift 1
+ '[' -n '' ']'
+ '[' -z '' ']'
+ '[' 0 -eq 0 ']'
+ '[' -z '' ']'
+ printf '%s\n' '27/06/2024 11:57:38 ERROR: The Wazuh API user wazuh does not exist'
+ tee -a /var/log/wazuh-install.log
27/06/2024 11:57:38 ERROR: The Wazuh API user wazuh does not exist
+ for j in "${!fileapiusers[@]}"
+ supported=false
+ '[' false = false ']'
+ '[' -n 'wazuh-indexer/stable,now 4.8.0-1 amd64 [installed]' ']'
+ common_logger -e 'The Wazuh API user wazuh-wui does not exist'
++ date '+%d/%m/%Y %H:%M:%S'
+ now='27/06/2024 11:57:38'
+ mtype=INFO:
+ debugLogger=
+ nolog=
+ '[' -n -e ']'
+ '[' -n -e ']'
+ case ${1} in
+ mtype=ERROR:
+ shift 1
+ '[' -n 'The Wazuh API user wazuh-wui does not exist' ']'
+ case ${1} in
+ message='The Wazuh API user wazuh-wui does not exist'
+ shift 1
+ '[' -n '' ']'
+ '[' -z '' ']'
+ '[' 0 -eq 0 ']'
+ '[' -z '' ']'
+ printf '%s\n' '27/06/2024 11:57:38 ERROR: The Wazuh API user wazuh-wui does not exist'
+ tee -a /var/log/wazuh-install.log
27/06/2024 11:57:38 ERROR: The Wazuh API user wazuh-wui does not exist
+ set +x

**Comment by davidcr01** [comment]
Hello again, thank you for your cooperation and for sharing the logs. I am debugging the script trace in order to guess what's happening. I have concluded that the array of the Wazuh API users is not initialized, that is why you are getting those errors.

I would like to request your cooperation again by debugging the code. 

I request you to follow these instructions:
- Edit the wazuh-install.sh file.
- Remove the changes you have done previously. This would consist in removing the `set -x` of the 2103 line and the `set +x` of the 2166 line.
- Go to line 1933, insert a new line and add the `set -x` command.
- Go to line 1940, insert a new line and add the `set +x` to that line.
- Run the script again.

After the edit, you should have that script block as follows:
```
set -x
if { [ -n "${wazuh}" ] || [ -n "${AIO}" ]; } && { [ "${server_node_types[pos]}" == "master" ] || [ "${#server_node_names[@]}" -eq 1 ]; }; then
    passwords_getApiToken
    passwords_getApiUsers
    passwords_getApiIds
else
    api_users=( wazuh wazuh-wui )
fi
set +x
```

Please make sure you save the changes in the file before executing the script. Please share with me again the logs.

Looking forward to seeing the results.

**Comment by Pinchinium** [comment]
That's new log lines:

+ '[' -n '' ']'
+ '[' -n 1 ']'
+ '[' '' == master ']'
+ '[' 1 -eq 1 ']'
+ passwords_getApiToken
+ retries=0
+ max_internal_error_retries=20
++ curl -s -u wazuh:wazuh -k -X POST 'https://localhost:55000/security/user/authenticate?raw=true' --max-time 300 --retry 5 --retry-delay 5
+ TOKEN_API=
+ [[ '' =~ Wazuh Internal Error ]]
+ [[ '' =~ Wazuh Internal Error ]]
+ [[ '' =~ Invalid credentials ]]
+ passwords_getApiUsers
+ mapfile -t api_users
++ common_curl -s -k -X GET -H '"Authorization:' Bearer '"' -H '"Content-Type:' 'application/json"' '"https://localhost:55000/security/users?pretty=true"' --max-time 300 --retry 5 --retry-delay 5
++ grep username
++ awk '-F: ' '{print $2}'
++ '[' -n 0 ']'
++ eval 'curl -s' -k -X GET -H '"Authorization:' Bearer '"' -H '"Content-Type:' 'application/json"' '"https://localhost:55000/security/users?pretty=true"' --max-time 300 --retry 5 --retry-delay '5 --retry-connrefused'
++ sed -e 's/[\'\''",]//g'
+++ curl -s -k -X GET -H 'Authorization: Bearer ' -H 'Content-Type: application/json' 'https://localhost:55000/security/users?pretty=true' --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused
++ e_code=56
++ return 56
+ passwords_getApiIds
+ mapfile -t api_ids
++ common_curl -s -k -X GET -H '"Authorization:' Bearer '"' -H '"Content-Type:' 'application/json"' '"https://localhost:55000/security/users?pretty=true"' --max-time 300 --retry 5 --retry-delay 5
++ grep id
++ '[' -n 0 ']'
++ awk '-F: ' '{print $2}'
++ eval 'curl -s' -k -X GET -H '"Authorization:' Bearer '"' -H '"Content-Type:' 'application/json"' '"https://localhost:55000/security/users?pretty=true"' --max-time 300 --retry 5 --retry-delay '5 --retry-connrefused'
+++ curl -s -k -X GET -H 'Authorization: Bearer ' -H 'Content-Type: application/json' 'https://localhost:55000/security/users?pretty=true' --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused
++ sed -e 's/[\'\''",]//g'
++ e_code=56
++ return 56
+ set +x

Thank you!!

**Comment by davidcr01** [comment]
I am working in your answer. I will be back ASAP!

**Comment by davidcr01** [comment]
Hello. It seems that the Installation assistant can't get the API token of the Wazuh manager. In order to help you with this, I recommend you to change the approach to install Wazuh.

You are using the `-a` parameter of the script, that installs every central component in the machine. I suggest you to follow the official documentation of the installation of each component. It's not difficult, I leave you the related documentation:
- [Installing the Wazuh indexer.](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html)
- [Installing the Wazuh server.](https://documentation.wazuh.com/current/installation-guide/wazuh-server/installation-assistant.html)
- [Installing the Wazuh dashboard.](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/installation-assistant.html)

If you have any problem in the installation, don't hesitate to ask me for help.

**Comment by Pinchinium** [comment]
Ok, I try to install it on another system

**Comment by davidcr01** [comment]
No, it is not about installing it in other system, is about changing the way your are installing it. Sorry if I didn't explain myself properly.
