### ISSUE TITLE
Question: Injected event from custom integrator completely ignored - why?

### ISSUE THREAD

**Issue by pandel** [wazuh/wazuh#24264]
Hey!

I am trying to inject an event via a custom script into the queue, as described in the many integrator articles on the Wazuh blog and elsewhere.

I am using a fresh deployment of Wazuh 4.8.0 via Docker stack (official wazuh-docker single_node).

Additionally, I
- activated my custom integrator script
- added the neccessary rules to local_rules.xml
- activated `logall`, to see what's going on in `archives.log`.

**The Python code responsible for the event generation in the script:**
```
def send_event(msg, agent = None):
    if not agent or agent["id"] == "000":
        string = '1:misp:{0}'.format(json.dumps(msg))
    else:
        string = '1:[{0}] ({1}) {2}->misp:{3}'.format(agent["id"], agent["name"], agent["ip"] if "ip" in agent else "any", json.dumps(msg))
    sock = socket(AF_UNIX, SOCK_DGRAM)
    sock.connect(socket_addr)
    sock.send(string.encode())
    sock.close()
```

**The event being added to the queue via the custom integrator script after a successful execution:**
`1:[001] (machine) 10.90.206.32->misp:{"misp": {"event_id": "179", "category": "Network activity", "value": "zu4f.top", "type": "domain"}}`

**The ruleset:**
```
<group name="misp,">
 <rule id="100620" level="10">
    <field name="integration">misp</field>
    <description>MISPs</description>
    <group>misp,</group>
    <options>no_full_log</options>
  </rule>
<rule id="100621" level="5">
    <if_sid>100620</if_sid>
    <field name="misp.error">\.+</field>
    <description>MISP - Error connecting to API</description>
    <options>no_full_log</options>
    <group>misp,misp_error,</group>
  </rule>
<rule id="100622" level="12">
    <if_sid>100620</if_sid>
    <field name="misp.category">\.+</field>
    <description>MISP - IoC found in Threat Intel - Category: $(misp.category), Attribute: $(misp.value)</description>
    <options>no_full_log</options>
    <group>misp,misp_alert,</group>
  </rule>
</group>
```

**The result**
There is an entry in `archives.log` which looks fine so far, but no event is created. I also tested the injected line via the `Ruleset Test` webpage but also with no result. After a week of research, trial and error, changing the script, rewriting the script from scratch, I have absolutely no idea why this is happening.

I simply don't understand why everything seems to work (integrator firing my custom script, receiving data from the external service, building the new event out of all the data and in the end injecting it into the queue via `send_event(...)`) as in all the other examples regarding the integrator - my event is not being interpreted. It is simply ignored ¯\_(ツ)_/¯

Maybe someone has an idea, why...

Regards,
Holger

**Comment by OlexTratisky** [comment]
Hello i am facing some issues with the misp integratio too in 4.8 

Sysmon events type 22 (DNS) fire correctly the misp custom-script but sysmon event != 22 like 3 fo example, gets ignored completely.    The script is not called on those. Maybe someone can have a look? 

<integration>
<name>custom-misp</name>
<group>sysmon_event1,sysmon_event3,sysmon_event6,sysmon_event7,sysmon_event_15,sysmon_event_22,</group> <alert_format>json</alert_format>
</integration>

**Comment by juliancnn** [comment]
Hi @pandel,

If the event appears in `archives.log`, it means your event is being received correctly but might not be matching your rules. Your script seems correct, so let's verify the rules.

Please enable the [logall_json](https://documentation.wazuh.com/current/user-manual/manager/wazuh-archives.html#enabling-the-wazuh-archives) option to create entries in JSON format (`archive.json`). This will help us precisely evaluate your rules against the incoming events.

Could you share some entries from this file where the integration logs are? This will help us identify any issues with the rules.

Best regards,
Julian

**Comment by pandel** [comment]
Hi @juliancnn ,

thanks for your hint regarding the json log, but yesterday I made some progress and regardless of your message, I wanted to verify my results today and post them here.

I noticed, that the script did not add the `integrations` field anywhere in the event, so I modified the Python code, because from my understanding rule no. 100620 is referring to that field, but it is not found in the alert anywhere:

```
def send_event(msg, agent = None):
    msg["integration"] = "misp"
    if not agent or agent["id"] == "000":
        string = '1:misp:{0}'.format(json.dumps(msg))
    else:
        string = '1:[{0}] ({1}) {2}->misp:{3}'.format(agent["id"], agent["name"], agent["ip"] if "ip" in agent else "any", json.dumps(msg))
    sock = socket(AF_UNIX, SOCK_DGRAM)
    sock.connect(socket_addr)
    sock.send(string.encode())
    sock.close()
    f = open( '/tmp/misp.log', 'a' )
    f.write(string)
    f.write( '\n' )
    f.close()
```

This leads to events being added to the queue like this (mind the added field):

`1:[001] (FW098ST7) 10.226.98.5->misp:{"misp": {"event_id": "179", "category": "Network activity", "value": "zu4f.top", "type": "domain"}, "integration": "misp"}`

**And NOW the rules trigger! Yay!**

So the error is clearly within my custom script that generates the event.

**Comment by juliancnn** [comment]
Glad to hear that! I will close this issue as resolved.

Regards!
