### ISSUE TITLE
Question - Get active vulnerabilities: Wazuh 4.8.0

### ISSUE THREAD

**Issue by tfmotu** [wazuh/wazuh#24268]
Hi, 
in previous versions of Wazuh we get the agents vulnerabilities using wazuh api endpoint:
https://documentation.wazuh.com/4.7/user-manual/api/reference.html#tag/Vulnerability
      "agent_vulnerabilities": "/vulnerability/XXX?pretty=true",
      "agent_vulnerabilities_summary": "/vulnerability/XXX/summary/severity",

but in new versions the vulnerability endpoint is deprecated: https://github.com/wazuh/wazuh/issues/20115

We need some help in order to get this info from the new indice, or from Vulnerability Detection inventory.
If you can share an example, we would appreciate it.

Thanks in advance.

**Comment by davidcr01** [comment]
Hello. Yes, the endpoint you mentioned was removed due to the Vulnerability Detector refactor. Now, as the alerts are stored in an index in Wazuh Indexer.

The index name will follow the pattern `wazuh-states-vulnerabilities-<cluster-name>`.
You can query that index using the API on your Wazuh Indexer, port 9200 by default, as follows
`GET <index-name>/_search`

More information is in the following link: https://opensearch.org/docs/latest/api-reference/search/

Hope it helps.

**Comment by davidcr01** [comment]
I'm working in your issue. I will come back as soon as I have your answer!

**Comment by davidcr01** [comment]
Hello again.

Maybe you are only getting the vulnerabilities of one node because of the indicated `cluster-name`. You can use a wildcard to get the vulnerabilities of all the nodes.

Please, try the following query:
```console
GET /wazuh-states-vulnerabilities-*/_search
{
  "query": {
    "match": {
      "vulnerability.severity": "Critical"
    }
  }
}
```
That query searches in all the nodes for critical vulnerabilities. Hope it helps.

**Comment by shkatara** [comment]
Hello David. 
This works just fine what I was looking for :D 
However, it only gives me "some" vulnerabilities of "some" nodes, instead of telling about all the critical vulnerability packages on all the agents.
Am I missing something here.. 😞

**Comment by shkatara** [comment]
I mean, I could list the agents from the API and register them in a variable and run the query per host to get their vulnerabilities. But was thinking if this is possible right from the elasticsearch :)

**Comment by davidcr01** [comment]
I'm working on your answer. I will be back ASAP!

**Comment by shkatara** [comment]
I tried with query having vulnerability and package name, but looks like they are not supported together

{
  "query": {
    "match": {
      "vulnerability.severity": "Critical",
      "agent.name": "metal24"
    }
  }
}

**Comment by shkatara** [comment]
Also, if I tried only having one match in the query for agent.name, it still does not give me all the critical vulnerabilities, just returns two or three results that are high / medium or critical

**Comment by davidcr01** [comment]
Hello. In case you want to filter by more than one field, you should change the syntax of the query. Here is an example of getting the critical vulnerabilities of the agent with name `metal24`:

```console
GET /wazuh-states-vulnerabilities-*/_search
{
  "query": {
    "bool": {
      "must": [
        {"match": {"vulnerability.severity": "Critical"}},
        {"match": {"agent.name": "metal24"}}
      ]
    }
  }
}
```
Hope it helps!

**Comment by shkatara** [comment]
Perfect ! This works just fine. 
Just thing, can we give a list of nodes in the match for agent.name so I do not have to loop over it for all the nodes ?

**Comment by shkatara** [comment]
Ah, it is a bool. So perhaps no. But the soln you gave is just fine. Thank you :)
