### ISSUE TITLE
'regex/order' does not work with 'prematch' in parent decoder

### ISSUE THREAD

**Issue by candlerb** [wazuh/wazuh#2427]
## Bug report

**OS**
Ubuntu 18.04

**Wazuh version**
3.8.0-1

**Wazuh API version**
3.8.0-1

**Install type**
manager

**Install method**
packages

**Log sample**
see below

Bug description
----------------

I added the following to `/var/ossec/ruleset/decoders/0065-cisco-ios_decoders.xml`

```
<!--
  - Sequence number and origin-id
  - 106: ix-edgesw-r1b3a: %SYS-5-CONFIG_I:
-->

<decoder name="cisco-ios">
  <prematch>^\d+:\s+\w+:\s+%</prematch>
  <regex>^\d+:\s+(\w+):</regex>
  <order>origin</order>
</decoder>
```

I added it just above this existing entry:

```
<!-- Cisco IOS
  - Will extract the action, srcip, srcport, dstip and dstport
  - Samples:
  -
  - %SEC-6-IPACCESSLOGP: list 102 denied tcp 10.0.6.56(3067) -> 172.36.4.7(139), 1 packet
  - %SEC-6-IPACCESSLOGP: list 199 denied tcp 10.0.61.108(1477) -> 10.0.127.20(445), 1 packet
  -->
... etc
```

This decoder does match, but it doesn't capture the "origin" value.  It appears to be ignoring regexp/order entirely.

```
# echo "106: ix-edgesw-r1b3a: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (1.2.3.4)" | /var/ossec/bin/ossec-logtest
2019/01/22 11:37:00 ossec-testrule: INFO: Started (pid: 23948).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: '106: ix-edgesw-r1b3a: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (1.2.3.4)'
       timestamp: '(null)'
       hostname: 'ix-wazuh'
       program_name: '(null)'
       log: '106: ix-edgesw-r1b3a: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (1.2.3.4)'

**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       id: '%SYS-5-CONFIG_I'      <<<< NOTE: missing "origin"

**Phase 3: Completed filtering (rules).
       Rule id: '4721'
       Level: '3'
       Description: 'Cisco IOS router configuration changed.'
**Alert to be generated.
```

But notice that it does work with the *child* decoder which is at the end of the file, as it captures the "id" value.  Here is the existing child decoder:

```
<!-- Cisco IOS
  - Extracts the ID of cisco ios messages IF NOT IDS/ACL log.
  -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(%\w+-\d-\w+):</regex>
  <order>id</order>
</decoder>
```

In fact, I can add a second child decoder, and they will capture the parts:

```
<!-- Cisco IOS
  - Extracts the ID of cisco ios messages IF NOT IDS/ACL log.
  -->
<!-- NEW -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(\w+): %</regex>
  <order>origin</order>
</decoder>

<!-- ORIGINAL -->
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(%\w+-\d-\w+):</regex>
  <order>id</order>
</decoder>
```

Gives:

```
**Phase 2: Completed decoding.
       decoder: 'cisco-ios'
       origin: 'ix-edgesw-r1b3a'     <<<<<
       id: '%SYS-5-CONFIG_I'
```

However I don't want to do it here, because in the child decoder, `\w+` might match things other than origin (e.g. the last two digits of a timestamp).  I only want to extract the 'origin' value if the original pattern contains an origin, which only the parent knows.

**Comment by juan70** [comment]
Hello, @candlerb,

I have been testing decoders on versions 3.8, 3.3 and 3.5, and the behaviour is the same: it seems as though the `<order>` element is not taken into account when a decoder is used as a `parent` in another decoder.

I came up with a minimal working solution, by adding the following code to the XML file:
- The parent:
```
<decoder name="cisco-ios">
  <prematch>^\d+:\s+\w+:\s+%</prematch>
</decoder>
```
- And the child:
```
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>:\s+(\w+):</regex>
  <order>origin</order>
</decoder>
```
Or `<regex>^\d+:\s+(\w+):</regex>`, where the beginning of the parent's prematch is repeated in the child. I have been testing with the sample log strings existing in the XML file and with the log string from your example:
``` 
echo "00:00:46: %LINK-3-UPDOWN: Interface Port-channel1, changed state to up" | /var/ossec/bin/ossec-logtest
echo "*Mar  1 18:46:11: %SYS-5-CONFIG_I: Configured from console by vty2 (10.34.195.36)" | /var/ossec/bin/ossec-logtest
echo "Mar  1 18:46:11: %SYS-5-CONFIG_I: Configured from console by vty2 (10.34.195.36)" | /var/ossec/bin/ossec-logtest
echo "*Mar  1 18:48:50.483 UTC: %SYS-5-CONFIG_I: Configured from console by vty2 (10.34.195.36)" | /var/ossec/bin/ossec-logtest
echo "Mar  1 18:48:50.483 UTC: %SYS-5-CONFIG_I: Configured from console by vty2 (10.34.195.36)" | /var/ossec/bin/ossec-logtest
echo "000019: %SYS-5-CONFIG_I: Configured from console by vty2 (10.34.195.36)" | /var/ossec/bin/ossec-logtest
echo "1348: .Jun 12 18:22:22 UTC: %SYS-5-CONFIG_I:" | /var/ossec/bin/ossec-logtest
echo "1348: *Jun 12 18:22:22 UTC: %SYS-5-CONFIG_I:" | /var/ossec/bin/ossec-logtest
echo "1348: Jun 12 18:22:22 UTC: %SYS-5-CONFIG_I:" | /var/ossec/bin/ossec-logtest
echo "681: Aug 17 17:41:24.776 AEST: %SEC-6-IPACCESSLOGS:" | /var/ossec/bin/ossec-logtest
echo "%SEC-6-IPACCESSLOGP: list 102 denied tcp 10.0.6.56(3067) -> 172.36.4.7(139), 1 packet" | /var/ossec/bin/ossec-logtest
echo "%SEC-6-IPACCESSLOGP: list 199 denied tcp 10.0.61.108(1477) -> 10.0.127.20(445), 1 packet" | /var/ossec/bin/ossec-logtest
echo "Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:51654 -> 10.10.10.10:4444]" | /var/ossec/bin/ossec-logtest
echo "Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:3051 Subsig:1 Sev:4 TCP Connection Window Size DoS [192.168.100.11:60797 -> 10.10.10.10:80]" | /var/ossec/bin/ossec-logtest
echo "Sep  1 10:25:29 10.10.10.1 %IPS-4-SIGNATURE: Sig:5123 Subsig:2 Sev:5 WWW IIS Internet Printing Overflow [192.168.100.11:60797 -> 10.10.10.10:80]" | /var/ossec/bin/ossec-logtest
echo "106: ix-edgesw-r1b3a: %SYS-5-CONFIG_I: Configured from console by admin on vty0 (1.2.3.4)" | /var/ossec/bin/ossec-logtest
``` 
The only log string for which a field `origin` is extracted is the last one.

Hope it helps.

As a side note, bear in mind that the standard decoders files located at `/var/ossec/ruleset/decoders/` will be lost during an update. You may want to have a look at the documentation https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#changing-an-existing-decoder in order to preserve your changes in case you decide to update Wazuh to a newer version.


Thank you.
juan70.

**Comment by candlerb** [comment]
Thanks - I guess that will work.

> As a side note, bear in mind that the standard decoders files located at `/var/ossec/ruleset/decoders/` will be lost during an update.

I know: I'm developing some enhancements to contribute back to the project.

**Comment by juan70** [comment]
Ah, Ok. Thank you very much for your contribution.

**Comment by candlerb** [comment]
I would like to see either:

1. A documentation update which says explicitly that `order` does not function if the decoder has one or more child decoders (and also stating that as a workaround, you can create an extra child decoder which matches the same regex as the parent); or
2. A code change which makes `order` work when there are child decoders.

The current behaviour is surprising, since the user has no reason to suspect that it shouldn't work.

**Comment by vikman90** [comment]
Hi @candlerb,

Just as a reply to your last message, there is a related discussion in the mailing list: [Custom decoder field Padding](https://groups.google.com/d/msg/wazuh/awWrghZXpUg/0WGR74rSAAAJ), where I tried to clarify the behavior of the parent-children decoders that @juan70 explained here.

I'm looking forward to explaining all this in the documentation, it's a bit tricky.
Best regards.
