### ISSUE TITLE
`wazuh-modulesd` The scan interval value '10 seconds' is too small Warning message

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#24289]
## Description

Through the development of version 4.9.0
The following message has been observed in the footprint tests:

```
wazuh-modulesd WARNING: The scan interval value '10 seconds' is too small. Option set to 60 seconds.
```

This message is related to https://github.com/wazuh/wazuh/pull/23145

> More analysis is required

**Comment by sebasfalcone** [comment]
This behavior is expected, we set the lower bound for syscollector scan time to 60 seconds to prevent overlaps between scans

Related issue:
- https://github.com/wazuh/wazuh/issues/22440
