### ISSUE TITLE
Wildcard for restrict option of syscheck 

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#2428]
## Feature request

**Compatibility**
_both_

**Component involved**
_Syscheck_

Description
--------------

I'd found interesting to allow `wildcards` in the `restrict` option of Syscheck. It could be used like this example:

```
<directories check_all="yes" whodata="yes" report_changes="yes" restrict="*.txt">/home/anon/files/</directories>
```

Share your thoughts on this.

Cheers

**Comment by Lopuiz** [comment]
Hi!

I am going to close this issue because it solved in new FIM

Regards,
Eva
