### ISSUE TITLE
Indexer Connector - Multiple CA files aren't supported

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24295]
## Description
The configuration for the indexer connector allows the user to define multiple CA (certificate authorities) files to connect to the indexer:
```xml
      <certificate_authorities>
        <ca>/etc/pki/tls/private/private-ca-chain.pem</ca>
      </certificate_authorities>
```

However, this is not reflected in the code:
https://github.com/wazuh/wazuh/blob/70c40f2006adf55b563c378d8d6b0eaafafc00d0/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L45

## Expected behavior
We should iterate over the array of CA files and generate as many secure communications:
https://github.com/wazuh/wazuh/blob/70c40f2006adf55b563c378d8d6b0eaafafc00d0/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L65-L68

Each post to the indexer should attempt to use each secure communication once (and stop trying if it succeeds)

<details>
<summary>Post requests</summary>

https://github.com/wazuh/wazuh/blob/d2f167fdc540600429a679d693ffd52ff65b9222/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L168-L182
https://github.com/wazuh/wazuh/blob/d2f167fdc540600429a679d693ffd52ff65b9222/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L150-L157
https://github.com/wazuh/wazuh/blob/d2f167fdc540600429a679d693ffd52ff65b9222/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L264-L271
https://github.com/wazuh/wazuh/blob/d2f167fdc540600429a679d693ffd52ff65b9222/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L411-L422

</details>

## DoD
- [x] Multiple CA files are supported
- [ ] Tests are updated

**Comment by GabrielEValenzuela** [comment]
# Update

- Analysis and research.

**Comment by GabrielEValenzuela** [comment]
# Update

- Await confirmation of solution proposal, which consists of a refactor of code and dependences.

**Comment by GabrielEValenzuela** [comment]
# Update

- Doing research, trying to emulate the cloud environment and replicate multiple instances of Indexer to probe concatenate certificates in a single file.

**Comment by sebasfalcone** [comment]
## Issue blocked
@Dwordcito We have to decide the right approach for the solution:

- Refactor http-request to receive multiple CAs in the same request:
  - This requires a lot of refactor on the http-request module due to how libcurl works with CA files
- Create a wrapper in wazuh/wazuh
  - This is a simpler approach but requires to create a new wrapper for the requests
- Bundle multiple CAs into one:
  - This is the simpler approach, it requires that we update the documentation

**Comment by GabrielEValenzuela** [comment]
# Update

- Working on design based on the proposal.

**Comment by sebasfalcone** [comment]
## Update
The proposed solution has changed, we are going to use the third approach "Bundle multiple CAs into one". But instead of making the user bundle the certs, we are going to do it at the indexer connector initialization level

**Comment by GabrielEValenzuela** [comment]
# Update
- Redesign solution based on today’s meet.

**Comment by GabrielEValenzuela** [comment]
# Update

- Set up a Docker environment (2 managers, 3 indexers, 1 dashboard), to test the solution of manually merging the CAs.
- I noticed with three indexers and default configuration

```xml
 <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://wazuh1.indexer:9200</host>
      <host>https://wazuh2.indexer:9200</host>
      <host>https://wazuh3.indexer:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/ssl/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/ssl/filebeat.pem</certificate>
      <key>/etc/ssl/filebeat.key</key>
    </ssl>
  </indexer>
```

- There is only one CA

**Comment by GabrielEValenzuela** [comment]
# Update

- Block trying to add another indexer to test. This could be a potential issue, due need to automate the testing.
- Trying to add a fourth indexer in Docker -> Unable to add, the generate_certs tool only generates certs for all dockers, the same `root_ca.pem`
- Trying to create two VMs, one having (1 indexer, 1 manager, 1 dashboard) and another VM with 1 indexer -> Unable to install and run the cluster. 4Gb RAM and 4vCPU.

**Comment by sebasfalcone** [comment]
## ETA updated
- Due to difficulties generating the test environment we were unable to test the solution

**Comment by GabrielEValenzuela** [comment]
# Update

- After meeting with the indexer team, we created an issue to delegate the confirmation of this feature.

**Comment by sebasfalcone** [comment]
## Issue blocked
This issue is blocked by:
- https://github.com/wazuh/wazuh/issues/24551

**Comment by sebasfalcone** [comment]
## Issue unblocked
The research made by the indexer team demonstrated the feasibility of this proposal

**Comment by GabrielEValenzuela** [comment]
# Update

- Task done. Pending review.

**Comment by GabrielEValenzuela** [comment]
# Update

- Changes done. Pending review.

**Comment by GabrielEValenzuela** [comment]
# Update

- Change the path and add a new feature to the directory's path.

**Comment by GabrielEValenzuela** [comment]
# Update

- Change to relative path and add logic of folder creation.

**Comment by GabrielEValenzuela** [comment]
# Update 

- Refactor based on review comments. Logic improvement. Pending review.

**Comment by sebasfalcone** [comment]
## Update ETA
Updated ETA so the final reviewer can see this issue
