### ISSUE TITLE
Significant Decrease in Resource Usage by modulesd

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#24291]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-Alpha1 | Wazuh component | Manager and Agent | Packages | centOS, Windows, Ubuntu |

Testing: [Footprint Metrics - SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/24270)

Significant Decrease in Resource Usage by modulesd Across All Platforms

In the manager and all the agents (centOS, Windows, Ubuntu)

Observed Behavior: Significant decrease in CPU, Disk, RSS, USS, VMS, Read_Ops, and PSS usage by modulesd.

CPU:
4.9.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/ceb7b3a8-de9d-41c7-b50d-db41a595841c)
4.8.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/e618ab31-d386-4c57-a07e-98a5bd97a98e)

4.9.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/9e6b97bf-8caa-4aa1-9319-b93914935cbb)
4.8.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/61004385-a314-4a17-9305-a75406285ba0)

4.9.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/18ca6fd1-bd5c-46c3-b02d-70c04427ba08)
4.8.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/7e3544a7-3721-4974-8449-7d0101d4779b)

Disk
4.9.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/1c683c4f-ea59-4499-aedb-4f0738231261)
4.8.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/93d17e27-f968-435a-b04b-487dab31a3d6)

4.9.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/bc39133d-6411-4955-be33-ee231ddce8fb)
4.8.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/997c965d-5bef-4d6c-a885-8847efcb99b3)

4.9.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/d4e74d6f-5c6f-4cbf-abc3-77bb149fdd43)

4.8.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/8a533b97-a988-4a92-bec1-be85c71d4a46)

RSS, USS, VMS, PSS (some examples)
4.9.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/a556311b-b9d6-4f7a-929e-039a10ec73fd)

4.8.0 Manager
![image](https://github.com/wazuh/wazuh/assets/125690423/284e019a-1672-4fa9-a501-c4e7ed45ea46)

4.9.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/ad820d90-8fd9-401d-b78c-95783a3fe000)

4.8.0 Agent centOS
![image](https://github.com/wazuh/wazuh/assets/125690423/d37770ce-c796-49f3-adb3-f0c0ed8a0268)

4.9.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/94816e8c-00d4-4c1e-8c79-c10a8374b465)

4.8.0 Agent Ubuntu
![image](https://github.com/wazuh/wazuh/assets/125690423/7c086a44-f73e-4ae5-a606-65f5abbb9e52)

This pattern observed in several graphs must be evaluated to define whether it is an expected behavior or not.

**Comment by vikman90** [comment]
This issue is related to this wrong configuration in the test:

- https://github.com/wazuh/wazuh-jenkins/issues/6645
