### ISSUE TITLE
Upgrade 4.7 to 4.8 - Vulnerability Detection/Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: Timeout was reached

### ISSUE THREAD

**Issue by s3pwarwatwist** [wazuh/wazuh#24300]
Hi,

I have this error message in the logs after the server upgrade:
_wazuh-modulesd:content-updater: ERROR: Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: Timeout was reached_
Could someone explain to me what is the 'vulnerability_feed_manager' and how can I fix it ?
![2024-06-24 18_09_15-Window](https://github.com/wazuh/wazuh/assets/173711371/c76eda73-d19b-4119-9385-28e1721afe43)

**Comment by Dwordcito** [comment]
@s3pwarwatwist Do you have connectivity with cti.wazuh.com from your manager's server? Note that wazuh connects against that server to get updates to our own vulnerability feed.

@Damian-Mangold  Please look at this issue.

**Comment by Damian-Mangold** [comment]
Hi @s3pwarwatwist , the error message you are encountering:

```
wazuh-modulesd:content-updater: ERROR: Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: Timeout was reached
```

typically occurs when the Wazuh manager is unable to download the vulnerability content feed. This can happen for several reasons:

- Internet Connectivity Issues: the manager may not have a stable internet connection, or it may have lost connection during the download process.

- Access Blocked by Environment: there could be network restrictions or firewalls in place that prevent the manager from accessing the feed server (cti.wazuh.com).

---

## Steps to Troubleshoot and Resolve the Issue

### Check Internet Connectivity:
Verify that the Wazuh manager has a stable and reliable internet connection. You can do this by trying to access an external website from the server.

```
curl -I https://www.google.com
```

If this fails, you need to resolve the network connectivity issue.

### Verify Access to cti.wazuh.com:
Ensure that the Wazuh manager can reach the feed server.

```
curl -I https://cti.wazuh.com
```

If you are unable to access this URL, there might be network restrictions or firewalls blocking the connection. You will need to adjust your network settings or consult with your network administrator to allow access.

### Firewall and Proxy Settings:
Check if there are any firewall rules or proxy settings that might be blocking the connection. Ensure that outgoing connections to `cti.wazuh.com` are allowed.

### Retry the Update:
Once connectivity is confirmed, you should wait for the next retry to download content and check the status, or you can manually trigger the update process:

```
systemctl restart wazuh-manager
```

**Comment by s3pwarwatwist** [comment]
Hi,
The access to cti.wazuh.com is ok
![2024-06-26 11_55_33-Window](https://github.com/wazuh/wazuh/assets/173711371/f5d6af27-c861-4e6d-95ae-c90f0a2e1490)

I think my problem is coming from the proxy, beacuse before the upgrade i configured the proxy in the wazuh-manager.service file to get the updates to the vulnerability feed:
![2024-06-26 11_56_13-Window](https://github.com/wazuh/wazuh/assets/173711371/641ef100-082b-4c03-9b1f-7302d0b83708)
Now, if I do the same I lose the connection to the IndexerConnector so i commented the two lines:
![2024-06-26 16_49_51-10 94 8 216 (wazuh-server)](https://github.com/wazuh/wazuh/assets/173711371/35444262-6cf1-4645-8fbe-050ec5599596)
Where should I set up the proxy to unblock the acces to the vulnerability database?

Thank you very much for your support.

**Comment by Damian-Mangold** [comment]
Hi @s3pwarwatwist, please allow me to investigate how to properly configure this.

However, I have a question that I need to clarify: When you configure the proxy, are you able to access cti.wazuh.com but lose the connection to the indexer?

**Comment by s3pwarwatwist** [comment]
Hi,

I added the 2 proxy lines in the wazuh-control file and the error message is gone :
_export http_proxy=http://<proxy:port>
export https_proxy=http://<proxy:port>_

But yes, when i configure the proxy in the wazuh-manager.service file il lose the connexion to the indexer.

Thank you again for your support.

**Comment by Damian-Mangold** [comment]
Hi, 

Searching I have found other solutions and recommendations::

### Community Solution:
I found a similar issue reported by the community which also suggests a solution similar to yours. Please review the following link and see if it aligns with your environment:

[Wazuh GitHub Issue #1112](https://github.com/wazuh/wazuh/issues/1112)

### Using NO_PROXY Variable:

Another solution involves using the NO_PROXY environment variable to bypass the proxy for certain addresses, which might help in maintaining the connection to the indexer. You can find detailed steps in this guide:

[Setting up Wazuh Behind a Proxy](https://medium.com/@johan.ekenlycka/setting-up-wazuh-behind-a-proxy-64b31ef3ac2d)

Example configuration:

```
export http_proxy=http://proxy:port
export https_proxy=http://proxy:port
export NO_PROXY=localhost,127.0.0.1,.yourdomain.com
```

### Next Steps
If these solutions do not resolve your issue, I recommend providing more details about your environment to help diagnose the problem. Specifically, please share:

- The ossec.conf configuration file
- The environment details where Wazuh is running
- Any other relevant information or error messages

This additional information will assist us in reproducing the problem and finding a more tailored solution.

Thank you for your patience and cooperation. Looking forward to your response.
