### ISSUE TITLE
Incremental pattern of WazuhDB usage in FD graph in Wazuh Manager

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#24302]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-Alpha1 | Wazuh component | Manager | Packages | CentOS |

Testing [Release 4.9.0 - Alpha 1 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d) ](https://github.com/wazuh/wazuh/issues/24274)

The following incremental pattern of WazuhDB usage in FD graph in Wazuh Manager has been found.
4.9.0-Alpha1
![image](https://github.com/wazuh/wazuh/assets/125690423/01f410e7-7bd9-40da-b9fb-83a514a75aa7)

4.8.0-rc4
![image](https://github.com/wazuh/wazuh/assets/125690423/14d489bc-b23e-46d9-adff-996802950505)

In 4.8.0-rc4 the same pattern was also seen but less defined
I open this issue for analysis and evaluation of its relevance

**Comment by rauldpm** [comment]
Due to an error in the stress tests configuration, we need to check the configuration, I close this issue as not planned and will check the new stress tests results in Alpha 2 

- https://github.com/wazuh/wazuh-jenkins/issues/6645
