### ISSUE TITLE
Vulnerability Detection error in upgrade test related to missing file

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24326]
# Description

A Vulnerability Detection error has been found in the ossec.log of almost all 4.8.0 Wazuh manager upgrade tests to 4.9.0:

```
wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Couldn't open file
```

We need to investigate the origin of this error and determine if it is a component error or if we need to adapt our tests

## Related

- https://github.com/wazuh/wazuh/issues/24258#issuecomment-2191720357
- https://ci.wazuh.info/job/Test_upgrade_tier/2223/console
- https://ci.wazuh.info/job/Test_upgrade/135414/console (replay)

## Video

- https://github.com/wazuh/wazuh/issues/24326#issuecomment-2195317260

## Hypothesis

- https://github.com/wazuh/wazuh/issues/24326#issuecomment-2196802118

## Steps to reproduce it

  1. Install Wazuh manager 4.9.0
  2. Start Wazuh manager
  3. Wait to start to finish
  4. Wait for the decompress process to start (check the `/var/ossec/tmp directory`)
  5. While the file is being decompressed, run a `wazuh-control start`
  6. Check logs (can appear after some seconds)

**Comment by GabrielEValenzuela** [comment]
# Analysis


## Host OS 

```bash
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

## Steps

1. Install manager from [wazuh-manager_4.8.0-1_amd64.deb](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.8.0-1_amd64.deb)
2. Download Database 
3. Run `cp vd_1.0.0_vd_4.8.0.tar.xz /var/ossec/tmp`
4. Await until offsets are sync
5. Install manager 4.9.0 from the provided link
6. Check log

## Results

```bash
root@uadmin:/var/ossec# ./bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
wazuh-monitord is running...
wazuh-logcollector is running...
wazuh-remoted is running...
wazuh-syscheckd is running...
wazuh-analysisd is running...
wazuh-maild not running...
wazuh-execd is running...
wazuh-db is running...
wazuh-authd is running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid is running...
root@uadmin:/var/ossec# ./bin/wazuh-control info
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40901"
WAZUH_TYPE="server"
root@uadmin:/var/ossec# tail -f /var/ossec/logs/ossec.log
2024/06/26 17:31:47 sca: INFO: Security Configuration Assessment scan finished. Duration: 1 seconds.
2024/06/26 17:31:47 wazuh-modulesd:syscollector: INFO: Module started.
2024/06/26 17:31:47 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/06/26 17:31:47 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/06/26 17:31:47 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-uadmin', retrying until the connection is successful.
2024/06/26 17:31:47 wazuh-modulesd:vulnerability-scanner: INFO: Starting database file decompression.
2024/06/26 17:31:47 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/06/26 17:32:04 rootcheck: INFO: Ending rootcheck scan.
2024/06/26 17:32:20 wazuh-modulesd:vulnerability-scanner: INFO: Database decompression finished.
2024/06/26 17:32:21 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started
```

## Conclusion
Tests are failing, possibly due to an issue with the update offset process. Even though the database is downloaded, the offset needs to be updated.

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela I am not so sure about the conclusion

The log we are seeing is present in the Utils::ArchiveHelper::decompress function:
https://github.com/wazuh/wazuh/blob/76b73de76bb56295662325ce46f81ceefc925f33/src/shared_modules/utils/archiveHelper.hpp#L113-L117

Which is called here:
https://github.com/wazuh/wazuh/blob/76b73de76bb56295662325ce46f81ceefc925f33/src/wazuh_modules/vulnerability_scanner/src/vulnerabilityScannerFacade.cpp#L84-L85

If possible we should attempt to run the test in debug 2 to see this with better granularity

**Comment by GabrielEValenzuela** [comment]
# Update

## Host OS 

```bash
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```


```text
vCPU 1
vRAM 1048Mb
vDisk 45Gb
```

## Steps

1. Install manager from [wazuh-manager_4.8.0-1_amd64.deb](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.8.0-1_amd64.deb)
2. Optional: Connect an agent.
3. Optional: Await until offsets are synced
4. Install manager 4.9.0 from the provided link
5. Check log


<details><summary>Screenshots</summary>

![Screenshot from 2024-06-27 14-44-05](https://github.com/wazuh/wazuh/assets/27935340/602196e5-ef4c-40b1-97e0-25694282b89e)


![Screenshot from 2024-06-27 14-45-33](https://github.com/wazuh/wazuh/assets/27935340/5adcdb56-dd03-48a1-8c86-e9bb9ae6b99a)



</details>

**Comment by rauldpm** [comment]
I executed a build with a 300s sleep between the Wazuh manager 4.8.0 start and the 4.9.0 upgrade and the same error was obtained

https://ci.wazuh.info/job/Test_upgrade/135443/

**Comment by GabrielEValenzuela** [comment]
# Update

- Create PR with possible solution

**Comment by rauldpm** [comment]
Created a Wazuh manager package with the PR branch and executed new upgrade test, the following log has been obtained

```
2024/06/28 12:24:53 wazuh-modulesd:vulnerability-scanner: INFO: Starting vulnerability_scanner module.
2024/06/28 12:24:53 sca: INFO: Module started.
2024/06/28 12:24:53 sca: INFO: No policies defined. Exiting.
2024/06/28 12:24:53 wazuh-modulesd:router: INFO: Starting router module.
2024/06/28 12:24:53 wazuh-modulesd:content_manager: INFO: Starting content_manager module.
2024/06/28 12:24:53 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2024/06/28 12:24:53 wazuh-modulesd:database: INFO: Module started.
2024/06/28 12:24:53 wazuh-modulesd:download: INFO: Module started.
2024/06/28 12:24:53 wazuh-modulesd:control: INFO: Starting control thread.
2024/06/28 12:24:53 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2024/06/28 12:24:53 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2024/06/28 12:24:53 wazuh-modulesd:task-manager: INFO: (8200): Module Task Manager started.
2024/06/28 12:24:53 wazuh-modulesd:syscollector: INFO: Module started.
2024/06/28 12:24:53 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/06/28 12:24:53 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/06/28 12:24:53 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-73-102.ec2.internal', retrying until the connection is successful.
2024/06/28 12:24:53 wazuh-modulesd:vulnerability-scanner: INFO: Starting database file decompression.
2024/06/28 12:24:54 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/06/28 12:24:56 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2024/06/28 12:24:56 wazuh-syscheckd: INFO: FIM sync module started.
2024/06/28 12:25:12 wazuh-modulesd[5925] debug_op.c:116 at _log_function(): DEBUG: Logging module auto-initialized
2024/06/28 12:25:12 wazuh-modulesd[5925] main.c:77 at main(): DEBUG: Wazuh home directory: /var/ossec
2024/06/28 12:25:12 wazuh-modulesd[5925] wmodules-osquery-monitor.c:78 at wm_osquery_monitor_read(): DEBUG: Logpath read: /var/log/osquery/osqueryd.results.log
2024/06/28 12:25:12 wazuh-modulesd[5925] wmodules-osquery-monitor.c:84 at wm_osquery_monitor_read(): DEBUG: configPath read: /etc/osquery/osquery.conf
2024/06/28 12:25:12 wazuh-modulesd:router[5925] wm_router.c:98 at wm_router_read(): INFO: Loaded router module.
2024/06/28 12:25:12 wazuh-modulesd:content_manager[5925] wm_content_manager.c:87 at wm_content_manager_read(): INFO: Loaded content_manager module.
2024/06/28 12:25:16 wazuh-csyslogd: INFO: Remote syslog server not configured. Clean exit.
2024/06/28 12:25:17 wazuh-dbd: INFO: Database not configured. Clean exit.
2024/06/28 12:25:17 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
2024/06/28 12:25:17 wazuh-agentlessd: INFO: Not configured. Exiting.
2024/06/28 12:25:27 rootcheck: INFO: Ending rootcheck scan.
2024/06/28 12:25:42 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Couldn't open file during decompress. Error: Failed to open 'tmp/vd_1.0.0_vd_4.8.0.tar'
```

This matches the behavior reported in https://github.com/wazuh/wazuh/issues/24326#issuecomment-2195317260 video, the tar file disappears when being extracted and then VD cannot find the file

**Comment by sebasfalcone** [comment]
## Update
The hypothesis proposed by @rauldpm is true, the tar file is being removed if we call `wazuh-control start` when the xz decompression is taking place


### Solution
1. Add an exclusion for the decompressed tar file:
https://github.com/wazuh/wazuh/blob/76b73de76bb56295662325ce46f81ceefc925f33/src/init/wazuh-server.sh#L281-L282

2. Remove the tar file before starting the xz decompression (start with a clean environment):
https://github.com/wazuh/wazuh/blob/76b73de76bb56295662325ce46f81ceefc925f33/src/wazuh_modules/vulnerability_scanner/src/vulnerabilityScannerFacade.cpp#L64-L67

**Comment by GabrielEValenzuela** [comment]
# Update

- Changes done. Thanks @sebasfalcone for your help!

**Comment by rauldpm** [comment]
Created a RPM and DEB packages

- https://github.com/wazuh/wazuh/actions/runs/9715360078/job/26816538486
- https://github.com/wazuh/wazuh/actions/runs/9715364142/job/26816552488

Launched a Test_upgrade_tier from 4.8.0 to 4.9.0

- https://ci.wazuh.info/job/Test_upgrade/135520/console
- https://ci.wazuh.info/job/Test_upgrade/135519/console

Both tests passed the `test_check_log_errors` test but failed due to check-files, already reported

In any case, the test is going to be modified to wait until the feed has been completely processed (not only decompressed) as we need to be sure that no error is present in that stage
