### ISSUE TITLE
Upgrade docker and urllib3 dependencies

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#24329]
## Description

During the investigation in https://github.com/wazuh/wazuh/issues/24288, we found that the packages versions used for the `docker-listener` wodle are incompatible.

If we follow the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/container-security/monitoring-docker.html), the dependencies we end up with are:
- `docker==6.0.0`
- `urllib3=1.26.3`
- `requests==2.32.2` (it's installing the latest version by default)

The problem is that the docker version is not compatible with the requests version, it worker well until `2.29.0` and is now broken.

We should upgrade the docker version to `>=7.0.0` and urllib3 to `>=2.0.0` at least.

> [!Note]
> I've [tested](https://github.com/wazuh/wazuh/issues/24288#issuecomment-2192088896) the execution using the latest available versions and the wodle works as expected, but I haven't tested the functionality of other modules where upgrading `urllib3` could cause issues, so we should make sure to test this before choosing a version.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment]
Finally, this won't be included in 4.8.1. It was already fixed in 4.9.0.
