### ISSUE TITLE
FIM keeps alerting after removing a symbolic link

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2433]
## Bug report

**Wazuh version**
_3.8.0-3805_

**Install type**
_manager_

Bug description
----------------
Having the following configuration and a few symbolic links inside `/test:

```
<directories check_all="yes" realtime="yes" follow_symbolic_link="yes">/test</directories>
```

If we delete the links, we keep having alerts about the directories the links were pointing to.

Example
------------
```
/test
├── some_file
└── my_link -> /wazuh
```

If we delete `my_link` we should not receive any alerts from `/wazuh` neither in `frequency` nor in `realtime`.

**Comment by 0xN3utr0n** [comment]
Solved in #4347
