### ISSUE TITLE
agent key already in use and failed to sync agent

### ISSUE THREAD

**Issue by DokorWolf** [wazuh/wazuh#24338]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8 | Wazuh-manager | Manager | Packages | - |

Hello, since I updated my wazuh from 4.7.5 to 4.8 I'm struggling with "vulnerability detection". It works for some agents and not for other even if they are basically similar servers.
In the file ossec.log I have errors like this for differents agents :
wazuh-remoted: WARNING: Agent key already in use: agent ID '020'
or 
indexer-connector: WARNING: Failed to sync agent '083' with the indexer.

And I don't know why. The first error seems to happen for all my agents, but the second one it depends, sometimes all, sometimes few. These errors pop up every time an agent is restarting (the first error, not always the second one) or they happen randomly.

**Comment by DokorWolf** [comment]
If look at more verbose logs, I have logs like this : 

2024/07/01 08:20:45 wazuh-modulesd:vulnerability-scanner[743519] osScanner.hpp:346 at handleRequest(): DEBUG: Vulnerability scan for OS 'windows_server_2022' on Agent '012' has completed.
2024/07/01 08:20:45 wazuh-modulesd:vulnerability-scanner[743519] scanInventorySync.hpp:179 at handleRequest(): DEBUG: No changes in agent element key: 012_Microsoft Windows Server 2022 Standard
2024/07/01 08:20:45 wazuh-modulesd:vulnerability-scanner[743519] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 3 processed
2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '012' with the indexer.
2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:446 at operator()(): WARNING: Failed to sync agent '012' with the indexer.
2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:447 at operator()(): DEBUG: Error: No available server
2024/07/01 08:20:55 wazuh-modulesd:vulnerability-scanner[743519] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/01 08:20:55 wazuh-modulesd:vulnerability-scanner[743519] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '012' sync omitted due to abuse control.

**Comment by pereyra-m** [comment]
Hello @DokorWolf 

The first error message is related to the agents' connection and registration

> wazuh-remoted: WARNING: Agent key already in use: agent ID '020'

Could you provide your full `ossec.log` file to analyze all entries? Don't forget to remove any sensitive data.
It could be that your agents don't have valid keys, or have a connection issue in ports 1514/1515, etc. These agents might not be in active state due to these problems and can't be scanned if their inventories aren't synced.

About the second one

> indexer-connector: WARNING: Failed to sync agent '083' with the indexer.

There are two possible causes considering the rest of the DEBUG los you share
- `2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:447 at operator()(): DEBUG: Error: No available server`: if your indexer connector isn't in 'green' state or if you have a problem with the certs/credentials, the connection won't be possible and the agent vulnerabilities won't be indexed
- `2024/07/01 08:20:55 indexer-connector[743519] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '012' sync omitted due to abuse control.`: there is a cool-down time that prevents the same agent to re-sync with the indexer too often, this is to avoid overloading the indexer with requests. If everything is OK, the module will try again later.

Can you verify the health of your Wazuh Indexer cluster? For example: `GET _cluster/health`
Did you update the `wazuh-keystore` in the upgrade steps? Check the corresponding guide at https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html

Regards.

**Comment by troublestarter** [comment]
Same issue here

**Comment by pereyra-m** [comment]
Hi @troublestarter 

I recommended similar debugging steps. Please verify the connectivity of the agents in the mentioned ports, verify they are properly registered, and share the `ossec.log` file to be analyzed.

> When i reinstalled one agent with good way, i completly reinstalled it. Then:

Did you re-register the agent after the installation? Or re-utilized the old `client.keys.file`?
Also, ensure that the connection with the indexer works and that some time has passed to allow the cooldown time to expire.

**Comment by DokorWolf** [comment]
Hello @pereyra-m, thanks for your response ! 

*First* : 
> It could be that your agents don't have valid keys, or have a connection issue in ports 1514/1515, etc. These agents might not be in active state due to these problems and can't be scanned if their inventories aren't synced.

All my agents are active and I don't see any interruptions. I put some logs below from the ossec.log

*For the second problem* : 
> There are two possible causes considering the rest of the DEBUG los you share

Yesterday I added 3 indexers (so now I have 4) and it seemed to have resolved the problem. Since then I didn't see "indexer-connector: WARNING: Failed to sync agent '083' with the indexer." pop up again. Before my cluster's status was yellow but I didn't know why and now it's green.

*Ossec.log* : 
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '121' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '022'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '040'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '017'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '010'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '102'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '078'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '121' sync omitted due to abuse control.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '084'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '096'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '120'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '076'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '099'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '045'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '079'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '065'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '071' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '023'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '098'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '025' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '048'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '072'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '029'
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '073' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '075'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '101'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '019'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '070'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '027' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '110'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '043'
2024/07/02 07:50:42 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:42 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '082' with the indexer.
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '090'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '038'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '028'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '012'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '047'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '113'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '039'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '064'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '104'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '046'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '089'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '066'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '087'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '034'
2024/07/02 07:50:42 wazuh-remoted: WARNING: Agent key already in use: agent ID '060'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '037'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '095'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '081'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '018'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '024'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '051'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '106'
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] osScanner.hpp:244 at operator()(): DEBUG: etc...
... (more and more vulnerability scan)
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '044'
... (more and more vulnerability scan)
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] osScanner.hpp:244 at operator()(): DEBUG: etc...
... (more and more vulnerability scan)
2024/07/02 07:50:43 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '088' with the indexer.
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '021'
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '057'
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-modulesd:vulnerability-scanner[25195] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/07/02 07:50:43 wazuh-remoted: WARNING: Agent key already in use: agent ID '068'
2024/07/02 07:50:43 indexer-connector[25195] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '025' sync omitted due to abuse control.
2024/07/02 07:50:43 indexer-connector[25195] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '071' sync omitted due to abuse control.
2024/07/02 07:50:43 indexer-connector[25195] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '067' with the indexer.

**Comment by PUDPUD** [comment]
Hello,

Since upgrading to Wazuh 4.8, I've been experiencing persistent issues with agent synchronization. Here are the raw logs and output from my system which highlight the problems encountered:

```

root@fs-wazuh01:/var/ossec/logs# cat ossec.log  | grep "agent"
2024/07/03 00:11:55 wazuh-agentlessd: INFO: Not configured. Exiting.
2024/07/03 00:12:03 wazuh-modulesd[16051] main.c:95 at main(): DEBUG: Created new thread for the 'agent-upgrade' module.
2024/07/03 00:12:03 wazuh-modulesd:agent-upgrade[16051] wm_agent_upgrade_manager.c:69 at wm_agent_upgrade_start_manager_module(): INFO: (8153): Module Agent Upgrade started.
2024/07/03 00:12:03 wazuh-modulesd:database[16051] wm_database.c:275 at wm_sync_agents(): DEBUG: Synchronizing agents.
2024/07/03 00:12:03 wazuh-modulesd:database[16051] wm_database.c:282 at wm_sync_agents(): DEBUG: Agents synchronization completed.
2024/07/03 00:12:03 wazuh-modulesd:database[16051] wm_database.c:285 at wm_sync_agents(): DEBUG: wm_sync_agents(): 1.788 ms (7.267 clock ms).
2024/07/03 00:12:03 wazuh-modulesd:database[16051] wm_database.c:423 at wm_sync_legacy_groups_files(): DEBUG: Couldn't open directory 'queue/agent-groups': No such file or directory.
2024/07/03 00:12:03 wazuh-modulesd:database[16051] wm_database.c:698 at wm_inotify_setup(): DEBUG: wd_agents='1'
2024/07/03 00:12:03 sca[16051] wm_sca.c:2041 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:Defaults\s*\t*logfile=\S+)(# "sudo scp" or "sudo rsync" should be able to use your SSH agent.) -> 0
2024/07/03 00:12:03 sca[16051] wm_sca.c:2044 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:Defaults\s*\t*logfile=\S+)(# "sudo scp" or "sudo rsync" should be able to use your SSH agent.) -> 0
2024/07/03 00:12:03 sca[16051] wm_sca.c:1568 at wm_sca_check_file_contents(): DEBUG: (r:Defaults\s*\t*logfile=\S+)(# "sudo scp" or "sudo rsync" should be able to use your SSH agent.) -> 0
2024/07/03 00:12:03 sca[16051] wm_sca.c:2041 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:Defaults\s*\t*logfile=\S+)(# Ditto for GPG agent) -> 0
2024/07/03 00:12:03 sca[16051] wm_sca.c:2044 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:Defaults\s*\t*logfile=\S+)(# Ditto for GPG agent) -> 0
2024/07/03 00:12:03 sca[16051] wm_sca.c:1568 at wm_sca_check_file_contents(): DEBUG: (r:Defaults\s*\t*logfile=\S+)(# Ditto for GPG agent) -> 0
2024/07/03 00:12:05 wazuh-modulesd:vulnerability-scanner[16051] scanAgentList.hpp:247 at handleRequest(): DEBUG: Error executing query to fetch agent data for agents. Reason: DB query not synced.
2024/07/03 00:12:05 wazuh-modulesd:vulnerability-scanner[16051] scanOrchestrator.hpp:143 at operator()(): DEBUG: AgentReScanListException. Reason: Error executing rescan for multiple agents.
2024/07/03 00:12:11 sca[16051] wm_sca.c:1028 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 33066 'Ensure mail transfer agent is configured for local-only mode.'
2024/07/03 00:12:11 sca[16051] wm_sca.c:1303 at wm_sca_do_scan(): DEBUG: Result for check id: 33066 'Ensure mail transfer agent is configured for local-only mode.' -> 0
2024/07/03 00:12:11 wazuh-modulesd:syscollector[16051] logging_helper.c:40 at taggedLogFunction(): DEBUG: Sync sent: {"component":"syscollector_processes","data":{"attributes":{"argvs":"--watch","checksum":"96f0358303eecc785cbba27303c092d6693085ce","cmd":"/bin/systemd-tty-ask-password-agent","egroup":"root","euser":"root","fgroup":"root","name":"systemd-tty-ask","nice":0,"nlwp":1,"pgrp":15494,"pid":"15495","ppid":15494,"priority":20,"processor":2,"resident":3708,"rgroup":"root","ruser":"root","scan_time":"2024/07/02 22:12:11","session":3529,"sgroup":"root","share":714,"size":4079,"start_time":1719958308,"state":"S","stime":0,"suser":"root","tgid":15495,"tty":34819,"utime":0,"vm_size":16316},"index":"15495","timestamp":""},"type":"state"}
2024/07/03 00:12:11 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '021' with the indexer.
root@fs-wazuh01:/var/ossec/logs# cat ossec.log  | grep "Syncing agent"
2024/07/03 00:12:11 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '021' with the indexer.
2024/07/03 00:12:15 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '011' with the indexer.
2024/07/03 00:12:15 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '022' with the indexer.
2024/07/03 00:12:17 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '020' with the indexer.
2024/07/03 00:12:17 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '009' with the indexer.
2024/07/03 00:12:17 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '004' with the indexer.
2024/07/03 00:12:20 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '007' with the indexer.
2024/07/03 00:12:22 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '014' with the indexer.
2024/07/03 00:12:22 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '010' with the indexer.
2024/07/03 00:12:22 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '019' with the indexer.
2024/07/03 00:12:22 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '006' with the indexer.
2024/07/03 00:12:24 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '012' with the indexer.
2024/07/03 00:12:24 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '016' with the indexer.
2024/07/03 00:12:24 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '015' with the indexer.
2024/07/03 00:12:24 indexer-connector[16051] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '001' with the indexer.
root@fs-wazuh01:/var/ossec/logs# curl -u admin:hlWNf0C.7r+41xGyP.jZ0kqap+QOeWup --cacert /etc/filebeat/certs/root-ca.pem --cert /etc/filebeat/certs/filebeat.pem --key /etc/filebeat/certs/filebeat-key.pem "https://172.24.12.24:9200/_cluster/health"
{"cluster_name":"wazuh-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":698,"active_shards":698,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":10,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":98.58757062146893}root@fs-wazuh01:/var/ossec/logs# ^C


```


Additionally, here is the output from checking the health of our cluster:

`{"cluster_name":"wazuh-cluster","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":698,"active_shards":698,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":10,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":98.58757062146893}root@wazuh01:/var/ossec/logs#`

**Comment by pereyra-m** [comment]
Hello @PUDPUD 

I understand that the issue is similar, but if the user who created the issue has resolved the problem, please create another issue to keep the repository organized. 

Consider that you must have your cluster in `green` status because the **indexer_module** won't sync the vulnerabilities otherwise. It might be related to the `unassigned_shards` you show in the health command. 
You can't get more information here
https://opensearch.org/docs/latest/api-reference/cluster-api/cluster-allocation/

@DokorWolf 

Glad to know it's working

> Yesterday I added 3 indexers (so now I have 4) and it seemed to have resolved the problem. Since then I didn't see "indexer-connector: WARNING: Failed to sync agent '083' with the indexer." pop up again. Before my cluster's status was yellow but I didn't know why and now it's green.

Maybe adding a new node allowed the cluster to assign all remaining shards. If this happens again, I recommend the same endpoint I mentioned above to get more details.

**Comment by troublestarter** [comment]
> Hi @troublestarter
> 
> I recommended similar debugging steps. Please verify the connectivity of the agents in the mentioned ports, verify they are properly registered, and share the `ossec.log` file to be analyzed.
> 
> > When i reinstalled one agent with good way, i completly reinstalled it. Then:
> 
> Did you re-register the agent after the installation? Or re-utilized the old `client.keys.file`? Also, ensure that the connection with the indexer works and that some time has passed to allow the cooldown time to expire.

I have for some agent just update and for some unsintall and reinstall and some are completly new agents.

I have deployed the agent with the powershell script or with the linux steps. I didn't do anything more.

**Comment by pereyra-m** [comment]
Hi @troublestarter 

Please create another issue to keep the repository organized.
But it's very likely that the message ` WARNING: Failed to sync agent '00X' with the indexer.` is due to a cluster in 'yellow' status. You can follow the instructions I detailed above to get more details.

> I have for some agent just update and for some unsintall and reinstall and some are completly new agents.

In the new thread you could share more details about this, so we can solve the message `WARNING: Agent key already in use: agent ID '0XX`. It's important to know which agents are having trouble (the new ones, the re-installed ones, etc.) because if you have verified the connectivity, then it seems to be a registration key problem.

**Comment by sebasfalcone** [comment]
Inactive thread, please re open if necessary
