### ISSUE TITLE
FIM keeps alerting with follow_symbolic_link="no" 

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2434]
## Bug report

**Wazuh version**
_3.8.0-3805_

**Install type**
_manager_

Bug description
----------------
If we add a symbolic link in a monitored realtime directory like the following while FIM is running:
```
<directories check_all="yes" realtime="yes" follow_symbolic_link="no">/test</directories>
```

We're getting alerts from directories pointed by this links although the option `follow_symbolic_link` is disabled.

**Comment by albertomn86** [comment]
Solved https://github.com/wazuh/wazuh/pull/2466
