### ISSUE TITLE
Remove initialization from the indexer connector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24351]
## Description
This task focuses on removing the index initialization feature from the Indexer Connector module. The implementation for this feature will be moved to a new location: [Wazuh-Indexer Issue #256](https://github.com/wazuh/wazuh-indexer/issues/256).

## Objectives
- Remove the initialization code from the Indexer Connector module.

## Tasks
1. **Remove Initialization Code**
    - Safely remove the index initialization code from the module.
    - Ensure that the removal does not affect other functionalities of the module.

2. **Testing**
    - Conduct testing to ensure that the module functions correctly without the initialization feature.
    - Verify that the removal does not introduce new issues.

## Deliverables
- Updated Indexer Connector module with the index initialization feature removed.
- Test results confirming the module's stability and functionality post-removal.

## Dependencies
- Completion of the feature migration to [Wazuh-Indexer Issue #256](https://github.com/wazuh/wazuh-indexer/issues/256).

**Comment by MiguelazoDS** [comment]
# Update 

The indexer connector executes multiple tasks where the index name is required. As far as I understand, according to the information in the mentioned issues addressed by the indexer team, there's no longer an index with a hostname as a suffix. The index name must be set by default without the possibility to modify it, since that flexibility may create multiple indices every time the indexer-connector needs to index the vulnerabilities data. We can also delete the created index manually through the IP, so the module must be capable of recreating it.

**Comment by MiguelazoDS** [comment]
## Update 24/07 

There's a bad approach to the implementation requested by this issue. There's no initialization of any kind in this module. What I see is that the index pattern currently mentioned in the issues above is still `wazuh-states-vulnerabilities-*` and that does not match the discussed name for index `wazuh-states-vulnerabilities`. I'll assume the template as well as the aforementioned index is already created in the indexer. The module will only use the index name for its operations.

**Comment by MiguelazoDS** [comment]
## Update 

I found that the indexerConnector component tests are not considered in the coverage report. Figuring out why... 

it successfully detect the .gcda files 

```console
Scanning build/tests/unit for .gcda files ...
Found 3 data files in build/tests/unit
Processing indexer_connector_unit_tests.dir/serverSelector_test.cpp.gcda
Processing indexer_connector_unit_tests.dir/main.cpp.gcda
Processing indexer_connector_unit_tests.dir/monitoring_test.cpp.gcda
Excluded data for 109 files due to include/exclude options
Scanning build/tests/component for .gcda files ...
Found 2 data files in build/tests/component
Processing indexer_connector_component_tests.dir/main.cpp.gcda
Processing indexer_connector_component_tests.dir/indexerConnector_test.cpp.gcda
Excluded data for 119 files due to include/exclude options
Finished .info-file creation
```

But the generated coverage.info file does not have indexerConnector information 

```console
root@jammy:/home/vagrant/wazuh/src/shared_modules/indexer_connector# grep "shared_modules" build/coverage.info
SF:/home/vagrant/wazuh/src/shared_modules/indexer_connector/src/monitoring.hpp
SF:/home/vagrant/wazuh/src/shared_modules/indexer_connector/src/serverSelector.hpp
SF:/home/vagrant/wazuh/src/shared_modules/indexer_connector/src/monitoring.hpp
```
 
![image](https://github.com/user-attachments/assets/60cc613e-3d88-4c92-92c4-a6df60f6714a)
