### ISSUE TITLE
Vulnerability Detection scanner log messages do not end with a period

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24368]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.9.0-alpha1 | wazuh-modulesd:vulnerability-scanner| Manager | Packages | All |

# Description

The messages reported in the ossec.log file end with a period (`.`), and some Vulnerability Scanner messages do not, we need to check this as we need to maintain a log integrity report.

```
2024/07/01 10:11:47 wazuh-modulesd:router: INFO: Loaded router module.
2024/07/01 10:11:47 wazuh-modulesd:content_manager: INFO: Loaded content_manager module.
2024/07/01 10:11:56 wazuh-csyslogd: INFO: Remote syslog server not configured. Clean exit.
2024/07/01 10:11:56 wazuh-dbd: INFO: Database not configured. Clean exit.
2024/07/01 10:11:56 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
2024/07/01 10:11:56 wazuh-agentlessd: INFO: Not configured. Exiting.
2024/07/01 10:13:35 wazuh-modulesd:vulnerability-scanner: INFO: Database decompression finished.
2024/07/01 10:13:36 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started
2024/07/01 10:13:37 wazuh-modulesd:vulnerability-scanner: INFO: Initiating update feed process
```

**Comment by sebasfalcone** [comment]
## Improvements
@MiguelazoDS lets add some improvements on the logging if we can, just to justify adding dots on the logs

Like this one (print error string instead of errno):
https://github.com/wazuh/wazuh/blob/fcbc1199ab7067d177e07c2a1d8ccf38c6d9b47d/src/shared_modules/utils/xz/fileDataCollector.hpp#L74-L80
