### ISSUE TITLE
Week 27 - Check Wazuh compatibility with new OSs versions #24128

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh#24370]
|Week|Previous issue|
|---|---|
|27|https://github.com/wazuh/wazuh/issues/23838|

## Description
This issue is a weekly reminder to check for new versions of the operating systems supported by Wazuh. In this way, we will be attentive to the new betas to check that there is no problem with the packages and the operation of Wazuh.

Frequency is estimated based on previous release dates. Use it just as a guideline.

Priority is based upon release notes content & minor/major released. Release notes should be read and based on the changes informed, a criticality level should be chosen to better adjust the testing level to be performed.

If there is a new beta or release that has not been tested, it will be necessary to build an environment with that new version of the OS in question and test it with an updated Wazuh package. Basic tests to be performed should include agent installation, server installation (for server OSs), and checking every module in Wazuh. For this purpose, we must open a specific issue for each new minor/major version found, and test the following points, making sure that Wazuh works correctly:

Agent and server (if possible) installations.
O.S. reporting in the interface.
WPK installation/upgrade / uninstall/upgrade.
Enrollment and connectivity with the manager.
FIM: Real-time and who-data engines (if available).
SCA: Policy support.
Vulnerability Detector: Vulnerability support.
Syscollector: Complete inventory.
Active Response: port blocking.
Log capture (Eventchannel for Windows and ULS for macOS).

Each OS must have one of the following check statuses:
 
| Check | Description |
|:-:|--------------------------------------------|
| 🟡      | New OS version has been found. |
| ⚫      | No new  OS version has been found. |

Check the current table: 

| OS | Last Release | Release date | Last Pre-release | Pre-release Date| Frequency | Links | Check | Issue related |
|-|-|-|-|-|-|-|-|-|
| Ubuntu                         | Ubuntu 24.04 | 05/23/2024 | Ubuntu 24.10 | 10/10/2024 | Semester   | [Releases](https://wiki.ubuntu.com/Releases) / [Pre-releases](https://wiki.ubuntu.com/Releases#:~:text=mailing%20list.-,Future,-Version)| ⚫ | - |
| Debian                          | Debian 12.6                    | 29/06/2024 | Debian 13 and Debian 14 |TBD | Annual      | [Releases](https://www.debian.org/releases/) / [Release notes](https://wiki.debian.org/DebianReleases)| 🟡 | https://github.com/wazuh/wazuh/issues/24371 |
| Raspbian                      | Raspberry Pi OS 12 (bookworm)| 12/05/2023 |  | TBD | +3 Monthly | [Releases](https://www.raspberrypi.com/software/operating-systems/) / Pre-releases depend on Debian Schedule | ⚫ | - |
| Fedora                          |  Fedora 40 | 05/23/2024 |  Fedora 41 |15/10/2024 |  Semester   | [Releases](https://docs.fedoraproject.org/en-US/releases/) / Check **Development and Upcoming Releases** to find Pre-releases | ⚫ | - |
| CentOS Stream            | CentOS Stream 10              | 06/06/2024 | | TBD |  +1 year     | [Releases](https://centos.org/centos-stream/) / [Pre-release](https://blog.centos.org/category/announcement/) | ⚫  | - |
| Red Hat Enterprise Linux      | Red Hat Enterprise Linux 9.4 | 05/06/2024 | | TBD |  Semester    | [Releases](https://developers.redhat.com/products/rhel/overview) / Also contains pre-release information | ⚫ | - |
| Rocky Linux                  | Rocky Linux 9.4                     | 05/23/2024 | | TBD | Monthly    | [Releases](https://rockylinux.org/) / [Pre-release](https://forums.rockylinux.org/) | ⚫ | - |
| AlmaLinux                     | AlmaLinux 9.4                     | 05/06/2024 | | TBD | Semester    | [Releases](https://wiki.almalinux.org/release-notes/) / Also contains pre-release information | ⚫ | - |
| SUSE Linux Enterprise         | SUSE Linux Enterprise 15 SP6 | 10/19/2023 | | TBD | +1 year    |  [Releases](https://www.suse.com/releasenotes/index.html) / [Pre-releases](https://www.suse.com/es-es/betaprogram/releases/)| ⚫  | - |
| OpenSUSE                      | OpenSUSE Leap 15.6 | 07/01/2024 | | TBD | Yearly     |  [Releases](https://get.opensuse.org/) / Also contains pre-release information | 🟡 | https://github.com/wazuh/wazuh/issues/24372 |
| Oracle Linux                  | Oracle Linux 9.4             | 05/29/2024 |  |TBD | Semester   |  [Releases](https://docs.oracle.com/en-us/iaas/oracle-linux/release-notes/index.htm) | ⚫  | - |
| Amazon Linux                  | Amazon Linux 2023 - 2023.5.20240624   | 07/01/2024  || TBD | Biweekly   | [Releases](https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html) / No pre-release info since it's release every 2 weeks | 🟡 | https://github.com/wazuh/wazuh/issues/24373 |
| Windows                       | Windows 11 23H2              | 07/01/2024 | | TBD | Semester   |  [Releases](https://learn.microsoft.com/en-us/windows/release-health/) / [Pre-release](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso) requires Windows insider registration | ⚫ | - |
| Windows Server                | Windows Server 2022          | 07/01/2024 | Windows Server 2025 | TBD | +1 year    |  [Releases](https://learn.microsoft.com/en-us/windows-server/get-started/windows-server-release-info) / [Pre-release](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewserver) requires Windows insider registration / [Latest build in Windows 11](https://www.microsoft.com/en-us/windowsinsider/) | ⚫ | - |
| macOS 13                      | macOS Ventura 13.5  | 03/14/2024 | - | TBD | Variable   |  [Releases](https://developer.apple.com/documentation/macos-release-notes/macos-13_5-release-notes) / Also contains pre-release information | ⚫ | - |
| macOS 14                      | macOS Sonoma 14.5 | 07/01/2024 | macOS Sonoma 14.6 Beta | TBD | Yearly     |  [Releases](https://developer.apple.com/documentation/macos-release-notes/macos-14-release-notes) / Also contains pre-release information| ⚫  | - |
| macOS 15                      | - | TBD | macOS Sequoia 15 Beta 2 | TBD | Yearly     |  [Releases](https://developer.apple.com/documentation/macos-release-notes/macos-15-release-notes) / Also contains pre-release information| ⚫   | - |
| Solaris                       | Solaris 11.4                 | 05/25/2023 | | TBD | +1 year    |  [Releases](https://support.oracle.com/knowledge/Sun%20Microsystems/2433412_1.html) / [Pre-releases](https://blogs.oracle.com/solaris/) | ⚫ | - |
| AIX                           | AIX 7.3 TL2                  | 04/28/2023 | | TBD | Annual     |  [Releases](https://www.ibm.com/support/pages/aix-support-lifecycle-information) / [Pre-releases](https://community.ibm.com/community/user/power/communities/community-home/recent-community-blogs?communitykey=daa942cb-b783-4fd3-ba27-a2d7462f9530)| ⚫ | - |
| HPUX                          | HP-UX 11i v3                 | 05/xx/2023 | | TBD | Monthly    |  [Releases](https://www.hpe.com/global/softwarereleases/releases-media2/HPEredesign/pages/library.html) / No pre-release info available | ⚫ | - |

**Comment by MarcelKemp** [comment]
LGTM.
