### ISSUE TITLE
How to add a custom decoder without overridding the full decoder?

### ISSUE THREAD

**Issue by dlundgren** [wazuh/wazuh#24380]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.7.4 | Rules/Decoders | New/Error/Improve |

## Description
I am trying to add the following decoder to get the event id from Sonicwall logs in `/var/ossec/etc/decoders/sonicwall.xml`, however it's not decoding. If I put the decoder in the `0295-sonicwall_decoders.xml` file near the top it does work, if I add it to the bottom it doesn't work.

```
<decoder name="sonicwall-fields">
  <parent>sonicwall</parent>
  <regex> m=(\d+)</regex>
  <order>eventId</order>
</decoder>
```

I'm seeking to understand the following:
* Why does this decoder only work near the top of the 0295 sonicwall decoder file, and no where else in the file?
* Why does the decoder not work in a custom file with just itself?
* Without duplicating the 0295 sonicwall decoders how can we add custom decoding?

### Current results
```
**Phase 2: Completed decoding.
	name: 'sonicwall'
	action: 'Administrator login denied due to bad credentials'
	dstip: '1.1.1.1'
	dstport: '50000'
	srcip: '2.2.2.2'
	srcport: '36701'
	status: '1'
```

### Expected results
```
**Phase 2: Completed decoding.
	name: 'sonicwall'
	action: 'Administrator login denied due to bad credentials'
	dstip: '1.1.1.1'
	dstport: '50000'
	eventId: '30'
	srcip: '2.2.2.2'
	srcport: '36701'
	status: '1'
```

### Log source / integration
Sonicwall decoder tests from this repository

### Log examples
```
id=firewall sn=000SERIAL time="2007-01-03 14:48:07" fw=1.1.1.1 pri=1 c=32 m=30 msg="Administrator login denied due to bad credentials" n=7 src=2.2.2.2:36701:WAN dst=1.1.1.1:50000:WAN```

### Threats and compliance
Sonicwall publishes a [list of log events](https://www.sonicwall.com/techdocs/pdf/sonicos-6-5-4-log-events-reference-guide.pdf) that can be used to link to the various compliance frameworks for reporting.

**Comment by JcabreraC** [comment]
his issue will not be addressed. We are currently developing a new analysis engine that significantly changes the way rules and decoders are created.

For more information about the new engine, please refer to issue #23577.
