### ISSUE TITLE
Error update in wazuh (Python 27, CentOS 6.10)

### ISSUE THREAD

**Issue by crakerkai** [wazuh/wazuh#2438]
Hello,

Today, I met a issus like that when I try to upgrade ruleset wazuh. Please help me to fix it

[root@WAZUH bin]# ./update_ruleset
Traceback (most recent call last):
  File "./update_ruleset", line 31, in <module>
    from wazuh.cluster.cluster import read_config
  File "./../framework/wazuh/__init__.py", line 7, in <module>
    from wazuh.utils import execute
  File "./../framework/wazuh/utils.py", line 7, in <module>
    from wazuh.database import Connection
  File "./../framework/wazuh/database.py", line 10, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
[root@WAZUH bin]#

Thanks,

**Comment by crakerkai** [comment]
Hello, 

The problem is pysqlite was error or unavailable, So I install it and re-enable it again. Can do the following commands:
pip install pysqlite
./configure --enable-loadable-sqlite-extensions && make && sudo make install

And then I have another problem and  I feel that there are people like me but I have not finalized at #[1115 ](https://github.com/wazuh/wazuh/issues/1115)
Please help me to fix it.

Thanks,

**Comment by vikman90** [comment]
Hi @crakerkai,

Sorry for the late reply. The Wazuh Framework (the internal Python library used by the API and some other tools like _upgrade_ruleset_) requires Python 2.7.

I guess you installed the package `python27`. That package includes the Python library "sqlite3". However, it depends on the binary library SQLite3 with minimal version 3.6.20. Wazuh includes that library in the installation.

I tried to follow these steps:

```shellsession
# Install Python 2.7
$ yum install -y centos-release-scl
$ yum install -y python27

# Update ruleset. It requires Python 2.7
$ scl enable python27 bash
$ /var/ossec/bin/update_ruleset

wazuh.exception.WazuhException: Error 2001 - Incompatible version of SQLite: 3.6.20
Try to export the internal SQLite library:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/framework/lib
```

Following the instructions by the message:

```shellsession
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/framework/lib
# /var/ossec/bin/update_ruleset
### Wazuh ruleset ###

The following rules will be updated:
	0565-ms_ipsec_rules_json.xml
You already have the latest version of rootchecks.
You already have the latest version of decoders.

OSSEC requires a restart to apply changes.
Do you want to restart OSSEC now? [y/N]:
Do not forget to restart OSSEC to apply changes.

Ruleset v3.8.2 updated to v3.8.2 successfully
```

Do these steps work your you?

Hope it helps.
Best regards.

**Comment by crakerkai** [comment]
Hi @vikman90 ,

Yes, It worked. Thanks so much :)

Best regards,
Pm

**Comment by vikman90** [comment]
@crakerkai thank you for letting us know.

Happy to help!
Best regards.
