### ISSUE TITLE
Spike: Fields used by vulnerability detector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#24392]
## Description

This issue aims to investigate the current vulnerability detector module to check what are the fields used in the vulnerability detector come from inventories.

The need for this issue is because with the changes that will come from the agent(https://github.com/wazuh/wazuh-indexer/issues/282), the model will possibly change, as the model will change, how the information comes from a source will also be affected.

## Expected
- Hotfix inventory fields used by VD.
- Package Inventory used by VD.
- OS inventory used by VD.
 
 
 
Consider that the model tends to be reduced, therefore it is imperative to qualify that it is really used.

**Comment by MiguelazoDS** [comment]
Most of the information (if not all) can be obtained from this class

https://github.com/wazuh/wazuh/blob/4331840578da7fb09df8d10de06e3bd39402db07/src/shared_modules/utils/wazuhDBQueryBuilder.hpp#L21

That class is responsible for formatting different queries to communicate with the Wazuh-DB module to retrieve information about the different inventory providers.

This wrapper class allows us to perform general queries that can retrieve all fields from a specific table but for vulnerability detector the ones used are listed here

| ID | Queries                           | Location                                |
|----|-----------------------------------|-----------------------------------------|
| 1  | global get-all-agents context     | buildAllAgentListContext.hpp            |
| 2  | global get-agent-info <agent_id>  | buildSingleAgentListContext.hpp         |
| 3  | agent <agent_id> osinfo get       | osDataCache.hpp, scanAgentList.hpp      |
| 4  | agent <agent_id> hotfix get       | osScanner.hpp, remediationDataCache.hpp |
| 5  | agent <agent_id> package get      | scanAgentList.hpp                       |

Translation to SQLite query

| ID | WDB Queries                       | SQLite Queries                          |
|----|-----------------------------------|-----------------------------------------|
| 1  | global get-all-agents context     | SELECT id,version,name,ip FROM agent    |
| 2  | global get-agent-info <agent_id>  | SELECT * FROM agent WHERE id = ?        |
| 3  | agent <agent_id> osinfo get       | SELECT * FROM sys_osinfo                |
| 4  | agent <agent_id> hotfix get       | SELECT HOTFIX FROM SYS_HOTFIXES         |
| 5  | agent <agent_id> package get      | SELECT DISTINCT NAME, VERSION, ARCHITECTURE, VENDOR, FORMAT, SOURCE, CPE, MSU_NAME, ITEM_ID, DESCRIPTION, LOCATION, SIZE, INSTALL_TIME FROM SYS_PROGRAMS |

| TABLE        | DATABASE | FIELDS                | NOTES  |
|--------------|----------|-----------------------|--------|
| agent        | Global   | id, version, name, ip | Although for a single agent we are getting all fields, we only use 4 https://github.com/wazuh/wazuh/blob/343ff10cf8873f0c8650fb3047861ed020f77d79/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/buildSingleAgentListContext.hpp#L70-L74 |
| sys_osinfo   | Agent    | hostname, architecture, os_name, os_codename, os_major, os_minor, os_patch, os_build, os_platform, os_version, os_release, os_display_version, sysname, version, release, cpe_name | https://github.com/wazuh/wazuh/blob/f4a93c33751482e766d2aaed8d5d3a9f3048728c/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/osDataCache.hpp#L73-L87|
| sys_hotfixes | Agent    | hotfix                | - |
| sys_programs | Agent    | name,version,architecture,vendor,format,source,cpe,msu_name,item_id,description,location,size,install_time | - |

**Comment by sebasfalcone** [comment]
Thanks for the analysis @MiguelazoDS!

## Conclusion

> [!NOTE]
> The charts below shows which fields should be preserved, and from which DB and table obtain them


|   DB   |    Table     |       Field        |
|--------|--------------|--------------------|
| Global | agent        | id                 |
|        |              | version            |
|        |              | name               |
|        |              | ip                 |
|        |              |                    |
| Agent  | sys_osinfo   | hostname           |
|        |              | architecture       |
|        |              | os_name            |
|        |              | os_codename        |
|        |              | os_major           |
|        |              | os_minor           |
|        |              | os_patch           |
|        |              | os_build           |
|        |              | os_platform        |
|        |              | os_version         |
|        |              | os_release         |
|        |              | os_display_version |
|        |              | sysname            |
|        |              | version            |
|        |              | release            |
|        |              | cpe_name           |
|        |              |                    |
| Agent  | sys_hotfixes | hotfix             |
|        |              |                    |
| Agent  | sys_programs | name               |
|        |              | version            |
|        |              | architecture       |
|        |              | vendor             |
|        |              | format             |
|        |              | source             |
|        |              | cpe                |
|        |              | msu_name           |
|        |              | item_id            |
|        |              | description        |
|        |              | location           |
|        |              | size               |
|        |              | install_time       |

**Comment by Dwordcito** [comment]
We expect all the fields used by the VD engine, such as msu_name and CPE from sys_programs, are not used in the code.

**Comment by MiguelazoDS** [comment]
https://github.com/wazuh/wazuh/blob/4396d58d336276012e8e0788d47908f31cdc9310/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanAgentList.hpp#L143-L158 

| FIELDS | 
|--------|
| architecture, checksum, description, format, groups, install_time, item_id, location, multiarch, name, priority, scan_time, size, source, vendor, version |

**Comment by sebasfalcone** [comment]
@Dwordcito Updated required fields

**Comment by Dwordcito** [comment]
Thanks for the analysis.
