### ISSUE TITLE
Silent Event Discard in Wazuh-Analysisd Archive Log

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#24396]
| Wazuh version | Component       | Install type | Install method | Platform |
|---------------|-----------------|--------------|----------------|----------|
| current 4.x        | Wazuh-Analysisd | Manager      | Any            | Linux    |

### Description

Under certain conditions, Wazuh-Analysisd may silently discard events that should be archived in `archive.json` or `.log`. These events are neither logged nor visible in the statistics, leading to potential data loss without adequate notification to the user.

### Issue Detail

The core of the issue arises when the `archive log` queue reaches its capacity. At this point, any incoming events are discarded, and the system logs a warning in `ossec.log`. However, this warning is issued only once per thread after which, further overflows of the queue are not logged until the service is restarted. This behavior results in the potential for significant data loss without continuous alerts to indicate such a condition post-initial warning.

**Log Example:**
```
XXXX/XX/XX XX:XX:XX wazuh-analysisd: WARNING: Archive writer queue is full. XX
```

### Code Analysis

The issue is evident in the following segment of the code, where it is clear that when the queue is full, the event is simply discarded without any attempt to log the incident or record statistics for these discarded events:

https://github.com/wazuh/wazuh/blob/f82944723acac543ef9ee61fb22195742ea9a51f/src/analysisd/analysisd.c#L2204-L2211

### Impact

This only occurs in high load scenarios with archiving enabled, but leading to possible gaps in log archiving without sufficient notice to administrators.

**Comment by JcabreraC** [comment]
This issue has been resolved with the release of the new Wazuh engine in version 5.0.0.

The development and details of this fix can be tracked in the following GitHub issue: [#23577](https://github.com/wazuh/wazuh/issues/23577).
