### ISSUE TITLE
Agent for Windows failed to compile on Ubuntu 22.04 x86_64

### ISSUE THREAD

**Issue by ZeroLiShu** [wazuh/wazuh#24408]
|Wazuh version|Component|Install type|Install method|Platform|
|4.6.0|winagent|Agent|Sources|Ubuntu 22.04 x86_64|

Hi,

I tried to compile agent for windows on Ubuntu 22.04 x86_64, but failed in wazuh_db/schema.o.

I used the command as follows:
make deps TARGET=winagent
make TARGET=winagent

The build log is like this:

Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
make libwazuhext.lib CFLAGS="-DCLIENT -D_POSIX_C_SOURCE -DWIN32 -DPSAPI_VERSION=1" LIBS="-lwsock32 -lws2_32 -lcrypt32"
make[1]: Entering directory '/home/lishu/wazuh-4.6.0/src'
Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
make[1]: 'libwazuhext.lib' is up to date.
make[1]: Leaving directory '/home/lishu/wazuh-4.6.0/src'
make win32/syscollector win32/syscheck CFLAGS="-DCLIENT -D_POSIX_C_SOURCE -DWIN32 -DPSAPI_VERSION=1"
make[1]: Entering directory '/home/lishu/wazuh-4.6.0/src'
Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
cd shared_modules/dbsync/ && mkdir -p build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix   -DRESOURCE_OBJ=win32/version-dll.o .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build
make[2]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
make[3]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
Consolidate compiler generated dependencies of target dbsync
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
[ 60%] Built target dbsync
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
Consolidate compiler generated dependencies of target dbsync_example
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
[ 80%] Built target dbsync_example
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
Consolidate compiler generated dependencies of target dbsync_test_tool
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
[100%] Built target dbsync_test_tool
make[3]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
make[2]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/dbsync/build'
cd shared_modules/rsync/ &&  mkdir -p build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix   -DRESOURCE_OBJ=win32/version-dll.o .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build
make[2]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
make[3]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
Consolidate compiler generated dependencies of target rsync
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
[ 37%] Built target rsync
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
Consolidate compiler generated dependencies of target rsync_test_tool
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
[100%] Built target rsync_test_tool
make[3]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
make[2]: Leaving directory '/home/lishu/wazuh-4.6.0/src/shared_modules/rsync/build'
cd data_provider/ && mkdir -p build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix    -DRESOURCE_OBJ=win32/version-dll.o .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishu/wazuh-4.6.0/src/data_provider/build
make[2]: Entering directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
make[3]: Entering directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
Consolidate compiler generated dependencies of target sysinfo
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
[ 75%] Built target sysinfo
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
Consolidate compiler generated dependencies of target sysinfo_test_tool
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
[100%] Built target sysinfo_test_tool
make[3]: Leaving directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
make[2]: Leaving directory '/home/lishu/wazuh-4.6.0/src/data_provider/build'
cd wazuh_modules/syscollector/ && mkdir -p build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix   -DRESOURCE_OBJ=win32/version-dll.o .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build
make[2]: Entering directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
make[3]: Entering directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
Consolidate compiler generated dependencies of target syscollector
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
[ 66%] Built target syscollector
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
Consolidate compiler generated dependencies of target syscollector_test_tool
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
[100%] Built target syscollector_test_tool
make[3]: Leaving directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
make[2]: Leaving directory '/home/lishu/wazuh-4.6.0/src/wazuh_modules/syscollector/build'
cd syscheckd/ && mkdir -p build && cd build && cmake -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc -DCMAKE_CXX_COMPILER=i686-w64-mingw32-g++-posix   -DRESOURCE_OBJ=win32/version-dll.o .. && make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lishu/wazuh-4.6.0/src/syscheckd/build
make[2]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
make[3]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
Consolidate compiler generated dependencies of target fimdb
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
[ 20%] Built target fimdb
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
Consolidate compiler generated dependencies of target wazuh-syscheckd
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
[ 58%] Built target wazuh-syscheckd
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
Consolidate compiler generated dependencies of target wazuh-syscheckd-event
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
[ 95%] Built target wazuh-syscheckd-event
make[4]: Entering directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
Consolidate compiler generated dependencies of target fimdb_test_tool
make[4]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
[100%] Built target fimdb_test_tool
make[3]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
make[2]: Leaving directory '/home/lishu/wazuh-4.6.0/src/syscheckd/build'
make[1]: Leaving directory '/home/lishu/wazuh-4.6.0/src'
make win32/wazuh-agent.exe win32/wazuh-agent-eventchannel.exe win32/manage_agents.exe win32/setup-windows.exe win32/setup-syscheck.exe win32/setup-iis.exe win32/os_win32ui.exe win32/agent-auth.exe CFLAGS="-DCLIENT -D_POSIX_C_SOURCE -DWIN32 -DPSAPI_VERSION=1" LIBS="-lwsock32 -lwevtapi -lshlwapi -lcomctl32 -ladvapi32 -lkernel32 -lpsapi -lgdi32 -liphlpapi -lws2_32 -lcrypt32 -lwintrust"
make[1]: Entering directory '/home/lishu/wazuh-4.6.0/src'
Makefile:2515: warning: overriding recipe for target 'win32/ui_resource.o'
Makefile:2455: warning: ignoring old recipe for target 'win32/ui_resource.o'
Makefile:2518: warning: overriding recipe for target 'win32/auth_resource.o'
Makefile:2458: warning: ignoring old recipe for target 'win32/auth_resource.o'
    [34mCC[0m [33mwazuh_db/schema_agents.o[0m
<stdin>:1:33: warning: missing terminating " character
<stdin>:1:33: error: missing terminating " character
<stdin>:2:4: error: 'SQL' undeclared here (not in a function)
<stdin>:2:8: error: expected ',' or ';' before 'Schema'
<stdin>:12:40: warning: multi-character character constant [-Wmultichar]
<stdin>:12:48: warning: character constant too long for its type
<stdin>:12:64: warning: character constant too long for its type
<stdin>:13:45: warning: multi-character character constant [-Wmultichar]
<stdin>:13:51: warning: multi-character character constant [-Wmultichar]
<stdin>:15:37: warning: character constant too long for its type
<stdin>:15:46: warning: character constant too long for its type
<stdin>:34:1: error: unknown type name 'CREATE'
<stdin>:34:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:34:14: error: unknown type name 'IF'
<stdin>:35:1: error: unknown type name 'CREATE'
<stdin>:35:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:35:14: error: unknown type name 'IF'
<stdin>:36:1: error: unknown type name 'CREATE'
<stdin>:36:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:36:14: error: unknown type name 'IF'
<stdin>:38:1: error: unknown type name 'CREATE'
<stdin>:38:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:38:14: error: unknown type name 'IF'
<stdin>:47:1: error: unknown type name 'CREATE'
<stdin>:47:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:47:14: error: unknown type name 'IF'
<stdin>:48:1: error: unknown type name 'CREATE'
<stdin>:48:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:48:14: error: unknown type name 'IF'
<stdin>:50:1: error: unknown type name 'CREATE'
<stdin>:50:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:50:14: error: unknown type name 'IF'
<stdin>:67:47: error: empty character constant
<stdin>:72:1: error: unknown type name 'CREATE'
<stdin>:72:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:72:14: error: unknown type name 'IF'
<stdin>:74:1: error: unknown type name 'CREATE'
<stdin>:74:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:74:14: error: unknown type name 'IF'
<stdin>:79:40: warning: character constant too long for its type
<stdin>:79:51: warning: character constant too long for its type
<stdin>:79:63: warning: character constant too long for its type
<stdin>:79:74: warning: character constant too long for its type
<stdin>:79:92: warning: character constant too long for its type
<stdin>:81:47: error: empty character constant
<stdin>:86:1: error: unknown type name 'CREATE'
<stdin>:86:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:86:14: error: unknown type name 'IF'
<stdin>:88:1: error: unknown type name 'CREATE'
<stdin>:88:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:88:14: error: unknown type name 'IF'
<stdin>:95:47: error: empty character constant
<stdin>:100:1: error: unknown type name 'CREATE'
<stdin>:100:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:100:14: error: unknown type name 'IF'
<stdin>:102:1: error: unknown type name 'CREATE'
<stdin>:102:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:102:14: error: unknown type name 'IF'
<stdin>:119:47: error: empty character constant
<stdin>:122:37: error: empty character constant
<stdin>:126:1: error: unknown type name 'CREATE'
<stdin>:126:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:126:14: error: unknown type name 'IF'
<stdin>:136:47: error: empty character constant
<stdin>:140:1: error: unknown type name 'CREATE'
<stdin>:140:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:140:14: error: unknown type name 'IF'
<stdin>:154:47: error: empty character constant
<stdin>:159:1: error: unknown type name 'CREATE'
<stdin>:159:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:159:14: error: unknown type name 'IF'
<stdin>:161:1: error: unknown type name 'CREATE'
<stdin>:161:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:161:14: error: unknown type name 'IF'
<stdin>:180:47: error: empty character constant
<stdin>:185:1: error: unknown type name 'CREATE'
<stdin>:185:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:185:14: error: unknown type name 'IF'
<stdin>:187:1: error: unknown type name 'CREATE'
<stdin>:187:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'obsolete_vulnerabilities'
<stdin>:187:16: error: unknown type name 'obsolete_vulnerabilities'
<stdin>:189:26: warning: character constant too long for its type
<stdin>:192:24: warning: character constant too long for its type
<stdin>:194:39: warning: character constant too long for its type
<stdin>:195:1: warning: data definition has no type or storage class
<stdin>:195:1: warning: type defaults to 'int' in declaration of 'END' [-Wimplicit-int]
<stdin>:197:1: error: unknown type name 'CREATE'
<stdin>:197:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:197:14: error: unknown type name 'IF'
<stdin>:201:47: error: empty character constant
<stdin>:205:1: error: unknown type name 'CREATE'
<stdin>:205:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:205:14: error: unknown type name 'IF'
<stdin>:207:1: error: unknown type name 'CREATE'
<stdin>:207:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'hotfix_delete'
<stdin>:207:16: error: unknown type name 'hotfix_delete'
<stdin>:209:26: warning: character constant too long for its type
<stdin>:212:24: warning: character constant too long for its type
<stdin>:215:1: warning: data definition has no type or storage class
<stdin>:215:1: warning: type defaults to 'int' in declaration of 'END' [-Wimplicit-int]
<stdin>:217:1: error: unknown type name 'CREATE'
<stdin>:217:16: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'hotfix_insert'
<stdin>:217:16: error: unknown type name 'hotfix_insert'
<stdin>:219:26: warning: character constant too long for its type
<stdin>:222:24: warning: character constant too long for its type
<stdin>:225:1: warning: data definition has no type or storage class
<stdin>:225:1: warning: type defaults to 'int' in declaration of 'END' [-Wimplicit-int]
<stdin>:227:1: error: unknown type name 'CREATE'
<stdin>:227:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:227:14: error: unknown type name 'IF'
<stdin>:258:47: error: empty character constant
<stdin>:262:1: error: unknown type name 'CREATE'
<stdin>:262:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:262:14: error: unknown type name 'IF'
<stdin>:264:1: error: unknown type name 'CREATE'
<stdin>:264:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:264:14: error: unknown type name 'IF'
<stdin>:278:1: error: unknown type name 'CREATE'
<stdin>:278:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:278:14: error: unknown type name 'IF'
<stdin>:280:1: error: unknown type name 'CREATE'
<stdin>:280:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:280:14: error: unknown type name 'IF'
<stdin>:285:1: error: unknown type name 'CREATE'
<stdin>:285:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:285:14: error: unknown type name 'IF'
<stdin>:296:1: error: unknown type name 'CREATE'
<stdin>:296:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:296:14: error: unknown type name 'IF'
<stdin>:301:4: error: stray '`' in program
<stdin>:301:15: error: stray '`' in program
<stdin>:305:1: error: unknown type name 'CREATE'
<stdin>:305:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:305:14: error: unknown type name 'IF'
<stdin>:318:1: error: unknown type name 'CREATE'
<stdin>:318:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:318:14: error: unknown type name 'IF'
<stdin>:331:4: error: stray '`' in program
<stdin>:331:15: error: stray '`' in program
<stdin>:337:1: error: unknown type name 'CREATE'
<stdin>:337:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:337:14: error: unknown type name 'IF'
<stdin>:339:1: error: unknown type name 'CREATE'
<stdin>:339:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:339:14: error: unknown type name 'IF'
<stdin>:341:3: error: stray '`' in program
<stdin>:341:8: error: stray '`' in program
<stdin>:343:26: error: stray '`' in program
<stdin>:343:31: error: stray '`' in program
<stdin>:346:1: error: unknown type name 'CREATE'
<stdin>:346:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:346:14: error: unknown type name 'IF'
<stdin>:348:1: error: unknown type name 'CREATE'
<stdin>:348:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:348:14: error: unknown type name 'IF'
<stdin>:350:3: error: stray '`' in program
<stdin>:350:7: error: stray '`' in program
<stdin>:351:3: error: stray '`' in program
<stdin>:351:9: error: stray '`' in program
<stdin>:352:27: error: stray '`' in program
<stdin>:352:31: error: stray '`' in program
<stdin>:352:34: error: stray '`' in program
<stdin>:352:40: error: stray '`' in program
<stdin>:355:1: error: unknown type name 'CREATE'
<stdin>:355:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:355:14: error: unknown type name 'IF'
<stdin>:357:1: error: unknown type name 'CREATE'
<stdin>:357:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:357:14: error: unknown type name 'IF'
<stdin>:362:1: error: unknown type name 'INSERT'
<stdin>:362:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'vuln_metadata'
<stdin>:364:1: error: unknown type name 'CREATE'
<stdin>:364:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:364:14: error: unknown type name 'IF'
<stdin>:370:49: error: empty character constant
<stdin>:371:47: error: empty character constant
<stdin>:374:1: error: unknown type name 'CREATE'
<stdin>:374:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:374:14: error: unknown type name 'IF'
<stdin>:379:33: error: empty character constant
<stdin>:380:27: warning: character constant too long for its type
<stdin>:380:59: warning: character constant too long for its type
<stdin>:380:71: warning: multi-character character constant [-Wmultichar]
<stdin>:380:79: warning: character constant too long for its type
<stdin>:380:89: warning: multi-character character constant [-Wmultichar]
<stdin>:380:96: warning: multi-character character constant [-Wmultichar]
<stdin>:380:104: warning: character constant too long for its type
<stdin>:383:28: error: empty character constant
<stdin>:384:23: error: empty character constant
<stdin>:384:51: warning: multi-character character constant [-Wmultichar]
<stdin>:384:57: warning: character constant too long for its type
<stdin>:385:25: warning: character constant too long for its type
<stdin>:385:62: warning: character constant too long for its type
<stdin>:385:71: warning: character constant too long for its type
<stdin>:385:82: warning: character constant too long for its type
<stdin>:386:38: error: empty character constant
<stdin>:387:28: error: empty character constant
<stdin>:388:24: error: empty character constant
<stdin>:389:20: error: empty character constant
<stdin>:390:18: error: empty character constant
<stdin>:393:1: error: unknown type name 'CREATE'
<stdin>:393:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:393:14: error: unknown type name 'IF'
<stdin>:394:1: error: unknown type name 'CREATE'
<stdin>:394:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:394:14: error: unknown type name 'IF'
<stdin>:395:1: error: unknown type name 'CREATE'
<stdin>:395:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:395:14: error: unknown type name 'IF'
<stdin>:396:1: error: unknown type name 'CREATE'
<stdin>:396:14: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'IF'
<stdin>:396:14: error: unknown type name 'IF'
<stdin>:398:1: warning: data definition has no type or storage class
<stdin>:398:1: warning: type defaults to 'int' in declaration of 'BEGIN' [-Wimplicit-int]
<stdin>:400:1: error: unknown type name 'INSERT'
<stdin>:400:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'metadata'
<stdin>:400:43: warning: character constant too long for its type
<stdin>:400:57: warning: multi-character character constant [-Wmultichar]
<stdin>:401:1: error: unknown type name 'INSERT'
<stdin>:401:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'scan_info'
<stdin>:401:40: warning: multi-character character constant [-Wmultichar]
<stdin>:402:1: error: unknown type name 'INSERT'
<stdin>:402:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'scan_info'
<stdin>:402:40: warning: character constant too long for its type
<stdin>:403:1: error: unknown type name 'INSERT'
<stdin>:403:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:403:43: warning: multi-character character constant [-Wmultichar]
<stdin>:404:1: error: unknown type name 'INSERT'
<stdin>:404:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:404:43: warning: character constant too long for its type
<stdin>:405:1: error: unknown type name 'INSERT'
<stdin>:405:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:405:43: warning: character constant too long for its type
<stdin>:406:1: error: unknown type name 'INSERT'
<stdin>:406:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:406:43: warning: character constant too long for its type
<stdin>:407:1: error: unknown type name 'INSERT'
<stdin>:407:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:407:43: warning: character constant too long for its type
<stdin>:408:1: error: unknown type name 'INSERT'
<stdin>:408:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:408:43: warning: character constant too long for its type
<stdin>:409:1: error: unknown type name 'INSERT'
<stdin>:409:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:409:43: warning: character constant too long for its type
<stdin>:410:1: error: unknown type name 'INSERT'
<stdin>:410:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:410:43: warning: character constant too long for its type
<stdin>:411:1: error: unknown type name 'INSERT'
<stdin>:411:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:411:43: warning: character constant too long for its type
<stdin>:412:1: error: unknown type name 'INSERT'
<stdin>:412:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:412:43: warning: character constant too long for its type
<stdin>:413:1: error: unknown type name 'INSERT'
<stdin>:413:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:413:43: warning: character constant too long for its type
<stdin>:414:1: error: unknown type name 'INSERT'
<stdin>:414:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:414:43: warning: character constant too long for its type
<stdin>:415:1: error: unknown type name 'INSERT'
<stdin>:415:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:415:43: warning: character constant too long for its type
<stdin>:416:1: error: unknown type name 'INSERT'
<stdin>:416:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:416:43: warning: character constant too long for its type
<stdin>:418:1: warning: data definition has no type or storage class
<stdin>:418:1: warning: type defaults to 'int' in declaration of 'COMMIT' [-Wimplicit-int]
<stdin>:419:1: warning: missing terminating " character
<stdin>:419:1: error: missing terminating " character
make[1]: *** [Makefile:1646: wazuh_db/schema_agents.o] Error 1
make[1]: Leaving directory '/home/lishu/wazuh-4.6.0/src'
make: *** [Makefile:839: winagent] Error 2

How should I fixed it?

**Comment by ZeroLiShu** [comment]
<stdin>:416:1: error: unknown type name 'INSERT'
<stdin>:416:13: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'sync_info'
<stdin>:416:43: warning: character constant too long for its type
<stdin>:418:1: warning: data definition has no type or storage class
<stdin>:418:1: warning: type defaults to 'int' in declaration of 'COMMIT' [-Wimplicit-int]
<stdin>:419:1: warning: missing terminating " character
<stdin>:419:1: error: missing terminating " character
make[1]: *** [Makefile:1646: wazuh_db/schema_agents.o] Error 1
make[1]: Leaving directory '/home/lishu/wazuh-4.6.0/src'
make: *** [Makefile:839: winagent] Error 2

**Comment by pereyra-m** [comment]
Hello @ZeroLiShu 

I have an Ubuntu Jammy where I've run the following commands:

- Installed all required dependencies and downloaded the source code (https://documentation.wazuh.com/4.6/deployment-options/wazuh-from-sources/wazuh-agent/index.html)
- Downloaded the external dependencies `make deps TARGET=winagent`
- Compiled the agent `make TARGET=winagent`

The process ended successfully.
Have you modified any files in the repository? Can you share the content of `./wazuh_db/schema_agents.sql` ?

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
