### ISSUE TITLE
Missing translation for LibreOffice reported by user Nikolay in Google Groups

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh#24403]
# Description

A community user has [reported](https://groups.google.com/g/wazuh/c/lSJjLypYZtY/m/pUXZPWNnAQAJ) that version 4.8.0 of the vulnerability detector is not detecting vulnerabilities for LibreOffice in Windows.

![image](https://github.com/wazuh/wazuh/assets/7939712/179545dc-2d33-4316-aabd-dd2a1195dc84)

This is due to missing translation information for that application.

An internal issue has been created to add the missing translation:
- https://github.com/wazuh/intelligence-data/issues/748

# DoD
- [x] Translation for the correct mapping of LibreOffice vulnerabilities detection is created.
- [x] Translation is published.
- [x] Correct detection of LibreOffice vulnerabilities in Windows validated

**Comment by sebasfalcone** [comment]
## Update
- Translation reviewed and approved

**Comment by sebasfalcone** [comment]
## Update
- Moved to 4.10.0 release

**Comment by GabrielEValenzuela** [comment]
# Update

- Test case added. Await for review.

**Comment by sebasfalcone** [comment]
## Issue blocked
We need the translation to impact the compressed content, once that happens we can merge this PR

**Comment by GabrielEValenzuela** [comment]
# Update 

- Apply 039115d
