### ISSUE TITLE
How to understand Wazuh Rules?

### ISSUE THREAD

**Issue by ProSehran** [wazuh/wazuh#24404]
I was trying to understand the predefined rules, but they are very confusing. I'm not sure how the tags of XML make a difference. Can someone guide me on how to create our own rules and send me a guide to understand the predefined ones?

**Comment by juliancnn** [comment]
Hi @ProSehran,

I share some resources below, and if after reading them you have specific questions you can ask here or in [our community](https://wazuh.com/community/join-us-on-slack/) channel in slack

- Introduccion to [Rules](https://documentation.wazuh.com/current/user-manual/ruleset/rules/index.html)
- For a deeper understanding of creating decoders, refer to [Creating Decoders and Rules from Scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/).
- Learn about sibling decoders in [Sibling Decoders - Flexible Extraction of Information](https://wazuh.com/blog/sibling-decoders-flexible-extraction-of-information/).
- For more detailed guidance, check the [official documentation on custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)
- Don’t forget to test your configurations with [Testing Decoders and Rules](https://documentation.wazuh.com/current/user-manual/ruleset/testing.html)

I hope you find this useful,
Regards

**Comment by Dwordcito** [comment]
Thank you for being part of the community, if you have any other questions related to this issue, please reopen it, if it is related to another reason, create another issue.
