### ISSUE TITLE
Registered agents using a subnet mask IP are shown as never connected in Kibana

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2443]
## Bug report

**Wazuh version**
_3.7.2_

**Wazuh API version**
_3.7.2_

**Install type**
_manager_

**Install method**
_packages_

**Log sample**

```
2019/01/17 21:49:03 wazuh-modulesd:database[12977] wm_database.c:1410 at wm_inotify_start(): DEBUG: inotify: i='0', name='wazuh_node_1-10.8.0.0', mask='8', wd='2'
2019/01/17 21:49:03 wazuh-modulesd:database[12977] wm_database.c:1484 at wm_inotify_push(): DEBUG: Adding '/var/ossec/queue/agent-info/wazuh_node_1-10.8.0.0' to path table.
2019/01/17 21:49:03 wazuh-modulesd:database[12977] wm_database.c:1515 at wm_inotify_pop(): DEBUG: Taking '/var/ossec/queue/agent-info/wazuh_node_1-10.8.0.0' from path table.
2019/01/17 21:49:03 wazuh-modulesd:database[12977] wm_database.c:770 at wm_sync_file(): DEBUG: Synchronizing file '/var/ossec/queue/agent-info/wazuh_node_1-10.8.0.0'
2019/01/17 21:49:03 wazuh-modulesd:database[12977] wm_database.c:830 at wm_sync_file(): DEBUG: No such agent at database for file /var/ossec/queue/agent-info/wazuh_node_1-10.8.0.0
```

Bug description
----------------
I was having an issue whereby my agents would always have the status "never connected" in the Kibana app. After some investigating, I found the root cause of this issue. When enabling debugging for `wazuh-modulesd:database` I got the entries shown above in ossec.log.

What seems to be happening is that `wm_extract_agent()` is called from`wm_sync_file()` to determine the client name and IP-address from the agents filename in `/queue/agent-info/*`. Then that combination of agent name and IP address is looked up by `wdb_find_agent()` in the agent table of `global.db` (which holds the agent information for the app). But since my agents were using DHCP I assigned a subnet mask of /24 to the IP-address.

**Because the forward slash has a special meaning in Linux it is omitted from the agent filename** `wazuh_node_1-10.8.0.0/24` **but it was NOT omitted from the agent table in global.db**. Therefore the agent-info file could never be found by `wazuh-modulesd` and it never got the status active in the kibana app. This did not affect the CLI tools by the way.

**Comment by vikman90** [comment]
I confirm that the bug is in the legacy database sychronization engine.

## How to reproduce

1. Register an agent with network mask:

```sh
agent-auth -m 192.168.33.10 -I 192.168.33.0/24
service wazuh-agent restart
```

2. The agent gets connected:

> 2019/05/20 02:31:05 ossec-agentd: INFO: Trying to connect to server (192.168.33.10:1514/udp).
> 2019/05/20 02:31:06 ossec-agentd: INFO: (4102): Connected to the server (192.168.33.10:1514/udp).


3. But that agent appears as never connected:

```
$ agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: stretch64 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: centos, IP: 192.168.33.0/24, Active
```

4. The database reports this error, and deletes the _agent-info_ file:
> 019/05/20 11:58:08 wazuh-modulesd:database[30388] wm_database.c:852 at wm_sync_file(): DEBUG: No such agent at database for file /var/ossec/queue/agent-info/centos-192.168.33.0

## Proposed fix

Maybe we can split the network mask part of the IP in the database, or adapt the finding function to match the IP without a mask.
