### ISSUE TITLE
Release 4.8.1 - Release Candidate RC 2- Python unit tests

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#24488]
The following issue aims to run all `python unit tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## Python unit tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |           https://github.com/wazuh/wazuh/issues/24417#top                                 |
| **Version**                          |                      4.8.1                      |
| **Release candidate #**              |                  RC2                          |
| **Tag**                              |                      [v4.8.1-rc2](https://github.com/wazuh/wazuh/tree/v4.8.1-rc2)                      |
| **Previous python unit tests issue** |                   https://github.com/wazuh/wazuh/issues/23990                         |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

As for the coverage results, they must be added split by modules. Test files must not be included in the coverage report.

All test coverage results must have one of the following statuses: 
|                 |        |
|-----------------|--------|
| :green_square:  | >= 75% |
| :yellow_square: | >= 50% |
| :orange_square: | >= 25% |
| :red_square:    | < 25%  |

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/24488#issuecomment-2214847109).

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

|                                        |              |            |
|----------------------------------------|--------------|------------|
|                                        | **Coverage** | **Status** |
| **Overall python unit tests coverage** |      92%        |     :green_square:       |

### New issues
- https://github.com/wazuh/wazuh/issues/24506

### Known issues
- https://github.com/wazuh/wazuh/issues/21678

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @Selutario

**Comment by RamosFe** [comment]
## Test Results
## API
Artifacts: [api.zip](https://github.com/user-attachments/files/16132880/api.zip)

| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| controllers/test/test_active_response_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_agent_controller.py | 44 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_cdb_list_controller.py | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_ciscat_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_cluster_controller.py | 24 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_decoder_controller.py | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_default_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_event_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_experimental_controller.py | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_manager_controller.py | 21 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_mitre_controller.py | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_overview_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_rootcheck_controller.py | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_rule_controller.py | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_sca_controller.py | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_security_controller.py | 51 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_syscheck_controller.py | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_syscollector_controller.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| controllers/test/test_task_controller.py | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| models/test/test_model.py | 30 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_alogging.py | 22 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_authentication.py | 11 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_configuration.py | 51 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_encoder.py | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_middlewares.py | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_signals.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_uri_parser.py | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_util.py | 47 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test/test_validator.py | 176 | 0 | 0 | 0 | 0 |  | :green_circle: |


## Framework
Artifacts: [framework.zip](https://github.com/user-attachments/files/16132881/framework.zip)
---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| scripts/tests/test_agent_groups.py | 14 | 0 | 0 | 0 | 0 |  | :green_circle: |
| scripts/tests/test_agent_upgrade.py | 17 | 0 | 0 | 0 | 0 |  | :green_circle: |
| scripts/tests/test_cluster_control.py | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| scripts/tests/test_rbac_control.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| scripts/tests/test_wazuh_clusterd.py | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| scripts/tests/test_wazuh_logtest.py | 22 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/dapi/tests/test_dapi.py | 32 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_client.py | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_cluster.py | 35 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_common.py | 86 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_control.py | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_local_client.py | 14 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_local_server.py | 24 | 0 | 0 | 0 | 0 |  | :green_circle: |
| wazuh/core/cluster/tests/test_master.py | 45 | 0 | 0 | 0 | 1 | insert issue link | :red_circle: |

## Integrations
Artifacts: [integrations.zip](https://github.com/user-attachments/files/16132885/integrations.zip)

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| tests/test_maltiverse.py | 46 | 0 | 0 | 0 | 0 |  | :green_circle: |
| tests/test_pagerduty.py | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| tests/test_shuffle.py | 18 | 0 | 0 | 0 | 0 |  | :green_circle: |
| tests/test_slack.py | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| tests/test_virustotal.py | 22 | 0 | 0 | 0 | 0 |  | :green_circle: |

## Wodles
Artifacts: [wodles.zip](https://github.com/user-attachments/files/16132891/wodles.zip)
The following errors appeared when running the test pipeline for the Wodles:
```bash
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.5.0 -- /usr/local/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.10.13', 'Platform': 'Linux-5.10.218-208.862.amzn2.x86_64-x86_64-with-glibc2.36', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.5.0'}, 'Plugins': {'aiohttp': '1.0.4', 'asyncio': '0.18.1', 'tavern': '1.23.5', 'trio': '0.7.0', 'html': '2.1.1', 'metadata': '3.1.1'}, 'AWS_REGION': 'us-east-1'}
rootdir: /tmp/build/wazuh/wodles
configfile: pytest.ini
plugins: aiohttp-1.0.4, asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, metadata-3.1.1
asyncio: mode=auto
collecting ... collected 618 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 665, in perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/main.py", line 832, in genitems
INTERNALERROR>     rep = collect_one_node(node)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/_pytest/runner.py", line 550, in collect_one_node
INTERNALERROR>     ihook.pytest_exception_interact(node=collector, call=call, report=rep)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/pytest_trio/plugin.py", line 62, in pytest_exception_interact
INTERNALERROR>     if issubclass(call.excinfo.type, trio.MultiError):
INTERNALERROR>   File "/home/test_user/.local/lib/python3.10/site-packages/trio/_deprecate.py", line 153, in __getattr__
INTERNALERROR>     raise AttributeError(msg.format(self.__name__, name))
INTERNALERROR> AttributeError: module 'trio' has no attribute 'MultiError'

============================ no tests ran in 1.23s =============================
```

This error was related to this Issue https://github.com/wazuh/wazuh/issues/21678. No errors were found after testing it locally and applying the changes described in the issue.

```bash
(env) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh/wodles$ PYTHONPATH=/home/federamos/Documents/Wazuh/Repositories/wazuh/framework/:/home/federamos/Documents/Wazuh/Repositories/wazuh/api pytest .
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.5.0
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/wodles
configfile: pytest.ini
plugins: asyncio-0.18.1, html-2.1.1, metadata-3.1.1, tavern-1.23.5, aiohttp-1.0.4, trio-0.8.0
asyncio: mode=auto
collected 857 items                                                                                                                                                                                                                     

aws/tests/test_aws_bucket.py .................................................................................................................................................................................................... [ 22%]
.............                                                                                                                                                                                                                     [ 24%]
aws/tests/test_aws_s3.py ....................                                                                                                                                                                                     [ 26%]
aws/tests/test_aws_service.py ....                                                                                                                                                                                                [ 27%]
aws/tests/test_cloudtrail.py ..                                                                                                                                                                                                   [ 27%]
aws/tests/test_cloudwatchlogs.py .....................................................                                                                                                                                            [ 33%]
aws/tests/test_config.py ..............................................................................                                                                                                                           [ 42%]
aws/tests/test_guardduty.py .................                                                                                                                                                                                     [ 44%]
aws/tests/test_inspector.py ......                                                                                                                                                                                                [ 45%]
aws/tests/test_load_balancers.py ............                                                                                                                                                                                     [ 46%]
aws/tests/test_s3_log_handler.py ....                                                                                                                                                                                             [ 47%]
aws/tests/test_server_access.py .................................                                                                                                                                                                 [ 51%]
aws/tests/test_sqs_queue.py .......                                                                                                                                                                                               [ 51%]
aws/tests/test_tools.py ...............................                                                                                                                                                                           [ 55%]
aws/tests/test_umbrella.py ......                                                                                                                                                                                                 [ 56%]
aws/tests/test_vpcflow.py ...........................                                                                                                                                                                             [ 59%]
aws/tests/test_waf.py .......                                                                                                                                                                                                     [ 60%]
aws/tests/test_wazuh_integration.py ......................................................................................................                                                                                        [ 72%]
azure/tests/test_azure.py .....................................................................................................................                                                                                   [ 85%]
azure/tests/test_orm.py ...............................                                                                                                                                                                           [ 89%]
docker-listener/tests/test_docker_listener.py ...................                                                                                                                                                                 [ 91%]
gcloud/tests/test_bucket.py .................................                                                                                                                                                                     [ 95%]
gcloud/tests/test_gcloud.py .........                                                                                                                                                                                             [ 96%]
gcloud/tests/test_integration.py ........                                                                                                                                                                                         [ 97%]
gcloud/tests/test_subscriber.py ..............                                                                                                                                                                                    [ 99%]
gcloud/tests/test_tools.py ........                                                                                                                                                                                               [100%]

========================================================================================================== 857 passed in 4.46s ==========================================================================================================
```

**Comment by RamosFe** [comment]
## Test Coverage
> Comment: These results were obtained after applying the changes in https://github.com/wazuh/wazuh/issues/21678 as commented in  https://github.com/wazuh/wazuh/issues/24488#issuecomment-2214847109
### FRAMEWORK

| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| framework/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/scripts/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/scripts/agent_groups.py | 172 | 16 | 91% | :green_square: |
| framework/scripts/agent_upgrade.py | 120 | 9 | 92% | :green_square: |
| framework/scripts/cluster_control.py | 133 | 1 | 99% | :green_square: |
| framework/scripts/rbac_control.py | 64 | 10 | 84% | :green_square: |
| framework/scripts/wazuh_clusterd.py | 121 | 14 | 88% | :green_square: |
| framework/setup.py | 3 | 3 | 0% | :red_square: |
| framework/wazuh/__init__.py | 50 | 13 | 74% | :yellow_square: |
| framework/wazuh/__main__.py | 2 | 2 | 0% | :red_square: |
| framework/wazuh/active_response.py | 25 | 0 | 100% | :green_square: |
| framework/wazuh/agent.py | 514 | 7 | 99% | :green_square: |
| framework/wazuh/cdb_list.py | 77 | 2 | 97% | :green_square: |
| framework/wazuh/ciscat.py | 27 | 0 | 100% | :green_square: |
| framework/wazuh/cluster.py | 64 | 0 | 100% | :green_square: |
| framework/wazuh/core/InputValidator.py | 19 | 0 | 100% | :green_square: |
| framework/wazuh/core/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/core/active_response.py | 70 | 3 | 96% | :green_square: |
| framework/wazuh/core/agent.py | 505 | 30 | 94% | :green_square: |
| framework/wazuh/core/cdb_list.py | 106 | 2 | 98% | :green_square: |
| framework/wazuh/core/cluster/__init__.py | 5 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/client.py | 165 | 10 | 94% | :green_square: |
| framework/wazuh/core/cluster/cluster.py | 287 | 2 | 99% | :green_square: |
| framework/wazuh/core/cluster/common.py | 702 | 12 | 98% | :green_square: |
| framework/wazuh/core/cluster/control.py | 63 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/dapi/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/dapi/dapi.py | 387 | 30 | 92% | :green_square: |
| framework/wazuh/core/cluster/local_client.py | 115 | 6 | 95% | :green_square: |
| framework/wazuh/core/cluster/local_server.py | 152 | 1 | 99% | :green_square: |
| framework/wazuh/core/cluster/master.py | 420 | 5 | 99% | :green_square: |
| framework/wazuh/core/cluster/server.py | 203 | 4 | 98% | :green_square: |
| framework/wazuh/core/cluster/tests/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/utils.py | 166 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/worker.py | 334 | 12 | 96% | :green_square: |
| framework/wazuh/core/common.py | 127 | 2 | 98% | :green_square: |
| framework/wazuh/core/configuration.py | 485 | 7 | 99% | :green_square: |
| framework/wazuh/core/database.py | 55 | 5 | 91% | :green_square: |
| framework/wazuh/core/decoder.py | 52 | 0 | 100% | :green_square: |
| framework/wazuh/core/exception.py | 116 | 3 | 97% | :green_square: |
| framework/wazuh/core/manager.py | 152 | 12 | 92% | :green_square: |
| framework/wazuh/core/mitre.py | 257 | 13 | 95% | :green_square: |
| framework/wazuh/core/pyDaemonModule.py | 64 | 17 | 73% | :yellow_square: |
| framework/wazuh/core/results.py | 335 | 24 | 93% | :green_square: |
| framework/wazuh/core/rootcheck.py | 61 | 0 | 100% | :green_square: |
| framework/wazuh/core/rule.py | 133 | 0 | 100% | :green_square: |
| framework/wazuh/core/sca.py | 78 | 2 | 97% | :green_square: |
| framework/wazuh/core/security.py | 70 | 18 | 74% | :yellow_square: |
| framework/wazuh/core/stats.py | 125 | 1 | 99% | :green_square: |
| framework/wazuh/core/syscheck.py | 28 | 0 | 100% | :green_square: |
| framework/wazuh/core/syscollector.py | 38 | 0 | 100% | :green_square: |
| framework/wazuh/core/task.py | 37 | 0 | 100% | :green_square: |
| framework/wazuh/core/tests/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/core/utils.py | 1042 | 51 | 95% | :green_square: |
| framework/wazuh/core/wazuh_queue.py | 82 | 2 | 98% | :green_square: |
| framework/wazuh/core/wazuh_socket.py | 160 | 76 | 52% | :yellow_square: |
| framework/wazuh/core/wdb.py | 210 | 9 | 96% | :green_square: |
| framework/wazuh/core/wlogging.py | 98 | 3 | 97% | :green_square: |
| framework/wazuh/decoder.py | 153 | 2 | 99% | :green_square: |
| framework/wazuh/event.py | 18 | 0 | 100% | :green_square: |
| framework/wazuh/manager.py | 142 | 17 | 88% | :green_square: |
| framework/wazuh/mitre.py | 53 | 0 | 100% | :green_square: |
| framework/wazuh/rbac/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/rbac/auth_context.py | 197 | 37 | 81% | :green_square: |
| framework/wazuh/rbac/decorators.py | 232 | 63 | 73% | :yellow_square: |
| framework/wazuh/rbac/orm.py | 1295 | 319 | 75% | :green_square: |
| framework/wazuh/rbac/preprocessor.py | 73 | 22 | 70% | :yellow_square: |
| framework/wazuh/rbac/tests/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/rbac/tests/utils.py | 36 | 0 | 100% | :green_square: |
| framework/wazuh/rbac/utils.py | 23 | 10 | 57% | :yellow_square: |
| framework/wazuh/rootcheck.py | 64 | 3 | 95% | :green_square: |
| framework/wazuh/rule.py | 169 | 2 | 99% | :green_square: |
| framework/wazuh/sca.py | 63 | 3 | 95% | :green_square: |
| framework/wazuh/security.py | 552 | 203 | 63% | :yellow_square: |
| framework/wazuh/stats.py | 119 | 7 | 94% | :green_square: |
| framework/wazuh/syscheck.py | 95 | 4 | 96% | :green_square: |
| framework/wazuh/syscollector.py | 35 | 8 | 77% | :green_square: |
| framework/wazuh/task.py | 19 | 0 | 100% | :green_square: |
| framework/wazuh/tests/util.py | 42 | 2 | 95% | :green_square: |
| TOTAL | 12256 | 1141 | 91% | :green_square: |

### API

| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| api/__init__.py | 0 | 0 | 100% | :green_square: |
| api/alogging.py | 78 | 0 | 100% | :green_square: |
| api/api_exception.py | 12 | 0 | 100% | :green_square: |
| api/authentication.py | 109 | 7 | 94% | :green_square: |
| api/configuration.py | 94 | 4 | 96% | :green_square: |
| api/constants.py | 14 | 0 | 100% | :green_square: |
| api/controllers/__init__.py | 0 | 0 | 100% | :green_square: |
| api/controllers/active_response_controller.py | 15 | 0 | 100% | :green_square: |
| api/controllers/agent_controller.py | 252 | 5 | 98% | :green_square: |
| api/controllers/cdb_list_controller.py | 41 | 0 | 100% | :green_square: |
| api/controllers/ciscat_controller.py | 13 | 0 | 100% | :green_square: |
| api/controllers/cluster_controller.py | 163 | 0 | 100% | :green_square: |
| api/controllers/decoder_controller.py | 46 | 0 | 100% | :green_square: |
| api/controllers/default_controller.py | 16 | 0 | 100% | :green_square: |
| api/controllers/event_controller.py | 15 | 0 | 100% | :green_square: |
| api/controllers/experimental_controller.py | 109 | 0 | 100% | :green_square: |
| api/controllers/manager_controller.py | 121 | 0 | 100% | :green_square: |
| api/controllers/mitre_controller.py | 41 | 0 | 100% | :green_square: |
| api/controllers/overview_controller.py | 12 | 0 | 100% | :green_square: |
| api/controllers/rootcheck_controller.py | 27 | 0 | 100% | :green_square: |
| api/controllers/rule_controller.py | 58 | 0 | 100% | :green_square: |
| api/controllers/sca_controller.py | 20 | 0 | 100% | :green_square: |
| api/controllers/security_controller.py | 245 | 9 | 96% | :green_square: |
| api/controllers/syscheck_controller.py | 31 | 0 | 100% | :green_square: |
| api/controllers/syscollector_controller.py | 65 | 0 | 100% | :green_square: |
| api/controllers/task_controller.py | 13 | 0 | 100% | :green_square: |
| api/controllers/test/utils.py | 11 | 0 | 100% | :green_square: |
| api/encoder.py | 24 | 1 | 96% | :green_square: |
| api/middlewares.py | 104 | 37 | 64% | :yellow_square: |
| api/models/__init__.py | 3 | 0 | 100% | :green_square: |
| api/models/active_response_model.py | 29 | 0 | 100% | :green_square: |
| api/models/agent_added_model.py | 72 | 0 | 100% | :green_square: |
| api/models/agent_inserted_model.py | 50 | 0 | 100% | :green_square: |
| api/models/base_model_.py | 104 | 0 | 100% | :green_square: |
| api/models/basic_info_model.py | 59 | 0 | 100% | :green_square: |
| api/models/configuration_model.py | 205 | 0 | 100% | :green_square: |
| api/models/events_ingest_model.py | 17 | 0 | 100% | :green_square: |
| api/models/group_added_model.py | 15 | 0 | 100% | :green_square: |
| api/models/security_model.py | 72 | 0 | 100% | :green_square: |
| api/models/security_token_response_model.py | 19 | 0 | 100% | :green_square: |
| api/signals.py | 53 | 1 | 98% | :green_square: |
| api/uri_parser.py | 29 | 0 | 100% | :green_square: |
| api/util.py | 152 | 4 | 97% | :green_square: |
| api/validator.py | 163 | 14 | 91% | :green_square: |
| TOTAL | 2791 | 82 | 97% | :green_square: |

### WODLES

| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| wodles/__init__.py | 0 | 0 | 100% | :green_square: |
| wodles/aws/__init__.py | 0 | 0 | 100% | :green_square: |
| wodles/aws/aws_s3.py | 94 | 18 | 81% | :green_square: |
| wodles/aws/aws_tools.py | 144 | 22 | 85% | :green_square: |
| wodles/aws/buckets_s3/__init__.py | 10 | 0 | 100% | :green_square: |
| wodles/aws/buckets_s3/aws_bucket.py | 427 | 16 | 96% | :green_square: |
| wodles/aws/buckets_s3/cloudtrail.py | 26 | 3 | 88% | :green_square: |
| wodles/aws/buckets_s3/config.py | 91 | 7 | 92% | :green_square: |
| wodles/aws/buckets_s3/guardduty.py | 64 | 1 | 98% | :green_square: |
| wodles/aws/buckets_s3/load_balancers.py | 69 | 0 | 100% | :green_square: |
| wodles/aws/buckets_s3/server_access.py | 137 | 12 | 91% | :green_square: |
| wodles/aws/buckets_s3/umbrella.py | 22 | 0 | 100% | :green_square: |
| wodles/aws/buckets_s3/vpcflow.py | 107 | 15 | 86% | :green_square: |
| wodles/aws/buckets_s3/waf.py | 38 | 0 | 100% | :green_square: |
| wodles/aws/services/__init__.py | 4 | 0 | 100% | :green_square: |
| wodles/aws/services/aws_service.py | 44 | 0 | 100% | :green_square: |
| wodles/aws/services/cloudwatchlogs.py | 189 | 6 | 97% | :green_square: |
| wodles/aws/services/inspector.py | 56 | 6 | 89% | :green_square: |
| wodles/aws/subscribers/__init__.py | 4 | 0 | 100% | :green_square: |
| wodles/aws/subscribers/s3_log_handler.py | 113 | 62 | 45% | :orange_square: |
| wodles/aws/subscribers/sqs_message_processor.py | 35 | 22 | 37% | :orange_square: |
| wodles/aws/subscribers/sqs_queue.py | 60 | 7 | 88% | :green_square: |
| wodles/aws/tests/__init__.py | 0 | 0 | 100% | :green_square: |
| wodles/aws/tests/aws_utils.py | 115 | 0 | 100% | :green_square: |
| wodles/aws/wazuh_integration.py | 248 | 22 | 91% | :green_square: |
| wodles/azure/azure-logs.py | 450 | 15 | 97% | :green_square: |
| wodles/azure/orm.py | 141 | 0 | 100% | :green_square: |
| wodles/docker-listener/DockerListener.py | 93 | 6 | 94% | :green_square: |
| wodles/gcloud/buckets/access_logs.py | 16 | 0 | 100% | :green_square: |
| wodles/gcloud/buckets/bucket.py | 128 | 2 | 98% | :green_square: |
| wodles/gcloud/exceptions.py | 23 | 0 | 100% | :green_square: |
| wodles/gcloud/gcloud.py | 68 | 1 | 99% | :green_square: |
| wodles/gcloud/integration.py | 38 | 2 | 95% | :green_square: |
| wodles/gcloud/pubsub/subscriber.py | 60 | 2 | 97% | :green_square: |
| wodles/gcloud/tools.py | 41 | 0 | 100% | :green_square: |
| wodles/utils.py | 58 | 27 | 53% | :yellow_square: |
| TOTAL | 3213 | 274 | 91% | :green_square: |

### INTEGRATIONS

| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| integrations/maltiverse.py | 178 | 15 | 92% | :green_square: |
| integrations/pagerduty.py | 104 | 21 | 80% | :green_square: |
| integrations/shuffle.py | 105 | 7 | 93% | :green_square: |
| integrations/slack.py | 112 | 30 | 73% | :yellow_square: |
| integrations/tests/__init__.py | 0 | 0 | 100% | :green_square: |
| integrations/virustotal.py | 174 | 45 | 74% | :yellow_square: |
| TOTAL | 673 | 118 | 82% | :green_square: |



OVERALL COVERAGE PERCENTAGE: 92%

**Comment by juliamagan** [comment]
LGTM
