### ISSUE TITLE
Support new OSs - CentOS Stream 10 - Test dashboard package #24159

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24494]
# Description
| Related issue | Epic issue |
|---|---|
| https://github.com/wazuh/wazuh/issues/24128 | https://github.com/wazuh/wazuh/issues/24490 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**Dashboard**
- [ ] Make sure that the agent-related information in the agent list is correct.
- [ ] Test the deployment one-liner for the new OS.

**Comment by MarcelKemp** [comment]
Closed due to new changes in the document.
