### ISSUE TITLE
MVP - Modify the Wazuh agent uninstallation script/process to integrate with the validation endpoint

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#24510]
Parent issue:
- https://github.com/wazuh/wazuh/issues/23466

# Description

We are going to implement the necessary development for the DEB and RPM package uninstallation scripts to validate the uninstallation with the manager.

[After the spike carried out here](https://github.com/wazuh/wazuh/issues/24356), the following decisions were taken to carry out the development:

- Let's use a configuration block like this one that collects the users decision of whether or not the uninstallation validation process is necessary or not. By default it will be set to NO.
```
  <anti_tampering>
    <package_uninstallation>yes</package_uninstallation>
  </anti_tampering>
```
- During package uninstallation scripts (prerm for DEB, wazuh-agent.spec for RPM), we must read the configuration (be careful to make sure that we read also the centralized configuration), and if the mentioned setting is yes, we must execute the agentd module, with the necessary parameters (either the user and password, or the TOKEN to make the necessary request), which will execute the necessary code to obtain the validation.

- The execution of agentd should be like this:
`/var/ossec/bin/wazuh-agentd --uninstall-auth-login X:Y --uninstall-auth-token Z`
(Check the `:` character in the parameter, we must ensure correct operation.)

- Inside agentd, we must make the necessary request to the endpoints of the API to obtain the validation of the manager. In case of finding some problem with the user/password, not being able to obtain the TOKEN, not being able to make the validation request, or in case of obtaining a negative result of the validation, we must interrupt the flow of uninstallation of the package. If everything goes well and the validation is positive, we will continue with the uninstallation.

**Comment by jotacarma90** [comment]
# Update 09/07/2024

- I start working on the implementation.
- Analysis of the configuration and layout of the agentd daemon.
- Working on the code related to the setting of the necessary parameters. Researching getopt.
- Working with the needs of the API requests.

**Comment by jotacarma90** [comment]
ETA delayed due to complexity of the code and size of changes.

**Comment by MarcelKemp** [comment]
MVP implementation done at https://github.com/wazuh/wazuh/pull/24526.
- `Approved`

Because that branch is not going to be merged yet, and is missing the testing part that will be applied in the `Feature complete implementation` step. I proceed to close the issue as completed, finalizing the PR on the new issue.
