### ISSUE TITLE
Warning messages in `indexer-connector` detected during Specific Systems tests in 4.8.1-rc2

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#24513]
| Wazuh Version | Component | Install Type | Install Method | Platform |
| --- | --- | --- | --- | --- |
| 4.8.1-rc2 | indexer-connector | Manager | AMI / OVA | Amazon Linux 2 |

During [Release 4.8.1 - RC 2 - Specific systems](https://github.com/wazuh/wazuh/issues/24434) testing, warnings were detected in `indexer-connector` for OVA and AMI. 

The warning logs are as follows (they are the same warning messages for the OVA and the AMI):

```console
[root@wazuh-server wazuh-user]# grep -i -E "error|critical|fatal|warning" /var/ossec/logs/ossec.log
2024/07/08 14:44:00 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/07/08 14:44:00 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-wazuh-server', retrying until the connection is successful.
```

These are the tests that have been done on both the OVA and the AMI:

- [OVA Tests](https://github.com/wazuh/wazuh/issues/24434#issuecomment-2214256358)
- [AMI Tests](https://github.com/wazuh/wazuh/issues/24434#issuecomment-2213703266)

We have also been able to verify that no vulnerabilities appear and it may be related to the previous logs.

![image](https://github.com/wazuh/wazuh/assets/54536265/1abe7daa-161c-43d5-97ee-91222c2e2e27)

An investigation is necessary to clarify the root cause

**Comment by davidcr01** [comment]
This error is directly related to: https://github.com/wazuh/wazuh/issues/24441. It is necessary to fix that issue to make the IndexerConnector initializes correctly and then, update the VD feed.

I suggest to close this issue as not planned, and check if the problem persists with the applied fix.
