### ISSUE TITLE
Daemons and binaries related removals

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#24527]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/22888

## Description

Based on the table from the parent issue, we will remove the following deprecated binaries from the project:

| Daemons              | Tools                  |
|----------------------|------------------------|
| `wazuh-agentd`       | `agent-auth`           |
| `wazuh-agentlessd`   | `agent_control`        |
| `wazuh-analysisd`    | `agent_groups`         |
| `wazuh-authd`        | `agent_upgrade`        |
| `wazuh-csyslogd`     | `clear_stats`          |
| `wazuh-db`           | `manage_agents`        |
| `wazuh-dbd`          | `update_ruleset`       |
| `wazuh-execd`        | `verify-agent-conf`    |
| `wazuh-integratord`  | `wazuh-control`        |
| `wazuh-logcollector` | `wazuh-logtest`        |
| `wazuh-maild`        | `wazuh-logtest-legacy` |
| `wazuh-modulesd`     | `wazuh-regex`          |
| `wazuh-monitord`     | `cluster_control`      |
| `wazuh-remoted`      |                        |
| `wazuh-reportd`      |                        |
| `wazuh-syscheckd`    |                        |

## Functional Requirements

1. The code for the specified binaries must be removed from the codebase.
2. These programs should not be compiled or installed.
3. The documentation must not reference these binaries.

## Plan

1. Remove the code for the binaries.
2. Clean up the compilation in the Makefile.
4. Clean up the source installers.
5. Clean up the packages.
6. Clean up the documentation.

## Requirement Traceability Matrix

| Requirement  | Description                        | Plan part  | DRI                |
|--------------|------------------------------------|------------|--------------------|
| Functional 1 | Remove binaries from codebase      | 1          | @wazuh/devel-agent |
| Functional 2 | Do not compile or install programs | 2, 3, 4, 5 | @wazuh/devel-agent |
| Functional 3 | Delete documentation               | 6          | @wazuh/devel-agent |

**Comment by mjcr99** [comment]
## Update
**(11/07/2024)** Started researching the issue. Investigating Makefile structure, removable parts and related folders with the used sources.

**Comment by javimed** [comment]
Reopening this issue due to reverting the merge. It caused compilation errors and sems to include changes that doesn't seem correct.

**Comment by MarcelKemp** [comment]
### Update
- Documentation PR:
Recovering mentions of some daemons that will have to be modified in the future. 
Removing references to avoid compilation problems, and removing by sections to get it to compile correctly.
