### ISSUE TITLE
Revert deprecation warnings in API endpoints

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#24522]
|Component|
|---|
| Wazuh API |

## Description
We decided not to show any deprecation warning for API endpoints until they are removed. Some of the endpoints that will be removed were deprecated in 4.9, so we should revert the changes made in the following PR until 5.0:
- https://github.com/wazuh/wazuh/issues/20792

Some of the endpoints that were deprecated may eventually be kept as a result of [new protocol](https://github.com/wazuh/wazuh/issues/22677) development, [persistence](https://github.com/wazuh/wazuh/issues/22887), etc. Therefore, it will be better not to mark any endpoint as deprecated until those objectives are completed.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Updated the base branch, rebased the dev one and solved the conflicts.
