### ISSUE TITLE
VulnerabilityScannerFacade::start: RSA decryption failed

### ISSUE THREAD

**Issue by am1-source** [wazuh/wazuh#24543]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8 | vulnerability-scanner | Manager Cluster | Assisted | Ubuntu 22.04 |

Vulnerability Detection not working
wazuh-states-vulnerabilities-wazuh_cluster index is there but not getting populated.
Vulnerability Detection Page shows: "No results match your search criteria"

This error is found in logs:
2024/07/11 10:39:52 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: RSA decryption failed
2024/07/11 10:52:55 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: RSA decryption failed

No documentation was found regarding this error.
No other warnings in logs.
Default config as per assisted cluster setup. Pristine, untouched as per assisted setup.
Fresh install. 
Vulnerability detection config 100% matches the one in the docs (same, line by line).

Edit: Forgot to say that I turned on Manager Identity Verification and Password Verification and that clients are enrolling just fine.

**Comment by MiguelazoDS** [comment]
Hi @am1-source, 

We recently found an issue in the decryption process. It works using this config for certificates. 

https://github.com/wazuh/wazuh/blob/878af9ecfe0e18190e9246ce4e9b1f4364ddb3fc/src/init/inst-functions.sh#L228

For any other manual certificate generation has problems, different encryption algorithms, different bit numbers, etc. We are currently working on refactoring this process. 

Sorry for the inconvenience.

**Comment by am1-source** [comment]
Thank you for the reply.

In my case I generated new sslmanager.key/pem because i am using a load balancer.
The other features seem to work just fine, just the vuln scanner is having issue.
What would be the appropriate fix in this case since I need the cert to work with the load balancer IP?

**Comment by MiguelazoDS** [comment]
>  Can you confirm that other features would work and just not the vuln scanner 

Yeap, it only affects vuldet since it's the only module that uses the keystore. This is an issue we have with the Keystore implementation. It uses the same pair ( sslmanager ) but it only works with RSA and recently we found that RSA with 4096 bits also does not work, only 2048. So any custom creation of sslmanager affects the keystore encryption.

Wazuh-authd is just a wrapper around Openssl to create a RSA pair (sslmanager) that is always created by default if there's no any other pair created manually. The mistake was to use the same pair for the Keystore.

Unfortunately, I don't see any workaround other than using the sslmanager pair created by default or recompiling your manager from sources editing the hardcoded path here, to use another pair and not the sslmanager. 

https://github.com/wazuh/wazuh/blob/d2b78968a72447f95970f8af7450942b9dff7745/src/shared_modules/keystore/include/keyStore.hpp#L20-L21

**Comment by am1-source** [comment]
Thanks again.

Do keystore and ossec.conf certs have to be forcefully the same or could one just restore the setup generated and point the ossec.conf at a different cert?
If not is this going to be fixed in the near future so that it can work with the custom ones that I generated using the assisted setup ca or will it always require a new cert setup?  Any way to bypass the keystore for the vuln module like for other modules that don't use it?

**Comment by MiguelazoDS** [comment]
> Do keystore and ossec.conf certs have to be forcefully the same

What do you mean for ossec.conf certs? the one used here? 

```xml
    <ssl_manager_cert>etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>etc/sslmanager.key</ssl_manager_key>
```

In that case, yes. At the moment of the keystore implementation, we didn't consider that using the same pair will affect the flexibility of the sslmanager keys. The path is hardcoded in the lines I commented earlier. 

> If not is this going to be fixed in the near future so that it can work with the custom ones that I generated using the assisted setup ca or will it always require a new cert setup? Any way to bypass the keystore for the vuln module like for other modules that don't use it?

We're trying our best to release this improvement ASAP. 

> Any way to bypass the keystore for the vuln module like for other modules that don't use it?

I'm not sure if I understood this question. If the keystore is empty, it will use `admin:admin` as default credentials to communicate with the indexer. That means that it will not use at all the sslmanager.* keys.

**Comment by am1-source** [comment]
Ok thanks for the insights. I guess I'll wait for the update since the various options are not viable for me. I'll appreciate if you can update the thread when there is a fix for this.

**Comment by MiguelazoDS** [comment]
@am1-source 

Something you can do that a teammate suggested is to change the path used in authd. 

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#ssl-manager-key

So you can keep your custom keys moved to another location for authd and use the default /etc/sslmanager keys for keystore. It's kinda messy but I hope that helps. Regards!

**Comment by am1-source** [comment]
I tried this earlier today restoring the original sslmanager keys to their default location and moving those custom ones I made for the Load Balancer to a different file etc/sslmanager_lb.key together with their reference in the ossec.conf but somehow i still got the RSA crypto error on the manager restart. I only tried it on the master manager in cluster configuration but unfortunately with no luck. Not sure if I missed something.

**Comment by MiguelazoDS** [comment]
Hi @am1-source, 

Well that's strange. What's the output you get with this command? 

`openssl rsa -in /var/ossec/etc/sslmanager.key -text | grep Private-Key
`
I would expect it to be 2048. 

```
root@jammy:/home/vagrant/wazuh# openssl rsa -in /var/ossec/etc/sslmanager.key -text | grep Private-Key
Private-Key: (4096 bit, 2 primes)
writing RSA key
root@jammy:/home/vagrant/wazuh# openssl rsa -in ../ssl_backup/sslmanager.key -text | grep Private-Key
writing RSA key
Private-Key: (2048 bit, 2 primes)
```

What I think that may be happening is that you need to update the keys with that new default pair, otherwise, the encrypted values will still be encrypted with the old keys and trying to decrypt them with the new pair will trigger the error.

**Comment by am1-source** [comment]
Looks like I was able to get the master manager running by restoring the backup of the keys. However for the two workers of the cluster I do not have the original sslmanager.key/cert backup. 

I tried to use the master sslmanager.key and set again the store with the `/var/ossec/bin/wazuh-keystore -f indexer -k username -v admin
 /var/ossec/bin/wazuh-keystore -f indexer -k password -v fdjkfjksdjfff` commands where I used the with the first line of the password.txt file without the single quotes (# Admin user for the web user interface and Wazuh indexer. Use this user to log in to Wazuh dashboard).

However even if the RSA error has gone, I get this one now
`indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-wazuh_cluster', retrying until the connection is successful.
`

Do I have to use a different password?
Any clue on how to fix this?

**Comment by MiguelazoDS** [comment]
Hi @am1-source 

You can use curl to validate your information. 

`curl --cacert root-ca.pem --cert node-1.pem --key node-1-key.pem -u admin:admin https://127.0.0.1:9200/_cluster/health
`
Change the certs, key path, credentials and IP according to your environment, and then configure the IP and certs path in the indexer block (ossec.conf) and the credentials with the Keystore as you did before.

**Comment by am1-source** [comment]
Any way I can simply copy the working keystore from the working machine to the other without further messing with the settings?
All the index-connnector errors only start to appear when I modify the keystore and I haven't touched any of the node certificate.
I'd prefer not to change any of the indexer settings or certs since it's all working except the vuln scanner.

I just need the sslmanager.key copied over from node 1 to node 2 and 3 to work with the keystore.

**Comment by MiguelazoDS** [comment]
Glad to know you could solve this @am1-source, sorry for the inconvenience, and thanks for the troubleshooting. Regards!

**Comment by taylorwalton** [comment]
Hey Team,

I am also facing the same `RSA decription failed` issue when running version 4.8.0 within a container with Wazuh's provided 4.8.0 manager image. 

what is odd is that if I use the cert, key and ca for a wazuh manager non docker, the service has no problem doing the RSA decryption and can connect to the indexers, but when I run within a container I get the issue. I simply copied over the same cert that the non docker wazuh manager was using to the containerized manager. 

Are there any other steps I am missing or any further troubleshooting I can provide?

Thanks!

**Comment by MiguelazoDS** [comment]
Hi @taylorwalton, 

I did a quick test with this image 

![image](https://github.com/user-attachments/assets/302ecc2e-d8e8-4eb3-8df2-6c388674080f)

and I'm not having that issue. 

I added the keys and, I restarted the service 

```console
bash-5.2# /var/ossec/bin/wazuh-keystore -f indexer -k username -v test
bash-5.2# /var/ossec/bin/wazuh-keystore -f indexer -k password -v test
```

![image](https://github.com/user-attachments/assets/da47b099-be7d-484c-abaf-8538df796435)

Please tell me the output of this command 

`openssl x509 -in sslmanager.cert -text | grep Public-Key`

The bug here is that the keystore is not working for 4096 keys because the size in the decryption is hardcoded to 256.

**Comment by taylorwalton** [comment]
Hey @MiguelazoDS thanks for the clarification, I found where my issue lied and all good now

**Comment by MiguelazoDS** [comment]
Glad you could solve that @taylorwalton. Don't hesitate to contact us again if you need to. Regards!
