### ISSUE TITLE
Engine - Update HowardHinnant/date Library and Add Configuration Option for IANA DB Updates

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24549]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

### Description
This issue addresses the need to update the HowardHinnant/date library used in Wazuh-Engine to a newer commit, enhancing stability and feature set. Additionally, there is a requirement to add a new configuration parameter that allows users to decide whether to automatically update the IANA time zone database, which is crucial for time-related calculations in the `date` library. Integration and unit tests must be updated to reflect these changes. The usage of the `date` library should also be encapsulated within the `hlp` module to minimize direct exposure in other parts of the system.

### Tasks
1. **Library Update**:
   - Perform a preliminary investigation of the current version of the HowardHinnant/date library used in the project versus newer commits available on the GitHub repository.
   - Identify any potential breaking changes or major improvements that would affect Wazuh-Engine.
   - Update the library to a more recent, stable commit that offers better performance or additional functionalities.

2. **Configuration Parameter for IANA DB Updates**:
   - Implement a new configuration parameter in Wazuh-Engine that allows users to enable or disable automatic updates of the IANA time zone database. This setting will help users who require strict control over external updates due to security or operational policies.

3. **Testing**:
   - Update existing integration tests to ensure they accommodate the new library version and the configurable IANA DB updates.
   - Update or add new unit tests to validate the functionality of the new configuration parameter and its impact on the system.

4. **Code Refactoring**:
   - Refactor the implementation to encapsulate the `date` library's functionality within the `hlp` module. This change will reduce the direct exposure of third-party library details to other modules, adhering to good software design principles.

### Requirements
- Ensure backward compatibility with existing configurations and deployments.
- Validate that the new configuration parameter is accessible and functional through the Wazuh-Engine's configuration management interfaces.
- Maintain or improve the performance and accuracy of time-related calculations within Wazuh-Engine.

### Acceptance Criteria
- The HowardHinnant/date library is successfully updated to a newer commit without introducing regressions.
- The new configuration parameter effectively controls the automatic updating of the IANA time zone database.
- Integration and unit tests conclusively demonstrate the stability and correctness of the changes.
- The `date` library functionality is appropriately encapsulated within the `hlp` module.

**Comment by juliancnn** [comment]
## Update

  - Investigate and compare the current version of HowardHinnant/date with newer commits.
  - Update the library to a selected, stable commit and ensure that the new library version integrates seamlessly with existing functionalities.
  - Implement a new configuration parameter for enabling/disabling IANA DB updates.
  - Encapsulate the `date` library functionality within the `hlp` module.

**Comment by juliancnn** [comment]
## Update

- CMake fixes
- UT for date parser 
- Update IT readme
- Minor fixes in HLP
- Manual testing
- Create new seccion in user manual for operacion with Time Zones Database
