### ISSUE TITLE
Feature request: Adding more debugging to the new Wazuh keystore

### ISSUE THREAD

**Issue by lucasatw** [wazuh/wazuh#24544]
Hello team,

I'm opening this request because @[zbalkan](https://github.com/zbalkan) reported the logs in the Wazuh keystore are not enough if there is an issue. The only log wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: RSA decryption failed. This feature request has been associated with a PR to improve the debugging logs of the Wazuh keystore: https://github.com/wazuh/wazuh/pull/24362

Regards,
Lucas

**Comment by Dwordcito** [comment]
@sebasfalcone, have we already done this in another PR?

**Comment by sebasfalcone** [comment]
@Dwordcito Yes, we are making some improvements over the keystore module here:
- https://github.com/wazuh/wazuh/pull/24529

We are going to add some of the debug logs proposed by the user

**Comment by sebasfalcone** [comment]
## Closing issue
This issue is duplicated, we are going to take some of the logs proposed by @zbalkan into our PR
