### ISSUE TITLE
Engine - Bug in Policy API: Asset Deletion Leads to Unresolvable Errors

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24541]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

**Description:**

### Description
There is a critical issue in the policy API where deleting an asset from the catalog that is associated with a policy results in unresolvable errors when subsequently accessing or modifying the policy.

### Steps to Reproduce
1. Create an asset (i.e `decoder/test_decoder/0`) 
2. Add the asset to a policy. (i.e. `policy/test/0`)
3. Delete the asset from the catalog.
4. Attempt to retrieve the policy using `wazuh-engine policy get -p policy/test/0`. This results in an error stating that the asset does not exist.
5. Try to remove the non-existent asset from the policy `wazuh-engine policy asset-remove -p policy/test/0 decoder/test_decoder/0`. The same error is returned.

### Expected Behavior
After an asset is deleted from the catalog, any attempt to retrieve or modify the policy should handle the missing asset gracefully. Ideally, do not allow removing an asset that is in use.

### Actual Behavior
Currently, once an asset associated with a policy is deleted from the catalog, it becomes impossible to retrieve or modify the policy due to errors related to the missing asset. The API returns an "Asset not found" error and does not allow further modification to the policy, effectively locking the policy.

### Command Line Replication i.e.
The issue can be replicated using the following commands:
```bash
# Initially retrieve a policy
wazuh-engine policy get -p policy/test/0
# Output:
# policy: policy/test/0
# hash: 6540325007721650527
# assets:
#   - decoder/test_decoder/0
# default_parents:
#   - user: decoder/integrations/0

# Delete an asset
wazuh-engine catalog delete decoder/test_decoder/0

# Attempt to retrieve the policy again
wazuh-engine policy get -p policy/test/0
# Output:
# Asset not found: decoder/test_decoder/0

# Attempt to remove the non-existent asset from the policy
wazuh-engine policy asset-remove -p policy/test/0 decoder/test_decoder/0
# Output:
# Asset not found: decoder/test_decoder/0
```

### Impact
This bug can severely impact the usability and management of policies within the Wazuh-Engine, particularly in dynamic environments where assets are frequently updated or removed.

**Comment by JavierBejMen** [comment]
## Update
- Added unit tests for clean deleteted assets method
- Updated API policy methods to return validation messages
- Updated API policy handler tests
- Updated API policy unit tests
- Updated integration policy tests
- Updated main commands
