### ISSUE TITLE
Investigate whether MS-Graph integration can accommodate MDM Intune integration

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#24552]
**Parent issue:** https://github.com/wazuh/wazuh/issues/24498

## Description

As Wazuh already has an integration to interact with the Microsoft Graph API, the purpose of this issue is to investigate whether it could be used or extended to collect logs from the Microsoft Intune MDM API.

## Implementation restrictions

The integration must be able to extract information from the following endpoints:
- https://graph.microsoft.com/v1.0/deviceManagement/auditEvents.
- https://graph.microsoft.com/v1.0/deviceManagement/managedDevices.
- [https://graph.microsoft.com/v1.0/deviceManagement/managedDevices/{deviceId}/detectedApps](https://graph.microsoft.com/v1.0/deviceManagement/managedDevices/%7BdeviceId%7D/detectedApps).

## Plan

- Conduct initial research on MS-Graph integration.
  - Decide if the MDM Intune integration can fit within this integration.
- Define all the tasks necessary to add this new integration.
  - Define team responsibilities.

**Comment by TomasTurina** [comment]
## Update

After some testing, when trying to interact with the first two endpoints, I get the following errors:

```
2024/07/15 19:43:42 wazuh-modulesd:ms-graph[35613] wm_ms_graph.c:249 at wm_ms_graph_scan_relationships(): DEBUG: Microsoft Graph API Log URL: 'https://graph.microsoft.com/v1.0/deviceManagement/auditEvents'
2024/07/15 19:43:43 wazuh-modulesd:ms-graph[35613] wm_ms_graph.c:259 at wm_ms_graph_scan_relationships(): WARNING: Received unsuccessful status code when attempting to get relationship 'auditEvents' logs: Status code was '400' & response was '{"error":{"code":"AuthenticationError","message":"AADSTS500014: The service principal for resource '0000000a-0000-0000-c000-000000000000' is disabled. This indicate that a subscription within the tenant has lapsed, or that the administrator for this tenant has disabled the application, preventing tokens from being issued for it. Trace ID: c39f256d-76a4-4dee-97d7-b8bf2a373200 Correlation ID: b85d72b6-bcd5-423c-9b3f-456f9ba8d930 Timestamp: 2024-07-15 19:43:43Z","innerError":{"date":"2024-07-15T19:43:43","request-id":"b85d72b6-bcd5-423c-9b3f-456f9ba8d930","client-request-id":"b85d72b6-bcd5-423c-9b3f-456f9ba8d930"}}}'

2024/07/15 20:01:31 wazuh-modulesd:ms-graph[37623] wm_ms_graph.c:249 at wm_ms_graph_scan_relationships(): DEBUG: Microsoft Graph API Log URL: 'https://graph.microsoft.com/v1.0/deviceManagement/managedDevices'
2024/07/15 20:01:31 wazuh-modulesd:ms-graph[37623] wm_ms_graph.c:259 at wm_ms_graph_scan_relationships(): WARNING: Received unsuccessful status code when attempting to get relationship 'managedDevices' logs: Status code was '400' & response was '{"error":{"code":"AuthenticationError","message":"AADSTS500014: The service principal for resource '0000000a-0000-0000-c000-000000000000' is disabled. This indicate that a subscription within the tenant has lapsed, or that the administrator for this tenant has disabled the application, preventing tokens from being issued for it. Trace ID: bc47739b-d08b-4ba5-a4aa-0c080f000d00 Correlation ID: 19e86d2a-d4f3-40d6-a6a2-e3c573e7b725 Timestamp: 2024-07-15 20:01:31Z","innerError":{"date":"2024-07-15T20:01:31","request-id":"19e86d2a-d4f3-40d6-a6a2-e3c573e7b725","client-request-id":"19e86d2a-d4f3-40d6-a6a2-e3c573e7b725"}}}'
```

It appears to be a permission error. I couldn't solve it. This solution (recommended on many sites) didn't work: https://stackoverflow.com/questions/67169671/powershell-getting-aadsts500014-error-while-trying-to-connect-to-exchange-onlin

I'll be asking for help from @vcerenu to try to solve this.

> Note: I had to modify the code to perform this test since the `createdDateTime` filter is not required/allowed for these endpoints.

**Comment by vcerenu** [comment]
The Microsoft Intune trial was used to assign Tomas the license necessary to perform the test.

**Comment by vcerenu** [comment]
The Microsoft Intune trial was used to assign Tomas the license necessary to perform the test.

**Comment by TomasTurina** [comment]
## Update

The MDM Intune API works as expected after the trial was activated. Example usage:

![image](https://github.com/user-attachments/assets/bdd06203-6f83-4add-aef7-a554dc26fe5c)

It can be implemented within the current MS-Graph integration, but will require additional/different configurations and logic.

The team involved in this development should only be the agent team.
