### ISSUE TITLE
Custom log writing to Wazuh

### ISSUE THREAD

**Issue by nidhin077** [wazuh/wazuh#24557]
## Description

I am attempting to push some custom logs that an application has created. Using the compose file from the official repository, I installed Wazhu in the docker container. I then used Wazhu-agent to connect Wazuh to another system. To connect Wazhu to another machine, I used Wazuh-agent. Wazuh and the installation area are configured correctly.

As per the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/monitoring-log-files.html) configured the custom log file to the ossec.conf file of the Wazuh-agent machine. 

When checking the log file (/var/ossec/logs/ossec.log) it seems like 
2024/07/12 02:14:11 wazuh-logcollector: INFO: (1950): Analyzing file: '/home/xxxx/log/xx-xx-xx.log'.
However, the logs are not displaying in the dashboard.

Thus, the custom log writing has me completely confused. Therefore, kindly assist with setting up the relevant dashboard to view the custom log and provide the necessary steps to send the custom log from the remote machine to Wazuh. 

compose file: wazuh-docker-4.8

Awaiting your response.

**Comment by juliancnn** [comment]
Hi @nidhin077,

It looks like you've set up everything correctly. The Wazuh agent is successfully recognizing and analyzing the file as indicated in your `ossec.log`:

```plaintext
2024/07/12 02:14:11 wazuh-logcollector: INFO: (1950): Analyzing file: '/home/xxxx/log/xx-xx-xx.log'.
```

However, seeing the logs in the dashboard depends on whether these logs trigger any security alerts, as the dashboard primarily displays alerts, not raw logs. Since it's a custom log, you may need to create custom decoders and rules to parse and evaluate these logs for security incidents.

Here are some resources to help you get started with custom decoders and rules:
- [Creating Decoders and Rules from Scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/)
- [Sibling Decoders - Flexible Extraction of Information](https://wazuh.com/blog/sibling-decoders-flexible-extraction-of-information/)
- [Official documentation on custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)
- [Testing Decoders and Rules](https://documentation.wazuh.com/current/user-manual/ruleset/testing.html)

On the other hand, [this entry](https://documentation.wazuh.com/current/user-manual/ruleset/index.html#data-analysis) explains how log analysis works, so you will find it very helpful to understand the data flow

If you need further assistance or examples for creating specific decoders or rules, feel free to share some sample logs, and I'd be glad to help you develop them.

Best regards,

**Comment by Niba-nazar** [comment]
Hi @juliancnn,

As per the above details I have tried again, the modification I have made in my `agent-docker container` are as follows:

```
# Modify ossec.conf to monitor the log file
RUN sed -i '/<\/ossec_config>/i \
  <localfile> \
    <log_format>syslog</log_format> \
    <location>/app/hub-prime-application.log</location> \
  </localfile>' /var/ossec/etc/ossec.conf && \
  sed -i 's/<address>[^<]*<\/address>/<address>192.168.2.39<\/address>/' /var/ossec/etc/ossec.conf

# Enable Docker listener
RUN sed -i '/<\/ossec_config>/i \
  <wodle name="docker-listener"> \
    <disabled>no</disabled> \
  </wodle>' /var/ossec/etc/ossec.conf
```

- Restarted the wazuh agent

#### Then on the `wazuh manager-docker conatiner` the following changes I have made:
```
cat /var/ossec/etc/decoders/custom_decoders.xml 
<decoder name="hub-prime-log">
  <program_name>^hub-prime-application</program_name>
</decoder>

<decoder name="hub-prime-log-details">
  <parent>hub-prime-log</parent>
  <regex>^(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (.*)</regex>
  <order>timestamp, message</order>
</decoder>
```

```
cat /var/ossec/etc/rules/custom_rules.xml 
<group name="hub-prime-logs">
  <rule id="100001" level="5">
    <decoded_as>hub-prime-log-details</decoded_as>
    <description>Hub Prime Application log message</description>
    <group>hub-prime,custom</group>
    <options>no_full_log</options>
  </rule>
</group>

```

##### `wazuh-logtest` result:
```
bash-5.2# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.8.0
Type one log per line

2024-06-27 14:11:40 - InteractionsFilter Persist DB /js/NewWindow_2_all.js true (req body true, resp body true)

** Wazuh-Logtest: WARNING: (7612): Rule ID '100001' is duplicated. Only the first occurrence will be considered.

**Phase 1: Completed pre-decoding.
	full event: '2024-06-27 14:11:40 - InteractionsFilter Persist DB /js/NewWindow_2_all.js true (req body true, resp body true)'

**Phase 2: Completed decoding.
	name: 'windows-date-format'
```

- Did the wazuh manager-container restart

Still not able to get the logs on the wazuh manager dashboard.

**Comment by juliancnn** [comment]
Hi @nidhin077,

It seems there might be an issue with how your custom logs are being formatted and recognized by Wazuh. Here's how to potentially resolve this:

1. **Adjust Log Format**: Your logs do not adhere to a standard syslog format, which is likely causing the pre-decoding to fail. Consider modifying your log output to match a standard syslog format, or use the [out_format](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html?highlight=out_format#out-format) option in Logcollector to prepend necessary syslog-like headers to your logs. This can be done as follows:

    ```xml
    <localfile>
        <location>/app/application.log</location>
        <log_format>syslog</log_format>
        <out_format>$(timestamp) $(hostname) custom_program_name: $(log)</out_format>
    </localfile>
    ```

2. **Update Decoders and Rules**:
   - Ensure your decoders match the program name defined in `out_format`.
   - Define a rule that generates alerts for all messages from your custom logs:

    ```xml
    <group name="application-logs">
      <rule id="100002" level="5">
        <decoded_as>custom_program_name</decoded_as>
        <description>Application log message</description>
        <group>app-log,custom</group>
      </rule>
    </group>
    ```

3. **Correct Rule**: Ensure that the rule ID `100002` is not duplicated elsewhere in your ruleset and change the condition for generate an alert:
```xml
<group name="application-logs">
  <rule id="100002" level="5">
    <decoded_as>custom_program_name</decoded_as>
    <description>Application log message</description>
    <group>app-log,custom</group>
  </rule>
</group>
```
```

By following these steps, you should be able to correctly format, decode, and generate alerts from your custom logs. 
This is a basic configuration. If you can see the logs in the dashbord you can start testing and changing the rules and decoders, but I recommend to try this configuration first.


Regards,

**Comment by Dwordcito** [comment]
Closed due to inactivity, thank you for being part of the community, if you need any other help or consider that we have somewhere in the product please create an issue or reopen this if you think it is related.
