### ISSUE TITLE
Support wildcard in Logcollector for Windows

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2455]
Logcollector has wildcard support when running on UNIX:

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/*.log</location>
</localfile>
```

Logcollector uses a UNIX-specific library: _glob_. This library is not available on Windows, to the agent can't resolve wildcards when running on Windows.

Let's make Logcollector support wildcards on Windows, surely the Win32 API has the needed functions to do that.

**Comment by Zenidd** [comment]
This issue was resolved in the PR https://github.com/wazuh/wazuh/pull/3236

I'm closing this ticket.

Regards,

Juan Pablo Sáez
