### ISSUE TITLE
Remote upgrade tool try to upgrade to latest Wazuh version instead of the manager's one

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2458]
## Bug report

**OS**
_Linux_

**Wazuh version**
_all_

**Wazuh API version**
_all_

**Install type**
_manager_

**Install method**
_packages/sources_

**Log sample**

```
root@wazuh-manager:/var/ossec# ./bin/agent_upgrade -l
ID    Name                                Version
001   Windows-hostname      Wazuh v3.7.2

Total outdated agents: 1
root@wazuh-manager:/var/ossec# ./bin/agent_upgrade -a 001
Error 1717: Cannot upgrade to a version higher than the manager: Manager: v3.8.0 / Agent: v3.7.2 -> v3.8.1
root@wazuh-manager:/var/ossec# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.8.0"
REVISION="3805"
DATE="Sat Jan 19 00:57:31 UTC 2019"
TYPE="server"
root@wazuh-manager:/var/ossec#
```

Bug description
----------------

For now, the `agent_upgrade` tool tries to send to the agent the latest released version without matter the manager version. But the upgrade procedure fails when the manager version is lower.

So, currently, to upgrade agents in an outdated manager we have to add `-v <manager_version>` when running `agent_upgrade`.

The desired behavior is to upgrade to the manager version by default, to upgrade to the latest available version we should set the force flag and the version explicitly: `# /var/ossec/bin/agent_upgrade -a 001 -F -v v3.8.1`

**Comment by Leamsy** [comment]
I fixed the `agent_upgrade.py` script so the agent's max version is always the manager's, but broke the -v parameter in the process. I'm still working on it and should be ready by tomorrow.

Best regards.
