### ISSUE TITLE
Release 4.8.1 - RC3 - Demo use cases

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#24639]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release stage issue**     |  #24592                                        |
| **Version**                      | 4.8.1                                                   |
| **Release stage**                | RC 3                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.8.1-rc3          |
| **Previous Demo use cases**      | #24592                                                   |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:green_circle:     | Audit                  |        |
:green_circle:     | AWS Wodle              |        |
:green_circle:     | Brute force            |        |
:green_circle:     | Docker                 |        |
:green_circle:     | Emotet                 |        |
:green_circle:     | FIM                    |        |
:green_circle:     | IP Reputation          |        |
:green_circle:     | Netcat                 |        |
:green_circle:     | Osquery                |        |
:green_circle:     | Shellshock             |        |
:green_circle:     | SQL Injection          |        |
:green_circle:     | Slack                  |        |
:green_circle:     | Suricata               |        |
:green_circle:     | Trojan                 |        |
:green_circle:     | Virustotal             |        |
:green_circle:     | Vulnerability Detector |        |
:green_circle:     | Yara                   |        |
:green_circle:     | Windows Defender       |        |
---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:black_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias

**Comment by davidcr01** [comment]
### Deployment
The deployment succeeded: [JenkinsJob](https://ci.wazuh.info/job/Procedure_deploy_demo/467/console).

### UC Tests
All the automatic UC tests succeeded except for the VD one.
This test was manually validated:
![image](https://github.com/user-attachments/assets/80a9af73-5b60-4fe9-b5be-fa65650ddea3)




#### Slack
The Slack UC was manually validated:
![image](https://github.com/user-attachments/assets/e3c3e89e-c96b-4e7c-995d-506c267338b5)



#### Emotet
The Emotet UC was manually validated:
![image](https://github.com/user-attachments/assets/f88a3bc7-ac8c-4c41-9542-6421a4e4f704)

**Comment by Rebits** [comment]
LGTM
