### ISSUE TITLE
Release 4.9.0 - Alpha 2 - Demo use cases

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#24648]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release stage issue**     |  #24573                                        |
| **Version**                      | 4.9.0                                                   |
| **Release stage**                | Alpha 2                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-alpha2          |
| **Previous Demo use cases**      | #24639                                                   |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:black_circle:     | Audit                  |        |
:black_circle:     | AWS Wodle              |        |
:black_circle:     | Brute force            |        |
:black_circle:     | Docker                 |        |
:black_circle:     | Emotet                 |        |
:black_circle:     | FIM                    |        |
:black_circle:     | IP Reputation          |        |
:black_circle:     | Netcat                 |        |
:black_circle:     | Osquery                |        |
:black_circle:     | Shellshock             |        |
:black_circle:     | SQL Injection          |        |
:black_circle:     | Slack                  |        |
:black_circle:     | Suricata               |        |
:black_circle:     | Trojan                 |        |
:black_circle:     | Virustotal             |        |
:black_circle:     | Vulnerability Detector |        |
:black_circle:     | Yara                   |        |
:black_circle:     | Windows Defender       |        |
---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:black_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias

**Comment by rauldpm** [comment]
Skipped until Alpha 3 so we have 4.8.1 RC 4 changes
