### ISSUE TITLE
Footprint 4.9.0 Big decrease in the events and messages

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#24663]
## Description

Analyzing the footprint tests in the issue https://github.com/wazuh/wazuh/issues/24598, a large decrease in the events and messages generated is noted. However, no error was detected in the logs that demonstrate the decline of the events.
This was detected in CentOS and Ubuntu agents:

<details>
   <summary>CentOS</summary>
   <br/>

- **Events_buffered:** Much less load is noted in the number of buffered events.
- **Events_generated:** Fewer events generated.
- **number_of_messages:** Fewer messages generated.

</details>

<details>
   <summary>Ubuntu</summary>
   <br/>

- **Events_buffered:** Much less load is noted in the number of buffered events.
- **Events_generated:** Fewer events generated.
- **number_of_messages:** Fewer messages generated.

</details>

Compare with: 
- https://github.com/wazuh/wazuh/issues/24005

Graphs:

4.9.0:

![image](https://github.com/user-attachments/assets/0e91b072-3b4d-4c5e-bcb1-875f296ff057)
![image](https://github.com/user-attachments/assets/6e20b9c4-712a-4411-81e1-321b6b8950b9)
![image](https://github.com/user-attachments/assets/881c6976-f4a9-4e46-856f-d01f413a697f)

4.8.0:
![image](https://github.com/user-attachments/assets/a3ba3c40-b60d-453f-b0fa-e9a12af2dfd9)
![image](https://github.com/user-attachments/assets/d7f8fe49-159b-4bac-84d2-ab14721466ad)
![image](https://github.com/user-attachments/assets/5a60add7-5a7e-4fbc-9f46-34eb3461e0b9)

Further research is required.

**Comment by cborla** [comment]
# Analysis
As a first observation, I can say that there is a difference in the agent configuration, for the case of 4.9.0 the Ubuntu agent has configured the interval in 60 seconds, while in 4.8.0 the syscollector interval is 10 seconds.

![image](https://github.com/user-attachments/assets/9e482a98-ab89-4608-a39f-b8bc00c329d9)

**Comment by cborla** [comment]
In the `tmp/logcollector_test/logcollector.log` files of each test we have a big difference in the generation of events.

- 4.8.0
  - `Appended message to 100 files`. Appears 14,980 times
  - `Appended message to 1000 files`.  Appears 168 times
  - Total Appended messages: 1.666.000
- 4.9.0
  - `Appended message to 100 files`. Appears 400 times
  - `Appended message to 1000 files`.  Appears 168 times
  - Total Appended messages: 208,000

In the manager statistics we see that in 4.9.0 it received less than 10% of the logcollector events it received in the 4.8.0 test.
![image](https://github.com/user-attachments/assets/aa959607-a97c-482c-a6ce-abbc52b46452)

**Comment by rauldpm** [comment]
Syscollector change: https://github.com/wazuh/wazuh/issues/24663#issuecomment-2236507539

Related to https://github.com/wazuh/wazuh-jenkins/pull/6651

The default value for Syscollector was changed and the test was adapted

**Comment by cborla** [comment]
After the analysis, we understand that the problem lies in the test itself, which behaves differently from previous versions.
The QA team is going to analyze this behavior:
- https://github.com/wazuh/wazuh-qa/issues/5584
