### ISSUE TITLE
Wazuh 4.8 - Vulnerability False Positive - OFFICE SUITE - MacOS

### ISSUE THREAD

**Issue by CyberOverflow** [wazuh/wazuh#24678]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.8.0 | Vulnerability Engine | Manager/Agent | macOS |

With the upgrade to the new Wazuh 4.8.0 engine, the manager reports finding vulnerabilities in office suite products from 2000 when the applications are up to date on the latest version.

![image](https://github.com/user-attachments/assets/79019eee-1245-4ede-afe9-9cceedf407be)

**Comment by GabrielEValenzuela** [comment]
Hi @CyberOverflow!

We are currently working on a fix for this issue. You can follow our progress here: [GitHub Issue #24174](https://github.com/wazuh/wazuh/issues/24174).

We hope to have the solution soon. Please check the issue status to stay updated on our progress.

Thanks for your cooperation, and have a great Friday!

**Comment by sebasfalcone** [comment]
## Conclusion
- Known issue
- The resolution will be done in a private repository
  - https://github.com/wazuh/intelligence-platform/issues/1623
