### ISSUE TITLE
Vulnerability Index Pattern Not Persisting After Restart

### ISSUE THREAD

**Issue by Stuti3097** [wazuh/wazuh#24674]
**Description:**
After performing a refresh of the index in the Index Management > Indexes section and selecting wazuh-states-vulnerabilities-*, It updates the index pattern, which regenerates the pattern and results in 51 fields. This resolves the display errors in the dashboard. However, upon restarting the Wazuh manager and indexer, this change is lost, and the dashboard errors reappear. Reapplying the procedure resolves the issue temporarily, but it does not persist through restarts.

**Steps to Reproduce:**
Go to Index Management > Indexes.
Select wazuh-states-vulnerabilities-*.
In Actions, select refresh to regenerate the index pattern.
Observe that the dashboard displays correctly with 51 fields.
Restart the Wazuh manager and indexer.
Observe that the dashboard errors reappear and the index pattern changes are lost.

**Expected Behavior:** The updated index pattern should persist after restarting the manager and indexer, and the dashboard should display correctly without requiring the procedure to be reapplied.

**Current Behavior**: The updated index pattern does not persist after restarts, causing the dashboard to display errors until the index pattern is regenerated again.

**Environment:**
Wazuh Version: 4.8.0
Module: Vulnerability Detection

![image (44)](https://github.com/user-attachments/assets/7bdb3904-c701-4bdc-8f8c-1970b63818f8)
![image (46)](https://github.com/user-attachments/assets/e108d94b-5ed8-4736-b360-36525109e4aa)
![image (47)](https://github.com/user-attachments/assets/d1611eb6-cafd-4cc5-ba49-9b734fe0e398)
![image (45)](https://github.com/user-attachments/assets/86c2b94a-7d97-4bc5-b2d3-467f8daf4043)

Issue link: https://wazuh.slack.com/archives/C0A933R8E/p1720072218359959

**Comment by Pr0xyBu6** [comment]
Hello, if any other information related to the issue is needed, let me know and I will be glad to provide it. I look forward to hearing from you. Thanks

**Comment by sebasfalcone** [comment]
## Update
Started investigation with Indexer and Dashboard teams

**Comment by sebasfalcone** [comment]
## Update
We weren't able to reproduce this issue

**Comment by sebasfalcone** [comment]
@Pr0xyBu6 Hi! How are you doing?

If this is happening to you too, could you share the new template you created?

**Comment by sebasfalcone** [comment]
## Pending final review
Users are inactive, we are unable to continue the investigation
