### ISSUE TITLE
Hide undesired messages in the package generation script

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24676]
# Description

The package generation script in 4.9.0 https://github.com/wazuh/wazuh/commit/18f6364f14f0ccefb1f1096ed8685a764bd1d64c script shows debug info when used for any command, this info should be hidden as shows more information than needed, for example, I wanted to check the help message and I obtained this

![image](https://github.com/user-attachments/assets/fb88cd8e-6a6f-437d-8eb2-f9f1a8925cf3)

The script should show only the main messages, not the `+` messages unless desired

This is produced by the https://github.com/wazuh/wazuh/blob/master/packages/generate_package.sh#L11 (`set` command), specifically the `x` option, consider adding an option to use `set -e` or `set -ex`

**Comment by lchico** [comment]
# Update
I created a PR, and it’s ready for review.

**Comment by lchico** [comment]
# Update
Considering that the [PR](https://github.com/wazuh/wazuh/pull/24724) removes the verbose mode by default, I have created another [PR](https://github.com/wazuh/wazuh-agent-packages/pull/66) in **wazuh-agent-packages** to make our workflow verbose. I have a pending test for it.

**Comment by lchico** [comment]
# Update
The pull request is ready for review. There's an unrelated issue with the macOS package generation test failing because "ValueError: macStadium ARM server is full capacity, use AWS provider."
