### ISSUE TITLE
Benchmarking tests: Saturation tools for Wazuh agent's modules

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#24680]
# Description

We need to develop tools to customize the saturation of various Wazuh agent modules. These tools should be capable of generating a specified number of events within a defined time frame.

## Modules lists

The proposed modules to be saturated in this iteration are:

- Logcollector (Basic plain event collection)
- Syscheck (Creation, deletion and modification events)

## Functional requirements

- Develop a Python library capable of generating a specified number of events per second for the configured modules.
- Create a Python script that uses the libraries developed in https://github.com/wazuh/wazuh/issues/24737 to configure and restart the agent, and to stimulate the configured modules based on a YAML configuration file.

## Non-functional requirements

- Supported Operating Systems: macOS, Windows, Linux
- Maintainability: Use an object-oriented class structure to facilitate the inclusion of new event types in the future.

## Deliverable

- Python modules capable of saturating the Logcollector and Syscheck modules.
- A Python script that allows triggering event saturation based on a YAML configuration.

## Dependencies

- https://github.com/wazuh/wazuh/issues/24737

**Comment by jseg380** [comment]
On hold due to testing of 4.9.0 - Alpha 3

**Comment by santipadilla** [comment]
## Design the Event Generator Library

This library will handle the generation of events at a defined rate. Here’s what we should aim to accomplish:

- Create a base class for event generation:
  - This class will handle the timing and rate of event generation.

- Implement a method to generate events:
  - This method will be a placeholder in the base class and overridden by subclasses for specific types of events (log entries, file modifications...)

**Comment by santipadilla** [comment]
Moved to on hold due to [this issue](https://github.com/wazuh/wazuh-jenkins/issues/6658).

**Comment by santipadilla** [comment]
## Python script

- Entry point for running the event generators. It parses command-line arguments to configure the type of generator, target path for operations, and number of operations.

- Supports specifying whether to test logcollector or syscheck through command-line options, making it versatile for different testing scenarios.

- Usage:

  - The script is executed via the command line, where the user specifies:

     - The module to saturate (log for logcollector or file for syscheck).
     - The path to the target file or directory for operations.
     - The number of operations to perform.
     - Example: `python3 main.py --module log --path /path/to/logfile.log --operations 100`

**Comment by santipadilla** [comment]
## Update

As we modify or add functionality to the library or the script we will update the different comments.

Comment of the library [here](https://github.com/wazuh/wazuh/issues/24680#issuecomment-2252827845) and comment of the script [here](https://github.com/wazuh/wazuh/issues/24680#issuecomment-2258561486).

We begin with a command line approach, then with a YAML configuration file, we have thought to leave only the YAML configuration file, since with command line when we have many files and each one has its own configuration it can become something complicated, reason why the configuration file facilitates that part to us in the future.

Therefore at the time of launching the script we will only have to define the configuration file and if we want the debug mode. Like this: `python3 main.py --config config.yaml --debugmode`

Currently investigating how to implement a template for the logs.

**Comment by santipadilla** [comment]
Moved to on hold due to [this issue](https://github.com/wazuh/wazuh-jenkins/issues/6825).

**Comment by santipadilla** [comment]
## Update

Logcollector class and script working correctly, modifying the configuration file and restarting the agent manually. These actions will be implemented later in methods, when we have the 5.0 version configuration, for the automation of these tasks.

Development of syscheck class in progress.

**Comment by Rebits** [comment]
Delayed ETA to allow review of the development

**Comment by santipadilla** [comment]
Moved to on hold due to [this issue](https://github.com/wazuh/wazuh/issues/25185) of 4.9.0

**Comment by santipadilla** [comment]
Moved to on hold due to [4.8.2 testing](https://github.com/wazuh/wazuh/issues/25270)

**Comment by santipadilla** [comment]
## Update

Class for logcollector and syscheck working correctly as well as the script.
Test development in progress

**Comment by santipadilla** [comment]
## Update

Documenting all files under the [pep8 standard](https://peps.python.org/pep-0008/).

**Comment by santipadilla** [comment]
## Update

Created branch: `enhancement/24680-saturation-tools-for-agent-modules`
In this PR: https://github.com/wazuh/wazuh-qa/pull/5697

**Comment by rafabailon** [comment]
### LGMT

I have reviewed the code and the changes and it seems to be fine. I have also tried to run the code, run the tests and I have not had any problems.

**Comment by Rebits** [comment]
Delayed to allow final review 20/09/2024

**Comment by Rebits** [comment]
LGTM
