### ISSUE TITLE
Vulnerability Detector - RPM upgrade won't download new content

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24699]
## Description
While performing the RCA of this issue:
- https://github.com/wazuh/wazuh-jenkins/issues/6760

It was found that the [RPM upgrades](https://github.com/wazuh/wazuh-jenkins/issues/6760#issuecomment-2237483677) on the manager won't trigger the download of the latest VD compressed content

We need to investigate the root cause of this issue and fix it.

>[!NOTE]
> [Upgrades from deb packages](https://github.com/wazuh/wazuh-jenkins/issues/6760#issuecomment-2237700254) do trigger the download

## DoD
- [x] Root cause found
- [x] Solution proposed
- [x] Solution tested

**Comment by MiguelazoDS** [comment]
# Analysis 

I don't see how the package installation can trigger a download, what it should do is put the compressed file in the /var/ossec/tmp so then the vulnerability scan module can decompress it.

**Comment by sebasfalcone** [comment]
## DRI change
Due to E2E testing, we changed the DRI of this issue from @MiguelazoDS to @pereyra-m

**Comment by pereyra-m** [comment]
## Update

I try to reproduce the issue and find the root cause

**Comment by pereyra-m** [comment]
## Update

The issue seems to be related to the recent addition of the `missingok` configuration to the vulnerability detector content file. I'm creating new packages to confirm this.

**Comment by sebasfalcone** [comment]
## Update
Moved issue to 4.9.1 release
