### ISSUE TITLE
Review and fix Python security scan alerts

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#24709]
## Description

During the last weekly security scan, we noticed that the [Python code analysis](https://github.com/wazuh/wazuh/actions/runs/9954785283) workflow found several weaknesses in the API, framework and wodles Python code.

We should review the alerts and fix them if appropriate, or mark them as false positive leaving a comment that explains the reason.

Code scanning alerts: https://github.com/wazuh/wazuh/security/code-scanning

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Review alerts.
- [x] Apply fixes and/or dismiss the alerts.

**Comment by GGP1** [comment]
## Update

The scanning alerts related to the PyServer team are:

- [x] [Possible hardcoded password: ''](https://github.com/wazuh/wazuh/security/code-scanning/3411): dismissed, the string `''` is the `password` parameter default value. It may be empty if the client uses certificates for authentication (perhaps the client should enforce that certificates are used if the password is empty).
- [x] [Possible hardcoded password: 'client_cert_password'](https://github.com/wazuh/wazuh/security/code-scanning/3410): dismissed, the variable corresponds to a field name, not to a password value.
- [x] [Consider possible security implications associated with the subprocess module](https://github.com/wazuh/wazuh/security/code-scanning/3336): dismissed, the [security flaw](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments) is related to the `shell=True` parameter, as it could make a program vulnerable to [shell injection](http://en.wikipedia.org/wiki/Shell_injection#Shell_injection). But in our case we don't specify that argument.

**Comment by GGP1** [comment]
## Update

The scanning alerts related to the PyServer team were:

- [x] [Possible hardcoded password: ''](https://github.com/wazuh/wazuh/security/code-scanning/3411): dismissed, the string `''` is the `password` parameter default value. It may be empty if the client uses certificates for authentication (perhaps the client should enforce that certificates are used if the password is empty).
- [x] [Possible hardcoded password: 'client_cert_password'](https://github.com/wazuh/wazuh/security/code-scanning/3410): dismissed, the variable corresponds to a field name, not to a password value.
- [x] [Consider possible security implications associated with the subprocess module](https://github.com/wazuh/wazuh/security/code-scanning/3336): dismissed, the [security flaw](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments) is related to the `shell=True` parameter, as it could make a program vulnerable to [shell injection](http://en.wikipedia.org/wiki/Shell_injection#Shell_injection). But in our case we don't specify that argument.

All the others belong to the `src/` folder, which is under heavy development and maintained by other teams.

**Comment by javiersanchz** [comment]
LGTM !

**Comment by fdalmaup** [comment]
The scan alerts have been correctly analyzed and dismissed, LGTM!
