### ISSUE TITLE
Release 4.9.0 - Alpha 3

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24714]
The following issue will gather all the info regarding testing and fixing in order to validate this release stage.

The definition of done for this task is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes, all the issues from below must be closed.

## QA testing issues

In order to move to a new stage or the GA version, all tests and metrics analyses below must be in Closed status.

| Name                        | Issue                                         | Status      |DRI|
|-----------------------------|-----------------------------------------------|-------------|---|
| Footprint metrics | https://github.com/wazuh/wazuh/issues/24715 | :red_circle: Completed with failures  |@wazuh/devel-qa|
| C unit | https://github.com/wazuh/wazuh/issues/24934 |:purple_circle: Completed |@wazuh/devel-agent|
| Python unit | https://github.com/wazuh/wazuh/issues/24895 | :yellow_circle: Completed with accepted known issues  |@wazuh/devel-pyserver|
| Ruleset | https://github.com/wazuh/wazuh/issues/24919 |:purple_circle: Completed |@wazuh/devel-threatintel|
| Coverity scan | https://github.com/wazuh/wazuh/issues/24887 | :purple_circle: Completed |@wazuh/devel-agent|
| Packages | https://github.com/wazuh/wazuh/issues/24716 |:red_circle: Completed with failures  |@wazuh/devel-qa|
| Installation assistant | https://github.com/wazuh/wazuh/issues/24874 | :red_circle: Completed with failures<br>:brown_circle: AL2   | @wazuh/devel-devops|
| WPK agent upgrade | #24876 |:red_circle: Completed with failures |@wazuh/devel-agent|
| Docker and Kubernetes upgrade | - | :white_circle: Skipped |@wazuh/devel-devops|
| Integration | https://github.com/wazuh/wazuh/issues/24915 |  :red_circle: Completed with failures  |@wazuh/devel-qa|
| API integration | #24893 | :red_circle: Completed with failures |@wazuh/devel-pyserver|
| External integrations modules | https://github.com/wazuh/wazuh/issues/24896 | :yellow_circle: Completed with accepted known issues | @wazuh/devel-pyserver|
| System | https://github.com/wazuh/wazuh/issues/24916 | :purple_circle: Completed | @wazuh/devel-qa|
| Workload benchmarks | #24894 | :red_circle: Completed with failures |@wazuh/devel-pyserver|
| Demo uses cases | https://github.com/wazuh/wazuh/issues/24875 | :purple_circle: Completed |@wazuh/devel-devops|
| UI regression | https://github.com/wazuh/wazuh-dashboard-plugins/issues/6860 | :red_circle: Completed with failures | @wazuh/devel-dashboard|
| Vulnerability detection | https://github.com/wazuh/wazuh/issues/24808 | :red_circle: Completed with failures  | @wazuh/devel-qa |
| E2E UX | https://github.com/wazuh/wazuh/issues/24871 | :red_circle: Completed with failures | @wazuh/devel-qa |

:white_circle: Skipped: The task has been deemed unnecessary for this stage.
:brown_circle:  Partially skipped:  Some parts of the task are skipped.
:black_circle: Not finished: The tasks haven't been finished yet.
:purple_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.
:yellow_circle: Completed with accepted known issues (new): Some issues were raised here, they were deemed non stopper.

**Comment by juliamagan** [comment]
### New issues

- https://github.com/wazuh/wazuh-qa/issues/5613
- https://github.com/wazuh/wazuh-qa/issues/5614
- https://github.com/wazuh/wazuh-qa/issues/5615
- https://github.com/wazuh/wazuh-qa/issues/5616
- https://github.com/wazuh/wazuh-jenkins/issues/6793
- https://github.com/wazuh/wazuh/issues/24950
