### ISSUE TITLE
Develop fleet management use cases

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#24711]
|Objective|
|---|
| #22677 |

# Description 

As part of the MVP implementation of the upcoming [**Comms API** ](https://github.com/wazuh/wazuh/issues/24305), the [new registration system](https://github.com/wazuh/wazuh/issues/24294) part of the Server management API and following the work being carried out by the @wazuh/devel-dashboard team in the [AcA UX Spike](https://github.com/wazuh/wazuh-dashboard/issues/209), we must analyze and implement the necessary use cases to be considered related to the management of the agents.

Considering the possible responses, these use cases should define the complete sequence corresponding to the interaction of the involved endpoints and components.

Proposed use cases:
  - Agent registration
  - Agent deletion
  - Agent listing

##  Plan
- Analyze how the proposed use cases currently work and the available used parameters.
- Determine the required changes for the complete implementation of the fleet management use cases, including parameters no longer supported or that will require a new definition. 
- Implement the mentioned use cases to achieve the minimal functionalities and define any structural changes to be carried out in other issues:
  - [x] [Agent registration](https://github.com/wazuh/wazuh/issues/24711#issuecomment-2298447957)
      - [x] Define the minimum requirements that the agent key must meet and implement the corresponding verification mechanism.
  - [x] Agent deletion
  - [x] Agent restart
  - [x] Agent listing

**Comment by fdalmaup** [comment]
### Agent Registration

The basic agent registration use case has been developed in:
- https://github.com/wazuh/wazuh/pull/25197

It accepts the following body:
```json
{
  "id": "uuid",
  "name": "agent_name",
  "key": "agent_key"
}
```

Batch agent creation passing a list of agent parameters is not allowed. 

Agent registration involving group assignments has not been developed. Once the changes in https://github.com/wazuh/wazuh/issues/25122 have been carried out, we must implement this use case allowing the insertion of the `agent.groups` field in the [`agents` index](https://github.com/wazuh/wazuh-indexer/issues/270#issuecomment-2176507169).

**Comment by nico-stefani** [comment]
# Update

I've been analyzing how to use the fields on the agent list in a query to the indexer.

**Comment by nico-stefani** [comment]
# Agent list analysis

According to the agent schema defined in https://github.com/wazuh/wazuh-indexer/issues/270#issuecomment-2176507169 the current set of query params of the endpoint can be translated in the next way:

| Current Field | Eq Field | Note |
|--------|--------|--------|
| offset | from | Query param of the `_search` endpoint |
| limit | size| Query param of the `_search` endpoint |
| select | _source_includes | Query param of the `_search` endpoint |
| sort | sort | Query param of the `_search` endpoint |
| search | - |  |
| q | q | Query param of the `_search` endpoint that uses Lucene query language |
| status | - | In 5.0 the status is interpreted |
| agents_list | agent.id | Field of the `agents` index |
| older_than| agent.last_login	| Field of the `agents` index |
| os.* | - | Information not present in the `agents` index |
| manager | agent.node_name | Field of the `agents` index |
| name | agent.name | Field of the `agents` index |
| group | agent.groups | Field of the `agents` index |
| ip,registerIp | - | Information not present in the `agents` index |
| group_config_status | - | Information not present in the `agents` index |
| distinct | - | Option not available |

Regarding the behavior of the query itself, it is possible to identify three ways to do it:

1. Adopts the Lucene as the query language and receives the `q` param containing the query. Here the management API will receive and pass the `q` to the indexer and only parse the results to form the response.

2. Receive all the query parameters, like the current behavior, construct the query, pass it to the indexer, and process the results to form the response.

3. The last one will be a mix of the previous, receive the `q` along the other query params, and define a priority of one of the methods. For example, if the `q` is present this will be used and the other params omitted.

We need to discuss this as a team to define how to continue.

**Comment by nico-stefani** [comment]
# Update

I've been implementing the needed changes in the `GET /agents` endpoint to adapt the query params according to the proposal.

**Comment by nico-stefani** [comment]
# Update

We discussed the requirements of the `key` team and we decided:
* Fix the length to 32 chars
* Use uppercase, lowercase, and digits

**Comment by nico-stefani** [comment]
# Update

I've been working on the logic to filter the agent's records fc42ffa6048d85aef86c6c8f649891f2539a8325.

Also, worth mentioning that the [agent index definition](https://github.com/wazuh/wazuh-indexer/issues/270#issuecomment-2176507169) was updated. This will need to carry out extra changes like updating the model and adding more filters to the list endpoint.

**Comment by nico-stefani** [comment]
# Update

* Fixed length of the agent key
* Added validation for the uuid7 in `POST /agents`

**Comment by nico-stefani** [comment]
# Update

* Fixing and updating framework unittests

**Comment by nico-stefani** [comment]
# Update

* Fixed current UT's
* Added UT's
* Skipped AIT's
