### ISSUE TITLE
Integration API endpoints test faling after upward merge

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24727]
|Wazuh version|Component|
|---|---|
| 5.0.0| API |

## Description
One of the integration tests is failing after merging 4.10.0 into master:
- #24712

|        Test name         | Status |         Plain report         |         HTML report          |             Test logs             |
|--------------------------|--------|------------------------------|------------------------------|-----------------------------------|
| test_agent_GET_endpoints | ❌      | [test_agent_GET_endpoints.txt](https://ci.wazuh.info/job/Test_integration_endpoints/4695/artifact/artifacts/Test_integration_endpoints_B4695_test_agent_GET_endpoints.txt) | [test_agent_GET_endpoints.zip](https://ci.wazuh.info/job/Test_integration_endpoints/4695/artifact/artifacts/Test_integration_endpoints_B4695_test_agent_GET_endpoints.zip) | [test_agent_GET_endpoints_logs.zip](https://ci.wazuh.info/job/Test_integration_endpoints/4695/artifact/artifacts/Test_integration_endpoints_B4695_test_agent_GET_endpoints_logs.zip) |

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
The issue has already been analyzed in the following issues:
- https://github.com/wazuh/wazuh/issues/24106
- https://github.com/wazuh/wazuh/issues/24401

Given that the error is sporadic and the upcoming changes that will be carried out for 5.0, we can dismiss this issue.
