### ISSUE TITLE
Kaspersky active-response not writing logs

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#2475]
Hi everyone,

There is an issue with the Kaspersky integration with active response.

The [kaspersky.py](https://github.com/wazuh/wazuh/blob/master/active-response/kaspersky.py) script do not write a new entry in the `active-response.log` like the other scripts do.

https://github.com/wazuh/wazuh/blob/97c8c61da5b32f6198e7c7848a8deaffbaff4dfc/active-response/host-deny.sh#L79

This causes the active response to not leave any track of the time it was executed.

Also, in the script [kaspersky.sh](https://github.com/wazuh/wazuh/blob/v3.8.1/active-response/kaspersky.sh) , no error would be generated if the python script is not able to run.

Best regards,
Miguel

**Comment by snaow** [comment]
Merged: https://github.com/wazuh/wazuh/pull/2748
