### ISSUE TITLE
Dynamic scaling of retain_db_records for AWS Wodle

### ISSUE THREAD

**Issue by UranusBytes** [wazuh/wazuh#2476]
## Feature request

**Compatibility**
Manager

**Component involved**
AWS Wodle

Description
--------------

If an execution of `iter_files_in_bucket` processes more objects than the value of `retain_db_records`, the execution of `db_maintenance` will delete the oldest records of the object_list stored in the DB.  At next execution, the older files will be re-processed.  At minimum, this can cause duplicate event processing; at worse it can create an infinite loop such that the wodle is never able to progress forward between executions.

Suggestion:  At the end of `iter_files_in_bucket`, scale the value of `retain_db_records` sufficiently that all records within a single execution (plus 10%) are kept.  This will prevent reprocessing of records, yet limit the growth of the sqlite DB to the minimum required record count.

**Comment by druizz90** [comment]
Hi,

This issue was solved in #2978.

Best regards,

Demetrio.
