### ISSUE TITLE
Release 4.9.0 - Alpha 3 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24810]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |            https://github.com/wazuh/wazuh/issues/24714                   |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/24808                       |
| **Version**                          |                   4.9.0                         |
| **Release stage**              |                   Alpha 3                      |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.9.0-alpha3                               |
| **Previous Vulnerability performance tests issue**      |       https://github.com/wazuh/wazuh/issues/24504                    |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 25 | 3 | 50000 | 1 | 60 | 100 | 1h |

**Considerations**

- `KIBANA_API_REQUESTS` should be enabled
- `EXTRA_LOAD_API_REQUESTS` should be enabled
- Due to the current operation of the simulator and how it does the EPS distribution with the frequency, we can expect the actual EPS to be about half, so it is necessary to set twice as much.

#### New issues

- https://github.com/wazuh/wazuh-jenkins/issues/6801

**Comment by rauldpm** [comment]
## Builds

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/587
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/588
- Very high: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/589

**Comment by rauldpm** [comment]
## Analysis report

- Medium and High activity failed due to:

```
20:14:26  TASK [Copy wazuh-cluster.log file to data files] *******************************
20:14:26  [WARNING]: Platform linux on host CLUSTER-
20:14:26  Workload_benchmarks_metrics_B587_dashboard is using the discovered Python
20:14:26  interpreter at /usr/bin/python, but future installation of another Python
20:14:26  interpreter could change this. See [https://docs.ansible.com/ansible/2.9/referen](https://docs.ansible.com/ansible/2.9/referen%1B[0m)
20:14:26  ce_appendices/interpreter_discovery.html for more information.
20:14:26  fatal: [CLUSTER-Workload_benchmarks_metrics_B587_dashboard]: FAILED! => {
20:14:26      "ansible_facts": {
20:14:26          "discovered_interpreter_python": "/usr/bin/python"
20:14:26      },
20:14:26      "changed": false
20:14:26  }
20:14:26  
20:14:26  MSG:
20:14:26  
20:14:26  Source /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log not found
```

- Very High failed due, expected to fail due to the previous error:

```
23:47:34  hudson.remoting.ProxyException: org.wazuh.JenkinsException: Generic exception.Number of workers exceeded. Max is 30
```


## Related

- https://github.com/wazuh/wazuh-documentation/pull/6810
- https://github.com/wazuh/wazuh-dashboard-plugins/issues/6137

**Comment by pro-akim** [comment]
## Review Notes
LGTM
