### ISSUE TITLE
Release 4.9.0 - Alpha 3 - Demo use cases

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh#24875]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release stage issue**     |  #24714                                        |
| **Version**                      | 4.9.0                                                   |
| **Release stage**                | Alpha 3                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-alpha3          |
| **Previous Demo use cases**      | #24639                                                  |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:green_circle:     | Audit                  |        |
:green_circle:     | AWS Wodle              |        |
:green_circle:     | Brute force            |        |
:green_circle:     | Docker                 |        |
:green_circle:     | Emotet                 |        |
:green_circle:     | FIM                    |        |
:green_circle:     | IP Reputation          |        |
:green_circle:     | Netcat                 |        |
:green_circle:     | Osquery                |        |
:green_circle:     | Shellshock             |        |
:green_circle:     | SQL Injection          |        |
:green_circle:     | Slack                  |        |
:green_circle:     | Suricata               |        |
:green_circle:     | Trojan                 |        |
:green_circle:     | Virustotal             |        |
:green_circle:     | Vulnerability Detector |        |
:green_circle:     | Yara                   |        |
:green_circle:     | Windows Defender       |        |
---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:black_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @wazuh/devel-qa-release

**Comment by CarlosALgit** [comment]
## Deployment
The deployment succeeded: [JenkinsJob](https://ci.wazuh.info/job/Procedure_deploy_demo/471/console).

## UC Tests

All the automatic UC tests succeeded except for the VD one.
This test was manually validated:
![image](https://github.com/user-attachments/assets/205ddedf-3cad-48c6-94b9-e4842e58610e)
