### ISSUE TITLE
Add and verify new QA Test Cases for VDP v1.0.1

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#24900]
## Description

The new version of VDP v1.0.1 aims to address false positives and false negatives in vulnerability detection. As part of the release verification process, it is essential to run tests that validate the changes in the content. Issue [Define New QA Test Cases for VDP v1.0.1](https://github.com/wazuh/intelligence-platform/issues/1660#top) identifies new test cases to be added.

## Expected

1. **Add New Test Cases:**
   - Integrate the new test cases identified in Issue [Define New QA Test Cases for VDP v1.0.1](https://github.com/wazuh/intelligence-platform/issues/1660#top) into the existing [QA test suite for the vulnerability detector](https://github.com/wazuh/wazuh/tree/v4.8.1/src/wazuh_modules/vulnerability_scanner/qa).
   
2. **Execute Tests:**
   - Run the QA test suite with the [new content introduced in VDP v1.0.1](https://drive.google.com/file/d/1nHMjcf--vq25H_Z_laLWJwrdCkW-0KnN/view?usp=sharing).
   - Ensure that all new test cases pass successfully and verify that the behavior is as expected.

3. **Analyze Test Results:**
   - Review the results of the test execution.
   - Identify if any of the existing test cases fail and analyze the reason for the failure.
   - Document any issues found and provide an analysis of the root cause.

## Deliverables

- [x] Updated QA Test Suite: The QA test suite updated with new test cases from Issue [Define New QA Test Cases for VDP v1.0.1](https://github.com/wazuh/intelligence-platform/issues/1660#top).
- [x] Test Execution Report: A detailed report of the test execution results, including any identified issues and their root causes.

By completing these steps, we aim to ensure that VDP v1.0.1 effectively resolves false positives and negatives, enhancing the accuracy and reliability of vulnerability detection.

**Comment by jftuduri** [comment]
# Update
- Setup local environment.
- Fixed existing test cases that were failing when the new v1.0.1 content was used.

**Comment by jftuduri** [comment]
# Update
- Added all the new test cases.

**Comment by jftuduri** [comment]
# Update 
- Added new [commit](https://github.com/wazuh/wazuh/pull/24906/commits/2a88f4591079ed15b0236370b46ce140228d1dc1) to fix failing test due to recent sanitizations.
- vulnerability-scanner-module-qa tests successful: https://github.com/wazuh/wazuh/actions/runs/10254551174/job/28369587153?pr=24906
