### ISSUE TITLE
Warning message in vulnerability-scanner about empty package name

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24905]
# Description

The following message related to vulnerability-scanner was found in the v4.9.0-alpha3 AMI

```
2024/07/22 19:09:02 wazuh-modulesd:vulnerability-scanner: WARNING: Failed to scan package: '', CVE Numbering Authorities (CNA): 'nvd', Error: 'Invalid package/cna name.'.
```

There is no package name indicated, we need to review this and check if this warning is legit or if there is some problem with a package name fetch

Note: This AMI has been used to test the AIX, HP-UX, and Solaris SPARC v4.9.0-alpha3 agents, checking the agent's status and removing them using the manage_agent binary

**Comment by Dwordcito** [comment]
Could you give us the local databases of syscollector agents ?

We need this file from all agents. (this database resides inner the agent)
/var/ossec/queue/syscollector/db/local.db

**Comment by rauldpm** [comment]
@Dwordcito No, those agents are only rented for 24 hours and the machines no longer exist, you can ask devops team to deploy the AMI and those systems to try to reproduce the error

We will take into account this in the next stage (Beta 1) testing, but in the meantime, the machines can be rented

**Comment by Dwordcito** [comment]
Moved to the agent team, these issues come from a report of an empty package name on the agent side.

The data on the server side is not mutable.

**Comment by MarcelKemp** [comment]
Due to the lack of information about the special OS that is causing the empty package error, we will wait for the next special OS testing to verify the problem and have it replicated.
