### ISSUE TITLE
Release 4.9.0 - Alpha 3 - Integration tests

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24915]
# Description
|| | 
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/24714 |
| **Version**                      | 4.9.0                                                   |
| **Release stage**            | Alpha 3                                                    
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.9.0-alpha3         |
| **Wazuh QA: Branch**    | `4.9.0`
| **Wazuh Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-alpha3         |
| **Wazuh Branch**    | `4.9.0`
| **Previous test** | https://github.com/wazuh/wazuh/issues/24438 |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build***:  https://ci.wazuh.info/job/Test_integration_launcher/259/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47674/manager_html_report_Test_integration_B47674.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47675/agent_centos_html_report_Test_integration_B47675.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47675/agent_windows_html_report_Test_integration_B47675.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47676/agent_centos_html_report_Test_integration_B47676.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47676/agent_windows_html_report_Test_integration_B47676.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47677/manager_html_report_Test_integration_B47677.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47678/agent_centos_html_report_Test_integration_B47678.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47678/agent_windows_html_report_Test_integration_B47678.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47679/manager_html_report_Test_integration_B47679.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47681/agent_macos_html_report_Test_integration_B47681.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47681/agent_solaris_html_report_Test_integration_B47681.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47682/manager_html_report_Test_integration_B47682.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47683/manager_html_report_Test_integration_B47683.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47684/agent_centos_html_report_Test_integration_B47684.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47684/agent_windows_html_report_Test_integration_B47684.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47684/agent_macos_html_report_Test_integration_B47684.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47684/agent_solaris_html_report_Test_integration_B47684.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47685/manager_html_report_Test_integration_B47685.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47686/manager_html_report_Test_integration_B47686.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47687/manager_html_report_Test_integration_B47687.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47688/manager_html_report_Test_integration_B47688.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47689/manager_html_report_Test_integration_B47689.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47673/agent_centos_html_report_Test_integration_B47673.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47673/agent_windows_html_report_Test_integration_B47673.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47673/agent_macos_html_report_Test_integration_B47673.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

**Comment by joaquinsgi** [comment]
# GA Executions

## API :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098717555 :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098760408 :green_circle: 

## Analysisd


## Execd :green_circle:
- https://github.com/wazuh/wazuh/actions/runs/10098788460 :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098793736 :green_circle: 

## Github :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098804685 :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098809167 :green_circle: 

## Office365
- https://github.com/wazuh/wazuh/actions/runs/10098817795 :green_circle: 

## MSGraph :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10098831771 :green_circle:

**Comment by rauldpm** [comment]
Jenkins results should be ignored as those tests were migrated to GHA

**Comment by joaquinsgi** [comment]
# Analysis Report for GA Executions

Testing [Integration tests for Analysisd - Tier 2 for 4.9.0-Alpha3](https://github.com/wazuh/wazuh/actions/runs/10098774058), many errors occurred and are related to the following issue: [Failed Integration test for Analysisd - Tier 2 for 4.9.0-Alpha3](https://github.com/wazuh/wazuh/issues/24949)

**Comment by hossam1522** [comment]
LGTM!
