### ISSUE TITLE
Release 4.9.0 - Alpha 3 - Deployability

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24935]
### Packages tests metrics information

|||
| :--                              | :--                                                             |
| **Main release stage issue**     | #24714                                         |
| **Main packages metrics issue**  | #24716                                                   |
| **Version**                      | 4.9.0                                                   |
| **Release stage**                | Alpha 3                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-alpha3          |

---

Note: YAML files do not have `on_error` set, so if some thread fails the other can continue

### Wazuh agent tests

- Log: [agents.log](https://github.com/user-attachments/files/16383140/agents.log)
- YAML: [Test-agents-complete.yaml.txt](https://github.com/user-attachments/files/16383151/Test-agents-complete.yaml.txt)

Note: macOS was skipped due to infrastructure, it will be launched in the next stage

|System Agent|Deploy instance|Connection instance|Install|Registration|Connection|Basic info|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 7 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 8 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Red Hat 9 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 7 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|CentOS 8 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 10 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 11 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Debian 12 AMD64| :red_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
|Debian 12 ARM64| :red_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 22.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 20.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 18.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Ubuntu 18.04 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Oracle Linux 9 AMD64| :red_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2023 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Amazon Linux 2023 ARM64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Desktop 10 AMD64| :green_circle: | :red_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
|Windows Server 2012-r2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2016 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :red_circle: | :green_circle: | :green_circle: |
|Windows Server 2019 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|Windows Server 2022 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |
|macOS Ventura 13 AMD64| :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |
|macOS Sonoma 14 AMD64| :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: | :black_circle: |

### Wazuh manager tests

- Log: [manager.log](https://github.com/user-attachments/files/16383718/manager.log)
- YAML: [Test-manager-complete.yaml.txt](https://github.com/user-attachments/files/16383602/Test-manager-complete.yaml.txt)

|System|Deploy instance|Connection instance|Install|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Debian 12 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |  
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: |  
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 

### Wazuh central components tests

- Log:  [cc.log](https://github.com/user-attachments/files/16384140/cc.log)
  - Destroy resource error related to 5615
- YAML: [Test-CC-complete.yaml.txt](https://github.com/user-attachments/files/16384145/Test-CC-complete.yaml.txt)

|System|Deploy instance|Connection instance|Install|Restart|Stop|Uninstall|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|
|Red Hat 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Red Hat 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Red Hat 9 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|CentOS 7 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|CentOS 8 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :red_circle: | 
|Debian 10 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Debian 11 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Debian 12 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Ubuntu 22.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Ubuntu 20.04 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | 
|Amazon Linux 2 AMD64| :green_circle: | :green_circle: | :green_circle: | :green_circle: | :green_circle: | :red_circle: | 

---

Status legend:

:black_circle: - Not started/In progress
:white_circle: - Skipped
:red_circle: - Found new errors/bugs/failures
:yellow_circle: - Found known errors/bugs/failures
:green_circle: - All tests passed

---

### New issue

- https://github.com/wazuh/wazuh-qa/issues/5613
- https://github.com/wazuh/wazuh-qa/issues/5614
- https://github.com/wazuh/wazuh-qa/issues/5615
- https://github.com/wazuh/wazuh-qa/issues/5616
- https://github.com/wazuh/wazuh-qa/issues/5617

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @wazuh/devel-qa-release

**Comment by rauldpm** [comment]
## Analysis report

### Agent

- Windows Server 2016

```
modules/testing/tests/test_agent/test_restart.py::test_port [2024-07-25 21:21:08] [ERROR] TESTER: Port is closed
 FAILED
....
=========================== short test summary info ============================
FAILED modules/testing/tests/test_agent/test_restart.py::test_port - Assertio...
=================== 1 failed, 6 passed, 4 warnings in 17.76s ===================
```

### Manager

- All tests passed

### Central components

- Amazon Linux 2

```
modules/testing/tests/test_central_components/test_uninstall.py::test_manager_agent_enrollment_port [2024-07-26 00:05:04] [ERROR] TESTER: The Wazuh manager API port in amazon-2 is still active
FAILED
modules/testing/tests/test_central_components/test_uninstall.py::test_dashboard_port [2024-07-26 00:05:05] [ERROR] TESTER: The Wazuh dashboard port in amazon-2 is still active
FAILED
...
=========================== short test summary info ============================
FAILED modules/testing/tests/test_central_components/test_uninstall.py::test_manager_agent_enrollment_port
FAILED modules/testing/tests/test_central_components/test_uninstall.py::test_dashboard_port
=================== 2 failed, 5 passed, 4 warnings in 41.79s ===================
```

- CentOS 8

```
modules/testing/tests/test_central_components/test_uninstall.py::test_manager_agent_enrollment_port [2024-07-26 00:05:04] [ERROR] TESTER: The Wazuh manager API port in amazon-2 is still active
FAILED
modules/testing/tests/test_central_components/test_uninstall.py::test_dashboard_port [2024-07-26 00:05:05] [ERROR] TESTER: The Wazuh dashboard port in amazon-2 is still active
FAILED
...
=========================== short test summary info ============================
FAILED modules/testing/tests/test_central_components/test_uninstall.py::test_manager_api_port
FAILED modules/testing/tests/test_central_components/test_uninstall.py::test_manager_agent_enrollment_port
=================== 2 failed, 5 passed, 4 warnings in 58.03s ===================
```

**Comment by fcaffieri** [comment]
LGTM

**Comment by juliamagan** [comment]
Why are there no issues with allocator failures for Debian 12 and Oracle Linux 9?

**Comment by juliamagan** [comment]
LGTM
