### ISSUE TITLE
Vulnerability Detector - Update compatiblity matrix - Ubuntu Noble

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24937]
## Description
The scope of this issue is to investigate the compatibility matrix of the new Vulnerability Detector

The current [compatiblity matrix](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix) doesn't reflect the support for Ubuntu Noble (despite being fully supported)

Nevertheless, to maintain our quality standard we are going to test the Vulnerability Detector in this OS before updating the matrix

## DoD
- [x] Validate VD behaviour in Ubuntu Noble
- [x] Update the compatibility matrix

**Comment by GabrielEValenzuela** [comment]
# Update

- After installing a manager v4.8.1 on Ubuntu Noble and enabling the VD module on the manager, we can see that vulnerabilities are being detected successfully

![image](https://github.com/user-attachments/assets/e8a5d0c0-892b-4459-abe4-0af48f2c2587)

![image](https://github.com/user-attachments/assets/f4c5cfa5-a87d-4e60-9fcb-c0c73f8574fa)


We're going to update the [compatiblity matrix](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#compatibility-matrix) to reflect this behavior.

**Comment by GabrielEValenzuela** [comment]
# Update

- Improve documentation. PR ready for review.

**Comment by GabrielEValenzuela** [comment]
# Update

- Apply review request changes.

**Comment by GabrielEValenzuela** [comment]
# Update

- Update brief based on review comments.

**Comment by Dwordcito** [comment]
LGTM

**Comment by yourdevDex** [comment]
thanks fir this. Will update for the latest version.

**Comment by sebasfalcone** [comment]
## Issue re-open
We need to update the compatibility matrix, there are some errors in it
