### ISSUE TITLE
Typo error in site wazuh.com for auditd and wazuh

### ISSUE THREAD

**Issue by s23hck** [wazuh/wazuh#24931]
Hi there,
I feel like there is a mistake in site wazuh.com at : 
https://wazuh.com/blog/monitoring-root-actions-on-linux-using-auditd-and-wazuh/

At chapter "**First steps with Linux Audit system**", the content indicate this command : 
`systemctl enable auditd.servicesystemctl start auditd.service`

I think It should be : 
`systemctl enable auditd.service && systemctl start auditd.service`

Regards,
Steph

**Comment by juliancnn** [comment]
Hi @s23hck,

Thank you very much for taking the time to report this, I will pass it on to the content team.

**Comment by juliancnn** [comment]
Hi @s23hck, This is now fixed, thanks for reporting it!

**Comment by s23hck** [comment]
Hi @juliancnn,
With pleasure ! 
Thanks for this quick fix :)
Regards.

**Comment by JcabreraC** [comment]
Fixed a typo in the documentation.

Close issue.
