### ISSUE TITLE
Unit testing coverage is not considering all tests 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#24944]
# Description 

It was found as part of the implementation of this [issue](https://github.com/wazuh/wazuh/issues/24351) that the coverage for indexerConnector is not considering the indexerConnector.hpp/cpp files for the final report 

![image](https://github.com/user-attachments/assets/62a65cac-848f-4881-bcac-a880aec5e254)

[Coverage Report - indexer_connector.zip](https://github.com/user-attachments/files/16392388/Coverage.Report.-.indexer_connector.zip)
 
In addition, an overview of all unit test cases for any anomaly is desirable. 

## DoD 

- [x] Include indexerConnector tests in the coverage final report.
- [x] Review all unit test cases are considered during the coverage report.

**Comment by pereyra-m** [comment]
## Update

I begin with the issue. I first analyze the CMakeLists file.

**Comment by pereyra-m** [comment]
## Update

I verify the proposed approach

**Comment by pereyra-m** [comment]
## Update

I continue analyzing the results to make sure all the files are included.

**Comment by sebasfalcone** [comment]
## Issue blocked
This changes make evident a lot of technical debt, we need to define how to proceed

**Comment by pereyra-m** [comment]
This is the issue created for the technical debt
- https://github.com/wazuh/wazuh/issues/25207

**Comment by Dwordcito** [comment]
In 5.0 we will remove the major part of this code.
