### ISSUE TITLE
Footprint - Windows RSS memory spikes found

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#24940]
## Description

Analyzing this footprint [issue](https://github.com/wazuh/wazuh/issues/24747), we notice that the agent continues to be stressed in the `resources release phase` and has memory usage spikes.
This is visible in all the stress tests that contain the sca module active and those tests that do not enable the sca module the graph to behave normally without spikes.

For example:

[ALL](https://github.com/wazuh/wazuh/issues/24747):

- 4.9.0 Alpha 3:

![image](https://github.com/user-attachments/assets/9588c23f-b89a-4ef6-954f-f67aff8cfc18)

- 4.8.1 RC 2:

![image](https://github.com/user-attachments/assets/2a74feb4-05f3-4897-9ed5-056c13eaf32e)

[ALL-EXCEPT-SYSCHECK](https://github.com/wazuh/wazuh/issues/24756)

- 4.9.0 Alpha 3:

![image](https://github.com/user-attachments/assets/cb6ec707-3901-4d52-b4da-5873d7102cd9)

- 4.8.1 RC 2:

![image](https://github.com/user-attachments/assets/fcdafdbb-0b05-471b-bfdb-32e1b2ceb14c)

Then in the test [ALL-EXCEPT-SCA](https://github.com/wazuh/wazuh/issues/24746) we see:

- 4.9.0 Alpha 3:

![image](https://github.com/user-attachments/assets/104b5dcb-18e9-433b-a8fe-685a123193c8)

- 4.8.1 RC 2:

![image](https://github.com/user-attachments/assets/53762c01-9fa5-40d8-938c-fafd030e3619)

> Further analysis is required

**Comment by cborla** [comment]
## Analysis

The RSS memory usage or memory spikes do not represent that the agent is stressed or not, a similar signal is drawn before starting the stress zone, and this is similar for both 4.8.X and 4.9.0. In addition, the operating system is the one who manages when and how to release the memory blocks even if the application does not require them, or has already released them.

### From the comparison of the graphs we can highlight

- Change in frequency in the post-stress area

| 4.9.0 Alpha 3 | 4.8.1 RC 2 |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/f412b34e-e993-4504-a6bb-b4244f5cec1c) | ![image](https://github.com/user-attachments/assets/5bff5879-864d-4721-a6d4-f12b7968ea84) |

It can be observed that version 4.8.1 releases memory more frequently than version 4.9.0, there are more downward spikes.  In any case, cumulative ramps are not observed to denote any accumulation problem, but rather less frequently.

Possible causes of this behavior may be:

- Differences in the configuration of ossec.conf between version:
  - 4.9.0 Syscollector interval `60s`
  - 4.8.0 Syscollector interval `10s`
  - Changing the sample rate will affect the memory behavior. 
    
- Version 4.9.0-alpha3 has more SCA rules than version 4.8.1. ([v4.8.1 vs v4.9.0-alpha1](https://github.com/wazuh/wazuh/compare/v4.8.1...v4.9.0-alpha3))
  - This point is very important, there is a small increase in memory usage between versions, and it is most likely that the rules or lists of rules are loaded in the RSS memory.

- An important observation is the increased memory usage when the SCA module is enabled, but this behavior is not from version 4.9.0 it includes later versions to.

## Conclusion

According to the evidence mentioned in the previous points, both in terms of configuration and increase of SCA rules/policies, and not observing signs of memory accumulation without release. I believe that this behavior does not represent a problem for the product, so the issue can be dismissed.
