### ISSUE TITLE
Engine - Refactor Base module for Enhanced Maintainability and Modularity

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#24958]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager/Agent | Packages | OS version |

## Description
The modification of this module affects the entire engine. It requires a comprehensive review, module by module, to determine what should be made private in the CMake configuration, and to update all includes accordingly. This module is currently a collection of various components that need to be organized and cleaned up.

Also, the engine github workflows must be changed to be triggered manually and on pull requests.

## Objectives
- Divide and Organize: Split the module into submodules if necessary, such as utils, shared types, logging, and others.
- Remove Dead Code: Eliminate unused code, particularly in the tracing section.
- Library Assembly: Reconstruct the module as a library.
- Profiler Removal: Remove the Profiler component.
- Testing: Ensure that all utilities have corresponding tests.

## Deliverables
- A well-organized base module with clear delineation of submodules.
- Documentation of changes made to the CMake configuration.
- A rebuilt module structured as a library.
- Confirmation of the removal of the Profiler.
- Test coverage reports for utilities.

## Goal
To refactor the base module for improved maintainability, clarity, and modularity, ensuring that the codebase is clean, organized, and well-documented, with all necessary tests in place.
Contraer

**Comment by JavierBejMen** [comment]
## Update
- Made base a static package
- Added interface library for testing functionality base::test
- Working on updating tests and others engine modules
- Removed profiling code

**Comment by JavierBejMen** [comment]
## Update
- Added error tests
- Added expression tests
- Added timer tests
- Added workflow tags and paths to engine workflow tests
