### ISSUE TITLE
WPK forced upgrade fails in RPM 4.9.0

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#24950]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-alpha3 | Wazuh component | Agent | Packages | Red Hat 9 |

## Description

During testing performed in [Release 4.9.0 - Alpha 3 - Upgrade metrics](https://github.com/wazuh/wazuh/issues/24718), a Red Hat 9 agent forced WPK upgrade failed. 

### Steps to reproduce the bug
- Install wazuh agent 4.8.1
- Upgrade using WPK to 4.9.0
- Force WPK upgrade with the same package as for the second step

Note: the protocol for agent-manager communication chosen was UDP.

Here is the output of the failed upgrade command:

```console
# /var/ossec/bin/agent_upgrade -a 003 -f /home/vagrant/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk -F

Upgrading...

Failed upgrades:
	Agent 003 status: Upgrade procedure exited with error code
```

```console
# /var/ossec/bin/agent_control -i 003

Wazuh agent_control. Agent information:
   Agent ID:   003
   Agent Name: rh9-2-11
   IP address: any
   Status:     Active

   Operating system:    Linux |rh9-2-11 |5.14.0-362.8.1.el9_3.x86_64 |#1 SMP PREEMPT_DYNAMIC Tue Oct 3 11:12:36 EDT 2023 |x86_64
   Client version:      Wazuh v4.9.0
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1721995794

   Syscheck last started at:  Fri Jul 26 12:03:15 2024
   Syscheck last ended at:    Fri Jul 26 12:03:17 2024
```

The agent's OS is Red Hat 9 with the following characteristics:

```console
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"
```

### Evidences

For more details, see https://github.com/wazuh/wazuh/issues/24718#issuecomment-2253013490

- [upgrade.log](https://github.com/user-attachments/files/16394080/upgrade.log) 
- [agent_ossec.log](https://github.com/user-attachments/files/16394082/agent_ossec.log)
- [manager_ossec.log](https://github.com/user-attachments/files/16394083/manager_ossec.log)

**Comment by TomasTurina** [comment]
@jseg380 as we can see in the upgrade log:

```
2024/07/26 15:24:24 - Upgrade started.
2024/07/26 15:24:24 - Checking execution path.
Verifying...                          ########################################
Preparing...                          ########################################
	package wazuh-agent-4.9.0-1.x86_64 is already installed
2024/07/26 15:24:25 - Installation result = 2
2024/07/26 15:24:25 - Checking for Wazuh Agent control script.
2024/07/26 15:24:25 - Checking if Wazuh Agent is running.
2024/07/26 15:24:25 - Wazuh Agent is already running.
2024/07/26 15:24:26 - Waiting connection... Remaining attempts: 30.
2024/07/26 15:24:27 - Status = connected. 
2024/07/26 15:24:27 - Upgrade failed...
```

The upgrade is expected to fail as the `rpm` upgrade command returns error:

```
Verifying...                          ########################################
Preparing...                          ########################################
	package wazuh-agent-4.9.0-1.x86_64 is already installed
```

This is new, since before 4.9.0 the upgrade was done with sources. Now that the upgrade is done using a package, it informs the exit code of the package upgrade.

Somewhat related, we have seen a problem when trying to upgrade to the same version that is being fixed [here](https://github.com/wazuh/wazuh/pull/24939), but in any case the upgrade won't end as successful and an error is the expected result.
