### ISSUE TITLE
Vulnerability Detector - RPM upgrade won't download new content

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#24963]
## Description
The target of this issue is to backport the fix of a bug introduced in 4.9.0:
- https://github.com/wazuh/wazuh/pull/24375

And was addressed in 4.9.1:
- https://github.com/wazuh/wazuh/pull/24909

## DoD
- [x] Add fix to 4.9.0
- [x] Validate fix

**Comment by sebasfalcone** [comment]
## Update
- PR created

**Comment by Dwordcito** [comment]
Moved to on-hold based on daily meeting discussion (The development side will test with a ci package)

**Comment by sebasfalcone** [comment]
## Update
- Performed testing
