### ISSUE TITLE
Cannot register more than one agent as "any" using agent-auth if the tag <use_source_ip> is set to yes

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#2497]
Hello team,

I tried to register agents through NAT using the `ossec-authd` daemon and configuring the IP "any" on the agent side using the command `agent-auth -I any`. 

This way, when I registered more of 1 agent using that command, the manager was always overwriting the previous one. The manager only registered one agent with "any" IP.

I had set the tag`use_source_ip` in the manager to no, to register the agent as "any" and not use the option `-I any`.

Is this the expected behavior?

Regards,

Miguel Casares

**Comment by y-cann** [comment]
Hi,

any updates on this issue ? We are facing the same bug, and perform manual registration.

**Comment by MiguelCasaresRobles** [comment]
Hello @y-cann , 

Sorry for the late reply.

This has been fixed in #2533 and will be featured in next versions.

Let us know if you have further questions.

**Comment by chemamartinez** [comment]
Solved at #2533
