### ISSUE TITLE
Set the Geolocation field for the rule description

### ISSUE THREAD

**Issue by fnxaw** [wazuh/wazuh#24985]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.7.x-1 | Rules/Decoders | Improve |

## Description
Hi team! The purpose of this FR is to add the `Geolocation.country_name` to the rule description so it's easier to understand from which country (or even city/region) a source IP is from:

![image](https://github.com/user-attachments/assets/729dbecf-1862-4ac5-9d4d-72a59cd74dd3)

The idea is to set a rule as follows and read the country name (as shown above):
```
  <rule id="100000" level="3">
    <CONDITION>VALUE</CONDITION>
    <description>The country for this alert is $(Geolocation.country_name).</description>
  </rule>
```
This is especially helpful when reading the alerts through emails because the geolocation country name is not directly accessible as in the dashboard.

### Log examples
```
2024-07-09 16:42:48,542 INFO [org.xxx.xxx.xxx.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN ============================================================= WHO: user WHAT: Supplied credentials: [user] ACTION: AUTHENTICATION_FAILED APPLICATION: APP WHEN: Tue Jul 09 16:42:48 EDT 2024 CLIENT IP ADDRESS: 1.1.1.1 SERVER IP ADDRESS: 1.1.1.1============================================================= >
```

**Comment by jnasselle** [comment]
Hi @fnxaw ,

Wazuh server has a built-in localization server provided by GeoIP library.

Refs:
- Makefile options, Available flags [link](https://documentation.wazuh.com/current/development/makefile.html?highlight=use_geoip#available-flags)
- Alerts, use_geoip [link](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html?highlight=use_geoip#use-geoip)
- Rule Syntax, srcgeoip and dstgeoip [link](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html?highlight=dstgeoip#dstgeoip)

This feature is not enabled by default and not recommended due to its complex approach, meaning that should be enabled, compiled and packaged by users.

Quoting @juliancnn last guide to add this feature

> In order to create rules that can use geolocation, you must build wazuh with the flag `USE_GEOIP=yes`.  It also requires a GeoIP database: We support the legacy Maxmind GeoLite format, and the updated and maintained databases use the new GeoLite2 format. It should be converted to the legacy format using an external tool.
> Steps to include GeoLite2 database to Wazuh version:
> - Install libgeoip-dev library. i.e. ubuntu: 
> ```bash
> apt install libgeoip-dev
> ```
> - Install manager from the source ([doc here](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html)) but compile it with the USE_GEOIP flag, that is:  
> ```bash
> make TARGET=server USE_GEOIP=yes
> ```
> - Download the GeoLite2 free databases, it's necessary create an account. choose the City version in CSV format, zipped. [link](https://dev.maxmind.com/geoip/geolite2-free-geolocation-data) .
> - Download [geolite2legacy.py](https://github.com/sherpya/geolite2legacy) to convert from .CSV to .DAT file (supported by Wazuh).
> - Convert the GeoLite2-City-CSV to DB file. command: 
> ```bash
> ./geolite2legacy.py -i GeoLite2-City-CSV_20220603.zip -f geoname2fips.csv -o GeoIP.dat
> ```
> - Copy the converted GeoIP.dat DB inside the Wazuh directory. command: 
> ```bash
> cp GeoIP.dat /var/ossec/etc
> ```
> - Following steps are configuration settings.
>   - Enable USE_GEOIP in ossec.conf file:
>     ```xml
> 	    <global>
> 	        <geoipdb>/var/ossec/etc/GeoIP.dat</geoipdb>
> 	    </global>
>     
> 	    <alerts>
> 	        <use_geoip>yes</use_geoip>
> 	    </alerts>
>     ```
>   - Enable USE_GEOIP in internal_options.conf file:
>   ```ini
> 	  analysisd.geoip_jsonout=1
> 	  maild.geoip=1
>   ```
>   - Restart Wazuh server and it should run without any ERROR message. At this point the functionality is enable, every generated alert that include srcip or dstip field will look for the srcgeoip or dstgeoip information in GeoIP.dat database.
>   - Then, you could create a rule like the following, which will ignore the 81614 rule when the srcip is from the USA:
>   ```xml
>   <rule id="100014" level="0">
>       <if_sid>81614</if_sid>
>       <srcgeoip>United States</srcgeoip>
>       <description>ignore eeuu srcip.</description>
>     </rule>
>   ```
