### ISSUE TITLE
Release 4.9.0 - Beta 1 - E2E UX tests - Azure integration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#25022]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.9.0-beta1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Aug 05, 2024 and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-pyserver team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Aug 06, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Aug 7, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta1/installation-guide/wazuh-indexer/step-by-step.html) | Single node | CentOS 9 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta1/installation-guide/wazuh-server/step-by-step.html) | Multi node | CentOS 9 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta1/installation-guide/wazuh-dashboard/step-by-step.html) | - | CentOS 9 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.9.0-beta1/_images/deploy-new-agent-from-ui1.png) | - | Amazon Linux 2 x86_64 |

## Test description

Configure the Azure integration in a Wazuh Manager and a Wazuh Agent. 
Try the Graph, Log Analytics, and Storage integrations.
Ensure the events are correctly displayed on the dashboard.
Documentation: https://documentation-dev.wazuh.com/v4.9.0-beta1/cloud-security/azure/index.html

## Known issues

- https://github.com/wazuh/wazuh-documentation/issues/5803
- https://github.com/wazuh/wazuh-documentation/issues/6494
- https://github.com/wazuh/wazuh-documentation/issues/6563
- https://github.com/wazuh/wazuh/issues/19282
- https://github.com/wazuh/wazuh-documentation/issues/6559

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :green_circle:  | Deployment | NA | NA|
| :green_circle:  | Azure Integration for Log Analytics, Graphs and Storage on Wazuh Server | NA | NA|
| 🔴 |  Azure Integration for Log Analytics, Graphs and Storage on Wazuh agent| Error: 1 | Ran into the same issue described in [#24545](https://github.com/wazuh/wazuh/issues/24545) |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **Testing guideline was clear enough**
- Did you face any challenges not covered by the guideline?
  - **No**
- Suggestions for improvement:
  - **Having maybe a Azure test account with all necessary permissions would speed things up.**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/devel-pyserver

**Comment by aritosteles** [comment]
# Environment
### Indexer
- Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic-x64/centos9s"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
end
```
- OS
```
[vagrant@centos9s ~]$ cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

**Comment by aritosteles** [comment]
# Deployment
<details><summary>Indexer</summary>

[vagrant@indexer ~]$ curl -sO https://packages-dev.wazuh.com/4.9/wazuh-certs-tool.sh
[vagrant@indexer ~]$ curl -sO https://packages-dev.wazuh.com/4.9/config.yml

</details>

**Comment by aritosteles** [comment]
# Test for Log Analytics, Graph and Storage integration

### App registration:

![image](https://github.com/user-attachments/assets/680ff441-0477-457e-937c-2cda32c705b0)

**Comment by aritosteles** [comment]
# Test for Log Analytics, Graph and Storage integration

### App registration:

![image](https://github.com/user-attachments/assets/680ff441-0477-457e-937c-2cda32c705b0)

- Created application key:

![image](https://github.com/user-attachments/assets/404c90d9-b569-4be6-a75a-7a2333276f1f)

- Requested API permissions:

![image](https://github.com/user-attachments/assets/01945d42-9763-4059-a070-2221410fe8ba)

![image](https://github.com/user-attachments/assets/8d5a5af2-d2ce-4489-b215-6ab79bf5d11d)

- Added application to LogAnalyticsWorkspace

![image](https://github.com/user-attachments/assets/5727d4e2-dc45-4bfe-9fa6-7d0beddb6539)

- Configured Diagnostics setting

![image](https://github.com/user-attachments/assets/ef53797b-7122-44b2-a0ef-df0c176f2ce0)

- Queried for Audit Logs on Log Analytics Workspace:

![image](https://github.com/user-attachments/assets/535f5870-3001-49a6-ab23-96e7563447d4)

## Wazuh Server Config
```
[root@server1 vagrant]# cat /var/ossec/LogAnalyticsCredentials.txt 
application_id = ab24dxxxxxxxxxxxxxx
application_key = 2340598xxxxxxxxxxxxxxxx
[root@server1 vagrant]# 
```

- Modified /var/ossec/etc/ossec.conf

```
    <log_analytics>
        <auth_path>/var/ossec/wodles/credentials/log_analytics_credentials</auth_path>

        <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
        <request>
       	    <tag>azure-auditlogs</tag>
            <query>AuditLogs</query>
            <workspace>204dxxxxxxxxxxxxxxxx</workspace>
            <time_offset>1d</time_offset>
        </request>
    </log_analytics>
  </wodle>
```
- Restarted the manager

```
# wazuh-control restart
```

**Comment by aritosteles** [comment]
# Test for Graph and Storage integration

**Comment by aritosteles** [comment]
# Test for Storage integration

**Comment by davidcr01** [comment]
The diagnostic setting were created as specified in the documentation, please proceed with the test.
![image](https://github.com/user-attachments/assets/c8012846-3c03-429d-866d-7d9a530d2b3b)

**Comment by rauldpm** [comment]
@davidcr01 

![image](https://github.com/user-attachments/assets/7aa0b172-423a-44dc-a8a9-5a6625eab1f2)

**Comment by aritosteles** [comment]
# Agent

- Installed dependencies
```
yum update && yum install python3
```

**Comment by aritosteles** [comment]
# Agent :red_circle: 

- Installed dependencies
```
yum update && yum install python3
yum update && yum install python3-pip
```
- Ran into a problem with dependencies that needed python3.8 :yellow_circle: 
 Solution: Install version 3.8 and set as alternative higher than version 3.7

```
# sudo amazon-linux-extras install python3.8 -y
# sudo python3.8 -m ensurepip
# sudo python3.8 -m pip install --upgrade pip
# sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
# sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2

```
- Created credentials files

```
[root@agent ossec]# cat StorageCredentials.txt 
account_name = frameworkteststorage
account_key = chwxxxxxxxxxxxxxxxxxxxxxxx

[root@agent ossec]# cat GraphCredentials.txt 
application_id = 77bxxxxxxxxxxxxxxxxxxxxxxxxxxx
application_key = Q4Wxxxxxxxxxxxxxxxxxxxxxxxxxx

[root@agent ossec]# cat LogAnalyticsCredentials.txt 
application_id = ab2xxxxxxxxxxxxxxxxxxxxxxxxxxx
application_key = vUexxxxxxxxxxxxxxxxxxxxxxxxxxx
```
- Added configuration to ossec.conf

```
<wodle name="azure-logs">
    <disabled>no</disabled>
    <run_on_start>yes</run_on_start>

    <log_analytics>
        <auth_path>/var/ossec/LogAnalyticsCredentials.txt</auth_path>

        <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
        <request>
            <tag>azure-auditlogs</tag>
            <query>AuditLogs</query>
            <workspace>20xxxxxxxxxxxxxxxxxxxxxxxx</workspace>
            <time_offset>1d</time_offset>
        </request>
    </log_analytics>

    <graph>
	<auth_path>/var/ossec/GraphCredentials.txt</auth_path>
        <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
        <request>
            <tag>microsoft-entra_id</tag>
            <query>auditLogs/directoryAudits</query>
            <time_offset>1d</time_offset>
        </request>
    </graph>

    <storage>
	<auth_path>/var/ossec/StorageCredentials.txt</auth_path>
        <tag>azure-activity</tag>

        <container name="insights-logs-auditlogs">
            <blobs>.json</blobs>
            <content_type>json_inline</content_type>
            <time_offset>24h</time_offset>
            <path>info-logs</path>
        </container>
    </storage>

 </wodle>

```

- Restarted agent

- Checked log file and found errors :red_circle: 
```
[root@agent bin]# grep azure /var/ossec/logs/ossec.log
2024/08/08 17:22:47 wazuh-modulesd:azure-logs[21029] wm_azure.c:440 at wm_azure_cleanup(): INFO: Module finished.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Module started.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Starting fetching of logs.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: ERROR: azure-auditlogs: Returned error code: '1'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for request 'azure-auditlogs'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Starting Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: ERROR: microsoft-entra_id: Returned error code: '1'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Graphs log collection for request 'microsoft-entra_id'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Graphs log collection for the domain 'wazuh.onmicrosoft.com'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Starting Storage log collection for 'azure-activity'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: ERROR: insights-logs-auditlogs: Returned error code: '1'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for container 'insights-logs-auditlogs'.
2024/08/08 17:22:53 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for 'azure-activity'.

```

**Comment by nico-stefani** [comment]
# Review

You are missing the dependencies installed during the agent setup, this could be one of the causes of the errors.
Also, having two versions of python3 could be ambiguous for the script execution.

Please repeat the agent step:

* Installing the dependencies listed in the [prerequisites](https://documentation-dev.wazuh.com/v4.9.0-beta1/cloud-security/azure/activity-services/prerequisites/dependencies.html#python) section.
* Keep only one version of python installed or modify the [shebag](https://github.com/wazuh/wazuh/blob/v4.9.0-beta1/wodles/azure/azure-logs.py#L1) of the script to point directly to python3.8.

**Comment by aritosteles** [comment]
# Agent retry

- Remove default python version

```
# sudo yum remove python3
```
- Check for python package presence

![image](https://github.com/user-attachments/assets/f7dd5928-e6ac-4445-a44e-8d74d56863e0)

**Comment by aritosteles** [comment]
# Agent retry

- Remove default version of python

```
sudo yum remove python3
```
- Install version 3.8

```
# sudo amazon-linux-extras install python3.8 -y
# sudo python3.8 -m ensurepip
# sudo python3.8 -m pip install --upgrade pip
```
- Set version 3.8 as default
- 
```
# sudo alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
```
- Check there is no other version present and that 3.8 is set as default

![image](https://github.com/user-attachments/assets/ed4ab0d4-e525-40dd-bfe9-f30937cf838a)

**Comment by nico-stefani** [comment]
LGTM
