### ISSUE TITLE
Vulnerability Detection Register Stress Tests log ERROR in vulnerability_feed_manager

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25065]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.9.0 Beta 1 | vulnerability_feed_manager | Manager| Packages |CentOS |

# Description
While testing the issue: [VULNERABILITY-DETECTOR-REGISTER (2.5d) FOOTPRINT TEST]( https://github.com/wazuh/wazuh/issues/25037), an error was detected in one of the logs from the manager, which seems to fail in the `vulnerability_feed_manager` action; it appears to return a partial file.

Error:

```
./var/ossec/logs/wazuh/2024/Aug/ossec-02.log:2024/08/02 21:35:35 wazuh-modulesd:content-updater: ERROR: Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: Transferred a partial file.
```

**Comment by sebasfalcone** [comment]
## Analysis
This is a temporary error from CTI that we are handling. If we take a look at the logs, we see that the feed was re-downloaded and processed
```bash
2024/08/02 21:35:35 wazuh-modulesd:content-updater: ERROR: Action for 'vulnerability_feed_manager' failed: Orchestration run failed: Error -1 from server: Transferred a partial file.
.
.

2024/08/02 22:41:30 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/08/02 22:47:46 wazuh-modulesd:vulnerability-scanner: INFO: Initiating update feed process.
2024/08/02 23:42:08 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update.
2024/08/02 23:42:08 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed.
```

Given that the logs are not in debug, we won't be able to go into more details

**Comment by sebasfalcone** [comment]
## Conclusion
It was confirmed that CTI had some issues on Friday and offset download was not possible, therefore the content got to be downloaded via snapshot (**Triggered a re-scan after content update**). This fallback mechanism was successful so I will close the issue
