### ISSUE TITLE
Check defects detected by Coverity in 4.9.0 Beta 1

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25063]
|Wazuh version|Components|Source|
|---|---|---|
| 4.9.0 Beta 1 | Vulnerability Scanner, Content Manager & Indexer Connector | https://github.com/wazuh/wazuh/issues/25015 |

A Coverity scan has reported the following defects related to the components mentioned above:

| Status | CID     | Type                         | Impact | Date     | Component              | Notes |
|:------:|---------|------------------------------|--------|----------|-----------------------|-------|
|   🟢   | 1598810 | Waiting while holding a lock | Medium | 08/01/24 | Content manager              |   [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271372221)    |
|  ⚪    | 1598792 | Overflowed return value      | Medium | 08/01/24 | Vulnerability Scanner        |   [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271375951)    |
|   🟢   | 1598791 | Waiting while holding a lock | Medium | 08/01/24 | Content manager              |   [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271380221)    |
| 🔴     | 1598783 | Overflowed integer argument  | High   | 08/01/24 | Other                        |    [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271383698)   |
| 🔴     | 1598781 | Overflowed integer argument  | High   | 08/01/24 | Other                        |    [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271387706)   |
| 🔵     | 1598773 | Overflowed constant          | Medium | 08/01/24 | Shared modules               |   [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271391254)    |
| 🔴     | 1598744 | Data race condition          | Medium | 08/01/24 | Router                       |    [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271394129)   |
| 🔴     | 1598740 | Data race condition          | Medium | 08/01/24 | Router                       |    [Comment](https://github.com/wazuh/wazuh/pull/25066#issuecomment-2271397414)   |

### Legend
🔴 Fix pending
🟡 Untriaged
🟢 Intentional
🔵 Ignore
🟣 Fixed
⚪ False positive

Please find out:

1. Either it's a confirmed bug or a false positive.
2. Its impact.
3. Whether it's new in 4.9.0.

Those defects that appeared by the first time in 4.9.0 should be considered as stoppers.

Then, please fill the tables:
- Table above.
- Coverity report (including the owner).

**Comment by Damian-Mangold** [comment]
## Update

The table is updated with the analysis carried out.

**Comment by Dwordcito** [comment]
Based on the analysis, none of these problems are incorporated in 4.9, therefore they are not blocking, they are all modules that will be removed by the relevant refactors in 5.0, and the router module will no longer be there. Therefore we will not fix it.
