### ISSUE TITLE
Release 4.9.0 - Beta 1 - Integration tests

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#25078]
# Description
|| | 
| :--                              | :--                                                             |
| **Main release stage issue** | https://github.com/wazuh/wazuh/issues/25025 |
| **Version**                      | 4.9.0                                                   |
| **Release stage**            | Beta 1                                                   
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.9.0-beta1         |
| **Wazuh QA: Branch**    | `4.9.0`
| **Wazuh Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-beta1         |
| **Wazuh Branch**    | `4.9.0`
| **Previous test** | https://github.com/wazuh/wazuh/issues/24915 |

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build***:  https://ci.wazuh.info/job/Test_integration_launcher/260/

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47697/manager_html_report_Test_integration_B47697.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47698/agent_centos_html_report_Test_integration_B47698.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47698/agent_windows_html_report_Test_integration_B47698.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47700/manager_html_report_Test_integration_B47700.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47701/agent_centos_html_report_Test_integration_B47701.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47701/agent_windows_html_report_Test_integration_B47701.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47702/manager_html_report_Test_integration_B47702.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47703/agent_centos_html_report_Test_integration_B47703.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47703/agent_windows_html_report_Test_integration_B47703.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47704/agent_macos_html_report_Test_integration_B47704.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47704/agent_solaris_html_report_Test_integration_B47704.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47705/manager_html_report_Test_integration_B47705.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47706/manager_html_report_Test_integration_B47706.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/#">Couldn't get evidence. Check the pipeline.</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47708/manager_html_report_Test_integration_B47708.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47709/manager_html_report_Test_integration_B47709.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47710/manager_html_report_Test_integration_B47710.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47711/manager_html_report_Test_integration_B47711.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47712/manager_html_report_Test_integration_B47712.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47696/agent_centos_html_report_Test_integration_B47696.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47696/agent_windows_html_report_Test_integration_B47696.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47696/agent_macos_html_report_Test_integration_B47696.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

## Conclusion:
- **active_response** :green_circle: 
- **agentd** :yellow_circle:
- **enrollment** :green_circle: 
- **FIM** :red_circle: 
- **gcloud** :green_circle: 
- **logcollector** :yellow_circle: 
- **logtest**	:green_circle:
- **remoted** :green_circle:
- **rids** :green_circle:
- **wazuh_db** :green_circle:
- **syscollector** :yellow_circle: 

- **GA EXECUTIONS** :green_circle: 

- Known Issues:
    - https://github.com/wazuh/wazuh/issues/22854
    - https://github.com/wazuh/wazuh-qa/issues/4230
    
- Opened Issues:
    - https://github.com/wazuh/wazuh-qa/issues/5645 
    - https://github.com/wazuh/wazuh-qa/issues/5644
    - https://github.com/wazuh/wazuh-qa/issues/5646
    - https://github.com/wazuh/wazuh-qa/issues/5647

**Comment by joaquinsgi** [comment]
# Analysis GA Executions

## API :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10286808213 :green_circle: 
``` 
=========== 72 passed, 3 deselected, 1 xfailed in 1128.42s (0:18:48) ===========
```
- https://github.com/wazuh/wazuh/actions/runs/10286816393 :green_circle: 
``` 
====================== 3 passed, 73 deselected in 49.07s =======================
```

## Analysisd :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10286826003 :green_circle: 
```
============== 84 passed, 57142 deselected in 2372.87s (0:39:32) ===============
```
- https://github.com/wazuh/wazuh/actions/runs/10286830046 :green_circle: 
```
============== 57142 passed, 84 deselected in 2581.60s (0:43:01) ===============
```


## Execd :green_circle:
- https://github.com/wazuh/wazuh/actions/runs/10286857633 :green_circle: 
```
========================= 6 passed in 88.82s (0:01:28) =========================
```
- https://github.com/wazuh/wazuh/actions/runs/10286863050 :green_circle: 
```
=========== 2 passed, 4 deselected, 4 warnings in 91.77s (0:01:31) ============
```

## Github :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10286880942 :green_circle: 
```
======================== 8 passed in 268.58s (0:04:28) =========================
```
- https://github.com/wazuh/wazuh/actions/runs/10286883887 :green_circle: 
```
================= 8 passed, 16 warnings in 255.05s (0:04:15) ==================
```

## Office365 :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10287037459 :green_circle: 
```
======================== 8 passed in 268.98s (0:04:28) =========================
```

- https://github.com/wazuh/wazuh/actions/runs/10287040931 :green_circle: 
```
================= 8 passed, 16 warnings in 256.09s (0:04:16) ==================
```

## MSGraph :green_circle: 
- https://github.com/wazuh/wazuh/actions/runs/10287052140 :green_circle: 
```
================== 20 passed, 1 skipped in 722.30s (0:12:02) ===================
```

**Comment by hossam1522** [comment]
LGTM!
