### ISSUE TITLE
Vulnerability detector severity field must be unified

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#2508]
Hi team, the generated field `data.vulnerability.severity` sometimes is being stored with the first character in lowercase and sometimes is stored using uppercase.

Example:

```
Low, Medium, moderate, important
```

Since this behavior comes from the feeds we should unify it.

**Proposal 1**

At SQLite time, here https://github.com/wazuh/wazuh/blob/3b70695feb155c3a8406958fdd0eda9f922691bf/src/wazuh_modules/wm_vuln_detector.c#L1026 we might include it:

```c
if(info_it->severity) {
    info_it->severity[0] = toupper(info_it->severity[0]);
}
sqlite3_bind_text(stmt, 3, (info_it->severity) ? info_it->severity : unknown_value, -1, NULL); 
```

**Proposal 2**

Or before passing the alert to `analysisd`, something like this:

```c
if(severity) {
    severity[0] = toupper(severity[0]);
}
cJSON_AddStringToObject(alert_cve, "severity", (severity) ? severity : unknown_value);
```

Regards

**Comment by albertomn86** [comment]
Solved: https://github.com/wazuh/wazuh/pull/2603
