### ISSUE TITLE
Deprecate Vagrantfile and Update Documentation for Wazuh-Engine development environment

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#25083]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Wazuh-Engine | Manager | - | - |

### Description

As the Wazuh project progresses with the integration of the Wazuh-Engine into the master branch and the ongoing separation of Wazuh-Agent and Wazuh-Manager, it has become necessary to begin phasing out outdated components. One such component is the `Vagrantfile` used in the Wazuh-Engine project, which currently sets up an environment with Wazuh-Manager, compiles Wazuh-Engine, creates a security policy for Wazuh-Engine with the entire ruleset, and installs various internal tools that facilitate administration such as engine-test, engine-integration, engine-clear, etc.

Given the impending changes in the master branch that will render the existing `Vagrantfile` obsolete, this issue focuses on deprecating the `Vagrantfile` and documenting the transition. The objective is to remove the `Vagrantfile` from the repository and create a comprehensive `README.md` that explains the available internal tools (all Python packages), compilation requirements for Wazuh-Engine, and any other useful information previously accessible through the Vagrant environment.

### Tasks

1. **Deprecate Vagrantfile**:
   - Remove the `Vagrantfile` from the repository.
   - Ensure that any dependencies or configurations specific to the `Vagrantfile` are either updated or removed.

2. **Documentation**:
   - Create a `README.md` in the root of the repository detailing:
     - The internal tools available for Wazuh-Engine, focusing on Python packages like engine-test, engine-integration, engine-clear, etc.
     - The requirements and steps for compiling Wazuh-Engine post-deprecation.
     - Any other critical information previously facilitated by the Vagrant setup.
   - Include examples and instructions for setting up a development or testing environment without the use of the `Vagrantfile`.

3. **Review and Testing**:
   - Review the changes with the development team to ensure no critical functionality is lost with the deprecation of the Vagrant environment.
   - Test the documentation steps to verify that they provide a clear and functional setup process for developers and testers.

### Expected Outcome

The removal of the `Vagrantfile` should streamline the development process by reducing reliance on outdated components, while the new `README.md` will provide developers with all the necessary information to set up and manage their development environments efficiently. This change will align the Wazuh-Engine project with the latest architectural updates and prepare it for future enhancements.

**Comment by NahuFigueroa97** [comment]
## Update

- Vagrant review
- Readme of tools in progress - API communication

**Comment by NahuFigueroa97** [comment]
## Update

### Deprecated Vagrant for the engine
- Eliminate the use of Vagrant to lift the engine, along with the other tools that were used by this

### Fixed and improved the tool for running asan on tests
- Make adjustments and improvements to the tool that runs asan (AddressSanitizer) for the tests, which involves optimizing the execution of the tests and improving error detection.

### Progressed with tool documentation
- Readme of tools in progress - API communication
- Readme of tools in progress - evtx2xml

**Comment by NahuFigueroa97** [comment]
## Update

- Readme of tools - engine-suite
   - engine-clear
   - engine-decoder
   - engine-test
   - engine-diff
- Readme of tools - check_Vagrant
- Readme of tools - check_ASAN
- Readme of engine
   - Guide to compile engine
   - Reply steps in clear environment
   - Readme of source directory
