### ISSUE TITLE
`wazuh-modulesd` RSS increment in the post-stress stage

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#25098]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta1 | wazuh-modulesd | Agent | Packages | Ubuntu 20 |

In the analysis of the [ALL](https://github.com/wazuh/wazuh/issues/25032) stress test, I have noticed the following increment in wazuh-modulesd in the RSS plot

Note that in the final stage, where the stress script is not working, instead of liberating resources there is an increment, this increment appeared in 4.8.0 and since then, is more evident

- 4.9.0-beta1 https://github.com/wazuh/wazuh/issues/25032

![image](https://github.com/user-attachments/assets/3b94d752-912e-41ea-8380-dc48d3732abc)

- 4.8.1-rc2 https://github.com/wazuh/wazuh/issues/24474

![image](https://github.com/user-attachments/assets/02d0ee99-33ed-4efb-a6f1-0251e789202d)

- 4.8.0-rc4 https://github.com/wazuh/wazuh/issues/24005

![image](https://github.com/user-attachments/assets/69a64e44-e9d5-4dc0-85c7-820b67ebfe50)

Although this increment in 4.9.0 is just 8MB, we need to validate if this behavior is acceptable or if there is something that is not working as expected, as it is not releasing resources

**Comment by cborla** [comment]
When the stress zone ends, the agent has the same configuration as at the beginning of the test, this means that there are active modules which can continue collecting data but in a normal way, not stressed, for example syscheck is still active.
It can be seen in the graphic:

![image](https://github.com/user-attachments/assets/c9153fb6-7785-45a7-9b82-870fa2c82780)

Also looking for similarities in previous versions, similar increases are observed, for example in [Release 4.7.3 - RC 2 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/22299#top)

![image](https://camo.githubusercontent.com/b7a8fd276de9777ee6f250127c0e54e4e7e76ec8458c429ee104256db141a6ad/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e372e332f42343931352d333630306d2f42343931355f6167656e745f7562756e74752f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42343931355f7562756e74752d7072652d72656c656173655f5253535f4d41584d494e2e706e67)

In my opinion this behaviour does not represent an error or lack of release of resources.
