### ISSUE TITLE
API Documentation review 

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2510]
## Description
Since API has been widely modified, it is necessary to check that documentation matches the real behaviour of each endpoint. 

## Tasks
- [x] Review documentation for new/modified endpoints
- [x] Generate documentation with sphinx

**Comment by mgmacias95** [comment]
Documentation generated at https://github.com/wazuh/wazuh-documentation/pull/938.
Necessary changes to generate it at https://github.com/wazuh/wazuh-api/pull/276.

**Comment by crd1985** [comment]
This issue is blocked until 3.9 is finished.

**Comment by crd1985** [comment]
@druizz90 this issue can be achieved now that API 3.9 designed is stable.
