### ISSUE TITLE
Integratord isn't reading events

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2512]
## Bug report

**OS**
_Fedora 29_

**Wazuh version**
_3.9.0_

**Install type**
_manager_

**Install method**
_sources_

Bug description
----------------
I'm generating syscheck events in my Wazuh installation but `integratord` seems to be stuck in this line of the code
https://github.com/wazuh/wazuh/blob/852146faece1c041c8b90045d8a53bd6a4f037a1/src/shared/json-queue.c#L65
This causes `integratord` to be repeatly logging this line:
```
2019/02/01 06:28:29 ossec-integratord[7224] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
```
And, therefore, no alerts from `integratord` (virustotal) are raised:
```shellsession
[root@fedora29 vagrant]# grep syscheck /opt/ossec/logs/alerts/alerts.json | wc -l
7
[root@fedora29 vagrant]# grep virus /opt/ossec/logs/alerts/alerts.json | wc -l
0
```

**Comment by vikman90** [comment]
This issue is related to #2498.
