### ISSUE TITLE
Release 4.9.0 - Beta 2 - Vulnerability Detection tests

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#25138]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     |  https://github.com/wazuh/wazuh/issues/25126                                  |
| **Version**                          |                   4.9.0                         |
| **Release candidate #**              |                    Beta 2                    |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.9.0-beta2                              |
| **Previous Vulnerability tests issue**      | https://github.com/wazuh/wazuh/issues/25079                                         |

## Description

The primary goal of this issue is to conduct thorough vulnerability tests on the current release candidate. The process involves executing all vulnerability tests, analyzing the outcomes, and promptly reporting any identified issues. Additionally, new issues will be opened for encountered errors, contributing to the continuous improvement of the Vulnerability Detection module and the utilized vulnerability feed.
 
*** 

| Status | Test              | Issue              |
| :--:   | :--               | :--:               |
| :white_circle: Skipped   |  E2E Vulnerability Detection tests|  #25139  |
| :red_circle: Completed with failures     |  Vulnerability Detection performance tests | #25140 |

---

:white_circle: Skipped: The task has been deemed unnecessary for this stage.
:black_circle: Not finished: The tasks haven't been finished yet.
:green_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.
:yellow_circle: Completed with accepted known issues (new): Some issues were raised here, they were deemed non-stopper.

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [x] @wazuh/devel-qa-release 

---

**Comment by juliamagan** [comment]
For Beta 2 we have only been able to add the fix https://github.com/wazuh/wazuh-jenkins/issues/6848. However, there are still others to be analyzed and added, so we will skip this test in this stage and launch it in the next one.
