### ISSUE TITLE
vulnerability scan error : Agent sync omitted due to abuse control

### ISSUE THREAD

**Issue by ljm5608** [wazuh/wazuh#25143]
Wazuh v4.8.1 | wazuh-index,manager,dashboard | rpm package install | rocky linux 9.3

Hello.
After upgrading wazuh version to 4.7.4 -> 4.8.1, the Vulability scan only works in part and does not update.

When the service is restarted, the Vulcanability Detection dashboard is initialized, but data is not updated by the new or existing agent.

**log**

```
2024/08/12 12:32:46 wazuh-modulesd:vulnerability-scanner[3999663] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/08/12 12:32:46 indexer-connector[3999663] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '029' sync omitted due to abuse control.
2024/08/12 12:38:47 wazuh-modulesd:vulnerability-scanner[3999663] osScanner.hpp:271 at handleRequest(): DEBUG: No CPE product found for OS 'Microsoft Windows Server 2016 Standard' on Agent '024'.
2024/08/12 12:38:47 wazuh-modulesd:vulnerability-scanner[3999663] osScanner.hpp:346 at handleRequest(): DEBUG: Vulnerability scan for OS 'Microsoft Windows Server 2016 Standard' on Agent '024' has completed.
2024/08/12 12:38:47 wazuh-modulesd:vulnerability-scanner[3999663] eventDetailsBuilder.hpp:101 at handleRequest(): DEBUG: Building event details for component type: 2
2024/08/12 12:38:47 wazuh-modulesd:vulnerability-scanner[3999663] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 3 processed
2024/08/12 12:38:54 wazuh-modulesd:vulnerability-scanner[3999663] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/08/12 12:38:54 indexer-connector[3999663] indexerConnector.cpp:437 at operator()(): DEBUG: Syncing agent '024' with the indexer.
2024/08/12 12:38:55 wazuh-modulesd:vulnerability-scanner[3999663] scanOrchestrator.hpp:299 at run(): DEBUG: Event type: 11 processed
2024/08/12 12:38:55 indexer-connector[3999663] indexerConnector.cpp:129 at abuseControl(): DEBUG: Agent '024' sync omitted due to abuse control.
```

**cluster status**

```
{
  "cluster_name" : "opensearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 389,
  "active_shards" : 389,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}
```

**Comment by GabrielEValenzuela** [comment]
Hi @ljm5608! How are you?

> After upgrading wazuh version to 4.7.4 -> 4.8.1, the Vulability scan only works in part and does not update.

Could you share more details about the specific issue you're facing?

The message `sync omitted due to abuse control` is a common one. The vulnerability detection feature has a mechanism to prevent an agent from sending too many sync messages when establishing a round-robin connection between nodes. There's a 30-minute window between syncs to control this behavior.

Let me know if there's anything else you'd like to discuss or if you need further assistance! Nice day!

**Comment by ljm5608** [comment]
Thank you for your answer.

The error appeared and the vulnerability scan of one agent was not applied for about 3 days.

How to increase the bandwidth of use control.
agent, is there a way to check the setting values on the server setting side?

**Comment by GabrielEValenzuela** [comment]
Hi @ljm5608 !

You can change the time making a source installation:

https://github.com/wazuh/wazuh/blob/0846daa587119a7c95aff54b59e519fc778fbf92/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L45-L46

Let me know if there's anything else you need!

**Comment by dalso0418** [comment]
Hello.
Is there any way I can take action while it is installed as a package?
A week has passed, but the dashboard is not updated with the same error.

**Comment by GabrielEValenzuela** [comment]
Hi @dalso0418 ! How are you?

The only way to change the value is by source code. 
Did you check the status of the indexer?

Nice day!

**Comment by sebasfalcone** [comment]
Inactive thread, please re open-it if necessary
