### ISSUE TITLE
About custom decoder 

### ISSUE THREAD

**Issue by yunusmrcoban** [wazuh/wazuh#25142]
|Wazuh version| Component | Action type |
|---| --- | --- |
| v4.8.1 | Decoders | Error |

## Description

Hi, I tried to write a custom decoder and I don't get any error but when I test the log the decoder doesn't work. Can you help me? Obviously, I also tried regex but again I could not get any result.

### Current results
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/fa35ba25-61f3-422f-933a-82661c89a9e8">

### Local Rule
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/6293d8a6-6d92-4c5e-aa16-af42c7584562">

### Local Decoder
<img width="686" alt="image" src="https://github.com/user-attachments/assets/112226fb-f028-4f9a-9053-ffb8dacff675">

**Comment by juliancnn** [comment]
Hi @yunusmrcoban,

Could you share with us the information in plain text so we can test the log, rules and decoders you share with us?

On the other hand your log is not json, so the decoder you share does not work, this makes that your log is not being decoded by any decoder, while the rule has as a condition that it is decoded by a decoder called `test`. 

I hope the following resources can help you better understand the operation of custom rulers and decoders:
- For a deeper understanding of creating decoders, refer to [Creating Decoders and Rules from Scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/).
- Learn about sibling decoders in [Sibling Decoders - Flexible Extraction of Information](https://wazuh.com/blog/sibling-decoders-flexible-extraction-of-information/).
- For more detailed guidance, check the [official documentation on custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)
- Don’t forget to test your configurations with [Testing Decoders and Rules](https://documentation.wazuh.com/current/user-manual/ruleset/testing.html)

Regards,

**Comment by yunusmrcoban** [comment]
I made some changes when I realized I was doing it wrong. I share what you want.

Raw Log:

Aug 09 20:50:26 instance-ID: 7dd4ca7f-46b7-4029-be55-7422c78837d5, User: test@test.com, Action: FoldersDelete.delete, Context: DELETE, Status: /folders/11c3c30b-d3dc-4f3d-ab5d-1a802d8db172.json, Created: 1   2024-08-09 20:26:05
Aug 09 20:51:28 instance-ID: 7dd4ca7f-46b7-4030-be56-7422c78837d5, User: test@test.com, Action: ResourcesDelete.delete , Context: DELETE, Status: /folders/11c3c30b-d3dd-4f3d-ab5d-1a802d8db173.json, Created: 1   2024-09-09 20:34:05

Decoder:

Decoder:

<decoder name="testapp">
  <prematch>^.*instance-ID:</prematch>
  <regex>^\s*instance-ID:\s*(\S+),\s*User:\s*([^,]+),\s*Action:\s*([^,]+),\s*Context:\s*([^,]+),\s*Status:\s*([^,]+),\s*Created:\s*(\d+)\s+(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2})</regex>
  <order>instance_id, user, action, context, status, created_num, timestamp</order>
</decoder>

Rule:

<group name="test app">
  <rule id="100901" level="12">
    <decoded_as>testapp</decoded_as>
    <field name="action">FoldersDelete.delete</field>
    <description>Capture delete actions for folders in the application logs.</description>
    <mitre>
      <id>T1070</id>
    </mitre>
  </rule>
  
  <rule id="100902" level="12">
    <decoded_as>testapp</decoded_as>
    <field name="action">ResourcesDelete.delete</field>
    <description>Capture delete actions for resources in the application logs.</description>
    <mitre>
      <id>T1070</id>
    </mitre>
  </rule>
</group>

Thanks.

**Comment by juliancnn** [comment]
Hi @yunusmrcoban, good job, just a few minor adjustments:

- If the predecoder can obtain the program_name, which in this case is obtained as `instance-ID`, then the decoder must have a program_name. This is because decoders are divided into 2 lists, those that have a program_name and those that do not, so when a log is evaluated, if it can get a program_name it will use this list.
- If you want to use PCRE2 regex engine you must specify it, otherwise it will use the os_regex engine by default ([ref here](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html))
- Do not replace the timestamp field if it does not meet the expected timestamp standard, that timestamp is not a date type (see https://github.com/wazuh/wazuh/issues/9949).
- Action is a [static field](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html) and should be used with their tag.


Then the ruleset will look like this:

Decoder
```xml
<decoder name="testapp">
  <program_name>instance-ID</program_name>
  <regex type="pcre2">(?i)([^,]+), user: (\S+), action: (\S+), context: (\S+), Status: ([^,]+), Created: (.*)</regex>
  <order>instance_id, user, action, context, status, created_num, created</order>
</decoder>

```

Rules
```xml
<group name="test-app">
  <rule id="100901" level="12">
    <decoded_as>testapp</decoded_as>
    <action>FoldersDelete.delete</action>
    <description>Capture delete actions for folders in the application logs.</description>
    <mitre>
      <id>T1070</id>
    </mitre>
  </rule>
  
  <rule id="100902" level="12">
    <decoded_as>testapp</decoded_as>
    <action>ResourcesDelete.delete</action>
    <description>Capture delete actions for resources in the application logs.</description>
    <mitre>
      <id>T1070</id>
    </mitre>
  </rule>
</group>

```

Testing logs with logtest:

```bash
╰─# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.7.5
Type one log per line

Aug 09 20:50:26 instance-ID: 7dd4ca7f-46b7-4029-be55-7422c78837d5, User: test@test.com, Action: FoldersDelete.delete, Context: DELETE, Status: /folders/11c3c30b-d3dc-4f3d-ab5d-1a802d8db172.json, Created: 1   2024-08-09 20:26:05

**Phase 1: Completed pre-decoding.
        full event: 'Aug 09 20:50:26 instance-ID: 7dd4ca7f-46b7-4029-be55-7422c78837d5, User: test@test.com, Action: FoldersDelete.delete, Context: DELETE, Status: /folders/11c3c30b-d3dc-4f3d-ab5d-1a802d8db172.json, Created: 1   2024-08-09 20:26:05'
        timestamp: 'Aug 09 20:50:26'
        hostname: 'instance-ID:'
        program_name: 'instance-ID'

**Phase 2: Completed decoding.
        name: 'testapp'
        action: 'FoldersDelete.delete'
        context: 'DELETE'
        created_num: '1   2024-08-09 20:26:05'
        dstuser: 'test@test.com'
        instance_id: '7dd4ca7f-46b7-4029-be55-7422c78837d5'
        status: '/folders/11c3c30b-d3dc-4f3d-ab5d-1a802d8db172.json'

**Phase 3: Completed filtering (rules).
        id: '100901'
        level: '12'
        description: 'Capture delete actions for folders in the application logs.'
        groups: '['test-app']'
        firedtimes: '1'
        mail: 'True'
        mitre.id: '['T1070']'
        mitre.tactic: '['Defense Evasion']'
        mitre.technique: '['Indicator Removal on Host']'
**Alert to be generated.

```

Regards,

**Comment by yunusmrcoban** [comment]
Hi @juliancnn 
It worked!  Thanks for support!

Regards,
