### ISSUE TITLE
Release 4.9.0 - Beta 2 - E2E UX tests - RBAC

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#25166]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.9.0-beta2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Aug 12, 2024 and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-pyserver team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Aug 13, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Aug 14, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Installation assistant](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-indexer/installation-assistant.html) | Multi node | CentOS 7 x86_64 |
| Server | [Installation assistant](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-server/installation-assistant.html) | Single node | CentOS 7 x86_64 |
| Dashboard | [Installation assistant](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-dashboard/installation-assistant.html) | - | CentOS 7 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.9.0-beta2/_images/deploy-new-agent-from-ui1.png) | - | CentOS 7 x86_64 |

## Test description

Follow and complete the documentation steps and the examples, ensuring the access is adequate based on each requirement:

https://documentation-dev.wazuh.com/v4.9.0-beta2/user-manual/user-administration/rbac.html?highlight=RBAC

## Known issues

- https://github.com/wazuh/wazuh-documentation/issues/6893

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Wazuh Indexer  multinode - installation assistant   |  |   |
| 🟢 |  Wazuh server setup - installation assistant|  |  |
| 🟢 |  Wazuh dashboard setup - installation assistant |  |  |
| 🟢 |  Wazuh agent setup - WUI one liner|  |  |
| 🟢 |  Test case: Creating and setting a Wazuh admin user |  |  |
| 🟢 |  Test case: Creating and setting a Wazuh read-only user  |  |  |
| 🟢 |  Test case: Use case: Give a user permission to read and manage a group of agents  |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **No ambiguities. Testing guidelines were clear**
- Did you face any challenges not covered by the guideline?
  - **No**
- Suggestions for improvement:
  - **Nil**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/devel-pyserver

**Comment by ihost-007** [comment]
### Installing Wazuh Indexer Cluster

**Wazuh Indexer Node 1**

**System Info** 

![Screenshot 2024-08-12 223847](https://github.com/user-attachments/assets/85a2f64c-5a8a-454e-841b-0dadd13751c8)

**Certificate Creation** 

![Screenshot 2024-08-12 224826](https://github.com/user-attachments/assets/56bfbb81-79dc-4ef8-98df-bc97d46b9e6b)

**Running installation assistant**

![Screenshot 2024-08-12 232734](https://github.com/user-attachments/assets/094da8c3-3ee3-42a6-a156-b93f444c4b47)

![Screenshot 2024-08-13 004155](https://github.com/user-attachments/assets/652402c2-49b3-4b1e-adb2-9f3b536275d1)

![Screenshot 2024-08-13 001153](https://github.com/user-attachments/assets/20228a4d-1ba9-4026-8ac0-97025a67167d)

**Wazuh Indexer Node 2**

**System Info**

![Screenshot 2024-08-12 232902](https://github.com/user-attachments/assets/16fa699c-d657-4073-a7a6-e2785b449751)

**Running Installtion Node 2**

![Screenshot 2024-08-13 000859](https://github.com/user-attachments/assets/8a862bf5-7beb-4351-a327-122c0e9ca9c0)

![Screenshot 2024-08-13 004018](https://github.com/user-attachments/assets/872d28a8-2551-4590-8c8d-df9aa63bf210)

**Comment by ihost-007** [comment]
Wazuh Server Setup

System Info
![Screenshot 2024-08-13 001215](https://github.com/user-attachments/assets/d7e5fda7-4e9e-43bc-96be-3f3021befba3)

Setting up the Wazuh server with the Installation Assistant
![Screenshot 2024-08-13 002235](https://github.com/user-attachments/assets/6444ce87-b459-404c-86f6-a9bb92b90d81)
![Screenshot 2024-08-13 004100](https://github.com/user-attachments/assets/4f101561-30b9-4ad7-8d47-230ce2f696d8)

**Comment by ihost-007** [comment]
### Wazuh Dashboard Setup

**System Info**
![Screenshot 2024-08-13 002329](https://github.com/user-attachments/assets/a5f6d550-ca7f-4d03-a56b-2eed07c237d8)

**Wazuh Dashboard Installation Assistant**
![image](https://github.com/user-attachments/assets/c10e6c64-ede6-4b2a-9648-dc7d9f91db41)

![Screenshot 2024-08-13 004121](https://github.com/user-attachments/assets/b1501f91-9357-402b-8630-01b093e166f2)

**Comment by ihost-007** [comment]
### Wazuh Agent Installation

**Using Wazuh WUI one-liner command**
![image](https://github.com/user-attachments/assets/e26dbcf0-f024-45f4-a3f0-2dea6e31b516)

![Screenshot 2024-08-13 005106](https://github.com/user-attachments/assets/bf7cf13b-4c8a-4edd-acbd-0031e155194f)

**Comment by ihost-007** [comment]
### Creating and setting a Wazuh admin user

**Created the user TestUser**
![Screenshot 2024-08-13 005527](https://github.com/user-attachments/assets/accd4594-8ddd-4d14-a24d-42eaabbb4945)
![Screenshot 2024-08-13 005800](https://github.com/user-attachments/assets/df09e51c-8d48-48f4-97fe-4a2b1f3ab82a)

**Mapped the user created to the duplicated role**
![Screenshot 2024-08-13 010019](https://github.com/user-attachments/assets/e03c8257-0d95-439c-a4df-0584285397ca)
![Screenshot 2024-08-13 010107](https://github.com/user-attachments/assets/d4a0c1c2-8855-4e91-ba3b-7240a90ec353)
![Screenshot 2024-08-13 010238](https://github.com/user-attachments/assets/a9dae3a4-f354-427e-9670-e86947f43ea6)

**Created the Wazuh internal mapping**
![Screenshot 2024-08-13 010545](https://github.com/user-attachments/assets/897a8e08-4ba4-467f-8176-1080581a7e2a)

**Test the created user**
![Screenshot 2024-08-13 011102](https://github.com/user-attachments/assets/8c1036ff-a986-4656-89b6-5b9b7152b9e7)
![Screenshot 2024-08-13 011118](https://github.com/user-attachments/assets/7e87471d-3d63-4077-a95d-4873e92e1329)

**Comment by ihost-007** [comment]
### Creating and setting a Wazuh read-only user

Created internal user TestReadOnly
![Screenshot 2024-08-13 011333](https://github.com/user-attachments/assets/5ea9020f-dbe3-4866-b616-b1b9ada1496c)
![Screenshot 2024-08-13 011408](https://github.com/user-attachments/assets/9503e9c3-e22b-49fb-bd86-1ef11483f063)

Created user Role
![Screenshot 2024-08-13 012154](https://github.com/user-attachments/assets/e700c9d3-f5e2-46c6-8450-bdb2c3ecbf40)
![Screenshot 2024-08-13 012207](https://github.com/user-attachments/assets/77778ca0-d6cb-4364-8e2b-5f05ab1f6810)
![Screenshot 2024-08-13 012346](https://github.com/user-attachments/assets/345f10eb-36a1-45fb-a404-d5951cb406fa)

Created Role map
![Screenshot 2024-08-13 012824](https://github.com/user-attachments/assets/a1623806-0372-484f-a476-19e06745f3d4)

Testing Read only user TestReadOnly
![Screenshot 2024-08-13 013330](https://github.com/user-attachments/assets/24f9cc85-0f7c-4b74-bddc-535f4d51103e)
![Screenshot 2024-08-13 013341](https://github.com/user-attachments/assets/7452c023-7aae-42c5-8792-3aa7dfb31a8e)

As a read only user, User can not edit Agent group (Add new group is grayed out) 
![Screenshot 2024-08-13 015136](https://github.com/user-attachments/assets/ab9a6d71-41a0-42dd-9e59-3b24e3e913f8)

**Comment by ihost-007** [comment]
### Use case: Give a user permissions to read and manage a group of agents

**Create an internal user Groupuser and added the Agentgroup label**
![Screenshot 2024-08-13 015623](https://github.com/user-attachments/assets/e9dda1f4-960b-4629-914b-bfc44d0bed0c)
![Screenshot 2024-08-13 024748](https://github.com/user-attachments/assets/c41149ff-747a-4239-9a40-fbb5b7e47e9e)


**Created WazuhGroupUser Role** 
![Screenshot 2024-08-13 020329](https://github.com/user-attachments/assets/5446f367-a3bc-45ad-8b12-ee2408d98b3a)

**Created a policy for the Testcase group** 
![Screenshot 2024-08-13 021057](https://github.com/user-attachments/assets/a835f8c2-9b9e-445a-9ada-e941e888c355)

**Created Wazuh Role for the policy created in the previous step and then mapped the user**
![Screenshot 2024-08-13 021203](https://github.com/user-attachments/assets/6671d5a7-872b-4f6f-8771-0e8a4d8b1ded)
![Screenshot 2024-08-13 025313](https://github.com/user-attachments/assets/ecebbe5d-cfbb-42fa-a9ff-4d7b5cbb5948)

**Test use case**
![Screenshot 2024-08-13 025608](https://github.com/user-attachments/assets/bcc8db46-e72a-480c-8bdc-c8a647ea9283)
![Screenshot 2024-08-13 025556](https://github.com/user-attachments/assets/13562d12-f8fd-44ae-824c-ee189899d3af)

**Comment by fdalmaup** [comment]
# Review

Requested a minor change related to the console output of the Dashboard installation. Leaving the issue On Hold until the modification is carried out.

**Comment by ihost-007** [comment]
@fdalmaup This has been updated.

**Comment by fdalmaup** [comment]
# Review 

LGTM, neat work!

**Comment by rauldpm** [comment]
I can't find the `Creating an internal user and mapping it to Wazuh` section, also, the use case does not show all steps or data, I would expect that if the following code has to be added to an index, there should be a screenshot about that

```
{
  "bool": {
    "must": {
      "match": {
        "group": "Team_A"
      }
    }
  }
}
```

I can't see references to the wazuh.yml file changes mentioned in the documentation

**Comment by ihost-007** [comment]
Creating an internal user and mapping it to Wazuh

Created internal user WazuhInternalUser
![Screenshot 2024-08-13 013513](https://github.com/user-attachments/assets/34c37070-ef47-44dd-8ad0-01755bbb7f47)
![Screenshot 2024-08-13 013541](https://github.com/user-attachments/assets/b0ef59d9-364e-4707-b4ea-712a981efb27)

Map User
![Screenshot 2024-08-13 013942](https://github.com/user-attachments/assets/792e7543-cac8-4908-a3f0-9ef4f303328f)
![Screenshot 2024-08-13 013959](https://github.com/user-attachments/assets/6cbd8531-c346-4fdd-ae32-de72ac26f4bd)

Create Role Mapping
![Screenshot 2024-08-13 014235](https://github.com/user-attachments/assets/79ff639e-9a86-4044-bf36-5e53633931f6)
![Screenshot 2024-08-13 014250](https://github.com/user-attachments/assets/000cbb47-55aa-4a19-b171-9ff606b954a3)

**Comment by ihost-007** [comment]
@rauldpm I have added those images and the missing section.

**Comment by fdalmaup** [comment]
Hi @ihost-007. If the status before `On Hold` was `In Final review`, when the required changes are carried out it should go back to Pending Final review. Nevertheless, I checked the newly attached images and some of them do not have filled the same fields as the documentation use case, for example, the `Created a policy for the Testcase group` [here](https://github.com/wazuh/wazuh/issues/25166#issuecomment-2286700620) does not have the `Resource` field with the required value.

Moving it to On Hold.
