### ISSUE TITLE
Release 4.9.0 - Beta 2 - E2E UX tests - Change custom logos

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#25165]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.9.0-beta2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-dashboard team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Aug 12, 2024 and notify the @wazuh/devel-dashboard team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-dashboard team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Aug 13, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Aug 14, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-indexer/step-by-step.html) | Single node | Fedora 39 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-server/step-by-step.html) | Multi node | Fedora 39 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.9.0-beta2/installation-guide/wazuh-dashboard/step-by-step.html) | - | Fedora 39 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.9.0-beta2/_images/deploy-new-agent-from-ui1.png) | - | CentOS Stream 9 x86_64 |

## Test description

Follow and complete the documentation steps and the examples:

https://documentation-dev.wazuh.com/v4.9.0-beta2/user-manual/wazuh-dashboard/custom-branding.html

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Indexer installation | - | - |
| 🟢 | Wazuh server - Master | - | -|
| 🟢 | Cluster configuration - Wazuh server master  | - | -|
| 🟢 | Wazuh server - Worker | - | -|
| 🟢 | Cluster configuration - Wazuh server worker | - | -|
| 🟢 | Wazuh dashboard installation | - | -|
| 🟢 | Agent installation with one-liner | - | -|
| 🟢  | Health check logo| - | - | 
| 🟡 | App main logo | Needs documentation improvement | Previous tester created an issue [wazuh/wazuh-documentation#7647](https://github.com/wazuh/wazuh-documentation/issues/7647) |
| 🔴 | Wazuh dashboard home logo | Needs documentation improvement about the need to restart the Wazuh dashboard service | https://github.com/wazuh/wazuh-documentation/issues/7667 |
| 🟢 | Custom branding of the PDF reports | - | - |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - The guideline had no ambiguities 
- Did you face any challenges not covered by the guideline?
  - No challenges faced
- Suggestions for improvement:
  - None

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @davidjiglesias
- [x] @wazuh/devel-dashboard

**Comment by ace-109** [comment]
# Infrastructure

## Wazuh Indexer

```
root@indexer:/home/wazuh# uname -a
Linux indexer 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
```

## Wazuh Server - Master

```
root@master:/home/wazuh# uname -a
Linux master 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
```

## Wazuh Server - Worker

```
root@worker:/home/wazuh# uname -a
Linux worker 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
```

## Wazuh Dashboard 

```
root@dashboard:/home/wazuh# uname -a
Linux dashboard 6.5.6-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct  6 19:57:21 UTC 2023 x86_64 GNU/Linux
```

**Comment by ace-109** [comment]
# Indexer installation

## Cert installation

I downloaded the config file and the Wazuh cert tools

```
root@worker:/home/wazuh# curl -sO https://packages-dev.wazuh.com/4.9/wazuh-certs-tool.sh
curl -sO https://packages-dev.wazuh.com/4.9/config.yml
```
I updated the config.yml file with the correct values

```
root@worker:/home/wazuh# cat config.yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "192.168.33.131"
    #- name: node-2
    #  ip: "<indexer-node-ip>"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "192.168.33.133"
      node_type: master
    - name: wazuh-2
      ip: "192.168.33.132"
      node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "192.168.33.134"
```

**Comment by ace-109** [comment]
# Wazuh server - Master

I added the Wazuh repo

```
root@master:/home/wazuh# rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
root@master:/home/wazuh# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
```
Wazuh manager installation
The Wazuh manager successfully installed
```
root@master:/home/wazuh# yum -y install wazuh-manager
EL-39 - Wazuh                                                                                              1.4 MB/s |  28 MB     00:20
Last metadata expiration check: 0:00:34 ago on Mon 12 Aug 2024 12:57:21 PM WAT.
Dependencies resolved.
===========================================================================================================================================
 Package                               Architecture                   Version                          Repository                     Size
===========================================================================================================================================
Installing:
 wazuh-manager                         x86_64                         4.9.0-1                          wazuh                         304 M

Transaction Summary
===========================================================================================================================================
Install  1 Package

Total download size: 304 M
Installed size: 857 M
Downloading Packages:
[MIRROR] wazuh-manager-4.9.0-1.x86_64.rpm: Curl error (28): Timeout was reached for https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.9.0-1.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
[MIRROR] wazuh-manager-4.9.0-1.x86_64.rpm: Curl error (28): Timeout was reached for https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.9.0-1.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]
wazuh-manager-4.9.0-1.x86_64.rpm                    0% [                                                 ] 820 kB/s |   0  B     06:19 ETA
wazuh-manager-4.9.0-1.x86_64.rpm                                                  540 kB/s | 304 MB     09:35    T
------------------------------------------------------------------------------------------------------------------
Total                                                                             540 kB/s | 304 MB     09:35
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                          1/1
  Running scriptlet: wazuh-manager-4.9.0-1.x86_64                                                             1/1
  Installing       : wazuh-manager-4.9.0-1.x86_64                                                             1/1
  Running scriptlet: wazuh-manager-4.9.0-1.x86_64                                                             1/1
  Verifying        : wazuh-manager-4.9.0-1.x86_64                                                             1/1

Installed:
  wazuh-manager-4.9.0-1.x86_64

Complete!
```

**Comment by ace-109** [comment]
# Wazuh server - Worker 🟢

I added the Wazuh repo
```
root@worker:/home/wazuh# rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
root@worker:/home/wazuh# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
```
The Wazuh manager successfully installed
```
root@worker:/home/wazuh# yum -y install wazuh-manager
EL-39 - Wazuh                                                      4.8 MB/s |  28 MB     00:05
Last metadata expiration check: 0:00:17 ago on Mon 12 Aug 2024 01:57:42 PM WAT.
Dependencies resolved.
===================================================================================================
 Package                     Architecture         Version                Repository           Size
===================================================================================================
Installing:
 wazuh-manager               x86_64               4.9.0-1                wazuh               304 M

Transaction Summary
===================================================================================================
Install  1 Package

Total download size: 304 M
Installed size: 857 M
Downloading Packages:
wazuh-manager-4.9.0-1.x86_64.rpm                                   5.5 MB/s | 304 MB     00:55
---------------------------------------------------------------------------------------------------
Total                                                              5.5 MB/s | 304 MB     00:55
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                           1/1
  Running scriptlet: wazuh-manager-4.9.0-1.x86_64                                              1/1
  Installing       : wazuh-manager-4.9.0-1.x86_64                                              1/1
  Running scriptlet: wazuh-manager-4.9.0-1.x86_64                                              1/1
  Verifying        : wazuh-manager-4.9.0-1.x86_64                                              1/1

Installed:
  wazuh-manager-4.9.0-1.x86_64

Complete!
```

**Comment by ace-109** [comment]
# Wazuh dashboard installation 🟢
I installed the dependency and imported the Wazuh repo
```
root@dashboard:/home/wazuh# yum install libcap
EL-39 - Wazuh                                                      4.0 MB/s |  28 MB     00:06
Last metadata expiration check: 0:00:22 ago on Mon 12 Aug 2024 02:24:55 PM WAT.
Package libcap-2.48-7.fc39.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

```
root@dashboard:/home/wazuh# rpm --import https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
root@dashboard:/home/wazuh# echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' | tee /etc/yum.repos.d/wazuh.repo
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-$releasever - Wazuh
baseurl=https://packages-dev.wazuh.com/pre-release/yum/
protect=1
```

**Comment by ace-109** [comment]
# Agent installation with one-liner 🟢

I navigated to `Server management` -> `Endpoint summary` and clicked on `Deploy new agent`
![image](https://github.com/user-attachments/assets/85d778d1-af46-48c4-ad66-f82ca9a79f5f)
I filled the appropriate fields, copied and edited the command
![image](https://github.com/user-attachments/assets/17a28c07-bd50-4dbe-a142-98f30a4d6d68)

```
[root@wazuh vagrant]# curl -o wazuh-agent-4.9.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.0-1.x86_64.rpm && sudo WAZUH_MANAGER='192.168.33.13' WAZUH_AGENT_NAME='Cent-stream-9' rpm -ihv wazuh-agent-4.9.0-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.4M  100 10.4M    0     0  2188k      0  0:00:04  0:00:04 --:--:-- 2247k
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-agent-4.9.0-1 
```

```
[root@wazuh vagrant]# sudo systemctl daemon-reload
sudo systemctl enable wazuh-agent
sudo systemctl start wazuh-agent
```

**Comment by ace-109** [comment]
# Setting up custom branding

## Custom logos in the Wazuh dashboard

### App loading and Health check logos

I clicked on `Dashboard management` > `App Settings`

![image](https://github.com/user-attachments/assets/1d25b489-92d4-4610-8549-d7dab3d42d1e)

The interface after changing the logos
![image](https://github.com/user-attachments/assets/0cec69cb-d921-4c5c-8592-2d4e2a3fe2d9)

It was successfully saved
![image](https://github.com/user-attachments/assets/2e1d1e78-5b3d-42a5-ba42-267407fdf0b1)

I can also see the files in the `/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom/images/` directory

```
root@dashboard:/home/wazuh# ls /usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom/images/
customization.logo.app.jpg  customization.logo.healthcheck.png
```

### Wazuh dashboard home logo
I edited the `/etc/wazuh-dashboard/opensearch_dashboards.yml` file with the URL to the logos

```
server.host: 0.0.0.0
server.port: 443
opensearch.hosts: https://192.168.33.131:9200
opensearch.ssl.verificationMode: certificate
opensearch.requestHeadersAllowlist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/wazuh-dashboard/certs/dashboard-key.pem"
server.ssl.certificate: "/etc/wazuh-dashboard/certs/dashboard.pem"
opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
uiSettings.overrides.defaultRoute: /app/wz-home
opensearchDashboards.branding:
   mark:
      defaultUrl: "https://i.imgur.com/XXXXXX.jpeg"
      darkModeUrl: "https://i.imgur.com/XXXXXXX.png"

```

**Comment by ace-109** [comment]
# Custom branding of the PDF reports 🟢 

I navigated to `Dashboard management` > `App Settings` and updated the necessary field for the PDF customization
![image](https://github.com/user-attachments/assets/3ebe0bc8-c2b4-421f-bc82-e69c31b9f808)

I navigated to `Threat Hunting` > `Generate report` and I downloaded the report. The customization can be seen on the report screenshot below
![image](https://github.com/user-attachments/assets/0085b5a0-4282-4a42-b787-fff505847029)
[wazuh-module-overview-general-1723562331.pdf](https://github.com/user-attachments/files/16601713/wazuh-module-overview-general-1723562331.pdf)

**Comment by rauldpm** [comment]
LGTM, nice work!

Take into account that the wrong branch has been used for the filebeat template, the tag v4.9.0-beta2 should have been used

> curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/4.9.0/extensions/elasticsearch/7.x/wazuh-template.json

As this file does not have changes between the tag and the branch, it does not affect the testing results, please be careful next time
