### ISSUE TITLE
Remoted sometimes fails to download external merged files on startup

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2516]
|Version|Components|
|---|---|
|3.5.0+|Remoted, Modulesd|

Remoted can download external shared files for agents. This is configured at _etc/shared/files.yml_.

This feature depends on the Download module, running in Wazuh Modulesd, so Remoted requires Modulesd is running when it needs to download a file.

Since Remoted and Modulesd start at the same time, it may happen that Modulesd is not ready when Remoted requests a download.

## Remediation plan

If Remoted finds a valid _files.yml_ file, it shall perform a health check of the Download module. If it's not available in 10 seconds, show an error and continue.

**Comment by chemamartinez** [comment]
Merged: #2517
