### ISSUE TITLE
Use fastfloat from VCPKG

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25176]
## Description
This issue aims to start using fastfloat from vcpkg, at the moment it is not uploaded in the vcpkg repository, therefore we will have to make use of what has been researched in: https://github.com/wazuh/wazuh-agent/issues/38

## Expected
- Use fast_float from vcpkg during the engine compilation.

**Comment by NahuFigueroa97** [comment]
## Update

- Investigate https://github.com/wazuh/wazuh-agent/issues/38

**Comment by NahuFigueroa97** [comment]
## Update

- [Use packages with CMake](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started?pivots=shell-cmd)
- [Package a library with vcpkg](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging?pivots=shell-cmd)
- [Add a port to the vcpkg open-source registry](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-adding-to-registry?pivots=shell-cmd)

Once both the vcpkg.json and the portfile.cmake were added I found that the fast_float library was already available in the vcpkg repositories unlike what is mentioned in the edition. Running the following command: `./vcpkg search fast-float`

**Comment by NahuFigueroa97** [comment]
## Update

- [Install and use packages with CMake](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started?pivots=shell-cmd)
- [Package a library with vcpkg](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-packaging?pivots=shell-cmd)
- [Add a port to the vcpkg open-source registry](https://learn.microsoft.com/en-us/vcpkg/get_started/get-started-adding-to-registry?pivots=shell-cmd)

After completing the previous guides I found that the fast_float library is now available in the vcpkg ports. Running the following command: `./vcpkg search fast-float`

### Changes

- Remove fast_float installation with CPMAddPackage
- Add the fast_float library to the vcpkg.json in both dependencies and overrides

**Comment by NahuFigueroa97** [comment]
## Update

- Fixed PR observations
