### ISSUE TITLE
Release 4.9.0 - Beta 2 - Workload benchmarks metrics

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25175]
The following issue aims to run all `workload benchmarks` for the current release candidate, report the results, and open new issues for any encountered errors.

## Workload benchmarks metrics information
|                                               |                                            |
|-----------------------------------------------|--------------------------------------------|
| **Main release candidate issue**              |              https://github.com/wazuh/wazuh/issues/25126                              |
| **Version**                                   |                      4.9.0                      |
| **Release candidate #**                       |                     Beta 2                       |
| **Tag**                                       |                    https://github.com/wazuh/wazuh/tree/v4.9.0-beta2                        |
| **Previous Workload benchmarks metrics issue**|               https://github.com/wazuh/wazuh/issues/25053                             |

## Test configuration
All tests will be run and workload performance metrics will be obtained for the following clustered environment configurations:

|                   |                    |
|-------------------|--------------------|
| **# Agents**      | **# Worker nodes** |
|      50000             |       25             |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found https://github.com/wazuh/wazuh/issues/25175#issuecomment-2286564808 and https://github.com/wazuh/wazuh/issues/25175#issuecomment-2286618328.

Most of the tests have some failure related to the `wazuh-db` errors described in the logs. The following Issues were created:
- https://github.com/wazuh/wazuh/issues/25212

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @fdalmaup 
- [ ] @wazuh/devel-qa

**Comment by RamosFe** [comment]
## API performance tests 🔴  

Artifacts: [api_performance_tests.zip](https://github.com/user-attachments/files/16602014/api_performance_tests.zip)

### Tests results

| **Endpoint test name**  | **Status** | **Issues Ref.** |
|--|--|--|
| GET /cluster/local/info | :green_circle: | |
| GET /cluster/nodes| :green_circle:  | |
| GET /cluster/healthcheck | :green_circle: | |
| GET /cluster/status | :green_circle: | |
| GET /cluster/local/config | :green_circle: | |
| GET /cluster/api/config | :green_circle: | |
| GET /cluster/configuration/validation | :green_circle: | |
| GET /manager/status | :green_circle: | |
| GET /manager/info | :green_circle: | |
| GET /manager/configuration | :green_circle: | |
| GET /manager/logs | :green_circle:   | |
| GET /manager/api/config | :green_circle: | |
| GET /manager/configuration/validation | :green_circle: | |
| GET /mitre/groups | :green_circle: | |
| GET /mitre/metadata | :green_circle: | |
| GET /mitre/mitigations | :green_circle: | |
| GET /mitre/references | :green_circle: | |
| GET /mitre/software | :green_circle: | |
| GET /mitre/tactics | :green_circle: | |
| GET /mitre/techniques | :green_circle: | |
| GET /overview/agents | :green_circle:  |  |
| GET /tasks/status | :green_circle: | |
| PUT /active-response | :green_circle:   |  |
| PUT /rootcheck | :green_circle: | |
| PUT /syscheck | :green_circle: | |
| POST /groups | :green_circle: | |
| POST /security/users | :green_circle: | |
| POST /security/roles | :green_circle: | |
| POST /security/policies | :green_circle: | |
| POST /security/rules | :green_circle: | |
| PUT /agents/group | :green_circle: | |
| PUT /agents/group/new_test_group/restart | :green_circle: | |
| PUT /agents/restart | :red_circle:  |  |
| POST /agents | :green_circle: | |
| POST /agents/insert​|  :green_circle: | |
| POST /agents/insert​/quick | :green_circle: | |
| GET /agents | :green_circle: | |
| GET /agents/no_group | :green_circle: | |
| GET /agents/outdated | :green_circle: | |
| GET /decoders | :green_circle: | |
| GET /groups | :green_circle: | |
| GET /lists | :green_circle: | |
| GET /rules | :green_circle: | |
| GET /security/users | :green_circle: | |
| GET /security/roles | :green_circle: | |
| GET /security/policies | :green_circle: | |
| GET /security/rules | :green_circle: | |
| DELETE /groups | :green_circle: | |
| DELETE /agents | :red_circle: |  |
| DELETE /security/users | :red_circle:  |  |
| DELETE /security/roles | :green_circle: | |
| DELETE /security/policies | :green_circle: | |
| DELETE /security/rules | :green_circle: | |
| PUT /manager/restart | :green_circle: | |
| PUT /cluster/restart | :green_circle: | |

**Comment by RamosFe** [comment]
## Cluster performance tests :red_circle: 

Artifacts: [test_cluster_performance.zip](https://github.com/user-attachments/files/16602041/test_cluster_performance.zip)

The test failed with the error
 
<details>

<summary>Results</summary>

```console
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.9.18, pytest-7.1.2, pluggy-1.4.0
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh-qa/tests, configfile: pytest.ini
plugins: metadata-3.1.1, html-3.1.1, testinfra-5.0.0
collected 1 item                                                                                                                                                                                                                        

test_cluster_performance.py 
Setup phase took 0:28:38s (2024/08/12 13:32:13 - 2024/08/12 14:00:51).
Stable phase took 0:00:45s (2024/08/12 14:00:51 - 2024/08/12 14:01:36).
F

=============================================================================================================== FAILURES ================================================================================================================
_______________________________________________________________________________________________________ test_cluster_performance ________________________________________________________________________________________________________

artifacts_path = '/home/federamos/Downloads/archive/artifacts', n_workers = 25, n_agents = 50000

    def test_cluster_performance(artifacts_path, n_workers, n_agents):
        """Check that a cluster environment did not exceed certain thresholds.
    
        This test obtains various statistics (mean, max, regression coefficient) from CSVs with
        data generated in a cluster environment (resources used and duration of tasks). These
        statistics are compared with thresholds established in the data folder.
    
        Args:
            artifacts_path (str): Path where CSVs with cluster information can be found.
            n_workers (int): Number of workers folders that are expected inside the artifacts path.
            n_agents (int): Number of agents in the cluster environment.
        """
        if None in (artifacts_path, n_workers, n_agents):
            pytest.fail("Parameters '--artifacts_path=<path> --n_workers=<n_workers> --n_agents=<n_agents>' are required.")
    
        # Check if there are threshold data for the specified number of workers and agents.
        selected_conf = f"{n_workers}w_{n_agents}a"
        if selected_conf not in configurations:
            pytest.fail(f"This is not a supported configuration: {selected_conf}. "
                        f"Supported configurations are: {', '.join(configurations.keys())}.")
    
        # Check if path exists and if expected number of workers matches what is found inside artifacts.
        try:
            cluster_info = ClusterEnvInfo(artifacts_path).get_all_info()
        except FileNotFoundError:
            pytest.fail(f"Path '{artifacts_path}' could not be found or it may not follow the proper structure.")
    
        if cluster_info.get('worker_nodes', 0) != int(n_workers):
            pytest.fail(f"Information of {n_workers} workers was expected inside the artifacts folder, but "
                        f"{cluster_info.get('worker_nodes', 0)} were found.")
    
        # Calculate stats from data inside artifacts path.
        data = {'tasks': ClusterCSVTasksParser(artifacts_path).get_stats(),
                'resources': ClusterCSVResourcesParser(artifacts_path).get_stats()}
    
        if not data['tasks'] or not data['resources']:
            pytest.fail(f"Stats could not be retrieved, '{artifacts_path}' path may not exist, it is empty or it may not"
                        f" follow the proper structure.")
    
        # Compare each stat with its threshold.
        for data_name, data_stats in data.items():
            for phase, files in data_stats.items():
                for file, columns in files.items():
                    for column, nodes in columns.items():
                        for node_type, stats in nodes.items():
                            for stat, value in stats.items():
                                th_value = configurations[selected_conf][data_name][phase][file][column][node_type][stat]
                                if value[1] >= th_value:
                                    exceeded_thresholds.append({'value': value[1], 'threshold': th_value, 'stat': stat,
                                                                'column': column, 'node': value[0], 'file': file,
                                                                'phase': phase})
    
        try:
>           assert not exceeded_thresholds, 'Some thresholds were exceeded:\n- ' + '\n- '.join(
                '{stat} {column} {value} >= {threshold} ({node}, {file}, {phase})'.format(**item) for item in
                exceeded_thresholds)
E               AssertionError: Some thresholds were exceeded:
E                 - max time_spent(s) 427.046 >= 50 (worker_16, agent-info_sync, setup_phase)
E                 - mean time_spent(s) 4.177669334303382 >= 3.1 (master, agent-info_sync, setup_phase)
E                 - max time_spent(s) 426.894 >= 31 (master, agent-info_sync, setup_phase)
E                 - reg_cof USS(KB) 475.21777864436854 >= 332.64 (master, wazuh-clusterd, setup_phase)
E                 - reg_cof FD 0.2181496295324897 >= 0.1 (master, wazuh-clusterd, setup_phase)
E               assert not [{'column': 'time_spent(s)', 'file': 'agent-info_sync', 'node': 'worker_16', 'phase': 'setup_phase', ...}, {'column': ...phase': 'setup_phase', ...}, {'column': 'FD', 'file': 'wazuh-clusterd', 'node': 'master', 'phase': 'setup_phase', ...}]

test_cluster_performance.py:85: AssertionError
----------------------------------------- generated html file: file:///home/federamos/Documents/Wazuh/Repositories/wazuh-qa/tests/performance/test_cluster/test_cluster_performance/report.html -----------------------------------------
======================================================================================================== short test summary info ========================================================================================================
FAILED test_cluster_performance.py::test_cluster_performance - AssertionError: Some thresholds were exceeded:
=========================================================================================================== 1 failed in 0.71s ===========================================================================================================
```

</details>


## Cluster tasks :red_circle: 

Artifacts: [artifacts.zip](https://github.com/user-attachments/files/16499026/artifacts.zip)

Obtained the tasks' duration manually by modifying the `tests/performance/test_cluster/test_cluster_performance/test_cluster_performance.py` file print the data. These were the results:

<details><summary>Tasks</summary>

```json
        "setup_phase": {
            "agent-info_sync": {
                "time_spent(s)": {
                    "workers": {
                        "mean": ("worker_17", 4.3462410714285715),
                        "max": ("worker_16", 427.046),
                    },
                    "master": {
                        "mean": ("master", 4.177669334303382),
                        "max": ("master", 426.894),
                    },
                }
            },
            "integrity_check": {
                "time_spent(s)": {
                    "workers": {
                        "mean": ("worker_12", 0.1180225988700565),
                        "max": ("worker_22", 1.723),
                    },
                    "master": {
                        "mean": ("master", 0.005866576209859792),
                        "max": ("master", 0.315),
                    },
                }
            },
            "integrity_sync": {
                "time_spent(s)": {
                    "workers": {
                        "mean": ("worker_21", 0.04148),
                        "max": ("worker_8", 0.116),
                    },
                    "master": {
                        "mean": ("master", 0.29067226219024783),
                        "max": ("master", 1.817),
                    },
                }
            },
        },
        "stable_phase": {
            "agent-info_sync": {
                "time_spent(s)": {
                    "workers": {
                        "mean": ("worker_9", 0.005),
                        "max": ("worker_2", 0.018),
                    },
                    "master": {
                        "mean": ("master", 0.0020000000000000005),
                        "max": ("master", 0.002),
                    },
                }
            },
            "integrity_check": {
                "time_spent(s)": {
                    "workers": {
                        "mean": ("worker_19", 0.0124),
                        "max": ("worker_19", 0.022),
                    },
                    "master": {
                        "mean": ("master", 0.0040560000000000014),
                        "max": ("master", 0.016),
                    },
                }
            },
        },
```

</details>

All values are within the ranges defined in [25w_50000a_thresholds.yaml](https://github.com/wazuh/wazuh-qa/blob/master/tests/performance/test_cluster/test_cluster_performance/data/25w_50000a_thresholds.yaml), except for the `agent_info-sync`.

**Comment by fdalmaup** [comment]
# Review

As correctly mentioned, the errors seem to be directly related to `wazuh-db` and a possible bug that did not allow the cluster to carry out the `Agent-groups` task properly.

LGTM
