### ISSUE TITLE
Release 4.9.0 - Beta 2 - Demo use cases

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#25171]
### Demo use cases information
|                                  |                                                                 |
|--------------------------------- |--------------------------------------------                     |
| **Main release stage issue**     |  #25126                                        |
| **Version**                      | 4.9.0                                                   |
| **Release stage**                | Beta 2                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-beta2          |
| **Previous Demo use cases**      | #24875                                                   |

---

## Checks
Status | Use case               | Issues |
:--:   | :--                     | :--:    |
:green_circle:     | Audit                  |        |
:green_circle:     | AWS Wodle              |        |
:green_circle:     | Brute force            |        |
:green_circle:     | Docker                 |        |
:green_circle:     | Emotet                 |        |
:green_circle:     | FIM                    |        |
:green_circle:     | IP Reputation          |        |
:green_circle:     | Netcat                 |        |
:green_circle:     | Osquery                |        |
:green_circle:     | Shellshock             |        |
:green_circle:     | SQL Injection          |        |
:green_circle:     | Slack                  |        |
:green_circle:     | Suricata               |        |
:green_circle:     | Trojan                 |        |
:green_circle:     | Virustotal             |        |
:green_circle:     | Vulnerability Detector |        |
:green_circle:     | Yara                   |        |
:green_circle:     | Windows Defender       |        |

---

Status legend:
:black_circle: - Pending/In progress
:white_circle: - Skipped
:red_circle: - Rejected
:yellow_circle: - Ready to review
:black_circle: - Approved

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @davidjiglesias

**Comment by davidcr01** [comment]
### Deployment
The deployment succeeded: [JenkinsJob](https://ci.wazuh.info/job/Procedure_deploy_demo/485/console).

### UC Tests
All the automatic UC tests succeeded except for the VD one.
This test was manually validated:
![image](https://github.com/user-attachments/assets/226b5b87-4b3f-4607-9787-582cd32b40f9)





#### Slack
The Slack UC was manually validated:
![image](https://github.com/user-attachments/assets/fac64c82-c9e4-403a-8d0d-787e23ba4d47)




#### Emotet
The Emotet UC was manually validated:

![image](https://github.com/user-attachments/assets/d4448f0f-fa9b-4023-b616-1fa823d25ad1)

**Comment by davidcr01** [comment]
### Deployment
The deployment succeeded: [JenkinsJob](https://ci.wazuh.info/job/Procedure_deploy_demo/485/console).

### UC Tests
All the automatic UC tests succeeded except for the VD one.
This test was manually validated:
![image](https://github.com/user-attachments/assets/226b5b87-4b3f-4607-9787-582cd32b40f9)





#### Slack
The Slack UC was manually validated:
![image](https://github.com/user-attachments/assets/fac64c82-c9e4-403a-8d0d-787e23ba4d47)




#### Emotet
The Emotet UC was manually validated:

![image](https://github.com/user-attachments/assets/d4448f0f-fa9b-4023-b616-1fa823d25ad1)


## Extra

I also have validated that the Yara use case passed correctly:
```
20:51:59  Executing Test: Yara
20:52:00  /usr/local/lib/python3.7/dist-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
20:52:00    "cipher": algorithms.TripleDES,
20:52:00  /usr/local/lib/python3.7/dist-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
20:52:00    "class": algorithms.TripleDES,
20:52:01  
20:52:01  PLAY [all, !windows, !windowsagents] *******************************************
20:52:01  
20:52:01  PLAY [localhost] ***************************************************************
20:52:02  
20:52:02  TASK [Gathering Facts] *********************************************************
20:52:02  ok: [localhost]
20:52:05  
20:52:05  TASK [Launching unit tests for use cases that imply queries to ES] *************
20:52:05  ok: [localhost]
20:52:06  
20:52:06  PLAY [windows] *****************************************************************
20:52:06  
20:52:06  PLAY RECAP *********************************************************************
20:52:06  XX.X.XXX.195              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.XXX.13             : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.XXX.151            : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.XXX.196              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.XX.54                : ok=0    changed=0    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0   
20:52:06  XX.X.XXX.200              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.XXX.101               : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.X.X.177                 : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.XXX.XXX.8               : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.XXX.XX.169              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.XXX.XXX.29              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.XXX.XXX.40              : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  XX.XX.XX.247               : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
20:52:06  localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
20:52:06  
```

**Comment by c-bordon** [comment]
LGTM
