### ISSUE TITLE
Decrease of Agent queries in Wazuh Master at VD performance test

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#25185]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | Wazuh component | Manager | Packages/Sources | OS version |

In VD performance test, while analyzing plots in https://github.com/wazuh/wazuh/issues/25140#issuecomment-2284057950 for Master at 4.9.0-beta2, it has been detected a decrease of `Agent queries` in the **Database queries count** table, in wazuhdbd plots, compared to previous versions:

### 4.9.0-Beta2
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/8c647db2-c61c-4c82-b8f5-af8fbea1f1a8)

### 4.9.0-Beta1
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/1a97cf19-9b56-46f2-8b3b-ebcda5d6e423)

### 4.8.1-RC2
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/wazuh/wazuh/assets/11089305/9f96cb23-2de8-40ee-9adc-c34cb5c88839)

Further investigation into the reason for this issue will be required.

**Comment by santipadilla** [comment]
Build in progress: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/626/

**Comment by santipadilla** [comment]
## Update

The error is consistent and is not related to any changes introduced in 4.9.0-beta2 in the CLUSTER-Workload_benchmarks_metrics pipeline.

Handled by the file located at:
jenkins-files/tests/performance/test_cluster.groovy

**Comment by jseg380** [comment]
Maybe it could be related to #25198(?)
LGTM
