### ISSUE TITLE
Too big message size from socket [25]

### ISSUE THREAD

**Issue by Sean-keep** [wazuh/wazuh#25194]
{"timestamp":"2024/08/13 17:42:02","tag":"wazuh-remoted","level":"warning","description":"Too big message size from socket [25]."}
{"timestamp":"2024/08/13 17:42:07","tag":"wazuh-remoted","level":"warning","description":"Unexpected message (hex): '6c6021ffffffff60ffff7effff5d0dff1fffffffff2250ff393affffff79ff09452225ffff2645ff0bff4affffff750affff2c56ffff37ff04ff3aff3f2f3affff26ffff434f33ff71ff7140ff1036ff30384affffffffffffff3f76ffffff07ff54ffffff2effff21ffff17ffffff4758291529ffffffffff0c693cff1b30ffffff30ffff6d3cffff79ff5a15ff3825ff4eff535fffff4d0d533effffffff005bff557154ffffff163754ffff372fff6aff27ff0cff637261ffff70ff2bffffffffffff0fffffff272eff48ffffff32ffff2014ffffff1d5dff151233ffffffff0e10ffff7610ffff2bff03787b372dffff307850257f4071ff7d7e5cff00ff7c174c370700ffffff61ff0778047f48ff09ff43ff51ff3effffff07ffff116f127c76ffffffffff1918690628742effffffffff52ffffff5d53ff612b08ffff12ffffff58ffff05016dff2fff64ff367d2bff6143ffffff4c7f5dffffffffff1b44ffffffff4e643cff01ff4d3755573bffff5b7b074f58410a0fff71ffff282fffffffff31ffffffff20ff021aff7a3d5056ff09ffffffff6bffffff62ff6effffffffffff3fff324270ff37ff6f31ffff6affffffff0c16ffffff4a77ffffff3d47ffff2f7639192d3155ff00ffffff3b62ff252d2845ffffff04ffff7408150f2c4158ffff277c59645cff4205ff23547d59ffff3b562a3cffffff30ff1fff4e0bffff184946ffffff7939ff4b3cffffff75ff11ff0e3a6fff605bff41ff18471f0628ffffffffffff53233e124fff09ff42ffff2aff655356ff08477a045b3aff28ff1fff4162ffff0affff0024293bff72ff5375ffffff00ff47ff370b0effff6fffffffffff5572ffffffffff684fffffffff240b441bffff38ffff6578ffff2b0fff5e56ff357c3c1fffffff12564d6020025eff6a007d07ffff1b1b31ffffff38ffff0fffff3708ffff4f05177cffffff68ff4bff5effff0f26ffffffffff38351114ff5cff6c6021ffffffff60ffff7effff5d0dff1fffffffff2250ff393affffff79ff09ff14ff32ffffffff2fffffff4cffffffff00ff1767ff68ff07ff7bff36ffff4a7221ffff0662ff6affffff19ff77ffffffff6f2d0effffffffffffffffff402f30ffff71ff67ffff457c2d013523ff04ff54ffff73ff56ff13ffffff78ff47ff11447bff3015ffffffff7b21ff6fffff462bff1026ff766d20ffff2affff6dff10ff60ff22ffffffffff37512e56ffff01597bffffffff15ff52ffff27ff601effffff7764ffff5cffff3a5862516cffff0158307aff1d79ffffff2e177e5e4f3aff14ffffffffff496d7604ffffff5f45ffff541a670cff39ff41ff7c1618453dffff33ff05ffffff1f2c16ffffff54ffffffffffff59ffffffff7a5aff6b0cff7530ffffff43ff50495e41ff0e3e3effff264c74ff'"}

**Comment by juliancnn** [comment]
Hi @Sean-keep,

A few days ago we merged the patch for this error here https://github.com/wazuh/wazuh/issues/25225.

Thanks for reporting it.

**Comment by JcabreraC** [comment]
As @juliancnn mentioned, the fix in the following PR (https://github.com/wazuh/wazuh/pull/25239) resolves  the error.

This has been merged into Wazuh version 4.8.2.
