### ISSUE TITLE
Wazuh server centralized logging

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25191]
|Epic|
|---|
| #25208 | 

# Description

This issue is intended to analyze, define, and develop the new centralized logging task to be added to the Wazuh cluster since this will be the principal daemon in the upcoming Wazuh server.

The Wazuh server will be initially composed of the following daemons:
- Cluster
- Engine
- Server Management API
- Comms API

The Wazuh cluster will be the first one to start, and then enabling the initialization of the rest of the daemons in the defined order, to be available to fetch the logs of the rest of the daemons.

# Requirements

## Functional requirements

- The logs must be able to be stored in a single file.
- The Logger task must implement a mechanism to rotate the logs by time and size.
- The Logger task must have defined a minimal configuration related to its basic settings.
- The log format must be standardized, the Logger task is not in charge of transforming the received logs.
- The Logger task must be able to receive logs from multiple sources and write them into the log file in the corresponding order.

## Non-functional requirements

- The Logger task must not negatively affect the performance of the other functions performed by the cluster.

## Implementation restrictions (TBD)

# Plan

- [x] #25231

**Comment by GGP1** [comment]
## Update

Based on the [decision](https://github.com/wazuh/wazuh/issues/25231#issuecomment-2304868878) we have taken for the logging, we consider there's no much work required for this issue.

The only thing to have in mind during the development is that we should be able to capture the `wazuh-server` subprocesses standard streams to be able to redirect the logs to files, remote hosts, etc.

This functional requirement has been added to the issue https://github.com/wazuh/wazuh/issues/7108 where the `wazuh-server` daemon will be developed. This issue may now be closed after the spike is considered done.

**Comment by fdalmaup** [comment]
# Review

The requirement related to how the processes will log has already been added to the parent issue and no new Logging task is required in the Wazuh Server.

LGTM!
