### ISSUE TITLE
Wazuh server centralized configuration and distribution

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25193]
|Epic|
|---|
| #25208 | 

# Description

As part of the development of the Wazuh server as a cluster by default, it was decided that as the main daemon, and being able to communicate with the rest of the Wazuh server nodes, it would be in charge of distributing the upcoming server's centralized configuration.

This issue aims to study, define, design, and implement the necessary developments to carry out the Configurator task.

# Requirements

## Functional requirements

- The configuration must be defined in a single file.
- The configuration must be centralized in the Wazuh server master node.
- The Wazuh server worker node base configuration must include the minimum deployment configuration to communicate with the master node.
- The configuration file template must include the basic necessary configurations to have a functional Wazuh server node.
- The configuration file must not include every available option. 
- At the setup phase of any newly added Wazuh server node, the Configurator task must be able to respond to configuration pull requests. 
- During the stable phase, the Configurator task must be able to push new configuration changes (**hot changes**).
- The configuration must only be persisted in the master node. The workers must only have the required deployment configuration required to connect to the master node.

## Non-functional requirements

- The Configurator task must not significantly impact the performance of the other functions performed by the cluster.
- The Configurator task must reliably validate and apply configurations without causing errors or downtime.

## Implementation restrictions

- **Configuration Format:**
The configuration will be in YAML format.
- **Validation**:
The configuration must be validated before application. The Wazuh server should never accept a configuration that produces errors.

# Plan

1. **Current configuration management**:
   Review the current configuration module used by the cluster. Define the necessary changes that it would require.
   Teams involved: @wazuh/devel-cppserver @wazuh/devel-pyserver 
   **Spikes:**
      CppServer -> #25472
      PyServer -> #25595, #25702
   
2. **Configuration options**
   Define the minimum required configuration for the deployment of a Wazuh Server node. 
   Server Node: #25697 
   Teams involved: @wazuh/devel-pyserver 
3. **Configuration persistence**
   Develop the necessary code to persist the configuration in a master node.
   Server Node: https://github.com/wazuh/wazuh/issues/26356
   Teams involved: @wazuh/devel-pyserver 
4. **Configuration pulling**
   Develop the necessary mechanisms to make the configuration pulling available from any newly connected node and service initializing. 
   Engine: #25618
   PyServer:
       - First iteration: #26954
   Teams involved: @wazuh/devel-cppserver @wazuh/devel-pyserver 
5. **Configuration hot changes** 
   Develop the mechanism to push new configuration changes to worker nodes.
   Engine: #25624
   Teams involved: @wazuh/devel-cppserver

**Comment by RamosFe** [comment]
## Update

I start reviewing the actual configuration.

**Comment by RamosFe** [comment]
The follwing Issue was added [Review current configuration management #25595](https://github.com/wazuh/wazuh/issues/25595).
