### ISSUE TITLE
Footprint - modulesd decreased on all various manager plots

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25198]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-Beta2 | Wazuh component | Manager | Packages | CentOS |

Testing [Release 4.9.0 - Beta 2 - Footprint Metrics - VULNERABILITY-DETECTOR-REGISTER (2.5d) #](https://github.com/wazuh/wazuh/issues/25158), modulesd decreased on all various manager plots

- CPU: Absence of modulesd peaks at the start of the test
- Disk: relevant decrease of modulesd, now follows the pattern of wazuhdb and wazuh-authd
- Disk_Read: Large drop in modules with a more staggered ascending pattern until reaching a valley
- Disk_Written: relevant decrease of modulesd, now follows the pattern of wazuhdb and wazuh-authd
- FD: decrease of modulesd
- PSS, RSS y USS : decrease of modulesd
- Read_Ops: decrease of modulesd
- VMS: decrease of modulesd

[v4.9.0-Beta2](https://github.com/wazuh/wazuh/issues/25158)
<details>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/monitor-manager-Test_stress_B5499_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5499-3600m/B5499_manager_centos/plots/Test_stress_B5499_manager_analysisd_events_Dropped_events.png)
</details>

[v4.8.1-RC2](https://github.com/wazuh/wazuh/issues/24471)
<details>

![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5394-3600m/B5394_manager_centos/plots/monitor-manager-Test_stress_B5394_manager_analysisd_events_Dropped_events.png)

</details>

The reason for the fall and whether it is expected should be analyzed.

**Comment by sebasfalcone** [comment]
## RCA
The only correlation I see (with the reduced information the logs provide) is that the VD content used in 4.9.0 has the latest offset. 

> [!NOTE]
> The upgrade via offsets is a costly operation (in FD, disk_read, disk_write, CPU, etc)

Packages were [created on Friday3](https://wazuh-team.slack.com/archives/C02A737S5MJ/p1723219573945439?thread_ts=1723185320.615229&cid=C02A737S5MJ) and the [generated content](https://github.com/wazuh/wazuh/actions/runs/10311575596/job/28545413669) already contained the latest offset to this date (**851035**)


![Image](https://github.com/user-attachments/assets/eb61e6e6-6168-43bd-8f3a-1fd5913d8661)

**Comment by Dwordcito** [comment]
LGTM, valid reason.
