### ISSUE TITLE
Wazuh cluster enhancement and new features

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25208]
| Objective |
|---|
| #22887 |

# Description

Along with the upcoming changes for Wazuh v5.0, we need to enhance the current tasks and features of the Wazuh cluster, to be able to handle the following responsibilities:
- Make Wazuh server installations a cluster by default
- Centralized logging of every daemon running in the Wazuh server.
- Distribution of the Wazuh configuration options and templates to other Wazuh server nodes.

## Wazuh server daemons

```mermaid
flowchart TD

subgraph wazuh-server
    subgraph Configurator
    end
    subgraph Process Control
    end
end

subgraph Engine
end

subgraph Api["Server Managment API"]
end

subgraph Ca["Comms API"]
end

Api --> Engine
Ca --> Engine
Engine --> wazuh-server
Api --> wazuh-server
Ca --> wazuh-server
wazuh-server --> Engine
wazuh-server --> Ca
wazuh-server --> Api
```

The proposed initialization order is:
1. `wazuh-server`: initializes the Configuration task, loading its default configuration. It starts the rest of the daemons in order via the Process Control task.
2. `Engine`
3. `Server Management API`
4. `Comms API`

At the setup phase of a newly added node, this will pull the configuration from the master node. During the stable phase, the latter may push new configuration changes.

# Requirements

## Functional requirements

- `wazuh-server` must be always running and will be the principal daemon of the Wazuh Server, initializing first before any other daemon that it will start via the Process Control task.
- `wazuh-server` must be able to log the activity of every running process in the Wazuh Server: Engine, Server Management API, and Comms API.
- `wazuh-server` must be able to distribute the configuration to other Wazuh server nodes.

## Non-functional requirements

- The `wazuh-server` process must follow industry security standards to avoid any possible risks.
- `wazuh-server` must be bounded at `localhost:1516` by default for security reasons. Currently, it is bonded at `0.0.0.0:1516` by default.

## Implementation restrictions

- The new tasks will be developed in Python.
- The daemons socket protocol must be HTTP following a common nomenclature.

# Plan

- [x] #7108 
- [x] #25193
- [x] #25191

**Comment by GGP1** [comment]
## Update

I've listed all the cluster tasks and threads, marking whether they should be kept/removed in the new design. 

This could be part of the [legacy removal](https://github.com/wazuh/wazuh/issues/22888) objective but I decided to include it here, where most of the cluster changes will be tracked.

### Cluster tasks

| Task | Description | Status |
| --- | --- | --- |
| Integrity-check | Calculates the hash of all the files to be synchronized | ❌ |
| Integrity-sync | Synchronizes agent, groups, rules, decoders, CDB lists and other files | ❌ |
| Agent-info sync | Synchronizes the agents' last keepalives and operating system information | ❌ |
| Agent-groups send | Synchronizes new agent groups assignments | ❌ |
| Agent-groups send full | Synchronizes all agents groups information | ❌ |

### Cluster threads

| Name | Node | Description | Status |
| --- | --- | --- |  --- |
| Keep alive - send to master | Worker | Used to consider a node as disconnected from the cluster | ✔️ |
| Integrity sync | Worker | Integrity information synchronization between master and worker nodes | ❌ |
| Agent info sync | Worker | Synchronize agent last keepalives and operating system information | ❌ |
| Keep alive - check workers | Master | Used to consider a node as disconnected from the cluster | ✔️ |
| Agent groups send | Master | Synchronize agent groups information | ❌ |
| Local agent-groups | Master | Periodically asks information about the agent groups to wazuh-db | ❌ |
| Local integrity | Master | Periodically reads all its integrity files and calculates their checksums | ❌ |
| Sendsync | Master | Allows redirection of messages coming from worker nodes to master services | ❌ |
| DAPI | Both | It's used to receive API requests and forward them to the most suitable node to process the request | ✔️ |

#### Legend

|Symbol|Meaning|
|:-:|--|
| ✔️ | Keep |
| ❌ | Remove |
| | Currently N/A |

> [!Note]
> The binary `cluster_control` will also be removed.

**Comment by GGP1** [comment]
## Update

I've listed all the cluster tasks and threads, marking whether they should be kept/removed in the new design. 

This could be part of the [legacy removal](https://github.com/wazuh/wazuh/issues/22888) objective but I decided to include it here, where most of the cluster changes will be tracked.

### Cluster tasks

| Task | Description | Status |
| --- | --- | --- |
| Integrity-check | Calculates the hash of all the files to be synchronized | ❌ |
| Integrity-sync | Synchronizes agent, groups, rules, decoders, CDB lists and other files | ❌ |
| Agent-info sync | Synchronizes the agents' last keepalives and operating system information | ❌ |
| Agent-groups send | Synchronizes new agent groups assignments | ❌ |
| Agent-groups send full | Synchronizes all agents groups information | ❌ |

> [!Note]
> We will need to synchronize the JWT tokens signing key on each new connected node, but it should be done only once and not as a periodic task.

### Cluster threads

| Name | Node | Description | Status |
| --- | --- | --- |  --- |
| Keep alive - send to master | Worker | Used to consider a node as disconnected from the cluster | ✔️ |
| Integrity sync | Worker | Integrity information synchronization between master and worker nodes | ❌ |
| Agent info sync | Worker | Synchronize agent last keepalives and operating system information | ❌ |
| Keep alive - check workers | Master | Used to consider a node as disconnected from the cluster | ✔️ |
| Agent groups send | Master | Synchronize agent groups information | ❌ |
| Local agent-groups | Master | Periodically asks information about the agent groups to wazuh-db | ❌ |
| Local integrity | Master | Periodically reads all its integrity files and calculates their checksums | ❌ |
| Sendsync | Master | Allows redirection of messages coming from worker nodes to master services | ❌ |
| DAPI | Both | It's used to receive API requests and forward them to the most suitable node to process the request | ✔️ |

#### Legend

|Symbol|Meaning|
|:-:|--|
| ✔️ | Keep |
| ❌ | Remove |
| | Currently N/A |

> [!Note]
> The binary `cluster_control` will also be removed.
