### ISSUE TITLE
Significant decrease in wazuh-modulesd Disk_Read during VD performance tests on master

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25203]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | wazuh-modulesd | Manager | Packages | OS version |

While analyzing the results of the **VD performance test** in https://github.com/wazuh/wazuh/issues/25140, a suspicious behavior was discovered in the **master**, specifically in `wazuh-modulesd` in **Disk_Read**. Although it was expected that wazuh-modulesd usage would decrease, such a significant drop compared to previous versions was not expected.

### 4.9.0-beta2
![Disk_Read](https://github.com/user-attachments/assets/a4f1b36b-5c0f-44b4-b567-b6add5baaab4)

### 4.8.1-RC2
![Disk_Read-4 8 1](https://github.com/user-attachments/assets/4b344320-5611-490f-a2ab-ca23351d8db6)

**Analyze this behavior and determine if it is expected.**

**Comment by juliamagan** [comment]
Could it be related to https://github.com/wazuh/wazuh/issues/25198?

**Comment by jseg380** [comment]
## Analysis

As @juliamagan mentioned in [the comment](https://github.com/wazuh/wazuh/issues/25203#issuecomment-2288168818):
> Could it be related to `#25198`?

<br/>

It indeed seems to be related to #25198, no errors seemingly related to this event were found in the logs and artifacts of the build  ([original comment](https://github.com/wazuh/wazuh/issues/25140#issuecomment-2284128568)). As the previously mentioned issue shows, the GitHub Actions logs seem to be correct. As can be seen in the image, no errors are shown and there is no time discrepancy between the start and the end of the offset update.

![image](https://github.com/user-attachments/assets/4bbaedc2-0eb4-4d72-b927-d5af37042420)
 
It seems safe to say that wazuh-modulesd is working correctly and there are no errors.

**Comment by santipadilla** [comment]
LGTM
