### ISSUE TITLE
Solve technical debt after updating coverage calculation approach

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#25207]
## Description

After analyzing the coverage calculation approach at #24944, it was found that some modules need more UT because some files weren't included at all or some percentages weren't accurate.

This is also a good moment to remove some LCOV exclusion blocks and TODOs.

## DoD

For each affected module (router, content_manager, vulnerability_scanner, indexer_connector)

- [ ] Remove all LCOV exclusions and TODOs
- [ ] Implement missing UT to take the coverage again to an acceptable level
- [ ] Enable the coverage check (temporarily disabled)

**Comment by Dwordcito** [comment]
Not planned, some modules will be removed in 5.0 based on the new architecture.
