### ISSUE TITLE
High decrease of agent-get-agent-info in Wazuh Master at VD performance test

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#25204]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | Wazuh component | Manager | Packages/Sources | OS version |

In VD performance test, while analyzing plots in https://github.com/wazuh/wazuh/issues/25140#issuecomment-2284057950 for Master at 4.9.0-beta2, it has been detected a high decrease of `agent-get-agent-info` in the **Global agent queries** table, in wazuhdbd plots, compared to previous versions:

### 4.9.0-Beta2
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/228eadbe-2b92-498f-803f-4c0f5d7a0468)

### 4.9.0-Beta1
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/edd88d8c-f9a6-4420-8865-bbbb64ccf2aa)

### 4.8.1-RC2
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/wazuh/wazuh/assets/11089305/d0cf4f2d-0bee-4d8b-89c9-bf352dd50357)

Further investigation into the reason for this issue will be required.

**Comment by Rebits** [comment]
Related to https://github.com/wazuh/wazuh/issues/25220
Analysis performed in https://github.com/wazuh/wazuh/issues/25220#issuecomment-2294193683. There is no clear conclusion for this issue https://github.com/wazuh/wazuh/issues/25220#issuecomment-2296034582. We will check these values in future iterations.

**Comment by rafabailon** [comment]
### Investigation

I've been looking through the Artifacts logs. I've found some bugs, but they are known and shouldn't affect the graphics. I've also reviewed the code and the changes introduced in this version, and it doesn't seem like there's anything that could affect it.

I've been able to find another issue where this same error is discussed. It was decided to wait for the next tests to see if the results are consistent [#25215 (Comment #2292642404)](https://github.com/wazuh/wazuh/issues/25215#issuecomment-2292642404).

In the last comment of the issue, the results of 4.8.0-RC4 are also compared and are similar to those obtained in 4.9.0 [#25215 (#2293441935)](https://github.com/wazuh/wazuh/issues/25215#issuecomment-2293441935).

**Comment by MARCOSD4** [comment]
LGTM

**Comment by Rebits** [comment]
LGTM
