### ISSUE TITLE
Vulnerability Detector - Investigate behaviour in 4.9.0

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#25217]
## Description
It was discovered, in the 4.9.0 demo environment, the following behaviour:
- An alert is generated, informing a vulnerable package
- An alert is generated, informing the package is no longer vulnerable

This happens in a short period and without making changes to the packages, so we need to investigate it 

## DoD
- [x] Root Cause determined

**Comment by sebasfalcone** [comment]
## Analysis

We have two alerts:
- New vulnerability for package 'linux-image-cloud-amd64'
- Vulnerability solved for package 'linux-image-cloud-amd64


### Active vulnerability
```json
{
    "condition": "Package default status",
    "name": "linux-image-cloud-amd64",
    "source": "linux-signed-amd64 (5.10.223+1)",
    "version": "5.10.223-1",
    "architecture": "amd64"
},
"timestamp":
[
    "2024-08-14T07:35:16.324Z"
]
```

### Solved vulnerability
```json
{
    "name": "linux-image-cloud-amd64",
    "version": "5.10.221-1",
    "architecture": "amd64"
},
"timestamp":
[
    "2024-08-14T07:35:32.283Z"
]
```

### Debian agent
We can go into the debian agent and see the package history:

```bash
root@ip-10-0-1-74:/usr/bin# cat /var/log/apt/history.log | grep "linux-image-cloud-amd64" -B3 -A2

Start-Date: 2024-08-10  06:26:39
Commandline: /usr/bin/unattended-upgrade
Install: linux-image-5.10.0-31-cloud-amd64:amd64 (5.10.221-1, automatic), firmware-linux-free:amd64 (20200122-1, automatic)
Upgrade: linux-image-cloud-amd64:amd64 (5.10.113-1, 5.10.221-1)
End-Date: 2024-08-10  06:26:54

Start-Date: 2024-08-14  06:46:04
Commandline: /usr/bin/unattended-upgrade
Install: linux-image-5.10.0-32-cloud-amd64:amd64 (5.10.223-1, automatic)
Upgrade: linux-image-cloud-amd64:amd64 (5.10.221-1, 5.10.223-1)
End-Date: 2024-08-14  06:46:13
```

```bash
root@ip-10-0-1-74:/var/ossec/logs# cat /var/log/dpkg.log | grep "linux-image-5.10.0-32-cloud-amd64"
2024-08-14 06:46:04 install linux-image-5.10.0-32-cloud-amd64:amd64 <none> 5.10.223-1
2024-08-14 06:46:04 status half-installed linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1
2024-08-14 06:46:07 status unpacked linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1
2024-08-14 06:46:07 configure linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1 <none>
2024-08-14 06:46:07 status unpacked linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1
2024-08-14 06:46:07 status half-configured linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1
2024-08-14 06:46:13 status installed linux-image-5.10.0-32-cloud-amd64:amd64 5.10.223-1
```

### Debian feed
Debian considers this package as affected by default, no matter the version:
```json
{
    "defaultStatus": "affected",
    "platforms":
    [
        "bookworm",
        "bullseye"
    ],
    "product": "linux-image-cloud-amd64",
    "vendor": "debian"
}
```

I am still not sure about the time difference between the alerts generation and the package upgrade

**Comment by sebasfalcone** [comment]
## Conclusion
This behaviour is expected due to how syscollector reports package modifications. Because the version is part of the primary key of the syscollector table, a package upgrade is detected as:
- A package removal
- A package insert

If the syscollector events appear in the inverse order (insert - remove), we are going to see this exhibit behaviour (an alert that appears and disappears)

**Comment by Dwordcito** [comment]
LGTM.
