### ISSUE TITLE
Decrease in database queries by the agent

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#25215]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2 | Agent | Agent | Packages | Debian 10 |

## Description

Drastic reduction of database agent queries in version 4.9.0-beta2. The error is consistent and is not related to any changes introduced in 4.9.0-beta2 in the CLUSTER-Workload_benchmarks_metrics pipeline. Handled by the file located at: jenkins-files/tests/performance/test_cluster.groovy

This behavior has not occurred in earlier stages of 4.9.0 or 4.8. It has appeared in 4.9.0-beta2.

Detected in vulnerability detection performance tests, analyzed in [this issue](https://github.com/wazuh/wazuh/issues/25140).

### 4.9.0-Beta2
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/8c647db2-c61c-4c82-b8f5-af8fbea1f1a8)

### 4.9.0-Beta1
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/1a97cf19-9b56-46f2-8b3b-ebcda5d6e423)

### 4.8.1-RC2
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/wazuh/wazuh/assets/11089305/9f96cb23-2de8-40ee-9adc-c34cb5c88839)

## Test case

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |

## Evidences

- https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/618/
  - [artifacts.zip](https://github.com/user-attachments/files/16613118/artifacts.zip)
- https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/626/
  - [artifacts-1.zip](https://github.com/user-attachments/files/16613121/artifacts-1.zip)
- https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/629/
  - [artifacts-2.zip](https://github.com/user-attachments/files/16613124/artifacts-2.zip)

**Comment by sebasfalcone** [comment]
## Investigation

## [4.9.0 Beta2 vs 4.9.0 Beta1](https://github.com/wazuh/wazuh/compare/v4.9.0-beta1...v4.9.0-beta2)
- No functional changes

## [4.9.0 Beta1 vs 4.9.0 alpha3](https://github.com/wazuh/wazuh/compare/v4.9.0-alpha3...v4.9.0-beta1)
- Fixed code-smell in the Wazuh DB connect function (no functional change)
![image](https://github.com/user-attachments/assets/7865c035-1ba6-4a6c-8744-77efe73a54b4)

### [4.9.0 alpha3 vs 4.9.0 alpha2](https://github.com/wazuh/wazuh/compare/v4.9.0-alpha3...v4.9.0-alpha2)
- No changes

### [4.9.0 alpha2 vs 4.9.0 alpha1](https://github.com/wazuh/wazuh/compare/v4.9.0-alpha3...v4.9.0-alpha2)
- No changes

### [4.9.0 alpha2 vs 4.9.0 alpha1](https://github.com/wazuh/wazuh/compare/v4.9.0-alpha2...v4.9.0-alpha1)
-

**Comment by Dwordcito** [comment]
LGTM, We will wait for the next tests to see if these results are consistent or if it is a failure in the test. We found no recent changes such as in related modules that could cause this.

**Comment by sebasfalcone** [comment]
## Important update
I've checked the graphs in 4.8.0 RC4, which look like the ones in 4.9.0
![image](https://github.com/user-attachments/assets/1c1a44d9-498c-4014-9618-80a8e00f7f91)
