### ISSUE TITLE
SPIKE - Investigate best cybersecurity practices regarding certificates, passwords, and credentials

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25228]
# Description

As part of the Wazuh cluster enhancement in #7108, we need to define the mechanism to handle encryption keys to be used in the cluster communication. This issue aims to research, document, and help define the best practices to be implemented in the cluster regarding certificates, passwords, or credential files in encrypted communications.

# Plan

- [x] Research on best and industry standard cybersecurity practices for encrypted communications.
- [x] Define the pros and cons of each alternative and the development challenges that each one may present.
- [x] Conclude the investigation by defining and explaining the solution that best suits the cluster encrypted communications.

**Comment by GGP1** [comment]
## Update

I've been reviewing the work that has been done to make the `wazuh-server` a cluster by default and researching the best alternatives to encrypt the communication between the cluster nodes.

**Comment by GGP1** [comment]
## Update

I've been reviewing the current implementation, its limitations and drafting a proposed new solution that is more secure, efficient and easier to use. 

### Current scheme

By default, the data is encrypted using a 32-byte pre-shared [Fernet key](https://cryptography.io/en/latest/fernet/) that users generate during the installation and set on every node's configuration.

Fernet is built on top of a number of standard cryptographic primitives. Specifically it uses:

- AES in CBC mode with a 128-bit key for encryption; using PKCS7 padding.
- HMAC using SHA256 for authentication.
- Initialization vectors are generated using os.urandom().

> Specification: https://github.com/fernet/spec/blob/master/Spec.md

The caveats of this mechanism are:

- Only part of the payload is encrypted (the actual data); the header format, message IDs and commands are not.
- All nodes have the same key and there's no rotation, the same key is used for absolutely all the cluster's life communications. If one node is compromised, the communication between all the nodes from the cluster is available for the attacker.
- Using 128 bits is a bit outdated. It's not exactly insecure yet and should be fine for at least another decade, but 256 is recommended on new designs.
- CBC-encrypted ciphertexts are vulnerable to the [padding oracle attack](https://en.wikipedia.org/wiki/Padding_oracle_attack), where an attacker can obtain the plaintext by recording which inputs have a valid padding and which don't. 

### Proposal

Our current code already contemplates using SSL for the TCP connection between the nodes, but the option is disabled by default and does not take part of the configuration. Therefore, unless the scipt is executed manually with the flag `--ssl`, the connection won't be encrypted.

In the new implementation, we should remove the Fernet key and always use TLS (preferrably >=1.3), moving the encryption from the cluster logic to between the transport and application layers.

> [!Note]
> TLS 1.3 only supports the more efficient and secure authenticated ciphers. It also removes optional data compression, a feature that enabled the [CRIME attack](https://en.wikipedia.org/wiki/CRIME) on version 1.2. Furthermore, it brings new features that make the connections more secure and efficient: downgrade protection, single round-trip handshakes and session resumption.

We should generate new certificates for each node signed by the root CA during the installation, like we do to encrypt the communication with the other Wazuh components. 

> [!Note]
> For the key pair type choice, it may be appropiate to change the key length used to 3072 or 4096, or even using the [Elliptic Curve Digital Signature Algorithm](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm). Currently, the generation is done with 2048-bit RSA keys, which provide an acceptable security until 2030, as per NIST.

This way, the nodes will use the counterpart public key to securely exchange the session key that will be used to encrypt the rest of the communication, offering us data encryption, data integrity and authentication.

### Passwords

As far as passwords are concerned, I would suggest using a minimum of 100 bits of entropy. 

> Entropy is a measure of the uncertainty of a system and its formula is `log2(keyspace)`. Keyspace is the set of all possible permutations of a key, calculated doing `pool_length ^ secret_length`.

That is, passwords should have a length between 16 and 32 characters, using lowercase, uppercase and digits (optionally symbols). The sweet spot may be 24, a balance between space and security.

For example a password with ~100 bits of entropy (17 characters) would take 47 million millenniums to crack with a current specialized computer:

```console
gasti@gasti:~/work/wazuh$ kure gen -l 17 -L 1,2,3
Password: SrcYGaAR5glOxdMQT

Entropy: 101.22 bits
Keyspace: 2,955,688,905.82 sextillion
Average time taken to crack: 47,513,003.24 millenniums
```

and one with 24 characters has ~142 bits of entropy and takes even longer:

```console
gasti@gasti:~/work/wazuh$ kure gen -l 24 -L 1,2,3
Password: DRpQs9fSxJzWjXFyCPq1c6eN

Entropy: 142.90 bits
Keyspace: 10,408,797,222,153,477,947,392.00 sextillion
Average time taken to crack: 167,322,486,210,028,863,488.00 millenniums
```

> Results calculated using my CLI password manager (assumes 1 trillion tries per second): https://github.com/GGP1/kure

**Comment by GGP1** [comment]
## Update

I've been reviewing the current implementation, its limitations and drafting a proposed new solution that is more secure, efficient and easier to use. 

### Current scheme

By default, the data is encrypted using a 32-byte pre-shared [Fernet key](https://cryptography.io/en/latest/fernet/) that users generate during the installation and set on every node's configuration.

Fernet is built on top of a number of standard cryptographic primitives. Specifically it uses:

- AES in CBC mode with a 128-bit key for encryption; using PKCS7 padding.
- HMAC using SHA256 for authentication.
- Initialization vectors are generated using os.urandom().

> Specification: https://github.com/fernet/spec/blob/master/Spec.md

The caveats of this mechanism are:

- Only part of the payload is encrypted (the actual data); the header format, message IDs and commands are not.
- All nodes have the same key and there's no rotation, the same key is used for absolutely all the cluster's life communications. If one node is compromised, the communication between all the nodes from the cluster is available for the attacker.
- Using 128 bits is a bit outdated. It's not exactly insecure yet and should be fine for at least another decade, but 256 is recommended on new designs.
- CBC-encrypted ciphertexts are vulnerable to the [padding oracle attack](https://en.wikipedia.org/wiki/Padding_oracle_attack), where an attacker can obtain the plaintext by recording which inputs have a valid padding and which don't. 

### Proposal

Our current code already contemplates using SSL for the TCP connection between the nodes, but the option is disabled by default and does not take part of the configuration. Therefore, unless the scipt is executed manually with the flag `--ssl`, the connection won't be encrypted.

In the new implementation, we should remove the Fernet key and always use TLS (preferrably >=1.3), moving the encryption from the cluster logic to between the transport and application layers.

> [!Note]
> TLS 1.3 only supports the more efficient and secure authenticated ciphers. It also removes optional data compression, a feature that enabled the [CRIME attack](https://en.wikipedia.org/wiki/CRIME) on version 1.2. Furthermore, it brings new features that make the connections more secure and efficient: downgrade protection, single round-trip handshakes and session resumption.

We should generate new certificates for each node signed by the root CA during the installation, like we do to encrypt the communication with the other Wazuh components. 

> [!Note]
> For the key pair type choice, it may be appropiate to change the key length used to 3072 or 4096, or even using the [Elliptic Curve Digital Signature Algorithm](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm). Currently, the generation is done with 2048-bit RSA keys, which provide an acceptable security until 2030, as per NIST.

This way, the nodes will use the counterpart public key to securely exchange the session key that will be used to encrypt the rest of the communication, offering us data encryption, data integrity and authentication.

### Passwords

As far as passwords are concerned, I would suggest using a minimum of 100 bits of entropy. 

> Entropy is a measure of the uncertainty of a system and its formula is `log2(keyspace)`. Keyspace is the set of all possible permutations of a key, calculated doing `pool_length ^ secret_length`.

That is, passwords should have a length between 16 and 32 characters, using lowercase, uppercase and digits (optionally symbols). The sweet spot may be 24, a balance between space and security.

For example a password with ~100 bits of entropy (17 characters) would take 47 million millenniums to crack with a current specialized computer:

```console
gasti@gasti:~/work/wazuh$ kure gen -l 17 -L 1,2,3
Password: SrcYGaAR5glOxdMQT

Entropy: 101.22 bits
Keyspace: 2,955,688,905.82 sextillion
Average time taken to crack: 47,513,003.24 millenniums
```

and one with 24 characters has ~142 bits of entropy and takes even longer:

```console
gasti@gasti:~/work/wazuh$ kure gen -l 24 -L 1,2,3
Password: DRpQs9fSxJzWjXFyCPq1c6eN

Entropy: 142.90 bits
Keyspace: 10,408,797,222,153,477,947,392.00 sextillion
Average time taken to crack: 167,322,486,210,028,863,488.00 millenniums
```

> The results were obtained using my CLI password manager (assumes 1 trillion tries per second): https://github.com/GGP1/kure

**Comment by nico-stefani** [comment]
# Review

The analysis was conclusive and deep. It exposed the cluster's current state and provided a replacement mechanism based on the latest industry trends. LGTM!

**Comment by fdalmaup** [comment]
# Review

Every item from the plan has been correctly carried out leaving the following proposals:
- Use TLS >=1.3 for cluster communication.
- Generate new certificates/key pairs for each node signed by the same root CA.
- Use ECDSA for key pair generation, already used for signing the Comms API JWTs (check https://github.com/wazuh/wazuh/issues/24618 for more information).
- Passwords of 24 characters using lowercase, uppercase, and digits (optionally symbols).

LGTM!
