### ISSUE TITLE
Inconsistent results in Dashboard Vulnerability Detection performance tests

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#25221]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta2| Wazuh Dashboard | Manager | Packages/Sources | OS version |

While analyzing the results of the **Very High Activity** in **VD performance test** (https://github.com/wazuh/wazuh/issues/25140#issuecomment-2286616771), it is found that the Dashboard CPU plot appears incorrect or inconsistent.

In the rest of the plots, you can see that the dashboard was not working or went silent. There are no errors detected in the logs that refer to this.

### 4.9.0-Beta2

![CPU](https://github.com/user-attachments/assets/1bf8e5b8-7409-4fb4-96a2-a8c1096738d2)

### 4.8.1-RC2

![CPU](https://github.com/user-attachments/assets/8ec67cc2-0f4c-4cb4-b38c-bc726c6dbf91)

More research is required.

**Comment by rauldpm** [comment]
Actually, the 4.9.0 plot is similar to 4.8.1, it is just that in some specific moments, the CPU has more usage (two continuous spikes of ~14% and two 4% spikes)

This could have been produced by a system load or a punctual process, as those % values are small, I do not think this is a problem and it could be an expected usage
