### ISSUE TITLE
ERROR3099 - Wazuh not ready yet | wazuh-manager issues

### ISSUE THREAD

**Issue by djedcurtis** [wazuh/wazuh#25234]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.3-2 | Wazuh API | Manager | Packages | Ubuntu 22.04.4 |

Roughly a week ago the device running Wazuh ran out of storage space due to inadequate log space.
This has now been remedied, and should no longer be an issue.

However after restarting all Wazuh processes, I'm continuously getting the following error on the dashboard: 
`[API connection] No API available to connect`
paired with `3099 - ERROR3099 - Wazuh not ready yet`
![image](https://github.com/user-attachments/assets/1723c411-3375-4d23-82c0-853a16cac609)

When checking **ossec.log**, the below warnings & error are seen:
![image](https://github.com/user-attachments/assets/72bb3a1c-2209-4f8b-8224-01e03ad570c9)

When running `systemctl status wazuh-dashboard`, `systemctl status wazuh-indexer`, and `systemctl status wazuh-manager`, I get the following outputs respectively.
![image](https://github.com/user-attachments/assets/85fded7f-9292-4128-b09a-3cd92065e400)
![image](https://github.com/user-attachments/assets/7ab89cfd-8efd-4086-9c36-b11102696b8d)
![image](https://github.com/user-attachments/assets/f6577fe9-38dc-4024-b6d8-8b98d93fa9f5)

So the issue looks to be with wazuh-manager. I was able to find that for some bizarre reason my **ossec.conf** file was empty, despite it not being changed since original setup.

After using a (what seems to be) backup of the **ossec.conf** file, I received the follow errors.
![image](https://github.com/user-attachments/assets/b3030d18-9c2f-44fb-a743-d9b437c54f57)

I commented out the **ca_verification** field for the moment, and am right back where I started, with the output (after restarting) being seen below.
![image](https://github.com/user-attachments/assets/2dd52db5-b834-4d4b-a114-b4a67ed9e217)

I'm not well-versed with Wazuh, so it's possible I've broken something, but am not sure what could possibly be causing this?
Any assistance would be appreciated greatly :)

**Comment by djedcurtis** [comment]
In reference to the last screenshot errors:
`etc/lists/audit-keys` permissions are (what I believe to be) correct.
![image](https://github.com/user-attachments/assets/46f4482d-455a-4fa1-99a4-0e52bed2e0cc)

**Comment by djedcurtis** [comment]
Just a little update with info that has been asked on prior threads regarding Wazuh issues.
- No recent changes have been made to Wazuh
- Issues first occurred about a week ago, however those issues were traced down to storage problems as the partition logs were located on was filled to 98%.
- After a new drive was installed, and the ossec/logs dir content was moved onto the new drive with a mount binding between the two, this issue started occurring

If any other information is needed, please let me know :)

**Comment by MiguelazoDS** [comment]
Hi @djedcurtis 

The error is because this configuration block is missing for remote communication. Please check that this comment exists and it is not commented.  

```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>
 ```

**Comment by djedcurtis** [comment]
Hi @MiguelazoDS

Thank you for your response, and I apologise for my delayed response.

I've added the remote communication block into my ossec.conf file, just above the policy monitoring segment.
This seems to be starting the wazuh-manager service now, however I'm getting errors on the UI displaying the following:

![image](https://github.com/user-attachments/assets/b13cd054-976d-4e9c-9379-897a070d809b)
![image](https://github.com/user-attachments/assets/6a0deb8b-59a6-4807-ba62-6d55ecbd3e81)

I've done a bit of research on these errors and the follow log file output may be useful in diagnosing the cause of this.
Output of `grep -i -E "error|warn" /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log`
```
{"data":{"dapi_errors":{"node01":{"error":"Error connecting with socket: Socket 'auth' cannot receive connections","logfile":"WAZUH_HOME/logs/api.log"}},"detail":"Error connecting with socket: Socket 'auth' cannot receive connections","error":1121,"remediation":"Please ensure the selected module is running and properly configured","title":"Wazuh Internal Error"},"date":"2024-08-20T00:07:00.244Z","level":"error","location":"wazuh-api:makeRequest"}
```
My `api.log` file doesn't have any logs from today, or seemingly since this entire issue occurred, so sharing that isn't of much use.
It looks to me like the api may be down? But I'm not sure, any assistance or advice would be greatly appreciated.
I'll keep looking into it from my end and will put any updates on this thread.

Again, thank you for your response and assistance :)

**Comment by djedcurtis** [comment]
After looking through the UI a bit, most areas seem to be working.

I am however unable to add a new agent, I've done the usual steps of installing the agent on the device (Windows).
The service installation was successful, and it is running, but the agent is not appearing on the UI.
I assume this is related to the error above somehow.

Some error logs when the request fails via the UI are shown below:

`response`
![image](https://github.com/user-attachments/assets/075ab0a6-8963-4126-96bc-4a77444388ed)

`request`
![image](https://github.com/user-attachments/assets/135e451c-95f2-432a-8a0c-aa39adaa9285)

`ui error that appears when selecting "See the full error"` **(not sure if this is relevant or helpful)**
```
AxiosError@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:99982
settle@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:20234
onloadend@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:25714
EventHandlerNonNull*dispatchXhrRequest@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:25858
xhr<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:24275
dispatchRequest@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:29954
request@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:8:36983
wrap@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:226714
_callee$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:166949
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:164851
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:165180
_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:165317
_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:165074
request@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:167733
_callee$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:181365
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178377
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178706
_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178843
_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178600
genericReq@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:183378
_callee2$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:184121
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178377
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178706
_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178843
_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:178600
apiReq@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.plugin.js:1:185272
_callee8$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9015921
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
register_agent_services_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012371
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012747
register_agent_services_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012908
register_agent_services_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012617
_getAuthConfiguration@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9016423
getAuthConfiguration@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9015382
_callee5$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9021237
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
register_agent_services_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012371
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012747
promise callback*register_agent_services_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012489
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012747
promise callback*register_agent_services_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012489
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012747
promise callback*register_agent_services_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012489
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012747
register_agent_services_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012908
register_agent_services_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9012617
getMasterConfiguration@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9021495
_callee$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9130394
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
register_agent_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126103
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126461
register_agent_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126613
register_agent_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126340
getMasterConfig@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9130717
_callee2$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9131267
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
invoke@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:790934
defineIteratorMethods/</<@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:788105
register_agent_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126103
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126461
promise callback*register_agent_asyncGeneratorStep@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126221
_next@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126461
register_agent_asyncToGenerator/</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126613
register_agent_asyncToGenerator/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9126340
fetchData@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9132532
RegisterAgent</<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:9132558
is@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:83209
gc@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:102288
__osdSharedDeps__</t.unstable_runWithPriority@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:444:3844
ji@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:45024
bc@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:102047
Qs@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:93596
Ui/<@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:45315
__osdSharedDeps__</t.unstable_runWithPriority@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:444:3844
ji@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:45024
Ui@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:45262
Hi@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:45195
tc@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:94045
jc@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:113115
__osdSharedDeps__</t.render@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:436:116094
601/ngReact/renderComponent/<@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.6.js:17:40891
$digest@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:100890
$apply@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:103069
$applyAsync/r<@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:103217
Jr/this.completeTask@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:123750
un/o.defer/r<@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:34475
setTimeout handler*un/o.defer@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:34447
$applyAsync@https://x.x.x.x:1234/47302/bundles/osd-ui-shared-deps/osd-ui-shared-deps.js:428:103197
_callee5$@https://x.x.x.x:1234/47302/bundles/plugin/wazuh/wazuh.chunk.10.js:1:8965375
tryCatch@https://x.x.x.x:1234/47302/bundles/plugin/customImportMapDashboards/customImportMapDashboards.plugin.js:13:786910
```

**Comment by MiguelazoDS** [comment]
Hi  @djedcurtis, 

Could you verify the wazuh-auth is running? 

`ps -aux | grep wazuh-auth`

**Comment by djedcurtis** [comment]
The output is below
![image](https://github.com/user-attachments/assets/26c8f156-e80c-4d16-ad48-aa09c69ff843)

When running `ps -A | grep wazuh`, I get the following
![image](https://github.com/user-attachments/assets/5b8b8f68-db0c-4ad1-8c12-cca8e99810a4)

**Comment by djedcurtis** [comment]
Hi @MiguelazoDS,

It looks to be working!!

After referencing your default ossec.conf file, it looks like the backup that I had used that was made was missing the `<auth>` section.
I added that in, checked my copy and made sure all was in order and restarted the manager.

After restarting and running `ps -A | grep wazuh`, I now get the following.
![image](https://github.com/user-attachments/assets/e8e88078-a4fb-46a0-8857-9b8990643565)
With the authd process running.

I don't seem to be getting any errors on the UI anymore, looks like my local_rules have been wiped for some bizarre reason, but I should be able to rebuild these.
The agent I added has also gone through now.

It shouldn't matter as it now seems to be working, but my ossec.log file doesn't output what you've shown above?
When running `systemctl restart wazuh-manager.service`, no output appears at all.
Where is this log stored / where should it be output to?

Thank you very much for all your assistance, it's been a pleasure :)

**Comment by MiguelazoDS** [comment]
Hi @djedcurtis, glad to know it's working. 

That command does not print any message. You could check with `status` to see if everything is ok. 

![image](https://github.com/user-attachments/assets/1c2b000d-5b44-43a4-99dc-98175faa6a83)

The file `/var/ossec/etc/local_rules.xml` is preserved during upgrades. 

Regards!

**Comment by djedcurtis** [comment]
![image](https://github.com/user-attachments/assets/0dbdbb3e-72a2-45ab-944a-d75abf8f5917)

All looks to be working now, I'm not sure if the local_rules.xml has changed but that's something I'll look into.
I'll need to go through and update my monitoring connections for Entra, Github, Office 365 and so on, but that's not a problem.

Again, thank you for all your assistance!
I'll close this off now 👍 

Regards! :)

**Comment by MiguelazoDS** [comment]
Great @djedcurtis, have a good day!

**Comment by merin862** [comment]
Hello Guys, please help me with the same issue. I faced the same problem and went through this discussion. Nothing helps me to solve my issue. 

![Image](https://github.com/user-attachments/assets/41881a22-bea0-43f6-9209-768292b6bd49)
