### ISSUE TITLE
Add registry scan in whodata mode

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2525]
Currently whodata does not handle registry modification events. It may be sufficient to add processing for event [4657](https://www.ultimatewindowssecurity.com/securitylog/encyclopedia/event.aspx?eventID=4657).

**Comment by chemamartinez** [comment]
Duplicated.

https://github.com/wazuh/wazuh/issues/5863
https://github.com/wazuh/wazuh/issues/11103
