### ISSUE TITLE
Wazuh dose now work

### ISSUE THREAD

**Issue by Chrisj76au** [wazuh/wazuh#25250]
|Wazuh version|Component|Install type|Install method|Platform|
Ubuntu 22.04 | 4.8 |  curl -sO https://packages.wazuh.com/4.8/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
Fresh Server 4vcpu / 8GB /50GB 
attached full ssh interaction and logs

try to go to  web interface https://<wazuh-dashboard-ip> ask the server IP address

This page isn’t working10.2.1.248 didn’t send any data.
ERR_EMPTY_RESPONSE

I've tried this 4 time now recreating the vm and still do not work? 
clearly there is an issue with this software?
[Wazuh.txt](https://github.com/user-attachments/files/16657673/Wazuh.txt)

-->

**Comment by pereyra-m** [comment]
Hi @Chrisj76au 

If you are going to test Wazuh on a virtual machine, maybe it is easier to download the pre-built image with everything installed

[Virtual Machine (OVA)](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html#virtual-machine-ova)

This way you can skip the installation step.

Still, the installation process doesn't show any error message.
Also, there are many messages like `"message":"http server running at https://0.0.0.0:443"}` so it seems to be up and running.
If you are going to keep debugging the installation, can you share the network configuration of the VM?
Maybe the network interface isn't configured as bridged and you can't reach the Wazuh dashboard from your host.

Regards.

**Comment by Chrisj76au** [comment]
Thanks for the suggestion I finally managed to get it to work and add a bridge

**Comment by pereyra-m** [comment]
Great news @Chrisj76au , thanks for the update.
