### ISSUE TITLE
Alert in ossec logs not created in wazuh-app

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh#2526]
|Wazuh version|Install type|Install method|Platform|
|3.8.2|Manager|Packages|RH7|

Hi, I have integrations two integrations and notice an alert in particular that was sent to the integrations but when I searched for it, it is not in the wazuh-app, searched in the dashboards, discover and directly into the index searching by that rule id and there is nothing there, the event came from an agent running agent 3.8.2 as well, is there any log listing all alerts dropped or not loaded into elasticsearch? how can I generate an alarm in case of an alarm being dropped?

{
    "agent": {
        "id": "111",
        "ip": "10.a.b.c",
        "name": "HOSTNAME"
    },
    "cluster": {
        "name": "wazuh",
        "node": "wazuh-manager-node.domain.com"
    },
    "data": {
        "data": "BlackShield",
        "dstuser": "(no user)",
        "id": "0",
        "status": "ERROR",
        "system_name": "HOSTNAME.ad.domain.com",
        "type": "Application"
    },
    "decoder": {
        "name": "windows",
        "parent": "windows"
    },
    "full_log": "2019 Feb 05 14:51:17 WinEvtLog: Application: ERROR(0): BlackShield: (no user): no domain: HOSTNAME.ad.domain.com: Exception has been handled while closing socket:   An existing connection was forcibly closed by the remote host     at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)     at ProxiedSource.SocketListener.SocketSucker.ReadSocket(Object incData)    ",
    "id": "1549378583.4856245608",
    "location": "WinEvtLog",
    "manager": {
        "name": "wazuh-node.domain.com"
    },
    "predecoder": {
        "program_name": "WinEvtLog",
        "timestamp": "2019 Feb 05 14:51:17"
    },
    "previous_output": "2019 Feb 05 14:56:06 WinEvtLog: Application: ERROR(0): BlackShield: (no user): no domain: ASSETTAG.ad.domain.com: Exception has been handled while closing socket:   An existing connection was forcibly closed by the remote host     at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)     at ProxiedSource.SocketListener.SocketSucker.ReadSocket(Object incData)    \n2019 Feb 05 14:49:16 WinEvtLog: Application: ERROR(21): BlackShield: (no user): no domain: ASSETTAG.ad.domain.com: Error provisioning user 1002440 for SS_PassToken_Provision in TATA Consultancy Services Limited  5515// 3 3? Failed to add provisioning entry. Not enough capactiy. 5515// 3 3? Failed to add provisioning entry. Not enough capactiy.    at
(LONG LOG REMOVED)  ",
    "rule": {
        "description": "Multiple Windows error events.",
        "firedtimes": 1,
        "frequency": 6,
        "groups": [
            "windows"
        ],
        "id": "18154",
        "level": 10,
        "mail": false
    },
    "timestamp": "2019-02-05T14:56:23.380+0000"
}

**Comment by jesusgn90** [comment]
Hi @spartantri,

First of all, sorry for the late response.

I've appended your alert in one-line format to my `alerts.json` and I can see it in Discover:

![image](https://user-images.githubusercontent.com/8860227/58177245-4d027c00-7ca4-11e9-983a-3fe9c1f1c961.png)

So my suggestion is to check if the alert was added to the `alerts.json`. I think the next command should be enough to do that:

```
cat /var/ossec/logs/alerts/alerts.json | grep WinEvtLog | grep '"18154"'
```

Regards,
Jesús
