### ISSUE TITLE
Errors related to 'libatomic.a' library on AIX 7.X

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#25263]
# Description
Hello team,

After some open issues due to problems installing the Wazuh agent on the AIX operating system.

We have detected that it is necessary to move the `libatomic.a` to a specific directory `/usr/lib`, or at least modify the `LIBPATH` environment variable to contain the path where this library is located, by default `/opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8/ppc64/`.

Error installing wazuh-agent:
```
bash-5.1# WAZUH_MANAGER="10.0.0.2" rpm -ivh wazuh-agent-4.8.1-1.aix.ppc.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-agent-4.8.1-1              ################################# [100%]
bash-5.1# /var/ossec/bin/wazuh-control start
exec(): 0509-036 Cannot load program /var/ossec/bin/wazuh-execd because of the following errors:
        0509-130 Symbol resolution failed for /var/ossec/lib/libwazuhext.so because:
        0509-136   Symbol _GLOBAL__AIXI_libatomic_so (number 167) is not exported from
                   dependent module /usr/lib/libatomic.a(libatomic.so.1).
        0509-136   Symbol _GLOBAL__AIXD_libatomic_so (number 168) is not exported from
                   dependent module /usr/lib/libatomic.a(libatomic.so.1).
        0509-136   Symbol __atomic_is_lock_free (number 170) is not exported from
                   dependent module /usr/lib/libatomic.a(libatomic.so.1).
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.
wazuh-execd: Configuration error. Exiting
```

After moving libatomic.a, it works:
```
bash-5.1# cp /opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8/ppc64/libatomic.a /usr/lib
bash-5.1# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.8.1...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

This problem appears in AIX 7.X versions, since for version 6 the agent was correctly tested here: 
- https://github.com/wazuh/wazuh/issues/23963

We have managed to make it work with the [workaround given in the mentioned issues](https://github.com/wazuh/external-devel-requests/issues/2853#issuecomment-2288523283), however, we want to investigate further to see if we can or should do something in the agent to make it work directly.

**Comment by vikman90** [comment]
## Caveats

1. Has the `LIBPATH` changed, or is it the location of the libraries?
2. Is there a guarantee that the _libatomic.so_ file is always present on AIX 7.x?

## Fix proposal

I think we can simply update `LIBPATH` at [ossec-hids-aix.init](https://github.com/wazuh/wazuh/blob/4.9.1/src/init/templates/ossec-hids-aix.init).

**Comment by jotacarma90** [comment]
# Investigation
Upon further investigation, I have not found that we have modified the LIBPATH variable. Actually the problem comes because we are looking for it in the /usr/lib directory:
```
ifeq (${uname_S},AIX)
		DEFINES+=-DAIX -D__unix
		DEFINES+=-DHIGHFIRST
		OSSEC_CFLAGS+=-pthread
		OSSEC_LDFLAGS+=-pthread -L./lib
ifeq ($(INSTALLDIR),)
	INSTALLDIR = /var/ossec
endif
		CMAKE_OPTS+=-DINSTALL_PREFIX=${INSTALLDIR}
		OSSEC_LDFLAGS+='-Wl,-blibpath:${INSTALLDIR}/lib:/usr/lib:/lib'
		AR_LDFLAGS+=-pthread
		AR_LDFLAGS+='-Wl,-blibpath:${INSTALLDIR}/lib:/usr/lib:/lib'
		PATH:=${PATH}:/usr/vac/bin
		CC=gcc
		PRECOMPILED_OS:=aix
```

And yet for AIX 7.X versions, it seems that it is no longer found in that directory. I have found in an IBM docu, that for the Open XL C/C++ 17.1.1 compiler version, the libatomic library is no longer linked implicitly, and maybe this has also caused that it has been removed from `/usr/lib`:
https://www.ibm.com/docs/en/SSRZSMX_17.1.1/pdf/migrate.pdf

```
In IBM Open XL C/C++ for AIX 17.1.1, many libraries are no longer linked implicitly, such as libatomic
and libm. If operations related to these libraries are used in your program, specify the corresponding
linking options explicitly, such as -latomic and -lm.
```

The library is present in the installation of gcc 8 itself, so a possible option would be as @vikman90 mentions to include it manually in the `LIBPATH`. It can also be done directly in the Makefile by adding the path:

`$(OSSEC_SHARED) $(OSSEC_CFLAGS) libwazuhext/*.o -o $@ -static-libgcc -Wl,-blibpath:/opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8/ppc64:/usr/lib:/lib -latomic`

**Comment by vikman90** [comment]
@jotacarma90 thanks!

## Action items

- [ ] **Check the library search order (in load time):**
    According to the **[ld.so manual](https://man7.org/linux/man-pages/man8/ld.so.8.html)**, the Linux loader first looks at the `DT_RPATH` section of the binary, and it later searches in `LD_LIBRARY_PATH`.
    We need to check if AIX works in the same way, either finding some documentation or checking it manually.
- [ ] **Implement the Makefile fix**:
  Check if we can add some kind of wildcards to `-blibpath` and extend the flag with `/opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8/ppc64` (or similar).

**Comment by mjcr99** [comment]
## Update
**(26/08/2024)** Requested VM to develop and test the solution. Providing the VM with the required dependencies to build and test the solution.
