### ISSUE TITLE
Engine - Eliminate engine-suite dependency on integration test

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25295]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Engine | Manager | Packages/Sources | OS version |

## Description
Revise the Engine integration tests to directly utilize the API for loading assets and integrations. This update will eliminate the reliance on the engine-suite tool, which has led to issues where integration tests fail due to changes outside of the Engine codebase.

Also the initial setup needs to be fixed (path errors) and improve output information.

## Expected Deliverables
- Integration tests no longer rely on the engine-suite Python package.
- Initial setup is fixed.
- Integration test is implemented as a python package and uses the engine-updown package.

## DoD
- [x] Integration tests pass successfully.
- [x] Integration tests are fully independent of the engine-suite package.
- [x] it-utils package is removed.
- [x] Integration test python package is created.

**Comment by JavierBejMen** [comment]
## Update
- Updated all integration tests
- Updated integration workflow
- Working on updating helper_test

**Comment by JavierBejMen** [comment]
## Update
- Updated helper tests
- Minor fixes in helper test workflow
- Minor fixes in integration test steps
