### ISSUE TITLE
Mitre Technique ID 'Txxxx' not found in database

### ISSUE THREAD

**Issue by nvducict** [wazuh/wazuh#25321]
| 4.8.2-1 | Wazuh component | Manager | Packages | Ubuntu 22.04 |

Problem 1:
- When I check the log at "/var/ossec/logs/ossec.log" I get a lot of warnings as shown in the picture.
![ảnh](https://github.com/user-attachments/assets/0d19c946-d7d0-4cde-9de7-de1019df2a75)
- On wazuh-dashboard, MITERs do not appear
![ảnh](https://github.com/user-attachments/assets/1a7bb5f8-2cff-4a7c-9cc5-be42685be6a8)

Problem 2:
- Vulnerability Detection function in wazuh-dashboard shows error message "Vulnerability detection seems to be disabled or has a problem"
![ảnh](https://github.com/user-attachments/assets/dadff5a8-92c9-4153-a7b8-6faac5af3b02)

Referred to the instructions at https://documentation.wazuh.com/current/upgrade-guide/troubleshooting.html but still could not fix the above 2 problems

Note: MITER IDs can still be found in Rules
![ảnh](https://github.com/user-attachments/assets/9a099911-22a1-4383-be64-0ab58ffa00c7)

**Comment by pereyra-m** [comment]
Hello @nvducict 

About the MITRE warnings, there could be an issue related to the DB that stores all the techniques. Have you modified/removed that file? Were there any warning/error messages during the installation?
Please share the output of the following command so we can check it's present and contains the right permissions

```
# ls -l /var/ossec/var/db/
```

I have installed a fresh 4.8.2 manager and the technique is present

<details><summary>Details</summary>
<p>

```
root@fb659c773250:/var/ossec# sqlite3 /var/ossecvar/db/mitre.db "SELECT * FROM reference WHERE external_id = 'T1498';"
-- Loading resources from /root/.sqliterc
         id = course-of-action--654addf1-47ab-410a-8578-e1a0dc2a49b8
     source = mitre-attack
external_id = T1498
        url = https://attack.mitre.org/mitigations/T1498
description = 
       type = mitigation

         id = attack-pattern--d74c4a7e-ffbf-432f-9365-7ebf1f787cab
     source = mitre-attack
external_id = T1498
        url = https://attack.mitre.org/techniques/T1498
description = 
````

</p>
</details> 

Can you share also the hardware specifications of your host? Maybe having less than 8GB of RAM ([hardware requirements](https://documentation.wazuh.com/current/quickstart.html#requirements)) makes the queries take too much time and they end up failing.

Now, about the vulnerability scanner, could you share your complete `ossec.log` and `ossec.conf` files?
If there is a credentials/certs issue with the manager it won't create the vulnerabilities index.
We can try with this `curl` command to confirm that the indexer node is reachable from the manager and that the password/certs are valid. Replace with the values from your configuration file and the values stored in your `wazuh-keystore`

```
curl --cacert PATH_TO_CA_ROOT --cert PATH_TO_CERT --key  PATH_TO_KEY -u USERNAME:PASSWORD "https://INDEXER_IP:9200/"
```

**Comment by pereyra-m** [comment]
Hello again @nvducict, thank you for the information provided.
Could you tell me also if you used the installation assistant or the step-by-step guide? Have you installed all Wazuh components on the same host?

I'm researching about the MITRE error, the permissions are correct.

About the vulnerability detector module, if the `curl` command is successful then we should check the `wazuh-keystore`.
Have you followed the steps at https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#configuring-the-wazuh-indexer-connection? If the password contains some special Bash characters it might not have been saved correctly.

Then you could temporarily enable the debug logs for `wazuh-modulesd` so we can get more information about the module, the portion of the logs you've shared has no information about vulnerability detector
- Stop the `wazuh-manager`
- Set `wazuh_modules.debug=2` at `/var/ossec/etc/internal_options.conf`
- Restart your manager
- Share the `ossec.log` file with the debug logs.

**Comment by pereyra-m** [comment]
Hi @nvducict 

We've been analyzing the logs you've provided with the team.

The test for the vulnerability scanner has shown a complete restart of the manager and it's clear from the logs that `wazuh-db` takes too long to be ready for the other daemons, making all the related queries fail (including the MITRE techniques).
This is probably due to a lack of resources, can you increase the CPU cores/speed of the host?

About the other issue, we can see this type of messages
```
2024/08/24 10:25:41 indexer-connector[99182] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-fit-hids': No available server. Retrying in 60 seconds.
```

It is possible that the indexer cluster isn't in 'green' status, so the module won't index the vulnerabilities.
To confirm this, please run these queries to gather more information

```
curl --cacert PATH_TO_CA_ROOT --cert PATH_TO_CERT --key  PATH_TO_KEY -u USERNAME:PASSWORD "https://INDEXER_IP:9200/_cluster/health"

curl --cacert PATH_TO_CA_ROOT --cert PATH_TO_CERT --key  PATH_TO_KEY -u USERNAME:PASSWORD "https://INDEXER_IP:9200/_cluster/allocation/explain"
```

There could be unassigned shards, etc.

**Comment by pereyra-m** [comment]
Great news!
Thanks for the update.
