### ISSUE TITLE
Incorporate a new method to log lambda functions

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25326]
## Description

This issue aims to add a new macro to log with lambdas and display more accurate information related to the lambda function.

##  Expected
- Add methods:
   LOG_DEBUG_L("Lambda description", LOG, VARIADIC LIST)
   LOG_TRACE_L("Lambda description", LOG, VARIADIC LIST)
   LOG_INFO_L("Lambda description", LOG, VARIADIC LIST)
   LOG_WARNING_L("Lambda description", LOG, VARIADIC LIST)
   LOG_ERROR_L("Lambda description", LOG, VARIADIC LIST)

- Modify lambda functions to log more descriptive function references.
  - osScanner.hpp
  - packageScanner.hpp

- Create a new issue to investigate this usage in the engine.

**Comment by JavierBejMen** [comment]
## Update
- Added lambdas to logging.hpp
- Modified code in VD
- Working on logging tests
- Working on better lambda parametrization and formatting

**Comment by JavierBejMen** [comment]
## Update
- Added function to format the name.
- Added tests
