### ISSUE TITLE
Release 4.9.0 - RC 1- Integration tests

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25347]
# Description
|| | 
| :--                              | :--                                                             |
| **Main release stage issue** |  https://github.com/wazuh/wazuh/issues/25332 |
| **Version**                      | 4.9.0                                               |
| **Release stage**            | RC 1                                                    
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.9.0-rc1         |
| **Wazuh QA: Branch**    | `v4.9.0-rc1`
| **Wazuh Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-rc1         |
| **Wazuh Branch**    | `v4.9.0-rc1`

The tests will be performed in Jenkins using `centOS` as the manager OS. As for the agents, `Linux`, `Windows`, `Solaris`, `and macOS` will be used as required.

### Build

***Build***: https://ci.wazuh.info/job/Test_integration_launcher/261

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

<html>
</html>

### Pipeline

**active_response** :green_circle: 
**agentd** :red_circle: 
**authd** :green_circle: 
**enrollment** :green_circle: 
**FIM** :yellow_circle: 
**gcloud** :green_circle: 
**logcollector** :green_circle: 
**logtest** :green_circle: 
**remoted** :green_circle: 
**rids** :green_circle: 
**wazuh_db** :green_circle: 
**syscollector** :yellow_circle: 

### GHA integration test

**test_agentd** :green_circle:
**test_authd** :red_circle:
**test_aws** :red_circle:
**test_enrollment** :green_circle:
**test_fim** :green_circle:
**test_integratord** :green_circle:
**test_logcollector** :green_circle:
**test_logtest** :green_circle:
**test_remoted** :green_circle:
**test_sca** :green_circle:
**test_syscollector** :green_circle:
**test_vulnerability_detector** :red_circle:
**test_wazuh_db** :green_circle:
**test_analysisd** :green_circle:
**test_api** :green_circle:
**test_execd** :green_circle:
**test_github** :green_circle:
**test_msgraph** :green_circle:
**test_office365** :green_circle:

Known Issue: 
- https://github.com/wazuh/wazuh-qa/issues/4230
- https://github.com/wazuh/wazuh/issues/23403

Opened Issue: 
- https://github.com/wazuh/wazuh/issues/25371
- https://github.com/wazuh/wazuh/issues/25432
- https://github.com/wazuh/wazuh/issues/25431
- https://github.com/wazuh/wazuh/issues/25430

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

</br>

<html>
  <table>
    <thead>
      <tr>
        <th>Test suite</th>
        <th>Target</th>
        <th>CentOS</th>
        <th>Ubuntu</th>
        <th>Windows</th>
        <th>macOS</th>
        <th>Solaris</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>active_response</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47717/manager_html_report_Test_integration_B47717.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>active_response</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47718/agent_centos_html_report_Test_integration_B47718.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47718/agent_windows_html_report_Test_integration_B47718.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>agentd</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47719/agent_centos_html_report_Test_integration_B47719.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47719/agent_windows_html_report_Test_integration_B47719.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>authd</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47720/manager_html_report_Test_integration_B47720.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>enrollment</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47721/agent_centos_html_report_Test_integration_B47721.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47721/agent_windows_html_report_Test_integration_B47721.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Manager</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47722/manager_html_report_Test_integration_B47722.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47723/agent_centos_html_report_Test_integration_B47723.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47723/agent_windows_html_report_Test_integration_B47723.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>fim</td>
        <td>Agent</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47724/agent_macos_html_report_Test_integration_B47724.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47724/agent_solaris_html_report_Test_integration_B47724.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>gcloud</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47725/manager_html_report_Test_integration_B47725.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47726/manager_html_report_Test_integration_B47726.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>logcollector</td>
        <td>Agent</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47727/agent_centos_html_report_Test_integration_B47727.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47727/agent_windows_html_report_Test_integration_B47727.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47727/agent_macos_html_report_Test_integration_B47727.zip">Download evidence</a></td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47727/agent_solaris_html_report_Test_integration_B47727.zip">Download evidence</a></td>
      </tr>
      <tr>
        <td>logtest</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47728/manager_html_report_Test_integration_B47728.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>remoted</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47729/manager_html_report_Test_integration_B47729.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>rids</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47730/manager_html_report_Test_integration_B47730.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>wazuh_db</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47731/manager_html_report_Test_integration_B47731.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Manager</td>
        <td>:green_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47732/manager_html_report_Test_integration_B47732.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>syscollector</td>
        <td>Agent</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47716/agent_centos_html_report_Test_integration_B47716.zip">Download evidence</a></td>
        <td>N/A</td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47716/agent_windows_html_report_Test_integration_B47716.zip">Download evidence</a></td>
        <td>:red_circle: <a href="https://s3.amazonaws.com/ci.wazuh.com/data/Test_integration/B47716/agent_macos_html_report_Test_integration_B47716.zip">Download evidence</a></td>
        <td>N/A</td>
      </tr>
    </tbody>
  </table>
</html>

**Comment by joaquinsgi** [comment]
# Analysis Report

## **agentd** :red_circle: 
- Agent: Opened Issue: https://github.com/wazuh/wazuh/issues/25371

## **FIM** :red_circle: 
- CentOS Manager: Opened Issues: 
    - https://github.com/wazuh/wazuh-qa/issues/5645 
    - https://github.com/wazuh/wazuh-qa/issues/5644
    - https://github.com/wazuh/wazuh-qa/issues/5646
- Agent CentOS: Opened Issue: 
    - https://github.com/wazuh/wazuh-qa/issues/5645 
    - https://github.com/wazuh/wazuh-qa/issues/5644
    - https://github.com/wazuh/wazuh-qa/issues/5646
- Agent Windows: Opened Issue: 
    - https://github.com/wazuh/wazuh-qa/issues/5646
    - https://github.com/wazuh/wazuh-qa/issues/5644
- Agent MacOS and Solaris
    - https://github.com/wazuh/wazuh-qa/issues/5647
    

## **syscollector** :yellow_circle: 
- Agent: known Issue: https://github.com/wazuh/wazuh-qa/issues/4230

**Comment by joaquinsgi** [comment]
# Analysis GA Executions

## API :black_circle: 
-  :black_circle: 
``` 
```
-  :black_circle: 
``` 
```

## Analysisd :black_circle: 
-  :black_circle: 
```

```
-  :black_circle: 
```
```


## Execd :black_circle:
-  :black_circle: 
```

```
-  :black_circle: 
```

```

## Github :black_circle: 
-  :black_circle: 
```

```
-  :black_circle: 
```
```

## Office365 :black_circle: 
-  :black_circle: 
```

```

-  :black_circle: 
```

```

## MSGraph :black_circle: 
-  :black_circle: 
```

```

**Comment by fcaffieri** [comment]
LGTM

**Comment by fcaffieri** [comment]
LGTM

**Comment by juliamagan** [comment]
In 4.9.0, the tests are considered fully migrated and the Jenkins pipeline is no longer launched, only the GHAs are launched. However, there are still [tests](https://github.com/wazuh/wazuh/tree/v4.9.0-rc1/tests/integration) that need to be launched.

**Comment by fcaffieri** [comment]
A request was made to @cppserver to restore and copy the YAMLS of the GHA integration test to proceed with its execution.

**Comment by joaquinsgi** [comment]
# Analysis GA Executions

## Agentd :black_circle: 
-   :black_circle: 
``` 

```
-   :black_circle: 
``` 

```

## Authd :black_circle: 
-  :black_circle: 
```
```
-  :black_circle: 
```
```


## AWS :black_circle:
-  :black_circle: 
```
```
-  :black_circle: 
```
```

## Enrollment :black_circle: 
-  :black_circle: 
```
```
-  :black_circle: 
```
```

## FIM :black_circle: 
-  :black_circle: 
```
```

-  :black_circle: 
```
```

## Integratord :black_circle: 
-  :black_circle: 
```
```
## Logtest :black_circle: 
-  :black_circle: 
```
```

**Comment by hossam1522** [comment]
# Analysis GA Executions

## Logcollector :black_circle: 
-  
``` 

```
-  
``` 

```
-  
``` 

```

## RBAC :black_circle: 
- 
```

```


## Remoted :black_circle:
- 
```


```

## SCA :black_circle: 
- 
```

```
- 
```

```

## Syscollector :black_circle: 
- 
```

```

-  
```

```

## Vulnerability detector :black_circle: 
- 
```

```

## Wazuh_db :black_circle: 
- 
```

```

**Comment by fcaffieri** [comment]
LGTM
