### ISSUE TITLE
Rule to get alert on more than one windows session of the same user?

### ISSUE THREAD

**Issue by shahmilan34** [wazuh/wazuh#2536]
if user is already logged in and an attempt made to logon to same user from different ip then need to send alert.

**Comment by Cerv1** [comment]
Hi @shahmilan34,

I think this issue is solved on https://github.com/wazuh/wazuh/pull/2689 so let me close this issue. 

If it's not, please feel free to reopen this thread.

Best regards,
Cerv1.
