### ISSUE TITLE
Windows Agent failed in Integration Tests

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25371]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 RC 1 | agentd | Agent | Packages | Windows |

Analyzing the integration tests of: https://github.com/wazuh/wazuh/issues/25347 in **agentd** on the Windows agent, a failure was found due to what appears to be the fact that a message was not sent from the agent. It was expected that 1 message would be sent, but none was sent.

<details>
  <summary>Report Log</summary>
  <br/>

```console
while self._continue:
if self._abort:
self.stop()
if error_message:
logger.error(error_message)
logger.error(f"Results accumulated: "
f"{len(result) if isinstance(result, list) else 0}")
logger.error(f"Results expected: {accum_results}")
> raise TimeoutError(error_message)
E TimeoutError: Notify message from agent was never sent!

C:\Python311\Lib\site-packages\wazuh_testing\tools\monitoring.py:465: TimeoutError
------------------------------Captured stdout call------------------------------
The Wazuh service was stopped successfully. The Wazuh service is starting. The Wazuh service was started successfully.
------------------------------Captured stderr call------------------------------
2024-08-22 14:48:14,386 - wazuh_testing - ERROR - Notify message from agent was never sent! 2024-08-22 14:48:14,387 - wazuh_testing - ERROR - Results accumulated: 0 2024-08-22 14:48:14,387 - wazuh_testing - ERROR - Results expected: 1
-------------------------------Captured log call--------------------------------
ERROR wazuh_testing:monitoring.py:461 Notify message from agent was never sent! ERROR wazuh_testing:monitoring.py:462 Results accumulated: 0 ERROR wazuh_testing:monitoring.py:464 Results expected: 1
```

</details>

In previous analyses of integration tests, the failure was due to: https://github.com/wazuh/wazuh/issues/22854, but it seems that this time it is a different type, which also causes a failure in the CentOS agent.

## Evidences
Report:  [report.zip](https://github.com/user-attachments/files/16729983/report.zip)
Build: https://ci.wazuh.info/job/Test_integration/47719/

**Comment by vikman90** [comment]
## Replay

Job [#47333](https://ci.wazuh.info/job/Test_integration/47733)
