### ISSUE TITLE
Release 4.9.0 - RC 1 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#25403]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |            https://github.com/wazuh/wazuh/issues/25332                   |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/25362                       |
| **Version**                          |                   4.9.0                         |
| **Release stage**              |                   RC 1                      |
| **Tag**                              |          https://github.com/wazuh/wazuh-qa/tree/v4.9.0-rc1                               |
| **Previous Vulnerability performance tests issue**      |       https://github.com/wazuh/wazuh/issues/25140                    |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 25 | 3 | 50000 | 1 | 60 | 100 | 1h |

**Considerations**

- `KIBANA_API_REQUESTS` should be enabled
- `EXTRA_LOAD_API_REQUESTS` should be enabled
- Due to the current operation of the simulator and how it does the EPS distribution with the frequency, we can expect the actual EPS to be about half, so it is necessary to set twice as much.

### Builds

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/649/
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/650/
- Very high: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/653/

## Conclusion :red_circle: 

New issues:

- https://github.com/wazuh/wazuh/issues/25420
- https://github.com/wazuh/wazuh-jenkins/issues/6902
- https://github.com/wazuh/wazuh-jenkins/issues/6903

Known issues:

- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/wazuh/wazuh-indexer/issues/328
- https://github.com/wazuh/wazuh-indexer/issues/167
- https://github.com/wazuh/wazuh/issues/25215
- https://github.com/wazuh/wazuh/issues/25204

**Comment by MARCOSD4** [comment]
Moved to On hold until the builds are finished:

Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/649/
High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/650/
Very high: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/651/

**Comment by santipadilla** [comment]
# Medium Activity 

**Artifacts**: 

**Comparision**: Compared with https://github.com/wazuh/wazuh/issues/24504

**Build**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/649/

***

## Logs :black_circle:
 
### Summary


<details>

<summary> Master :black_circle: </summary>

- Expected errors:

```



```



```


```

</details>
 
<details>

<summary> Worker 1 :black_circle: </summary> 


- Expected errors:

```



```

</details>

<details>

<summary> Worker 2 :black_circle: </summary>


- Expected errors:

```


```

</details>

<details>

<summary> Indexer 1 :black_circle: </summary>



```


```



```


```



```

```



```

```


</details>

<details>

<summary> Indexer 2 :black_circle: </summary>




```


```



```


```



```

```



```

```

</details>

<details>

<summary> Dashboard :black_circle:  </summary>




</details>

**Comment by MARCOSD4** [comment]
# Medium Activity

## Metrics and Statistics

**Comment by MARCOSD4** [comment]
# Medium Activity

## Metrics and Statistics

<details><summary>Worker 1 :black_circle: </summary>

- Binaries

![CPU](https://github.com/user-attachments/assets/234a54cc-4979-4a0b-946c-aaed82e94164)

![Disk_Read](https://github.com/user-attachments/assets/0b95577d-02af-470a-889a-4dd11eb6551d)

![Disk_Read_Speed](https://github.com/user-attachments/assets/928d39d5-ac3d-44cb-b20d-a6b297714348)

![Disk_Write_Speed](https://github.com/user-attachments/assets/67a746af-f5c9-44b6-ac9f-4f4c00fde9de)

![Disk_Written](https://github.com/user-attachments/assets/f9c8886c-97ff-4e64-ab55-cfab728b47ab)

![FD](https://github.com/user-attachments/assets/f29d5e6b-3238-4f08-9e72-e14f4f83e396)

![PSS](https://github.com/user-attachments/assets/92784f50-5caa-4bbe-8b16-c57e26539f94)

![Read_Ops](https://github.com/user-attachments/assets/bdc50124-fb25-4925-8ba0-b97807b38426)

![RSS](https://github.com/user-attachments/assets/b8a2c3f7-498b-47f1-989d-ec18fd918ace)

![SWAP](https://github.com/user-attachments/assets/de177935-3c93-4af6-ba37-32c969a80ea1)

![USS](https://github.com/user-attachments/assets/141f22bd-fedc-436e-a794-a6357bb992ac)

![VMS](https://github.com/user-attachments/assets/91b71c81-8805-4c29-b51b-2f020d8ffd78)

![Write_Ops](https://github.com/user-attachments/assets/52e10b63-ac82-46f2-92cd-d679b1f43d34)

- Stats: wazuhdbd

- Stats: remoted

- Stats: logcollectord


</details>

<details><summary>Worker 2 :black_circle: </summary>

- Binaries

![CPU](https://github.com/user-attachments/assets/124651a0-0f1a-405e-ab35-f757745ba60c)

![Disk_Read](https://github.com/user-attachments/assets/186473ee-1ddc-49cc-a6e2-7426d53134f2)

![Disk_Read_Speed](https://github.com/user-attachments/assets/27d548b2-945e-4534-ad9c-51d212f3f150)

![Disk_Write_Speed](https://github.com/user-attachments/assets/672f115e-85de-4874-bd19-35ac06859ee9)

![Disk_Written](https://github.com/user-attachments/assets/776b7add-af62-41fd-9f26-ff9932e247f6)

![FD](https://github.com/user-attachments/assets/51ba2dcc-f7b7-47c8-ba19-6ead17018c07)

![PSS](https://github.com/user-attachments/assets/0f1ec15b-43a7-41dd-b602-f25252ac01c4)

![Read_Ops](https://github.com/user-attachments/assets/512a25e1-c74f-46d4-9776-4bfb9fbae7f9)

![RSS](https://github.com/user-attachments/assets/44401226-e45d-4d5c-95a5-3d182fc0d807)

![SWAP](https://github.com/user-attachments/assets/833bb776-405f-499f-9b1e-07733e6d021f)

![USS](https://github.com/user-attachments/assets/63c6ec0e-3cb6-487e-b85b-e6389e897a8e)

![VMS](https://github.com/user-attachments/assets/03d18e5b-2ded-41c8-9c07-3bc648225702)

![Write_Ops](https://github.com/user-attachments/assets/44b32a25-1276-40fe-9132-7d85b31413f0)

- Stats: wazuhdbd

- Stats: remoted

- Stats: logcollectord

</details>

**Comment by MARCOSD4** [comment]
# Medium Activity

## Metrics and Statistics

<details><summary>Indexer 1 :black_circle: </summary>

- Binaries

![CPU](https://github.com/user-attachments/assets/d6a9c27c-0eeb-43aa-99f7-98fefcce6b0f)

![Disk_Read](https://github.com/user-attachments/assets/5ee1ca55-1f4c-4ec1-b4cf-8d39a9ddd713)

![Disk_Read_Speed](https://github.com/user-attachments/assets/01227321-75f6-41f5-b2c3-86ab4c6da683)

![Disk_Write_Speed](https://github.com/user-attachments/assets/dc5776ee-e0e1-4436-acb0-0d4d957e89ea)

![Disk_Written](https://github.com/user-attachments/assets/d3811dc3-6af3-4b55-b81a-ca43f6c40f23)

![FD](https://github.com/user-attachments/assets/27b7ac9d-cece-41d9-8320-3470f8de4db5)

![PSS](https://github.com/user-attachments/assets/73c35652-e53b-460c-a36c-a688834a8839)

![Read_Ops](https://github.com/user-attachments/assets/f8def26d-17c9-439b-b4a3-7dc09d328002)

![RSS](https://github.com/user-attachments/assets/4d632c4d-393f-4fc4-819a-02a35bc92089)

![SWAP](https://github.com/user-attachments/assets/e74d9564-6b23-429e-9350-6fad7c04ad0e)

![USS](https://github.com/user-attachments/assets/bffff0fc-e088-49e9-8871-225af68bd412)

![VMS](https://github.com/user-attachments/assets/db5fe256-33ce-4dba-9481-d36ac3f4fa72)

![Write_Ops](https://github.com/user-attachments/assets/6d303c1e-88fa-46bb-ab13-c284ce9bfbba)


- Stats


</details>

<details><summary>Indexer 2 :black_circle: </summary>

- Binaries

![CPU](https://github.com/user-attachments/assets/aa1a5776-7ea4-46d1-9cd9-6bc211e0424f)

![Disk_Read](https://github.com/user-attachments/assets/9b9b822f-7889-4b43-92a0-c7c5542c9d33)

![Disk_Read_Speed](https://github.com/user-attachments/assets/5e90e1f8-6999-444c-b793-d8bb09aee99e)

![Disk_Write_Speed](https://github.com/user-attachments/assets/189e6889-a25c-49c4-844e-cf40a29c3cf2)

![Disk_Written](https://github.com/user-attachments/assets/712af1f7-36a5-4f16-bc22-399e477b23cf)

![FD](https://github.com/user-attachments/assets/a67b6ba0-6fe7-468c-a16f-ce516157a46f)

![PSS](https://github.com/user-attachments/assets/8449807c-0f13-4bc8-8d97-0d5670f9a661)

![Read_Ops](https://github.com/user-attachments/assets/4d76c69d-bec0-4ff2-90f7-c536c7f2f668)

![RSS](https://github.com/user-attachments/assets/c6162dc7-183f-4ed5-9e54-37cb1ce694ff)

![SWAP](https://github.com/user-attachments/assets/6ec0fa5d-953f-4dd1-ba49-9368ca1652f7)

![USS](https://github.com/user-attachments/assets/6c23a866-5c72-4cf1-8abd-79f3ad0beb2e)

![VMS](https://github.com/user-attachments/assets/c7b9747a-4aa3-42a3-b18b-f19133500246)

![Write_Ops](https://github.com/user-attachments/assets/c0e38fd6-3d42-48e7-af3d-4a74e440c8f8)

- Stats



</details>

## Vulnerability State :black_circle: 

## Alerts :black_circle:

**Comment by santipadilla** [comment]
# High Activity 
      
**Report**: [artifacts(4).zip](https://github.com/user-attachments/files/16757966/artifacts.4.zip)

**Build:**: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/650/

**Comparision** Compared with: https://github.com/wazuh/wazuh/issues/24504


***

## Logs :black_circle: 
 
### Summary


<details>

<summary> Master :black_circle:: </summary>


- Expected errors:

```

```



```

```

</details>
 
<details>

<summary> Worker 1 :black_circle: </summary> 




- Expected errors:

```

```


</details>


<details>

<summary> Worker 2 :black_circle: </summary>


- Expected errors:

```

```


</details>



<details>

<summary> Indexer 0 :black_circle: </summary>




```

```
</details>


<details>

<summary> Indexer 1 :black_circle: </summary>




```

```

</details>


<details>

<summary> Dashboard :green_circle:  </summary>

- No logs

</details>

**Comment by MARCOSD4** [comment]
# High Activity

## Metrics and Statistics

<details><summary>Master :black_circle: </summary>

- Metrics:



- Statistics:



---

- Binaries

![CPU](https://github.com/user-attachments/assets/8624339e-7cd6-480e-80bf-f0661d345814)
![Disk_Read](https://github.com/user-attachments/assets/437288e5-9b2a-4b9d-b10b-6aea33f23b2f)
![Disk_Read_Speed](https://github.com/user-attachments/assets/a3543232-1fcb-4b9b-a60d-2e8a1e6bf100)
![Disk_Write_Speed](https://github.com/user-attachments/assets/82b5b76c-4abd-4c8b-8d5f-0949a2c0dca5)
![Disk_Written](https://github.com/user-attachments/assets/9ec30f1d-9eb9-4fdb-a824-42e9be6d3c09)
![FD](https://github.com/user-attachments/assets/e0d4dabd-5e7f-4790-91eb-cca3ce740dae)
![PSS](https://github.com/user-attachments/assets/aaf60f8c-6b5c-415a-bef3-150190fa3ad0)
![Read_Ops](https://github.com/user-attachments/assets/f9823c58-89e6-4fae-b5b7-b54947a1f7e3)
![RSS](https://github.com/user-attachments/assets/eb7bf401-b273-4a5d-b3bf-998f51ef1b43)
![SWAP](https://github.com/user-attachments/assets/7f29cd50-faf2-4f25-868c-6dd278b21ef1)
![USS](https://github.com/user-attachments/assets/778c212d-e665-4a77-ab73-8e01f2ea00c3)
![VMS](https://github.com/user-attachments/assets/b6407a05-5943-4664-98d9-9afc45f8ab54)
![Write_Ops](https://github.com/user-attachments/assets/5e7d89ed-10c6-4ff3-b36e-dfe12c749ab8)


- Stats: wazuhdbd

![wazuh-wazuhdb_api_stats_Agent queries breakdown](https://github.com/user-attachments/assets/f739ff9d-50d7-4431-bf39-f44ab2803af2)
![wazuh-wazuhdb_api_stats_Agent tables breakdown](https://github.com/user-attachments/assets/37753453-67d0-40f0-a5eb-f22dd7877e70)
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/b41a8a67-7487-4afa-b3c8-7c2a4e54afc2)
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/98a04f41-5ead-40e7-ba02-b9ec9238141d)
![wazuh-wazuhdb_api_stats_Global group queries](https://github.com/user-attachments/assets/4b891491-2bae-4ad1-9ac8-82a81cf24525)
![wazuh-wazuhdb_api_stats_Global queries breakdown](https://github.com/user-attachments/assets/4f5953eb-4bf7-4dd6-b07c-6fbc54821d82)
![wazuh-wazuhdb_api_stats_Queries time metrics](https://github.com/user-attachments/assets/4e8ce15c-0241-479b-9516-a06c6f1ece79)
![wazuh-wazuhdb_api_stats_Task queries breakdown](https://github.com/user-attachments/assets/00a2713c-385a-4158-b2ca-9666c3763d9f)


- Stats: remoted

![wazuh-remote_api_stats_Bytes received](https://github.com/user-attachments/assets/f6d056ed-d4e0-4d5c-a560-db39a39ae9a3)
![wazuh-remote_api_stats_Events sent and count](https://github.com/user-attachments/assets/4ec7564d-b891-435c-bba8-2289ca1a96cc)
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/9c539e81-a5b2-475e-b8fd-657d8197ec9e)
![wazuh-remote_api_stats_TCP sessions](https://github.com/user-attachments/assets/c54b2e5b-6b8f-4799-bf1d-03403da3806f)


- Stats: logcollectord

![active-responses_log_Bytes sent](https://github.com/user-attachments/assets/4ded42f8-c746-41f9-9983-87804f4b2466)
![active-responses_log_Events dropped](https://github.com/user-attachments/assets/df113ca7-1a6a-468b-8b82-9bad444e2b2a)
![active-responses_log_Events generated](https://github.com/user-attachments/assets/ff3226a1-b58c-4f1f-878e-02e312f6e420)
![audit_log_Bytes sent](https://github.com/user-attachments/assets/9859fe19-b1bc-44e5-b4c7-c2d4c8c558fc)
![audit_log_Events dropped](https://github.com/user-attachments/assets/eacb6581-0b8e-4a4a-97b3-466547143e8f)
![audit_log_Events generated](https://github.com/user-attachments/assets/c24c1a2d-b817-4941-b34f-4f833f236264)
![df_Bytes sent](https://github.com/user-attachments/assets/c53061fa-24ec-43bc-a136-dd05ee87d2f5)
![df_Events dropped](https://github.com/user-attachments/assets/c4dc0bbc-7a48-4aa7-9050-ab1d169c67d5)
![df_Events generated](https://github.com/user-attachments/assets/14190ec2-d467-4108-b19f-309f6a3397b0)
![journald_Bytes sent](https://github.com/user-attachments/assets/1aafb869-5bc5-4d8e-b309-643ebc6f2976)
![journald_Events dropped](https://github.com/user-attachments/assets/564bf657-57b2-4a7a-a649-861e94ddd0ad)
![journald_Events generated](https://github.com/user-attachments/assets/f431dc4e-7551-493d-9d24-0356dca87e8e)
![last_Bytes sent](https://github.com/user-attachments/assets/c588d9f0-8ce9-495e-852a-2e797f437758)
![last_Events dropped](https://github.com/user-attachments/assets/acbf247a-980e-40d2-816d-f59343b39867)
![last_Events generated](https://github.com/user-attachments/assets/f8fd66f1-6b9b-4421-b911-cabc79b4d1db)
![netstat_Bytes sent](https://github.com/user-attachments/assets/daef2f0a-ddba-4c0b-8783-b34ec07c6542)
![netstat_Events dropped](https://github.com/user-attachments/assets/99e40711-c25a-4bc3-a5fc-8935922afa9f)
![netstat_Events generated](https://github.com/user-attachments/assets/bb7c7f36-5131-4902-a786-dfffe6e679e9)

</details>

<details><summary>Dashboard :black_circle: </summary>

- Binaries

![CPU](https://github.com/user-attachments/assets/d71f9ade-331d-434d-989f-1902461b562e)
![Disk_Read](https://github.com/user-attachments/assets/3d4ea893-ef68-4d94-b6c7-ca91f006cfd2)
![Disk_Read_Speed](https://github.com/user-attachments/assets/7c177ba0-de4e-4e18-9d2b-62c5f2fec650)
![Disk_Write_Speed](https://github.com/user-attachments/assets/814191fd-1a27-465f-9909-9f916d80af15)
![Disk_Written](https://github.com/user-attachments/assets/16b418e2-fcde-4cc2-9b94-2071ef4bcd5e)
![FD](https://github.com/user-attachments/assets/b1358abd-1f57-45ad-bf85-e2d50d26a727)
![PSS](https://github.com/user-attachments/assets/34aade13-566c-48cc-a891-845de232430e)
![Read_Ops](https://github.com/user-attachments/assets/813be0eb-87c4-4d4f-8a55-096e67eab12f)
![RSS](https://github.com/user-attachments/assets/81693a88-efbd-4d44-87c9-cc5b3885139e)
![SWAP](https://github.com/user-attachments/assets/e56a31cc-e89c-46f1-8426-2fcc3affcc81)
![USS](https://github.com/user-attachments/assets/df2a7cab-2e13-49c5-a50c-6b809e0e7ebf)
![VMS](https://github.com/user-attachments/assets/f75ead08-1c9c-4c55-964a-2cbfc396fc13)
![Write_Ops](https://github.com/user-attachments/assets/413611c6-8113-40ee-91d5-eb4f5f017011)


</details>

**Comment by MARCOSD4** [comment]
# High Activity

## Metrics and Statistics

<details><summary>Worker 1 :black_circle: </summary>

- Metrics:


- Statistics:


---

- Binaries

![CPU](https://github.com/user-attachments/assets/7a5bd978-a375-4cae-b163-f8e2c88fa1d6)
![Disk_Read](https://github.com/user-attachments/assets/62f27bcd-eeb6-4487-a1cf-c96f206db5d3)
![Disk_Read_Speed](https://github.com/user-attachments/assets/89a6058e-b3b0-4c34-a6de-a9633ff5eb98)
![Disk_Write_Speed](https://github.com/user-attachments/assets/4765ef84-9649-4c6e-b6ba-f848776f9c40)
![Disk_Written](https://github.com/user-attachments/assets/48e49b9c-6856-4862-9b9c-b2cda28b07eb)
![FD](https://github.com/user-attachments/assets/2224db09-0901-40ee-a2bf-0f8e2027d91f)
![PSS](https://github.com/user-attachments/assets/0a5a6186-816b-4851-adfb-48a43db2efaa)
![Read_Ops](https://github.com/user-attachments/assets/41cf8603-93ba-445e-a101-47c063cb21b5)
![RSS](https://github.com/user-attachments/assets/2048f1ea-fff5-4f8f-9f05-a686d50b8cfa)
![SWAP](https://github.com/user-attachments/assets/8ab54cab-5a6e-41cc-a5e5-98fc9c04f5d6)
![USS](https://github.com/user-attachments/assets/42a4ed49-0a79-4620-88c8-48fc3e1c4a15)
![VMS](https://github.com/user-attachments/assets/66a7c5d2-d388-4eab-a4dd-f92f4da7ba8e)
![Write_Ops](https://github.com/user-attachments/assets/f9c4f08b-3521-40dc-b377-b89b8afd82c6)


- Stats: wazuhdbd

![wazuh-wazuhdb_api_stats_Agent queries breakdown](https://github.com/user-attachments/assets/db007673-58de-489c-b042-6a464c77696d)
![wazuh-wazuhdb_api_stats_Agent tables breakdown](https://github.com/user-attachments/assets/b43f178f-97ef-4cff-ab27-80ff22ed5c41)
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/b6858d8f-e6b1-4f2a-885d-afef15c8e25c)
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/560fd99e-170d-415a-a9e7-9ecd7ac94185)
![wazuh-wazuhdb_api_stats_Global group queries](https://github.com/user-attachments/assets/92a73078-0a37-4624-99d8-64872f64fa03)
![wazuh-wazuhdb_api_stats_Global queries breakdown](https://github.com/user-attachments/assets/0712d54e-8631-4d20-bf41-4b56103df216)
![wazuh-wazuhdb_api_stats_Queries time metrics](https://github.com/user-attachments/assets/f3d6c5bf-7dfc-4f36-ab8e-cf7a43de2783)
![wazuh-wazuhdb_api_stats_Task queries breakdown](https://github.com/user-attachments/assets/bd1dafb6-c984-4a76-912b-8d2db9b792cd)

- Stats: remoted

![wazuh-remote_api_stats_Bytes received](https://github.com/user-attachments/assets/0005a9ee-b777-43bb-a7af-115b08a9687b)
![wazuh-remote_api_stats_Events sent and count](https://github.com/user-attachments/assets/4fc3e4c8-b2c6-4680-afc4-b5776e90654a)
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/ad9c6aed-2882-4bae-9a43-1886178dd7e8)
![wazuh-remote_api_stats_TCP sessions](https://github.com/user-attachments/assets/c81de8b7-bf2e-42f6-8674-a5cefaed60f3)

- Stats: logcollectord

![active-responses_log_Bytes sent](https://github.com/user-attachments/assets/27e7e39e-a735-4a64-8c4b-7c5741560735)
![active-responses_log_Events dropped](https://github.com/user-attachments/assets/85ad7486-4658-4e52-ab26-6890635da3ba)
![active-responses_log_Events generated](https://github.com/user-attachments/assets/45205afe-a021-47dd-8f30-14a02039490e)
![audit_log_Bytes sent](https://github.com/user-attachments/assets/377f6577-7c4c-4a9f-9fb5-f476cde8420e)
![audit_log_Events dropped](https://github.com/user-attachments/assets/d09657fc-9003-44f3-ad27-de1c5dc35307)
![audit_log_Events generated](https://github.com/user-attachments/assets/f91b6a53-e9eb-4cdf-9c44-26def61e4278)
![df_Bytes sent](https://github.com/user-attachments/assets/39e1c85c-f7db-436c-89ea-d277838f846d)
![df_Events dropped](https://github.com/user-attachments/assets/a0437bb6-71bf-4d17-9fda-e10f921b9a48)
![df_Events generated](https://github.com/user-attachments/assets/7a5534f4-669f-4535-bc0c-30277ca8a733)
![journald_Bytes sent](https://github.com/user-attachments/assets/0207012d-405b-42d1-9124-cb21c384bf5b)
![journald_Events dropped](https://github.com/user-attachments/assets/cf469908-426a-4456-aac8-4152e774c4e4)
![journald_Events generated](https://github.com/user-attachments/assets/7e5b2ca6-ac52-447b-9623-ae0655f65214)
![last_Bytes sent](https://github.com/user-attachments/assets/371f5d5b-7fdf-4509-a170-0182dc9e3f86)
![last_Events dropped](https://github.com/user-attachments/assets/c623cf7a-4bda-4476-b86a-6bbfdd6e62a2)
![last_Events generated](https://github.com/user-attachments/assets/91c8b128-7685-4b82-955b-230866f8a312)
![netstat_Bytes sent](https://github.com/user-attachments/assets/2c0aa5a7-b611-4e25-a66d-1d65d0d2cfca)
![netstat_Events dropped](https://github.com/user-attachments/assets/3481ff05-15fc-4ffd-bbf6-13c5be1c07b1)
![netstat_Events generated](https://github.com/user-attachments/assets/36da9a4d-6189-491f-bbd8-71ce1b98f0e7)

</details>

<details><summary>Worker 2 :black_circle: </summary>

- Metrics:


- Statistics:


---

- Binaries



- Stats: wazuhdbd


- Stats: remoted


- Stats: logcollectord


</details>

**Comment by MARCOSD4** [comment]
# High Activity

## Metrics and Statistics

<details><summary>Indexer 1 :black_circle: </summary>



---

- Binaries


- Stats


</details>

<details><summary>Indexer 2 :black_circle: </summary>



---

- Binaries


- Stats


</details>

## Vulnerabilities State :black_circle: 



## Alerts :black_circle:

**Comment by santipadilla** [comment]
# Very high Activity 
      
**Report**:

**Build:**: 

**Comparision** Compared with: https://github.com/wazuh/wazuh/issues/24504


***

## Logs :black_circle: 
 
### Summary


<details>

<summary> Master :black_circle: </summary>



```

```


```

```

</details>
 
<details>

<summary> Worker 1 :black_circle: </summary> 

- Expected errors:
```

```


```

```


</details>


<details>

<summary> Worker 2 :black_circle: </summary>


- Expected errors:

```

```


```

```


```

```

</details>



<details>

<summary> Indexer 0 :black_circle: </summary>

- Expected opensearch warnings:
```




```


```

```


```

```



```

```


```

```


```

```


```

```

</details>


<details>

<summary> Indexer 1 :black_circle: </summary>

- Expected opensearch warnings:
```




```


```

```



```

```


```

```


```

```


```

```

</details>


<details>

<summary> Dashboard :green_circle:  </summary>

- No logs

</details>

**Comment by MARCOSD4** [comment]
# Very High Activity

## Metrics and Statistics

<details><summary>Master :black_circle: </summary>

- Metrics:



- Statistics:



---

- Binaries



- Stats: wazuhdbd



- Stats: remoted



- Stats: logcollectord



</details>

<details><summary>Dashboard :black_circle: </summary>



</details>

**Comment by MARCOSD4** [comment]
# Very High Activity

## Metrics and Statistics

<details><summary>Workers :black_circle: </summary>



</details>

**Comment by MARCOSD4** [comment]
# Very High Activity

## Metrics and Statistics

<details><summary>Indexers :black_circle: </summary>



</details>


## Vulnerabilities State :black_circle: 



## Alerts :black_circle:

**Comment by santipadilla** [comment]
ETA increase due to relaunch of [very high activity](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/652/) case.

**Comment by MARCOSD4** [comment]
The last two builds launched for the Very High Activity test have failed, therefore, this test will not be analyzed in this stage. A last build has been launched to try to get the plots to be used for comparison of future versions. When finished, the results should be uploaded to the comments above.

Opened issues :red_circle: :

- https://github.com/wazuh/wazuh-jenkins/issues/6902
-
