### ISSUE TITLE
Footprint - Logcollector resource usage growth

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25410]
## Description

Testing: [Release 4.9.0 - RC 1 - Footprint Metrics - LOGCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/25387) in the CentOS Agent the following increase of logcollector could be registered

PSS
4.9.0-RC1
![image](https://github.com/user-attachments/assets/189a69d6-d548-4c94-b3ab-d22a7c916104)

4.8.1 RC2 
![image](https://github.com/user-attachments/assets/a4597e01-c932-4357-9366-14915e3b8613)

RSS
4.9.0-RC1
![image](https://github.com/user-attachments/assets/44a81bcd-3f60-4ddf-ac17-631c4cc7d49c)

4.8.1 RC2 
![image](https://github.com/user-attachments/assets/2ad716a7-1b01-40b6-89c8-1ba53211fd30)

USS
4.9.0-RC1
![image](https://github.com/user-attachments/assets/94bed1c2-0995-4ca3-8c9f-37ba69cb54f2)

4.8.1 RC2 
![image](https://github.com/user-attachments/assets/4e285e13-cfb3-4384-a40e-87b42579668e)

VMS
4.8.1 RC2 
![image](https://github.com/user-attachments/assets/a9a9ee96-fa40-4cee-aaaf-8e2a53823756)
4.9.0-RC1
![image](https://github.com/user-attachments/assets/a67783f9-776d-4b21-8bc4-fda499690f08)

Also in Ubuntu, the same increase of logcollector in VMS could be seen

It must be evaluated whether the increase (sometimes up to double its value) is an expected value.

**Comment by cborla** [comment]
## Analysis

### Configuration

Analyzing the initial test, some configuration differences are observed between the 2 tests.
- ossec.conf
  - syscollector and open-scap 
  ![image](https://github.com/user-attachments/assets/2cb66b4b-83ff-4b52-b88f-858bb2f19f00)
- internal_options.conf
  - No differences.
- local_internal_options.conf
  - No differences.

In this case, in 4.9.0 RC 1 the syscollector scan was performed every 60 seconds, while in 4.8.1 RC 2 it was every 10 seconds.

### Number of events generated

That's almost the same number of events generated

| 4.9.0 RC 1| 4.8.2 RC 2 |
|---|---|
| ![imagen](https://camo.githubusercontent.com/3060145acd93270b581c15dadb8128542fc7ce45c8a44a1d7dbc5ffee98c942e/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e392e302f42353531382d333630306d2f42353531385f6167656e745f63656e746f732f706c6f74732f546573745f7374726573735f42353531385f63656e746f735f6167656e74645f73746174655f4167656e74445f4e756d6265725f6f665f67656e6572617465645f6576656e74732e706e67) | ![imagen](https://camo.githubusercontent.com/a251dbdd386282aacc8b0431ca788d174530b12f541ff2d067975140c60c5141/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e382e312f42353338392d333630306d2f42353338395f6167656e745f63656e746f732f706c6f74732f546573745f7374726573735f42353338395f63656e746f735f6167656e74645f73746174655f4167656e74445f4e756d6265725f6f665f67656e6572617465645f6576656e74732e706e67) |

### Code difference between versions [v4.8.1...v4.9.0-rc1](https://github.com/wazuh/wazuh/compare/v4.8.1...v4.9.0-rc1)
The following PRs are the only ones that affect the agent. 

- Added Journald support in Logcollector. ([#23137](https://github.com/wazuh/wazuh/pull/23137))

### Memory usage statistics
Here the differences in percentages of the 2 versions can be seen.
![image](https://github.com/user-attachments/assets/9b7743ce-56e6-45d0-bede-e1ef7c0824c3)
The percentage increases of the memories can be seen below.
- RSS: 71 %
- VMS: 0 %
- USS: 69 %
- PSS: 74 %

### Similar test result
- For example in the [Release 4.9.0 - RC 1 - Footprint Metrics - LOGCOLLECTOR,SYSCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/25399#top) it's possible to see that the value of the PSS memory is at values like in 4.8.1.

 ![imagen](https://camo.githubusercontent.com/f6071f8c8f823402f1925a67ad5ed66de2d96791ddcf8d205b87fc43af623ed8/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e392e302f42353532342d333630306d2f42353532345f6167656e745f63656e746f732f706c6f74732f6d6f6e69746f722d6167656e742d546573745f7374726573735f42353532345f63656e746f732d7072652d72656c656173655f5053532e706e67)


### Conclusion
- We can highlight that no ramps are observed that represent memory allocation without returning at any stage of the test, not even in the stress test stage.
- The release and management of this type of memory depends on each OS.
- In other tests of the same version the values are similar to 4.8.1.
- The memory increase is around 70 % for all 3 cases, which denotes some general condition of the OS.
