### ISSUE TITLE
Increase in memory usage by wazuh_apid in Vulnerability Detection performance test

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh#25420]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.0  |  RC1  |  Development  |  Master  | Repository |  

## Description

During testing performed in https://github.com/wazuh/wazuh/issues/25403, an increase in different plots related to memory usage (FD, PSS, RSS, USS, and VMS) by the `wazuh_apid` daemon was detected in Master, both in the Medium Activity and High activity tests. This behavior has not been seen in previous versions or stages.

**Plots for Medium Activity test:**

<details><summary>4.9.0-RC1</summary>

![FD](https://github.com/user-attachments/assets/d6fb2761-8849-4f05-8573-b5d577306861)

![PSS](https://github.com/user-attachments/assets/79844a5f-d604-458d-8360-6c896c78f9d8)

![RSS](https://github.com/user-attachments/assets/bc5007d9-1c65-44fc-8334-62052fe2a108)

![USS](https://github.com/user-attachments/assets/9512b692-e8b5-413d-bd07-03a26cc406f0)

![VMS](https://github.com/user-attachments/assets/01bc9367-39b3-4b55-962d-9a7bdd4aa21f)

</details>

<details><summary>4.9.0-beta2</summary>

![FD](https://github.com/user-attachments/assets/c88db1a8-78f8-4d49-8a42-2f95633ae6b1)
![PSS](https://github.com/user-attachments/assets/0c5ce355-7eda-419e-8f8b-cab3aeabc9bd)
![RSS](https://github.com/user-attachments/assets/7e38b77c-a606-4796-8bdb-2789d46e83fa)
![USS](https://github.com/user-attachments/assets/ab5d3233-bd9b-462f-8383-200004e5ea46)
![VMS](https://github.com/user-attachments/assets/1dd95ec0-658c-4f6d-81fd-ac9c7125a429)

</details>

<details><summary>4.8.1-RC2</summary>

![FD](https://github.com/user-attachments/assets/ff165b92-8753-4b05-a8f1-27c8a96f9352)
![PSS](https://github.com/user-attachments/assets/ea664d92-3c7e-4e72-9d48-357aea3100b0)
![RSS](https://github.com/user-attachments/assets/8d93ecf5-0160-4e75-8113-91169535b4a0)
![USS](https://github.com/user-attachments/assets/9a40c622-1c37-4c96-a0da-068bfc1ddc8f)
![VMS](https://github.com/user-attachments/assets/87bd4d2d-38af-4e9d-992c-6b6dd75dcc4a)

</details>

The results for the High Activity test are similar but the increase in `wazuh_apid` occurs mainly at the beginning of the test.

**Plots for High Activity Test:**

<details><summary>4.9.0-RC1</summary>

![FD](https://github.com/user-attachments/assets/54028dd6-6cf6-4fbe-8d4b-34016c8af6ab)
![PSS](https://github.com/user-attachments/assets/14733538-9621-4632-b96e-723645f49b8e)
![RSS](https://github.com/user-attachments/assets/6b0df6e9-3aa2-4c54-bb54-5120102f7508)
![USS](https://github.com/user-attachments/assets/472c6a57-2207-4945-9de3-b4a3d23d4dd4)
![VMS](https://github.com/user-attachments/assets/7efe1cec-c9f9-4de6-a8c5-17cd39c5cb28)

</details>

<details><summary>4.9.0-beta2</summary>

![FD](https://github.com/user-attachments/assets/65430a83-1e13-47e8-9f06-396a9ec1e4f3)
![PSS](https://github.com/user-attachments/assets/18ecc7d5-7488-4da6-a36d-ac81fa6213f1)
![RSS](https://github.com/user-attachments/assets/31f6190c-885d-47fa-b46e-89d49bcdbc48)
![USS](https://github.com/user-attachments/assets/0667a65f-3b0f-4358-99e3-f54989fbd2e5)
![VMS](https://github.com/user-attachments/assets/4a4b547b-9385-4383-a90b-9814104b8de5)

</details>

<details><summary>4.8.1-RC2</summary>

![FD](https://github.com/user-attachments/assets/91216a69-54bc-4891-969d-c18fc9595258)
![PSS](https://github.com/user-attachments/assets/f39d119b-8f22-4bd3-8dac-51b003809c26)
![RSS](https://github.com/user-attachments/assets/e62adca2-d40c-441f-91f5-7b40fc063db2)
![USS](https://github.com/user-attachments/assets/253ecec9-a535-4bfd-b3f2-75ea529ca077)
![VMS](https://github.com/user-attachments/assets/27d842a6-8dbe-4b5e-8d78-6026d189d08e)

</details>

### Environment

The tests have been launched with the [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/) pipeline, using the following environment:

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |

## Steps to reproduce

To reproduce it, the pipeline must be executed making sure that the `KIBANA_API_REQUESTS` and `EXTRA_LOAD_API_REQUESTS` checks are enabled. Also, the parameters in the pipeline are as follows:

<details><summary>Build parameters</summary>

![image](https://github.com/user-attachments/assets/81dca7c7-29f9-49a6-88dd-f291cf0997e0)
![image](https://github.com/user-attachments/assets/608563e0-f505-49ff-a2fb-45676000bd26)
![image](https://github.com/user-attachments/assets/f8bc1127-31ac-43f4-9de4-50b75216824e)
![image](https://github.com/user-attachments/assets/74487f47-491d-4801-ac2e-8c058188b610)
![image](https://github.com/user-attachments/assets/8a35a83a-15f1-46f9-bffb-67a93f99f66d)

</details>

The type of load that the API supports depends on the environment, as indicated in the previous section. 

### Current result

The `wazuh_apid` daemon has high values in the plots above.

### Expected result

The plots should be similar to those obtained in 4.9.0-beta2 or 4.8.1-rc2, and the `wazuh_apid` values should be lower.

### Attachments

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/649/ and https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/650/
- Artifacts: [artifactsMediumTest.zip](https://github.com/user-attachments/files/16759342/artifacts1.zip) and [artifactsHighTest.zip](https://github.com/user-attachments/files/16759351/artifacts2.zip)

**Comment by GGP1** [comment]
## Update

I started comparing the high-activity results from the previous and current stages.

However, the team has decided to rollback the changes that made the cluster tasks asynchronous, so the results from these performance tests won't be taken into consideration.  This issue may now be closed.

### Notes

In spite of this, I leave some worth mentioning things I found by looking at the logs in case it's useful in the future.

- No changes were introduced in the API or cluster in the RC1 stage: https://github.com/wazuh/wazuh/compare/v4.9.0-beta2...v4.9.0-rc1

- Beta2 API logs show less activity. In beta2 we can see that the typical operation is 2 authentications + 2 requests:

  ```console
  2024/08/10 00:00:16 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.713s: 200
  2024/08/10 00:00:16 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.610s: 200
  2024/08/10 00:00:16 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.131s: 200
  2024/08/10 00:00:16 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.135s: 200
  ```

  While in RC1 there's one authentication and request more:

  ```console
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 1.233s: 200
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 1.199s: 200
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 1.200s: 200
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-remoted", "wait_for_complete": "true"} and body {} done in 0.135s: 200
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-db", "wait_for_complete": "true"} and body {} done in 0.166s: 200
  2024/08/26 12:20:18 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd", "wait_for_complete": "true"} and body {} done in 0.174s: 200
  ```

  This seems like a little change, but the test is now performing 50% more tasks.

- No timeout error was found in the API nor the cluster logs.

- In beta2, the `/cluster/configuration/validation` had a median time of ~1.3s, while in RC1 this time increased to ~3s.

- All cluster tasks finished within 400ms in both versions, `Agent-groups` being the only one that surpassed 100ms.

- In RC1, there are 9225 disconnections in the cluster logs, while in beta2 only 3946. This could be related to the increase in the tests operations mentioned before.

**Comment by javiersanchz** [comment]
## Review

LGTM !

**Comment by Rebits** [comment]
@GGP1 undibitable we can 

> Beta2 API logs show less activity. In beta2 we can see that the typical operation is 2 authentications + 2 requests:

Regarding the `wazu_api_simulator.log` we can see that both tests were launched indeed with the same parameters. 

<details>

<summary> RC 1: wazu_api_simulator.log</summary>


```shell
2024/08/26 07:10:40 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.2.194', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/26 07:10:40 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/26 07:10:40 INFO: [ExtraLoad] Initializing process
2024/08/26 07:10:40 INFO: [ExtraLoad] 5 requests per loop
2024/08/26 07:10:40 INFO: [ExtraLoad] Frequency: 60
2024/08/26 07:10:40 INFO: [ExtraLoad] Trying to obtain API token
2024/08/26 07:10:40 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/26 07:10:40 INFO: [Kibana] Initializing process
2024/08/26 07:10:40 INFO: [Kibana] 7 requests per loop
2024/08/26 07:10:40 INFO: [Kibana] Frequency: 60
```

</details>

<details>

<summary> Beta 2: wazu_api_simulator.log </summary>

```shell
2024/08/09 18:26:43 INFO: [Main] Loaded configuration file: {'remote': {'host': '172.31.9.58', 'port': 55000}, 'kibana': {'enabled': True}, 'extra_load': {'enabled': True, 'api_requests_percentage': 10}}
2024/08/09 18:26:43 INFO: [ExtraLoad] Loaded template in api_extra_load_template.yaml
2024/08/09 18:26:43 INFO: [ExtraLoad] Initializing process
2024/08/09 18:26:43 INFO: [ExtraLoad] 5 requests per loop
2024/08/09 18:26:43 INFO: [ExtraLoad] Frequency: 60
2024/08/09 18:26:43 INFO: [ExtraLoad] Trying to obtain API token
2024/08/09 18:26:43 INFO: [Kibana] Loaded template in api_kibana_template.yaml
2024/08/09 18:26:43 INFO: [Kibana] Initializing process
2024/08/09 18:26:43 INFO: [Kibana] 7 requests per loop
2024/08/09 18:26:43 INFO: [Kibana] Frequency: 60
```

</details>

However, it's clear the discrepancy between both tests (8315 request in Beta 2 vs 11822 in RC1). This could be related due to some error in the request of the analysisd, although no changes in the api configuration were performed. Further research is required and it will be carried on in  https://github.com/wazuh/wazuh-qa/issues/5706

**Comment by fdalmaup** [comment]
# Review

Thanks for the comment @Rebits. Great work @GGP1, the carried investigation may be helpful in the future, and as you mentioned, #25449 rollbacks the behavior of the cluster related to its tasks.

LGTM!

**Comment by pro-akim** [comment]
I reopen this issue since the analysis of https://github.com/wazuh/wazuh-qa/issues/5706#issuecomment-2337612569
validates what was reported in https://github.com/wazuh/wazuh-qa/issues/5706#issuecomment-2334427657

**Comment by GGP1** [comment]
These plots were generated in an outdated version that did not include the reversion of the cluster asynchronous changes, therefore, they won't be taken into account.

**Comment by fdalmaup** [comment]
Since v4.9.0 was released and given the changes not taken into account as mentioned by @GGP1, this issue will be closed. In case a similar behavior is seen in stages of upcoming releases, please open new issues mentioning this.
