### ISSUE TITLE
Wazuh DB Error when running Cluster reliability test - Perform testing over custom branch

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#25427]
## Description
To pinpoint the root cause of the behaviour described in this issue:
- https://github.com/wazuh/wazuh/issues/25212

[Here](ttps://github.com/wazuh/wazuh/issues/25212#issuecomment-2312870374), @pereyra-m proposes to re-run the tests in a custom branch, with these changes reverted:
- https://github.com/wazuh/wazuh/pull/22640

## DoD
- [ ] Test results are ready

**Comment by fdalmaup** [comment]
Given the revert of the changes in the cluster commands behavior carried out in https://github.com/wazuh/wazuh/issues/25449 and the upcoming release testing for `v4.9.0-rc2` to verify that the results of the performance and reliability tests are again within the expected ranges, we proceed to close this issue.
