### ISSUE TITLE
Install issue (no rule to make target 'external/cJSON/.o')

### ISSUE THREAD

**Issue by JSON-HSB** [wazuh/wazuh#25424]
On Debian 10 & Arch:
- git repo cloned ( also rescursively and also with depth set to 1 )
- inside src: sudo make deps
- curl doesnt have permissions to download `external/cJSON` and `shared_modules/http-request`
- downloading these manually
- sudo make deps
- sudo ./install.sh: `make: no rule to make target 'external/cJSON/.o', needed by 'external/cJSON//libcjson.a'`

_Originally posted by @JSON-HSB in https://github.com/wazuh/wazuh/issues/6099#issuecomment-2312597276_

**Comment by vikman90** [comment]
@JSON-HSB Currently, the `master` branch is used for active development of Wazuh version 5.0, which is still under development. This explains why `make` is not functioning as expected, as it is not yet fully operational.

To avoid this issue, I recommend cloning the latest stable release, which is version 4.9.0. You can do so by checking out the corresponding tag with the following commands:

```bash
git clone --branch v4.9.0 https://github.com/wazuh/wazuh.git
```

This version is fully functional and should not encounter the problems you're experiencing. If you continue to have any issues or need further assistance, feel free to reach out.

Thank you for your understanding.
