### ISSUE TITLE
Failed to sync agent with the indexer (4.8.2)

### ISSUE THREAD

**Issue by VenkataPatrana** [wazuh/wazuh#25435]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.2| Wazuh Indexer | Manager | Packages (All in one Deployment) | Amazon Linux 2 |

### Description

After upgrading the [Wazuh central components](https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html) from version 4.7 to 4.8.2, we noticed warning messages for some of the agents. We attempted to upgrade one of the agents to version 4.8.2, but the same WARNING message still appears.

```
Aug 27, 2024 @ 18:11:46.000 indexer-connector WARNING Failed to sync agent '014' with the indexer.
Aug 27, 2024 @ 18:11:42.000 indexer-connector WARNING Failed to sync agent '006' with the indexer.
Aug 27, 2024 @ 18:11:11.000 indexer-connector WARNING Failed to sync agent '016' with the indexer.
Aug 27, 2024 @ 18:11:03.000 indexer-connector WARNING Failed to sync agent '015' with the indexer.
Aug 27, 2024 @ 18:09:59.000 indexer-connector WARNING Failed to sync agent '007' with the indexer.
Aug 27, 2024 @ 18:08:41.000 indexer-connector WARNING Failed to sync agent '012' with the indexer.
```

**Comment by MiguelazoDS** [comment]
Hi @VenkataPatrana, 

Did you configure the indexer block in your `ossec.conf` configuration file? if the indexer connector cannot communicate with the indexer, those messages are expected. 

Please take a look at

https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html#configuring-vulnerability-detection

**Comment by VenkataPatrana** [comment]
@MiguelazoDS Yes, the indexer block is configured according to the documentation, but we're still seeing these warning messages for some agents (though not all).

`  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://127.0.0.1:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/filebeat/certs/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/filebeat/certs/wazuh-server.pem</certificate>
      <key>/etc/filebeat/certs/wazuh-server-key.pem</key>
    </ssl>
  </indexer>`

**Comment by MiguelazoDS** [comment]
Take into account that the IP as well as the certificates may differ in your environment, did you check that the indexer is indeed connected? 

Please add `wazuh_modules.debug=2` in your local_internal_configuration.conf file and restart your manager. 

grep and share the logs for `"indexer-connector" `

**Comment by VenkataPatrana** [comment]
@MiguelazoDS here is the Debug log 
```
{"timestamp":"2024/08/29 17:08:02","tag":"indexer-connector","pid":17823,"file":"indexerConnector.cpp","line":437,"routine":"operator()","level":"debug","description":"Syncing agent '034' with the indexer."}
{"timestamp":"2024/08/29 17:08:02","tag":"indexer-connector","pid":17823,"file":"indexerConnector.cpp","line":446,"routine":"operator()","level":"warning","description":"Failed to sync agent '034' with the indexer."}
{"timestamp":"2024/08/29 17:08:02","tag":"indexer-connector","pid":17823,"file":"indexerConnector.cpp","line":447,"routine":"operator()","level":"debug","description":"Error: No available server"}
{"timestamp":"2024/08/29 17:08:02","tag":"indexer-connector","pid":17823,"file":"indexerConnector.cpp","line":129,"routine":"abuseControl","level":"debug","description":"Agent '034' sync omitted due to abuse control."}
```

**Comment by MiguelazoDS** [comment]
> Error: No available server

It cannot connect to the server. 

Try this curl command from the command line to validate your configuration 

`curl --cacert <cacertpath> --cert <certpath> --key <keypath> -u <user:pass> -XGET https://<IP>:9200/_cluster/health`

Replace the values for those options according to your environment.

**Comment by VenkataPatrana** [comment]
Not sure what's the issue, some agents can connect and sync with indexer but not all
_Cluster health is in Yellow status_

```
{
  "cluster_name": "wazuh-cluster",
  "status": "yellow",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "discovered_master": true,
  "discovered_cluster_manager": true,
  "active_primary_shards": 804,
  "active_shards": 804,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 3,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 99.62825278810409
}
```

**Comment by VenkataPatrana** [comment]
And the reason for yellow status is
```
{
  "index": ".opendistro-alerting-alerts",
  "shard": 0,
  "primary": false,
  "current_state": "unassigned",
  "unassigned_info": {
    "reason": "CLUSTER_RECOVERED",
    "at": "2024-08-23T20:01:55.986Z",
    "last_allocation_status": "no_attempt"
  },
  "can_allocate": "no",
  "allocate_explanation": "cannot allocate because allocation is not permitted to any of the nodes",
  "node_allocation_decisions": [
    {
      "node_id": "xxxxxxxxxx",
      "node_name": "node-1",
      "transport_address": "127.0.0.1:9300",
      "node_attributes": {
        "shard_indexing_pressure_enabled": "true"
      },
      "node_decision": "no",
      "deciders": [
        {
          "decider": "same_shard",
          "decision": "NO",
          "explanation": "a copy of this shard is already allocated to this node [[.opendistro-alerting-alerts][0], node[xxxx], [P], s[STARTED], a[id=xxxxx]]"
        }
      ]
    }
  ]
}
```

**Comment by MiguelazoDS** [comment]
Great! thanks for the information. 

The reason for this 

> Not sure what's the issue, some agents can connect and sync with indexer but not all
Cluster health is in Yellow status

it is because we found that endpoints are being considered active even if they are in yellow state, which causes sometimes to work even if the cluster is not green. The team is working on that to avoid indexing on yellow clusters.

Let's try this from the elastic forum. 

> This is a replica, but you only have one node, so of course no replicas can be allocated. You should set number_of_replicas: 0 on all your indices.

https://discuss.elastic.co/t/the-shard-cannot-be-allocated-to-the-same-node-on-which-a-copy-of-the-shard-already-exists/233133/2

The setting he's mentioning is this where "*" is your index. 

```
PUT /*/_settings
{
  "index" : {
    "number_of_replicas" : 0
  }
}
```

some more details can be found here 

https://opensearch.org/docs/1.3/api-reference/index-apis/create-index/

![image](https://github.com/user-attachments/assets/639ac137-26df-463f-9b37-686b854351fd)

**Comment by VenkataPatrana** [comment]
@MiguelazoDS I tried to update the index settings with default Admin user but for some reason I am getting permissions error.

```
PUT /.opendistro-alerting-alerts/_settings
{
  "index" : {
    "number_of_replicas" : 0
  }
}

```
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
      }
    ],
    "type": "security_exception",
    "reason": "no permissions for [] and User [name=admin, backend_roles=[admin], requestedTenant=null]"
  },
  "status": 403
}
```

**Comment by MiguelazoDS** [comment]
Please try with Curl command in the terminal the same way you did before. I would try something like this 

```
curl --cacert <cacertpath> --cert <certpath> --key <keypath> -X PUT "https://<IP>:9200/*/_settings" -H 'Content-Type: application/json' -d '{
  "index" : {
    "number_of_replicas" : 0
  }
}'
```

**Comment by VenkataPatrana** [comment]
@MiguelazoDS Thanks, I was able to update the Index replica settings from terminal. After that, I don't see agent sync warning messages and cluster health is in GREEN status

**Comment by MiguelazoDS** [comment]
Glad to know that @VenkataPatrana! Regards!

**Comment by Adanmage** [comment]
curl --cacert <cacertpath> --cert <certpath> --key <keypath> -X PUT "https://<IP>:9200/*/_settings" -H 'Content-Type: application/json' -d '{
  "index" : {
    "number_of_replicas" : 0
  }
}'
I have no idea where to find my path. Can anyone help me?
