### ISSUE TITLE
Revert cluster commands asynchronous behavior

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25449]
## Description

In https://github.com/wazuh/wazuh/issues/21862, the following tasks related to `wazuh-db` stopped running in the process pool to start running asynchronously:
- `Sendsync`
- `Agent-info sync`
- `Agent-groups recv` 
- `Agent-groups recv full` 

The changes generated several performance and behavioral issues, like the one detailed [here](https://github.com/wazuh/wazuh/issues/25212#issuecomment-2315343062), since `wazuh-db` is not prepared for these asynchronous calls.

This issue aims to revert the changes introduced in the associated PRs (https://github.com/wazuh/wazuh/pull/22640 and https://github.com/wazuh/wazuh-documentation/pull/7173) from the `4.9.0` and the following `4.x` Wazuh versions.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment]
## Update

Reverted the changes from the cluster code and the documentation.
