### ISSUE TITLE
Wazuh Agent Crash at Syscollector

### ISSUE THREAD

**Issue by weeix** [wazuh/wazuh#25440]
### Discussed in https://github.com/wazuh/wazuh/discussions/20382

<div type='discussions-op-text'>

<sup>Originally posted by **str4int** November 23, 2023</sup>
Dear Community,

I've question about wazuh agent v4.6.0 on **virutal** windows 10 entrerprise 22H2.
I install wazuh form command line and by msi but same behavior.
When the service _WazuhSvc_ is started it stop righ after.

I have this event from windows:
    _Faulting application path: C:\Program Files (x86)\ossec-agent\wazuh-agent.exe
    Faulting module path: C:\Program Files (x86)\ossec-agent\sysinfo.dll_

strangely into ossec.log i dont find any Error or Warning.
sysinfo seems to be verify properly:
    _- wazuh-agent[0] cryptography.c:541 at verify_hash_and_pe_signature(): DEBUG: PE signature verification succeeded for C:\Program 
    Files (x86)\ossec-agent\sysinfo.dll
    - wazuh-agent[0] dll_load_notify.c:101 at dll_notification(): DEBUG: The file 'C:\Program Files (x86)\ossec-agent\sysinfo.dll' is signed 
    and its signature is valid._

FYI, i don't have any issue on server.
Do you know what it could be ?

Best,

</div>

<sup>[Patch provided by **JBent90914** August 27, 2024](https://github.com/wazuh/wazuh/discussions/20382#discussioncomment-10458392)</sup>
> From MSDN, both gmtime() and localtime() can (and likely will) return NULL.
> 
> https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/gmtime-gmtime32-gmtime64?view=msvc-170
> 
> https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=msvc-170
> 
> If an installed package has an install date outside those ranges, the Utils::getTimestamp() call in timeHelper.h will fail.
> 
> Patch below.
> 
> ```
> diff -ruN wazuh-4.8.2/src/shared_modules/utils/timeHelper.h new/src/shared_modules/utils/timeHelper.h
> --- wazuh-4.8.2/src/shared_modules/utils/timeHelper.h   2024-08-19 12:13:17.000000000 -0400
> +++ new/src/shared_modules/utils/timeHelper.h   2024-08-27 00:02:36.065955978 -0400
> @@ -29,6 +29,10 @@
>          std::stringstream ss;
>          // gmtime: result expressed as a UTC time
>          tm* localTime {utc ? gmtime(&time) : localtime(&time)};
> +
> +        // Return "invalid" timestamp, if the input is invalid.
> +        if (localTime == NULL) { return("1970/01/01 00:00:00"); }
> +
>          // Final timestamp: "YYYY/MM/DD hh:mm:ss"
>          // Date
>          ss << std::setfill('0') << std::setw(4) << std::to_string(localTime->tm_year + 1900);
> ```

**Comment by vikman90** [comment]
@weeix Thank you very much for opening the issue, conducting such a detailed investigation, and providing a fix. We will work immediately to resolve this.

## Update on My Work

I have uploaded the corresponding fix, but I have discovered that the versions of `gmtime` and `localtime` currently in use are not reentrant, which could potentially cause a race condition. Therefore, I will adapt the code to use the reentrant versions of these functions:
- `gmtime_r` and `localtime_r` on UNIX.
- `gmtime_s` and `localtime_s` on Windows.

The next step will be to extend the unit test suite to cover this case.

**Comment by vikman90** [comment]
## Update

- Updated unit tests for this change.
- https://github.com/wazuh/wazuh/pull/25469

Next:

- Port this change to the new Agent repository: [wazuh-agent](https://github.com/wazuh/wazuh-agent).

**Comment by vikman90** [comment]
## Update

- Applied code review.
- Extended the fix to similar functions: `getCompactTimestamp()`, `getCurrentISO8601()`, `timestampToISO8601()`, and `rawTimestampToISO8601()`.
- Ported to wazuh-agent: https://github.com/wazuh/wazuh-agent/pull/111
