### ISSUE TITLE
No report feature in vulnerability detection module

### ISSUE THREAD

**Issue by mojrhmwork** [wazuh/wazuh#25442]
|Wazuh version 4.8.2 |Component Vulnerability detector|assisted installation|Linux/Open search|

Since the changes from earlier version took place to version 4.8.1 and 4.8.2 , i can not find the generate report feature in vulnerability detection module.
There used to be a button to generate report based on vulnerability detection findings on related agents.

Is there a way to enable this feature or is this a bug ?

**Comment by pereyra-m** [comment]
Hi @mojrhmwork 

Can you give more details about the report feature you are looking for? Remember that the vulnerability detection module has been refactored in v4.8.0.

The inventory tab allows to export the current vulnerabilities for the agents in csv format

![2024-08-28_20-31](https://github.com/user-attachments/assets/56984b9a-a2e4-4757-badc-23532ae5358c)

**Comment by VenkataPatrana** [comment]
is there way to filter Dashboard / Inventory with end point group name or Labels?

**Comment by pereyra-m** [comment]
Hello @VenkataPatrana 

The agents groups aren't currently added to the indexed vulnerabilities, but that isn't related to the report feature.
Here you have another issue where this problem is being discussed:
- https://github.com/wazuh/wazuh/issues/24118

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary
