### ISSUE TITLE
Missing FIM events in Whodata with symbolic links

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#2547]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager/Agent | Packages/Sources | Linux |

Whodata is not reporting file creation events when the given path starts with a symbolic link.

If we add the following configuration:
```
lrwxrwxrwx   1 root root     1 Feb  8 17:00 external -> /
```
**ossec.conf**
```
<syscheck>
...
    <directories check_all="yes" whodata="yes">/external/home/user/test</directories>
...
</syscheck>
```

The folder is correctly added in Audit:
```
# auditctl -l

-w /external/home/user/test -p wa -k wazuh_fim
```

but the event generated doesn't include the full path and it is not matched in the syscheck database:

```
2019/02/08 17:26:18 ossec-syscheckd[24263] syscheck_audit.c:717 at audit_parse(): DEBUG: audit_event: uid=root, auid=root, euid=root, gid=root, pid=28964, ppid=28869, inode=1845724, path=/home/user/test/tes_file, pname=/bin/bash
```

**Comment by santiago-bassett** [comment]
Just to add more context, I believe the issue occurs when we monitor a directory, that depends on a symbolic link as a parent directory. For example

directory I want to monitor: /home/santiago/directory
symbolic link: /link -> /home/santiago
syscheck entry: /link/directory

I hope it helps
