### ISSUE TITLE
Content Updater - Add new component tests

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#25478]
## Description
To validate the behaviour detected in the following issue:
- https://github.com/wazuh/cti/issues/477

And validated in the next one:
- https://github.com/wazuh/internal-devel-requests/issues/1506

We need to add component tests over the content updater module to verify its behaviour

## DoD
- [ ] Added new component test

**Comment by pereyra-m** [comment]
## Update

I start the test implementation.

**Comment by pereyra-m** [comment]
## Update

The test is on hold until the issue can be manually reproduced and fiixed
- https://github.com/wazuh/wazuh/issues/25560

**Comment by pereyra-m** [comment]
## Update

I couldn't reproduce the issue with a deterministic procedure, see https://github.com/wazuh/wazuh/issues/25560#issuecomment-2327803025.

I propose to validate this fix by manual testing, in the environments where it originally failed.

**Comment by sebasfalcone** [comment]
## Update
I was able to reproduce the issue consistently as we can see here:
- https://github.com/wazuh/wazuh/pull/25565#pullrequestreview-2287269622

We will continue to pursue this issue to determine the root cause

**Comment by sebasfalcone** [comment]
## ETA updated
We are still unable to determine the root cause, ETA updated to give more time for it

**Comment by sebasfalcone** [comment]
## Closing issue
We are closing this issue, as all related tests will be implemented in this issue needed:
- https://github.com/wazuh/wazuh/issues/25560
