### ISSUE TITLE
Set default values for vulnerability severity empty fields

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25484]
## Description
This issue aims to for fields that lack values (`score.base`, `score.version`, `severity`, `classification`), automatically assign a hyphen (-) as a placeholder.

Note: depending on the field type, a '-' might be an unrepresentable value. For example, in a numeric field we might use -1 or other values as a '-' cannot be indexed. Review this with @wazuh/devel-indexer

## Expected
The empty fields for vulnerability events and alerts are filled with '-' or '-1'

>[!IMPORTANT]
> Apply this logic to:
> - [cveSolvedAlertDetailsBuilder](https://github.com/wazuh/wazuh/blob/v4.8.2/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cveSolvedAlertDetailsBuilder.hpp)
> - [eventPackageAlertDetailsBuilder](https://github.com/wazuh/wazuh/blob/v4.8.2/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventPackageAlertDetailsBuilder.hpp)
> - [scanOsAlertDetailsBuilder](https://github.com/wazuh/wazuh/blob/v4.8.2/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanOsAlertDetailsBuilder.hpp)

**Comment by sebasfalcone** [comment]
## ETA  delayed
Due to [urgent priority issues](https://github.com/wazuh/wazuh/issues/25212), this ETA was delayed

**Comment by GabrielEValenzuela** [comment]
# Update

- Filling all fields that are missing with '-'

**Comment by sebasfalcone** [comment]
## ETA updated
Issue delayed due to other tasks being done in parallel

**Comment by GabrielEValenzuela** [comment]
# Update

- Code complete, pending reformat UT

**Comment by GabrielEValenzuela** [comment]
# Update

- Add helper based on review comments.
- Add UT case

**Comment by sebasfalcone** [comment]
## ETA updated
Definitions for this issue have changed by managment, updating ETA without updating ETA cycles

**Comment by GabrielEValenzuela** [comment]
# Update

- Refactoring due change of requeriments

**Comment by GabrielEValenzuela** [comment]
# Update

- Refactoring due to change of requirements. Back to previous logic. Correct entries.
