### ISSUE TITLE
Add ADP source field into the vulnerability state

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25480]
## Description
This issue aims to Introduce/populate a field called `vulnerability.scanner.source` to capture the origin of the decision of the scanner (AKA feed used to detect the vulnerability).

## Expected
- The field `vulnerability.scanner.source` is added to the vulnerabilities inventory (see [eventDetailsBuilder](https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp))
- This field is loaded with the name of the CNA (see [packageScanner](https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp#L697-L698) and [osScanner](https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/osScanner.hpp#L280-L281)) in a human-readable form.

Consider using a base-rules map to populate the source field information, we can use the **subshortname** as the key.

Example:
```json
{
	"alas": "Human readable text",
	"almalinux": "Human readable text",
	"arch": "Human readable text",
	"debian": "Human readable text",
	"npm": "Human readable text",
	"nvd": "Human readable text",
	"pypi": "Human readable text",
	"redhat": "Human readable text",
	"rocky": "Human readable text",
	"suse": "Human readable text",
	"canonical": "Human readable text"
}
```

> [!IMPORTANT]
> Align this map with the one proposed [here](https://github.com/wazuh/wazuh/issues/25481) (we can create an object for each key to hold this information)

**Comment by MiguelazoDS** [comment]
# Update 

The changes are returning the expected value. More testing will be needed to ensure everything works as expected. This issue will be set on hold. I'm addressing higher-priority issues. 

![image](https://github.com/user-attachments/assets/8bf08a2a-3c5a-4afe-9a0b-40b6612dde27)
![image](https://github.com/user-attachments/assets/b57a1187-c80d-4975-afa3-75951c33e821)

**Comment by MiguelazoDS** [comment]
# Update 

Resuming this issue

**Comment by AlexRuiz7** [comment]
Some suggestions:

- Consider renaming that field to `cna`, to properly reference it.
- Consider adding it to the `vulnerability` object, as this is a property of the CVE event generated by Wazuh, not something related to the `Wazuh` object, used to contain information about the deployment.

It would look like:

`vulnerability.scanner.cna` or `vulnerability.scanner.source`

**Comment by MiguelazoDS** [comment]
@AlexRuiz7 I only see vulnerability.scanner.vendor in the ECS. Is it possible to add a field like that? Isn't that the reason we use the "Wazuh" object?

**Comment by AlexRuiz7** [comment]
We can add custom values wherever we want, as far as it makes sense with the rest of the information.

**Comment by MiguelazoDS** [comment]
@AlexRuiz7 Well, we can discuss the best way to show that information. That will change the requirements for this issue. @sebasfalcone @Dwordcito, what do you think?

**Comment by Dwordcito** [comment]
@AlexRuiz7 The intention of the wazuh object is to diverge from what was specified in the ECS, although your idea does not seem bad to me, it is what I discussed with Gabriel and Javier, in any case I will insist with your question tomorrow.

Regarding whether CNA or source, the correct thing is that it is "source" since the term CNA does not have to do with the origin of the data, but rather with the fact that certain authorities wrote that data in a single repository (NVD), The case of the ADP's is oriented towards organizations that give more value to elements published by authorities that numbered a CVE.

**Comment by sebasfalcone** [comment]
## Definition update
@MiguelazoDS We decided to change the field from `vulnerability.scanner.source` to `vulnerability.scanner.source`

**Comment by MiguelazoDS** [comment]
## Update 

Windows package 
![image](https://github.com/user-attachments/assets/84113310-be37-483e-80fe-e1d3683e6b45)

Centos package
![image](https://github.com/user-attachments/assets/f354464c-bbdc-4a27-98ff-f7e3bf26b2b9)

Windows OS
![image](https://github.com/user-attachments/assets/9d2635f7-c03d-4462-be6e-4d9ba8a0694b)

**Comment by AlexRuiz7** [comment]
New index template at https://github.com/wazuh/wazuh-indexer/pull/383

**Comment by MiguelazoDS** [comment]
There's something wrong with Windows 

```console
2024/09/09 13:46:23 wazuh-modulesd:vulnerability-scanner[101447] scanOrchestrator.hpp:153 at operator()(): ERROR: Error processing delayed event: [json.exception.out_of_range.403] key '' not found.
2024/09/09 13:46:24 wazuh-modulesd:vulnerability-scanner[101447] versionMatcher.hpp:200 at createVersionObject(): DEBUG: Error creating VersionObject (DPKG). Version string doesn't match the specified type. Version string: (4.0)
2024/09/09 13:46:24 wazuh-modulesd:vulnerability-scanner[101447] packageScanner.hpp:688 at operator()(): DEBUG: Failed to scan package: 'firefox', CVE Numbering Authorities (CNA): 'nvd', Error: 'Unable to compare versions (129.0.2 vs (4.0)).'
2024/09/09 13:46:24 wazuh-modulesd:vulnerability-scanner[101447] versionMatcher.hpp:200 at createVersionObject(): DEBUG: Error creating VersionObject (DPKG). Version string doesn't match the specified type. Version string: (4.0)
2024/09/09 13:46:24 wazuh-modulesd:vulnerability-scanner[101447] packageScanner.hpp:688 at operator()(): DEBUG: Failed to scan package: 'firefox', CVE Numbering Authorities (CNA): 'nvd', Error: 'Unable to compare versions (129.0.2 vs (4.0)).'
2024/09/09 13:46:24 wazuh-modulesd:vulnerability-scanner[101447] scanOrchestrator.hpp:153 at operator()(): ERROR: Error processing delayed event: [json.exception.out_of_range.403] key '' not found.
```

**Comment by MiguelazoDS** [comment]
## Update 

Ready for review. Suggested changes, implemented

**Comment by sebasfalcone** [comment]
## ETA updated
ETA updated to accommodate for reviews

**Comment by sebasfalcone** [comment]
## Issue blocked
We are awaiting the new map to be available in the content

**Comment by sebasfalcone** [comment]
## Update
Tests are still failing. The generated content is still outdated

We invalidated the caché in CloudFront:
- https://github.com/wazuh/internal-devel-requests/issues/1576

But seems like it didn't work out

## Release
@Dwordcito Code delivery for 4.10.0 is today but this issue didn't allow us to proceed

**Comment by sebasfalcone** [comment]
## Update
The issue is on hold, we are fixing the efficacy tests

**Comment by sebasfalcone** [comment]
## Update
Efficacy tests fixed on this PR:
- https://github.com/wazuh/wazuh/pull/25775

We are waiting for the upward merge from 4.9.1 into 4.10.0 to finish this task
