### ISSUE TITLE
Populate vulnerability object with adp context

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25481]
## Description
For ADPs with a CVSS score and description information, populate the associated vulnerability information with that in place of the NVD data. If the ADPs description column family does not have that information, proceed with NVD.

### Considerations
- SuSe, RedHat and AmazonLinux feeds most of the time contain this information
- The rest of the feeds don't contain this information
- When the description has "not defined", we will take the description information from NVD.

## Vendors status

|  Vendor   |                                                     CVSS                                                     |                  Description                  |
|-----------|--------------------------------------------------------------------------------------------------------------|-----------------------------------------------|
| ALAS      | Does not contain.                                                                                            | Contains.                                     |
| ALMA      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| ARCH      | Does not contain.                                                                                            | Contains with a default value ("not defined") |
| Canonical | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| Debian    | Does not contain.                                                                                            | Contains.                                     |
| NVD       | Contains.                                                                                                    | Contains.                                     |
| Oracle    | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains with a default value ("not defined") |
| npm       | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| pypi      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| RedHat    | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| Rocky     | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| SUSE      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |

## Expected
- The CVSS score and description information are obtained from the ADP. If it's not available, the NVD is used instead

Consider using a base-rules map that expresses the status of this information for each feed, we can use the **subshortname** as the key.

Examples:

```json
{
    "alas":
    {
        "description": "nvd",
        "cvss": "alas"
    },
    "almalinux":
    {
        "description": "almalinux",
        "cvss": "almalinux"
    },
    "arch":
    {
        "description": "nvd",
        "cvss": "nvd"
    },
    "debian":
    {
        "description": "nvd",
        "cvss": "debian"
    },
    "oracle":
    {
        "description": "nvd",
        "cvss": "oracle"
    }
    "npm":
    {
        "description": "npm",
        "cvss": "npm"
    },
    "nvd":
    {
        "description": "nvd",
        "cvss": "nvd"
    },
    "pypi":
    {
        "description": "pypi",
        "cvss": "pypi"
    },
    "redhat":
    {
        "description": "redhat",
        "cvss": "redhat"
    },
    "rocky":
    {
        "description": "rocky",
        "cvss": "rocky"
    },
    "suse":
    {
        "description": "suse",
        "cvss": "suse"
    },
    "canonical":
    {
        "description": "canonical",
        "cvss": "canonical"
    }
}
```

> [!IMPORTANT]
> Align this map with the one proposed [here](https://github.com/wazuh/wazuh/issues/25480) (we can create an object for each key to hold this information)

**Comment by pereyra-m** [comment]
## Update

I begin to analyze the issue and related ones.

**Comment by pereyra-m** [comment]
## Update

After discussing some details with the team, I continue with the implementation.

**Comment by pereyra-m** [comment]
Hi @Dwordcito, I have a question.

When you say

> Important
Align this map with the one proposed https://github.com/wazuh/wazuh/issues/25480 (we can create an object for each key to hold this information)

Can we merge both in the same file?
Something like

```json
{
    "alas":
    {
        "description": "nvd",
        "cvss": "alas",
        "adp_name" : "Human readable text"
    },
```

**Comment by pereyra-m** [comment]
Hi again @Dwordcito 

Another question related to this.

Should we consider only the ADPs listed in the issue or we should add those expanded by `base-rules/cna-mapping-global.json` ?

To be more clear, the `getCNA()` method at `src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/packageScanner.hpp` selects the CNA/ADP to use according to `base-rules/feed-global.json` but then expands this with `base-rules/cna-mapping-global.json`.

Should the feature requested here allow a more granular selection (for example `redhat_8`, `redhat_9` ) or we consider all `redhat` versions with the same CVSS/description mapping?

**Comment by pereyra-m** [comment]
## Update

I've analyzed the code, and considering that `storeVulnerabilityDescription()` only stores the CNA information, I propose to create another issue to include the ADPs information also.
I'll propose an approach to include the missing information.

**Comment by pereyra-m** [comment]
## Update

I keep working on the addition of the ADP descriptions to the scanner internal DB.

**Comment by pereyra-m** [comment]
## Update

I continue with the development. I've tested the local changes to update the descriptions' DB and its size is almost 6GB. Now I'm updating the required methods to build the description from different sources.

**Comment by pereyra-m** [comment]
## Update

I took more time than expected to adjust the branch to the changes at #25480. Also, I add the UT to verify the case of the "not defined" description. Now I'll compare the resulting alerts for some agents.

**Comment by sebasfalcone** [comment]
## ETA update
Updated ETA to accommodate for the final review

**Comment by sebasfalcone** [comment]
## Issue blocked
We are awaiting the new map to be available in the content

**Comment by sebasfalcone** [comment]
## Update
Tests are still failing. The generated content is still outdated

We invalidated the caché in CloudFront:
- https://github.com/wazuh/internal-devel-requests/issues/1576

But seems like it didn't work out

## Release
@Dwordcito Code delivery for 4.10.0 is today but this issue didn't allow us to proceed

**Comment by sebasfalcone** [comment]
## Update
The issue is on hold, we are fixing the efficacy tests

**Comment by sebasfalcone** [comment]
## Update
Efficacy tests fixed on this PR:
- https://github.com/wazuh/wazuh/pull/25775

We are waiting for the upward merge from 4.9.1 into 4.10.0 to finish this task

**Comment by pereyra-m** [comment]
## Update

Rebase and rerun test

**Comment by pereyra-m** [comment]
## Update

I fix the compilation and the failed UT.

**Comment by sebasfalcone** [comment]
## ETA delayed
Changes requested by the reviewer have to be trougly tested and implemented

**Comment by GabrielEValenzuela** [comment]
# Update

- Work almost done. Working in UT refactoring.

**Comment by GabrielEValenzuela** [comment]
# Update

- Pending review. UT refactoring done.

**Comment by sebasfalcone** [comment]
## ETA update
We won't make it to the proposed ETA

Testing wasn't succesfull
