### ISSUE TITLE
Introduce vulnerability evaluation status

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25482]
## Description
This issue aims to add a new field to indicate whether a vulnerability is disputed or under evaluation (When the vulnerability is in the status Awaiting analysis (NVD) and the ADP does not have that information), `vulnerability.under_evaluation`

> [!IMPORTANT]
> We can identify vulnerabilities under evaluation by checking if the vulnerability doesn't have a vulnerability score (is equal to 0), this comparison is with the flatbuffer result of the getDescription Call
> ![image](https://github.com/user-attachments/assets/871afed7-c802-47ae-b77f-7b60fea4387c)
> ![image](https://github.com/user-attachments/assets/9e9de682-33ba-4b2f-b349-a761697ca38b)
> ![image](https://github.com/user-attachments/assets/961162e6-655b-47e3-af13-7d50ce4daf01)
> ![image](https://github.com/user-attachments/assets/c017c001-1e5b-4c6f-91fb-91e11eb56d98)

## Vendors status

|  Vendor   |                                                     CVSS                                                     |                  Description                  |
|-----------|--------------------------------------------------------------------------------------------------------------|-----------------------------------------------|
| ALAS      | Does not contain.                                                                                            | Contains.                                     |
| ALMA      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| ARCH      | Does not contain.                                                                                            | Contains with a default value ("not defined") |
| Canonical | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| Debian    | Does not contain.                                                                                            | Contains.                                     |
| NVD       | Contains.                                                                                                    | Contains.                                     |
| Oracle    | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains with a default value ("not defined") |
| npm       | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| pypi      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| RedHat    | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| Rocky     | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |
| SUSE      | Contains. Does not include the "format" field, and note that CVSS information is not available for all CVEs. | Contains.                                     |

## Expected
- The field `wazuh.vulnerability.under_evaluation` is added to the vulnerabilities inventory (see [eventDetailsBuilder](https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/eventDetailsBuilder.hpp))
- This field should be false by default and true if the vulnerability is `under_evaluation`

**Comment by GabrielEValenzuela** [comment]
# Update

- Development in progress. Woking in UTs

**Comment by GabrielEValenzuela** [comment]
# Update

- Task done. Await review.

**Comment by AlexRuiz7** [comment]
Suggestion:

- Consider renaming the field to `is_awaiting_analysis`, to better match the NVD report.

**Comment by sebasfalcone** [comment]
## Definition update
We decided to change the field from `wazuh.vulnerability.under_evaluation` to `vulnerability.under_evaluation`

**Comment by GabrielEValenzuela** [comment]
We found a typo on the `index-template` JSON
