### ISSUE TITLE
Release 4.9.0 - RC 2 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#25507]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |            https://github.com/wazuh/wazuh/issues/25475                   |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/25503                       |
| **Version**                          |                   4.9.0                         |
| **Release stage**              |                   RC 2                      |
| **Tag**                              |          https://github.com/wazuh/wazuh/tree/v4.9.0-rc2                               |
| **Previous Vulnerability performance tests issue**      |       https://github.com/wazuh/wazuh/issues/25403                    |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Frequency | Number of Vulnerable Packages | Time |
| --- | --- | --- | --- | --- | --- | --- | --- |--- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 60  | 100 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 60 | 100 | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 25 | 3 | 50000 | 1 | 60 | 100 | 1h |

**Considerations**

- `KIBANA_API_REQUESTS` should be enabled
- `EXTRA_LOAD_API_REQUESTS` should be enabled
- Due to the current operation of the simulator and how it does the EPS distribution with the frequency, we can expect the actual EPS to be about half, so it is necessary to set twice as much.

### Builds

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/666/
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/667/
- Very high: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/668/

### Known Issues :yellow_circle: 

- https://github.com/wazuh/wazuh/issues/8480
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-indexer/issues/71
- https://github.com/wazuh/wazuh-indexer/issues/167
- https://github.com/wazuh/wazuh-indexer/issues/328
- https://github.com/wazuh/wazuh-packages/issues/1511
- https://github.com/opensearch-project/performance-analyzer/issues/644
- https://github.com/opensearch-project/OpenSearch/issues/9061
- https://github.com/wazuh/wazuh-jenkins/issues/6902
- https://github.com/wazuh/wazuh/issues/25420
- https://github.com/wazuh/wazuh/issues/25215
- https://github.com/wazuh/wazuh/issues/25204

### New issue :red_circle: 

- https://github.com/wazuh/wazuh-jenkins/issues/6919

**Comment by rafabailon** [comment]
Moved to `On hold` until the builds are finished:

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/666/
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/667/
- Very high: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/668/

**Comment by rafabailon** [comment]
# High Activity

## Info

**Report:** [artifacts.zip](https://github.com/user-attachments/files/16845169/artifacts.zip)
**Build:** [CLUSTER-Workload_benchmarks_metrics/667/](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/667/)
**Comparision** Compared with: [#24504](https://github.com/wazuh/wazuh/issues/24504)

## Logs 🔵 

## Metrics and Statistics 🔵 

## Vulnerabilities State 🔵 

## Alerts 🔵

**Comment by santipadilla** [comment]
# Medium activity

## Metrics and statistics

<details><summary>Worker 1 :black_circle:  </summary>

- Metrics: 

  - 

- Statistics:

  

---

- Binaries

![CPU](https://github.com/user-attachments/assets/7d4b49ca-a235-487b-ae54-c6c922a89442)
![Disk_Read](https://github.com/user-attachments/assets/a1d6553d-1952-4f64-8948-1da84144bd50)
![Disk_Read_Speed](https://github.com/user-attachments/assets/34a10c99-ec0e-40d1-9f82-146d0f344ff6)
![Disk_Write_Speed](https://github.com/user-attachments/assets/ac7acd72-30ad-49f0-bdf6-5b2de249b5af)
![Disk_Written](https://github.com/user-attachments/assets/703a4952-db18-4b82-96b6-4c26ca2c9697)
![FD](https://github.com/user-attachments/assets/ae0e0d2b-219a-4a7e-a953-382b7fa2161f)
![PSS](https://github.com/user-attachments/assets/8293fd45-87c1-44fa-b44b-98a443da9c19)
![Read_Ops](https://github.com/user-attachments/assets/76079833-817f-4fc9-bfbe-8edd267f5ea9)
![RSS](https://github.com/user-attachments/assets/254eb495-6662-4239-acbf-09a6030dbd44)
![SWAP](https://github.com/user-attachments/assets/814592d5-36a5-4d1e-b431-81e40f2fe23c)
![USS](https://github.com/user-attachments/assets/c7b99d9a-a673-44a3-9852-198d68bc995f)
![VMS](https://github.com/user-attachments/assets/862c5cb6-db6f-43ac-81f6-252c01830f3d)
![Write_Ops](https://github.com/user-attachments/assets/3aeac9d0-2df6-4746-9aaa-a48fd05d9a3e)


- Stats: wazuhdbd

![wazuh-wazuhdb_api_stats_Agent queries breakdown](https://github.com/user-attachments/assets/db601c72-ce1a-4bb5-9988-384cb337b09b)
![wazuh-wazuhdb_api_stats_Agent tables breakdown](https://github.com/user-attachments/assets/e91be319-df6e-44a7-a12e-ed2ac540133f)
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/7885ec9d-fc6b-4d98-aae6-e7ac1b8d754f)
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/d6a4f081-bd30-41a4-9353-3045aa4a4c09)
![wazuh-wazuhdb_api_stats_Global group queries](https://github.com/user-attachments/assets/7c21c2cc-51f0-44fe-a73d-6788254704c1)
![wazuh-wazuhdb_api_stats_Global queries breakdown](https://github.com/user-attachments/assets/961395d6-9829-415b-a6a3-70e1923a5d69)
![wazuh-wazuhdb_api_stats_Queries time metrics](https://github.com/user-attachments/assets/01642b75-913b-4e92-b1c3-b8b1f2c86599)
![wazuh-wazuhdb_api_stats_Task queries breakdown](https://github.com/user-attachments/assets/f583d81c-3ca5-4eba-b213-78f27ba80c9f)


- Stats: remoted

![wazuh-remote_api_stats_Bytes received](https://github.com/user-attachments/assets/56b737c0-567f-465e-af67-ff117b4b552d)
![wazuh-remote_api_stats_Events sent and count](https://github.com/user-attachments/assets/8919a029-0166-4f52-9e03-61a9c5d5e309)
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/a58c186b-67bb-4702-baae-478bf28de9f3)
![wazuh-remote_api_stats_TCP sessions](https://github.com/user-attachments/assets/b3812af7-6bf1-474e-8bcf-70c8b315c8ad)



- Stats: logcollectord

![active-responses_log_Bytes sent](https://github.com/user-attachments/assets/29a3b145-167e-4f1a-b2c4-fc0c06781ddf)
![active-responses_log_Events dropped](https://github.com/user-attachments/assets/7747dbe1-b088-4464-95b8-fb667f3df0ef)
![active-responses_log_Events generated](https://github.com/user-attachments/assets/60b61fc8-398a-4f41-a929-870f0fe7ae64)
![audit_log_Bytes sent](https://github.com/user-attachments/assets/93de93ed-dbbd-48b4-887a-ddf9ef71d4ab)
![audit_log_Events dropped](https://github.com/user-attachments/assets/c348dd35-fa8a-4adf-b84c-5e0c0224a4d7)
![audit_log_Events generated](https://github.com/user-attachments/assets/e4b7587a-10ba-4fdd-8447-c257391aa854)
![df_Bytes sent](https://github.com/user-attachments/assets/48deea1d-3668-4150-b86f-e34a00d7e1e6)
![df_Events dropped](https://github.com/user-attachments/assets/fd71ad07-8299-4bf4-838e-672731d84c31)
![df_Events generated](https://github.com/user-attachments/assets/ed9be1da-e0bb-40da-840e-bc0ac5ad3483)
![journald_Bytes sent](https://github.com/user-attachments/assets/cfc78c72-8acc-4a83-90cc-5305d205fcc1)
![journald_Events dropped](https://github.com/user-attachments/assets/2e3422eb-1ba9-45a0-a5e1-ad1294890991)
![journald_Events generated](https://github.com/user-attachments/assets/3bf918c7-edc8-4384-bb8c-ed0de843799c)
![last_Bytes sent](https://github.com/user-attachments/assets/7fa23d9c-fd01-49c2-bc40-d76ce58fd8bd)
![last_Events dropped](https://github.com/user-attachments/assets/e61f7864-e1bb-4369-8715-b80549d3080f)
![last_Events generated](https://github.com/user-attachments/assets/ccf8a2ed-44c0-4a53-ae5b-23bd4e21e3b0)
![netstat_Bytes sent](https://github.com/user-attachments/assets/d7eaf27f-eff5-4c0f-9a35-ba217090860e)
![netstat_Events dropped](https://github.com/user-attachments/assets/b82b3cb6-b876-4956-b03e-1a012321dda6)
![netstat_Events generated](https://github.com/user-attachments/assets/60741f39-0641-45fb-abda-bacca71b010e)



</details>

<details><summary>Worker 2 :black_circle:  </summary>

- Metrics: 

  - 

- Statistics:

  

---

- Binaries



- Stats: wazuhdbd




- Stats: remoted




- Stats: logcollectord




</details>

**Comment by rafabailon** [comment]
# High Activity

## Metrics and Statistics 🔵 

<details>
   <summary>Worker 2</summary>
   <br/>

- Metrics

- Statistics

- Binaries

![image](https://github.com/user-attachments/assets/b815d70d-9fb2-4f9d-857e-0f2f85d404c6)

![image](https://github.com/user-attachments/assets/72822dc3-6749-42be-98ac-cf27254d160c)

![image](https://github.com/user-attachments/assets/6ea0ff32-6530-4e77-8a98-9c17e4cb7514)

![image](https://github.com/user-attachments/assets/49a18e53-6808-4935-aa11-dfa6e86afff8)

![image](https://github.com/user-attachments/assets/0c33cd91-6ab8-4922-8a95-13897ff3efa7)

![image](https://github.com/user-attachments/assets/11109454-cca6-4dbd-bf97-29acaf3f58c9)

![image](https://github.com/user-attachments/assets/24005c9a-bed3-4366-9516-0c23b8669184)

![image](https://github.com/user-attachments/assets/1cb61f81-dadc-4365-8854-d3794797371d)

![image](https://github.com/user-attachments/assets/7086e95c-7c3e-4a68-b664-0ac73796f147)

![image](https://github.com/user-attachments/assets/b72f7cd5-2f85-49c4-913d-4778d0c5587f)

![image](https://github.com/user-attachments/assets/c6cbb338-799c-421a-b982-799f8c4b5f73)



- Stats - logcollectord



- Stats - remoted



- Stats - wazuhdbd


</details>

## Vulnerabilities State 🔵 

## Alerts 🔵

**Comment by santipadilla** [comment]
ETA increase due to [relaunch](https://github.com/wazuh/wazuh/issues/25507#issuecomment-2324183300) of very high and medium activity cases.

**Comment by santipadilla** [comment]
- The medium activity case build did not have all the demons in the graphs in [this build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/666/). After relaunching the graphs appeared correctly in [this build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/670/).
  - New issue:
 
- The very high activity case [build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/668/) has failed.
   - Known issue:

**Comment by Rebits** [comment]
LGTM
