### ISSUE TITLE
Release 4.9.0 - Release Candidate 2 - Pyserver integration

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25513]
The following issue aims to run all **Pyserver integration tests** for the current release candidate, report the results, and open new issues for any encountered errors.

## Pyserver integration tests information
|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         |                   https://github.com/wazuh/wazuh/issues/25475                         |
| **Version**                              |                        4.9.0                    |
| **Release candidate #**                  |                     RC2                       |
| **Tag**                                  |                        [v4.9.0-rc2](https://github.com/wazuh/wazuh/tree/v4.9.0-rc2)                    |
| **Previous Pyserver integration tests issue** |                           -                 |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found below.

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | [API tier 0/1 test report](https://github.com/wazuh/wazuh/issues/25513#issuecomment-2324608200) | | |  
| 🟢 | [API tier 2 test report](https://github.com/wazuh/wazuh/issues/25513#issuecomment-2324576546) | | |
| 🟢 | [RBAC tier 0/1 test report](https://github.com/wazuh/wazuh/issues/25513#issuecomment-2324584744) | | |

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @fdalmaup 
- [x] @wazuh/devel-qa

**Comment by GGP1** [comment]
## API tier 2 test report

[Build](https://github.com/wazuh/wazuh/actions/runs/10666564567/job/29562265919)

## Test results

| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
|  test_api/test_config/test_max_upload_size/test_max_upload_size.py | 3 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by fdalmaup** [comment]
LGTM
