### ISSUE TITLE
 Release 4.9.0 - RC 2- Integration tests for server

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25537]
# Description
|| | 
| :--                              | :--                                                             |
| **Main release stage issue** |  https://github.com/wazuh/wazuh/issues/25475 |
| **Version**                      | 4.9.0                                               |
| **Release stage**            | RC 2                                                    
| **Wazuh QA: Tag**                          | https://github.com/wazuh/wazuh-qa/tree/v4.9.0-rc2         |
| **Wazuh QA: Branch**    | `v4.9.0-rc2`
| **Wazuh Tag**                          | https://github.com/wazuh/wazuh/tree/v4.9.0-rc2         |
| **Wazuh Branch**    | `v4.9.0-rc2`

- **These tests must be run manually.**

## Results of the integration tests

> |Color| Details |
> |:--:|:--|
> | :green_circle: | The **pipeline** has been executed successfully |
> | :red_circle: | The **pipeline** has failed or it has errors |

<html>
</html>

## Conclusion

| Status                                             | Test| Link      | Coments |
|----------------------------------------------|-----|-----------|--|
| :green_circle:           |integration-tests-analysisd-tier-0-1     |https://github.com/wazuh/wazuh/actions/runs/10671404899/job/29577147493   | |
| :green_circle:             | integration-tests-analysisd-tier-2  |https://github.com/wazuh/wazuh/actions/runs/10671429652/job/29577214634   | |
| :red_circle:                | integration-tests-authd-tier-0-1   | https://github.com/wazuh/wazuh/actions/runs/10671446198/job/29577260353  | Know issue https://github.com/wazuh/wazuh/issues/25430 work in 4.9.1|
| :green_circle:        |  integration-tests-integratord-tier-0-1   | https://github.com/wazuh/wazuh/actions/runs/10671455216 | |
| :green_circle:              | integration-tests-logtest-tier-0-1  | https://github.com/wazuh/wazuh/actions/runs/10671464947 | |
| :green_circle:            | integration-tests-remoted-tier-0-1   | https://github.com/wazuh/wazuh/actions/runs/10671512737/job/29577439293 ||
| :red_circle:               |  integration-tests-remoted-tier-2  | https://github.com/wazuh/wazuh/actions/runs/10681361461 |https://github.com/wazuh/wazuh/issues/25564 |
| :red_circle: |  vulnerability-scanner-tests  | https://github.com/wazuh/wazuh/actions/runs/10683345820 | Fixed in #25094 |
|  :green_circle:     |   integration-tests-wazuh_db-tier-0-1       | https://github.com/wazuh/wazuh/actions/runs/10671550171/job/29577536255  | |

## Auditors' validation

- [x] @wazuh/devel-cppserver 
- [ ] @wazuh/devel-qa-release

**Comment by NahuFigueroa97** [comment]
# Analysis GA Executions

## Analysisd :green_circle: 
-  https://github.com/wazuh/wazuh/actions/runs/10671404899  :green_circle: 
``` 
=========== 72 passed, 3 deselected, 1 xfailed in 1101.96s (0:18:21) ===========
```
-  https://github.com/wazuh/wazuh/actions/runs/10671429652 :green_circle: 
```

**Comment by JcabreraC** [comment]
## Vulnerability detector ⚫ 
The tier 0, 1 and 2 tests of this module are no longer run. Instead we run 
- https://github.com/wazuh/wazuh/actions/runs/10683345820

**Comment by NahuFigueroa97** [comment]
## Remoted 🔴

The same test was run locally. Replicating the environment and then using the act command. In both cases the tests passed.
```
act -s GITHUB_TOKEN="$(gh auth token)" -W .github/workflows/integration-tests-remoted-tier-2.yml -j build
```

and
```
sudo python3 -m pytest --tier 2 test_remoted/
```
![Captura desde 2024-09-03 13-06-36](https://github.com/user-attachments/assets/63b09899-1ffa-4f19-aec6-7774a5737e78)

n this situation it is difficult to replicate the problem. But I ran the test again with additional checks such as:

- Check if the server is running
- Check that there is no firewall blocking the connection to port 1515 on localhost
- The error is occurring in the create_agents call in the agent_simulator.py module. Check the parameters used in the create_agents function, such as the manager_address and any SSL or authentication settings (authd_password). All of this compared to the remotd test for a tier 2.
- Checked the Wazuh server logs for more details on why it might be refusing the connection, but I found nothing.
