### ISSUE TITLE
Error in stringHelper function

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#25547]
## Description
It was discovered that the **[replaceAll](https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/shared_modules/utils/stringHelper.h#L70-L83)** function from **stringHelper** has a bug (see steps to reproduce)

The proposed solution is as follows:
```C++
static bool replaceAll(std::string& data, const std::string& toSearch, const std::string& toReplace)
{
    bool found = false;
    auto pos = data.find(toSearch);

    while (pos != std::string::npos)
    {
        data.replace(pos, toSearch.size(), toReplace);
        found = true;
        pos = data.find(toSearch, pos + toReplace.size());
    }

    if (found && toSearch != toReplace)
    {
        while (replaceAll(data, toSearch, toReplace)) {}
    }

    return found;
}
```

## Steps to reproduce
[This code example](https://godbolt.org/z/dx66fe5e8) shows how to reproduce this issue (The **toReplace** string is a subset of the **toSearch** string)

## DoD
- [x] Implement the fix
- [x] Validate the fix
- [x] Update UTs

**Comment by sebasfalcone** [comment]
## Updated ETA
Delayed due to issues related to 4.9.1 and 4.10.0 releases being pushed to completion

**Comment by GabrielEValenzuela** [comment]
#  Update

- Co-implementation with @sebasfalcone complete
