### ISSUE TITLE
ID as optional field in the indexer connector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25541]
## Description
The new uses that the `indexerConnector` will endure, in the engine, forced us to make the `_id` field for queries optional (so OpenSearch can assign it on its own)

The following methods should take into account this new requirement:
https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L165-L186

> [!TIP]
> We could use the [builder pattern](https://refactoring.guru/design-patterns/builder) to make the inferace to this queries ([see example](https://github.com/wazuh/wazuh/blob/8f93ae377aa120ed58d16b17a4d9af50c1cd6f5e/src/shared_modules/utils/wazuhDBQueryBuilder.hpp))

## DoD
- [x] Feature implemented
- [x] UTs updated

**Comment by pereyra-m** [comment]
## Update

I analyze the requirements and begin with the implementation.

**Comment by sebasfalcone** [comment]
## Updated ETA
Delayed due to issues related to 4.9.1 and 4.10.0 releases being pushed to completion

**Comment by pereyra-m** [comment]
## Update

I revert the approach after the review
