### ISSUE TITLE
Add placeholder to manage index names with dates in the indexer connector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25540]
## Description
The `indexerConnector` should be able to receive an index with a date placeholder and replace it. The implementation should be similar to:
https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanContext.hpp#L192-L196

The logic should be implemented here:
https://github.com/wazuh/wazuh/blob/bde6280610f6571baad79db0e4f344cd41f76af3/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L404-L404

> [!IMPORTANT]
> A helper function should be implemented to follow the single responsibility principle

## Expected format
`yyyy.MM.dd` from `$(date)`

## DoD
- [x] Feature added
- [x] Updated UTs

**Comment by sebasfalcone** [comment]
## Updated ETA
Delayed due to issues related to 4.9.1 and 4.10.0 releases being pushed to completion
