### ISSUE TITLE
Error handling for alerts in the indexer connector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25542]
## Description
If data pushed by the `indexerConnector` fails to be indexed, it will continue to be in its corresponding persistent queue

See how an exception could occur in the functor and will prevent the pop to be performed:
https://github.com/wazuh/wazuh/blob/adbe03170c581f432267a45ee0e3489030ca4678/src/engine/source/base/include/base/utils/threadEventDispatcher.hpp#L202-L235

For example, if a bulk query is performed:
https://github.com/wazuh/wazuh/blob/adbe03170c581f432267a45ee0e3489030ca4678/src/engine/source/base/include/base/utils/threadEventDispatcher.hpp#L211-L212

Elements that failed should be removed from the queue and log it.

To achieve this, we should list all possible errors that come from the indexer and handle them accordingly (sync with the @wazuh/devel-cppserver-div3 team)

## Extras

To implement this feature we will change how the threadEventDispatcher is initialized:
https://github.com/wazuh/wazuh/blob/adbe03170c581f432267a45ee0e3489030ca4678/src/engine/source/base/include/base/utils/threadEventDispatcher.hpp#L37-L38

Instead of passing the number of threads, we will provide the constructor with an enum class:
```C++
enum class ThreadEventDispatcherType
{
    SINGLE_THREADED_ORDERED,
    MULTI_THREADED_UNORDERED
};
```

The `MULTI_THREADED_UNORDERED` type will dispatch 3 threads.

## DoD
- [x] Feature added
- [x] Added UTs
- [x] Behaviour validated

**Comment by MiguelazoDS** [comment]
So far, the multithread dispatching works reinserting the elements it couldn't process (multiAndUnordered), but the single thread implementation I understand is not the same, we are going to drop elements that couldn't be processed. For indexing, if the indexer is not connected it will drop all elements, impossible to reindex later. Wouldn't that cause issues in the vulnerabilities dashboard? many users are having issues connecting the indexer connector, if the module scans before the module is connected to the indexer, they won't see any vulnerability.

**Comment by sebasfalcone** [comment]
## ETA update
- Tests weren't being compilated we are aligning them
- Expected behaviour is not being achieved

**Comment by MiguelazoDS** [comment]
Isn't too much an issue, but the cerr messages are not thread-safe. 
![image](https://github.com/user-attachments/assets/9967e426-2984-40cf-ad2b-1dbd639bdcbc)

The implementation is done and the tests are passing, but the test throws an exception based on the amount of processed events (counter) and not in a specific event. The implementation of that test is failing, but I assume that there's a bad test implementation and not the feature. 

Also, there was a test with a bulk size greater than one for threadSafeMultiQueue, but that does not have effect, since it uses the method getAndPop instead of getBulkAndPop.

**Comment by MiguelazoDS** [comment]
Ready for review, the validation was done through testing. Basically, a test changing the lambda function that processes the events popped from the queue will decide if the event that caused the exception is discarded or not, also the lambda will log a message if required.
