### ISSUE TITLE
Wazuh Management API legacy endpoints removal

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25554]
|Objective|
|---|
| #22888 |

## Description

As part of the development of Wazuh v5.0 and the removal of legacy modules in Wazuh, the Management API, which contains several endpoints related to these, needs to be reviewed and modified to simplify the definition of requirements and the work of the new developments.

## Non-functional requirements

- [x] Review the current Management API endpoints containing references to daemons and modules removed from the server. Some work related has been carried out in:
    - https://github.com/wazuh/wazuh/issues/23393#issuecomment-2151028451
    - https://github.com/wazuh/wazuh/issues/17063
    - https://github.com/wazuh/wazuh/issues/17068
    - https://github.com/wazuh/wazuh/issues/17069
    These can be checked out for reference.
- [x] Remove endpoints related to modules that will report to the Comms API via the `POST /events/stateful` (FIM, Inventory, SCA) and document the test cases contemplated in the API integration tests to take them into account for the Comms API integration tests.
- [x] Remove endpoints related to legacy modules.

## Plan

- https://github.com/wazuh/wazuh/issues/26552
- https://github.com/wazuh/wazuh/issues/26553
- https://github.com/wazuh/wazuh/issues/26554
- https://github.com/wazuh/wazuh/issues/26555
- https://github.com/wazuh/wazuh/issues/26763

**Comment by Dwordcito** [comment]
LGTM
