### ISSUE TITLE
Upgrade Fedora 32 from 4.8.2 to 4.9.0 fails

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#25575]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.9.0-rc2 | Wazuh component | Agent | Packages | Fedora 32 |

During the [Release 4.9.0 - RC 2 - Upgrade metrics test](https://github.com/wazuh/wazuh/issues/25491)

The following error was found, upgrading Fedora 32 from 4.8.2 to 4.9.0 in https://ci.wazuh.info/job/Test_upgrade/136472/

```
11:07:05  2024/09/02 08:31:25 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
11:07:05  
11:07:05  2024/09/02 08:31:26 wazuh-modulesd:content-updater: ERROR: Couldn't start scheduled action: _Map_base::at
11:07:05  
11:07:05  2024/09/02 08:31:26 wazuh-modulesd:content-updater: ERROR: Couldn't start on-demand action: _Map_base::at
11:07:05  
11:07:05  2024/09/02 08:31:31 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning..
```

Log:
[log_upgrade_fedora_32.log](https://github.com/user-attachments/files/16872202/log_upgrade_fedora_32.log)

Running a new test on https://ci.wazuh.info/job/Test_upgrade/136536, the error is not displayed

> More research is required.

**Comment by Dwordcito** [comment]
Cosmetic and pre-existing issue, the call of startScheduling and startOnDemand succeed after the call gracefullShutdown call.

Call order:
1- addProvider()
2- stop()
3- startScheduling()
4- startOnDemand()


We could move this to 4.9.1.

```cpp
void ContentModuleFacade::stop()
{
    std::lock_guard<std::shared_mutex> lock {m_mutex};
    m_providers.clear();
}

void ContentModuleFacade::addProvider(const std::string& name, const nlohmann::json& parameters)
{
    std::lock_guard<std::shared_mutex> lock {m_mutex};
    // If already exist throw exception
    if (m_providers.find(name) != m_providers.end())
    {
        throw std::runtime_error("Provider already exist");
    }

    m_providers.emplace(name, std::make_unique<ContentProvider>(name, parameters));
}
void ContentModuleFacade::startScheduling(const std::string& name, size_t interval)
{
    std::shared_lock<std::shared_mutex> lock {m_mutex};
    try
    {
        m_providers.at(name)->startActionScheduler(interval);
    }
    catch (const std::exception& e)
    {
        logError(WM_CONTENTUPDATER, "Couldn't start scheduled action: %s.", e.what());
    }
}
void ContentModuleFacade::startOndemand(const std::string& name)
{
    std::shared_lock<std::shared_mutex> lock {m_mutex};
    try
    {
        m_providers.at(name)->startOnDemandAction();
    }
    catch (const std::exception& e)
    {
        logError(WM_CONTENTUPDATER, "Couldn't start on-demand action: %s.", e.what());
    }
}
```

**Comment by tsarquis88** [comment]
# Update

I tried to reproduce the error on a Fedora 32 vagrant box, without success.

I did reproduce it by forcing the following sequence on a Content Manager UT:
```c++
auto& contentModuleFacade = ContentModuleFacade::instance();
contentModuleFacade.start({});
contentModuleFacade.addProvider(topicName, m_parameters);
contentModuleFacade.stop();
contentModuleFacade.startScheduling(topicName, 1);
```

Apparently this is caused by a race condition and as such it doesn't happen on every execution.

**Comment by tsarquis88** [comment]
# Update

The scenario has been reproduced with the help of some modification in the source code.

After meeting with @Damian-Mangold and @Dwordcito, it was decided that since this can only happen when the Content Manager is being stopped, the library shouldn't log an error.

**Comment by tsarquis88** [comment]
# Update

Solution implemented. Issue now moved to pending reviews.

**Comment by tsarquis88** [comment]
# Update

Code review changes applied.
