### ISSUE TITLE
A `core` file appeared in the Wazuh manager 4.9.0 RC 2 upgrade test 

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#25572]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.9.0-rc2 | - | Manager | Packages | Fedora 36 |

We have found another core file in the upgrade test check-files test while upgrading from 4.8.0 to 4.9.0

```
11:07:03  /var/ossec/core.323  [root root 0600 -rw-------]
```

We saw this problem in v4.9.0-beta2 in a Fedora 34 agent and it was reported here https://github.com/wazuh/wazuh/issues/25201

It is the first time that we have seen `core` files in the upgrade tests, both upgrading to the 4.9.0 version, as it is the second time that this error appeared, we should investigate it and check why it is appearing

## Related

- First report https://github.com/wazuh/wazuh/issues/25201
- Agent core Beta 2 https://ci.wazuh.info/job/Test_upgrade/136238/
- Manager core RC 2 https://ci.wazuh.info/job/Test_upgrade/136469/

**Comment by sebasfalcone** [comment]
## Update
After performing 10 upgrades I wasn't able to replicate this issue

I will propose a solution to this test instead (assuming the core dump is a valid file to begin with)

**Comment by sebasfalcone** [comment]
## Update
After performing 10 upgrades I wasn't able to replicate this issue

I will propose a solution to this test instead (assuming the core dump is a valid file to begin with)

**Comment by sebasfalcone** [comment]
## Update
Continue testing, the issue has to do with an error on the parameters of the jenkins run

**Comment by Dwordcito** [comment]
Unfortunately, this issue has no other destination than (https://github.com/wazuh/wazuh/issues/25201#issuecomment-2288138343) since it is intermittent and we do not have the forensic information capable of identifying the problem, we cannot even begin the analysis.

We tried to reproduce the bug 10 times, but we can't achieve it.
