### ISSUE TITLE
Adapt Agent model according the last changes of the index data model

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh#25582]
|Objective|
|---|
| #22677 |

# Description 

During the development of #24711, we detected that the [Agent index data model](https://github.com/wazuh/wazuh-indexer/issues/270#issuecomment-2176507169) was updated.

It is needed to adapt our models, to the latest changes, and do the modification to the CRUD.

##  Plan
- [x] Adapt the [Agent model](https://github.com/wazuh/wazuh/blob/8f234ea61d22de1f41650bf890fb9d8bcde88bd8/framework/wazuh/core/indexer/models/agent.py#L41)
- [x] Review the `POST /agent` flow to index with the new schema.
- [x] Review the `GET /agent` endpoint to filter by the new fields.
- [x] Review the `DELETE /agent` endpoint to filter by the new fields.

**Comment by GGP1** [comment]
## Update

Updated the agent model and fixed a bug when updating an agent's groups.

**Comment by GGP1** [comment]
## Update

Reviewed the behavior of the endpoints affected and fixed a couple of bugs related to the DSL query filtering and group assignation on agent creation.

**Comment by GGP1** [comment]
## Update

Explained why the endpoint fields weren't added as controllers arguments.

**Comment by GGP1** [comment]
## Update

Explained why the endpoint fields weren't added as controller arguments.

**Comment by GGP1** [comment]
## Update

Rebased branch to master and resolved conflicts.
