### ISSUE TITLE
Track necessary changes in the Comms API MVP

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25592]
|Objective|
|---|
| #22677  |

## Description

As part of the Comms API objective, the team needs to track and apply the necessary changes to the already developed modules due to possible changes in the components that participate in agent/server communication. 

## Components
- **Agent**: modifications related to the requests made by it.
- **Indexer**: modifications related to the indices fields and the upcoming Command manager development (https://github.com/wazuh/wazuh-indexer/issues/349)
    - https://github.com/wazuh/wazuh/issues/25582
    - Adapt commands model according to the new index template defined in https://github.com/wazuh/wazuh-indexer-plugins/issues/42#issuecomment-2358745436.
- **Engine**: modifications related to the delivery of `stateless` events or any other required endpoint that communicates with it.
    - The @wazuh/devel-cppserver team is carrying out the development of the required `events/stateless` endpoint in https://github.com/wazuh/wazuh/issues/25619 and #25620 is already in the Backlog to develop the necessary changes in the Comms API.
    - https://github.com/wazuh/wazuh/issues/25621
- Comms API Hot fixes:
    - https://github.com/wazuh/wazuh/issues/26086

**Comment by GGP1** [comment]
## Update

The developments have been carried out in the issues linked in the description. The only ones that haven't been closed yet are https://github.com/wazuh/wazuh/issues/25599 and https://github.com/wazuh/wazuh/issues/25620, which are in pending review. Therefore, I'm putting this task in the same status.

**Comment by fdalmaup** [comment]
# Review 

I am closing this issue since the required changes in the Comms API and the Server MVP will be tracked at https://github.com/wazuh/wazuh/issues/26562.
