### ISSUE TITLE
Review current configuration management

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25595]
| Related task |
|---|
| https://github.com/wazuh/wazuh/issues/25193 |

## Description

This issue aims to review the current configuration module used by the cluster and define the necessary changes it would require. This includes reviewing the configuration options for each configuration file, the code managing this file, and the new layout in `yaml`.

In the future, the configuration files `ossec.conf` and `local_internal_options.conf` will no longer exists and all their related configuration options will be moved to `ossec.conf`.

## Requirements
- [x] Review the `ossec.conf` configuration file:
   -  Review the configuration options and document which ones will stay or be deprecated.
   -  Review the necessary changes in the code for the configuration.
   -  Define the new structure of the configurations options in `yaml`.
- [x] Review the `api.yaml` configuration file:
   -  Review the configuration options and document which ones will stay or be deprecated.
   -  Review the necessary changes in the code in charge of the configuration.
   -  Review if it is necessary to change or re-define the structure of the configurations options in `yaml`. 
- [x] Review the `local_internal_options.conf` configuration file:
   -  Review the configuration options and document which ones will stay or be deprecated.
   -  Review the necessary changes in the code in charge of the configuration.
   -  Define the new structure of the configurations options in `yaml`.

**Comment by RamosFe** [comment]
### Update

I started reviewing the `API.yaml` configuration and its related code. Also, check the documentation we have of the file to check where we should make changes.

**Comment by RamosFe** [comment]
# Configuration File `api.yaml`
## Configuration options review

- ✔️ : Keep the configuration option.
-  ♻️ : Will be replaced by other configuration options or must be defined in the future.
- ❌ : It will no longer exits.

### General Options

| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| host |IP address or hostname of the Wazuh manager where the Wazuh server API is running.  | ✔️  | - |
| port |  Port where the Wazuh server API will listen.| ✔️  | - |
| drop_privileges | Run wazuh-api process as the wazuh user. | ✔️   | - |
| experimental_features | Enable features under development | ✔️  | - |
| max_upload_size |  Set the maximum body size that the API can accept, in bytes (0 -> limitless)  |  ♻️  | We should investigate the possibility of deleting this option or using one option for the CAPI and another for the management API due to the event body tend to be bigger than the average body in the Management API. |
| intervals.request_timeout | Set the maximum response time (in seconds) for each API request | ✔️  | - |

### HTTPs Options

| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| https.enabled | Enable or disable SSL (https) in the Wazuh server API. | ♻️ | This option will probably be the default way, causing this option to be deleted.|
| https. key |Name of the private key. Stored in /var/ossec/api/configuration/ssl. | ✔️  | - |
| https. cert | Name of the certificate. Stored in /var/ossec/api/configuration/ssl.| ✔️ | - |
| https. use_ca | Whether to use a certificate from a Certificate Authority or not. | ✔️ | - |
| http.ca | Name of the certificate of the Certificate Authority (CA). Stored in /var/ossec/api/configuration/ssl. | ✔️ | - |
| http.ssl_protocol | SSL protocol to allow. Its value is not case sensitive. | ✔️ | - |
| http. ssl_ciphers | SSL ciphers to allow. Its value is not case sensitive. | ✔️ | - |

### Logs Options

| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| logs.level | Set the verbosity level of the Wazuh server API logs. | ✔️  | - |
| logs.format | Set the format of the Wazuh server API logs. | ✔️  | - |
| logs.max_size.enabled | Toggle between time-based and size-based Wazuh API log rotation. Enabling this option disables time-based rotation, enabling rotation based on file size instead. | ❓   | - |
| logs.max_size.size | Set the maximum file size to not trigger size-based log rotation. Lower than 1 M values are considered as 1 M. | ❓   | - |

### CORS Options
| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| cors. enabled | Enable or disable the use of CORS in the Wazuh server API. | ✔️  | - |
| cors. source_route | Sources for which the resources will be available. For example http://client.example.org. | ✔️  | - |
| cors. expose_headers | Which headers can be exposed as part of the response. | ✔️  | - |
| cors. allow_headers | Which HTTP headers can be used during the actual request. | ✔️  | - |
| cors. allow_credentials | Tell browsers whether to expose the response to frontend JavaScript or not. | ✔️  | - |

### Access Options
| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| access. max_login_attempts |Set a maximum number of login attempts during a specified block_time number of seconds. | ✔️  | - |
| access. block_time |Established period of time (in seconds) to attempt login requests. If the established number of requests (max_login_attempts) is exceeded within this time limit, the IP address is blocked until the end of the block time period. | ✔️  | - |
| access. max_request_per_minute |The maximum number of requests allowed per minute. It applies to all Wazuh server API endpoints except for authentication requests. Reaching this limit in less than a minute blocks all incoming requests from any user for the remaining time. A value of 0 disables this feature. For POST /events requests, the effective value is 30 for values greater than 30. | ✔️    |  |

### Upload Configuration
| Option | Description | Status | Related Issue - Changes |
|  --------  |  -------  |  -------  | -------  |
| upload_configuration.remote_commands.allow | Allow uploading configurations with remote commands through the Wazuh server API. Setting this option to false prevents uploading ossec.conf files that contain the [wodle "command" option](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-command.html#wodle-command) or the <command> option inside the [localfile tag](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#reference-ossec-localfile). | ♻️ | - |
| upload_configuration.remote_commands. exceptions | Set a list of commands allowed to be uploaded through the API. These exceptions can always be uploaded regardless of the allow configuration. | ♻️ | - |
| upload_configuration. agents.eps.allow | Allow uploading configurations with modified EPS limits through the Wazuh server API. Setting this option to false prevents uploading ossec.conf files if the <limits><eps> section inside the [global tag](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#reference-ossec-global) has changed. | ♻️ | - |
| upload_configuration. agents.allow_higher_versions.allow | Allow uploading configurations that accept higher agent versions through the Wazuh server API. Setting this option to false prevents uploading ossec.conf files that contain the <allow_higher_versions> section with the yes value inside the [auth](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html#reference-ossec-auth) or [remote](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#reference-ossec-remote) tags. | ♻️ | - |
| upload_configuration.indexer.allow | Allows uploading an updated [indexer configuration section](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/indexer.html) through the Wazuh server API. Setting this option to false prevents updating the indexer configuration when uploading ossec.conf. | ♻️ | - |
| upload_configuration.integrations.virustotal.allow | Allows uploading an updated [Virus Total integration configuration section](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html) using a public API key through the Wazuh server API. Setting this option to false prevents updating the integrations Virus Total configuration when uploading ossec.conf. | ♻️ | - |
| upload_configuration.integrations.virustotal.minimum_quota | Minimum quota value for Virus Total public API key. | ♻️ | - |

**Comment by RamosFe** [comment]
# Configuration File `api.yaml`
## Codes Changes

In this section I will mention each file where the configuration is used. In the future this code must be replaced with the new configuration file. Most of the code, specially the one related to the parsing of the `yaml` could be useful for future Issues of https://github.com/wazuh/wazuh/issues/25193

### Obtaining the contents of `api.yaml`

The configuration path is obtained from the `api/api/constants.py`:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/api/api/constants.py#L11-L12

These contansts are used in Exception messages defined in `api/api/api_exception.py`:
https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/api/api/api_exception.py#L28-L32


And primarily in `api/api/configuration.py`. Here it is used for obtaining the contents of the `api.yaml` file, parsing some of their values to convert them to their respective types in Python and replacing the empty configuration options with the default ones.

### Configuration file parsing
The following function is in charge of parsing the `api.yaml` file. This function could be re-used to parse the new configuration file.

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/api/api/configuration.py#L266-L280

This function also includes some helper functions:
- `replace_bools`: In charge of changing the string values "yes," "no," "enabled," "disabled" into their boolean counterparts.
- `append_wazuh_prefixes`: In charge of appending the Wazuh prefix to all path fields in a dictionary.
- `fill_dict`: In charge of replacing empty values in a dictionary with their default configuration.

The default configuration of the API is defined in the global variable `default_api_configuration`:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/api/api/configuration.py#L33-L104

Finally, the contents of the file are saved in the global variable `api_conf ` for further use in the API (especially in the initialization and some specific endpoints).

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/api/api/configuration.py#L342-L344

### Endpoints

The configuration API is accessed directly by two endpoints:
- [GET /manager/api/config](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_api_config): Get the complete local Wazuh server API configuration.
- [GET /cluster/api/config](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.cluster_controller.get_api_config): Get the complete Wazuh server API configuration of all (or a list) of the cluster nodes.

Each one with their respective controller:
- `api/api/controllers/manager_controller.py`
- `api/api/controllers/cluster_controller.py`

The content of each of the `get_api_config` is similar, calling the  `get_api_config` present in `framework/wazuh/manager.py`:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/manager.py#L149-L167

Finally, this function uses the `get_api_conf ` function in `framework/wazuh/core/manager.py` that makes a deep copy of the `api_conf` global variable mentioned above.

**Comment by RamosFe** [comment]
# Configuration File `ossec.conf`
## Configuration options review

- ✔️ : Keep the configuration option.
-  ♻️ : Will be replaced by other configuration options or must be defined in the future.
- ❌ : It will no longer exits.

### Cluster Options

| Option                         | Description                                                                                         | Status | Related Issue - Changes |
| ------------------------------ | --------------------------------------------------------------------------------------------------- | ------ | ----------------------- |
| **name**                       | Specifies the name of the cluster this node belongs to.                                             | ✔️     | -                       |
| **node_name**                  | Specifies the name of the current node of the cluster. Each node must have a unique name.           | ✔️     | -                       |
| **node_type**                  | Specifies the role of the node. Can be `master` or `worker`.                                        | ✔️     | -                       |
| **key**                        | Defines the key used to encrypt communication between the nodes. Must be 32 characters long.        | ✔️     | -                       |
| **port**                       | Specifies the port for cluster communications.                                                      | ✔️     | -                       |
| **bind_addr**                  | Specifies which IP address will communicate with the cluster when the node has multiple interfaces. | ✔️     | -                       |
| **nodes**                      | Lists all master nodes in the cluster using the `<node>` tag for each one.                          | ✔️     | -                       |
| **hidden**                     | Toggles whether to show information about the cluster that generated an alert.                      | ✔️     | -                       |
| **disabled**                   | Toggles whether the cluster is enabled or not.                                                      | ❌      |  As part of https://github.com/wazuh/wazuh/issues/7108, the Cluster will be enabled by default.                      |
| **haproxy_helper**             | Configures the HAProxy helper for agent balancing.                                                  | ✔️     | -                       |
| **haproxy_disabled**           | Toggles whether the HAProxy helper is enabled or not.                                               | ✔️     | -                       |
| **haproxy_address**            | Specifies the address of HAProxy to communicate with.                                               | ✔️     | -                       |
| **haproxy_user**               | Specifies the user of HAProxy to connect with.                                                      | ✔️     | -                       |
| **haproxy_password**           | Specifies the password of HAProxy to connect with.                                                  | ✔️     | -                       |
| **haproxy_port**               | Specifies the port to use for HAProxy communication.                                                | ✔️     | -                       |
| **haproxy_protocol**           | Specifies the protocol to use for HAProxy communication.                                            | ✔️     | -                       |
| **haproxy_cert**               | Specifies the location of the HAProxy certificate file.                                             | ✔️     | -                       |
| **client_cert**                | Specifies the location of the client-side certificate file.                                         | ✔️     | -                       |
| **client_cert_key**            | Specifies the location of the client-side certificate key file.                                     | ✔️     | -                       |
| **client_cert_password**       | Specifies the password for the client-side certificate.                                             | ✔️     | -                       |
| **haproxy_backend**            | Specifies the name of the backend that will be created in HAProxy.                                  | ✔️     | -                       |
| **haproxy_resolver**           | Specifies the name of the HAProxy resolver to use.                                                  | ✔️     | -                       |
| **excluded_nodes**             | Specifies the cluster nodes to exclude from the agent distribution.                                 | ✔️     | -                       |
| **frequency**                  | Specifies the number of seconds to wait until the next check.                                       | ✔️     | -                       |
| **agent_chunk_size**           | Specifies the size of the chunk of agents to reconnect at the same time.                            | ✔️     | -                       |
| **agent_reconnection_time**    | Specifies the number of seconds to wait between chunks of agents reconnected.                       | ✔️     | -                       |
| **agent_reconnection_stability_time** | Specifies the number of seconds to wait after reconnecting agents to a new worker.       | ✔️     | -                       |
| **imbalance_tolerance**        | Specifies a tolerance value to determine when a cluster is unbalanced.                              | ✔️     | -                       |
| **remove_disconnected_node_after** | Specifies the number of minutes to wait to remove a disconnected worker.                       | ✔️     | -                       |


### Indexer Options

This options aren't currently used by the API, but they will be needed in `5.0` due  to being used extensively in the new CAPI API.

| Option                    | Description                                                                                   | Status | Related Issue - Changes |
|---------------------------|-----------------------------------------------------------------------------------------------|--------|-------------------------|
| `enabled`                 | Enables forwarding inventory data to the Wazuh indexer.                                      | ♻️     | -                       |
| `hosts`                   | Wazuh indexer nodes to connect to. Use the `host` option for setting up each node connection. | ♻️     | -                       |
| `host`                    | Wazuh indexer node URL or IP address to connect to, e.g., `http://172.16.1.11`.               | ♻️     | -                       |
| `ssl`                     | Configuration options for the SSL parameters.                                                 | ♻️     | -                       |
| `certificate_authorities` | List of root certificate file paths for verification.                                         | ♻️     | -                       |
| `ca`                      | CA certificate file path.                                                                     | ♻️     | -                       |
| `certificate`             | The end-entity (leaf) certificate.                                                            | ♻️     | -                       |
| `key`                     | The certificate key used for authentication.                                                  | ♻️     | -                       |

### Logging Options

This options aren't currently used by the API, but they will be needed in `5.0` due to the centralization of the logs file into one file. Some of these options will probably be combined with the ones described in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2341122581.

| Option      | Description                                                                                                                     | Status | Related Issue - Changes |
|-------------|---------------------------------------------------------------------------------------------------------------------------------|--------|-------------------------|
| `log_format`| Specifies the log format for the internal log file ("ossec.log") as JSON output (.json), plain text (.log), or both formats.   | ♻️     | -                       |


### Integrations Options

The configuration options will remain the same unless this Issue is continued: https://github.com/wazuh/wazuh/issues/19013.

| Option           | Description                                                                                                            | Status | Related Issue - Changes |
|------------------|------------------------------------------------------------------------------------------------------------------------|--------|-------------------------|
| `name`           | Specifies the service to integrate with (e.g., Slack, PagerDuty, VirusTotal). Custom integrations must start with `custom-`. | ✔️     | -                       |
| `hook_url`       | URL used for communication with the integration service. Mandatory for Slack, Shuffle, and Maltiverse integrations.   | ✔️     | -                       |
| `api_key`        | API key retrieved from the PagerDuty, VirusTotal, or Maltiverse API. Mandatory for these integrations.                | ✔️     | -                       |
| `alert_format`   | Specifies the alert file format in JSON, used by the Integrator to fetch fields. Set to `json` for Slack, VirusTotal, Shuffle, and Maltiverse integrations. | ✔️     | -                       |
| `level`          | Filters alerts by rule level, pushing only those at or above the specified level.                                      | ✔️     | -                       |
| `rule_id`        | Filters alerts by rule ID.                                                                                             | ✔️     | -                       |
| `group`          | Filters alerts by rule group. For VirusTotal, only `syscheck` group rules are available.                               | ✔️     | -                       |
| `event_location` | Filters alerts by event origin using regex expressions.                                                                | ✔️     | -                       |
| `max_log`        | Maximum length of alert snippets sent to the Integrator, applicable when `alert_format` is not set to `json`.          | ✔️     | -                       |
| `options`        | Customizes fields in the JSON object, overriding previous fields or adding new ones.                                   | ✔️     | -                       |
| `timeout`        | Timeout (in seconds) to wait for a response from the external integration server.                                      | ✔️     | -                       |
| `retries`        | Number of retry attempts on timeout for requests to the external integration server.                                   | ✔️     | -                       |

**Comment by RamosFe** [comment]
# Configuration File `ossec.conf`
## Code Changes
### Endpoints

The following endpoints use the `ossec. conf` configuration file:
- `GET /manager/configuration`
- `PUT /manager/configuration`
- `GET /manager/configuration/{component}/{configuration}`
- `GET /manager/configuration/validation`
- `GET /cluster/local/config`
- `GET /cluster/:node_id/configuration`
- `PUT /cluster/:node_id/configuration`

### Reading and manipulating the `ossec.conf` file

The following function is in charge of reading the `ossec.conf` configuration file and return the contents of it:

> Note that this function doesn't parse the file, it treats it as plain text.

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/manager.py#L279-L315


The following function is in charge of adding new configuration blocks to `ossec. conf`:

> Note that this function doesn't parse the file, it treats it as plain text.

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/manager.py#L346-L395

### Validation of configuration file
The following function is in charge of validating the `ossec. conf` file:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/manager.py#L222-L239

Underneath it, use a UNIX socket to ask for validation, and it returns the response.

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/core/manager.py#L174-L227

### Parse configuration file

Finally, the following function parses the configuration file and returns a dict with each configuration option:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/core/configuration.py#L642-L714

It uses a dictionary to define the expected schema of the configuration:

https://github.com/wazuh/wazuh/blob/d3e254e3a9219bbeb6a844259144257883d8f02e/framework/wazuh/core/configuration.py#L35-L114

**Comment by RamosFe** [comment]
# Configuration File `ossec.conf`
## New Format

Most of the configuration options will remain the same but with a `yaml` format. For example, for the cluster configuration, the following example is provided:

```xml
<cluster>
  <name>wazuh</name>
  <node_name>manager_01</node_name>
  <node_type>master</node_type>
  <key>ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa</key>
  <port>1516</port>
  <bind_addr>0.0.0.0</bind_addr>
  <nodes>
    <node>master</node>
  </nodes>
  <hidden>no</hidden>
  <disabled>no</disabled>
  <haproxy_helper>
    <haproxy_disabled>no</haproxy_disabled>
    <haproxy_address>wazuh-proxy</haproxy_address>
    <haproxy_user>haproxy</haproxy_user>
    <haproxy_password>haproxy</haproxy_password>
    <haproxy_port>5555</haproxy_port>
    <haproxy_protocol>http</haproxy_protocol>
    <haproxy_backend>wazuh_cluster</haproxy_backend>
    <frequency>60</frequency>
    <agent_chunk_size>100</agent_chunk_size>
    <agent_reconnection_time>10</agent_reconnection_time>
    <agent_reconnection_stability_time>60</agent_reconnection_stability_time>
    <imbalance_tolerance>0.1</imbalance_tolerance>
    <remove_disconnected_node_after>10</remove_disconnected_node_after>
  </haproxy_helper>
</cluster>
```

In yaml format, it would be:

```yaml
cluster:
  name: wazuh
  node_name: manager_01
  node_type: master
  key: ugdtAnd7Pi9myP7CVts4qZaZQEQcRYZa
  port: 1516
  bind_addr: 0.0.0.0
  nodes:
    - master
  hidden: no
  disabled: no
  haproxy_helper:
    haproxy_disabled: no
    haproxy_address: wazuh-proxy
    haproxy_user: haproxy
    haproxy_password: haproxy
    haproxy_port: 5555
    haproxy_protocol: http
    haproxy_backend: wazuh_cluster
    frequency: 60
    agent_chunk_size: 100
    agent_reconnection_time: 10
    agent_reconnection_stability_time: 60
    imbalance_tolerance: 0.1
    remove_disconnected_node_after: 10
````

The only change is in the `integrations` configuration options. Due to `yaml` not allowing multiple keys with the same name on the same level, some changes must be made in the `yaml` structure to represent the configuration options as a list:


```xml
<!-- Integration with Slack -->
<integration>
  <name>slack</name>
  <hook_url>https://hooks.slack.com/services/...</hook_url> <!-- Replace with your Slack hook URL -->
  <level>10</level>
  <group>multiple_drops,authentication_failures</group>
  <alert_format>json</alert_format>
  <options>{"pretext": "Custom Title"}</options> <!-- Replace with your custom JSON object -->
</integration>

<!-- Integration with PagerDuty -->
<integration>
  <name>pagerduty</name>
  <api_key>API_KEY</api_key> <!-- Replace with your PagerDuty API key -->
  <options>{"pretext": "Custom title"}</options> <!-- Replace with your custom JSON object -->
  <alert_format>json</alert_format> <!-- With the new script this is mandatory -->
</integration>

<!-- Integration with VirusTotal -->
<integration>
  <name>virustotal</name>
  <api_key>API_KEY</api_key> <!-- Replace with your VirusTotal API key -->
  <group>syscheck</group>
  <alert_format>json</alert_format>
  <timeout>30</timeout>
  <retries>5</retries>
</integration>
````

```yaml
integrations:
  - name: slack
    hook_url: https://hooks.slack.com/services/...
    level: 10
    group: multiple_drops,authentication_failures
    alert_format: json
    options:
      pretext: Custom Title

  - name: pagerduty
    api_key: API_KEY
    options:
      pretext: Custom title
    alert_format: json

  - name: virustotal
    api_key: API_KEY
    group: syscheck
    alert_format: json
    timeout: 30
    retries: 5

``

**Comment by RamosFe** [comment]
# Configuration File `internal_options.conf`
## Configuration options review

- ✔️ : Keep the configuration option.
-  ♻️ : Will be replaced by other configuration options or must be defined in the future.
- ❌ : It will no longer exits.


Here are the updated tables with the new description format:

### Integrator

| Option                         | Description                                                                                         | Status | Related Issue - Changes |
| ------------------------------ | --------------------------------------------------------------------------------------------------- | ------ | ----------------------- |
| **integrator.debug**    | Sets the debug level of integrator.                      |  ✔️              |  - |

### Wazuh Clusterd

| Option                         | Description                                                                                         | Status | Related Issue - Changes |
| ------------------------------ | --------------------------------------------------------------------------------------------------- | ------ | ----------------------- |
| **wazuh_clusterd.debug**    | Sets the debug level of wazuh_clusterd.                      |  ✔️              |  - |

**Comment by GGP1** [comment]
## Review

I've found some minor corrections on the status of the keys.

### api.yaml

- `experimental_features` should be removed as they won't be part of the API in 5.0.

### ossec.conf

- `key` should be removed, communication will be encrypted using TLS instead.
- `haproxy` settings should be double checked to confirm whether it will be used or not.
- `agent_reconnection_time` and `agent_reconnection_stability_time` may be removed, agents won't have a persistent connection to the servers. They send periodic requests to the Comms API but no connection is open for more than 30 seconds.
- `rule_id` should be removed, rules won't exist in 5.0.
- `group` should be removed, syscheck won't exist in 5.0.

### internal_options.conf

- `integrator.debug` should be removed, according to the [Legacy removal](https://github.com/wazuh/wazuh/issues/22888) issue, integratord will be replaced by either the Engine or a module in the agent.

**Comment by RamosFe** [comment]
## Update

Added changes commented in https://github.com/wazuh/wazuh/issues/25595#issuecomment-2349044195.

**Comment by GGP1** [comment]
## Review

The suggested changes were applied correctly. LGTM.

**Comment by fdalmaup** [comment]
# Review

Neat and thorough analysis :+1: . Just a couple of comments to check:
- `apy.yaml`:
   - The `upload_configuration.remote_commands` should be considered to be removed in 5.0 since the Command wodle will be part of the Agent and not the Server.
- `ossec.conf`:
   -  The new `integratord` is not yet defined (plus the mentioned issue https://github.com/wazuh/wazuh/issues/19013 has no assigned project nor objective). We should mark the options as ♻️ and modify the comment accordingly.
   - You mentioned that rules will not exist in 5.0, do you have a reference related to that?

**Comment by RamosFe** [comment]
## Update

After reviewing the comments made by @GGP1 and @fdalmaup, I revisited the Issues related to the Engine (https://github.com/wazuh/wazuh/issues/11334). The new Engine has the concept of rules, but they don't have the same functionality as before. Instead of using it for triggering alerts, they are used for adding more information/metadata to the events. All this is described in the Issue's documents.

**Comment by fdalmaup** [comment]
# Review

Changes to the mentioned comments were made. LGTM.
