### ISSUE TITLE
The automatic page refresh is not working in Wazuh Dashboard in version 4.9.0

### ISSUE THREAD

**Issue by sakib789** [wazuh/wazuh#25617]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh Dashabord |  | Quickstart |  Ubuntu 22.04 LTS|

The automatic page refresh is not working properly for the Wazuh Dashboard in version 4.9.0. The page is refreshing but it is not updating the changes on the Dashboard. 
![image](https://github.com/user-attachments/assets/2c36fa0b-c85b-4501-b564-101afe1ce7fb)

Please look into this.

**Comment by pereyra-m** [comment]
Hi @sakib789 
I'd move this issue to https://github.com/wazuh/wazuh-dashboard

@wazuh/devel-dashboard

**Comment by guidomodarelli** [comment]
The resolution for this issue can be found in the pull request available at: https://github.com/wazuh/wazuh-dashboard-plugins/pull/7090.

This resolution also addressed a performance concern.
