### ISSUE TITLE
Expose endpoint to receipt the hot configuration changes

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25624]
## Description
We need to expose an unix socket HTTP endpoint that will trigger a pull of updated configurations from a cluster endpoint source. The endpoint will receive a command that initiates the pull process, after which the service will fetch the latest configuration and apply it dynamically without restarting.

## Requirements
- Create a new API endpoint (e.g., `/config/pull`).
- Include logging for the command execution and configuration updates for auditing purposes.

## Acceptance Criteria
- [ ] A new API endpoint exists to trigger the configuration pull process.
- [ ] The endpoint accepts a command via `POST` request to initiate the pull.

**Comment by JcabreraC** [comment]
Awaiting definitions

**Comment by JcabreraC** [comment]
Awaiting definitions

**Comment by JcabreraC** [comment]
Awaiting definitions

**Comment by JcabreraC** [comment]
Awaiting definitions

**Comment by JcabreraC** [comment]
Awaiting definitions

**Comment by JcabreraC** [comment]
Awaiting definitions
