### ISSUE TITLE
Router stateless message to engine `/api/v1/events/stateless` endpoint

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#25620]
# Description

As part of #25105, the Comms API is required to expose a new endpoint related to the stateless messages. This endpoint will allow the agent to send the stateless messages to the engine endpoint.

- The VD UNIX socket location is in `/run/wazuh-server/engine.sock`.
- The VD endpoint is  `POST /api/v1/events/stateless`. 

## Request
- Only forward json

#### Success

A successful response will contain a 200 HTTP status.

#### Failure

A failed response will contain a JSON struct following the format defined in and an HTTP status between 300 and 505.

```json
{
    "error": {
        "message": "Error",
        "code": 503
    }
}
```

# Plan
- [x] Modify the related engine-related abstractions to route the stateless messages to the stateless endpoint that exposes the engine.
- [x] Develop the necessary unit tests.
- [x] Define the test cases for future integration tests.

**Comment by javiersanchz** [comment]
## Update

- I was reviewing the development done in https://github.com/wazuh/wazuh/issues/25619, and I was testing it in an environment.
- I am starting the development.

**Comment by javiersanchz** [comment]
## Update

- I have been implementing the changes to the endpoints.
- I have been running tests, and there are still things to change and the tests for them need to be implemented

**Comment by javiersanchz** [comment]
## Update

- The implementation on the endpoint is almost ready. I'll put it on hold for now to talk with Gasti about its implementation in [Router vulnerability scan message to engine /api/v1/vulnerability/scan endpoint #25621](https://github.com/wazuh/wazuh/issues/25621) on the path `/run/wazuh-server/engine.sock` and coordinate on that.
- On the other hand, I'll continue working on issues related to `4.9.x`

**Comment by javiersanchz** [comment]
## Update

- I was reviewing and seeing how the agent sends `stateless` events through the already defined `/api/v1/events/stateless endpoint`.
- I was configuring the server to send these events to the engine using the `send` method in the `EventsModule`.
- I was testing bringing up the engine environment to test the endpoint

**Comment by javiersanchz** [comment]
## Update

- I am still working on it, conducting tests to ensure it works correctly.
- I was resolving conflicts while setting up the environment with the engine and dealing with certificate issues for that.

**Comment by fdalmaup** [comment]
- Modified the StatelessEvent model according to the expected body shown in https://github.com/wazuh/wazuh/pull/25796.
- Integration test cases:
  - Successful single stateless event request.
  - Successful multiple stateless events request. 
  - Request with missing fields in the body.
  - Request without a valid authentication token.
  - Request with the wrong type of field (`event` or `wazuh`).
