### ISSUE TITLE
Upgrade from 4.8.2 to 4.9.0 -- wazuh-indexer_4.9.0-1_amd64.deb not found

### ISSUE THREAD

**Issue by KDPryor** [wazuh/wazuh#25628]
Upgrading from 4.8.2 to 4.9.0 on Ubuntu server 22.04.4 via apt-get
Following the guide at https://documentation.wazuh.com/4.9/upgrade-guide/upgrading-central-components.html I get 404 not found error when attempting to upgrade the wazuh-indexer.

```
apt-get install wazuh-indexer
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  wazuh-indexer
1 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Need to get 850 MB of archives.
After this operation, 26.6 MB of additional disk space will be used.
Err:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-indexer amd64 4.9.0-1
  404  Not Found [IP: 18.160.249.30 443]
E: Failed to fetch https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.0-1_amd64.deb  404  Not Found [IP: 18.160.249.30 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I am unsure what the problem is and would appreciate assistance very much.

**Comment by pereyra-m** [comment]
Hi @KDPryor, sorry for the inconvenience.

There was an issue with the published Wazuh Dashboard package, so the repository was temporarily disabled.
It should be working now, please try again.

Let me share with you the official announcement about this
https://wazuh.slack.com/archives/C014T3YNEH5/p1725676916840059

<details><summary>Details</summary>
<p>

![2024-09-06_23-50](https://github.com/user-attachments/assets/65ff302a-40df-454f-adc9-97a38d244db9)


</p>
</details> 

Regards.

**Comment by KDPryor** [comment]
Thank you so much! I failed to see the announcement on that and was afraid I had messed something up. I will try the upgrade again when I get back to the office on Monday. I greatly appreciate your help.

**Comment by pereyra-m** [comment]
Thanks to you @KDPryor !
