### ISSUE TITLE
WPK remote upgrade failing after upgrading to 4.9.0 ( The WPK for this platform is not available)

### ISSUE THREAD

**Issue by T100D** [wazuh/wazuh#25645]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Remote upgrade  | dnf | RPM | Rocky Linux 8.1 |

After upgrading from 4.8.2 to 4.9.0 some remote linux clienst do not upgrade.

./agent_upgrade -a 002 004 006 007 008

Upgrading...

Failed upgrades:
        Agent 002 status: The WPK for this platform is not available
        Agent 004 status: The WPK for this platform is not available
        Agent 006 status: The WPK for this platform is not available
        Agent 007 status: The WPK for this platform is not available
        Agent 008 status: The WPK for this platform is not available

The remote servers are Rocky Linux 8.1
CentOS 7.9 Upgraded successfully

**Comment by joaquinsgi** [comment]
Hi @T100D!

I reproduced your error, and we are investigating its cause. In the meantime, you can update the agent by manually downloading the WPK: https://packages.wazuh.com/4.x/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk and then upgrade it as you did before, but using the -f option and specifying the full path where the package is located.

You can use this example: /var/ossec/bin/agent_upgrade -f /path/to/wpk -a XXX

In the next documentation, you can find all WPK files for the 4.9.0 version: https://documentation.wazuh.com/current/user-manual/agent/agent-management/remote-upgrading/wpk-files/wpk-list.html

If you have any further questions feel free to ask.

Joaquin

**Comment by T100D** [comment]
Hi @joaquinsgi 

The file was present on the system on theright place.
Upgrading went well when using the -f option.
