### ISSUE TITLE
Support for AWS organisations

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#2565]
Hi team,

Amazon added support to organizations in `CloudTrail` service ([trail-organization](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-trail-organization.html)) and we do not support this feature yet.

The tasks for giving support to `CloudTrail` organizations should be the next:
- [ ] Add a new parameter (organization name).
- [ ] Update our function for getting prefixes.

**Comment by crd1985** [comment]
Closing because duplicated in https://github.com/wazuh/wazuh/issues/2473
