### ISSUE TITLE
Migrate cmocka UT execution from Jenkins to GitHub Actions

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#25653]
## Description

As part of [this](https://github.com/wazuh/internal-devel-requests/issues/1501) research, it was identified that legacy _cmocka_ UT are still running on Jenkins.

We need to create some GHA workflows to run them.

Tests should be able to run on the following operating systems:
- [x] Linux
- [ ] ~~macOS~~
- [x] Windows

Also, the following items should be carefully reviewed:
- [x] Tests should be triggered manually and with every PR.
- [ ] About the PR trigger, look at the legacy modules folders to trigger them.
- [x] Separate the logic as _actions_ from the _workflows_.

Additionally, we should be able to display the results in a more graphical way to make it easier to find the tests that failed in a run.

Note: Due to compatibility issues between the build tools and the arm64 architecture, the tests will not be run on macOS.

**Comment by sdvendramini** [comment]
## 07/10/2024
I've started with the development of the workflow and test the changes on this [PR](https://github.com/wazuh/wazuh/pull/26191)

**Comment by aritosteles** [comment]
# Update

- **2024/10/07**:
Getting acquainted with issue requirements and the work that's been done up to now.
