### ISSUE TITLE
API: Flask - Web documentation

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2566]
This issue is related to #2413

Currently, Wazuh API is generated using sphinx and running a whole environment. Once we have an openapi spec, we could generate the web doc from the spec directly. There are lots of tools to do this.
This looks fine and fits for our purposes: http://dapperdox.io/docs/overview

Tasks:
- [x] Do some research and select the best tool that fits our needs
- [x] Generate documentation with a style that fits the web
- [x] Write a README.md to explain how to use the tool

**Comment by mgmacias95** [comment]
Hello team,

I have found some candidates that could be very helpful for us:

| Tool name                                                              | Cons                            |
|:----------------------------------------------------------------------:|---------------------------------|
| [DapperDox](http://dapperdox.io/)                                      | Only works with OpenAPI 2.0     |
| [Sphinxcontrib-openapi](https://sphinxcontrib-openapi.readthedocs.io/) | Doesn't include output examples |
| [apidoc](http://apidocjs.com/)                                         | Currently used method           |
| [Sphinxcontrib-redoc](https://sphinxcontrib-redoc.readthedocs.io/)     | Doesn't match our docs design   |
| [Spectacle](https://sourcey.com/spectacle)                             | Only works with OpenAPI 2.0     |
| [Widdershins](https://github.com/mermade/widdershins)                  | Doesn't match our docs design   |

We could modify the generated API page to match our documentation design in case we want to use ReDoc or Widdershins.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello team,

I think the more convenient tool is [`ReDoc`](https://github.com/Rebilly/ReDoc). It doesn't fit our current documentation style, we will need from the @wazuh/content team here.

The tool is very simple to use, it's just using [this HTML](https://github.com/Rebilly/ReDoc#tldr) replacing the spec URL with ours.

To work locally with the documentation, `redoc-cli` must be used. The steps to use `redoc-cli` are:
1. Install it using `npm`:
    ```shellsession
    $ npm install redoc-cli --global
    ```
2. Serve the spec:
    ```shellsession
    $ redoc-cli serve .\Documents\GitHub\wazuh\api\api\spec\spec.yaml -w

    Server started: http://127.0.0.1:8080
    👀  Watching C:\Users\Marta\Documents\GitHub\wazuh\api\api\spec for changes...
    ```
3. Open `localhost:8080` in your browser.

Best regards,
Marta
