### ISSUE TITLE
Wazuh dashboard vulnerability detection filter by endpoint group

### ISSUE THREAD

**Issue by jcasals** [wazuh/wazuh#25662]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-1 | Wazuh dashboard | Manager | Packages| AlmaLinux9/Centos7 |

Hi,

First of all, I know I have seen a similar request somewhere but now I can't find it again, so I'm opening this issue, but feel free to point me to the right place if needed. 

We are moving from a basic tool to detect CVEs to Wazuh, which gives us a lot more tools than expected (which in this case it's great!) but for the moment we are focused on tracking vulnerabilities and exposures, to then mitigate them based on criticity and needs. 

We could install a single server wazuh instance and see how it was working by updating packages and seeing endpoints disappear from the CVE lists, _but_, there is something that we would like to have, or maybe I couldn't find how to do it. 

Our previous tool only let us have one group per endpoint, and Wazuh lets us have multiple groups, which in our case is extremely useful, since we can assign groups based on type of machine but also by VLAN the server is in, which increases or decreases criticity. The problem is that it seems wazuh can not filter by endpoint group in the vulnerability detection part of the dashboard. I can't seem to find the right variables to search in the searchbox, in case there are. 

Is this something that can be done in some way, or is this something that you plan to add in future releases?

Thank you so much,

Jordi

**Comment by eglyn** [comment]
Same question here, we have to filter by group because groups haven't the same criticity, group filter works on agent view, but not on vulnerabilities view :/

**Comment by pereyra-m** [comment]
Hello @jcasals 

Thank you for your comments. We keep working to improve Wazuh.
This situation was commented on here also:
- https://github.com/wazuh/wazuh/issues/24118

I understand the problem and currently, the vulnerabilities' index doesn't store information from the agent groups. The team will make major improvements in a future major release, here you can see more details
- https://github.com/wazuh/wazuh/issues/22887

Regards.

**Comment by marcinliszka12** [comment]
Please add labels to Vulnerability evens like in Threat module.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if necessary

**Comment by branchnetconsulting** [comment]
Historically, the only way I'm aware of being able to make Wazuh alerts or events of any kind reflect the group membership of the related agent, has been to apply group-specific agent labels to each group's agent.conf.   Thus once Wazuh solves the problem of non-inclusion of agent labels in Vulnerability Detection inventory records, filtering vulnerabilities on the inventory side by agent group will be indirectly possibly by filtering on group-specific agent labels.

**Comment by branchnetconsulting** [comment]
Re: "The team will make major improvements in a future major release"
5.0 is way, way too late to be addressing the failure to include agent labels in Vulnerability Detection inventory records.  Way more is at stake with that than just supporting the filtering of VD inventory by endpoint group.

**Comment by d0j05u8** [comment]
I've seen this issue floating around in a few different places and it looks like the definitive answer is that group filtering is not yet a feature offered by the platform.

However, you can achieve a similar result by creating custom DQL queries which can be saved and used later. You have the option to save a timeframe when saving the query. As long as you don't use that option you can use the saved query to filter your present data.

Note that this option does not apply to every index (dashboard) and each filter needs to be created per index. For example the "A-Pod" group would need discrete filters for each view (i.e. "FIM A-Pod", "Vulnerability Detection A-Pod", etc).
