### ISSUE TITLE
Improve Intune ruleset

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#25674]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.10.0 | MS-Graph | Manager/Agent | Packages/Sources | All |

## Description

As part of https://github.com/wazuh/wazuh/issues/24498, the `ms-graph` module was extended to collect Intune logs as well.

Since only generic rules were developed for these new logs, we need to investigate and analyze some real logs to improve this set of rules.

Tasks to do:
- [ ] Collect a sample of logs.
- [ ] Analyze them, identify useful alerts, and categorize them by severity.
- [ ] Create specific rules for the logs identified in the previous step.

**Comment by TomasTurina** [comment]
I'm closing this one since we didn't get the requested logs.

cc @vikman90 @gdiazlo

**Comment by vikman90** [comment]
@TomasTurina We've been provided with a brief list of events. Let's see if we can use them to extend the ruleset.

Best!
