### ISSUE TITLE
API: Flask - Implement new path location

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#2568]
This issue is related to #2413

We should decide carefully the proper path where the API is located due to implications in scripts and config files.

My proposal is to install the new API under /var/wazuh/api. However, the API python package will be installed under the standard python packages folder.

Tasks:
- [x] Decide the API path
- [x] Review all references to API home folder and adapt to the new one

**Comment by mgmacias95** [comment]
This is how the API installation looks right now:
```shellsession
# ls -l /var/ossec/api/
total 4
drwxr-x--- 2 root ossec 4096 Mar  5 16:03 configuration
```
And this is how the API python package looks right now:
```shellsession
# ls -l /var/ossec/framework/python/lib/python3.7/site-packages/api-3.9.0-py3.7.egg/api/
total 36
-rwxrwxrwx 1 root root  834 Mar  5 16:03 APIException.py
-rwxrwxrwx 1 root root    0 Mar  5 16:03 __init__.py
drwxr-xr-x 2 root root 4096 Mar  5 16:03 __pycache__
-rwxrwxrwx 1 root root  371 Mar  5 16:03 authentication.py
-rwxrwxrwx 1 root root 3290 Mar  5 16:03 configuration.py
drwxr-xr-x 3 root root 4096 Mar  5 16:03 controllers
-rwxrwxrwx 1 root root  597 Mar  5 16:03 encoder.py
drwxr-xr-x 3 root root 4096 Mar  5 16:03 models
drwxr-xr-x 2 root root 4096 Mar  5 16:03 spec
-rwxrwxrwx 1 root root 3677 Mar  5 16:03 util.py
```
