### ISSUE TITLE
Fail vulnerability-scanner-tests

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#25692]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Wazuh component | Manager/Agent | Packages/Sources | OS version |

In the task routine scheduled to run the integration test check for `wazuh-manager` (https://github.com/wazuh/wazuh/issues/25685 issue tracker tests), a failure been detected in the vulnerability-scanner-modules-qa workflow.

As detailed in the comments these tests failed in [4.9.1](https://github.com/wazuh/wazuh/issues/25685#issuecomment-2342962801) and [4.10](https://github.com/wazuh/wazuh/issues/25685#issuecomment-2342963198).

It is necessary to fix this and check which branches it is affecting.

**Comment by sebasfalcone** [comment]
## Update
Task finished, acomodated ETA for its review
