### ISSUE TITLE
Bug in decoder interpreter

### ISSUE THREAD

**Issue by rwagner-inf** [wazuh/wazuh#257]
I'm creating a custom decoder for pfSense.
The decoder follows:
```

<!-- PFSENSE
Nov  8 12:37:34 pfSense filterlog: 5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166
 -->
<decoder name="pf">
  <prematch>^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
</decoder>

<decoder name="pf_filterlog">
  <parent>pf</parent>
  <regex offset="after_parent">^ filterlog: \d+,,,(\d+)</regex>
  <order>id</order>
</decoder>
```

When testing with ossec-logtest, putting a log entry with only 1 digit in the day field of the date the decoder does not work.
If I put 2 digits in the date day field it works. This is strange.

Here is an example:
![image](https://user-images.githubusercontent.com/24550871/32606324-ac044276-c533-11e7-8073-6b4031764600.png)

I also tried putting the following:
```
<prematch>^\w\w\w  \d \d\d:\d\d:\d\d pfSense|^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\.*pfSense</prematch>
and
<prematch>^\w\w\w  \w \d\d:\d\d:\d\d pfSense|^\w\w\w  \d+ \d\d:\d\d:\d\d pfSense</prematch>
and
<prematch>^\w\w\w\s\s\d+ \d\d:\d\d:\d\d pfSense</prematch>
```

None of these ways worked, just with the \d+ and 2 digits in day field of log entry.

**Comment by vikman90** [comment]
Hi @rwagner-inf,

I think this is a duplicate issue: https://github.com/wazuh/wazuh/issues/51#issuecomment-259949331

This is not exactly a bug although it can be improved. The thing is that events go through a pre-decoding stage that tries to parse them as standard Syslog events. As I explained in the issue above, Syslog events specify date as two-digit number, if this number is lower than 10 it will contain a leading space.

The host name is after the date and then is the program name.

In your case, the second log had the leading space (that should replace the ten) has two digits (18) and this cancels the predecoder.

So your log's hostname is "pfsense", the program name is "filterlog" and the actual content content is:

```
5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166
```

Let me suggest you this decoder:

```xml
<decoder name="pf">
  <program_name>filterlog</program_name>
  <regex>^\d+,,,(\d+)</regex>
  <order>id</order>
</decoder>
```

It extracts the hostname, the program name and the `id` field as I think you need:

```
Nov  8 12:37:34 pfSense filterlog: 5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166


**Phase 1: Completed pre-decoding.
       full event: 'Nov  8 12:37:34 pfSense filterlog: 5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166'
       hostname: 'pfSense'
       program_name: 'filterlog'
       log: '5,,,1000102433,em0,match,block,in,4,0x0,,128,24677,0,none,17,udp,186,10.9.0.119,10.9.0.255,17500,17500,166'

**Phase 2: Completed decoding.
       decoder: 'pf'
       id: '1000102433'
```

Hope it help.
Best regards.

**Comment by rwagner-inf** [comment]
Hi @vikman90 !

It really works that way. But the timestamp field is wrong, as the print below shows:

![image](https://user-images.githubusercontent.com/24550871/32725978-04ef2638-c856-11e7-84fe-6c9be417716f.png)


How do you solve this?

**Comment by vikman90** [comment]
Hi,

The `timestamp` field is always the time when the alert was produced. This is a convention. Unfortunately, the timestamp is not extracted from the source message. But we investigated it and added the data you mentioned in the `predecoder.timestamp` field, for a future version: https://github.com/wazuh/wazuh/commit/846ca232424aae7bc352b08bd920ef2c251a3874

This is a sample of an alert for the log: `Nov 13 21:52:00 localhost salute: Hello world`:

```
{
  "timestamp": "2017-11-13T21:52:55-0800",
  "rule": {
    "level": 5,
    "description": "Salute alert.",
    "id": "100001",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "local",
      "syslog",
      "sshd"
    ]
  },
  "agent": {
    "id": "000",
    "name": "ubuntu"
  },
  "manager": {
    "name": "ubuntu"
  },
  "id": "1510638775.28698",
  "cluster": {
    "name": "wazuh",
    "node": "node01"
  },
  "full_log": "Nov 13 21:52:00 localhost salute: Hello world",
  "predecoder": {
    "program_name": "salute",
    "event_timestamp": "Nov 13 21:52:00",
    "hostname": "localhost"
  },
  "decoder": {},
  "location": "/var/log/myapp.log"
}
```

I hope you find it useful.
Best regards.

**Comment by rwagner-inf** [comment]
Hi @vikman90, great news!
Thanks!
