### ISSUE TITLE
Review `cluster.json` configuration file

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25702]
| Related task |
|---|
| https://github.com/wazuh/wazuh/issues/25193 |

## Description

This Issue aims to review the `cluster.json` file and validate if there is any configuration option that can be useful for the client. We should check each one of the configuration options of `cluster.json` and document which could be useful to be added to the centralized configuration file. Finally, in the case of using one of the configuration options in the new centralized configuration, we should review the code changes we should make to the cluster.

> Some changes were made to the `cluster.json` in https://github.com/wazuh/wazuh/issues/25648. We should review the new schema. 

## Requirements
- [x] Review the `cluster.json` configuration file.
- [x] Document which configuration options should be migrated to the centralized configuration file.
- [x] Review if it is necessary to change or redefine the structure of the configuration options in yaml.
- [x] Review code changes in case of configuration migration.

**Comment by RamosFe** [comment]
## `cluster.json` Configurations
### Files configuration options

This part of the `cluster.json` file includes the files to be distributed between the server nodes. This is an internal configuration, and the user shouldn't have any useful use for this configuration part. 


https://github.com/wazuh/wazuh/blob/cf1a7af9cbaacc8539f48343663ca65b37601600/framework/wazuh/core/cluster/cluster.json#L2-L25

### Interval configuration options

This part of the file includes configuring some options related to intervals and the communication protocol between the workers and the master. Most configuration options are related to parameters that affect the internal communication protocol and aren't of much use to the User.

https://github.com/wazuh/wazuh/blob/cf1a7af9cbaacc8539f48343663ca65b37601600/framework/wazuh/core/cluster/cluster.json#L27-L53

## Conclusion

All of the configurations in the `cluster.json` file are used as parameters for multiple parts of the internal communication protocol of the Cluster. These configuration options are only intended for internal use and should remain the same since it is not something that would be useful for the user to configure.

**Comment by GGP1** [comment]
## Review

Althought I agree with the fact that this configuration is very technical and most users won't change it, I do think it could be useful to offer the possibility of tweaking these values in 5.0.

To mention a use case that comes to mind, in a cluster without many group changes, one could opt to increase the values `master.recalculate_integrity` and `worker.sync_integrity` significantly to avoid using unnecessary CPU and request calls every ~10s.

Another example could be that a user considers the `communications` timeouts to be too big and would prefer lowering them to detect performance issues earlier.

It's really hard to accomodate all users with hardcoded values, and I think that's the reason they were included in a configuration file in the first place.

Because of that, I consider we should review these fields one by one and decide which one to expose in the configuration and which one to not include.

**Comment by RamosFe** [comment]
## Update

I continue reading the code and documenting the use of each of the configuration options. I am also documenting some improvements to the process itself, because of the code reading multiple times the file when it could read one time (especially knowing that the contents don't change).

I am also documenting the accesses to the `cluster.json` file to separate the new configuration from the internal one (the actual `cluster.json`).

**Comment by RamosFe** [comment]
## Update

Passed to `on-hold` due to Issues with more priority.

**Comment by RamosFe** [comment]
# Interval configuration options
## Description

The configuration key `intervals` have multiple configuration options divided into different sections:
- `master`: Configuration related to the master.
- `worker`: Configuration related to the worker.
- `communication`: Configuration related to the communication protocol of the cluster.

I will be analyzing each of the sections and their configuration option to check if there is any option that could be useful for the user.

### Master section
| Option   |      Description      |  Should be public? |  Reason |
|----------|:-------------:|------| ------|
|process_pool_size| The maximum number of workers that the server can use to handle requests. | Yes | Allow the user to set a limit on the number of cores used by the master |
|timeout_extra_valid| The timeout value used when processing a file from a worker | No | The more files the worker sends to the master, the bigger this timeout must be. Because the number of files to send is an internal configuration, this should also be internal. |
|recalculate_integrity | Time interval between consecutive integrity checks. | - | |
| check_worker_lastkeepalive | Determines how frequently the server checks if it has received a "keep alive" signal from its clients. | Yes | Allows the user to set bigger or smaller frequencies depending on their topology. |
| max_allowed_time_without_keepalive | Determinate when to disconnect a connection based on when the last keep alive was received. | Yes | Allows the user to set a bigger or smaller timeout for client disconnection. This configuration should be bigger than check_worker_lastkeepalive to avoid clients' disconnection. |
| max_locked_integrity_time | How long a lock (in this case, a permission flag) can remain in place for an integrity check before being automatically released. | No | This configuration is related to the implementation of the cluster. |


### Worker section
| Option   |      Description      |  Should be public? |  Reason |
|----------|:-------------:|------| ------|
| sync_integrity | Defines how frequently the worker synchronizes its file integrity data with the master. | - | |
| keep_alive | Determines how frequently the client sends a `keep alive` signal to the master| Yes | If `check_worker_lastkeepalive` and `max_allowed_time_without_keepalive` are configurable, this option should also be configurable. |
| max_failed_keepalive_attempts | Determines the maximum number of consecutive failed `keep alive` attempts that the client can make before disconnecting from the server. | - | | 
| connection_retry | How long the system waits before attempting to reconnect to the server after a connection failure. | - | |

### Communication section
| Option   |      Description      |  Should be public? |  Reason |
|----------|:-------------:|------| ------|
|zip_limit_tolerance | Tolerance factor applied when adjusting the zip file size limits | No | This configuration option is related to the compression method used in the cluster and should maintain internal.|
| compress_level | Defines the compression level used when compressing the files | No | This configuration option is related to the compression method used in the cluster and should maintain internal. |
| min_zip_size | Minimum size for the zip file | No |This configuration option is related to the compression method used in the cluster and should maintain internal. |
| max_zip_size | Maximum size for the zip file | No | This configuration option is related to the compression method used in the cluster and should maintain internal.| 
| timeout_receiving_file | Maximum amount of time allowed for sending the compressed file during the synchronization process | No | This configuration option is related to the compression method used in the cluster and should maintain internal. |
| timeout_dapi_request | Maximum amount of time (in seconds) that the system will wait for a response to a DAPI request | Yes  | Allow the user to set the limit in case the connection between the nodes in the cluster is slow. |
| timeout_cluster_request | How long the system will wait for a response from the cluster. | Yes | Allow the user to set the limit in case the connection between the nodes in the cluster is slow.|

**Comment by RamosFe** [comment]
## Update 
### Code usage and new format

The schema should be maintained in `yaml`, replacing the `json` format to `yaml`. There isn't very big changes, due to only being migrated the `intervals` configuration. Finally the configuration options are used on only 3 files of the project:
- `framework/wazuh/core/cluster/common.py`
- `framework/wazuh/core/cluster/master.py`
- `framework/wazuh/core/cluster/worker.py`

**Comment by GGP1** [comment]
## Review

After reviewing the configuration options one by one, I couldn't find a reason why not to expose all of them.

Options like `compress_level`, `zip_limit_tolerance` and `max_zip_size` are useful to lower or limit the size of the files that are being synchronized among nodes, perhaps because of limited storage space.

Similarly, `min_zip_size` can be used to do a single bigger synchronization instead of many small ones, letting the users choose whether to batch tasks.

Furthermore, `timeout_receiving_file` and `timeout_extra_valid` are the same as `timeout_dapi_request` but for different operations, so I don't see why we one should be public and the others not.

Lastly, `max_locked_integrity_time` may sound super specific but by chaning that value, a user could tweak how often the integrity sync operation is permitted and thus performed in his cluster.

**Comment by RamosFe** [comment]
## Update

After the suggestions, I updated the table to mark which configuration options should be the default, meaning that they aren't part of the minimum required configuration defined in https://github.com/wazuh/wazuh/issues/25697. Still, they have a default value that the user can overwrite if it wants to.

This allows us to migrate all the configuration options of the `cluster.json` to the new centralized configuration and enable the user to configure them if needed, but it avoids overwhelming the user with so many configurations and does not force you to configure them if you are not interested.

**Comment by GGP1** [comment]
## Review

The `Should be default?` section is a little bit confusing. Users should be able to execute the cluster without specifying **any** option (default values will be used), or specifying only some of them (default values would be overwritten by the user-defined values for those options). Meaning that all fields should have a default value.

Other than that, I think the investigation completed the tasks for this issue. LGTM.

**Comment by fdalmaup** [comment]
# Review

After checking the analysis of the current contents of the `cluster.json` file, I agree with what was mentioned by @GGP1, unless there is something that the user must define, every option will use a default value. We can conclude that every field must have a default value that can be modified and/or extended (for the `files` case) in the upcoming centralized configuration of the server.

Please, @RamosFe, modify the contents of the comment https://github.com/wazuh/wazuh/issues/25702#issuecomment-2383981401 for its final version with the defined conclusions.

**Comment by fdalmaup** [comment]
# Review

Analysis completed. LGTM
