### ISSUE TITLE
Support on CTI service application addition

### ISSUE THREAD

**Issue by mazayahamdallah** [wazuh/wazuh#25714]
Dear Wazuh Development Team,

As I understand, starting from version 4.8.0, Wazuh no longer uses the CPE helper to detect application vulnerabilities, but instead relies on the CTI service provided by Wazuh. 

I would like to inquire if it is possible for users to request the addition of applications to the CTI service’s vulnerability detection list, especially for applications that might not currently be included. To support such a request, am I correct in assuming that I would need to provide a .json file with the relevant application details?

Please let me know if my understanding is correct, or if any additional steps are required.

Thank you for your time and assistance.

**Comment by Damian-Mangold** [comment]
@jftuduri please take it.

**Comment by jftuduri** [comment]
Hello @mazayahamdallah !

> As I understand, starting from version 4.8.0, Wazuh no longer uses the CPE helper to detect application vulnerabilities, but instead relies on the CTI service provided by Wazuh.

Yes, that is correct. We now call this configurations `translations`.

It is possible,  and encouraged, to request the addition of applications to the CTI service’s vulnerability detection list as this helps improve the overall coverage and ensures the detection of vulnerabilities for more applications.

To request additional translations, please follow these steps:

- Create an issue with the title: `'Add translation for <package_name>'`
- In the issue body, include the following details:
  - Syscollector information for the package:
     - You can obtain this using the Wazuh API: [Syscollector packages API reference](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_packages_info)
  - OS information for the machine where the package is installed:
      - This can also be retrieved via the API: [OS Info API reference](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.syscollector_controller.get_os_info)
   - Vulnerabilities list (if you know of any) related to the package, as this would be helpful for validation.

Once submitted, the team will review the information and generate the necessary translation to enable vulnerability detection for the specified package.

Let me know if you have any problem with this.
Regards!

**Comment by mazayahamdallah** [comment]
Hi @jftuduri !

Thanks for the info. I will raise the issue and provide details. Please check on that issue to ensure my understanding is correct. Thank you

**Comment by jftuduri** [comment]
Hi @mazayahamdallah ,
I took a look at the file you uploaded, and there are a couple of things to note. 
It looks like there are some JSON formatting issues that are preventing it from being parsed correctly, and also I couldn’t find the OS information in there.

If you’re running these queries from the command line, you might find it easier to do it directly from the dashboard. In `Server Management -> Dev Tools` you can run each query and export the results:

- For packages: `GET /syscollector/003/packages`
- For OS info: `GET /syscollector/003/os`

I noticed there are 500 packages listed, which is quite a bit to handle at once. While we aim to cover as many products as possible, it's a progressive process. It might be helpful if you could highlight the most important packages for detecting vulnerabilities. 

As a final note, if you have the CPE helper file you were using, sharing that could also speed things up.

Regards!

**Comment by mazayahamdallah** [comment]
Hi @jftuduri,

Thank you for your response. So it should be 2 separate files which contain packages and OS? >I think the result of OS info might be the same for several agents. I will combine the multiple OS information. We are working on listing most important packages that we use in our organization.

Unfortunately, we don't have CPE helper file for current application packages. 

I will back to you when there is update.

Thank you

**Comment by jftuduri** [comment]
> So it should be 2 separate files which contain packages and OS?
Yes, one query will have all the packages information, and the other will be just the info of the OS.

>I think the result of OS info might be the same for several agents. I will combine the multiple OS information.
If you have multiple agents using the same OS, just the result of one of the `GET /syscollector/<AGENT_ID/os` query from one of these agents is enough.

**Comment by mazayahamdallah** [comment]
Hi @jftuduri 

Thank you for the wait. 

Hereby I attach the listed application/package list. I've tried to sort the applications, but since there are various applications that my organization use, so I concluded to submit attached list. 

I also want to attached the OS information of my organization. Please kindly check. Thanks.

[agent_os_information.json](https://github.com/user-attachments/files/17055545/agent_os_information.json)
[modified_all_packages.json](https://github.com/user-attachments/files/17055546/modified_all_packages.json)

**Comment by Damian-Mangold** [comment]
@jftuduri, could you please create an issue template that includes a structured format with all the necessary information required for reporting false positives or false negatives in vulnerability detection? It should ensure that all relevant details are captured to facilitate a thorough investigation and resolution of the reported issues.

**Comment by jftuduri** [comment]
Hi @mazayahamdallah , I have one more request. Could you please edit the [other issue](https://github.com/wazuh/wazuh/issues/25719) by attaching the new files you provided above (and removing the first one) so that we have all the necessary information in one place?

If you prefer, I can take care of it for you, but it would be more consistent with our process if you did it. Apologies for the inconvenience!

In the meantime, I'll start analyzing the list of packages.

**Comment by Damian-Mangold** [comment]
Reviewed. 

Status of the user's query: resolved.
