### ISSUE TITLE
wazuh-manager aarch64 deb and rpm downloads missing

### ISSUE THREAD

**Issue by justinludwig** [wazuh/wazuh#25727]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-1 | wazuh-manager | Manager | packages.wazuh.com | Linux aarch64 |

The aarch64 versions of the wazuh-manager deb and rpm downloads linked from the Packages List page of the Wazuh Installation Guide seem to be missing.

### Repro steps

1. Navigate to https://documentation.wazuh.com/current/installation-guide/packages-list.html
2. Scroll down to the "Wazuh manager" table
3. Click the "Package" link for the "aarch64" package of the "Amazon Linux" distribution (the link is labeled "wazuh-manager-4.9.0-1.aarch64.rpm", and the URL is https://packages.wazuh.com/4.x/yum/wazuh-manager-4.9.0-1.aarch64.rpm)

### Actual Result

An XML error page displays with the following message.

    <Error>
        <Code>NoSuchKey</Code>
        <Message>The specified key does not exist.</Message>
        <Key>4.x/yum/wazuh-manager-4.9.0-1.aarch64.rpm</Key>
        <RequestId>HJHAK86PH88N7QVZ</RequestId>
        <HostId>Qsob4BHmmg7OBPzL6d0kV3M939jhl3DVK4XilOXO8iS9Q2wC214Lb2/VSNmquINUwBthbBMlLDY=</HostId>
    </Error>

### Expected Result

Download the wazuh-manager-4.9.0-1.aarch64.rpm file.

### Notes

A similar error page is shown for the aarch64 deb packages (from this URL: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.0-1_arm64.deb).

However, the x86_64 version of the wazuh-manager deb and rpm packages download as expected; and the both the aarch64 and x86_64 versions of the wazuh-agent deb and rpm packages download just fine, as well.

**Comment by joaquinsgi** [comment]
Hi @justinludwig!

What you just saw is a discrepancy we're already working on in this issue: https://github.com/wazuh/wazuh-documentation/issues/7774. Since version 4.9.0, the Wazuh manager for ARM systems is not available, we are working on providing deployment for all the Wazuh central components in the future for ARM architectures. 

Thanks for your comment. If you have any other questions, feel free to ask.

**Comment by justinludwig** [comment]
I see; the aarch64 packages for wazuh-manager are no longer shown on the Packages List page. Thanks.
