### ISSUE TITLE
Add and verify new QA Test Cases for VDP v1.0.2

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#25769]
## Description

The new version of VDP v1.0.2 aims to address false positives and false negatives in vulnerability detection. As part of the release verification process, it is essential to run tests that validate the changes in the content.

## Expected

1. **Add New Test Cases:**
   - Integrate the new test cases into the existing [QA test suite for the vulnerability detector](https://github.com/wazuh/wazuh/tree/master/src/engine/source/vdscanner/qa).
   
2. **Execute Tests:**
   - Run the QA test suite with the new content introduced in VDP v1.0.2
   - Ensure that all new test cases pass successfully and verify that the behavior is as expected.

3. **Analyze Test Results:**
   - Review the results of the test execution.
   - Identify if any of the existing test cases fail and analyze the reason for the failure.
   - Document any issues found and provide an analysis of the root cause.

## Deliverables

- [x] Updated QA Test Suite: The QA test suite updated with new test cases.
- [x] Test Execution Report: A detailed report of the test execution results, including any identified issues and their root causes.

**Comment by jftuduri** [comment]
# Update
- Tests added.
- I want to run some extra verifications before moving it to pending review

**Comment by jftuduri** [comment]
# Update
- Full tests report added
