### ISSUE TITLE
Write Unit Tests for WMI API Integration

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25767]
**Parent Issue:**

- #25760

## Description

This task involves creating unit tests to ensure that the new functionality of retrieving installed updates via the WMI API works as expected and is properly integrated into Syscollector.

## Requirements

- Write unit tests to cover the WMI API integration logic.
- Ensure that tests cover different scenarios, including potential error handling and edge cases.

## Definition of Done

- [x] Unit tests for the WMI API integration are written and pass successfully.
- [x] Test coverage is sufficient to ensure the reliability of the new feature.

**Comment by lchico** [comment]
# Update
- I started working on this task and conducting research on possible approaches for implementing these unit tests.
