### ISSUE TITLE
Remove `getopt` lib and `libcurl` usage from HP-UX/AIX/SOLARIS

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#25789]
# Description

Hello team, during the development of the [anti_tampering ](https://github.com/wazuh/wazuh/issues/24908)function, a new function getopt_long was included in agentd, this function requires the getopt.h library, and this is not compiled in HP-UX/AIX/SOLARIS, given the difficulties, we think that the best option is to remove this anti_tampering functionality from the HP-UX/AIX/SOLARIS agent, since it is not intended to be used in these systems as well.

Currently the compilation of these systems cannot be completed correctly due to this error:

```
[2024-09-19T11:58:53.872Z] [0;33m   15 | #include <getopt.h>[0m
[2024-09-19T11:58:53.872Z] [0;33m      |          ^~~~~~~~~~[0m
[2024-09-19T11:58:53.872Z] [0;33mcompilation terminated.[0m
[2024-09-19T11:58:53.872Z] [0;33mgmake[1]: *** [Makefile:2087: client-agent/main.o] Error 1[0m
[2024-09-19T11:58:53.872Z] [0;33mgmake: *** [Makefile:859: agent] Error 2[0m
[2024-09-19T11:58:53.872Z] [0;33mgrep: can't open /etc/os-release[0m
```
https://ci.wazuh.info/job/Packages_builder_special/1078/consoleText

In addition, we also have problems using libcurl on these systems:
```
ld: Unsatisfied symbol "curl_easy_getinfo" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_easy_cleanup" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_easy_setopt" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_easy_strerror" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_slist_free_all" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_slist_append" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_easy_perform" in file libwazuh.a[url.o]
ld: Unsatisfied symbol "curl_easy_init" in file libwazuh.a[url.o]
```

# Testing
Using:
![image](https://github.com/user-attachments/assets/958f64c5-a594-482b-ae00-844b6fdfbb31)

Execution pipelines:
- HP-UX: https://ci.wazuh.info/job/Packages_builder_special/1088/
- AIX: https://ci.wazuh.info/job/Packages_builder_special/1087/
- Solaris 10: https://ci.wazuh.info/job/Packages_builder_solaris/31880/
- Solaris 11: https://ci.wazuh.info/job/Packages_builder_solaris/31881/

**Comment by vikman90** [comment]
HP-UX and AIX libraries definitely do not support the getopt_long function, which is used to receive parameters with long names, like `uninstall_auth_token` instead of `-t` for example.

So, we have two options:
1. Drop anti-tampering support on HP-UX and AIX.
2. Modify the new anti-tampering options to use only single-letter parameters.

**Comment by jotacarma90** [comment]
# Update 19/09/2024
- Issue/PR created after analysis and check of the compilation error found.
- Removed anti_tampering function from AIX and HP-UX.
- Created issue request to both VM to check Jenkins pipelines: https://github.com/wazuh/internal-devel-requests/issues/1586
