### ISSUE TITLE
Please make Wazuh Kibana App compatible with Search Guard 

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#258]
I read in this thread that there are known issues with certain parts of the Kibana App breaking due to issues with Search Guard.  

https://groups.google.com/d/msg/wazuh/9UJ9-6YcjBo/vJ2zypVpAgAJ

I have a client with a Wazuh deployment who wants to deploy Search Guard soon, and need it not to break the Wazuh Kibana App.

Thanks,
Kevin

**Comment by JuanjiJG** [comment]
Hi @branchnetconsulting and sorry for the late response.

We've added this request to our internal roadmap for further debate and research. Thanks for the suggestion!

Best regards,
Juanjo

**Comment by DaspawnW** [comment]
Hi @JuanjiJG,

Is there any progress on it?

**Comment by branchnetconsulting** [comment]
Still interested here, too.  We'd really like to be able to use our Search Guard license on our new Elasticsearch cluster but the Kibana web app is important to us, too.  We are available to help test.

**Comment by JuanjiJG** [comment]
Hello @DaspawnW and @branchnetconsulting,

We don't have specific dates yet to develop this feature for the Wazuh App.

We would like to know about your current needs with this integration. Why do you need it? Are you experiencing errors when using the Wazuh App?

Thanks for your feedback.

Regards,
Juanjo

**Comment by DaspawnW** [comment]
Hi @JuanjiJG,

I only saw this issue and tried to ask for the functionality ;-)

Best regards,
 Björn

**Comment by branchnetconsulting** [comment]
After we install our new Elasticsearch cluster next week, we plan to install the latest Search Guard as well as the latest Wazuh Kibana app.  We will be happy to share our findings at that time.

**Comment by JuanjiJG** [comment]
Hello again  @branchnetconsulting,

Thank you so much for your feedback, we'll wait for your findings.

Regards,
Juanjo

**Comment by ajohnson8503** [comment]
I was able to get Wazuh working with Search Guard in place. What I did was install Wazuh running on its own server with a local Logstash which pointed to our Elasticsearch Cluster and our Kibana server. Once that was all connected and working with the Secure API connection. I installed Search Guard and configured it. The only thing I had to do was redo the Wazuh API connection and Kibana Plugin worked fine. The last step was to setup the "Elasticsearch output" in the Logstash and sg_role settings per Search Guard.

The only thing with all of this was you have to give sg_logstash the below settings in the sg_role which I don't really want to do. If Wazuh could figure out a better way to play with Search Guard when it comes to indices.

**Comment by branchnetconsulting** [comment]
Hi ajohnson,

Thanks for sharing your experience.  It appears your message may have been
clipped.  Just what sg_role settings did you end up giving to sg_logstash?

Kevin

**Comment by ajohnson8503** [comment]
under indices you have to add the following which is the only way I was able to get to work. I really don't like the '*','*' with admin/create but this is only a test system so nothing important.
    'wazuh-alerts-3.x-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*':
      '*':
        - "indices:admin/create"
        - ALL

**Comment by novaksam** [comment]
+1

I have an existing searchguard installation that I want to add Wazuh into; the role at https://groups.google.com/d/msg/wazuh/9UJ9-6YcjBo/fZYHXfU2AAAJ seemed to help, but I'm unable to get the main dashboard loaded.

I also tried seeding an API configuration into my cluster .wazuh index, but it's complaining about invalid JSON format for a checkstoredAPI call.

**Comment by JuanjiJG** [comment]
Hello everybody,

We've made some progress in order to make the app compatible with SearchGuard (but it's not finished yet).

You can read more information about it here: https://github.com/wazuh/wazuh-kibana-app/issues/913

We'll proceed to close this issue. If you have comments or problems about this, please open a new thread on the [Wazuh Kibana app repository](https://github.com/wazuh/wazuh-kibana-app/issues).

Thanks for your patience on this matter.

Regards,
Juanjo
