### ISSUE TITLE
Engine - Develop `engine-policy` to manage policies

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25815]
### Description:
The goal of this task is to develop `engine-policy`, a Python script that replaces the `policy` command of the Wazuh-Engine CLI. This new tool will manage policies, allowing for creation, deletion, modification, and asset management within policies.

### Requirements:
- Create, delete, and modify policies in Wazuh-Engine.
- Add or remove assets from policies.
- Ensure compatibility with existing API endpoints that interact with policies.
- Implement error handling and logging to maintain robustness and traceability.

### Deliverables:
- A fully functional `engine-policy` script integrated into the Wazuh-Engine's tooling suite.
- Comprehensive unit tests to cover new functionalities.
- Documentation updates to reflect how to use `engine-policy` within the development environment.

### DoD (Definition of Done):
- [ ] The `engine-policy` script is implemented and tested.
- [ ] Documentation is updated and clear instructions are provided.
- [ ] The tool is reviewed and merged into the main development branch.

**Comment by JcabreraC** [comment]
Extended ETA. The above issues have not been implemented due to priority in other issues.

**Comment by juliancnn** [comment]
## Update

Functionality is almost complete, documentation is missing, manual tests, changing prints to sys.exit and I will create the PR. I do not upload the commit because it is based on the catalog, waiting for merge of https://github.com/wazuh/wazuh/issues/25815
