### ISSUE TITLE
Engine - Develop `engine-catalog` as a replacement for the `wazuh-engine catalog` CLI command

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25814]
### Description:
The `engine-catalog` script will replace the existing `wazuh-engine catalog` CLI command, inheriting all its functionalities with enhancements to facilitate operations via API calls. This script will manage the catalog of assets within Wazuh-Engine, supporting operations such as adding, removing, updating, validating assets, and retrieving lists of assets by type and namespace. It must handle asset definitions in both YAML and JSON formats, ensuring compatibility and ease of integration within the new architecture.

### Tasks:
1. **Development of the `engine-catalog` Script:**
   - Implement functionalities to add, remove, update, and validate assets in the catalog.
   - Enable fetching of asset lists filtered by type and namespace.

2. **Support for Multiple Data Formats:**
   - Ensure the script can handle asset data in both YAML and JSON formats seamlessly.

3. **Integration with Wazuh-Engine API:**
   - Develop the script to interact with the Wazuh-Engine API for all operations instead of direct CLI commands.

4. **Documentation:**
   - Document the usage, features, and examples of the `engine-catalog` script in the Wazuh-Engine documentation.
   - Update the API and developer guides to include information on the new script.

### Expected Outcome:
A fully functional `engine-catalog` script that provides a robust interface for managing the Wazuh-Engine catalog, replacing the need for the original CLI command and enhancing the system's flexibility and API-driven interaction.

This implementation aims to ensure a smooth transition from the CLI-based asset management to a more scalable and manageable API-driven approach, aligning with the broader goals of enhancing Wazuh-Engine's configurability and ease of use.

**Comment by JcabreraC** [comment]
Extended ETA. The above issues have not been implemented due to priority in other issues.

**Comment by juliancnn** [comment]
## Update

- Added base commands for catalog tools (create, validate, update, delete, get)

**Comment by juliancnn** [comment]
## Update

- Add documentation and other minor changes
