### ISSUE TITLE
Release 4.9.1 - RC 1 - E2E UX tests - Wazuh Indexer ISM policies

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#25828]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.9.1-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-indexer team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Sep 23, 2024 and notify the @wazuh/devel-indexer team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-indexer team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Sep 24, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Sep 25, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.9.1-rc1/quickstart.html) | - | Red Hat Enterprise Linux 8 |
| Server | Same as indexer, all-in-one | - | - |
| Dashboard | Same as indexer, all-in-one | - | - |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.9.1-rc1/installation-guide/wazuh-agent/index.html) | - | Red Hat Enterprise Linux 8 x86_64, Windows 11 x86_64 |

## Test description

Follow and read documentation links to test ISM policies in Wazuh Indexer:
- Retention policies
- Rollover + alias

https://documentation-dev.wazuh.com/v4.9.1-rc1/user-manual/wazuh-indexer/index-life-management.html
https://opensearch.org/docs/latest/im-plugin/ism/index/

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Creating a retention policy using visual editor |  |  |
| 🟢 | Creating a retention policy using json editor |  |  |
| 🟢 | Applying the retention policy to alerts index |  |  |
| 🟢 | Wazuh agent installation |  |  |
| 🟢 | Roll Over |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **Yes steps were clear and easy to follow. nonetheless lack of instructions regardin how to perform Roll over + Alias, what exactly is expected to be done and what should be the outcome of the test.**
- Did you face any challenges not covered by the guideline?
  - **Yes, the guidelines do not contain verification steps to ensure the retention policy does work. Also no mention on how to perform rollback in the documentation. **
- Suggestions for improvement:
  - **Create documentation on how to create and manage data streams and performing roll over. See [Issue#5771](https://github.com/wazuh/wazuh-qa/issues/5771)**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @juliamagan
- [x] @wazuh/devel-indexer

**Comment by Rolly-M** [comment]
## Wazuh agent installation

I installed the Wazuh agent using the command from Wazuh dashboard and below is the log
```console
[root@localhost ~]# curl -o wazuh-agent-4.9.1-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.1-1.x86_64.rpm && sudo WAZUH_MANAGER='192.168.21.220' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='Linux' rpm -ihv wazuh-agent-4.9.1-1.x86_64.rpm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10.4M  100 10.4M    0     0  5723k      0  0:00:01  0:00:01 --:--:-- 5726k
warning: wazuh-agent-4.9.1-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
Updating / installing...
   1:wazuh-agent-4.9.1-1              ################################# [100%]
```

```console

```

**Comment by rauldpm** [comment]
# Final review

## Creating a retention policy using visual editor

If I see correctly, step 11 of https://documentation-dev.wazuh.com/v4.9.1-rc1/user-manual/wazuh-indexer/index-life-management.html#using-the-visual-editor is not done. @AlexRuiz7 as the initial reviewer, which consequences has this missing step in the test, test validation, or usage? As I see, the documentation steps are based on the previous ones. Should the documentation be changed to set as `Initial state` the `delete_alerts` instead of `Initial`?

![image](https://github.com/user-attachments/assets/b24b337d-21ae-4038-ab1a-21681dc8fa66)

## Deployment

Also, the Wazuh agent should be installed `before` starting the test, this test alone does not make sense https://github.com/wazuh/wazuh/issues/25828#issuecomment-2371347487

I opened this issue to change this E2E based on the observations I made https://github.com/wazuh/wazuh-qa/issues/5771

**Comment by Rolly-M** [comment]
## Testing the retention policy

To test if the retention policy did work, I configured wazuh archives following the documentation [Archiving event logs](Archiving event logs). I then created a custom policy to delete archives after 5mins. Below is the policy used for the test:

![RetentionPolicy3](https://github.com/user-attachments/assets/f4f2cd73-49ef-499b-8e88-3f114e5a10a4)

```console
{
    "policy": {
        "policy_id": "example_Policy",
        "description": "Wazuh archives retention policy",
        "last_updated_time": 1727218176684,
        "schema_version": 21,
        "error_notification": null,
        "default_state": "Initial",
        "states": [
            {
                "name": "Initial",
                "actions": [],
                "transitions": [
                    {
                        "state_name": "delete_archives",
                        "conditions": {
                            "min_index_age": "5m"
                        }
                    }
                ]
            },
            {
                "name": "delete_archives",
                "actions": [
                    {
                        "retry": {
                            "count": 3,
                            "backoff": "exponential",
                            "delay": "1m"
                        },
                        "delete": {}
                    }
                ],
                "transitions": []
            }
        ],
        "ism_template": [
            {
                "index_patterns": [
                    "wazuh-archives-*"
                ],
                "priority": 1,
                "last_updated_time": 1727218176684
            }
        ]
    }
}
```

Below is an image of the  `wazuh-archives-4.x-2024.09.24` Index before applying the policy to it:

![image](https://github.com/user-attachments/assets/2dec4f71-c93c-4e66-ba1a-0561d43adf1c)

Another image showing the same Index five minutes later which confirms data has been deleted.

![image](https://github.com/user-attachments/assets/92a7ea44-2d79-4e49-b6ed-d54c5a7edc07)


## Configuring Rollover

**Comment by AlexRuiz7** [comment]
> If I see correctly, step 11 of https://documentation-dev.wazuh.com/v4.9.1-rc1/user-manual/wazuh-indexer/index-life-management.html#using-the-visual-editor is not done. @AlexRuiz7 as the initial reviewer, which consequences has this missing step in the test, test validation, or usage? As I see, the documentation steps are based on the previous ones. Should the documentation be changed to set as `Initial state` the `delete_alerts` instead of `Initial`?

It won't work correctly. The latest version of the documentation is correct.

**Comment by rauldpm** [comment]
Changes were applied and everything seems to work as expected
