### ISSUE TITLE
Review the Comms API `POST /events/stateful` endpoint when receiving commands results

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25835]
|Epic|
|---|
| https://github.com/wazuh/wazuh-indexer/issues/349 |

## Description

Following the changes to be introduced in the development of the Command Manager, the `POST /commands/results` will no longer be required and instead, the commands execution results sent by the `wazuh-agent` are expected to be processed in the `POST /events/stateful`.

The issue where the agent team is developing the Command Handler, and thus, the results to be sent to the Command Manager is the following:
- https://github.com/wazuh/wazuh-agent/issues/146

## Tasks

- [x] Review the behavior of the `POST /events/stateful` endpoint when receiving the results of commands executed in an agent.
- [x] Apply the necessary changes for the endpoint to process the results of the command execution and update the required documents in the indexer.

**Comment by GGP1** [comment]
## Update

I've removed the `POST /commands/results` endpoint and added the model `CommandResult` as a part of the `StatefulEvents` that can be sent in `POST /events/stateful`.
