### ISSUE TITLE
Alert ID in Active Response is different from the one generated in Kibana.

### ISSUE THREAD

**Issue by ambatshri** [wazuh/wazuh#2583]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager | Packages(Docker) | Ubuntu 18.04 |

I've been trying to achieve event correlation using ruleset, but due to limitations of ruleset. Switched to active response. The use case I'm trying 

> When a user is created in Active Directory an event is generated. And another event is generated for deletion. I want to check if the creation and deletion of the user is done within 48 hrs. 

So i've created a simple command and a python script without any fields in expect. So by default it should pass the default args to the python script which contains ALERT-ID. This alert id in the argument is different from the one generated in the Kibana.

Command and Active Response in ossec.conf
```
  <command>
    <name>windows-user-crdl</name>
    <executable>win-ad-creation.py</executable>
    <expect></expect>
  </command>

  <active-response>
    <disabled>no</disabled>
    <command>windows-user-crdl</command>
    <location>server</location>
    <rules_id>18112</rules_id>
  </active-response>
  
```

Python Script win-ad-creation.py
```
#!/usr/bin/env python
import sys

f = open('/var/ossec/logs/python.log','a+')

args = sys.argv
f.write("Args: "+ repr(args))
```

AlertID in python.log

```
Args: ['/var/ossec/active-response/bin/win-ad-creation.py', 'add', '-', '-', '1549984447.1231027', '18112', '(WIN-C587PG3SC9V)', '192.168.56.3->WinEvtLog', '-', '-']
```

AlertID in Kibana
```
id 1549984447.1231901
```
I was planning on using that alert id to query the elastic to get the alert details and then lookup another alert based on the one which triggered the active response.

**Comment by jctello** [comment]
More examples of this behavior:
Active response time | Kibana Time | Difference
-- | -- | --
1549976481.45151 | 1549976481.45202 | 0.000506162643433
1549968682.41873 | 1549968682.4196 | 0.00086498260498
1549968426.4165 | 1549968426.417 | 0.000505924224854
1549968408.40859 | 1549968408.40878 | 0.000197887420654
1549968134.40386 | 1549968134.40437 | 0.000506162643433
1549968038.39595 | 1549968038.39615 | 0.000198125839233
1549967844.39122 | 1549967844.39173 | 0.000506162643433
1549967668.37413 | 1549967668.37433 | 0.000197887420654
1549967604.36409 | 1549967604.36429 | 0.000197887420654
1549967542.35404 | 1549967542.35424 | 0.000197887420654
1549967494.35104 | 1549967494.35155 | 0.000506162643433
1549967418.34151 | 1549967418.34313 | 0.001627922058105
1549967384.34013 | 1549967384.34064 | 0.000506162643433
1549967352.3306 | 1549967352.33222 | 0.001627922058105
1549967316.32218 | 1549967316.32238 | 0.000198125839233
1549967312.31968 | 1549967312.32131 | 0.001627922058105
1549967157.31831 | 1549967157.31882 | 0.000505924224854
1549967059.30791 | 1549967059.30877 | 0.00086498260498
1549966935.30654 | 1549966935.30704 | 0.000500917434692

These seem to show that the difference is not constant but not too large. Maybe for this use case the alerts could be identified by an elastic query that rounds to 2 decimals.

**Comment by ssigwart** [comment]
I'm seeing the same issue and think I spotted a pattern.  One alert ID was `1552580954.2023520`.  If I look in `/var/ossec/logs/alerts/alerts.log`, the real ID is `1552580954.2024046`.  However, if I look at the alert just before it in the log, it's `1552580943.2023520`.  Notice how it ends with the same fractions of a second.  I confirmed this on multiple alert IDs.

**Comment by sergiospa** [comment]
I duplicated this issue, let's continue in the other one since it already has assignees and a project.
