### ISSUE TITLE
AWS script show CommonPrefixes as a type of error

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#2586]
Hi Team, 

I have realized that the script of AWS shows the following error when there is an _Invalid bucket type_:

```
 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 12
 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  CommonPrefixes
```

What error is **CommonPrefixes**? Is this an expected output of an error?

Regards,

Miguel Casares

**Comment by druizz90** [comment]
Hi team,

This error happens when you introduce a wrong `--trail-prefix` and this function throws a `KeyError`:
```python
def find_account_ids(self):
       return [common_prefix['Prefix'].split('/')[-2] for common_prefix in
               self.client.list_objects_v2(Bucket=self.bucket,
                                           Prefix=self.get_base_prefix(),
                                           Delimiter='/')['CommonPrefixes']
               ]
```
I think we should improve the error message.

Best regards,

Demetrio.
