### ISSUE TITLE
Release 4.9.1 - RC 1 - External integrations modules

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#25882]
The following issue aims to perform all the required testing for the current release candidate to ensure the modules (AWS, GCP, Azure, DockerListener, and Shuffle) work as expected, report the results, and open new issues for any encountered errors.

## Modules test information

|||
|----------------------------------|------ |
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/25833     |
| **Version**                      | 4.9.1 |
| **Release candidate #**          | RC 1   |
| **Tag**                          |  [v4.9.1-rc1]( https://github.com/wazuh/wazuh/tree/v4.9.1-rc1   )   |
| **Previous modules tests issue** |  https://github.com/wazuh/wazuh/issues/24896  |

## Test report procedure

All test results must have one of the following statuses: 
|                                  |                                                        |
|-----------------|-------------------------------------------------------------------------|
| :green_circle:  | The test passed successfully. 										    |
| :yellow_circle: | The test passed, but some enhancements must be applied to the module. |
| :red_circle:    | The test failed.                                                        |
| :white_circle:  | The test does not apply.                                                |

Any failing test must be adequately addressed with a new issue detailing the error and the possible cause. It must be included in the Fixes section of the current release candidate's central issue.

The resulting logs for the tests must be included in the status report so the auditors can use them to dig deeper into any possible failures and details.

## Conclusions

| **Module**      |  **Status**  |**Issues**|
|-----------------|-------------|---------|
| AWS             | :green_circle:   |- |
| Azure           |⚪ Skipped   | |
| GCP             | ⚪ Skipped  |  |
| Docker Listener | ⚪ Skipped   |  |
| Shuffle | ⚪ Skipped  |  |
| Slack | ⚪ Skipped  |  |
| Virustotal | ⚪ Skipped  |  |
| Pagerduty | ⚪ Skipped  |  |
| Maltiverse | ⚪ Skipped  |  |

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.
## Auditors validation

The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted to close this issue.

- [x] @fdalmaup  
- [ ] @wazuh/devel-qa

**Comment by RamosFe** [comment]
## AWS integration tests :yellow_circle: 

[Build](https://github.com/wazuh/wazuh/actions/runs/10993789327/job/30521023375)

| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_aws/test_basic.py | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_custom_bucket.py | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_discard_regex.py | 17 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_log_groups.py | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_only_logs_after.py | 45 | 0 | 0 | 2 | 0 |  | :green_circle: |
| test_aws/test_parser.py | 26 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_path.py | 42 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_path_suffix.py | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_aws/test_regions.py | 17 | 0 | 0 | 0 | 6 | https://github.com/wazuh/wazuh/issues/23431 | :yellow_circle: |
| test_aws/test_remove_from_bucket.py | 12 | 0 | 3 | 0 | 0 |  | :green_circle: |


The tests that failed were fixed in  https://github.com/wazuh/wazuh/issues/23431 and the changes will be added in `4.10.0`.

**Comment by RamosFe** [comment]
## AWS - Security Lake as a subscriber integration :green_circle: 
### Configuration

<details>
<summary>Wodle configuration</summary>


```xml
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>30s</interval>
    <run_on_start>yes</run_on_start>
    <subscriber type="security_lake">
        <sqs_name>********-Main-Queue</sqs_name>
        <external_id>********</external_id>
        <iam_role_arn>********</iam_role_arn>
    </subscriber>
  </wodle>
```

</details>

### Logs 

<details>
<summary>Execution logs</summary>

Logs file `ossec.log`:


```
2024/09/23 17:48:30 wazuh-modulesd:aws-s3[32994] wm_aws.c:842 at wm_aws_run_subscriber(): WARNING: Subscriber: security_lake ********-Main-Queue  -  DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://********-Main-Queue
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: ********-Main-Queue
DEBUG: The message is: {'source': 'aws.s3', 'time': '2024-09-21T17:44:05Z', 'account': '********', 'region': '********', 'resources': ['********'], 'detail': {'bucket': {'name': '********'}, 'object': {'key': '********.gz.parquet', 'size': 21417, 'etag': '45be74d7e487892436b07e844433ab94'}, 'request-id': '********', 'requester': 'securitylake.amazonaws.com'}}
DEBUG: The message is: {'source': 'aws.s3', 'time': '2024-09-21T18:04:05Z', 'account': '********', 'region': '********', 'resources': ['********'], 'detail': {'bucket': {'name': '********'}, 'object': {'key': '********.gz.parquet', 'size': 25268, 'etag': '5554aef8a1988d083bf27da3adace998'}, 'request-id': '********', 'requester': 'securitylake.amazonaws.com'}}
DEBUG: The message is: {'source': 'aws.s3', 'time': '2024-09-21T18:09:05Z', 'account': '********', 'region': '********', 'resources': ['********'], 'detail': {'bucket': {'name': '********'}, 'object': {'key': '********.gz.parquet', 'size': 22186, 'etag': 'b4dd1ac279d1f8523cd899106f83dabc'}, 'request-id': '********', 'requester': 'securitylake.amazonaws.com'}}


DEBUG: 337 events sent to Analysisd
DEBUG: Message deleted from queue: ********
2024/09/23 17:48:36 wazuh-modulesd:aws-s3[32994] wm_aws.c:201 at wm_aws_main(): INFO: Fetching logs finished.

```

> These logs were obtained  by setting `wazuh_modules.debug=2` in `etc/internal_options.conf`
</details>

**Comment by RamosFe** [comment]
## AWS - Security Hub Integration :green_circle: 
### Configuration

<details>
<summary>Wodle configuration</summary>

```xml
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>1h</interval>
    <run_on_start>yes</run_on_start>
    <subscriber type="security_hub">
      <sqs_name>********</sqs_name>
      <aws_profile>default</aws_profile>
    </subscriber>
  </wodle>
```

</details>

### Logs

<details>
<summary>Execution logs</summary>

Logs file `ossec.log`:

```
2024/09/23 18:48:43 wazuh-modulesd:aws-s3[75513] wm_aws.c:845 at wm_aws_run_subscriber(): DEBUG: Subscriber: ******** -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: ********
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: ********
DEBUG: The message is: {'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': '********', 'eventTime': '2024-07-25T13:08:33.255Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': '********'}, 'requestParameters': {'sourceIPAddress': '**'}, 'responseElements': {'x-amz-request-id': '********', 'x-amz-id-2': 'k9/COvAV9pUBo4UCTKFky3W8ulqcoCWL0lP/TyECmy79wNpU6fx1bGKNE92W4J77ezt+gXU0r+p0jEGMUqQU/3OgoDET1Ci+DQwnPWhrYs4='}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': 'test', 'bucket': {'name': '********', 'ownerIdentity': {'principalId': '********'}, 'arn': 'arn:aws:s3:::********'}, 'object': {'key': '********', 'size': 3214, 'eTag': '2712ae8aa2627533a0447f3ea8b155cb', 'sequencer': '0066A24E512C20C7A2'}}}]}
```

> These logs were obtained by setting `wazuh_modules.debug=2` in `etc/internal_options.conf`

</details>

**Comment by RamosFe** [comment]
## Test using ossec.conf in an agent with Python 3.7 🟢

### Dependencies

```console
root@ubuntu-jammy:/var/ossec# which python3.7
/usr/bin/python3.7

```

### Configuration

```xml
<ossec_config>
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>30s</interval>
    <run_on_start>yes</run_on_start>
    <subscriber type="security_lake">
        <sqs_name>**</sqs_name>
        <external_id>**</external_id>
        <iam_role_arn>**</iam_role_arn>
    </subscriber>
  </wodle>
</ossec_config>
```

### Results

```
2024/09/23 20:15:10 rootcheck: INFO: Ending rootcheck scan.
2024/09/23 20:15:22 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2024/09/23 20:15:22 wazuh-modulesd:aws-s3: INFO: Executing Subscriber fetch: (Type and SQS:****)
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: The SQS queue is: https://********-Main-Queue
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: Retrieving messages from: ********-Main-Queue
----
DEBUG: 21 events sent to Analysisd
DEBUG: Message deleted from queue: ********
2024/09/23 20:15:22 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
``

**Comment by fdalmaup** [comment]
# Review

LGTM
