### ISSUE TITLE
Release 4.9.1 - RC 1 - Footprint Metrics - ALL-EXCEPT-OSQUERY,VULNERABILITY-DETECTOR (2.5d)

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#25880]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #25833                                         |
| **Main footprint metrics issue #** | #25838                                         |
| **Version** | 4.9.1                                      |
| **Release stage #** | RC 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.9.1-rc1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress_Vagrant/237/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/Test_stress_Vagrant_B237_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/plots/Test_stress_Vagrant_B237_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B237_manager_2024-09-23.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/logs/ossec_Test_stress_Vagrant_B237_manager_2024-09-23.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_Vagrant_B237_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/data/monitor-manager-Test_stress_Vagrant_B237_manager-pre-release.csv)
[Test_stress_Vagrant_B237_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/data/Test_stress_Vagrant_B237_manager_analysisd_events.csv)
[Test_stress_Vagrant_B237_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/data/Test_stress_Vagrant_B237_manager_analysisd_state.csv)
[Test_stress_Vagrant_B237_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_manager_centos/data/Test_stress_Vagrant_B237_manager_remoted_state.csv)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/Test_stress_Vagrant_B237_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/Test_stress_Vagrant_B237_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/Test_stress_Vagrant_B237_macos_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/plots/Test_stress_Vagrant_B237_macos_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B237_macos_2024-09-23.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/logs/ossec_Test_stress_Vagrant_B237_macos_agent_2024-09-23.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/data/monitor-agent-Test_stress_Vagrant_B237_macos_agent-pre-release.csv)
[Test_stress_Vagrant_B237_macos_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_macos/data/Test_stress_Vagrant_B237_macos_agent_agentd_state.csv)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/Test_stress_Vagrant_B237_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/Test_stress_Vagrant_B237_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/Test_stress_Vagrant_B237_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/plots/Test_stress_Vagrant_B237_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_Vagrant_B237_solaris_2024-09-23.zip](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/logs/ossec_Test_stress_Vagrant_B237_solaris_agent_2024-09-23.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/data/monitor-agent-Test_stress_Vagrant_B237_solaris_agent-pre-release.csv)
[Test_stress_Vagrant_B237_solaris_agent_agentd_state.csv](https://ci.wazuh.com/data/Test_stress_Vagrant/pre-release/4.9.1/B237-3600m/B237_agent_solaris/data/Test_stress_Vagrant_B237_solaris_agent_agentd_state.csv)

    </details>

</details>

## Conclusion :red_circle: 

Plots compared to https://github.com/wazuh/wazuh/issues/25533

### Graphs :yellow_circle: 

Known issue:

- https://github.com/wazuh/wazuh/issues/25413

### Logs :red_circle: 

New issues:

- https://github.com/wazuh/wazuh/issues/25918

Known issues:

- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5538
- https://github.com/wazuh/wazuh/issues/25222
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4656

**Comment by rauldpm** [comment]
Found message reported in 

```
2024/09/21 21:37:50 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2024/09/21 21:37:51 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '002' at 'any'.
2024/09/21 21:37:51 wazuh-remoted: WARNING: Decrypt the message fail, socket 30
2024/09/21 21:37:51 wazuh-remoted: WARNING: Unexpected message (hex): 'ff7048ffffff5effffff30ffff06ff0101ffffffff3226ffffffff5fff5d2f7eff70ffff7aff5438ff13ffffff51396d20ff5bff33ffffffffffffff0eff63ff44ffffff594bffffffff277cff6f04ff2f33ff3e480dffff3c5eff11741326ffffffff4eff48533f33754dffffff6bff55ff72ffffff58ff75ffffffff77ffff5a4a23ff51ffff55ff6926ffff53ffff00ffff592c71ff2109ffffffff7affff7b1bff04355bff6c5739ff6521ff7aff757814ff56ffff6bff47512672ffffffff6249ffff19ff2b3d2cff1affffff02ff451bffff30ff55ff0f7b58ff15ffffffffffffffff45ff6bffff4eff424162ff521030ff0100002130303221234145533a3b4dff01ffffff03ffff45694fffffff48217048ff24ffff1a221cffffffffff246c25ffffff09307effffffff75ffffffff17ffffff34ff6effff3effffff51ff4b6d12ff21ff0365ffffff4dffff7a1a444dff28ffffff00792021ffffffff67ff2d41151dff77ffff372f06003bff1f4b39ff5c38ff00ff007dff2fff3cff55ffffff7aff1dff27ffffff73ffffff4b032a5d41ffff5b107f514d263578ff48ffffffffff7057ffff6affffff54ffff5763750bffffff635affffffffff52ffffffffff317b0c22ff5751ffff4fffff2bff10ff50ffffff487c40ffffffffff3e46197f6dff5c275effffff7a6e2c2507ff19ffffffff6972ffffffffff5e5f5bffff5e75ff4464ff44ff2bffffffff2223ff4b5fffff1affffffff3b7c05ff685273ff5877ffffff364d442effffffff4e0018007c5d51135f2a7effffff1b2cff7578ff7effff6b6a626318ffff752c4bff30ff53ffff1107ffffffff34ffff7dff6bff105bff71ff531fffff45ffffffff65ff611dff4cff16ff6c7b185eff38ffffffffffff7bff05ff3705ff13ffffff2fffffff2166ffff1bff42ffff2cff18ff23ffffffffff24ff56ff49ff0100002130303221234145533a6d445202ff28ff75271f10ffffff32ffffffff333bff5aff7a68ff0aff11ffff08ffff6e701a4bffff1158ffffffff7bffffff4030ffff2634ff68ff7eff7468ff17ff531bffffff35ffffff0b1b4e36ff3b6f50ff33352404ffff43ff4e2a46ffffff62ff4eff2344ffffff6c25655aff1bffffff2affff07ffff2237ffffff216dff55266a025cffff7d42ffffff7e035dffffff6b01ff063f42ff71260338ff09ffff45ff4affff6bffff2151ff3cff0bff43ff21ff02ffff4dff3b6618ffff78ff5affffffff3fffff1affffff39ffff677dffff0442ffff31ff54153427ff2bffffff62ff0100002130303221234145533affff62ffffffff10ff23ff174b62ff4fffffffffffffff31253c35ff42ffff7fff57ff2f1fffff30ff23070f28ffffffff6e6150ff61ffffff33ff5014ffff4f541aff7b28ffff6630ffffff'
2024/09/21 21:37:51 wazuh-remoted: WARNING: Too big message size from socket [30].
```

Reported in https://github.com/wazuh/wazuh/issues/25222

**Comment by hossam1522** [comment]
# Analysis report :yellow_circle: 
 
## Graphs :yellow_circle:  

<details><summary>Manager</summary>

- **Disk:** decrease in `wazuh-modulesd`.
- **Disk_read_** small decrease in `wazuh-syscheckd` and increase in  `wazuh-monitord`.
- **PSS, RSS, USS** small increase in `wazuh-remoted`

</details>

<details><summary>macOS</summary>

- **RSS, VMS:** decrease in `wazuh-modulesd` (similar to previous stages):
  - Known issue: https://github.com/wazuh/wazuh/issues/25413

</details>


<details><summary>Solaris</summary>

- **Agentd_Number_of_generated_events, Agentd_Number_of_messages:** decrease in values (similar to previous stages).

</details>


## Logs :yellow_circle:


<details><summary>macOS</summary>

- Reported in 
```

```

- Reported in 
```

```

</details>

<details><summary>Manager</summary>

- Expected in stress test
```

```

- Reported in 

```

```

- Reported in: 
```

```

- Reported in 
```

```

</details>


<details><summary>Solaris</summary>

- Reported in 
```

```

- Reported in 
```

```

</details>

**Comment by fcaffieri** [comment]
LGTM
