### ISSUE TITLE
Release 4.9.1 - RC 1 - API integration tests

### ISSUE THREAD

**Issue by DamianNud** [wazuh/wazuh#25891]
The following issue aims to run all [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) for the current release candidate, report the results, and open new issues for any encountered errors.

## API integration tests information
|                                          |                                            |
|------------------------------------------|--------------------------------------------|
| **Main release candidate issue**         |                     https://github.com/wazuh/wazuh/issues/25833                       |
| **Version**                              |                      4.9.1                      |
| **Release candidate #**                  |                       RC1                     |
| **Tag**                                  |                       [v4.9.1-rc1](https://github.com/wazuh/wazuh/tree/v4.9.1-rc1)                     |
| **Previous API integration tests issue** |                     https://github.com/wazuh/wazuh/issues/25512                       |

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Conclusions

All tests have been executed and the results can be found [here](https://github.com/wazuh/wazuh/issues/25891#issuecomment-2368685878)

All tests have passed and the fails have been reported or justified. I therefore conclude that this issue is finished and OK for this release candidate.

### New issue :red_circle: 

- https://github.com/wazuh/wazuh/issues/25905
- https://github.com/wazuh/wazuh/issues/25936

## Auditors validation
The definition of done for this one is the validation of the conclusions and the test results from all auditors.

All checks from below must be accepted in order to close this issue.

- [x] @fdalmaup 
- [ ] @wazuh/devel-qa

**Comment by javiersanchz** [comment]
## Test report
[Artifacts.zip](https://github.com/user-attachments/files/17100300/artifacts.zip)


## Test results

---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_DELETE_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_GET_endpoints.tavern.yaml | 95 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_POST_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_agent_PUT_endpoints.tavern.yaml | 10 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_cluster_endpoints.tavern.yaml | 49 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_decoder_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_default_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_event_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_manager_endpoints.tavern.yaml | 34 | 0 | 0 | 0 | 1 | https://github.com/wazuh/wazuh/issues/25738 | :yellow_circle: |
| test_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_agent_endpoints.tavern.yaml | 41 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_event_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_black_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_active_response_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_agent_endpoints.tavern.yaml | 41 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_all_endpoints.tavern.yaml | 162 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cdb_list_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_cluster_endpoints.tavern.yaml | 19 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_decoder_endpoints.tavern.yaml | 6 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_event_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_experimental_endpoints.tavern.yaml | 12 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_logtest_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_manager_endpoints.tavern.yaml | 16 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_mitre_endpoints.tavern.yaml | 7 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_overview_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_rule_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_sca_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_security_endpoints.tavern.yaml | 25 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_syscollector_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rbac_white_task_endpoints.tavern.yaml | 1 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rootcheck_endpoints.tavern.yaml | 4 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_rule_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_sca_endpoints.tavern.yaml | 45 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_DELETE_endpoints.tavern.yaml | 15 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_GET_endpoints.tavern.yaml | 11 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_POST_endpoints.tavern.yaml | 8 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_security_PUT_endpoints.tavern.yaml | 9 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_syscheck_endpoints.tavern.yaml | 33 | 0 | 0 | 0 | 1 | insert issue link | :red_circle: |
| test_syscollector_endpoints.tavern.yaml | 159 | 0 | 0 | 0 | 0 |  | :green_circle: |
| test_task_endpoints.tavern.yaml | 2 | 0 | 0 | 0 | 0 |  | :green_circle: |

**Comment by javiersanchz** [comment]
## Update

Regarding the failure on `test_manager_endpoints.tavern.yaml`, work is already being done on the issue https://github.com/wazuh/wazuh/issues/25738. Although it was discovered in version `4.10.0`, the failure is in the same test, so it seems to be failing in both branches.

As for the failure in `test_syscheck_endpoints.tavern.yaml`, it appears to be a sporadic failure. The test was run individually and as part of the test suite, and both passed correctly:

```console
(venv) wazuh@javier:~/Git/wazuh/api/test/integration$ pytest -vv 'test_syscheck_endpoints.tavern.yaml::PUT /syscheck'
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.5.0 -- /home/wazuh/Git/wazuh/venv/bin/python3.10
cachedir: .pytest_cache
metadata: {'Python': '3.10.13', 'Platform': 'Linux-6.5.0-35-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.5.0'}, 'Plugins': {'anyio': '4.1.0', 'cov': '5.0.0', 'metadata': '3.1.1', 'trio': '0.8.0', 'html': '2.1.1', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: anyio-4.1.0, cov-5.0.0, metadata-3.1.1, trio-0.8.0, html-2.1.1, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 1 item                                                                                                                                                                                                  

test_syscheck_endpoints.tavern.yaml::PUT /syscheck PASSED                                                                                                                                                   [100%]


==================================================================================== 1 passed, 2 warnings in 486.66s (0:08:06) ====================================================================================
                                                                                                  [100%]
```
```console
(venv) wazuh@javier:~/Git/wazuh/api/test/integration$ pytest -vv test_syscheck_endpoints.tavern.yaml    
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.5.0 -- /home/wazuh/Git/wazuh/venv/bin/python3.10
cachedir: .pytest_cache
metadata: {'Python': '3.10.13', 'Platform': 'Linux-6.5.0-35-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.5.0'}, 'Plugins': {'anyio': '4.1.0', 'cov': '5.0.0', 'metadata': '3.1.1', 'trio': '0.8.0', 'html': '2.1.1', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: anyio-4.1.0, cov-5.0.0, metadata-3.1.1, trio-0.8.0, html-2.1.1, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 34 items                                                                                                                                                                                                

test_syscheck_endpoints.tavern.yaml::GET /syscheck/000 PASSED                                                                                                                                               [  2%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[date] PASSED                                                                                                                                         [  5%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[mtime] PASSED                                                                                                                                        [  8%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[file] PASSED                                                                                                                                         [ 11%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[size] PASSED                                                                                                                                         [ 14%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[perm] PASSED                                                                                                                                         [ 17%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[uname] PASSED                                                                                                                                        [ 20%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[gname] PASSED                                                                                                                                        [ 23%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[md5] PASSED                                                                                                                                          [ 26%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[sha1] PASSED                                                                                                                                         [ 29%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[sha256] PASSED                                                                                                                                       [ 32%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[inode] PASSED                                                                                                                                        [ 35%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[gid] PASSED                                                                                                                                          [ 38%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[uid] PASSED                                                                                                                                          [ 41%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[type] PASSED                                                                                                                                         [ 44%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000/last_scan PASSED                                                                                                                                     [ 47%]
test_syscheck_endpoints.tavern.yaml::PUT /syscheck PASSED                                                                                                                                                   [ 50%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002 PASSED                                                                                                                                               [ 52%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[date] PASSED                                                                                                                                         [ 55%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[mtime] PASSED                                                                                                                                        [ 58%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[file] PASSED                                                                                                                                         [ 61%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[size] PASSED                                                                                                                                         [ 64%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[perm] PASSED                                                                                                                                         [ 67%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[uname] PASSED                                                                                                                                        [ 70%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[gname] PASSED                                                                                                                                        [ 73%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[md5] PASSED                                                                                                                                          [ 76%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[sha1] PASSED                                                                                                                                         [ 79%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[sha256] PASSED                                                                                                                                       [ 82%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[inode] PASSED                                                                                                                                        [ 85%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[gid] PASSED                                                                                                                                          [ 88%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[uid] PASSED                                                                                                                                          [ 91%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[type] PASSED                                                                                                                                         [ 94%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002/last_scan PASSED                                                                                                                                     [ 97%]
test_syscheck_endpoints.tavern.yaml::DELETE /syscheck PASSED                                                                                                                                                [100%]

=================================================================================== 34 passed, 35 warnings in 519.08s (0:08:39) ===================================================================================
```

**Comment by javiersanchz** [comment]
## Update

- A specific issue was finally opened: [Failure in the API integration test of test_manager_endpoints.tavern.yaml #25905](https://github.com/wazuh/wazuh/issues/25905) to fix the `test_manager_endpoints.tavern.yaml`, since after investigating, we found that the test failure initially stems from issues introduced in `4.9.1`

**Comment by fdalmaup** [comment]
# Review

LGTM, the error in the `test_manager_endpoints.tavern.yaml` test case was introduced since it was not modified in https://github.com/wazuh/wazuh/pull/25216. The corresponding issue was opened.

**Comment by rauldpm** [comment]
> As for the failure in test_syscheck_endpoints.tavern.yaml, it appears to be a sporadic failure. The test was run individually and as part of the test suite, and both passed correctly:

We have to open an issue to investigate why it is happening, we can't assume that it is just a flaky test or it is just sporadic without  proper research

**Comment by javiersanchz** [comment]
## Update

A new issue was created to investigate the failure of test_syscheck_endpoints.tavern.yaml more thoroughly --> [Failure in the API integration test of test_syscheck_endpoints.tavern.yaml #25936](https://github.com/wazuh/wazuh/issues/25936)
