### ISSUE TITLE
Wazuh App for Kibana 5.6.4

### ISSUE THREAD

**Issue by batidiane** [wazuh/wazuh#259]
Hello,

I updated my ELK server to 5.6.4. Is there a way to make current wazuh app functionning under this version of ELK?

When trying to install the wazuh app, I get this error:
``Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.4]; found [5.6.3]"

Thank you for your help.

**Comment by havidarou** [comment]
Hi @batidiane , we are working on it.

We'll let you know when it is ready.

Regards.

**Comment by batidiane** [comment]
Hi @havidarou,

thank you for the answer. Waiting for it then.

Cheers.

**Comment by ferrfrax** [comment]
Hi @batidiane:

@havidarou commented in #264 :

"Hi,  sorry, didn't see this thread. 
 There's a version available for 5.6.4: 
packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.4.zip  

Regards.-"



now it works for me.

**Comment by merlinwizard** [comment]
Is there a version for 5.6.5? I'm getting the same issue. Better question, is there a documented work around where we can specify the version to be installed and lock it, as a way to not get trapped in the rapid release cycle and required synchronization between Wazuh and ELK?

**Comment by havidarou** [comment]
Hi @merlinwizard,

yes, there is a version for 5.6.5, please refer to the README.md to see the available packages.

Regards.

**Comment by merlinwizard** [comment]
Thank you I found in the README.md history, also looks like it jump from 2.1.1 to 3.0? Congrats on the major update. Hopefully somebody Wazuh will become the defacto OSSEC method.

**Comment by JuanjiJG** [comment]
Thanks for your kind words @merlinwizard.

Yes, we've updated the README, and you can still download the 2.1.1 app packages on the 2.1 branch of the repository: https://github.com/wazuh/wazuh-kibana-app/tree/2.1#installation

Best regards, 
Juanjo
