### ISSUE TITLE
Failure in the API integration test of `test_manager_endpoints.tavern.yaml`

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#25905]
|Wazuh version|
|---|
| 4.9.1 |

## Description

- While working on the release of [Release 4.9.1 - RC 1 - API integration tests #25891](https://github.com/wazuh/wazuh/issues/25891), we noticed that in `4.9.1` the test_manager_endpoints.tavern.yaml is failing. The specific test that fails is `test_manager_endpoints.tavern.yaml::GET /manager/api/config`.

- This failure is due to the changes introduced in https://github.com/wazuh/wazuh/pull/25216 in `4.9.1`, which were not reflected in the corresponding test

- This failure was also being worked on for version `4.10.0` in a more general way, as the same test is failing: [Failed tests in test_manager_endpoints and test_rbac_black_decoder_endpoints for 4.10.0 #25738](https://github.com/wazuh/wazuh/issues/25738), for more information on it

## Task

- Fix the specific test `test_manager_endpoints.tavern.yaml::GET /manager/api/config` for the next stage of `4.9.1`

**Comment by DamianNud** [comment]
# Update

I applied the fix mentioned in [this comment](https://github.com/wazuh/wazuh/issues/25738#issuecomment-2369744291) and opened a Pull Request (https://github.com/wazuh/wazuh/pull/25956) with the changes.
