### ISSUE TITLE
Wazuh-alerts* index creation

### ISSUE THREAD

**Issue by urfin00djuce** [wazuh/wazuh#25910]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-1 | Wazuh Indexer | Manager | Packages | Ubuntu 20.04.06 LTS |

**Wazuh > Index management > Dev Tools**:
```
GET wazuh-alerts-4.x-2024.09.23/_mapping
```
**Output**:
```json

               "ModifiedProperties": {
                  "properties": {
                    "Name": {
                      "type": "keyword"
                    },
                    "NewValue": {
                      "type": "keyword"
                    },
                    "OldValue": {
                      "type": "keyword"
                    }
                  }
                },

```
**Wazuh > Index management > Dev Tools**:
```
GET wazuh-alerts-4.x-2024.09.24/_mapping
```
**Output**:
```json

                "ModifiedProperties": {
                  "type": "keyword"
                },

```

**Filebeat** log:
```
failed to parse field [data.office365.ModifiedProperties] of type [keyword]
```
I did not make any changes to the creation of indexes. A new index is created automatically every day, but the `data.office365.ModifiedProperties` value has different properties, which is why filebeat does not write an event to the Wazuh Indexer.

**Comment by urfin00djuce** [comment]
As a workaround added the following lines to the file `/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json`:

```json
    {
      "rename": {
        "if": "ctx?.data?.office365?.ModifiedProperties != null",
        "field": "data.office365.ModifiedProperties",
        "target_field": "data.office365.ModifiedProperties_obj",
        "ignore_failure": true,
        "ignore_missing": true
      }
    },
...
    { "remove": { "field": "data.office365.ModifiedProperties", "ignore_missing": true, "ignore_failure": true } }
```
And reload pipeline:

```bash
filebeat setup --pipelines
```

**Comment by f-galland** [comment]
Hey @urfin00djuce,

Can you share an example of an event's `json` that is not being indexed? We can use that to run tests on our end.

Thanks!

**Comment by urfin00djuce** [comment]
Hi @f-galland 
It's about rule `91713`:
```json
{"CreationTime":"2024-09-24T12:17:46","Id":"aaaa1111-1a11-11aa-aa11-aaa1a1111111","Operation":"Add member to group.","OrganizationId":"aaaa1111-11a1-111a-1111-11111111111a","RecordType":8,"ResultStatus":"Success","UserKey":"11111111AAAA1A11@domain.com","UserType":0,"Version":1,"Workload":"AzureActiveDirectory","ObjectId":"user.name_mail.net#EXT#@cloud.onmicrosoft.com","UserId":"cloud.user@domain.com","AzureActiveDirectoryEventType":1,"ExtendedProperties":[{"Name":"additionalDetails","Value":"{\"User-Agent\":\"TeamsMiddleTier\/1.0a$*+\"}"},{"Name":"extendedAuditEventCategory","Value":"Group"}],"ModifiedProperties":[{"Name":"Group.ObjectID","NewValue":"aaaa1111-1aa1-11aa-1aa1-a111aa1a1a1a","OldValue":""},{"Name":"Group.DisplayName","NewValue":"Group07","OldValue":""},{"Name":"Group.WellKnownObjectName","NewValue":"","OldValue":""}],"Actor":[{"ID":"cloud.user@domain.com","Type":5},{"ID":"11111111AAAA1A57","Type":3},{"ID":"Microsoft Teams Services","Type":1},{"ID":"aaaa1111-1a1a-1111-a11a-11a1a1111aaa","Type":2},{"ID":"User_aaaa1111-11a1-1a11-a1a1-11111aa1a11a","Type":2},{"ID":"aaaa1111-11a1-1a11-a1a1-11111aa1a11a","Type":2},{"ID":"User","Type":2}],"ActorContextId":"aaaa1111-11a1-111a-1111-11111111111a","InterSystemsId":"aaaa1111-11a1-111a-111a-aa1111111aaa","IntraSystemId":"aaaa1111-a111-1a11-aa1a-a1a111a1a1a1","SupportTicketId":"","Target":[{"ID":"User_aaaa1111-aaa1-1111-aaa1-1a11a1111111","Type":2},{"ID":"aaaa1111-aaa1-1111-aaa1-1a11a1111111","Type":2},{"ID":"User","Type":2},{"ID":"user.name_mail.net#EXT#@cloud.onmicrosoft.com","Type":5},{"ID":"11111111A11111A1","Type":3}],"TargetContextId":"aaaa1111-11a1-111a-1111-11111111111a"}
```

**Comment by f-galland** [comment]
Hi @urfin00djuce ,

I've gone through the event and our mapping (available at `/etc/filebeat/wazuh-template.json`) and I found that there is no default mapping for the `ModifiedProperties` field.
Whenever there is no default mapping for a particular field, the Indexer tries to infer the type then stores a new mapping with that inferred type to memory.

The `office365` mapping is being reviewed internally at the moment to take this issue into account, but for the time being you can add your needed mapping to `/etc/filebeat/wazuh-template.json`.

In the example event you shared, `ModifiedProperties` is actually an array of objects, so your mapping for this field would look as follows:

```json
{
  "mappings": {
    "properties": {
      "ModifiedProperties": {
        "type": "nested", 
        "properties": {
          "Name": {
            "type": "keyword"
          },
          "NewValue": {
            "type": "keyword"
          },
          "OldValue": {
            "type": "keyword"
          }
        }
      }
    }
  }
}
```

By making these changes to `wazuh-template.json` you would make them persistent for each new daily `wazuh-alerts-*` index.
Make sure to run `filebeat setup --index-management` and `filebeat setup --pipelines` after making any changes to the template for them to be applied.

Let me know if this helped.

**Comment by urfin00djuce** [comment]
Hi @f-galland
I'll check the solution you provided and let you know the result.
Thank you.

**Comment by urfin00djuce** [comment]
Hey @f-galland 
The file `/etc/filebeat/wazuh-template.json` already contained a `mapping` so I added an entry and now it looks like this:
```json
  "mappings": {
    "dynamic_templates": [
      {
        "string_as_keyword": {
          "mapping": {
            "type": "keyword"
          },
          "match_mapping_type": "string"
        }
      }
    ],
    "properties": {
      "ModifiedProperties": {
        "type": "nested",
        "properties": {
          "Name": {
            "type": "keyword"
          },
          "NewValue": {
            "type": "keyword"
          },
          "OldValue": {
            "type": "keyword"
          }
        }
      }
    },
```
Unfortunately, this did not affect the index creation properties.
```
GET wazuh-alerts-4.x-2024.09.29/_mapping
```
```
                "ModifiedProperties": {
                  "type": "keyword"
                },
```
```
GET wazuh-alerts-4.x-2024.09.30/_mapping
```
```
                "ModifiedProperties": {
                  "properties": {
                    "Name": {
                      "type": "keyword"
                    },
                    "NewValue": {
                      "type": "keyword"
                    },
                    "OldValue": {
                      "type": "keyword"
                    }
                  }
                },
```

**Comment by f-galland** [comment]
@urfin00djuce ,

I'm leaving a copy of my own modified `wazuh-template.json`. If you haven't performed any other modifications to the template, you should be able to replace the stock file without issues.
[wazuh-template.json](https://github.com/user-attachments/files/17188864/wazuh-template.json)

**Comment by urfin00djuce** [comment]
@f-galland 
I have replaced my file with the one you provided. It appears that the issue has now been resolved.
I notice that your file includes a mapping related to ms-graph. I hope these corrections will be incorporated into the next release.
Thank you for your help.

**Comment by f-galland** [comment]
@urfin00djuce , I'm happy to hear that. We've raised this issue internally and hopefully this fix will be included in a future release.

Regards,
Fede
