### ISSUE TITLE
Footprint - Change in RSS_MAXMIN, RSS, USS and VMS  of Windows Agent plots

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#25928]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Wazuh Agent | Agent | Packages | Windows |

## Description

During the tests of: [Release 4.9.1 - RC 1 - Footprint Metrics - SCA (2.5d)](https://github.com/wazuh/wazuh/issues/25857), a change in the Windows agent was detected in the RSS_MAXMIN, RSS, USS and VMS plot, which was not seen in previous versions.

- 4.9.0 RC 2

RSS_MAXMIN:
![image](https://github.com/user-attachments/assets/25cff328-c7ec-4128-b72e-f125284d0020)

RSS:
![image](https://github.com/user-attachments/assets/9d9f2ee5-c8d7-40ae-8141-685c7d48353f)

USS:
![image](https://github.com/user-attachments/assets/818c2fc9-07d7-4338-be3f-320e12d763d4)

VMS:
![image](https://github.com/user-attachments/assets/54c47af9-ad9a-409b-ae60-54acf28da911)

- 4.9.1 RC 1

RSS_MAXMIN:
![image](https://github.com/user-attachments/assets/22bd4ba5-d321-4ae3-91eb-c97e0cce311e)

RSS:
![image](https://github.com/user-attachments/assets/b13adac0-3166-424f-a446-30bff8c0239e)

USS:
![image](https://github.com/user-attachments/assets/5fbcddaa-46fc-4b1d-8042-580d49117b84)

VMS:
![image](https://github.com/user-attachments/assets/97467789-d6db-4a4e-a0a8-b7c975de4678)

## Evidences

[ossec_Test_stress_B5595_windows_2024-09-23.zip](https://github.com/user-attachments/files/17122255/ossec_Test_stress_B5595_windows_2024-09-23.zip)

**Comment by vikman90** [comment]
Comparing the graphs, we see that both reach a similar peak, below 70 MB. The progression they follow is practically indifferent, as long as there is no clearly positive slope. Memory management is handled by the underlying library and the operating system.
