### ISSUE TITLE
wazuh-execd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.15' not found

### ISSUE THREAD

**Issue by dstr-wpd** [wazuh/wazuh#25921]
|Wazuh version|Component|Install type|Install method|Platform|
|4.9|agent|deb|GUI|Debian Wheezy|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

I tried to install the agent on a debian 7.9:

![image](https://github.com/user-attachments/assets/cce47f40-685f-4bcd-bae3-a0b27853afdd)

Do you know how to solve this? I read that debian 7 is still supported.

Agent Version is: [wazuh-agent_4.9.0-1_armhf.deb](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_armhf.deb)

Thanks and Regards

**Comment by jnasselle** [comment]
Hi @dstr-wpd,

Could you please tell us your glibc version? this could be retrieved by executing:

```
ldd --version
```

About

> I read that debian 7 is still supported.

I'm double-checking this, but seems that arm and intel architectures requirements get mixed in our documentation.

**Comment by dstr-wpd** [comment]
![image](https://github.com/user-attachments/assets/d45aac0f-9db7-4477-ba38-28d86fded637)
its 2.13

**Comment by jnasselle** [comment]
Hi @dstr-wpd ,

Here's the issue for fixing this in our documentation https://github.com/wazuh/wazuh-documentation/issues/7795. 

For ARMv7 architectures and DEB packages, Debian Stretch (9) is the baseline

**Comment by dstr-wpd** [comment]
Well I just realized its fine. I scrolled the list down and came to:
![image](https://github.com/user-attachments/assets/2770cc06-f19f-43f8-ba46-8ca12f2d7d95)
that does not include wheezy. I think that can be closed

**Comment by jnasselle** [comment]
Hi @dstr-wpd ,

We are double-checking this table to be accurate about the agent's compatible OS. I'm closing this issue since your particular scenario is ok.

Regards,
Nico
