### ISSUE TITLE
Release 4.9.1 - RC 1 - Agent Integration Tests

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25923]
| Main RC Issue                               | Version | Stage | Tag        | Previous issue |
| ------------------------------------------- | ------- | ----- | ---------- | --- |
| https://github.com/wazuh/wazuh/issues/25833 | 4.9.1   | RC 1  | v4.9.1-rc1 | #25538 |

The tests will be performed on GitHub workflows. `Linux`, `Windows`, and `macOS` will be used as required.

## Results

| Result | Test                                          | Link | Comment |
|:------:| --------------------------------------------- | ---- | ------- |
| 🟢 | integration-tests-agentd-tier-0-1-lin         | [30607454381](https://github.com/wazuh/wazuh/actions/runs/11021112636/job/30607454381) |         |
| 🟢 | integration-tests-agentd-tier-0-1-win         | [30607644436](https://github.com/wazuh/wazuh/actions/runs/11021117671/job/30607644436) |         |
| 🟡  | integration-tests-aws-tier-0-1                | [30607870451](https://github.com/wazuh/wazuh/actions/runs/11021239852/job/30607870451) | Known [issue](https://github.com/wazuh/wazuh/issues/25431), fixed in `4.10.0` |
| 🟢 | integration-tests-enrollment-tier-0-1-lin     | [30609897349](https://github.com/wazuh/wazuh/actions/runs/11021860911/job/30609897349) |         |
| 🟡 | integration-tests-enrollment-tier-0-1-win     | [30610090530](https://github.com/wazuh/wazuh/actions/runs/11021865190/job/30610090530) | Last [comment](https://github.com/wazuh/wazuh/issues/25347#issuecomment-2307220216), same [issue](https://github.com/wazuh/wazuh/issues/25371)  |
| 🟢 | integration-tests-execd-tier-0-1-lin          | [30610009515](https://github.com/wazuh/wazuh/actions/runs/11021895453/job/30610009515) |         |
| 🟢 | integration-tests-execd-tier-0-1-win          | [30610187380](https://github.com/wazuh/wazuh/actions/runs/11021896937/job/30610187380) |         |
| 🟢 | integration-tests-fim-tier-0-1-lin            | [30610096723](https://github.com/wazuh/wazuh/actions/runs/11021922142/job/30610096723) |         |
| 🟢 | integration-tests-fim-tier-0-1-macos          | [30610103069](https://github.com/wazuh/wazuh/actions/runs/11021924468/job/30610103069) |         |
| 🟢 | integration-tests-fim-tier-0-1-win            | [30610265180](https://github.com/wazuh/wazuh/actions/runs/11021925683/job/30610265180) |         |
| 🟢 | integration-tests-github-tier-0-1-lin         | [30610154664](https://github.com/wazuh/wazuh/actions/runs/11021940632/job/30610154664) |         |
| 🟢 | integration-tests-github-tier-0-1-win         | [30610309595](https://github.com/wazuh/wazuh/actions/runs/11021943075/job/30610309595) |         |
| 🟢 | integration-tests-logcollector-tier-0-1-lin   | [30610198125](https://github.com/wazuh/wazuh/actions/runs/11021954990/job/30610198125) |         |
| 🟢 | integration-tests-logcollector-tier-0-1-macos | [30610202380](https://github.com/wazuh/wazuh/actions/runs/11021956086/job/30610202380) |         |
| 🟢 | integration-tests-logcollector-tier-0-1-win   | [30610354774](https://github.com/wazuh/wazuh/actions/runs/11021957100/job/30610354774) |         |
| 🟢 | integration-tests-msgraph-tier-0-1-lin        | [30610238928](https://github.com/wazuh/wazuh/actions/runs/11021966608/job/30610238928) |         |
| 🟢 | integration-tests-office365-tier-0-1-lin      | [30610256790](https://github.com/wazuh/wazuh/actions/runs/11021973315/job/30610256790) |         |
| 🟢 | integration-tests-office365-tier-0-1-win      | [30610410539](https://github.com/wazuh/wazuh/actions/runs/11021974703/job/30610410539) |         |
| 🟢 | integration-tests-sca-tier-0-1-lin            | [30610296815](https://github.com/wazuh/wazuh/actions/runs/11021985541/job/30610296815) |         |
| 🟢 | integration-tests-sca-tier-0-1-win            | [30610455213](https://github.com/wazuh/wazuh/actions/runs/11021987310/job/30610455213) |         |
| 🟢 | integration-tests-syscollector-tier-0-1-lin   | [30610306817](https://github.com/wazuh/wazuh/actions/runs/11021989461/job/30610306817) |         |
| 🟢 | integration-tests-syscollector-tier-0-1-win   | [30610461429](https://github.com/wazuh/wazuh/actions/runs/11021991810/job/30610461429) |         |
| 🟢 | integration-tests-fim-tier-2-lin              | [30610341319](https://github.com/wazuh/wazuh/actions/runs/11022001328/job/30610341319) |         |
| 🟢 | integration-tests-fim-tier-2-win              | [30610490532](https://github.com/wazuh/wazuh/actions/runs/11022002517/job/30610490532) |         |

### Legend

|Color| Details |
|:--:|:--|
| :green_circle: | The **pipeline** has been executed successfully |
| 🟡 |  The **pipeline** has known errors |
| :red_circle: | The **pipeline** has failed or it has a new errors |

## Conclusion

- Two tests with failed results:
  - Similar to the previos release: #25538
  - We decided not to fix them.
- One test failing in 4.9.0 has been fixed in this release.

## Auditors' validation

- [x] @wazuh/devel-agent
- [x] @wazuh/devel-qa-release

**Comment by rauldpm** [comment]
Please link issues about the 4.10.0 and flaky test
