### ISSUE TITLE
Engine - Custom decoder.

### ISSUE THREAD

**Issue by its4win** [wazuh/wazuh#25931]
| Wazuh version |  Integration name  | Integration type | Integration version |
|---------------|--------------------|------------------|---------------------|
|   4.9.0   | custom decoder |        |         |

Hi All, 
when i create a custom decoder, 
i get the error when i write "offset" on <regex> attribute
![image](https://github.com/user-attachments/assets/2ef2b4e4-1ec5-4a5d-a563-bb3665079cd1)

but it can works when i write "offest" <-- typo
![image](https://github.com/user-attachments/assets/cd81f917-7d3c-4e37-981d-fffb48d9ebe6)

**Comment by jnasselle** [comment]
Hi @its4win ,

The `after_prematch` needs a `prematch` option defined and fails due to this behavior. 

Regarding the `offest` attribute, after checking the code I validate that there's no "invalid attribute" handling, and related information is disregarded.

**Comment by its4win** [comment]
Hi @jnasselle ,
Thanks for your response.

As u can see on the screenshots, 
The <prematch> is on the parent. and the child decoder link to parent decoder using <parent>.

Should write <prematch> again on the child when wrote in parent?

**Comment by jnasselle** [comment]
Based on Wazuh Documentation, `after_parent` offset is the right attribute value https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#decoders-regex.

I was not able to validate this since it's a screenshot and could not be copied.

**Comment by its4win** [comment]
Hi @jnasselle ,
Yup, you're right, `offset` is the right attribute ,
But I don't know why it was give me error.

Last time I test using offset, it can works now.
But now I can use either, tag `offest` or `offset` , as you can see on this screenshot when i write `offest`, it still can works.
![image](https://github.com/user-attachments/assets/afe679a4-cf47-4dc8-87ff-2452c0130875)

Anyway, Thanks.
