### ISSUE TITLE
Engine - Update `engine-suite` to manage sessions

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25949]
**Description:**
With the planned removal of the `wazuh-engine tester` CLI tool, the functionality to manage API sessions directly via the command line will be lost. To maintain the ability to manage sessions, it is proposed to update the `engine-suite` package, specifically enhancing the `engine-test` tool to include session management capabilities that were previously part of `wazuh-engine tester`.

**Tasks:**
1. **Analysis and Design:**
   - Analyze the current session management features provided by `wazuh-engine tester`.
   - Design the necessary additions or modifications to the `engine-test` tool to include session management functionalities.

2. **Development:**
   - Implement session management commands within `engine-test`, including:
     - Create a new session.
     - Delete existing sessions.
     - Retrieve data about a specific session.
     - List all sessions.
   - Ensure that these functionalities can be handled via API calls to align with the new architecture.

**Expected Outcome:**
The updated `engine-test` tool within the `engine-suite` package will seamlessly handle session management, replacing the need for `wazuh-engine tester` and aligning with the shift towards a more integrated and API-driven system management approach.

This update will ensure that developers and administrators can continue to manage API sessions effectively, supporting testing and operational tasks within the Wazuh-Engine environment.

**Comment by JcabreraC** [comment]
Extended ETA. The above issues have not been implemented due to priority in other issues.

**Comment by juliancnn** [comment]
## Update

**Comment by juliancnn** [comment]
## Update

- Added commands and documentation

**Comment by JcabreraC** [comment]
Extended ETA for review
