### ISSUE TITLE
Syscollector unable to collect npm packages in macOS Sonoma

### ISSUE THREAD

**Issue by SamsonIdowu** [wazuh/wazuh#25943]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc1 | Syscollector | Agent | Packages | macOS Sonoma |

## Description
It has been detected in https://github.com/wazuh/wazuh/issues/25825 that syscollector is currently unable to collect npm packages on macOS Sonoma.

A vulnerable npm test package `axios@0.6.0` is shown to be installed [here](https://github.com/wazuh/wazuh/issues/25825#issuecomment-2371203715), but is not detected after syscollector module has completed evaluation.

The package can be found in this location:

```
ec2-user@ip-172-31-44-170 ~ % npm list -g --depth=0
/usr/local/lib
+-- axios@0.6.0
+-- corepack@0.17.2
`-- npm@9.6.6

ec2-user@ip-172-31-44-170 ~ % npm list --depth=0
/Users/ec2-user
`-- (empty)

```

**Comment by vikman90** [comment]
I've successfully reproduced this issue:

```bash
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
nvm install node
npm install -g axios@0.6.0

npm list -g --depth=0
```

```
+-- axios@0.6.0
+-- corepack@0.29.3
`-- npm@10.8.3
```

I found the `axios` package installed at:
```
/Users/vikman/.nvm/versions/node/v22.9.0/lib/node_modules/axios
```

However, that folder is not in the current search list:
https://github.com/wazuh/wazuh/blob/8e0e581a1925a90472fd6a7bdbc358947f809e3f/src/data_provider/src/sharedDefs.h#L125-L135

## Proposed fix

Add `/Users/*/.nvm/versions/node/v*/lib` to the search list.

**Comment by mjcr99** [comment]
## Update 
**(07/10/2024)** Reviewing required changes. Detected some repeteated paths which should be improved. Researching different ways to retrieve packages' information.
