### ISSUE TITLE
Engine - Develop `engine-router` to manage routing

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25947]
**Description:**
The task involves developing `engine-router`, a Python script to replace the `router` command of the Wazuh-Engine CLI. This tool will manage the routing configurations in Wazuh-Engine, allowing for listing, creating, modifying, and deleting routes.

**Requirements:**
- List all current routes in the Wazuh-Engine.
- Create new routes and update existing routes.
- Delete routes from the engine.
- Ensure compatibility with existing Wazuh-Engine API endpoints that handle routing operations.
- Implement logging and error handling for transparency and resilience.

**Deliverables:**
- A fully functional `engine-router` script integrated into the Wazuh-Engine tooling suite.
- Unit tests that validate the tool's functionalities.
- Documentation updates to include instructions on how to use `engine-router`.

**DoD (Definition of Done):**
- [x] The `engine-router` script is implemented and its functionalities verified.
- [ ] Tool is reviewed and merged into the development branch.

**Comment by JcabreraC** [comment]
Extended ETA. The above issues have not been implemented due to priority in other issues.

**Comment by juliancnn** [comment]
## Update

I have added most of the router's features. Testing, documentation and everything related to EPS remain.

**Comment by juliancnn** [comment]
## Update

- Changes for review
