### ISSUE TITLE
Engine - Develop `engine-geo` to manage GeoIP Databases

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#25948]
**Description:**
This task involves creating the `engine-geo` Python script to replace the `geo` command of the Wazuh-Engine CLI. This tool will facilitate the management of GeoIP databases within the Wazuh-Engine, including adding, deleting, listing, and updating GeoIP databases from remote URLs.

**Requirements:**
- Add new GeoIP databases to the Wazuh-Engine.
- Delete existing GeoIP databases without removing the physical file.
- List all GeoIP databases currently utilized by the Wazuh-Engine.
- Update GeoIP databases from remote URLs (remoteUpsert functionality).
- Ensure the script works with the current API socket configuration and respects client timeout settings.

**Deliverables:**
- A fully functional `engine-geo` script that integrates seamlessly with the Wazuh-Engine environment.
- Comprehensive unit tests to ensure all functionalities work as expected.
- Updated documentation detailing how to manage GeoIP databases using `engine-geo`.

**DoD (Definition of Done):**
- [x] The `engine-geo` script correctly implements all specified functionalities.
- [x] The script is reviewed and approved for merging into the main development branch.

**Comment by JcabreraC** [comment]
Extended ETA. The above issues have not been implemented due to priority in other issues.

**Comment by juliancnn** [comment]
# Update

- Add base for tool with add/delete/get commands

**Comment by juliancnn** [comment]
Extended ETA, by highest priority issues
