### ISSUE TITLE
Investigate about agent removal performance improvements

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#25940]
## Description

During #25883, the `DELETE /agents` endpoint failed with a timeout error.

```console
2024/09/24 03:59:46 ERROR: Timeout executing API request
2024/09/24 03:59:46 INFO: wazuh 172.31.23.22 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.053s: 500
```

The request is deleting all the agents registered (50,000 in this case), it is expected that given a higher number of agents, the request will take longer.

```console
gasti@gasti:~/Downloads/archive/master/logs$ cat ossec.log | grep "deleted (requested locally)" | wc -l
50003
```

All agents were deleted in a timespan of 14s, a few seconds more than the timeout (10s).

```
# First deletion
2024/09/24 03:59:41 wazuh-authd: INFO: Agent '7896' (1-ncMUFIkoYBEd48NL-debian10) deleted (requested locally)
# Last deletion
2024/09/24 03:59:55 wazuh-authd: INFO: Agent '23579' (1-pqdgsD8x7v29b4rF-debian10) deleted (requested locally)
```

The performance issue lays in the fact that the framework is deleting agents one by one. For every existing agent, the framework is sending a socket message to authd instructing its deletion.

```
{"function": "remove", "arguments": {"id": str(self.id).zfill(3), "purge": purge}}
```

This issue aims at investigating if it's possible to batch the removal of the agents instead of sending them one by one. The investigation should consider the effort needed to achieve such goal and the fact that these operations won't exist in 5.0.

Artifacts: [artifacts.zip](https://github.com/user-attachments/files/17131303/artifacts.zip)

**Comment by GGP1** [comment]
## Update

I reviewed the authd module `remove` instruction and it does not support specifying multiple agents per command, forcing us to send one message per agent.

```c
  } else if (!strcmp(function->valuestring, "remove")) {
    cJSON *item;
    int purge;

    if (arguments = cJSON_GetObjectItem(request, "arguments"), !arguments) {
        ierror = ENOARGUMENT;
        goto fail;
    }

    if (item = cJSON_GetObjectItem(arguments, "id"), !item) {
        ierror = ENOID;
        goto fail;
    }

    purge = cJSON_IsTrue(cJSON_GetObjectItem(arguments, "purge"));

    response = local_remove(item->valuestring, purge);
  }

....

// Remove an agent
cJSON* local_remove(const char *id, int purge) {
    int index;
    cJSON *response = NULL;

    mdebug2("local_remove(id='%s', purge=%d)", id, purge);

    w_mutex_lock(&mutex_keys);

    if (index = OS_IsAllowedID(&keys, id), index < 0) {
        mdebug1("Error %d: %s.", ERRORS[ENOAGENT].code, ERRORS[ENOAGENT].message);
        response = local_create_error_response(ERRORS[ENOAGENT].code, ERRORS[ENOAGENT].message);
    } else {
        minfo("Agent '%s' (%s) deleted (requested locally)", id, keys.keyentries[index]->name);
        /* Add pending key to write */
        add_remove(keys.keyentries[index]);
        OS_DeleteKey(&keys, id, purge);
        write_pending = 1;
        w_cond_signal(&cond_pending);
        response = local_create_agent_delete_response();
    }

    w_mutex_unlock(&mutex_keys);
    return response;
}
```

Removing agents in batches would require changing the way in which the module operates. Considering it will no longer exist in 5.0, this effort may not be worth the work required.

In addition to this, the timeout error may have been caused by the fact that the build had lower resources than the other test stages. I launched another [build](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/733) with more resources to see if the issue persists.

**Comment by GGP1** [comment]
## Conclusion

Considering that the test did not fail in an instance with higher resources, that removing several agents in batches requires refactoring the `wazuh-authd` module and that the agents enrollment will change completely in 5.0, I don't think it's worth putting effort into this task.

**Comment by javiersanchz** [comment]
## Review

As can be seen, the error was due to a lack of resources when assigning them as a parameter, and increasing them resolves the issue.

On my part, I believe Gasti's investigation and final conclusion are correct!

LGTM!

**Comment by fdalmaup** [comment]
# Review
This issue must be considered when errors related to `authd` are seen in stress tests where many agents are involved.

LGTM!
