### ISSUE TITLE
Add efficacy test for docker translation

### ISSUE THREAD

**Issue by Damian-Mangold** [wazuh/wazuh#25969]
## Description

This issue aims to add the efficiency test to verify the translation of Docker for Windows and MacOS operating systems.

## Expected

Add the efficiency tests and verify that the translations are correctly created.

## DoD
- [x] Efficiency test created
- [x] Successful verification

**Comment by tsarquis88** [comment]
Moving this to on hold until the translation is present in the CTI database.

**Comment by tsarquis88** [comment]
# Update

Efficacy tests implemented.

**Comment by Damian-Mangold** [comment]
ETA Updated

Reason: Test failures due to a GA problem https://github.com/wazuh/wazuh/issues/26090
