### ISSUE TITLE
GitHub Action for Vulnerability Database Generation is not working

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#25974]
**Summary:**

The GitHub Action for generating the vulnerability database has encountered two issues that need to be resolved for successful execution. Below are the details of the problems observed in the scheduled update jobs.

---

**Job Details:**

1. **Job:** `vulnerability_scanner_database_scheduled_update (v4.10.0)`  
   **Issue:**  
   - **Warning Message:** `Unable to find tag v4.10.0. Continuing with branch 4.10.0`  
   - **Description:** The action is unable to locate the specified tag for version `4.10.0`, which may affect the integrity of the database update process.

2. **Job:** `vulnerability_scanner_database_scheduled_update (v4.8.0)`  
   **Issue:**  
   - **Error Message:** `The user-provided path vd_1.0.0_vd_4.8.0.tar.xz does not exist.`  
   - **Description:** The specified path for the tarball does not exist, preventing the action from accessing necessary data for version `4.8.0`.

---

**Action Items:**

1. **Investigate the missing tag for `4.10.0`:**  
   - Confirm whether the tag `v4.10.0` was created in the repository.
   - If the tag is missing, decide if it should be created based on the latest commit or if the action should reference a different existing tag or branch.

2. **Resolve the path issue for `4.8.0`:**  
   - Verify the expected path for the tarball `vd_1.0.0_vd_4.8.0.tar.xz` in the cloud.
   - Check if the file has been renamed, moved, or deleted.
   - Update the action to provide the correct path or restore the missing file as necessary.

4. **Test the Changes:**  
   - After implementing the above fixes, run the GitHub Action to ensure both jobs are completed successfully without warnings or errors.

---

**Expected Outcome:**

- The `vulnerability_scanner_database_scheduled_update` job should complete successfully for both versions (`4.10.0` and `4.8.0`) without encountering warnings or errors.
- All paths provided in the action should exist and be correctly referenced.

**Comment by MiguelazoDS** [comment]
# Analysis 

There are 3 types of errors here 

Taking a look at https://github.com/wazuh/wazuh/actions/workflows/vulnerability-scanner-generate-database.yml we can see. 

## Scheduled database generation for v4.8.0
- The user-provided path vd_1.0.0_vd_4.8.0.tar.xz does not exist. 

## Scheduled database generation for v4.10.0
- Warning: Unable to find tag v4.10.0. Continuing with branch 4.10.0

## Manually database generation 
- It does not compile the external dependencies (curl maybe?)

**Comment by MiguelazoDS** [comment]
## Scheduled database generation for v4.10.0 :red_circle: 
> [!NOTE]
> Warning: Unable to find tag v4.10.0. Continuing with branch 4.10.0
https://github.com/wazuh/wazuh/actions/runs/11062389201/job/30736789731

This error comes with a bad command to get the branch after a failing tag reference 

https://github.com/wazuh/wazuh/blob/9ca5bdc9a7ad99c2ecab085705031ed34f3bb231/.github/workflows/vulnerability-scanner-generate-database.yml#L55

---

## Manually database generation :green_circle: 
> [!NOTE]
> It does not compile the external dependencies. 

### Conclusion

It is not intended to be run in the master branch. 
https://github.com/wazuh/wazuh/actions/runs/11056752548

So changing to a branch from 4.10.0 (https://github.com/wazuh/wazuh/pull/25681) the compilation steps work.
https://github.com/wazuh/wazuh/actions/runs/11071678377/job/30764086761

![image](https://github.com/user-attachments/assets/00654b7e-aff0-4a6f-a004-53762a2176f8)

This is working

> [!CAUTION]
> Although it was not tested, giving an empty box to type the content version manually without any restriction will generate wrong names for the compressed database.

**Comment by MiguelazoDS** [comment]
Pending review 

This is working although it is more a workaround than a fix 

https://github.com/wazuh/wazuh/actions/runs/11078115363/job/30784794054?pr=25997

v4.8.0 (tag)
![image](https://github.com/user-attachments/assets/37f35a09-ebf7-459c-aa45-7a7bcdb2edf6)
![image](https://github.com/user-attachments/assets/66b7f684-c683-4072-bc88-c7eef2d919ad)

4.10.0(branch)
![image](https://github.com/user-attachments/assets/a6a06ff3-0358-4170-875b-b3ed047b2a30)
![image](https://github.com/user-attachments/assets/4a79cbf6-f038-4c6b-afa4-08d542795149)

> [!IMPORTANT]
> The last commit should be removed.

**Comment by sebasfalcone** [comment]
## ETA update
I want to validate some things with @Dwordcito first

Manual dispatch is working, we can re-generate the DBs on Monday if needed
