### ISSUE TITLE
Standardize Package Generation Process for Wazuh on ARM64 Linux

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#25979]
## Description

Currently, we are using different systems to generate packages for the Wazuh Manager and Agent on the ARM64 architecture for Linux. The Wazuh Agent package generation process uses an allocator provided by the DevOps team, while the Wazuh Manager package generation is handled via a GitHub runner.

Our objective is to standardize the package generation process so that both the Wazuh Manager and Agent use the same underlying system for package generation. This will simplify the workflow, reduce inconsistencies, and make the process easier to maintain.

## Tasks

1. **Discuss with DevOps team**: Coordinate with the DevOps team to determine the most appropriate system to use for package generation.
2. **Adapt Manager package generation**: Update the Wazuh Manager package generation workflow to use the agreed-upon system, if necessary.
3. **Adapt Agent package generation**: Update the Wazuh Agent package generation workflow to align with the standard system, if necessary.
4. **Testing**: Ensure that the package generation works correctly for both Manager and Agent on ARM64 Linux.

## Acceptance Criteria

- Both the Wazuh Manager and Agent packages for ARM64 Linux are generated using the same underlying system.
- Successful testing of generated packages.

**Comment by mjcr99** [comment]
## Update
**(14/10/2024)** I have researched the billing implications of this change. The per minute cost for arm runners are listed [here](https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-actions/about-billing-for-github-actions#per-minute-rates-for-arm64-powered-larger-runners). We are already using GHA runners for ARM architecture for building managers, as seen here:
* https://github.com/wazuh/wazuh/blob/42c06f5db6f963a7a602aacea60402cad483c04c/.github/workflows/packages-build-manager.yml#L95

The used machine is Linux 2-core, so the pricing is the cheapest, $0.005 per minute. Having a manager package building time of 10 - 12 minutes, the cost to build a manager package would be close to $0.10 - $0.12.

**Comment by vikman90** [comment]
We're finally dismissing this issue.
