### ISSUE TITLE
Removing the ss4o index templates -   Release 4.9.1 - RC 1 - E2E UX tests - Central components upgrade

### ISSUE THREAD

**Issue by ihost-007** [wazuh/wazuh#25971]
Removing the ss4o index templates is part of the steps for upgrading the Wazuh, refer to the [documentation](https://documentation-dev.wazuh.com/v4.9.1-rc1/upgrade-guide/upgrading-central-components.html#upgrading-the-wazuh-indexer). However, during the test for [Release 4.9.1 - RC 1 - E2E UX tests - Central components upgrade](https://github.com/wazuh/wazuh/issues/25823) this step returns an error.

```
root@indexer:/home/vagrant#  curl -X DELETE "https://192.168.33.194:9200/_index_template/ss4o_*_template" -u admin:pM8kWrINZ2Wl0SVZ9a+******** -k
{"error":{"root_cause":[{"type":"index_template_missing_exception","reason":"index_template [ss4o_*_template] missing"}],"type":"index_template_missing_exception","reason":"index_template [ss4o_*_template] missing"},"status":404}
```

**Comment by AlexRuiz7** [comment]
Testing on which versions of OpenSearch these templates are created.

| Wazuh version | OpenSearch version | Templates created |
| ------------- | ------------------ | ----------------- |
| 4.8.2         | 2.10.0             | yes               |
| 4.9.0         | 2.13.0             | no                |
| 4.10.0        | 2.16.0             | no                |

It seems that from 4.9.0 and above, these templates are no longer generated by OpenSearch's observability plugin.

The step to remove these index templates can be skipped if wazuh-indexer is upgraded from 4.9.0 and above.
Upgrades from versions below 4.8.0 will need to run this step.

**Comment by AlexRuiz7** [comment]
I tried to upgrade from a v4.8.2 to a v4.9.1 directly without removing the `ss4o` index templates, but could continue as the GPG keys are failing.

```console
root@ubuntu2204:/home/vagrant# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
```

**Comment by AlexRuiz7** [comment]
The step to remove the ss4o index templates was for 4.8.0.

- https://github.com/wazuh/wazuh-indexer/issues/171

As the templates are no longer created on the OpenSearch versions we are supporting in future releases, I think it's safe to delete that step for the upgrade guide to 4.9.1 and above.
