### ISSUE TITLE
Vulnerability detector timeout + weird behavior

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#2599]
| Version | Revision | Branch |
| --- | --- | --- |
| 3.9.0 | 3901 | 3.9 |

**Request timeout**

> 2019/02/14 11:52:32 wazuh-modulesd: WARNING: CURL ERROR The requested URL returned error: 504 Gateway Time-out

We may want to review timeout for this kind of requests, sometimes those large files may take a bit longer time than expected.

**Do not abort all the fetching function if one page fails**

> 2019/02/14 11:53:38 wazuh-modulesd:vulnerability-detector: ERROR: (5489): There was no valid response to 'https://access.redhat.com/labs/securitydataapi/cve.json?after=2010-01-01&per_page=1000&page=6' after 3 attempts.

Vulnerability is aborting all the fetching function if one page fails, we may want to store partial results. It's better to have 9.500 items of 10.000 than just zero.

**Be consistent between logs**

> 2019/02/14 11:53:38 wazuh-modulesd:vulnerability-detector: ERROR: (5400): REDHAT database could not be fetched.
2019/02/14 11:53:38 wazuh-modulesd:vulnerability-detector: ERROR: (5426): CVE database could not be updated.
...
2019/02/14 12:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5494): The update of the feeds ended successfully.
2019/02/14 12:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5452): Starting vulnerability scanning.
2019/02/14 12:08:52 wazuh-modulesd:vulnerability-detector: INFO: (5453): Vulnerability scanning finished.

**Do not start the scan if there are zero CVEs**

Once Vulnerability is enabled, the databases must always have information. Vulnerability should detect if there are zero CVEs to be analyzed.

**Unify severity**

Each feed comes with its own severity values. What Vulnerability should do is to unify that value. 

> Eg: "Moderate", "moderate", "Medium", "medium" --> "Medium"

Regards

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/2603.

**Comment by albertomn86** [comment]
Merged
