### ISSUE TITLE
Delay in starting the Wazuh-Agent process after the registration in macOS Sequoia AMD64

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25993]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh component | Agent | Packages | macOS Sequoia 15 AMD64 |

Testing in DTT with [macOS Sequoia 15 AMD64 and ARM64](https://github.com/wazuh/wazuh/issues/24157)

We noticed on AMD64 that after:
1. Installing the agent
2. Modifying the `MANAGER_IP` data in `ossec.conf`
3. Starting the service

By running: `ps aux | grep wazuh-agent | grep -v grep`

There is a delay in the appearance of the process.

By adding 5 seconds the test works correctly.

On ARM64 it has not happened.

--- 

In order to test this behavior and simulate the automated rest:

1. Install agent
2. Create a bash script that performs a sed modifying the `MANAGER_IP`, start the service and immediately run `ps aux | grep wazuh-agent | grep -v grep`

It is suggested to do it this way since it will be difficult to manually execute all these commands sequentially and quickly.

I also report that in both Ventura 13 and Sonoma 14 (ARM and AMD) this behavior has not been demonstrated.

**Comment by vikman90** [comment]
@pro-akim do you mean this command?

```sh
/Library/Ossec/bin/wazuh-control start && ps aux | grep wazuh-agent | grep -v grep
```

I'm trying to figure out how this can occur, since `wazuh-control` is expected to check each process as it start them.

**Comment by vikman90** [comment]
@pro-akim As we discussed on Slack, there is no implementation difference between ARM64 and Intel64 for macOS.

I bet this is a timing issue. For example, the process status is checked just as the agent is restarting. This can happen, and we have had similar cases in the past few months.

For this, I recommend using the `wazuh-control` tool to manage the agent status. For example:
```
bin/wazuh-control status | grep wazuh-agent
```

This will handle the service manager mutex, and will probably fix the problem.

Cheers!
