### ISSUE TITLE
Vulnerablity Detector - Update efficacy tests

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26009]
## Description
This issue aims to update the efficacy tests used for the Vulnerability Scanner, based on updates in the content

- [Failing test logs](https://github.com/user-attachments/files/17167624/Test-logs.txt)

## DoD
- [x] Efficacy tests pass
- [x] Changes justified

**Comment by Damian-Mangold** [comment]
Hi @sebasfalcone , here the tests fail for another reason, could you check if it is related to this ?

- https://github.com/wazuh/wazuh/pull/25556
- https://github.com/wazuh/wazuh/pull/25785
- https://github.com/wazuh/wazuh/pull/25805

**Comment by sebasfalcone** [comment]
@pereyra-m Lets also check those failing tests
```
DEBUG    test_efficacy_log:test_efficacy_log.py:64 Running test engine/source/vdscanner/qa/test_false_negative_data/001/input_001.json
DEBUG    urllib3.connectionpool:connectionpool.py:475 http://localhost:None "POST /vulnerability/scan HTTP/1.1" 500 38
INFO     test_efficacy_log:test_efficacy_log.py:49 Socket error Error sending data to the socket: 500
assert 500 == 200
 +  where 500 = <Response [500]>.status_code
DEBUG    test_efficacy_log:helpers.py:55 Found '0' matches of a total of '1' expected of regex 'Event type: (.*) processed'.
```

**Comment by pereyra-m** [comment]
## Update

I've created a PR with some changes, but I couldn't reproduce the errors shown above.
