### ISSUE TITLE
Indexer Connector - Drop invalid messages

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26015]
## Description
As a new requirement, the indexer-connector module needs to reject non-json data that is received

To achieve this, we need to set the `allow_exeptions` flag to false while parsing the incoming data;
https://github.com/wazuh/wazuh/blob/f79cdb0e72ed19a2159e32c6e162e0dd15b8d365/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L401

And discard the message

## DoD
- [x] Non-JSON data is now discarded on the indexer
- [x] Updated UTs

**Comment by GabrielEValenzuela** [comment]
# Update

- Task complete and in review process.
