### ISSUE TITLE
Coverity defects on 4.10.0

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26059]
## Description
To improve our code reliability we should address some Coverity defects:

|Status|CID|Type|Impact|Date|Component|Origin|Notes|
|:-:|---|---|---|---|---|---|---|
|🔵 |[1600023](https://scan7.scan.coverity.com/#/project-view/49654/12532?selectedIssue=1600023)|Uninitialized pointer field|Medium|Sep 27, 2024|Vulnerabiliity Scanner| https://github.com/wazuh/wazuh/issues/24967|  |
|🔴|[1600022](https://scan7.scan.coverity.com/#/project-view/49654/12532?selectedIssue=1600022)|COPY_INSTEAD_OF_MOVE|Low|Sep 27, 2024|Content manager| https://github.com/wazuh/wazuh/issues/24967|  |
|🔵|[1600021](https://scan7.scan.coverity.com/#/project-view/49654/12532?selectedIssue=1600021)|Uninitialized pointer field|Medium|Sep 27, 2024|Vulnerabiliity Scanner| https://github.com/wazuh/wazuh/issues/24967 |  |

## DoD
- [x] Defects have been addressed

**Comment by pereyra-m** [comment]
## Update

I analyze the issues to fix or ignore them

**Comment by pereyra-m** [comment]
## Update

I will ignore the false positive in the Coverity system instead of the code. Then, I'll run the scan again.

**Comment by pereyra-m** [comment]
Hi @sebasfalcone 
This issue is still open.
