### ISSUE TITLE
Footprint: Upward trend in block pattern of agent.exe in performance graphs in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26063]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc2 | Wazuh component | Agent | Packages | Windows |

- Testing Footprint test: https://github.com/wazuh/wazuh/issues/26024

Upward trend in block pattern of agent.exe in performance 

v4.9.1-rc2
![image](https://github.com/user-attachments/assets/a48eab60-cbc6-4162-ad16-87cec4992d76)
![image](https://github.com/user-attachments/assets/5ca84f40-67d4-4304-b539-a7e8b91dde2d)
![image](https://github.com/user-attachments/assets/2268792d-db72-4996-b386-63c0ce21e14b)

v4.9.0-rc2
![image](https://github.com/user-attachments/assets/d128b606-c5f9-4475-9d41-6d348829f234)
![image](https://github.com/user-attachments/assets/e45d92e2-f3cc-4d85-a083-94c4002bc9ee)
![image](https://github.com/user-attachments/assets/65b7da6f-98fc-4283-925e-d65487f4d1c8)

Although the upward trend is small over the time covered by the study, it should be analyzed to ensure that it is not a leak.

**Comment by vikman90** [comment]
After reviewing the memory patterns shown in the graph you provided, we have observed the following:

- In both versions, 4.9.0 and 4.9.1, memory usage follows a block pattern where memory usage increases intermittently and then stabilizes.
- For version 4.9.0, the local maximum values appear consistent during each phase, though the minimum values vary slightly. The two highest peaks reach 17.05 MB.
- For version 4.9.1, the memory usage appears more stable, with both maximum and minimum values being more consistent. The maximum peak reaches 1711 MB.

At this time, we do not observe any behavior that would indicate a product issue. The Wazuh agent does not manage memory directly; memory allocation and management are handled by the underlying library. Variations in memory usage, such as fragmentation or peak differences, are not within the scope of the agent's control and do not represent a concern for our product.

Based on this analysis, we are confident that **there is no significant issue**, and we will proceed with closing this issue.

Best regards,
