### ISSUE TITLE
Vulnerability module appears to have stopped operating and appears to be only static.  

### ISSUE THREAD

**Issue by borkedporcupine** [wazuh/wazuh#26088]
4.9 | Vulnerability Component | Quick Start | Quick Start | Ubuntu 24.04.1 LTS Server |

| 0.7 | Vulnerability Assessment | Manager/Agent | WAZUH Repo | Ubuntu 24.04.1 LTS Server |

After upgrading to 4.9 (I think this is the trigger) I am no longer receiving vulnerability events.  Even after actively resolving vulnerabilities in my infrastructure the number of vulnerabilities never decreases or increases.   No new events have been logged since August 23rd.  No notable errors, the dashboard displays without issue but appears to be static content now.  No notable errors in the logs related to vulnerability module. 

It appears the module is no longer functioning but I don't know how to verify it.

**Comment by Damian-Mangold** [comment]
Hi @borkedporcupine  Could you check if all modules are active and working without errors ?

Wazuh Indexer:
  - To check the status of the wazuh-indexer, run the following command:
    - `systemctl status wazuh-indexer`  --->  (must be active - running)
  - To check the cluster health, use:
    - `curl -XGET -k -u user:pass "https://wazuh_indexer_ip:9200/_cluster/health"`   --->  (must be in a green state)


Wazuh Manager:
  - To check the status of the wazuh-manager, run the following command:
    - `systemctl status wazuh-manager`    --->  (must be active - running)


Wazuh Filebeat:
  - To check the status of the wazuh-filebeat, run the following command:
    - `systemctl status filebeat`    --->  (must be active - running)
    - `filebeat test output`    --->  (All OK)


Wazuh dashboard
  - To check the status of the wazuh-dashboard, run the following command:
    - `systemctl status wazuh-dashboard`    --->  (must be active - running)

**Comment by borkedporcupine** [comment]
Wazuh Indexer:

    To check the status of the wazuh-indexer, run the following command:
        systemctl status wazuh-indexer ---> **Active: active (running) since Wed 2024-09-18 20:17:21 UTC; 1 week 5 days ago**

    To check the cluster health, use:
        curl -XGET -k -u user:pass "https://wazuh_indexer_ip:9200/_cluster/health" ---> **{"cluster_name":"wazuh-indexer-cluster","status":"green","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"discovered_master":true,"discovered_cluster_manager":true,"active_primary_shards":326,"active_shards":326,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}**

Wazuh Manager:

    To check the status of the wazuh-manager, run the following command:
        systemctl status wazuh-manager ---> **Active: active (running) since Wed 2024-09-18 20:16:30 UTC; 1 week 5 days ago**

Wazuh Filebeat:

    To check the status of the wazuh-filebeat, run the following command:
        systemctl status filebeat ---> **Active: active (running) since Wed 2024-09-18 20:15:56 UTC; 1 week 5 days ago**
        filebeat test output ---> **Confirmed all OK**

Wazuh dashboard

    To check the status of the wazuh-dashboard, run the following command:
        systemctl status wazuh-dashboard ---> **Active: active (running) since Wed 2024-09-18 20:15:56 UTC; 1 week 5 days ago**

**Comment by borkedporcupine** [comment]
Sorry about this comment, tried bolding my replies but it added it all as code...   Let me know if you are unable to decipher.

**Comment by Damian-Mangold** [comment]
> Sorry about this comment, tried bolding my replies but it added it all as code... Let me know if you are unable to decipher.

Don't worry, I can read it as is.

It looks like all the modules are working without any problems.

**Comment by Damian-Mangold** [comment]
I need you to enable debug level 2. You can do this by changing the `wazuh_modules.debug=2` in the `/var/ossec/etc/internal_options.conf` file.

Then restart the manager `systemctl restart wazuh-manager` and share with me the whole `/var/ossec/logs/ossec.log`

**Comment by borkedporcupine** [comment]
> Could you please enable debug level 2? You can do this by changing the `wazuh_modules.debug=2` in the `/var/ossec/etc/internal_options.conf` file.
> 
> Then restart the manager `systemctl restart wazuh-manager`, wait about 30min and share with me the whole `/var/ossec/logs/ossec.log` file.

[ossec.txt](https://github.com/user-attachments/files/17213501/ossec.txt)

See attached log, let me know if you need anything else.

**Comment by Damian-Mangold** [comment]
Hi @borkedporcupine Could you please check if you shared the complete file with me? The shared file contains very little information.

**Comment by borkedporcupine** [comment]
> Hi @borkedporcupine, The issue seems to stem from a corrupted database, which may have occurred due to an unexpected or uncontrolled shutdown of the Wazuh manager:
> 
> ```
> 2024/10/01 17:16:31 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: While opening a file for sequentially reading: queue/vd/event/MANIFEST-000005: No such file or directory.
> ```
> 
> To resolve this, you should follow the steps outlined in [this workaround](https://github.com/wazuh/wazuh/issues/25698#issuecomment-2364033467). However, **_before proceeding with step 5_**, please ensure that you remove the corrupted database by executing the following command:
> 
> ```
> sudo rm -rf /var/ossec/queue/vd/event
> ```
> 
> Once you've completed this, proceed with the remaining steps and let me know the results after performing this action. Note that after step 8, when you start the manager again you must wait some time until the database is created again and the agents are re-scanned.

I followed this guide, but don't really see anything that looks much different.  I still see the old events, from the 23rd of Aug.  Wouldn't deleting the DB remove those? See screenshot from the terminal.  I captured my commands as well in case I missed a step. 

![Screenshot 2024-10-01 163335](https://github.com/user-attachments/assets/56b77ad9-7851-4d32-9ed9-36d7337b1446)

**Comment by borkedporcupine** [comment]
After sitting overnight I finally have an event.  And the dashboard numbers have finally changed.  So, it appears to be resolved will continue to monitor, but it looks positive.

**Comment by Damian-Mangold** [comment]
Hi @borkedporcupine. Thank you very much for the feedback. What a great news that the vulnerability/events update is already working. Please keep monitoring it and keep me informed.

**Comment by borkedporcupine** [comment]
Can you describe the vulnerability mechanism?  What triggers an event of found or solved?  I still only have 1 singular new event from yesterday.  However the numbers on the dashboard do appear to be going down now as I'm actively solving vulnerabilities.

**Comment by Damian-Mangold** [comment]
Hi @borkedporcupine. Vulnerability events are generated each time Syscollector runs on the agent and detects a change in a package associated with a vulnerability. However, it’s important to note that if the agent is restarted, the type of event registered during the startup is different and is not counted as part of the Vulnerability Detection (VD) events. As a result, in this scenario, you may observe a vulnerability being marked as found or resolved without a corresponding event being generated.

For more details on how alert generation works and the overall vulnerability detection mechanism, you can refer to the official Wazuh documentation at: 
 - [Vulnerability detection](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html)

**Comment by borkedporcupine** [comment]
> Hi @borkedporcupine. Vulnerability events are generated each time Syscollector runs on the agent and detects a change in a package associated with a vulnerability. However, it’s important to note that if the agent is restarted, the type of event registered during the startup is different and is not counted as part of the Vulnerability Detection (VD) events. As a result, in this scenario, you may observe a vulnerability being marked as found or resolved without a corresponding event being generated.
> 
> For more details on how alert generation works and the overall vulnerability detection mechanism, you can refer to the official Wazuh documentation at:
> 
>     * [Vulnerability detection](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html)

@Damian-Mangold Thanks for the link that helps a lot. Appreciate all your help in getting this back up and going for me.

**Comment by RedPandaDoge** [comment]
I have been trying to solve this problem in my own instance for a while now, this thread was the first that helpmed me solve it. 

Followed the steps, checked the log file and same as @borkedporcupine I had the same` vd/event/MANIFEST-000005` file locked.

Removed the folder as instructed and all working again for me.

Thanks @Damian-Mangold

**Comment by Damian-Mangold** [comment]
> > Hi @borkedporcupine. Vulnerability events are generated each time Syscollector runs on the agent and detects a change in a package associated with a vulnerability. However, it’s important to note that if the agent is restarted, the type of event registered during the startup is different and is not counted as part of the Vulnerability Detection (VD) events. As a result, in this scenario, you may observe a vulnerability being marked as found or resolved without a corresponding event being generated.
> > For more details on how alert generation works and the overall vulnerability detection mechanism, you can refer to the official Wazuh documentation at:
> > ```
> > * [Vulnerability detection](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html)
> > ```
> 
> @Damian-Mangold Thanks for the link that helps a lot. Appreciate all your help in getting this back up and going for me.

You're very welcome!. It was a pleasure to help you.
