### ISSUE TITLE
Log correlation failure from different windows agent

### ISSUE THREAD

**Issue by ebenezersolution** [wazuh/wazuh#26081]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.9.0-rev | Rules| Error |

## Description

Good Day!
I'm trying to create a rule to detect password spray
I created the following rules:

```
<group name="windows,windows_system,">
    <rule id="300000" level="10" frequency="3" timeframe="120">
        <if_matched_sid>60122</if_matched_sid>
        <field name="win.eventdata.subStatus">^0xC0000064$</field>
        <different_field>win.eventdata.targetUserName</different_field>
        <description>Possible password spray, different unknown users with login failures. With Agent</description>
        <options>no_full_log</options>
    </rule>

    <rule id="300001" level="12" frequency="3" timeframe="120">
        <if_matched_sid>300000</if_matched_sid>
        <same_field>win.eventdata.workstationName</same_field>
        <description>Possible password spray, different unknown users with login failures same source. With Agent</description>
        <options>no_full_log</options>
    </rule>

    <rule id="300002" level="10" frequency="3" timeframe="120">
        <if_matched_sid>60104</if_matched_sid>
        <field name="win.eventdata.status">^0x6$</field>
        <different_field>win.eventdata.targetUserName</different_field>
        <description>Possible password spray, different unknown users with login failures. No AGENT</description>
        <options>no_full_log</options>
    </rule>

    <rule id="300003" level="12" frequency="3" timeframe="120">
        <if_matched_sid>300002</if_matched_sid>
        <field name="win.eventdata.status">^0x6$</field>
        <same_field>win.eventdata.ipAddress</same_field>
        <description>Possible password spray, different unknown users with login failures same source. No AGENT</description>
        <options>no_full_log</options>
    </rule>
</group>
```

Rule 300000:
I want to identify logon failures of different users that do not exist in active directory
Rule 300001:
I want to identify logon failures of different users that do not exist in active directory and that are coming from the same source host
Rule 300002 and 300003
Same thing as the rules above but without the installation of the wazuh agent respectively

### Current results

When I make 3 login error attempts with 3 different users on the same host, the rule works
However, when I make an error twice on host 01 and once on host 02, it doesn't work... however, my logic should work correctly with rule 300000.
Why can't SIEM concatenate information coming from different agents?
Am I doing something wrong?

![image](https://github.com/user-attachments/assets/19161058-b975-42de-8a19-2731497d1773)

### Expected results

The correct thing would be to correlate the logon failure logs regardless of the agents.
### Log source / integration

Wazuh Agent Windows
### Log reference

Windows eventchannel

**Comment by juliancnn** [comment]
Hi @ebenezersolution,

This is expected, since the default correlation acts on the same agent. It is possible to change this behavior with the [global-frequency](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#global-frequency) so that it does not generate the correlation only between the same agent. It is important to note that this option works at manager level and not at cluster level, that is to say that if you have agents connected to different managers, then you will not be able to correlate events between them.
We know that this can often be a limitation, so we are working to make the correlation rules more complex and powerful in the future. We are currently [developing the wazuh-analysisd replacement,](https://github.com/wazuh/wazuh/issues/23577) and have done [some research on this](https://github.com/wazuh/wazuh/issues/23510).

Regards,

**Comment by ebenezersolution** [comment]
Thank you very much for your feedback!

When there is a password spray attack, it is necessary to fix it globally with all log sources and not just individually.

Good to know that you have already noticed this and are looking to improve it.

Thank you and I am looking forward to the next versions...

I couldn't find an example of how to use global_frequency, would that be the case?



```
<group name="windows,windows_system,">
    <rule id="300000" level="10" frequency="3" timeframe="120">
        <if_matched_sid>60122</if_matched_sid>
        <field name="win.eventdata.subStatus">^0xC0000064$</field>
        <different_field>win.eventdata.targetUserName</different_field>
        <description>Possible password spray, different unknown users with login failures. With Agent</description>
        <options>no_full_log</options>
        <global_frequency />
    </rule>

    <rule id="300001" level="12" frequency="3" timeframe="120">
        <if_matched_sid>300000</if_matched_sid>
        <same_field>win.eventdata.workstationName</same_field>
        <description>Possible password spray, different unknown users with login failures same source. With Agent</description>
        <options>no_full_log</options>
        <global_frequency />
    </rule>

    <rule id="300002" level="10" frequency="3" timeframe="120">
        <if_matched_sid>60104</if_matched_sid>
        <field name="win.eventdata.status">^0x6$</field>
        <different_field>win.eventdata.targetUserName</different_field>
        <description>Possible password spray, different unknown users with login failures. No AGENT</description>
        <options>no_full_log</options>
        <global_frequency />
    </rule>

    <rule id="300003" level="12" frequency="3" timeframe="120">
        <if_matched_sid>300002</if_matched_sid>
        <field name="win.eventdata.status">^0x6$</field>
        <same_field>win.eventdata.ipAddress</same_field>
        <description>Possible password spray, different unknown users with login failures same source. No AGENT</description>
        <options>no_full_log</options>
        <global_frequency />
    </rule>
</group>
```

**Comment by juliancnn** [comment]
> I couldn't find an example of how to use global_frequency, would that be the case?

Yes, this would be the correct way to set up the rules.
I hope this has been useful to you

Regards,

**Comment by JcabreraC** [comment]
I close the issue. Feel free to contact us if you have any other questions.
