### ISSUE TITLE
Database Error when inserting into the alerts table

### ISSUE THREAD

**Issue by stideswell** [wazuh/wazuh#261]
With wazuh-2.1.0 and Postgresql I find that starting up ossec-dbd yields the following error in ossec.log ...

_2017/11/10 15:53:05 ossec-dbd: INFO: Connected to database 'ossec' at '127.0.0.1'.
2017/11/10 15:53:05 ossec-dbd: ERROR: (5204): Database error. Unable to run query.
2017/11/10 15:53:10 ossec-dbd: ERROR: (5203): Error executing query 'INSERT INTO alert(server_id,rule_id,level,timestamp,location_id,src_ip,src_port,dst_ip,dst_port,alertid,"user",full_log) VALUES ('1', '502','3','1510289590', '2', '(null)', '0', '(null)', '0', '1510289587.35288', '(null)', 'ossec: Ossec started.')'. Error: 'ERROR:  invalid input syntax for integer: "(null)"
LINE 1: ...ll_log) VALUES ('1', '502','3','1510289590', '2', '(null)', ...
                                                             ^
'.
2017/11/10 15:53:10 ossec-dbd: INFO: (5209): Closing connection to database._

Clearly **src_ip** does not conform to INT8, but why is the value '(null)' held at this point? I believe the insertions relate to log events associated with the restarting the wazuh server's own processes which might, in part, explain why no IP address value is held.

**Comment by stideswell** [comment]
BTW this is on Ubuntu 16.04.

I'm just a "hacker" (in the least impressive sense of the word) sysadmin but this _appears_ to be easily resolved by making a tiny change to **src/os_dbd/alert.c** ...
200c200
<                  "VALUES ('%u', '%u','%u','%u', '%u', '%lu', '%u', '%lu', '%u', '%s', '%s', '%s')",
---
>                  "VALUES ('%u', '%u','%u','%u', '%u', '%s', '%u', '%s', '%u', '%s', '%s', '%s')",

In other words don't use **string** formatting but **long unsigned integer** instead in **snprintf** for the POSTGDB usage case. Perhaps this defect has been present for a long time, but has been exposed by a change in an underlying library (software update on my host)? Though, by comparison with the same file in the OSSEC (2.8.3) source, it looks as though the separation into a MYSQLDB and POSTGDB cases is where this was introduced - so it is a new bug in either OSSEC or Wazuh stemming from around that time.

**Comment by crolopez** [comment]
Hi @stideswell,

Thank you for reporting that bug, we are working on it. You will have a solution soon.

Best regards.

**Comment by crolopez** [comment]
Hi @stideswell,

The fix will be included in the next release. Thanks for your feedback!

Best regards.
