### ISSUE TITLE
Wazuh 4.9.0-1 not capturing EventID 4624 for Windows Server 2022

### ISSUE THREAD

**Issue by ryanrudolfoba** [wazuh/wazuh#26105]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-1 | Wazuh Manager | Manager | Packages | AlmaLinux 9.4 |
| 4.9.0-1 | Wazuh Agent | Agent | MSI | Windows Server 2022 |
| 4.8.2-1 | Wazuh Agent | Agent | MSI | Windows Server 2022 |

### Here is sample log -

> {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4624","version":"2","level":"0","task":"12544","opcode":"0","keywords":"0x8020000000000000","systemTime":"2024-10-02T14:00:11.2043799Z","eventRecordID":"8018237","processID":"684","threadID":"2348","channel":"Security","computer":"redacted.com","severityValue":"AUDIT_SUCCESS","message":"\"An account was successfully logged on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nLogon Information:\r\n\tLogon Type:\t\t3\r\n\tRestricted Admin Mode:\t-\r\n\tVirtual Account:\t\tNo\r\n\tElevated Token:\t\tYes\r\n\r\nImpersonation Level:\t\tImpersonation\r\n\r\nNew Logon:\r\n\tSecurity ID:\t\tS-1-5-21-2009767785-3115395534-1445535999-32672\r\n\tAccount Name:\t\tuseraccount\r\n\tAccount Domain:\t\tredacted.com\r\n\tLogon ID:\t\t0x22CAAEBA\r\n\tLinked Logon ID:\t\t0x0\r\n\tNetwork Account Name:\t-\r\n\tNetwork Account Domain:\t-\r\n\tLogon GUID:\t\t{405e5cd9-5ff3-7e39-278a-bb886fd77d1a}\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x0\r\n\tProcess Name:\t\t-\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\t-\r\n\tSource Network Address:\t10.10.10.10\r\n\tSource Port:\t\t58780\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tKerberos\r\n\tAuthentication Package:\tKerberos\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\r\n\r\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\r\n\r\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.\""},"eventdata":{"subjectUserSid":"S-1-0-0","subjectLogonId":"0x0","targetUserSid":"S-1-5-21-2009767785-3115395534-1445535999-32672","targetUserName":"username","targetDomainName":"redacted.com","targetLogonId":"0x22caaeba","logonType":"3","logonProcessName":"Kerberos","authenticationPackageName":"Kerberos","logonGuid":"{405e5cd9-5ff3-7e39-278a-bb886fd77d1a}","keyLength":"0","processId":"0x0","ipAddress":"10.10.10.10","ipPort":"58780","impersonationLevel":"%%1833","virtualAccount":"%%1843","targetLinkedLogonId":"0x0","elevatedToken":"%%1842"}}}

### When I put it on wazuh-logtest it gets decoded correctly but it doesnt show up in alerts.log or alerts.json.
Here is screenshot of wazuh-logtest -
![image](https://github.com/user-attachments/assets/51d14bf5-2212-429c-914f-2482eb97fcc2)
![image](https://github.com/user-attachments/assets/7f866821-30e8-4d4e-b634-cf9e4d889747)
![image](https://github.com/user-attachments/assets/3bf20234-e691-42c6-9db6-cf76cce47ea6)

### I've enabled logall json in the config and here is sample json log file -

> {"timestamp":"2024-10-02T10:45:43.493-0400","agent":{"id":"002","name":"computer","ip":"10.20.20.20"},"manager":{"name":"ossec"},"id":"1727880343.10901968","full_log":"{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-a5ba-3e3b0328c30d}\",\"eventID\":\"4624\",\"version\":\"2\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8020000000000000\",\"systemTime\":\"2024-10-02T14:45:43.3997140Z\",\"eventRecordID\":\"8019581\",\"processID\":\"684\",\"threadID\":\"2348\",\"channel\":\"Security\",\"computer\":\"computer\",\"severityValue\":\"AUDIT_SUCCESS\",\"message\":\"\\\"An account was successfully logged on.\\r\\n\\r\\nSubject:\\r\\n\\tSecurity ID:\\t\\tS-1-0-0\\r\\n\\tAccount Name:\\t\\t-\\r\\n\\tAccount Domain:\\t\\t-\\r\\n\\tLogon ID:\\t\\t0x0\\r\\n\\r\\nLogon Information:\\r\\n\\tLogon Type:\\t\\t3\\r\\n\\tRestricted Admin Mode:\\t-\\r\\n\\tVirtual Account:\\t\\tNo\\r\\n\\tElevated Token:\\t\\tYes\\r\\n\\r\\nImpersonation Level:\\t\\tImpersonation\\r\\n\\r\\nNew Logon:\\r\\n\\tSecurity ID:\\t\\tS-1-5-21-2009767785-3115395534-1445535999-32672\\r\\n\\tAccount Name:\\t\\tusername\\r\\n\\tAccount Domain:\\t\\tredacted.com\\r\\n\\tLogon ID:\\t\\t0x22DD323C\\r\\n\\tLinked Logon ID:\\t\\t0x0\\r\\n\\tNetwork Account Name:\\t-\\r\\n\\tNetwork Account Domain:\\t-\\r\\n\\tLogon GUID:\\t\\t{74fee08f-cdc0-1bfe-dfca-c75c74eaa055}\\r\\n\\r\\nProcess Information:\\r\\n\\tProcess ID:\\t\\t0x0\\r\\n\\tProcess Name:\\t\\t-\\r\\n\\r\\nNetwork Information:\\r\\n\\tWorkstation Name:\\t-\\r\\n\\tSource Network Address:\\t10.10.10.10\\r\\n\\tSource Port:\\t\\t63099\\r\\n\\r\\nDetailed Authentication Information:\\r\\n\\tLogon Process:\\t\\tKerberos\\r\\n\\tAuthentication Package:\\tKerberos\\r\\n\\tTransited Services:\\t-\\r\\n\\tPackage Name (NTLM only):\\t-\\r\\n\\tKey Length:\\t\\t0\\r\\n\\r\\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\\r\\n\\r\\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\\r\\n\\r\\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\\r\\n\\r\\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\\r\\n\\r\\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\\r\\n\\r\\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\\r\\n\\r\\nThe authentication information fields provide detailed information about this specific logon request.\\r\\n\\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\\r\\n\\t- Transited services indicate which intermediate services have participated in this logon request.\\r\\n\\t- Package name indicates which sub-protocol was used among the NTLM protocols.\\r\\n\\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.\\\"\"},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-5-21-2009767785-3115395534-1445535999-32672\",\"targetUserName\":\"username\",\"targetDomainName\":\"redacted.com\",\"targetLogonId\":\"0x22dd323c\",\"logonType\":\"3\",\"logonProcessName\":\"Kerberos\",\"authenticationPackageName\":\"Kerberos\",\"logonGuid\":\"{74fee08f-cdc0-1bfe-dfca-c75c74eaa055}\",\"keyLength\":\"0\",\"processId\":\"0x0\",\"ipAddress\":\"10.10.10.10\",\"ipPort\":\"63099\",\"impersonationLevel\":\"%%1833\",\"virtualAccount\":\"%%1843\",\"targetLinkedLogonId\":\"0x0\",\"elevatedToken\":\"%%1842\"}}}","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4624","version":"2","level":"0","task":"12544","opcode":"0","keywords":"0x8020000000000000","systemTime":"2024-10-02T14:45:43.3997140Z","eventRecordID":"8019581","processID":"684","threadID":"2348","channel":"Security","computer":"computer","severityValue":"AUDIT_SUCCESS","message":"\"An account was successfully logged on.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nLogon Information:\r\n\tLogon Type:\t\t3\r\n\tRestricted Admin Mode:\t-\r\n\tVirtual Account:\t\tNo\r\n\tElevated Token:\t\tYes\r\n\r\nImpersonation Level:\t\tImpersonation\r\n\r\nNew Logon:\r\n\tSecurity ID:\t\tS-1-5-21-2009767785-3115395534-1445535999-32672\r\n\tAccount Name:\t\tusername\r\n\tAccount Domain:\t\tredacted.com\r\n\tLogon ID:\t\t0x22DD323C\r\n\tLinked Logon ID:\t\t0x0\r\n\tNetwork Account Name:\t-\r\n\tNetwork Account Domain:\t-\r\n\tLogon GUID:\t\t{74fee08f-cdc0-1bfe-dfca-c75c74eaa055}\r\n\r\nProcess Information:\r\n\tProcess ID:\t\t0x0\r\n\tProcess Name:\t\t-\r\n\r\nNetwork Information:\r\n\tWorkstation Name:\t-\r\n\tSource Network Address:\t10.10.10.10\r\n\tSource Port:\t\t63099\r\n\r\nDetailed Authentication Information:\r\n\tLogon Process:\t\tKerberos\r\n\tAuthentication Package:\tKerberos\r\n\tTransited Services:\t-\r\n\tPackage Name (NTLM only):\t-\r\n\tKey Length:\t\t0\r\n\r\nThis event is generated when a logon session is created. It is generated on the computer that was accessed.\r\n\r\nThe subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.\r\n\r\nThe logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).\r\n\r\nThe New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.\r\n\r\nThe network fields indicate where a remote logon request originated. Workstation name is not always available and may be left blank in some cases.\r\n\r\nThe impersonation level field indicates the extent to which a process in the logon session can impersonate.\r\n\r\nThe authentication information fields provide detailed information about this specific logon request.\r\n\t- Logon GUID is a unique identifier that can be used to correlate this event with a KDC event.\r\n\t- Transited services indicate which intermediate services have participated in this logon request.\r\n\t- Package name indicates which sub-protocol was used among the NTLM protocols.\r\n\t- Key length indicates the length of the generated session key. This will be 0 if no session key was requested.\""},"eventdata":{"subjectUserSid":"S-1-0-0","subjectLogonId":"0x0","targetUserSid":"S-1-5-21-2009767785-3115395534-1445535999-32672","targetUserName":"username","targetDomainName":"redacted.com","targetLogonId":"0x22dd323c","logonType":"3","logonProcessName":"Kerberos","authenticationPackageName":"Kerberos","logonGuid":"{74fee08f-cdc0-1bfe-dfca-c75c74eaa055}","keyLength":"0","processId":"0x0","ipAddress":"10.10.10.10","ipPort":"63099","impersonationLevel":"%%1833","virtualAccount":"%%1843","targetLinkedLogonId":"0x0","elevatedToken":"%%1842"}}},"location":"EventChannel"}

### Here is wazuh logtest of the json log. It just sits at Phase 2 completed decoding name 'json' -
![image](https://github.com/user-attachments/assets/200e4f81-e143-4de0-b3e0-1e46308ffe79)
![image](https://github.com/user-attachments/assets/26e0916c-6d3c-4e18-aea8-67ea31b61770)

### Additional info
I have an older wazuh 4.2.1-1 that is working fine - im able to see 4624 eventID.
For testing I've backed up the `/var/ossec/ruleset folder` of 4.9.0-1, deleted it and copied over the `/var/ossec/ruleset folder` from 4.2.1-1. 
Restarted the wazuh manager and after that im getting the 4624 eventID on 4.9.0-1. 
So i think something is broken on the default rules / decoder for 4.9.0-1 but i cant pinpoint which one. 
Please help to fix it!

**Comment by ryanrudolfoba** [comment]
The sample json log file came from /var/ossec/logs/archives/archives.json


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by branchnetconsulting** [comment]
OK that was just an artefact of the way you pulled it from the archives.json record.   Your first example tripped rule 92651 but note the rule's level is 0 which means it will not generate an alert or be written to alerts or archives json files.

**Comment by ryanrudolfoba** [comment]
thank you so much that fixed it!

**Comment by branchnetconsulting** [comment]
You are very welcome!

**Comment by Trapulo** [comment]
Hi,
I've same problem running 4.10.1: 4624 from Win AD controller are missing. I cannot understand how to fix it, someone can explain?

thanks

**Comment by branchnetconsulting** [comment]
@Trapulo, you will probably get the best help if you inquire about this on the Wazuh Slack #community channel or the mailing list.
https://wazuh.com/community/
Also, include as much detail as you can to get faster help.
