### ISSUE TITLE
Exception in ASGI application error message was found in Vulnerability detection performance test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26117]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  v4.9.1-rc2  | 1   | Development   |  VD  | Assistant |  

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/26066, the test `Very high Activity` failed. In this test it could be seen the following log:
```
2024/09/30 23:32:44 ERROR: Exception in ASGI application
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
    |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    |     raise RuntimeError("No response returned.")
    | RuntimeError: No response returned.
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    raise RuntimeError("No response returned.")
RuntimeError: No response returned.
  File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
TypeError: 'coroutine' object is not callable
```
A linked error was found and fixed was performed in this issue: https://github.com/wazuh/wazuh/issues/22735

### Environment

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Very High Activity | Simulate a large-scale environment with significant activity | 10 | 3 | 50000 | 1 | 1h |

### Steps to reproduce

1. Execute a test in https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics by using the following parameters
![image](https://github.com/user-attachments/assets/79d5845a-1ee0-4c47-881a-4762a086b033)
![image](https://github.com/user-attachments/assets/390b0d7f-87e7-4235-8ac4-c08214df79a8)
![image](https://github.com/user-attachments/assets/24665d53-0af7-4458-960f-5ef16686f8fd)
![image](https://github.com/user-attachments/assets/711a7f25-9f52-4362-95de-0e80cbc264fa)
2. Check the logs

### Current result

The mentioned log could be seen

### Expected result
Absence of error logs

### Attachments

As the artifact is to heavy I am attaching only 1 example from all of these:

<details>

```

akim@akim-PC:~/Downloads$ grep -r "Exception in ASGI application" .
./worker_9/logs/api.log:2024/09/30 23:32:44 ERROR: Exception in ASGI application
./worker_9/logs/api.log:2024/09/30 23:32:45 ERROR: Exception in ASGI application
./worker_9/logs/api.log:2024/09/30 23:32:45 ERROR: Exception in ASGI application
./worker_7/logs/api.log:2024/09/30 23:32:44 ERROR: Exception in ASGI application
./worker_5/logs/api.log:2024/09/30 23:32:44 ERROR: Exception in ASGI application

```
</details>

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/739/
- Build parameters: Mentioned previously
- Artifacts/Logs: 
Worker 9:
[api.log](https://github.com/user-attachments/files/17243036/api.log)

**Comment by GGP1** [comment]
## Update

This is an [issue](https://github.com/encode/starlette/issues/2516) with the starlette `BaseHTTPMiddleware` that was fixed in  [v0.38.3](https://github.com/encode/starlette/tree/0.38.3) by [this](https://github.com/encode/starlette/pull/2620) pull request. 

We should upgrade the starlette dependency to fix the error. I've opened the issue #26140 for this.

**Comment by RamosFe** [comment]
LGTM 🚀

**Comment by fdalmaup** [comment]
# Review

As stated in the issue shared by @GGP1, the error is raised when the client drops the connection during a request. This condition is obtained under certain circumstances, it does not represent a very high-impact bug but will be fixed in the next minor version.
