### ISSUE TITLE
Vulnerability Detector - Port "Adjustment of vulnerability descriptions" from 4.10.0

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26130]
## Description
This issue aims to port the changes related to the ADP descriptive information usage, from 4.10.0 into 5.0.0:
- https://github.com/wazuh/wazuh/issues/25479

This will ensure consistency and accuracy on the descriptive information from generated events and alerts for the Vulnerability Detector module

>[!IMPORTANT]
> We are not going to update the store model, this includes:
> - updateCVEDescription.hpp
> - databaseFeedManager.hpp
> Instead, we are going to rely solely on the generated content from 4.10.0 to serve this functionality

## DoD
- [x] Changes ported
- [x] Updated testing
- [x] Tested behaviour

**Comment by sebasfalcone** [comment]
## Update
Remember to add this field into the API response

**Comment by sebasfalcone** [comment]
## ETA updated
Due to higger priority issues:
- https://github.com/wazuh/wazuh/issues/26528

**Comment by sebasfalcone** [comment]
## Update
Still working in higger priority issues

**Comment by sebasfalcone** [comment]
## Update
Still working on higger priority issues

**Comment by sebasfalcone** [comment]
## Update
Still working on higher priority issues

**Comment by pereyra-m** [comment]
## Update

I begin with the feature port. First, I'll review what is ready and what is missing.

**Comment by pereyra-m** [comment]
## Update

I continue with the feature porting. I'm moving the new classes, adapting the tests, removing sections no longer required, etc.

**Comment by pereyra-m** [comment]
## Update

Now that the changes are ported, I'll fix the failing UT and perform more manual tests.

**Comment by pereyra-m** [comment]
## Update

I check the coverage failure.

**Comment by pereyra-m** [comment]
## Update

I create another issue for the coverage problem and revert the commit
