### ISSUE TITLE
Wazuh and MISP integration

### ISSUE THREAD

**Issue by pesquisa1234** [wazuh/wazuh#26131]
How do I do integration with MISP?

**Comment by nbertoldo** [comment]
Hi @pesquisa1234,

I hope you are doing fine.
 
There is no official Wazuh documentation for an integration with MISP.
Such an integration would require the use of a custom Python script that would interface with the MISP API. This script should follow the general guidelines set in the following documentation:

[Creating an integration script](https://documentation.wazuh.com/current/user-manual/manager/integration-with-external-apis.html#creating-an-integration-script)

You should save that script in the location `/var/ossec/integrations` of the manager node that will handle that integration, and set the following section in that node's `/var/ossec/etc/ossec.conf` file.

```xml
<integration>
   <name>custom-misp-integration</name>
   <group>RULES_GROUPS</group>
   <alert_format>json</alert_format>
</integration>
```

Where `custom-misp-integration` is the name of the custom script and `RULES_GROUPS` is the list of groups which the alerts that trigger the integration belong to. Alternatively, a `<rule_id>` segment can be used in place of the group, to specify each individual rule. You can find more information on the available settings in the official documentation:

[integration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html)

Remember to restart the manager service to set the configuration.

```console
systemctl restart wazuh-manager
```

You can find an example of a custom integration (but for a different product) in the documentation:

[How to integrate external software using Integrator](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/)

I hope this was helpful.
Regards

**Comment by pesquisa1234** [comment]
I did like this and it did not worked:

**custom-misp.py:**

```python
#!/usr/bin/env python

import sys
import os
import json
import ipaddress
import requests
from requests.exceptions import ConnectionError, HTTPError
from socket import socket, AF_UNIX, SOCK_DGRAM
import time

# Enable or disable debugging
debug_enabled = True  # Set to False to disable debug logging

# File and socket paths
pwd = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
socket_addr = f'{pwd}/queue/sockets/queue'

# Set paths for logging
now = time.strftime("%a %b %d %H:%M:%S %Z %Y")
log_file = f'{pwd}/logs/integrations.log'

def debug(msg):
    """Log debug messages."""
    if debug_enabled:
        timestamped_msg = f"{now}: {msg}\n"
        print(timestamped_msg)
        with open(log_file, "a") as f:
            f.write(timestamped_msg)

def send_event(msg, agent=None):
    """Send an event to the Wazuh Manager."""
    try:
        if not agent or agent["id"] == "000":
            string = f'1:misp:{json.dumps(msg)}'
        else:
            string = f'1:[{agent["id"]}] ({agent["name"]}) {agent["ip"] if "ip" in agent else "any"}->misp:{json.dumps(msg)}'

        debug(f"Sending Event: {string}")
        with socket(AF_UNIX, SOCK_DGRAM) as sock:
            sock.connect(socket_addr)
            sock.send(string.encode())
    except Exception as e:
        debug(f"Error sending event: {e}")

# Read configuration parameters
try:
    alert_file = open(sys.argv[1])
    alert = json.loads(alert_file.read())
    alert_file.close()
    debug("Alert loaded successfully")
except Exception as e:
    debug(f"Error reading alert file: {e}")
    sys.exit(1)

# New Alert Output for MISP Alert or Error calling the API
alert_output = {}

# MISP Server Base URL
misp_base_url = "https://192.168.130.32/attributes/restSearch/"
# MISP Server API AUTH KEY
misp_api_auth_key = "WhbTMNNb21xdNUjGiTACvhEXdYLcxi9s0dnfprQr"
# API - HTTP Headers
misp_apicall_headers = {
    "Content-Type": "application/json",
    "Authorization": f"{misp_api_auth_key}",
    "Accept": "application/json"
}

# Extract Event Source and Type
try:
    event_source = alert["rule"]["groups"][0]
    debug(f"Event source: {event_source}")
except KeyError as e:
    debug(f"Missing expected key in alert: {e}")
    sys.exit(1)

if event_source == 'web':
    try:
        client_ip = alert["data"]["srcip"]
        debug(f"Extracted Client IP: {client_ip}")

        if ipaddress.ip_address(client_ip).is_global:
            misp_search_value = f"value:{client_ip}"
            misp_search_url = f'{misp_base_url}{misp_search_value}'
            debug(f"MISP API URL: {misp_search_url}")

            try:
                misp_api_response = requests.get(misp_search_url, headers=misp_apicall_headers, verify=False)
                misp_api_response.raise_for_status()
                debug("API request successful")
            except ConnectionError as conn_err:
                alert_output["misp"] = {"error": 'Connection Error to MISP API'}
                alert_output["integration"] = "misp"
                debug(f"ConnectionError: {conn_err}")
                send_event(alert_output, alert.get("agent"))
            except HTTPError as http_err:
                alert_output["misp"] = {"error": f'HTTP Error: {http_err}'}
                alert_output["integration"] = "misp"
                debug(f"HTTPError: {http_err}")
                send_event(alert_output, alert.get("agent"))
            except Exception as e:
                alert_output["misp"] = {"error": f'Unexpected Error: {e}'}
                alert_output["integration"] = "misp"
                debug(f"Unexpected Error: {e}")
                send_event(alert_output, alert.get("agent"))
            else:
                try:
                    misp_api_response = misp_api_response.json()
                    debug(f"API Response Data: {misp_api_response}")

                    if "Attribute" in misp_api_response["response"] and misp_api_response["response"]["Attribute"]:
                        # Generate Alert Output from MISP Response
                        attribute = misp_api_response["response"]["Attribute"][0]
                        alert_output["misp"] = {
                            "event_id": attribute["event_id"],
                            "category": attribute["category"],
                            "value": attribute["value"],
                            "type": attribute["type"]
                        }
                        alert_output["integration"] = "misp"
                        debug(f"Alert Output: {alert_output}")
                        send_event(alert_output, alert.get("agent"))
                    else:
                        alert_output["misp"] = {"error": 'No Attributes found in MISP response'}
                        alert_output["integration"] = "misp"
                        debug("No Attributes found in MISP response")
                        send_event(alert_output, alert.get("agent"))
                except Exception as e:
                    alert_output["misp"] = {"error": f"Error parsing JSON response: {e}"}
                    alert_output["integration"] = "misp"
                    debug(f"Error parsing JSON response: {e}")
                    send_event(alert_output, alert.get("agent"))
        else:
            debug(f"Client IP is not global: {client_ip}")
            sys.exit()
    except KeyError as e:
        alert_output["misp"] = {"error": f'Missing expected key: {e}'}
        alert_output["integration"] = "misp"
        debug(f"KeyError: {e}")
        send_event(alert_output, alert.get("agent"))
        sys.exit()
else:
    debug(f"Event source is not 'awswaf': {event_source}")
    sys.exit()
``` 
**custom-misp:**

```python
#!/bin/sh
WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"

DIR_NAME="$(cd $(dirname ${SCRIPT_PATH_NAME}); pwd -P)"
SCRIPT_NAME="$(basename ${SCRIPT_PATH_NAME})"

case ${DIR_NAME} in
    */active-response/bin | */wodles*)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/../..; pwd)"
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
    */bin)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

        PYTHON_SCRIPT="${WAZUH_PATH}/framework/scripts/${SCRIPT_NAME}.py"
    ;;
     */integrations)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
esac


${WAZUH_PATH}/${WPYTHON_BIN} ${PYTHON_SCRIPT} "$@"
``` 

**In ossec.conf file:**

```python
<integration>
    <name>custom-misp</name>
    <group>web</group>
    <alert_format>json</alert_format>
</integration>
``` 

And rules:

`<group name="misp,">
  
  <rule id="100620" level="10">
    <field name="integration">misp</field>
    <match>misp</match>
    <description>MISP Events</description>
    <options>no_full_log</options>
  </rule>

  
  <rule id="100621" level="0">
    <if_sid>100620</if_sid>
    <field name="misp.error">\.+</field>
    <description>MISP - Error connecting to API</description>
    <options>no_full_log</options>
    <group>misp_error,</group>
  </rule>

  
  <rule id="100622" level="12">
    <if_sid>100620</if_sid>
    <field name="misp.value">\.+</field>
    <description>MISP - IoC found in Threat Intel - IP: $(misp.value) - Category: $(misp.category), Info: $(misp.info)</description>
    <options>no_full_log</options>
    <group>misp_alert,</group>
  </rule>

  
  <rule id="100623" level="3">
    <if_sid>100620</if_sid>
    <field name="misp.error">No Attributes found in MISP response</field>
    <description>MISP - No IoC found for the given query</description>
    <options>no_full_log</options>
    <group>misp_no_result,</group>
  </rule>

  
  <rule id="100624" level="5">
    <if_sid>100620</if_sid>
    <field name="misp.category">\.+</field>
    <description>MISP - Successful IoC Query - Category: $(misp.category), IP: $(misp.value)</description>
    <options>no_full_log</options>
    <group>misp_success,</group>
  </rule>

  
  <rule id="100625" level="1">
    <if_sid>100620</if_sid>
    <field name="misp.error">Connection Error to MISP API</field>
    <description>MISP - Connection Error</description>
    <options>no_full_log</options>
    <group>misp_error,</group>
  </rule>

  
  <rule id="100626" level="5">
    <if_sid>100620</if_sid>
    <field name="misp.error">HTTP Error: .+</field>
    <description>MISP - HTTP Error</description>
    <options>no_full_log</options>
    <group>misp_error,</group>
  </rule>

  
  <rule id="100627" level="5">
    <if_sid>100620</if_sid>
    <field name="misp.error">Unexpected Error: .+</field>
    <description>MISP - Unexpected Error</description>
    <options>no_full_log</options>
    <group>misp_error,</group>
  </rule>
</group>`


What is wrong? Can you help me? @nbertoldo

**Comment by nbertoldo** [comment]
@pesquisa1234,

Please could you edit the comment as it does not read the rules well.

**Comment by pesquisa1234** [comment]
@nbertoldo Sorry, I edited, it is ok now.

**Comment by nbertoldo** [comment]
@pesquisa1234,

- Which Wazuh version do you have installed?
- Please could you check the _ossec.log_ for `integratord` messages:

```console
cat /var/ossec/logs/ossec.log | grep wazuh-integratord
```

**Comment by pesquisa1234** [comment]
- Wazuh version: 4.9
- This command does not show anything

**Comment by nbertoldo** [comment]
Hi @pesquisa1234,

You must run the command in the manager. Even if you do not have any integration configured, you will get this message:

```console
[root@wazuh-server wazuh-user]# cat /var/ossec/logs/ossec.log | grep wazuh-integratord
2024/10/09 10:48:03 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
```

**Comment by pesquisa1234** [comment]
@nbertoldo here you are, the logs:


```python
2024/10/10 18:49:07 wazuh-integratord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/10 18:49:12 wazuh-integratord: INFO: Started (pid: 203102).
2024/10/10 18:49:12 wazuh-integratord: INFO: Enabling integration for: 'custom-misp'.
```

**Comment by nbertoldo** [comment]
@pesquisa1234,

According to the messages, the integration is enabled correctly and no errors occur.
You should check the messages in the `/var/ossec/logs/integrations.log` file to see if it is running correctly and if the events are being parsed.
Note that the `custom-misp.py` script extracts the events from the `/var/ossec/logs/alerts/alerts.json` file and parses those whose group is '_web_'. So, you'll need to make sure that these types of events are being collected and sent to the manager, and in turn, are generating the corresponding alerts.

**Comment by pesquisa1234** [comment]
@nbertoldo Thank you for your help, it worked with sysmon!
