### ISSUE TITLE
Wazuh manager wazuh-modulesd OOM in 4.9.1 RC 2 stress test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#26161]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
| 4.9.1   | RC 2   | Development   | wazuh-modulesd   | Download |  

## Description

As part of the https://github.com/wazuh/wazuh/issues/26057 issue, a 4.9.1 RC 2 stress test has been launched with the following modifications

- Debug level
  - wazuh-modulesd: 1
  - wazuh-db: 2
- Core dumps are enabled based on the following documentation: https://documentation.wazuh.com/current/development/coredump.html

It has been discovered that wazuh-modulesd crashed at some point, the following trace has been obtained

1. wazuh-modulesd process is alive but not used by wazuh

```
[root@ip-172-31-8-78 centos]# /var/ossec/bin/wazuh-control stop
wazuh-clusterd not running...
wazuh-modulesd: Process 1698 not used by Wazuh, removing...
wazuh-modulesd not running...
Killing wazuh-monitord...
Killing wazuh-logcollector...
Killing wazuh-remoted...
Killing wazuh-syscheckd...
Killing wazuh-analysisd...
wazuh-maild not running...
Killing wazuh-execd...
Killing wazuh-db...
Killing wazuh-authd...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
Killing wazuh-apid...
Wazuh v4.9.1 Stopped
```

2. The api.log reports errors with codes 400 and 429

```
2024/10/06 08:01:57 INFO: wazuh ::1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.063s: 200
2024/10/06 08:02:02 INFO: wazuh ::1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.006s: 400
...
2024/10/06 08:02:04 INFO: wazuh ::1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.003s: 400
2024/10/06 08:02:04 INFO: wazuh ::1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.001s: 429
```

3. dmesg reports OOM errors related to wazuh-modulesd, no segfaults found, note that the segfault  reported is the one generated while testing the core dump configuration

```
[root@ip-172-31-8-78 centos]# dmesg | grep segfault
[  625.621582] seg[1386]: segfault at 0 ip 0000000000400546 sp 00007fff8da20ff0 error 6 in seg[400000+1000]
```

```
[216956.391686] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-1.scope,task=wazuh-modulesd,pid=1698,uid=0
[216956.394379] Out of memory: Killed process 1698 (wazuh-modulesd) total-vm:2188320kB, anon-rss:1521660kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:3440kB oom_score_adj:0
[216956.403046] oom_reaper: reaped process 1698 (wazuh-modulesd), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
[216957.981219] python3 invoked oom-killer: gfp_mask=0x6280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), order=0, oom_score_adj=0
[216957.983066] CPU: 1 PID: 465196 Comm: python3 Kdump: loaded Not tainted 4.18.0-305.3.1.el8.x86_64 #1
[216957.984586] Hardware name: Amazon EC2 c5a.large/, BIOS 1.0 10/16/2017
[216957.985683] Call Trace:
[216957.986132]  dump_stack+0x5c/0x80
[216957.986707]  dump_header+0x4a/0x1db
[216957.987361]  oom_kill_process.cold.32+0xb/0x10
[216957.988104]  out_of_memory+0x1ab/0x4a0
[216957.988697]  __alloc_pages_slowpath+0xc02/0xd20
[216957.989430]  __alloc_pages_nodemask+0x283/0x2c0
[216957.990136]  alloc_pages_vma+0x74/0x1d0
[216957.990761]  do_anonymous_page+0xe3/0x380
[216957.991428]  __handle_mm_fault+0x983/0xca0
[216957.992065]  ? __switch_to_asm+0x35/0x70
[216957.992673]  ? __switch_to_asm+0x41/0x70
[216957.993280]  handle_mm_fault+0xc2/0x1d0
[216957.993871]  __do_page_fault+0x1ed/0x4c0
[216957.994477]  do_page_fault+0x37/0x130
[216957.995045]  ? page_fault+0x8/0x30
[216957.995587]  page_fault+0x1e/0x30
[216957.996105] RIP: 0033:0x7f54d73d2731
[216957.996656] Code: Unable to access opcode bytes at RIP 0x7f54d73d2707.
[216957.997627] RSP: 002b:00007ffc59be8610 EFLAGS: 00010216
[216957.998424] RAX: 00007f541acd1010 RBX: 00007f5462961040 RCX: 0000000000000069
[216957.999541] RDX: 000000001c4c6fc0 RSI: 00007f541acd1040 RDI: 000000001c4c6fc0
[216958.000609] RBP: 0000000023e47f60 R08: 000000001c4c6fc1 R09: 0000000000000069
[216958.001685] R10: 00000000ffffff01 R11: 0000000000000049 R12: 0000000000000001
[216958.002770] R13: 00007f5437198000 R14: 00007f5437198001 R15: 00007f54dab97a88
[216958.003929] Mem-Info:
[216958.004351] active_anon:2967 inactive_anon:888177 isolated_anon:0
                 active_file:165 inactive_file:63 isolated_file:0
                 unevictable:0 dirty:0 writeback:0
                 slab_reclaimable:6661 slab_unreclaimable:9115
                 mapped:7381 shmem:18028 pagetables:4512 bounce:0
                 free:21445 free_pcp:116 free_cma:0
```

There is another OOM related to Python3 after the wazuh-modulesd one, but with less information

```
[216958.118544] Out of memory: Killed process 465196 (python3) total-vm:3130428kB, anon-rss:2679160kB, file-rss:4kB, shmem-rss:0kB, UID:0 pgtables:5524kB oom_score_adj:0
[216958.163432] oom_reaper: reaped process 465196 (python3), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch a `Test_stress` for the Vulnerability Detector Register test of 2.5d, add an input in the Jenkinsfile before starting the monitor process, and unmark the destroy instance parameter (check the linked build at the end for more information)
2. Configure core dumps in Wazuh manager
3. Enable debug mode in the Wazuh manager for wazuh-db (2) and wazuh-modulesd (1)
4. Restart the Wazuh manager instance to apply changes and start the Wazuh manager
5. Click on Proceed in the Test_stress build
6. Wait until the test finishes (expect failure when fetching log due to debug logs size) 
7. Access the Wazuh manager instance and check `dmesg` and `process` status

### Current result

The wazuh-modulesd module crashed with an `OOM` error

### Expected result

The wazuh-modulesd module should not crash with an OOM error and the Wazuh manager functionality is fine

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5630/
- Build parameters: 
  - https://ci.wazuh.info/job/Test_stress/5630/parameters/
  - Manually changed:
    - Coredumps enabled
    - wazuh-modulesd debug level set to 1
    - wazuh-db debug level set to 2
- Artifacts:
  - Not provided due to sensitive information, ask @rauldpm to provide it
- Logs:
  - Not provided due to sensitive information, ask @rauldpm to provide it

<details><summary>Wazuh manager stress test plots</summary>

![stress_Written_stats](https://github.com/user-attachments/assets/bb960741-f3ee-4f7c-8bbc-55994ae48a6a)
![stress_Write_Ops](https://github.com/user-attachments/assets/a86099e4-39b5-4006-844a-53b974275cf2)
![stress_VMS](https://github.com/user-attachments/assets/094e81cd-88ba-42d9-aa15-02d7dc203a08)
![stress_USS](https://github.com/user-attachments/assets/6490b453-e397-41e5-bd9a-3ef16022c5fb)
![stress_SWAP](https://github.com/user-attachments/assets/e42568d1-a06f-4147-b993-d331fe995990)
![stress_RSS](https://github.com/user-attachments/assets/b6c3d583-e338-439a-8880-443434eda91a)
![stress_RSS_MAXMIN](https://github.com/user-attachments/assets/9f49e40b-c92b-4482-a117-1db19a65046d)
![stress_Read_Ops](https://github.com/user-attachments/assets/5a4b534a-645a-4d40-86ca-df5519ecbe6e)
![stress_Queues_state](https://github.com/user-attachments/assets/3e70c769-d67b-45c3-9c8a-0383f23411db)
![stress_PSS](https://github.com/user-attachments/assets/5fc201ad-1d3b-4f27-b901-2917f6bed099)
![stress_Number_Events](https://github.com/user-attachments/assets/43c96530-d4c2-41d9-869e-eecdfd6c2fde)
![stress_FD](https://github.com/user-attachments/assets/62d2919f-2447-4453-924f-22df84b5117b)
![stress_EDPS](https://github.com/user-attachments/assets/f35e36a4-40d0-4d17-b1fd-4e4a90947fd7)
![stress_Dropped_events](https://github.com/user-attachments/assets/50da6371-664e-475c-b4e0-1ee5fd117991)
![stress_Disk](https://github.com/user-attachments/assets/8408b66f-a80b-43ca-872f-ecd46cc01baa)
![stress_Disk_Written](https://github.com/user-attachments/assets/ac20f048-b980-41df-a272-cb3057754728)
![stress_Disk_Read](https://github.com/user-attachments/assets/0fa1308c-5aed-42d1-9a7a-2b7e76d5f899)
![stress_Decoded_events](https://github.com/user-attachments/assets/a6a469ed-4960-49cd-b87e-91b28cadcd5b)
![stress_CPU](https://github.com/user-attachments/assets/f2f95b0e-6a5b-43c5-bc7e-b8475bd58f42)

</details>

> [!NOTE]
> Instance has been marked to not be destroyed, ask @wazuh/devel-qa team to provide access

**Comment by sebasfalcone** [comment]
## Analysis
We suspect this has to do with a re-scan that's triggered after processing an update on the feed

After taking a look at the logs, I've found that two re-scans were triggered:
```
2024/10/03 20:07:51 wazuh-modulesd:vulnerability-scanner[1696] vulnerabilityScannerFacade.cpp:444 at operator()(): INFO: Triggered a re-scan after content update.

2024/10/04 18:59:20 wazuh-modulesd:vulnerability-scanner[1696] vulnerabilityScannerFacade.cpp:444 at operator()(): INFO: Triggered a re-scan after content update.
```

The first re-scan was before the test started so no information

![image](https://github.com/user-attachments/assets/508a19a8-2dcb-4990-8074-7bcf6f1ec14c)

**Comment by sebasfalcone** [comment]
## Issue closure
Given that the issue wasn't present in RC3, and that the identified bug corresponds to the exposed behavior. I think we can conclude this issue

**Comment by Dwordcito** [comment]
LGTM
