### ISSUE TITLE
Vulnerability scanner: concurrent access to OS scan column family throws an error 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#26212]
## Description

These errors were reported a few times by the users:

```
2024/10/04 23:08:49 wazuh-modulesd:vulnerability-scanner[132706] scanOrchestrator.hpp:153 at operator()(): ERROR: Error processing delayed event: Error deleting data: Invalid argument: Invalid column family specified in write batch

2024/10/04 23:08:49 wazuh-modulesd:vulnerability-scanner[132706] scanAgentList.hpp:253 at handleRequest(): ERROR: Error handling request: Error putting data: Invalid argument: Invalid column family specified in write batch
```

- https://github.com/wazuh/wazuh/issues/25804
- https://github.com/wazuh/wazuh/issues/24410

In the second issue, we find logs with more details

```
2024/07/04 14:37:34 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing delayed event: Error deleting data: Invalid argument: Invalid column family specified in write batch

2024/07/04 14:37:34 wazuh-modulesd:vulnerability-scanner: ERROR: Error processing delayed event: Couldn't find column family: 'os_initial_scan'
```
An analysis of the source code reveals that we have two threads working at the same time over the same `m_inventoryDatabase`
- `m_eventDelayedDispatcher`
- `m_eventDispatcher`

Some orchestrations perform read/write operations over the `OS_INITIAL_SCAN` column family

https://github.com/wazuh/wazuh/blob/2617f9fa1ee88c21c90221bfd7beaf41d9b1618a/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cleanAgentInventory.hpp#L122

https://github.com/wazuh/wazuh/blob/2617f9fa1ee88c21c90221bfd7beaf41d9b1618a/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/scanInventorySync.hpp#L137-L145

But some other drop and a create the whole column

https://github.com/wazuh/wazuh/blob/2617f9fa1ee88c21c90221bfd7beaf41d9b1618a/src/wazuh_modules/vulnerability_scanner/src/scanOrchestrator/cleanInventory.hpp#L94

https://github.com/wazuh/wazuh/blob/2617f9fa1ee88c21c90221bfd7beaf41d9b1618a/src/shared_modules/utils/rocksDBWrapper.hpp#L538-L544

This could lead to a transaction with a reference to a column handler that no longer exists
https://github.com/facebook/rocksdb/issues/7268#issuecomment-675063647

Some possible approaches:
- Change the vulnerability scanner code to simple delete all elements from the column instead of dropping it
- Update the Rocks DB wrapper to make sure no transaction references dangling handlers before dropping a column

## How to reproduce

This simple UT reproduces the error message

```c++
TEST_F(RocksDBWrapperTest, MultiThreadTest)
{

    constexpr auto COLUMN_NAME_A {"column_A"};
    constexpr auto KEY_A {"key_A"};
    constexpr auto VALUE_A {"value_A"};

    db_wrapper->createColumn(COLUMN_NAME_A);

    std::thread t1(
        [&]()
        {
            for (int i = 0; i < 1000; i++)
            {
                std::cout << "Thread 1: " << i << std::endl;
                std::string value;
                if (db_wrapper->get(KEY_A, value, COLUMN_NAME_A))
                {
                    db_wrapper->delete_(KEY_A, COLUMN_NAME_A);
                }
                else
                {
                    db_wrapper->put(KEY_A, VALUE_A, COLUMN_NAME_A);
                }
            }
        });

    std::thread t2(
        [&]()
        {
            for (int i = 0; i < 1000; i++)
            {
                std::cout << "Thread 2: " << i << std::endl;
                db_wrapper->deleteAll(COLUMN_NAME_A);
            }
        });

    t1.join();
    t2.join();
}
```

```
[ RUN      ] RocksDBWrapperTest.MultiThreadTest
Thread 1: 0
Thread 2: 0
Thread 1: 1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error deleting data: Invalid argument: Invalid column family specified in write batch
Aborted (core dumped)
```

## DoD

- [ ] Reproduce the issue over the scanner code
- [x] Propose a fix, validate it and discuss with the team
- [x] Add tests
- [x] CI pass

**Comment by GabrielEValenzuela** [comment]
# Update

- Make a benchmark based on team discussion and make the fix proposal

**Comment by sebasfalcone** [comment]
## ETA update
Due to definition changes

**Comment by GabrielEValenzuela** [comment]
# Update

- Implement new changes and make new benchmarks to validate them

**Comment by GabrielEValenzuela** [comment]
# Update

- Finish E2E

**Comment by GabrielEValenzuela** [comment]
# Update

- I made today an analysis with `heaptrack` and now I recently implemented the new proposal of the revision using a fixed batch to make the deletion. I need to validate with testing and agree if the right size of the batch

**Comment by sebasfalcone** [comment]
## ETA update
To address memory consumption issues we are going to make some changes to the implementation

- Implementation ETA -> 25/10
- Review ETA -> 29/10

**Comment by GabrielEValenzuela** [comment]
# Update

- Validate new approach and compare with another alternative

**Comment by GabrielEValenzuela** [comment]
# Update

- Implement changes based on review comments
