### ISSUE TITLE
Vulnerability-detector | DEBUG: Unable to initialize IndexerConnector : No available server.

### ISSUE THREAD

**Issue by daniel-tedra** [wazuh/wazuh#26224]
AIO machine. 
Upgraded from 4.7.2 to 4.8.0, from 4.8.0 to 4.9.0

Vulnerability-detection is still broken, no error nor data is shown in its dashboard section.

**indexer-connector[7387] indexerConnector.cpp:474 at operator()(): DEBUG: Unable to initialize IndexerConnector for index 'wazuh-states-vulnerabilities-wazuh': No available server. Retrying in 60 seconds.**

What I see is it did create the index "wazuh-states-vulnerabilities-wazuh"

Filebeat config validated

```
# filebeat test output
elasticsearch: https://127.0.0.1:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 127.0.0.1
    dial up... OK
  TLS...
    security: server's certificate chain verification is enabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.2
```

/var/ossec/etc/ossec.conf

```
 <vulnerability-detection>
   <enabled>yes</enabled>
   <index-status>yes</index-status>
   <feed-update-interval>60m</feed-update-interval>
</vulnerability-detection>

<indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://127.0.0.1:9200</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/filebeat/certs/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
      <key>/etc/filebeat/certs/filebeat-key.pem</key>
    </ssl>
  </indexer>


```

CURL to indexer 
same certificates that are on ossec.conf and filebeat.yml
same ip that is in filebeat.yml and ossec.conf
same user/pw that is in keystore and filebeat.yml

```
curl -u admin:MYPASSWORD --cacert /etc/filebeat/certs/root-ca.pem --cert /etc/filebeat/certs/filebeat.pem --key /etc/filebeat/certs/filebeat-key.pem -X GET "https://127.0.0.1:9200/_cluster/health?pretty"
{
  "cluster_name" : "wazuh",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "discovered_master" : true,
  "discovered_cluster_manager" : true,
  "active_primary_shards" : 1652,
  "active_shards" : 1652,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 164,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 90.96916299559471

```

I can't further debug it with your log verbosity.

**Comment by sebasfalcone** [comment]
Hi @daniel-tedra, how are you doing?

The indexerConnector module requires the cluster status to be green, yours is in yellow. This can be due to multiple factor

Please run this request to the indexer to check the status: 
- `curl -u admin:MYPASSWORD --cacert /etc/filebeat/certs/root-ca.pem --cert /etc/filebeat/certs/filebeat.pem --key /etc/filebeat/certs/filebeat-key.pem -X GET "https://127.0.0.1:9200/_cluster/allocation/explain"
`

> [!NOTE]
> Its most probably due to having more than 0 replicas (but lets validate it with the above command)

**Comment by daniel-tedra** [comment]
Why does the indexerConnector needs green to work? I´ve yellow status because I  migrated some indexes from a cluster to my AIO, and didn't change the replicas to 0 yet, older versión of vulnerability-detector worked, and it should as long as its index is green¿?

**Comment by sebasfalcone** [comment]
@daniel-tedra The Vulnerability Detection module only indexes if the cluster is in a green state, that was a decision taken by management when we refactored the module

This decision was changed in 4.9.1. From that point onward the indexing will work even if the cluster is in a yellow state:
- https://github.com/wazuh/wazuh/issues/25416
