### ISSUE TITLE
Support multiple CA files in Indexer Connector configuration

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#26233]
### Description:
The configuration for the indexer connector allows the user to define multiple CA (certificate authorities) files for connecting to the indexer:

```xml
<certificate_authorities>
  <ca>/etc/pki/tls/private/private-ca-chain.pem</ca>
</certificate_authorities>
```

A PR has already been implemented to enhance the handling of multiple CA files. The solution consolidates multiple CA entries from the configuration into a single CA bundle file. This change streamlines the process, making it simpler to manage multiple CAs while improving error messaging to enhance usability.

We need to move forward with the changes made in

- https://github.com/wazuh/wazuh/pull/24620

And integrate them into the latest development branch `(master)` to complete the full support for multiple CA files in the indexer connector configuration.

**Comment by GabrielEValenzuela** [comment]
# Update

- I made the development according to the previous work. Awaiting review

**Comment by GabrielEValenzuela** [comment]
# Update

- Research about how mock syscall

**Comment by GabrielEValenzuela** [comment]
# Update

- Implement mocking and review improvements

**Comment by sebasfalcone** [comment]
## Updated ETA
ETA updated to accommodate for the final review

**Comment by GabrielEValenzuela** [comment]
# Update

- Implement changes requested on directories and log debug

**Comment by GabrielEValenzuela** [comment]
# Update

- Fix path

**Comment by Dwordcito** [comment]
Delayed 1 day because the final reviewer
