### ISSUE TITLE
Error found un wazuh-api `'coroutine' object is not callable`

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#26231]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc3 | Master | Manager/Agent | Packages/Sources | debian10 |

# Description
During the tests of: https://github.com/wazuh/wazuh/issues/26172, a significant decreas of `wazuh-apid` in **FD**, **PSS**, **Read_Ops**, **RSS**, **USS**, **VMS**, **Write_Ops** , from **Master**, **Worker1** and **Worker2** has been detected. 

Error found:

```
./master/logs/api.log: 2024/10/07 14:33:05 ERROR: Exception in ASGI application
./master/logs/api.log: | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
./master/logs/api.log: |   File "/var/ossec/framework/python/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
./master/logs/api.log: |     raise RuntimeError("No response returned.")
./master/logs/api.log: TypeError: 'coroutine' object is not callable
```

Full logs (it is a tgz file):
[artifacts.tgz.txt](https://github.com/user-attachments/files/17300149/artifacts.tgz.txt)

**Comment by fdalmaup** [comment]
This error has already been reported and analyzed at https://github.com/wazuh/wazuh/issues/26117. It is being taken care of at:
- https://github.com/wazuh/wazuh/issues/26140
