### ISSUE TITLE
Significant decrease of `wazuh-apid`

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#26230]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.1-rc3 | Master|Workers | Manager/Agent | Packages/Sources | debian10 |

# Description
During the tests of: https://github.com/wazuh/wazuh/issues/26172, a significant decreas of `wazuh-apid` in **FD**, **PSS**, **Read_Ops**, **RSS**, **USS**, **VMS**, **Write_Ops** , from **Master**, **Worker1** and **Worker2** has been detected. 

## 4.9.1-rc2
- Master:

![FD](https://github.com/user-attachments/assets/fc7a95bc-184c-4506-bd8b-68ce23f3e7cc)
![PSS](https://github.com/user-attachments/assets/c1aba67d-69f5-48f7-a3ec-82dc63ac4f86)
![RSS](https://github.com/user-attachments/assets/636aca31-0c24-4a56-9434-4a2d70abca53)
![USS](https://github.com/user-attachments/assets/4b140450-8147-4f45-978e-a8e39596333c)
![VMS](https://github.com/user-attachments/assets/b28802b5-879f-40c1-95c4-4554a25133cf)
![Write_Ops](https://github.com/user-attachments/assets/dc57f4e3-5cae-47dd-ad2d-0d50737f622c)

- Workers:

![FD](https://github.com/user-attachments/assets/1cf2187f-9eb1-485d-9444-d392506f901c)
![PSS](https://github.com/user-attachments/assets/273527ab-0ef6-4aa4-a3ae-43c6d7cf38d6)
![RSS](https://github.com/user-attachments/assets/0d954da8-acb4-4959-a271-1a37728edb23)
![USS](https://github.com/user-attachments/assets/9d11199c-074b-47fd-994c-e5f3b184e5be)
![VMS](https://github.com/user-attachments/assets/2e71f679-03bc-4fea-bc07-99bf999f3517)
![Write_Ops](https://github.com/user-attachments/assets/37b6231e-1a6d-4b4d-93bb-708fdf7929f8)

## 4.9.1-rc3

- Master

![FD](https://github.com/user-attachments/assets/7225d57b-548b-47a6-a4d7-014f99ce5d9a)
![PSS](https://github.com/user-attachments/assets/659fdd52-269f-4ee5-a2ca-f2000ae82ead)
![RSS](https://github.com/user-attachments/assets/371e1061-0e3f-41ba-97d5-ca90f0749048)
![USS](https://github.com/user-attachments/assets/4246a718-7b67-4056-9dab-7a79e29b7ca3)
![VMS](https://github.com/user-attachments/assets/03d87ec3-ae33-44d6-8e81-5b1d005f959a)
![Write_Ops](https://github.com/user-attachments/assets/91f1663a-c59b-411b-8685-73334650714a)

- Workers:

![FD](https://github.com/user-attachments/assets/71d4808a-3be0-441e-b2c9-2b9a95c17231)
![PSS](https://github.com/user-attachments/assets/272de461-64ec-4201-b126-a496dfa020d6)
![RSS](https://github.com/user-attachments/assets/e9253a83-a4c3-498c-aab9-98e368495d12)
![USS](https://github.com/user-attachments/assets/da13962f-ad4b-4729-b358-58f3e4f1e313)
![VMS](https://github.com/user-attachments/assets/ef32afe5-67d7-4768-8798-23a92da18fa1)
![Write_Ops](https://github.com/user-attachments/assets/9f67c552-aac0-481e-989d-c003102ac53f)

**Comment by fdalmaup** [comment]
The values are similar to those from `v4.8.1-rc2` (https://github.com/wazuh/wazuh/issues/24504#issuecomment-2220977623). The increase in `4.9.x` was investigated at https://github.com/wazuh/wazuh/issues/25420.
