### ISSUE TITLE
Rename "cluster" references to "server"

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#26248]
|Objective|
|---|
| #22888 |

## Description

What we currently call "cluster" in our source code is, in reality, the logic that each one of the server nodes run. 

A cluster is an abstract concept that refers to a number of computers networked together in order to function as a single computing system.

From 5.0 onwards, `wazuh-clusterd` will be renamed to `wazuh-server` and we should update the framework and APIs code to reflect this.

## Plan

- [ ] Rename `wazuh-clusterd` to `wazuh-server`
- [ ] Rename `cluster.json` to `server.json`.
- [ ] Move `wazuh/framework/core/cluster` to `wazuh/framework/core/server`

> [!Warning]
> Do NOT rename `/cluster` endpoints.

**Comment by javiersanchz** [comment]
## Update

For now, this issue will be locked until all the legacy removal work from https://github.com/wazuh/wazuh/issues/25554 is completed, as many cluster components have already been removed

**Comment by fdalmaup** [comment]
Due to the upcoming modifications to be carried out in #27434, we are closing this issue and the references will be removed in said issue.
