### ISSUE TITLE
Footprint - `wazuh-analysisd` unexpected warning in manager

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26243]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.1-RC 3  |  1  |  Development  |  wazuh-analysisd  | - |  

## Description

While analyzing manager logs in https://github.com/wazuh/wazuh/issues/26175, an unexpected log has been detected. Further investigation is required.

### Environment

Test_stress environment. A centOS manager and three agents (centOS, Ubuntu and Windows) subjected to a 2.5-day stress test with all modules activated except the ACTIVE-RESPONSE module.

### Current result

The log obtained is:

```
2024/10/04 18:32:50 wazuh-analysisd: WARNING: (1210): Queue 'queue/alerts/cfgarq' not accessible: 'Connection refused'
```

### Expected result

The log mentioned above should not appear.

### Steps to reproduce

The test is automated. The steps it follows are:

1. Deploy a Wazuh Manager (CentOS) and three agents (CentOS, Ubuntu, Windows)
2. Configure the manager
3. Configure the agents and register agents to the manager.
4. Launch the monitor and wait to monitor first values
5. Launch stress tests and wait until they are finished
6. Fetch CSVs and logs

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5648/

- Logs: [ossec_Test_stress_B5648_manager_2024-10-07.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.1/B5648-3600m/B5648_manager_centos/logs/ossec_Test_stress_B5648_manager_2024-10-07.zip)

**Comment by JcabreraC** [comment]
After analyzing the logs, we found that this warning message appears only once, right when the manager restarts to begin the tests:
```yml
2024/10/04 18:32:45 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
2024/10/04 18:32:50 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. 
Exit Cleaning...
2024/10/04 18:32:50 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:50 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:50 wazuh-analysisd: WARNING: (1210): Queue 'queue/alerts/cfgarq' not accessible: 'Connection refused'
2024/10/04 18:32:50 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/10/04 18:32:50 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:50 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:50 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/10/04 18:32:50 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:50 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:51 wazuh-db: INFO: Graceful process shutdown.
2024/10/04 18:32:51 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/10/04 18:32:52 wazuh-authd: INFO: Exiting...
```

n the logs, it's evident that before the warning message appears, `wazuh-remoted` shuts down. This module is responsible for handling the queue, as shown in this code snippet: [cfga-forward.c](https://github.com/wazuh/wazuh/blob/194796ea9fad3714423200e917ed172b980abd97/src/remoted/cfga-forward.c#L28-L31).

As a result, the warning message about the queue being inaccessible is expected and does not indicate an issue—it occurs because `wazuh-remoted` is no longer active at that moment.

**Comment by Dwordcito** [comment]
LGTM, not a bug based on the comment https://github.com/wazuh/wazuh/issues/26243#issuecomment-2402594940
