### ISSUE TITLE
The Modulesd process was found duplicated at certain times during the stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26242]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  v4.9.1-rc3  |  1  |  Development  |  modulesd  | Packages |  

## Description

Testing [Release 4.9.1 - RC 3 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/26184) monitor.py (which is a script that analyzes the processes during the stress test) has shown that the modulesd process duplicates itself at times.

We need to:

Evaluate whether this is expected
If not expected, make the required corrections

### Environment

Test_stress environment

### Steps to reproduce

1. Deploy a Wazuh manager and a Wazuh agent
3. Connect them
4. Start them
5. Run the provided code and monitor the Wazuh processes
6. Check the script output

### Current result

A duplicated and temporal wazuh-modulesd appears with a hight PID value

### Expected result

Validate if that temporal wazuh-modulesd process is acceptable and why it is appearing

### Attachments

```
import psutil
from signal import signal, SIGINT
from time import sleep, time
import sys

iteration=0
wazuh_binaries = {
    "manager": set(["wazuh-analysisd", "wazuh-authd", "wazuh-execd",
                    "wazuh-integratord", "wazuh-logcollector", "wazuh-maild",
                    "wazuh-monitord", "wazuh-syscheckd", "wazuh-remoted",
                    "wazuh-modulesd", "wazuh-clusterd", "wazuh-db", ]),
    "agent": set(["wazuh-agentd", "wazuh-execd", "wazuh-logcollector",
              "wazuh-syscheckd", "wazuh-modulesd", ]),
    "winagent": set(["wazuh-agent.exe", ])
}

while True:
  try:
    print(f"Iteration: {iteration}")
  
    dead_processes = set(wazuh_binaries['agent'])
    running_processes = [psutil.Process(x.pid) for x in filter(lambda x: x.name() in wazuh_binaries['agent'], psutil.process_iter())]
    print(f"Running processes: {running_processes}")
    for process in running_processes:
      if process.is_running():
        print(f"Removing: {process.name()} - {process.pid}")
        dead_processes.remove(process.name())
    print(f"Running processes after removal: {running_processes}")
  except KeyError as e:
      print("Error getting something from a dict")
      print(e)
  finally:
    sleep(1)
    iteration+=1
    print()
    sys.stdout.flush()
```

Log: [custom_monitor.log](https://github.com/user-attachments/files/17299457/custom_monitor.log)

Some additional tests and comments were done: https://github.com/wazuh/wazuh-jenkins/issues/7018#issuecomment-2402022693
The same issue was not be able to replicate by using OVA in localhost https://github.com/wazuh/wazuh-jenkins/issues/7018#issuecomment-2401841098

**Comment by vikman90** [comment]
## False alarm

### How to reproduce

```shell
while true; do 
    ps aux | grep wazuh-modulesd | grep -v grep
    echo
    sleep 0.1
done
```

> root      652441  3.1  2.1 473484 81748 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> 
> root      652441  3.1  2.1 473484 81764 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> 
> root      652441  3.1  2.1 473484 81580 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> 
> root      652441  3.1  2.1 473484 81576 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> 
> root      652441  3.1  2.1 473484 81576 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> root      656627  0.0  0.0      4     4 ?        RNs  15:12   0:00 [wazuh-modulesd]
> 
> root      652441  3.1  2.1 473484 81572 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> root      656649  0.0  0.0      4     4 ?        RNs  15:12   0:00 [wazuh-modulesd]
> 
> root      652441  3.1  2.1 473484 81576 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd
> root      656687  0.0  1.2 473484 48736 ?        RNs  15:12   0:00 /var/ossec/bin/wazuh-modulesd
> 
> root      652441  3.1  2.1 473484 81580 ?        Sl   15:11   0:02 /var/ossec/bin/wazuh-modulesd

The extra line that we see sporadically:
> root      656649  0.0  0.0      4     4 ?        RNs  15:12   0:00 [wazuh-modulesd]

It corresponds to the **newly forked process**.

However, this only happens when the **SCA configuration is stressed**.

If we disable SCA, we stop observing this phenomenon.

### Rationale

The SCA module (inside the wazuh-modulesd process), among others, runs subprocesses. The way to do this on UNIX systems is:
- Clone the process with fork
- Change the process image with exec
In the time between both calls, we would have two "wazuh-modulesd" processes. The life of one of them will last an instant, probably in the order of microseconds.

### Conclusion

This does not represent a bug.
