### ISSUE TITLE
 Privilege Escalation Issue: Custom User Gains Full Admin Access After Admin Session

### ISSUE THREAD

**Issue by joseraeiro** [wazuh/wazuh#26269]
## Description
I encountered a potential **privilege escalation vulnerability** in Wazuh's web interface. A custom user with limited permissions (to manage and read documents for a specific group of agents) gains **full admin access** after using an admin session. Clearing the browser cache temporarily resolves the issue, but it seems to be session-related and reproducible across different browsers.

**Confirmation from Wazuh:**
The issue was confirmed by **Cédrick Foko** from the Wazuh team. It was replicated in their lab. While the user doesn't get full admin access, they do gain admin access to the **manager**, allowing them to access the security configuration in the server management but not in the index management tab, and also access to all agents(not just the ones on Team_A, as expected), including the possibility of obtaining the command for agent installation. 

For now, the suggested workaround is to clear the browser cache and cookies after logging out from the admin session. Using Incognito mode does not circumvent the issue (tested in Chrome).

## Steps to Reproduce
1. **Environment Setup**:
   - Created agent groups (e.g., Team_A).
   - Added a label to the group’s centralized configuration (`agent.conf`) to identify Wazuh alerts coming from this group.

2. **User Creation**:
   - Created an internal user via **Indexer management > Security > Internal users**.
   - Created a custom role via **Security > Roles** with permissions to read and manage documents for the specific group.
   - Granted cluster-level read permissions and document-level security for `wazuh-alerts*` and `wazuh-monitoring*` indices.

3. **Mapping**:
   - Mapped the custom role to the user, allowing read and manage permissions over the group of agents.

4. **Policy Creation**:
   - Created a custom policy to grant the necessary actions (e.g., `agent:read` for the group) and mapped it to the user.

5. **Issue**:
   - The custom user intermittently gains full admin access when switching sessions after using an admin session.
   - Switching to a different browser restores correct limited access, but clearing the cache resolves the issue temporarily.

## Expected Behavior
The custom user should have **only** the permissions assigned (read/manage for a specific group of agents) and should **not** have admin access.

## Wazuh Version
- App version: 4.9.0
- App revision: 07

## Additional Context
This issue occurs across multiple browsers (tried incognito/private mode as well). It looks like a session handling bug, possibly allowing permission contamination.

## Severity
High (Potential privilege escalation vulnerability).

**Comment by OndrejSerek** [comment]
Also happening for me on version 4.8.0. Also having priviliges for all agents.

**Comment by gdiazlo** [comment]
Thanks for reporting this. This was already notified as a possible security advisory. It is fixed in https://github.com/wazuh/wazuh-dashboard-plugins/pull/6995

To report any security issue, please review the security policy in the repository you're trying to open the issue https://github.com/wazuh/wazuh/blob/master/README.md
It is also linked in the left pane of the repository:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/9f06138d-f7a2-4077-a141-7836f61864b3">

The tl;dr is to use the Security tab in the repository.
