### ISSUE TITLE
Footprint: High decrease of fluctuations of events buffered in Windows Agent in Syscollector stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26274]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|   v4.9.1-rc3  |    1 |  Development  |  Windows Agent  | Assistant |  

## Description

During the analysis of the test: https://github.com/wazuh/wazuh/issues/26167, it has been detected a high decrease of fluctuations of number of events buffered, it was expected that the number of events would decrease because in 4.9.0, the load was reduced for syscollector, but too few events are being generated for 4.9.1-rc3. A deeper investigation is needed to explain this behavior.

### Environment

Stress test infrastructure

### Steps to reproduce

1. Move to https://ci.wazuh.info/job/Test_stress/

2. Run a stress test with the following parameters:
![image](https://github.com/user-attachments/assets/676ca779-0f68-417a-b07d-ab9ae57b6588)
![image](https://github.com/user-attachments/assets/b81ddd5f-8369-4f25-b6e4-4d07163d3a11)
![image](https://github.com/user-attachments/assets/d691847c-fb0d-4e67-9c6f-846d8d5bcc3e)
![image](https://github.com/user-attachments/assets/1aaa18c1-c863-45f7-98f1-c1905bdcaafb)

### Current result

4.9.1-rc3 plot:
![image](https://github.com/user-attachments/assets/c9f7c17e-203b-4d6f-81fc-7ed6aca9df8e)

### Expected result

More peaks of buffered events as in:
4.9.1-rc2 plot:
![4 9 1-rc2](https://github.com/user-attachments/assets/09f2a41a-1cc5-4d03-a432-4ca9afd9dadf)

- Build link: https://ci.wazuh.info/job/Test_stress/5637/

- Build parameters: https://ci.wazuh.info/job/Test_stress_tier/188/parameters

- Artifacts: 
[B5637_agent_windows.zip](https://github.com/user-attachments/files/17309276/B5637_agent_windows.zip)

- Logs: 
[ossec_Test_stress_B5637_windows_2024-10-07.zip](https://github.com/user-attachments/files/17309283/ossec_Test_stress_B5637_windows_2024-10-07.zip)

**Comment by vikman90** [comment]
In 4.9.1-RC2 there were 14 spikes of 1 queued event, while in 4.9.1-RC3 there was a one-time spike of 9 queued events, and 7 spikes of 1 event.

This is an effect that depends on the exact instant at which the snapshot is taken. Having several spikes of value 1 shows that the buffer is cleared.

Also, there are no changes in the agent logic between RC 2 and RC 3.

We can close this issue.
