### ISSUE TITLE
Enable linux kernel detection in Ubuntu platforms

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26292]
## Description
This issue is created under the request of the community https://wazuh.slack.com/archives/C07CCCCGHHP/p1728722270154219

Basically we need a translation to match between "linux" (how ubuntu reports the package name for vulnerabilities) and the collected kernel package name software. Ex "linux-image-6.8.0-45-generic"

proposal:
```json
{
  "target": [
    "ubuntu"
  ],
  "source": {
    "vendor": "^Ubuntu Kernel Team$",
    "product": "^linux-image-.*-generic$",
    "version": ""
  },
  "translation": [
    {
      "vendor": "Ubuntu Kernel Team",
      "product": "linux"
    }
  ],
  "action": [
    "replace_vendor"
  ]
}
```

**Comment by GabrielEValenzuela** [comment]
# Update

- Work in progress

**Comment by GabrielEValenzuela** [comment]
# Update

- Task complete. Await for review.

**Comment by GabrielEValenzuela** [comment]
# Update

- I ran the test but the update on the database snapshot is not available yet

**Comment by sebasfalcone** [comment]
## ETA update
Awaiting for translation to impact the generated databases
