### ISSUE TITLE
UI: "Add filter" button not visible if many filters are applied

### ISSUE THREAD

**Issue by apertureless** [wazuh/wazuh#26296]
![image](https://github.com/user-attachments/assets/6e3b2a16-1b19-49e3-a8c7-0183e8d13854)

The div containing the filters does not grow properly. And if you have too many filters active, it hides the "+ Add filter" button. So you are unable to add any more filters.

**Comment by guidomodarelli** [comment]
Hello @apertureless, thank you for bringing the issue to our attention.

The issue has been resolved in [this pull request](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7077).

Should you have any questions, please feel free to ask.
