### ISSUE TITLE
wazuh-logtest inconsistant with analysisd when using FIM field names

### ISSUE THREAD

**Issue by landon-lengyel** [wazuh/wazuh#26327]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-2 | wazuh-logtest | Manager | Packages | Debian 12 |

According to [this documentation](https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/creating-custom-fim-rules.html#mapping-fim-fields-to-wazuh-alerts) the FIM rules should match the value in the "**FIM Field**" column. `wazuh-analysisd` (alerts that appear in the WUI) do follow that, however the `wazuh-logtest` utility says the rule _wouldn't_ be caught. If you're new to Wawzuh and don't realize this, you may instead use the field names as it appears in the alert in your rule name. In which case the test tool will tell you that it will be caught, but the alert will never work properly with `wazuh-analysisd`.

Adding to the confusion, the option `<if_sid>550</if_sid>` must appear for `wazuh-analysisd` to work, but must not appear for `wazuh-logtest` to think it will work.

This makes for an extremely frustrating troubleshooting experience if you don't happen to know that `wazuh-analysisd` doesn't see the same data that is stored in the alert. Below is an example to test with:

Raw log (a few fields altered to remove identifying information): 
```json
{"timestamp":"2024-10-14T13:42:59.160-0600","rule":{"level":7,"description":"Integrity checksum changed.","id":"550","mitre":{"id":["T1565.001"],"tactic":["Impact"],"technique":["Stored Data Manipulation"]},"firedtimes":1,"mail":false,"groups":["ossec","syscheck","syscheck_entry_modified","syscheck_file"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"],"tsc":["PI1.4","PI1.5","CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"008","name":"MyAgent","ip":"1.1.1.1"},"manager":{"name":"wazuhserver"},"id":"1728934979.157906674","full_log":"File 'c:\\program files\\zabbix agent 2\\zabbix_agent2.conf' modified\nMode: whodata\nChanged attributes: size,mtime,md5,sha1,sha256\nSize changed from '16978' to '16979'\nOld modification time was: '1728933157', now it is '1728934978'\nOld md5sum was: 'db81ef9d58bfcc9bf20bfd6a41ad3a71'\nNew md5sum is : '5bd9be2735dfa58d00d388257b0c25a1'\nOld sha1sum was: 'dc73be9eb9d1c4b0e4a9fc60edef499a28d39c8a'\nNew sha1sum is : 'bac2513452a685d869d9bb1b6431626d822e59bb'\nOld sha256sum was: 'd2ae7381046691869e29eafbb6e7e1fdcb2dde613f8d9d65beb421c63248ed84'\nNew sha256sum is : 'c6ad7107f62256cd012e7bb9a4ab90d9e67bac1a589a6ffb475a06f2c058d4f0'\n","syscheck":{"path":"c:\\program files\\zabbix agent 2\\zabbix_agent2.conf","mode":"whodata","size_before":"16978","size_after":"16979","win_perm_after":[{"name":"SYSTEM","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","READ_DATA","WRITE_DATA","APPEND_DATA","READ_EA","WRITE_EA","EXECUTE","READ_ATTRIBUTES","WRITE_ATTRIBUTES"]},{"name":"Administrators","allowed":["DELETE","READ_CONTROL","WRITE_DAC","WRITE_OWNER","SYNCHRONIZE","READ_DATA","WRITE_DATA","APPEND_DATA","READ_EA","WRITE_EA","EXECUTE","READ_ATTRIBUTES","WRITE_ATTRIBUTES"]},{"name":"Users","allowed":["READ_CONTROL","SYNCHRONIZE","READ_DATA","READ_EA","EXECUTE","READ_ATTRIBUTES"]},{"name":"ALL APPLICATION PACKAGES","allowed":["READ_CONTROL","SYNCHRONIZE","READ_DATA","READ_EA","EXECUTE","READ_ATTRIBUTES"]},{"name":"ALL RESTRICTED APPLICATION PACKAGES","allowed":["READ_CONTROL","SYNCHRONIZE","READ_DATA","READ_EA","EXECUTE","READ_ATTRIBUTES"]}],"uid_after":"S-1-5-18","md5_before":"db81ef9d58bfcc9bf20bfd6a41ad3a71","md5_after":"5bd9be2735dfa58d00d388257b0c25a1","sha1_before":"dc73be9eb9d1c4b0e4a9fc60edef499a28d39c8a","sha1_after":"bac2513452a685d869d9bb1b6431626d822e59bb","sha256_before":"d2ae7381046691869e29eafbb6e7e1fdcb2dde613f8d9d65beb421c63248ed84","sha256_after":"c6ad7107f62256cd012e7bb9a4ab90d9e67bac1a589a6ffb475a06f2c058d4f0","attrs_after":["ARCHIVE"],"uname_after":"SYSTEM","mtime_before":"2024-10-14T13:12:37","mtime_after":"2024-10-14T13:42:58","diff":"< # HELLO\n< # --- This config file was generated programatically by a script ---\n---\n> # 1:42PM\n> # --- This config file was generated programatically by a script ---\n","changed_attributes":["size","mtime","md5","sha1","sha256"],"event":"modified","audit":{"user":{"id":"S-1-5-21-3071002778-2177150733-3146294172-289265","name":"MyUsername"},"process":{"id":"2236","name":"C:\\Windows\\System32\\notepad.exe"}}},"decoder":{"name":"syscheck_integrity_changed"},"location":"syscheck"}
```

Rule that works with `wazuh-logtest`:
```xml
<group name="falsepositives,">
    <rule id="100007" level="3">
      <field name="syscheck.path">c:\\program files\\zabbix agent 2\\zabbix_agent2.conf</field>
      <field name="syscheck.audit.user.name">MyUsername</field>
      <description>Custom - MyUsername updating Zabbix</description>
  </rule>
</group>
```

Rule that actually works in `wazuh-analysisd` when the file is altered, but fails in `wazuh-logtest`:
```xml
<group name="falsepositives,">
  <rule id="100007" level="3">
    <if_sid>550</if_sid>
    <field name="file">c:\\program files\\zabbix agent 2\\zabbix_agent2.conf</field>
    <field name="user_name">MyUsername</field>
    <description>Custom - MyUsername updating Zabbix</description>
  </rule>
</group>
```

**PS**: If anyone can give advice on how to log/record the raw data that `wazuh-analysisd` is seeing from decoders to know the field names for debugging purposes, please let me know. It would be very appreciated.

**Comment by landon-lengyel** [comment]
In case it wasn't clear, this is a Windows client. Windows Server 2022 to be exact, if it makes a difference.

**Comment by juliancnn** [comment]
Hi @landon-lengyel,

Currently, wazuh-logtest is only prepared to test syslog events, i.e. those events that are decoded with xml decoders. Other events, such as windows event channel or FIM, are decoded by decoders written in C. We know that this is a big limitation, not only for testing, but also for understanding the data flow. This problem, together with the normalization of events, data types and the problems with the wazuh-analisysd predecoder have led us to make a replacement of wazuh-analisysd. We are currently developing wazuh-engine, a new engine that will have a much more powerful and transparent decoding tree, written in YAML, with the possibility of analyzing what happens at each step of the decoding process, allowing data typing, field renaming and even operations between fields. You can see more about it here https://github.com/wazuh/wazuh/issues/23577

Regards

**Comment by juliancnn** [comment]
Hi @landon-lengyel,

I will leave this issue open and mark it as a feature request, so we can evaluate it. I also think we should make it clear in the documentation. The good thing is that this kind of problem is already solved in 5.x.

Regards
