### ISSUE TITLE
Modify wazuh-engine packages builder to include a `store` with basic  ruleset

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#26325]
## Description:

With the recent implementation of DEB and RPM package builds for Wazuh-Engine (https://github.com/wazuh/wazuh/issues/25790), it's crucial to modify these packages for a MVP. The modification involves integrating a basic store, which has been previously developed, into the packages. This store will include a basic ruleset, similar to the one found in branch 1.2.0 + a indexer-connector output. The store will be compressed and uploaded to `S3`,and during the building of the package it will be downloaded. During installation, this store will be decompressed into the necessary store directory.

## Tasks:

1. **Create a basic store**: Create locally a basic store, with the default ruleset, an indexerconnector output, the policy and the default path that accepts all events. Change the file output to a path that is writable by the process. Upload the store to S3.
2. **Modify the package build scripts** to include the download and integration of the compressed store file from S3.
3. **Adjust the installation scripts** to handle the decompression and setup of the store in its designated directory.
4. **Test the package builds** to ensure the store is correctly integrated and functioning post-installation.

## Expected Outcome:

The updated DEB and RPM packages should seamlessly integrate a basic store, enhancing the out-of-box functionality of Wazuh-Engine, providing a better user experience for initial setups.

**Comment by JavierBejMen** [comment]
## Update
- Implemented changes in inst-functions.sh
- Added indexer output only for the package 
- Working on testing

**Comment by JavierBejMen** [comment]
## Update
- Store generated and working deb package
- Working on rpm
- Investigating issue with glibc in ubuntu 22

**Comment by JavierBejMen** [comment]
## Update
- Added rpm store specs

**Comment by JcabreraC** [comment]
ETA extended for technical problems.
