### ISSUE TITLE
Framework -  UTs failing test after merging 4.10.0 into 4.10.1

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26379]
|Wazuh version|Component|
|---|---|
| 4.10.1 & 4.10.2 | framework |

## Description
After merging the 4.10.0 branch into 4.10.1, the "Framework unit tests" workflow failed ([see details](https://github.com/wazuh/wazuh/actions/runs/11391254302/job/31694639457?pr=26375))

> [!NOTE]
> No merge conflicts occurred during the process

> [!NOTE]
> This also failed in 4.10.2 ([see details](https://github.com/wazuh/wazuh/actions/runs/11393872539/job/31703062948?pr=26381))

## Checks
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment]
The bug has been introduced in #26255 since the `framework/wazuh/tests/data/security/rbac_catalog.yml` file was not correctly updated.
