### ISSUE TITLE
Incorrect Kibana version in plugin [wazuh]. Expected [5.6.4]; found [5.6.3]

### ISSUE THREAD

**Issue by ferrfrax** [wazuh/wazuh#264]
Hi,

I have this problem when installing the kibana app plugin:

$ /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 4458996 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.4]; found [5.6.3]"

wazuh-manager => wazuh-manager-2.1.1-1.el6.x86_64
wazuh-api => wazuh-api-2.1.1-1.el6.x86_64
rpm -q kibana => kibana-5.6.4-1.x86_64

the file https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.4.zip  does not exist  in the repository.

I appreciate the help you can give me

Regards,

**Comment by batidiane** [comment]
Hi,
I had the same issue yesterday. But no fix is available yet. Refer to thread #259.

Best regards.

**Comment by havidarou** [comment]
Hi, we are working on it. I hope to have it today.

Regards.

**Comment by havidarou** [comment]
Hi, 

you can now download the app for Kibana 5.6.4

Please refer to links in the repo's READEM.

Regards

**Comment by ferrfrax** [comment]
Thank you for your collaboration,

Now it works.

**Comment by havidarou** [comment]
Hi,

sorry, didn't see this thread.

There's a version available for 5.6.4:
packages.wazuh.com/wazuhapp/wazuhapp-2.1.1_5.6.4.zip

Regards.
