### ISSUE TITLE
Release 4.10.0 - Alpha 2 - E2E UX tests - Deployment on Kubernetes

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26406]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.10.0-alpha2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct 22, 2024 and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-devops team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct 23, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct 24, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Deployment on Kubernetes](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-kubernetes/index.html) | Single node | RHEL 7 x86_64 |
| Server | [Deployment on Kubernetes](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-kubernetes/index.html) | Multi node | RHEL 7 x86_64 |
| Dashboard | [Deployment on Kubernetes](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-kubernetes/index.html) | - | RHEL 7 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using FQDN and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.10.0-alpha2/_images/deploy-new-agent-from-ui1.png) | - | Ubuntu 24.04 aarch64 |

## Test description

Test [Deployment on Kubernetes](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-kubernetes/index.html).
- Test the installation guide in detail
- Test changing the default passwords

Remember to update the version of the Docker image to point to the current v4.10.0-alpha2 under tests. Example: v4.10.0-alpha2

## Known issues

- https://github.com/wazuh/wazuh-docker/issues/916

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| :red_circle:  | Wazuh Kubernetes Deployment |  | No failure, but I created an issue to investigate the warning message displayed during deployment: https://github.com/wazuh/wazuh-kubernetes/issues/868 |
| 🟢 | Changing the Default Passwords|  |  |
| 🟢 | Agent Deployment |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **RESPONSE HERE**
- Did you face any challenges not covered by the guideline?
  - **RESPONSE HERE**
- Suggestions for improvement:
  - **RESPONSE HERE**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [x] @juliamagan
- [x] @wazuh/devel-devops

**Comment by AwwalQuan** [comment]
## Infrastructure information

<details>
   <summary>Kubernetes host (RHEL 7 x86_64)</summary>
   <br/>

Host information
```
[vagrant@rhel7 wazuh-kubernetes]$ cd ~
[vagrant@rhel7 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

Docker version
```
[vagrant@rhel7 ~]$ docker --version
Docker version 26.1.4, build 5650f9b
```

Kubectl version
```
[vagrant@rhel7 ~]$ kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.0
```

Minikube cluster
```
[vagrant@rhel7 wazuh-kubernetes]$ minikube start --driver=docker
😄  minikube v1.34.0 on Redhat 7.9 (vbox/amd64)
✨  Using the docker driver based on user configuration
📌  Using Docker driver with root privileges
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🚜  Pulling base image v0.0.45 ...
💾  Downloading Kubernetes v1.31.0 preload ...
    > preloaded-images-k8s-v18-v1...:  326.69 MiB / 326.69 MiB  100.00% 5.41 Mi
    > gcr.io/k8s-minikube/kicbase...:  487.90 MiB / 487.90 MiB  100.00% 5.11 Mi
🔥  Creating docker container (CPUs=2, Memory=3800MB) ...
🐳  Preparing Kubernetes v1.31.0 on Docker 27.2.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

</details>

<details>
   <summary>Agent endpoint (Ubuntu 24.04 aarch64)</summary>
   <br/>

```
ubuntu@ip-172-31-41-249:~$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

</details>

## Deployment on Kubernetes running on RHEL 7
<details>
   <summary>Details</summary>
   <br/>

1. Clone the repository
```
[vagrant@rhel7 ~]$ git clone https://github.com/wazuh/wazuh-kubernetes.git -b v4.10.0-alpha2 --depth=1
Cloning into 'wazuh-kubernetes'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 63 (delta 24), reused 30 (delta 7), pack-reused 0 (from 0)
Unpacking objects: 100% (63/63), done.
Note: checking out '7cece2832b635d2c293edf9bd63c3ee419829459'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name
[vagrant@rhel7 ~]$ cd wazuh-kubernetes/
```

2. Generate the certificates
```
[vagrant@rhel7 wazuh-kubernetes]$ wazuh/certs/indexer_cluster/generate_certs.sh
Root CA
Generating RSA private key, 2048 bit long modulus
.............+++
.....+++
e is 65537 (0x10001)
Admin cert
create: admin-key-temp.pem
Generating RSA private key, 2048 bit long modulus
..........................................................+++
..................................................+++
e is 65537 (0x10001)
create: admin-key.pem
create: admin.csr
create: admin.pem
Signature ok
subject=/C=US/L=California/O=Company/CN=admin
Getting CA Private Key
* Node cert
create: node-key-temp.pem
Generating RSA private key, 2048 bit long modulus
............................+++
......................................+++
e is 65537 (0x10001)
create: node-key.pem
create: node.csr
create: node.pem
Signature ok
subject=/C=US/L=California/O=Company/CN=indexer
Getting CA Private Key
* dashboard cert
create: dashboard-key-temp.pem
Generating RSA private key, 2048 bit long modulus
...................................................................................+++
.........................................+++
e is 65537 (0x10001)
create: dashboard-key.pem
create: dashboard.csr
create: dashboard.pem
Signature ok
subject=/C=US/L=California/O=Company/CN=dashboard
Getting CA Private Key
* Filebeat cert
create: filebeat-key-temp.pem
Generating RSA private key, 2048 bit long modulus
.............................+++
..........................................................+++
e is 65537 (0x10001)
create: filebeat-key.pem
create: filebeat.csr
create: filebeat.pem
Signature ok
subject=/C=US/L=California/O=Company/CN=filebeat
Getting CA Private Key
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$ wazuh/certs/dashboard_http/generate_certs.sh
Generating a 2048 bit RSA private key
........................+++
......+++
writing new private key to 'key.pem'
-----
```

3. Edit `envs/local-env/storage-class.yaml` and configure the provisioner for a Minikube cluster
```
[vagrant@rhel7 wazuh-kubernetes]$ cat envs/local-env/storage-class.yaml
# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh StorageClass

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage

# Microk8s is our standard for local development
# provisioner: microk8s.io/hostpath

# In case you're running Minikube you can comment the line above and use this one
provisioner: k8s.io/minikube-hostpath

# If you're using a different provider you can list storage classes
# with: "kubectl get sc" and look for the column "Provisioner"
```

4. Deploy the cluster
```
[vagrant@rhel7 wazuh-kubernetes]$ kubectl apply -k envs/local-env/
namespace/wazuh created
storageclass.storage.k8s.io/wazuh-storage created
configmap/dashboard-conf-46kfc92gfm created
configmap/indexer-conf-t8tdh7thct created
configmap/wazuh-conf-54bf8bh7fk created
secret/dashboard-certs-8g5bt66db2 created
secret/dashboard-cred created
secret/indexer-certs-4f6f5h82cm created
secret/indexer-cred created
secret/wazuh-api-cred created
secret/wazuh-authd-pass created
secret/wazuh-cluster-key created
service/dashboard created
service/indexer created
service/wazuh created
service/wazuh-cluster created
service/wazuh-indexer created
service/wazuh-workers created
deployment.apps/wazuh-dashboard created
statefulset.apps/wazuh-indexer created
statefulset.apps/wazuh-manager-master created
Warning: spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector: a null labelSelector results in matching no pod
statefulset.apps/wazuh-manager-worker created
```

5. Verify the deployment
```
[vagrant@rhel7 wazuh-kubernetes]$ kubectl get namespaces | grep wazuh
wazuh             Active   16m
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$ kubectl get services -n wazuh
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                          AGE
dashboard       LoadBalancer   10.111.53.222   <pending>     443:30579/TCP                    16m
indexer         LoadBalancer   10.107.247.89   <pending>     9200:31958/TCP                   16m
wazuh           LoadBalancer   10.110.92.10    <pending>     1515:32613/TCP,55000:31523/TCP   16m
wazuh-cluster   ClusterIP      None            <none>        1516/TCP                         16m
wazuh-indexer   ClusterIP      None            <none>        9300/TCP                         16m
wazuh-workers   LoadBalancer   10.111.46.176   <pending>     1514:30730/TCP                   16m
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$ kubectl get deployments -n wazuh
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
wazuh-dashboard   1/1     1            1           16m
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$ kubectl get statefulsets -n wazuh
NAME                   READY   AGE
wazuh-indexer          1/1     16m
wazuh-manager-master   1/1     16m
wazuh-manager-worker   1/1     16m
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$
[vagrant@rhel7 wazuh-kubernetes]$ kubectl get pods -n wazuh
NAME                              READY   STATUS    RESTARTS   AGE
wazuh-dashboard-86ffdf998-8jrj6   1/1     Running   0          16m
wazuh-indexer-0                   1/1     Running   0          16m
wazuh-manager-master-0            1/1     Running   0          16m
wazuh-manager-worker-0            1/1     Running   0          16m
```


</details>

**Comment by AwwalQuan** [comment]
## Agent deployment 🟢

First forward port 1514 and 1515
```
[vagrant@rhel7 wazuh-kubernetes]$ kubectl -n wazuh port-forward --address 192.168.132.130 service/wazuh-workers 1514:1514
[vagrant@rhel7 wazuh-kubernetes]$ kubectl -n wazuh port-forward --address 192.168.132.130 service/wazuh 1515:1515
```

Create the group

![image](https://github.com/user-attachments/assets/ec702d46-8c53-4d8e-8942-cc90786d9ea5)


Agent deployment page

![image](https://github.com/user-attachments/assets/a85f261e-d507-4b60-b2a9-9e99dce1d384)

Internal VPN IP address used in the configuration.

Deploy Wazuh agent on the Ubuntu endpoint
```
root@ip-172-31-41-249:/home/ubuntu# wget https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.0-1_arm64.deb && sudo WAZUH_MANAGER='192.168.192.218' WAZUH_REGISTRATION_PASSWORD=$'password' WAZUH_AGENT_GROUP='linuxgroup' dpkg -i ./wazuh-agent_4.10.0-1_arm64.deb
--2024-10-22 23:08:03--  https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.0-1_arm64.deb
Resolving packages-dev.wazuh.com (packages-dev.wazuh.com)... 3.167.37.46, 3.167.37.122, 3.167.37.54, ...
Connecting to packages-dev.wazuh.com (packages-dev.wazuh.com)|3.167.37.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5954488 (5.7M) [application/vnd.debian.binary-package]
Saving to: 'wazuh-agent_4.10.0-1_arm64.deb'

wazuh-agent_4.10.0-1_arm64.deb      100%[================================================================>]   5.68M  11.7MB/s    in 0.5s

2024-10-22 23:08:04 (11.7 MB/s) - 'wazuh-agent_4.10.0-1_arm64.deb' saved [5954488/5954488]

Selecting previously unselected package wazuh-agent.
(Reading database ... 101523 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.10.0-1_arm64.deb ...
Unpacking wazuh-agent (4.10.0-1) ...
Setting up wazuh-agent (4.10.0-1) ...
Processing triggers for libc-bin (2.39-0ubuntu8.3) ...
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu# systemctl start wazuh-agent
root@ip-172-31-41-249:/home/ubuntu# systemctl enable wazuh-agent
Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /usr/lib/systemd/system/wazuh-agent.service.
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu#
root@ip-172-31-41-249:/home/ubuntu# systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/usr/lib/systemd/system/wazuh-agent.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-10-22 23:08:33 UTC; 17s ago
      Tasks: 33 (limit: 2196)
     Memory: 98.9M (peak: 99.0M)
        CPU: 2.823s
     CGroup: /system.slice/wazuh-agent.service
             ├─13981 /var/ossec/bin/wazuh-execd
             ├─13989 /var/ossec/bin/wazuh-agentd
             ├─14002 /var/ossec/bin/wazuh-syscheckd
             ├─14015 /var/ossec/bin/wazuh-logcollector
             ├─14032 /var/ossec/bin/wazuh-modulesd
             ├─14111 /bin/sh active-response/bin/restart.sh agent
             └─14115 /bin/sh /var/ossec/bin/wazuh-control restart

Oct 22 23:08:27 ip-172-31-41-249 systemd[1]: Starting wazuh-agent.service - Wazuh agent...
Oct 22 23:08:27 ip-172-31-41-249 env[13959]: Starting Wazuh v4.10.0...
Oct 22 23:08:27 ip-172-31-41-249 env[13959]: Started wazuh-execd...
Oct 22 23:08:28 ip-172-31-41-249 env[13959]: Started wazuh-agentd...
Oct 22 23:08:29 ip-172-31-41-249 env[13959]: Started wazuh-syscheckd...
Oct 22 23:08:30 ip-172-31-41-249 env[13959]: Started wazuh-logcollector...
Oct 22 23:08:31 ip-172-31-41-249 env[13959]: Started wazuh-modulesd...
Oct 22 23:08:33 ip-172-31-41-249 env[13959]: Completed.
Oct 22 23:08:33 ip-172-31-41-249 systemd[1]: Started wazuh-agent.service - Wazuh agent.
```

![image](https://github.com/user-attachments/assets/7f033b52-6beb-4563-8aba-0b4bdba63ab8)

**Comment by rauldpm** [comment]
We should investigate this warning

```
Warning: spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector: a null labelSelector results in matching no pod
```

There is a community post about it from 2 months ago https://www.reddit.com/r/Wazuh/comments/18rokgn/failed_local_deployment_issue_wazuhindexer0/
