### ISSUE TITLE
Release 4.10.0 - Alpha 2 - E2E UX tests - Deployment with Ansible

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26405]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.10.0-alpha2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct 22, 2024 and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-devops team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct 23, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct 24, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-ansible/index.html) | Multi node | Debian 11 x86_64 |
| Server | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-ansible/index.html) | Multi node | Debian 11 arm64 |
| Dashboard | [Deployment with Ansible](https://documentation-dev.wazuh.com/v4.10.0-alpha2/deployment-options/deploying-with-ansible/index.html) | - | Debian 11 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using FQDN and GROUP (created beforehand, don't use default)](https://documentation-dev.wazuh.com/v4.10.0-alpha2/_images/deploy-new-agent-from-ui1.png) | - | RHEL 7 x86_64 |

## Test description

Test distributed deployment with the Wazuh manager cluster and Wazuh indexer cluster via Ansible.
Test deployment of the agent via Ansible.

You might need to edit the `wazuh-template.json` URL to point to the current v4.10.0-alpha2 under test. Example: v4.10.0-alpha2

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🔴  | Deployments to manager and indexer server failed due to a certificate generation issue | The certificate generation tool failed due to errors in the repository |  New issue: https://github.com/wazuh/wazuh-ansible/pull/1443 |
| 🔴 | Signature key failed while setting up the Ansible Server | Dependency failure | New issue opened: https://github.com/wazuh/wazuh-documentation/issues/7924 |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **The testing guidelines were not clear, there were a number of ambiguities in the sense that the documentation only focused on all-in-one and cluster deployment with a single playbook, there was no guide as to what to do if a user wants to use individual playbooks across multiple servers**
- Did you face any challenges not covered by the guideline?
  - **Yes, there were dependencies that I had to install that were not stated in the guidelines, I have also reported them in the test report**
- Suggestions for improvement:
  - **Ensure documentation is descriptive  enough that user doesn't have to troubleshoot or improvise on anything while they're doing the deployment**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @juliamagan
- [x] @wazuh/devel-devops

**Comment by jk-olaoluwa** [comment]
## Environment

<details>
<summary> Ansible Server Specs</summary>

``` console
root@ip:/home/admin# hostnamectl
   Static hostname: ip
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec2****************************
           Boot ID: 8********************************
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-33-cloud-amd64
      Architecture: x86-64
root@ip:/home/admin# uname -m
x86_64
```

<details>
<summary> Manager Server Specs</summary>

``` console
root@ip:/home/admin# hostnamectl
   Static hostname: ip
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec****************************
           Boot ID: cf*****************************
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-33-cloud-amd64
      Architecture: x86-64
root@ip:/home/admin# uname -m
x86_64
```

<details>
<summary> Indexer Server Specs</summary>

``` console
admin@ip:~$ sudo su
root@ip:/home/admin# hostnamectl
   Static hostname: ip
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ec****************************
           Boot ID: 52**********************************
    Virtualization: kvm
  Operating System: Debian GNU/Linux 11 (bullseye)
            Kernel: Linux 5.10.0-33-cloud-amd64
      Architecture: x86-64
root@ip:/home/admin# uname -m
x86_64
```

<details>
<summary> Agent Specs</summary>

``` console
[root@ip- ec2-user]# hostnamectl
   Static hostname: ip-.ec2.internal
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 02**********************
           Boot ID: 0*****************************
    Virtualization: kvm
  Operating System: Red Hat Enterprise Linux Server 7.9 (Maipo)
       CPE OS Name: cpe:/o:redhat:enterprise_linux:7.9:GA:server
            Kernel: Linux 3.10.0-1160.118.1.el7.x86_64
      Architecture: x86-64
[root@ip- ec2-user]# uname -m
x86_64
```

**Comment by jk-olaoluwa** [comment]
# Install Ansible

## Installation on Debian

<details>
<summary> Install required dependencies</summary>

``` console
root@ip-:/home/admin# apt-get update
apt-get install lsb-release software-properties-common
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Hit:2 http://cdn-aws.deb.debian.org/debian bullseye InRelease
Hit:3 http://cdn-aws.deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://cdn-aws.deb.debian.org/debian bullseye-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
lsb-release is already the newest version (11.1.0).
lsb-release set to manually installed.
The following additional packages will be installed:
  gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 iso-codes libappstream4 libdw1 libgirepository-1.0-1 libglib2.0-bin libglib2.0-data
  libgstreamer1.0-0 libpackagekit-glib2-18 libpolkit-agent-1-0 libpolkit-gobject-1-0 libstemmer0d libunwind8 packagekit
  packagekit-tools policykit-1 python3-gi python3-software-properties
Suggested packages:
  isoquery gstreamer1.0-tools appstream
The following NEW packages will be installed:
  gir1.2-glib-2.0 gir1.2-packagekitglib-1.0 iso-codes libappstream4 libdw1 libgirepository-1.0-1 libglib2.0-bin libglib2.0-data
  libgstreamer1.0-0 libpackagekit-glib2-18 libpolkit-agent-1-0 libpolkit-gobject-1-0 libstemmer0d libunwind8 packagekit
  packagekit-tools policykit-1 python3-gi python3-software-properties software-properties-common
0 upgraded, 20 newly installed, 0 to remove and 1 not upgraded.
Need to get 8540 kB of archives.
After this operation, 44.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libgirepository-1.0-1 amd64 1.66.1-1+b1 [96.7 kB]
Get:2 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 gir1.2-glib-2.0 amd64 1.66.1-1+b1 [151 kB]
Get:3 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libpackagekit-glib2-18 amd64 1.2.2-2 [124 kB]
Get:4 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 gir1.2-packagekitglib-1.0 amd64 1.2.2-2 [36.8 kB]
Get:5 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 iso-codes all 4.6.0-1 [2824 kB]
Get:6 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libstemmer0d amd64 2.1.0-1 [119 kB]
Get:7 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libappstream4 amd64 0.14.4-1 [172 kB]
Get:8 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libdw1 amd64 0.183-1 [234 kB]
Get:9 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libglib2.0-data all 2.66.8-1+deb11u4 [1178 kB]
Get:10 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libglib2.0-bin amd64 2.66.8-1+deb11u4 [142 kB]
Get:11 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libunwind8 amd64 1.3.2-2 [54.5 kB]
Get:12 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libgstreamer1.0-0 amd64 1.18.4-2.1 [2230 kB]
Get:13 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libpolkit-gobject-1-0 amd64 0.105-31+deb11u1 [48.5 kB]
Get:14 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 libpolkit-agent-1-0 amd64 0.105-31+deb11u1 [28.1 kB]
Get:15 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 policykit-1 amd64 0.105-31+deb11u1 [96.7 kB]
Get:16 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 packagekit amd64 1.2.2-2 [598 kB]
Get:17 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 packagekit-tools amd64 1.2.2-2 [41.7 kB]
Get:18 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 python3-gi amd64 3.38.0-2 [232 kB]
Get:19 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 python3-software-properties all 0.96.20.2-2.1 [49.7 kB]
Get:20 http://cdn-aws.deb.debian.org/debian bullseye/main amd64 software-properties-common all 0.96.20.2-2.1 [83.4 kB]
Fetched 8540 kB in 0s (50.3 MB/s)
Selecting previously unselected package libgirepository-1.0-1:amd64.
(Reading database ... 28329 files and directories currently installed.)
Preparing to unpack .../00-libgirepository-1.0-1_1.66.1-1+b1_amd64.deb ...
Unpacking libgirepository-1.0-1:amd64 (1.66.1-1+b1) ...
Selecting previously unselected package gir1.2-glib-2.0:amd64.
Preparing to unpack .../01-gir1.2-glib-2.0_1.66.1-1+b1_amd64.deb ...
Unpacking gir1.2-glib-2.0:amd64 (1.66.1-1+b1) ...
Selecting previously unselected package libpackagekit-glib2-18:amd64.
Preparing to unpack .../02-libpackagekit-glib2-18_1.2.2-2_amd64.deb ...
Unpacking libpackagekit-glib2-18:amd64 (1.2.2-2) ...
Selecting previously unselected package gir1.2-packagekitglib-1.0.
Preparing to unpack .../03-gir1.2-packagekitglib-1.0_1.2.2-2_amd64.deb ...
Unpacking gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Selecting previously unselected package iso-codes.
Preparing to unpack .../04-iso-codes_4.6.0-1_all.deb ...
Unpacking iso-codes (4.6.0-1) ...
Selecting previously unselected package libstemmer0d:amd64.
Preparing to unpack .../05-libstemmer0d_2.1.0-1_amd64.deb ...
Unpacking libstemmer0d:amd64 (2.1.0-1) ...
Selecting previously unselected package libappstream4:amd64.
Preparing to unpack .../06-libappstream4_0.14.4-1_amd64.deb ...
Unpacking libappstream4:amd64 (0.14.4-1) ...
Selecting previously unselected package libdw1:amd64.
Preparing to unpack .../07-libdw1_0.183-1_amd64.deb ...
Unpacking libdw1:amd64 (0.183-1) ...
Selecting previously unselected package libglib2.0-data.
Preparing to unpack .../08-libglib2.0-data_2.66.8-1+deb11u4_all.deb ...
Unpacking libglib2.0-data (2.66.8-1+deb11u4) ...
Selecting previously unselected package libglib2.0-bin.
Preparing to unpack .../09-libglib2.0-bin_2.66.8-1+deb11u4_amd64.deb ...
Unpacking libglib2.0-bin (2.66.8-1+deb11u4) ...
Selecting previously unselected package libunwind8:amd64.
Preparing to unpack .../10-libunwind8_1.3.2-2_amd64.deb ...
Unpacking libunwind8:amd64 (1.3.2-2) ...
Selecting previously unselected package libgstreamer1.0-0:amd64.
Preparing to unpack .../11-libgstreamer1.0-0_1.18.4-2.1_amd64.deb ...
Unpacking libgstreamer1.0-0:amd64 (1.18.4-2.1) ...
Selecting previously unselected package libpolkit-gobject-1-0:amd64.
Preparing to unpack .../12-libpolkit-gobject-1-0_0.105-31+deb11u1_amd64.deb ...
Unpacking libpolkit-gobject-1-0:amd64 (0.105-31+deb11u1) ...
Selecting previously unselected package libpolkit-agent-1-0:amd64.
Preparing to unpack .../13-libpolkit-agent-1-0_0.105-31+deb11u1_amd64.deb ...
Unpacking libpolkit-agent-1-0:amd64 (0.105-31+deb11u1) ...
Selecting previously unselected package policykit-1.
Preparing to unpack .../14-policykit-1_0.105-31+deb11u1_amd64.deb ...
Unpacking policykit-1 (0.105-31+deb11u1) ...
Selecting previously unselected package packagekit.
Preparing to unpack .../15-packagekit_1.2.2-2_amd64.deb ...
Unpacking packagekit (1.2.2-2) ...
Selecting previously unselected package packagekit-tools.
Preparing to unpack .../16-packagekit-tools_1.2.2-2_amd64.deb ...
Unpacking packagekit-tools (1.2.2-2) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../17-python3-gi_3.38.0-2_amd64.deb ...
Unpacking python3-gi (3.38.0-2) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../18-python3-software-properties_0.96.20.2-2.1_all.deb ...
Unpacking python3-software-properties (0.96.20.2-2.1) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../19-software-properties-common_0.96.20.2-2.1_all.deb ...
Unpacking software-properties-common (0.96.20.2-2.1) ...
Setting up libdw1:amd64 (0.183-1) ...
Setting up libpackagekit-glib2-18:amd64 (1.2.2-2) ...
Setting up libunwind8:amd64 (1.3.2-2) ...
Setting up libglib2.0-data (2.66.8-1+deb11u4) ...
Setting up libgirepository-1.0-1:amd64 (1.66.1-1+b1) ...
Setting up libstemmer0d:amd64 (2.1.0-1) ...
Setting up iso-codes (4.6.0-1) ...
Setting up libpolkit-gobject-1-0:amd64 (0.105-31+deb11u1) ...
Setting up libgstreamer1.0-0:amd64 (1.18.4-2.1) ...
Setcap worked! gst-ptp-helper is not suid!
Setting up libglib2.0-bin (2.66.8-1+deb11u4) ...
Setting up libappstream4:amd64 (0.14.4-1) ...
Setting up gir1.2-glib-2.0:amd64 (1.66.1-1+b1) ...
Setting up libpolkit-agent-1-0:amd64 (0.105-31+deb11u1) ...
Setting up policykit-1 (0.105-31+deb11u1) ...
Setting up gir1.2-packagekitglib-1.0 (1.2.2-2) ...
Setting up python3-gi (3.38.0-2) ...
Setting up packagekit (1.2.2-2) ...
Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
Setting up packagekit-tools (1.2.2-2) ...
Processing triggers for dbus (1.12.28-0+deb11u1) ...
Processing triggers for sgml-base (1.30) ...
Processing triggers for libc-bin (2.31-13+deb11u11) ...
Processing triggers for man-db (2.9.4-2) ...
Setting up python3-software-properties (0.96.20.2-2.1) ...
Setting up software-properties-common (0.96.20.2-2.1) ...
Processing triggers for dbus (1.12.28-0+deb11u1) ...
```
</details>


<details>
<summary> Setup ansible repository </summary>

``` console

```
</details>

**Comment by jk-olaoluwa** [comment]
# Install Wazuh indexer and dashboard

<details>
<summary> Accessing the wazuh-ansible directory 🟢  </summary>

``` console
root@ip-:/etc/ansible/roles# cd /etc/ansible/roles/wazuh-ansible/

root@ip-:/etc/ansible/roles/wazuh-ansible# tree roles -d
roles
├── elastic-stack
│   └── ansible-kibana
│       └── defaults
├── opendistro
│   └── opendistro-kibana
│       └── defaults
└── wazuh
    ├── ansible-filebeat
    │   └── defaults
    ├── ansible-filebeat-oss
    │   ├── defaults
    │   ├── handlers
    │   ├── meta
    │   ├── tasks
    │   └── templates
    ├── ansible-wazuh-agent
    │   ├── defaults
    │   ├── handlers
    │   ├── meta
    │   ├── tasks
    │   └── templates
    ├── ansible-wazuh-manager
    │   ├── defaults
    │   ├── files
    │   │   └── custom_ruleset
    │   │       ├── decoders
    │   │       └── rules
    │   ├── handlers
    │   ├── meta
    │   ├── tasks
    │   ├── templates
    │   └── vars
    ├── check-packages
    │   ├── defaults
    │   ├── files
    │   ├── scripts
    │   └── tasks
    ├── vars
    ├── wazuh-dashboard
    │   ├── defaults
    │   ├── handlers
    │   ├── tasks
    │   ├── templates
    │   └── vars
    └── wazuh-indexer
        ├── defaults
        ├── handlers
        ├── meta
        ├── tasks
        └── templates

50 directories

root@ip-:/etc/ansible/roles/wazuh-ansible# tree playbooks/
playbooks/
├── ansible.cfg
├── wazuh-agent.yml
├── wazuh-dashboard.yml
├── wazuh-indexer.yml
├── wazuh-manager-oss-cluster.yml
├── wazuh-manager-oss.yml
├── wazuh-production-ready.yml
└── wazuh-single.yml

0 directories, 8 files
```
</details>

<details>
<summary> Preparing to run the playbook 🔴 </summary>
``` console

```
</details>
