### ISSUE TITLE
Release 4.10.0 - Alpha 2 - E2E UX tests - SAML SSO

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26417]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.10.0-alpha2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-dashboard team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct 22, 2024 and notify the @wazuh/devel-dashboard team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-dashboard team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct 23, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct 24, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.10.0-alpha2/quickstart.html) | - | CentOS 8 x86_64 |
| Server | Same as indexer, all-in-one | - | - |
| Dashboard | Same as indexer, all-in-one | - | - |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.10.0-alpha2/installation-guide/wazuh-agent/index.html) | - | Fedora 39 x86_64 |

## Test description

Following documentation from Single sign-on https://documentation-dev.wazuh.com/v4.10.0-alpha2/user-manual/user-administration/single-sign-on/index.html, try the best effort to complete the steps and test the dashboard login using Okta and Microsoft Entra ID

## Known issues

There are no known issues.

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢   | Quickstart installation  |  |  |
| 🟢   | Wazuh agent installation |  |  |
| 🟢   | Okta - Admin role |  |  |
| 🟢   | Okta - Read only role |  |  |
| 🟢   | Entra ID - Admin role |  |  |
| 🟢   | Entra ID - Read only role |  |  |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - **All clear**
- Did you face any challenges not covered by the guideline?
  - **None**
- Suggestions for improvement:
  - **The template should be updated to match a more recent OS, Cent OS 8 has reached EOL**

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @juliamagan
- [x] @wazuh/devel-dashboard

**Comment by ace-109** [comment]
# Installation Environment
## Wazuh central components
I got approval from Julia to use CentOS stream 9 as CentOS 8 has reached EOL.
### OS Details 
```
[root@localhost wazuh]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```
### Quickstart installation
```
[root@localhost wazuh]# curl -sO https://packages-dev.wazuh.com/4.10/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
21/10/2024 13:40:36 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.0
21/10/2024 13:40:36 INFO: Verbose logging redirected to /var/log/wazuh-install.log
21/10/2024 13:40:36 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.
21/10/2024 13:40:36 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.
21/10/2024 13:40:36 INFO: Verifying that your system meets the recommended minimum hardware requirements.
21/10/2024 13:40:36 INFO: Wazuh web interface port will be 443.
21/10/2024 13:40:36 WARNING: The system has Firewalld enabled. Please ensure that traffic is allowed on these ports: 1515, 1514, 443.
21/10/2024 13:40:37 INFO: Wazuh repository added.
21/10/2024 13:40:37 INFO: --- Configuration files ---
21/10/2024 13:40:37 INFO: Generating configuration files.
21/10/2024 13:40:38 INFO: Generating the root certificate.
21/10/2024 13:40:38 INFO: Generating Admin certificates.
21/10/2024 13:40:38 INFO: Generating Wazuh indexer certificates.
21/10/2024 13:40:38 INFO: Generating Filebeat certificates.
21/10/2024 13:40:38 INFO: Generating Wazuh dashboard certificates.
21/10/2024 13:40:38 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
21/10/2024 13:40:39 INFO: --- Wazuh indexer ---
21/10/2024 13:40:39 INFO: Starting Wazuh indexer installation.
21/10/2024 13:40:47 ERROR: Wazuh indexer installation failed.
21/10/2024 13:40:47 INFO: --- Removing existing Wazuh installation ---
21/10/2024 13:40:47 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
```
`/var/log/wazuh-install.log` file
I encountered an error
```
21/10/2024 13:40:36 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.0
21/10/2024 13:40:36 INFO: Verbose logging redirected to /var/log/wazuh-install.log
21/10/2024 13:40:36 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.
21/10/2024 13:40:36 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.
21/10/2024 13:40:36 INFO: Verifying that your system meets the recommended minimum hardware requirements.
21/10/2024 13:40:36 INFO: Wazuh web interface port will be 443.
21/10/2024 13:40:36 WARNING: The system has Firewalld enabled. Please ensure that traffic is allowed on these ports: 1515, 1514, 443.
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-${releasever} - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1
21/10/2024 13:40:37 INFO: Wazuh repository added.
21/10/2024 13:40:37 INFO: --- Configuration files ---
21/10/2024 13:40:37 INFO: Generating configuration files.
21/10/2024 13:40:38 INFO: Generating the root certificate.
21/10/2024 13:40:38 INFO: Generating Admin certificates.
21/10/2024 13:40:38 INFO: Generating Wazuh indexer certificates.
21/10/2024 13:40:38 INFO: Generating Filebeat certificates.
21/10/2024 13:40:38 INFO: Generating Wazuh dashboard certificates.
21/10/2024 13:40:38 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
21/10/2024 13:40:39 INFO: --- Wazuh indexer ---
21/10/2024 13:40:39 INFO: Starting Wazuh indexer installation.
EL-9 - Wazuh 2.8 kB/s | 3.5 kB 00:01 Last metadata expiration check: 0:00:04 ago on Mon 21 Oct 2024 01:34:11 PM WAT. No match for argument: wazuh-indexer-4.10.0-* Error: Unable to find a match: wazuh-indexer-4.10.0-*
21/10/2024 13:40:47 ERROR: Wazuh indexer installation failed.
21/10/2024 13:40:47 INFO: --- Removing existing Wazuh installation ---
21/10/2024 13:40:47 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
[root@localhost wazuh]#
```

## Wazuh agent

**Comment by ace-109** [comment]
# Okta setup
-  Create user
I created 2 users
<img width="667" alt="image" src="https://github.com/user-attachments/assets/58e2ee1a-1230-4731-86c3-b4f589ebf6f9">
<img width="667" alt="image" src="https://github.com/user-attachments/assets/412595a2-3c16-45d9-82a5-1984ab6025eb">
<img width="666" alt="image" src="https://github.com/user-attachments/assets/3578a093-4b82-4476-ae19-bb3e22d08d07">

- Create a new group
I created the `wazuh-admins` group, the backend role for admin permission. 
<img width="666" alt="image" src="https://github.com/user-attachments/assets/b1d2259b-c369-4f45-8827-6e96268e75b2">

I created the `wazuh-readonly` group, the backend role for readonly permission.
<img width="668" alt="image" src="https://github.com/user-attachments/assets/9f182115-f9db-406d-bb7a-412a9f5d4f08">


- Add user to the group. 

Admin user
<img width="668" alt="image" src="https://github.com/user-attachments/assets/05bf0b6b-ae88-4585-863e-ec9f63673b08">

Readonly user
<img width="668" alt="image" src="https://github.com/user-attachments/assets/395b24f8-6599-419d-8c5a-d95e8b7ed0bf">

- Creation and configuration of the app
<img width="665" alt="image" src="https://github.com/user-attachments/assets/26359d3e-774b-4929-9c1b-56881f80ac65">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/1df8c280-f1c9-4498-8c09-10db92540267">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/4ce3890f-63ce-4810-959c-99ad62cac222">

App successfully created 
<img width="666" alt="image" src="https://github.com/user-attachments/assets/d160a7ec-12e3-46a2-a230-9f6f99bcb152">

- Add app to group
I added the app to both readonly and admin groups
<img width="668" alt="image" src="https://github.com/user-attachments/assets/de0cdeac-2854-4b04-8a35-60b13b1242ae">

<img width="669" alt="image" src="https://github.com/user-attachments/assets/2442fea1-ec61-4913-9f40-4ca3c9727154">

- Wazuh indexer configuration
The `/etc/wazuh-indexer/opensearch-security/config.yml` file
```
authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "intern"
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: 'https://trial-XXXXXX.okta.com/app/XXXXXX/sso/saml/metadata'
              entity_id: 'http://www.okta.com/XXXXXX'
            sp:
              entity_id: wazuh-saml
            kibana_url: https://192.168.33.130
            roles_key: Roles
            exchange_key: 'b2cb3edc8256bc68d44a2ba9096b2fXXXXXX'
        authentication_backend:
          type: noop
```

I ran the `securityadmin.sh` script
```
[root@localhost wazuh]# export JAVA_HOME=/usr/share/wazuh-indexer/jdk/ && bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/config.yml -icl -key /etc/wazuh-indexer/certs/admin-key.pem -cert /etc/wazuh-indexer/certs/admin.pem -cacert /etc/wazuh-indexer/certs/root-ca.pem -h 127.0.0.1 -nhnv
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.16.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/wazuh
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["config"],"updated_config_size":1,"message":null} is 1 (["config"]) due to: null
Done with success
```
- Role mapping for admin role

I edited the `/etc/wazuh-indexer/opensearch-security/roles_mapping.yml` file and added the backend role for the admin group
```
all_access:
  reserved: true
  hidden: false
  backend_roles:
  - "admin"
  - "wazuh-admins"
```
I ran the securityadmin.sh script to apply the role mapping configuration
```
[root@localhost wazuh]# export JAVA_HOME=/usr/share/wazuh-indexer/jdk/ && bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/roles_mapping.yml -icl -key /etc/wazuh-indexer/certs/admin-key.pem -cert /etc/wazuh-indexer/certs/admin.pem -cacert /etc/wazuh-indexer/certs/root-ca.pem -h 127.0.0.1 -nhnv
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.16.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/wazuh
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["rolesmapping"],"updated_config_size":1,"message":null} is 1 (["rolesmapping"]) due to: null
Done with success
```

- Wazuh dashboard configuration
The value of `run_as` in the /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml configuration file is false by default.

```
hosts:
  - default:
      url: https://127.0.0.1
      port: 55000
      username: wazuh-wui
      password: "XXXXXXXXXXXXXXXXXX"
      run_as: false
```
- Wazuh dashboard configuration file
I added these configurations to `/etc/wazuh-dashboard/opensearch_dashboards.yml` file

```
opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]
opensearch_security.session.keepalive: false
```

I restarted the Wazuh dashboard
```
systemctl restart wazuh-dashboard
```
- Login with admin role


- Role mapping for read only role
- Login with readonly role

**Comment by ace-109** [comment]
# Entra ID SSO setup 🟢
<details> <summary> Entra ID SSO Configuration 🟢 </summary>

- Create App
<img width="669" alt="image" src="https://github.com/user-attachments/assets/b8b6a38d-bbfc-4538-b882-56ef5aeca212">
- Create app role
I created the admin role
<img width="668" alt="image" src="https://github.com/user-attachments/assets/8889dacc-8269-49a7-b733-7b1bcce41fef">
I created the read-only role also
<img width="669" alt="image" src="https://github.com/user-attachments/assets/4bbdab31-95e8-4cce-afed-7d1fed1beb6c">
- Assign a user to the app
I assigned the admin and readonly users and roles to the application
<img width="668" alt="image" src="https://github.com/user-attachments/assets/a8a45697-24be-44a0-bcd4-39ea5a7e89dd">
- Configure SSO
SAML configuration summary
<img width="668" alt="image" src="https://github.com/user-attachments/assets/a579ecd4-7aff-4afb-a529-75af772defda">
</details>

<details> <summary> Wazuh Indexer🟢 </summary>

The `/etc/wazuh-indexer/opensearch-security/config.yml` file 

```
authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: "basic"
          challenge: false
        authentication_backend:
          type: "intern"
      saml_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://login.microsoftonline.com/bcc335b2XXXXXXXXXXXX
              entity_id: https://sts.windows.net/bcc335b2-f64b-49a0-b8e4-XXXXXXXXXXX
            sp:
              entity_id: wazuh-saml2
            kibana_url: https://192.168.33.130
            roles_key: Roles
            exchange_key: '18bb49233d9a4832738da369fccd580294d7XXXXXXXXXXXXXXXX'
        authentication_backend:
          type: noop
```
I ran the security admin script
```
[root@localhost wazuh]# export JAVA_HOME=/usr/share/wazuh-indexer/jdk/ && bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/config.yml -icl -key /etc/wazuh-indexer/certs/admin-key.pem -cert /etc/wazuh-indexer/certs/admin.pem -cacert /etc/wazuh-indexer/certs/root-ca.pem -h 127.0.0.1 -nhnv
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.16.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/wazuh
Will update '/config' with /etc/wazuh-indexer/opensearch-security/config.yml
   SUCC: Configuration for 'config' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["config"],"updated_config_size":1,"message":null} is 1 (["config"]) due to: null
Done with success
```
</details>

<details> <summary> Wazuh dashboard configuration 🟢 </summary>

```
opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_opendistro/_security/saml/acs/idpinitiated"]
opensearch_security.session.keepalive: false
```
</details>

<details> <summary> Login with admin role 🟢 </summary>

I edited the `/etc/wazuh-indexer/opensearch-security/roles_mapping.yml` file
```
all_access:
  reserved: false
  hidden: false
  backend_roles:
  - "admin"
  - "Wazuh_role"
  description: "Maps admin to all_access"
```
I ran the securityadmin script

```
[root@localhost wazuh]# export JAVA_HOME=/usr/share/wazuh-indexer/jdk/ && bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/securityadmin.sh -f /etc/wazuh-indexer/opensearch-security/roles_mapping.yml -icl -key /etc/wazuh-indexer/certs/admin-key.pem -cert /etc/wazuh-indexer/certs/admin.pem -cacert /etc/wazuh-indexer/certs/root-ca.pem -h 127.0.0.1 -nhnv
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
Security Admin v7
Will connect to 127.0.0.1:9200 ... done
Connected as "CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US"
OpenSearch Version: 2.16.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Clustername: wazuh-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /home/wazuh
Will update '/rolesmapping' with /etc/wazuh-indexer/opensearch-security/roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
SUCC: Expected 1 config types for node {"updated_config_types":["rolesmapping"],"updated_config_size":1,"message":null} is 1 (["rolesmapping"]) due to: null
Done with success
```

I logged in successfully

<img width="668" alt="image" src="https://github.com/user-attachments/assets/32ef13c4-9248-42e2-bb2e-f0a95ff0dc50">

<img width="667" alt="image" src="https://github.com/user-attachments/assets/c4f6d856-7cc3-4607-ae03-73ee6014b54c">

</details>

<details> <summary> Login with readonly role 🟢 </summary>

</details>

**Comment by Tostti** [comment]
LGTM
