### ISSUE TITLE
Release 4.10.0 - Alpha 2 - E2E UX tests - Azure integration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26422]
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.10.0-alpha2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Oct 22, 2024 and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-pyserver team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Oct 23, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Oct 24, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.10.0-alpha2/installation-guide/wazuh-indexer/step-by-step.html) | Single node | CentOS 9 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.10.0-alpha2/installation-guide/wazuh-server/step-by-step.html) | Multi node | CentOS 9 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.10.0-alpha2/installation-guide/wazuh-dashboard/step-by-step.html) | - | CentOS 9 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.10.0-alpha2/_images/deploy-new-agent-from-ui1.png) | - | Amazon Linux 2 x86_64 |

## Test description

Configure the Azure integration in a Wazuh Manager and a Wazuh Agent. 
Try the Graph, Log Analytics, and Storage integrations.
Ensure the events are correctly displayed on the dashboard.
Documentation: https://documentation-dev.wazuh.com/v4.10.0-alpha2/cloud-security/azure/index.html

## Known issues

- https://github.com/wazuh/wazuh-documentation/issues/5803
- https://github.com/wazuh/wazuh-documentation/issues/6494
- https://github.com/wazuh/wazuh-documentation/issues/6563
- https://github.com/wazuh/wazuh/issues/19282
- https://github.com/wazuh/wazuh-documentation/issues/6559

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢  |  Wazuh Deployment/Setup |N/A | N/A|
| 🟢  | Azure integration for Log analytics and Storage on Wazuh Server |N/A|N/A |
| 🔴   | Azure integration for Graph on Wazuh Server |No error code| No error codes were thrown, however, there were no alerts reported on the dashboard. While _data.TargetResource.displayName_ shows Microsoft graph, no events were reported with the tag _microsoft-entra_id_  [#26489](https://github.com/wazuh/wazuh/issues/26489)|
| 🟢    | Azure integration for Log Analytics on Wazuh Agent |N/A| Logs were shown on the Wazuh dashboard|
|  🔴   | Azure integration for Graph & Storage on Wazuh Agent |Error code 1 was thrown for Storage| Same Credentials and similar configurations used for Wazuh server configuration were used but did not work on the agent [#26523](https://github.com/wazuh/wazuh/issues/26523) |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
  - Testing guide was clear, no ambiguities
- Did you face any challenges not covered by the guideline?
  - None
- Suggestions for improvement:
  - None

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @juliamagan
- [ ] @wazuh/devel-pyserver

**Comment by ofvyn** [comment]
### System Information

<details>
<summary>CentOS 9 x86_64 (Indexer/Server 1)</summary>

```console
[root@ip-172-31-34-84 ec2-user]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0e:09:b6:fc:d4:11 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 172.31.34.84/20 brd 172.31.47.255 scope global dynamic noprefixroute eth0
       valid_lft 3378sec preferred_lft 3378sec
    inet6 fe80::c09:b6ff:fefc:d411/64 scope link
       valid_lft forever preferred_lft forever

[root@ip-172-31-34-84 ec2-user]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

````
</details>

<details>
<summary>CentOS 9 x86_64 (Dashboard/Server 2)</summary>

```console
[root@ip-172-31-35-94 ec2-user]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc mq state UP group default qlen 1000
    link/ether 0e:4e:c9:e5:20:e9 brd ff:ff:ff:ff:ff:ff
    altname enp0s5
    altname ens5
    inet 172.31.35.94/20 brd 172.31.47.255 scope global dynamic noprefixroute eth0
       valid_lft 3168sec preferred_lft 3168sec
    inet6 fe80::c4e:c9ff:fee5:20e9/64 scope link
       valid_lft forever preferred_lft forever

[root@ip-172-31-35-94 ec2-user]# cat /etc/os-release
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="9"
PLATFORM_ID="platform:el9"
PRETTY_NAME="CentOS Stream 9"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:centos:centos:9"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

````
</details>

**Comment by ofvyn** [comment]
# Wazuh Setup

<details><summary>Indexer/Server 1 setup</summary>

```bash
[root@ip-172-31-35-94 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.10/wazuh-install.sh
[root@ip-172-31-35-94 ec2-user]# curl -sO https://packages-dev.wazuh.com/4.10/config.yml
[root@ip-172-31-35-94 ec2-user]# ls
config.yml  wazuh-install.sh
[root@ip-172-31-35-94 ec2-user]# nano config.yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "172.31.35.94"
    #- name: node-2
    #  ip: "<indexer-node-ip>"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "172.31.35.94"
      node_type: master
    - name: wazuh-2
      ip: "172.31.34.84"
      node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "172.31.34.84"


[root@ip-172-31-35-94 ec2-user]# bash wazuh-install.sh --generate-config-files
21/10/2024 20:22:36 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.0
21/10/2024 20:22:36 INFO: Verbose logging redirected to /var/log/wazuh-install.log
21/10/2024 20:22:36 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.
21/10/2024 20:22:36 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.
21/10/2024 20:22:36 INFO: Verifying that your system meets the recommended minimum hardware requirements.
21/10/2024 20:22:36 INFO: --- Configuration files ---
21/10/2024 20:22:36 INFO: Generating configuration files.
21/10/2024 20:22:37 INFO: Generating the root certificate.
21/10/2024 20:22:37 INFO: Generating Admin certificates.
21/10/2024 20:22:37 INFO: Generating Wazuh indexer certificates.
21/10/2024 20:22:38 INFO: Generating Filebeat certificates.
21/10/2024 20:22:39 INFO: Generating Wazuh dashboard certificates.
21/10/2024 20:22:40 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
[root@ip-172-31-35-94 ec2-user]# ls
wazuh-install-files.tar  wazuh-install.sh
[root@ip-172-31-35-94 ec2-user]# bash wazuh-install.sh --wazuh-indexer node-1
21/10/2024 20:58:16 INFO: Starting Wazuh installation assistant. Wazuh version: 4.10.0
21/10/2024 20:58:16 INFO: Verbose logging redirected to /var/log/wazuh-install.log
21/10/2024 20:58:16 INFO: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04.
21/10/2024 20:58:16 WARNING: The current system does not match with the list of recommended systems. The installation may not work properly.
21/10/2024 20:58:16 INFO: Verifying that your system meets the recommended minimum hardware requirements.
21/10/2024 20:58:16 INFO: --- Dependencies ---
21/10/2024 20:58:16 INFO: Installing lsof.
21/10/2024 20:58:19 INFO: Wazuh repository added.
21/10/2024 20:58:19 INFO: --- Wazuh indexer ---
21/10/2024 20:58:19 INFO: Starting Wazuh indexer installation.
21/10/2024 20:58:42 ERROR: Wazuh indexer installation failed.
21/10/2024 20:58:42 INFO: --- Removing existing Wazuh installation ---
21/10/2024 20:58:42 INFO: --- Dependencies ---
21/10/2024 20:58:42 INFO: Removing lsof.
21/10/2024 20:58:44 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.
[root@ip-172-31-35-94 ec2-user]#

```
</details>

**Comment by ofvyn** [comment]
# Graph, Log Analytics, and Storage integrations Tests :green_circle:

<details><summary>Getting Access for Microsoft Graph and Log Analytics :green_circle:</summary>

### Log Analytics

- Create application

![image](https://github.com/user-attachments/assets/c58b3cbd-e3d2-4776-b53b-a115e8ba2e09)
![image](https://github.com/user-attachments/assets/eaf0deb9-a5db-4364-a517-25aac55df17b)

- Log Analytics Permissions

![image](https://github.com/user-attachments/assets/2c4c6b9e-3b9c-4fbf-a3d0-c537f0cb08bb)
![image](https://github.com/user-attachments/assets/cd55be95-baee-4911-832a-b4286d0e0871)

- Grant Consent

![image](https://github.com/user-attachments/assets/73ec4430-c1e2-43a8-9058-f5da52d7ae95)

- Note Workspace ID
 
![image](https://github.com/user-attachments/assets/a9ee09d7-b033-4bbf-940d-10b457c768f0)


- IAM:  Adding Role & Role Selection

![image](https://github.com/user-attachments/assets/9128cd32-f475-48f1-add1-31543f8ea2af)
![image](https://github.com/user-attachments/assets/4e7a72b8-b6b2-40ca-acb4-f1b2de9896e4)
![image](https://github.com/user-attachments/assets/e4b1bfd9-fd6a-4fb8-9ab2-1fd147f83bd2)

- Entra ID Diagnostic Setting
![image](https://github.com/user-attachments/assets/84445399-668a-4097-9a2a-c490e9c8c962)


- Client Secret key Creation

![image](https://github.com/user-attachments/assets/6afa0157-2474-4fc2-994f-1994676a0162)

- Audit Log Query

![image](https://github.com/user-attachments/assets/9e1744ce-d0ee-476e-a8e4-d6467bc2d79a)

**Comment by ofvyn** [comment]
# Wazuh Agent Test: Graph, Log Analytics, and Storage integrations Tests

<details><summary>Agent Configuration:</summary>

- Installing Dependencies:

```bash


[root@ip-172-31-47-136 ec2-user]# yum update && yum install python3
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                       | 3.6 kB  00:00:00
amzn2extra-docker                                                                                | 2.9 kB  00:00:00
amzn2extra-kernel-5.10                                                                           | 3.0 kB  00:00:00
wazuh                                                                                            | 3.5 kB  00:00:00
No packages marked for update
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package python3-3.7.16-1.amzn2.0.6.x86_64 already installed and latest version
Nothing to do
[root@ip-172-31-47-136 ec2-user]# yum update && yum install python3
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
amzn2-core                                                                                       | 3.6 kB  00:00:00
amzn2extra-docker                                                                                | 2.9 kB  00:00:00
amzn2extra-kernel-5.10                                                                           | 3.0 kB  00:00:00
wazuh                                                                                            | 3.5 kB  00:00:00
No packages marked for update
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package python3-3.7.16-1.amzn2.0.6.x86_64 already installed and latest version
Nothing to do
[root@ip-172-31-47-136 ec2-user]# yum update && yum install python3-pip
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
No packages marked for update
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package python3-pip-20.2.2-1.amzn2.0.6.noarch already installed and latest version
Nothing to do
[ec2-user@ip-172-31-47-136 ~]$ sudo pip3 install azure-storage-blob==12.20.0 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certifi==2022.12.07 chardet==3.0.4 idna==2.9 urllib3==1.26.18 SQLAlchemy==2.0.23 pytz==2020.1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
ERROR: Could not find a version that satisfies the requirement azure-storage-blob==12.20.0 (from versions: 0.37.0, 0.37.1, 1.0.0, 1.1.0, 1.2.0rc1, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 2.0.0, 2.0.1, 2.1.0, 12.0.0b1, 12.0.0b2, 12.0.0b3, 12.0.0b4, 12.0.0, 12.1.0, 12.2.0, 12.3.0, 12.3.1, 12.3.2, 12.4.0b1, 12.4.0, 12.5.0, 12.6.0b1, 12.6.0, 12.7.0b1, 12.7.0, 12.7.1, 12.8.0b1, 12.8.0, 12.8.1, 12.9.0b1, 12.9.0, 12.10.0b1, 12.10.0b2, 12.10.0b3, 12.10.0b4, 12.10.0, 12.11.0, 12.12.0b1, 12.12.0, 12.13.0b1, 12.13.0, 12.13.1, 12.14.0b1, 12.14.0b2, 12.14.0, 12.14.1, 12.15.0b1, 12.15.0, 12.16.0b1, 12.16.0, 12.17.0b1, 12.17.0, 12.18.0b1, 12.18.0, 12.18.1, 12.18.2, 12.18.3, 12.19.0b1, 12.19.0, 12.19.1)
ERROR: No matching distribution found for azure-storage-blob==12.20.0

[ec2-user@ip-172-31-47-136 ~]$ sudo pip3 install azure-storage-blob==12.19.1 azure-storage-common==2.1.0 azure-common==1.1.25 cryptography==3.3.2 cffi==1.14.4 pycparser==2.20 six==1.14.0 python-dateutil==2.8.1 requests==2.25.1 certifi==2022.12.07 chardet==3.0.4 idna==2.9 urllib3==1.26.18 SQLAlchemy==2.0.23 pytz==2020.1
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting azure-storage-blob==12.19.1
  Downloading azure_storage_blob-12.19.1-py3-none-any.whl (394 kB)
     |████████████████████████████████| 394 kB 23.2 MB/s
Collecting azure-storage-common==2.1.0
  Downloading azure_storage_common-2.1.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 6.9 MB/s
Collecting azure-common==1.1.25
  Downloading azure_common-1.1.25-py2.py3-none-any.whl (12 kB)
Collecting cryptography==3.3.2
  Downloading cryptography-3.3.2-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
     |████████████████████████████████| 2.6 MB 31.0 MB/s
Collecting cffi==1.14.4
  Downloading cffi-1.14.4-cp37-cp37m-manylinux1_x86_64.whl (402 kB)
     |████████████████████████████████| 402 kB 34.9 MB/s
Collecting pycparser==2.20
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 39.7 MB/s
Collecting six==1.14.0
  Downloading six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting python-dateutil==2.8.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 32.0 MB/s
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 12.3 MB/s
Collecting certifi==2022.12.07
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 24.8 MB/s
Collecting chardet==3.0.4
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 37.8 MB/s
Collecting idna==2.9
  Downloading idna-2.9-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 8.5 MB/s
Collecting urllib3==1.26.18
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
     |████████████████████████████████| 143 kB 41.4 MB/s
Collecting SQLAlchemy==2.0.23
  Downloading SQLAlchemy-2.0.23-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 38.0 MB/s
Collecting pytz==2020.1
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 37.0 MB/s
Collecting isodate>=0.6.1
  Downloading isodate-0.7.2-py3-none-any.whl (22 kB)
Collecting typing-extensions>=4.3.0
  Downloading typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting azure-core<2.0.0,>=1.28.0
  Downloading azure_core-1.30.1-py3-none-any.whl (193 kB)
     |████████████████████████████████| 193 kB 40.2 MB/s
Collecting greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))
  Downloading greenlet-3.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (602 kB)
     |████████████████████████████████| 602 kB 28.7 MB/s
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-6.7.0-py3-none-any.whl (22 kB)
Collecting zipp>=0.5
  Downloading zipp-3.15.0-py3-none-any.whl (6.8 kB)
Installing collected packages: pycparser, cffi, six, cryptography, isodate, typing-extensions, urllib3, certifi, idna, chardet, requests, azure-core, azure-storage-blob, python-dateutil, azure-common, azure-storage-common, greenlet, zipp, importlib-metadata, SQLAlchemy, pytz
  WARNING: The script chardetect is installed in '/usr/local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed SQLAlchemy-2.0.23 azure-common-1.1.25 azure-core-1.30.1 azure-storage-blob-12.19.1 azure-storage-common-2.1.0 certifi-2022.12.7 cffi-1.14.4 chardet-3.0.4 cryptography-3.3.2 greenlet-3.1.1 idna-2.9 importlib-metadata-6.7.0 isodate-0.7.2 pycparser-2.20 python-dateutil-2.8.1 pytz-2020.1 requests-2.25.1 six-1.14.0 typing-extensions-4.7.1 urllib3-1.26.18 zipp-3.15.0

```

**Comment by fdalmaup** [comment]
# Review

- Regarding the unsuccessful Microsoft Graph test case found [here](https://github.com/wazuh/wazuh/issues/26422#issuecomment-2429614901), have you created a new user in Azure as described in the [Use Case](https://documentation-dev.wazuh.com/v4.10.0-alpha2/cloud-security/azure/activity-services/entra/graph.html#microsoft-graph-use-case) to trigger the alert or any other action after setting the module?
-  In [Wazuh Agent Test: Graph, Log Analytics, and Storage integrations Tests](https://github.com/wazuh/wazuh/issues/26422#issuecomment-2430268370) the Python version being used is 3.7 when the [documentation](https://documentation-dev.wazuh.com/v4.10.0-alpha2/cloud-security/azure/activity-services/prerequisites/dependencies.html#python) states that the module is compatible with Python 3.8 - 3.11. If you find the same error, please open an issue in the `wazuh/wazuh` repository for the team to work on it.

**Comment by ofvyn** [comment]
Hi @fdalmaup 

- Regarding the Microsoft Graph, Devops have now assisted with creating the user as i do not have sufficient privileges. However, the event still wasn't reported by Graph but was reported by Storage. Please find screenshot below

![image](https://github.com/user-attachments/assets/c4e2d5a8-2888-47f7-a232-c5a9354e030a)

**Comment by fdalmaup** [comment]
# Review 

The reported errors are related to different components:
- [The first one](https://github.com/wazuh/wazuh/issues/26422#issuecomment-2429614901) is related to the Graph alerts not being triggered in the Wazuh Server and not shown in dashboard. 
- [The other one](https://github.com/wazuh/wazuh/issues/26422#issuecomment-2430268370) is related to the Azure module execution in the Wazuh Agent and its failure, not related to the alerts themselves.
Since the problems are not mutually related, these require different issues detailing the found behavior following the lineups mentioned `Reporting New Issues` bullet of the testing [issue description](https://github.com/wazuh/wazuh/issues/26422#issue-2601672981).

**Comment by fdalmaup** [comment]
# Review

LGTM

**Comment by rauldpm** [comment]
# Wazuh setup

https://github.com/wazuh/wazuh/issues/26422#issuecomment-2427714378

```
[root@ip-172-31-35-94 ec2-user]#curl -sO https://packages.wazuh.com/4.10/wazuh-certs-tool.sh
[root@ip-172-31-35-94 ec2-user]#curl -sO https://packages.wazuh.com/4.10/config.yml
[root@ip-172-31-35-94 ec2-user]# bash wazuh-certs-tool.sh -A
21/10/2024 23:56:54 INFO: Verbose logging redirected to /home/ec2-user/wazuh-certificates-tool.log
21/10/2024 23:56:55 INFO: Generating the root certificate.
21/10/2024 23:56:55 INFO: Generating Admin certificates.
21/10/2024 23:56:55 INFO: Admin certificates created.
21/10/2024 23:56:55 INFO: Generating Wazuh indexer certificates.
21/10/2024 23:56:56 INFO: Wazuh indexer certificates created.
21/10/2024 23:56:56 INFO: Generating Filebeat certificates.
21/10/2024 23:56:57 INFO: Wazuh Filebeat certificates created.
21/10/2024 23:56:57 INFO: Generating Wazuh dashboard certificates.
21/10/2024 23:56:57 INFO: Wazuh dashboard certificates created.
```

The above command is an impossible execution, as that script is not present in the packages.wazuh.com bucket, how did you get the correct output of the command execution, paste the correct output, but use the wrong command? I want to think that you pasted the command provided in the documentation, which is indicated to be modified, if you copied the command output, why didn't you copy the command executed too?


```
╰─➤  curl -sO https://packages.wazuh.com/4.10/wazuh-certs-tool.sh
╰─➤  cat wazuh-certs-tool.sh                                                                                                                                                                                 130 ↵
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>4.10/wazuh-certs-tool.sh</Key><RequestId>GJHBGB8GBK5BWJDF</RequestId><HostId>dkD5AU6lfSiMT5qjZh1dZqtYJ4T4FSHRakrv6YlMsBzh723cy3ip+RbndyacogHlXk5y+nhPC/A=</HostId></Error>%   
```

**Comment by ofvyn** [comment]
Hi  @rauldpm 

It appears the URL I actually used was this: curl -sO https://packages-dev.wazuh.com/4.10/wazuh-certs-tool.sh as the earlier wasn't yielding results.

Apologies for the mix up.
