### ISSUE TITLE
Release 4.10.0 - Alpha 2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#26425]
The following issue will gather all the info regarding testing and fixing in order to validate this release stage.

The definition of done for this task is the validation from the product owner of each QA analysis and the acceptance of the implemented fixes, all the issues from below must be closed.

## QA testing issues

In order to move to a new stage or the GA version, all tests and metrics analyses below must be in Closed status.

| Name                        | Issue                                         | Status      |DRI|
|-----------------------------|-----------------------------------------------|-------------|---|
| Footprint metrics | - |:white_circle: Skipped  |@wazuh/devel-qa|
| C unit | #26427 |:purple_circle: Completed |@wazuh/devel-agent|
| Python unit | https://github.com/wazuh/wazuh/issues/26449 | :red_circle: Completed with failures |@wazuh/devel-pyserver|
| Ruleset | https://github.com/wazuh/wazuh/issues/26483 | :purple_circle: Completed |@wazuh/devel-threatintel|
| Coverity scan | #26428 |:purple_circle: Completed |@wazuh/devel-agent|
| Packages | https://github.com/wazuh/wazuh/issues/26432 | :red_circle: Completed with failures|@wazuh/devel-qa|
| Installation assistant | https://github.com/wazuh/wazuh/issues/26446 | :red_circle: Completed with failures | @wazuh/devel-devops|
| WPK agent upgrade | #26458 | :red_circle: Completed with failures |@wazuh/devel-agent|
| Docker and Kubernetes upgrade | #26443 | :red_circle: Completed with failures |@wazuh/devel-devops|
| Agent integration | #26429 |  :purple_circle: Completed  |@wazuh/devel-agent|
| Cppserver integration | #26426 |  :orange_circle: Completed with accepted known issues (old)  |@wazuh/devel-cppserver|
| Pyserver integration | https://github.com/wazuh/wazuh/issues/26450 | :purple_circle: Completed  |@wazuh/devel-pyserver|
| API integration | https://github.com/wazuh/wazuh/issues/26451 | :purple_circle: Completed |@wazuh/devel-pyserver|
| External integrations modules | https://github.com/wazuh/wazuh/issues/26445 |:purple_circle: Completed| @wazuh/devel-pyserver|
| System | #26471 | :orange_circle: Completed with accepted known issues (old) | @wazuh/devel-qa|
| Workload benchmarks | #26457 | :red_circle: Completed with failures |@wazuh/devel-pyserver|
| Demo uses cases | https://github.com/wazuh/wazuh/issues/26447 |:red_circle: Completed with failures |@wazuh/devel-devops|
| UI regression | https://github.com/wazuh/wazuh/issues/26431 | :red_circle: Completed with failures | @wazuh/devel-dashboard|
| Vulnerability detection | https://github.com/wazuh/wazuh/issues/26474 | :red_circle: Completed with failures | @wazuh/devel-qa|
| E2E UX | https://github.com/wazuh/wazuh/issues/26424 | :red_circle: Completed with failures | @wazuh |

:white_circle: Skipped: The task has been deemed unnecessary for this stage.
:brown_circle:  Partially skipped:  Some parts of the task are skipped.
:black_circle: Not finished: The tasks haven't been finished yet.
:purple_circle: Completed: Task finished with success. Nothing to do here.
:red_circle: Completed with failures: Some issues were raised here.
:yellow_circle: Completed with accepted known issues (new): Some issues were raised here, they were deemed non stopper.
:orange_circle: Completed with accepted known issues (old): Some older known issues appeared here, they were deemed non stopper.

**Comment by rauldpm** [comment]
## New issues

- https://github.com/wazuh/internal-devel-requests/issues/1691#issuecomment-2432339602
- https://github.com/wazuh/wazuh/issues/26466
