### ISSUE TITLE
Vulnerability tab not updated, old data are shown 

### ISSUE THREAD

**Issue by nobe80** [wazuh/wazuh#26454]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.9.1 | wazuh-dashboard - vulnerability scanner | Manager | Packages | Ubuntu 24.04 + 22.04 |

Since Update to 4.9.0 we do not have fresh data in vulnerability tab in Wazuh dashboard. There are old data shown and also agents that are deleted since weeks. When i filter for new agent there are no data.

In ossec Lofgile i have this error:
wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: While opening a file for sequentially reading: queue/vd/event

Are there any possibilities to delete the old agents in vulnerability tab?

**Comment by Morzomb** [comment]
I have same problem

**Comment by sebasfalcone** [comment]
@Morzomb @nobe80 Hi, thanks for reporting this issue

I will need both to share with us the DBs for further analysis:
- /var/ossec/queue/vd/delayed
- /var/ossec/queue/vd/event
- /var/ossec/queue/vd/inventory
- /var/ossec/queue/vd/reports
- /var/ossec/queue/vd/state_track

If you want to share the information privately, here is my email: sebastian.falcone@wazuh.com

**Comment by nobe80** [comment]
> @Morzomb @nobe80 Hi, thanks for reporting this issue
> 
> I will need both to share with us the DBs for further analysis:
> 
>     * /var/ossec/queue/vd/delayed
> 
>     * /var/ossec/queue/vd/event
> 
>     * /var/ossec/queue/vd/inventory
> 
>     * /var/ossec/queue/vd/reports
> 
>     * /var/ossec/queue/vd/state_track
> 
> 
> If you want to share the information privately, here is my email: [sebastian.falcone@wazuh.com](mailto:sebastian.falcone@wazuh.com)

Dear Sebastian, 

i send you the logfiles to your email adress.

regards

**Comment by PeriodCorrect** [comment]
Got the same issue:

2024/10/26 13:30:39 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-wazuh-server', retrying until the connection is successful.
2024/10/26 13:30:39 wazuh-modulesd:vulnerability-scanner: ERROR: VulnerabilityScannerFacade::start: Failed to open RocksDB database. Reason: While opening a file for sequentially reading: queue/vd/event/MANIFEST-000005: No such file or directory.

Vulnerability logging stopped thr 17th of October. I can see the latest events are from a 4.9.0 agent. It all came to a halt when I upgraded server and agents to 4.9.1.

Content of the event folder:

[root@wazuh-server event]# ls -l
total 25092
-rw-r--r-- 1 root root     1553 Oct 11 22:06 000042.sst
-rw-r--r-- 1 root root     1004 Oct 12 16:17 000045.sst
-rw-r--r-- 1 root root     6208 Oct 12 16:19 000050.sst
-rw-r--r-- 1 root root 25639310 Oct 20 13:01 000055.log
-rw-r--r-- 1 root root     5076 Oct 17 09:32 000056.sst
-rw-r--r-- 1 root root       16 Oct 12 16:20 CURRENT
-rw-r--r-- 1 root root       36 Oct 12 16:20 IDENTITY
-rw-r--r-- 1 root root        0 Oct 12 16:20 LOCK
-rw-r--r-- 1 root root        0 Oct 26 13:30 LOG
-rw-r--r-- 1 root root        0 Oct 12 16:20 LOG.old.1729429399859846
-rw-r--r-- 1 root root        0 Oct 20 13:03 LOG.old.1729429586420291
-rw-r--r-- 1 root root        0 Oct 20 13:06 LOG.old.1729681649063800
-rw-r--r-- 1 root root        0 Oct 23 11:07 LOG.old.1729949439286712
-rw-r--r-- 1 root root      471 Oct 20 13:01 MANIFEST-000052
-rw-r--r-- 1 root root     7071 Oct 12 16:17 OPTIONS-000049
-rw-r--r-- 1 root root     7071 Oct 12 16:19 OPTIONS-000054

**Comment by nobe80** [comment]
Hi @sebasfalcone ,

did you received my email with the logs?

regards

**Comment by sebasfalcone** [comment]
@nobe80 Yes! I will analyze the DBs

**Comment by nobe80** [comment]
> @nobe80 Yes! I will analyze the DBs

perfect thanks! If you need any further infos or help, pls let me know.

**Comment by sebasfalcone** [comment]
## Update
Tomorrow I will come up with a proposal on how to fix this issue

**Comment by PeriodCorrect** [comment]
I use the Wazuh OVF. Port 9200 is not listening on the IP adres of the host. Changing it to 127.0.0.1:9200 did work.

After inplementing the fix I can now see new events come in. Thank you very much for the fix!

**Comment by Damian-Mangold** [comment]
I closed it because it had been inactive for more than 7 days. Please reopen it if necessary.

**Comment by nobe80** [comment]
> ## Update
> 
> DBs analyzed, the problem is related to this issue:
> 
>     * [Vulnerability scanner shows RocksDB errors during startup #24151](https://github.com/wazuh/wazuh/issues/24151)
> 
> 
> This will be fixed in 4.10.0
> ## Workaround
> 
> Warning
> 
> Please note that this procedure is specific to this situation due to the actions taken previously.
> ### Here's what we need to do:
> #### 1. Stop the Wazuh manager
> 
> ```shell
> systemctl stop wazuh-manager
> ```
> 
> #### 2. Disable the Vulnerability Detector module
> 
> Edit the configuration file to disable this module:
> 
> ```shell
> nano /var/ossec/etc/ossec.conf
> ```
> 
> And set the module to disabled:
> 
> ```
> <vulnerability-detector>
>   <enabled>no</enabled>
>   
> </vulnerability-detector>
> ```
> 
> #### 3. Remove the state databases
> 
> Clear out the existing state databases:
> 
> ```shell
> rm -rf /var/ossec/queue/vd/inventory/
> rm -rf /var/ossec/queue/vd/delayed/
> rm -rf /var/ossec/queue/vd/event/
> rm -rf /var/ossec/queue/indexer/
> ```
> 
> #### 4. Clean the vulnerabilities index
> 
> Delete the existing vulnerabilities index using this command:
> 
> ```shell
> curl -X DELETE "https://<INDEXER_IP>:9200/wazuh-states-vulnerabilities-*/" -u <INDEXER_USER>:<INDEXER_PASSWORD> -k
> ```
> 
> Ensure you replace `<INDEXER_IP>`, `<INDEXER_USER>`, and `<INDEXER_PASSWORD>` with your actual Indexer IP, username, and password.
> 
> You should receive
> 
> ```
> {"acknowledged":true}
> ```
> 
> #### 5. Verify that the index is clean
> 
> Check if the index has been cleared properly:
> 
> ```shell
> curl -X GET "https://<INDEXER_IP>:9200/wazuh-states-vulnerabilities-*/_count" -u <INDEXER_USER>:<INDEXER_PASSWORD> -k
> ```
> 
> You should receive
> 
> ```
> {"count":0,"_shards":{"total":0,"successful":0,"skipped":0,"failed":0}}
> ```
> 
> #### 6. Start and configure the manager
> 
> Restart the manager and enable the Vulnerability Detector module:
> 
> ```shell
> systemctl start wazuh-manager
> ```
> 
> Then enable the module again:
> 
> ```shell
> nano /var/ossec/etc/ossec.conf
> ```
> 
> Set the module back to enabled:
> 
> ```
> <vulnerability-detector>
>   <enabled>yes</enabled>
>   
> </vulnerability-detector>
> ```
> 
> #### 7. Restart the manager one more time
> 
> ```shell
> systemctl restart wazuh-manager
> ```

Hi @sebasfalcone,

thanks! This worked for me and i can see new vulnerabilities in the Event tab of vulnerability section.

regards

**Comment by nobe80** [comment]
Dear @sebasfalcone ,

unfortunately the issue is back again. We do not get updated informations in vulnerability tab. There we have always old informations that have already been fixed. :-/

What can we do?

regards

**Comment by sebasfalcone** [comment]
Hi @nobe80, how are you doing? 

This problem is most probably related to this issue:
- https://github.com/wazuh/wazuh/issues/26806

This will be fixed in `4.10.0` which is just around the corner

---

To validate my hypothesis, can you share the content of the `/var/ossec/queue/indexer/` directory with me?

Here is my email if you want to send it privately: sebastian.falcone@wazuh.com

**Comment by nobe80** [comment]
Hi @sebasfalcone,

thanks i am fine :) Hope you too!

Thank you i will wait for 4.10.0 and hope the issues with vulnerability scanner will ends then.

Have a good time!

**Comment by sebasfalcone** [comment]
> Thank you i will wait for 4.10.0 and hope the issues with vulnerability scanner will ends then.

We hope so, we are doing our best to polish the rough corners. I am generating a troubleshooting guide in our documentation, so you will be able to fix this issue once 4.10.0 is released
