### ISSUE TITLE
Release 4.10.0 - Alpha 2 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#26477]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |          https://github.com/wazuh/wazuh/issues/26425               |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/26474                      |
| **Version**                          |                   4.10.0                         |
| **Release stage**              |                   Alpha 2                     |
| **Tag**                              |          https://github.com/wazuh/wazuh/tree/v4.10.0-alpha2                               |
| **Previous Vulnerability performance tests issue**      |     https://github.com/wazuh/wazuh/issues/26172                 |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 10 | 3 | 20000 | 1 | 1h |

### Test parameters

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha2`
- JENKINS_REFERENCE: `v4.10.0-alpha2`
- QA_REFERENCE: `v4.10.0-alpha2`
- TEST_TIME: (As specified in test cases: 3h -> `10800`, 1h -> `3600`)
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: (As specified in test cases)
- MANAGER_WORKERS: (As specified in test cases)
- INDEXER_NODES: (As specified in test cases)
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: (`Twice` the number specified in the test cases)
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

### Test considerations

- Test frequency: 60
- Number of vulnerable packages: 100

### Builds

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/766/
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/767/
- Very High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/768/

## Conclusion 
New issue
- https://github.com/wazuh/wazuh-jenkins/issues/7051

**Comment by pro-akim** [comment]
Medium Build Failed: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/766/

```
12:12:44  + aws --region us-east-1 ecs describe-tasks --cluster QAPerformance --tasks arn:aws:ecs:us-east-1:966237403726:task/QAPerformance/1a7e87adbf2f484b988f6b77dd6668a9
12:12:45  [Pipeline] readJSON
12:12:45  [Pipeline] }
12:12:45  ERROR: Execution failed
12:12:45  org.wazuh.JenkinsException: Error deploying task.
12:12:45  	at org.wazuh.ECSTask.run(ECSTask.groovy:219)
12:12:45  	at ___cps.transform___(Native Method)
12:12:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
12:12:45  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
12:12:45  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
12:12:45  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
12:12:45  	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
12:12:45  	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
12:12:45  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
12:12:45  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
12:12:45  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
12:12:45  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
12:12:45  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
12:12:45  	at jdk.internal.reflect.GeneratedMethodAccessor1465.invoke(Unknown Source)
12:12:45  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:12:45  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
12:12:45  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
12:12:45  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
12:12:45  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
12:12:45  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
12:12:45  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
12:12:45  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
12:12:45  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
12:12:45  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:403)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:97)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:315)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:279)
12:12:45  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
12:12:45  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:12:45  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
12:12:45  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
12:12:45  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
12:12:45  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
12:12:45  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:12:45  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:12:45  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:12:45  	at java.base/java.lang.Thread.run(Thread.java:829)
```

It seems that Agents could not be simulated:
```
12:15:13  INFO: ENVIRONMENT HEALTH CHECK REPORT
12:15:13  Registered agents = 0
12:15:13  Active agents = 0
12:15:13  Never connected agents = 0
```

**Comment by rauldpm** [comment]
To be launched again in Alpha 3 when the issue https://github.com/wazuh/wazuh-jenkins/issues/7051 is completed
