### ISSUE TITLE
Using ossec-logtest to test the new Windows EventChannel logs

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#2648]
Hi team,

As you may know, `ossec-logtest` is one of the most useful tools while creating your own custom rules.

With the new 3.8.2 `Windows Eventchannel` events internally coded in C to be parsed as json, it is impossible to test their behavior using `ossec-logtest`.

It would be great if we could find a solution to make logtest compatible with these logs by using the json generated from the Windows log:

![imagen](https://user-images.githubusercontent.com/37381070/53090336-5fd3ac00-350f-11e9-871d-d8a659035ec3.png)

Best regards,
Miguel

**Comment by teb1z** [comment]
I agree. This is caused because the actual log from agent contains more than this *"full_log"* you tried to test. I think you can do the log-test if you add this

`{"timestamp":"2019-02-27T13:39:53.932+0000","agent":{"id":"046","name":"abc","ip":"1.1.1.1"},"manager":{"name":"abc"},"id":"111111.111","full_log":"{\"EventChannel\":{\"System\":...`

**Comment by chemamartinez** [comment]
Let me close this issue. You can track the progress at https://github.com/wazuh/wazuh/issues/2765 which is generic for all the C-decoders.

Regards.

**Comment by biancaasan** [comment]
Hi! I have the following log {"Id":3,"Version":5,"Qualifiers":null,"Level":4,"Task":3,"Opcode":0,"Keywords":-9223372036854775808,"RecordId":4642,"ProviderName":"Microsoft-Windows-Sysmon","ProviderId":"5770385f-c22a-43e0-bf4c-06f5698ffbd9","LogName":"Microsoft-Windows-Sysmon/Operational","ProcessId":2168,"ThreadId":1408,"MachineName":"DESKTOP-31QQ5SI","UserId":{"BinaryLength":12,"AccountDomainSid":null,"Value":"S-1-5-18"},"TimeCreated":"\/Date(1618504493804)\/","ActivityId":null,"RelatedActivityId":null,"ContainerLog":"c:\\users\\40725\\desktop\\regsvr32ok.evtx","MatchedQueryIds":[],"Bookmark":{},"LevelDisplayName":"Information","OpcodeDisplayName":"Info","TaskDisplayName":"Network connection detected (rule: NetworkConnect)","KeywordsDisplayNames":[],"Properties":[{"Value":"technique_id=T1218.010,technique_name=Regsvr32"},{"Value":"2021-04-15 16:34:52.026"},{"Value":"b87c6baf-6b2a-6078-e901-000000001200"},{"Value":7452},{"Value":"C:\\Windows\\System32\\regsvr32.exe"},{"Value":"DESKTOP-31QQ5SI\\40725"},{"Value":"tcp"},{"Value":true},{"Value":false},{"Value":"192.168.180.133"},{"Value":"DESKTOP-31QQ5SI.localdomain"},{"Value":62679},{"Value":"-"},{"Value":false},{"Value":"185.199.110.133"},{"Value":"-"},{"Value":443},{"Value":"https"}],"Message":"Network connection detected:\r\nRuleName: technique_id=T1218.010,technique_name=Regsvr32\r\nUtcTime: 2021-04-15 16:34:52.026\r\nProcessGuid: {b87c6baf-6b2a-6078-e901-000000001200}\r\nProcessId: 7452\r\nImage: C:\\Windows\\System32\\regsvr32.exe\r\nUser: DESKTOP-31QQ5SI\\40725\r\nProtocol: tcp\r\nInitiated: true\r\nSourceIsIpv6: false\r\nSourceIp: 192.168.180.133\r\nSourceHostname: DESKTOP-31QQ5SI.localdomain\r\nSourcePort: 62679\r\nSourcePortName: -\r\nDestinationIsIpv6: false\r\nDestinationIp: 185.199.110.133\r\nDestinationHostname: -\r\nDestinationPort: 443\r\nDestinationPortName: https"}
![log](https://user-images.githubusercontent.com/33804961/115005069-28bf7200-9eb0-11eb-93b2-8beb0e193112.PNG)

What can I do test it?
