### ISSUE TITLE
Vulnerability Detection - Incorrect formatting

### ISSUE THREAD

**Issue by jcopling** [wazuh/wazuh#26491]
|Wazuh version - 4.8.2 | Component - Vulnerability Detection | Platform -  Linux|
|---|---|---|---|---|
| 4.8.2-1 | Vulnerability Detection | Manager |

The vulnerability detection module in 4.8.2 while searching inventory has incorrect formatting. 

When using the ability to export vulnerability inventory, the option is for "Export Formated" rather than "Export Formatted"

![Wauzh-Vuln-bug](https://github.com/user-attachments/assets/019ebe26-d648-4bef-b22f-77fd11220b6b)

**Comment by asteriscos** [comment]
This has been fixed in [this](https://github.com/wazuh/wazuh-dashboard-plugins/pull/7081) pull request. I will close this issue.
