### ISSUE TITLE
Syslog Server

### ISSUE THREAD

**Issue by guilhermebasalia** [wazuh/wazuh#265]
Which the Syslog server tool (ex. Rsyslog, Syslog-NG, etc) the Wazuh Agent can read the log files and send to manager?

**Comment by vikman90** [comment]
Hi @guilhermebasalia,

If I'm not mistaken, both _RSYSLOG_ and _syslog-ng_ use a log file as output. So you can set up Wazuh agent to monitor those files this way:

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/all.log</location>
</localfile>
```

`/var/log/all.log` is an example of the path to any file you want to monitor. You can get more information at the [Wazuh Documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html).

Hope it help.
Best regards.

**Comment by guilhermebasalia** [comment]
But in both softwares, I applied the same settings but still the Wazuh still does not send the logs.

**Comment by crolopez** [comment]
Hi @guilhermebasalia,

Have you included a localfile block in ossec.conf indicating the path of the log which is written by your server tool? If so, have you checked that the log file is being updated?

If you use the syslog format, each new line in the log will be sent to the manager, without needing a specific format.

Best regards.
