### ISSUE TITLE
Decompress base vulnerability feed during the first start of wazuh-engine

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26524]
## Description

This issue aims to check if `/tmp/wazuh-server/vd_1.0.0_vd_4.10.0.tar.xz` and decompress it. This must be done in runtime (like in 4.8) to not increase the size of installation types such as docker images.

## Expected
- If /tmp/wazuh-server/vd_1.0.0_vd_4.10.0.tar.xz exists decompress it
- Be careful that within the root of the tar.xz, everything is inside the queue folder, which is part of 4.x, what must be copied is the content of the queue folder (vd and vd_updater) to /var/lib/wazuh-server
- No errors.

## Current behavior
- error ```2024-10-24 08:29:18.118 22152:22152 error: Error opening the database: Couldn't find column family: 'vendor_map', trying to re-download the feed.```
- Dangling tmp file in /tmp/wazuh-server

**Comment by sebasfalcone** [comment]
## Note
Take this issue into consideration when applying this changes:
- https://github.com/wazuh/wazuh/issues/25560

**Comment by MiguelazoDS** [comment]
# Update 

By sources work as expected 

![image](https://github.com/user-attachments/assets/fe169c31-b50c-46ce-9a30-de0d9c53be9f)
![image](https://github.com/user-attachments/assets/ff206e7c-4d43-41b9-a6a8-a4361e9a1c25)

**Comment by Dwordcito** [comment]
This is for 5.0 @MiguelazoDS

**Comment by MiguelazoDS** [comment]
Yeap, I noticed later, working on it.

**Comment by MiguelazoDS** [comment]
# Update 

I can not reproduce this error after the changes, 
![image](https://github.com/user-attachments/assets/e9b18f26-0d9c-45ad-8b74-22452cd49a25)

But I don't understand the Decompression log in databaseFeedManager class. 

https://github.com/wazuh/wazuh/blob/fc953956e847967793227d6e5a5d632fb2422edd/src/engine/source/feedmanager/src/databaseFeedManager.cpp#L22-L25

The decompression takes place in vulnerabilityScannerFacade class.

Now we can see the database in the right place, but not because of a decompression, it is opening a new database as expected when using rocksDB

![image](https://github.com/user-attachments/assets/9bc12090-35c6-4908-9146-cde745b92b64)

**Comment by MiguelazoDS** [comment]
# Update 

Decompression tools were added to migrate the logic from the old vulnerabilityScannerFacade to this new refactor. 

Currently, we have two working tools for vulnerability scanner, the legacy (prior 5.0.0) is still being used to generate the database considering the old path (queue). 

I will assume the compressed database format will change to the required one (wazuh-server) and not add any workaround in the code to rename the old folder queue. Changes in the generation database will be required. 

I'll discuss with the team what is the scope of this issue and if these changes are required or I'm not seeing how this new refactor is going.

**Comment by MiguelazoDS** [comment]
# Update 

- Restoring decompression helpers in shared_modules
- Linking libraries

**Comment by MiguelazoDS** [comment]
# Update 

- Code review changes: 
  - Add UTs.
  - Fix target for new libraries added.

**Comment by MiguelazoDS** [comment]
# Update 

- Code review changes: 
  - Add UTs.
  - Fix target for new libraries added. 
  - Fix configuration for LibArchive
  
 Ready for Review again. Waiting for feedback and comments

**Comment by sebasfalcone** [comment]
## ETA update
To accommodate for reviews

**Comment by sebasfalcone** [comment]
## ETA update
Review corresponds to a small refactor, updated ETA accordingly

**Comment by MiguelazoDS** [comment]
# Update 

Redoing the implementation following the Engine development conventions and practices.

**Comment by MiguelazoDS** [comment]
# Update 

Moved interface outside include folders and created new interface target.
