### ISSUE TITLE
wazuh-keystore: What is a column family?

### ISSUE THREAD

**Issue by ilsaloving** [wazuh/wazuh#26549]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | wazuh-keystore | Manager | Packages | Ubuntu |

The documentation for wazuh-keystore (https://documentation.wazuh.com/current/user-manual/reference/tools/wazuh-keystore.html) needs more details.

In particular, what is a column family?  What are the available choices?  What does this allow us to do?  Can we store passwords in this keystore instead of embedding them into configuration files?

**Comment by Dwordcito** [comment]
Hi @ilsaloving 


Currently, the only use given to this tool is to store the credentials of the wazuh-indexer in encrypted form, which are used internally by wazuh to carry the vulnerability detection inventory to the indexer in versions greater than or equal to 4.8, another use it is not given.

**Comment by JcabreraC** [comment]
As @Dwordcito mentioned, this tool is currently only used to store encrypted credentials for the wazuh-indexer, enabling wazuh to transfer the vulnerability detection inventory to the indexer in versions 4.8 and above. No other uses are implemented at this time.

Closing the issue, but please feel free to reopen it if you have further questions on this.
