### ISSUE TITLE
Release xx.xx.xx - xx - Packages tests

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#26569]
### Packages tests information

|||
| :--                              | :--                                                             |
| **Main release stage issue**     | #                                         |
| **Version**                      | xx.xx.xx                                                   |
| **Release stage**                | xx                                                   |
| **Tag**                          | https://github.com/wazuh/wazuh/tree/vxx.xx.xx-xx          |
| **Previous packages metrics**    | #                                               |

---

| Status | Test              | Issue              |
| :--:   | :--               | :--:               |
| :black_circle:     | Deployability | #26572        |
| :black_circle:     | Upgrade | #26570      |
| :black_circle:     | Specific systems | #26571     |

---

Status legend:
:black_circle: - Not started/In progress
:white_circle: - Skipped
:red_circle: - Found new errors/bugs/failures
:yellow_circle: - Found known errors/bugs/failures
:green_circle: - All tests passed

---

## Auditor's validation

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.

- [ ] @wazuh/devel-qa-release

---

**Comment by pro-akim** [comment]
This issue is opened for testing purposes
