### ISSUE TITLE
High increase of wazuhdb queries in master at VD performance tests

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26627]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.9.2  | RC 1   |  Development  |  wazuh-db  | Download/Repository/Sources/Assistant | 

## Description

While analyzing plot in https://github.com/wazuh/wazuh/issues/26617#issuecomment-2444439678, it has been detected a high increase of wazuh-db queries in master compared to previous release.

### Environment

A performance test with 10 workers, 3 indexers and 20000 agents. The pipeline is:
https://github.com/wazuh/wazuh-jenkins/blob/v4.9.2-rc1/jenkins-files/tests/performance/test_cluster.groovy

### Steps to reproduce

1. Go to https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/build?delay=0sec

2. Execute Very High Activity test with the parameters indicated in https://github.com/wazuh/wazuh/issues/26617#issue-2620948775

#### v4.9.2-RC 1

![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/a02be97f-f1b7-4a01-9699-a76848639687)

#### v4.9.1-RC 3

![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/2d9c2a04-3457-4386-8472-61e920c0a924)

### Attachments

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/769

- Build parameters: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/769/parameters/

- Artifacts: 
  - [artifacts1.zip](https://github.com/user-attachments/files/17558429/artifacts1.zip)
  - [artifacts2.zip](https://github.com/user-attachments/files/17558431/artifacts2.zip)
  - [artifacts3.zip](https://github.com/user-attachments/files/17558432/artifacts3.zip)

**Comment by rauldpm** [comment]
Maybe related https://github.com/wazuh/wazuh/issues/26628

**Comment by pereyra-m** [comment]
## Update

I can't find the artifacts related to that plot for `v4.9.1-RC 3`

**Comment by sebasfalcone** [comment]
## Conclusion
This issue is closed related to:
- https://github.com/wazuh/wazuh/issues/26628

[See conclusion](https://github.com/wazuh/wazuh/issues/26628#issuecomment-2449967738)
