### ISSUE TITLE
Copy instead of move defect at the shared library

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#26626]
|Wazuh version|Component|Install type|Source|
|---|---|---|---|
| 4.9.2 RC 1 | Shared library | Manager | #26453 |

The following defect has been reported by Coverity:

> 1601408 [COPY_INSTEAD_OF_MOVE](https://scan7.scan.coverity.com/doc/en/cov_checker_ref.html#static_checker_COPY_INSTEAD_OF_MOVE)
>  copy_constructor_call: client is passed-by-value as parameter to processRead when it could be moved instead.

https://github.com/wazuh/wazuh/blob/205425e75c05a4e4d13a4d66acc63c41e889aa79/src/shared_modules/utils/socketServer.hpp#L109

**Comment by Dwordcito** [comment]
This is a minimal warning, it can be solved later, it is a copy of a structure.

**Comment by GabrielEValenzuela** [comment]
# Update

- Make a fix by adding `std::move`
- Run Coverity scan
