### ISSUE TITLE
Possible crash in Fedora 36 upgrades

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26640]
## Description
During the upgrade tests, it was found that **Fedora 36** managers are susceptible to crashes:
- [4.9.1 => 4.9.2](https://github.com/wazuh/wazuh-jenkins/issues/7062)
- [4.8.0 => 4.9.0](https://github.com/wazuh/wazuh/issues/25572)

These dumps were not found in any other OS, so we could narrow the investigation to this specific environment.

> [!Important]
> [Enable core dumps generation](https://documentation.wazuh.com/current/development/coredump.html) to perform this tests

> [!Note]
> Due to the nature of the tests, we are not able to retrieve the core dumps

## DoD
- [ ] RCA
- [ ] Solution proposed

**Comment by NahuFigueroa97** [comment]
A docker file was built that installs a wazuh manager 4.9.1 on a Fedora 36, ​​in addition to configuring the coredamp and adding an entrypoint that performs the upgrade to 4.9.2 every time a container is instantiated in order to run several containers and see if a core dump occurs.

```
FROM fedora:36

RUN dnf -y install systemd \
    && dnf -y install wget \
    && dnf -y install https://packages.wazuh.com/4.x/yum/wazuh-manager-4.9.1-1.x8

RUN /var/ossec/bin/wazuh-control start

RUN rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH \
    && echo -e '[wazuh]\ngpgcheck=1\ngpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH\nenabled=1\nname=EL-$releasever - Wazuh\nbaseurl=https://packages-dev.wazuh.com/pre-release/yum/\nprotect=1' > /etc/yum.repos.d/wazuh.repo

RUN echo -e 'DumpCore=yes\nDefaultLimitCORE=infinity' >> /etc/systemd/system.conf

RUN mkdir -p /etc/sysctl.d \
    && echo -e 'kernel.core_pattern=/var/lib/coredumps/core-%e-pid%p-time%t\nkernel.core_uses_pid=1\nfs.suid_dumpable=2' > /etc/sysctl.d/core.conf \
    && mkdir -p /var/lib/coredumps \
    && chmod 773 /var/lib/coredumps

ENTRYPOINT ["/bin/bash", "-c", "yum -y install wazuh-manager-4.9.2-1 && /var/ossec/bin/wazuh-control restart && /bin/bash"]
```

```
docker build -t wazuh-fedora36 .
```

```
#!/bin/bash
for i in {1..1000}
do
    echo "Exec conteiner number $i"
    docker run --privileged -it wazuh-fedora36-coredump
done
```

**Comment by JcabreraC** [comment]
Multiple tests have been conducted without replicating the error. 

Additionally, the test where the issue originally occurred does not provide us with any useful information.
