### ISSUE TITLE
Update `POST /events/stateless` endpoint

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26656]
# Description

The modifications carried out in #25620 need to be reviewed and changed accordingly to have consistency between the `/events` endpoints and the expected body and headers and to have a clearer definition of the data that the Wazuh Agent will be able to send and the required one by the Engine. Currently, the  `POST /events/stateless` endpoint expects a body like the following example:
```json
{
    "wazuh": {
        "queue": 50, // Queue number 1-127
        "location": "[003] (agent-name) any->/tmp/syslog.log", // Location
    },
    "event": {
        "original": "orginal message, recollected from the agent", // Original message
    }
}
```

- The `queue` value is not being currently sent by the Agent, we need a clearer definition of it.
- The `location` data provided by the agent does not contain its `id` nor its `name`, and it is being defined in https://github.com/wazuh/wazuh/issues/26568#issuecomment-2448008056 that it will be passed in the `User-Agent` header and part of the JWT token. We need to modify our code to generate the expected format in the value.

- `User-Agent` header will contain the following information:

    - Agent version. Example: 5.0.0
    - Agent type. Example: Endpoint
    - Agent architecture. Example: x86_64
    - Agent platform. Example: Linux 

    Example with the expected format:
    ```User-Agent: WazuhXDR/5.0.0 (Endpoint; x86_64; Linux)```

**Comment by cborla** [comment]
## Stateless: Logcollector
On the agent side, for the logcollector case, the format that the agent can complete is the following. 

```json
{
  "module": { "name": "logcollector" },
  "data": {
    "file": { "path": "/var/log/syslog" },
    "event": { "original": "2024-10-31T16:21:25.198579+01:00 Rocket systemd-resolved[176]: Clock change detected. Flushing caches." }
  }
}
```

The idea is to include the path that was previously used as location inside the data object.

**Comment by fdalmaup** [comment]
Thanks, @cborla :raised_hands:. We are currently awaiting the redefinition of the expected events on behalf of @wazuh/devel-cppserver team which will include the use of JSON streaming.

**Comment by GGP1** [comment]
## Update

Investigated about JSON streaming requests and started making changes to adapt the endpoint to the new requirements.

**Comment by GGP1** [comment]
## Update

Moving to on hold, we need definitions from the Cpp Server team about the Engine `/events/stateless` endpoint and we need the changes to be implemented to be able to test ours.

**Comment by fdalmaup** [comment]
Changing ETA to November 8 due to the need for definitions from the Cpp Server team.

**Comment by fdalmaup** [comment]
The expected request body is the one described https://github.com/wazuh/wazuh-agent/issues/253#issuecomment-2466031714.

**Comment by GGP1** [comment]
## Update

Updated the Content-Type header to `application/x-ndjson` and implemented the logic necessary to relay the stream bytes coming from the agent to the engine.
