### ISSUE TITLE
add external data to vulnerability detection

### ISSUE THREAD

**Issue by MathisLandreau** [wazuh/wazuh#26651]
Hello, the objective would be to provide a CSV or JSON file from the server or an agent. This file would contain information about an OS and a version, or even an OS of software and a version, to be processed by the vulnerability detection module. 

Why do this? To respond to the fact that we can't have agents everywhere, for various reasons (security, co-contracting, etc.).  But also for hardware that can't have an agent (switch, router, etc.).

In short, to be able to give information to the vulnerability detection module in a way other than with agents, simply with a file containing the minimum information required, or detailed information depending on the need.
With this in mind, the traceability option is important, so give a name to the source (e.g. switch-85222) so that, in the event of an alert, it's easy to identify the hardware concerned. 

example of information to be sent:
OS: SonicOS
Maintainer: <<security@sonicwall.com>>
Version: 7.0.1-5035
Description: firewall-26B

**Comment by sebasfalcone** [comment]
@MathisLandreau Hi, how are you doing?

This is a great feature proposal! It won't be easy to implement though. The vulnerability scanner expects a specific format to be provided to interpret the package information, so we should implement a sort of normalizer tool with a comprehensive interface to ingest information and map it against

**Comment by MathisLandreau** [comment]
@sebasfalcone Hi fine and you ? 
I've also been thinking about the deletion/evolution issue.
To avoid duplication ... 

thank you this feature will help me a lot.

**Comment by MathisLandreau** [comment]
@sebasfalcone Hi fine and you ?
I've also been thinking about the deletion/evolution issue.
To avoid duplication ...

thank you this feature will help me a lot.

**Comment by MathisLandreau** [comment]
@sebasfalcone Hi fine and you ?
I've also been thinking about the deletion/evolution issue.
To avoid duplication ...
I closed by accident.

thank you this feature will help me a lot.

**Comment by sebasfalcone** [comment]
> @sebasfalcone Hi fine and you?

I am fine

----

We will see in the future if we can implement this issue, for the time being, it's not on the roadmap. But it will discussed

**Comment by Damian-Mangold** [comment]
I closed it because it had been inactive for more than 7 days. Please reopen it if necessary.
