### ISSUE TITLE
Get the register IP from the global DB when the field IP is NULL

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#2666]
When an agent with lower version than 3.9 is connected to a 3.9 manager, the field IP of the `global.db` is NULL, because in 3.9 there are two IP fields, the current IP and the register IP, and the manager moves the content of `ip` to `register_ip` in order to store the real IP of the agent in `ip`.
Now, when the manager try to send a WPK to the agent, it can't found the `agent-info` file, cause in the line:
https://github.com/wazuh/wazuh/blob/2e470860e88abb5812ac76e252d51345fe160f1e/framework/scripts/agent_upgrade.py#L74
the IP is NULL.
We need to change the function that load the info from the `global.db` to extract the `register_ip` whenever it is going to make/search an `agent-info` file

**Comment by chemamartinez** [comment]
Merged: #2669
