### ISSUE TITLE
Improve daemons CLI parameters usage

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#26693]
## Description

In the development of https://github.com/wazuh/wazuh/issues/26356 some CLI arguments of the Management API, Communications API, and Server process are no longer used:
- `-h --host` and `-p --port`: These parameters were replaced by the `wazuh-server.yml` configuration file and should not be used for log messages as it happens in the `wazuh_comms_apid.py` script which does not take into account the configuration nor the default configuration:
https://github.com/wazuh/wazuh/blob/53d6b6bcb02058ea34a18bc2a1b0308212fe5f92/apis/comms_api/scripts/wazuh_comms_apid.py#L342
- `-t`: The configuration is always validated when the process starts, so there is no need for this parameter.

We should remove these CLI parameters and change the scripts that initialize these processes, adding or changing them.
The following lineups must be followed for each daemon to be executed via CLI (same as the ones to be used by the `wazuh-agent` team [here](https://github.com/wazuh/wazuh-agent/issues/288)):
- **Default foreground execution**: If the daemon is executed without CLI options, it will start the service in the foreground. 
- **Prevent multiple instances**: If the daemon detects that another instance is already running, its execution will be terminated.

**Comment by GGP1** [comment]
## Update

Improved the CLIs behavior consistency , applied the changes necessary to conform with the requirements and removed unnecessary flags.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.

**Comment by GGP1** [comment]
## Update

Applied suggested changes.
