### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement docker==7.1.0

### ISSUE THREAD

**Issue by chantal-kelm** [wazuh/wazuh#26695]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9| Wazuh component | Manager/Agent | Packages/Sources | Amazon Linux 2 |

I followed the following steps to reproduce a community, I set up a Wazuh following the documentation for assisted installation on an Amazon Linux 2 and followed the documentation for [enable the Wazuh Docker listener](https://documentation.wazuh.com/current/user-manual/capabilities/container-security/monitoring-docker.html#enable-the-wazuh-docker-listener).

<img width="1792" alt="Captura de pantalla 2024-11-01 a la(s) 4 15 36 p  m" src="https://github.com/user-attachments/assets/cc3ef0e2-82f5-4c83-a7ad-9d5cd1193825">

This paragraph mentions that Docker container module requires Python 3. Specifically, it is compatible with Python 3.8-3.12. 

<img width="937" alt="image" src="https://github.com/user-attachments/assets/0d93e167-773d-43c8-b4f4-9da6da7e4b7c">

But in the command range the version starts from 3.7.

<img width="984" alt="image" src="https://github.com/user-attachments/assets/a31f71bf-e14f-476d-8053-072cd4c404a7">

I have tested with versions 3.7 and 3.8 and both give the same error reported by the user

<img width="568" alt="Captura de pantalla 2024-11-01 a la(s) 3 46 12 p  m" src="https://github.com/user-attachments/assets/3c2fc7d0-b6fd-40b1-bcff-d7e9513b8193">

**Comment by branchnetconsulting** [comment]
As I mentioned on the community channel, this was attempted on a standard install of Amazon Linux 2 with the standard yum repos and Docker version.  
I'm pretty sure the tab that says Python 3.7-3.10 is a typo and should say Pyuthon 3.8-3.10.  I also did install Python 3.8 in parallel to the standard version and your venv as described in my threat, but could not get the wodle to work.  I look forward to hear what you find.  Thanks in advance.

**Comment by branchnetconsulting** [comment]
So is this just a documentation issue or is it truly not possible at this time to use the Wazuh docker-listener wodle with the 4.9 version of Wazuh agent?

**Comment by javiersanchz** [comment]
## Update

- After speaking with the team, it was decided to update the documentation to show that starting from Python version `3.8`, the version of `urllib3` will be changed to `1.26.20`, as it is compatible with all versions and OSs


It was verified with `Amazon Linux 2`:

```console
[vagrant@localhost ~]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

Python 3.8 was installed:

```console
[root@localhost /]# python3 --version
Python 3.8.12
```
The necessary dependencies were installed with `urllib3=1.26.20`:

```console
 [root@localhost /]# pip3 install docker==7.1.0 urllib3==1.26.20 requests==2.32.2
Collecting docker==7.1.0
  Downloading docker-7.1.0-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 2.2 MB/s 
Collecting urllib3==1.26.20
  Downloading urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
     |████████████████████████████████| 144 kB 2.3 MB/s 
Collecting requests==2.32.2
  Downloading requests-2.32.2-py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 1.9 MB/s 
...

```
```console
[root@localhost /]# python3.8
Python 3.8.12 (default, Nov 20 2024, 11:28:55) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker

[root@localhost /]# python3.8
Python 3.8.12 (default, Nov 20 2024, 11:28:55) 
[GCC 7.3.1 20180712 (Red Hat 7.3.1-17)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
import requests
import urllib3

print(docker.__version__)
print(requests.__version__)
print(urllib3.__version__)
>>> 7.1.0
>>> 2.32.2
>>> 1.26.20
```

**Comment by javiersanchz** [comment]
## Update

It was verified that the Docker listener works in a `4.9` environment as reported in the issue, on an agent with an `Amazon Linux 2` operating system

```console
bash-4.2# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```

### Agent installation

```
bash-4.2# /var/ossec/bin/wazuh-control start
Starting Wazuh v4.9.2...
Started wazuh-execd...
Started wazuh-agentd...
Started wazuh-syscheckd...
Started wazuh-logcollector...
Started wazuh-modulesd...
Completed.
```

### We installed the minimum version of Python `3.8`:

```console
bash-4.2# python3.8 --version
Python 3.8.10
```

### We installed the necessary dependencies:

```console
bash-4.2# pip3 install docker==7.1.0 urllib3==1.26.20 requests==2.32.2
Collecting docker==7.1.0
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting urllib3==1.26.20
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Collecting requests==2.32.2
  Downloading requests-2.32.2-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests==2.32.2)
...
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 docker-7.1.0 idna-3.10 requests-2.32.2 urllib3-1.26.20
```

### We added the configuration:

```console
  <wodle name="docker-listener">
    <interval>1m</interval>
    <attempts>5</attempts>
    <run_on_start>yes</run_on_start>
    <disabled>no</disabled>
  </wodle>
```

### Docker-listener output:

```python
bash-4.2# cat /var/ossec/logs/ossec.log | grep docker-listener
...
2024/11/21 12:14:59 wazuh-modulesd[32099] main.c:95 at main(): DEBUG: Created new thread for the 'docker-listener' module.
2024/11/21 12:14:59 wazuh-modulesd:docker-listener[32099] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/11/21 12:14:59 wazuh-modulesd:docker-listener[32099] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/11/21 12:14:59 wazuh-modulesd:docker-listener[32099] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/11/21 12:19:33 wazuh-modulesd:docker-listener[32099] wm_docker.c:177 at wm_docker_cleanup(): INFO: Module finished.
2024/11/21 12:19:35 wazuh-modulesd[32777] main.c:95 at main(): DEBUG: Created new thread for the 'docker-listener' module.
2024/11/21 12:19:35 wazuh-modulesd:docker-listener[32777] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/11/21 12:19:35 wazuh-modulesd:docker-listener[32777] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/11/21 12:19:35 wazuh-modulesd:docker-listener[32777] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

- As observed, the module is working correctly. The agent was also restarted to check its behavior.
- Possible errors were also checked, but everything is functioning properly.

**Comment by javiersanchz** [comment]
## Update

- The changes mentioned in https://github.com/wazuh/wazuh-documentation/pull/7978#pullrequestreview-2452666008 regarding the Docker documentation were also added.
