### ISSUE TITLE
Enable virus scanning feature

### ISSUE THREAD

**Issue by PhuketIsland** [wazuh/wazuh#26707]
I am currently using version 4.6.0. I noticed there is a VirusTotal module in the configuration module, so I wanted to try using it. However, after I turned on this switch, I found that the feature didn't actually work at all.
![1730773824848](https://github.com/user-attachments/assets/b9a9d78b-c178-4633-bad2-c3cbc8568fc2)
There's no data in it
![image](https://github.com/user-attachments/assets/44d037e5-699d-42b5-a6b2-72de7ae9d22f)
Then I looked at the documentation, which stated that the VirusTotal API is required. Is there no open-source alternative for this?

**Comment by MiguelazoDS** [comment]
Hi @PhuketIsland, 

I don't have in mind an open-source alternative to Virus Total. Your concern is about the request limit of the public VT token or the fact that VT is not an open-source tool?

If you find an alternative, we can try to integrate it. The integration with virus total works through the integrator module, as well as many others, and is customizable.

**Comment by PhuketIsland** [comment]
“Thank you, I currently only need the free version of VirusTotal.”

**Comment by MiguelazoDS** [comment]
Hi @PhuketIsland, 

Could you make it work? could you get the token?

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
