### ISSUE TITLE
all logging stopped after 4.9.2 upgrade

### ISSUE THREAD

**Issue by MROSSFTEK** [wazuh/wazuh#26717]
i was running wazuh OVA version 4.9.0. i took a month off work for a medical procedure, and while i was gone, the logging was running PERFECTLY. 
i did a yum update and yum upgrade on the VM and then after, all the logging stopped for 
FIM
Vulnerability scanning
Office 365

I ran agent upgrades on the clients and even after that, my logging all stopped at 8:34 am 11/4/2024. Is there a post upgrade command, or set of command i should run to fix this? i can see all the services are running properly on the wazuh server. i cannot find any errors with the system. can anyone point me to directions on how to fix this?

**Comment by sebasfalcone** [comment]
Hi @MROSSFTEK hope you are recovering well

Can you share with me the last logs you see?

On the other hand, what happens if you perform a restart of the manager?

**Comment by Damian-Mangold** [comment]
I closed it because it had been inactive for more than 7 days. Please reopen it if necessary.
