### ISSUE TITLE
Engine stateless endpoint request-response schema implementation

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26719]
### Description

This issue aims to readjust the scheme that the engine will receive in 5.0 through the stateless endpoint.

Basically we will receive an ndjson, `Content-Type: application/x-ndjson` and process it.

### Request example
```json
{"agent":{"id":"2887e1cf-9bf2-431a-b066-a46860080f56","name":"javier","type":"endpoint","version":"5.0.0","groups":["group1","group2"],"host":{"hostname":"myhost","os":{"name":"Amazon Linux 2","platform":"Linux"},"ip":["192.168.1.2"],"architecture":"x86_64"}}}
{"module":"logcollector","type":"file"}
{"log": {"file": {"path": "/var/log/apache2/access.log"}}, "base": {"tags": ["production-server"]}, "event": {"original": "::1 - - [26/Jun/2020:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\" 404 209", "ingested": "2023-12-26T09:22:14.000Z", "module": "apache-access", "provider": "file"}}
{"log":{"file":{"path":"string"}},"base":{"tags":"string"},"event":{"original":"string","ingested":"string","module":"string","provider":"string"}}
{"module":"inventory","type":"package"}
{"base":{"tags":"string"},"event":{"original":"string","ingested":"string","module":"string","provider":"string"}}

```

Basically the first line is a header for each message received.
The line 2 and 5 are a subheader of the line 3 and 4(for line 2) and 6(for line 5)

### Exception handling / error response
- Response code 400
### Response
- Response code 200

**Comment by juliancnn** [comment]
## Update

```json
{
    "agent": {
        "id": "2887e1cf-9bf2-431a-b066-a46860080f56",
        "name": "javier",
        "type": "endpoint",
        "version": "5.0.0",
        "groups": [
            "group1",
            "group2"
        ],
        "host": {
            "hostname": "myhost",
            "os": {
                "name": "Amazon Linux 2",
                "platform": "Linux"
            },
            "ip": [
                "192.168.1.2"
            ],
            "architecture": "x86_64"
        }
    }
}
```

Example of event:

```json
{
    "base": {
        "tags": [
            "production-server"
        ]
    },
    "event": {
        "ingested": "2023-12-26T09:22:14.000Z",
        "module": "apache-access",
        "original": "::1 - - [26/Jun/2020:16:16:29 +0200] \"GET /favicon.ico HTTP/1.1\" 404 209",
        "provider": "file"
    },
    "log": {
        "file": {
            "path": "/var/log/apache2/access.log"
        }
    }
}
```

Note some of the updates:
- The agent object
- The `log.file.path` field is optional, as this field is only valid when collecting from a file.
- The `base.tags` field is a string array.
- The `event.ingested` field is a date string with the format '%Y-%m-%dT%H:%M:%SZ' and it is the time when the agent collects the log.

Do not confuse event.module with the module that reads the log (logcollector) but the source of the log, for example, apache-access, apache-error, suricara-alerts, jounarld, windows-event-channel. Whereas the provider can be a file, an eventchannel, or the unit that logs the message in journald.

CC: @wazuh/devel-agent

**Comment by juliancnn** [comment]
## Update

- Added endpoint with the functionality
- Added unit tests to orchestrator

The implementation was completed and according to agreement:
- If the agent header is corrupted, all events are discarded (silently).
- If any event is corrupted, it is ignored and the next one is processed (silently).
- If there is not enough space in the queue to process all the events, the events in the queue are processed, and the rest are discarded. A debug message is issued warning about this and a 200 is returned, i.e., events will be silently lost.
- The scheme is not checked for performance reasons.


### Friendly testing
The testing tool has been updated to bypass port 80 from localhost to unix socket, allowing friendly testing with tools such as postman:
```
go run $ENGINE_SRC/tools/http_bypass.go
```

![image](https://github.com/user-attachments/assets/8af6685c-4f0b-4f2a-aacb-5903acf70490)
