### ISSUE TITLE
Docker listener <run_on_start> option not working

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#2672]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3904 | Manager/Agent | Packages/Sources | Ubuntu 18.04 |

The option `<run_on_start>` for the Docker module is not working, the module starts to listen Docker events once the time established at the `<interval>` field is overtaken.

**Comment by Leamsy** [comment]
Hi @cristgl,

I have tried to replicate the issue but the module does seem to work correctly. When `<run_on_start>` is activated the module does start to listen to Docker events immediately without waiting the assigned interval. And when it is deactivated it waits before it starts reporting, as seen by the logs here:

`2019/02/25 12:30:09 wazuh-modulesd:docker-listener: INFO: Module docker-listener started
2019/02/25 12:30:09 wazuh-modulesd:docker-listener: INFO: Waiting the interval (300 seconds) to run the listener.
`

Best regards.
