### ISSUE TITLE
Support new OSs - Windows Server 2025 - Test VD works properly with new OS

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#26730]
# Description

| Related issue | Epic issue |
|---|---|
| #26715 | #26722 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**CppServer**
- [x] Make sure that VD works properly according to the OS tier.

**Comment by Dwordcito** [comment]
Waiting environment

**Comment by Dwordcito** [comment]
@sebasfalcone talk with devops about that.

**Comment by sebasfalcone** [comment]
## Issue blocked
Awaiting issue resolution
- https://github.com/wazuh/wazuh/issues/26729

**Comment by GabrielEValenzuela** [comment]
# Funtional testing 🟢 

## Steps

- Install agent `4.9.2` on the provided Windows Server 2025 machine
- Enable debug mode 2 on manager and restart
- Connect to manager
- Set syscollector scan to 2min

## Results

### Agent connected

![Image](https://github.com/user-attachments/assets/3eb36017-dc30-4d37-b84b-4ccdf443ea31)

![Image](https://github.com/user-attachments/assets/8a1cffc5-2e02-4ee5-a1d7-727fd0c03ba1)


### Updated content and run scan (See hotfix scan)


![Image](https://github.com/user-attachments/assets/b9178dc2-1a85-4d62-b74a-19ea46bfa9a4)


### Install vulnerable package (`Firefox 65.0`)

![Image](https://github.com/user-attachments/assets/28bc5199-079a-4ddf-9dca-0b288af39590)

![Image](https://github.com/user-attachments/assets/b5e99952-c6ca-45b8-8825-3299f50449b2)

![Image](https://github.com/user-attachments/assets/772053d0-3884-4d51-9655-07f5ee81e79a)


### Upgrade package to the last stable version 

![Image](https://github.com/user-attachments/assets/771e43d4-4f21-4dbb-8b73-8a62eb9e1279)

![Image](https://github.com/user-attachments/assets/ad50f8a9-b0a5-484f-baf9-3c843b85ac96)

![Image](https://github.com/user-attachments/assets/29a1b35d-d290-4233-b3f6-e74b43be10a3)

### Check warning and errors in the log

![Image](https://github.com/user-attachments/assets/2e621d0c-0ecb-46ca-a09a-2995efce483b)

**Comment by sebasfalcone** [comment]
Good work @GabrielEValenzuela 

## Conclusion
- Windows Server 2025 is supported by VD

## Post tasks
@GabrielEValenzuela Please create the sanitization issues for the failing comparisons (check that there are not already existing sanitizations for those CVEs)

**Comment by Dwordcito** [comment]
LGTM
