### ISSUE TITLE
Support new OSs - Fedora 41 - Test agent package

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#26735]
# Description

| Related issue | Epic issue |
|---|---|
| #26715 | #26723 |

| Agent tier | Central components support | OS type |
|-|-|-|
| 1 | No | Major |

# Plan

**Agent**

- [x] Smoke test that the package works, including installation, upgrade, and its related tier functionality.
- [x] Check the default settings of previous versions, and adapt them to the new OS version if necessary.
- [x] Add support for the new OS to the GitHub Actions package builder.

Requested testing code:
:white_circle: Requested.
:black_circle: Not requested.

Result code:
:green_circle: Completed: Test finished with success.
:red_circle: Completed with failures.
:yellow_circle: Completed with known issues.

- **Requested checks by tier:**

|| Tier 1 | Tier 2 | Tier 3 | Result |
|-|-|-|-|-|
| **Log collection - System events** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection - Log files** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Log collection -Command execution** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **FIM - Scheduled** | :white_circle: | :white_circle: | :white_circle: | :green_circle:|
| **FIM - Realtime** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **FIM - Whodata** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **SCA** | :white_circle: | :white_circle: | :black_circle: | 🟡 |
| **Inventory** | :white_circle: | :white_circle: | :white_circle: | :green_circle: |
| **Active response** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Remote upgrade** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |
| **Command monitoring** | :white_circle: | :white_circle: | :black_circle: | :green_circle: |
| **Wodles** | :white_circle: | :black_circle: | :black_circle: | :green_circle: |

**Comment by mjcr99** [comment]
Hi team, 

exhaustive testing was performed on this issue:

* https://github.com/wazuh/wazuh/issues/23661

The agent has been still testing in the released Fedora 41 version with a basic test. Enrolling the agent 4.10.0 with a manager with the same version, everything seems to work properly. No weird logs are found, and the basic functionalities regarding syscheck scans, commands, and logs monitoring have been seen to work with no problem.

**Comment by MarcelKemp** [comment]
LGTM.
