### ISSUE TITLE
Wazuh Queue DB

### ISSUE THREAD

**Issue by taylorwalton** [wazuh/wazuh#26743]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2 | Wazuh Queing| Manager| Packages/Sources | Debian 12 |

Hey Team,

I’ve been noticing that the queue directory where the agent SQLite .db files are stored is consuming quite a bit of space. With 633 agents currently registered, the directory has grown to 45GB, which seems substantial. Is this the kind of disk usage we’d expect with this number of agents, or does it seem a bit high to you?

![image](https://github.com/user-attachments/assets/71b4df73-9ec0-4c93-9e6b-b0fdfd3f013c)

I’m wondering if there’s a configuration adjustment I should consider, or perhaps this is something that has been optimized in newer releases. Would it be worth exploring ways to reduce this footprint, or is increasing disk space the recommended approach?

Looking forward to any insights you can share on this!

Taylor

**Comment by MiguelazoDS** [comment]
Hi @taylorwalton, 

I would say that is expected. You can check here the recommended environment requirements for different numbers of agents. 

https://documentation.wazuh.com/current/quickstart.html#requirements

Personally, I don't consider this unusual.  

We can check the size of each table in any database (I see most of them are around +400M) and try to disable some unneeded modules.

**Comment by MiguelazoDS** [comment]
> I’m curious—when you say it's expected, are you thinking the current setup might still be optimized further by turning off unused modules or tables? Or would it mostly be about balancing storage needs?

Mmm for me the size is coherent with the information we are storing, I don't see any bug or something that could be oversizing the databases for no reason. 

I just was thinking about all these tables in the agent databases and by doing a quick comparison by table size maybe we could've found something. 

```console
root@jammy:/var/ossec/queue/db# sqlite3 001.db '.ta'
ciscat_results        sca_policy            sys_netiface
fim_entry             sca_scan_info         sys_netproto
metadata              scan_info             sys_osinfo
pm_event              sync_info             sys_ports
sca_check             sys_hotfixes          sys_processes
sca_check_compliance  sys_hwinfo            sys_programs
sca_check_rules       sys_netaddr
```

> [!NOTE] 
> For 4.7.x you may found vuln_cves and other tables too.

It seems that the small size for a table is 4096 bytes, which is the pagesize. Then each table can have multiple pages.  

Here I can see that FIM, sys_programs (syscollector) and sca_check are the "bigger" tables. But these are core features of the project, and few people would disable it. sys_programs table is required for vulnerability detector. 

```console
root@jammy:/var/ossec/queue/db# sqlite3 001.db 'select name, sum(pgsize) size from dbstat group by name order by size desc'
fim_entry|888832
fim_type_full_path_checksum_index|241664
fim_type_file_checksum_index|241664
sys_programs|229376
sca_check|204800
fim_type_full_path_index|118784
fim_type_file_index|118784
sqlite_autoindex_fim_entry_1|102400
fim_full_path_index|102400
fim_file_index|102400
sqlite_autoindex_sca_check_compliance_1|90112
sca_check_compliance|86016
sqlite_autoindex_sys_programs_1|45056
sqlite_autoindex_sca_check_rules_1|40960
sca_check_rules|40960
fim_date_index|40960
sys_processes|24576
sqlite_schema|16384
comp_id_check_index|16384
programs_id|12288
sys_ports|4096
```

> [!NOTE] 
> In conclusion I don't see too much improvements, it was an attempt that came to my mind. You can try what table consumes more space in your environment. 

---

> One more thing, with the release of 4.8.1 and newer versions moving vulnerability data storage to the Indexer, I’m wondering if you've noticed a meaningful decrease in disk consumption with the upgrade. What has your experience been with users who have made this upgrade?

One of the key point to address by doing the refactor of the vulnerability detector module in 4.8.0 was to separate the scanner logic from the content logic. 

Prior 4.8.0 the manager downloaded raw data (nvd, ubuntu feed, debian feed, etc) that then was processed by the manager and filling the cve.db database. 
Then the result of the scanner where stored in the agent database (probably with the steps I previously mentioned you can notice a difference in the vuln_cves table size) 
Now as you mentioned that information is stored in the wazuh-indexer, and the indexer is in another machine we can save some space there. 

But we know use the rocksdb database for storing the preprocessed content for the scanner, and that is will consume around 6-7G. 

![image](https://github.com/user-attachments/assets/1629a170-51ff-4023-b44e-d10881377a40)
 
 > [!NOTE]
 > If you can find how much size consumes the vulnerability detector tables in 4.7 plus the cve.db probably we can do some calculations compared to the 4.8.x version, but I wouldn't say that updating to 4.8.x will means a great improvement in saving storage.

**Comment by taylorwalton** [comment]
Hey @MiguelazoDS ,

Thank you for your update. I really appreciate it. It sounds like the best solution is to upgrade the storage which is what I am going to explore.

Thanks again!
