### ISSUE TITLE
Typo in the error message "string not correctly formated"

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#2675]
Hi team,

I have realized there is a typo in the following error message: https://github.com/wazuh/wazuh/blob/dc306353a51cd0651c2367c77fe33c08b09ab44b/src/error_messages/error_messages.h#L22

Should be 
>string not correctly **formatted**

Regards,

Miguel Casares

**Comment by albertomn86** [comment]
Merged
