### ISSUE TITLE
Agent registration refinement

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#26766]
## Description

Due to recent changes in the stateful events agents metadata, we are updating the agent data model used during registration to be consistent across the implementation of both APIs.

The new model will have the following structure:

```json
{
  "agent": {
      "id": "2887e1cf-9bf2-431a-b066-a46860080f56",
      "key": "BfDbq0PpcLl9iWatJjY1shGvuQ4KXyOR",
      "name": "example",
      "type": "endpoint",
      "version": "5.0.0",
      "groups": ["group1", "group2"],  // Optional
      "host": {                        // Optional
          "hostname": "myhost",
          "os": {
              "name": "Amazon Linux 2",
              "platform": "Linux"
          },
          "ip": ["192.168.1.2"],
          "architecture": "x86_64"
      }
  }
}
```

In addition to this, we should send an `update-group` order to the agent if it specified groups during the registration, so it can get the group configuration later.

**Comment by davidjiglesias** [comment]
We should add the agent name when registering:

{
  "agent": {
      "id": "2887e1cf-9bf2-431a-b066-a46860080f56",
      "key": "BfDbq0PpcLl9iWatJjY1shGvuQ4KXyOR",
      "name": "example",
      "type": "endpoint",
      "version": "5.0.0",
      "groups": ["group1", "group2"],
      "host": {
          "hostname": "myhost",
          "os": {
              "name": "Amazon Linux 2",
              "platform": "Linux"
          },
          "ip": "192.168.1.2",
          "architecture": "x86_64"
      }
  }
}

**Comment by GGP1** [comment]
## Update

Updated the `POST /agents` endpoint to take into account the missing agent fields and sent an `update-group` command to the registered agent.

**Comment by GGP1** [comment]
## Update

Applied suggested changes and updated the group queries and scripts to fulfill the requirements of the agents index mapping.

**Comment by GGP1** [comment]
## Update

Created the issue https://github.com/wazuh/wazuh/issues/26847 to use arrays in the agent groups queries and scripts.
