### ISSUE TITLE
#Syscheck - check_sum not working

### ISSUE THREAD

**Issue by yinynick** [wazuh/wazuh#2676]
|Wazuh version|Install type|Install method|Platform|
|3.8.2-1|Manager/Agent|---|Redhat6, Redhat7|

check_all is working well, but check_sum alone will not alert file integrity change.

**Comment by yinynick** [comment]
Update: check_sum works together with check_inode

**Comment by bah07** [comment]
Hi @yinynick 

We are not aware of any problems related to the `check_sum` option. 

Please, could you paste here the configuration you are using (specifically the tag <directories> where you configure the option `check_sum`) and the alert generated by that configuration?

Thanks,
Regards.

**Comment by yinynick** [comment]
Hi,

The configuration is all by default on 3.8.2-1.
1. Below is working well and we can see alert logs when we change a file:
<directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
<directories check_all="yes">/bin,/sbin,/boot</directories>

2. It is not working if we change check_all to check_sum, there is no alert log when we change any file
<directories check_sum="yes">/etc,/usr/bin,/usr/sbin</directories>
<directories check_sum="yes">/bin,/sbin,/boot</directories>

3. There are alert logs again with check_inode together
<directories check_sum="yes" check_inode="yes">/etc,/usr/bin,/usr/sbin</directories>
<directories check_sum="yes" check_inode="yes">/bin,/sbin,/boot</directories>

BTW, there is no issue for check_sum on version 2.6

**Comment by TJOSERAFAEL** [comment]
Hi @yinynick,

first of all, sorry for the late response. We have made some tests with Wazuh 3.8.2 and we get the alerts.

With the same configuration:

```
<directories check_sum="yes">/etc,/usr/bin,/usr/sbin</directories>
<directories check_sum="yes">/bin,/sbin,/boot</directories>
```

And frequency changed to 30 seconds for testing:

```
  <!-- Frequency that syscheck is executed default every 12 hours -->
  <frequency>30</frequency>
```

```
** Alert 1558087562.106570: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 May 17 12:06:02 rafa-GS63-7RD->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/etc/newfile.txt' checksum changed.
Old md5sum was: '057c83ccbd9f91546d1a81a028da46ce'
New md5sum is : '77183b3bcd52f2b6e2a0029ae90584c4'
Old sha1sum was: '6acae7c29dec287ee6cdf319058c76e7e5335b80'
New sha1sum is : 'd2ab7cadff0ee7dc69321e1fdf58c9ba902f3c62'
Old sha256sum was: 'e4daa9ebdcc2e58eed19d8bc876beced1a71dc94b910af7eab11160091f030f1'
New sha256sum is : '5f90055792724ab044deb22497b1afbb3c0d5f67fcc29d50eadb5c3b3ea84f13'

Attributes:
 - MD5: 77183b3bcd52f2b6e2a0029ae90584c4
 - SHA1: d2ab7cadff0ee7dc69321e1fdf58c9ba902f3c62
 - SHA256: 5f90055792724ab044deb22497b1afbb3c0d5f67fcc29d50eadb5c3b3ea84f13


** Alert 1558087613.107369: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 May 17 12:06:53 rafa-GS63-7RD->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
File '/etc/newfile.txt' checksum changed.
Old md5sum was: '77183b3bcd52f2b6e2a0029ae90584c4'
New md5sum is : '0438a676a65f4eddca32a14a45e58bf3'
Old sha1sum was: 'd2ab7cadff0ee7dc69321e1fdf58c9ba902f3c62'
New sha1sum is : 'fca40a03658b8d8fd1e78a300910e80313c0facf'
Old sha256sum was: '5f90055792724ab044deb22497b1afbb3c0d5f67fcc29d50eadb5c3b3ea84f13'
New sha256sum is : '297ce1121e67a89eb5c62cd39e012ad8f315e62f4f44e1b96e94599007de8240'

Attributes:
 - MD5: 0438a676a65f4eddca32a14a45e58bf3
 - SHA1: fca40a03658b8d8fd1e78a300910e80313c0facf
 - SHA256: 297ce1121e67a89eb5c62cd39e012ad8f315e62f4f44e1b96e94599007de8240
```

If you have many files on those directories, you can try to change the `internal_options.conf` to make syscheck sleep less and go faster with the file analysis:

```
# Syscheck checking/usage speed. To avoid large cpu/memory
# usage, you can specify how much to sleep after generating
# the checksum of X files. The default is to sleep one second
# per 100 files read.
syscheck.sleep=1
syscheck.sleep_after=100
```

Please tell us if it works for you.

Best regards.
