### ISSUE TITLE
Wazuh error indexor for opensearch ssl

### ISSUE THREAD

**Issue by Techrese** [wazuh/wazuh#26771]
So I was running wazuh 4.8.0 in docker containers on vmware esxi.
Recently I migrated to proxmox latest version as of today 8.x.x
I also wanted to upgrade wazuh to version 4.9.0, but i received not supported cpu x86-64. in proxmox I tried with cpu kvm64 but no luck aswell.

So i downgraded back to 4.8.0
I did a git checkout to the 4.8.0 branch
build images and run.

All containers are running, however dashboard gave me the healthcheck error api no connection available.
So with the help of chatgpt I went digging.

I checked docker logs

Dashboard OK no errors
Manager OK no errors
Indexer NOK gave exceptions
ERROR StatusConsoleListener Could not define attribute view on path "/var/log/wazuh-indexer/opensearch.log" got access denied ("java.lang.RuntimePermission" "accessUserInformation")
[2024-11-09T21:27:09,605][WARN ][o.o.h.AbstractHttpServerTransport] [wazuh.indexer] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:51418}
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 44454c455445202f77617a75682d2a20485454502f312e310d0a486f73743a206c6f63616c686f73743a393230300d0a557365722d4167656e743a206375726c2f372e38312e300d0a4163636570743a202a2f2a0d0a0d0a
[2024-11-09T21:17:16,269][WARN ][r.suppressed             ] [wazuh.indexer] path: /.kibana/_count, params: {index=.kibana}
org.opensearch.action.search.SearchPhaseExecutionException: all shards failed

these are the most common errors I received. 
I also went into bash to check the opensearch.log file in the container and received the same ssl/tls notsslrecordexception.

I tried several time rebuild the images but no luck.

Any idea?
Also maybe any idea for the not supported cpu i know i have a very old cpu intel xeon E5 2680v1

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by M4jx** [comment]
Can you please provide more information regarding:
- What operating system are you using?
- How you received the "not supported CPU" error? Was it in the OS, docker, container...
- Did you follow the [official documentation](https://documentation.wazuh.com/current/deployment-options/docker/docker-installation.html) for Docker deployment?

**Comment by Techrese** [comment]
Os is ubuntu 24.04.1 with docker and docker-compose running on it
For the not supported cpu I received it when starting the containers, so also docker.

for back downgrading to 4.8.0, I followed the readme file that comes in the single-node folder.
I ran previously 4.8.0 aswell so i don't really know why it is not working anymore

**Comment by Techrese** [comment]
oke no sorry my mistake I receive the error when building the images.
![Screenshot 2024-11-11 112725](https://github.com/user-attachments/assets/6259bb00-f14d-45f1-9a09-a6e278bfed64)

**Comment by Techrese** [comment]
OKe kinda weird after retying this step for 4.9.0, i went back to 4.8.0 using git checkout 4.8.0
Again did all the steps in the readme but dashboard and indexer wont start when I check the logs. I suddenly also have the error not supported exception.

The only difference here is indeed that it previously worked on vmware esxi rather than proxmox

**Comment by M4jx** [comment]
The glibc error "CPU does not support x86-64-v2" is because your current VM CPU configuration in Proxmox does not properly emulate the required CPU features. Therefore, to fix this issue, use CPU type "host" (recommended) or use "Broadwell-noTSX" and reboot your VM.

Your Indexer issue seems to be related to not properly modifying the `vm.max_map_count` value. Please update the `vm.max_map_count` setting in `/etc/sysctl.conf` to set this value permanently and reboot your VM. To verify after rebooting, run `sysctl vm.max_map_count`.

**Comment by Techrese** [comment]
thanks you for this information, however the vm map count was already set, Altough I have to admit that after migrating to proxmox even tough I did a ovf import I ran the containers without redoing the map count, but when I set the map count I rebuilded my images and removed the old ones. 
![image](https://github.com/user-attachments/assets/cb8b21e7-cb02-4fa5-ab1f-3a1d60799c8a)

**Comment by Techrese** [comment]
however for the 4.9.0 unsupported cpu, that seems to be fixed, I have set the cpu to host and my images build and run, however I do have the same exception so still not working.

**Comment by Techrese** [comment]
I solved this one by deleting the vm and reimporting the vm in proxmox.
