### ISSUE TITLE
Dynamic index naming bug in Indexer Connector module

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#26779]
### Description:
A bug has been identified in the Wazuh-Engine's Indexer Connector module, which currently uses a static `$(date)` placeholder for indexing events in OpenSearch. This placeholder is only replaced with the actual date upon instantiation of the indexer connector. Consequently, if the indexer remains active across date changes, it incorrectly continues using the initial date, leading to events being sent to an outdated index. This issue requires a fix to ensure accurate and dynamic index naming aligned with the actual date of event handling.

### Objective:
To resolve the bug by enabling dynamic index naming in the Indexer Connector. Two potential solutions are proposed: extending the interface to allow specifying the index name per event or updating the placeholder dynamically during each bulk send operation to OpenSearch.

### Proposed Solutions:
1. **Parameter Addition to Publish Method**:
   - Enhance the `publish` method to accept an additional parameter specifying the target index name. This change would allow flexibility for the calling function to determine the index name dynamically at runtime (Desirable solution).

2. **Dynamic Placeholder Update During Bulk Operations**:
   - Modify the indexing functionality to update the `$(date)` placeholder dynamically each time events are bulk sent to OpenSearch. This would ensure that the index name reflects the actual date at the time of sending.

### Expected Outcome:
Both proposed solutions aim to rectify the index naming issue, ensuring that data is routed to the correct OpenSearch index based on real-time operational context. The chosen solution should align with Wazuh's operational requirements and technical constraints.

### DoD (Definition of Done):
- [x] A decision is made on which solution to implement based on a detailed analysis of pros and cons.
- [x] The chosen solution is implemented ensuring that the indexer connector dynamically names indices correctly.
- [x] Comprehensive testing is conducted to confirm that the fix addresses the issue without introducing new bugs.
- [x] Documentation is updated to reflect any changes in the indexer connector's operation or API.

### Impact:
Implementing this fix will prevent data misplacement issues in OpenSearch and ensure that Wazuh-Engine's telemetry data is accurately indexed and retrievable based on the correct temporal context. This is crucial for maintaining the integrity and usability of stored data in security monitoring and analysis scenarios.

**Comment by pereyra-m** [comment]
## Update

I analyze the code to compare the possible solutions.

**Comment by pereyra-m** [comment]
## Update

I continue the development, now I'll add some component test to validate the proposed approach.

**Comment by pereyra-m** [comment]
## Update

Rebase and package generation
