### ISSUE TITLE
Vulnerability Detector - Infinite loop indexing events

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26806]
## Description
As part of the testing of this issue:
- https://github.com/wazuh/wazuh/issues/26098

It was found that there is a possible infinite loop:
```console
2024/11/11 12:31:00 indexer-connector[95787] indexerConnector.cpp:518 at operator()(): DEBUG: Added document for insertion with id: 003_002c810a974f4612d7f1390945c62722a246301a_CVE-2022-27406.
2024/11/11 12:31:00 indexer-connector[95787] indexerConnector.cpp:518 at operator()(): DEBUG: Added document for insertion with id: 003_002c810a974f4612d7f1390945c62722a246301a_CVE-2022-27406.
2024/11/11 12:31:00 indexer-connector[95787] indexerConnector.cpp:518 at operator()(): DEBUG: Added document for insertion with id: 003_002c810a974f4612d7f1390945c62722a246301a_CVE-2022-27406.
2024/11/11 12:31:00 indexer-connector[95787] indexerConnector.cpp:518 at operator()(): DEBUG: Added document for insertion with id: 003_002c810a974f4612d7f1390945c62722a246301a_CVE-2022-27406.
```

If the information that will be indexed doesn't follow the expected format, an exception is thrown in the indexerConnector ThreadDispatchQueue thread ([ex. no data](https://github.com/wazuh/wazuh/blob/0a233ff9e5730cfc4b64704d059b3922dad37a69/src/shared_modules/indexer_connector/src/indexerConnector.cpp#L510-L511)) and the event is never removed from the [database](https://github.com/wazuh/wazuh/blob/0a233ff9e5730cfc4b64704d059b3922dad37a69/src/shared_modules/utils/threadEventDispatcher.hpp#L192-L193). 

The failing events are then re-processed again and fail in an infinite manner

## How to reproduce
1. Install manager from [this branch](https://github.com/wazuh/wazuh/tree/enhancement/26098-prioritize-cisa-vulnerability-content-over-nvd-in-the-vulnerability-scanner)
2. Register an agent in centOS 8

## DoD
- [x] Bug fixed
- [x] Testing updated

**Comment by Dwordcito** [comment]
Delayed because PR review testing.
