### ISSUE TITLE
Vulnerability Detector - Unhandled erros from rocksDB

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26807]
## Description

Multiple errors were found in the rocksDBQueue interface:
- If the put operation fails, m_last is not restored to its original value:
https://github.com/wazuh/wazuh/blob/0a233ff9e5730cfc4b64704d059b3922dad37a69/src/shared_modules/utils/rocksDBQueue.hpp#L129-L133

Rendering that **id** useless.

This can be seen after we use the ["at" method](https://github.com/wazuh/wazuh/blob/0a233ff9e5730cfc4b64704d059b3922dad37a69/src/shared_modules/utils/rocksDBQueue.hpp#L184-L186), were an exception is thrown ([see comment](https://github.com/wazuh/internal-devel-requests/issues/1747#issuecomment-2468897875))

## DoD
- [ ] Behaviour fixed
- [ ] Added UTs

**Comment by Dwordcito** [comment]
Closed, because this issue will be fixed in https://github.com/wazuh/wazuh/issues/26806
