### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Vulnerability Detection performance test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#26813]
## Tests information

|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release stage issue**     |          https://github.com/wazuh/wazuh/issues/26759               |
| **Main Vulnerability Detection tests issue**     |           https://github.com/wazuh/wazuh/issues/26812                     |
| **Version**                          |                   4.10.0                         |
| **Release stage**              |                   Alpha 3                     |
| **Tag**                              |          https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3                               |
| **Previous Vulnerability performance tests issue**      |     https://github.com/wazuh/wazuh/issues/26477                 |

## Description

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads: high, medium, and low. This comparative analysis will provide a comprehensive understanding of the current status of the vulnerability detection module and will help identify any unexpected behavior.

### Methodology

Utilizing the CLUSTER-Workload_benchmarks_metrics pipeline to execute specified test cases automatically. Results will be manually analyzed and shared with the development team for validation adjustments.

### Test Cases

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 3h |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 3h |
| Very High Activity | Simulate a large-scale environment with significant activity | 10 | 3 | 20000 | 1 | 1h |

### Test parameters

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha3`
- JENKINS_REFERENCE: `v4.10.0-alpha3`
- QA_REFERENCE: `v4.10.0-alpha3`
- TEST_TIME: (As specified in test cases: 3h -> `10800`, 1h -> `3600`)
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: (As specified in test cases)
- MANAGER_WORKERS: (As specified in test cases)
- INDEXER_NODES: (As specified in test cases)
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: (`Twice` the number specified in the test cases)
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

### Test considerations

- Test frequency: 60
- Number of vulnerable packages: 100

### Builds

- Medium: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/787
- High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/786
- Very High: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/789/

### Artifacts

- https://github.com/wazuh/wazuh/issues/26813#issuecomment-2470318809

# Conclusion :red_circle: 

- Logs :yellow_circle: 

  - Known issues:

    - https://github.com/wazuh/wazuh/issues/22565
    - https://github.com/wazuh/wazuh-packages/issues/1511
    - https://github.com/wazuh/wazuh-indexer/issues/328
    - https://github.com/wazuh/wazuh-indexer/issues/167
    - https://github.com/wazuh/wazuh-indexer/issues/71
    - https://github.com/wazuh/wazuh/issues/8480
    - https://github.com/wazuh/wazuh/issues/25942
    - https://github.com/wazuh/wazuh/issues/26115
    - https://github.com/opensearch-project/security-analytics/issues/1312
    - https://github.com/wazuh/wazuh-indexer/issues/480
    - https://github.com/wazuh/wazuh-indexer/issues/167

- Plots :red_circle: 

  - New Issues: 
  
     - https://github.com/wazuh/wazuh/issues/26839
     - https://github.com/wazuh/wazuh/issues/26844
     - https://github.com/wazuh/wazuh/issues/26845
     - https://github.com/wazuh/wazuh/issues/26846

**Comment by rauldpm** [comment]
## Artifacts

- Very High: [vd_veryhigh.tgz.zip](https://github.com/user-attachments/files/17715994/vd_veryhigh.tgz.zip)
- High: In progress
- Medium: In progress

**Comment by santipadilla** [comment]
# Very high Activity

**Comment by santipadilla** [comment]
# High Activity

**Comment by joaquinsgi** [comment]
# Medium Activity 

**Comparision**: Compared with https://github.com/wazuh/wazuh/issues/26172


***

## Logs :black_circle:
 
### Summary


<details>

<summary> Master :black_circle: </summary>

- Known issue: https://github.com/wazuh/wazuh/issues/22565
```
2024/10/07 07:28:37 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/10/07 07:28:37 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-7-229.ec2.internal', retrying until the connection is successful.
```

- Known issue: https://github.com/wazuh/wazuh/issues/8480
```
2024/10/07 07:42:38 wazuh-remoted: ERROR: (1320): Agent '000' not found.
```

</details>
 
<details>

<summary> Worker 1 :black_circle: </summary> 


- Expected errors:

```
2024/10/07 09:25:11 wazuh-analysisd: WARNING: Syscollector decoder queue is full.
2024/10/07 09:25:11 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
```


</details>

<details>

<summary> Worker 2 :black_circle:  </summary>


- Expected errors:

```
2024/10/07 09:25:11 wazuh-analysisd: WARNING: Syscollector decoder queue is full.
```

- Known issue: https://github.com/wazuh/wazuh/issues/22565
```
2024/10/07 07:28:37 indexer-connector: WARNING: No username and password found in the keystore, using default values.
2024/10/07 07:28:37 indexer-connector: WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-7-229.ec2.internal', retrying until the connection is successful.
```


</details>

<details>

<summary> Indexer 1 :black_circle: </summary>

- Related to: https://github.com/wazuh/wazuh-packages/issues/1511
```
[2024-10-07T07:24:45,822][ERROR][o.o.s.a.s.SinkProvider   ] [CLUSTER-Workload_benchmarks_metrics_B740_indexer_1] Default endpoint could not be created, auditlog will not work properly.
```

- Related to: https://github.com/wazuh/wazuh-indexer/issues/328
```
[2024-10-07T07:24:47,228][ERROR][o.o.p.c.j.GCMetrics      ] [CLUSTER-Workload_benchmarks_metrics_B740_indexer_1] MX bean missing: G1 Concurrent GC
```

- Related to: https://github.com/wazuh/wazuh-indexer/issues/167
```
[2024-10-07T07:24:51,168][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [CLUSTER-Workload_benchmarks_metrics_B740_indexer_1] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
```

</details>

<details>

<summary> Indexer 2 :black_circle: </summary>

- Related to: https://github.com/opensearch-project/performance-analyzer/issues/644
```
[2024-10-07T07:24:52,242][WARN ][o.o.p.c.u.JsonConverter  ] [CLUSTER-Workload_benchmarks_metrics_B740_indexer_1] Json Mapping Error: Cannot invoke "java.lang.Long.longValue()" because "this.cacheMaxSize" is null (through reference chain: org.opensearch.performanceanalyzer.collectors.CacheConfigMetricsCollector$CacheMaxSizeStatus["Cache_MaxSize"])
```

</details>

<details>

<summary> Dashboard :black_circle:  </summary>

- No logs

</details>
 

## Metrics and Statistics :black_circle: 

<details><summary>Master :black_circle:  </summary>



- Metrics:


- Known issue: https://github.com/wazuh/wazuh/issues/25957 not appear again
- New issue: https://github.com/wazuh/wazuh/issues/26230


---

- Binaries

![CPU](https://github.com/user-attachments/assets/5be113f8-140f-46ab-bbf7-f9474c6e7b08)
![Disk_Read](https://github.com/user-attachments/assets/b51f0d10-3378-4e8f-9bcc-d29e18bbd15f)
![Disk_Read_Speed](https://github.com/user-attachments/assets/eec57ae4-8b7d-4d85-b80e-4ae10d7d5937)
![Disk_Write_Speed](https://github.com/user-attachments/assets/9368a0e6-1bc7-4cc7-ad7a-1d63985079ca)
![Disk_Written](https://github.com/user-attachments/assets/ee08b7e5-b84c-4543-8114-613792f53eaa)
![FD](https://github.com/user-attachments/assets/a27cb7ac-6557-47a9-bbb6-e8555cd1d508)
![PSS](https://github.com/user-attachments/assets/c2236b89-94fc-4aa8-b930-281843066c91)
![Read_Ops](https://github.com/user-attachments/assets/e225e20c-17f4-482b-9c7d-53071a40fff4)
![RSS](https://github.com/user-attachments/assets/7a54cc73-57ba-4da5-90f5-1e658109624f)
![SWAP](https://github.com/user-attachments/assets/27490882-5cac-486b-96b8-fdc8f244824b)
![USS](https://github.com/user-attachments/assets/747776bd-1c57-44d7-aa8e-75db39c79425)
![VMS](https://github.com/user-attachments/assets/6e754f06-ee40-4b59-8baa-42140ab5470f)
![Write_Ops](https://github.com/user-attachments/assets/562d9fb8-21ba-4d2b-9a61-822faa6395b5)



- Stats: wazuhdbd
![wazuh-wazuhdb_api_stats_Agent queries breakdown](https://github.com/user-attachments/assets/a5e3a43b-7521-46b3-84d0-133a8421684a)
![wazuh-wazuhdb_api_stats_Agent tables breakdown](https://github.com/user-attachments/assets/88d2c4c7-e2ba-4975-a0d2-dab92483ac56)
![wazuh-wazuhdb_api_stats_Database queries counts](https://github.com/user-attachments/assets/a26657c0-1618-4eb9-bf25-ea7ca1610f6f)
![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/5b47ba12-0ad9-4a38-bc8e-64b5a1e459f2)
![wazuh-wazuhdb_api_stats_Global group queries](https://github.com/user-attachments/assets/089e174b-8a2e-4a08-b66b-b5805f3145ec)
![wazuh-wazuhdb_api_stats_Global queries breakdown](https://github.com/user-attachments/assets/f2c2695e-f28a-4fae-a06d-dec9f2884d8f)
![wazuh-wazuhdb_api_stats_Queries time metrics](https://github.com/user-attachments/assets/67731fa2-48a9-486a-b5ba-305c130eeae3)
![wazuh-wazuhdb_api_stats_Task queries breakdown](https://github.com/user-attachments/assets/0faecc19-5087-4260-8791-ac5c69f586cd)






- Stats: remoted
![wazuh-remote_api_stats_Bytes received](https://github.com/user-attachments/assets/6713e2f3-431d-4a22-82dc-83af07efcea0)
![wazuh-remote_api_stats_Events sent and count](https://github.com/user-attachments/assets/9d46efc5-5ab9-4e12-b1bc-bd0259327de6)
![wazuh-remote_api_stats_Queue status](https://github.com/user-attachments/assets/2853d762-f4d1-49f2-856c-baf539f18202)
![wazuh-remote_api_stats_TCP sessions](https://github.com/user-attachments/assets/e94213ac-f985-4cbb-8732-f04ebfab0e3d)




- Stats: analysisd

![wazuh-analysis_api_stats_Alerts and events info](https://github.com/user-attachments/assets/9f174760-0353-4758-8f14-7c965702afaa)
![wazuh-analysis_api_stats_Events decoded per queue](https://github.com/user-attachments/assets/38b3969a-d63f-40e6-b6e4-3e82890b4a17)
![wazuh-analysis_api_stats_Events decoded per second](https://github.com/user-attachments/assets/65257958-9d6b-4f89-bc98-d154e4c908f8)
![wazuh-analysis_api_stats_Events dropped per queue](https://github.com/user-attachments/assets/a09e4a66-6558-455f-9719-807e8fb7b863)



</details>





<details><summary>Dashboard :black_circle:  </summary>

- No anomalies detected

---

- Binaries

![CPU](https://github.com/user-attachments/assets/5e2357ec-967f-42f3-b951-70b14033e032)
![Disk_Read](https://github.com/user-attachments/assets/6a8fcd93-42e4-4421-9223-624232129988)
![Disk_Read_Speed](https://github.com/user-attachments/assets/90092359-e783-4092-8b59-b3eb200c465a)
![Disk_Write_Speed](https://github.com/user-attachments/assets/22f479d9-969b-406d-ac35-c85387f9f707)
![Disk_Written](https://github.com/user-attachments/assets/5a543225-33ee-41ea-925f-d81ea9035758)
![FD](https://github.com/user-attachments/assets/b03d2233-9216-4d62-94b2-321ea1737978)
![PSS](https://github.com/user-attachments/assets/901641a0-9bdf-4f67-baef-95fd77876be5)
![Read_Ops](https://github.com/user-attachments/assets/86b1d316-c20c-49d0-aacc-3ed99cb73368)
![RSS](https://github.com/user-attachments/assets/a8ff63c6-8bd4-4e46-80ae-1e28479c568a)
![SWAP](https://github.com/user-attachments/assets/c1288c6b-2a9a-4b41-b62d-c5b84841edee)
![USS](https://github.com/user-attachments/assets/16b82101-f417-4543-9949-061e1f4f325b)
![VMS](https://github.com/user-attachments/assets/b639cd2d-db7b-402a-a8b2-ad4c7daba2eb)
![Write_Ops](https://github.com/user-attachments/assets/26ecb91c-27f4-43c3-91ef-6cdecb0a33f6)




</details>

**Comment by joaquinsgi** [comment]
LGTM!
