### ISSUE TITLE
`wazuh-modulesd` error in MacOS agent while performing a WPK upgrade

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26827]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha3  |  Development  |  `wazuh-modulesd`  | Download | 

# Description

While testing in https://github.com/wazuh/wazuh/issues/26797#issuecomment-2470887055, the following error log was detected after a forced WPK upgrade from 4.10.0 to 4.10.0:

```console
sh-3.2# grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log | wc -l
       1
sh-3.2# grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log 
2024/11/12 08:05:00 wazuh-modulesd: ERROR: Couldn't delete PID file.
```

## Environment

A Wazuh 4.10.0-alpha3 AMI and a MacOS 14 Sonoma Intel64 machine. The failed test consists of having a Wazuh agent v4.10.0 installed on the MacOS machine and performing a forced WPK upgrade to v4.10.0 from the AMI.

## Steps to reproduce

1. Ask DevOps for a Wazuh 4.10.0-alpha3 AMI and a macOS 14 Sonoma intel64 machine

2. Install v4.9.2 Wazuh Agent in the MacOS machine and connect it to the manager

3. Perform a WPK upgrade from manager to 4.10.0

```
/var/ossec/bin/agent_upgrade -a xxx -f /home/wazuh-user/wazuh_agent_v4.10.0_macos_intel64.pkg.wpk
```

4. Force another WPK upgrade to 4.10.0 from 4.10.0
```
/var/ossec/bin/agent_upgrade -a 016 -f /home/wazuh-user/wazuh_agent_v4.10.0_macos_intel64.pkg.wpk -F
```

5. Check logs in agent
```
grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log
```

For more details, check https://github.com/wazuh/wazuh/issues/26797#issuecomment-2470887055

## Current result

```console
sh-3.2# grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log | wc -l
       1
sh-3.2# grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log 
2024/11/12 08:05:00 wazuh-modulesd: ERROR: Couldn't delete PID file.
```

## Expected result

```console
sh-3.2# grep -iE "Error|\Warning\|Critical" /Library/Ossec/logs/ossec.log | wc -l
       0
```

## Attachments

- Logs: 
[ossec.log](https://github.com/user-attachments/files/17719663/ossec.log)

**Comment by vikman90** [comment]
I've not managed to reproduce this problem, even upgrading 5 times:

```
2024/11/13 10:28:07 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/11/13 10:28:07 wazuh-modulesd:syscollector: INFO: Module finished.
2024/11/13 10:28:07 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2024/11/13 10:28:07 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/11/13 10:28:07 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2024/11/13 10:28:07 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2024/11/13 10:28:08 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/11/13 10:28:08 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
```

I guess that the installer may have deleted the file before _wazuh-modulesd_ have exited. However, since the rest of daemons print nothing on this case, we're going to silence this log.
