### ISSUE TITLE
Abnormal behaviour of Wazuh Dashboard in VD performance tests

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26845]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha3  | Development   |  Dashboard  | Repository | 

## Description

During the testing of 4.10.0 - Alpha 3 in the vulnerability detection performance test in https://github.com/wazuh/wazuh/issues/26813, comparing it with previous versions, abnormal behaviour of the Wazuh Dashboard has been detected.

### Environment

| Node | Vagrant/AWS | Image | vCPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch |
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Worker nodes | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Indexer nodes | AWS | amazonlinux | 4 | 8 | 32 | pre-release |
| Dashboard node | AWS | amazonlinux | 4 | 8 | 32 | pre-release |

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads, in this case, medium.

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10  | 3h |

### Steps to reproduce

1. Go to https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/build?delay=0sec

2. Execute the pipeline with the following parameters:

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha3`
- JENKINS_REFERENCE: `v4.10.0-alpha3`
- QA_REFERENCE: `v4.10.0-alpha3`
- TEST_TIME: 10800
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: 50
- MANAGER_WORKERS: 2
- INDEXER_NODES: 2
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: 20
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

### Current result

<details><summary>4.10.0-alpha3</summary>

![CPU](https://github.com/user-attachments/assets/d49a2d04-77d6-4a9d-8832-df4a1aea4fc1)
![Disk_Read](https://github.com/user-attachments/assets/3276ef1b-75ef-44e0-8b78-c9e56a22b10e)
![Disk_Read_Speed](https://github.com/user-attachments/assets/cd52b579-78d2-4549-af97-90cf5462d84d)
![Disk_Write_Speed](https://github.com/user-attachments/assets/aadc7f6c-a12a-42f7-9ce0-daa957367800)
![Disk_Written](https://github.com/user-attachments/assets/32a2f967-86c9-4ffc-9088-8e31398e2631)
![FD](https://github.com/user-attachments/assets/dc8d8f15-a6be-4517-80d2-368a3d46b8da)
![PSS](https://github.com/user-attachments/assets/61ffa791-0940-44fb-9fdc-3601254e44ba)
![Read_Ops](https://github.com/user-attachments/assets/5b20ac83-8924-434a-ab35-081387b6d07d)
![RSS](https://github.com/user-attachments/assets/fc207352-fac1-4010-b5fb-ac9f5bc7b869)
![SWAP](https://github.com/user-attachments/assets/f0b87d6c-b2db-4805-97d1-95e9ec94d75f)
![USS](https://github.com/user-attachments/assets/d4c5b8d1-657a-4b8c-b64e-050479212a64)
![VMS](https://github.com/user-attachments/assets/1648169b-6ba9-4b66-ad24-eb56946b0a87)
![Write_Ops](https://github.com/user-attachments/assets/d617458f-6b87-4a61-aae0-311a79608bff)

</details>

### Expected result

<details><summary>4.9.1-rc3</summary>

![CPU](https://github.com/user-attachments/assets/6f52e663-112b-485d-b6f7-7f885269545b)
![Disk_Read](https://github.com/user-attachments/assets/93e13f2d-cdc9-4469-b909-eacea0e24143)
![Disk_Read_Speed](https://github.com/user-attachments/assets/5f2ae0dc-6101-47f7-9065-56567d0168f5)
![Disk_Write_Speed](https://github.com/user-attachments/assets/6e630002-2f41-453b-bd39-8be05f81be6c)
![Disk_Written](https://github.com/user-attachments/assets/89ab6d6d-21b4-4e91-8eb3-72c0d3981021)
![FD](https://github.com/user-attachments/assets/17d1a589-7122-49ff-805b-d2be313b281e)
![PSS](https://github.com/user-attachments/assets/5c359ee1-171d-4cda-bf7b-6bbfaec588d9)
![Read_Ops](https://github.com/user-attachments/assets/185dc1ec-cf24-4fe5-90c8-70ba31261243)
![RSS](https://github.com/user-attachments/assets/f438fba9-c298-4fac-bfd3-956f22e4923b)
![SWAP](https://github.com/user-attachments/assets/f6810028-4c6b-4ee9-8c09-044ef03be0d0)
![USS](https://github.com/user-attachments/assets/50c0f233-575d-4ff4-9d46-aad0f33d431b)
![VMS](https://github.com/user-attachments/assets/22e9412a-6f4c-4bc7-b2ca-f8f192bdf8a2)
![Write_Ops](https://github.com/user-attachments/assets/82ebf323-c156-4f14-90cb-3b9f8483551a)

</details>

### Attachments

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/787/

- Build parameters:

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha3`
- JENKINS_REFERENCE: `v4.10.0-alpha3`
- QA_REFERENCE: `v4.10.0-alpha3`
- TEST_TIME: 10800
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: 50
- MANAGER_WORKERS: 2
- INDEXER_NODES: 2
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: 20
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

- Artifacts: [medium.tgz.zip](https://github.com/user-attachments/files/17733894/medium.tgz.zip)

**Comment by rauldpm** [comment]
Before proceeding with this issue we are going to check the environment again, as the indexer node reports low usage too

- https://github.com/wazuh/wazuh/issues/26844
