### ISSUE TITLE
High increase of `agent-get-agent-info` in Wazuh Master at VD performance test

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26846]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha3  | Development   |  `wazuhdbd`  | Repository | 

## Description

During the testing of 4.10.0 - Alpha 3 in the vulnerability detection performance test in https://github.com/wazuh/wazuh/issues/26813, comparing it with previous versions, it has been detected a high increase of `agent-get-agent-info` in the Global agent queries table, in wazuhdbd plots

### Environment

| Node | Vagrant/AWS | Image | vCPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch |
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Worker nodes | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Indexer nodes | AWS | amazonlinux | 4 | 8 | 32 | pre-release |
| Dashboard node | AWS | amazonlinux | 4 | 8 | 32 | pre-release |

The objective is to conduct performance tests to analyze the vulnerability detection module across varying environment loads, in this case, medium.

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10  | 3h |

### Steps to reproduce

1. Go to https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/build?delay=0sec

2. Execute the pipeline with the following parameters:

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha3`
- JENKINS_REFERENCE: `v4.10.0-alpha3`
- QA_REFERENCE: `v4.10.0-alpha3`
- TEST_TIME: 10800
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: 50
- MANAGER_WORKERS: 2
- INDEXER_NODES: 2
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: 20
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

#### 4.10.0-alpha3

![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/bd029cc0-6817-4d08-a6d2-773824e5a984)

#### 4.9.1-rc3

![wazuh-wazuhdb_api_stats_Global agent queries](https://github.com/user-attachments/assets/064a57be-5661-47d5-8674-bdbd25f680f6)

### Attachments

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/787/

- Build parameters:

<details><summary>Parameters</summary>

- TARGET_PKG_VERSION: `4.10.0`
- TARGET_PKG_REVISION: `1`
- TARGET_REPOSITORY: `pre-release`
- VERBOSITY: `-v`
- SOURCE_REFERENCE: `v4.10.0-alpha3`
- JENKINS_REFERENCE: `v4.10.0-alpha3`
- QA_REFERENCE: `v4.10.0-alpha3`
- TEST_TIME: 10800
- LOAD_BALANCER: `elb`
- PROTOCOL: `TCP`
- OS: `debian10`
- AGENT_SIMULATED_VERSION: `4.10.0`
- LABELS: `left empty`
- EVENTS_SIZE: `0`
- MODE: `HYBRID`
- AGENT_NUMBER: 50
- MANAGER_WORKERS: 2
- INDEXER_NODES: 2
- DASHBOARD: `True`
- PARSE_CLUSTER_LOGS: `False`
- CLUSTER_TESTS: `left empty`
- KIBANA_API_REQUESTS: `True`
- TEST_PERFORMANCE_API_ENDPOINTS: `False`
- EXTRA_LOAD_API_REQUESTS: `True`
- UNIFY_BINARY_PROCESSES_FOR_PLOTTING: `True`
- API_REQUESTS_PERCENTAGE: `10`
- MANAGERS_AWS_DEPLOYMENT: `EC2`
- MANAGER_INSTANCES: `auto`
- AGENT_INSTANCES: `auto`
- QUEUES: `Vulnerability`
- FIM_EPS: `0`
- ROOTCHECK_EPS: `0`
- SYSCOLLECTOR_EPS: `0`
- VULNERABILITY_EPS: 20
- LOGCOLLECTOR_EPS: `0`
- SCA_EPS: `0`
- WINDOWS_EVENT_EPS: `0`
- HOST_INFO_EPS: `0`
- FIM_INTEGRITY_EPS: `0`
- MANAGER_MONITORING_PROCESSES: `wazuh-analysisd`,`wazuh-remoted`,`wazuh-db`,`wazuh-modulesd`,`wazuh-apid`,`wazuh_clusterd`,`wazuh-authd`,`wazuh-dbd`
- MANAGER_MONITORING_STATS: `remote`,`analysis`,`wazuhdb`
- INDEXER_MONITORING: `wazuh-indexer`
- INDEXER_MONITORING_STATS: `vulnerabilities`,`alerts`
- DASHBOARD_MONITORING: `wazuh-dashboard`
- LOGGING: `alerts.log`
- GROUPS_NUMBER: `0`
- FILES_NUMBER_PER_GROUP: `0`
- BYTES_NUMBER_PER_FILE: `0`
- LOCAL_INTERNAL_OPTIONS_CONFIG: `monitord.rotate_log=0`,`wazuh_database.max_queued_events=33554431`,`wazuh_clusterd.debug=1` (each `,` is a `new line`)
- DESTROY_INSTANCES: `True`

</details>

- Artifacts: [medium.tgz.zip](https://github.com/user-attachments/files/17733894/medium.tgz.zip)

**Comment by sebasfalcone** [comment]
## Pre-analysis
It is probably related to a feed update process

```console
2024/11/12 16:16:35 wazuh-modulesd:vulnerability-scanner: INFO: Triggered a re-scan after content update.
2024/11/12 16:16:35 wazuh-modulesd:vulnerability-scanner: INFO: Feed update process completed.
```

![image](https://github.com/user-attachments/assets/0f4ceafe-8040-4fe1-bab6-e952d741b8c4)
