### ISSUE TITLE
Strange behavior in one Indexer plot from 4.10.0-alpha3 VD performance test

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#26844]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  Alpha 3  |  Development  |  Indexer  | Repository | 

## Description

During the tests performed in https://github.com/wazuh/wazuh/issues/26813, it has been found that the one indexer node has a strange behavior in plots, we can see thatin some plots  in 4.10.0-alpha3 that behavior:
![CPU](https://github.com/user-attachments/assets/544c6737-6e1b-45b9-847e-35c2e1c276be)
![FD](https://github.com/user-attachments/assets/0826bc6a-aff4-4036-94ae-71ac14ab055c)
![PSS](https://github.com/user-attachments/assets/da50bcfd-51db-472d-b8a7-d082d28ac8c0)
![Read_Ops](https://github.com/user-attachments/assets/584e45e4-c357-4a55-88e7-ce685f92d695)
![RSS](https://github.com/user-attachments/assets/7620970a-c86a-4d72-86c5-6cba7866a020)
![USS](https://github.com/user-attachments/assets/16f6bf6a-47e3-46a2-a036-a51bd9c367ad)
![VMS](https://github.com/user-attachments/assets/ab555a3e-5a80-4599-a549-cc8ee8815ee0)
![Write_Ops](https://github.com/user-attachments/assets/cdbe79f3-c727-40a9-9cf3-ab806ea20f21)

And if we analyse the plots from previous builds like in 4.9.1-rc3:
![CPU](https://github.com/user-attachments/assets/ffff7a7c-4c84-4c88-ad77-983b30a526d7)
![FD](https://github.com/user-attachments/assets/0ac0bd59-2072-4722-a08e-7493f5d43d11)
![PSS](https://github.com/user-attachments/assets/22081bda-2eaf-450e-8a98-d23164b506da)
![Read_Ops](https://github.com/user-attachments/assets/89423d6e-0946-4ea6-bdf0-68fb03044feb)
![RSS](https://github.com/user-attachments/assets/8cefbfb2-fa97-4eb1-b85b-7253c2601c4b)
![USS](https://github.com/user-attachments/assets/bef7a5cb-b80d-4c90-8c7c-148fd7a43a1a)
![VMS](https://github.com/user-attachments/assets/1d482aa9-e9ca-4553-94e8-1487221951ae)
![Write_Ops](https://github.com/user-attachments/assets/a43652c4-a501-40b8-a53d-dfbff9fe1057)

So the plots are very different.

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Worker nodes | AWS | amazonlinux | 4 | 8 | 60 | pre-release |
| 2 Indexer nodes | AWS | amazonlinux | 4 | 8 | 32 | pre-release |
| Dashboard node | AWS | amazonlinux | 4 | 8 | 32 | pre-release |

### Steps to reproduce
1. Execute : https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics with the parameters below

### Current result

A strange behavior in plots for one indexer, also the 2 indexers in 4.10.0-alpha3 are different.

### Expected result
It is expected a similar behavior like in 4.9.1-rc3, cause the plots are similar meanwhile in 4.10.0-alpha3 the plots are so different.

### Attachments

- Build link: https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/787

- Build parameters: 

![image](https://github.com/user-attachments/assets/8ee2b9fe-9093-4cb0-8569-a5eba1fe492c)
![image](https://github.com/user-attachments/assets/a1c86b8e-fffa-4d30-a205-0e232f2bbdfc)
![image](https://github.com/user-attachments/assets/87574ca7-62c5-4ff6-8775-7f137e5383c2)
![image](https://github.com/user-attachments/assets/4e9f655c-046a-4412-bce0-6743fd11b2dc)
![image](https://github.com/user-attachments/assets/2e88e245-1763-4bc1-8a47-dc84c839be1b)

- Artifacts: 
[medium.tgz.zip](https://github.com/user-attachments/files/17735762/medium.tgz.zip)

**Comment by hossam1522** [comment]
A build with the `DESTROY INSTANCES` parameter set to `False` has been executed:
- https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/790/

**Comment by rauldpm** [comment]
Before proceeding with this issue we are going to check the environment again, as the indexer node reports low usage too

- https://github.com/wazuh/wazuh/issues/26845
