### ISSUE TITLE
Unify the SSL configuration and logic

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#26858]
## Description

In https://github.com/wazuh/wazuh/issues/26356, the centralized configuration changed how the SSL fields are configured, but the required fields are inconsistent for the different services. Some of these inconsistencies are because they don't have some features, like choosing the SSL protocol version.

We should analyze if adding these missing options and their logic to the other services is possible and unify the models used for the SSL configuration. 

For example, the `SSL` configuration used for the APIs has the `ssl_protocol` field, to choose which protocol to use:

https://github.com/wazuh/wazuh/blob/1bd95bc8d0b1794d2a741941ba26009bdb6eb945/framework/wazuh/core/config/models/ssl_config.py#L54-L77

But for the Server of the Indexer, the option isn't present, causing the use of 3 classes to represent the same configuration:

https://github.com/wazuh/wazuh/blob/1bd95bc8d0b1794d2a741941ba26009bdb6eb945/framework/wazuh/core/config/models/ssl_config.py#L14-L51

In this case, we should investigate if we can specify the `ssl_protocol` in the other services or remove the option in the API to unify the configurations. This type of investigation should be made with the other fields that don't match the models.

**Comment by fdalmaup** [comment]
To be carried out as part of #27158
