### ISSUE TITLE
Agent UI Access Lost After WPK Upgrade on Windows Agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#26856]
|Wazuh version|Component|Install type|Install method|Platform|User|
|---|---|---|---|---|---|
| 4.10.0-alpha3 | Installer | Agent | WPK | Windows 11 | Vikman (Administrator)|

## Description

When updating the Windows Agent from version 4.10.0 to the same version (4.10.0) using WPK, access to the UI (`win32ui.exe`) is lost. This behavior contradicts the intended design specified in:
- #25429

The issue appears to stem from the WPK update process, which may not properly handle existing UI components during reinstallation of the same version.  

## Steps to Reproduce

1. Install the MSI package for Windows, version `4.10.0-alpha3`: [wazuh-agent-4.10.0-1.msi](https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.10.0-1.msi).
2. Update the agent to the same version using WPK: [wazuh_agent_v4.10.0_windows.wpk](https://packages-dev.wazuh.com/pre-release/wpk/windows/wazuh_agent_v4.10.0_windows.wpk).

## Expected Behavior

Access to the UI (`win32ui.exe`) should remain functional after updating to the same version using WPK:

![Screenshot 2024-11-14 113804](https://github.com/user-attachments/assets/e354e7f0-c214-4719-a08a-1f8b7370682d)

## Observed Behavior

Access to `win32ui.exe` is lost following the update:

![Screenshot 2024-11-14 113739](https://github.com/user-attachments/assets/4d3246cb-084b-48b9-a3ea-c21ba223aeea)

**Comment by mjcr99** [comment]
## Update
**(15/11/2024)** Researched problem context. Understanding reach and implications, testing environment ready.
