### ISSUE TITLE
Validate engine logging function calls

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#26867]
## Description

It was found that some calls to the logging function don't work because they use an invalid structure.
For example

https://github.com/wazuh/wazuh/blob/2be90523bbfe89dbd8b2c443eec5cc5832a39f21/src/engine/source/api/include/api/api.hpp#L79

The `%s` should be `{}`.

It happened in other modules, and it was corrected 
https://github.com/wazuh/wazuh/pull/26216/commits/802327bbacdbf75530180b5d7eb33811cae25730

Also, it seems that the logging isn't unified in across the files. Some functions still use the `wazuh/src/shared_modules/utils/loggerHelper.h` class.

## DoD

- [x] Find and fix all places where the logging isn't working
- [ ] Consider creating another issue for the logging unification

**Comment by GabrielEValenzuela** [comment]
# Update

- Task completed
- Awaited review
