### ISSUE TITLE
Wazuh windows agent crashed frequently in version 4.8.1

### ISSUE THREAD

**Issue by jegasmile** [wazuh/wazuh#26879]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.1 | Wazuh component | Agent | Packages/Sources | Microsoft Windows Server 2022 Datacenter |

Wazuh server is in 4.9.2 version

Windows Event Log
```
Faulting application name: wazuh-agent.exe, version: 4.7.3.0, time stamp: 0x65e0813c
Faulting module name: syscollector.dll_unloaded, version: 4.7.3.0, time stamp: 0x65e080cf
Exception code: 0xc0000005
Fault offset: 0x00001be0
Faulting process id: 0x1458
Faulting application start time: 0x01dacbc13c638643
Faulting application path: C:\Program Files (x86)\ossec-agent\wazuh-agent.exe
Faulting module path: syscollector.dll
Report Id: d6759bc4-917e-44c7-8068-f3b26a94d3cb
Faulting package full name: 
Faulting package-relative application ID:
```
Wazuh agent logs

```
2024/11/18 00:13:29 wazuh-agent: INFO: (6009): File integrity monitoring scan ended.
2024/11/18 00:30:33 wazuh-agent: CRITICAL: (1102): Could not acquire memory due to [(12)-(Not enough space)].
2024/11/18 00:30:33 wazuh-agent: INFO: Received exit signal. Starting exit process.
2024/11/18 00:30:33 wazuh-agent: INFO: Set pending exit signal.
2024/11/18 00:30:33 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/11/18 00:30:33 wazuh-agent: INFO: Exit completed successfully.
2024/11/18 00:30:33 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2024/11/18 05:23:56
```
We are not experiencing this issue in Linux agents.

As per this https://github.com/wazuh/wazuh/issues/24376  we disabled syscollector module though it doesn't help.

**Comment by extr3metech** [comment]
`2024/11/18 00:30:33 wazuh-agent: CRITICAL: (1102): Could not acquire memory due to [(12)-(Not enough space)].
`
Is there a space issue?

**Comment by jegasmile** [comment]
Thanks for the recommendations. We will try that in our environment and update you here.

**Comment by jegasmile** [comment]
@extr3metech Its not a disk or RAM issue. we don't experience any disk and RAM alert from the server

**Comment by vikman90** [comment]
@jegasmile Let me close this issue due to inactivity. If the problem persists, and you can share the data with us, feel free to reopen the issue and ping me.

Cheers.
