### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26889]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/53

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![monitor-manager-Test_stress_B53-manager-pre-release_CPU](https://github.com/user-attachments/assets/c2ac8f16-868e-4dc5-8dc0-3a69feb32229)
![monitor-manager-Test_stress_B53-manager-pre-release_Disk](https://github.com/user-attachments/assets/ac6f765b-3230-4903-bc23-fbeec9b820df)
![monitor-manager-Test_stress_B53-manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/22ad7805-8ed4-45b0-a157-8c3181619d1c)
![monitor-manager-Test_stress_B53-manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/a6a44e9f-e727-4eda-9028-1377b09d5ce4)
![monitor-manager-Test_stress_B53-manager-pre-release_FD](https://github.com/user-attachments/assets/671c8233-18c8-4258-9453-57ea1d030815)
![monitor-manager-Test_stress_B53-manager-pre-release_PSS](https://github.com/user-attachments/assets/9160e139-ddb0-455b-8749-004f417e3463)
![monitor-manager-Test_stress_B53-manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/d4a8b855-7020-44b1-9804-9ea72f71b2a2)
![monitor-manager-Test_stress_B53-manager-pre-release_RSS](https://github.com/user-attachments/assets/8e76bbfe-a26b-4c04-8d99-387e39f6abaf)
![monitor-manager-Test_stress_B53-manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/5aa98704-0043-4be0-9b52-921d493c6f69)
![monitor-manager-Test_stress_B53-manager-pre-release_SWAP](https://github.com/user-attachments/assets/0646f64d-5faa-4e1c-a188-b1438f062fd9)
![monitor-manager-Test_stress_B53-manager-pre-release_USS](https://github.com/user-attachments/assets/81a05eee-267e-4385-8324-f62aa43c5640)
![monitor-manager-Test_stress_B53-manager-pre-release_VMS](https://github.com/user-attachments/assets/50fdd738-e09b-4afb-9d24-a4b339edf2a2)
![monitor-manager-Test_stress_B53-manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/b433b89c-6ea6-4f37-8f26-43118186224b)
![test_stress_B53_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/bc12f995-ae07-49bc-ae15-fcbfb636ef2d)
![test_stress_B53_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/e00413fd-9d12-492c-b323-41da74d7cf0b)
![test_stress_B53_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/c41afeea-273f-47d3-8729-fddbf64875a8)
![test_stress_B53_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/f2293414-3d3c-485f-92a3-cf62fedbf7a8)
![test_stress_B53_manager_analysisd_state csv_Number_Events](https://github.com/user-attachments/assets/627234e0-326b-4ca7-934e-50d0716ff4bd)
![test_stress_B53_manager_analysisd_state csv_Queues_state](https://github.com/user-attachments/assets/f0f88bc1-f35a-4123-a14a-0be172c583d3)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B53_manager_2024-11-14.zip](https://github.com/user-attachments/files/17803094/ossec_Test_stress_B53_manager_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803097/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-centos-Test_stress_B53_centos-pre-release_CPU](https://github.com/user-attachments/assets/736a5e31-f273-4c6e-9110-c646dc03c414)
![monitor-centos-Test_stress_B53_centos-pre-release_Disk](https://github.com/user-attachments/assets/bf740a89-9abf-49f0-a14a-2a247af4cae8)
![monitor-centos-Test_stress_B53_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/feb77c7b-c7cf-482e-832b-e7a116262af3)
![monitor-centos-Test_stress_B53_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/388cd291-881e-4592-b003-17345dd19e31)
![monitor-centos-Test_stress_B53_centos-pre-release_FD](https://github.com/user-attachments/assets/97023bc6-8213-4e00-b05e-3cf3db132ae0)
![monitor-centos-Test_stress_B53_centos-pre-release_PSS](https://github.com/user-attachments/assets/7996a7c7-6e9a-461f-a629-b23f8a4b9487)
![monitor-centos-Test_stress_B53_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/367b157d-e588-446a-a05c-f02f338db963)
![monitor-centos-Test_stress_B53_centos-pre-release_RSS](https://github.com/user-attachments/assets/2b29b421-77af-4afc-83df-ed8be5cb562a)
![monitor-centos-Test_stress_B53_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/f1e8f0e6-caa9-4f42-a4f5-c79bf84b1dd6)
![monitor-centos-Test_stress_B53_centos-pre-release_SWAP](https://github.com/user-attachments/assets/5b8588eb-79b1-4c5c-ba6e-f3781023f663)
![monitor-centos-Test_stress_B53_centos-pre-release_USS](https://github.com/user-attachments/assets/234bc60d-df20-48ee-8b5c-a1ef98b6f58f)
![monitor-centos-Test_stress_B53_centos-pre-release_VMS](https://github.com/user-attachments/assets/552421ca-7045-4a18-bd4a-325130c68be0)
![test_stress__centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/8fc16c55-97d9-4e3e-a082-fe34197fa4f3)
![test_stress__centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/d0d79140-8296-4732-a24b-f2f8dd39df8e)
![test_stress__centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/6275fc0c-a52c-4617-ab09-606645ce05e1)
![test_stress__centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/92e3bfea-0aae-43fd-82cf-7cb714e545cf)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B53_centos_2024-11-14.zip](https://github.com/user-attachments/files/17803118/ossec_Test_stress_B53_centos_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803120/csv.zip)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    
    ![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/07f90cda-13e8-4cb0-a7dc-0648236c4878)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/d57b075a-d85a-481e-b101-7fc06f3e32a6)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/b0a74791-c345-4dc6-b3fb-b156a69d3ebe)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/afd05bac-da57-4389-a0a4-3ddc663ae970)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/f687dcb6-f4c4-42a8-876e-d3a6cf4702b6)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/dd9b4597-3740-45b7-8dbc-95a9c1c66dca)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/5797a226-6dfc-4ca0-9a65-51cee8808099)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/bd1a15f1-9113-4bd7-a121-eaf9a34ef280)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/6de909ab-ad90-43e3-9cd0-558aeba2b088)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/725bf3e0-d0d3-4ef5-9af6-c42ce5268361)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/d1edcf38-e9ff-4cf8-b028-03f05009fe30)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/b2b72bfa-d68a-4a68-94a1-c7342f339668)
![monitor-ubuntu-Test_stress_B53_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/a93a58c5-04ef-4b55-bb12-6711246db391)
![test_stress_B53_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/77f63ae9-b296-431f-ab48-463a9793b146)
![test_stress_B53_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/c9af4f74-b0c6-472c-84dc-7ce1a29f99cd)
![test_stress_B53_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/f2df9bd3-4563-4cca-95aa-953ae21c4ce7)
![test_stress_B53_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/e86841c7-f8bb-4cbb-ad3a-f16ecd5a304c)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B53_ubuntu_2024-11-14.zip](https://github.com/user-attachments/files/17803144/ossec_Test_stress_B53_ubuntu_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803145/csv.zip)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

     ![monitor-windows-Test_stress_B53_windows-pre-release_CPU](https://github.com/user-attachments/assets/941d9681-8e04-4054-a83b-f7b20959a41a)
![monitor-windows-Test_stress_B53_windows-pre-release_Disk](https://github.com/user-attachments/assets/588cb3a9-7f8a-43d3-945e-268336436ae4)
![monitor-windows-Test_stress_B53_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/5cc59f9c-29ce-435d-a55f-619013c65536)
![monitor-windows-Test_stress_B53_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/5515dcc3-0583-4ab1-9852-b0633dee9a6d)
![monitor-windows-Test_stress_B53_windows-pre-release_Handles](https://github.com/user-attachments/assets/eb569128-8d67-4427-9ae1-514f65117c51)
![monitor-windows-Test_stress_B53_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/bd3ed115-51da-431c-bff8-e772244dc8a3)
![monitor-windows-Test_stress_B53_windows-pre-release_RSS](https://github.com/user-attachments/assets/534cf2bb-3bcc-4ec6-800e-31e6baf0bfa4)
![monitor-windows-Test_stress_B53_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/bb035204-98e7-4726-8d17-7e779f5d0682)
![monitor-windows-Test_stress_B53_windows-pre-release_USS](https://github.com/user-attachments/assets/8ebdc028-1e5d-4162-80c8-5a9499dd026a)
![monitor-windows-Test_stress_B53_windows-pre-release_VMS](https://github.com/user-attachments/assets/79f61944-446c-4dea-b200-bb29672fa556)
![monitor-windows-Test_stress_B53_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/7da05f26-5dbe-453b-9625-4d027e848fee)
![test_stress_B53_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/91d77d33-7af6-4725-a7b2-be742874006f)
![test_stress_B53_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/ac0831a4-b450-4d67-8cd6-7cea791e3e0d)
![test_stress_B53_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/ef4ba788-bd16-4c06-b5ca-94968eee4518)
![test_stress_B53_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/d2fc8239-7174-4cb2-ad4c-3aa1f7fa8f5a)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B53_windows_2024-11-14.zip](https://github.com/user-attachments/files/17803154/ossec_Test_stress_B53_windows_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803152/csv.zip)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle: 
Known issue
- https://github.com/wazuh/wazuh-jenkins/issues/5588
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/3293
- https://github.com/wazuh/wazuh-jenkins/issues/4656
- https://github.com/wazuh/wazuh/issues/22565

Not Known issue
- https://github.com/wazuh/wazuh-qa-automation/issues/118

**Comment by pro-akim** [comment]
# Analysis report

Compared to: https://github.com/wazuh/wazuh/issues/26501

## Graphs

### Ubuntu

### Centos

### Windows

### Manager

## Logs


<details><summary>Ubuntu</summary>

```
FileNotFoundError: [Errno 2] No such file or directory: '/proc/824183/cmdline'
 
AttributeError: _cache
 
ProcessLookupError: [Errno 3] No such process
 
2024/11/14 18:28:26 wazuh-modulesd:ciscat ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'. 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.4.26]:1514/tcp': 'Connection refused'. 
2024/11/14 18:29:29 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
2024/11/16 00:01:32 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
```
</details>



<details><summary>Centos</summary>

```
2024-11-14 18:31:00,219 Error getting something from a dict
 
KeyError: 'wazuh-modulesd'
 
AttributeError: _cache
 
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2106031/stat'
 
ProcessLookupError: [Errno 3] No such process
 
2024/11/17 00:00:59 wazuh-modulesd:ciscat ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory 
2024/11/17 00:00:59 wazuh-modulesd:ciscat ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml' 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.4.26]:1514/tcp': 'Connection refused'. 
2024/11/14 18:29:28 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
2024/11/15 00:30:17 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
```
</details>



<details><summary>Windows</summary>

```
2024/11/15 00:05:49 wazuh-modulesd:ciscat ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'. 
2024/11/14 18:30:21 wazuh-modulesd:ciscat ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory 
2024/11/15 00:05:49 wazuh-modulesd:ciscat WARNING: Interval overtaken. 
```
</details>



<details><summary>Manager</summary>

```
AttributeError: _cache
 
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2838286/stat'
 
ProcessLookupError: [Errno 3] No such process
 
2024/11/17 00:00:57 wazuh-modulesd:azure-logs ERROR: azure-activity: Returned error code: '1'. 
2024/11/14 18:27:39 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/14 18:27:39 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-4-26.ec2.internal', retrying until the connection is successful. 
2024/11/14 18:29:27 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
2024/11/14 18:29:45 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting... 
```
</details>

**Comment by joaquinsgi** [comment]
LGTM!

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message
