### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - ACTIVE-RESPONSE (2.5d)

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#26885]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | https://github.com/wazuh/wazuh/issues/26761                                         |
| **Main footprint metrics issue #** | https://github.com/wazuh/wazuh/issues/26795                                         |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/48/

---

<details><summary>Manager</summary>

<details><summary>Plots</summary>

![monitor-manager-test_stress_B48_manager-pre-release_CPU](https://github.com/user-attachments/assets/6b331a2f-3b22-40ba-afa7-789a7ff68302)
![monitor-manager-test_stress_B48_manager-pre-release_Disk](https://github.com/user-attachments/assets/c03ec52a-d118-4ad1-8e80-26b9dd5e9fc8)
![monitor-manager-test_stress_B48_manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/65f7d478-af26-4287-8026-b8ae25794ef8)
![monitor-manager-test_stress_B48_manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/0d257724-95a2-4f02-85c5-3e58eef03bbf)
![monitor-manager-test_stress_B48_manager-pre-release_FD](https://github.com/user-attachments/assets/203db930-19c7-4976-989c-e2a1ea1647b5)
![monitor-manager-test_stress_B48_manager-pre-release_PSS](https://github.com/user-attachments/assets/fa0ad59b-e62c-40e3-a369-8fcaea0201af)
![monitor-manager-test_stress_B48_manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/c15f154b-2061-41e8-8fcb-77a0ff679398)
![monitor-manager-test_stress_B48_manager-pre-release_RSS](https://github.com/user-attachments/assets/c69a972b-3de8-4d82-af4f-8f6055e70c9f)
![monitor-manager-test_stress_B48_manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/fb74580b-ea6c-4255-b4cf-4c8e522244b0)
![monitor-manager-test_stress_B48_manager-pre-release_SWAP](https://github.com/user-attachments/assets/0709d64e-263c-48c7-bf54-792228159110)
![monitor-manager-test_stress_B48_manager-pre-release_USS](https://github.com/user-attachments/assets/2ac60227-35c6-4860-8374-8aa772ab910c)
![monitor-manager-test_stress_B48_manager-pre-release_VMS](https://github.com/user-attachments/assets/7554c1eb-12f2-4a2c-9fa2-8d86d53cc488)
![monitor-manager-test_stress_B48_manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/00234d84-1adc-4adb-ae0d-2881afb14800)
![test_stress_B48_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/8be50163-790d-4fa2-9aff-400cd2bb583b)
![test_stress_B48_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/9aead927-7903-46a1-a09d-df6a307382ee)
![test_stress_B48_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/2ecaca9c-58c5-4e18-a2d0-d328c1500952)
![test_stress_B48_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/dbe0ab51-8275-4948-a814-097ffd706684)
![test_stress_B48_manager_analysisd_state_Number_Events](https://github.com/user-attachments/assets/da46d2b5-2fd1-4a37-b803-c8935cabb612)
![test_stress_B48_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/7966b6ef-ba7f-4c85-b4ef-8df578efd7ac)

</details>

<details><summary>Logs and configuration</summary>

 [ossec.zip](https://github.com/user-attachments/files/17800384/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-manager-test_stress_B48_manager-pre-release.zip](https://github.com/user-attachments/files/17800372/monitor-manager-test_stress_B48_manager-pre-release.zip)

[test_stress_B48_manager_analysisd_events.zip](https://github.com/user-attachments/files/17800377/test_stress_B48_manager_analysisd_events.zip)

[test_stress_B48_manager_analysisd_state.zip](https://github.com/user-attachments/files/17800379/test_stress_B48_manager_analysisd_state.zip)

[test_stress_B48_manager_remoted_state.zip](https://github.com/user-attachments/files/17800382/test_stress_B48_manager_remoted_state.zip)

</details>

</details>

<details><summary>Centos agent</summary>

<details><summary>Plots</summary>

![monitor-agent-test_stress_B48_centos-pre-release_CPU](https://github.com/user-attachments/assets/bd278537-eef3-4fd1-9833-ee9277f03768)
![monitor-agent-test_stress_B48_centos-pre-release_Disk](https://github.com/user-attachments/assets/926dfdcc-dfcd-4b5b-80b9-42341c5bd506)
![monitor-agent-test_stress_B48_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/658f4743-f01f-47f9-b1ec-9539b867f3f3)
![monitor-agent-test_stress_B48_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/bc021d8f-0901-42e5-a216-7adb51f114b9)
![monitor-agent-test_stress_B48_centos-pre-release_FD](https://github.com/user-attachments/assets/32efc8a9-8585-49cb-8795-e550db78736d)
![monitor-agent-test_stress_B48_centos-pre-release_PSS](https://github.com/user-attachments/assets/56874bbf-436c-491b-a974-569df6b7ffb7)
![monitor-agent-test_stress_B48_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/f31d7fdd-a5be-40c5-940f-d89dec074b24)
![monitor-agent-test_stress_B48_centos-pre-release_RSS](https://github.com/user-attachments/assets/78058ec7-8f2f-4025-9a9a-11af2097702b)
![monitor-agent-test_stress_B48_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/03704970-392f-44c6-9995-906dfa2be865)
![monitor-agent-test_stress_B48_centos-pre-release_SWAP](https://github.com/user-attachments/assets/454cfe9e-5947-48ec-8242-38e495cc724d)
![monitor-agent-test_stress_B48_centos-pre-release_USS](https://github.com/user-attachments/assets/2611efab-3ed0-407a-90c6-03eef1f0a3dc)
![monitor-agent-test_stress_B48_centos-pre-release_VMS](https://github.com/user-attachments/assets/b82c2f87-6a84-43d3-b248-1ea5a0c3894a)
![monitor-agent-test_stress_B48_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/8a47ba88-e23e-4472-9e0e-46c117307c61)
![test_stress_B48_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/9707bf7e-bb6f-477f-89ba-b4920fe555ef)
![test_stress_B48_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/c29daa2d-36aa-4158-9a06-5eebb751b8db)
![test_stress_B48_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/dac04e46-c083-4b26-a0de-67f3bdf40eb7)
![test_stress_B48_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/32e968fd-fd4b-49a8-b924-bff46f14c928)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17800891/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-agent-test_stress_B48_centos-pre-release.zip](https://github.com/user-attachments/files/17800887/monitor-agent-test_stress_B48_centos-pre-release.zip)

[test_stress_B48_centos_agentd_state.zip](https://github.com/user-attachments/files/17800889/test_stress_B48_centos_agentd_state.zip)

</details>

</details>

<details><summary>Ubuntu agent</summary>

<details><summary>Plots</summary>

![monitor-agent-test_stress_B48_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/80948f72-eba7-495d-bf40-533d519b946e)
![monitor-agent-test_stress_B48_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/0c5cb46d-1ee0-4777-9a7c-e395b75baea0)
![monitor-agent-test_stress_B48_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/40fc0d60-97bc-40fb-bc8c-377572edcb39)
![monitor-agent-test_stress_B48_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/c4d4a162-57df-4e37-ac85-e62e7e533bcf)
![monitor-agent-test_stress_B48_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/22425247-bf93-4308-8c31-a52af335190a)
![monitor-agent-test_stress_B48_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/422dad72-585b-44ec-a378-667de6eb5064)
![monitor-agent-test_stress_B48_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/b88d514c-2420-4831-95da-da36505e8810)
![monitor-agent-test_stress_B48_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/6af39756-4571-4a8b-bbd7-ae3b23942df9)
![monitor-agent-test_stress_B48_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/40adb973-09dd-4d13-a704-6c0caca610a2)
![monitor-agent-test_stress_B48_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/0c35db7f-7c3f-44b9-b8c8-7ee4074445b2)
![monitor-agent-test_stress_B48_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/6ac347d5-a0f1-4947-95a5-aa736a052844)
![monitor-agent-test_stress_B48_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/975d19c8-e54a-44a8-90a4-70364cac75be)
![monitor-agent-test_stress_B48_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/fbabc3ce-53ef-47f3-822d-14edf3da1c98)
![test_stress_B48_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/5f2bf26a-829e-42af-817c-d9549686698e)
![test_stress_B48_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/de7f0a3e-c131-4b8b-80b9-3fa316d87538)
![test_stress_B48_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/009ecdc1-6ea8-4f27-8b11-40d6e44db503)
![test_stress_B48_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/ffd807f8-419c-45de-bf1c-b1d5416aeedc)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17801286/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-agent-test_stress_B48_ubuntu-pre-release.zip](https://github.com/user-attachments/files/17801291/monitor-agent-test_stress_B48_ubuntu-pre-release.zip)

[test_stress_B48_ubuntu_agentd_state.zip](https://github.com/user-attachments/files/17801292/test_stress_B48_ubuntu_agentd_state.zip)

</details>

</details>

<details><summary>Windows agent</summary>

<details><summary>Plots</summary>

![monitor-winagent-test_stress_B48_windows-pre-release_CPU](https://github.com/user-attachments/assets/f7b3e771-dbfb-493d-992d-5e54dd1e30d2)
![monitor-winagent-test_stress_B48_windows-pre-release_Disk](https://github.com/user-attachments/assets/9ec8cd03-73d2-4fe8-9ceb-5d453a38a8c4)
![monitor-winagent-test_stress_B48_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/c4150eec-03df-464d-a5a4-4f125f074ed0)
![monitor-winagent-test_stress_B48_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/9cb256d8-a740-4619-a88b-a4a7bfa89e41)
![monitor-winagent-test_stress_B48_windows-pre-release_Handles](https://github.com/user-attachments/assets/07944178-0060-448a-837a-a3b76299d6fe)
![monitor-winagent-test_stress_B48_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/4804c73b-9d41-4e44-a303-a04119ffd114)
![monitor-winagent-test_stress_B48_windows-pre-release_RSS](https://github.com/user-attachments/assets/b9054b79-e349-4c77-b119-f769b39b6a7e)
![monitor-winagent-test_stress_B48_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/82632fdc-9d2c-4da5-ba6a-39bc93584d01)
![monitor-winagent-test_stress_B48_windows-pre-release_USS](https://github.com/user-attachments/assets/39e87f59-0080-4215-aaba-d6924b5c1c67)
![monitor-winagent-test_stress_B48_windows-pre-release_VMS](https://github.com/user-attachments/assets/00447b52-d1a7-4291-aeed-04d50da3ba9c)
![monitor-winagent-test_stress_B48_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/82197c90-03dc-4851-9f71-eeb58279ec61)
![test_stress_B48_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/b92f1fe1-ca29-4f4a-a54d-e85e2c425c5d)
![test_stress_B48_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/3e6dd09d-cfce-4e0c-a477-d003c574bb01)
![test_stress_B48_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/67e7add2-87ae-4bab-891e-3c7bb96fdd0f)
![test_stress_B48_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/c85f61de-ff29-474d-bf60-0751049ad5c6)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17801809/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-winagent-test_stress_B48_windows-pre-release.csv](https://github.com/user-attachments/files/17801833/monitor-winagent-test_stress_B48_windows-pre-release.csv)
[test_stress_B48_windows_agentd_state.csv](https://github.com/user-attachments/files/17801837/test_stress_B48_windows_agentd_state.csv)

</details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### Known issues
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh/issues/22565

**Comment by santipadilla** [comment]
Ready Plots, logs and configuration, and CSV, ready to analyze, moved to on hold until start of analysis.

**Comment by pro-akim** [comment]
# Analysis report

Compared to: https://github.com/wazuh/wazuh/issues/26507

## Graphs :green_circle:

### Centos
PSS, RSS, USS: decrease of logcollector
VMS: decrease of modulesd
Agentd_number_of_generated_events and messages: small decrease

### Windows
VMS: less fragmented pattern of agent.exe

### Ubuntu
Disk decrease of agentd
VMS: decrease of modulesd

### Manager
Disk_read: small increase of execd

## Logs :yellow_circle:


<details><summary>Centos</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:32:45 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:32:45 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.0.89]:1514/tcp': 'Connection refused'. 
```
</details>



<details><summary>Windows</summary>

</details>



<details><summary>Ubuntu</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:32:45 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:32:45 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.0.89]:1514/tcp': 'Connection refused'. 
```
</details>



<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/14 18:30:47 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/14 18:30:47 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-0-89.ec2.internal', retrying until the connection is successful.
```

- Reported: https://github.com/wazuh/wazuh/issues/24509 - Not Known issue
```
2024/11/14 18:32:45 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
```
</details>

**Comment by santipadilla** [comment]
LGTM
