### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - SYSCOLLECTOR (2.5d)

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#26886]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                         |
| **Main footprint metrics issue #** | #26795                                         |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/49/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

   ![monitor-manager-test_stress_B49_manager-pre-release_CPU](https://github.com/user-attachments/assets/8668e3e6-4b67-4f27-b275-b801da6ab477)
   ![monitor-manager-test_stress_B49_manager-pre-release_Disk](https://github.com/user-attachments/assets/51561446-a924-4e33-a328-9adeea0ee984)
   ![monitor-manager-test_stress_B49_manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/6d4c78dd-22ba-448d-b35d-5770bde91af4)
   ![monitor-manager-test_stress_B49_manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/3877b265-f68a-4a2e-8e4a-bedea810e44b)
   ![monitor-manager-test_stress_B49_manager-pre-release_FD](https://github.com/user-attachments/assets/8a51b94b-6e2c-4c98-bf48-452b37c7d632)
   ![monitor-manager-test_stress_B49_manager-pre-release_PSS](https://github.com/user-attachments/assets/6b451e34-ecac-4598-a122-d5ccfb65de80)
   ![monitor-manager-test_stress_B49_manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/cd463a6c-16b7-4a85-9123-aa9300407666)
   ![monitor-manager-test_stress_B49_manager-pre-release_RSS](https://github.com/user-attachments/assets/d0c1c178-08d6-415d-b31a-65c5fd9df78b)
   ![monitor-manager-test_stress_B49_manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/531a9d91-b6c1-4160-bcbd-6ed9ad97b2d6)
   ![monitor-manager-test_stress_B49_manager-pre-release_SWAP](https://github.com/user-attachments/assets/d383784c-2e90-4414-b09b-ba58c8f5a69d)
   ![monitor-manager-test_stress_B49_manager-pre-release_USS](https://github.com/user-attachments/assets/952cd8e0-50ed-48c1-9b75-0571f8e7b848)
   ![monitor-manager-test_stress_B49_manager-pre-release_VMS](https://github.com/user-attachments/assets/088b1f37-4658-45dd-9da2-f528a91b9d08)
   ![monitor-manager-test_stress_B49_manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/df47cf66-1820-4b9f-a7a9-c121c0c680be)
   ![test_stress_B49_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/465c7224-bba9-4352-9513-00d34b63fa75)
   ![test_stress_B49_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/a1d02373-f159-426d-b478-fa7b48ca143d)
   ![test_stress_B49_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/f8ea10c9-95be-445c-ab1b-20f54f1aad2d)
   ![test_stress_B49_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/f5bcfc19-c297-47de-bb29-44f167cd90e5)
   ![test_stress_B49_manager_analysisd_state_Number_Events](https://github.com/user-attachments/assets/98b99366-e273-42b7-90b5-340eb3479b49)
   ![test_stress_B49_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/70ecd079-726c-47f6-938d-29e1072247f0)

    </details>
+ <details><summary>Logs and configuration</summary>

   [ossec.zip](https://github.com/user-attachments/files/17800939/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

   [test_stress_B49_manager_analysisd_events.csv](https://github.com/user-attachments/files/17800963/test_stress_B49_manager_analysisd_events.csv)
   [test_stress_B49_manager_analysisd_state.csv](https://github.com/user-attachments/files/17800967/test_stress_B49_manager_analysisd_state.csv)
   [test_stress_B49_manager_remoted_state.csv](https://github.com/user-attachments/files/17800969/test_stress_B49_manager_remoted_state.csv)
   [monitor-manager.zip](https://github.com/user-attachments/files/17800982/monitor-manager-test_stress_B49_manager-pre-release.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

   ![monitor-agent-test_stress_B49_centos-pre-release_CPU](https://github.com/user-attachments/assets/d720a7a1-a567-4885-9c5f-2c4b912e2bcc)
   ![monitor-agent-test_stress_B49_centos-pre-release_Disk](https://github.com/user-attachments/assets/c6b6dc0d-2349-4e0e-a4e6-c874a96178d0)
   ![monitor-agent-test_stress_B49_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/0dc06fba-f8ff-49c2-9b0b-da29d4731cc9)
   ![monitor-agent-test_stress_B49_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/0f6ebd1b-c024-4625-bc1c-9f9fe0207465)
   ![monitor-agent-test_stress_B49_centos-pre-release_FD](https://github.com/user-attachments/assets/dcb9d956-ff4a-4336-9a25-3bc00d75d888)
   ![monitor-agent-test_stress_B49_centos-pre-release_PSS](https://github.com/user-attachments/assets/6ae6d591-cce5-4682-a01a-89452e5d0f47)
   ![monitor-agent-test_stress_B49_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/18b09271-f249-491a-9328-0a636b364630)
   ![monitor-agent-test_stress_B49_centos-pre-release_RSS](https://github.com/user-attachments/assets/ba4a6495-f7c1-487b-9bc9-71b4078ad74c)
   ![monitor-agent-test_stress_B49_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/f01c569a-36d4-43c2-9140-4f5104065a8b)
   ![monitor-agent-test_stress_B49_centos-pre-release_SWAP](https://github.com/user-attachments/assets/56d87808-a605-4221-a534-88a69a129a85)
   ![monitor-agent-test_stress_B49_centos-pre-release_USS](https://github.com/user-attachments/assets/4ec10c92-116e-4f15-befb-8dd1db9d8fcc)
   ![monitor-agent-test_stress_B49_centos-pre-release_VMS](https://github.com/user-attachments/assets/8a02a9c6-2575-436a-b40b-6ca808e4cd98)
   ![monitor-agent-test_stress_B49_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/d7a3a849-685f-400c-8e28-fee4af23a67e)
   ![test_stress_B49_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/4cc5d1ec-b5e0-4aac-926a-2fbe6373ef8f)
   ![test_stress_B49_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/04bc6575-c7c1-4125-9867-abde0d85d5c8)
   ![test_stress_B49_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/006f9803-085e-4de1-88a1-f588cc1d2f33)
   ![test_stress_B49_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/fb6af74f-cfd5-41a1-8212-1313775c092b)

    </details>
+ <details><summary>Logs and configuration</summary>

   [ossec.zip](https://github.com/user-attachments/files/17800988/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

   [monitor-agent-test_stress_B49_centos-pre-release.csv](https://github.com/user-attachments/files/17800993/monitor-agent-test_stress_B49_centos-pre-release.csv)
   [test_stress_B49_centos_agentd_state.csv](https://github.com/user-attachments/files/17800994/test_stress_B49_centos_agentd_state.csv)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

   ![monitor-agent-test_stress_B49_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/8d7051a5-9785-4878-8a7d-d58e681b7d60)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/33a8f660-9b0b-4bee-990d-4e68360b8f02)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/63e745ca-df34-45d4-90be-ae88fd7070f2)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/e230c8a7-17d7-4f52-b606-6e80b01cca78)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/4a396e04-998d-4c83-a183-b91b2672c123)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/d8a96947-d3d6-4ae6-898a-9a306fc5f638)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/d8fe842e-34b8-4ec6-800f-3324ba894e6f)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/4f1f2556-1b64-4705-9361-c0998ff7560a)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/dba3b851-f452-40b1-b9d3-f15aa86b50bc)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/75fcb543-ad65-4f0d-90a2-eafae55b436f)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/a937f219-82c6-4029-bb22-dbdde305800d)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/8a0814a2-3dbf-4ee6-a6f6-9e28d5041211)
   ![monitor-agent-test_stress_B49_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/d4cc6a21-1d13-4c84-99ed-6a0bdb852316)
   ![test_stress_B49_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/ddee7e61-f28d-4152-9fcb-c14f183132de)
   ![test_stress_B49_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/a7f7d6f6-8d1d-4d8d-b929-5ef670274c7a)
   ![test_stress_B49_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/3e92c1ea-a771-4a53-a9f1-805f016937f1)
   ![test_stress_B49_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/6a1552f9-094e-4192-8c36-266e8cbbcc84)

    </details>
+ <details><summary>Logs and configuration</summary>

   [ossec.zip](https://github.com/user-attachments/files/17801004/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

   [monitor-agent-test_stress_B49_ubuntu-pre-release.csv](https://github.com/user-attachments/files/17801009/monitor-agent-test_stress_B49_ubuntu-pre-release.csv)
   [test_stress_B49_ubuntu_agentd_state.csv](https://github.com/user-attachments/files/17801010/test_stress_B49_ubuntu_agentd_state.csv)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

   ![monitor-winagent-test_stress_B49_windows-pre-release_CPU](https://github.com/user-attachments/assets/c199a41d-db9a-4b72-93bd-19818e6a26ab)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Disk](https://github.com/user-attachments/assets/50e692fd-54d2-439c-af03-9d01b82533be)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/fbd51156-b851-47f3-bf89-cc1915cf4f4d)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/96758172-2117-4067-bde0-bbd5929b899f)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Handles](https://github.com/user-attachments/assets/0e49954b-52dd-4059-b81e-90e24ec4567a)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/a283c899-2d8a-4243-90a3-a396e1023496)
   ![monitor-winagent-test_stress_B49_windows-pre-release_RSS](https://github.com/user-attachments/assets/3be911a1-cea6-4767-8902-61079d2238fc)
   ![monitor-winagent-test_stress_B49_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/90d1fc8b-8ca6-48ad-8dd8-5be0ab0973b4)
   ![monitor-winagent-test_stress_B49_windows-pre-release_USS](https://github.com/user-attachments/assets/83a32fd2-fc04-4a7d-9da5-4c95631261b1)
   ![monitor-winagent-test_stress_B49_windows-pre-release_VMS](https://github.com/user-attachments/assets/7695f5db-fc49-4996-973f-31a6ba9c330c)
   ![monitor-winagent-test_stress_B49_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/989ca603-0c8b-426a-ad14-d4f3e88af997)
   ![test_stress_B49_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/d464491d-f0c8-49fe-9c12-feee3fbcba1e)
   ![test_stress_B49_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/c4b081e2-2398-474a-82d4-cc09f501e604)
   ![test_stress_B49_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/0b3aa833-99de-4daf-a789-9f71b3197805)
   ![test_stress_B49_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/c2175d6c-5993-440f-b75c-aa6c9da3925b)

    </details>
+ <details><summary>Logs and configuration</summary>

   [ossec.zip](https://github.com/user-attachments/files/17801016/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

   [monitor-winagent-test_stress_B49_windows-pre-release.csv](https://github.com/user-attachments/files/17801021/monitor-winagent-test_stress_B49_windows-pre-release.csv)
   [test_stress_B49_windows_agentd_state.csv](https://github.com/user-attachments/files/17801022/test_stress_B49_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

---

## Conclusions 🟡 

Compared to https://github.com/wazuh/wazuh/issues/26657

### Known Issues

- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh/issues/24509
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh/issues/18179

**Comment by rafabailon** [comment]
# Analysis Report

## Graph Report 🔵 

## Log Report 🔵

**Comment by MARCOSD4** [comment]
LGTM

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message
