### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - ALL-EXCEPT-LOGCOLLECTOR (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26890]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/55/

---

<details><summary>Manager</summary>

<details><summary>Plots</summary>

![monitor-manager-test_stress_B55_manager-pre-release_CPU](https://github.com/user-attachments/assets/3bf895fa-65f9-4f2e-aca8-9278849f25e0)
![monitor-manager-test_stress_B55_manager-pre-release_Disk](https://github.com/user-attachments/assets/ba38e99f-873c-43b6-baba-91441aaca675)
![monitor-manager-test_stress_B55_manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/d9c6fc83-a5f4-490f-b6b4-919143080c90)
![monitor-manager-test_stress_B55_manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/b7b56f37-db84-4dc9-9985-9ed0fc890b9d)
![monitor-manager-test_stress_B55_manager-pre-release_FD](https://github.com/user-attachments/assets/2cb2a737-5e02-4ac8-81ae-6e8cb98acb15)
![monitor-manager-test_stress_B55_manager-pre-release_PSS](https://github.com/user-attachments/assets/50654c36-3189-4d27-9e2e-73f44e9c0000)
![monitor-manager-test_stress_B55_manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/8f5deb61-1822-48e2-8396-e9121748c199)
![monitor-manager-test_stress_B55_manager-pre-release_RSS](https://github.com/user-attachments/assets/98b9f360-16d9-4461-a0f6-a8ac52089b9e)
![monitor-manager-test_stress_B55_manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/61b7d724-c8fa-4a65-b94a-ea4c7e66e5bb)
![monitor-manager-test_stress_B55_manager-pre-release_SWAP](https://github.com/user-attachments/assets/cbd0517e-7640-41de-b346-3209e008f06c)
![monitor-manager-test_stress_B55_manager-pre-release_USS](https://github.com/user-attachments/assets/9350db45-7c5a-411e-bdb9-a88cad2f92a9)
![monitor-manager-test_stress_B55_manager-pre-release_VMS](https://github.com/user-attachments/assets/96a8d3bd-f48b-44f4-8b3a-3376f7956637)
![monitor-manager-test_stress_B55_manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/fdb2b757-b8be-46ce-8d4b-e0c6d80159e1)
![test_stress_B55_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/297dc0b6-b771-4497-8936-99cc4280ab62)
![test_stress_B55_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/2d1e298e-0cb0-4ed3-a30f-2c0956bbedb8)
![test_stress_B55_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/ca09dd53-61f6-48ba-8e13-84fdc702f2d2)
![test_stress_B55_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/0f259ad0-2278-494f-9de1-88d2b08f70f6)
![test_stress_B55_manager_analysisd_state_Number_Events](https://github.com/user-attachments/assets/8e744bfc-dd4c-4d2d-9573-e1d14dc04127)
![test_stress_B55_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/ea3d7726-db96-4337-a43a-bd9051842cd6)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17803963/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-manager-test_stress_B55_manager-pre-release.zip](https://github.com/user-attachments/files/17803968/monitor-manager-test_stress_B55_manager-pre-release.zip)

[test_stress_B55_manager_analysisd_events.zip](https://github.com/user-attachments/files/17803969/test_stress_B55_manager_analysisd_events.zip)

[test_stress_B55_manager_analysisd_state.zip](https://github.com/user-attachments/files/17803971/test_stress_B55_manager_analysisd_state.zip)

[test_stress_B55_manager_remoted_state.zip](https://github.com/user-attachments/files/17803972/test_stress_B55_manager_remoted_state.zip)

</details>

</details>

<details><summary>Centos agent</summary>

<details><summary>Plots</summary>

![monitor-agent-test_stress_B55_centos-pre-release_CPU](https://github.com/user-attachments/assets/ab011e46-624e-4403-9312-2195457e19e6)
![monitor-agent-test_stress_B55_centos-pre-release_Disk](https://github.com/user-attachments/assets/12c46be9-81a1-43d3-8dbe-3caa8221e9f6)
![monitor-agent-test_stress_B55_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/6320e386-ab71-49b6-9882-cdebd3618653)
![monitor-agent-test_stress_B55_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/b212e3ad-2dc6-4e56-9746-862644388e7f)
![monitor-agent-test_stress_B55_centos-pre-release_FD](https://github.com/user-attachments/assets/6e4c2752-f1b1-4c47-9d4e-684c2e1f258c)
![monitor-agent-test_stress_B55_centos-pre-release_PSS](https://github.com/user-attachments/assets/65ef554d-8ed4-4a8f-859c-5cf7889f8412)
![monitor-agent-test_stress_B55_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/a64da389-96b2-4493-aea4-523876c2d1fe)
![monitor-agent-test_stress_B55_centos-pre-release_RSS](https://github.com/user-attachments/assets/80ea3f5b-e3d0-4534-a335-940899f1182b)
![monitor-agent-test_stress_B55_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/87c779da-f5fd-4a7b-b35c-dc2b9f65868a)
![monitor-agent-test_stress_B55_centos-pre-release_SWAP](https://github.com/user-attachments/assets/2dfdf505-5cad-4a82-b396-516871615f76)
![monitor-agent-test_stress_B55_centos-pre-release_USS](https://github.com/user-attachments/assets/824d6806-c218-4f6f-9d78-4e48412644ed)
![monitor-agent-test_stress_B55_centos-pre-release_VMS](https://github.com/user-attachments/assets/5b0c0903-e82e-438a-ad5d-565cb108c626)
![monitor-agent-test_stress_B55_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/750c2c84-e76d-4bc7-b51d-fb088f6cc299)
![test_stress_B55_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/d3671373-89a4-423f-927c-8c68cdfab346)
![test_stress_B55_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/67a715ef-e3f3-46d5-92e0-71e5b413cb01)
![test_stress_B55_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/4d6a95d1-691a-4988-9d51-5f93d3def37d)
![test_stress_B55_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/2e562e58-4cb1-4c80-a6c3-9ea302db1967)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17814482/ossec.zip)

</details>

<details><summary>CSV</summary>

[csv.zip](https://github.com/user-attachments/files/17814481/csv.zip)

</details>

</details>

<details><summary>Ubuntu agent</summary>

<details><summary>Plots</summary>

![monitor-agent-test_stress_B55_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/e14d672f-0248-412a-b1f9-e62f38c53f43)
![monitor-agent-test_stress_B55_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/974f4acd-f7ed-4aa6-b097-703bc5d421b6)
![monitor-agent-test_stress_B55_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/a18010a9-235e-4fdc-b395-c0c6b1e6d301)
![monitor-agent-test_stress_B55_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/0a23b45f-5cc5-49e8-83f6-283d533ceaaa)
![monitor-agent-test_stress_B55_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/79b5f9ee-dab6-4531-830b-f449e15e5735)
![monitor-agent-test_stress_B55_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/8e1934a4-193f-4223-9b78-eed44ec18cd2)
![monitor-agent-test_stress_B55_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/2bfb25ca-249d-46be-a024-1be9dca24530)
![monitor-agent-test_stress_B55_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/2f239a5b-4705-44d5-ad24-dc75e2df2a03)
![monitor-agent-test_stress_B55_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/9b957fd9-e946-4eb9-ab62-416f94ba8112)
![monitor-agent-test_stress_B55_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/d5e53d27-1ce0-4203-8b77-d42a4f6a6929)
![monitor-agent-test_stress_B55_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/17dc58ce-62e8-42c4-8306-2b0946551a3c)
![monitor-agent-test_stress_B55_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/da125129-700e-4517-af08-4dedce63db45)
![monitor-agent-test_stress_B55_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/cac0a350-625c-4de0-b892-71454b5fccb1)
![test_stress_B55_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/cf5efb94-302a-4489-8ddd-1320b7b9c49e)
![test_stress_B55_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/6a7388cd-8cf0-4598-8d77-194a0b32019c)
![test_stress_B55_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/992c45f1-0947-4011-8862-6c7c645ecac5)
![test_stress_B55_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/bbf59625-8554-46ae-9280-09e68859384c)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17814503/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-agent-test_stress_B55_ubuntu-pre-release.zip](https://github.com/user-attachments/files/17814501/monitor-agent-test_stress_B55_ubuntu-pre-release.zip)

[test_stress_B55_ubuntu_agentd_state.zip](https://github.com/user-attachments/files/17814502/test_stress_B55_ubuntu_agentd_state.zip)

</details>

</details>

<details><summary>Windows agent</summary>

<details><summary>Plots</summary>

![monitor-winagent-test_stress_B55_windows-pre-release_CPU](https://github.com/user-attachments/assets/55468f43-6863-4f5e-8ff7-4e8fb510fdfc)
![monitor-winagent-test_stress_B55_windows-pre-release_Disk](https://github.com/user-attachments/assets/6cbbaf3f-194e-40f4-aa84-a7193aaa6451)
![monitor-winagent-test_stress_B55_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/6cde1e48-4e5e-46a3-b723-e0e3daed2f08)
![monitor-winagent-test_stress_B55_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/92b49b8d-8ce8-4891-bfc5-bcf85e476d9b)
![monitor-winagent-test_stress_B55_windows-pre-release_Handles](https://github.com/user-attachments/assets/31ca054d-622e-4f12-a0ac-6308c34fa1c7)
![monitor-winagent-test_stress_B55_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/7a52c256-a1cf-451c-85a5-486e692aa396)
![monitor-winagent-test_stress_B55_windows-pre-release_RSS](https://github.com/user-attachments/assets/854299ab-15ba-4f09-aab7-3a5dcf4981e0)
![monitor-winagent-test_stress_B55_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/928060c0-3a3a-4178-91dc-42b41dbb2a2c)
![monitor-winagent-test_stress_B55_windows-pre-release_USS](https://github.com/user-attachments/assets/9a937f4b-cd18-41f1-b0ed-9199ab816e03)
![monitor-winagent-test_stress_B55_windows-pre-release_VMS](https://github.com/user-attachments/assets/b3f0f92b-d8ec-4072-aa96-5ede4332ee06)
![monitor-winagent-test_stress_B55_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/0708b76e-d5e9-47a7-a8d0-b34487d8dc81)
![test_stress_B55_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/e02b4b23-aad2-44a6-a210-6eb27c62bb2f)
![test_stress_B55_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/22dd702a-a8de-43ad-9f06-83b4d0c0a297)
![test_stress_B55_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/33c67c99-e631-4ddc-986d-a0330b1184a5)
![test_stress_B55_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/9299cd99-de56-4e1c-bd63-4ed09a65bb6c)

</details>

<details><summary>Logs and configuration</summary>

[ossec.zip](https://github.com/user-attachments/files/17814458/ossec.zip)

</details>

<details><summary>CSV</summary>

[monitor-winagent-test_stress_B55_windows-pre-release.csv](https://github.com/user-attachments/files/17814461/monitor-winagent-test_stress_B55_windows-pre-release.csv)
[test_stress_B55_windows_agentd_state.csv](https://github.com/user-attachments/files/17814462/test_stress_B55_windows_agentd_state.csv)

</details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle: 

Plots compared to https://github.com/wazuh/wazuh/issues/26605

#### Known issues

- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/4481
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh/issues/20608
- https://github.com/wazuh/wazuh/issues/12074
- https://github.com/wazuh/wazuh/issues/18995

**Comment by santipadilla** [comment]
## Update

Ready plots, logs and configuration, and CSV, ready to analyze.

**Comment by santipadilla** [comment]
# Analysis report

## Logs :black_circle:

**Comment by rafabailon** [comment]
### LGTM

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message
