### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - LOGCOLLECTOR,SYSCHECK (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26898]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/52

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

   
    ![monitor-manager-test_stress_B52_manager-pre-release_CPU](https://github.com/user-attachments/assets/2280de21-2665-42c3-8c81-b8e5f464af69)
    ![monitor-manager-test_stress_B52_manager-pre-release_Disk](https://github.com/user-attachments/assets/56c0bcb7-2d76-47ae-a39f-a1369b24619b)
    ![monitor-manager-test_stress_B52_manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/2daa0a42-7f18-4620-8637-9f85a0e31510)
    ![monitor-manager-test_stress_B52_manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/61240911-66ca-406d-a80b-71823563777d)
    ![monitor-manager-test_stress_B52_manager-pre-release_FD](https://github.com/user-attachments/assets/1034d8a3-9751-49c0-802d-a6146a5f9ffd)
    ![monitor-manager-test_stress_B52_manager-pre-release_PSS](https://github.com/user-attachments/assets/993f30d9-6ee4-4337-989d-a2cabbf0e30b)
    ![monitor-manager-test_stress_B52_manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/23444d7f-09ce-4dd5-a354-08f914e09033)
    ![monitor-manager-test_stress_B52_manager-pre-release_RSS](https://github.com/user-attachments/assets/b9c67bf3-fc34-4287-827d-c136d7a2e987)
    ![monitor-manager-test_stress_B52_manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/48214de8-86b4-4e63-8175-1446be1ffa2b)
    ![monitor-manager-test_stress_B52_manager-pre-release_SWAP](https://github.com/user-attachments/assets/3168355a-63a2-45d4-9abc-614fffc9ef72)
    ![monitor-manager-test_stress_B52_manager-pre-release_USS](https://github.com/user-attachments/assets/a34a537b-e136-44e6-b336-e8417a08d67a)
    ![monitor-manager-test_stress_B52_manager-pre-release_VMS](https://github.com/user-attachments/assets/4ae6d091-3cb8-4ecf-8f6c-4a6e99716cbe)
    ![monitor-manager-test_stress_B52_manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/e5d44851-2711-467c-ab16-42cc4225dc37)
    ![test_stress_B52_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/be215392-f994-4685-b778-584b3441a942)
    ![test_stress_B52_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/3738a4bb-a6a3-4cda-acfe-7614717bc1e9)
    ![test_stress_B52_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/e74480b5-fce7-4dc7-a669-d3823c0d8259)
    ![test_stress_B52_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/734441cc-6878-4502-895f-8a6513ea541e)
    ![test_stress_B52_manager_analysisd_state_Number_Events](https://github.com/user-attachments/assets/0ceaad6f-6912-4e52-a658-b91e5c6ba759)
     ![test_stress_B52_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/312d063e-3253-47ff-a933-5728f1387bcd)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803486/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803487/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-test_stress_B52_centos-pre-release_CPU](https://github.com/user-attachments/assets/cedd57c4-8db4-4111-afd5-956003a85834)
    ![monitor-agent-test_stress_B52_centos-pre-release_Disk](https://github.com/user-attachments/assets/45974d20-a0b8-4d76-9a41-ba507081fdb3)
    ![monitor-agent-test_stress_B52_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/f1d0f63f-a8f4-4cf5-86a3-cf07864fb701)
    ![monitor-agent-test_stress_B52_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/baee6062-2791-421d-8750-f6f92a506ce4)
    ![monitor-agent-test_stress_B52_centos-pre-release_FD](https://github.com/user-attachments/assets/2694a860-8bda-4457-9e20-04511380dc09)
    ![monitor-agent-test_stress_B52_centos-pre-release_PSS](https://github.com/user-attachments/assets/bd5d618e-aaec-4707-9802-999654395892)
    ![monitor-agent-test_stress_B52_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/26d59398-e3fb-4e6b-a954-5133aab26f21)
    ![monitor-agent-test_stress_B52_centos-pre-release_RSS](https://github.com/user-attachments/assets/e8f41399-e8e8-4d45-b0ea-fd8cbbbc8bf7)
    ![monitor-agent-test_stress_B52_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/2726c923-ca53-4889-8867-2a6c3bb7ad4e)
    ![monitor-agent-test_stress_B52_centos-pre-release_SWAP](https://github.com/user-attachments/assets/71fe279e-9aae-4d51-bfdc-989d354d0392)
    ![monitor-agent-test_stress_B52_centos-pre-release_USS](https://github.com/user-attachments/assets/4aafd924-6558-4535-922c-8f19b65a313e)
    ![monitor-agent-test_stress_B52_centos-pre-release_VMS](https://github.com/user-attachments/assets/a405ee42-3c34-4b1f-9f58-9f145d7ab0f5)
    ![monitor-agent-test_stress_B52_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/134e7047-f1f5-46ad-b539-61dfcbd0d095)
    ![test_stress_B52_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/f93c5665-3b00-4b33-8c52-2287e8c666b9)
    ![test_stress_B52_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/2c2affef-63d3-4f7b-8d2f-12af874046fd)
    ![test_stress_B52_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/3c798469-66ad-4624-84d6-6ddde394565c)
    ![test_stress_B52_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/c00a2356-bd7c-4c86-8726-848878c0bf1c)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803501/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803503/csv.zip)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-test_stress_B52_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/c64777e7-bc4f-477f-83cb-9ee5e2272127)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/2f6abd71-61e2-4f80-8311-5aa351b9064d)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/6a689794-5509-4d02-9965-56206a2cbe5f)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/f557eee4-eabc-4671-b21b-5fe7eff5445d)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/245e00f4-4fdc-4344-88a3-5bcf4e012e67)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/ab382ecd-69cd-4fad-a89e-024ae0141aad)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/2c4d19b0-7ae6-44be-bf88-1ee181b9f854)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/fa158c19-2a1d-4ad7-976a-bf9f56c59fb6)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/6e06cd2b-1dd1-40d2-ae26-7ca42cf094f7)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/b031cdfb-c1d7-4282-a380-12c16e963d1b)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/debfbfb5-0ca5-484f-8812-c179dda3211c)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/09f70e8a-d0dd-49a1-bba5-c627b01fe212)
    ![monitor-agent-test_stress_B52_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/cc1585d0-ab25-4956-ad96-795cdaedccdf)
    ![test_stress_B52_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/6dc2ebf1-1e8a-48fc-95bb-77e9213f75b0)
    ![test_stress_B52_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/429d4643-0891-45ac-8708-7ecf2cd061b3)
    ![test_stress_B52_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/9cf070ab-078b-4b90-80c4-aa22e8c58aad)
    ![test_stress_B52_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/d73fe657-38c7-4141-a1b3-85a5fdb7f668)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803506/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803507/csv.zip)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-winagent-test_stress_B52_windows-pre-release_CPU](https://github.com/user-attachments/assets/02efe811-f806-4fbb-bb89-ed787c5ce7b6)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Disk](https://github.com/user-attachments/assets/911372a7-5707-451b-a469-bfaf05fce00d)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/4e148304-821c-410b-bae2-cc733f526b28)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/9cdfc97d-2cb5-48e7-b891-937687e9282f)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Handles](https://github.com/user-attachments/assets/d7d74927-88b5-43da-85da-6280a1440960)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/a003b912-35d0-43ca-b49c-ef2fa5f88174)
    ![monitor-winagent-test_stress_B52_windows-pre-release_RSS](https://github.com/user-attachments/assets/2a3a3736-e99c-4b36-a3bc-4212949e46b1)
    ![monitor-winagent-test_stress_B52_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/922a08d3-ca58-4f1c-9ee1-073919e2fb4b)
    ![monitor-winagent-test_stress_B52_windows-pre-release_USS](https://github.com/user-attachments/assets/0b2d75e3-9724-426e-b830-a3651f223518)
    ![monitor-winagent-test_stress_B52_windows-pre-release_VMS](https://github.com/user-attachments/assets/1cf776ee-3e3d-4dc5-9eb3-ce8ea5fec4f0)
    ![monitor-winagent-test_stress_B52_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/e317f48f-be3f-4b7d-8cfc-d358080ebd08)
    ![test_stress_B52_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/81a96ef9-46d4-48eb-ae7b-ccef58d33b38)
    ![test_stress_B52_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/459f294b-e446-4aca-9477-93ae8109b98b)
    ![test_stress_B52_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/d0e5c57b-5788-4942-a8ee-389488b5192f)
    ![test_stress_B52_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/0d41bd10-61ad-4f0b-9965-d4e8eda7d8c2)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803512/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-test_stress_B52_windows-pre-release.csv](https://github.com/user-attachments/files/17803514/monitor-winagent-test_stress_B52_windows-pre-release.csv)
    [test_stress_B52_windows_agentd_state.csv](https://github.com/user-attachments/files/17803515/test_stress_B52_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle: 
- Known Issues:
  - https://github.com/wazuh/wazuh/issues/22565
  - https://github.com/wazuh/wazuh-jenkins/issues/4867
  - https://github.com/wazuh/wazuh-jenkins/issues/5287
  - https://github.com/wazuh/wazuh/issues/12074
  - https://github.com/wazuh/wazuh/issues/18179

**Comment by rafabailon** [comment]
### LGTM
