### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - ALL-EXCEPT-ROOTCHECK (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26892]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/57/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![monitor-manager-test_stress_B57_manager-pre-release_CPU](https://github.com/user-attachments/assets/4131c529-5a3e-4c9f-9689-a43112b57d8c)
    ![monitor-manager-test_stress_B57_manager-pre-release_Disk](https://github.com/user-attachments/assets/f94c9239-0cba-4c35-b370-51f9433965e1)
    ![monitor-manager-test_stress_B57_manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/d9e15243-1747-404f-919c-76d30c6d9b46)
    ![monitor-manager-test_stress_B57_manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/c827e76f-e9ac-4df4-8a7a-2d298a6725b9)
    ![monitor-manager-test_stress_B57_manager-pre-release_FD](https://github.com/user-attachments/assets/5492bbbe-3d6e-4436-a4b9-7a39fbb181ca)
    ![monitor-manager-test_stress_B57_manager-pre-release_PSS](https://github.com/user-attachments/assets/22c1c263-28e2-442f-9933-0b2c3ed54a76)
    ![monitor-manager-test_stress_B57_manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/df7909a6-ca8d-40a2-b2a6-237b18177f11)
    ![monitor-manager-test_stress_B57_manager-pre-release_RSS](https://github.com/user-attachments/assets/c8b8d1f6-b53d-4971-8c1e-2fb1e22b0390)
    ![monitor-manager-test_stress_B57_manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/826bbbf1-87f6-41ad-ac72-177c17ce5f6f)
    ![monitor-manager-test_stress_B57_manager-pre-release_SWAP](https://github.com/user-attachments/assets/4d438816-17b5-4ffe-b0b2-00f5c0a37ccb)
    ![monitor-manager-test_stress_B57_manager-pre-release_USS](https://github.com/user-attachments/assets/db3bf96e-eeac-4683-9612-36659c483dae)
    ![monitor-manager-test_stress_B57_manager-pre-release_VMS](https://github.com/user-attachments/assets/ff8cbb3a-5d53-497a-af80-e1e1a615f7f5)
    ![monitor-manager-test_stress_B57_manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/25b82ad1-42c7-4db7-b4ef-f520dab32d6a)
    
    - analysisd

    ![test_stress_B57_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/69c6d6ce-76af-491b-9bc3-2229ed96fac4)
    ![test_stress_B57_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/5d8efd56-846a-4350-8d6e-5f476063362a)
    ![test_stress_B57_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/e2a7e433-f099-4b25-a588-a99c0dcece77)
    ![test_stress_B57_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/f2c35855-4428-4b6d-9a95-87f3d64bdb62)
    ![test_stress_B57_manager_analysisd_state_Number_Events](https://github.com/user-attachments/assets/b2108231-37c3-42ab-bf2f-d245ec5baf61)
    ![test_stress_B57_manager_analysisd_state_Queues_state](https://github.com/user-attachments/assets/3bf1e96a-4908-4446-a1be-816d3063edf5)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803081/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803084/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-test_stress_B57_centos-pre-release_CPU](https://github.com/user-attachments/assets/c85a22d4-ed7c-42f1-8ac7-c76ba6af3864)
    ![monitor-agent-test_stress_B57_centos-pre-release_Disk](https://github.com/user-attachments/assets/740c305e-f82b-4ca9-aa0d-e83f6f886445)
    ![monitor-agent-test_stress_B57_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/62d346db-e06f-4784-8221-a3d4ec130ec6)
    ![monitor-agent-test_stress_B57_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/5e931d89-2a63-4b59-bb7b-aace4a3c58b5)
    ![monitor-agent-test_stress_B57_centos-pre-release_FD](https://github.com/user-attachments/assets/c0dae8a3-fc16-4613-a685-8ba9c614516a)
    ![monitor-agent-test_stress_B57_centos-pre-release_PSS](https://github.com/user-attachments/assets/f3058ac2-6847-4229-9269-84de4c7ec3c2)
    ![monitor-agent-test_stress_B57_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/b976aa32-d58a-4721-8d73-fea2797076fc)
    ![monitor-agent-test_stress_B57_centos-pre-release_RSS](https://github.com/user-attachments/assets/6b8bc1d7-cab8-4a5a-bf18-bd8d050edf09)
    ![monitor-agent-test_stress_B57_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/5a325bb4-f109-401f-ab95-77b15dfab559)
    ![monitor-agent-test_stress_B57_centos-pre-release_SWAP](https://github.com/user-attachments/assets/7bb84ab3-d48e-4cff-a4b7-4a2db4f2ef67)
    ![monitor-agent-test_stress_B57_centos-pre-release_USS](https://github.com/user-attachments/assets/9e7e41c6-551d-429b-b3f3-5b057216f0eb)
    ![monitor-agent-test_stress_B57_centos-pre-release_VMS](https://github.com/user-attachments/assets/ac961ed6-092c-42f3-9f30-3ec06a570423)
    ![monitor-agent-test_stress_B57_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/b001fea6-fae6-48d8-a420-e9cbde55535a)
    
    - agentd

    ![test_stress_B57_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/7a2cfa84-18da-4c1f-8069-2627e9df44b0)
    ![test_stress_B57_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/97cb5862-78c9-4450-8c64-bc263563ac39)
    ![test_stress_B57_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/9cbeb5f5-0d15-4f85-9118-0c6a775b2801)
    ![test_stress_B57_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/05be412c-319e-45e0-9254-478c98a303cd)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803088/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803090/csv.zip)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-test_stress_B57_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/e0df6595-4b2c-413c-a9d8-04822693d6b7)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/03ec5999-4355-4c51-b2f3-75d84520fbd5)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/34266027-bb70-429c-b62c-cc1c32094f10)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/b8fc210f-06fb-49ff-980d-06a00d1f3523)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/3ee0a077-3065-4d5b-b567-08251f9b2eca)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/bd509f24-dc2c-415c-b89f-88c7df2ad902)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/4981584d-b44f-4bf8-856c-d38c11a042d8)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/883bb6fd-fd51-4691-a099-89d85451b2e8)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/49834011-1e1d-4f2e-8a2a-e44c93a8db85)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/4b8fc0c0-1aa7-4748-ab48-a0adcaaabd20)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/136450ff-9a9a-4eb8-b5ed-ea8da3680b83)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/df6486cd-a648-42ff-a9e8-c54f590f995c)
    ![monitor-agent-test_stress_B57_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/2e0c0643-b88a-4812-a7ee-06eac1460dc8)
    
    - agentd

    ![test_stress_B57_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/d28cec1e-3972-4a8c-9808-50dd59a45a8c)
    ![test_stress_B57_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/a4ed1a1b-040b-4bd6-ba3b-5b5ac1b09d92)
    ![test_stress_B57_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/de231bea-16b4-4ef1-8259-93340f974ca2)
    ![test_stress_B57_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/5d87a60e-5b03-456f-bea2-68202e1d5e5d)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803095/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803099/csv.zip)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-test_stress_B57_windows-pre-release_CPU](https://github.com/user-attachments/assets/43005da6-9e0c-4cc2-877b-da9aac7fa762)
    ![monitor-agent-test_stress_B57_windows-pre-release_Disk](https://github.com/user-attachments/assets/27224c15-c26b-4e35-b3a2-58caabbd03e5)
    ![monitor-agent-test_stress_B57_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/ee60b1fa-7ff6-4d0f-9789-e2bb5dad75e0)
    ![monitor-agent-test_stress_B57_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/174eabbc-8ac3-4cd9-8e12-04b53194cb47)
    ![monitor-agent-test_stress_B57_windows-pre-release_FD](https://github.com/user-attachments/assets/e1ed3253-1aa5-4ea1-888f-2b145ee0e898)
    ![monitor-agent-test_stress_B57_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/9db5fa49-04fc-4e0e-bdab-83afce381d8d)
    ![monitor-agent-test_stress_B57_windows-pre-release_RSS](https://github.com/user-attachments/assets/718913dd-8dfd-4253-8832-11dcbac55508)
    ![monitor-agent-test_stress_B57_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/6db6afb5-f61e-4b2c-a33b-a4c6c39bbee8)
    ![monitor-agent-test_stress_B57_windows-pre-release_USS](https://github.com/user-attachments/assets/b1b3f833-c08e-439a-9eab-8e736306a43a)
    ![monitor-agent-test_stress_B57_windows-pre-release_VMS](https://github.com/user-attachments/assets/6ecf4649-4162-42e6-8740-0f33237066f5)
    ![monitor-agent-test_stress_B57_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/3d12fe84-58d6-4090-92d0-aaea3e3c6010)
    
    - agentd
    
    ![test_stress_B57_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/1acb9ba7-aa0a-492d-b75e-74a7c202a792)
    ![test_stress_B57_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/5dbceb76-2774-4aaa-9379-a3b8306e37a8)
    ![test_stress_B57_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/ca202f20-a394-45b3-9ca9-618f310d0d7d)
    ![test_stress_B57_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/ebadf1e5-6953-4fca-baf1-e168571fe3bc)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803119/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-test_stress_B57_windows-pre-release.csv](https://github.com/user-attachments/files/17803122/monitor-winagent-test_stress_B57_windows-pre-release.csv)
    [test_stress_B57_windows_agentd_state.csv](https://github.com/user-attachments/files/17803123/test_stress_B57_windows_agentd_state.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### Logs :yellow_circle: 

- Known issues
   - QA Known
       - https://github.com/wazuh/wazuh-jenkins/issues/4656
       - https://github.com/wazuh/wazuh-jenkins/issues/5287
       - https://github.com/wazuh/wazuh/issues/22565
       - https://github.com/wazuh/wazuh-jenkins/issues/3293
       - https://github.com/wazuh/wazuh-jenkins/issues/5588
       - https://github.com/wazuh/wazuh-jenkins/issues/4469
       - https://github.com/wazuh/wazuh-jenkins/issues/4867
       - https://github.com/wazuh/wazuh/issues/18995
       - https://github.com/wazuh/wazuh/issues/21942
       - https://github.com/wazuh/wazuh/issues/12074

**Comment by rafabailon** [comment]
### LGTM

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message
