### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - LOGCOLLECTOR,SCA (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26897]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/51/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    [plots.zip](https://github.com/user-attachments/files/17803529/plots.zip)

    </details>
+ <details><summary>Logs and configuration</summary>

  
    [ossec.zip](https://github.com/user-attachments/files/17803530/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803531/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

  ![logcollector_sca_centos-pre-release_CPU](https://github.com/user-attachments/assets/04e93d39-a795-46ca-9e98-4c9c603268ac)
  ![logcollector_sca_centos-pre-release_Disk](https://github.com/user-attachments/assets/7c31f9da-5901-447b-af71-c4db54d5b2e0)
  ![logcollector_sca_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/3e3a2355-d3c4-447f-b781-84e807678686)
  ![logcollector_sca_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/d675b539-d193-44de-949a-bd55382a0984)
  ![logcollector_sca_centos-pre-release_FD](https://github.com/user-attachments/assets/67c24ef4-26cf-451c-a070-c003248c2bde)
  ![logcollector_sca_centos-pre-release_PSS](https://github.com/user-attachments/assets/56b6ba36-0040-400b-9f8c-0e8749502d77)
  ![logcollector_sca_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/4c7da70f-f0ba-424f-a2c1-7c49b0fd4dba)
  ![logcollector_sca_centos-pre-release_RSS](https://github.com/user-attachments/assets/8ed6532c-0377-4544-bd9d-311b41c737c2)
  ![logcollector_sca_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/09096e1f-6692-46d6-8683-f391c998ad45)
  ![logcollector_sca_centos-pre-release_SWAP](https://github.com/user-attachments/assets/a032c190-55a4-46d7-bccf-d2e61f44a8f7)
  ![logcollector_sca_centos-pre-release_USS](https://github.com/user-attachments/assets/c0325b3f-dfdf-4fd0-840f-80c6071218ca)
  ![logcollector_sca_centos-pre-release_VMS](https://github.com/user-attachments/assets/cc705ed4-c98b-432e-8ca7-f7faf508b1af)
  ![logcollector_sca_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/5a90638f-542f-4041-a1fa-a03845359348)
  ![test_stress_B51_centos_agent_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/d0fbba41-7b99-4faf-bd2c-0ec8e97273aa)
  ![test_stress_B51_centos_agent_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/4b90851c-7a6b-4a26-972f-24dd3dafffe8)
  ![test_stress_B51_centos_agent_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/399dc14c-7c83-4cd1-ae56-b335fac8a888)
  ![test_stress_B51_centos_agent_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/95a9bb3a-94af-4249-810a-c6f8e98485a6)

    </details>
+ <details><summary>Logs and configuration</summary>

  
    [ossec.zip](https://github.com/user-attachments/files/17803536/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803537/csv.zip)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

  ![logcollector_sca_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/d10438f2-ef0f-43f7-bb49-5e7cc25616df)
  ![logcollector_sca_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/f5fd4bc4-c287-4122-8083-0aac6431b763)
  ![logcollector_sca_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/eb8caf9b-f1e8-47ff-93b8-c671d5292f2d)
  ![logcollector_sca_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/1b4ec20e-8bdb-40e8-83b0-29589e45c724)
  ![logcollector_sca_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/52d917c1-5a04-4ef8-ae35-ce81cd95df1c)
  ![logcollector_sca_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/f9607583-ac7d-46de-b3e5-73877777a687)
  ![logcollector_sca_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/d8d32d17-414b-49f6-9704-4106f796a850)
  ![logcollector_sca_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/0ebd36e1-9c2f-42c7-981c-cae37b33df9f)
  ![logcollector_sca_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/5e3cb6d9-f163-412e-833c-f2010f47cf7d)
  ![logcollector_sca_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/a7fbeec6-7422-41ce-9014-72b32c15ed8e)
  ![logcollector_sca_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/d90a94bb-2a4d-4f6b-8ff2-000ff90647d0)
  ![logcollector_sca_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/3c351a1c-5f89-41d3-b7fc-42df5996e75d)
  ![logcollector_sca_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/4ac9c0f3-4c41-4a7b-8484-5f18cb90254c)
  ![test_stress_B51_ubuntu_agent_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/7ca20168-b6ca-408e-b613-e49a97cb4128)
  ![test_stress_B51_ubuntu_agent_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/bd4b324b-27ca-40ec-9588-773611287a3f)
  ![test_stress_B51_ubuntu_agent_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/d0941da0-4a67-48f1-befb-eae722ab5d76)
  ![test_stress_B51_ubuntu_agent_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/86d4b065-34b6-40f2-8aa8-647229322e60)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803540/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803541/csv.zip)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

  ![logcollector_sca_windows-pre-release_CPU](https://github.com/user-attachments/assets/b7f39315-347b-409b-b029-04eb6cb2da46)
  ![logcollector_sca_windows-pre-release_Disk](https://github.com/user-attachments/assets/0dce4eb0-5f96-40ce-992a-42f48a673170)
  ![logcollector_sca_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/833a0295-c57d-4dbf-b223-59381af218d2)
  ![logcollector_sca_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/445d869a-966e-4ca2-9526-85ee08d51207)
  ![logcollector_sca_windows-pre-release_Handles](https://github.com/user-attachments/assets/0456bb89-0648-4449-a7fc-6d021e7345fe)
  ![logcollector_sca_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/965bfab4-f327-4be8-ae97-77e7b5a04837)
  ![logcollector_sca_windows-pre-release_RSS](https://github.com/user-attachments/assets/e977fbd5-c459-48df-b5ac-754274f1b50e)
  ![logcollector_sca_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/10f49259-334f-4c01-b461-83609b175736)
  ![logcollector_sca_windows-pre-release_USS](https://github.com/user-attachments/assets/15e222a5-85ce-4030-9773-8aadd40de847)
  ![logcollector_sca_windows-pre-release_VMS](https://github.com/user-attachments/assets/44f03ab2-4145-4f0b-9563-04945941741f)
  ![logcollector_sca_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/2ad00d46-7bff-4cf6-a59a-a6324b71fa0d)
  ![test_stress_B51_windows_agent_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/5b26803c-74a5-45d5-9212-99b242b86ac3)
  ![test_stress_B51_windows_agent_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/3131ccb3-6504-4bab-83ef-5a04374a45f3)
  ![test_stress_B51_windows_agent_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/04e622b8-7b2f-490a-a00d-6ec22bbf9393)
  ![test_stress_B51_windows_agent_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/c2fc3542-3929-4f5a-86f7-6c038bcb3a09)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803544/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

  
    [test_stress_B51_windows_agentd_state.csv](https://github.com/user-attachments/files/17801884/test_stress_B51_windows_agentd_state.csv)
    [monitor-winagent-test_stress_B51_windows-pre-release.csv](https://github.com/user-attachments/files/17801885/monitor-winagent-test_stress_B51_windows-pre-release.csv)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :red_circle: 

Plots comapred to https://github.com/wazuh/wazuh/issues/26658

### Graphs :red_circle: 

New issue:

- https://github.com/wazuh/wazuh/issues/26906

### Logs :yellow_circle: 

Known issues:

- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh/issues/24509
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/18179

**Comment by MARCOSD4** [comment]
# Analysis Report :red_circle:  


## Graphs :red_circle:  

<details>
   <summary>Manager  </summary>
   <br/>

Disk_Read: small increase in wazuh-monitord
Disk_written, Write_ops: small increase in modulesd.

</details>

<details>
   <summary>CentOS </summary>
   <br/>
   
Disk_Read, Disk_written: decrease in wazuh-modulesd

</details>

<details>
   <summary>Ubuntu Agent  </summary>
   <br/>
   
- Disk_read: increase in modulesd: New issue: https://github.com/wazuh/wazuh/issues/26906

VMS: small decrease in modulesd.

</details>

<details>
   <summary>Windows Agent  </summary>
   <br/>

- No abnormalities found.

</details>


## Logs :yellow_circle: 

<details>
   <summary>Manager  </summary>
   <br/>
   
   - Expected in stress test: 
   
   ```
2024/11/17 00:00:13 sca WARNING: Interval overtaken.
2024/11/15 00:31:30 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files".
2024/11/15 00:31:35 wazuh-analysisd WARNING: Input queue is full.
2024/11/15 00:31:35 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2024/11/15 00:34:36 wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
   ```
   
   - Known Issue: https://github.com/wazuh/wazuh/issues/22565

```
2024/11/14 18:28:43 indexer-connector WARNING: No username and password found in the keystore, using default values.
2024/11/14 18:28:43 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-x-x-x-x.ec2.internal', retrying until the connection is successful.
```   

- Known issue: https://github.com/wazuh/wazuh/issues/24509
```2024/11/14 18:30:42 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted.

```
    
</details>

<details>
   <summary>CentOS  </summary>
   <br/>
   
   - Expected in stress test: 
   
   ```
2024/11/17 00:00:14 sca WARNING: Interval overtaken.
2024/11/15 00:31:37 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files".
2024/11/15 00:31:46 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2024/11/15 00:31:46 wazuh-agentd WARNING: Agent buffer is full: Events may be lost.
   ```
   
- Known Issue: https://github.com/wazuh/wazuh-jenkins/issues/4867

```
2024/11/14 18:30:42 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/14 18:30:42 wazuh-agentd ERROR: (1216): Unable to connect to '[x.x.x.x]:1514/tcp': 'Connection refused'.
2024/11/14 18:30:42 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection...
```


    

</details>

<details>
   <summary>Ubuntu  </summary>
   <br/>
   
   - Expected in stress Test

```
2024/11/17 00:00:10 wazuh-agentd WARNING: Agent buffer is full: Events may be lost.
2024/11/17 00:01:51 sca WARNING: Interval overtaken.
2024/11/15 00:31:31 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files".
2024/11/15 00:31:36 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2024/11/15 06:45:43 wazuh-agentd WARNING: Agent buffer is flooded: Producing too many events.
```    

- Known Issue: https://github.com/wazuh/wazuh-jenkins/issues/4867

```
2024/11/14 18:30:42 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/14 18:30:42 wazuh-agentd ERROR: (1216): Unable to connect to '[x.x.x.x]:1514/tcp': 'Connection refused'.
2024/11/14 18:30:42 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection...
```



</details>

<details>
   <summary>Windows  </summary>
   <br/>
   
   - Expected in stress Test:
   
   ```
2024/11/15 00:31:51 wazuh-agent WARNING: (1960): File limit has been reached (200).
2024/11/15 00:31:51 wazuh-agent WARNING: Agent buffer at 90 %.
2024/11/15 00:31:51 wazuh-agent WARNING: Target 'agent' message queue is full (1024). Log lines may be lost.
2024/11/15 00:31:54 wazuh-agent WARNING: Agent buffer is full: Events may be lost.
2024/11/15 00:35:28 sca WARNING: Interval overtaken.
   ```
   - Known Issue: https://github.com/wazuh/wazuh-jenkins/issues/4867

```
2024/11/14 18:30:48 wazuh-agent ERROR: (1208): Unable to connect to enrollment service at '[x.x.x.x]:1515'
```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/5287
```
2024/11/15 13:57:50 wazuh-agent ERROR: (1103): Could not open file 'C:\tmp\logcollector_test\date-2024-11-15-53-702.log' due to [(2)-(No such file or directory)].
```

- Known issue: https://github.com/wazuh/wazuh/issues/18179
```
2024/11/14 18:30:42 wazuh-agent ERROR: SSL read (unable to receive message)
2024/11/14 18:30:42 wazuh-agent ERROR: If Agent verification is enabled, agent key and certificates may be incorrect!
```


</details>

**Comment by rafabailon** [comment]
### LGTM

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message 

```
2024/11/14 18:30:42 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/11/14 18:30:42 wazuh-modulesd:syscollector: INFO: Module finished.
2024/11/14 18:30:42 wazuh-modulesd:vulnerability-scanner: INFO: Stopping vulnerability_scanner module.
2024/11/14 18:30:42 wazuh-modulesd:content-updater: WARNING: The offsets download has been interrupted.
2024/11/14 18:30:42 wazuh-modulesd:router: INFO: Stopping router module.
2024/11/14 18:30:42 wazuh-modulesd:content_manager: INFO: Stopping content_manager module.
2024/11/14 18:30:42 wazuh-monitord: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:42 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:42 wazuh-remoted: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:42 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/11/14 18:30:43 wazuh-authd: INFO: Client timeout from 172.31.2.21
2024/11/14 18:30:43 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:43 wazuh-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:43 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/11/14 18:30:43 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:43 wazuh-db: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/11/14 18:30:44 wazuh-db: INFO: Graceful process shutdown.
2024/11/14 18:30:44 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```
