### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - ALL-EXCEPT-SYSCHECK (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26891]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/56/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

 
    ![monitor-manager-Test_stress_B56-manager-pre-release_CPU](https://github.com/user-attachments/assets/c610899a-1e7e-4a08-9425-bf0912d8262c)
![monitor-manager-Test_stress_B56-manager-pre-release_Disk](https://github.com/user-attachments/assets/97278fc4-3985-4ff3-8f40-a7d0087460d9)
![monitor-manager-Test_stress_B56-manager-pre-release_Disk_Read](https://github.com/user-attachments/assets/1355b4a8-dfda-4ec1-904b-e5a9a95610a9)
![monitor-manager-Test_stress_B56-manager-pre-release_Disk_Written](https://github.com/user-attachments/assets/deca4325-8a31-4a99-9a12-ed7fb8a3d37c)
![monitor-manager-Test_stress_B56-manager-pre-release_FD](https://github.com/user-attachments/assets/8380a947-f2ee-40c5-8b27-03c139fd9f0a)
![monitor-manager-Test_stress_B56-manager-pre-release_PSS](https://github.com/user-attachments/assets/d350081f-9a81-4894-967e-0121ccae2a49)
![monitor-manager-Test_stress_B56-manager-pre-release_Read_Ops](https://github.com/user-attachments/assets/9470d4c8-1864-41f6-82fb-d882d311b9c3)
![monitor-manager-Test_stress_B56-manager-pre-release_RSS](https://github.com/user-attachments/assets/592046f2-2aec-41c5-857c-3957a99ee9cf)
![monitor-manager-Test_stress_B56-manager-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/1671ff91-4f3a-4eae-adfb-afefade4efb0)
![monitor-manager-Test_stress_B56-manager-pre-release_SWAP](https://github.com/user-attachments/assets/d1a2870c-7d6e-4b29-9002-52d31f0cbfbb)
![monitor-manager-Test_stress_B56-manager-pre-release_USS](https://github.com/user-attachments/assets/b190e397-6e52-4de5-b3d6-3dffe1ded08e)
![monitor-manager-Test_stress_B56-manager-pre-release_VMS](https://github.com/user-attachments/assets/3d380372-9d2c-481f-b713-9c6ab58e46d7)
![monitor-manager-Test_stress_B56-manager-pre-release_Write_Ops](https://github.com/user-attachments/assets/e08ef56e-b226-4597-8650-67f1fbd1dc45)
![test_stress_B56_manager_analysisd_events_Decoded_events](https://github.com/user-attachments/assets/15a8e1b5-ef63-4505-a6d2-f637cefe78d1)
![test_stress_B56_manager_analysisd_events_Dropped_events](https://github.com/user-attachments/assets/d1e96818-c3c7-4d78-a6ad-9dee1cd5b02e)
![test_stress_B56_manager_analysisd_events_EDPS](https://github.com/user-attachments/assets/dde84ebd-e83e-4097-a2dc-1c5c1608edd0)
![test_stress_B56_manager_analysisd_events_Written_stats](https://github.com/user-attachments/assets/8f215b98-2b56-4c12-a7a3-9f70f1184512)
![test_stress_B56_manager_analysisd_state csv_Number_Events](https://github.com/user-attachments/assets/b8e8a7ab-8845-4ed1-ab99-555c683cc09d)
![test_stress_B56_manager_analysisd_state csv_Queues_state](https://github.com/user-attachments/assets/3fb50d6f-ed7d-4f14-ae87-e49e5603d0f3)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B56_manager_2024-11-14.zip](https://github.com/user-attachments/files/17802843/ossec_Test_stress_B56_manager_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17802847/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-centos-Test_stress_B56_centos-pre-release_CPU](https://github.com/user-attachments/assets/4279df7f-70ad-4a6b-8c3a-307e9800bc68)
![monitor-centos-Test_stress_B56_centos-pre-release_Disk](https://github.com/user-attachments/assets/8dae828f-726f-4977-b2b3-3a51b0aa2bf9)
![monitor-centos-Test_stress_B56_centos-pre-release_Disk_Read](https://github.com/user-attachments/assets/88495cde-2395-4934-a161-4d757138b1ba)
![monitor-centos-Test_stress_B56_centos-pre-release_Disk_Written](https://github.com/user-attachments/assets/5369ace8-036c-4116-8146-80bd8d94f152)
![monitor-centos-Test_stress_B56_centos-pre-release_FD](https://github.com/user-attachments/assets/f379cf1d-0453-4d31-8b9e-7f0377126467)
![monitor-centos-Test_stress_B56_centos-pre-release_PSS](https://github.com/user-attachments/assets/92560570-77bc-4209-85e3-a13dbde34cab)
![monitor-centos-Test_stress_B56_centos-pre-release_Read_Ops](https://github.com/user-attachments/assets/8a95d4e3-d262-4a66-bae3-13048a6fde3d)
![monitor-centos-Test_stress_B56_centos-pre-release_RSS](https://github.com/user-attachments/assets/dc0af18d-ca2c-480d-8f7c-8809c8e7640a)
![monitor-centos-Test_stress_B56_centos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/520994aa-b116-4dcb-b020-342969abfb89)
![monitor-centos-Test_stress_B56_centos-pre-release_SWAP](https://github.com/user-attachments/assets/a6229f3c-40d6-4aff-88e6-826e845a2f5b)
![monitor-centos-Test_stress_B56_centos-pre-release_USS](https://github.com/user-attachments/assets/8be8148e-fff9-42df-833b-8076cff3f4ae)
![monitor-centos-Test_stress_B56_centos-pre-release_VMS](https://github.com/user-attachments/assets/e5f934ac-e006-4e60-99b1-7be03ab2d13a)
![monitor-centos-Test_stress_B56_centos-pre-release_Write_Ops](https://github.com/user-attachments/assets/45240668-8362-4ebf-9af2-b7b1f2216f70)
![test_stress_B56_centos_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/4069697c-59c3-4f15-a0a5-a4a7a904fdfd)
![test_stress_B56_centos_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/cb32ee25-759a-47ef-8680-7e6db662c793)
![test_stress_B56_centos_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/23f5cad9-f0b6-45d0-9f6e-123c7650e1da)
![test_stress_B56_centos_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/fcafd3b1-d4f9-4cbf-be07-303c82e22ea4)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B56_centos_2024-11-14.zip](https://github.com/user-attachments/files/17802856/ossec_Test_stress_B56_centos_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17802855/csv.zip)

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_CPU](https://github.com/user-attachments/assets/91199d6c-5378-4c1d-9fb5-29b5180de7a7)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_Disk](https://github.com/user-attachments/assets/50882365-dc03-4b3f-963b-3e188a60f062)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_Disk_Read](https://github.com/user-attachments/assets/fbb31768-5fe4-41bc-a735-af736f0e2b05)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_Disk_Written](https://github.com/user-attachments/assets/3ed63168-a0ce-410b-adcf-cdfd5cc8c515)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_FD](https://github.com/user-attachments/assets/15d3ec6c-0b0e-4003-883e-f566a57e0b24)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_PSS](https://github.com/user-attachments/assets/3b49c4ea-90cc-46a0-a77f-531d0b0f456f)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_Read_Ops](https://github.com/user-attachments/assets/f6f76f70-7007-413a-83c2-e69b23a5eade)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_RSS](https://github.com/user-attachments/assets/c3669b4b-4eb1-421b-ab18-087030c18eb2)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/91313683-9e18-45ec-a5b5-3aad3df9d419)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_SWAP](https://github.com/user-attachments/assets/b22d8236-f33a-486a-a18e-8384d2c0b6f9)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_USS](https://github.com/user-attachments/assets/7d3f5986-d19c-4683-bad6-21b62b48c608)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_VMS](https://github.com/user-attachments/assets/4f23c010-9adc-4b62-b877-0e270b27727e)
![monitor-ubuntu-Test_stress_B56_ubuntu-pre-release_Write_Ops](https://github.com/user-attachments/assets/f48fca7f-c6bb-4e53-a574-03bf34bbd28d)
![test_stress_B56_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/73b295f3-422a-4c64-aa00-81c7b66226f3)
![test_stress_B56_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/3b3e672a-4677-49a4-a6c8-fb750f1e1819)
![test_stress_B56_ubuntu_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/6e5909a4-cda4-478f-aedb-945b01ab452e)
![test_stress_B56_ubuntu_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/99d23f42-ed16-4f73-a49f-4d8e97c201ab)

    </details>
+ <details><summary>Logs and configuration</summary>

   [ossec_Test_stress_B56_ubuntu_2024-11-14.zip](https://github.com/user-attachments/files/17802871/ossec_Test_stress_B56_ubuntu_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17802872/csv.zip)

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-windows-Test_stress_B56_windows-pre-release_CPU](https://github.com/user-attachments/assets/405d6ac6-b2fc-42ac-8d64-341b8be4941e)
![monitor-windows-Test_stress_B56_windows-pre-release_Disk](https://github.com/user-attachments/assets/a1006f74-5e8d-4095-a610-8848455266e9)
![monitor-windows-Test_stress_B56_windows-pre-release_Disk_Read](https://github.com/user-attachments/assets/182dd00b-6d43-4351-8bea-b06a922b48dd)
![monitor-windows-Test_stress_B56_windows-pre-release_Disk_Written](https://github.com/user-attachments/assets/98c2c068-a1c7-4d6a-becb-ead1123d2ccc)
![monitor-windows-Test_stress_B56_windows-pre-release_Handles](https://github.com/user-attachments/assets/9c0ca803-b814-492c-a458-487fc8564722)
![monitor-windows-Test_stress_B56_windows-pre-release_Read_Ops](https://github.com/user-attachments/assets/46323e35-2342-463e-89aa-2c9a5388fc7e)
![monitor-windows-Test_stress_B56_windows-pre-release_RSS](https://github.com/user-attachments/assets/1390c706-5194-4fb4-9431-f2478c98efe3)
![monitor-windows-Test_stress_B56_windows-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/47d0f5ce-9be7-4379-9853-87893244670b)
![monitor-windows-Test_stress_B56_windows-pre-release_USS](https://github.com/user-attachments/assets/f7704760-333f-4b98-bb88-7ebb66305e2d)
![monitor-windows-Test_stress_B56_windows-pre-release_VMS](https://github.com/user-attachments/assets/da631e5e-a88a-4d35-a4db-a588dc1ecbdd)
![monitor-windows-Test_stress_B56_windows-pre-release_Write_Ops](https://github.com/user-attachments/assets/008d9c31-212d-4326-86d7-3183054229a8)
![test_stress_B56_windows_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/2a38bd60-d81a-474c-beca-8d3a7eaac047)
![test_stress_B56_windows_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/14abd2f5-e7d1-4749-a613-cb2a24a749f5)
![test_stress_B56_windows_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/1f321283-83a0-41a8-9245-4bd59e3cb38c)
![test_stress_B56_windows_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/dbe8674d-b83f-481a-a34e-131ead014d6b)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B56_windows_2024-11-14.zip](https://github.com/user-attachments/files/17802901/ossec_Test_stress_B56_windows_2024-11-14.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17802904/csv.zip)

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle: 
Known issue
- https://github.com/wazuh/wazuh-jenkins/issues/5588
- https://github.com/wazuh/wazuh-jenkins/issues/4656
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/3293
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh/issues/18179

Not Known issue
- https://github.com/wazuh/wazuh/issues/24509

**Comment by pro-akim** [comment]
# Analysis report

## Graphs

### Manager

### Centos

### Ubuntu

### Windows

## Logs :yellow_circle:


<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-14 18:31:24,067 Writing binary info to monitor-manager-test_stress_B56_manager-pre-release.csv.
2024-11-14 18:31:29,090 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/29172/stat'

2024-11-15 00:48:09,836 Error getting something from a dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 615, in check_wazuh_processes
    dead_processes.remove(process.name())
KeyError: 'systemctl'
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
ProcessLookupError: [Errno 3] No such process
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4656 - Known issue
```
2024/11/17 00:14:53 wazuh-modulesd:azure-logs ERROR: azure-activity: Returned error code: '1'. 
```

- Expected in stress test
```
2024/11/17 00:00:17 sca WARNING: Interval overtaken. 
2024/11/14 18:28:59 wazuh-remoted WARNING: Message queue is full (10). Events may be lost. 
2024/11/14 18:29:00 wazuh-remoted WARNING: Agent key already in use: agent ID '003' 
2024/11/16 00:00:11 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files". 
2024/11/15 00:29:32 wazuh-analysisd WARNING: Input queue is full. 
2024/11/15 00:29:32 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost. 
2024/11/15 00:45:59 wazuh-analysisd WARNING: Security Configuration Assessment decoder queue is full. 
```

- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/14 18:26:20 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/14 18:26:20 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-5-234.ec2.internal', retrying until the connection is successful. 
2024/11/14 18:27:40 indexer-connector WARNING: Failed to sync agent '001' with the indexer. 
```


- Reported: https://github.com/wazuh/wazuh/issues/24509 - Not Known issue
```
2024/11/14 18:28:27 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/14 18:28:42 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting... 
```





</details>



<details><summary>Centos</summary>


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-14 18:30:05,888 Error getting something from a dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 615, in check_wazuh_processes
    dead_processes.remove(process.name())
KeyError: 'wazuh-modulesd'
 
2024-11-15 03:02:54,758 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1697, in cmdline
    data = f.read()
ProcessLookupError: [Errno 3] No such process
 
2024-11-15 07:51:10,792 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/3240481/stat'
```

- Report: https://github.com/wazuh/wazuh-jenkins/issues/3293 - Known issue
```
2024/11/17 00:00:14 wazuh-modulesd:ciscat ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory 
2024/11/17 00:00:14 wazuh-modulesd:ciscat ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml' 
```

- Report: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:28:27 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:28:27 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.5.234]:1514/tcp': 'Connection refused'. 
```


- Expected in stress test
```
2024/11/17 00:00:30 sca WARNING: Interval overtaken. 
2024/11/14 18:28:28 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
2024/11/16 00:00:31 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files". 
2024/11/16 00:04:03 wazuh-agentd WARNING: Agent buffer at 90 %. 
2024/11/16 00:04:43 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
2024/11/15 00:30:04 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost. 
```
</details>



<details><summary>Ubuntu</summary>


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-14 20:05:17,905 Error getting something from a dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 615, in check_wazuh_processes
    dead_processes.remove(process.name())
KeyError: 'sudo'

2024-11-14 21:59:43,246 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
ProcessLookupError: [Errno 3] No such process
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2464499/stat'
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known isuee
```
2024/11/14 18:27:14 wazuh-modulesd:ciscat ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'. 
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:28:27 wazuh-agentd ERROR: Connection socket: Connection reset by peer (104) 
2024/11/14 18:28:27 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:28:27 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.5.234]:1514/tcp': 'Connection refused'. 
2024/11/14 18:28:27 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
```


- Expected in stress test
```
2024/11/17 00:00:41 sca WARNING: Interval overtaken. 
2024/11/16 00:00:13 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
2024/11/16 00:00:33 wazuh-agentd WARNING: Agent buffer at 90 %. 
2024/11/16 00:01:34 wazuh-logcollector WARNING: (1960): File limit has been reached (1000). Please reduce the number of files or increase "logcollector.max_files". 
2024/11/16 00:44:41 wazuh-agentd WARNING: Agent buffer is flooded: Producing too many events. 
2024/11/15 00:29:32 wazuh-logcollector WARNING: Target 'agent' message queue is full (1024). Log lines may be lost. 
```
</details>



<details><summary>Windows</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/15 00:04:59 wazuh-modulesd:ciscat ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'. 
```


- Reported: https://github.com/wazuh/wazuh/issues/18179 - Known issue
```
2024/11/14 18:28:29 wazuh-agent ERROR: SSL read (unable to receive message) 
2024/11/14 18:28:29 wazuh-agent ERROR: If Agent verification is enabled, agent key and certificates may be incorrect! 
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/14 18:29:31 wazuh-modulesd:ciscat ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory 
```

- Expected in stress test
```
2024/11/15 00:04:59 wazuh-modulesd:ciscat WARNING: Interval overtaken. 
2024/11/15 00:29:32 wazuh-agent WARNING: (1960): File limit has been reached (200). 
2024/11/15 00:29:32 wazuh-agent WARNING: Target 'agent' message queue is full (1024). Log lines may be lost. 
2024/11/15 00:29:32 wazuh-agent WARNING: Agent buffer at 90 %. 
2024/11/15 00:29:47 wazuh-agent WARNING: Agent buffer is flooded: Producing too many events. 
2024/11/15 00:33:18 sca WARNING: Interval overtaken. 
2024/11/15 00:40:48 wazuh-agent WARNING: Agent buffer is full: Events may be lost. 
```
</details>

**Comment by pro-akim** [comment]
Fixes done!

**Comment by MARCOSD4** [comment]
LGTM

**Comment by rauldpm** [comment]
The warning `WARNING: The offsets download has been interrupted.` is related to a graceful shutdown, it is an expected message
