### ISSUE TITLE
Release 4.10.0 - Alpha 3 - Footprint Metrics - MACOS-SOLARIS (2.5d)

### ISSUE THREAD

**Issue by jseg380** [wazuh/wazuh#26899]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26761                                       |
| **Main footprint metrics issue #** | #26795                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Alpha 3                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-alpha3 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress_vagrant/4/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    [plots.zip](https://github.com/user-attachments/files/17803590/plots.zip)

    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec.zip](https://github.com/user-attachments/files/17803591/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803594/csv.zip)

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    
  ![macos-solaris_macos-pre-release_CPU](https://github.com/user-attachments/assets/b6802d1d-94ee-4157-990f-985687c5342e)
  ![macos-solaris_macos-pre-release_FD](https://github.com/user-attachments/assets/3b91afea-b56c-433f-a205-4dab3e362ed9)
  ![macos-solaris_macos-pre-release_RSS](https://github.com/user-attachments/assets/c90f4d5d-7bb7-4c02-807f-19c611a5a568)
  ![macos-solaris_macos-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/758e4473-d29a-4fd5-a3d4-c45506c186fc)
  ![macos-solaris_macos-pre-release_VMS](https://github.com/user-attachments/assets/6bd82ffc-2d13-4ee3-8dcd-eaf09de83e2e)
  ![test_stress_vagrant_B4_macos_agent_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/37cf56aa-f8b9-4dc0-9770-e76d90d6e7fe)
  ![test_stress_vagrant_B4_macos_agent_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/b34eef36-323e-41be-aec2-d7a552355900)
  ![test_stress_vagrant_B4_macos_agent_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/329af279-00e6-411d-97fb-460a97209525)
  ![test_stress_vagrant_B4_macos_agent_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/a05304cb-377d-4413-9213-45e7d2bd0bcb)

    </details>
+ <details><summary>Logs and configuration</summary>

    

    [ossec.zip](https://github.com/user-attachments/files/17803600/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    
    [csv.zip](https://github.com/user-attachments/files/17803601/csv.zip)

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    
  ![macos-solaris_solaris-pre-release_CPU](https://github.com/user-attachments/assets/980d68cb-490f-4ab5-8df9-a0ea1803a0c2)
  ![macos-solaris_solaris-pre-release_FD](https://github.com/user-attachments/assets/ee9cd1ae-98fc-46ec-8ee2-3165758b2a8b)
  ![macos-solaris_solaris-pre-release_RSS](https://github.com/user-attachments/assets/0d5cc024-78f0-44a9-8b27-a781a2f38e06)
  ![macos-solaris_solaris-pre-release_RSS_MAXMIN](https://github.com/user-attachments/assets/db462998-3086-4bac-b3be-6116ce1daddb)
  ![macos-solaris_solaris-pre-release_VMS](https://github.com/user-attachments/assets/eaf0284c-cfbf-4622-af9c-6d9f3e75506c)
  ![test_stress_vagrant_B4_solaris_agent_agentd_state_AgentD_Number_of_events_buffered](https://github.com/user-attachments/assets/0e2fe611-da43-4881-8f22-f7a23d1d7f42)
  ![test_stress_vagrant_B4_solaris_agent_agentd_state_AgentD_Number_of_generated_events](https://github.com/user-attachments/assets/ae66af86-84ee-4f01-82f1-411b72776ac8)
  ![test_stress_vagrant_B4_solaris_agent_agentd_state_AgentD_Number_of_messages](https://github.com/user-attachments/assets/e35eb567-7d83-417c-8920-e58afbbaed95)
  ![test_stress_vagrant_B4_solaris_agent_agentd_state_AgentD_Status](https://github.com/user-attachments/assets/134b049a-4841-42e4-b422-97687d68784a)

    </details>
+ <details><summary>Logs and configuration</summary>

    
    [ossec.zip](https://github.com/user-attachments/files/17803604/ossec.zip)

    </details>
+ <details><summary>CSV</summary>

    [csv.zip](https://github.com/user-attachments/files/17803605/csv.zip)

        

    </details>

</details>

## Conclusion :yellow_circle: 

Plots compared to https://github.com/wazuh/wazuh/issues/26673

### Logs :yellow_circle: 

Known issues:

- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5538
- https://github.com/wazuh/wazuh/issues/25222
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4656

**Comment by MARCOSD4** [comment]
# Analysis report :yellow_circle: 
 
## Graphs :green_circle:  

<details><summary>Manager</summary>

Disk_written, Write_ops: small increase in wazuh-modulesd.

</details>

<details><summary>macOS</summary>

RSS, VMS: decrease in modulesd (similar to previous versions)
Small increase in number of events and messages.

</details>


<details><summary>Solaris</summary>

-  No abnormalities found.

</details>


## Logs :yellow_circle:


<details><summary>macOS</summary>

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4867
```
2024/11/14 18:38:45 wazuh-agentd ERROR: Connection socket: Connection reset by peer (54)
2024/11/14 18:39:12 wazuh-agentd ERROR: (1216): Unable to connect to '[x.x.x.x]:1514/tcp': 'Connection refused'
2024/11/15 12:31:12 wazuh-agentd ERROR: (1208): Unable to connect to enrollment service at '[x.x.x.x]:1515'
2024/11/17 06:40:37 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/17 06:40:37 wazuh-agentd ERROR: Connection socket: Operation timed out (60)
2024/11/17 06:40:37 wazuh-syscheckd WARNING: Process locked due to agent is offline. Waiting for connection...
2024/11/15 12:31:22 wazuh-agentd WARNING: (4101): Waiting for server reply (not started). Tried: 'x.x.x.x'. Ensure that the manager version is 'v4.10.0' or higher.
2024/11/15 12:31:22 wazuh-agentd WARNING: Unable to connect to any server.
```

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/5538 
```
[2024-11-15_00:40:15] [WARNING] Error reading /var/ossec/logs/ossec.log: [Errno 2] No such file or directory: '/var/ossec/logs/ossec.log'
```



</details>

<details><summary>Manager</summary>

- Expected in stress test
```
2024/11/17 00:00:18 sca WARNING: Interval overtaken.
2024/11/15 12:31:38 wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
```

- Reported in https://github.com/wazuh/wazuh/issues/25222

```
2024/11/14 18:38:47 wazuh-remoted WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '002' at 'any'.
2024/11/14 18:38:47 wazuh-remoted WARNING: Decrypt the message fail, socket 36
2024/11/14 18:38:47 wazuh-remoted WARNING: Unexpected message (hex): 'ffffffff46ff62ff08ff185b7cffff7d1effff2cffffff763617ffffffffffff5eff2e7effffffffff5525ffff7273ff293affff3d39ff01ffffff48045e43ff7803ff14ffffff1cff0017347e57ffff750cff5655ff18ffffffffff7865ffffffffffff6e4dff30ffffffffffffffff5c44ffff467cffff4eff0c60ffffff01ff40ff3953ffff47ffff29ffff0cffffffffffffff1508ffff131e48ffffff2505ff1dffff175c7e38ff74ffff43522cffff39ffffff0d333644ffff30ffffffff66ff3dffffff266b2008505cffffff7f04763763ffff3475ff40ff4effff1c336707ff183e58ff78ffff6f53475fffffffffffff453b1a2a0100002130303221234145533affffff0c5fffffffff05ff5cffff16305373631e06434eff0effffff32ff4cff0fffff5affffffff4432ff7e6303ff2d7a674d7f77ffff0d4affff1aff13ff69ff7cff76ffff69ff074c0cff4b5dffff6117ffff53ffff6527ffffff371e5fffffffffffffffff376569ffff4dff621bffff5b43ff14ffff5cff4aff6d552a51ffffff35ff4cff46ff6712ffff60ffffff07ffff72ffff1c645d3243ffffff2e25ffff69ff00ff4a4e0dffff0734ffff517f1750ff7f1eff23ff3f79ff05ffffffff6bffffffff3affffffffffffff11ff0704ffff22ffff420fff37ffff2c20ff5eff33ffff4f042759ffffffff7b3fff172b5dff0328ffffff57ffffff76ff47ff63ff521831ffff1bffffff2f115e7810ffff1837ffffff134aff3eff7876ff0100002130303221234145533a2b7aff7c7e301d55ff45ff0b5763382863ffffff23ffffffff7cffffffff7effffff0c531dffff6fffff480c271dff663f20ffff1bffffff3474557534ff3a20ffffffffff5effffffffffff0affff34ffffffffffff124053ff012bffff4a3aff1c0a2261ffff4a1d5539ffffffff7038ff45ffff52116705ffffffff00ff6affff3f064fff105738ffffff284171ff7f04ff336f32ff1bffffff78ff291874ffffffff41ff5009ffffff2c2cffff39ff7fffff05113aff0fffff31ff7cffffffffffff4b41ff0affff297244ff64ff69ff72220935ff5e176d14ffffff19ffff116dff49ff655affff4523ff067cff19ff0bff4b5d4b7922ff24ff5bffffffffffff11ffff610fff7107ffff22ff28043e595effffff27ff667effffffff715effffffff643fff19ffffff686a19ff49ffffffff0430ffff1a34ff2a2157ffffffffff4f5affff79ffff50ff76ff05ff2fff171242405f46ff211e73ff02ff4151ffffffff1fff753b3aff25ff40ffffffffffffff3bffffff29ffff2cffff5a46ff7f09ff467fffff682132ffff3cff75ff1affffffffffff210c43ff56ff2a0100002130303221234145533a0c426e75ff375e7bffffffff69ff1c3effffff7dff68206b3027ff1535ff'
2024/11/17 06:40:42 wazuh-remoted WARNING: Too big message size from socket [32].
"2024/11/17 06:40:42 wazuh-remoted WARNING: Unexpected message (hex): 'ffff43670645ff5a0cff6717ffff62706736ffff4a3d1effffffffff7349ffff6045ff72683f3bffffffffffff410a5d5bffff3dffff247dffffff4376ffff244216ff32413651ff334bffffff4013407e14ff157e1855ffff5dff6919ffff59'"
```

- Reported in: https://github.com/wazuh/wazuh/issues/22565
```
2024/11/14 18:26:40 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-x-x-x-x.ec2.internal', retrying until the connection is successful.
2024/11/14 18:26:40 indexer-connector WARNING: No username and password found in the keystore, using default values
```

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4469 
```
2024/11/14 18:39:27 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4656
```
2024/11/17 00:14:39 wazuh-modulesd:azure-logs ERROR: azure-activity: Returned error code: '1'.
```



</details>


<details><summary>Solaris</summary>

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4867 
```
2024/11/14 18:39:12 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/14 18:39:12 wazuh-agentd ERROR: (1216): Unable to connect to '[x.x.x.x]:1514/tcp': 'Connection refused'.
2024/11/15 12:28:41 wazuh-agentd ERROR: Connection socket: Connection reset by peer (131)
2024/11/14 18:39:12 wazuh-agentd WARNING: Process locked due to agent is offline. Waiting for connection...
2024/11/15 12:30:30 wazuh-agentd WARNING: Server unavailable. Setting lock.
```

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4469
```
2024/11/14 18:32:41 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```



</details>

**Comment by rafabailon** [comment]
### LGTM
