### ISSUE TITLE
Security failure: default installation directory in /var

### ISSUE THREAD

**Issue by slhotellier** [wazuh/wazuh#26901]
|4.9.0|ALL Component|Install type: standart|Install method step by step|Platform RHEL8.10|

Hello

the installation procedure places Wazuh components in /var by default, including executables.

The CIS 5009 rule indicates that /var must be in noexec.

It is therefore necessary to modify the installation procedure in order to place the executables on a mount point authorizing the execution of programs.

Please review the installation procedure in order to comply with the CIS 5009 rule.

This issue is valid for both the server and agent components.

Best regards

**Comment by SirStephanikus** [comment]
I know the CIS Framework in and out ... almost by heart.

I doubt, that `/var` is mentioned anywhere to have the `noexec` option set. I rather assume, you misread the text.
`/var/tmp` is recommended to have the `noexec` option set.

May I ask for more details? Perhaps a screenshot?

**Comment by SirStephanikus** [comment]
Ok, I guess I know what you meant:

`  # 1.1.3.3 Ensure noexec option set on /var partition. (Automated)
  - id: 5009
    title: "Ensure noexec option set on /var partition."
    description: "The noexec mount option specifies that the filesystem cannot contain executable binaries."
    rationale: "Since the /var filesystem is only intended for variable files such as logs, set this option to ensure that users cannot run executable binaries from /var."
    remediation: "Edit the /etc/fstab file and add noexec to the fourth field (mounting options) for the /var partition. Example: <device> /var <fstype> defaults,rw,nosuid,nodev,noexec,relatime 0 0 Run the following command to remount /var with the configured options: # mount -o remount /var."
    compliance:
      - cis: ["1.1.3.3"]
      - cis_csc_v8: ["3.3"]
      - cis_csc_v7: ["14.6"]
      - cmmc_v2.0: ["AC.L1-3.1.1", "AC.L1-3.1.2", "AC.L2-3.1.3", "AC.L2-3.1.5", "MP.L2-3.8.2"]
      - hipaa: ["164.308(a)(3)(i)", "164.308(a)(3)(ii)(A)", "164.312(a)(1)"]
      - iso_27001-2013: ["A.9.1.1"]
      - nist_sp_800-53: ["AC-5", "AC-6"]
      - pci_dss_v3.2.1: ["7.1", "7.1.1", "7.1.2", "7.1.3"]
      - pci_dss_v4.0: ["1.3.1", "7.1"]
      - soc_2: ["CC5.2", "CC6.1"]
    condition: all
    rules:
      - "c:findmnt --kernel /var -> r:noexec"`
      
I checked the real CIS-Benchmarks at CIS directly. `/var` should **NOT** have the `noexec` flag set. `/tmp` and `/var/tmp` , but not `/var` ... yes, this is wrong. 

As a workaround, you can edit the SCA file your self to fix the path.

**Comment by SirStephanikus** [comment]
Wazuh does a great job here, well, in software developing, mistakes happen. And your issue is just a small issue.

Anyway, it takes just some seconds to fix it by yourself --> Super easy, barely an inconvenience.

**Comment by slhotellier** [comment]
hello. 
I'm not sure that it only takes a few seconds to redo the installations from source (because it seems the only solution to change the installation directory). 
By re-consulting the Linux standards, it turns out that /var is dedicated to receiving only data files (log, database) and especially no executable files. 
The main part of my problem is not to have a good CIS score but to respect the highest security standards. 
I am perfectly aware of the enormous work done by the Wazuh teams. 
but it's really a shame not to respect the recommendations, especially when it comes to security. 
Best regards

**Comment by slhotellier** [comment]
Hi Stephan

I would prefer that we continue this debate in private in order to keep the thread as clean as possible.
However, here are some sources of information that support my statements:
1. usage of / var
1.1 https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05.html#purpose31 : "/var contains variable data files. This includes spool directories and files, administrative and logging data, and transient and temporary files."
1.2 https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/6/html/storage_administration_guide/ch-filesystem: "2.1.1.14. The /var/ Directory
Since the FHS requires Linux to mount /usr/ as read-only, any programs that write log files or need spool/ or lock/ directories should write them to the /var/ directory. The FHS states /var/ is for variable data, which includes spool directories and files, logging data, transient and temporary files."

=> only data no reference to executable files


2. noexec on /var
2.1 https://static.open-scap.org/ssg-guides/ssg-ol8-guide-index.html: Rule ID: xccdf_org.ssgproject.content_rule_mount_option_var_noexec "The noexec mount option can be used to prevent binaries from being executed out of /var. Add the noexec option to the fourth column of /etc/fstab for the line which controls mounting of /var.
The /var directory contains variable system data such as logs, mails and caches. No binaries should be executed from this directory."
2.2 https://cyber.gouv.fr/sites/default/files/document/fr_np_linux_configuration-v2.0.pdf: rule 28 page 33 and 34: "/var nosuid,nodev,noexec Partition containing variable files during the life of the system
(mails, PID files, databases
of a service)"

=> only data, executable files are "forbidden"

Once again, I want to say it again, I find that Wazuh is a very good tool, I am very satisfied with the work of the development team, but it seems to me that it is important to go a step further by standardizing the deployment in more suitable directories. especially since this seems possible by installing from source.

Best regards

**Comment by slhotellier** [comment]
I'm surprised : 

> /noexec on the full /var path would break almost every Linux OS out there, simply, because many 3rd party applications are installed somewhere in /var (often /var/lib ) --> Databases, Monitoring Software, WebApps, various Server Applications etc.

has you can found in Linux Foundations : Data are in /var, executable files are in /usr
All databases I known only put data in /var and no executable files
I don't know software except Wazuh that put executables files in /var (I work with a lot of software like Nagios, Zabbix, Oracle, Mysql, PostgreSQL, MariaDB, RabbitMQ, Kafka, Glassfish, TomEE, Apache, NGinx and so on)

Oracle Linux put noexec on /var, and I m sure it is not the only one.

my RSSI was shocked that Wazuh default installation directory was /var

**Comment by slhotellier** [comment]
For information I have change the issue title to security failure : default installation directory in /var 
because CIS 5009 is no more the subject (not in CIS recomendation)

**Comment by SirStephanikus** [comment]
> (I work with a lot of software like Nagios, Zabbix, Oracle, Mysql, PostgreSQL, MariaDB, RabbitMQ, Kafka, Glassfish, TomEE, Apache, NGinx and so on)
> 

Issue this command:
`find /var/ -type f -executable -print`

And then reevaluate your above statement. ☕️

**Comment by slhotellier** [comment]
I made the test

> find /var/ -type f -executable -print

nothing comes except backup files that have exec flag  but no real executable file.

**Comment by SirStephanikus** [comment]
Interesting, I checked quickly 11 different systems from various companies. 
--> A plethora of environments, many Debians & Rockies, some Ubuntus ...
All had bins in `/var`.

I don't say that this is correct in regard of the FHS, I just say, that there are many applications that place themselves in `/var`.

However, I find it really insightful how your environment runs. May I ask (send via E-Mail) for some details, just for the exchange of professional opinions?

**Comment by slhotellier** [comment]
I recieved a mail of wazuh team, there is already an issue on it : [New Wazuh directory layout](https://github.com/wazuh/wazuh/issues/9175)

It will be resolved in Wazuh 5.0.
