### ISSUE TITLE
Add OS version field to agent registration body

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26949]
# Description

Following the recent changes in the registration body of the agent carried out in https://github.com/wazuh/wazuh-agent/pull/320, we need to modify the `POST /agents` endpoint to follow the new structure which adds the `host.os.version` field:
```{
    "groups": [],
    "host": {
        "architecture": "aarch64",
        "hostname": "tomas",
        "ip": [
            "192.168.64.16",
            "fde7:1d32:1c4f:33cc:70ef:32ff:fecc:228b"
        ],
        "os": {
            "name": "Ubuntu",
            "platform": "Linux",
            "version": "22.04.5 LTS (Jammy Jellyfish)"
        }
    },
    "id": "784832cf-f189-4da8-8abd-b5b99a23e9a2",
    "key": "KPhX7AZXe3FK32wj1hKFaZG8RnfdDRnE",
    "name": "tomas",
    "type": "Endpoint",
    "version": "5.0.0"
}
```

**Comment by javiersanchz** [comment]
## Update

- I begin by adding the os.version parameter for the agent to the OS class.
- Still needs to be reviewed and verified.

**Comment by javiersanchz** [comment]
## Update

- Development is complete, pending the conclusion of testing due to failures in the test environment.

**Comment by javiersanchz** [comment]
## Update

The agent's OS version was added, and tests were included in the PR https://github.com/wazuh/wazuh/pull/26994.
