### ISSUE TITLE
VD files in tmp that are not deleted after processing

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#26947]
## Description
This must be deleted on the first server start and apparently it remains.

```
[root@mvp-12-centos-8 /]# ll /tmp/wazuh-server/
total 214864
-rw-r-----. 1 root wazuh    119094 Oct 18 12:35 engine_store_0.0.2_5.0.0.tar.gz
-rw-r-----. 1 root wazuh 219894220 Nov 17 01:09 vd_1.0.0_vd_4.10.0.tar.xz
```

# DoD
- [x] Confirm this issue.
- [x] Fix if the bug exists.

**Comment by JcabreraC** [comment]
The file `vd_1.0.0_vd_4.10.0.tar.xz` it is deleted.

The file `engine_store_0.0.2_5.0.0.tar.gz` is the one from S3 and remains.

**Comment by JcabreraC** [comment]
The file `vd_1.0.0_vd_4.10.0.tar.xz` is deleted after unzipping on the first run.
The file `engine_store_0.0.2_5.0.0.0.tar.gz` remains after installation. It needs to be fixed.
