### ISSUE TITLE
Wazuh server configuration pulling

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#26954]
# Description

As part of implementing the new server configuration, we must make a series of modifications to ensure that it is available for the services it initializes.
The required changes are:
  - Modify the `wazuh-server` initialization process:
    1. Server: functionality related to the type of cluster node.
    2. Engine
    3. Comms API
    4. Management API
  - Define and make a new socket available in the master cluster node for the processes to pull the configuration from it. This is especially crucial for the Engine process and its connection to the Indexer since it does not receive nor will read the `wazuh-server.yml` configuration file. 
  - Refine any option related to the Engine according to what it expects in its configuration.

**Comment by RamosFe** [comment]
## Unix Socket

A new server was created to handle the request for this new functionality. The server uses HTTP over a UNIX socket, the same logic as the one in the Communications API:

https://github.com/wazuh/wazuh/blob/575f27c7c12996ac1aade433445cd9c82ebed077/apis/comms_api/core/unix_server/server.py#L11-L30

The new socket is `/run/wazuh-server/server.sock` and has a similar structure to the code used in the Communications API:

https://github.com/wazuh/wazuh/blob/575f27c7c12996ac1aade433445cd9c82ebed077/framework/wazuh/core/cluster/unix_server/server.py#L10-L22


### Request and Query Parameters

The new endpoint is `/commands` and requests the configuration file contents in JSON format. The endpoint also has a `sections` query parameter, allowing the user to specify which configuration sections it wants to pull and avoiding sending unnecessary sections. The `sections` parameter accepts a string with a comma-separated list of sections, for example, `sections=indexer,engine`. Here are some request examples:


<details>
<summary>Request without specifying the section</summary>

```console
root@wazuh-master:/# curl --unix-socket /run/wazuh-server/server.sock -X GET "http://localhost/api/v1/config" -i
HTTP/1.1 200 OK
date: Mon, 25 Nov 2024 19:22:48 GMT
server: uvicorn
content-length: 2480

{
  "server": {
    "port": 1516,
    "bind_addr": "0.0.0.0",
    "nodes": [
      "wazuh-master"
    ],
    "hidden": false,
    "update_check": false,
    "node": {
      "name": "manager_01",
      "type": "master",
      "ssl": {
        "key": "/var/lib/wazuh-server/etc/slmanager.key",
        "cert": "/var/lib/wazuh-server/etc/sslmanager.cert",
        "ca": "/var/lib/wazuh-server/etc/sslmanager.ca",
        "keyfile_password": ""
      }
    },
    "worker": {
      "intervals": {
        "sync_integrity": 9,
        "keep_alive": 60,
        "connection_retry": 10
      },
      "retries": {
        "max_failed_keepalive_attempts": 2
      }
    },
    "master": {
      "intervals": {
        "timeout_extra_valid": 40,
        "recalculate_integrity": 8,
        "check_worker_last_keep_alive": 60,
        "max_allowed_time_without_keep_alive": 120,
        "max_locked_integrity_time": 1000
      },
      "processes": {
        "process_pool_size": 2
      }
    },
    "communications": {
      "zip": {
        "max_size": 1073741824,
        "min_size": 31457280,
        "compress_level": 1,
        "limit_tolerance": 0.2
      },
      "timeouts": {
        "cluster_request": 20,
        "dapi_request": 200,
        "receiving_file": 120
      }
    },
    "logging": {
      "level": "debug2"
    },
    "cti": {
      "update_check": true,
      "url": "https://cti.wazuh.com"
    }
  },
  "indexer": {
    "hosts": [
      "wazuh-indexer:9200",
      "wazuh-indexer2:9200"
    ],
    "username": "admin",
    "password": "SecretPassword1%",
    "ssl": {
      "use_ssl": false,
      "key": "/var/lib/wazuh-server/etc/indexer.key",
      "certificate": "",
      "certificate_authorities": [
        "/var/lib/wazuh-server/etc/indexer1.ca",
        "/var/lib/wazuh-server/etc/indexer2.ca"
      ]
    }
  },
  "engine": {
    "tzdv_automatic_update": false,
    "client": {
      "api_socket_path": "/run/wazuh-server/engine.socket",
      "retries": 3,
      "timeout": 10
    },
    "logging": {
      "level": "info"
    }
  },
  "management_api": {
    "host": [
      "0.0.0.0",
      "::"
    ],
    "port": 55000,
    "drop_privileges": true,
    "max_upload_size": 10485760,
    "jwt_expiration_timeout": 900,
    "rbac_mode": "white",
    "intervals": {
      "request_timeout": 10
    },
    "ssl": {
      "key": "/etc/wazuh-server/api/configuration/ssl/server.key",
      "cert": "/etc/wazuh-server/api/configuration/ssl/server.crt",
      "use_ca": false,
      "ca": "",
      "ssl_protocol": "auto",
      "ssl_ciphers": ""
    },
    "logging": {
      "level": "debug",
      "format": [
        "plain"
      ],
      "max_size": {
        "enabled": false,
        "size": "1M"
      }
    },
    "cors": {
      "enabled": false,
      "source_route": "*",
      "expose_headers": "*",
      "allow_headers": "*",
      "allow_credentials": false
    },
    "access": {
      "max_login_attempts": 50,
      "block_time": 300,
      "max_request_per_minute": 99999
    }
  },
  "communications_api": {
    "host": "0.0.0.0",
    "port": 27000,
    "workers": 4,
    "logging": {
      "level": "debug",
      "format": [
        "plain"
      ],
      "max_size": {
        "enabled": false,
        "size": "1M"
      }
    },
    "batcher": {
      "max_elements": 5,
      "max_size": 3000,
      "wait_time": 0.15
    },
    "ssl": {
      "key": "/etc/wazuh-server/api/configuration/ssl/server.key",
      "cert": "/etc/wazuh-server/api/configuration/ssl/server.crt",
      "use_ca": false,
      "ca": "",
      "ssl_protocol": "auto",
      "ssl_ciphers": ""
    }
  }
}
```

</details>

<details>
<summary>Request specifying the section</summary>

```console
root@wazuh-master:/# curl --unix-socket /run/wazuh-server/socket/server.sock -X GET "http://localhost/api/v1/config?sections=indexer" -i
HTTP/1.1 200 OK
date: Mon, 25 Nov 2024 18:22:51 GMT
server: uvicorn
content-length: 316

{
   "indexer":{
      "hosts":[
         "wazuh-indexer:9200",
         "wazuh-indexer2:9200"
      ],
      "user":"admin",
      "password":"SecretPassword1%",
      "ssl":{
         "use_ssl":false,
         "key":"/var/lib/wazuh-server/etc/indexer.key",
         "cert":"/var/lib/wazuh-server/etc/indexer.crt",
         "ca":[
            "/var/lib/wazuh-server/etc/indexer1.ca",
            "/var/lib/wazuh-server/etc/indexer2.ca"
         ]
      }
   }
}

```

</details>


<details>
<summary>Request with invalid section</summary>

```console
curl --unix-socket /run/wazuh-server/socket/server.sock -X GET "http://localhost/api/v1/config?sections=example" -i
HTTP/1.1 400 Bad Request
date: Mon, 25 Nov 2024 18:13:02 GMT
server: uvicorn
content-length: 72
content-type: application/json

{
   "detail":"Invalid section(s): 'example' is not a valid ConfigSections"
}
```

</details>

The sections available are the following:
https://github.com/wazuh/wazuh/blob/b88da97bba93bcf3d7823394bd856605eb27c9f6/framework/wazuh/core/config/client.py#L16-L22

For now, the sections available are the ones related to the services, in the future, we could add options to filter by subsections, as we do in the Management API.

**Comment by RamosFe** [comment]
## Indexer config changes

The following changes were made to maintain the consistency between the configuration and what the Engine expects when pulling the configuration.

- The `host` configuration option is changed to a list of hosts. The new configuration option is `hosts` and expects the following format:

```yaml
indexer:
  hosts:
    - host: localhost
      port: 9200
```

The indexer client uses the first `host-port` in the list.

- The `ca` configuration option in the Indexer configuration is changed to accept a list of ca paths. The field is now called `certificate_authorities`:
```yaml
    certificate_authorities:
      - <PATH_TO_CA_FILE>
```

- The `cert` configuration option in the Indexer configuration is now called `certificate`.
- The `user` configuration option in the Indexer configuration is now called `username`.

- New options were added to the logging levels for the Engine configuration. The accepted values are the following:
https://github.com/wazuh/wazuh/blob/e9c286eb980294ad9c6a670be9b4fe72dec7dfc8/framework/wazuh/core/config/models/logging.py#L32-L39

- Due to the need of the Engine to use `URI` to communicate with the Indexer, the `host` and `port` fields are serialized differently to `JSON`. This is because of the Indexer client used in the server, where it is initialized with the host and port, so we needed a way to maintain this format but return a `URI` for the Engine. The following classes were changed to handle this:

https://github.com/wazuh/wazuh/blob/e9c286eb980294ad9c6a670be9b4fe72dec7dfc8/framework/wazuh/core/config/models/indexer.py#L8-L48

This serialization logic is only used for `json`, if we made this change to `plain` when we updated the configuration file bia API, the URI would be saved instead of the expected format, causing an error when reading the file.

Finally, this is the `JSON` response:

<details>
<summary>Indexer config in JSON</summary>

```console
root@wazuh-master:/# curl --unix-socket /run/wazuh-server/socket/server.sock -X GET "http://localhost/api/v1/config?sections=indexer" -i
HTTP/1.1 200 OK
date: Mon, 25 Nov 2024 18:22:51 GMT
server: uvicorn
content-length: 316
{
  "indexer": {
    "hosts": [
      "https://wazuh-indexer:9200",
      "https://wazuh-indexer2:9200"
    ],
    "username": "admin",
    "password": "SecretPassword1%",
    "ssl": {
      "use_ssl": false,
      "key": "/var/lib/wazuh-server/etc/indexer.key",
      "certificate": "/var/lib/wazuh-server/etc/indexer.crt",
      "certificate_authorities": [
        "/var/lib/wazuh-server/etc/indexer1.ca",
        "/var/lib/wazuh-server/etc/indexer2.ca"
      ]
    }
  }
}
```

</details>

Finally, the final format of the Indexer configuration is:
```yaml

indexer:
  hosts:
    - host: localhost
      port: 9200
  username: admin
  password: admin
  ssl:
    use_ssl: true
    key: <PATH_TO_KEY_FILE>
    certificate: <PATH_TO_CERT_FILE>
    certificate_authorities:
      - <PATH_TO_CA_FILE>
 ```
