### ISSUE TITLE
Update runner OS version for style check workflow

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#26966]
## Description

It was found that the workflow that checks the code format has a runner based in Ubuntu 22.04
https://github.com/wazuh/wazuh/blob/b3915ae16d5fe2836b64b2d1f5209d2bc6914c9f/.github/workflows/engine_style_documentation.yml#L142-L143

This means that ` clang-format version 14.0.0-1ubuntu1.1` is used.
But the dev container is based on Ubuntu 24.04

https://github.com/wazuh/wazuh/blob/b3915ae16d5fe2836b64b2d1f5209d2bc6914c9f/src/engine/tools/devContainer/.devcontainer/Dockerfile#L1

And `clang-format version 18.1.3 (1ubuntu1)` is used instead.

This difference leads to errors and inconsistencies.

## DoD

- [ ] Update the OS defined in the workflow
- [ ] Confirm the test doesn't fail after the change

**Comment by NahuFigueroa97** [comment]
## Update

Clang 18
```
╭─root@0c35081c3276 /workspaces/devContainer/wazuh ‹enhancement/26130-vulnerability-detector-port-adjustment-of-vulnerability-descriptions●› 
╰─# clang-format-18 -i src/engine/source/vdscanner/src/fieldAlertHelper.hpp --style=file -assume-filename=src/engine/.clang-format  --dry-run 
src/engine/source/vdscanner/src/fieldAlertHelper.hpp:58:85: warning: code should be clang-formatted [-Wclang-format-violations]
        static_assert(std::is_arithmetic_v<std::remove_cv_t<std::remove_reference_t<
                                                                                    ^
src/engine/source/vdscanner/src/fieldAlertHelper.hpp:59:35: warning: code should be clang-formatted [-Wclang-format-violations]
                              T>>> || std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string>,
```

Clang 14
```
╭─root@0c35081c3276 /workspaces/devContainer/wazuh ‹enhancement/26130-vulnerability-detector-port-adjustment-of-vulnerability-descriptions●› 
╰─# clang-format-14 -i src/engine/source/vdscanner/src/fieldAlertHelper.hpp --style=file -assume-filename=src/engine/.clang-format  --dry-run 
src/engine/source/vdscanner/src/fieldAlertHelper.hpp:33:79: warning: code should be clang-formatted [-Wclang-format-violations]
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string_view>
                                                                              ^
src/engine/source/vdscanner/src/fieldAlertHelper.hpp:33:97: warning: code should be clang-formatted [-Wclang-format-violations]
    if constexpr (std::is_same_v<std::remove_cv_t<std::remove_reference_t<T>>, std::string_view>
                                                                                                ^
```

**Comment by NahuFigueroa97** [comment]
## Update

After confirming that the --dry-run option both indicate the same errors, I tried removing the option and noticed that versions 14 and 18 correct in a different way, the result is not the same.
I am verifying that the configuration files with the options are the same in both cases. Apparently there is a problem with the --dump-config option in charge of returning the options used during execution. The default configuration is always returned. To make sure that I take the correct file, I incorrectly modified a configuration value and clang reported it, with which I intuit that it takes the file correctly, although the dump returns another configuration.

**Comment by NahuFigueroa97** [comment]
## Update

- The BreakBeforeBinaryOperators parameter we used in the configuration and that is set to NonAssignment is indicating that there must be a break after a binary operator that is different from = . clang-format-14 is misinterpreting the operators, it breaks at the angle brackets in the template, instead of the || like clang-format-18 does. I discovered this by setting None as the value of BreakBeforeBinaryOperators , which indicates that there must be a break after the operators. In that case both clang-format-18 (the one used by the dev-container) and clang-format-14 (used in the workflow) give the same result
- In this case I recommend only updating the clanf-format version in the workflow instead of the dev-container since it is a specific problem of that version
- There is no other difference in the configuration files, other than new options added by clang-format-18

**Comment by JcabreraC** [comment]
Extended ETA while deciding whether to upgrade clang-format or downgrade the dev-container.

**Comment by JcabreraC** [comment]
ETA extended by priority in other issues.

**Comment by NahuFigueroa97** [comment]
## Update

- Downgrade devcontainer version to 20.04
- Solving problems during instalation
