### ISSUE TITLE
JSON Decoder Custom Field for GeoIP Lookup

### ISSUE THREAD

**Issue by mr-worf** [wazuh/wazuh#26961]
|Wazuh version|Component|Action type |
|---|---|---|
| 4.9.2 | Decoder/Rules | Feature/Improve |

I have a VPN server that generates logs in JSON format, as shown in the example below (note: real data has been altered):

```
{"id":"673e725e7ab4ae5d7b206d9e","event":"user_connect_success","timestamp":1732145758.110738,"host_id":"53023c49d161402c9779b02e92ecbf6f","host_name":"v.acme.com","host_public_address":"3.9.16.24","host_public_address6":null,"host_local_address":"192.168.1.9","host_local_address6":"fe80::1375:2923:f7d4:50e4","remote_address":"1.2.11.22","platform":"mac","device_id":"55c573ad793a3cbfa412ffddf9986d23","device_name":"spice-dreams","mac_addr":"71:77:7f:7f:77:17","auth_nonce":"b'ec8886cc16aa4a62461b4f892f6c44e92c1nn7721f59321c5c69c0d6b8325879'","auth_timestamp":1732145757,"auth_modes":["2fa"],"reauth":false,"organization_id":"778e79f077d9f85f1bcd377c","organization_name":"Acme","user_id":"66aa152a2ab4ae5d7bb3da97","user_name":"Foo.Bar","user_email":"foo.bar@aaa.com","user_type":"client","user_auth_type":"mfa","server_id":"66a371784cd8b287e4697f48","server_name":"ABB-M","server_network":"192.168.15.0/24","server_port":11259,"event_long":"User connected"}
```
It would be great to have the ability to instruct a JSON decoder on which fields to use for GeoIP lookups from JSON logs, such as remote_address. The goal is to configure an alert that triggers whenever a VPN connection originates from outside a predefined list of countries.

I came across this PR: [#24985](https://github.com/wazuh/wazuh/issues/24985#issuecomment-2268897822), which explains how to use GeoIP lookup. In the comments, it is mentioned:
    ` Every generated alert that includes the srcip or dstip field will look for the srcgeoip or dstgeoip information in the GeoIP.dat database.`

Is there a possibility to extend this functionality to support custom fields, such as `remote_address`, for GeoIP lookups? Alternatively, is there a known workaround to achieve GeoIP lookup on a custom field?

**Comment by juliancnn** [comment]
Hi @mr-worf ,

In wazuh 4.x we do not support this functionality, but we are currently developing a replacement for wazuh-analisysd, called [wazuh-engine](https://github.com/wazuh/wazuh/issues/23577). This new engine supports full manipulation of json fields, such as deleting, modifying and adding fields to a json object. Within this functionality it also allows to extract IPs from custom fields, validate them and map them to another field.
The event will be normalized at the decoding stage, allowing to extract the IPs and obtain the geolocation of the given IPs.

Regards,

**Comment by mr-worf** [comment]
Thank you for the response!

**Comment by JcabreraC** [comment]
As @juliancnn indicates, Wazuh 4.x does not support this functionality, but the upcoming Wazuh-engine will enable advanced JSON manipulation and IP geolocation.

Closing this issue.
