### ISSUE TITLE
Migrate keystore tool

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#26971]
## Description
We need to migrate the [keystore tool](https://github.com/wazuh/wazuh/blob/9195ce75c93c3e1bd8ee953e3ac30bba215d59f0/src/shared_modules/keystore) to the engine project. The tool will be a separate module in the engine directory, similar to the [vdscanner](https://github.com/wazuh/wazuh/blob/81bf9ae0bbb0a91811b1a39efeade99186b4823d/src/engine/source/vdscanner) one

>[!IMPORTANT]
> [Example in python](https://github.com/wazuh/wazuh/pull/27066#issuecomment-2524843328) for the @wazuh/devel-pyserver team

## DoD
- [x] Tool migrated
- [x] Tool tested

**Comment by sebasfalcone** [comment]
## Extra
On the other hand, the @wazuh/devel-pyserver team will be working with these databases, we need to provide them with a comprehensive guide on how to read rocksDB databases using Python

Here is the guide to the API for Python:
- https://python-rocksdb.readthedocs.io/en/latest/api/database.html#database-object

**Comment by sebasfalcone** [comment]
## Update
- The tool has a hardcoded path queue/keystore that we could change
    - Path should be `/var/lib/wazuh_server/keystore`
- There is a legacy code related to the certificates that we could remove
    - We will maintain this feature but reset the version counter
- The static linking produces a big binary (200MB)
    - Post discussion, this is due to the binary being compiled in debug
- It was required to add OpenSSL to the project
    - Coordinate with @wazuh/devel-cppserver-div3 to see if this is truly necesary

**Comment by pereyra-m** [comment]
## Update

I continue with the migration.
The size problem was due to the debug compilation.
The new paths were checked with PyServer team.

**Comment by pereyra-m** [comment]
## Update

I keep working to adjust the final details of the migration.

**Comment by pereyra-m** [comment]
## Update

I fix a failing test.

**Comment by sebasfalcone** [comment]
## Definition update
The Keystore won't use a rocksdb database it will save its information in a plain text file located at /etc/wazuh-server/client.keystore 

File format:
```
<key>:<cipher key + cipher iv + cipher text>
<key>:<cipher key + cipher iv + cipher text>
```

**Comment by pereyra-m** [comment]
## Update

I remove the RocksDB dependency from the keystore according to the new requirements and update all the tests.

**Comment by pereyra-m** [comment]
## Update

Changes by review. Add UT. Perform manual testing.

**Comment by pereyra-m** [comment]
## Update

I modify the implementation again with the new definitions: we'll encrypt the whole file (instead of each key) and the IndexerConnector won't read the keystore directly.

**Comment by sebasfalcone** [comment]
## ETA update
Updated ETA due to changes in definitions and to accommodate for the reviews

**Comment by pereyra-m** [comment]
## Update

I apply some review changes and perform some manual tests.

**Comment by pereyra-m** [comment]
## Update

I update the doxygen as requested.

**Comment by pereyra-m** [comment]
## Update

I implement changes in the PR after review
