### ISSUE TITLE
OSSEC vs WAZUH.

### ISSUE THREAD

**Issue by givilleneuve** [wazuh/wazuh#270]
Hello Everyone,
I began to learn about OSSEC about 1 month ago and I'm fascinated.
Looking for more information about that, I found the project WAZUH.
If I understood correctly, WAZUH is a kind of a fork for OSSEC Project.
I couldn't find what the main differences are.
Is WAZUH Free as well as OSSEC?
Thank you.

**Comment by mgmacias95** [comment]
Hello @givilleneuve,

Wazuh was born as a fork of Ossec. It is a free open source software, just like Ossec. The source code is hosted on this github repository and can be downloaded and used for free. 

Some of the most important features made by the Wazuh team are:
* A kibana app to show all information and work with the manager.
* A RESTful API to retrieve information about the manager.
* Integration with OpenSCAP.
* An improved ruleset.
* Improved some components like log analysis and FIM capabilities.
* And bug fixes.

Also, the Wazuh team has added some features that can be read in [the documentation](https://documentation.wazuh.com/current/release-notes/index.html).

Finally, the Wazuh team is working on a new release which will include new features such as a cluster of managers, groups of agents, remote upgrades, integration with VirusTotal, unattended installation, new MSI installers for Windows, Chocolatey packages and much more.

Best regards,
Marta

**Comment by givilleneuve** [comment]
Hello @mgmacias95 ,
Thanks a lot.
I've deployed OSSEC in a Lab environment, and now I'll deploy WAZUH.
Regards,
Gilles Villeneuve.
