### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - SYSCOLLECTOR (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27005]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/90/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/monitor-manager-test_stress_B90_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/plots/test_stress_B90_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/logs/ossec_test_stress_B90_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/data/monitor-manager-test_stress_B90_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/data/test_stress_B90_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/data/test_stress_B90_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_manager_centos/data/test_stress_B90_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/monitor-agent-test_stress_B90_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/test_stress_B90_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/test_stress_B90_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/test_stress_B90_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/plots/test_stress_B90_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/logs/ossec_test_stress_B90_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/data/monitor-agent-test_stress_B90_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_centos/data/test_stress_B90_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/monitor-agent-test_stress_B90_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/test_stress_B90_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/test_stress_B90_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/test_stress_B90_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/plots/test_stress_B90_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/logs/ossec_test_stress_B90_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/data/monitor-agent-test_stress_B90_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_ubuntu/data/test_stress_B90_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/monitor-winagent-test_stress_B90_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/test_stress_B90_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/test_stress_B90_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/test_stress_B90_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/plots/test_stress_B90_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/logs/ossec_test_stress_B90_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/data/monitor-winagent-test_stress_B90_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B90-3600m/B90_agent_windows/data/test_stress_B90_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle:  

Known issues:
- https://github.com/wazuh/wazuh/issues/18179
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh/issues/22565

**Comment by pro-akim** [comment]
# Analysis report

Compared to: https://github.com/wazuh/wazuh/issues/26657

## Graphs :green_circle:

### Windows
Agentd_number_of_generated_events: increase of number of peaks

### Centos
No abnormalities were found

### Ubuntu
No abnormalities were found

### Manager
No abnormalities were found

## Logs :yellow_circle:


<details><summary>Windows</summary>

- Reported: https://github.com/wazuh/wazuh/issues/18179 Known issue
```
2024/11/22 22:39:53 wazuh-agent ERROR: SSL read (unable to receive message) 
2024/11/22 22:39:53 wazuh-agent ERROR: If Agent verification is enabled, agent key and certificates may be incorrect! 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/22 22:39:59 wazuh-agent ERROR: (1208): Unable to connect to enrollment service at '[172.31.11.52]:1515' 
```
</details>



<details><summary>Centos</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/22 22:39:54 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/22 22:39:54 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.11.52]:1514/tcp': 'Connection refused'. 
2024/11/22 22:39:54 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
```
</details>



<details><summary>Ubuntu</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/22 22:39:54 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/22 22:39:54 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.11.52]:1514/tcp': 'Connection refused'. 
2024/11/22 22:39:54 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
```
</details>



<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/22 22:37:55 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/22 22:37:55 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-11-52.ec2.internal', retrying until the connection is successful. 
2024/11/22 22:39:12 indexer-connector WARNING: Failed to sync agent '001' with the indexer. 
```

- Expected in stress test
```
2024/11/22 22:39:53 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
```
</details>

**Comment by hossam1522** [comment]
LGTM!
