### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - ROOTCHECK (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27002]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/87/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/monitor-manager-test_stress_B87_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/plots/test_stress_B87_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/logs/ossec_test_stress_B87_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/data/monitor-manager-test_stress_B87_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/data/test_stress_B87_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/data/test_stress_B87_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_manager_centos/data/test_stress_B87_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/monitor-agent-test_stress_B87_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/test_stress_B87_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/test_stress_B87_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/test_stress_B87_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/plots/test_stress_B87_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/logs/ossec_test_stress_B87_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/data/monitor-agent-test_stress_B87_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_centos/data/test_stress_B87_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/monitor-agent-test_stress_B87_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/test_stress_B87_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/test_stress_B87_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/test_stress_B87_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/plots/test_stress_B87_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/logs/ossec_test_stress_B87_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/logs/monitor-agent-test_stress_B87_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_ubuntu/logs/test_stress_B87_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/monitor-winagent-test_stress_B87_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/test_stress_B87_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/test_stress_B87_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/test_stress_B87_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/plots/test_stress_B87_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/logs/ossec_test_stress_B87_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/data/monitor-winagent-test_stress_B87_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B87-3600m/B87_agent_windows/data/test_stress_B87_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle:
- Known Issue:
  - https://github.com/wazuh/wazuh/issues/22565
  - https://github.com/wazuh/wazuh-jenkins/issues/5588
  - https://github.com/wazuh/wazuh-jenkins/issues/4867

- NOT Known Issue: 
  - https://github.com/wazuh/wazuh-qa-automation/issues/118

**Comment by joaquinsgi** [comment]
Compared to: https://github.com/wazuh/wazuh/issues/26663
 
# Analysis report  

## Graphs :black_circle: 

### Manager
Disk: small increase of syscheckd
Disk_read: increase of syscheckd (3.5 to 6)
FD: tiny increase of monitord
RSS: small increase of wazuhdb

### Ubuntu
VMS: decrease of modulesd

### Centos
PSS, USS: decrease of modulesd and agentd
RSS: decrase of agentd and modulesd
VMS: decrease of modulesd

### Windows
RSS, USS: increase in the range of fluctuations of agentd
VMS: less range of fluctuations of agentd


## Logs :black_circle:


<details><summary>Manager</summary>


- Expected in stress test
```
2024/11/14 20:34:32 wazuh-db WARNING: After vacuum, the database '000' has become just as fragmented or worse 
2024/11/14 18:34:23 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
```


- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/14 18:32:27 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/14 18:32:27 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-13-26.ec2.internal', retrying until the connection is successful. 
```







</details>



<details><summary>Ubuntu</summary>






- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:34:24 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:34:24 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.13.26]:1514/tcp': 'Connection refused'. 
```
</details>



<details><summary>Centos</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-16 15:14:03,790 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache
```


- Reported: https://github.com/wazuh/wazuh-qa-automation/issues/118 - Not Known issue

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 611, in check_wazuh_processes
    filter(lambda x: x.name() in binary_list, psutil.process_iter())]
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 610, in <listcomp>
    running_processes = [psutil.Process(x.pid) for x in
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 611, in <lambda>
    filter(lambda x: x.name() in binary_list, psutil.process_iter())]
  File "/usr/local/lib64/python3.6/site-packages/psutil/__init__.py", line 617, in name
    name = self._proc.name()
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1671, in name
    name = self._parse_stat_file()['name']
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1580, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1001644)

```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:34:24 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:34:24 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.13.26]:1514/tcp':'Connection refused'. 
```
</details>



<details><summary>Windows</summary>


No abnormalities were found

</details>

**Comment by hossam1522** [comment]
LGTM!
