### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27006]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/95/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/monitor-manager-test_stress_B95_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/plots/test_stress_B95_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/logs/ossec_test_stress_B95_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/data/monitor-manager-test_stress_B95_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/data/test_stress_B95_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/data/test_stress_B95_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_manager_centos/data/test_stress_B95_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/monitor-agent-test_stress_B95_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/test_stress_B95_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/test_stress_B95_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/test_stress_B95_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/plots/test_stress_B95_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/logs/ossec_test_stress_B95_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/data/monitor-agent-test_stress_B95_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_centos/data/test_stress_B95_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/monitor-agent-test_stress_B95_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/test_stress_B95_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/test_stress_B95_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/test_stress_B95_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/plots/test_stress_B95_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/logs/ossec_test_stress_B95_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/data/monitor-agent-test_stress_B95_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_ubuntu/data/test_stress_B95_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/monitor-winagent-test_stress_B95_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/test_stress_B95_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/test_stress_B95_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/test_stress_B95_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/plots/test_stress_B95_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/logs/ossec_test_stress_B95_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/data/monitor-winagent-test_stress_B95_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B95-3600m/B95_agent_windows/data/test_stress_B95_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### Plots
New issue
- https://github.com/wazuh/wazuh/issues/27092

### Logs
Known issue
- https://github.com/wazuh/wazuh-jenkins/issues/5588
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/3293
- https://github.com/wazuh/wazuh-jenkins/issues/4656
- https://github.com/wazuh/wazuh/issues/22565

**Comment by joaquinsgi** [comment]
# Analysis report
  
Compared to: https://github.com/wazuh/wazuh/issues/26501
Due to lack of DOCKER-LISTENER,CIS-CAT,OSQUERY,AZURE-LOGS in v,4.9.2-rc1, the comparison was done against v4.9.1-rc4

## Graphs :black_circle: 

### Ubuntu
Disk_read:  increase of agentd, decrease of logcollector
PSS, RSS, USS: values of agentd, modulesd, syschecd remain stable until the last moment
Read_ops: small decrease of agentd
Agentd_number_of_generated_events: small decrease of generated events

### Centos
PSS: increase of agentd
RSS, USS : increase of agentd
Agent_d_number_of_events_buffered: decrease of number of peaks


### Windows
VMS: decrease of the range of the fluctuation


### Manager
Disk: less number of peaks of wazuh-analysisd
Disk_read: decrease of monitord
EDPS: tiny differences in the pattern


## Logs :black_circle:


<details><summary>Ubuntu</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-15 01:42:54,235 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1696, in cmdline
    with open_text("%s/%s/cmdline" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 725, in open_text
    return open(fname, "rt", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/824183/cmdline'

2024-11-15 13:34:12,006 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
ProcessLookupError: [Errno 3] No such process
```



- Reported: https://github.com/wazuh/wazuh-qa-automation/issues/118 - Not Known issue
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 610, in check_wazuh_processes
    running_processes = [psutil.Process(x.pid) for x in
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 610, in <listcomp>
    running_processes = [psutil.Process(x.pid) for x in
  File "/usr/local/lib/python3.8/dist-packages/jenkins_utils-3.11.0-py3.8.egg/jenkins_utils/monitor.py", line 611, in <lambda>
    filter(lambda x: x.name() in binary_list, psutil.process_iter())]
  File "/usr/local/lib/python3.8/dist-packages/psutil/__init__.py", line 617, in name
    name = self._proc.name()
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1671, in name
    name = self._parse_stat_file()['name']
  File "/usr/local/lib/python3.8/dist-packages/psutil/_pslinux.py", line 1580, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=1759123)
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/14 18:28:26 wazuh-modulesd:ciscat ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'. 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:29:28 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.4.26]:1514/tcp': 'Connection refused'. 
2024/11/14 18:29:29 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
```

- Expected in stress test
```
2024/11/16 00:01:32 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
```
</details>



<details><summary>Centos</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-14 18:31:00,219 Error getting something from a dict
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/jenkins_utils-3.11.0-py3.6.egg/jenkins_utils/monitor.py", line 615, in check_wazuh_processes
    dead_processes.remove(process.name())
KeyError: 'wazuh-modulesd'
 
2024-11-15 04:00:02,573 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

2024-11-15 14:44:34,179 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/2205427/stat'

2024-11-15 14:07:21,458 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1697, in cmdline
    data = f.read()
ProcessLookupError: [Errno 3] No such process
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/3293
```
2024/11/17 00:00:59 wazuh-modulesd:ciscat ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory 
2024/11/17 00:00:59 wazuh-modulesd:ciscat ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml' 
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
2024/11/14 18:29:28 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock. 
2024/11/14 18:29:28 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.4.26]:1514/tcp': 'Connection refused'. 
2024/11/14 18:29:28 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection... 
```

- Expected in stress test
```
2024/11/15 00:30:17 wazuh-agentd WARNING: Agent buffer is full: Events may be lost. 
```
</details>



<details><summary>Windows</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/3293 - Known issue
```
2024/11/15 00:05:49 wazuh-modulesd:ciscat ERROR: Timeout expired executing 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'. 
2024/11/14 18:30:21 wazuh-modulesd:ciscat ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/15 00:05:49 wazuh-modulesd:ciscat WARNING: Interval overtaken. 
```
</details>



<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5588 - Known issue
```
2024-11-15 20:55:32,192 Wazuh process not found
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1618, in _parse_stat_file
    with open_binary("%s/%s/stat" % (self._procfs_path, self.pid)) as f:
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 711, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/3449027/stat'
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1576, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_common.py", line 450, in wrapper
    return fun(self)
  File "/usr/local/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1619, in _parse_stat_file
    data = f.read()
ProcessLookupError: [Errno 3] No such process
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4656 - Known issue
```
2024/11/17 00:00:57 wazuh-modulesd:azure-logs ERROR: azure-activity: Returned error code: '1'. 
```

- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
2024/11/14 18:27:39 indexer-connector WARNING: No username and password found in the keystore, using default values. 
2024/11/14 18:27:39 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-4-26.ec2.internal', retrying until the connection is successful. 
```

- Expected in stress test
```
2024/11/14 18:29:27 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted. 
```

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
2024/11/14 18:29:45 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting... 
```

</details>
