### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-LOGCOLLECTOR (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27007]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/monitor-manager-test_stress_B97_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/plots/test_stress_B97_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/logs/ossec_test_stress_B97_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/data/monitor-manager-test_stress_B97_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/data/test_stress_B97_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/data/test_stress_B97_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/data/test_stress_B97_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/monitor-agent-test_stress_B97_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/test_stress_B97_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/test_stress_B97_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/test_stress_B97_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/plots/test_stress_B97_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/logs/ossec_test_stress_B97_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/data/monitor-agent-test_stress_B97_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_centos/data/test_stress_B97_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/monitor-agent-test_stress_B97_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/test_stress_B97_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/test_stress_B97_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/test_stress_B97_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/plots/test_stress_B97_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/logs/ossec_test_stress_B97_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/data/monitor-agent-test_stress_B97_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_ubuntu/data/test_stress_B97_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/monitor-winagent-test_stress_B97_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/test_stress_B97_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/test_stress_B97_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/test_stress_B97_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/plots/test_stress_B97_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/logs/ossec_test_stress_B97_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/data/monitor-winagent-test_stress_B97_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_agent_windows/data/test_stress_B97_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

### New Issue
- https://github.com/wazuh/wazuh/issues/27083
- https://github.com/wazuh/wazuh/issues/27095

### Known Issues
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/4656
- https://github.com/wazuh/wazuh-jenkins/issues/5284
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/12074
- https://github.com/wazuh/wazuh/issues/18995
- https://github.com/wazuh/wazuh-jenkins/issues/3293

**Comment by DiegoRatto** [comment]
# Analysis report

## Logs :yellow_circle: 

<details><summary>Manager</summary>


- **Expected in Stress Test**
```
2024/11/25 00:00:11 sca WARNING: Interval overtaken.
2024/11/23 04:46:50 wazuh-syscheckd WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.
2024/11/23 04:47:40 wazuh-analysisd WARNING: Syscheck decoder queue is full.
2024/11/23 10:47:11 wazuh-db WARNING: After vacuum, the database '002' has become just as fragmented or worse
2024/11/23 12:47:44 wazuh-analysisd WARNING: Security Configuration Assessment decoder queue is full.
2024/11/22 22:45:02 wazuh-modulesd:content-updater WARNING: The offsets download has been interrupted.
2024/11/22 22:45:25 wazuh-remoted WARNING: Message queue is full (10). Events may be lost.
```

- **Known issue**: https://github.com/wazuh/wazuh/issues/22565
```
2024/11/22 22:43:13 indexer-connector WARNING: No username and password found in the keystore, using default values.
2024/11/22 22:43:13 indexer-connector WARNING: IndexerConnector initialization failed for index 'wazuh-states-vulnerabilities-ip-172-31-14-139.ec2.internal', retrying until the connection is successful.
2024/11/22 22:44:31 indexer-connector WARNING: Failed to sync agent '001' with the indexer.
```

- **Known issue**: https://github.com/wazuh/wazuh-jenkins/issues/4481
```
2024/11/25 00:41:31 wazuh-modulesd:azure-logs ERROR: azure-activity: Returned error code: '1'.
```


- **Known issue**: https://github.com/wazuh/wazuh-jenkins/issues/5284
```
2024/11/22 22:45:26 wazuh-remoted WARNING: Agent key already in use: agent ID '003'
```


- **Known issue**: https://github.com/wazuh/wazuh-jenkins/issues/4469
```
2024/11/22 22:45:20 wazuh-modulesd:ciscat WARNING: No evals defined. Exiting...
```


</details>

<details><summary>Ubuntu</summary>


- Expected in Stress Test
```
2024/11/17 00:00:30 sca WARNING: Interval overtaken.
2024/11/16 00:01:18 wazuh-syscheckd WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.
```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/4867
```
2024/11/14 18:28:33 wazuh-agentd ERROR: Connection socket: Connection reset by peer (104)
2024/11/14 18:28:33 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/14 18:28:33 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.7.81]:1514/tcp': 'Connection refused'.
2024/11/14 18:28:33 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection...
```


- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/4469
```
2024/11/14 18:27:30 wazuh-modulesd:ciscat ERROR: CIS-CAT tool not found at '/var/ossec/wodles/cis-cat'.
```


- Known issue: https://github.com/wazuh/wazuh/issues/20608
```
2024/11/14 18:28:33 wazuh-agentd WARNING: (1218): Unable to send message to 'server': No such file or directory
```


</details>



<details><summary>Centos</summary>

- Expected in Stress Test
```
2024/11/17 00:02:01 sca WARNING: Interval overtaken.
2024/11/16 00:01:20 wazuh-syscheckd WARNING: Real-time inotify kernel queue is full. Some events may be lost. Next scheduled scan will recover lost data.
```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/4469
```
2024/11/17 00:00:18 wazuh-modulesd:ciscat ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
2024/11/17 00:00:18 wazuh-modulesd:ciscat ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml'
```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/4867
```
2024/11/14 18:28:33 wazuh-agentd ERROR: (1137): Lost connection with manager. Setting lock.
2024/11/14 18:28:33 wazuh-agentd ERROR: (1216): Unable to connect to '[172.31.7.81]:1514/tcp': 'Connection refused'.
2024/11/14 18:28:33 wazuh-modulesd WARNING: Process locked due to agent is offline. Waiting for connection...
```


</details>



<details><summary>Windows</summary>

- Expected in Stress Test
```

```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/5287
```

```

- Known issue: https://github.com/wazuh/wazuh/issues/12074
```

```

- Known issue: https://github.com/wazuh/wazuh-jenkins/issues/4469
```

```


- Known issue: https://github.com/wazuh/wazuh/issues/18995
```
```


</details>

## Graphs :black_circle: 

- **Compared with** https://github.com/wazuh/wazuh/issues/26669

### Manager


### CentOS


### Ubuntu



### Windows

**Comment by pro-akim** [comment]
## Review


### Logs
Windows

```
[2024-11-23_05:45:44] [ERROR] (create_delete): files\fimStress.410674 file cannot be deleted.
```

This log is not related to 
- https://github.com/wazuh/wazuh/issues/12074


```
2024/11/23 04:50:34 wazuh-agent WARNING: At get_user(c:\tmp\syscheck_test\files\fimstress.33496): CreateFile(): The system cannot find the file specified. (2)
2024/11/23 05:48:40 wazuh-agent WARNING: (6922): Cannot open 'c:\tmp\syscheck_test\directories\dir1786': No such file or directory
```
These are not related to: https://github.com/wazuh/wazuh/issues/18995

### Plots


Add the following notes:

Manager
CPU: increase of syscheckd
Disk_read: increase of monitord
Read_ops: small increase of modulesd and syscheckd
Queues state: Decrease of the syscheck peaks


CentOS
Modulesd has an increase in the last part of the test of disk use in Disk_written, read_ops, write_ops
> Could be linked to the issue #27083


Ubuntu
VMS: small increase of logcollector
> Write_ops: small increase of modulesd: Could be linked to the issue #27083

**Comment by DiegoRatto** [comment]
The request was corrected 
The 3 errors belonged to the issue https://github.com/wazuh/wazuh-jenkins/issues/5287

Notes were also added to the logs.

**Comment by pro-akim** [comment]
LGTM
