### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - SCA (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27003]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/88/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/monitor-manager-test_stress_B88_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/plots/test_stress_B88_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/logs/ossec_test_stress_B88_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/data/monitor-manager-test_stress_B88_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/data/test_stress_B88_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/data/test_stress_B88_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_manager_centos/data/test_stress_B88_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/monitor-agent-test_stress_B88_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/test_stress_B88_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/test_stress_B88_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/test_stress_B88_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/plots/test_stress_B88_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/logs/ossec_test_stress_B88_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/data/monitor-agent-test_stress_B88_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_centos/data/test_stress_B88_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/monitor-agent-test_stress_B88_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/test_stress_B88_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/test_stress_B88_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/test_stress_B88_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/plots/test_stress_B88_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/logs/ossec_test_stress_B88_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/data/monitor-agent-test_stress_B88_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_ubuntu/data/test_stress_B88_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/monitor-winagent-test_stress_B88_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/test_stress_B88_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/test_stress_B88_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/test_stress_B88_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/plots/test_stress_B88_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/logs/ossec_test_stress_B88_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/data/monitor-winagent-test_stress_B88_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B88-3600m/B88_agent_windows/data/test_stress_B88_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle: 

Compared to https://github.com/wazuh/wazuh/issues/26664

### Logs :yellow_circle: 

Known issues:
 - https://github.com/wazuh/wazuh/issues/22565
 - https://github.com/wazuh/wazuh-jenkins/issues/4867
 - https://github.com/wazuh/wazuh-jenkins/issues/4867

**Comment by jseg380** [comment]
# Analysis report

## Graphs :green_circle:

Compared to https://github.com/wazuh/wazuh/issues/26664

### Manager
Disk_Read: slight increase of wazuh-monitord

### Centos
No abnormalities were found

### Ubuntu
No abnormalities were found

### Windows
No abnormalities were found

**Comment by hossam1522** [comment]
LGTM!
