### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-SCA (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27010]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/100/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/monitor-manager-test_stress_B100_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/plots/test_stress_B100_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/logs/ossec_test_stress_B100_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/data/monitor-manager-test_stress_B100_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/data/test_stress_B100_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/data/test_stress_B100_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_manager_centos/data/test_stress_B100_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/monitor-agent-test_stress_B100_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/test_stress_B100_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/test_stress_B100_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/test_stress_B100_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/plots/test_stress_B100_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/logs/ossec_test_stress_B100_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/data/monitor-agent-test_stress_B100_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_centos/data/test_stress_B100_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/monitor-agent-test_stress_B100_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/test_stress_B100_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/test_stress_B100_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/test_stress_B100_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/plots/test_stress_B100_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/logs/ossec_test_stress_B100_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/data/monitor-agent-test_stress_B100_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_ubuntu/data/test_stress_B100_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/monitor-winagent-test_stress_B100_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/test_stress_B100_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/test_stress_B100_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/test_stress_B100_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/plots/test_stress_B100_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/logs/ossec_test_stress_B100_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/data/monitor-winagent-test_stress_B100_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B100-3600m/B100_agent_windows/data/test_stress_B100_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## New Issue:
- https://github.com/wazuh/wazuh/issues/27081

### Known Issue
- https://github.com/wazuh/wazuh-jenkins/issues/4469
- https://github.com/wazuh/wazuh-jenkins/issues/3293
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/12074
- https://github.com/wazuh/wazuh-jenkins/issues/4656
- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh-jenkins/issues/5284
- https://github.com/wazuh/wazuh-jenkins/issues/4867

**Comment by DiegoRatto** [comment]
# Analysis report :black_circle: 
  
## Graphs :black_circle: 

Compared to: https://github.com/wazuh/wazuh/issues/26662

### Windows


### Manager


### Centos



### Ubuntu


## Logs :black_circle: 


<details><summary>Windows</summary>


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/3293 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5287 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh/issues/12074 - Known issue
```
```


- Expected in stress test
```
```
</details>


<details><summary>Manager</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4656 - Known issue
```
```


- Expected in stress test
```
```


- Reported: https://github.com/wazuh/wazuh/issues/22565 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/3293 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5287 - Known issue
```
```
</details>


<details><summary>Centos</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/3293 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Known issue
```
```


- Expected in stress test
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/5287 - Known issue
```
```
</details>


<details><summary>Ubuntu</summary>

- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4469 - Known issue
```
```


- Reported: https://github.com/wazuh/wazuh-jenkins/issues/4867 - Kwnon issue
```
```


- Expected in stress test
```
```
</details>
