### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-DOCKER,CISCAT,OSQUERY,AZURE (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27013]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress/103/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/monitor-manager-test_stress_B103_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_events_Decoded_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_events_Dropped_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_events_EDPS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_events_Written_stats.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_state_Number_Events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/plots/test_stress_B103_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/logs/ossec_test_stress_B103_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/data/monitor-manager-test_stress_B103_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/data/test_stress_B103_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/data/test_stress_B103_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_manager_centos/data/test_stress_B103_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/monitor-agent-test_stress_B103_centos-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/test_stress_B103_centos_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/test_stress_B103_centos_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/test_stress_B103_centos_agentd_state_AgentD_Number_of_messages.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/plots/test_stress_B103_centos_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/logs/ossec_test_stress_B103_centos_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/data/monitor-agent-test_stress_B103_centos-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_centos/data/test_stress_B103_centos_agentd_state.csv

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/monitor-agent-test_stress_B103_ubuntu-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/test_stress_B103_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/test_stress_B103_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/test_stress_B103_ubuntu_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/plots/test_stress_B103_ubuntu_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/logs/ossec_test_stress_B103_ubuntu_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/data/monitor-agent-test_stress_B103_ubuntu-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_ubuntu/data/test_stress_B103_ubuntu_agentd_state.csv

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Disk.png)	
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Handles.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/monitor-winagent-test_stress_B103_windows-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/test_stress_B103_windows_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/test_stress_B103_windows_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/test_stress_B103_windows_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/plots/test_stress_B103_windows_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/logs/ossec_test_stress_B103_windows_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/data/monitor-winagent-test_stress_B103_windows-pre-release.csv
    https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B103-3600m/B103_agent_windows/data/test_stress_B103_windows_agentd_state.csv

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    

    </details>
+ <details><summary>Logs and configuration</summary>

    

    </details>
+ <details><summary>CSV</summary>

    

    </details>

</details>

## Conclusion :yellow_circle:  

Compared to: https://github.com/wazuh/wazuh/issues/26509

### Logs

Know issues:

- https://github.com/wazuh/wazuh/issues/22565
- https://github.com/wazuh/wazuh/issues/12074
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/18179
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/4867
- https://github.com/wazuh/wazuh-jenkins/issues/5287
- https://github.com/wazuh/wazuh/issues/20608

**Comment by dgamboa1605** [comment]
# Analysis Report :black_circle: 
- Compared with: https://github.com/wazuh/wazuh/issues/25871

## Graphs :black_circle:      

<details>
   <summary>Manager  </summary>
   <br/>



</details>

<details>
   <summary>CentOS </summary>
   <br/>


</details>

<details>
   <summary>Ubuntu Agent  </summary>
   <br/>


</details>

<details>
   <summary>Windows Agent  </summary>
   <br/>


</details>


## Logs :black_circle: 

<details><summary>Windows</summary>

- Expected in Stress Test


</details>



<details><summary>Centos</summary>

- Expected in Stress Test

</details>



<details><summary>Ubuntu</summary>

- Expected in Stress Test


</details>



<details><summary>Manager</summary>

- Expected in Stress Test


</details>

**Comment by joaquinsgi** [comment]
LGTM! But there are some comments to know:
- Plots:
  - There is a decrease of Disk_Read in centOS from` wazuh-modulesd` from 2.5 to 1.5.
