### ISSUE TITLE
Release 4.10.0 - Beta 1 - Footprint Metrics - MACOS-SOLARIS (2.5d)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27017]
Release 4.10.0 - Beta 1 - Footprint Metrics - MACOS-SOLARIS (2.5d)

## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #26970                                       |
| **Main footprint metrics issue #** | #26974                                     |
| **Version** | 4.10.0                                      |
| **Release stage #** | Beta 1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.10.0-beta1 |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://jenkins-staging.qa.wazuh.info/job/test_stress_vagrant/12/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_CPU.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_Disk_Read.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_Disk_Written.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_Disk.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_PSS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_Read_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_SWAP.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_USS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/monitor-manager-test_stress_vagrant_B12_manager-pre-release_Write_Ops.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/test_stress_vagrant_B12_manager_analysisd_state_Number_Events.png)	
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/plots/test_stress_vagrant_B12_manager_analysisd_state_Queues_state.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/logs/ossec_test_stress_vagrant_B12_manager_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/data/monitor-manager-test_stress_vagrant_B12_manager-pre-release.csv
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/data/test_stress_vagrant_B12_manager_analysisd_events.csv
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/data/test_stress_vagrant_B12_manager_analysisd_state.csv
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_manager_centos/data/test_stress_vagrant_B12_manager_remoted_state.csv

    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    </details>
+ <details><summary>Logs and configuration</summary>

    </details>
+ <details><summary>CSV</summary>

    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release_CPU.png)	
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release_RSS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/test_stress_vagrant_B12_macos_agent_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/test_stress_vagrant_B12_macos_agent_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/test_stress_vagrant_B12_macos_agent_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/plots/test_stress_vagrant_B12_macos_agent_agentd_state_AgentD_Status.png)

    </details>

+ <details><summary>Logs and configuration</summary>

    
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/logs/ossec_test_stress_vagrant_B12_macos_agent_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/data/monitor-agent-test_stress_vagrant_B12_macos_agent-pre-release.csv
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_macos/data/test_stress_vagrant_B12_macos_agent_agentd_state.csv

    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release_CPU.png)	
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release_FD.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release_RSS_MAXMIN.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release_RSS.png)	
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release_VMS.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/test_stress_vagrant_B12_solaris_agent_agentd_state_AgentD_Number_of_events_buffered.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/test_stress_vagrant_B12_solaris_agent_agentd_state_AgentD_Number_of_generated_events.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/test_stress_vagrant_B12_solaris_agent_agentd_state_AgentD_Number_of_messages.png)
    ![](https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/plots/test_stress_vagrant_B12_solaris_agent_agentd_state_AgentD_Status.png)

    </details>
+ <details><summary>Logs and configuration</summary>

    
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/logs/ossec_test_stress_vagrant_B12_solaris_agent_2024-11-25.zip

    </details>
+ <details><summary>CSV</summary>

    
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/data/monitor-agent-test_stress_vagrant_B12_solaris_agent-pre-release.csv
    https://ci.wazuh.com/data/test_stress_vagrant/pre-release/4.10.0/B12-3600m/B12_agent_solaris/data/test_stress_vagrant_B12_solaris_agent_agentd_state.csv

    </details>

</details>

## Conclusion :yellow_circle: 
**Known Issues:**
-  [Connection error during registration in stress tests](https://github.com/wazuh/wazuh-jenkins/issues/4867)
-  [FIM doesn't find ossec.log during Footprint test](https://github.com/wazuh/wazuh-jenkins/issues/5538)
- [Vulnerability Detector module is enabled at the start of the stress test](https://github.com/wazuh/wazuh/issues/22565)
- [Remove CIS-CAT from the stress test](https://github.com/wazuh/wazuh-jenkins/issues/4469) 
- [The wazuh-moduled shows the error azure-activity return error code: '1']( https://github.com/wazuh/wazuh-jenkins/issues/4656)

**Comment by DiegoRatto** [comment]
# Analysis report :black_circle: 
 
## Graphs :black_circle:  

<details><summary>Manager</summary>

</details>


<details><summary>macOS</summary>

</details>


<details><summary>Solaris</summary>

</details>


## Logs :black_circle:

<details><summary>macOS</summary>

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4867
```
```


- Reported in https://github.com/wazuh/wazuh-jenkins/issues/5538 
```
```
</details>


<details><summary>Manager</summary>

- Expected in stress test
```
```

- Reported in https://github.com/wazuh/wazuh/issues/25222

```
```


- Reported in: https://github.com/wazuh/wazuh/issues/22565
```
```


- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4469 
```
```

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4656
```
```
</details>


<details><summary>Solaris</summary>

- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4867 
```
```


- Reported in https://github.com/wazuh/wazuh-jenkins/issues/4469
```
```
</details>

**Comment by DiegoRatto** [comment]
The request is corrected

**Comment by joaquinsgi** [comment]
LGTM!
