### ISSUE TITLE
Vulnerability scanner module shows errors related to openSUSE Tumbleweed

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#27042]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.10.0-alpha1| Vulnerability scanner module | Manager| Packages | openSUSE Tumbleweed amd64|

# Description

During https://github.com/wazuh/wazuh/issues/26976, specifically on openSUSE upgrade test, it was found that Wazuh Manager contains several error messages on `ossec.log` showing the following message

```
2024/11/22 22:46:21 wazuh-modulesd:vulnerability-scanner: ERROR: Error message: Couldn't find column family: 'descriptions_suse'
```

## Details
- Both Manager and Agent are openSUSE Tumbleweed
- Jenkins Job: https://jenkins-staging.qa.wazuh.info/job/test_upgrade/213/ 
- Jenkins manager's log: [test_upgrade_manager_log_B213.txt](https://github.com/user-attachments/files/17906902/test_upgrade_manager_log_B213.txt)
- This errors exist on both 4.8.2 to 4.10.0 and 4.9.2 to 4.10.0 upgrades

**Comment by sebasfalcone** [comment]
## Pre-analysis
Description mapping is not correctly defined ([see mapping](https://github.com/wazuh/intelligence-data/blob/4c2787a0e7bb0cc460f7e64b42a7248b252652af/base-rules/feed-global.json#L89-L93))

It should be suse_server_15 for OpenSuse ([see mapping](https://github.com/wazuh/intelligence-data/blob/4c2787a0e7bb0cc460f7e64b42a7248b252652af/base-rules/cna-mapping-global.json#L8))

**Comment by Dwordcito** [comment]
Operational, we need to change feed mappings.
