### ISSUE TITLE
Investigate error in `test_cluster_error_logs`

### ISSUE THREAD

**Issue by javiersanchz** [wazuh/wazuh#27050]
## Description

During the launch of `Workload benchmarks metrics for 4.10.0 - Beta 1` (https://github.com/wazuh/wazuh/issues/26995), the `test_cluster_error_logs` produced the following error:

```console
2024/11/25 12:59:47 ERROR: [Master] [D API] Error executing API request locally: 'SecurityError' object is not subscriptable
TypeError: 'SecurityError' object is not subscriptable
TypeError: 'SecurityError' object is not subscriptable
2024/11/25 12:59:48 ERROR: [Master] [D API] Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
```
```console
E       assert not {'master': [b"2024/11/25 12:59:47 ERROR: [Master] [D API] Error executing API request locally: 'SecurityError' object ...trics_B798_manager_22] [Main] Connection closed due to an unhandled error: [Errno 104] Connection reset by peer'], ...}
```

The error comes from an object of type `SecurityError`

Artifacts : [artifacts.zip](https://github.com/user-attachments/files/17916908/artifacts.zip)

**Comment by javiersanchz** [comment]
## Update

- I was looking at the artifacts generated by master and investigating the cause of the error within the master `api.log` file.
- I was reviewing the part of the code where the failure occurs and looking into the possible reason.

**Comment by javiersanchz** [comment]
## Update

It was further investigated regarding the error within the files generated by `master` in the artifacts.

Within the master `api.log`, we can find the error that occurred:

```console
2024/11/25 12:59:47 ERROR: [Master] [D API] Error executing API request locally: 'SecurityError' object is not subscriptable
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 239, in run_local
    data = f(**f_kwargs)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/preprocessor.py", line 177, in get_permissions
    roles = get_roles(auth_context=auth_context, user_id=user_id)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/preprocessor.py", line 142, in get_roles
    rbac = RBAChecker(auth_context=auth_context, user_id=user_id)
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/rbac/auth_context.py", line 70, in __init__
    for rule in rm.get_role_id(role_id=role['id'])['rules']:
TypeError: 'SecurityError' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.10/site-packages/wazuh/core/cluster/dapi/dapi.py", line 285, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
TypeError: 'SecurityError' object is not subscriptable
```

The error arises because a `SecurityError` object is being received and handled in:


```console
for rule in rm.get_role_id(role_id=role['id'])['rules']:
    rules.append(rum.get_rule(rule))
```

which is not subscriptable, meaning it cannot be treated as a dictionary. However, the code assumes that the result of `get_role_id` will always have a `['rules']` key, which causes the error:

`TypeError: 'SecurityError' object is not subscriptable
`

This originates from the method:

https://github.com/wazuh/wazuh/blob/286c3c6464e6b960c59b891f706a4300d52c4d04/framework/wazuh/rbac/auth_context.py#L65-L76


The problem arises because the `get_role_id` method does not guarantee that it will always return a dictionary with the expected format. Instead, it could return:

- A dictionary with the role information (as expected).
- A SecurityError object indicating that the role does not exist.

https://github.com/wazuh/wazuh/blob/286c3c6464e6b960c59b891f706a4300d52c4d04/framework/wazuh/rbac/orm.py#L1114-L1133


To resolve this issue, the response from `get_role_id` should be validated before attempting to access its keys `(['rules'])`, or the exception should be handled in the return of `get_role_id`

**Comment by javiersanchz** [comment]
## Update

Initially, I decided to add a `try` block inside the handling of `get_role_id` to avoid the issues that arose:

```console
        with orm.RolesManager() as rm:
            with orm.RulesManager() as rum:
                processed_roles_list = list()
                for role in roles_list:
                    try:
                        role_data = rm.get_role_id(role_id=role['id'])
                        rules = list()
                        for rule in role_data.get('rules', []):
                            rules.append(rum.get_rule(rule))
                        if len(rules) > 0:
                            processed_roles_list.append(role)
                            processed_roles_list[-1]['rules'] = rules
                    except ValueError as e:
                        logger.error(f"Skipping role with ID {role['id']} due to error: {e}")
                        continue
```
But I saw that this was not the solution and continued with the investigation

An attempt was also made to reproduce the error that occurred, but it was not successful.

Continuing with the investigation, the reason this error occurs is because a `SecurityError.ROLE_NOT_EXIST` is returned : 

https://github.com/wazuh/wazuh/blob/286c3c6464e6b960c59b891f706a4300d52c4d04/framework/wazuh/rbac/orm.py#L63-L64

It indicates that the role does not exist in the database.

On the other hand, I was reviewing the `api.log` of the `master` and found the error: 

```console
2024/11/25 12:59:47 INFO: wazuh 172.31.37.78 "PUT /manager/restart" with parameters {} and body {} done in 0.048s: 200
2024/11/25 12:59:51 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 12:59:51 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.004s: 500
2024/11/25 12:59:51 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 12:59:51 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.003s: 500
2024/11/25 12:59:51 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 12:59:51 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.003s: 500
2024/11/25 13:00:17 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 13:00:17 INFO: wazuh 172.31.37.78 "GET /" with parameters {} and body {} done in 0.003s: 500
2024/11/25 13:00:22 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
...
2024/11/25 13:00:48 INFO: wazuh 172.31.37.78 "GET /" with parameters {} and body {} done in 0.003s: 500
2024/11/25 13:00:53 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 13:00:53 INFO: wazuh 172.31.37.78 "GET /" with parameters {} and body {} done in 0.004s: 500
2024/11/25 13:00:53 INFO: Shutdown wazuh-apid server.
2024/11/25 13:00:55 INFO: Checking RBAC database integrity...
2024/11/25 13:00:55 INFO: /var/ossec/api/configuration/security/rbac.db file was detected
2024/11/25 13:00:55 INFO: RBAC database integrity check finished successfully
```

Since the manager was restarted:
```console
2024/11/25 12:59:47 INFO: wazuh 172.31.37.78 "PUT /manager/restart" with parameters {} and body {} done in 0.048s: 200
```

Until it is confirmed that the `RBAC database` integrity check was successfully completed, `1 minute and 8 seconds` pass : 

```console
2024/11/25 13:00:55 INFO: RBAC database integrity check finished successfully
```

And yet, even after that, we can find more logs about errors in the master and requests with a `500` response:

```console
2024/11/25 13:00:59 INFO: Getting installation UID...
2024/11/25 13:00:59 INFO: Getting updates information...
2024/11/25 13:01:03 ERROR: Some Wazuh daemons are not ready yet in node "master" (wazuh-modulesd->restarting, wazuh-analysisd->restarting, wazuh-execd->restarting, wazuh-db->restarting, wazuh-remoted->restarting)
2024/11/25 13:01:03 INFO: wazuh 172.31.37.78 "GET /" with parameters {} and body {} done in 0.017s: 500
2024/11/25 13:01:10 INFO: wazuh 172.31.37.78 "GET /" with parameters {} and body {} done in 2.369s: 200
```

Therefore, when accessing the database to obtain the `role_id` from `get_role_id`, the database requests or other internal system resources might not have been processed yet or may not have been processed correctly, leading to that error.

All of this seems to be due to the high amount of resources used by the master in the testing environment, leading to a long restart time for the manager and malfunctioning of the environment. An issue has already been opened for this: https://github.com/wazuh/wazuh/issues/27058 to investigate it.

- Therefore, this issue can be considered resolved

**Comment by RamosFe** [comment]
## Review

The analysis was as expected and the comments in the Issue justify the reasons for the error as well as its causes.

Great job! LGTM!

**Comment by fdalmaup** [comment]
# Review

Checking the files from where the error arose and comparing them in the `v4.10.0-beta1` and the `v4.9.2` versions, we can verify that no changes were introduced to them. As correctly pointed out, the error arose because the requests were carried out before the API finished the RBAC database integrity check as expected.

This is strictly related to the testing environment and not the codebase itself.

LGTM.
