### ISSUE TITLE
Alert not triggered

### ISSUE THREAD

**Issue by Fede2602** [wazuh/wazuh#27070]
Hi all, I added to the local_rules.xml file this rule to create alerts when a powershell is opened on an agent:
```
<rule id="100006" level="7">
    <decoded_as>windows_eventchannel</decoded_as>
    <field name="win.system.eventID">40961</field>
    <field name="providerName">Microsoft-Windows-PowerShell</field>
    <description>Windows eventID 40961 - PowerShell console is starting up</description>
</rule>
```

I also wrote a decoder in the local_decoder.xml file:
```
<decoder name="windows_eventchannel">
    <program_name>EventChannel</program_name>
    <type>windows</type>
</decoder>
```

The log received from the server is in json format and is this:
```
{
  "_index": "wazuh-archives-4.x-2024.11.26",
  "_id": "o8D3Z5MBYcTU8jMXyRJs",
  "_version": 1,
  "_score": null,
  "_source": {
    "agent": {
      "ip": "10.10.10.67",
      "name": "DESKTOP-GB3H72T",
      "id": "002"
    },
    "manager": {
      "name": "wazuh-server"
    },
    "data": {
      "win": {
        "system": {
          "eventID": "40961",
          "keywords": "0x0",
          "providerGuid": "{a0c1853b-5c40-4b15-8766-3cf1c58f985a}",
          "level": "4",
          "channel": "Microsoft-Windows-PowerShell/Operational",
          "opcode": "1",
          "message": "\"Avvio della console di PowerShell\"",
          "version": "1",
          "systemTime": "2024-11-26T10:15:07.6703595Z",
          "eventRecordID": "404",
          "threadID": "7592",
          "computer": "DESKTOP-GB3H72T",
          "task": "4",
          "processID": "1560",
          "severityValue": "INFORMATION",
          "providerName": "Microsoft-Windows-PowerShell"
        }
      }
    },
    "decoder": {
      "name": "windows_eventchannel"
    },
    "full_log": "{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-PowerShell\",\"providerGuid\":\"{a0c1853b-5c40-4b15-8766-3cf1c58f985a}\",\"eventID\":\"40961\",\"version\":\"1\",\"level\":\"4\",\"task\":\"4\",\"opcode\":\"1\",\"keywords\":\"0x0\",\"systemTime\":\"2024-11-26T10:15:07.6703595Z\",\"eventRecordID\":\"404\",\"processID\":\"1560\",\"threadID\":\"7592\",\"channel\":\"Microsoft-Windows-PowerShell/Operational\",\"computer\":\"DESKTOP-GB3H72T\",\"severityValue\":\"INFORMATION\",\"message\":\"\\\"Avvio della console di PowerShell\\\"\"}}}",
    "input": {
      "type": "log"
    },
    "@timestamp": "2024-11-26T10:15:08.690Z",
    "location": "EventChannel",
    "id": "1732616108.402621",
    "timestamp": "2024-11-26T10:15:08.690+0000"
  },
  "fields": {
    "@timestamp": [
      "2024-11-26T10:15:08.690Z"
    ],
    "timestamp": [
      "2024-11-26T10:15:08.690Z"
    ]
  },
  "highlight": {
    "data.win.system.eventID": [
      "@opensearch-dashboards-highlighted-field@40961@/opensearch-dashboards-highlighted-field@"
    ]
  },
  "sort": [
    1732616108690
  ]
}
```

The ossec.conf file on the agent contains the code:
```
<localfile>
    <location>Microsoft-Windows-PowerShell/Operational</location>
    <log_format>eventchannel</log_format>
</localfile>
```

Is shown on the dashboard with wazuh-archives-* when I activate logall_json in the ossec.conf file, but since it is not recognized by the rule I wrote it is discarded and no alert is generated.
I don't understand where the error is, could someone help me?

Thanks.

**Comment by jftuduri** [comment]
Hello @Fede2602 !

There are a couple of things you should adjust for the rule to work correctly.

First, the custom decoder isn't necessary, so you can go ahead and remove it.

Second, the event you shared, without any custom rule applied, matches rule `60009` ("Windows informational event"). To achieve the specific match you want, you can create a child rule of 60009 using the [if_sid](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#if-sid) tag.

Your new rule could look like this:

```
<rule id="100006" level="7">
    <if_sid>60009</if_sid>
    <field name="win.system.eventID">^40961$</field>
    <field name="win.system.providerName">Microsoft-Windows-PowerShell</field>
    <description>Windows eventID 40961 - PowerShell console is starting up</des>
</rule>
```

A couple of points to note:
- I surrounded the `eventID` with `^` and `$` to ensure it matches the number exactly. You can see [this documentation](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html) for more info.
- For `providerName`, we need to use the full name of the decoded field, which in this case is `win.system.providerName`.
    
Please try this new rule and let me know if you encounter any issues. Also, remember to restart the manager after updating the ruleset.

Regards!

**Comment by Fede2602** [comment]
Thank you it works now.
Just one question, why in the if_sid field I should not put the value 61600 which is the id for the rule with:
win.system.severityValue = ^INFORMATION$

**Comment by Fede2602** [comment]
Now it is more clear to me, thank you very much!

**Comment by Damian-Mangold** [comment]
Reviewed. 

Status of the user's query: resolved.
