### ISSUE TITLE
Preventing Duplicate Alerts in Wazuh Rule Engine Based on Parameter Consistency

### ISSUE THREAD

**Issue by zaneef** [wazuh/wazuh#27075]
Hi there,
I need assistance with configuring the Wazuh rule engine to avoid generating repetitive alerts when a specific parameter remains unchanged.

Scenario:
- **Issue:** one of my agents is consistently triggering rule every time a user logs into the machine (obviously).
- **Objective:** i want to log only the first 10 occurrences of this event. After reaching 10 alerts, subsequent logins by the same user should not trigger additional alerts.

For example, an agent of mine is triggering the rule `60106` every time an user is logged in the machine. I would like to log only the first 10 occurrences and, after those, stop triggering the rule if the logged user is the same of the previous ones.

I tried overriding the existing rule with the following configuration but it isn't functioning as expected because the modification of the `if_sid` tag is being ignored. According to the Wazuh documentation, https://documentation.wazuh.com/current/user-manual/ruleset/rules/custom.html#changing-existing-rules, changes to certain tags like `if_sid` may not be supported while trying to override a rule.

```
<rule id="60106" level="3" frequency="5" timeframe="2" ignore="120" overwrite="yes">
    <if_matched_sid>60103</if_matched_sid>
    <same_field>win.eventdata.workstationName</same_field>
    <field name="win.system.eventID">^528$|^540$|^673$|^4624$|^4769$</field>
    <description>Windows Logon Success</description>
    <options>no_full_log</options>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
    <mitre>
      <id>T1078</id>
    </mitre>
  </rule>
```

I already tried to create a new rule which will trigger after 10 successfully logins with the `frequency` and the `ignore` keywords but it doesn't seems to be working. If the documentation is clear, the `ignore` clause will prevent the new rule to be triggered for 3600 seconds, not the original rule (rule `100289` will not be triggered but I want to suppress rule `60106`).

```
<rule id="100289" level="5" frequency="10" timeframe="3600" ignore="3600">
    <if_matched_sid>60103</if_matched_sid>
    <same_field>win.eventdata.TargetUserName</same_field>
    <field name="win.system.eventID">528|540|673|4624|4769</field>
    <description>Windows Logon Success - Suppressed after 10 occurrences per user</description>
    <options>no_full_log</options>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3</group>
    <mitre>
        <id>T1078</id>
    </mitre>
</rule>
```

Is it possible to configure the Wazuh rule engine to limit the number of alerts generated for the same event parameter (e.g., the same logged-in user)? specifically, I want to:
1. log ony the first 10 occurrences of rule `60106` for a particular user
2. suppress further alerts for that user after the initial 10 to prevent alert flooding in the dashboard

Implementing such a mechanism would help in controlling and preventing excessive alerts, making it easier to manage and respond to significant events without being overwhelmed by repetitive notifications.

Thank you for your assistance!

**Comment by zaneef** [comment]
Hi @juliancnn,
I implemented the rule you suggested for the "Windows application error event" with ID `60602`, but it's not working as expected. Here’s the rule I applied:

```
<rule id="101505" level="8" frequency="5" timeframe="120">
      <if_matched_sid>60602</if_matched_sid>
      <same_field>win.system.message</same_field>
      <same_field>win.system.providerName</same_field>
      <description>Windows application error event - Anti Flooding</description>
      <options>no_full_log</options>
      <group>gdpr_IV_35.7.d,gpg13_4.3,system_error,</group>
</rule>
```

In the threat hunting dashboard, I noticed that after rule `60602` triggers five times, rule `101505` is correctly executed. However, subsequent alerts for rule `60602` are not being suppressed, which was the issue I intended to resolve.

Here’s a screenshot for reference:

![image (1)](https://github.com/user-attachments/assets/04cbb1fc-243f-4e7b-8c64-4ddc997b6573)

After reviewing the documentation, it seems that the `timeframe` option allows detecting when a specific rule is triggered a fixed number of times within a maximum timeframe, at which point the custom rule is executed.
However, this behavior does not align with what I was aiming to achieve, which is:
- Count the number of times a rule is triggered.
- After reaching the threshold, continue producing the custom rule for all subsequent occurrences (within the same timeframe).

Instead, the system appears to execute the custom rule only once within the timeframe and does not suppress further occurrences of the original rule. This explains why, even though the custom rule `101505` is triggered correctly after the threshold is reached, subsequent alerts for rule `60602` are not being suppressed as intended.

Is there a way to configure this logic to work as described?

Thank you in advance!

**Comment by juliancnn** [comment]
I now understand the problem and have been able to replicate it. The problem here is that when the alert is generated the past events are part of the alert that has the if_matched_sid option and it is not possible to store the state that the alert was triggered. Actually it is not possible to keep that status, wazuh-analisysd does not have that functionality.
I tried to make a child rule for this (which I share below), but it fails so I will mark this issue as a bug to analyze it in the future.

```xml
<!-- Example -->
<group name="local,syslog,sshd,">

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <rule id="100001" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>


<rule id="100002" level="8" frequency="5" timeframe="120">
      <if_matched_sid>100001</if_matched_sid>
      <description>Windows application error event - Anti Flooding</description>
      <group>gdpr_IV_35.7.d,gpg13_4.3,system_error,</group>
</rule>


<rule id="100003" level="1" frequency="2" timeframe="120">
      <if_matched_sid>100002</if_matched_sid>
      <if_sid>100001</if_sid>
      <description>Windows application error event - Anti Flooding</description>
      <group>gdpr_IV_35.7.d,gpg13_4.3,system_error,</group>
</rule>

</group>
```

Thanks for sharing this use case, we will come back to analyze this issue when we improve the rule correlation.

**Comment by JcabreraC** [comment]
As @juliancnn has pointed out, this use case is currently not feasible with `wazuh-analysisd` due to its limitations.

However, we will keep this use case in mind as we develop the new engine planned for version 5.0.0.

I am closing this issue now, but please feel free to reopen it if you have any further questions or concerns. Thank you for your feedback and contribution.
