### ISSUE TITLE
Increase of the fluctuation range of RSS in Windows Agent

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#27089]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd  | Packages | 

 

## Description
During the analysis of [VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/26999), it has been found an increase in Windows of the range of fluctuation (RSS Max and Min) to 4.9.2-rc1 and 4.10.0-alpha2 (in alpha3 the test was skipped) version 

RSS_MAXMIN: Increase of the distance between max and min values
RSS: increase of the fluctuation range as observed in RSS_MAXMIN
At the same time in:
USS: decrease of the general level of agent.exe

- 4.10.0-beta1
![image](https://github.com/user-attachments/assets/1c5d0c56-a9a9-422b-a0f4-ed3cfefaef31)
![image](https://github.com/user-attachments/assets/08ee08b4-28fb-47ed-944d-0e810591286a)

- 4.9.2-rc1
![image](https://github.com/user-attachments/assets/c45c92f7-5835-46ed-a560-d3953aa16230)
![image](https://github.com/user-attachments/assets/c7785e3f-970a-4642-9657-d279644923bd)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

2. Check the test and plots

### Current result
Increase of the range of fluctuation of RSS.

### Expected result
A similar behavior with 4.9.2-rc1 plot, unless it is expected that behavior.

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

- Logs: 

  - 4.10.0-beta1
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B91-3600m/B91_agent_windows/logs/ossec_test_stress_B91_windows_2024-11-25.zip

  - 4.9.2-rc1
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5701-3600m/B5701_agent_windows/logs/ossec_Test_stress_B5701_windows_2024-10-31.zip

**Comment by vikman90** [comment]
||[4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26661)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/26999)|Difference|
|---|--:|--:|--:|
|CPU Time (s)|3.00|1.63|45.58 % ⬇️ |
|CPU Average (%)|0.01|0.00|45.61 % ⬇️ |
|CPU Max (%)|12.10|9.10|24.79 % ⬇️ |
|RSS Average (MB)|19.50|19.52|0.07 % ⬆️ |
|RSS Max (MB)|19.98|20.63|3.24 % ⬆️ |
|FD Average|395.95|400.08|1.04 % ⬆️ |
|FD Max|433.00|435.00|0.46 % ⬆️ |
|Read Ops Average (M)|0.00|0.00|🟰 |
|Read Ops Max (M)|0.02|0.02|🟰 |
|Write Ops Average (M)|0.00|0.00|🟰 |
|Write Ops Max (M)|0.02|0.02|🟰 |
|Disk Read Average (MB)|16.81|16.71|0.63 % ⬇️ |
|Disk Read Max (MB)|21.15|23.27|10.05 % ⬆️ |
|Disk Write Average (MB)|1.41|1.44|2.24 % ⬆️ |
|Disk Write Max (MB)|8.83|8.99|1.91 % ⬆️ |

Despite more fluctuations, the average and ceiling of memory usage are mostly maintained.

They can be explained by increased activity or memory fragmentation.
