### ISSUE TITLE
Comms API - Enhance logging for debugging 

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27088]
# Description

During our tests of the 5.0 MVP, we found that the current logging of the Comms API does not provide enough detail to analyze the requests being made making it difficult to determine what could be failing in it or being received by it.
Examples of successful and failed requests:
```
2024/11/27 14:47:06 INFO: (c2804aa2-ffd7-4be2-bdd2-3a0778d78bf8) "POST /api/v1/events/stateful" with parameters {} and body {} done in 0.007s: 400
```

```
2024/11/27 15:21:09 INFO: (c2804aa2-ffd7-4be2-bdd2-3a0778d78bf8) "POST /api/v1/events/stateless" with parameters {} and body {} done in 0.108s: 204
2024/11/27 15:21:41 INFO: (c2804aa2-ffd7-4be2-bdd2-3a0778d78bf8) "GET /api/v1/commands" with parameters {} and body {} done in 30.019s: 408
2024/11/27 15:21:47 INFO: (c2804aa2-ffd7-4be2-bdd2-3a0778d78bf8) "POST /api/v1/events/stateless" with parameters {} and body {} done in 0.082s: 204
```

We need to modify the current logging level to provide the maximum level of detail for MVP testing and debugging.

**Comment by GGP1** [comment]
## Update

Implemented the changes necessary, added unit tests and tested the changes in a development environment.
