### ISSUE TITLE
Relevant increase of modulesd in Centos VMS Plot

### ISSUE THREAD

**Issue by dgamboa1605** [wazuh/wazuh#27081]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd  | Packages | 

 

## Description
During the tests and analysis of [Release 4.10.0 - Beta 1 - Footprint Metrics - LOGCOLLECTOR,SYSCHECK (2.5d) ](https://github.com/wazuh/wazuh/issues/27016), we discover a relevant increase of modulesd in Centos vms plot in comparison with 4.92-rc1 version

### VMS

- 4.10.0-beta1
![image](https://github.com/user-attachments/assets/2487771b-ede7-4d6c-b749-ebbdf2718174)

- 4.9.2-rc1
![image](https://github.com/user-attachments/assets/1ca1cb21-decb-4347-be8a-673b1e4283ac)

### RSS

- 4.10.0-beta1
![image](https://github.com/user-attachments/assets/578c6cbb-61af-4c2c-838f-48bcc9e38742)

- 4.9.2-rc1
![image](https://github.com/user-attachments/assets/26591c44-f4cb-4ded-83a6-f362e216b7bd)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 250 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/94/parameters/

2. Check the test and plots

### Current result
A relevant increase of modulesd in Centos VMS plot

### Expected result
Similar behavior with 4.9.2-rc1 plot should be displayed in modulesd for Centos VMS plot

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/94/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/94/parameters/

- Logs: 

  - 4.10.0-beta1
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B94-3600m/B94_agent_centos/logs/ossec_test_stress_B94_centos_2024-11-25.zip

  - 4.9.2-rc1
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5704-3600m/B5704_agent_centos/logs/ossec_Test_stress_B5704_centos_2024-10-31.zip

**Comment by vikman90** [comment]
||[4.9.2 RC 1](https://github.com/wazuh/wazuh/issues/26667)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27016)|Difference|
|---|--:|--:|--:|
|CPU Time (s)|2.79|3.19|14.34 % ⬆️ |
|CPU Average (%)|0.01|0.01|14.40 % ⬆️ |
|CPU Max (%)|2.00|2.00|🟰 |
|RSS Average (MB)|6.85|4.30|37.17 % ⬇️ |
|RSS Max (MB)|8.82|6.80|22.94 % ⬇️ |
|FD Average|8.00|8.00|🟰 |
|FD Max|8.00|8.00|🟰 |

Even though we see VMS going up, RSS (used memory) has actually gone down.

We can ignore VMS.

**Comment by DiegoRatto** [comment]
:warning: This issue could be related to what was detected in [Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-SCA (2.5d)](https://github.com/wazuh/wazuh/issues/27010)

> [PSS, RSS, USS: small increase of modulesd](https://github.com/wazuh/wazuh/issues/27010#issuecomment-2501652806)

Consistent increase of RSS in CentOS agentd
![image](https://github.com/user-attachments/assets/a271b99e-ba07-4762-9463-f5eb78692563)
![image](https://github.com/user-attachments/assets/dda9ebf0-26c3-4a1f-a511-26b1193e7d4b)
