### ISSUE TITLE
Relevant increase of modulesd in Ubuntu Disk_written Plot

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh#27083]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  wazuh-modulesd  | Packages | 

## Description
During the tests and analysis of [Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-LOGCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/27007), we discover a relevant increase of modulesd in Ubuntu Disk_written Plot in comparison with 4.9.2 - rc 1 version

- **4.10.0-beta1**
![image](https://github.com/user-attachments/assets/721279f4-ae2b-4889-8341-a97abc1cdaa4)

- **4.9.2-rc1**
![image](https://github.com/user-attachments/assets/fad89f40-c14d-4119-b469-732b666b6215)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 250 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build:  https://jenkins-staging.qa.wazuh.info/job/test_stress/97/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/parameters/

2. Check the test and plots

### Current result
A relevant increase of modulesd in Ubuntu Disk_written Plot

### Expected result
Similar behavior with 4.9.2-rc1 plot should be displayed in modulesd for Ubuntu Disk_written Plot

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/
- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/parameters/

- Logs: 

  - **4.10.0-beta1**
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5706-3600m/B5706_agent_ubuntu/logs/ossec_Test_stress_B5706_ubuntu_2024-10-31.zip

  - **4.9.2-rc1**
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5706-3600m/B5706_agent_ubuntu/logs/ossec_Test_stress_B5706_ubuntu_2024-10-31.zip

**Comment by vikman90** [comment]
||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26669)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26890)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27007)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|3577.42|3255.98|5357.20|49.75 % ⬆️ |
|CPU Average (%)|9.23|8.39|13.82|49.71 % ⬆️ |
|CPU Max (%)|99.90|99.50|105.40|5.51 % ⬆️ |
|RSS Average (MB)|60.04|65.94|60.66|1.04 % ⬆️ |
|RSS Max (MB)|63.48|68.63|62.96|0.81 % ⬇️ |
|FD Average|21.18|22.18|21.21|0.13 % ⬆️ |
|FD Max|24.00|25.00|24.00|🟰 |
|Read Ops Average (M)|36.85|36.79|39.70|7.71 % ⬆️ |
|Read Ops Max (M)|49.55|49.62|83.36|68.24 % ⬆️ |
|Write Ops Average (M)|3.13|3.09|3.32|5.85 % ⬆️ |
|Write Ops Max (M)|4.41|4.37|7.00|58.73 % ⬆️ |
|Disk Read Average (MB)|27.67|8.49|8.68|68.64 % ⬇️ |
|Disk Read Max (MB)|51.10|13.26|14.42|71.78 % ⬇️ |
|Disk Write Average (MB)|8193.58|8072.26|8700.95|6.19 % ⬆️ |
|Disk Write Max (MB)|11201.15|11094.92|18407.46|64.34 % ⬆️ |

**Comment by DiegoRatto** [comment]
## Adittional Note

This increase has also been observed in Write_ops

![image](https://github.com/user-attachments/assets/dc997d31-535d-4500-b0f4-5629fa152fa8)

**Comment by vikman90** [comment]
## Analysis

### All Except Logcollector

#### Ubuntu Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26669)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26890)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27007)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|3577.42|3255.98|5357.20|49.75 % 🔼 |
|CPU Average (%)|9.23|8.39|13.82|49.71 % 🔼 |
|CPU Max (%)|99.90|99.50|105.40|5.51 % 🔼 |
|RSS Average (MB)|60.04|65.94|60.66|1.04 % 🔼 |
|RSS Max (MB)|63.48|68.63|62.96|0.81 % 🔽 |
|FD Average|21.18|22.18|21.21|0.13 % 🔼 |
|FD Max|24.00|25.00|24.00|🟰 |
|Read Ops Average (M)|36.85|36.79|39.70|7.71 % 🔼 |
|Read Ops Max (M)|49.55|49.62|83.36|68.24 % 🔼 |
|Write Ops Average (M)|3.13|3.09|3.32|5.85 % 🔼 |
|Write Ops Max (M)|4.41|4.37|7.00|58.73 % 🔼 |
|Disk Read Average (MB)|27.67|8.49|8.68|68.64 % 🔽 |
|Disk Read Max (MB)|51.10|13.26|14.42|71.78 % 🔽 |
|Disk Write Average (MB)|8193.58|8072.26|8700.95|6.19 % 🔼 |
|**Disk Write Max** (MB)|11201.15|11094.92|18407.46|64.34 % 🔼 ⚠️  |

#### CentOS Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26669)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26890)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27007)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|3236.33|3171.39|7018.19|116.86 % 🔼 |
|CPU Average (%)|8.21|8.04|17.80|116.86 % 🔼 |
|CPU Max (%)|97.60|101.20|105.70|8.30 % 🔼 |
|RSS Average (MB)|71.87|71.02|72.79|1.28 % 🔼 |
|RSS Max (MB)|75.64|75.42|76.71|1.41 % 🔼 |
|FD Average|21.15|21.13|21.19|0.18 % 🔼 |
|FD Max|23.00|24.00|24.00|4.35 % 🔼 |
|Read Ops Average (M)|352.90|316.25|353.97|0.30 % 🔼 |
|Read Ops Max (M)|555.49|478.17|827.42|48.95 % 🔼 |
|Write Ops Average (M)|6.17|4.55|5.07|17.87 % 🔽 |
|Write Ops Max (M)|9.61|6.99|11.78|22.53 % 🔼 |
|Disk Read Average (MB)|146.25|102.34|90.07|38.42 % 🔽 |
|Disk Read Max (MB)|303.12|194.59|168.49|44.41 % 🔽 |
|Disk Write Average (MB)|16435.98|13038.66|14092.43|14.26 % 🔽 |
|Disk Write Max (MB)|25623.18|19933.05|28883.57|12.72 % 🔼 |

### SCA

#### Ubuntu Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26664)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26883)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27003)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|7861.27|6488.56|6790.52|13.62 % 🔽 |
|CPU Average (%)|20.10|16.57|17.36|13.62 % 🔽 |
|CPU Max (%)|101.80|101.90|103.10|1.28 % 🔼 |
|RSS Average (MB)|60.58|62.20|57.55|5.00 % 🔽 |
|RSS Max (MB)|60.82|62.78|58.32|4.11 % 🔽 |
|FD Average|11.08|11.07|11.07|0.10 % 🔽 |
|FD Max|13.00|13.00|13.00|🟰 |
|Read Ops Average (M)|68.48|65.98|66.87|2.35 % 🔽 |
|Read Ops Max (M)|141.48|124.84|127.84|9.65 % 🔽 |
|Write Ops Average (M)|4.18|3.92|3.99|4.43 % 🔽 |
|Write Ops Max (M)|9.28|7.85|8.08|12.91 % 🔽 |
|Disk Read Average (MB)|3.34|3.50|3.50|5.04 % 🔼 |
|Disk Read Max (MB)|3.34|3.50|3.50|5.04 % 🔼 |
|Disk Write Average (MB)|11653.34|10939.80|11137.47|4.43 % 🔽 |
|Disk Write Max (MB)|25870.51|21884.85|22532.00|12.90 % 🔽 |

#### CentOS Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26664)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26883)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27003)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|6803.93|7198.02|7510.01|10.38 % 🔼 |
|CPU Average (%)|17.40|18.40|19.21|10.39 % 🔼 |
|CPU Max (%)|101.40|101.00|101.90|0.49 % 🔼 |
|RSS Average (MB)|60.00|64.72|62.04|3.40 % 🔼 |
|RSS Max (MB)|60.64|64.89|62.64|3.30 % 🔼 |
|FD Average|12.14|12.10|12.10|0.34 % 🔽 |
|FD Max|14.00|14.00|14.00|🟰 |
|Read Ops Average (M)|494.70|392.38|390.56|21.05 % 🔽 |
|Read Ops Max (M)|1104.46|883.37|875.14|20.76 % 🔽 |
|Write Ops Average (M)|8.67|5.13|5.11|41.08 % 🔽 |
|Write Ops Max (M)|19.52|11.68|11.57|40.71 % 🔽 |
|Disk Read Average (MB)|0.00|0.00|0.00|🟰 |
|Disk Read Max (MB)|0.00|0.00|0.00|🟰 |
|Disk Write Average (MB)|18754.79|11776.56|11753.72|37.33 % 🔽 |
|Disk Write Max (MB)|41364.34|25981.51|25811.83|37.60 % 🔽 |

### Syscollector

#### Ubuntu Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26657)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26886)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27005)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|286.56|256.82|269.09|6.10 % 🔽 |
|CPU Average (%)|0.73|0.66|0.69|6.11 % 🔽 |
|CPU Max (%)|18.00|16.00|16.00|11.11 % 🔽 |
|RSS Average (MB)|14.51|14.52|14.63|0.83 % 🔼 |
|RSS Max (MB)|14.54|14.54|14.64|0.70 % 🔼 |
|FD Average|13.04|13.04|13.04|0.02 % 🔼 |
|FD Max|15.00|15.00|15.00|🟰 |
|Read Ops Average (M)|1.77|1.76|1.76|0.41 % 🔽 |
|Read Ops Max (M)|3.54|3.52|3.52|0.50 % 🔽 |
|Write Ops Average (M)|0.66|0.65|0.65|1.45 % 🔽 |
|Write Ops Max (M)|1.32|1.31|1.31|1.08 % 🔽 |
|Disk Read Average (MB)|0.00|0.00|0.00|🟰 |
|Disk Read Max (MB)|0.00|0.00|0.00|🟰 |
|Disk Write Average (MB)|1271.14|1250.53|1249.74|1.68 % 🔽 |
|Disk Write Max (MB)|2534.80|2499.67|2500.13|1.37 % 🔽 |

#### CentOS Agent

||[4.9.2-rc1.csv](https://github.com/wazuh/wazuh/issues/26657)|[4.10.0 Alpha 3](https://github.com/wazuh/wazuh/issues/26886)|[4.10.0 Beta 1](https://github.com/wazuh/wazuh/issues/27005)|Difference|
|---|--:|--:|--:|--:|
|CPU Time (s)|274.48|235.42|251.28|8.45 % 🔽 |
|CPU Average (%)|0.70|0.60|0.64|8.46 % 🔽 |
|CPU Max (%)|16.00|16.00|16.00|🟰 |
|RSS Average (MB)|24.27|24.66|26.89|10.81 % 🔼 |
|RSS Max (MB)|24.27|24.66|26.94|10.98 % 🔼 |
|FD Average|13.03|13.03|13.03|🟰 |
|FD Max|15.00|15.00|15.00|🟰 |
|Read Ops Average (M)|31.85|31.94|31.88|0.10 % 🔼 |
|Read Ops Max (M)|63.68|63.85|63.73|0.08 % 🔼 |
|Write Ops Average (M)|0.45|0.44|0.44|1.37 % 🔽 |
|Write Ops Max (M)|0.89|0.88|0.88|1.39 % 🔽 |
|Disk Read Average (MB)|0.00|0.00|0.00|🟰 |
|Disk Read Max (MB)|0.00|0.00|0.00|🟰 |
|Disk Write Average (MB)|854.06|843.47|842.38|1.37 % 🔽 |
|Disk Write Max (MB)|1707.60|1686.05|1683.71|1.40 % 🔽 |

### Configuration

The configuration files are exactly the same for all versions. The only difference is the manager IP address.

### Logs

#### 4.10.0 Alpha 3

```
2024/11/17 05:00:44 sca: INFO: Starting Security Configuration Assessment scan.
...
2024/11/17 05:02:33 sca: INFO: Integration checksum failed for policy '/var/ossec/ruleset/sca/stress_files_policy.yml'. Resending scan results in 5 seconds.
2024/11/17 05:02:33 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/17 05:02:36 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/17 05:02:36 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/17 05:02:40 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/17 05:02:40 sca: INFO: Security Configuration Assessment scan finished. Duration: 116 seconds.
```

#### 4.10.0 Beta 1

**Before the steep slope:**

```
2024/11/25 03:37:17 sca: INFO: Starting Security Configuration Assessment scan.
...
2024/11/25 03:39:05 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/25 03:39:08 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/25 03:39:08 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/25 03:39:12 rootcheck: INFO: Ending rootcheck scan.
2024/11/25 03:39:13 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/25 03:39:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 116 seconds.
```

**After the steep slope:**

```
2024/11/25 03:39:13 sca: INFO: Starting Security Configuration Assessment scan.
2024/11/25 03:39:14 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/25 03:39:17 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/stress_files_policy.yml'
2024/11/25 03:39:17 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/25 03:39:22 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/11/25 03:39:22 sca: INFO: Security Configuration Assessment scan finished. Duration: 9 seconds.
```

## Rationale

We observed that the agent managed to synchronize the database with the agent at the end of the "All-Except-Logcollector" test in 4.10.0-Beta1, which is unusual, and allowed the agent to run more scans per unit of time, from 116 seconds to 9 seconds.

This explains the difference in disk usage.

There have been no changes in SCA in 4.10.0-Alpha3 or 4.10.0-Beta1.

## Conclusion

We conclude that this is a normal condition and does not imply a bug or a change in behavior.
