### ISSUE TITLE
Error '-1' when downloading file: Could not connect to server warning message found in stress test

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#27086]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  |  modulesd  | Packages | 

 

## Description
During the analysis of [VULNERABILITY-DETECTOR-REGISTER (2.5d)](https://github.com/wazuh/wazuh/issues/26999), it has been found a the following warning in the manager logs

```
2024/11/25 00:40:41 wazuh-modulesd:content-updater WARNING: Error '-1' when downloading file: Could not connect to server. 
```

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 400 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build 2,5d: https://jenkins-staging.qa.wazuh.info/job/test_stress/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

2. Check the test and plots

### Current result
Presence of:

```
2024/11/25 00:40:41 wazuh-modulesd:content-updater WARNING: Error '-1' when downloading file: Could not connect to server. 
```

### Expected result
Absence of the warning

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/

- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/91/parameters

- Logs: 

  - 4.10.0-beta1
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B91-3600m/B91_manager_centos/logs/ossec_test_stress_B91_manager_2024-11-25.zip

  - 4.9.2-rc1
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5701-3600m/B5701_manager_centos/logs/ossec_Test_stress_B5701_manager_2024-10-31.zip

**Comment by juliamagan** [comment]
Expected behaviour with `localhost`
