### ISSUE TITLE
Silence 15029 errors on Wazuh agent

### ISSUE THREAD

**Issue by CodingJ13** [wazuh/wazuh#27093]
Hello, 

I have been discussing this issue in the Wazuh Slack channel, but have been forwarded here to raise this issue. 

**_Errors reported:_**
`2024/11/19 08:48:41 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:48:41 wazuh-agent: ERROR: Could not get message for (Security)
2024/11/19 08:51:06 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:51:06 wazuh-agent: ERROR: Could not get message for (Security)
2024/11/19 08:51:39 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:51:39 wazuh-agent: ERROR: Could not get message for (Security)
2024/11/19 08:51:39 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:51:39 wazuh-agent: ERROR: Could not get message for (Security)
2024/11/19 08:57:41 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:57:41 wazuh-agent: ERROR: Could not get message for (Security)
2024/11/19 08:57:41 wazuh-agent: ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2024/11/19 08:57:41 wazuh-agent: ERROR: Could not get message for (Security)`

Currently we have 9 servers with the Wazuh agent installed for log collection. Some of them are Domain Controllers, and these errors only occur on said Domain Controllers. 

I believe these errors fill the agent queue, which then starts raising alerts in our dashboard. I was advised to increase the buffer size for the agents on these servers, but obviously this doesnt resolve the errors and just prevents the alerts relating to event queue flooding being raised in the dashboard. 

I did notice our old SIEM agent (Splunk) was still installed, but removing that and rebooting the servers did not fix the issue either. 

**_Current agent version:_** 
WAZUH_VERSION="v4.9.0"
WAZUH_REVISION="40907"
WAZUH_TYPE="server"

Any assistance with this is greatly appreciated!

Many Thanks
J

**Comment by CodingJ13** [comment]
After further investigation it looks like these errors in the Wazuh agent logs are caused by the 1108 event id in the Windows server for event processing. While the issue with the server is being investigated, I would like to silence these 15029 errors on the agent as they generate unnecessary noise.

**Comment by jnasselle** [comment]
Hi @CodingJ13,

Could you please share the Event information with us to check what could be going wrong?


On the other hand, you can ignore the 1108 event by extending the default Windows [`query`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#query) value at agent `localfile` configuration

```xml
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 1108]</query>
  </localfile>
```

Regards,
Nico

**Comment by damarisg** [comment]
Since there has been no update on the issue, it will be closed.
