### ISSUE TITLE
Large decrease of events registered in Manager Dropped_events plot

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh#27095]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  beta1  |  Development  | syscheck| Packages | 

## Description
During the tests and analysis of [Release 4.10.0 - Beta 1 - Footprint Metrics - ALL-EXCEPT-LOGCOLLECTOR](https://github.com/wazuh/wazuh/issues/27007), we discover a large decrease of events registered in Manager Dropped_events plot in comparison with 4.9.2 - rc 1 version

- **4.10.0-beta1**
![image](https://github.com/user-attachments/assets/faf71b79-b2ae-48bb-b576-da1bdda132af)

- **4.9.2-rc1**
![image](https://github.com/user-attachments/assets/22861005-073e-4d99-a440-1a37da9a9c8c)

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | AWS | CentOS 8 | c5a.large | c5a.large | 250 | Packages |
| Agent node | AWS | CentOS 8 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Ubuntu 20 | c5a.large | c5a.large | 32 | Packages|
| Agent node | AWS | Windows 2019 | c5a.2xlarge| c5a.2xlarge | 64 | Packages|

### Steps to reproduce

1. Launch Test Stress build:  https://jenkins-staging.qa.wazuh.info/job/test_stress/97/ with the parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/parameters/

2. Check the test and plots

### Current result
Large decrease of events registered in Manager Dropped_events plot

### Expected result
Similar behavior with 4.9.2-rc1 plot should be displayed in syscheck for Manager Dropped_events plot

### Attachments

- Build link: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/
- Build parameters: https://jenkins-staging.qa.wazuh.info/job/test_stress/97/parameters/

- Logs: 

  - **4.10.0-beta1**
https://ci.wazuh.com/data/test_stress/pre-release/4.10.0/B97-3600m/B97_manager_centos/logs/ossec_test_stress_B97_manager_2024-11-25.zip

  - **4.9.2-rc1**
https://ci.wazuh.com/data/Test_stress/pre-release/4.9.2/B5706-3600m/B5706_manager_centos/logs/ossec_Test_stress_B5706_manager_2024-10-31.zip

**Comment by GabrielEValenzuela** [comment]
### **Report: Analysis of Dropped Events in RC2 and Beta1**

A detailed analysis was conducted on the data from two datasets (RC2 and Beta1) to evaluate the behavior of "Dropped from syscheck" events. Key metrics, statistical properties, correlations, and potential impacts of recent changes were investigated.

---

#### **Key Observations**
1. **Scale Differences**:
   - The number of dropped events in Beta1 is significantly lower compared to RC2, indicating a smaller scale of impact in Beta1.
   - This aligns with the observation that no errors or anomalies were detected in the logs.

2. **Potential Impact of Recent PR**:
   - https://github.com/wazuh/wazuh/issues/26741 introduced in version **4.10.0**, may have positively impacted the tests, potentially reducing the number of dropped events.
   - A search for changes related to "syscheck" or "FIM" highlighted this PR as the most relevant.

---

<details><summary>Statistical Properties</summary>

- **RC2 (Dropped from syscheck)**:
  - **Count**: 37,924
  - **Mean**: 10,052.29
  - **Standard Deviation**: 7,312.72
  - **Minimum**: 0
  - **Maximum**: 19,773
  - **Quartiles**:
    - 25th Percentile: 3,913
    - 50th Percentile (Median): 8,815
    - 75th Percentile: 18,015

- **Beta1 (Dropped from syscheck)**:
  - **Count**: 38,696
  - **Mean**: 3,029.72
  - **Standard Deviation**: 1,236.78
  - **Minimum**: 0
  - **Maximum**: 3,851
  - **Quartiles**:
    - 25th Percentile: 3,156
    - 50th Percentile (Median): 3,668
    - 75th Percentile: 3,830

**Interpretation**:
- RC2 has a much wider distribution of values, with a higher mean and greater variability, compared to Beta1's more consistent and lower range.
---

#### Linearity Analysis
- **Beta1**:
  - \( R^2 = 0.64 \): Moderate linearity, suggesting that while the data shows a general trend, non-linear factors may also influence the "Dropped from syscheck" metric.
- **RC2**:
  - \( R^2 = 0.97 \): Strong linearity, indicating that the behavior of "Dropped from syscheck" in RC2 closely follows a linear trend over time.

---

#### **Correlation Analysis**
- **Correlation Between RC2 and Beta1 (Dropped Events)**: **0.76**
  - This strong positive correlation suggests a consistent relationship between the two datasets for the "Dropped from syscheck" metric.
  - While the datasets are not identical, their behavior aligns closely, indicating similar patterns or trends.


</details>


#### **Conclusions**
- The observed decrease in dropped events in Beta1 may be linked to the implementation of the https://github.com/wazuh/wazuh/issues/26741. This change appears to have improved performance, reducing dropped events in the newer tests.
- The strong correlation between RC2 and Beta1, despite differences in scale, suggests consistency in the underlying processes or patterns.
- RC2 exhibits a broader and more variable distribution of dropped events, while Beta1 demonstrates a more stable and predictable behavior.

**Comment by rauldpm** [comment]
Hi @GabrielEValenzuela, if you need access to the environment please tell us, if not, notify us via Slack to destroy the environment when not needed please!

**Comment by sebasfalcone** [comment]
@GabrielEValenzuela Let's verify the amount of alerts generated in both 4.9.2 and 4.10.0

**Comment by GabrielEValenzuela** [comment]
#  Update
Thanks to @sebasfalcone's recommendation to review the reports, we found that the comparison between **4.9.2 RC2** and **4.10.0 Beta1** reveals **practically identical behavior**. This confirms that the module operates as expected across versions.

![Image](https://github.com/user-attachments/assets/5ee8a9de-fdfd-467c-bc30-de419dea4bde)

![Image](https://github.com/user-attachments/assets/28d27576-72a2-46ec-a044-a4d8c378aab9)
