### ISSUE TITLE
PCRE2 decoding - RockyLinux 9.4

### ISSUE THREAD

**Issue by asimat** [wazuh/wazuh#27109]
Wazuh version 4.9

## Description
PCRE2 Decoding not working

I have a working decoder rule that works on v4.7, I am now setting a new v4.9 Wazuh server but could not get the same decoder to work. When I run logtest it does not detect.

### Service/Product/Module

QNAP PCRE2 method

Decoder code:
<decoder name="qnap">
  <program_name>qulogd</program_name>
  <regex type="pcre2">Users: (.*), Source IP: ([^,]+),.* Accessed resources: (.*),.* Action: (.*)</regex>
  <order>loginname,sourceip,sharename,action</order>
</decoder>

### Current results

When using logtest these decoder is not used. If I change to normal prematch code like below then it works.

<decoder name="qnap">
  <prematch>qulogd</prematch>
</decoder>
<decoder name="qnap_child">
 <parent>qnap</parent>
 <regex>\.+ Users: (\.+),</regex>
 <order>user</order>
</decoder>

### Expected results

I expect the logtest command to pick it up, but does not

### Log examples

Some Raw syslogs from QNAP taken from Wazuh log archive as below:

2024 Oct 01 15:23:37 NAS-RND-200->10.30.44.200 Oct 1 15:23:35 NAS-200 qulogd[15593]: conn log: Users: admin, Source IP: 10.212.134.101, Computer name: ---, Connection type: HTTPS, Accessed resources: Administration, Action: Login Success

2024 Oct 01 15:24:32 NAS-RND-200->10.30.44.200 Oct 1 15:24:30 NAS-200 qulogd[15593]: event log: Users: admin, Source IP: 10.212.134.101, Computer name: ---, Application: ---, Category: ---, Content: [SNMP] Enabled/modified.

**Comment by jnasselle** [comment]
Hi @asimat ,

There was an error during the copy-paste of your custom decoder. Could you please check it?

Regards,
Nico

**Comment by damarisg** [comment]
Since there has been no update on the issue, it will be closed.
