### ISSUE TITLE
Wazuh agent uninstallation

### ISSUE THREAD

**Issue by Malwazu** [wazuh/wazuh#27117]
how admin knows  which wazuh agent uninstalled  by user

**Comment by pereyra-m** [comment]
Hello @Malwazu 

As you can see in this documentation section

https://documentation.wazuh.com/current/user-manual/agent/agent-enrollment/agent-life-cycle.html#agent-connection-states

The agent sends periodic keep-alive messages to the manager to report its state.
If after a few minutes there is no message received from that agent, the agent becomes disconnected, an alert is generated, and it could be for any of the following reasons:
- There is a communication problem with the manager
- The host is down
- The agent was removed

The user shouldn't be able to remove the `wazuh-agent` package without admin privileges, but soon in v4.10.0 we'll have a specific feature to prevent unauthorized removals
- https://github.com/wazuh/wazuh/issues/23466

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
