### ISSUE TITLE
Vulnerability Scanner - Fix offline content processing

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#27129]
## Description
The offline content processing is not working in 4.10.0, after the changes introduced here:
- https://github.com/wazuh/wazuh/pull/25094

The file hash is not properly set, therefore the file is re-processed every time the module starts.

It should be saved here:
https://github.com/wazuh/wazuh/blob/84556abb1034267960153667884791f3d31c5d37/src/shared_modules/content_manager/src/actionOrchestrator.hpp#L154-L186

If we check the feed manager updater database for the hash, we see its empty:
```console
 ./rocks_db_query_testtool -d /var/ossec/queue/vd_updater/rocksdb/updater_vulnerability_feed_manager_metadata/ -c downloaded_file_hash
```

This behaviour was validated here:
- https://github.com/wazuh/wazuh/issues/27124

## DoD
- [ ] Found the point of failure
- [ ] Fix the bug

**Comment by Dwordcito** [comment]
Changes were requested after doing the review and functional test.
