### ISSUE TITLE
Investigate Indexer-Connector/HTTP connection support for in Wazuh-Engine

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#27123]
#### Description

Currently, when **Wazuh-Engine** starts, it reads environment variables to load its configuration. We need to investigate whether it is possible to configure **Wazuh-Server** to connect to the **Indexer-Connector** of Wazuh-Engine over **HTTP** instead HTTPS.

**Objectives:**

- **Investigate** the capability of Wazuh-Engine to support HTTP communication for the Indexer-Connector.
- **Configure** Wazuh-Server to establish a connection with the Indexer-Connector over HTTP.
- **Determine** any necessary configuration changes or code modifications required to enable HTTP support.
- **Ensure** that Wazuh-Engine correctly reads environment variables to facilitate this configuration.

**Comment by JcabreraC** [comment]
Checked that it works well in the mentioned environment.

**Comment by Dwordcito** [comment]
LGTM
