### ISSUE TITLE
Wazuh stops collecting and displaying system logs after journald rotation.

### ISSUE THREAD

**Issue by lphbraz** [wazuh/wazuh#27151]
Hello, in the last few days I installed the latest version of wazuh (4.9.2 - all-in-one - following the official documentation on the website) on an Ubuntu 24.04 LTS server. I also installed the latest version of the agent (4.9.2) on all my production servers.

Everything was ok and working as expected, however, I noticed that the logs simply stopped appearing on the wazuh dashboard. After searching the wazuh forum and list, I identified that it could be a problem with wazuh not working correctly after the journald logs are rotated. This is evident because before the logs stopped displaying, there was a rotation log on my dashboard.

I ran the following command guided by a wazuh member on the email list:

`journalctl -u systemd-journald | tail -4 ps auxfww | grep wazuh-log grep -ri 'logcoll.*reload' /var/ossec/etc/ stat /var/ossec/etc/internal_options.conf cat /var/ossec/logs/ossec.log | grep "read_syslog"`

This was the result:

`nov 18 00:07:29 vazo systemd-journald[526]: Received client request to flush runtime journal.
nov 18 00:07:29 vazo systemd-journald[526]: /var/log/journal/eecd26ba9cc84748a85d14a22cf91232/system.journal: Journal file uses a different sequence number ID, rotating.
nov 18 00:07:29 vazo systemd-journald[526]: Rotating system journal.
nov 29 01:39:04 vazo systemd-journald[526]: /var/log/journal/eecd26ba9cc84748a85d14a22cf91232/user-1000.journal: Journal file uses a different sequence number ID, rotating.
root        1847  0.0  0.5 668784 48100 ?        Sl   nov18   1:40 /var/ossec/bin/wazuh-logcollector
root      182320  0.0  0.0   6676  2304 pts/0    S+   21:19   0:00                      \_ grep --color=auto wazuh-log
/var/ossec/etc/internal_options.conf:logcollector.force_reload=0
/var/ossec/etc/internal_options.conf:logcollector.reload_interval=64
/var/ossec/etc/internal_options.conf:logcollector.reload_delay=1000
  File: /var/ossec/etc/internal_options.conf
  Size: 14480           Blocks: 32         IO Block: 4096   regular file
Device: 252,0   Inode: 2247798     Links: 1
Access: (0640/-rw-r-----)  Uid: (    0/    root)   Gid: (  110/   wazuh)
Access: 2024-12-02 11:48:42.003681343 +0000
Modify: 2024-10-28 15:31:52.000000000 +0000
Change: 2024-11-09 20:07:32.426371937 +0000
 Birth: 2024-11-09 20:07:03.106790934 +0000`

I am available to provide anything else that is needed. I found Wazuh to be fantastic and would like it to work as expected so I can continue using it.

**Comment by juliancnn** [comment]
Hi @lphbraz,

Thanks for sharing this, we know it is causing inconvenience and we currently have the task in our backlog, you can follow it in this issue https://github.com/wazuh/wazuh/issues/26778
We appreciate your patience, and you will be able to see any updates in the previous issue. 

Best regards,
