### ISSUE TITLE
Exploratory ARM64 server in 4.10.2 with packages

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#27152]
## Description

As part of our efforts to provide support for ARM architectures, we need to conduct exploratory testing of the **Wazuh-Manager** (server) ARM64 packages for version **4.10.2**. The goal is to ensure that the ARM64 packages function correctly and provide the same level of reliability and functionality as the x86_64 packages.

## Objectives

- **Verify Core Functionality**: Ensure all core functionalities of Wazuh-Manager work correctly on ARM64 architecture.
- **Installation and Removal**: Confirm that the ARM64 packages install, upgrade, and remove smoothly on supported ARM64 platforms.
- **Compatibility Testing**: Test the ARM64 packages on various supported ARM64 distributions as per the compatibility matrix.
- **Performance Assessment**: Evaluate the performance of Wazuh-Manager on ARM64 hardware to ensure it meets non-functional requirements.

## Tasks

1. **Prepare Test Environments**:
   - Set up ARM64 environments with supported operating systems (e.g., Ubuntu 20.04 ARM64, Debian 11 ARM64).
   - Ensure environments are clean installations without conflicting software.

2. **Install Wazuh-Manager ARM64 Package**:
   - Obtain the Wazuh-Manager ARM64 package for version 4.10.2.
   - Install the package using the appropriate package manager (`apt`, `yum`, etc.).
   - Document any issues or errors encountered during installation.

3. **Functional Testing**:
   - **Agent Registration and Management**:
     - Register Wazuh agents (both ARM64 and x86_64) to the ARM64 Wazuh-Manager.
     - Verify agent connectivity, heartbeat signals, and status reporting.
   - **Event Collection and Alerting**:
     - Simulate security events to trigger alerts.
     - Verify that alerts are correctly generated, processed, and stored.
   - **Configuration Management**:
     - Apply configuration changes on the manager and verify they propagate to the agents.
     - Test policy enforcement and response.
   - **Module Testing**:
     - Test various Wazuh modules (e.g., File Integrity Monitoring, Log Analysis, Vulnerability Detector).
     - Ensure modules operate as expected on ARM64.

4. **Compatibility Testing**:
   - Install and test the Wazuh-Manager ARM64 package on different supported ARM64 distributions.
   - Confirm that dependencies are correctly resolved and that there are no distribution-specific issues.

5. **Removal Testing**:
   - Test the removal process to ensure it cleans up all components without residual files.

## Acceptance Criteria

- Wazuh-Manager ARM64 package for version 4.10.2 installs and operates correctly on all supported ARM64 platforms.
- All core functionalities, including agent management, event processing, and module operations, work as expected.
- No critical or high-severity issues remain unresolved.
- Performance is within acceptable ranges compared to benchmarks.
- Installation, upgrade, and removal processes are smooth and error-free.

## Additional Information

- **Supported Platforms**: Refer to the Wazuh compatibility matrix for the list of supported ARM64 distributions.
- **Artifacts**: Obtain ARM64 packages from the official repository or build pipeline.
- **Dependencies**: Ensure all dependencies are met on the ARM64 platforms.
- **Collaboration**: Coordinate with QA and development teams to report issues and get support.

**Comment by NahuFigueroa97** [comment]
<details><summary>Amazon linux 2 :green_circle: </summary> 
<p> 

```console
[ec2-user@ip-172-31-46-186 ~]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"

[ec2-user@ip-172-31-46-186 ~]$ sudo yum install wazuh-indexer_4.10.2-0_aarch64_999f5ab.rpm
Complementos cargados:extras_suggestions, langpacks, priorities, update-motd
Examinando wazuh-indexer_4.10.2-0_aarch64_999f5ab.rpm: wazuh-indexer-4.10.2-0.aarch64
Marcando wazuh-indexer_4.10.2-0_aarch64_999f5ab.rpm para ser instalado
Resolviendo dependencias
--> Ejecutando prueba de transacción
---> Paquete wazuh-indexer.aarch64 0:4.10.2-0 debe ser instalado
--> Resolución de dependencias finalizada
amzn2-core/2/aarch64                                                                                                                                                                 | 3.6 kB  00:00:00     
amzn2extra-docker/2/aarch64                                                                                                                                                          | 2.9 kB  00:00:00     
amzn2extra-kernel-5.10/2/aarch64                                                                                                                                                     | 3.0 kB  00:00:00     
wazuh                                                                                                                                                                                | 3.5 kB  00:00:00     

Dependencias resueltas

============================================================================================================================================================================================================
 Package                                      Arquitectura                           Versión                                   Repositorio                                                            Tamaño
============================================================================================================================================================================================================
Instalando:
 wazuh-indexer                                aarch64                                4.10.2-0                                  /wazuh-indexer_4.10.2-0_aarch64_999f5ab                                1.0 G

Resumen de la transacción
============================================================================================================================================================================================================
Instalar  1 Paquete

Tamaño total: 1.0 G
Tamaño instalado: 1.0 G
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Advertencia: Las bases de datos (RPMDB) han sido modificadas por un elemento ajeno a yum.
  Instalando    : wazuh-indexer-4.10.2-0.aarch64                                                                                                                                                        1/1 
### NOT starting on installation, please execute the following statements to configure wazuh-indexer service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable wazuh-indexer.service
### You can start wazuh-indexer service by executing
 sudo systemctl start wazuh-indexer.service
  Comprobando   : wazuh-indexer-4.10.2-0.aarch64                                                                                                                                                        1/1 

Instalado:
  wazuh-indexer.aarch64 0:4.10.2-0                                                                                                                                                                          

¡Listo!

```

</p>
</details>

**Comment by NahuFigueroa97** [comment]
# Ubuntu 20.04 
## Installation 
<details><summary>Indexer :green_circle: </summary>   
<p>  
 
```console

```

</p>
</details> 

<details><summary>Manager :green_circle: </summary> 
<p> 
 
```console


```

</p>
</details> 

<details><summary>Dashboard :green_circle: </summary> 
<p> 

``` console

 
```

</p> 
</details>

**Comment by Dwordcito** [comment]
LGTM, thanks @NahuFigueroa97
