### ISSUE TITLE
Wazuh Server cluster files synchronization configuration

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27171]
# Description

We need to modify the current server configuration to establish the file paths to synchronize between the cluster nodes. It is currently located in the `framework/wazuh/core/config/models/server.py` file but the instantiation of the `ServerSyncConfig` is not correct regarding its attributes:

https://github.com/wazuh/wazuh/blob/16ad9b02829d10cd19768a77f83cb722b51ba579/framework/wazuh/core/config/models/server.py#L262-L289

As it can be checked, the paths are not parametrized nor obtained from the location where the server resources are being defined (`framework/wazuh/core/common.py`).

**Comment by GGP1** [comment]
## Update

Updated filed paths.

**Comment by GGP1** [comment]
## Update

Updated filed paths and validated that it worked as expected.
