### ISSUE TITLE
Wazhu Installation Error

### ISSUE THREAD

**Issue by ArcZCodex** [wazuh/wazuh#27201]
Hey,

I have been trying to install Wazuh for some hours now, and getting this error. Even after using a clean new ubantu machine .

curl -sO https://packages.wazuh.com/4.9/wazuh-install.sh && sudo bash ./wazuh-install.sh -a
07/12/2024 15:14:04 INFO: Starting Wazuh installation assistant. Wazuh version: 4.9.2
07/12/2024 15:14:04 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/12/2024 15:14:16 INFO: --- Dependencies ----
07/12/2024 15:14:16 INFO: Installing gawk.
07/12/2024 15:14:27 INFO: Verifying that your system meets the recommended minimum hardware requirements.
07/12/2024 15:14:27 INFO: Wazuh web interface port will be 443.
07/12/2024 15:14:39 INFO: --- Dependencies ----
07/12/2024 15:14:39 INFO: Installing apt-transport-https.
07/12/2024 15:14:44 INFO: Installing debhelper.
07/12/2024 15:15:20 INFO: Wazuh repository added.
07/12/2024 15:15:20 INFO: --- Configuration files ---
07/12/2024 15:15:20 INFO: Generating configuration files.
07/12/2024 15:15:21 INFO: Generating the root certificate.
07/12/2024 15:15:21 INFO: Generating Admin certificates.
07/12/2024 15:15:21 INFO: Generating Wazuh indexer certificates.
07/12/2024 15:15:22 INFO: Generating Filebeat certificates.
07/12/2024 15:15:22 INFO: Generating Wazuh dashboard certificates.
07/12/2024 15:15:24 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
07/12/2024 15:15:25 INFO: --- Wazuh indexer ---
07/12/2024 15:15:25 INFO: Starting Wazuh indexer installation.
07/12/2024 15:18:13 INFO: Wazuh indexer installation finished.
07/12/2024 15:18:13 INFO: Wazuh indexer post-install configuration finished.
07/12/2024 15:18:13 INFO: Starting service wazuh-indexer.
07/12/2024 15:18:40 INFO: wazuh-indexer service started.
07/12/2024 15:18:40 INFO: Initializing Wazuh indexer cluster security settings.
07/12/2024 15:18:48 INFO: Wazuh indexer cluster security configuration initialized.
07/12/2024 15:18:48 INFO: Wazuh indexer cluster initialized.
07/12/2024 15:18:48 INFO: --- Wazuh server ---
07/12/2024 15:18:48 INFO: Starting the Wazuh manager installation.
07/12/2024 15:22:40 INFO: Wazuh manager installation finished.
07/12/2024 15:22:40 INFO: Wazuh manager vulnerability detection configuration finished.
07/12/2024 15:22:40 INFO: Starting service wazuh-manager.
07/12/2024 15:23:01 INFO: wazuh-manager service started.
07/12/2024 15:23:01 INFO: Starting Filebeat installation.
07/12/2024 15:25:38 INFO: Filebeat installation finished.
07/12/2024 15:25:47 INFO: Filebeat post-install configuration finished.
07/12/2024 15:25:47 INFO: Starting service filebeat.
07/12/2024 15:25:49 INFO: filebeat service started.
07/12/2024 15:25:49 INFO: --- Wazuh dashboard ---
07/12/2024 15:25:49 INFO: Starting Wazuh dashboard installation.
07/12/2024 15:31:42 INFO: Wazuh dashboard installation finished.
07/12/2024 15:31:42 INFO: Wazuh dashboard post-install configuration finished.
07/12/2024 15:31:42 INFO: Starting service wazuh-dashboard.
07/12/2024 15:31:46 INFO: wazuh-dashboard service started.
07/12/2024 15:31:49 INFO: Updating the internal users.
07/12/2024 15:32:40 INFO: A backup of the internal users has been saved in the /etc/wazuh-indexer/internalusers-backup folder.
07/12/2024 15:34:54 INFO: There was an error accessing the API. Retrying...
07/12/2024 15:36:00 INFO: The filebeat.yml file has been updated to use the Filebeat Keystore username and password.
07/12/2024 15:39:05 ERROR: wazuh-manager could not be started.
07/12/2024 15:39:05 INFO: --- Removing existing Wazuh installation ---
07/12/2024 15:39:05 INFO: Removing Wazuh manager.
07/12/2024 15:40:31 INFO: Wazuh manager removed.
07/12/2024 15:40:31 INFO: Removing Wazuh indexer.
07/12/2024 15:40:57 INFO: Wazuh indexer removed.
07/12/2024 15:40:57 INFO: Removing Filebeat.
07/12/2024 15:41:05 INFO: Filebeat removed.
07/12/2024 15:41:05 INFO: Removing Wazuh dashboard.
07/12/2024 15:41:18 INFO: Wazuh dashboard removed.
07/12/2024 15:41:18 INFO: --- Dependencies ----
07/12/2024 15:41:18 INFO: Removing gawk.
07/12/2024 15:41:24 INFO: Installation cleaned. Check the /var/log/wazuh-install.log file to learn more about the issue.

**Comment by pereyra-m** [comment]
Hello @ArcZCodex 

Can you give me more details about your host? What are your OS and hardware specs?
If the installation failed during the `wazuh-manager` start phase, please upload the following log files so I can analyze them:
- `/var/ossec/log/ossec.log`
- `/var/log/wazuh-install.log`

Regards.

**Comment by sebasfalcone** [comment]
Inactive thread, please re-open it if needed
