### ISSUE TITLE
Test Failure: test_configuration_change in vulnerability scanner

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#27240]
## Description
The vulnerability test has been running for almost 5hs (and continues), when the usual is 20 minutes. It seems to be stuck in the `test_configuration_change`, I attach 2 runs of workflows:

## Workflow Details
- **Workflow Link:** [GitHub Actions Run](https://github.com/wazuh/wazuh/actions/runs/12238218922/job/34135779622)
- **Workflow Link:** [GitHub Actions Run](https://github.com/wazuh/wazuh/actions/runs/12238033626/job/34135153997)

```console
------------------------------ live log teardown -------------------------------
INFO     test_policy_change_log:test_policy_change_log.py:61 Copying /home/runner/work/wazuh/wazuh/src/log.out to /home/runner/work/wazuh/wazuh/qa_logs/log.out.test_configuration_change[runner_function2]
wazuh_modules/vulnerability_scanner/qa/test_policy_change_log.py::test_configuration_change[runner_function3] 
```

**Comment by sebasfalcone** [comment]
## Update
Attempting to reproduce the failure locally

**Comment by sebasfalcone** [comment]
## Update
The changes introduced here:
- https://github.com/wazuh/wazuh/issues/27135

Modified the behaviour of the module, we can see that the test also hung:
- https://github.com/wazuh/wazuh/actions/runs/12151704269/job/33886777182?pr=27145

## Solution
We need to update the tests

**Comment by Dwordcito** [comment]
Moved to 4.10.1

**Comment by sebasfalcone** [comment]
## Issue blocked
We need the latest changes from 4.10.0 in order for this changes to make sense

**Comment by sebasfalcone** [comment]
## ETA update
Updated ETA while we await for the upward merge

**Comment by sebasfalcone** [comment]
## Issue unblocked
Upward merge performed, issue unblocked

**Comment by JcabreraC** [comment]
Reopened. The error is persisting: https://github.com/wazuh/wazuh/actions/runs/12389232775/job/34603700986

**Comment by sebasfalcone** [comment]
Re-launched the test in this branch and it passed:
- https://github.com/wazuh/wazuh/actions/runs/12322998132/job/34652706505?pr=27252

We will investigate this further

**Comment by sebasfalcone** [comment]
## Closing issue
Tests are now green
- https://github.com/wazuh/wazuh/issues/27446#issuecomment-2562782312
