### ISSUE TITLE
Review and fix bugs related to Wazuh Server directories in /run 

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27258]
# Description

During the last tests carried out for the 5.0 MVP, some bugs were found that must be taking care of by the team:
- The `wazuh-server` package creates the `/run/wazuh-server` directory when installed but `/run` is not a persistent file system, therefore the `wazuh-server` folder and its contents are deleted when the host is rebooted.
- The `/run/wazuh-server` folder contains the `cluster` and `socket` folders that are no longer required. These should not be created.

## Tasks

- [x] Apply the necessary changes to solve the mentioned bugs.
- [x] Test the changes and verify that these fix the bugs.

**Comment by nico-stefani** [comment]
# Update

I've moved the responsibility of creating the `/run/wazuh-server` directory to `wazuh_server.py` and removed it from the installation functions and package specs.
