### ISSUE TITLE
Huge increase of wazuh-indexer in Vulnerability Detection performance test

### ISSUE THREAD

**Issue by dgamboa1605** [wazuh/wazuh#27269]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  RC 1  |  Development  |  Indexer  | Repository |  

## Description

During the testing of 4.10.0 - RC 1 in the [vulnerability detection performance test](https://github.com/wazuh/wazuh/issues/27190), comparing it with the [previous version](https://github.com/wazuh/wazuh/issues/26617) an increase in wazuh-indexer has been detected and needs to be investigated. It was detected in the case of very high activity in indexer 1. Here are the details.

<details><summary>4.10.0-RC 1</summary>

![Disk_Read_Speed](https://github.com/user-attachments/assets/aca94377-ed37-4a21-947f-03d17d70f14a)
![Disk_Read](https://github.com/user-attachments/assets/ccc5c30a-6f50-43ea-afe1-a1edd55edced)
![Disk_Write_Speed](https://github.com/user-attachments/assets/fafbc664-81a4-453a-8958-90d74a371ff3)
![PSS](https://github.com/user-attachments/assets/78e0ce87-141d-4203-b6bb-dc9c561c84fd)
![USS](https://github.com/user-attachments/assets/25a59f3e-2d8c-434c-9995-98dba447e00d)
![VMS](https://github.com/user-attachments/assets/6404f2b8-8ce4-4ca6-82d3-e66cb61ef9e3)
![Write_Ops](https://github.com/user-attachments/assets/ad2543b8-97d6-4a9e-ac21-a34047edaf2e)

</details>

<details><summary>4.9.2 - RC1</summary>

![image](https://github.com/user-attachments/assets/fd24b5c0-3bdf-4dec-b83c-a9bfde82e7e7)
![image](https://github.com/user-attachments/assets/8258e42a-a611-44d5-bd2a-8d5add975088)
![image](https://github.com/user-attachments/assets/f67fcec1-1f3d-49a8-8acf-9196964e78ec)
![image](https://github.com/user-attachments/assets/99bc6d19-c018-4634-8af8-b8ac583ae38a)
![image](https://github.com/user-attachments/assets/2ac7eef5-5b79-439f-b5bb-460801c4e405)
![image](https://github.com/user-attachments/assets/36235991-a3fe-4557-8a89-1366c8116943)
![image](https://github.com/user-attachments/assets/71d3452f-1615-4c6d-8839-0d52a16476fd)

</details>

### Environment

The tests have been launched with the [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/) pipeline, using the following environment:

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Very High Activity | Simulate a large-scale environment with significant activity | 10 | 3 | 20000 | 1 | 1h |

<details><summary>Build parameters</summary>

[Build 804](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/804/parameters/)

</details>

## Evidences

- 4.10.0 - RC 1 Artifacts
   - [VeryHigh_Part1.zip](https://github.com/user-attachments/files/18071138/VeryHigh_Part1.zip)
   - [VeryHigh_Part2.zip](https://github.com/user-attachments/files/18071155/Veryhigh_Part2.zip)
   - [VeryHigh_Part3.zip](https://github.com/user-attachments/files/18071185/VeryHigh_Part3.zip)
   - [VeryHigh_Part4.zip](https://github.com/user-attachments/files/18071206/VeryHigh_Part4.zip)

- 4.9.2 - RC1 Artifacts
   - [artifacts1.zip](https://github.com/user-attachments/files/17558429/artifacts1.zip)
   - [artifacts2.zip](https://github.com/user-attachments/files/17558431/artifacts2.zip)
   - [artifacts3.zip](https://github.com/user-attachments/files/17558432/artifacts3.zip)

**Comment by AlexRuiz7** [comment]
We don't see that much difference on the charts. We cannot conclude any abnormal behavior.
