### ISSUE TITLE
Review and fix bug related to Wazuh Server files ownership

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27263]
# Description

After the merge of #26908, it was found that when trying to run the `wazuh-server` via `systemctl`, the files inside `src/init/templates/` that define the `start`, `stop` and `restart` commands which use the binary, still contain the `-r` flag.

These needs to be reviewed and modified to avoid requiring to run the Wazuh Server as root  and also modify the `wazuh` user and group to `wazuh-server`.

## Tasks

- [x] Implement the necessary changes to the install and package generation scripts.
- [x] Test the changes and provide evidence of the expected files and folders ownership.

**Comment by nico-stefani** [comment]
# Update

I've been trying to replicate the problem without success, I used the installation from sources and packages.
