### ISSUE TITLE
Spike - Package installation performance

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh#27278]
## Description
We need to validate the changes in performance for the server installation between 4.x and 5.0, using packages (rpm and deb)

### 5.0.0 packages
- [deb](https://github.com/wazuh/wazuh/actions/runs/12301599363/artifacts/2313192388)
- [rpm](https://github.com/wazuh/wazuh/actions/runs/12301627888/artifacts/2313202883)

### 4.9.2 packages
- [deb](https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.2-1_amd64.deb)
- [rpm](https://packages.wazuh.com/4.x/yum/wazuh-manager-4.9.2-1.x86_64.rpm)

## DoD
- [x] Performance comparison done

**Comment by sebasfalcone** [comment]
# Testing

## 4.9.2

### Centos 8
```console
time rpm -i wazuh-manager-4.9.2-1.x86_64.rpm 
warning: wazuh-manager-4.9.2-1.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 29111145: NOKEY

real	0m55.221s
user	0m46.612s
sys	0m3.538s

```

### Ubuntu 22.04
```console
root@ubuntu:/home/vagrant# time dpkg -i wazuh-manager_4.9.2-1_amd64.deb
Selecting previously unselected package wazuh-manager.
(Reading database ... 64136 files and directories currently installed.)
Preparing to unpack wazuh-manager_4.9.2-1_amd64.deb ...
Unpacking wazuh-manager (4.9.2-1) ...
Setting up wazuh-manager (4.9.2-1) ...

real	0m38.963s
user	0m31.754s
sys	    0m6.638s
```

## 5.0.0

## Upgrade

### Centos 8
```console
time rpm -i wazuh-server_5.0.0-0_x86_64_5ca2998.rpm 
chmod: cannot access '/bin/wazuh-engine': No such file or directory
chown: cannot access '/bin/wazuh-engine': No such file or directory
chmod: cannot access '/bin/wazuh-apid': No such file or directory
chown: cannot access '/bin/wazuh-apid': No such file or directory
chmod: cannot access '/bin/wazuh-comms-apid': No such file or directory
chown: cannot access '/bin/wazuh-comms-apid': No such file or directory
chmod: cannot access '/bin/wazuh-server': No such file or directory
chown: cannot access '/bin/wazuh-server': No such file or directory

real	0m23.288s
user	0m15.726s
sys	0m6.292s
```

> [!NOTE]
> Some errors appear in the upgrade


### Ubuntu 22.04
```console
time dpkg -i wazuh-server_5.0.0-0_amd64_5ca2998.deb
Selecting previously unselected package wazuh-server.
(Reading database ... 88137 files and directories currently installed.)
Preparing to unpack wazuh-server_5.0.0-0_amd64_5ca2998.deb ...
Unpacking wazuh-server (5.0.0-0) ...
Setting up wazuh-server (5.0.0-0) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...

real	0m4.320s
user	0m1.630s
sys	    0m1.560s
```

## Fresh install

### Centos 8
```console
sudo su
[root@centos vagrant]# time rpm -i wazuh-server_5.0.0-0_x86_64_5ca2998.rpm 
chmod: cannot access '/bin/wazuh-engine': No such file or directory
chown: cannot access '/bin/wazuh-engine': No such file or directory
chmod: cannot access '/bin/wazuh-apid': No such file or directory
chown: cannot access '/bin/wazuh-apid': No such file or directory
chmod: cannot access '/bin/wazuh-comms-apid': No such file or directory
chown: cannot access '/bin/wazuh-comms-apid': No such file or directory
chmod: cannot access '/bin/wazuh-server': No such file or directory
chown: cannot access '/bin/wazuh-server': No such file or directory

real	0m40.701s
user	0m17.403s
sys	0m18.178s
```

> [!NOTE]
> Some errors appear in the installation

### Ubuntu 22.04
```console
time dpkg -i wazuh-server_5.0.0-0_amd64_5ca2998.deb
Selecting previously unselected package wazuh-server.
(Reading database ... 64154 files and directories currently installed.)
Preparing to unpack wazuh-server_5.0.0-0_amd64_5ca2998.deb ...
Unpacking wazuh-server (5.0.0-0) ...
Setting up wazuh-server (5.0.0-0) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...

real	0m4.441s
user	0m1.585s
sys	    0m1.770s
```

## Comparison

### Centos
| **Version** | **Test Type**       | **real (s)** | **user (s)** | **sys (s)** |
|-------------|---------------------|--------------|--------------|-------------|
| **4.9.2**   | Install             | 55.221       | 46.612       | 3.538       |
| **5.0.0**   | Upgrade             | 23.288       | 15.726       | 6.292       |
| **5.0.0**   | Install             | 40.701       | 17.403       | 18.178      |

- Improvement in the real-time (30% to 81%)
- Improvement in the cpu user mode (91% to 99%)
- Degradation in the cpi kernel mode (56% to 134%)


### Ubuntu
| **Version** | **Test Type**       | **real (s)** | **user (s)** | **sys (s)** |
|-------------|---------------------|--------------|--------------|-------------|
| **4.9.2**   | Install             | 38.963       | 31.754       | 6.638       |
| **5.0.0**   | Upgrade             | 4.320        | 1.630        | 1.560       |
| **5.0.0**   | Install             | 4.441        | 1.585        | 1.770       |


- Improvement in the real-time (160%)
- Improvement in the cpu user mode (180%)
- Improvement in the cpi kernel mode (115% to 124%)

**Comment by Dwordcito** [comment]
Based on the test evidence I can conclude that we don't have degradation in the installation time at the moment.
