### ISSUE TITLE
Huge increase of wazuh-indexer in Vulnerability Detection performance test

### ISSUE THREAD

**Issue by DiegoRatto** [wazuh/wazuh#27271]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  RC 1  |  Development  |  Indexer  | Repository |  

## Description

During the testing of 4.10.0 - RC 1 in vulnerability detection perfomarce test in [this issue](https://github.com/wazuh/wazuh/issues/27190), comparing it with previous versions an increase in wazuh-indexer has been detected and needs to be investigated. It has been detected in the case of high activity in the  indexer 1. Here are the details.

<details><summary>4.10.0-RC 1</summary>

![Disk_Read](https://github.com/user-attachments/assets/34cf079f-55de-45c5-ae89-14c236367ad3)
![PSS](https://github.com/user-attachments/assets/e851b36a-a7f5-4f4b-97c1-b5d492a4a7d1)
![RSS](https://github.com/user-attachments/assets/215dfb62-a4ba-44eb-9af4-56e9668fffbe)
![USS](https://github.com/user-attachments/assets/c3c74aea-40b9-48c6-9f56-72c5e3c854b5)

</details>

<details><summary>4.9.1-RC 2</summary>

![Disk_Read](https://github.com/user-attachments/assets/37cf16eb-9574-44a5-adfe-6660207765d1)
![PSS](https://github.com/user-attachments/assets/a96b1207-9bcb-44c5-911b-aaeccf74bf58)
![RSS](https://github.com/user-attachments/assets/c160c637-5c5b-4e2a-b42f-4c3bf1dbbf1b)
![USS](https://github.com/user-attachments/assets/1eb5daff-af3a-4292-a49c-23cd98df6097)

</details>

### Environment

The tests have been launched with the [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/) pipeline, using the following environment:

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| High Activity | Simulate a large-scale environment with significant activity | 2 | 2 | 200 | 50  | 3h |

<details><summary>Build parameters</summary>

[Build 803](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/803/parameters/)

</details>

## Evidences

- [4.10.0-RC 1 Artifact](https://github.com/user-attachments/files/18071057/high.zip)

- [4.9.1-RC 1 Artifact](https://github.com/user-attachments/files/17212326/artifacts.zip)

**Comment by AlexRuiz7** [comment]
We don't see that much difference on the charts. We cannot conclude any abnormal behavior.
