### ISSUE TITLE
Significant decrease of wazuh-apid in Vulnerability Detection performance test

### ISSUE THREAD

**Issue by dgamboa1605** [wazuh/wazuh#27270]
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.10.0  |  RC 1  |  Development  |  Master  | Repository |  

## Description

During the testing of 4.10.0 - RC 1 in the [vulnerability detection performance test](https://github.com/wazuh/wazuh/issues/27190), comparing it with the [previous version](https://github.com/wazuh/wazuh/issues/26172)  significant decrease of `wazuh-apid` in **FD, PSS, Read_Ops, RSS, USS**, and **VMS** from Master has been detected. Here are the details.

<details><summary>4.10.0-RC 1</summary>

![image](https://github.com/user-attachments/assets/6c30e6b1-e2d6-41c7-9381-6ddae3da1163)
![image](https://github.com/user-attachments/assets/2a9d5a26-d270-4063-b7c4-3024b187983a)
![image](https://github.com/user-attachments/assets/91de8e35-0ce7-42cf-8c91-196e798eb079)
![image](https://github.com/user-attachments/assets/576bbb08-2a99-4715-a0dc-3731aa5ce36a)
![image](https://github.com/user-attachments/assets/556e3347-4796-4749-94c8-6dcaa99916b7)
![image](https://github.com/user-attachments/assets/8386ae3a-7576-4aab-af99-a561afe4704a)
![image](https://github.com/user-attachments/assets/e53fa416-c9cf-47fb-8443-1d61e5dffccb)

</details>

<details><summary>4.9.1 - RC 3</summary>

![image](https://github.com/user-attachments/assets/50e245ca-c4da-40ab-98cf-ae5921a34cb9)
![image](https://github.com/user-attachments/assets/62ef74dc-be9d-4408-b8da-12f95e94886f)
![image](https://github.com/user-attachments/assets/952b46c1-c661-4b9f-b849-50de1e49d2a7)
![image](https://github.com/user-attachments/assets/21e871e3-7037-4f37-b241-0f633fd36734)
![image](https://github.com/user-attachments/assets/cf57eb18-2238-4eb7-99ff-7ee567e2ff83)
![image](https://github.com/user-attachments/assets/2e2a183a-2a41-4a33-ae42-e06fd8a26bd6)
![image](https://github.com/user-attachments/assets/f3262691-bcc5-402e-be49-aa57ffa028c2)

</details>

### Environment

The tests have been launched with the [CLUSTER-Workload_benchmarks_metrics](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/) pipeline, using the following environment:

| Case | Description | Workers | Indexers |  Agents | EPS  | Time |
| --- | --- | --- | --- | --- | --- | --- |
| Medium Activity | Simulate a medium-sized environment with moderate activity | 2 | 2 | 50 | 10 | 3h |

<details><summary>Build parameters</summary>

[Build 802](https://ci.wazuh.info/job/CLUSTER-Workload_benchmarks_metrics/802/parameters/)

</details>

## Evidences

- 4.10.0 - RC 1 Artifacts
   - [Medium.zip]https://github.com/user-attachments/files/18071022/Medium.zip)

- 4.9.1 - RC 3 Artifacts
   - [artifacts.tgz.zip)](https://github.com/user-attachments/files/17296010/artifacts.tgz.zip)

**Comment by fdalmaup** [comment]
# Update

A similar script as the one found [here](https://github.com/wazuh/wazuh/issues/26839#issuecomment-2479550542) was used to compare the mentioned properties:

![image](https://github.com/user-attachments/assets/7d33c3f8-cf61-4528-bb25-b33e63fec13e)

![image](https://github.com/user-attachments/assets/f5298ee1-2d4d-4d6a-9d75-cecae987bc06)

![image](https://github.com/user-attachments/assets/58b6d549-9239-4569-a117-6afb0132a32f)

![image](https://github.com/user-attachments/assets/a785b85e-11ec-40c5-833c-115a1108b2dd)

![image](https://github.com/user-attachments/assets/b9fb7b51-cf8d-4c07-9778-00dc0199153c)

![image](https://github.com/user-attachments/assets/ebea8538-01c2-4b76-af92-9488ea8a66db)

## Conslusions

As it can be checked, the behavior of the variables is similar in both versions, with slight differences in the maximum and minimum values. Moreover, no major changes have been carried out between versions, only upgrades in dependencies related to the Python embedded interpreter.

**Comment by GGP1** [comment]
## Review

The investigation successfully compared the values with a previous version and we could observe a small upward change in this version's values, but nothing outside of the extraordinary.

The metrics vary depending on the hosts' load and the tests unpredicatable behavior. I don't think the difference is enough to make any modifications. Furthemore, as it was pointed out, no major changes have been carried out between versions. LGTM.
