### ISSUE TITLE
Rules with correlation of PID and PPID fields

### ISSUE THREAD

**Issue by JavierEnciso280** [wazuh/wazuh#27281]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| TBD | Analysisd| Manager | - | - |

# Description

If I have a Sysmon Event 3 (Network Connection) and, from all the fields in the event, I’m interested in these two:
"win.eventdata.image: pepito.exe", "win.eventdata.processId": 1234.

Then another event is generated, this time Event 1 (Process Create), with the following fields:
"win.eventdata.image: cmd.exe",
"win.eventdata.parentProcessId": 1234.

How can I activate a rule that performs this comparison? Specifically: a process with ID 1234 generates a "network connection" event, and later that same process generates a "Process Create" event (e.g., executes cmd.exe). The only link between the two events is the value 1234, which appears in different fields in both events.

It’s crucial to have the ability to activate rules that perform such comparisons because I’ve found that comparing other fields proves this cannot be done otherwise.

**Comment by JavierEnciso280** [comment]
Si tengo un evento 3 de Sysmon (Network Connection) y en el evento, y de todos los campos del evento me interesan estos 2:
 "win.eventdata.image: pepito.exe", "win.eventdata.processId": 1234
Luego se genera otro evento, esta vez el evento 1 (Process Create) con los siguientes campos:  
"win.eventdata.image: "cmd.exe"
"win.eventdata.parentProcessId": 1234   
Como activar una regla que logre hacer esa comparacion? es decir, Un proceso con Id 1234 genera una "conexion de red" posteriormente ese proceso genera un evento "Process Create" Ej. Ejecuta un cmd.exe. 
Es mas que necesario tener la capacidad de activar reglas que hagan esta comparacion, ya que por comparar otros campos he comprobado que esto no se puede hacer.

**Comment by jnasselle** [comment]
Hi @JavierEnciso280,

Please use English as the language to allow this information to be widely accessible.

I have translated your comment into English and incorporated it into the main issue description. Please validate that the content is consistent with your original question and mention the version of wazuh you are working on. Once this is done, we will continue to determine how to help you with your problem.

**Comment by JavierEnciso280** [comment]
That's right, I need to compare two different labels with the same content in two diffrent events

**Comment by jnasselle** [comment]
Hi @JavierEnciso280 ,

Unfortunately, Wazuh Rules does not allow the correlation of two different fields and their values.

Sorry for the inconvenience,
Nico
