### ISSUE TITLE
Wazuh Server scaffolding refinement

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#27285]
# Description

As part of the E2E being carried out at https://github.com/wazuh/wazuh/issues/27248, we have found a couple of changes required in the Wazuh Server scaffolding that should be taken into account for the current stage of development:

- [x] Change the name of the group file folder from `shared` to `groups`, being the absolute location `/etc/wazuh-server/groups`.
- [x] Move every certificate file to `/etc/wazuh-server/certs` so that they are in a separate and specific location.

**Comment by GGP1** [comment]
## Update

Made the modifications necessary to conform with the new scaffolding requiremetns.

**Comment by GGP1** [comment]
## Update

Made the modifications necessary to conform with the new scaffolding requirements.
