### ISSUE TITLE
Wazuh Vulnerabilty detection dashboard and Inventory "No results match your criteria" but showing events

### ISSUE THREAD

**Issue by 42nado** [wazuh/wazuh#27299]
<html>
<body>

<table>
  <thead>
    <tr>
      <th>Wazuh Version</th>
      <th>Component</th>
      <th>Install Type</th>
      <th>Install Method</th>
      <th>Platform</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>4.8.2</td>
      <td>Vulnerability Detector</td>
      <td>Manager/Agent</td>
      <td>Packages/Sources</td>
      <td>Any OS</td>
    </tr>
  </tbody>
</table>

</body>
</html>
****

We have wazuh setup 4.8.2 already try disabled and enabled the vulnerability detection in the ossec conf then restart the wazuh. I already tried deleting the content of /var/ossec/queue/vd/*

Our setup is a multi node. I am not the one setup this the one who set up this is no longer works here.I think there previous version is from 4.7 and upgrade to current version i really not sure with this. Hopefully someone will help me to solve this issue . Thank
![viber_image_2024-12-15_09-47-09-134](https://github.com/user-attachments/assets/7c9d9d87-e0d5-446c-a541-56a402ae61ed)
![viber_image_2024-12-15_09-42-22-660](https://github.com/user-attachments/assets/d70ccdd9-61ee-4e20-b377-92665617d58a)
![viber_image_2024-12-15_09-38-17-935](https://github.com/user-attachments/assets/450da0e3-15fc-40e8-a09b-6b8607387cce)
![viber_image_2024-12-15_09-35-28-350](https://github.com/user-attachments/assets/d5891872-a5c7-418e-88ae-f5f76d89bd17)
![viber_image_2024-12-15_09-33-57-098](https://github.com/user-attachments/assets/fcf2fbfa-879a-474a-8eef-159b3af58b7d)

![viber_image_2024-12-15_09-33-35-029](https://github.com/user-attachments/assets/5a01c82e-fadf-4d50-8c28-57cc3d3c08c0)
![viber_image_2024-12-15_09-32-46-282](https://github.com/user-attachments/assets/ea4c0667-0cbc-485a-abc9-3c4092c327fb)
![viber_image_2024-12-15_09-32-30-875](https://github.com/user-attachments/assets/1660c415-656b-4c88-9153-3e2524febad3)
![image](https://github.com/user-attachments/assets/c7b97851-b16d-412f-ad44-29091edbcec6)
![image](https://github.com/user-attachments/assets/aa1074c8-f410-4b41-a3c1-213e8fe5af6f)
![image](https://github.com/user-attachments/assets/121a65fc-6e70-4c27-95e9-11930ca38393)

**Comment by Damian-Mangold** [comment]
Duplicated https://github.com/wazuh/community/issues/40740

**Comment by 42nado** [comment]
> Duplicated https://github.com/wazuh/community/issues/40740

![image](https://github.com/user-attachments/assets/fe1c82eb-335b-43bc-9154-ee1d9e7c8ded)
404 not found

**Comment by Damian-Mangold** [comment]
Hello @42nado, the link I passed above is for internal tracking. I was referring to this slack thread:

 - https://wazuh.slack.com/archives/C07CNG3M11N/p1734263391730879
