### ISSUE TITLE
Impact of multiple localfile directives pointing to the same file.

### ISSUE THREAD

**Issue by gjahchan** [wazuh/wazuh#2730]
Windows Agent 3.8.2 complains with a warning of duplicate localfile entries if more than one localfile entry points to the same location. The consequence is however unclear. How does the agent behave when that happens?

Does it:
i) Ignore all entries; or
ii) Apply the last entry; or
iii) Apply all the entries -- leading to potential duplication of events collected in case of overlap; or
iv) Apply all the entries while preventing duplication of events collected in case of overlap.

**Comment by TJOSERAFAEL** [comment]
Hi @gjahchan 

if there are duplicated `localfile` entries, the agent will load them all, check for duplicated ones and remove them, so only the first non duplicated entries will be taken into account.

Best regards.

**Comment by gjahchan** [comment]
How about adding an "overwrite" directive similar to the mechanism of overwriting an out-of-the-box rule *without* having to tamper with the original rule or the ootb ruleset, which gets updated silently with every Wazuh update.

If we need to add filter to the following entry in ossec.conf *without* having to manually edit ossec.conf on the agent:
\<localfile\>
  \<location\>Security\</location\>
  \<log_format>eventchannel\</log_format\>
\</localfile\>

We would like to be be able to specify it as follows in agent.conf:
  \<!-- Overwrite previous localfile entry --\>
\<localfile overwrite="yes"\>
  \<location\>Security\</location\>
  \<log_format>eventchannel\</log_format\>
  \<query\>
  ...
  \</query>
\</localfile\>

This approach maintains the integrity of the deployment model while enabling full customizability of the out-of-the-box ossec agent localfile configuration.

**Comment by Zenidd** [comment]
Hi @gjahchan,

- In the current version of Wazuh (At the time of writing this message is v3.9.2) localfile behavior is what explains @TJOSERAFAEL on the answer above.

- Our target is that if more than one localfile entry points to the same location the **last entry is the one applied**. It has been already implemented on this PR https://github.com/wazuh/wazuh/pull/3616 . This fix will be available in upcoming versions of Wazuh.

- I can see the further Warning message when starting up Wazuh with a duplicated localfile entry:

```
2019/07/08 15:12:49 ossec-logcollector: WARNING: (1958): Log file '/var/log/apache2/error.log' is duplicated.
```

We have changed the warning message for an INFO message, more suitable for what we communicate. PR: https://github.com/wazuh/wazuh/pull/3633
```
2019/07/08 15:32:54 ossec-logcollector: INFO: (1958): Log file '/var/log/apache2/error.log' is duplicated.
```

- As for the overwrite functionality in the configuration files we will review your proposal and if possible we will include it in our roadmap.

Thank you very much for your contributions! 

Greetings,

Juan Pablo Sáez
