### ISSUE TITLE
The `tar.xz` feed file provided by the Wazuh manager at installation is processed even if an offline update is configured

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#27334]
| Version | Revision | Production/Development | Component | Install type |
|:--:|:--:|:--:|:--:|:--:|
| 4.10.0  | RC 1   | Development   |  wazuh-modulesd:vulnerability-detection  | Repository | 

## Description

The Wazuh manager can be configured to use a feed offline specified by the user in its local file system, this can be configured following the documentation https://documentation-dev.wazuh.com/v4.10.0-rc1/user-manual/capabilities/vulnerability-detection/offline-update.html

The installed package already has a `tar.xz` file located in `/var/ossec/tmp/` ready to be ingested in the first start, but I found some scenarios that we need to review

### Scenario 1

If the Wazuh manager is configured to use the offline feed, it will ingest the offline feed (`zip`) and the `tar.xz` file located in `/var/ossec/tmp` (or at least the process decompress it and remove it like the usual usage). This could mean that the feed is being ingested from two sources at the same time and could lead to potential errors

### Scenario 2

If the Wazuh manager is configured to use the offline feed and the `tar.xz` provided by the package is removed to force the use of the offline feed, an error will appear when decompressing the `tar.xz` file, in this case, the log will show an error and a message of the feed being ingested (which is inconsistent: if no file is decompressed then there is no feed to be handled)

In the second scenario, an error can be observed in the ossec.log file, then, it can be seen that the feed is being ingested (the offline one)

The decompress message refers to the `tar.xz` file while the `Initiating update feed process` message refers to the offline `zip` file (the following logs are obtained with debug 0

```
2024/12/17 20:44:15 wazuh-modulesd:vulnerability-scanner: ERROR: Error opening the database: Couldn't find column family: 'vendor_map'.
2024/12/17 20:44:15 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/12/17 20:44:15 wazuh-modulesd:vulnerability-scanner: INFO: Vulnerability scanner module started.
2024/12/17 20:44:19 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2024/12/17 20:44:19 sca: INFO: Security Configuration Assessment scan finished. Duration: 4 seconds.
2024/12/17 20:44:24 wazuh-modulesd:vulnerability-scanner: INFO: Initiating update feed process.
```

### Debug 2 research

Reviewing the ossec.log in debug 2, we can see that the first scenario shows a message stating an `xz` decompression (the offline file is a `zip` file)

```
2024/12/17 20:06:10 wazuh-modulesd:vulnerability-scanner[111507] vulnerabilityScannerFacade.cpp:63 at decompressDatabase(): INFO: Starting database file decompression.
2024/12/17 20:06:10 wazuh-modulesd:vulnerability-scanner[111507] vulnerabilityScannerFacade.cpp:64 at decompressDatabase(): DEBUG: Starting XZ file decompression.
```

In the second scenario, we can see in debug 2 that the `tar.xz` file provided by the package is not found (but the offline file has been decompressed successfully)

```
2024/12/17 20:22:47 wazuh-modulesd:vulnerability-scanner[166607] vulnerabilityScannerFacade.cpp:382 at handlePolicyChanges(): DEBUG: No policy has changed or no action is needed for the manager.
2024/12/17 20:22:47 wazuh-modulesd:vulnerability-scanner[166607] vulnerabilityScannerFacade.cpp:57 at decompressDatabase(): DEBUG: No database compressed file found at 'tmp/vd_1.0.0_vd_4.10.0.tar.xz'. Skipping decompression.
2024/12/17 20:22:47 wazuh-modulesd:vulnerability-scanner[166607] databaseFeedManager.hpp:340 at TDatabaseFeedManager(): ERROR: Error opening the database: Couldn't find column family: 'vendor_map'.
2024/12/17 20:22:47 wazuh-modulesd:content-updater[166607] actionOrchestrator.hpp:125 at ActionOrchestrator(): DEBUG: Creating 'vulnerability_feed_manager' Content Updater orchestration
```

```
2024/12/17 20:22:48 wazuh-modulesd:content-updater[166607] zipDecompressor.hpp:74 at handleRequest(): DEBUG: ZipDecompressor - Starting process
2024/12/17 20:22:48 wazuh-modulesd:content-updater[166607] zipDecompressor.hpp:49 at decompress(): DEBUG: Decompressing 'queue/vd_updater/tmp/downloads/vd.zip' into 'queue/vd_updater/tmp/contents'
```

### Environment

| Node | Vagrant/AWS | Image | CPU | RAM (GB) | Disk size (GB) | Packages/Repository/Sources branch|
|:--:|:--:|:--:|:--:|:--:|:--:|---|
| Master node | vagrant | generic/ubuntu2004 | 4 | 8096 | Default (20) | Repository |
| Indexer node | vagrant | generic/ubuntu2004 | 4 | 8096 | Default (20) | Repository |

> [!NOTE]
> Master and indexer nodes are the same node

#### Scenario 1

1. Deploy the vagrant VM specified in the environment section
2. Access the VM and install the Wazuh indexer and the Wazuh manager following the step-by-step guide without starting the Wazuh manager and Filebeat packages
  - https://documentation-dev.wazuh.com/v4.10.0-rc1/installation-guide/wazuh-indexer/step-by-step.html 
  - https://documentation-dev.wazuh.com/v4.10.0-rc1/installation-guide/wazuh-server/step-by-step.html 
3. Download the feed and move it to the /tmp directory
  - $ curl -sO https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1117976_1733137820.zip
  - $ mv 1117976_1733137820.zip /tmp/vd.zip
4. Configure the Wazuh manager with the offline feed using the offline documentation
   - https://documentation-dev.wazuh.com/v4.10.0-rc1/user-manual/capabilities/vulnerability-detection/offline-update.html 
5. Start the Wazuh manager and Filebeat services
6. Monitor the /var/ossec/tmp directory and the ossec.log file

#### Scenario 2

1. Deploy the vagrant VM specified in the environment section
2. Access the VM and install the Wazuh indexer and the Wazuh manager following the step-by-step guide without starting the Wazuh manager and Filebeat packages
  - https://documentation-dev.wazuh.com/v4.10.0-rc1/installation-guide/wazuh-indexer/step-by-step.html 
  - https://documentation-dev.wazuh.com/v4.10.0-rc1/installation-guide/wazuh-server/step-by-step.html 
3. Download the feed and move it to the /tmp directory
  - $ curl -sO https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1117976_1733137820.zip
  - $ mv 1117976_1733137820.zip /tmp/vd.zip
4. Configure the Wazuh manager with the offline feed using the offline documentation
   - https://documentation-dev.wazuh.com/v4.10.0-rc1/user-manual/capabilities/vulnerability-detection/offline-update.html 
5. Remove the `/var/ossec/tmp/vd_1.0.0_vd_4.10.0.tar.xz` file
5. Start the Wazuh manager and Filebeat services
6. Monitor the /var/ossec/tmp directory and the ossec.log file

### Current result

- Scenario 1: The Wazuh manager seems to be ingesting the offline and the installed feed at the same time
- Scenario 2: The Wazuh manager seems to try to ingest the installed feed always even if the offline feed is configured

### Expected result

- If the offline feed is configured the installed feed should not be ingested or handled

### Attachments

- Vulnerability detection configuration

```
<vulnerability-detection>
    <enabled>yes</enabled>
    <index-status>yes</index-status>
    <feed-update-interval>60m</feed-update-interval>
    <offline-url>file:///tmp/vd.zip</offline-url>
  </vulnerability-detection>

  <indexer>
    <enabled>yes</enabled>
    <hosts>
      <host>https://<indexer-ip>:9200/</host>
    </hosts>
    <ssl>
      <certificate_authorities>
        <ca>/etc/filebeat/certs/root-ca.pem</ca>
      </certificate_authorities>
      <certificate>/etc/filebeat/certs/filebeat.pem</certificate>
      <key>/etc/filebeat/certs/filebeat-key.pem</key>
    </ssl>
  </indexer>
```

- Offline feed: https://cti.wazuh.com/store/contexts/vd_1.0.0/consumers/vd_4.8.0/1117976_1733137820.zip
- ossec.log in debug2 when both files are ingested: [ossec.log](https://github.com/user-attachments/files/18171379/ossec.log)
- ossec.log in debug2 when only the offline feed exists (installed feed has been removed): [ossec.log](https://github.com/user-attachments/files/18171381/ossec.log)

**Comment by Dwordcito** [comment]
This issues was discussed on an internal call.

The first case is expected by design, first is decompressed and after that the offline feed is ingested.
The second one not is a valid case, we don't have the use case to delete the /var/ossec/tmp/xxx.tar.xz file after install.
