### ISSUE TITLE
Wazuh-Server uninstallation does not remove `wazuh-server` user and group

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#27350]
## Description
When uninstalling **Wazuh-Server** (tested on DEB packages and potentially affecting RPM as well), the `wazuh-server` user and group created during installation are not removed. This leads to leftover system accounts even after the package is purged, resulting in a less clean uninstallation process.

## Objectives
- Ensure that the `wazuh-server` user and group are removed upon uninstallation, maintaining a clean system state.
- Verify and apply this fix for both DEB and RPM package formats.

## Tasks
1. **Investigate Current Behavior:**
   - Review the post-removal (`postrm`) or equivalent script logic in the DEB packaging to identify why the user and group are not removed.
   - Check the RPM packaging scripts for similar behavior.

2. **Implement User and Group Removal:**
   - Modify the uninstallation scripts to remove the `wazuh-server` user and group once all related Wazuh-Server processes and files are gone.
   - Ensure that the removal only occurs if the `wazuh-server` user and group were originally created by the package installation (to avoid unintended consequences if they existed beforehand).

3. **Testing:**
   - Install Wazuh-Server on a clean system and verify that the `wazuh-server` user and group are created.
   - Uninstall Wazuh-Server and check if the `wazuh-server` user and group are removed.
   - Repeat the process for both DEB and RPM packages, if applicable.

**Comment by fdalmaup** [comment]
Carried out in https://github.com/wazuh/wazuh/pull/27332/commits/9f1637006400e595cd31d3bb9fe5a5291b89904d.
