### ISSUE TITLE
ossec-control does not shut down disabled ossec daemons

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#274]
After disabling an optional Wazuh Manager daemon like this

`/var/ossec/bin/ossec-control disable auth`

...when you then do an "ossec-control stop" or "ossec-control restart", it fails to shut down the disabled daemon.  
I recommend you make "ossec-control disable" automatically shut down the daemon it is disabling, or make ossec-control check for the existence of disabled ossec-* daemons that might still be running rather than only consult the list of enabled daemons.

Kevin

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting,

You are totally right and we will improve that feature as soon as possible.

Best regards,
Chema.

**Comment by vikman90** [comment]
Hi @branchnetconsulting,

This issue has just been done by @PSanchezR in https://github.com/wazuh/wazuh/pull/300.

Thank you for feedback!
Best regards.
