### ISSUE TITLE
Group field in email_alerts doesn't work

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh#2744]
Hi team,
I've done some tests to `<email_alerts>` config (Granular email options) in ossec.conf file according to:
https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?

But when I use the option `<group>` it stops sending the emails, I've used the following configuration:

![imagen](https://user-images.githubusercontent.com/47329460/53805222-dc23b180-3f49-11e9-94d3-320aeaebf415.png)

When I've used other options in the `<email_alerts>` section like `<level>` or `<event_location>` it has worked for me.

**Comment by DaveVG1** [comment]
This bug happens if no `email_to` is configured in `global` regardless of the `group` configuration. The solution is in the PR above.

**Comment by albertomn86** [comment]
Merged
