### ISSUE TITLE
Disconnecting agent when receiving shared Configuration

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#2746]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.7.2 | Agent | Packages |Microsoft Windows Server 2016 Standard [Ver: 10.0.14393] |

This agent keep disconnecting after receiving the following shared configuration : 

![sharedconf](https://user-images.githubusercontent.com/16334770/53816431-d9ce5100-3f63-11e9-8654-9675603dab31.png)

In the logs the error that preceded the agent shutdown is : 

`2019/03/01 18:49:40 ossec-agent: ERROR: Unable to read vista security descriptions.`

From the error it seems that it is complaining about this file **vista_sec.txt**, Although the file exist and with correct permission and has been updated by its latest version https://github.com/wazuh/wazuh/blob/3.9/src/win32/vista_sec.txt .

The only way to make this agent keep reporting and active was to remove the shared configuration.

More debug logs here for further investigation : 

```
2019/03/04 16:08:15 ossec-agent: INFO: (4102): Connected to the server (x.x.x.x:1514/udp).
2019/03/04 16:08:15 wazuh-modulesd:syscollector: INFO: Module started.
2019/03/04 16:08:15 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2019/03/04 16:08:15 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2019/03/04 16:08:15 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2016 Standard [Ver: 10.0.14393] - Wazuh v3.7.2).
2019/03/04 16:08:15 ossec-agent: ERROR: Unable to read vista security descriptions.
2019/03/04 16:08:15 ossec-agent: INFO: (1314): Shutdown received. Deleting responses.
2019/03/04 16:13:14 ossec-agent[19628] win_agent.c:155 at local_start(): DEBUG: Reading agent configuration.
2019/03/04 16:13:14 ossec-agent[19628] win_agent.c:169 at local_start(): INFO: Using notify time: 10 and max time to reconnect: 60
2019/03/04 16:13:14 ossec-agent[19628] win_agent.c:172 at local_start(): DEBUG: Reading logcollector configuration.
2019/03/04 16:13:14 ossec-agent[19628] config.c:194 at ExecdConfig(): DEBUG: Added CA store 'wpk_root.pem'.
2019/03/04 16:13:14 ossec-agent[19628] win_execd.c:86 at WinExecd_Start(): INFO: Started (pid: 19628).
2019/03/04 16:13:14 ossec-agent[19628] win_agent.c:220 at local_start(): INFO: (1410): Reading authentication keys file.
2019/03/04 16:13:14 ossec-agent[19628] msgs.c:79 at OS_StartCounter(): DEBUG: OS_StartCounter: keysize: 1
2019/03/04 16:13:14 ossec-agent[19628] msgs.c:121 at OS_StartCounter(): DEBUG: No previous counter available for 'McAfee_Server'.
2019/03/04 16:13:14 ossec-agent[19628] msgs.c:135 at OS_StartCounter(): DEBUG: Assigning counter for agent McAfee_Server: '0:0'.
2019/03/04 16:13:14 ossec-agent[19628] msgs.c:130 at OS_StartCounter(): DEBUG: Assigning sender counter: 0:15
2019/03/04 16:13:14 ossec-agent[19628] msgs.c:145 at OS_StartCounter(): DEBUG: Stored counter.
2019/03/04 16:13:14 ossec-agent[19628] start_agent.c:85 at connect_server(): INFO: Trying to connect to server (x.x.x.x:1514/udp).
```

**Comment by Skeptor** [comment]
I hasn't been capable of reproduce the issue with the same agent configuration.
Talking with @elwali10 the issue has been solved in the agent deleting the fields `realtime` and `report_canges` from the syscheck configuration.
We dont know the content of `D:\Mcafee_ePO` so my guess is the directory is too big that Wazuh agent runs out of memory if the option `report_changes` is enabled. That's why it can't create the Hash table for the Windows Vista security descriptions.
