### ISSUE TITLE
Rootcheck 'Scan On Start' Delay Feature

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#2749]
|3.8.2|Windows Agents|

Hello,

I've created a custom Rootcheck signature (p:!scanhost.exe;) for checking if our Anti-Virus process is running on the Windows systems, and we've had a few false positives show up.

My thought on this is that the Rootcheck might be running on system startup faster than the AV process is starting up. Is there any way to add a small delay to when Rootcheck runs on system reboot?

Thanks!

**Comment by TJOSERAFAEL** [comment]
Hi @Justangatang ,

sure we could add this feature into our roadmap. I'm going to open a feature request.
Thank you for sharing your use case and experience!

Best regards.

**Comment by TJOSERAFAEL** [comment]
Hi @Justangatang ,

the enhancement issue is ready, you can follow the development https://github.com/wazuh/wazuh/issues/2786 here.

Best regards.

**Comment by jesusjimsa** [comment]
Hello.

As we opened another issue to solve this problem, I'm closing this one. You can follow the progress in #2786.

Best regards,
Jesús.
