### ISSUE TITLE
aws-s3 wodle use first bucket key to start the iteration not last key

### ISSUE THREAD

**Issue by gurkavcu** [wazuh/wazuh#2753]
### Improvement 

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 to the 3.9.3 | Manager | Packages | RH7 |

aws-s3 wodle use first bucket key to start the iteration not last key as mentioned in the below query:

```python
        self.sql_find_last_key_processed = """
                                        SELECT
                                            log_key
                                        FROM
                                            {table_name}
                                        WHERE
                                            bucket_path='{bucket_path}' AND
                                            aws_account_id='{aws_account_id}' AND
                                            aws_region = '{aws_region}'
                                        ORDER BY
                                            log_key ASC
                                        LIMIT 1;"""
```

Updating order by case to "ROWID DESC" can prevent unnecessary database checks for already processed logs. If I'm not mistaken, this will accelerate the iteration.

**Comment by druizz90** [comment]
Hi @gurkavcu,

Thank you for your collaboration. Your proposal make sense, but we have to do that because AWS does not store keys by lexicographical order:

![1](https://user-images.githubusercontent.com/32929872/53862809-c9ac8500-3fe8-11e9-84f4-600f284f525e.png)

We talk about it in #1367.

Best regards,

Demetrio.
