### ISSUE TITLE
Make the Windows installer to choose between eventlog and eventchannel

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2760]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3907 | Agent | Packages/Sources | Windows |

For now, the default `ossec.conf` for Windows set the `eventlog` format for System and Application channels. https://github.com/wazuh/wazuh/blob/3.9/src/win32/ossec.conf#L31

By default, the `eventchannel` format should be set for every monitored channel. For Windows versions without Eventchannel support (older than Vista), the installer has to notice that fact and set the `eventlog` format for monitored channels.

**Comment by chemamartinez** [comment]
Issue status:

**Comment by chemamartinez** [comment]
Task list:

- [ ] Install the `ossec.conf` regarding the Windows platform (pre/post Vista)

- [ ] Set the correct configuration for each version of the `ossec.conf` for Windows log channels.

- [ ] Clean `ossec.conf` templates from default configuration which cause errors in fresh installations.

- [ ] Design a template mechanism for installing custom templates for every Windows platform.

**Comment by branchnetconsulting** [comment]
Please make sure the Wazuh ruleset has full coverage for the Windows logs that were still defaulting to eventlog and are now defaulting to eventchannel format.  It will be good to default to 100% eventchannel on Windows systems with support for it.

**Comment by chemamartinez** [comment]
The remaining task for finishing this issue will be implemented in next iterations. [Here](https://github.com/wazuh/wazuh/issues/2811) can be tracked.

@branchnetconsulting let continuous this topic about the ruleset at this issue: https://github.com/wazuh/wazuh-ruleset/issues/310. It has been separated the ruleset for eventlog format and eventchannel format. The first one contains the same rules as ever, for the eventchannel format we are designing and creating new rules to cover all the possibilities.

Regards.
