### ISSUE TITLE
Enable Wazuh optional components by default

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2762]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager/Agent | Packages/Sources | All |

Historically, for using certain modules it is necessary to enable them by using the `ossec-control` tool. 

```
# ossec-control enable

Enable options: database, client-syslog, agentless, debug, integrator
Usage: /var/ossec/bin/ossec-control enable [database|client-syslog|agentless|debug|integrator]
```

This is an impediment to enable them from the Wazuh APP when updating the configuration file due to they won't launch and read the configuration for starting to work if are not enabled previously in the CLI.

It is necessary to enable by default those modules and, when starting the manager, turn off those that are not enabled in the configuration file.

### List of issued modules

- [x] _integratord_

- [x] _database_

- [x] _client-syslog_

- [x] _agentless_

**Comment by TJOSERAFAEL** [comment]
Hi @chemamartinez,

this PR https://github.com/wazuh/wazuh/pull/2769 solves the issue.

Regards.
