### ISSUE TITLE
Docker wodle works as usual when attempts field has an invalid value

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#2768]
|Wazuh version|Install type
|---|---|
| 3.9.0-3907 | Agent |

Bug report
----
While configuring the docker wodle (`<wodle name="docker-listener">`):
- If an invalid value is assigned to the `attempts` field the module works as usual.
- It should log an **ERROR** and stop (like it happens if an invalid value is assigned to `disabled`, `run_on_start` or `interval`) or at least, it should log a **WARNING** and continue.

**Comment by Leamsy** [comment]
I just fixed the issue here: 37bcb1f. 

It was using `strtoul()` to translate the attempts string, which turns everything in the string into an integer, turning invalid values into valid ones. The solution was switching it with `atol()`, which only translates numeric values.
