### ISSUE TITLE
oscap.py fail on Debian Stretch

### ISSUE THREAD

**Issue by EdLeforestier** [wazuh/wazuh#277]
On Debian stretch oscap.py return an error:

root@debian9:/# /var/ossec/wodles/oscap/oscap.py --xccdf /var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml
Traceback (most recent call last):
  File "/var/ossec/wodles/oscap/oscap.py", line 370, in <module>
    oscap(profile)
  File "/var/ossec/wodles/oscap/oscap.py", line 100, in oscap
    temp = mkstemp()
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: 'tmp/tmpWKsF4P'

**Comment by PSanchezR** [comment]
Hi @EdLeforestier,
 Can you try to run oscap.py from "/var/ossec" path?. The problem is that oscap.py are using relatives paths and it is necessary to execute it from "/var/ossec/".

Best regards.

**Comment by EdLeforestier** [comment]
Hi PSanchezR, Thanks for the reply

Ok, from /var/ossec it run perfectly.
But agent run : 
wazuh-modulesd:oscap: DEBUG: Launching command: /var/ossec/wodles/oscap/oscap.py --xccdf ssg-debian-8-ds.xml

Is there a way to config agent to run oscap.py from /var/ossec/ ?

Best regards.

**Comment by PSanchezR** [comment]
Hi @EdLeforestier,

wazuh-modulesd by default runs oscap.py in a context with path /var/ossec as a root path, so if it is the process that runs oscap.py the script will work properly.

Best regards.

**Comment by EdLeforestier** [comment]
Hi PSanchezR,

Thanks for your time, this issue can be closed. Solved
