### ISSUE TITLE
Wazuh manager - frequency counter

### ISSUE THREAD

**Issue by soulmaster43** [wazuh/wazuh#2771]
|Wazuh Manager 3.8.2 | Installed from RPM & Source |  Amazon Linux 2 4.14.97-90.72.amzn2.x86_64|

Hi,

I noticed a problem with the wazuh alerting rules.
Take the rule listed below:

$MS_FREQ=8

<rule id="18152" level="10" frequency="$MS_FREQ" timeframe="240">
    <if_matched_group>win_authentication_failed</if_matched_group>
    <same_user />
    <description>Multiple Windows Logon Failures.</description>
    <group>authentication_failures</group>
 </rule>

The rule will keep triggering after 8 windows logon failures, meaning the frequency counter does not reset.
One would expect for the alert counter to go back to 0 and then start to increment, meaning that an alert will be raised every 8 failed login failures not starting with 8 login failures.
This does not happen in ossec. Ossec will trigger the rule very 8 occurrences.
I believe the problem lies in the <same_user /> condition.
I've tested this with several rules involving the same user and got the same behavior.

Is this something you can fix in 3.8.2 ? 

Thank you.

L.E: Same problem with wazuh-manager 3.9

**Comment by Leamsy** [comment]
Hi @soulmaster43,

I have checked it, and there is indeed an issue when using the `same_user` parameter, as when it is in use, the frequency option works in unintended ways. I have already opened an issue #2850 and it should be fixed soon.

Thanks for your input.

Regards.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/2854.

Best regards.

**Comment by chemamartinez** [comment]
Hi @soulmaster43,

Let me close this issue since it has been fixed at #2854 and will be available in the next released version. Thank you for reporting this undesired behavior.

Regards.
