### ISSUE TITLE
FIM doesn't report alerts if check_inode is disabled

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#2779]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| From 3.8.0 | Manager/Agent | Packages/Sources | Linux |

Hi team, 

If we have the following configuration:

```xml
<directories check_all="yes" check_inode="no">/path/to/folder</syscheck>
```

FIM does not report any alerts in `frequency`, `realtime` or `whodata`. This occurs because we use the `str_inode` to insert the inode inside the hash table `inode_hash` and this contains `\0` as we can see here:

https://github.com/wazuh/wazuh/blob/d1528e5577c0b0289d5285f1f1b9e7e3781342e9/src/syscheckd/create_db.c#L449-L461

Therefore, all the scanned files will have the same inode, which produces a duplication error when trying to add this entry into the hash table. This causes the alert not to be generated.

Regards,
Cerv1.

**Comment by albertomn86** [comment]
Solved in https://github.com/wazuh/wazuh/pull/2813
