### ISSUE TITLE
Unexpected behavior when generating deletion alerts on frequency scans

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2782]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| From 3.8.0 | Manager/Agent | Packages/Sources | Linux/Windows |

### Use case
FIM in frequency scans, monitoring a directory in which a file is moved from one directory to another.

### Problem

When the deletion alert is generated, **the hash table entry of inodes is not being removed**, which causes unexpected behavior.

The following message appears in the subsequent scan:

>Inode already added to db: /root/test/folder2/file1 (2621896)

When moving the file between directories what is produced is a deletion of a file, the inode disappears for the operating system, and another file is generated in another directory that obtains the same inode as the previous one, discarding the alert.

### Solution

At this point we need to delete inode hash entry:
https://github.com/wazuh/wazuh/blob/3.8/src/syscheckd/create_db.c#L956

Considering that if the `check_inode` option is set to no, we cannot get the inode in the checksum. We have to look for the path in the hash table of inodes.

**Comment by albertomn86** [comment]
Solved in https://github.com/wazuh/wazuh/pull/2813
