### ISSUE TITLE
Wazuh agents not auto negotiating TLS, Windows 7, Wazuh 3.7.2

### ISSUE THREAD

**Issue by shortstack** [wazuh/wazuh#2789]
have a 2 node wazuh cluster running version 3.7.2

deploying agents to windows 7 and windows server 2012 via ansible

have tried running all of the following to auth:

this command output says that the "option requires an argument -- a", i did what's in the documentation. i stopped ossec-authd and re-ran it as "ossec-authd -a" (is there a cleaner way to configure that other than killing the process and rerunning it?), and i also set ssl_auto_negotiate to yes on both of the wazuh nodes in ossec.conf, restarted. still getting the "option requires an argument" message.
```
.\agent-auth.exe -m wazuh-master.domain.com -p 1515 -P mysekritpassword -a
```

when i just run this one, it just says SSL error, wrong version, etc
```
.\agent-auth.exe -m wazuh-master.domain.com -p 1515 -P mysekritpassword 
```

do i need to use an older agent? have never had this issue on older versions of wazuh. tried several older versions of the agent, and get this continuously flooding the log.

```
2019/03/08 14:16:22 agent-auth: WARNING: Unexpected status (0x80090308).
2019/03/08 14:16:22 agent-auth: WARNING: Unexpected status (0x80090308).
2019/03/08 14:16:22 agent-auth: WARNING: Unexpected status (0x80090308).
2019/03/08 14:16:22 agent-auth: WARNING: Unexpected status (0x80090308).
2019/03/08 14:16:22 agent-auth: WARNING: Unexpected status (0x80090308).
```

**Comment by vikman90** [comment]
Hi @shortstack,

I wonder if you are running the version 3.7.2 or higher of Wazuh Agent for Windows.

The manager includes its own version of OpenSSL, that supports TLSv1.2. On the other hand, the agent for Windows relied the connection security (SSL/TLS) on the operating system library until v3.7.2. We moved to OpenSSL in v3.7.2.

In other words, the old agent for Windows (below v3.7.2) supported TLS if the OS supports it. This depends on the OS version and the security updates installed. In these cases, enabling auto-negotiate and expanding the cipher list may help:

```xml
<auth>
   <ciphers>ALL</ciphers>
  <ssl_auto_negotiate>yes</ssl_auto_negotiate>
</auth>
```

The option `-a` has the same effect as `<ssl_auto_negotiate>yes</ssl_auto_negotiate>`, but it's not available on Windows until v3.7.2.

Please confirm us what version of Wazuh agent you're using on Windows. If it's below 3.7.2, I recommend you upgrade if possible, or try the configuration above in the manager.

Hope it helps.
Best regards.

**Comment by shortstack** [comment]
added ciphers ALL to both nodes, restarted wazuh-manager on both

tried to auth the same way as before, with and without the "-a", same results

tried 3.7.2, and 3.8.0

**Comment by shortstack** [comment]
bottom line, what version of the agent on windows 7 will work 3.7.2 manager or 3.8.0 manager?

**Comment by vikman90** [comment]
Hi,

Since I think that this issue is caused by an old version of the agent, you need a Wazuh Agent for Windows version 3.7.2 or higher, so the following options are fine:

- Agent 3.7.2 and manager 3.7.2.
- Agent 3.7.2 and manager 3.8.0.
- Agent 3.8.0 and manager 3.8.0.

In conclusion, the manager must have the same version or higher than the agent.

Best regards.

**Comment by shortstack** [comment]
i've got manager 3.8.0 running.

i'm unable to find the 3.8.0 exe for the agent for windows, could only find 3.8.2.

installed the 3.8.2 agent, windows 7, ran the above commands that are in original issue, and getting exact same results.

**Comment by shortstack** [comment]
<img width="1002" alt="Screenshot 2019-03-09 15 51 12" src="https://user-images.githubusercontent.com/1244979/54077211-989bb100-4283-11e9-9f42-a297de4909df.png">
<img width="341" alt="Screenshot 2019-03-09 15 51 42" src="https://user-images.githubusercontent.com/1244979/54077212-989bb100-4283-11e9-8acd-13df9f7105a9.png">
<img width="673" alt="Screenshot 2019-03-09 15 51 54" src="https://user-images.githubusercontent.com/1244979/54077213-989bb100-4283-11e9-9d8e-34d54e0a90b3.png">
<img width="859" alt="Screenshot 2019-03-09 15 52 55" src="https://user-images.githubusercontent.com/1244979/54077214-989bb100-4283-11e9-91dd-c080956d0e92.png">

**Comment by cristgl** [comment]
Hello @shortstack, 

You are right, this is a bug, the option '-a' was not being passed correctly to the function in charge of checking the arguments passed to `agent-auth`, as it was being considered that this option required an argument. This has been fixed for Wazuh v3.9.0 at https://github.com/wazuh/wazuh/pull/2808

Best regards,
Cristina

**Comment by shortstack** [comment]
Thank you!

One more question -- will older versions of the agent that are already deployed on endpoints, 3.2.3, 3.3.1, continue to work with Wazuh if I upgrade the manager to 3.8.0?

**Comment by cristgl** [comment]
Hello @shortstack,

We are trying to reproduce the SSL error you encountered while trying to register an agent, could you please give us some more information? Do you have the same SSL or TLS version in both, Windows agents and linux manager? Have you been trying to use [host verification](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html?highlight=ssl#host-verification-using-ssl)?

About your last question, yes, they should work, the only thing necessary is that the manager version is equal or higher than the agents, if you have Wazuh v3.8 they should totally work.

Best regards,
Cristina

**Comment by shortstack** [comment]
Not using host verification

Where do I find the version for the agents?

Thanks so much!

**Comment by cristgl** [comment]
Hi @shortstack,

The following line will show you which SSL and TLS versions are enabled at a Linux system:

```
openssl ciphers -v | awk '{print $2}' | sort | uniq
```

For Windows 7, you will have to search for 'Internet Options' at the Windows main menu. When the new window pops up, go to the 'Advanced' tab, there you can verify which SSL and TLS versions are enabled.


Best regards,
Cristina
