### ISSUE TITLE
Let Logcollector filter files by date

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#2799]
Logcollector allows defining log locations with wildcarded patterns, so we can define files by name. However, Logcollector should allow filtering files by date:

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/var/log/*.log</location>
  <age>1d</age>
</localfile>
```

`<age>` shall discard every file that has not been written during the defined time.

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90 ,

this branch https://github.com/wazuh/wazuh/tree/3.9-logcollector-date has the implementation done for Linux and Windows.

Valid values for `<age>` label:

- Days        `<age>1d</age>`
- Weeks     `<age>1w</age>`
- Hours      `<age>1h</age>`
- Minutes   `<age>1m</age>`
- Seconds  `<age>1s</age>`

Logcollector will ignore files older than the speficied `age`.

**Comment by TJOSERAFAEL** [comment]
Hi @vikman90 ,

now the file descriptors are closed when the files get ignored by age.
Commit: https://github.com/wazuh/wazuh/commit/d7dc46ec95d199ba018ebcf3e464ddb3b18e9ded

Regards.

**Comment by TJOSERAFAEL** [comment]
Merged at https://github.com/wazuh/wazuh/pull/2929
