### ISSUE TITLE
Wazuh rulset vs Oscap Security Guide

### ISSUE THREAD

**Issue by EdLeforestier** [wazuh/wazuh#281]
Hi,

Question: 
I'm really interested by some oscap scurity guide profiles (https://github.com/OpenSCAP/scap-security-guide), is there a way to integrate specific profile in wazuh rulset ?

**Comment by chemamartinez** [comment]
Hi @EdLeforestier ,

In the ``scap_content`` folder of Wazuh Ruleset there are included the Oscap Security Guide profiles from the project you means.

You are able to use any of those policies however you want while they are compatible with the OpenScap scanner.

Let me know if you have any question about that.

Best regards.
