### ISSUE TITLE
SCA checks: "process" column isn't filled in database and wrong compliance values

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2810]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3908 | Manager | Packages | Ubuntu 18 |

---

The `process` column in SCA checks database isn't being correctly filled. For example, the following check should include a process value:
https://github.com/wazuh/wazuh/blob/5b27cac1f8ab1ee01ef5f996150354e877f74703/etc/sca/debian/cis_debian_linux_rcl.yml#L254-L267
But in the database row it doesn't:
```sql
sqlite> select title,process,result from sca_check where title like "%inetd%";
Ensure inetd is not installed||failed
```
I have the same issue with the `registry` column.

Also, the compliance values are wrong, for example, instead of `9` it should be `9.2`:
```sql
sqlite> select * from sca_check_compliance where key="cis_csc";
5000|cis_csc|5
5001|cis_csc|5
5002|cis_csc|5
5003|cis_csc|5
5004|cis_csc|5
5005|cis_csc|5
5006|cis_csc|5
5007|cis_csc|5
5008|cis_csc|5
5009|cis_csc|5
5010|cis_csc|5
5011|cis_csc|5
5012|cis_csc|5
5013|cis_csc|5
5014|cis_csc|5
5016|cis_csc|5
5017|cis_csc|5
5015|cis_csc|5
5018|cis_csc|9
5019|cis_csc|9
5020|cis_csc|9
5021|cis_csc|9
5022|cis_csc|9
5023|cis_csc|9
5025|cis_csc|9
5026|cis_csc|9
5024|cis_csc|9
5027|cis_csc|9
5029|cis_csc|2.6, 4.5
5028|cis_csc|9
5030|cis_csc|2.6, 4.5
5031|cis_csc|5
5032|cis_csc|5
5033|cis_csc|5
5034|cis_csc|14
5035|cis_csc|9
5037|cis_csc|4
5036|cis_csc|16
5038|cis_csc|16
5040|cis_csc|5
5039|cis_csc|4
```

**Comment by TJOSERAFAEL** [comment]
Hi @mgmacias95 

this PR https://github.com/wazuh/wazuh/pull/2805 solves the issue.

As for the empty process value, this is a normal behavior because if the process doesn't exists, it's path is unknown. Inherited from the rootcheck default implementation. 

We need the clarify this use case and change it if it necessary.
