### ISSUE TITLE
Design a template mechanism for installing custom templates for every Windows platform.

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#2811]
The goal is to install a custom basic configuration for every Windows platform to avoid errors at starting Wazuh agent.
At this moment, the syscheck configuration for Windows contains all the registers to cover all the Windows platforms. If we could install a custom ossec.conf for every Windows platform as it is done in Linux we can reduce the useless configuration and add exclusive checks for the platforms

**Comment by chemamartinez** [comment]
We are working on https://github.com/wazuh/wazuh/issues/3912 to solve this issue.
