### ISSUE TITLE
Correlate feeds to add a severity to Debian alerts

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2812]
Vulnerability-detector always adds _Unknown_ in the severity field of Debian alerts. This is because Debian's OVAL does not include this information. 

In these cases, it could be correlated with the NVD database to obtain the severity of these vulnerabilities.

Related issue https://github.com/wazuh/wazuh/issues/2430.

**Comment by snaow** [comment]
Work in progress.
Closed in favor of https://github.com/wazuh/wazuh/issues/4749
