### ISSUE TITLE
Wazuh behavior of the multiple grouping rules that inherit from the same base rule

### ISSUE THREAD

**Issue by MrRubi** [wazuh/wazuh#2819]
Hello,

Recently I've been upgrading wazuh 1.1.1 to wazuh 3.8.2. One of the tests I'm performing is to check the wazuh behaviour regarding the multiple rules agrupations (that is same_source_id, same_id, etc).  that inherits form the same base rule 

What does this mean?

For example I have the following group rule:

    <group name="test,">
      <rule id="190001" level="0">
        <decoded_as>Test</decoded_as>
        <description>Test</description>
      </rule>
    
     
      <rule id="190501" level="5">
        <if_sid>190001</if_sid>
        <match>admin</match>
        <description>Base rule</description>
      </rule>
    
    
      
    
      <rule id="19502" level="10" frequency="3" timeframe="500">
        <if_matched_sid>190501</if_matched_sid>
        <same_source_ip />
        <description>Test multiple same origin IP</description>
      </rule>
    
      <rule id="19504" level="10" frequency="4" timeframe="500">
        <if_matched_sid>190501</if_matched_sid>
        <same_id />
        <description>Test multiple same ID</description>
      </rule>
    
    </group>

The tests I'm performing are the following ones (modifying the level of the 19502 and 19504 rules accordingly):

 1. Check what happens to a high-level rule when a lower rule is triggered
 2. Check what happens to a low-level rule when a higher rule is triggered
 3. Check what happens to a rule when a same-level rule is triggered

I have the results for the cases 1 and 2. But the behaviour with the case 3 is quite random, I can not found a common pattern.

In the first case, when a low-level rule is triggered it doesn't affect to the higher rules counter.
When a high-level rule is triggered it resets the counter of the lower rules

Anyone know the behaviour in the third case?

I've been doing a lot of tests and I haven't been able to came to a conclusion.

**Comment by DaveVG1** [comment]
I've discovered a bug while checking out this issue (it is related to the question you've made). I've opened an issue about it #2870

**Comment by jesusjimsa** [comment]
Hello.

As we opened another issue to solve this problem, I'm closing this one. You can follow the progress in #2870.

Best regards,
Jesús.
