### ISSUE TITLE
Decoder <regex> doesn't work correctly

### ISSUE THREAD

**Issue by CorraMatte** [wazuh/wazuh#2834]
Hello team,
I was working on a custom decoder and I had some troubles with the regex.

The monitored command generates the following output:

`ram-usage: 021 SRV_SDG_SEC 94`

So I created the following decoder to capture 3 groups (agentid, name, used) with the regex:

```
<decoder name="ram-usage">
    <prematch>^ram-usage: </prematch>
    <regex offset="after_prematch">([0-9]+) (\S+) ([0-9]+)</regex>
    <order>agentid, name, used</order>
</decoder>
```
that actually is correct (verified on https://regexr.com/).
But testing with `/var/ossec/bin/ossec-logtest` it doesn't caputer the groups.

Instead, the following decoder works properly and catches all the groups:

```
<decoder name="ram-usage">
    <prematch>^ram-usage: </prematch>
    <regex offset="after_prematch">(\S+)\s*\t*(\S+)\s*\t*(\S+)</regex>
    <order>agentid, name, used</order>
</decoder>
```

Is it the first regex still wrong for some reason?
As I said, I tried it and it should work correctly.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager| Packages| CentOS Linux release 7.6.1810 (Core) |

**Comment by DaveVG1** [comment]
Hi,

The regex syntax you should use for custom decoders is described in: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html

In this case, the decoder you need would look like this:
```
<decoder name="ram-usage">
    <prematch>^ram-usage: </prematch>
    <regex offset="after_prematch">(\d+) (\w+) (\d+)</regex>
    <order>agentid, name, used</order>
</decoder>
```
You can also check the following link for more examples of custom decoders and rules:
https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

Regards,
David

**Comment by CorraMatte** [comment]
Thanks David, this solves my problem.
