### ISSUE TITLE
Remote upgrade with different application folder

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#2853]
Hello, when I first installed an agent on a windows machine I chose a different application folder than the default ossec-agent folder. I've upgraded my wazuh server in my test environment and I wanted to do a remote upgrade, the problem is that the remote upgrade uses a wpk that installs the agent in the default ossec-agent folder, so the upgrade actually installs the new version but the old one remains in the previous folder. 
I tried to play around with the do_upgrade.ps1 script so maybe I could create my own wpk that installs it in my custom folder, the line that installs the agent is:
`cmd /c start (Get-Item ".\wazuh-agent*.msi").Name -quiet -norestart -log installer.log`
I thought that maybe I could add the APPLICATIONFOLDER property but I keep on getting the wrong msi parameters error.
`cmd /c start (Get-Item ".\wazuh-agent*.msi").Name -quiet -norestart -log installer.log APPLICATIONFOLDER="C:\Program Files (x86)\custom_folder"`
I also tried using msiexec.exe but the only way it works for me is when I give the property directly to the msi:
`wazuh-agent-3.8.2-1.msi APPLICATIONFOLDER="<custom folder>"`
Does anyone know how can I do this?

Thanks in advance!

**Comment by DaveVG1** [comment]
Hi,

This is actually a known bug (#2494) which has been fixed (#2532). It'll be available from 3.9 agents and up which means you will be able to update Wazuh agent remotely in a non-default installation folder if you have a 3.9 or higher Windows agent.

Regards,
David

**Comment by DaveVG1** [comment]
Hi again @agentsofshield 

As this bug has been fixed for 3.9. I'm going to close this issue. Please, feel free to re-open it if you have any question/trouble regarding this topic.

Thanks for reporting this.

Kind regards.

**Comment by agentsofshield** [comment]
It seems the solution you gave me was not included in 3.9 as it is still awaiting review.

**Comment by DaveVG1** [comment]
Hi again,

I'm going to reopen this issue as you're right, it didn't make it to 3.9. Nonetheless, it's going to be included in next versions (if not next which is tentatively 3.9.1).

I'll let you know as soon as this is available. Remember this will work with future Wazuh agents (upgrades from an agent which has this fix to another that has it too). Sorry for the inconvenience.

Kind regards,
David

**Comment by snaow** [comment]
Hi @agentsofshield,

Thanks for reporting the issue and sorry for the inconveniences caused.

I hope you don't mind to track the status in the following related issue: https://github.com/wazuh/wazuh/issues/2494

The proposed change in the above issue can affect the current MSI installation and upgrades, we need some time to evaluate the solution and make sure it is truly effective.

Please, feel free to comment and track the progress in the above issue.
Closing the issue.
