### ISSUE TITLE
Broken multigroup after add an unsupported file to the merged file

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#2862]
In the case that an unsupported file is in the folder `shared` of a group, for example an excel file, `ossec-remoted` gives the following error:
```
2019/03/19 16:26:16 ossec-remoted: ERROR: Incorrect message size: 0
2019/03/19 16:26:16 ossec-remoted: ERROR: (1217): Error creating encrypted message.
2019/03/19 16:26:16 ossec-remoted: WARNING: (1246): Unable to send file 'merged.mg' to agent ID '005'.
```
After that, every multigroup that contain the "corrupted" group can't be used because the manager can't add the multigroup to the Hash table.
```
2019/03/19 16:58:37 ossec-remoted[24650] manager.c:537 at c_files(): DEBUG: Updating shared files sums.
2019/03/19 16:58:37 ossec-remoted[24650] manager.c:698 at c_files(): DEBUG: Couldn't add multigroup 'default,g1,g2' to hash table 'm_hash'
2019/03/19 16:58:38 ossec-remoted[24650] manager.c:771 at c_files(): DEBUG: End updating shared files sums.
```
Even if the unsupported file is deleted, the manager can't delete the corrupted merged file and the group stay useless because the merged can't be updated.

**Comment by Skeptor** [comment]
Research on the issue:
When an invalid file is in a group folder, the manager tries to dump his content into the file `merged.mg`. This cause a corrupted `merged.mg` that can't be sent to the agents. Also, the invalid file is copied to all the multigroups where the group belongs, which leads the multigroups to the same corrupted state that the group has.

Solution:
Check if a file is valid before dumping it in the `merged.mg`. In the case that the file is invalid it is added to a list of invalid files and it is ignored. When a file is ignored it isn't written in the `merged.mg` and it is not sent to the multigroups to preserve the integrity of the multigroups.

**Comment by chemamartinez** [comment]
This is the development plan:

- Every candidate file to be merged will be checked before merging it to know if it is a valid file.

- When an invalid file is found, an error message is logged and the file is stored into a hash table including its last modification time.

- That table will be consulted in every rebuilt of the merged file. If a file is found in the hash table, we have to check if the modification time of the file has changed, if so, we consider it has been fixed, so it is removed from the hash table and retry to append it again to the merged file hoping that now it is valid.

- If the file is still invalid, it will be readded to the hash table and ignored.

**Comment by Skeptor** [comment]
The development branch is: https://github.com/wazuh/wazuh/tree/fix_corrupted_merged
It contains a commit where the corrupted files are discarded from being dumped in the `merged.mg` and from being moved to the multigroups.
Also they are added to a Hash table to avoid the error log flood in the case that the file isn't changed.
