### ISSUE TITLE
Real time events moving files or directories

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2863]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Agent | Packages/Sources | Linux |

Hi team, 

We have found a problem with the data stored in the hash table that controls the directories monitored with real-time. 

In case of moving a directory that has an active _inotify watch_, the path stored in that table is not updated, but both the id of the watches and the descriptor of the folder are maintained.

If the path is not updated is generated using the previous folder.

In this line is composed the path with the content of the hash table and the element that triggered the callback.

https://github.com/wazuh/wazuh/blob/master/src/syscheckd/run_realtime.c#L339 

To fix this problem we have to update the path in these cases.

**Comment by jesusjimsa** [comment]
To check what causes this, the following function can be used:
```c
void print_dirtb() {
    OSHashNode *hash_node;
    char *data;
    unsigned int inode_it = 0;
    int i = 0;

    if(syscheck.realtime->fd) {
        w_mutex_lock(&syscheck.fim_entry_mutex);
        hash_node = OSHash_Begin(syscheck.realtime->dirtb, &inode_it);
        while(hash_node) {
            data = hash_node->data;
            minfo("dirtb(%d)(%d) => (%s)'%s'", i, inode_it, (char*)hash_node->key, (char*)data);
            hash_node = OSHash_Next(syscheck.realtime->dirtb, &inode_it, hash_node);
            i++;
        }
        w_mutex_unlock(&syscheck.fim_entry_mutex);
    }
    
    return;
}
```
And placing it at the end of the `realtime_adddir` function, just before this return:
https://github.com/wazuh/wazuh/blob/2ccb1f40b2d123933964bfd3763e7beb60c29bc9/src/syscheckd/run_realtime.c#L127-L128

**Comment by jesusjimsa** [comment]
The _inotify watches_ are not being freed when the monitored folder is moved from its original route, for example:
1. `/test` is monitored
    * `/test` and its subfolders get a _watch_
2. `/test` is renamed as `/test1`
    * `/test1` does not have _watches_ (as it should) but `/test` keeps its _watches_ despite not existing

This does not happen when removing the folder. Removing `/test` deletes all of its _watches_.

The solution will be to delete the _watches_ of those folders that don't exist in case they still have one.

**Comment by jesusjimsa** [comment]
The `errno` where a file/folder does not exists is `2`, so adding a case with `errno == 2` in this `if` statement where the directory hash and its subdirectories hashes are deleted will solve this issue.

https://github.com/wazuh/wazuh/blob/2ccb1f40b2d123933964bfd3763e7beb60c29bc9/src/syscheckd/run_realtime.c#L95-L101

**Comment by jesusjimsa** [comment]
The fix is actually related to the type of event. The `IN_MOVE_SELF` event needs to be added here:

https://github.com/wazuh/wazuh/blob/2ccb1f40b2d123933964bfd3763e7beb60c29bc9/src/syscheckd/run_realtime.c#L43

Also, to delete all the watches a folder contains, we need to modify this switch statement:

https://github.com/wazuh/wazuh/blob/2ccb1f40b2d123933964bfd3763e7beb60c29bc9/src/syscheckd/run_realtime.c#L184-L191

We need to add the `IN_MOVE_SELF` event to the switch statement and check all the entries in the hash table that begin by the moved directory plus a an extra slash. For example, if the monitored folder is `/test`, we will need to check all the entries in the hash table and delete those that start with `/test/`. This way, we will not delete from the hash table folder like `/testfolder` or `/other/test`, which also contain `/test`.

**Comment by jesusjimsa** [comment]
We also need to add a debug message with the number of _watches_ at the end of the scan in order to make the integrity test.

**Comment by jesusjimsa** [comment]
Another case to have in mind is when the monitored folder in the `ossec.conf` file is `/test/`, here we won't need to add the extra slash.

**Comment by jesusjimsa** [comment]
Added debug message with number of inotify watches. It looks like this:
```
DEBUG: (6343): Folders monitored with inotify engine: 56
```

**Comment by jesusjimsa** [comment]
Fixed bug that caused `ossec-syscheckd` to stop executing when no folder was monitored in `realtime` mode.

**Comment by jesusjimsa** [comment]
## Unit tests cases
- [ ] `create_db.c:fim_scan() --> rt_active == true`
- [ ] `create_db.c:fim_scan() --> rt_active == false`
- [ ] `run_realtime.c:realtime_process() --> event->mask == IN_MOVE_SELF`
- [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> dir[strlen(dir) - 1] != '/'`
- [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> dir[strlen(dir) - 1] == '/'`
- [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> syscheck.realtime->fd == NULL`
- [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> syscheck.realtime->fd != NULL`
    - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> hash_node == NULL`
    - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> hash_node != NULL`
        - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> data == NULL`
        - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> data != NULL`
            - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> strncmp(dir_slash, data, strlen(dir_slash)) != 0`
            - [ ] `run_realtime.c:delete_subdirectories_watches(char *dir) --> strncmp(dir_slash, data, strlen(dir_slash)) == 0`
- [ ] `run_realtime.c:count_watches() --> syscheck.realtime->fd == NULL`
- [ ] `run_realtime.c:count_watches() --> syscheck.realtime->fd != NULL`
    - [ ] `run_realtime.c:count_watches() --> hash_node == NULL`
    - [ ] `run_realtime.c:count_watches() --> hash_node != NULL`

**Comment by jesusjimsa** [comment]
Finished `create_db.c` tests. Still working on tests for `run_realtime.c`.

**Comment by jesusjimsa** [comment]
Tests for `run_realtime.c` finished.

**Comment by jesusjimsa** [comment]
Added `count_watches` to Windows

**Comment by jesusjimsa** [comment]
After adding `count_watches` to Windows, the unit tests need to be changed.

**Comment by jesusjimsa** [comment]
## Unit test cases Linux
- [ ] `create_db.c:fim_scan()` ––> Just one case with debug message about inotify watches
- [ ] Delete tests that used `rt_active`

**Comment by jesusjimsa** [comment]
## Unit tests cases Windows
- [ ] `create_db.c:fim_scan()` ––> Just one case with debug message about inotify watches
- [x] `run_realtime.c:count_watches() --> syscheck.realtime->fd == NULL`
- [x] `run_realtime.c:count_watches() --> syscheck.realtime->fd != NULL`
    - [x] `run_realtime.c:count_watches() --> hash_node == NULL`
    - [x] `run_realtime.c:count_watches() --> hash_node != NULL`

**Comment by jesusjimsa** [comment]
Linux unit tests are ready, Windows unit tests still need to be finished

**Comment by jesusjimsa** [comment]
Windows unit tests also ready.
