### ISSUE TITLE
Realtime does not disable without reboot

### ISSUE THREAD

**Issue by joeyUalberta** [wazuh/wazuh#2864]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| X.Y.Z-rev | Manager/Agent | Packages/Sources | OS version |
|3.8.2|Agent|Packages/Sources|Ubuntu 18.04.1 LTS|

Initially, I have the realtime enabled on syscheck. However, if I disable it, and restart the wazuh-agent, the real-time monitoring will still run on the background. When I run lsof | grep inotify|grep ossec, it shows that it is still monitoring.

The real-time monitoring is disabled when the system is rebooted. lsof | grep inotify|grep ossec show nothing this time.

Local conf:
![image](https://user-images.githubusercontent.com/43220311/54644550-2f742480-4a5f-11e9-8f86-725a03490a3f.png)
Shared config:
![image](https://user-images.githubusercontent.com/43220311/54644595-47e43f00-4a5f-11e9-9cef-6799454db018.png)

**Comment by joeyUalberta** [comment]
Local config:
<syscheck>
    <disabled>no</disabled>
    <frequency>43200</frequency>
    <scan_on_start>yes</scan_on_start>
    <directories check_all="yes" realtime="no">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes" realtime="no">/bin,/sbin,/boot</directories>
........
Shred config: 
......
   <syscheck>
        <disabled>no</disabled>
        <frequency>4320000000</frequency>
        <scan_on_start>yes</scan_on_start>
        <directories check_all="yes" whodata="yes" realtime="no" report_changes="yes">/etc,/usr/bin,/usr/sbin</directories>
        <directories check_all="yes" whodata="yes" realtime="no" report_changes="yes">/bin,/sbin,/boot</directories>
        <directories check_all="yes" whodata="yes" realtime="no" report_changes="yes">/testDir/*/dirA</directories>
   </syscheck>
......

**Comment by Cerv1** [comment]
Hello @joeyUalberta,

I couldn't reproduce your issue. I've use the same configuration and, as you said, when `realtime` monitoring is enabled I get the following output:

```
# lsof | grep inotify | grep ossec

ossec-sys 19437             root    9r  a_inode        0,13       0      13695 inotify
ossec-sys 19437 19438       root    9r  a_inode        0,13       0      13695 inotify
ossec-sys 19437 19564       root    9r  a_inode        0,13       0      13695 inotify
```

Then, I've disabled the `realtime` option for all the directories in the `agent.conf` and after being pushed to the `wazuh-agent` (it restarts automatically) I've executed again the previous command. This was the output:
```
# lsof | grep inotify | grep ossec

```

As you can see, al the `inotify` watchers have been deleted. Could you please verify that the `wazuh-agent`was restarted after you changed the configuration?

Don’t hesitate to ask us for further information or help.

Best regards,
Cerv1.

**Comment by joeyUalberta** [comment]
Her Cerv1,

I tried it again. And you are right, it does remove the inotify watch.  I believe I was testing it too quick yesterday. After modifying the agent.conf, I restarted the wazuh manager, then wazuh agent. But it was done too quick, so the wazuh agent only got the agent.conf after it is restarted, so it is still using the config. Sorry for the inconvenience.
