### ISSUE TITLE
Incoherent error message when removing agents from API

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh#2865]
|Wazuh version|Install type|Install method|Platform|Authd|
|---|---|---|---|---|
| X.Y.Z-rev | Manager/Agent | Packages/Sources | OS version |Disabled|

---

Trying to remove agents having `authd` disabled can result in the following error:

```javascript
# curl -u foo:bar "localhost:55000/agents/001?pretty&purge" -XDELETE
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "affected_agents": [],
      "failed_ids": [
         {
            "id": "001",
            "error": {
               "message": "Maximum attempts exceeded for sqlite3 execute: database is locked",
               "code": 2002
            }
         }
      ]
   }
}
# curl -u foo:bar "localhost:55000/agents/001?pretty&purge" -XDELETE
{
   "error": 0,
   "data": {
      "msg": "Some agents were not removed",
      "affected_agents": [],
      "failed_ids": [
         {
            "id": "001",
            "error": {
               "message": "Agent does not exist: 001",
               "code": 1701
            }
         }
      ]
   }
}
# cat /var/ossec/etc/client.keys
002 test2 any 7a9c0990dadeca159c239a06031b04d462d6d28dd59628b41dc7e13cc4d3a344
003 test3 any d7ae2f7fe182d202f9088ecb7a0c8899fee7f192c0c0d2d4db906d5fc22a7ad5
```

What happened? The [`_remove_manual`](https://github.com/wazuh/wazuh/blob/f5326f7c3684c77d012a6b103f5e70914e575f95/framework/wazuh/agent.py#L437) function, used by the framework to remove agents when `authd` is not enabled, follows the following process:
1. Remove agent from client.keys file
2. Remove all agent's files such as `agent-info`, `agent-groups`, `rids`, etc.
3. Remove agent's group assigment from global database.

This process is quite risky: if 2 or 3 fails, the agent will be already removed and therefore, the remove process can't be retried. 

I suggest doing one of the following fixes:
- Reverse the removal steps to 3, 2, 1. The database is the most likely step to fail. If the function fails at this step all agent data will be kept and no restore will ne needed. Also, if the agent is kelt at client.keys the process can be retried.
- Specify in the error message which part of the process failed.
- Restore all removed data if any part of the process fails (more difficult to implement).

**Comment by crd1985** [comment]
@mgmacias95 I suggest researching this [package](https://pypi.org/project/transaction/). It seems to be well maintained and could fit our needs for the third point.
