### ISSUE TITLE
Fit scan info messages of FIM in Windows systems

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2873]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager/Agent | Packages/Sources | Windows |

Hi team,

Messages informing of FIM start/end scans and when Real-time and Whodata are active are not accurate on Windows systems.

The reason for this is that the Registry Key scan is performed after reporting that Whodata, Real-time and the first scan have finished.

We have to move the following messages to fit the current state of FIM:

> Whodata auditing engine started.
> Real-time file monitoring engine started.
> Finished creating syscheck database (pre-scan completed).

**Comment by bah07** [comment]
### Update

Working on the branch: https://github.com/wazuh/wazuh/tree/fix-FIM-infomessages

- Fix to indicate when Realtime is active.
d78191cdb8c0674f6573eab203006af16015705b
- Regroup debug, error and information messages.
6528e578abcc4ceded78e1e6a6291b39ac7cae86
c25cf78d73acf147918fc61f47f1d7894dab7b46
0ece54625baefc71f6af7d6e431b24fd46f942e9
- Assign an identifier to each message of the File Integrity Monitoring module.
44ce2e50c22f99971a318a180e2583df606fd491
82a02a61e7ec6c2c24e388e6b3445656a99157c3
8046743a410ad82ce7f3d5dd0f4e88465a468408
6f8923c8d005833c09756036a893f41c90ab4031

**Comment by albertomn86** [comment]
Merged
