### ISSUE TITLE
Whodata fails in some scenarios

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2874]
Hi team,

We have done some testing over syscheck(whodata) module with the following errors:

| Wazuh version | Install type | Install method | Platform |
|---|---|---|---|
| 3.9.0-3908 | Agent | Packages | Windows 10 enterprise |

We got the following results of moving a file with mouse to whodata folder from not monitored whodata folder:
```
** Alert 1553102996.2733868: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 Mar 20 17:29:56 (IE11Win10) 192.168.121.3->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\tmp\file - copy.txt' was added.

Attributes:
 - Size: 14
 - Date: Mon Mar  4 16:58:29 2019
 - User: IEUser (S-1-5-21-837234192-605533775-2443057095-1000)
 - MD5: 9208487debedb59f33585a879183c1c1
 - SHA1: 259f2d60a39c4fa251d4a2f7758116f44dff2055
 - SHA256: ca0b8c19e45bec8fad9971e325148151fdef08faf8ae61e7a99fd57260d56dc5
 - File attributes: ARCHIVE
 - Permissions: 
   Administrators  (ALLOWED) - DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE, FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES
   SYSTEM  (ALLOWED) - DELETE, READ_CONTROL, WRITE_DAC, WRITE_OWNER, SYNCHRONIZE, FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES
   Users  (ALLOWED) - READ_CONTROL, SYNCHRONIZE, FILE_READ_DATA, FILE_READ_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES
   Authenticated Users  (ALLOWED) - DELETE, READ_CONTROL, SYNCHRONIZE, FILE_READ_DATA, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_EA, FILE_WRITE_EA, FILE_EXECUTE, FILE_READ_ATTRIBUTES, FILE_WRITE_ATTRIBUTES

** Alert 1553103085.2735208: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 Mar 20 17:31:25 (IE11Win10) 192.168.121.3->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\tmp\file - copy.txt' was deleted.

```
We can't see information of whodata on such files.

Otherwise when we copy a file we have great results:
```
** Alert 1553101841.2731044: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 Mar 20 17:10:41 (IE11Win10) 192.168.121.3->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File 'c:\tmp\file.txt' was added.
(Audit) User: 'IEUser (S-1-5-21-837234192-605533775-2443057095-1000)'
(Audit) Process id: '2968'
(Audit) Process name: 'C:\Windows\explorer.exe'

Attributes:
 - Size: 14
 - Date: Mon Mar  4 16:58:29 2019
 - User: IEUser (S-1-5-21-837234192-605533775-2443057095-1000)
 - MD5: 9208487debedb59f33585a879183c1c1
 - SHA1: 259f2d60a39c4fa251d4a2f7758116f44dff2055
 - SHA256: ca0b8c19e45bec8fad9971e325148151fdef08faf8ae61e7a99fd57260d56dc5
 - Permissions: 100666

** Alert 1553101845.2731729: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2019 Mar 20 17:10:45 (IE11Win10) 192.168.121.3->syscheck
Rule: 553 (level 7) -> 'File deleted.'
File 'c:\tmp\file.txt' was deleted.
(Audit) User: 'IEUser (S-1-5-21-837234192-605533775-2443057095-1000)'
(Audit) Process id: '2968'
(Audit) Process name: 'C:\Windows\explorer.exe'
```

| Wazuh version | Install type | Install method | Platform |
|---|---|---|---|
| 3.8.2-1 | Agent | Packages | Windows 10 enterprise |

We didn't get nothing when we moved a file from not monitored folder to whodata folder, no alerts was received on manager.

| Wazuh version | Install type | Install method | Platform |
|---|---|---|---|
| 3.7.2-1 | Agent | Packages | Windows 10 enterprise |

Same as 3.8.2, we still researching.

Regards.

**Comment by crolopez** [comment]
- When an event is moved to a monitored folder, or it is renamed, the creation event has no information with Whodata. This is because there is no way to determine this information, and we prefer to give at least one standard alert.

- When you copy a file to a folder monitored with Whodata the operation is different: you are creating a new file from that directory and therefore you do get that information in the alert.

- The alert you got after removing a file moved to a monitored folder was reported by frequency, so it is normal that it does not have Whodata information. The reason for this is due to a bug in Windows systems which does not refresh file audit policies. We explain this bug and add functionality to control it in https://github.com/wazuh/wazuh/pull/2888.
