### ISSUE TITLE
Monitoring files in Sysnative (System32) with whodata does not work

### ISSUE THREAD

**Issue by vnil1994** [wazuh/wazuh#2877]
|Wazuh version|Install type|Install method|Platform|
| 3.8.2 | Agent | Packages | Windows Server Datacenter 2016 64-Bit |

Hi,

Syscheck with whodata does not work at all when monitoring SysNative (System32). I have been unable to detect any sort of changes, new files, deleted files etc when using syscheck with whodata. If i replace whodata with realtime, everything works.

With whodata enabled and syscheck.debug=1  i can see the following in the logs:

`2019/03/20 13:46:14 ossec-agent: DEBUG: Scanning new file 'C:\Windows\SysNative\testwazuh\testigen.txt' with options for directory 'C:\Windows\SysNative\testwazuh'.
2019/03/20 13:46:14 ossec-agent: DEBUG: Attempted to check NFS status for 'C:\Windows\SysNative\testwazuh\testigen.txt', but we don't know how on this OS.
2019/03/20 13:46:15 ossec-agent: DEBUG: Could not convert SID to string which returned (87)
2019/03/20 13:46:15 ossec-agent: DEBUG: Performing a LookupAccountSid() on (unknown)`

Here is how i configured the agent:
`<directories check_all="yes" whodata="yes">%WINDIR%\SysNative</directories>`

Let me know if there is any more information i can provide. I will be trying to make this work the whole day.

EDIT: I can see changes with whodata when monitoring %WINDIR% in every folder and directly in %WINDIR% but not in system32. It even works in SysWOW64, but still not system32.

EDIT 2: I am now able to detect some things in system32. I noticed that if i do it the following way, new files added to system32 will be noticed by the agent:

1. Create document test.txt outside of System32
2. Copy and paste test.txt to C:\Windows <- This gets picked up by the agent and creates an alert
3. Copy and paste test.txt from C:\Windows to C:\Windows\System32 <- This gets picked up by the agent and creates an alert (This works every time)
4. If i then delete test.txt from System32 this will also generate an alert.

If i repeat steps 3 and 4 over and over again, it will generate an alert for each copy and for each delete. However if i change the contents of the file test.txt after i've placed it in System32, no alert will be generated.

**Comment by crolopez** [comment]
Hi @vnil1994,

We are investigating the use case with the steps you have provided. We will soon give a more detailed answer about the reason and implement a solution if possible.

Thanks for your feedback!

Best regards.

**Comment by crolopez** [comment]
Hi @vnil1994,

We have implemented a solution to the problem. It will be included in the next release.

You can see it [here](https://github.com/wazuh/wazuh/pull/2935).

Best regards.

**Comment by albertomn86** [comment]
Merged. Thanks @vnil1994 for reporting this issue! 
Please re-open this issue if the fix described in the related PR https://github.com/wazuh/wazuh/pull/2935 doesn't work for you.
