### ISSUE TITLE
Monitoring drives different from "C:" with Whodata option

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2883]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Agent | Packages/Sources | Windows |

If a directory is configured to monitor with Whodata on a drive different from "C:", the path collected by Windows CallBack is not a typical drive: D, E, F etc... instead it appears with the internal name of the device, for example:'\device hardddiskvolume4\test\newfile1'.

This does not cause alerts for directories configured with Whodata option.

To reproduce it configure:
```
<directories check_all="yes" whodata="yes">f:\test</directories>
```
The following result is obtained:
```
DEBUG: The '\device\harddiskvolume4\test\newfile1' directory has been discarded because it is not being monitored in whodata mode.
DEBUG: Scanning of the '(null)' directory is aborted because something has gone wrong.
```

**Comment by bah07** [comment]
We found a posible solution at msdn documentation:

https://docs.microsoft.com/es-es/windows/desktop/FileIO/displaying-volume-paths

In the example they get an output where they relate all the possible drives of a device:
```
Found a device:
 \Device\HarddiskVolume2
Volume name: \\?\Volume{4c1b02c1-d990-11dc-99ae-806e6f6e6963}\
Paths:  C:\

Found a device:
 \Device\CdRom0
Volume name: \\?\Volume{4c1b02c4-d990-11dc-99ae-806e6f6e6963}\
Paths:  D:\
```

**Comment by bah07** [comment]
Working on the branch: https://github.com/wazuh/wazuh/tree/fix-fim-driveletter

We can now relate the devices to the mounting points of each Windows system.

```
2019/03/25 18:34:29 ossec-agent[1560] win_whodata.c:1336 at get_drive_names(): DEBUG: Device '\Device\HarddiskVolume4' associated with the mounting point 'F:'
2019/03/25 18:34:29 ossec-agent[1560] win_whodata.c:1336 at get_drive_names(): DEBUG: Device '\Device\HarddiskVolume5' associated with the mounting point 'G:'
2019/03/25 18:34:29 ossec-agent[1560] win_whodata.c:1336 at get_drive_names(): DEBUG: Device '\Device\HarddiskVolume2' associated with the mounting point 'C:'
2019/03/25 18:34:29 ossec-agent[1560] win_whodata.c:1336 at get_drive_names(): DEBUG: Device '\Device\CdRom0' associated with the mounting point 'D:'
```

All we need to do is replace the chain with the corresponding letter.

**Comment by albertomn86** [comment]
Merged
