### ISSUE TITLE
Installation of Wazuh on different folders delete some files

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2884]
Hi team,

This time I have installed Wazuh 3.9.0-rc4 on default folder `C:\Program Files (x86)\ossec-agent` and I try to install other agent version `3.8.2-1` and `3.7.2-1` on different folders as `ossec-agent-382` with MSI installer on advanced settings, when any of those MSIs are installed, the binaries and some files inside my original `ossec-agent` folder are deleted. 

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-rc4 | Agent | Packages | Windows 10 Enterprise |
| 3.8.2-1 | Agent | Packages | Windows 10 Enterprise |
| 3.7.2-1 | Agent | Packages | Windows 10 Enterprise |

Regards.

**Comment by DaveVG1** [comment]
This could be related to this #2494

**Comment by chemamartinez** [comment]
Hi @okynos,

This issue has been solved at https://github.com/wazuh/wazuh/pull/2534.

Thanks for reporting it.

Regards.
