### ISSUE TITLE
Wazuh cluster + agent purge issues

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#2886]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Manager | Packages | CentOS 7 |

Hello team,
I've noticed a strange behavior in Wazuh cluster while purging agents using the Wazuh API.

I deployed a 2 node cluster (`purge` option set to no):
- Master
- Worker

And then deployed 3 agents reporting to the worker node.

After that, I used the Wazuh API to delete a specific agent. I noticed:

- `client.keys` was being reordered, purged (!) agents moved to the end of the file This may cause errors when computing file differences with `diff`.
- No deletion log on `api.log`. https://github.com/wazuh/wazuh/blob/v3.8.2/framework/wazuh/cluster/cluster.py#L508 that line is not being executed.
- Even though aforementioned line didn't execute, `agent-info` on the worker side was being deleted. I'm not sure what is doing that.
- After some attempts, sometimes the `agent-info` got deleted, and some others it didn't.

Regards.

**Comment by AdriiiPRodri** [comment]
Hi @havidarou ,

We've reviewed every issue you mentioned:

- The client.keys file was being rearranged when we deleted an agent with the purge option set to no. This behaviour is correct and it is the cause of the problem you mention in version 3.8.2.  PR [2541](https://github.com/wazuh/wazuh/pull/2541) solved it, and the changes are currently available in [3.9](https://github.com/wazuh/wazuh/tree/3.9).

- The line https://github.com/wazuh/wazuh/blob/v3.8.2/framework/wazuh/cluster/cluster.py#L508 does not run. Hence, the agent deletion does not appear in the api log or in the cluster log. This has also been corrected in version [3.9](https://github.com/wazuh/wazuh/tree/3.9).

- As for the agent-info, we have tried to replicate the error. The deletion of the agents takes a few seconds to spread throughout the cluster. In any case the cluster has been improved in [3.9](https://github.com/wazuh/wazuh/tree/3.9).

Please, let me know if the answers fullfill your needs. We await your confirmation.

Thank you for your time and your report.

Best regards,
Adri
