### ISSUE TITLE
Debug option 

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2894]
Hi team,

We found an error inside `internal_options.conf` on Windows, when we set the option `syscheck.debug=2` the Debug options are enabled, the option `windows.debug=2` also enables debug options.

As we see on comments:
```
# Syscheck (local, server and Unix agent)
syscheck.debug=2
```
This option wouldn't work on Windows.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-rc4 | Agent | Packages | Windows 10 Enterprise |

Regards.

**Comment by DaveVG1** [comment]
|Working branch|
|---------|
|[fix-win-debug-msg](https://github.com/wazuh/wazuh/tree/fix-win-debug-msg) |

I'm working on this in the referenced branch. The following steps have been taken:
- Ignore every call to `GetDefine_Int` for debug options in Windows (except for `windows.debug`).
- As only some daemons are compiled into Windows agent, it's only necessary to exclude the calling for the debug options used in those daemons ( `logcollector`, `syscheck`, `wazuh-modules`, `exec` and `agentd`).

**Comment by chemamartinez** [comment]
Hi team,

This issue is handled at https://github.com/wazuh/wazuh/issues/3150.

Regards.
