### ISSUE TITLE
[Question] Requirements to install Wazuh

### ISSUE THREAD

**Issue by KarenKawaii** [wazuh/wazuh#2897]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| master | Manager | Sources with ./install.sh  | Centos 7 |

I Have problems in Wazuh instalation with the ./install.sh script because is trying to find some dependencies that I don't have in my docker container Centos 7.

I have been looking at the official documentation and I have not found information related to the necessary libraries before installing Wazuh to avoid this everytime that I run the script (different errors):

![image](https://user-images.githubusercontent.com/11741384/54856030-39479300-4cbe-11e9-8c27-0da05e587fd5.png)

Could you help me guiding me to that prerequisite checklist please.

Regards.

**Comment by TJOSERAFAEL** [comment]
Hi @KarenKawaii ,

in order to build Wazuh from sources you need to install the following dependencies:

- libtool
- automake
- autoconf
- gcc

`yum install gcc libtool automake autoconf`

you should be fine with that.

Regards.

**Comment by TJOSERAFAEL** [comment]
Hi @KarenKawaii,

I'm going to close this issue. If you have more questions feel free to re-open it.

Best regards.
