### ISSUE TITLE
Get reporting IP for Mac OS X agents

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2921]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-rc4 | Agent | Packages/Sources | Mac OS X |

Issue https://github.com/wazuh/wazuh/issues/2199 includes a new module called _control_ in charge of querying Syscollector for the main IP address of an agent and sending that IP to the manager.

For now, that module works for Linux and Windows only due to the network inventory for Mac OS X agents doesn't retrieve the default gateway (which is necessary to determine the primary IP address of the agent).

We have to extend that functionality to Mac OS X agents.

### Tasks

- [x] Add the default gateway to the network inventory of macOS agents.

- [x] Use the _control_ module to guess the primary IP and send it to the manager in macOS.

**Comment by Skeptor** [comment]
Researching on how to get the default network interface in Mac OS X and BSD systems:

In Mac and BSD the console command `route get default` extract the default interface writting in a socket and reading the socket information with `getnameinfo()`
I'm trying to reproduce the workflow of `route` creating the socket and trying to communicate with it using the `default` route that the system would use.

The goal is to obtain the default interface and his gateway.

**Comment by Skeptor** [comment]
Solution:
Instead of replicating the route mechanism, the solution is going to be different:
· Read the routing table through `sysctl`
· Loop over the structure extracted from the routing table
· Get the name and the socket from the entry of the table
· Get the gateway from the socket

This way the syscollector scan will report the gateway of the interfaces. Once we have the gateway information gathered, we can guess the agent primary IP and send it to the manager

**Comment by Skeptor** [comment]
The last commits add to the Mac OS X agents the control module to send the IP to the manager as it is done in the Linux agents.
The module filters the gateway list to take the first interface that is marked as default and that doesn't have a gateway with form: `link#n`
I've been trying to extract the priority list that Mac OS uses to route the connections but I didn't find any way to do it.
The last things in the roadmap are check the integrity of the code (Memory leaks, correct workflow,...) and test the enhancement with the use cases.

**Comment by chemamartinez** [comment]
Merged: #3010
