### ISSUE TITLE
Error when getting the package inventory in Mac OS X

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2922]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Agent | Packages/Sources | Mac OS X |

The package parser for Mac OS X agents is failing when reading the `Info.plist` file of several packages because its format is different as expected.

Here we can see two different cases, the first one, for the Dropbox package its `Info.plist` file follows a standard XML format:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>18B75</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>Dropbox</string>
	<key>CFBundleDocumentTypes</key>
```

However, the `Info.plist` for iTunes has an unreadable format which makes the parser fail:

```
bplist00�(


 !"#$%&'()MNOPQQRMMUopq�����������Oxyz9{Q|}QP~��_CFBundleURLTypes_NSAppleScriptEnabled_CFBundleInfoDictionaryVersion_NSHumanReadableCopyright_DTPlatformVersion_CFBundleIconFile\CFBundleNameYDTSDKName_CSResourcesFileMapped_$NSSupportsAutomaticGraphicsSwitching_UTImportedTypeDeclarations_NSPrincipalClass_LSApplicationCategoryType_CFBundleDocumentTypesZDTSDKBuild_CFBundleShortVersionString_CFBundleSupportedPlatforms_BuildMachineOSBuild_DTPlatformBuild_CFBundlePackageType\DTXcodeBuild_CFBundleDevelopmentRegion^MDItemKeywords_CFBundleVersion_UTExportedTypeDeclarations_CFBundleGetInfoString_OSAScriptingDefinition]NSMainNibFile_CFBundleIdentifier_HPDHelpProjectIdentifierWDTXcode_CFBundleIconName_CFBundleHelpBookName_CFBundleHelpBookFolder_CFBundleExecutable_LSMinimumSystemVersion_CFBundleSignature^DTPlatformName_NSDockTilePlugInZDTCompiler�*4:?H�+,-./013_LSIsAppleDefaultForType_CFBundleURLName_CFBundleURLSchemes_CFBundleTypeRoleSYes_iTunes Remote Library URL�2TdaapVEditor�+,-./563_iTunes Music Store URL�789TitmsUitmssVitunes�+,-./;<3_iTunes Podcast URL
```

This makes the Inventory tab for Mac OS X agents to show empty rows in the package table:

![Screen Shot 2019-03-26 at 5 42 28 AM](https://user-images.githubusercontent.com/29475387/55003756-44116900-4fd9-11e9-9079-b4b68b273d88.png)

We have to look for an alternative way to get the package information in those cases, or at least, not to report that packages. In my test environment, this happens for iTunes, Dukto, and VirtualBox.

**Comment by Leamsy** [comment]
I've been taking a look at what may be causing the issue and what the best solution may be. As some programs use a completely different formatting in the Info.plist files, the best solution may be to look for the info somewhere else. I am working on a possible fix right now.

**Comment by Leamsy** [comment]
I've figured out a possible solution in trying to extract the program's name from its folder, and am working on it at the moment.

**Comment by Leamsy** [comment]
I've a way to get the package's name outside of their Info.plist, as seen in commit 9016e81.
3 tasks remain: Removing the .app from the package's name, cleaning the rest of their fields so no corrupt info remains and, if possible, trying to find a way to extract the rest of their info from another place.

**Comment by Leamsy** [comment]
As of commit 3a73138, when we can't extract an app's info from its `Info.plist` file, we try to at least get its name from its `/Applications` folder and then empty the rest of its spaces in the database to avoid it getting filled with garbage data.
