### ISSUE TITLE
Add ports and processes inventory for Mac OS X

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#2923]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| All | Agent | Packages/Sources | Mac OS X |

As we can see in the compatibility matrix of inventories: https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#compatibility-matrix

Running processes and opening ports are not gathering for macOS agents.

### Tasks

- [ ] Add the port inventory to macOS agents.

- [ ] Add the process inventory to macOS agents.

**Comment by Skeptor** [comment]
- Port inventory: I was investigating the `nmap` workflow to see the port scanning. I see that nmap send a ping signal and tries to connect to all the ports of the address.
After the execution a list of open ports is returned with the protocol, state and adress. Also a count of closed ports and filtered ports is returned.

- Process inventory: After investigating how Osquery, ps,... retrieves the list in MAC I'm investigating the library libproc, and I'm trying to adapt it to C to get all the current pids and extract all the data from that pids.

**Comment by Skeptor** [comment]
Today I've been working in the Process scan.
The scan gets a list of current pids on the system and then it iterates through the list of pids to obtain the information. On the first approach to the scan, it shows the next information:
```
	PID 50:
    Father's pid: 1 | Group's pid: 0 | name: syslogd | user_name: root | nice: 0 | status: 2 | priority: 4 | 

	PID 1:
    Father's pid: 0 | Group's pid: 0 | name: launchd | user_name: root | nice: 0 | status: 2 | priority: 31 | 

	PID 0:
    Father's pid: 0 | Group's pid: 0 | name: kernel_task | user_name: root | nice: 0 | status: 2 | priority: 81 | 
```

The status still needs to be displayed as text and I have to check the maximum number of fields that I can extract as it is done in the other Operative Systems but the most relevant information is almost finished.

**Comment by Skeptor** [comment]
I'm going to close this issue because I've created independent issues for each task.
