### ISSUE TITLE
Unable to Automate Adding Agents without overwriting pre-existing Agents ID

### ISSUE THREAD

**Issue by paulcombs** [wazuh/wazuh#2932]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Agent | RPM | CentOS 7.6 |

**Background**
Using a slightly modified version of the "official" Ansible script to install the client and use the authd method to register.  An odd result occurs where the IP address of the firewall is registered, rather than the IP address of the client agent.   This may be a symptom of my environment.  So as a work-a-round I modified the Ansible script to include "`-I any`" .  

**Command Line (automation using auth)** - Fail
According to documentation,` -I any` is implied when not explicitly used.  This is not a problem with the Ansible script, however confirmed with the actual command. This presents the next issue, the command:  
`/var/ossec/bin/agent-auth -m 10.10.10.10 -p 1515 -I any; /var/ossec/bin/ossec-control restart`

This will register with the server as expected, with "any" for the IP.  However, when running the exact command from another client, the ID number is incremented, the old host is deleted, a new host is created and the IP "any"  is created.  

From documentation, IP addresses must be unique.  I believe that "any" is being considered as a duplicate IP, or at least the behavior suggests that.

**Command Line (manual)** - Success
The manual method works (Note: still using "any" for IP)
From server:
- `/var/ossec/bin/manage_agents`  (press A to create, follow instructions, then press E to extract the key and copy that key)
From client:
-  `/var/ossec/bin/manage_agents` (press I to import, follow instructions)
- `/var/ossec/bin/ossec-control restart`

Follow this process on a couple of clients, works!

**Mixed method** - Fail
If for some reason a client registers with the server via the automated method.  Then try to register another client via manual method.  then another via automated method.  Whatever that was created is deleted and overwritten with the last added client.

**Comment by paulcombs** [comment]
**Automated Method** that works is the **Register an agent using a shell script**
https://raw.githubusercontent.com/wazuh/wazuh-api/3.8/examples/api-register-agent.sh

**Comment by DaveVG1** [comment]
Hi Paul,

I think the bug you're getting might be related to #2497. This has been fixed in #2533 and will be featured in next versions.

As you said, the problem was happening while adding agents with IP as `any` with `agent-auth`, but not with `manage_agents`.

I hope this helped.

Best regards,
David

**Comment by paulcombs** [comment]
Thank you, I look forward to the next release.  Much appreciated for the quick response.

**Comment by DaveVG1** [comment]
You're welcome, Paul. I'm going to close this issue. Please, feel free to re-open it if you have any further questions regarding this topic. Thanks.

Regards,
David
