### ISSUE TITLE
Wazuh services in MacOS: launchctl

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#2934]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Agent | Packages/Sources | MacOS |

Hello team

 The Wazuh services for using launchctl are not correctly installed. We need to review the installation process from sources. 

Best regards, 
Alberto R.

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/3119.

**Comment by alberpilot** [comment]
Hello team

  Under fresh MacOS Wazuh agent installation we noticed: 
```
root@Bird:/Library/Ossec/ruleset/sca$ launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
/Library/LaunchDaemons/com.wazuh.agent.plist: Could not find specified service
```

We need to investigate this further. 
Best regards, 

Alberto R.

**Comment by crolopez** [comment]
Hi,

The reason it does not work from packages installation is that the service generation script is not being called in the postinstall. I have uploaded a PR fixing it to the installers repository.

Best regards.
