### ISSUE TITLE
Glob on non-existent path causes ossec-logcollector to exit

### ISSUE THREAD

**Issue by annmuor** [wazuh/wazuh#295]
Example on ( shared/agent.conf )
`<agent_config profile="web">
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/nginx/*_access.log</location>
  </localfile>
  <localfile>
    <log_format>apache</log_format>
    <location>/var/log/nginx/*_error.log</location>
  </localfile>
</agent_config>
`

Logs:
`
2017/12/01 08:35:00 ossec-logcollector: ERROR: (1121): Glob error. Invalid pattern: '/var/log/nginx/*_access.log'.`
`2017/12/01 08:35:00 ossec-logcollector: ERROR: (1121): Glob error. Invalid pattern: '/var/log/nginx/*_error.log'.`

Workaround:
`touch /var/log/nginx/test_{access,error}.log`

Inspecting the code I've found that wazuh is expecting at least one glob to exists and exits if it's not true.

**Comment by crolopez** [comment]
Hi @kreon,

Paths with wildcards currently have the error you are talking about. If there is no coincidence with this pattern when starting logcollector, it will give a non-critical error and continue with its normal operation. Neither will it detect new files that match the pattern #195. 

We are working on it, and the solution will come out for Wazuh 3.1 or earlier. You can see the development branch [here](https://github.com/wazuh/wazuh/commits/dev-logcollector-rescan2).

Best regards.

**Comment by kreon** [comment]
Looks strange as I got logcollector exit after this error. I'll check if there was something along with that caused exit.

**Comment by vikman90** [comment]
Hi,

This issue has been fixed in this PR: Hope you find it useful.

Let me close this issue.
Best regards.
