### ISSUE TITLE
Syscheck doesn't start scan when no directories defined on configuration

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2951]
Hi team,

We have found strange behavior inside Syscheck module, when we configured Syscheck with the following configuration it works as expected:

```
  <syscheck>
    <disabled>no</disabled>
    <frequency>5</frequency>
    <directories check_all="yes">%WINDIR%\regedit.exe</directories>
    <windows_registry>HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Lsa</windows_registry>
    <ignore type="sregex">.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$</ignore>
    <windows_audit_interval>300</windows_audit_interval>
  </syscheck>
```

But if we remove the `directories` entry, scan never starts.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-rc4 | Agent | Packages | Windows server 2016 |

Regards.

**Comment by JoseAntonioMHerrera** [comment]
I tried to replicate this issue on master for a windows agent on windows server 2016 with no result. The issue seems to be fixed. Without any directories tags, the FIM scan still run every n seconds. Also tried to replicate it with the posted configuration, works fine too.
