### ISSUE TITLE
Incoherence with report_changes field in FIM

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#2952]
In the FIM alerts we can see differences when showing the file diff in the Windows agent:

```
What changed:
***** QUEUE\DIFF\LOCAL\USERS\ADMINISTRATOR\DESKTOP\FILE\state.1553703752
***** QUEUE\DIFF\LOCAL\USERS\ADMINISTRATOR\DESKTOP\FILE\LAST-ENTRY
new line
*****
```

Ubuntu file diff:

```
What changed:
3a4,5
> 55
> 
```

We should unify the format of Windows alerts with the rest of agents, removing the unnecessary path. We must also insert the differences of the files in a single field. 

Currently we have that information in` syscheck.diff` and `data.data`.

**Comment by albertomn86** [comment]
Merged https://github.com/wazuh/wazuh/pull/2969
