### ISSUE TITLE
Deadlock in Remoted when updating the 'keyentries' structure

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2954]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.7.2 | Manager | Packages/Sources | Any |

We have found a case in which we remain in a lock in the thread that updates the data structure that contains the 'client.keys'.

This causes the manager to never refresh the agent information (new or modified).

In case of showing this message:
```
ossec-remoted[17143] sendmsg.c:72 at send_msg(): WARNING: (1245): Sending message to disconnected agent '001'.
```

A read_lock is never unlocked causing new agents not to be able to connect:
```
ossec-remoted: WARNING: (1213): Message from '10.0.0.51' not allowed.
```

**Comment by albertomn86** [comment]
Merged
