### ISSUE TITLE
Realtime not working on FreeBSD

### ISSUE THREAD

**Issue by rizarizkan** [wazuh/wazuh#296]
Please help, wazuh cannot running realtime and syscheck delete on freeBSD ? it's bug ?

**Comment by vikman90** [comment]
Hi @rizarizkan,

Unfortunately, Syscheck uses two OS specific real-time engines:

- inotify library for Linux.
- Win32 API (function `ReadDirectoryChangesW()`) for Windows.

The BSD family does not support real-time yet. 

However BSD supports kqueue, we introduced it to perform message polling for TCP in Remoted. We will investigate how this library could help to support real-time capabilities for Syscheck in BSD.

Kind regards.

**Comment by fzipi** [comment]
I've compiled wazuh 3.13 with inotify support, and seems to be working. Someone interested?

**Comment by vikman90** [comment]
@fzipi That is great news!

We would love to know how you made that. Does FreeBSD include the inotify wrapper or did you add a dependency? Did you introduce any change in the code?

Thank you for your effort.
Best regards.

**Comment by fzipi** [comment]
@vikman90 I peeked at how ossec did it. Yes, I needed to add some small changes to wazuh build. Sent the patch to Michael (Muenz?). These are the changes I did in upstream:

```
diff --git a/security/wazuh-agent/files/patch-src_Makefile b/security/wazuh-agent/files/patch-src_Makefile
new file mode 100644
index 000000000000..ed7bc96c9151
--- /dev/null
+++ b/security/wazuh-agent/files/patch-src_Makefile
@@ -0,0 +1,20 @@
+--- src/Makefile.orig	2020-08-08 14:04:40 UTC
++++ src/Makefile
+@@ -1164,7 +1164,7 @@ $(WAZUHEXT_LIB): $(EXTERNAL_LIBS)
+ 	$(OSSEC_SHARED) $(OSSEC_CFLAGS) -mimpure-text -o $@ -Wl,--whole-archive $^ -Wl,--no-whole-archive ${OSSEC_LIBS}
+ else
+ $(WAZUHEXT_LIB): $(EXTERNAL_LIBS)
+-	$(OSSEC_SHARED) $(OSSEC_CFLAGS) -o $@ -Wl,--whole-archive $^ -Wl,--no-whole-archive ${OSSEC_LIBS}
++	$(OSSEC_SHARED) $(OSSEC_CFLAGS) -o $@ -Wl,--whole-archive $^ ${OSSEC_LDFLAGS} -Wl,--no-whole-archive ${OSSEC_LIBS}
+ endif
+ endif
+ endif
+@@ -1355,7 +1355,7 @@ syscheckd/schema_fim_db.o: syscheckd/sch
+ 	${QUIET_CC}echo 'const char *schema_fim_sql = "'"`cat $< | tr -d \"\n\"`"'";' | ${MING_BASE}${CC} ${OSSEC_CFLAGS} -xc -c -o $@ -
+ 
+ syscheckd/%.o: syscheckd/%.c
+-	${OSSEC_CC} ${OSSEC_CFLAGS} -DARGV0=\"ossec-syscheckd\" -c $^ -o $@
++	${OSSEC_CC} ${OSSEC_CFLAGS} -I./syscheckd -DARGV0=\"ossec-syscheckd\" -c $^ -o $@
+ 
+ syscheckd/%-event.o: syscheckd/%.c
+ 	${OSSEC_CC} ${OSSEC_CFLAGS} ${DEFINES_EVENTCHANNEL} -DEVENTCHANNEL_SUPPORT -DARGV0=\"ossec-syscheckd\" -c $^ -o $@
diff --git a/security/wazuh-agent/files/patch-src_syscheckd_run__realtime.c b/security/wazuh-agent/files/patch-src_syscheckd_run__realtim
e.c
new file mode 100644
index 000000000000..237bca8b8098
--- /dev/null
+++ b/security/wazuh-agent/files/patch-src_syscheckd_run__realtime.c
@@ -0,0 +1,25 @@
+--- src/syscheckd/run_realtime.c.orig	2020-08-08 14:07:37 UTC
++++ src/syscheckd/run_realtime.c
+@@ -9,7 +9,7 @@
+  */
+ 
+ #include "shared.h"
+-#include "syscheck.h"
++#include "syscheckd/syscheck.h"
+ 
+ volatile int audit_thread_active;
+ volatile int whodata_alerts;
+@@ -40,6 +40,13 @@ volatile int audit_db_consistency_flag;
+ #ifdef INOTIFY_ENABLED
+ #include <sys/inotify.h>
+ 
++W_Vector *audit_added_rules;
++W_Vector *audit_added_dirs;
++W_Vector *audit_loaded_rules;
++pthread_mutex_t audit_mutex;
++pthread_mutex_t audit_hc_mutex;
++pthread_mutex_t audit_rules_mutex;
++
+ #define REALTIME_MONITOR_FLAGS  IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF
+ #define REALTIME_EVENT_SIZE     (sizeof (struct inotify_event))
+ #define REALTIME_EVENT_BUFFER   (2048 * (REALTIME_EVENT_SIZE + 16))
-- 
2.26.2
```

I can clean it up and send a proper patch.

**Comment by vikman90** [comment]
@fzipi Thanks for the info, that seems a pretty simple change in the code.

I'm curious about how you get the inotify library for FreeBSD. Is that preinstalled or did you install it? Following our zero-dependency principle, we should add it to the _src/external_ folder through the dependency repo.

Your code shows that achieving real-time in FreeBSD is possible and easy. Thank you very much for sharing your code with us!

Best regards.

**Comment by fzipi** [comment]
@vikman90 It is in [the ports system](https://github.com/freebsd/freebsd-ports/blob/master/devel/libinotify/Makefile). It is kqueue based, https://github.com/libinotify-kqueue/libinotify-kqueue.

**Comment by vikman90** [comment]
Gotcha. We developed a common library to switch between epoll and kqueue depending on the platform, but that works for file descriptors only ([notify_op.h](https://github.com/wazuh/wazuh/blob/master/src/headers/notify_op.h)).

I think we can include this inotify wrapper library as an external dependency.

Thank you.

**Comment by chemamartinez** [comment]
Related to https://github.com/wazuh/wazuh/issues/8602

**Comment by chemamartinez** [comment]
Hi guys, closing this issue in favor of https://github.com/wazuh/wazuh/issues/16226.

Regards.
