### ISSUE TITLE
Save old alerts.json data for a specific amount of time

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#2964]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| Any | Manager | Any | Any |

Hello team,

it would be helpful to have a setting allowing you to preserve old alert.json files for a specific amount of time, similar to `monitord.keep_log_days`.

As for now, I've been doing this with a separated script running on a cronjob.
This is specially critical on container environments where the Wazuh manager not always runs on the same node.

Regards.

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
