### ISSUE TITLE
The lack of syscheck debug option on internal_options do agent to crash on Windows

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2980]
Hi team,

Related to this issue #2976 we was trying to delete, unused configuration from agent internal_options when suddenly the removal of that option `syscheck.debug=2` crashes Wazuh agent with the following message `ossec-agent[1588] validate_op.c:212 at getDefine_Int(): CRITICAL: (2301): Definition not found for: 'syscheck.debug'.`, inside documentation such option is specific of Linux https://documentation.wazuh.com/current/user-manual/reference/internal-options.html?highlight=internal_options#windows

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3910 | Agent | Packages | Windows Server 2016 |

Regards!.

**Comment by DaveVG1** [comment]
|Working branch|
|---------|
|[fix-win-debug-msg](https://github.com/wazuh/wazuh/tree/fix-win-debug-msg) |

I'm working on this in the referenced branch.

- This isn't exactly a "crash" it's more like a controlled stop of Wazuh agent (this comes from a calling to merror_exit, not a crash). Anyway, I'm working on this as any debug options should be unused on Windows agent, except for windows.debug (it'll be the only needed debug option in Windows agent from now on, but the agent will continue stopping if this options is deleted from the options).

**Comment by chemamartinez** [comment]
Hi team,

This issue is handled at https://github.com/wazuh/wazuh/issues/3150.

Regards.
