### ISSUE TITLE
Deletion of databases after removing an agent

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2985]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| >=3.2.0 | Manager | Packages/Sources | Any |

Hi team,

We need to delete _Wazuh-db_ databases of the agents after removing an agent.
If we can not cause errors and inconsistencies in the alerts in case of registering a new agent with the same id. 

For example, for a new agent with an old database, the manager will understand that it is not the first scan of that agent and will report all the files as ADD alerts. In Syscollector it can also cause inconsistencies since the installed software inventory will not correspond to reality. The functioning of the vulnerability-detector will be affected by reporting false positives.

Authd is responsible for removing the agents and all information concerning them. We have to add the deletion of the database at this point.

In addition in cluster mode, as the master node is the only one that can delete agents, this information should spread to the workers and delete the local database in each one.

**Comment by mgmacias95** [comment]
Hello @bah07,

The framework is already doing this. It was added in https://github.com/wazuh/wazuh/pull/2546. The master node in a cluster is using authd to remove agents, so Wazuh DB databases aren't removed in master nodes.

Best regards,
Marta

**Comment by bah07** [comment]
Authd must be in charge of giving the order to delete the databases, but the one in charge of the operation must be Wazuh-db.

The daemon maintains an internal structure with the databases open at all times. We have to remove that data structure before proceeding to delete the physical file to avoid leaks of descriptors.

Otherwise, once the file is deleted, wazuh-db keeps the descriptor open without deleting it.

![imagen](https://user-images.githubusercontent.com/6572618/55405733-f9ed3200-555a-11e9-920e-97563fdbe1b5.png)

**Comment by albertomn86** [comment]
Solved in https://github.com/wazuh/wazuh/pull/3123
