### ISSUE TITLE
Fluentd forwarder tests

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#2992]
### Test made so far

- [x] Start without fluentd server started
- [x] Start fluentd server, connects after 30 seconds
- [x] High load 64KB strings without secure mode enabled (TLS)
- [x] High load 64KB strings secure mode disabled (TLS)
- [x] Delete module socket during high load
- [x] Valgrind, check file descriptors, memory leaks

**Comment by TJOSERAFAEL** [comment]
### Tests to be made on MacOS and other Unix systems

- [ ] Start without fluentd server started
- [ ] Start fluentd server, connects after 30 seconds
- [ ] High load 64KB strings without secure mode enabled (TLS)
- [ ] High load 64KB strings secure mode disabled (TLS)
- [ ] Test every configuration option combination
- [ ] Check remote configuration output
- [ ] Delete module socket during high load
- [ ] Valgrind, check file descriptors, memory leaks

### Performance graphs

- Every graph must have a time interval of 2 minutes
- Full load socket injection

### 1024 bytes string

- [ ] Graph throughput, CPU consumption and memory consumption without TLS
- [ ] Graph throughput, CPU consumption and memory consumption with TLS

### 10240 bytes string

- [ ] Graph throughput, CPU consumption and memory consumption without TLS
- [ ] Graph throughput, CPU consumption and memory consumption with TLS

### 65535 bytes string

- [ ] Graph throughput, CPU consumption and memory consumption without TLS
- [ ] Graph throughput, CPU consumption and memory consumption with TLS

**Comment by DaveVG1** [comment]
Testing 
---

### 1024 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 18044222 | 2 minutes |

**Stats**

![cpu](https://user-images.githubusercontent.com/10405193/55887474-dc007c80-5bad-11e9-9d31-1de77e1e44f9.JPG)

**Comment by TJOSERAFAEL** [comment]
### Testing MacOS

| O.S. | CPU | RAM |
| --- | --- | --- |
| MacOS 10.13.5 | 1 x 3Ghz GHz | 16 GB |

**Method**

- Non-stop writing messages in the `fluent-forward` socket. `wazuh-modulesd` is the only active daemon and it's active for 2 minutes.

**Notes**

While writing full speed into the Unix domain socket, it seems that the network handler was slower than the buffer filling, causing the following error on the Python script that writes the messages:

```
[Errno 55] No buffer space available
```

This error doesn't appear on other Unix systems.

Also the script taking the cpu and memory usage every second, was slower so the time frame shown in the graphs is limited to 105 seconds.

### 1024 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 6020960 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55893762-39e69180-5bb9-11e9-9822-9d2bed9dd3f0.png)

![image](https://user-images.githubusercontent.com/16609513/55893812-4ff45200-5bb9-11e9-8436-1eea0846d03c.png)


### 10240 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 562324 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55894008-9e095580-5bb9-11e9-9428-177af2d70317.png)

![image](https://user-images.githubusercontent.com/16609513/55894016-a19cdc80-5bb9-11e9-960a-c0c3246bf19a.png)


### 65535 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 158662 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55894103-d01ab780-5bb9-11e9-9978-6a9616be3a2f.png)

![image](https://user-images.githubusercontent.com/16609513/55894116-d7da5c00-5bb9-11e9-9cc1-353401809ced.png)

As we can see above, the CPU usage slows down as the message size gets bigger.

**Comment by TJOSERAFAEL** [comment]
### Testing MacOS TLS

| O.S. | CPU | RAM |
| --- | --- | --- |
| MacOS 10.13.5 | 1 x 3GHz CPU | 16 GB |

**Method**

- Non-stop writing messages in the `fluent-forward` socket. `wazuh-modulesd` is the only active daemon and it's active for 2 minutes.

**Notes**

While writing full speed into the Unix domain socket, it seems that the network handler was slower than the buffer filling, causing the following error on the Python script that writes the messages:

```
[Errno 55] No buffer space available
```

This error doesn't appear on other Unix systems.

Also the script taking the cpu and memory usage every second, was slower so the time frame shown in the graphs is limited to 110 seconds.

### 1024 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 569055 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55950758-eece8c00-5c55-11e9-82dd-c4fea4bc3de0.png)

![image](https://user-images.githubusercontent.com/16609513/55950764-f55d0380-5c55-11e9-9359-fc62df158cae.png)


### 10240 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 389201 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55950784-01e15c00-5c56-11e9-9b53-5ad483bd2cec.png)

![image](https://user-images.githubusercontent.com/16609513/55950764-f55d0380-5c55-11e9-9359-fc62df158cae.png)

### 65535 bytes string

| Total messages sent | Time |
| :---: | :---: |
| 87902 | 2 minutes |

- Performance graph

![image](https://user-images.githubusercontent.com/16609513/55950794-0d348780-5c56-11e9-979b-b02a09220396.png)

![image](https://user-images.githubusercontent.com/16609513/55950764-f55d0380-5c55-11e9-9359-fc62df158cae.png)
