### ISSUE TITLE
SCA: don't send the whole scan when the agent is restarted

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3006]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager/Agent | Packages/Sources | All |

The SCA module sends the whole scan info when it is restarted due to its local table of checks is empty. That provokes an unnecessary load of events when the manager already has that information and nothing has changed between the current scan and the last one.

We have to use the integrity mechanism to check that any check has changed before resending the scan again.

**Comment by TJOSERAFAEL** [comment]
Hi @chemamartinez,

this branch https://github.com/wazuh/wazuh/tree/3.9-sca-first-scan implements the feature.

**Comment by cristgl** [comment]
Testing for branch `3.9-sca-first-scan`:

- Valgrind for `analysisd` and `modulesd`.
- Restarting the agent does not show the alerts anymore unless their result has changed.
- Tried modifying some checks for the policy files, they are alerted normally after a restart.
- Check that the databases are correctly updated.
- Modify the configuration block adding and removing some policy check files.

**Comment by chemamartinez** [comment]
Merged: #3049. Thanks, @TJOSERAFAEL and @cristgl !
