### ISSUE TITLE
Wazuh MacOS High Sierra agent unable to connect to server

### ISSUE THREAD

**Issue by lukelee1987** [wazuh/wazuh#3014]
I am trying to monitor my MacBook using Wazuh, and I have successfully added the Agent on it. But after I have run the Wazuh agent, I realized the Wazuh Manager did not capture this agent. It shows "Never connected" on Kibana dashboard. 

While troubleshooting this issue, I went to the agent side and run this command : ./ossec-agentd -df. And there are error spotted: Debug: Connection socket: Resource temporarily unavailable (35). Kindly share your experience on resolving it. Thanks 

|Wazuh Agent version 3.8.2 
MacOS High Sierra

**Comment by davidjiglesias** [comment]
Hi @lukelee1987 , this issue has been treated in [Wazuh - MacOS High Sierra](https://groups.google.com/forum/#!searchin/wazuh/Wazuh$20MacOS$20High$20Sierra%7Csort:date/wazuh/DfShifrr-4c/ab2ZtQSjBQAJ).

Best regards,

David J. Iglesias
