### ISSUE TITLE
Make output of ossec-makelists clearer when a CDB list has been edited

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#3026]
At present when you edit a CDB list like ssh-watch-list in my example below, running ossec-makelists makes an unclear statement about the changed list needing to be updated when actually it has already updated it:

```
[root@manager6 ~]# ossec-makelists
 * File etc/lists/audit-keys.cdb does not need to be compiled
 * File etc/lists/amazon/aws-eventnames.cdb does not need to be compiled
 * File etc/lists/security-eventchannel.cdb does not need to be compiled
 * File etc/lists/ssh-watch-list.cdb needs to be updated
```

May I suggest changing "needs to be updated" to "has been updated"?  This issue is confusing to the uninitiated, giving the impression that something else must be done to actually update the changed list.

Thanks!
Kevin

**Comment by cristgl** [comment]
Hi @branchnetconsulting,

Thank you for your suggestion. We have considered it and are working on improving this message.

Kind regards,
Cristina

**Comment by chemamartinez** [comment]
Hi all,

After several discussions about this issue and others related to the CDB lists. We have decided to deprecate the `ossec-makelists` tool to easier users the update procedure of them.

The tasks in charge of `ossec-makelists` to re-build the CDB lists manually will be transferred to Analysisd at every start. That way, restarting the manager will apply the changes and addition of new CDB lists automatically.

Best regards.

**Comment by branchnetconsulting** [comment]
Hi Chema,

Right now with ossec-makelists, we can make changes to CDB lists and have them take effect right away without having to restart the manager.  If we depreciate ossec-makelists, let's make sure to provide a way, probably via the Wazuh API, to reload changed CDBs without a manager restart like it presently does for ossec-makelists.  In fact the Wazuh API would be able to do a much nicer job at this than ossec-makelists, because a single API call could be routed by the master node manager to all the worker node managers, telling them to reload their CDB lists, with not disruption to the Wazuh manager cluster.

I think this is important because some use cases for CDBs that involve more frequent, dynamic updates to the lists, probably would be harmed by the requirement to restart all managers every time a CDB is updated.

I think we are generally wanting to move away from requiring manager restarts to make changes take effect.  For example I understand we are aspiring to support hot reloading of Wazuh rules (https://github.com/wazuh/wazuh/issues/39).  It would be good to follow that same pattern with CDBs in my opinion.

Thanks for your consideration,
Kevin

Kevin Branch

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting,

PR #3488 has been merged including the `ossec-makelists` output messages modifications for clarity, as well as the automation of the compile process as you know.

Let me close the issue. As always, your feedback is really appreciated.

Regards.
