### ISSUE TITLE
rootcheck not ignoring specified files

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3030]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2-3814 | Manager/Agent | Packages | CentOS |
| 3.9.0-3911 | Manager/Agent | Packages | CentOS |

If a file or folder is specified to be ignored (either in centralized configuration's `agent.conf`, or an agent's or manager's `ossec.conf`) :
```
<ossec_config>
  <rootcheck>
    <ignore>/dev/ignore/</ignore>
  </rootcheck>
</ossec_config>
```
And a file is created that should be ignored:
```
mkdir /dev/ignore/
touch /dev/ignore/.badalert
systemctl restart wazuh-manager
```
It still generates an alert:
```
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
File '/dev/ignore/.badalert' present on /dev. Possible hidden file.
title: File present on /dev.
file: /dev/ignore/.badalert
```
A workaround is to create a whitelisting rule:
```
<group name="rootcheck">
  <rule id="100002" level="0">
    <if_sid>510</if_sid>
    <match>/dev/ignore/</match>
    <description>rootcheck ignore</description>
  </rule>
</group>
```

**Comment by albertomn86** [comment]
Solved in https://github.com/wazuh/wazuh/pull/3058
