### ISSUE TITLE
Rejecting Mapping Update: Wazuh 3.8.2 with Open-Distro

### ISSUE THREAD

**Issue by 0x18katyan** [wazuh/wazuh#3032]
I have installed the template into elasticsearch but it is still generating the following error.
I stopped all logstash instances, then deleted the old indices from elasticsearch and then only installed the template. I am using the Open-Distro-Elasticsearch and Open-Distro-Kibana. I have successfully installed Wazuh app into Kibana and it is working except that it shows X out of Y shards failed when accessing visualizations of any sort. The problem is only with the alerting index and not with the monitoring index.
ELK Stack Version: 6.5.4
Open-Distro: 0.7.1
Wazuh Version: 3.8.2

`[2019-04-05T09:51:59,077][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2019.04.05", :_type=>"doc", :routing=>nil}, #<LogStash::Event:0x51981178>], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2019.04.05", "_type"=>"doc", "_id"=>"FSTp7GkB2r2MykACfK6g", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [wazuh-alerts-3.x-2019.04.05] as the final mapping would have more than 1 type: [wazuh, doc]"}}}}     `

**Comment by 0x18katyan** [comment]
Also, the environment is docker and I built the docker image myself as Wazuh Version 3.8.2 wasn't available on dockerhub. Please ask for any information needed for debugging purposes. And Hi !

**Comment by root360-AndreasUlm** [comment]
Hi,

I have the same issues with the following fresh setup (no migration from earlier version done):
Server: EC2 instance
ELK: 6.6.2
Ubuntu: 18.04
Wazuh: 3.8.2

Message:
```
[2019-04-16T17:07:55,123][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2019.04.16", :_type=>"doc", :routin
g=>nil}, #<LogStash::Event:0x2ff7b7b5>], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2019.04.16", "_type"=>"doc", "_id"=>"rWUeJ2oBE9FO4KDajAuX", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Rejecting mapping update to [wazuh-alerts-3.x-2019.04.16] as the final mapping would have more than 1 type: [wazuh, doc]"}}}}
```

In reference to #1104 the output of the commands are attached.
[indices.txt](https://github.com/wazuh/wazuh/files/3086090/indices.txt)
[es_template.txt](https://github.com/wazuh/wazuh/files/3086091/es_template.txt)
[01-wazuh.conf](https://github.com/wazuh/wazuh/files/3086095/wazuh_3.8_local_logstash.txt) (removed 'document_type' as it is deprecated since ES 6.x)

1) Do you need any additional information?

Regards,
Andreas

**Comment by root360-AndreasUlm** [comment]
@0x18katyan After debugging the issue I found that you just have to change the ES template JSON file. Now I also found pull request #2382 which includes the change I created in our JSON file.

**Comment by 0x18katyan** [comment]
@root360-AndreasUlm Hey, I have got it working with:

`output {
if [type] == "Wazuh" {
    elasticsearch {
        document_type => "wazuh"
        user => ""
        password => ""
        ssl => true
        ssl_certificate_verification => false
        hosts => "https://127.0.0.1:9200" 
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}" 
        template_name => "wazuh"
        template => "/etc/logstash/conf.d/wazuh-elastic6-template-alerts.json"
        template_overwrite => true
       }
    }
}
`

I am planning to try installing Wazuh onto Opendistro 0.8.0 soon, will update. Thanks for your responses, much appreciated.

**Comment by 0x18katyan** [comment]
As the initial issue has been solved using the above wazuh.conf output, I find this issue resolved and close it as so.
P.S. For anyone struggling with having to update wazuh-alerts-* template for elasticsearch using curl, I found it easy to just specify the template using a path, and providing the above options in the wazuh.conf itself.

Regards,
KatyanSun
