### ISSUE TITLE
Add API support for ossec-makelists

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#3037]
Please provide an API call that can cause the equivalent of **ossec-makelists** to be performed for a single manager node or for all manager nodes, as without this function being performed either by API call or legacy command, the affected managers will not actually notice a changed CDB file until their wazuh-manager service is restarted.

Also consider adding an optional parameter on the existing API call(s) for changing CDB files to support automatically following a CDB change with a call to **ossec-makelists** on the same manager nodes.  That way by default we would have to follow a batch of one of more API-based CDB changes with an explicit **ossec-makelists** API request, but when we are only wanting to fire off a single CDB change via API we could just mark that to the applied immediately.

Thanks!
Kevin

**Comment by davidjiglesias** [comment]
Hello Kevin,

Sorry for the late reply and thank you for your contribution. Our team is currently studying a solution to implement the proposed enhancement and it will be released as soon as possible.

Best regards,

David I.

**Comment by jctello** [comment]
Hi Kevin, 
Starting in Wazuh v3.11 `ossec-analysisd ` will compile CDB lists upon start as per: https://github.com/wazuh/wazuh/pull/3488
This will make it unnecessary to have this API call as a manager restart is necessary for the lists to take effect in the ruleset.
I proceed to close this issue.
