### ISSUE TITLE
Wazuh manager only compress alerts when it is running

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#3047]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
|3.8.2-3814|Manager|Packages|CentOS 7|

Hi, 

I am working in a python script to upload `compressed alerts files` to S3 repository and delete them from wazuh. 

I installed a wazuh-manager in a virtual machine some days ago. I shut it down every day and I restart it when it is needed. However, if I move to `/var/ossec/logs/alerts/2019/Apr` folder, it contains the following files:
```
-rw-r-----. 1 ossec ossec  18747 Apr  3 11:05 ossec-alerts-03.json
-rw-r-----. 1 ossec ossec  11630 Apr  3 11:05 ossec-alerts-03.log
-rw-r-----. 1 ossec ossec  81121 Apr  4 09:41 ossec-alerts-04.json
-rw-r-----. 1 ossec ossec  46606 Apr  4 09:41 ossec-alerts-04.log
-rw-r-----. 1 ossec ossec 101989 Apr  5 14:24 ossec-alerts-05.json
-rw-r-----. 1 ossec ossec  57921 Apr  5 14:24 ossec-alerts-05.log
-rw-r-----. 2 ossec ossec  47204 Apr  8 10:40 ossec-alerts-08.json
-rw-r-----. 2 ossec ossec  26527 Apr  8 10:40 ossec-alerts-08.log
```
There is no compressed files from previous days because the machine was not running all day along to compress the alerts. This should be checked also when starting the machine.

Regards.

**Comment by rossengeorgiev** [comment]
It would be nice if wazuh played nice with logrotate. I know before it had a script that would essentially restart the service to rotate files, which is not great.

Wazuh server should be able to handle SIGHUP and reopen all log files without interruption. Then logrotate can be used to deal with log rotation and compression. At the moment, log rotation is built in and has multiple issues, see #2290

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
