### ISSUE TITLE
Agent does not check permissions or ownership of loaded policies.

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3053]
Currently the agent does not check the ownership and permissions of the files that are loaded from the `ossec.conf ` file thus creating the opening for a user that could alter those files to inject commands that would ran in privileged mode.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9| Agent | Sources | All |

**Comment by chemamartinez** [comment]
As it is explained [here](https://github.com/wazuh/wazuh/pull/3061#issuecomment-482643703). This issue is not a security concern for now and will be postponed for further versions.
