### ISSUE TITLE
Get hostname for cluster configuration

### ISSUE THREAD

**Issue by druizz90** [wazuh/wazuh#3057]
Hi team,

This issue is related with #2249. It would be very useful to get the system hostname when `cluster` configuration is as the next:

```XML
<node_name>$HOSTNAME</node_name>
```

There is a problem for getting environment variables (environment variables are override when Wazuh is started trough `systemd`)  but `hostname` can be obtained by Python function `socket.gethostname()`.

Best regards,

Demetrio.

**Comment by druizz90** [comment]
## Issue update

I introduced a change in `cluster.py` for getting the hostname from a system (I am working in branch `dev-cluster-get-hostname` and it works fine:

```XML
<cluster>
    <name>wazuh</name>
    <node_name>$HOSTNAME</node_name>
    <node_type>master</node_type>
    <key>449e3a6ffd9b484c5c645321eed4d610</key>
    <port>1516</port>
    <bind_addr>192.168.122.111</bind_addr>
    <nodes>
        <node>192.168.122.111</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
```

```bash
# echo $HOSTNAME
localhost.localdomain
# /var/ossec/bin/cluster_control -l
NAME                   TYPE    VERSION  ADDRESS          
localhost.localdomain  master  3.9.0    192.168.122.111  
```

**Comment by druizz90** [comment]
## Issue update

I created a Docker image by setting environment variables (`ENV NODE_TYPE="master" NODE_NAME="node_master_docker`) and it works fine with changes introduced in branch `dev-cluster-environment-variables`.

Below there are the cluster configuration in `ossec.conf` and the content of environment variables inside the container:

```XML
  <cluster>
    <name>wazuh</name>
    <node_name>$NODE_NAME</node_name>
    <node_type>$NODE_TYPE</node_type>
    <key>9d273b53510fef702b54a92e9cffc82e</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>master-docker</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
```
```bash
# echo $NODE_NAME
master-docker
# echo $NODE_TYPE
master
```

Cluster is running:

```bash
# /var/ossec/bin/cluster_control -l
NAME           TYPE    VERSION  ADDRESS        
master-docker  master  3.9.0    master-docker 
```

It is possible to get environment variables because Wazuh is not started by `systemd` inside the container.

**Comment by druizz90** [comment]
# Issue update

## Summary

- Added support for this feature in `framework`.

## TO DO

- Add support for this feature in Wazuh core.

**Comment by carlocas** [comment]
### Issue update
I add support for this feature en Wazuh core 
https://github.com/wazuh/wazuh/pull/2246

**Comment by chemamartinez** [comment]
Closing this issue due to the explanation at https://github.com/wazuh/wazuh/issues/2249#issuecomment-560363540
