### ISSUE TITLE
Unable to remove wazuh-agent

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#3064]
How do I remove a wazuh-agent from an Ubuntu 18.04 machine?  Here is what I currently get when attempting to remove:

sudo apt-get remove --purge wazuh-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  wazuh-agent
0 upgraded, 0 newly installed, 1 to remove and 224 not upgraded.
1 not fully installed or removed.
After this operation, 109 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 567072 files and directories currently installed.)
Removing wazuh-agent (3.7.2-1) ...
dpkg: error processing package wazuh-agent (--remove):
 installed wazuh-agent package post-removal script subprocess returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
W: Operation was interrupted before it could finish

**Comment by Lopuiz** [comment]
Hi @alphaDev23,
This error shouldn't appear. Could you tell me how you've installed Wazuh? Or have you removed some Wazuh's file or directory?
Kind regards, Eva

**Comment by alphaDev23** [comment]
It could have been initially installed via 'apt-get install wazuh-agent' or the ansible wazuh-agent role.  Regardless, I'm unable to both remove the existing, reinstall the existing, or install the latest from a downloaded deb package.  

How do I remove manually?

**Comment by Lopuiz** [comment]
Hi @alphaDev23,
You can try removing the files associated to wazuh-agent from /var/lib/dpkg/info. If you execute `ls -l /var/lib/dpkg/info/  | grep wazuh-agent` you should obtain following output:
```
-rw-r--r-- 1 root root      64 Jan 30 12:10 wazuh-agent.conffiles
-rw-r--r-- 1 root root   10605 Apr 17 16:28 wazuh-agent.list
-rw-r--r-- 1 root root   13898 Jan 30 12:10 wazuh-agent.md5sums
-rwxr-xr-x 1 root root    4438 Jan 30 12:10 wazuh-agent.postinst
-rwxr-xr-x 1 root root    1449 Jan 30 12:10 wazuh-agent.postrm
-rwxr-xr-x 1 root root    2204 Jan 30 12:10 wazuh-agent.preinst
-rwxr-xr-x 1 root root    1685 Jan 30 12:10 wazuh-agent.prerm
-rw-r--r-- 1 root root     323 Jan 30 12:09 wazuh-agent.templates
```
Now all you need to do is to remove these files: `rm -rf /var/lib/dpkg/info/wazuh-agent.*`. Use `sudo apt update` and then you should be able to install software as usual.

If it doesn't work let us know.

Kind regards, Eva

**Comment by Lopuiz** [comment]
Hi!

I hope these instructions helped you.
I am going to close this issue as it has been a long time since the last comment.
If you have further questions, let us know.

Kind regards, Eva

**Comment by warifp** [comment]
> 

Thank!

**Comment by YohanRodriguezMDM** [comment]
> Hi @alphaDev23, You can try removing the files associated to wazuh-agent from /var/lib/dpkg/info. If you execute `ls -l /var/lib/dpkg/info/ | grep wazuh-agent` you should obtain following output:
> 
> ```
> -rw-r--r-- 1 root root      64 Jan 30 12:10 wazuh-agent.conffiles
> -rw-r--r-- 1 root root   10605 Apr 17 16:28 wazuh-agent.list
> -rw-r--r-- 1 root root   13898 Jan 30 12:10 wazuh-agent.md5sums
> -rwxr-xr-x 1 root root    4438 Jan 30 12:10 wazuh-agent.postinst
> -rwxr-xr-x 1 root root    1449 Jan 30 12:10 wazuh-agent.postrm
> -rwxr-xr-x 1 root root    2204 Jan 30 12:10 wazuh-agent.preinst
> -rwxr-xr-x 1 root root    1685 Jan 30 12:10 wazuh-agent.prerm
> -rw-r--r-- 1 root root     323 Jan 30 12:09 wazuh-agent.templates
> ```
> 
> Now all you need to do is to remove these files: `rm -rf /var/lib/dpkg/info/wazuh-agent.*`. Use `sudo apt update` and then you should be able to install software as usual.
> 
> If it doesn't work let us know.
> 
> Kind regards, Eva

This definitely helped, we had the same error with wazuh-manager package :)
