### ISSUE TITLE
Wazuh incorrectly handling syslog format

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#307]
Wazuh can't handle syslog messages which have no space after the colon terminating the TAG. 

To reproduce, enable `logall_json`, restart and run `logger -t 'app:word1' word2`.

```json
{
    "agent": {
        "id": "000",
        "name": "wazuh.local"
    },
    "decoder": {},
    "full_log": "2017-12-11T11:21:02.728349+00:00 wazuh.local app:word1: word2",
    "hostname": "lognode-01.local",
    "location": "/var/log/messages",
    "manager": {
        "name": "wazuh.local"
    },
    "rule": {},
    "timestamp": "2017-12-11T11:21:02+0000"
}
```
Notice how the `program_name` is missing from the json output. It should be `app`. Naturally, this breaks any rule that relies on the `program_name` field.

The problem is that the code assume that colon is followed by space, which is actually optional according the [RFC3164](https://www.ietf.org/rfc/rfc3164.txt).

The code is question is:

https://github.com/wazuh/wazuh/blob/ff64c5c3a5ba5f518f7040036ac809fb8fc3fc7d/src/analysisd/cleanevent.c#L192-L196  
https://github.com/wazuh/wazuh/blob/ff64c5c3a5ba5f518f7040036ac809fb8fc3fc7d/src/analysisd/cleanevent.c#L206

There might be other instances besides the above.

**Comment by vikman90** [comment]
Hi @rossengeorgiev,

I've taken a look at the document and I've seen the issue you've raised in sections 4.1.3 and 5.3.

Now the syslog pre-decoder will accept logs with format `app:description` and `app[pid]:description`, leaving the whitespace after the tag as optional.

This is the new result from `ossec-logtest`:

```
Dec 11 17:20:34 ubuntu app:word1: word2

    full event: 'Dec 11 17:20:34 ubuntu app:word1: word2'
    timestamp: 'Dec 11 17:20:34'
    hostname: 'ubuntu'
    program_name: 'app'
    log: 'word1: word2'
```

```
Dec 11 17:20:34 ubuntu app[12]:word1: word2

       full event: 'Dec 11 17:20:34 ubuntu app[12]:word1: word2'
       timestamp: 'Dec 11 17:20:34'
       hostname: 'ubuntu'
       program_name: 'app'
       log: 'word1: word2'
```

The commit is https://github.com/wazuh/wazuh/commit/a82e86c7622231e61036cfa9f85ac169aaa033e8.

Thank you very much for your feedback and your detailed description.

Best regards.

**Comment by rossengeorgiev** [comment]
Hi @vikman90 nice work! Thanks
