### ISSUE TITLE
Checks parsing localizable command output might fail

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3071]
If the system is localized and some test relies on parsing the output of certain program, those tests might fail unless the tests are localized as well. For instance, check
```
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort</command>
    <frequency>360</frequency>
  </localfile>
```
will fail on Spanish systems as netstat output is localized:
```
Proto  Recib Enviad Dirección local         Dirección remota       Estado      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               ESCUCHAR   
tcp        0      0 127.0.0.1:49944         127.0.0.1:8080          TIME_WAIT  
tcp        0      0 127.0.0.1:47666         127.0.0.1:2222          ESTABLECIDO
tcp6       0      0 :::22                   :::*                    ESCUCHAR   
tcp6       0      0 ::1:631                 :::*                    ESCUCHAR   
```
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| -- | Manager/Agent | Sources | Localized Linux |

**Comment by vikman90** [comment]
This issue will be tackled during 5.0 development as part of state changes in the inventory module using the new analysis engine's ruleset.
