### ISSUE TITLE
New Wazuh File Integrity Monitoring module

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#3073]
# Wazuh FIM

We are going to start development for a new module, the Wazuh File Integrity Monitoring (FIM). In the following releases, it will run parallel to the existing Syscheck.
The purpose of this rework is twofold, to improve usability at the configuration level and to make the FIM module more reliable when working in Wazuh cluster environments.

## Steps

- [ ] Configuration restructuring.
* In case of conflict between configurations the last read prevails (agent.conf)
* Overwrite any existing configuration that conflicts with one that comes from the centralized configuration (agent.conf)
* The different options can be defined both in the group block and in a path to facilitate the configuration grouping as appropriate (the last configuration prevails).
* Define the frequency-time in the scheduled mode for each path independently
* The agent does not report alerts occurred during a reboot or while stopped. When it starts it will create the baseline of the one that started to report.

- [ ] Design an internal data structure for each mode

- [x] Make the agent in charge of the process of checking the states of the monitored files.
* Scanning and reporting process is done separately
* Maintain the data in the agent in independent hash tables for each mode
* Ability to perform scans on specific path onDemand

- [ ] Incorporate a database integrity mechanism
* Ability to detect when a database is obsolete and stop reporting until an updated baseline is obtained (don't restart agent).
* Get the baseline of an agent at any time

- [x] The communication between the agent and the manager he reports to through messages in JSON format.

- [x] Simplify the manager-side process 
* Ability to request a complete and updated baseline
* Store in SQL the last state in the manager just to get data from the app or API

**Comment by bah07** [comment]
## Configuration Examples

### 1º Iteration

``` json

/*
    Attributes:

        // Default value: scheduled
        mode="[scheduled | realtime | realtime-whodata]"

        // Default value: 43200
        frequency="[1 - 2147483647]"

        // Default value: emtpy
        scan_day="[monday | tuesday | wednesday | thursday | friday | saturday | sunday]"

        // Default value: emtpy
        scan_time="00:00"

        // Default value: all
        options="[all | size, perm, owner, group, uid, gid, md5, sha1, sha256, mtime, inode]"

        // Default value: empty
        depth="[1 - 320]"

        // Default value: all
        alert="[all | new, modified, delete]"

        // Default value: empty
        tags="a, b ,c"

        // Default value: no
        changes="[yes | no]"

        // Default value: empty
        nodiff = "[regex]"

        // Default value: empty
        ignore = "[regex]"

        // Default value: empty
        restrict = "[regex]"

        // Default value: no
        symbolic_link="[yes | no]"
*/

<fim>
    // Examples
    <path>/home/user</path>

    <group mode="realtime">
        <path>/home/usera</path>
        <path>/home/userb</path>
        <path>/home/userc</path>
        <path>/home/userd</path>
    </group>

    // Configurations by groups
    <group mode="realtime-whodata" options="md5, size, perm" level="10">
        <path>/home/usera</path>
        <path>/home/userb</path>
        <group mode="scheduled" level="1"> 
            <path ignore=".log$">/usr</path>
            <path ignore=".conf$">/etc</path>
        </group>
    </group>

    // Overwriting group configuration in path tag
    <group mode="realtime" ignore".log$">
        <path options="size, sha256, mtime, inode">/home/usera</path>
        <path>/home/userb</path>
    </group>

    <group mode="realtime-whodata" alert="modified" options="sha256, changes">
        <path ignore="/log/">/home/*/apps</path>
    </group>

    // Default configuration of old syscheck module
    <group ignore=".log$|.swp$ | /sys/kernel/security | /sys/kernel/debug" nodiff="/etc/ssl/private.key">
        <path ignore="/etc/mtab | /etc/hosts.deny | /etc/mail/statistics | /etc/random-seed | /etc/random.seed | /etc/adjtime | /etc/httpd/logs | /etc/utmpx | /etc/cups/certs | /etc/dumpdates | /etc/svc/volatile">/etc</path>
        <path>/usr/bin</path>
        <path>/usr/sbin</path>
        <path>/bin</path>
        <path>/sbin</path>
        <path>/boot</path>
    </group>

</fim>

```

**Comment by 32bitbradley** [comment]
This is a fantastic feature release! Cant wait!!! :)

**Comment by zarkoaleksic** [comment]
Can you please consider adding randomization interval for scan_time or even frequency? 
Both OSSEC and Wazuh seem to lack an option to prevent all servers in the environment from running at the same time. 
It would be really useful to specify scan time with a random delay added up to a X amount of time. For example, scheduling at 1AM, with randomization factor of 1 hour would make the scan run at a random minute between 1 and 2AM.

Thanks!

**Comment by bah07** [comment]
Hi @zarkoaleksic 

Thanks, we really appreciate your contribution. We are going to add this functionality in the Syscheck rework, this will be coming out in 3.10.

You can check the status in this issue #3319.

**Comment by Molter73** [comment]
Tasks for converting syscheckd into a wazuh module have been moved to #7981. Closing this issue to avoid duplication of tasks.
