### ISSUE TITLE
Add MongoDB's log_format

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#3082]
Hi Team,

Pre-decoding doesn't work with MongoDB's logs.

The log messages have form:  < timestamp > < severity >  < component > [< context >] < message >
For example:
>2014-11-03T18:28:32.450-0500 I NETWORK [initandlisten] waiting for connections on port 27017
2017-03-27T19:32:31.916+0200 I ACCESS [conn10000] Successfully authenticated as principal snapshots on myUser

And the first example's ossec-logtest output is:
```
**Phase 1: Completed pre-decoding.
       full event: '2014-11-03T18:28:32.450-0500 I NETWORK [initandlisten] waiting for connections on port 27017'
       timestamp: '2014-11-03T18:28:32.450-0500 I '
       hostname: 'ETWORK'
       program_name: '(null)'
       log: '[initandlisten] waiting for connections on port 27017'

**Phase 2: Completed decoding.
       No decoder matched.
```
Pre-decoding adds tags severity and component in the timestamp. It could solve adding new log_format in logcollector.

Kind regards, Eva

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9 | Manager | Sources | Linux mint |

**Comment by slavag** [comment]
When it's expected that fix for MongoDB logs will be released? 
Thanks
