### ISSUE TITLE
Upgrade from 3.8.2 to 3.9.0-3913 with modified internal_options.conf breaks syscheck load

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#3088]
Hi team,

We have found an error on upgrade from 3.8.2 to 3.9.0-3913, we will describe the steps to reproduce it:
1. Install Wazuh Agent 3.8.2 from production on Windows host. https://packages.wazuh.com/3.x/windows/wazuh-agent-3.8.2-1.msi
2. Without register or start agent modify from `internal_options.conf` file the variable `windows.debug=0` to `windows.debug=2` and variable `syscheck.debug=0` to `syscheck.debug=2`.
3. Upgrade to 3913 package.
4. Register agent with `agent-auth.exe` and add server IP on `ossec.conf`.
5. Start Wazuh agent and see `ossec-agent[4464] validate_op.c:212 at getDefine_Int(): CRITICAL: (2301): Definition not found for: 'syscheck.file_max_size'.`.

We know that `internal_options.conf` is a file that isn't recommended to edit but by this way we expect that updates overwrite this to get necessary parameters.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3913 | Agent | Packages | Windows Server 2008 |

Regards.

**Comment by branchnetconsulting** [comment]
I just had the same happen to me after upgrading a working Windows 10 Wazuh agent from 3.8.2 to 3.9.0rc6.  I had to recover by backing up ossec.conf/client.keys, uninstalling the agent, and reinstalling the agent.  Now the agent starts OK.

**Comment by snaow** [comment]
I have just double check it, you both are correct.

The `internal_options.conf` file is not been overwritten on the upgrade process, which makes the agent fail on first boot up.
That file is supposed to be overwritten cause contain new settings which must be present.

My test was upgrading Windows agent from v3.8.2 to v3.9.0-0.3915.20190421.msi (RC7).

**Comment by JuantAldea** [comment]
It seems this issue has been dormant for ages. Wix does not modify unversioned files if they have been modified (i.e, installed hash != current hash). We will address this by setting a "fake version" to the internal_options.conf so that it is always overwritten.

**Comment by branchnetconsulting** [comment]
It would probably be nice to also copy that file to
internal_options.conf.old or something like that.

Kevin

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting ,

The `internal_options.conf` file should not be modified by users, it has to be treated as a template to see default options and use the `local_internal_options.conf` to modify the parameters (that file is not overwritten on upgrades).

On the other side, we are working on deprecating this internal options file (https://github.com/wazuh/wazuh/issues/3150) for future releases.

Regards,
Chema.

**Comment by chemamartinez** [comment]
Merged: #3153
