### ISSUE TITLE
agent_upgrade in clustered Wazuh server environment

### ISSUE THREAD

**Issue by evilpete** [wazuh/wazuh#3089]
When agent_upgrade is run from a server in load balanced clustered environment, agent_upgrade may error when "com upgrade_result" message times out if upgraded agent connects to different server (via. Load Balancer) after restart.

(Note agent_upgrade can only be run from the server the agent is currently connected to and not be run from the cluster master)

Suggestion: have agent_upgrade poll upgrade validation from cluster agent status

**Comment by TJOSERAFAEL** [comment]
Hi @evilpete ,

sorry for the late response, your issue makes totally sense and our team is working hard to fix these issues.

We will take this issue into account for our future releases of Wazuh while we try to figure out the best solution to this.

Thank you for your contribution!

Best regards.
