### ISSUE TITLE
SCA: Alerts involving more than one item (i.e, files) should return arrays instead of comma separated lists

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3097]
Currently rules involving checking more than one item return a string with all items concatenated with a comma e.g,

`"files" :"file1,file2,file3"`

But in order to allow elastic to index this elements and perform searches on them, those lists should be broken down into arrays

`"files" :["file1","file2","file3"]`

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9 | Manager/Agent | Sources | -- |

**Comment by chemamartinez** [comment]
Merged: #3100
