### ISSUE TITLE
SCA: Check the policy files integrity to detect metadata changes

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3099]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager/Agent | Packages/Sources | All |

For the SCA module, a new layer of integrity it is necessary to ensure that changes in the policy files are detected when scanning them again, and those changes are propagated to the manager's DB and finally to the agents' tab in the Wazuh App.

The development plan is the next one:

- When scanning a policy, the checksum of the whole file will be calculated and send it in the summary event of that policy by the SCA module.
- The manager will compare that checksum with the one received in the last scan. If different, we consider that policy (which is the baseline of the scan) has changed, so the action plan is to purge the DB of that policy and ask the agent for the whole scan again.
- That new integrity level implies to store a new field in the DB of the policy metadata to include its checksum, as well as to use the existing functions for purging the DB and for resending the last scan.

**Comment by Skeptor** [comment]
Im working in this branch: https://github.com/wazuh/wazuh/tree/sca_policy_md5
The commit https://github.com/wazuh/wazuh/commit/18ecb684f7778d16d0e9ccdd12ec9e72f13487a6 adds to the table `sca_policy` the MD5 of each policy file to check the integrity of the policies. The next step in the roadmap is compare the current MD5 of the file with the stored MD5 to replace the DB information with the current file.

**Comment by Skeptor** [comment]
The commit https://github.com/wazuh/wazuh/commit/559b08132fecec7afa666874f5740e9d488a7481 change the Hash of the policies from MD5 to SHA256 and provides a function to retrieve the Hash of a policy from the DB to compare the new SHA256 coming from a scan and watch for changes.
The last step is purge the DB with `DeletePolicy` and `DeletePolicyCheck` and ask for a new scan with `PushDumpRequest`

**Comment by Skeptor** [comment]
The commits https://github.com/wazuh/wazuh/commit/673e6a01b290557aed2bd6660187314825cee4f0 and https://github.com/wazuh/wazuh/commit/fbf685a3dea20a1607c6a5df1a2ed2c53e1acfcb add the functionality to retrieve the Hash from the DB and remake the SCA scan if the integrity fails
