### ISSUE TITLE
full_log message truncated in json

### ISSUE THREAD

**Issue by nonaz** [wazuh/wazuh#310]
I'm using the execution of commands on the agent side. There is a problem with truncating full_log field in alerts.json. What are the limitations? and how to change them? Is there a parameter to change field size?

**Comment by vikman90** [comment]
Hi @nonaz,

Currently the string length limit in Wazuh is 6 KiB. Network packets have a 128-byte header so the maximum log size is:

> 6 * 1024 - 128 = 6016 bytes

This limit _may_ be changed by modifying the definition `OS_MAXSTR` at https://github.com/wazuh/wazuh/blob/master/src/headers/defs.h#L40. This would imply to recompile both manager and agent.

However, increasing this value has not been tested and there may be side effects like lost events when connecting via UDP or some overhead in the manager.

Best regards.
