### ISSUE TITLE
Change hash function used to check for DB changes by SCA from MD5 to SHA256

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3110]
Currently SCA uses MD5 which is neither the fastest nor the best function of the hash function zoo. It shall be changed to SHA256.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9| Manager/Agent | Sources | All |

**Comment by chemamartinez** [comment]
Merged: #3111
