### ISSUE TITLE
Windows Agent Eventchannel - 'Could not EvtOpenPublisherMetadata()'

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh#3114]
|Wazuh version|Install type|Install method|Platform|
|3.8.2|msi|powershell|Windows|

I keep seeing the following errors appear on some of our Windows agents running 3.8.1/3.8.2

```
ossec-agent: ERROR: Could not EvtOpenPublisherMetadata() with flags (1) which returned (2)
ossec-agent: ERROR: Could not get message for (Application)
ossec-agent: ERROR: Could not EvtOpenPublisherMetadata() with flags (1) which returned (2)
ossec-agent: ERROR: Could not get message for (Application)
ossec-agent: ERROR: Could not EvtFormatMessage() to determine buffer size with flags (1) which returned (15027)
ossec-agent: ERROR: Could not get message for (Application)

```

Windows debug set to (2) doesn't seem to give any more information about it.
```
ossec-agent[1880] read_win_event_channel.c:246 at get_message(): ERROR: Could not EvtOpenPublisherMetadata() with flags (1) which returned (1722)
ossec-agent[1880] read_win_event_channel.c:520 at send_channel_event(): ERROR: Could not get message for (Application)
```

The configuration we currently have set for this event file is:

```
  <localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID !=1009]</query>
  </localfile>
```

Not sure which event is causing this issue, it started working again after I cleared the Application log, however it started having issues again soon after I restarted.

I noticed the following eventIDs were missing in the archive after the restart, when the errors started showing up:
1000 - VMware NAT Service
1531 - User Profile Service started
1532 - User Profile Service stopped
5615 - WMI service started
5617 - WMI initialized
9027 - Desktop Window Manager registered session port.

**Comment by cristgl** [comment]
Hello @Justangatang,

Regarding the error messages you are getting, focusing on the error codes and comparing them with the [Windows error codes](https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes), we can see that the log file could not be found (error code 2), the message could not be found (error code 15027) or the RPC server is unavailable (error code 1722).

Could you give me some information about how have you cleared the Application channel log? Maybe removing the file from %SystemRoot%\System32\Winevt\Logs, which means logcollector could not monitor that file.

Kind regards,
Cristina
