### ISSUE TITLE
SSL/TLS Certificate Signed Using a Weak SIgnature Algorithm

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#3115]
Openvas scan reports that certificates are part of the certificate chain but using insecure signature algorithm.

**Comment by Zenidd** [comment]
Hi @alphaDev23,

Thanks for reporting the situation. We will review our signature procedure to verify that when we use the ssl/tls protocol it is a secure operation.
<br></br>
Best regards,

Juan Pablo Sáez.

**Comment by antoniomanuelfr** [comment]
Hi alphaDev23. 
I have been trying to replicate your issue.
I downloaded OpenVAS and started a scan, but after the scan is completed there is no issue about the certificates that Wazuh is using. 
On the other hand, we have checked that the used key to generate the certificate is created with RSA-2048 and as far as we know, this algorithm hasn't any security problem. 
Please could you share with us more info like: 
1. Wazuh version. 
2. Platform. 
3. How you launched the OpenVAS scan. 

Best regards, 
Antonio Fresneda.

**Comment by antoniomanuelfr** [comment]
I`m going to close this issue due to innactivity.
Regards.
