### ISSUE TITLE
API: Flask - Delete pretty parameter from new API

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#3117]
Delete parameter `pretty` from the new API.

Goals:
* [x] Remove parameter `pretty`

**Comment by davidjiglesias** [comment]
This issue is blocked by #2640

**Comment by vicferpoy** [comment]
# Status update
Instead of removing this parameter, we can choose if we want our response to be _pretty_ or not. It is set to **False** by default.
