### ISSUE TITLE
unable to Load Wazuh Elasticsearch template

### ISSUE THREAD

**Issue by Sonofmaurice** [wazuh/wazuh#313]
Hi, New to Wazuh so apologies for any user errors. I am installing on a new build Centos 7 which has been updated.  I am following the Guide at https://documentation.wazuh.com/2.0/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elastic-server-rpm
I am at Item 3 to load the template - When I run the curl I get this error message 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     37      0 --:--:-- --:--:-- --:--:--    37
{"error":{"root_cause":[{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"}],"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"},"status":500}
Elasticsearch version 
{
  "name" : "node-1",
  "cluster_name" : "wazuh",
  "cluster_uuid" : "yhebxjtEQXqaLt-PeQtWHQ",
  "version" : {
    "number" : "5.6.5",
    "build_hash" : "6a37571",
    "build_date" : "2017-12-04T07:50:10.466Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
Any assistance gratefully received, any further clarification required please let me know.

**Comment by jesusgn90** [comment]
Hi @Sonofmaurice I have seen that you are using a 2.0 link. Is it your desired version to be installed? We have released the **3.0** version and it is the `current` version, the following link could help you https://documentation.wazuh.com/current/ , also I have seen that you are trying to follow 2.0 installation, if you want to install 2.X for any reason please follow the **2.1 documentation** in order to work properly with **ELK 5.6.5**, that case follow this link https://documentation.wazuh.com/2.1/

Best regards, 
Jesús

**Comment by Sonofmaurice** [comment]
Hi Jesús, many thanks for the update. 
I want the latest so I will follow the new link. I will raise a new issue if I run into any other problems.
Mike

**Comment by Sonofmaurice** [comment]
Hi Jesús,Sorry, I know I closed this but on following the link Welcome to Wazuh — Documentation 3.0 documentation the template update link gives me  curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/2.1/server/startup/integration_files/template_file.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @- This directly references 2.1 in the URL - should this have been updated to 3.0? Anyway - it still gives me the same error.
Thanks,
Mike 
  
|  
|   |  
Welcome to Wazuh — Documentation 3.0 documentation
   |  |

  |

 
 

    On Wednesday, 13 December 2017, 17:23, Jesús Ángel <notifications@github.com> wrote:
 

 Hi @Sonofmaurice I have seen that you are using a 2.0 link. Is it your desired version to be installed? We have released the 3.0 version and it is the current version, the following link could help you https://documentation.wazuh.com/current/ , also I have seen that you are trying to follow 2.0 installation, if you want to install 2.X for any reason please follow the 2.1 documentation in order to work properly with ELK 5.6.5, that case follow this link https://documentation.wazuh.com/2.1/Best regards,
Jesús—

**Comment by JuanjiJG** [comment]
Hi @Sonofmaurice 

The documentation is already updated, you might be seen a cached version of the old documentation. Delete your Internet browser's cache and try to access again to this URL:

https://documentation.wazuh.com/3.x/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elastic-server-rpm

As you can see, the templates and config files are updated to Wazuh 3.0.

Best regards,
Juanjo

**Comment by Sonofmaurice** [comment]
Guys, Thanks for getting me back on track, all installed now. One mention, I had to edit the elasticsearch.yml file to setnetwork.host: 127.0.0.1 http.port: 9200 to allow me to install the template files, otherwise it could not connect as it was not listening on the  IPV4 port 9200
Next hurdle - I try to connect to my host 10.10.12.9:5601 and I get 10.10.12.9 didn’t send any data. ERR_EMPTY_RESPONSEIf i use links locally I get an OK response
I know the port is openState       Recv-Q Send-Q                                 Local Address:Port                                                Peer Address:PortLISTEN      0      128                                                *:22                                                             *:*LISTEN      0      100                                        127.0.0.1:25                                                             *:*LISTEN      0      128                                        127.0.0.1:5601                                                           *:*LISTEN      0      128                                 ::ffff:127.0.0.1:9200                                                          :::*LISTEN      0      128                                 ::ffff:127.0.0.1:9300                                                          :::*LISTEN      0      128                                               :::22                                                            :::*LISTEN      0      128                                               :::55000                                                         :::*LISTEN      0      100                                              ::1:25                                                            :::*
Elasticsearch statuscurl -XGET 'localhost:9200/_cluster/health?pretty'{  "cluster_name" : "wazuh",  "status" : "yellow",  "timed_out" : false,  "number_of_nodes" : 1,  "number_of_data_nodes" : 1,  "active_primary_shards" : 26,  "active_shards" : 26,  "relocating_shards" : 0,  "initializing_shards" : 0,  "unassigned_shards" : 26,  "delayed_unassigned_shards" : 0,  "number_of_pending_tasks" : 0,  "number_of_in_flight_fetch" : 0,  "task_max_waiting_in_queue_millis" : 0,  "active_shards_percent_as_number" : 50.0}
I have gone through the installation again but cannot find any step that failed or was missed.Any advice gratefully received..
Mike 

    On Thursday, 14 December 2017, 9:17, Juanjo Jiménez <notifications@github.com> wrote:
 

 Hi @SonofmauriceThe documentation is already updated, you might be seen a cached version of the old documentation. Delete your Internet browser's cache and try to access again to this URL:https://documentation.wazuh.com/3.x/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elastic-server-rpmAs you can see, the templates and config files are updated to Wazuh 3.0.Best regards,
Juanjo—

**Comment by Sonofmaurice** [comment]
Hi, I have been doing some more investigation and found this curl -XGET 'localhost:9200/_cluster/allocation/explain?pretty'{  "index" : ".kibana",  "shard" : 0,  "primary" : false,  "current_state" : "unassigned",  "unassigned_info" : {    "reason" : "CLUSTER_RECOVERED",    "at" : "2017-12-14T10:53:20.661Z",    "last_allocation_status" : "no_attempt"  },  "can_allocate" : "no",  "allocate_explanation" : "cannot allocate because allocation is not permitted to any of the nodes",  "node_allocation_decisions" : [    {      "node_id" : "dxHznadSTpqoK8Pt4wCExQ",      "node_name" : "node-1",      "transport_address" : "127.0.0.1:9300",      "node_decision" : "no",      "deciders" : [        {          "decider" : "same_shard",          "decision" : "NO",          "explanation" : "the shard cannot be allocated to the same node on which a copy of the shard already exists [[.kibana][0], node[dxHznadSTpqoK8Pt4wCExQ], [P], s[STARTED], a[id=aKW0JS2uQo2g-BIPxjN7NQ]]"        }      ]    }  ]}Mike 

    On Thursday, 14 December 2017, 11:00, "mike.ryan@sky.com" <mike.ryan@sky.com> wrote:
 

 Guys, Thanks for getting me back on track, all installed now. One mention, I had to edit the elasticsearch.yml file to setnetwork.host: 127.0.0.1 http.port: 9200 to allow me to install the template files, otherwise it could not connect as it was not listening on the  IPV4 port 9200
Next hurdle - I try to connect to my host 10.10.12.9:5601 and I get 10.10.12.9 didn’t send any data. ERR_EMPTY_RESPONSEIf i use links locally I get an OK response
I know the port is openState       Recv-Q Send-Q                                 Local Address:Port                                                Peer Address:PortLISTEN      0      128                                                *:22                                                             *:*LISTEN      0      100                                        127.0.0.1:25                                                             *:*LISTEN      0      128                                        127.0.0.1:5601                                                           *:*LISTEN      0      128                                 ::ffff:127.0.0.1:9200                                                          :::*LISTEN      0      128                                 ::ffff:127.0.0.1:9300                                                          :::*LISTEN      0      128                                               :::22                                                            :::*LISTEN      0      128                                               :::55000                                                         :::*LISTEN      0      100                                              ::1:25                                                            :::*
Elasticsearch statuscurl -XGET 'localhost:9200/_cluster/health?pretty'{  "cluster_name" : "wazuh",  "status" : "yellow",  "timed_out" : false,  "number_of_nodes" : 1,  "number_of_data_nodes" : 1,  "active_primary_shards" : 26,  "active_shards" : 26,  "relocating_shards" : 0,  "initializing_shards" : 0,  "unassigned_shards" : 26,  "delayed_unassigned_shards" : 0,  "number_of_pending_tasks" : 0,  "number_of_in_flight_fetch" : 0,  "task_max_waiting_in_queue_millis" : 0,  "active_shards_percent_as_number" : 50.0}
I have gone through the installation again but cannot find any step that failed or was missed.Any advice gratefully received..
Mike 

    On Thursday, 14 December 2017, 9:17, Juanjo Jiménez <notifications@github.com> wrote:
 

 Hi @SonofmauriceThe documentation is already updated, you might be seen a cached version of the old documentation. Delete your Internet browser's cache and try to access again to this URL:https://documentation.wazuh.com/3.x/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elastic-server-rpmAs you can see, the templates and config files are updated to Wazuh 3.0.Best regards,
Juanjo—

**Comment by Sonofmaurice** [comment]
OK, seems I have an issue with shards.
 curl localhost:9200/_cat/shards
.kibana                         0 p STARTED    239   151kb 127.0.0.1 node-1
.kibana                         0 r UNASSIGNED
.wazuh                          1 p STARTED      0    264b 127.0.0.1 node-1
.wazuh                          1 r UNASSIGNED
.wazuh                          2 p STARTED      0    264b 127.0.0.1 node-1
.wazuh                          2 r UNASSIGNED
.wazuh                          3 p STARTED      0    264b 127.0.0.1 node-1
.wazuh                          3 r UNASSIGNED
.wazuh                          4 p STARTED      0    264b 127.0.0.1 node-1
.wazuh                          4 r UNASSIGNED
.wazuh                          0 p STARTED      0    264b 127.0.0.1 node-1
.wazuh                          0 r UNASSIGNED
.wazuh-version                  1 p STARTED      0    264b 127.0.0.1 node-1
.wazuh-version                  1 r UNASSIGNED
.wazuh-version                  2 p STARTED      0    264b 127.0.0.1 node-1
.wazuh-version                  2 r UNASSIGNED
.wazuh-version                  3 p STARTED      1   6.1kb 127.0.0.1 node-1
.wazuh-version                  3 r UNASSIGNED
.wazuh-version                  4 p STARTED      0    264b 127.0.0.1 node-1
.wazuh-version                  4 r UNASSIGNED
.wazuh-version                  0 p STARTED      0    264b 127.0.0.1 node-1
.wazuh-version                  0 r UNASSIGNED
wazuh-alerts-3.x-2017.12.14     1 p STARTED     12  89.6kb 127.0.0.1 node-1
wazuh-alerts-3.x-2017.12.14     1 r UNASSIGNED
wazuh-alerts-3.x-2017.12.14     2 p STARTED     14 124.9kb 127.0.0.1 node-1
wazuh-alerts-3.x-2017.12.14     2 r UNASSIGNED
wazuh-alerts-3.x-2017.12.14     3 p STARTED      7  73.7kb 127.0.0.1 node-1
wazuh-alerts-3.x-2017.12.14     3 r UNASSIGNED
wazuh-alerts-3.x-2017.12.14     4 p STARTED      9  84.4kb 127.0.0.1 node-1
wazuh-alerts-3.x-2017.12.14     4 r UNASSIGNED
wazuh-alerts-3.x-2017.12.14     0 p STARTED     12 101.6kb 127.0.0.1 node-1
wazuh-alerts-3.x-2017.12.14     0 r UNASSIGNED
wazuh-monitoring-3.x-2017.12.14 1 p STARTED      0    264b 127.0.0.1 node-1
wazuh-monitoring-3.x-2017.12.14 1 r UNASSIGNED
wazuh-monitoring-3.x-2017.12.14 2 p STARTED      0    264b 127.0.0.1 node-1
wazuh-monitoring-3.x-2017.12.14 2 r UNASSIGNED
wazuh-monitoring-3.x-2017.12.14 3 p STARTED      0    264b 127.0.0.1 node-1
wazuh-monitoring-3.x-2017.12.14 3 r UNASSIGNED
wazuh-monitoring-3.x-2017.12.14 4 p STARTED      0    264b 127.0.0.1 node-1
wazuh-monitoring-3.x-2017.12.14 4 r UNASSIGNED
wazuh-monitoring-3.x-2017.12.14 0 p STARTED      0    264b 127.0.0.1 node-1
wazuh-monitoring-3.x-2017.12.14 0 r UNASSIGNED
wazuh-alerts-2017.12.13         1 p STARTED      0    264b 127.0.0.1 node-1
wazuh-alerts-2017.12.13         1 r UNASSIGNED
wazuh-alerts-2017.12.13         2 p STARTED      0    264b 127.0.0.1 node-1
wazuh-alerts-2017.12.13         2 r UNASSIGNED
wazuh-alerts-2017.12.13         3 p STARTED      0    264b 127.0.0.1 node-1
wazuh-alerts-2017.12.13         3 r UNASSIGNED
wazuh-alerts-2017.12.13         4 p STARTED      0    264b 127.0.0.1 node-1
wazuh-alerts-2017.12.13         4 r UNASSIGNED
wazuh-alerts-2017.12.13         0 p STARTED      0    264b 127.0.0.1 node-1
wazuh-alerts-2017.12.13         0 r UNASSIGNED
Not sure what happened as this is a new build. Have I possibly caused the issue by mixing old and new initially? Will it be quicker to kill this VM and start over? I want to get this build process right before we go into production.
Thanks, Mike

**Comment by JuanjiJG** [comment]
Hi again @Sonofmaurice 

If you follow the documentation, it's not necessary to edit any Elasticsearch configuration file to insert the templates. Instead, you need to edit the `kibana.yml` file and edit the `server.host` parameter and change it to `0.0.0.0` in order to make Kibana available and accesible from everywhere.

If you started with a 2.0 installation and you tried to upgrade to 3.0, it's highly possible that the installation has been broken if you didn't follow our upgrading guide.

So, I suggest you creating a new VM and follow the steps from our guide carefully, and I'm sure that you'll get Wazuh up and running in a very short time. :)

Here you have the link to the beginning of the installation process:  https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/index.html

You can install Wazuh using our RPM or DEB guide, depending on your current OS.

If you still have any more questions, doubts or problems, please let me know.

Best regards,
Juanjo

**Comment by Sonofmaurice** [comment]
Kibana.yml was the issue - I missed " off. Many many thanks and apologies for falling down the rabbit hole.
