### ISSUE TITLE
How to upgrade wazuh from 3.8.2 to 3.9.0?

### ISSUE THREAD

**Issue by cheney223** [wazuh/wazuh#3136]
I have installed wazuh 3.8.2 on my CentOS7 server. However, when I try to upgrage it to wazuh 3.9.0 via "yum upgrade wazuh-manager", it shows "No packages marked for update". How can I upgrade to the latest version?

**Comment by shauryagarg2006** [comment]
I think 3.9.0 is not yet released. Its still in rc phase. We will have to wait for some time.

**Comment by crd1985** [comment]
Hi, you can follow the progress of 3.9.0 [here](https://github.com/wazuh/wazuh/projects/23).

I am closing this issue since it is not a feature request nor a bug.

I hope you understand :)

Thank you very much.

Regards,
