### ISSUE TITLE
Error with names starting with "n" in windows events

### ISSUE THREAD

**Issue by nacho94** [wazuh/wazuh#3146]
When the name of an application or a directory starts with "n", the name is displayed correctly in the sysmon events.

![image](https://user-images.githubusercontent.com/9137028/56497090-70e36e00-64fc-11e9-96df-c6315f69be84.png)

But when these events arrive at the server, the "n" disappears so the name of the application or the directory is not displayed correctly.

2019 Apr 22 10:25:14 (DESKTOP-GPVB6HT) 192.168.1.34->EventChannel {"EventChannel":{"System":{"ProviderName":"Microsoft-Windows-Sysmon","ProviderGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","EventID":"3","Version":"5","Level":"4","Task":"3","Opcode":"0","Keywords":"0x8000000000000000","SystemTime":"2019-04-22T10:25:11.060949100Z","EventRecordID":"4456","ProcessID":"3692","ThreadID":"4272","Channel":"Microsoft-Windows-Sysmon/Operational","Computer":"DESKTOP-GPVB6HT","SeverityValue":"INFORMATION","Message":"Network connection detected:"},"EventData":{"RuleName":"","UtcTime":"2019-04-22 10:25:14.636","ProcessGuid":"{75147e5a-9685-5cbd-0000-00104e2ecf00}","ProcessId":"4128","Image":"**C:\\Users\\PCGOOD\\Downloads\\etcat-win32-1.11\\etcat-1.11\\c.exe**","User":"DESKTOP-GPVB6HT\\PCGOOD","Protocol":"tcp","Initiated":"true","SourceIsIpv6":"false","SourceIp":"192.168.1.34","SourceHostname":"DESKTOP-GPVB6HT.home","SourcePort":"64497","SourcePortName":"","DestinationIsIpv6":"false","DestinationIp":"192.168.1.124","DestinationHostname":"","DestinationPort":"31337","DestinationPortName":""}}}

![image](https://user-images.githubusercontent.com/9137028/56497124-94a6b400-64fc-11e9-8172-f22b1256cd5b.png)

**Comment by TJOSERAFAEL** [comment]
Hi @nacho94 ,

this issue has already been fixed with this PR https://github.com/wazuh/wazuh/pull/2725, as you can see this was the line https://github.com/wazuh/wazuh/pull/2725/files#diff-df254503a06ab2c0d1ebc43fdce4eeb9L62 causing the issue. 

Our next release Wazuh 3.9 includes de fix.

Best regards.

**Comment by chemamartinez** [comment]
Hi @nacho94,

Wazuh v3.9.0 has been already released. You can see its highlights [here](https://documentation.wazuh.com/current/release-notes/release_3_9_0.html), so this issue should be fixed as @TJOSERAFAEL told you.

Don't hesitate to ask us again for further questions, your feedback is very welcome.

Regards.
