### ISSUE TITLE
Incompatible field types in Kibana

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3171]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3915 | Manager/Agent | Packages/Sources | All |

The `syscheck.attrs_after` and `syscheck.win_perm_after` fields are not compatible with the field type defined in Kibana. This issue causes a warning in the visualization.

![image](https://user-images.githubusercontent.com/14975138/56677567-19dac600-66c1-11e9-8daa-8c62ff70c98f.png)

**Comment by albertomn86** [comment]
The format for the `syscheck.win_perm_after` field is restructured in this PR: https://github.com/wazuh/wazuh/pull/2944

**Comment by bah07** [comment]
This fix was added in 3.12 release.
