### ISSUE TITLE
Error in 'ftell()' function causes agent shutdown on Windows

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3178]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.8.2 | Agent | Packages | Windows |

The function `ftell()` is returning an undefined error and causes that the agent is receiving a shutdown signal.

This signal comes from the macro defined here:
https://github.com/wazuh/wazuh/blob/d1528e5577c0b0289d5285f1f1b9e7e3781342e9/src/headers/shared.h#L189
and avoid the access to an invalid offset.

```
2019/02/18 19:50:44 ossec-agent: INFO: Received exit signal.
2019/02/18 19:50:44 ossec-agent: INFO: Exiting...
2019/02/18 19:50:44 ossec-agent: CRITICAL: Ftell function failed due to [(0)-(No error)]
2019/02/18 19:50:44 ossec-agent: INFO: (1314): Shutdown received. Deleting responses.
```

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/3248 solves the issue
