### ISSUE TITLE
SCA issues

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh#3183]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager/Agent | Packages/Sources | All platforms |

### Score is null

The `score` is `null` as we can see bellow because we are dividing by 0.

```
 {"type":"summary","scan_id":1887707360,"name":"System audit for web-related vulnerabilities","policy_id":"system_audit","file":"system_audit_rcl.yml","description":"Guidance for establishing a secure configuration for web-related vulnerabilities.","passed":0,"failed":0,"invalid":16,"total_checks":16,"score":null,"start_time":1556261901,"end_time":1556261901,"hash":"9a6b564cffa3a6e212a431c2e5fba5886471c896c66e818589a5a955f43d06a1","hash_file":"a4ad3c3a1409e04217eabb884589717861b9389b68eba897093a5571a7671e2f","force_alert":"1"}
```

GDB
```
(gdb) p score
$1 = -nan(0x400000)
```

### Not applicable status (false positive)

For example with the policy `system_audit_pw.yml` check id 13000, if a file is missing the status is `not applicable` even if the rest of rules are passed or failed. In this case, we should change the behavior.

Being more specific, when a check has the condition `any`. The fact one of the rules is invalid doesn't make the whole check to be invalid, its result should be determined by the other rules if passed/failed results are found.

### Incorrect split of rule patterns

Having this rule `f:/etc/redhat-release -> IN r:^CentOS && r:release 7;`, spaces are being taken as delimiters to split the minterms located at that rule, this makes the `release 7` string to be treated as two separated minterms:

```
2019/04/26 12:20:45 sca[7021] wm_sca.c:868 at wm_sca_do_scan(): DEBUG: Checking entry: 'Check RHEL7 version'.
2019/04/26 12:20:45 sca[7021] wm_sca.c:879 at wm_sca_do_scan(): DEBUG: Rule is: f:/etc/redhat-release -> IN r:^CentOS && r:release 7;
2019/04/26 12:20:45 sca[7021] wm_sca.c:934 at wm_sca_do_scan(): DEBUG: Checking file: '/etc/redhat-release'.
2019/04/26 12:20:45 sca[7021] wm_sca.c:1610 at wm_sca_pt_matches(): DEBUG: Testing buf "CentOS Linux release 7.6.1810 (Core) " with minterm r:^CentOS -> 1
2019/04/26 12:20:45 sca[7021] wm_sca.c:1610 at wm_sca_pt_matches(): DEBUG: Testing buf "CentOS Linux release 7.6.1810 (Core) " with minterm r:release -> 1
2019/04/26 12:20:45 sca[7021] wm_sca.c:1610 at wm_sca_pt_matches(): DEBUG: Testing buf "CentOS Linux release 7.6.1810 (Core) " with minterm 7 -> 0
2019/04/26 12:20:45 sca[7021] wm_sca.c:1612 at wm_sca_pt_matches(): DEBUG: Rule test result: 0
```

This happens in the use of `strtok_r` here: https://github.com/wazuh/wazuh/blob/53245657fab410be5d71f224a330bcfb5bb9bd16/src/wazuh_modules/wm_sca.c#L1602

And makes, for example, to fail the requirements in a CentOS 7 for the policy `cis_rhel7_linux_rcl.yml` because the result is 0 instead of 1.

```
2019/04/26 12:07:21 sca: INFO: Skipping policy 'cis_rhel7_linux_rcl.yml': 'Check RHEL7 version'.
```

**Comment by JuantAldea** [comment]
The "Incorrect split of rule patterns" happens because strtok treats the delimiter string as a list of single character delimiters. We should implement our own split function.
