### ISSUE TITLE
Problem with syscollector endpoint filters

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3184]
Hi team,

I'm doing the integrated syscollector endpoint tests and I found the following situation, the vendor is "Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>":
```bash
root@fc8540c61242:/# curl -u foo:bar -X GET "http://localhost:55000/syscollector/000/packages?pretty&vendor="Ubuntu""
{
   "error": 0,
   "data": {
      "items": [],
      "totalItems": 0
   }
}
root@fc8540c61242:/# curl -u foo:bar -X GET "http://localhost:55000/syscollector/000/packages?pretty&vendor="Ubuntu%20Core%20developers%20%3Cubuntu-devel-discuss@lists.ubuntu.com%3E""
{
   "error": 609,
   "message": "Param not valid. Valid characters: a-z, A-Z, 0-9, ., _, -, +.  Field: vendor"
}
root@fc8540c61242:/# curl -u foo:bar -X GET "http://localhost:55000/syscollector/000/packages?pretty&vendor="Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>""
bash: ubuntu-devel-discuss@lists.ubuntu.com: No such file or directory
```

The same thing happens with all parameters that contain non-alphanumeric characters and all are equally strict, for example with the parameter name if we look for binutils, you will find only one because the others that contain this string are called binutils-{string}.

Best regards,
Adri

**Comment by druizz90** [comment]
This issue will be solved in [#400](https://github.com/wazuh/wazuh-api/pull/400). Regular expression for validating `vendor` field was updated.
