### ISSUE TITLE
Wrong generated checksum with files larger than max size

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#3198]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3916 | Agent | Packages/Sources | Any |

We have found an error when monitoring files that exceeded the maximum size configured for a file
In the `internal_options.conf`. Option: `syscheck.file_max_size=1024`
​
When a file is modified and its size is bigger than 1024 kb, an erroneous deletion alert appears. This is because the return code of the function that calculates the hash is correct when it should throw an error to discard that event.

It also generates a  wrong checksum that the manager discards because it is not able to decode

```
# Agent
DEBUG: (6211): File '/home/test/file'
WARNING: '/home/test/file' filesize is larger than the maximum allowed (1024 MB). File skipped.

# Manager
at fim_db_search: Agent '001' Couldn't decode fim sum '!0:root:root::' from file '/home/test/file'.
```

**Comment by albertomn86** [comment]
Merged in https://github.com/wazuh/wazuh/pull/3190
