### ISSUE TITLE
Unused file descriptors in wazuh-modulesd

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3201]
|Wazuh version|Install type|Install method|
|---|---|---|
| v3.9.0 and lower | Manager/Agent | Packages/Sources |

When `wazuh-modulesd` forks a child module, the parent file descriptors are copied to the child process. These inherited file descriptors are not used by the child process and there's no reason to keep them.

This issue is described in the following example.
Enabling the `DockerListener` module we can check that the file descriptors for the files ` /var/ossec/etc/ossec.conf` and `/var/ossec/etc/internal_options.conf` were inherited from the parent procees when reads its configuration.

```
[root@centos7 ~]# ls -la  /proc/`pidof python /var/ossec/wodles/docker/DockerListener`/fd
total 0
dr-x------. 2 root ossec  0 Apr 29 12:19 .
dr-xr-xr-x. 9 root ossec  0 Apr 29 12:18 ..
lrwx------. 1 root ossec 64 Apr 29 12:19 0 -> /dev/null
l-wx------. 1 root ossec 64 Apr 29 12:19 1 -> pipe:[1601130]
lr-x------. 1 root ossec 64 Apr 29 12:19 16 -> /dev/urandom
l-wx------. 1 root ossec 64 Apr 29 12:19 2 -> pipe:[1601130]
lrwx------. 1 root ossec 64 Apr 29 12:19 3 -> socket:[1601132]
lrwx------. 1 root ossec 64 Apr 29 12:19 4 -> socket:[1657062]
lr-x------. 1 root ossec 64 Apr 29 12:19 6 -> /var/ossec/etc/ossec.conf
lr-x------. 1 root ossec 64 Apr 29 12:19 8 -> /var/ossec/etc/internal_options.conf
```

### Possible solution:

Opening the config files in the parent process using the `O_CLOEXEC` flag blocks the inheritance of file descriptors. We can add this flag using several options:

1. Using the `e` option in the `fopen()` function (since GLIBC 2.7):
```C
fp = fopen(def_file, "re");
```
http://man7.org/linux/man-pages/man3/fopen.3.html

2. Set the flag `FD_CLOEXEC` using the function `()`:
```C
fp = fopen(def_file, "r");
...
fcntl(fileno(fp), F_SETFD, FD_CLOEXEC);
```
http://man7.org/linux/man-pages/man2/fcntl.2.html

**Comment by sergiovp** [comment]
## Reproduce the issue

We have reproduced the issue in differents OS.

+ CentOS7
~~~
[root@AgentCentOS7 wazuh]# ls -la  /proc/`pidof python /var/ossec/wodles/docker/DockerListener`/fd
total 0
dr-x------. 2 root ossec  0 may 31 10:42 .
dr-xr-xr-x. 9 root ossec  0 may 31 10:42 ..
lrwx------. 1 root ossec 64 may 31 10:42 0 -> /dev/null
l-wx------. 1 root ossec 64 may 31 10:42 1 -> pipe:[1108867]
lr-x------. 1 root ossec 64 may 31 10:42 14 -> /dev/urandom
l-wx------. 1 root ossec 64 may 31 10:42 2 -> pipe:[1108867]
lrwx------. 1 root ossec 64 may 31 10:42 3 -> socket:[1108870]
lrwx------. 1 root ossec 64 may 31 10:42 4 -> socket:[1108876]
~~~

+ Ubuntu18
~~~
root@AgentUbuntu18:/var/ossec# ls -la  /proc/`pidof python /var/ossec/wodles/docker/DockerListener`/fd
total 0
dr-x------ 2 root ossec  0 May 31 10:55 .
dr-xr-xr-x 9 root ossec  0 May 31 10:55 ..
lrwx------ 1 root ossec 64 May 31 10:55 0 -> /dev/null
l-wx------ 1 root ossec 64 May 31 10:55 1 -> 'pipe:[1369613]'
lr-x------ 1 root ossec 64 May 31 10:55 16 -> /dev/urandom
l-wx------ 1 root ossec 64 May 31 10:55 2 -> 'pipe:[1369613]'
lrwx------ 1 root ossec 64 May 31 10:55 3 -> 'socket:[1371343]'
lr-x------ 1 root ossec 64 May 31 10:55 4 -> /var/ossec/var/wodles/syscollector
lr-x------ 1 root ossec 64 May 31 10:55 5 -> /dev/urandom
lrwx------ 1 root ossec 64 May 31 10:55 6 -> 'socket:[1371346]'
~~~

We may apply the second solution:
~~~
fp = fopen(def_file, "r");
...
fcntl(fileno(fp), F_SETFD, FD_CLOEXEC);
~~~
due best compatibility.

**Comment by sergiovp** [comment]
We have debugged with gdb the program looking for the place where child process inherit file descriptors.

## Next Step
Fix it adding **FD_CLOEXEC** in the function.

**Comment by sergiovp** [comment]
Added `fcntl(fileno(fp), F_SETFD, FD_CLOEXEC);` at `src/shared/validate_op.c` and `src/os_xml.c` files.

## Next Step
Check the error is fixed

**Comment by sergiovp** [comment]
After check if the error was fixed, I discovered that there were other files descriptors which are inherit.

I'll check which files are, running a script.

**Comment by sergiovp** [comment]
+ `lr-x------ 1 root ossec 64 Jun  5 09:26 4 -> /var/ossec/var/wodles/syscollector`
+ `lr-x------ 1 root ossec 64 Jun  5 09:26 8 -> /var/ossec/ruleset/sca/cis_debian_linux_rcl.yml`
+ `l-wx------ 1 root ossec 64 Jun  5 09:26 8 -> /var/ossec/logs/ossec.log`

This are the files which continues been inherit.

## Next Step
Fix it adding **fcntl(fileno(fp), F_SETFD, FD_CLOEXEC);** when the file is opened.
