### ISSUE TITLE
3.0.0_2 - Syscheck/Rootcheck scans not happening.

### ISSUE THREAD

**Issue by aslap5** [wazuh/wazuh#321]
I have a lab environment and a test environment both with the same problem.  The syscheck scans only occur when the agent is restarted.  Rootcheck hasn't happened since the agents were installed.

I believe the issue is with my config file.  I used the same file between the two.  Right now I have the scan frequency set to 60 seconds to test if it's working.  I've included the last few lines of the ossec.log file as well as the config file.

Log was pulled 10 minutes after the last message.  It should have scanned in that period.
`2017/12/19 14:53:02 ossec-logcollector: WARNING: Duplicated log file given: '/var/ossec/logs/active-responses.log'.
2017/12/19 14:53:02 ossec-logcollector: WARNING: Duplicated log file given: '/var/log/auth.log'.
2017/12/19 14:53:02 ossec-logcollector: WARNING: Duplicated log file given: '/var/log/syslog'.
2017/12/19 14:53:02 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2017/12/19 14:53:02 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/kern.log'.
2017/12/19 14:53:02 ossec-logcollector: INFO: Started (pid: 2748).
2017/12/19 14:53:32 ossec-syscheckd: INFO: Syscheck scan frequency: 60 seconds
2017/12/19 14:54:02 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2017/12/19 14:54:02 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2017/12/19 14:55:12 ossec-logcollector: INFO: (1904): File not available, ignoring it: '/var/log/messages'.
`

Agent.conf and ossec.conf from the agent are in reply messages.

**Comment by aslap5** [comment]
```
<agent_config>
 <!-- Policy monitoring -->
 <rootcheck>
  <disabled>no</disabled>
  <check_unixaudit>yes</check_unixaudit>
  <check_files>yes</check_files>
  <check_trojans>yes</check_trojans>
  <check_dev>yes</check_dev>
  <check_sys>yes</check_sys>
  <check_pids>yes</check_pids>
  <check_ports>yes</check_ports>
  <check_if>yes</check_if>

  <!-- Frequency that rootcheck is executed - every 6 hours -->
  <frequency>60</frequency>

  <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
  <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>

  <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
  <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt</system_audit>
  <system_audit>/var/ossec/etc/shared/cis_debian_linux_rcl.txt</system_audit>

  <skip_nfs>yes</skip_nfs>
 </rootcheck>

 <!-- File integrity monitoring -->
 <syscheck>
  <disabled>no</disabled>

  <!-- Frequency that syscheck is executed default every 12 hours -->
  <frequency>60</frequency>

  <scan_on_start>yes</scan_on_start>

  <!-- Generate alert when new file detected -->
  <alert_new_files>yes</alert_new_files>

  <!-- Directories to check  (perform all possible verifications) -->
  <directories check_all="yes">/etc/bind</directories>
  <directories check_all="yes">/etc</directories>
  <directories check_all="yes">/boot</directories>
  <directories check_all="yes">/usr</directories>
  <directories check_all="yes">/bin,/sbin,/usr/local/sbin</directories>
  <directories check_all="yes">/var</directories>
  <directories check_all="yes">/dev</directories>

   <!-- Don't ignore files that change more than 3 times -->
    <auto_ignore>no</auto_ignore>

    <!-- Files/directories to ignore -->

    <!-- Check the file, but never compute the diff -->
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>
    </syscheck>

  <!-- Log data collection -->
  <localfile>
      <log_format>syslog</log_format>
      <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/auth.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/syslog</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/dpkg.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/kern.log</location>
  </localfile>

  <!-- Active response -->
  <active-response>
    <disabled>yes</disabled>
  </active-response>

  <!-- Open-SCAP -->
  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-ubuntu-1604-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
  </wodle>
</agent_config>
```

**Comment by aslap5** [comment]
```
<ossec_config>
  <client>
    <server>
      <address>x.x.x.x</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <config-profile>ubuntu</config-profile>
    <notify_time>60</notify_time>
    <time-reconnect>300</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>

  <client_buffer>
    <!-- Agent buffer options -->
    <disable>no</disable>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>

 <!-- Policy monitoring -->
  <rootcheck>
    <disabled>no</disabled>

    <!-- Frequency that rootcheck is executed - every 12 hours -->
    <frequency>60</frequency>

    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>

    <system_audit>/var/ossec/etc/shared/system_audit_rcl.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/system_audit_ssh.txt</system_audit>
    <system_audit>/var/ossec/etc/shared/cis_debian_linux_rcl.txt</system_audit>

    <skip_nfs>yes</skip_nfs>
  </rootcheck>

  <wodle name="open-scap">
    <disabled>yes</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-debian-8-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_common</profile>
    </content>
    <content type="oval" path="cve-debian-oval.xml"/>
  </wodle>

  <!-- File integrity monitoring -->
  <syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>60</frequency>

    <scan_on_start>yes</scan_on_start>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin,/boot</directories>

    <!-- Files/directories to ignore -->
   
    <!-- Check the file, but never compute the diff -->
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>
  </syscheck>

  <!-- Log analysis -->
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/auth.log</location>
  </localfile>

  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/syslog</location>
  </localfile>

  <localfile>
    <log_format>command</log_format>
    <command>df -P</command>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tan |grep LISTEN |grep -v 127.0.0.1 | sort</command>
    <frequency>360</frequency>
  </localfile>

  <localfile>
    <log_format>full_command</log_format>
    <command>last -n 5</command>
    <frequency>360</frequency>
  </localfile>

  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
  </active-response>

</ossec_config>

```

**Comment by smtszk** [comment]
I have exactly the same issue.

**Comment by aslap5** [comment]
I did a fresh install of this in my lab version 3.0.0_2 and syschecks are now running on my defined frequency.  I'll confirm rootcheck is running shortly.

The only thing that differs from my previous installation is what is contained in the agent.conf file.  The new installation's agent.conf only has active response set to disabled and my directories to monitor/ignore.   I assume the new version stumbles over some of the settings being in both configuration files.  If my rootcheck runs as scheduled I'll move these configs over to my test environment and confirm this resolves the issue in an existing installation

Here is a sample

```
<agent_config>
  <syscheck>
  <!-- Directories to check  (perform all possible verifications) -->
  <directories check_all="yes">/etc</directories>
  <directories check_all="yes">/boot</directories>
  <directories check_all="yes">/usr</directories>
  <directories check_all="yes">/bin,/sbin,/usr/local/sbin</directories>
  <!-- directories check_all="yes">/var</directories -->

  <!-- Directories to check  (attribute checks only - owner, group, permissions) -->
  <directories check_owner="yes" check_group="yes" check_perm="yes">/etc/hosts</directories>

  <!-- Files/directories to ignore -->
  <ignore>/etc/mtab</ignore>
  <ignore>/etc/hosts.deny</ignore>
  <ignore>/etc/mail/statistics</ignore>
  <ignore>/etc/random-seed</ignore>
  <ignore>/etc/random.seed</ignore>
  <ignore>/etc/adjtime</ignore>
  <ignore>/etc/httpd/logs</ignore>
  <ignore>/etc/utmpx</ignore>
  <ignore>/etc/wtmpx</ignore>
  <ignore>/etc/cups/certs</ignore>
  <ignore>/etc/dumpdates</ignore>
  <ignore>/etc/svc/volatile</ignore>

  <!-- Check the file, but never compute the diff -->
  <nodiff>/etc/ssl/private.key</nodiff>

  <skip_nfs>yes</skip_nfs>
  </syscheck>

  <!-- Active response -->
  <active-response>
    <disabled>yes</disabled>
    <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
  </active-response>
</agent_config>
```

**Comment by aslap5** [comment]
rootcheck ran successfully after syscheck.  Going to let it run overnight.

If there's anything I can look at to narrow down what's happening let me know.  As of now I think the config files are stumbling over one another.

**Comment by vikman90** [comment]
Hi @aslap5 and @smtszk,

I have tested your configuration with a frequency of 10 seconds and and it seems to work OK. This is my log:

```
2017/12/20 15:16:19 ossec-syscheckd: INFO: Syscheck scan frequency: 10 seconds
2017/12/20 15:16:49 ossec-syscheckd: INFO: Starting syscheck scan (forwarding database).
2017/12/20 15:16:49 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2017/12/20 16:40:55 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2017/12/20 16:41:05 ossec-syscheckd: INFO: Ending syscheck scan (forwarding database).
2017/12/20 16:41:25 ossec-syscheckd: INFO: Starting syscheck scan.
```

Some caveats:

- As you said, your configuration at `agent.conf` overlaps with the `ossec.conf`. The effect is that duplicate directories entries will be scanned twice.
- Syscheck inserts delays between scanned files in order to preserve CPU and network. By default it will pause during 2 seconds for each 15 scanned files. This is a rate of 7,5 files per second. The agent where I did the test scanned 36418 files, that's why it toke 1:24 hours to complete the scan. You can speed up this process by modifying `syscheck.sleep` and `syscheck.sleep_after` in file [etc/internal_options.conf](https://github.com/wazuh/wazuh/blob/master/etc/internal_options.conf#L147-L152), but I recommend you to change them only for testing purposes.
- The `frequency` option is not very accurate since Syscheck was designed to be CPU lightweight, so it makes some delays between cycles.

Apart of these points I haven't found problems in Syscheck.

If you want to follow the agent's Syscheck reports, you may use:

```sh
tail -fn1000 /var/ossec/queue/syscheck/\(agentname\)\ ip-\>syscheck
```

Let `agentname` be the name of the agent (between parentheses) and `ip` the source address (or `any`). This command lets you see if the agent is reporting file signatures.

If you find that Syscheck doesn't report files or it takes longer than expected, please share with us your logs and let us know if Syscheck is reporting.

Thank you for your feedback.
Best regards.

**Comment by aslap5** [comment]
I think caveat one+two was the issue.  Although it says it's going to ignore duplicate directories at startup according to you it's not.   In the working configuration I have no directories setup to be monitored in ossec.conf and everything defined in agent.conf.

I'm going to monitor both environments and close the issue if things continue working correctly.

Thanks for the response and thanks for the product.

**Comment by vikman90** [comment]
Hi @aslap5,

I'm sorry I forgot to clarify a nuance: You're right, duplicate directories are discarded, they will be scanned once only. But this only occurs if the directory entry is the same.

For instance, in your configuration:

```xml
<!-- Default ossec.conf -->
<directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
<directories check_all="yes">/bin,/sbin,/boot</directories>

<!-- Custom agent.conf -->
<directories check_all="yes">/etc</directories>
<directories check_all="yes">/boot</directories>
<directories check_all="yes">/usr</directories>
<directories check_all="yes">/bin,/sbin,/usr/local/sbin</directories>
<directories check_owner="yes" check_group="yes" check_perm="yes">/etc/hosts</directories>
```

In fact, `/etc`, `/boot`, `/usr` and `/sbin` are doubled, Syscheck will detect this condition and discard the redefinition. However, `/usr/bin`, `/usr/sbin`, `/usr/local/sbin` and `/etc/hosts` overlap with `/usr` and `/etc`. I this case, Syscheck will not detect the overlap and it will scan _/usr/bin_, _/usr/sbin_, _/usr/local/sbin_ and _/etc/hosts_ twice.

This behavior has the advantage of allowing overwrite some options, for instance, if you want to monitor _/usr_ periodically but you want to monitor _/usr/bin_ in realtime-mode.

By the way, since you only want the owner, group and permissions from `/etc/hosts`, I recommend you to restrict the first declaration of `/etc` to discard `/etc/hosts`:

```xml
<directories check_all="yes" restrict="!^/etc/hosts$">/etc</directories>
```

Hope it help.

Best regards.

**Comment by aslap5** [comment]
Everything looks to be working correctly now.  Thanks for the help.

I have 1 last question regarding syscheck.  Specifically around rules and how they are triggered.  PCI requires alerts generated on log file size reduced.  There's already a rule in wazuh for that but what triggers it?  Is it <syscheck> or <localfile> that generates that alert?

**Comment by vikman90** [comment]
Those alerts are reported by Logcollector for each log file it's monitoring.

There are two rules:
1. If the file itself shrinks (like `echo -n > mylog.txt`):
```
** Alert 1513972225.4107: - ossec,attacks,pci_dss_10.5.2,pci_dss_11.4,gpg13_10.1,
2017 Dec 22 11:50:25 ubuntu->ossec-logcollector
Rule: 592 (level 8) -> 'Log file size reduced.'
ossec: File size reduced (inode remained): '/root/mylog.txt'.
```

2. When the file is rotated (like `mv mylog.txt mylog.txt.rotate && touch mylog.txt`):
```
** Alert 1513972271.4347: - ossec,pci_dss_10.5.2,pci_dss_10.5.5,gpg13_10.1,
2017 Dec 22 11:51:11 ubuntu->ossec-logcollector
Rule: 591 (level 3) -> 'Log file rotated.'
ossec: File rotated (inode changed): '/root/mylog.txt'.
```

**Comment by Ossec-HIDS** [comment]
hi all,

i need help i have created dir monitoring for windows & linux as below in /var/ossec/etc/sharedagent.conf location:

Note :Linux FIM is working when we add/delete to dir which we created below but not with windows please help

<agent_config os="Linux">
 <localfile>
        <location>/home/riggsc/test/test.txt</location>
        <log_format>syslog</log_format>
    </localfile>
 <syscheck>
    <directories realtime="yes" report_changes="yes" check_all="yes">/home/riggsc/test</directories>
 </syscheck>
</agent_config>

<agent_config os="Windows">
<localfile>
    <location>C:\pruthviraj-ossec</location>
    <log_format>syslog</log_format>
</localfile>
</agent_config>

<agent_config os="Windows">
<localfile>
    <location>D:\test/*</location>
    <log_format>syslog</log_format>
</localfile>
 <syscheck>
    <directories realtime="yes" report_changes="yes" check_all="yes">D:\test</directories>
 </syscheck>
</agent_config>

Below are errors i see : in agent logs (client machine)
2018/12/24 14:17:08 ossec-logcollector(1103): ERROR: Could not open file 'D:\test/*' due to [(9)-(Bad file descriptor)].

 ossec-syscheckd(1758): ERROR: Unable to open registry key using 32 bit registry: 'Software\Microsoft\Windows\CurrentVersion\RunOnceEx'.
