### ISSUE TITLE
Disabling all FIM checksums causes critical error

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#3214]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| v3.9.0 and lower| Manager/Agent | Packages&Sources | All|

<br></br>
In `ossec.conf` at FIM config section, when writing a directories entry, If `check_all` is `disabled` , or all single checks are `disabled`, syscheck throws an error:
<br></br>
**Error output**:
```
2019/04/26 11:01:45 ossec-syscheckd[17303] syscheck.c:320 at main(): DEBUG: Starting ...
2019/04/26 11:01:45 ossec-syscheckd[17303] config.c:55 at Read_Syscheck_Config(): DEBUG: (6287): Reading configuration file: '/var/ossec/etc/ossec.conf'.
2019/04/26 11:01:45 ossec-syscheckd[17303] syscheck-config.c:632 at read_attr(): WARNING: (6677): No option provided for directories: '/test', ignoring it.
2019/04/26 11:01:45 ossec-syscheckd[17303] config.c:246 at ReadConfig(): ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
2019/04/26 11:01:45 ossec-syscheckd[17303] syscheck.c:329 at main(): CRITICAL: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
ossec-syscheckd: Configuration error. Exiting
```

<br></br>

**Example lines to reproduce the error:**
`<directories check_all="no">/test</directories>`
`<directories check_sum="no">/test</directories>`
`<directories check_sha1sum="no" check_md5sum="no">/test</directories>`

**Comment by Lopuiz** [comment]
Hello team,

New FIM solves it. I am going to close this issue.

Regards,
Eva
