### ISSUE TITLE
wm_sca_check_dir tries to open directories as files

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3215]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9-rc9 | -- | -- | -- |

Given a rule such as  `d:dir -> r:target -> r:content`
wm_sca_check_dir would check files in `dir` matching the `r:target` regex and would also recursively explore the whole directory tree hanging from `dir`.
The problem arises when there is a folder matching the regex, as it will be passed to `wm_sca_check_file` for checking.

Right now this does not trigger any problem, as `wm_sca_check_file` will skip the directory as it cannot open it, but the overall logic is flawed.

With a simplified version of the code:
```
int wm_sca_check_dir(dir) 
{
    while (file = readdir(dir)) { (wm_sca.c:~1652)
        if (OS_Regex(file + 2, entry->d_name)) {
            check_result = wm_sca_check_file(file); (wm_sca.c:~1665) (1)
        }
        // non exclusive IFs!
        if (ISDIR(file)) { (wm_sca.c:~1687)
            check_result = wm_sca_check_dir(file); (2)
        }
    }
    return result;
}
```
```
int wm_sca_check_file(file) 
{
    int return_code = 0;
    for (file) {
        FILE fp = fopen(file);
        while (fgets(fopen) { (wm_sca.c:1433) (3)
            return_code = {...}
        }
    }
    return return_code;
}
```
A Regex-matching directory will be passed to  `wm_sca_check_file` at  (1), read nothing at (3), making it pass, and finally get tested at (2).

**Comment by chemamartinez** [comment]
Merged #3235
