### ISSUE TITLE
AIX service file doesn't work

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#3224]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.10.0 | Agent | Packages/Sources | AIX |

Hi team,

I noticed that the AIX's service file doesn't work. The error is caused by a wrong path to the `ossec-control` script: https://github.com/wazuh/wazuh/blob/8b3fa8020a223ec7c73d1a3172e7f7cd6130d5bd/src/init/ossec-hids-aix.init#L15-L18

This path should be `${DIRECTORY}/bin/ossec-control` instead of `${DIRECTORY}/ossec-control`.

Regards.

**Comment by alberpilot** [comment]
Merged 3.9.2. Thanks @BraulioV
