### ISSUE TITLE
SCA does not follow symbolic links

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3228]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9 | -- | -- | All|

Currently SCA does not follow symbolic links when checking either directories or files.
This affects functions `wm_sca_check_dir` and `wm_sca_check_file`.

**Comment by JuantAldea** [comment]
See https://github.com/wazuh/wazuh/pull/3286/commits/bb6e8a8baedf26a379836a582f9b7419ae1f4ae8

**Comment by chemamartinez** [comment]
This issue has been added at (https://github.com/wazuh/wazuh/commit/bb6e8a8baedf26a379836a582f9b7419ae1f4ae8) and reviewed. It is included as a part of the [SCA refactor](https://github.com/wazuh/wazuh/pull/3286) included in 3.10.

Closing it.
