### ISSUE TITLE
Setting internal option 'sca.request_db_interval' to '0' can make wazuh-modulesd to crash

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#3233]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3918 | Manager/Agent | Packages/Sources | Any |

Bug description
---
If the option `sca.request_db_interval` is set to **0**, `wazuh-modulesd` could crash (if an integrity fails).

Steps to reproduce
---
For example, in the manager (with `sca` enabled):

1) Change this line in `/var/ossec/etc/internal_options.conf`:
```
# Security Configuration Assessment DB request interval in minutes [0..60]
# This option sets the maximum waiting time to resend a scan when the DB integrity check fails
sca.request_db_interval=0
```
2) Delete the manager database (`/var/ossec/queue/db/000.db`).

3) Restart the manager.

Trace
---
There's an inconsistency between what's said in the documentation about this option and the `internal_options`/code.

- In the documentation (https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#security-configuration-assessment) it says that the accepted range is "between 1 and 60". In the internal options file, as you can see above it says the interval is "[0..60]". This last one is the real accepted range as we can see in our code:

https://github.com/wazuh/wazuh/blob/f9c8a0d1a6bba263a4332251da9650800fab23aa/src/wazuh_modules/wm_sca.c#L129

Later, the following operation is performed:

https://github.com/wazuh/wazuh/blob/f9c8a0d1a6bba263a4332251da9650800fab23aa/src/wazuh_modules/wm_sca.c#L2542

This can cause a division by 0, which causes the crash.

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/3254 solves the issue
