### ISSUE TITLE
Plugin capabilities

### ISSUE THREAD

**Issue by MadsRC** [wazuh/wazuh#3241]
Reading through the documentation and the src, I don't see any support for adding additional features through plugins (Or something similar).

Looking at utilizing Wazuh to solve some issues at a client of mine, it would have been great if it was possible to add the functionality that competing products have. Specifically I'm looking at features such as Endpoint Isolation (Having the agent configure the host firewall to only allow traffic to and from the Manager cluster) and adding a Binary Archive (archiving every binary/file executed on the endpoint). Those are features that other endpoint protection products have - Being able to implement them as plugins would be amazing.

**Comment by TJOSERAFAEL** [comment]
Hi @MadsRC ,

wazuh does support plugins in form of Python scripts using `ossec-integratord` mainly used to connect with external APIs but you can launch any script with it.

For example for the Virtustotal integration https://documentation.wazuh.com/3.x/user-manual/capabilities/virustotal-scan/index.html

Here you have a nice tutorial for a custom integration https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/.

Best regards.

**Comment by MadsRC** [comment]
Hi @TJOSERAFAEL  - Thanks!

That seems to solve some of it. It seems that the daemon only runs on the manager, or does it/can it run on the agents aswell?

My usecase of isolating an endpoint would require the python script to run locally on the agent.

**Comment by TJOSERAFAEL** [comment]
Hi @MadsRC ,

`ossec-integratord` runs on the manager only, but for a work around Wazuh has also the capability of launching an active response for a certain event.

With active response you can execute a custom script on any agent that receives the event, take a look at our documentation: https://documentation.wazuh.com/3.x/user-manual/capabilities/active-response/how-it-works.html

I hope it works for your use case.

Best regards.
