### ISSUE TITLE
Active Response is Sending Wrong AlertID to Custom Active Response Command

### ISSUE THREAD

**Issue by keassol** [wazuh/wazuh#3247]
have the following command/response in ossec.conf:

```
  <command>
    <name>Stop-Nuisance-Auth</name>
    <executable>stopNuisanceAuth.php</executable>
    <timeout_allowed>no</timeout_allowed>
    <expect />                           
  </command>

  <active-response>                  
    <disabled>no</disabled>           
    <command>Stop-Nuisance-Auth</command>
    <location>server</location>                 
    <rules_id>110035, 110999, 995503, 110992</rules_id>               
  </active-response>
```

what stopNuisanceAuth.php gets:

> arg0: /var/ossec/active-response/bin/stopNuisanceAuth.php
> arg1: add
> arg2: -
> arg3: -
> arg4: 1557154264.382860
> arg5: 110035
> arg6: /var/log/remotesyslog/hormel.log

Looks good however arg4 is the wrong alertID and instead is the previous alertID.  Consider the following two alerts from /var/ossec/logs/alerts/alerts.log: 

> ** Alert 1557154264.382860: mail  - local,syslog,sshd,gpg13_4.3,
> 2019 May 06 07:51:04 other.example.com->/var/log/remotesyslog/differentServer.log
> Rule: 1002 (level 2) -> 'Unknown problem somewhere in the system.'
> May  6 07:51:04 other.example.com - 1,2019/05/06 07:51:04,001606027415,SYSTEM,proxy,etc,etc,etc
> 
> ** Alert 1557154278.383397: - local,syslog,sshd,
> 2019 May 06 07:51:18 errorServer.example.com->/var/log/remotesyslog/errorServer.log
> Rule: 110035 (level 6) -> 'Auth attempts on errorServer, assigning as rule 110035, to trigger active response.'
> May  6 07:51:17 errorServer.example.com  inbound/pass1: attacker.otherexample.com[x.x.x.x] 1557154277-553284-4242-76477-1 1557154277 1557154277 RECV - - 2 83 504 Error: encryption required for requested authentication mechanism [-]
>

**Comment by sergiospa** [comment]
Hi keassol,

Active-response can't still send dynamic fields to commands. How are you sending those arguments to `stopNuisanceAuth.php`? Maybe it is the script which is not fetching well the correct data. Also, the field `expect` is not required if you're not going to use it.

**Comment by keassol** [comment]
I dont believe it is a dynamic field.  According to [this doc](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/remediation-faq.html), and how I have used it in the past, one of the arguments sent to the script should be the alertID which it is sending, it is just sending the wrong alertID:

`<SCRIPT-NAME> <ACTION> <USER> <IP> <ALERT-ID> <RULE-ID> <AGENT> <FILENAME>`

Everything that the script receives, including the ruleID is correct, except for the alertID, which is the previous alertID.  

I have had it working this way for years and all of the sudden it stopped working.  In may have stopped working with the last update but I dont know that for sure.

**Comment by sergiospa** [comment]
Sorry, I misunderstood the context. I'll check this and get back here soon.

**Comment by sergiospa** [comment]
Indeed, you are right **keassol**. I have created a new issue for our development team to take a look at this problem. You can keep track of it if you want to be up to date on the progress: https://github.com/wazuh/wazuh/issues/3267

Thank you for your contribution! We're so happy to receive reports and suggestions from our community.

Best regards,
Sergio.
