### ISSUE TITLE
Feature request : agent_upgrade should have an option to specify the installation path

### ISSUE THREAD

**Issue by mi-cha-el** [wazuh/wazuh#3262]
Hi !

Just a little suggestion for the agent remote update : agent_upgrade should have an option to specify the installation path when the agent is running on windows.

For my agents running on windows, I chose to use a specific path. When I launched an upgrade from 3.8.2 to 3.9.0 , agent_upgrade successfully sent the WPK file to my windows server and did a new install in the default path, losing the content of client.keys and local_internal_options.conf .

If possible, could you add a -p or --path option allowing to specify the install path on the remote windows server. Example : 

`# /var/ossec/bin/agent_upgrade -d -p "C:\ossec\" -a 012`

Thanks and keep up the good work !

**Comment by snaow** [comment]
Hi @mi-cha-el,

Thanks for reporting the issue and sorry for the inconveniences caused.

We are tracking this bug in the following issue: https://github.com/wazuh/wazuh/issues/2494

Please, feel free to comment and track the progress in the above issue.
Closing the issue.
