### ISSUE TITLE
Upgrade OVF Appliance 3.8.2 to 3.9.0

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh#3268]
# Upgrade test

Appliance OVF

| 3.8.2 | rev | branch |

## RPM (Linux)

Hi, i cannot upgrade because my wazuh.repo file is empty, i cannot find anything on the github. What i need to add in it? (i dl the 3.9.0 ovf and same issue with the file /etc/yum/yum.repos.d/wazuh.repo, empty :/

thank you for your help!

**Comment by Cerv1** [comment]
Hi @b4b857f6ee,

I hope you're doing well. You can find the official repositories for `wazuh-manager` [here](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#wazuh-server-rpm) and the official repositories for `wazuh-agent` [here](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_rpm.html). 

If you have any problem, please don't hesitate to ask here again.

Best regards,
Cerv1.

**Comment by b4b857f6ee** [comment]
Cerv1, this not a problem because i have wget the package https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.0_6.7.1.zip
But when i launch the same command in local.
sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install wazuhapp-3.9.0_6.7.1.zip

But he try : Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/wazuhapp-3.9.0_6.7.1.zip/wazuhapp-3.9.0_6.7.1.zip-6.5.4.zip

If he didn't get the proxy this is cannot work. 
maybe i can download it with my wget configure wiht my proxy and launch in local the command to use the package i have previously download?

**Comment by Cerv1** [comment]
Hi again @b4b857f6ee,

Sure! You can use the following command to install it locally:
```
sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install file:///path/to/file/wazuhapp-3.9.0_6.7.1.zip
```

Hope this helps!

Best regards,
Cerv1.

**Comment by b4b857f6ee** [comment]
This is the problem because the installer do not use system proxy :/

sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install wazuhapp-3.9.0_6.7.1.zip
Attempting to transfer from wazuhapp-3.9.0_6.7.1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/wazuhapp-3.9.0_6.7.1.zip/wazuhapp-3.9.0_6.7.1.zip-6.5.4.zip
Error: Client request error: connect ETIMEDOUT 151.101.38.222:443
Plugin installation was unsuccessful due to error "Client request error: connect ETIMEDOUT 151.101.38.222:443"

**Comment by b4b857f6ee** [comment]
the problem is the script didn't used my system proxy

**Comment by Cerv1** [comment]
Hi @b4b857f6ee,

I this problem solved then? 

Please, let me know if you're still facing this problem.

Regards,
Cerv1.

**Comment by b4b857f6ee** [comment]
No. I need to look at the command line if i can force to use specific proxy. Or i need to reinstall it x).

**Comment by b4b857f6ee** [comment]
I have try adding export http_proxy=http://myproxy:portproxy and the command for http and https

And i get this :

/usr/share/kibana/bin/kibana-plugin install wazuhapp-3.9.0_6.7.1.zip
Found previous install attempt. Deleting...
Attempting to transfer from wazuhapp-3.9.0_6.7.1.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/wazuhapp-3.9.0_6.7.1.zip/wazuhapp-3.9.0_6.7.1.zip-6.5.4.zip
Picked up proxy http://myproxy:portproxy from environment variable.
Plugin installation was unsuccessful due to error "No valid url specified."

**Comment by b4b857f6ee** [comment]
Ok this is not working, https://artifacts.elastic.co/downloads/kibana-plugins/wazuhapp-3.9.0_6.7.1.zip/wazuhapp-3.9.0_6.7.1.zip-6.5.4.zip
That's why.

**Comment by Cerv1** [comment]
Hi again @b4b857f6ee,

As you can see, that URL isn't working for you. 

Could you replace the URL with the following one?

`https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.0_6.7.1.zip`

Regards,
Cerv1.

**Comment by jesusgn90** [comment]
Hi @b4b857f6ee and @Cerv1 ,

As you can see in https://www.elastic.co/guide/en/kibana/6.7/install-plugin.html, there are several ways to successfully install a plugin for Kibana.

Since you managed to `wget` the zip package, you can make a local installation, your first attempt was wrong because `file:///` was missing in your command @b4b857f6ee.

Here is an example on how to install plugins locally:

```sh
# File is located at /tmp/wazuhapp-3.9.0_6.7.1.zip
sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuhapp-3.9.0_6.7.1.zip
```

The above command differs from your command just in the `file:///` addition, otherwise Kibana tries to fetch the package from artifacts.elastic.co


Here is a brief summary of plugin installation commands:

- From a downloaded zip package:
```sh
/usr/share/kibana/bin/kibana-plugin install file:///full-path/package.zip
```

- From a plugin name:

```sh
/usr/share/kibana/bin/kibana-plugin install plugin-name
# Kibana will try to fetch it from artifacts.elastic.co
```


- From an external URL:
```sh
/usr/share/kibana/bin/kibana-plugin install https://url.com/package.zip
```

- From an external URL + proxy:
```sh
http_proxy="http://proxy.local:4242" /usr/share/kibana/bin/kibana-plugin install https://url.com/package.zip
```

> It says that "wazuh" plugin already exists
```sh
/usr/share/kibana/bin/kibana-plugin remove wazuh
rm -rf /usr/share/kibana/optimize/bundles
chown -R kibana:kibana /path/to/kibana/optimize
chown -R kibana:kibana /path/to/kibana/plugins
# Install again
```

Once done, restart Kibana:

```
systemctl restart kibana
```

I hope it helps.

Best regards,
Jesús

**Comment by b4b857f6ee** [comment]
Thank you @jesmg  and @Cerv1 for your answer.

But now i got this 

> [root@localhost ~]# http_proxy="http://proxyip:proxyport" sudo -u kibana NODE_OPTIONS="--max-old-space-size=3072" /usr/share/kibana/bin/kibana-plugin install file:///tmp/wazuhapp-3.9.0_6.7.1.zip
> Attempting to transfer from file:///tmp/wazuhapp-3.9.0_6.7.1.zip
> Transferring 20935644 bytes....................
> Transfer complete
> Retrieving metadata from plugin archive
> Extracting plugin archive
> Extraction complete
> Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.5.4]; found [6.7.1]"

It's mean i have to downgrade my kibana? :)

Well, i have add the repository for kibana 6.x
https://www.elastic.co/guide/en/kibana/6.7/rpm.html

update into 6.7.2-1 kibana, elasticsearch and logstash
Once again not the good version
So i have downgrade the kibana from 6.7.2 to 6.7.1

> yum downgrade kibana

Relaunch the install wazuh kibana app.

Ok.

Trying to start kibana, error, permission denied for 443

> FATAL  Error: listen EACCES: permission denied 0.0.0.0:443

I manage to trying to start it with the kibana account 

> sudo -u kibana service kibana start

by i get this:

> chroot: cannot change root directory to /: Operation not permitted

Sadly, i have no experience with chroot...

**Comment by jesusgn90** [comment]
Hello again @b4b857f6ee,

**Fast answer**

```
sudo setcap 'CAP_NET_BIND_SERVICE=+eip' /usr/share/kibana/node/bin/node
sudo service kibana restart
```

**Detailed answer**

> Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [6.5.4]; found [6.7.1]"

Kibana 6.5.4 is installed, but the plugin was built for 6.7.1

>  So i have downgrade the kibana from 6.7.2 to 6.7.1

We support 6.7.2 as well, (https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.0_6.7.2.zip)

> Trying to start kibana, error, permission denied for 443

443 is a privileged port (1-1023 ports are privileged), to allow a non-root user to bind a privileged port some distributions need the next command:

```
sudo setcap 'CAP_NET_BIND_SERVICE=+eip' /usr/share/kibana/node/bin/node
```

> I manage to trying to start it with the kibana account

It will run as `kibana` user, no need to use `sudo -u kibana`, so the right restarting command is:

```
sudo service kibana restart
```

I hope it helps.

Best regards,
Jesús

**Comment by b4b857f6ee** [comment]
Hello Worl! Ahah.

Ok, thank you all for your support and answer, this is working now! 👍
