### ISSUE TITLE
Agent registering: Do not enforce source IP checking by default.

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#3269]
Latest Wazuh release v3.9.0 includes the [capability](https://github.com/wazuh/wazuh/pull/2577) to gather the agent primary interface IP address, that IP will be displayed and use in `agent.ip` field for alerts, Wazuh API response agent info responses and Wazuh interface (Kibana and Splunk).

Currently, the manager by ships the setting `use_source_ip` set to `yes`.
Its enable the source IP checking and only allow an agent to report if the IP used for registration is the same one being used for reporting.

I have seen how this setting makes several users complain about an agent not able to report a few days after the registration. Dynamics environment (boot up and shut down instances) and load balancers make the agent unable to report.

My proposal is to disable `use_source_ip` by default. I think it will make easier the agent deployment (registering via LB) and connection durability.

Current (v3.9.0) [configuration](https://github.com/wazuh/wazuh/blob/master/etc/ossec.conf#L247):

> \<auth>
>   \<use_source_ip>**yes**</use_source_ip>

Proposed configuration:

> \<auth>
>   \<use_source_ip>**no**</use_source_ip>

Regards,
Pedro.

**Comment by vikman90** [comment]
Hi @snaow,

We set `<use_source_ip>` to `yes` at the express request of @santiago-bassett.

Thanks for the PR, we will merge it immediately if you guys confirm that this should be the correct default option value.

Cheers!
