### ISSUE TITLE
Ubuntu's vulnerabilities without operation are not being indexed 

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3277]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager | Packages/Sources | Any |

Some packages include their version in the name, such as `linux-image-4.18.0-18-generic`. In the Canonical feed, these packages usually do not have a version check because the existence of the same would confirm the vulnerability.

In Vulnerability Detector, these checks are indexed in the following line:

https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/src/wazuh_modules/wm_vuln_detector.c#L1007

However, in this type of checks NULL is binded, which means that nothing is inserted because of the `NOT NULL` restriction.

https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/src/wazuh_db/schema_vuln_detector.sql#L57

**Comment by crolopez** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/3283.

**Comment by snaow** [comment]
Move to 3.10.0 project (https://github.com/wazuh/wazuh/projects/30).
More research required.
The PR mention there is massive flooding caused by the proposed solution.

**Comment by chemamartinez** [comment]
This issue is outdated since 3.13.0. Now, all the vulnerabilities are indexed in the CVE database, not only those with a fixing version.

Regards.

**Comment by chemamartinez** [comment]
Closing https://github.com/wazuh/wazuh/pull/3283
