### ISSUE TITLE
Migrate Ossec Server to Wazuh

### ISSUE THREAD

**Issue by twicebar** [wazuh/wazuh#329]
Im install ossec with to many agent in my company. but now i want migrate it to wazuh.
what must i do? overwrite all ossec agent to wazuh agent or ossec server can send they syslog to wazuh?

i try to <syslog_output> from ossec server an wazuh listened that. Log from ossec server write to /var/log/message , but wazuh not show that log on kibana dashboard

**Comment by vikman90** [comment]
Hi @twicebar,

This page may help you: [Migrate from OSSEC - Wazuh 3.0 documentation](https://documentation.wazuh.com/current/migrating-from-ossec/index.html)

Just like OSSEC, Wazuh has native Syslog input (logs from agents) and Syslog output (for alerts). If you use Kibana you may find the JSON output more helpful. The Wazuh Documentation also explains [how to install and configure Elastic Stack](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html).

Hope it help.
Best regards.

**Comment by angystardust** [comment]
Hi @vikman90 is it possible to enable both the json and the syslog output for a wazuh server?

**Comment by vikman90** [comment]
Hi @angystardust,

Absolutely, you can. In fact, JSON or plain-text output (at least one of them) is necessary to make the Syslog forwarder work.

This is an example of configuration:

```xml
<ossec_config>
  <!-- Enable JSON output -->
  <global>
    <jsonout_output>yes</jsonout_output>
  </global>

  <!-- Enable Syslog client -->
  <syslog_output>
    <server>192.168.1.3</server>
    <level>7</level>
    <format>default</format>
  </syslog_output>
```
