### ISSUE TITLE
Unify timestamp field format for all the alerts 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3293]
Hi team,

I've noticed the milliseconds part of the `timestamp` field in our alerts is not always the same.

It must have always the same length (**3**).

Here are some `cat | grep` commands useful to see what I'm talking about:

```
cat /var/ossec/logs/alerts/alerts.json | grep -P "\.\d\+0000"
cat /var/ossec/logs/alerts/alerts.json | grep -P "\.\d\d\+0000"
cat /var/ossec/logs/alerts/alerts.json | grep -P "\.\d\d\d\+0000"
```

And here you can see some timestamps from my alerts:

```
2019-05-09T14:03:05.6+0000
2019-05-09T14:04:04.36+0000
2019-05-09T16:08:58.462+0000
```

The issue here is `.6` should be `.600`, `.36` should be `.360`, and `.462` is just fine.

We need this for **Elastic 7**.

Best regards,
Jesús

**Comment by snaow** [comment]
Closed by: https://github.com/wazuh/wazuh/pull/3814/files

Released in v3.9.5.
