### ISSUE TITLE
Documentation: add same_field to rules XML syntax

### ISSUE THREAD

**Issue by epol** [wazuh/wazuh#3299]
I see from the 3.9 version changelog that the `same_field` option has been added to the rules syntax. I can't find it in the [online documentation](https://documentation.wazuh.com/3.9/user-manual/ruleset/ruleset-xml-syntax/rules.html). It may be useful to add it also there.

Best regards and thank you for you work.

**Comment by TJOSERAFAEL** [comment]
Hi @epol ,

thank you for your collaboration! I opened the issue on our documentation repository https://github.com/wazuh/wazuh-documentation/issues/1204. 
We will do it ASAP. 

Best regards.

**Comment by TJOSERAFAEL** [comment]
Hi @epol ,

I'm going to close this issue as this is already merged on https://github.com/wazuh/wazuh-documentation/pull/1205

Fell free to re-open it if needed.

Best regards.
