### ISSUE TITLE
Service wazuh-agent is not correctly installed in Red Hat Enterprise Linux 8

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3309]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | Service wazuh-agent | Agent | Packages | RedHat8 |

After installing the Wazuh agent package in Red Hat 8, the service is not installed correctly and cannot be started using `systemctl`.

```
[root@rhel8]# service wazuh-agent restart
Reloading systemd:                                         [  OK  ]
Restarting wazuh-agent (via systemctl):  Failed to restart wazuh-agent.service: Unit wazuh-agent.service not found.
                                                           [FAILED]
```
Checking the SPEC file:
https://github.com/wazuh/wazuh-packages/blob/c405e791da87fccc33dcccc493015b89b3bd2221/rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec#L239

the file is correctly installed in the corresponding folder: 
```
[root@rhel8 vagrant]# ls -la  /etc/systemd/system/ | grep wazuh-agent
-rw-r--r--.  1 root root  345 May 13 00:53 wazuh-agent.service
```

**Comment by rossengeorgiev** [comment]
Hi @albertomn86, please see https://github.com/wazuh/wazuh/issues/2176

**Comment by vikman90** [comment]
Related issue: https://github.com/wazuh/wazuh-packages/issues/86

**Comment by alberpilot** [comment]
Fixed. Thanks all for supporting. 
Best regards, 
Alberto R
