### ISSUE TITLE
FIM is not able to parse some symbols in a Windows Agent

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#3310]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0| FIM | Agent | Packages | Windows 10 |

Hello team,

I have realized that FIM is not able to process the following symbols in a file: `ñ`, `´`.

When I write those symbols in a file I get the following:

```
"manager":{"name":"localhost.localdomain"},"id":"1557757293.4963107","full_log":"File 'c:\\users\\migue\\documents\\test▒`▒^^.txt' was added.\n","syscheck":{"path":"c:\\users\\migue\\documents\\test▒`▒^^.txt",
```
![image](https://user-images.githubusercontent.com/23264276/57629698-83e9db00-759c-11e9-8b96-11cc20baf88a.png)

This only happens in a Windows agent.

Regards,

Miguel Casares

**Comment by jotacarma90** [comment]
This work fine in wazuh version 3.12. 
Issue closed
