### ISSUE TITLE
Daemon execd not working properly when active response is disabled

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3312]
**Affected**

- Wazuh agent 3.8.2, Wazuh agent 3.9.0

_The issue probably exists since 3.8.0 but not confirmed._

**Steps to reproduce**

1. Disable `active-response` on the agent

```xml
  <active-response>
    <disabled>yes</disabled>
```
2. Restart the agent

```
systemctl restart wazuh-agent
```

3. There is a segmentation fault in a thread from ossec-execd

```
May 14 10:10:21 pop-os kernel: [ 1958.505941] ossec-execd[22429]: segfault at 48 ip 00007fd297f882c2 sp 00007ffe3b7d62e0 error 4 in libpthread-2.27.so[7fd297f7c000+1a000]
```

However `ossec-control status` shows `ossec-execd is running...` that's why I think is just a thread and not the whole daemon.

Best regards,
Jesús

**Comment by chemamartinez** [comment]
Done: #3316
