### ISSUE TITLE
Wazuh API restart agent not working due to #3312

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3313]
**Affected**

- Wazuh API 3.9.0

_This issue probably exists since 3.8.0_

**Blocked by  #3312**

**Steps to reproduce**

Due to #3312 the Wazuh API endpoint for restarting agents is not working when `active-response` is disabled on the agent.

The next `curl` command doesn't work for the agent:

```sh
 curl -u foo:bar -XPOST -H "Content-Type:application/json" -d '{"ids":["007"]}' "http://127.0.0.1:55000/agents/restart?pretty"
```

The Wazuh API tells all is fine but it's not:

```js
{
   "error": 0,
   "data": {
      "msg": "All selected agents were restarted",
      "affected_agents": [
         "007"
      ]
   }
}
```

Regards,
Jesús

**Comment by TJOSERAFAEL** [comment]
Hi @jesusgn90 ,

this issue is not related to https://github.com/wazuh/wazuh/issues/3312 because if active response is disabled, it's impossible to restart the agent even if `ossec-execd` is running since it is an active response event after all. 

An implementation must be done to restart the agent even with active response disabled.

Best regards.

**Comment by davidjiglesias** [comment]
Hi team, I have implemented a fix for this issue. Now, if agent's active response is disabled, the API response will display that it could not restart the agent.

With agent's active-response disabled="no":
```
root@151dc0a54c67:/# curl -u foo:bar -X PUT "http://localhost:55000/agents/001/restart?pretty"
{
   "error": 0,
   "data": {
      "msg": "All selected agents were restarted",
      "affected_agents": [
         "001"
      ]
   }
}
```
We disable the agent's active-response in ossec.conf and we test the request again:
```
root@f552ba637dbe:/wazuh-api# curl -u foo:bar -X PUT "http://localhost:55000/agents/001/restart?pretty"
{
   "error": 0,
   "data": {
      "msg": "Some agents were not restarted",
      "affected_agents": [],
      "failed_ids": [
         {
            "id": "001",
            "error": {
               "message": "Could not restart agent, agent-response is disabled in the agent",
               "code": 1750
            }
         }
      ]
   }
}
```
Original issue was using POST request, in this case, the POST and PUT methods to restart the agent are referring to the same framework function, so the fix solves the issue for both calls.

**Comment by davidjiglesias** [comment]
In the other hand, the implemented solution is only valid for a petition to restart a single Agent, as we can easily check its active configuration and decide whether or not the restart would be feasible. However, if we have a setup with thousands of agents, sending a petition to each of them prior to the restart request would add too much processing load and should be avoided.  Also, from the API's standpoint we can only guarantee that we have sent the restart request to the Agent, nothing else. If anything goes wrong after the petition is sent the API would be unaware as there is no response back. Adding another state to the agent status (such as restarting) could be useful in the future if we want to improve the quality of the responses we can give to the API users.
