### ISSUE TITLE
Remote upgrade not working properly in cluster mode 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3323]
**Description**

Remote upgrades in a cluster environment with a load balancer between agents and managers it's not working properly.

**Wazuh API remote upgrade**

Using the Wazuh API, `PUT /agents/:agent/upgrade`, a timeout is always thrown. I also think the load balancer just adds an extra layer here but the Wazuh API has no chunk size parameter and it'd throw a timeout even with no load balancer.

**agent_upgrade tool**

Using the agent_upgrade tool we have two issues:

For the cluster itself, you must know the node that the agent is reporting to, then you must launch the `agent_upgrade` tool from that node and not the master node (or even better, any node). This issue is not new but we should improve it for the next releases.

Here are some lines to make a workaround:

```
AGENTID="009"
CREDENTIALS="foo:bar"
APIURL="http://172.16.1.2"
REPORTINGTO=$(curl -u "$CREDENTIALS" "$APIURL:55000/agents/$AGENTID?pretty&select=node_name" -s | grep -oP ': ".*"' | cut -d'"' -f2)
NODEIP=$(curl -u "$CREDENTIALS" "$APIURL:55000/cluster/nodes/$REPORTINGTO?pretty" -s | grep '"ip"' | grep -oP ': ".*"' | cut -d'"' -f2)
```

Where `REPORTINGTO` would be the node name that the agent 009 is reporting to and `NODEIP` is the IP address of the node.

Ideally, the above lines should make easy to launch something like this:

```
ssh vagrant@$NODEIP -i /tmp/private_key 'sudo /var/ossec/bin/agent_upgrade -a 009 -f /tmp/wazuh_agent_v3.9.0_linux_x86_64.wpk -c 64000 -x upgrade.sh -F'
```

If we add a load balancer, the agent probably rejects the upgrading process because the source IP (node IP) differs from the sender IP (load balancer IP), this can be fixed at load balancer level, but not always is as easy as we'd want to be.

That was my idea to launch all the commands remotely. I still need to set up the load balancer properly, I will comment on this ticket with more details.

On the other hand, if the agent receives just a part of the WPK file, then you must remove it from `/var/ossec/var/incoming/name_of_wpk.wpk`, then restart the agent. Otherwise, you can't try to remotely upgrade it again.

Definitively all of the above issues should be fixed, day by day the cluster begins to be a mandatory thing is most of the users.

**Environment to reproduce**

Here are the instances needed to reproduce/debug this issue:

2 x Wazuh managers (master, worker) 3.9.0
1 x LB (NGINX, working as expected for the rest of Wazuh features)
1 x Wazuh agent 3.8.2

I've done all the above stuff using CentOS 7, but this is a "wazuh-networking" issue and not an OS-related issue.

**Proposals**

- Add `chunk` as an optional parameter for the Wazuh API
- Increase the maximum `chunk` size allowed value
- Increase the performance for sending the WPK file
- Allow ignoring the sender IP on the agent side when receiving a remote upgrade (is this possible right now? I don't know)
- Make the `agent_upgrade` tool _distributed_, any node should be able to send an upgrade regardless of the node that agent is currently reporting to or at least, the master node should be able to send the upgrade always.

**Related**

Wazuh core:

- https://github.com/wazuh/wazuh/issues/2580
- https://github.com/wazuh/wazuh/issues/3227
- https://github.com/wazuh/wazuh/issues/2494
- https://github.com/wazuh/wazuh/issues/2408
- https://github.com/wazuh/wazuh/issues/2437
- https://github.com/wazuh/wazuh/issues/1030

Wazuh API:

- https://github.com/wazuh/wazuh-api/issues/385
- https://github.com/wazuh/wazuh-api/issues/286

**Comment by jesusgn90** [comment]
**Update**

Some problems disappear if no `-c` is used for `agent_upgrade` tool. And it's much faster than using `-c 64000`.

**Comment by davidjiglesias** [comment]
Related to https://github.com/wazuh/wazuh/issues/5387
