### ISSUE TITLE
Each agent need one wazuh database, would it cause any performance issue?

### ISSUE THREAD

**Issue by hapablanha** [wazuh/wazuh#3332]
As we can see, each agent need one wazuh database, and it contains multiple tables. And RESTful API support query of info by agent id.
If we need collect the info for all the agents, it would invoke RESTful API many times and open many SQLite databases, would it cause any performance issue?

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0-rc7 | wazuh db | Manager | Source | CentOS |

**Comment by Skeptor** [comment]
Hi @hapablanha 

The RESTful API doesn't present performance issues until a huge number of petitions is made. In case it is your situation you can try the API call `GET /agents` to test the performance of the API.
In any case, the API performance is independent from the Manager performance so it musn't affect the `wazuh_db` component

Regards,
Pablo.
