### ISSUE TITLE
Uploading a configuration file fails on mounted volumes

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3335]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | Framework | Manager | Any | Any |

The following error is raised in the cloud environment:

```
>>> upload_file('tmp/api_group_conf_1557503379_60', 'etc/ossec.conf', 'application/xml', overwrite=True)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 563, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/var/ossec/tmp/api_tmp_file_1557503748.2873518_690.xml' -> '/var/ossec/etc/ossec.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 212, in upload_file
    return upload_xml(file_data, path)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 280, in upload_xml
    raise e
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.9.0-py3.7.egg/wazuh/manager.py", line 269, in upload_xml
    move(tmp_file_path, new_conf_path)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 577, in move
    copy_function(src, real_dst)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 263, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/var/ossec/framework/python/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/var/ossec/etc/ossec.conf'
```
The error is raised because of the `move` operation. Since temporary files are uploaded first to `/var/ossec/tmp` and then moved to `/var/ossec/target_folder`, errors may ocurred when that `target_folder` is a mounted volume in Docker or a link to any other filesystem. 

This operation is performed in two functions:
- https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/framework/wazuh/manager.py#L268
- https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/framework/wazuh/manager.py#L310

The fix proposed is replacing the move call for the following code:
```python
from shutil import copyfile
copyfile(tmp_file_path, new_conf_path)
remove(tmp_file_path)
```

**Comment by jesuslinares** [comment]
It is happening in Docker environments.

Here more info: https://bugs.python.org/issue26791.

**Comment by crd1985** [comment]
I have debugged in detail what `shutil.move` function does behind the scenes. The actual problem raises when the default copy function (`copy2`) calls to `copystat` and tries to overwrite the `ossec.conf` metadata. Since the API runs as `ossec` and the owner of the file is `root` this operation fails. However, a call to `copyfile` is executed so the exception is raised after the contents of the temporary file have been copied to `ossec.conf`: https://github.com/python/cpython/blob/b16b4e45923f4e4dfd8e970ae4e6a934faf73b79/Lib/shutil.py#L407

I would propose the following fix:
- Replace `move(src, dst)` by `move(src, dst, copy_function=copyfile)` in https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/framework/wazuh/manager.py#L268 and  https://github.com/wazuh/wazuh/blob/18bac2de69f5a37e5c3c4e2dfbce5a0093042ea7/framework/wazuh/manager.py#L310

This would work because `copyfile` does not copy permissions or stats to target file, avoiding ownership conflicts.

**Comment by crd1985** [comment]
According to my previous comment, we need to improve our testing environment to be more realistic.
The problem here only arises when two conditions are met:
- The target file to be overwritten is in a different filesystem (for example, when it is allocated in a mounted folder in a docker volume)
- The target file's owner is not `ossec`

These circumstances should be taken into account when developing and testing from now on.
