### ISSUE TITLE
Bug using convert_windows_string function

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#3341]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | Locollector | Agent | Packages/Sources | Windows |

We must check the returned value of this function, in case of error, returns `NULL` and possible later uses will cause a failure of the Windows agent.

This issue can occur configuring `localfiles` with the options `eventchannel` or `eventlog` in `log_format`.

https://github.com/wazuh/wazuh/blob/db853c7a01ef5f6851d30b7e939aed0914404e33/src/shared/string_op.c#L301-L355

As it says in [MSDN](https://docs.microsoft.com/en-us/cpp/c-runtime-library/parameter-validation?view=vs-2019) the behavior of the C Runtime when an invalid parameter is found can causes the application to "crash".

At this point we need to check returned value.
https://github.com/wazuh/wazuh/blob/d1528e5577c0b0289d5285f1f1b9e7e3781342e9/src/logcollector/read_win_event_channel.c#L488-L490

This bug was reported in our mailing lists: [Windows Agent Crash](https://groups.google.com/d/msgid/wazuh/62e54b84-da95-4e29-a3a0-6bf8a2a425f1%40googlegroups.com.)

**Comment by kai-hier** [comment]
<markdown-accessiblity-table data-catalyst="">
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
4.10.1 | Locollector | Agent | Packages/Sources | Windows

Sorry to Negrobump this but here I am having this exact same Error in the ossec.log files of a number of Windows 11 pr clients in 2025.
Is there Something I can do on my end?
