### ISSUE TITLE
Make clearer error message on stopped daemons

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3346]
There is a control in distributed API to avoid processing requests when some of the minimal Wazuh daemons is down.

It is implemented in https://github.com/wazuh/wazuh/blob/4f8b5b73f72b82e46e3f4a68ae6b4992e4497361/framework/wazuh/cluster/dapi/dapi.py#L109

The problem when the exception is raised is the unclear message:
```json
{"message": "Wazuh is stopped. Start Wazuh before using the API.: ('running', 'running', 'running', 'running', 'stopped')",
 "error": 1018
}
```

The message should be more descriptive such as the following one:
```json
{"message": "Wazuh is stopped. Start Wazuh before using the API.: ('wazuh-modulesd: running', 'ossec-remoted: running', 'ossec-analysisd: running', 'ossec-execd: running', 'wazuh-db: stopped')",
 "error": 1018
}
```

**Comment by branchnetconsulting** [comment]
Yes, please take care of this.  It threw me for a loop this morning not knowing why the Wazuh-API on my master node manager thought "Wazuh is stopped" when it looked like it was running as intended to me.  I had disabled the 1514 listener intentionally, which turns off remoted entirely, but it isn't intuitive that ossec-remoted would be required for the API to operate.  Thanks to **crd1985** for putting this note out there.  It saved me from losing even more time on this issue.

**Comment by JmZero** [comment]
I modified the code and now generates a dictionary with the key-value pairs of the minimal Wazuh daemons and add it as an extra_message to the error.

```json
{"message": "Wazuh is stopped. Start Wazuh before using the API.: {'wazuh-modulesd': 'stopped', 'ossec-remoted': 'running', 'ossec-analysisd': 'running', 'ossec-execd': 'running', 'wazuh-db': 'running'}",
 "error": 1018
}
```
