### ISSUE TITLE
Querying WPK available versions will fail in v3.10

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3353]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0 | Remote upgrades | Manager | All | All |

Since the Linux WPK were unified in v3.4.0, the list of available versions to upgrade agents is taken from two different locations depending on the Wazuh version:

https://github.com/wazuh/wazuh/blob/4f8b5b73f72b82e46e3f4a68ae6b4992e4497361/framework/wazuh/agent.py#L1918
https://github.com/wazuh/wazuh/blob/4f8b5b73f72b82e46e3f4a68ae6b4992e4497361/framework/wazuh/agent.py#L1991

When looking for `v3.10` the comparison in the script will be `v3.1 < v3.4` and will look for the incorrect version file.

**Comment by crd1985** [comment]
To fix this issue, #3358 must be closed first.
