### ISSUE TITLE
wazuh keeps deleted files opened on wildcard logs

### ISSUE THREAD

**Issue by kreon** [wazuh/wazuh#337]
So we faced and issue when wazuh was looking into a huge ( ~ 40 Gb per day ) nginx log directory and kept it as 'open' even after logrotate did his job.
wazuh-agent-2.1.1-1.el7.x86_64
CentOS Linux release 7.2.1511 (Core)
Config: localfile /var/log/nginx/*.log
Proofs:
> sudo lsof +aL1 / 2>&- | grep deleted |  sort -rnk7 
ossec-log 23865     root   10r   REG    8,3 7260675048     0  801130 /var/log/nginx/ssl_access.log-20180102 (deleted)
ossec-log 23865     root   11r   REG    8,3  618190327     0  797096 /var/log/nginx/access.log-20180102 (deleted)

**Comment by crolopez** [comment]
Hi @kreon,

A logcollector upgrade will be released in Wazuh 3.2, allowing rescanning paths with wildcards so that you can monitor new files and close deleted files. You can see its development [here](https://github.com/wazuh/wazuh/pull/332).

Best regards.
