### ISSUE TITLE
Support client.keys sync from Workers to Master

### ISSUE THREAD

**Issue by hubbcaps** [wazuh/wazuh#3389]
|Version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.8.2 | client.keys | Manager | RPM | Amazon Linux 2 |

Currently in Wazuh, if the master in a clusters client.keys file ends up being blank when the workers connect to it for clustering, the workers will all wipe their client.keys to match the master.

In an environment such as AWS where everything should be disposable and redeployable, this causes quite a few issues.

The following scenario is what I experienced:

Inside of AWS, two seperarate auto scaling groups, one for the single master, one for anywhere from 3 to 6 worker nodes.

Have a cluster, 1 master, 3 workers.

handful of agents registered against the master and shipping logs happily to the workers/master.

Needing to change some postfix settings around, I rebake my master AMI and redeploy the node. When the new node comes back up, it's basically net new, so the client.keys file is blank.

All the worker nodes once they find the new master alive, then conform their client.keys file to the masters, meaning all the currently registered agents are now unable to send messages without reregistering them.

Expected or Preferred experience would be the possibility of a config option, in which when a master comes up and received communication from worker nodes, if the masters client.keys file is blank, to just ingest the worker nodes client.keys file instead.

This would allow for some scalability in terms of the master coming and going as needed in an environment such as AWS and save some headache of having to engineer a solution around it such as what we have setup.

Our current work around for this is to copy the /var/ossec/etc directory at boot to a temp directory for storing the configs we have baked into the AMI, then a s3 bucket mounted via s3fs at /var/ossec/etc, containing the client.keys file namely and whatever previous config iterations existed and then copying the temp directory configs over sans blank client.keys.

As you can see, that's pretty hacky way of forcing the app to work in the AWS paradigm, and I think a config option allowing bidirectional sync of the client.keys would be a much cleaner implementation for the cloud.

**Comment by hubbcaps** [comment]
or possibly just let us point the config at a different path for the client.keys file so we don't need to do weird work arounds that include the entirety of the ossec/etc directory.

**Comment by crd1985** [comment]
Hi @hubbcaps ,

sorry for the late reply.

Thank you for pointing this problem. We will take this into account for future developments. 

However, I would say that is not the root cause of your problem. The cluster should be able to recover when a master is down. There are several ways to do this, like having more than one master or let a worker become the new master. 

Facing this issue in that way would have much more benefits for all cluster users, and would still fit in your AWS environment. Actually, this is an active discussion in the dev team, but we hope to give the community a solution in the short term.

I hope you agree :), but if not, feel free to discuss other approaches.

Thank you for your collaboration.

Regards,
Dani

**Comment by hubbcaps** [comment]
Absolutely, in particular having multiple masters would be nice, or the ability to promote a worker to master, however I could see issues with the later where security groups in AWS are setup to where certain communication is locked down to the master group vs the worker group like registration of agents which would fail when the duty is passed to a worker.

In terms of the multiple masters, I think that would be the ideal solution moving forward, with one caveat that there be an ability for mis matched master versions allowed so the older nodes can be cycled out as the new one comes online and gets the client.keys shared to the new one so it's not lost as this ticket is all about.

Glad to know it's on your radar, and hope to see the implementation soon. I'll leave ya'll to it.

**Comment by crd1985** [comment]
Thank you again!

We'll keep in mind everything commented here.

Regards,
