### ISSUE TITLE
Feature request: ability to read multi-line json logs

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3403]
Some security relevant log sources will populate their json log outputs with indentation and line breaks. 

Currently logcollector will claim a message `is not a JSON object` if it is not completely contained within a single line.

Wazuh would be able to integrate with multiline json logs if it would attempt to complete the json message by reading the next lines until it detects all json brackets have been closed.

**Comment by jnasselle** [comment]
Hi @jctello ,

Collecting multiple-line logs from files was introduced by #6890.

Regards,
Nico

**Comment by jctello** [comment]
As mentioned by @jnasselle this was added in Wazuh v4.2.0 so I proceed to close this issue
