### ISSUE TITLE
Need help on 'Wazuh stopped' message in Kibana app, problem with local install, too

### ISSUE THREAD

**Issue by crankedguy** [wazuh/wazuh#3418]
Hi,

I would need some help here. 
I am trying to install Wazuh only on a local instance.
I followed the advice from the Wazuh repo, issue 211 for this https://github.com/wazuh/wazuh/issues/211
> You only need to remove \<auth>...\</auth> and \<remote>..\</remote> sections from this file and restart the manager.

Now when I try to activate the Kibana app it tells me Wazuh is stopped and I should start it before using the API. 
The query comes from GET /agents/?pretty which errors in error 1018, also manually
 curl "https://foo:bar@127.0.0.1:55000/agents?pretty"
{
   "error": 1018,
   "message": "Wazuh is stopped. Start Wazuh before using the API."
}

Service wazuh-manager and wazuh-api both are running and showing ok in systemd.

agent_control lists 1 agent (the server)
```
Wazuh agent_control. List of available agents:
   ID: 000, Name: ms1.domain.tld (server), IP: 127.0.0.1, Active/Local
```

What am I missing here?
Do I have to install an agent on the machine explicitely?

**Comment by crankedguy** [comment]
I tried the same with a manual install of a 'local' installation now which leads to a similar problem just with another error code

api.log
` foo: [127.0.0.1] GET /agents/000? - 500 - error: '1'.`

Error message in UI
`Settings. 3005 - Error executing internal command (/api/check-api)`

API call done by UI, manually executed :
```
 curl "https://foo:bar@127.0.0.1:55000/agents/000?pretty"
{
   "error": 1,
   "message": "Error executing internal command"
}
```
Can you please advise on that? Thanks

**Comment by davidjiglesias** [comment]
This issue has been responded in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wazuh/SxOf8k38iI0

Best regards,

David J. Iglesias
