### ISSUE TITLE
Kibana/Wazuh customization issue

### ISSUE THREAD

**Issue by aamore** [wazuh/wazuh#3434]
My current Kibana UI does not have the wazuh app on it. It looks like below:
![kibana_app1](https://user-images.githubusercontent.com/51163236/58648278-5c527c80-82d7-11e9-8496-8188910425dd.PNG)

How do I get Kibana to show the wazuh app and customize it to look more like this:
![kibana_app](https://user-images.githubusercontent.com/51163236/58648309-6eccb600-82d7-11e9-85e5-8a2ecf3eace8.png)

Any help would be much appreciated. Thanks!

**Comment by Zenidd** [comment]
Hello @aamore,


- In the image below the interface looks like Kibana 5. The newer versions of wazuh do not support Kibana 5, we do not recommend the use of this version.
-  Furthermore seems like your current Kibana version is 7.1 or 7.1.1 and is the version we recommend you install . Probably you installed an older version of Wazuh app. There is a [Kibana - WazuhAPP compatibility matrix](https://github.com/wazuh/wazuh-kibana-app#older-packages) for you to find the exact version of the app you need. 
- After installing the correct Kibana and Wazuh app versions, the Kibana ui should show the Wazuh application.
<br></br>
Please let us know if it helps, and write us if you have any questions.
<br></br>

Best regards,

Juan Pablo Sáez

**Comment by aamore** [comment]
I checked the version of Kibana. I have 7.1.0 and my Wazuh App is version 3.9.1. The documentation is not too good at explaining how to customize kibana corrrectly. I am still trying to figure out how to manage logs and Wazuh from Kibana.
