### ISSUE TITLE
Processing Suricata events from a remote syslog.

### ISSUE THREAD

**Issue by jxbuddrige** [wazuh/wazuh#3436]
Hi all,

I am trying to decode Suricata events coming from a remote syslog, however, it is not working.

If I run:

May 30 20:30:19 suricata[39840]: {"timestamp": "2019-05-30T20:30:19.033987+0100", "flow_id": 1005338820754915, "in_iface": "vmx2", "event_type": "alert", "src_ip": "REDACTED", "src_port": 1040, "dest_ip": "REDACTED", "dest_port": 61460, "proto": "TCP", "metadata": {"flowints": {"applayer.anomaly.count": 1}}, "alert": {"action": "allowed", "gid": 1, "signature_id": 2260003, "rev": 1, "signature": "SURICATA Applayer Protocol detection skipped", "category": "Generic Protocol Command Decode", "severity": 3}, "app_proto": "failed", "flow": {"pkts_toserver": 90, "pkts_toclient": 68, "bytes_toserver": 126846, "bytes_toclient": 5116, "start": "2019-05-30T20:30:18.802275+0100"}, "payload": "", "payload_printable": "", "stream": 0, "packet": "AEUduyhgAAwpEUR4CABFAAA0AABAAD8GXOu8J6tiBQJyTQQQ8BSSFRtNJ/h3u4AQA/zB8wAAAQEFCif4ejAn+MmY", "packet_info": {"linktype": 1}}

I receive not hits through ossec-logtest.

However, if I run: 

{"timestamp": "2019-05-30T20:30:19.033987+0100", "flow_id": 1005338820754915, "in_iface": "vmx2", "event_type": "alert", "src_ip": "REDACTED", "src_port": 1040, "dest_ip": "REDACTED", "dest_port": 61460, "proto": "TCP", "metadata": {"flowints": {"applayer.anomaly.count": 1}}, "alert": {"action": "allowed", "gid": 1, "signature_id": 2260003, "rev": 1, "signature": "SURICATA Applayer Protocol detection skipped", "category": "Generic Protocol Command Decode", "severity": 3}, "app_proto": "failed", "flow": {"pkts_toserver": 90, "pkts_toclient": 68, "bytes_toserver": 126846, "bytes_toclient": 5116, "start": "2019-05-30T20:30:18.802275+0100"}, "payload": "", "payload_printable": "", "stream": 0, "packet": "AEUduyhgAAwpEUR4CABFAAA0AABAAD8GXOu8J6tiBQJyTQQQ8BSSFRtNJ/h3u4AQA/zB8wAAAQEFCif4ejAn+MmY", "packet_info": {"linktype": 1}}

It is processed successfully using the JSON decoder.

Is there a way I can process the first event log?, which is what I receive from the remote syslog.

Thanks,

James

**Comment by Zenidd** [comment]
Hello @jxbuddrige,

I used rsyslog to recreate the environment of your issue. Please specify which software you are using to send the logs to the manager. 
<br></br>
- Using rsyslog, when entering the further event as an input:

---
{"timestamp": "2019-05-30T20:30:19.033987+0100", "flow_id": 1005338820754915, "in_iface": "vmx2", "event_type": "alert", "src_ip": "REDACTED", "src_port": 1040, "dest_ip": "REDACTED", "dest_port": 61460, "proto": "TCP", "metadata": {"flowints": {"applayer.anomaly.count": 1}}, "alert": {"action": "allowed", "gid": 1, "signature_id": 2260003, "rev": 1, "signature": "SURICATA Applayer Protocol detection skipped", "category": "Generic Protocol Command Decode", "severity": 3}, "app_proto": "failed", "flow": {"pkts_toserver": 90, "pkts_toclient": 68, "bytes_toserver": 126846, "bytes_toclient": 5116, "start": "2019-05-30T20:30:18.802275+0100"}, "payload": "", "payload_printable": "", "stream": 0, "packet": "AEUduyhgAAwpEUR4CABFAAA0AABAAD8GXOu8J6tiBQJyTQQQ8BSSFRtNJ/h3u4AQA/zB8wAAAQEFCif4ejAn+MmY", "packet_info": {"linktype": 1}}

---

- I get this output in `/var/ossec/logs/archives/archives.log`:

---
2019 May 31 16:01:45 ubuntu16worker->/var/log/syslog May 31 16:00:16 ubuntu16worker suricata {timestamp: 2019-05-30T20:30:19.033987+0100, flow_id: 1005338820754915, in_iface: vmx2, event_type: alert, src_ip: REDACTED, src_port: 1040, dest_ip: REDACTED, dest_port: 61460, proto: TCP, metadata: {flowints: {applayer.anomaly.count: 1}}, alert: {action: allowed, gid: 1, signature_id: 2260003, rev: 1, signature: SURICATA Applayer Protocol detection skipped, category: Generic Protocol Command Decode, severity: 3}, app_proto: failed, flow: {pkts_toserver: 90, pkts_toclient: 68, bytes_toserver: 126846, bytes_toclient: 5116, start: 2019-05-30T20:30:18.802275+0100}, payload: , payload_printable: , stream: 0, packet: AEUduyhgAAwpEUR4CABFAAA0AABAAD8GXOu8J6tiBQJyTQQQ8BSSFRtNJ/h3u4AQA/zB8wAAAQEFCif4ejAn+MmY, packet_info: {linktype: 1}}

---


**Rsyslog adds timestamps and extra information to the original log that makes it unable to match with our json decoder**. 

- Is it possible that you modify the configuration of the remote logs to eliminate this extra information and just send the raw log to make it match with our json decoder? If that's not possible, we can work it out some other way.

<br></br>
Best regards,

Juan Pablo Sáez

**Comment by jxbuddrige** [comment]
Hi @Zenidd ,

Thanks, for your prompt response. I am using the following to get my syslog:

	<remote>
		<connection>syslog</connection>
		<allowed-ips>192.168.2.1/24</allowed-ips>
		<port>514</port>
		<protocol>udp</protocol>
	</remote>

The full message I receive in archives.log is:


2019 May 31 15:46:07 ncrmkv-app-003-1->192.168.2.1 May 31 16:46:07 suricata[96056]: {"timestamp": "2019-05-31T16:46:07.153350+0100", "flow_id": 661391882827393, "in_iface": "vmx2", "event_type": "tls", "src_ip": "REDACTED", "src_port": 37560, "dest_ip": "REDACTED", "dest_port": 443, "proto": "TCP", "tls": {"subject": "C=US, unknown=07013, ST=New Jersey, L=Clifton, unknown=Suite 100, unknown=1255 Broad St, O=Comodo Security Solutions, Inc., OU=DevOps, CN=one.comodo.com", "issuerdn": "C=GB, ST=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO RSA Organization Validation Secure Server CA", "serial": "24:EA:71:3F:5F:84:D3:9B:BE:23:A6:E4:08:73:28:C4", "fingerprint": "76:1a:45:e8:08:71:5b:8e:25:80:4b:55:0f:d0:68:ad:0e:e5:43:3c", "version": "TLSv1", "notbefore": "2019-01-08T00:00:00", "notafter": "2021-01-07T23:59:59", "ja3": {}}}
2019 May 31 15:46:09 ncrmkv-app-003-1->192.168.2.1 May 31 16:46:09 suricata[96056]: {"timestamp": "2019-05-31T16:46:08.976094+0100", "flow_id": 1767068936496350, "in_iface": "vmx2", "event_type": "dns", "src_ip": "188.39.171.98", "src_port": 18130, "dest_ip": "1.1.1.1", "dest_port": 53, "proto": "UDP", "dns": {"type": "query", "id": 2760, "rrname": "wg.spotify.com", "rrtype": "A", "tx_id": 0}}

**Comment by jxbuddrige** [comment]
Sorry, sent to early!

Not sure if that way is the best way to do it with Wazuh, what's your thoughts? 

Thanks again,

James

**Comment by jxbuddrige** [comment]
Sorry, @Zenidd,

I may have misread your first question.

To send the logs to the manager I am using the built-in pfsense remote syslogger:
https://i.imgur.com/RqJpBRH.png

Unfortunately, I cannot see a way of customizing it to remove the extra info: " May 31 16:46:07 suricata[96056]"

Thanks again,

James

**Comment by jxbuddrige** [comment]
@Zenidd,

After speaking to a few guys, we've decided to run Suricata on a separate instance, and use the agent.

This now works!

 Thanks again,

James

**Comment by Zenidd** [comment]
Hello @jxbuddrige,

first of all, sorry for the late reply.

Thank you for updating us on your situation. I'm glad you got a configuration that allows you to monitor Suricata events and fire rules when necessary. I'm closing this ticket, please feel free to open others whenever you need to. 


<br></br>
Best regards,

Juan Pablo Sáez
