### ISSUE TITLE
Increase the <field>, <same_field> and <not_same_field> options range

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh#3440]
Hello team,

It would be great to make the options `<same_field>` and `<not_same_field>` able to handle the static fields 
We can handle static fields by using different tags like <same_user /> or <same_source_ip /> but it would be better to use the same tag to manage every field.
Besides, I've seen the following behavior while using the mentioned options:

Decoder:
```
<decoder name="test">
    <prematch>testing log</prematch>
    <regex>testing log value: (\d*)</regex>
    <order>value</order>
</decoder>
```

Rule:
```
  <rule id="100001" level="5">
    <decoded_as>test</decoded_as>
    <field name="value">45</field>
    <description>test log</description>
  </rule>
```

Log: `testing log value: 45`

Result:
```
**Phase 1: Completed pre-decoding.
       full event: 'testing log value: 45'
       timestamp: '(null)'
       hostname: 'centOS7-2'
       program_name: '(null)'
       log: 'testing log value: 45'

**Phase 2: Completed decoding.
       decoder: 'test'
       value: '45'

**Phase 3: Completed filtering (rules).
       Rule id: '100001'
       Level: '5'
       Description: 'test log'
**Alert to be generated.
```

Same result with the option `<same_field/>`. When I've tried to use these options with different fields such as `hostname` or `agent.id` they didn't work.
So, as I can see it, these options are working for fields extracted by decoders but they cannot be used with internal extracted fields.

**Comment by snaow** [comment]
Issue: https://github.com/wazuh/wazuh/issues/4050
PR: https://github.com/wazuh/wazuh/pull/4416

**Comment by vikman90** [comment]
@DanielMorLoz @snaow issue @4050 was already implemented and released.

Best regards.
