### ISSUE TITLE
Rootcheck race condition makes analysisd crash

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#3442]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.9.1-3921 | analysisd:decoder-rootcheck | Manager | Packages | CentOS 7 |

|Working branch|
|---|
|[3.9-rootcheck-race-3442](https://github.com/wazuh/wazuh/compare/3.9-rootcheck-race-3442)|

**Description**

The _rootcheck_ decoder has an issue if 2 or more threads are being used. It's a race condition which makes that a malformed event generates a segmentation fault due to a racing condition.

The affected code can be found here:

https://github.com/wazuh/wazuh/blob/5e08ac2eef1327c0f1264f3b0a75bf473a85168c/src/analysisd/decoders/rootcheck.c#L74-L94

Probably handling files such as `fclose(rk_agent_fps[i]);` with more than one thread is making a race condition, then crashing the _analysisd_ engine.

**Steps to reproduce**

Ensure the next internal setting is `0` GTE than `2` otherwise you can't generate a race condition.

```
# Number of rootcheck decoder threads
analysisd.rootcheck_threads=0
```

Send multiple _rootcheck_ malformed events directly to _analysisd, you can use the next script (from wazuh-tools) for testing purposes.

```py
#!/usr/bin/env python
# Print messages on OSSEC queue (analysisd/agentd)
# November 1, 2016
#
# Syntax: queue.py <message>
# Standard message form: <id>:<location>:<log>

from socket import socket, AF_UNIX, SOCK_DGRAM, SO_SNDBUF, SOL_SOCKET
from sys import argv

ADDR = '/var/ossec/queue/ossec/queue'
BLEN = 212992

if len(argv) < 2:
    print("Syntax: {0} [-L] <message>")
    exit(1)

sock = socket(AF_UNIX, SOCK_DGRAM)
sock.connect(ADDR)
oldbuf = sock.getsockopt(SOL_SOCKET, SO_SNDBUF)

if oldbuf < BLEN:
    sock.setsockopt(SOL_SOCKET, SO_SNDBUF, BLEN)
    newbuf = sock.getsockopt(SOL_SOCKET, SO_SNDBUF)
    print("INFO: Buffer expended from {0} to {1}".format(oldbuf, newbuf))

if argv[1] == '-L':
    string = ' '.join(argv[2:])
    i=1
    try:
        while True:
            sock.send(string.encode())
            i += 1
    except BaseException as e:
        print(e)
        print("Messages: {0}\nBytes: {1}".format(i, i * len(string)))

else:
    string = ' '.join(argv[1:])
    sock.send(string.encode())

sock.close()
```
And here we are:

```
./queue.py -L '9:/var/:'
```

```
/var/log/messages:May 31 16:27:37 master kernel: ossec-analysisd[15648]: segfault at 0 ip 00007f6175a82ec
4 sp 00007f6111ffa1e0 error 4 in libc-2.17.so[7f6175a15000+1c2000]
```

Regards,
Jesús

**Comment by vikman90** [comment]
We confirmed this crash is due to a race condition:

1. A thread inserts an item in the agent file array: https://github.com/wazuh/wazuh/blob/v3.9.1/src/analysisd/decoders/rootcheck.c#L107
2. At the same time, other thread tries to read the agent file array: https://github.com/wazuh/wazuh/blob/v3.9.1/src/analysisd/decoders/rootcheck.c#L89

This produces a read-write race condition.

## Proposed fix

Introduce a global mutex in the Rootcheck decoder to constraint that only one thread can handle the global array at the same time.
