### ISSUE TITLE
Firewall logs in wazuh

### ISSUE THREAD

**Issue by mad-eye21** [wazuh/wazuh#3454]
Hello,

I have a Wazuh setup and working fine in ubuntu server (agent), I want wazuh to analyze firewall logs also.
but can't install agent there in firewall...
can someone help me with that ???

**Comment by Lopuiz** [comment]
Hello @mad-eye21,

Wazuh manager can receive log messages via Syslog.
You need configure section remote in ossec.conf. It is located at /var/ossec/etc/ossec.conf
For more information you can follow our documentation: [Local configuration - remote](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html)

A configuration example is:
```xml
<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
  <allowed-ips>10.0.0.0/24</allowed-ips>
  <local_ip>10.0.0.1</local_ip>
</remote>
``` 
I hope this example help you. If you have further questions, let us know.

Regards, Eva

**Comment by mad-eye21** [comment]
> 
> 
> Hello @mad-eye21,
> 
> Wazuh manager can receive log messages via Syslog.
> You need configure section remote in ossec.conf. It is located at /var/ossec/etc/ossec.conf
> For more information you can follow our documentation: [Local configuration - remote](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html)
> 
> A configuration example is:
> 
> ```
> <remote>
>   <connection>syslog</connection>
>   <port>514</port>
>   <protocol>udp</protocol>
>   <allowed-ips>10.0.0.0/24</allowed-ips>
>   <local_ip>10.0.0.1</local_ip>
> </remote>
> ```
> 
> I hope this example help you. If you have further questions, let us know.
> 
> Regards, Eva

OK Got the point I need to do this setup for Syslog in wazuh manager.
I have a doubt what setting or script I need to make in firewall in order to send logs to wazuh?

**Comment by Lopuiz** [comment]
@mad-eye21 
It's possible your firewall has a specific configuration to send messages via Syslog. Could you say me your firewall OS or/and machine OS

**Comment by mad-eye21** [comment]
> 
> 
> @mad-eye21
> It's possible your firewall has a specific configuration to send messages via Syslog. Could you say me your firewall OS and machine OS

Ya firewall send Syslogs and for Firewall OS I don't have idea i have limited access to it, Machine OS where wazuh is running is Ubuntu.

I want to know that do I need to create file with syslog configuration which will send logs to wazuh or anything else?
I want to  the procedure ?

**Comment by Lopuiz** [comment]
Hi @mad-eye21, 
Wazuh only needs the previous configuration and to be restart.
The firewall must be configured to send event messages to the Wazuh manager's IP.
This configuration changes according to the firewall you have.

If your firewall has already sent event messages on the administrator's IP and is saved in a file, you can use [localfile](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html) to read these logs.
A configuration examples is:
```xml
<localfile>
  <log_format>syslog</log_format>
  <location>path_your_file</location>
</localfile>
```

Regards, Eva

**Comment by Lopuiz** [comment]
To check you receive logs you can modify option `logall ` of the section `global`. Change from no to yes.
```xml
<logall>yes</logall>
```
It creates a file `/var/ossec/logs/archives/archives.log` where save all event messages received.

You can follow our documentation: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html

**Comment by mad-eye21** [comment]
> 
> 
> To check you receive logs you can modify option `logall ` of the section `global`. Change from no to yes.
> 
> ```
> <logall>yes</logall>
> ```
> 
> It creates a file `/var/ossec/logs/archives/archives.log` where save all event messages received.
> 
> You can follow our documentation: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html

Thank You so much it is really helpful I'll  work on it.

**Comment by mad-eye21** [comment]
I Have one more question 

![picturemessage_3pain1uq cxx](https://user-images.githubusercontent.com/48945491/58882180-50acee80-86f9-11e9-9a63-d63b3304dde7.png)

as you can see in this screenshot Rule ID 5501 login session opened
can I see which user logged in and if yes then?

**Comment by Lopuiz** [comment]
Hi @mad-eye21, 

Yes. You have to open the Discover tab. In that tab is all the information of all the alerts.
You can filter the alerts using `rule.id:5501` so that only the 5501 alerts are shown.

Regards, Eva

**Comment by mad-eye21** [comment]
> 
> 
> Hi @mad-eye21,
> 
> Yes. You have to open the Discover tab. In that tab is all the information of all the alerts.
> You can filter the alerts using `rule.id:5501` so that only the 5501 alerts are shown.
> 
> Regards, Eva

Thank you so much its was really helpful.

**Comment by jsinix** [comment]
I have added the below lines to /var/ossec/etc/ossec.conf 

<logall>yes</logall>

<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
  <allowed-ips>10.10.10.0/24</allowed-ips>
  <local_ip>x.x.x.x</local_ip>
</remote>

I see my logs being appended to /var/ossec/logs/archives/archives.log but it doesn't appear anywhere in wazuh interface. Is there something i am missing ? Using wazuh 4.0

**Comment by jsinix** [comment]
Sending pfsense logs

**Comment by scarfula** [comment]
> I have added the below lines to /var/ossec/etc/ossec.conf
> 
> yes
> 
> syslog 514 udp 10.10.10.0/24 x.x.x.x
> I see my logs being appended to /var/ossec/logs/archives/archives.log but it doesn't appear anywhere in wazuh interface. Is there something i am missing ? Using wazuh 4.0

Hello Jsinix.

Maybe your Alert level is high for firewall logs.
  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
At default in Ossec.conf like above log alert level is 3. when i have same problem like yours i change alert level to 0 and i see my logs at wazuh interface and kibana discover.

Hope this help. Best regards.

**Comment by mrahmatellah** [comment]
hello,

I meet the same problems on pfsense i have configure it to send logs to wazuh manager 

on wazuh manager on : /var/ossec/etc/ossec.conf i add:
<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
  <allowed-ips>192.168.6.0/24</allowed-ips>
  <local_ip>192.168.6.39</local_ip>
</remote>

i also add:

<logall>yes</logall>

i see logs from pfsense on :

/var/ossec/logs/archives/archives.log

but nothing on wazuh interface, i also change log alert level from <log_alert_level>3</log_alert_level>:

to <log_alert_level>0</log_alert_level>


but nothing on wazuh interface and kibana overview 
@jsinix  have you resolv this problem ??

**Comment by scarfula** [comment]
Helloi have configure it to sonicwall decoders for see logs from Dashboard.like a alert levels etc.maybe you may change something in to Pfsense decoders to see logs in dashboard. Hope it will help. Best regards. 16.04.2021, 11:04, "mrahmatellah" ***@***.***>: hello,I meet the same problems on pfsense i have configure it to send logs to wazuh manageron wazuh manager on : /var/ossec/etc/ossec.conf i add:syslog514udp192.168.6.0/24<local_ip>192.168.6.39</local_ip>i also add:yesi see logs from pfsense on :/var/ossec/logs/archives/archives.logbut nothing on wazuh interface, i also change log alert level from <log_alert_level>3</log_alert_level>:to <log_alert_level>0</log_alert_level>but nothing on wazuh interface and kibana ***@***.*** have you resolv this problem ??—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrahmatellah** [comment]
hello @scarfula  sonicwall decoders ? is there a file on wazuh manager that i need to modify it (decoder section )?

i think that on pfsense i have nothing to do, pfsense just send logs, the rest of the work will be on wazuh manager maybe.

if i receiv logs from pfsense, maybe i need just to do something on wazuh manager to get logs on dashboard.

an other question should i condifure an agentless on wazuh ????

**Comment by scarfula** [comment]
Yes There should be a decoder for Pfsense or default decoders. 16.04.2021, 11:19, "mrahmatellah" ***@***.***>: hello @scarfula sonicwall decoders ? is there a file on wazuh manager that i need to modify it (decoder section )?i think that on pfsense i have nothing to do, pfsense just send logs, the rest of the work will be on wazuh manager maybe.if i receiv logs from pfsense, maybe i need just to do something on wazuh manager to get logs on dashboard.an other question should i condifure an agentless on wazuh ????—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrahmatellah** [comment]
when you say default decoder ?? if i go to /var/ossec/ruleset/decoders/ 
i qill found something like XXX-default decoder ??

**Comment by mrahmatellah** [comment]
oh yes found it 0455-pfsense_decoders.xml
can you tell me what you have done with soniwall (your how to to get logs) 

thanks in advance

**Comment by scarfula** [comment]
Hello again Great an Glad you find it. i changed some alert levels in decoder likexxx alert level was 3 and i change it 0 as we made in main configuration on wazuh A key is in decoder and Main configuration alert levels must be same level to logs seen in dashboard 16.04.2021, 11:33, "mrahmatellah" ***@***.***>: oh yes found it 0455-pfsense_decoders.xmlcan you tell me what you have done with soniwall (your how to to get logs)thanks in advance—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrahmatellah** [comment]
so know i see that there is a problem on the decoder when i run /var/ossec/bin/ossec-logtest and past the log received:


![image](https://user-images.githubusercontent.com/33620058/115000305-ecd1e000-9ea2-11eb-9e49-a67a85af5c3f.png)
![image](https://user-images.githubusercontent.com/33620058/115000519-21459c00-9ea3-11eb-80a5-8c66b03290de.png)
![image](https://user-images.githubusercontent.com/33620058/115000594-315d7b80-9ea3-11eb-8de1-7ff3a69afd50.png)

**Comment by mrahmatellah** [comment]
@scarfula, on discover you seeing your log on wich index ?? can you share a screen ?

**Comment by scarfula** [comment]
Oh Sorry cant at the moment kinda in Quarentined becouse of covid and my wasuh work on local area network only. i will show you as son as possible when i am back to office. 16.04.2021, 12:52, "mrahmatellah" ***@***.******@***.***, on discover you seeing your log on wich index ?? can you share a screen ?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by mrahmatellah** [comment]
no prob thanks i found the problme i think

my pfsense send this logs:
 Apr 16 11:10:11 filterlog[24923]: 4,,,1000000103,em0,match,block,in,4,0x0,,128,14042,0,none,17,udp,291,192.168.10.34,192.168.10.255,54915,54915,271
 if i delete the [24923]
 logtest work
 
 
![image](https://user-images.githubusercontent.com/33620058/115016486-61157f00-9eb5-11eb-9c6f-0ffdfdab2529.png)

**Comment by mrahmatellah** [comment]
on pfsense version 2.5.0 the logs countain [XXXX] after filterlog, that's why i think the decoder(pfsense) don't match

**Comment by apoukan** [comment]
Hello all,
I have also a pfsense 2.5.1 and wazuh latest version. 
But I can't get log from pfsense decoded properly...
I use syslog-ng to forward log from pfsense which arrive correctly at the archive.log but when decoded it's not working. I also write a custom decoder but that not passing the phase 2. Some one can help?

**Comment by mrahmatellah** [comment]
hello @apoukan,

can you describe the step to send logs from pfsense syslog-ng to wazuh (especially the config on pfsense syslog-ng) i want to reproduce the same issue to work on it.

**Comment by apoukan** [comment]
By the way im on pfsense 2.5.1 and wazuh 4.1.5

**Comment by apoukan** [comment]
Ok i have something...

first i change the regex on decoders like this :
![image](https://user-images.githubusercontent.com/37113674/117486865-82c0ce00-af6a-11eb-9e5a-9a5d5936210f.png)

<regex type="pcre2">.*?(?=- -).+?(?=,).+?(?=,).+?(?=,),(.+?(?=,)).+?(?=,).+?(?=,),(.+?(?=,)).+?(?=,).+?(?=,).+?(?=,).+?(?=,).+?(?=,).+?(?=,).+?(?=,).+?(?=,).+?(?=,),(.+?(?=,)).+?(?=,),(.+?(?=,)),(.+?(?=,)),(.+?(?=,)),(.+?(?=,)).*</regex>

And this is my rules file :
![image](https://user-images.githubusercontent.com/37113674/117486998-bb60a780-af6a-11eb-942f-4ce9ac8ebb62.png)

Make sure you put the 2 files on /var/ossec/etc/... or they will be overrited by update process.

if you have better solution im open to read 💯
