### ISSUE TITLE
Monitor macOS system log by default

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3455]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Logcollector | Agent | Packages/Sources | macOS Mojave |

Set up a template for Logcollector on macOS. We suggest _/private/var/log/system.log_.

- Search for interesting logs on macOS.
- Check if the ruleset supports the most important security-related logs.

**Comment by jnasselle** [comment]
Hi!

I think this could be related to #4572 implementation.

Regards,
Nico
