### ISSUE TITLE
 files Not monitored anymore

### ISSUE THREAD

**Issue by petersutty** [wazuh/wazuh#3461]
after debugging syscheck I see following:
2019/06/04 12:58:04 ossec-syscheckd[23811] create_db.c:159 at remove_local_diff(): DEBUG: Deleting '/var/ossec/queue/diff/local/www/test/Transaction.php'. Not monitored anymore.
2019/06/04 13:08:49 ossec-syscheckd[23811] create_db.c:275 at read_file(): DEBUG: File '/www/test/Transaction.php'
2019/06/04 13:08:49 ossec-syscheckd[23811] create_db.c:508 at read_file(): DEBUG: Inode already added to db: /www/test/Transaction.php () 
2019/06/04 13:09:44 ossec-syscheckd[23811] create_db.c:159 at remove_local_diff(): DEBUG: Deleting '/var/ossec/queue/diff/local/www/test/Transaction.php'. Not monitored anymore.

In fact I can see, that we monitor? (have diff) only for one file, although the ossec should monitor much more files.

emi29:/var/ossec/queue/diff/local/www/test# sudo ls -l
drwxr-x--- 2 root ossec 4096 Jun  4 13:19 README.md

| 3.8.2-1 | syscheck | Manager/Agent | Packages | debian 8.11 |

**Comment by Skeptor** [comment]
Hi Peter,

It would be so helpful if I could see your ossec.conf to check your syscheck configuration.
There is a bug in FIM in 3.8.x versions when the option to calculate the inodes of the files is disabled that doesn't allow syscheck to update the Hash tables. I would like to check if it is happening in your environment.

Regards,
Pablo.

**Comment by petersutty** [comment]
Hi Pablo,
I just noticed we have this version available - 3.9.1-1 on debian. Is it
fixed in that version ?
Thanks,
Peter

**Comment by Skeptor** [comment]
Hi Peter,

Yes. It is solved in 3.9.1-1.
Thank you for your interest, feel free to ask if you need something more.

Regards,
Pablo

**Comment by petersutty** [comment]
Hi Pablo,
I did upgrade to 3.9.1-1, but there is another problem now - it seem like
wazuh is following symbolic links, even though it should not
(*follow_symbolic_link
- *default value is "no")

ossec.conf:

<agent_config>

 <client>
   <server>
     <address>10.99.4.4</address>
     <port>1514</port>
     <protocol>udp</protocol>
   </server>
   <config-profile>debian9, debian9.8</config-profile>
   <notify_time>10</notify_time>
   <time-reconnect>60</time-reconnect>
   <auto_restart>yes</auto_restart>
   <crypto_method>aes</crypto_method>
 </client>

 <client_buffer>
   
   <disabled>no</disabled>
   <queue_size>5000</queue_size>
   <events_per_second>500</events_per_second>
 </client_buffer>

 
 <syscheck>
   <disabled>no</disabled>

   
   <frequency>600</frequency>

   <scan_on_start>yes</scan_on_start>

   
   <alert_new_files>yes</alert_new_files>

   
   <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>

   
   <directories report_changes="yes" check_all="yes"
realtime="yes">/etc,/usr/bin,/usr/sbin</directories>
   <directories report_changes="yes" check_all="yes"
realtime="yes">/bin,/sbin,/boot</directories>

   
   <ignore>/etc/mtab</ignore>
   <ignore>/etc/hosts.deny</ignore>
   <ignore>/etc/mail/statistics</ignore>
   <ignore>/etc/random-seed</ignore>
   <ignore>/etc/random.seed</ignore>
   <ignore>/etc/adjtime</ignore>
   <ignore>/etc/httpd/logs</ignore>
   <ignore>/etc/utmpx</ignore>
   <ignore>/etc/wtmpx</ignore>
   <ignore>/etc/cups/certs</ignore>
   <ignore>/etc/dumpdates</ignore>
   <ignore>/etc/svc/volatile</ignore>
   <ignore>/sys/kernel/security</ignore>
   <ignore>/sys/kernel/debug</ignore>

   
   <ignore type="sregex">.log$|.swp$</ignore>
   <ignore type="sregex">.git</ignore>

   
   <nodiff>/etc/ssl/private.key</nodiff>

   <skip_nfs>yes</skip_nfs>

   
   <restart_audit>yes</restart_audit>
 </syscheck>

<agent_config>

 <syscheck>
   <directories realtime="yes" check_sha256sum="yes"
report_changes="yes">/www/app-staging/current</directories>
   <directories realtime="yes" check_sha256sum="yes"
report_changes="yes">/www/emi3/current</directories>
   <ignore>/www/app-staging/current/app/cache</ignore>
   <ignore>/www/emi3/current/cache</ignore>
 </syscheck>

</agent_config>

emi29:~# ls -la /www/app-staging/current
lrwxrwxrwx 1 www-data www-data 51 Jun  4 10:25 /www/app-staging/current ->
/www/app-staging/releases/20190604102339
emi29:~# ls -la /var/ossec/queue/diff/local/www/app-staging/
total 12
drwxr-x--- 3 root ossec 4096 Jun  5 09:19 .
drwxr-x--- 4 root ossec 4096 Jun  5 09:18 ..
drwxr-x--- 3 root ossec 4096 Jun  5 09:17 releases
emi29:~# ls -la /var/ossec/queue/diff/local/www/app-staging/releases/
total 12
drwxr-x---  3 root ossec 4096 Jun  5 09:17 .
drwxr-x---  3 root ossec 4096 Jun  5 09:19 ..
drwxr-x--- 17 root ossec 4096 Jun  5 09:18 20190604102339
emi29:~# ls -la
/var/ossec/queue/diff/local/www/app-staging/releases/20190604102339/
total 68
drwxr-x--- 17 root ossec 4096 Jun  5 09:18 .
drwxr-x---  3 root ossec 4096 Jun  5 09:17 ..
drwxr-x--- 14 root ossec 4096 Jun  5 09:18 app
drwxr-x--- 23 root ossec 4096 Jun  5 09:18 bin
drwxr-x---  2 root ossec 4096 Jun  5 09:20 composer.json
drwxr-x---  2 root ossec 4096 Jun  5 09:20 composer.lock
drwxr-x---  2 root ossec 4096 Jun  5 09:20 .editorconfig
drwxr-x---  4 root ossec 4096 Jun  5 09:18 etc
drwxr-x---  2 root ossec 4096 Jun  5 09:20 .htaccess
drwxr-x---  2 root ossec 4096 Jun  5 09:20 LICENSE
drwxr-x---  2 root ossec 4096 Jun  5 09:19 Makefile
drwxr-x---  2 root ossec 4096 Jun  5 09:19 README.md
drwxr-x---  2 root ossec 4096 Jun  5 09:19 REVISION
drwxr-x---  5 root ossec 4096 Jun  5 09:17 src
drwxr-x---  3 root ossec 4096 Jun  5 09:17 untracked-vendor
drwxr-x--- 68 root ossec 4096 Jun  5 09:18 vendor
drwxr-x--- 18 root ossec 4096 Jun  5 09:18 web

comparing to behaviour before - emi21 was not upgraded yet :
emi21:~# ls -la /var/ossec/queue/diff/local/www/emi/
total 12
drwxr-x--- 3 root ossec 4096 May 28 12:36 .
drwxr-x--- 3 root ossec 4096 Jun  5 09:31 ..
drwxr-x--- 3 root ossec 4096 Jun  5 09:31 current
emi21:~# ls -l /var/ossec/queue/diff/local/www/emi/current/
total 44
drwxr-x---  2 root ossec 4096 Jun  3 09:19 composer.json
drwxr-x---  9 root ossec 4096 Jun  5 09:42 config
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 docs
drwxr-x--- 14 root ossec 4096 Jun  5 09:42 EMI
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 i18n
drwxr-x--- 16 root ossec 4096 Jun  5 09:42 lib
drwxr-x--- 17 root ossec 4096 Jun  5 09:42 public
drwxr-x---  2 root ossec 4096 Jun  5 09:42 REVISION
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 templates
drwxr-x---  3 root ossec 4096 Jun  5 09:42 tools
drwxr-x---  3 root ossec 4096 Jun  5 09:42 vhosts

The following difference is also interesting - ls -la gives less lines then
before ls -l - this is not relevant for me atm.
emi21:~# ls -la  /var/ossec/queue/diff/local/www/emi/current/
total 12
drwxr-x--- 3 root ossec 4096 Jun  5 09:43 .
drwxr-x--- 3 root ossec 4096 May 28 12:36 ..
drwxr-x--- 2 root ossec 4096 Jun  3 09:19 composer.json

I believe this is a bug or has something to do with the documentation for
*follow_symbolic_link*  "If set, realtime works as usual (with symbolic
links to directories, not files)."

Regards,
Peter

**Comment by Skeptor** [comment]
Hi Peter,

The option `follow_symbolic_link` prevent syscheck from following a symbolic link detected inside a monitored directory. This case is different because syscheck is monitoring the symbolic link directly.
Instead of monitor the symbolic link:
 `<directories realtime="yes" check_sha256sum="yes" report_changes="yes">/www/app-staging/current</directories>` 
You can monitor the folder:
 `<directories realtime="yes" check_sha256sum="yes" report_changes="yes">/www/app-staging</directories>` 
Then the symbolic link won't be monitored if the option `follow_symbolic_link` isn't enabled.

Due to technical reasons, the behaviour of symbolic links inside directories and links directly monitored is different.

Regards,
Pablo.

**Comment by petersutty** [comment]
Hi Pablo,

so the behavior change is expected, right ?

What we want to achieve, is to monitor files content change, nevermind if
the symbolic link change, for instance:
we monitor /www/app-staging/current/file.php
So if we release new version, we relink the current folder - I don't care
if the symbolic link changed, I want only to know if the end file changed.
Is this achievable somehow ?

Regards,
Peter

**Comment by Skeptor** [comment]
Hi Peter,

If you want to monitor a file over a symbolic link you can add the file to the syscheck configuration. In this case, if `/www/app-staging/current` is a symbolic link for `/www/app-staging/releases/20190604102339` and you want to monitor `file.php` inside `releases/20190604102339` you can add
`<directories>/www/app-staging/current/file.php</directories>` 
to your ossec.conf and it will work.
The only thing different is that the backup file for `file.php` in `/var/ossec/queue/diff/` will be stored in `/www/app-staging/releases/20190604102339/file.php/last-entry.gz`.

Hope it helps you.

Regards,
Pablo.

**Comment by petersutty** [comment]
Hi Pablo,

thanks a lot for suggestions, but non of them is good enough. I did several
test, with different configs.
The change how wazuh stores the diffs in latest release (if symlink folder
is monitored, then syscheck follows that symlink), is the breakpoint here I
think and that is what changed to version 3.8.2-1.
Can you please just confirm, this behaviour is a feature, not a bug and it
is going to be that way ?

For your convenience:
   <directories realtime="yes" check_sha256sum="yes"
report_changes="yes">/www/app-staging/current</directories>

3.8.2-1
emi21:~# ls -la /var/ossec/queue/diff/local/www/emi/
total 12
drwxr-x--- 3 root ossec 4096 May 28 12:36 .
drwxr-x--- 3 root ossec 4096 Jun  5 09:31 ..
drwxr-x--- 3 root ossec 4096 Jun  5 09:31 current
emi21:~# ls -l /var/ossec/queue/diff/local/www/emi/current/
total 44
drwxr-x---  2 root ossec 4096 Jun  3 09:19 composer.json
drwxr-x---  9 root ossec 4096 Jun  5 09:42 config
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 docs
drwxr-x--- 14 root ossec 4096 Jun  5 09:42 EMI
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 i18n
drwxr-x--- 16 root ossec 4096 Jun  5 09:42 lib
drwxr-x--- 17 root ossec 4096 Jun  5 09:42 public
drwxr-x---  2 root ossec 4096 Jun  5 09:42 REVISION
drwxr-x--- 10 root ossec 4096 Jun  5 09:42 templates
drwxr-x---  3 root ossec 4096 Jun  5 09:42 tools
drwxr-x---  3 root ossec 4096 Jun  5 09:42 vhosts

3.9.1-1
emi29:~# ls -la /www/app-staging/current
lrwxrwxrwx 1 www-data www-data 51 Jun  4 10:25 /www/app-staging/current ->
/www/app-staging/releases/20190604102339
emi29:~# ls -la /var/ossec/queue/diff/local/www/app-staging/
total 12
drwxr-x--- 3 root ossec 4096 Jun  5 09:19 .
drwxr-x--- 4 root ossec 4096 Jun  5 09:18 ..
drwxr-x--- 3 root ossec 4096 Jun  5 09:17 releases
emi29:~# ls -la /var/ossec/queue/diff/local/www/app-staging/releases/
total 12
drwxr-x---  3 root ossec 4096 Jun  5 09:17 .
drwxr-x---  3 root ossec 4096 Jun  5 09:19 ..
drwxr-x--- 17 root ossec 4096 Jun  5 09:18 20190604102339
emi29:~# ls -la /var/ossec/queue/diff/local/www/app-staging/releases/
20190604102339/
total 68
drwxr-x--- 17 root ossec 4096 Jun  5 09:18 .
drwxr-x---  3 root ossec 4096 Jun  5 09:17 ..
drwxr-x--- 14 root ossec 4096 Jun  5 09:18 app
drwxr-x--- 23 root ossec 4096 Jun  5 09:18 bin
drwxr-x---  2 root ossec 4096 Jun  5 09:20 composer.json
drwxr-x---  2 root ossec 4096 Jun  5 09:20 composer.lock
drwxr-x---  2 root ossec 4096 Jun  5 09:20 .editorconfig
drwxr-x---  4 root ossec 4096 Jun  5 09:18 etc
drwxr-x---  2 root ossec 4096 Jun  5 09:20 .htaccess
drwxr-x---  2 root ossec 4096 Jun  5 09:20 LICENSE
drwxr-x---  2 root ossec 4096 Jun  5 09:19 Makefile
drwxr-x---  2 root ossec 4096 Jun  5 09:19 README.md
drwxr-x---  2 root ossec 4096 Jun  5 09:19 REVISION
drwxr-x---  5 root ossec 4096 Jun  5 09:17 src
drwxr-x---  3 root ossec 4096 Jun  5 09:17 untracked-vendor
drwxr-x--- 68 root ossec 4096 Jun  5 09:18 vendor
drwxr-x--- 18 root ossec 4096 Jun  5 09:18 web


Regards,
Peter

**Comment by Skeptor** [comment]
Hi Peter,

Yes, the behaviour of symbolic folders that are directly monitored in the ossec.conf is going to be that way.

Regards,
Pablo.

**Comment by petersutty** [comment]
Thanks Pablo, closing ticket.
