### ISSUE TITLE
Adapt framework to the 'internal_options' deprecation

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#3462]
Hi team,

In order to fully develop the deprecation of the `internal_options` file (https://github.com/wazuh/wazuh/issues/3150), some changes need to be done in the Wazuh API:

- [x] Add `wazuhdb` to the on-demand configuration components.

- [x] Read the cluster debug configuration from `ossec.conf`

- [x] Include this option to the on-demand configuration of `cluster` module (`config/com/cluster`)

A few notes on the last two checks:
- This option will be called `log_level`, it'll be on the `cluster` module and it must accept these values: `0`, `1` and `2`.
- The algorithm will be the following:

    1. Read the option from `internal_options`/ `local_internal_options` (as it is now).
    2. If the option is not present in any of those two files, read the option from `ossec.conf` (as it was specified above).
    3. If the option is not present in `ossec.conf` either, set the `debug_level` to 0 (default value).

If anything new related to this appears this issue will be updated.

**Comment by druizz90** [comment]
Hi team,

I worked in order to adapt framework to these changes.

`wazuhdb` was added to to the on-demand configuration components:

```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/cluster/master/config/wazuhdb/internal?pretty"
{
   "error": 0,
   "data": {
      "internal": {
         "wdb": {
            "worker_pool_size": 8,
            "commit_time": 60,
            "open_db_limit": 64,
            "rlimit_nofile": 65536,
            "log_level": 0,
            "thread_stack_size": 8192
         }
      }
   }
}
```

Cluster reads the debug configuration from `ossec.conf` if this option is not present into `internal_options` or `local_internal_options`. I made different tests for checking that log level configuration is set properly depending if it was set in `local_internal_options`, `internal_options` or `ossec.conf`.

`log_level` is not set in any configuration:
```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/cluster/master/config/com/cluster?pretty"
{
   "error": 0,
   "data": {
      "name": "wazuh",
      "node_name": "master",
      "node_type": "master",
      "key": "9d273b53510fef702b54a92e9cffc82e",
      "port": 1516,
      "bind_addr": "0.0.0.0",
      "nodes": [
         "wazuh-master"
      ],
      "hidden": "no",
      "disabled": false,
      "log_level": 0
   }
}
```

`log_level=1` in `ossec.conf`:
```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/cluster/master/config/com/cluster?pretty"
{
   "error": 0,
   "data": {
      "name": "wazuh",
      "node_name": "master",
      "node_type": "master",
      "key": "9d273b53510fef702b54a92e9cffc82e",
      "port": 1516,
      "bind_addr": "0.0.0.0",
      "nodes": [
         "wazuh-master"
      ],
      "hidden": "no",
      "disabled": false,
      "log_level": 1
   }
}
```

`log_level=2` in `internal_options`:
```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/cluster/master/config/com/cluster?pretty"
{
   "error": 0,
   "data": {
      "name": "wazuh",
      "node_name": "master",
      "node_type": "master",
      "key": "9d273b53510fef702b54a92e9cffc82e",
      "port": 1516,
      "bind_addr": "0.0.0.0",
      "nodes": [
         "wazuh-master"
      ],
      "hidden": "no",
      "disabled": false,
      "log_level": 2
   }
}
```

`log_level=1` in `local_internal_options`:
```bash
# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/cluster/master/config/com/cluster?pretty"
{
   "error": 0,
   "data": {
      "name": "wazuh",
      "node_name": "master",
      "node_type": "master",
      "key": "9d273b53510fef702b54a92e9cffc82e",
      "port": 1516,
      "bind_addr": "0.0.0.0",
      "nodes": [
         "wazuh-master"
      ],
      "hidden": "no",
      "disabled": false,
      "log_level": 1
   }
}
```

If `log_level` is set with a value higher than `2`, `log_level` will be equal to `2`, which is the maximum value.

Best regards,

Demetrio.
