### ISSUE TITLE
Null compliance lists causes SCA to sigsev

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3463]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9| SCA| Manager/Agent | -- | -- |

Checks with a compliance NULL list such as 
```yml
compliance:
  - null
```
Can cause a SIGSEV on `wm_sca_build_event` as it accesses `compliance->child->valuestring` without testing the NULLness of `compliance->child`

**Comment by chemamartinez** [comment]
Merged #3464
