### ISSUE TITLE
Custom integration with external api don't work in wazuh 3.9.1

### ISSUE THREAD

**Issue by EvaSok98** [wazuh/wazuh#3467]
Wazuh version 3.9.1

After upgrading to 3.9.1 version my custom integration don't work. 
In /var/ossec/logs/ossec.log I see:
`2019/06/05 13:44:50 ossec-integratord: INFO: Started (pid: 17630).
2019/06/05 13:44:50 ossec-integratord: ERROR: Invalid integration: 'jira'. Not currently supported.`
In docs name can be only slack, pagerduty, virustotal:
https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/integration.html#name

Can I use custom integration in 3.9.1 as I do earlier?

**Comment by Zenidd** [comment]
Hello @EvaSok98,

Could you paste here your <integration> settings so I can better see what the situation is? 
Feel free to obfuscate your APIkey/Creedentials.


Kind regards,

Juan Pablo Sáez

**Comment by EvaSok98** [comment]
I wrote my custom integration with jira. In previous version of wazuh (3.8) all worked ok.
My script locates in /var/ossec/integrations/jira.
Part of /var/ossec/etc/ossec.conf: 
`  <integration>
    <name>jira</name>
    <level>3</level>
    <group>jira-alert</group>
    <hook_url>url</hook_url>
    <api_key>username:key</api_key>
    <alert_format>json</alert_format>
  </integration>
`

**Comment by Zenidd** [comment]
Hello again @EvaSok98,

What method have you chosen to perform the update?

I've tried to recreate your environment without success:

1. Installed Wazuh-manager v3.8.2 via packages. 
2. Successfully configured integration with jira.
3. Updated to Wazuh-manager v3.9.2 via repository. 
4. Jira keeps working


With a little more information we can have your integration with jira working again.
<br></br>
Regards,

Juan Pablo Sáez

**Comment by EvaSok98** [comment]
Hello, Juan Pablo Sáez!

I updated wazuh using this guide:
https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

As I mentioned earlier in this documentation https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/integration.html#name allowed values for name is only slack, pagerduty, virustotal:
![image](https://user-images.githubusercontent.com/48674472/59270261-b4836a00-8c59-11e9-9b5e-e0f710d5deab.png)

Maybe this is a problem?

**Comment by Zenidd** [comment]
Hi @EvaSok98, 

As you have seen in the documentation for the integration, the allowed values are slack, pagerduty and virustotal. If you want to do another integration different to these three, it is necessary that the name of the integration and the script start with `custom-`. This information does not appear in the documentation and we will update it as soon as possible.

In the following line you can see how the integration name is checked:
https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_integrator/integrator.c#L103

Honestly, we don't know how you've been able to work with your integration as it's called `jira` and not `custom-jira` as it should be.
<br></br>
I think we can solve your problem by modifying the name of your script and your integration as in the further example:

- `/var/ossec/integrations/jira`  ----------> `/var/ossec/integrations/custom-jira`
- on ossec.conf at `<integration>`: `<name>jira</name>` ----------> `<name>custom-jira</name>`

With that configuration you shouldn't have any problems from now on when you perform an update.
Please let me know if it helps. 

Kind regards,

Juan Pablo Sáez

**Comment by EvaSok98** [comment]
Hi, Juan Pablo Sáez!

I changed name from jira to custom-jira and now it's ok. Thank you very much!

**Comment by tekletade** [comment]
Please can you help me; how the custom-jira code looks like??

**Comment by aldahirbj23** [comment]
EvaSok98 what is the url? and username y api key, where I can search it?

**Comment by AhmadNazir7** [comment]
Hi everyone,

I want to know , How can I integrate WAZUH with ServiceNow(SNOW) is there any article or anything related to that, it will be a huge help for me.

Thanks in advance.
