### ISSUE TITLE
Possible file descriptor leak in agent's wazuh-modulesd

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#3468]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2-3923 | wazuh-modulesd | Agent | Packages | CentOS 7 |

Hi team,

While testing the tag v3.9.2-rc1, I noticed something weird in the file descriptors opened by `wazuh-modulesd`. Here you can see the image:
![image](https://user-images.githubusercontent.com/9081114/58952031-f496a880-8792-11e9-8d53-8218fa97a096.png)
The deep blue line indicates how the file descriptors opened by `wazuh-modulesd` never stop growing over the test, which may indicate a possible file descriptors leak in this daemon. 

You can find attached the [ossec.conf](https://github.com/wazuh/wazuh/files/3256872/ossec.conf.txt) file used by the agent. 

Regards,
Braulio.

**Comment by bah07** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/3470
