### ISSUE TITLE
cluster_control does not work when clusterd is launched manually

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3473]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.1 | wazuh-clusterd | Manager | Any | Any |

The script `cluster_control` checks needs that `wazuh-clusterd` is running. The way to check that is looking for the .pid file, which is not generated when clusterd is executed manually instead of using ossec-control.

The line involved is https://github.com/wazuh/wazuh/blob/13fd8ce3b92cb1edad95c9d1a3c0547db173f58a/framework/scripts/cluster_control.py#L146.

It calls `get_status_json` in cluster.py:
https://github.com/wazuh/wazuh/blob/13fd8ce3b92cb1edad95c9d1a3c0547db173f58a/framework/wazuh/cluster/cluster.py#L173
which uses the `status` function in manager.py:
https://github.com/wazuh/wazuh/blob/13fd8ce3b92cb1edad95c9d1a3c0547db173f58a/framework/wazuh/manager.py#L31

It is necessary to find a better way to check if there is communication with clusterd different from reading a .pid file.

**Comment by Selutario** [comment]
Fixed in #6724
