### ISSUE TITLE
Race condition hazards due to non-reentrant function calls

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3474]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.7.0 | Analysis, Remote, Syscheck, Modules, Auth | All | All | UNIX platforms |

We have found many calls to non-reentrant functions in Wazuh. Some of them may produce a race condition and potentially corrupt data or produce a crash.

Please review every call to non-reentrant functions and determine whether they produce a race condition hazard. In that case, replace them with their reentrant equivalent call.

### Related issue

#3445 

### List of thread-unsafe functions

[Thread-safety and POSIX.1](http://www.unix.org/whitepapers/reentrant.html)

### `ctime()`

- [x] ./shared/read-agents.c:989: `os_strdup(ctime(&fim_start), timestamp);`
- [x] ./shared/read-agents.c:1000: `os_strdup(ctime(&fim_start), agt_info->syscheck_time);`
- [x] ./shared/read-agents.c:1011: `os_strdup(ctime(&fim_end), agt_info->syscheck_endtime);`
- [x] ./shared/read-agents.c:1047: `os_strdup(ctime(&s_time), agt_info->rootcheck_time);`
- [x] ./shared/read-agents.c:1063: `os_strdup(ctime(&s_time), agt_info->rootcheck_endtime);`
- [x] ./shared/read-agents.c:1104: `return (strdup(ctime(&file_status.st_mtime)));`
- [x] ./analysisd/alerts/log.c:196: `printf(" - Date: %s", ctime(&lf->mtime_after));`
- [x] ./analysisd/alerts/log.c:381: `fprintf(_aflog, " - Date: %s", ctime(&lf->mtime_after));`
- [x] ./analysisd/decoders/syscheck.c:674: `char *old_ctime = strdup(ctime(&oldsum->mtime));`
- [x] ./analysisd/decoders/syscheck.c:675: `char *new_ctime = strdup(ctime(&newsum->mtime));`

### `strtok()`

- [x] ./config/syscheck-config.c:1279: `key = strtok(children[j]->content, &delim);`
- [x] ./config/syscheck-config.c:1286: `key = strtok(NULL, &delim);`
- [x] ./wazuh_modules/wm_oscap.c:238: `for (line = strtok(output, "\n"); line; line = strtok(NULL, "\n")){`
- [x] ./wazuh_modules/wm_command.c:206: `for (line = strtok(output, "\n"); line; line = strtok(NULL, "\n")){`
- [x] ./wazuh_modules/wmodules.c:509: `path = strtok(env_path, sep);`
- [x] ./wazuh_modules/wmodules.c:524: `path = strtok(NULL, sep);`
- [x] ./wazuh_modules/wm_download.c:120: `if (command = strtok(buffer, " "), !(command && *command)) {`
- [x] ./wazuh_modules/wm_download.c:136: `if (url = strtok(NULL, " "), !(url && *url)) {`
- [x] ./wazuh_modules/wm_download.c:144: `if (fpath = strtok(NULL, " "), !(fpath && *fpath)) {`
- [x] ./wazuh_modules/wm_aws.c:453: `for (line = strtok(output, "\n"); line; line = strtok(NULL, "\n")){`
- [x] ./wazuh_modules/wm_aws.c:584: `for (line = strtok(output, "\n"); line; line = strtok(NULL, "\n")){`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1064: `cpuname = strtok(string, ":");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1065: `cpuname = strtok(NULL, "\n");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1075: `frec = strtok(string, ":");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1076: `frec = strtok(NULL, "\n");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1097: `aux_string = strtok(string, ":");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1098: `aux_string = strtok(NULL, "\n");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1107: `aux_string = strtok(string, ":");`
- [x] ./wazuh_modules/syscollector/syscollector_linux.c:1108: `aux_string = strtok(NULL, "\n");`
- [x] ./agentlessd/agentlessd.c:309: `for (token = strtok(_options, " "); token; token = strtok(NULL, " ")) {`
- [x] ./addagent/manage_keys.c:357: `token = strtok(line, delims);`
- [x] ./addagent/manage_keys.c:361: `token = strtok(NULL, delims);`
- [x] ./syscheckd/seechanges.c:268: `tmpstr = strtok(buffer + PATH_OFFSET, "/\\");`
- [x] ./syscheckd/seechanges.c:270: `tmpstr = strtok(buffer + PATH_OFFSET, "/");`
- [x] ./syscheckd/seechanges.c:279: `while (next = strtok(NULL, "/\\"), next) {`
- [x] ./syscheckd/seechanges.c:281: `while (next = strtok(NULL, "/"), next) {`
- [x] ./wazuh_db/wdb_agent.c:644: `multi_group = strtok(group, delim);`
- [x] ./wazuh_db/wdb_agent.c:659: `multi_group = strtok(NULL, delim);`
- [x] ./shared/version_op.c:319: `tag = strtok(buff, "=");`
- [x] ./shared/version_op.c:322: `name = strtok(NULL, "\n");`
- [x] ./shared/version_op.c:330: `version = strtok(NULL, "\n");`
- [x] ./shared/version_op.c:338: `id = strtok(NULL, " \n");`
- [x] ./shared/version_op.c:447: `tag = strtok(buff, "=");`
- [x] ./shared/version_op.c:449: `info->os_version = strdup(strtok(NULL, "\n"));`
- [x] ./shared/version_op.c:549: `} else if(strcmp(strtok(buff, "\n"),"Darwin") == 0){`
- [x] ./shared/version_op.c:555: `info->os_name = strdup(strtok(buff, "\n"));`
- [x] ./shared/version_op.c:563: `info->os_version = strdup(strtok(buff, "\n"));`
- [x] ./shared/version_op.c:571: `info->os_build = strdup(strtok(buff, "\n"));`
- [x] ./shared/version_op.c:588: `} else if (strcmp(strtok(buff, "\n"),"SunOS") == 0){ // Sun OS`
- [x] ./shared/version_op.c:619: `} else if (strcmp(strtok(buff, "\n"),"HP-UX") == 0){ // HP-UX`
- [x] ./shared/version_op.c:632: `} else if (strcmp(strtok(buff, "\n"),"OpenBSD") == 0 ||`
- [x] ./shared/version_op.c:633: `strcmp(strtok(buff, "\n"),"NetBSD")  == 0 ||`
- [x] ./shared/version_op.c:634: `strcmp(strtok(buff, "\n"),"FreeBSD") == 0 ){ // BSD`
- [x] ./shared/version_op.c:647: `} else if (strcmp(strtok(buff, "\n"),"Linux") == 0){ // Linux undefined`
- [x] ./shared/agent_op.c:508: `char *individual_group = strtok(multi_group_cpy, delim);`
- [x] ./shared/agent_op.c:519: `individual_group = strtok(NULL, delim);`
- ./os_auth/check_cert.c:216: `* of labels found. strtok() is not used as we want to detect labels with` (NOT APLICABLE)
- [x] ./os_auth/main-server.c:874: `char *group = strtok(groups_added, delim);`
- [x] ./os_auth/main-server.c:940: `group = strtok(NULL, delim);`
- [x] ./remoted/manager.c:478: `group = strtok(multi_group, delim);`
- [x] ./remoted/manager.c:544: `group = strtok(NULL, delim);`

### `srandom()`

- ./win32/win_agent.c:234: `srandom(time(0));` (NOT APLICABLE)
- ./os_integrator/main.c:145: `srandom( time(0) + getpid()+ i);` (NOT APLICABLE)
- ./headers/shared.h:149:#define srandom(x) srand(x)` (NOT APLICABLE)
- ./shared/hash_op.c:53: `srandom((unsigned int)time(0));` (NOT APLICABLE)
- ./shared/randombytes.c:84: `srandom(seed);` (NOT APLICABLE)

When we use srandom() we don't call to random() so it's innecesary to change srandom() by srandom_r(). In consecuense, we're not going to change this function.

### `gmtime()`

- [x] ./config/wmodules-vuln-detector.c:205: `t_date = gmtime(&n_date);`

### `localtime()`

- [x] ./config/localfile-config.c:395: ``p = localtime(&l_time);``
- [x] ./config/localfile-config.c:439: `p = localtime(&l_time);`
- [x] ./config/localfile-config.c:465: `p = localtime(&l_time);`
- [x] ./win32/setup-iis.c:203: `p = localtime(&tm);`
- [x] ./win32/add-localfile.c:79: `p = localtime(&tm);`
- [x] ./monitord/monitord.c:42: `p = localtime(&tm);`
- [x] ./monitord/monitord.c:79: `p = localtime(&tm);`
- [x] ./monitord/manage_files.c:35: `pp_old = localtime(&tm_old);`
- [x] ./wazuh_modules/wm_vuln_detector.c:2097: `tm_time = localtime(&l_time);`
- [x] ./wazuh_modules/wmodules.c:358: `time_now = localtime(&curr_time);`
- [x] ./wazuh_modules/wmodules.c:398: `time_now = localtime(&curr_time);`
- [x] ./wazuh_modules/wmodules.c:449: `time_now = localtime(&curr_time);`
- [x] ./agentlessd/agentlessd.c:452: `p = localtime(&tm);`
- [x] ./agentlessd/agentlessd.c:468: `p = localtime(&tm);`
- [x] ./addagent/validate.c:707: `strftime(timestamp, 40, "%Y", localtime(&now));`
- [x] ./addagent/validate.c:718: `strftime(timestamp, 40, "%Y/%b", localtime(&now));`
- [x] ./addagent/validate.c:729: `strftime(timestamp, 40, "%Y/%b/%d", localtime(&now));`
- [x] ./addagent/validate.c:776: `strftime(timestamp, 40, "%Y-%m-%d %H:%M:%S", localtime(&now));`
- [x] ./syscheckd/run_check.c:209: `p = localtime(&curr_time);`
- [x] ./syscheckd/run_check.c:245: `p = localtime(&curr_time);`
- [x] ./logcollector/read_win_el.c:80: `ts = localtime(&epoch);`
- [x] ./logcollector/read_djb_multilog.c:145: `pt = localtime(&djbtime);`
- [x] ./logcollector/logcollector.c:751: `p = localtime(&__ctime);`
- [x] ./os_dbd/dbd.c:31: `p = localtime(&tm);`
- [x] ./os_dbd/dbd.c:44: `p = localtime(&tm);`
- [x] ./os_maild/maild.c:241: `p = localtime(&tm);`
- [x] ./os_maild/maild.c:279: `p = localtime(&tm);`
- [x] ./os_csyslogd/csyslogd.c:45: `p = localtime(&tm);`
- [x] ./os_csyslogd/csyslogd.c:98: `p = localtime(&tm);`
- [x] ./shared/read-agents.c:308: `tm_time = localtime(&change_time);`
- [x] ./shared/read-agents.c:428: `tm_time = localtime(&change_time);`
- [x] ./shared/read-agents.c:571: `tm_time = localtime(time_last_scan);`
- [x] ./shared/read-agents.c:641: `tm_time = localtime((time_t *)&s_time);`
- [x] ./shared/read-agents.c:643: `tm_time = localtime((time_t *)&i_time);`
- [x] ./shared/report_op.c:398: `p = localtime(&tm);`
- [x] ./analysisd/stats.c:473: `p = localtime(&c_time);`
- [x] ./analysisd/format/to_json.c:296: `strftime(mtime, 20, "%FT%T%z", localtime(&lf->mtime_before));`
- [x] ./analysisd/format/to_json.c:301: `strftime(mtime, 20, "%FT%T%z", localtime(&lf->mtime_after));`
- [x] ./analysisd/cleanevent.c:557: `localtime(&c_time);`
- [x] ./analysisd/analysisd.c:2485: `p = localtime(&c_time);`

### `getgrgid()`

- [x] ./shared/syscheck_op.c:579: `struct group *group = getgrgid(gid);`

### `getgrnam()`

- [x] ./config/active-response.c:63: `if ((os_group = getgrnam(USER)) == NULL) {`
- [x] ./shared/privsep_op.c:39: `grp = getgrnam(name);`
- [x] ./analysisd/active-response.c:57: `if ((os_group = getgrnam(USER)) == NULL) {`

### `getpwuid()`

- [x] ./shared/syscheck_op.c:574: `struct passwd *user = getpwuid(uid);`

### `getpwnam()`

- [x] ./shared/privsep_op.c:28: `pw = getpwnam(name);`

### `readdir()`

- [ ] ./config/rules-config.c:294: `while ((entry = readdir(dfd)) != NULL) {`
- [ ] ./config/rules-config.c:351: `while ((entry = readdir(dfd)) != NULL) {`
- [ ] ./monitord/rotate_log.c:204: `while (dirent = readdir(dir), dirent) {`
- [ ] ./monitord/rotate_log.c:230: `while (dirent = readdir(dir), dirent) {`
- [ ] ./monitord/rotate_log.c:278: `while (dirent = readdir(dir), dirent) {`
- [ ] ./wazuh_modules/wm_database.c:452: `while ((dirent = readdir(dir))) {`
- [ ] ./wazuh_modules/wm_database.c:770: `while ((dirent = readdir(dir)))`
- [ ] ./wazuh_modules/wm_sca.c:1720: `while ((entry = readdir(dp)) != NULL) {`
- [x] ./wazuh_modules/syscollector/syscollector_bsd.c:92: `while ((de = readdir(dr)) != NULL) {`
- [x] ./wazuh_modules/syscollector/syscollector_bsd.c:119: `while ((de = readdir(dr)) != NULL) {`
- [x] ./wazuh_modules/syscollector/syscollector_bsd.c:151: `while ((de = readdir(dr)) != NULL) {`
- [x] ./wazuh_modules/syscollector/syscollector_bsd.c:171: `while ((version = readdir(dir)) != NULL) {`
- [ ] ./addagent/validate.c:604: `while ((dp = readdir(dirp)) != NULL) {`
- [ ] ./syscheckd/create_db.c:67: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./syscheckd/create_db.c:769: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./logcollector/logcollector.c:1311: `while (dirent = readdir(dir), dirent) {`
- [ ] ./logcollector/logcollector.c:2191: `while (dirent = readdir(dir), dirent) {`
- [ ] ./rootcheck/check_rc_sys.c:211: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./rootcheck/check_rc_dev.c:101: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./rootcheck/check_rc_readproc.c:60: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./rootcheck/util/ads_dump.c:140: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./rootcheck/common.c:46: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./rootcheck/common.c:432: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./wazuh_db/main.c:401: `while ((db = readdir(fd)) != NULL) {`
- [ ] ./wazuh_db/wdb_agent.c:847: `while ((dirent = readdir(dir))){`
- [ ] ./util/rootcheck_control.c:206: `while ((entry = readdir(sys_dir)) != NULL) {`
- [ ] ./util/syscheck_update.c:103: `while ((entry = readdir(sys_dir)) != NULL) {`
- [ ] ./util/clear_stats.c:103: `while ((entry = readdir(daily)) != NULL) {`
- [ ] ./util/clear_stats.c:136: `while ((entry = readdir(daily)) != NULL) {`
- [ ] ./util/verify-agent-conf.c:95: `while (entry = readdir(gdir), entry) {`
- [ ] ./util/syscheck_control.c:238: `while ((entry = readdir(sys_dir)) != NULL) {`
- [ ] ./shared/read-agents.c:1285: `while ((entry = readdir(dp)) != NULL) {`
- [ ] ./shared/file_op.c:855: `while ((ent = readdir(dir)) != NULL) {`
- [ ] ./shared/file_op.c:1991: `while (dirent = readdir(dir), dirent) {`
- [ ] ./shared/file_op.c:2446: `while (dirent = readdir(dir), dirent) {`
- [ ] ./remoted/manager.c:651: `while (entry = readdir(dp), entry) {`
- [ ] ./remoted/manager.c:681: `while (entry = readdir(dp), entry) {`
- [ ] ./remoted/manager.c:723: `while (entry = readdir(dp), entry) {`
- [ ] ./remoted/manager.c:1263: `while (entry = readdir(dp), entry) {`

**Comment by chemamartinez** [comment]
Merged #4081
