### ISSUE TITLE
Pre-built packages for ppc64le architecture contribution

### ISSUE THREAD

**Issue by junawaneshivani** [wazuh/wazuh#3478]
Hi all, I have been able to build wazuh from source on ppc64le architecture. I would like to find out how can I contribute to make the .deb packages available for ppc64le architecture here https://packages.wazuh.com/ for direct installation. Any help would be highly appreciated.

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.8.2 | Wazuh component | Manager/Agent | Sources | Ubuntu 18.04 |

**Comment by vikman90** [comment]
Hi @junawaneshivani,

That's a great achievement! Thank you for offering this package to us.

I think the best way to accept contributions from you would be a pull request in the [Packages project](https://github.com/wazuh/wazuh-packages). That would let us compile, sign and release the package if it's OK for you.

Pinging @wazuh/cicd who will give you more detailed information about this.

Thank you again, we appreciate your initiative to contribute.
Best.

**Comment by junawaneshivani** [comment]
@vikman90 Thanks for your quick response. Will look into the  [ Packages project ](url) to try and undertand the build mechanism.

**Comment by vikman90** [comment]
@junawaneshivani That sounds great. Let me close this issue as it's related to the Packages project. Don't hesitate to reopen it to ask any other question, or create a new issue in _wazuh-packages_.

Thank you again.
Cheers.
