### ISSUE TITLE
failed to parse [predecoder] on wazuh-manager-3.0.0-2.x86_64

### ISSUE THREAD

**Issue by michaelhidalgo** [wazuh/wazuh#348]
Hi folks, I'm trying to index this document. I'm running wazuh-manager-3.0.0-2.x86_64

``
"{timestamp":"2018-01-09T17:52:29+0000",
"rule":{
"level":4,
"description":"OpenVPN: Connection Certificate Failed",
"id":"81803",
"firedtimes":17,
"mail":false,
"groups":[
"openvpn",
"openvpn-error"
]
},
"agent":{
"id":"000",
"name":"XYZ"
},
"manager":{
"name":"XYZ"
},
"id":"1515520349.150505",
"full_log":"Jan 9 17:52:28 XYZ openvpn: Tue Jan 9 17:52:28 2018 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)",
"predecoder":{
"program_name":"openvpn",
"hostname":"XYZ"
},
"decoder":{
"name":"openvpn"
},
"location":"/var/log/messages"
}
``

But i get this error when indexing 

**"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [predecoder]", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:15"}}}}}**

I checked the template and it seems like you guys are not using the predecoder https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/wazuh-elastic6-template-alerts.json

Can you please advice what might be wrong?

**Comment by michaelhidalgo** [comment]
Hi folks, any clues? I guess i can just modify the template to add support

Thanks.

**Comment by Zenidd** [comment]
Hello @michaelhidalgo,

First of all, sorry for the late reply. 

The "predecoder" field was added to the Elastic template in Wazuh 3.9.  

https://github.com/wazuh/wazuh/blob/8dfea182176937e90791339b163c641cad69476a/extensions/elasticsearch/6.x/wazuh-template.json#L296

The link to the template on your comment is no longer available. Anyway in that template did not exist the field "predecoder". 

- Do you still have the same situation? In that case, what version of Wazuh Manager, Elastic and Elastic template are you using?
- Do you have a custom decoder for the event shown in your example?
<br></br>
Best regards,

Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hello again @michaelhidalgo,

I'm closing this ticket due to inactivity. Do not hesitate to reopen this ticket or open a new one if you experience these problems again. You can also contact us through our Slack channel.

Best regards, JP Sáez
