### ISSUE TITLE
no agent's info in the mysql database

### ISSUE THREAD

**Issue by wttat** [wazuh/wazuh#3483]
I have configured the wazuh to database ouput. In the alters table I can find the alerts info inside while in the agent there is nothing but I can see my agents using the kibana app’s wazuh api.what should i do?

mysql> select * from agent;
Empty set (0.00 sec)

root@compute22:~# curl -u foo:bar -X GET "http://localhost:55000/agents?pretty&q=os.name=ubuntu;os.version>12&select=id,name,os.name,os.version,os.codename,os.major"
{
   "error": 0,
   "data": {
      "items": [
         {
            "os": {
               "codename": "Xenial Xerus",
               "major": "16",
               "name": "Ubuntu",
               "version": "16.04.5 LTS"
            },
            "id": "000",
            "name": "compute22"
         },
         {
            "os": {
               "codename": "Xenial Xerus",
               "major": "16",
               "name": "Ubuntu",
               "version": "16.04.5 LTS"
            },
            "id": "004",
            "name": "compute21"
         },
         {
            "os": {
               "codename": "Xenial Xerus",
               "major": "16",
               "name": "Ubuntu",
               "version": "16.04.5 LTS"
            },
            "id": "005",
            "name": "compute19"
         },
         {
            "os": {
               "codename": "Xenial Xerus",
               "major": "16",
               "name": "Ubuntu",
               "version": "16.04.5 LTS"
            },
            "id": "006",
            "name": "compute20"
         },
         {
            "os": {
               "codename": "Xenial Xerus",
               "major": "16",
               "name": "Ubuntu",
               "version": "16.04.5 LTS"
            },
            "id": "007",
            "name": "compute23"
         }
      ],
      "totalItems": 5
   }
}

**Comment by vikman90** [comment]
Hi @wttat,

Sorry for the late response in Slack. 

As I answered there, the database output integration (_os_db_) indexes the alerts produced (`logs/alerts/alerts.json`) to a MySQL database, while the agent data (`etc/client.keys`, `queue/agent-info`, `queue/agent-groups` and `queue/agents-timestamp`) is natively synchronized to an SQLite database (`var/db/global.db`). 

That's why we won't see the list of agents in the MySQL database. The recommended way to get the list of agents is using the API, just how you're doing.

Hope it helps.
Best regards.

**Comment by wttat** [comment]
> Hi @wttat,
> 
> Sorry for the late response in Slack.
> 
> As I answered there, the database output integration (_os_db_) indexes the alerts produced (`logs/alerts/alerts.json`) to a MySQL database, while the agent data (`etc/client.keys`, `queue/agent-info`, `queue/agent-groups` and `queue/agents-timestamp`) is natively synchronized to an SQLite database (`var/db/global.db`).
> 
> That's why we won't see the list of agents in the MySQL database. The recommended way to get the list of agents is using the API, just how you're doing.
> 
> Hope it helps.
> Best regards.

thanks , I found it in the folder.Hope oneday wazuh will place these things in one db.

best regards
