### ISSUE TITLE
Logcollector - Overwrite alias duplicated

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#3487]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.1 | Wazuh component | Manager | Sources |Linux mint 19 |
| 3.9.1 | Wazuh component | Agent | package |Ubuntu 18 |

Hello Team,

I have these two configurations:

In `agent.conf`:
```xml
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn4 | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
    <alias>netstat listening ports</alias>
    <frequency>43200</frequency>
  </localfile>
```
In agent's `ossec.conf`:
```xml
  <localfile>
    <log_format>full_command</log_format>
    <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
    <alias>netstat listening ports</alias>
    <frequency>360</frequency>
  </localfile>
```
It may be a good idea to have agent.conf's localfile overwrite ossec.conf's localfile.

This can be done by improve the `remove_duplicates` function. It can check that the alias is not duplicated.
I attach the function:
https://github.com/wazuh/wazuh/blob/787c56bd1ee56db4a701a9a685b4ce0a94560ed3/src/logcollector/logcollector.c#L1460

Regards, Eva

**Comment by vikman90** [comment]
This issue will be tackled during 5.0 development as part of state changes in the inventory module using the new analysis engine's ruleset.
