### ISSUE TITLE
Create an actual Makefile

### ISSUE THREAD

**Issue by nwmcsween** [wazuh/wazuh#349]
Using install.sh is sort of a mess.

**Comment by vikman90** [comment]
Hi @nwmcsween,

The install.sh script provides a wizard to select the installation mode and choose some options. This is not possible in a Makefile.

The installer has another advantage: you can build the code in one host and install it on other hosts without having to install `make`.

**Comment by nwmcsween** [comment]
an install script isnt a replacement for a proper build system

**Comment by vikman90** [comment]
Hi @nwmcsween,

As I told you, in my humble opinion the build system with the Makefile has been a proper way to reach some requirements, including:
- Multiplatform, including Linux, FreeBSD, OpenBSD, macOS, AIX, HP-UX, Solaris and Windows.
- Multiple modes: manager, agent, local and hybrid.
- Allow some settings at build time and installation time.
- Need only `bash` or the OS's native shell to install the system, do not depend even on `make`.

If you think that the installer is messy, we admit suggestions or some extra requirements you may have with it. On the other hand, we always appreciate contributions, please feel free to propose a change and make a pull request on this project.

Thank you.
Best regards.
