### ISSUE TITLE
Duplicate logs from eventchannel

### ISSUE THREAD

**Issue by qoole** [wazuh/wazuh#3491]
Wazuh Agent v3.8.2 running on WS2008R2

```
<localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907]</query>
  </localfile>

  <localfile>
    <location>System</location>
    <log_format>eventchannel</log_format>
  </localfile>
```

Whenever the agent restarts it appears to resend all log entries from the eventlog which causes any alert triggering events to re-trigger alerts.

for example take the following debug=2 line:

```2019/06/07 13:17:20 ossec-agent[6580] win_agent.c:495 at SendMSG(): DEBUG: Sending message to server: '{"Message":"A new process has been created.","Event":"<Event xmlns='http://schemas.microsoft.com/win/2004/08/events/event'><System><Provider Name='Microsoft-Windows-Security-Auditing' Guid='{54849625-5478-4994-A5BA-3E3B0328C30D}'/><EventID>4688</EventID><Version>1</Version><Level>0</Level><Task>13312</Task><Opcode>0</Opcode><Keywords>0x8020000000000000</Keywords><TimeCreated SystemTime='2019-04-09T07:01:37.306046200Z'/><EventRecordID>1261771</EventRecordID><Correlation/><Execution ProcessID='4' ThreadID='88'/><Channel>Security</Channel><Computer>COMPUTER_NAME</Computer><Security/></System><EventData><Data Name='SubjectUserSid'>S-1-5-18</Data><Data Name='SubjectUserName'>SERVERNAME$</Data><Data Name='SubjectDomainName'>DOMAIN</Data><Data Name='SubjectLogonId'>0x3e7</Data><Data Name='NewProcessId'>0x1244</Data><Data Name='NewProcessName'>C:\\Windows\\SysWOW64\\msiexec.exe</Data><Data Name='TokenElevationType'>%%1938</Data><Data Name='ProcessId'>0x13d4</Data><Data Name='CommandLine'></Data></EventData></Event>"}'```

You can see that the log line is dated 7th June 2019, yet the event is from 9th April 2019....

Is this normal behaviour?

**Comment by albertomn86** [comment]
Hi @qoole,

there's an issue already reported that explains this behavior https://github.com/wazuh/wazuh/issues/3475

In Wazuh version 3.8.0 the bookmark which manages the reported events from the Eventchannel is not set correctly. For this reason the bookmark is not updated and always the same events are sent.

You can remove the older bookmark set by the previous Wazuh installation deleting the files in `C:\Program Files (x86)\ossec-agent\bookmarks` to prevent receiving duplicate events.

This fix will be merged in a next release.

Best regards.

**Comment by cristgl** [comment]
Hi,

We are closing this issue as it was fixed in this PR https://github.com/wazuh/wazuh/pull/3485.
Do not hesitate to ask again if you have any questions.

Kind regards,
Cristina
