### ISSUE TITLE
Framework wrongly detects daemon as down 

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#3492]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.1-3921 | Framework/DB | Manager| Packages | Amazon Linux 2 |

Hello team, 

We have noticed that something wrong just happened to the Wazuh API: suddenly, the `Inventory` section of the app stopped working. After digging into it, I discovered that the API was recognizing the Wazuh status as `down` when requested certain endpoints, the ones related to `/syscheck`, `/rootcheck` and `/syscollector`.

For example, this is the result of the `/manager/status` request:
```
{
   "error": 0,
   "data": {
      "ossec-agentlessd": "stopped",
      "ossec-analysisd": "running",
      "ossec-authd": "running",
      "ossec-csyslogd": "stopped",
      "ossec-dbd": "stopped",
      "ossec-monitord": "running",
      "ossec-execd": "running",
      "ossec-integratord": "running",
      "ossec-logcollector": "running",
      "ossec-maild": "stopped",
      "ossec-remoted": "running",
      "ossec-reportd": "stopped",
      "ossec-syscheckd": "running",
      "wazuh-clusterd": "running",
      "wazuh-modulesd": "running",
      "wazuh-db": "running"
   }
}
```
Everything looks correct there.However, this is the result of the `/syscollector/003/packages`:
```
{
   "error": 1018,
   "message": "Wazuh is stopped. Start Wazuh before using the API."
}
```
This behavior also applies to the rest of the requests mentioned above. I set the API to `debug` mode and I noticed this trace:

```
WazuhAPI 2019-06-07 23:15:04 admin: Wazuh is stopped. Start Wazuh before using the API.: ('stopped', 'running', 'running', 'running', 'running')
WazuhAPI 2019-06-07 23:15:04 admin: [::ffff:10.0.0.92] GET /syscheck/006/last_scan? - 200 - error: '1018'.
WazuhAPI 2019-06-07 23:15:05 admin: ::ffff:10.0.0.92 GET /manager/status
```
So I jumped into the code and saw this method, which looks to be in charge of determining the status of the daemons:
 https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/framework/wazuh/cluster/dapi/dapi.py#L109-L113

So it seems that `modulesd` is not able to be seen as started. Every daemon looks alright, alsoI wanted to check with `ossec-control status`, `systemctl status wazuh-manager` and with `ps aux` in order to guarantee the daemon status. Every daemon was running.

Regards

**Comment by crd1985** [comment]
Hi @manuasir ,

I think the problem is caused because you are running a Wazuh cluster and the daemon is down in a worker node. 

The problem here is a poor error message. We have improved it to show the name of the daemons in issue https://github.com/wazuh/wazuh/issues/3346.

However, we have an additional problem to fix in a cluster environment to show the name of the node where the daemon is down.
