### ISSUE TITLE
Fix path issues with Wazuh API

### ISSUE THREAD

**Issue by JmZero** [wazuh/wazuh#3495]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Framework | Any | Any | Any |

Hi team, 

Currently, the API makes use of a default ossec path on which the Wazuh installation will be carried out. Some problems that may appear are the following:
- The default installation is in `/var/ossec`, if we use other path can be problems in the installation process.
- If the directory changes, the API will continue reading the values of the file `/etc/ossec-init.conf`, which will be outdated.

As we see, the main problem is the use of a file from which we get the values of the path, when it should be obtained dynamically when running the API.

To do this we will have to modify the following code:

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/framework/wazuh/__init__.py#L80-L101

At the same time, we should also avoid having a function to edit global variables.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/framework/wazuh/common.py#L10

We want to avoid using `/etc/ossec-init.conf` so the following line is not necessary:

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/framework/wazuh/__init__.py#L42

Deleting the previous file has some problems because we can't get information about the date, type of installation or revision.

To avoid these problems @crd1985  has suggested adding these variables to the python package during the installation process. In this way these variables would be found in the file `setup.py`.

Best regards,
Jesús Jaldo.

**Comment by crd1985** [comment]
# Status update
## Summary
The main goal of this development is breaking all dependencies with `ossec-init.conf` file. This will have some advantages:
- Fix errors on custom path installations
- Reduce and improve `Wazuh` code, and consequently, improve framework overall stability.
- Be more precise with `basic_services` according to installation type. For instance, `remoted` is not required in a local installation.

## Tasks
* Modify setup.py to include custom parameters and save them in a file inside package installation. These parameters are wazuh-version, wazuh-path and installation-type.
* Refactor `common.py` module
* Refactor `__init__.py` module and `Wazuh` class

## Stoppers
There are no stoppers

## Difficulties
* Complexity in Makefile and install functions
* Lack of good documentation for setuptools

## Tests performed
That is the next step

## Pending
* Refactor `Wazuh` class use in all framework and scripts
* Testing (installing via sources and packages, on docker, centos and debian distributions)

**Comment by crd1985** [comment]
# Status update
## Summary
Now I have a candidate development. Now I can get `ossec_path` without reading `ossec-init.conf` file. Furthermore, I did some refactoring to delete unnecessary `Wazuh` calls. This has simplified the code a bit.

Everything looks fine, but I need to solve a problem with one unit test. See `Tests performed` section for details.

## Tasks
* Delete `Wazuh` calls
* Correct some mistakes in Makefile's and check metadata are recorded in `wazuh.json` file
* Do some manual tests to check it is working
* Run unit tests

## Stoppers
There are no stoppers

## Difficulties
* Complexity in Makefile and install functions

## Tests performed
All unit tests are passing except one of them:
```
rootdir: /var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh
collected 290 items                                                                                                  

var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/cluster/tests/test_cluster.py . [  0%]
.................                                                                                              [  6%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/cluster/tests/test_local_client.py . [  6%]
                                                                                                               [  6%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/cluster/tests/test_worker.py . [  6%]
..........                                                                                                     [ 10%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_active_response.py . [ 10%]
.....                                                                                                          [ 12%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_agent.py ...... [ 14%]
.............................................                                                                  [ 30%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_cdb_list.py ... [ 31%]
........                                                                                                       [ 33%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_decoders.py ... [ 34%]
.....................................                                                                          [ 47%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_group.py ...... [ 49%]
..                                                                                                             [ 50%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_manager.py .... [ 51%]
.........................                                                                                      [ 60%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_rules.py ...... [ 62%]
...............................................................                                                [ 84%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_security_configuration_assessment.py . [ 84%]
....                                                                                                           [ 85%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_syscheck.py .F. [ 86%]
...                                                                                                            [ 87%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_util.py ....... [ 90%]
.....................                                                                                          [ 97%]
var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_wdb.py .......  [100%]

====================================================== FAILURES ======================================================
____________________________________________ test_last_scan[002-version1] ____________________________________________

db_mock = <MagicMock name='connect' id='139623144889256'>, version = {'version': 'Wazuh v3.6.2'}, agent_id = '002'

    @pytest.mark.parametrize('agent_id, version', [
        ('001', {'version': 'Wazuh v3.5.0'}),
        ('002', {'version': 'Wazuh v3.6.2'}),
        ('003', {'version': 'Wazuh v3.7.1'}),
        ('004', {'version': 'Wazuh v3.8.2'}),
        ('005', {'version': 'Wazuh v3.9.1'}),
        ('006', {'version': 'Wazuh v3.10.0'})
    ])
    @patch('sqlite3.connect', side_effect=get_fake_syscheck_db('schema_syscheck_test.sql'))
    def test_last_scan(db_mock, version, agent_id):
        """
        Test last_scan function
        """
        with patch('wazuh.syscheck.Agent.get_basic_information', return_value=version):
>           result = last_scan(agent_id)

var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/tests/test_syscheck.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

agent_id = '002'

    def last_scan(agent_id):
        """
        Gets the last scan of the agent.
    
        :param agent_id: Agent ID.
        :return: Dictionary: end, start.
        """
        my_agent = Agent(agent_id)
        # if agent status is never connected, a KeyError happens
        try:
            agent_version = my_agent.get_basic_information(select={'fields': ['version']})['version']
        except KeyError:
            # if the agent is never connected, it won't have either version (key error) or last scan information.
            return {'start': 'ND', 'end': 'ND'}
    
        if WazuhVersion(agent_version) < WazuhVersion('Wazuh v3.7.0'):
            db_agent = glob('{0}/{1}-*.db'.format(common.database_path_agents, agent_id))
            if not db_agent:
>               raise WazuhException(1600)
E               wazuh.exception.WazuhException: Error 1600 - There is no database for selected agent

var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.10.0-py3.7.egg/wazuh/syscheck.py:99: WazuhException
======================================== 1 failed, 289 passed in 1.11 seconds ========================================
```
The call to `glob` function should be mocked to get fake data...

## Pending
* Testing (installing via sources and packages, on docker, centos and debian distributions)

**Comment by crd1985** [comment]
# Status update
## Summary
I have done some testing from sources first in order to check all possible services. Several issues have been detected and fixed. In relation to wazuh-api, the issue https://github.com/wazuh/wazuh-api/issues/406 have been created.

Finally, I have changed the approach to calculate the installation path dynamically instead of getting the PREFIX variable from Makefile. This will avoid problems when moving the folder after installation.

## Tasks
* Check clusterd is working
* Check API is working

## Stoppers
There are no stoppers

## Difficulties
* Complexity in Makefile and install functions

## Tests performed
Manual testing after installation with sources

## Pending
* Testing (installing via packages, on docker, centos and debian distributions)
