### ISSUE TITLE
Change new API's nested fields structure

### ISSUE THREAD

**Issue by JmZero** [wazuh/wazuh#3503]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Wazuh API | Any | Any | Any |

Hi team, 

Some API calls return a response that has nested fields. Currently we don't have a standard way to identify those fields, although most of them are defined using the `_` character as a separator between the different levels of the fields. Example: `tx_packets`, `tx_bytes`, etc.

This can cause errors because the character '_' is also used as a separator between different words such as `agent_id`.

It's necessary for the new API to unify a way to identify the different levels of the nested fields. A more correct way would be to use the character `.` as a separator between levels of the nested field.

Best regards,
Jesús Jaldo.

**Comment by JmZero** [comment]
# Status update
## Summary
After reviewing all endpoints only in four types of calls nested fields are used for the param sort and select:
- Agents:
    - /agents
    - /agents/:agent_id
    - /agents/name/:agent_name
    - /agents/groups/:group_id
    - agents/stats/distinct
- Ciscat:
    - /ciscat/:agent_id/results
- Syscollector:
    - /syscollector/:agent_id/hardware
    - /syscollector/:agent_id/netiface
    - /syscollector/:agent_id/os
    - /syscollector/:agent_id/packages
    - /syscollector/:agent_id/ports
    - /syscollector/:agent_id/processes
- Experimental:
    - /experimental/ciscat/results
    - /experimental/syscollector/hardware
    - /experimental/syscollector/netiface
    - /experimental/syscollector/os
    - /experimental/syscollector/packages
    - /experimental/syscollector/ports
    - /experimental/syscollector/processes

After debugging, I have checked that in agent calls uses the keys of the database to make sort and select. In ciscat and syscollector there are defined set objects that contain the values by which you can select and sort.

The keys returned by the database, in the case of agent, those that refer to a nested field are returned using `.` character as separator between levels, on the other hand, in ciscat and syscollector use  `_` character as separator.

## Tasks
* [2.5 h] Endpoint review
* [1.5 h] Endpoint debug

## Pending
* Change DB response to represent the nested fields with the same structure
* Change set object to use the `.` character instead of `_` for nested fields

**Comment by davidjiglesias** [comment]
Hello team,

I have completed the adaptation from `_` to `.` for nested fields when using the new API filters and parameters. It has required changes in the `spec.yaml` for parameter names and descriptions. I have also made changes in API controllers and framework for `agents`, `ciscat` and `syscollector`.

Updated API integration tests results:
