### ISSUE TITLE
Add integration with Azure Office 365 API

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh#3508]
Hello team,

It is necessary to add integration with the API of Azure Office 365.

https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/

We already have enough users from the community asking for it and we need to implement such integration to increase the possibilities of Wazuh. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by havidarou** [comment]
Duplicated https://github.com/wazuh/wazuh/issues/4983
