### ISSUE TITLE
Add Catchall rule - Forward alert level 0

### ISSUE THREAD

**Issue by plopmate** [wazuh/wazuh#3516]
Hi team, 

I’m currently using the Wazuh agent to forward logs to the manager. 

However, some agents forward too much logs to the manager and thus to ELK and I would like to filter out some noise directly on the agent side and/or the manager. 

As of today, I’m forwarding all the logs from archives.json (using the logall option) as I need history in case of incident. 

Based on that, I have multiple issues/questions:

1) What is the current best way to filter out noise coming from endpoint when using Wazuh Agent? 
          - It seems we cannot filter on the agent itself, but how to do so on the manager when using archives.json? Are there better solution than using Filebeat or Logstash for this purpose?

2) Using the logall option doesn't allow me to do any filtering (using rules) on the manager. Thus I wanted to create a catchall rule. However, we cannot send alerts level "0" but only from "1" to "16" ... :(. Why is that? Is there a way to bypass that?

3) I tried to modify any rules with level of 0 to set them to 1 in order for them to be forwarded to the alerts.json file. But of course, it creates many issues afterward because of that (order of the rules, etc etc ...). What would then be the best way to do?

4) Another downside of using the logall option  is that it costs so much money/storage for nothing. Indeed, if we want to populate the logs in rules (rule groups, info, level, severity, etc...) to have better control over the logs, then we start getting so much duplicate between the alerts.json and archives.json! How do you guys deal with that?

I would be very glad to have your view on how you guys are forwarding all your logs as well as being able to filter noise out, categorize logs, etc..

I imagine that the best way would be to allow to forward level 0 events to alerts.json.

Thank you :)
Alex

**Comment by cristgl** [comment]
Hi @plopmate,

This issue has been already answered at our [Wazuh mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/R7BDnfBqkvc/AsifrdlLAAAJ).
I am closing this issue as we will continue working in the mentioned link. If you have any other doubts, do not hesitate to open another issue or ask your question at our mailing list or community channel in Slack.

Kind regards,
Cristina
