### ISSUE TITLE
Authd will force agent overwrite when 'force' is -1

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#3526]
|Working branch|
|---------|
|[fix-authd-duplicated-id-3526](https://github.com/wazuh/wazuh/tree/fix-authd-duplicated-id-3526) |

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Wazuh component | Manager | Sources | Ubuntu 16.04 |

Bug description
-----------------

If the API makes a call like the following (having an agent already registered with the same ID as indicated):
```
curl -u foo:bar -k -X POST -d curl -u foo:bar -k -X POST -d '{"name":"NewHost_4","ip":"10.0.10.16","id":"126","key":"1abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza2cdefghi64"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents/insert?pretty"
```
The `authd` process will overwrite the previous agent.

This is related to https://github.com/wazuh/wazuh/issues/3431

Solution
---------

If no `force` parameter is indicated in the API call, its value is `-1` by default.
This is what happens when `force` has that value:

https://github.com/wazuh/wazuh/blob/53b751e5dce09daed54bfb42c34b9acb70b0b6a0/src/os_auth/local-server.c#L286

We should check if `force` is `>=0` instead, as a negative value means that agent overwriting is not wanted when the ID is the same.

**Comment by druizz90** [comment]
Hi team,

Issue #3431 is solved with this PR. `force` parameter works as expected:

```
# curl -u foo:bar -k -X POST -d '{"name":"NewHost_4","ip":"10.0.10.14","id":"010","key":"1abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi64", "force": "0"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents/insert?pretty"
{
   "error": 0,
   "data": {
      "id": "010",
      "key": "MDEwIE5ld0hvc3RfNCAxMC4wLjEwLjE0IDFhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5emFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6YWJjZGVmZ2hpNjQ="
   }
}
# curl -u foo:bar -k -X POST -d '{"name":"NewHost_4","ip":"10.0.10.14","id":"010","key":"1abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi64", "force": "0"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents/insert?pretty"
{
   "error": 0,
   "data": {
      "id": "010",
      "key": "MDEwIE5ld0hvc3RfNCAxMC4wLjEwLjE0IDFhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5emFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6YWJjZGVmZ2hpNjQ="
   }
}
```

It is not possible to add an agent if `id` is already exists and `force` parameter is not set:

```bash
# curl -u foo:bar -k -X POST -d '{"name":"NewHost_4","ip":"10.0.10.14","id":"010","key":"1abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi64"}' -H 'Content-Type:application/json' "http://127.0.0.1:55000/agents/insert?pretty"
{
   "error": 9012,
   "message": "Duplicated ID"
}

```

Best regards,

Demetrio.

**Comment by JcabreraC** [comment]
This issue won't be solved: We shouldn't reuse IDs as they are unique identifiers and can't be overwritten. To reuse an ID, it must be deleted first.

**Comment by chemamartinez** [comment]
Merged https://github.com/wazuh/wazuh/pull/3527
