### ISSUE TITLE
wazuh-db *.db-wal files in /var/ossec/queue/db grow to huge size and never shrink [bug_report]

### ISSUE THREAD

**Issue by selivan** [wazuh/wazuh#3535]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.8.2-1 | wazuh-db | Manager | Packages | Ubuntu 18.04 Bionic |

On my small installation with just 24 agents and 1 wazuh-manager the directory `/var/ossec/queue/db` was 7.8 Gb after a month. All the space was taken by `*.db-wal` files.

After restarting wazuh-manager these files were re-created and directory size shrunk back to 53 Mb.

Those are sqlite write-aherad log files([sqlite documentation](https://sqlite.org/wal.html)) and they should not be growing without limit. They can be truncated manually by calling appropriate sqlite functions or automatically on commit(controlled by `PRAGMA wal_autocheckpoint` directive).

**Comment by Zenidd** [comment]
Hi @selivan,

As you said, *.db-wal are write-ahead-logging files, that store temp information until a commit occurs. The Wazuh DB commits every time a minute goes by without accessing a BD. In your case the large file size can be a sign of an intensive use being made on your database so there is no opportunity to commit. 

On the other hand, to optimize the Wazuh DB and reduce its size you can use the further line that contains the command [VACUUM](https://www.sqlite.org/lang_vacuum.html)(Please be sure that you have stopped the manager before doing this):
```
# find /var/ossec/queue/db -name "*.db" | while read i; do sqlite3 $i "VACUUM;"; done
```

If you think that this is not your case and that with little use of the BD the size of the .db-wal files does not decrease, please let us know and we will look for a solution.

Greetings,

Juan Pablo Sáez

**Comment by selivan** [comment]
@Zenidd just restarting wazuh-manager helps, it seems to perform vacuum when it is terminating. Additional manual vacuum is not required.

But it is still an issue: wazuh-manager can not be running for a long time without restarts. Seems that for whatever reason it fails to run vacuum even a single time until termination, files are constantly growing. Server is not under a heavy load, other services on it(elastic, logstash) work fine. And even if agent is not available for some time it's *.db file doesn't shrink.

Soon we will be upgrading to wazuh 2.9 and I will see if the bug remains.

**Comment by Zenidd** [comment]
Hi again @selivan,

This is the normal workflow of Wazuh DB:

- Wazuh DB starts, agents connect and start sending events, which are saved in the DB
- In order not to impact the performance (EPS), Wazuh DB does not commit (save in the `.db`) until one minute passes without arriving queries for an agent, or until we have more than 64 DBs open simultaneously.
- Could you check if these commits occur? To do this, you can activate Wazuh DB debug mode in the file `/var/ossec/etc/internal_options.conf` 
        ```
        # Wazuh DB debug level 
        wazuh_db.debug=2
        ``` 
    You should be able now to see if DB is performing commits by looking on `ossec.conf` for the further message:
    ```
    2019/07/16 10:52:30 wazuh-db[6971] wdb.c:656 at wdb_commit_old(): DEBUG: Committing database for agent <agentID>
    ```

If you are going to upgrade soon to a higher version of Wazuh we can continue working once you have done the upgrade.

Thank you very much for reporting your problem, do not hesitate to communicate any update on this or other issues. I will keep an eye on this issue !

Best regards,

Juan Pablo Sáez

**Comment by selivan** [comment]
Hi @Zenidd 

I enabled  `wazuh_db.debug=2` in `internal_options.conf`, restart wazuh-manager, and suddenly the bug is gone. Log contains "Committing database" messages, db files are small and nice.

It might have been gone for some time, because I restart wazuh-manager with a cronjob as a workaround for this issue, and it might have been working fine for some time already.

No idea why it wasn't working correct at first.

I think you can close this issue as "can't reproduce".

**Comment by Zenidd** [comment]
Hi again @selivan,

I'm glad the bug's gone. I take note of your cronjob workaround as it may be useful to other users in the community.

I'm closing this ticket. If this Wazuh DB behavior occurs again, please, let us know so that we can investigate it in depth. 

Kind regards, Juan Pablo Sáez

**Comment by 700grm** [comment]
Hi @selivan and @Zenidd, 
I got exactly the same issue as described by @selivan only in the latest version, two weeks after I did an upgrade:
VERSION="v3.10.2"
REVISION="31014"

I did upgrade from version v3.6.1 to v3.10.2. However before update I removed wazuh-manager and  removed /var/ossec directory. The only element that was used from Wazuh v3.6.1 was ossec.conf file.

We have very tiny environment, less than 10 servers.

Any solution how to fix it.

**Comment by selivan** [comment]
@700grm May be check difference between your v3.6.1 and default v3.10.2 configs? That may show where the problem is.

I could not find any permanent fix except restarting wazuh-manager periodically.

**Comment by Andy13000ft** [comment]
Hello everyone,

Thanks for the information in this thread so far. I am working with Wazuh 3.10.2 and also have the problem of the WAL files from each of my agents growing uncontrollably. So far I have put the manager into debug mode and I can see the agents being committed, but the WAL file corresponding to that agent does not shrink in size. Many of my WAL files are above 4MB in size which I understood was the threshold for the file to be shrunk during a commit. I am also happy that there is not constant communication between the agent and the manager by observing the alerts log. Again there is a period of greater than 60 seconds when some of the agents, with large WAL files do not communicate, another trigger I understood to cause the files to shrink. However their files only shrink (back to zero) if the manager is restarted. Unfortunately we don't want to keep doing this as we lose alerts from agentless clients, i.e. routers etc.  This lack of file shrinking seems to be a bug....any thoughts ?

**Comment by Theoooooo** [comment]
Hey,
I also got this issue with my Wazuh Cluster on v3.10.2 fresh install.
Every db files are getting bigger and bigger and it has completly filled my partition to the point of not being able to log any informations to the partition.

Restarting the manager cleaned up the .db files and now i got plenty of space in my partition.
For a work around, just create a new Crontab task that run every week and restart your manager. But please we really need to fix this issue.

**Comment by sturem** [comment]
> For a work around, just create a new Crontab task
> that run every week and restart your manager.
> But please we really need to fix this issue.

@Theoooooo @selivan @700grm @Andy13000ft :
It's probably better to open a new issue if this is still a problem for you (and mention this issue); this one was closed several months ago, so updates to it may not be noticed...
