### ISSUE TITLE
Apply the Active-Response to an specific group

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3540]
Currently, there is no way to activate an Active-Response block for a specific group. It is possible to execute the response on a specific agent (`<location>defined-agent</location>`), but this will be done regardless of who generates the alert.

It would be nice to implement an option that launches the active response only if an agent or group has generated it.

A use case for this feature can be found in [this thread](https://groups.google.com/forum/#!topic/wazuh/2xt5iA4y23s).

**Comment by snaow** [comment]
Related: https://github.com/wazuh/wazuh/issues/2084
Closing.
