### ISSUE TITLE
Logcollector does not ignore existing lines of files when restarting

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3546]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Logcollector | Agent | Packages | Windows Server 2016 |

Logcollector should only send the lines that appear after the agent starts. However, you are sending the complete content of the files with each restart.

## How to replicate the issue

1) With the Windows agent stopped, configure a localfile block as follow:

``` XML
  <localfile>
    <location>C:\Users\Administrator\Desktop\test\*</location>
    <log_format>syslog</log_format>
     <ignore_binaries>yes</ignore_binaries>
  </localfile>
```

2) Create several files with content in that folder.
3) Enable the `archieves.log` (`<logall>yes</logall>`) in the manager and restart it.
4) Start the agent. You should see the content of the files in this log with each restart.

**Comment by crolopez** [comment]
The reason for the bug is an invalid condition when calling to `_ftelli64` in `w_ftell`.

https://github.com/wazuh/wazuh/blob/421c4fd9b5c142936b3f1922587c355076ae4e03/src/logcollector/read_syslog.c#L38

There seems to be a bug in this function for some MinGW implementations that leads to not returning the pointer position in the file by setting `errno` to 0. This happens randomly.

We could think that it is a race condition between the threads of Logcollector, but [this function is thread-safe](https://docs.microsoft.com/es-es/cpp/c-runtime-library/reference/ftell-ftelli64?view=vs-2019).

I can easily reproduce it with MinGW **7.3-win32 20180506**.

**Comment by chemamartinez** [comment]
Let's continue the tracking of this issue at #4030
