### ISSUE TITLE
Wazuh on The Changelog?!

### ISSUE THREAD

**Issue by jerodsanto** [wazuh/wazuh#3547]
Howdy from [The Changelog](https://changelog.com/podcast)!

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

[One of our listeners pointed us your way](https://github.com/thechangelog/ping/issues/792). We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Wazuh and all the cool stuff y'all are up to?

Please email jerod@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by JcabreraC** [comment]
Hi @jerodsanto!

I'm really sorry for the late reply! We really appreciate giving us this opportunity! It would be great to speak on your show and let people know about Wazuh.

We will contact you shortly to coordinate this.

Thanks again for contacting and considering us.
