### ISSUE TITLE
Vulnerability Detector can ignore some packages if a Syscollector scan is in progress

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3553]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.2 | Modulesd | Manager | Packages and sources | Ubuntu 18.04 |

The expected behaviour for a Vulnerability Detector scan is the following:

- **If it is the first scan** after a manager starts, Vulnerability Detector must request all the agent's packages, analyze them, and report its vulnerabilities if found.
- **If it is not the first scan**, only the new packages (updated or not), which was not marked with `triaged=1` in a previous scan, will be analyzed. If the `<ignore_time>` interval has been reached, all packages will be analyzed independently of `triaged` value.

## Request packages about an in-process scan

Vulnerability Detector requests the agent packages to WazuhDB. If the scan is in progress, WazuhDB will send only the available packages.

The logic behaviour is that the excluded packages will be processed in the next scan, even if `<ignore_time>` has not been reached. It will not work that way since packages with that scan ID are marked as reported (`triaged`). For this reason, there is a possibility that part of an agent's packages will not be reported if Vulnerability Detector requests them while there are being scanned.

## How to reproduce

To reproduce it easily, configure Vulnerability Detector for a manager with a large number of packages installed. Clean installations of an operating system will produce fast scans, so there will be no overlap with requests.

1) Configure a Vulnerability Detector feed that matches the manager OS with an offline update. Wait for the feed to update and stop the manager.
2) Activate program scanning for Syscollector.
3) Disable the feed previously configured. The vulnerabilities are indexed, so the package scan will run directly.
4) Enable level 2 debug in modulesd.
5) Restart the manager.
6) You should not see the debug messages indicating the processing of vulnerabilities for the last packages of the next query:

``` BASH
sqlite3 /var/ossec/queue/db/000.db "SELECT DISTINCT NAME, VERSION, ARCHITECTURE FROM SYS_PROGRAMS WHERE SCAN_ID = 'LAST_SCAN_ID';"
```

## Impact

The possibilities for this race condition increase if the environment has one or a few feeds configured with offline update. This causes the scan to start earlier and may overlap with the Syscollector scan of the manager. Vulnerability Detector and Syscollector start at the same time if `scan_on_start = yes`.

It is more complicated than this condition appears with the scanning of the agents, since the beginning of the scanning of the agent has to coincide with the request of Vulnerability Detector to WazuhDB, but it is possible.

We need to design an effective sync solution for this use case.

**Comment by crolopez** [comment]
In order to difficulty the race condition, since 3.11 the manager packages are the last to be requested.

**Comment by pereyra-m** [comment]
The epics #7749 and #8727 solve this synchronization issue by making the vulnerability detector query's atomic.

**Comment by pereyra-m** [comment]
### Validation

The epics https://github.com/wazuh/wazuh/issues/7749 and https://github.com/wazuh/wazuh/issues/8727 were included in the `master` branch, and they include a fix for this issue: if the packages synchronization is still in progress, the agent's vulnerability scan is delayed.

Some tests were run to confirm this feature, with both legacy and current **syscollector** scan mechanism. 
The agent's `sync_info` table was modified to simulate a lack of synchronization with the manager. It is interesting to consider that the integration tests **test_vulnerability_detector/test_general_settings/test_general_settings_retry_interval.py** already verifies this.

#### Legacy synchronization mechanism 

**Manager**: Ubuntu 20.04, Wazuh v4.3.0
**Agent**: Ubuntu 20.10, Wazuh v4.1.5

![4 1 5_not_ready](https://user-images.githubusercontent.com/65046601/141808089-91bab90c-3731-40af-92d8-0d1669c419f8.png)

#### Current synchronization mechanism 

**Manager**: Ubuntu 20.04, Wazuh v4.3.0
**Agent**: Ubuntu 20.10, Wazuh v4.2.4

![4 2 4_not_ready](https://user-images.githubusercontent.com/65046601/141808104-3ea8353b-2585-49e4-b8d6-02399ad2d08c.png)
