### ISSUE TITLE
Custom decoder issue with syslogs

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#356]
Custom decoders do not work as expected.

Take for example the following custom decoder:
```xml
<decoder name="test-decoder">
  <prematch>test message</prematch>
  <regex>test message by (\S+)</regex>
  <order>user</order>
</decoder>
```
and the following syslog messages:
```bash
# echo 'Jan 01 00:11:22 HOSTNAME app[12]: test message by user1' | /var/ossec/bin/ossec-logtest
**Phase 1: Completed pre-decoding.
       full event: 'Jan 01 00:11:22 HOSTNAME app[12]: test message by user1'
       hostname: 'HOSTNAME'
       program_name: 'app'
       log: 'test message by user1'

**Phase 2: Completed decoding.
       No decoder matched.
# echo 'Jan 01 00:11:22 HOSTNAME app[FF]: test message by user1' | /var/ossec/bin/ossec-logtest
**Phase 1: Completed pre-decoding.
       full event: 'Jan 01 00:11:22 HOSTNAME app[FF]: test message by user1'
       hostname: 'HOSTNAME'
       program_name: '(null)'
       log: 'app[FF]: test message by user1'

**Phase 2: Completed decoding.
       decoder: 'test-decoder'
       dstuser: 'user1'
```
Notice how the message where `program_name` is successfully decoded does not match our decoder. While in the second example, where `program_name` was not decoded will match our decoder.

A quick look at the source code reveals that there are 2 decoder lists. One with decoders that have `<program_name>` and one for decoders that don't.

https://github.com/wazuh/wazuh/blob/9d007250c109eb8f1354c8f8613f40aabb44160a/src/analysisd/decoders/decoders_list.c#L36-L45

As far as I can tell this behaviour is not documented anywhere. It is unintuitive and can cause events to be missed when writing custom decoders. There doesn't seem to be a way to handle both cases without making 2 or more decoders.

**Comment by vikman90** [comment]
Hi @rossengeorgiev,

Sorry for the late response.

You are right, decoders for events that specify the program name must match that field no matter the decoder has a prematch.

This feature was introduced 11 years ago (https://github.com/wazuh/wazuh/commit/02327b512e48df3c76623e65b00bdff063a18247#diff-524f3cb8717be5751bef6e816ccfe6e0R23). As it's written in the comment, it was made for performance reasons.

Rolling back this commit would affect the semantics of the current decoders: they may match logs that shouldn't be decoded by these decoders. I think it's better to keep this feature.

However, as you well say, the documentation should make this point clear. We will clarify it in the decoder reference.

Thank you for your detailed description and your feedback!

Best regards.

**Comment by rossengeorgiev** [comment]
Hi @vikman90, I'm not suggesting to revert it. However, I'm very sceptical of the performance gains. The commit doesn't mention any metrics or tests that were performed, or on what hardware. I guess it cuts down some matching and at the same time requires that multiple decoders need to be created. I've written a couple of custom decoders that end up having duplicate decoders one for with `program_name` and one without. Even child decoders need to be duplicated too.

I think a good first step would be to document the behaviour.

If I am not mistaken the matching in done in a single thread. Having multiple threads should make performance a non issue and allow for this code to be removed.

**Comment by vikman90** [comment]
Hi @rossengeorgiev.

It's a good point. We will document this behavior in the decoder reference.

On the other hand, I agree with you: the computing performance has improved so much in the last 11 years, some things that were a problem before may not be now. Implementing multithread issuing (Remoted) and analysis (Analysisd) is on our roadmap so we will take this in mind.

Will leave this issue open until we implement multithreading or we decide that we shouldn't change this behavior. Rule tests will help here a lot.

Thank you for your valuable opinion.
Best regards.

**Comment by rossengeorgiev** [comment]
Looks like this issue can be worked around by making 2 parent decoders with the same name, one for events with program_name and one without. Then making the decoder a child of those.

```xml
<decoder name="test-parent">
  <prematch>test message</prematch>
</decoder>

<decoder name="test-parent">
  <program_name />
  <prematch>test message</prematch>
</decoder>

<decoder name="test-decoder">
  <parent>test-parent</parent>
  <regex>test message by (\S+)</regex>
  <order>user</order>
</decoder>
```

```bash
# echo 'Jan 01 00:11:22 HOSTNAME app[FF]: test message by user1' | /var/ossec/bin/ossec-logtest
2019/02/12 15:39:01 ossec-testrule: INFO: Started (pid: 19723).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: 'Jan 01 00:11:22 HOSTNAME app[FF]: test message by user1'
       timestamp: 'Jan 01 00:11:22'
       hostname: 'HOSTNAME'
       program_name: '(null)'
       log: 'app[FF]: test message by user1'

**Phase 2: Completed decoding.
       decoder: 'test-parent'
       dstuser: 'user1'
# echo 'Jan 01 00:11:22 HOSTNAME app[12]: test message by user1' | /var/ossec/bin/ossec-logtest
2019/02/12 15:39:05 ossec-testrule: INFO: Started (pid: 19725).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: 'Jan 01 00:11:22 HOSTNAME app[12]: test message by user1'
       timestamp: 'Jan 01 00:11:22'
       hostname: 'HOSTNAME'
       program_name: 'app'
       log: 'test message by user1'

**Phase 2: Completed decoding.
       decoder: 'test-parent'
       dstuser: 'user1'
```

**Comment by coopjab** [comment]
is this stilled opened???

**Comment by msbayoub** [comment]
i faced this same issue with the 4.11.1 version , i was able to apply the work around solution.but any fixes/patches for this ?
