### ISSUE TITLE
Update version of Azure Active Directory Graph API to Microsoft Graph API

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh#3562]
Hello team,

Since February of this year, the Azure Active Directory Graph API is deprecated. 

https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api

We must update to Microsoft Graph API

https://docs.microsoft.com/en-us/graph/use-the-api

Best regards,

Alfonso Ruiz-Bravo

**Comment by SitoRBJ** [comment]
Hello team,

This issue refers to this other issue #2720.

We may consider closing one of the two issues, but it reflects the growing need to update the integration. 

Regards,

Alfonso Ruiz-Bravo

**Comment by davidjiglesias** [comment]
We will continue along #2720.
