### ISSUE TITLE
Request- Automatic agent rename

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#3571]
Hello Wazuh team!

I recently discovered many of my agents are not the computers they claim to be! 
It seems some people in my organization change their computer's name even though we have a very clear name convention, which results in agents having old names that do not correspond to the computer they are installed on.
Furthermore, new computers in the organization get the names that were replaced before, so the agents register with a name that already exists and gets "2" added to their agent name, which of course is not an actual computer name in my organization.

Right now I need to manually change agent names on both the manager and agents which for me is not ideal.

My suggestion is that Wazuh will change the agent name when the computer name is changed. Wazuh will also identify which agent registered with the default name (computer name) so it wont overwrite agent names that were given specific names when registered.

Thanks for considering my idea.
Appreciate you work.

**Comment by Lopuiz** [comment]
Hello @agentsofshield 

Unfortunately, the only solution is to re-register the agents.
You can assign names to agents with a different name convention.
The programs to register agents usually have help messages where you can see the options to name the agents. You can also follow our documentation: 
- [manage_agents](https://documentation.wazuh.com/current/user-manual/reference/tools/manage_agents.html)
- [agent-auth](https://documentation.wazuh.com/current/user-manual/reference/tools/agent-auth.html)

I'm sorry it's not possible to modify the name of the agents. We will consider your suggestion. Thank you very much.

Regards, Eva

**Comment by Lopuiz** [comment]
Hello @agentsofshield 

I hope you solved it.
I will close this issue for inactivity.

Regards,
Eva

**Comment by MikeC-BC** [comment]
Are there any updates on this? Is this possible to change?
