### ISSUE TITLE
Slack integration fails with Agentless alerts 

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#3572]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9 |ossec-integratord | Manager | Any | Ubuntu 18.04 |

### Description
Hi team, 

Agentless alerts cause an error if there is a slack integration.
This has been reported and a fix has been proposed on https://github.com/wazuh/wazuh/pull/3550 

```
2019/06/25 10:48:41 ossec-agentlessd: INFO: ssh_integrity_check_linux: vagrant@192.168.33.32: Started.
2019/06/25 10:48:41 ossec-agentlessd: INFO: ssh_integrity_check_linux: vagrant@192.168.33.32: Finished.
2019/06/25 10:48:43 ossec-integratord: ERROR: Unable to run integration for slack -> /var/ossec/integrations/slack
2019/06/25 10:48:43 ossec-integratord: ERROR: While running slack -> /var/ossec/integrations/slack. Output: KeyError: 'agent'
```

### Steps to reproduce:

- Agentless configuration:
```XML
<agentless>
  <type>ssh_integrity_check_linux</type>
  <frequency>10</frequency>
  <host>vagrant@192.168.33.32</host>
  <state>periodic</state>
  <arguments>/etc/test_agentless</arguments>
</agentless>
```

- Slack integration settings:
```XML
<integration>
  <name>slack</name>
  <group>syscheck</group>
  <hook_url>xxxxxmyHookUrlxxxxx</hook_url>
  <alert_format>json</alert_format>
</integration>
```

- Make FIM trigger on agentless argument path by creating, modifying or deleting files. The first agentless alert will activate the Slack integration and cause the above error
<br></br>
Greetings,

Juan Pablo Sáez

**Comment by snaow** [comment]
Fixed here: https://github.com/wazuh/wazuh/pull/3971
Closing.
