### ISSUE TITLE
Problem with the result of forward all nodes calls 

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#3575]
Hi team,

this issue is to report a problem that the cluster currently has, 

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0=< | Cluster | Manager/Workers | Sources/Packages | Linux |

it happens that when we make a forward all nodes request, if any of the results returned in this call is an error, it will be interpreted as if the whole call had been wrong. This happens because of the merge logic that we currently have implemented.

Here we can see an example of this that we mentioned:
```bash
root@a2139ce3a5df:/# curl -X GET "http://localhost:55000/cluster/configuration/validation"
{
  "code": 1908,
  "dapi_errors": {
    "worker1": {
      "error": "Error validating configuration: [\"(1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).\"]",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "detail": "Error validating configuration: [\"(1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).\"]",
  "remediation": "Please, fix the corrupted files",
  "status": 400,
  "title": "Wazuh Error",
  "type": "about:blank"
}
```
In this case we have made a call to check that all the configurations of our nodes are valid, the master node has a valid configuration, the worker2 node also but the worker1 node has an incorrect configuration. As we see the result we get does not let us see this and tells us that there has been an error and does not show the successes.

We need to redefine these types of calls to correct this error.

Best regards,
Adri

**Comment by crd1985** [comment]
This has been fixed in https://github.com/wazuh/wazuh/pull/2859
