### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [wazuh/wazuh#3579]
I would like to point out that identifiers like “[`__AGENTD_H`](https://github.com/wazuh/wazuh/blob/716302be2ec76e055f60e69cb74d30c524852373/src/client-agent/agentd.h#L11 "Update candidate")” and “[`__LOGREADER_H`](https://github.com/wazuh/wazuh/blob/2ba5a5f7e8a94bdb5053e7debc8109bd62a0ee43/src/logcollector/logcollector.h#L11 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Zenidd** [comment]
Hi again @elfring,

we agree with you, that syntax is not the most appropriate. To avoid this identifiers from causing problems in the future there is already a PR:  https://github.com/wazuh/wazuh/pull/3585

This fix is going to be added to the Wazuh project when possible.Thank you very much for letting us know about this situation. 
<br></br>
Greetings,

Juan Pablo Sáez

**Comment by elfring** [comment]
I find that [more identifiers should be reconsidered](https://github.com/wazuh/wazuh/blob/53245657fab410be5d71f224a330bcfb5bb9bd16/src/analysisd/eventinfo.h#L25 "Update candidate") (besides include guards) for standard compliance.

**Comment by Zenidd** [comment]
Hi @elfring,

The complete refactor will be performed progressively. When we modify a part of the code we will also check the identifiers of that part to adjust them to the naming convention. 

We always like to leave the code cleaner than we found it. 
<br></br>
Regards,

Juan Pablo Sáez

**Comment by chemamartinez** [comment]
Hi @elfring,

Thanks for reporting it, the PR #3585 has been already merged and will be available in the next Wazuh version released.

Regards,
Chema.

**Comment by elfring** [comment]
[Some update candidates were left over](https://github.com/wazuh/wazuh/blob/3014f972dd73c18459e59e4881502c79ead5b602/src/analysisd/rules.h#L79 "Update candidate: _FieldInfo").
