### ISSUE TITLE
Bad Code Block Formatting in Slack Integration

### ISSUE THREAD

**Issue by keaneokelley** [wazuh/wazuh#358]
https://github.com/wazuh/wazuh/blob/fbc5561376b9e5ceca286727e863c8ee916347f9/integrations/slack#L39

I am not sure how this isn't affecting anyone else, but for the past 2 years or so, I've noticed that the formatting in Slack is completely broken; the code block backticks are not respected and I get a glob of text. This is because the newlines get lost somewhere, since `echo`  only interprets backslash escapes with the `-e` flag explicitly specified. It works as expected if the flag is added to the `echo` command.

**Comment by albertomn86** [comment]
Hi @keaneokelley,

we appreciate your comment and let you know that this issue is already fixed. 
In addition, the integration has been improved and the design of the messages has also been updated. All these changes will be included in the next release.

Best regards.
