### ISSUE TITLE
Windows agents don't report Syscheck tags when who-data is enabled

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3582]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.9.1 | Syscheck | Agent | All | Windows |

It has been detected that Syscheck tags are not being included in alerts about modifications and deletions when who-data is enabled.

The issue was found over a Windows agent with Wazuh v3.9.1. During investigating the problem, moving from `who-data` to `real-time` mode solved the problem.

### Configuration to reproduce it

```xml
<syscheck>
  ...
  <directories report_changes="yes" tags="testing" whodata="yes">C:\my_dir</directories>
</syscheck>
```

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/pull/3601.
