### ISSUE TITLE
syscollector_win_ext.dll outside installation folder

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#3597]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.x |-| Agent | Packages | Windows 10 Pro |

Hello,
I've noticed a file named `syscollector_win_ext.dll` appeared in my C:\ folder.
It weights 479 KB.

Regards.

**Comment by vikman90** [comment]
Hello @havidarou,

Could you provide any hash of the DLL file, or the file itself in order to find the exact version from which the file comes?

We have not managed to reproduce this issue with a 3.9.x MSI package, so that information could help us to find the package that failed.

Thanks you.

**Comment by chemamartinez** [comment]
I am closing this issue due to the inability to reproduce it as well as the inactivity of the issue.

Please, reopen it if the issue appears again.

Regards.
