### ISSUE TITLE
API call DELETE /agents seems to ignore filtering by status or older_than param

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3614]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | Framework/API | Manager | Any | Any |

Sometimes after a call to `DELETE/agents` filtering by `status` and `older_than` param all agents are deleted. The result is the `client.keys` file being modified in the following way:
```
...
001 !agent1 any ...
002 !agent2 any ...
003 !agent3 any ...
...
```

Although the cause is being investigated, the root of this anomalous behaviour could be in a bad query in line https://github.com/wazuh/wazuh/blob/38893cd7ac5255f52dc06d755ffff31bb59df798/framework/wazuh/agent.py#L1042-L1044
or wrong data in `/var/ossec/var/db/global.db`.

**Comment by vicferpoy** [comment]
Hello team. With the changes made in the PR bellow, this issue was fixed: https://github.com/wazuh/wazuh/pull/4865

Registering a new agent and filtering by the status `Never connected` and `older_than` 10 minutes, we can see how this new agent is not removed:

`curl -X GET "https://localhost:55001/v4/agents?limit=500&status=never_connected" -H "accept: application/json" -H "Authorization: Bearer <TOKEN>"
`
```
{
  "data": {
    "affected_items": [
      {
        "registerIP": "any",
        "ip": "any",
        "id": "011",
        "node_name": "unknown",
        "name": "wazuh-agent11",
        "dateAdd": "1970-01-01T00:00:00Z",
        "status": "never_connected"
      },
      {
        "registerIP": "any",
        "ip": "any",
        "id": "012",
        "node_name": "unknown",
        "name": "wazuh-agent12",
        "dateAdd": "1970-01-01T00:00:00Z",
        "status": "never_connected"
      },
      {
        "registerIP": "10.0.10.11",
        "ip": "10.0.10.11",
        "id": "013",
        "node_name": "unknown",
        "name": "NewHost_2",
        "dateAdd": "2020-04-28T15:23:46Z",
        "status": "never_connected"
      }
    ],
    "total_affected_items": 3,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information is shown"
}
```

`curl -X DELETE "https://localhost:55001/v4/agents?status=never_connected&older_than=10m" -H "accept: application/json" -H "Authorization: Bearer <TOKEN>"
`

```
{
  "data": {
    "affected_items": [
      "011",
      "012"
    ],
    "total_affected_items": 2,
    "total_failed_items": 11,
    "failed_items": [
      {
        "error": {
          "code": 1731,
          "message": "Agent is not eligible for removal: The agent has a status different to '['never_connected']' or the specified time frame 'older_than 10m' does not apply",
          "remediation": "Please check the agent's status [official documentation](https://documentation.wazuh.com/3.x/user-manual/agents/restful-api/remove.html)"
        },
        "id": [
          "001",
          "002",
          "003",
          "004",
          "005",
          "006",
          "007",
          "008",
          "009",
          "010",
          "013"
        ]
      }
    ],
    "older_than": "10m"
  },
  "message": "Some agents were not deleted"
}
```

Regards.
