### ISSUE TITLE
cis_debian_linux_rcl.yml is not deployed on debian8 jessie

### ISSUE THREAD

**Issue by aderumier** [wazuh/wazuh#3622]
Hi,
I'm not sure how the sca profiles are deployed, 
but I don't see cis_debian_linux_rcl.yml deployed in /var/ossec/ruleset/sca on debian8 jessie.

It's ok on stretch.

**Comment by Skeptor** [comment]
Hi @aderumier 

Policy `cis_debian_linux_rcl.yml` is a generic file for Debian versions without a specific policy. Versions 7 and 8 have policies `debian/cis_debianlinux7-8_L1_rcl.yml` and `debian/cis_debianlinux7-8_L2_rcl.yml` which are installed by default.

Also, the SCA module is going to have some changes, as you can see here https://github.com/wazuh/wazuh/pull/3286, and as a result, the file `cis_debian_linux_rcl.yml` will be removed in further versions.

Regards,
Pablo.

**Comment by Skeptor** [comment]
Hi @aderumier 

I'm going to close the issue. If the doubt is unresolved or you have any other doubt, don't hesitate to reopen the issue and I will help you.

Regards,
Pablo
