### ISSUE TITLE
Total events decoded in analisysd state file does not include SCA events

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3623]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.9.1 | ossec-analisysd | Manager | Packages/Sources | All |

The total amount for decoded events in the state file in analysisd doesn't include the decoded SCA events. 

The variable `s_events_sca_decoded` should be added to this addition:

https://github.com/wazuh/wazuh/blob/38893cd7ac5255f52dc06d755ffff31bb59df798/src/analysisd/state.c#L238

**Comment by Skeptor** [comment]
Hi,

The commit 4778e9cd00b866f6ead997320bcfffd4755ca81b of the PR https://github.com/wazuh/wazuh/pull/3286 contains the fix for this issue.

Regards.

**Comment by chemamartinez** [comment]
This issue has been fixed (https://github.com/wazuh/wazuh/commit/4778e9cd00b866f6ead997320bcfffd4755ca81b) and reviewed. It is included as a part of the [SCA refactor](https://github.com/wazuh/wazuh/pull/3286) included in 3.10.

Closing it.
