### ISSUE TITLE
Offline compilation

### ISSUE THREAD

**Issue by michaelhidalgo** [wazuh/wazuh#3638]
Hey folks, I would like to install wazuh on Linux machines standalone, since I need to install it on different flavors of Linux, I would like to compile the code offline. Do I need to compile the code on each platform or is it possible to do it  from Centos 7.5 for instance?

Thanks for your help.

**Comment by DaveVG1** [comment]
Hi @michaelhidalgo,

You can compile and make packages from a Centos 7.5 instances (and others) following the instructions in https://github.com/wazuh/wazuh-packages
You should have an internet connection to clone that repository as well as for letting Wazuh download the needed dependencies.
I hope this helps. If you have any troubles or any more questions regarding this topic, please don't hesitate to ask us.

Best regards,
David

**Comment by michaelhidalgo** [comment]
Hey @DaveVG1 , it worked fine. Quick question, I want to install wazuh standalone (aka not having a manager).

For example OSSEC installation gives you the chance to choose the mode and I choose local:
`What kind of installation do you want (server, agent, local, hybrid or help)? local`

However, in the compilation instructions, I have the following options:

`Usage: ./generate_wazuh_rpm.sh [OPTIONS]

    -b, --branch <branch>     [Required] Select Git branch [master]. By default: master.
    -t, --target              [Required] Target package to build: manager, api or agent.
    -a, --architecture        [Optional] Target architecture of the package. By default: x86_64
    -j, --jobs                [Optional] Change number of parallel jobs when compiling the manager or agent. By default: 2.
    -l, --legacy              [Optional] Build the package for CentOS 5.
    -r, --release             [Optional] Package release. By default: 1.
    -p, --path                [Optional] Installation path for the package. By default: /var.
    -d, --debug               [Optional] Build the binaries with debug symbols and create debuginfo packages. By default: no.
    -h, --help                Show this help.`

What would be the target equivalent for local?

Thanks in advance.

**Comment by DaveVG1** [comment]
Hi again @michaelhidalgo 

Glad to hear it worked. We currently don't make packages for local installations, but there's a couple of things you can do to install it:

1) You can make your own recipe to make local installation packages. This process differs depending on the package you need (`rpm` or `deb`).

2) You can download the source code of Wazuh, compile it as local installation and install it (this is the easiest way). Unfortunately, there's currently a bug in 3.9 that makes the compilation of a local installation to fail. This has been fixed and will be available in the next version of Wazuh. When it's available you can compile a local installation by following the next steps:
- Download the Wazuh source code
- In the `wazuh/etc` folder, edit `preloaded-vars.conf` file. Uncomment the line ```USER_INSTALL_TYPE="local"```. Save and close the file.
- In the `wazuh/src` folder, execute `make deps && make TARGET=local`.
- In the `wazuh` folder, execute `./install.sh` to install Wazuh.

I'll keep you informed if we include local installation packages in the future.

Regards,
David

**Comment by michaelhidalgo** [comment]
Hey @DaveVG1 , thanks for your prompt response.
It seems to work but there is an issue if you change the installation path in the preloaded variables:
For example, I want that wazuh is installed in a folder in opt:

``` 
# USER_INSTALL_TYPE defines the installation type to
# be used during install. It can only be "local",
# "agent" or "server".
USER_INSTALL_TYPE="local"
#USER_INSTALL_TYPE="agent"
#USER_INSTALL_TYPE="server"
# USER_DIR defines the location to install ossec
USER_DIR="/opt/ossec"
```

The build using `make deps && make TARGET=local` works like a charm, however the installation fails because a configuration file is expected at `/var/ossec/etc/ossec.conf'` not at `/opt/ossec` where I specified.

Here is the error:

``` root@centos-build wazuh-3.9.3]#  /opt/ossec/bin/ossec-control start

2019/07/12 18:26:34 ossec-csyslogd: CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).

ossec-csyslogd: Configuration error. Exiting 

```
Any idea why is it using a different path from the one I've defined in the preloaded vars?

Really appreciate your feedback.

**Comment by DaveVG1** [comment]
Hi @michaelhidalgo 

I think the problem is that you should execute this instead to build it correctly: ```make deps && make TARGET=server PREFIX=/opt/ossec```

Also, be careful while following the installation steps (once you have built it) and check that the installation path selected is the one you desire.

I hope this helps. If it doesn't, don't hesitate to reach us again and I'll try to help you in every way possible.

Best regards,
David

**Comment by michaelhidalgo** [comment]
Thanks for your quick response @DaveVG1 , Let me give a try!.

Really appreciate your help.

**Comment by DaveVG1** [comment]
Hi @michaelhidalgo ,

I hope it worked for you. I'm going to close this issue due to inactivity. Don't hesitate to re-open it or open a new one if you have any trouble regarding this topic.

Best regards,
David
