### ISSUE TITLE
Install agent on manager 

### ISSUE THREAD

**Issue by Stealth5hadow** [wazuh/wazuh#3641]
Is there any way to install the agent on the manager to view the activity on the manager itself?  The process of installing the agent onto the manager machine seems to delete the manager package.  Or does there need to be two machines in order to make use of the software?

**Comment by DaveVG1** [comment]
Hi @Stealth5hadow 

The manager already includes the functionality of the agent. You can configure and use in the manager all the modules available for the agent. In fact, by default, some modules are active in the manager (syscheck, rootcheck, syscollector, etc.). Therefore, you do not need to install a separate agent as the manager already includes its functionality.

I hope this helps. If you have any further questions regarding this topic, please don't hesitate to ask, we'll be happy to help.

Best regards,
David

**Comment by Stealth5hadow** [comment]
Thanks for the information!  This definitely helps me in trying to get familiar with the software.
