### ISSUE TITLE
Error  No matching indices found: No indices match pattern "wazuh-alerts-3.x-*"

### ISSUE THREAD

**Issue by sasam3l4** [wazuh/wazuh#3645]
`hello,`

since i installed the wazuh 3.9.3 there are no alerts, when i check the localhost:9200/_cat/indices i cant find the "wazuh-alerts-3.x-*" just the wazuh-monitoring. 

**here is my http://localhost:9200/_cat/indices**

> green  open wazuh-monitoring-3.x-2019.07.12 SgAvEje3T_uZz8eKOdYdxw 2 0 9 0 108.5kb 108.5kb
> green`  open .kibana_2                       KT85pak5TFWrNZurhYQW2Q 1 0 6 1  65.6kb  65.6kb
> green`  open .kibana_task_manager            deQ2-4uqScmdS7y_35ZqEA 1 0 2 0  45.5kb  45.5kb
> yellow open .wazuh                          XcDF0tvbR3a3RmZGzZJQMA 1 1 1 0  11.3kb  11.3kb
> green  open .kibana_1                       05q-aRmbTdOpW_otQEzy3w 1 0 6 1  61.9kb  61.9kb
> yellow` open .wazuh-version                  Fm029K9rScGu20YXWM44mw 1 1 1 0   5.2kb   5.2kb

**http://localhost:9200/_cat/templates**

> .ml-config                  [.ml-config]                  0          7020099
> .ml-notifications           [.ml-notifications]           0          7020099
> .ml-anomalies-`              [.ml-anomalies-*]             0          7020099
.ml-state                   [.ml-state*]                  0          7020099
.monitoring-es              [.monitoring-es-7-*]          0          7000199
.monitoring-kibana          [.monitoring-kibana-7-*]      0          7000199
wazuh-agent                 [wazuh-monitoring-3.x-*]      0          
.data-frame-internal-1      [.data-frame-internal-1]      0          7020099
.ml-meta                    [.ml-meta]                    0          7020099
.monitoring-logstash        [.monitoring-logstash-7-*]    0          7000199
.monitoring-alerts-7        [.monitoring-alerts-7]        0          7000199
.logstash-management        [.logstash]                   0          
.watch-history-9            [.watcher-history-9*]         2147483647 
.watches                    [.watches*]                   2147483647 
.kibana_task_manager        [.kibana_task_manager]        0          7020099
wazuh                       [wazuh-alerts-3.x-*]          0          
.management-beats           [.management-beats]           0          70000
.data-frame-notifications-1 [.data-frame-notifications-*] 0          7020099
.monitoring-beats           [.monitoring-beats-7-*]       0          7000199
.triggered_watches          [.triggered_watches*]         2147483647 

**lsof /var/ossec/logs/alerts/alerts.json**

> COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
ossec-ana 28976 ossec   10w   REG    8,1   145392 1067265 /var/ossec/logs/alerts/alerts.json
filebeat  1275  root    3r   REG    8,1   124594 1067264 /var/ossec/logs/alerts/alerts.json

**Comment by pablotr9** [comment]
Hi @sasam3l4,

Could you please paste your elasticsearch error log so we can see if there is something wrong with it? This file can be found at **/var/log/elasticsearch/(cluster name | elasticsearch).log**.

Filebeat seems to be reading from _alerts.json_ but it's not sending anything to Elastic, could you please check that Wazuh is working and generating alerts and these alerts are stored in _/var/ossec/logs/alerts/alerts.json_.
Also, it would be helpful if you could paste the configuration of your Filebeat, as it may be misconfigured. This configuration file can be found here:  /etc/filebeat/filebeat.yml

Regards,
Pablo Torres

**Comment by stephenmelcher** [comment]
I am having a similar issue.  I curl -XGET the indices and the "wazuh-alerts-3-*" is missing.  The "wazuh-monitoring" one is there.  Filebeat's yml file shows the output being "wazuh-alerts-3.x-%{+yyyy.MM.dd}".  This happened after a system failure.  I had to create a new node for ElasticSearch in a fresh directory.  When the services started everything came back up, but without any alert traffic.

**Comment by pablotr9** [comment]
Hi @stephenmelcher,

Please check that Filebeat is reading the `alerts.json` file with this command:
```
lsof /var/ossec/logs/alerts/alerts.json
```
If Filebeat is reading the alerts.json, check that Filebeat can connect to Elasticsearch as it is probably having connection issues with Elasticsearch and indices can't be created
```
filebeat test output
```

I will close this issue due to inactivity, please feel free to reopen it if you are still facing this issue.

Regards,
Pablo Torres
