### ISSUE TITLE
wazuh data does not show up in kibana app

### ISSUE THREAD

**Issue by zozo6015** [wazuh/wazuh#3646]
wazuh version 3.9.3, apt repository, ubuntu 18.04, elk stack 7.2.0

We have upgraded our system from elasticsearch 6.6.1 to 7.2.0 and wazuh from 3.8.x to 3.9.3. We can see wazuh data coming in from logstash but they do not show up in kibana wazuh app or discovery app either.  We had the same issue with other indexes in the past when the data injested were not compatible with the templates stored in the elasticsearch. 
Any suggestion on how to fix it?

Regards,
Peter

**Comment by pablotr9** [comment]
Hi @zozo6015,

What steps did you follow to do that upgrade? this upgrade process can be a bit annoying, have you followed our guide to upgrade ELK? https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/index.html

Could you please send us error logs from elasticsearch and logstash, these files can be found here: **/var/log/elasticsearch/(cluster name | elasticsearch).log** and **/var/log/logstash**.

It would be also helpful for us if you could send us the output of this request:
`curl elastic-ip:9200/_template/wazuh`


Best regards,
Pablo Torres

**Comment by zozo6015** [comment]
I have followed the elasticsearch upgrade documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/restart-upgrade.html since the upgrade was from an older version of elasticsearch and not 6.8 to 7.x.

**Comment by pablotr9** [comment]
Hi @zozo6015,

Are you using just Logstash, or is Filebeat being used too? 
For Elastic 7.x we have removed Logstash (you can still use it as an optional component), we've also moved the place for the template, now is Filebeat who sends the template.

Here you can find a guide to install Filebeat and send Wazuh logs to Elasticsearch https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-server/wazuh_server_deb.html#installing-filebeat 

Regards,
Pablo Torres

**Comment by zozo6015** [comment]
I was using logstash since it was configured like that for about one and half years. I've changed to filebeat and started to work after reimporting the template. Thank you alot for your help
