### ISSUE TITLE
why ossec-logtest generated alert but alert.json not has this logs 

### ISSUE THREAD

**Issue by 0x442e** [wazuh/wazuh#3665]
[root@datanode2 bin]# ./ossec-logtest
2019/07/16 15:47:15 ossec-testrule: INFO: Started (pid: 12172).
ossec-testrule: Type one log per line.

{"win":{"system":{"providerName":"Microsoft-Windows-Sysmon","providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","eventID":"1","version":"5","level":"4","task":"1","opcode":"0","keywords":"0x8000000000000000","systemTime":"2019-07-16T06:30:58.665789300Z","eventRecordID":"318081","processID":"4748","threadID":"7500","channel":"Microsoft-Windows-Sysmon/Operational","computer":"cocacolaPC","severityValue":"INFORMATION","message":"Process Create:"},"eventdata":{"utcTime":"2019-07-16 06:30:58.638","processGuid":"{7bfeca87-6f22-5d2d-0000-0010e12b572a}","processId":"14984","image":"C:\Windows\System32\dxgiadaptercache.exe","fileVersion":"10.0.18362.1 (WinBuild.160101.0800)","description":"DXGI Adapter Cache","product":"Microsoft® Windows® Operating System","company":"Microsoft Corporation","originalFileName":"DXGIAdapterCache.exe","commandLine":"C:\WINDOWS\system32\dxgiadaptercache.exe","currentDirectory":"C:\WINDOWS\system32\","user":"NT AUTHORITY\SYSTEM","logonGuid":"{7bfeca87-2af7-5d2d-0000-0020e7030000}","logonId":"0x3e7","terminalSessionId":"0","integrityLevel":"System","hashes":"MD5=3F095547EF68AF8FBA429BC3D6D405C7,SHA256=A8F1EAA2BE98BE43B79F743FDE5D360974ECC0A3DC4AD57EAD3033F689C3B67C","parentProcessGuid":"{7bfeca87-2af8-5d2d-0000-0010b8220200}","parentProcessId":"1720","parentImage":"C:\Windows\System32\svchost.exe","parentCommandLine":"C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s Schedule"}}}

**Phase 1: Completed pre-decoding.
full event: '{"win":{"system":{"providerName":"Microsoft-Windows-Sysmon","providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","eventID":"1","version":"5","level":"4","task":"1","opcode":"0","keywords":"0x8000000000000000","systemTime":"2019-07-16T06:30:58.665789300Z","eventRecordID":"318081","processID":"4748","threadID":"7500","channel":"Microsoft-Windows-Sysmon/Operational","computer":"cocacolaPC","severityValue":"INFORMATION","message":"Process Create:"},"eventdata":{"utcTime":"2019-07-16 06:30:58.638","processGuid":"{7bfeca87-6f22-5d2d-0000-0010e12b572a}","processId":"14984","image":"C:\Windows\System32\dxgiadaptercache.exe","fileVersion":"10.0.18362.1 (WinBuild.160101.0800)","description":"DXGI Adapter Cache","product":"Microsoft® Windows® Operating System","company":"Microsoft Corporation","originalFileName":"DXGIAdapterCache.exe","commandLine":"C:\WINDOWS\system32\dxgiadaptercache.exe","currentDirectory":"C:\WINDOWS\system32\","user":"NT AUTHORITY\SYSTEM","logonGuid":"{7bfeca87-2af7-5d2d-0000-0020e7030000}","logonId":"0x3e7","terminalSessionId":"0","integrityLevel":"System","hashes":"MD5=3F095547EF68AF8FBA429BC3D6D405C7,SHA256=A8F1EAA2BE98BE43B79F743FDE5D360974ECC0A3DC4AD57EAD3033F689C3B67C","parentProcessGuid":"{7bfeca87-2af8-5d2d-0000-0010b8220200}","parentProcessId":"1720","parentImage":"C:\Windows\System32\svchost.exe","parentCommandLine":"C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s Schedule"}}}'
timestamp: '(null)'
hostname: 'datanode2'
program_name: '(null)'
log: '{"win":{"system":{"providerName":"Microsoft-Windows-Sysmon","providerGuid":"{5770385f-c22a-43e0-bf4c-06f5698ffbd9}","eventID":"1","version":"5","level":"4","task":"1","opcode":"0","keywords":"0x8000000000000000","systemTime":"2019-07-16T06:30:58.665789300Z","eventRecordID":"318081","processID":"4748","threadID":"7500","channel":"Microsoft-Windows-Sysmon/Operational","computer":"cocacolaPC","severityValue":"INFORMATION","message":"Process Create:"},"eventdata":{"utcTime":"2019-07-16 06:30:58.638","processGuid":"{7bfeca87-6f22-5d2d-0000-0010e12b572a}","processId":"14984","image":"C:\Windows\System32\dxgiadaptercache.exe","fileVersion":"10.0.18362.1 (WinBuild.160101.0800)","description":"DXGI Adapter Cache","product":"Microsoft® Windows® Operating System","company":"Microsoft Corporation","originalFileName":"DXGIAdapterCache.exe","commandLine":"C:\WINDOWS\system32\dxgiadaptercache.exe","currentDirectory":"C:\WINDOWS\system32\","user":"NT AUTHORITY\SYSTEM","logonGuid":"{7bfeca87-2af7-5d2d-0000-0020e7030000}","logonId":"0x3e7","terminalSessionId":"0","integrityLevel":"System","hashes":"MD5=3F095547EF68AF8FBA429BC3D6D405C7,SHA256=A8F1EAA2BE98BE43B79F743FDE5D360974ECC0A3DC4AD57EAD3033F689C3B67C","parentProcessGuid":"{7bfeca87-2af8-5d2d-0000-0010b8220200}","parentProcessId":"1720","parentImage":"C:\Windows\System32\svchost.exe","parentCommandLine":"C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s Schedule"}}}'

**Phase 2: Completed decoding.
decoder: 'json'
win.system.providerName: 'Microsoft-Windows-Sysmon'
win.system.providerGuid: '{5770385f-c22a-43e0-bf4c-06f5698ffbd9}'
win.system.eventID: '1'
win.system.version: '5'
win.system.level: '4'
win.system.task: '1'
win.system.opcode: '0'
win.system.keywords: '0x8000000000000000'
win.system.systemTime: '2019-07-16T06:30:58.665789300Z'
win.system.eventRecordID: '318081'
win.system.processID: '4748'
win.system.threadID: '7500'
win.system.channel: 'Microsoft-Windows-Sysmon/Operational'
win.system.computer: 'cocacolaPC'
win.system.severityValue: 'INFORMATION'
win.system.message: 'Process Create:'
win.eventdata.utcTime: '2019-07-16 06:30:58.638'
win.eventdata.processGuid: '{7bfeca87-6f22-5d2d-0000-0010e12b572a}'
win.eventdata.processId: '14984'
win.eventdata.image: 'C:\Windows\System32\dxgiadaptercache.exe'
win.eventdata.fileVersion: '10.0.18362.1 (WinBuild.160101.0800)'
win.eventdata.description: 'DXGI Adapter Cache'
win.eventdata.product: 'Microsoft® Windows® Operating System'
win.eventdata.company: 'Microsoft Corporation'
win.eventdata.originalFileName: 'DXGIAdapterCache.exe'
win.eventdata.commandLine: 'C:\WINDOWS\system32\dxgiadaptercache.exe'
win.eventdata.currentDirectory: 'C:\WINDOWS\system32'
win.eventdata.user: 'NT AUTHORITY\SYSTEM'
win.eventdata.logonGuid: '{7bfeca87-2af7-5d2d-0000-0020e7030000}'
win.eventdata.logonId: '0x3e7'
win.eventdata.terminalSessionId: '0'
win.eventdata.integrityLevel: 'System'
win.eventdata.hashes: 'MD5=3F095547EF68AF8FBA429BC3D6D405C7,SHA256=A8F1EAA2BE98BE43B79F743FDE5D360974ECC0A3DC4AD57EAD3033F689C3B67C'
win.eventdata.parentProcessGuid: '{7bfeca87-2af8-5d2d-0000-0010b8220200}'
win.eventdata.parentProcessId: '1720'
win.eventdata.parentImage: 'C:\Windows\System32\svchost.exe'
win.eventdata.parentCommandLine: 'C:\WINDOWS\system32\svchost.exe -k netsvcs -p -s Schedule'

**Phase 3: Completed filtering (rules).
Rule id: '100002'
Level: '3'
Description: 'sysmon : C:\Windows\System32\dxgiadaptercache.exe'
**Alert to be generated.

my rule :
`<group name="sysmon,"> <rule id="100002" level="3"> <field name="win.system.severityValue">INFORMATION</field> <description>sysmon : $(win.eventdata.image)</description> </rule> </group>`

And in archives.json file has this log ,but alert.json not has
my ossec.conf:
`<alerts> <log_alert_level>3</log_alert_level> <email_alert_level>12</email_alert_level> </alerts>`

**Comment by cristgl** [comment]
Hello @0x442e,

This log includes a header which states that it is an EventChannel event. This is why you cannot see it at your alerts.log file. As you are passing the JSON part of the event to `ossec-logtest`, the JSON decoder is the one that matches.

EventChannel events are decoded by an internal decoder, which cannot be tested with `ossec-logtest`.
In order to make your rule match, you should add a parent to it. As it has `Microsoft-Windows-Sysmon/Operational` as channel you should make it pend from rule 61004. Your rule is similar to 60100, as you are matching `INFORMATION` as severity value.

Which Wazuh version are you using? There is other method with which you can test your EventChannel rules, you can replace the rule 60000 by the next one:

```
<rule id="60000" level="0">
    <decoded_as>json</decoded_as>
    <field name="win.system.providerName">\.+</field>
    <options>no_full_log</options>
    <description>Group of windows rules</description>
  </rule>
```

Then, pasting the JSON part of the event in `ossec-logtest` will return the right rule with `windows_eventchannel` as the decoder.

Let me know if this helped and if you could solve your issue.

Kind regards,
Cristina

**Comment by 0x442e** [comment]
@cristgl  thx u answer my questions，my logs is sysmon v10 generated，Wazuh is v3.9.3，Wazuh is currently supporting sysmon 10？

**Comment by 0x442e** [comment]
i want sysmon all logs sent to alert.json ，What should I do？

**Comment by cristgl** [comment]
Hello @0x442e,

Sysmon 10 is not supported in the last Wazuh release, but we have already started making some rules that match with the new events in the next PRs: https://github.com/wazuh/wazuh-ruleset/pull/435 and https://github.com/wazuh/wazuh-ruleset/pull/436, they will be added to the ruleset in the next releases. Nevertheless, you could paste these rules to your Sysmon file so that you can start using them.

If you want every Sysmon log to be sent to alert.json, you could increase the level of a generic Sysmon rule that only matches the channel to 3 or higher. This way every Sysmon event will be forwarded to alerts.json.

Let me know if this helped,
Kind regards,
Cristina

**Comment by 0x442e** [comment]
> Hello @0x442e,
> 
> Sysmon 10 is not supported in the last Wazuh release, but we have already started making some rules that match with the new events in the next PRs: [wazuh/wazuh-ruleset#435](https://github.com/wazuh/wazuh-ruleset/pull/435) and [wazuh/wazuh-ruleset#436](https://github.com/wazuh/wazuh-ruleset/pull/436), they will be added to the ruleset in the next releases. Nevertheless, you could paste these rules to your Sysmon file so that you can start using them.
> 
> If you want every Sysmon log to be sent to alert.json, you could increase the level of a generic Sysmon rule that only matches the channel to 3 or higher. This way every Sysmon event will be forwarded to alerts.json.
> 
> Let me know if this helped,
> Kind regards,
> Cristina

Thx Cristina，I see 👍

**Comment by 0x442e** [comment]
Sorry, I have another question. My  Wazuh is v3.9.3，sysmon 10 ，Which should I add file？wazuh/wazuh-ruleset#435 or  wazuh/wazuh-ruleset#436, ？

**Comment by cristgl** [comment]
Hello @0x442e,

As you are using Wazuh 3.9.3 with Eventchannel, I recommend you adding wazuh/wazuh-ruleset#436.

Kind regards,
Cristina
