### ISSUE TITLE
Policy Monitoring Module - SCA

### ISSUE THREAD

**Issue by iostack** [wazuh/wazuh#3673]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9 | Policy Monitoring Module | Agent | Packages| Debian 9 |

The 'SSH Hardening - 1: Port 22' check is wrong, if we use a port like 2235 it will fail the check.

**Comment by cristgl** [comment]
Hello @iostack,

You are right, this check is wrong and it's including every number that contains '22'. It was fixed [here](https://github.com/wazuh/wazuh-ruleset/blob/b9e3346cdb2418d9e21b83044c4bc525e247e59c/sca/generic/sca_unix_audit.yml#L33). Thank you very much for reporting this, your feedback is really appreciated.

Kind regards,
Cristina

**Comment by cristgl** [comment]
Hi,

We are closing this issue as it was already fixed in the file mentioned above.
If you need further help, do not hesitate to ask.

Kind regards,
Cristina
