### ISSUE TITLE
Due to Wazuh Duplicated IP,agent install fail

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#3674]
|Wazuh version:3.9.2-1
|Component: Wazuh-manager
|Install type:Manager
|Install method:Packages
|Platform|CentOS 7.5

Hello,I installed Wazuh-Manager in my company network ,ip is 192.168.10.31

And I try to install Wazuh-Agent in my  Vmware host ,Vmware use  NAT to join  the  network. My host  AAA's ip is  192.168.248.163 ，agent name is “aaa”. And  my  host  real  ip  is 192.168.25.66.The  kibana  Wazuh app show  the  ip  is  192.168.25.66 not    192.168.248.163. I think Wazuh-Manager just  use  my  connection  ip  not   interface  ip

So, When I try  to  install Wazuh-Agent in my  other  Vmware host  like bbb, ip  is  192.168.248.142. The  agent  AAA  just  vanished. I lookup the Manager  log.I find  if I install agent "bbb",the "aaa" is  Authentication error.SO when I  visit Kibana Wazuh APP, the page show me the agent just only "bbb"

![image](https://user-images.githubusercontent.com/15324125/61343531-a0e2a900-a880-11e9-85a3-847c16f2b401.png)

![image](https://user-images.githubusercontent.com/15324125/61343603-f1f29d00-a880-11e9-8e55-c7ece3ade7fb.png)

I visited the Manager host directory "/var/ossec/queue/agent-info",there is only bbb-agent file,and filename's ip is my  host real ip.The file content show me the ip is interface

![image](https://user-images.githubusercontent.com/15324125/61343651-164e7980-a881-11e9-9cf9-21249906e796.png)

I try to edit the ossec.conf.set the "force_insert" to "no" and set the "force_time" to "-1",then I restart the Wazuh-manager

![image](https://user-images.githubusercontent.com/15324125/61343747-7b09d400-a881-11e9-96ae-1c5083661231.png)

But it's useless,when I try to restart aaa agent, the log tell me Server not reply

![image](https://user-images.githubusercontent.com/15324125/61343845-d340d600-a881-11e9-9a4a-01aee2077781.png)

I try to reinstall the wazuh-agent in aaa,but also tell me "ERROR: Duplicated IP: 192.168.25.66 (from manager)"

![image](https://user-images.githubusercontent.com/15324125/61343907-fcf9fd00-a881-11e9-80e6-0fffdc216fac.png)

So I don't know how to solve the question.I think it's normal for some host. These hosts could not connect the manager host directly.To connect the manager host,it will use proxy host like nginx or danted. If Wazuh manager just use agent  connection ip not interface ip,these hosts will not connect to manager ip,because these hosts's connection ip are proxy host's ip. I just want to know what can I do in this situation.thx!

I hope receive your reply soon~~

**Comment by Zenidd** [comment]
Hi @xufengnian,

This behavior is common on Multiple VMS on one host environments:

- Inside the VM scenario, each machine has its own IP but from the host side, the have the same IP. You can read more about on this [stackexchange thread](https://unix.stackexchange.com/questions/29999/why-are-my-two-virtual-machines-getting-the-same-ip-address)

- If from the host's point of view we see the same IP for this VM's, from outside the host we only see the host's IP.

In your situation a small change in the `<auth>` configuration block of should solve your problem:

Please, change `<use_source_ip>` to "no" and let `<force_insert>` and `<force_time>` with their default values. The further example has the needed values.
```
<auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <!-- other auth tags -->
```

Please, let me know if it helps. Don't hesitate to write to us again if it doesn't work and we'll look for another solution.

Greetings, Juan Pablo Sáez

**Comment by xufengnian** [comment]
Thank for your reply,this question has been solved.Your answer help me a lot.
I think I should read Wazuh document more.
