### ISSUE TITLE
wazuh manager crash - ossec-logcollector: ERROR: socketerr (not available).

### ISSUE THREAD

**Issue by ips972** [wazuh/wazuh#3675]
|Wazuh version= v3.9.3 |Install method = apt-get |Platform =Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)

Hi, 
Forgive my not so perfect English (not first language) 
I'm totally new to wazuh as I started a few months back with wazuh 3.8.2
Did a complete install on a single all in one server of wazuh manager+api + ELK
Server is a VM with 20 cores + 64GB ram + 2TB SSD of the main storage that the host VM is attached to.
The Wazuh server has a total of 5900 agents registered (Win10 & win7 - no servers) - all was running great!

Until i updated to 3.9.2 (and then to 3.9.3- maybe fix but sadly not) and ever since then i've been getting wazuh manager crashes..

As i said I'm new to wazuh and very new to linux - so please give detailed instructions in any request (please dont assume i know how to do what you ask :-))

I've gone through all the threads and posts i could find. verified as many files/directories/permissions as i saw people talking about with no apparent solution..

Crashes are all the time at random hours. with the following error messages:

2019/07/17 09:10:02 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:10:01 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:10:01 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:10:00 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:09:59 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:09:58 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:09:57 ossec-logcollector ERROR:  socketerr (not available).
2019/07/17 09:09:56 ossec-logcollector ERROR:  socketerr (not available).

**Comment by vikman90** [comment]
Hi @ips972,

First of all, thank you very much for reporting this issue. We have been reported another crash that may be related to this one: #3618.

We suspect that this crash is due to one of these issues:
1. Uncontrolled interaction with Eventchannel: #3626
2. Bug when handling invalid JSON input: #3648

Both bugs have been fixed in the branch _master_ and they are ready for the next release v3.9.4.

Since your manager is a 20-core machine and your agents' platform is Windows, I guess that the problem you're experiencing is due to an uncontrolled interaction —race condition— between components, and I wonder if the fixes above would solve this issue.

Did you upgrade your agents to 3.9?

On the other hand, I wonder if you are able to install a development version of the manager. In other words, I would propose you to install a preliminar version 3.9.4, that we're developing right now. If you are able to, I will help you with that.

Thank you so much again, and apologies for the inconveniences.
Best regards.

**Comment by vikman90** [comment]
If you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.

Regards.

**Comment by ips972** [comment]
vikman90 thank you very much for the detailed answer. 

only one pc was upgraded to agent 3.9.2 - and as soon as i noticed the server crashes I stopped the upgrade process for the remaining 5K workstations. 

the installation is a production one - i think it would be a smart move to install dev version.. wouldn't want to have to re-install and re-register 5K pc's

how should we continue?

**Comment by ips972** [comment]
well, setting the analysisd.sca_thread to 1 as requested  didn't help and at 01:37 am the manager crashed again with these error logs:

2019/07/22 01:37:23 ossec-remoted: ERROR: socketerr (not available).
2019/07/22 01:37:23 ossec-remoted: ERROR: socketerr (not available).
2019/07/22 01:37:23 ossec-remoted: ERROR: socketerr (not available).
2019/07/22 01:37:23 ossec-remoted: ERROR: socketerr (not available).
2019/07/22 01:37:23 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/07/22 01:37:23 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection reset by peer'.
2019/07/22 01:37:23 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/07/22 01:37:23 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/07/22 01:37:24 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:25 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:26 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:27 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:28 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:29 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:30 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:31 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:32 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:33 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:34 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:35 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:36 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:37 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:38 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:38 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/07/22 01:37:38 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/07/22 01:37:38 ossec-remoted: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/07/22 01:37:38 ossec-remoted: CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/07/22 01:37:38 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/07/22 01:37:38 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/07/22 01:37:38 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/07/22 01:37:39 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:40 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:41 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:42 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:43 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 01:37:44 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).

**Comment by ips972** [comment]
and at 2:08 the logs switched to these error messsages:

2019/07/22 02:07:57 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 02:07:58 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 02:07:58 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 02:07:59 ossec-logcollector[12121] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).
2019/07/22 02:08:00 ossec-monitord: ERROR: (1224): Error sending message to queue.
2019/07/22 02:08:00 ossec-monitord: ERROR: socketerr (not available).

**Comment by vikman90** [comment]
Hi @ips972,

Apologies for the late response. All these logs mean that Analysisd became unavailable.

Indeed, if you run `ossec-control status` you'll see an issue with Analysisd:

```
$ /var/ossec/bin/ossec-control status
```
> wazuh-clusterd not running...
> wazuh-modulesd is running...
> ossec-monitord is running...
> ossec-logcollector is running...
> ossec-remoted is running...
> ossec-syscheckd is running...
> **ossec-analysisd: Process 656 not used by Wazuh, removing...**
> ossec-analysisd not running...
> ossec-maild not running...
> ossec-execd is running...
> wazuh-db is running...
> ossec-authd is running...
> ossec-agentlessd not running...
> ossec-integratord not running...
> ossec-dbd not running...
> ossec-csyslogd not running...
```

The fact that this issue still appears even if you set the number of SCA threads to `1` makes me think that the PRs that I mentioned should fix it.

I understand that you cannot set up a debugging focused installation as you're experiencing this problem in a production environment. We're working to release Wazuh 3.9.4 including these fixes very soon, maybe this week or next.

However, I can provide you with the binary _ossec-analysisd_ version 3.9.4-rc1, that is compatible with your current version 3.9.3 and you can simply copy it into the installation folder (_/var/ossec/bin_), if you're OK with this.

Kind regards.

**Comment by ips972** [comment]
thanks for the in depth explanation, I'll wait for the final production release. 
I'm currently working with the crontab job as a work around restarting the manager services every 60 minutes. not the best solution - but working.

**Comment by vikman90** [comment]
Okay, let's do it that way. 

I will leave this issue opened until you install 3.9.4 and confirm whether it fixes this issue. I hope so.

Regards.

**Comment by vikman90** [comment]
Hi @ips972,

This is only to let you know that we've just released Wazuh 3.9.5, that includes the fixes related to Analysisd.

Let us know if you have the chance to upgrade your manager. I hope this solves the problem you're experiencing.

Best regards.

**Comment by vikman90** [comment]
Hi,

We've got Analysisd crashed again, even with the fixes applied. We analyzed the core dump and found that the SCA decoder was using socket with high file descriptor numbers. This is an issue due to a bug in the GLib's implementation of `select`.

Related issue (same bug in Wazuh DB): #587.

## How to reproduce

1. Stop Wazuh.
2. Run Execd, Wazuh DB and Analysisd.
3. Send about 1500 Rootcheck events, spoofing different agents.
4. Start Wazuh Modulesd.

### Scripts

```shell
ossec-control stop
ossec-execd
wazuh-db
gdb -ex run --args ossec-analysisd -f
```

```shell
for i in {1..1500}
do
    echo -n "9:[001] (agent$i) any->rootcheck:hello" | nc -Uu /var/ossec/queue/ossec/queue
done
```

```shell
wazuh-modulesd
```

### Crash report by GDB

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd47f0700 (LWP 2174)]
0x00000000004497fe in pm_send_db (msg=0x7fffe0007380 "\020U", response=0x7fffe0017390 "ok", sock=0x7fffd47efeec)
    at analysisd/decoders/security_configuration_assessment.c:1882
1882	}
```

## Remediation

We should replace `select` with the _Wazuh Notify_ library, as we did in Wazuh DB.

**Comment by ips972** [comment]
upgrading to 3.9.5 - seems to have solved my servers crash.. they have been running with no issues for a week now. 

Thanks for the assistance!

**Comment by Zenidd** [comment]
Hi @ips972,

Great. We're glad we helped you. I'm closing this ticket, If you have any other questions, don't hesitate to ask. Also If you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

Best regards from Wazuh team.
