### ISSUE TITLE
ruleset / sca  system_audit_ssh.yml protocol version is wrong

### ISSUE THREAD

**Issue by iostack** [wazuh/wazuh#3681]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | SCA | Manager/Agent | Package Deb | Deb 9 |

In system_audit_ssh.yml file id 1501 it says 'The SSH protocol should not be 1.' but the rule is checking for protocol 1. I dont know if you really want to check for version 1 with a labelling error, or rule is for protocol 2. Correction has been made on cis_debian_linux_rcl.yml id 5035 with the same error.

 - id: 1501
   title: "**SSH Hardening - 2: Protocol 1**"
   description: "**The SSH protocol should not be 1.**"
   rationale: "The Protocol parameter dictates which version of the SSH communication and encryption protocols are in use. Version 1 of the SSH protocol has weaknesses."
   remediation: "Change the Protocol option value in the sshd_config file."
   compliance:
    - pci_dss: "2.2.4"
   condition: any
   rules:
     - 'f:$sshd_file -> IN !r:^# && r:**Protocol\.+1**;'

**Comment by Skeptor** [comment]
Hi @iostack,

SCA search for the wrong values of a check to give a result:

In this example, if `Protocol 1` is found then the check is marked as false.
On the other hand, if SCA doesn't find `Protocol 1` then the check is passed.

The logic behind SCA is going to change for version 3.10. The changes and the tracking of the work can be found here: https://github.com/wazuh/wazuh/issues/3249

If you have any other doubt, please don't hesitate to ask.

Regards.

**Comment by iostack** [comment]
My bad , sorry for the waste of your time.

**Comment by Skeptor** [comment]
Don't apologize, feel free to ask if you need anything and we will be pleased to help you.
We know that this SCA behaviour could be confusing and this is one of the main reasons for the change on the mechanism.

Regards.
