### ISSUE TITLE
Configuration files can be sent to agents in bulk ?  

### ISSUE THREAD

**Issue by 0x442e** [wazuh/wazuh#3703]
Configuration files can be sent to agents in bulk ?  eg:ossec.conf add 
`  <localfile>
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>`

**Comment by DaveVG1** [comment]
Hi @0x442e,

You can send the same configuration to several agents by using the centralized configuration (`agent.conf` file in the manager).

This file is located in `/var/ossec/etc/shared/default/agent.conf` (for the `default` group). This configuration will be sent to the agents you desire (you can group agents by `name`, `os` or `profile`).

For example, if you want to send the configuration you specified to every Windows agent, the next configuration in `agent.conf` should work:

```
<agent_config os="Windows">

  <localfile> 
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format> 
  </localfile>

</agent_config>
```

For more information please visit https://documentation.wazuh.com/3.9/user-manual/reference/centralized-configuration.html

If you have any further doubts regarding this topic, don't hesitate to contact us.

Kind regards,
David
