### ISSUE TITLE
Syscheck directories tag doesn't recognize directory / it needs /.

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#3705]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-1 | Syscheck/fim | Agent | Packages | Ubuntu 18.04 |

Hello team,

We have noticed when we define a directories tag on syscheck configuration with `/` path it doesn't recognize the path, saying:
```
2019/07/22 08:08:27 ossec-syscheckd: INFO: (6003): Monitoring directory: '', with options 'perm | size | owner | group | md5sum | sha1sum | sha256sum | report_changes | mtime | inode | follow_symbolic_link'.
```

Inside documentation it refers that we need to add `.` to the path https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?#directories
If we set directories tag to `/.` it works right:
```
2019/07/22 08:14:18 ossec-syscheckd: INFO: (6003): Monitoring directory: '/.' (/), with options 'perm | size | owner | group | md5sum | sha1sum | sha256sum | report_changes | mtime | inode | follow_symbolic_link'.
```

It seems an unnatural way to define a path, we open this issue to talk this topic.

Regards!.

**Comment by FernandoCP** [comment]
Hi team!

New FIM solves it. I am going to close this issue.

Best regards, Fernando.
