### ISSUE TITLE
[Feature request]  Upgrade multiple agents with agent_upgrade

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3710]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-rev | agent_upgrade | Manager | Packages | - |

### Feature Requested
That the `agent_upgrade` utility should have an option to upgrade all outdated agents (or a sub-group of them). 

### Rationale
Currently the `agent_upgrade` utility takes in a single ID for an agent to be upgraded, this requires to either individually upgrade agents one by one or to depend on an external script.

This would also affect the API `PUT /agents/:agent_id/upgrade` call.

### Workaround
A simple script to attempt to upgrade all outdated agents would be:
`/var/ossec/bin/agent_upgrade -l | awk '$1 ~ /^[0-9]+$/ {print "Starting upgrade on agent " $1; system("/var/ossec/bin/agent_upgrade -a " $1)}'`
This will of course give an error for disconnected agents but will continue with all other agents.

**Comment by jlruizmlg** [comment]
But the workaround only works for the agents connected in that specific manager right? so you need to run the command in each manager if you have more than one...

**Comment by jctello** [comment]
That is correct.
It could be improved with a script instead of a one-liner that would check which agents are connected to the node (using `cluster_control -a | grep nodename` where the `agent_upgrade` is being run on. 
And also to verify that the agent is currently active to avoid getting an error about disconnected agents.

**Comment by jesusjimsa** [comment]
Hello team.
When helping an user find the correct command to upgrade all its agents, I have tried the `cluster_control -a` command in a script and this is what worked for me:
```bash
for x in `cluster_control -a | awk '{print $1}' | sed -n '1!p'`; do agent_upgrade -a $x; done
```

**Comment by TomasTurina** [comment]
Feature introduced in https://github.com/wazuh/wazuh/issues/5387
