### ISSUE TITLE
Inconsistency between deployment options on Linux and Windows

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3714]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-3929 | Deployment/Registration | Agent | Packages | All |

Since Wazuh v3.9.0, the Unix packages admit variables to automate the registration and connection process when installing agents. That feature was available for Windows MSI packages some versions ago.

The issue is related to the variables names. They are totally different in both platforms. An example with the one to set the manager IP:

**Windows agents**

On Windows, the variable is called `ADDRESS` and lists of IPs are separated by semicolons.

`ADDRESS="10.0.0.2;10.0.0.3"`

https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/deployment_variables_windows.html

**Unix agents**

Meanwhile, for Unix agents we use `WAZUH_MANAGER_IP`, separating different IPs by commas.

`WAZUH_MANAGER_IP="10.0.0.2,10.0.0.3"`

https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/deployment_variables.html

It happens the same with other variables such as `WAZUH_MANAGER_PORT/SERVER_PORT`.

Those variables should be unified to standardize the process and make it more intuitive for the users.

**Comment by BraulioV** [comment]
Hi @chemamartinez,

There's a PR opened that will unify the variables used in Windows and UNIX hosts to auto-deploy the agents. You can see the changes in https://github.com/wazuh/wazuh/pull/3708 in the source code and the changes in the docs in https://github.com/wazuh/wazuh-documentation/pull/1588.

Also, we are currently working to unify the character that separates the values for the `WAZUH_MANAGER` variable (previously, `WAZUH_MANAGER_IP`).

Regards.

**Comment by BraulioV** [comment]
Hi again @chemamartinez,

Here you can see the commit that unifies the character in UNIX and Windows: https://github.com/wazuh/wazuh/pull/3708/commits/b389486fdbc7959f3d30e057eed3c522832d01f1. This commit allows to install the agent like this:
- `WAZUH_MANAGER="172.17.0.2,172.17.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`
- `WAZUH_MANAGER="172.17.0.2;172.17.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`
- `WAZUH_MANAGER="172.17.0.2;172.17.1.1,1.1.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`

Regards.

**Comment by chemamartinez** [comment]
> Hi again @chemamartinez,
> 
> Here you can see the commit that unifies the character in UNIX and Windows: [b389486](https://github.com/wazuh/wazuh/commit/b389486fdbc7959f3d30e057eed3c522832d01f1). This commit allows to install the agent like this:
> 
> * `WAZUH_MANAGER="172.17.0.2,172.17.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`
> * `WAZUH_MANAGER="172.17.0.2;172.17.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`
> * `WAZUH_MANAGER="172.17.0.2;172.17.1.1,1.1.1.1" yum install -y wazuh/wazuh-agent-3.9.3-1.x86_64.rpm`
> 
> Regards.

Hi @BraulioV,

Thanks for the update! So, it is still needed to use semicolons for separate addresses on Windows?

Regards.

**Comment by BraulioV** [comment]
Hi @chemamartinez,

Yes, Windows installer only uses semicolons to separate addresses. In UNIX, both characters are supported.
