### ISSUE TITLE
Access Wazuh using global IP

### ISSUE THREAD

**Issue by sasam3l4** [wazuh/wazuh#3736]
Is it possible to access wazuh using global ip? 
I want to access it outside the network.
Please help me.

My router is IO DATA
WN-AX2033GR2 

Im using ubuntu 16

thank You.

**Comment by sasam3l4** [comment]
Hi @Zenidd 

Thank you for your reply,
I tried that but I think the problem is in the router itself.

regards,

**Comment by Zenidd** [comment]
Hi again @sasam3l4, 

> I tried that but I think the problem is in the router itself.

What problems have you encountered? Is port forwarding prohibited on your router?

Greetings, Juan Pablo Sáez

**Comment by sasam3l4** [comment]
Hi @Zenidd 

> What problems have you encountered? Is port forwarding prohibited on your router?

Yes, I found out that the router doesnt support port forwading.

**Comment by Zenidd** [comment]
Hi @sasam3l4,

I guess that using a network tunnel service as [Ngrok](https://ngrok.com/docs) can be a good workaround given your situation

[Here](https://j3ssiejjj.blogspot.com/2017/08/how-to-open-port-forwarding-without.html) you have a short guide in which Ngrok is used to access an Apache server from the Internet without using port forwarding.

If you can't access the machine this way, don't hesitate to let us know and we will continue looking for your solution.

Greetings, Juan Pablo Sáez

**Comment by Zenidd** [comment]
Hi again @sasam3l4,

I'm closing this ticket due to inactivity. If you need more help, please don't hesitate to reopen this ticke or open a new one.

If you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.


Greetings, Juan Pablo Sáez
