### ISSUE TITLE
Memory leak in Wazuh module Control in MacOS agents

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#3738]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | WM Control | Agent | Packages/Sources | MacOS |

The control module doesn't free the memory used to store the address of the gateways. It is needed to clear the Hash table before it is removed.

The following operations need to be moved near the clearing of the table
https://github.com/wazuh/wazuh/blob/91de7ca0118f96027805be613937b37a3bb41a83/src/wazuh_modules/wm_control.c#L84
https://github.com/wazuh/wazuh/blob/91de7ca0118f96027805be613937b37a3bb41a83/src/wazuh_modules/wm_control.c#L89

Move to:
https://github.com/wazuh/wazuh/blob/91de7ca0118f96027805be613937b37a3bb41a83/src/wazuh_modules/wm_control.c#L125

**Comment by Skeptor** [comment]
I'm currently working in the branch: https://github.com/wazuh/wazuh/tree/3738-memleak-control-mac
I'm creating a function to free the `gateway` struct and adding to the `OSHash_Free` function of the control module.
I'm compiling with `scan-build` and running the feature with `AddressSanitize`

**Comment by chemamartinez** [comment]
This issue has been solved at https://github.com/wazuh/wazuh/pull/3795
