### ISSUE TITLE
Agent Overview dashboard Not Showing Any Data

### ISSUE THREAD

**Issue by Nrsh1986** [wazuh/wazuh#374]
Hi,

I have installed Wazuh 2.1 v as a single host architecture and I installed the agents and registration too, in Wazuh dashboard agents status showing active but if I select any agents it's not showing any content.

Wazuh-manager collecting the all OSSEC logs and alerts even agents entries also available, I have manually check in server but in the kibana agent dashboard am not getting anything to display.

Even email alert also am not getting. Please help me.

Regards,
Naresh
![dashboard](https://user-images.githubusercontent.com/14367985/35722527-aa3f37ee-081c-11e8-90d0-a5df3d2ae3ee.png)

**Comment by havidarou** [comment]
Hi @Nrsh1986 ,

sorry you are having problems.

There are some things you can check:

 - Change the time filter, sometimes there aren't alerts in the selected time range. 
 - Go to Kibana discover tab (left menu, first choice) and check alerts from that agent are being shown in Kibana.
 - Go to Overview -> General and check you are getting alerts there too.

On a side note, I highly recommend you to upgrade to our 3.x-6.x version, there are tons of new features and enhancements in almost every part of Wazuh (including a more stable Wazuh app plugin for Kibana).

Hope that helps.

Regards.

**Comment by Nrsh1986** [comment]
Hi havidarou,

1. I have changed the time filter as well am not getting any contents.
2. In discovery tab I selected the wazuh-alerts but it's showing the local alerts, not clients machine alerts 
3. In wazuh-manager -> I check the alerts.json logs it's collecting all records from the clients but not displaying in the dashboard and agents dashboards also

**Comment by havidarou** [comment]
Hi @Nrsh1986 ,

if you are getting local alerts in the discover tab, but not client machine alerts it is really weird the are in fact in the alert.json, cause it would mean that logstash is just reading some lines.

How are you searching in the discover tab for an specific agent alerts?

Regards.

**Comment by JuanjiJG** [comment]
Hello @Nrsh1986,

It's been more than a month since the last response from our team to this issue, so we'll proceed to close it. Don't hesitate to open a new one if you have questions or problems about Wazuh or the Wazuh app.

Regards,
Juanjo
