### ISSUE TITLE
File integrity monitoring Cannot use regular expressions in the path

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#3742]
|Wazuh version:3.9.2-1
|Component: Wazuh-manager
|Install type:Manager
|Install method:Packages
|Platform|CentOS 7.5

Hello，I just want know if File integrity monitoring Could use regular expressions in the path?

For example,

I want to monitor this file

/home/testa/.ssh/authorized_keys
/home/testb/.ssh/authorized_keys
/home/testc/.ssh/authorized_keys

As you can see,this is  users's authorized_keys file,I wish I can  receive  the  warning if  these files are changed.

So,I edited the ossec.conf , use regular expressions to monitor this path
  
`     <directories check_all="yes">/home/.*/.ssh/authorized_keys</directories>`

![image](https://user-images.githubusercontent.com/15324125/61838803-9bf3aa00-aebd-11e9-886d-5ca1eb986c43.png)

Then,I  restart the wazuh-manager,and try to modify agent's authorized_keys several times in 2 days.But there is no warning and log.

So,I just want to know if File integrity monitoring Could use regular expressions in the path?If I can't monitor these files with this method.How can I monitor these files with FIM?

I want to receive your reply soon.

Best regard.

**Comment by Lopuiz** [comment]
Hello @xufengnian 

Unfortunately, regex is not allowed.
If they all have the same name you can try this setting:
```xml
<directories realtime="yes" check_all="yes" restrict="authorized_keys$">/home/lopezziur/testing</directories>
```
You will only receive alerts that end with the name that appears in the `restrict` option.

Best regards,
Eva

**Comment by xufengnian** [comment]
Thank you very much,your reply help me a lot!
