### ISSUE TITLE
Issue for update ruleset + Issue on kibana interface

### ISSUE THREAD

**Issue by eowin** [wazuh/wazuh#3751]
Wazuh Version : 3.9.3
Elasticsearch version : 7.2.0
OS: Debian 9
Installed from apt

------------------------------------------
Hi guys,

I encounter 2 Issues, but I dunno actually if it's a bug or if this come from me :

1. My first issue is with the command to update ruleset, I get the following error : 

```
### Wazuh ruleset ###
ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.9.x. Found version v3.9.2
```
I don't understand this message, I checked my wazuh-manager which is on version 3.9.3 :

```
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.9.3"
REVISION="3929"
DATE="Wed Jul 17 12:13:50 CEST 2019"
TYPE="server"
```
For the wazuh api i'm not sur where can I get the information, but normally that should be 3.9.3 too.

How can I solve that ?

------

2. My second Issue, is on kibana, when I go on Management and Status, a message appear on the bottom right of the screen with a code error 1005, I tried to reproduce it from command line with a curl and I get this message : 

`{"error":1005,"message":"Error reading file"}[10:43:02]`

The message is not clear, because it doesn't say what is the file which is concerned.

Do you know how can I solve it ? 

Regards

**Comment by Zenidd** [comment]
Hi @eowin,

About your first issue:

The problem was due to an outdated `VERSION` file on our `stable` ruleset branch. 

- Out-of-date content:
```
RULESET_VERSION="v3.9.2"
REVISION="3918"
```

- has been replaced by the correct content:

```
RULESET_VERSION="v3.9.3"
REVISION="3921"
```

Running `/var/ossec/bin/update_ruleset` should be error-free now.

Please, let me know if it helps. Greetings, 

Juan Pablo Sáez

**Comment by MrMonkeyMonk** [comment]
I'm having the same ruleset issue, and running/rerunning /var/ossec/bin/update_ruleset still fails.

Note the expected version is 3.9.x , while the found version is 3.9.3.

**Comment by Zenidd** [comment]
Hi @MrMonkeyMonk,

The problem was due again to an outdated VERSION file on our `stable` ruleset branch. Running /var/ossec/bin/update_ruleset should be error-free now.

Thank you very much for letting us know, this way we have been able to solve it quickly. 

Greetings, Juan Pablo Sáez

**Comment by eowin** [comment]
HI @Zenidd 

Thanks for your answer :) my 2 Issues seems to be solved ! :)

So I close this ticket 

Thanks again !
