### ISSUE TITLE
SCA policies list folder empty when remote upgrading the agent

### ISSUE THREAD

**Issue by carlocas** [wazuh/wazuh#3753]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-rev | upgrade_agents | Manager/Agent | Packages | Linux |

Hi team:

While upgrading the agent with `upgrade_agents` I notify that the folder of the SCA politicies, `var/ossec/ruleset/sca` is empty. But if you upgrade the agent directly by sources is not. 

I reproduce the error with wazuh-3.8, upgrading the agent with `upgrade_agents`. The content of the folder is the next:

```
ls -la /var/ossec/ruleset/sca/
total 0
drwxr-x---. 2 root ossec  6 jul 26 10:21 .
drwxr-x---. 3 root ossec 17 jul 26 10:21 ..
```
While another machine with the same agent upgrade by sources show:
```
ls -la /var/ossec/ruleset/sca/
total 88
drwxr-x---. 2 root ossec   120 jul 26 09:26 .
drwxr-x---. 3 root ossec    17 jul 26 09:02 ..
-rw-r-----. 1 root ossec 60289 jul 26 09:26 cis_rhel7_linux_rcl.yml
-rw-r-----. 1 root ossec 11622 jul 26 09:26 system_audit_pw.yml
-rw-r-----. 1 root ossec  4189 jul 26 09:26 system_audit_rcl.yml
-rw-r-----. 1 root ossec  5635 jul 26 09:26 system_audit_ssh.yml
```
This issue was reported in the Wazuh mailing list: [https://groups.google.com/forum/?hl=en#!topic/wazuh/NrOmnW5cb2E](url)

Best regards,

Carlos

**Comment by chemamartinez** [comment]
Done at #3775 and [#249](https://github.com/wazuh/wazuh-packages/pull/249). GJ @carlocas.
