### ISSUE TITLE
Wazuh Windows agent does not undo active responses when restarted, but instead makes them permanent.

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#376]
At least on Windows Server 2016 running Wazuh Agent 3.1.0, when a win_route-null active response is triggered and a specific IP address shows up with a persistent null route in the routing table, if I restart the Wazuh agent service before the stateful active response times out, it is not undone.  Neither is the entry removed from the routing table nor does a "delete" entry in appear in the active-responses log file on the agent indicating the removal was attempted. Worst of all, once the Windows Wazuh service is restarted, it appears **Wazuh completely loses state related to the still-active active response**, because after the service restart, it never automatically deletes the null route entry, even long after the timeout period or after a reboot.  If I don't restart the service, Windows times out and undoes active responses just fine.

On Linux agents I observe that "ossec-control restart" always backs out any stateful active responses that are currently in effect, so I presume this is a problem.

**Comment by bah07** [comment]
Hi @branchnetconsulting 

Thank you very much for reporting this issue! We have fixed it, you can see it in [#563](https://github.com/wazuh/wazuh/pull/563)

Best regards.
