### ISSUE TITLE
maild fails to properly read alerts.json

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#3762]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-3929| ossec-maild | Manager | Packages | - |

### Issue
If no `email_log_source` is specified (so by default `maild` uses `alerts.json`) some alerts with `rule.mail=true` are not sent. Specifically alerts from the **Windows EventChannel**, **SCA** or **vulnerability-detector** are not sent (it is likely that other families of rules are affected as well). 

### Steps to reproduce

1. Configure email alerts `<email_notification>yes</email_notification>` along with SMTP related settings.
2. Set `<email_alert_level>7</email_alert_level>` in the `alerts` section (for example)
3. Restart the manager
4. Monitor the `alerts.json` file to see which alerts would trigger an email:
`tail -f /var/ossec/logs/alerts.json | grep 'mail"=true'`
5. Either wait until an `sca` or `vulnerability-detector` scan generates alerts and see no emails are sent. Alternatively generate events in a Windows agent, for example by adding a new account.

Note that alerts for agents being restarted, syscheck, rootcheck and a simple custom rule will send alerts without issue.

### Workaround
This seems to only affect when the log source is the alerts.json file, so setting `<email_log_source>alerts.log</email_log_source>` in the `<global>` section of the `/var/ossec/etc/ossec.conf` file will work around this issue. For this `<alerts_log>yes</alerts_log>` is also necessary.

This will also not affect logs from windows collected via the classic `eventlog` instead of the `eventchannel`, so as a lesser workaround the configuration of windows agents may be changed.

### Additional request
More debugging information for the mail daemon and an internal option to enable debugging. Hijacking `ossec-maild` (by killing it and starting it as `ossec-maild -ddf`) only provided information when an email was to be sent and not what it decides regarding each alert.

**Comment by DaveVG1** [comment]
It seems like when `email_log_source` is `alerts.json` it's expecting the alert to have a `full_log` field which not always happen. If the alert doesn't have the `full_log` field the email is not sent as seen in:

I've been testing it and I think this PR fix this: https://github.com/wazuh/wazuh/pull/3174
I'm going to test it deeper anyway but the alerts seem to be being emailed correctly.

**Comment by chemamartinez** [comment]
Hi team, the fix has already been merged (#3174).

Regards.
