### ISSUE TITLE
Feature request: allow configuration verification to accept a path

### ISSUE THREAD

**Issue by curiositycasualty** [wazuh/wazuh#3781]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | - | Manager/Agent | Packages | Ubuntu 18.04 |

With the exception of `verify-agent-conf`'s `-f` flag, none of the methods described in the [Verifying Configuration docs](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/verifying-configuration.html) accept a file path to a of an OSSEC conf file to verify.

This makes writing configuration management for Wazuh more difficult as most config. management tools will "stage" changes to a config file (before writing them to their final destination) and perform verification on the *staged* copy only. This seems like a reasonable request because determination of the particular "flavor" of config file can be deemed from its `xml` contents (`ossec_config`, `agent_config`, etc.) regardless of filename or file path.

It would look something like this (following the doc for `Wodles`):
```
sudo /var/ossec/bin/wazuh-modulesd -t /tmp/ossec.conf_temp
```

This would lend itself to use in (off the top of my head) [chef](https://docs.chef.io/resource_file.html#properties):
```
edit_resource(:file, "/var/ossec/etc/ossec.conf") do
  ...
  verify "/var/ossec/bin/wazuh-modulesd -t %{path}"
  ...
end
```

and [salt](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.managed):
```
/var/ossec/etc/ossec.conf:
  file.managed:
    ...
    - check_cmd: /var/ossec/bin/wazuh-modulesd -t
    ...
```

**Comment by vikman90** [comment]
Hi @curiositycasualty,

Agree, we need this option. In fact, it exists on some components like Logcollector, Syscheckd or Agentd (`-c`):

```
/var/ossec/bin/ossec-logcollector -t -c /tmp/ossec.conf_temp
```

However, some other daemons, like Modulesd, miss it.

Let us take a look on this and schedule this issue for a version.

Thank you very much for your feedback.
Best regards.

**Comment by curiositycasualty** [comment]
Closing own stale issues.
