### ISSUE TITLE
Syscollector error: sys_hw_windows(): Serial Number not available in SMBIOS firmware table

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3799]
|Wazuh version|Component|Install type|Platform|Instance type|
|---|---|---|---|---|
| 3.9.3 | Syscollector | Agent | Windows Server 2019 | AWS t2.medium

Syscollector is printing this error:

> 2019/08/02 12:31:46 wazuh-modulesd:syscollector: ERROR: At sys_hw_windows(): Serial Number not available in SMBIOS firmware table.

- [x] Investigate the cause of this error.
- [x] If this condition is expectable, convert the error into debug log. https://github.com/wazuh/wazuh/commit/fd507ba160996e05eaad631eacb5e37aec7a1912

**Comment by chemamartinez** [comment]
In case it helps, I have always seen this behavior in AWS instances. Otherwise, when running Syscollector in my local VMs (which no have Serial number as well) no errors appear, the Serial Number value is `None`.
