### ISSUE TITLE
Vulnerability Detector for debian 10

### ISSUE THREAD

**Issue by oleg9301** [wazuh/wazuh#3802]
Hello!
I install debian 10 and don't see any support in wazuh src for debian buster oval
https://www.debian.org/security/oval/oval-definitions-buster.xml
Do you have any plans to support buster?

**Comment by Zenidd** [comment]
Hi @oleg9301,

Currently, Wazuh does not support the OVAL configuration needed for Debian 10 Buster. This information is found in the [Vulnerability detector compatibility matrix](https://documentation.wazuh.com/3.x/user-manual/capabilities/vulnerability-detection.html#compatibility-matrix).

Let's use this issue to track progress on this task. Thank you very much for giving visibility to this necessary enhancement to Wazuh project.

Greetings, Juan Pablo Sáez

**Comment by oleg9301** [comment]
Any news yet?

**Comment by crolopez** [comment]
Hi,

This feature does not have a release date at the moment. We are currently focused on the support for Windows agents (https://github.com/wazuh/wazuh/issues/2430).

We will announce in this issue when support for Debian 10 is implemented.

Best regards.

**Comment by aderumier** [comment]
Hi,

It seem that schema don't have change between debian 9 and debian 10,
for vuls.io for example, debian 10 is working out of the box without any change
https://github.com/future-architect/vuls/issues/844

I'm going to test it with wazuh, adding buster in wm_vuln_detector.c

**Comment by crolopez** [comment]
Hi @oleg9301,

The support for Debian 10 has been merged and will be released in the next release (3.11.0).

Thanks to @aderumier for its contribution.

Best regards.
