### ISSUE TITLE
Limit commit interval in Wazuh DB

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3803]
|Wazuh version|Component|Install type|Branch|
|---|---|---|---|
| 3.2.0+ | Wazuh DB | Manager |[3.10-wdb-commit-3803](https://github.com/wazuh/wazuh/compare/3.10...3.10-wdb-commit-3803)|

Wazuh DB can handle up to `wazuh_db.open_db_limit` databases in transaction mode (caching operations). Databases that have not been updated within `wazuh_db.commit_time` seconds get commited so the changes are sorted and saved into disk.

If the system requires opening more than `wazuh_db.open_db_limit`, Wazuh DB commits and closes the oldest ones, if they are not being used at the time they are checked.

## Hazard

If the system handles less than `wazuh_db.open_db_limit` databases and there is never a delay of more than `wazuh_db.commit_time` seconds between queries, insertions could be cached permanently.

This may cause the manager to take an indefinite time to stop.

## Fix

`wazuh_db.commit_time` shall mean the time to commit a transaction regardless the time since elapsed since the last query to the database.

### Drawbacks

This change may impact the performance of Wazuh DB and Analysisd for databases that run many insertions.

**Comment by vikman90** [comment]
## Configuration changes

1. `wazuh_db.commit_time` becomes `wazuh_db.commit_time_min`.
2. New option `wazuh_db.commit_time_max`

|Option|Range|Default|Description|
|---|---|---|---|
|`wazuh_db.commit_time_min`|`1`..`3600`|`10`|Minimum time to commit a DB.|
|`wazuh_db.commit_time_max`|`1`..`3600`|`60`|Maximum time to commit a DB.|

### Automatic DB committing

Wazuh DB is continuously iterating down the databases opened. For each database that has an active transaction, Wazuh DB closes it if at least one of the following conditions met:

1. More than `wazuh_db.commit_time_min` seconds elapsed since the last query to that DB.
2. More than `wazuh_db.commit_time_max` seconds elapsed since the transaction began.

**Comment by jesuslinares** [comment]
Hi team,

I had an environment which was using around 25GB in `/var/osssec/queue/db` with only ~40 agents. After checking the files, I see that the biggest ones were `.db-shm` and `.db-wal`.

So, I kill `wazuh-db` (it last less than 1 second) and started it again. The result: only 88MB.

I think the proposed change is right: commit every 10 seconds if the DB is no in use, and commit after 60 seconds if it was not possible previously. This will prevent other processes - `analysisd` from accessing the `DB`, so I think we must understand the factors that impact in the commit time to be sure that other processes will not be blocked for a long time in some scenarios.

**Comment by vikman90** [comment]
Thank you @jesuslinares.

On the other hand, I saw that Wazuh DB takes less than one second to commit a database with 1 million pending insertions.

This makes me think that forcing one commit per minute will produce no significant overhead.

**Comment by jesuslinares** [comment]
Sounds good (It would be better with a hardware reference).

Could we add a warning log if the commit process is longer than 2 (?) seconds?. In that way, I can monitor if everything is working as expected.

**Comment by vikman90** [comment]
Sure!

**Comment by vikman90** [comment]
This bran has been merged into [fix-syscheck-integritydb-sync](https://github.com/wazuh/wazuh/tree/fix-syscheck-integritydb-sync) and [fix-syscheck-integritydb](https://github.com/wazuh/wazuh/tree/fix-syscheck-integritydb).

Issue: #3319 (FIM rework).

**Comment by vikman90** [comment]
Closing this issue as it's already merged into branch for issue #3319.
