### ISSUE TITLE
Monitor File and Folder Permissions in Windows

### ISSUE THREAD

**Issue by perfecthoogie** [wazuh/wazuh#3808]
Afternoon all, 

I wonder if you could assit, im looking to monitor any permissions changes to files and folders on our windows file servers and wondered if it was possible using the syscheck function on ossec ? 

I dont want to monitor changes to a file itself or any modifications or file creations i just want to monitor any changes to permissions on a whole file system so C:/ > down.

i figure it would be some a modification to the check_all="yes" part of the below but im unsure

directories check_all="yes" recursion_level="3">C:\</directories

many thanks for your assitance.

**Comment by perfecthoogie** [comment]
Appologoies for the delayed response my end, thats great thank you that is now working with desired effects. 

many thanks for your assistance

**Comment by Zenidd** [comment]
Hi again @perfecthoogie,

I'm glad you got the tuning you needed! I'm closing this issue, please, do not hesitate to reopen this issue or open a new one if you need our help again.

Also, if you want to chat with us directly, please join Slack: https://wazuh.com/community/join-us-on-slack.

We will happy to help you in the Community channel.

Best regards, Juan Pablo Sáez
