### ISSUE TITLE
"ossec-control enable debug" can't be reverted with "ossec-control disable debug"

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#3809]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-3929 | Wazuh daemons | Manager | Packages| CentOS-7  |

Hi team,

Seems like the `ossec-control` binary for debug mode is broken. If you enable it, there is no way to disable it.

![image](https://user-images.githubusercontent.com/30299229/62639084-14874b80-b93f-11e9-8eec-4e18f019cf07.png)
![image](https://user-images.githubusercontent.com/30299229/62639182-47c9da80-b93f-11e9-8565-85a23fcb9dee.png)

I also tried with `ossec-control restart` but it doesn't solve the issue.

**Steps to reproduce**
- Introduce the command `/var/ossec/bin/ossec-control enable debug`. 
- Check daemons with `ps aux | grep ossec`. They will show the `-d` option (debug mode).
- Try to disable debug mode.

Regards,
Sergio.

**Comment by sergiospa** [comment]
**Update**
I found a workaround to disable debug mode with `kill -9 <PID>`
![image](https://user-images.githubusercontent.com/30299229/62640534-13a3e900-b942-11e9-964f-06906962a954.png)

**Comment by snaow** [comment]
Hi @sergiospa,

Thanks for the feedback.

Killing the process is not a workaround, is just killing it.
You are starting the daemon manually, which means, next time you use `ossec-control start|restart` or `systemctl start|restart wazuh-manager` will boot all the daemons again in debug mode.

The `enable debug` command writes a flag into the `.process_list` file, which is read later when spawning the daemons.

Here you can read  how it is adding the mentioned flag:

- https://github.com/wazuh/wazuh/blob/master/src/init/ossec-server.sh#L160

You can notice how how it is adding `DEBUG_CLI=-d` in `.process_list` file.

As you mention, `disable debug` command does not work properly, the best workaround  I can think of is to remove `.process_list` file or open it and remove the `DEBUG_CLI` line:

`rm -f /var/ossec/bin/.process_list`

Restart the service to apply:

`/var/ossec/bin/ossec-control restart` / `systemctl restart wazuh-manager`

**Comment by snaow** [comment]
Fixed here: https://github.com/wazuh/wazuh/commit/27cad7ca59c5732ef196cd3f1acf9b23fe85b610

Coming version v3.10 will have the fix applied.
Closing issue, thanks.
