### ISSUE TITLE
Sources installer inclusion error

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#3830]
|Wazuh version|Component|Platform|
|---|---|---|
| 3.9.5 | Sources installer | Linux and macOS |

The source installer shows the following error (it's easy to see it if we run the installer as non-root):

```
  ** Türkçe kurulum için seçin [tr].
  (en/br/cn/de/el/es/fr/hu/it/jp/nl/pl/ru/sr/tr) [en]:
./src/init/init.sh: line 9: ./dist-detect.sh: No such file or directory
```

The critical line was changed by the last time when fixing issue #3309, but such change is not the cause of this error.

## Fix

I think that the correct line is:
```sh
. src/init/dist-detect.sh
```

However, I wonder it that could affect any package building process.

Pinging @wazuh/cicd to ask them help to understand this issue.

**Comment by BraulioV** [comment]
Hi @vikman90,

You can change this line without problems. The `install.sh` is only used to install the vast majority of the files and generate the package after that. To generate the OS-specific files, the `dist-detect.sh` script is used in the post-install script of the packages. 

This means that changing this line won't affect any build process :)

Regards.

**Comment by vikman90** [comment]
Closing this issue as PR https://github.com/wazuh/wazuh/pull/3775 suggests that line is superfluous.
