### ISSUE TITLE
Error reading cluster configuration

### ISSUE THREAD

**Issue by ryan0323** [wazuh/wazuh#3833]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5 | Wazuh Cluster | Manager | Sources | CentOS 7.6.1810(Linux 5.2.7-1.el7.elrepo.x86_64) |

Error:
[root@wazuhmgr01 ~]# curl -u xxx:yyy -k http://127.0.0.1:55000/cluster/status?pretty
{
   "error": 3006,
   "message": "Error reading cluster configuration"
}

Info:
1. No matter wazuh-clusterd is running or not, the error are the same.
[root@wazuhmgr01 ~]# vim /wazuh/ossec/etc/ossec.conf 
  < cluster>
    < name>wazuh< /name>
    < node_name>wazuhmgr01< /node_name>
    < node_type>master< /node_type>
    < key>IftKQnpm1Ip1zTXwnp46yZJRMLjRxCVE< /key>
    < port>1516< /port>
    < bind_addr>172.16.xx.116< /bind_addr>
    < nodes>
        < node>172.16.xx.116< /node>
    < /nodes>
    < hidden>no< /hidden>
    < disabled>no< /disabled>
  < /cluster>

[root@wazuhmgr01 ~]#  /wazuh/ossec/bin/ossec-control status
wazuh-clusterd is running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild is running...
ossec-execd is running...
wazuh-db is running...
ossec-authd is running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...

[root@wazuhmgr01 ~]# curl -u xxx:yyy -k http://127.0.0.1:55000/cluster/nodes?pretty
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "name": "wazuhmgr01",
            "type": "master",
            "version": "3.9.5",
            "ip": "172.16.xx.116"
         }
      ]
   }
}

2.  Error log of Wazuh APP on Kibana: wazuh-api:checkAPI: Error reading cluster configuration
[elk@elkkbn01 share]$ tail /elk/kibana/optimize/wazuh-logs/wazuhapp-plain.log
debug: 2019/08/10 21:59:52: initialize:init: .wazuh (total: 0) / .wazuh-version (success)
debug: 2019/08/10 22:0:0: monitoring:getConfig: There are no Wazuh API entries yet
debug: 2019/08/10 22:0:46: wazuh-api-elastic:getAPIEntries: 0 Wazuh API entries
debug: 2019/08/10 22:0:46: wazuh-api-elastic:getAPIEntries: 0 Wazuh API entries
debug: 2019/08/10 22:0:47: wazuh-api-elastic:getAPIEntries: 0 Wazuh API entries
debug: 2019/08/10 22:1:15: wazuh-api:checkAPI: undefined is valid
debug: 2019/08/10 22:1:15: wazuh-api:checkAPI: undefined credentials are valid
error: 2019/08/10 22:1:16: wazuh-api:checkAPI: Error reading cluster configuration
debug: 2019/08/10 22:15:0: monitoring:getConfig: There are no Wazuh API entries yet
debug: 2019/08/10 22:30:0: monitoring:getConfig: There are no Wazuh API entries yet

[elk@elkkbn01 share]$ curl -u xxx:yyy -k http://172.16.xx.116:55000/cluster/status?pretty
{
   "error": 3006,
   "message": "Error reading cluster configuration"
}
[elk@elkkbn01 share]$ curl -u xxx:yyy -k http://172.16.xx.116:55000/cluster/nodes?pretty
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "name": "wazuhmgr01",
            "type": "master",
            "version": "3.9.5",
            "ip": "172.16.xx.116"
         }
      ]
   }
}

**Comment by AdriiiPRodri** [comment]
Hi @ryan0323,

This question is answered in the following link https://groups.google.com/forum/#!topic/wazuh/PTWpqQxEC2A

Best regards,
Adri
