### ISSUE TITLE
[bug] ossec-syscheckd is always scanning /var/lib/mysql even if in <ignored> or if syscheck is disabled

### ISSUE THREAD

**Issue by selivan** [wazuh/wazuh#3839]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5-1 | ossec-syscheckd | Agent | Packages | Ubuntu Xenial 16.04 LTS  |

Installed from `http://packages.wazuh.com/3.x/apt stable/main`.

After installing waguh-agent and connecting it to wazuh-manager I noticed high CPU (one core) and I/O load by process `ossec-syscheckd`. This machine has a lot of large files in `/var/lib/mysql`.

`lsof -p $(pgrep ossec-syscheckd)` shows that it has opened some large files files in `/var/lib/mysql`.

`strace -p $(pgrep ossec-syscheckd) -f` shows that mysql data files are actually being read.

`<syscheck>` config section had default settings:

```
<syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin,/boot</directories>

    <!-- Files/directories to ignore -->
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <ignore>/sys/kernel/security</ignore>
    <ignore>/sys/kernel/debug</ignore>
    <ignore>/dev/core</ignore>

    <!-- File types to ignore -->
    <ignore type="sregex">^/proc</ignore>
    <ignore type="sregex">.log$|.swp$</ignore>

    <!-- Check the file, but never compute the diff -->
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>
</syscheck>
```

I tried adding `/var/lib/mysql` to exceptions, normal and regexp:
```
    <ignore>/var/lib/mysql</ignore>
    <ignore type="sregex">^/var/lib/mysql</ignore>
```

It did not change this behavior.

Then I tried disabling syscheck completely:

```
<syscheck>
  <disabled>yes</disabled>
```

And yet the behavior didn't change!!!

I am all out of ideas how to stop it.

**Comment by selivan** [comment]
@Zenidd , you were really helpful last time I reported a bug in wazuh-agent, may be you may look into it?

**Comment by selivan** [comment]
After some poking around I have foundm that this behaviour goes off if i disable `<check_sys>` for rootcheck:

```
<rootcheck>
<check_sys>no</check_sys>
```

I suggest it should have ignored list, or ignore files listed to ignore by syscheck.
On servers with large datafies this check consumes a lot of I/O and processor time.

**Comment by DaveVG1** [comment]
Hi @selivan,

This behavior has already been reported by @vilitux in https://github.com/wazuh/wazuh/issues/3790

There's already an `ignore` option in `rootcheck` module (https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/rootcheck.html#ignore)

You should add this to your `rootcheck` configuration:
```
 <ignore type="sregex">^/var/lib/mysql</ignore>
```

If you don't mind, I'm going to give a more detailed answer in the referenced issue on why this happens. Thank you so much for your feedback as it has helped to figure out why this happens. I hope this helps.

Best regards,
David

**Comment by selivan** [comment]
Hi @DaveVG1 ,

Thanks for the reply. I think I can close this issue now.

I suggest adding the list of directories to check explicitly in `<rootcheck>` config section, like with `<syscheck><directories>`. Now you can not guess which directories are checked by rootcheck unless you dig into wazuh sources. A bit unobvious :)

Also about documentation - I think configuration options(`<check_sys>` and like that) are worth mentioning in https://documentation.wazuh.com/3.x/user-manual/capabilities/anomalies-detection/how-it-works.html. Now it is hard to guess which option configures which type of described checks.

**Comment by DaveVG1** [comment]
I just added your considerations about the documentation to the referenced issue. 

Thanks again for your contribution. Really appreciated.

**Comment by selivan** [comment]
Thanks for helping :)
