### ISSUE TITLE
Wazuh manager:3.9.3

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [wazuh/wazuh#3844]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-1 | alert | Manager 3.9.3-1/Agent3.9.3-1 | sources.list | Debian 10 |

Hi:

I have created a new rule:

```
<group name="custom_windows,">
  <rule id="100102" level="10" frequency="6" timeframe="60">
     <if_matched_sid>60122</if_matched_sid>
     <same_user />
     <description> Brute force Windows </description>
     <group>windows,  windows_security, win_authentication_failed,</group>
  </rule>
</group>
```

-no problems executing ossec-logtest
-no problems restarting wazuh-manager
-no more than 8000 events per second in manager
-verified than events 60122 are matching (more than enogh to match the <if_matched_sid>)
-just one manager, no event balancing

But the rule is not triggering any alert.

Im using hydra to perform a brute force attack over my agent using the same user and realice that events 60122 it's there but not my custom rules.
******hydra -t 4 -V -f -l administrador -P password.lst rdp://<ip>******

Also i realice that there it's a rule that must be triggered too in /var/ossec/ruleset/rules/0220-msauth_rules.xm, but it's not triggering

```
<rule id="18152" level="10" frequency="$MS_FREQ" timeframe="240">
    <if_matched_group>win_authentication_failed</if_matched_group>
    <same_source_ip />
    <description>Multiple Windows Logon Failures.</description>
<group>authentication_failures,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_11.4,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
</rule>
```

**Comment by Zenidd** [comment]
Hi @BernaldoPenasAntelo,

The `<same_user />` option in your custom rule is probably causing this behavior.  In [Eventchannel](https://documentation.wazuh.com/3.x/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#monitor-the-windows-event-channel-with-wazuh) events, the `user` value is not decoded. We apologize as this is not mentioned in the Wazuh documentation and it will be included as soon as possible.


This is not a problem since Eventchannel stores the login target user in the `win.eventdata.targetUserName` field. It is also possible to use an arbitrary field for comparison using the [`<field>`](https://documentation.wazuh.com/3.8/user-manual/ruleset/ruleset-xml-syntax/rules.html#field) option. 

Applied to your rule in the example below:
```
<group name="custom_windows,">
  <rule id="100102" level="10" frequency="6" timeframe="60">
     <if_matched_sid>60122</if_matched_sid>
     <same_field>win.eventdata.targetUserName</same_field>
     <description> Brute force Windows </description>
     <group>windows,  windows_security, win_authentication_failed,</group>
  </rule>
</group>
```
Now the hydra brute force attack should trigger your rule. Please, let me know if it helps.
Greetings, Juan Pablo Sáez

**Comment by BernaldoPenasAntelo** [comment]
HI:
Apologizes for the delay.
I have triyed what u suggest but got the same behavior, even when i saw lots of 60122 events.

Best regards.

**Comment by Zenidd** [comment]
Hi again @BernaldoPenasAntelo,

To see what happens when using this rule, I've recreated your environment and released tests with Hydra:

- Windows Server 2016 with Wazuh agent
- Manager with the further rule on `/var/ossec/etc/rules/local_rules.xml`:
```XML
  <rule id="100102" level="10" frequency="6" timeframe="60">
     <if_matched_sid>60122</if_matched_sid>
     <same_field>win.eventdata.targetUserName</same_field>
     <description> Brute force Windows </description>
  </rule>
```

- ` ./hydra -t 4 -V -f -l Administrador -P /home/vagrant/wazuh/password.lst rdp://192.168.75.131  -I`

In addition to 60122 rule ID alerts, I have obtained this new rule alerts: 

```XML
** Alert 1567677543.576522: mail  - local,syslog,sshd,windows,  windows_security, win_authentication_failed,
2019 Sep 05 11:59:03 (SERV2016) 192.168.75.131->EventChannel
Rule: 100102 (level 10) -> ' Brute force Windows '
{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4625","version":"0","level":"0","task":"12544","opcode":"0","keywords":"0x8010000000000000","systemTime":"2019-09-05T09:59:02.260067200Z","eventRecordID":"2043251","processID":"704","threadID":"1368","channel":"Security","computer":"WIN-9DVF24624AG","severityValue":"AUDIT_FAILURE","message":"Error de una cuenta al iniciar sesión."},"eventdata":{"subjectUserSid":"S-1-0-0","subjectLogonId":"0x0","targetUserSid":"S-1-0-0","targetUserName":"Administrador","status":"0xc000006d","failureReason":"%%2313","subStatus":"0xc000006a","logonType":"3","logonProcessName":"NtLmSsp","authenticationPackageName":"NTLM","workstationName":"nanoPill","keyLength":"0","processId":"0x0","ipAddress":"192.168.75.1","ipPort":"0"}}}
win.system.providerName: Microsoft-Windows-Security-Auditing
win.system.providerGuid: {54849625-5478-4994-A5BA-3E3B0328C30D}
win.system.eventID: 4625
win.system.version: 0
win.system.level: 0
win.system.task: 12544
win.system.opcode: 0
win.system.keywords: 0x8010000000000000
win.system.systemTime: 2019-09-05T09:59:02.260067200Z
win.system.eventRecordID: 2043251
win.system.processID: 704
win.system.threadID: 1368
win.system.channel: Security
win.system.computer: WIN-9DVF24624AG
win.system.severityValue: AUDIT_FAILURE
win.system.message: Error de una cuenta al iniciar sesión.
win.eventdata.subjectUserSid: S-1-0-0
win.eventdata.subjectLogonId: 0x0
win.eventdata.targetUserSid: S-1-0-0
win.eventdata.targetUserName: Administrador
win.eventdata.status: 0xc000006d
win.eventdata.failureReason: %%2313
win.eventdata.subStatus: 0xc000006a
win.eventdata.logonType: 3
win.eventdata.logonProcessName: NtLmSsp
win.eventdata.authenticationPackageName: NTLM
win.eventdata.workstationName: nanoPill
win.eventdata.keyLength: 0
win.eventdata.processId: 0x0
win.eventdata.ipAddress: 192.168.75.1
win.eventdata.ipPort: 0
```


Could you make sure once again that you don't get alerts on the new rule? Please, try this version without timeframe option. 

```XML
  <rule id="100102" level="10" frequency="6">
     <if_matched_sid>60122</if_matched_sid>
     <same_field>win.eventdata.targetUserName</same_field>
     <description> Brute force Windows </description>
  </rule>
```

If you give me some example alerts maybe I can see what's going on.

I hope it helps. Greetings, 

Juan Pablo Sáez

**Comment by BernaldoPenasAntelo** [comment]
Hi:
I understand a little bit more of my issue but still have no response.
New data on this:

-As you say the new rule it's working fine, i can see that it's triggering in alerts.log.

My actual problem it's that i have elasticsearch installed and wazuh plugin in kibana and new event didn't appear in discover.

I dont know how can i use ossec-logtest command with windows events in order to debug this issue, with linux it's easy just coping and pasting raw text log.

Could be some sort of problem with the parsing of alert.json ????
This is the output i get from:

#cat /var/ossec/logs/alerts/alerts.json | grep "\"100102\"" | tail -n1

`

{"timestamp":"2019-09-05T13:16:31.633+0200",
"rule":{"level":10,
        "description":" Brute force Windows  from same ip",
		"id":"100102",
		"frequency":6,
        "firedtimes":2642,
		"mail":false,
        "groups":[
		          "Custom windows rules",
				  "windows",
				  "  windows_security",
				  " win_authentication_failed"]
	    },
"agent":{
         "id":"003",
		 "name":"windows2012",
		 "ip":"192.168.6.59"
		 },
"manager":{
           "name":"CalderaServer"
		   },
"id":"1567682191.128078502",
"previous_output":"{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:29.063126400Z\",\"eventRecordID\":\"225024\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"}
,\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"}}}\n{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D
}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:28.984996500Z\",\"eventRecordID\":\"225023\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"
},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"
}
}
}\n{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D
}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:28.859996200Z\",\"eventRecordID\":\"225022\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"
},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"
}
}
}\n{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D
}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:28.828751600Z\",\"eventRecordID\":\"225021\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"
},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"
}
}
}\n{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D
}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:28.813125300Z\",\"eventRecordID\":\"225020\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"
},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"
}
}
}
","full_log":"{\"win\":{\"system\":{\"providerName\":\"Microsoft-Windows-Security-Auditing\",\"providerGuid\":\"{54849625-5478-4994-A5BA-3E3B0328C30D
}\",\"eventID\":\"4625\",\"version\":\"0\",\"level\":\"0\",\"task\":\"12544\",\"opcode\":\"0\",\"keywords\":\"0x8010000000000000\",\"systemTime\":\"2019-09-05T11:16:29.078750800Z\",\"eventRecordID\":\"225025\",\"processID\":\"468\",\"threadID\":\"2504\",\"channel\":\"Security\",\"computer\":\"WIN-AIEOJTT8UG6\",\"severityValue\":\"AUDIT_FAILURE\",\"message\":\"Error de una cuenta al iniciar sesión.\"
},\"eventdata\":{\"subjectUserSid\":\"S-1-0-0\",\"subjectLogonId\":\"0x0\",\"targetUserSid\":\"S-1-0-0\",\"targetUserName\":\"Administrador\",\"status\":\"0xc000006d\",\"failureReason\":\"%%2313\",\"subStatus\":\"0xc000006a\",\"logonType\":\"3\",\"logonProcessName\":\"NtLmSsp\",\"authenticationPackageName\":\"NTLM\",\"workstationName\":\"kali\",\"keyLength\":\"0\",\"processId\":\"0x0\"
}
}
}","decoder":{"name":"windows_eventchannel"},"data":{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D
}","eventID":"4625","version":"0","level":"0","task":"12544","opcode":"0","keywords":"0x8010000000000000","systemTime":"2019-09-05T11:16:29.078750800Z","eventRecordID":"225025","processID":"468","threadID":"2504","channel":"Security","computer":"WIN-AIEOJTT8UG6","severityValue":"AUDIT_FAILURE","message":"Error de una cuenta al iniciar sesión."
},"eventdata":{"subjectUserSid":"S-1-0-0","subjectLogonId":"0x0","targetUserSid":"S-1-0-0","targetUserName":"Administrador","status":"0xc000006d","failureReason":"%%2313","subStatus":"0xc000006a","logonType":"3","logonProcessName":"NtLmSsp","authenticationPackageName":"NTLM","workstationName":"kali","keyLength":"0","processId":"0x0"}}},"location":"EventChannel"}

`

**Comment by BernaldoPenasAntelo** [comment]
Forgot about the bad formatting, the format it's ok ...
I think it's related with the decoder

**Comment by BernaldoPenasAntelo** [comment]
Hi:

I found the problem i've updated wazuh-manager and agent to 3.9.5 and filebeat to 7.3.0 following documentation:

https://documentation.wazuh.com/3.9/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.html?highlight=filebeat

now the filebeat it's using wazuh module and it works perfect.
