### ISSUE TITLE
Error while removing old SCA files in a fresh install

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#3849]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0-31006 | Wazuh component | Manager/Agent | Sources | Any UNIX |

Hi team,

In an OpenSUSE 15 host, we detected this error when installing the agent using the source code from [3249-refactor-SCA-internal-logic-engine](https://github.com/wazuh/wazuh/tree/3249-refactor-SCA-internal-logic-engine).
```
Wait for success...
success
Removing old SCA policies...
rm: cannot remove '/var/ossec/ruleset/sca/*': No such file or directory
Installing SCA policies...
SCAP security policies not available for this OS version.
```

In addition, there's a typo in `SCAP security policies not available for this OS version.` => `SCAP security policies are not available for this OS version.`

This issue is related to the development of this https://github.com/wazuh/wazuh/issues/3249 one.

Regards

**Comment by chemamartinez** [comment]
Fixed: https://github.com/wazuh/wazuh/commit/a3a0517085b69563fb7e2cfada5ef9d907d43d77
