### ISSUE TITLE
windows agent ,I uninstall it , and install again ,but it's not work

### ISSUE THREAD

**Issue by freegit9527** [wazuh/wazuh#3858]
C:\Program Files (x86)\ossec-agent>agent-auth.exe  -m  192.168.164.101  -P  "TopSecret"
2019/08/19 16:22:24 agent-auth: INFO: Started (pid: 8808).
2019/08/19 16:22:24 agent-auth: ERROR: SSL error (1). Connection refused by the manager. Maybe the port specified is incorrect. Exiting.
8812:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1399:SSL alert number 40

**Comment by freegit9527** [comment]
C:\Program Files (x86)\ossec-agent>agent-auth.exe  -m  192.168.164.101  -P  "TopSecret"  -d
2019/08/19 16:28:06 agent-auth[8696] main-client.c:241 at main(): DEBUG: Starting ...
2019/08/19 16:28:06 agent-auth[8696] main-client.c:271 at main(): INFO: Started (pid: 8696).
2019/08/19 16:28:06 agent-auth[8696] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2019/08/19 16:28:06 agent-auth[8696] main-client.c:349 at main(): ERROR: SSL error (1). Connection refused by the manager. Maybe the port specified is incorrect. Exiting.
8504:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1399:SSL alert number 40

**Comment by Zenidd** [comment]
Hi @freegit9527,

first of all, sorry for the late reply

while I recreate your environment to know what causes the error, could you give me a little more information?

- What manager and agent version are you using?
- Have you modified the `ossec-authd` configuration block on `ossec.conf`? The target port or some other parameter.
- Do others [agent registration methods](https://documentation.wazuh.com/current/user-manual/registering/index.html) work for you?


Greetings, Juan Pablo Sáez

**Comment by freegit9527** [comment]
I  have solved  this  problem,when I disabled ipv6
