### ISSUE TITLE
Add process to open ports in syscollector (Linux)

### ISSUE THREAD

**Issue by brantcolemanthis** [wazuh/wazuh#3859]
Why in Linux we don't have this field? Are you going to add them?
![image](https://user-images.githubusercontent.com/25495660/63267329-75e1df80-c29a-11e9-8544-a6a2b684c8ba.png)

Related issues:
- [ ] https://github.com/wazuh/wazuh-kibana-app/issues/5529

**Comment by chemamartinez** [comment]
Hi @brantcolemanthis,

We are aware of this lack of functionality for the Linux port inventory. Actually, it is reported at https://github.com/wazuh/wazuh/issues/535.

We are working on improving the performance of this module every version, for example, for 3.11 it will be included support for the port and process inventory for MAC OS X.
- https://github.com/wazuh/wazuh/issues/3296
- https://github.com/wazuh/wazuh/issues/3295

We hope it will be available ASAP. Thank you for your feedback.

**Comment by MiguelazoDS** [comment]
# Analysis 

## Environment 

- Ubuntu Jammy: Manager - Wazuh 4.3.8

## Description

### Introduction

Considering some examples, let's say port 22 and port 53 which are used by sshd and domain name resolution respectively, we can see that CLI tools successfully report the port 

- netstat 
![image](https://user-images.githubusercontent.com/13010397/190710128-dfb3b477-0a85-4957-9717-0910f707a819.png)

- fuser
![image](https://user-images.githubusercontent.com/13010397/190710160-2aaf454c-4c15-4065-89e7-1d2c240f73f9.png)

- lsof
![image](https://user-images.githubusercontent.com/13010397/190710183-760a3d8c-c627-49ce-a30c-64310bcdf9eb.png)

Considering the information from the sys_ports inventory we can see that the port 22 with inode 23658 (for TCP) is used by the sshd process (PID 809)

#### Port 22 

<details>
<summary>Click to expand</summary>

```json 
[
    {
        "scan_id": 0,
        "scan_time": "2022/09/16 13:06:02",
        "protocol": "tcp6",
        "local_ip": "::",
        "local_port": 22,
        "remote_ip": "::",
        "remote_port": 0,
        "tx_queue": 0,
        "rx_queue": 0,
        "inode": 23660,
        "state": "listening",
        "PID": 0,
        "checksum": "562778431cdc8e127fad41f9d8d36b5829c880f9",
        "item_id": "2360cb04d9e37bfb3950b3adc024988f8c2672d8"
    },
    {
        "scan_id": 0,
        "scan_time": "2022/09/16 13:06:03",
        "protocol": "tcp",
        "local_ip": "0.0.0.0",
        "local_port": 22,
        "remote_ip": "0.0.0.0",
        "remote_port": 0,
        "tx_queue": 0,
        "rx_queue": 0,
        "inode": 23658,
        "state": "listening",
        "PID": 0,
        "checksum": "f9e43de68484927007fc65e04eb0bed4343a36f9",
        "item_id": "df7fe6dd6c89e3fcbbdc3607719146adadbbbea7"
    }
]
```

</details>

#### Port 53

<details>
<summary>Click to expand</summary>

```json
[
    {
        "scan_id": 0,
        "scan_time": "2022/09/16 13:06:02",
        "protocol": "udp",
        "local_ip": "127.0.0.53",
        "local_port": 53,
        "remote_ip": "0.0.0.0",
        "remote_port": 0,
        "tx_queue": 0,
        "rx_queue": 0,
        "inode": 23581,
        "PID": 0,
        "checksum": "bf68c2400c255f6bc13714713ceb01b049cee2cc",
        "item_id": "1150eb3ecc8ca4af31562d4444234be2bf644204"
    },
    {
        "scan_id": 0,
        "scan_time": "2022/09/16 13:06:03",
        "protocol": "tcp",
        "local_ip": "127.0.0.53",
        "local_port": 53,
        "remote_ip": "0.0.0.0",
        "remote_port": 0,
        "tx_queue": 0,
        "rx_queue": 0,
        "inode": 23582,
        "state": "listening",
        "PID": 0,
        "checksum": "78cdc63f58aeff436ecf7b77f5cf881871df46dc",
        "item_id": "deeaaefc6a9e08392ddc49e7dc5a8c9b0471ef90"
    }
]
```

</details>

### Parse information manually

Currently sys_ports uses the files `/proc/net/{udp,udp6,tcp,tcp6}` to get the inodes of certain ports. 

Once we have the inode number, let's say 23658 (port 22/tcp) we need to find the process ID that has a file descriptor for a socket with that inode number. 

We need to iterate over `/proc/[0-9]*/fd/*` where [0-9]* refers to all PIDs and '*' all file descriptors for that particular process. 

Once we found the PID, the process name can be found by reading the symlink 

![image](https://user-images.githubusercontent.com/13010397/190714446-c67cd09e-de2a-4414-8ead-8c040bd79917.png)

**Note: Although as far as we know the command lines tools follow a similar approach, the manual parsing is considerably slow**

**Comment by MiguelazoDS** [comment]
# Library

The procps library, which is currently in use, seems not to fit completely our needs to get this information. 

The functions openproc() readproc() with this set of flags 

```c
#define PROC_FILLMEM         0x0001 // read statm
#define PROC_FILLCOM         0x0002 // alloc and fill in `cmdline'
#define PROC_FILLENV         0x0004 // alloc and fill in `environ'
#define PROC_FILLUSR         0x0008 // resolve user id number -> user name
#define PROC_FILLGRP         0x0010 // resolve group id number -> group name
#define PROC_FILLSTATUS      0x0020 // read status
#define PROC_FILLSTAT        0x0040 // read stat
#define PROC_FILLARG         0x0100 // alloc and fill in `cmdline'
#define PROC_FILLCGROUP      0x0200 // alloc and fill in `cgroup`
#define PROC_FILLSUPGRP      0x0400 // resolve supplementary group id -> group name
#define PROC_FILLOOM         0x0800 // fill in proc_t oom_score and oom_adj
#define PROC_FILLNS          0x8000 // fill in proc_t namespace information
#define PROC_FILLSYSTEMD    0x80000 // fill in proc_t systemd information
#define PROC_FILL_LXC      0x800000 // fill in proc_t lxcname, if possible
```

doesn't populate the struct `proc_t` with information about file descriptors, which let us without options to get the socket and the port related to a specific process.

**Comment by MiguelazoDS** [comment]
## Findings 

After implementation, we noticed that for some ports was not possible to get the process information using this approach 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/13010397/192382215-c2a48591-4ae9-4d58-8838-e88ed2f92173.png)

</details>

With some research, we figured out those ports are reserved for RPC. For this specific case, NFS has a kernel module and it is not listed as a regular process,  ergo it has no PID. 

With the help of `rpcinfo -p` we can see some of the ports 

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/13010397/192383140-07722cb0-5faa-4c9e-97d0-fb87a3c5151b.png)

</details>

But we know that all that six ports are related to NFS service by stopping it. The solution of this seems not to be trivial and will require a deeper analysis.

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/13010397/192383399-5b52a628-42cb-4c27-8428-ddd1229003db.png)

</details>

**Comment by Dwordcito** [comment]
It is moved to the product backlog until the status of this issue in the project is To Do.

**Comment by pereyra-m** [comment]
This issue is blocked by: https://github.com/wazuh/wazuh-jenkins/issues/5074

**Comment by MiguelazoDS** [comment]
# Update 05/23/23:

After rebase checks passed.

**Comment by MiguelazoDS** [comment]
# Port information from UI
## Linux

<details>
<summary>Expand</summary>

![2023-06-02_16-27](https://github.com/wazuh/wazuh/assets/13010397/55a44176-a6df-451d-9733-d7e8eda2a940)

</details>

**Note: There's no process name info.**

## Windows

<details>
<summary>Expand</summary>

![2023-06-02_16-28](https://github.com/wazuh/wazuh/assets/13010397/795badcf-75f0-44ad-ada7-eb7e0bd650ae)

</details>

**Note: Since this is port information, I personally would rather see the local port as the first field**
