### ISSUE TITLE
Windows Agent locks files when whodata or realtime is enabled.

### ISSUE THREAD

**Issue by jmmallorq** [wazuh/wazuh#3864]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5 | Syscheck | Agent | Packages | Win Server 2012 R2 Stnd. |

## Issue
Windows Wazuh Agent is locking files when _whodata_ or _realtime_ is enabled. It avoids deleting files or folders even by the Administrator user.
```
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
```

## Steps to reproduce

The `Syscheck` remote configuration is set like below:
```
<agent_config>
<syscheck>
  <directories check_all="yes" whodata="yes">d:\applicationdata</directories>
</syscheck>
</agent_config>
```

The problem can be recreated by extracting a .zip folder at that directory and immediately trying to delete it. Windows displays a popup message notifying the following: 
**"The action cannot be completed because the file is open in Wazuh."**

![error_file_in_use](https://user-images.githubusercontent.com/41509336/63414410-17cd0d80-c3fc-11e9-8d5f-f071c92df92b.png)

In addition, we need to mention that the problem doesn’t occur every time we try to force it, but only some times.

Thanks in advance. Regards.

**Comment by chemamartinez** [comment]
Fixed at #3872.

Thanks, @jmmallorq for reporting it.
