### ISSUE TITLE
scan-build 8 reports new minor defects

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3870]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0-31004 | N/A | N/A | N/A | N/A |

`scan-build` report when building on Linux:

Bug Group | Bug Type | File | Function/Method | Line
-- | -- | -- | -- | --
Logic error | Cast from non-struct type to struct type | wazuh_modules/wm_database.c | wm_inotify_start | 1434
Logic error | Cast from non-struct type to struct type | os_net/os_net.c | OS_GetHost | 521
Logic error | Cast from non-struct type to struct type | rootcheck/os_string.c | os_string | 182
Logic error | Cast from non-struct type to struct type | os_net/os_net.c | OS_GetHost | 526
Logic error | Dereference of null pointer | os_xml/os_xml.c | _xml_sgetc | 52 | 11
Logic error | Potential unintended use of sizeof() on pointer type | syscheckd/syscheck_audit.c | audit_read_events | 1109
Logic error | Use of identical expressions | rootcheck/check_rc_pids.c | loop_all_pids | 250
Memory error | Memory leak | analysisd/rules.c | Rules_OP_ReadRules | 363
Memory error | Memory leak | config/reports-config.c | Read_CReports | 179

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/pull/3887.

**Comment by chemamartinez** [comment]
Merged #3887
