### ISSUE TITLE
agent show 1000?

### ISSUE THREAD

**Issue by xisafe** [wazuh/wazuh#3886]
3.9.5
![image](https://user-images.githubusercontent.com/29724312/63740653-83175380-c8c4-11e9-8a27-335608e88cd1.png)
api:55000/agents

only 500，all1400

**Comment by xisafe** [comment]
"Specified limit exceeds maximum allowed (1000)"

**Comment by davidjiglesias** [comment]
Hello @xisafe,

I will try to help you here. In the first call you are not using limit parameter,and the answer defaults to 500 items being showed. In the second call, the limit of 1299 exceeds the maximum allowed of 1000 items per answer. In this case, if you want to see all 1394 agents you have to use pagination.

First call could be:
/agents?limit=1000

And the second one:
/agents?limit=1000&offset=1000

I hope this helps clarify. Please do not hesitate to contact back if you have any more issues.

**Comment by xisafe** [comment]
Thanks
