### ISSUE TITLE
The windows_audit_interval option should be in whodata block

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#3891]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5 | Syscheck | Manager and agent | Packages and sources | Windows |

There is a sub-block to configure the whodata options in the Syscheck block since 3.7.1 ([\<whodata\>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=startup_healthcheck#whodata)). 

However, this option is only used to configure the whodata mode for Linux. It should also include the configurable parameter for Windows [\<windows_audit_interval\>](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html?highlight=startup_healthcheck#windows-audit-interval).

**Comment by JcabreraC** [comment]
Related issue: https://github.com/wazuh/wazuh/issues/4002
