### ISSUE TITLE
Wazuh API fails operating agent groups after trying to remove hundreds of agents

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#3907]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.x-x | Framework | Manager | Any | Any |

## Description

When trying to unset a high volume of agents from a group, a timeout arises. After that error, any other operations involving agents and groups fail with a 1005 error and the message `Operation not permitted`. The only way to fix it seems to be running the agent operation through command line using the `agent_groups` utility with root privileges.

## Cause

The error is due to a conflict between `remoted` and the Wazuh API. According to the following code, the framework tries to create the multigroup folder manually:
https://github.com/wazuh/wazuh/blob/b3dc8c2fd5f0c9c554bc24537d23a84307d5f3da/framework/wazuh/agent.py#L1476-L1501
Since the API usually runs as `ossec`, it fails the attempt to execute the `chown` or `chmod`, showing an `Operation not permitted` error because those files belongs to `ossecr`.
It is important to note that `remoted` uses the `agent-groups` folder to recreate every 15 seconds the proper multigroup folder hierarchy, so there is a race condition.

## Proposed fix

The quickest way to fix this is removing the manual creation of multigroups, maintaining only the edition of `agent-groups`. This way, `remoted` would be the only one in charge of handling those folders.

However, this is not the optimal solution. To reach the best solution, a daemon should be responsible for managing the groups and multigroups folder hierarchy, accepting a request via socket (or HTTP REST API even better).

This idea should be extended to any other functions handling folder or files manually via framework and delegate these tasks to an unique Wazuh daemon.

**Comment by davidjiglesias** [comment]
Hello team,

I have worked to remove framework handling of `/var/ossec/var/db/multrigroups` files and folders. Now, when the framework is given the task to add or remove agents from a group, it only modifies the files for those agents in `/var/ossec/queue/agent-groups` and `remoted` daemon would be in charge of refreshing the multigroups every 10 seconds.
 
### Manual test procedure
We have a cluster with a worker and 3 agents.

Create group `pciserver`:
```
curl -u foo:bar -k -X PUT "https://127.0.0.1:55000/agents/groups/pciserver?pretty"
{
   "error": 0,
   "data": "Group 'pciserver' created."
}
```
Assign agents `001` and `002` to group `pciserver`
```
curl -u foo:bar -X POST -H "Content-Type:application/json" -d '{"ids":["001","002"]}' "https://127.0.0.1:55000/agents/group/pciserver?pretty" -k
{
   "error": 0,
   "data": {
      "msg": "All selected agents assigned to group pciserver",
      "affected_agents": [
         "001",
         "002"
      ]
   }
}
Create group `fix_test`:
```
curl -u foo:bar -k -X PUT "https://127.0.0.1:55000/agents/groups/fix_test?pretty"
{
   "error": 0,
   "data": "Group 'fix_test' created."
}
```
Assign agents `001` and `003` to group `fix_test`:
```
curl -u foo:bar -X POST -H "Content-Type:application/json" -d '{"ids":["001","003"]}' "https://127.0.0.1:55000/agents/group/fix_test?pretty" -k
{
   "error": 0,
   "data": {
      "msg": "All selected agents assigned to group fix_test",
      "affected_agents": [
         "001",
         "003"
      ]
   }
}
```
We see that the framework only modifies the agent_groups files, and `ossecr`(remoted) creates the multigroups a few seconds after:
```
