### ISSUE TITLE
Windows agent MSI installer: Detect Windows version

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3912]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 | MSI Installer - SCA | Agent | Packages | Windows |

Currently the only policy installed by default in Windows system is the generic one, this should be changed so that the policy files for the specific running OS are installed as well.

**Comment by Skeptor** [comment]
Design
-----
I'm developing this feature based on the behaviour of Unix-based systems installer. The template folder will have a Windows folder with any version of Windows with specific configuration files (For example, the `ossec.conf`) before Windows Vista.

Work
----
Create the folder structure in folder templates and in folder sca and reallocate the files.
Adapt the Windows MSI to install the files automatically depending on the Windows version.
    - Remove the specific install for SCA policies to install every file in the version folder.
    - Move the `ossec-pre6.conf` file to the folders of Windows with versions older than Vista with name `ossec.conf`

**Comment by Skeptor** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/3912-add-templates-msi

Currently working in the JS script to move the files from the Windows version folder (autodetected) to the ruleset/sca folder of the agent

**Comment by Skeptor** [comment]
I'm having troubles with the execution time of the Custom Action that I'm using to move the files. WiX doesn't schedule the script any time after the mark `InstallFinalize` but the directory structure is created after that mark.

I'm currently working on scheduling the script in time.
Also, I'm working in the MSI recollecting the SCA files automatically, no matter what files are inside the version folder, because of wxs files work with the fact that all files are known by the installer.

**Comment by Skeptor** [comment]
Update on the solution
----------
I discard the Javascript solution because it is causing troubles with the scheduling and use the variable path of the SCA policies adds too many difficulties. 
I'm trying to add the policies with the component: CopyFile using wildcards, extracting the version and type from a header (wxi) to match the SCA policies folder. I'm working to ignore the folder that doesn't exist because they are causing the installer to fail

**Comment by Skeptor** [comment]
Work In Progress
---------

I'm working in create a zip with the files for each operative system (SCA policies, templates for ossec.conf,...) to attach it to the MSI.

After that, a script would decompress it and move the SCA files to their destination folder. Also, it would replace the configuration blocks in `.template` files in the `ossec.conf` of the agent.
Then the folder with the zip files will be deleted.

**Comment by DFolchA** [comment]
## Update report

Review https://github.com/wazuh/wazuh/pull/3967 and test changes in that PR.

Start applying changes to later versions and adding the new SCA policies added in wazuh/wazuh-ruleset#776.

**Comment by DFolchA** [comment]
## Update Report

Merge `master` branch into `3912-add-templates-msi`, new working branch: [3912-add-templates-msi-4.3](https://github.com/wazuh/wazuh/tree/3912-add-templates-msi-4.3).

Build new [4.3 packages](https://ci.wazuh.info/job/Packages_builder_win/5897/consoleFull) from development branch:
```
creating: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/
12:37:37   extracting: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/001  
12:37:37   extracting: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/002  
12:37:37   extracting: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/003  
12:37:37   extracting: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/004  
12:37:37    inflating: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/005  
12:37:37    inflating: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/006  
12:37:37    inflating: wazuh-3912-add-templates-msi-4.3/api/test/integration/env/configurations/base/manager/configuration_files/master_only/config/queue/agent-groups/007  
. . . .
. . . .
. . . . 
12:37:37    adding: wazuh-3912-add-templates-msi-4.3/CONTRIBUTORS (deflated 52%)
12:37:37    adding: wazuh-3912-add-templates-msi-4.3/install.sh (deflated 76%)
12:37:37    adding: wazuh-3912-add-templates-msi-4.3/add_localfiles.sh (deflated 40%)
12:37:37  + cp windows_agent_test.sca.zip /shared
12:37:37  
12:37:37  [Pipeline] sh
12:37:37  + mv /mnt/efs/packages/windows_agent_test.sca.zip /home/ec2-user/workspace/Packages_builder_win
12:37:37  [Pipeline] sh
12:37:38  + curl -OL https://raw.githubusercontent.com/wazuh/wazuh-packages/master/windows/generate_wazuh_msi.ps1
12:37:38    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
12:37:38                                   Dload  Upload   Total   Spent    Left  Speed
12:37:38  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2894  100  2894    0     0   176k      0 --:--:-- --:--:-- --:--:--  176k
12:37:38  [Pipeline] }

```

Add new SCA rule changes in https://github.com/wazuh/wazuh-ruleset/pull/776.

**Comment by DFolchA** [comment]
## Update Report

Add new SCA file policies to MSI and start testing packages.

- Change SCA files compressed in zip file
- Change `UnzipVersionFiles.vbs` script 
- Generate new packages

### To Do
- [ ] Test packages

**Comment by DFolchA** [comment]
## Update Report

Test MSI packages and fix problems.

We found that the merge created an outdated version of the wxs file and we need you to update it with the latest changes in master and include the actions for the PR.

**Comment by DFolchA** [comment]
# Update Report

Add Windows Server 2019 and  2016 feeds to the package.

## Test packages:

### 4.1.5 Windows server 2012
![image](https://user-images.githubusercontent.com/19505384/118664341-ad741780-b7f1-11eb-83ed-e4d2ea251b82.png)

### 4.3.0 Windows server 2012

### 4.1.5 Windows server 2016
![image](https://user-images.githubusercontent.com/19505384/118657867-25d7da00-b7ec-11eb-944d-ecad8769665a.png)

### 4.3.0 Windows server 2016
![image](https://user-images.githubusercontent.com/19505384/118680813-56753f00-b7ff-11eb-9598-462b7aea08aa.png)

### 4.1.5 Windows server 2019

### 4.3.0 Windows server 2019

### 4.1.5 Windows 10

### 4.3.0 Windows 10
