### ISSUE TITLE
Index Lifecycle Management for Wazuh ​

### ISSUE THREAD

**Issue by javierescobarcerezo** [wazuh/wazuh#3924]
| Wazuh version | Elastic version     | 
|---------------|---------------------|
| Wazuh 3.9.5   | Elastic stack 7.3.0 | 
## Description
Currently, Wazuh alerts are indexed into Elasticsearch using daily indices but we do not provide any solution for those indices management over time.

Using Index Lifecycle Management policies will allow us to define the lifecycle for an index from the ingestion stage to deletion. Enabling us to optimize the cluster performance and establishing a retention policy for our data.

### Why is it a problem for Elasticsearch cluster?
With the current default configuration, creating two daily indices (monitoring and alerts) with 3 shards per index would generate 2190 active shards after a year. Without the proper management tools, that could cause a cluster failure and performance issues.

### What is an ILM policy?
ILM is Elasticsearch's built-in solution to replace Curator.

An ILM policy allows us to control how indices are handled as they age. It progresses through four primary phases: 

- Hot—​the index is actively being updated and queried.
- Warm—​the index is no longer being updated, but is still being queried.
- Cold—​the index is no longer being updated and is seldom queried. The information still needs to be searchable, but it’s okay if those queries are slower.
- Delete—​the index is no longer needed and can safely be deleted.

It's not needed to define every phase if one is absent ILM will skip it. ILM allows establishing when to move between the phases and what to do with the index when entering that phase.

### Rollover and aliases
One of the ILM capabilities is to automatically perform rollover for hot indices.

When ingesting using an alias rollover allows moving the ingestion flow  to a different index when some conditions are met:
- Rollover by size.
- Rollover by day.
- Rollover by # of documents.

Using rollover is a requirement for environments that ingest high volumes of data per day.

This is the biggest downside of using Wazuh with ILM. It is not possible to configure ILM for Wazuh indices as it is not compatible with our Wazuh Filebeat module.

### Pros and cons
​Pros:
- Setting indices as Warm/read-only, with options to shrink or merge. (X days after index creation). The shrinking/merging time is priority-based, so it wouldn't be performed during Elasticsearch high load periods.
- Automatically manage retention time, by deleting indices X days after creation.
- Improved Elasticseach cluster performance by shards management.

Cons:
- Rollover has conflicts with Wazuh Filebeat module. It also prevents the possibility of indexing previous day's alerts in their corresponding indexes.
- Shrinking configuration doesn't allow setting a condition, like an index size, to determine the target number of shards
- Merging automatically could affect cluster performance during peak ingestion moments.

## Proposal
Based on our experience working with ILM we propose setting an empty policy as default. That would allow our users editing this policy at their will, adapting it to their needs.

This would be an example of an empty policy configuration:

1. Default policy with just a hot phase (`/etc/filebeat/policy.json`):

```json
{
    "policy": {
        "phases": {
            "hot": {
                "min_age": "0ms",
                "actions": {
                    "set_priority": {
                        "priority": 100
                    }
                }
            }
        }
    }
}
```

This policy keeps the way our indices work at the moment.
​
 2. Define the policy name in the index template on `/etc/filebeat/wazuh-template.json`:
```json
{
"order": 0,
"index_patterns": [
    "wazuh-alerts-3.x-*",
    "wazuh-archives-3.x-*"
],
"settings": {
    "index.refresh_interval": "5s",
    "index.number_of_shards": "3",
    "index.number_of_replicas": "0",
    "index.lifecycle.name": "wazuh_policy",
    "index.auto_expand_replicas": "0-1",
    "index.mapping.total_fields.limit": 10000,
    "index.query.default_field": []

    ...
}
```

3. Filebeat configuration file:
```yaml
# Wazuh - Filebeat configuration file
filebeat.modules:
- module: wazuh
    alerts:
        enabled: true
    archives:
        enabled: false
​
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: true
setup.ilm.policy_name: 'wazuh_policy'
setup.ilm.policy_file: '/etc/filebeat/policy.json'
​
# Send events directly to Elasticsearch
output.elasticsearch:
    hosts: ['http://ELASTICSEARCH_IP:9200']
```

We just have to enable ILM and add a policy name and the file where it's stored.
​
*Note: enabling ILM will create a Filebeat index with a default template.*
​
Newly created indices will have the ILM policy and work like always. Filebeat will upload the policy or overwrite it if existed before.
​
Besides, these changes just affect alerts (and archives) indices and not the monitoring ones because those are created by the Wazuh App.

## Testing ILM
Using the above configuration, but a custom policy, we've done some tests, following the progress of the ILM phases.

This policy jump to the next stage every day, change the priority of the index and execute some actions like Shrinking and Freezing. On the third day of creation, the index is deleted.

Test policy:
```json
{
    "policy": {
        "phases": {
            "hot": {
                "actions": {
                    "set_priority": {
                        "priority": 100
                    }
                }
            },
            "warm": {
                "min_age": "1d",
                "actions": {
                    "shrink": {
                        "number_of_shards": 1
                    },
                    "set_priority": {
                        "priority": 50
                    }
                }
            },
            "cold": {
                "min_age": "2d",
                "actions": {
                    "set_priority": {
                        "priority": 0
                    }
                }
            },
            "delete": {
                "min_age": "3d",
                "actions": {
                    "delete": {}
                }
            }
        }
    }
}
```

The tests proved that the indices progressed to the next phase properly and executed the tasks assigned to their phase during times of less activity so as not to affect Elasticsearch's performance, finally being deleted on the third day.

For existing indices, we can apply an ILM policy with the command:
```
PUT /wazuh-alerts-3.x-*/_settings
{  
    "index" : {
       "lifecycle.name" : "my_policy"
    }
}
```

## Conclusion
​We could adapt ILM to Wazuh in two ways. 
We could include the use of ILM policies by default with Wazuh in new installations, including the empty policy. It wouldn't change how our indices work and would let users edit it to suit their needs.
Or we could add this information to our documentation so anyone will be able to implement it, providing examples of custom policies for different scenarios.

**Comment by MiguelCasaresRobles** [comment]
I created the following PR to accomplish this: https://github.com/wazuh/wazuh/pull/3974

Documentation is needed.

**Comment by Born2Bake** [comment]
Hi, is there any progress on that change?

**Comment by PetrVladimirov** [comment]
Hi Team, 
Is there a plan to get it rolled out soon?

**Comment by MiguelCasaresRobles** [comment]
Hello @Born2Bake  and @PetrVladimirov,

Sorry for the late reply.

We did not include it out-of-the-box in Wazuh but we created the following documentation to show how it can be configured: https://wazuh.com/blog/wazuh-index-management/

We are still discussing the best method to include this in Wazuh.

Thank you for your patience. Stay tuned!

Regards,

Miguel Casares

**Comment by PetrVladimirov** [comment]
Hello @MiguelCasaresRobles - thank you for the reply.
The article you mentioned is a great start, but not very flexible for the long-term retention schemas. E.g. the most necessary feature in many the cases is ability to manage the space, i.e. control the size (Rollover by size). So, I'm looking forward to get this PR implemented/documented as a part of Wazuh
