### ISSUE TITLE
verify-agent-conf does not catch syscollector config errors in agent conf that break agents

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#393]
On the Wazuh 3.2 manager I added this to agent.conf
```
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan-on-start>yes</scan-on-start>
    <packages>yes</packages>
  </wodle>
```
which was flawed because ``<scan-on-start>`` should have been ``<scan_on_start>``.

However, when I ran verify-agent-conf on the manager it claimed all was well:

```
root@Wazuh:/var/ossec/etc/shared/linux# verify-agent-conf

verify-agent-conf: Verifying [/var/ossec/etc/shared/default/agent.conf]
verify-agent-conf: OK
```

The result was that after I restarted the manager, it caused all of my Wazuh Linux agents to crash
```
2018/02/14 21:25:41 wazuh-modulesd: ERROR: No such tag 'scan-on-start' at module 'syscollector'.
2018/02/14 21:25:41 wazuh-modulesd: ERROR: (1202): Configuration error at '/var/ossec/etc/shared/agent.conf'. Exiting.
```

Thankfully I only had two Linux agents connected to this manager, because to recover from this after fixing agent.conf on the manager I had to go to each agent and locally delete ``/var/ossec/etc/shared/agent.conf`` and ``/var/ossec/etc/shared/merged.mg`` and then run ``ossec-control restart`` a couple of times, since crashed agents don't pick up new versions of agent.conf on their own, nor do they like to let go of a bad agent.conf once they pick it up.

Anyway please make verify-agent-conf correctly validate whatever it is missing here.  I really count on that script to accurately certify agent.conf changes as safe to push out.

Thanks!
Kevin

**Comment by branchnetconsulting** [comment]
Thanks Chema!

**Comment by chemamartinez** [comment]
Hi @branchnetconsulting ,

In this PR (https://github.com/wazuh/wazuh/pull/408) has been fixed the reported issue. It will be included in the next release.

Thanks for your feedback!
