### ISSUE TITLE
wazuh-client 3.9.3-1 install broken...again

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#3937]
I had previously reported #3064 with version 3.7.3.  With wazuh-client 3.9.3-1 and Ubuntu 18.04 it is the same issue.  When installing a new package (separate from wazuh-client), and because 'apt-get --fix-broken install' doesn't work (see error below), I have to refer back to github to issue 3064 for notes on how to resolve the issue  I've run Ubuntu since 12.04 and this is probably the most frustrating package to deal with.  Will this issue be fixed in the near future such that the following is not observed on every server?

Removing wazuh-agent (3.9.3-1) ...
dpkg: error processing package wazuh-agent (--remove):
 installed wazuh-agent package post-removal script subprocess returned error exit status 1

**Comment by DFolchA** [comment]
Hello @alphaDev23,

Can you give me more details about your environment, for example, are you running wazuh in a Docker and mounting /var/ossec as a volume? 

Also, can you tell me if you have systemd and upstart enabled?

Best regards, 
Daniel Folch

**Comment by alphaDev23** [comment]
Running directly on 18.04 host, 4.15.0-54-generic, 

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

18.04 uses systemd

**Comment by DFolchA** [comment]
Hello @alphaDev23,

I have tried to reproduce your error with the same environment that you described, but the package worked properly for installation, upgrade, remove and purge.

Could you edit this file var/lib/dpkg/info/wazuh-agent.postrm and change `set -e` to `set-ex` and send us the output, that way we will be able to see which line is failing within the post-remove script and we will try to fix it for future releases.

Regards, 
Daniel Folch

**Comment by alphaDev23** [comment]
I'm closing this issue.  Could have been related to the kernel.  After upgrading 18.04 to the latest, I'm able to remove and install the agent.
