### ISSUE TITLE
Adjust and make configurable the maximum number of supported agents

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#3942]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0 | N/A | Manager | All | All |

The `MAXAGENTS` variable defines the maximum supported agents by a manager, more specifically, the maximum number of agents defined in the manager's client.keys file.

It is defined when compiling the manager and there is no way to change its value once the manager is installed.

That variable should be overwritten by a configurable option. In addition, that limit should be adjusted to ensure the maximum number of agents supported by the manager to be registered is set.

This issue involves the following subtasks:

- [ ] Make the `MAXAGENTS` variable configurable through the ossec.conf.

- [x] Adjust the default value for this variable, as well as the limit of the maximum file descriptors opened by the issued daemons (`analysisd`, `remoted`, `wazuh-db`)

- [x] Make dynamic arrays for those with `MAXAGENTS` size. https://github.com/wazuh/wazuh/blob/41d1430afa627d7f218c358bc1fedfad513b42a6/src/remoted/manager.c#L61
https://github.com/wazuh/wazuh/blob/41d1430afa627d7f218c358bc1fedfad513b42a6/src/analysisd/decoders/rootcheck.c#L33

**Comment by jctello** [comment]
Additional context: 
The `authd` will allow adding more agents than this value causing the remoted to output:
```
2019/11/06 13:46:09 ossec-remoted: ERROR: (4110): Maximum number of agents '13998' reached.
2019/11/06 13:46:09 ossec-remoted: CRITICAL: (1202): Configuration error at '/etc/client.keys'.
```
And in consequence the process will exit. These two components should not conflict in such a way that one can crash the other.

**Comment by snaow** [comment]
Related: https://github.com/wazuh/wazuh/issues/6097

**Comment by vikman90** [comment]
Closing this issue as it's related to #6097.
