### ISSUE TITLE
server ossec-logcollector  command setting but  agent  is fail

### ISSUE THREAD

**Issue by simlelcf** [wazuh/wazuh#3947]
## server  ossec.confg

![image](https://user-images.githubusercontent.com/18651522/64578740-ea4c0200-d3b2-11e9-9751-23845952111e.png)

![image](https://user-images.githubusercontent.com/18651522/64578803-14052900-d3b3-11e9-86f3-0b9d73bb955b.png)

##  Agent  is unsuccessful
![image](https://user-images.githubusercontent.com/18651522/64578823-24b59f00-d3b3-11e9-81db-c181f3360924.png)

**Comment by simlelcf** [comment]
tanks you

**Comment by simlelcf** [comment]
thanks you

**Comment by cristgl** [comment]
Hello @simlelcf,

Localfile blocks are contemplated in the local machine, if you want your agents to have the same directory, you can add the same configuration to them. Although, you can also change agent's configuration from the server, paste this in your agent.conf file (located in _etc/shared/<group>/agent.conf_). 

```
<agent_config>
<localfile>
    <log_format>command</log_format>
    <command>mkdir /root/yy</command>
    <frequency>10</frequency>
  </localfile
</agent_config>
```
