### ISSUE TITLE
Unsused variable warning when compiling without INOTIFY_ENABLED

### ISSUE THREAD

**Issue by JuantAldea** [wazuh/wazuh#3975]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 |Syscheck | -- | -- | -- |

This popped out while compiling on MacOS ElCapitan

```
syscheckd/run_realtime.c:36:24: warning: unused variable 'adddir_mutex' [-Wunused-variable]
static pthread_mutex_t adddir_mutex;
```

**Comment by chemamartinez** [comment]
This issue is fixed at tree [#fix-syscheck-integritydb](https://github.com/wazuh/wazuh/tree/fix-syscheck-integritydb)
