### ISSUE TITLE
File descriptor leak on Windows agents

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#3977]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0-31009 | Not determined yet | Agent | Packages | Windows Server 2019 |

Hi team,

We found a file descriptor leak in the Windows Agent while running the stress tests for more than 2 days. Here you can find an image that shows this leak: ![image](https://user-images.githubusercontent.com/9081114/64960143-f8a68c00-d892-11e9-96d0-a3b09f831206.png)

You can also find [here](https://github.com/wazuh/wazuh/files/3616395/ossec.conf.txt) the configuration file used in the Windows agent.

We are currently investigating which of the available modules is the one that produces this leak. We will keep you posted with any news.

Regards.

**Comment by snaow** [comment]
Closed by https://github.com/wazuh/wazuh-qa/issues/156
False positive.
