### ISSUE TITLE
Update version detection for macOS Catalina

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#3987]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.0 | ossec-agentd | Agent | Packages | macOS |

An update in the OS version detection is necessary to add the new release of [macOS Catalina](https://www.apple.com/macos/catalina/).

The function to update is `OSX_ReleaseName`:
https://github.com/wazuh/wazuh/blob/b0939a11a9cd80d11b0de61e65d8d61b58d41a5a/src/shared/version_op.c#L278

**Comment by chemamartinez** [comment]
Merged #4061
