### ISSUE TITLE
Simple and sregex syscheck <registry_ignore> stanzas are incompatible

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#3990]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5 | Syscheck | Agent | All | Windows |

Hi team,

During the investigation to solve [this mail list community ticket](https://groups.google.com/forum/?hl=es#!topic/wazuh/jlSRgiyU3JI), a bug was found in the Syscheck module:

When combining `<registry_ignore>` and `<registry_ignore type="sregex">` stanzas, only the non-sregex ones will be taken into account at the registry ignore process.

**Steps to reproduce:**

- Using a registry ignore list that contains one or more <registry_ignore type="regex"> entries and at least one <registry_ignore> entry, as the example below:

```
agent ossec.conf or agent.conf:

      <registry_ignore>HKEY_LOCAL_MACHINE\Security</registry_ignore>
      <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\System</registry_ignore>
      <registry_ignore type="sregex">HKEY_LOCAL_MACHINE\Software</registry_ignore>
      <registry_ignore arch='64bit'>HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer</registry_ignore>
```

- Apparently, the ignore is acknowledged:
```
agent ossec.log:

ossec-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Security'
ossec-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer'
ossec-agent: INFO: (6207): Ignore 'registry' sregex 'HKEY_LOCAL_MACHINE\System'
ossec-agent: INFO: (6207): Ignore 'registry' sregex 'HKEY_LOCAL_MACHINE\Software'
```

- However, the sregex ignores stanzas are never applied. After examining the related code, the cause of this behavior has been found:
https://github.com/wazuh/wazuh/blob/b98f0a8ca3789e67e27ae011b7db0a05b1ffd0bd/src/syscheckd/win-registry.c#L330-L349

The existence of one simple `<registry_ignore>` causes `syscheck.registry_ignore` structure initialization, so the `If` body is always executed. The `else` statement body, the one that performs the sregex check is never executed.

Best regards, Juan Pablo Sáez

**Comment by FernandoCP** [comment]
Hello team!

The part of code that caused the bug has been modified and I've checked it's fixed, so I am going to close this issue.

Best regards, Fernando.
