### ISSUE TITLE
Information message number 6022 can flood the Windows agent log file

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#3998]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 | Syscheck | Win Agent | Packages/Sources | Windows Server 2019 |

***

Hi team,

When Wazuh agent monitor any directory in Whodata and it doesn't exist, the first message from Wazuh is as follow:

`2019/09/23 04:52:29 ossec-agent: WARNING: 'directory_path' does not exist. Monitoring discarded`

Then, Wazuh tries to add it to audit rules with a frequency configure in  `windows_audit_interval`. If this file doesn't exist Wazuh shows the following message:

`2019/09/23 04:55:58 ossec-agent: INFO: (6022): 'directory_path' has been deleted. It will not be monitored in real-time Whodata mode.`

If there are a lot of directories to monitor and/or `windows_audit_interval` is too short the second message will be repeated too many times and it may be annoying.

Regards,
Eva.

**Comment by Skeptor** [comment]
This issue is no longer reproducible after the FIM rework. First Warning is no longer logged.
![image](https://user-images.githubusercontent.com/9034923/69718784-74cd1380-110f-11ea-9d1b-340d90b94cbf.png)

**Comment by jotacarma90** [comment]
Hello team,
New FIM solves it. I am going to close this issue.
Regards,
Jose
