### ISSUE TITLE
Orphan whodata configuration option on Windows (windows_audit_interval)

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#4002]
Hello team,

We have detected an orphan parameter inside syscheck configuration block (ossec.conf), such parameter is `windows_audit_interval` that probably will be clearer if put inside `whodata` configuration block as we can see here https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syscheck.html#whodata

Thanks and regards.

**Comment by jotacarma90** [comment]
Hello Okynos, 

This variable `windows_audit_interval` only appears in Windows, and the Whodata block is for the other platforms (not for windows), we have decided not to implement this change at the moment. Since it would generate an entire block for a single variable.
