### ISSUE TITLE
Wazuh receives data from the syslog but is not displayed in kibana

### ISSUE THREAD

**Issue by Daulet-AlmatyKZ** [wazuh/wazuh#4006]
Hello command!!!
I'm testing Wazuh virtual machine. During testing included a localfile and syslog from port 514/udp/. But kibana does not see files. Also, does not see syslogs. please help me, what am I doing wrong???
Below are the settings and screenshots.
1. configuration ossec.conf (global,remote,local file)

<global>
		<jsonout_output>yes</jsonout_output>
		<alerts_log>yes</alerts_log>
		<logall>yes</logall>
		<logall_json>yes</logall_json>
		<email_notification>no</email_notification>
		<smtp_server>smtp.example.wazuh.com</smtp_server>
		<email_from>ossecm@example.wazuh.com</email_from>
		<email_to>recipient@example.wazuh.com</email_to>
		<email_maxperhour>12</email_maxperhour>
		<email_log_source>alerts.log</email_log_source>
	</global>
	<alerts>
		<log_alert_level>1</log_alert_level>
		<email_alert_level>12</email_alert_level>
	</alerts>
.......
<remote>
		<connection>syslog</connection>
		<port>514</port>
		<protocol>udp</protocol>
		<allowed-ips>IP_adress_Firewall</allowed-ips>
</remote>
........

<ossec_config>
	<localfile>
		<location>/var/fortigate/*.log</location>
		<log_format>syslog</log_format>
		<target>fortigate_agent</target>
	</localfile>
</ossec_config>

2.wazuh receives syslog from port 514 and writes to a file archives.log

![archives log](https://user-images.githubusercontent.com/55727526/65568174-9c222b80-df7a-11e9-96be-0c65a881d930.JPG)

3.  I tested one line from the logfile archives.log to ossec-logtest. result:

![ossec-logtest](https://user-images.githubusercontent.com/55727526/65568761-c1b03480-df7c-11e9-9b02-aeb5829a9fb7.JPG)

kibana  web screenshots. 
 log collection
![ossec_config_log collection](https://user-images.githubusercontent.com/55727526/65568791-de4c6c80-df7c-11e9-9bdf-34bec1638a35.JPG)

![kibana](https://user-images.githubusercontent.com/55727526/65568988-8cf0ad00-df7d-11e9-822d-b21c9cac612c.JPG)

**Comment by Zenidd** [comment]
Hi @Daulet-AlmatyKZ, 

Let's follow the conversation in the Wazuh mail list thread: https://groups.google.com/forum/?hl=es#!topic/wazuh/rN7WEzCesac

Greetings, JP Sáez
