### ISSUE TITLE
Wrong permissions in agent-groups file

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#4010]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.3 | ossec-remoted | Manager | Sources | Ubuntu 18.04 |

### **Issue:** 
Hello team,

I have found an issue with a file permissions in agent-groups. I am creating a wazuh-cluster with 1 master, 2 workers and 100 agents using docker-compose.

When I bring the environment up, one of the agent files in `var/ossec/queu/agent-groups` is being created with the wrong permissions:
```
-rw-rw---- 1 ossecr ossec    8 2019-09-25 10:17:00.247927186 +0000 058
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:05.000000000 +0000 059
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:05.000000000 +0000 060
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:00.000000000 +0000 061
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:00.000000000 +0000 062
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:01.000000000 +0000 063
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:01.000000000 +0000 064
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:01.000000000 +0000 065
-rw-r--r-- 1 ossecr ossec    8 2019-09-25 10:17:01.407907337 +0000 066
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:02.000000000 +0000 067
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:02.000000000 +0000 068
-rw-rw---- 1 ossec  ossec    8 2019-09-25 10:17:02.000000000 +0000 069
-rw-rw---- 1 ossecr ossec    8 2019-09-25 10:17:02.367890913 +0000 070
```
As we can see above, agent 066 file is created with `644` permissions, while all others have `660`.

### **Details:**
- The agent with this problem always has `ossecr` as the owner. This means the agent is reporting to this specific node (the master in this case), and it is `ossec-remoted` who creates the file.
- It can also happen in the other nodes.
Agent 037 in Worker1:
`-rw-r--r-- 1 ossecr ossec 8 2019-09-25 10:16:56.635989010 +0000 037`
Agent 061 in Worker2:
`-rw-r--r-- 1 ossecr ossec 8 2019-09-25 10:17:00.919915687 +0000 061`
- Which agent group file ends up being the one with wrong permissions seems random, as there are files modified by `ossec-remoted` before and after the wrong one:
```
root@5c3b14a81efa:/var/ossec/queue/agent-groups# stat 058 066 070
  File: 058
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: 46h/70d	Inode: 865192      Links: 1
Access: (0660/-rw-rw----)  Uid: (  997/  ossecr)   Gid: (  999/   ossec)
Access: 2019-09-25 10:17:02.231893240 +0000
Modify: 2019-09-25 10:17:00.247927186 +0000
Change: 2019-09-25 10:17:00.247927186 +0000
 Birth: -
  File: 066
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: 46h/70d	Inode: 865579      Links: 1
Access: (0644/-rw-r--r--)  Uid: (  997/  ossecr)   Gid: (  999/   ossec)
Access: 2019-09-25 10:17:02.367890913 +0000
Modify: 2019-09-25 10:17:01.407907337 +0000
Change: 2019-09-25 10:17:01.407907337 +0000
 Birth: -
  File: 070
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: 46h/70d	Inode: 865727      Links: 1
Access: (0660/-rw-rw----)  Uid: (  997/  ossecr)   Gid: (  999/   ossec)
Access: 2019-09-25 10:17:02.447889544 +0000
Modify: 2019-09-25 10:17:02.367890913 +0000
Change: 2019-09-25 10:17:02.367890913 +0000
 Birth: -
```
- If the file with wrong permissions is removed manually, `ossec-remoted` creates it again with OK permissions:
```
root@5c3b14a81efa:/var/ossec/queue/agent-groups# rm 066
root@5c3b14a81efa:/var/ossec/queue/agent-groups# stat 066
  File: 066
  Size: 8         	Blocks: 8          IO Block: 4096   regular file
Device: 46h/70d	Inode: 863942      Links: 1
Access: (0660/-rw-rw----)  Uid: (  997/  ossecr)   Gid: (  999/   ossec)
Access: 2019-09-25 10:52:09.903424621 +0000
Modify: 2019-09-25 10:52:09.875425007 +0000
Change: 2019-09-25 10:52:09.875425007 +0000
 Birth: -
```
### **Implications:**
- The wazuh API can't perform add/remove operations to/from any group to the agent with wrong file permissions:
```
root@5c3b14a81efa:/var/ossec/queue/agent-groups# curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/groups/test?pretty"
{
   "error": 0,
   "data": "Group 'test' created."
}
root@5c3b14a81efa:/var/ossec/queue/agent-groups# curl -u foo:bar -k -X PUT "http://127.0.0.1:55000/agents/066/group/test?pretty"
{
   "error": 1005,
   "message": "Error reading file"
}
```
- This problem occurs because the Wazuh API belongs to `ossec` group. Therefore, it only has read permissions over the file with 644 permissions, as the owner is `ossecr`.

### **Investigation:**
- In order to further investigate the origin of the issue I have tried to set `remoted.debug=2` in `/var/ossec/etc/internal_options.conf` before starting the cluster for the first time (this is when remoted creates those agent group files). However, when I do this, the problem never replicates, and I am unable to further check what might be happening when ossec-remoted creates the file with wrong permissions.

@wazuh/core

**Comment by vikman90** [comment]
Hi. I did not manage to reproduce that, but I figured out the cause of this bug using `strace`:
```sh
pkill -f remoted
strace -f /var/ossec/bin/ossec-remoted -f 2>strace.log &
tail -f strace.log | grep umask
```

### Looking for calls to umask

```
[pid 132157] umask(006)                 = 022
[pid 132157] umask(022)                 = 006
[pid 132155] umask(006)                 = 022
[pid 132155] umask(022)                 = 006
```

There are many threads calling `umask` to achieve permissions `rw-rw----` and then restoring back the old mask. This may cause a race condition, so Remoted may create files with permissions `rw-r--r--`.

## Possible fixes

1. Set the permission mask once on startup. This will eliminate the race condition but could affect other files (like rids).
2. Add `chmod` after writing into files. That will ensure the files have the correct permissions.
