### ISSUE TITLE
SCA in Ubuntu 12,14,16

### ISSUE THREAD

**Issue by ericlee0517** [wazuh/wazuh#4017]
Hi bro,
 These days I was working on our new future SCA.I found we have lots of yaml in different operating system except Ubuntu 12,14,16.What 's more, I compared with the module open-scap which has the same problems.It is hard to find ubuntu systems in XCCDF format for CIS.
Please help me.
Best wishes.

**Comment by Zenidd** [comment]
Hi @ericlee0517 

[Our SCA Debian policies](https://github.com/wazuh/wazuh-ruleset/tree/master/sca/debian) are compatible with Ubuntu 12, 14 and 16. You could use these to discover the exposures or misconfiguration in your monitored hosts.


On the other hand, [here](https://github.com/ComplianceAsCode/content/releases/download/v0.1.46/scap-security-guide-0.1.46-oval-5.10.zip) you can download the last openSCAP security guide from the [ComplianceAsCode repository](https://github.com/ComplianceAsCode
). There you will find the policies file for ubuntu 14 and ubuntu 16. Seems like there is no openSCAP compliance file for Ubuntu 12.

Let me know if there is something more to clarify regarding this or other topics. Greetings, 
JP Sáez

**Comment by Zenidd** [comment]
Hello again @ericlee0517,

I'm close this issue as it does not imply a bug report nor feature request. For further questions, (apart from this topic) please, use our [mailing list](https://groups.google.com/forum/?hl=es#!forum/wazuh) or the [Wazuh #community Slack channel](https://wazuh.com/community/join-us-on-slack/).

Regards, JP Sáez
