### ISSUE TITLE
Create new Python script to pull messages from Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4021]
According to #4015, a new Python package should be created in order to let `wazuh-modulesd` to get messages from Google Cloud Pub/Sub. 

## Requirements
- Pull messages from a topic subscription: use the official package https://pypi.org/project/google-cloud-pubsub/ to download messages and redirect them to standard output (similar to our AWS wodle)
- Use the Python standard logging utility, instead of printing (an enhancement relative to our previous AWS wodle). Deciding the file to log to is still pending. `ossec.log` is not the best option since some concurrency problems and race conditions may occur.
- To keep things in order, the package structure would be the standard in Python:
```
- gcloud-wodle
  - __main__.py
  - Any other auxiliar code modules (tools.py, errors.py, etc)
```
The way to run this wodle would be: `python3 -m gloud-wodle`
- The output would be something like:
```
 {
 insertId: "1ji580hdw8x4"  
 
jsonPayload: {
  authAnswer: true   
  protocol: "UDP"   
  queryName: "mirrors.fedoraproject.org."   
  queryType: "A"   
  rdata: "mirrors.fedoraproject.org.	287	IN	cname	wildcard.fedoraproject.org.
wildcard.fedoraproject.org.	47	IN	a	140.211.169.196
wildcard.fedoraproject.org.	47	IN	a	8.43.85.67
wildcard.fedoraproject.org.	47	IN	a	8.43.85.73
wildcard.fedoraproject.org.	47	IN	a	67.219.144..."   
  responseCode: "NOERROR"   
  sourceIP: "10.10.10.10"   
  sourceNetwork: ""   
  vmInstanceId: 1234123412341234   
  vmInstanceName: "xxxxxxx"   
 }
 logName: "projects/xxx/logs/dns.googleapis.com%2Fdns_queries"  
 receiveTimestamp: "2019-09-27T10:11:31.787413623Z"  
 
resource: {
  
labels: {
   location: "us-central1"    
   project_id: "xxx"    
   source_type: "gce-vm"    
   target_name: ""    
   target_type: "external"    
  }
  type: "dns_query"   
 }
 severity: "ERROR"  
 timestamp: "2019-09-27T10:11:30.934244226Z"  
}
 {
 insertId: "1ji580hdw8x5"  
 
jsonPayload: {
  authAnswer: true   
  protocol: "UDP"   
  queryName: "mirrors.fedoraproject.org."   
  queryType: "A"   
  rdata: "mirrors.fedoraproject.org.	287	IN	cname	wildcard.fedoraproject.org.
wildcard.fedoraproject.org.	47	IN	a	140.211.169.196
wildcard.fedoraproject.org.	47	IN	a	8.43.85.67
wildcard.fedoraproject.org.	47	IN	a	8.43.85.73
wildcard.fedoraproject.org.	47	IN	a	67.219.144..."   
  responseCode: "NOERROR"   
  sourceIP: "10.10.10.10"   
  sourceNetwork: ""   
  vmInstanceId: 1234123412341234   
  vmInstanceName: "xxxxxxx"   
 }
 logName: "projects/xxx/logs/dns.googleapis.com%2Fdns_queries"  
 receiveTimestamp: "2019-09-28T10:11:31.787413623Z"  
 
resource: {
  
labels: {
   location: "us-central1"    
   project_id: "xxx"    
   source_type: "gce-vm"    
   target_name: ""    
   target_type: "external"    
  }
  type: "dns_query"   
 }
 severity: "ERROR"  
 timestamp: "2019-09-28T10:11:30.934244226Z"  
}
```

**Comment by druizz90** [comment]
# Issue update

I am working on branch `dev-wodle-google-pubsub-4021` for this development. I create a `core.py` module for including classes and functions for getting and processing events from `Google Cloud`.

The wodle has the next input parameters:
- `project`: Name of the project.
- `subscription_id`: Subscription ID
- `credentials_file`: Path to credentials file (it is a `JSON` file).
- `max_messages`: Maximum number of messages retrieved each time which `pull` method is executed.
- `log_level`: I defined five low levels, as the standard logger of Python has (https://docs.python.org/3/library/logging.html#logging-levels).

### Basic usage

When the wodle is executed, the credentials and the permissions for getting events from the subscription are checked. Then, events are got by using `pull` method from `pubsub` library. This method is called with the parameter `max_messages` until no more messages are available. It is possible that the deadline for retrieving messages would be exceeded. If this happens, the wodle will finish to process events on the current execution. More events will be processed when it will be executed the next time.

The wodle generates a log file each day and logging messages are written in these files. If an error happens while the wodle is executed, the full trace of the error will be included in the log files. It would be necessary to create a function for rotate/clean logs.

### Structure

The wodle has three files:

- `__main__.py`: This is the file will be executed. Launch the wodle. Import classes and functions from the other modules.
- `wazuh_gcloud`: Contains a class to interact with a `Google Cloud` subscription.
- `tools`: Contains generic functions as a function for getting the input arguments.

Unit tests will be placed into `tests` directory.

**Comment by druizz90** [comment]
# Issue update

I added unit tests for this wodle. It is necessary to make the integration with `modulesd` to continue the development.
