### ISSUE TITLE
DEBUG flag doesn't work as expected

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#4032]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| any | Makefile | Manager/Agent | Sources | OS version |

Hi team,

We found an issue related to the `DEBUG` flag in the Makefile that makes this variable to not work as expected. This variable is used to compile the binaries with debug symbols using the `-g` flag while building the binaries but the Makefile doesn't check the value of this variable, it only checks if the variable is defined: https://github.com/wazuh/wazuh/blob/ee0943daae73677c3ff886b9ac892711fdf4ceeb/src/Makefile#L199-L201

So, if you build the agent or the manager using this flag, no matter what is its value, the binaries will be compiled with debug symbols:
```shellsession
# make TARGET=server DEBUG="no" 
# make TARGET=server DEBUG="random text"
```
Both examples will build the manager with debug symbols.

Regards.

**Comment by chemamartinez** [comment]
Done: #4034
