### ISSUE TITLE
Negation regexp in alerts not working

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [wazuh/wazuh#4040]
|Wazuh version|Component|Install type|Install method|Platform|
|     3.9.5          | Filebeat 7.3|                |                       |Elastic 7.X|

Hi:

i'm triying to create this rule:
```

  <rule id="100105" level="10">
    <if_sid>60103</if_sid>
    <field name="win.system.eventID">^4656$|^4661$</field>
    <field name="win.eventdata.processName">**!ossec-agent.exe$**</field>
    <description>Attempts to Steal Passwords from the Registry, MITRE ATT&CK Technique T1214</description>
    <group>MITRE ATT&CK Technique T1214</group>
  </rule>
```

The rule works fine if i remove exclamation, i mean, the negation of the regexp, but if i try to filter events related with process ossec-agent.exe just using an exclamation at the beginning of the regexp it didn't work.
Do someone know any issue related with negations of regexp.
Do someone know what i'm doing wrong ??

**Comment by Zenidd** [comment]
Hi @BernaldoPenasAntelo, 

This has been discussed in our slack #community channel but i'll try to summarize it here:

- **The issue** with this rule is that `<field>` option supports [OS_Regex](https://documentation.wazuh.com/3.10/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) expressions and the negation "!" operator isn't included in these expressions.
- **The solution** involves using a CDB list: As @BernaldoPenasAntelo  wants to whitelist one or more files, it's possible to include the full path of these files inside a CDB list. The events paths will be checked against this whitelist to decide whether they trip an alert or not.

Link to the Slack conversation: https://wazuh.slack.com/archives/C0A933R8E/p1570093609094500

I'm closing this issue as it has been solved in our Slack channel. Do not hesitate to open this ticket or reopen a new one if you want to add any information or whatever is needed.

Best regards, JP Sáez
