### ISSUE TITLE
Elastic fails to index some alerts because of a huge `previous_output` field

### ISSUE THREAD

**Issue by vsenko** [wazuh/wazuh#4045]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5-1 | wazuh-manager | Manager | Packages | Ubuntu 18.04 |

I observe a lot of the following events in `/var/log/syslog`:
```
Oct  3 05:23:25 srv logstash[6439]: [2019-10-03T05:23:25,545][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"wazuh-alerts-3.x-2019.10.03", :_type=>"_doc", :routing=>nil}, #<LogStash::Event:0x95371c7>], :response=>{"index"=>{"_index"=>"wazuh-alerts-3.x-2019.10.03", "_type"=>"_doc", "_id"=>"LlISkG0BvvvMsh5BqqvO", "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"Document contains at least one immense term in field=\"previous_output\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[80, 114, 101, 118, 105, 111, 117, 115, 32, 111, 117, 116, 112, 117, 116, 58, 10, 111, 115, 115, 101, 99, 58, 32, 111, 117, 116, 112, 117, 116]...', original message: bytes can be at most 32766 in length; got 65052", "caused_by"=>{"type"=>"max_bytes_length_exceeded_exception", "reason"=>"bytes can be at most 32766 in length; got 65052"}}}}}
```

Currently alerts flow is configured the following way (to fix timestamps on alerts from old JSON decoded events):
```
Wazuh -> Filebeat -> Logstash -> Elastic
```

I'm totally confident that before inserting Logstash in alert flow there were similar events from Filebeat.

It looks like the field `previous_output` sometimes grow too big. Shouldn't there be any means to limit it's size? Probably Wazuh manager should be responsible for this with configurable option?

**Comment by pablotr9** [comment]
Hi @vsenko ,

Unfortunately there's a maximum field size of ~32KB, when a field exceeds that limit the alert is not indexed in Elasticsearch.
A solution to this problem is truncating the log to a maximum of 32KB, so if any of your alerts has a field with a size higher than 32KB, only the first 32KB will be indexed and the rest would be dropped.
To do that we can use the `truncate filter plugin` in Logstash:
```
filter {
        truncate {
          length_bytes => 32000
        }
}
```

I hope it helps, let me know if that works for you.

Best regards,
Pablo Torres

**Comment by vsenko** [comment]
@pablotr9, thank you!

So the most fit option currently is to truncate it with Logstash.

I suppose that 32KB is too much, 1-2KB would be enough.

**Comment by vsenko** [comment]
By the way, implementing something like this in Wazuh manager would definitely improve performance and memory usage - looks like currently Wazuh can handle a lot of `previous_output` values for different rules concurrently.
