### ISSUE TITLE
Extend the static fields comparison options

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#4050]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.10 and earlier | Ruleset options | Manager | All | All |

The static field comparison options are incomplete. There are only these options:
-  same_source_ip 
-  same_src_port
-  same_dst_port
-  same_user
-  same_location
-  same_id
-  different_url
-  different_srcgeoip

Some examples of the missing options:

-  same_destination_ip
-  different_destination_ip

It would be a great feature extending these options to all the static fields and two new options for dynamic fields: 
- `<same>field</same>`
- `<different>field</different>`

Greetings, JP Sáez

**Comment by danimegar** [comment]
|Branch|
|---|
|[4050-statics-fields-comparison](https://github.com/wazuh/wazuh/compare/3.11...4050-statics-fields-comparison)|

I have created a branch and a draft PR. I added **same_destination_ip** and **different_destination_ip**. Is it necessary to add more options such as:
- [ ] different_location ?
- [ ] different src_port ?
- [ ] different dst_port ?
- [ ] same_agent ?
- [ ] same_src ?

In addition, is it necessary to add two new options for dynamic fields when we have the **same_fields** and **not_same_fields** dynamic fields?

![image](https://user-images.githubusercontent.com/24528466/71909244-e87f2900-316f-11ea-880a-8de0452864f7.png)
