### ISSUE TITLE
Master and Worker feature request

### ISSUE THREAD

**Issue by ajohnson8503** [wazuh/wazuh#4058]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Wazuh Cluster | Manager | Packages | All |

Currently all agents need to be registered with the master and not the worker. This only really works on single sites or interconnected sites where the master is able to be connected to via the agent. This is not the best for no connected sites or for sites with secure zones that only allow out limited traffic. In sites like this it would be more preferred if the worker could be able to communicate back to the master about new agents that are being connected or any changes to the site. This would limit allowing all system in a site outbound on 1514 and would only require the worker to be the outbound connection. The master could still be the main single system getting all the information. As it stands for companies such as mine that have to follow PCI and have multiple offices around the US, AWS and Azure. We have to run master nodes at all these sites and manage them as stand alone systems then though we have interconnections between some of these sites.

**Comment by crd1985** [comment]
Hi @ajohnson8503 ,

Thank you for pointing out your use case.

As you say, the current cluster implementation only allows registering agents through the `master` node. I agree with the idea of implementing a kind of 'forwarding' mechanism to allow registration of agents also in 'worker' nodes. I think this could be a simple way to deal with your use case, where master node should be isolated and only allows communicating with worker nodes.

We will study the best technical approach and take it into account in the cluster rework needed to support multi-master and HA (#811).

Thanks again for your collaboration.

Regards,
Daniel Ruiz

**Comment by palaciosjeremias** [comment]
Hi @ajohnson8503 ,
Again, thanks for pointing out your use case.
I wan't to inform you that we were working on this functionality and plan to include it on next Wazuh release.
After a research, we decided to keep an unique and unmodifiable master node, responable of creating and sync up Agents keys, and added the functionality to hand a key request on the workers. In this way. A worker node will receive the Agent key request, ask it to the master node, using a clustered message chanel and dispatch the response again to the agent.

**Comment by palaciosjeremias** [comment]
As this issue is being handled in #4905 I think we can close this one
