### ISSUE TITLE
Vulnerability Detector error: The version of '(null)' could not be extracted.

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#4059]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | Modulesd | Manager | Packages and sources | Ubuntu 18.04 |

The Red Hat vulnerability feed that Vulnerability Detector uses indexes its conditions by including the package name and version in a single string. To manage it and separate the version from the name, the module uses a regular expression that until today covered 100% of the standard followed by indexed packages.

https://github.com/wazuh/wazuh/blob/7aa4d46661f8b0f97b0969634482626f30866731/src/wazuh_modules/wm_vuln_detector.c#L1861

However, due to two news packages which do not follow this format have been introduced, we will see the following errors in the `ossec.log` file when performing an update.

> 2019/10/08 08:05:29 wazuh-modulesd:vulnerability-detector: ERROR: (5493): The version of '(null)' could not be extracted.
> 2019/10/08 08:05:29 wazuh-modulesd:vulnerability-detector: ERROR: (5493): The version of '(null)' could not be extracted.

Those packages are:

- **kube-rbac-proxy-container-v3.11.82-3**
- **openshift-enterprise-console-container-v3.11.98-6**

We need two things:

- Taken into account that we are integrating an external feed which can change the mentioned format without waiting for Wazuh update, that message should be a debug message, no an error. It should also include the string from which the package data is attempted to be extracted.

https://github.com/wazuh/wazuh/blob/7aa4d46661f8b0f97b0969634482626f30866731/src/wazuh_modules/wm_vuln_detector.c#L2268

Should be replaced by:

``` C
mtdebug1(WM_VULNDETECTOR_LOGTAG, VU_VER_EXTRACT_ERROR, tmp_affected_packages->valuestring);
```

This change has been applied in the [vuln-windows](https://github.com/wazuh/wazuh/pull/2787) branch, so it is possible that it is merged when this issue is assigned.

- Include support for decoding those packages. This can be performed by adding a new entry to the regex previously mentioned.

This bug does not break the updating process.

**Comment by crolopez** [comment]
I can confirm that another package whose version cannot be decoded in the last Wazuh version (3.10.2) has been added: `logging-elasticsearch5-container-v3.11.153-2`.

This package appears several times, so we will see increased the number of errors for each appearance it has.

Currently, the Red Hat Security Data feed indexes 3 packages that the module cannot parse, so several errors are displayed when updating but does not avoid that this process ends correctly:

- **kube-rbac-proxy-container-v3.11.82-3**
- **openshift-enterprise-console-container-v3.11.98-6**
- **logging-elasticsearch5-container-v3.11.153-2**

I can also confirm this issue is not generating memory leaks, but I think this could happen in the future if the feed is updated so that the flow goes through this line several times in a row. 

https://github.com/wazuh/wazuh/blob/7aa4d46661f8b0f97b0969634482626f30866731/src/wazuh_modules/wm_vuln_detector.c#L2262

In that case, we are talking about a memory leak of a few bytes for each update of the Red Hat feed.

**Comment by JcabreraC** [comment]
This problem has been solved in the next version, which will be released soon.

This version has a new vulnerability detection engine more robust, reliable, and complete.
