### ISSUE TITLE
Rootcheck false positives due to wrong ignored files handling

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#4065]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 and Previous | Rootcheck | Manager/Agent | All | Linux systems|

Hi team,

Directory names ending with a string as the ones specified in the `Rootcheck` ignore option trigger `Rootcheck` false positives. This happens because directories that have that ignored termination are excluded from the directory inodes count.

**Steps to reproduce**
- Include some ignores in `rootcheck` configuration:
```
<ignore type="sregex">.log$|.log.|.swp$|.out$|.gz$|.gz2$|.bz$|.bz2$|.mp4$|.mkv$|.webm$|.rmvb$|.avi$|.mp3$|.wav$|.h5$|.csv$|.iso$</$
<ignore type="sregex">^/var/log|^/var/lib|^/var/crash|^/var/cache|^/var/mail|^/opt/share|^/home|^/data|^/mnt</ignore>
```
- Create directories with some of the ignored extensions:
```
root@vagrant /etc/dummy_folder $ ll
total 44
drwxr-xr-x   9 root root  4096 oct 10 15:41 ./
drwxr-xr-x 155 root root 12288 oct 10 15:38 ../
drwxr-xr-x   2 root root  4096 oct 10 15:38 dummy0/
drwxr-xr-x   2 root root  4096 oct 10 15:38 dummy1/
drwxr-xr-x   2 root root  4096 oct 10 15:38 dummy2/
drwxr-xr-x   2 root root  4096 oct 10 15:38 dummy3.gz/
drwxr-xr-x   2 root root  4096 oct 10 15:41 dummy_alert.log/
drwxr-xr-x   2 root root  4096 oct 10 15:41 dummy_alert.mp4/
drwxr-xr-x   2 root root  4096 oct 10 15:40 dummy_alert.webm/
```
- False positives:
```
** Alert 1570717271.936110: - ossec,rootcheck,gdpr_IV_35.7.d,
2019 Oct 10 16:21:11 nanoPill->rootcheck
Rule: 510 (level 7) -> 'Host-based anomaly detection event (rootcheck).'
Files hidden inside directory '/etc/dummy_folder'. Link count does not match number of files (5,9).
title: Files hidden inside directory '/etc/dummy_folder'.
```
The directories  `dummy3.gz dummy_alert.log dummy_alert.mp4 dummy_alert.webm` were excluded from the inodes count as they match with the ignored files regex.

This issue was [reported by a user in our mail list](https://groups.google.com/forum/?hl=es#!topic/wazuh/ovnltdTssPA).

Greetings, JP Sáez

**Comment by antoniomanuelfr** [comment]
Hi team! 
This issue was fixed after #4603 was merged.
I'm closing this issue.
Regards.
