### ISSUE TITLE
Windows SCA

### ISSUE THREAD

**Issue by ajohnson8503** [wazuh/wazuh#4075]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10 | SCA | Manager/Agent | Packages | Windows |

Right now the highest Windows Version is Windows 2012 R2 for the new SCA system. There is a good amount of overlap from 2012+, but there has been quite a few changes to the Windows OS. Windows Server is currently on 2019 is there any plans to add support for 2016 and 2019?

**Comment by sergiovp** [comment]
Hello @ajohnson8503.

On our last Wazuh-version (3.10) SCA policies were fully reviewed, adapted to the module refactor and added support for new platforms.
We have introduced new rules and decoders for other technologies such as VIPRE antivirus, support for Cisco-ASA devices or Windows Software Restriction Policy rules.

We're still working on the new Windows Server policies, in fact, it's on our roadmap. You can track the progress in the related issue https://github.com/wazuh/wazuh-ruleset/issues/485.

We are continually trying to improve Wazuh and We'll do it as soon as our workflow allows us.

Thanks a lot for your feedback, we really appreciate your comments.

Best regards.
