### ISSUE TITLE
Vuln Detection on Windows Documentation

### ISSUE THREAD

**Issue by dwizel** [wazuh/wazuh#4099]
Probably not a new issue as I've been following some resources but still need help. I would like to configure vuln detection on Windows and there are no documentation on the Wazuh portal for this. From what I've read so far you seem to be using the NVD database as a reference, can you please help me?

**Comment by dwizel** [comment]
Do you have a release date for 3.11?

**Comment by Zenidd** [comment]
Hello @dwizel,

Our teams are working really hard and I'm pretty sure it will be out in the next few weeks. Please, stay tuned. 

Best regards, JP Sáez
