### ISSUE TITLE
Fix MemoryError when /tmp is mounted with noexec

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4111]
## Description
In some environments, a MemoryError is thrown by `wazuh-clusterd` as explained in #3327. Apparently, It happens if the /tmp directory is mounted using the `noexec` flag.

# Alternatives
- Comment the line related with this Python issue. https://bugs.python.org/issue35523. According to that link, that line has been removed in Python 3.8, so upgrading to Python 3.8 would close this issue too.
- Use the `TMPDIR` variable to point `cryptography` and any other Python packages to create any temporary file in that folder. This fix has been proved to solve the issue. The variable could be added to the framework wrapper script in `framework/wrappers/generic_wrapper.sh`.

**Comment by davidjiglesias** [comment]
Fixed with python bump
