### ISSUE TITLE
Question about reporting

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#4116]
Hi, 
I use Elasticsearch 7.4.0, Wazuh 3.10.2 and Kibana 7.3.2.
I would like know if it's possible to extract in "Security Events" the top 5 of Agents ? When I generate Report I have a summary. I would like top 5 in xml, json,csv or pdf. For put this information in other dashboard for example. Thank you. 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

When you generate a report of Security Events you can only get a report of all the visualizations in that dashboard, you can not extract only one visualization (top 5 agents in your case), you can find the top 5 agents in the generated report of Security Events:
![image](https://user-images.githubusercontent.com/35685689/67264492-7de11a00-f4ab-11e9-93a3-fe77536a5d7b.png)

-----------

If you need the top 5 agents in CSV there is a way to get that information in CSV format,
Go to Kibana -> Visualize and create a New Visualization of type **Data table** and select the index pattern `wazuh-alerts-3.x-*`
![image](https://user-images.githubusercontent.com/35685689/67264648-ffd14300-f4ab-11e9-9a2d-b36fd393b8b1.png)

Now add a bucket and select `Split rows`:
![image](https://user-images.githubusercontent.com/35685689/67264845-9271e200-f4ac-11e9-9d9c-87bdf4831262.png)

Then, in `Aggregation` select **Terms** and in `Field` select **agent.name**.
Apply changes in the play button on top, and you will see a new table with the top 5 agents. Now you can click on `Formatted` to export this data in **CSV format.**
![image](https://user-images.githubusercontent.com/35685689/67265056-11671a80-f4ad-11e9-95cf-84fdebf08765.png)

I hope it helps, let me know if you need anything else

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi @pablotr9,

Thank you for you help. 
In .csv I don't have the % of agent used. I have : Agent_Name , 10 or 5 or 2. For example a agent use 63,16% but in csv it's writing 10.  And it's possible to generate automatically the .csv every month ? 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

You can add the count percentages in the data table we created as follows:
In the `Options` tab, select `count` in the dropdown list of `Percentage Column`: 
![image](https://user-images.githubusercontent.com/35685689/67460578-a13acf00-f63b-11e9-874a-3bb33417ed12.png)
Unfortunately, Kibana does not support downloading the .csv with the percentage column, you will only get agent.names and the alerts count of each agent.

Regarding your question about automatic monthly generation of .csv, there is no way to automatic generate the csv of a visualization but there is a solution that may work for you.
You can create a script that queries Elasticsearch and get the top 5 agents to create your own .csv based on the result of that query, you can find more information about manually querying Elasticsearch here: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-search.html


Let me know if that works for you or if you need anything else

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Ok, thank you I look this. 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

I'll close this issue, feel free to reopen it or create a new one if you need anything else.

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi @pablotr9 
I don't have "Percentage column " :

![image](https://user-images.githubusercontent.com/46779058/67695291-15130980-f9a5-11e9-9d81-996100441d55.png)


And it's possible to see this result in query POST/GET ? For try to script ?

Best Regards,

**Comment by pablotr9** [comment]
Hi @John33000 ,

I have just created a Python3 script that queries Elasticsearch and creates a file with the information you asked for ( agent name, agent count and agent count percentage) in CSV format or Json format.
It will give you the result for the today's date indices ( if the index does not exist it will give you some errors as there is no error handling in this simple script).

Script: [agentsSummary.zip](https://github.com/wazuh/wazuh/files/3782424/agentsSummary.zip)

Make sure that you replace these two variables:
```
output = 0
elastic_ip = "172.16.1.2" # replace with your Elastic server IP
```
if `output` equals 0: the script will write the result in the file AgentsSummary.csv in CSV format.
if `output` is different from 0, the script will write the result in the file AgentsSummary.txt in JSON format.
Replace `elastic_ip` with your Elasticsearch server IP and make sure the machine where you run the script can access Elasticsearch (otherwise it won't work)

To run the script (you need Python3 installed) you just have to execute this:
`python3 agentsSummary.py`
Then, in the same folder where you ran it, you will have a new file, `AgentsSummary.csv `. In my case the content is:
```
agentName,count,percentage
master,85,54.48717948717948
agent,71,45.51282051282051
```
or in JSON format:
```
{
    "master": {
        "count": 85,
        "percentage": 54.48717948717948
    },
    "agent": {
        "count": 71,
        "percentage": 45.51282051282051
    }

```



You can take this script as an example if you want to get extra information or improve the output,

I hope it helps, let me know if you need anything else

Kind regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,

Sorry for the time of my answer. 
I run this script on my server, but the percentage stay at "0". 
The top 5 of Wazuh Agent it's good, but percentage stay a "0" in txt and .csv.

I use python for lunch the script, I need to lunch with python3 ? 

Best regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

That's weird, I have just tried, and Python3 it's not needed.
I have added some `prints` to the code so we can get  an idea of how is the script behaving.
[agentsSummary2.zip](https://github.com/wazuh/wazuh/files/3836479/agentsSummary2.zip)
Extract that `.zip` and run the script as follows:
```
python agentsSummary2.py
```
You should see some output when running the script, please paste it in your reply so I can give you further assistance.

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi @pablotr9 

The script give me this : 

```
Url: http://172.17.2.9:9200/wazuh-alerts-3.x-2019.11.12/_search

Headers: {'Content-type': 'application/json'}

Data: {"size":"0", "aggs" : {  "unique_agents" : {   "terms" : { "field" : "agent.name" }  } }}

Result json: {u'hits': {u'hits': [], u'total': {u'relation': u'eq', u'value': 2536}, u'max_score': None}, u'_shards': {u'successful': 3, u'failed': 0, u'skipped': 0, u'total': 3}, u'took': 1, u'aggregations': {u'unique_agents': {u'buckets': [{u'key': u'<SERVER-NAME>', u'doc_count': 1128}, {u'key': u'<SERVER-NAME>', u'doc_count': 540}, {u'key': u'<SERVER-NAME>', u'doc_count': 523}, {u'key': u'<SERVER-NAME>', u'doc_count': 163}, {u'key': u'<SERVER-NAME>', u'doc_count': 153}, {u'key': u'inf-infvm-soc01.infocheops.local', u'doc_count': 29}], u'sum_other_doc_count': 0, u'doc_count_error_upper_bound': 0}}, u'timed_out': False}

Result: {u'<SERVER-NAME>': {'count': 540, 'percentage': 0}, u'<SERVER-NAME>': {'count': 1128, 'percentage': 0}, u'<SERVER-NAME>': {'count': 523, 'percentage': 0}, u'<SERVER-NAME>': {'count': 163, 'percentage': 0}, u'<SERVER-NAME>': {'count': 153, 'percentage': 0}, u'<SERVER-NAME>': {'count': 29, 'percentage': 0}}

```

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

Ok, my bad, there was a small mistake in the script, the alerts count was of integer type so that's why we were getting `0` as result.
Here is the script with the fix:
[agentsSummary.zip](https://github.com/wazuh/wazuh/files/3836746/agentsSummary.zip)
Try with this new script and let me know if everything is working correctly now,

Best regards,
Pablo Torres

**Comment by John33000** [comment]
Hi,
Perfect, thank you ! I have percentage and 7 agents not 5, where you select 5 agent ?  It's "size" : "0" in headers ? 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

Sorry for the late reply, I have attached a new file with those 2 changes:
- To limit the agents, you can see I added a `"size": 5` (if you want to show more you can edit that value)
- To delete the field count, you can see I deleted the lines highlighted in this screenshot:
![image](https://user-images.githubusercontent.com/35685689/68849708-d84c4f80-06d2-11ea-867a-3066bbafdee2.png)

[agentsSummary.zip](https://github.com/wazuh/wazuh/files/3845973/agentsSummary.zip)

I hope it helps, let us know if you need anything else.


Kind regards,
Pablo Torres

**Comment by John33000** [comment]
Thanks again for your help. 
It's work. 

Best regards,

**Comment by pablotr9** [comment]
Hi @John33000 ,

I'm glad to see it is now successfully working, let us know if you need anything else.
I'll close this issue, feel free to reopen it or open a new one if you have any other question.

Kind regards,
Pablo Torres

**Comment by John33000** [comment]
Hi, @pablotr9 

My bad, I would like to reopen this case, is it possible to select top 5 agents started by custom string ? The script gave me the top 5 of all agents, and how can I select by agent's name ? .  

Best regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

Sorry for the late reply, I just noticed that you reopened this issue. 
Are you still trying to get the top 5 agents started by a custom string or you already did it?
Anyway, I'll explain to you how to customize the query to Elasticsearch to obtain specific results:
This is the new script:
[agentsSummary.zip](https://github.com/wazuh/wazuh/files/3994118/agentsSummary.zip)

You can see that I changed this line:
```

**Comment by John33000** [comment]
Sorry too for the late reply. I was in holiday. I take your new script. Thank you again.

Best Regards,

**Comment by John33000** [comment]
Hi @pablotr9 

 I toke your script. I change IP of elastic, but when I lunched the script, but the file .csv or .txt was empty. 

Best Regards

**Comment by pablotr9** [comment]
Hi @John33000 ,

Does the script show any error when you run it?

Best Regards,
Pablo Torres

**Comment by John33000** [comment]
No, in .csv I have : agentName,percentage. And in .txt {}.

Best Regards
