### ISSUE TITLE
Add RBAC support to decoders endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4119]
This issue is related to #3287. It aims to add RBAC support to decoders framework and API modules, including:

- [x] Create list of actions-resources
- [x] Refactor decoders framework module into SDK + core
- [x] Add RBAC decorators to decoders SDK
- [x] Add integration tests

Subtasks:
- [x] GET /decoders
- [x] GET /decoders/files
- [x] GET /decoders/files/{file}/download
- [x] GET /decoders/parents
- [x] GET /decoders/{decoder_name}

**Comment by AdriiiPRodri** [comment]
### **API decoders endpoints RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| GET | /decoders | decoders:read | decoder:file | 
| GET | /decoders/files | decoders:read | decoder:file | 
| GET | /decoders/files/{file}/download | decoders:read | decoder:file | 
| GET | /decoders/parents | decoders:read | decoder:file |

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We've refactored the entire decoder module. After refactoring we added support for RBAC.
Finally, we have adapted the existing integrated tests, this is the result of these:

### Integrated tests
```bash
adriiiprodri@Wazuh python -m pytest -vv ~/Desktop/git/wazuh/api/test/integration/test_decoders_endpoints.tavern.yaml
======================================================================================= test session starts ========================================================================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 23 items                                                                                                                                                                                 

../../test_decoders_endpoints.tavern.yaml::GET /decoders PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders[file] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders[path] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders[name] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders[position] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders[status] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name} PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[file] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[path] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[name] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[position] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/{decoder_name}[status] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/files PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/files[file] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/files[path] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/files[status] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents[file] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents[name] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents[path] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents[position] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/parents[status] PASSED
../../test_decoders_endpoints.tavern.yaml::GET /decoders/files/{file}/download PASSED

============================================================================== 23 passed, 5 warnings in 8.79 seconds ===============================================================================
```

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

Currently the tests for the decoders module in **white** mode are finished. We cover all endpoints with several use cases tested. **Each mode will have its own environment** which will be configured before running the tests. This way we can fully **automate** them.

Best regards,
Adri

### Environment configuration
| Resource     | List                                                        |
|--------------|-------------------------------------------------------------|
| decoder:file | 0005-wazuh_decoders.xml 0064-cisco-asa_decoders.xml         |
|              | 0100-fortigate_decoders.xml 0160-netscaler_decoders.xml ... |

| Actions       | Resources    | Allow                                               | Deny |
|---------------|--------------|-----------------------------------------------------|------|
| decoders:read | decoder:file | 0005-wazuh_decoders.xml 0160-netscaler_decoders.xml |      |

### Tests result
```bash
adriiiprodri@Wazuh python -m pytest -vv  ~/Desktop/git/wazuh/api/test/integration/test_rbac_white_decoders_endpoints.tavern.yaml
====================================== test session starts ======================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 4 items                                                                               

../test_rbac_white_decoders_endpoints.tavern.yaml::GET DECODERS RBAC PASSED               [ 25%]
../test_rbac_white_decoders_endpoints.tavern.yaml::GET DECODERS FILES RBAC PASSED         [ 50%]
../test_rbac_white_decoders_endpoints.tavern.yaml::GET DECODERS FILES RBAC (Download) PASSED [ 75%]
../test_rbac_white_decoders_endpoints.tavern.yaml::GET DECODERS PARENTS RBAC PASSED       [100%]

============================= 4 passed, 1 warnings in 59.66 seconds =============================
```

**Comment by AdriiiPRodri** [comment]
## Status update

We have added the remaining tests for **black** mode. 

### Environment configuration
| Resource     | List                                                        |
|--------------|-------------------------------------------------------------|
| decoder:file | 0005-wazuh_decoders.xml 0064-cisco-asa_decoders.xml         |
|              | 0100-fortigate_decoders.xml 0160-netscaler_decoders.xml ... |

| Actions       | Resources    | Allow | Deny                                                |
|---------------|--------------|-------|-----------------------------------------------------|
| decoders:read | decoder:file |       | 0005-wazuh_decoders.xml 0160-netscaler_decoders.xml |

### Tests result
```bash
adriiiprodri@Wazuh python -m pytest -vv  ~/Desktop/git/wazuh/api/test/integration/test_rbac_black_decoders_endpoints.tavern.yaml    
====================================== test session starts ======================================
platform linux -- Python 3.5.3, pytest-4.5.0, py-1.8.0, pluggy-0.13.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/adriiiprodri/Desktop/git/wazuh/api
plugins: tavern-0.28.0
collected 4 items                                                                               

../test_rbac_black_decoders_endpoints.tavern.yaml::GET DECODERS RBAC PASSED               [ 25%]
../test_rbac_black_decoders_endpoints.tavern.yaml::GET DECODERS FILES RBAC PASSED         [ 50%]
../test_rbac_black_decoders_endpoints.tavern.yaml::GET DECODERS FILES RBAC (Download) PASSED [ 75%]
../test_rbac_black_decoders_endpoints.tavern.yaml::GET DECODERS PARENTS RBAC PASSED       [100%]

============================= 4 passed, 1 warnings in 64.10 seconds =============================
```
