### ISSUE TITLE
Add RBAC support to cluster and manager endpoints

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4126]
This issue is related to #3287. It aims to add RBAC support to cluster/manager framework and API modules, including:

- [x] Create list of actions-resources
- [x] Refactor cluster/manager framework module into SDK + core
- [x] Add RBAC decorators to cluster/manager SDK

Subtasks:
- Cluster:
- [x] GET /cluster/config
- [x] GET /cluster/configuration/validation
- [x] GET /cluster/healthcheck
- [x] GET /cluster/healthcheck/{node_id}
- [x] GET /cluster/node
- [x] GET /cluster/nodes
- [x] GET /cluster/nodes/{node_id}
- [x] PUT /cluster/restart
- [x] GET /cluster/status
- [x] GET /cluster/{node_id}/configuration
- [x] GET /cluster/{node_id}/configuration/validation
- [x] GET /cluster/{node_id}/configuration/{component}/{configuration}
- [x] DELETE /cluster/{node_id}/files
- [x] GET /cluster/{node_id}/files
- [x] PUT /cluster/{node_id}/files
- [x] GET /cluster/{node_id}/info
- [x] GET /cluster/{node_id}/logs
- [x] GET /cluster/{node_id}/logs/summary
- [x] PUT /cluster/{node_id}/restart
- [x] GET /cluster/{node_id}/stats
- [x] GET /cluster/{node_id}/stats/analysisd
- [x] GET /cluster/{node_id}/stats/hourly
- [x] GET /cluster/{node_id}/stats/remoted
- [x] GET /cluster/{node_id}/stats/weekly
- [x] GET /cluster/{node_id}/status
- Manager:
- [x] GET /manager/configuration
- [x] GET /manager/configuration/validation
- [x] GET /manager/configuration/{component}/{configuration}
- [x] DELETE /manager/files
- [x] GET /manager/files
- [x] PUT /manager/files
- [x] GET /manager/info
- [x] GET /manager/logs
- [x] GET /manager/logs/summary
- [x] PUT /manager/restart
- [x] GET /manager/stats
- [x] GET /manager/stats/analysisd
- [x] GET /manager/stats/hourly
- [x] GET /manager/stats/remoted
- [x] GET /manager/stats/weekly
- [x] GET /manager/status

**Comment by davidjiglesias** [comment]
`GET /cluster/config` --> Endpoint renamed to `GET /cluster/local/config`. Endpoint response now uses AffectedItemsWazuhResult.
`GET /cluster/configuration/validation` --> Endpoint now accepts a parameter `list_nodes` to specify a list of nodes to validate. It will try to validate all nodes if parameter list_nodes is not specified.

**Comment by davidjiglesias** [comment]
### **API cluster endpoints RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| GET | /cluster/config | cluster:read_config | node:id | 
| GET | /cluster/configuration/validation | cluster:read_config | node:id |
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/healthcheck | cluster:read_config | node:id |

**Comment by davidjiglesias** [comment]
| GET | /cluster/healthcheck | cluster:read_config | node:id |

**Comment by davidjiglesias** [comment]
### **MANAGER ENDPOINTS CHANGES:**

**Comment by davidjiglesias** [comment]
### **API manager endpoints RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| GET | /cluster/local/config | cluster:read_config | node:id | 
| GET | /cluster/configuration/validation | cluster:read_config | node:id |
| GET | /cluster/healthcheck | cluster:read_config | node:id | 
| GET | /cluster/local/info | cluster:read_config | node:id | 
| GET | /cluster/nodes | cluster:read_config | node:id | 
| PUT | /cluster/restart | cluster:restart | node:id | 
| GET | /cluster/status | cluster:status | * | 
| GET | /cluster/{node_id}/configuration | cluster:read_config | node:id | 
| GET | /manager/configuration/{component}/{configuration} | cluster:read_config | node:id |
| DELETE | /cluster/{node_id}/files | cluster:delete_file | node:id file:path |
| GET | /cluster/{node_id}/files | cluster:read_file | node:id file:path |
| PUT | /cluster/{node_id}/files | cluster:upload_file | node:id |
| GET | /cluster/{node_id}/logs | cluster:read_config | node:id |
| GET | /cluster/{node_id}/logs/summary | cluster:read_config | node:id |
| GET | /cluster/{node_id}/stats | cluster:read_config | node:id |
| GET | /cluster/{node_id}/stats/analysisd | cluster:read_config | node:id |
| GET | /cluster/{node_id}/stats/hourly | cluster:read_config | node:id |
| GET | /cluster/{node_id}/stats/remoted | cluster:read_config | node:id |
| GET | /cluster/{node_id}/stats/weekly | cluster:read_config | node:id |
| GET | /cluster/{node_id}/status | cluster:read_config | node:id |
