### ISSUE TITLE
RemoteD defunct process

### ISSUE THREAD

**Issue by eduzuchetti** [wazuh/wazuh#4134]
|Wazuh Manager Version|Wazuh API Version|ELK Stack Version|Module|
|---|---|---|---|
|3.10.0-1|3.10.0-1|7.3.2-1|remoted|

I have a Wazuh Manager and Wazuh API on AWS EC2 instance (ELK is on another instance) and sometimes, all of agents are disconnected. 

On logs, I see the following error:
```
2019/10/22 13:05:19 ossec-remoted: CRITICAL: (1206): Unable to Bind port '1514' due to [(98)-(Address already in use)]
```

And searching for this port, I found this zoombie process of remoted that still running even after I stop all the Wazuh services (systemctl stop wazuh-manager wazuh-api). I tried to kill it (kill -9 or -15) but nothing happens

```
[root@ip-9-9-9-9 logs]# ps aux | grep -v grep | grep Z
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ossecr    6268 37.7  0.0      0     0 ?        Zl   Oct18 2071:39 [ossec-remoted] <defunct>
```

The only pattern that I've been observed is that this problem occurs sometimes when I restart the wazuh-manager service to solve another problem: All agents disconnected, but with a different error:
```
2019/10/21 18:00:12 ossec-remoted: CRITICAL: At pthread_mutex_destroy(): Device or resource busy
```
Today, the only solution I've found is to reboot the instance to get rid of this defunct process

Any help will be appreciated,

Regards

**Comment by vikman90** [comment]
Hi @eduzuchetti, 

Apologies for not replying to this threa. This bug was fixed by #3988 and released in v3.10.1

Hope you haven't found that error again. Should this problem persist, please reopen this issue.
Best regards.
