### ISSUE TITLE
systemctl status wazuh-api failed 

### ISSUE THREAD

**Issue by khaleehh** [wazuh/wazuh#4141]
Hi, 
I have error whrn checking the "systemctl status wazuh-api"

[root@wazuhmanager auth]# systemctl status wazuh-api
● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-10-23 12:09:21 UTC; 34min ago
     Docs: https://documentation.wazuh.com/current/user-manual/api/index.html
  Process: 50026 ExecStop=/bin/kill -HUP $MAINPID (code=exited, status=1/FAILURE)
  Process: 50010 ExecStart=/usr/bin/node /var/ossec/api/app.js (code=exited, status=1/FAILURE)
 Main PID: 50010 (code=exited, status=1/FAILURE)

Oct 23 12:09:21 wazuhmanager kill[50026]: -q, --queue <sig>      use sigqueu...)
Oct 23 12:09:21 wazuhmanager kill[50026]: -p, --pid              print pids ...m
Oct 23 12:09:21 wazuhmanager kill[50026]: -l, --list [=<signal>] list signal...e
Oct 23 12:09:21 wazuhmanager kill[50026]: -L, --table            list signal...s
Oct 23 12:09:21 wazuhmanager kill[50026]: -h, --help     display this help a...t
Oct 23 12:09:21 wazuhmanager kill[50026]: -V, --version  output version info...t
Oct 23 12:09:21 wazuhmanager systemd[1]: wazuh-api.service: control process ...1
Oct 23 12:09:21 wazuhmanager kill[50026]: For more details see kill(1).
Oct 23 12:09:21 wazuhmanager systemd[1]: Unit wazuh-api.service entered fail....
Oct 23 12:09:21 wazuhmanager systemd[1]: wazuh-api.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
[root@wazuhmanager auth]#

**Comment by powderedegg** [comment]
What do the api and system logs say?    They're normally found in /var/ossec/logs/api.log

**Comment by crd1985** [comment]
Hi @khaleehh ,

I would recommend opening a new discussion in https://groups.google.com/forum/#!forum/wazuh and giving as much detail as possible. As pointed in the previous comment, you could take a look to the api log in `/var/ossec/logs/api.log`.

The GitHub repo should only be used to report bugs or request new features.

Sorry for the inconveniences.

Regards,
Daniel Ruiz
