### ISSUE TITLE
wazuh-agent.msi unattended install doesn't use FQDN

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#4149]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | wazuh-agent.msi | Agent | Packages | Windows 10 |

I'm trying out the `wazuh-agent.msi` for unattended installs for windows. However, it the agent appears to get registered with the computer and and not the FQDN name. Is there any way of using FQDN instead?

```
Invoke-WebRequest -Uri https://packages.wazuh.com/3.x/windows/wazuh-agent-3.10.2-1.msi -OutFile wazuh-agent.msi;
wazuh-agent.msi /q ADDRESS="..." AUTHD_SERVER="..." PASSWORD="..."
```

**Comment by Zenidd** [comment]
Hello @rossengeorgiev,

> Is there any way of using FQDN instead?

Our [Deployment variables for Windows](https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_windows.html#deployment-variables-for-windows) document contains a complete listing of the different deployment variables for windows. I think you can set the agent name to its FQDN name using the `WAZUH_AGENT_NAME` variable.

As you said, by default, the Agent name is taken through the hostname.

![image](https://user-images.githubusercontent.com/14923294/67772309-2538f080-fa5a-11e9-9c3e-c9db28926cb9.png)

Let me know if you already tried this or if I'm not getting the problem right.

Greetings, JP Sáez

**Comment by rossengeorgiev** [comment]
I managed achieve this with the following powershell:

```powershell
$AGENT_NAME = ([System.Net.Dns]::GetHostByName(($env:computerName))).Hostname

./wazuh-agent.msi" /q WAZUH_.... WAZUH_AGENT_NAME="$AGENT_NAME"
```

**Comment by Zenidd** [comment]
Hello again @rossengeorgiev,

I'm glad you did it. I thank you for writing down your solution as it can help the team and other community members. 

I'm also closing this thread. If you still have any doubts or need guidance, please open a new discussion in our forum: https://groups.google.com/forum/#!forum/wazuh or join us in our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/). 



Greetings, JP Sáez

**Comment by danilosantossdbrasil** [comment]
Hi Guys,

Try.

powershell Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.7.1-1.msi -OutFile ${env.tmp}\wazuh-agent; msiexec.exe /i ${env.tmp}\wazuh-agent /q WAZUH_MANAGER='URL-WAZUH' WAZUH_AGENT_GROUP='NAME-GROUP' WAZUH_AGENT_NAME="$env:COMPUTERNAME" WAZUH_REGISTRATION_SERVER='URL-WAZUH'
