### ISSUE TITLE
Bug downgrade Wazuh 

### ISSUE THREAD

**Issue by lukelee1987** [wazuh/wazuh#4152]
How can I downgrade from Wazuh 3.10.x to 3.9.3, to this specific version? I can't find any guide online regarding the downgrading.

**Comment by DaveVG1** [comment]
Hi @lukelee1987,

As I've seen you had already questioned this in the mailing list. Another team member has already answered this question there.

For that reason, I'm closing this issue. If you have any trouble regarding this topic (or another), please use the mailing list for further questions. Thanks.

Best regards,
David
