### ISSUE TITLE
Connectivity issues with Wazuh Cluster and load balancer.

### ISSUE THREAD

**Issue by JaviMJ** [wazuh/wazuh#4153]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-1 | Wazuh Cluster | Manager | Packages | CentOS 7.4 |

Hi Wazuh team.

Currently I am setting up a Wazuh Cluster, I have 2 Wazuh workers and 1 Wazuh master. At the beginning I did not use any load balancer and everything works fine, but I recently install a Nginx in one of the workers in order to balancing the requests sended by the Wazuh agents (I am not sure if is a good idea have a balancer and a wazuh worker in the same machine). After configurated it like in Wazuh's documentation the agents are no longer able to connect with the workers. The load balancer and worker of Wazuh have this IP address '192.168.240.58'.
In the log of the agents are printing continuously the following message:
<pre>ossec-agentd[65961] start_agent.c:80 at connect_server(): INFO: Trying to connect to server (192.168.240.58:1518/tcp).</pre>
In the log of the Wazuh master  are printing continuously the following message:
<pre>ossec-remoted[53416] secure.c:344 at HandleSecureMessage(): WARNING: (1213): Message from '192.168.240.58' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.</pre>

Load balancer is serving port 1518 and forwarding to 1514. This is the nginx configuration:
<pre>stream {

    upstream cluster {
        hash $remote_addr consistent;
        server wazuh_master:1514;
        server wazuh_worker01:1514;
        server wazuh_worker02:1514;
    }
    upstream master {
        server wazuh_master:1515;
    }
    server {
        listen 1518;
        proxy_pass cluster;
    }
    server {
        listen 1515;
        proxy_pass master;
    }
}</pre>

This is the agent configuration:
```
<client>
	 <server>
		 <address>192.168.240.58</address>
		 <port>1518</port>
		 <protocol>tcp</protocol>
	 </server>
	 <config-profile>centos, centos7, centos7.4</config-profile>
	 <notify_time>10</notify_time>
	 <time-reconnect>60</time-reconnect>
	 <auto_restart>yes</auto_restart>
	 <crypto_method>aes</crypto_method>
</client>
```

I already checked that the agent and the worker were able to connect:
<pre>[root@host ~]# telnet 192.168.240.58 1518
Trying 192.168.240.58...
Connected to 192.168.240.58.
Escape character is '^]'.

[root@host ~]# telnet 192.168.240.58 1514
Trying 192.168.240.58...
Connected to 192.168.240.58.
Escape character is '^]'.</pre>

And this were the connections of the worker on port 1518:
<pre>[root@wazuh_worker02 ~]# netstat -tuplan | grep 1518
tcp        0      0 0.0.0.0:1518            0.0.0.0:*               LISTEN      59971/nginx: master
tcp        0      0 192.168.240.58:1518     192.168.240.78:34984    TIME_WAIT   -
tcp        0      0 192.168.240.58:1518     192.168.240.78:34988    TIME_WAIT   -
tcp        0      0 192.168.240.58:1518     192.168.240.78:34980    TIME_WAIT   -
tcp        0      0 192.168.240.58:1518     192.168.240.78:34990    TIME_WAIT   -
tcp        0      0 192.168.240.58:1518     192.168.240.78:34978    TIME_WAIT   -
tcp        0      0 192.168.240.58:1518     192.168.240.78:34986    TIME_WAIT   -

</pre>

Could someone give me a hand with this issue?

Regards.

**Comment by crd1985** [comment]
Hi @JaviMJ,

please, have a look to these resources:
- https://documentation.wazuh.com/3.10/user-manual/configuring-cluster/advanced-settings.html#pointing-agents-to-the-cluster-with-a-load-balancer
- https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/

If you still have any doubts, please open a new discussion in our forum: https://groups.google.com/forum/#!forum/wazuh.

We usually keep Github for reporting bugs and registering feature requests.

I hope you understand and sorry for the inconveniences.

Regards,
Daniel Ruiz
