### ISSUE TITLE
How to use wazuh agent to collect host's custom log files?

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#4157]
|Wazuh version:3.9.4
|Component: Wazuh-manager
|Install type:Manager
|Install method:Packages
|Platform|CentOS 7.5

Hello,I want use ossec-logcollector module to collect host's custom log files but I find two problems

1. I just want collect the whole log files,don't want to decoder or match rules
Because wazuh agent can collect log files to manager,but manager will decoder these log files,and only show some alerts when match the rules.But I just want to collect the whole log and send the log files to my Nifi Server(a open source data routing, transformation project).So if I just use <localfile> tag to select my log files,it will not work.And I don't want to use `archives.json`，because it's too big.So I feel confused when I  use wazuh agent，I think  wauzh can do it，but I have no useful idea.

2. how to set <log_format> when my log files just create by log4j?
My  applications’s log files  always create by log4j.My log files contents like these:

![image](https://user-images.githubusercontent.com/15324125/67649250-3a871f80-f973-11e9-91df-c7f474532cf6.png)

I try to look up  document
https://documentation.wazuh.com/3.9/user-manual/reference/ossec-conf/localfile.html#log-format

but I don't know which one could support log4j log files,So I want to  your help，thank you!

**Comment by Lopuiz** [comment]
Hello,

About generate alerts for all logs you can create rule and decoder that match them. A rule and decoder that match these logs could be the following:

```xml
<decoder name="my-program">
   <prematch>^log   [\d+:\d+:\d+.\d+]  [info]|^error  [\d+:\d+:\d+.\d+]  [warning]</prematch>
</decoder>
```

```xml
<rule id="100000" level="10">
   <decoded_as>my-program</decoded_as>
   <description>Log grouped in (program) messages</description>
</rule>
```

They must be added int `/var/ossec/etc/rules/local_rules.xml` and `/var/ossec/etc/decoders/local_decoders.xml`.

Concerning capturing log using Logcollector,  we haven't any option for `log4j` but you can try `multi-line` option to capture logs that have multiples lines.

Your program doesn't seem to have the number of lines determined. Would there be anyway your program could have the number of log lines determined? This would facilitate log forwarding.

For example, the error logs which have 7 lines are saved in error.log file and the info logs which have 1 line are saved in info.log

We have a mailing list and Slack channel where you can subscribe and do further questions about it. For more information follow the link: [community](https://wazuh.com/community/)

Best regards,
Eva

**Comment by xufengnian** [comment]
Thanks a lot,the solution is use decoder and rule to create alert,I think it's best way to solve my problems!
