### ISSUE TITLE
[Feature request] Dynamic Software Reconciliation for Wazuh

### ISSUE THREAD

**Issue by paroma96** [wazuh/wazuh#4158]
Hi, Team!

It would be great Wazuh works with a DSR (Dynamic Software Reconciliation) module. This would check an update's reliability by querying Microsoft's Technet and Linux YUM in order to verify its patches' file-level manifests. In case its source is not legitime, it will unauthorize the installation of the update in which a suspicious patch file has been found and report it by triggering alerts.

In this way, it would be possible to automatize every legitime Microsoft/Linux update by compiling its patches and identifying its source in case it causes any kind of problem to promote possible changes, some kind of automatic feedback for future releases do fix/improve it.

To do so, a way to perform those queries to both Microsoft's Technet and Linux YUM dependencies should be researched to obtain the patches' file-level manifests, warn about issues found with specific patches' installation, etc.

Then, the Wazuh manager should extract its fields to analyze that information (format, type, patch's name, what it solves, version, public key, etc) by comparing it with a database in which trustworthy sources' data is stored, and validate the updates on the agents' side, authorizing the installation, so the agents should also count on a system configuration that let them control the reception and installation of these updates and report it to the manager for allowance.

It would also be necessary to log all the events related to this process and trigger alerts to let users know the status of these updates (not legitime, (un)authorized, completed (un)successfully, etc).

I hope you find this information helpful for the task. Let me know if I may be of further help.

Regards,
Pablo Rodríguez

**Comment by MiguelCasaresRobles** [comment]
Hello team,

We found a better approach.


The Wazuh-Agents can detect changes in the patches in real-time by using FIM. Agents will send this information to the Manager and in the Manager, we can use a CBD list to create a white/black list of trusted/untrusted packages. 

By doing so, the Manager can generate an alert if the package installed matches the list mentioned before. What’s more, we can use our VirusTotal integration to detect if the package is identified by the database as malware.

Regards,

Miguel Casares
