### ISSUE TITLE
No logs to process in bucket even when logs are present

### ISSUE THREAD

**Issue by gopivalleru** [wazuh/wazuh#4159]
I'm getting "No logs to process in bucket" when I tried to integrate wazuh with cloudtrail and guardduty. 

version: 3.9.2

Please provide me a way to debug or figure out this issue.

2019/10/28 20:12:42 2019/10/28 20:12:42 wazuh-modulesd:aws-s3[30976] wm_aws.c:409 at wm_aws_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket wazuh-cloudtrail-xxx --aws_account_id xxxx --trail_prefix /cloudtrail/ --only_logs_after 2019-OCT-20 --regions us-west-2 --type cloudtrail --debug 3 --skip_on_error

2019/10/28 20:12:43 wazuh-modulesd:aws-s3[30976] wm_aws.c:443 at wm_aws_run_s3(): DEBUG: Bucket: xxxxx  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 3
DEBUG: +++ Working on xxxx - us-west-2
DEBUG: +++ Marker: /cloudtrail/AWSLogs/xxxx/CloudTrail/us-west-2/2019/10/20

DEBUG: +++ No logs to process in bucket: xxxx/us-west-2
DEBUG: +++ DB Maintenance

**Comment by druizz90** [comment]
Hi @gopivalleru,

You should remove slashes (`/`) for `<path>` tag in the wodle configuration for getting the logs. Use slashes when the path to the logs includes more directories, but not at the start or at the end.

For example, with your configuration:

```XML

  <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
        
    <bucket type="cloudtrail">
      <aws_profile>default</aws_profile>
      <name>wazuh-cloudtrail-xxx</name>
      <path>cloudtrail</path>
      <only_logs_after>2019-OCT-20</only_logs_after>
    </bucket>

  </wodle>

```

I hope that you can process the logs after doing that.

Best regards,

Demetrio.

**Comment by gopivalleru** [comment]
Thats for the suggestion. Now I'm getting below exception 

DEBUG: +++ Error marking log cloudtrail/AWSLogs/xxxx/CloudTrail/us-west-2/2019/10/29/xxxx_CloudTrail_us-west-2_20191029T0445Z_X6ARF7m8918mTQt7.json.gz as completed: database is locked
DEBUG: +++ Unexpected error: database is locked
ERROR: 1 Unexpected error querying/working with objects in S3: database is locked

**Comment by gopivalleru** [comment]
This is occurring at self.db_connector.execute(self.sql_mark_complete.format(
                    table_name=self.db_table_name,
                    bucket_path=self.bucket_path,
                    aws_account_id=self.aws_account_id,
                    log_key=log_file['Key'],
                    created_date=self.get_creation_date(log_file)
                ))

in mark_complete method for class AWSCustomBucket. 
This is only happening for cloudtrail but not for guardduty.

**Comment by gopivalleru** [comment]
This looks good now after cleaning up sqllite db file and restarting and waiting for cloudtrail logs to get loaded.

**Comment by usmanaa10** [comment]
Hi @gopivalleru ,
                   I am getting the same error, 

![DB Error](https://user-images.githubusercontent.com/66419518/175938752-c262a2f1-b833-4369-ac34-406bf47bf8ef.png)

can you share what commands should i run to solve this issue.

Note: Couple of days ago i was running wodle for cloudwatch manually and it give me no error but today i did same activity and i got the above error.

**Comment by gopivalleru** [comment]
@usmanaa10 I did this

> This looks good now after cleaning up sqllite db file and restarting and waiting for cloudtrail logs to get loaded.

**Comment by Abhilash-sandupatla** [comment]
Hi @usmanaa10   @gopivalleru 
Almost the same issue I am getting. I have configured cloud trail, it worked fine for some time. But After some time, data/events were not showing.

I see below error log in /var/ossec/etc/ossec.conf

I see the database/disk is full, what exactly I have to delete/cleanup ?

2022022/07/06 15:10:50 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 7
2022/07/06 15:10:50 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Unexpected error querying/working with objects in S3: database or disk is full

2022/07/06 15:10:50 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.
2022/07/06 15:10:50 wazuh-modulesd:aws-s3: WARNING: Interval overtaken.
2022/07/06 15:10:50 wazuh-modulesd:aws-s3: INFO: Starting fetching of logs.
2022/07/06 15:10:50 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: phenomcloudtraillogs, Path: phenom, Type: cloudtrail, Profile: default)
2022/07/06 15:10:51 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 7
2022/07/06 15:10:51 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Unexpected error querying/working with objects in S3: database or disk is full
