### ISSUE TITLE
How configure FIM feature in a CI/CD env.

### ISSUE THREAD

**Issue by cmorell** [wazuh/wazuh#4162]
Hi all,

As you can see in the issue title I want to know how can I configure FIM in order to avoid false positive in a CI/CD environment. I mean, I want to avoid false positive for each correct deployment and only get the alert if someone is modifying the file. 

Could you give me a clue to do it?

Thanks!

**Comment by Zenidd** [comment]
Hello @cmorell,

In the [Syscheck documentation](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syscheck.html) you can read about the options below to exclude files and folders using sregex expressions with their corresponding wildcards(placed within the `<syscheck>` section of `ossec.conf`).

- [ignore](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syscheck.html#ignore)
- [directories(restrict option)](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syscheck.html#directories)

If you don't manage to limit the scan through its configuration we can later create custom silencing rules to avoid alerts flooding.  It would be really useful a more detailed description of your use case (i.e. files that cause false positives, your syscheck configuration .. etc) we can help you further.

Greetings, JP Sáez

**Comment by cmorell** [comment]
Hi JP Sáez,

Thanks for your answer.
Let me explain a little bit more. I would like to monitor if someone is changing production code. 
The problem is that I want to avoid approved deployments and I don't know how can I do it. 

We can deploy code when we want, so this need to be automatically

**Comment by Zenidd** [comment]
Hello again @cmorell,

> Let me explain a little bit more. I would like to monitor if someone is changing production code.
> The problem is that I want to avoid approved deployments and I don't know how can I do it.

- How does the file system you have to monitor behave?

- What attributes can we check to distinguish between an authorized change and a malicious modification? Would be the user an effective way to check?

We should find a difference between the allowed changes and the malicious one, each use case is different so the more information you bring us, the more we can help you. On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).


Greetings, JP Sáez

**Comment by Zenidd** [comment]
Hello @cmorell,

I'm closing this ticket due to inactivity. Do not hesitate to reopen it if you have more questions. For further questions apart from this one, we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez
