### ISSUE TITLE
KeyError: 'CommonPrefixes': Integration with AWS config

### ISSUE THREAD

**Issue by gopivalleru** [wazuh/wazuh#4166]
Version: 3.9.2

I'm getting below exception while trying to integrate aws config with Wazuh.

Unknown error: 'CommonPrefixes'
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 2272, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 2239, in main
    bucket.iter_bucket(options.aws_account_id, options.regions)
  File "/var/ossec/wodles/aws/aws-s3.py", line 710, in iter_bucket
    self.iter_regions_and_accounts(account_id, regions)
  File "/var/ossec/wodles/aws/aws-s3.py", line 993, in iter_regions_and_accounts
    account_id = self.find_account_ids()
  File "/var/ossec/wodles/aws/aws-s3.py", line 862, in find_account_ids
    Delimiter='/')['CommonPrefixes']
KeyError: 'CommonPrefixes'

But CommonPrefixes is even a key in the output of list_objects_v2 for config just like guardduty but it is present for cloudtrail. Anyway looks like for guardduty wazuh is not trying to get find_account_ids which makes sense but for config it is being done which is not necessary and not being handled.

I've event tried your latest aws-s3.py which is throwing same error for config.

Bucket: wazuh-config-xxx
Prefix: config/AWSLogs/
list_objects_v2: {'ResponseMetadata': {'RequestId': 'xxx', 'HostId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'xxx', 'x-amz-request-id': 'xxx', 'date': 'Wed, 30 Oct 2019 00:12:11 GMT', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'wazuh-config-xxx', 'Prefix': 'config/AWSLogs/', 'Delimiter': '/', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 0}

>>> s3.list_objects_v2(Bucket='wazuh-guardduty-xxx', Prefix='guardduty/AWSLogs/', Delimiter='/')
{'ResponseMetadata': {'RequestId': 'xxx', 'HostId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'xxx', 'x-amz-request-id': 'xxx', 'date': 'Wed, 30 Oct 2019 00:14:04 GMT', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 1}, 'IsTruncated': False, 'Name': 'wazuh-guardduty-xxx', 'Prefix': 'guardduty/AWSLogs/', 'Delimiter': '/', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 0}

>>> s3.list_objects_v2(Bucket='wazuh-cloudtrail-xxx', Prefix='cloudtrail/AWSLogs/', Delimiter='/')
{'ResponseMetadata': {'RequestId': 'xxx', 'HostId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'xxx', 'x-amz-request-id': 'xxx', 'date': 'Wed, 30 Oct 2019 00:15:05 GMT', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 1}, 'IsTruncated': False, 'Name': 'wazuh-cloudtrail-xxx', 'Prefix': 'cloudtrail/AWSLogs/', 'Delimiter': '/', 'MaxKeys': 1000, 'CommonPrefixes': [{'Prefix': 'cloudtrail/AWSLogs/xxxx/'}], 'EncodingType': 'url', 'KeyCount': 1}

**Comment by druizz90** [comment]
Hi @gopivalleru,

It seems that you haven't got logs for `GuardDuty` service. We introduced an improvement for checking if there are logs in the specified path in `3.10` version (https://github.com/wazuh/wazuh/blob/3.10/wodles/aws/aws_s3.py#L800-L806).

Could you paste your wodle configuration (it is placed in `ossec.conf` file)?

Furthermore, I suggest to you to use our mail list (https://groups.google.com/forum/#!forum/wazuh) when you have an issue like this. We check more frequently our mail list and we will give a better support for you :)

Best regards,

Demetrio.

**Comment by gopivalleru** [comment]
@druizz90 I've also used your latest aws-s3.py file yesterday. In the new file wazuh is handling exception from list_objects_v2 as "ERROR: Invalid type of bucket. The bucket was set up as 'config' type and this bucket does not contain log files from this type. Try with other type: {'guardduty', 'cloudtrail', 'custom', 'vpcflow'}". But I think the error handling is not done properly and the new version is actual masking the real exception. The real underlying exception is still KeyError: 'CommonPrefixes' because the output of 
self.client.list_objects_v2(Bucket=self.bucket, Prefix=self.get_base_prefix(), Delimiter='/')
doesn't contain key with name "CommonPrefixes" when we are using bucket type of config just like bucket type gurardduty. The logs path for config doesn't contain account id. This is happening when find_account_ids method is being called. 


/var/ossec/wodles/aws/aws-s3 --bucket wazuh-config-xxx --trail_prefix config --type config --debug 3
+++ sys args: ['--bucket', 'wazuh-config-xxx', '--trail_prefix', 'config', '--type', 'config', '--debug', '3']
DEBUG: +++ Debug mode on - Level: 3
DEBUG custom: dbpath: /var/ossec/wodles/aws/s3_cloudtrail.db
DEBUG: +++ In iter_bucket
{'ResponseMetadata': {'RequestId': 'xxx', 'HostId': 'xxx', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-id-2': 'xxx', 'x-amz-request-id': 'xxx', 'date': 'Tue, 29 Oct 2019 23:37:36 GMT', 'x-amz-bucket-region': 'us-west-2', 'content-type': 'application/xml', 'transfer-encoding': 'chunked', 'server': 'AmazonS3'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'wazuh-config-xxx', 'Prefix': 'config/AWSLogs/', 'Delimiter': '/', 'MaxKeys': 1000, 'EncodingType': 'url', 'KeyCount': 0}
ERROR: Invalid type of bucket. The bucket was set up as 'config' type and this bucket does not contain log files from this type. Try with other type: {'guardduty', 'cloudtrail', 'custom', 'vpcflow'}

**Comment by gopivalleru** [comment]
Posted this issue to google maillist.
https://groups.google.com/forum/#!topic/wazuh/3aq47N1rwvY
