### ISSUE TITLE
Consider and remediate daylight saving induced false positives

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#4167]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v2.0 or later  | FIM | Manager/Agent | All | All|

Hi team,

**Windows daylight saving automatic hour adjustment may trigger false-positive FIM alerts in Windows NTFS file systems**:

- The reason for this behavior lies in the way NTFS and FAT store file times: NTFS stores time in UTC format, while FAT uses local time (_The timestamps will always be relative to current local time_).

- When times of these two different formats are compared, one format has to be converted into the other first. In either way, Windows uses the current DST status as well as the current time zone for its calculations. Consequently, the result of this comparison is dependent from current system settings with the effect that file times that used to be the same show up as different after a DST switch or when the time zone has changed. This is how daylight saving adjustment can lead to an hour off.

This unexpected "update" in file timestamps triggers false file modification FIM alerts (_It happens twice a year on DST changes_)

[This MSDN document](https://docs.microsoft.com/es-es/windows/win32/sysinfo/file-times?redirectedfrom=MSDN) explains how to account for daylight saving time when converting file time to local time, using a sequence of functions. 

Although it may seem that this just messes up events for auditing, it really does make sense as the timestamps are always relative to current local time.

As a workaround, there are two easy options to avoid the DST change induced flooding:

- Making the Windows agents skip (do not collect) the files modification time: Add the option `check_mtime=no` in every FIM `<directories>` stanza.

- Using a custom a rule to silence alerts regarding file changes, if only the modification time changed. i.e:
```XML
<rule id="100001" level="0">
    <if_sid>550</if_sid>
    <field name="changed_fields">^mtime,$</field>
    <description>Modification time changed.</description> 
  </rule>
```

Greetings, JP Sáez

**Comment by vnil1994** [comment]
This bug affected us quite hard in the last few days. We had over 300,000 "checksum changed" events because of this.

**Comment by Theoooooo** [comment]
To clarify the situation, i also got this issue on LVM partition ...

**Comment by jotacarma90** [comment]
This issue will be solved in:
https://github.com/wazuh/wazuh/pull/6801
And this PR in wazuh/QA, add an integration test to check this bug:
https://github.com/wazuh/wazuh-qa/pull/960
