### ISSUE TITLE
Add the option to capture modification time for Windows registries.

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#4173]
Hi team,

Currently, we don't have the option to capture the modification time (`mtime`) for Windows registries using `syscheck`. In the alerts, we are showing the timestamp of the event, which may not match the time when the registry was modified. 

The modification time of registries is relevant information regarding security and it is also in the system and it's something that we should add to the alerts.

It seems we can use the following field: `Registry Timestamps`: https://helgeklein.com/blog/2010/06/registry-tricks/

Best regards,
Sergio.

**Comment by vikman90** [comment]
@sergiospa I think we can achieve that through function [`RegQueryInfoKey()`](https://docs.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regqueryinfokeya). Its last parameter is the datetime of the last write.

Adding this task to the roadmap.
Thanks!

**Comment by sergiospa** [comment]
Thank you @vikman90 !!

**Comment by vikman90** [comment]
Hi,

This request has been commited (9732fd9f67920c58d27e8da34e39a99dcd874df3) as a feature for task #3319.

Let me close this issue.
