### ISSUE TITLE
CIS_Debian9_L1 - Rule 3046 typo results in consistent failure of check command

### ISSUE THREAD

**Issue by scott239** [wazuh/wazuh#4180]
Wazuh Version: 3.10.2
Install Type: Agent
OS: Debian 10
SCA Rule File: cis_debian9_L1.yml

Line 636 in file 'cis_debian9_L1.yml' appears to have a typo in the check command, net.ipv4_forward should be net.ipv4.ip_forward.

Original Line:
`'c:grep -Rh net\.ipv4\.ip_forward /etc/sysctl.conf /etc/sysctl.d -> r:^net.ipv4_forward\s*=\s*0$'`

Corrected Line:
`'c:grep -Rh net\.ipv4\.ip_forward /etc/sysctl.conf /etc/sysctl.d -> r:^net.ipv4.ip_forward\s*=\s*0$'`

**Comment by cristgl** [comment]
Hi @scott239,

Thank you for reporting this, you are right, we will fix this as soon as possible. Just in case you didn't know, remember that you can also open a Pull Request to our [ruleset repository](https://github.com/wazuh/wazuh-ruleset) where all the rules and benchmarks are included. :)

Kind regards,
Cristina

**Comment by cristgl** [comment]
Hi @scott239, 

I've opened a PR, you can follow its updates here https://github.com/wazuh/wazuh-ruleset/pull/514.
I'm closing this issue, but feel free to reopen it if you need to!

Best regards,
Cristina
