### ISSUE TITLE
Why xml_buffer_queue_size max is 100000

### ISSUE THREAD

**Issue by pyama86** [wazuh/wazuh#4187]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.7 | ossec-syscheck | agent | all | ubuntu16 |

Hi team.
I have used wazuh with cgroups.
Because ossec-syscheck is often use cpu resouece a lot.

but, i happend this message.

`wazuh: Agent buffer: 'flooded'.`

it is means that the current queue count has reached queue_size.
I think queue_size may be a larger number depending on the system.
I would be pleased if you increase the upper limit.

**Comment by Zenidd** [comment]
Hello @pyama86,

Here are some hints to tune the agent and improve the queue/CPU usage issues:

- To reduce Syscheck CPU usage and let the events reach the queue slower, you can sleep Syscheck after a number of analyzed files. You should modify the default values:

`/var/ossec/etc/internal_options.conf ` (default values)
Sleep one second after 100 analyzed files.
```
# Syscheck checking/usage speed. To avoid large CPU/memory
# usage, you can specify how much to sleep after generating
# the checksum of X files. The default is to sleep one second
# per 100 files read.
syscheck.sleep=1
syscheck.sleep_after=100
```

You can try with sleep 1 second after 25 files analyzed.
```
syscheck.sleep=1
syscheck.sleep_after=25
```

- In TCP Agent-Manager communications taking place in networks with Loss packets issues, the lost packets resending can lead to a full queue as the events have to wait in the queue until the TCP ACK arrives.

- Restricting `ossec-agentd` resources through cgroups can lead to slow sending of events from agentd. Could you exclude `ossec-agentd` from the cgroups resources restrictions?

I hope these clarifications will help you improve the Wazuh component's performance. Count on me for further guidance.

Greetings, JP Sáez

**Comment by pyama86** [comment]
Hi @Zenidd .
Thankyou for your answer.
I didn't know `syscheck.sleep_after`.
It is probably solves my problem.
Thasnk!!!!
