### ISSUE TITLE
Display a warning message when the manager is not verified

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#4190]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.11|Manager/Agent|Manager/Agent|Packages/Sources|All|

### Description

Regarding the registration method with manager verification, we need to display a warning message when the agent runs without the -v option.

This message must indicate that the manager wasn't verified, which means that the connection may be insecure.

### Involved tasks

- [x] Add the warning message _(core)_

- [x] Documentation

**Comment by TomasTurina** [comment]
This solution isn't safe enough to ensure a secure verification of the manager:

- If the manager is replaced and becomes insecure, it can disable this option and allow connections from agents that won't be able to verify it.

- There is no way for the agents to tell the manager that ran with the -v option before starting the connection. The only way will be telling him in the request message sent, but this will be a problem for older agents that don't send this information to the manager and may be unauthorized regardless of whether they used the -v option or not.

That's why we decided to just add a warning message when the agent runs without the -v option. In this way, the manager won't be verified and the connection will be stablished, but the agent will display a log message indicating that the connection may be insecure.

**Comment by chemamartinez** [comment]
Merged #4207.
