### ISSUE TITLE
Latch remote FIM prefilter command setting

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4193]
|Wazuh version|Component|Install type|
|---|---|---|
| 3.11-31109 |Syscheck | Agent | 

The new option `<allow_prefilter_cmd>` enables `<prefilter_cmd>`. But there is no option to set `<prefilter_cmd>` locally and disallow overwriting it remotely (via _agent.conf_).

## Proposal

- Always allow `<prefilter_cmd>` locally.
- Rename `<allow_prefilter_cmd>` to `<allow_remote_prefilter_cmd>`.
- The previous setting will allow remote configuration overwrite the prefilter command.

**Comment by chemamartinez** [comment]
Merged both PR #4194 and [#2025](https://github.com/wazuh/wazuh-documentation/pull/2025).
