### ISSUE TITLE
AWS Guardduty logs not visible

### ISSUE THREAD

**Issue by shrivastavshubham34** [wazuh/wazuh#4195]
I'm using wazuh v3.9.5
Followed this article to add guard-duty to wazuh-manager.
https://documentation.wazuh.com/3.9/amazon/services/guardduty.html

I do get no error in ossec logs:
![image](https://user-images.githubusercontent.com/13406071/68252765-2ed2d300-ffdb-11e9-8342-ae372f040990.png)

But my buckets are not populating with any data.
I tested firehose using a test with the demo data feature of the kinesis firehose and saw logs coming in. But nothing after that.

Below is the ossec.conf changes:
```yaml
       <wodle name="aws-s3">
        <disabled>no</disabled>
        <interval>10m</interval>
        <run_on_start>yes</run_on_start>
        <skip_on_error>yes</skip_on_error>
        <bucket type="cloudtrail">
          <name>bucket-1</name>
        </bucket>
        <bucket type="guardduty">
          <name>bucket-2</name>
        </bucket>
        <service type="inspector">
        </service>
      </wodle>
```

The logs are coming in for cloud trail but no logs for guard duty.

**Comment by shrivastavshubham34** [comment]
The logs were not coming in from the kinesis firehose stream since they run at a given time. 
Logs now visible in kibana

**Comment by rukender** [comment]
Hi shrivastavshubham34,

All my config is same, still wazuh logs are not reading guarduty logs but showing cloudtrail logs.
Also, not seeing logs in kibana console, I have alert parsed from Firehose to S3 bucket.
