### ISSUE TITLE
agentlessd: INFO: Test passed for 'agentless_script'

### ISSUE THREAD

**Issue by dummypunter** [wazuh/wazuh#4225]
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
|3.9.3|agentless|Manager|Any|CentOS 7.6.1810|

When starting ossec, agentlessd checks the agentless scripts in the ossec.conf. When the ossec.conf contains many servers that are checked with the same script, the script is checked again for each server. When the servers are dozens, you have to wait an hour or more before the first scan begins.
 

```
ossec.conf:
<ossec_config>
  <agentless>
    <type>agentless_script</type>
    <frequency>86400</frequency>
    <host>ossec@host1</host>
    <state>periodic</state>
    <arguments>/foo /bar</arguments>

    <type>agentless_script</type>
    <frequency>86400</frequency>
    <host>ossec@host2</host>
    <state>periodic</state>
    <arguments>/foo /bar</arguments>

    ...

    <type>agentless_script</type>
    <frequency>86400</frequency>
    <host>ossec@host60</host>
    <state>periodic</state>
    <arguments>/foo /bar</arguments>
```

after ossec-control restart:
```
ossec.log:
2019/11/12 12:59:11 ossec-agentlessd: INFO: Test passed for 'agentless_script'.
2019/11/12 12:59:12 ossec-agentlessd: INFO: Test passed for 'agentless_script'.
...
2019/11/12 13:27:44 ossec-agentlessd: INFO: Test passed for 'agentless_script'.
```

**Comment by Zenidd** [comment]
Hello @dummypunter,

Thank you for reporting this problem and sending us the log messages.


- The further code block contains the agentless script test section. As you said above, no check is performed to avoid redundant tests:
https://github.com/wazuh/wazuh/blob/1c92d178c2e876a774ddd0acf2501e821c2fd688/src/agentlessd/agentlessd.c#L334-L365


- Just using two entries with the same script leads to the behavior you described above:
```XML
<agentless>
  <type>ssh_integrity_check_linux</type>
  <frequency>36000</frequency>
  <host>root@test.com</host>
  <state>periodic</state>
  <arguments>/bin /etc /sbin</arguments>
</agentless>

<agentless>
  <type>ssh_integrity_check_linux</type>
  <frequency>36000</frequency>
  <host>root@test2.com</host>
  <state>periodic</state>
  <arguments>/bin /etc /sbin</arguments>
</agentless>
```

```
2019/12/27 10:12:53 ossec-agentlessd: INFO: Test passed for 'ssh_integrity_check_linux'.
2019/12/27 10:12:54 ossec-agentlessd: INFO: Test passed for 'ssh_integrity_check_linux'.
```


As soon as our workflow allows us, we will fix it so the test for the agentless scripts is passed just once for each different script. Thanks again for your contribution.

Greetings, JP Sáez

**Comment by nicolaspapp** [comment]
Hello @dummypunter if you want to define multiple server for the same agentless script, this also could be a valid configuration:

```
ossec.conf:
<ossec_config>
  <agentless>
    <type>agentless_script</type>
    <frequency>86400</frequency>
    <host>ossec@host1</host>
    <host>ossec@host60</host>
    <host>ossec@host2</host>
    <state>periodic</state>
    <arguments>/foo /bar</arguments>
  </agentless>
```

That way you configure multiple servers for the same script. The command will be executed for all the hosts, but the check will only be executed one.

Do you think a configuration such as the one I presented could solve your problem?
Regards,
Nicolas

**Comment by dummypunter** [comment]
Many thanks!!! This configuration both solved my problem and yielded a cleaner ossec.conf!!!
