### ISSUE TITLE
Agents get disconnected after few hours

### ISSUE THREAD

**Issue by shrivastavshubham34** [wazuh/wazuh#4228]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.5-1 | clusterd | Manager | Packages | Ubuntu 16.04 |

I have raised this issue on 16th October and have been following it for one month now in the google groups: 
https://groups.google.com/forum/#!topic/wazuh/md0PGQIG1eA

I have performed all the steps suggested but still can't track down the issue.

The Gist:
After couple of hours, the kibana dashboard says agents are disconnected, even though clicking on discover a section in kibana, I can still see logs incoming from agents like how a user logged in, but the Wazuh API shows agents as disconnected.

**Comment by crd1985** [comment]
Closing because of the reason explained in the forum thread above.
