### ISSUE TITLE
SCA Regex: Ensure events that modify the system's network environment are collected

### ISSUE THREAD

**Issue by nimeops** [wazuh/wazuh#4235]
Hi,
seems that the regex is not good for **Ensure events that modify the system's network environment are collected** for debian

`- 'f:/etc/audit/audit.rules -> r:^-w && r:/etc/sysconfig/network && r:-p wa && r:-k system-locale'`

should be:
```
- 'f:/etc/audit/audit.rules -> r:^-w && r:/etc/networks && r:-p wa && r:-k system-locale'
- 'f:/etc/audit/audit.rules -> r:^-w && r:/etc/network && r:-p wa && r:-k system-locale'
```

File: https://github.com/wazuh/wazuh/blob/master/etc/sca/debian/cis_debian9_L2.yml

**Comment by cristgl** [comment]
Hello @nimeops and thanks again for reporting these bugs.

I fixed it in this PR https://github.com/wazuh/wazuh-ruleset/pull/527. However, I've seen that you have added another line with the file _/etc/networks_. Can you explain this? It is not reflected in the [CIS](https://downloads.cisecurity.org/?utm_campaign=Benchmarks&utm_medium=email&_hsenc=p2ANqtz-9ms9XRMho-H1dUberlJzBpcEOJIqJNqAQh_MQTY8pO14KkWMKaC5HClBn3x-FrIoUaoSSVmqhzSnEWXORx-u9FFJD3zA&_hsmi=35678746&utm_content=35678746&utm_source=hs_automation&hsCtaTracking=41ef8b02-d0e5-4acb-b542-67c919c7098e%7C500cec43-3dc4-4f4e-8680-465ba237fae1#/) Debian benchmark.

Kind regards,
Cristina

**Comment by nimeops** [comment]
Hi, 
on Debian/Ubuntu, there are ressources to check:

- file /etc/networks
- directory /etc/network
