### ISSUE TITLE
Problem with frequency and <same_field> options

### ISSUE THREAD

**Issue by goldarai** [wazuh/wazuh#4236]
| 3.10.2 | - | Manager | Packages | Ubuntu 18.04 |

Hi team,

We are trying to create a rule to detect brute force attacks against specific servers (regardless of whether they come from the same source IP or not), but our rule (107007) does not fire. However, another alert (107001) that has similar logic is triggered. Could you give us a hand?

>     <rule id="106002" level="9">
>         <if_sid>5710</if_sid>
>         <description>Invalid user login</description>
>     </rule>

>     <rule id="107007" level="10" frequency="7" timeframe="120" ignore="60">
>         <if_matched_sid>106002</if_matched_sid>
>         <description>sshd: brute force trying to get access to the system.</description>
>         <same_field>hostname</same_field>
>     </rule>

>     <rule id="107001" level="10" frequency="9" timeframe="120" ignore="60">
>         <if_matched_sid>106002</if_matched_sid>
>         <description>sshd: brute force trying to get access to the system.</description>
>         <same_source_ip/>
>     </rule>

Logtest
Nov 13 15:57:26 server-test-00 sshd[11497]: Invalid user test from 172.16.1.11 port 63138
Nov 13 15:57:27 server-test-00 sshd[11499]: Invalid user test from 172.16.1.11 port 63139
Nov 13 15:57:28 server-test-00 sshd[11501]: Invalid user test from 172.16.1.11 port 63140
Nov 13 15:57:29 server-test-00 sshd[11503]: Invalid user test from 172.16.1.11 port 63141
Nov 13 15:57:30 server-test-00 sshd[11505]: Invalid user test from 172.16.1.11 port 63142
Nov 13 15:57:32 server-test-00 sshd[11507]: Invalid user test from 172.16.1.11 port 63143
Nov 13 15:57:33 server-test-00 sshd[11509]: Invalid user test from 172.16.1.11 port 63144
< Rule 107007 should be triggered but that does not happen >
Nov 13 15:57:34 server-test-00 sshd[11511]: Invalid user test from 172.16.1.11 port 63145
Nov 13 15:57:35 server-test-00 sshd[11511]: Invalid user test from 172.16.1.11 port 63146
< Rule 107001 triggered >

Regards.

**Comment by cristgl** [comment]
Hello @goldarai,

I am sorry for the inconveniences, but using the `same_field` option with the values obtained in the pre-decoding of rules is not possible at the time. We have opened an issue where we explain the limitations of these options (same_field, not_same_field, field) https://github.com/wazuh/wazuh/issues/3440. You can follow its development and updates.

Thanks for your collaboration,
Cristina

Kind regards,
Cristina

**Comment by Zenidd** [comment]
Hello again @goldarai,

I'm closing this ticket due to inactivity. As my mate @cristgl said above, you can follow the fix development and updates in the related issue https://github.com/wazuh/wazuh/issues/3440. 

Thanks again for reporting this bug. Greetings, 
JP Sáez
