### ISSUE TITLE
SLES 12 SP3 install issue

### ISSUE THREAD

**Issue by neilashbysenior** [wazuh/wazuh#424]
Hi, I am trying to install wazuh-agent for SLES 12 and according to the compatibility matrix, the latest version is 3.1.0.
I have a custom repo set up and if I install from this using zypper the error is:

Additional rpm output:
wazuh-agent: unknown service
wazuh-agent: unknown service

and the service is not created but the OS does report the package as installed.

If I use rpm to install with verbose output, it gives the information provided in the attached file.
I have tried on multiple machines and with multiple wazuh agent versions and get the same behaviour. 
Can anyone shed any light on this please, is it something related to wazuh or something I am doing wrong? No issues on non Suse machines.
Thanks,
Neil.
[wazuh-sles-error.txt](https://github.com/wazuh/wazuh/files/1780273/wazuh-sles-error.txt)

**Comment by BraulioV** [comment]
Hi @neilashbysenior,

there is a problem with our compatibility matrix in Wazuh docs, we are updating it. The binaries in the rpm package are fully compatible with SLES 12 and SLES 11, but there's a problem with the wazuh-agent.init file which is not compatible with SLES. This is solved in Wazuh 3.2.1, so you can use the latest version of Wazuh with the latests RPM packages.

Sorry for the inconveniences and thank you for the feedback.

Regards,  
Braulio.

**Comment by neilashbysenior** [comment]
Hi Braulio, thanks for the quick and helpful response. I think the version of 3.2.1 has worked. Cheers.

**Comment by BraulioV** [comment]
Glad to help 😄
