### ISSUE TITLE
AWS Rule "80200" generates unsupported field "eventTime"

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh#4257]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-rev31014 | Wazuh Manager | Manager | Packages | Centos 7 |

Hi team,

The AWS wodle generates the following error when activating the rule "80200" :

![image](https://user-images.githubusercontent.com/46649922/69228487-f3600900-0b83-11ea-832d-f5f68e3b0dfa.png)

### Steps to reproduce

*Please note some sensitive data will be replaced with `xxx`*

- On the Wazuh Master, enable the AWS Wodle. The configuration I'm using is the following:

```
  <wodle name="aws-s3">
    <disabled>no</disabled>
    <remove_from_bucket>no</remove_from_bucket>
    <interval>30m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>no</skip_on_error>
    <bucket type="cloudtrail">
      <name>xxx</name>
      <access_key>xxx</access_key>
      <secret_key>xxx</secret_key>
      <only_logs_after>2019-MAR-24</only_logs_after>
    </bucket>
    <bucket type="guardduty">
      <name>xxx</name>
      <path>guardduty</path>
      <access_key>xxx</access_key>
      <secret_key>xxx</secret_key>
      <only_logs_after>2019-MAR-24</only_logs_after>
    </bucket>
    <bucket type="custom">
      <name>xxx</name>
      <path>macie</path>
      <access_key>xxx</access_key>
      <secret_key>xxx</secret_key>
      <only_logs_after>2019-MAR-24</only_logs_after>
    </bucket>
    <bucket type="vpcflow">
      <name>xxx</name>
      <path>vpc</path>
      <access_key>xxx</access_key>
      <secret_key>xxx</secret_key>
      <only_logs_after>2019-MAR-24</only_logs_after>
    </bucket>
    <service type="inspector">
      <access_key>xxx</access_key>
      <secret_key>xxx</secret_key>
    </service>
  </wodle>
```
- Enable the rule `80200` in `/var/ossec/ruleset/rules/0350-amazon_rules.xml`
```
    <rule id="80200" level="3">
        <decoded_as>json</decoded_as>
        <field name="integration">aws</field>
        <description>AWS alert.</description>
        <options>no_full_log</options>
    </rule>
```
- Restart Wazuh Manager

- It will generate alerts like the following:

```
{"timestamp":"2019-11-20T09:47:17.468+0000","rule":{"level":3,"description":"AWS alert.","id":"80200","firedtimes":5733,"mail":false,"groups":["amazon","aws"]},"agent":{"id":"000","name":"master"},"manager":{"name":"master"},"id":"xxx","cluster":{"name":"wazuh","node":"node01"},"decoder":{"name":"json"},"data":{"integration":"aws","aws":{"log_info":{"log_file":"AWSLogsxxx","s3bucket":"xxx"},"eventVersion":"1.05","userIdentity":{"type":"IAMUser","principalId":"xxx","arn":"arn:aws:iam::xxx","accessKeyId":"xxx","userName":"xxxz"},"eventTime":"2019-06-22T06:50:40Z","eventSource":"inspector.amazonaws.com","eventName":"ListFindings","awsRegion":"xxx","userAgent":"Boto3/1.9.82 Python/3.7.2 Linux/4.14.114-105.126.amzn2.x86_64 Botocore/1.12.128","requestParameters":{"maxResults":"100","nextToken":"{\"v\":\"1\",\"scatter\":\"10\"}","filter":{"creationTimeRange":{"endDate":"Jun 22, 2019 6:50:38 AM","beginDate":"Jun 22, 2019 6:20:39 AM"}}},"requestID":"xxx","eventID":"xxx","eventType":"AwsApiCall","apiVersion":"v20160216","recipientAccountId":"xxx","source":"cloudtrail","aws_account_id":"xxx","source_ip_address":"xxx"}},"location":"xxx"}

```

- If you navigate to Kibana, you will find the error linked at the beginning of the issue 

Best regards,

Jose

**Comment by davidjiglesias** [comment]
I have checked the actual [Elastic template](https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/7.x/wazuh-template.json) being used and the field `data.aws.eventTime` is not defined. 

I have been able to reproduce the error above and solved it by adding the appropriate `data.aws.eventTime` mapping (type: date) to wazuh-template.json.

![image](https://user-images.githubusercontent.com/48716145/70548260-8a602580-1b72-11ea-9153-4b2bc56c2f6d.png)


We can see the field being displayed now:

![image](https://user-images.githubusercontent.com/48716145/70547943-1291fb00-1b72-11ea-9763-4702eec68587.png)

We should add `data.aws.eventTime` as `type: date` permanently to `wazuh-template` @juankaromo

**Comment by juankaromo** [comment]
We'll take it into account. ping @wazuh/frontend @pablotr9

**Comment by davidjiglesias** [comment]
This field and several others will be added in https://github.com/wazuh/wazuh-kibana-app/issues/1951.
