### ISSUE TITLE
Agent auth bug with "any" as source IP.

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh#4265]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.Z | Authd | Manager | Packages | CentOS 7 |

Hello team,

I've seen the following behavior while testing the agent_auth tool with "any" as the agent 

**Use case:**

Registering two agents with "any" as source IP.

**Expected behavior:**

Executing the following command should register an agent with "any" as its IP address:
```
/var/ossec/bin/agent-auth -m MANAGERIP -A agentname -I any
```
And it then, registering another agent with a different name:
```
/var/ossec/bin/agent-auth -m MANAGERIP -A agentname2 -I any
``` 
Should give us two agents registered in the manager:
```
[root@centOS7-2 ~]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centOS7-2 (server), IP: 127.0.0.1, Active/Local
   ID: 021, Name: agentname, IP: any, Never connected
   ID: 022, Name: agentname2, IP: any, Never connected
```

**Behavior found:**

When I register the second agent the manager thinks it is the same one and it updates the previous information, it makes the manager lose the information from the first agent. The final result is:
```
[root@centOS7-2 ~]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: centOS7-2 (server), IP: 127.0.0.1, Active/Local
   ID: 024, Name: agent2, IP: any, Never connected
```

I've noticed It works when the option <use_source_ip> is changed to `no` in the Wazuh manager `ossec.conf` file.

**Comment by DaveVG1** [comment]
This issue is duplicated https://github.com/wazuh/wazuh/issues/2497
The related PR (https://github.com/wazuh/wazuh/pull/2533) should fix this issue (is currently pending to be reviewed).
Please check if it's in fact duplicated and close this issue in that case.

**Comment by DanielMorLoz** [comment]
> This issue is duplicated #2497 

I'll close this issue then, thank for the feedback.
