### ISSUE TITLE
Make JWT tokens be revocable

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4266]
## Description
Current RBAC implementation is fully based on JWT to allow clients log in the API and simultaneously give permissions through the encoded token. By default, the token expires in a prefixed date. However, if changes are made in permissions the token will be still valid until it expires due to a date, leading to some inconsistencies among users.

## Requirements
The solution must fit the following requirements:
- JWT tokens should be still self contained. This requirement allows keeping things simple. This way the API does not need to store issued tokens and to do inefficient maintenance tasks to clean a database.
- Every time an administrator changes any permissions for a role, all affected JWT tokens must be invalid inmediately. This will force any user with a outdated token to login again and request a new one.

## Design
There are two possible alternatives:
- Change the private key that the API uses to sign the encoded JWT token, so any outdated token becomes disavowed. This is quite aggressive since all users are forced to request a new authentication token, however, it is very easy to implement and very efficient computationally.
-  Calculate the SHA256 hash of the JSON resulting from the permissions involved. The hash may be included in the token and compared against the same hash previously stored in the server. If both hash values do not match the token is rejected and another one should be requested. This approach may save some extra logins although it is a bit more complex to implement and a bit less efficient. It also increases the length of the JWT token.

**Comment by crd1985** [comment]
After studying the question, I have come up with another alternative.
We could store the timestamp of the last role modification and include it in the JWT. This new field could be used to validate the JWT so if the timestamp is not equal to that in the server the token is rejected.

We should assess how hard is having a timestamp for each role. If the implementation cost is too high we could implement a faster solution with only one timestamp. If the timestamp does not match, all JWT are revoked.

**Comment by davidjiglesias** [comment]
In order to implement the mentioned alternative https://github.com/wazuh/wazuh/issues/4266#issuecomment-560373661, we have added a new security endpoint `PUT /security/user/revoke` to allow the users with enough permissions to revoke access to all active JWT tokens.

**Comment by davidjiglesias** [comment]
I have also added test integration points for the new endpoint as well as RBAC white and black test stages. Test results:

**Comment by davidjiglesias** [comment]
### **API added security endpoint RBAC catalog:**
| Http Method | API endpoint  | Actions | Resources |
| ------------- | ------------- | ------------- | ------------ |
| PUT | /security/user/revoke | security:revoke | * |
