### ISSUE TITLE
Event-location email alerts by subnet

### ISSUE THREAD

**Issue by dmitrijn** [wazuh/wazuh#427]
Hello, 

How to send multiple email alerts for specific big subnet like /16 /12 bits
Example in documentation only shows /24 bit

`````
  <email_alerts>
      <email_to>bob@test.com</email_to>
      <event_location>192.168.</event_location>
  </email_alerts>
  `````

https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/email_alerts.html#event-location

If i have more than 1 subnet like 10.1.0.0/16, 10.24.0.0/16, 10.240.0.0/12 - how can i send to different email address for event-location by subnet?  
I tried to configure email_alerts rule, but it's not working all email was sent to default email alert rule. Is it possible to make such configuration and remove default email? 
`````
  <email_alerts>
      <email_to>bob@bob.com</email_to>
      <event_location>10.1.0.0/16</event_location>
  </email_alerts>

  <email_alerts>
      <email_to>john@john.com</email_to>
      <event_location>10.24.0.0/16</event_location>
  </email_alerts>

  <email_alerts>
      <email_to>deborah@deborah.com</email_to>
      <event_location>10.240.0.0/12</event_location>
  </email_alerts>
`````

**Comment by bah07** [comment]
Hi dmitrijn, 

At the moment it's not possible configure a subnet from which to report alerts to send them by email. Thank you for considering this possibility, we will study in the future how to implement this feature.

However, there is a possibility of doing what you propose. When registering an agent we can specify from which IP address it will be connected, instead we can indicate the subnet to which it belongs. On the other hand, this field is the one that uses `<event_location>` to identify who generated the alert, so if the agents are registered in this way we can configure in `<email_alerts>` different email addresses for the subnets that you want to monitor.

For example:
Registering with manage_agent the following agents
```
   ID: 005, Name: ag-test1, IP: 10.240.0.0/12
   ID: 006, Name: ag-test2, IP: 10.24.0.0/24
   ID: 007, Name: ag-test3, IP: 10.1.0.0/16
```

We can add the next email alerts
```
  <email_alerts>
      <email_to>bob@bob.com</email_to>
      <event_location>10.1.0.0/16</event_location>
      <do_not_group/>
  </email_alerts>

  <email_alerts>
      <email_to>john@john.com</email_to>
      <event_location>10.24.0.0/16</event_location>
      <do_not_group/>
  </email_alerts>

  <email_alerts>
      <email_to>deborah@deborah.com</email_to>
      <event_location>10.240.0.0/12</event_location>
      <do_not_group/>
  </email_alerts>
```
`
<do_not_group/>`: To not group alerts of the same type in the same email.

I hope it helps you.
Best regards.

**Comment by bah07** [comment]
Hello @dmitrijn,

It's been more than a month since the last response, so I'll proceed to close it.

Thanks for reporting
Best regards
