### ISSUE TITLE
Receiving large amounts of data on syslog over TCP causes wrong output for analysis.

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#4272]
|Wazuh version|Component|Install type|
|---|---|---|
| 3.12 | remoted | Manager |

When receiving a large amount of logs on a TCP syslog connection the remoted component send an incorrect output for analysis. There are basically two different conditions/errors.
- When several log messages are received on the same TCP packet, only the first log message is correctly parsed and passed down for analysis.
- When several log messages are received in 2 or more TCP packets, only the first log message is correctly parsed and passed down for analysis and, upon receiving the second message, the remainder of the log messages from the first packet are logged with the first log of the second packet. The remainder of the log messages from the second packet are discarded.

Both of this errors are because the logic on the HandleClient function assumes that the received TCP packet is either a full log message, part of the message with the rest of it coming in following messages or a full log message and a part of a second message. If the received TCP packet holds two full log messages, two full messages and the beginning of a third, three messages and the beginning of a fourth, etc., the message passed down for analysis will be wrong.

To proof this, I wrote a simple python program that sends the message `<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n` 800 times on the syslog port of a manager and the archives log showed the following:

```
{"timestamp":"2019-11-22T22:55:13.999+0100","rule":{"level":4,"description":"User logged","id":"100010","firedtimes":13,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"manager"},"manager":{"name":"manager"},"id":"1574459713.2405631","full_log":"Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'","predecoder":{"program_name":"example","timestamp":"Dec 25 20:45:02","hostname":"MyHost"},"decoder":{"name":"example"},"data":{"srcip":"192.168.1.100","dstuser":"admin"},"location":"192.168.50.10"}
{"timestamp":"2019-11-22T22:57:09.200+0100","rule":{"level":4,"description":"User logged","id":"100010","firedtimes":14,"mail":false,"groups":["local","syslog","sshd"]},"agent":{"id":"000","name":"manager"},"manager":{"name":"manager"},"id":"1574459829.2414018","full_log":"Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin' logged from '192.168.1.100'\n<1000>Dec 25 20:45:02 MyHost example[12345]: User 'admin...
```
The easiest solution I can see to this problem is to check whether the received TCP packet contains anymore full log messages before the cleanup part of the following code and send all of them in separate messages, maybe wrapping around the logic for parsing syslog messages until the buffer length is 0 or no other line feeds are found.
https://github.com/wazuh/wazuh/blob/5b02b003d0b57f2b262e1bd0ca32524eaee30e39/src/remoted/syslogtcp.c#L99-L137

**Comment by RamiusKahn** [comment]
Hello, we are seeing this on a feed in our production environment. Is there an ETA on a patch / fix?

**Comment by vikman90** [comment]
@RamiusKahn apologies for not having attended this issue before. I'm moving that to this sprint to fix it ASAP. 

I hope to have a fix implemented for next week. Unfortunately, I cannot estimate a deadline for a GA patch at this moment.

We will keep you posted. Thank you for your patience.

Best regards.
