### ISSUE TITLE
Eventchannel not overwritting existing configuration based on order

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#4276]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3-1 | Centralized configuration/Eventchannel | Agent | Packages | Windows Server 2016 |

Hi team,

I found an issue with Centralized configuration, not overwriting local Eventchannel config based on the order. I've noticed it because of the following case:

When using this configuration inside agent.conf, the Security query wasn't showing properly in the Wazuh API.

```xml
<agent_config>

  <!-- Log analysis -->
  <localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 10016 and EventID != 1008]</query>
  </localfile>

</agent_config>
```
![imagen](https://user-images.githubusercontent.com/37381070/69559226-d4111380-0fa9-11ea-81e7-b7a093ba38bc.png)

But when changing the order of the options:
```xml
<agent_config>

  <!-- Log analysis -->
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 10016 and EventID != 1008]</query>
  </localfile>

  <localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
  </localfile>

</agent_config>
```
![imagen](https://user-images.githubusercontent.com/37381070/69559405-2e11d900-0faa-11ea-9e14-4c515160f8a0.png)

It is not a synchronization error, as I also tested changing from config 2 to config 1 and the Query goes back to its default.
It is neither a visual error. I tested it and the agent does not apply the query as the API shows.

Best regards,
Miguel

**Comment by migruiz4** [comment]
I haven't been able to reproduce this same behavior in version 3.10.2.

The configuration works properly independently of the order.

**Comment by wazuhci** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.4.4                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.4.4-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4077/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/monitor-manager-Test_stress_B4077_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/plots/Test_stress_B4077_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4077_manager_2023-07-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/logs/ossec_Test_stress_B4077_manager_2023-07-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4077_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/data/monitor-manager-Test_stress_B4077_manager-pre-release.csv)
[Test_stress_B4077_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/data/Test_stress_B4077_manager_analysisd_events.csv)
[Test_stress_B4077_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/data/Test_stress_B4077_manager_analysisd_state.csv)
[Test_stress_B4077_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_manager_centos/data/Test_stress_B4077_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/monitor-agent-Test_stress_B4077_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/Test_stress_B4077_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/Test_stress_B4077_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/Test_stress_B4077_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/plots/Test_stress_B4077_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4077_centos_2023-07-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/logs/ossec_Test_stress_B4077_centos_2023-07-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4077_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/data/monitor-agent-Test_stress_B4077_centos-pre-release.csv)
[Test_stress_B4077_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_centos/data/Test_stress_B4077_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/plots/monitor-agent-Test_stress_B4077_ubuntu-pre-release_Write_Ops.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4077_ubuntu_2023-07-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/logs/ossec_Test_stress_B4077_ubuntu_2023-07-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4077_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_ubuntu/data/monitor-agent-Test_stress_B4077_ubuntu-pre-release.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/monitor-winagent-Test_stress_B4077_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/Test_stress_B4077_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/Test_stress_B4077_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/Test_stress_B4077_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/plots/Test_stress_B4077_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4077_windows_2023-07-05.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/logs/ossec_Test_stress_B4077_windows_2023-07-05.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4077_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/data/monitor-winagent-Test_stress_B4077_windows-pre-release.csv)
[Test_stress_B4077_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.4.4/B4077-480m/B4077_agent_windows/data/Test_stress_B4077_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>
