### ISSUE TITLE
how to use wazuh to collect custom json format log?

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#4292]
Hello,I want to use wazuh to collect log file without alert
My host will create openapi.log,the content like this:
```
{"timestamp":"2018-09-11T15:51:21.343","level":"INFO","ip_addr":"192.168.25.67","username":"cheno-test","http_method":"POST","detail":"test1","result":"Success","url":"http://192.168.5.191/gezhen-management-platform/company/edit","http_code":200}
{"timestamp":"2018-09-12T15:51:21.343","level":"INFO","ip_addr":"192.168.25.67","username":"cheno-test","http_method":"POST","detail":"test2","result":"Success","url":"http://192.168.5.191/gezhen-management-platform/company/edit","http_code":200}
{"timestamp":"2018-09-13T15:51:21.343","level":"INFO","ip_addr":"192.168.25.67","username":"cheno-test","http_method":"POST","detail":"test3","result":"Success","url":"http://192.168.5.191/gezhen-management-platform/company/edit","http_code":200}
```

I want to use <localfile> tag to collect this log file,but I don't want set alert rule to collect it.
If I use <logall> or <logall_json> tag, it will collect all localfile, I just want to collect my custom log file,So how can I do it?

**Comment by xufengnian** [comment]
I want to use wazuh agent collect my custom log to manager host's archives.json or collect the log to manager host with json format

**Comment by sergiospa** [comment]
Hi @xufengnian ,
We can make use of the `logcollector` module to read those JSON logs and let `archives.json` write them without triggering any alert. Please follow these steps:
- To enable `archives.json` logging, open your manager's `ossec.conf` and change the option `<logall_json>` from `no` to `yes`. Then, restart your manager to apply changes: `systemctl restart wazuh-manager` or `service wazuh-manager restart`.
- If the file `openapi.log` is in the Wazuh manager, write this `localfile` block in the manager's `/var/ossec/etc/ossec.conf`:
```xml
<localfile>
  <log_format>json</log_format>
  <location>/test/test_localfile</location>
 </localfile>
```

- If  `openapi.log` is in a Wazuh agent, you have the possibility to write the `localfile` configuration locally in the agent's `ossec.conf` or to send the configuration remotely from the Wazuh manager. To send the configuration remotely, your agent should belong to any group. By default, every agent belong to the `default` group. You can also make your agents belong to multiple groups. This command will let you know which groups your agent belongs to:
`/var/ossec/bin/agent_groups -s -i 000`

Once you know the group you are going to use (let's say you decided to use the `default` group), please write the following lines in the manager's `/var/ossec/etc/shared/default/agent.conf`:
```xml
<agent_config>
 <localfile>
   <log_format>json</log_format>
   <location>/test/test_localfile</location>
  </localfile>
</agent_config>
```
For Windows agents, you can find that file in `C:\Program Files (x86)\ossec-agent\shared\agent.conf`.

After sending the remote configuration, the agent may take a while to fetch it. You can accelerate the process by restarting the manager.

Let me know if this works for you.

Regards,
Sergio.

**Comment by xufengnian** [comment]
Thank you!But I want to only collect `openapi.log`,if I use <logall_json>,it will collect a lot of whole log file such as `/var/log/secure`、`/var/log/httpd/access_log`...
To solve this question ,I create a custom rule in /var/ossec/etc/rules/local_rules.xml

```
<group name="openapi,">

  <rule id="100002" level="1">
   <decoded_as>json</decoded_as>
   <field name="timestamp">\.+</field>
   <field name="level">\.+</field>
   <description>openapi:Security log</description>
  </rule>
```
so I can receive this log file in alerts.json,if I want to monitor my openapi's security,I can create another rules,in this way,I can receive openapi's log without collect other whole log files

But thanks a lot ,your reply is very useful,too.So I also suggest wazuh can modify `logcollector` module to collect user custom log file in manager another log file not just use <logall> or <logall_json>

**Comment by sergiospa** [comment]
Hi @xufengnian ,
Happy to help! 
I am not sure if your solution will fulfill your request. By default, the minimum level a rule needs to have in order to generate an alert is **3**. You can change this value by modifying `<log_alert_level>` in the manager's `ossec.conf`:
```xml
<alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>
```
If you didn't modify the default value, that rule will not generate an alert (as you wanted) but the event will be discarded by the manager if `<logall_json>` is disabled. Generating an alert or enabling `logall` are the only ways to store an event in the manager.

Let me know if you have any questions, or if you think that the provided information is wrong.
Best regards,
Sergio.

**Comment by xufengnian** [comment]
yes,I had changed the manager's ossec.conf
As you can see,I create the custom rule to make alert with level 1,so I change ossec.conf `<log_alert_level>` value is "1",I had lookup up wazuh default rules, there is a few rule with "level 1",so I just use it. This is the result of my kibana discover page ,it is work.Thank you very much!

![image](https://user-images.githubusercontent.com/15324125/70107231-dbf34680-1680-11ea-8567-ac042e3e72eb.png)

**Comment by DeGrootePasja** [comment]
What other rules do you have in order to make this work? @xufengnian

**Comment by nguyenthanhvu240** [comment]
Hi guys,i had a json file with more than 60000 lines.I use Splunk to read this file,but splunk can read limit with 5000 lines.How about wazuh agent,i can not find document about this stuff
