### ISSUE TITLE
Rewrite unit tests for agents module (core)

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4296]
## Description
Unit tests must be adapted to new RBAC and API implementation.

## Tasks
- [x] wazuh/core/tests/test_agent.py

**Comment by Selutario** [comment]
Hello team,

I found what looks like an incorrect query within the `_filter_status` method of the `WazuhDBQueryAgents` class in the `core_agent.py` module, on the following line:

https://github.com/wazuh/wazuh/blob/cc223fb3845d7838f4e1e47fc4811c85eea46e75/framework/wazuh/core/core_agent.py#L54

When the method is called with these parameters:
```Python
query_agent = WazuhDBQueryAgents()
query_agent._filter_status({'value': value, 'operator': '=='})
```
Returns a query like the following:

`SELECT {0} FROM agentNOT (last_keepalive >= :time_active AND version IS NOT NULL) or id = 0`

The NOT tag is attached to the 'agent' table, which prevents it from being found correctly. Looks like it needs a space after the first quote.

Kind regards,
Jose Luis.
