### ISSUE TITLE
Limit number of files that FIM can monitor

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4319]
|Related issue|
|---|
|#3319|

File Integrity Monitoring analyzes and reports changes in the host's file system (new, modified and deleted files). In addition, as of issue #3319 it will syncronize that state with the manager's database.

The state is currently stored on RAM, meaning that the process occupies in memory grows with the amount of files monitored, and with the number of collected attributes.

It is essential to limit the memory used by the agent, so we should limit the number of files monitored by FIM.

## Proposed configuration

```xml
<syscheck>
  <max_files>100000</max_files>
</syscheck>
```

|Option|Range|Default|Description|
|---|---|---|---|
|**max_files**|1000 .. 10000000|100000|Limit of files monitored by the agent.

**Comment by bah07** [comment]
Duplicated: [#4687](https://github.com/wazuh/wazuh/issues/4687)
