### ISSUE TITLE
Wazuh logs to LogRhythm 

### ISSUE THREAD

**Issue by LRUz** [wazuh/wazuh#4327]
Hi Wazuh Team,

We are using wazuh on splunk and would like to forward the wazuh alerts.log to LogRhythm in a readable format.
Let us know how this can be done technically

**Comment by Zenidd** [comment]
Hello @LRUz,

On the LogRhythm website, I found that it has [Syslog collection capabilities](https://logrhythm.com/products/features/collection-technology/). Wazuh alerts can be sent through Syslog protocol to a given IP. Basically all you have to do is to configure a [<syslog_output>](https://documentation.wazuh.com/3.10/user-manual/manager/manual-syslog-output.html#configuring-syslog-output) configuration block on your Wazuh manager:

You can use different filters on the logs to send:
```XML
<syslog_output>
    <level>6</level>
    <server>YOUR_SYSLOG_IP_ON_LOGRHYTHM_SIDE</server>
</syslog_output>

<!-- Remember restarting the Wazuh manager after these changes -->
```

Please, let me know if this solution fits your use case. We can explore other options if needed. Greetings,  JP Sáez

**Comment by LRUz** [comment]
Hi @Zenidd,
We are using Syslog for the collection. Since the logs have already been ingested by Wazuh before being routed to LogRhythm, it seems LogRhythm has issue to parse the alerts.json received from wazuh. Any advice of this?

**Comment by Zenidd** [comment]
Hello @LRUz,

First of all, sorry for the late reply, I was AFK for some days.

I'm not sure of getting you at all so let me clarify it a bit. Wazuh ingests events and If an event trips a rule it generates an alert. Then, do you want to send to LogRhythm the alerts produced by Wazuh or the events prior to the Wazuh ingestion?

- If you need to send to LogRhythm the alerts produced by Wazuh you should use the [<syslog_output>](https://documentation.wazuh.com/3.10/user-manual/manager/manual-syslog-output.html#configuring-syslog-output) option or set directly read from the `alerts.(json|log)`. In my previous message I forgot to mention that you can change the format for <syslog_output> using the <[format>](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/syslog-output.html#format) option. Maybe one of these formats suits your use case. i.e:
```XML
<syslog_output>
    <level>3</level>
    <server>SERVER_IP</server>
    <format>default</format>
</syslog_output>

```
Also, could you detail the LogRhythm requirements for the logs to be correctly parsed or the error produced with the current configuration? 

On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

I hope we can get this thing up and running soon. Greetings, 
JP Sáez

**Comment by Zenidd** [comment]
Hello again @LRUz,

I'm closing the ticket due to inactivity. Do not hesitate to contact us again if you need anything else and for future questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez
