### ISSUE TITLE
No alarms with new decoder

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [wazuh/wazuh#4329]
|Wazuh version|Component|Install type|Install method|Platform|
|9.9.2                |Decoder      |Manager   |   repository   |Debian10|

Hi, i have created a new decoder:

`<decoder name="windows-EvtLog-4663">
  <prematch>\.+(\d+.\d+.\d+.\d+)->EventChannel\.+"eventID":"4663"\.+</prematch>
</decoder>
<decoder name="EvtLog-4663">
  <parent>windows-EvtLog-4663</parent>
  <regex>\.+(\d+.\d+.\d+.\d+)->EventChannel {"win":{"system":{"providerName":"(\.+)","providerGuid":"(\.+)","eventID":"(\.+)","version":"(\.+)","level":"(\.+)","task":"(\.+)","opcode":"(\.+)","keywords":"(\.+)","systemTime":"(\.+)","eventRecordID":"(\.+)","processID":"(\.+)","threadID":"(\.+)","channel":"(\.+)","computer":"(\.+)","severityValue":"(\.+)","message":"(\.+\p)"},"eventdata":{"subjectUserSid":"(\.+)","subjectUserName":"(\.+)","subjectDomainName":"(\.+)","subjectLogonId":"(\.+)","objectServer":"(\.+)","objectType":"(\.+)","objectName":"(\.+)","handleId":"(\.+)","accessList":"(\.+)","accessMask":"(\.+)","processId":"(\.+)","processName":"(\.+)","resourceAttributes":"(\.+)"}}}</regex>
  <order>src.ip,win.system.providerName,win.system.providerGuid,win.system.eventID,win.system.version,win.system.level,win.system.task,win.system.opcode,win.system.keywords,win.system.systemTime,win.system.eventRecordID,win.system.processID,win.system.threadID,win.system.channel,win.system.computer,win.system.severityValue,win.system.message,win.system.subjectUserSid,win.system.subjectUserName,win.system.subjectDomainName,win.system.subjectLogonId,win.system.objectServer,win.system.objectType,win.system.objectName,win.system.handleId,win.system.accessList,win.system.accessMask,win.system.processId,win.system.processName,win.system.resourceAttributes</order>
</decoder>`

And the alarms that i want to be triggered:

`</group>
<group name="integrity, dlp,">
 <rule id="100100" level="3">
   <decoded_as>windows-EvtLog-4663</decoded_as>
   <field name="win.system.eventID">4663</field>
   <description>Windows User attempted to access an object</description>
 </rule>
 <rule id="100101" level="5">
   <if_sid>100100</if_sid>
   <field name="win.system.accessList">%%4416</field>
   <description>Windows User attempted to access an object - Read Data</description>
 </rule>
 <rule id="100102" level="5">
   <if_sid>100100</if_sid>
   <field name="win.system.accessList">%%4417</field>
   <description>Windows User attempted to access an object - Write Data</description>
 </rule>
 <rule id="100103" level="5">
   <if_sid>100100</if_sid>
   <field name="win.system.accessList">%%4418</field>
   <description>Windows User attempted to access an object - Append Data</description>
 </rule>
</group>`

i have tested the decoder and alarms in `ossec-logtest` with an event that i get from archives.log and the result looks fine:

`**Phase 1: Completed pre-decoding.
       full event: '2019 Dec 03 15:38:06 (Windows2012) 192.168.6.59->EventChannel {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4663","version":"1","level":"0","task":"12812","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-03T14:38:05.128446200Z","eventRecordID":"1664492","processID":"480","threadID":"488","channel":"Security","computer":"WIN-AIEOJTT8UG6","severityValue":"AUDIT_SUCCESS","message":"Se intentó tener acceso a un objeto."},"eventdata":{"subjectUserSid":"S-1-5-21-2800651688-3019912576-308981525-500","subjectUserName":"Administrador","subjectDomainName":"WIN-AIEOJTT8UG6","subjectLogonId":"0x243b7e","objectServer":"Security","objectType":"File","objectName":"C:\\Users\\Administrador\\Desktop\\carpeta_test\\Nuevo documento de texto.txt","handleId":"0xfa0","accessList":"%%4416","accessMask":"0x1","processId":"0x478","processName":"C:\\Windows\\explorer.exe","resourceAttributes":"S:AI"}}}'
       timestamp: '2019 Dec 03 15:38:06'
       hostname: '(Windows2012)'
       program_name: '(null)'
       log: '192.168.6.59->EventChannel {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4663","version":"1","level":"0","task":"12812","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-03T14:38:05.128446200Z","eventRecordID":"1664492","processID":"480","threadID":"488","channel":"Security","computer":"WIN-AIEOJTT8UG6","severityValue":"AUDIT_SUCCESS","message":"Se intentó tener acceso a un objeto."},"eventdata":{"subjectUserSid":"S-1-5-21-2800651688-3019912576-308981525-500","subjectUserName":"Administrador","subjectDomainName":"WIN-AIEOJTT8UG6","subjectLogonId":"0x243b7e","objectServer":"Security","objectType":"File","objectName":"C:\\Users\\Administrador\\Desktop\\carpeta_test\\Nuevo documento de texto.txt","handleId":"0xfa0","accessList":"%%4416","accessMask":"0x1","processId":"0x478","processName":"C:\\Windows\\explorer.exe","resourceAttributes":"S:AI"}}}'

**Phase 2: Completed decoding.
       decoder: 'windows-EvtLog-4663'
       src.ip: '92.168.6.59'
       win.system.providerName: 'Microsoft-Windows-Security-Auditing'
       win.system.providerGuid: '{54849625-5478-4994-A5BA-3E3B0328C30D}'
       win.system.eventID: '4663'
       win.system.version: '1'
       win.system.level: '0'
       win.system.task: '12812'
       win.system.opcode: '0'
       win.system.keywords: '0x8020000000000000'
       win.system.systemTime: '2019-12-03T14:38:05.128446200Z'
       win.system.eventRecordID: '1664492'
       win.system.processID: '480'
       win.system.threadID: '488'
       win.system.channel: 'Security'
       win.system.computer: 'WIN-AIEOJTT8UG6'
       win.system.severityValue: 'AUDIT_SUCCESS'
       win.system.message: 'Se intentó tener acceso a un objeto.'
       win.system.subjectUserSid: 'S-1-5-21-2800651688-3019912576-308981525-500'
       win.system.subjectUserName: 'Administrador'
       win.system.subjectDomainName: 'WIN-AIEOJTT8UG6'
       win.system.subjectLogonId: '0x243b7e'
       win.system.objectServer: 'Security'
       win.system.objectType: 'File'
       win.system.objectName: 'C:\\Users\\Administrador\\Desktop\\carpeta_test\\Nuevo documento de texto.txt'
       win.system.handleId: '0xfa0'
       win.system.accessList: '%%4416'
       win.system.accessMask: '0x1'
       win.system.processId: '0x478'
       win.system.processName: 'C:\\Windows\\explorer.exe'
       win.system.resourceAttributes: 'S:AI'

**Phase 3: Completed filtering (rules).
       Rule id: '100101'
       Level: '5'
       Description: 'Windows User attempted to access an object - Read Data'
**Alert to be generated.`

But i trigger events in my lab and no alerts are generated
, i have checked that events that will trigger the alarms (suppousedly) appears in archieve.log but i have no alerts in alerts.log.

**Comment by Zenidd** [comment]
Hello @BernaldoPenasAntelo, 

I must admit that your decoder has a great job behind it, however, this job is already done by the Eventchannel internal decoder and _you should write rules over the existing Eventchannel ones_.

### Testing Eventchannel events in ossec-logtest
You can rely on the `ossec-logtest` binary to test your Windows Eventchannel events and see If they trigger rules. There is one peculiarity about using Eventchannel events on the ´ossec-logtest` binary:

- Before using `Eventchannel` events in `ossec-logtest` you should go to the `0575-win-base_rules.xml` ruleset file and modify the base rule as in the example below. Without this modification, the Eventchannel events are not correctly recognized by the `ossec-logtest`.:

```XML
# Accesing the file
# nano /var/ossec/ruleset/rules/0575-win-base_rules.xml

<!-- You should modify the original version for the 60000 id rule -->
  <rule id="60000" level="0">
    <category>ossec</category>
    <decoded_as>windows_eventchannel</decoded_as>
    <field name="win.system.providerName">\.+</field>
    <options>no_full_log</options>
    <description>Group of windows rules</description>
  </rule>

<!--  With this version that allows ossec-logtest processing the Eventchannel events -->
  <rule id="60000" level="0">
<!-- <category>ossec</category> -->
    <decoded_as>json</decoded_as>
    <field name="win.system.providerName">\.+</field>
    <options>no_full_log</options>
    <description>Group of windows rules</description>
  </rule>

<!-- once you finish testing your events you should return the rule to its original options -->
```


- Here you have an example event I generated this morning. You should use it to check if Eventchannel events work on your `ossec-logtest` binary. Please, check that you get the same output.
```
{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4689","version":"0","level":"0","task":"13313","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-04T12:45:38.962884600Z","eventRecordID":"47823","processID":"4","threadID":"284","channel":"Security","computer":"DESKTOP-D33AN6I","severityValue":"AUDIT_SUCCESS","message":"Se salió de un proceso."},"eventdata":{"subjectUserSid":"S-1-5-21-2635242741-4024004514-10403589-1001","subjectUserName":"Zenidd","subjectDomainName":"DESKTOP-D33AN6I","subjectLogonId":"0x6e03e","status":"0xc000013a","processId":"0xc34","processName":"C:\\Windows\\System32\\cmd.exe"}}}


**Phase 1: Completed pre-decoding.
       full event: '{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4689","version":"0","level":"0","task":"13313","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-04T12:45:38.962884600Z","eventRecordID":"47823","processID":"4","threadID":"284","channel":"Security","computer":"DESKTOP-D33AN6I","severityValue":"AUDIT_SUCCESS","message":"Se salió de un proceso."},"eventdata":{"subjectUserSid":"S-1-5-21-2635242741-4024004514-10403589-1001","subjectUserName":"Zenidd","subjectDomainName":"DESKTOP-D33AN6I","subjectLogonId":"0x6e03e","status":"0xc000013a","processId":"0xc34","processName":"C:\\Windows\\System32\\cmd.exe"}}}'
       timestamp: '(null)'
       hostname: 'nanoPill'
       program_name: '(null)'
       log: '{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-a5ba-3e3b0328c30d}","eventID":"4689","version":"0","level":"0","task":"13313","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-04T12:45:38.962884600Z","eventRecordID":"47823","processID":"4","threadID":"284","channel":"Security","computer":"DESKTOP-D33AN6I","severityValue":"AUDIT_SUCCESS","message":"Se salió de un proceso."},"eventdata":{"subjectUserSid":"S-1-5-21-2635242741-4024004514-10403589-1001","subjectUserName":"Zenidd","subjectDomainName":"DESKTOP-D33AN6I","subjectLogonId":"0x6e03e","status":"0xc000013a","processId":"0xc34","processName":"C:\\Windows\\System32\\cmd.exe"}}}'

**Phase 2: Completed decoding.
       decoder: 'json'
       win.system.providerName: 'Microsoft-Windows-Security-Auditing'
       win.system.providerGuid: '{54849625-5478-4994-a5ba-3e3b0328c30d}'
       win.system.eventID: '4689'
       win.system.version: '0'
       win.system.level: '0'
       win.system.task: '13313'
       win.system.opcode: '0'
       win.system.keywords: '0x8020000000000000'
       win.system.systemTime: '2019-12-04T12:45:38.962884600Z'
       win.system.eventRecordID: '47823'
       win.system.processID: '4'
       win.system.threadID: '284'
       win.system.channel: 'Security'
       win.system.computer: 'DESKTOP-D33AN6I'
       win.system.severityValue: 'AUDIT_SUCCESS'
       win.system.message: 'Se salió de un proceso.'
       win.eventdata.subjectUserSid: 'S-1-5-21-2635242741-4024004514-10403589-1001'
       win.eventdata.subjectUserName: 'Zenidd'
       win.eventdata.subjectDomainName: 'DESKTOP-D33AN6I'
       win.eventdata.subjectLogonId: '0x6e03e'
       win.eventdata.status: '0xc000013a'
       win.eventdata.processId: '0xc34'
       win.eventdata.processName: 'C:\Windows\System32\cmd.exe'

**Phase 3: Completed filtering (rules).
       Rule id: '60103'
       Level: '0'
       Description: 'Windows audit success event'

```
### Your rules and your example event.

Seems like something is wrong with the event you pasted above. Did you manually changed any field? The paths found on your event that you got from your `archives.log` file should contain the `\` characters escaped, as in the example event I pasted above but it doesn't.

The further event is the same that you pasted above but with the `\` characters escaped.
```
{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4663","version":"1","level":"0","task":"12812","opcode":"0","keywords":"0x8020000000000000","systemTime":"2019-12-03T14:38:05.128446200Z","eventRecordID":"1664492","processID":"480","threadID":"488","channel":"Security","computer":"WIN-AIEOJTT8UG6","severityValue":"AUDIT_SUCCESS","message":"Se intentó tener acceso a un objeto."},"eventdata":{"subjectUserSid":"S-1-5-21-2800651688-3019912576-308981525-500","subjectUserName":"Administrador","subjectDomainName":"WIN-AIEOJTT8UG6","subjectLogonId":"0x243b7e","objectServer":"Security","objectType":"File","objectName":"C:\\Users\\Administrador\\Desktop\\carpeta_test\\Nuevo documento de texto.txt","handleId":"0xfa0","accessList":"%%4416","accessMask":"0x1","processId":"0x478","processName":"C:\\Windows\\explorer.exe","resourceAttributes":"S:AI"}}}
```

Also, it triggers an alert if I enter it in the `ossec-logtest` binary:
```
**Phase 2: Completed decoding.
       decoder: 'json'
       win.system.providerName: 'Microsoft-Windows-Security-Auditing'
       win.system.providerGuid: '{54849625-5478-4994-A5BA-3E3B0328C30D}'
       win.system.eventID: '4663'
       win.system.version: '1'
       win.system.level: '0'
       win.system.task: '12812'
       win.system.opcode: '0'
       win.system.keywords: '0x8020000000000000'
       win.system.systemTime: '2019-12-03T14:38:05.128446200Z'
       win.system.eventRecordID: '1664492'
       win.system.processID: '480'
       win.system.threadID: '488'
       win.system.channel: 'Security'
       win.system.computer: 'WIN-AIEOJTT8UG6'
       win.system.severityValue: 'AUDIT_SUCCESS'
       win.system.message: 'Se intentó tener acceso a un objeto.'
       win.eventdata.subjectUserSid: 'S-1-5-21-2800651688-3019912576-308981525-500'
       win.eventdata.subjectUserName: 'Administrador'
       win.eventdata.subjectDomainName: 'WIN-AIEOJTT8UG6'
       win.eventdata.subjectLogonId: '0x243b7e'
       win.eventdata.objectServer: 'Security'
       win.eventdata.objectType: 'File'
       win.eventdata.objectName: 'C:\Users\Administrador\Desktop\carpeta_test\Nuevo documento de texto.txt'
       win.eventdata.handleId: '0xfa0'
       win.eventdata.accessList: '%%4416'
       win.eventdata.accessMask: '0x1'
       win.eventdata.processId: '0x478'
       win.eventdata.processName: 'C:\Windows\explorer.exe'
       win.eventdata.resourceAttributes: 'S:AI'

**Phase 3: Completed filtering (rules).
       Rule id: '60103'
       Level: '0'
       Description: 'Windows audit success event'
```
That's why I think that you manually modified the event.


On the other hand, I ported your rule to its Eventchannel version:
```XML
<group name="integrity, dlp,">
<rule id="100100" level="5">
   <if_sid>60103</if_sid>
   <field name="win.system.eventID">4663</field>
   <description>Windows User attempted to access an object</description>
   <options>no_full_log</options>
 </rule>


<rule id="100101" level="5">
 <if_sid>100100</if_sid>
 <field name="win.eventdata.accessList">%%4416</field>
 <description>Windows User attempted to access an object - Read Data</description>
</rule>

<rule id="100102" level="5">
 <if_sid>100100</if_sid>
 <field name="win.eventdata.accessList">%%4417</field>
 <description>Windows User attempted to access an object - Write Data</description>
</rule>

<rule id="100103" level="5">
 <if_sid>100100</if_sid>
  <field name="win.eventdata.accessList">%%4418</field>
  <description>Windows User attempted to access an object - Append Data</description>
</rule>
</group>
```

And here you have an example output:
```
**Phase 2: Completed decoding.
       decoder: 'json'
       win.system.providerName: 'Microsoft-Windows-Security-Auditing'
       win.system.providerGuid: '{54849625-5478-4994-A5BA-3E3B0328C30D}'
       win.system.eventID: '4663'
       win.system.version: '1'
       win.system.level: '0'
       win.system.task: '12812'
       win.system.opcode: '0'
       win.system.keywords: '0x8020000000000000'
       win.system.systemTime: '2019-12-03T14:38:05.128446200Z'
       win.system.eventRecordID: '1664492'
       win.system.processID: '480'
       win.system.threadID: '488'
       win.system.channel: 'Security'
       win.system.computer: 'WIN-AIEOJTT8UG6'
       win.system.severityValue: 'AUDIT_SUCCESS'
       win.system.message: 'Se intentó tener acceso a un objeto.'
       win.eventdata.subjectUserSid: 'S-1-5-21-2800651688-3019912576-308981525-500'
       win.eventdata.subjectUserName: 'Administrador'
       win.eventdata.subjectDomainName: 'WIN-AIEOJTT8UG6'
       win.eventdata.subjectLogonId: '0x243b7e'
       win.eventdata.objectServer: 'Security'
       win.eventdata.objectType: 'File'
       win.eventdata.objectName: 'C:\Users\Administrador\Desktop\carpeta_test\Nuevo documento de texto.txt'
       win.eventdata.handleId: '0xfa0'
       win.eventdata.accessList: '%%4416'
       win.eventdata.accessMask: '0x1'
       win.eventdata.processId: '0x478'
       win.eventdata.processName: 'C:\Windows\explorer.exe'
       win.eventdata.resourceAttributes: 'S:AI'

**Phase 3: Completed filtering (rules).
       Rule id: '100101'
       Level: '5'
       Description: 'Windows User attempted to access an object - Read Data'
**Alert to be generated.
```
Well, let me know how it goes. Here I am if you need further guidance.
Greetings, JP Sáez

**Comment by BernaldoPenasAntelo** [comment]
Hi:

Thanks for your response and forgiveme because of the delay.
About your question of the event that i post, i didn't modifiy anything, i paste it as i get from the archives.log.
I'm not going to be able to test in my lab enviroment for a while but next step for me it's to remove my decoder and test my rules, cause as far as i see you didin't mainly modify them, with the regular windows eventchannel decoder and real events and check if they trigger any alarms as expected.

 best regards.

**Comment by Zenidd** [comment]
Hello again @BernaldoPenasAntelo,

Don't worry about the delayed reply, I was AFK for some days too. 

> I'm not going to be able to test in my lab enviroment for a while but next step for me it's to remove my decoder and test my rules, cause as far as i see you didin't mainly modify them, with the regular windows eventchannel decoder and real events and check if they trigger any alarms as expected.

Yes, you should remove your decoder and about the rules, the minor modification above should be enough. Let me know how it goes a count for me if you need further guidance.

On the other hand, for further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez

**Comment by BernaldoPenasAntelo** [comment]
Finally ... i been able to test it and it works ... Thanks for your help.
