### ISSUE TITLE
Compliance Support for CMMC

### ISSUE THREAD

**Issue by galactic-admin** [wazuh/wazuh#4333]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Compliance | N/A | N/A | N/A |

The Cybersecurity Maturity Model Certification (CMMC) will be replacing NIST 800-171 and NIST 800-53 next year. Any and all companies and organizations that have contracts with the United States Federal Government and DoD will need to meet CMMC requirements starting 2020, with a deadline of 2025 (time-frame of individual company contract renewal will dictate when they need to meet compliance).

This issue is a request to have the CMMC framework added to the list of existing compliance modules.

CMMC Information: https://www.acq.osd.mil/cmmc/index.html

NOTE: The CMMC is still in draft form, and is expected to be published January 2020, and will be using many of the same controls from the NIST 800-53 and NIST 800-171 frameworks.

**Comment by Zenidd** [comment]
Hello @galactic-admin,

Thank you for letting us know. We want to get ready so Wazuh can help users to meet with the latest compliances as already does with other security standards like `GDPR`, `PCI DSS` or `GPG13`.  Therefore we will closely observe the development and release of this new compliance and try to take advantage of its resemblance to `NIST`. This resemblance is nice as we are not starting from nothing.

As a brief list of tasks for the CMMC compliance:

- Map rules to CMMC standard.
- Map SCA checks to CMMC standard.
- New Wazuh UI dashboard for CMMC standard.

We will consider including this new feature in the product roadmap to be available in upcoming releases. Thank you once more for letting us know.

Regards, JP Sáez

**Comment by jlj0304** [comment]
@Zenidd, is there any update to CMMC being integrated into Wazuh? With the release of 4.0, is there a chance that CMMC will replace the NIST 800-53 or add to it?

**Comment by mmasino-matc** [comment]
Checking on an update for this. We are also needing to cover CMMC compliance instead of NIST.

**Comment by 72nomada** [comment]
Hi @mmasino-matc and @jlj0304,

We are working now on CMMC covering, will there is no ERD planning is in-progress and work will start soon. Please stay tuned. 

Thanks, 
Jose Izquierdo

**Comment by devapps80** [comment]
Thank you @72nomada 

> Hi @mmasino-matc and @jlj0304,
> 
> We are working now on CMMC covering, will there is no ERD planning is in-progress and work will start soon. Please stay tuned.
> 
> Thanks,
> Jose Izquierdo

**Comment by 72nomada** [comment]
Hi @devapps80, if you don't mind, we will close this and will follow on #7658

**Comment by bimal1970** [comment]
We are implementing the Wazuh security monitoring platform for CMMC compliance to monitor security and vulnerabilities across our Windows, Ubuntu, and Rocky Linux machines. We have already added them as agents, but the SCA scan results are not appearing on the Wazuh dashboard for Rocky Linux. Could someone please assist with this issue?

Additionally, I would like to know if it's possible to set up NIST 800-171 assessment display on Wazuh. Any guidance on this matter would be appreciated. Thank you.

**Comment by bimal1970** [comment]
We are implementing the Wazuh security monitoring platform for CMMC compliance to monitor security and vulnerabilities across our Windows, Ubuntu, and Rocky Linux machines. We have already added them as agents, but the SCA scan results are not appearing on the Wazuh dashboard for Rocky Linux. Could someone please assist with this issue?

Additionally, I would like to know if it's possible to set up NIST 800-171 assessment display on Wazuh. Any guidance on this matter would be appreciated. Thank you.
