### ISSUE TITLE
FIM v2.0: Unit testing for Syscheckd functions

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#4336]
|Working branch|
|---|
| [3319-fim-rework-unit-tests](https://github.com/wazuh/wazuh/tree/3319-fim-rework)|

The purpouse of this issue is to keep track of progress made on the creation and review of unit testing done on the syscheck module in the context of the FIM rework.

# Status
|Test file|Review|Line Coverage|Status|
|---|---|---|---|
|test_file_op|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-564036373)|2.7%|Pass|
|test_integrity_op|Done|100%|Pass|
|test_rbtree_op|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-562117047)|78.8%|Fail|
|test_version_op|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-562145785)|22.7%|Pass|
|test_create_db|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-562098205)|82.1%|Pass|
|test_syscheck_audit|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-562233484)|91.2%|Pass|
|test_seechanges|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-562235239)|100%|Pass|
|test_syscom|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-563929199)|100%|Pass|
|test_run_realtime|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-563977575)|83.7%|Pass|
|test_syscheck_config|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-563987250)|52%|Pass|
|test_syscheck|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-563989437)|100%|Pass|
|test_fim_sync|Done|93.8%|Pass|
|test_run_check|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-564031821)|100%|Pass|
|test_syscheck_op|[Comments](https://github.com/wazuh/wazuh/issues/4336#issuecomment-565555820)|99.4%|Fail|

**Comment by Molter73** [comment]
### test_create_db

- fim_check_restrict returns 0 when a match for the regex is found, but it does too if the input regex is NULL, seems like a bug on the function itself.
- Tests for fim_audit_inode_event don't make any assertions.
- Tests on fim_checker don't make any assertions.
- Tests on fim_scan don't make any assertions.
- Tests on fim_get_data are not running the generation of hashes.
- Tests on fim_delete don't make any assertions.
- Tests on fim_realtime_event don't make any assertions.
- Tests on check_deleted_files don't make any assertions.
- Tests on delete_inode_item don't make any assertions.

**Comment by Molter73** [comment]
### test_integrity_op

- [expect_assert_failure](https://api.cmocka.org/group__cmocka__mock__assert.html#gab1cc38a7a3d0cbb7da53935d6f8645ed) and [mock_assert](https://api.cmocka.org/group__cmocka__mock__assert.html#ga7f1663184edbd6120732191c4bffada2) should be used in order to test the standard C assertions used in the integrity_op functions.

**Comment by Molter73** [comment]
### test_rebtree_op

- Non of the basic rb_* private functions are tested directly, only through calls to higher level functions.
- test_rbtree_insert_failure should assert that the input value is not destroyed by rbtree_insert.
- The following functions are not tested for NULL input parameters:
  - rbtree_insert
  - rbtree_maximum
  - rbtree_minimum
  - rbtree_keys
  - rbtree_ranges
  - rbtree_black_depth
  - rbtree_size
  - rbtree_empty

**Comment by Molter73** [comment]
### test_version_op
- Currently only one of the written tests is being run.
- uname could be wrapped in order to check more values on tests and make them system independent.

**Comment by Molter73** [comment]
### test_syscheck_audit
- openproc and readproc should be wrapped if possible in order to add failure tests for check_auditd_enabled.
- When wrapping fopen the expected mode could be added.
- When wrapping fwrite the expected input could be checked.
- regcomp should be wrapped in order to test init_regex.
- Tests on audit_parse rely on init_regex being tested previously and leaving the regex preinitialized. Tests on init_regex should clean up the environment on exit and audit_parse should explicitly compile global regexes by calling init_regex if they are necessary, easiest way would be a couple of shared setup/teardown functions for this.
- The following tests make no assertions:
  - test_audit_parse_rm_hc
  - test_audit_parse_add_hc
  - test_audit_parse_unknown_hc

**Comment by Molter73** [comment]
### test_seechanges
- is_nodiff is the only function tested.

**Comment by Molter73** [comment]
### test_syscom
- The mwarn wrapper could be improved by adding expected input values where applicable.
- fim_sync_push_msg should be wrapped
- On test_syscom_dispatch_restart, either wrap os_set_restart_syscheck in order to check it is being called or check os_restart.syscheck and os_restart.rootcheck for changed values.
- syscom_dispatch is not tested for a NULL input parameters.
- When calling will_return on __wrap_getSyscheckConfig, __wrap_getRootcheckConfig and __wrap_getSyscheckInternalOptions, passing the cJSON object or NULL would be easier to read.
- syscom_main is not tested.

**Comment by Molter73** [comment]
### test_run_realtime
- Instead of wrapping read to mock the real OSHash_Create function, either have OSHash_Create return a fixed OSHash object or wrap os_getprime, wrapping results in too many dependencies for testing functions on run_realtime.
- test_realtime_adddir_whodata could check the directory is added to the vector.
- test_realtime_adddir_realtime_add should add a mdebug2 wrapper in order to have a more precise test.
- free_syscheck_dirtb_data is a wrapper for the free function, either delete the tests for this function or add __wrap_free in order to check it is properly called.
- The following tests make no assertions:
  - test_realtime_process_failure
  - test_realtime_process

**Comment by Molter73** [comment]
### test_syscheck_config
- test_Read_Syscheck_Config_success should either check the read configuration in order to guarantee it is correct or wrap ReadConfig.
- test_getSyscheckConfig and test_getSyscheckInternalOptions should check the contestns of the returned cJSON, not just the length of arrays.
- Tests for free_whodata_event are in create_db.c, they should be moved to this source.

**Comment by Molter73** [comment]
### test_syscheck
- test_read_internal is not run.
- The following tests make no assertions:
  - test_fim_initialize
  - test_fim_initialize_warn

**Comment by Molter73** [comment]
### test_fim_sync
- The assert statements should be checked for the error condition.
- fim_sync_checksum_split and fim_sync_send_list should be checked for NULL start and top input parameters.
- The following functions should be wrapped:
  - fim_entry_json
  - dbsync_state_msg
  - dbsync_check_msg 
- The following tests make no assertions:
  - test_fim_sync_push_msg_no_response
  - test_fim_sync_dispatch_noarg
  - test_fim_sync_dispatch_invalidarg
  - test_fim_sync_dispatch_invalid_id
  - test_fim_sync_dispatch_id
  - test_fim_sync_dispatch_unknown

**Comment by Molter73** [comment]
### test_run_check
- test_fim_whodata_initialize can check the global values initialized by fim_whodata_initialize and wrap calls to realtime_adddir and audit_set_db_consistency.
- test_log_realtime_status and test_fim_whodata_initialize are the only functions tested.

**Comment by Molter73** [comment]
### test_file_op
- Currently the only function being tested is CreatePID.

**Comment by Molter73** [comment]
### test_syscheck_op
- The following tests fail due to the tested function not handling null inputs correctly, causing segmentation faults:
  - test_normalize_path_null_input
  - test_remove_empty_folders_null_input
  - test_sk_decode_sum_extra_data_null_sum
  - test_sk_decode_sum_extra_data_null_c_sum
  - test_sk_decode_extradata_null_c_sum
  - test_sk_fill_event_null_eventinfo
  - test_sk_fill_event_null_f_name
  - test_sk_fill_event_null_sum
  - test_sk_build_sum_null_sum
  - test_sk_build_sum_null_output
  - test_sk_sum_clean_null_sum
  - test_attrs_to_json_null_attributes
  - test_win_perm_to_json_null_input
- The following tests fail with segmentation faults due to the tested function attempting to free pointers to the middle of blocks or uninitialized:
  - test_sk_sum_clean_shortest_valid_message
  - test_sk_sum_clean_invalid_message
- Additionally remove_empty_folders is meant to delete only folders under a specific directory ("/var/ossec/queue/diff/local" by default), but never explicitly checks to see if the requested folder is under this directory, causing the function to keep going until finding a directory it is unable to remove (either due to a permission problem or finding a folder that is not empty).

**Comment by chemamartinez** [comment]
Done & merged at [3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)
