### ISSUE TITLE
Super decoder/alert

### ISSUE THREAD

**Issue by brickwall1** [wazuh/wazuh#4340]
Hello,

I need to define decoders/alerts for my syslog devices.
But now i want to send to elastic all logs from syslog and biuld these decoders/alerts later. How can i do it?

**Comment by Lopuiz** [comment]
Hello @brickwall1 

Only alerts can be shown in Kibana. If you want to see all logs in Kibana you can create a rule which matches all logs and generate alert.

You can follow our [documentation](https://documentation.wazuh.com/3.10/user-manual/ruleset/index.html) to create new rules and decoders. If you need help with some rule or decoder you can send us the logs and we will help you to create it.

Please, for the next questions subscribe to our mailing list or join on slack.
[Wazuh community](https://wazuh.com/community/)

Best regards,
Eva

**Comment by Lopuiz** [comment]
I'll close this issue for inactivity
