### ISSUE TITLE
No debug messages to inform when the FIM database is synchronized

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#4349]
When the synchronization process starts, Syscheck prints the following debug message:

> Performing synchronization check.

However, we cannot see a similar message when the synchronization ends. It is necessary to include that information to analyze the communication performance between Analysisd and Syscheck.

The function that arbitrates synchrony is:

https://github.com/wazuh/wazuh/blob/7cd01987759791ee9109efd5d235d68b97570d39/src/syscheckd/fim_sync.c#L28-L52

**Comment by chemamartinez** [comment]
For now, it is not contemplated to perform this change for design reasons.

Regards.
