### ISSUE TITLE
FIM v2.0: First synchronization fails when Wazuh DB is empty

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh#4350]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.11.0-31111 | Syscheck (FIM) | Manager & Agent | Sources | centos7 |

Hello team, 

We've detected the following issue with the new FIM module for Wazuh 3.11, it seems that the first synchronization between manager and agent fails (or, at least, is not marked as completed).

## Steps to reproduce
- Deploy a manager and agent
- Stop the agent
- Register the agent 
- On manager, check the output of the following query (using [this script](https://github.com/wazuh/wazuh-tools/blob/master/utils/wdb-query.py))
```java
# ./wdb-query.py 003 "SELECT * FROM sync_info"
[
    {
        "component": "fim",
        "last_attempt": 0,
        "last_completion": 0,
        "n_attempts": 0,
        "n_completions": 0
    }
]
```
- Start the agent and wait a few minutes:
```java
# ./wdb-query.py 003 "SELECT * FROM sync_info"
[
    {
        "component": "fim",
        "last_attempt": 1576071485,
        "last_completion": 1576071485,
        "n_attempts": 2,
        "n_completions": 1
    }
]
```

If you restart the agent or wait for `sync_interval` to be completed, the following attempts will probably be successful (in my tests they have been always been successful but they could fail for external causes such as a network problem or a real problem in the file integrity).

If you clean the Wazuh database, for example, by running: the following command (with Agent stopped and Manager running)

```java
./wdb-query.py 001 "Delete FROM fim_entry"
./wdb-query.py 001 "UPDATE sync_info SET last_attempt = 0, last_completion = 0, n_attempts = 0, n_completions = 0 WHERE component = 'fim'"
```
and start the agent again, the first attemp will also fail.

If you register the same agent again (it will receive a new id and, therefore, a new database), the first synchronization with the new ID will also fail.

We need to check if there is a real problem during the synchronization or, maybe, if the n_completitions count is not being updated when required.

**Comment by chemamartinez** [comment]
Closing the issue. It is a design matter.

Regards.
