### ISSUE TITLE
Cannot save Process information

### ISSUE THREAD

**Issue by dbray925** [wazuh/wazuh#4353]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-1 | Syscollector/wazuh-db/Process | Manager | Packages | CentOS 7 |

I've just migrated from OSSEC to Wazuh. I decided to start clean, as this is a test environment, so this wasn't necessarily a migration, but more of a rip and replace. Installation went smooth, only unknown issue I can see at this time is certain servers are failing the Syscollector - Process information. Here is the DEBUG logs:

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 008 query: sca query_scan cis_rhel7

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 008 query: process save 1620668989|2019/12/11 13:32:06|1|systemd|S|0|1019|1045|/usr/lib/systemd/systemd|--switched-root,--system,--deserialize,22|root|root|root|root|root|root|root|20|0|10926|43704|1018|649|2|1|1|1|1|0|1

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:204 at wdb_parse(): DEBUG: Updated 'sys_processes' table for agent '008'

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 008 query: process save 1620668989|2019/12/11 13:32:06|1|systemd|S|0|1019|1045|/usr/lib/systemd/systemd|--switched-root,--system,--deserialize,22|root|root|root|root|root|root|root|20|0|10926|43704|1018|649|2|1|1|1|1|0|1

2019/12/11 13:32:06 wazuh-db[18054] wdb_syscollector.c:888 at wdb_process_insert(): ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:3306 at wdb_parse_processes(): DEBUG: Cannot save Process information.

2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:206 at wdb_parse(): ERROR: Unable to update 'sys_processes' table for agent '008'

**Comment by vikman90** [comment]
Hi @dbray925.

Thank you for reporting this problem and sending us the debug messages.

It seems that the database is complaining about a duplicate entry. In fact, this log appears twice:
> 2019/12/11 13:32:06 wazuh-db[18054] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 008 query: process save 1620668989|2019/12/11 13:32:06|1|systemd|S|0|1019|1045|/usr/lib/systemd/systemd|--switched-root,--system,--deserialize,22|root|root|root|root|root|root|root|20|0|10926|43704|1018|649|2|1|1|1|1|0|1

Let me explain this message a bit:

```
1620668989|2019/12/11 13:32:06|1|systemd|...
^          ^                   ^       
Scan ID    Timestamp           PID
```

What this means is that the manager is attempting to save the same process (1) from the same scan (1620668989) twice.

I cannot figure out why this is happening. The issue is probably on the agent side.

Could you run Modulesd with debug on the agent? 

```sh
echo wazuh_modules.debug=2 >> /var/ossec/etc/local_internal_options.conf
service wazuh-agent restart
```

Then, leave Syscollector run a scan and find the log for the process with PID 1:
```sh
grep sys_proc_linux /var/ossec/logs/ossec.log | grep '"pid":1,'
```
> 2019/12/12 04:11:52 wazuh-modulesd:syscollector[8997] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending '{"type":"process","ID":103390150,"timestamp":"2019/12/12 04:11:52","process":{"pid":1,"name":"systemd","state":"S","ppid":0,"utime":27,"stime":153,"cmd":"/usr/lib/systemd/systemd","argvs":["--switched-root","--system","--deserialize","21"],"euser":"root","ruser":"root","suser":"root","egroup":"root","rgroup":"root","sgroup":"root","fgroup":"root","priority":20,"nice":0,"size":48391,"vm_size":193564,"resident":1270,"share":645,"start_time":4,"pgrp":1,"session":1,"nlwp":1,"tgid":1,"tty":0,"processor":3}}'

That is a sample result on CentOS 7 (Vagrant box). I haven't been able to reproduce that so far.

Could you do the same and share your results with us? On the other hand, does this issue appear consistently?

Thank you.
Best regards.

**Comment by dbray925** [comment]
Well it was consistently happening all day yesterday after the initial install, and on multiple servers. Today, however, I am no longer seeing the issue. Very weird, and kind of annoying. I waited before opening this issue, but wouldn't you know it...as soon as I did, the issue resolves itself.

I've been updating various things, but mainly just tweaking some "ignores" and things like that. I'm guessing one of the updates, restarts, or whatever must have fixed the issue. Thank you for your time though, and I've updated my notes with those above troubleshooting steps.

**Comment by dbray925** [comment]
Ignore the above. Guess it just took awhile for the error to come back. Unfortunately, I removed all the DEBUG settings to quiet the log files down. I will enable those settings again, leave them in place, and capture the necessary logs.

As stated above, this is happening on multiple different agents:
2019/12/12 23:50:56 wazuh-db: ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid
2019/12/12 23:50:56 wazuh-db: ERROR: Unable to update 'sys_processes' table for agent '048'
2019/12/12 23:50:56 ossec-analysisd: ERROR: at sc_send_db(): received: 'err Cannot save Process information.'
2019/12/12 23:50:56 wazuh-db: ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid
2019/12/12 23:50:56 wazuh-db: ERROR: Unable to update 'sys_processes' table for agent '027'
2019/12/12 23:50:56 ossec-analysisd: ERROR: at sc_send_db(): received: 'err Cannot save Process information.'
2019/12/12 23:50:56 wazuh-db: ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid
2019/12/12 23:50:56 wazuh-db: ERROR: Unable to update 'sys_processes' table for agent '065'
2019/12/12 23:50:56 ossec-analysisd: ERROR: at sc_send_db(): received: 'err Cannot save Process information.'


I will report back once I have better DEBUG information.

**Comment by dbray925** [comment]
I was finally able to grab some good DEBUG information. Here is the entry from the master:
2019/12/17 00:02:57 wazuh-db[20223] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 065 query: process save 
525107137|2019/12/17 00:02:57|1|systemd|S|0|221|292|/usr/lib/systemd/systemd|
--switched-root,--system,--deserialize,22|root|root|root|root|root|root|root|
20|0|10889|43556|987|655|3|1|1|1|1|0|1

2019/12/17 00:02:57 wazuh-db[20223] wdb_syscollector.c:888 at wdb_process_insert(): ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid

2019/12/17 00:02:57 wazuh-db[20223] wdb_parser.c:3306 at wdb_parse_processes(): DEBUG: Cannot save Process information.

2019/12/17 00:02:57 wazuh-db[20223] wdb_parser.c:206 at wdb_parse(): ERROR: Unable to update 'sys_processes' table for agent '065'


Checking the agent, and I see about 13 similar DEBUG lines that look like this:
2019/12/17 00:02:57 wazuh-modulesd:syscollector[1928] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending
'{"type":"process",
"ID":525107137,
"timestamp":"2019/12/17 00:02:57",
"process":
  {"pid":1,"
    name":"systemd",
    "state":"S",
    "ppid":0,
    "utime":221,
    "stime":292,
    "cmd":"/usr/lib/systemd/systemd",
    "argvs":["--switched-root","--system","--deserialize","22"],
    "euser":"root",
    "ruser":"root",
    "suser":"root",
    "egroup":"root",
    "rgroup":"root",
    "sgroup":"root",
    "fgroup":"root",
    "priority":20,
    "nice":0,
    "size":10889,
    "vm_size":43556,
    "resident":987,
    "share":655,
    "start_time":3,
    "pgrp":1,
    "session":1,
    "nlwp":1,
    "tgid":1,
    "tty":0,
    "processor":1}}'

The only differences in each of the 13 lines are the values for:
2019/12/17 00:02:57 wazuh-modulesd:syscollector[1928] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending
'{"type":"process",
"ID":525107137,
    "utime":221,
    "stime":292,
    "processor":1}}'

2019/12/17 09:02:57 wazuh-modulesd:syscollector[1928] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending 
'{"type":"process",
"ID":574675028,
  "utime":466,
  "stime":521,
  "processor":6}}'

2019/12/17 12:02:57 wazuh-modulesd:syscollector[1928] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending
 '{"type":"process",
 "ID":511877785,
   "utime":543,
   "stime":599,
   "processor":2}}'

**Comment by vikman90** [comment]
@dbray925 Thank you for sending your system's debugging logs.

The logs following the first one are normal: the scan ID is different, so I think there are no bugs here.

On the other hand, there is only one log about process 1 at 00:02:57 —could you confirm this?—: 
```
2019/12/17 00:02:57 wazuh-modulesd:syscollector[1928] syscollector_linux.c:1596 at sys_proc_linux(): DEBUG: sys_proc_linux() sending
'{"type":"process",
"ID":525107137,
"timestamp":"2019/12/17 00:02:57",
"process":
{"pid":1,"
name":"systemd",
"state":"S",
"ppid":0,
"utime":221,
"stime":292,
"cmd":"/usr/lib/systemd/systemd",
"argvs":["--switched-root","--system","--deserialize","22"],
"euser":"root",
"ruser":"root",
"suser":"root",
"egroup":"root",
"rgroup":"root",
"sgroup":"root",
"fgroup":"root",
"priority":20,
"nice":0,
"size":10889,
"vm_size":43556,
"resident":987,
"share":655,
"start_time":3,
"pgrp":1,
"session":1,
"nlwp":1,
"tgid":1,
"tty":0,
"processor":1}}'
```

That event is producing a duplicate ID/PID pair error. The scan ID is random for every scan. If this scan ID was the same as the previous scan, we would have a lot of errors in the database —not only one—. 

I have two suggestions:

1. Could you confirm that your agent 65 has no duplicate logs about the same scan ID and PID?
2. The manager (Analysisd) boosts up the Syscollector logs analysis by parallelizing the process. This should not produce any issue with duplicate IDs, but just in case, could you set a single thread for Syscollector analysis? Please add this line to the manager's file _/var/ossec/etc/local_internal_options.conf_, and restart the manager:

```
analysisd.syscollector_threads=1
```

Hope this helps. Looking forward to catching this bug soon.
Thank you again.
Best regards.

**Comment by dbray925** [comment]
It seems I'm seeing duplicate logs for the same ID/PID in the manager log file. Here is a more recent log entry:

```
2019/12/23 00:03:05 wazuh-db[20223] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 065 query: process save 
411498721|2019/12/23 00:03:04|1|systemd|S|0|2885|3102|/usr/lib/systemd/systemd|--switched-root,-
-system,--deserialize,22|root|root|root|root|root|root|root|20|0|10889|43556|994|655|3|1|1|1|1|0|3
2019/12/23 00:03:05 wazuh-db[20223] wdb_parser.c:204 at wdb_parse(): DEBUG: Updated 'sys_processes' table for agent '065'

2019/12/23 00:03:05 wazuh-db[20223] wdb_parser.c:76 at wdb_parse(): DEBUG: Agent 065 query: process save 411498721|2019/12/23 00:03:04|1|systemd|S|0|2885|3102|/usr/lib/systemd/systemd|--switched-root,-
-system,--deserialize,22|root|root|root|root|root|root|root|20|0|10889|43556|994|655|3|1|1|1|1|0|3
2019/12/23 00:03:05 wazuh-db[20223] wdb_syscollector.c:888 at wdb_process_insert(): ERROR: at wdb_process_insert(): sqlite3_step(): UNIQUE constraint failed: sys_processes.scan_id, sys_processes.pid
2019/12/23 00:03:05 wazuh-db[20223] wdb_parser.c:3306 at wdb_parse_processes(): DEBUG: Cannot save Process information.

```
These seem to be the same entry back to back, first one works, the second fails because it is an exact duplicate of the first. 

In checking the agent log files, with DEBUG turned on, it is a lot to look over, but I do not think I caught any duplicated logs about the same scan ID and PID.

I've added the single thread setting and restarted the manager. Waiting and monitoring the log files.

**Comment by dbray925** [comment]
Quick update. I noticed an updated version was available, wazuh-manager-3.11.0-1.x86_64, so I applied that. Unfortunately, the issue remains.

**Comment by jesusjimsa** [comment]
Hello @dbray925, could you confirm me if you are using Docker when you get this error, please?

**Comment by dbray925** [comment]
No Docker, just CentOS 7 package install.

**Comment by jesusjimsa** [comment]
Could you execute this in one of the affected machines and paste here the output?
```
ps aux | grep "deserialize"
```

**Comment by dbray925** [comment]
/usr/lib/systemd/systemd --switched-root --system --deserialize 22

**Comment by Dwordcito** [comment]
@dbray925 Many modifications were made (refactor to c++) in versions equal to or greater than 4.2, could you inform me if the error continues to reproduce.

**Comment by dbray925** [comment]
No, I have not seen this error in a very long time. Thank you.
