### ISSUE TITLE
FIM v2.0: Unit testing for WazuhDB functions

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh#4354]
|Working branch|
|---|
|[3319-fim-rework-unit-tests](https://github.com/wazuh/wazuh/tree/3319-fim-rework)|

The purpose of this issue is to keep track of progress made on the creation and review of unit testing done on the Wazuh DB module in the context of the FIM module.

Tier 1 (FIM v2.0)
----------------
**wdb_fim.c**
- [x] wdb_syscheck_save2
- [x] wdb_fim_insert_entry2

**wdb_integrity.c**
- [x] wdbi_checksum_range
- [x] wdbi_delete
- [x] wdbi_update_attempt
- [x] wdbi_update_completion
- [x] wdbi_query_checksum
- [x] wdbi_query_clear

**wdb_parser.c**
- [x] wdb_parse_syscheck

Tier 2 (FIM v1.0 & external functions)
-------------------------------------
**wdb_fim.c**
- [ ] wdb_insert_file
- [ ] wdb_find_file
- [ ] wdb_get_last_fim
- [ ] wdb_insert_fim
- [ ] wdb_delete_fim
- [ ] wdb_delete_fim_all
- [ ] wdb_syscheck_load
- [ ] wdb_syscheck_save
- [ ] wdb_fim_find_entry
- [ ] wdb_fim_insert_entry
- [ ] wdb_fim_update_entry
- [ ] wdb_fim_delete
- [ ] wdb_fim_update_date_entry
- [ ] wdb_fim_clean_old_entries

**wdb_parser.c**
- [ ] wdb_parse

Status
----------

Test file | Review | Line Coverage | Status
-- | -- | -- | --

**Comment by JcabreraC** [comment]
### wdb_syscheck_save2


TEST|STATUS
|--|--|
Test_wdb_syscheck_save2_wbs_null|**Failed**. The function does not check whether parameter `wbs` is null, causing a segmentation fault.
Test_wdb_syscheck_save2_payload_null|**Failed**. The function does not check whether parameter `payload` is null, causing a segmentation fault.
Test_wdb_syscheck_save2_data_null|**Passed**
Test_wdb_syscheck_save2_fail_transaction|**Passed**
Test_wdb_syscheck_save2_fail_file_entry|**Passed**
Test_wdb_syscheck_save2_success|**Passed**

**Comment by Skeptor** [comment]
### wdb_parse_syscheck

TEST|STATUS
|--|--|
test_wdb_parse_syscheck_no_space|**Passed**
test_scan_info_error|**Passed**
test_scan_info_ok|**Passed**
test_update_info_error|**Passed**
test_update_info_ok|**Passed**
test_clean_old_entries_error|**Passed**
test_clean_old_entries_ok|**Passed**
test_scan_info_update_noarg|**Passed**
test_scan_info_update_error|**Passed**
test_scan_info_update_ok|**Passed**
test_scan_info_fim_check_control_error|**Passed**

**Comment by JcabreraC** [comment]
### wdb_syscheck_save2


TEST|STATUS
|--|--|
test_wdb_fim_insert_entry2_wdb_null|**Failed**. The function does not check whether parameter `wbs` is null, causing a segmentation fault.
test_wdb_fim_insert_entry2_data_null|**Passed**
test_wdb_fim_insert_entry2_path_null|**Passed**
test_wdb_fim_insert_entry2_timestamp_null|**Passed**
test_wdb_fim_insert_entry2_attributes_null|**Passed**
test_wdb_fim_insert_entry2_fail_cache|**Passed**
test_wdb_fim_insert_entry2_fail_element_string|**Pending**
test_wdb_fim_insert_entry2_fail_sqlite3_stmt|**Passed**
test_wdb_fim_insert_entry2_success|**Passed**

**Comment by JcabreraC** [comment]
### wdbi_checksum_range


TEST|STATUS
|--|--|
test_wdbi_checksum_range_wdb_null|
test_wdbi_checksum_range_component_null|
test_wdbi_checksum_range_begin_null|
test_wdbi_checksum_range_end_null|
test_wdbi_checksum_range_hexdigest_null|
test_wdbi_checksum_range_wdb_stmt_cache_fail|
test_wdbi_checksum_range_step_no_100|
test_wdbi_checksum_range_success|

**Comment by JcabreraC** [comment]
### wdbi_delete


TEST|STATUS
|--|--|
test_wdbi_delete_wdb_null|**Failed**. The function does not check whether parameter `wbs` is null, causing a segmentation fault.
test_wdbi_delete_begin_null|**Passed**
test_wdbi_delete_end_null|**Passed**
test_wdbi_delete_tail_null|**Passed**
test_wdbi_delete_wdb_stmt_cache_fail|**Passed**
test_wdbi_delete_sql_no_done|**Passed**
test_wdbi_delete_success|**Passed**

**Comment by JcabreraC** [comment]
### wdbi_update_attempt


TEST|STATUS
|--|--|
test_wdbi_update_attempt_wbs_null|**Failed**. The function does not check whether parameter `wbs` is null, causing a segmentation fault.
test_wdbi_update_attempt_stmt_cache_fail|**Passed**
test_wdbi_update_attempt_no_sql_done|**Passed**
test_wdbi_update_attempt_success|**Passed**

**Comment by JcabreraC** [comment]
### wdbi_update_completion


TEST|STATUS
|--|--|
test_wdbi_update_completion_wbs_null|**Failed**. The function does not check whether parameter `wbs` is null, causing a segmentation fault.
test_wdbi_update_completion_stmt_cache_fail|**Passed**
test_wdbi_update_completion_no_sql_done|**Passed**
test_wdbi_update_completion_success|**Passed**

**Comment by Skeptor** [comment]
**wdbi_query_clear**


TEST|STATUS
|--|--|
test_wdbi_query_clear_null_payload|**Failed**. If the payload is NULL, the JSON object is also NULL and Wazuh DB tries to log the payload in a Debug1 message.
test_wdbi_query_clear_invalid_payload|**Passed**
test_wdbi_query_clear_no_id|**Passed**
test_wdbi_query_clear_stmt_cache_error|**Passed**
test_wdbi_query_clear_sql_step_error|**Passed**
test_wdbi_query_clear_ok|**Passed**

**Comment by Skeptor** [comment]
**wdbi_query_checksum**


TEST|STATUS
|--|--|
test_wdbi_query_integrity_null_payload|**Failed**. If the payload is NULL, the JSON object is also NULL and Wazuh DB tries to log the payload in a Debug1 message.
test_wdbi_query_checksum_no_begin|**Pending**
test_wdbi_query_checksum_no_end|**Pending**
test_wdbi_query_checksum_no_checksum|**Pending**
test_wdbi_query_checksum_no_id|**Pending**
test_wdbi_query_checksum_range_fail|**Pending**
test_wdbi_query_checksum_equal_hexdigest|**Pending**
test_wdbi_query_checksum_diff_hexdigest|**Pending**
test_wdbi_query_checksum_bad_command|**Pending**
test_wdbi_query_checksum_check_global_attempt|**Pending**
test_wdbi_query_checksum_check_global_completion|**Pending**
test_wdbi_query_checksum_check_left|**Pending**

**Comment by chemamartinez** [comment]
Done & merged at [3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)
