### ISSUE TITLE
unrecognizable characters error

### ISSUE THREAD

**Issue by damayu2013** [wazuh/wazuh#436]
i use Non-English Windows10 OS, after install agent:
![tim 20180308221209](https://user-images.githubusercontent.com/16527289/37157952-1d0de702-2325-11e8-8b4a-a96b44803a6d.png)

os_name and os_uname show unrecognizable characters:
![tim 20180308225942](https://user-images.githubusercontent.com/16527289/37157990-33b117e0-2325-11e8-90a5-19ebbbea6c7e.png)

global.db
![tim 20180308221952](https://user-images.githubusercontent.com/16527289/37158013-4a0f4200-2325-11e8-9699-4aa55dfafb40.png)

and wazuh-kibana get erro:
![tim 20180308222031](https://user-images.githubusercontent.com/16527289/37158055-601ab566-2325-11e8-915f-12e1e52f682c.png)

![tim 20180308222054](https://user-images.githubusercontent.com/16527289/37158066-66c96b82-2325-11e8-8f7c-4d1d4ff1581c.png)

how to solve the problem,thank you;

PS: use wazuh-3.2.1

**Comment by albertomn86** [comment]
Hi @damayu2013 

thank you for reporting this issue. We are already aware about this problem with non-english versions of Windows and we are working on it. 
We hope to have a solution to this issue as soon as possible.

Best regards,

**Comment by albertomn86** [comment]
This issue is solved in https://github.com/wazuh/wazuh/pull/478
