### ISSUE TITLE
FIM v2.0: Set a maximum synchronization interval

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4363]
|Related issue|
|---|
|#3319|

## Description

The FIM module implements a synchronization protocol to ensure the data stored in the manager is consistent with the one scanned by the agents.

This protocol is configurable by the following set of settings:

```xml
<inventory>
    <sync_interval>5m</sync_interval>
    <response_timeout>30</response_timeout>
    <sync_queue_size>16384</sync_queue_size>
</inventory>
```

In particular, `sync_interval` defines the frequency to start the sync protocol. When the synchronization fails (e.g. due to overload in the manager side, network issues), it is reattempted every interval sending a big amount of messages to recover the stable state.

This fact does not help the synchronization to get accomplished.

## Proposed solution

Make the interval incremental for every failed sync attempt.

### Requirements

- [x] Increase the interval x2 every failed attempt. When success, reset the initial value (`sync_interval`)

- [x] Add descriptive logs to inform about the remaining time for each sync attempt

- [x] Add a setting `max_sync_interval` to limit the maximum interval timeout. When that value is reached, the interval doesn't grow anymore

- [x] Default value for `max_sync_interval` should be 1 hour

- [x] Add the new setting to the remote configuration 

- [x] Add the new setting to the FIM v2.0 documentation https://github.com/wazuh/wazuh-documentation/pull/2027

**Comment by nicolaspapp** [comment]
## Update 1
> * [x]  Increase the interval x2 every failed attempt. When success, reset the initial value (`sync_interval`)

The method `fim_run_integrity` will be modified to keep track of synchronization failures

``` C
void * fim_run_integrity(void * args) {
    // Keep track of synchronization failures
    int fim_sync_failed_multiplicator = 1;

    fim_sync_queue = queue_init(syscheck.sync_queue_size);

    while (1) {
        bool fim_sync_successfull = true;
        
        mdebug2("Performing synchronization check.");
        fim_sync_checksum();

        struct timespec timeout = { .tv_sec = time(NULL) + (syscheck.sync_interval * fim_sync_failed_multiplicator ) };

        // Get messages until timeout
        char * msg;

        while ((msg = queue_pop_ex_timedwait(fim_sync_queue, &timeout))) {
            long margin = time(NULL) + syscheck.sync_response_timeout;

            fim_sync_dispatch(msg);
            free(msg);

            // Wait for sync_response_timeout seconds since the last message received, or sync_interval
            timeout.tv_sec = timeout.tv_sec > margin ? timeout.tv_sec : margin;

            fim_sync_successfull = false;
        }

        if(fim_sync_successfull){
            fim_sync_failed_multiplicator = 1;
        }
        else{
            // Duplicate for every failure
            fim_sync_failed_multiplicator *= 2;
        } 
    }

    return args;
}
```

The variable `fim_sync_failed_multiplicator` will store the time multiplicator, which will be duplicating itself for every failure detected by the `fim_sync_successfull` flag. This multiplicator will be set back to 1 if the synchronization process is successfull

**Comment by nicolaspapp** [comment]
## Update 2
> - [x] Add a setting to limit the maximum attempts (`sync_max_attempts`). When that value is reached, the interval doesn't grow anymore
> - [x] A value of zero means unlimited attempts, this should be the default value.

Instead of a `sync_max_attemps` key will be adding a new key to establish a maximum synchronization interval:

Option | Default | Description
-- | -- | --
max_sync_interval |   0m  | Maximum allowed synchronization intervals. When value is zero (default) there is no limit 

Example configuration
``` xml 
<inventory>
  <sync_interval>5m</sync_interval>
  <max_sync_interval>0m</max_sync_interval>
  <response_timeout>30</response_timeout>
  <sync_queue_size>16384</sync_queue_size>
</inventory>
```
