### ISSUE TITLE
Space in syslog program_name not handled

### ISSUE THREAD

**Issue by cfi-gb** [wazuh/wazuh#438]
While doing https://github.com/wazuh/wazuh-ruleset/pull/102 i've noticed that Wazuh 3.2.1 isn't catching e.g. the program_name of the following syslog entry:

```
Mar 10 09:54:53 hostname gsad main[8990]: Starting GSAD version 7.0.2
```

leading to a not caught program_name:

```
**Phase 1: Completed pre-decoding.
       full event: 'Mar 10 09:54:53 hostname gsad main[8990]: Starting GSAD version 7.0.2'
       timestamp: 'Mar 10 09:54:53'
       hostname: 'hostname'
       program_name: '(null)'
       log: 'gsad main[8990]: Starting GSAD version 7.0.2'

**Phase 2: Completed decoding.
       No decoder matched.
```

I'm not sure if the ``gsad main[8990]:`` is something compliant with the syslog format.

**Comment by vikman90** [comment]
Hi @cfi-gb,

This log is not compliant with the syslog format.

Please take a look at the [RFC-3164](https://www.ietf.org/rfc/rfc3164.txt).

### Heading 4.1.3

> (...) 
> **The TAG is a string of ABNF alphanumeric characters that MUST NOT exceed 32 characters.**  Any non-alphanumeric character will terminate the TAG field and will be assumed to be the starting character of the CONTENT field.  Most commonly, the first character of the CONTENT field that signifies the conclusion of the TAG field has been seen to be the left square bracket character ("["), a colon character (":"), or a space character.  This is explained in more detail in Section 5.3.

### Heading 5.3

> It has also been considered to be a good practice to include some information about the process on the device that generated the message - if that concept exists.  This is usually the process name and process id (often known as the "pid") for robust operating systems.  The process name is commonly displayed in the TAG field. Quite often, additional information is included at the beginning of the CONTENT field.  The format of "TAG[pid]:" - without the quote marks - is common.  **The left square bracket is used to terminate the TAG field in this case and is then the first character in the CONTENT field.**  If the process id is immaterial, it may be left off.
> In that case, a colon and a space character usually follow the TAG. This would be displayed as "TAG: " without the quotes.  In that case, the colon is the first character in the CONTENT field.

In other words: the TAG part of a syslog header strictly ends with any non-alphanumerical character, even with `[`. So, in your case, the TAG part would be "gsad".

The Wazuh pre-decoder extracts the TAG if it's ended with `[` or `:`. In the former case, it discards the process ID and takes the log after `:`.

With *gsad* left, the input is compliant with a syslog message.

Best regards.

**Comment by cfi-gb** [comment]
Hey, and thanks for your reply / the great input. I was stumbling over the same RFC later but wasn't quite sure as it had some different examples in Heading "5.4 Examples". Especially the RFC says at "5.2 Domain Name and Address":

> To readily identify the device that originated the message, it may be a good practice to include its fully qualified domain name (FQDN) and its IP address within the CONTENT field.  Traditionally, however, only the hostname has been included in the HOSTNAME field.

When using the stripped down example:

``Oct 22 10:52:01 scapegoat.dmz.example.org 10.1.2.3 sched[0]: That's All Folks!``

Wazuh is also not able to extract the program_name:

```
**Phase 1: Completed pre-decoding.
       full event: 'Oct 22 10:52:01 scapegoat.dmz.example.org 10.1.2.3 sched[0]: That's All Folks!'
       timestamp: 'Oct 22 10:52:01'
       hostname: 'scapegoat.dmz.example.org'
       program_name: '(null)'
       log: '10.1.2.3 sched[0]: That's All Folks!'

**Phase 2: Completed decoding.
       No decoder matched.
```

On the other hand i have found http://www.rsyslog.com/doc/master/configuration/properties.html as well which has some other examples like:

``Mar 10 09:54:53 hostname sbin/gsad[8990]: Starting GSAD version 7.0.2``

where Wazuh would extract the full ``sbin/gsad`` even if ``/`` is not alphanumerical:

```
**Phase 1: Completed pre-decoding.
       full event: 'Mar 10 09:54:53 hostname sbin/gsad[8990]: Starting GSAD version 7.0.2'
       timestamp: 'Mar 10 09:54:53'
       hostname: 'hostname'
       program_name: 'sbin/gsad'
       log: 'Starting GSAD version 7.0.2'

**Phase 2: Completed decoding.
       No decoder matched.
```

It looks to me that there are so many different variants of the syslog messages out there which are not easy to extract / parse by Wazuh.

Any suggestion how to proceed with this?

**Comment by rossengeorgiev** [comment]
@cfi-gb 

`1990 Oct 22 10:52:01 scapegoat.dmz.example.org sched[0]: That's All Folks!` is not valid rtc3164 format. The example you are referring is used to illustrate how relays should handle such messages.

> Example 4
>
>      <0>1990 Oct 22 10:52:01 TZ-6 scapegoat.dmz.example.org 10.1.2.3
>      sched[0]: That's All Folks!
>
>    This example has a lot of extraneous information throughout.  A human
>    or sufficiently adaptable automated parser would be able to determine
>    the date and time information as well as a fully qualified domain
>    name (FQDN) [4] and IP address.  The information about the nature of
>    the event is, however, limited.  Due to the indicated severity of the
>    event, the process may not have been able to gather or send anything
>    more informative.  It may have been fortunate to have generated and
>    sent this message at all.
>    This example is obviously an original message from a device.  **Since
>    the first field in the HEADER part is not a TIMESTAMP in the format
>    defined in Section 4.1.2, it MUST be modified by a relay.** A relay
>    will add a TIMESTAMP and SHOULD add a HOSTNAME as follows and will
>    treat the entire received packet after the PRI part from the original
>    packet as the CONTENT field of the new packet.  The value used in the
>    HOSTNAME field is only the hostname without the domain name as it is
>    known by the relay.  A TAG value will not be added to the relayed
>    packet.  While the inclusion of the domain name and IPv4 address in
>    the original message is a noble endeavor, it is not consistent with
>    the use of the field as described in Section 4.1.2.
>  
>     <0>Oct 22 10:52:12 scapegoat 1990 Oct 22 10:52:01 TZ-6 scapegoat.dmz.example.org 10.1.2.3 sched[0]: That's All Folks!

I valid syslog would look like this:

`1990 Oct 22 10:52:01 scapegoat.dmz.example.org sched[0]: That's All Folks`

If you want consistency, I can only suggest putting `rsyslog` in front of `wazuh`. `rsyslog` will handle the wierdness and will forward a valid RFC3164 to `wazuh`.
