### ISSUE TITLE
Add Agent Key Polling capability to wazuh-clusterd

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4387]
## Description

The Agent Key Polling feature lets any worker node request a new key for any of its reporting agents. This is useful for some environments where the agent keys are managed externally.

The diagram below illustrates the sequence of events that must be implemented:

![imagen](https://user-images.githubusercontent.com/17462947/71351476-0d6e7c00-2574-11ea-8fc9-90640213234e.png)

1. An agent without a valid key tries to connect to a manager (a worker node in this example).
2. `remoted` (having the agent key polling mode enabled) requests to `clusterd` a new agent key. `clusterd` process this call asynchronously and immediately answers an ack to `remoted`.
3. `clusterd` in worker creates an asynchronous request to the master node that triggers the agent key polling module.
4. `clusterd` in master asks `modulesd` (which runs the agent key polling module) to get a new key for the agent.
5. `modulesd` uses an external script which is in charge of managing agent keys to get a valid one.
6. `modulesd` sends the new key to `authd`.
7. `authd` updates the `client.keys` file.
8. `clusterd`'s Integrity thread notices a new version of `client.keys`.
9. The `client.keys` is sent to the worker node.
10. The updated `client.keys` is written in the worker node and the agent now is granted sending events to the manager.

## Main tasks

To achieve this, the following issues must be solved:
- Add new logic to `clusterd` to process the distributed request in the master node and send a new agent key to the workers (steps 2, 3 and 4).
- Develop a new call from `remoted` to clusterd to trigger the Agent Key Polling procedure (steps 1 and 2).
- Enable a new call to `modulesd` to let the master node request a new agent key (step 4).

### Testing
- https://github.com/wazuh/wazuh-qa/issues/564

**Comment by davidjiglesias** [comment]
To be done differently in #9092
