### ISSUE TITLE
Possible descriptor leak in Rootcheck on Windows

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4388]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 3.9.4 | Rootcheck | Agent | Windows |

@wazuh/cicd has detected that the agent process is increasing the number of semaphore and token handles everytime that Rootcheck runs a scan:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/10536251/71355616-def69e00-257f-11ea-91fc-4241426c3fba.png">

**Comment by alberpilot** [comment]
Windows agent ossec.conf: 
[windows_ossec.conf.txt](https://github.com/wazuh/wazuh/files/3997891/windows_ossec.conf.txt)

The file `internal_options.conf` can be modified with the following setting:
```rootcheck.sleep=0```

**Comment by vikman90** [comment]
This bug was caused by:

- 5e609e9 (OSSEC v1.0).
- 8eb1712 (Wazuh v3.9.4). 

The latter presumes to affect every component running on Windows that uses `OSList_Create()`:

- Rootcheck.
- SCA.
