### ISSUE TITLE
Separate indices 

### ISSUE THREAD

**Issue by brickwall1** [wazuh/wazuh#4389]
Hello,

Now i send all alerts to one index, but i want to separate it to something like this(it's only example) *-win-* and *-lin-* to have separate indices for windows and for linux. How can i filter them in logstash filter (or in output section)?

**Comment by pablotr9** [comment]
Hi @brickwall1 ,

This can be done in multiple ways I will explain you two different options, the first one using Logstash and the second one using only Filebeat. 
One solution could be naming your agents to include the OS name:
**Windows agents**: windows-\<agent-name>
**Linux agents**: linux-\<agent-name>
This way you can easily know if an alert is coming from a Windows agent or a Linux agent.
Now, you can add some conditions to the Logstash output section:
```
output {
 if [agent][name] =~ /linux/ {
   
    elasticsearch {
        hosts => ["172.16.1.2:9200"]
        manage_template => true
        template_overwrite => true
        template => "/etc/logstash/wazuh-template.json"
        template_name => "wazuh"
        index => "wazuh-alerts-3.x-linux-%{+YYYY.MM.dd}"
    }
 } else if [agent][name] =~ /windows/ {
  
    elasticsearch {
        hosts => ["172.16.1.2:9200"]
        manage_template => true
        template_overwrite => true
        template => "/etc/logstash/wazuh-template.json"
        template_name => "wazuh"
        index => "wazuh-alerts-3.x-windows-%{+YYYY.MM.dd}"
    }
 }else {
    elasticsearch {
        hosts => ["172.16.1.2:9200"]
        manage_template => true
        template_overwrite => true
        template => "/etc/logstash/wazuh-template.json"
        template_name => "wazuh"
        index => "wazuh-alerts-3.x-%{+YYYY.MM.dd}"
    }
 } 
}
```
With the regex operator `=~`  we can filter by agent.name in the alerts, as you can see in that example:
- If the agent name contains the word `linux` it will be sent to the index `wazuh-alerts-3.x-linux-%{+YYYY.MM.dd}`
- If the agent name contains the word `windows`, the alert will be sent to the index `wazuh-alerts-3.x-windows-%{+YYYY.MM.dd}`
- If the alert does not contain netiher `linux` nor `windows` words, the alert will be sent to the index `wazuh-alerts-3.x-%{+YYYY.MM.dd}` 
Now that you have different indices for linux and windows you can create an index pattern for them and you can switch the index pattern in the Wazuh WUI to show only alerts related to an specific OS.
![image](https://user-images.githubusercontent.com/35685689/71470679-3dfd2280-27cd-11ea-8380-9f78725d6b4f.png)

This is one possible solution, another option (without using Logstash- only Filebeat) is defining a processor in the filebeat.yml that depending on the **agent.name** adds a new field to the alert that you can use to filter the results of a search:
```
processors:
- add_fields:
    when:
        contains:
             agent.name: "linux"
    fields:
      os_name: linux

- add_fields:
    when:
        contains:
             agent.name: "windows"
    fields:
      os_name: windows
```

This way, you will avoid having multiple indices, all the alerts will be stored in the same index but your alerts will have a new field (**os_name** in this case) with the name of the OS, so you can filter the results depending on the OS you want to check.


I hope it helps, let me know if you have any trouble configuring this so I can give you further assistance.

Kind regards,
Pablo Torres

**Comment by Zenidd** [comment]
Hello @brickwall1,

I'm closing this ticket due to inactivity. Do not hesitate to comment here again if you keep having issues, we will reopen the ticket with no problem. On the other hand, for further questions we would like you to use our #community Slack channel or the Wazuh mail list.


Best regards, JP Sáez
