### ISSUE TITLE
Inventory: Alerts and synchronization mechanism

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#4397]
|Main issue|
|---|
| https://github.com/wazuh/wazuh/issues/3940 |

The new inventory events were already developed and they are explained in this issue: https://github.com/wazuh/wazuh/issues/4316

To continue with the syscollector rework, now it is necessary to cover the following tasks:

- [ ] Create a synchronization mechanism that ensure the integrity of the data between manager and agent.

- [ ] Trigger alerts when the manager receives a new event.

- [ ] Add unit tests to developed features.

**Comment by Dwordcito** [comment]
This has already been implemented in other epics, issue is closed.
