### ISSUE TITLE
wazuh Event per second(eps)

### ISSUE THREAD

**Issue by tekletade** [wazuh/wazuh#4399]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.10.2 | Wazuh component | Manager | Sources | ubuntu 18.0.4 |

Hello,
how many eps(events per second) can wazuh generate???
help me.
regars.

**Comment by Selutario** [comment]
Hello @tekletade

Wazuh can generate **up to 1000 events per second**. To set the desired value, you need to edit the `<client_buffer>` section that you will find in /var/ossec/etc/ossec.conf. Below you can see an example where a value of 500 events per second is set:
```XML
<client_buffer>
    <!-- Agent buffer options -->
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
</client_buffer>
```
If you want more information about it, you can find it [here](https://documentation.wazuh.com/3.11/learning-wazuh/survive-flood.html?highlight=eps).

Kind regards,
Jose Luis.

**Comment by Zenidd** [comment]
Hello @tekletade,

Your question seems answered, I'm closing this issue.
