### ISSUE TITLE
Add number of buffered events to ossec-agentd.state file

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh#4413]
Hi team,

The current content of `ossec-agentd.state` file contains the further fields:
```bash
# State file for ossec-agentd

# Agent status:
# - pending:      waiting to get connected.
# - connected:    connection established with manager in the last 10 seconds.
# - disconnected: connection lost or no ACK received in the last 10 seconds.
status='pending'

# Last time a keepalive was sent
last_keepalive=''

# Last time a control message was received
last_ack=''

# Number of generated events
msg_count='0'

# Number of messages (events + control messages) sent to the manager
msg_sent='822'
``` 

To get the exact number of buffered events, subtracting the `Number of messages` and `Number of generated events` is not an accurate method as the messages also include the control messages.

Having a metric for the number of buffered messages would be really useful. 

Greetings, JP Sáez

**Comment by vikman90** [comment]
Fixed by #7239.
