### ISSUE TITLE
Issue Remote Upgrade .pt 2

### ISSUE THREAD

**Issue by Theoooooo** [wazuh/wazuh#4414]
This issue is a following to #4192 because i can't reopen this one.
There is the entire process i want through

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2 | Remote Upgrade | Manager | Sources | CentOS 7 |

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.3 | Remote Upgrade | Agent | Sources | Windows Server 2016 R2 |

I'm having issue remote upgrading windows and linux agents remotly.
I got a dual manager setup in a HA configuration behind a load balancer to distribute authentication request to the master manager and the events to both my managers.

Now the issue i'm getting is the API throw me timeout after launching the upgrade process :
```
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/019/upgrade?pretty"
{
   "error": 3021,
   "message": "Timeout executing API request"
}
```
Note that the linux agents i've upgraded where inside the same subnet as the manager so there is no conflit of a firewall misconfigured.
But the agent gets undeed upgraded in the process and restarted properly after this.

I also tried to upgrade agents in other subnets (which are able to communicate properly with my manager though the load balancer) and it's working properly with the WAzuhAPI but not with the "agent_upgrade" command :

agent_upgrade output :
```
bin/agent_upgrade -a 032
Error 1715: Error sending WPK file: Cannot send request
```

wazuh_api output :
```
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/032/upgrade?pretty"
{
   "error": 3021,
   "message": "Timeout executing API request"
}
```

And like before, the agent got upgraded with the API properly but i didn't have a good return from the API.

Result of the agent upgrade with the API in Grafana :
![image](https://user-images.githubusercontent.com/33425208/71617261-96ac3100-2bba-11ea-8942-de36f37f0436.png)

I've tested this with **Linux AND Windows** from VM outside the manager subnet and it's working properly.
There is some kind of issue with the "agent_upgrade" command but it's working with the API

I can't try this process on the 2 mentionned VM above because there has been some changes in the FW in there network and there a not able to communicate with my wazuh load balancer anymore. But i will try later.

For the timeout issue with the API, i think i pinpoint the issue : I got a static redirection on the FW to redirect every connection with the destination port 1514-1515 to my LoadBalancer. If the manager communication the upgrade process to the agents with these ports, my manager will never got the answer from the agent because the response got routed to the LoadBalancer.

Or if the manager is using another port to communicate with the client, i should check the FW configuration to let this port through my subnet.
On the officiel documentation, i'm only seeing the port 55000 being used by the api and nothing else. We should have the choise to use another port for the upgrade process.

Maybe that's not the issue but i think this is the problem :/

Another update on the subject, i got agent_upgrade mostly working with the following command :
```
bin/agent_upgrade -a 028 -dF -f /var/ossec/var/upgrade/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
```

If i don't specify the file with the "-f" option, the process stop immediately with the following error :
```
bin/agent_upgrade -a 016 -dF -v v3.10.2 --http
Manager version: 3.11.0
Agent version: Wazuh v3.11.0
Agent new version: v3.10.2
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.10.2_linux_x86_64.wpk - SHA1SUM:                                                                                                            216f793e1ccaece72ec2f0c46e54c37e1f9b8606
Upgrade PKG: wazuh_agent_v3.10.2_linux_x86_64.wpk (4877.83203125 KB)
MSG SENT: 016 com lock_restart -1
RESPONSE: err Cannot send request
Error 1715: Error sending WPK file: Cannot send request
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.0-py3.7.egg/wazuh/agent.p                                                                                                           y", line 2159, in upgrade
    use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.0-py3.7.egg/wazuh/agent.p                                                                                                           y", line 2010, in _send_wpk_file
    raise WazuhException(1715, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1715 - Error sending WPK file: Cannot send request
```

Also, the manager is never getting a response from the agent and timeouts occur as the agent does not respond to the upgrade process like this :
```
bin/agent_upgrade -a 028 -dF -f /var/ossec/var/upgrade/wazuh_agent_v3.10.2_windows.wpk -x upgrade.bat
Custom WPK file: wazuh_agent_v3.10.2_windows.wpk (2553.669921875 KB)
MSG SENT: 028 com lock_restart -1
RESPONSE: ok
MSG SENT: 028 com open wb wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok
Chunk size: 512 bytes
FILE SHA1: 1141118b0e3548e65031346aa10f65fbf5ad408c
MSG SENT: 028 com close wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok
MSG SENT: 028 com sha1 wazuh_agent_v3.10.2_windows.wpk
RESPONSE: ok 1141118b0e3548e65031346aa10f65fbf5ad408c
WPK file sent
MSG SENT: 028 com upgrade wazuh_agent_v3.10.2_windows.wpk upgrade.bat
RESPONSE: ok 0
Installation started
MSG SENT: 028 com upgrade_result
RESPONSE: err Cannot read upgrade_result file.
MSG SENT: 028 com upgrade_result
^C
```

Or this : 
```
bin/agent_upgrade -a 018 -dF
Manager version: 3.11.1
Agent version: Wazuh v3.11.0
Agent new version: v3.11.1
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.11.1_linux_x86_64.wpk - SHA1SUM: 891c42443eee13a228c8309bf4c6ceec3e94fd08
Upgrade PKG: wazuh_agent_v3.11.1_linux_x86_64.wpk (5160.6708984375 KB)
MSG SENT: 018 com lock_restart -1
RESPONSE: ok
MSG SENT: 018 com open wb wazuh_agent_v3.11.1_linux_x86_64.wpk
RESPONSE: ok
MSG SENT: 018 com lock_restart -1
RESPONSE: ok
Chunk size: 512 bytes
Sending: /var/ossec/var/upgrade/wazuh_agent_v3.11.1_linux_x86_64.wpk
MSG SENT: 018 com close wazuh_agent_v3.11.1_linux_x86_64.wpk
RESPONSE: ok
MSG SENT: 018 com sha1 wazuh_agent_v3.11.1_linux_x86_64.wpk
RESPONSE: ok 891c42443eee13a228c8309bf4c6ceec3e94fd08
WPK file sent
MSG SENT: 018 com upgrade wazuh_agent_v3.11.1_linux_x86_64.wpk upgrade.sh
RESPONSE: ok 0
Upgrade procedure started
MSG SENT: 018 com upgrade_result
RESPONSE: err Cannot send request
MSG SENT: 018 com upgrade_result
RESPONSE: err Cannot send request
```

But with this, the agent gets undeed upgraded and restarted properly after the process is finished, like the api above : the response is not being received by the manager under my configuration

**Comment by AdriiiPRodri** [comment]
Hi @Theoooooo,

The first error is well-known, in version `4.0` it will be fixed. At the moment the solution to avoid the timeout is adding the **wait_for_complete** flag to the call. The error is due to the fact that the update process **takes longer than the timeout specified for each API call**. Thus the update process is completed but the API returns a timeout. To fix it we just need to add the following:

```bash
curl -u username:password -X PUT "http://172.31.27.4:55000/agents/019/upgrade?pretty&wait_for_complete"
```

The port `55000` is only used for the Wazuh API. There is no need to modify this port. On the other hand, error `1715` may be due to multiple reasons. In Wazuh version `3.11` the error messages of the agent update process were improved, I recommend you to update to the latest stable version ([3.11.1](https://documentation.wazuh.com/3.11/upgrade-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor)). 

If we run the same API call from version `3.11` we can see the error in more detail. On the other hand, we can set the **debug mode of the execd daemon in the agent we want to update**. To do this, we have to go to `/var/ossec/etc/internal_options.conf` and change the line `execd.debug=0` to `execd.debug=2`.

As for the load balancer, to update the Wazuh agents we use port `1514`, maybe the update process works correctly but when a new connection is created again to check the status of the update, the load balancer redirects to some **Worker** node. This is what may have happened in the last execution you shared.
Therefore I recommend you to check the configuration of the load balancer to be able to update the agents without any problem.

I hope I helped you. For any other questions, please don't hesitate to ask. 
I look forward to your answer.

Best regards,
Adri

**Comment by Theoooooo** [comment]
Thanks for the answer,

To test this, i downgrade a windows agent to 3.10.2 and upgrade it back to 3.11.1.

Sadly, the file integrity don't match at the end and i'm getting this error :
```
bin/agent_upgrade -a 034 -dF -v v3.11.1
Manager version: 3.11.1
Agent version: Wazuh v3.10.2
Agent new version: v3.11.1
Downloading WPK file from: https://packages.wazuh.com/wpk/windows/wazuh_agent_v3.11.1_windows.wpk
Error 1714: The file has lost integrity in the transfer. Original SHA1; a376b77d1d40f019004f0df1ebdfff51ed609293 , Received SHA1; fe4c05167800fea03375560022cbd5875ad1d275
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.1-py3.7.egg/wazuh/agent.py", line 2159, in upgrade
    use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.1-py3.7.egg/wazuh/agent.py", line 1992, in _send_wpk_file
    _get_wpk = self._get_wpk_file(wpk_repo=wpk_repo, debug=debug, version=version, force=force, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.1-py3.7.egg/wazuh/agent.py", line 1977, in _get_wpk_file
    cmd_error=True)
wazuh.exception.WazuhException: Error 1714 - The file has lost integrity in the transfer. Original SHA1; a376b77d1d40f019004f0df1ebdfff51ed609293 , Received SHA1; fe4c05167800fea03375560022cbd5875ad1d275
```

I tried removing the .wpk from the manager to let it download again but it seems the .wpk checksum has changed between monday and thursday

I was also wondering, can we specify which version to upgrade through the API ?

From the cli we can specify the version to upgrade/downgrade the agent but this option does not seems to exist in the documentation.

**Comment by AdriiiPRodri** [comment]
There seems to be an **error** in the Wazuh packages (https://groups.google.com/forum/#!topic/wazuh/oVgpvOXjOw), sorry for the inconvenience.

To update to a specific version we can use the **version parameter** of the call to update the agents, the command would be the following:

```
curl -u USER:PASSWORD -k -X PUT "https://API_IP:API_PORT/agents/AGENT_ID/upgrade?version=v3.11.1&pretty"
```

You can find more information here: [Upgrade agent](https://documentation.wazuh.com/3.11/user-manual/api/reference.html#upgrade-agent-using-online-repository)
For any other questions, don't hesitate to ask.

Regards

**Comment by Theoooooo** [comment]
I'm sorry but the ID in the google group link is incorrect.
Is there a solution inside this link or just an error report ?

**Comment by AdriiiPRodri** [comment]
Sorry, the link is now fixed. it is only an error report.

**Comment by Theoooooo** [comment]
Does downloading the file again fix it ? 
I still got the issue after removing the file and downloading it again from the master.
I also download it manually (https://documentation.wazuh.com/3.11/user-manual/agents/remote-upgrading/wpk-list.html#windows) and select the file in the cli like this :
```
bin/agent_upgrade -a 034 -f var/upgrade/wazuh_agent_v3.11.1_windows.wpk -x upgrade.bat
Sending WPK: [=========================] 100%
Installation started... Please wait.
```

And then nothing happened but the agent get upgraded.

**Comment by AdriiiPRodri** [comment]
This last error happens when trying to check that the agent **has finished the update process**. 
First the package is sent and the update process starts, and then it is checked that the agent has been updated.  It is in the last part where it has failed: [Upgrade result](https://github.com/wazuh/wazuh/blob/49e2a60680483e247c6e1b0e1da80e182ffa0519/framework/wazuh/agent.py#L2252)

In any case the process of updating agents remotely is being improved and we hope to have it finished as soon as possible. In the current code, there is a possible race condition, it could be that the process is started to check the update status in the agent at the moment it is being restarted. This could cause the error `1716` because the agent is eventually not ready to answer.

In addition, We could check the configuration of the load balancer (deleting sensitive information) to make sure everything is correct.

**Comment by Theoooooo** [comment]
Sure, there is my Load Balancer configuration on HAProxy 1.8.23. :
```
global
  user haproxy
  group haproxy

defaults
  log global
  mode tcp
  option tcplog
  option dontlognull
  timeout connect 5s
  timeout client 60s
  timeout server 60s

listen stats
  bind VIP:8081
  mode http
  stats enable
  stats uri /haproxy?stats
  stats auth username:password
  timeout connect 5s
  timeout client 10s
  timeout server 10s

frontend Frontend_Port_1514
  bind VIP:1514
  option forwardfor
  default_backend Backend_Port_1514

frontend Frontend_Port_1515
  bind VIP:1515
  option forwardfor
  default_backend Backend_Port_1515

backend Backend_Port_1514
  default-server inter 1s fall 3 rise 10
  server master_wazuh IP_Master:1514 weight 1 check
  server worker_wazuh IP_Worker:1514 weight 1 check

backend Backend_Port_1515
  default-server inter 1s fall 3 rise 10
  server master_wazuh IP_Master:1515 weight 1 check
```

**Comment by AdriiiPRodri** [comment]
Hi @Theoooooo,

I have looked at the load balancer settings and I think a possible problem may be in 
```
server master_wazuh IP_Master:1514 weight 1 check
server worker_wazuh IP_Worker:1514 weight 1 check
```

According to the documentation, the fact that both have the same weight means that the load will be **equally** distributed. You can see more information here: [HAProxy weight](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#5.2-weight)

In Wazuh environments this type of configuration **is not recommended** as it can result in possible **problems** with the **connections** between managers and agents. There are many algorithms but in Wazuh environments **is highly recommended to use IP hash**. 

In the case of the HAProxy balancer, the equivalent would be the **source** algorithm, [balance algorithm](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-balance) (by default the algorithm is **RoundRobin**). I recommend you to take a look at the following blog where we explain how to configure a load balancer to work in a Wazuh environment without problems: [Wazuh load balancer](https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/)

On the other hand, we can also enable the **debug** mode of the load balancer to see what may be happening, it can be enabled by following these steps [HAProxy debug mode](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#3.3-debug), the log is located in `/var/log/haproxy.log`.

Regards

**Comment by Theoooooo** [comment]
@AdriiiPRodri You're right on this point.
IP Source hashing should be the best choice for a load balancer, but it's not explicitly said in the documentation about the wazuh cluster : https://documentation.wazuh.com/3.11/development/wazuh-cluster.html?highlight=load%20balancer

**Comment by AdriiiPRodri** [comment]
No problem @Theoooooo, 

I give you the following link to the Wazuh documentation because the link you specified is for developers. To configure the cluster of Wazuh follow this link: [Configuring the Wazuh cluster](https://documentation.wazuh.com/3.11/user-manual/configuring-cluster/advanced-settings.html#pointing-agents-to-the-cluster-with-a-load-balancer)

Regards

**Comment by crd1985** [comment]
Closing this issue since it is not a feature request nor a bug report.
