### ISSUE TITLE
Slack integration crashes for alerts with no description

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#4418]
Slack integration crashes for alerts with no description in Wazuh Manager v3.10.2.

I consider that there are 3 issues:
- The first event after the restart generates 2 messages in Slack
- If the alert doesn't have description, the event is not sent to Slack
- After that, any alerts are sent to Slack

## Test

1. Configure Slack integration
2. Re-start Wazuh manager
3. Send event to the manager
```
logger -t sshd "pam_unix(sshd:session): session opened for user root by TEST WAZUH 1"
```

For some reason, this event generates 2 messages in slack (**first issue**):
```
integrations.log
Wed Jan 08 09:47:10 UTC 2020 /tmp/slack-1578476830-1857600020.alert https://hooks.slack.com/services/<id> > /dev/null
Wed Jan 08 09:47:13 UTC 2020 /tmp/slack-1578476833--522642422.alert https://hooks.slack.com/services/<id> > /dev/null
```
4. Send alert with no description:
```
echo '{"timestamp":"2019-12-16T23:43:42.683+0000","rule":{"level":4,"id":"11","mail":true,"groups":["stats"]},"agent":{"id":"xxx","name":"yyy"},"manager":{"name":"wazuh-manager-master-0"},"id":"1576539822.850338","cluster":{"name":"wazuh","node":"wazuh-manager-master-0"},"full_log":"The average number of logs between 23:00 and 24:00 is 7885. We reached 19714.","predecoder":{"program_name":"systemd","timestamp":"Dec 16 23:43:42"},"decoder":{"name":"systemd"},"location":"/var/log/syslog"}' >> /var/ossec/logs/alerts/alerts.json
```

```
integrations.log
Wed Jan 08 09:49:29 UTC 2020 /tmp/slack-1578476969--1723865066.alert https://hooks.slack.com/services/<id> > /dev/null
```

We can see the following error in the ossec.log and the alert is not sent to slack (**second issue**):

```
ossec.log
2020/01/08 09:49:29 ossec-integratord: ERROR: Unable to run integration for slack -> /var/ossec/integrations/slack
2020/01/08 09:49:29 ossec-integratord: ERROR: While running slack -> /var/ossec/integrations/slack. Output: KeyError: 'description'
```

The error is due to the `description` key doesn't exist in the `alert['rule']` dictionary ([line](https://github.com/wazuh/wazuh/blob/v3.10.2/integrations/slack#L88)):

```
msg['title'] = alert['rule']['description']
```

Since this moment, any alerts are sent to slack (**third issue**).

**Comment by vikman90** [comment]
@jesuslinares Let me answer issues 1 and 3:

## Two alerts appear in Slack

Your sample command:

```sh
logger -t sshd "pam_unix(sshd:session): session opened for user root by TEST WAZUH 1"
```

It produces two alerts: one from _/var/log/messages_ and another from _/var/log/syslog_:
```
** Alert 1579546462.354031: - pam,syslog,authentication_success,pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 20 19:54:22 buster->/var/log/messages
Rule: 5501 (level 3) -> 'PAM: Login session opened.'
User: root
Jan 20 19:54:22 buster sshd: pam_unix(sshd:session): session opened for user root by TEST WAZUH 1

** Alert 1579546462.354405: - pam,syslog,authentication_success,pci_dss_10.2.5,gpg13_7.8,gpg13_7.9,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 20 19:54:22 buster->/var/log/syslog
Rule: 5501 (level 3) -> 'PAM: Login session opened.'
User: root
Jan 20 19:54:22 buster sshd: pam_unix(sshd:session): session opened for user root by TEST WAZUH 1
```

That is not an issue in Wazuh.

## An integration that failed sends no further data

This is the expected behavior: when an integration exits with a code other than 0, Integratord disables it:
https://github.com/wazuh/wazuh/blob/v3.11.1/src/os_integrator/integrator.c#L412.

Explanation: https://github.com/wazuh/wazuh/issues/1483
An integration may fail due to a particular issue or a general problem, e.g. a package or dependency is missing. Letting Integratord run an integration that failed multiple times may waste resources.

Best regards.
