### ISSUE TITLE
Add report_changes and whodata attributes for <windows_registry> option

### ISSUE THREAD

**Issue by FabioPizzamiglio** [wazuh/wazuh#4420]
Hi Team,

currently agent.conf only supports report_changes and whodata attributes only for plain text in <directories> option in syscheck section, would it be possible to have them for windows_registry as well?
Having detail info also for windows_registry FIM changes would be useful.

Best regards
Fabio

**Comment by antoniomanuelfr** [comment]
Hi FabioPizzamiglio. 
Sorry for the late reply. 
As you mentioned, right now syscheck doesn't support report_changes and whodata for windows registries. 
We will consider to add this feature in a future.
Best regards. 
Antonio.

**Comment by antoniomanuelfr** [comment]
Hi @FabioPizzamiglio 

This feature that you were asking as been developed. 
- This is the report changes issue: https://github.com/wazuh/wazuh/issues/5865
- This is the whodata issue: https://github.com/wazuh/wazuh/issues/4223

These features need testing and are not completed yet, but you can take a look at them in this development branch ([fim-registry-improvements](https://github.com/wazuh/wazuh/tree/fim-registry-improvements))

I'm going to mark this issue as a duplicate and close it.
Kind regards.
