### ISSUE TITLE
Arguments are not passed to active-response script

### ISSUE THREAD

**Issue by marinovgit** [wazuh/wazuh#4422]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.1-1.x86_64 | active-response | Manager | Packages | CentOS Linux release 7.7.1908 (Core) |

The problem is that only dashes (empty) are passed to the script.
In the email is visible that the srcip is decoder correctly. but it is not passed to the active response script.

Active response log:
```Thu Jan  9 11:28:08 UTC 2020 /var/ossec/active-response/bin/openvpn.sh add - - 1578569288.255003 81801 /var/log/openvpn.log - -```

openvpn.sh
```#!/bin/sh
echo "`date` $0 $1 $2 $3 $4 $5 $6 $7 $8" >> /var/ossec/logs/active-responses.log
```
Rule:
```
<group name="openvpn,">
    <rule id="81801" level="10" overwrite="yes">
        <if_sid>81800</if_sid>
        <match>Peer Connection Initiated with</match>
        <description>OpenVPN: User logged in</description>        <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,</group>
    </rule>
<group>
```

command and active-response:

```
        <name>openvpn</name>
        <executable>openvpn.sh</executable>
        <expect></expect>
        <timeout_allowed>no</timeout_allowed>

        <command>openvpn</command>
        <location>local</location>
        <rules_id>81801</rules_id>
```

Email log:
```
Wazuh Notification.
2020 Jan 09 11:28:08

Received From: jump->/var/log/openvpn.log
Rule: 81801 fired (level 10) -> "OpenVPN: User logged in"
Src IP: 1.1.1.1
Portion of the log(s):

Jan  9 11:28:07 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434

```
Logtest:
```
**Phase 1: Completed pre-decoding.
       full event: 'Jan  9 11:28:07 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434'
       timestamp: 'Jan  9 11:28:07'
       hostname: 'server'
       program_name: 'openvpn'
       log: '1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434'

**Phase 2: Completed decoding.
       decoder: 'openvpn'
       srcip: '1.1.1.1'
       srcport: '57434'
       srcuser: 'user'

**Phase 3: Completed filtering (rules).
       Rule id: '81801'
       Level: '10'
       Description: 'OpenVPN: User logged in'
**Alert to be generated.

```

**Comment by Zenidd** [comment]
Hello @marinovgit,

First of all, thanks for the detailed issue description.

> In the email is visible that the srcip is decoder correctly. but it is not passed to the active response script.

While the `srcip` field is correctly extracted, you should also specify it in the [<expect>](https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/commands.html#expect) command section related to the active response.

- In your command, the `<expect>` section is empty

```XML
<name>openvpn</name>
<executable>openvpn.sh</executable>
<expect></expect> <!-- empty expect section -->
<timeout_allowed>no</timeout_allowed>
```
It leads to the `srcip` field not being correctly passed to the script. I could recreate this using your configuration setting in my lab environment:

```
#Alert regarding the OpenVPN event.
** Alert 1578580607.157798: - openvpn,authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 09 15:36:47 server->/var/log/syslog
Rule: 81801 (level 3) -> 'OpenVPN: User logged in'
Src IP: 1.1.1.1
Src Port: 57434
Jan  9 11:28:07 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434

#Alert regarding the active-response triggered by the OpenVPN event. (empty srcip)
** Alert 1578580607.158195: - ossec,active_response,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SI.4,
2020 Jan 09 15:36:47 nanoPill->/var/ossec/logs/active-responses.log
Rule: 607 (level 3) -> 'Active response: test_command.sh - add'
Src IP: -
jue ene  9 15:36:47 CET 2020 /var/ossec/active-response/bin/test_command.sh add - - 1578580607.157401 81801 /var/log/syslog - -
script: test_command.sh
type: add

#Output in active-response.log without srcip
jue ene  9 15:36:47 CET 2020 /var/ossec/active-response/bin/test_command.sh add - - 1578580607.157401 81801 /var/log/syslog - -
```

- However, using `<expect>srcip</expect>` inside the command section does the trick:


```XML
  <command>
    <name>test_command</name>
    <executable>test_command.sh</executable>
    <expect>srcip</expect>
    <timeout_allowed>no</timeout_allowed>
  </command>
``` 
Triggering again the active-response, now containing `<expect>srcip</expect>`:

```
#Alert regarding the OpenVPN event.
** Alert 1578580738.162600: - openvpn,authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 09 15:38:58 server->/var/log/syslog
Rule: 81801 (level 3) -> 'OpenVPN: User logged in'
Src IP: 1.1.1.1
Src Port: 57434
Jan  9 11:28:07 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434

#Alert regarding the active-response triggered by the OpenVPN event. (filled srcip)
** Alert 1578580738.162997: - ossec,active_response,pci_dss_11.4,gdpr_IV_35.7.d,nist_800_53_SI.4,
2020 Jan 09 15:38:58 nanoPill->/var/ossec/logs/active-responses.log
Rule: 607 (level 3) -> 'Active response: test_command.sh - add'
Src IP: 1.1.1.1
jue ene  9 15:38:58 CET 2020 /var/ossec/active-response/bin/test_command.sh add - 1.1.1.1 1578580738.162600 81801 /var/log/syslog - -
script: test_command.sh
type: add

#Output in active-response.log with srcip
jue ene  9 15:38:58 CET 2020 /var/ossec/active-response/bin/test_command.sh add - 1.1.1.1 1578580738.162600 81801 /var/log/syslog - -
```

Filling the `<expect> `field should solve your problem. I also want you to know that the expect section only supports the fields `user`, `srcip` and `filename`. We are working to enhance the module so any field could be passed to an active-response script.

Let me know how it goes. Greetings, 
JP Sáez

**Comment by marinovgit** [comment]
Hello, thank you for your detailed explanation. Unfortunately, I am aware that there is no srcip in the expect. I removed it because if it is there the script is not executed at all.

**Without:**
Alert:
```
** Alert 1578585592.174094: mail  - openvpn,authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 09 15:59:52 server ->/var/log/openvpn.log
Rule: 81801 (level 10) -> 'OpenVPN: User logged in'
Src IP: 1.1.1.1
Src Port: 57434
Jan  9 15:59:51 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434
```
Main log: (mention this because I saw that this pop up when something in the active-response dir is executed)
```
2020/01/09 15:59:28 ossec-execd: INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
```
active-response log:
```
add - - 1578585592.173689 81801 /var/log/openvpn.log - -
```
active-response and command:
```
       <command>openvpn</command>
        <location>local</location>
        <rules_id>81801</rules_id>
   
     <name>openvpn</name>
        <executable>openvpn.sh</executable>
        <expect></expect>
        <timeout_allowed>no</timeout_allowed>
```
openvpn.sh 
```
#!/bin/sh 
echo $@ >> /var/ossec/logs/active-responses.log
```
**With:**
Only add srcip in the expect.
systemctl restart wazuh-manager

Alert:
```
** Alert 1578586207.193876: mail  - openvpn,authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,
2020 Jan 09 16:10:07 server->/var/log/openvpn.log
Rule: 81801 (level 10) -> 'OpenVPN: User logged in'
Src IP: 1.1.1.1
Src Port: 57434
Jan  9 16:10:05 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434
```

Nothing in the /var/ossec/logs/active-responses.log

This line **does not** show in the main log:
```
2020/01/09 15:59:28 ossec-execd: INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
```
Logtest:
```
/var/ossec/bin/ossec-logtest 
2020/01/09 16:13:03 ossec-testrule: INFO: Started (pid: 18246).
ossec-testrule: Type one log per line.
Jan  9 16:10:05 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434

**Phase 1: Completed pre-decoding.
       full event: 'Jan  9 16:10:05 server openvpn: 1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434'
       timestamp: 'Jan  9 16:10:05'
       hostname: server'
       program_name: 'openvpn'
       log: '1.1.1.1:57434 [user] Peer Connection Initiated with [AF_INET]2.2.2.2:57434'

**Phase 2: Completed decoding.
       decoder: 'openvpn'
       srcip: '1.1.1.1'
       srcport: '57434'
       srcuser: 'user'

**Phase 3: Completed filtering (rules).
       Rule id: '81801'
       Level: '10'
       Description: 'OpenVPN: User logged in'
**Alert to be generated.
```

Best regards

**Comment by Zenidd** [comment]
Hello again @marinovgit,


> Main log: (mention this because I saw that this pop up when something in the active-response dir is executed) `2020/01/09 15:59:28 ossec-execd: INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.` 

Due to the duality (linux-windows support) of the active response scripts, running the module in Linux systems usually leads to messages about not using the complementary windows script version. We plan to get this messages under debug verbosity. I think there is nothing to worry about here, anyway thanks for the detailed explanation.

About the arguments being not passed, I could not recreate your environment:

- I'm able to see the new entry in the active-response log whenever I place the `srcip` or not in the `<expect>` option.
-  Also, when I place the `srcip` I'm also able to see the `srcip` in the active response script.

I'm afraid I need some more clues to figure out what is happening here:
- Where is your `openvpn.sh` script located? Manager side or both agent and manager?
- Could you please paste here the full `ossec.conf` file content?
- Could you also paste the output for `# ll /var/ossec/active-response/bin` (if you have the script in both sides, please paste the both sides output) ? I think the `owner:group` or permissions could be messing here.

_*Feel free to obfuscate any sensitive data_

I think the issue could be in the file permissions, `owner:group` pair or in looking for the active-response.log on the wrong side. Anyway let's wait for your reply so we can keep analyzing what is happening. Thanks for your patience @marinovgit.



Best regards, JP Sáez

**Comment by marinovgit** [comment]
Hello, sorry for the delay. I figure it out.
The IP from which I made the test is in <white_list>.
If you have nothing in <expect> the active response is executed. 
If srcip is in <expect> the script is not executed at all.

From the documentation: "This designates IP addresses that should never be blocked with an active response ... "
In my case, the active response is just a custom notification script not ban or smth, so I need to be executed. How can I do this?

Best regards

**Comment by Zenidd** [comment]
Hello again @marinovgit, 

Your last insights are right: events containing an IP under a `<white_list>` section can't trigger any active response scripts. As you said, it occurs although the script _isn't related to IP banning or dropping actions._

Wazuh  `<white_list>` documentation:

> This designates IP addresses that should never be blocked with an active response and, though only one IP address can be included in this section, you may repeat this as many times as needed to include additional IP addresses.

This feature guarantees that the Wazuh manager will not be wrongly isolated by an active-response script. I think this behavior shall be preserved at least until we introduce new features to the module active-response.

We discussed today a new active-response option to specify stanzas that should ignore the IP whitelist. i.e:

```XML
<!-- whitelist ignoring thorugh a new active-response attribute -->
<active-response ignore_whitelist="yes">
        <command>openvpn</command>
        <location>local</location>
        <rules_id>81801</rules_id>
</active-response>


<!-- whitelist ignoring thorugh a new active-response option -->
<active-response>
        <command>openvpn</command>
        <location>local</location>
        <rules_id>81801</rules_id>
       <ignore_whitelist/>
</active-response>
```

In the meanwhile, the workaround is disabling the whitelist for the IP that should be passed to active-response scripts. I want to point out that it could lead to the Wazuh manager banning its own address.

I hope it helps. Let me know if you have any further questions.

Greetings, JP Sáez

**Comment by Zenidd** [comment]
Hello again @marinovgit,


I just created a pull request replacing the `<white_list>` description with a clearer one:

`This specifies an IP for which Active Responses will not be triggered. Only one IP may be specified for each <while_list> tag, but several IPs may be used by including multiple <white_list> tags.`

Best regards, JP Sáez

**Comment by marinovgit** [comment]
Hello, this will be great " active-response ignore_whitelist="yes" "
Yes, this is a much better explanation.

Thank you

**Comment by vikman90** [comment]
Hi,

Let me close this issue as I see its related PR is merged.

Best regards.
