### ISSUE TITLE
[Development] File descriptor leak in Linux rootcheck module

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#4473]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.2-31118 | rootcheck | Manager/Agent | Packages | Ubuntu 18.04/CentOS 7 |

Hi team, 

While performing some stress test to the pre-release packages we found some issues related to `ossec-syscheck` daemon, more specifically with `rootcheck` module. It seems that there's a file descriptor leak in this module, which, eventually it will have more than 1K opened file descriptors.

Here you can see some graphics that show this behavior with all the components enabled:
- Ubuntu agent:
![image](https://user-images.githubusercontent.com/9081114/72716836-341fd280-3b73-11ea-800f-5f127dae7f62.png)
![image](https://user-images.githubusercontent.com/9081114/72717178-db046e80-3b73-11ea-8c66-9f0e60d1a1ba.png)
- CentOS agent:
![image](https://user-images.githubusercontent.com/9081114/72717104-b7d9bf00-3b73-11ea-9529-760bc1928e16.png)
![image](https://user-images.githubusercontent.com/9081114/72716859-40a42b00-3b73-11ea-8d4e-4f945ca156eb.png)

We also ran a test where `rootcheck` was the only module enabled, and the same behavior appeared in the tests:
- Ubuntu agent:
![image](https://user-images.githubusercontent.com/9081114/72717373-2f0f5300-3b74-11ea-9930-e4a231581659.png)
![image](https://user-images.githubusercontent.com/9081114/72717376-3171ad00-3b74-11ea-9474-8afcdc5bc3bc.png)
- CentOS agent:
![image](https://user-images.githubusercontent.com/9081114/72717363-29197200-3b74-11ea-978b-b770a10ea497.png)
![image](https://user-images.githubusercontent.com/9081114/72717365-2a4a9f00-3b74-11ea-8cc9-3d6a590db3f5.png)

**Comment by vikman90** [comment]
This issue is a regression produced by PR #4415.

**Comment by vikman90** [comment]
Fixed.
@BraulioV @wazuh/cicd thank you very much for catching this bug!
