### ISSUE TITLE
Database migration issue.

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh#4482]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.11.1 | Manager | Packages | CentOS 7 |

Hello team,

I've faced the following issue when I've tried to migrate the DB from a Wazuh manager to another one.
The process I followed was:

1. I stopped both Wazuh manager and API.
2. I copied the folders `/var/ossec/var/db` and `/var/ossec/queue` to the new instance.
3. I started the Manager and API again

After that, I am not able to access to the Wazuh API from Kibana:
![image](https://user-images.githubusercontent.com/47329460/72733995-414fb800-3b99-11ea-97bd-204c6e4022b5.png)
And some daemons are not running anymore:
```
[root@centOS7-14 ossec]# ps -aux | grep ossec
ossec    14948  0.2  0.8 925144 32900 ?        Ssl  14:11   0:00 /bin/node /var/ossec/api/app.js
root     15751  0.0  0.0 112544  3460 ?        Sl   14:13   0:00 /var/ossec/bin/ossec-authd
root     15777  0.0  0.0  30488  1436 ?        Sl   14:13   0:00 /var/ossec/bin/ossec-execd
root     15817  0.1  0.1 565224  6632 ?        Sl   14:13   0:00 /var/ossec/bin/wazuh-modulesd
root     16050  0.0  0.0  10664   692 pts/0    R+   14:15   0:00 grep --color=auto ossec
```
Is this the expected behavior? Is there a wat to migrate the DB?

**Comment by MiguelCasaresRobles** [comment]
Hi team,

Sorry. This is an Invalid issue. 

Regards,
