### ISSUE TITLE
FIM v2 [dev]: Agent DB won't synchronize

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#4495]
|Wazuh version|Component|Install type|
|---|---|---|
| 3319-fim-rework | syscheck | Agent |

### Bug description

The agent's database won't ever synchronize in FIM rework.
The following error is shown every time a synchronization message arrives to `ossec-agentd`:
```
2020/01/23 12:22:41 ossec-agentd: ERROR: dbsync: cannot connect to syscheck: No such file or directory (2)
```
The message that triggers this error is:
```
2020/01/23 12:22:41 ossec-agentd: INFO: ~~~~~~~ MESSAGE: dbsync no_data {"id":1579782161,"begin":"/bin/bash","end":"/usr/sbin/zic"}
```

It may seem as if the socket file doesn't exist, but it does:
```
  File: '/var/ossec/queue/ossec/syscheck'
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 801h/2049d	Inode: 55253       Links: 1
Access: (0660/srw-rw----)  Uid: (    0/    root)   Gid: (  999/   ossec)
Access: 2020-01-23 13:29:36.988000000 +0000
Modify: 2020-01-23 13:29:36.988000000 +0000
Change: 2020-01-23 13:29:36.988000000 +0000
 Birth: -
```

### Configuration

The configuration is the same as default except for `<frequency>` field in `<syscheck>` which is set to `5`. Also, the following components are disabled: `rootcheck`, `sca` and `syscollector`.

**Comment by jesusjimsa** [comment]
I have found that going back to this commit: 9f76af51a72981b190c1226cfaa6c22051ebbd6f, the connection to the socket works as expected. Looking trough the code, we have found that the path to the socket is not the correct one.

**Comment by jesusjimsa** [comment]
The path passed to `OS_ConnectUnixDomain` inside the `ag_send_syscheck` function, wasn't complete.
https://github.com/wazuh/wazuh/blob/87ad1cee52b91b44f4f35140d6c643b3d77a6f78/src/shared/syscheck_op.c#L573
Adding `DEFAULTDIR` fixes this issue.
