### ISSUE TITLE
Implement SQLite database in FIM module

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#4500]
|Related issue|
|---|
|#4347|

|Working branch|
|---|
|[3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)|

Integrate the functionality developed in issue [4499](https://github.com/wazuh/wazuh/issues/4499) into the FIM module.

### create_db.c

- [x] Delete Files
`void fim_checker(char *path, fim_element *item, whodata_evt *w_evt, int report)`
To be replace using:
`void fim_db_remove_path(fdb_t *fim_sql, fim_entry *entry, void *arg)`

- [x] Check, insert and update files
`int fim_file (char *file, fim_element *item, whodata_evt *w_evt, int report)`
We need to implement a method to obtain the DB entry, check the changes and modify or insert an entry using:
`fim_entry *fim_db_get_path(fdb_t *fim_sql, const char *file_path)`
`int fim_db_insert_data(fdb_t *fim_sql, const char *file_path, fim_entry_data *entry)`

- [x] Check, insert and update files for registries
`int fim_registry_event (char * key, fim_entry_data * data, int pos)`
We need to implement a method to obtain the DB entry, check the changes and modify or insert an entry using:
`fim_entry *fim_db_get_path(fdb_t *fim_sql, const char *file_path)`
`int fim_db_insert_data(fdb_t *fim_sql, const char *file_path, fim_entry_data *entry)`

- [x] Processing realtime and whodata events
`void fim_realtime_event(char *file)`
`void fim_whodata_event(whodata_evt * w_evt)`
`void fim_audit_inode_event(char *file, const char *inode_key, fim_event_mode mode, whodata_evt * w_evt)`
They must be unified to get all hardlinks pointing to the same inode, get the changes and get an alert for each of them:
`char **fim_db_get_paths_from_inode(fdb_t *fim_sql, const unsigned long int inode, const unsigned long int dev)`

- [x] Deleting files in scheduled scans
`void check_deleted_files()`
The operation of deleting unscanned files is replaced by:
`int fim_db_delete_not_scanned(fdb_t * fim_sql)`
Note that we must show an alert for each deleted file, which forces a message to be sent. We need to think about whether to do this within the function that manages the SQLite database or to find a way to do it outside.

- [x] Replace the following functions with: fim_db_insert_data(fdb_t *fim_sql, const char *file_path, fim_entry_data *entry)
`int fim_insert(char *file, fim_entry_data *data, __attribute__((unused))struct stat *file_stat)`
`int fim_update(char *file, fim_entry_data *data, __attribute__((unused)) fim_entry_data *old_data)`
`int fim_update_inode(char *file, char inode_key[])`

- [x] Replace the following functions with: fim_db_remove_path(fdb_t *fim_sql, fim_entry *entry, void *arg)
`void fim_delete (char * file_name)`
`void delete_inode_item(char *inode_key, char *file_name)`

### fim_sync.c

- [x] Sending of synchronization events
`void fim_sync_send_list(const char * start, const char * top)`
Replace by:
`int fim_db_sync_path_range(fdb_t *fim_sql, char *start, char *top)`

- [x] Generate integrity checksum
`void fim_sync_checksum()`
Using:
`int fim_db_get_row_path(fdb_t * fim_sql, int mode, char **path)`
`int fim_db_get_data_checksum(fdb_t *fim_sql, void * arg)`

### run_check.c

- [x] Deletion of entries that are monitored by a symbolic link.
`static void fim_link_delete_range(int pos)`
Implement with the next call, it remains to be evaluated whether to send the delete message inside or outside the SQLite function:
`int fim_db_delete_range(fdb_t * fim_sql, char *start, char *top)`

**Comment by 0xN3utr0n** [comment]
### SQLite3 in-memory database 

- [ ] Add option in wazuh configuration to choose whether we want the db to be stored in memory or in disk. `<database>memory|disk</database>`

- [ ] Modify or add a `wdb_create_file()` compatible with this feature.

**Comment by 0xN3utr0n** [comment]
### Update 1
After successfully compiling syscheckd, we ran it for the first time and tested out basic functionalities such as `update`, `delete` and `insert`. All of them worked, however a few issues were found:

- A database commit only happened after trying it twice per modification.
- An odd and sneaky segfault happened near a `sleep()` call. Hard to find since it only appeared once, so our guess is it's due to a race condition or something alike.

**Comment by DaveVG1** [comment]
- Fixed a segmentation fault (https://github.com/wazuh/wazuh/commit/30bcf76d5699f0bf39b02df2d51f8690bcb1a43c) while adding a file in a monitored folder in realtime.
- Fixed an invalid read in `fim_db_data_checksum_range` (https://github.com/wazuh/wazuh/commit/e00bdaef7a8c0b9b8f1996ddb74eebd0083384f2)

**Comment by DaveVG1** [comment]
- Fixed a memory leak while processing realtime/whodata events (https://github.com/wazuh/wazuh/commit/2a95a75a8f4c58f785245734857af84ca039291b)

**Comment by 0xN3utr0n** [comment]
- Fixed segmentation fault ([e00bdae](https://github.com/wazuh/wazuh/commit/bc0982b645c734f4a715e27487d9ca567c148a53)) while deleting a malformed cJSON in `fim_sync_checksum_split`.

**Comment by DaveVG1** [comment]
- Added the delete unscanned behavior and fixed an error that happened while synchronizing an empty database (https://github.com/wazuh/wazuh/commit/db587c47decf88d33e669b6e89093b4c0edb1b14).

**Comment by bah07** [comment]
Done!
