### ISSUE TITLE
SQLite CMoka tests

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#4501]
|Related issue|
|---|
|#4347|

|Working branch|
|---|
|[3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)|

We need to develop CMoka tests for the following functions used in fim-rework-sqlite:

### fim_db.c

- [x] `fdb_t *fim_db_init(int memory);`
- [x] `void fim_db_close(fdb_t *fim_sql);`
- [x] `int fim_db_set_all_unscanned(fdb_t *fim_sql);`
- [x] `int fim_db_clean(void);`
- [x] `int fim_db_cache(fdb_t *fim_sql);`
- [x] `int fim_db_finalize_stmt(fdb_t *fim_sql);`
- [x] `void fim_db_check_transaction(fdb_t *fim_sql);`
- [x] `void fim_db_force_commit(fdb_t *fim_sql);`
- [x] `int fim_db_clean_stmt(fdb_t *fim_sql, int index);`
- [x] `int fim_db_get_data_checksum(fdb_t *fim_sql, void * arg);`
- [x] `int fim_db_sync_path_range(fdb_t *fim_sql, char *start, char *top);`
- [x] `fim_entry *fim_db_get_path(fdb_t *fim_sql, const char *file_path);`
- [x] `int fim_db_get_inode(fdb_t *fim_sql, const unsigned long int inode, const unsigned long int dev);`
- [x] `char **fim_db_get_paths_from_inode(fdb_t *fim_sql, const unsigned long int inode, const unsigned long int dev);`
- [x] `int fim_db_insert_data(fdb_t *fim_sql, const char *file_path, fim_entry_data *entry);`
- [x] `int fim_db_insert_path(fdb_t *fim_sql, const char *file_path, fim_entry_data *entry);`
- [x] `void fim_db_callback_sync_path_range(__attribute__((unused)) fdb_t *fim_sql,`
- [ ] `void fim_db_callback_calculate_checksum(__attribute__((unused)) fdb_t *fim_sql,`
- [x] `int fim_db_data_checksum_range(fdb_t *fim_sql, const char *start, const char *top,`
- [x] `int fim_db_get_count_range(fdb_t *fim_sql, char *start, char *top, int *counter);`
- [x] `void fim_db_remove_path(fdb_t *fim_sql, fim_entry *entry, void *arg);`
- [x] `int fim_db_delete_not_scanned(fdb_t * fim_sql);`
- [x] `int fim_db_delete_range(fdb_t * fim_sql, char *start, char *top);`
- [x] `int fim_db_get_row_path(fdb_t *fim_sql, int mode, char **path);`

**Comment by chemamartinez** [comment]
Merged #4688.

Awesome job @TomasTurina @nicolaspapp @Molter73!
