### ISSUE TITLE
Who-data monitoring not working on branch 3319-fim-rework

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#4507]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.12.0| Syscheck | Manager/Agent | Sources | CentOS Linux 7 |

Hello team, I have found a recent error on whodata monitoring when in **branch 3319-fim-rework**. Deeper information:

## Description

While developing a test for the issue [398](https://github.com/wazuh/wazuh-qa/issues/398) I found this strange behavior:

When monitoring a directory (for example, /testdir1) whodata monitoring generates events in the ossec.log file a few times after creating files inside. Then it stops displaying events and also does not show any errors. It does not work again until restarting the wazuh-manager service. Once restarted, it repeats the same pattern. It raises a few events when creating / modifying / deleting files within that directory, and then stops working again without showing any errors. In the audit log, alerts **do** appear.

This behavior does not occur in realtime mode. I am using the Wazuh branch 3319-fim-rework.

## Expected behavior

The expected behavior is that it generates events in the ossec.log file after each new creation / modification / deletion of files in a monitored directory, as in realtime.

## How to reproduce the error

- Create the directory `/testdir1`.
- Add this line inside `<syscheck>` in ossec.conf file:
`<directories check_all="yes"  whodata="yes">/testdir1</directories>`
- Restart wazuh
- Create / modify / delete any file inside /testdir1 while watching `/var/ossec/logs/ossec.log`.

In my case, it generates the events corresponding to the first two archives that I create. Then it stops working.

Kind regards,
José Luis.

**Comment by bah07** [comment]
Thanks for the report, it's fixed in [1a86d6b](https://github.com/wazuh/wazuh/commit/1a86d6b3f6c881428d56fd711fd29481500a888c)
