### ISSUE TITLE
Empty <directories></directories> tag in ossec.conf not working (3319-fim-rework)

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#4517]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.12.0| Syscheck | Manager/Agent | Sources | CentOS Linux 7 |

Hello team, I found another unexpected behavior when content is not set within the directories tag. Im in **branch 3319-fim-rework**. Deeper information:

## Description

According to the expected behavior, when we add no directory to be monitored in `/var/ossec/etc/ossec.conf` as shown here:
```XML
<directories realtime="yes"></directories>
```
and we restart Wazuh, a log should appear in `ossec.log`, not an error. There should be no problems in the restart.

However, currently when we try to restart Wazuh, a message like this appears in ossec.log:
`2020/02/14 00:08:19 ossec-syscheckd[5145] syscheck-config.c:767 at read_attr(): DEBUG: Could not check the real path of '' due to [(2)-(No such file or directory)].`

Besides that wazuh does not start again:
[root@wazuh-master test_wazuh]# systemctl status wazuh-manager.service
```
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2020-02-14 00:08:19 UTC; 13min ago
  Process: 4941 ExecStop=/usr/bin/env ${DIRECTORY}/bin/ossec-control stop (code=exited, status=0/SUCCESS)
  Process: 5123 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=1/FAILURE)

Feb 14 00:08:19 wazuh-master env[5123]: File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.12.0-py3.7.egg/wazuh/cluster/cluster.py", line 97, in read_config
Feb 14 00:08:19 wazuh-master env[5123]: return read_cluster_config(config_file=common.ossec_conf)
Feb 14 00:08:19 wazuh-master env[5123]: File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.12.0-py3.7.egg/wazuh/cluster/utils.py", line 48, in read_cluster_config
Feb 14 00:08:19 wazuh-master env[5123]: raise WazuhException(3006, e.message)
Feb 14 00:08:19 wazuh-master env[5123]: wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Requested component does not exist: 'NoneType' object has no attribute 'split'
Feb 14 00:08:19 wazuh-master env[5123]: wazuh-clusterd: Configuration error. Exiting
Feb 14 00:08:19 wazuh-master systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
Feb 14 00:08:19 wazuh-master systemd[1]: Failed to start Wazuh manager.
Feb 14 00:08:19 wazuh-master systemd[1]: Unit wazuh-manager.service entered failed state.
Feb 14 00:08:19 wazuh-master systemd[1]: wazuh-manager.service failed.
```

## Expected behavior

After adding the <directories> tags without any directory and restarting Wazuh, a log informing should appear, not an error. 

## How to reproduce the error

- Add this line inside `<syscheck>` in ossec.conf file:
`<directories realtime="yes"></directories>`
- Restart Wazuh
- Wazuh has not started and an error appears in ossec.log.

Kind regards,
José Luis.

**Comment by Selutario** [comment]
Hello team,

After searching a bit, I discovered that the error is possibly being caused in this line:
https://github.com/wazuh/wazuh/blob/006792ea3261fdd99cef0e0cb213fd306d917aef/framework/wazuh/configuration.py#L180

When the <directories> tag of ossec.conf does not contain any string, it is not possible to use the split () method and this is what causes error 3006.
```
Feb 14 00:08:19 wazuh-master env[5123]: wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Requested component does not exist: 'NoneType' object has no attribute 'split'
````

Kind regards,
José Luis.

**Comment by JcabreraC** [comment]
# Update
Found new related error. If we have an invalid directory/file, we jump to the next line of the configuration 

``` xml
<directories check_all="yes" realtime="yes">/home/user/TestFim/NULL*, /home, /TestFim</directories>
```

With `/home/user/TestFim/NULL*` invalid, we don't monitor the `/home` or `/TestFim` directories either. 

We should take the following directory/file from the configuration line.

**Comment by JcabreraC** [comment]
# Update

Found new related error. When an attribute or value in the <directories> field is incorrect, an error message is shown and Wazuh is stopped. 

With the following configuration:
Ossec.conf
``` xml
<directories check_all="invalid" realtime="yes">/home/user/TestFim/NULL*, /home, /TestFim</directories>
```

Output ossec.log:
```
2020/01/30 12:24:08 ossec-syscheckd: ERROR: (6680): Invalid option 'invalid' for attribute 'check_all'
2020/01/30 12:24:08 ossec-syscheckd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
2020/01/30 12:24:08 ossec-syscheckd: CRITICAL: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
ossec-syscheckd: Configuration error. Exiting
``` 
We should show a warning message and continue reading the configuration
