### ISSUE TITLE
Wazuh dashboard show that wazuh agent 001 is disconnected but it still receive alert.

### ISSUE THREAD

**Issue by nizarakbarm** [wazuh/wazuh#452]
![1521184876_1421_16032018_1365x293](https://user-images.githubusercontent.com/12729998/37508439-9f81ac36-2925-11e8-81fd-0419a037ac80.png)
![1521184979_1422_16032018_1344x728](https://user-images.githubusercontent.com/12729998/37508444-a9a24e3c-2925-11e8-9495-40bfe8dc31c1.png)
In ossec.log, it says that wazuh manager or server is unavailable. But the server give response again. In dashboard discover with index wazuh-monitoring it says my agent disconnected from 09:50:00.618.
![1521184906_1421_16032018_1166x608](https://user-images.githubusercontent.com/12729998/37508532-0ef00090-2926-11e8-9e94-025ff9fc1172.png)
But then it still receive alert when i am sudoing in my ssh.
![1521185261_1427_16032018_1365x699](https://user-images.githubusercontent.com/12729998/37508568-3d55e468-2926-11e8-9d57-a3a4770b1924.png)
And it is happening when vurnerability-detector trying to update it's database but i am still not sure if it is related or not. Thanks

**Comment by mgmacias95** [comment]
Hello @nizarakbarm,

The agent status is calculated based on its last keep alive. This last keep alive is stored as the modification date of the file `/var/ossec/queue/agent-info/kominfo-90.5-192.168.90.5`. I see the API reports this last keep alive as `2018-03-16 09:09:48`, could you confirm this is correct? Use the following command to check it:

`# stat /var/ossec/queue/agent-info/kominfo-90.5-192.168.90.5`

Best regards,
Marta

**Comment by nizarakbarm** [comment]
Oh sorry, i am already restarting my wazuh manager and agent so it last keep alive status already change too. I will try to see it again when my problem happening in the next day because it is always happening in that time everyday when vurnerability-detector updating. And i will find some way too to recreate this problem manually. Thanks, I will send my response again in the next time when i am having this problem.

**Comment by JPLachance** [comment]
Hello,

I recently deployed Wazuh 3.6.1 and I have the same issue.

When I connect to my master manager and call `/var/ossec/bin/cluster_control`, I get:
``` 
root@wazuh-manager-master-0:/# /var/ossec/bin/cluster_control -a -d
DEBUG: [Transport-InternalSocketSend] Starting: /var/ossec//queue/cluster/c-internal.sock.
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_agents all%--%all%--%0%--%500'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'ok'.
DEBUG: [Transport-InternalSocketSend] Closing socket.
DEBUG: [Transport-InternalSocketSend] Socket closed.
  ID: 000, Name: wazuh-manager-master-0, IP: 127.0.0.1, Status: Active,  Node: wazuh-manager-master
  ID: 001, Name: ip-10-6-16-202, IP: any, Status: Disconnected,  Node: wazuh-manager-worker-1
DEBUG: [Transport-InternalSocketSend] Starting: /var/ossec//queue/cluster/c-internal.sock.
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_agents all%--%all%--%500%--%500'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'ok'.
DEBUG: [Transport-InternalSocketSend] Closing socket.
DEBUG: [Transport-InternalSocketSend] Socket closed.

Listing 2 agent(s).
```

But, when I call `/var/ossec/bin/agent_control`, I get:
```
root@wazuh-manager-master-0:/# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh-manager-master-0 (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: ip-10-6-16-202, IP: any, Active

List of agentless devices:

```

I think cluster_control fails to list agents while agent_control succeeds.

How can I get the right status back? 😃

**Comment by JPLachance** [comment]
Hello!

After investigating with @mgmacias95, `wazuh-modulesd` was not running anymore and we were not able to identify why.

A simple `/var/ossec/bin/wazuh-modulesd -d` to relaunch the service fixed my agent status issue.

I started `wazuh-modulesd` in debug mode and I hope I will have more informations for you if ever it stops again :)

**Comment by juergenc** [comment]
Hello @JPLachance,

the `wazuh-modulesd` daemon process crashes due to segfaults, see #1529  and #1332. It should be fixed in release _3.7.0_.
