### ISSUE TITLE
Create 'queue/fim/db' folder in agent's installation

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh#4525]
|Wazuh version|Component|Install type|
|---|---|---|
| [3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite) | Syscheck | Agent |

In order to accomplish the SQLite development for the FIM rework the agent's installation should create a folder in `INSTALLATION_FOLDER/queue`.

This folder is already present in the manager, but it will also be necessary for the agent (as it's going to have the database in that folder).

This folder must be deleted while uninstalling. Both UNIX and Windows (MSI and NSI) installers must be changed.

**Comment by jesusjimsa** [comment]
I have modified the installation file (`ins-functions.sh`) and `fim_db.c` to create the folder and the `fim.db` file.
