### ISSUE TITLE
Alerting based on agent group - feature request

### ISSUE THREAD

**Issue by Nithinbs18** [wazuh/wazuh#4526]
Dear team,

As there are multiple ways to create alert based on rule-group, ID, location etc is there any way that I could trigger email alert to different email address based on the agent-group it belongs to?

regards,
Nithin

**Comment by Zenidd** [comment]
Hello @Nithinbs18,

Wazuh allows [granular configuration](https://documentation.wazuh.com/3.1/user-manual/manager/manual-email-report/index.html#granular-email-options) options for email alerts. Email alerts can be configured to send an email based on one or more rule groups:

```XML
<email_alerts>
  <email_to>mail1@example.com</email_to>
  <email_to>mail2@example.com</email_to>
  <email_to>mail3@example.com</email_to>
  <group>syscheck</group>
</email_alerts>
```
Any rule group is allowed on `<group>`. Multiple groups should be separated with a pipe character `|`. You could also mix it with other granular email filters as  `<level>`:
```XML
<email_alerts>
  <email_to>mail1@example.com</email_to>
  <email_to>mail2@example.com</email_to>
  <email_to>mail3@example.com</email_to>
  <group>syscheck</group>
   <level>10</level>
</email_alerts>
```
I also suggest you reading our [How to send email notifications](https://wazuh.com/blog/how-to-send-email-notifications-with-wazuh/) with Wazuh blogpost. It covers an use case where granular email configuration is applied. 

I hope it helps. Let me know how it goes.
Greetings, JP Sáez

**Comment by Nithinbs18** [comment]
Hi @Zenidd 

Thanks for you response.
I am aware of email alerts with respect to rule group, but I want to know if there is an option to alert on agent_group ( https://documentation.wazuh.com/3.8/user-manual/agents/grouping-agents.html ).
Do you have any idea on this?

Regards,
Nithin

**Comment by Zenidd** [comment]
Hello @Nithinbs18,

> I am aware of email alerts with respect to rule group, but I want to know if there is an option to alert on agent_group ( https://documentation.wazuh.com/3.8/user-manual/agents/grouping-agents.html ).
> Do you have any idea on this?

Thanks for undoing the misunderstanding!

Currently, it is not possible as the agent groups are intended just for central configuration spreading. In other words, the rule engine has no awareness of agent groups.

 I think that it could be an extended feature for the email alerts `<event_location>` option. In the following block there is an example syntax for this new feature  (I would like to read your opinion about) :

```XML
<email_alerts>
  <email_to>mail1@example.com</email_to>
  <email_to>mail2@example.com</email_to>
  <email_to>mail3@example.com</email_to>
  <event_location type="group">windows_agents</event_location>
</email_alerts>
```

Let's keep this issue for the feature request.

Best regards, JP Sáez

**Comment by Nithinbs18** [comment]
Hi @Zenidd 

I will work on this and let you the results asap.
Thank you very much.

Regards,
Nihtin

**Comment by Nithinbs18** [comment]
Hi @Zenidd 

It does not work as expected, I guess we have to keep this as a feature request.

Regards,
Nithin

**Comment by Zenidd** [comment]
Hello again @Nithinbs18,

Sorry if I was not clear, the block above was a syntax example for the future feature. 

Thanks for the patience. Best regards,

JP Sáez

**Comment by nebriv** [comment]
Hey There - 

I would also be **very** interested in this feature as well. Happy to test as needed. That syntax would work fine for us, I think it'd offer a decent amount of flexibility with basic regex, etc.

Thanks,
Ben

**Comment by ozguruygarbayar** [comment]
We would also be very interested in this feature as well. It's very easy to configure for group alerts.

**Comment by vP3nguin** [comment]
+1

**Comment by kmfreder1** [comment]
+1

**Comment by titleistfour** [comment]
+1, this would be awesome to have

**Comment by proteus88** [comment]
+1

**Comment by vikman90** [comment]
@Nithinbs18 This feature will be supported in the new Engine: https://github.com/wazuh/wazuh/issues/11334.

Let me close this issue.

Best regards.
