### ISSUE TITLE
error processing package wazuh-api 

### ISSUE THREAD

**Issue by itcrowdsource** [wazuh/wazuh#453]
I am having troubles installing the wazuh-api. I am able to install the wazuh-manager but the next step with the wazuh-api consistently fails. I was able to install a previous version of the wazuh-api succesfully. But the latest version seems to have installer problems.

My apt term.log
Setting up wazuh-api (3.2.1-1) ...
==============================================================================================================
= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh =
==============================================================================================================
dpkg: error processing package wazuh-api (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-api

My apt history.log
Commandline: apt-get install wazuh-api
Requested-By: ubuntu (1000)
Error: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by itcrowdsource** [comment]
I able to instal v3.1.0-1 without problems, only the newer versions cannot be installed.

**Comment by itcrowdsource** [comment]
The latest GIT version seems to work properly, so I guess it is only related to the DEB package

**Comment by itcrowdsource** [comment]
Hi Braulio,

I am using systemd.

These are the details of the system:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Linux sec 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**APT version**: 1.2.25

**Comment by PSanchezR** [comment]
Hello @itcrowdsource,

What method did you use to delete version 3.1.0-1 prior to installing the new version?

In some cases not all Wazuh files have been deleted and this has caused failures in the installations, you can confirm that after the uninstall process all the following files have been removed:

- Complete folder /var/ossec
- /etc/ossec-init.conf
- /etc/rc0.d/K01wazuh-manager
- /etc/rc0.d/K01wazuh-api
- /etc/rc1.d/K01wazuh-manager
- /etc/rc1.d/K01wazuh-api
- /etc/rc2.d/S02wazuh-api
- /etc/rc2.d/S02wazuh-manager
- /etc/rc3.d/S02wazuh-api
- /etc/rc3.d/S02wazuh-manager
- /etc/rc4.d/S02wazuh-api
- /etc/rc4.d/S02wazuh-manager
- /etc/rc5.d/S02wazuh-api
- /etc/rc5.d/S02wazuh-manager
- /etc/rc6.d/K01wazuh-manager
- /etc/rc6.d/K01wazuh-api 

You can make sure everything is removed by running:

```
apt-get purge wazuh-manager
apt-get autoremove
rm -rf /var/ossec
rm -f /etc/ossec-init.conf
rm -f `find /etc/rc* | grep wazuh`
```
After this try installing with:

` apt-get install wazuh-api `

This should install the latest version of wazuh-api and wazuh-manager without problems.

Thank you for contribution.

**Comment by jeremylarose** [comment]
This happens every time I update versions.  What's the proper way to update?  I first stop all of the services and then install the updates over the top of the current version....  wazuh-api .deb always has issues.  wazuh-manager and elk update fine, but wazuh-api errors out whether using apt-get repository or dpkg -I ... I don't want to remove everything just to update every time... Ubuntu 16.04.4 ... 3.2.2 .. happened with 3.2.1 as well.  I've just installed from source the past two versions.... curl -s -o install_api.sh https://raw.githubusercontent.com/wazuh/wazuh-api/v3.2.2/install_api.sh && bash ./install_api.sh download

**Comment by suryjuto** [comment]
I'm pretty consistently having this issue as well.  A fix would be lovely!

**Comment by BraulioV** [comment]
Hi all,

sorry for the inconvenience. I was trying to reproduce this error but I couldn't. I would be great if you try to install the package using `dpkg`.

To do so, first, download the package:
```shellsession
$ wget https://packages.wazuh.com/3.x/apt/pool/main/w/wazuh-api/wazuh-api_3.2.4-1_amd64.deb
```
and then install it using `dpkg`:
```shellsession
# dpkg -i wazuh-api_3.2.4-1_amd64.deb
```
If the installation fails, you can find the post-install script of this package executing the following command:
```shellsession
# ls /var/lib/dpkg/info | grep wazuh-api
```
If you can execute the post-install script and see what is the error and paste it here to know exactly the error it would be very helpful.

Regards,
Braulio.

**Comment by suryjuto** [comment]
Braulio --

Thanks for looking into this.  It's been bugging me for quite some time!

I removed the existing install of wazuh-api with 'apt purge' then installed
via dpkg and this is what I receive:

dpkg -i wazuh-api_3.2.4-1_amd64.deb
Selecting previously unselected package wazuh-api.
(Reading database ... 39907 files and directories currently installed.)
Preparing to unpack wazuh-api_3.2.4-1_amd64.deb ...
cat: /var/ossec//~api/package.json: No such file or directory
dpkg: error processing archive wazuh-api_3.2.4-1_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Warning: wazuh-api.service changed on disk. Run 'systemctl daemon-reload'
to reload units.
Errors were encountered while processing:
 wazuh-api_3.2.4-1_amd64.deb

There are no wazuh-api package scripts currently residing in
/var/lib/dpkg/info -- which is very strange because usually there are.

Previous attempts had it failing on the postinst script.  It's now failing
on preinst.

**Comment by suryjuto** [comment]
Did a little more digging and removed the trailing '/' at the end of the
DIR variable.

It's now complaining that there is no 'package.json' found.

I touched a file called /var/ossec/~api/package.json and re-executed the
package install and it fails out with the same error
(wazuh-api_3.2.4-2_amd64.deb is the packaged I created to test my changes):

dpkg -i wazuh-api_3.2.4-2_amd64.deb
(Reading database ... 39483 files and directories currently installed.)
Preparing to unpack wazuh-api_3.2.4-2_amd64.deb ...
cat: /var/ossec/~api/package.json: No such file or directory
dpkg: error processing archive wazuh-api_3.2.4-2_amd64.deb (--install):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-api_3.2.4-2_amd64.deb

package.json is no long on the system.

**Comment by BraulioV** [comment]
Hi @suryjuto,

thank you for your feedback. We are working to fix all these issues and we hope to get the package ready for the next release. I will back to you as soon as I can.

Thank you very much for your patience and, once again, your feedback.

Regards,
Braulio.

**Comment by Sliim** [comment]
In my case, wazuh-api failed to install because the old systemd service was enabled:
```
# apt-get install wazuh-api
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wazuh-api is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up wazuh-api (3.2.4-1) ...
==============================================================================================================
= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh =
==============================================================================================================
dpkg: error processing package wazuh-api (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-api
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

```
# bash -x  /var/lib/dpkg/info/wazuh-api.postinst configure
+ set -e
+ case "$1" in
++ lsb_release -si
+ OS=Debian
+ DIR=/var/ossec/api
+ WAZUH_TMP_DIR=/tmp/wazuh-api
+ USER=ossec
+ GROUP=ossec
+ OSMYSHELL=/sbin/nologin
+ SCRIPTS_DIR=/usr/share/wazuh-api/scripts/tmp
+ '[' '!' -f /sbin/nologin ']'
+ '[' -f /bin/false ']'
+ OSMYSHELL=/bin/false
+ '[' -z '' ']'
+ echo ==============================================================================================================
==============================================================================================================
+ echo '= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh ='
= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh =
+ echo ==============================================================================================================
==============================================================================================================
+ '[' -f /var/ossec/api/node_modules/htpasswd/bin/htpasswd ']'
+ '[' '!' -x /var/ossec/api/configuration/auth/htpasswd ']'
+ '[' -x /etc/init.d/wazuh-api ']'
+ '[' -d /run/systemd/system ']'
+ systemctl enable wazuh-api
```

```
# systemctl enable wazuh-api
Synchronizing state for wazuh-api.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d wazuh-api defaults
Executing /usr/sbin/update-rc.d wazuh-api enable
Failed to execute operation: File exists
```

```
# systemctl disable wazuh-api
Synchronizing state for wazuh-api.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d wazuh-api defaults
Executing /usr/sbin/update-rc.d wazuh-api disable
insserv: warning: current start runlevel(s) (empty) of script `wazuh-api' overrides LSB defaults (2 3 4 5).
insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `wazuh-api' overrides LSB defaults (0 1 6).
Removed symlink /etc/systemd/system/multi-user.target.wants/wazuh-api.service.
```

```
# apt-get install wazuh-api
Reading package lists... Done
Building dependency tree
Reading state information... Done
wazuh-api is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up wazuh-api (3.2.4-1) ...
==============================================================================================================
= Don’t forget to secure the API configuration by running the script /var/ossec/api/scripts/configure_api.sh =
==============================================================================================================
#
```

Hope this help

**Comment by BraulioV** [comment]
Hi all,

with the latest Wazuh release, we changed how the wazuh-api package handles the services and how it install the services. Now the package disables the previous service while upgrading and install the new service using the same script that the sources installation use.

Can you try to upgrade to the latest version?

PS: thanks @Sliim for the feedback :)

**Comment by avinchakov** [comment]
You have "space" on the end of "/var/ossec/packages_files/agent_config_files/group/agent.conf "

**Comment by davidjiglesias** [comment]
Wazuh-api package is removed in Wazuh 4.0
