### ISSUE TITLE
FIM v2.0: Bugs reported by scan-build

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4530]
# SQLite development

## Scan parameters

- **Branch:** [3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)
- **Platform:** Ubuntu 18
- **Command line:** make TARGET=server DEBUG=1 -j4
- **CLANG version:** clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)

## Scan report

Bug Group | Bug Type | File | Function/Method | Line
-- | -- | -- | -- | --
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 325
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 258
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 288
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1517
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1523
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1530
Memory error | Memory leak | syscheckd/fim_db.c | fim_db_init | 162

# RBTree development

## Scan parameters

- **Branch:** [3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework)
- **Platform:** Ubuntu 18
- **Command line:** make TARGET=server DEBUG=1 -j4
- **CLANG version:** clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)

## Scan report

Bug Group | Bug Type | File | Function/Method | Line
-- | -- | -- | -- | --
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 325
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 258
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 288
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1517
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1523
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1530

Be aware of most of the reported defects are common for both branches.

**Comment by JcabreraC** [comment]
# SQLite development

## Scan parameters

- **Branch:** [3319-fim-rework-sqlite](https://github.com/wazuh/wazuh/tree/3319-fim-rework-sqlite)
- **Platform:** Ubuntu 18
- **Command line:** make TARGET=server DEBUG=1 -j4
- **CLANG version:** clang version 8.0.0-3~ubuntu18.04.2 (tags/RELEASE_800/final)

## Scan report

Bug Group | Bug Type | File | Function/Method | Line
-- | -- | -- | -- | --
API | Argument with 'nonnull' attribute passed null | logcollector/config.c | _getLocalfilesListJSON | 147 
API | Argument with 'nonnull' attribute passed null | syscheckd/fim_db.c | fim_db_data_checksum_range | 705
API | Argument with 'nonnull' attribute passed null | logcollector/config.c | _getLocalfilesListJSON | 146 | 31
API | Argument with 'nonnull' attribute passed null | syscheckd/fim_db.c | fim_db_data_checksum_range | 719 | 29
API | Argument with 'nonnull' attribute passed null | logcollector/config.c | _getLocalfilesListJSON | 145 | 30
Logic error | Cast from non-struct type to struct type | rootcheck/os_string.c | os_string | 182 
Logic error | Cast from non-struct type to struct type | wazuh_modules/wm_database.c | wm_inotify_start | 1434
Logic error | Cast from non-struct type to struct type | os_net/os_net.c | OS_GetHost | 525 
Dead store | Dead assignment | shared/labels_op.c | labels_format | 91 
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 288 
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1517
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1530 | 33 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1530 | 33 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1523 | 31 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1523 | 31 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | analysisd/decoders/syscheck.c | fim_fetch_attributes_state | 1517 | 29 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 258 | 23 | View Report | Report Bug | Open File
Logic error | Dereference of null pointer | shared/rbtree_op.c | rb_balance_delete | 325 | 32 | View Report | Report Bug | Open File
Memory error | Memory leak | syscheckd/fim_db.c | fim_db_init | 162 | 8 | View Report | Report Bug | Open File
Memory error | Memory leak | syscheckd/fim_db.c | fim_db_data_checksum_range | 726 | 13 | View Report | Report Bug | Open File

**Comment by vikman90** [comment]
- [X] **Argument with 'nonnull' attribute passed null**.  logcollector/config.c:145 at `_getLocalfilesListJSON()`.
- [X] **Argument with 'nonnull' attribute passed null**.  logcollector/config.c:146 at `_getLocalfilesListJSON()`.
- [ ] **Argument with 'nonnull' attribute passed null**.  analysisd/decoders/security_configuration_assessment.c:695 at `SaveCompliance()`.
- [ ] **Argument with 'nonnull' attribute passed null**.  syscheckd/fim_db.c:732 at `fim_db_data_checksum_range()`.
- [ ] **Argument with 'nonnull' attribute passed null**.  logcollector/config.c:147 at `_getLocalfilesListJSON()`.
- [ ] **Argument with 'nonnull' attribute passed null**.  syscheckd/fim_db.c:718 at `fim_db_data_checksum_range()`.
- [ ] **Argument with 'nonnull' attribute passed null**.  analysisd/decoders/security_configuration_assessment.c:695 at `SaveCompliance()`.
- [ ] **Branch condition evaluates to a garbage value**.  syscheckd/create_db.c:348 at `fim_audit_inode_event()`.
- [ ] **Dead assignment**.  shared/labels_op.c:91 at `labels_format()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1526 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1530 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1517 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1517 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1533 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  shared/rbtree_op.c:325 at `rb_balance_delete()`.
- [ ] **Dereference of null pointer**.  shared/rbtree_op.c:258 at `rb_balance_delete()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1519 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1533 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1530 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1523 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  shared/rbtree_op.c:288 at `rb_balance_delete()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1519 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1526 at `fim_fetch_attributes_state()`.
- [ ] **Dereference of null pointer**.  analysisd/decoders/syscheck.c:1523 at `fim_fetch_attributes_state()`.
- [ ] **Memory leak**.  syscheckd/fim_db.c:739 at `fim_db_data_checksum_range()`.
- [ ] **Memory leak**.  syscheckd/fim_db.c:171 at `fim_db_init()`.

**Comment by danimegar** [comment]
Build ID: 292895
    Analysis Summary:
       New defects found: 0
       Defects eliminated: 5
