### ISSUE TITLE
Google Cloud and Cloudflare integration

### ISSUE THREAD

**Issue by nzpopa** [wazuh/wazuh#4535]
I'd like to ingest security events from Google Cloud and Cloudflare, like how the AWS integration does. Can you provide documentation about the required steps I should take so I can develop these two integrations? I will submit a PR afterwards.

**Comment by vicferpoy** [comment]
Hi @nzpopa,

We are currently working on a Google Cloud integration. You can follow and use its development here:

https://github.com/wazuh/wazuh/issues/4015 
https://github.com/wazuh/wazuh-documentation/issues/2046


If you have any suggestion please let us know and we can add it to our backlog.

Regards,
Víctor.
