### ISSUE TITLE
FIM v2.0: bug on Windows while doing the integrity synchronization check 

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#4539]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3319-fim-rework-sqlite | Syscheckd | Agent | ALL | Windows |

## Summary
We developed tests to check if events are generated while doing the integrity synchronization check, following this issue: https://github.com/wazuh/wazuh-qa/issues/414

These tests reported that using `whodata` monitoring on `Windows`, this event is not being generated in most of the cases.

## Test behaviour
- Create 3000 files on `/testdir`
- Restart Wazuh using `whodata` monitoring on `/testdir`
- Once syscheck sends the `Initializing FIM Integrity Synchronization check` message, create another file on `/testdir`
- Expect the 'added' event from that new file with a timeout of 15 seconds

This was also tested with a timeout of 60 seconds (FIM integrity synchronization check finished before this) and less files, but it failed too.

The code and test results can be found here:  
https://github.com/wazuh/wazuh-qa/pull/418

**Comment by bah07** [comment]
The error is due to the fact that the generation of the DB in the Windows agent is not correct what causes a failure in the synchronization.
