### ISSUE TITLE
FIM v2: fim-sqlite thread synchronization

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#4553]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3319-fim-rework-sqlite | Syscheckd | Agent | ALL | ALL |

### Bug Description
In the new **sqlite3** implementation, several functions which access `fim.db` are used between mutexes for thread synchronization; for instance: `realtime` functions in thread1 and `fim_sync` functions in thread2. 

The bug lies specifically in some new sqlite-related functions' design, as each one of them holds for too long the mutexes. This causes multiple issues like inconsistency on the files integrity results and delays.

For instances:
```
int fim_db_sync_path_range(fdb_t *fim_sql, char *start, char *top) {
    fim_db_clean_stmt(fim_sql, FIMDB_STMT_GET_PATH_RANGE);
    fim_db_bind_range(fim_sql, FIMDB_STMT_GET_PATH_RANGE, start, top);
    return fim_db_process_get_query(fim_sql, FIMDB_STMT_GET_PATH_RANGE, fim_db_callback_sync_path_range, NULL);

int fim_db_process_get_query(fdb_t *fim_sql, int index, void (*callback)(fdb_t *, fim_entry *, void *), void * arg) {
    int result;

    while (result = sqlite3_step(fim_sql->stmt[index]), result == SQLITE_ROW) {
        fim_entry *entry = fim_db_decode_full_row(fim_sql->stmt[index]);
        callback(fim_sql, (void *) entry, arg);

        free_entry(entry);
}
```
_It makes an SQL statement which generates multiple rows and goes one by one in a loop calling a callback-function that sends a message to the manager. All this used within mutexes._

### Possible solution

 Instead of performing an sql statement which gets all files' path and loops through them in one step, we can first get the paths (within mutexes), save them in a temporary storage, and use them afterward without any other thread waiting.

As for the storage, here are some options:

- Use a new database.
- Use a simple file in plain text format.
- Use a new table within the same database.

**Comment by bah07** [comment]
Thanks @0xN3utr0n !
