### ISSUE TITLE
Add regex support to the multi-line format for Logcollector

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh#4555]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.11.2 | Manager | Packages | CentOS 7 |

Hello team,

It would be great to allow the log collection to read multiple lines looking for a specified expression as the end of log delimiter.
Filebeat has the `multiline.pattern` setting to specify that expression as you may see here: https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html

Regards.

**Comment by chemamartinez** [comment]
Reading multiple lines is already supported for the log collector: https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/localfile.html#log-format
