### ISSUE TITLE
FIM v2.0: Create unit tests for Windows functions

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4569]
|Main issue|
|---|
| https://github.com/wazuh/wazuh/issues/4513 |

This issue accomplishes the development of unit tests for Windows-only functions of the FIM module. In the branch [3319-fim-rework](https://github.com/wazuh/wazuh/tree/3319-fim-rework) the list of functions to review is:

### create_db.c

- [x] fim_registry_event()

### run_check.c

- [x] set_priority_windows_thread()
- [x] set_whodata_mode_changes()

### run_realtime.c

- [x] free_win32rtfim_data()
- [x] realtime_start()
- [x] realtime_win32read()
- [x] realtime_adddir()

### seechanges.c

- [x] filter()
- [x] adapt_win_fc_output()

### syscheck.c

- [x] Start_win32_Syscheck()

### win_whodata.c

- [x] set_winsacl()
- [x] is_valid_sacl()
- [x] set_privilege()
- [x] run_whodata_scan()
- [x] audit_restore()
- [x] restore_sacls()
- [x] restore_audit_policies()
- [x] whodata_callback()
- [x] whodata_audit_start()
- [x] state_checker()
- [x] whodata_list_add()
- [x] whodata_list_remove_multiple()
- [x] whodata_clist_remove()
- [x] whodata_list_set_values()
- [x] set_policies()
- [x] set_subscription_query()
- [x] get_file_time()
- [x] compare_timestamp()
- [x] free_win_whodata_evt()
- [x] check_object_sacl()
- [x] whodata_hash_add()
- [x] notify_SACL_change()
- [x] get_volume_names()
- [x] get_drive_names()
- [x] replace_device_path()
- [x] get_whodata_path()
- [x] whodata_path_filter()
- [x] whodata_adapt_path()
- [x] whodata_check_arch()
- [x] w_update_sacl()

### win_registry.c:

- [x] os_winreg_sethkey()
- [x] os_winreg_querykey()
- [x] os_winreg_open_key()
- [x] os_winreg_check()

### syscheck_op.c

- [x] get_user()
- [x] w_get_file_permissions()
- [x] copy_ace_info()
- [x] w_get_account_info()
- [x] w_get_file_attrs()
- [x] ag_send_syscheck()

**Comment by Molter73** [comment]
## create_db.c Windows agent tests

Total winagent tests: 71

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76620366-4b54be00-652d-11ea-83ba-926c8b257032.png)

### Covered functions
- fim_json_event
- fim_attributes_json
- fim_entry_json
- fim_json_compare_attrs
- fim_audit_json
- fim_check_ignore
- fim_check_restrict
- fim_scan_info
- fim_get_checksum
- fim_check_depth
- fim_configuration_directory
- init_fim_data_entry
- fim_file
- fim_scan
- fim_checker
- fim_directory
- fim_get_data
- check_deleted_files
- free_inode
- fim_realtime_event
- fim_whodata_event
- fim_process_missing_entry
- fim_registry_event

### Comments
Some of the `WIN_WHODATA` branches are not being tested.

**Comment by Molter73** [comment]
## run_check.c Windows agent tests

Total winagent tests: 19

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76620737-26147f80-652e-11ea-8aa2-0ea68e30e253.png)

### Covered functions
- fim_whodata_initialize
- set_priority_windows_thread
- log_realtime_status
- fim_send_msg
- fim_send_sync_msg
- send_syscheck_msg
- fim_send_scan_info
- set_whodata_mode_changes

### Comments
--

**Comment by Molter73** [comment]
## run_realtime.c Windows agent tests

Total winagent tests: 21

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76620961-a63ae500-652e-11ea-8c46-49fab896449e.png)

### Covered functions
- realtime_start
- realtime_win32read
- free_win32rtfim_data
- RTCallBack
- realtime_adddir

### Comments
--

**Comment by Molter73** [comment]
## seechanges.c Windows agent tests

Total winagent tests: 26

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76621280-4db81780-652f-11ea-9ff6-1f4fb2879b6f.png)

### Covered functions
- seechanges_dupfile
- seechanges_addfile
- filter
- adapt_win_fc_output
- is_nodiff

### Comments
--

**Comment by Molter73** [comment]
## syscheck.c Windows agent tests

Total winagent tests: 10

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76621832-93291480-6530-11ea-974c-26b9715f9a43.png)

### Covered functions
- fim_initialize
- read_internal
- Start_win32_Syscheck

### Comments
--

**Comment by Molter73** [comment]
## win_whodata.c Windows agent tests

Total winagent tests: 49

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76628541-2ff1af00-653d-11ea-83cd-3c53a283fb92.png)

### Covered functions
- set_winsacl
- set_privilege
- w_update_sacl
- whodata_check_arch
- whodata_adapt_path
- whodata_path_filter
- get_whodata_path
- is_valid_sacl
- replace_device_path
- get_drive_names

### Comments
Tests on `set_winsacl` need to be improved.
Still missing tests on the following functions:
- run_whodata_scan
- audit_restore
- restore_sacls
- restore_audit_policies
- whodata_callback
- whodata_audit_start
- state_checker
- whodata_list_add
- whodata_list_remove_multiple
- whodata_clist_remove
- whodata_list_set_values
- set_policies
- set_subscription_query
- get_file_time
- compare_timestamp
- free_win_whodata_evt
- check_object_sacl
- whodata_hash_add
- notify_SACL_change
- get_volume_names

**Comment by Molter73** [comment]
## win_registry.c Windows agent tests

Total winagent tests: 21

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76628827-a55d7f80-653d-11ea-9058-a034f0a267c1.png)

### Covered functions
- os_winreg_sethkek
- os_winreg_querykey
- os_winreg_check
- os_winreg_open

### Comments
--

**Comment by Molter73** [comment]
## syscheck_op.c Windows agent tests

Total winagent tests: 67

### Windows agent coverage
![imagen](https://user-images.githubusercontent.com/20206636/76629473-9f1bd300-653e-11ea-8776-8e0c649d8bdf.png)

### Covered functions
- delete_target_file
- escape_syscheck_field
- normalize_path
- remove_empty_folders
- get_group
- ag_send_syscheck
- decode_win_attributes
- decode_win_permissions
- attrs_to_json
- win_perm_to_json
- get_user
- w_get_account_info
- copy_ace_info
- w_get_file_permissions
- w_get_file_attrs

### Comments
Missing tests on `w_directory_exists`
