### ISSUE TITLE
New API: Restructure group exclusive endpoints in new path /groups

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#4571]
Hello team,

For the new API, the following endpoints should be renamed to a new path `/groups`:

`DELETE /agents/groups` --> `Delete /groups`
`GET /agents/groups `--> `Get /groups`
`DELETE /agents/groups/{group_id}` --> `Delete /groups/{group_id}`
`POST /agents/groups/{group_id}` --> `POST /groups/{group_id}`
`GET /agents/groups/{group_id}/configuration` --> `GET /groups/{group_id}/configuration`
`PUT /agents/groups/{group_id}/configuration` --> `PUT /groups/{group_id}/configuration`
`GET /agents/groups/{group_id}/files` --> `GET /groups/{group_id}/files`
`GET /agents/groups/{group_id}/files/{file_name}/json` --> `GET /groups/{group_id}/files/{file_name}/json`
`GET /agents/groups/{group_id}/files/{file_name}/xml` --> `GET /groups/{group_id}/files/{file_name}/xml`

All these endpoints operate exclusively with the groups themselves and having them inside `/agents` path brings confusion as to what exactly they do and could also cause errors such as https://github.com/wazuh/wazuh/issues/3970.

Steps:

- [x]  Rename endpoints in spec.yaml
- [x] Re-run all integration tests

**Comment by crd1985** [comment]
This issue has been performed collaterally in #4474
