### ISSUE TITLE
AWS S3 Wodle - Custom buckets: Ignore only_logs_after when trail_prefix includes YYYY/MM/DD

### ISSUE THREAD

**Issue by awill1988** [wazuh/wazuh#4582]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.x+ | wazuh | both | Packages/Sources | all |

Please see proposed feature enhancement to aws wodle here #4581

Underlying issue arises on subsequent runs of the custom bucket integration and objects exist on the same prefix level as the date.

For Example, objects can contain the following prefixes:
```
AWSLogs/{ACCOUNT_ID}/ecs/us-east-1/2020/02/10/00/...zip
AWSLogs/{ACCOUNT_ID}/ecs/us-east-1/processing_failed/...zip
```

The first run of the wodle (if not found in the SQLLite db) will append `only_logs_after` argument.

However, subsequent runs will not include the date in the prefix and unexpectedly pickup other objects that don't conform to the date prefix pattern, such as second item above. The result is that the marker for that custom integration will be scanning for new objects that are alphanumerically descendant from "p" instead of "2020/02/10/"

This can happen when using Kinesis transforms from CloudWatch... failures get dumped with `processing_failed/` prefixes.

We attempted to alter the `trail_prefix` and append the date, but on the first run we got duplicate date prefixes `AWSLogs/{ACCOUNT_ID}/ecs/us-east-1/2020/02/10/2020/02/10`.

The issue is that on the first run or on reparse, `only_logs_after` is appended to the prefix and our attempt to explicitly indicate the date in the `trail_prefix` breaks the integration.

I understand that custom integrations weren't necessarily designed to handle ever use case under the sun. But if you refer to the pull request, the change is small and I feel it adds value.

Thanks for your time,
Adam

**Comment by vikman90** [comment]
Hi @awill1988,

Thank you for opening this issue and your contribution! We'll review and merge it as soon as possible.

Best regards.

**Comment by CarlosRS9** [comment]
Hi @awill1988,

We are currently reviewing your proposal but first I need to better understand what's happening.

Could you please paste here your wodle configuration to see what exactly you are trying to achieve?

> However, subsequent runs will not include the date in the prefix and unexpectedly pickup other objects that don't conform to the date prefix pattern, such as second item above. The result is that the marker for that custom integration will be scanning for new objects that are alphanumerically descendant from "p" instead of "2020/02/10/"

Could you give us more information regarding what you mention here?

Thanks again for opening this issue and for your contribution, it help us keep improving.

Best regards.
