### ISSUE TITLE
Whodata does not work if there is no valid audit directory

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#4584]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| fim-rework | syscheck | Manager/Agent | Packages/Sources | OS version |

Hello team,

File integrity monitoring with Whodata does not work if when Wazuh is started there is no existing directory with `whodata="yes"` in the configuration.

## Case 1

With the following configuration in the `ossec.conf` file:
```
<directories check_all="yes" whodata="yes">/home/Exist</directories>
<directories check_all="yes" whodata="yes">/home/NoExits</directories>
```
with `/home/NoExits` a directory that does not exist and `/home/Exits` an existing one. 

We have the next output:
```
2020/02/10 17:19:09 ossec-syscheckd: ERROR: (6638): Error adding audit rule for directory (-1): '/home/NoExist'.
```
but when creating the non-existent directory, file integrity monitoring with `Whodata` works well.

## Case 2

With the following configuration in the `ossec.conf` file:
```
<directories check_all="yes" whodata="yes">/home/NoExist1</directories>
<directories check_all="yes" whodata="yes">/home/NoExits2</directories>
```
with `/home/NoExist1` and `/home/NoExist1` directories that don't exist.

We have the next output:
```
2020/02/10 17:19:09 ossec-syscheckd: ERROR: (6638): Error adding audit rule for directory (-1): '/home/NoExits1'.
2020/02/10 17:19:09 ossec-syscheckd: ERROR: (6638): Error adding audit rule for directory (-1): '/home/NoExist2'.
2020/02/10 17:19:09 ossec-syscheckd: WARNING: (6913): Who-data engine could not start. Switching who-data to real-time.
```
and when creating the directory it is monitored in `realtime` mode.

This happens because we cannot add audit rules to a directory that does not exist. As there is no valid directory with `whodata`, the mode is changed to `realtime` for all the directories that had `whodata`.

**Comment by aurelioremonda** [comment]
Hello team,

I managed to reproduce both cases on v3.11.3.

**Comment by chemamartinez** [comment]
Done at #4616
