### ISSUE TITLE
Implement in API 4.0 the distinct parameter

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh#4601]
# Description

This issue is related to https://github.com/wazuh/wazuh/issues/4466.

The changes described there must be implemented also in the new API.

**Comment by josema0097** [comment]
The api now accept the new parameter:
![Captura de pantalla de 2020-03-18 13-30-28](https://user-images.githubusercontent.com/43790556/76961493-b8959400-691d-11ea-9296-bd1923fd03db.png)

**Comment by josema0097** [comment]
### The distinct will be applied to the parameter in select.
http://172.17.0.1:55000/syscheck/000?pretty=false&wait_for_complete=true&offset=0&limit=4&select=gid&select=uname&summary=false&distinct=true
![imagen](https://user-images.githubusercontent.com/43790556/77159820-616efb00-6aa6-11ea-85e1-c3fa869a865d.png)

**Comment by josema0097** [comment]
### Added distinct parameter to both test: 
============================= test session starts ==============================
test_syscheck.py::test_syscheck_files[agent_id0-None-None-None] PASSED   [ 20%]
test_syscheck.py::test_syscheck_files[agent_id1-select1-None-False] PASSED [ 40%]
test_syscheck.py::test_syscheck_files[agent_id2-None-filters2-True] PASSED [ 60%]
test_syscheck.py::test_syscheck_files[agent_id3-select3-filters3-False] PASSED [ 80%]
test_syscheck.py::test_syscheck_files[agent_id4-None-filters4-True] PASSED [100%]

**Comment by josema0097** [comment]
### Added distinct parameter to integration test:
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000 PASSED                                                                                                                                            [  2%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[date] PASSED                                                                                                                                                                    [  5%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[mtime] PASSED                                                                                                                                                                   [  8%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[file] PASSED                                                                                                                                                                    [ 11%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[size] PASSED                                                                                                                                                                    [ 14%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[perm] PASSED                                                                                                                                                                    [ 17%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[uname] PASSED                                                                                                                                                                   [ 20%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[gname] PASSED                                                                                                                                                                   [ 22%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[md5] PASSED                                                                                                                                                                     [ 25%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[sha1] PASSED                                                                                                                                                                    [ 28%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[sha256] PASSED                                                                                                                                                                  [ 31%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[inode] PASSED                                                                                                                                                                   [ 34%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[gid] PASSED                                                                                                                                                                     [ 37%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[uid] PASSED                                                                                                                                                                     [ 40%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000[type] PASSED                                                                                                                                                                    [ 42%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/000/last_scan PASSED                                                                                                                                                                [ 45%]
test_syscheck_endpoints.tavern.yaml::PUT /syscheck PASSED                                                                                                                                                                              [ 48%]
test_syscheck_endpoints.tavern.yaml::PUT /syscheck/000 PASSED                                                                                                                                                                          [ 51%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002 PASSED                                                                                                                                                                          [ 54%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[date] PASSED                                                                                                                                                                    [ 57%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[mtime] PASSED                                                                                                                                                                   [ 60%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[file] PASSED                                                                                                                                                                    [ 62%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[size] PASSED                                                                                                                                                                    [ 65%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[perm] PASSED                                                                                                                                                                    [ 68%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[uname] PASSED                                                                                                                                                                   [ 71%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[gname] PASSED                                                                                                                                                                   [ 74%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[md5] PASSED                                                                                                                                                                     [ 77%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[sha1] PASSED                                                                                                                                                                    [ 80%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[sha256] PASSED                                                                                                                                                                  [ 82%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[inode] PASSED                                                                                                                                                                   [ 85%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[gid] PASSED                                                                                                                                                                     [ 88%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[uid] PASSED                                                                                                                                                                     [ 91%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002[type] PASSED                                                                                                                                                                    [ 94%]
test_syscheck_endpoints.tavern.yaml::GET /syscheck/002/last_scan PASSED                                                                                                                                                                [ 97%]
test_syscheck_endpoints.tavern.yaml::DELETE /syscheck PASSED                                                                                                                                                                           [100%]
