### ISSUE TITLE
wazuh compile error on Raspberry Pi 

### ISSUE THREAD

**Issue by yimingsir** [wazuh/wazuh#4610]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh v3.11.3 | Wazuh component | Agent | Sources | Raspberry Pi 4 Model B Rev 1.1  Debian GNU/Linux 10|
 
addagent/validate.c:48:9: note: ‘snprintf’ output between 4 and 12 bytes into a destination of size 9
         snprintf(_id, 9, "%03d", ++keys->id_counter);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/config.o
    CC logcollector/read_snortfull.o
/usr/bin/ld: external/openssl/libcrypto.a(chacha-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(chacha-armv8.o):(.text+0x20): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_blocks' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): in function `poly1305_init':
(.text+0x40): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_emit' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: (.text+0x48): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): in function `poly1305_emit_neon':
(.text+0x9a0): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha1-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha1-armv8.o): in function `sha1_block_armv8':
(.text+0x1240): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha256-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha256-armv8.o): in function `sha256_block_data_order':
(.text+0xf88): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha512-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha512-armv8.o): in function `sha512_block_data_order':
(.text+0x1108): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1109: libwazuhext.so] Error 1
make[1]: *** Waiting for unfinished jobs....
logcollector/read_snortfull.c: In function ‘read_snortfull’:
logcollector/read_snortfull.c:43:17: warning: ‘strncpy’ output may be truncated copying 65536 bytes from a string of length 65536 [-Wstringop-truncation]
                 strncpy(f_msg, str, OS_MAXSTR);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: Leaving directory '/root/wazuh/src'
make: *** [Makefile:600: agent] Error 2

**Comment by vikman90** [comment]
Hi @yimingsir,

I've got a Raspberry Pi 4 Model B like yours:

|Model|Revision|Hardware (cpuinfo)|Platform (os-release)|
|---|---|---|---|
|Raspberry Pi 4 B|1.1|b03111|Raspbian GNU/Linux 10 (buster)|

I've made a fresh install of Raspbian, I've been able to install an agent version 3.11.3. These two methods worked for me:

## Source build + install

```sh
cd src
make deps
make TARGET=agent -j4
cd ..
sudo USER_BINARYINSTAL=y ./install.sh
```

## Install (implicit building)

```sh
sudo ./install.sh
```

I've found no problems following these steps. Can you share with us how you launched the installation?

Best regards.

**Comment by yimingsir** [comment]
I installed by executing the install.sh script and select agent installation. I tried the compilation method you provided and still reported this error.

`
root@raspbian191:~/wazuh/src# make TARGET=agent -j4
make ossec-agentd agent-auth ossec-logcollector ossec-syscheckd ossec-execd manage_agents wazuh-modulesd
make[1]: Entering directory '/root/wazuh/src'
    LINK libwazuh.a
ar: `u' modifier ignored since `D' is the default (see `U')
    CC libwazuhext.so
    CC os_auth/check_cert.o
    CC logcollector/read_ossecalert.o
    RANLIB libwazuh.a
    CC logcollector/read_command.o
    CC logcollector/read_djb_multilog.o
    CC logcollector/read_postgresql_log.o
    CC logcollector/main.o
    CC logcollector/read_ucs2_le.o
    CC logcollector/config.o
logcollector/read_postgresql_log.c: In function ‘read_postgresql_log’:
logcollector/read_postgresql_log.c:104:17: warning: ‘strncpy’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
                 strncpy(buffer, str, str_len + 2);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
logcollector/read_postgresql_log.c:96:17: warning: ‘strncpy’ output may be truncated copying between 2 and 65536 bytes from a string of length 65536 [-Wstringop-truncation]
                 strncpy(buffer, str, str_len + 2);
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CC logcollector/read_win_el.o
/usr/bin/ld: external/openssl/libcrypto.a(chacha-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(chacha-armv8.o):(.text+0x20): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_blocks' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): in function `poly1305_init':
(.text+0x40): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_ADR_PREL_LO21 against symbol `poly1305_emit' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: (.text+0x48): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(poly1305-armv8.o): in function `poly1305_emit_neon':
(.text+0x9a0): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha1-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha1-armv8.o): in function `sha1_block_armv8':
(.text+0x1240): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha256-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha256-armv8.o): in function `sha256_block_data_order':
(.text+0xf48): dangerous relocation: unsupported relocation
/usr/bin/ld: external/openssl/libcrypto.a(sha512-armv8.o): relocation R_AARCH64_PREL64 against symbol `OPENSSL_armcap_P' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: external/openssl/libcrypto.a(sha512-armv8.o): in function `sha512_block_data_order':
(.text+0x10c8): dangerous relocation: unsupported relocation
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1079: libwazuhext.so] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/wazuh/src'
make: *** [Makefile:573: agent] Error 2
`

**Comment by yimingsir** [comment]
`cd src
make deps
make TARGET=agent DISABLE_SHARED=1 -j4`

I had resolvd using above method.
