### ISSUE TITLE
wazuh-app-version not compatible, I all installed v3.10.2, why the wazuh-app-version need 3.11.x??

### ISSUE THREAD

**Issue by SoldierProgrammer** [wazuh/wazuh#4611]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-rev | Wazuh component | ELK | Sources | CentOS 7 |

when I set wazuh api configuration in kibana, there is an error :
**Settings. 3005 - Invalid 'wazuh-app-version' header. Expected version '3.11.x', and found '3.10.x'. (/api/check-api)**

I have read the troubleshooting:
https://documentation.wazuh.com/3.10/user-manual/kibana-app/troubleshooting.html
API version mismatch. Expected vX.Y.Z
The Wazuh app uses the Wazuh API to fetch information, being compatible between patch versions. For example, you can use an app designed for Wazuh 3.7.2 with a Wazuh API 3.7.1.
You can’t use the 3.7.2 version of Wazuh API with a Wazuh app designed for Wazuh 3.10.2.

But I do not understand why it needs 3.11.x version, because I installed vazuh agent and manager is version 3.10.2. Both of the elasticsearch and kibana is version 7.5.1 according to the guide:
https://documentation.wazuh.com/3.10/installation-guide/installing-elastic-stack/elastic_server_rpm.html

And the wazuhapp version is downbelow:
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.10.2_7.5.1.zip

**Comment by danimegar** [comment]
Hello @SoldierProgrammer 

You are right. The Elastic Stack versions available for v3.10.x are 6.8.6 to 7.5.1. In this link, you can check the compatibility required between Wazuh API and Elastic Stack: https://documentation.wazuh.com/3.11/installation-guide/compatibility_matrix/#api-and-kibana-app

Now, I would like to check the Wazuh and Wazuh API versions. Can you copy the outputs of the following commands?
Wazuh:
`cat /var/ossec/etc/ossec-init.conf | grep VERSION `
Wazuh API:
`# cat /var/ossec/api/package.json | grep version`

If they do not have the same version, please let me know.

If Wazuh API has the latest version, you can download the wazuh-api v3.10.2 package from this website: https://documentation.wazuh.com/3.10/installation-guide/packages-list/index.html

Regards,
               Daniel

**Comment by SoldierProgrammer** [comment]
Hello Daniel,
Your needed information is below:
cat /var/ossec/etc/ossec-init.conf | grep VERSION
VERSION="v3.10.2"
cat /var/ossec/api/package.json | grep version
  "version": "3.11.3",
The versions are different.

I installed the api by execute the commond below:
curl -s -o install_api.sh  https://raw.githubusercontent.com/wazuh/wazuh-api/v3.10.2/install_api.sh && bash ./install_api.sh download

Now I found the file install_api.sh in the URLs below are the same.
https://raw.githubusercontent.com/wazuh/wazuh-api/v3.10.2/install_api.sh
https://raw.githubusercontent.com/wazuh/wazuh-api/v3.11.3/install_api.sh

Is it the problem??

**Comment by danimegar** [comment]
Hello @SoldierProgrammer 

Yes, it is. That command will install the lastest Wazuh-api version (v3.11.3) instead of v3.10.2. It is an issue that was not fixed yet although an issue was created. 

Options to downgrade the wazuh-api:
1) Download the package from https://documentation.wazuh.com/3.10/installation-guide/packages-list/index.html and install it.
2) Download the wazuh-api repository: https://github.com/wazuh/wazuh-api/archive/v3.10.2.zip or https://github.com/wazuh/wazuh-api/archive/v3.10.2.tar.gz and extract it.
```
   # cd wazuh-api-3.10.2
   # ./install_api.sh
```
I hope we fix this issue soon. 
Sorry for the inconveniences.

Regards,
               Daniel

**Comment by SoldierProgrammer** [comment]
Hello @danimegar 
Thank you very much. 
And I have a question now, how could I uninstall the API 3.11.3?
If I execute the wazuh-api-3.10.2/install_api.sh，will it directly replace the 3.11.3 ??

Regards,
daik

**Comment by danimegar** [comment]
Hello @SoldierProgrammer
 
Yes, it will. 

Then you can check if the api works well:

`#  curl -u foo:bar -k http://127.0.0.1:55000?pretty`

Output:
```
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.10.2",
      "hostname": "host",
      "timestamp": "Tue Feb 18 2020 14:22:25 GMT+0100 (GMT+01:00)"
   }
}
```
Regards,
Daniel

**Comment by SoldierProgrammer** [comment]
Hello, @danimegar 
      Thank you!
Regards,
Daik

**Comment by danimegar** [comment]
You are welcome @SoldierProgrammer
 
Please do not hesitate to contact us to share more questions. You can do it in our Slack channel or Google Group so that more people can help you with the questions: https://wazuh.com/community/

Regards,
               Daniel
