### ISSUE TITLE
follow_symbolic_link setting should only monitor symbolic links specified in the directories tag

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#4614]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | FIM | UNIX Agent | Packages/Sources | OS version |

As part of the **syscheck** module rework, the `follow_symbolic_link` option should only monitor links that are specified in the `directories` tag.

As an example, if we have a configuration like this:
```
<syscheck>
  <frequency>50</frequency>
  ...
  <directories follow_symbolic_link="yes">/test/link</directories>
  ...
</syscheck>
```

Where `/test/link` -> `/home/user`. If the option is enabled, the link will be monitored and as a result, also the folder `/home/user`. If the option is not enabled, it will save information related to the link itself but not related to the file or folder where the link is pointing to.

**Comment by chemamartinez** [comment]
Fixed at #4618. 

Thanks, @DProvinciani !!
