### ISSUE TITLE
Feature request:  File Integrity Monitoring - add attribute recursion_level for Windows registry 

### ISSUE THREAD

**Issue by dkempny** [wazuh/wazuh#4615]
Hello Team,

**Future request:** Currently, File Integrity Monitoring has an attribute `recursion_level` available only for directories but not for `windows_registry`. 

It would be useful to add this functionality because a registry tree can be many levels deep, `recursion_level` could help to manage `syscheck` configuration. 

All the best,
Daria

**Comment by jesusjimsa** [comment]
We should also add to Windows registry scan all other options currently present in FIM
- `check_all`
- `check_sum`
- `check_sha1sum`
- `check_md5sum`
- `check_sha256sum`
- `check_size`
- `check_owner`
- `check_group`
- `check_perm`
- `check_attrs`
- `check_mtime`
- `check_inode`?
- `restrict`
- `tag`
- `recursion_level`
