### ISSUE TITLE
FIM v2.0: fim_print_info not showing count in sqlite

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#4619]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | ossec-syscheckd | Manager/Agent | n/a | n/a |

## Bug description
The `fim_print_info` function is not showing the count of nodes and paths in fim-sqlite.

## Log
```Log
2020/02/19 10:40:01 ossec-syscheckd[29991] create_db.c:1038 at fim_print_info(): DEBUG: (6335): Fim entries: 0
2020/02/19 10:40:01 ossec-syscheckd[29991] create_db.c:1047 at fim_print_info(): DEBUG: (6336): Fim inode entries: 0, path count: 0
```

## Remediation
Add sqlite query to check the number of entries in `entry_data` and `entry_path`.

**Comment by bah07** [comment]
Merge: [4620](https://github.com/wazuh/wazuh/pull/4620)
