### ISSUE TITLE
Wazuh email alert content customized

### ISSUE THREAD

**Issue by linsihao7788** [wazuh/wazuh#4627]
I wanted to have a custom alert email feature so I could take advantage of what wazuh found

**Comment by Zenidd** [comment]
Hello @linsihao7788,

In the current Wazuh version you can set several groups of filters to output alerts to one or more emails. You can read more about it in our [Granular email options](https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html#granular-email-options) documentation section. Anyway, this has more to do with how it works than with customizing the content in the emails.

We are already working on native tools to customize the emails body and subject. You can track our progress in the issue [here](https://github.com/wazuh/wazuh/issues/4593).

Meanwhile, in case you are interested in changing the subject of the email alerts you can read t[his Wazuh mail list thread](https://groups.google.com/forum/#!searchin/wazuh/custom$20email|sort:date/wazuh/G-iaDX269WM/fRj9UG01BQAJ) where there are instructions to customize it. It involves modifying and [building](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.html#centos-from-sources) the source code.

I'm labeling this issue as a duplicate as we already have an issue for this enhancement. Let me know if I can close it. Also, for further questions, please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, 


JP Sáez

**Comment by Zenidd** [comment]
Hello again @linsihao7788,

I'm closing the ticket. Don't hesitate to contact us again if you need guidance.

Greetings, JP Sáez
