### ISSUE TITLE
FIM v2.0: inode_id is not updated when inode changes

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#4629]
| Wazuh version | Component         | Install type         | Install method        | Platform  |
|----------------|-----------------|-----------------|--------------------|----------|
| 3.12                   | ossec-syscheck | Manager/Agent  | Packages/Sources | Unix         |

## Bug description

When the inode of a file is modified, the `inode_id` of the `entry_path` table is not updated, while the inode of the `entry_data` table does get updated, causing the tables to unbalance and send `added` alerts instead of `modify` alerts.

## Remediation

Update the `inode_id` of the `entry_path` table when the inode of a file gets changed.

**Comment by jesusjimsa** [comment]
I have updated the `fim_db_insert` function to delete and insert the `entry_data` info only when the `inode` changes.

**Comment by jesusjimsa** [comment]
I have changed the SQL query to update `inode_id` and search by the `path`.

Replaces this:
https://github.com/wazuh/wazuh/blob/1f62e5db67e2358bd7f9274ef360baea3ca8061b/src/syscheckd/fim_db.c#L23

With this:
https://github.com/wazuh/wazuh/blob/e56ca16aba55e51b9cf0d18f07efdc87cbc096cc/src/syscheckd/fim_db.c#L23

**Comment by chemamartinez** [comment]
Merged #4635
