### ISSUE TITLE
wazuh rules about mitre

### ISSUE THREAD

**Issue by ghlilou97** [wazuh/wazuh#4639]
is there any wazuh_rules that already exits wich are based on  mitre att&ck  ?

**Comment by danimegar** [comment]
Hi @ghlilou97
 
Actually, we are working on the development of Mitre att&ck and it will be included as soon as possible. 

We mapped some Mitre technique to the Wazuh rules in wazuh-ruleset repository. You can watch it on this link (look Files Changed tab): https://github.com/wazuh/wazuh-ruleset/compare/3.10-mitre

Also, we added a Mitre database to Wazuh Database that stores more information about a Mitre Technique (description, platforms, phases, etc) and the alerts will show Mitre information in a terminal and Kibana. Repo in wazuh:  https://github.com/wazuh/wazuh/compare/3.10-mitre

Wazuh UI is being developed too to show more options related to MITRE on Kibana.

**Comment by danimegar** [comment]
I close this issue for inactivity.

Feel free to reopen this issue or to use our Slack channel or join our mailing list: https://wazuh.com/community/ to share more questions.

Regards,
Daniel
