### ISSUE TITLE
FIM v2.0: Non-existing directories monitored do not generate alerts in Windows

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh#4640]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3319-fim-rework-sqlite | Syscheck | Winagent | All | All |

## Description
I check if a non-existing directory is monitored in realtime after the frequency-time has passed. 

I created the directory and a file after the first scan and I waited for the frequency to pass. When the frequency passed I create a new file in the directory. I expected to receive an 'added' alert in mode realtime as it happens in Linux but it did not appear. The same happened in whodata mode.

It is necessary to modify syscheck to allow alerts to be generated.

**Comment by jesusjimsa** [comment]
The problem was caused because it only checked the `realtime` directories when starting `syscheck`. It can be solved by moving the check of directories to the `while` loop and have it checked every second.

**Comment by jesusjimsa** [comment]
Despite this fix, the tests still fail. I will continue to investigate this issue.

**Comment by jesusjimsa** [comment]
The fix I added to the Pull Request works only with `realtime`, `whodata` does not send alerts for non-monitored folders.

**Comment by jesusjimsa** [comment]
I have added `whodata` to the loop and now, it works with both `realtime` and `whodata`.

**Comment by jesusjimsa** [comment]
The tests will always fail in Windows because now, `realtime` and `whodata` don't have to wait for the next scan to generate events, which is a condition for the test right now.

**Comment by chemamartinez** [comment]
Merged #4645!
