### ISSUE TITLE
[Development] Configuration issues in Windows Agents

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#4644]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0 | syscheck | Agent | Packages | Windows Server 2016 |

Hi team,

We've detected an issue related to the new FIM configuration options in Windows hosts. With this configuration
```xml
  <syscheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <scan_on_start>yes</scan_on_start>
    <synchronization>
      <interval>1</interval>
      <response_timeout>1</response_timeout>
      <queue_size>16384</queue_size>
    </synchronization>
    <directories recursion_level="" restrict="" tags="">C:\performance_test_fim</directories>
  </syscheck>
```
the agent won't start due to a configuration error. Here you can see the log: `2020/02/21 10:05:32 ossec-agent[3760] syscheck-config.c:1347 at Read_Syscheck(): ERROR: (1230): Invalid element in the configuration: 'synchronization'.`

It seems the `synchronization` block is causing some error, but if we decide to remove that entire block and let the agent apply the default configuration, another error appears in the logs: `2020/02/21 10:20:13 ossec-agent[4928] syscheck.c:124 at Start_win32_Syscheck(): CRITICAL: (1202): Configuration error at 'ossec.conf'.`

Also, this message appears in the logs: `2020/02/21 10:20:13 ossec-agent[4928] syscheck-config.c:635 at read_attr(): WARNING: (6677): No option provided for directories: 'c:\performance_test_fim', ignoring it.`

All of this is really strange because the same configuration works fine in Linux environments and macOS environments, both `synchronization` block and `directories` line.

**Comment by vikman90** [comment]
Hi @BraulioV,

I agree that this behavior is really weird. I haven't managed to reproduce this problem. This is my full configuration:

```xml
<!--
  Wazuh - Agent - Default configuration for Windows
  More info at: https://documentation.wazuh.com
  Mailing list: https://groups.google.com/forum/#!forum/wazuh
-->

<ossec_config>

  <client>
    <server>
      <address>buster</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>

  <!-- Agent buffer options -->
  <client_buffer>
    <disabled>no</disabled>
    <queue_size>5000</queue_size>
    <events_per_second>500</events_per_second>
  </client_buffer>

  <!-- File integrity monitoring
  <syscheck>
    <disabled>no</disabled>
    <frequency>10</frequency>
    <windows_audit_interval>300</windows_audit_interval>
    <process_priority>10</process_priority>
    <max_eps>200</max_eps>
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
    </synchronization>
  </syscheck>
  -->
  
  <syscheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <scan_on_start>yes</scan_on_start>
    <synchronization>
      <interval>1</interval>
      <response_timeout>1</response_timeout>
      <queue_size>16384</queue_size>
    </synchronization>
    <directories recursion_level="" restrict="" tags="">C:\performance_test_fim</directories>
  </syscheck>

  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>wpk_root.pem</ca_store>
    <ca_verification>yes</ca_verification>
  </active-response>

  <!-- Choose between plain or json format (or both) for internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>

</ossec_config>

<!-- END of Default Configuration. -->
```

Can you compare it with yours?
Cheers.

**Comment by BraulioV** [comment]
Hi @vikman90,

After some research, I found that this error was caused by a bug in the deployment of the infrastructure done by the CI environment, so I'm closing this issue.

Sorry for the inconvenience.
