### ISSUE TITLE
elasticsearch Memory configuration with docker

### ISSUE THREAD

**Issue by freegit9527** [wazuh/wazuh#4649]
hi，
   I set elasticsearch memory 3GB in docker-compose.yml, but when  I  enter  the elasticsearch  container,I find mem is 1GB;
docker-compose.yml : 
    environment:
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 8g
elasticsearch  container:
/usr/share/elasticsearch/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSI

Please help to solve this question，thinks!

**Comment by Lopuiz** [comment]
Hello, @freegit9527 

I have checked it and it works. I stopped containers, modified  `docker-compose.yml` and I up them again. Now the limit memory of Elasticsearch container is 8GiB (as shown below):

![imagen](https://user-images.githubusercontent.com/17710550/75141531-68962980-56f1-11ea-85fc-633ce097559e.png)

Please, Could you give us more information about the issue?

Regards,
Eva

**Comment by Lopuiz** [comment]
Hello @freegit9527 

I hope it helped you. I am going to close this issue for inactivity.

Best regards,
Eva
