### ISSUE TITLE
FIM - cannot interpret '*' as all the users you have in our local machine.

### ISSUE THREAD

**Issue by Schiltech** [wazuh/wazuh#4650]
Hi,

As Daniel said, _At the moment, FIM cannot interpret '*' as all the users you have in our machine. You have to do for separate:_

`<directories check_all="yes" whodata="yes">c:\Users\user1\AppData\Local</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user1\AppData\Local\Temp</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user1\AppData\LocalLow</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user1\AppData\Roaming</directories>`

`<directories check_all="yes" whodata="yes">c:\Users\user2\AppData\Local</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user2\AppData\Local\Temp</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user2\AppData\LocalLow</directories>`
`<directories check_all="yes" whodata="yes">c:\Users\user2\AppData\Roaming</directories>`

The goal is to simplify the lines above by something like this : 
`<directories check_all="yes" whodata="yes">C:\Users\*\AppData\Local</directories>`
`<directories check_all="yes" whodata="yes">C:\Users\*\AppData\Local\Temp</directories>`
`<directories check_all="yes" whodata="yes">C:\Users\*\AppData\LocalLow</directories>`
`<directories check_all="yes" whodata="yes">C:\Users\*\AppData\Roaming</directories>`

See the topic bellow for more information.

https://groups.google.com/forum/#!topic/wazuh/vMzzdH84Gug

**Comment by Molter73** [comment]
I'm closing this issue since it looks like #2723 already included this feature request. Furthermore, #8461 added support for wildcards in Windows, which will be available starting with version 4.3.0.

Regards
