### ISSUE TITLE
FIM v2.0: Huge number of Audit events are lost randomly

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#4660]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3319-fim-rework-sqlite | Syscheck | Agent | Sources | Linux |
### Description
While monitoring a directory(whodata)  and adding 1k files, syscheckd fails to report most of them:
```
[root@serv-test-centos-1 vagrant]# for i in {1..1000}; do touch /opt/fim_testing/file_${i} ; done
[root@serv-test-centos-1 vagrant]# ls /opt/fim_testing/ | grep file_ | wc -l
1000
[root@serv-test-centos-1 vagrant]# cat /var/log/audit/audit.log | grep /opt/fim_testing/file_ | wc -l
1000
```
Way lower number of events reported:
```
[root@serv-test-manager-centos-1 vagrant]# cat /var/ossec/logs/alerts/alerts.json | grep /opt/fim_testing/file_ | grep added | grep audit | wc -l
148
```

After some debugging, we've seen that said events are lost even before calling `fim_whodata_event()`, which means that the bug must be quite old.

Our best guess is that there's a bug in `audit_parse()` .

**Comment by jotacarma90** [comment]
I checked the audit log for all events. It works correctly. In the function audit_parse I have created a debug message to see how many events can be filtered. And at this point many have already been lost. This is a problem with the audit socket.
There are two different variables that affect the amount of lost events:
in /etc/audisp/audispd.conf, the q_dephs variable (I tried 125, 512, 1024)
in internal_option, the variable rt_delay (I tried values between 1 and 20)

Translated with www.DeepL.com/Translator (free version)

**Comment by jotacarma90** [comment]
## Events loss evaluation

Im going to test with more detail the changes produced by the different variables related to the loss of events:
- **q_dephs** = [125, 512, 1024]
- **disp_qos** = [lossy, lossless]
- **rt_delay** = [1, 2, 5, 8, 10]
 
  
 ----------------------------------------------------------------------------
`q_dephs = 125`
`disp_qos = lossy`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1253  | 1021     | 491     |
| 2        | 1098  | 975      | 655     |
| 5        | 613   | 481      | 458     |
| 8        | 400   | 357      | 203     |
| 10       | 336   | 302      | 220     |
 ----------------------------------------------------------------------------
`q_dephs = 125`
`disp_qos = lossless`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1911  | 1879     | 1946    |
| 2        | 1872  | 1853     | 1955    |
| 5        | 1792  | 1756     | 1888    |
| 8        | 1724  | 1701     | 1907    |
| 10       | 1656  | 1646     | 1860    |
 ----------------------------------------------------------------------------
`q_dephs = 512`
`disp_qos = lossy`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1162  | 1086     | 748     |
| 2        | 1061  | 966      | 892     |
| 5        | 646   | 505      | 351     |
| 8        | 436   | 436      | 180     |
| 10       | 401   | 368      | 229     |
 ----------------------------------------------------------------------------
`q_dephs = 512`
`disp_qos = lossless`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1929  | 1891     | 1938    |
| 2        | 1879  | 1863     | 1950    |
| 5        | 1804  | 1770     | 1937    |
| 8        | 1732  | 1697     | 1911    |
| 10       | 1674  | 1657     | 1821    |
 ----------------------------------------------------------------------------
`q_dephs = 1024`
`disp_qos = lossy`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1140  | 1218     | 861     |
| 2        | 1226  | 1014     | 959     |
| 5        | 714   | 636      | 271     |
| 8        | 527   | 493      | 459     |
| 10       | 490   | 454      | 138     |
 ----------------------------------------------------------------------------
`q_dephs = 1024`
`disp_qos = lossless`
| rt_delay | added | modified | deleted |
|----------|-------|----------|---------|
| 1        | 1947  | 1890     | 1939    |
| 2        | 1895  | 1866     | 1924    |
| 5        | 1798  | 1784     | 1948    |
| 8        | 1738  | 1716     | 1921    |
| 10       | 1703  | 1684     | 1863    |

**Comment by jotacarma90** [comment]
# Extra:
The user must change the audit configuration to get the best functionality. These parameters should be recommended in the wazuh documentation:
- /etc/audisp/audispd.conf -> **q_dephs**
- /etc/audit/auditd.conf -> **disp_qos** (lossy or lossless)

The range of the rt_delay variable is (1..1000) currently. It would be necessary to add 0 to this range (0..1000). 
Be careful when rt_delay is 0, the function sleep(0) dont work correctly because is not real 0 seconds.

**Comment by jotacarma90** [comment]
wazuh/wazuh-documentation#2249
Added some explanation about this in the documentation.
