### ISSUE TITLE
Symbolic links are followed when realtime is enabled in a directory even if follow_symbolic_link is disabled

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#4671]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | FIM | UNIX Agent | Packages/Sources | OS version |

When the `follow_symbolic_link` option is disabled, it shouldn't follow the symbolic links and shouldn't monitor the content of the folders where the links are pointing to.

The issue here is, even having this setting disabled if the `realtime` setting is enabled over the same directory, the symbolic links are followed.

Here some steps to reproduce:
1. Create an empty directory called `testdir_target`
2. Create an empty directory called `testdir_link`
3. Create a symbolic link within `testdir_link` called `symlink2` pointing to `testdir_target`
4. Apply the next configuration to the **ossec.conf** file and restart the wazuh service

```
<syscheck>
    <disabled>no</disabled>
    <directories realtime="yes" follow_symbolic_link="no">/testdir_link/symlink2</directories>
</syscheck>
```

5. After restarting the service, create a file called `regular1` within `testdir_target` and check the **ossec.log**. You will find a line of log like:

```
Sending FIM event: {"type":"event","data":{"path":"/testdir_link/symlink2/regular1","mode":"real-time","type":"added","timestamp":1582646934,"attributes":{"type":"file","size":0,"perm":"rw-r--r--","uid":"0","gid":"0","user_name":"root","group_name":"root","inode":52398404,"mtime":1582646934,"hash_md5":"d41d8cd98f00b204e9800998ecf8427e","hash_sha1":"da39a3ee5e6b4b0d3255bfef95601890afd80709","hash_sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","checksum":"32f9959b9b992d5b729d1af7575de8e6264cc18d"}}}
```

**Comment by chemamartinez** [comment]
Merged #4672
