### ISSUE TITLE
FIM v2.0: Minor fixes

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#4679]
| Wazuh version | Component        | Install type | Install method | Platform |
|----------------|-----------------|------------|---------------|----------|
| 3.12                   | ossec-syscheck | n/a             | n/a                    | n/a          |

This issue will be used to detail all the minor fixes that need to be added to `3319-fim-rework-sqlite`. The branch where they will be added is `3319-fim-rework-sqlite-minor-fixes`.  
The procedure will be:
1. Comment here what will be fixed
2. Commit to `3319-fim-rework-sqlite-minor-fixes`
3. Comment in the Pull Request explaining what was fixed in the commit (using the commit identifier)

**Comment by jesusjimsa** [comment]
There are several missing `fim_db_force_commit` in `fim_db.c`.

**Comment by Molter73** [comment]
There is a memory leak on `fim_registry_event` when an error occurs inserting data into the fim db
https://github.com/wazuh/wazuh/blob/fb5b2824800ff6220ca73d97fb8471b8dbfc8636/src/syscheckd/create_db.c#L419-L433

**Comment by Molter73** [comment]
Calling multiple Windows API calls before `GetLastError` might cause a wrong/confusing message to be writen into the log
https://github.com/wazuh/wazuh/blob/fb5b2824800ff6220ca73d97fb8471b8dbfc8636/src/shared/syscheck_op.c#L667-L697

**Comment by JcabreraC** [comment]
Added checking of the returned value of the function `fim_db_get_paths_from_inode`.

**Comment by jotacarma90** [comment]
Fixed two warnings.
```
syscheckd/run_realtime.c: In function 'realtime_adddir':
syscheckd/run_realtime.c:340:55: warning: unused parameter 'followsl' [-Wunused-parameter]
 int realtime_adddir(const char *dir, int whodata, int followsl)
                                                       ^~~~~~~~
    CC logcollector/read_ossecalert-event.o
syscheckd/win_whodata.c: In function 'get_drive_names':
syscheckd/win_whodata.c:1314:51: warning: passing argument 1 of 'strlen' from incompatible pointer type [-Wincompatible-pointer-types]
             wcstombs(convert_name, nameit, strlen(nameit));
                                                   ^~~~~~
In file included from /usr/share/mingw-w64/include/io.h:10:0,
                 from /usr/share/mingw-w64/include/sys/stat.h:14,
                 from ./headers/shared.h:40,
                 from syscheckd/win_whodata.c:10:
/usr/share/mingw-w64/include/string.h:64:18: note: expected 'const char *' but argument is of type 'wchar_t * {aka short unsigned int *}'
   size_t __cdecl strlen(const char *_Str);
                  ^~~~~~
```

**Comment by JcabreraC** [comment]
Fixed the following windows compilation warning:
```
shared/log_builder.c: In function ‘log_builder_update_host_ip’:
shared/log_builder.c:242:15: warning: implicit declaration of function ‘get_agent_ip’; did you mean ‘get_agent_info’? [-Wimplicit-function-declaration]
     host_ip = get_agent_ip();
               ^~~~~~~~~~~~
               get_agent_info
shared/log_builder.c:242:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     host_ip = get_agent_ip();
             ^
```
