### ISSUE TITLE
Shared config files (cis_*, rootlkit_*, win_*) disappear after agent registration for non-default groups

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh#4684]
Hi,
I hit something I am not sure 100% it is a bug (in my opinion it is, however I just need someone to check on this). I can reproduce this with any Wazuh-version >= 3.10

This looks pretty much as https://github.com/wazuh/wazuh/issues/3536, however in my option this default behaviour is really bad.

- install a Wazuh Manager on Ubuntu/CentOS
- install a Wazuh agent (I can see the same behaviour on CentOS/Ubuntu/Windows)
- check the etc/shared on the agent's side: you'll see all the config files cis_*, rootkit_*, win_*:
`[root@localhost bin]# ls -la ../etc/shared/
total 1692
drwxrwx---. 2 root  ossec   4096 Mar  2 01:20 .
drwxrwx---. 3 ossec ossec    181 Mar  2 01:17 ..
-rw-rw----. 1 root  ossec  28416 Feb 24 09:32 cis_apache2224_rcl.txt
-rw-rw----. 1 root  ossec  12581 Feb 24 09:32 cis_debian_linux_rcl.txt
-rw-rw----. 1 root  ossec   7614 Feb 24 09:32 cis_mysql5-6_community_rcl.txt
-rw-rw----. 1 root  ossec  10302 Feb 24 09:32 cis_mysql5-6_enterprise_rcl.txt
-rw-rw----. 1 root  ossec  35786 Feb 24 09:32 cis_rhel5_linux_rcl.txt
-rw-rw----. 1 root  ossec  33875 Feb 24 09:32 cis_rhel6_linux_rcl.txt
-rw-rw----. 1 root  ossec  36962 Feb 24 09:32 cis_rhel7_linux_rcl.txt
-rw-rw----. 1 root  ossec  17663 Feb 24 09:32 cis_rhel_linux_rcl.txt
-rw-rw----. 1 root  ossec  34381 Feb 24 09:32 cis_sles11_linux_rcl.txt
-rw-rw----. 1 root  ossec  35086 Feb 24 09:32 cis_sles12_linux_rcl.txt
-rw-rw----. 1 root  ossec  94882 Feb 24 09:32 cis_win2012r2_domainL1_rcl.txt
-rw-rw----. 1 root  ossec  28011 Feb 24 09:32 cis_win2012r2_domainL2_rcl.txt
-rw-rw----. 1 root  ossec 100535 Feb 24 09:32 cis_win2012r2_memberL1_rcl.txt
-rw-rw----. 1 root  ossec 376007 Feb 24 09:32 cis_win2012r2_memberL2_rcl.txt
-rw-r--r--. 1 ossec ossec 585728 Mar  2 01:20 merged.mg
-rw-rw----. 1 root  ossec  16179 Feb 24 09:32 rootkit_files.txt
-rw-rw----. 1 root  ossec   5553 Feb 24 09:32 rootkit_trojans.txt
-rw-rw----. 1 root  ossec   4471 Feb 24 09:32 system_audit_rcl.txt
-rw-rw----. 1 root  ossec   3290 Feb 24 09:32 system_audit_ssh.txt
-rw-rw----. 1 root  ossec   5219 Feb 24 09:32 win_applications_rcl.txt
-rw-rw----. 1 root  ossec   4282 Feb 24 09:32 win_audit_rcl.txt
-rw-rw----. 1 root  ossec   7319 Feb 24 09:32 win_malware_rcl.txt
`
- now change the MANAGER_IP on ossec.conf & register the agent (my manager is on that IP specified, but for your environment of course it will be different):
`./agent-auth -m 172.16.204.194`

result: agent is assigned to the default group and everything works fine, even better rootcheck will be able to find all the files shared/rootcheck_* under the shared folder (I have removed some of the output): (in ossec.conf we have)
`
  <rootcheck>
    <rootkit_files>/var/ossec/etc/shared/rootkit_files.txt</rootkit_files>
    <rootkit_trojans>/var/ossec/etc/shared/rootkit_trojans.txt</rootkit_trojans>
  </rootcheck>
`

- if you register the agent with 
`./agent-auth -m 172.16.204.194 -G my_new_group`
the agent's etc/shared folder will be cleared and this basically means rootcheck won't be able to start.

Sure, we can copy all the files from the default group to our new group, and assign each file to the ossec/ossec owner/group, however what I am really asking here is why those config files are deleted during the agent's registration. They should stay there and (optionally) overwritten if our custom group "my_new_group" has something that needs to be pushed to the agent.

**Comment by 0xN3utr0n** [comment]
Hello **lucanus81**,
I've been checking the issue and it's as you say, right now the folder is cleaned after changing the group. I will mark it with the label of `enhancement` since it's more of a feature rather than a bug.

Thanks for the feedback!

Kind regards,
Fernando G.

**Comment by lucanus81** [comment]
@0xN3utr0n ,
thanks for finding some time for checking my bugs.

Well, I am not sure this is really an enhancement because if you assign an agent to a group during the registration rootcheck (and potentially any tool that expects any configuration file on the etc/shared folder won't work at all)

Anyway, you guys are the experts, so I am sure you know the product much more than I do.

Thanks,
Luca
