### ISSUE TITLE
[FIM] Implement an option to set the maximum number of files to monitor

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#4687]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| fim-rework-sqlite | FIM | Manager/Agent | Packages/Sources | All |

Hello team,

In systems with limited resources, a wrong configuration of `syscheck` can lead to monitoring hundreds of thousands of files, which could be a serious problem if we think about system performance. That's why it is necessary to implement a global option to set the maximum number of files to monitor.

This option should be as follows:

```xml
<syscheck>
    <file_limit>100000</file_limit>
</syscheck>
```

- Only positive values are allowed.
- The default value is 100000.
- If set to 0, there will be no limit (as it currently works).

**Comment by TomasTurina** [comment]
## Update 3:

- The new configuration option `file_limit` was added to the configuration file inside the `syscheck` block. Its default value is 100000.

```xml
<syscheck>
    <file_limit>100000</file_limit>
</syscheck>
```

- A function to organize the directory folders alphabetically was added. Its name is `organize_syscheck_dirs` and it receives the `syscheck` configuration block as a parameter.

- The double scan mechanism was implemented inside the `fim_scan` function. At the end of the first scan, the `file_limit` is checked. If its value is 0, it continues the execution as usual. If not, it continue as follows:

  - If the number of entries in the DB is lower than the `file_limit`, it continues the execution as usual.

  - If not, a second scan is performed. This scan has the particularity that it will stop the directory iteration when the DB changes its state to full, so it could iterate all the directories or just the necessaries to fill the DB.

- An alert is generated in the following cases:

  - When the DB reaches its 80% of capacity, a message is sent to the manager and an alert of `level` 7 is generated.

  - When the DB reaches its 90% of capacity, a message is sent to the manager and an alert of `level` 9 is generated.

  - When the DB gets full, a message is sent to the manager and an alert of `level` 12 is generated.

  - When the DB returns to its normal state (<80%),  a message is sent to the manager and an alert of `level` 3 is generated.

- When an alert of a kind is displayed, it won't display again unless the DB changes its state. All these changes are managed in the new function `fim_check_db_state`.

**Comment by TomasTurina** [comment]
## Update 4:

Unit tests for Linux and Windows are already implemented.

**Comment by jesusjimsa** [comment]
The highest number that will be permitted to write in the configuration will be `2147483647`. Also, the configuration will change its format, being like this:

```xml
<file_limit>
  <enabled>yes|no</enabled>
  <entries>1|2147483647</entries>
</file_limit>
```

The default configuration will be `enable=yes entries=100000` and it will not appear in the default configuration that is added when installing Wazuh for the first time.

**Comment by jesusjimsa** [comment]
Added max value for `file_limit` and support for the new configuration format.

**Comment by jesusjimsa** [comment]
Refactored `fim_scan` function to simplify it.

**Comment by jesusjimsa** [comment]
Unit tests need to be adapted to the refactorization and the warning message for full database.
