### ISSUE TITLE
Syscheck report_changes takes too much to report alerts from Windows agent.

### ISSUE THREAD

**Issue by rshad** [wazuh/wazuh#4691]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 Testing Branch | Syscheck| Agent | Packages|Windows Server 2012 & 2016|

**wazuh-agent Custom Package RPM URL**: [Check Here]( https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/branches/3.12/rpm/var/wazuh-agent-3.12.0-0.3319fimreworksqlite.x86_64.rpm)

Hi Wazuh!

### Issue Description

We recently were testing _Syscheck_ `report_changes` behavior, and especially on Windows, it takes a long time to run the diff process of each file. 

---

### Related _ossec.conf config.**_ for _Syscheck_
```xml
<directories recursion_level="320"  check_all="yes"  realtime="yes" report_changes="yes">
C:\fim_testing
</directories>
```
---

### How to reproduce

Having enabled the feature `report_changes` in Syscheck for the directory `C:\fim_testing` and after having created 5010 files from different sizes, we then modified each file by adding a sentence at the beginning of it, e.g: `Hello World`.

To generate files, we ran the script [generate_files.py](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/generate_files.py)

files_configuration.json is found [here](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/files_configuration.json.j2)

```bash

python3 generate_files.py -c files_configuration.json -o files_generated.txt"
```

To modify the files, then we ran the script [modify_files.py](https://github.com/wazuh/wazuh-qa/blob/feature-493-create-test-scenarios/tests/system/fim/common_tasks/modify_files.py)

```
python3 modify_files.py -i files_generated.txt -o files_modified.txt -t
```

---

### Windows Host Machine Characteristics

**Default Machine Characteristics**
- 1 GB of RAM memory.
- 1 Core.

**Custom Machine Characteristics**
- 2 GB of RAM memory.
- 2 Cores.

**Windows Images**
- Windows Server 2016.
- Windows Server 2012.

But nothing has been changed; still has the same behavior.

After checking the Windows machine RAM and CPU behavior we found that there is no leak of RAM memory or CPU, as you can check on the following capture.

![image](https://user-images.githubusercontent.com/19154337/75336934-513f7380-588c-11ea-9f01-b09ff98ccd0a.png)

We can clearly see that the process of  `wazuh-agent` is consuming only ~ 10 MB of RAM and nothing of CPU, but we also can notice the process `DOS 5 File Compare Utility (32 bit)` which is the background process used by `wazuh-agent` to run the `diff` for `Syscheck` and it's consuming almost half of the available CPU. This process seems to be running so slowly, depending on the file size.

---

**Tests, Evaluations and, Metrics**

It's clear that Windows is taking a long time to run the diff process of each file, but to know what time it exactly takes depending on each group of files of a determined size, we estimated the time between the first received alert and the last one, testing with the different files groups depending on the file size, separately.

`Time refers to "Time needed till all the alerts are received"`.

| File Size| Number of Files | Time (min) | Average time/alert (sec) | Test State |
|---|---|---|---|---|
|11 KB|4000|~11|~0.165|✔️|
|513KB|500|~150|~18|✔️|
|1.1M|500|~633|~76|✔️|  
|11M|10|~140|~840 = (14 min)|❌ |

**Notes**
- The test in the case of files of `11MB`, fails as the alert list does grow very slowly.

- Also, the process DOS 5 File Compare Utility (32 bit) responsible for running the `diff` in `Syscheck`, died after sending the first alert of the file of `11MB`.

Kr,

Rshad

**Comment by jotacarma90** [comment]
I analyzed this problem, measured the time it takes to run the  function, and saw the following differences (according to file size):

**Comment by jotacarma90** [comment]
Finally, I discovered that time was being spent on the **diff** command (**fc** command in windows). Im going to analyze the time with every size file.

**Comment by jotacarma90** [comment]
At least, this problem might not be blocking between threads, so, I've changed the mutex so that it doesn't block the fim_json_event function, which doesn't need them. But this is another issue.

**Comment by jotacarma90** [comment]
I have been analyzing different options for this issue, and I have discovered that the problem appears exclusively when dealing with **long line files**.
I've done similar tests to the issue, same configuration and same scripts.
- The 11 Mb single line files take about 15 minutes to process.
- By simply dividing that line, I have made each line 32*1024 characters at most. Modified alerts take about 5 seconds to appear.

The differences are huge, so the problem is to treat the long line files.
One possibility is to look for the longest line in a file, and if it exceeds a certain amount, divide it so that we don't have such long waiting times.

**Comment by jotacarma90** [comment]
More analysis about this problem in Windows:

- 10 Mb file in 1 line (~10.000.000 chars): ~14 minutes.
- 10 Mb file in 10 lines (~1.000.000 char/line): ~8 minutes.
- 10 Mb file in 20 lines (~500.000 char/line): ~2 minutes.
- 10 Mb file in 40 lines (~250.000 char/line): ~15 seconds.
- 100 Mb file in 400 lines (~250.000 char/line): ~2.5 minutes.
- 100 Mb file in 800 lines (~125.000 char/line): ~1 minute.

**Comment by jotacarma90** [comment]
We definitely can't do anything about this problem, since the tools we have don't handle file comparisons well when we have extremely long lines (as we have seen in the time analysis). 
The issue is closed for now.
