### ISSUE TITLE
Support for differential mode

### ISSUE THREAD

**Issue by hapablanha** [wazuh/wazuh#4697]
syscollector periodically collect inventory information such as RPM and send to manager, even there is no any change, this is affordable for "agent", but "server" has to process and store unchanged data.
In order to improve the scalability, it could be an option to support differential mode like osquery. Ideally syscollector generate "removed" and "add" events and agentd send them to "server", and "server" analyse the data and update wazuh_db to synchronise the inventory data.

**Comment by bah07** [comment]
Hi @hapablanha 

We already have this contemplated in our roadmap, here is the issue where you can see the progress of development, I proceed to close this issue to avoid duplication.

[Syscollector inventory #3940](https://github.com/wazuh/wazuh/issues/3940)

Regards.
