### ISSUE TITLE
office 365 smtp error in wazuh 

### ISSUE THREAD

**Issue by coopjab** [wazuh/wazuh#4718]
@Lopuiz 
when i setted up with office 365 and trying to send mail 
i cant send mail its saying in /var/logs/mailog that smtp.office365.com offered no supported AUTH mechanisms: 'LOGIN XOAUTH2 
how can i solve this issue?

and to that I'm also getting this type of issue 

 server smtp.office365.com offered no compatible authentication mechanisms for this type of connection security)

**Comment by Lopuiz** [comment]
Hello @coopjab 

It seems to be an SMTP error, not Wazuh error.
Could you tell us the SMTP server used? Also, I would like to know the Wazuh configuration.

Greetings,
Eva

**Comment by coopjab** [comment]
@Lopuiz 

smtp server : smtp.office365.com

wazuh configuration u mean email  configuration ?? in wazuh ?

**Comment by Lopuiz** [comment]
Hello @coopjab 

Sorry, I didn't explain well.

It may you only configured Wazuh (ossec.conf), but you have to authenticate to send mails using an Office 365 account.

If I am right, you can follow our documentation to configure [SMTP server with authentication](https://documentation.wazuh.com/3.11/user-manual/manager/manual-email-report/smtp_authentication.html)

If you already did it, I would like to know the SMTP server you configure.

I wait for your answer.

Regards,
Eva

**Comment by coopjab** [comment]
this is my wazuh configuration 
![Screenshot (93)](https://user-images.githubusercontent.com/36020960/76745707-582b1900-679c-11ea-8864-7fbad0fa8768.png)

**Comment by coopjab** [comment]
@Lopuiz 
looking forward for ur solution on my question
thanks

**Comment by coopjab** [comment]
@Lopuiz 

It's saying smtp lost connection wat can be the problem???

![github_pic](https://user-images.githubusercontent.com/36020960/76931969-deb43780-690f-11ea-9de3-e3556b1249a2.png)

**Comment by Lopuiz** [comment]
Hello Coopjab,

The issue seems to be the Postfix configuration or the Office 365 account and, I don't know how to solve it. To help you, I would like to know your Postfix configuration and if the account has the multi-factor authentication.

Regarding your question about the lost connection, I don't think it. The following logs seem due to Postfix can't authenticate with your email account.
`smtp.office365.com offered no supported AUTH mechanisms: 'LOGIN XOAUTH2`

Regards,
Eva

**Comment by coopjab** [comment]
@Lopuiz 
this is my postfix configuration 
![postfix](https://user-images.githubusercontent.com/36020960/76938661-0bbb1700-691d-11ea-94b7-236520389cbc.png)

**Comment by Lopuiz** [comment]
Hello,

Sorry for the late response.

If you couldn't solve it, you can follow this tutorial: [Configure Postfix to Relay Mail to an External SMTP Server on CentOS 7](https://www.lisenet.com/2018/configure-postfix-to-relay-mail-to-an-external-smtp-server-on-centos-7/)

Maybe you need to add `smtpd_banner`, `inet_interfaces`, `inet_protocols`, and `mynetworks` to it works. Also, remember that the email account can't have multi-factor authentication.

I'm sorry I can't be more help. I'll open an issue to improve our documentation.


Regards,
Eva

**Comment by coopjab** [comment]
@Lopuiz 
thanks a lot I will give a try and let u know 
cheers

**Comment by Lopuiz** [comment]
Hello,

I'm going to close this issue for inactivity. If you have more questions you can join our community:
https://wazuh.com/community/

Best regards,
Eva
