### ISSUE TITLE
custom-jira doesn't create any alert??

### ISSUE THREAD

**Issue by tekletade** [wazuh/wazuh#4726]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.1 | Integrations | Manager | Sources | Ubuntu|

I use the process placed in wazuh to ingrate jira with wazuh. https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/
But, I don't see any alert on Jira? help me.

**Comment by 0xN3utr0n** [comment]
Hello @tekletade,
Could you please provide the manager's `ossec.conf` and the script used for the integration?

Kind regards,
Fernando G.

**Comment by tekletade** [comment]
my ossec.conf is  
<integration>
  <name>custom-jira</name>
  <hook_url>https://xxx.atlassian.net/projects/projectname/issues</hook_url>
  <api_key>user@gmail.com:T1Z3RzwGmLGERyPrZcJf9EFB</api_key>
  <alert_format>json</alert_format>
</integration>


and my Custom-jira.py script is

import sys
import json
import requests
from requests.auth import HTTPBasicAuth

# Set the project attributes
project_alias = 'SIEM'
issue_name ='Task'

# Read configuration parameters
alert_file = open(sys.argv[1])
user = sys.argv[2].split(':')[0]
api_key = sys.argv[2].split(':')[1]
hook_url = sys.argv[3]

# Read the alert file
alert_json = json.loads(alert_file.read())
alert_file.close()

# Extract issue fields
alert_level = alert_json['rule']['level']
description = alert_json['rule']['description']
path = alert_json['syscheck']['path']

# Generate request
msg_data = {}
msg_data['fields'] = {}
msg_data['fields']['project'] = {}
msg_data['fields']['project']['key'] = project_alias
msg_data['fields']['summary'] = 'FIM alert on [' + path + ']'
msg_data['fields']['description'] = '- State: ' + description + '\n- Alert level: ' + str(alert_level)
msg_data['fields']['issuetype'] = {}
msg_data['fields']['issuetype']['name'] = issue_name
headers = {'content-type': 'application/json', 'Accept-Charset': 'UTF-8'}

# Send the request
requests.post(hook_url, data=json.dumps(msg_data), headers=headers, auth=(user, api_key))

sys.exit(0)

**Comment by 0xN3utr0n** [comment]
Hello @tekletade,
The script seems to be correct, although I need more information to be completely sure.  

-  The script is located in `/var/ossec/integrations/`, right?
-  Which type of events do you want to send? You didn't provide the `group` field. E.j: 
`<group>syscheck</group>`
- Could you run the command `ls -l /var/ossec/integrations/` in order to see the files permissions?

**Comment by tekletade** [comment]
Yes!  
The my script is located in /var/ossec/integrations/
and I also use the group now <group>syscheck</group> and
when the permission is like this; 
root@user:~# ls -l /var/ossec/integrations
total 44
-rwxr-x--- 1 root root  1165 Mar 13 14:08 custom-jira
-rwxr-x--- 1 root ossec 1165 Mar 13 14:08 custom-jira.py
-rwxr-x--- 1 root ossec 1023 Mar 13 08:34 custom-script
-rwxr-x--- 1 root ossec 1176 Mar 18 07:37 custom-script.py
-rwxr-x--- 1 root ossec 4326 Jan  8 13:13 pagerduty
-rwxr-x--- 1 root ossec 1022 Jan  8 13:14 slack
-rwxr-x--- 1 root ossec 3769 Jan  8 13:13 slack.py
-rwxr-x--- 1 root ossec 1022 Jan  8 13:14 virustotal
-rwxr-x--- 1 root ossec 6442 Jan  8 13:13 virustotal.py

**Comment by 0xN3utr0n** [comment]
Hello @tekletade,
For starters, I apologize for the late response. Could you please provide the output of the following command?
`cat /var/ossec/logs/ossec.log | grep -i integrator`
_this command will report any possible error_

I've ran a custom script with Integrator and everything worked as expected; hence, my guess is your python script is the culprit.

Kind regards,
Fernando G.

**Comment by 0xN3utr0n** [comment]
I'm closing this issue. Feel free to re-open it again if you need more help.

**Comment by alyvusal** [comment]
as helper comment want to add:
name script must start with `custom-` . like `custom-jira`
