### ISSUE TITLE
windows Authentication failure don´t show logged on security events on wazuh

### ISSUE THREAD

**Issue by megajonh** [wazuh/wazuh#4744]
Hello Guys,

My WAZUH versions:
Version v3.11.3 Wazuh Manager and AGENT, this is my configuration on my AGENT:

  <localfile>
    <location>Application</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447 and
      EventID != 4656 and EventID != 4658 and EventID != 4663 and EventID != 4660 and
      EventID != 4670 and EventID != 4690 and EventID != 4703 and EventID != 4907 and
      EventID != 5152 and EventID != 5157 and EventID != 4625 and EventID != 4688 and EventID != 4611]</query>
  </localfile>

  <localfile>
    <location>System</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>

**Comment by megajonh** [comment]
My problem is trying to attempt many failures credentials on windows to registry the event, but this events don't show on security events in wazuh dashboard.

Another config on AGENT same issue.


  <localfile>
    <location>Application</location>
    <log_format>eventlog</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventlog</log_format>
  </localfile>

  <localfile>
    <location>System</location>
    <log_format>eventlog</log_format>
  </localfile>

  <localfile>
    <location>Microsoft-Windows-Sysmon/Operational</location>
    <log_format>eventchannel</log_format>
  </localfile>

  <localfile>
    <location>active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>

Thanks for your help.
Jonathan.

**Comment by Lopuiz** [comment]
Hello

We have noted you wrote in our mailing list: https://groups.google.com/forum/#!topic/wazuh/qEOidWefP5I

My colleague will answer, so I close this issue.

Please, use our mailing list or join our Slack channel for further questions.

Regards,
Eva
