### ISSUE TITLE
Vulnerability Detector: NVD feed support for Linux agents

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#4749]
### Requirements

- Prevent false positives
- NVD feed analyzer must use the other vendor feeds (Canonical, RHEL, ALAS) to enhance its output (find patches).
- All the vulnerability metadata must be included in the database and later on in the alert object.
- A summary alert must be triggered after each agent scan, including: Scan timestamp, vulnerabilities analyzed per feed, positives matches found per feed.
- The feed must be only downloaded if there is a newer version compared with the version in the local DB.
- Do not forget to include unit tests and integration tests as part of the development
- Syscollector must analyze the package name and generate the CPE if possible. The generated CPE will be stored in agent DB.

### TBD

A) NVD feed and other vendors feed must work simultaneously. It's on user decision to have one or more feeds enabled. Said so, non NVD feeds disable means they won't generate alerts, but they must be still downloaded cause NVD needs the patches info from those feeds to prevent false positives.
B) Only use NVD as source of truth and do not use Canonical, RHEL or ALAS as the primary source. 

### Configuration

Current NVD configuration block will be reused. All the OS distributions and versions will be enabled by default. The user should be able to disable the scan for a specific OS.

```
<provider name="nvd">
  <enabled>yes</enabled>
  <update_from_year>2010</update_from_year>
  <update_interval>1h</update_interval>
  <os enable="yes|no">wheezy|stretch|...|xenial|bionic..|santiago|maipo..|al1|al2..|centos7|centos8</os>
  <os enable="yes|no">wheezy|stretch|...|xenial|bionic..|santiago|maipo..|al1|al2..|centos7|centos8</os>
</provider>
```

### Flowchart

![NVD Linux Wazuh](https://user-images.githubusercontent.com/1519428/76859789-43ad5600-685a-11ea-9d92-aa248e613914.png)

**Comment by chemamartinez** [comment]
Main development branch: [4749-vuln-NVD](https://github.com/wazuh/wazuh/tree/4749-vuln-NVD)

**Comment by chemamartinez** [comment]
This development was merged at https://github.com/wazuh/wazuh/pull/5097.

Best regards.
