### ISSUE TITLE
Vulnerability Detector: Store the CPE for all inventoried Linux packages

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4761]
### Description

The Syscollector module is in charge of collecting all the installed packages in Wazuh agents. For each package, attributes such as architecture, vendor, source, are collected and stored.

The goal of this issue is to use that data to generate the CPE of each package, which is used to correlate vulnerabilities (CVEs) with affected packages (CPEs) in the NVD.

### Requirements

- Syscollector is responsible to generate that CPE
- It should be sent as a new field in the Syscollector events to the manager
- This development only involves Linux packages (deb & rpm)
- The CPE should not be included as a dynamic field for Syscollector alerts
- Create unit tests for new functions

### Reference

- CPE dictionary: https://nvd.nist.gov/products/cpe

**Comment by TomasTurina** [comment]
## Update:

This story is not going to be done. CPEs can't be obtained from the information provided by `syscollector` for the following reasons:

- The `vendor` doesn't came with the package information. Instead, the maintainer comes.

- The `product` name is not always the same as the name in the NVD database:

  - RPM Packages:

    - In some cases, the NVD has the name of the package. Ex: `automake`, `avahi`, `bind`, `gcc`, `python`.

    - In other cases, it doesn't have the package name. Ex: `python3`.

  - DEB packages:

    - In some cases, the NVD has the name of the source package. Ex: `avahi`.

    - In some cases, it has the name of the binary package. Ex: `automake`, `gcc`, `python`.

    - In other cases, it doesn't have the source name or the binary name of the package. Ex: `python3.7`, `bind9`.

- The `version` is not always the same as the version in the NVD database:

  - Only the 4.71% of the NVD entries that follow the DEB/RPM version format have the review/release number.

  - Only the 0.01% of the NVD entries that follow the DEB/RPM version format have the epoch number.

  - Only the 0.005% of the NVD entries that follow the DEB/RPM version format have both.

- The `update`, `edition`, `language`, `sw_edition`, `target_sw`, `target_hw` and `other` fields aren't always consistent with the data from `syscollector`.
