### ISSUE TITLE
Vulnerability Detector: Populate alerts with the vulnerabilities metadata

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4763]
### Description

The vulnerability detector collects all the vulnerabilities from different sources (NVD, Canonical, RHEL...). Each of those sources provides different information related to the indexed CVEs (severity, references, rationale...)

All that information has to be parsed from the feeds to be stored in the vulnerabilities database. When a package is vulnerable to a specific CVE, the fired alert also must contain that data.

### Requirements

- For each feed listed below, review the downloaded documents, and how vulnerability-detector populates the DB with their content. If any interesting information is not collected. It should be added to the vulnerabilities DB as well as include it as an alert field.

- [ ] NVD feed

- [ ] Canonical feeds

- [ ] Debian feeds

- [ ] RHEL feed

### References

- Canonical feeds: https://people.canonical.com/~ubuntu-security/oval/
- Debian feeds: https://www.debian.org/security/oval/
- RHEL feeds: https://access.redhat.com/security/security-updates/#/cve
- NVD feeds: https://nvd.nist.gov/vuln/data-feeds

**Comment by DProvinciani** [comment]
Adding some useful mindmaps that were created to analyze what information we should add to the alerts.
From these mindmaps, we analyzed the information that is always provided in the feeds and then we evaluated whether is important or not and whether that information will give an extra value to the users.

![mindmap-nvd](https://user-images.githubusercontent.com/5703274/78382027-8ede9d00-75ac-11ea-9724-3dc7a75008e8.png)
![mindmap-rh](https://user-images.githubusercontent.com/5703274/78382033-90a86080-75ac-11ea-8b46-afc2c95bba77.png)
![mindmap-ubuntu-debian](https://user-images.githubusercontent.com/5703274/78382035-91d98d80-75ac-11ea-91c5-f016c6e9bacc.png)

**Comment by chemamartinez** [comment]
Merged #4836 which completes this issue.
