### ISSUE TITLE
Vulnerability Detector: Fixing the version comparator

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#4769]
### Description

In most cases, the vulnerability feeds provide the package version where a specific CVE is fixed. The version comparator at the Vulnerability Detector is used to evaluate that version against the installed one.

The current comparator is not accurate enough due to the following requirements are not met:

- ``deb`` and ``rpm`` packages have different syntax, so it is necessary to use different comparators
- Some parts of the version are not being evaluated

The goal of this issue is the redesign of the version comparison algorithm according to the way Debian and RPM compare the packages.

### Requirements

- Include unit tests for every new function

### Reference

**Debian**
- https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
- https://github.com/oerdnj/dpkg/blob/master/src/enquiry.c

**RPM**
- https://blog.jasonantman.com/2014/07/how-yum-and-rpm-compare-versions/
https://github.com/rpm-software-management/rpm/blob/master/lib/rpmvercmp.c

**Comment by chemamartinez** [comment]
Development branch: [dev-vulndetector-evr_matching](https://github.com/wazuh/wazuh/tree/dev-vulndetector-evr_matching)

**Comment by DProvinciani** [comment]
This issue was completed with the merge of https://github.com/wazuh/wazuh/pull/4874
