### ISSUE TITLE
ossec-analysisd WARNING:  at fim_db_search: Agent '020' Couldn't decode fim sum

### ISSUE THREAD

**Issue by fvaz1906** [wazuh/wazuh#4801]
Hi,

When activating the integrity check in wazuh for windows, it returns the following error message: 

2020/03/27 18:27:51 ossec-analysisd WARNING:  at fim_db_search: Agent '020' Couldn't decode fim sum '{"type":"event","data":{"path":"c:\\tmp\\new' from file 'text document.txt","mode":"real-time","type":"deleted","timestamp":1585344447

can you help me?

**Comment by FernandoCP** [comment]
Hi @fvaz1906!

It seems that the error is that you can't see if the alert is added, modified or deleted.

I want to reproduce the problem to know better what is wrong and give you a good solution. For this, could you tell me what version of windows and what version of wazuh you have?
I would also like to know how you have configured syscheck in your configuration.

Best regards, Fernando.

**Comment by FernandoCP** [comment]
Hi!
I think the problem may be that you have a more up-to-date agent than the manager. Can you confirm that both the agent and the manager are at 3.12?

It's necessary that for everything to work correctly the manager doesn't have a lower version than the agent.

Best regards, Fernando.

**Comment by fvaz1906** [comment]
> Oi!
> Acho que o problema pode ser que você tenha um agente mais atualizado que o gerente. Você pode confirmar que o agente e o gerente estão em 3,12?
> 
> É necessário que, para que tudo funcione corretamente, o gerente não tenha uma versão inferior à do agente.
> 
> Atenciosamente, Fernando.

Hi, Fernando

actually the manager was in a lower version of the agent, i managed to solve the problem with a simple update.

thank you very much for your help.

**Comment by dell390** [comment]
Hello,
i am seen the same issue using manager 3.13 and agentless 
 ossec-analysisd: WARNING: at fim_db_search: Agent '000' Couldn't decode fim sum ':b185b9ff7f80c1ede58b9fcd39a1c730:'

**Comment by gianpaolod** [comment]
> Hello, i am seen the same issue using manager 3.13 and agentless ossec-analysisd: WARNING: at fim_db_search: Agent '000' Couldn't decode fim sum ':b185b9ff7f80c1ede58b9fcd39a1c730:'

I have the same problem, the time is offset by 4 hours, the agentless script (or something else) is not using the time set by Wazuh Manager GUI.

>2023/12/07 19:05:25 wazuh-analysisd: WARNING: at fim_db_search: Agent '000' Couldn't decode fim sum ':6d759a088c884d539f5d72074a83ceb1:' from file '/sbin/wifi'.
2023/12/07 15:05:25 wazuh-agentlessd: INFO: ssh_integrity_check_linux: root@example.com: Finished.
