### ISSUE TITLE
Yum update on CentOS7 switches wazuh-manager from x86_64 to i686

### ISSUE THREAD

**Issue by minorOffense** [wazuh/wazuh#4815]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0-1 | wazuh-manager |  | wazuh-manager.x86_64 | CentOS 7 |

When running updates on CentOS 7 the version number of the i686 version is higher than the 64bit version and so it tries to update to the 32bit version (which doesn't really work that well on a 64bit OS cause all the dependencies are 64bit).

We're using the puppet module and so it keeps trying to replace it over and over. We switched from ensure latest to ensure present and are manually updating the manage for the time being.

I'd suggest either update your 64bit version to match or maybe consider splitting your repos by architecture. Or introduce an architecture line in the package installation. I'm not sure what the best approach is.

```
[root@cfl-prod-mon4 bin]# yum list installed | grep 'wazuh'
wazuh-manager.x86_64                3.12.0-1                   @wazuh
[root@cfl-prod-mon4 bin]# yum list | grep wazuh
wazuh-manager.x86_64                      3.12.0-1                       @wazuh
wazuh-agent.x86_64                        3.12.0-1                       wazuh
wazuh-agent.i386                          3.12.0-2                       wazuh
wazuh-api.x86_64                          3.12.0-1                       wazuh
wazuh-manager.i386                        3.12.0-2                       wazuh
[root@cfl-prod-mon4 bin]# yum update
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.advancedhosters.com
 * epel: fedora-epel.mirrors.tds.net
 * extras: mirror.siena.edu
 * updates: mirrors.gigenet.com
Resolving Dependencies
--> Running transaction check
---> Package wazuh-manager.x86_64 0:3.12.0-1 will be updated
---> Package wazuh-manager.i386 0:3.12.0-2 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

=====================================================================================================================================================================================================================
 Package                                                  Arch                                            Version                                             Repository                                        Size
=====================================================================================================================================================================================================================
Updating:
 wazuh-manager                                            i386                                            3.12.0-2                                             wazuh                                             79 M

Transaction Summary
=====================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 79 M
Is this ok [y/d/N]: n
```

**Comment by gyterpena** [comment]
Had same issue, have about 124 hosts, it happened only on 16 of them. Workaround was to remove 

yum remove wazuh-agent
yum install wazuh-agent

mv -f /var/ossec/etc/ossec.conf.rpmsave /var/ossec/etc/ossec.conf
mv -f /var/ossec/etc/client.keys.rpmsave /var/ossec/etc/client.keys

systemctl start wazuh-agent

**Comment by okynos** [comment]
Hello @minorOffense and @gyterpena,

We have solved such problem a few days ago by releaseasing packages 3.12.0-2 for x64 and i386 architecture. This avoid the architecture switch that you're experiencing with yum.
We recommend you to clean yum's cache in order to get clean repository metadata with `yum clean all` and try to upgrade again.

We will close this issue, feel free to open again if you need more assistance or have any related issue.

Kindly regards.
