### ISSUE TITLE
API 4.0 Problem in PUT /manager/files for CDB lists in error response

### ISSUE THREAD

**Issue by Joanes04** [wazuh/wazuh#4830]
Hi team,

We found an error in the error response of the next endpoint:   `PUT /manager/files`.

When you try to create a file in CDB lists, sending a wrong format in the body, the error response is not related to the error itself.

**Steps**

1. It creates a file with the wrong format, for example with the following format: 

`{ content: 'abc:123' }`

2. We make an API request to the endpoint `PUT 'manager/files'` with the parameters: 

```
{
   path: 'etc/lists/test'
   overwrite: false
}
```
3. The error returned by the API is the following, which is not the expected error for a wrong format of the uploaded file:

```
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1802,
          "message": "Lists file not found",
          "remediation": "Please, use `GET /lists/files` to find all available lists"
        },
        "id": [
          "etc/lists/test"
        ]
      }
    ]
  },
  "message": "Could not upload file"
}
```

**Comment by davidjiglesias** [comment]
When fixing this we have to check why the integration tests did not detect the fail and add a test case if necessary.

**Comment by vicferpoy** [comment]
The correct code is the 1800:

```
1800: {'message': 'Bad format in CDB list {path}'},
```

Our tests did not catch this error because they were wrong as well:

```
    response:
      status_code: 200
      body:
        data:
          affected_items: []
          failed_items:
            - error:
                code: 1802
              id:
                - 'etc/lists/new-list'
          total_affected_items: 0
          total_failed_items: 1
        message: !anystr
```

**Comment by vicferpoy** [comment]
Fixed here: https://github.com/wazuh/wazuh/pull/4868
