### ISSUE TITLE
Let agents auto-enroll to managers to get a connection key

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4833]
|Branch|
|---|
|[dev-agent-enrollment](https://github.com/wazuh/wazuh/compare/dev-agent-enrollment)|

## Main goal

The enrollment (or agent key request) is an extra step that we must do before getting an agent connected to a manager. As a user, we want to avoid this stage: a basic agent setup should only need the manager's address. The agent will request a key to the manager when needed.

## First iteration

1. The **agent service** will inherit the capabilities from _agent-auth_ to connect to a manager via TLS, and request a key. We will deprecate _agent-auth_ but won't remove it yet.
2. The *enrollment service* in the manager will need to work in any cluster's worker, and will forward the requests from agents to the cluster's master. The master is the only node that can manage agent keys.

**Comment by snaow** [comment]
Merged.
https://github.com/wazuh/wazuh/pull/5609

Congratz team. Huge win.
