### ISSUE TITLE
CRITICAL: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Permission denied'.

### ISSUE THREAD

**Issue by int80h** [wazuh/wazuh#4848]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.4-1| ossec-agentd | Agent | Packages | Debian Buster 10.3 |

I have two machines that failed to start because of the error "CRITICAL: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Permission denied'."  The first one is a physical machine which exhibited that error when running 3.12.0 and returned to normal after downgrading to 3.11.4-1.  The second is is a VM running 3.11.4-1 and continues to show this behavior.

After setting analysisd.debug, agent.debug, and wazuh_db.debug to 2 and restarting the agent on the second machine running 3.11.4-1, I got the following output in /var/ossec/logs/ossec.log:

2020/04/04 07:46:45 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2020/04/04 07:46:45 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2020/04/04 07:46:45 ossec-execd: INFO: (1350): Active response disabled.
2020/04/04 07:46:45 ossec-execd: INFO: Started (pid: 2395).
2020/04/04 07:46:45 ossec-agentd[2401] agentd.c:51 at AgentdStart(): INFO: Using notify time: 10 and max time to reconnect: 60
2020/04/04 07:46:45 ossec-agentd[2401] agentd.c:56 at AgentdStart(): INFO: Version detected -> Linux |$hostname |5.4.0-0.bpo.3-amd64 |#1 SMP Debian 5.4.13-1~bpo10+1 (2020-02-07) |x86_64 [Debian GNU/Linux|debian: 10 (buster)] - Wazuh v3.11.4
2020/04/04 07:46:45 ossec-agentd[2401] agentd.c:72 at AgentdStart(): CRITICAL: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Permission denied'.
2020/04/04 07:46:45 rootcheck: INFO: Rootcheck disabled.
2020/04/04 07:46:45 ossec-logcollector: INFO: (1905): No file configured to monitor.
2020/04/04 07:46:45 wazuh-modulesd: INFO: Process started.
2020/04/04 07:46:45 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2020/04/04 07:46:45 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2020/04/04 07:46:45 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2020/04/04 07:46:45 wazuh-modulesd:syscollector: INFO: Module disabled. Exiting...
2020/04/04 07:46:45 sca: INFO: Module disabled. Exiting.
2020/04/04 07:46:45 wazuh-modulesd:control: INFO: Starting control thread.

**Comment by vikman90** [comment]
Hi @int80h,

Sorry for the late reply. Just as you saw, that _CRITICAL_ error is preventing the agent's components from communicating with the agent service. According to the log description, it's due to a permissions issue.

Please check the following points:

1. The user and the group `ossec` must exist in the system:

```sh
# grep ossec /etc/{passwd,group}
/etc/passwd:ossec:x:994:990::/var/ossec:/sbin/nologin
/etc/group:ossec:x:990:ossec
```

2. We expect the following files have these permissions:
```sh
# ls -ld /var/ossec{,/queue{,/ossec{,/queue}}}
drwxr-x---. 15 root  ossec 181 Apr 22 13:35 /var/ossec
drwxr-x---.  7 root  ossec  68 Apr 22 13:35 /var/ossec/queue
drwxrwx---.  2 ossec ossec 116 Apr 22 13:42 /var/ossec/queue/ossec
srw-rw----.  1 ossec ossec   0 Apr 22 13:42 /var/ossec/queue/ossec/queue
```

Could you share with us the result of running these checks in your systems?

`ossec-agentd` runs as user `ossec`, and it must have permissions enough to create a socket in _/var/ossec/queue/ossec_.

Best regards.

**Comment by vikman90** [comment]
Closing this issue as it's inactive and we've been unable to reproduce this problem.

@int80h should this issue persist in your environment, feel free to reopen it, and continue the conversation.

Best regards.
