### ISSUE TITLE
Vulnerability detector: Can't get Ubuntu/Canonical feeds because of xml.bz2 files

### ISSUE THREAD

**Issue by jpcozar** [wazuh/wazuh#4855]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0 | Wazuh Manager | Manager | Packages | Ubuntu 18.04 |

I was trying to get feeds from Canonical online and ossec.log said:
`2020/04/06 11:55:42 wazuh-modulesd:vulnerability-detector WARNING:  (5400): Ubuntu Trusty database could not be fetched.
2020/04/06 11:55:42 wazuh-modulesd:vulnerability-detector DEBUG:  (5437): Failed when updating 'canonical TRUSTY' database. Retrying in 300 seconds.
2020/04/06 11:55:31 wazuh-modulesd:vulnerability-detector WARNING:  (5400): Ubuntu Xenial database could not be fetched.
2020/04/06 11:55:31 wazuh-modulesd:vulnerability-detector DEBUG:  (5437): Failed when updating 'canonical XENIAL' database. Retrying in 300 seconds`

So I tried and offline approach and it wasn't working neither.

 I went to `https://people.canonical.com/~ubuntu-security/oval/` and  there it says that xml files are now compressed with  **bz2** . So these files in Wazuh documentation:
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.trusty.cve.oval.xml

are really 
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml.bz2
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.xenial.cve.oval.xml.bz2
https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.trusty.cve.oval.xml.bz2

So I was able to fix offline updates doing a previous uncompression of downloaded files in my cron task script but I guess someone of Wazuh team should fix code to do such uncompression so online feeding is working too for Ubuntu  and correct documention about they are now xml.bz2 files.
In debian xml files are still plain xml files.
Thank you in advance.

--

**Comment by jesusjimsa** [comment]
Hello, @jpcozar.

We have already been working on this. The solution to this problem will be included in Wazuh 3.12.1.

Best regards,
Jesús.

**Comment by jesusjimsa** [comment]
We fixed it in this PR: #4834.

We are currently preparing the release of Wazuh 3.12.1, that will include the fixes done in #4834.

Best regards,
Jesús.

**Comment by jpcozar** [comment]
Ok thanks!
