### ISSUE TITLE
Is ZeroMQ is available?

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#486]
Hi, I was looking at the docs and there are settings for a zeromq output. I tried using it, but nothing happens. Nothing comes up in the logs. Looking at the source code it looks like it needs to be enabled during the build. What is the status of this feature?

**Comment by albertomn86** [comment]
Hi @rossengeorgiev 

To use ZeroMQ you need to enable it during compilation from source code using 
`make TARGET=server USE_ZEROMQ=yes`. 

Once the compilation is finished you can install/upgrade using the script `install.sh` and configure your `ossec.conf` file: 

```
<global>
     ...
    <zeromq_output>yes</zeromq_output>
    <zeromq_uri>ZEROMQ_SOCKET_PATH</zeromq_uri>
</global>
```

If you have any additional questions or require further clarification, please, let me know.

Best regards.

**Comment by rossengeorgiev** [comment]
Hi @albertomn86, I see, thanks! What would I need to do to build a RPM?
