### ISSUE TITLE
Windows remote upgrade process adds extra carriage returns to incoming WPK file

### ISSUE THREAD

**Issue by rtkjbillo** [wazuh/wazuh#487]
I'm trying to get the remote upgrade functionality of Wazuh to work with a custom WPK being sent to a Windows client. I've followed the instructions at https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/create-custom-wpk.html to generate a CA and certificate, build and sign a WPK package and use `agent_upgrade` to send it to the appropriate client. 

This works correctly for a Linux client, but when the file is received on a Windows system, it appears that `ossec-agent` on the Windows host is introducing carriage return characters (`\r`) before each newline (`\n`) character in the WPK file. 

This causes the SHA1 checksum to mismatch - the server indicates `Error 1715: Error sending WPK file: ok` followed by a SHA1 sum that doesn't match the one of the WPK file on the server.

I have tried converting all files in the WPK package to use `\r\n` line endings with `unix2dos` but inspecting the sequence encoded in the WPK received on the Windows client with a hex editor, this becomes `\r\r\n`. 

Here are my reproduction steps with a very simple upgrade script (it doesn't actually do an upgrade, just write some logging information.)

# Linux and Windows versions

Linux client (Ubuntu 16.04)
```
root@ip-172-31-40-192:/var/ossec/bin# ./ossec-agentd -h

Wazuh v3.2.2 - Wazuh Inc. (info@wazuh.com)
```

Windows client (Windows Server 2016, installed from MSI at https://documentation.wazuh.com/current/installation-guide/packages-list/index.html)
```
PS C:\Program Files (x86)\ossec-agent> .\ossec-agent.exe -h

Wazuh ossec-agent v3.2.1 .
```

Linux server (Ubuntu 16.04, installed with apt from repo at packages.wazuh.com)
```
root@ip-172-31-30-25:/var/ossec/bin# ./ossec-syscheckd -h

Wazuh v3.2.1 - Wazuh Inc. (info@wazuh.com)
```

# Generate keys and construct bare-bones package on server

```
sudo -s
mkdir -p /root/repro; cd /root/repro
openssl req -x509 -new -nodes -newkey rsa:2048 -keyout wpk_root.key -out wpk_root.pem -batch
openssl req -new -nodes -newkey rsa:2048 -keyout wpkcert.key -out wpkcert.csr -subj '/C=US/ST=CA/O=Wazuh'
openssl x509 -req -days 365 -in wpkcert.csr -CA wpk_root.pem -CAkey wpk_root.key -out wpkcert.pem -CAcreateserial

# Download the latest stable Wazuh source for the contrib scripts
wget https://github.com/wazuh/wazuh/archive/stable.zip
unzip stable.zip

# Create an empty package directory and add upgrade scripts for both Windows and Linux
mkdir -p /root/repro/package; cd /root/repro/package

cat <<EOF > upgrade.sh
#!/bin/bash
logger -t wazuh-upgrade "Started first phase upgrade"
. /etc/ossec-init.conf 2> /dev/null || exit 1
(sleep 5 && chmod +x \$DIRECTORY/var/upgrade/*.sh && \$DIRECTORY/var/upgrade/upgrade2.sh) >/dev/null 2>&1 &
logger -t wazuh-upgrade "Exiting upgrade.sh"
EOF

cat <<EOF > upgrade2.sh
#!/bin/bash
logger -t wazuh-upgrade "Started second phase upgrade"
. /etc/ossec-init.conf
\${DIRECTORY}/bin/ossec-control restart
echo -ne "0" > \${DIRECTORY}/var/upgrade/upgrade_result
logger -t wazuh-upgrade "Finished second phase upgrade"
EOF

chmod +x upgrade.sh upgrade2.sh

cat <<EOF > upgrade.bat
@ECHO off

IF "%1"=="B" GOTO background

START /B upgrade\upgrade.bat B
GOTO end

:background
SLEEP 5 2> NUL || ping -n 5 127.0.0.1 > NUL
powershell -ExecutionPolicy ByPass -File upgrade\upgrade2.ps1

:end
EOF

cat <<EOF > upgrade2.ps1
Write-Output "\$(Get-Date -format u) - ran upgrade script" > C:\upgraded.txt
Restart-Service -Name "ossec-agent" -ErrorAction SilentlyContinue
Write-Output "0" | out-file ".\upgrade\upgrade_result" -encoding ascii
EOF

# Ensure Windows files have Windows line endings
unix2dos upgrade.bat
unix2dos upgrade2.ps1

# Build package with wpkpack.py in /root/repro/package directory
/root/repro/wazuh-stable/contrib/agent-upgrade/wpkpack.py /root/repro/myagent.wpk /root/repro/wpkcert.pem /root/repro/wpkcert.key *
```

# Attempted upgrade process

Ensure wpk_root.pem is copied to clients and wazuh-agent restarted.
Deploy upgrade to clients from manager

`/var/ossec/bin/agent_upgrade -a 004 -f /root/repro/myagent.wpk -x upgrade.sh`

Agent upgraded successfully.

`/var/ossec/bin/agent_upgrade -a 002 -f /root/repro/myagent.wpk -x upgrade.sh`

Output:

`Error 1715: Error sending WPK file: ok 2fb26b39b5e487600025c0257dc4413d5dfeda78`

SHA1 of myagent.wpk on server:

```
sha1sum /root/repro/myagent.wpk
8bc125c2ee7511adceb69a206c8e5c50b3f18d69  /root/repro/myagent.wpk
```

SHA1 of myagent.wpk on Linux client:

```
sha1sum /var/ossec/var/incoming/myagent.wpk
8bc125c2ee7511adceb69a206c8e5c50b3f18d69  /var/ossec/var/incoming/myagent.wpk
```

SHA1 of myagent.wpk on Windows client:

```
Get-FileHash "C:\Program Files (x86)\ossec-agent\incoming\myagent.wpk" -Algorithm SHA1
SHA1            2FB26B39B5E487600025C0257DC4413D5DFEDA78
```

Please let me know if I can provide any more relevant information. I've also tried building the WPK package on Windows with wpkpack.py (with Python 2.7/latest "cryptography" from pip), then copying the result back to the Wazuh server and deploying it to a Windows client, but the same problem occurs.

Thanks!

**Comment by vikman90** [comment]
Hi @rtkjbillo,

I have just seen a typo in the corresponding line: the WPK was delivered as a text file instead of a binary file.

I have fixed it in this commit: https://github.com/wazuh/wazuh/commit/ccb4757ffdeb56151e00ea9826d67b617798fea6

Please pull your branch 3.2 and let me know if this fixed your issue.

Thank you very much for reporting this issue!
Best regards.

**Comment by rtkjbillo** [comment]
@vikman90 Thanks very much for the quick response! 

I can confirm that applying your patch to the Wazuh server was successful - the WPK file delivered to the Windows client matched the correct checksum, and the client was able to execute the sample .bat/.ps1 scripts correctly.

**Comment by vikman90** [comment]
Hi @rtkjbillo,

Thanks for confirming that that patch fixes the problem.

Let me close this issue.
Cheers,
