### ISSUE TITLE
Support null value discard for general decoder

### ISSUE THREAD

**Issue by raymanound** [wazuh/wazuh#4876]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.1 | Decoder| Manager | Packages| Ubuntu |

Wazuh support to discard null value for json now by json_null_field but it is better if it can support general decoder as well. Because it is difficult to avoid capturing null value like such format - https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/traffic-log-fields.html.

Besides, I don't think following regex pattern from the online document is supported in wazuh?
`<regex> [+-]?(\d+(\.\d+)?|\.\d+)([eE][+-]?\d+)? </regex>`
https://documentation.wazuh.com/3.12/user-manual/ruleset/ruleset-xml-syntax/decoders.html

**Comment by Lopuiz** [comment]
Hello,

I don't understand your request. Using XML decoders, the users decided which fields want to print in the alerts.

Could you facilities more information and some Palo Alto log example?

Regarding the regex, yes, it doesn't work. I'll open an issue to remove it from the documentation.

Thanks for your feedback!

Best regards,
Eva

**Comment by Lopuiz** [comment]
Hello,

I'm going to close this issue for inactivity. If you have further questions, join our community:
https://wazuh.com/community/

Best regards,
Eva
