### ISSUE TITLE
 Local configuration (ossec.conf) localfile <out_format> tag is not work

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#4877]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
3.12.0 | agent | Manager | Packages | CentOS

Hello,yesterday I have updated the wazuh manager/api/agent version from 3.9.2 to 3.12.0,it's  difficult.I have solved a lot of problems.

But when I check custom alert,I find there is noting about it.

I create a decoder to resolve dns application named "bind",and I modify the agent's ossec.conf

```
<localfile>    
    <location>/app/log/bind/queries.log</location>    
    <log_format>syslog</log_format>    
    <target>agent</target>    
    <out_format>agent_dns\|$(log)</out_format>
</localfile>
```
It will add strings "agent_dns" at the log record head when the agent's version is 3.9.2,So,I can use custom decoder to resolve it,

The Original Record log like it:

`11-Feb-2020 18:58:17.875 queries: info: client 192.168.124.185#59706 (113-123-28-139.nhost.00cdn.com): query: 113-123-28-139.nhost.00cdn.com IN A + (192.168.10.240)`

And after I use _<out_format>agent_dns\|$(log)</out_format>_,the  Record log like it:

`agent_dns|11-Feb-2020 18:58:17.875 queries: info: client 192.168.124.185#59706 (113-123-28-139.nhost.00cdn.com): query: 113-123-28-139.nhost.00cdn.com IN A + (192.168.10.240)`

but when I upgrade it to 3.10.2,I never change the ossec.conf,the <out_format> tag seems to be useless

I try to delete "target" tag,it's not work,too!

And I try to modify <out_format> like document
`<out_format>$(timestamp %Y-%m-%d %H:%M:%S): $(log)</out_format>`

it's not work,too!

So I want to know if the <out_format> tag is not work?

**Comment by FernandoCP** [comment]
Hi @xufengnian!

I've been testing the problem you mentioned and it seems that it's a bug that affects 3.12 and is produced by this fix we made. https://github.com/wazuh/wazuh/pull/4696 

We really appreciate the information, it helps us keep trying to improve Wazuh. We are working on it and will do so as soon as our workflow allows.

I'm sorry I couldn't be more helpful. 
Best regards, Fernando.

**Comment by vikman90** [comment]
@xufengnian we've just merged the fix to this bug into branch _3.12_. It will be available in the next release.

Thank you again for reporting this bug. Kudos to @FernandoCP for fixing that!
Cheers!
