### ISSUE TITLE
Various Wazuh Python scripts don't work on RHEL/CentOS 8 (including oscap.py)

### ISSUE THREAD

**Issue by mattvw** [wazuh/wazuh#4879]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0-2 | wazuh-modulesd | Agent | Packages | RHEL/CentOS 8 |
| 3.12.0-2 | wazuh-modulesd | Manager/API | Packages | RHEL/CentOS 8 |

I've found that there are various Python scripts used internally by Wazuh that will not work in default installs of RHEL/CentOS 8. For sure, I know this is a problem with the [oscap.py](https://github.com/wazuh/wazuh/blob/master/wodles/oscap/oscap.py) wrapper script that is used for the OpenSCAP checks on the Agent and Manager systems. There also appears to be other Python scripts in the Agent install and in only the Manager/API install that also will not work on RHEL/CentOS 8 (I've included a preliminary list below).

Basically the issue is that you are using the 'python' shebang/env in these scripts. By default, there is no unversioned 'python' executable in RHEL/CentOS 8 (see [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-python3_configuring-basic-system-settings#python_versions) and [here](https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/)). Instead, it is required that you use 'python2' or 'python3' explicitly. It is possible to set up 'python' to point to 'python2' or 'python3' but it is not recommended. This aligns with the recommendations in upstream [PEP 394](https://www.python.org/dev/peps/pep-0394/).

For example, the use of 'python' causes the oscap.py script to fail completely on a RHEL 8 agent as it is unable to find the 'python' executable. In ossec.log on said agent, it just shows:

`2020/04/08 07:23:08 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...`

When running the script manually with all the options that were used on a RHEL 7 agent:

```
[root@<RHEL 8 agent> ossec]# pwd
/var/ossec
[root@<RHEL 8 agent> ossec]# python /var/ossec/wodles/oscap/oscap.py --xccdf ssg-rhel8-ds.xml --profiles xccdf_org.ssgproject.content_profile_standard
-bash: python: command not found
[root@<RHEL 8 agent> ossec]# /var/ossec/wodles/oscap/oscap.py --xccdf ssg-rhel8-ds.xml --profiles xccdf_org.ssgproject.content_profile_standard 
/usr/bin/env: ‘python’: No such file or directory
[root@<RHEL 8 agent> ossec]# ls -l wodles/oscap/content/ssg-rhel8-ds.xml
-rw-r----- 1 root ossec 14919015 Apr  4 11:20 wodles/oscap/content/ssg-rhel8-ds.xml
```

IMO, I believe a quick and easy (initial) fix ("famous last words") would be to simply change 'python' to either 'python2' or 'python3' in each of the affected scripts. Preferable to use 'python3' unless the script only works with 'python2'.

If any of the scripts depend on Python 2 still, a longer-term fix would be to make these scripts Python 3 compatible. This is especially the case given that Python 2 support is being found in less and less OS's since it is already EOL upstream. RHEL 8 will only be supporting Python 2 until June 2024 (see python 2.7 in table [here](https://access.redhat.com/support/policy/updates/rhel8-app-streams-life-cycle)), rather than the normal full 10-year lifespan. I wouldn't be surprised if we stop seeing Python 2 completely in newer OS releases, like Ubuntu 20.04 LTS (coming out later this month). It would be ***_greatly_*** preferred from our POV not to have to install Python 2 on all our RHEL 8 (and other) agents, given the limited support lifespan for it.

Here's a list of the scripts I found on the Agent install that use 'python':

- [wodles/oscap/oscap.py](https://github.com/wazuh/wazuh/blob/master/wodles/oscap/oscap.py)
- [wodles/docker-listener/DockerListener.py](https://github.com/wazuh/wazuh/blob/master/wodles/docker-listener/DockerListener.py)
- [wodles/aws/aws-s3.py](https://github.com/wazuh/wazuh/blob/master/wodles/aws/aws_s3.py)
- [active-response/kaspersky.py](https://github.com/wazuh/wazuh/blob/master/active-response/kaspersky.py)

Here's ones that I found on the Manager/API install only (on top of the Agent ones above):

-  [API] [examples/api-client.py](https://github.com/wazuh/wazuh-api/blob/master/examples/api-client.py)
- [API] [examples/api-register-agent.py](https://github.com/wazuh/wazuh-api/blob/master/examples/api-register-agent.py)
- [API] [models/wazuh-api.py](https://github.com/wazuh/wazuh-api/blob/master/models/wazuh-api.py)
- [framework/scripts/agent_upgrade.py](https://github.com/wazuh/wazuh/blob/master/framework/scripts/agent_upgrade.py)
- [framework/scripts/update_ruleset.py](https://github.com/wazuh/wazuh/blob/master/framework/scripts/update_ruleset.py)
- [framework/wazuh/cdb_list.py](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/cdb_list.py)
- [framework/wazuh/security_configuration_assessment.py](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/security_configuration_assessment.py)
- [integrations/slack](https://github.com/wazuh/wazuh/blob/master/integrations/slack)
- [integrations/virustotal](https://github.com/wazuh/wazuh/blob/master/integrations/virustotal)

(Note: I'm not listing all those found within framework/python/lib/python3.7/. I'm not sure if these use the system Python, but there are quite a few in there that are calling the unversioned 'python'.)

This is **not** an exhaustive list at all. I'm **sure** there are others that I've missed. 

The oscap.py script would be our highest priority to get fixed (easy fix is fine), since that's what we're interested in using now (and my guess is the most popular of the affected scripts).

Let me know if there's any other details I can provide that would help.

Thank you!

**Comment by vikman90** [comment]
Hi @mattvv,

Thank you for opening this issue. If ain't wrong, `python` always refers to Python 2, and `python3` to Python 3.

Here is a point where we have to decide what version to support primarily: using Python 2 will work on RHEL 6 and 7 (by default) while using Python 3 will work on RHEL 7 and 8. RHEL 6 brings no Python 3 out-of-the-box, and RHEL 8 does not bring Python 2.

Maybe we could use a custom version wrapper to detect the version of Python that is installed on the host, and run the script with the correct version.

Let me add this to the roadmap to take a deeper look at it.

Best regards.

**Comment by mattvw** [comment]
Hello,

Any thoughts and/or progress on getting this fixed in Wazuh (in some manner)?

I also just wanted to add that it looks like the same issues will show up in Ubuntu 20.04 LTS (which came out last month), as they also will not provide the 'python' binary by default on fresh installs. See: https://wiki.ubuntu.com/FocalFossa/ReleaseNotes#Python3_by_default.

Python 2 can be installed but only from universe, so it doesn't receive the same support from Ubuntu/Canonical as most packages (nor is the universe repo enabled by default). 'python2' is used explicitly for anything that requires Python 2 still.
Also, it seems that you can get the 'python' binary by installing another package, but that only makes 'python' point to 'python3'. So, it only seems possible to make 'python' point to 'python2' if it's added in manually.

So, it seems like new default installs of both RHEL 8 **AND** Ubuntu 20.04 LTS will run into the same issues with these scripts on both Manager and Agent installs.

I will also note that RHEL 6 will become EOL later this year (6 months from this Saturday), so I'm not sure that you will have to provide much support for it going forward.

As I mentioned, it still makes the most sense to me just make everything work with Python 3 and call 'python3' in the scripts instead of 'python' for best compatibility. Using 'python3' explicitly is the recommended way (by upstream) to call Python anyways now (so we don't run into this 'python' mess again when newer major Python versions come out). Or you could use a wrapper to identify RHEL 6 and use 'python2' to call the scripts and then use 'python3' everywhere else.

Thank you for your help.

**Comment by vikman90** [comment]
@mattvw Apologies, we haven't been able to work on this yet.

Let me answer some questions and raise some ideas:

### Manager side

Some of the files mentioned are never executed directly. They are wrapped:
|Script|Executable wrapper|
|---|---|
|wodles/oscap/oscap.py|wodles/oscap/oscap|
|wodles/docker-listener/DockerListener.py|wodles/docker-listener/DockerListener|
|wodles/aws/aws-s3.py|wodles/aws/aws-s3|
|active-response/kaspersky.py|active-response/kaspersky.sh|
|integrations/slack.py|integrations/slack|
|integrations/virustotal.py|integrations/virustotal|

The wrapper makes the build-in Python 3 interpreter execute the scripts. So that should not be a problem.

### Agent side

On the other hand, the scripts installed in the agent have no wrapper, and here is the problem.

The scripts themself should be compatible with Python 2.6+. Regarding your phrase:
> RHEL 6 will become EOL later this year.

We are still offering support for CentOS 5. In fact, I remember that we have compiled Wazuh on CentOS 3 and 4 😂.

The thing is that I think we should continue supporting Python 2, though operating systems continue moving to Python 3. So I think we have the following options:

1. Support Python2: set shebang to `python2`.
2. Support Python3: set shebang to `python3`.
3. Implement a wrapper that would find Python 2 or Python 3 in the system.

## Workaround

In the meantime, I've been investigating a couple of workarounds, if your system has no `python` interpreter:

### RHEL/CentOS 8

Set an alternative command for `python` to Python2 or Python3:
```sh
alternatives --set python /usr/bin/python3
```

### Ubuntu 20.04 Focal Fossa
```sh
apt install python-is-python3
```

Hope this helps you. We will discuss a solution as soon as possible.

Best regards.

**Comment by mattvw** [comment]
Hello @vikman90,

Just wanted to check in to see if there has been any progress or further discussion on this issue?

From our point of view, I think it'd be best to go with option 3, where the wrapper script would prefer python3 but would then fall back to python2 if python3 isn't installed (for older systems). This would future-proof the scripts, while still allowing older systems that only provide Python 2.x to work. This would mean the scripts would have to all be python3 compatible as well, of course (or is that already the case now?).

As I've mentioned, there is ZERO support for Python 2.x in upstream and Ubuntu 20.04+ (meaning NO fixes for security vulnerabilities) and there is only a limited support time span (only until March 2024) for Python 2.x in RHEL/CentOS 8, even though RHEL/CentOS 8 itself is supported until 2029 (currently *only* critical security issues are being fixed, with no security updates after March 2024).

Given this, we would ***greatly*** prefer not being forced to install Python 2.x on Ubuntu 20.04 and RHEL/CentOS 8 systems with Wazuh agent installed (eventually all our systems), as it's either already EOL or will be EOL within the OS lifespan. This would be a bad security practice to follow, IMO. Especially when it would just be to make a security-centric product like Wazuh work.. ;)

So, I think using a wrapper that preferred python3, with a fallback to python2, would be MUCH better than forcing the use of Python 2 (or Python 3) for the scripts. Just my view!

Thank you for your help with this!

**Comment by vikman90** [comment]
@mattvw I agree with you. I think that is the option we will choose. On the other hand, the workaround I proposed should run Python 3.

I'm sorry we have not been able to schedule this issue yet. We will fix it as soon as possible.

Best regards.

**Comment by vikman90** [comment]
Hi @mattvw,

Finally, we've normalized the module script shebangs (issue #9128, PR #12150). So, this is the current status:

- OpenSCAP integration (`oscap.py`) has been deprecated.
- Docker Listener script (`DockerListener.py`) has been normalized.
- The rest of the module scripts were already normalized.
- Integrations run on the manager-side only, which has Python 3 embedded.
- The Kaspersky Active Response runs on a native module that selects the Python version available.

Let me close this issue. Should you have any questions or concerns, feel free to reopen it.
Best regards.
