### ISSUE TITLE
Remote agent upgrade fail

### ISSUE THREAD

**Issue by mi-cha-el** [wazuh/wazuh#4887]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-manager 3.12.2-1 | agent_upgrade | Manager | Packages | Debian 9.12 |

When trying to upgrade remotely an agent (from 3.12.0 to 3.12.2) with the agent_upgrade utility, it fails with the following error :

> ./agent_upgrade -a 141                                Internal error: 'utf-8' codec can't decode byte 0x82 in position 89: invalid start byte

The target agent is running under Microsoft Windows Server 2008 Standard Edition Service Pack 2. Other upgrades with the same os and versions were successful.
Target server name is  : SRV-BILDMN

**Comment by FernandoCP** [comment]
Hi @mi-cha-el !

That error is that in some file there is some character that cannot be decoded with utf-8, for example, a character with a tilde.
Do you remember modifying any file in that agent with some special character?
If you can give me more information about this I can give you better help.

I hope this helps you.
Best regards, Fernando.

**Comment by FernandoCP** [comment]
Hi! 

You can try running the program with the `-d` option, to enable debugging messages and track the error, like this:
`agent_upgrade -a 141 -d`

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,
Thank you for your help.
When I install a new agent, the only file I manually modify is local_internal_options.conf and I checked it does not contain any special character right now : 
```
# local_internal_options.conf
#
# This file should be handled with care. It contains
# run time modifications that can affect the use
# of OSSEC. Only change it if you know what you
# are doing. Look first at ossec.conf
# for most of the things you want to change.
#
# This file will not be overwritten during upgrades
# but will be removed when the agent is un-installed.
wazuh_command.remote_commands=1
```
Here is the result of a new upgrade attempt with the debug option : 
```
./agent_upgrade -a 141 -d
Manager version: 3.12.2
Agent version: Wazuh v3.12.0
Agent new version: v3.12.2
WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.12.2_windows.wpk - SHA1SUM: 88db74903b609563c94bc28fdd251c540ce0fbef
Upgrade PKG: wazuh_agent_v3.12.2_windows.wpk (2948.7138671875 KB)
MSG SENT: 141 com lock_restart -1
RESPONSE: ok 
MSG SENT: 141 com open wb wazuh_agent_v3.12.2_windows.wpk
RESPONSE: ok 
MSG SENT: 141 com lock_restart -1
RESPONSE: ok 
Chunk size: 512 bytes
Sending: /var/ossec/var/upgrade/wazuh_agent_v3.12.2_windows.wpk
MSG SENT: 141 com close wazuh_agent_v3.12.2_windows.wpk
RESPONSE: ok 
MSG SENT: 141 com sha1 wazuh_agent_v3.12.2_windows.wpk
RESPONSE: ok 88db74903b609563c94bc28fdd251c540ce0fbef
WPK file sent
MSG SENT: 141 com upgrade wazuh_agent_v3.12.2_windows.wpk upgrade.bat
Internal error: 'utf-8' codec can't decode byte 0x82 in position 89: invalid start byte
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.12.2-py3.7.egg/wazuh/agent.py", line 2177, in upgrade
    data = s.receive().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 89: invalid start byte
zsh: exit 1     ./agent_upgrade -a 141 -d
```
And here is the upgrade.log file found in \upgrade : 
```
2020-04-14 11:02:41Z - Current version: v3.12.0
2020-04-14 11:02:41Z - Generating backup.
2020-04-14 11:02:42Z - Trying to stop Wazuh service again. Remaining attempts: 5.
2020-04-14 11:02:45Z - Starting upgrade processs.
2020-04-14 11:02:45Z - Waiting for the installation end.
2020-04-14 11:02:47Z - Waiting for the installation end.
2020-04-14 11:02:49Z - Waiting for the installation end.
2020-04-14 11:02:51Z - Waiting for the installation end.
2020-04-14 11:02:53Z - Waiting for the installation end.
2020-04-14 11:02:55Z - Restarting Wazuh service.
2020-04-14 11:02:55Z - Installation finished.
2020-04-14 11:02:55Z - Process ID: 13128
2020-04-14 11:02:55Z - Reading status file: status='connected'
2020-04-14 11:02:55Z - Upgrade finished successfully.
2020-04-14 11:02:55Z - New version: v3.12.0
```
On the agent side, which other file should I check for an unusual character ?

**Comment by FernandoCP** [comment]
Hi @mi-cha-el!

First of all, I'm sorry for the late reply.

You can try going to the file `/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.12.2-py3.7.egg/wazuh/agent.py` and change the line 2177 `´data = s.receive().decode()´` to `data = s.receive().decode(errors='replace')`. And could you show me the result? 

This will help me to narrow down the error and give you a solution as soon as possible.

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

Here is the result : 

> ./agent_upgrade -a 141 -d
> Manager version: 3.12.2
> Agent version: Wazuh v3.12.0
> Agent new version: v3.12.2
> WPK file already downloaded: /var/ossec/var/upgrade/wazuh_agent_v3.12.2_windows.wpk - SHA1SUM: 88db74903b609563c94bc28fdd251c540ce0fbef
> Upgrade PKG: wazuh_agent_v3.12.2_windows.wpk (2948.7138671875 KB)
> MSG SENT: 141 com lock_restart -1
> RESPONSE: ok 
> MSG SENT: 141 com open wb wazuh_agent_v3.12.2_windows.wpk
> RESPONSE: ok 
> MSG SENT: 141 com lock_restart -1
> RESPONSE: ok 
> Chunk size: 512 bytes
> Sending: /var/ossec/var/upgrade/wazuh_agent_v3.12.2_windows.wpk
> MSG SENT: 141 com close wazuh_agent_v3.12.2_windows.wpk
> RESPONSE: ok 
> MSG SENT: 141 com sha1 wazuh_agent_v3.12.2_windows.wpk
> RESPONSE: ok 88db74903b609563c94bc28fdd251c540ce0fbef
> WPK file sent
> MSG SENT: 141 com upgrade wazuh_agent_v3.12.2_windows.wpk upgrade.bat
> RESPONSE: ok 1 '??' n'est pas reconnu en tant que commande interne
> ou externe, un programme ex�cutable ou un fichier de commandes.
> '?%?' n'est pas reconnu en tant que commande interne
> ou externe, un programme ex�cutable ou un fichier de commandes.
> 
> Upgrade procedure started
> MSG SENT: 141 com upgrade_result
> RESPONSE: err Maximum attempts exceeded
> MSG SENT: 141 com upgrade_result
> RESPONSE: ok 0
> 
> Agent upgraded successfully

As you can imagine, the upgrade was unsuccessful.

**Comment by mi-cha-el** [comment]
Sorry I clicked on the wrong link ! /o\

**Comment by FernandoCP** [comment]
Hi @mi-cha-el!

I'm tracking the problem and it seems that the answer that returns to this message ´MSG SENT: 141 com upgrade wazuh_agent_v3.12.2_windows.wpk upgrade.bat´ is not the right one because even if the terminal writes "ok" behind it should appear "0" and, in this case, it returns 1 and some more messages.

I think the problem may be in the output of the upgrade.bat file.
Could you show me what is written in the upgrade.log file? This file is, in the agent, in `ossec-agent\upgrade\upgrade.log`

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

As requested, here is the content of upgrade.log on the agent side : 

> 2020-04-21 14:32:36Z - Current version: v3.12.0
> 2020-04-21 14:32:36Z - Generating backup.
> 2020-04-21 14:32:39Z - Trying to stop Wazuh service again. Remaining attempts: 5.
> 2020-04-21 14:32:42Z - Starting upgrade processs.
> 2020-04-21 14:32:42Z - Waiting for the installation end.
> 2020-04-21 14:32:44Z - Waiting for the installation end.
> 2020-04-21 14:32:46Z - Waiting for the installation end.
> 2020-04-21 14:32:48Z - Waiting for the installation end.
> 2020-04-21 14:32:50Z - Waiting for the installation end.
> 2020-04-21 14:32:52Z - Restarting Wazuh service.
> 2020-04-21 14:32:52Z - Installation finished.
> 2020-04-21 14:32:52Z - Process ID: 12740
> 2020-04-21 14:32:52Z - Reading status file: status='connected'
> 2020-04-21 14:32:52Z - Upgrade finished successfully.
> 2020-04-21 14:32:52Z - New version: v3.12.0

And the content of upgrade_result : 

> 0

**Comment by FernandoCP** [comment]
Hi!

I've been doing some testing and there's a chance that the problem comes from `PowerShell`. Can you confirm that `PowerShell` is installed on your agent and is working correctly? 
I'm asking you to eliminate that possibility and continue on the right path to solve the problem.

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

Thanks again for your help.

PowerShell 2.0 is installed on the agent side, here is what I could collect about it : 

> $PSVersionTable
> 
> Name                           Value
> ----                           -----
> CLRVersion                     2.0.50727.8806
> BuildVersion                   6.0.6002.18111
> PSVersion                      2.0
> WSManStackVersion              2.0
> PSCompatibleVersions           {1.0, 2.0}
> SerializationVersion           1.1.0.1
> PSRemotingProtocolVersion      2.1

**Comment by FernandoCP** [comment]
Hi @mi-cha-el 

I seem to be having a hard time replicating the problem and it may be that the error is coming from the codepage. If it's not too much trouble, could you execute the `chcp` and `systeminfo` commands in the failed agent as well as in the one that didn't? 
If you have any objection to show me the complete `systeminfo`, the fields I am most interested in are `Sistem Locale` and `Input Locale`.

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

First the server on which the remote agent upgrade failed : 
[SRV-BILDMN.txt](https://github.com/wazuh/wazuh/files/4557463/SRV-BILDMN.txt)
And another serveron which the remote agent upgrade was successful (same exact OS version) : 
[SRV-APP02.txt](https://github.com/wazuh/wazuh/files/4557465/SRV-APP02.txt)

Once again, thank you !

**Comment by FernandoCP** [comment]
Hi @mi-cha-el!

There may be some configuration that causes this error, you could try these commands: 
```
REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor"
REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor"
```

You may have an 'AutoRun' command set in the registry. With those commands, we can know what is executed every time the command processor (cmd.exe) is started and in this way, we can know if the error comes from there.

Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

Indeed, the setup is not the same on both servers.

On SRV-BILDMN : 
> C:\Users\user>REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor"
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor
>     AutoRun    REG_SZ
> 
> C:\Users\user>REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor"
> 
> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
>     CompletionChar    REG_DWORD    0x9
>     DefaultColor    REG_DWORD    0x0
>     EnableExtensions    REG_DWORD    0x1
>     PathCompletionChar    REG_DWORD    0x9

On SRV-APP02 : 

> C:\Users\user>REG QUERY "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor"
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor
>     CompletionChar    REG_DWORD    0x40
>     DefaultColor    REG_DWORD    0x0
>     EnableExtensions    REG_DWORD    0x1
>     PathCompletionChar    REG_DWORD    0x40
>     Autorun    REG_SZ
> 
> C:\Users\user>REG QUERY "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor"
> 
> HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
>     CompletionChar    REG_DWORD    0x9
>     DefaultColor    REG_DWORD    0x0
>     EnableExtensions    REG_DWORD    0x1
>     PathCompletionChar    REG_DWORD    0x9

**Comment by FernandoCP** [comment]
Hi @mi-cha-el!

It seems that we have reached something, you could try to open the command console (cmd) in the client that fails. If the problem is caused by what I think, an error like the following should appear by just opening it 
```
'??' n'est pas reconnu en tant que commande interne ou externe, un programme ex�cutable ou un fichier de commandes.
```
Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

You are right, I have never paid attention to this but when opening the command console I have this on my screen : 
> Microsoft Windows [version 6.0.6003]
> Copyright (c) 2006 Microsoft Corporation. Tous droits réservés.
> '?↓?' n'est pas reconnu en tant que commande interne
> ou externe, un programme exécutable ou un fichier de commandes.
> 
> C:\Users\user>

But where are these '?↓?' defined ?

**Comment by FernandoCP** [comment]
Hi @mi-cha-el!

Now that we've located the possible source of the error, try running `cmd /d`. This way you will be able to run the command console without running the AutoRun commands. If you don't get the same error message, it means it's coming from there. 

After checking it, using `regedit` go to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor` and check the Autorun string, if you find something suspicious you might want to fix it or even delete it completely. Then check again if everything is OK.

I hope this helps you.
Best regards, Fernando.

**Comment by mi-cha-el** [comment]
Hi @FernandoCP ,

You're the man ! 🥇 

Running `cmd /d` allowed me to run the command console without error message. Then I delete the AutoRun string and the wazuh agent remote upgrade completed successfully.

Muchas gracias for your help and your time. 

Michaël.

**Comment by FernandoCP** [comment]
I'm glad everything is working again if you have any more problems don't hesitate to reopen the issue.

Best regards!
Fernando.
