### ISSUE TITLE
Big routing tables causes performance degradation on agents

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#4890]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.0 | wazuh-modulesd | Agent | Packages/Sources | Debian 10 |

A user reported that when a Wazuh agent is installed in a server working as a BGP router, `wazuh-modulesd` takes 100% cpu utilization. The server has over 500k entries on it's routing table. After disabling all of the modules the high CPU usage persisted.

I reproduced the situation on a smaller scale, by adding 65k routing table entries with the following command on a Debian 10 agent:
```
for i in {0..255}; do for j in {0..255}; do ip route add 10.$i.$j.0/24 via 192.168.50.10; done; done
```
After running the previous command, `wazuh-modulesd` never goes below 30% CPU usage with all modules disabled.
![imagen](https://user-images.githubusercontent.com/20206636/79106974-d0710400-7d73-11ea-9dcc-34b60f3a446b.png)

Looking around in the code, I suspected the problem might be in `getPrimaryIP`
https://github.com/wazuh/wazuh/blob/8cc3c17ba7e61a38333b72271c0ae46f6df70344/src/wazuh_modules/wm_control.c#L71

I added a couple of lines in order to print into the log the time taken in this function, before running the `ip route add` commands:
```
2020/04/13 08:24:17 wazuh-modulesd: INFO: getPrimaryIP took 0.000994 seconds
2020/04/13 08:24:18 wazuh-modulesd: INFO: getPrimaryIP took 0.000909 seconds
2020/04/13 08:24:19 wazuh-modulesd: INFO: getPrimaryIP took 0.001049 seconds
2020/04/13 08:24:20 wazuh-modulesd: INFO: getPrimaryIP took 0.000935 seconds
2020/04/13 08:24:21 wazuh-modulesd: INFO: getPrimaryIP took 0.000972 seconds
2020/04/13 08:24:22 wazuh-modulesd: INFO: getPrimaryIP took 0.000928 seconds
2020/04/13 08:24:23 wazuh-modulesd: INFO: getPrimaryIP took 0.000938 seconds
2020/04/13 08:24:23 wazuh-modulesd: INFO: getPrimaryIP took 0.001048 seconds
```
After running the  `ip route add` commands:
```
2020/04/13 08:25:58 wazuh-modulesd: INFO: getPrimaryIP took 0.746768 seconds
2020/04/13 08:26:00 wazuh-modulesd: INFO: getPrimaryIP took 0.752888 seconds
2020/04/13 08:26:02 wazuh-modulesd: INFO: getPrimaryIP took 0.741330 seconds
2020/04/13 08:26:04 wazuh-modulesd: INFO: getPrimaryIP took 0.802986 seconds
2020/04/13 08:26:04 wazuh-modulesd: INFO: getPrimaryIP took 0.756209 seconds
2020/04/13 08:26:05 wazuh-modulesd: INFO: getPrimaryIP took 0.748657 seconds
2020/04/13 08:26:07 wazuh-modulesd: INFO: getPrimaryIP took 0.759937 seconds
2020/04/13 08:26:09 wazuh-modulesd: INFO: getPrimaryIP took 0.763791 seconds
2020/04/13 08:26:11 wazuh-modulesd: INFO: getPrimaryIP took 0.745021 seconds
```

We can see a large increase in the time taken in this function.
In order to narrow the problem down I moved the statements around and found that most of the time is taken up by the following for loop:
https://github.com/wazuh/wazuh/blob/8cc3c17ba7e61a38333b72271c0ae46f6df70344/src/wazuh_modules/wm_control.c#L126-L170

**Comment by WojRep** [comment]
Can you know the estimated time to address this problem?

**Comment by Molter73** [comment]
Hi @WojRep,

We are currently working to figure out the best solution to this problem and hope to have it working on the next few weeks. However, a release date has not been set yet, sorry for the inconvenience.

**Comment by danimegar** [comment]
As I explained in the Pull Request:

The file /proc/net/route is opened and read to get the default gateway. We found out that the first lines of the file have the default gateway information so it is not necessary to read the entire file.
With this we avoid reading thousands of lines in case of big routing tables.

In the Linux repository we found the function that fills/proc/net/route file:
https://github.com/torvalds/linux/blob/v3.17/net/ipv4/fib_trie.c#L2498-L2521

prefix = htonl(l->key); Prefix is the Destination IP and it is store from l->key. The first key is 0.0.0.0/24 (default):
https://github.com/torvalds/linux/blob/v3.17/net/ipv4/fib_trie.c#L1905-L1916
