### ISSUE TITLE
Improve RHEL 7 CIS benchmark for the SCA module

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh#4895]
Hello team,
working on the improvement of the RHEL7 CIS policy:  https://github.com/wazuh/wazuh/blob/v3.12.2/etc/sca/rhel/7/cis_rhel7_linux.yml

Missing checks from section **1.1 Filesystem Configuration**:

- [ ]  1.1.1.1 Ensure mounting of cramfs filesystems is disabled

- [ ]  1.1.1.2 Ensure mounting of freevxfs filesystems is disabled

- [ ]  1.1.1.3 Ensure mounting of jffs2 filesystems is disabled

- [ ]  1.1.1.4 Ensure mounting of hfs filesystems is disabled

- [ ]  1.1.1.5 Ensure mounting of hfsplus filesystems is disabled

- [ ]  1.1.1.6 Ensure mounting of squashfs filesystems is disabled

- [ ]  1.1.1.7 Ensure mounting of udf filesystems is disabled

- [ ]  1.1.1.8 Ensure mounting of FAT filesystems is disabled

- [ ]  1.1.8 Ensure nodev option set on /var/tmp partition

- [ ]  1.1.9 Ensure nosuid option set on /var/tmp partition

- [ ]  1.1.10 Ensure noexec option set on /var/tmp partition

- [ ]  1.1.18 Ensure nodev option set on removable media partitions

- [ ]  1.1.19 Ensure nosuid option set on removable media partitions

- [ ]  1.1.20 Ensure noexec option set on removable media partitions

- [ ]  1.1.21 Ensure sticky bit is set on all world-writable directories

- [ ]  1.1.22 Disable Automounting

All sections missing in **1.2 Configure Software Update** :

- [ ]  1.2.1 Ensure package manager repositories are configured

- [ ]  1.2.2 Ensure gpgcheck is globally activated

- [ ]  1.2.3 Ensure GPG keys are configured

- [ ]  1.2.4 Ensure Red Hat Subscription Manager connection is configured

- [ ]  1.2.5 Disable the rhnsd Daemon

All sections missing in **1.3 Filesystem Integrity Checking**
- [ ]  1.3.1 Ensure AIDE is installed

- [ ]  1.3.2 Ensure filesystem integrity is regularly checked

**Comment by havidarou** [comment]
Issue moved to [wazuh/wazuh-ruleset #615](https://github.com/wazuh/wazuh-ruleset/issues/615) via [**ZenHub**](https://www.zenhub.com/)
