### ISSUE TITLE
Unable to use environment variables as responses in order to configure the wazuh-agent

### ISSUE THREAD

**Issue by angystardust** [wazuh/wazuh#49]
Following the instructions found in _https://raw.githubusercontent.com/wazuh/ossec-wazuh/master/doc/manage_agents.txt_, I was trying to implement an unattended agent setup using the environment variables as responses for the **manage_agent** command (using ansible).
Even if I correctly set all the 6 required env-vars (OSSEC_ACTION OSSEC_AGENT_NAME OSSEC_AGENT_IP OSSEC_AGENT_ID  OSSEC_AGENT_KEY OSSEC_ACTION_CONFIRMED), the **manage_agent** command produces an incorrect base-64 hash which doesn't match the manager key.
So, on the manager, I see many of these log lines:

`1403 - Incorrectly formated message”`

If I copy-and-paste the OSSEC_AGENT_KEY interactively, it works.
The workaround for us was to create an _expect_ script to feed the **manage_agent** command with the responses. This way, it works.
I double-check the OSSEC_AGENT_ID variable value for spurious newline or blank characters but I can't find any difference between the "agent key string" passed in interactive mode or as a env variable. 

The steps to reproduce the issue are:
- create a new agent key on the manager with `manage_agents -a 10.1.1.1 -n testhost`
- extract the agent key with `manage_agents -e <AGENT_ID>`
- log on the testhost (10.1.1.1) and set these variables:

```
 export OSSEC_ACTION: a
 export OSSEC_AGENT_NAME: testhost
 export OSSEC_AGENT_IP: 10.1.1.1
 export OSSEC_AGENT_ID: <AGENT_ID>
 export OSSEC_AGENT_KEY: <AGENT_KEY>
 export OSSEC_ACTION_CONFIRMED: y
```
- run the `manage_agents` without many parameters
- verify that the base64 hash in the client_keys file on the manager and the agent host is different (while it should be the same)

**Comment by vikman90** [comment]
Hi @angystardust,

Unfortunately the documentation inside that folder is unmaintained. For future references, please go to [OSSEC Wazuh Documentation](http://documentation.wazuh.com).

From what I understand, you want to import a key generated by the manager into an agent. The action code to do this is `i` (from "import"). `a` is used to create a new key. Please note that the exported key includes the agent's name, ID and address.

So, once you have a key, you have two options to import it non-interactively:

1. Input the key as a call argument:
`manage_agents -i <key>`

2. Using environment variables: 
```
export OSSEC_ACTION="i"
export OSSEC_AGENT_ID="<key>"
export OSSEC_ACTION_CONFIRMED="y"
manage_agents
```

This way the agent key at manager and agent side should match.

Hope this helps you.
Best regards.

**Comment by angystardust** [comment]
Hi @vikman90 thanks for your reply. Setting the OSSEC_ACTION="i" did the trick, thanks!
But I still have a problem. Even if the manage_agents command complete successfully, it returns an **exit code 1** with  the error "`Input too large. Not adding it`".
This is the complete output of the command:

```
   "****************************************",
   "* OSSEC HIDS v2.8 Agent manager.     *",
   "* The following options are available: *",
   "****************************************",
   "   (I)mport key from the server (I).",
   "   (Q)uit.",
   "Choose your action: I or Q: ",
   "* Provide the Key generated by the server.",
   "* The best approach is to cut and paste it.",
   "*** OBS: Do not include spaces or new lines.",
   "",
   "Paste it here (or '\\q' to quit): ",
   "Agent information:",
   "   ID:079",
   "   Name:testhost",
   "   IP Address:10.1.1.5",
   "",
   "Confirm adding it?(y/n): Added.",
   "** Press ENTER to return to the main menu.",
   "manage_agents: Input too large. Not adding it."
```

Do you want me to open a new bug for this issue?
Thanks

**Comment by vikman90** [comment]
Hi @angystardust,

I couldn't reproduce your issue. Are you calling it with `manage_agents` and no options like the example?

Regards.

**Comment by angystardust** [comment]
Hi @vikman90 yes, i'm just launching the `manage_agents` without any options.
It adds the agent key successfully but the exit code is 1 instead of 0.
P.s.: the O.S. of the agent is a Centos 6 64-bit

**Comment by vikman90** [comment]
Hi @angystardust,

That commit should fix your problem: https://github.com/wazuh/ossec-wazuh/commit/fe47c5ff67f2ac4e3a2c5af96fc17246729da82f

From now on, `manage_agents` won't ask to press Enter if it imported a key successfully, and this should avoid that error to happen and return code 1.

This change will be available at the new release. Please confirm us that it works for you.

Thank you very much for your feedback.
Regards.

**Comment by angystardust** [comment]
Thanks @vikman90 I'll test it asap but i'm pretty sure your patch will fix the issue.

**Comment by angystardust** [comment]
Hi @vikman90 your patch works as expected. 
Now I'm able to deploy a wazuh agent is unattended mode using an ansible role without using the authd demon (i can publish on github if you want) 
Thank you so much for your work and hope to see a new Wazuh release soon.

**Comment by angystardust** [comment]
Hi @vikman90 
unfortunately, there is a regression introduced in your commit https://github.com/wazuh/wazuh/commit/43fa12ff45100fbc529a4e9568a9a28d588a54c4

**Comment by vikman90** [comment]
Hi @angystardust,

Sorry for the inconveniences. I'm trying to reproduce this issue but it seems to work properly in these two ways:

1. Key as a command-line argument:
```
# OSSEC_ACTION_CONFIRMED=y manage_agents -i MDAxIG9uZSBhbnkgNDhmNmRjZDFkZTVmMjkwZTcxZjcyZDFiNTZmOTBhY2Q4OTQxZWU4YjRkZWQyMWIzM2E0ZWM4YTE1N2RhMjcyNQ==

Agent information:
   ID:001
   Name:one
   IP Address:any

Confirm adding it?(y/n): Added.
```

2. Key as an environment variable:
```
# OSSEC_ACTION_CONFIRMED=y OSSEC_AGENT_KEY='MDAxIG9uZSBhbnkgNDhmNmRjZDFkZTVmMjkwZTcxZjcyZDFiNTZmOTBhY2Q4OTQxZWU4YjRkZWQyMWIzM2E0ZWM4YTE1N2RhMjcyNQ==' OSSEC_ACTION=i manage_agents


****************************************
* Wazuh v3.4.0 Agent manager.          *
* The following options are available: *
****************************************
   (I)mport key from the server (I).
   (Q)uit.
Choose your action: I or Q:
* Provide the Key generated by the server.
* The best approach is to cut and paste it.
*** OBS: Do not include spaces or new lines.

Paste it here (or '\q' to quit):
Agent information:
   ID:001
   Name:one
   IP Address:any

Confirm adding it?(y/n): Added.

manage_agents: Exiting.
```

Could you detail how you are importing keys into the agent, please?

Thank you for reporting this issue.
Kind regards.

**Comment by angystardust** [comment]
Hi @vikman90 thanks for your support. Can you please retry with an agent in version 3.3.1?

**Comment by vikman90** [comment]
Hi @angystardust,

Unfortunately, I did not manage to reproduce this issue. I've tested 3.3.0, 3.3.1 and 3.4.0 (in development).

I ran these 6 combinations, changing the order of the definitions:
```sh
OSSEC_ACTION_CONFIRMED=y OSSEC_ACTION=i OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' manage_agents
OSSEC_ACTION_CONFIRMED=y OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' OSSEC_ACTION=i manage_agents
OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' OSSEC_ACTION_CONFIRMED=y OSSEC_ACTION=i manage_agents
OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' OSSEC_ACTION=i OSSEC_ACTION_CONFIRMED=y manage_agents
OSSEC_ACTION=i OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' OSSEC_ACTION_CONFIRMED=y manage_agents
OSSEC_ACTION=i OSSEC_ACTION_CONFIRMED=y OSSEC_AGENT_KEY='MDAxIHRlc3RhZ2VudCAxOTIuMTY4LjE1NS4zIDM2MDZiNzE5MjIyOWYzZWE1YWNkZTM0NDIxZDVlNTMzNTczMTE5NWVlY2U0Yjc3ZDQ1YTQ5ZTA4NGUyMTgzZWM=' manage_agents
```

Can you share with us a complete instance of failing execution, please?

Best regards.

**Comment by angystardust** [comment]
Hi @vikman90, sorry for the delay. I've tested the unattended agent registration with wazuh 3.8 and everything seems ok. Thanks for your support :+1:
