### ISSUE TITLE
Let the Agent service perform auto-enroll when Remoted closes a connection

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#4901]
Once the enrollment library is ready, the Agent service shall request a new key to the manager when it detects that the manager rejected the connection.

- Do the best effort to distinguish when the agent needs a key. If the manager is not reachable or the connection is closed due to a timeout, the agent shall not request a key.
- The agent should never cause the manager to add multiple keys for it. This is, only one key for each agent must be in the client list (_client.keys_).
- The agent should skip auto-enrolling if the agent name is `localhost`, either set in the configuration or automatically got from the system (`gethostname()`).
- If no manager address set in the configuration, the agent must request a key to the address of the manager that rejected the connection.

**Comment by nicolaspapp** [comment]
Analysis of current handshake between `ossec-agentd`  and  `ossec-authd`:
1. Agent: Tries to connect to manager socket (either UDP of TCP protocols) and sends a start up message.
2. Manger: Accepts connection, validates agent. If agent is not enrolled, socket is closed. 
              On success, sends a message to agent.
3. Agent: On successfull expects a message from manager.
                In failure retries


If agent is not enrolled we should be able to identify that the connection has been closed by the manager by observing the recv return.
