### ISSUE TITLE
No log message when agent.remote_conf is set to 0

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh#491]
Hello team,

I'd like to suggest something for an option on the `internal_options.conf` file.

When applying this setting:
```
# Apply remote configuration
# 0. Disabled
# 1. Enabled
agent.remote_conf=0
```

The option works fine, he logs in `ossec.log` are not indicating anything. This could be a problem because a user could forget that and think that the feature is not working. A simple log message would help in both testing purposes and daily use.

Regards,
Juanjo

**Comment by Zenidd** [comment]
Hi @JuanjiJG,

Thank you very much for your suggestion. We really appreciate the time you took to think about it.

 `ossec.log` should not echo the settings, for that we have the API query. Also, some logs of parsing of rules have been removed. It is important for us to keep the logs as clean as possible.

<br></br>
Best regards,

Juan Pablo Sáez
