### ISSUE TITLE
File changes not showing in email for v3.12.x

### ISSUE THREAD

**Issue by dbray925** [wazuh/wazuh#4919]
| 3.12.2 | email | Manager | Packages | CentOS 7 |

After upgrading from 3.11.4, email is no longer showing changes in files. We have two identical environments (config settings) PROD and TEST. We've noticed our TEST environment (3.12.2) no longer shows the changes in files (in email only), but still shows in PROD (3.11.4).

In TEST the email we get has the familiar beginning::
```
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

File '/etc/crontab' modified
Mode: real-time
Changed attributes: size,mtime,inode,md5,sha1,sha256 Old modification time was: '1505485482', now it is '1587039124'
```

But in PROD, we not only get those same headers, but it will also show what changed:
```
Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):

File '/etc/crontab' checksum changed.
Old modification time was: 'Wed Apr 15 20:02:20 2020', now it is 'Thu Apr 16 12:02:54 2020'
Old inode was: '134272208', now it is '134272210'
19c19,20
> # Test
```

However, in TEST we are still seeing the "What changed" in /var/ossec/logs/alerts/alerts.log. It is just not making it to the email.

**Comment by Lopuiz** [comment]
Hello,

Thanks for your feedback!

Since FIM rework, the FIM events have a different structure. It must have caused the file changes don't print on the email alerts.

We will solve it as soon as possible.

Best regards,
Eva

**Comment by bah07** [comment]
Hi @dbray925 

We have unified several issues that report problems related to the fields that appear in the email alerts. We're going to close this issue for duplication and fix it in the next sprint.

You can see the development status in the next issue we'll be working on in the next few weeks. [#953](https://github.com/wazuh/wazuh/issues/953)

Thank you and best regards.
