### ISSUE TITLE
FIM - Wazuh can't restore SACLs when file/directory is moved

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#4921]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | Syscheckd | Agent | Packages/Sources | Windows |

***

Hello team!

To monitor file/directory in Whodata mode, Wazuh adds the SACLs on each directory/file recursively.

![imagen](https://user-images.githubusercontent.com/17710550/79472747-83f02780-8004-11ea-904f-14211fed00f7.png)

When Wazuh stops, restores these SACLs to the original state.

If we move a subdirectory or file saved in a directory monitored (and with SACLs added) out of Wazuh scope, can't restore them.

**Configuration example:**
```xml
<directories whodata="yes" check_all="yes">C:\testing</directories>
```

Best regards,
Eva

**Comment by antoniomanuelfr** [comment]
Hi team! 

I have been investigating this issue and it looks like this is the normal behavior of windows.
I have replicated this issue setting manually some rules in a not monitored folder and moving it. If the folder is moved inside the same volume, the ACLs are kept and if the folder is moved to another volume (for example from `C:\test` to `D:\test` the ACLs are restored. 

In this Windows blog, this behavior is explained https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/inherited-permissions-not-automatically-update.

**Comment by jotacarma90** [comment]
After further analysis of this issue, we have come to the conclusion that there is not much more we can do.
I have tried manually creating policies on a directory, which contains a subdirectory. When moving the subdirectory to another location, even if we delete or edit the policies of the parent directory, the subdirectory's policies are no longer editable in this way.

**Comment by Molter73** [comment]
After going over several tests in order to find a workaround to this problem, we have come to a conclusion that no easy fix is possible due to this being the default Windows behaviour.
