### ISSUE TITLE
SCA support for Debian 10 benchmark

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#4929]
I see on https://www.cisecurity.org/cis-benchmarks/ that there is now a Debian 10 based benchmark guide available from CIS, called CIS_Debian_Linux_10_Benchmark_v1.0.0.pdf.   I suggest that we use this to make debian10 versions of the cis_debian9_L1.yml and cis_debian9_L2.yml files currently distributed with the Wazuh SCA ruleset.  It sounds like that would be a better match for the Bionic version of Ubuntu and the Buster version of Debian.

**Comment by vikman90** [comment]
Hi @branchnetconsulting,

Thank you for letting us know, I confirm we could get the CIS Benchmark for Debian 10. Adding this issue to the product roadmap to update our SCA policies.

Cheers!

**Comment by branchnetconsulting** [comment]
It appears this has been taken care of.
https://github.com/wazuh/wazuh/blob/master/ruleset/sca/debian/cis_debian10.yml

**Comment by vikman90** [comment]
@branchnetconsulting Indeed, this issue was addressed at https://github.com/wazuh/wazuh-ruleset/issues/682, and implemented by https://github.com/wazuh/wazuh-ruleset/pull/726 in Wazuh 4.0.

Thank you for reviewing this issue.
Best regards.
