### ISSUE TITLE
Cluster configuration checks contradiction

### ISSUE THREAD

**Issue by JPLachance** [wazuh/wazuh#493]
Greetings,

I upgraded from Wazuh manager 3.2.0-1 to 3.2.1-1 and my cluster is not working anymore.
```
2018-03-27 15:58:23,634 ERROR: Error 3004 - Error in cluster configuration: Invalid elements in node fields: localhost.
```

My master config:
```
  <cluster>
    <name>wazuh</name>
    <node_name>wazuh-manager-master</node_name>
    <node_type>master</node_type>
    <key>${cluster_key}</key>
    <interval>10s</interval>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>localhost</node>
        <node>wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local</node>
        <node>wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
```

My clients config:
```
  <cluster>
    <name>wazuh</name>
    <node_name>wazuh-manager-client</node_name>
    <node_type>client</node_type>
    <key>${cluster_key}</key>
    <interval>10s</interval>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
        <node>localhost</node>
        <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
```

[A change was made in the cluster management code](https://github.com/wazuh/wazuh/commit/b195cce7ea9bf83fd4bbc0b23a38079127d3ea93) and that change is now rejecting what was considered as a valid cluster configuration in the Wazuh manager 3.2.0-1.

Before that change, a nodes list with only one node, the localhost node, was considered invalid. Now, because of `invalid_elements = list(reservated_ips & set(config['nodes']))`, if there is a `localhost` node in the nodes list, the cluster configuration is considered "invalid".

If we try to remove the `localhost` node from the nodes list, the [`get_remote_nodes` function](https://github.com/wazuh/wazuh/blob/54d25e0cf7314035b221415411fffd75f4d7a688/framework/wazuh/cluster/handler.py#L485) raises another error:
``` 
2018-03-28 13:59:49,936 ERROR: Cluster nodes are not correctly configured at ossec.conf.
```

So, right now, the `check_cluster_config` function is rejecting a cluster configuration that has a `localhost` node and the `get_remote_nodes` is rejecting a cluster configuration that doesn't have a  `localhost` node 😃

Right now, it look's quite impossible to me to make a cluster work with the Wazuh manager 3.2.1-1.

Thanks for your time and support!

**Comment by mgmacias95** [comment]
Hello @JPLachance,

The `<nodes>` configuration should be the same in all cluster nodes. The `localhost` used to be the default one but we changed it since it was confusing. The change is made on the commit that you've pointed out. 

The `localhost` URL is not valid and it breaks the cluster. This behaviour is documented here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/cluster.html#nodes

In the previous cluster version, the error wasn't being properly reported and that has been fixed for this new version. We discussed this issue here: https://github.com/wazuh/wazuh/issues/398#issuecomment-368980982.

Best regards,
Marta

**Comment by JPLachance** [comment]
Greetings!

So, with 3.2.0, here are my nodes lists:

Master:
```XML
<nodes>
    <node>localhost</node>
    <node>wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local</node>
</nodes>
```

Client 1:
```XML
<nodes>
    <node>localhost</node>
    <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
</nodes>
```

Client 2:
```XML
<nodes>
    <node>localhost</node>
    <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
</nodes>
```

Note in that configuration that both my clients share the same nodes list. This allowed me to create a [single StatefulSet for my Wazuh clients in my wazuh-kubernetes project](https://github.com/coveo/wazuh-kubernetes/blob/master/manager_clients/wazuh-manager-client-sts.yaml).

So, since you are telling me that "the <nodes> configuration should be the same in all cluster nodes", I tried this with Wazuh 3.2.1:

Master:
```XML
<nodes>
    <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local</node>
</nodes>
```

Client 1:
```XML
<nodes>
    <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local</node>
</nodes>
```

Client 2:
```XML
<nodes>
    <node>wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local</node>
    <node>wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local</node>
</nodes>
```

Then, if I check the `cluster.log` file on the master, I see:
```
2018-04-03 16:35:16,385 INFO: Starting cluster wazuh
2018-04-03 16:35:16,385 INFO: Listening on port 1516.
2018-04-03 16:35:16,386 INFO: 3 nodes found in configuration
2018-04-03 16:35:16,386 INFO: Synchronization interval: 10s
2018-04-03 16:35:16,592 INFO: Accepted connection from host 100.103.25.222
2018-04-03 16:35:16,875 ERROR: Cluster nodes are not correctly configured at ossec.conf.
```

And when I run some basic `cluster_control` commands:
```bash
root@wazuh-manager-master-0:/# /var/ossec/bin/cluster_control -n --debug
---------------------------------------------------------------------------------------------------
Node                  Address                                                     Type    Status     
---------------------------------------------------------------------------------------------------
wazuh-manager-master  wazuh-manager-master-0.wazuh-master.csec.svc.cluster.local  master  connected  
wazuh-manager-client  wazuh-manager-client-0.wazuh-client.csec.svc.cluster.local  client  connected  
wazuh-manager-client  wazuh-manager-client-1.wazuh-client.csec.svc.cluster.local  client  connected  
---------------------------------------------------------------------------------------------------

root@wazuh-manager-master-0:/# /var/ossec/bin/cluster_control -a --debug
------------------------------------------------------
ID   IP   Name            Status  Node name             
------------------------------------------------------
016  any  ip-10-6-30-231  Active  wazuh-manager-master  
017  any  ip-10-6-18-220  Active  wazuh-manager-master  
020  any  ip-10-6-25-166  Active  wazuh-manager-master  
021  any  ip-10-6-30-166  Active  wazuh-manager-master  
------------------------------------------------------

root@wazuh-manager-master-0:/# /var/ossec/bin/cluster_control -l --debug
2018-04-03 16:36:50,670 DEBUG: CLIENT: Sending 104 of 104
2018-04-03 16:36:50,677 DEBUG: CLIENT: Sending 104 of 104
2018-04-03 16:36:50,685 DEBUG: CLIENT: Sending 104 of 104
2018-04-03 16:36:50,689 ERROR: Cluster nodes are not correctly configured at ossec.conf.
```

So, here, even with all the manager nodes sharing the same nodes list, I'm not able to get the cluster working anymore.

Any idea what I should try next? 😄 

Thanks for your time!

**Comment by mgmacias95** [comment]
Hello @JPLachance,

Our actual implementation doesn't support DNS. This is why you're getting that error in your configuration. We're working at this moment in a new version of the cluster that will support DNS and the only URL that will appear in configuration will be the master. This way, clients won't know each other and they will only communicate with the master.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @JPLachance,

It's been more than a month since the last response to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you still have questions or problems.

Thanks,
Marta
