### ISSUE TITLE
Custom active response not triggered (agent ip=any, script used=custom)

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh#4934]
Hello,
I have been playing with a small custom active response, and in general all seems to be fine. 
Manager (Ubuntu) and Agent (CentOS) at the latest available version (v3.12.2).

I have noticed that when I run the code below, all is fine. But when I enable
`<expect>srcip</expect>` 
the custom active response is not called (even if I see the alert being created under alerts/alerts.json)

I couldn't really understand why adding <expect> this doesn't work. Might this be related to the fact that the IP assigned to the agent is "any"? Or maybe the "expect" field has an invalid value? Even when enabling debug I couldn't find a single clue.

Thanks,
Luca

**Installation details**
The setup is pretty simple (a clean new installation):
`root@ubuntu:/var/ossec/bin# ./agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ubuntu (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: localhost.localdomain, IP: any, Active

List of agentless devices:
`

**Sample output**
`Mon Apr 20 05:39:41 PDT 2020 Hello! /var/ossec/active-response/bin/../../logs/active-responses.log add - - 1587386381.281764 510 (localhost.localdomain) any->rootcheck
`

**Ossec.conf definition**
`<command><name>say-hello</name><executable>say-hello.sh</executable><!-- <expect>srcip</expect> --></command>`
  
`<active-response><disabled>no</disabled><command>say-hello</command><location>server</location><rules_id>510</rules_id></active-response>`

**Sample Custom Script**
`root@ubuntu:/var/ossec/logs# cat ../active-response/bin/say-hello.sh 
#!/bin/sh

ACTION=$1
USER=$2
IP=$3
ALERT_ID=$4
RULE_ID=$5
AGENT=$6
FILENAME=$7
LOCAL=`dirname $0`
LOGFILE=${LOCAL}/../../logs/active-responses.log
TIMESTAMP=`date`

echo "${TIMESTAMP} Hello! ${LOGFILE} ${ACTION} ${USER} ${IP} ${ALERT_ID} ${RULE_ID} ${AGENT} ${FILENAME}" >> ${LOGFILE}

exit 0
`

**Comment by vikman90** [comment]
Hi @lucanus81,

Per your samples, I guess that this is happening because your alert does not contain a source IP.

This configuration:

```xml
<expect>srcip</expect>
```

It expects the alert to contain a `srcip` member. Events triggering the rule 510 does not contain `srcip`. The manager rejects triggering active responses missing any expected field.

Please try out this example:

|Action|Rule|
|---|---|
|Log in to the system via SSH with a public key.|5715 (SSH authentication success).|

### AR Configuration

```xml
<command>
  <name>say-hello</name>
  <executable>say-hello.sh</executable>
  <expect>srcip</expect>
</command>

<active-response>
  <disabled>no</disabled>
  <command>say-hello</command>
  <location>server</location>
  <rules_id>5715</rules_id>
</active-response>
```

### System log

```
Apr 22 12:02:27 eoan sshd[3214]: Accepted publickey for root from 192.168.33.1 port 58418 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI
```

### Alert

```json
{
  "timestamp": "2020-04-22T12:02:27.981+0200",
  "rule": {
    "level": 3,
    "description": "sshd: authentication success.",
    "id": "5715",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "syslog",
      "sshd",
      "authentication_success"
    ],
    "pci_dss": [
      "10.2.5"
    ],
    "gpg13": [
      "7.1",
      "7.2"
    ],
    "gdpr": [
      "IV_32.2"
    ],
    "hipaa": [
      "164.312.b"
    ],
    "nist_800_53": [
      "AU.14",
      "AC.7"
    ]
  },
  "agent": {
    "id": "000",
    "name": "eoan"
  },
  "manager": {
    "name": "eoan"
  },
  "id": "1587549747.5702",
  "full_log": "Apr 22 12:02:27 eoan sshd[3214]: Accepted publickey for root from 192.168.33.1 port 58418 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI",
  "predecoder": {
    "program_name": "sshd",
    "timestamp": "Apr 22 12:02:27",
    "hostname": "eoan"
  },
  "decoder": {
    "parent": "sshd",
    "name": "sshd"
  },
  "data": {
    "srcip": "192.168.33.1",
    "dstuser": "root"
  },
  "location": "/var/log/auth.log"
}
```

This alert does contain `data.srcip`, and it should trigger your AR command.

This is your script's log:

```
date Hello! /var/ossec/active-response/bin/../../logs/active-responses.log add - 192.168.33.1 1587550688.13759 5715 /var/log/auth.log -
```

Hope that helps.

Best regards.

**Comment by lucanus81** [comment]
Hi @vikman90,

yes, now I understand it perfectly. For some reason I couldn't figure out exactly how to populate <expect> field. Yep, that helps a lot! 
I think maybe you might consider to add few more words to the official documentation:
https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/commands.html#expect

where you could really specify:

- what fields are supported, and
- you could add that the fields in <expects> should match a filed with the same name on some alert.

Feel free to close this ticket, and again thanks!

Luca

**Comment by vikman90** [comment]
Hi @lucanus81,

Thank you for confirming that this is working for you. I've proposed a change in the documentation (https://github.com/wazuh/wazuh-documentation/pull/2419) to clarify this point.

Let me close this issue.
Best regards.
