### ISSUE TITLE
Wazah cluster manager not receiving agent status updates

### ISSUE THREAD

**Issue by evilpete** [wazuh/wazuh#495]
I have a Multi AWS region Wazah set up with version 3.2.1-1

My system is set up similar to what is described in Issue thread #398, with peer connections directly linking regional AWS VPC with the Master's VPC

Everything appears to be working correctly with the exception of agent status Not been reported to the cluster master.  Configuration info such as `client.keys`, `agent.conf`,  `local_rules.xml` (etc..)  are being properly automatically synced from the cluster-master to cluster-nodes/clients.

The problem is agent connection status does not seem to be automatically propagating getting from cluster-nodes to cluster-master resulting in agents always appearing with the 'Disconnected' status.

I foundi can sync manually sync with a script

```bash
sudo /var/ossec/bin/cluster_control -f
for i in 10.1.2.3 10.1.2.4 10.1.2.5 10.1.20.3 10.1.20.3 10.1.20.3 ...  OTHER_NODE_IPs ; do
        echo $i
        ssh $i sudo /var/ossec/bin/cluster_control -f -m  IP_MASTER
done
```

thus I know cluster-master and cluster-nodes both can connect to each other.

The only collectivity issues are between cluster-nodes on separate VPCs, as AWS does not allow transitive routing.

any suggestions??

**Comment by mgmacias95** [comment]
Hello @evilpete ,

Sorry for the late response. I encourage you to try our new cluster and check if this works again. The synchronization process has been improved and I'm sure it will work for you now without using `cluster_control -f`.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello @evilpete,

We've been talking in other issues and I think your problem got solved, so I'm closing this issue.

Don't hesitate to open a new one if you still have questions or problems.

Thanks,
Marta
