### ISSUE TITLE
Vulnerability detector alerts parity for different feeds

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#4978]
## Description

After analyzing the vulnerability-detector alerts generated by the different vulnerabilities feeds that can be configured, we realized that there are some fields that are reported in ones but not in others.

As an example, if we take an alert generated by the NVD and other by the vendor feeds, we get the next field differences:

The first one has these fields that are not present in the second one:

- vulnerability.updated
- vulnerability.cwe_reference
- vulnerability.rationale
- vulnerability.assigner
- vulnerability.cve_version

The second one has these fields that are not present in the first one:

- vulnerability.state
- vulnerability.package.source
- vulnerability.package.condition
- vulnerability.bugzilla_references
- vulnerability.references

The purpose of this issue is to unify the data fields reported in the alerts independently on where the alert was generated.

**Comment by chemamartinez** [comment]
Merged #4981 and https://github.com/wazuh/wazuh-ruleset/pull/638. Closing the issue.
