### ISSUE TITLE
WHO-data not getting in email

### ISSUE THREAD

**Issue by arvindjkhr** [wazuh/wazuh#4985]
I am not getting who-data in email in latest wazuh version 13.2

**Comment by jotacarma90** [comment]
Hi arvindjkhr, 
could you explain more about the environment in which you have this problem? For example, showing me the configuration of both manager and agent.
Our last official release is 3.12.3. 
I hope I can help you with anything, greetings!

**Comment by arvindjkhr** [comment]
@jotacarma90 
Here are my configurations 

For email settings
`  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>XXXXX@XXXX.com</email_from>
    <email_to>XXXX@XXXX.com</email_to>
    <email_maxperhour>1200</email_maxperhour>
  </global>
  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>4</email_alert_level>
  </alerts>
  <syscheck>
    <disabled>no</disabled>
    <frequency>60</frequency>
    <scan_on_start>yes</scan_on_start>
    <alert_new_files>yes</alert_new_files>
    <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>
    <directories check_all="yes" recursion_level="300" whodata="yes" realtime="yes" >/</directories>
    <ignore type="sregex">.log$|.swp$</ignore>
  </syscheck>
`

Same syscheck settings are on Agent.

I am getting the who-data in Kibana, but not getting in email. In email it just says like below.

`Rule: 550 fired (level 7) -> "Integrity checksum changed."
Portion of the log(s):
File '/opt/test.file' modified
Mode: scheduled
Changed attributes: size,mtime,md5,sha1,sha256
Size changed from '375640490' to '375646828'
Old modification time was: '1588578179', now it is '1588578493'
Old md5sum was: '5f6272cad9d1b4bdd16e345f2f78c6a1'
New md5sum is : '7e2984325a94fca52251f680b6ab8356'
Old sha1sum was: 'f47f3947d28803961a12c6c3d11fdb1e4516ef9c'
New sha1sum is : '642f261eb3d007a3ab08683c74df7ae19cc78afd'
Old sha256sum was: '1f06e081db204f606bcdf7a48f6b07ed3534246a33656ffc2ab8ce1da3766c84'
New sha256sum is : '94022ed33addb5a5907d3a3202160375e893a56c9a6e1794b29271aea2fb44a6'
`

**Comment by jotacarma90** [comment]
I'm seeing in your syscheck configuration, that you have set the modes "realtime" and "whodata" both at the same time.
Whodata already includes everything that has realtime, so there is no need to put both. This configuration causes an error at startup, and your directory is probably not being monitored correctly.
Try the following:
`<directories check_all="yes" recursion_level="300" whodata="yes">/</directories>`

**Comment by arvindjkhr** [comment]
I changed the same and still facing the same issue.

**Comment by jotacarma90** [comment]
Arvindjkhr, 
We are currently working on this problem, as you can see here:
https://github.com/wazuh/wazuh/issues/5002
We hope to resolve this issue as soon as possible.
Best regards.
