### ISSUE TITLE
Bug in AWS-S3 wodle (in function "check_bucket")

### ISSUE THREAD

**Issue by darrais** [wazuh/wazuh#4999]
Hello,

While trying to configure the AWS-S3 wodle, I noticed a small bug which was preventing me from being able to ingest log data generated by CloudTrail. 

The bug mentioned is caused by the block of code responsible for verifying if a bucket is empty or the credentials are wrong:
```
def check_bucket(self):
    """Check if the bucket is empty or the credentials are wrong."""
    try:
        if not 'CommonPrefixes' in self.client.list_objects_v2(Bucket=self.bucket, Prefix=self.prefix, Delimiter='/'):
            print("ERROR: No files were found in '{0}'. No logs will be processed.".format(self.bucket_path))
            exit(14)
    except botocore.exceptions.ClientError:
        print("ERROR: Invalid credentials to access S3 Bucket")
        exit(3)
```

In a scenario where the following two conditions are true, this verification will fail:
* A CloudTrail trail or a Firehose delivery stream is set without a _log file prefix_ (meaning that log data is stored right under the bucket's root path); and 
* There are at least 1000 files stored under the same bucket's root path. 

This is due to the fact that the boto3 `list_objects_v2` function returns paginated results (in series of 1000, by default). In this very specific case, this function, when executed, will return a response containing keys pointing to the first 1000 objects stored in the bucket - if no "directories" are present in those first 1000 results, there will be no `CommonPrefixes` array containing their name, hence the condition fails.

To solve this issue, I believe you should make use of boto3 `paginators` (should you desire to continue using the same function):
```
def check_bucket(self):
    """Check if the bucket is empty or the credentials are wrong."""
    try:
        paginator = self.client.get_paginator("list_objects_v2")

        for page in paginator.paginate(Bucket=self.bucket, Prefix=self.prefix, Delimiter='/'):
            if 'CommonPrefixes' in page:
                return
    
        print("ERROR: No files were found in '{0}'. No logs will be processed.".format(self.bucket_path))
        exit(14)
    except botocore.exceptions.ClientError:
        print("ERROR: Invalid credentials to access S3 bucket.")
        exit(3)
```

Another option is to only validate if the bucket exists or if the credentials are wrong:
```
def check_bucket(self):
    """Check if the bucket does not exist or the credentials are wrong."""
    s3 = boto3.resource("s3")

    try:
        s3.meta.client.head_bucket(Bucket=self.bucket)
    except botocore.exceptions.ClientError as e:
        error_code = int(e.response['Error']['Code'])
        if error_code == 403:
            print("ERROR: Invalid credentials to access S3 bucket.")
            exit(3)
        elif error_code == 404:
            print("ERROR: Bucket '{0}' does not exist.".format(self.bucket))
            exit(14)
```

In my opinion, this second option should be enough to solve the issue, considering the moment this function is executed - I can see that the code contains posterior validations as to assess the veracity/existence of log files. Also, this option is **far less computationally expensive**.

Additional information:
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.2 | AWS-S3 | N.A. | Packages | Amazon Linux 2 |

**Comment by Selutario** [comment]
Hi @darrais,

Thank you very much for reporting this issue and proposing a solution. It seems like a reasonable change, so we'll study it and probably add it to our roadmap.

If you have any other suggestion, don't hesitate to let us know.

Kind regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

I have reproduced this problem by creating a directory with +1000 files and an `AWSLogs` folder inside. Indeed, as reported in the issue, the wodle throws an error when it does not find CommonPrefixes among the first 1000 elements.

I am testing a solution that makes use of the `head_bucket()` method as suggested by darrais, especially in order not to worsen the efficiency of the wodle. 
```PYTHON
    def check_bucket(self):
        try:
            self.client.head_bucket(Bucket=self.bucket)
        except botocore.exceptions.ClientError:
            print("ERROR: Invalid credentials to access S3 Bucket")
            exit(3)
```

However, it needs further testing. At first glance, I can see that the presence of `CommonPrefixes` is only actively checked on methods that inherit from the `AWSLogsBucket` class. Since `check_bucket` was used by any type of service, I have to review the consequences of the change for Guardduty, Macie, Umbrella etc. 

Regards,
Selu.
