### ISSUE TITLE
Can't start docker-listener module

### ISSUE THREAD

**Issue by SirTerrific** [wazuh/wazuh#5000]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3  | docker-listener | Agent | Last Docker Stack | Debian 10 Stable |

Hi, I have an agent installed on my docker host with debian 10 stable Kernel  4.19.98-1 last updated. 
I tried to enable the module docker-listener but I have this error in the ossec.log

```
2020/05/05 11:52:08 wazuh-modulesd:docker-listener: ERROR: 'docker' module needs to be installed. Execute 'pip install docker' to do it.
2020/05/05 11:52:08 wazuh-modulesd:docker-listener: WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run it in 1 seconds...
2020/05/05 11:52:09 wazuh-modulesd:docker-listener: INFO: Starting to listening Docker events.
2020/05/05 11:52:09 wazuh-modulesd:docker-listener: ERROR: 'docker' module needs to be installed. Execute 'pip install docker' to do it.
2020/05/05 11:52:09 wazuh-modulesd:docker-listener: ERROR: Maximum attempts reached to run the listener. Exiting...
```
However, I already have the python package docker installed on. So I uninstalled and reinstalled it with all the dependance : 
`pip install --no-cache-dir docker websocket-client requests  backports.ssl-match-hostname  chardet certifi urllib3 idna `

but I still have the error... 

In doubt, I tried to install with python3
`pip3 install --no-cache-dir docker websocket-client requests  backports.ssl-match-hostname  chardet certifi urllib3 idna `

but still the same.

I don't know how I can fix it now.
Thanks.

**Comment by SirTerrific** [comment]
HI,
Finally, I resolved my issue. 
I saw in /var/ossec/wodles/docker/DockerListener that you do a try import docker. I tried with a simple script with just import docker in order to see what it will tell me and I had:

`Traceback (most recent call last):
  File "./test_import.py", line 3, in <module>
    import docker
  File "/usr/local/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 10, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 6, in <module>
    from .. import auth
  File "/usr/local/lib/python2.7/dist-packages/docker/auth.py", line 9, in <module>
    from .utils import config
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/__init__.py", line 3, in <module>
    from .decorators import check_resource, minimum_version, update_headers
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 4, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py", line 13, in <module>
    from .. import tls
  File "/usr/local/lib/python2.7/dist-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLHTTPAdapter
  File "/usr/local/lib/python2.7/dist-packages/docker/transport/ssladapter.py", line 23, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname`

So I searched for installing the module backports.ssl_match_hostname and on debian I installed it with 
- **aptitude search python-backports.ssl-match-hostname** and I confirmed that it was not installed on my server. 
I installed with 
- **aptitude install python-backports.ssl-match-hostname** . After that restarted the agent on my host. And now all work well !

Sorry I'm not a pro in the editing on git.

**Comment by Umair841** [comment]
I have the same issue. I am running wazuh-agent on the node of AWS EKS . got hit by the same error. I followed your steps but still having the same issue .!! 

2021/09/21 13:53:39 wazuh-modulesd:docker-listener: INFO: Starting to listening Docker events.
2021/09/21 13:53:39 wazuh-modulesd:docker-listener: ERROR: 'docker' module needs to be installed. Execute 'pip install docker' to do it.
2021/09/21 13:53:39 wazuh-modulesd:docker-listener: WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run in next scheduled time...
2021/09/21 13:54:39 wazuh-modulesd:docker-listener: INFO: Starting to listening Docker events.
2021/09/21 13:54:39 wazuh-modulesd:docker-listener: ERROR: 'docker' module needs to be installed. Execute 'pip install docker' to do it.
2021/09/21 13:54:39 wazuh-modulesd:docker-listener: WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run in next scheduled time...

**Comment by wowtalon** [comment]
I resolved this issue by installing python-docker package:
```bash
sudo apt install python-docker
sudo systemctl restart wazuh-agent
```

**Comment by marvincorreia** [comment]
The easy way to solve the problem is running
`sudo python -m pip install docker`
