### ISSUE TITLE
./disable-account.sh  show error info, No such file or directory

### ISSUE THREAD

**Issue by chaolmrrt** [wazuh/wazuh#5007]
[root@test18 bin]# ./disable-account.sh 
./disable-account.sh: line 22: /var/ossec/active-response/../log/active-responses.log: No such file or directory
./disable-account.sh: [ add | delete ] <username>
[root@test18 bin]# pwd
/var/ossec/active-response/bin

 /var/ossec/logs is the correct path， with “s“

**Comment by vikman90** [comment]
Hi @chaolmrrt,

This issue has been already fixed by PR #4839, and will be available in version 3.13.0.

Thank you for letting us know.
Closing this issue.

Best regards.
