### ISSUE TITLE
Improve the alternative download of OVALs 

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#502]
The possibility of indicating alternative sources for downloading OVALs has already been included in Wazuh 3.3. To do this you will have to indicate the address of the alternative repository, which the manager has access, using the appropriate options. 

More information: https://github.com/wazuh/wazuh/pull/416

However, this is only possible if the external server has SSL. Support for downloads without this protocol and proxies is pending.

**Comment by vikman90** [comment]
This issue depends on PR https://github.com/wazuh/wazuh/pull/519
