### ISSUE TITLE
Backward-incompatibility problem at Wazuh Makefile (GNU make 4.3)

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh#5021]
Hello team!

I've been doing some tests compiling Wazuh on rolling releases such as Arch Linux and I've detected a problem in our Makefile when we try to compile wazuh using the last available version of GNU make (`GNU Make 4.3`) 

## Steps to reproduce (using an arch Linux docker container)
(you could also use other Linux distro such as Centos7, just need to install make 4.3 from sources)

```shell
$> docker run -it archlinux bash
# pacman -Syu gcc git make automake autoconf libtool libnghttp2 libpsl librtmp0 brotli python perl-text-glob
# git clone https://github.com/wazuh/wazuh --depth=1 -b v3.12.3
# cd wazuh/src/
# make deps
curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/3 12./cJSON.tar.gz
make: *** [Makefile:904: external/cJSON.tar.gz] Error 6
```

As you can see, Wazuh deps could not be downloaded because the `VERSION` variable, defined in the Makefile, don't content te expected `3.12`.

After a little research, I found that our Makefile has the following definition for such variable.

```Makefile
space =
space +=
VERSION = $(subst $(space),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))
```

The entire line for `VERSION` definition works fine, the problem is at the definition of `space`.

If we check the [Make changelog](https://lists.gnu.org/archive/html/info-gnu/2020-01/msg00004.html) for 4.3 there is a "Backward-incompatibility" statement announcing:

```
* WARNING: Backward-incompatibility!
  Previously appending using '+=' to an empty variable would result in a value
  starting with a space.  Now the initial space is only added if the variable
  already contains some value.  Similarly, appending an empty string does not
  add a trailing space.
```

This makes our definition of space (which seems to be a non-standard/outdated one) wrong.

I'm not an expert in Makefile syntax but it seems that changing the definition of space to the following would fix the problem with Make 4.3  

```shell
[root@4cfff929a31b src]# git diff Makefile
diff --git a/src/Makefile b/src/Makefile
index e349bd6..17bbb0f 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -864,8 +864,8 @@ endif
 TAR := tar -xf
 GUNZIP := gunzip
 CURL := curl -so
-space =
-space +=
+E =
+space = $E $E
 VERSION = $(subst $(space),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))
 RESOURCES_URL := https://packages.wazuh.com/deps/$(VERSION)
 CPYTHON := cpython

```

I've tested this on Arch Linux and Centos 7 (installing make 4.3 from sources)

I suggest updating the Makefile to avoid problems with Rolling releases (or future updates of Make in supported distributions)

Best regards!

**Comment by BraulioV** [comment]
Related to https://github.com/wazuh/wazuh/issues/4773

**Comment by BraulioV** [comment]
Fixed in https://github.com/wazuh/wazuh/commit/8e2f4d83c9548556d4acd66c7e382f8e46ce79a1
