### ISSUE TITLE
Wazuh Office 365 dashboard

### ISSUE THREAD

**Issue by mskrishna20051974** [wazuh/wazuh#5032]
Hi,

I have followed your blog and configured Office 365 monitoring

https://wazuh.com/blog/monitor-office-365-with-wazuh/

I am new to Wazuh and Kibana and trying to setup the dashboard but i could not. Is there a way i can get the dashboard which could be imported to my system?

Regards,
Krishna M S

**Comment by pereyra-m** [comment]
Hi Krishna.

I shared to you in the google group post that the Office 365 integration script has been updated, check the [blog](https://wazuh.com/blog/monitor-office-365-with-wazuh/).

Hoping this solves your issue! But you'll tell us the result, don't hesitate to contact us again.

Regards.

**Comment by pereyra-m** [comment]
Hi.

I'm closing this issue, but don't hesitate to contact us again if you have any question.

Regards.
