### ISSUE TITLE
office_365.py stops after few mins

### ISSUE THREAD

**Issue by mskrishna20051974** [wazuh/wazuh#5039]
Hi,

I have setup office 365 monitoring as per your blog and the problem is that the script stops running after 1 hour or so.

root@elk:/var/ossec/etc# service wazuh-manager status
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-05-13 10:44:14 CEST; 2s ago
  Process: 3737 ExecStop=/usr/bin/env ${DIRECTORY}/bin/ossec-control stop (code=exited, status=0/SUCCESS)
  Process: 3850 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=0/SUCCESS)
    Tasks: 113 (limit: 4915)
   CGroup: /system.slice/wazuh-manager.service
           ├─3960 /var/ossec/bin/ossec-authd
           ├─3975 /var/ossec/bin/wazuh-db
           ├─3998 /var/ossec/bin/ossec-execd
           ├─4009 /var/ossec/bin/ossec-maild
           ├─4016 /var/ossec/bin/ossec-analysisd
           ├─4074 /var/ossec/bin/ossec-syscheckd
           ├─4093 /var/ossec/bin/ossec-remoted
           ├─4124 /var/ossec/bin/ossec-logcollector
           ├─4159 /var/ossec/bin/ossec-monitord
           ├─4216 /var/ossec/bin/wazuh-modulesd
           └─4232 /var/ossec/framework/python/bin/python3 /var/ossec/bin/office_365.py --contentType DLP.All Audit.General Audit.AzureActiveDirectory Audit.Exchange Audit.SharePoint --hours

When it stops

root@elk:/var/ossec/etc# service wazuh-manager status
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-05-13 09:39:25 CEST; 1h 3min ago
  Process: 1263 ExecStop=/usr/bin/env ${DIRECTORY}/bin/ossec-control stop (code=exited, status=0/SUCCESS)
  Process: 1379 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=0/SUCCESS)
    Tasks: 114 (limit: 4915)
   CGroup: /system.slice/wazuh-manager.service
           ├─1458 /var/ossec/bin/ossec-authd
           ├─1473 /var/ossec/bin/wazuh-db
           ├─1496 /var/ossec/bin/ossec-execd
           ├─1507 /var/ossec/bin/ossec-maild
           ├─1514 /var/ossec/bin/ossec-analysisd
           ├─1572 /var/ossec/bin/ossec-syscheckd
           ├─1584 /var/ossec/bin/ossec-remoted
           ├─1615 /var/ossec/bin/ossec-logcollector
           ├─1655 /var/ossec/bin/ossec-monitord
           └─1666 /var/ossec/bin/wazuh-modulesd

May 13 09:39:19 elk env[1379]: Started ossec-analysisd...
May 13 09:39:19 elk env[1379]: Started ossec-syscheckd...
May 13 09:39:20 elk env[1379]: Started ossec-remoted...
May 13 09:39:21 elk env[1379]: Started ossec-logcollector...
May 13 09:39:21 elk env[1379]: Started ossec-monitord...
May 13 09:39:21 elk env[1379]: 2020/05/13 09:39:21 wazuh-modulesd: WARNING: Option <tag> not found at module 'command'.
May 13 09:39:21 elk env[1379]: 2020/05/13 09:39:21 wazuh-modulesd: WARNING: The 'hotfixes' option is only available on Windows systems. Ignoring it.
May 13 09:39:23 elk env[1379]: Started wazuh-modulesd...
May 13 09:39:25 elk env[1379]: Completed.
May 13 09:39:25 elk systemd[1]: Started Wazuh manager.

The only solution is to check manually and restart the service which is not ideal.

Could u please help me out?

**Comment by elwali10** [comment]
Hello @mskrishna20051974 

If you have followed the blog post then you must probably defined below command block : 

```
<wodle name="command">
  <disabled>no</disabled>
  <command>/path/to/script/office_365.py --contentType Audit.Exchange Audit.SharePoint DLP.All Audit.General Audit.AzureActiveDirectory --hours 24 --tenantId your_tenant_id --clientId your_client_id --clientSecret your_client_secret</command>
  <interval>24h</interval>
  <ignore_output>yes</ignore_output>
  <run_on_start>yes</run_on_start>
  <timeout>0</timeout>
</wodle>
``` 
In that case the setting `interval` will decide when the script should run and it will run every 24h and fetch the last 24 hours of logs ` --hours 24`. 

On the other hand, the option `<run_on_start>yes</run_on_start>` will make the script run when restarting Wazuh manager.

The office 365 integration is not meant to be running all the time as other services do, but it will run once and fetch the logs then wait the period defined in the `interval` to be re-executed.

Hope this helps and I invite to join the community channel in slack https://wazuh.com/community/join-us-on-slack/ for prompter/interactive responses.

Regards,
Wali

**Comment by mskrishna20051974** [comment]
Hi,

This is now clear. You can go ahead and archive this.

**Comment by elwali10** [comment]
Hello,

Glad you find it useful.

Closing the issue as for now.

Should you require further help, Do not hesitate joining the community slack channel.

Regards,
Wali

**Comment by mskrishna20051974** [comment]
Hi I am getting an error while trying to run the Office 365 API logs
script from Wazuh
2020-06-03 04:16:33: [ERROR] Error while retrieving Office 365 activity
logs: ('Request ', 'POST', ' ', '
https://manage.office.com/api/v1.0/6664c39d-0d76-4cf3-909f-734267583c7b/activity/feed/subscriptions/start?contentType=Audit.AzureActiveDirectory',
' failed with ', 400, ' - ', '{"error":{"code":"AF20024","message":"The
subscription is already enabled. No property change."}}').

Could u please help me out?

Regards,
Krishna M S
