### ISSUE TITLE
Command monitoring

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#5055]
Hi guys,
can you please advice how to disable netstat listening ports command on some of the hosts via the manager and not doing it manually on every agent, thanks!

**Comment by FernandoCP** [comment]
Hi @a108a108!

Right now the logcollector only allows you to add and overwrite tags but does not allow you to disable them. 

One thing you can try is to replace the netstat alias in the manager with something that doesn't apply. This way it is possible that it will not return anything or it will return logs for the netstat command

I hope it's helpful, best regards
Fernando.

**Comment by a108a108** [comment]
That will do it, thanks!
