### ISSUE TITLE
sending events to ossim

### ISSUE THREAD

**Issue by Nikkhah** [wazuh/wazuh#5056]
Hi
We have wazuh server and ossim server in our lab. I want to connect wazuh manager to ossim server so that ossim only receives generated events not alerts. Can I do this?

**Comment by pereyra-m** [comment]
Hi Nikkhah!

### Quick answer

Yes, you can configure the manager to communicate to an OSSIM server, or many different type of servers in fact, using syslog. But be aware that you'll receive alerts and not events at this point of the product development. 
If you configure the `logall` option, you'll save all the info in archives.log, this may be what you need.

One possible workaround would be configuring a low alert threshold, or make every event an alert with a rule. But this may create many alerts you'll have to filter later.
Another possibility is to use an external tool that sends the manager .log file, the one that saves all the information and not the alerts.

I'll leave you below the options and you can reply with any question or progress.
Regards!

#### logall option
[Here](https://documentation.wazuh.com/3.12/user-manual/capabilities/log-data-collection/how-it-works.html?#alert) you have a reference to the `logall` option, that stores all events in `/var/ossec/logs/archives/archives.log`
```

<ossec_config>
  <global>
     ...
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    ...
 </global>
</ossec_config>
```

#### Syslog alert output

As you can see in this documentation section about [syslog output](https://documentation.wazuh.com/3.12/user-manual/manager/manual-syslog-output.html), you can configure your Wazuh manager to send all the alerts to a server. 
```
<ossec_config>
  <syslog_output>
    <server>192.168.1.240</server>
  </syslog_output>
</ossec_config>
```
You should change the default alert level threshold (3) according to [this](https://documentation.wazuh.com/3.12/user-manual/manager/alert-threshold.html) section of the documentation to 1, modifying which events are considered alerts by the system

```
<ossec_config>
  <alerts>
      <log_alert_level>1</log_alert_level>
  </alerts>
</ossec_config>
```
And finally, you can create your own custom rules to configure all events as alerts with [this](https://documentation.wazuh.com/3.12/user-manual/ruleset/ruleset-xml-syntax/rules.html) instructions

```
<rule id="100001" level="1">
  <description>Common event registered as alert by user.</description>
</rule>
```

#### Send .log as syslog

The other option is to use a rsyslog module like [this](https://www.rsyslog.com/doc/v8-stable/configuration/modules/imfile.html) one, and configuring a remote syslog input in your OSSIM server to send the _/var/ossec/logs/ossec.log_ file.

**Comment by pereyra-m** [comment]
Hi.

I'm closing this issue, but do not hesitate to ask again if you need.

Regards.
