### ISSUE TITLE
Segmentation fault in the vulnerability-detector module

### ISSUE THREAD

**Issue by Excess0** [wazuh/wazuh#5071]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.4-1 | Vulnerability-detector | Manager | Packages | Centos 7 |

Hello,

 

I'm working with Wazuh 3.11.4-1 and I get a segmentation fault when enabling the vulnerability detector module :

 
![segfault](https://user-images.githubusercontent.com/9552390/82356903-8fb87a80-9a04-11ea-924e-97c4bb0d199c.png)

I have investigated a bit about it and I believe a part of the issue is in **/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c:2380** in the **wm_vuldet_decode_package_version()** function :

 
![source_code_annotation](https://user-images.githubusercontent.com/9552390/82356975-a9f25880-9a04-11ea-8297-a9be5b52bd51.png)

 

When updating the vuln local database, a package name parsing occurs leading to a call of the strstr() function with a null pointer as a second argument.

I found out this behavior using gdb. In the following screenshot, I have set breakpoints with a print of rsi and rdi registers (corresponding to the strstr() arguments : raw and *reg->d_substrings)

 
![gdb2_annotation](https://user-images.githubusercontent.com/9552390/82357007-b971a180-9a04-11ea-9764-30ebd89df111.png)

I believe there exists an error in the **OSRegex_Execute_ex()** function when called with the "**codeready-workspaces/theia-rhel8:2.1-30**" string and the "**(-\d+:)|(-\d+.)|(-\d+\w+)**" compiled regex.

This function set a null value to the reg->d_substrings variable whereas it should set the ["-30"] value, leading to the segmentation fault error.

Regards

**Comment by vikman90** [comment]
Hi @Excess0,

Apologies for the late response. Thank you for your highly detailed description of the problem. Indeed, this issue is a duplicate of #4884: there was a bug in the regex handling that affected Vulnerability Detector on a change in the RHEL feed.

This bug was fixed by #4885 and released in Wazuh 3.12.2. Please update your manager and consider closing this issue.

Thank you again and sorry for the inconvenience.
Best regards.

**Comment by Excess0** [comment]
Hi @vikman90, 
Thank you for your response. 
I have updated Wazuh to the last version and it solved the issue
Best regards
