### ISSUE TITLE
[question] Certificates used to register an agent expired: suggested update procedure

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh#5073]
Hello,

in our environment we are are registering agents using agent verification without host verification.
Let's suppose we have N agents registered. At some point rootCA.pem expires.
What's the suggested upgrade procedure here?
- I imagine we need to recreate rootCA.pem, sslagent.*, sslmanager.*, and move sslagent.* to each machine we want to install a new agent
- what about already-registered agents? Are they safe even if we replace the current set of certificates? I believe the ssl verification is just used to exchange the private symmetric key used to communicate (what we have in client.keys), and hence I tend to believe existing agents will keep working without any issue.

Am I understanding it correctly?

ps. I would suggest to update Wazuh's documentation regarding rootCA.pem creation: you do not use the -days parameter, so this means that by default rootCA.pem will expire in 30 days.
[https://documentation.wazuh.com/3.12/user-manual/registering/host-verification-registration.html#available-options-to-verify-the-hosts](url)

Thanks,
Luca

**Comment by davidjiglesias** [comment]
Hello @lucanus81,

You are completely right in your though process regarding the upgrade procedure. Once the rootCA.pem expires you would have to recreate them and share with new agents for installation.

As for the already registered agents, you are also right, the ssl verification is used in the registration process and once they have been correctly registered they will work just fine even if the rootCA.pem in the manager expires.

Lastly, I believe the actual duration of 30 days by default is done on purpose for security reasons. However, if you feel like you want to expand the life of the CA please feel free to generate a new with a longer duration using `-days`.

I hope this helps clarify any doubts. Please feel free to contact back with any other issues or inquiries you might have.

Regards
