### ISSUE TITLE
[development] Package names with caps not recognized by vulnerability detector

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#5079]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-31300| Vulnerability detector | Manager/Agent | Packages/Sources | All |

Hello team,

We found that in version 3.13.0, from branch `4749-vuln-NVD`, if the name of a package in the database of vulnerabilities contains caps, it will not match with the same package in the database of installed packages.

How to reproduce:
1. Insert a package in the `sys_programs` table of the agent database, located in `/var/ossec/queue/db/<AGENT_ID>.db`, which name contains caps. For example Wazuh.
2. Insert a matching vulnerability in the database of vulnerabilities, located in `/var/ossec/queue/vulnerabilities/cve.db`.
3. Check if the corresponding alert is triggered.

In our test we inserted the following packages:
```
sqlite> select * from sys_programs;
1589979502|2020/05/20 12:58:22|rpm|wazuh||Unspecified|99|WazuhIntegrationTests|2020/05/20 12:58:22|1.0.0-1.el7|x86_64||Wazuh Integration tests mock package|Wazuh Integration tests mock package||1||
1589979502|2020/05/20 12:58:22|rpm|WazuhIntegrationPackage||Unspecified|99|WazuhIntegrationTests|2020/05/20 12:58:22|1.0.0-1.el7|x86_64||Wazuh Integration tests mock package|Wazuh Integration tests mock package||1||
```
And their vulnerabilities:
```
sqlite> select * from vulnerabilities;
WVE-000|RHEL7||wazuh|0|less than|2.0.0-1.el7|0
WVE-002|RHEL7||WazuhIntegrationPackage|0|less than|2.0.0-1.el7|0
```
And only obtained an alert from the `wazuh` package but not from `WazuhIntegrationPackage` that contains caps in its name:
![imagen](https://user-images.githubusercontent.com/19505384/82462725-3ad83b00-9abc-11ea-9efe-9ead73859d84.png)

Regards,
Daniel Folch

**Comment by chemamartinez** [comment]
Closing the issue since the package names are lowercased for both the inventory and CVE databases.

Regards.
