### ISSUE TITLE
rsyslog problem

### ISSUE THREAD

**Issue by cemzafer** [wazuh/wazuh#5083]
```
Hi all,
I have configured wazuh and some agents then I tried rsyslog for test purpose, 
but i havent achieved yet. 
I checked it out with tcpdump -i any udp port 514 -AA and tail -f /var/ossec/logs/archives/archives.log, but nothing comes in. 
Can someone enlighten me? Thanks.
Here are the configurations:

ossec.conf
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>

  <remote>
    <connection>syslog</connection>
    <port>514</port>
    <protocol>udp</protocol>
    <allowed-ips>10.116.176.0/24</allowed-ips>
    <local_ip>10.116.176.226</local_ip>
  </remote>

-------------------------
And the rsyslog client configuration, in the /etc/rsyslog.d/test.conf
*.* @@10.116.176.226:514
-------------------------
Additional Informations:
Wazuh-manager - centos8
Syslog client - centos7
```

**Comment by vikman90** [comment]
Hi @cemzafer,

`<logall_json>` enabled JSON archives (_archives.json_). On the other hand, if you need to fill the file _archives.json_, please check that `<logall>` is set to `yes`.

Best regards.

**Comment by cemzafer** [comment]
Thanks for the quick reply but I checked the configuration again and the global options look like that.
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>

**Comment by a108a108** [comment]
HI @cemzafer,

your syslog config in the manager says port 514 on udp, but 
. @@10.116.176.226:514 on the host means tcp.

Either change it to . @10.116.176.226:514 or set tcp on the wazuh manager.

I personally advice to be udp communication.

**Comment by cemzafer** [comment]
```
Thanks, my bad. I changed the settings as you mentioned like.
*.* @10.116.176.226:514
I tested with the tail -f archives.log but nothing appears.
```

**Comment by a108a108** [comment]
One way to be sure is to trigger syslog alarm, for example try login to the host via ssh with no existing user or make mistakes on the password few times. I test it with ssh brute force using hydra,
other then that i am not sure how much is actually supposed to show.

**Comment by cemzafer** [comment]
@a108a108, thanks for the hint, as you mentioned now get the related ssh errors. 
Regards.
