### ISSUE TITLE
WPK upgrade doesn't remove unpackaged files

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#5086]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3-31209 | Agent_upgrade/WPK | Agent | WPK Packages | All Linux and Windows Server 2016 |

Hello team,

We have detected that the upgrade through WPK left some unwanted files on both systems Linux and Windows, on Linux side the trace of files are:
[extra_files.txt](https://github.com/wazuh/wazuh/files/4667070/extra_files.txt)

On Windows systems it seems that the WPK and the MSI is stored and never removed from upgrade folder.

Is it possible to remove them after the upgrade?.

Regards.

**Comment by DFolchA** [comment]
# Status update

**Working branch:** [5086-remove-msi-in-wpk](https://github.com/wazuh/wazuh/tree/5086-remove-msi-in-wpk)

Applied necessary changes so the WPK upgrade deletes the files once it is finished.

## Linux WPK

### Old behavior

**Test package:** https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/wpk/linux/x86_64/wazuh_agent_v4.2.0_linux_x86_64.wpk

After upgrading using WPK the source files were kept in the `/var/ossec/var/upgrade` directory of the agent.

![imagen](https://user-images.githubusercontent.com/19505384/126341065-bba93723-74ea-4a7a-be52-a9339e66a520.png)

### New behavior

**Test package:** https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.2/wpk/linux/x86_64/wazuh_agent_v4.2.0-0.remove_linux_x86_64.wpk

All the files are deleted after the upgrade:

![imagen](https://user-images.githubusercontent.com/19505384/126342541-b26aacf3-48ba-430d-84e6-41245ad56f6a.png)


## Windows WPK

### Old behavior

**Test package:** https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/wpk/windows/wazuh_agent_v4.2.0_windows.wpk

The upgrade scripts, WPK, and MSI are present in `C:\Program Files (x86)\ossec-agent\upgrade` after the upgrade.

![imagen](https://user-images.githubusercontent.com/19505384/126344839-c659ebf7-2ccd-4bab-871c-da0f0510f451.png)

### New behavior

**Test package:** https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/warehouse/test/4.2/wpk/windows/wazuh_agent_v4.2.0-0.remove_windows.wpk

After the upgrade, only the upgrade.log file is present in `C:\Program Files (x86)\ossec-agent\upgrade` .

![imagen](https://user-images.githubusercontent.com/19505384/126349135-15b9487f-e543-4400-9e10-166c1b0f0a1b.png)
