### ISSUE TITLE
FIM - Don't use variable Pointer from the OVERLAPPED structure in Windows agent

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#5136]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | Syscheckd | Agent | Packages/Sources | Windows (all) |

Hello team!

Wazuh use the following structure to save the directory/file watches monitored in Realtime.

```c
typedef struct _win32rtfim {
    HANDLE h;
    OVERLAPPED overlap;

    char *dir;
    TCHAR buffer[65536];
    unsigned int watch_status;
} win32rtfim;
```
`OVERLAPPED` is a Windows struct which contains the following variables:
```c
typedef struct _OVERLAPPED {
  ULONG_PTR Internal;
  ULONG_PTR InternalHigh;
  union {
    struct {
      DWORD Offset;
      DWORD OffsetHigh;
    } DUMMYSTRUCTNAME;
    PVOID Pointer;
  } DUMMYUNIONNAME;
  HANDLE    hEvent;
} OVERLAPPED, *LPOVERLAPPED;
```

According to Windows documentation, we shouldn't use `overlap.Pointer` after initialization to zero, it is reserved for system use. The issue is we use this variable to save the directory/file path.

It is due Wazuh has a hash table to save al directories monitored in realtime mode. The key is the directory, and the data is `win32rtfim` struct.

We could modify the hash table for the key is the memory address of overlap struct.

**Related documentation:**
+ [Windows OVERLAPPED documentation](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-overlapped)

Best regards,
Eva

**Comment by Molter73** [comment]
While researching a different issue involving realtime on Windows systems I checked the documentation page for `ReadDirectoryChangesW`. Under the `Remarks` section (https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesw#remarks) it states that when using a completion routine:

> The hEvent member of the OVERLAPPED structure is not used by the system, so you can use it yourself.

It looks like we could solve this issue by simply moving the responsabilites taken by `Pointer` over to the `hEvent` variable, but further testing of this is needed.
