### ISSUE TITLE
Possible bug when comparing Ubuntu packages

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#514]
Despite not having found any real use case to confirm it, the comparator algorithm does not work as it should when comparing the release section of the Ubuntu packages.

If we have a package whose version is **65.0.3325.181-0ubuntu0.16.04.1**, being vulnerable if its version is smaller than **65.0.3325.181-0ubuntu1**, the algorithm would report a false positive for the following reason:

1) Until **'-'** everything is correct, so the release section have to be checked.
2) The package revision (0) matches, so the algorithm look for the following comparable number: 0 vs 1.
3) At this point a false positive occurs.

Possible solutions:

- Stop comparing when the algorithm read "ubuntu". 
- Stop comparing if the algorithm finds 2 non-numeric characters. We are checking individual characters.

**Comment by jesusgn90** [comment]
Hi @crolopez, additionally to your current researching:

```
2018/04/06 13:55:27 wazuh-modulesd:vulnerability-detector: 
DEBUG: (5467): The 'linux-firmware' package from agent 000 is vulnerable to RHSA-2018:0094. 
Condition: package version (10-a) less than 10-65.

2018/04/06 13:58:05 wazuh-modulesd:vulnerability-detector: 
DEBUG: (5456): The 'linux-firmware' package from agent 000 is not vulnerable to RHSA-2018:0094. 
Condition: package version (10-65) less than 10-a.

```

**Comment by crolopez** [comment]
Hi @jesusgn90,

This behavior is expected due to the higher value given to numerical characters.
