### ISSUE TITLE
Agent wazuh for AD not connected

### ISSUE THREAD

**Issue by tXambe** [wazuh/wazuh#5147]
Hello,

I have installed one agent of wazuh (3.12) in one DC but in the console always appears how "Never Connected" but it never connects. I have connection so much IP how DNS with this DC, ¿can anyone  help me ?
```
/var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: spro (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: srv.mydomain.com, IP: 1.1.1.1, Never connected
```
Thanks and a greeting

**Comment by danimegar** [comment]
Hello @tXambe 

One idea that you can try: [using simple registration service](https://documentation.wazuh.com/3.12/user-manual/registering/index.html).

### Using simple registration service
I recommend you remove the agent 002 in the manager. Then, open a terminal in the agent and execute:
`# /var/ossec/bin/agent-auth -m manager_IP -A agent_name`

The agent-auth program is the client application used along with ossec-authd to automatically add agents to a Wazuh manager.

Then, open  /var/ossec/etc/ossec.conf.
In the <client><server> section, MANAGER_IP has to be replaced with the Wazuh server’s IP address or the DNS name:

```
<client>
  <server>
    <address>MANAGER_IP</address>
    ...
  </server>
</client>
```
Restart the Wazuh service. 
You will find more details in the [documentation](https://documentation.wazuh.com/3.12/user-manual/registering/index.html#registering-the-wazuh-agent-using-simple-registration-service).

### Other easy registration methods
You will find other registration methods in the [documentation](https://documentation.wazuh.com/3.12/user-manual/registering/index.html). The choice depends on the particular use case and the user’s preferences.

Regards,
            Daniel

**Comment by tXambe** [comment]
> 
> 
> Hello @tXambe
> 
> One idea that you can try: using simple registration service
> ### Using simple registration service
> 
> I recommend you remove the agent 002 in the manager. Then, open a terminal in the agent and execute:
> `# /var/ossec/bin/agent-auth -m manager_IP -A agent_name`
> 
> The agent-auth program is the client application used along with ossec-authd to automatically add agents to a Wazuh manager.
> 
> Then, open /var/ossec/etc/ossec.conf.
> In the section, MANAGER_IP has to be replaced with the Wazuh server’s IP address or the DNS name:
> 
> ```
> <client>
>   <server>
>     <address>MANAGER_IP</address>
>     ...
>   </server>
> </client>
> ```
> 
> Restart the Wazuh service.
> You will find more details in the [documentation](https://documentation.wazuh.com/3.12/user-manual/registering/index.html#registering-the-wazuh-agent-using-simple-registration-service).
> ### Other easy registration methods
> 
> You will find other registration methods in the [documentation](https://documentation.wazuh.com/3.12/user-manual/registering/index.html). The choice depends on the particular use case and the user’s preferences.
> 
> Regards,
> Daniel

Hello,
But I don't login in this DC and I don't execute "/var/ossec/bin/agent-auth -m manager_IP -A agent_name".

In my **ossec.conf** I don't have this configuration.

Thanks

**Comment by danimegar** [comment]
Hello,
In this case, can you tell me how you installed the agent? Did you do it via package? Because it is possible to register an agent to the manager while the wazuh-agent package is installing. Examples of Centos and Ubuntu/Debian:

`WAZUH_MANAGER="10.0.0.2" yum install wazuh-agent` or `WAZUH_MANAGER="10.0.0.2" yum install https://packages.wazuh.com/3.x/yum/wazuh-agent-3.12.3-1.x86_64.rpm`

`WAZUH_MANAGER="10.0.0.2" apt-get install wazuh-agent` or `WAZUH_MANAGER="10.0.0.2" apt-get install https://packages.wazuh.com/3.x/apt/pool/main/w/wazuh-agent/wazuh-agent_3.12.3-1_amd64.deb`

Regards

**Comment by tXambe** [comment]
Hello,

Excume maybe I'm explaining myself wrong, the problem is with one domain controller w2012, have  installed the agent for windows, but appears in the console how "Never Connected"

**Comment by danimegar** [comment]
Hello,

It seems Windows agent is correctly registered. Now, let's check if Wazuh service is running. For that you can open the terminal (cmd or PowerShell) and execute:

`net start wazuh`
or
`net stop wazuh`

These commands are used to start or stop Wazuh. 

Similar commands:
`net start Wazuh`
`net stop Wazuh`

`net start OssecSvc`
`net stop OssecSvc`


You can start Wazuh and then check the ossec.log file. That log is in C:\Program Files (x86)\ossec-agent\ossec.log. This log can show you information, warnings or errors related to your problem.

Also, you can open C:\Program Files (x86)\ossec-agent\ossec.conf file and check the <client> section:
```
<client>
    <server>
      <address>172.16.1.23</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
```
Be sure that `<address>` has the Manager IP.

**Comment by tXambe** [comment]
Hello,

The address inside of the ossec.conf  of the domain controller is the IP of the SIEM (ELK)

```

  <client>
    <server>
      <address>1.1.1.1</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client

```

**Comment by danimegar** [comment]
Hello,

If the IP address of the SIEM and the Wazuh server IP address are the same, alright. Is the Windows agent still in Never Connected after executing` net stop Wazuh` and `net start Wazuh` commands? Sometimes there are connection problems due to firewall configuration or other causes.

To see debug messages, you can write/add the following line in  C:\Program Files (x86)\ossec-agent\local_internal_options.conf:
windows.debug=2

Restart Windows service. Then, ossec.log file will show more information that may be related to the connection between server and agent.

Regards.

**Comment by tXambe** [comment]
Hello,

I follow your recomendations with same result.And the content of ossec.log is:

```
2020/06/03 13:38:52 ossec-agent[3860] start_agent.c:86 at connect_server(): INFO: Trying to connect to server (1.1.1.1:1514/tcp).
2020/06/03 13:38:53 ossec-agent[3860] start_agent.c:102 at connect_server(): ERROR: (1216): Unable to connect to '1.1.1.1': 'No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión.'.
```

**Comment by danimegar** [comment]
Hello,

Thank you for the information. It was useful. I think the remote configuration in the server is fine:
```
<remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>udp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```
The protocol is udp. Can you check protocol udp is in client configuration in Windows agent?
```
<client>
    <server>
      <address>172.16.1.23</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>
    ...
  </client>
```
I think the protocol has to be the same.

Regards.

**Comment by tXambe** [comment]
Hello,

Well it seems that the problem was that the client had configured the protocol TCP when modified this and restart the service, already appears on the console how connect, wait 24/48 hours to close this case.

Thanks very mucho and a greeting

**Comment by danimegar** [comment]
Hello,
I am glad that the problem was solved at the moment.
You are welcome and do not hesitate to share more questions.
 
Remember that Wazuh has a community where you can learn from other users, participate in discussions, talk to the developers: https://wazuh.com/community/

Regards,
Daniel

**Comment by tXambe** [comment]
Hello,

You can close how Resolved ?

Thanks

**Comment by danimegar** [comment]
Yes, I can. Feel free to reopen this issue if you need it.
