### ISSUE TITLE
[Feature Request] Allow compressed feeds for offline updates of the vulnerability detector

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#5152]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.3 | Vulnerability Detector | Manager | Packages | - |

In order to update CVE feeds from a custom location following the Wazuh documentation, as [shown here](https://documentation.wazuh.com/3.12/user-manual/capabilities/vulnerability-detection/offline_update.html), one must uncompress the files downloaded by the scripts provided.

In the case of NVD, for example, this will make the files occupy 1.6GB instead of the compressed 72MB. 

Instructions and storage consumption would be reduced if the compressed files could be used.

**Comment by chemamartinez** [comment]
Done at #5745.
