### ISSUE TITLE
[Vulnerability Detector] False positives for Windows 10

### ISSUE THREAD

**Issue by joselopezrio** [wazuh/wazuh#5164]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.5-patched | Vulnerability Detector | Manager/Agent | Packages/Sources | Windows 10 1909 |

Hello team,
There seem to be Vulnerability Detector false positives for `Windows 10 version 1909`.  Specific alerts were generated from the events collected by a `wazuh-agent` version 3.11.4 installed on a `Windows 10 1909`, that should not affect that specific Windows version, but other versions such as `Windows 10 1607`.

The alerts were showing that certain patches were not installed on the system, when these patches were not released for the Windows version alerted in the first place. All the fields that were checked to figure out this inconsistency were:
- `data.vulnerability.package.condition` --> Missing patch alerted
- `data.vulnerability.cve`  --> CVE 
- `data.vulnerability.package.generated_cpe` --> Windows version extracted.

It was also used the following documentation as a reference to confirm the noncorrelation between the patches and the Windows version that was alerted for the specific CVE used --> https://portal.msrc.microsoft.com/en-US/security-guidance

The following checks were done:
- The Windows version showed in the `data.vulnerability.package.generated_cpe` field is correct.
- The `msu.json` content seems to be correct.

Regards,
Jose Manuel Lopez

**Comment by chemamartinez** [comment]
Outdated
