### ISSUE TITLE
WAZUH 3.12 API cannot be connected

### ISSUE THREAD

**Issue by lukelee1987** [wazuh/wazuh#5169]
|Wazuh version|Component|Install type|Install method|Platform|
|3.12|Wazuh-API|standard package|apt-get|Ubuntu|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Test configuration issues: 
2001 - unidentified alias "Mypassword" at line 131, column 31: password: MyPassword ^

I have tried to modify the file and also using /var/ossec/api/scripts/configure_api.sh, but both I cant connect. Please advise. Is it the password filed i will to have " " ?

**Comment by FernandoCP** [comment]
Hi @lukelee1987 !

I have changed my password without any problem in Ubuntu18 using the following steps:

`cd /var/ossec/api/configuration/auth`
`node htpasswd -c user myUserName` substituting your desired username for myUserName.

Once you run the above command, enter your desired password at the prompt and, after that, don't forget to restart the API.

Can you confirm that this was the form you used to change the password? If not, try doing so and reconnecting. 

I hope I was helpful, don't hesitate to ask if you have any problems. 
Best regards, Fernando.
