### ISSUE TITLE
[Development] Duplicated os in provider configuration block breaks manager configuration

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh#5178]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-31302 | Vulnerability detector | Manager | Packages | Ubuntu 16.04 |

Hi team, 

While doing some testing I found this bug in the Vulnerability Detector module. If you define twice or more times the same os in `provider` block, `wazuh-modulesd` ends failing.

Here you can see the configuration block:
```xml
    <provider name="debian">
      <enabled>yes</enabled>
      <os>wheezy</os>
      <os>stretch</os>
      <os>jessie</os>
      <os>buster</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>
```

And the error while restarting the manager:
```shellsession
root@manager:/# /var/ossec/bin/ossec-control restart
2020/06/05 11:35:33 wazuh-modulesd: WARNING: Duplicate OVAL configuration for 'debian BUSTER'.
2020/06/05 11:35:33 wazuh-modulesd: ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
wazuh-modulesd: Configuration error. Exiting
```

For me, the expected behavior is to show the warning that appears in the log but, the last duplicated `<os>` label should overwrite or merge the same labels and continue.

**Comment by chemamartinez** [comment]
Done at #6683
