### ISSUE TITLE
Invalid behavior with multilog format

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#518]
When logcollector reads logs with multi-log format only the first ones are grouped together and the rest are treated as individual events.

**Comment by crolopez** [comment]
If multilog is configured with X lines, these lines must be ready by the time logcollector starts reading the file. Otherwise, the lines will not be taken into account. 

Example:

Multilog is configured for 3 lines, 2 are added to the file to be monitored and after a while the third one is added. The event is not generated.

**Comment by bah07** [comment]
The first part of this issue:

> When logcollector reads logs with multi-log format only the first ones are grouped together and the rest are treated as individual events.

 is fixed at [#754](https://github.com/wazuh/wazuh/pull/754)

Thanks @crolopez !
