### ISSUE TITLE
Drive letter directory with recursion_level set to 0 is not working correctly on FIM for Windows

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#5180]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12 | ossec-syscheckd | Manager/Agent | Packages/Sources | Windows |

## Description

`recursion_level="0"` should send alerts only from the files modified directly in the configured folder, no subdirectories should be checked however, when configuring FIM to monitor the drive letter directory (`c:\`, `d:\`, ...), with recursion level set to `0` on Windows, it will send alerts for files in deeper levels.

For example, with a configuration like the following one:
```xml
<syscheck>
    <disabled>no</disabled>

    <!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>43200</frequency>

    <scan_on_start>yes</scan_on_start>

    <!-- Generate alert when new file detected -->
    <alert_new_files>yes</alert_new_files>

    <!-- Directories to check  (perform all possible verifications) -->
    <directories report_changes="yes" realtime="yes" recursion_level="0">c:\\</directories>
</syscheck>
```

Alerts from a folder like `c:\test` will be raised when only alerts from files directly in `c:\` should appear.

While testing this bug, we have realised that FIM will go through the entire tree of files instead of ignoring the files which are deeper than the value configured in `recursion_level`.

**Comment by Molter73** [comment]
This bug is being caused by a call to `GetFullPathName` here:
https://github.com/wazuh/wazuh/blob/9a63c238e701deb939687a98459ecbbcefb8cae5/src/config/syscheck-config.c#L772

As stated by the remarks section of `GetFullPathName` docs:
```
- If you specify "U:" the path returned is the current directory on the "U:\" drive
```

This causes any subsequent calls to `fim_check_depth` to skip the first `\` and consider the drive level to be -1, allowing for a level of recursion extra to the one configured.

**Comment by Molter73** [comment]
While working on integration tests for this issue, it became evident that some monitoring options are generating an excess of events being processed by syscheckd. For instance, rules generated for auditd causes it to monitor the directory recursively to the bottom, regardless of the recursion_level set on the configuration. Same goes for Windows whodata.

On Linux systems, exclusion rules could be added so events on subtree levels lower than the configured recursion_level are not logged by auditd. Manually configured exclusion rules look like this:

-a never,exit -F dir=/var/
-w / -p wa -k custom-rule

Further research on how to create this type of rule programmatically is required.

On Windows systems, the audit policies should be set until the required level.
