### ISSUE TITLE
Host-based Anomoly-Detection System and /dev Directory in Linux Container (LXC)

### ISSUE THREAD

**Issue by GraysonPeddie** [wazuh/wazuh#5185]
### Bare-metal host
/etc/debian_version: bullseye/sid
Linux kernel: 5.6.0-2-amd64
Hostname: vmserver
Install type: agent
Version: 3.12.3
Packages installed/version: lxc (1:4.0.2-1), libvirt0 (6.0.0-7)
Purpose: For hosting LXC (Linux containers) and KVM virtual machines

### Linux Container
/etc/debian_version: 10.4
Hostname: siem-server
Install type: manager
Version: 3.12.3
Purpose: for hosting Wazuh Manager running in a Linux container

### Linux Container
/etc/debian_version: stretch/sid
Hostname: unifi-controller
Install type: agent
Version: 3.12.3
Purpose: UniFi Controller running in LXC

### Linux Container
/etc/debian_version: 10.4
Hostname: nas
Install type: agent
Version: 3.12.3
Purpose: File/Media server in a Linux container

### Linux Container
/etc/debian_version: bullseye/sid
Hostname: router
Install type: agent
Version: 3.12.3
Purpose: A gateway to the Internet running in a Linux container.

### Issue
I have setup 4 agents each running in Linux containers and a host machine: router, nas, unifi-controller, and vmserver. "vmserver" is the name for the host of my machine which runs KVM virtual machines and LXC (Linux containers).

What I ran into when I look at Wazuh console in Kibana web UI is "Host-based anomaly detection event (rootcheck)." In the "Control" column, I get "File present on /dev" with a count of 36,951. Out of the 36,951, my two agents reported the following:

UniFi Controller: 15,721 as of June 2.
Router (an LXC container that serves as a gateway to the Internet): 180
NAS: 20,830

I double- and triple-checked and the numbers are correct and I can only guess that 220 alerts due to the /dev directory must have came from siem-server agent built right into the manager.

So, I took the time to investigate and here's what I found, starting with vmserver (bare-metal machine hosting KVM and LXC Linux containers (pardon my repetition, but I want to ensure all the information is clear):

```
root@vmserver:/mnt/vm/lxc# ls /dev/
autofs            loop2         pts     tty19    tty46     uinput
block             loop3         random    tty2     tty47     urandom
bsg               loop4         rfkill    tty20    tty48     vcs
btrfs-control     loop5         rtc       tty21    tty49     vcs1
bus               loop6         rtc0      tty22    tty5      vcs2
char              loop7         sda       tty23    tty50     vcs3
console           loop-control  sda1      tty24    tty51     vcs4
core              mapper        sdb       tty25    tty52     vcs5
cpu_dma_latency   mem           sdb1      tty26    tty53     vcs6
cuse              mqueue        serial    tty27    tty54     vcsa
disk              net           sg0       tty28    tty55     vcsa1
fb0               null          sg1       tty29    tty56     vcsa2
fd                nvme0         shm       tty3     tty57     vcsa3
full              nvme0n1       snapshot  tty30    tty58     vcsa4
fuse              nvme0n1p1     snd       tty31    tty59     vcsa5
gpiochip0         nvme1         stderr    tty32    tty6      vcsa6
gpiochip1         nvme1n1       stdin     tty33    tty60     vcsu
gpiochip2         nvme1n1p1     stdout    tty34    tty61     vcsu1
gpiochip3         nvme1n1p2     tty       tty35    tty62     vcsu2
hpet              nvme1n1p3     tty0      tty36    tty63     vcsu3
hugepages         nvme1n1p4     tty1      tty37    tty7      vcsu4
hwrng             nvram         tty10     tty38    tty8      vcsu5
initctl           port          tty11     tty39    tty9      vcsu6
input             ppp           tty12     tty4     ttyS0     vfio
kfd               psaux         tty13     tty40    ttyS1     vga_arbiter
kmsg              ptmx          tty14     tty41    ttyS2     vhci
kvm               ptp0          tty15     tty42    ttyS3     vhost-net
log               ptp1          tty16     tty43    ttyUSB0   vhost-vsock
loop0             ptp2          tty17     tty44    ttyUSB1   zero
loop1             ptp3          tty18     tty45    uhid
```

unifi-controller (LXC):

```
root@unifi-controller:/# ls /dev
console  full       log     null  random  stdin   tty1  tty4
core     hugepages  lxc     ptmx  shm     stdout  tty2  urandom
fd       initctl    mqueue  pts   stderr  tty     tty3  zero
```

router (LXC):

```
root@router:/# ls /dev/
console  full       log     net   pts      stderr  tty     tty3     zero
core     hugepages  lxc     null  random   stdin   tty1    tty4
fd       initctl    mqueue  ptmx  shm      stdout  tty2    urandom
```

nas (LXC; file/media server)

```
root@nas:/# ls /dev/
console  hugepages  mqueue  random  sdb1    stdout  tty3
core     initctl    null    sda     shm     tty     tty4
fd       log        ptmx    sda1    stderr  tty1    urandom
full     lxc        pts     sdb     stdin   tty2    zero
```

Last, but not least, siem-server (which hosts Wazuh manager, Elastic Search, and Kibana):

```
root@siem-server:/# ls /dev/
console  full       log     null  random  stdin    tty1    tty4
core     hugepages  lxc     ptmx  shm      stdout  tty2    urandom
fd       initctl    mqueue  pts   stderr  tty      tty3    zero
```

So my question is, is there any way to deal with the false positive in the policy monitoring section of Wazuh? Because none of the Linux containers will run without the /dev directory along with the files. Especially since I have two hard drives connected to my Linux container (/dev/sda and /dev/sdb).

### Information
I have reported an issue in the thread here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/wazuh/S5r4kCMi_2A/1sr1g7iuAQAJ

Disabling check_dev in /var/ossec/etc/ossec.conf in Linux containers did solve a problem, but I would like to consider that as a temporary solution.

### Update as of 11:25 AM EDT

Two days ago, I installed an agent for my FreeIPA server running in a Kernel-based Virtual Machine (KVM, for short) and I disabled check_dev out of habit when I registered Linux containers as agents.

Today, I enabled check_dev in all the agents that have it disabled and out of two agents (nas and unifi-controller) that reported over 5,000+ alerts for /dev, my FreeIPA server's agent reported no anomalies for the /dev directory, so it seems the culprit lies with agents running inside Linux containers and not KVM virtual machines.

**Comment by vikman90** [comment]
Hi @GraysonPeddie,

Thank you for your highly detailed explanation of the issue. The option `<check_dev>` looks for regular files in _/dev_ that are not expected to exist.

## Predefined exclusions

There are a series of predefined exclusions ([check_rc_dev.c](https://github.com/wazuh/wazuh/blob/v3.12.2/src/rootcheck/check_rc_dev.c#L64-L87)):

- /dev/**/MAKEDEV
- /dev/**/README.MAKEDEV
- /dev/**/MAKEDEV.README
- /dev/**/.udevdb
- /dev/**/.udev.tdb
- /dev/**/.initramfs-tools
- /dev/**/MAKEDEV.local
- /dev/**/.udev
- /dev/**/.initramfs
- /dev/**/oprofile
- /dev/**/fd
- /dev/**/cgroup
- /dev/shm/sysconfig
- /dev/bus/usb/.usbfs
- /dev/shm
- /dev/gpmctl

In addition, on Solaris:
- /dev/**/.devfsadm_dev.lock
- /dev/**/.devlink_db_lock
- /dev/**/.devlink_db
- /dev/**/.devfsadm_daemon.lock
- /dev/**/.devfsadm_deamon.lock
- /dev/**/.devfsadm_synch_door
- /dev/**/.zone_reg_door

## Finding regular files

If you are getting this kind of alerts, Rootcheck is finding regular files in /dev that do not match the predefined exclusions.

Please run this command in your host —as the result of `ls` that you sent us does not report the type of the files:

```sh
find /dev -type f
```

I see that Ubuntu 20.04 has no regular files in _/dev_.

Please let us know which regular files are present on your hosts. If the list is long, as I guess, maybe a sample will suffice.

In addition, the platform version as `uname -a` reports will be helpful for us:
```sh
$ uname -a
Linux focal 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I think this data will help us to investigate those files and consider adding them to the predefined exclusion list.

## Workaround

Just as @JcabreraC told you in the mailing list, you can use the option `<ignore>` to manually extend the exclusion list.

Thank you again for opening this issue.
Best regards.

**Comment by vikman90** [comment]
@GraysonPeddie,

Sorry for the late reply. Thank you for sending us the lists. The vast majority of files are related to LXC, but a few files like `/dev/console` are not related to it.

There is a weird case that I couldn't explain yet: if I run `find` on a Docker container having Debian Stretch, I have:

```sh
# find /dev -type f
/dev/console
```

However, `stat` confirms that it's not a regular file but a character special file:
```sh
# stat /dev/console
  File: /dev/console
  Size: 0         	Blocks: 0          IO Block: 1024   character special file
```

I've run a Rootcheck scan on that container and I had no defects reported for `/dev`. 

This makes me think that all the alerts you're having are false positives by files created by LXC. In that case, you can set Rootcheck to ignore them:

```xml
<rootcheck>
  <!-- (...) -->
  <ignore>/dev/.lxc-boot-id</ignore>
  <ignore>/dev/lxc</ignore>
  <ignore>/dev/.lxc</ignore>
</rootcheck>
```

That should silence those false positives. If you find any alert related to another file, please send us the name of them for us to analyze them.

Best regards.

**Comment by GraysonPeddie** [comment]
Okay, will do. Thanks.


*Grayson Peddie*
*Twitter:* twitter.com/GraysonPeddie
*Linkedin*: linkedin.com/in/grayson-peddie

**Comment by pld0vr** [comment]
I also get this issue on LXCs.. both debian and ubuntu LXCs running on Proxmox hosts.

**Comment by C0rn3j** [comment]
Ran into this, and the suggested ignore rules seem to unfortunately be ignored as reported in #30747
