### ISSUE TITLE
Ossec logrotate output

### ISSUE THREAD

**Issue by hdep** [wazuh/wazuh#52]
Hello,

Here is an issue I opened on https://github.com/ossec/ossec-hids/issues/963 , but they said I should create it here.

I'm currently getting spammed by ossec every night, during logrotate, there is a restart of ossec, but the output is not managed hence, logrotate send the output by e-mail :

```
/etc/cron.daily/logrotate:
Killing ossec-logcollector ..
Killing ossec-syscheckd ..
Killing ossec-agentd ..
Killing ossec-execd ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
Started ossec-execd...
2016/10/03 06:53:16 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
Started ossec-agentd...
Started ossec-logcollector...
Started ossec-syscheckd...
Completed.
```

If I take rsysolg has example, the postrotate command send output to /dev/nul : 
`invoke-rc.d rsyslog rotate > /dev/null`

I tried this solution but I still get this output : 

`2016/11/14 06:33:10 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
`
Any idea ?

**Comment by vikman90** [comment]
Hello @hdep,

sorry, I don't understand why you are receiving that log by email.

When you restart OSSEC, messages from the restarting script are printed on _stdout_ and the ones from the daemons arrive to _stderr_. So if you want to silence all the messages, you should use:

> `invoke-rc.d rsyslog rotate > /dev/null 2>&1`

The `2>&1` argument will redirect the _stderr_ (2) to _stdout_ (1).

Settings related to OSSEC log rotation are placed in `/etc/logrotate.d/ossec-hids`. You may try to null the output at the _postrotate_ section:

> `postrotate`
> `/var/ossec/bin/ossec-control restart > /dev/null 2>&1`

Regarding the email, could you tell us whether you're monitoring the OSSEC logs or you're using an application to send logs by email? Please paste a complete mail for us so we could find the origin of that spam.

Thank you for your feedback.
Kind regards.

**Comment by hdep** [comment]
Thank you for your awnser.
I didn't realise that le last output was coming from stderr.

The e-mail I am talking about is coming from cron : 

```
Subject : Cron <root@hostname> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )

/etc/cron.daily/logrotate:
Killing ossec-logcollector ..
Killing ossec-syscheckd ..
Killing ossec-agentd ..
Killing ossec-execd ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
Started ossec-execd...
2016/11/14 06:43:29 ossec-agentd: INFO: Using notify time: 600 and max time to reconnect: 1800
Started ossec-agentd...
Started ossec-logcollector...
Started ossec-syscheckd...
Completed.
```

By default, logrotate send an e-mail if there is an output.

**Comment by hdep** [comment]
I assume that ossec shouldn't output stderr has there is no error here.

**Comment by vikman90** [comment]
Hi @hdep,

every daemon log is printed on the `ossec.log` file and into the stderr, no matter whether it's an _INFO_, _WARN_ or _ERROR_ message, since every log uses the same function: 

https://github.com/wazuh/wazuh/blob/master/src/shared/debug_op.c#L78

This is so by design, it is not an error.
Best regards.
