### ISSUE TITLE
vulnerability report is not available in the Dashboard

### ISSUE THREAD

**Issue by rejee** [wazuh/wazuh#5204]
Hi ,

I have installed and configured Wazuh Server 3.12 Version. All the configurations for Windows scanning has been set in both server and agent conf files. No errors in debug logs. But still no data in the dashboard.  I am not able to find the rulegroup vulnerability-detector in the discovery page.

Please help

![agents](https://user-images.githubusercontent.com/58874347/84287442-8af76a00-ab5d-11ea-91de-83733925428d.PNG)
![discovery](https://user-images.githubusercontent.com/58874347/84287444-8c289700-ab5d-11ea-8b46-dcb7eb25522f.PNG)
![ossec_logs](https://user-images.githubusercontent.com/58874347/84287446-8cc12d80-ab5d-11ea-893e-741c681e939a.PNG)
![syscollector](https://user-images.githubusercontent.com/58874347/84287447-8df25a80-ab5d-11ea-9919-ce4450cec8d1.PNG)
![vuldetector](https://user-images.githubusercontent.com/58874347/84287449-8e8af100-ab5d-11ea-8606-48df4e4f9f43.PNG)

**Comment by chemamartinez** [comment]
Hi @rejee,

All your configurations seem correct. Is this happening only with vulnerability related alerts? Have you checked if alerts from other components are indexed in Elasticsearch?

The problem can be also related to the Wazuh plugin of Kibana, in that case, the vulnerability detector alerts should appear in the Kibana discover at least. Let me briefly show you a flow of the alerts from the manager to the WUI dashboards:

- The generated alerts, such as vulnerability detector reports for the agents, are written in the file `/var/ossec/logs/alerts/alerts.json` of the manager to whom the agent is reporting.
- That file is read by `filebeat`, which forwards the JSON alerts to Elasticsearch.
- Alerts are indexed by Elasticsearch, and should be available in the Kibana discover.
- At the Wazuh app, those alerts are used to display the vulnerability dashboards, and also should be available in its own discover.

Could you check that the flow is not broken in any of the described steps?

Best regards,
Chema.

**Comment by rejee** [comment]
Hi Chema,
Thank you very much for your support.
I found the mistake. It was an error in filebeat.yml file.
I have missed to update the host address to https in filebeat.yml file.
Now the vulnerabilities are showing properly in Kibana Dashboard.
your help is much appreciated. :)

Rejeesh

**Comment by rejee** [comment]
Hi Chema,
Thank you very much for your support.
I found the mistake. It was an error in filebeat.yml file.
I have missed to update the host address to https in filebeat.yml file.
Now the vulnerabilities are showing properly in Kibana Dashboard.
Thanks for your help, much appreciated. :)

Rejeesh

**Comment by chemamartinez** [comment]
Hi Rejeesh,

I am glad to hear that you solved it.

Best regards,
Chema.
