### ISSUE TITLE
Health check cloning local disk c: in wazuh folder

### ISSUE THREAD

**Issue by fvaz1906** [wazuh/wazuh#5218]
c:\program files (x86)\ossec-agent\queue\diff\local\c\program files (x86)\ossec-agent\queue\fim\db\fim.db-journal\last-entry.gz

when activating the integrity check module there was a significant increase in storage on the server and agent, I solved the problem by disabling the service, but what would be these problems?

Thank

**Comment by Lopuiz** [comment]
Hello,

The file integrity monitoring module saves an inventory of all files monitored. Additionally, monitoring of `C:` disk in realtime or whodata mode generates an alert for each modification of a file.

Files that change frequently can do server files `alerts.log` and `alerts.json` grow up much. I recommend you ignore these files using the option `ignore`. You can read about it in our [documentation](https://documentation.wazuh.com/3.12/user-manual/capabilities/file-integrity/fim-configuration.html#configuring-ignoring-files-and-windows-registry-entries)

If it doesn't solve your issue, send us your Wazuh configuration and the number of files monitored

Best regards,
Eva

**Comment by Lopuiz** [comment]
Hello!

I close this issue for inactivity

Regards,
Eva
