### ISSUE TITLE
Mutex error in Agentd for Mac OS X

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#522]
When running `ossec-agentd` in version 3.3 and a Mac OS agent. We get the following log:

```
2018/04/10 11:56:05 ossec-agentd: CRITICAL: At pthread_mutex_lock(): Invalid argument
```

This is because a mutex is being locked with an invalid value when we are reloading the count of events. Probably that function is being called with a null structure, as we can see below:

```
2018/04/10 19:38:04 ossec-agentd: DEBUG: keys->keyentries[id]->keyid = 0
2018/04/10 19:38:04 ossec-agentd: DEBUG: keys->keyentries[id]->id = (null)
2018/04/10 19:38:04 ossec-agentd: DEBUG: keys->keyentries[id]->key = (null)
2018/04/10 19:38:04 ossec-agentd: DEBUG: keys->keyentries[id]->name = (null)
2018/04/10 19:38:04 ossec-agentd: CRITICAL: At pthread_mutex_lock(): Invalid argument
```

The issue is located in this line:
https://github.com/wazuh/wazuh/blob/master/src/os_crypto/shared/msgs.c#L199

**Comment by vikman90** [comment]
Fixed in commit: https://github.com/wazuh/wazuh/commit/34b5c58e8ac5ae788fabf5e126555b77b544c1e3
