### ISSUE TITLE
Move max file size from internal configuration to regular configuration

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#5231]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | ossec-syscheckd | Manager/Agent | Packages/Sources | n/a |

The internal option `syscheck.file_max_size` needs to be moved from the internal configuration to the regular configuration (_ossec.conf_). There needs to be a global option and a local option for each `directories` line.

Example of configuration:
```xml
<syscheck>
    <disabled>no</disabled>

    <directories file_max_size="1GB">/home/user</directories>

    <file_max_size>1GB</file_max_size>
</syscheck>
```

* Default value: 1GB

**Comment by bah07** [comment]
Close due duplication with [#5648](https://github.com/wazuh/wazuh/issues/5648)
