### ISSUE TITLE
Unable to send events from Filebeat to Logstash

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh#5233]
Hi,
We try to resolve the problem with sending logs to Elastic through Logstash. We used official [documentation](https://documentation.wazuh.com/3.12/installation-guide/installing-elastic-stack/transform_logstash.html) but it doesn't work. The same problem disscussed in this [topic](https://groups.google.com/forum/#!msg/wazuh/JreQZQ8TRO8/UWs_VyEeBAAJ) and the solution doesn't work.
There is no errors in logs Elasticsearch, filebeat and logstash and there is no info in Elastic.
We use ES 7.7, the same logstash and filebeat 7.6.2. Wazuh 3.12.3

**Comment by jsanchez91** [comment]
Hi @VN1977,

Before we start, let's check if all the processes and settings are correct:

1. Check if your Elasticsearch is ready and accessible from your logstash server by running this command on your logstash server:
```bash
# Command
curl <your_elastic_ip>:9200
# The output will look like this
{
  "name" : "ae1a037bbd40",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "IZqFUsh0TZ-WLEFchybpyQ",
  "version" : {
    "number" : "7.7.0",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "81a1e9eda8e6183f5237786246f6dced26a10eaf",
    "build_date" : "2020-05-12T02:01:37.602180Z",
    "build_snapshot" : false,
    "lucene_version" : "8.5.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

If you have errors with this, set the network.host file configuration of your elasticsearch.yml to 0.0.0.0 and then restart Elasticsearch. If the problem persists, let me know and tell me if you have a firewall or use ssl

2. Check if your Logstash configuration is correct

```bash
# Change the value of the -f property if you named your configuration file with another name
/usr/share/logstash/bin/logstash --config.test_and_exit -f /etc/logstash/conf.d/01-wazuh.conf
```

Let me know if you have any errors in the configuration of the logstash

3. Test your filebeat configuration

```bash
filebeat test output
```

4. Run Logstash in debug mode if you did not get errors in the above checks.

```bash
/usr/share/logstash/bin/logstash --debug -f '/etc/logstash/conf.d/01-wazuh.conf'
```

Share with me the result of the execution of these commands or any errors you get

**Comment by VN1977** [comment]
Hi @jsanchez91  
I have solved this problem. I added processor to filebeat config
```
processors:
- rename:
    fields:
    - from: "agent"
      to: "filebeat_agent"
    ignore_missing: true
```
and my logstash config is 
```
# Wazuh - Logstash configuration file
## Remote Wazuh Manager - Filebeat input
input {
    beats {
        port => 5043
        codec => "json"
    }
}

filter {
	mutate {
		remove_field => ["host"]
	}
}

output {
    elasticsearch {
		hosts => "localhost:9200"
		manage_template => false
		index => "wazuh-alerts-3.x"
		user => "logstash"
		password => "password"
    }
}
```
This config is correct but what I noticed is that docs which were get directly from Filebeat to Logstash differs from the same docs got through Logstash. There are more fields if send through Logstash.
I think your documentation needs to be updated.

**Comment by jsanchez91** [comment]
I'm glad you solved your problem!

Thank you very much for telling us how you solved it, we will take it into account to update the documentation.

I'll close the issue, but if you have any questions please don't hesitate to ask.
Regards, 
Jose.
