### ISSUE TITLE
How to monitor wazuh server itself

### ISSUE THREAD

**Issue by cwynd** [wazuh/wazuh#5238]
We're in the process of migrating a 5+ year-old ossec deployment to wazuh (going pretty well so far, first few agents moved over and talking to the server). We're using a single server architecture, since we only have about 50 agents reporting in.

One problem though, ossec monitors the server installation itself out-of-the-box, but:

After a couple of hours of searching all I've found about _monitoring the Wazuh server itself_ is this:
https://github.com/wazuh/wazurh/issues/1085
which unfortunately does not provide any answer that I can see after re-reading the [referred link](https://documentation.wazuh.com/3.12/getting-started/architecture.html) many times.

I feel like I must be missing something obvious here, and sorry if this is a stupid question, but:

Any hint at all on where find info on monitoring the Wazuh server itself would be very greatly appreciated!

**Comment by Selutario** [comment]
Hi @cwynd!

Wazuh server monitors itself by default. The manager includes an agent (whose ID is `000`) when you install it. Although it is not listed in Kibana, you can see that it really exists if you run this command in your manager:
```shell
root@wazuh-manager:/# /var/ossec/bin/agent_control -lc

Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh-manager (server), IP: 127.0.0.1, Active/Local
```

Do not hesitate to ask if you still have any questions about it.

Best regards,
Selu.

**Comment by cwynd** [comment]
@Selutario thank you so much! And (as I suspected) I must apologize for not seeing this for my self. (I had seen the '000' agent in some screenshots, but failed to connect the dots)

Thanks again Selu

**Comment by Selutario** [comment]
You do not have to worry, we are here to help. We are still improving the documentation and we should probably indicate more clearly that the manager includes an agent, it is not a fact that should be taken for granted.

I close this issue but do not hesitate to open another one, [join our slack community](https://wazuh.com/community/join-us-on-slack/) or our [mailing lists](https://groups.google.com/forum/#!forum/wazuh) to ask everything you need.

Kind regards!
Selu.

**Comment by Stefan-CPlanet** [comment]
@Selutario Hi, in Splunk, how can I show and see the information of the manager? Thank you

**Comment by bowojori7** [comment]
> @Selutario Hi, in Splunk, how can I show and see the information of the manager? Thank you

Hi. Please I need to know how to find this as well.

**Comment by bowojori7** [comment]
> > @Selutario Hi, in Splunk, how can I show and see the information of the manager? Thank you
> 
> Hi. Please I need to know how to find this as well.

For anyone who needs this: filter by agent.id : "000" and refresh on the Security Events page.

**Comment by IkiDBC** [comment]
Hello to everyone, related to this case, i have a doubt maybe someone can help me, i found this article :  https://wazuh.com/resources/Wazuh_PCI_DSS_Guide.pdf on the req 10.2.3, log access to logs, i dont figure it out how those wazuh modules, can acomplish the req. for example on wazuh apps logs /usr/share/kibana/data/wazuh/logs/wazuhapp.log or in management logs you cant see actions of internal users, like failed logins, or user john open the logs tab etc. my doubt is how to monitor wazuh manager audit activities, 

i really apreciate any help, and sorry for my bad english.
