### ISSUE TITLE
Monitoring C: is replaced by the agent's installation directory

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#5239]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | syscheckd | Agent | Packages/Sources | Windows |

## Description

When attempting to monitor `C:` on Windows and having the agent installed under `C:\Program Files (x86)\ossec-agent\` the monitored directory gets changed into the agent's installation directory. If the monitored directory is set to `C:\\` or `C:\.`, it's not replaced and works as expected.

### Test

Syscheck configuration:
```
  <syscheck>
    <disabled>no</disabled>
    <frequency>30</frequency>
    <directories realtime="yes" recursion_level="0">C:</directories>
  </syscheck>
```

Log output on startup:
```
2020/06/16 18:07:18 ossec-agent[960] syscheck.c:175 at Start_win32_Syscheck(): INFO: (6003): Monitoring directory/file: 'c:\program files (x86)\ossec-agent', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
```

After debugging, the conclusion was reached that this change was made by the following call to `GetFullPathName`

https://github.com/wazuh/wazuh/blob/9a63c238e701deb939687a98459ecbbcefb8cae5/src/config/syscheck-config.c#L772

**Comment by Molter73** [comment]
While working on integration tests for this issue, it became evident that some monitoring options are generating an excess of events being processed by syscheckd. For instance, rules generated for auditd causes it to monitor the directory recursively to the bottom, regardless of the `recursion_level` set on the configuration. Same goes for Windows whodata.

On Linux systems, exclusion rules could be added so events on subtree levels lower than the configured `recursion_level` are not logged by auditd. Manually configured exclusion rules look like this:
```
-a never,exit -F dir=/var/
-w / -p wa -k custom-rule
```
Further research on how to create this type of rule programmatically is required.

On Windows systems, the audit policies should be set until the required level.

**Comment by antoniomanuelfr** [comment]
Hi team! 

The cause of this issue is that if the path has only the disk drive without the backslash this is interpreted as the current working directory. This is why it is monitoring the agent's installation directory. 

More info can be founded here: 
https://docs.microsoft.com/es-es/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
