### ISSUE TITLE
Deprecate rootcheck in framework for 4.0

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5246]
Hello team,

Old rootcheck endpoints https://documentation.wazuh.com/3.12/user-manual/api/reference.html#rootcheck are being deprecated in new API for Wazuh 4.0. We should ensure we adapt the new API and the framework to remove unnecesary and unused code regarding rootcheck endpoits and framework module.

We currently have unit tests for rootcheck that are failing, we should remove those ones too.

Regards,

David J. Iglesias

**Comment by CarlosRS9** [comment]
# Status Update

The development is finished. Integrated tests were executed to ensure everything is working as expected
