### ISSUE TITLE
[Development]MSU and cpe_helper only updated if run_on_start is active

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#5261]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0 | vulnerability detector | Manager | Packages/Sources | Linux |

Hello team,

We have found that if the `run_on_start` option for vulnerability detector is not enabled, the MSU and cpe_helper tables in `cve.db` do not get updated.

How to reproduce:

1. Install Wazuh manager
2. Enable vulnerability detector but disable run_on_start.

```
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5s</interval>
    <ignore_time>6h</ignore_time>
    <run_on_start>no</run_on_start>

    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2020</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>
```

3. Restart the Wazuh manager
4. Check that the tables MSU and CPE_HELPER in `/var/ossec/queue/vulnerabilities/cve.db` are empty, if level 2 debug is active no message indicating a CPE or MSU update will appear.

Regards,
Daniel Folch

**Comment by chemamartinez** [comment]
Merged #5335
