### ISSUE TITLE
Log Data Collector doesn't collect my own logs

### ISSUE THREAD

**Issue by Datorrespr** [wazuh/wazuh#5262]
Hi, I have been experiencing issues with Wazuh Log Data Collector. The problem is the following: I need to read non syslog logs, I have logs without format, like this:

```
18-06-2020 23:59:27,RESPUESTA PETICION TRANSACCION PROCESANDO|
SITES:,serialTucompra:XXXXXXX,idfactura:XXXXXXX,estado:0,descripcion:Exitoso
```
The Wazuh agent cannot read that, I have the ```ossec.conf``` like this:

```
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/REVCM_concentrador1/testfinal.log</location>
  </localfile>
```

I installed and configured RSyslog, which allows me to format those syslog logs, so store the logs in sys format. Therefore, the new log remains such that:

```
2020-06-18T17:21:35.910846-05:00 REVCM_concentrador1 testfinal RESPUESTA PETICION TRANSACCION PROCESANDO|
SITES:,serialTucompra:XXXXXXX,idfactura:XXXXXXX,estado:0,descripcion:Exitoso
```

and the ```ossec.log```  like:

```
2020/06/19 08:19:11 ossec-logcollector: INFO: Monitoring output of command(60): df -P
2020/06/19 08:19:11 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2020/06/19 08:19:11 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2020/06/19 08:19:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/REVCM_concentrador1/testfinal.log'.
2020/06/19 08:19:11 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2020/06/19 08:19:11 ossec-logcollector: INFO: Started (pid: 1185).
```

Even so, in the kibana interface, the logs mentioned above do not appear to me. Supposedly the ossec log everything is working correctly and this log file is being checked, I also configured the: local_decoder.xml and local_rules.xml so that it would read the log correctly from the wazuh manager and therefore it is checked by: ```/var/ossec/bin /ossec-logtest```:

```
ossec-testrule: Type one log per line.

2020-06-18T16:19:19.819539-05:00 REVCM_concentrador1 testfinal:


**Phase 1: Completed pre-decoding.
       full event: '2020-06-18T16:19:19.819539-05:00 REVCM_concentrador1 testfinal:'
       timestamp: '2020-06-18T16:19:19.819539-05:00'
       hostname: 'REVCM_concentrador1'
       program_name: 'testfinal'
       log: ''

**Phase 2: Completed decoding.
       decoder: 'testfinal'

**Phase 3: Completed filtering (rules).
       Rule id: '100010'
       Level: '0'
       Description: 'User logged'
```
But kibana doesn't show that log.

If someone can tell me what to do or what I do wrong, I would be very grateful.

I stay tuned.

Atte
Diego Torres Primero.

**Comment by vikman90** [comment]
Hi Diego,

Here are two points I'd like to explain:

Logcollector supports multiple input formats. The format depends on how data appears in the file, not to the syntax of the data. Find the available input formats in the [documentation](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/localfile.html#log-format).

Actually, the `syslog` formats reads one log per line, while `multi-line:N` reads N lines from the file and joins them as a single log.

The log you showed seems to be composed by 2 lines. If every log in that file has 2 lines, this format is appropriate:

```xml
<log_format>multi-line:2</log_format>
```

However, Logcollector seems to be reading the file properly.

On the other hand, _ossec-logtest_ decodes your single-line log and matches it with the rule 100010, but its level is `0` and it won't produce an alert.

- The minimum rule level to produce an alert is `1`.
- The actual rule level threshold to produce an alert is given by [`log-alert-level`](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/alerts.html#log-alert-level):
```xml
<alerts>
  <log-alert-level>3</log-alert-level>
```

<details>
<summary>SSH log rule test</summary>

```
Jun 19 16:06:48 focal sshd[36291]: Accepted publickey for root from 192.168.33.1 port 63314 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI


**Phase 1: Completed pre-decoding.
       full event: 'Jun 19 16:06:48 focal sshd[36291]: Accepted publickey for root from 192.168.33.1 port 63314 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI'
       timestamp: 'Jun 19 16:06:48'
       hostname: 'focal'
       program_name: 'sshd'
       log: 'Accepted publickey for root from 192.168.33.1 port 63314 ssh2: RSA SHA256:uhFanl4fNGvHK/2FON2NbW4MNMZ7m5/xr69XeTmdyQI'

**Phase 2: Completed decoding.
       decoder: 'sshd'
       dstuser: 'root'
       srcip: '192.168.33.1'

**Phase 3: Completed filtering (rules).
       Rule id: '5715'
       Level: '3'
       Description: 'sshd: authentication success.'
**Alert to be generated.
```
</details>

Please note the last line, that confirms that an alert will be generated:

```
**Alert to be generated.
```

I'm afraid _ossec-logtest_ does not support multi-line logs, although you can replace the newline with whitespace in most cases.

Kibana will only show alerts (appearing in _/var/ossec/logs/alerts/alerts.json_), but you can enable the archives to check that the log is arriving to the manager:

```xml
<global>
  <logall>yes</logall>
```

This way, every log will appear in _/var/ossec/logs/archives/archives.log_, no matter if they become an alert or not.

Hope this helps you.
Best regards.

**Comment by Datorrespr** [comment]
Hi Vikman, thanks for your quick asw.

It works, but there are some problems yet. The logs aren't constants in lines, one is written in 1 line but other can be in 4 or 5 lines.

other thing it's that changue the logall works and and it is reflected in the manager in  /var/ossec/logs/archives/archives.log, but it still not showing up in the kibana.

What can I do now?

Best regards,

Diego Torres Primero

**Comment by vikman90** [comment]
Hi!

Logcollector needs a kind of rule to delimit a log. For instance, `syslog` reads one line per log, and `multi-line` reads N lines per log. On the other hand, `audit` reads as many lines as they share the same ID. If you could get a rule to parse that file —is that a custom file?— we could help you to use a particular format or even extend the Logcollector functionality with a new format. You are also welcome to contribute :)

If you're using a custom log, the `full-command` format may be helpful: you should use a program (it may be a script) to read your file and produce one single log per execution. Or you could even write a custom "tail" and run it with `<wodle name="command">`. It requires you to program but lets you do anything you need.

Regarding the second issue (you can't see any alerts from your logs), please test a single log from archives. For instance, if this is the line appearing in _archives.log_:
```
2020 Jun 22 18:21:39 focal->/root/demo.log Hello World.
```

The actual log is:
```
Hello World.
```

This is a sample of a log that would produce an alert (I wrote a toy rule):
```
# echo "Hello World." | /var/ossec/bin/ossec-logtest
2020/06/22 18:24:29 ossec-testrule: INFO: Started (pid: 25387).
ossec-testrule: Type one log per line.



**Phase 1: Completed pre-decoding.
       full event: 'Hello World.'
       timestamp: '(null)'
       hostname: 'focal'
       program_name: '(null)'
       log: 'Hello World.'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '100001'
       Level: '5'
       Description: 'Test rule.'
**Alert to be generated.
```

As I told you, the last line confirms that the log would appear in the alerts.

If you confirm that the log is OK but you still don't see the alert in Kibana, please try to find the log in _/var/ossec/logs/alerts/alerts.json_. That would let us know if the alert is not produced, or Elasticsearch is not ingesting that.

Best regards.

**Comment by Datorrespr** [comment]
Hi!

I have another problem with all logs, I have changed the agents. I needed it because the agents were behind a Nat, but I already remembered it, the problem now is that after I register the new agents, I am no longer monitored by any element of the machines, security, or integrity monitoring. Agents are active, and the manager receives the logs correctly but does not display them in the kibana.

this is my Manager's ossec.conf:

```
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>smtp.gmail.com</smtp_server>
    <email_from>torresprimero2001@gmail.com</email_from>
    <email_to>dat@orcait.com.co</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
  </global>

  <auth>
  <disabled>no</disabled>
  <port>1515</port>
  <use_source_ip>no</use_source_ip>
  <force_insert>yes</force_insert>
  <force_time>0</force_time>
  <purge>yes</purge>
  <use_password>no</use_password>
  <limit_maxagents>yes</limit_maxagents>
  <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
  <!-- <ssl_agent_ca></ssl_agent_ca> -->
  <ssl_verify_host>no</ssl_verify_host>
  <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
  <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
  <ssl_auto_negotiate>no</ssl_auto_negotiate>
 </auth>

  <alerts>
    <log_alert_level>3</log_alert_level>
    <email_alert_level>12</email_alert_level>
  </alerts>

```

this is one of the logs in ```/var/ossec/logs/archives/archives.log ``` :

```
2020 Jun 24 10:14:37 (REVCM_gateway1) any->/var/log/messages Jun 24 10:14:15 [localhost] audispd: node=REVCM_gateway1 type=SYSCALL msg=audit(1593011655.019:25505): arch=c000003e syscall=21 success=no exit=-13 a0=199cac0 a1=1 a2=7ffcc7460ed0 a3=3 items=1 ppid=29936 pid=30946 auid=4294967295 uid=991 gid=989 euid=991 suid=991 fsuid=991 egid=989 sgid=989 fsgid=989 tty=(none) ses=4294967295 comm="sh" exe="/usr/bin/bash" subj=system_u:system_r:zabbix_agent_t:s0 key=(null)
2020 Jun 24 10:14:37 (REVCM_gateway1) any->/var/log/messages Jun 24 10:14:15 [localhost] audispd: node=REVCM_gateway1 type=AVC msg=audit(1593011655.019:25506): avc:  denied  { execute } for  pid=30946 comm="sh" name="rpm" dev="sda3" ino=201931132 scontext=system_u:system_r:zabbix_agent_t:s0 tcontext=system_u:object_r:rpm_exec_t:s0 tclass=file permissive=0

```

But it doesnt work in kibana in that hour and agent.

![tempsnip](https://user-images.githubusercontent.com/66637305/85599792-78c40400-b612-11ea-8c78-ca029be76939.png)


What can I do?

Best Regards.

**Comment by Datorrespr** [comment]
Yesterday I Update Wazuh 3.12 to 3.13, after that it didn't work

**Comment by bah07** [comment]
Hi @Datorrespr 

I'll try to help out here. Sorry for late response.

First, check that your manager has a version equal to or greater than the agents. In version 3.13, for example, the FIM events changed and the manager needs to be updated to decode those messages.

Secondly, check that alerts are generated in the file` /var/ossec/logs/alerts/alerts.json`. If the alerts are appearing the problem is further down the line, either _filebeat_ is not indexing the alerts or the _kibana_ app for some reason is not receiving information.

To check that the communication between _filebeat_ and elastic is correct run the following command, check if service is running and the connection works fine:

>  root@centos7:/home/vagrant$ systemctl status filebeat.service

```log
● filebeat.service - Filebeat sends log files to Logstash or directly to Elasticsearch.
   Loaded: loaded (/usr/lib/systemd/system/filebeat.service; enabled; vendor preset: disabled)
   Active: active (running) since vie 2020-07-31 07:05:55 UTC; 4min 15s ago
     Docs: https://www.elastic.co/products/beats/filebeat
 Main PID: 6374 (filebeat)
   CGroup: /system.slice/filebeat.service
           └─6374 /usr/share/filebeat/bin/filebeat -environment systemd -c...

```

> root@centos7:/home/vagrant$ filebeat test output

The output should be something like: 

```log
elasticsearch: http://10.2.0.40:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 10.2.0.40
    dial up... OK
  TLS... WARN secure connection disabled
  talk to server... OK
  version: 7.7.
```
Hope its helps, regards.
