### ISSUE TITLE
Use aiohttp-cache 2.0.2 and remove local fix

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#5265]
Hello team

# Description

Until now, the version of the `aiohttp-cache` library we were using in the API 4.0 had a bug when using custom middlewares. I reported and fixed it in the official repository here https://github.com/cr0hn/aiohttp-cache/issues/22. 

However, although it was uploaded to PyPI, we were not able to use it due to incompatibilities with the version of the embedded python interpreter in Wazuh, which was 3.7.5 (3.8 was required). The fix was implemented locally in order to make it work.

Now that the embedded python interpreter has been upgraded to Python 3.8 in Wazuh, we should use the official library and delete the local fix.

# What to do

Currently, the `setup_cache` is implemented locally in order to overwrite the bug with our fix. It can be found inside `api/api/aiohttp_cache.py`. There is also a middleware called `cache_middleware` with the fix itself (api/api/middlewares.py) that could be deleted. 

Updating aiohttp-cache requirement to version 2.0.2 is needed too.

Best regards,
Selu.

**Comment by ZhukovGreen** [comment]
Hey guys, just letting you know that the new release of aiohttp-cache==2.1.0 supports python 3.6, 3.7, and 3.8.
