### ISSUE TITLE
Review and update custom messages in API responses

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5266]
Hello team,

As part of the development of the new Wazuh API 4.0 we have added custom and dynamic message responses for the majority of the API endpoints. These messages follow the structure below:

```python
    result = AffectedItemsWazuhResult(all_msg='All selected agents information is shown',
                                      some_msg='Some agents information is not shown',
                                      none_msg='No agent information is shown'
                                      )
```

We should review and update the current messages in the framework looking to:
- Improve English quality
- Standardize output for all models
- Include more useful information for human users

Best regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
# Status update
Framework modules, spec and some unit tests have been modified in order to improve the field `message` in the API response. 

## Pending 
- Update API examples in the documentation.
