### ISSUE TITLE
Syscheck facing lag and generating erroneous alerts

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh#5268]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11 | Wazuh component | Manager/Agent | Packages | Debian 10.2 |

Wazuh syscheck showing lag of about 2+ hours in reporting file modification/creation/deletion changes.
Some times, the files it is reporting to have changed, shows mtime and ctime (output from stat) from way before, more then months.

Also for quite a number of files, alerts are as follows:

```
Old sha256sum was: ''
New sha256sum is : '783990d11819c473ccf153a73ac1edc2bebb366b9d432bf9bb0df07570466998'

```
For files like the above too, on server it shows changes were made way before, however Wazuh is showing alert.

**Comment by djmgit** [comment]
These false positives are becoming quite frequent and flooding our ES.

**Comment by djmgit** [comment]
Sometimes, for sha256 sum, the reverse is also happening, that is, the old sha256 sum is showing value but the new sum is ''.  For such files too, Wazuh is reporting syscheck modification alert however the file had been changed way back.

**Comment by Lopuiz** [comment]
Hello,

We released Wazuh version 3.12 where we did a Syscheckd rework.
Could you tell us the Syscheck configuration and the characteristic of the files which generate issues?
We will check it doesn't happen in 3.12

Regards,
Eva

**Comment by djmgit** [comment]
@Lopuiz 

```
<syscheck>
  <disabled>no</disabled>
  <frequency>300</frequency>
  <scan_on_start>yes</scan_on_start
  <directories check_all="yes" whodata="yes" realtime="no">[files and directories]</directories>
 <ignore>[file or directory]</ignore>
 .
 .
 . 
</syscheck>
```

The files for which this issue is happening are only text files - config files, code files like php and js and other text dumps.

**Comment by Lopuiz** [comment]
Okay, so I can assume they're small files.
Could you tell us the auditd version?

**Comment by djmgit** [comment]
@Lopuiz 

Yes, files are not big.

**Comment by Lopuiz** [comment]
It's strange behavior. Could you check if you have some error or warning message in /var/ossec/logs/ossec.log?

Some auditd versions fail to report some events, but it doesn't (that we know). So, Could you update it to 3.13? if Syscheck had a bug, the rework can solve it.

**Comment by djmgit** [comment]
@Lopuiz 
I will check /var/ossec/logs/ossec.log and get back to you.
Also, I would like to ask, just out of my curiosity, how is auditd coming into this?
Actually I was under the impression that fim works by verifying if the existing sha256 sum of the file
and its metadata has changed. Auditd is only required by syscheck fim if we wish to enable the whodata feature.

**Comment by Lopuiz** [comment]
Yes, FIM verifies if the existing sha256 sum of the file and its metadata has changed. But it's is auditd which report if there is some modification in the file. FIM read auditd logs and generate the alerts.

**Comment by Lopuiz** [comment]
Hello!

I close this issue for inactivity. If you have further questions join our Slack channel or subscribe our mailing list.
https://wazuh.com/community/

Regards,
Eva
