### ISSUE TITLE
Allow to store data to logstash/ES

### ISSUE THREAD

**Issue by gittygoo** [wazuh/wazuh#5274]
Currently the information about inventory etc... is being stored on the wazuh manager side, ideally it would be good to have this data on the Elasticsearch side as an option to try to make the manager as ephemeral as possible

**Comment by davidjiglesias** [comment]
Hello @gittygoo,

Thank you for your feedback on this matter. We already have an ongoing issue https://github.com/wazuh/wazuh/issues/204 regarding this topic.

**Comment by gittygoo** [comment]
hi @davidjiglesias I believe it is not the same issue we are talking about. On the issue you mention only alerts are being mentioned. AFAIK the INVENTORY data is not mentioned there. Isnt this stored differentlty inside some wdb files? This is the data i would like to have on elasticsearch.

**Comment by davidjiglesias** [comment]
Hello @gittygoo, 

You are totally correct, the issue https://github.com/wazuh/wazuh/issues/204 only includes alerts being stored directly in Elasticsearch. However, we also plan to include inventory, FIM and vulnerability data. We would be updating the issue to Epic state including these new features shortly. I have moved this issue to Waiting R&D so we can follow up when the update is made.

Thanks for your contribution and proposals,

David J. Iglesias

**Comment by gittygoo** [comment]
@davidjiglesias why is this closed again? is there  another one i canfollow for this request?
