### ISSUE TITLE
Vulnerability Detector: Unit tests for the RHEL OVAL support

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#5287]
### Description

The development of https://github.com/wazuh/wazuh/issues/5285 must be accompanied by their respective unit tests:

- Ensure all existing UT passes without memory issues, and the coverage of the related functions have no decreased.
- Create UT for new functions.

Added functions:
- [x] void wm_vuldet_oval_traverse_rhsa
- [x] void wm_vuldet_oval_append_rhsa
- [x] void wm_vuldet_oval_copy_rhsa
- [x] void wm_vuldet_add_oval_vulnerability
- [x] void wm_vuldet_clean_vulnerability_info
- [x] int wm_vuldet_insert_cve_info
- [x] bool wm_vuldet_set_feed_update_url

Modified functions:
- [x] wm_vuldet_fill_report_oval_data
- [ ] wm_vuldet_update_feed
- [x] wm_vuldet_oval_xml_preparser
- [x] wm_vuldet_oval_xml_parser
- [ ] wm_vuldet_run_update
- [x] wm_vuldet_json_parser
- [x] wm_vuldet_get_package_os
- [x] wm_vuldet_set_subversion

Deleted functions:
- [x] wm_vuldet_add_rvulnerability: Unit tests not found.
- [x] wm_vuldet_decode_package_version: Unit tests deleted
- [x] wm_parse_rpm_source_package: Unit tests deleted

**Comment by danimegar** [comment]
These are the functions that were created or modified. The first 6 are the ones with more code to test:
- [ ] int wm_vuldet_insert_cve_info
- [ ] bool wm_vuldet_set_feed_update_url
- [ ] int wm_vuldet_fetch_feed
- [ ] int wm_vuldet_update_feed
- [ ] int wm_vuldet_check_feed
- [ ] void wm_vuldet_enable_rhel_json_feed
- [ ] void wm_vuldet_oval_traverse_rhsa
- [ ] void wm_vuldet_oval_append_rhsa
- [ ] void wm_vuldet_oval_copy_rhsa
- [ ] void wm_vuldet_add_oval_vulnerability
- [ ] void wm_vuldet_clean_vulnerability_info
- [ ] int wm_vuldet_sync_feed
