### ISSUE TITLE
Define C++ Coding style

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5290]
Define a coding style guideline to follow in the project.

## Tasks
- [X] Create draft document.
- [x] Create wiki page.

**Comment by Dwordcito** [comment]
https://docs.google.com/document/d/1lYRl6pcHoCfMkCD-L4UNGH1D39B8Zwm1wcOMAJ2Ieoo/edit?usp=sharing

**Comment by tinachoB** [comment]
I'll create the needed wiki github pages based on the C++ Coding Style already completed in gdocs

**Comment by tinachoB** [comment]
Wiki has been created successfully: https://github.com/wazuh/wazuh/wiki/Coding-style-guide-(C-plus-plus)
