### ISSUE TITLE
oscap.py error with mkfifo(FIFO_PATH, 0666)

### ISSUE THREAD

**Issue by mdiavm** [wazuh/wazuh#5297]
Hi, found an error with oscap.py:

 [root@ol1 ~]# /var/ossec/wodles/oscap/oscap.py --xccdf /usr/share/xml/scap/ssg/content/ssg-ol7-ds.xml --profiles xccdf_org.ssgproject.content_profile_stig
Traceback (most recent call last):
  File "/var/ossec/wodles/oscap/oscap.py", line 401, in <module>
    oscap(profile)
  File "/var/ossec/wodles/oscap/oscap.py", line 110, in oscap
    mkfifo(FIFO_PATH, 0666)

Chage mkfifo(FIFO_PATH, 0666) to mkfifo(FIFO_PATH, 0o666) make it work.

Best regards.

**Comment by chemamartinez** [comment]
Hi @mdiavm,

Thank you so much for reporting this bug and suggest a solution for it.

I have already submitted [a pull request](https://github.com/wazuh/wazuh/pull/5317) to let the issue solved for future Wazuh releases. It will be reviewed and merged ASAP.

Best regards,
Chema.

**Comment by chemamartinez** [comment]
Merged the fix for this issue (#5317)

It will be included in the next release.

Best regards.
