### ISSUE TITLE
.spec file used for building RPMs?

### ISSUE THREAD

**Issue by valorcz** [wazuh/wazuh#53]
Hello,

I'd like to rebuild ossec-wazuh RPM packages for our environment, but I cannot find any up-to-date .spec file. It's probably just me, but can you help me with that? How do you build your RPMs? 

Thank you,
Vaclav

**Comment by jlruizmlg** [comment]
Hello @valorcz , we will release the .spec files and debs installers with the new release as soon as possible.

**Comment by valorcz** [comment]
That would be awesome, thank you!

**Comment by jlruizmlg** [comment]
Hello @valorcz  we have a new repository with the debian files and rpm spec in order create Wazuh packages.

https://github.com/wazuh/wazuh-packages
