### ISSUE TITLE
Wazuh Decoder Kaspersky  CEF Log error 

### ISSUE THREAD

**Issue by rokitoh** [wazuh/wazuh#5307]
Wazuh version - 3.12.3-1

I get trouble while writing decoder for Kaspersky CEF logs.
Here is the example:
Example log:

`CEF:0|KasperskyLab|SecurityCenter|11.0.0.1131|GNRL_EV_VIRUS_FOUND_AND_BLOCKED|Dangerous link blocked|4|msg=Event type:     Dangerous link blocked\r\nApplication:     Google Chrome\r\nApplication\\Name:     chrome.exe\r\nApplication\\Path:     C:\\Program Files (x86)\\Google\\Chrome\\Application\\\r\nApplication\\Process ID:     14944\r\nUser:     PEPITO (Active user)\r\nComponent:     Web Threat Protection\r\nResult\\Description:     Blocked\r\nResult\\Type:     Threat of data loss\r\nResult\\Name:     https://www.brunoferrini.com.pe/favicon.ico\r\nResult\\Threat level:     High\r\nResult\\Precision:     Exactly\r\nObject:     https://www.brunoferrini.com.pe/favicon.ico\r\nObject\\Type:     Web page\r\nObject\\Path:     https://www.brunoferrini.com.pe/favicon.ico\r\nObject\\Name:     favicon.ico\r\nReason:     Automatic analysis\r\nDatabase release date:     22/06/2020 09:14:00\r\n rt=1592928663000 cs9=SERVER01 cs9Label=GroupName dhost=SERVER01 dst=192.168.1.2 cs2=KES cs2Label=ProductName cs3=11.0.0.0 cs3Label=ProductVersion cs10=Web Threat Protection cs10Label=TaskName cs5=https://www.brunoferrini.com.pe/favicon.ico cs5Label=ObjectName cs1=https://www.brunoferrini.com.pe/favicon.ico cs1Label=VirusName duser=PEPITO cs6=70 cs6Label=DetectionType cs7={"engine":3,"method":5} cs7Label=ExtraAttrib `

If I write decoder this way, I get all parameters from order tag:

[decoder.txt](https://github.com/wazuh/wazuh/files/4824232/decoder.txt)

![image](https://user-images.githubusercontent.com/61008657/85524658-a73ce180-b608-11ea-8335-fbd0d96ff4d2.png)

Can you help me please? I can't understand where is my fault.

**Comment by vikman90** [comment]
Hi @rokitoh,

The structure is good, but I see some problems with the regexes. Let me give you some points about them:

### dhost

```xml
<regex>"(\.+)"dhost="(\.+)"</regex>
```

There are two groups, but one field only (in `<order>`). I can't find the double-quotes in the input log, they will prevent the regex from matching the log. In addition, `\.` means "anything", so it would match the rest of the log.

This regex seems to work:
```xml
<regex>dhost=(\S+)</regex>
```

### dstip

Your regex:
```xml
<regex>dst=(\d+.\d+.\d+.\d+):(\d+)\S*</regex>
```

It's forcing the input to contain a colon. If you need to match both "X.Y.Z.W" and "X.Y.Z.W:P", this will work:

```xml
<regex>dst=(\d+.\d+.\d+.\d+:\d+)|dst=(\d+.\d+.\d+.\d+)</regex>
```

### Kaspersky.cs1

```xml
<regex>cs1="(\.+)"</regex>
```

Just like `dhost`, I think we should remove the double quotes and replace `\.` with `\S`:

```xml
<regex>cs1=(\S+)</regex>
```

## Result

I could extract these fields applying the changes above:

```
**Phase 2: Completed decoding.
       decoder: 'Kaspersky'
       dhost: 'SERVER01'
       dstip: '192.168.1.2'
       Kaspersky.cs1: 'https://www.brunoferrini.com.pe/favicon.ico'
```

I'm sure you will find the fixes for the rest of the regexes. Please let me know if you need further help with them.

Hope this helps.
Best regards.

**Comment by rokitoh** [comment]
Hi @vikman90
Thank you very much!
Best regards,
rokitoh
