### ISSUE TITLE
Syscollector: collect network data

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#531]
- [X] Get data about network interfaces and addresses.-
- [X] Join address + netmask + broadcast.
- [X] Remove support for CentOS 5 to allow compilation.
- [X] Dropped packages (Linux)
- [x] Dropped packages (BSD)
- [x] Dropped packages (Windows)

**Comment by vikman90** [comment]
Get dropped packages in Linux: https://github.com/wazuh/wazuh/commit/b0b3d795d1f6b22fb3456fe69faf0e663a14b78f

**Comment by chemamartinez** [comment]
Dropped packets (Windows): https://github.com/wazuh/wazuh/commit/1650fa1d3e3b35851e901aa757715fcb6c902a62

Dropped packets (BSD): https://github.com/wazuh/wazuh/commit/a3758f5278be8d3385a8a47dd8bc8e2129a8a2d0
