### ISSUE TITLE
Syscollector: get application inventory natively

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#532]
- [X] Linux/DEB
- [X] Linux/RPM
- [x] Windows
- [x] macOS
- [ ] BSD

**Comment by vikman90** [comment]
@chemamartinez Please add the registry HKEY where the application data is gathered from. This is very valuable for Vulnerability Detector to find applications in registry tests.

**Comment by chemamartinez** [comment]
macOS inventory: https://github.com/wazuh/wazuh/pull/554/commits/536d0730bca24b5407db4d41449dcc7c8688af8c
