### ISSUE TITLE
How to pull  mongodb logs with Wazuh agent?

### ISSUE THREAD

**Issue by sawant23** [wazuh/wazuh#5320]
I did following settings on /var/ossec/etc/ossec.conf   and after that I  restart agent but its **not show logs** on kibana dashboard 

```
<localfile>
    <log_format>syslog</log_format>
    <location>/var/log/mongodb/mongod.log</location>
  </localfile>

```
I also want to pull following log:
Node js logs
Rabbitmq logs
Redis logs
Mysql logs
Python logs
Dot Net Logs

**Comment by JcabreraC** [comment]
Hello sawant23

Which version of MongoDB are you using? Could you share a sample log?

Perhaps you are using a different timestamp than the one Wazuh needs to check the rules and decoders.

To work properly, the `timeStampFormat` must have the value `iso8601-local` on MongoDB configuration.

Greetings:
Juan Cabrera

**Comment by JcabreraC** [comment]
Hi sawant23

Let me close this issue due to inactivity. Do not hesitate to reopen it if the problem persists or you have further questions.

Kind regards.
