### ISSUE TITLE
Support for pulling messages from multiple GCP pubsub topics

### ISSUE THREAD

**Issue by amit-k-yadav** [wazuh/wazuh#5336]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.13.0 | configuration | -- | -- | -- |

### Overview

Hello Everyone,

I was testing out recently released Google Cloud Platform Integration ([gcp-pubsub](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/gcp-pubsub.html)) and I would like to submit a feature request of supporting multiple blocks of `gcp-pubsub` (or some other way) to read logs/messages from more than one [GCP Pub-Sub](https://cloud.google.com/pubsub) topics.

Currently, if we have more than one block of this configuration, only the last one is considered and others get ignored.

### How to reproduce

* Create multiple topics and subscriptions in GCP pub-sub using the following [gcloud](https://cloud.google.com/pubsub/docs/quickstart-cli) commands:
  ```sh

  # Create topics
  gcloud pubsub topics create wazuh-test-1
  gcloud pubsub topics create wazuh-test-2

  # Create subscriptions
  gcloud pubsub subscriptions create sub-wazuh-test-1 --topic=wazuh-test-1
  gcloud pubsub subscriptions create sub-wazuh-test-2 --topic=wazuh-test-2

  # Publish sample messages
  gcloud pubsub topics publish wazuh-test-1 --message="message from wazuh-test-1"
  gcloud pubsub topics publish wazuh-test-2 --message="message from wazuh-test-2"
  ```

* Edit `/var/ossec/etc/ossec.conf` file in order to have two different blocks of `<gcp-pubsub>` for the above two subscriptions

  ```xml
  <gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1m</interval>
    <project_id>project123</project_id>
    <subscription_name>sub-wazuh-test-1</subscription_name>
    <logging>debug</logging>
    <credentials_file>/path/to/credentials.json</credentials_file>
  </gcp-pubsub>

  <gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>1m</interval>
    <project_id>project123</project_id>
    <subscription_name>sub-wazuh-test-2</subscription_name>
    <logging>debug</logging>
    <credentials_file>/path/to/credentials.json</credentials_file>
  </gcp-pubsub>
  ```
* Restart Wazuh manager or Wazuh agent depending on where this configuration is, set `wazuh_modules.debug=2` in `WAZUH_PATH/etc/local_internal_options.conf` and finally check the logs using `tail -f /var/ossec/logs/ossec.log | grep gcp` command

### Expected behavior
* Both the messages (`message from wazuh-test-1` and `message from wazuh-test-2`) should be received and logged

### Actual behavior
* Only the messages related to the second block is received and logged (i.e. `message from wazuh-test-2`)

### Inputs
* If having more than one block of `gcp-pubsub` seems like a repetitive way of configuration, then supporting multiple `<subscription_name>` (if possible and suitable) will also do the work.

Thanks!

**Comment by davidjiglesias** [comment]
Hello @amit-k-yadav,

Thank you so much for your contribution, it helps to keep Wazuh growing. Our team will study your proposal for future releases. 

In the meantime, I would like to add that you can obtain the same behaviour you are looking for by merging both subscriptions and having just one with any neccesary filters on your Google Cloud Platform. You could also have several wazuh-managers or agents pull the different logs. I know it is not the exact same behavior you propose but I thought it might do the trick and be useful for you.

Best regards,

David J. Iglesias

**Comment by amit-k-yadav** [comment]
Hi @davidjiglesias ,

Yes, currently I am using a single filter that is nothing but _all the existing filters combined with **_OR_** condition_.

Thanks.

**Comment by dangzed** [comment]
Hi, any update about the issue? In my case I'd rather not merge both subscriptions because they belong to 2 different projects. It would be nice if I can have multiple gcp-pubsub block in the configuration

**Comment by davidjiglesias** [comment]
We have finally decided not to go with this development. We think we have everything in place to be able to overcome this by using several agents, as we initially intended with the GCP integration.

**Comment by anthonytwh** [comment]
@davidjiglesias Only allowing 1 gcp_pubsub per configuration is not ideal. If we have 10 projects and a pub/sub topic/subscription for each, is the expectation to deploy 10 agents (one per project) to collect and forward logs to wazuh manager? This seems excessive..
