### ISSUE TITLE
Wazuh-logtest: Implement logtest as a thread of analysisd

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#5337]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.0 | Analysisd | Manager | Packages/Sources | Linux |

Hello team,

ossec-logtest is a useful tool for testing and verification of rules and decoders. Users can test their custom ruleset before adding it in a production environment.

Although it is a good tool, there are some issues in Logtest:
1. UI can't use it. The users must access the server where the wazuh-manager is installed and execute the binary in the console. 
2. Can't test rules and decoders for eventchannel events, syscheck events, the events collected with different logcollector formats (mysql, postgresql, command, full_command), etc.

This development aims to deprecate the ossec-logtest in favor of  wazuh-logtest.

This new tool will be an Analysisd thread which listens in AF_UNIX socket. Multiples clients can be connected. The server processes their requests and responds. The communication messages will be in JSON format.

Additionally, wazuh-logtest must allow testing more events than ossec-logtest.

Best regards,
Core team.

***

|**Working branch**|
|---|
|feature/5337-logtest-enhancement|

**Comment by JcabreraC** [comment]
# Current status of ossec-logtest

Currently, logtest runs as a separate wazuh-manager program. This makes it easier to check rules, decoders and cdb lists that the manager does not have in memory, as each process has its own rule and decoder lists, its frequency, fts, timeframe, etc. This does not conflict with the state of Analysisd.

To differentiate the log flow of Analysisd and Logtest, the `TESTRULE` flag is used.

The logtest code can be found in the `testrule.c` file.

## Logtest control flow 
### Program Initialization:

1. Read the configuration to load the rules
2. Obtains the name of the server and removes the part of the domain if it is available
3. Check that the user/group is valid.
4. Create an event list using the `OS_CreateListEvent` function
5. Initialization of the decoders: 
a. Create and initialize the decoder list with `OS_CreateOSDecoderList`
b. If there is no decoder list in the global configuration file, read the decoders and reload them based on the `ossec.conf` file. Read the local decoder list.
     1. If there is a list of decoders in the global configuration file, it loads them from the ossec.conf file.
c. Load the decoders with `SetDecodeXML`
6. Initialization of the lists.
7. Initialization of the rules: 
a. Create the rule list with `Rules_OP_CreateRules`
b.  Read the rules.
c. Find all rules that require list searches and attach the correct list structure to the rule with `OS_ListLoadRules`
8. Initialize the analysisd queues with the function `w_init_queues`
9. Sets the total number of enabled rules.
10. Creates a hash table of rules to read alerts from other servers.
11. Prepares the user.
12. Launches the startup message.

### Log analysis
Log analysis has three phases:

1. Pre-processing:
- The message is received from the queue.
- The time at which the event was received is obtained.
- Blank lines and line feed are ignored
- The default values for the event are configured. 
- The `OS_CleanMSG` function divides the log in four fields: timestamp, hostname, program-name, log (message). It stores it in the event.

2. Decoders:
- The size of the log is obtained.
- Osdecoders decode the received event and obtain useful information using the function DecodeEvent
- Data from events that share the same ID are grouped together.

3. Rules

- Get the first rule with `OS_GetFirstRule` and start a loop through all
- If the event is an "alert" type, process the alert
  - If not, check that the category matches the event type
  - If not, check for each rule whether the current rule matches the event information.
- A pointer is created to the rule that has been generated.
- Level 0 is ignored
- Check the ignore time. If the time the rule was ignored is less than the time it should be ignored, do not alert again.
- Check if the event should be ignored.
- Checks if it should be added to the ignore list. 
- Shows the alert if it's configured
- Check if the rule is if_matched_sid. If so, it copies the structure to its status memory.
- Checks if the rule is if_matched_group. If so, it copies the structure to its status memory.
- Adds the event to the list of previous events with `OS_AddEvent`
4. The information is removed and the memory deleted only if the event was not added to the status memory.

**Comment by JcabreraC** [comment]
# Design of Wazuh-logtest

## Requirements
- It won't be a separate program anymore. Now it'll be a thread listening on a local socket (AF_UNIX).
- The input and output will be in JSON format.
- The input JSON will have a log or event field with the log in RAW.
- Multiple simultaneous and independent sessions should be allowed.
- The ruleset folder is common (several users compete for it), and each Logtest request will involve a ruleset parsing + log analysis.
- There will be a reload of rules.
- If the rules or decoders are not correct, the service reports the faults, but will not stop the execution.
- In a cluster, only the master can execute Logtest. The workers will send requests to the master.
- There must be a `"Save"` and an `"Apply changes"`. `"Apply changes"` will cause the manager to restart
`"save"` will only save.

**Comment by juliancnn** [comment]
> `Output`:
> 
> ```
> {
>     "timestamp":"2020-06-24T11:28:09.308+0200",
>     "rule":{
>         "level": 3,
>         "description":"Successful sudo to ROOT executed.",
>         "id":"5402",
>         "mitre":{
>             "id":["T1169"],
>             "tactics":["Privilege Escalation" ]
>             },
>         "firedtimes":1,
>         "mail":false,
>         "groups":[ "syslog", "sudo" ],
>         "pci_dss":[ "10.2.5", "10.2.2" ],
>         "gpg13":[
>             "7.6",
>             "7.8",
>             "7.13"
>         ],
>         "gdpr":[ "IV_32.2"],
>         "hipaa":[ "164.312.b"],
>         "nist_800_53":[ "AU.14", "AC.7", "AC.6" ],
>         "tsc":["CC6.8","CC7.2","CC7.3"]
>     },
>     "agent":{
>         "id":"000",
>         "name":"master"
>     },
>     "manager":{
>             "name":"master"
>     },
>     "id":"1592990889.62076",
>     "full_log":"Jun 24 11:28:09 master sudo: master : TTY=pts/0 ; PWD=/home/master ; USER=root ; COMMAND=/bin/su",
>     "predecoder":{
>         "program_name":"sudo",
>         "timestamp":"Jun 24 11:28:09",
>         "hostname":"master"
>     },
>     "decoder":{
>         "parent":"sudo",
>         "name":"sudo",
>         "ftscomment":"First time user executed the sudo command"
>     },
>     "data":{
>         "srcuser":"master",
>         "dstuser":"root",
>         "tty":"pts/0",
>         "pwd":"/home/master",
>         "command":"/bin/su"
>     },
>     "location":"/var/log/auth.log"
> }
> ```

We should add an error field and its description to output msg, this will make the task of the frontend easier, what do you think?

**Comment by JcabreraC** [comment]
# New communication protocol

Adapted the new communication protocols for the Wazuh demons.

The design of the new protocol is defined in the following issue: https://github.com/wazuh/wazuh/issues/5934

## Examples remove_session

### Protocol error example (invalid token field)

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "remove_session",
    "parameters": {
        "token": 6
    }
}
```

Expected output
```
{
    "error": 7316,
    "data": {},
    "message": "Failure to remove session. remove_session JSON field must be a string"
}
```

### Internal wazuh-log test error (Session not found)

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "remove_session",
    "parameters": {
        "token": "12345678"
    }
}
```

Expected
```
{
    "error": 0,
    "data": {
        "messages": [
            "ERROR: (7004): No session found for token '12345678'"
        ],
        "codemsg": -1
    }
}
```

### Successful 
 
Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "remove_session",
    "parameters": {
        "token": "15915911"
    }
}
```

Expected output
```
{
    "error": 0,
    "data": {
        "messages": [
            "INFO: (7206): The session '{}' was closed successfully"
        ],
        "codemsg": 0
    }
}
```

## Examples log_processing (Invalid inputs)

### Missing field event

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "log_format": "syslog",
        "location": "master->/var/log/syslog"
    }
}
```

Expected output
```
{
    "error": 7313,
    "data": {},
    "message": "'event' JSON field not found or is empty"
}
```

### Missing field log_format

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",
        "location": "master->/var/log/syslog"
    }
}

```

Expected output
```
{
    "error": 7308,
    "data": {},
    "message": "'log_format' JSON field is required and must be a string"
}
```

### Missing field location

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",
        "log_format": "syslog"
    }
}

```

Expected output
```
{
    "error": 7308,
    "data": {},
    "message": "'location' JSON field is required and must be a string"
}
```

### Missing event/log_format

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "location": "master->/var/log/syslog"
    }
}
```

Expected output (Only returns the first error)
```
{
    "error": 7308,
    "data": {},
    "message": "'log_format' JSON field is required and must be a string"
}
```

### Missing event/location

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "log_format": "syslog"
    }
}
```

Expected output
```
{
    "error": 7308,
    "data": {},
    "message": "'location' JSON field is required and must be a string"
}
```

### Missing log_format/location

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756."
    }
}
```

Expected output
```
{
    "error": 7308,
    "data": {},
    "message": "'location' JSON field is required and must be a string"
}
```

### Empty data

Input
```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token": "4885bbf4",
        "event": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756."
    }
}
```

Expected output
```
{
    "error": 7308,
    "data": {},
    "message": "'location' JSON field is required and must be a string"
}
```

## Example log_processing OK

### Input:

```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "event": "Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928",
        "location": "master->/var/log/syslog",
        "log_format": "syslog"
    }
}
```

### Output:

```
{
    "error": 0,
    "data": {
        "token": "ed528f12",
        "messages": [
            "INFO: (7202): Session initialized with token 'ed528f12'"
        ],
        "output": {
            "timestamp": "2020-09-18T13:39:37.185+0000",
            "rule": {
                "level": 5,
                "description": "sshd: Attempt to login using a non-existent user",
                "id": "5710",
                "mitre": {
                    "id": [
                        "T1110"
                    ]
                },
                "firedtimes": 1,
                "mail": false,
                "groups": [
                    "syslog",
                    "sshd",
                    "invalid_login",
                    "authentication_failed"
                ],
                "pci_dss": [
                    "10.2.4",
                    "10.2.5",
                    "10.6.1"
                ],
                "gpg13": [
                    "7.1"
                ],
                "gdpr": [
                    "IV_35.7.d",
                    "IV_32.2"
                ],
                "hipaa": [
                    "164.312.b"
                ],
                "nist_800_53": [
                    "AU.14",
                    "AC.7",
                    "AU.6"
                ],
                "tsc": [
                    "CC6.1",
                    "CC6.8",
                    "CC7.2",
                    "CC7.3"
                ]
            },
            "agent": {
                "id": "000",
                "name": "30-u20-manager"
            },
            "manager": {
                "name": "30-u20-manager"
            },
            "id": "1600436377.0",
            "full_log": "Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928",
            "predecoder": {
                "program_name": "sshd",
                "timestamp": "Oct 15 21:06:59",
                "hostname": "linux-agent"
            },
            "decoder": {
                "parent": "sshd",
                "name": "sshd"
            },
            "data": {
                "srcip": "18.18.18.18",
                "srcport": "48928",
                "srcuser": "blimey"
            },
            "location": "master->/var/log/syslog"
        },
        "alert": true,
        "codemsg": 0
    }
}
```

## Error parsing json (a quote is missing in token field)

### Input:

```
{
    "version": 1,
    "origin": {
        "name": "Integration Test",
        "module": "api"
    },
    "command": "log_processing",
    "parameters": {
        "token":  4ee2ed51",
        "event": "Aug  7 15:14:52 eva sshd[27810]: Invalid user edith from 200.94.18.3",
       "log_format":  "syslog","location": "master->/var/log/syslog"
    }
}
```

### Output:

```
{
    "error": 7306,
    "data": {
    },
    "message": "Error parsing JSON"
}
```

**Comment by juliancnn** [comment]
Scan build [report-scan.zip](https://github.com/wazuh/wazuh/files/6778954/scan.zip):

![image](https://user-images.githubusercontent.com/1891958/124801535-535c1c80-df2d-11eb-9728-af9d02510e85.png)

[Valgrind_report.log](https://github.com/wazuh/wazuh/files/6778977/ValgrindPRs.log):

```
==293912== HEAP SUMMARY:
==293912==     in use at exit: 19,296,974 bytes in 103,644 blocks
==293912==   total heap usage: 1,397,036 allocs, 1,293,392 frees, 4,537,489,899 bytes allocated
==293912== 
==293912== LEAK SUMMARY:
==293912==    definitely lost: 0 bytes in 0 blocks
==293912==    indirectly lost: 0 bytes in 0 blocks
==293912==      possibly lost: 52,768 bytes in 194 blocks
==293912==    still reachable: 19,244,206 bytes in 103,450 blocks
==293912==         suppressed: 0 bytes in 0 blocks
==293912== Reachable blocks (those to which a pointer was found) are not shown.
==293912== To see them, rerun with: --leak-check=full --show-leak-kinds=all
```


Logtest API test
```console
  go run ./wazuh_sock.go -f /var/ossec/queue/sockets/logtest -m '{"version":1,"origin":{"name":"Integration Test","module":"api"},"command":"log_processing","parameters":{"event":"Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928","location":"master->/var/log/syslog","log_format":"syslog","options":{"rules_debug": true}}}'
  go run ./wazuh_sock.go -f /var/ossec/queue/sockets/logtest -m '{"version":1,"origin":{"name":"Integration Test","module":"api"},"command":"log_processing","parameters":{"token":"73ad4927","event":"Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928","location":"master->/var/log/syslog","log_format":"syslog","options":{"rules_debug": false}}}'
  go run ./wazuh_sock.go -f /var/ossec/queue/sockets/logtest -m '{"version":1,"origin":{"name":"Integration Test","module":"api"},"command":"log_processing","parameters":{"token":"73ad4927","event":"Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928","location":"master->/var/log/syslog","log_format":"syslog","options":{"rules_debug": "test"}}}'
  go run ./wazuh_sock.go -f /var/ossec/queue/sockets/logtest -m '{"version":1,"origin":{"name":"Integration Test","module":"api"},"command":"log_processing","parameters":{"token":"73ad4927","event":"Oct 15 21:06:59 linux-agent sshd[29205]: Invalid user blimey from 18.18.18.18 port 48928","location":"master->/var/log/syslog","log_format":"syslog","options":"rules_debug"}}'
  go run ./wazuh_sock.go -f /var/ossec/queue/sockets/logtest -m '{"version":1,"origin":{"name":"Integration Test","module":"api"},"command":"remove_session","parameters":{"token":"73ad4927"}}'
```
