### ISSUE TITLE
Any known limit of Agents using UDP?

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh#5343]
Wazuh version: 3.12.3
RPM Install
Red Hat Enterprise Linux 7.7

We replacing our old Ossec Installation with new Wazuh System.
There are serval Wazuh-Manager.
One runs fine with about 1023 Clients.
The other, same installation, runs fine till 1039 Clients, then these Message repeats for every Client 

2020/06/26 13:30:33 ossec-remoted: ERROR: (1218): Unable to send message to '6627': Invalid argument [-1]
2020/06/26 13:30:33 ossec-remoted: ERROR: (1218): Unable to send message to '3298': Invalid argument [-1]
2020/06/26 13:30:33 ossec-remoted: ERROR: (1218): Unable to send message to '2866': Invalid argument [-1]
2020/06/26 13:30:33 ossec-remoted: ERROR: (1218): Unable to send message to '2861': Invalid argument [-1]
2020/06/26 13:30:33 ossec-remoted: ERROR: (1218): Unable to send message to '2853': Invalid argument [-1]

In total there are about 2040 Agents registered.
When i disable 1000 Agents, every things runs fine again.
What is this for an Limit? nofile is 65536, I dont see any Message with an Error.

**Comment by 0xN3utr0n** [comment]
Hi @Joeri-MS,
The limit per manager is about 14.000 agents, although that's just on paper. In a real environment, it's up to your available resources; for instance, in your scenario it seems there is probably a network bottleneck as soon as you reach the 1000 agents.

Correct me if Im wrong, but from your message I deduce you haven't deployed a Cluster with a proper load balancer. I highly recommend you to do so, it's the way to go when dealing with a huge number of agents. For more information you can read our [documentation](https://documentation.wazuh.com/3.13/user-manual/configuring-cluster/index.html). 

Kind regards,
Fernando

**Comment by Joeri-MS** [comment]
I found my mistake.....

The ARP Cache size:

net.ipv4.neigh.default.gc_thresh1 = 128
net.ipv4.neigh.default.gc_thresh2 = 512
net.ipv4.neigh.default.gc_thresh3 = 1024

With 

net.ipv4.neigh.default.gc_thresh1 = 128
net.ipv4.neigh.default.gc_thresh2 = 4096
net.ipv4.neigh.default.gc_thresh3 = 65536

every problem seems sovled.
