### ISSUE TITLE
Unify and standardize error response for HTTP code 400 in the new API

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5345]
Hello team,

As part of the development to get new Wazuh API 4.0 ready for production use we should ensure the response structure for the HTTP code 400 follows an unified standard structure.

Actually, the error response varies depending on whether it is generated by Connexion at the spec level, the API/framework or the cluster in another node. 

Connexion example:
```json
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'{\\n  \"arguments\": sr\\n}' is not of type 'object'",
  "status": 400
}
```
Framework example:
```json
{
    "type": "about:blank",
    "title": "Wazuh Error",
    "detail": "Body is empty",
    "status": 400,
    "remediation": "Please, check the content of the file to be uploaded",
    "code": 1912,
    "dapi_errors": {}
}
```
Each one of these error responses should follow the same structure. We can include an exception handler for `connexion` raised exceptions.

Best regards,

David J. Iglesias

**Comment by CarlosRS9** [comment]
# Status update

In order to come up with an unified response standard we analyzed well-known APIs such as Docker or Kubernetes APIs, among others. None of these APIs have our `type`, `title` or `status` fields and they are not essentials for us. Because of that, we are checking the impact of their removal from our responses standard. The `status` field removal could be tricky as we use this field internally, but we can hide it from the fianl responses by using a middleware if needed.

**Comment by CarlosRS9** [comment]
# Status update

To unify the responses we need to be able to catch and adapt responses from connexion/aiohttp. For example, when a spec requirement is not met. 

We have explored various ways to accomplish this by using middlewares, a custom exception handler for connexion and other solutions. We are currently working on the custom exception handler approach.

**Comment by CarlosRS9** [comment]
# Status Update

We found the following issues on connexion's github regarding this topic and we are working following this advice:

https://github.com/zalando/connexion/issues/138 `Any possibility to override default validation error message?`
https://github.com/zalando/connexion/issues/550 `Overriding route-specific 404s to a custom response`
https://github.com/zalando/connexion/issues/558 `Custom validation error handler`

**Comment by CarlosRS9** [comment]
# Status Update

A new middleware has been implemented to handle `connexion.exceptions` and apply the expected format to their responses. 

Here is an example of the response before this change:

```
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'AAA' is not a 'numbers'\n\nFailed validating 'format' in schema['items']:\n    {'description': 'Agent ID',\n     'format': 'numbers',\n     'minLength': 3,\n     'type': 'string',\n     'x-scope': ['', '#/components/parameters/list_agents']}\n\nOn instance[0]:\n    'AAA'",
  "status": 400
}
```

And here is the response we return now:

```
{
  "detail": "'AAA' is not a 'numbers'. Failed validating 'format' in schema['items']: {'description': 'Agent ID', 'format': 'numbers', 'minLength': 3, 'type': 'string', 'x-scope': ['', '#/components/parameters/list_agents']}. On instance[0]: 'AAA'"
}
```


## Pending tasks

* Choose the standard format we plan to follow for all the responses, including `connexion` exceptions.
* Apply the modifications needed to use this new format.

**Comment by CarlosRS9** [comment]
# Status Update

Here is the standard we plan to follow from now on:

```
{
    "title": Mandatory,
    "detail": Mandatory,
    "remediation": Optional,
    "code": Optional,
    "dapi_errors": Optional
}
```
Changes: 
* `type` will be removed
* `title` content will be changed. Now will contain the exception type (e.g. Permission denied)
* `detail` will not contain the exception type.
* `status` will be removed


**Example of Connexion response**
```
{
  	"title": "Bad Request",
  	"detail": "'AAA' is not a 'numbers'. Failed validating 'format' in schema['items']: {'description': 'Agent ID', 'format': 'numbers', 'minLength': 3, 'type': 'string', 'x-scope': ['', '#/components/parameters/list_agents']}. On instance[0]: 'AAA'"
}
```

**Example of Permission Denied response**
```
{
  "title": "Permission denied",
  "detail": "Resource type: *:*",
  "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html",
  "code": 4000,
  "dapi_errors": {
    "unknown-node": {
      "error": "Permission denied: Resource type: *:*"
    }
  }
}
```

**Comment by CarlosRS9** [comment]
# Status Update

Development is finished unless new changes are required. The code can be checked in `dev-5345-standarize-resposes` branch.

* The middleware was updated again to match the required output for the responses.

* A new WazuhPermissionError exception was created and previous Wazuh exception in `exception.py` has been updated use `type` and `title` parameters. Each exception class have its default type and title. The default types will be updated in the future once we have the URIs needed.

* ProblemException raised in `utils.py` will use the new type and title from its original Wazuh exception from now on.

* `spec.yaml` has been updated to add the new generic example for 400 and 403 responses.

### Response examples

Here is the generic response for 400:
```
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'{invalid_param}' is not a '{expected_type}'. Failed validating 'format' in schema['items']: {'description': '{parameter_name}', 'format': '{expected_format}', 'minLength': {expected_length}, 'type': '{expected_type}', 'x-scope': ['', '#/components/parameters/{parameter_name}']}."
}
```

This is the generic response example for 403:
```
{
  "type": "about:blank",
  "title": "Permission Denied",
  "detail": "Permission denied: Resource type: *:*",
  "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html",
  "code": 4000,
  "dapi_errors": {
    "unknown-node": {
      "error": "Permission denied: Resource type: *:*"
    }
  }
}
```

And finally, here is a real example of a 400 response:
```
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'AAA' is not a 'numbers'. Failed validating 'format' in schema['items']: {'description': 'Agent ID', 'format': 'numbers', 'minLength': 3, 'type': 'string', 'x-scope': ['', '#/components/parameters/list_agents']}. On instance[0]: 'AAA'"
}
```

**Comment by vicferpoy** [comment]
# Status update
Development is finished. New changes were added after discussing the design again.

## Response examples
- 400 - Framework response
```json
{
  "type": "about:blank",
  "title": "WazuhInternalError",
  "detail": "Error trying to load the JWT secret",
  "remediation": "Make sure you have the right permissions: WAZUH_PATH/api/configuration/security/jwt_secret",
  "code": 6003
}
```

- 400 - Bad request from spec (malformed body)
```json
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "'\"invalid\": \"invalid\"' is not of type 'object'"
}
```

- 400 - Bad request from framework (wrong fields in body)
```json
{
  "type": "about:blank",
  "title": "Bad Request",
  "detail": "Invalid field found {'invalid'}"
}
```

- 403 - Permission denied
```json
{
  "type": "about:blank",
  "title": "Permission Denied",
  "detail": "Permission denied: Resource type: agent:id",
  "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/current/user-manual/api/rbac/configuration.html",
  "code": 4000,
  "dapi_errors": {
    "unknown-node": {
      "error": "Permission denied: Resource type: agent:id"
    }
  }
}
```

- 404 - Resource not found
```json
{
  "type": "about:blank",
  "title": "WazuhResourceNotFound",
  "detail": "The group does not exist",
  "remediation": "Please, use `GET /agents/groups` to find all available groups",
  "code": 1710,
  "dapi_errors": {
    "master-node": {
      "error": "The group does not exist",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  }
}
```

## Pending
- Add 404 to spec.
- Update integration tests to expect a 404 when the resource does not exist.

**Comment by vicferpoy** [comment]
# Status update
With the integration tests, new errors were caught:

- When the spec detects a wrong parameter, an `ExtraParameterProblem` is raised. We were not handling these errors properly and they had a different format. Since this is managed by the spec, we can only format this in the middleware. This was solved but needs a revision because it is not flexible at all. 

- Any `Unauthorized` response will have the `status` field even though we are removing it in the middleware. This cannot be handled by our current design because the problem does not inherit from `ProblemException`, it inherits from `OAuthProblem` (`Unauthorized`). This means it has different attributes and thus it is not compatible with the `problem` function from `connexion`. We need to further investigate this.

All integration tests pass and the spec has been updated.

**Comment by CarlosRS9** [comment]
# Status update

* The middleware has been improved to handle `ExtraParameterProblem` and `OAuthProblem` better. The `status` field is no longer shown in `Unauthorized` responses.

* `type` field has been hide from our responses until we have the proper URIs to be returned for each case.

* Integration tests have been executed to ensure new changes didn't break anything. A few more integration tests are pending but the overall result is ok.

## Pending

* Run the remaining integration tests.

**Comment by CarlosRS9** [comment]
# Status update

Some integration tests must be updated to expect the new response format. We are currently working on this.

**Comment by CarlosRS9** [comment]
# Status Update

Several changes were made to our integration tests to improve and adapt them to the new changes. They are now working fine. We have some problems with the experimental endpoint tests related to ciscat. We are currently looking into it.
