### ISSUE TITLE
Parse Suricata (json) and Snort (snort-full) events from wazuh-agent to Wazuh

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#5348]
Hello,

I am trying to integrate Snort and Suricata with Wazuh, but while I'm seeing the Suricata/ Snort events under their log directory, I do not see any errors in the wazuh-agent log file, but i still dont see anything in Elasticseach. Can you assist in troubleshooting?

I have the below added localfile confiigs in ossec.conf for the agent:

  <localfile>
    <location>C:\Suricata\log\eve.json</location>   
	<log_format>json</log_format>
  </localfile>

  <localfile>
    <location>C:\Snort\log\alert.ids</location>   
	<log_format>snort-full</log_format>
  </localfile>

and this is an example of one of the alerts coming up in Suricata under eve.json:
{"timestamp":"2020-06-28T09:56:08.167548Eastern Daylight Time","flow_id":499404326342268,"in_iface":"\\Device\\NPF_{267E30D9-DD07-4C5F-9CB0-F9B84D7181DC}","event_type":"alert","src_ip":"10.115.1.164","src_port":53105,"dest_ip":"10.1.11.9","dest_port":53,"proto":"UDP","alert":{"action":"allowed","gid":1,"signature_id":2009702,"rev":5,"signature":"ET POLICY DNS Update From External net","category":"Potential Corporate Privacy Violation","severity":1,"metadata":{"updated_at":["2010_07_30"],"created_at":["2010_07_30"]}},"dns":{"query":[{"type":"query","id":21385,"rrname":"sdomain","rrtype":"SOA","tx_id":0}]},"app_proto":"dns","flow":{"pkts_toserver":1,"pkts_toclient":0,"bytes_toserver":156,"bytes_toclient":0,"start":"2020-06-28T09:56:08.167548Eastern Daylight Time"}}

and snort log under alert.ids.
![image](https://user-images.githubusercontent.com/36517441/85950791-e9c62d00-b92c-11ea-85c0-fca20441f7c7.png)

note that snort runs in logging in full.

Any assistance would be GREATLY appreciated!

Thanks,
Tony

**Comment by antonisnyc94** [comment]
I run the ossec-logtest utility and it appears that the issue for the Suricata is that the "timestamp" field contains Eastern Daylight Time. Does anyone know how to control how timestamps are shown by Suricata?

For snort the issue appears that the full snort logs are under multiple lines. Does anyone know how to make snort print them under a single line?

Thanks,
tony

**Comment by Lopuiz** [comment]
Hello

To collect snort logs, you can use the option multi-line in localfile configuration as show below:

` <log_format>multi-line: 5</log_format>`

I have tested it with your logs and it seems works:

```
** Alert 1593415996.63106: - ids,fts,
2020 Jun 29 09:33:16 eva->/home/eva/test2.log
Rule: 20100 (level 8) -> 'First time this IDS alert is generated.'
Src IP: 10.250.0.245
Dst IP: 10.124.0.234:3389
[**] [129:12:1] Consecutive TCP small segment exceeding threshold [**] [Classification: Potentially Bad Traffic] [Priority: 2] 06/28-00:21:55.886573 10.250.0.245:49314 -> 10.124.0.234:3389 TCP TTL:127 TOS:=x0 ID32341 IpLen:20 DgmLen:93 DF ***AP*** Seq: 0xCF80D5E0 Win: 0xFF88 TcpLen: 20
``` 


Regarding the Suricata log, I have tested it. I think the issue is due to the backslash of the `in_iface` field. Following log modified works correctly:

```
{"timestamp":"2020-06-28T09:56:08.167548Eastern Daylight Time","flow_id":499404326342268,"in_iface":"\\Device\\NPF_{267E30D9-DD07-4C5F-9CB0 F9B84D7181DC}","event_type":"alert","src_ip":"10.115.1.164","src_port":53105,"dest_ip":"10.1.11.9","dest_port":53,"proto":"UDP","alert":{"action":"allowed","gid":1,"signature_id":2009702,"rev":5,"signature":"ET POLICY DNS Update From External net","category":"Potential Corporate Privacy Violation","severity":1,"metadata":{"updated_at":["2010_07_30"],"created_at":["2010_07_30"]}},"dns":{"query":[{"type":"query","id":21385,"rrname":"sdomain","rrtype":"SOA","tx_id":0}]},"app_proto":"dns","flow":{"pkts_toserver":1,"pkts_toclient":0,"bytes_toserver":156,"bytes_toclient":0,"start":"2020-06-28T09:56:08.167548Eastern Daylight Time"}}
```


Best regards,
Eva

**Comment by antonisnyc94** [comment]
Hey Eva,

Thanks a ton for your response! I was able to get snort working but with Suricata the issue appears to be the "Eastern Daylight Time" part in timestamp. I am using Suricata for windows, and i was hoping there was an option in the yaml file for either modifying timestamp or removing it.

Thanks,
Tony

**Comment by antonisnyc94** [comment]
I added the below in my filebeat ingested pipeline for ElasticSearch and now it works. Thanks again Eva.

 {
		"gsub": {
		"field": "timestamp",
		"pattern": "...Eastern Daylight Time",
		"replacement": "Z",
		"on_failure" : [
		{
			"set" : {
			"field" : "timestamperror",
			"value" : "failed-{{ _ingest.on_failure_message }}"
				}
		}
					]
			}
		},
	  {
		"gsub": {
		"field": "data.timestamp",
		"pattern": "...Eastern Daylight Time",
		"replacement": "Z",
		"on_failure" : [
		{
		 "set" : {
         "field" : "datatimestamperror",
         "value" : "failed-{{ _ingest.on_failure_message }}"
			}
		}
			]
			}
	  },
