### ISSUE TITLE
Unable to start wazuh server on rpi

### ISSUE THREAD

**Issue by securigeek** [wazuh/wazuh#5354]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Hello Team,

I am trying to install Wazuh 3.9.5 server from sources on my RPI 3B Linux raspberrypi 4.19.118-v7+  , i followed all the steps mentioned under 
![image](https://user-images.githubusercontent.com/33580691/86007760-2458c400-ba18-11ea-9024-70f2a7aad417.png)
and also got a confirmation saying the installation as succesfull
But when I turn to run the services I have an error message as followed: 

```
root@raspberrypi:/home/pi# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/etc/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-06-29 13:45:28 BST; 4min 59s ago
  Process: 322 ExecStart=/usr/bin/env ${DIRECTORY}/bin/ossec-control start (code=exited, status=1/FAILURE)

Jun 29 13:45:21 raspberrypi systemd[1]: Starting Wazuh manager...
Jun 29 13:45:28 raspberrypi env[322]: Traceback (most recent call last):
Jun 29 13:45:28 raspberrypi env[322]:   File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 12, in <module>
Jun 29 13:45:28 raspberrypi env[322]:     from wazuh.cluster import cluster, __version__, __author__, __ossec_name__, __licence__, ma
Jun 29 13:45:28 raspberrypi env[322]: ModuleNotFoundError: No module named 'wazuh'
Jun 29 13:45:28 raspberrypi env[322]: wazuh-clusterd: Configuration error. Exiting
Jun 29 13:45:28 raspberrypi systemd[1]: wazuh-manager.service: Control process exited, code=exited, status=1/FAILURE
Jun 29 13:45:28 raspberrypi systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Jun 29 13:45:28 raspberrypi systemd[1]: Failed to start Wazuh manager.
root@raspberrypi:/home/pi# systemctl start wazuh-manager
Job for wazuh-manager.service failed because the control process exited with error code.
See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.
root@raspberrypi:/home/pi# /var/ossec/bin/ossec-control start
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/wazuh-clusterd.py", line 12, in <module>
    from wazuh.cluster import cluster, __version__, __author__, __ossec_name__, __licence__, master, local_server, worker
ModuleNotFoundError: No module named 'wazuh'
wazuh-clusterd: Configuration error. Exiting
root@raspberrypi:/home/pi#
```

**Comment by danimegar** [comment]
Hello @securigeek 

Wazuh started to support ARM from **v.3.13.0** on. If you can, I recommend you install Wazuh 3.13.0. It is the easiest way.

[Installation guide for Debian/Ubuntu via package](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.html#wazuh-server-packages-ubuntu)

[Installation guide for Debian via source](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_sources_deb.html)

[Installation guide for Ubuntu via source](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_sources_ubuntu.html)

If you prefer the via source, I suggest you execute the following commands:
```
cd wazuh/src
# make clean && make clean-deps
```

Regards,
Daniel

**Comment by danimegar** [comment]
Hello @securigeek 
I am going to close this issue due to inactivity although feel free to reopen it if you need it.

Regards,
Daniel
