### ISSUE TITLE
My custom active response isn't working

### ISSUE THREAD

**Issue by Aviv641999** [wazuh/wazuh#5356]
Hi,
I am using wazuh V3.11.2 in cluster mode on ubuntu 16.04(Xenial), and i have wazuh app on splunk 7.2.
My problem is that my custom active response isnt working properly.
I am trying to confige active response for restarting an auditd service when specific rule is fired, this the the response:

```
#!/bin/bash

ACTION=$1
USER=$2
IP=$3

cd $LOCAL
cd ../
PWD=`pwd`

echo "`date` $0 $1 $2 $3 $4 $5 " >> ${PWD}/../logs/active-response.log

service auditd restart
```

On the ossec.conf of all the servers set the active resaponse and the command:
```

<command>
    <name>restart-auditd</name>
    <executable>/var/ossec/active-response/bin/restart_auditd.sh</executable>
    <expect/>
</command>

<active-response>
    <disabled>no</disabled>
    <command>restart-auditd</command>
    <location>local</location>
    <rules_id>100001</rules_id>
</active-response>

```

The rule trigger and the response isnt running. (no clue in active-response.log)

So i tried to execute it on demand by "agent_control", i entered to my manager and exec:

`
/var/ossec/bin/agent_control -b 0.0.0.0 -f restart-auditd0 -u 100
`

It doesnt work, same for integrity checks and restart agent.
When i try to restart the agent from wazuh app in splunk  it is working.
But then again in Dev tools when i try to restart auditd the agent it is not working

`
PUT /active-response/100/restart-auditd0
`

Thanks for the helpers :)

**Comment by vikman90** [comment]
Hi @Aviv641999.

Your configuration is great but there are a couple of details that are preventing the agent from triggering the AR:

1. The base AR binary location is _/var/ossec/active-response/bin_.

```xml
<executable>/var/ossec/active-response/bin/restart_auditd.sh</executable>
```

I'm pretty sure the agent is printing a log like this:
```
2020/07/03 14:50:35 ossec-execd: INFO: Active response command not present: '/var/ossec/active-response/bin//var/ossec/active-response/bin/restart_auditd.sh'. Not using it on this system.
```

It's joining `/var/ossec/active/response/bin` twice. The correct setting is:

```xml
<executable>restart_auditd.sh</executable>
```

2. The AR script is not reaching the _active-responses.log_ file properly.

The script runs:
```sh
cd $LOCAL
```

But `$LOCAL` is undefined. On the other hand, the correct AR log file is _active-responses.log_ (ending with _s_).

Try out this version of your script:
```sh
#!/bin/bash

ACTION=$1
USER=$2
IP=$3

LOCAL=`dirname $0`
cd $LOCAL
cd ../
PWD=`pwd`

echo "`date` $0 $1 $2 $3 $4 $5 " >> ${PWD}/../logs/active-responses.log

service auditd restart
```

This configuration seems to work. Please try that and let us know if it works for you.

Best regards.
