### ISSUE TITLE
Array access after deallocation

### ISSUE THREAD

**Issue by arshad01** [wazuh/wazuh#538]
Hello,

In syscheckd/run_realtime.c, there seems to be array access after memory deallocation; `free(buf)` followed by access to `buf[6]`:

            // Update database
            snprintf(alert_msg, sizeof(alert_msg), "%.*s%.*s", SK_DB_NATTR, buf, (int)strcspn(c_sum, " "), c_sum);        
            free(buf);

            if (!OSHash_Update(syscheck.fp, file_name, strdup(alert_msg))) {
                merror("Unable to update file to db: %s", file_name);
            }

            alert_msg[OS_MAXSTR] = '\0';
            char *fullalert = NULL;

            if (buf[6] == 's' || buf[6] == 'n') {

Thanks

**Comment by vikman90** [comment]
Hi @arshad01,

Thank you for notifying us. I saw your PR https://github.com/wazuh/wazuh/pull/542 fixing this issue. Please let's continue commenting on the PR.

Let me close this issue.

Best regards.
