### ISSUE TITLE
restore_alerts.conf has misspelled

### ISSUE THREAD

**Issue by demantos** [wazuh/wazuh#539]
I was restore 2.x index to 3.x, but my restored index has no "data.srcip" field.
So, I check config file.

https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/restore_alerts/restore_alerts.conf

at line 17
> rename => { "[scrip]" => "[data2][scrip]" }

not "scrip" but "srcip"

please modify script code

**Comment by BraulioV** [comment]
Hi @demantos ,

thank you for your reporting. We have already fixed in [bcf02e0](https://github.com/wazuh/wazuh/commit/bcf02e03d0dd8181915cce98e06d87f887e33736). 

Thank you very much for your feedback.

Best regards,
Braulio

**Comment by DaveVG1** [comment]
Hi again @demantos,

I hope the aforementioned fix worked for you. As this has been fixed, I'm going to close this issue. If you experience troubles regarding this again, please feel free to re-open it.

Thanks again for reporting this.

Kind regards.
