### ISSUE TITLE
wazuh-logtest configuration

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#5408]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | Logtest | Manager | Packages/Sources | Linux |

Hello team,

For new module wazuh-logtest we will add the configuration shown below in ossec.conf:

```xml
<rule_test>
  <enabled>yes</enabled>
  <threads>1</threads>
  <max_sessions>64</max_sessions>
  <session_timeout>15m</session_timeout>
</rule_test>
```

**Description:**

| Option | Description | Default value | Values allowed |
| --- | --- | --- | --- |
|`enabled`| Determine if logtest is enabled or disabled. | yes | `yes` or `no`. |
|`threads`| Number of wazuh-logtest threads. | 1 | A number between 1 and 128, or `auto` to create one thread per CPU.|
|`max_sessions`| Number of users connected simultaneously. | 64 | A number between 1 and 65534.|
|`session_timeout`| Time interval in which a client must remain offline to remove the resources associated with their session. | 15 minutes | A number to represent seconds, to represent the interval in minutes adds `m`, or `h` to represent the interval in hours. 

Additionally, this issue will be the first task that needs unit and integration tests. We have to create a struct for unit tests and integration tests.

**Tasklist:**
- [x] Read and save the configuration
- [x] Get the configuration
- [x] Unit tests: structure and tests
- [x] Integration tests: structure and tests

Best regards,
Eva

**Comment by JcabreraC** [comment]
This PR also covers issue https://github.com/wazuh/wazuh/issues/5464, defined for the creation of the basic structure of the unitary and integrated tests. In addition, it performs such tests to this new configuration.
