### ISSUE TITLE
 Expose new function on the interface for FIM use cases.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5414]
## Description

Add the proposed interface to cover FIM uses cases

```
 TxnHandle dbsync_create_transaction(DBSYNC_HANDLE handle, char** tables, void* callback, int thread_number, int max_queue_size); // 0 use std::thread::hardware_concurrency, > 0 use value
 int dbsync_sync_txn_row(TxnHandle txn, cJSON* input);				// -> return error code (0- success, > 0 error code)
 int dbsync_get_deleted_rows(TxnHandle txn, void* callback); 		 	// -> return error code (0- success, > 0 error code)
 int dbsync_close_transaction(TxnHandle txn);				 	        // -> block call, return error code (0- success, > 0 error code)
 int dbsync_set_table_max_rows(DBSYNC_HANDLE handle, char* table, unsigned long long)   // -> return error code (0- success, > 0 error code), auxiliary table, which maintains the number of records in a table
 int dbsync_add_table_relationship(DB_HANDLE handle, char* table, char* table_parent, char* key_base, char* parent_field) // -> block call, return error code (0- success, > 0 error code)  insert into auxiliary table -> table_base, table_parent, key_base, parent_field -> multiple key support
 int dbsync_delete_rows(DBSYNC_HANDLE handle, cJSON* key_values); // -> just delete a record and relationship records.
 int dbsync_sync_row(DBSYNC_HANDLE handle, cJSON* input, void* callback); // -> just insert or modify a record.
 int dbsync_select_rows(DBSYNC_HANDLE handle, cJSON* select_input, void* callback);// -> select a series of records with filters, or the possibility of seeing a view..
```

## Tasks / DoD
- [x] Add to the interface and create dummy functions.
- [x] Doxygen update
- [x] Check project compilation

**Comment by tinachoB** [comment]
Following are the **exposed DBSync APIs documentation**:
![image](https://user-images.githubusercontent.com/22640902/86827938-fce1a700-c068-11ea-920c-d1ba27c9b0a4.png)
![image](https://user-images.githubusercontent.com/22640902/86827779-cdcb3580-c068-11ea-9653-bbf474226b4a.png)
![image](https://user-images.githubusercontent.com/22640902/86828068-226eb080-c069-11ea-9c23-81ec81f1f142.png)
![image](https://user-images.githubusercontent.com/22640902/86828763-04ee1680-c06a-11ea-8a64-f2416851aba3.png)
![image](https://user-images.githubusercontent.com/22640902/86829004-4e3e6600-c06a-11ea-9a53-27dde08eceae.png)
![image](https://user-images.githubusercontent.com/22640902/86829133-6e6e2500-c06a-11ea-8bb5-1ed6cc1f253a.png)
![image](https://user-images.githubusercontent.com/22640902/86829203-85147c00-c06a-11ea-934f-5ec166e70b4a.png)
![image](https://user-images.githubusercontent.com/22640902/86829304-a2e1e100-c06a-11ea-8705-e8efe690977d.png)
![image](https://user-images.githubusercontent.com/22640902/86829367-b3925700-c06a-11ea-8875-a74aa634a0f7.png)
![image](https://user-images.githubusercontent.com/22640902/86829475-d45aac80-c06a-11ea-9dba-dcbe63aa6244.png)
![image](https://user-images.githubusercontent.com/22640902/86829573-f05e4e00-c06a-11ea-9316-3d2d33820dbe.png)
![image](https://user-images.githubusercontent.com/22640902/86829667-0ec44980-c06b-11ea-998b-3286456085ef.png)
![image](https://user-images.githubusercontent.com/22640902/86829806-3ca98e00-c06b-11ea-9f9e-7f869035dcc6.png)
![image](https://user-images.githubusercontent.com/22640902/86829868-50ed8b00-c06b-11ea-9279-07b73fa41a7f.png)
![image](https://user-images.githubusercontent.com/22640902/86829911-5fd43d80-c06b-11ea-9d4e-a26b7b14c203.png)
![image](https://user-images.githubusercontent.com/22640902/86829959-711d4a00-c06b-11ea-981d-fd8fb6709d37.png)
