### ISSUE TITLE
Modify agent-control to work with Wazuh DB

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#5428]
### Description

The goal of this issue is to implement the necessary changes to make **agent-control** work with Wazuh DB. This work is part of the Wazuh tools and executables unification process so, we should make sure that the execution for getting the list of agents returns the same information than **cluster-control**.

Definition of done
This modification will be considered as done after having the next items finished:

- [x] Feature implementation.
- [x] Unit test to have 100% of coverage for all the new functions.
- [x] Manual test of the list of agents execution to verify the same result than **cluster-control**.
- [x] Code review approved.

**Comment by pereyra-m** [comment]
There is an issue related to this fix [#5365](https://github.com/wazuh/wazuh/issues/5365).

In a **cluster** scenario, `agent_control -l ` may not give the accurate result

**Comment by DProvinciani** [comment]
Closing the issue as https://github.com/wazuh/wazuh/pull/5776 was merged.
