### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by zuoshouzz** [wazuh/wazuh#544]
How to upgrade from 3.0 to 3.2, whether the connected agent will be disconnected?

**Comment by JuanjiJG** [comment]
Hello @zuoshouzz,

If you don't upgrade your agent, it won't be disconnected. It will lose connection to the manager while it's being updated, but right after finishing the upgrading process, he will connect again to the agents.

If you decide to upgrade your agents, the `wazuh-agent` service will be stopped and later restarted after finishing the upgrade.

Just like I told you in this [previous issue](https://github.com/wazuh/wazuh/issues/524), you can follow our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html) for a proper upgrading process. Don't hesitate to post again if you have more questions.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hello @zuoshouzz,

It's been more than a month since the last response to this issue. I'll proceed to close it. Don't hesitate to open a new one if you have questions or need help with Wazuh.

Regards,
Juanjo
