### ISSUE TITLE
Custom attributes in ossec_conf?

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh#5442]
I am facing a weird issue. In order to simplify a bit ossec.conf, we split each <ossec_conf> into different sections:
- one global,
- one for commands, and
- one for active responses.

In order to easily identify each section, we added a custom id. We checked the code, and all looked fine, especially because the code in ./src/config/config.c simply reads the <ossec_conf>. So when testing something like this:
`<ossec_conf id="test"> .... </ossec_conf>`
all looks fine. No error, even when all modules have debug set to verbose.

One of those section, also change the logging format to "json", so we added:
`<ossec_config id="test">
  <logging>
    <log_format>json</log_format>
  </logging>
</ossec_config>
`

and this doesn't work: the option is ignored. No error, nothing until I noticed this in the log files:
`2020/07/08 06:05:17 ossec-integratord[3326] debug_op.c:241 at os_logging_config(): DEBUG: (1228): Element 'log_format' without any option.
`

So, it looks like for the logging, the call to
`
void os_logging_config() { 
  // ....
    const char * xmlf[] = {"ossec_config", "logging", "log_format", NULL};
     logformat = OS_GetOneContentforElement(&xml, xmlf);
}`

Now I am wondering: am I really doing something wrong? I think we should either
- fail completely in ./src/config/config.c when reading the config, or
-maybe OS_GetOneContentforElement() has a bug?

Thanks,
Luca

**Comment by juliancnn** [comment]
Hi Luca, 

This case is not covered in the xml parser.
You are right, if you add additional attributes, the entire loggin section (within ossec_conf) will be ignored, then it will use the default values (log_format = plain)

If you think we should implement this feature, you could always open an issue with your feature request in https://github.com/wazuh/wazuh and we will evaluate with the team how and when to implement it

Regards,
Julian
