### ISSUE TITLE
Issue with Agentless Monitoring

### ISSUE THREAD

**Issue by bowojori7** [wazuh/wazuh#5450]
Hi. 

I'm trying to set up an agentless monitor and I get the following message from the logs. 

ossec-agentlessd: INFO: ssh_integrity_check_linux: root@example_adress.com: **Started**.

All the examples in the documentation show Starting then Finished like below to confirm that the manager has connected to the remote device. 

ossec-agentlessd: INFO: ssh_integrity_check_linux: root@example_adress.com: **Starting**.
ossec-agentlessd: INFO: ssh_integrity_check_linux: root@example_adress.com: **Finished**.

There is no information on the "Started" status. 
Can I have some assistance with this please?

**Comment by jesusjimsa** [comment]
Hello, @bowojori7.

I have just set up agentless with my Raspberry Pi in Wazuh 3.13 and it is working fine. I get these messages in my log:

```
2020/07/22 09:31:39 ossec-agentlessd: INFO: ssh_integrity_check_linux: pi@xxx.xx.xx.xx: Started.
2020/07/22 09:32:36 ossec-agentlessd: INFO: ssh_integrity_check_linux: pi@xxx.xx.xx.xx: Finished.
```

Are you having problems with receiving alerts from the agentless module?

The `Starting` message seems to have change to `Started` in one of the updates of Wazuh. I can't find when it was changed right now, however, I have notified the documentation team and it will be updated in the documentation as soon as possible.

Let me know if you need more help.

Best regards.

**Comment by jesusjimsa** [comment]
We have now created an issue in the wazuh-documentation repository and will fix this as soon as possible: wazuh/wazuh-documentation#2729.

**Comment by jesusjimsa** [comment]
As we now have an issue in the documentation repository, I'm closing this one. Feel free to re-open it if you need it.
