### ISSUE TITLE
Log input definitions from default/agent.conf cluster masters are not interpreted by agents despite being in the mg

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh#5453]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.1 | logcollector | Manager + Agent | Packages | Ubuntu 14 LXC container |

We're running a 3-node cluster of Wazuh masters on 3.11.1. We just found a case where adding
```
<agent_config os="Linux">
  <localfile>
    <location>/var/log/hadoop-hdfs/hadoop-hdfs-namenode-*.log</location>
    <log_format>syslog</log_format>
  </localfile>
```
did not get us new data from an agent. We checked `lsof` and sure enough, no read lock on the inode from ossec-logcollector.
Agent is Centos6, so we figured just in case, lets add it to the main `<agent_config>` section. Same effect.
We stopped the masters, we deleted all of the mg's, and started the masters to rebuild them. Mgs have the localfile definition for sure now, but still agen't not seeing it.
In the wazuh kibana app, the only localfile inputs it shows are ones from the _agent's pre-defined ossec.conf_ and none of the ones defined in the agent.conf for the default group of which the node is a member.
We added the localfile section to the agents own ossec.conf, and it works.
We can see the stanza in the agent.conf file on the agent, as well as its merged.mg.

Somehow the agent is ignoring the central configuration for log inputs. How do we fix this?

**Comment by sempervictus** [comment]
Confirm that this is happening with other agents too - they're ignoring the `localfile` directives from the `/var/ossec/etc/shared/default/agent.conf` on the masters _at least_, possibly other directives too.
`/var/ossec/bin/verify-agent-conf` does not show errors in the `default/agent.conf`.
We _are_ seeing the failing `localfile` directives appearing on the agent in both `agent.conf` and `merged.mg` so they're _making_ it to the agent, but being ignored somehow.

**Comment by antoniojpascualv** [comment]
Hello,
I will proceed to close this issue as the problem has been already solved in the community thread.

I am glad to see that your system is now working after reinstalling.

Regards.
