### ISSUE TITLE
[Development] Worker node does not launch services

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#5454]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1-31307 | Authd | Manager| Packages| Amazon Linux 2 |

Hi team,

Just got this weird situation when joining a worker manager node into the cluster. Using a default configuration, the `auth` block is like this:

```
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>no</use_password>
    <limit_maxagents>yes</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
```
Which seems to prevent the manager to start any service, looking at the `ossec.log` I have this:
```
2020/07/09 16:32:34 ossec-authd: INFO: Cluster worker node: Disabling Authd daemon.
```

### Steps to reproduce
1. Set up a manager as `master` node.
2. Set up a manager as `worker` node, configuration block used
```
  <cluster>
    <disabled>no</disabled>
    <name>wazuh</name>
    <node_name>worker_01</node_name>
    <node_type>worker</node_type>
    <key>#password#</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
      <node>10.0.0.131</node>
    </nodes>
    <hidden>no</hidden>
  </cluster>
```
3. Check that no `ossec` daemons are currently running in the worker
```
ps aux | grep ossec
```
#### Observations

When the `authd` block is disabled, the manager starts normally.

Thanks

**Comment by vikman90** [comment]
This issue is not related to Clusterd.
The Authd's configuration parser detects that it's running in a worker and exits with code `0`.
Since #4237, `ossec-control` checks that every daemon is running after launching it, and that makes the service startup fail.

## Action plan

- Restore the startup logic of v3.13.0.
