### ISSUE TITLE
New installation : Elastic Search template error

### ISSUE THREAD

**Issue by jkarmack** [wazuh/wazuh#5456]
Wazuh version : 3.13 / Ubuntu Server 2020.04

Greetings,

I have created an Ubuntu Server 2020.04 VM.
I have followed the Wazuh Install guide step by step.
Every module installation was package based
I have made a custom Wazuh API configuration, and made it work.
FileBeat, ElasticStack and Kibana are running properly,

However, I am told in Wazuh Status that there is an  Elastic Search template error

![image](https://user-images.githubusercontent.com/58203071/87088603-4dd0d700-c1f2-11ea-894d-f17e99d2e3a0.png)

The output of the following command might help troubleshooting :

john@wazuh:/usr/share/kibana$ curl http://localhost:9200/_cat/templates
.ml-state                        [.ml-state*]                 0          7080099
.ml-inference-000002             [.ml-inference-000002]       0          7080099
.triggered_watches               [.triggered_watches*]        2147483647 11
.management-beats                [.management-beats]          0          70000
filebeat-7.8.0                   [filebeat-7.8.0-*]           1
.ml-config                       [.ml-config]                 0          7080099
.watches                         [.watches*]                  2147483647 11
.ml-meta                         [.ml-meta]                   0          7080099
.ml-stats                        [.ml-stats-*]                0          7080099
.monitoring-kibana               [.monitoring-kibana-7-*]     0          7000199
.ml-anomalies-                   [.ml-anomalies-*]            0          7080099
.transform-internal-005          [.transform-internal-005]    0          7080099
.logstash-management             [.logstash]                  0
.monitoring-beats                [.monitoring-beats-7-*]      0          7000199
.transform-notifications-000002  [.transform-notifications-*] 0          7080099
ilm-history                      [ilm-history-2*]             2147483647 2
.monitoring-alerts-7             [.monitoring-alerts-7]       0          7000199
.slm-history                     [.slm-history-2*]            2147483647 2
.watch-history-11                [.watcher-history-11*]       2147483647 11
.monitoring-logstash             [.monitoring-logstash-7-*]   0          7000199
.kibana-event-log-7.8.0-template [.kibana-event-log-7.8.0-*]  0
.ml-notifications-000001         [.ml-notifications-000001]   0          7080099
.monitoring-es                   [.monitoring-es-7-*]         0          7000199
wazuh-agent                      [wazuh-monitoring-3.x-*]     0

What could be causing this issue ?

Thank you

John

**Comment by 32bitbradley** [comment]
Hi,

I'd just double check that you have index templates for `wazuh-agent [wazuh-alerts-3.x-]` and an index pattern for `wazuh-alerts-3.x-*`.

You can then select the right index pattern in the top right of the Wazuh Kibana app.

:)

**Comment by pablotr9** [comment]
Hi @jkarmack,

Sorry for the late reply, as @32bitbradley mentioned, it seems that the `wazuh-alerts-3.x-` template is missing.
Take a look at these Filebeat installation steps https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.html#installing-filebeat
You can see in the 4th steps that the Wazuh alerts template is downloaded, if you followed these steps you can find our template here:  `/etc/filebeat/wazuh-template.json` 
If Filebeat was correctly configured (step 3) and it can connect to Elasticsearch, the template should have been created automatically.
Please check the connection of Filebeat with Elasticsearch with this command: 
`filebeat test output`

Let me know if it helps or if you need further assistance!

Best Regards,
Pablo Torres

**Comment by pablotr9** [comment]
Hi @jkarmack ,

I will close this issue due to inactivity, if you are still facing this issue, please feel free to reopen it or open a new one!

Best Regards,
Pablo Torres
