### ISSUE TITLE
Update and fix older_than parameter behaviour in DELETE /agents API endpoint

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5470]
Hello team,

There is a problem with `older_than` parameter in API call to delete agents. Actually, there is no option available to force the deletion of an agent, and `older_than` has a default value of 7d (7 days). Even if we set `older_than` to 0s, there is a possibility based on a race condition that the agent is not deleted. This happens because the final query contains:

`(last_keepalive IS NOT NULL AND last_keepalive < strftime('%s', 'now') - :lastKeepAlive$0)`

If `last_keepalive` coincides with `strftime('%s', 'now')` the condition is not met, and so the agent is filtered out. This kind of behaviour makes so it is impossible to ensure the deletion of an agent if the user desires to do so using current API call. Also, it is making our current API test to fail randomly (roughly 10% of the times this call is used the agent will not be deleted, because `last_keep_alive` is updated every 10 seconds).

I suggest to update the behaviour of `older_than` when used value is 0s. In such case, the selected agents will be deleted without checking `last_keepalive` nor `registration_date`. We should update API parameter description to inform of such behaviour.

Best regards,

David J. Iglesias

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have implemented a fix for this bug, now when an older_than of 0s is specified, the parameter is ingested when querying the database. 

### Test results
```bash
adriiiprodri@wazuh python3 run_tests.py -rbac both -k agent           
Collected tests [6]:
test_agents_DELETE_endpoints.tavern.yaml, test_agents_GET_endpoints.tavern.yaml, test_agents_POST_endpoints.tavern.yaml, test_agents_PUT_endpoints.tavern.yaml, test_rbac_black_agents_endpoints.tavern.yaml, test_rbac_white_agents_endpoints.tavern.yaml


test_agents_DELETE_endpoints.tavern.yaml 
	 7 passed, 59 warnings

test_agents_GET_endpoints.tavern.yaml 
	 90 passed, 533 warnings

test_agents_POST_endpoints.tavern.yaml 
	 4 passed, 40 warnings

test_agents_PUT_endpoints.tavern.yaml 
	 8 passed, 66 warnings

test_rbac_black_agents_endpoints.tavern.yaml 
	 38 passed, 157 warnings

test_rbac_white_agents_endpoints.tavern.yaml 
	 38 passed, 166 warnings
```
