### ISSUE TITLE
agent´s IP appearing as any in Kibana. RedHat 6.x / Centos6

### ISSUE THREAD

**Issue by antoniojpascualv** [wazuh/wazuh#5479]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| "v3.13.0" | Kibana | Manager | Sources | RedHat v6 / Centos6 |

Hello team,
We have detected a problem with the RedHat 6.x and Centos6 OS when you install an agent. The registration with the `any` IP of the agent goes well and the agent reports to the manager without a problem.

The problem comes from the /var/ossec/queue/agent-info/  of the agent. The agent does not get the IP of the host properly and it does not appear in the agent-info file.

This issue causes that in the Kibana plugin in the agent's tab, the agent appears with any as IP. 

![image](https://user-images.githubusercontent.com/22274721/88296283-c5c4f400-ccfe-11ea-981e-8be5cfd53f24.png)

This is an image of the agent´s information in the agent-info file. In this case, the agent has the problem mentioned and the agent´s IP does not appear.

![image](https://user-images.githubusercontent.com/22274721/87543763-8d416c80-c6a5-11ea-8feb-1041ed8560fe.png)

This is an image of another agent in the same file. In this case, the problem did not affect this agent and we can see that the IP is in the agent´s information.

![image](https://user-images.githubusercontent.com/22274721/87543961-ee694000-c6a5-11ea-8497-e73cbac4b467.png)

I have seen this behavior in the 6.x Versions of RedHat and Centos.

**Comment by vikman90** [comment]
This bug has been produced by #5088: the optimization used to speed up the default gateway gathering seems not valid in the kernel 2.6.

## Possible solutions

1. Undo #5088. This will make the table route analysis be linear back.
2. Let the optimization apply depending on the kernel version.
3. Let the optimization apply if and only if the first line parsed has destination 0 (default gateway).
