### ISSUE TITLE
Agent upgrade failed

### ISSUE THREAD

**Issue by Newlik92** [wazuh/wazuh#5482]
|3.12.3|Agent|Manager/Agent|YUM packages|Centos 7.8|

Hello. I am not able to upgrade an agent when IP range is set.

 ID: 020, Name: LAPTOP-XXXX, IP: 192.168.1.0/24, Active

sudo /var/ossec/bin/agent_upgrade -a 020
Error 1720: Agent disconnected

If the IP is set to "any" or a fixed value, there is no problem.

Anyone had the same problem?
Thank you!

**Comment by pereyra-m** [comment]
Hello @Newlik92 !

Let's try to find more information about this error:

-  Please, share the output of the same command but in debug mode:
`sudo /var/ossec/bin/agent_upgrade -d -a 020`

- Are we in a cluster scenario ? Check the status of the agent with 
`sudo /var/ossec/bin/cluster_control -a`

- If you use the **API** instead, what happens? 
This command begins the upgrade
`curl -u foo:bar -k -X PUT "https://127.0.0.1:55000/agents/020/upgrade?pretty"`
This commands returns the upgrade result
`curl -u foo:bar -k -X GET "https://127.0.0.1:55000/agents/020/upgrade_result?pretty"`
You can also check the status of the agent with
`curl -u foo:bar -k -X GET "https://127.0.0.1:55000/agents?pretty&name=LAPTOP-XXXX"`

The commands above will help us to understand what's happening.

Regards.

**Comment by Newlik92** [comment]
Hello @pereyra-m, thanks for your response!
Please, see the outputs:

- **sudo /var/ossec/bin/agent_upgrade -d -a 020:**
Error 1720: Agent disconnected
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 73, in main
    raise WazuhException(1720)
wazuh.exception.WazuhException: Error 1720 - Agent disconnected

- ****Are we in a cluster scenario ? Check the status of the agent with:****
I do not use cluster
ERROR: Cluster is not running.

- **curl -u foo:bar -k -X PUT "https://127.0.0.1:55000/agents/020/upgrade?pretty"**
{
   "error": 3021,
   "message": "Timeout executing API request"
}

- **curl -u wazuh:alphaserverf63A -k -X GET "https://127.0.0.1:55000/agents/020/upgrade_result?pretty"**
curl: (52) Empty reply from server

- **curl -u foo:bar -k -X GET "https://127.0.0.1:55000/agents?pretty&name=LAPTOP-XXXX"**
{
   "error": 0,
   "data": {
      "items": [
         {
            "os": {
               "build": "18362",
               "major": "10",
               "minor": "0",
               "name": "Microsoft Windows 10 Pro",
               "platform": "windows",
               "uname": "Microsoft Windows 10 Pro",
               "version": "10.0.18362"
            },
            "id": "020",
            "node_name": "node01",
            "group": [
               "default"
            ],
            "registerIP": "192.168.1.2/24",
            "ip": "192.168.1.28",
            "mergedSum": "279579633ee2431d12f5a093a3010ed2",
            "status": "Active",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "name": "LAPTOP-XXXX",
            "lastKeepAlive": "2020-07-16 08:16:09",
            "manager": "wazuh_server",
            "dateAdd": "2020-07-15 15:08:09",
            "version": "Wazuh v3.10.2"
         }
      ],
      "totalItems": 1
   }
}

**Comment by pereyra-m** [comment]
Hello @Newlik92 

Thank you for sharing your results (please, don't forget to change your credentials to foo:bar).
What I'm seeing is that the agent IP

```
"name": "LAPTOP-XXXX",
"ip": "192.168.1.28",
```
Is not in the range you showed above

`ID: 020, Name: LAPTOP-XXXX, IP: 192.168.1.0/24, Active`

If you were able to upgrade your agent anyway, this workaround works. Try to use the **API** as much as you can.
Nevertheless, I'll leave the issue open for now because of the **agent_upgrade** failure.

Regards.

**Comment by pereyra-m** [comment]
Issue related #5511

**Comment by pereyra-m** [comment]
I'm closing this issue because the PR [5655](https://github.com/wazuh/wazuh/pull/5655) is merged.
These changes will be present in Wazuh 4.0.
