### ISSUE TITLE
Windows agents disconnect and reconnect when Log analysis configuration is empty in the agent's local configuration

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh#5497]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.11.4-31121 | Logcollector / Syscollector| Agent | Packages | Windows 2012 R2 Standard / Datacenter|

Hi team,

I have experienced a wrong behavior of the Wazuh agent 3.11.4.

## Description
When the `Log analysis` configuration is empty in the agent's `ossec.conf`. After working correctly for about one hour and a half, the agent disconnects and one hour later, it connects again.
The disconnection time matches the time when syscollector finishes a scan, and the reconnection time matches the next syscollector finished scan.

Here is a log file that shows that behavior. This is the full log file:

[ossec.log](https://github.com/wazuh/wazuh/files/4937440/ossec.log)

Here is a trace of those logs that encloses the time between the disconnection and the reconnection. The logs do not mention any disconnections or reconnections, but keep alives should be sent every 10 seconds. However, there are no keep alives sent between `03:38:02` and `04:38:01` (and this time matches when syscollector finishes the scans).
[ossec_trace.log](https://github.com/wazuh/wazuh/files/4937441/ossec_trace.log)

## Steps to reproduce:
1- Install the Wazuh agent 3.11.4 and register in the manager. In my case, I used a 3.11.4 CentOS-7 manager.
2- Send this remote configuration using the default group:
[agent.txt](https://github.com/wazuh/wazuh/files/4937458/agent.txt)

3- Use this configuration in the local `ossec.conf` of the agent:
[ossec.txt](https://github.com/wazuh/wazuh/files/4937472/ossec.txt)

4- The manager should be using TCP.
5- The agent should disconnect intermittently. In my case, it got disconnected after the second syscollector scan finished, connected again just before the third syscollector scan started, then disconnected again when it finished. The agent is only connected while the syscollector scan is being performed. However, after the fourth scan, it keeps connected.

## Additional notes:
- The agent keeps thinking that he is connected, but the manager thinks he is not (note that the agent's time does not match the manager's time, but everything is happening at the same time). 

![image](https://user-images.githubusercontent.com/30299229/87782351-a62b5880-c832-11ea-98cd-59f8aa142467.png)

![image](https://user-images.githubusercontent.com/30299229/87782375-acb9d000-c832-11ea-9db6-222df12262cf.png)

![image](https://user-images.githubusercontent.com/30299229/87782469-d1ae4300-c832-11ea-9cb3-1e2de929d6b9.png)

- Meanwhile, on the manager side, `netstat` shows that the connection is established:

![image](https://user-images.githubusercontent.com/30299229/87782446-c3f8bd80-c832-11ea-86e7-bba0d042e1cd.png)

Let me know if you need any further information. I have disabled syscollector now and I will update the issue when I see what is the behavior.

Best regards,
Sergio.

**Comment by sergiospa** [comment]
Update:
After disabling syscollector in the agent via local `ossec.conf`, the agent got disconnected at some point and never got to reconnect.

**Comment by sergiospa** [comment]
Update 2:
NOT happening in 3.13.1

**Comment by Dwordcito** [comment]
Close based on the comment https://github.com/wazuh/wazuh/issues/5497#issuecomment-662388339
