### ISSUE TITLE
 How to use FreeIPA decoder

### ISSUE THREAD

**Issue by isitavi** [wazuh/wazuh#5503]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.0-1 | Wazuh component | Manager | Packages | Red Hat Enterprise Linux Server release 7.6 (Maipo) |

For official purpose i need to send IPA AAA logs in Wazuh and Visualize them by Kibana. So i was started searching regarding this issue and got a decoder about [FreeIPA](https://github.com/wazuh/wazuh-ruleset/blob/master/decoders/0105-freeipa_decoders.xml) but actually i'm unable to understand how i can use this?

Also i was searching for IPA AAA logs in os but didn't get AAA kind of logs. I also follow this [document](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/linux_domain_identity_authentication_and_policy_guide/log-file-ref) also saw some [post](https://www.redhat.com/archives/freeipa-users/2013-February/msg00232.html) for logs surfing but got noting about AAA logs.

**Comment by Lopuiz** [comment]
Hello,

Regarding where the IPA AAA logs are,  I can't help you.
When you know where FreeIPA prints logs, you can collect them using a configuration as follow:

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/path/to/logfile.log</location>
</localfile>
```

It does the Logcollector module send logs to the Analysisd module (which process logs to generate alerts).

The decoder you mention is the only Wazuh have. You can find rules in file [0420-freeipa_rules.xml](https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0420-freeipa_rules.xml).

Although Wazuh has rules, I think you should create custom rules for freeipa. For example, if you want to show all logs in Kibana, you can overwrite rule number 82200 and change level to 3 or 4 (it generates alerts). Additionally, you should check the logs match these rules.

If you send us log examples, we will help to create rules.

Here you can find [ruleset documentation](https://documentation.wazuh.com/3.13/user-manual/ruleset/index.html). It can help you to understand rules syntax.

Finally, please, for further questions [join or Slack channel or subscribe to our mailing list](https://wazuh.com/community/). Reserve Github issues to report bugs or suggest enhancement.


Best regards,
Eva

**Comment by Lopuiz** [comment]
Hello,

I close this issue for inactivity.
Please, for further questions, join our Slack channel or subscribe our mailing lists: [Wazuh Community](https://wazuh.com/community/)

Regards,
Eva
