### ISSUE TITLE
Unable map Office 365 Audit log Geolocation 

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#5504]
Wazuh Version 3.13 

We have Integrated the Office 365 API with wazuh manager, It has been getting audit logs from the office 365 properly. but we have tried to create a business use case to know the geolocation of user login. I have tried to edit the wazuh template file to add the custom(Ofice 365 field "clientIP") field to get the geolocation but unfortunately, wazuh manager did not map any geo value to the custom failed.

Is there any possibility to achieve the same?

**Comment by davidjiglesias** [comment]
Hello @VisakhMV-Coder,

Wazuh manager will not map geo values to the custom field. By default, it is Filebeat who adds GeoIP information to the alerts before sending them to Kibana.

Currently, the fields using GeoIP can be found in the filebeat configuration file:

https://github.com/wazuh/wazuh/blob/v3.13.1/extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json

Try adding your field to this configuration file and filebeat will add GeoIP data to the alert.

Best regards,

David J. Iglesias

**Comment by VisakhMV-Coder** [comment]
hai,
i am sorry that we need to reopen this ticket.

as per the suggestion of @davidjiglesias ,we added new fields in config file,but it didnt work.

In case of office_365,the value comes as "data.clientip".

#nano /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json
{
  "description": "Wazuh alerts pipeline",
  "processors": [
    { "json" : { "field" : "message", "add_to_root": true } },
    {
      "geoip": {
        "field": "data.srcip",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.clientip",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.win.eventdata.ipAddress",
        "target_field": "GeoLocation",
		"properties": ["city_name", "country_name", "region_name", "location"],
		"ignore_missing": true,
		"ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.aws.sourceIPAddress",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }
	  
this is the code i have added,still its not working.is there any problem or bug in wazuh for a field value in api to be added with a geotag.

Thanks in advance.sorry for the delay,as i was busy with some new projects.
