### ISSUE TITLE
Create a file access baseline measure for Wazuh

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#5507]
### Description

The goal of this task is to create a file access baseline measure of a Wazuh single Manager deployement. The measure should be focused on the next list of items:

- Number of read accesses.
- Number of write accesses.
- Total written data.
- Total read data.

If possible, as a result of this task we should have a script ready to be run in the Wazuh Manager that simplifies the improvement analysis of the [Epic 5367](https://github.com/wazuh/wazuh/issues/5367) implementation.

**Comment by pereyra-m** [comment]
### Test results

To compare the current performance and the results of the new implementation, an `AWS EC2 t2.xlarge` instance was created.
All the tests were performed under a CentOS 7 OS, and repeated many times. We created a dashboard in AWS Cloud Watch Panel and collected all the relevant metrics for the volume access.

Every test run consisted of a simulation of 100 agents during 15 minutes. 
Here we have an example of 2 consecutive runs in the dashboard, the first one is on the **master** branch, and the next one, on the **dev-agent-info** branch. There is more information about the metrics in the [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using_cloudwatch_ebs.html#ebs-volume-metrics).

#### Example under master branch
![master](https://user-images.githubusercontent.com/65046601/94305042-f7e51300-ff46-11ea-9ced-1a2035295f19.png)
#### Example under dev-agent-info branch
![agent-info](https://user-images.githubusercontent.com/65046601/94305193-2fec5600-ff47-11ea-9714-c034f4b8ee75.png)

### Average results

The following plots are the most relevant ones to this task. The total read data was really small and similar for all the branches, so they are not uploaded here.

![volume_write_bytes](https://user-images.githubusercontent.com/65046601/94305850-421ac400-ff48-11ea-891e-3b96028eb291.png)
![volume_write_ops](https://user-images.githubusercontent.com/65046601/94305862-47780e80-ff48-11ea-9668-d3036cff9a43.png)
![volume_total_write_time](https://user-images.githubusercontent.com/65046601/94305875-4e068600-ff48-11ea-9523-6ab13180f714.png)
![iops](https://user-images.githubusercontent.com/65046601/94305895-552d9400-ff48-11ea-833e-f6e354f0fef9.png)
![throughput](https://user-images.githubusercontent.com/65046601/94305909-5ced3880-ff48-11ea-8e5d-e79616a473dd.png)
![volume_idle_time](https://user-images.githubusercontent.com/65046601/94306403-4693ac80-ff49-11ea-883a-cfc81ebd9f9e.png)
![volume_queue_length](https://user-images.githubusercontent.com/65046601/94306429-514e4180-ff49-11ea-985e-dfd61eccfad3.png)

### Conclusion

It can be noticed a considerable HDD access reduction, **%80** approximately in these tests.

**Comment by pereyra-m** [comment]
### Update

The script used to perform these tests is shared below. 
```

#!/bin/bash

TEST_TIME=900
AGENTS=100

stop_delete () {
    echo "Stopping Wazuh and removing ossec folder"
    sudo systemctl stop wazuh-manager
    sudo /var/ossec/bin/ossec-control stop >/dev/null 2>&1
    sudo rm -r /var/ossec >/dev/null 2>&1
}

install_test () {
    echo "*** Testing $1 ***"
    stop_delete
    echo "Installing Wazuh..."

    sudo USER_LANGUAGE="en" \
    USER_NO_STOP="y" \
    USER_INSTALL_TYPE="server" \
    USER_DIR="/var/ossec" \
    USER_DELETE_DIR="y" \
    USER_ENABLE_SYSCHECK="y" \
    USER_ENABLE_ROOTCHECK="y" \
    USER_ENABLE_OPENSCAP="n" \
    USER_ENABLE_SYSCOLLECTOR="y" \
    USER_ENABLE_SECURITY_CONFIGURATION_ASSESSMENT="y" \
    USER_ENABLE_AUTHD="y" \
    USER_UPDATE="n" \
    USER_ENABLE_EMAIL="n" \
    USER_AUTO_START="n" \
    USER_ENABLE_SYSLOG="y" \
    USER_WHITE_LIST="192.168.2.1" \
    /home/centos/$1/wazuh/install.sh >/dev/null 2>&1

    sudo systemctl start wazuh-manager
    echo "Simulation time: $TEST_TIME s Agents: $AGENTS"
    sudo sh -c 'pidof -s wazuh-modulesd > /var/run/wazuh-modulesd.pid'
    sudo sh -c 'pidof -s wazuh-db > /var/run/wazuh-db.pid'
    sudo sh -c 'pidof -s ossec-analysisd > /var/run/ossec-analysisd.pid'
    sudo sh -c 'pidof -s ossec-remoted > /var/run/ossec-remoted.pid'
    echo "$1 start: $(date)"
    cd "/home/centos/tools/wazuh-tools-master/utils/agents_simulator/"
    python3.7 agent_simulator.py 127.0.0.1 $AGENTS 0 $TEST_TIME $2 >/dev/null 2>&1
    cd "/home/centos"
    echo "$1 end: $(date)";
}

echo "------Starting HDD test------"

install_test "3.13" "udp" ;
install_test "develop" "tcp" ;
install_test "master" "tcp" ;
install_test "agent-info" "tcp" ;

echo "------HDD test completed------"

```

The batch tests were done this way
```

#!/bin/bash

./hdd_script.sh &> measure_1.out || true ;
./hdd_script.sh &> measure_2.out || true ;
./hdd_script.sh &> measure_3.out || true ;
```
