### ISSUE TITLE
Redesign the agent-info synchronization mechanism in Wazuh cluster to work with Wazuh DB

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#5508]
### Description

The goal of this issue is to have a design of a new `agent-info` data synchronization mechanism that works with the data that now is stored in Wazuh DB in the `global.db` database. This task includes:

- Analysis of the current `zip` compressed files mechanism. Frequency and components involved.
- Definition of the new messages that will be shared between the `master` and `workers` nodes in the Wazuh cluster.
- The messages should cover all the scenarios like agent registration, keepalive updates and agent removal. This new mechanism shouldn't introduce any lack of functionality.

As a result of this task, we should have also a clear understanding of all the components that should be modified to implement this new mechanism.

**Comment by palaciosjeremias** [comment]
**agent-info** data synchronization is performed on a cluster environment thru the [agent-info thread].(https://documentation.wazuh.com/3.13/user-manual/configuring-cluster/basics.html#agent-info-thread) 
This thread is in charge to send agent info raw files on the workers to the master to be processed and unified. Workers clusterd zip and send **agent-info** data every 10 seconds, configurable on **cluster.json**.

**Comment by palaciosjeremias** [comment]
[Agent-info cluster sync proposal.pdf](https://github.com/wazuh/wazuh/files/4995480/Agent-info.cluster.sync.proposal.pdf)
![Proposal Agent info Cluster Sync](https://user-images.githubusercontent.com/11434230/88814207-31401300-d190-11ea-9d84-2b2c0c250cb8.PNG)

**Comment by DProvinciani** [comment]
Closing as the proposal in the comment was approved and will be implemented.
