### ISSUE TITLE
[WPK] Receive messages from the workers and validate them (API/CLI)

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#5515]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.0 | wazuh-modulesd | Manager |

The upgrade module of the master node should be able to receive messages comming from the worker nodes through `clusterd` daemon. These messages have to be validated like messages comming from API/CLI, for example `upgrade` and `upgrade_result` requests. Besides, a task has to be created for each agent and the task IDs should be stored.

The result of the message validation, with the error codes, agent IDs, task IDs and/or status, has to be sent  through `clusterd` daemon to the worker node from where the message comes from.

**Comment by nicolaspapp** [comment]
This issue has already been covered by #5513
