### ISSUE TITLE
vulnerability-detector NVD module Offline Update Error

### ISSUE THREAD

**Issue by xufengnian** [wazuh/wazuh#5519]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
3.13.0 | wazuh-moduled:vulnerability-detector | Manager | Packages | CentOS 7.4

Hello,When I install wazuh-manager 3.13.0 in new host,everything is well,but vulnerability-detector is error.

because my host could not connect the internet,so I download "redhat and NVD"vulnerability databases with wazuh shell
,the url is https://github.com/wazuh/wazuh/tree/v3.13.0/tools/vulnerability-detector.I download this json and gz file into my manager and change ossec.conf

>     <provider name="redhat">
>       <enabled>yes</enabled>
>       <path>/var/ossec/ruleset/rh-feed/redhat-feed.*json$</path>
>       <update_interval>1h</update_interval>
>     </provider>
> 
>     <provider name="nvd">
>       <enabled>yes</enabled>
>       <path>/var/ossec/ruleset/nvd/nvd-feed.*json.gz$</path>
>       <update_interval>1h</update_interval>
>     </provider>

I also change the file owner as root:ossec,and change mode 644
![image](https://user-images.githubusercontent.com/15324125/88008979-01678e80-cb44-11ea-8278-1b79975e4579.png)

And I restart wazuh-manager,but I can't get agent vulnerability info.In /var/ossec/logs/ossec.log have error info

> 2020/07/21 11:17:35 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'Red Hat Enterprise Linux' database update.
> 2020/07/21 11:17:37 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'Red Hat Enterprise Linux' feed finished successfully.
> 2020/07/21 11:17:40 wazuh-modulesd:vulnerability-detector: INFO: (5400): Starting 'National Vulnerability Database' database update.
> 2020/07/21 11:17:40 wazuh-modulesd:vulnerability-detector: INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
> 2020/07/21 11:17:40 wazuh-modulesd:vulnerability-detector: INFO: (5431): Starting vulnerability scan.
> 2020/07/21 11:17:40 wazuh-modulesd:vulnerability-detector: ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.

I try to disable NVD module even delete NVD provider and restart wazuh-manager,it's useless,the error is same

> ERROR: (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
 
And I find similar issue in https://github.com/wazuh/wazuh/issues/5306

1. Stop the manager
2. Remove the vulnerabilities database, located at /var/ossec/queue/vulnerabilities/cve.db
3. Set run_on_start to yes in the Vulnerability Detector configuration
4. Restart the manager

I try these steps,but it's useless,by the way ,I use same config in another manager host with 3.12.3,that host vulnerabilitiy info is OK

So I guess Wazuh manager 3.13.x has some error in NVD module Offline Update,could you help me to fix it?Thank you very much!

**Comment by 0xN3utr0n** [comment]
Hi @xufengnian,
As stated in the [docu](https://documentation.wazuh.com/3.13/user-manual/capabilities/vulnerability-detection/offline_update.html?highlight=nvd#national-vulnerability-database), you must first decompress all the nvd files(note the `.gz` extension) when attempting to update from a local folder.  

Running the following command should do the job:
`$ gunzip -d /var/ossec/ruleset/nvd/*`
For assurance, check afterwards the files' names. They should match with `nvd-feed<date>.json`.

This is a common misunderstanding among Wazuh users, so sooner rather than later we'll somehow automate this step within the nvd script to avoid future headaches :wink:.

Kind regards,
Fernando

**Comment by xufengnian** [comment]
Your answer solved my problem perfectly.The Vulnerability module works well,thank you very much!
