### ISSUE TITLE
Ossec agent active response stopped working

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#552]
I have Wazuh-manager installed on my Debian 7 server. I have connect many wazuh-agent into wazuh-manager and it works great for monitoring all of those machine. I  did some configuration on my wazuh-manager to make active-response for each wazuh-agent. it works great for a weeks, until it's stopped working.  Wazuh-manager couldn't make any active respone works for each wazuh-agent. I have checked my wazuh-agent status and have some error messages for `ossec-logcollector`.

```
root@debian:/home/agt1# systemctl status wazuh-agent
● wazuh-agent.service - LSB: Start and stop Wazuh
   Loaded: loaded (/etc/init.d/wazuh-agent)
   Active: active (running) since Thu 2018-04-19 18:02:22 WITA; 35min ago
  Process: 3158 ExecStop=/etc/init.d/wazuh-agent stop (code=exited, status=0/SUCCESS)
  Process: 3196 ExecStart=/etc/init.d/wazuh-agent start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/wazuh-agent.service
           ├─3222 /var/ossec/bin/ossec-execd
           ├─3227 /var/ossec/bin/ossec-agentd
           ├─3234 /var/ossec/bin/ossec-syscheckd
           └─3238 /var/ossec/bin/ossec-logcollector

Apr 19 18:02:20 debian systemd[1]: Starting LSB: Start and stop Wazuh...
Apr 19 18:02:20 debian wazuh-agent[3196]: Starting Wazuh v3.2.1 (maintained by Wazuh Inc.)...
Apr 19 18:02:20 debian wazuh-agent[3196]: Started wazuh-modulesd...
Apr 19 18:02:20 debian wazuh-agent[3196]: Started ossec-execd...
Apr 19 18:02:20 debian wazuh-agent[3196]: 2018/04/19 18:02:20 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
Apr 19 18:02:20 debian wazuh-agent[3196]: Started ossec-agentd...
Apr 19 18:02:20 debian wazuh-agent[3196]: Started ossec-syscheckd...
Apr 19 18:02:20 debian wazuh-agent[3196]: 2018/04/19 18:02:20 ossec-logcollector: ERROR: Remote commands are not accepted from the manager. Ignoring it on ...agent.conf
Apr 19 18:02:20 debian wazuh-agent[3196]: Started ossec-logcollector...
Apr 19 18:02:22 debian wazuh-agent[3196]: Completed.

```

All of these 4 machines have same error status messages like above message. 

I have checked my `agent.conf` at `nano /var/ossec/etc/shared/default/agent.conf`
`
and it looks like below.

```
<agent_config>

  <!-- Shared agent configuration here -->
<localfile>
     <log_format>full_command</log_format>
     <command>tasklist</command>
     <frequency>120</frequency>
 </localfile>

 <localfile>
        <log_format>syslog</log_format>
        <location>/var/ossec/logs/active-responses.log</location>
    </localfile>

</agent_config>
```

I dont know what's the problem, since it works fine for a weeks, but suddenly the active-response stopped working... Does anyone know what's the problem with my machine ?

**Comment by TJOSERAFAEL** [comment]
Hi @gagantous,

you can do the following steps:

1. On each agent, edit the file **/var/ossec/etc/internal_options.conf** 
     Set `logcollector.remote_commands=1`
2. Restart the agent

I hope it helps you.

Best regards.

**Comment by gagantous** [comment]
Hi @TJOSERAFAEL 

I have follow and did your instruction, but wazuh active-response for each wazuh-agent still didnt work

**Comment by gagantous** [comment]
Hi @TJOSERAFAEL !

It looks like the machine started to works normally, i have to wait for maybe an hour to make this works, thanks for your helps

**Comment by TJOSERAFAEL** [comment]
Hi @gagantous ,

I'm glad it worked for you!

Best regards.
