### ISSUE TITLE
Makefile:697: *** No external directory found. Run "make deps" before compiling external libraries.  Stop.   Error 0x5.  Building error. Unable to finish the installation.

### ISSUE THREAD

**Issue by rmdhfz** [wazuh/wazuh#5527]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-3.13.1 | Wazuh component | Manager | Sources | Linux ifah 4.19.0-kali5-amd64 (kali 2020.3) |

Makefile:697: *** No external directory found. Run "make deps" before compiling external libraries.  Stop.

 Error 0x5.
 Building error. Unable to finish the installation.

**Comment by bah07** [comment]
Hi @rmdhfz 

You need to compile dependencies before compile Wazuh. Take the following steps:

```sh
## Install dependencies
apt update
apt-get install make gcc libc6-dev curl policycoreutils automake autoconf libtool -y

## From wazuh/src folder
make deps
make TARGET=agent -j8

## To install from wazuh folder
./install.sh
```

In my lab it works fine
```
root@kali:/var/ossec/bin# uname -a
Linux kali 5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux
root@kali:/var/ossec/bin# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.13.1"
REVISION="31309"
DATE="Wed 22 Jul 2020 03:34:44 AM EDT"
TYPE="agent"
```

If you have any problems, don't hesitate to write to us, I hope it's helpful.
Regards.

**Comment by rmdhfz** [comment]
Hi @bah07 , thank you. 

After this : 
~ apt-get install make gcc libc6-dev curl policycoreutils automake autoconf libtool -y

I get an error: 
The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-9-dev (< 9.3.0-5~) but 9.2.1-21 is to be installed
E: Unable to correct problems, you have held broken packages

**Comment by bah07** [comment]
hi @rmdhfz 

Sorry for late response, It seems that you have a more recent version of libc, but it should not give problems when compiling Wazuh. Have you tried compiling?

Regards

**Comment by rmdhfz** [comment]
Hi @bah07 ,

Yes, no problem, I've tried compiling

**Comment by bah07** [comment]
Hi @rmdhfz 

What error does it show when compiling?

Regards.
