### ISSUE TITLE
Vulnerability assesment gives error for windows agent

### ISSUE THREAD

**Issue by nsxfar** [wazuh/wazuh#5533]
Hi, my setup is as below:
NAME="Wazuh"
VERSION="v3.13.1"
REVISION="31309"
TYPE="server"

After installing windows agent, I have seen nothing in vulnerability dashboard and when I inspect logs, some errors pops up inside debug logs. I can see all programs installed in the host at inventory page of the agent.

2020-07-22 16:26:24 wazuh-modulesd:vulnerability-detector ERROR  (5530): Invalid response from wazuh-db: 'err Cannot execute SQL query'
2020-07-22 16:26:24 wazuh-modulesd:vulnerability-detector ERROR  (5532): Could not generate the CPE inventory from the agent '001'
2020-07-22 16:26:24 wazuh-modulesd:vulnerability-detector ERROR  (5507): The software of the agent '001' could not be obtained.

Here is my vuln confign in ossec.conf file: I have updated ignore_time to 5 minutest to make full scan..

<vulnerability-detector>
    <enabled>yes</enabled>
    <interval>5m</interval>
    <ignore_time>5m</ignore_time>
    <run_on_start>yes</run_on_start>

    <provider name="canonical">
      <enabled>no</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="debian">
      <enabled>no</enabled>
      <os>wheezy</os>
      <os>stretch</os>
      <os>jessie</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="redhat">
      <enabled>no</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>

And here is the syscollector config in ossec.conf:
`<wodle name="syscollector">
    <disabled>no</disabled>
    <interval>1h</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
</wodle>`

Could you please verify if win agent can make vulnerability assessment? Thanks

**Comment by DProvinciani** [comment]
Hi, I just verified in my environment and the vulnerability detection for Windows seems to be working correctly for the manager version that you are specifying.

Let's see what could be happening here. In the **vulnerability-detector** module, there is an interaction with **Wazuh DB** to get some information related to the agents. So, at the end of the day, the next two daemons get communicated through a socket.

```
[root@centos8 ~]# ps aux | grep wazuh
ossec       1634  0.0  0.8 720640 15640 ?        Sl   14:58   0:01 /var/ossec/bin/wazuh-db
root        1795 36.8  9.3 794728 175076 ?       Sl   14:58  10:57 /var/ossec/bin/wazuh-modulesd
```

For some reason, seems like the query made from **vulnerability-detector** (within `wazuh-modulesd`) is not getting the expected answer from `wazuh-db`. Probably the `wazuh-db` daemon is in a bad state.

Could you verify in the `/var/ossec/logs/ossec.log` if there are error logs generated by `wazuh-db`?

If not, I would suggest adding the next lines to the file `/var/ossec/etc/local_internal_options.conf` and restart the **wazuh-manager** in order to have more information in the logs in case that the communication with `wazuh-db` could fail again.

```
wazuh_db.debug = 2
wazuh_modules.debug = 2
```

**Comment by nsxfar** [comment]
Hi, I set debug modes and surprisingly I guess I find the reason that wazuh vuln is getting error due to the sql syntax:

UPDATE
  SYS_PROGRAMS
SET
  CPE = 'a:microsoft:office:2016:(null):(null):(null):(null):(null):i686:(null)',
  MSU_NAME = 'Microsoft Office 2016'
WHERE
  VENDOR = 'Microsoft Corporation'
  AND NAME = 'Microsoft Office Proofing Tools 2016 - **o' zbekcha '** AND VERSION = ' 16.0.4266.1001 ' AND ARCHITECTURE = ' i686 ';


As you can see o'zbekcha has a single quote and sql syntax is not correct. When I tried to validate it gives following;

You have an error in your SQL syntax; it seems the error is around: 'zbekcha ' AND VERSION = ' 16.0.4266.1001 ' AND ARCHITECTURE = ' i686 '' at line 8

**Comment by nsxfar** [comment]
Due to this error, whole component is out of order.

**Comment by DProvinciani** [comment]
We just confirmed the issue and we will need to implement a fix in the code. Tagging the issue as a bug.

**Comment by DProvinciani** [comment]
@nsxfar , the fix was implemented in [Pull 5570](https://github.com/wazuh/wazuh/pull/5570) and is being tested and reviewed.

**Comment by DProvinciani** [comment]
@nsxfar the fix was verified and merged. So this will follow the normal process to be included in the next release.

Thanks for reporting this issue.

Closing as https://github.com/wazuh/wazuh/pull/5570/ was merged.
