### ISSUE TITLE
[WPK][Framework] Refactor framework to connect to new upgrade module

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5537]
Hello team,

This issue is based on #5387.

## Description

With the refactor and changes to the upgrade process, the new Wazuh upgrade module will be in charge to handle upgrade requests with agents and update the appropriate task status. Until now, the framework was in charge of the complete upgrade process, validating the input, downloading the wpk, etc. We should refactor the framework module for agents so the petition is sent to the new upgrade module directly through the provided socket.

## Design

Remove all deprecated framework code in favor of the new upgrade module. The framework function should only receive an upgrade request from the API or the CLI, apply RBAC access permissions and send the petition to the new upgrade module socket, await for the response and send it back.

## Testing

We should update unit tests for agent framework modules accordingly to the proposed changes. Remove or update deprecated tests and new ones if necessary.

## Tasks

- [x] Update agent.py framework SDK and core modules
- [x] Update/add and run new unit tests

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have modified the agent upgrade functions of the framework. Currently we have made the connection with the new module and we control the errors that the upgrade module raises right now.

```
{
  "data": {
    "affected_items": [
      0
    ],
    "total_affected_items": 1,
    "total_failed_items": 1,
    "failed_items": [
      {
        "error": {
          "code": 1756,
          "message": "Upgrade procedure could not start. Agent already upgrading",
          "remediation": "You can check the status of this task with the /agents/:agent_id/upgrade_result endpoint"
        },
        "id": [
          0
        ]
      }
    ]
  },
  "message": "Some agents have not been upgraded"
}
```
