### ISSUE TITLE
Splunk CIM Compatible?

### ISSUE THREAD

**Issue by Idriel** [wazuh/wazuh#5557]
Hi,

Is Splunk App data index CIM compatible?

**Comment by JcabreraC** [comment]
Hello @Idriel,

I regret to inform you that Splunk CIM is not currently compatible with Wazuh.

We will consider adding it to the roadmap.

Best regards,
Juan Cabrera

**Comment by JcabreraC** [comment]
Hello @Idriel 

Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our Slack channel or subscribe to our mailing list.

Best regards,
Juan
