### ISSUE TITLE
Index wazuh-alerts-3.x*  Field [data.vulnerability.updated] of type [keyword] does not support custom formats

### ISSUE THREAD

**Issue by guilhermerezendemarques** [wazuh/wazuh#5560]
The alarm index cannot open reporting an error when trying to load data on the vulnerabilities.

illegal_argument_exception at shard 2index wazuh-alerts-3.x-2020.07.26 node XXXX
Type
illegal_argument_exception
Reason
Field [data.vulnerability.updated] of type [keyword] does not support custom formats

**Comment by pablotr9** [comment]
Duplicate of https://github.com/wazuh/wazuh-kibana-app/issues/2403
