### ISSUE TITLE
agentless doesn't save checksum of ESXi servers

### ISSUE THREAD

**Issue by hanschl** [wazuh/wazuh#5561]
|Wazuh version|Component|Install type|Install method|Platform|
|3.12.3|agentless|Manager|Packages|CentOS 8 Linux|

Hello,

we are having problems with our agentless checks of VMware ESXi Servers. It seems like Wazuh is scanning the servers and getting the correct checksum for the files but isn't actually saving the checksum to any database. Because of that we are getting E-Mail every 8 hours (Around 6MB per Mail). If I check our Splunk Logs I can see that the old checksum always stays the same and then a alert is sent with the new checksum and that for every file that is being checked. 

I'm not sure if this is actually a bug or a configuration issue but I'll open this anyway. Our configs are like this:

**/var/ossec/etc/ossec.conf:**

```
<agentless>
<type>ssh_integrity_check_vmware</type>
<frequency>28800</frequency>
   <host>ossec@server1</host>
   <host>ossec@server2</host>
   <host>ossec@server3</host>
   <host>ossec@server4</host>
   <host>ossec@server5</host>
   <host>ossec@server6</host>
   <host>ossec@server7</host>
   <host>ossec@server8</host>
   <host>ossec@server9</host>
   <host>ossec@server10</host>
   <host>ossec@server11</host>
   <host>ossec@server12</host>
   <state>periodic_diff</state>
   <arguments>/bin /etc /sbin /usr/lib/vmware/busybox/bin</arguments>
</agentless>
```

**For the check we use a slightly modified ssh_integrity_check_linux script:**

```
 #!/usr/bin/env expect

# @(#) $Id: ./src/agentlessd/scripts/ssh_integrity_check_linux, 2011/09/08 dcid Exp $

# Agentless monitoring for vmware

# Main script.
source "agentless/main.exp"

# SSHing to the box and passing the directories to check.
if [catch {
    spawn ssh $hostname
} loc_error] {
    send_user "ERROR: Opening connection: $loc_error.\n"
    exit 1;
}

source $sshsrc
source $susrc

set timeout 600
send "echo \"INFO: Starting.\"; for i in `find $args 2>/dev/null`;do tail \$i >/dev/null 2>&1 && md5=`md5sum \$i | cut -d \" \" -f 1` && sha1=`sha1sum \$i | cut -d \" \" -f 1` && echo FWD: `stat -Lc \"%s:%a:%u:%g\" \$i`:\$md5:\$sha1 \$i; done; exit\r"
send "exit\r"

expect {
    timeout {
        send_user "ERROR: Timeout while running commands on host: $hostname .\n"
        exit 1;
    }
    eof {
        send_user "\nINFO: Finished.\n"
        exit 0;
    }
}

exit 0;
```

**Comment by vikman90** [comment]
Hi @hanschl,

Thank you for opening this issue. This is a known problem (#3565). As agentless devices have no ID, the manager uses the manager's database (000) to store the checksum of every device.

The list of files in every device is colliding with the other devices' files. That is prone to produce false positives.

That requires us to develop a fix, it's not your script's fault.

Sorry for the inconvenience.
Best regards.

**Comment by hanschl** [comment]
Hi @vikman90,

that's okay. Please let me know if I can help you in any way.

Best Regards,

**Comment by vikman90** [comment]
@hanschl Let me close this issue as the related ticket is already in the roadmap. We will fix that as soon as possible.

Thank you again.
Best regards.
