### ISSUE TITLE
[API] Add new endpoints to support logtest.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#5577]
|Working branch| 
|---|
|[feature/5577-new-logtest-endpoints](https://github.com/wazuh/wazuh/tree/feature/5577-new-logtest-endpoints)|

|Wazuh version|Component|Install type|Install method|
|---|---|---|---|
| 4.1.0 | API | Manager | Packages/Sources |

# Description
Hello team. As explained in https://github.com/wazuh/wazuh/issues/5337, the logtest tool will undergo multiple changes to allow being used in the API and the in the APP. The specifications of this issue may still change depending on future decisions / revisions.
​
New endpoints are required:
- `PUT /logtest`: Check if a specified log raises any alert among other information.
- `DELETE /logtest/sessions/{token}`: Delete the saved session corresponding to {token}
​

They will be **distributed API call**, the worker nodes do not test events, the test is sent to the master and returns results.
​

`PUT /logtest` should accept the following list of parameters as a RequestBody:
- `token`:  alphanumeric string.
- `log_format`:  Enum of strings. It must accept any of these values https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/localfile.html#log-format 
- `location`: path string (_paths).
- `event`: string
​

`DELETE /logtest/sessions/{token}` should accept the following parameter, in path:
- `token`: alphanumeric string
​

​
The output will be in JSON format like the one you can see here, and will be returned as is by the socket. It is probably still undergoing changes as it has to return a token that does not appear right now:
```JSON
{
    "token": "bd83b45f",
    "messages": ["INFO: (7202): Session initialized with token 'bd83b45f'"],
    "output": {
        "timestamp": "2020-08-27T08:36:54.740+0000",
        "rule": {
            "description": "Systemd rules",
            "id": "40700",
            "firedtimes": 1,
            "mail": false,
            "groups": ["local", "systemd"]
        },
        "agent": {
            "id": "000",
            "name": "wazuh-master"
        },
        "manager": {
            "name": "wazuh-master"
        },
        "id": "1598517414.1892559",
        "cluster": {
            "name": "wazuh",
            "node": "master-node"
        },
        "full_log": "Jun 24 11:54:19 Master systemd[2099]: Started VTE child process 20118 launched by terminator process 17756.",
        "predecoder": {
            "program_name": "systemd",
            "timestamp": "Jun 24 11:54:19",
            "hostname": "Master"
        },
        "decoder": {
            "name": "systemd"
        },
        "location": "master->/var/log/syslog"
    },
    "alert": false,
    "codemsg": 0
}
```

​
Kind regards,
Selu.

**Comment by mcarmona99** [comment]
**Issue updates**

Issue almost finished, log parameter as a RequestBody and x-rbac-actions for the new endpoints left.

Added code and/or files:
- `spec.yaml`: added the 2 new endpoints with its parameters and examples.
- `logtest_controller.py`: added the logtest controller and the 2 functions corresponding to the 2 new endpoints.
- `logtest_log_model.py`: pending.

**Comment by mcarmona99** [comment]
**Working branch:** `feature/5577-new-logtest-endpoints`

Added logtest_model.py, x-rbac-actions and updated `test_security.py`: 

```
framework/wazuh/tests/test_security.py
================== 65 passed, 12 warnings in 73.54s (0:01:13) ==================
```
Pending: 
- More API integration test cases: using token, not using token and then check the token used is the one generated, etc.

**Comment by mcarmona99** [comment]
Draft PR related to this issue: https://github.com/wazuh/wazuh/pull/5984

Waiting for the blocking issues.

**TO DO**: pass the new API integration tests.
