### ISSUE TITLE
Vulnerability-Detector: Duplicated alerts for Windows 10 agents

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#5587]
Hello team,
It seems that for Windows 10 agents all generated alerts appear to be duplicated. At first we thought that it was due to an error while matching against the MSU, but it looks like the issue is happening way before that. 

After some investigation we came to the conclusion that the faulty code is:
https://github.com/wazuh/wazuh/blob/ff962364251c1fa38468bc750c8431ced9254b84/src/wazuh_modules/vulnerability_detector/wm_vuln_detector_nvd.c#L1864-L1889

The SQL query `VU_GET_NVD_CPE` is returning two rows, and each one of them having slightly different CPE URI:
```
cpe:2.3:o:microsoft:windows_10:1809:*:*:*:*:*:*:*
cpe:2.3:o:microsoft:windows_10:-:*:*:*:*:*:*:*
```
Hence, almost every CVE gets matched twice, once per CPE. This is an undesired result, since each O.S should be identified by only one CPE. 

kind regards,
Fernando

**Comment by chemamartinez** [comment]
Merged #5600
