### ISSUE TITLE
Add ignore option to vulnerability detector

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#559]
Hi guys, this is only a request feature not an issue itself. It would be nice if the vulnerability detector could ignore an agent which has syscollector but we don't need to scan its packages. From my knowledge I understand if the manager has vulnerability enabled and an agent has syscollector, its packages will be scanned with no option to ignore them.

Also it would be nice if we can ignore at group level not only agent level.

Regards,
Jesús

**Comment by JcabreraC** [comment]
Hi @jesusgn90 

This option exists since 3.11. For this, the `ignore_time` tag is used.

We can see how it works in the documentation:
https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html?highlight=vulnerability%20detector#ignore-time

Best regards,
Juan
