### ISSUE TITLE
How to pronounce Wazuh

### ISSUE THREAD

**Issue by z0n3z3r0** [wazuh/wazuh#5592]
Quick question, how do we pronounce Wazuh? :-D Please close this issue after replying. 

Thanks!

**Comment by Selutario** [comment]
Hi @z0n3z3r0,

There is no "official" pronunciation for Wazuh. We have heard it in multiple ways and they all are fine. However, the usual pronunciation for us (especially in English) is to pronounce it as _Waza_ (something like `wɑ:zʌ`).

Take a look at our youtube channel. It may help you set up certain tools, and in all of them, you can hear how we pronounce the word Wazuh: https://www.youtube.com/watch?v=peTSzcAueEc

Kind regards,
Selu.
