### ISSUE TITLE
Memory release of Wazuh-logtest structures

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#5596]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | Wazuh component | Manager | Packages/Sources | OS version |

Hello team,

With the new implementation of Wazuh-logtest, it is necessary to perform a series of functions that release the resources of the structures used by this module.

The functions to be developed are:
- os_remove_decoders_list
- os_list_removecdblist
- os_list_removecdbrules
- os_remove_rules_list
- os_remove_rule
- os_remove_eventlist

Best regards,
Juan

**Comment by Lopuiz** [comment]
Done!!
