### ISSUE TITLE
[Development] Possible error receiving message from control socket in ossec-agentd

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#5611]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0-40000 | agentd  | Agent | Packages | CentOS 7 |

Hello team,

The Jenkins installation pipeline has detected that in some cases (rarely) there are install tests that fail caused by the following error in  `ossec.log` 

```
ossec-agentd: ERROR: Error receiving msg from control socket (104) Connection reset by peer
```
It is requested to investigate the possible causes of this error.

Here is attached a file with the complete trace of [ossec.log](https://github.com/wazuh/wazuh/files/5007531/ossec.log)

Best regards.

**Comment by vikman90** [comment]
## Rationale

This error means that Modulesd exited while getting the IP address for Agentd. It appears when the agent restarts (second execution), and before Modulesd starts again. That makes me think that Agentd is quering the old Modulesd process.

The agent restarted while Modulesd was running an SCA scan, that executes commands. The [`wm_cleanup` function](https://github.com/wazuh/wazuh/blob/v3.13.1/src/wazuh_modules/main.c#L191-L202) first deletes the PID file and then kills the existing child processes. This could make `ossec-control` assume that Modulesd is closed while it's killing the child processes.

## Proposed fix

Erasing the PID file shall be the very last operation that Modulesd performs. We should let it kill the processes before deleting the PID file.
