### ISSUE TITLE
Delay when retrying to run docker-wodle after error

### ISSUE THREAD

**Issue by issacg** [wazuh/wazuh#5620]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
1.13.0 | docker-wodle | agent | RPM | Amazon Linux 2 (latest) |

I had an issue when getting the docker wodle to run properly when installing `pip install docker` after my agent was already up-and-running.

Before installing it, I was able to see logs from `modulesd` warning about it not being installed
```
2020/08/02 07:40:00 wazuh-modulesd:docker-listener[15178] wm_docker.c:56 at wm_docker_main(): INFO: Starting to listening Docker events.
2020/08/02 07:40:00 wazuh-modulesd:docker-listener[15178] wm_docker.c:60 at wm_docker_main(): DEBUG: Launching command '/var/ossec/wodles/docker/DockerListener'
2020/08/02 07:40:00 wazuh-modulesd:docker-listener[15178] wm_docker.c:77 at wm_docker_main(): ERROR: 'docker' module needs to be installed. Execute 'pip install docker' to do it.
2020/08/02 07:40:00 wazuh-modulesd:docker-listener[15178] wm_docker.c:95 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 1). Retrying to run in next scheduled time...
2020/08/02 07:40:00 wazuh-modulesd:docker-listener[15178] wm_docker.c:52 at wm_docker_main(): DEBUG: Sleeping until: 2020/08/02 07:41:00
```

But after installing it, despite restarting `modulesd` alone, and several times as part of a full `ossec-control restart`, I wasn't seeing anything happening - no events, and the only log lines I got were
```
2020/08/02 07:52:07 wazuh-modulesd:docker-listener[17712] wm_docker.c:56 at wm_docker_main(): INFO: Starting to listening Docker events.
2020/08/02 07:52:07 wazuh-modulesd:docker-listener[17712] wm_docker.c:60 at wm_docker_main(): DEBUG: Launching command '/var/ossec/wodles/docker/DockerListener'
```

Eventually, I tried to bring up a new agent on a new machine from scratch, ensuring to install the pip module before installing Wazuh via yum, and then I started seeing docker events in the logs.

My guess is that there's some sort of timeout maybe that needs to expire before the docker listener tries to do anything after failing, and every time I'd tried installing the pip library after installing and starting the Wazuh agent, I'd miss it somehow?  Or maybe some other config magic that happens at install?  But the lack of any visible changes after installing it had me convinced that I was on the wrong path weeks ago (well before I discovered the Slack organization to ask for help)

PS.  There's also possibly some potential to improve the docs on this.  Although [there is a document](https://documentation.wazuh.com/3.13/docker-monitor/monitoring_containers_activity.html) which to my eyes is now very clear, when I started a few weeks ago as a complete beginner, I didn't understand that I'd need to `pip install docker` on the agents.  I barely understood what a "wodle" was, and was clueless to where it would be running.  I figured "Well, I'm running Wazuh 1.13, so it looks like I don't really need it, and installing it manually doesn't seem to be helping anyway, so I'll just assume that that's not the issue" - especially given the above behavior that seemed to show me that installing the pip package didn't fix anything, and kept on looking for other fixes.

**Comment by vikman90** [comment]
Hi @issacg,

That behavior is weird. This log means that the Docker listener is working:

```
2020/08/02 07:52:07 wazuh-modulesd:docker-listener[17712] wm_docker.c:60 at wm_docker_main(): DEBUG: Launching command '/var/ossec/wodles/docker/DockerListener'
```

The listener launching could be delayed if `run_on_start` was disabled:
```xml
<wodle name="docker-listener">
  <disabled>no</disabled>
  <run_on_start>no</run_on_start>
</wodle>
```

Anyway, the log above states that the listener is active. I don't believe in magic but I would kindly ask you to try that again. Also, you can try to run the integration manually:

```json
# /var/ossec/wodles/docker/DockerListener
{"integration": "docker", "docker": {"Wodle event": "Started"}}
Docker service was started.
{"integration": "docker", "docker": {"Wodle event": "Connected to Docker service"}}
```

When an event occurs, the listener should print that:
```json
{"integration": "docker", "docker": {"status": "create", "id": "bf55c5f9ab853feb9135049ab3de098dc98ba2925a53b04edf34cdb6380135e8", "from": "hello-world", "Type": "container", "Action": "create", "Actor": {"ID": "bf55c5f9ab853feb9135049ab3de098dc98ba2925a53b04edf34cdb6380135e8", "Attributes": {"image": "hello-world", "name": "gifted_johnson"}}, "scope": "local", "time": 1596694486, "timeNano": 1596694486917620519}}
```

Your feedback about the documentation is very valuable to us. We will work to make it clearer. Don't worry about the "wodle" term, we are going to get rid of it. A wodle is simply each module —Wazuh module— running in Modulesd.

I'm sorry of not being of more help, but the log seems OK. If you are able to run the script manually and reproduce the problem, maybe we can address the issue that caused it.

Best regards.
