### ISSUE TITLE
Evaluation of composed primary keys.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#5632]
## Description
Evaluate/investigate the use of composed primary keys in tables.

## DoD / Tasks
- [x] Assesment

As a result of this assessment the following issue has been created to achieve the expected work: Issue [#5670](https://github.com/wazuh/wazuh/issues/5670) - Extend current mechanism to support compound primary keys

**Comment by tinachoB** [comment]
The complete work will be done in the issue #5670
