### ISSUE TITLE
Move FIM internal options to regular configuration

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#5648]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| n/a | ossec-syscheck | Manager/Agent | Packages/Sources | n/a |

## Description

The File Integrity Monitoring module has a series of internal options that can only be changed from the agent itself. To fix this, the internal options need to be moved from the _internal_options.conf_ file to the _ossec.conf_ file. This way, these options could be changed using the centralized configuration (_agent.conf_).

Currently, the internal options are:

- `syscheck.rt_delay`
- `syscheck.max_fd_win_rt`
- `syscheck.max_audit_entries`
- `syscheck.default_max_depth`
- `syscheck.symlink_scan_interval`
- `syscheck.file_max_size`

Some of this options would be just global and other would need to have a local version, like the one described in #5231.

### Example of configuration
One example of configuration after the change is done would be this one:
```xml
<syscheck>
    <disabled>no</disabled>

    <directories realtime="yes">/home/user</directories>

    <rt_delay>5</rt_delay>
</syscheck>
```

**Comment by antoniomanuelfr** [comment]
Documentation issue https://github.com/wazuh/wazuh-documentation/issues/3260

**Comment by Molter73** [comment]
We've come to realize that this issue is in conflict with #3150. We will not make further developments on this issue for the moment, but due to #3150 looking like it became a little stale, we will keep the associated PRs on this issue in case we decide to go on with this approach.
