### ISSUE TITLE
email alerts does not contain what changed (syscheck module)

### ISSUE THREAD

**Issue by wafaance** [wazuh/wazuh#5657]
I use wazuh-manager and wazuh-agent 3.13.1. I want to monitor files with syscheck module and send alerts by email.
My problem is I can't report what changed in the email alert.

You find below my configuration.
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>192.168.30.30</smtp_server>
    <email_from>ossec@certification.tn</email_from>
    <email_to>hids@certification.tn</email_to>
    <email_maxperhour>12</email_maxperhour>
    <queue_size>131072</queue_size>
  </global>

....

  <syscheck>
    <disabled>no</disabled>

    
    <frequency>10</frequency>

    <scan_on_start>yes</scan_on_start>

    
    <auto_ignore frequency="10" timeframe="3600">no</auto_ignore>

    
    <directories check_all="yes" realtime="yes" report_changes="yes">/etc/rsyslog.conf</directories>
    <directories check_all="yes" realtime="yes" report_changes="yes">/etc/fstab</directories>
    <directories check_all="yes" realtime="yes" report_changes="yes">/etc/audit/auditd.conf</directories>

<directories check_all="yes" realtime="yes" report_changes="yes">/etc/passwd</directories>
    
    <ignore>/etc/mtab</ignore>

    
    <nodiff>/etc/ssl/private.key</nodiff>

    <skip_nfs>yes</skip_nfs>

    
    <remove_old_diff>yes</remove_old_diff>

    
    <restart_audit>yes</restart_audit>
  </syscheck>

...

<email_alerts>
        <email_to>site1-l-management-01@certification.tn</email_to>
        <rule_id>550</rule_id>
        <event_location>SITE1-L-MANAGEMENT-01</event_location>
        <do_not_delay />
</email_alerts>

....

</ossec_config>

**Comment by bah07** [comment]
Hi @wafaance 

We have unified several issues that report problems related to the fields that appear in the email alerts. We're going to close this issue for duplication and fix it in the next sprint.

You can see the development status in the next issue we'll be working on in the next few weeks.
Thank you and best regards.
