### ISSUE TITLE
SysCollector fails to fetch some Windows hotfixes

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#5664]
Hi team,

The current implementation of SysCollector for Windows fetches the hotfixes list from `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages`, reading all the entries that match the format `Package_X_for_<hotfix>`.  It has proven to be an effective solution for the last couple of years, but due to its design, there might be some cases where it fails to fetch the hotfixes.

For instance `KB4565483` (WIndows 10 1909) :

- It does appear with the Powershell commands `get-hotfixes` and  `wmic qfe get`.

- It doesn't have a proper `Package_X_for_<hotfix>` entry in `HKEY_LOCAL_MACHINE`, although it appears as a rollup `Package_for_RollupFix~31bf3856ad364e35~amd64~~18362.959.1.9`.

- Within the entry, we can found at the `Location` field:
` C:\WINDOWS\SoftwareDistribution\Download\45c607e11a3b77e9e67a19227e0ffa65\Windows10.0-KB4565483-x64.cab`

#### Solution
- Ideally,  we should switch to a more reliable solution such as a public C Windows API. Alas, we should assume that there're more unknown cases where the hotfixes are not showing up.

- Worst case scenario, we stick with the parser but adding new regular expressions, in order to match those entries with unusual names.

A very careful investigation must be carried out. The new solution must be portable among all Windows versions.

Regards,
Fernando

**Comment by chemamartinez** [comment]
Done at https://github.com/wazuh/wazuh/pull/5792
