### ISSUE TITLE
Windows agents collecting Active-response.log from the begining.

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh#5684]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1 | Localfile/Logcollector | Agent | Packages | Windows Server 2012 |

Hello team,

We found an issue with the Windows agent and active-response.log.

The agent seems to be reporting the log file from the beginning with every restart, generating multiple duplicated events.

![image](https://user-images.githubusercontent.com/37381070/89678452-76cab180-d8ef-11ea-80f2-4df5325040fb.png)

In the above picture, every stack of 7 events corresponds to a restart performed in the same agent which has 7 events in active-response.log.

Reproducing the issue is simple: Using a Windows agent, use active response, check that active-response.log is being populated and restart the agent to see events being sent to the manager with every restart.

Best regards,
Miguel Ruiz

**Comment by vikman90** [comment]
This issue should have been fixed by #9364.
