### ISSUE TITLE
wazuh install with mysql

### ISSUE THREAD

**Issue by huweiqing915** [wazuh/wazuh#569]
I want to insert alerts event into mysql, but I don't know how to configure it. Is there has any document about how to compile ossec with mysql.

**Comment by crolopez** [comment]
Hi @huweiqing915,

You can see the options to configure Mysql as Wazuh output in [this page](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/database-output.html?highlight=database). However, we know that this documentation is insufficient to configure it, so we will improve it soon.

To run the database output you will have to compile Wazuh indicating the database flag:

```
wget https://github.com/wazuh/wazuh/archive/v3.2.1.tar.gz -O wazuh.tar.gz
tar zxvf wazuh.tar.gz
cd wazuh-3.2.1//src
make TARGET=server DATABASE=mysql
../install.sh
```

You may need some dependencies. For Ubuntu you will need the following packages:

- mysql-server
- libmysqlclient-dev

In addition, you need to create the database and user that you will indicate in the ossec.conf file. Once you have created the database you must create the tables inside it by loading the file that you can find in _src/os_dbd/mysql.schema_.

Best regards.
