### ISSUE TITLE
CDB list: error parsing ':' character

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh#5690]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.x | CDB lists| Manager | both | all |

Hello team,

### Problem definition
We've detected a problem with CDB lists. When you define a key-value pair with `:` character, for example:

```json
key: "https://wazuh.com"
value: "wazuh
```
### Current behavior
Wazuh will load the CDB list with key `https` and value `//wazuh.com"` 

![Screenshot_20200810_114212](https://user-images.githubusercontent.com/15269938/89770126-9683f480-dafe-11ea-82db-63a10691286d.png)

### Expected behavior

Reading the code at https://github.com/wazuh/wazuh/blob/c4f7457782312b7d81bf4563060e85e43ef737f7/src/analysisd/lists_make.c#L74 I would expect that a key surrounded by double quotes would be correctly parsed.

Also, If I try to create a new list from the app with such key I got the following error:

```
Wazuh API error: 705 - Invalid CDB list. Format for CDB list is 'key:value'. Line 1: https://wazuh.com:wazuh
```

![Screenshot_20200810_114559](https://user-images.githubusercontent.com/15269938/89770512-2d50b100-daff-11ea-83d8-eb232bf6b9a3.png)

I think there is a problem with the CDB list parser. We should consider a way to scape keys containing '`:` character. I guess that the expected behavior would be to be able to scape such key with quotes but currently, it doesn't work. That probably generated the last-mentioned error.

Best regards.

**Comment by branchnetconsulting** [comment]
I originally requested this issue be fixed at the Wazuh Manager level in late 2018 (#1500).  I think that was successfully resolved at that time but when manipulation of CDB lists via the Wazuh API & UI was added later, the support for surrounding the key or the value in double quotes to prevent a colon from breaking the parsing of the CDB record, may not have been taken into account.  I imagine it should be a pretty easy fix at either the Wazuh API or Wazuh UI level.

Kevin
