### ISSUE TITLE
Wazuh agent not able to detect my OS distro version

### ISSUE THREAD

**Issue by djmgit** [wazuh/wazuh#5711]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Manager - 3.13, Agent - 3.9 | Agent | Agent | Packages | Debians |

Wazuh agent is not able to detect by OS distro version on some of my hosts. It is simply reporting major and minor version to be 
```0```.

Below is an example where its unable to detect version : 

```
{
   "error": 0,
   "data": {
      "node_name": "node01",
      "os": {
         "arch": "x86_64",
         "major": "0",
         "minor": "0",
         "name": "Debian GNU/Linux",
         "platform": "debian",
         "uname": "Linux |FQDN |kernel info|x86_64",
         "version": "0.0"
      },
      "name": "hostname",
      "mergedSum": "40a0aa494c33b6eac8b6679fde69bcca",
      "status": "Active",
      "lastKeepAlive": "2020-08-11 10:59:40",
      "version": "Wazuh v3.9.3",
      "dateAdd": "2020-08-10 12:25:41",
      "group": [
         "default"
      ],
      "ip": "1.2.3.4",
      "configSum": "ab73af41699f13fdd81903b5f23d8d00",
      "id": "053",
      "manager": "manager_name",
      "registerIP": "any"
   }
}

```

Also for these hosts Wazuh is unable to detect vulnerabilities. My manager is at version 3.13 and is configured with both Debian and NVD provider. The manager is able to detect vulnerabilities for hosts for which its able to detect version but not for the ones where distro version is undetected.

How can the version issue be fixed and can there be any other reason for vulerability detection is not working?

**Comment by 0xN3utr0n** [comment]
Hi @djmgit ,
It's perfectly normal for Vulnerability-Detector to be unable to work properly without the distribution's version; the reason being that Debian offers a unique feed per version, so we use them as the main source (aside from the NVD).

As far as I can see, It looks like SysCollector module is not fetching correctly all the system's information. 
Please run the following command and paste the output:
` $ uname -a`

Note however, that Debian `Jessie` and `Wezzy` have been recently deprecated, therefore no vulnerabilities should be reported for them.

Kind regards,
Fernando

**Comment by djmgit** [comment]
@0xN3utr0n 

Output of ```uname -a```

```
Linux <hostname> 4.20.13-<custom> #1 SMP Tue Mar 5 14:45:59 UTC 2019 x86_64 GNU/Linux
```

The output is same for both the servers, the one for which vulnerability is being detected and also the one for which it is not being detected.

**Comment by 0xN3utr0n** [comment]
@djmgit 
The version is fetched from `/etc/debian_version` file. Besides that, we use `uname` as an additional source.

Which distro do you have currently installed? (Debian `Buster`, `Strech`...)

kind regards,
Fernando

**Comment by djmgit** [comment]
@0xN3utr0n 

We use both ```Buster``` and ```Strech``` in our servers. Some have Buster and some have Strech.
However in all the servers /etc/debian_version is populated. The file contains the respective version number.

**Comment by 0xN3utr0n** [comment]
@djmgit 
Mmm that's odd... Are you perhaps using Wazuh in a clustered environment?
In addition to that, do the affected agents have anything in common? Or just all the agents are having the same issue? 

Kind regards,
Fernando

**Comment by djmgit** [comment]
@0xN3utr0n 

Nope, I am not using Wazuh in cluster mode.

However I found some difference between the functioning and the non functioning server

On the servers where vuln is getting detected has their version number in /etc/os-release and /etc/issue

On functioning server :
```
/etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

/etc/issue

Debian GNU/Linux 10 \n \l

```

On non fucntioning hosts:

```
/etc/os-release

PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"

/etc/issue

Debian GNU/Linux buster/sid \n \l
```

**Comment by 0xN3utr0n** [comment]
Good catch @djmgit ! It seems that `/etc/os-release` has priority over `/etc/debian_version`.

That's certainly a bug on our part, so I'll open a proper issue and try to fix it asap. Meanwhile, as a workaround, you can remove `/etc/os-release`, which wil force SysCollector to switch and use `/etc/debian_version`.

Kind regards,
Fernando

**Comment by djmgit** [comment]
@0xN3utr0n 

I updated /etc/os-release in one of my non-functioning hosts, provided the proper version there. Post that, Wazuh was able to detect the OS distro version correctly and now vulnerabilities are also getting reported.

I guess and as you aready mentioned, Wazuh might be using /etc/os-release to determine version.
It would be good if the documentation too mentions about this.

Thanks for your help :)
