### ISSUE TITLE
Can't get active response logs in manager/kibana

### ISSUE THREAD

**Issue by docsolid** [wazuh/wazuh#5720]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1-1 | Active Response | Manager | Packages | Debian 10 |

I have a working setup, agents report in, active response is also working fine and logs to /var/ossec/logs/active-responses.log on the agent. On the server, /var/ossec/logs/active-responses.log is empty.
I do not use a custom script, I'm testing with "firewall-drop" command.
No active response logs in /var/ossec/logs/alerts.log on the manager.
The only port on manager that is reachable for the agents is 1514 (1515 is not reachable, i connect agents by hand).

Anyone got the same issue? Any suggestions?

Thx in advance!

**Comment by docsolid** [comment]
Ok, update: I found the logs in /var/ossec/logs/archives/archives.log

please update the following tutorial:
https://documentation.wazuh.com/3.13/learning-wazuh/shellshock.html#use-kibana-to-review-active-response-actions-taken-on-all-agents-during-this-lab

it's really not as easy as it's written there.. I'm still not sure how to get the messages now into alert.log

**Comment by docsolid** [comment]
Okay guys, the problem are the locales..
As soon as a date string does not start like "Wed Aug 12 17:13:21", the decoders don't recognize it and the log gets lost in the depths of archive.. This may be worth mentioning somewhere?!

**Comment by davidjiglesias** [comment]
Hello @docsolid,

Thank you for your contribution. As you said, this may really be worth mentioning.

Could you please share one exact log (the ones you said you found in archives.log). This may help us identify the exact steps we need to follow to fix the issue.

Regards,

David J. Iglesias

**Comment by docsolid** [comment]
Hi David, thx for your response.

Here's the sample data:

NOT WORKING:
Mi 12. Aug 16:46:33 CEST 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...

WORKING OUT OF THE BOX:
Wed Aug 12 17:13:55 CEST 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...

I'd like to add that you guys are doing an amazing job!! Wazuh is one of the things every medium size IT environment will use in the near future if they at least heard of security operations. All the integrations and plugins you made, the usability with kibana and the possbilities of customized integrations are simply a must have for every secop.  
THX!

**Comment by davidjiglesias** [comment]
Hello @docsolid,

First of all, sorry for the late reply and thank you for your words and support towards our project!

Regarding your issue, try adding this extra decoder to `WAZUH_PATH/etc/decoders/local_decoder.xml` where `WAZUH_PATH` is your local Wazuh installation folder (`/var/ossec` by default):

```
<decoder name="ar_log">
  <prematch>^\w\w \d+.\s+\w+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/|^\w\w\w \d\d/\d\d/\d\d\d\d \.+"active-response/bin/|^\d\d/\d\d/\d\d\d\d \.+"active-response/bin/</prematch>
</decoder>
```

After that, your firewall-drop should match and raise an alert equally to the other log. I tested that:

```
2020/08/26 07:53:43 ossec-testrule: INFO: Started (pid: 11539).
ossec-testrule: Type one log per line.

Mi 12. Aug 16:46:33 CEST 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...


**Phase 1: Completed pre-decoding.
       full event: 'Mi 12. Aug 16:46:33 CEST 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...'
       timestamp: '(null)'
       hostname: 'wazuh-master'
       program_name: '(null)'
       log: 'Mi 12. Aug 16:46:33 CEST 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...'

**Phase 2: Completed decoding.
       decoder: 'ar_log'

**Phase 3: Completed filtering (rules).
       Rule id: '607'
       Level: '3'
       Description: 'Active response:  - '
**Alert to be generated.
```

It seems as if your log is generating the date in spanish? I hope this helps you solve your issue.

Please do not hesitate to contact back with any issues you might have.

Best regards,

David J. Iglesias

**Comment by NDetienne** [comment]
Hello,
I am testing this powerfull and great application and I have the same kind of problem.
The setup is working well, agents stop attacks with the firewall-drop command.

Active responses are correctly written on /var/ossec/logs/active-responses.log on agents side but theses action-responses couldn't be found on wazuh-manager.
It seems that it is possible to have an overview of all active-responses with Kibana but in my case I only found 2 old action-responses.

Here are logs, only the active-response of Tuesday (add/delete) are available on Kibana the others are not parsed by Kibana:

On agent1:

> **Tue Oct 27 13:34:43 UTC 2020 /var/ossec/active-response/bin/host-deny.sh add - ... parsed by Kibana
> Tue Oct 27 13:35:44 UTC 2020 /var/ossec/active-response/bin/host-deny.sh delete - ... paresed by Kibana**
> Wed Oct 28 11:46:17 UTC 2020 /var/ossec/active-response/bin/firewall-drop.sh add - ...
> Wed Oct 28 11:47:18 UTC 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...
> ...

On other agents nothing are available on Kibana:

> Wed Oct 28 12:42:33 CET 2020 /var/ossec/active-response/bin/firewall-drop.sh add - ...
> Wed Oct 28 12:43:34 CET 2020 /var/ossec/active-response/bin/firewall-drop.sh delete - ...
> ...


Kibana setting for Date format is: MMM D, YYYY @ HH:mm:ss.SSS and for nanoseconds: MMM D, YYYY @ HH:mm:ss.SSSSSSSSS


I don't know why Kibana don't show other logs than those on Tuesday. May be something has been changed on configuration but I can't find it. 
Do you have any idea how to fix it ?
Thanks for your help and for this great application !

Regards,
Nicolas
