### ISSUE TITLE
Multiple Groups

### ISSUE THREAD

**Issue by ruzzetto** [wazuh/wazuh#574]
Hi,
I created several groups but I noticed it's not possible to assign more than one group to agent.  For example I'd like to assign "Windows" and "Production" groups or "CentOS" and "Testing"..

Regards,
Fabio

**Comment by chemamartinez** [comment]
Hi @ruzzetto,

The own philosophy of groups is not compatible with assign more than one group to an agent. This is why one of the goals of agent groups is to share a particular configuration with its agents, and an agent is not allowed to receive two different configuration files from its manager.  

I suggest you take a look at this option of the ``agent.conf`` file:
https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html#options

These options allow you to classify agents in your group by name/OS/profile setting a different configuration block for each one of your agents. For example, having the "Testing" and "Production" groups, you could set a configuration as follows:

```
<agent_config os="windows">
...
</agent_config>
<agent_config os="centos">
...
</agent_config>
```

Best regards,
Chema.

**Comment by ruzzetto** [comment]
Hi Chema,
thanks for you clarification. 

Regards,
Fabio
PS: please close the ticket :)
