### ISSUE TITLE
OwlH to Wazuh NIDS :- Integration

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#5743]
An issue as a repository for some diagrams about Current architecture, near future drafts, and a far-future dream, hopefully no as far.

**Comment by jizquierdo-owlh** [comment]
Current Architecture. it's mainly a parallel relationship between OwlH and Wazuh 

![image](https://user-images.githubusercontent.com/34478747/90230422-d22dff80-de19-11ea-81b1-c4d0f292d72f.png)

**Comment by jizquierdo-owlh** [comment]
Near Future.
OwlH UI will be integrated as part of the Wazuh Kibana Plugin. 
Integrated UI keeps OwlH Management by API calls. 
The user has a single point to contact with both UI. 
OwlH Dashboards are going to be integrated within the new UI Plugin. 
OwlH Filebeat Module is going to be integrated with Wazuh Module. 

![image](https://user-images.githubusercontent.com/34478747/90231206-1b328380-de1b-11ea-817e-febb3ac730d7.png)

**Comment by jizquierdo-owlh** [comment]
Far Future, 
Agent, Cluster Master, and workers has a NIDS Module. It is OwlH API integrated as a module. (tons of discussion here)
Kibana Plugin has evolved from the previous NF scenario.  

![image](https://user-images.githubusercontent.com/34478747/90234098-63ec3b80-de1f-11ea-9da8-bbdd06227fc6.png)
