### ISSUE TITLE
Wazuh can't receive appliacation logs :

### ISSUE THREAD

**Issue by manhdinh** [wazuh/wazuh#575]
Can Wazuh take application logs?
 I config to collect log in /var/ossec/etc/ossec.conf :http://prntscr.com/jan2oo
 In the ossec.log : http://prntscr.com/jan1mm  . However i didn't see any log of my application in Kibana.

My Wazuh server is installed in Centos 7.3, version 3.2. I deployment Wazuh server in the same server with ELK stack.
Thanks !

**Comment by manhdinh** [comment]
@vikman90  Thank for your answer. So i guest if i want to collect & analyze logs, i must use some backend for ELK like Filebeat to collect & transfer logs to Wazuh server?
I have another question is  : Can i use alert function of Wazuh to make notification from logs. For example when the count of ERROR field inscrease more than 100 in 5 minute, Wazuh will send a email to administrator?

**Comment by alberpilot** [comment]
Hello @manhdinh 

  Sorry for the late response. Wazuh collects and filters logs itself, but they are stored in .json or .log files. Tools like ELK, Splunk, etc allow us to have more complex queries and powerful analysis tools. 

> I have another question is : Can i use alert function of Wazuh to make notification from logs. For example when the count of ERROR field inscrease more than 100 in 5 minute, Wazuh will send a email to administrator?

Yes, you can configure it: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html

Hope it help.
Best regards, 
Alberto R.
