### ISSUE TITLE
Update Ruleset

### ISSUE THREAD

**Issue by digitallantern** [wazuh/wazuh#5754]
|Wazuh 3.9|update ruleset

Hello, i am trying to update my wazuh ruleset with the update_ruleset command but i am getting this error,

ERROR: Upgrade Aborted: Unexpexted version in the new ruleset. Expected version v3.9.x. Found version v 3.13.1

I am running the command as root in the /var/ossec/bin directory. Any help is much appreciated.

Thanks!

**Comment by davidjiglesias** [comment]
Hello @digitallantern,

I will be glad to try and help you here. You are running and old version of Wazuh, and so using the update_ruleset CLI without any parameters will try to update your ruleset to the latest version. 

Please try the following command and let me know if it works (substitute 3.9.5 for the target version of the ruleset you want to update to):

`/var/ossec/bin/update_ruleset -u https://github.com/wazuh/wazuh-ruleset/archive/v3.9.5.zip -n 3.9.5 -f`

**Comment by digitallantern** [comment]
So this will not get me the most recent ruleset available? I am looking to update the ruleset weekly and dont want to be out of date. Would i have to update my wazuh agent?

**Comment by digitallantern** [comment]
I also ran the command and i got this error:
ERROR: Error extracting file '/var/ossec/tmp/ruleset/downloads/ruleset.zip': 'NoneType' object has no attribute 'group'.

**Comment by davidjiglesias** [comment]
Hello @digitallantern,

Sorry, I think I misunderstood your original question. I though you wanted to update the ruleset in your wazuh-manager for a different reason. If you are looking to upgrade the ruleset to the latest available version you have to update your wazuh-manager to the latest version.

For example,  ruleset version 3.13.1 might not be compatible with your manager 3.9.X. I recommend you upgrade your managers when there is a new release, that is the best way to always be updated with Wazuh latest improvements and the latest ruleset. Also, there has been numerous fixes and overall enhancements from 3.9.X to 3.13.1.

I hope this help solving your doubts. Please do not hesitate to contact back with any other questions.

Best regards,

David J. Iglesias

**Comment by digitallantern** [comment]
Does the ruleset for 3.9.x still get updated? I am having trouble upgrading to 3.13. I followed the instructions to upgrade and it says files dont exist. I am running this on security onion.

**Comment by davidjiglesias** [comment]
Hello @digitallantern,

If you update your Wazuh Manager to version 3.13.1, then the ruleset will also be updated to version 3.13.1.

Here you have a guide on how to upgrade your Wazuh Manager: https://documentation.wazuh.com/3.13/upgrade-guide/upgrading/latest_wazuh3_minor.html?highlight=upgrade

Please follow the steps to fully upgrade your Wazuh Manager and let me know how it goes.
