### ISSUE TITLE
Memory leak on sync-agent-info-get

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#5769]
|Wazuh version|Component|Install type|
|---|---|---|
|4.0.0|Wazuh-db|

wdb_sync_agent_info_get() asks for labels from a specific agent and the returned json object is added to an agent json object which is finally freed. If labels are returned as an json object without a child, the labels object isn't added to the agent json object, thus, it will not be freed.
This scenario must be handled.

**Comment by DProvinciani** [comment]
Closing the issue as https://github.com/wazuh/wazuh/pull/5770 was merged.
