### ISSUE TITLE
 ignore + same_source_ip is not as expected

### ISSUE THREAD

**Issue by onelife9** [wazuh/wazuh#5780]
there was a similar topic

https://github.com/wazuh/wazuh/issues/1716

I need to use ingore + same_source_ip, but all IPs are ignored.

Any news?

**Comment by davidjiglesias** [comment]
Hello @onelife9,

Thank you for reaching us. It seems as it has not been included yet. I will tag the original issue as community_support and move it to Waiting R&D, where our experts will check the implications for the development and possibly include it in Wazuh roadmap after a investigation.

We are constantly improving our software development cycle as well as our community support. Thank you for your patience and consideration.

Best regards,

David J. Iglesias
