### ISSUE TITLE
Intergirty Monitoring Not Picking Linux Box Agents

### ISSUE THREAD

**Issue by sp3107** [wazuh/wazuh#5785]
|3.13|Agent|Data Not Shown for Some Modules in Kibana App|FIM, AWS|CentOS(AWS EC2), Windws(Laptop)|
|---|---|---|---|---|

I have installed Wazuh Agent in some 5/6 Linux Box (Cloud) and 1 Windows (laptop). I can get Integrity management dashboard only for Laptop (Windows) and not for any linux. Please see attached screen shot.

Also, I was expecting AWS dashboard to get populated as most of my agents are installed on EC2 but it is showing blank.

I can see some other dashboard from Linux boxes , so Linux boxes are definitely working.

I have followed the documentation religiously.

**Comment by bah07** [comment]
Hi @sp3107 , sorry for the late response.

To ensure that everything is configured correctly we will get some information about the agents.

**NOTE:** Change de `<agent_id>` string with the id of the agent.

Check the configuration.
> curl -u foo:bar -k -X GET "https://127.0.0.1:55000/agents/<agent_id>/config/syscheck/syscheck?pretty"

If the configuration is correct, please, check if any FIM scan has been done with the next call:
> curl -u foo:bar -k -X GET "https://127.0.0.1:55000/syscheck/<agent_id>/last_scan?pretty"

You should see something like that:
```json
{
   "error": 0,
   "data": {
      "start": "2020-08-25 08:40:40",
      "end": "2020-08-25 08:40:47"
   }
}
```

You can also view the inventory data obtained from the scan on the inventory tab in the Integrity Monitoring module. For example:
![Captura de pantalla de 2020-08-25 12-25-59](https://user-images.githubusercontent.com/6572618/91163663-3c725a00-e6ce-11ea-80b7-ba673687e47e.png)

If you still have problems you can activate the FIM debug mode in the configuration file and see the log output to have some more information about what is happening.
> /var/ossec/etc/internal_options.conf

Changing the option:
`syscheck.debug=2`

With this command you can filter the information of the specific module.
> cat /var/ossec/logs/ossec.log |grep syscheckd

Regarding the configuration of AWS, have you followed the steps described in our documentation?

https://documentation.wazuh.com/3.13/amazon/services/supported-services/config.html?highlight=aws
