### ISSUE TITLE
Urgente: Error Elasticsearch & Wazuh Api & Kibana

### ISSUE THREAD

**Issue by samcontreras** [wazuh/wazuh#5787]
Dear, good afternoon. I turn to you because I already burned my head from trying hundreds of solutions so much and I have not been able to solve.

To begin I explain my case:
1) On an Ubuntu 20.04 server (Server ip: 10.10.201.120; hostname: wazuh02) to Wazuh - Agent (windows 10: ip 10.10.50.103), I am installing wazuh manager, wazuh, wazuh api, filebeat, elastic search, and kibana . I did a zero installation, following the step-by-step manual is installation "From packages"

a) https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/ubuntu/wazuh_server_packages_ubuntu.html#wazuh-server-packages-ubuntu (worked with errors)
b) https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/elastic_server_deb.html (buggy)
c) https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.html#wazuh-agent-package-windows (worked, I had no problem binding the agent)

I followed all the instructions to the letter, but even so, I could not make it work step a and B, I send you the excerpts of the errors that it meda:

Error 1): From a windows browser: https://10.10.201.120:55000/
enter, ask for username and password, I type it from the keyboard, and then enter and this error appears:

{"error": 0, "data": {"msg": "Welcome to Wazuh HIDS API", "api_version": "v3.13.1", "hostname": "wazuh02", "timestamp": "Thu Aug 20 2020 17:02:31 GMT + 0000 (Coordinated Universal Time) "}}

Error 2): ElasticSearch, I do not know the reason but I stopped the service, it was active before, this is the error:
Loaded: loaded (/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2020-08-20 17:03:33 UTC; 21s ago
       Docs: https://www.elastic.co
    Process: 12684 ExecStart = / usr / share / elasticsearch / bin / systemd-entrypoint -p $ {PID_DIR} /elasticsearch.pid --quiet (code = exited, status = 1 / FAILURE)
   Main PID: 12684 (code = exited, status = 1 / FAILURE)

Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.bootstrap.Elasticsearch.init (Elasticsearch.java:170)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.bootstrap.Elasticsearch.execute (Elasticsearch.java:161)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.cli.EnvironmentAwareCommand.execute (EnvironmentAwareCommand.java:86)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.cli.Command.mainWithoutErrorHandling (Command.java:127)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.cli.Command.main (Command.java:90)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.bootstrap.Elasticsearch.main (Elasticsearch.java:126)
Aug 20 17:03:33 wazuh02 systemd-entrypoint [12684]: at org.elasticsearch.bootstrap.Elasticsearch.main (Elasticsearch.java:92)
Aug 20 17:03:33 wazuh02 systemd [1]: elasticsearch.service: Main process exited, code = exited, status = 1 / FAILURE
Aug 20 17:03:33 wazuh02 systemd [1]: elasticsearch.service: Failed with result 'exit-code'.
Aug 20 17:03:33 wazuh02 systemd [1]: Failed to start Elasticsearch.
root @ wazuh02: / var / ossec / logs # Job for elasticsearch.service failed because the control process exited with error code.

2a)
Sending configuration data:
/etc/elasticsearch/elasticsearch.yml
network.host: <10.10.201.120>
node.name: <wazuh-cluster>
cluster.initial_master_nodes: ["<wazuh-cluster>"

This is the other way I tried, I don't know which one is correct, none of it worked:

node.name: $ {HOSTNAME}
cluster.initial_master_nodes: ["HOSTNAME"]
network.host: ["10.10.201.120"]
path.data: / var / lib / elasticsearch
path.logs: / var / log / elasticsearch
bootstrap.memory_lock: true
2 b)
/etc/kibana/kibana.yml:

server.host: "<10.10.201.120>"
elasticsearch.hosts: ["http: // <10.10.201.120>: 9200"]
server.ssl.enabled: true
server.ssl.key: /etc/kibana/kibana.key
server.ssl.certificate: /etc/kibana/kibana.cert
telemetry.enabled: false

I ask you please to help me,  thank you very much for the prompt response.

Elastisearch logs:

[2020-08-20T18: 24: 38.441 + 0000] [1261] [gc, heap] Heap region size: 1M
[2020-08-20T18: 24: 38.441 + 0000] [1261] [gc, heap, coops] Heap address: 0x00000000c0000000, size: 1024 MB, Compressed Oops mode: 32-bit
[2020-08-20T18: 24: 38.505 + 0000] [1261] [gc] Using G1
[2020-08-20T18: 24: 38.982 + 0000] [1261] [gc] Periodic GC disabled
[2020-08-20T18: 24: 39.241 + 0000] [1261] [gc, heap, exit] Heap
[2020-08-20T18: 24: 39.241 + 0000] [1261] [gc, heap, exit] garbage-first heap total 1048576K, used 1024K [0x00000000c0000000, 0x0000000100000000)
[2020-08-20T18: 24: 39.241 + 0000] [1261] [gc, heap, exit] region size 1024K, 2 young (2048K), 0 survivors (0K)
[2020-08-20T18: 24: 39.241 + 0000] [1261] [gc, heap, exit] Metaspace used 3134K, capacity 4480K, committed 4480K, reserv

**Comment by samcontreras** [comment]
#5751

**Comment by pablotr9** [comment]
Hi @samcontreras !

Is everything installed in the same machine? 

Let's update your `/etc/elasticsearch/elasticsearch.yml` with this basic configuration (I guess the server IP where Elasticsearch is installed is 10.10.201.120, if not please modify with its IP)
```
cluster.name: "my-cluster"
node.name: "es-node-1"
node.master: true
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
cluster.initial_master_nodes:
  - "es-node-1"
network.host: 10.10.201.120
```

Now let's update your `kibana.yml`, make sure that everything is commented, you will only need these 2 settings:
```
server.host: "0.0.0.0"
elasticsearch.hosts: ["http://10.10.201.120:9200"]
```


Now please restart both services:
```
systemctl restart  elasticsearch kibana
```
Wait some seconds and check the services status, also check if you can access Kibana in your browser:
`http://KIBANA-SERVER-IP:5601`
(Replace KIBANA-SERVER-IP with the IP of the machine where Kibana is installed)


Best Regards,
Pablo Torres

**Comment by pablotr9** [comment]
Hi @samcontreras,

> Well, clearing up the suggested settings, should they be like this? "4 item´s"

Yes, that Elasticsearch basic configuration looks ok.



> the port disabled, that commented line is ok, right?

Yes, by default the port that Kibana uses is the port 5601 so you don't have to uncomment it.



> The ip goes without quotes "", and is it 0.0.0.0 or should it be the ip of the server, in my case, 10.10.201.120? )

You can write it with quotes, let's now set the server.host with 0.0.0.0, once it's working you can change it if necessary

----------

Let's now check the Kibana message: Kibana server is not ready yet
The configuration looks ok. Kibana takes a few seconds/minutes to start, please try accessing Kibana again after a while, if the `Kibana server is not ready yet` message persists, please try checking Kibana logs and share those logs with me:
```
journalctl -u kibana
```
-----------

> [step five installation elasticsearch, ]
What is the directory where you have to execute these command lines? /etc/filebeat ???

You don't have to run that command in any specific directory




Regarding your last reply, please check Wazuh Api logs and share them with me, those logs can be found here:
```
cat /var/ossec/logs/api.log
```


Best Regards,
Pablo Torres

**Comment by pablotr9** [comment]
Hi @samcontreras,

 I will close this issue due to inactivity, please feel free to reopen it if the problem persists or open a new issue.

Best Regards,
Pablo Torres
