### ISSUE TITLE
How can the monitoring agent be illegally stopped or deleted?

### ISSUE THREAD

**Issue by yingshang** [wazuh/wazuh#5812]
The server and agent have established a connection. If I am a hacker, I directly stop the ossec process or delete the ossec directory, the server does not receive an abnormal log from the agent, and the connection status still shows alive.

I kill the wazuh agent run process
![image](https://user-images.githubusercontent.com/11006249/91161394-4a8b9f00-e6fd-11ea-9a22-40b50e685d7a.png)
but wazuh server status still show active
```
[root@test-wazuh-manager ~]# /var/ossec/bin/agent_control -lc

Wazuh agent_control. List of available agents:
   ID: 005, Name: localhost.localdomain, IP: 192.168.1.2, Active
```
how can i solve monitoring the agent status changed?

**Comment by Selutario** [comment]
Hi @yingshang,

If I understand you correctly, your question is why after shutting down or removing Wazuh agent, the manager still shows it as active.

This is relatively normal behavior. To determine if an agent is connected, the manager periodically receives a keepalive message from it. Only when it does not receive any keepalive for **30 minutes**, the manager will consider that the connection with the agent has been lost.

The interval can be modified only at compilation time, for that you will need to adjust following parameters:
 - The constant `DISCON_TIME`: https://github.com/wazuh/wazuh/blob/f012b5bf0e3b29bb09ca3ea80f6b2ce9c7d5334a/src/headers/defs.h#L98
- The variable `limit_seconds`: https://github.com/wazuh/wazuh/blob/f012b5bf0e3b29bb09ca3ea80f6b2ce9c7d5334a/framework/wazuh/common.py#L107

Then you will need to compile the manager as explained here:
https://documentation.wazuh.com/3.13/development/makefile.html#compiling-the-source-code

Let me know if this is useful for you.

Best regards,
Selu.

**Comment by yingshang** [comment]
Maybe my description is wrong. What I mean is that if the host has been hacked, the hacker knows that the server has wazuh monitoring, so he will kill the process or delete the wazuh directory directly. I test to stop the process or delete the wazuh directory, the wazuh server will not receive any warning information, I want to know how to get this warning information. So I can immediately check whether the server has been compromised.

**Comment by yingshang** [comment]
Because I saw that the commercial version of the intrusion detection system will have such a function, when the hacker deletes the monitoring client, the customer will know that the hacker deletes the monitoring client.

**Comment by Selutario** [comment]
Hi @yingshang,

To stop the Wazuh service or remove the ossec directory, you would need superuser privileges. It would possibly be too late if an intruder has gained access to even that.

The key is to monitor and detect someone's attempt, or intrusion into the system. To do this, Wazuh integrates HIDS (Host-based Intrusion Detection System) services such as Suricata. Take a look at this part of the documentation where it explains how to configure suspicious network traffic detection: https://documentation.wazuh.com/3.13/learning-wazuh/suricata.html

A full integration of OwlH in Wazuh is also in the works right now. You can see a related issue here: https://github.com/wazuh/wazuh/issues/5743

Kind regards,
Selu.

**Comment by yingshang** [comment]
I know, thank you very much for your answer.
