### ISSUE TITLE
VirusTotal Modification [Q]

### ISSUE THREAD

**Issue by AshourAziz** [wazuh/wazuh#582]
Is it to naive to say that a slight modification to the API endpoints in the VirusTotal python program would allow the source of intel be changed from VirusTotal to another source such as AlienVault's OTX or a threat intel feed like CIF?

Assuming the JSON response is identical to what Wazuh is expecting.

**Comment by vikman90** [comment]
Hi @AshourAziz,

Absolutely, I don't know those APIs but you could use the VirustTotal integration script to do it. It would be very interesting to produce logs with other identification than "virustotal" so the ruleset could be extended to support more API integrations.

Unfortunately, the design of the Integrator daemon requires new integrations to be added programmatically but it's easy to do.

However, if you only want to replace VirusTotal by another API, you can modify the VirusTotal integration script perfectly.

Hope it help.
Best regards.

**Comment by AshourAziz** [comment]
I appreciate the response.

I felt as if it was almost 'too easy' so i was looking for a second opinion to confirm my thought process.

I will most likely fork and modify VirusTotal files to support a 'proxy' that ingests multiple threat exchange data and responds in the same way VirusTotal does that way you can theoretically add as many feeds as someone wishes.

Thanks!
