### ISSUE TITLE
Remove argument check for wdb_parse_global_sync_agent_info_get

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#5829]
|Wazuh version|Component|Install type|
|---|---|---|
|4.0.0|Wazuh-db|

wdb_parse_global_sync_agent_info_get() argument is optional, but wdb_parse() is rejecting the command if no argument is found previous the call. This check should be removed.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/5831 was merged.
