### ISSUE TITLE
Libraries installed in the Wazuh folder interfere with those of the system

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#583]
In Ubuntu 18.04 `curl` and `openssl` tools try to load the libraries installed in the Wazuh folder instead of the system libraries:

```
/usr/bin/curl: /var/ossec/lib/libcurl.so.4: no version information available (required by /usr/bin/curl)
	libcurl.so.4 => /var/ossec/lib/libcurl.so.4 (0x00007f2dffa7f000)
	libz.so.1 => /var/ossec/lib/libz.so.1 (0x00007f2dff861000)
	libssl.so.1.1 => /var/ossec/lib/libssl.so.1.1 (0x00007f2dfefe1000)
	libcrypto.so.1.1 => /var/ossec/lib/libcrypto.so.1.1 (0x00007f2dfeb54000)
```

This is because Wazuh starts the first program as a service. The path to the libraries is stored in the `ldd`'s cache and it will load those libraries for the rest of programs instead of the correct libraries in the system folder.

**Comment by chemamartinez** [comment]
To solve this issue, we have merged all the external libraries into a unique shared library. The progress of this development can be followed in this branch: https://github.com/wazuh/wazuh/tree/dev-shared-ext

OS tested:
- [X] Ubuntu 18/16
- [X] CentOS/RHEL 7
- [X] CentOS 5
- [X] macOS
- [x] Solaris 11/10
- [x] FreeBSD
- [ ] OpenBSD
- [ ] NetBSD
- [ ] HP-UX
- [ ] AIX
- [ ] Windows (NSIS)
- [ ] Windows (MSI)

**Comment by vikman90** [comment]
Master branch does not compile on macOS:

```
src$ make TARGET=server V=1
/Library/Developer/CommandLineTools/usr/bin/make ossec-maild - ossec-csyslogd - ossec-agentlessd - ossec-execd - ossec-logcollector - ossec-remoted ossec-agentd manage_agents utils ossec-syscheckd ossec-monitord ossec-reportd ossec-authd ossec-analysisd ossec-logtest ossec-makelists ossec-dbd - ossec-integratord wazuh-modulesd wazuh-db
cc -pthread  -Xlinker -rpath -Xlinker "@executable_path/../lib"  os_maild/config.o os_maild/mail_list.o os_maild/maild.o os_maild/os_maild_client.o os_maild/sendcustomemail.o os_maild/sendmail.o libwazuh.a libwazuhext.dylib  -o ossec-maild
Undefined symbols for architecture x86_64:
  "_curl_easy_cleanup", referenced from:
      _wurl_get in libwazuh.a(url.o)
```

**Comment by vikman90** [comment]
Fixed: https://github.com/wazuh/wazuh/commit/ede3207021eb967d677a1a516fde656cd721f583
