### ISSUE TITLE
Bug: info line in rule not overwritten by overwrite="yes" directive in rule def.

### ISSUE THREAD

**Issue by gjahchan** [wazuh/wazuh#584]
The line:
`<info type="text">Whatever text.</info>` does not get overwritten if a rule is overwritten by one that does _not_ include the `<info "text">Whatever text.</info>`. When the rule is triggered, the event reported will include the info text that was in the original rule, even though no info text is in the replacement rule.

Conversely, if the original rule did _not_ include a line `<info type="text">Whatever text.</info>`  and the replacement rule does, the info text will _not_ be reported in the event when the replacement rule is triggered.

This _undesirable_ behavior is consistent and repeatable.

**Comment by vikman90** [comment]
Hi @gjahchan,

I've managed to reproduce and fix this issue. It's committed (https://github.com/wazuh/wazuh/commit/9c7b985faa40e414f73c5f6aff37f39673b07f48) in the branch [3.2-dev](https://github.com/wazuh/wazuh/tree/3.2-dev) for the next patch version, likely 3.2.3.

Thank you very much for reporting this issue.
Best regards.

**Comment by TJOSERAFAEL** [comment]
Hi @gjahchan ,

you need to clone that branch and compile it by yourself.
For example on a terminal run: 
```
$ git clone -b 3.2-dev https://github.com/wazuh/wazuh
$ cd wazuh/src
# make TARGET=server
# ../install.sh

```
This will compile the source code and install the manager on your machine.

Best regards
