### ISSUE TITLE
Unable to decode aruba switch logs

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#5842]
Dear team,

i am not able to decode aruba switch logs. the logs are in the followingformat 

 Jun 27 23:16:07 xx.xx.xx.xx 00435 ports:  port A12 is Blocked by STP
 Jan 14 09:15:26 xx.xx.xx.xx 05220 activate:  Unable to resolve the Activate server address device.arubanetworks.com.

the issue is that before jun,there is a space which i am not able to prematch.

i am new to wazuh and i am not that good in decoding.can somebody please help...!!
Thanks in advance

**Comment by AdriiiPRodri** [comment]
Hi @VisakhMV-Coder,

For the cases in which we add new rules and decoders, we can check if they are really well formed with the [ossec-logtest](https://documentation.wazuh.com/3.13/user-manual/ruleset/testing.html) tool. In this case, it is possible that there is some kind of problem with the decoder associated with Aruba's switchs. 

This only happens before June, Could you show us the decoder and the rules of your system associated with the Aruba switches? In this way we can check why it does not match with the ossec-logtest tool and then correct it.

I look forward to your response, if you have any questions about the process, please don't hesitate to ask.

Best regards,
Adri

**Comment by VisakhMV-Coder** [comment]
the ticket can be closed,as we made new decoder and rules.thank you all for your support

**Comment by branchnetconsulting** [comment]
Jacob,

If you are at liberty to do so, I'd sure appreciate it if you would share what Aruba decoders and rules you've been able to come up with.  Maybe they could help us get some Wazuh Aruba coverage in place for the wider Wazuh community.  

Kevin

**Comment by BrunoWazuh** [comment]
I have this problem to collect the logs from the ARUBA switch.
If you found any way to collect these type of logs, help me.
