### ISSUE TITLE
Duplicated syscollector process, error: couldn't delete PID file

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#5844]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Modulesd | Agent | Packages | Ubuntu/Debian/¿Others? |

Hello Team, we've detected a weird behavior in modulesd during our installation testing. occurs only one out of several executions so we have concluded that it depends on a race condition. From now, we've detected it on Ubuntu bionic and Debian Stretch.

![image](https://user-images.githubusercontent.com/15269938/91527386-fbfd2100-e905-11ea-888c-1e153c7b4c54.png)

The agent report an error saying it `couldn't delete PID file`, and, in the logs, we could see a duplicated syscollector process stopping. That could be the cause of such an error.

We're working to reproduce the problem and solve it.

Best regards.

**Comment by grg121** [comment]
Hello Team, we've managed to reproduce the failure with modulesd on debugging 2, 

```
09:27:14  2020/08/28 07:26:31 wazuh-modulesd:syscollector[1475] syscollector_common.c:219 at wm_sys_cleanup(): INFO: Module finished.
09:27:14  2020/08/28 07:26:31 wazuh-modulesd:syscollector[1475] syscollector_common.c:219 at wm_sys_cleanup(): INFO: Module finished.
09:27:14  2020/08/28 07:26:31 wazuh-modulesd[1475] main.c:200 at wm_cleanup(): ERROR: Couldn't delete PID file.
```

We've found that the PID of the duplicated process is the same. That means there is no duplicated file but a double execution of the cleanup function by the same process.

We're working on a fix.

## statistical information about the problem

error in ubuntu: 0/13 builds
error in centos 0/13 builds
error in Debian 1/13 builds

error on tests: 1/39

We will continue launching tests so we could extract more information.

Best regards.

**Comment by grg121** [comment]
Hello Team, we've deployed a new branch with a fix: `fix-modulesd-exit` and have made some packages from it. We're launching test jut for Debian buster trying to reproduce the error again.

Best regards.

**Comment by Dwordcito** [comment]
This issue is closed, since there were substantial changes in the implementation of syscollector, if it were to be reproduced again, we will reopen the issue.
