### ISSUE TITLE
Collect Log Windows - SQL SERVER 2017

### ISSUE THREAD

**Issue by fvaz1906** [wazuh/wazuh#5848]
Hi, guys

I'm having trouble collecting the windows eventchannel logs, referring to SQLSERVER.

I use centralized configuration and created a group only for the SQLSERVER2017 database, I activated the bank's audit logs, in which within the eventviewer I can perform the visualization.

![image](https://user-images.githubusercontent.com/30749569/91561358-d6761480-e911-11ea-83d8-8244fe6e5240.png)

I created an error.log file and copied the logs within ERRORLOG to error.log to perform the collection via syslog, it worked, but SQLSERVER does not generate the file with an extension, which makes collection difficult.

![image](https://user-images.githubusercontent.com/30749569/91561977-cd397780-e912-11ea-85c3-7c393029a0e2.png)

the logs are in the eventviewer, but with the configuration I made above, the agent does not collect.

please can you help me?

**Comment by chemamartinez** [comment]
Hi @fvaz1906,

I'll try to help you with this issue.

If I understood, when you create the log file manually in the agent, the configuration is applied correctly and the logs are collected by the Wazuh agent, isn't it?

However, the goal is to monitor the log file created by the SQL server itself, and it creates the file with no extension. In that case, the agent configuration could be replaced by:

```xml
<localfile>
  <location>C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Log\error*</location>
  <log_format>syslog</log_format>
</localfile>
```

The `*` wildcard allows the module to monitor all files of that location that starts with `error`, no matter the extension. https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/localfile.html#location

On the other hand, you could use the `eventchannel` log format to read the events directly from the EventChannel service. You can see the source channel of the events in one of them, and set a configuration like:

```xml
<localfile>
  <location>Microsoft SQL Server/Operational</location>
  <log_format>eventchannel</log_format>
</localfile>
```

Hope it helps.

Best regards,
Chema.

**Comment by fvaz1906** [comment]
Hello Friend,

thanks for the help ... however I made the settings as explained, but it didn't solve the problem.

1. log collection via syslog with the * wildcard did not work.

2. there is no channel in windows with SQL Server, I did a search in the root of the files and I didn't find it.

**Comment by chemamartinez** [comment]
Hi again,

Regarding the first point, can you paste here the configuration you are applying to collect the log files using the wildcards? In addition, to find the cause of the issue it would be useful to read the Logcollector logs when starting the agent.

The log file is located at `C:\Program Files (x86)\ossec-agent\ossec.log` by default. Please, review that file looking for any suspicious message from the Logcollector service. You can also paste here the log file to help you with that.

On the other hand, if you are able to see SQL Server events in the Event Viewer service, they have to be available from the Event Channel service. Probably, they come from any other channel such as `Application`. I could identify the channel if you copy an event in XML from the Event Viewer and paste it here.

Best regards,
Chema.
