### ISSUE TITLE
Why the whole client.keys will be empty after restarting the wazuh-manager

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#585]
Hello, I was confused about the client.keys.
In my cluster( #573 ),  I found my clients of cluster will empty the client.keys after restarting.

I modified the ossec.conf of client and manually restarted it.  Even one line no left.

There is my ossec.conf of client in the wazuh about client.keys. (The auth part)

```
<!-- Configuration for ossec-authd
    To enable this service, run:
    ossec-control enable auth
  -->
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>yes</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>yes</use_password>
    <limit_maxagents>yes</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>yes</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>

```

Is there anything else will cause this situation?

**Comment by vikman90** [comment]
Hi @iAklis,

This is due to a conflict between your client nodes. Authd is supposed to run in the master node only. The _client.keys_ is synchronized in the master → client direction only. Please enable Authd in the master node and disable it in the clients.

Please let us know if this solves this issue. 

Best regards.

**Comment by vikman90** [comment]
Hi @iAklis,

I'm sorry, I did not understand your last sentence. Did it finally work?

The idea is that Authd is enabled on the master node, so it should populate the _client.keys_ with the keys provisioned to the agents that requested a key.

Could you confirm that Authd is populating the _client.keys_ properly in the master node?

Then, the cluster will transfer the agent information (_client.keys_) from the master node to the client nodes. The content of the _client.keys_ in the client nodes should match the _client.keys_ on the master node.

Maybe you need to restart your client node and also the master node.

Could you clarify where you found an empty _client.keys_ please?

Best regards.

**Comment by iAklis** [comment]
Hi @vikman90 ,

Yes, it finally work!  Thank you.

-----

But I want to know more about it.  
In my cluster, I confirm that all nodes were registered on the master node.

Master:
```
sh-4.2# cat client.keys  | wc -l
13828
```
Client:
```
sh-4.2# cat client.keys  | wc -l
13828
```

Best regards,
Aklis Chen
Which process will empty my client.keys? After I changed the ossec.conf for disable authd in the client node, I restarted the wazuh-manager(client) immediately. But it still made my client.keys empty. I was confused because he wazuh-authd process didn't start.  

I manaully push the client.keys from master by `./cluster_control -f` and restarted the wazuh-manager(client) immediately again.  It worked!

**Comment by vikman90** [comment]
Hi @iAklis,

Maybe the issue was due to Authd running —previously— in a client node. Authd is the process that modifies the content of the _client.keys_ in the master node. When it starts, It caches the list of agents in memory for performance reasons. When agents are registered or removed, it updates the _client.keys_ file but it never reloads it.

I think that Authd competed with the cluster in client mode. When you stopped Authd, it dumped its —empty— list of agents on the _client.keys_, that's why you were seeing it empty but the next time, when only the cluster was running, it worked properly.

Let me close the issue. If this does not resolve your question, please let me know.
Best regards.

**Comment by Ekene95** [comment]
Hi @vikman90,

I have a similar error when trying to enroll an agent automatically.

# ./agent-auth -d -m 10.104.0.47 -p 1515
2023/06/10 21:58:38 agent-auth[29651] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
2023/06/10 21:58:38 agent-auth[29651] main-client.c:248 at main(): DEBUG: Wazuh home directory: /var/ossec
2023/06/10 21:58:38 agent-auth[29651] main-client.c:291 at main(): INFO: Started (pid: 29651).
2023/06/10 21:58:38 agent-auth[29651] enrollment_op.c:122 at w_enrollment_request_key(): INFO: Requesting a key from server: 10.104.0.47
2023/06/10 21:58:38 agent-auth[29651] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2023/06/10 21:58:38 agent-auth[29651] enrollment_op.c:222 at w_enrollment_connect(): ERROR: (1208): Unable to connect to enrollment service at '[10.104.0.47]:1515'

Details of my setup:
One master node on Ubuntu 18.04
One worker node on Ubuntu 18.04
1 agent running on Oracle Linux 8
1 agent running on Ubuntu 18.04

I have disabled <auth> in my worker node.

I have also followed the suggestions and several other suggestions found here and else but no luck. I even changed the enrollment port to 9999 from 1515 in all ossec.conf file but no luck either.
I tested connection to port 1515 on my Master node using #nc -zv <ip address> 1515 and I got a successful output.

I am stuck now. Kindly assist.
