### ISSUE TITLE
Active response CMD script not working

### ISSUE THREAD

**Issue by Michealpool** [wazuh/wazuh#5858]
Hello,

i am running below CMD script by using active response to upload a file from agent to server. Active response executed but no result.

=======================
cmd.exe /c echo y | pscp -pw wazuh -batch  unique.txt root@10.10.10.126:/tmp
======================= 
 
When i run the script from agent manually by using CMD, it successfully upload file to server. When execute script by using active response it does noting. below message appears

Wazuh agent_control: Running active response 'upload-cmd600' on: 003
========================================================
There is no error in logs. All configuration are perfect. other windows script by using active  response like blocking IPs, Copy file locally working perfect. 
Kindly guide, i will be grateful.

**Comment by Michealpool** [comment]
one thing more. pscp.exe exist inside /activeresponse/bin directory. when i run the script manually its execute perfectly, but do not why not working with active response.

**Comment by 0xN3utr0n** [comment]
Hi @Michealpool ,

I've been trying by all possible means to automate  `pscp's` execution with `active-response`, but with no avail. Right now Wazuh uses the `CreateProcess` function from the WIndows API to run the specified scripts/executables, and as far as we know, there shouldn't be any kind of issues. It looks like it's not a Wazuh exclusive issue, as it can be seen [here](https://stackoverflow.com/questions/4368917/running-a-external-program-pscp-from-a-windows-service-doesnt-works). My best guess is that `pscp` incorporates some type of security mechanism that forbids it's execution under certain conditions. 

As a side note, from a security perspective I highly advise against the idea of connecting an agent to a manager via ssh. Should an attacker compromise the agent, he would have access to the manager's root credentials; meaning, it would instantly be game-over.

A more secure and feasible alternative could be to have a lightweight `SFTP` or `HTTPS` server running on the manager. 

Kind regards,
Fernando
