### ISSUE TITLE
Wazuh-alerts growing mapping due to AWS-S3 module

### ISSUE THREAD

**Issue by Phandora** [wazuh/wazuh#5859]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
|3.13.0-31306|Manager|Packages|Ubuntu 16.04.6 LTS|

Hi!

When using the **AWS-S3 module** to monitor AWS, `wazuh-alerts` index pattern fields grow depending on e.g. the attached instances, buckets, or applications, as the keys change based on these values.

This leads to a **continuously growing mapping** which causes quirky searches since there is a memory cost to every field. It affects the Elasticsearch performance significantly.

Here I show some of the conflictive fields, it looks like they came from **AWS Config**:

> The fields have been modified using `<>` for confidential reasons.

```
data.aws.configuration.AWS:Application.Content.<service>.Architecture
data.aws.configuration.AWS:Application.Content.<service>.Name
data.aws.configuration.AWS:Application.Content.<service>.PackageId
data.aws.configuration.AWS:Application.Content.<service>.Publisher
data.aws.configuration.AWS:Application.Content.<service>.Version

data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.ComplianceType
data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.DocumentName
data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.DocumentVersion
data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.Id
data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.Severity
data.aws.configuration.AWS:ComplianceItem.Content.Association.<id>.Status

data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.AgentType
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.AgentVersion
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.ComputerName
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.InstanceId
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.IpAddress
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.PlatformName
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.PlatformType
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.PlatformVersion
data.aws.configuration.AWS:InstanceInformation.Content.<instance-id>.ResourceType

data.aws.configuration.AWS:WindowsUpdate.Content.<id>.Description
data.aws.configuration.AWS:WindowsUpdate.Content.<id>.HotFixId
data.aws.configuration.AWS:WindowsUpdate.Content.<id>.InstalledBy
data.aws.configuration.AWS:WindowsUpdate.Content.<id>.InstalledTime

data.aws.supplementaryConfiguration.BucketNotificationConfiguration.configurations.<id>.events
data.aws.supplementaryConfiguration.BucketNotificationConfiguration.configurations.<id>.filter.s3KeyFilter.filterRules.name
data.aws.supplementaryConfiguration.BucketNotificationConfiguration.configurations.<id>.filter.s3KeyFilter.filterRules.value
data.aws.supplementaryConfiguration.BucketNotificationConfiguration.configurations.<id>.topicARN
data.aws.supplementaryConfiguration.BucketNotificationConfiguration.configurations.<id>.type

data.aws.supplementaryConfiguration.BucketReplicationConfiguration.rules.<id>.destinationConfig.bucketARN
data.aws.supplementaryConfiguration.BucketReplicationConfiguration.rules.<id>.status
```

Best regards,
Mayte Ariza

**Comment by CarlosRS9** [comment]
# Status Update

The problems seem to be in the decoder instead of the AWS-S3 module. We are currently working on this and performing some tests to fully understand the cause and consequences of this issue.

**Comment by CarlosRS9** [comment]
## Status Update

Here is a quick recap of the proposed solutions and the current status of this issue.

Three solutions were proposed to solve this problem:

1. Pre-filter the alerts from the Wodle.

2. Update the decoder to generate alerts that does not use variables such as IDs and the service type for the field names.

3. Change the concept of the Wodle from an Alert-kind to an Inventory-kind. 

### Prefiltering the alerts with the module

This solution is not feasible as the module does not perform any action that could affect the content of the alerts. It just takes a log in raw and sends it to `Analysisd` to be processed properly by the decoders and rules.

### Changing the concept of the Wodle

This solution implies a total rework of the module and also involves the following technical challenges:

- In case we want to handle those alerts as an inventory-kind it will be necessary to store the information in a database. 
- It would be necessary to decide in which database it would be stored: `global.db` or a new one. 
- We should measure and considere the expected size of the data stored in that database first.
- Several problems would raise if the module can be executed in agents.
- It would be necessary to see how to handle this approach when having a cluster enabled. The database information should be shared between nodes?

### Updating the existant decoder

This solution consist in updating the decoder in charge of handling this kind of alerts to process the fields present in the log in a more optimal way. No fields with variables in the name, such as IDs, would be generated.

Cloud team provided us with an event generated by wazuh from a problematic log. From this we have concluded that it would be feasible to modify the corresponding decoder to generate fields whose names do not contain variables such as the ID. Unfortunately, it is not possible to advance further with this solution until we have a real example of a log that has not yet been processed by `analysisd`, that is, before going through the corresponding decoder.

We are currently waiting to get this log to continue. It will be provided to us soon.

**Comment by CarlosRS9** [comment]
# Status Update

It was not possible to obtain from the client the logs we needed to perform the relevant tests. We proceeded to use logs created manually from the events left to us by Analysisd instead.

After going deeper into the proposed decoders solution, we realized the reasons we were relying on to discarded the option of pre-filtering the alerts within the module before sending them to Analysisd were not correct. It can be done and it would be a more viable solution than the decoder. However, there is still one inconvenient related to this solution. The idea was to simply remove the <id> from the fileds but according to the Cloud team, they realised the same alert could refer to several different `<id>`, so it would not be a valid solution.

## Pending

We need discuss again with the Cloud team to determine to what extend its true that the same alert can refer to several IDs and in that case we need to come up with a way to get around this.

**Comment by CarlosRS9** [comment]
# Status Update

We have discussed the issue again with Cloud team and since it is possible that an AWS Config alert references more than one instance ID we have decided to opt for the removal of all fields that could cause this issue. This implis that if we have an alert such as the following one:

```
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.ComputerName": "name",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.InstanceId": "<i-AAAAAAAAAAAAA>",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.IpAddress": "<ip>",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.AgentType": "amazon-ssm-agent",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.ResourceType": "EC2Instance",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.AgentVersion": "<version>",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.PlatformVersion": "<version>",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.PlatformName": "<platform>",
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>.PlatformType": "Windows"

configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.ComputerName": "name",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.InstanceId": "<i-BBBBBBBBBBBBB>",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.IpAddress": "<ip>",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.AgentType": "amazon-ssm-agent",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.ResourceType": "EC2Instance",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.AgentVersion": "<version>",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.PlatformVersion": "<version>",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.PlatformName": "<platform>",
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>.PlatformType": "Windows"
```

Having i-AAAAAAAAAAAAA and i-BBBBBBBBBBBBB as instance IDs will produce the following fields after the proposed removal:
```
configuration.AWS:InstanceInformation.Content.<i-AAAAAAAAAAAAA>,
configuration.AWS:InstanceInformation.Content.<i-BBBBBBBBBBBBB>
```

This would limit the information available in the alerts, but would ensure 100% compatibility and avoid the performance and resource issues reported by the client. In the future, the fields to be present could be extended, if necessary. This solution feasible by applying some modifications to our AWS module.

**Comment by CarlosRS9** [comment]
# Status Update

The implementation of the solution to this issue have begun. The development of that solution can be followed in #6537 .
