### ISSUE TITLE
Standardize wdb_sync_agent_info_get response format

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#5893]
|Wazuh version|Component|Install type|
|---|---|---|
|4.0 | Wazuh-DB | Manager |

The response of **wdb_sync_agent_info_get()** should follow the format below:

- Successful query with no pending data: **"ok {PAYLOAD}"**
- Successful query with pending data: **"due {PAYLOAD}"**
- Unsuccesful query: **"err {ERROR MESSAGE}"**

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/5894 was merged.
