### ISSUE TITLE
Kibana dashboard JSON doesn't load properly

### ISSUE THREAD

**Issue by cptcanuck** [wazuh/wazuh#59]
The current JSON file specifies the index to pull data as the literal [ossec-]YYYY.MM.DD, which isn't likely to be the index match.  It's more normal to have ossec-*

File: https://github.com/wazuh/wazuh/blob/1b6de44e9dc70fb056f804ebac58cabd9a357912/extensions/kibana/4.1/kibana-ossecwazuh-dashboards.json

`"searchSourceJSON": "{\"index\":\"[ossec-]YYYY.MM.DD\",\"query\":{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}},\"highlight\":{\"pre_tags\":[\"@kibana-highlighted-field@\"],\"post_tags\":[\"@/kibana-highlighted-field@\"],\"fields\":{\"*\":{}}},\"filter\":[]}"`

If you change the index to 

`"{\"index\":\"ossec-*\"`

It loads properly.

This looks like it's been fixed in the OSCAP dashboards: https://github.com/wazuh/wazuh/blob/1b6de44e9dc70fb056f804ebac58cabd9a357912/extensions/kibana/openscap-dashboards/new_kibana-ossecwazuh-dashboards.json

**Comment by snaow** [comment]
Hi @cptcanuck,

Thanks for the feedback.
The file you are mentioning is applied to Kibana version 4.1, it was a previous configuration we had, currently we have the index pattern set for the same regex you said, which is totally correct.

Kibana dashboards for version 4.5+:
https://github.com/wazuh/wazuh/blob/master/extensions/kibana/kibana-ossecwazuh-dashboards.json#L94

Let me merge your pull request, whatever the version is you are right about using that index pattern.

Thanks again for the feedback.

PS: We are working hard on new Wazuh release, which includes the integration with Elastic Stack 5.0, I hope you can give it a try when ready.

**Comment by q2dg** [comment]
Can this issue be closed already?

**Comment by havidarou** [comment]
Hi @q2dg ,

yes, there's been a lot of development since this.

Closing now.

Thanks,

regards.
