### ISSUE TITLE
Agent Info Inconsistencies

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#590]
I want to know how wazuh cluster manage agents. 

There is a inconsistencies.
```
sh-4.2# ./list_agents -a | wc -l
14194
sh-4.2# ./cluster_control -a | wc -l
7656
sh-4.2# ./agent_control -l | wc -l
13830
sh-4.2# cat ../etc/client.keys | wc -l
13824 
```

Another question newly agents could join the default group automatically after exchange keys with master of cluster. 

I will provide as much as possible to make wazuh great.

Best regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hello @iAklis ,

All cluster information is stored in the master node, the rest of nodes (clients) have only partial information about the whole cluster status. Are you doing the requests on the master node?

Also, the cluster uses the database `/var/ossec/var/db/global.db` to list agents, do a SQL request (using `sqlite`) to check if the database is correctly filled with all agents information (`select count(*) from agent;`).

Regarding your question, the agents join the `default` group when they start reporting to a manager. This is why `agent-groups` files are usually created in client nodes, and then they are sent to the master node.

Thank you so much for your contributions,
Marta

**Comment by iAklis** [comment]
Hi @mgmacias95 ,

Thank you for reply! I have solved the problem according your information. ^_^

I thought it was master who was responsible for distributing agent group. I was wrong.

Best Regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hello @iAklis,

I'm glad your problem was solved. Let me close this issue :).

Best regards,
Marta
