### ISSUE TITLE
No sshd alerts triggered on any Cent OS distrubution (feature request)

### ISSUE THREAD

**Issue by lucanus81** [wazuh/wazuh#5908]
Hi,

while testing active responses on our environment, we discovered that sshd alerts weren't triggered on centOS. 
The test case is pretty simple:
- enable sshd server on the manager's machine
- from any other machine, run root@<manager_ip>, and use a wrong password.

On Ubuntu this is logged into /var/log/auth.log, however in centOS this entry is logged into /var/log/secure.
The problem is that /var/log/secure is not part of the standard Wazuh's ossec.conf configuration.

Once we added:
`   <localfile>
      <log_format>syslog</log_format>
      <location>/var/log/secure</location>
   </localfile>`

any ssd-related alert was correctly generated. Obviously I cannot test any possible centOS distribution, however I think this is something. you might want to consider for a future release (to add /var/log/secure to Wazuh's standard ossec.conf).
The machine I was using is:

[root@localhost alerts]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Thanks,
Luca

**Comment by vicferpoy** [comment]
Hello @lucanus81 ,

You're absolutely right. The `/var/log/secure` path has never been included in the default `ossec.conf`. However, I took a look at the `ossec.conf` from a fresh install with `Wazuh v3.13.1` and I did not find any entry for `/var/log/auth.log` either.

Could you share which version of Wazuh are you using, please?

Regards.

**Comment by lucanus81** [comment]
Hello @vicferpoy,

this is bizarre because if you look at your GIT repository https://github.com/wazuh/wazuh/blob/master/etc/ossec.conf auth.log is there and has always been there for ages. 
We started with Wazuh 3.9.X and right now in production we have wazuh 3.12.

Thanks,
Luca

**Comment by vicferpoy** [comment]
Hello again @lucanus81 ,

I was about to make an update. After further research, I found that these `<localfile>` sections are added on installation when the installer detects that these files exist.

I did not install `openssh-server` beforehand in my testing environment, that is why I could not see that section in my `ossec.conf`. I apologize for that.

To conclude, these extra sections should be added on installation if you have previously installed and enabled your SSH service, but you can manually add them if you have not and it will work fine (as you have personally tested). 

I hope this solves any doubt I could cause with my first response. If you have any other question or request, do not hesitate to ask or open another issue.

Regards,
Víctor

**Comment by lucanus81** [comment]
@vicferpoy,

thanks for your answer. I have verified with the latest version of the agent and you are right! That file was added once sshd is enabled by default. Thanks a lot!
Feel free to close this ticket. 

Luca
