### ISSUE TITLE
Warning message not accurate

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#591]
Hello team

  I have Wazuh Manager 3.2.1 and Wazuh agent 2.1.1. Regarding the following message:

```
[root@wazuh-server ~]# /var/ossec/bin/verify-agent-conf
verify-agent-conf: Verifying [/var/ossec/etc/shared/windows/agent.conf]
2018/05/04 13:56:32 verify-agent-conf: WARNING: The <length> tag is deprecated, please use <queue_size> instead.
verify-agent-conf: OK
```

The Warning message is not correct or at least it's not accurate. The <length> tag is deprecated in 3.2.1 but not in 2.1.1. If a user read the message and change the tag by <queue_size>, the configuration will not have a Warning but it will not work on the agent, because the agent 2.1.1 doesn't recognize the new tag. 

In my opinion we have two options: 

1. Complete the Warning message with the text "deprecated for version newer than 2.1.1" or something like that. 
2. Wazuh agent version detection and adapt the message. Please take into account that other tags could be in the same situation now or in the future versions. 

Thanks. 
Kind regards, , 
Alberto R.

**Comment by TJOSERAFAEL** [comment]
Hi @alberpilot ,

this commit https://github.com/wazuh/wazuh/commit/7aa3e94454cbf66789f0104d306d9095c4cb33c2 adds better description for the warning as you suggest.

Best regards.

**Comment by alberpilot** [comment]
Thanks a lot. This will be useful. 

Best regards, 
Alberto R.
