### ISSUE TITLE
Whodata issue with Windows NFS path

### ISSUE THREAD

**Issue by josegob** [wazuh/wazuh#5912]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1 | Wazuh component | Agent | Packages | Windows |

Hello team,

An user asked in our Slack community (https://wazuh.slack.com/archives/C0A933R8E/p1599121584229100) about an issue auditing who-data in Windows.

He set the following configuration but it is not working properly:

```xml
<syscheck>
  <directories check_all="yes" whodata="yes">\\srv-test\test$</directories> 
  <skip_nfs>no</skip_nfs>
</syscheck>
```

The path is a NFS driver and he only has access to the UNC path.

The error from the `ossec.log` is the following:

```log
run_realtime.c:470 at realtime_adddir(): ERROR: (6619): Unable to add directory to whodata real time monitoring: '\\srv-test\test$'. It will be monitored in Realtime
```

Could you please check it as soon as possible? I tried to reproduce the issue without any luck

**Comment by Molter73** [comment]
I've mounted a NFS client in a Win7 machine and it does not seem possible to add audit policies to the drive, therefore we cannot monitor it in this mode. I tested on an Ubuntu client to check how it would work with auditd, files added/deleted/modified from the local machine do get notified and the user making the changes is properly logged under the `audit` section, however, changes done remotely are not shown.
