### ISSUE TITLE
[Development] Error in macOS ossec log: Cannot get process info for PID X

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#5913]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | modulesd | Agent | Packages | macOS Catalina |

Hello team,

The CICD team has detected during the installation tests that sometimes the following errors are shown in the `ossec.log`

```
wazuh-modulesd:syscollector: ERROR: Cannot get process info for PID 144
```

This is an error that happens occasionally and it would be good to have it investigated. I will try to provide more information in the next few days.

Best regards.

**Comment by Dwordcito** [comment]
Hi @jmv74211 

this issue can be reproduced with 4.2?

Regards

**Comment by Dwordcito** [comment]
Not seen since the issue was written, if you see this error prior to refactor of syscollector, please reopen the issue.
