### ISSUE TITLE
Plugin installation was unsuccessful due to error "Plugin wazuh [7.9.0] is incompatible with Kibana [7.9.1]"

### ISSUE THREAD

**Issue by xirehat** [wazuh/wazuh#5914]
Hello,
I cannot install latest wazuh pluging in kibana7.9.1
Error this is:

```Plugin installation was unsuccessful due to error "Plugin wazuh [7.9.0] is incompatible with Kibana [7.9.1]"```

**Comment by jotacarma90** [comment]
Hello @xirehat 
for compatibility between **Elasticsearch**, **Kibana** and the **Wazuh app** in Kibana, all three must have the same version. I can see that the version of Kibana 7.9.1 is too recent, is not yet ready the Wazuh app plugin with the same version. 

At the moment, the lastest version allowed are 7.9.0 in order for them to work correctly.
You can read the compatibility matrix here in our documentation:
https://documentation.wazuh.com/3.13/installation-guide/compatibility_matrix/index.html?highlight=compatibility#api-and-kibana-app

Sorry for the inconvenience.
Best regards.

**Comment by xirehat** [comment]
@jotacarma90 
When will this issue be fixed?
If it take a long time, It should come back to 7.9.0

**Comment by jotacarma90** [comment]
We have no deadlines for our releases, we always try to raise the product as clean as possible, our apologies. We will do it as soon as possible. You may need the older version of Kibana and Elasticsearch for now.

Thank you for using Wazuh.
Greetings

**Comment by vikman90** [comment]
@xirehat Wazuh App has just been updated for Kibana 7.9.1.

Please follow the documentation to install it: https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/index.html

Let me close this issue. Should you have any questions or troubles please reopen it and let us know.

Best regards.

**Comment by xirehat** [comment]
@vikman90 Thanks a lot.

I tested it and it works properly.
