### ISSUE TITLE
Define communication protocol specifications for wazuh daemons

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#5934]
Hello team,

This issue is part of https://github.com/wazuh/wazuh/issues/5927.

It aims to study, identify and define the design for a communication protocol to be used for Wazuh daemons. We should ensure new designs follow the same structure when communicating.

The new protocol should define the structure and fields of the response, as well as the error when it occurs.

Best regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
# Socket response proposal

We are aiming to standarize every Wazuh socket response. The purpose of it is to be able to parse every response in the same way, enabling a future microservices architecture which would improve scalability and ease future developments.

## Structure

The response must be a JSON type object with the following **required** fields:

- `error`: an **integer** equal or greater than 0.
    This field must be **0** when the response was a __successs__. Otherwise, it must be an actual and unique code error.

- `data`: either a **JSON object** or a **list**. Every module must decide which type of __data__ will return. It must be consistent, ignoring the number of elements.
    This field must contain any useful information that could be parsed. This is why it is expected to be a **JSON object** or a list of these. Every module will have its own __data__ structure. `data` structures which are a list must have its own **error** field since any element could have a different error/exception. The external field `error` must be a general code.

- `message`: an __optional__ **string**.
    It will contain a message with human readable information about the operation status. Although **its value is optional**, this field must be present in the response.


## Examples

### Successful response (JSON data)

```json
{
    "error": 0,
    "data": {
        "id": "016",
        "name": "agent-test-authd",
        "ip": "any",
        "key": "5f806e70652ca72b2e65f679f159d813a312c5f8b057128ef9ce212f679309a7"
    },
    "message": "Successful"
}
```

### Error response

```json
{
    "error": 1045,
    "data": {
        "id": "016"
    },
    "message": "Error trying to register an agent"
}
```

### Successful response (data list)

```json
{
    "error": 0,
    "data": [
        {
            "agent": 1,
            "task_id": 3,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Updated",
            "create_time": "2020/09/03 13:56:04",
            "update_time": "2020/09/03 13:57:14"
        },
        {
            "agent": 3,
            "task_id": 5,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Updated",
            "create_time": "2020/09/03 13:58:04",
            "update_time": "2020/09/03 13:59:14"
        }
    ],
    "message": "Successful upgrade"
}
```

### Partially successful response (data list)

Important to note that even though there was an agent that failed to upgrade, the field `error` is still 0.

```json
{
    "error": 0,
    "data": [
        {
            "agent": 1,
            "task_id": 3,
            "error": 0,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Updated",
            "create_time": "2020/09/03 13:56:04",
            "update_time": "2020/09/03 13:57:14"
        },
        {
            "agent": 3,
            "task_id": 5,
            "error": 1020,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Failed",
            "create_time": "2020/09/03 13:58:04",
            "update_time": "2020/09/03 13:59:14"
        }
    ],
    "message": "Some agents were not upgraded"
}
```

### Error response (data list)

The external field `error` here must be a general exception. In `data` lists, every element within must have its own exception.

```json
{
    "error": 1015,
    "data": [
        {
            "agent": 1,
            "task_id": 3,
            "error": 1035,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Failed",
            "create_time": "2020/09/03 13:56:04",
            "update_time": "2020/09/03 13:57:14"
        },
        {
            "agent": 3,
            "task_id": 5,
            "error": 1020,
            "module": "upgrade_module",
            "command": "upgrade",
            "status": "Failed",
            "create_time": "2020/09/03 13:58:04",
            "update_time": "2020/09/03 13:59:14"
        }
    ],
    "message": "Some agents were not upgraded"
}
```

**Comment by vicferpoy** [comment]
# Socket request proposal

## Structure

The request must be a JSON type object with the following fields:

- `payload`: a **JSON object**.
    This field will contain the real message to be processed by the socket.

- `metadata`: a **JSON object** which specific information.
    This field could have useful information such as the current protocol version or where is this request coming form.


This structure allows scalability since every daemon will have its own `payload` and the `metadata` field can have additions any time.


## Examples

### Standard request

```json
{
    "payload": {"remove_session":"372e5eac"},
    "metadata": {
        "version": "v1.0",
        "module": "logtest"
    }
}
```

### No metadata request (metadata does not affect the result)

```json
{
    "payload": {"event": "Mar  8 22:39:13 ip-10-0-0-10 ss56hd123[2742]: Accepted publickey for root from 73.189.131.56 port 57516","log_format": "syslog","location": "master->/var/log/syslog"},
    "metadata": {}
}
```

**Comment by AdriiiPRodri** [comment]
## Long-term message system proposal

![wazuh-broker (1)](https://user-images.githubusercontent.com/15522808/92400357-19af5f00-f12c-11ea-8fde-48e1bc7fcf74.png)

This scheme is based on the communication protocol [AMQP](https://www.amqp.org/). We want to create a standard protocol of interoperability between all Wazuh daemons, the Wazuh Framework and the CLI tools. To achieve this, we must create a new service "**Message_broker**", which will be responsible for storing all messages from Wazuh.

Each Wazuh daemon will have one consuming and one producing thread. The producer thread will be in charge of sending messages to our Message_broker. Once the message is sent, the target daemon will consume the message through its consumer thread, which will be listening the queue status of the Message_broker daemon. Once the message is consumed, it will perform the corresponding task and eventually send the message to the Message_broker. Finally, the daemon that initiated this operation will consume the message from the queue of our Message_broker.

To do all this, the structure of the messages could be as follows:
```json
{
  "id": "ProducerName-INTEGER",
  "from": "ProducerName",
  "to": "ConsumerName",
  "message": {"..."}
}
```

With our "**id**" key, which has to be unique (it can be an autoincremental value), each daemon will be able to control which message corresponds to which the task sent. On the other hand, the daemons will only consume the messages that are intended for them. This will be done by checking the "**to**" key. Once the target daemon performs the task, it will send a new message where now "**from**" will be its own name and "**to**" the new target daemon (the one that started the request or other).

In addition, the Framework and the CLI tools will communicate with Wazuh's core through this broker. This way, we will have a single entry point and a single point where all the messages sent within Wazuh are concentrated.
