### ISSUE TITLE
MAXAGENTS is not work

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#594]
Hello Teams,

I have changed the optional MAXAGENTS accroding the issue #223 

```
wazuh# make -C src clean
wazuh# make -C src TARGET=server MAXAGENTS=100000
wazuh# ./install.sh
```
Recompiled it and replace the `wazuh-modulesd` , `ossec-remoted` and `ossec-authd` with new ones.

But there are some ERROR like this:
 
```
2018/05/07 14:36:30 wazuh-modulesd: ERROR: (4110): Maximum number of agents '7998' reached.
2018/05/07 14:36:31 ossec-remoted: INFO: (4111): Maximum number of agents allowed: '100000'.
```

```
2018/05/07 17:28:44 ossec-remoted: DEBUG: No previous counter available for 'oneagent.com'.
2018/05/07 17:28:44 ossec-remoted: DEBUG: Assigning counter for agent oneagent.com: '0:0'.
2018/05/07 17:28:44 ossec-remoted: ERROR: Unable to open agent file. errno: 24
2018/05/07 17:28:44 ossec-remoted: CRITICAL: (1103): Could not open file '/queue/rids/18262' due to [(24)-(Too many open files)].
```

Best Regards,
Aklis Chen

**Comment by TJOSERAFAEL** [comment]
Hi @iAklis ,

the steps you followed are right. Can you please try to do the same but on a clean installation?. 

Best regards.

**Comment by iAklis** [comment]
Hi, @TJOSERAFAEL ,

I have solved it. 
I found  `rlimit_nofile`  which limit the maximum number of file descriptor that Remoted can open and changed it.
It works.

Best Regards,
Aklis Chen

**Comment by iAklis** [comment]
#624
