### ISSUE TITLE
[WPK] Add the upgrade logic in the upgrade module.

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#5949]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.1 | wazuh-modulesd | Manager |

The upgrade procedure on the agent side is performed by `execd`, which receives the commands from the agent and executes them.

This procedure should be performed by the upgrade module:

- Remoted should be able to send commands to the agent's upgrade module, which will receive them in the upgrade socket.

- The agent will validate the incomming messages.

  - If the message is OK, it should execute the command and send a response to the manager with the result of the command.

  - If the message is wrong, it should send an error response to the manager.

- Old mechanism should be mantained for legacy upgrades.

**Comment by nicolaspapp** [comment]
`<ca_verification>` will be moved from execd to `agent-upgrade` module.
Default behaviour will be kept
Example:
```
<agent-upgrade>
    <ca_verification>
      <enabled>yes</enabled>
      <ca_store>/var/ossec/etc/custom_wpk.pem</ca_store>
    </ca_verification>
  </agent-upgrade>
```
Will set custom_wpk.pem in the store

```
<agent-upgrade>
    <ca_verification>
      <enabled>no</enabled>
    </ca_verification>
  </agent-upgrade>
```
Will disable ca_verification

```
<agent-upgrade>
  </agent-upgrade>
```
Will set ca_store to default value: `/var/ossec/etc/wpk_root.pem`
