### ISSUE TITLE
File changes without realtime syscheck

### ISSUE THREAD

**Issue by farhanorderlogix** [wazuh/wazuh#596]
I have report changes set to yes in the directories check for any files modification. I cannot keep realtime check turned on because of the following issue:

https://github.com/wazuh/wazuh/issues/580

Can i still get alert of file modification / checksum changes? If yes what is the configuration on agent / server i need?

<directories check_all="yes">D:\apps\app\www\training\</directories>

**Comment by mjflve** [comment]
Hi @farhanorderlogix,

Yes you can still use the report_changes and check_* options, for example:

`
<directories check_all="yes" report_changes="yes">D:\apps\app\www\training</directories>
`

With the above, you will still be getting alerts for file changes and their diff on every schedule scan, this configuration should be set on the ossec.conf of the agents or can be deploy from the manager via [centralized configuration](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html). Be aware that the report_changes are limited to text files at this time.

In addition, you can use the [frequency ](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#frequency) syscheck setting to change how syscheck schedule the scans.

I hope it helps.

Best Regards,

**Comment by farhanorderlogix** [comment]
Thanks, When you say it is limited to text files at this time, .php or aspx extension also has text based files so it will be able report those change but dll files changes will be ignored. Please correct me if i am wrong.

**Comment by mjflve** [comment]
Hi @farhanorderlogix 

The `report_changes ` is to get what part of the content of a text file changed, will work with text files, not for binaries. But, with the `check_all ` you will still get alerts on file changes over checksum, date, ownership, among others no matter what the file type is.

Please take a look at here: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#directories

I hope it helps.
