### ISSUE TITLE
Wazuh manager config export

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#5997]
Hi guys,
is there a way to export and then import the wazuh configuration - groups, custom rules etc somehow ?
In my case i want to have the wazuh-manager in docker, but when i upgrade to new version and build new container i will lose everything...

**Comment by davidjiglesias** [comment]
Hello @a108a108,

There is not a specific way to do so, but you can achieve it. You would have to copy these files/folders into a backup and restore afer upgrading with a new container, please, remember you have to configure the same original permissions and owner/groups for the files and folders.

_`Agent information`_
COPY /var/ossec/etc/client.keys      
COPY /var/ossec/queue/agent-groups  
COPY /var/ossec/queue/agent-info     
COPY /var/ossec/queue/agents-timestamp 

_`Agent groups information`_
COPY /var/ossec/etc/shared

_`Ruleset custom`_
COPY /var/ossec/etc/decoders
COPY /var/ossec/etc/rules

_`Alerts`_
COPY /var/ossec/logs/alerts

Those are the importante files that you should backup and restore depending on your needs.

I hope this helps. 

Regards,

David J. Iglesias

**Comment by a108a108** [comment]
Hi @davidjiglesias,

Thank you!
