### ISSUE TITLE
Time/date rule filters

### ISSUE THREAD

**Issue by hitman28594** [wazuh/wazuh#6008]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

When creating rules, it is not possible to use regex for patterns which are in predecoded fields, such as time stamps.  

Use case: 
I want to whitelist system updates being run on the 3rd of every month. 

There is no rule option for day of month, nor one for things like “first Monday of month”,  “last weekday of month” etc. 

Also, The current rule options don’t allow me to use regex to do a pattern match because the time/date are predecoded wazuh fields.

**Comment by AdriiiPRodri** [comment]
Hi hitman28594,

After several tests with a new decoder and rules, it is currently not possible to perform. As you say, timestamps are a pre-decoded field. We will investigate this problem to be able to give a solution. We would need to use a regular expression similar to this to get updates made on the third day of each month ignored:

`^(?!\d\d\d\d-\d\d-03)\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d status`

Currently it is not possible to modify Wazuh's pre-coding in a simple and immediate way. It would be necessary to modify the source code. We will communicate this problem to the corresponding team and try to solve it as soon as possible.

If you have any other doubt, please do not hesitate to ask.

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
We have been testing and can provisionally use the following decoder to capture the logs belonging to the 3rd day of each month:
### Decoder
```xml
<decoder name="Upgrade-3">
  <parent>dpkg-decoder</parent>
  <regex>^(\d\d\d\d-\d\d-03) \d\d:\d\d:\d\d status|</regex>
  <order>cdate</order>
</decoder>
```
### Rule
```xml
<group name="test">
    <rule id="10000" level="1">
        <if_sid>2900</if_sid>
        <field name="cdate">\d\d\d\d-\d\d-03</field>
        <description>Installation on  3rd</description>
    </rule>
</group>
```
We choose a value that does not generate alerts, such as value 1 (Defautl value 3: https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/alerts.html#log-alert-level). This way, when our decoder matches the log, the alert will not be generated.

### Logtest on the 3rd:
```
2020/09/14 11:45:21 ossec-testrule: INFO: Started (pid: 18108).
ossec-testrule: Type one log per line.
2017-08-03 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3
**Phase 1: Completed pre-decoding.
       full event: '2017-08-03 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '2017-08-03 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3'
**Phase 2: Completed decoding.
       decoder: 'dpkg-decoder'
       cdate: '2017-08-03'
**Phase 3: Completed filtering (rules).
       Rule id: '10000'
       Level: '1'
       Description: 'Installation on 3rd'
```

### Installation on another day:
```
2017-08-21 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3
**Phase 1: Completed pre-decoding.
       full event: '2017-08-21 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '2017-08-21 11:44:43 status installed libaugeas0:amd64 1.2.0-0ubuntu1.3'
**Phase 2: Completed decoding.
       decoder: 'dpkg-decoder'
       cdate: '2017-08-21'
**Phase 3: Completed filtering (rules).
       Rule id: '2900'
       Level: '0'
       Description: 'Dpkg (Debian Package) log.'
```

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity

**Comment by hitman28594** [comment]
Hello Andriii,

The provisional fix you recommended works fine for any logs where the timestamp field is decoded in “phase 2” and is not a “pre-decoded” field. 

This issue I raised only affects events where the timestamp is a “pre-decoded” in “phase 1” of analysisd processing. 

We can NOT apply regex filters using any of the “pre-decoded” field in “phase 1”. We can only use regex for whatever is in the “log:” section of “phase 1”.
