### ISSUE TITLE
Compiling using newest clang/gcc produces error dues to -fno-common (FreeBSD 13.0 example)

### ISSUE THREAD

**Issue by fzipi** [wazuh/wazuh#6014]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1_1 | Wazuh package | Agent | Packages | FreeBSD 13.0 |

Compiling using newest clang/gcc produces error dues to `-fno-common` being the default (see https://www.gnu.org/software/gcc/gcc-10/changes.html).

```
root@wazuh:/usr/ports/security/wazuh-agent # make
===>  Building for wazuh-agent-3.13.1_1
gmake[2]: Entering directory '/usr/ports/security/wazuh-agent/work/wazuh-3.13.1/src'
gmake ossec-agentd agent-auth ossec-logcollector ossec-syscheckd ossec-execd manage_agents wazuh-modulesd
gmake[3]: Entering directory '/usr/ports/security/wazuh-agent/work/wazuh-3.13.1/src'
    CC ossec-agentd
ld: error: duplicate symbol: rotate_log
>>> defined at agentd.c
>>>            client-agent/agentd.o:(rotate_log)
>>> defined at config.c
>>>            client-agent/config.o:(.bss+0x14)

ld: error: duplicate symbol: agent_debug_level
>>> defined at config.c
>>>            client-agent/config.o:(agent_debug_level)
>>> defined at main.c
>>>            client-agent/main.o:(.bss+0x0)

ld: error: duplicate symbol: agt
>>> defined at config.c
>>>            client-agent/config.o:(agt)
>>> defined at msgs.c
>>>            msgs.o:(.bss+0x38) in archive libwazuh.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[3]: *** [Makefile:1266: ossec-agentd] Error 1
gmake[3]: Leaving directory '/usr/ports/security/wazuh-agent/work/wazuh-3.13.1/src'
gmake[2]: *** [Makefile:609: agent] Error 2
gmake[2]: Leaving directory '/usr/ports/security/wazuh-agent/work/wazuh-3.13.1/src'
*** Error code 2

Stop.
make[1]: stopped in /usr/ports/security/wazuh-agent
```
Clang version:
```
root@wazuh:/usr/ports/security/wazuh-agent # cc --version
FreeBSD clang version 11.0.0 (git@github.com:llvm/llvm-project.git llvmorg-11.0.0-rc2-0-g414f32a9e86)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by pereyra-m** [comment]
Hello @fzipi !

Thank you for your detailed report, I can confirm you are right. The new GCC version is causing conflicts with the global variables. We'll fix this as soon as we can.

In the meantime, are you compiling the Wazuh Agent for any particular reason? 
You can perform an installation from packages, selecting your OS form [installing-wazuh-agent](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/index.html).

But if the installation from sources is mandatory, you should configure an alternative version of GCC to compile Wazuh.

We'll keep this issue updated about the problem.
Have a nice day!
Regards.

**Comment by fzipi** [comment]
Hey @pereyra-m ! Yes, I'm compiling it for FreeBSD :)

BTW, you should add the install for in: mostly `pkg install wazuh-agent` ;)

**Comment by pereyra-m** [comment]
Hello again!

I apologize about FreeBSD, it isn't officially supported.
But the good news are that this issue was already reported in #5104 and fixed in this PR [5119](https://github.com/wazuh/wazuh/pull/5119). You can try the `master` branch, it has the recent updates for `4.0`.

Please, tell me how did it go!
Regards.

**Comment by mimugmail** [comment]
Hi,

as there are too many files involved it's better to wait for 3.14 instead of backporting the patches via FreeBSD patches. 
As only FreeBSD 13 is affected it' worth to wait, what to do you think @fzipi ?

**Comment by pereyra-m** [comment]
Hello again!

As @mimugmail says, the `master` branch has a lot of new changes in **v4.0**. It will be released as soon as possible.
The only option in the meantime is to manually copy the changes merged in the PR mentioned above, but it may not be that simple.

Regards.

**Comment by fzipi** [comment]
Hi @mimugmail , yeah, we can wait for it. Let's close this one.

**Comment by pereyra-m** [comment]
Please, don't hesitate in opening a new ticket with any question you have!

Have a nice day.
Regards.
