### ISSUE TITLE
Wazuh-Agent status never connected in agent on Debian 8.0 and Debian 7.6

### ISSUE THREAD

**Issue by taycom** [wazuh/wazuh#6022]
Hi. 

I install the wazuh-agent ( last version ) in to the Debian 7.6 and Debian 8.0, the first register in the wazuh-manager are correct, and appear in to the list of agents. But, the state never change and show " never connected", no info and any trace log . 

In the agent only show : ossec-agentd: WARNING: (4101): Waiting for server reply (not started). 

This log in to the two versions.

In another server with Debian 10 are installed wazuh-agent the same versión ( last ) and work all correctly. 

Any idea? 

Many thanks

**Comment by jnasselle** [comment]
Hi taycom!

According the [Agent life cycle documentation](https://documentation.wazuh.com/3.13/user-manual/agents/agent-life-cycle.html) "never connected" status means _The agent has been registered but has not yet connected to the manager_ . The key difference between "no registered" and "never connected" is the manager communication port (and process behind) that we are interacting with.

The fact that the agent is registered but not have communication with manager lead us to check that you Wazuh manager actually has the configuration that the agent was expecting or viceversa regarding to port number and protocol ([remote section](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/remote.html)). If the configuration is OK, then maybe there is a firewall problem.

Let me know if you need more help.

Regards.
Juan Nicolas
