### ISSUE TITLE
Issue getting agent data in Splunk

### ISSUE THREAD

**Issue by Stefan-CPlanet** [wazuh/wazuh#6028]
Hello, I have issues getting data.

I installed Splunk ( single Node ) and Wazuh manager and Wazuh API following instructions on the website,
However, no data is showing In wazuh ( I  cannot install wazuh agent on the same server as manager and API, I read its included in them).
I installed then Forwarder on the same server as everything else, changing post to 8090 as 8089 was taken, still, no data showing in wazuh.
I have tried to add an agent on a different server, installed it and it works, but no data is showing in was still. 

What can I do to troubleshoot this issue? What am I missing? Thanks

**Comment by Desvelao** [comment]
Hi @Stefan-CPlanet 

What version of Wazuh and Splunk are you using?

Could you share the output of:

1. Check you have alerts (in the host of Wazuh manager):
`cat /var/ossec/logs/alerts/alerts.json`

2. Check the forward-server is active on the forwarder:
`splunk list forward-server`
