### ISSUE TITLE
We lost our /var/ossec/etc/client.keys 

### ISSUE THREAD

**Issue by frankfoti** [wazuh/wazuh#6036]
Is there anyway or restoring that file from a db file or other in the directory somewhere?

|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by frankfoti** [comment]
We found a copy of the client.keys file and replaced it.  Some agents are reporting in but agenct_control -l does not indicate this are working correctly.  Is there a way to resolve this wihtout re-installing each agent?

**Comment by Selutario** [comment]
Hi @frankfoti,

I don't know if this is the case, but when you run Wazuh, the `authd` service loads a copy of the `client.keys` file. Therefore, if you modify or replace this file while Wazuh is active, many things will not work as expected.

For this reason, I recommend you to follow the steps below:
- Stop Wazuh.
- Replace/restore the `client.keys` file with the copy you had. 
- Start Wazuh again.

Let me know if this fixes your problem.

Kind regards!
Selu.

**Comment by frankfoti** [comment]
That worked for me.  Thanks
