### ISSUE TITLE
Rule creation for negate the specific field value 

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6044]
Dear Team,

We have configured the rule which indicates to give an alert in the case of particular field value is not matched. For example we take the office 365 use case;

`>  <rule id="100036" level="9">
    <decoded_as>json</decoded_as>
    <if_sid>100002</if_sid>
    <field name="office_365.Operation">AddedToSecureLink</field>
    <field name="office_365.TargetUserOrGroupName" negate="yes">\.@organisation.in$</field>
    <description>Office 365: Users sharing items with individuals outside of the organizations</description>
  </rule>`

what we need to achieve is to create an alert if the value of "office_365.Target User Group Name" is not belongs to the declared domain.

Thanks a lot for any help

**Comment by davidjiglesias** [comment]
Hello dear @VisakhMV-Coder,

The option to add `negate="yes"` in Wazuh rules is still not available. Our team is currently working on it and we hope it will be available as soon as possible https://github.com/wazuh/wazuh/issues/141#issuecomment-687617600

However, in the meantime, I think you can easily achieve the same behaviour with 2 rules, like this:

```
<rule id="100036" level="9">
    <if_sid>100002</if_sid>
    <field name="office_365.Operation">AddedToSecureLink</field>
    <description>Office 365: Users sharing items with individuals outside of the organizations</description>
</rule>

<rule id="100037" level="0">
    <if_sid>100036</if_sid>
    <field name="office_365.TargetUserOrGroupName">\.@organisation.in$</field>
    <description>Office 365: Users sharing items with individuals inside of the organizations</description>
</rule>
```

The first rule `100036` will match with any `Operation` being `AddedToSecureLink`, then, if the user is inside the organization it will match rule `100037` with level 0 and won't generate an alert, while users from outside the organization will only match rule `100036`, therefore generating the expected alert.

I hope this helps you. Please do not hesitate to contact back if you have any issues.

Regards,

David J. Iglesias

**Comment by VisakhMV-Coder** [comment]
Dear @davidjiglesias 

We have reached our solution regarding the above use case. It's worked for us. We are looking forward into the "negate field for creating use case easily. 

Thank you for your help.
