### ISSUE TITLE
Show Agent 000 ( Wazuh Manager) in Splunk

### ISSUE THREAD

**Issue by Stefan-CPlanet** [wazuh/wazuh#6046]
Ubuntu 20.04 Wazuh-Server ;
Wazuh Server all on a single node (manager + API) , Splunk (not elastic)

Hello, 
Can you please explain how to show Agent 000 ( The Wazuh Server- API & Manager ) in Splunk? 
I read that Manager includes Agent and that why I cannot install Agent on it, but there is no documentation that I can find how can I show it in Splunk? Thank you

**Comment by antoniomanuelfr** [comment]
Hi @Stefan-CPlanet 
I think that this problem was already solved in this issue, https://github.com/wazuh/wazuh/issues/6038, so I'm going to close it in order to not have duplicated issues in the repo. 

Feel free to re-open it again if it's necessary.
Kind regards.
