### ISSUE TITLE
Settings. 3005 - Invalid 'wazuh-app-version' header. Expected version '3.13.x', and found '3.9.x'. (/api/check-api)

### ISSUE THREAD

**Issue by vaibhav8666** [wazuh/wazuh#6051]
Hello I do have Wazuh 3.13.x , kibana=7.3.0, when and installed wazuh setup with Kibana, elasticsearch, filebeat perfectly.
On the first time when i tried to connect wazuh app with api, it was asking me to create a user. i follow the below page for the same :
https://documentation.wazuh.com/2.1/installation-guide/installing-elastic-stack/connect_wazuh_app.html

then I am getting this error
"Settings. 3005 - Invalid 'wazuh-app-version' header. Expected version '3.13.x', and found '3.9.x'. (/api/check-api)"

I tried to upgrade the wazuh api as well, but no success.:
https://documentation.wazuh.com/3.2/installation-guide/upgrading/latest_wazuh3_minor.html

Please help me out here.

**Comment by Desvelao** [comment]
Hi @vaibhav8666 

The link you posted about create a user is for Wazuh 2.1 version, and it seems you want to install 3.13.x. Please follow the guide for Wazuh version you want to install. 

Installation guides for Wazuh 3.13:
- Wazuh server: https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/index.html
- ELK: https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/index.html

The error ```"Settings. 3005 - Invalid 'wazuh-app-version' header. Expected version '3.13.x', and found '3.9.x'. (/api/check-api)"``` is saying what you have:
- Wazuh API 3.13.x
- Wazuh app for Kibana 3.9.x
The Wazuh app for Kibana and Wazuh API version should match exactly.

There is a Wazuh app for Kibana compatibility matrix that you can check to know what versions install. There is not compatibility between Wazuh app 3.13.x with Kibana 7.3.0.
https://github.com/wazuh/wazuh-kibana-app#wazuh---kibana---open-distro-version-compatibility-matrix

You could need to update ELK stack according to the version of Wazuh to be used.

**Comment by vaibhav8666** [comment]
thanks you so much... you were right.. I tried to upgrade the wazuh app as per my wazuh manager but failed. and because of miss match version I was getting this error.
thanks much. please close the issue.!!!
