### ISSUE TITLE
 Vulnerability Detector: NVD CVE JSON feeds version 1.0 no longer available

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh#6053]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1 | Vulnerability Detector | Manager | All | All |

## Description
It is not possible to download the NVD JSON feeds because feeds v1.0 are no longer available. For that reason, we need to start downloading the NVD JSON feeds v1.1.

**Comment by deepus101** [comment]
I have the same issue. Is there no way to manually change the download address?

**Comment by vikman90** [comment]
@deepus101 yes, you can. Add the `<url>` option to the NVD provider settings, this way:

```xml
<provider name="nvd">
    <enabled>yes</enabled>
    <url start="2002" end="2020">https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-[-].json.gz</url>
    <update_interval>1h</update_interval>
</provider>
```

Hope that helps.
Best regards.

**Comment by HoyluBert** [comment]
@vikman90 I tried your solution and I can no longer see the `There was no valid response` error messages I got from checking the no loner available feed. However I still get the following error message:
```
wazuh-modulesd:vulnerability-detector ERROR  (5582): Unavailable vulnerabilities at the NVD database. The scan is aborted.
```

I have `run_on_start` set to `yes` and tried to stop the wazuh manager, manually delete the vulnerability database and start it again, since I read this could help with this error message, but it did not change anything for me. Is there anything else I have to do to get the vulnerability scanning working again?
I am running manager version 3.13.1

**Comment by danimegar** [comment]
Hi @HoyluBert,

NVD is not updated because compressed file from URL is not correctly uncompressed (it will be fixed in next release). We have created a Pull Request to fix the URL so that the Vulnerability Detector module can download NVD feeds automatically again.

In the meantime, you can try to update the NVD via offline as explained in the [documentation](https://documentation.wazuh.com/3.13/user-manual/capabilities/vulnerability-detection/offline_update.html#national-vulnerability-database).

Regards,
Daniel

**Comment by danimegar** [comment]
Hello @Cyb3r4rch3r 
I think you are using the script that you can download below. You can change the path in the script:
```
# curl -O https://raw.githubusercontent.com/wazuh/wazuh/master/tools/vulnerability-detector/nvd-generator.sh
# chmod +x nvd-generator.sh
# ./nvd-generator.sh 2002 /custom/path/
```
Then, you have to uncompress the files. The NVD configuration would be:
```xml
<provider name="nvd">
    <enabled>yes</enabled>
    <path>/local_path/nvd-feed.*json$</path>
    <update_interval>1h</update_interval>
</provider>
```

Another idea: If you have the wazuh repository downloaded, you go to /wazuh/tools/vulnerability-detector/nvd-generator.sh. Open that file and check these lines:
```
while [ true ]
do
    link="https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-$year.json.gz"
```
If you see `link="https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-$year.json.gz"` you have to change it as shown above because that is the actual URL. 

Then use the script in the same way:  ./nvd-generator.sh 2002 /custom/path/

Regards,
Daniel
