### ISSUE TITLE
/var/ossec/etc/client.keys file keeps getting replaced

### ISSUE THREAD

**Issue by frankfoti** [wazuh/wazuh#6063]
This file "/var/ossec/etc/client.keys" keeps getting replaced and losing all our agent keys.  Is there a process that would be doing that?

Thanks

**Comment by pereyra-m** [comment]
Hello @frankfoti !

Sorry to hear you're still having trouble, I found your previous issue about **client.keys** #6036 

Even when you were able to restore your backup successfully, this file shouldn't be deleted by Wazuh. 
This isn't a normal behavior, and I can only think in a cluster scenario where the agents were registered in a Worker Node instead of the Master Node. This could cause troubles, and you should always register them in the Master node.

If you are not using a Wazuh cluster, then I would need more information about your version, agents and environment. 
Have you found any error messages in the manager logs? You can check this with the next command:
 `cat /var/ossec/logs/ossec.log | grep 'WARNING\|ERROR\|CRITICAL'`

Considering that **ossec-authd** is the daemon responsible for updating the **client.keys** file, you can also enable the debug output so we can get more information: replace the corresponding line with `authd.debug=2` in **/var/ossec/etc/internal_options.conf**.

Finally, if someone else is affecting this file, we can trace it this way ([source](https://www.thegeekdiary.com/how-to-audit-file-access-on-linux/))

- `sudo auditctl -w /var/ossec/etc/client.keys -p war -k client_keys_rule`
- `ausearch -f /var/ossec/etc/client.keys -i | less`

Well, will continue with all this new information.
Have a nice day.

Regards.

**Comment by frankfoti** [comment]
Debug is on now.  The ossec.log has tons of these WARNINGS below coming in continuously.  

2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2534 for the source ip: '207.102.20.146' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2561 for the source ip: '207.102.20.146' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2601 for the source ip: '98.172.56.41' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '026' at 'any'.
2020/09/21 12:20:03 ossec-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '053' at 'any'.
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 25676 for the source ip: '12.186.89.51' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 26385 for the source ip: '104.243.115.98' (name 'unknown').

**Comment by frankfoti** [comment]
We also have these ERRORS in the ossec.log
[root@wazuh-1 ~]# cat /var/ossec/logs/ossec.log | grep 'ERROR\|CRITICAL'
2020/09/21 06:41:55 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 06:47:12 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 07:24:20 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:24:20 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:24:55 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:24:55 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:25:05 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:25:05 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:25:20 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:25:20 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:30:40 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:30:40 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:31:10 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:31:10 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:31:30 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:31:30 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:36:35 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:36:35 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:36:50 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 07:36:50 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 07:47:52 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 07:53:31 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 08:01:22 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 08:01:22 ossec-maild: ERROR: (1223): Error Sending email to 52.96.9.178 (smtp server)
2020/09/21 08:54:12 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 08:59:53 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 09:22:05 ossec-authd: ERROR: (1401): Error reading authentication key: '
2020/09/21 09:22:13 ossec-remoted: ERROR: (1401): Error reading authentication key: '
2020/09/21 09:22:14 wazuh-modulesd: ERROR: (1401): Error reading authentication key: '
2020/09/21 09:24:27 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:24:27 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:24:43 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:24:43 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:25:00 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:25:00 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:25:20 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:25:20 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:27:35 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 09:40:21 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:40:21 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:40:37 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:40:37 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:47:10 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 09:47:10 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 09:49:47 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 10:22:21 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:22:21 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:23:07 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:23:07 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:32:50 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:32:50 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:33:10 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:33:10 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:44:13 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:44:13 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:44:22 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:44:23 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:44:48 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 10:44:48 ossec-maild: ERROR: (1223): Error Sending email to 52.96.87.194 (smtp server)
2020/09/21 10:55:53 ossec-analysisd: ERROR: Remoted socket error.
2020/09/21 10:55:53 ossec-analysisd: ERROR: Error communicating with remoted queue (-6).
2020/09/21 10:55:53 ossec-analysisd: ERROR: Remoted socket error.
2020/09/21 10:55:53 ossec-analysisd: ERROR: Error communicating with remoted queue (-6).
2020/09/21 11:00:00 wazuh-modulesd:vulnerability-detector: ERROR: (5513): CVE database could not be updated.
2020/09/21 11:14:09 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:14:09 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:14:21 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:14:21 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:19:38 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:19:38 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:21:46 ossec-remoted: ERROR: (1406): Checksum mismatch. Message received from agent '060' at 'any'.
2020/09/21 11:22:35 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:22:35 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:27:52 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:27:52 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:36:55 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:36:55 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:37:15 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:37:15 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:43:25 ossec-remoted: ERROR: (1406): Checksum mismatch. Message received from agent '115' at 'any'.
2020/09/21 11:47:28 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:47:28 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:47:43 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 11:47:43 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 11:55:36 ossec-remoted: ERROR: (1406): Checksum mismatch. Message received from agent '060' at 'any'.
2020/09/21 12:01:03 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:01:03 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:02:56 ossec-remoted: ERROR: (1406): Checksum mismatch. Message received from agent '066' at 'any'.
2020/09/21 12:05:44 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:05:44 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:06:04 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:06:04 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:07:24 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:07:24 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:07:49 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:07:49 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:07:59 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:07:59 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:08:44 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:08:44 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:09:05 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:09:05 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:09:54 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:09:54 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:10:45 ossec-maild: ERROR: (1764): Mail from not accepted by server
2020/09/21 12:10:45 ossec-maild: ERROR: (1223): Error Sending email to 52.96.90.34 (smtp server)
2020/09/21 12:18:10 ossec-remoted: ERROR: (2202): Error uncompressing string. Message received from agent '054' at 'any'
2020/09/21 12:22:10 ossec-csyslogd: ERROR: date or location not NULL or p is NULL

**Comment by frankfoti** [comment]
FYI - I have a slack communication on this as well with "Jeremías José Palacios "

I have applied this so next time the file gets changed (if it does)  then we will capture that activity correct?

**Comment by frankfoti** [comment]
Below is probably a separate issue correct?  Any Thoughts on why that is?  They have 1580+ in the clients.keys file but only about 800+/- ever get connected.

The ossec.log has tons of these WARNINGS below coming in continuously.

2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2534 for the source ip: '207.102.20.146' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2561 for the source ip: '207.102.20.146' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 2601 for the source ip: '98.172.56.41' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '026' at 'any'.
2020/09/21 12:20:03 ossec-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '053' at 'any'.
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 25676 for the source ip: '12.186.89.51' (name 'unknown').
2020/09/21 12:20:03 ossec-remoted: WARNING: (1408): Invalid ID 26385 for the source ip: '104.243.115.98' (name 'unknown').

**Comment by pereyra-m** [comment]
Hello again @frankfoti 
Thank you for all the information provided. The conversation with @palaciosjeremias has valuable information too.

The log messages like **...WARNING: (1408): Invalid ID...** and related may be from the time when the **client.keys** file was not updated, and the manager was unable to receive a message from an agent without its valid key. But you shouldn't see them now. If that is the case, please check that the key in the agent is the same than the manager is expecting.

We can sum up that:
- The correct way to replace **client.keys** is when the manager is stopped.
- Even if it is working now, it is strange it happened the first time.
- We can track the file activity with `auditctl` for the next time, but consider that if you don't edit the **/etc/audit.rules** file as we can see in [this source](https://www.thegeekdiary.com/how-to-audit-file-access-on-linux/), it won't not be persistent across system restarts. And please, be careful about your disk usage if you leave this log to grow up a long time.

On the other hand, the logs you shared show problems in your e-mail alerts and vulnerability detector database update. If you have enabled these modules and you are also experiencing trouble with them, don't hesitate in opening a new issue and we'll work on that too.

Regards.

**Comment by pereyra-m** [comment]
I am closing this issue, but feel free to contact us at any time!

Regards.
