### ISSUE TITLE
Wazuh services which uses http &https protocols for communication

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6078]
Dear team,

can somebody help me with an answer for the following question.

1.Which are the wazuh service that uses http & https communication.

eg: vulnerability detector needs to be updated through nvd and oval repository,
https://canonical.com: Used to pull CVEs for Ubuntu Linux distributions.
https://access.redhat.com: Used to pull CVEs for Red Hat and CentOS Linux distributions.
https://www.debian.org: Used to pull CVEs for Debian Linux distributions.

can somebody help with the answer of the question please

**Comment by chemamartinez** [comment]
Hi @VisakhMV-Coder,

All the Wazuh services that connect to external URLs use https by default. Let me show you this for the different services and modules where these communications are defined.

### Manager

**Vulnerability Detector**

It connects to external sources to fetch the data feeds. Here you can see the default repositories are https.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.h#L39

**Wazuh API**

You can reach the Wazuh API via https (which is the default option).

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/api/api/spec/spec.yaml#L21

**Collecting Azure logs**

The integration with Azure connects to an API to fetch the logs.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/wodles/azure/azure-logs.py#L198

### Manager

**Integrations with external APIs**

For example, the VirusTotal integration connects to their API to request information about suspicious checksums.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/integrations/virustotal#L101

The same with other integrations such as PagerDuty.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/integrations/pagerduty#L64

### Others

Communications out of the manager uses https as well.

**Dependencies**

When building Wazuh, dependencies are pulled from `https://packages.wazuh.com`.

https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/src/Makefile#L874

I hope this information is useful for you. Feel free to ask again any extra information.

I would also like to show you [our community section](https://wazuh.com/community/) where you can join to the slack channel or mailing lists to ask questions and participate in discussions.

Best regards,
Chema.

**Comment by VisakhMV-Coder** [comment]
Yes, Thanks for the details.
