### ISSUE TITLE
[Development] Wrong user-group mode of SSL files after upgrading to 4.0.0

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#6081]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0-40000 | wazuh-api | Manager | Packages | DEB and RPM  |

Hello team,

The CICD team has been testing the upgrade of the different versions of Wazuh to 4.0.0, and we have noticed the following unexpected changes in check-files:

```
Different:
/var/ossec/api/configuration/ssl/server.crt [Wrong:  mode]
	Expected: root root  0400  # -r--------
	Found   : root root  0644  # -rw-r--r--

/var/ossec/api/configuration/ssl/server.key [Wrong:  mode]
	Expected: root root  0400  # -r--------
	Found   : root root  0644  # -rw-r--r--
```

The following are all the results of this research:

- Only happens with versions below `3.12.0` and when the target version is `4.0.0`. For example:
   - From `3.11.4` to `3.13.1` it works.
   - From `3.12.0` to `4.0.0` it works.
   - From `3.11.4` to `4.0` it fails.
- This occurs for both DEB and RPM

The weird thing is that it finds `0644` permissions when not even in the database check-files they have those permissions (we have `0400` or `0600`).

It is requested to investigate the possible cause of this situation.

Best regards.

**Comment by davidjiglesias** [comment]
Fixed permissions for ssl certificates in `4.0.0` to be `400`:

```
root@wazuh-master:/var/ossec/api/configuration/ssl# ll
total 20
drwxrwx--- 1 root ossec 4096 Oct  7 08:25 ./
drwxrwx--- 1 root ossec 4096 Oct  7 07:42 ../
-r-------- 1 root root  1233 Oct  7 08:25 server.crt
-r-------- 1 root root  1704 Oct  7 08:25 server.key
``
