### ISSUE TITLE
Create a bplist parser to read extra info for macOS package inventory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6082]
## Description

Package properties in macOS are generally obtained by parsing the `Info.plist` file located at the content folder for each application. For some packages, that files are in `bplist` (binary property list format) so it is needed to convert them to XML before parsing.

The goal of this issue is to create a `bplist` parser to be able to read these files.

Added functions must include unit tests.

### References

- [Article explaining how this format works](https://medium.com/@karaiskc/understanding-apples-binary-property-list-format-281e6da00dbd#:~:text=Binary%20plist%20structure,offset%20table%20and%20the%20trailer)
- [Sample program written in C](https://github.com/vipyne/bplistparser/blob/master/bplist-parser.c)

**Comment by 0xN3utr0n** [comment]
Development branch: `6082_macos_read_bplists`
