### ISSUE TITLE
Normalize the package names for the macOS package inventory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6083]
## Description

As described in https://github.com/wazuh/wazuh/issues/5860, we are adding Vulnerability Detector compatibility to macOS agents.

To achieve it, one main task is to collect the most details as possible from the macOS installed packages.

### Separate vendor and package names

In a few cases, the name of the package contains its vendor:

```
VMware Fusion
Microsoft Excel
Microsoft Word
```

It creates a conflict with the CPE indexed from the NVD:

```
124175|a|vmware|fusion|8.1|*|*|*|*|mac_os_x|*|*
a|microsoft|excel|2016|*|*|*|*|mac|*|*
```

We may have to create a dictionary for these cases to send the product name and the vendor in different fields.

Add unit tests to created functions.

**Comment by danimegar** [comment]
## Separate vendor and package names
- Microsoft 365 -> Microsoft, 365
- Microsoft Word -> Microsoft, Word
- Microsoft Excel -> Microsoft, Excel
- Microsoft PowerPoint -> Microsoft, PowerPoint
- Microsoft Outlook -> Microsoft, Outlook
- Microsoft Remote Desktop -> Microsoft, Remote Desktop
- Microsoft OneNote -> Microsoft, OneNote
- Microsoft To Do -> Microsoft, To Do
- VMware Remote Console -> VMware, Remote Console
- VMware Fusion -> VMware, Fusion
- VMware Horizon Client -> VMware, Horizon Client
- zoom.us -> zoom (`.us` not fount in the package name from NVD): `179404|a|zoom|zoom|*|*|*|*|*|mac_os_x|*|*` and `589643493|2020/09/25 08:29:52|pkg|zoom.us||...`

**Comment by chemamartinez** [comment]
Done: #6147
