### ISSUE TITLE
Vulnerability Detector: make macOS agents scannable 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6084]
## Description

When the Vulnerability Detector gets the connected agent lists, it associates each compatible agent with its corresponding feed. https://github.com/wazuh/wazuh/blob/556d1b64d7feba74bb5060fd5fe18e48db55bee6/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L4538

Now, macOS agents have to be recognized to be scanned against the NVD later. 

Agents prior to the version where this feature will be included should be skipped as well, since those agents won't be compatible with the macOS vulnerability scan.

**Comment by MarcelKemp** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/6084-macOS-agents-scannable

**Comment by chemamartinez** [comment]
Done #6335
