### ISSUE TITLE
Remove the limit of agents that a manager can support

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#6097]
|Branch|
|---|
| [dev-max-agents](https://github.com/wazuh/wazuh/compare/dev-max-agents) |

# Main goal

The main goal of this epic is to deprecate the MAX_AGENTS variable which is now adding a limit to the number of agents a Wazuh manager can handle.

The idea is to no longer limit the number of agents for a Wazuh manager. To achieve this, the MAX_AGENTS variable must be deprecated in the following places:

- File handlers used by the rootcheck decoder of `analysisd`.

- RIDS files used by `remoted`.

- Upgrade queue used by the upgrade module of `modulesd`.

- Pending queue used by `remoted`.

**Comment by okbamasri** [comment]
how could we keep the limitation and mange desired numbers!

**Comment by vikman90** [comment]
@okbamasri this proposal aimed to eliminate the agent limit, so there is no limit currently.

However, we're starting to work on a couple of options that will once again allow us to limit the number of registered agents: #12512.

Should you have any questions or a particular use case, you're welcome to participate in that issue.

Best regards.

**Comment by okbamasri** [comment]
@vikman90  thank you very much dear. this point is important for me to have control over desired number of agent. i am just wondering if we have expected time for the release!

**Comment by vikman90** [comment]
Hi @okbamasri, 

I'm afraid that, after internal discussions, we have agreed not to implement the agent limit so far. We need to decide what the agent limit means: number of agents registered and/or number of active agents.

However, depending on why you need this feature, we have the following issues in the roadmap:

- #11007
  - Add a feature to automatically decommission disconnected agents.
- #10447
  - Extend the agent ID range.

Hope those issues meet your needs. If not, or if you still need an agent limit, feel free to open a feature request to us.

Best regards.
