### ISSUE TITLE
#5504 Unable map Office 365 Audit log Geolocation 

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6098]
Wazuh Version 3.13

We have Integrated the Office 365 API with wazuh manager, It has been getting audit logs from the office 365 properly. but we have tried to create a business use case to know the geolocation of user login. I have tried to edit the wazuh template file to add the custom(Ofice 365 field "clientIP") field to get the geolocation but unfortunately, wazuh manager did not map any geo value to the custom failed.

Is there any possibility to achieve the same?This was the question asked by me,and i got a response from @davidjiglesias ,

Hello @VisakhMV-Coder,

Wazuh manager will not map geo values to the custom field. By default, it is Filebeat who adds GeoIP information to the alerts before sending them to Kibana.

Currently, the fields using GeoIP can be found in the filebeat configuration file:

https://github.com/wazuh/wazuh/blob/v3.13.1/extensions/filebeat/7.x/wazuh-module/alerts/ingest/pipeline.json

Try adding your field to this configuration file and filebeat will add GeoIP data to the alert.

Best regards,

David J. Iglesias

@davidjiglesias 

hai,
i am sorry that we need to reopen this ticket.

as per the suggestion of @davidjiglesias ,we added new fields in config file,but it didnt work.

In case of office_365,the value comes as "data.clientip".

#nano /usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json
{
"description": "Wazuh alerts pipeline",
"processors": [
{ "json" : { "field" : "message", "add_to_root": true } },
{
"geoip": {
"field": "data.srcip",
"target_field": "GeoLocation",
"properties": ["city_name", "country_name", "region_name", "location"],
"ignore_missing": true,
"ignore_failure": true
}
},
{
"geoip": {
"field": "data.clientip",
"target_field": "GeoLocation",
"properties": ["city_name", "country_name", "region_name", "location"],
"ignore_missing": true,
"ignore_failure": true
}
},
{
"geoip": {
"field": "data.win.eventdata.ipAddress",
"target_field": "GeoLocation",
"properties": ["city_name", "country_name", "region_name", "location"],
"ignore_missing": true,
"ignore_failure": true
}
},
{
"geoip": {
"field": "data.aws.sourceIPAddress",
"target_field": "GeoLocation",
"properties": ["city_name", "country_name", "region_name", "location"],
"ignore_missing": true,
"ignore_failure": true
}

this is the code i have added,still its not working.is there any problem or bug in wazuh for a field value in api to be added with a geotag.

Thanks in advance.sorry for the delay,as i was busy with some new projects.

is there any other ways to update this geo location.or if you can help me with the details it will be very much helpful.

**Comment by Selutario** [comment]
Hi @VisakhMV-Coder!

As far as I can see, your `filebeat` configuration seems correct. However, make sure you are complying with these two aspects that a frontend teammate told me:
- The IPs of the fields must be public, otherwise, the module will not be able to obtain geoinformation from them.
- After modifying `filebeat`, it is important to run the following command, so it notices the changes performed:

  ```
  filebeat setup --pipelines
  ```

Give it a try and tell me if it works properly or you still have problems.

Best regards,
Selu.

**Comment by VisakhMV-Coder** [comment]
dear @Selutario ,

as per your suggestion,i confirmed the ip is public.
filebeat setup --pipelines also...but still it is not tagging geolocation.

i made a custom parser for sophos firewall and watchguard firewall...in that case for src ip geolocation is working...but as office 365 is a case of api call...i dont know whether the issue is happening...

**Comment by VisakhMV-Coder** [comment]
Hello,

We have still the same problem. Not yet resolved even after done the latest changes you have given.

**Comment by Selutario** [comment]
Hello @VisakhMV-Coder,

First of all, sorry for the late reply, I didn't see your last comment. As far as I can see it, the settings you have shown are correct and if the alert contains such a field, geolocation should be working. 

Could you paste an alert generated in your Wazuh manager from an Office 365 event that contains the `data.clientIP` field here? So I can try to reproduce your case.

Regards,
Selu.

**Comment by VisakhMV-Coder** [comment]
Hi,

Thanks for the response.

It's working now. 

There was a small mistake in the field name, I have mistakenly added the field name "data.clientip" instead of "data.office_365.ClientIP".

**Comment by VisakhMV-Coder** [comment]
Issue resolved.
