### ISSUE TITLE
Unable to download manager dependencies

### ISSUE THREAD

**Issue by tbhaxor** [wazuh/wazuh#6099]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v3.13.0 | Dependencies | Manager | Sources | Arch Linux |

I am unable to run the `make deps` command successfully in `src` directory

On running the command i see this errror
```
curl -so external/libdb.tar.gz https://packages.wazuh.com/deps/3 13./libraries/sources/libdb.tar.gz
make: *** [Makefile:925: external/libdb.tar.gz] Error 6
```

And when i goto external directory i see all files are ASCII Text
```
cJSON.tar.gz:   XML 1.0 document, ASCII text
cpython.tar.gz: XML 1.0 document, ASCII text
curl.tar.gz:    XML 1.0 document, ASCII text
libdb.tar.gz:   XML 1.0 document, ASCII text
```

So i tried to _cat_ one of the file and saw this weird XML Response
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>deps/3</Key><RequestId>AT7M8QET1K0Y6S5R</RequestId><HostId>/t3fCgzE/k1461vBQawzHJjeEEI3TQHt7uoH7QORANK7ICc6Zy8uMNjAo5zdmPjoaGnYpdp+r1s=</HostId></Error>
```

**Comment by grg121** [comment]
Hello @tbhaxor,

This is a [known issue](https://github.com/wazuh/wazuh/issues/5021). Arch Linux has the last gmake version which makes our space definition deprecated. If you check the curl statement that is failing you could see that `3 13.` in the path which should be  `3.13`.

The [fix](https://github.com/wazuh/wazuh/commit/8e2f4d83c9548556d4acd66c7e382f8e46ce79a1) for this will be introduced in `4.0.0`.

Meanwhile, the fix would be [this change on the Makefile](https://github.com/wazuh/wazuh/commit/8e2f4d83c9548556d4acd66c7e382f8e46ce79a1).

```
sed -i 's/VERSION = $(subst $(space),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))/VERSION = $(subst $() $(),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))/g' Makefile 
```
Do not doubt to ask again if you have further questions

Best regards.

**Comment by tbhaxor** [comment]
Hi @grg121 Will test in some days and come back here if i found any problem.

**Comment by BraulioV** [comment]
Hi @tbhaxor,

If you're going to build the manager in Arch Linux you'll probably face other issues related to ArchLinux. In https://github.com/wazuh/wazuh/issues/5162#issuecomment-637697781 you can find the three main issues. All of them have been solved for the next major release (`v4.0.0`).

For now, you can build the master branch which contains the latest changes and fixes for this release. 

In addition, you can find more info about the build dependencies in https://github.com/wazuh/wazuh/issues/3012#issuecomment-553458158, but here you have a quick summary to build the wazuh-manager:
```shellsession
# pacman -Syu gcc git make automake autoconf libtool libnghttp2 libpsl librtmp0 brotli python perl-text-glob expat bzip2 gdbm openssl libffi zlib libnsl tk sqlite valgrind bluez-libs mpdecimal llvm gdb xorg-server-xvfb --noconfirm
# git clone https://github.com/wazuh/wazuh --depth=1 && cd wazuh/
# make deps -C src/
# make TARGET=server -j$(nproc) -C src/
# ./install.sh
# /var/ossec/bin/ossec-control start
```

**Comment by tbhaxor** [comment]
@BraulioV and @grg121  I have a question for wazuh that why you are not releasing community packages for arch distros?

**Comment by tbhaxor** [comment]
Or should i create and upload AUR release myself?

**Comment by tbhaxor** [comment]
> Hello @tbhaxor,
> 
> This is a [known issue](https://github.com/wazuh/wazuh/issues/5021). Arch Linux has the last gmake version which makes our space definition deprecated. If you check the curl statement that is failing you could see that `3 13.` in the path which should be `3.13`.
> 
> The [fix](https://github.com/wazuh/wazuh/commit/8e2f4d83c9548556d4acd66c7e382f8e46ce79a1) for this will be introduced in `4.0.0`.
> 
> Meanwhile, the fix would be [this change on the Makefile](https://github.com/wazuh/wazuh/commit/8e2f4d83c9548556d4acd66c7e382f8e46ce79a1).
> 
> ```
> sed -i 's/VERSION = $(subst $(space),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))/VERSION = $(subst $() $(),.,$(wordlist 1,2,$(subst ., ,$(patsubst v%,%,$(shell cat VERSION)))))/g' Makefile 
> ```
> 
> Do not doubt to ask again if you have further questions
> 
> Best regards.

I am now unable to `make TARGET=server`

```
[root@f5a439b48370 src]# make TARGET=server
make: *** No rule to make target 'external/cJSON/cJSON.o', needed by 'external/cJSON/libcjson.a'.  Stop.
```

**Comment by BraulioV** [comment]
Hi @tbhaxor,

Releasing official ports for ArchLinux is in our roadmap (https://github.com/wazuh/wazuh-packages/issues/361), but I can't give you an ETA yet because first, we needed to solve some issues in the source code before building the official package.

About this error
> [root@f5a439b48370 src]# make TARGET=server
> make: *** No rule to make target 'external/cJSON/cJSON.o', needed by 'external/cJSON/libcjson.a'.  Stop.

Which version are you building? Did you follow the steps from https://github.com/wazuh/wazuh/issues/6099#issuecomment-700664569?

**Comment by tbhaxor** [comment]
> Which version are you building? Did you follow the steps from [#6099 (comment)](https://github.com/wazuh/wazuh/issues/6099#issuecomment-700664569)?

I want to build v3.13.0

**Comment by tbhaxor** [comment]
> official ports for ArchLinux is in our roadmap

That is awesome, it would be generous if you guys release at least an AUR package for arch linux distros

If you need any help regarding this. I would be happy to assist you

**Comment by grg121** [comment]
Hello @tbhaxor ,

We're going to release Wazuh 4.0 soon and all the issues related to ArchLinux have been addressed and fixed on it. If you really want to use 3.13 you would need to create a branch from the last 3.13 tag and add all the fixes merged to 4.0 into that branch, I think you should rather wait for 4.0 because this could be tedious.

Regarding the package on AUR: is something we have in mind. I cannot give you any ETA yet but we accept any kind of help: you could open a pull request on wazuh-packages adding a folder for Arch Linux package generation with instructions and required files to generate a custom package. We would review it and may use it as a base to start giving Arch Linux support.

**Comment by tbhaxor** [comment]
> pull request on wazuh-packages adding a folder for Arch Linux package

Just tell me one thing @grg121 How can we install wazuh by not prompting from user

Like if i want to simply install wazuh manager and in same directory

Is there any argument like
```
./install.sh --target [manger|agent]
```

**Comment by vikman90** [comment]
@tbhaxor Indeed, you can.

We can use environment variables to configure the installer so it will prompt no questions.

The parameters we must define depend on the installation mode (manager or agent). All they are in [preloaded-vars.conf-(https://github.com/wazuh/wazuh/blob/4.0/etc/preloaded-vars.conf). So we have three options:

1. Uncomment the options in `etc/preloaded-vars.conf` before running `install.sh`.
2. Export the environment variables and run `install.sh`.
3. Define such variables in the call to `install.sh`.

For instance, this script helps you install a manager from sources. The installer will do all the work, so you don't need to call `make` before `install.sh` unless you need to set a particular building option:

```sh
git clone --depth 1 https://github.com/wazuh/wazuh.git -b 4.0 wazuh-4.0

USER_LANGUAGE="en" \
    USER_NO_STOP="y" \
    USER_INSTALL_TYPE="server" \
    USER_DIR="/var/ossec" \
    USER_ENABLE_EMAIL="n" \
    USER_ENABLE_SYSCHECK="y" \
    USER_ENABLE_ROOTCHECK="y" \
    USER_WHITE_LIST="n" \
    USER_ENABLE_SYSLOG="y" \
    USER_ENABLE_AUTHD="y" \
    USER_AUTO_START="y" \
    wazuh-4.0/install.sh
```

Hope that helps.
Best regards.

**Comment by tbhaxor** [comment]
Will try to create aur packages and send pull request on [wazuh/wazuh-packages](https://github.com/wazuh/wazuh-packages)

**Comment by tbhaxor** [comment]
Meanwhile please keep this issue open

**Comment by JSON-HSB** [comment]
@spothound @vikman90 I'm still having this issue on debian 10 and arch. 
- git repo cloned ( also rescursively and also with depth set to 1 )
- cd to src
- sudo make deps
- curl doesnt have permissions to download external/cJSON and shares_modules/http-request
- downloading these manually
- make: no rule to make target 'external/cJSON/.o', needed by 'external/cJSON//libcjson.a'

**Comment by vikman90** [comment]
@JSON-HSB I've provided an answer for you at:

- https://github.com/wazuh/wazuh/issues/25424

Hope it helps. Let me close this issue.
