### ISSUE TITLE
Update coding style for C

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#6115]
## Description
Extend the current C coding style adding best practices examples, to improve the development on common modules.

Emphasize in:
- Initialization
- Naming conventions
- Memory management.
- Const correctness 
- Style conventions

- [x] Draft, include Victor revision.
- [x] Modify wiki

**Comment by tinachoB** [comment]
Wiki updated: https://github.com/wazuh/wazuh/wiki/Coding-style-guide-(C-plus-plus)
