### ISSUE TITLE
Add error code to API response outer field

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6131]
Hello team,

With the changes to Wazuh API for 4.0, we removed error field from the json response and moved it inside the failed_items field, where every failed item would have its own error in case it occurred. However, keeping the outside error field for HTTP responses with code 200 will help the developer determine if everything went OK, everything failed or the response is only partially OK.

We can add this change in the API middleware in charge of processing the response. 

error field will come in every HTTP 200 response with the following values:

0 -> All petitions succeeded.
1 -> All petitions failed.
2 -> There is a partial response with some successes and some fails.

The HTTP response would look like:

```
                data:
                    affected_items:
                      - '002'
                      - '004'
                    total_affected_items: 2
                    failed_items: []
                    total_failed_items: 0
                error: 0
                message: 'Restart command was sent to all agents'
``

**Comment by CarlosRS9** [comment]
# Status Update

After some researching and testing we discovered that adding the new error field using the middleware would not be efficient, as this would mean we have to decode the responses, add the new field and encode them again. We tested a solution using a `json_response` function instead.

After checking the viability of the addition of this new field we realized there are some endpoints that are not returning a dictionary named `data` with the content of the answers. Here are the list of endpoints that are not currently returning a "data" dictionary:
```
GET {protocol}://{host}:{port}/security/user/authenticate
POST {protocol}://{host}:{port}/security/user/authenticate/run_as
GET {protocol}://{host}:{port}/security/actions
GET {protocol}://{host}:{port}/security/resources
GET {protocol}://{host}:{port}/
```
Changing those endpoints to return a "data" dictionary would have impact on the Frontend team, so we need to make sure first.

The response of the `/security/resources` and `/security/actions` endpoints could be updated to return a "data" dictionary with no issues.

**Comment by CarlosRS9** [comment]
# Status Update

We should wait until the endpoint's responses are reviewed and improved before attempting to add the new `error` field to them. See #6196 for more information.

**Comment by CarlosRS9** [comment]
# Status Update

The development is finished. `error` field is now present in every api response. Additionally, `code` field present in failed responses has been replaced by the `error` field.
