### ISSUE TITLE
vulnerability-detector of agents not showing up only the manager reports

### ISSUE THREAD

**Issue by MalfuncEddie** [wazuh/wazuh#616]
Hi,

I'm trying to get the vulnerability-detector working but it does not work on anything else but the manager itself. So I don't think it is an issue with the manager config since that is reporting OK.

Config I've added to the agents.

`<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>`

Any idea?

Followed the documentation on 
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection.html

**Comment by crolopez** [comment]
Hi @MalfuncEddie,

Can you confirm that your agents have a [compatible version](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection.html#compatibility-matrix)? If so, have you configured vulnerability-detector to download the vulnerability databases for the operating systems of those agents?

Agents will not report vulnerabilities if the manager is not configured to download vulnerabilities from their operating system, even if they have syscollector enabled.

Best regards.

**Comment by MalfuncEddie** [comment]
Hi,

I think the manager is ok since the manger itself is reporting and it is the same OS as the client.

From the manager conf:
`<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <packages>yes</packages>
</wodle>

  <wodle name="vulnerability-detector">
    <disabled>no</disabled>
    <interval>1d</interval>
    <run_on_start>yes</run_on_start>
    <update_ubuntu_oval interval="60m" version="16,14,12">yes</update_ubuntu_oval>
    <update_redhat_oval interval="60m" version="7,6,5">yes</update_redhat_oval>
  </wodle>

`
client that is not reporting: 

`~ # cat /etc/issue
Ubuntu 16.04.2 LTS \n \l
# ./ossec-agentd -V

Wazuh v3.2.2 - Wazuh Inc.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License (version 2) as
published by the Free Software Foundation. For more details, go to
https://www.gnu.org/licenses/gpl.html


`

It looks good to me?

kind regards,
