### ISSUE TITLE
Custom Rules Priorities 

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#6183]
Hi guy,
can someone please explain to me the priorities on custom rules, for example
```

<group name="accesslog">
  <rule id="100001" level="6">
    <if_sid>31100</if_sid>
    <regex>phpstorm</regex>
    <description>php</description>
  </rule>
</group>

<group name="accesslog">
  <rule id="100002" level="3">
    <if_group>accesslog</if_group>
    <regex>^10\.</regex>
    <description></description>
  </rule>
</group>
```

When there is phpstorm in the log it fires rule 100001 which is expected, but when we have 10.* address + phpstorm it fires rule 100002. Why is that? Basically how ossec decides what rule to alert if there is matching rules?
Is it level, rule id, random?

Thanks in advance!

**Comment by Lopuiz** [comment]
Hello,

Line `<if_group>accesslog</if_group>` makes rule 100002 was a child of 100001 and all rules which have group `accesslog` (these rules can be found in `/var/ossec/ruleset/rules/0245-web_rules.xml`).

It does that Wazuh checks if rule 100002 matches all log which match `accesslog` rules. If this log has number 10, it matches, and the alert generated is from 100002.

You can use `ossec-logtest` with option -v. It will tell all rules fire from a log. For example:

The following log match rule number 4, 31100 and 31108.

>2015-07-28 15:07:26 1.2.3.4 GET /QOsa/Browser/Default.aspx UISessionId=SN1234123&DeviceId=SN12312232SHARP+MX-4111N 80 - 31.3.3.7 OpenSystems/1.0;+product-family="85";+product-version="123ER123" 302 0 0 624

And this is the ossec-logtest output:

```
/var/ossec# bin/ossec-logtest -v
2020/10/05 10:33:40 ossec-testrule: INFO: Started (pid: 10830).

Since Wazuh v4.0.0 this binary is deprecated. Use wazuh-logtest instead

ossec-testrule: Type one log per line.

2015-07-28 15:07:26 1.2.3.4 GET /QOsa/Browser/Default.aspx UISessionId=SN1234123&DeviceId=SN12312232SHARP+MX-4111N 80 - 31.3.3.7 OpenSystems/1.0;+product-family="85";+product-version="123ER123" 302 0 0 624


**Phase 1: Completed pre-decoding.
       full event: '2015-07-28 15:07:26 1.2.3.4 GET /QOsa/Browser/Default.aspx UISessionId=SN1234123&DeviceId=SN12312232SHARP+MX-4111N 80 - 31.3.3.7 OpenSystems/1.0;+product-family="85";+product-version="123ER123" 302 0 0 624'
       timestamp: '(null)'
       hostname: 'lopezziur'
       program_name: '(null)'
       log: '2015-07-28 15:07:26 1.2.3.4 GET /QOsa/Browser/Default.aspx UISessionId=SN1234123&DeviceId=SN12312232SHARP+MX-4111N 80 - 31.3.3.7 OpenSystems/1.0;+product-family="85";+product-version="123ER123" 302 0 0 624'

**Phase 2: Completed decoding.
       decoder: 'windows-date-format'
       action: 'GET'
       url: '/QOsa/Browser/Default.aspx UISessionId=SN1234123&DeviceId=SN12312232SHARP+MX-4111N'
       srcport: '80'
       srcip: '31.3.3.7'
       user_agent: 'OpenSystems/1.0;+product-family="85";+product-version="123ER123"'
       id: '302'

**Rule debugging:
    Trying rule: 4 - Generic template for all web rules.
       *Rule 4 matched.
       *Trying child rules.
    Trying rule: 31100 - Access log messages grouped.
       *Rule 31100 matched.
       *Trying child rules.
    Trying rule: 31108 - Ignored URLs (simple queries).
       *Rule 31108 matched.
       *Trying child rules.
    Trying rule: 31168 - Shellshock attack detected
    Trying rule: 31169 - Shellshock attack detected
    Trying rule: 31103 - SQL injection attempt.
    Trying rule: 31509 - CMS (WordPress or Joomla) login attempt.

**Phase 3: Completed filtering (rules).
       Rule id: '31108'
       Level: '0'
       Description: 'Ignored URLs (simple queries).'
```

I hope it helps you.

Regards,
Eva

**Comment by a108a108** [comment]
Hello @Lopuiz ,

thank you for your answer, if i understand correctly the child rule has the priority and it fires.
Which brings the question how ossec treats child rules, in my case if i add duplicated 100002 -> 100003,  
what would happen ?

` Trying rule: 31168 - Shellshock attack detected
    Trying rule: 31169 - Shellshock attack detected
    Trying rule: 31103 - SQL injection attempt.
    Trying rule: 31509 - CMS (WordPress or Joomla) login attempt.`

^ This seems like a random testing to me,

**Comment by Lopuiz** [comment]
Hello!

If these rules are children of the same parent, Wazuh orders it by level (high to low). If two rules have the same level, the rule read before will be first (This is why the rules files have a number on its name).

Rule levels allowed are from 0 to 16. From high to low: 0, 16, 15, 14, ..., 3, 2, 1. Level 0 is special, and rules with this level don't generate alerts. It is usually used to group logs. For example: 

```xml
  <rule id="200" level="0">
    <decoded_as>wazuh</decoded_as>
    <description>Grouping of wazuh rules.</description>
  </rule>
```

**Comment by a108a108** [comment]
Thank you @Lopuiz !
