### ISSUE TITLE
Refactor / Implement data platform selector

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#6191]
## Description

This issue aims to make a class that specializes by operating system, so that at compile time it is decided which segments of the code to compile including its operating system primitives.

In this way we avoid adding "ifdef" throughout the code, and only the corresponding ".cpp / .h" are compiled.

![SyscollectorDBSYNC](https://user-images.githubusercontent.com/14300208/95042795-57fb5800-06b1-11eb-8982-4af38cedf383.png)

## DoD / Tasks
- [ ] Implement pimpl idiom, and modify the build system in favour of the cross compiling.
- [ ] Check compilation for Linux, macOS and Windows(cross compilation)
- [ ] Run CPP check
- [ ] Add unit tests (100% pass rate)
- [ ] Run Valgrind / Helgrind
- [ ] Run ASAN
- [ ] Run Coverity
- [ ] PR

**Comment by konangc87** [comment]
Fixed as part of #6236
