### ISSUE TITLE
Syscollector CMake project (only cpp compilation)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#6202]
## Description
This issue aims to generate and compile the syscollector module project on the agent.

It should be considered that this should not include the linking of any binary, shared module or static module, it should only generate the .o files that should be linked in the wazuh modules building.

## Tasks
- [x] Add CMakeLists file to syscollector, to compile for each platform.
- [x] Modify Makefile to compile only all cpp files of syscollector.
- [x] PR

**Comment by tinachoB** [comment]
This issue has been considered as part of the resolution of #6190 
Related PR: https://github.com/wazuh/wazuh/pull/6236
