### ISSUE TITLE
Wazuh-Server offline Installation

### ISSUE THREAD

**Issue by PhilippBaur** [wazuh/wazuh#6213]
Hello,

I'm currently trying to install the Wazuh Server on a company Server. The company server does not have an internet connection, that's why I ran into several problems up until now.
I could already fix some of them, but it's very time consuming and I'm not sure if all the dependencies are installed correctly.

Is there a way to install the Wazuh Server without an internet connection? All I found is that I most likely need to have a internet connection to get all the dependencies. 

Thanks for any help!

Regards
Philipp

**Comment by jesusjimsa** [comment]
Hello, @PhilippBaur.

You can download the package in a computer where you have internet connection and use the package in the server. You have a list with the link to download the latest Wazuh packages here: https://documentation.wazuh.com/3.13/installation-guide/packages-list/index.html

Let me know if you need more help.

Best regards.

**Comment by PhilippBaur** [comment]
Ok, thanks, I'll try to install everything!
