### ISSUE TITLE
ossec-analysisd: ERROR: Could not get group name. 

### ISSUE THREAD

**Issue by bebedard** [wazuh/wazuh#6233]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.13.1-1| ossec-analysisd | Manager | Packages/Sources | Debian 10 |

Hello team!

After upgrading from 3.12 I was unable to start wazuh-manager with active-response enabled.
Running ossec-analysisd with debug would return the following.

2020/10/07 16:25:01 ossec-analysisd[11183] debug_op.c:69 at _log(): DEBUG: Logging module auto-initialized
2020/10/07 16:25:01 ossec-analysisd[11183] analysisd.c:380 at main(): DEBUG: Starting ...
2020/10/07 16:25:01 ossec-analysisd[11183] analysisd.c:393 at main(): DEBUG: Found user/group ...
2020/10/07 16:25:01 ossec-analysisd[11183] active-response.c:71 at ReadActiveResponses(): ERROR: Could not get group name.
2020/10/07 16:25:01 ossec-analysisd[11183] config.c:261 at ReadConfig(): ERROR: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.
2020/10/07 16:25:01 ossec-analysisd[11183] analysisd.c:398 at main(): CRITICAL: (1202): Configuration error at '/var/ossec/etc/ossec.conf'.

I've tried to downgrade, install from package, sources, all would return the same error.

I've finally got it to work after moving the entries for the ossec group from the bottom to the top in /etc/group.
It seems if the /etc/group file is too big, it wont be able to fit it in the buffer for https://github.com/wazuh/wazuh/blob/c4f7457782312b7d81bf4563060e85e43ef737f7/src/config/active-response.c#L69

Cheers!

**Comment by davidjiglesias** [comment]
Hello @bebedard,

I am glad you got it to work, I'm moving the issue to R&D for our development team at Wazuh core. 

Thank you for using Wazuh and your contributions!

Best regards,

David J. Iglesias

**Comment by vikman90** [comment]
Hi @bebedard @davidjiglesias.

This issue is related to #4816, fixed by #4873. I will port that fix into the code related to this issue.

Thank you for reporting this bug.
Best regards.

**Comment by vikman90** [comment]
PR #6688 fixing this problem has been merged.

Let me close this issue. Thanks again.
Regards.
