### ISSUE TITLE
Not working Whodata in Windows 2016 

### ISSUE THREAD

**Issue by rulezz55** [wazuh/wazuh#6244]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13-2 | Syscheckd | Agent | Packages & Sources | W2016  |

in log:
2020/10/08 17:00:53 ossec-agent: ERROR: (6915): Audit policies could not be auto-configured due to the Windows version. Check if they are correct for whodata mode.
2020/10/08 17:00:53 ossec-agent: ERROR: (6916): Local audit policies could not be configured.
2020/10/08 17:00:53 ossec-agent: ERROR: (6710): Failed to start the Whodata engine. Directories/files will be monitored in Realtime mode

in ossec.conf:
  <syscheck>
    
    <disabled>no</disabled>

    
    <frequency>120</frequency>

    
    <directories recursion_level="0" check_all="yes" whodata="yes">c:/temp1</directories>

    
    
    <windows_audit_interval>60</windows_audit_interval>

    
    <process_priority>10</process_priority>

    
    <max_eps>100</max_eps>

    
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>1h</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>

in 
https://github.com/wazuh/wazuh/blob/254b7d9b0c0453d21ce2ed76ed740d6b87ef036b/src/syscheckd/win_whodata.c

I saw that auditpol is used, but when the interface is not English, Whodata does not work. For the test, I deployed W2016 ENG and it worked correctly. The audit is installed, but auditpol can't work correctly because the commands in Russian localization look different for it:
for example
auditpol /get /Category:"Система" 

Please help me figure out how to make the Whodata parameter work.

**Comment by rulezz55** [comment]
![image](https://user-images.githubusercontent.com/14849445/95492180-5e384f80-09a3-11eb-8cd9-392451ee17a0.png)

**Comment by 0xN3utr0n** [comment]
Hi @rulezz55 ,
Indeed, FIM right now doesn't support Cyrillic characters, which may cause unexpected behavior in certain scenarios. We've been aware of this for quite some time know (see  #4612, #4386), and I'm afraid to say there's no workaround for it other than using ASCII compatible languages, such as English. That being said, since many users have asked about adding `UTF-8` support, we've decided to include this issue into our short term roadmap #6194.
