### ISSUE TITLE
Need to rebuild the wazuh management server

### ISSUE THREAD

**Issue by frankfoti** [wazuh/wazuh#6255]
Are there recommendations on "cleaning up"  a broken installation of wazuh manage and api?  My client had som os level issues and many directiesis and files are missing from the wazuh/ossec homes.

Thanks

**Comment by bah07** [comment]
Hi @frankfoti 

You can try simply reinstalling the Wazuh package. The following command will keep the configuration you had.

Debian:
> sudo apt --reinstall install wazuh-manager

Centos:
> sudo yum reinstall wazuh-manager

You can use the `force` option to restore the default configuration. Tell me if it has worked correctly, otherwise I would recommend reinstalling it again.

Hope it helps. Regards.

**Comment by frankfoti** [comment]
hitting some errors:

[secvaladmin@wazuh-1 ~]$ su - root
Password:
Last login: Fri Oct  9 12:29:06 EDT 2020 on pts/0
Last failed login: Fri Oct  9 15:19:00 EDT 2020 on pts/0
There was 1 failed login attempt since the last successful login.
[root@wazuh-1 ~]# sudo yum reinstall wazuh-manager
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
Could not retrieve mirrorlist http://mirrors.elrepo.org/mirrors-elrepo.el7 error was
14: curl#6 - "Could not resolve host: mirrors.elrepo.org; Unknown error"
Could not get metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64&infra=stock&content=centos error was
14: curl#6 - "Could not resolve host: mirrors.fedoraproject.org; Unknown error"
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=updates&infra=stock error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
 * base: mirror.mia11.us.leaseweb.net
 * elrepo: ftp.icm.edu.pl
 * epel: epel.mirror.constant.com
 * extras: linux.cc.lehigh.edu
 * updates: mirror.siena.edu
http://ftp.osuosl.org/pub/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: ftp.osuosl.org; Unknown error"
Trying other mirror.
http://mirror.mia11.us.leaseweb.net/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.mia11.us.leaseweb.net; Unknown error"
Trying other mirror.
http://centos.s.uw.edu/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: centos.s.uw.edu; Unknown error"
Trying other mirror.
http://centos.mirror.constant.com/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: centos.mirror.constant.com; Unknown error"
Trying other mirror.
http://ftpmirror.your.org/pub/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: ftpmirror.your.org; Unknown error"
Trying other mirror.
http://mirror.atl.genesisadaptive.com/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.atl.genesisadaptive.com; Unknown error"
Trying other mirror.
http://mirror.san.fastserv.com/pub/linux/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.san.fastserv.com; Unknown error"
Trying other mirror.
http://yum.tamu.edu/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: yum.tamu.edu; Unknown error"
Trying other mirror.
http://mirror.ilumno.com/centos/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.ilumno.com; Unknown error"
Trying other mirror.
http://centos3.zswap.net/7.8.2003/os/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: centos3.zswap.net; Unknown error"
Trying other mirror.
https://artifacts.elastic.co/packages/7.x/yum/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: artifacts.elastic.co; Unknown error"
Trying other mirror.
http://mirror.pit.teraswitch.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: mirror.pit.teraswitch.com; Unknown error"
Trying other mirror.
http://ftp.osuosl.org/pub/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: ftp.osuosl.org; Unknown error"
Trying other mirror.
http://ftp.icm.edu.pl/pub/Linux/distributions/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: ftp.icm.edu.pl; Unknown error"
Trying other mirror.
http://hkg.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: hkg.mirror.rackspace.com; Unknown error"
Trying other mirror.
http://fedora.is/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: fedora.is; Unknown error"
Trying other mirror.
http://iad.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: iad.mirror.rackspace.com; Unknown error"
Trying other mirror.
http://syd.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: syd.mirror.rackspace.com; Unknown error"
Trying other mirror.
http://muug.ca/mirror/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: muug.ca; Unknown error"
Trying other mirror.
http://dfw.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: dfw.mirror.rackspace.com; Unknown error"
Trying other mirror.
http://ord.mirror.rackspace.com/elrepo/elrepo/el7/x86_64/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: ord.mirror.rackspace.com; Unknown error"
Trying other mirror.

**Comment by frankfoti** [comment]
We established a new vm for this effort so we can close this.

Thanks

**Comment by frankfoti** [comment]
We established a new vm for this effort so we can close this.

Thanks
