### ISSUE TITLE
XML entities don't seem to be handled properly in local file commands

### ISSUE THREAD

**Issue by ssigwart** [wazuh/wazuh#6260]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.1 | localfile  |Agent | Packages/Sources | Amazon Linux 2 |

Several years ago, I set up a rule like this:
```xml
<localfile>
  <log_format>command</log_format>
  <frequency>604800</frequency>
  <command>/usr/bin/yum --disableplugin=versionlock --debuglevel 2 --security check-update 2&gt;/dev/null | grep -P '(?&lt;! 0 packages) available$'</command>
</localfile>
```

I noticed that I haven't gotten that alert in a long time (1 or 2 years).

I think it actually winds up executing this:

```
sh -c /usr/bin/yum --disableplugin=versionlock --debuglevel 2 --security check-update 2&gt;/dev/null | grep -P '(?&lt;! 0 packages) available$'
```

However, if I change it to the following, it work, which is odd because it's not valid XML with the `>`.  I also couldn't do an exact translation of the above command because I could find no way to add the `<`.
```xml
<localfile>
  <log_format>command</log_format>
  <frequency>604800</frequency>
  <command>/usr/bin/yum --disableplugin=versionlock --debuglevel 2 --security check-update 2>/dev/null | grep '[0-9]* package(s).*available'</command>
</localfile>
```

**Comment by pereyra-m** [comment]
Hello @ssigwart !

I hope you are having a good day, sorry to hear you are having troubles.

Please tell me, this command you are sharing used to work in the past? If it's the case, have you upgraded your manager version? Or what else changed since you noticed it stop working?

I have performed a few tests myself. The use of the ">" symbol works as expected, and this isn't necessarily an invalid XML. Escaping this character is recommended, but not always mandatory ([Element Data](https://www.liquid-technologies.com/XML/EscapingData.aspx) for example). Any error in the **ossec.conf** file would be reported at startup and the agent couldn't continue.

Nevertheless, the "<" do generates a XML error, and some substitutions like these ones may not be working:
- \&lt;
- \&\# 60; 
- $'\x3c'  

The first one, for example, would be considered like more than one commands because of the **;** , the first one in background. 
Please, share more details about the time you did make it work.

I'll keep this issue open to investigate it more deeply.
Regards.

**Comment by pereyra-m** [comment]
### Update

@ssigwart , please consider this new comment and ignore my previous tests.
The team told me that the correct way to escape that character is **\\<**, so the command you are trying to execute would have to replace **\&gt**; with **>** and **\&lt;** with **\\<**.

Don't hesitate in writing us again if you are still having problems with this issue.
Regards.

**Comment by ssigwart** [comment]
Hi, @pereyra-m.  Thank you for looking into this.  The command used to work probably around 2 years ago.  We update Wazuh monthly and are on the most recent version as of yesterday.

I'm slightly confused by this.  `\<` and `\>` will cause the XML to be invalid.  It looks like Wazuh does some special handling to allow those though.  However, it seems to me like the XML should validate on any XML validator (like https://www.w3schools.com/xml/xml_validator.asp).  Also, it seems like at least `&gt;`, `&lt;`, and `&amp;` should be decoded prior to running the command.

**Comment by pereyra-m** [comment]
You are right, this file is not pure XML, and Wazuh makes some workarounds for these cases.
I understand your point, but currently, the characters are supported like \\< and >. I apologize if isn't properly documented.

Were you able to make it work this way?

**Comment by ssigwart** [comment]
Yes, I was able to get it work with `>` and I found an alternative to leave out `<` altogether.  It's just concerning that if someone put an ampersand in the command for an XML entity because they think it should be valid XML, they will unknowingly run the command in the background and then try to execute the entity as if it were a command.  Consider the following:
```xml
<command>/bin/mycommand &gt; /outputfile</command>
```

That will actually execute `gt` and `/outputfile` as if they are commands, which could be dangerous.

**Comment by pereyra-m** [comment]
Hello again @ssigwart !
Thank you for your time and suggestions to improve Wazuh.

The command configuration can only be performed accessing the **ossec.conf** file as root, so the possibility to run any arbitrary command is expected.
Nevertheless, this special character situation has not been detailed in the documentation and it has been reported in this issue: [https://github.com/wazuh/wazuh-documentation/issues/3036](https://github.com/wazuh/wazuh-documentation/issues/3036). These Wazuh configuration files aren't pure XML.

I apologize again about the inconveniences it may have caused.
We may close this issue if you agree.

Regards.

**Comment by ssigwart** [comment]
Thanks, @pereyra-m.  My personal opinion is that at least `&gt;`, `&lt;`, and `&amp;` should be converted to the `>`, `<`, and `&` because if someone intentionally used them, I would assume that they would expect that conversion.  However, this is not my project, so if that's not something the Wazuh team wants, you can close this.

**Comment by pereyra-m** [comment]
No problem @ssigwart!
This is important and we'll consider it in a future upgrade.
We'll leave this issue open for now as a feature request.

Regards.
