### ISSUE TITLE
[API] Run and update API integration tests in 4.0-RC3

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6269]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0-RC3 | API | Manager | Sources | Ubuntu 18.04 |

As part of the testing process for 4.0.0-RC3 we should run and possibly fix/update integration tests for the API, including RBAC. Please do so and post the results here.

Regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
| Working branch |
| - |
| [fix/6269-framework-integration-tests](https://github.com/wazuh/wazuh/tree/fix/6269-framework-integration-tests) |


# Status update
`error` field was added to every integration test. This could lead to some unexpected errors, but it should not take much to fix them.

**Comment by davidjiglesias** [comment]
Added change from https://github.com/wazuh/wazuh/issues/6271 in 4f632f2cc94c47a79f3f19e892746b552b6dafba

# Status update
`list_agents`, `list_nodes` and `list_groups` parameters have been renamed to `agents_list`, `nodes_list` and `groups_list`. This could lead to some unexpected errors, but it should not take much to fix them.
