### ISSUE TITLE
Consistency when removing agents: Agents-timestamp file

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh#629]
> /var/ossec/queue/agents-timestamp

Memory overlap when discarding the line which is going to be removed.
Reading and writting in the same segment.

Review and check for corrupted lines.

**Comment by vikman90** [comment]
The issue was not memory overlap but an incorrect comparison of the agent ID. For instance, deleting agent "102" would remove the timestamp of agents "102", "1020", "1021", "10200", etc.
