### ISSUE TITLE
ossec-agentd: ERROR: dbsync: cannot connect to syscheck: Connection refused

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#6294]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | agentd + syscheck | Agent | Packages | Fedora31* |

*(Detected on Fedora31, probably ocurrs in all Linux agents)

## Test definition:
- Upgrade from 3.12.0 to pre-release 4.0.0
- Manager: fedora31
- Agent: fedora31

Hello team,

Launching automatic upgrade tests for 4.0 we've detected a possible race condition that throws an error related with agentd and syscheck.

It seems that, if `ossec-syscheckd` ends before `ossec-agentd`, the second continues connection with the first and throws errors as it can not connect.

![image](https://user-images.githubusercontent.com/15269938/96105786-b8bd3880-0eda-11eb-80df-e87b00af6f94.png)

[Example of failed build on Jenkins.](https://ci.wazuh.info/blue/organizations/jenkins/Test_upgrade/detail/Test_upgrade/45667/pipeline/)
[
Plan text logs](https://gist.github.com/grg121/be35b8c80a0d4f729359390ab047ed21)

**Comment by DFolchA** [comment]
This issue is still happening in upgrades from 4.0.x and 4.1.x to 4.2.0.
[Failed Jenkins build](https://ci.wazuh.info/job/Test_upgrade/70888/console)
```
11:38:14  2021/05/31 09:37:22 ossec-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
11:38:14  
11:38:14  2021/05/31 09:37:22 ossec-agentd: ERROR: dbsync: cannot connect to syscheck: Connection refused (111)
11:38:14  
11:38:14  2021/05/31 09:37:22 ossec-agentd: ERROR: dbsync: cannot connect to syscheck: Connection refused (111)
11:38:14  
11:38:14  2021/05/31 09:37:22 ossec-agentd: ERROR: dbsync: cannot connect to syscheck: Connection refused (111)
11:38:14  
11:38:14  2021/05/31 09:37:22 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
```

**Comment by Dooque** [comment]
This ERROR massage has been changed to WARNING on 11/30/2020 in commit 7117f4.
