### ISSUE TITLE
Windows Defender Logs not wokring

### ISSUE THREAD

**Issue by jeniha** [wazuh/wazuh#6298]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| unknown | unknown | unknown | unknown | unknown |

Hi to all,
My issue is that:
Wazuh won`t grab logs from Windows Defender for exmaple:
when i turn off Real-time protection i cant see it in logs into wazuh, also when is scan a file and cant see is it a clean file.
Can you help me?

**Comment by jnasselle** [comment]
Hi @jeniha ! In order to figure out where the problem is, could you please fill the table in the issue description with the information about your Wazuh installation? This will really help us.

**Comment by jeniha** [comment]
I use .ova image  and install new agent to new virtual machine with windows 10 for testing.
In ossec.conf in agent folder in Windows i put this code:
<localfile>
    <location>Microsoft-Windows-Windows Defender/Operational</location>
    <log_format>eventlog</log_format>
</localfile>
And in Security events event in web interface in wazuh cant show event from stoping Real-Time Proteciton or starting back up, even when find some virus there is no events from Defender.

**Comment by jeniha** [comment]
Fixed: 
<localfile>	
    <location>Microsoft-Windows-Windows Defender/Operational</location>	
    <log_format>eventchannel</log_format>	
  </localfile>

Victor Rebollo helps me in Slack

**Comment by jnasselle** [comment]
Great news! 
Despite both eventlog and evenchannel are supported by Wazuh, like the [documentation mention](https://documentation.wazuh.com/3.13/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html), use Eventchannel for Windows Vista and later versions.

Regards,
