### ISSUE TITLE
Change any for the real IP

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#630]
Hello team, as we discussed with @mgmacias95 on https://github.com/wazuh/wazuh-api/issues/74, we concluded this issue should be here, so here we go. Read https://github.com/wazuh/wazuh-api/issues/74 to have more information.

Regards,
Jesús

**Comment by jesuslinares** [comment]
This is really interesting.
It would be great to store 2 IP addresses:

- Registration IP: 'any' or a real IP.
- Last IP: The last real IP known for that agent. This will change if the agent is behind a DHCP. 
  - If the agents are behind a Load Balancer, we will see the same IP for all the agents.

**Comment by jesusgn90** [comment]
Duplicated: https://github.com/wazuh/wazuh/issues/2199
Closing this ticket
