### ISSUE TITLE
Add a new column to the agent table of global.db to reflect the agents' connection status

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6302]
## Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) is required to have some new data in the `global.db` database. We need to save information about the connection status of the agents. So, a new column in the `agent` table must be added.

## Requirements

- Column specs
  - **Name**: connection_status
  - **Datatype**: TEXT
  - **Allowed values**: `never_connected`, `pending`, `active` and `disconnected`.
- The default value of the column must be `never_connected` so that is not necessary to modify the agent insertion logic.
- A constraint must be defined to block any attempt of adding a different value.
- A new schema for upgrade must be created in order to upgrade from v1 to v2. In this case, the column value must be set to `disconnected` for all the agents in the `agent` table that has a value set in `last_keepalive`.
- The manager should be set always as `active`.

## Tests required

- [x] Update all the necessary Wazuh DB integration tests in order to check the column default value.
- [x] Manual test of manager upgrade to verify the column addition. Repeat the test with 3.9 and 3.10. In 3.9 is expected to get the database removed and regenerated. For 3.10 and above the upgrades to V1 and V2 should be applied.

## Definition of done

- [x] Code review approved.
- [x] Tests developed, executed, and passing successfully.

**Comment by pereyra-m** [comment]
### Update

The new column was added, and a new **wazuh/src/wazuh_db/schema_global_upgrade_v2.sql** was created.

The following upgrade scenarios were tested, the agents and the manager received the expected status:
- Wazuh V3.10: The upgrade successfully performs the V0->V1 and V1->V2 upgrades
- Wazuh V4.0: The upgrade successfully performs the V1->V2 upgrade

**Comment by DProvinciani** [comment]
Closing the issue as the PRs https://github.com/wazuh/wazuh/pull/6316 and https://github.com/wazuh/wazuh-qa/pull/908 were merged.
