### ISSUE TITLE
Agent's disconnection and alerts management by monitord

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6306]
## Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) is required to improve the agents' disconnection management and the alerts generated from monitord.

## Requirements

- The logic implemented in the thread that periodically monitors the agents in monitord should be modified.
- The thread will now have 3 time counters:
    - `agents_disconnection_time`: When this counter is triggered, the thread makes a call to Wazuh DB to execute the `disconnect_agents` command created in the [Issue 6345](https://github.com/wazuh/wazuh/issues/6345). The list of agents that were set as disconnected and returned by the command must be saved in memory.
    - `agents_disconnection_alert_time`: The list of agents that were set as disconnected and now lives in memory must be iterated and a call to Wazuh DB with the command `get-agent-info` must be done. Each agent should be verified whether is still disconnected and if so, compare the `last_keepalive` with the current time and the alert generation time to determine if an alert must be generated to report the disconnection. If the alert is generated, the agent is removed from the list. If the agent is no longer disconnected and is active, no alert should be generated and the agent should be also removed from the list in memory. The remaining list of agents that were set as disconnected but not yet alerted, must keep it in memory and be verified in the next iteration.
    - `monitor_delete_old_agentes`: This counter will ask Wazuh DB for the agents in `disconnected` status. Then, will iterate the list checking whether the agent should be removed.
- If possible, and if it is not in a separate thread, add the counter for the log rotation within the same logic.

## Tests required

- [x] 100% of unit test coverage for all the new and modified methods in monitord. (considering the volume of the unit tests required, this was separated into a new issue. https://github.com/wazuh/wazuh/issues/6458)
- [x] Manual test case of monitord by connecting and disconnecting agents to verify the connection status in Wazuh DB and alerts generation.
- [x] Manual test case of monitord by changing the system time to verify the log rotation.

## Definition of done

- [x] Code review approved.
- [x] No `scan-build` errors.
- [x] 0 memory leaks reported by Valgrind on UT and monitord.
- [x] Tests developed, executed, and passing successfully.

**Comment by pereyra-m** [comment]
### Tests

The scan build analysis does not report any new issue.
The **monitord** daemon was tested with Valgrind during the normal use (agent's disconnection, alerts, deleting old agents) and any memory leak was produced. There are only "still reachable" blocks related to the closing threads 

![monitord_valgrind](https://user-images.githubusercontent.com/65046601/97727358-13e05500-1aaf-11eb-8c21-28e440fe298b.png)
 
The following functionalities were tested, with many agents in different order:
- The disconnection alert
- The old agents removal
- The correct adding and deletion in the Hash Table

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/6465 was merged.
