### ISSUE TITLE
Refactor framework to connect to rootcheck DB

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#6307]
Based on https://github.com/wazuh/wazuh/issues/6096

## Description

The rootcheck module has been refactored to store all agent logs in the agent DB through Wazuh DB.

It is necessary to reimplement the following API endpoints:

- `DELETE /rootcheck` -> Delete rootcheck information. Should include a list of agents.

- `GET /rootcheck/{agent_id}` -> Retrieve rootcheck results of an agent.

- `GET /rootcheck/{agent_id}/last_scan` -> Retrieve rootcheck last scan information of an agent.

- `PUT /rootcheck` -> Run rootcheck scan. Should include a list of agents.

**Comment by davidjiglesias** [comment]
To be done in https://github.com/wazuh/wazuh/issues/6329
