### ISSUE TITLE
Add new global settings for the agent disconnection time

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6310]
## Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) the agents' connection monitoring is being improved. Having said that, two new settings are necessary for **monitord** to determine the time after which an agent is considered as disconnected and the time after which an agent disconnection alert should be generated.

## Requirements

- The new setting must be add withing the `<global>` tag because multiple daemons may need this data.
- A setting called `agents_disconnection_time` must be created with a default value of `20` seconds to configure the time after which an agent will be set as disconnected in the database.
- A setting called `alert_agent_disconnection_time` must be created with a default value of `2` minutes to configure the time after which an agent disconnection alert should be generated.
- Make sure that the method `getMonitorOptions` includes the new settings.
- Modify all the places where `DISCON_TIME` is used in **monitord** and **remoted** and make use of the value configured in this new setting. The definition of `DISCON_TIME` shouldn't be removed as part of this issue because it will still be used by **Vulnerability Detector** and the **read-agents.c** code. The definition will be removed as part of the [Issue 6311](https://github.com/wazuh/wazuh/issues/6311).
- The documentation should be modified in order to include this new setting.

## Tests required

- [x] Update unit test coverage for all the modified methods if required. (It was not required)
- [x] Manual testing of remoted to verify that the `AR_Forward` thread behaves as expected.

## Definition of done

- [x] Code review approved.
- [x] No `scan-build` errors.
- [x] 0 memory leaks reported by Valgrind on UT and remoted.
- [x] Tests developed, executed, and passing successfully.

**Comment by pereyra-m** [comment]
### Manual tests performed

The following cases were tested:
- Without adding the **alert_agent_disconnection_time** setting, its 2 minutes default value generates a disconnection alert
- The **alert_agent_disconnection_time** has to be a valid number greater than 2

**Comment by DProvinciani** [comment]
Closing the issue as the PRs https://github.com/wazuh/wazuh/pull/6412 and https://github.com/wazuh/wazuh-documentation/pull/3079 were merged.
