### ISSUE TITLE
Requesting logs using the API ends on "'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#632]
Hello team, on a random way, it means not always, I'm obtaining an error requesting the manager logs from the Wazuh API:

```
/manager/logs
{
  offset: 55
  limit: 15
}


Wazuh-Python Internal Error: 'NoneType' object is not iterable
```

Once done, you could execute again the same request and it's fine, it doesn't appear always.
Thanks in advance.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Additionally:

One scenario you could reproduce it easy is using excesive offset:

```{"method":"GET","path":"/manager/logs","body":{"offset":10000}}```

Other routes such /agents give us an empty array whenever I request using excesive offset.

Also this issue is not related only to excesive offset, whenever I've seen the error, I've been using low offset such  `offset: 55` and having ~3000 remaining items.

Regards,
Jesús

**Comment by mgmacias95** [comment]
Hello @jesusgn90,

This bug is caused when a logline doesn't match the following regex:

https://github.com/wazuh/wazuh/blob/08db4db58ad8ae7b8a4fc5f484129200157f002b/framework/wazuh/manager.py#L46-L49

For example, the following log causes the bug:
```
2018/05/21 11:22:55 ossec-logcollector: DEBUG: Running full command 'netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d'
2018/05/21 11:22:55 ossec-logcollector: DEBUG: Running full command 'last -n 20'
2018/05/21 11:22:55 ossec-logcollector: DEBUG: Reading command message: 'ossec: output: 'last -n 20':
root     pts/2        192.168.56.1     Mon May 21 11:21   still logged in
root     pts/2        192.168.56.1     Mon May 21 11:20 - 11:20  (00:00)
root     pts/2        192.168.56.1     Mon May 21 11:19 - 11:19  (00:00)
root     pts/2        192.168.56.1     Mon May 21 11:18 - 11:19  (00:01)
root     pts/2        192.168.56.1     Mon May 21 11:16 - 11:16  (00:00)
root     pts/2        192.168.56.1     Mon May 21 11:16 - 11:16  (00:00)
root     pts/2        192.168.56.1     Mon May 21 11:15 - 11:16  (00:00)
root     pts/1        192.168.56.1     Mon May 21 11:06   still logged in
root     pts/0        192.168.56.1     Mon May 21 11:06   still logged in
reboot   system boot  3.10.0-693.21.1. Mon May 21 11:05 - 11:22  (00:17)
reboot   system boot  3.10.0-693.21.1. Mon May 21 11:05 - 11:05  (00:00)
root     pts/1        192.168.56.1     Mon May 21 11:04 - crash  (00:00)
root     pts/0        192.168.56.1     Mon May 21 10:55 - crash  (00:10)
wazuh    tty1                          Mon May 21 10:51 - 11:04  (00:13)
reboot   system boot  3.10.0-693.21.1. Mon May 21 10:50 - 11:05  (00:14)
root     pts/0        192.168.56.1     Mon May 21 08:56 - crash  (01:53)
reboot   system boot  3.10.0-693.21.1. Mon May 21 08:56 - 11:05  (02:08)
root     pts/2        192.168.56.1     Sat May 19 18:10 - 18:10  (00:00)
root     pts/2        192.168.56.1     Sat May 19 17:53 - 17:53  (00:00)
root     pts/2        192.168.56.1     Sat May 19 17:51 - 17:52  (00:01)

wtmp begins Thu May  3 17:25:47 2018'
```

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello again @jesusgn90,

This bug has been solved in https://github.com/wazuh/wazuh/pull/644.

The solution implemented is to consider those logs as "multiline". If a logline doesn't match expected format, it is added to the previous logline:

https://github.com/wazuh/wazuh/blob/30a5856048edd2182982aa9872d782d65598fc7f/framework/wazuh/manager.py#L119-L120

Best regards,
Marta

**Comment by jesusgn90** [comment]
Great, now it's time to adapt the new format on the App logs section, but really appreciate this.

Regards,
Jesús
