### ISSUE TITLE
Fim registry improvement unit tests, tests for fim_db reestructuration

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#6340]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Syscheck | Agent | Sources | Windows |

## test_fim_db, test_fim_db_files and test_fim_db_registries

After the changes of the Fim registry improvement, it is necessary to remake the original test_fim_db file tests, to adapt to news directories in syscheck. 
Restructure all the tests necessary to check all functions.

**test_fim_db**

**test_fim_db_files**

**test_fim_db_registries**

**Comment by Molter73** [comment]
Coverage before starting to develop the new tests:
![imagen](https://user-images.githubusercontent.com/20206636/97008655-649dfe00-1543-11eb-8f18-2ac88bf8ff04.png)
