### ISSUE TITLE
Fim registry improvement unit tests, test_syscheck_op file modify

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#6342]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Syscheck | Agent | Sources | Windows |

## test_syscheck_op

After the changes of the Fim registry improvement, it is necessary to modify some of the tests related to the following functions:
- get_user
- remove_empty_folders

**Comment by jesusjimsa** [comment]
These functions also need unit testing:
* `get_registry_group`
* `get_registry_permissions`
* `get_registry_mtime`

**Comment by jesusjimsa** [comment]
### get_registry_group

- [ ] get_registry_group_GetSecurityInfo_fails
- [ ] get_registry_group_ConvertSidToStringSid_fails
- [ ] get_registry_group_LookupAccountSid_fails
- [ ] get_registry_group_LookupAccountSid_not_found
- [ ] get_registry_group_success

### get_registry_permissions

- [ ] get_registry_permissions_RegGetKeySecurity_insufficient_buffer
- [ ] get_registry_permissions_RegGetKeySecurity_fails
- [ ] get_registry_permissions_GetSecurityDescriptorDacl_fails
- [ ] get_registry_permissions_GetSecurityDescriptorDacl_no_DACL
- [ ] get_registry_permissions_GetAclInformation_fails
- [ ] get_registry_permissions_GetAce_fails
- [ ] get_registry_permissions_success

### get_registry_mtime

- [ ] get_registry_mtime_RegQueryInfoKeyA_fails
- [ ] get_registry_mtime_success

**Comment by jesusjimsa** [comment]
I have updated the tests I created last week using the new `expect_*` functions to encapsulate `will_return`, `expect_string` and `expect_value` in a function call. The already present (but declared in another test) `expect_*` functions have been moved to the _wrappers_ folder.
I have also added a missing call to the `GetLastError` wrapper in the tests I wrote last week.
Now, I will finish writing tests for `get_registry_group` and I will define the different tests that need to be added about `get_user` and `remove_empty_folders`.

**Comment by jesusjimsa** [comment]
I have fixed now the tests for `get_user` and `remove_empty_folders`. I have renamed the `get_user` tests to `get_file_user` and I will not create tests for `get_registry_user` because all it does is call `get_user` and that is already tested in the `get_file_user` tests.
I will fix now the `get_user` tests for Linux and this issue should be ready to create a pull request.
