### ISSUE TITLE
Fim registry improvement unit tests, test_wdb_parser and test_wdb_fim file modify

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#6343]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Syscheck | Agent | Sources | Linux |

## test_wdb_parser and test_wdb_fim

After the changes of the Fim registry improvement, it is necessary to modify some of the tests related to the following functions:
- wdb_parse_syscheck
- wdb_fim_insert_entry2
- wdb_syscheck_save2
- __wrap_sqlite3_step

**Comment by jesusjimsa** [comment]
Right now, I am fixing the already existing unit tests for `wdb_fim` and `wdb_parser` but I am seeing that we will need to add some more tests that don't exists right now. I will define these new tests in a comment here after everything is fixed and passing.

**Comment by jesusjimsa** [comment]
I have fixed now all the already present tests, I am going to prepare some tests for the new `registry_value` section of the `wdb_fim_insert_entry2` function.

https://github.com/wazuh/wazuh/blob/074743c1b215070f8e2109db3c1ee64c593667af/src/wazuh_db/wdb_fim.c#L533-L578

**Comment by jesusjimsa** [comment]
## wdb_fim_insert_entry2 tests for registries

* `test_wdb_fim_insert_entry2_registry_arch_null`
* `test_wdb_fim_insert_entry2_registry_value_name_null`
* `test_wdb_fim_insert_entry2_registry_item_type_null`
* `test_wdb_fim_insert_entry2_registry_value_succesful`

**Comment by jesusjimsa** [comment]
I have added now all the tests for the new registry code in _wdb_fim.c_. Next week, I will fix the unit tests for wdb_parser and it will be ready to create a pull request.
