### ISSUE TITLE
Cannot add more than one s3 bucket in ossec.conf (no logs are parsed for the buckets besides the first bucket specified)

### ISSUE THREAD

**Issue by antonisnyc94** [wazuh/wazuh#6370]
Hello,

I recently changed the aws-s3 module to a different wazuh node and now I only receive events from the first bucket specified in the aws-s3 wodle.

I have the below configuration, and to give a better understanding on what happens, Im only receiving events for cloudtrail, if i change the order and I put guardduty first, then i will  only receive for guardduty and so forth; 

![image](https://user-images.githubusercontent.com/36517441/96760377-e6a4f000-13a6-11eb-83e7-18f6f988d526.png)

I dont see any errors in the logs:
![image](https://user-images.githubusercontent.com/36517441/96759973-beb58c80-13a6-11eb-80da-7bf917a78e4e.png)

Thanks a lot!

**Comment by CarlosRS9** [comment]
Hello,

This is an strange behaviour that I must check but to do so I need to know which Wazuh and Wazuh API version you had in the previous node (I'm assuming the module was working fine in that module until you move it to another module) and also which version you are using in the current node.


Additionally, I suggest you to enable debug mode for the AWS module so we can see more information in the logs. You can enable it by adding the following line to the `{wazuh_path}/etc/local_internal_options.conf` and then restarting the wazuh service:
```
wazuh_modules.debug=2
```
Check the logs again after enabling the debug mode. With this information I may be able to see if there is any issue related to the module.

**Comment by antonisnyc94** [comment]
The strangest things of all, is that I moved the task back to the original node and the same thing was occurring. At this point I am having each bucket to a different node in order to get by until we solve this.


All nodes are having the version 3.13.2 for wazuh-manager and api.

I changed everything back to the configuration I had above and now for  an extremely weird reason it parses the cloudtrail events along with the config events but still not the guarmountdduty events. I attached the log file with the aws related tasks in this thread. Please let me know if you need anything else. 

[aws.txt](https://github.com/wazuh/wazuh/files/5423803/aws.txt)

**Comment by CarlosRS9** [comment]
Hello @antonisnyc94 ,

I was working on this issue trying to replicate it but I am not able to do so. I used the same configuration you shared but the AWS module worked just fine for me.

I checked the log you attached but I didn't find anything related to this issue. The only strange thing I saw was that for some reason it seems the AWS module didn't run for `GuardDuty`, only for `CloudTrail` and `Config`.

Could you please make sure there are logs available for GuardDuty in that bucket? I noticed for `GuarDuty` you specified a `path`. Could you please make sure that path is the right one?

Also, please take into account that you are not using the `only_logs_after` parameter, so by default when the AWS module runs it will use the current date as the value for `only_logs_after` which means logs from previous days will be skipped.

Finally, as I need more information to be able to replicate this issue try to enable `logall` option in your `{wazuh_path}/etc/ossec.conf` by setting it to `yes`. You will find this option at the begining of the `global` configuration. Keep the debug mode enabled too. Once logall is enabled restart the wazuh service, wait a few minutes and send me your `{wazuh_path}/logs/archives/archives.log` and your ossec.log. Maybe I can find something there that explains this behaviour. Remove from those files any sensitive information, specially from the archives.log file.

**Comment by antonisnyc94** [comment]
Hey Carlos,

The details you gave you me are extremely useful for troubleshooting, especially for future scenarios. After another 2 restarts of the service, it picks up everything (thankfully but it is kind of troublesome because we didn't find the root cause). I"ll close the ticket for now and will follow your steps in the future if it occurs again.

Thanks again!
