### ISSUE TITLE
[Development v4.0] Permissions error when re-registering an agent

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh#6372]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0-40004 | agent_auth | Agent | Sources | CentOS 7 |

Hi team,

I just faced this weird behavior when re-registering an agent. First of all, it was successfully registered by `auto-enrollment`, after that, the elimination of the agent was manually provoked so it could be re-registered using `agent-auth`. The result is a permissions error that blocks the agent initiation. 

## Description

- CentOS agent in Active status, registered by the auto-enrollment method. 

![image](https://user-images.githubusercontent.com/10210567/96769858-ff7dc780-13df-11eb-8e88-e5a54a3bd876.png)

- Master auth configuration:

![image](https://user-images.githubusercontent.com/10210567/96770245-82068700-13e0-11eb-8d14-6d57ae956280.png)

### Steps to reproduce

1. Manually proceed to remove the agent using `manage_agents` binary:

![image](https://user-images.githubusercontent.com/10210567/96769933-20461d00-13e0-11eb-814d-46184a26d8c9.png)

2. Stop the agent and manually remove the `client.keys` file

![image](https://user-images.githubusercontent.com/10210567/96770042-453a9000-13e0-11eb-8020-0fbcf45a1dd0.png)

3. Disable autoenrollment and re-register the agent using `agent_auth`:

![image](https://user-images.githubusercontent.com/10210567/96770467-c2660500-13e0-11eb-8019-5e7c49c5e7d9.png)

- Manager log

![image](https://user-images.githubusercontent.com/10210567/96770496-cb56d680-13e0-11eb-9d38-9a4f99e210a1.png)

4. Restart the agent, an error is returned. Agent's logs:

![image](https://user-images.githubusercontent.com/10210567/96771234-af076980-13e1-11eb-8f98-27195dcffd78.png)

### Conclussion

After checking the permissions of the `client.keys` using both methods auto-enrollment and by `agent-auth` , it's been confirmed that the owner changes using `agent-auth` so the `agentd` daemon is not able to read from it.

![image](https://user-images.githubusercontent.com/10210567/96789093-d0258580-13f4-11eb-9737-60f5af3d9833.png)

Regards

**Comment by palaciosjeremias** [comment]
When client.keys is created by **enrollment_op.c**, **TempFile()** copies the permissions from existent src file (original client.keys). 
If the src file doesn't exist, the new file will only have owner permissions.
If the file is created by agentd during autoenrollment, the owner will be ossec, and will be no permission issues.
If the file is created by agent-auth, the owner is root, and ossec group will not have read permissions over the file.

**Comment by palaciosjeremias** [comment]
Issue fixed on https://github.com/wazuh/wazuh/pull/6377
