### ISSUE TITLE
Bitdiffender API integration

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6378]
We would like to Integrate the cloud-based Bitdefender antivirus with Wazuh. They have provided the API integration steps but specifically for Splunk tool. 

Can we integrate the same with Wazuh? if yes. Cloud you give us the more detail about that?

Integration reference link provided by Bitdefender team as below

https://download.bitdefender.com/business/API/Bitdefender_GravityZone_Cloud_APIGuide_forCustomers_enUS.pdf

https://www.bitdefender.com/support/how-to-integrate-gravityzone-cloud-platform-with-splunk-2152.html

**Comment by 0xN3utr0n** [comment]
Hi @VisakhMV-Coder ,
It depends on the type of integration you want to implement, but a basic one should be possible.

- **Input data integration**:
Wazuh can read and parse any json log file specified by the `<localfile>` section. ([docu](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/localfile.html?highlight=log_format)) 
```
<localfile>
  <location>/var/log/myapp/mylog.json</location>
  <log_format>json</log_format>
</localfile>
```
- **Output data integration:**
Using [integratord](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/), a module which allows to run scripts(python, bash... you name it) when certain events get matched. Take for instance the integration with [VirusTotal](https://wazuh.com/blog/emotet-malware-detection/).

**Comment by Ramsiyahassan2021** [comment]
Do you know any tools / applications which can pull logs from any source (say bitdefender) save it as text files or databases and then Wazuh can pull data from them and Is there any endpoint to receive the logs from bitdefender?
