### ISSUE TITLE
Agent approves invalid remote settings

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh#638]
The agent.conf configuration is validated like the manager in the agent side. This can stop processes like modulesd when the agent restarts because no errors are found in the sended configuration.

**Comment by vikman90** [comment]
This issue is a false positive: if an agent gets an unknown module defined:
```
2018/06/15 09:52:39 wazuh-modulesd: ERROR: Unknown module 'testmodule'
```

However, a bug has been found when discarding invalid configuration.
