### ISSUE TITLE
Add queries to retrieve rootcheck information

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#6389]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.1 | wazuh-modulesd | Manager |

Wazuh DB now stores all the rootcheck information in real time.

We need to add new queries to retrieve the following information:

- All the rootcheck entries for a given agent ID.

- Last rootcheck scan time for a given agent ID.

**Comment by nicolaspapp** [comment]
This issue is no longer needed, since it will be handled by the API.
