### ISSUE TITLE
Document how to do file integrity monitoring with locked audit rules

### ISSUE THREAD

**Issue by kpinc** [wazuh/wazuh#6391]
|3.13.2|syscheck|?|?|Ubuntu 18.4.5|

Enhancement request.

We are using wazuh-agent 3.13.1-1, on Ubuntu 18 using the cloud Wazuh service.

The DSS PCI rules suggest locking the auditd rules with "-e 2".  But
if you do this then the FIM monitor cannot write auditd rules to audit
files.  The documentation should describe the proper way to use FIM
monitoring when the auditd rules are locked.

**Comment by jesusjimsa** [comment]
I'm closing this issue as it is a duplicate of #6393.
