### ISSUE TITLE
Windows Wazuh Agent security related issue.

### ISSUE THREAD

**Issue by jakko10** [wazuh/wazuh#6399]
|Wazuh version|Component|Install type|Install method|Platform|
|Wazuh-Agent 2.8.5-to-latest|Wazuh-Agent 2.8.5-to-latest|MSI|any|Windows 10|

There is a vertical privilege escalation flaw in the client. Should I disclose it here?

**Comment by snaow** [comment]
Hi @jakko10,

You can reach me (@snaow) and the team in our Slack workspace https://wazuh.com/community/join-us-on-slack/.
Let's discuss there and publish here the results later, just in case it can really impact other users.

Is it related to https://github.com/wazuh/wazuh/issues/4348 ?

Thanks for the help and contributions.

**Comment by vikman90** [comment]
Hi @jakko10 @snaow.

Closing this issue as it was fixed by #3593 
Best regards.
