### ISSUE TITLE
OpenSCAP Version dependency

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh#64]
the SCAP rules currently included with wazuh (e.g. ssg-debian-8-ds.xml) require at least OVAL Version 5.11.

Debian jessie includes "1.0.9-1+b2", which only supports OVAL version 5.10.1, causing this errors like this:
```
File '/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml' line 1835: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#linux}systemdunitdependency_test': This element is not expected.
```

Version `1.2-1jessie` of `wazuh-agent` and `wazuh-manager` depend on `libopenscap8`, it would be better if the wazuh packages would only recommend/suggest `libopenscap8` in the appropiate version (>= 1.2.4) if the openscap package is not necessary to run wazuh.

**Comment by jesuslinares** [comment]
Hi hex2a,

thanks for reporting us the issue. We are improving the packages and trying to solve compatibility issues. New packages will not include _openscap_ package as dependency, the user must install _openscap-scanner_ separately if he needs to use the integration.

Regards.

**Comment by hregis** [comment]
Hello @jesuslinares 

The problem is still current on Jessie!
How to remedy the problem?

Thanks

**Comment by hex2a** [comment]
unfortunately, the open-scap version in Jessie is too outdated to support OVAL 5.11.
https://tracker.debian.org/pkg/openscap

This should be fixed in stretch, although there is a missing build-dependency, preventing systemd services from being checked/causing the checks to fail.
If you build your own package, I recommend applying the patch from the bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826943

**Comment by hregis** [comment]
my solution work with Jessie...

aptitude install git make libdbus-1-dev libgconf2-dev libacl1-dev libblkid-dev libcap-dev libcurl4-gnutls-dev libgcrypt20-dev libselinux1-dev libxml2-dev libxslt1-dev libldap2-dev libpcre3-dev libxml-parser-perl libxml-xpath-perl libperl-dev swig  libpython-dev libbz2-dev libapt-pkg-dev librpm-dev dpkg-dev libdpkg-dev
git clone https://github.com/OpenSCAP/openscap.git
cd openscap
./autogen.sh
./configure
make
make check
aptitude purge libopenscap8
make install
aptitude install libopenscap8
service wazuh-agent restart

**Comment by jesuslinares** [comment]
It is failing in the "make check" step:

```
============================================================================
Testsuite summary for openscap 1.2.15
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[6]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/schema_version'
make[5]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/schema_version'
make[4]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/schema_version'
Making check in report_variable_values
make[4]: Entering directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
make  check-TESTS
make[5]: Entering directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
make[6]: Entering directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
FAIL: all.sh
make[7]: Entering directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
make[7]: Nothing to be done for 'all'.
make[7]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
============================================================================
Testsuite summary for openscap 1.2.15
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/API/OVAL/report_variable_values/test-suite.log
Please report to open-scap-list@redhat.com
============================================================================
Makefile:1156: recipe for target 'test-suite.log' failed
make[6]: *** [test-suite.log] Error 1
make[6]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
Makefile:1262: recipe for target 'check-TESTS' failed
make[5]: *** [check-TESTS] Error 2
make[5]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
Makefile:1335: recipe for target 'check-am' failed
make[4]: *** [check-am] Error 2
make[4]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL/report_variable_values'
Makefile:1332: recipe for target 'check-recursive' failed
make[3]: *** [check-recursive] Error 1
make[3]: Leaving directory '/home/wazuh/openscap/tests/API/OVAL'
Makefile:995: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/wazuh/openscap/tests/API'
Makefile:1005: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/wazuh/openscap/tests'
Makefile:1274: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1
```

Also, it is no a good idea to install a lot *-dev packages in a production agent. We will try to reach out the OpenSCAP team to review the package for Jessie...

Thanks for the feedback.
