### ISSUE TITLE
SQLite-related timeouts and failures

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh#6401]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.13.2| Wazuh API | Manager | Packages | Ubuntu 18.04  |

Seeing strange behavior on one of the test systems for 3.13.2.
The API appears to time out and stall throwing messages like
```
Agents. groups.data is undefined
```
and
```
Could not connect to API with id: production: 3005 - Maximum attempts exceeded for sqlite3 execute
```
the API logfile is full of:
```
WazuhAPI 2020-10-23 07:41:13 wazuhadmin: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-10-23 07:41:32 wazuhadmin: [::ffff:127.0.0.1] GET /agents/?offset=0&limit=25&q=id!%3D000&sort=%2Bid - 200 - error: '0'.
WazuhAPI 2020-10-23 07:41:54 wazuhadmin: [::ffff:127.0.0.1] GET /agents/005? - 200 - error: '0'.
WazuhAPI 2020-10-23 07:41:57 wazuhadmin: [::ffff:127.0.0.1] GET /agents/groups? - 200 - error: '2003'.
WazuhAPI 2020-10-23 07:41:58 wazuhadmin: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '0'.
WazuhAPI 2020-10-23 07:45:06 wazuhadmin: [::ffff:127.0.0.1] GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '2002'.
WazuhAPI 2020-10-23 07:45:07 wazuhadmin: [::ffff:127.0.0.1] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2020-10-23 07:45:33 wazuhadmin: [::ffff:127.0.0.1] GET /agents/005? - 200 - error: '2002'.
WazuhAPI 2020-10-23 07:45:39 wazuhadmin: [::ffff:127.0.0.1] GET /manager/info? - 200 - error: '2002'.
```
Seems... odd, given that other instances appear to run fine.

**Comment by CarlosRS9** [comment]
Hello @sempervictus

That's indeed an odd behaviour. It seems for some reasons your global.db file is locked, so queries ẁon't be able to be executed.

Please try to remove your `global.db` file and then restart the wazuh service. You can remove it by using the following command:
```
rm -rf {wazuh_path}/var/db/global.db*
```

Replace `{wazuh_path}` with your installation path. By default its `/var/ossec`.



Once you have remove this try to test if this issue happens again. Also, please run the following command and check for any errors:

```
curl -u foo:bar -k "https://localhost:55000/agents/groups?pretty"
```

Replace `foo:bar` with your API credentials and `localhost:55000` with the IP and PORT of the machine where API is located.


Finally, please share with us the following information:


- The Wazuh API version you are using. It should be the same as the Wazuh version (3.13)

- When this error ocurred? Were you using the Wazuh APP or the Wazuh API manually?



With this information I may be able to help you further.

**Comment by davidjiglesias** [comment]
Close due to inactivity.
