### ISSUE TITLE
Letsencrypt Certificate

### ISSUE THREAD

**Issue by WizardKid** [wazuh/wazuh#6413]
I am aware it must be tremendous job in getting this project to where it is today. I love this platform and willing to support the future of it, however the task of getting it up and running is the tedious and even upon with the all-in-one script - it failed after a day of running due to SSL issues.
Wouldn't it be much easier implementing letsencrypt into the unattended script to make it much easier? I have reinstall this project over 5 times and on to my 6th. The SSL failed and installing letsencrypt on this platform is a nightmare

**Comment by davidfmiranda** [comment]
Hello @WizardKid, the script generates self-signed certificates that should work without any modifications. If you are having troubles with them, I'll be glad to help you. Could you share which OS are you using? in addition, could you share your `/etc/kibana/kibana.yml` file? 

Regards, 

David

**Comment by WizardKid** [comment]
Hi my OS is CentOS 8 and the kibana.yml cont is `server.host: 0.0.0.0
server.port: 443
elasticsearch.hosts: https://localhost:9200
elasticsearch.ssl.verificationMode: none
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opendistro_security.multitenancy.enabled: false
opendistro_security.readonly_mode.roles: ["kibana_read_only"]
server.ssl.enabled: true
server.ssl.key: "/etc/kibana/certs/kibana.key"
server.ssl.certificate: "/etc/kibana/certs/kibana.pem"
server.defaultRoute: /app/wazuh/
` whenever i restart the server, I have to delete the certificate in the browser so that I can access the website again

**Comment by davidfmiranda** [comment]
Hello @WizardKid, I've been trying to replicate this behavior and I haven't been able to reproduce it. Could you share the steps you did to install the environments?

Regards,

David

**Comment by WizardKid** [comment]
This instance was installed using the all-in-one installation script. It is working now however, each time I tried installing Letsencrypt - it crashes. There are no instructions in your documentation to install letsencrypt so therefore maybe the pem,crt or key is pointing elsewhere.

**Comment by davidfmiranda** [comment]
Hello @WizardKid, I'm glad it is working now. This script is prepared to use self-signed certificates, but feel free to open an issue in the [Wazuh documentation repo](https://github.com/wazuh/wazuh-documentation) requesting this guide. I'll close this issue in this repo.

Regards,

David
