### ISSUE TITLE
Syscheck: Set "scan_on_start to no" will not work

### ISSUE THREAD

**Issue by Schnoogemetzger** [wazuh/wazuh#6415]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.2 | Syscheck | Agent | Packages | Debian Buster 10.6 |

Hi,

I'm just debugging a realtime monitoring problem at an agent and I've configured the [scan on start](https://documentation.wazuh.com/3.13/user-manual/reference/ossec-conf/syscheck.html?highlight=scan_on_start#scan-on-start) option from syscheck to no (`<scan_on_start>no</scan_on_start>`), so I don't have to wait for the Syscheck to be finished after the restart of the wazuh client. But the scan will be started anyway.
My config (w/o realtime):
```xml
  <syscheck>
    <frequency>3600</frequency>
    <scan_on_start>no</scan_on_start>
    <directories check_all="yes">/TEST</directories>
  </syscheck>
```

ossec.log:
```
2020/10/26 10:02:54 ossec-syscheckd: INFO: (6008): File integrity monitoring scan started.
[...]
2020/10/26 10:02:59 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
```

In the meantime on the manager:
```
$ /var/ossec/bin/agent_control -i 004
[...]
   Client version:      Wazuh v3.13.2 / 0021d252ce5dc0a55ec7b21eb34ff01a
   Shared file hash:    3a4a533bc3b360b91a5f14dc07cd7879
   Last keep alive:     Mon Oct 26 10:02:57 2020

   Syscheck last started at:  Mon Oct 26 10:02:54 2020 (Scan in progress)
   Syscheck last ended at:    Mon Oct 26 09:42:03 2020

   Rootcheck last started at: Mon Oct 26 10:02:57 2020

# some seconds later:

$ /var/ossec/bin/agent_control -i 004
   Syscheck last started at:  Mon Oct 26 10:02:54 2020
   Syscheck last ended at:    Mon Oct 26 10:02:59 2020

   Rootcheck last started at: Mon Oct 26 10:02:57 2020
```

The Syscheck scan will be started even though I've configured the option to no. It doesn't matter, if I set this option in a shared agent.conf, directly in the ossec.conf, restart the wazuh agent at the client or from the server. Furthermore, I recognized that e.g.  `<scan_time>9:42</scan_time>` works.

Is this a bug or do I misunderstand the option?

Thx in advance!

**Comment by Molter73** [comment]
Hi @Schnoogemetzger 

With the release of Wazuh 3.12, syscheck went under a pretty heavy rework and some of its options were removed, keeping them in the configuration for retrocompatibility with older versions. Unfortunately, `scan_on_start` is one of them, with the rework syscheck always creates the local baseline for events when it starts and there is no way to stop it.

I will create an issue in our documentation repo asking for those options to be marked as deprecated since 3.12 and share it here.

**Comment by Schnoogemetzger** [comment]
Ok, thanks.
