### ISSUE TITLE
Remove parentheses from package version field

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#6417]
### Description

We have found that some packages includes the build in the version field, separate by a space, whereas no version  with build separate by space has been found to date, in the NVD CPE.

     897661958|2020/10/23 06:35:48|pkg|zoom.us||public.app-category.video||||5.3.2 (53291.1011)|||applications|us.zoom.xos|/Applications/zoom.us.app|1||

In order for the vulnerability detector to work correctly, it is necessary to remove this parentheses from the version field.

**Comment by MarcelKemp** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/6417-remove-build-package-version

**Comment by chemamartinez** [comment]
Merged #6417
