### ISSUE TITLE
Fix return values in SACL functions in Windows whodata

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#6419]
| Wazuh version | Component       | Install type | Install method   | Platform |
| ------------- | --------------- | ------------ | ---------------- | -------- |
| 4.0.0         | ossec-syscheckd | Agent        | Packages/Sources | Windows  |

## Description

The `check_object_sacl` and `is_valid_sacl` functions are not returning the correct value when checking the SACL in Windows.

Here is `check_object_sacl`:
https://github.com/wazuh/wazuh/blob/8210a8e764509b133aa992eb74fb210340716b95/src/syscheckd/whodata/win_whodata.c#L1095-L1142

And here is `is_valid_sacl`:
https://github.com/wazuh/wazuh/blob/8210a8e764509b133aa992eb74fb210340716b95/src/syscheckd/whodata/win_whodata.c#L263-L295

These functions return `1` (error or invalid) in several ocassions and they should only return `1` when the SACL are invalid, returning other values when an error is encountered during their execution.

On the other hand, the `is_valid_sacl` function is not checking every SACL used by Wazuh, new SACL types were added to whodata in Windows and this wasn't updated.

**Comment by vnil1994** [comment]
Any update to this? This bug is preventing us from upgrading our environment

**Comment by jesusjimsa** [comment]
Hello, @vnil1994.

We have not started working on this yet but we will try to find a fix for this as soon as possible. Any update about this will be published here, so you can check the progress here.

On the other hand, feel free to submit a pull request with the fix if you find it and our team will be happy to review it. Contributions are always very welcome.
