### ISSUE TITLE
Windows message field parser creation

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6431]
Windows Message field contains a lot of values in a single field. Is it possible to create a parser for that?

We would like to meet the following things,

We have integrated with Windows PowerShell operational logs which give whole information in a single message field like executed commands, User etc. To create some custom rules we have to get parse message field values separately.

**Comment by MarcelKemp** [comment]
Hello @VisakhMV-Coder,

Sorry for the delay. Yes, there are several ways to parse it, depending on what you need.

For the following example:
```
{
  "timestamp": "2020-10-23T12:24:25.216+0000",
  "rule": {
    "level": 12,
    "description": "Windows Defender: Antimalware platform detected  potentially unwanted software",
    "id": "62123",
    "groups": [
      "windows",
      "windows_defender"
    ],
    ...
  "id": "1603455865.436193",
  "decoder": {
    "name": "windows_eventchannel"
  },
  "data": {
    "win": {
      "system": {
        ...
        "channel": "Microsoft-Windows-Windows Defender/Operational",
        "severityValue": "WARNING",
        "message": "\"Windows Defender Antivirus has detected malware or other potentially unwanted software.\r\n For more information please see the following:\r\nhttps://go.microsoft.com/fwlink/?linkid=37020&name=Virus:DOS/EICAR_Test_File&threatid=2147519003&enterprise=0\r\n \tName: Virus:DOS/EICAR_Test_File\r\n \tID: 2147519003\r\n \tSeverity: Severe\r\n \tCategory: Virus\r\n \tPath: file:_C:\\Users\\wazuh\\Downloads\\eicar.com.txt\r\n \tDetection Origin: Local machine\r\n \tDetection Type: Concrete\r\n \tDetection Source: Real-Time Protection\r\n \tUser: DESKTOP-HC4OQP7\\wazuh\r\n \tProcess Name: C:\\Windows\\System32\\notepad.exe\r\n \tSecurity intelligence Version: AV: 1.325.1278.0, AS: 1.325.1278.0, NIS: 1.325.1278.0\r\n \tEngine Version: AM: 1.1.17500.4, NIS: 1.1.17500.4\""
      },
      "eventdata": {
        ...
        "source Name": "%%818",
        "origin Name": "%%845",
        "execution Name": "%%813",
        ...
        "security intelligence Version": "AV: 1.325.1278.0, AS: 1.325.1278.0, NIS: 1.325.1278.0",
        "engine Version": "AM: 1.1.17500.4, NIS: 1.1.17500.4"
      }
    }
  },
  "location": "EventChannel"
}
```

Inside the message field it shows a lot of information that is already parsed in other fields, codified with the format **_%%123_**. So in order to create the rule, we have the following options:

- If we already have the field with the information parsed in **_%%_** format within the alert, we only need to capture that field.

      <field name="source Name">%%818</field>

- On the other hand, if it is only in the message field, we would have to parse the field to obtain a substring with the necessary information.

      <field name="message">Detection Origin: Local machine</field>

If you could send me an event example next to the fields you want to parse from that example, I could pass you the custom rule necessary for it.

**Comment by VisakhMV-Coder** [comment]
Hi,

I have got the point. We can create rules to achieve the same rather than parsing the message field. right?

Like this,

<var name="MS_FREQ">3</var>
<var name="actions">ACDO|ACO|ADBO|LGIF</var>


<group name="windows,sqlserver,sqlaudit">

<rule id="140000" level="3">
        <if_sid>60003</if_sid>
        <field name="win.system.eventID">^33205$</field>
        <field name="win.system.message">\.*action_id:$actions</field>
        <description>MSSQL Audit Events</description>
    </rule>

   <rule id="140002" level="5">
        <if_sid>140000</if_sid>
        <match>LGIF</match>
        <description>MSSQL Audit: LOGIN FAILED</description>
    </rule>

**Comment by MarcelKemp** [comment]
Sorry if I have not explained it well.

When creating the rule we will not parse the message field, but within the rule with the **field** option we will use **regex** to match the information we are looking for, and thus obtain a substring with the result obtained.

The rule you have sent me is not valid, if you tell me what you want to get from the message field, I can customize the rule for you. An example of that event you want to be fired would help a lot.

This event can be found, when you activate the **_logall_** option in _ossec.conf_, in the path: _/var/ossec/logs/archives/archives.log_

I am adding the documentation for creating rules below in case you want to create it yourself: 

- https://documentation.wazuh.com/4.0/user-manual/ruleset/custom.html
- https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html

I hope I have helped you understand it, if not let me know to try to explain it to you in a different way.

**Comment by VisakhMV-Coder** [comment]
Sorry for the delayed response.

Here an example of the log file. I would like to get an alert when the message field contains "Process Command Line: *****" any commands like arp, nslookup, ping, etc.


**Phase 2: Completed decoding.
       decoder: 'json'
       win.system.providerName: 'Microsoft-Windows-Security-Auditing'
       win.system.providerGuid: '{54849625-5478-4994-A5BA-3E3B0328C30D}'
       win.system.eventID: '4688'
       win.system.version: '2'
       win.system.level: '0'
       win.system.task: '13312'
       win.system.opcode: '0'
       win.system.keywords: '0x8020000000000000'
       win.system.systemTime: '2020-11-18T05:00:18.562772600Z'
       win.system.eventRecordID: '4642526'
       win.system.processID: '4'
       win.system.threadID: '3808'
       win.system.channel: 'Security'
       win.system.computer: 'WIN-JPO8V9E8OO6.soc.loc'
       win.system.severityValue: 'AUDIT_SUCCESS'
       win.system.message: '"A new process has been created.

Creator Subject:
        Security ID:            S-1-5-21-2504266149-2836159182-4221175343-500
        Account Name:           Administrator
        Account Domain:         SOC
        Logon ID:               0x32AAC

Target Subject:
        Security ID:            S-1-0-0
        Account Name:           -
        Account Domain:         -
        Logon ID:               0x0

Process Information:
        New Process ID:         0x10f8
        New Process Name:       C:\Windows\System32\ARP.EXE
        Token Elevation Type:   TokenElevationTypeDefault (1)
        Creator Process ID:     0x138c
        **Process Command Line:   arp  -a**

Token Elevation Type indicates the type of token that was assigned to the new pr                                                                                        ocess in accordance with User Account Control policy.

Type 1 is a full token with no privileges removed or groups disabled.  A full to                                                                                        ken is only used if User Account Control is disabled or if the user is the built                                                                                        -in Administrator account or a service account.

Type 2 is an elevated token with no privileges removed or groups disabled.  An e                                                                                        levated token is used when User Account Control is enabled and the user chooses                                                                                         to start the program using Run as administrator.  An elevated token is also used                                                                                         when an application is configured to always require administrative privilege or                                                                                         to always require maximum privilege, and the user is a member of the Administra                                                                                        tors group.

Type 3 is a limited token with administrative privileges removed and administrat                                                                                        ive groups disabled.  The limited token is used when User Account Control is ena                                                                                        bled, the application does not require administrative privilege, and the user do                                                                                        es not choose to start the program using Run as administrator."'
       win.eventdata.subjectUserSid: 'S-1-5-21-2504266149-2836159182-4221175343-                                                                                        500'
       win.eventdata.subjectUserName: 'Administrator'
       win.eventdata.subjectDomainName: 'SOC'
       win.eventdata.subjectLogonId: '0x32aac'
       win.eventdata.newProcessId: '0x10f8'
       win.eventdata.newProcessName: 'C:\\Windows\\System32\\ARP.EXE'
       win.eventdata.tokenElevationType: '%%1936'
       win.eventdata.processId: '0x138c'
       win.eventdata.commandLine: 'arp  -a'
       win.eventdata.targetUserSid: 'S-1-0-0'
       win.eventdata.targetLogonId: '0x0'

Here the full log,

{"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4688","version":"2","level":"0","task":"13312","opcode":"0","keywords":"0x8020000000000000","systemTime":"2020-11-18T05:00:18.562772600Z","eventRecordID":"4642526","processID":"4","threadID":"3808","channel":"Security","computer":"WIN-JPO8V9E8OO6.soc.loc","severityValue":"AUDIT_SUCCESS","message":"\"A new process has been created.\r\n\r\nCreator Subject:\r\n\tSecurity ID:\t\tS-1-5-21-2504266149-2836159182-4221175343-500\r\n\tAccount Name:\t\tAdministrator\r\n\tAccount Domain:\t\tSOC\r\n\tLogon ID:\t\t0x32AAC\r\n\r\nTarget Subject:\r\n\tSecurity ID:\t\tS-1-0-0\r\n\tAccount Name:\t\t-\r\n\tAccount Domain:\t\t-\r\n\tLogon ID:\t\t0x0\r\n\r\nProcess Information:\r\n\tNew Process ID:\t\t0x10f8\r\n\tNew Process Name:\tC:\\Windows\\System32\\ARP.EXE\r\n\tToken Elevation Type:\tTokenElevationTypeDefault (1)\r\n\tCreator Process ID:\t0x138c\r\n\tProcess Command Line:\tarp  -a\r\n\r\nToken Elevation Type indicates the type of token that was assigned to the new process in accordance with User Account Control policy.\r\n\r\nType 1 is a full token with no privileges removed or groups disabled.  A full token is only used if User Account Control is disabled or if the user is the built-in Administrator account or a service account.\r\n\r\nType 2 is an elevated token with no privileges removed or groups disabled.  An elevated token is used when User Account Control is enabled and the user chooses to start the program using Run as administrator.  An elevated token is also used when an application is configured to always require administrative privilege or to always require maximum privilege, and the user is a member of the Administrators group.\r\n\r\nType 3 is a limited token with administrative privileges removed and administrative groups disabled.  The limited token is used when User Account Control is enabled, the application does not require administrative privilege, and the user does not choose to start the program using Run as administrator.\""},"eventdata":{"subjectUserSid":"S-1-5-21-2504266149-2836159182-4221175343-500","subjectUserName":"Administrator","subjectDomainName":"SOC","subjectLogonId":"0x32aac","newProcessId":"0x10f8","newProcessName":"C:\\\\Windows\\\\System32\\\\ARP.EXE","tokenElevationType":"%%1936","processId":"0x138c","commandLine":"arp  -a","targetUserSid":"S-1-0-0","targetLogonId":"0x0"}}}

**Comment by MarcelKemp** [comment]
Hi @VisakhMV-Coder,

According to the alert you need, I have customized a rule that is activated when the **severityValue** is equal to _AUDIT_SUCCESS_ and the **event ID** is _4688_. Then it checks that the **Process Command Line** field contains _some information_, and shows it in the alert description.

```xml
 <rule id="100007" level="5">
   <if_sid>60103</if_sid>
   <field name="win.system.eventID">^4688$</field>
   <field name="win.eventdata.commandLine">\.+</field>
   <description>The Process Command Line is $(win.eventdata.commandLine)</description>
 </rule>
```

If you want, you can add more fields to the rule to obtain more information, I link the documentation below in case it helps you:
- https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/rules.html

In addition, I have assigned a level 5 to the alert, but you can modify it according to the priority that this rule has for you.

I hope I've helped. If you need anything else, do not hesitate to ask me.

Best regards,
Marcel

**Comment by VisakhMV-Coder** [comment]
Thank you for your Information.

**Comment by VisakhMV-Coder** [comment]
Resolved
