### ISSUE TITLE
wazuh 4.0 local rules if_matched_sid not working

### ISSUE THREAD

**Issue by ozgursuder** [wazuh/wazuh#6432]
<rule id="100002" level="15" frequency="3" timeframe="60">
    <if_matched_sid>20006</if_matched_sid>
    <field name="win.system.eventID">^529$|^4625$|^4771$</field>
	<field name="win.eventdata.targetUserName">root|administrator</field>
    <description>Domain Admins Logon Failure - Unknown User or Bad Password</description>
	<options>alert_by_email</options>
    <options>no_full_log</options>
    <group>win_authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
   </rule>

**Comment by ozgursuder** [comment]
It works like this but doesn't work when using if_matched_sid

<rule id="100002" level="15">
<if_sid>20006</if_sid>
<field name="win.system.eventID">^529$|^4625$|^4771$</field>
<field name="win.eventdata.targetUserName">root|administrator</field>
<description>Domain Admins Logon Failure - Unknown User or Bad Password</description>
<options>alert_by_email</options>
<options>no_full_log</options>
<group>win_authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>

**Comment by ozgursuder** [comment]
<rule id="100002" level="15" frequency="$MS_FREQ" timeframe="60" ignore="60">
    <if_matched_group>win_authentication_failed</if_matched_group>
    <field name="win.system.eventID">^529$|^4625$|^4771$</field>
	<field name="win.eventdata.targetUserName">root|administrator</field>
    <description>Domain Admins Logon Failure - Unknown User or Bad Password</description>
	<options>alert_by_email</options>
    <options>no_full_log</options>
    <group>win_authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
   </rule>

**Comment by Lopuiz** [comment]
Hello,

Exist similar rule in Wazuh which fire in this case:
```xml
  <rule id="60204" level="10" frequency="$MS_FREQ" timeframe="240">
    <if_matched_group>win_authentication_failed</if_matched_group>
    <same_field>win.eventdata.ipAddress</same_field>
    <description>Multiple Windows Logon Failures</description>
    <mitre>
      <id>T1110</id>
    </mitre>
    <options>no_full_log</options>
    <group>authentication_failures,pci_dss_10.2.4,pci_dss_10.2.5,pci_dss_11.4,gdpr_IV_35.7.d,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,nist_800_53_SI.4,tsc_CC6.1,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```

When this rule fires the counters set to 0, so it's possible your custom rule doesn't work. Could you test this the following rule?

```xml
<rule id="100002" level="15" frequency="$MS_FREQ" timeframe="60" ignore="60">
<if_sid>60204</if_sid>
<field name="win.system.eventID">^529$|^4625$|^4771$</field>
<field name="win.eventdata.targetUserName">root|administrator</field>
<description>Domain Admins Logon Failure - Unknown User or Bad Password</description>
<options>alert_by_email</options>
<options>no_full_log</options>
<group>win_authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,gpg13_7.1,gdpr_IV_35.7.d,gdpr_IV_32.2,</group>
```

Regards,
Eva
