### ISSUE TITLE
Minor fixes for registry scan

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh#6451]
| Wazuh version | Component | Install type  | Install method   | Platform |
| ------------- | --------- | ------------- | ---------------- | -------- |
| 4.1.0         | FIM       | Manager/Agent | Packages/Sources | Windows  |

## Description

We are going to use this this issue to describe all the minor fixes that need to be done in the Windows registry scan in the FIM module. The branch to work on minor fixes is `fim-registry-improvements-minor-fixes`.

Minor fixes found should be described in a comment in this issue and added in the `fim-registry-improvements-minor-fixes` branch.

The fixes to be done so far are:

- [x] Specify the registry architecture in the ignore and restrict debug messages.
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L176
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L188
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/create_db.c#L1107

- [x] Remove compilation warning about unused `xml_registry_ignore_value` variable in Linux.
https://github.com/wazuh/wazuh/blob/9232f9c4b52bf44b52eb331fb94d653f7143d7f4/src/config/syscheck-config.c#L1720

- [x] Calls to `os_free(str_pathlh)` and `os_free(str_pathuh)` in `fim_db_get_checksum_range` cause a segfault. The proper frees should be `os_free(*str_pathlh)` and `os_free(*str_pathuh)`.
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L816-L817

- [x] The first level in recursion level should be changed from `-1` to `0`.
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L117

- [x] The scan only ignores the registry value name, it should ignore its path.
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L662

- [x] We use the OR operation when checking the checksum options and it should be an AND operation.
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L270-L282

- [x] `fim_db_get_string`, `fim_db_decode_string` and `fim_db_decode_string_array` should use `sqlite_strdup` instead of `os_strdup` to avoid FIM closing in case of returning `NULL` from sqlite. If the first parameter of `sqlite_strdup` is `sqlite3_column_text`, we should use an aux vairable to avoud expanding the macro after two consecutive `sqlite3_column_text` calls.
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L678
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L643
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L660

- [x] The error message in `fim_db_get_string` prints `str` without using it. This is generally null.
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L673

- [x] The `fseek` call in `fim_db_read_line_from_file` is wrong, it should be `fseek(file->fd, 0, SEEK_SET)`. It is working now because `SEEK_SET` is `0`.
https://github.com/wazuh/wazuh/blob/f149914c1ef5d3fffc14f55dbb5614c6350fa210/src/syscheckd/db/fim_db.c#L861

- [x] The function `fim_db_get_entry_from_sync_msg` queries the DB for the key id when processing a value, but it's already available as part of the key, we can remove the following block of code and use the available id:
https://github.com/wazuh/wazuh/blob/2c93945936e7ef25c9961c5c4a44593b15e4b930/src/syscheckd/db/fim_db.c#L329-L334

- [x] Possible deadlock when `fim_db_get_path_range` fails https://github.com/wazuh/wazuh/blob/2c93945936e7ef25c9961c5c4a44593b15e4b930/src/syscheckd/fim_sync.c#L324-L332

- [x] Typo in `getSyscheckConfig`: `registry_ignore_value_regex` should be `registry_ignore_sregex` https://github.com/wazuh/wazuh/blob/2c93945936e7ef25c9961c5c4a44593b15e4b930/src/syscheckd/config.c#L397-L436

- [x] This function is not been used, we should remove it: `fim_db_get_registry_keys_range()`
https://github.com/wazuh/wazuh/blob/2c93945936e7ef25c9961c5c4a44593b15e4b930/src/syscheckd/db/fim_db_registries.c#L426-L442
https://github.com/wazuh/wazuh/blob/2c93945936e7ef25c9961c5c4a44593b15e4b930/src/syscheckd/db/fim_db_registries.h#L281-L294

- [x] There is a warning message in the compilation about the fim_diff_changes.c file.
```
syscheckd/fim_diff_changes.c: In function ‘initialize_file_diff_data’:
syscheckd/fim_diff_changes.c:518:35: warning: ‘/local’ directive output may be truncated writing 6 bytes into a region of size between 1 and 4096 [-Wformat-truncation=]
  518 |     snprintf(buffer, PATH_MAX, "%s/local%s", abs_diff_dir_path, diff->file_origin);
      |                                   ^~~~~~
syscheckd/fim_diff_changes.c:518:5: note: ‘snprintf’ output 7 or more bytes (assuming 4102) into a destination of size 4096
  518 |     snprintf(buffer, PATH_MAX, "%s/local%s", abs_diff_dir_path, diff->file_origin);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
syscheckd/fim_diff_changes.c:532:35: warning: ‘/tmp’ directive output may be truncated writing 4 bytes into a region of size between 1 and 4096 [-Wformat-truncation=]
  532 |     snprintf(buffer, PATH_MAX, "%s/tmp", abs_diff_dir_path);
      |                                   ^~~~
syscheckd/fim_diff_changes.c:532:5: note: ‘snprintf’ output between 5 and 4100 bytes into a destination of size 4096
  532 |     snprintf(buffer, PATH_MAX, "%s/tmp", abs_diff_dir_path);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
https://github.com/wazuh/wazuh/blob/4a840fca00d80726f781c96e263abbd84003ef31/src/syscheckd/fim_diff_changes.c#L518
https://github.com/wazuh/wazuh/blob/4a840fca00d80726f781c96e263abbd84003ef31/src/syscheckd/fim_diff_changes.c#L532

- [x] There is a segmentation fault in case the path in `NULL`. We need to check if it is `NULL` and assign `0` in an affirmative case.
https://github.com/wazuh/wazuh/blob/e7177aaea6606fd67b39dd8512c36d60f2547c13/src/analysisd/decoders/syscheck.c#L1559
https://github.com/wazuh/wazuh/blob/e7177aaea6606fd67b39dd8512c36d60f2547c13/src/analysisd/decoders/syscheck.c#L1572
https://github.com/wazuh/wazuh/blob/e7177aaea6606fd67b39dd8512c36d60f2547c13/src/analysisd/decoders/syscheck.c#L1585

- [x] `adapt_win_fc_output` is being compiled for *nix systems, eventhough it is only used in Windows. We should move it into an `#ifdef WIN32` block, preferably and existing one in the file so they are grouped together.
https://github.com/wazuh/wazuh/blob/ae6046a6b9963db1a6f116efe1547988c94025ca/src/syscheckd/fim_diff_changes.c#L897

- [x] There is a typo in this debug message, it should be `...it doesn't exist.`
https://github.com/wazuh/wazuh/blob/f3836f1e917d093cf56ece12b94cdfd46719dfc9/src%2Ferror_messages%2Fdebug_messages.h#L249

- [x] These messages should say `files/registries` in Windows:
https://github.com/wazuh/wazuh/blob/f3836f1e917d093cf56ece12b94cdfd46719dfc9/src%2Ferror_messages%2Fdebug_messages.h#L236-L237

- [x] Care of registry names that are larger than those buffers, the name will be truncated. We should put in the DB the full name:
https://github.com/wazuh/wazuh/blob/b2c492b7217b67e579b1d3a048c7f2bb7d232a2c/src/syscheckd/registry/registry.c#L833-L843

- [x] Size limits hardcoded. We need to call **RegEnumValue** with some NULL values to get the sizes we want.
https://github.com/wazuh/wazuh/blob/982de0ac1c65955e08b4be6898a5e8d4a2411403/src/syscheckd/registry/registry.c#L745-L767

**Comment by Molter73** [comment]
The item regarding the possible segfault when decoding an event without a path would be better handled in `fim_process_alert`, we can stop processing of the alert right after we have parsed the event if no path was provided.
