### ISSUE TITLE
[WPK] Unexpected behaviour when sending some messages to the socket

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#6453]
This is issue is part of #5387.

This issue reports some unexpected results when sending a message with command `upgrade` to the socket.

**1.- When sending the next message to the socket:**

`
{'version': 1, 'origin': {'module': 'api'}, 'command': 'upgrade', 'parameters': {'agents': [4], 'force_upgrade': True, 'use_http': False}}
`

The result expected must be a success so the agent 002 must have started upgrading to the newest Wazuh version (by default).
However, this is the actual result from the socket:

`
{'error': 0, 'data': [{'error': 13, 'message': 'The version of the WPK does not exist in the repository', 'agent': 4}], 'message': 'Success'}
`

**2.- When sending the next message to the socket:**

`
{'version': 1, 'origin': {'module': 'api'}, 'command': 'upgrade', 'parameters': {'agents': [5], 'version': 'v3.13.1', 'force_upgrade': True, 'use_http': False}}
`

The result expected must be a success and the `wpk_repo` taken by the core functions must be the 3.x repo (`packages.wazuh.com/wpk/`). However, the error is the same as before and the `wpk_repo` is not found. This make the user introduce the 3.x repo in order to upgrade successfully.

`
{'error': 0, 'data': [{'error': 13, 'message': 'The version of the WPK does not exist in the repository', 'agent': 5}], 'message': 'Success'}
`

When `version` is 4.0.0 with no `wpk_repo`, the result is the correct one and the upgrade task is done properly.

Regards,
Manuel.

**Comment by TomasTurina** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/5856/commits/5129e70007ff32c6735d6f35ea24414df672f117
