### ISSUE TITLE
Unit testing for the new logic of agents monitoring implemented in monitord

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6458]
## Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) was required to improve the agents' disconnection management and the alerts generated from monitord. This required to modify all the logic for agents monitoring and it ended up being a completely new code. So, unit test cases should be implemented for the new code.

## Requirementes

- [x] 100% of unit testing coverage for all the new code in monitord.
- [x] 100% of unit testing coverage for any critical method involved in the agents' monitoring.

## Definition of done

- [x] Code review approved.
- [x] No `scan-build` errors.
- [x] 0 memory leaks reported by Valgrind on UT.
- [x] Tests developed, executed, and passing successfully.

**Comment by pereyra-m** [comment]
### Tests
Memory leaks weren't found by **Valgrind** in the UT of **monitord**

- test_monitor_actions
![test_monitor_actions](https://user-images.githubusercontent.com/65046601/98049963-7f0f8b80-1e0f-11eb-88f5-95d30e710739.png)

- test_monitord
![test_monitord](https://user-images.githubusercontent.com/65046601/98050067-bbdb8280-1e0f-11eb-8f04-242d6b0ad793.png)

**Comment by DProvinciani** [comment]
Closing the issue as the PR https://github.com/wazuh/wazuh/pull/6487 was merged.
