### ISSUE TITLE
HP-UX compilation problem.

### ISSUE THREAD

**Issue by PSanchezR** [wazuh/wazuh#646]
Hello all,

I found 2 new error during HP-UX agent compilation. First error is during make deps process:

```
gmake deps
curl -so external/cJSON.tar.gz https://packages.wazuh.com/deps/3.3/cJSON.tar.gz
gmake: *** [Makefile:683: external/cJSON.tar.gz] Error 60
```
This error can be solve by changing the url to http protocol.

Second error appear during link process after compilation:

```
ld: Unrecognized argument: --whole-archive
Fatal error.
collect2: ld returned 1 exit status
gmake[1]: *** [Makefile:879: libwazuhext.so] Error 1
gmake[1]: Leaving directory '/tmp/wazuh-master/src'
gmake: *** [Makefile:484: agent] Error 2
```

**Comment by chemamartinez** [comment]
First error can be avoided by running the `make deps` into another OS and then, build the Wazuh agent on HP-UX after the external libraries have been downloaded.

About the second error, it has been solved in this commit: https://github.com/wazuh/wazuh/commit/7e87dbdd011b39caf3a4a9db12fc6364f94a4efa

There has been added a flag called `DISABLED_SHARED` to avoid building the shared library for incompatible Operating Systems.

Regards.
