### ISSUE TITLE
[Cluster] Add docstrings and comments to code

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6474]
|Wazuh version|Component|Install type|
|---|---|---|
|4.0| Wazuh cluster | Manager |

## Description

Hey team,

We need to add docstrings and comments to our cluster code. It is actually very difficult to understand the behaviour and purpose of many of the funcions due to the lack of it.

### Add docstrings and comments
There are practically no comments or docstrings on the methods and functions of our cluster that allow us to understand how each one works at a glance. It is necessary to add an explanation/docstring in order to speed up future developments.

## To do
- [x] Add dosctrings to cluster code
- [x] Add comments whenever necessary to code fragments with a difficult comprehension

Best regards,

David J. Iglesias

**Comment by Selutario** [comment]
## Issue update

Hello team!

I'm adding docstrings and comments in all those placed inside cluster which needed some kind of explanation. I am taking advantage of the process to change the format of all the docstrings to `numpydoc`, and improve or add complementary information in those places that I consider appropriate and that were already documented.

However, there is a lot of code and the process is slow. At the moment all these cluster modules are updated:
- `worker.py`
- `utils.py`
- `server.py`
- `master.py`
- `local_server.py`

At a glance, the modules left to document / change are smaller, so I hope to finish it in a day or two at the most.

## Example docstring
One good example of the new documentation is the docstring of the master's sync_integrity method:
```Python
    async def sync_integrity(self, task_name: str, received_file: asyncio.Event):
        """Perform the integrity synchronization process by comparing local and received files.

        It waits until the worker sends its integrity checksums. Once received, they are unzipped.

        The information inside the unzipped cluster_control.json file (integrity checksums) is compared with the
        local one (updated every self.cluster_items['intervals']['master']['recalculate_integrity'] seconds).
        All files that are different (new, deleted, with a different MD5, etc) are classified into four groups:
        shared, missing, extra and extra_valid.

        Finally, a zip containing this classification (cluster_control.json) and the files that are missing
        or that must be updated are sent to the worker.

        Parameters
        ----------
        task_name : str
            Task name in charge of doing the sync process.
        received_file : asyncio.Event
            Asyncio event that is holding a lock while the files are not received.

        Returns
        -------
        bytes, bytes
            Result, message.
        """
```

Best regards,
Selu.

**Comment by Selutario** [comment]
## Issue update

Hi team!

This modules are ready too:
- local_client.py
- control.py

I'm starting to comment `common.py`.

Regards,
Selu.

**Comment by Selutario** [comment]
## Issue update
Hey team!

Today I have added docstrings and comment to the modules below:
- `common.py`
- `cluster.py` (not finished, but almost). 

Only `client.py` is left to do.

Best regards,
Selu.
