### ISSUE TITLE
Microsoft azure : integration

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#6533]
Hi,

can somebody tell me what a **query** and **tag** in request part on the following configuration. As i am not good with azure part it would be helpful if somebody can help. Thanks in Advance

<wodle name="azure-logs">

    <disabled>no</disabled>
    <wday>monday</wday>
    <time>02:00</time>
    <run_on_start>no</run_on_start>

    <log_analytics>

        <auth_path>/home/manager/Azure/log_analytics_auth.txt</auth_path>
        <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>

        <request>
            **<tag>azure-activity</tag>**
            **<query>AzureActivity</query>**
            <workspace>d6b...efa</workspace>
            <time_offset>2d</time_offset>
        </request>

    </log_analytics>

</wodle>

**Comment by chemamartinez** [comment]
Hi @VisakhMV-Coder,

The goal of this module is to fetch logs from the Azure API and process them with Wazuh.

The fields you are asking for have the following purpose:

- **tag**: The value of this field is added as extra data to the pulled events. Therefore it simplifies the events filtering or rules creation.

- **query**: This is the query for the Azure Log Analytics API. It allows to filter fetched logs by following the syntax it is explained in the Azure documentation:

- https://docs.microsoft.com/en-us/azure/azure-monitor/log-query/get-started-queries
- https://dev.loganalytics.io/documentation/Using-the-API/RequestFormat

Let me add a few links about how to use the Wazuh Azure integration:

- https://documentation.wazuh.com/4.0/azure/index.html
- https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/wodle-azure-logs.html#log-analytics-request-tag

I hope it helps.

Best regards,
Chema.

**Comment by VisakhMV-Coder** [comment]
Thank you for your information.
