### ISSUE TITLE
Application Not Found - No application was found at this URL.

### ISSUE THREAD

**Issue by tusharbarhate** [wazuh/wazuh#6536]
Hello Team, 

After login the console we are getting error  "Application Not Found" I checked in browser getting "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)." 

We have installed latest version of wazuh, elasticsearch and kibana. Find attachment and let us know if required anything.

![elasticsearch](https://user-images.githubusercontent.com/1883965/98526448-c5496c80-229f-11eb-85fc-798f7614c11d.png)
![filebeat](https://user-images.githubusercontent.com/1883965/98526464-c9758a00-229f-11eb-8841-ee06a933cd1b.png)
![kibana](https://user-images.githubusercontent.com/1883965/98526479-ce3a3e00-229f-11eb-91b2-de1242864536.png)
![test](https://user-images.githubusercontent.com/1883965/98526482-d09c9800-229f-11eb-90d7-894206e082e0.png)
![wazuh_console_problem](https://user-images.githubusercontent.com/1883965/98526493-d2fef200-229f-11eb-8dcf-294512172273.png)
![wazuh-manager](https://user-images.githubusercontent.com/1883965/98526499-d5f9e280-229f-11eb-9247-4c300a52371d.png)

Please suggest what can be possible steps to resolve this issue ? 

Thanks

**Comment by AdriiiPRodri** [comment]
Hi @tusharbarhate,

It is possible that this error is due to some kind of **incompatibility** between the installed versions of our plugin and the Elastic Stack version. It is important to check that the versions are compatible, for this we must check the Wazuh's compatibility matrix: [4.0](https://documentation.wazuh.com/4.0/upgrade-guide/compatibility_matrix/#components-compatibility) or [3.13](https://documentation.wazuh.com/3.13/installation-guide/compatibility_matrix/#product-compatibility).

We see that the version of Elastic Stack you currently have installed is 7.9.1, which is compatible with Wazuh version 3.13 and 4.0. What version of Wazuh do you currently have installed?
```
cat /etc/ossec-init.conf
```

On the other hand, we need to check which version of the APP is installed, so we can execute the following command:
```
cat /usr/share/kibana/plugins/wazuh/package.json
```

Once we get the versions we have, we will check that they are compatible, if not, we will reinstall the correct version following the compatibility matrix.

I hope this answer is helpful to you, in case you have any trouble with this guide, please don't hesitate to ask.

Best regards,
Adrián Peña

**Comment by tusharbarhate** [comment]
Dear  Adrián Peña,

Please find the blow screenshot, installed version is  "v4.0.0". In second screen we are not getting the "wazuh" in plugin folder. Please assist further. 
![version](https://user-images.githubusercontent.com/1883965/98658193-c98d8c80-2368-11eb-8882-180bf47b4b04.png)
![app](https://user-images.githubusercontent.com/1883965/98658204-cc887d00-2368-11eb-8434-739b360e9d30.png)

Regards,
Tushar Barhate

**Comment by AdriiiPRodri** [comment]
Usually if the wazuh folder is not inside the plugins folder it means that the Wazuh's APP is not installed. To check this we will try to install it again.

To perform these steps we will follow the [Wazuh's installation guide](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html). In particular, we are going to perform the installation part of the Wazuh's APP.

First we will move to the `/usr/share/kibana` folder:
```
cd /usr/share/kibana
```

Then we will run the following command to install the APP:
```
sudo -u kibana /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/4.x/ui/kibana/wazuh_kibana-4.0.0_7.9.1-1.zip
```

With this command the Wazuh APP should be installed. After this we will follow the installation guide and once we restart Kibana as indicated in the documentation, we should have access to the APP.

In case it does not work, we will try to get the logs of it:
```
cat /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log | grep -i -E "error|warn"
```

More information [here](https://documentation.wazuh.com/4.0/user-manual/kibana-app/troubleshooting.html#none-of-the-above-solutions-are-fixing-my-problem).

Regards

**Comment by tusharbarhate** [comment]
Dear  Adrián Peña, 

Output of  cat /usr/share/kibana/plugins/wazuh/package.json

{
  "name": "wazuh",
  "version": "4.0.0",
  "revision": "4007",
  "code": "4007-0",
  "kibana": {
    "version": "7.9.1"
  },
  "description": "Wazuh app",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
  "node_build": "8.14.0",
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "dependencies": {
    "angular-animate": "1.7.8",
    "angular-chart.js": "1.1.1",
    "angular-cookies": "1.6.5",
    "angular-material": "1.1.18",
    "axios": "^0.19.0",
    "d3": "^5.12.0",
    "install": "^0.10.1",
    "js2xmlparser": "^3.0.0",
    "json2csv": "^4.1.2",
    "jwt-decode": "^2.2.0",
    "needle": "^2.0.1",
    "node-cron": "^1.1.2",
    "pdfmake": "^0.1.37",
    "pug-loader": "^2.4.0",
    "querystring-browser": "1.0.4",
    "react-codemirror": "^1.0.0",
    "react-redux": "^7.1.1",
    "read-last-lines": "^1.7.2",
    "redux": "^4.0.4",
    "timsort": "^0.3.0",
    "winston": "3.0.0",
    "brace": "^0.11.1"
  },
  "build": {
    "git": {
      "count": "1",
      "sha": "13831a3",
      "date": "Fri, 6 Nov 2020 02:46:24 +0100"
    },
    "date": "Fri Nov 06 2020 01:49:59 GMT+0000 (UTC)"
  }
}

Not getting /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log   wazuh-logs folder is missing. Followed all steps and its installed properly showing all services in running state. 

Please assist further.

![1](https://user-images.githubusercontent.com/1883965/98765132-64d34000-2403-11eb-8027-03e28fbcf872.png)


Regards,

Tushar

**Comment by AdriiiPRodri** [comment]
Hi tusharbarhate,

Great, the APP seems to be installed, after this step, we have to follow Wazuh's installation guide. The next thing would be:

1. Copy the Elasticsearch certificates into /etc/kibana/certs:
```
mkdir /etc/kibana/certs
cp /etc/elasticsearch/certs/root-ca.pem /etc/kibana/certs/
mv /etc/elasticsearch/certs/kibana_http.key /etc/kibana/certs/kibana.key
mv /etc/elasticsearch/certs/kibana_http.pem /etc/kibana/certs/kibana.pem
```

2. Link Kibana’s socket to privileged port 443:
```
setcap 'cap_net_bind_service=+ep' /usr/share/kibana/node/bin/node
```

3. Finally, we should restart Kibana:
```
update-rc.d kibana defaults 95 10
service kibana start
```

Once these steps have been carried out, we will check if the APP is working correctly. To do this, we will access the web interface:
```
https://localhost
user: admin
password: admin
```

Then we will go to the Wazuh APP which should load correctly, if not, please indicate the error so we can help you better. It is important that we make sure that all the steps mentioned in the [installation guide](https://documentation.wazuh.com/4.0/installation-guide/open-distro/all-in-one-deployment/all_in_one.html) are completed.

Regards

**Comment by tusharbarhate** [comment]
Still getting same page. please assist further : 

![wazuh-app](https://user-images.githubusercontent.com/1883965/98801845-6bc87580-2438-11eb-9b99-8c1a00349227.png)

**Comment by AdriiiPRodri** [comment]
By default Kibana does **not save the logs in a file**, we need to configure this in the `kibana.yml` file. To do this we go to the file `/etc/kibana/kibana.yml`, within it we will configure the option `logging.dest` with the path `/var/log/kibana`. After this we will restart Kibana:
```
# Enables you specify a file where Kibana stores log output.
#logging.dest: stdout
logging.dest: /var/log/kibana
```
```
service kibana restart
```

After that, try to access the Wazuh APP again. In case that the same page is displayed, let's execute again the command `cat /usr/share/kibana/optimize/wazuh-logs/wazuhapp.log | grep -i -E "error|warn"` to see the possible problem with the APP.

**Comment by tusharbarhate** [comment]
Hello 

After the below, it is not showing login page also... 
setcap 'cap_net_bind_service=+ep' /usr/share/kibana/node/bin/node

update-rc.d kibana defaults 95 10
service kibana start

checked all services are working fine. please assist what we can do in this if you need any conf file let me know. 

![browser](https://user-images.githubusercontent.com/1883965/98932297-2aea6280-2505-11eb-817f-15b275658f4a.png)


Thanks

**Comment by tusharbarhate** [comment]
Its solved. I have removed logging.dest from /etc/kibana/kibana.yml and restart services again. I didn't get the actual problem. 

Thanks for you support.

**Comment by AdriiiPRodri** [comment]
You're welcome

Regards
