### ISSUE TITLE
Logcollector confirms a file monitoring after an opening error

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#654]
This log:

```
2018/05/22 15:57:07 ossec-logcollector: ERROR: (1103): Could not open file '/var/log/httpd/acces_log' due to [(2)-(No such file or directory)].
2018/05/22 15:57:07 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/httpd/acces_log’.
```

is confused because it suggests that the file is being monitored after an opening error and just before ignoring it.

**Comment by vikman90** [comment]
This PR includes PR https://github.com/wazuh/wazuh/pull/568. Merge that one first.

**Comment by RaulMartinPineda** [comment]
Resolved here: https://github.com/wazuh/wazuh/pull/675
