### ISSUE TITLE
 Vulnerability Detector is misreading the Firefox ESR version

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#6562]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0 | Vulnerability Detector | Manager | Packages | Windows |

An issue is presented in the Vulnerability Detector when it is evaluating the Firefox ESR version it seems that VD assesses the firefox version:
![image](https://user-images.githubusercontent.com/37050249/98841987-a8d83c00-2427-11eb-8d86-8e60135c4875.png)

It seems that it is not considering the Firefox ESR as another product as we can see in the CVE associated:
![image](https://user-images.githubusercontent.com/37050249/98842137-dde48e80-2427-11eb-8391-edc882081b05.png)

Thanks in Advance!

**Comment by chemamartinez** [comment]
Thanks for reporting this bug @dariommr.

Currently, the CPE helper only recognizes Firefox, but not Firefox ESR.

We have to distinguish both packages in the CPE helper https://github.com/wazuh/wazuh/blob/master/src/wazuh_modules/vulnerability_detector/cpe_helper.json#L102.

**Comment by chemamartinez** [comment]
Merged #6610
