### ISSUE TITLE
Modify the get-agents-by-connection-status Wazuh DB command to respond data by chunks

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#6563]
### Description

As part of the epic #5887, a new Wazuh DB command called `get-agents-by-connection-status` was created. This command returns an array with the list of agents that are in the specified connection status. But considering the socket buffer limitation, this data may exceed the maximum size. Because of this, a mechanism should be implemented to send the data in chunks.

### Requirements

- [x] Modify the `get-agents-by-connection-status` command to send data by chunks in a similar way that the `get-all-agents` does.
- [x] Update all the necessary unit tests.

### Tests required

- [x] Unit tests executed and passing.
- [x] Manual testing of `Vulnerability Detector` to verify that only the `active` agents are scanned.

Note: Integration tests will be done as part of a separate issue.

### Definition of done

- [x] Code review approved.
- [x] No `scan-build` errors.
- [x] 0 memory leaks reported by Valgrind on UT and Wazuh DB.
- [x] Tests developed, executed, and passing successfully.

**Comment by pereyra-m** [comment]
### Tests

#### Scan-build

No new errors were reported.

#### Valgrind 
**test_wdb_agent**
![valgrind wdb_agent](https://user-images.githubusercontent.com/65046601/99035931-6ade3380-255f-11eb-803a-0d839b20d832.png)
**test_wdb_global**
![valgrind wdb_global](https://user-images.githubusercontent.com/65046601/99035948-7598c880-255f-11eb-9e7e-ccd21d4ccc9a.png)
**test_wdb_global_parser**
![valgrind wdb_global_parser](https://user-images.githubusercontent.com/65046601/99035975-89442f00-255f-11eb-9766-9ec643dc3618.png)

**Comment by DProvinciani** [comment]
closing the issue as the PR https://github.com/wazuh/wazuh/pull/6589 was merged.
