### ISSUE TITLE
Duplicated key inside ossec-analysisd.state

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6576]
|Wazuh version|Component|Install type|
|---|---|---|
| master (4.1) | ossec-analysisd | Manager | 

## Description

Hi team!

As I reported in this other issue https://github.com/wazuh/wazuh/issues/6573, we are facing some errors in our API tests due to a duplicated key inside the file `/var/ossec/var/run/ossec-analysisd.state`:
![imagen](https://user-images.githubusercontent.com/23361101/98932936-4db65000-24e0-11eb-8c2d-bb0b566c0351.png)

Regards!
Selu.

**Comment by TomasTurina** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/6566/commits/606e27081c31beb3b54e865e2b8c2003d48fefa3
