### ISSUE TITLE
AR question

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#6604]
| Wazuh | Elastic |
| ----- | ------- | 
| 3.13.0   | 7.7.1 

Hello.
i am trying to create custom script to work with active response. I want after integrity event to execute the script, which will access the alert(via the elastic api) and take some data. However the alert_id($4 parameter) active response is giving me is different than the number in the "id" field of the elastic document and i can't access that particular event.

Is that how is supposed to be and i am misunderstanding the alert_id thing ? 

P.S Sorry to post it here...

**Comment by vikman90** [comment]
Hi, this issue is a duplicate of #2583, #3247, and #3267. The reason is described at #2829.

Let me close this issue and let's continue posting on issue #3267.

Thank you.
Best regards.
