### ISSUE TITLE
Incorrect reporting.

### ISSUE THREAD

**Issue by Alex-0293** [wazuh/wazuh#6609]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.1-4008| Integrity monitoring | Manager | Packages | Ubuntu 20.04 |

Hi team!
I am facing with incorrect naming.
Rule description should be "Added registry entry"
![изображение](https://user-images.githubusercontent.com/5895448/99253602-15857900-2822-11eb-8f59-03e7503f9de8.png)

**Comment by Molter73** [comment]
Hi @Alex-0293,

We are currently working on a full rework on how we handle integrity of Windows register entries, that description has been updated as part of it.

You can follow up on this rework in [this issue](https://github.com/wazuh/wazuh/issues/5576).

**Comment by Molter73** [comment]
I'm closing this issue since it will shortly be fixed by Wazuh v4.1. As I mentioned in my previous comment, you can follow progress on the registry rework in [this issue](https://github.com/wazuh/wazuh/issues/5576)
