### ISSUE TITLE
Arbitrary failure to create a user for Wazuh API

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh#6617]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.1 | Wazuh API| Manager| Packages| Centos 7 Docker/K8S |

We have been testing these days the update to 4.0 in the cloud and we have found this little problem on quite a few occasions. The problem in question is that when the master container starts, we create a new super admin user and invalidate the **wazuh** one. The creation of this user is failing arbitrarily. Without making any changes, the first run can fail and the pod is restarted, making the second or any subsequent run, create it without problems.

We are creating it in the following way:

https://github.com/wazuh/wazuh-docker/blob/adapt-wazuh-4.0/wazuh/config/01-wazuh.sh#L239-L264

This function makes use of: 
https://github.com/wazuh/wazuh-docker/blob/adapt-wazuh-4.0/wazuh/config/create_user.py

I was watching this with @AdriiiPRodri  and we tried to put more logs in with this security.py https://github.com/wazuh/wazuh-docker/blob/adapt-wazuh-4.0/wazuh/config/security.py but it turns out that the changes in that script are made before writing in the api.log.
An example of an error log:

```bash
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/create_user.py", line 87, in <module>
    update_user(
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.1-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.0.1-py3.8.egg/wazuh/security.py", line 177, in update_user
    raise WazuhError(5007)
wazuh.core.exception.WazuhError: Error 5007 - Insecure user password provided
_user_password = re.compile(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$')
    elif not _user_password.match(password):
        elif not _user_password.match(password):
There was an error configuring the API user
```

To test we also take out the values that we load in the .json and they look like acceptable passwords:

Our superuser
```json
{
  "username": "service_wazuh_api",
  "password": "QUOmXy0yyyKz3ejEs_QJ5F2UF9xI7CVK"
}
```
wazuh-wui pass
```json
{
  "password": "1A2B3C4D_5e6f7g8h"
}
```

Regards

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have been investigating this issue and have found that the error is in the following lines of the script used to modify user passwords:
```
random_pass = "".join(
                    random.choices(
                        string.ascii_uppercase
                        + string.ascii_lowercase
                        + string.digits
                        + "@$!%*?&-_",
                        k=16,
                    )
                )
```
These lines can generate invalid passwords since they are generated randomly.
### Invalid
```
>>> "".join(
...                     random.choices(
...                         string.ascii_uppercase
...                         + string.ascii_lowercase
...                         + string.digits
...                         + "@$!%*?&-_",
...                         k=16,
...                     )
...                 )
'FsvsoYfjxSKJNvcu'
```
### Valid
```
>>> "".join(
...                     random.choices(
...                         string.ascii_uppercase
...                         + string.ascii_lowercase
...                         + string.digits
...                         + "@$!%*?&-_",
...                         k=16,
...                     )
...                 )
'I$cXSo?aDiQcixj9'
```

To solve this problem I suggest replacing these lines with:
```
random_pass = ([random.choice("@$!%*?&-_"),
                           random.choice(string.digits),
                           random.choice(string.ascii_lowercase),
                           random.choice(string.ascii_uppercase),
                           ]
                          + [random.choice(string.ascii_lowercase
                                           + string.ascii_uppercase
                                           + "@$!%*?&-_"
                                           + string.digits) for i in range(12)])

                random.shuffle(random_pass)
                random_pass = ''.join(random_pass)
```

In this way we ensure that all generated passwords fulfill the specification.

Regards

**Comment by jacen05** [comment]
Wazuh version | Component | Install type | Install method | Platform
-- | -- | -- | -- | --
4.1.5 | Wazuh API | Manager | Docker | Debian

Is this issue fixed?
Just got this problem today with latest version 4.1.5 published 3 days ago on Docker Hub.

Generated API password was `S%){zUe[xMFkMlOAydSJ`, we can see that it doesn't match the regex _user_password `r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$'` defined in `/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.1.5-py3.9.egg/wazuh/security.py` : [https://regex101.com/r/MvU143/1](https://regex101.com/r/MvU143/1)
A digit is missing to pass validation.

**Comment by jacen05** [comment]
Another error related to API password generation:

```
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/create_user.py", line 68, in <module>
    username, password = read_user_file()
  File "/var/ossec/framework/scripts/create_user.py", line 30, in read_user_file
    data = json.load(user_file)
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 17 (char 45)
```

The password generated was `6yavr4e{KxP+Z4Hp9tS4`, I guess the string was not quoted when written to the file, so the JSON parser threw an exception when trying to load it (probably due to the the `{` character).
