### ISSUE TITLE
SysInfo packages provider is failing for Windows Hotfixes data

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#6622]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.1 | SysInfo | Agent | Sources | Windows XP / 7 / 10 |

**Description**
The `SysInfo Packages provider` fails for Windows Hotfixes packages due to the fact these type of packages do not have fields like `version`, `vendor`, etc. This will end up when DBSync tries to insert/update packages accessing to fields which does not exist because, right now, there is only a single DB table for this type of provider.

**Syscollector tool execution on Windows XP OS:**
![image](https://user-images.githubusercontent.com/22640902/99293333-47e2a680-2821-11eb-9b42-5871f03d81fa.png)

**Syscollector tool execution on Windows 10 OS:**
![image](https://user-images.githubusercontent.com/22640902/99293258-2aadd800-2821-11eb-88f3-45690fe1879a.png)

**Propose solution:**
Create a new table for hotfixes information and split the package provider data accordingly.

**Comment by Dwordcito** [comment]
This change is included in #6192 issue.
