### ISSUE TITLE
Modify documentation of Wazuh compilation

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#6650]
## **Description**

This issue aims to modify the documentation repo to explain the steps to install GCC and CMake.
In the documentation is required Indicate the minimum versions of CMAKE 2.6.4 and GCC 5.5

Changes in wazuh-packages to build with GCC 5.5 and CMake 2.6.4: https://github.com/wazuh/wazuh-packages/pull/530 

## **DoD**
- [X] Modify documents
- [X] PR -> add as reviewer: David Fernández Miranda.
wazuh-documentation is being updated for this: [PR 3206](https://github.com/wazuh/wazuh-documentation/pull/3206)

**Comment by tinachoB** [comment]
- [X] **OpenSUSE:** Adding `cmake` and `gcc-c++` new dependencies the following results were obtained:
**Manager only**
![image](https://user-images.githubusercontent.com/22640902/100485230-0fbf4b80-30de-11eb-8b14-e32093f95fd6.png)
![image](https://user-images.githubusercontent.com/22640902/100485248-1d74d100-30de-11eb-91c3-c0b8655fbb7e.png)

**Comment by tinachoB** [comment]
- [X] **Ubuntu:** Adding `cmake` and `g++` new dependencies the following results were obtained:

- **Ubuntu 16.04**
**Manager:**
![image](https://user-images.githubusercontent.com/22640902/100484790-865b4980-30dc-11eb-9334-0094ef10cbef.png)
![image](https://user-images.githubusercontent.com/22640902/100484801-970bbf80-30dc-11eb-8950-4307b136a029.png)

  **Agent:**
  ![image](https://user-images.githubusercontent.com/22640902/100484923-fff33780-30dc-11eb-9769-07cde49e632c.png)
  ![image](https://user-images.githubusercontent.com/22640902/100484931-0da8bd00-30dd-11eb-8d14-c045e1aeed78.png)


- **Ubuntu 18.04**
**Manager:**
![image](https://user-images.githubusercontent.com/22640902/100480916-65d9c200-30d1-11eb-9c4c-3a781f17b076.png)
![image](https://user-images.githubusercontent.com/22640902/100480926-6ffbc080-30d1-11eb-94e3-ae885f5b240f.png)

  **Agent:**
  ![image](https://user-images.githubusercontent.com/22640902/100483562-2cf11b80-30d8-11eb-902a-be42f3122a3d.png)
  ![image](https://user-images.githubusercontent.com/22640902/100483652-73df1100-30d8-11eb-9eb6-10a159bb6b05.png)



- **Ubuntu 20.04**
**Manager:**
![image](https://user-images.githubusercontent.com/22640902/100486268-fa4c2080-30e1-11eb-959b-1a280bfb0a04.png)
![image](https://user-images.githubusercontent.com/22640902/100486279-0801a600-30e2-11eb-8327-69840ba1e810.png)

  **Agent:**
  ![image](https://user-images.githubusercontent.com/22640902/100486436-95dd9100-30e2-11eb-8a91-494c6ee176e8.png)
  ![image](https://user-images.githubusercontent.com/22640902/100486442-a3931680-30e2-11eb-810f-efd8380c4616.png)


- **Ubuntu 20.10**
**Manager**
![image](https://user-images.githubusercontent.com/22640902/100487708-db9d5800-30e8-11eb-900c-9c11ae537661.png)
![image](https://user-images.githubusercontent.com/22640902/100487724-e7891a00-30e8-11eb-82fe-55161532a4a9.png)

  **Agent**
  ![image](https://user-images.githubusercontent.com/22640902/100487908-cb39ad00-30e9-11eb-9c51-8f2269c8ebac.png)
  ![image](https://user-images.githubusercontent.com/22640902/100487918-dbea2300-30e9-11eb-99c0-97e546d4fda2.png)

**Comment by tinachoB** [comment]
- [X] **CentOS**: 

- **CentOS 6:** Adding `cmake`, `gcc-c++`,  `centos-release-scl` and `devtoolset-7`  new dependencies the following results were obtained (before running `make` and `./install.sh` it's necessary to enable the devtoolset bash: `scl enable devtoolset-7 bash`)

**Uname and gcc/g++ version:**
![image](https://user-images.githubusercontent.com/22640902/100615678-b1b98080-32f6-11eb-8481-4943581ec87f.png)

**Manager**
![image](https://user-images.githubusercontent.com/22640902/100615773-d877b700-32f6-11eb-8e1c-aeaa5a3cfd14.png)
![image](https://user-images.githubusercontent.com/22640902/100615924-15dc4480-32f7-11eb-91dc-a6e1a4f5a0a1.png)

**Agent**
![image](https://user-images.githubusercontent.com/22640902/100616689-3527a180-32f8-11eb-9839-6706cc56881f.png)
![image](https://user-images.githubusercontent.com/22640902/100616842-73bd5c00-32f8-11eb-9306-c8496da4d3c3.png)


- **CentOS 7:** Adding `cmake`, `gcc-c++`,  `centos-release-scl` and `devtoolset-7`  new dependencies the following results were obtained (before running `make` and `./install.sh` it's necessary to enable the devtoolset bash: `scl enable devtoolset-7 bash`)

**Uname and gcc/g++ version:**
![image](https://user-images.githubusercontent.com/22640902/100617879-d6fbbe00-32f9-11eb-9af7-7a7f3f7e5e5b.png)


**Manager**
![image](https://user-images.githubusercontent.com/22640902/100617945-ee3aab80-32f9-11eb-9c73-d9e34d59e3f4.png)
![image](https://user-images.githubusercontent.com/22640902/100618008-027ea880-32fa-11eb-99af-1e815f8620e8.png)


**Agent**
![image](https://user-images.githubusercontent.com/22640902/100618075-19bd9600-32fa-11eb-8d4a-bc11ccc16e25.png)
![image](https://user-images.githubusercontent.com/22640902/100618302-6a34f380-32fa-11eb-9712-d993c7ec05cf.png)


- **CentOS 8:** Changing  original `policycoreutils-python` by  `python3-policycoreutils` and adding `python3`, `cmake`, `gcc-c++` (extra step: `rpm -i http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-8.3.1-5.el8.0.2.x86_64.rpm`)new dependencies the following results were obtained:

**Uname and gcc/g++ version:**
![image](https://user-images.githubusercontent.com/22640902/100618675-ea5b5900-32fa-11eb-8bf3-efe545ac1320.png)


**Manager**
![image](https://user-images.githubusercontent.com/22640902/100619020-55a52b00-32fb-11eb-846d-d864cb0770ad.png)
![image](https://user-images.githubusercontent.com/22640902/100619077-648bdd80-32fb-11eb-9a70-b8bb6afa8f85.png)


**Agent**
![image](https://user-images.githubusercontent.com/22640902/100619133-79687100-32fb-11eb-9057-0700843c4034.png)
![image](https://user-images.githubusercontent.com/22640902/100620415-2a234000-32fd-11eb-8f82-44a49447fd23.png)

**Comment by tinachoB** [comment]
- [X] **macOS:** Adding cmake new dependency the following results were obtained:
**Agent only**
![image](https://user-images.githubusercontent.com/22640902/100659098-e34e3e00-332e-11eb-9a0b-e73fcccbac62.png)
![image](https://user-images.githubusercontent.com/22640902/100659140-f3661d80-332e-11eb-809f-daca496fc4a7.png)

**Comment by tinachoB** [comment]
- [X] **Windows:** Adding `cmake` new dependency the following results were obtained:
**Agent only**
![image](https://user-images.githubusercontent.com/22640902/100659294-2e685100-332f-11eb-8d96-246c3109b81b.png)

**Comment by tinachoB** [comment]
- [X] **Solaris**: 

- **Solaris 10:** Adding: 

```
PATH="${PATH}:/usr/sbin:/usr/bin:/usr/sbin/:/opt/csw/gnu/:/usr/sfw/bin/:/opt/csw/bin/"
export PATH
pkgadd -d http://get.opencsw.org/now


curl -k -O https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.gz
gtar xzf gcc-5.5.0.tar.gz
ln -sf gcc-5.5.0 gcc
cd gcc

wget ftp://gcc.gnu.org/pub/gcc/infrastructure/mpfr-2.4.2.tar.bz2
gtar xjf mpfr-2.4.2.tar.bz2
ln -sf mpfr-2.4.2 mpfr

wget ftp://gcc.gnu.org/pub/gcc/infrastructure/gmp-4.3.2.tar.bz2
gtar xjf gmp-4.3.2.tar.bz2 
ln -sf gmp-4.3.2 gmp

wget ftp://gcc.gnu.org/pub/gcc/infrastructure/mpc-0.8.1.tar.gz
gtar xzf mpc-0.8.1.tar.gz
ln -sf mpc-0.8.1 mpc

wget ftp://gcc.gnu.org/pub/gcc/infrastructure/isl-0.14.tar.bz2
gtar xjf isl-0.14.tar.bz2 
ln -sf isl-0.14 isl

cd ..
mkdir -p gcc-build
cd gcc-build
../gcc/configure --prefix=/usr/local/gcc-5.5.0 --enable-languages=c,c++ --disable-multilib --disable-libsanitizer --disable-bootstrap --with-gnu-as --with-as=/opt/csw/bin/gas
gmake
gmake install
echo "export PATH=/usr/local/gcc-5.5.0/bin:${PATH}" >> /etc/profile
PATH="/usr/local/gcc-5.5.0/bin:${PATH}"
export PATH
CPLUS_INCLUDE_PATH=/usr/local/gcc-5.5.0/include/c++/5.5.0/
export CPLUS_INCLUDE_PATH
LD_LIBRARY_PATH=/usr/local/gcc-5.5.0/lib/
export LD_LIBRARY_PATH
cd ..

curl -O -L https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2.tar.gz
gtar xzf cmake-3.18.2.tar.gz
ln -sf cmake-3.18.2 cmake
cd cmake
./bootstrap
gmake
gmake install
PATH="${PATH}:/usr/local/bin"
export PATH
```
following results were obtained:

**Uname and gcc/g++ version:**
![image](https://user-images.githubusercontent.com/22640902/100944225-952b6d00-34dd-11eb-88b6-8e86a2ef706f.png)

- **Solaris 11:** Adding:

```
/opt/csw/bin/pkgutil -y -U
/opt/csw/bin/pkgutil -y -i python27
ln -sf /opt/csw/bin/python2.7 /usr/bin/python
/opt/csw/bin/pkgutil -y -i git gmake gcc5core gcc5g++
export PATH="${PATH}:/usr/sfw/bin:/opt/csw/bin:/opt/ccs/bin"
pkg install gcc-45

curl -O https://ftp.gnu.org/gnu/gcc/gcc-5.5.0/gcc-5.5.0.tar.gz
gtar xzf gcc-5.5.0.tar.gz
ln -sf gcc-5.5.0 gcc
cd gcc && ./contrib/download_prerequisites
cd .. && mkdir -p gcc-build && cd gcc-build
../gcc/configure --prefix=/usr/local/gcc-5.5.0 --enable-languages=c,c++ --disable-multilib --disable-libsanitizer --disable-bootstrap --with-ld=/usr/ccs/bin/ld --without-gnu-ld --with-gnu-as --with-as=/opt/csw/bin/gas
gmake
gmake install
cd ..

export PATH=/usr/local/gcc-5.5.0/bin/:/usr/local/bin/:/usr/bin/:/usr/sbin/:$PATH
export CPLUS_INCLUDE_PATH=/usr/local/gcc-5.5.0/include/c++/5.5.0/
export LD_LIBRARY_PATH=/usr/local/gcc-5.5.0/lib/

curl -O -L https://github.com/Kitware/CMake/releases/download/v3.18.2/cmake-3.18.2.tar.gz
gtar xzf cmake-3.18.2.tar.gz
ln -sf cmake-3.18.2 cmake
cd cmake
./bootstrap
gmake
gmake install
```
new dependencies and libs the following results were obtained:

**Uname and gcc/g++ version:**
![image](https://user-images.githubusercontent.com/22640902/100915382-0b66aa00-34b3-11eb-9736-d7a169b1234f.png)


**Agent**
![image](https://user-images.githubusercontent.com/22640902/100915425-191c2f80-34b3-11eb-9132-52bc684ae559.png)
![image](https://user-images.githubusercontent.com/22640902/100915574-4cf75500-34b3-11eb-8edd-a839d6b2632a.png)

**Comment by tinachoB** [comment]
Work for this issue has been placed in the https://github.com/wazuh/wazuh-documentation/pull/3206 PR of the wazuh-documentation repository. Once the entire epic is merged, this PR will be merged to.
Closing this now.
