### ISSUE TITLE
RBAC database upgrade and migration

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#6652]
Hello team,

With the Wazuh `4.1.0` release we will apply some modifications to the existing `RBAC.db`. New entities will be added to the existing tables along with a few other changes. Taking into account the user may have applied some changes to the database, such as adding new roles, policies, etc, we should create a migration process that guarantees the new changes will be applied without affecting the information already stored in the database.

This issue should take care of the required refactors and improvements to the RBAC database, the Wazuh API and the Framework.

**WORKING_BRANCH**: [dev-rbac-upgrade-and-migration](https://github.com/wazuh/wazuh/tree/dev-rbac-upgrade-and-migration)
**TARGET_WAZUH_BRANCH**: [master](https://github.com/wazuh/wazuh/)

**DOCUMENTATION_BRANCH**: [dev-rbac-upgrade-and-migration](https://github.com/wazuh/wazuh-documentation/tree/dev-rbac-upgrade-and-migration)
**TARGET_DOCU_BRANCH**: [develop](https://github.com/wazuh/wazuh-documentation/)

Latest rebase of  **dev-rbac-upgrade-and-migration (working)** with **Master**: Aug, 02 - 09:25 CET
Latest rebase of **dev-rbac-upgrade-and-migration (docu)** with **Master**: Aug, 02 - 09:25 CET

**Comment by CarlosRS9** [comment]
## Issue update
Hello team,

Remember to use the main branch as base for each issue.

| Main branch |
|-|
| [dev-rbac-upgrade-and-migration](https://github.com/wazuh/wazuh/tree/feature/dev-rbac-upgrade-and-migration) |

> **EDIT:** Last rebase from `master` on February, 22th - 9:37 CET

**Comment by davidjiglesias** [comment]
@CarlosRS9 please keep the branches updated
