### ISSUE TITLE
 ossec-remoted: CRITICAL: (1206): Unable to Bind port '514' due to [(99)-(Cannot assign requested address)]

### ISSUE THREAD

**Issue by sadbosan** [wazuh/wazuh#6671]
ossec-remoted: CRITICAL: (1206): Unable to Bind port '514' due to [(99)-(Cannot assign requested address)]
why prot 514 can not bind....
syslog message did not wirte in /var/ossec/logs/archives.log

**Comment by JcabreraC** [comment]
Hello @sadbosan 

Could you share the `remote` block of the `/var/ossec/etc/ossec.conf` file ?

It is possible that you have used the `local_ip` tag incorrectly.

Regards

**Comment by sadbosan** [comment]
I found the problem

**Comment by sadbosan** [comment]
local ip should be the docker's IP，not the Host IP.....

**Comment by JcabreraC** [comment]
Ok, I'm glad your problem has been solved.

Kind regards.
