### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by salyh** [wazuh/wazuh#67]
Last release is more than half a year old (and 652 commits behind master). 
Any plans to make a new release soon?

**Comment by jlruizmlg** [comment]
Hi @salyh will be very soon, meanwhile you can review the changelog (so far) in the following link
https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md

Thanks!!

**Comment by snaow** [comment]
Hi @salyh, 

You are right, but we have an explanation for that, Wazuh 2.0 will be awesome :D ! Let me describe briefly the new features (currently found under the master branch):


- OpenSCAP integrated as part of the agent, allowing users to run OVAL checks.
- New WUI on top of Kibana 5, and integrated with the RESTful API to monitor configuration of the manager, rules and status of the agents.
- Improved log analysis and FIM capabilities.
- Ruleset with compliance mapping.
- Agent-manager communications over TCP supported.
- A modules manager that will allow future integration of other tools (in the roadmap is OSquery and Threat Intelligence sources)

If you are curious, here are some screenshots of the WUI.

[Wazuh 2.0 in-progress docs - Wazuh Kibana App](https://github.com/wazuh/wazuh-documentation/blob/new_template/source/index.rst)


Please feel free to give it a try, any feedback is very welcome!.

**Comment by k2nr** [comment]
@snaow Would upgrading from the current release (1.1.1) to 2.0 easy to do? Currently I'm planing to use wazuh in our PCI-compliant system and I am wondering if I should continue to work on wazuh 1.1.1 or I should wait for 2.0 to be released.
Thanks!

**Comment by snaow** [comment]
Hi @k2nr,

Yes, it will be easy to do, we will publish a detailed guide to upgrade from Wazuh 1.1.1 (sources) to Wazuh 2.0 packages or sources.

Consider how many agents are you going to deploy using sources installation, you will need to follow a manual process to upgrade each agent to 2.0 version (cause you won't have any package rpm/deb installed).

For further versions upgrading will be easier using yum/apt update tools.

**Comment by k2nr** [comment]
@snaow Hi, that's great. Thanks for letting me know!

**Comment by TamalSaha** [comment]
Hi, is there any updated on this front?

**Comment by jlruizmlg** [comment]
Hello,

We are finishing documentation, and the release will be very soon. If you
have more information, or test or new packages take a look in the following
link:

http://documentation-dev.wazuh.com (notice that this documentation is still
under construction).

Regards
-----------------------
Jose Luis Ruiz
Wazuh Inc.
jose@wazuh.com

On March 14, 2017 at 3:14:10 PM, Tamal Saha (notifications@github.com)
wrote:

Hi, is there any updated on this front?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/wazuh/wazuh/issues/67#issuecomment-286529863>, or mute
the thread

**Comment by TamalSaha** [comment]
Can you give any idea how does it compare to the https://github.com/ossec/ossec-hids/releases ? Does wazuh fork periodically pull from that ?

**Comment by jlruizmlg** [comment]
Hi @TamalSaha here the changeling

https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md

And the @snaow explanation above:

Let me describe briefly the new features (currently found under the master branch):

OpenSCAP integrated as part of the agent, allowing users to run OVAL checks.
New WUI on top of Kibana 5, and integrated with the RESTful API to monitor configuration of the manager, rules and status of the agents.
Improved log analysis and FIM capabilities.
Ruleset with compliance mapping.
Agent-manager communications over TCP supported.
A modules manager that will allow future integration of other tools (in the roadmap is OSquery and Threat Intelligence sources)
If you are curious, here are some screenshots of the WUI.

Wazuh 2.0 in-progress docs - Wazuh Kibana App

**Comment by snaow** [comment]
Hi Tamal,

Yes, we do, every Wazuh release includes all the latest commits (if they
make sense) from ossec-hids.
Same way, we try to contribute back to ossec-hids sending Pull Requests for
critical bugs or fixes.

We are close to finish and release the latest Wazuh 2.0 version, thanks for
your patience.

Cheers,
Pedro Sanchez.

**Comment by elisiano** [comment]
Is there an estimate for the official 2.0 release?

**Comment by jlruizmlg** [comment]
Hi @elisiano the code is done, you can install Wazuh 2.0 using this link: https://github.com/wazuh/wazuh/tree/2.0
 
If the code is done, why haven’t we released it?
 
We are now working on the documentation (uses cases, installation guide, components, etc.) and different modules like Puppet, Docker, Ansible, SaltStack, and more which is very important for us and the community.
 
If you install the stable branch 2.0 from the link above or our packages from the following link you will be using Wazuh 2.0
 
https://documentation-dev.wazuh.com/index.html

**Comment by elisiano** [comment]
Thanks @jlruizmlg, I was able to bring up a hybrid environment (manager with docker stack, agents installed regularly with puppet: including ossec::agent disabling key management).

Although I'm having some issues, I'll open a separate ticket for that.

**Comment by hex2a** [comment]
@elisiano there will be a new puppet module for wazuh 2.0 agent/manager, which adds support for adding new agents using authd

**Comment by elisiano** [comment]
@hex2a thanks, so I've been told. But I can't tell my boss to wait for that, we have a deadline 😄.
So for now I'll find some workaround and when the new module will be released I'll revisit.

And for the clients: I'm already using authd (actually when you set ossecc:client::manage_agent_keys to false it already uses agent-auth against authd).
