### ISSUE TITLE
Distributed API

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#670]
Since we have several managers with the API installed, it is necessary to distribute the API requests to the proper node (master or client).

#### Classify requests
Each API request must be classifed in 3 categories:
 - `local_any`: This request can be performed by any node and locally (no distributed).
   - Example: `/rules`.
 - `local_master`: This request can be performed by the master node and locally (no distributed).
   - Example: `/agents`
 - `distributed_master`: This request is forwarded to the master, if necessary. Then, the master will distribute the request and merge the response.
    - Example: `/agents/001/restart` - It must be forwarded to the node where the agent 001 is connected.

#### Request flow

1. API receives a request.
2. If it is a client node:
   - If it is local_any: Respond.
   - If it is distribued_master but for only that node (it contains the agent 001 in the previous example): Respond.
   - Otherwise, forward to the master.
3. If it is a master node or it is forwarded from a client:
   - If it is local_master: Respond or forward response.
   - if it is distributed_master:
     - Forward request to the corresponding nodes.
     - Wait and merge responses.
     - Forward response.

#### New requests

We will need to add new requests to get the information of a specific node. Example:
   - /cluster/:node_id/logs

#### Notes

- Communications between nodes (wazuh-clusterd) must be closed instantanealy. Don't use busy waiting.
- wazuh-api waits until wazuh-clusterd has everything ready, but it doesn't prevent other services (wazuh-clusterd, cluster_control, remote wazuh-clusterd) to use the cluster.

**Comment by mgmacias95** [comment]
Currently defined tasks:

- [x] Refactor internal socket code (8e2d75da1a55803a804f48337a964bf96c1a98d9 079fd7b55a5d5f20513ff284528287de5b55aceb)
- [x] Add distributed api (`local_master` requests) support in internal socket (2991973c9d67fc20fa47ee25855a9c939bbcc139 16f4867758a00d221fdb7895617e57dc020028e3)
- [x] Replicate API funcionality in distribute API module (fa9b28ab4e5d3efb4f741609abafb26ed4c54e81 b7e01d777ef4bcbb477d8aadb7e18936a34d9108)
- [x] Add `local_any` requests (ac09fbff1a05eee9bf71565b8da2e34fcd3b5540)
- [ ] Add `distributed_master` requests forwarding requests to one node only.
- [ ] Support forwarding requests to multiple nodes and merge results.
- [ ] Create a thread in cluster to process distributed api requests there.

**Comment by mgmacias95** [comment]
After some testing, I found out the following errors that need to be fixed before merging:

* [ ] After restarting the master node, the cluster raises the _"there's already an instance of wazuh-clusterd running"_ error.
* [ ] Syscollector API calls from client nodes raise lots of _"Resource temporary unavailable"_ errors .
