### ISSUE TITLE
how to compile the source code to a executable file?

### ISSUE THREAD

**Issue by 040840308** [wazuh/wazuh#6701]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by 040840308** [comment]
Is there someone to share instructions about how to compile WAZUH source code? Does Visual Studio 2019 work?

Thanks

**Comment by Dwordcito** [comment]
Hi @040840308 I hope you are well!

I suggest these two documentation guides that I leave below, they mention what you must do to compile wazuh on windows, for now we are not compiling the product from windows, but we are cross-compiling from linux with mingw.

In one extract it indicates the step by step to compile the agent and in the other the possible flags of the makefile.

ex:
make deps && make TARGET=winagent

this from the "src" folder would compile the executables.



https://documentation.wazuh.com/4.0/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.html
https://documentation.wazuh.com/4.0/development/makefile.html

**Comment by 040840308** [comment]
> Hi @040840308 I hope you are well!
> 
> I suggest these two documentation guides that I leave below, they mention what you must do to compile wazuh on windows, for now we are not compiling the product from windows, but we are cross-compiling from linux with mingw.
> 
> In one extract it indicates the step by step to compile the agent and in the other the possible flags of the makefile.
> 
> ex:
> make deps && make TARGET=winagent
> 
> this from the "src" folder would compile the executables.
> 
> https://documentation.wazuh.com/4.0/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.html
> https://documentation.wazuh.com/4.0/development/makefile.html

Let me have a try. Thanks a lot.

**Comment by Dwordcito** [comment]
Sure, reopen the issue if you have some related issue, thanks for your question!
