### ISSUE TITLE
Review the MSU recursion when building and scanning 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6715]
### Description

The MSU generation, as well as the use of its data when scanning Windows agents are recursive processes. However, there are been identified cases where this recursion is broken, at least when the MSU is generated.

The case of `KB4512578` was [reported by the Operations team](https://wazuh-team.slack.com/archives/GPAMKJHDM/p1605301082049800) a week ago:

![image](https://user-images.githubusercontent.com/29475387/100078475-d9ff3600-2e43-11eb-95c3-6a8c383d0700.png)

It seems the stairs of dependencies are not completed for these patches.

We have to review how the recursion is implemented to ensure it covers all the steps to correlate patches when generating the MSU and, after that, storing the data into the database and scanning the Windows vulnerabilities.

_Note: Check if forward recursion is sufficient to ensure all dependencies are covered._

**Comment by 0xN3utr0n** [comment]
PR with the fix https://github.com/wazuh/wazuh-tools/pull/88

**Comment by chemamartinez** [comment]
Fixed in the MSU generation process. Thanks @0xN3utr0n!
