### ISSUE TITLE
Wazuh agent on Windows

### ISSUE THREAD

**Issue by jstawowczyk** [wazuh/wazuh#6721]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.09 | Wazuh | Agent | Packages| Windows Server 2012R2 64bit|

Why Wazuh agent reread and resend to Wazuh manager all log records from monitored log files after agent restart? Result is that log records are duplicated in Wazuh/Elasticsearch?

**Comment by jnasselle** [comment]
Hello @jstawowczyk!

It's seems that the behavior you describe is related to this issue #4030 . Let me replicate your environment with that specific Wazuh version in order to make a workaround.

I will keep you posted.
Regards.

**Comment by jstawowczyk** [comment]
I upgraded agent to version 3.13.2 and problem still exist.

**Comment by jnasselle** [comment]
Hi @jstawowczyk !

Thank you for your patience. After an analyzing and reproducing your issue, we decide to label this issue as duplicate in flavor of  an older one with the sames characteristics: #5684 

You can follow the progress of the issue there.

Regards,
Nico
