### ISSUE TITLE
Custom integration and negative condition

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh#6723]
Hello!
I wrote custom script for integration with Telegram. We want to send an alert if level >= 12 and group is NOT vulnerability-detector. 
```
<integration>
  <name>custom-integration</name>
  <hook_url>WEBHOOK</hook_url>
  <level>10</level>
  <group>multiple_drops|authentication_failures</group>
  <api_key>APIKEY</api_key> <!-- Replace with your external service API key -->
  <alert_format>json</alert_format>
</integration>
```
But I can not understand how to set negative condition.

**Comment by pereyra-m** [comment]
Hello @VN1977 !

Thank you for opening this issue.
Unfortunately, the current **integrator** code doesn't allow a negative group filter. This is an interesting feature, so I'll leave the issue open and tagged like _enhancement_ so we can add it to our roadmap as soon as possible.

In the meantime, I think that some processing inside the script may be enough to receive only the desired alerts.
If we follow the blog entry about integrations: [How to integrate external software using Integrator](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/), we can find a reference about a custom script extracting all the desired fields from the alert:

```
alert_level = alert_json['rule']['level']
description = alert_json['rule']['description']
```

So, you could do something like this to extract all the groups from that alert and discard it if you find the vulnerability detector group:

`alert_groups = alert_json['rule']['groups']`

You can also share your script if you need more help to make it work.
Have a nice day!

Regards.

**Comment by VN1977** [comment]
Hi,
here are my scripts.
I use it this way:
  <integration>
    <name>custom-telegram</name>
    <hook_url>https://api.telegram.org/bot@1234567,9876543@vulnerability-detector</hook_url>
    <api_key>my_secure_key</api_key>
	<level>11</level>
    <alert_format>json</alert_format>
  </integration>

**Comment by pereyra-m** [comment]
Hello again @VN1977 !

Thank you for sharing your scripts.
Are they working now? What is the problem you are experiencing ?
Regards.

**Comment by VN1977** [comment]
Hi,
Yes, they work, but you need to correct indent in py-script in one string. 
I found this error later after uploading to the topic.
My problems connected with the necessity to restrict notifications to 
telegram about vulnerabilities and have alerts level higher 11 only.

**Comment by palaciosjeremias** [comment]
Hello @VN1977,
This happens because the **<level>** section of **<integration>** config sets a level filter so that the script will not receive alerts below this configured level (in your case **11**).
Alert levels are used across different Wazuh features to allow the user to define the threshold that triggers actions in general. In this case, it is used to filter the triggering of your script.
If you want to trigger your integrator script with alerts higher or equal to **12**, you have to set the **<level>** section on **12**.
Please let me know if I get you right and if your scripts are working fine but your problem was the triggering level of the alert.
Best regards.

**Comment by VN1977** [comment]
Hello,
My scripts works fine and you didn't get my main problem which is connected 
with excluding alerts about vulnerabilities as I wrote at the begining. I 
could earlier and can now define alerting level in ossec.conf and have no 
problem with this.
So after I have solved my problem I share my way with you and you can share 
it with community. If you ever develop more modern method filtering groups 
directly in ossec.conf this scripts should be changed.

**Comment by palaciosjeremias** [comment]
Hello again @VN1977.
I see. Thank you for sharing with us the script that lets you filter the group.
Glad to hear your problem is solved then!
If you agree I will close this issue now.
Best regards.

**Comment by VN1977** [comment]
Hello,
Yes, close the issue.

**Comment by palaciosjeremias** [comment]
OK. I am closing the problem since it is resolved now.
Thanks again for sharing this information with us.
Best regards.
