### ISSUE TITLE
Changing Wazuh Credentials Does Not Work

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh#6725]
Using docker image wazuh/wazuh:3.9.3_7.2.0 

Per https://documentation.wazuh.com/3.13/installation-guide/securing_api.html, this does not work (tested for user 'foo'): 
"Option b: Change the default credentials manually using the following commands:
cd /var/ossec/api/configuration/auth
node htpasswd -Bc -C 10 user myUserName"

Has this been tested and/or fixed?

**Comment by AdriiiPRodri** [comment]
Hi alphaDev23,

This procedure should work properly, it is essential to restart the API service after changing the password for it to take effect: 
```
root@wazuh-manager:/# curl -k -u foo:bar "https://localhost:55000?pretty"
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.9.3",
      "hostname": "wazuh-manager",
      "timestamp": "Wed Nov 25 2020 08:43:58 GMT+0000 (UTC)"
   }
}
root@wazuh-manager:/# cd /var/ossec/api/configuration/auth
root@wazuh-manager:/var/ossec/api/configuration/auth# node htpasswd -Bc -C 10 user foo
New password: 
Re-type new password: 
Adding password for user foo.
root@wazuh-manager:/var/ossec/api/configuration/auth# curl -k -u foo:testing6725 "https://localhost:55000?pretty"
401 Unauthorized
root@wazuh-manager:/var/ossec/api/confcurl -k -u foo:bar "https://localhost:55000?pretty"
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.9.3",
      "hostname": "wazuh-manager",
      "timestamp": "Wed Nov 25 2020 08:45:17 GMT+0000 (UTC)"
   }
}
root@wazuh-manager:/var/ossec/api/configuration/auth# service wazuh-api restart
WAZUH-API stopped.
WAZUH-API started.
root@wazuh-manager:/var/ossec/api/configuration/auth# curl -k -u foo:bar "https://localhost:55000?pretty"
401 Unauthorized
root@wazuh-manager:/var/ossec/api/configuration/auth# curl -k -u foo:testing6725 "https://localhost:55000?pretty"
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.9.3",
      "hostname": "wazuh-manager",
      "timestamp": "Wed Nov 25 2020 08:45:48 GMT+0000 (UTC)"
   }
}
```

When you execute the node command, do you get any errors?

On the other hand, I recommend you to take a look at [Wazuh 4.0](https://documentation.wazuh.com/4.0/release-notes/index.html). In this new version, besides multiple improvements in all areas, the API has changed radically and offers better support for users and general security.

Best regards,
Adrián Peña

**Comment by AdriiiPRodri** [comment]
Close this issue due to inactivity. Feel free to reopen it if you have any questions.

Regards
