### ISSUE TITLE
Add support for Amazon Linux in Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6734]
### Description

The aim of this issue is to add native support of vulnerability scans to Amazon Linux.

Since the addition of Vulnerability Detector, Amazon Linux agents were supported by assigning them the Redhat feeds. However, it was not accurate enough since the target of these feeds is RHEL systems, so the scan could lead to false positives as reported in https://github.com/wazuh/wazuh/issues/3952.

In Wazuh v3.13.0 we decided to deprecate that compatibility (https://github.com/wazuh/wazuh/pull/5089) letting the possibility to force it manually via configuration:

```xml
<os allow="Amazon Linux-2">7</os>
```

The goal now is to incorporate the [Amazon Linux Security bulletins](https://alas.aws.amazon.com/) as another Wazuh's vulnerability feed so the scanner is able to detect vulnerabilities of packages from the AL repositories.

**Comment by shurex** [comment]
hello @chemamartinez , thank you for raising this, I'm waiting for this feature for a long time.
have you had any joy with this in the roadmap @vikman90 ? do we know the ETA ?
thank you guys

**Comment by chemamartinez** [comment]
Hi @shurex,

**Comment by chemamartinez** [comment]
Hi @shurex,

First of all thanks for your feedback.

We share yours feels in the way that this development is a priority for us as well. It is that why it is already included in [our product roadmap](https://github.com/wazuh/wazuh/projects/41). As you can see, it is included in the list of the features which will be included in the medium term.

We cannot provide you an ETA for this feature yet. However, we will start to work on it soon.

Hope this information is helpful for you.

**Comment by chemamartinez** [comment]
Main devel branch: https://github.com/wazuh/wazuh/tree/6734-alas-support
