### ISSUE TITLE
Issues with restart all, restart by node and restart by group requests in big environments

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6748]
Hello team,

As part of the investigation for https://github.com/wazuh/wazuh/issues/6744 we have discovered a possible timeout and performance issue related with `PUT /agents/restart`, `PUT /agents/node/{node_id}/restart` and `PUT /agents/group/{group_id}/restart` in loaded environments.

Due to the RBAC changes in Wazuh v.4.0.0, it is not possible to restart all agents at once due to permissions from users. For that reason, in environments with a lot of agents, these calls may take a lot of time to process since they restart the agents 1 by 1, following a list of permitted agents.

There is not a possible solution within the current code iteration and I suggest to disable the endpoints until a proper fix is done in the next major version of Wazuh.

For such solution, I propose the usage of tasks. In these cases, the API would process the restart petitions, start tasks for the restart of those agents and provide a response with the task_ids. Later on, the user could check the status of all or some of those tasks using the appropriate endpoints. 

The API should never wait until all the processing is finished for such long tasks.

Regards,

David J. Iglesias

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

This issue is going to be closed as this was also reported and will be fixed in the issue https://github.com/wazuh/wazuh/issues/8870
