### ISSUE TITLE
Issue with PUT /agents/group in big environments

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#6749]
Hello team,

As part of the investigation for https://github.com/wazuh/wazuh/issues/6744 we have discovered a possible timeout and performance issue related with `PUT /agents/group` in loaded environments.

This call tries to add all agents in the system (permitted agents) to a single group. However, the agents are added to the agent-group files 1 by 1 and after a number of checks. Doing such processing for each single agent may take a very long time when the agents in the system are thousands.

There is not a possible solution within the current code iteration and I suggest to disable the endpoint until a proper fix is done in the next major version of Wazuh.

For such solution, we have to further investigate the code to try and make it more efficient for the current task.

Regards,

David J. Iglesias

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

I made a few improvements for this endpoint, reducing the time it takes to process a big number of agents. In its current state, it could scale up to 100k agents (for a single group). Although a full rework could probably improve its performance, I believe the current implementation is enough for now.

![image](https://user-images.githubusercontent.com/37274979/121326900-3ffc6800-c913-11eb-9995-87fe37b6f87f.png)

Regards,
Víctor

**Comment by vicferpoy** [comment]
## Issue update
This is the result after a few improvements:

![image](https://user-images.githubusercontent.com/37274979/122368966-128c6b80-cf5e-11eb-882e-54b1b7d9e54d.png)

Regards,
Víctor
