### ISSUE TITLE
Investigate and fix agents reporting to a deleted worker node

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6764]
|Component|
|---|
| Wazuh clusterd |

## Description
Hello team!

It is necessary to investigate if an error still occurs in which the agents that reported a worker, if load balancer is not used and the worker is eliminated, the master thinks that the agents continue to report to the eliminated node.

In case the problem still exists, it needs to be fixed.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Best regards, 
Selu.

**Comment by mcarmona99** [comment]
### Issue status

The error still occurs.

I have replicated the error following these steps. I have used our wazuh development docker environment (**1 master, 2 worker, 1 agent** reporting to load balancer).

First I have changed the agent's configuration to stop reporting the load balancer. I have set the address of the server to the `worker1` IP so now, the agent is reporting to **worker1 without LB.**

`/var/ossec/bin/cluster_control -a
`

```
ID   NAME          IP          STATUS  VERSION       NODE NAME
000  wazuh-master  127.0.0.1   active  Wazuh v4.3.0  master-node
001  f5003c8ff27a  172.19.0.3  active  Wazuh v4.3.0  worker1
```

After that, I disable (disabled=yes) the worker1 cluster configuration. The `cluster_control` output is the same so I can confirm this error is still ocurring.

With load balancer, if I disable worker1, the agent will report a different cluster node with no problems.

Regards,
Manuel.

**Comment by mcarmona99** [comment]
### Issue status

The `cluster_control` CLI is calling our framework function `get_agents`.

This function calls the `WazuhDBQueryAgents` class that look for information in the `global.db`. The information of the agent reporting to a non-existing node remains the same as there were no changes before the worker broke down.


When we use an endpoint to work with agents, a **forward request** to the node it reports to is sent.
In our case, the request is forwarded to a broken node. This is what was causing problems in the past but now, this error is handled here:

https://github.com/wazuh/wazuh/blob/ae7d0ea8b5e78cb6169f34cc2b0cab2127f3c5da/framework/wazuh/core/cluster/dapi/dapi.py#L422-L426

When we forward a request to an unknown node, the 3022 error code appears. For example, when we try to restart the agent reporting the broken node with the API, this is the response:

**API request:**

`PUT /agents/001/restart`

**Response:** 

```
{
  "title": "Wazuh Cluster Error",
  "detail": "Unknown node ID",
  "remediation": "Check the name of the node",
  "error": 3022
}
```

I am closing this issue as the error was fixed.

Regards,
Manuel.
