### ISSUE TITLE
Repeated offenders didnt work in active-response conf

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#678]
Hi Wazuh team!

I have this problem, first thing first, take a look at this picture

![1](https://user-images.githubusercontent.com/24579576/40597305-3a7a7aca-6273-11e8-8bfb-643f7a011dc7.JPG)

As you can see at above screenshot, it said that an alert 15 was triggered at `08:40:05`, from IP 104.128.69.56. I have set my active-response, if rule with id 4709 triggered, it would blocked the the ip using firewall-drop. for the configuration, as shown below:

![2](https://user-images.githubusercontent.com/24579576/40597306-3ab28a8c-6273-11e8-8305-0d9d29b9c902.JPG)

I set the time to 1800 seconds, or 30 minutes. It works well because it's unblocked at `09:10` which is 30 minutes later. After that, the rule was triggered again by the same IP, ofcourse it will got blocked again at `11:45`. When the second tried blocked occured, i assume the `repeated_offenders` would works, whic is will blocked the the IP for `1440` minutes, but it only blocked for about 30 minutes, as you can see above log, it's unblocked at `12:15` which is 30 minutes later, same amount of time with the first one. 

do you know why is this happen ?

**Comment by chemamartinez** [comment]
Hi @gagantous ,

Have you set the `repeated_offenders` in the `ossec.conf` of the agent that triggered the alert? Unfortunately, as the documentation explains in the following link:
https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/active-response.html#repeated-offenders

That option has to be set always on the configuration file of the agent that will run the active-response.  If this is not your case, could you tell us the version of Wazuh manager and agent that have you installed to try to reproduce the issue in our labs?

Thank you!

**Comment by gagantous** [comment]
So i have to set the repeated_offenders on each ossec agent ? Not only in ossec server ?

**Comment by chemamartinez** [comment]
I am afraid so, yes.

For now, it is necessary due to is the agent who has to know which timeout will use in each iteration of the active response. Despite this, we will take a look at this trying to find a solution which allows us to centralize that configuration.

**Comment by gagantous** [comment]
@chemamartinez 

So which configuration format should i use on each ossec.conf agent?  

like this( same configuration with the ossec server)  ?

```
<active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>4709</rules_id>
    <timeout>1800</timeout>
  <repeated_offenders>1440</repeated_offenders>
</active-response>
```
or like this ?

```
<active-response>
  <repeated_offenders>1440</repeated_offenders>
</active-response>
```

but if i used the second option, how do ossec now that "this" active response was intended for this conf ?

```
<active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>4709</rules_id>
    <timeout>1800</timeout>
  <repeated_offenders>1440</repeated_offenders>
</active-response>
```

**Comment by gagantous** [comment]
HI @chemamartinez 

Well i havent tried to configure ossec.conf file on each agent but, even in `ossec.conf` server, repeated_offender didnt workd too. Take a look at this log

![4](https://user-images.githubusercontent.com/24579576/40631246-768d7b94-630d-11e8-8681-fbcb827b8cfb.JPG)

**Comment by chemamartinez** [comment]
Hi @gagantous,

I have tried to reproduce your issue and `<repeated_offenders>` works for me in the manager and agents.

Despite this, this feature has some important limitations which make a little bit tricky to work with it, I have opened an issue to fix them as soon as possible (https://github.com/wazuh/wazuh/issues/683) where you can follow the status of that task.

As I explained in the issue, that field will only be applied whether it is set in the first `<active-response>` block of the configuration file. Could you ensure that is that your case?

After that, you could restart your Wazuh manager and look for any line like the following ones in the `ossec.log` file:

```
2018/05/29 14:58:33 ossec-execd: INFO: Adding offenders timeout: 1 (for #1)
2018/05/29 14:58:33 ossec-execd: INFO: Adding offenders timeout: 2 (for #2)
2018/05/29 14:58:33 ossec-execd: INFO: Adding offenders timeout: 3 (for #3)
```

They are the proof that the configuration is being read properly.

Apart from that, I see in your logs that there is a four-hour difference between each execution, it is possible that the manager was restarted in that period? It could explain that the counter was reloaded and it used the 30 minutes timeout again.

Answering to your question about the format in the agent's `ossec.conf`, it is enough by setting the following block:

```
<active-response>
  <repeated_offenders>1440</repeated_offenders>
</active-response>
```

But notice that it exists another `active-response` block by default, so you must write it above the default one.

**Comment by chemamartinez** [comment]
@gagantous,

There is no way of restarting Wazuh without reading the configuration again. This means that daemons like `execd` in charge of active-response will reload its internal variables.

Could you tell me what is the desired scenario you want to deploy to look for a workaround? I think mixing CDB lists with the `repeated_offenders` feature of active-response may cause a conflict like this one.

Thank you!

**Comment by gagantous** [comment]
@chemamartinez 

is it possible for `ossec-makelist` not to be restarted to update the CDB list ?

**Comment by gagantous** [comment]
@chemamartinez 

how do i make that cron job ?

**Comment by chemamartinez** [comment]
Hi @gagantous,

It an easy task, you could type the command `contrab -e` to edit the existing crontab in your system. Once editing them, add the following line, for example:

```
0 4 * * * /bin/bash /root/update_CDB.sh
```

After that, you can list your defined cronjobs with `crontab -l`. In the following link you have a more complex guide of doing this:

https://code.tutsplus.com/tutorials/scheduling-tasks-with-cron-jobs--net-8800

As you commented before, you could also use the wodle `command` to face this task.

Best regards,
Chema.

**Comment by gagantous** [comment]
Thanks for the fixed issue with active response! 
Really appreciate it, for all the the who works on it! Thanks

Best regards 
Fathin
