### ISSUE TITLE
How to skip the IP if there is already the same IP on CDB list  ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#679]
Hi, Wazuh team:, 

I have some question about my CDB list that added some existed IP that were already listed before. like below

```
61.177.172.42:Brute force attack
42.7.26.91:Brute force attack
61.177.172.42:Brute force attack
61.177.172.42:Brute force attack
103.207.37.216:Brute force attack
61.177.172.42:Brute force attack
61.177.172.42:Brute force attack
104.128.69.56:Brute force attack
60.173.82.156:Brute force attack
103.99.3.97:Brute force attack
5.188.10.182:Brute force attack
104.128.69.56:Brute force attack
103.207.37.216:Brute force attack
61.177.172.20:Brute force attack
5.188.10.156:Brute force attack
193.201.224.212:Brute force attack
104.128.69.56:Brute force attack
109.248.9.9:Brute force attack
5.188.10.180:Brute force attack
109.248.9.9:Brute force attack
125.212.254.94:Brute force attack
181.214.87.4:Brute force attack
103.99.3.237:Brute force attack
103.207.37.129:Brute force attack
212.83.136.196:Brute force attack
```

As you can see there are so many same ip that were added into CDB list, i want to prevent this, but how can i do that ? 

this is my conf, at `ossec.conf`

```
<command>
    <name>block-IP</name>
    <executable>block-IP.sh</executable>
    <timeout_allowed>no</timeout_allowed>
    <expect>srcip</expect>
</command>

<active-response>
    <command>block-IP</command>
    <location>local</location>
    <rules_id>5712,602</rules_id>
</active-response>

```
and my `block-IP.sh` file

```
IP=$3
BL_DIR="/var/ossec/etc/lists/IP-blacklist"

echo "$IP:Brute force attack" >> $BL_DIR
```

Regards
Fathin

**Comment by chemamartinez** [comment]
Hi @gagantous , 

As I see in your `block-IP.sh` script, you will always add the IP incoming from the decoded alerts to the CDB list. I recommend you to replace that piece of code by the following one, for example.

```
IP=$3
BL_DIR="/var/ossec/etc/lists/IP-blacklist"

if ! grep -q "$IP" $BL_DIR ; then
        echo "$IP:Brute force attack" >> $BL_DIR
fi
```

This way, the IP will only be added to the CDB list for the first time it appears.

Best regards,
Chema.

**Comment by gagantous** [comment]
Hi @chemamartinez,

Do i have to configure CDB list on each ossec agent ? or only on ossec server ?

**Comment by gagantous** [comment]
@chemamartinez 

What's the reason we use `-q` in grep option ?  i tried that in my terminal, using that command, and it gave nothing. what `-q` do on that syntax ?

**Comment by chemamartinez** [comment]
Hi again @gagantous,

Answering your first question, seeing your configuration, the CDB lists will be created in every host that runs the script `block-IP.sh` working as another active-response but you only need to have configured the active-response in the manager configuration, and the script in every agent to be able to write into the CDB list when rules 5712 and 602 are triggered. 

In the following section of the documentation (https://documentation.wazuh.com/3.x/user-manual/ruleset/cdb-list.html) you can see how Wazuh can integrate your created CDB lists into your rules allowing to be warned when something related to them. This is why it makes sense to create your CDB lists on the manager (where Wazuh processes the rules and decoders), but you could be interested to also create them on the agents with other purposes.

Talking about the script, we use the `-q` or `--quite` to avoid writing any output, we only need the exit status of the command for evaluating the condition.

On the other hand, active-response has its own syntax to run scripts calling them using the following arguments `<action> <user> <IP>`. This is the reason why the`$3` argument catches the IP incoming from the decoded event.

**Comment by gagantous** [comment]
H @chemamartinez  

Thanks for the explanation! it's really helpful, and it solved my CDB list problem

Again, Thank you very much

Regards 
Fathin

**Comment by chemamartinez** [comment]
@gagantous,

As I told you, the module in charge of active-response uses its own syntax to call the scripts and unfortunately that process is not documented yet. When the module runs the command, in most cases the syntax is the following one:
```
<script> <action: add/delete> <user> <IP> <alert-id> <rule-id> <trigger>
```
For example, when we trigger an active response from the rule ID 5716, the script should read arguments as follows:
```
$0 = /var/ossec/active-response/bin/block-IP.sh
$1 = add
...
$5 = 5716
```
I recommend you take a look at the default scripts to make it easier to create new ones.

**Comment by gagantous** [comment]
Thanks again @chemamartinez!

**Comment by gagantous** [comment]
Hi @chemamartinez!
I have question. Is there any line in active response module that catch a file path, for example virus path ? Like in some case the wazuh log, catch a malicious file or rootkit in some directories lets say `/etc/folder/virus.py` and `/usr/virus.py`. Is there a line in active-response sytax that catch these files ? So i can make a script to delete those files using active-response.

**Comment by chemamartinez** [comment]
Hi @gagantous ,

Unfortunately, active-response scripts don't allow custom syntax to performance those kinds of things. However, we know it is an important feature and we will try to introduce it as soon as possible.

I think meanwhile you could work around the issue by storing those malicious files into a CDB list when an alert reports them. After that, with the `command` Wazuh module you could run a script to delete files included in that list once a day, for example. Here you have the documentation about how to use that module:

https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/wodle-command.html

Finally, I would recommend you to open new threads when you have any question to share with the community instead of writing in a closed thread. That way it is easier for us and the rest of the users to track the issue and solve it as soon as possible.

Best regards,
Chema.
