### ISSUE TITLE
syscheck/rootcheck running netstat which taking up a lot of cpu for a long time for server with lots of connections

### ISSUE THREAD

**Issue by okyeoh** [wazuh/wazuh#680]
Hi, I am wondering if there can be a change on how the detection of port usage for syscheck/rootcheck using netstat as coded in src/rootcheck/check_rc_ports.c?

Currently for system with lots of connections, it will take up a lot of cpu resources for an extended period of time.

**Comment by vikman90** [comment]
Hi @okyeoh,

We are working on replacing this Rootcheck's feature by a port scan in Syscollector. Version 3.3 will report efficiently all the open ports and future versions will report which PID opened that port and show an alert.

In the meantime, if you're experimenting a performance issue, this internal option may help you:
https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#rootcheck

I've just found a typo in that option reference: the allowed range of values is `0` to `1000` (1 second).  Increasing that value should relax the CPU usage though it will extend the scan time.

Hope it help.
Best regards.
