### ISSUE TITLE
Stop using FIM temporary files for 'unscanned file' events

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#6806]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12+ | Wazuh FIM| Manager/Agent | Packages/Sources | OS version |

Temporary files for FIM have been causing problems since 3.12, we will try to stop using them and find ways to get the same behaviour by leveraging the sqlite DB.

In order to move closer to the previously stated goal, we should stop using the temporary files to store paths that have not been scanned during a schedule scan. A possible solution to this could be to create a query that gets unscanned entries one at a time, process the event, delete the entry from the DB and try to get another scanned entry.

![check_deleted_files](https://user-images.githubusercontent.com/20206636/100873164-2df0c700-34a3-11eb-9996-6d3b9caab731.png)

This solution will work with both `disk` and `memory` databases without any extra elements.

We should benchmark disk, cpu and memory usage before and after this change with a large number of entries in order to guarantee there is no degradation on performance.

**Comment by antoniomanuelfr** [comment]
Hello team!!

I'm closing this issue as while developing the DBSync based FIM DB, this process is handled by DBSync without using temporary files.

More info:

https://github.com/wazuh/wazuh/issues/10847
