### ISSUE TITLE
AWS ruleset enrichement. Adding MITRE att&ck to Cloudtrail rules

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#6807]
Hello team,

I am opening this issue to track the work we will perform to enrich the current AWS ruleset with the MITRE att&ck framework.

This will be done in https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0350-amazon_rules.xml and it will affect to AWS Cloudtrail service.

Reference: https://attack.mitre.org/matrices/enterprise/cloud/

![Image from iOS (1)](https://user-images.githubusercontent.com/23264276/100891959-1e30ad00-34ba-11eb-92df-6c82c0621f87.jpg)

Regards,

Miguel Casares

**Comment by fhielpos** [comment]
After analyzing the current ruleset for AWS I have concluded that most of the events will trigger the same rule (rule id 80202). This rule uses a list inside `etc/lists/amazon/aws-eventnames` to match eventNames. This list is also outdated as it does not include newer AWS services eventNames, making events outside the list to not trigger an alert.

To accomplish this we will need to:
* Map AWS eventNames to [MITRE ATT&CK AWS Matrix](https://attack.mitre.org/matrices/enterprise/cloud/aws/).
* Extend `etc/lists/amazon/aws-eventnames` adding the missing eventNames.
* Create new more detailed rules suiting the MITRE techniques detailed above.

**Comment by fhielpos** [comment]
Hello team,

I created this script to update the eventName lists:
https://github.com/wazuh/wazuh-ruleset/blob/4.0-AWS-ruleset-MITRE-enrichment/tools/amazon/eventnamesupdate.py

**Usage:**
`eventnamesupdate.py -u URL -s SERVICE [-p PATH]`

- URL: AWS API Reference page, for example:
https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Operations.html
https://docs.aws.amazon.com/IAM/latest/APIReference/API_Operations.html
https://docs.aws.amazon.com/lambda/latest/dg/API_Operations.html

- SERVICE: The service name, used as value for the list.

- PATH: List path, default:
`/var/ossec/etc/lists/amazon/aws-eventnames`

**Example:**
`eventnamesupdate.py -u https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Operations.html -s EC2`

Regards,
Franco Hielpos
