### ISSUE TITLE
Add renamed rules and decoders to deprecated list for manager upgrade

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#6815]
### Description

As part of the epic https://github.com/wazuh/wazuh-ruleset/issues/784, all the decoders and rules are being modified in order to work with the `wazuh` name instead of `ossec`. This leads to the renaming of some rules and decoders.
During exploratory testing https://github.com/wazuh/wazuh-ruleset/issues/793 it was found that these rules and decoders were not deleted during a manager upgrade.

There is a list in **deprecated_ruleset.txt** of deprecated rules and decoders that must be deleted during the upgrade
**0200-ossec_decoders.xml**, **0015-ossec_rules.xml**, **0016-wazuh_rules.xml** must be added to this list to guarantee the correct upgrade of the manager.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/6816 was merged.
