### ISSUE TITLE
Fix active-response increasing timeout

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#683]
The `<repeated_offenders>` allows us to increase the time during an active-response is enabled for each time its triggered.

This variable is defined as a unique array for the whole module: https://github.com/wazuh/wazuh/blob/master/src/os_execd/execd.c#L16

And it is read directly from the `ossec.conf` file by the `execd` module: https://github.com/wazuh/wazuh/blob/master/src/os_execd/config.c#L51

That facts provoke the following limitations:

- For agents configuration, it has to be set only in its local configuration.
- We cannot set different values for each configured active-responses, it always takes the value set in the first `<active-response>` section of the `ossec.conf`. For example, having the following configuration on the manager:

```
  <active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>5503</rules_id>
    <timeout>1800</timeout>
  </active-response>

  <active-response>
    <command>route-null</command>
    <location>local</location>
    <rules_id>5716</rules_id>
    <timeout>600</timeout>
    <repeated_offenders>30,60,180</repeated_offenders>
  </active-response>
```

The `<repeated_offenders>` field is ignored due to the module is looking for it in the first section, where is not defined.

**Comment by crolopez** [comment]
Some questions to discuss:

- In [this line](https://github.com/wazuh/wazuh/blob/25e12de32c7f7957eac4971613f8dec101f56045/src/config/active-response.c#L281) the active response is identified by the union of the command and the timeout. If we have an active response with a timeout equal to 5 and a command called act1, it would be identify as if it were using a command called act with a timeout equal to 15: act15.

- I think that repeated_offenders would have been for analysisd. This could allow to save an array for each active-response, which would be received with the rest of the event on [this line](https://github.com/wazuh/wazuh/blob/25e12de32c7f7957eac4971613f8dec101f56045/src/os_execd/execd.c#L320), with a delimiter to ensure compatibility. Only execd is aware of how many times each active response has been executed, but the logical way to collect these values is through analysisd and not execd.
