### ISSUE TITLE
SSL letsencrypt?

### ISSUE THREAD

**Issue by farzadha2** [wazuh/wazuh#6834]
Hello there, I was looking around and couldn't find any documentation on this, What i did try is install ngnix and installed letsencrypt using HTTP mode because elasticsearch uses port 443 but the issue is the renew part because nginx would also run on 443. I was reading about putting the NGINX as reverse proxy but when i try changing the port on 

`nano /etc/kibana/kibana.yml`

and restart the service it wont come back on so not sure whats the correct method?

Thank you

**Comment by vikman90** [comment]
Hi @farzadha2,

The correct path of `kibana.yml` is: _/usr/share/kibana/config/kibana.yml_. I think you should change the option:
```yml
server.port: 443
```

The default port is `5601`. Try to change that setting in the file and restart Kibana again.

Hope it helps.
Best regards.

**Comment by colans** [comment]
You also need to [allow Kibana access privileged ports](https://stackoverflow.com/questions/29615310/kibana4-to-listen-on-port-80-instead-of-port-5601/29618626).
