### ISSUE TITLE
Upgrading agent on Windows through MSI causes a new registration

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh#6839]
My previous issue #6639 was closed so I had to open a new one.
We have some agents 4.0.0 on Windows 10 deployed through group policy with password. We made transformation file MST and the first deployment worked great.
We met problems after deployed a new version 4.0.1 through group policy which should upgrade the previous one.
Previous version was deleted, client.keys file was renamed to client.keys.save and this agent was registered whis a new ID.
Is it possible somehow correct this behavior? For example, if it finds in installation folder config files with "save", it uses them but not generating new ones.

**Comment by VN1977** [comment]
I posted my last comment [there](https://github.com/wazuh/wazuh/issues/6639#issuecomment-737457899).

**Comment by vikman90** [comment]
Hi @VN1977.

Let me reopen #6639 and we will continue discussing there.
Best regards.
