### ISSUE TITLE
Possibility to active Active-response script when two exact id were triggered 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#686]
Like i have this two rules, the first one was a default rules, and the second one was custom rules.

```
<rule id="5712" level="10" frequency="6" timeframe="120" ignore="60">
    <if_matched_sid>5710</if_matched_sid>
    <description>sshd: brute force trying to get access to </description>
    <description>the system.</description>
    <same_source_ip />
    <group>authentication_failures,pci_dss_11.4,pci_dss_10.2.4,pci_dss_10.2.5,</group>
</rule>
```

and

```
<rule id="4709" level="15">
    <if_sid>5700</if_sid>
  <list field="srcip" lookup="match_key">etc/lists/IP-blacklist</list>
  <description>An IP included in the black list is trying to connect with the host.</description>
  <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
</rule>
```
The scenario is just like this, the first triggered rule 4709, but i dont want the active-response to be activated, until the same sources_ip triggered the rules 5712, and the active response would work.

Is it possible to activated the `active-response` script if these two rules were triggered from the same sources IP, ? i have tried like this.

```
<active-response>
    <command>firewall-drop</command>
    <location>local</location>
    <rules_id>4709, 5712</rules_id>
    <timeout>1800</timeout>
  <repeated_offenders>1440</repeated_offenders>
</active-response>
```

but the active response only triggered if at least one from two id were triggered or we can say, 4709 OR 5712, i need if two exact rule, 4709 AND 5712, were triggered from the same sources IP.

I dont need how many times the id were triggered ( the frequency ), i just need if these two id were triggered, and boom, the active-response work.

Is it possible ?

**Comment by crolopez** [comment]
Hi @gaelmuller,

The rules_id option does not work as an AND operation, so you cannot get it by that way. I propose two alternatives:

1) You can create another active-response command, triggered by the 4709 rule, to write to a list (a text file for example) that IP address. Then, another active response command, triggered with the 5712 rule, would execute the firewall-drop functionality only if it finds the source_ip in the list. The return command should also remove the IP from the list.

2) Modify rule 5712 to run according to a CDB list that would work exactly like the list in the example above. If you use this option remember to invoke make-list after including the IP in the list.

However, the feature you're talking about is interesting. We will consider including it in a future version.

Best regards.

**Comment by gagantous** [comment]
Hi @crolopez

I see, okay i will try your advice, gonna report my progress when i have configured that way

Thanks
