### ISSUE TITLE
Save Wazuh logs when API integration test fails.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6891]
|Wazuh version|Component|
|---|---|
| master | Tavern API tests |

## Description

Hi team! Recently, the API integration tests have been added to platforms like Jenkins, where they are run for each PR. This has lots of advantages and we can see the results directly in the github PR checks. 

However, right now, when there is a failed test, we only have the information provided by the test itself. It would be interesting for multiple use cases to save and store the content of the files below in case the test is failed:
- cluster.log
- ossec.log
- api.log

This way, if for instance there are fails in the `test_cluster_endpoints.tavern.yaml`, we could find out whether the origin of the error was that the workers did not connect on time to the master node, if there are any error in the code, etc, just by looking at the information obtained after running the test.

It would be interesting to study if it is worth carrying out this development, or if there is other useful information to save, such as the output of the `GET /security/users/me` endpoint to see what the real permissions of the user were.

## Checks

No changes in framework/API required.

Best regards,
Selu.

**Comment by vicferpoy** [comment]
## Issue update
In addition to the requested features from above, we should also add a function to retrieve RBAC user information when the tests are not able to get a token. Sometimes we see the following error for every test within the same run:

```
raise Exception(f"Error obtaining login token: {response.json()}")
E   Exception: Error obtaining login token: {'title': 'Unauthorized', 'detail': 'Invalid credentials'}
```

We should add this logic here:
https://github.com/wazuh/wazuh/blob/2344c910ba0a77e8194ecb981b67f4ad71d48f67/api/test/integration/conftest.py#L37-L38
