### ISSUE TITLE
The MSU script fails to handle invalid data returned by the Microsoft Catalog 

### ISSUE THREAD

**Issue by 0xN3utr0n** [wazuh/wazuh#6918]
Hi team,

As we already know, the **Microsoft Catalog** is quite unstable and very error-prone. We've now detected that, from time to time, some requests seem to return invalid data, or none at all, even though the HTTP answer has a 200(OK) status code. This can cause many false-positives when a Vulnerability Detector scan takes place, since many hotfixes, and their corresponding supersedences, are missing from the MSU.

The behavior above mentioned is difficult to reproduce due to its obvious randomness, but we've seen that around 4 out of 2000 requests end up failing. Being that said, we'll later update the issue with a script, which will hopefully automate this process.

Ideally, we should be capable of handling this unexpected case by retrying the HTTP request until we end up having the expected data, or we reach the maximum number of attempts. 

Best regards,
Fernando

**Comment by chemamartinez** [comment]
After the research in https://github.com/wazuh/wazuh/issues/13254 we are now collecting all the needed patches from the Microsoft Catalog.
