### ISSUE TITLE
agent_upgrade Error 1716

### ISSUE THREAD

**Issue by kulozzzz** [wazuh/wazuh#692]
HI:
    I encountered an error when using agent_upgrade to remotely upgrade the client:
`[root@localhost ossec]# /var/ossec/bin/agent_upgrade -a 020 -d -f var/upgrade/wazuh_agent_v3.2.3_centos_6_x86_64.wpk -x install.sh
wazuh_agent_v3.2.3_centos_6_x86_64.wpk
[root@localhost ossec]# /var/ossec/bin/agent_upgrade -a 020 -d -f var/upgrade/wazuh_agent_v3.2.3_centos_6_x86_64.wpk -x install.sh
Custom WPK file: wazuh_agent_v3.2.3_centos_6_x86_64.wpk (4153 KB)
MSG SENT: 020 com open wb wazuh_agent_v3.2.3_centos_6_x86_64.wpk
RESPONSE: ok
MSG SENT: 020 com lock_restart -1
RESPONSE: ok
Chunk size: 512 bytes
FILE SHA1: fdfc008b5d2dfb7b8663d04f29e44324b8637af5
MSG SENT: 020 com close wazuh_agent_v3.2.3_centos_6_x86_64.wpk
RESPONSE: ok
MSG SENT: 020 com sha1 wazuh_agent_v3.2.3_centos_6_x86_64.wpk
RESPONSE: ok fdfc008b5d2dfb7b8663d04f29e44324b8637af5
WPK file sent
MSG SENT: 020 com upgrade wazuh_agent_v3.2.3_centos_6_x86_64.wpk install.sh
RESPONSE: err Response timeout
Error 1716: Error upgrading agent: Response timeout
Traceback (most recent call last):
  File "/var/ossec/bin/agent_upgrade", line 147, in <module>
    main()
  File "/var/ossec/bin/agent_upgrade", line 75, in main
    upgrade_command_result = agent.upgrade_custom(file_path=args.file, installer=args.execute, debug=args.debug, show_progress=print_progress if not args.silent else None, chunk_size=args.chunk_size, rl_timeout=-1 if args.timeout == None else args.timeout)
  File "/var/ossec/bin/../framework/wazuh/agent.py", line 2507, in upgrade_custom
    raise WazuhException(1716, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1716 - Error upgrading agent: Response timeout`

How can I solve this problem?

**Comment by RaulMartinPineda** [comment]
Hi Kulozzzz.

It's possible that the error is in the command you are running. Try changing install.sh to upgrade.sh.
The command should look like this: 
`/var/ossec/bin/agent_upgrade -a 020 -d -f var/upgrade/wazuh_agent_v3.2.3_centos_6_x86_64.wpk -x upgrade.sh `.
Keep me posted on whether it works for you.

Regards.

**Comment by kulozzzz** [comment]
Thank！@RaulMartinPineda
