### ISSUE TITLE
AWS integration for Cloudtrail issue

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#6929]
Hello team, 

When configuring the AWS integration for Cloudtrail on one Wazuh agent, with the following versions:

Agent:
VERSION="v3.13.2"
Manager:
VERSION="v4.0.1"

Following this guide:
https://documentation.wazuh.com/4.0/amazon/services/supported-services/cloudtrail.html#amazon-cloudtrail.

With logs located at:

`s3://bucket/AWSLogs/AccountID/Cloudtrail/Region/year/month/day`

After running the script:

`./aws-s3 -t cloudtrail -b bucket_name -a XXXXXXXXXX -k XXXXXXXXXXXX -d 2`

We're getting the following error:

"Unexpected error querying/working with objects in s3: list index out of range"

The 7 "Unexpected error querying/working with objects in S3" refers according to the documentation to instances of the wodle running at the same time and the part "List index out of range refers to the fact that there are no elements in the list within items, so the query has not returned anything to the database as well".

Investigating I found this information:

The error “list index out of range” arises if you access invalid indices in your Python list. For example, if you try to access the list element with index 100 but your lists consist only of three elements, Python will throw an IndexError telling you that the list index is out of range."

Here a config example added on the agent:
```
<wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="cloudtrail">
        <name>bucket_name</name>
        <aws_profile>default</aws_profile>
        <regions>ap-northeast-1,ap-northeast-2</regions>
        <aws_account_id>Account_ID</aws_account_id>
    </bucket>
  </wodle>
```
  
Any help with this error generated? As a consequence, no logs/alerts related to Cloudtrail are displayed.

Thank you in advance!

**Comment by CarlosRS9** [comment]
Hello @abohorqu,

I tried to replicate this issue using a test environmnent with a 4.0.1 master node and a 3.13.2 agent but no error appeared. 

Could you please provide us more information about how to reproduce this error?

**Comment by MiguelCasaresRobles** [comment]
Solved
