### ISSUE TITLE
Unmerging merged.mg on manager client nodes for better visibility

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#693]
Now that the only group files sent from master node to client node in a Wazuh manager cluster are the **merged.mg** files, individual files like agent.conf no longer are updated on the client node side, giving the appearance on the client node that things are not propagating correctly unless you dig into the bulky **merged.mg** files directly.  I know that these **merged.mg** files do get properly unpacked into individual files once reaching agents, but I propose we also unpack **merged.mg** on the client nodes to better accommodate visibility and debugging.

Thanks!
Kevin

**Comment by jesuslinares** [comment]
Hi @branchnetconsulting,

I think that would be an extra effort for the cluster. If you want to debug what is happening, just review the files in the master node. Then, you can check the md5 of the merged.mg in every manager node to be sure that it is propagated.

Is that work for you?.

Thanks.

**Comment by branchnetconsulting** [comment]
Could we find some other to way eliminate the confusion caused by having
left over outdated files like agent.conf in /var/ossec/etc/shared/*GROUP*/
giving the impression that propagation from the master is not working.
That is my main concern.  When changing a manager from standalone to
client-node, the full set of files in /var/ossec/etc/shared/*GROUP*/
remains, while only merged.mg in that directory gets updated.  Maybe
client-node managers should always clear the  /var/ossec/etc/shared/*GROUP*/
directory of all files but merged.mg?  Otherwise it gives the impression
that propagation is not working.  It sure confused me at first.

Kevin

**Comment by jesuslinares** [comment]
> When changing a manager from standalone to client-node, the full set of files in 
>  /var/ossec/etc/shared/*GROUP*/ remains, while only merged.mg in that directory gets updated.

That is a good point. Let us investigate it.

**Comment by branchnetconsulting** [comment]
This is not as much of an issue now, as there is really little reason any
more for any file other than merged.mg to appear in a worker node's
agent-group directory anyway.  In an older version of Wazuh I believe the
separate files were conveyed from master to worker nodes and so when I
upgraded to the latest, I found it confusing that files such as agent.conf
on the worker node were not getting updated from the master node any more.
To the person setting up or upgrading the manager cluster, it gave the
impression that updates from the master were not arriving.  I think most of
our users (unless they have taken our training) do not understand that
merged.mg is actually the only file being conveyed from master to worker
nodes.  Usually we just think in terms of agent.conf moving from master to
workers to agent systems.  We could possibly have worker managers clean out
all their their agent-group directories of everything but merged.mg at
start time, just to keep things tidy since that is the only file that will
actually be passed along anyway, but I suppose that would bring the risk of
file loss is someone inadvertently chose to store things in an agent-group
directory.

I think at this point my only recommendation is that we clearly document
how merged.mg is actually used to convey config and data files from master
to workers to agents.  This is not presently explained in our public
documentation as far as I can find.

Kevin

**Comment by branchnetconsulting** [comment]
I no longer think having worker node managers unpack merged.mg makes sense.  If anything it just tempts us Wazuh admins to edit files like agent.conf on a worker node manager which then leads to our changes being overwritten from the master manager shortly thereafter.

While we still need to clearly explain what merged.mg is for in the online documentation, that should probably be a separate issue.  I will close this one.
