### ISSUE TITLE
Make the Wazuh building independent from the installation directory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6938]
### Description

The aim of this issue is to avoid defining the installation directory in compilation time but in runtime.  Now, when building Wazuh for Unix, the [`PREFIX` parameter](https://documentation.wazuh.com/4.0/development/makefile.html#available-flags) sets the installation directory in compilation time, making this a predefined parameter that cannot change later.

These changes will allow the Wazuh components to work in any location without the need of knowing it before starting to run. In addition, it avoids the need of building custom packages to change the installation dir.

### Requirements

- Wazuh must be able to be compiled without a predefined path

- In the installation process, the location is defined by the user. By default, it is still `/var/ossec`

- The Wazuh binaries will work with relative paths to the installation directory when possible. Making them independent from their location.

- The embedded python and the other dependencies should be compatible with the changes described above, working in any location

- This development must be followed by tests to ensure it works properly

This issue was previously defined at #785 and partially solved at #2186.

**Comment by alromeros** [comment]
Branch: https://github.com/wazuh/wazuh/tree/6938-make-wazuh-installdir-independent
