### ISSUE TITLE
Migrate README from ruleset repository to ruleset folder

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#6939]
### Description

As part of epic #6898, all the necessary changes are being implemented in the [wazuh](https://github.com/wazuh/wazuh) repository in order to have all the content of the ruleset and finally deprecate the [wazuh-ruleset](https://github.com/wazuh/wazuh-ruleset) repository.

As part of this issue, the README.md file of the **ruleset repository** should be migrated into the ruleset folder on the Wazuh repository.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/6940 was merged.
