### ISSUE TITLE
When assigning multiple groups to an API security policy it only applies the first group 

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh#6941]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.0.3| API | Manager | Packages | CentOS 7|

**Summary**

If an API user is given permission to read agents by specifying agents groups, they are only allowed to see the first group that is assigned to them. However, if they are given permission to read agents by their IDs this behaviour is not observed.

**Steps to reproduce:**

- Register at least 2 agents into a manager and assign them to 2 groups (groupA and groupB for example).
- Create a policy that allows to read agent:group:groupA and agent:group:groupB, and for comparison one that is able to read all the agents included in both groups (by specifying their IDs instead of groups). 
- Create roles with these policies.
- Create users and assign said roles.
- Query the agents endpoint with each user to see that the one given permission by specifying both groups only sees the first one and the other user is able to see both agents.

**Step by step reproduction on a newly installed environment:**

`TOKENadmin=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")`

Create groups:

```
/var/ossec/bin/agent_groups -a -g groupA -q
/var/ossec/bin/agent_groups -a -g groupB -q
```

Register an agent to group A and another to group B (this is the only step to be done from outside the manager, this is necessary because it is the only way to assign a group to a never_connected agent):

`/var/ossec/bin/agent-auth -m <MANAGER_ADDRESS> -g groupA` (from agent 001)
`/var/ossec/bin/agent-auth -m <MANAGER_ADDRESS> -g groupB` (from agent 002)

Create policies (the first one allows to read agents from groups A and B, and the second one allows to read the same agents by specifying its IDs):

```
curl -k -X POST "https://localhost:55000/security/policies" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{
"name": "readgroupsAandB",
"policy": {
    "actions": ["agent:read"],
     "resources": ["agent:group:groupA","agent:group:groupB"],"effect": "allow"}}'
```

```
curl -k -X POST "https://localhost:55000/security/policies" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{
"name": "readagentsAandB",
"policy": {
    "actions": ["agent:read"],
     "resources": ["agent:id:001","agent:id:002"],"effect": "allow"}}'
```
     
Create roles and assign them to their policies:

```
curl -k -X POST "https://localhost:55000/security/roles" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{"name": "readgroupsAandB_role"}'
curl -k -X POST "https://localhost:55000/security/roles/100/policies?policy_ids=100" -H "Authorization: Bearer $TOKENadmin" 
```

```
curl -k -X POST "https://localhost:55000/security/roles" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{"name": "readagentsAandB_role"}'
curl -k -X POST "https://localhost:55000/security/roles/101/policies?policy_ids=101" -H "Authorization: Bearer $TOKENadmin" 
```

Create users and assign their roles: 
```

curl -k -X POST "https://localhost:55000/security/users" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{
  "username": "groupsAandBreader",
  "password": "Pa$$word1"
}'
curl -k -X POST "https://localhost:55000/security/users/100/roles?role_ids=100" -H "Authorization: Bearer $TOKENadmin" 

```
```
curl -k -X POST "https://localhost:55000/security/users" -H "Authorization: Bearer $TOKENadmin" -H 'Content-Type: application/json' -d' 
{
  "username": "agentsAandBreader",
  "password": "Pa$$word1"
}'
curl -k -X POST "https://localhost:55000/security/users/101/roles ?role_ids=101" -H "Authorization: Bearer $TOKENadmin" 

```
Get tokens for these users:

```
TOKENgroups=$(curl -u groupsAandBreader:'Pa$$word1' -k -X GET "https://localhost:55000/security
/user/authenticate?raw=true")
```
```
TOKENagents=$(curl -u agentsAandBreader:'Pa$$word1' -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
```

Request agents with each account:
```

curl -k -X GET "https://localhost:55000/agents?select=name,group" -H "Authorization: Bearer $TOKENgroups"
{"data": {"affected_items": [{"name": "agentA1", "group": ["default", "groupA"], "id": "001"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
```

```
curl -k -X GET "https://localhost:55000/agents?select=name,group" -H "Authorization: Bearer $TOKENagents"
{"data": {"affected_items": [{"name": "agentA1", "group": ["default", "groupA"], "id": "001"}, {"name": "agentB1", "group": ["default", "groupB"], "id": "002"}], "total_affected_items": 2, "total_failed_items": 0, "failed_items": []}, "message": "All selected agents information was returned", "error": 0}
```

Note that the output of the `groupsAandBreader` user only has agents from groupA while the output of user `agentsAandBreader `includes both specified agents, the second of which is seen to have groupB within its groups.

**Comment by mcarmona99** [comment]
## Issue status

Hi team,

In the `context_cached` function of `common.py`, we are saving the result of the decorated function in a cache. This cache is unique for a specific key, `system_expanded_groups`, in this case.

The solution is changing the key of the cache from `system_expanded_groups` to `system_expanded_groups` + `args` + `kwargs`, this way, the cache entry is unique to more than one RBAC resource regarding `groups`.

## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
