### ISSUE TITLE
Error code 2318 during Windows uninstallation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#6947]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.0-alpha1 | Wazuh agent | Agent | Packages | Windows Server 2016 |

Hello team,

We've detected this error during Windows agent v4.1.0 uninstallation:

![error_windows](https://user-images.githubusercontent.com/11089305/102493863-16edcf80-4074-11eb-8af7-c27f22e59176.png)

"_The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2318_"

# Steps to reproduce:

Register the agent to a manager. Then while the agent is running start the uninstallation process and proceeds normally

Tested package:  https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.1.0-1.msi

**Comment by alberpilot** [comment]
This error occurs if the a user try to uninstall the Wazuh agent when syscheck create files in `tmp/` folder:

![image](https://user-images.githubusercontent.com/3830293/118103337-16b2ef80-b3da-11eb-99a1-ea62d007e6d9.png)

**Comment by DFolchA** [comment]
This error may be caused because the MSI uninstallation does not wait for the service to stop, 
https://github.com/wazuh/wazuh/blob/c9b0b1d73b3884cacf4c20a24489c7bcfae06d63/src/win32/wazuh-installer.wxs#L174

In this line, the return value of the CustomAction element is set to `ignore` it is should be set to `check` or `asyncWait` so we are sure that the service is stopped and Wazuh has deleted the file from `tmp`.

**Comment by okynos** [comment]
Hello team,

We have done tons of tests and improvements over this issue we will comment each one:
First branch `6947-fix-msi-uninstall`
- 2c735c6ac281e73afb4e8a1569955fa719588ac6
- 907b4018f1cd22383d45e70543f7fafac4f5aee7
- 3fca381547fd5a59ad5df6dcb68163bcd1efc1f2
- e7059175d26ad34f5ae9304875f16200f2e9de6d
- e0ea843efbb1efcbc14c24ed54ee513c3fb42b34 
- 982d27916033366a93e31ec6b8b397bfd874953b 
- f06e2655d322b53ba8771115769db4e279ee408e 
- e2dee6c22d15c5cd86eeab3312200b8752b57efe
With these commits, we tested different options of stop execution and ways to allow the service to correctly stops Wazuh. 

After all testing and @vikman90 PR that changes one item of my develop I created a new branch with such modifications.
Second branch: `6947-uninstall-msi`
- 0a60b67617167d5dcc99621debbd439fa159b9f0
- 3a19b017a9fe02e8a2b6586f09032f6e63c93aea
With this last commit, I will assume that the package is fixed of this issue but need to reproduce the error to completely assume this statement. I cannot reproduce this issue in any way or form.
I attach the testing generated package for the @wazuh/qa team to check if all goes well.

Thanks
[wazuh-agent-4.2.0-1.uninstall.msi.zip](https://github.com/wazuh/wazuh/files/6502708/wazuh-agent-4.2.0-1.uninstall.msi.zip)




Regards
