### ISSUE TITLE
Adapt Makefile to compile Wazuh without a predefined PREFIX

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6959]
### Description

The first step for making Wazuh independent from the destination folder is to adapt the Makefile to work without defining the installation path through the `PREFIX` parameter.

To do so, `DEFAULTDIR` won't be defined by the Makefile and the code should be adapted to get the location on runtime (https://github.com/wazuh/wazuh/issues/6958).

**Comment by alromeros** [comment]
Branch: https://github.com/wazuh/wazuh/tree/6959-adapt-makefile-without-prefix
