### ISSUE TITLE
"Wazuh App: API configuration" local configuration file location

### ISSUE THREAD

**Issue by sonofagl1tch** [wazuh/wazuh#696]
Issue: Cannot find configuration file on wazuh server that contains the Wazuh app API configuration.

additional context: Where on the filesystem on the wazuh server is the configuration setting for "Wazuh App: API configuration" kept?  I wrote some scripts that automate the installation of wazuh on to a server but I cannot automate the joining of clients until I can programmatically populate this last setting. Below is a screenshot to reference what API configuration I am looking to find the file for. Thanks!

<img width="1255" alt="screen shot 2018-05-30 at 3 54 33 pm" src="https://user-images.githubusercontent.com/20155474/40744173-cbd926d8-6421-11e8-8239-2a312887e128.png">

**Comment by citybasebrooks** [comment]
It's in the .wazuh ElasticSearch Index.  See [here](https://github.com/wazuh/wazuh-kibana-app/issues/324) for a starting point.

**Comment by sonofagl1tch** [comment]
thank you for your input! I am going to post on that thread in hopes of some help with modifying or creating that index programmatically. 

[ec2-user@ip-172-16-0-21 ~]$ curl -s -XGET http://172.16.0.21:9200/.wazuh/wazuh-configuration/_search
[ec2-user@ip-172-16-0-21 ~]$
[ec2-user@ip-172-16-0-21 ~]$ curl -s -XGET http://elasticsearch:9200/.wazuh/wazuh-configuration/_search
[ec2-user@ip-172-16-0-21 ~]$
[ec2-user@ip-172-16-0-21 ~]$ curl -s -XGET http://localhost:9200/.wazuh/wazuh-configuration/_search
{"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
[ec2-user@ip-172-16-0-21 ~]$
[ec2-user@ip-172-16-0-21 ~]$ curl -s -XGET http://127.0.0.1:9200/.wazuh/wazuh-configuration/_search
{"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
[ec2-user@ip-172-16-0-21 ~]$

**Comment by sonofagl1tch** [comment]
i figured out why nothing is returned in the queries above. the query returns nothing on a fresh install. i need to have the api configured to get a result. that doesnt help me from a fresh install

**Comment by citybasebrooks** [comment]
You could just issue a PUT request to the REST endpoint and set those values.

**Comment by sonofagl1tch** [comment]
I'm actually working on figuring that out now. This is my latest attempt but it doesn't seem to populate everything as expected. I'm working on it iteratively in hopes that I get it. i'll post again if i figure it out.

`curl -X POST "localhost:9200/.wazuh/wazuh-configuration" -H 'Content-Type: application/json' -d' {"took":0,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":".wazuh","_type":"wazuh-configuration","_score":1.0,"_source":{"api_user":"wazuh","api_password":"d2F6dWg=","url":"http://172.16.0.21","api_port":"55000","insecure":"true","component":"API","cluster_info":{"manager":"ip-172-16-0-21.ec2.internal","cluster":"Disabled","status":"disabled"},"extensions":{"audit":true,"pci":true,"oscap":true,"aws":false,"virustotal":false}}}]}}'`

**Comment by jlruizmlg** [comment]
Hi @sonofagl1tch , you have an example in our wazuh-docker, in this docker we populate automatically the API connection:

https://github.com/wazuh/wazuh-docker/blob/master/kibana/config/entrypoint.sh#L26-L46

```
  curl -s -XPOST $el_url/.wazuh/wazuh-configuration/1513629884013 -H 'Content-Type: application/json' -d'
    {
      "api_user": "foo",
      "api_password": "YmFy",
      "url": "https://wazuh",
      "api_port": "55000",
      "insecure": "true",
      "component": "API",
      "cluster_info": {
        "manager": "wazuh-manager",
        "cluster": "Disabled",
        "status": "disabled"
       },
      "extensions": {
        "oscap": true,
        "audit": true,
        "pci": true,
        "aws": true,
        "virustotal": true
      }
    }
```
Where the fields are:

**api_user:** is your API user (by default foo)
**api_password:** is the API password (by default bar encoded in Base64 format)
**url:** is the API url.
**api_port:** is the API port… default 55000
**cluster_info.manager:** is manager hostname.

The last thing is the number **“1513629884013**” included in the curl, this is an aleatory number, you can use any number, but if you want to add two API, the numbers need to be different, or you will overwrite the API.

**Comment by sonofagl1tch** [comment]
the following code looks to implement the feature I am looking for. Thank you very much for your help!

```API_PROTOCOL=${API_PROTOCOL:-http}
API_SERVER=${API_SERVER:-172.16.0.21}
API_PORT=${API_PORT:-55000}
API_USER=${API_USER:-wazuh}
API_PASS=${API_PASS:-wazuh}
API_PASS_BASE64=$(echo -n ${API_PASS} | base64)
ES_URL=${ES_URL:-'http://localhost:9200'}
ES_USER=${ES_USER:-kibana}
ES_PASSWORD=${ES_PASSWORD:-changeme}
until curl -u ${ES_USER}:${ES_PASSWORD} -XGET "${ES_URL}"; do
  >&2 echo "Elastic is unavailable - sleeping for 5 seconds"
  sleep 5
done
>&2 echo "Elastic is up - executing commands"
sleep 5
echo -e "\nSetting Wazuh API credentials into the Wazuh Kibana application"
# The Wazuh Kibana application configuration is the document with the ID 1513629884013, don't change that!
curl -s -u ${ES_USER}:${ES_PASSWORD} -XPOST "${ES_URL}/.wazuh/wazuh-configuration/1513629884013" -H 'Content-Type: application/json' -H "Accept: application/json" -d'
{
    "api_user": "'${API_USER}'",
    "api_password": "'${API_PASS_BASE64}'",
    "url": "'${API_PROTOCOL}'://'${API_SERVER}'",
    "api_port": "'${API_PORT}'",
    "insecure": "true",
    "component": "API",
    "active": true,
    "extensions": {
        "oscap": true,
        "audit": true,
        "pci": true
    },
    "cluster_info": {
        "node": "wazuh-manager-master",
        "cluster": "wazuh",
        "manager": "wazuh-manager-master-0",
        "status": "enabled"
    }
}
'
