### ISSUE TITLE
Rename the Windows default directory

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#6961]
### Description

The directory where the Windows agent is installed is called `ossec-agent`.

The aim of this issue is to rename it to `wazuh-agent`.

**Comment by alromeros** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/6961-rename-windows-default-directory/src

**Comment by chemamartinez** [comment]
After further discussions, we have decided to move this issue from the current development.
