### ISSUE TITLE
Is it possible to set our range time for email reports ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#699]
Hi Wazuh team

I have tried [ this ](https://documentation.wazuh.com/3.x/user-manual/manager/automatic-reports.html), that documented about automatic reports. it's a daily reports. It works great. I assume that these daily reports have the default time 24 hours, after that it will send to our email that we signed before in the conf.

Is it possible to use our own time range? So the email will be reported as a compilation for every 6 hours later, or maybe 4 hours later, or maybe 12 hours later. ?

Thanks before 
Fathin

**Comment by vikman90** [comment]
Hi @gagantous,

Unfortunately, alert reports are daily, there is no option to set the time interval for them. I think this is interesting, so let me add this issue to our roadmap to implement this feature.

Thank you for your feedback.
Best regards.

**Comment by havidarou** [comment]
This will be tackled through the indexer component instead.
