### ISSUE TITLE
[Development] Incorrect parameters accepted in agent-upgrade configuration

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#6998]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.0-alpha1 | modulesd | Manager| Packages | Linux |

Hello team,

We found that the manager accepts any parameter inside the new `agent_upgrade` block and allows Wazuh to start without indicating that the configuration is wrong.

### How to reproduce

1. Install [wazuh-manager 4.1.0](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.1.0-1.x86_64.rpm)
2. Set a wrong `agent_upgrade` block in `ossec.conf`
```
<agent-upgrade>
  <upgrade>16384</upgrade>
  <test>https://packages-dev.wazuh.com/pre-release/wpk/</test>
  <config>10</config>
  <extra-parameter>10</extra-parameter>
</agent-upgrade>
```
3. Restart the manager
4. The agent will start without any problem and the values for `agent-upgrade` actual parameters will be set to default.

Regards,
Daniel Folch

**Comment by TomasTurina** [comment]
Closed since the behavior is the expected (log a warning message):
```
2020/12/21 14:46:17 wazuh-modulesd: WARNING: No such tag <upgrade> at module 'agent-upgrade'.
2020/12/21 14:46:17 wazuh-modulesd: WARNING: No such tag <test> at module 'agent-upgrade'.
2020/12/21 14:46:17 wazuh-modulesd: WARNING: No such tag <config> at module 'agent-upgrade'.
2020/12/21 14:46:17 wazuh-modulesd: WARNING: No such tag <extra-parameter> at module 'agent-upgrade'.
```
