### ISSUE TITLE
[API] Remove behind_proxy_server from POST /agents/insert

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7015]
|Wazuh version|Component|
|---|---|
| 4.1 | Wazuh API |

## Description
Hi team! We should remove the following block of code inside `POST /agents/insert` endpoint, as it was removed in the past for the `POST /agents` since it is no longer needed:

https://github.com/wazuh/wazuh/blob/eeec711edd16e82c176af5419be732f16119b22f/api/api/controllers/agent_controller.py#L905-L915

Until now, it was in charge of getting the agent IP from a special header named `X-Forwarded-for`, or from the host where the endpoint was being run. However, after the development of agent enrollment feature, it is no longer needed.  

**`behind_proxy_server` API option won't be deleted yet. It will be removed in https://github.com/wazuh/wazuh/issues/7006, together with the tests and documentation.**

## To do
- [x] Remove `behind_proxy_server` code in `POST /agents/insert endpoint`
- [x] Mark as XFail the tests in wazuh-qa repository.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Issue update
Hi team!

In addition, we need to improve the `input validation` regexes. The `%`  character is missing from the `names` ones.
