### ISSUE TITLE
API Configurations Overwritten On Upgrade

### ISSUE THREAD

**Issue by suryjuto** [wazuh/wazuh#702]
How do I prevent the $OSSEC_HOME/api/configuration/config.js and $OSSEC_HOME/api/auth/user files from getting overwritten when wazuh is upgrade via apt?

**Comment by JmZero** [comment]
Hi @suryjuto 

This bug was fixed in previous versions, currently the files you mention can't be overwritten. Thank you for your contribution.
Best regards,

Jesús.
