### ISSUE TITLE
Improve basic (mapping tag) API integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7027]
## Description

Hello team. We run a bunch of API integration tests depending of the modified file in the framework/API. We use this mapping file for reference: https://github.com/wazuh/wazuh/blob/master/api/test/integration/mapping/integration_test_api_endpoints.json

If the file tag does not match any particular integration test, we simply run the basic ones. Currently, these are the basic tests:

- test_agent_GET_endpoints.tavern.yaml
- test_agent_DELETE_endpoints.tavern.yaml
- test_agent_PUT_endpoints.tavern.yaml
- test_agent_POST_endpoints.tavern.yaml
- test_security_POST_endpoints.tavern.yaml
- test_security_PUT_endpoints.tavern.yaml
- test_security_DELETE_endpoints.tavern.yaml
- test_security_GET_endpoints.tavern.yaml
- test_cluster_endpoints.tavern.yaml
- test_experimental_endpoints.tavern.yaml

There are two issues with these tests:

1. Although these are a lot of tests, there are some endpoints that could be considered as basic usage that are not being tested.
2. These tests are not testing anything related to RBAC permissions.

To solve this, we need to investigate what could be the best solution among these:
- Create two new test files: one for normal tests and another for RBAC tests.
    - Two new testing files from scratch.
    - New configuration files for this environment, as it would need to be able to make an API call for every endpoint.
    - Same as above with fixed RBAC permissions for the RBAC tests.
    - This would be harder to maintain. A lot of duplicated tests.

- Adjust our BASIC tag to include some RBAC tests.
    - We cannot have more than 10 test files, as it would double the ETA. This means we would have to remove some of them.
    - It is quite hard to cover every basic functionality, both normal and RBAC with a limit of 10 test files.

## To do

Once a solution has been chosen and implemented, we need to update the testing mapping file and make sure the new mappings are correct. To do so, the mapping script has a testing mode. Follow the documentation for further details.

Regards,
Víctor.

**Comment by davidjiglesias** [comment]
API integration tests pipeline has been severely improved and this issue is no longer necessary
