### ISSUE TITLE
question about how is active-response API work

### ISSUE THREAD

**Issue by jingnanj** [wazuh/wazuh#7047]
Hi team, 
I have a question about the active-response API. Here are the command and response below:

# curl -u foo:bar -k -X PUT -d '{"command":"dynamic", "arguments": ["abc", "bcd", "(from_the_server)", "(no_rule_id)","sc"]}' -H 'Content-Type:application/json' "http://0.0.0.0:55000/active-response/018?pretty"
{
   "error": 0,
   "data": "Command sent."
}

As you can see, I got a successful response. But my question is API get this response from remoted or agent? As we know the manager will give remoted this command and let remoted sent it to agents. I want to know this response means the agent runs this command successfully or just remoted sent this command to the agent successfully. If you can help me found where the code is in API will be great. because I'm trying to find it from the API reference page and active-response code in the API folder. but I still didn't find it.

**Comment by davidjiglesias** [comment]
Hello @jingnanj,

Let me ask you first which Wazuh API version are you currently using? I can see from the response that it is a version < 4.0, so I will assume v3.13.2, there should not be many differences with other v3.x versions.

In that case, the code in python for an Active Response API petition is as follows:

- https://github.com/wazuh/wazuh/blob/3.13/framework/wazuh/cluster/dapi/requests_list.py#L614-L619
- https://github.com/wazuh/wazuh/blob/3.13/framework/wazuh/active_response.py#L33-L80
- https://github.com/wazuh/wazuh/blob/3.13/framework/wazuh/ossec_queue.py#L83-L98

Queue:
- https://github.com/wazuh/wazuh/blob/3.13/framework/wazuh/common.py#L83

The response from the API means the message has been successfully sent to its Wazuh Manager counterpart. Starting from Wazuh 4.1 there will be a new module in charge of `tasks`, which could be useful for situations like this one, to understand when the agent has successfully completed or failed an Active response command, among others. 

I hope this helps solve your questions,

David J. Iglesias

**Comment by jingnanj** [comment]
Thanks
