### ISSUE TITLE
Remove old snapshot files for FIM

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#705]
Syscheck creates a state file for each file monitored with option `report_changes` enabled. But those files are kept even if the original files no longer exist.

Implement a state file following algorithm to remove state files if the original ones are removed or do not exist.

**Comment by jgreene-VSLLC** [comment]
Please consider adding an alert for the deletion of the state / snapshot files too.

**Comment by vikman90** [comment]
Hi @jgreene-VSLLC,

We are thinking what should happen if a file is deleted and it's recreated later. Since FIM has been saving all the files, if the new file is different from the old one, the differences are reported.

Hence, we are considering two possibilities:
1. **We think this is interesting.** So the alert about a file was recreated would appear with the differences with respect to the old file. We should keep the state files for a while, we would likely remove them each time a complete scan is performed. Reporting all the deleted files as you suggest makes much sense.
2. **We don't like this feature.** In this case, we would perform a snapshot purging when the agent gets started. When FIM detects a file deleted it would remove the snapshot file immediately. So reporting state file deletion makes sense on the purging stage.

All ideas is welcome!

Best regards,

**Comment by Cerv1** [comment]
Solved in #872
