### ISSUE TITLE
rule not matching properly.

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#7051]
Hi,

Could you please check the following rule?

################################################################

60103 ^528$|^540$|^673$|^4624$|^4769$ Windows Logon Success no_full_log T1078 authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_8$
60106 win.eventdata.targetUserName win.system.computer Multiple Logon Success From Same User
60106 win.eventdata.targetUserName win.system.computer Simultaneous Logins on a Same Host
###########################################################################

In the above rules, if matched condition only checking the single value it won't check the second value. Can someone give the resolution for the same.

**Comment by juliancnn** [comment]
hi @VisakhMV-Coder,

Correct me if I'm wrong, what you are looking for is a rule that generates an alert if a user logs in multiple times in a period of time, using the fields `win.eventdata.targetUserName` and `win.system.computer`?
For example, if the user logs in 3 times in less than 5 minutes (300 seconds), your rule could be like the following:

```xml
  <rule id="100099" level="10" frequency="3" timeframe="300">
    <if_matched_sid>60118</if_matched_sid>
    <description>Multiple Logon Success From Same User</description>
    <same_field>win.eventdata.subjectUserName</same_field>
    <same_field>win.system.computer</same_field>
    <group>authentication_success,pci_dss_10.2.5,gpg13_7.1,gpg13_7.2,gdpr_IV_32.2,hipaa_164.312.b,nist_800_53_AU.14,nist_800_53_AC.7,tsc_CC6.8,tsc_CC7.2,tsc_CC7.3,</group>
  </rule>
```

The rule with id 60118 (child of 60106), detects successful logins at a workstation, which will help you avoid false positives.
Please let me know if this is helpful.

Regards

**Comment by VisakhMV-Coder** [comment]
Thank you for your response.

Here an example of the rule that we would like to trigger.

################################################
<rule id="110033" level="9">
    <if_sid>60001</if_sid>
    <field name="win.system.eventID">^4624$</field>
    <field name="win.eventdata.logonType">^10$</field>
    <description>RDP:An Account was Successfully Logon</description>
 </rule>
 
 <rule id="110087" level="10" frequency="3" timeframe="240">
    <if_matched_sid>110033</if_matched_sid>
    <different_field>win.eventdata.targetUserName</different_field>
    <same_field>win.system.computer</same_field>
    <description>RDP: Simultaneous Logins on a Same Host</description>
 </rule>

##########################################################

When I test run the above rule, It will match only one condition either the same computer or a different user. The actual intention of the rule is to match all conditions.

**Comment by VisakhMV-Coder** [comment]
Thank you for your response.

Here an example of the rule that we would like to trigger

########################################################


![image](https://user-images.githubusercontent.com/61306426/103331616-ce2f1100-4a8c-11eb-95a1-0f668c9f7663.png)


##########################################################

When I test run the above rule, It will match only one condition either the same computer or a different user. The actual intention of the rule is to match all conditions.

**Comment by juliancnn** [comment]
I have created and tested two rules that could be useful to you. The fist one (`100099`) detect RDP access and the other one (`100100`) detects if the same computer receives two connections with different users using remote desktop.

```xml
  <rule id="100099" level="3">
    <if_sid>60106</if_sid>
    <field name="win.system.eventID">^4624$</field>
    <description>RDP: Logon</description>
    <field name="win.eventdata.logonType">^10$|^3$</field>
  </rule>

  <rule id="100100" level="10" frequency="3" timeframe="300">
    <if_matched_sid>100099</if_matched_sid>
    <same_field>win.system.computer</same_field>
    <different_field>win.eventdata.targetUserName</different_field>
    <description>RDP: simultanius logins on a same host</description>
  </rule>
```

I made some changes to your proposal that could  help strengthen the rules
- All rules that depends on windows successful login must inherit from rule with id `60106`.
- The `logonType` field can have a value of 3 or 10, depending on the type of RDP connection ([more information here](https://social.technet.microsoft.com/Forums/en-US/1fa214d7-e8b6-4d77-adda-117926aa9e6f/event-4624-logon-type-3-for-rdp-access-?forum=winserverDS)).

Please let me know if this is helpful to you
Regards,

**Comment by VisakhMV-Coder** [comment]
Helpful, Thank you.
