### ISSUE TITLE
issue with firewall parser

### ISSUE THREAD

**Issue by VisakhMV-Coder** [wazuh/wazuh#7052]
We have an issue regarding creating a new parser because the log pre-matched as below. We know how to create a parser for pre-matched program_name with but here the program name matched the date value. we are in trouble creating the parser. please help us to resolve the same.

#########################################################################################
^Croot@VMCH-WM-01:/home/visakh# /var/ossec/bin/ossec-logtest
2020/11/21 06:15:22 ossec-testrule: INFO: Started (pid: 19077).
ossec-testrule: Type one log per line.

Nov 20 22:29:36 FlorenceSt-T35 (2020-11-20T11:29:36) firewall: msg_id="3000-0148" Deny 0-External Firebox 36 igmp 24 1 10.1.1.1 224.0.0.1 (Unhandled External Packet-00)

**Phase 1: Completed pre-decoding.
full event: 'Nov 20 22:29:36 FlorenceSt-T35 (2020-11-20T11:29:36) firewall: msg_id="3000-0148" Deny 0-External Firebox 36 igmp 24 1 10.1.1.1 224.0.0.1 (Unhandled External Packet-00)'
timestamp: 'Nov 20 22:29:36'
hostname: 'FlorenceSt-T35'
program_name: '(2020-11-20T11'
log: '29:36) firewall: msg_id="3000-0148" Deny 0-External Firebox 36 igmp 24 1 10.1.1.1 224.0.0.1 (Unhandled External Packet-00)'

**Phase 2: Completed decoding.
No decoder matched.

###########################################################################################

**Comment by juliancnn** [comment]
Hi @VisakhMV-Coder!

I have checked that against the log you posted here and the problem seems to be this piece of log (2020-09-11T07:23:52) right after the hostname. 
Wazuh's pre-decoder is designed to capture standard syslog formats, therefore, this is why you see an error in pre-decoding.
Some programs and devices allow you to change the log format to suit different situations, could you tell me more about these logs?, maybe there is another way I can help you with this.
Are these logs read from a file or received by syslog?

Regards

**Comment by VisakhMV-Coder** [comment]
Sample logs 

#########################################
Dec 30 04:36:53 T35-Oasis (2020-12-30T04:36:53) firewall: msg_id="3000-0148" Allow 1-Trusted 0-External 52 tcp 20 127 10.201.52.133 40.90.189.152 49644 443 offset 8 S 4023259392 win 64240  (BOVPN-Allow.out-00)

2: Dec 30 04:36:52 T35-Oasis (2020-12-30T04:36:52) firewall: msg_id="3000-0148" Allow 1-Trusted 0-External 52 tcp 20 126 10.201.52.142 192.168.0.127 54330 139 offset 8 S 3165915561 win 64240  (BOVPN-Allow.out-00)

3: Dec 30 04:36:47 T35-Oasis (2020-12-30T04:36:47) firewall: msg_id="3000-0148" Allow 1-Trusted 0-External 52 tcp 20 127 10.201.52.142 192.168.0.127 54329 445 offset 8 S 2851616282 win 64240  (BOVPN-Allow.out-00)

4: Dec 30 04:36:45 T35-Oasis (2020-12-30T04:36:45) firewall: msg_id="3000-0148" Allow 1-Trusted 0-External 68 udp 20 127 10.201.52.133 10.2.40.102 58793 53  (BOVPN-Allow.out-00)
#############################################################

Are these logs read from a file or received by Syslog?  --- Syslog
Device type -- Firewall
Model -- Watchguard

Here the details of the log, please let me know any further information required.

**Comment by juliancnn** [comment]
I've read the Watchguard documentation and couldn't find the option to change the log format, so Wazuh won't be able to pre-decode it.
Thank you for your contribution, i tagged this issue as a bug, in this way we can analyze it, estimate it and add it to our roadmap to be able to address it in the future.

if you have any other inquiries please do not hesitate to ask.
Regards

**Comment by VisakhMV-Coder** [comment]
Thank you for the information.

**Comment by akraegelius** [comment]
hi! Is there any update or solution to this?

**Comment by jmgorro** [comment]
Hello akraegelius.
I think I've found a workarround. When you define the syslog server (wazuh) on Watchguard box, uncheck the TimeStamp. This means that this second date/time field is not sent to syslog and the Wazuh decoder can proceed.
Hope will be useful.
