### ISSUE TITLE
Kernel decoders defect

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#7061]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Any | Ruleset | Manager | Any | Any |

Hello team,

I've found 2 issues related to the ruleset specifically for "Iptables1" decoders in the 0140-kernel_decoders.xml.

1. When UFW logs are received that contain a space at the beginning of the field "kernel time since boot":

 "Dec 23 08:03:43 hostname kernel: **[ 9991.178400]** "

The log is not processed correctly. In the following link you'll find the structure of the mentioned log:

https://help.ubuntu.com/community/UFW

There you'll find a log example that also has the space in the mentioned field:

Feb  4 23:33:37 hostname kernel: **[ 3529.289825]** [UFW BLOCK] IN=eth0 OUT= MAC=00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd SRC=444.333.222.111 DST=111.222.333.444 LEN=103 TOS=0x00 PREC=0x00 TTL=52 ID=0 DF PROTO=UDP SPT=53 DPT=36427 LEN=83

2. Also when the field "Short description of the logged event" contains a space between the action e.g. [UFW BLOCK] is not processed correctly because a space is missing on the decoder regex.

This is why the default decoders must be modified to support space on both cases.

Regards. 
Alexander

**Comment by RyanInsolencee** [comment]
whats the solution for this?
