### ISSUE TITLE
Create a child rule of rule 510 with level 11 that must match with possible kernel level rootkit

### ISSUE THREAD

**Issue by juanrricci** [wazuh/wazuh#7097]
Hello team, 

The aim of this issue is to create a child rule of rule 510 with level 11 that must match with possible kernel level rootkit.

Currently, during the Diamorphine exercise, it is triggered the rule 510 with level 7 which corresponds to "bad word matching". It is also missing PCI-DSS or MITRE mapping.

**Comment by 72nomada** [comment]
- [ ] get a source log line to check the new rule
- [ ] set MITRE
