### ISSUE TITLE
integration with OSSIM?

### ISSUE THREAD

**Issue by rnbwkat** [wazuh/wazuh#71]
You guys have done amazing work on the upgraded version of OSSEC.  I wonder if anyone has thought of doing a guide for integration in the OSSIM? I have used Santiago's guide to actually do this, however, the new rulesets do not fire in this case because the IDs have not been integrated into the OSSIM DB. This would be a great add-on/enhancement. I might be willing to put a PR in as I have done some work on this, but wanted to wait on the final release of the new version.

**Comment by santiago-bassett** [comment]
Hi Kat,

this may help. If you already installed the RESTful API on the Wazuh manager. You can generate an updated wazuh.sql file, by going to the /var/ossec/api and run the following python script (rules2ossim.py):

```
#!/usr/bin/env python

from sys import path
path.append('{0}/framework'.format(path[0]))
from wazuh.rule import Rule

#print("file;id;description;level;status;groups;pci;details")
print("DELETE FROM plugin where id = '22000';")
print("DELETE FROM plugin_sid where plugin_id = '22000';")
print("INSERT IGNORE INTO plugin(id, type, name, description) VALUES(22000, 1, \"Wazuh\", \"Wazuh host and endpoint security\");")
print("INSERT IGNORE INTO plugin_sid(plugin_id, sid, category_id, subcategory_id, class_id, reliability, priority, name) VALUES")
for rule in Rule.get_rules(status='enabled', limit=0, sort={"fields":["file"],"order":"asc"})['items']:
#    print("{0};{1};{2};{3};{4};{5};{6};{7}".format(rule.file, rule.id, rule.description, rule.level, rule.status, rule.groups, rule.pci, rule.details))
    print("(22000, %s, 15, 173, NULL, 1, 1, \"Wazuh - %s\")," % (rule.id, rule.description))
```
Run it this way to remove some unwanted double quotes:

`python rules2ossim.py >> wazuh.sql | sed -i -e '5,$s/"//g' -e '5,$s/, Wazuh/, "Wazuh/g' -e '5,$s/),/"),/g' -e '$s/,$/;/' ./wazuh.sql`

Then move the wazuh.sql file to the OSSIM box and run:

`cat wazuh.sql | ossim-db`

Now you should be able to copy ossec-single-line.cfg, rename it as wazuh.cfg and change the plugin_id to 22000 (or whatever you defined in the python script).

**Comment by Regirv** [comment]
Tell me, after running the script:
python rules2ossim.py >> wazuh.sql | sed -i -e '5,$s/"//g' -e '5,$s/, Wazuh/, "Wazuh/g' -e '5,$s/),/"),/g' -e '$s/,$/;/' ./wazuh.sql

I get the following error:

Traceback (most recent call last):
  File "rules2ossim.py", line 12, in <module>
    for rule in Rule.get_rules(status='enabled', limit=0, sort={"fields":["file"],"order":"asc"})['items']:
  File "/var/ossec/framework/wazuh/rule.py", line 298, in get_rules
    return {'items': cut_array(rules, offset, limit), 'totalItems': len(rules)}
  File "/var/ossec/framework/wazuh/utils.py", line 104, in cut_array
    raise WazuhException(1406)
wazuh.exception.WazuhException: Error 1406 - 0 is not a valid limit.

What is the problem?

**Comment by Zenidd** [comment]
Hello @Regirv,

first of all, sorry for the late reply

For the script to work properly we must make a couple of modifications:
 

- On `rules2ossim.py`: 
    -` limit=0` a `limit=1000`.

- On `/var/ossec/framework/wazuh/common.py`: 
     - `database_limit = 500` to `database_limit = 5000`
     - `maximum_database_limit = 1000` to `maximum_database_limit = 10000`

After this modifications, should generate and updated `wazuh.sql`

`rules2ossim.py` code after limit modification:
```
#!/usr/bin/env python

from sys import path
path.append('{0}/framework'.format(path[0]))
from wazuh.rule import Rule

print("file;id;description;level;status;groups;pci;details")
print("DELETE FROM plugin where id = '22000';")
print("DELETE FROM plugin_sid where plugin_id = '22000';")
print("INSERT IGNORE INTO plugin(id, type, name, description) VALUES(22000, 1, \"Wazuh\", \"Wazuh host and endpoint security\");")
print("INSERT IGNORE INTO plugin_sid(plugin_id, sid, category_id, subcategory_id, class_id, reliability, priority, name) VALUES")

for rule in Rule.get_rules(status='enabled', limit=10000, sort={"fields":["file"],"order":"asc"})['items']:
#   print("{0};{1};{2};{3};{4};{5};{6};{7}".format(rule.file, rule.id, rule.description, rule.level, rule.status, rule.groups, rule.pci, rule.details))
    print("(22000, %s, 15, 173, NULL, 1, 1, \"Wazuh - %s\")," % (rule.id, rule.description))
```







Kind regards,

Juan Pablo Sáez
