### ISSUE TITLE
Test SHA256

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#711]
## Description
This new configuration allows you to check the hash 256 in _Syscheck_
## References
**Related PR:** [#410](https://github.com/wazuh/wazuh/pull/410)
**Branch:** Master
**Documentation:** [wazuh/wazuh-documentation#239](https://github.com/wazuh/wazuh-documentation/issues/239)

# Unit tests

- [x] Enable SHA256 explicitly.
- [x] Enable SHA256 with `check_all=yes`.
- [x] Enable SHA256 in the second scan.
- [x] Enable SHA256 in an agent connected to a manager v3.2.
- [x] Check that unchanged checksums are not reported. 
- [x] Check with `check_all=yes check_sha256sum=no`.
- [x] Agents < 3.3 do not cause failure when not reporting the SHA256 field
- [x] Check in Windows

**Comment by bah07** [comment]
I found a couple of bug fixes in this PR [710](https://github.com/wazuh/wazuh/pull/710)
