### ISSUE TITLE
RULES - File 0500-owncloud_rules.xml xml parsing error

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7113]

**Comment by juanrricci** [comment]
XML standard does not allow `--` in comments. As the rule file `0500-owncloud_rules.xml` has 2 example logs in comments that include `--` in their fields (line 23 and line 34), they cause issues when parsing the file during analysis procedures. The `--` in both examples was changed by `- -`, allowing the file to be parsed properly.
