### ISSUE TITLE
rule file 0260-nginx_rules.xml xml parsing error 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7115]
&  symbol not supported on standard xml language.

```
  <rule id="31335" level="7">
    <if_sid>31334</if_sid>
    <match>&block=1&</match>
    <description>NAXSI rejected a query</description>
    <mitre>
      <id>T1083</id>
    </mitre>
    <group>naxsi,gpg13_10.1,</group>
  </rule>
```

**Comment by juanrricci** [comment]
`&` is an special character for the XML standard format. As the rule file `0260-nginx_rules.xml` includes `&block=1&` in the `<match>` option of the rule `31335`, they cause issues when parsing the file during analysis procedures. The `&` character should be substitute by the `&amp;` escaped character, but this could most likely lead to a rule mismatch issue. 

The following log is an example found in this [tutorial](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-naxsi-on-ubuntu-16-04):
`2018/11/07 17:08:01 [error] 21356#0: *2 NAXSI_FMT: ip=your_server_ip&server=your_server_ip&uri=/&learning=0&vers=0.56&total_processed=2&total_blocked=2&block=1&cscore0=$SQL&score0=40&cscore1=$XSS&score1=40&zone0=ARGS&id0=1001&var_name0=q, client: your_server_ip, server: localhost, request: "GET /?q=1" or "1"="1" HTTP/1.1", host: "your_server_ip"
`

This log includes the string  `&block=1&` that the rule `31335` matches. We suggest changing the `&block=1&` for `block=1`. This change allows both matching the string in the log and avoiding the `&` special character usage.
