### ISSUE TITLE
SCRIPT - MITRE - Gap between current ruleset and MITRE 

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7116]
outputs

.- how many rules has at least one MITRE Technique (total rules vs rules with mitre) - %wazuh-mitre-ready-rules
.- how many MITRE Techniques are referenced (total mitre T and ST vs wazuh mitre rules) - %mitre-wazuh-coverage

**Comment by juanrricci** [comment]
Newer and more specific issues are being created for increasing the number of rules with proper MITRE IDs.
