### ISSUE TITLE
Adapt Wazuh package scripts to work without ossec-init.conf

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#7124]
### Description 

As part of the epic https://github.com/wazuh/wazuh/issues/7054, we have the main goal of removing the `/etc/ossec-init.conf` file from the Wazuh installations. Having said that, all the scripts used by packages during the installation should be modified in order to stop using that file.

As part of this issue the next Wazuh scripts should be modified:

- register_configure_agent.sh

**Comment by DProvinciani** [comment]
Closing the issue as the PRs https://github.com/wazuh/wazuh/pull/7125 and https://github.com/wazuh/wazuh-packages/pull/597 were merged.
