### ISSUE TITLE
<program_name>  extracting an empty string 

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#7126]
```
Nov 20 06:35:00 PUNGDC-FDCS-DIST_SF : (root) CMD (   /usr/libexec/atrun)
**Phase 1: Completed pre-decoding.
       full event: 'Nov 20 06:35:00 PUNGDC-FDCS-DIST_SF : (root) CMD (   /usr/libexec/atrun)'
       timestamp: 'Nov 20 06:35:00'
       hostname: 'PUNGDC-FDCS-DIST_SF'
       program_name: ''
       log: '(root) CMD (   /usr/libexec/atrun)'
**Phase 2: Completed decoding.
       No decoder matched.
```

As you can notice below the result for that log  gives  program_name  an empty string and not (null), I've tried with a pre-match entry but the decoder hasn't been detected.

The only way to get it work was to use the program_name in that way :

```
<decoder name="Junos-dist-switch-info4">
  <program_name></program_name>
</decoder>
<decoder name="Junos-dist-info-cron">
   <parent>Junos-dist-switch-info4</parent>
   <regex>(\(\S+\)) \S+ (\(\s+\S+\))</regex>
   <order>cron.user, cron.action</order>
</decoder>
```
the result is : 

```
Nov 20 06:35:00 PUNGDC-FDCS-DIST_SF : (root) CMD (   /usr/libexec/atrun) 


**Phase 1: Completed pre-decoding.
       full event: 'Nov 20 06:35:00 PUNGDC-FDCS-DIST_SF : (root) CMD (   /usr/libexec/atrun) '
       timestamp: 'Nov 20 06:35:00'
       hostname: 'PUNGDC-FDCS-DIST_SF'
       program_name: ''
       log: '(root) CMD (   /usr/libexec/atrun) '

**Phase 2: Completed decoding.
       decoder: 'Junos-dist-switch-info4'
       cron.user: '(root)'
       cron.action: '(   /usr/libexec/atrun)'
```

That may make many conflicts especially if we have many logs from different sources where the program_name is extracted as an empty string like in this case.

**Comment by JavierBejMen** [comment]
# Update

In order to solve this issue some decoder restructuring is needed, with a big one in sight this will be solved. 

Currently it affects: 
- 0260-rsa-auth-manager_decoders.xml
- 0205-pam_decoders.xml
- 0060-cisco-estreamer_decoders.xml

I'm closing this issue as it will be handled on decoder restructuring.
