### ISSUE TITLE
Wazuh Cluster configuration issue

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#714]
**pls help me out --**

[cluster issue.pdf](https://github.com/wazuh/wazuh/files/2071060/cluster.issue.pdf)

**Comment by JuanjiJG** [comment]
Hello @gyanprakashsahu,

The cluster got some improvements on v3.2.3, and you should update your configuration to avoid those messages.

Now, you only have to add the master's IP address in all the cluster nodes, both master and clients. Remove the unnecessary `<node>` tags inside the `<nodes>` section, and just leave the master node configured:

```xml
<nodes>
     <node>10.1.0.1</node>
 </nodes>
```

Don't forget to restar both your master and your clients:

```
systemctl restart wazuh-manager
```

You can find more information in our documentation, on [this link](https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html). Pay attention to the section for upgrading the cluster configuration if you came from a version earlier to v3.2.3.

Let us know if you need more help with this.

Regards,
Juanjo

**Comment by gyanprakashsahu** [comment]
As suggest, I have removed unnecessary nodes.
Error is removed but client node still is not showing --
root@wazuh-manager:/var/ossec/data/etc# /etc/init.d/wazuh-manager restart
Killing wazuh-clusterd...
Killing ossec-monitord...
Killing ossec-logcollector...
Killing ossec-remoted...
Killing ossec-syscheckd...
Killing ossec-analysisd...
ossec-maild not running...
Killing ossec-execd...
Killing wazuh-modulesd...
Killing wazuh-db...
Killing ossec-authd...
Wazuh v3.2.3 Stopped
Starting Wazuh v3.2.3 (maintained by Wazuh Inc.)...
Started ossec-authd...
Started wazuh-db...
Started wazuh-modulesd...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-syscheckd...
Started ossec-remoted...
Started ossec-logcollector...
Started ossec-monitord...
Started wazuh-clusterd...
Completed.
root@wazuh-manager:/var/ossec/data/etc# /var/ossec/bin/cluster_control -ld
DEBUG: [Transport-InternalSocketSend] Starting: /var/ossec///queue/cluster/c-internal.sock.
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_nodes {}'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'ok'.
DEBUG: [Transport-InternalSocketSend] Closing socket.
DEBUG: [Transport-InternalSocketSend] Socket closed.
-----------------------------------------------
Name               Address      Type    Version
-----------------------------------------------
in-wazuh-master-1  10.51.0.128  master  3.2.3
-----------------------------------------------

**Comment by JuanjiJG** [comment]
Hello again @gyanprakashsahu,

Look in the cluster logs file **from your master and client nodes** to see if everything is properly working:
```
tail /var/ossec/logs/cluster.log
```

Please, paste here the content.

Regards,
Juanjo

**Comment by gyanprakashsahu** [comment]
## Log--

root@wazuh-manager:/# tail /var/ossec/logs/cluster.log
2018-06-05 07:32:42,883 INFO    : [Master] Exiting. Reason: 'Signal [15-Terminated] received.'.
2018-06-05 07:32:46,377 INFO    : [Master] PID: 26374
2018-06-05 07:32:46,378 INFO    : [Master] Listening '0.0.0.0:1516'.
2018-06-05 07:32:48,392 INFO    : [Master] [Internal-COM ]: Ready.
root@wazuh-manager:/#

**Comment by JuanjiJG** [comment]
Hello again @gyanprakashsahu,

I see on the master logs that no clients have been connected. Could you please send me the **clients nodes logs** to see why they didn't connect?

```
tail /var/ossec/logs/cluster.log
```

Please, paste here the content.

Regards,
Juanjo

**Comment by gyanprakashsahu** [comment]
## Client log--

root@wazuh-manager:/var/ossec/data/etc# tail /var/ossec/logs/cluster.log
2018-06-05 07:47:35,089 ERROR   : [Client] Disconnected. Trying to connect again in 10s.
2018-06-05 07:47:46,124 INFO    : [Client] Disconnected.
2018-06-05 07:47:46,125 ERROR   : [Transport-Handler] Error: '[Errno 111] Connection refused'.
2018-06-05 07:47:46,125 ERROR   : [Client] Disconnected. Trying to connect again in 10s.
2018-06-05 07:47:57,181 INFO    : [Client] Disconnected.
2018-06-05 07:47:57,181 ERROR   : [Transport-Handler] Error: '[Errno 111] Connection refused'.
2018-06-05 07:47:57,182 ERROR   : [Client] Disconnected. Trying to connect again in 10s.
2018-06-05 07:48:08,210 INFO    : [Client] Disconnected.
2018-06-05 07:48:08,210 ERROR   : [Transport-Handler] Error: '[Errno 111] Connection refused'.
2018-06-05 07:48:08,210 ERROR   : [Client] Disconnected. Trying to connect again in 10s.

**Comment by JuanjiJG** [comment]
Hello again @gyanprakashsahu,

Looks like the client is incapable of reaching the master. This could be a network problem.

Try to `ping` between the master and client nodes to see if they can talk each other, and also check your firewall to see if the port `1516` is open.

Regards,
Juanjo

**Comment by gyanprakashsahu** [comment]
okay..Got it !!

I am using docker for wauzh setup. Cluster is working with docker ?

**Comment by gyanprakashsahu** [comment]
Thanks for support..
That was the network issue to communicating docker container. Now, Cluster is working fine.

Could you help me for client setup.
(i.e.- Both linux and win script  )

**Comment by mgmacias95** [comment]
Hello @gyanprakashsahu,

What do you mean with "client setup"? Cluster nodes can only be Wazuh managers so they must be linux. If you're refering to the setup of the Wazuh agents, then it can be both windows and linux.

You can open a new issue describing your new problem with more details. 

Best regards,
Marta

**Comment by gyanprakashsahu** [comment]
i mean wazuh agent

okay
