### ISSUE TITLE
Add bucket support to GCP module (Investigate reusing pub/sub)

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7146]
Hello team,

We should add bucket logs support to our current Google Cloud Platform module. 

As part of this EPIC, we should study and evaluate the design and solution to add support to the Wazuh module.

https://cloud.google.com/storage/docs/creating-buckets

Best regards,

David J. Iglesias

**Comment by JavierBejMen** [comment]
Related issue #8244

**Comment by CarlosRS9** [comment]
To be addressed in #8690.
