### ISSUE TITLE
Refactor /manager/files and /cluster/{node_id}/files API endpoints

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7148]
Hello team,

We should refactor our current API endpoints for` /manager/files `and `/cluster/{node_id}/files`. The current endpoints are way too generic and therefore it is very difficult to properly handle content, destination and validation.

We propose the following changes:

Deprecate:
- `GET /manager/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.manager_controller.get_files
- `PUT /manager/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.manager_controller.put_files
- `DELETE /manager/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.manager_controller.delete_files
- `GET /cluster/{node_id}/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.cluster_controller.get_files_node
- `PUT /cluster/{node_id}/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.cluster_controller.put_files_node
- `DELETE /cluster/{node_id}/files` https://documentation.wazuh.com/4.0/user-manual/api/reference.html#operation/api.controllers.cluster_controller.delete_files_node

Add:
- `GET /rules/file/{filename}` -> xml or json
- `PUT /rules/file/{filename}` -> xml
- `DELETE /rules/file/{filename}`
- `GET /decoders/file/{filename}` -> xml or json 
- `PUT /decoders/file/{filename}` -> xml
- `DELETE /decoders/file/{filename}`
- `GET /lists/file/{filename}` -> raw or json 
- `PUT /lists/file/{filename}` -> raw
- `DELETE /lists/file/{filename}`
- `GET /manager/configuration` -> xml or json (Already exist, add option to read in xml)
- `PUT /manager/configuration`
- `GET /cluster/{node_id}/configuration` -> xml or json (Already exist, add option to read in xml)
- `PUT /cluster/{node_id}/configuration`

Regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

The development has begun. Remember to use the main branch as base for each issue.

| Main branch |
|-|
| [dev-refactor-files-endpoints](https://github.com/wazuh/wazuh/tree/dev-refactor-files-endpoints) |
