### ISSUE TITLE
Wrong alert format 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#715]
Hello team, take a look at this alert from Vulnerability detector:

```js
{
...
   "agent":{
      "id":"0",
      "name":"osboxes",
      "ip":"local"
   },
...
}
```

Now take a look at any other alert from Wazuh manager:

```js
{
...
   "agent":{
      "id":"000",
      "name":"osboxes"
   },
...
}
```

As we can see there is inconsistency.

Regards,
Jesús

**Comment by jesusgn90** [comment]
I think it's not working between 000 to 099 IDs cause after test it with agents like 001, 002, 003 it's showing 1,2 and 3.

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/commit/ad7d0443f1a9c9a7df9869ce5ea63613115ca871.
