### ISSUE TITLE
Remove the reference to the ossec-init.conf file from the wazuh_framework_getting_started.rst file

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7155]
### Description 

As part of the epic https://github.com/wazuh/wazuh/issues/7054, we have the main goal of removing the `/etc/ossec-init.conf` file from the Wazuh installations. Having said that, the usage of this file to get information about the current Wazuh installation should be removed from the next file.

```
framework/docs/source/wazuh_framework_getting_started.rst
```

**Comment by pereyra-m** [comment]
This task will be carried out by another team, within a different epic to update the whole framework documentation. #7227 
I'm closing this issue as invalid.
