### ISSUE TITLE
Debugging received messages to syslog 

### ISSUE THREAD

**Issue by VN1977** [wazuh/wazuh#7159]
We have standalone server Wazuh version 4.0.3 on Centos 7.8.
We are trying to use it for collecting logs from Kaspersky Security Center sending them to syslog on Wazuh. KSC sends logs I we see them using tcpdump on input interface of Wazuh server. Also we see that UDP 514 is listened by ossec-remoted.
```
udp    UNCONN     0      0         *:1514                  *:*                   users:(("ossec-remoted",pid=75839,fd=4))
udp    UNCONN     0      0         *:514                   *:*                   users:(("ossec-remoted",pid=75840,fd=4))
```
But how to understand what really logcollector has got through syslog, then create the decoder and debug it? I have not found any info in ossec.log or anywhere else.

**Comment by Lopuiz** [comment]
Hello,

You can active [logall](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/global.html#logall) option to create the file `/var/ossec/logs/archive/archive.log`.  Analisisd writes all events processed in this file.

The following log is an example of an event processed from my `archive.log`:
```
2021 Jan 13 10:36:31 eva->/var/log/auth.log Jan 13 10:36:30 eva sudo: pam_unix(sudo:session): session opened for user root by (uid=0)
```
First is `2021 Jan 13 10:36:31 eva->/var/log/auth.log`. It is the timestamp and location added by Analisisd. Then, you can see the event processed by Analisisd. You can create decoders and rules for this second part of the message.

I hope it helps you.

Regards,
Eva

**Comment by VN1977** [comment]
Yes, it helped. Thanks!
