### ISSUE TITLE
Error log messages from Vulnerability

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#716]
Hello team, please see the next log messages:

```
2018/06/05 05:04:59 wazuh-modulesd:vulnerability-detector: ERROR: (5405): SQL error: UNIQUE constraint failed: AGENTS.AGENT_ID, AGENTS.PACKAGE_NAME, AGENTS.VERSION, AGENTS.ARCH
2018/06/05 05:05:00 wazuh-modulesd:vulnerability-detector: ERROR: (5410): The software of the agent '0' could not be obtained.
```
From my view this is totally related to https://github.com/wazuh/wazuh/issues/715, at some point, the Vulnerability detector is using 0 instead 000.

Regards,
Jesús

**Comment by jesusgn90** [comment]
In addition to my last message:

- I think the error comes from this database:

`/var/ossec/queue/vulnerabilities/cve.db`

```
sqlite> PRAGMA table_info(AGENTS);
0|AGENT_ID|INT|1||1
1|PACKAGE_NAME|TEXT|1||2
2|VERSION|TEXT|1||3
3|ARCH|TEXT|1||4
```
My testing database is empty.

Hope it helps!

Jesús

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/commit/93fe16c3b557f96319f1901feac1e265be7f6334.
