### ISSUE TITLE
Refactor framework stats module.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7161]
|Wazuh version|Component|
|---|---|
| master | Framework/stats |

## Description

Hi team!

Currently, the [stats](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/stats.py) module in framework is following an old schema which has already been replaced in other modules. 

Right now, for example for functions related to `manager`, we can find two files: `framework/wazuh/manager.py` (SDK) and `framework/wazuh/core/manager.py` (core). The core file contains the tools that are necessary to perform multiple actions on a manager, while in the SDK these tools are used and a response is created with a specific format and a pattern common to the rest of the modules.

To follow the same structure as in the rest of the modules, it is necessary to create a stats.py file in core that takes care of the logic that the SDK file is handling right now.

## To do
Split `framework/wazuh/stats.py` into:
- [x] `framework/wazuh/stats.py`
- [x] `framework/wazuh/core/stats.py`

Update unittests:
- [x] Create unittests for the new `framework/wazuh/core/stats.py` module.
- [x] Update current tests for `framework/wazuh/stats.py`.
 
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Best regards,
Selu.

**Comment by Kondent** [comment]
## Issue update
Refactor is almost done, im currently working on tests. I just need to checks a few more things before PR but I should be able to create it today.
