### ISSUE TITLE
Update copyright in framework and api files

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7162]
## Description
Hi team! 

Right now, copyright header is outdated in all framework and API files (2015-2020), so it should be updated to 2021.
https://github.com/wazuh/wazuh/blob/412981d8a0b9e5f11c6d59f3ffef08d73a989211/framework/wazuh/manager.py#L1-L3

Best regards,
Selu.

**Comment by davidjiglesias** [comment]
To be done in https://github.com/wazuh/wazuh/pull/7568
