### ISSUE TITLE
Agent never connect on client nodes in wazuh Cluster env

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#718]
# Client never connected on client-node-1   ( status NEVER CONNECTED )
# Client never connected on client-node-2  ( status NEVER CONNECTED )

**showing Active on master-node only**

root@wazuh-manager:~# /var/ossec/bin/cluster_control -ad
DEBUG: [Transport-InternalSocketSend] Starting: /var/ossec///queue/cluster/c-internal.sock.
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_agents all%--%all%--%0%--%500%--%None%--%None'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'ok'.
DEBUG: [Transport-InternalSocketSend] Closing socket.
DEBUG: [Transport-InternalSocketSend] Socket closed.
---------------------------------------------------------------------------------------------
ID   Address    Name                                                Status  Node
---------------------------------------------------------------------------------------------
000  127.0.0.1  wazuh-manager                                       Active  wazuh-master-1
001  10.1.1.1  client-1

  Active  wazuh-master-1
---------------------------------------------------------------------------------------------

**Comment by mgmacias95** [comment]
Hello @gyanprakashsahu,

The `cluster_control -a` output that a client node shows is the same output that the master's. The client nodes perform a request to retrieve this information from the master. You can see the request process in the DEBUG logs:
```
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_agents all%--%all%--%0%--%500%--%None%--%None'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'ok'.
```

Were agents registered in the master node?

Best regards,
Marta

**Comment by gyanprakashsahu** [comment]
root@wazuh-manager:/var/ossec/bin# ./manage_agents


****************************************
* Wazuh v3.2.4 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: l

Available agents:
   ID: 001, Name: client-agent-1, IP: 10.1.1.10

** Press ENTER to return to the main menu.

where it should be registered ?

**Comment by gyanprakashsahu** [comment]
root@wazuh-manager:~# /var/ossec/bin/cluster_control -i more
Cluster name: wazuh

Connected nodes (3):

    in-wazuh-master-1 (10.1.1.2)
        Version: 3.2.4
        Type: master
        Active agents: 2

    in-wazuh-node-1 (10.1.1.10)
        Version: 3.2.4
        Type: client
        Active agents: 0
        Status:
            Integrity
                Last synchronization: 2018-06-06 05:53:42.54 - 2018-06-06 05:53:42.55.
                Synchronized files: Shared: 0 | Missing: 0 | Extra: 0 | Extra valid: 0.
                Permission to synchronize: True.
            Agents-info
                Last synchronization: n/a - n/a.
                Synchronized files: 0.
                Permission to synchronize: True.
            Agents-group
                Last synchronization: n/a - n/a.
                Synchronized files: 0.
                Permission to synchronize: True.

    in-wazuh-node-2 (10.1.1.11)
        Version: 3.2.4
        Type: client
        Active agents: 0
        Status:
            Integrity
                Last synchronization: 2018-06-06 05:53:42.54 - 2018-06-06 05:53:42.55.
                Synchronized files: Shared: 0 | Missing: 0 | Extra: 0 | Extra valid: 0.
                Permission to synchronize: True.
            Agents-info
                Last synchronization: n/a - n/a.
                Synchronized files: 0.
                Permission to synchronize: True.
            Agents-group
                Last synchronization: n/a - n/a.
                Synchronized files: 0.
                Permission to synchronize: True.

root@wazuh-manager:~# /var/ossec/bin/cluster_control -a -fn
---------------------------------------------------------------------------------------------
ID   Address    Name                                                Status  Node
---------------------------------------------------------------------------------------------
000  127.0.0.1  wazuh-manager                                       Active  wazuh-master-1
001  101.1.10  client-agent-1                                          Active  wazuh-master-1
---------------------------------------------------------------------------------------------

Listing 2 agent(s).

**Comment by mgmacias95** [comment]
Hello @gyanprakashsahu,

All agents must be registered in the master node. The master node is responsible for replicating the registered agent across all nodes.

Also, I see your agent is reporting to the master node:
```
001 101.1.10 client-agent-1 Active wazuh-master-1
```

You should use a load balancer in your setup to distribute the load among your nodes. There's some information about the [load balancer setup](https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#pointing-agents-to-the-cluster-with-a-load-balancer) in our documentation.

Best regards,
Marta

**Comment by gyanprakashsahu** [comment]
@mgmacias95 

okay..

How to remove redirection http to https of wazuh UI

**Comment by mgmacias95** [comment]
Hello @gyanprakashsahu,

Was my last comment useful? 😄  If your problem is solved and you have new questions or problems you should open new issues. 

Best regards,
Marta

**Comment by gyanprakashsahu** [comment]
Yeah..I am working on that
