### ISSUE TITLE
Error when running wazuh-clusterd with wazuh-clusterd already running

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#7189]
Hi team,

When fixing #5011 , new bugs were found that need to be fixed.

This issue details one of them:

**Problem:**
If you run `wazuh-clusterd` in backround or foreground with `wazuh-clusterd` already running in backround or foreground, the result of `cluster-control` is:
`ERROR: Error 3012 - Cluster is not running`
After this case, no cluster endpoint in the API works, but the cluster does not appear to be down due to the `cluster.log` (there are no error messages and everything appears to be OK). 

**Cause and possible solution:**
The `ERROR 3012` message appears because the socket breaks down when running `wazuh-clusterd` again. The socket is going to be created but the last socket is still running. (It happens when running the daemon in both foreground and background). This may be solved including a condition before running the script that in case the daemon is in both `/var/run` and `/proc` (cluster running), the script stops.

Regards,
Manuel.

**Comment by DomCord** [comment]
I identified that in my case, the "ERROR: Error 3012 - Cluster is not running" was related to the version of the "Master" and the "Workers".

Master: 4.14.5
Worker1: 4.14.4
Worker2: 4.14.4
