### ISSUE TITLE
Test Syscollector 3.5

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#719]
## Description

Unit tests for the new features included in Syscollector for Wazuh 3.5:

- Packages inventory is done natively (Linux/Windows/macOS).
- Network, ports, processes inventory.
- OS information is getting natively (Windows).
- Improvements on Syscollector tables of Wazuh DB.
- A particular decoder for Syscollector events.
- Support to CentOS 5.

## References

**Related issue**: [531](https://github.com/wazuh/wazuh/issues/531) [532](https://github.com/wazuh/wazuh/issues/532)
**Related PR**: [441](https://github.com/wazuh/wazuh/pull/441) [461](https://github.com/wazuh/wazuh/pull/461) [471](https://github.com/wazuh/wazuh/pull/471) [546](https://github.com/wazuh/wazuh/pull/546) [547](https://github.com/wazuh/wazuh/pull/547) [674](https://github.com/wazuh/wazuh/pull/674)
**Documentation**: [226](https://github.com/wazuh/wazuh-documentation/issues/226)

# Unit tests
**Agents**

- [x] Complete scan in Linux (deb/rpm), Windows, macOS and BSD
- [x] Get package list (rpm/deb/macOS/Windows)
- [x] Get network inventory setting more than one IP address per interface
- [x] Scan ports (`listening ports only` vs `all ports`)
- [x] Test Syscollector in CentOS 5 (available scans)

**Manager**

- [x] Check data stored in the agents DB
- [x] Behavior when an insertion in the DB fails

**Comment by bah07** [comment]
Done!
