### ISSUE TITLE
wazuh-elastic2-template.json contains fields with period in mapping names

### ISSUE THREAD

**Issue by igorgatis** [wazuh/wazuh#72]
Tried to execute http://wazuh-documentation.readthedocs.io/en/latest/ossec_elk_elasticsearch.html#ossec-alerts-template

But got:
`{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Field name [file.mode] cannot contain '.'"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [wazuh]: Field name [file.mode] cannot contain '.'","caused_by":{"type":"mapper_parsing_exception","reason":"Field name [file.mode] cannot contain '.'"}},"status":400}`

This was against ElasticSearch 2.4.4 (provided by cloud.elastic.co)

**Comment by snaow** [comment]
Hi @igorgatis,

Are you installing Wazuh 1.1.1? From stable branch? If so, please use the following Elastic template from the stable version branch: https://github.com/wazuh/wazuh/blob/stable/extensions/elasticsearch/elastic-ossec-template.json

If you are installing master version (Wazuh 2.0), try to use the template again, we had some errors on it, we just fix it (ab65cf601ccb3b1ce1fdc3ac5ffbd1060806607d).

Thanks so much for your feedback, let me know if it works.

**Comment by igorgatis** [comment]
I just followed instructions I found at http://wazuh-documentation.readthedocs.io/en/latest/ossec_elk.html

**Comment by snaow** [comment]
I think you got the wrong template file, please give it a try to the above solution I posted.
Let me know if I can help you.

**Comment by hex2a** [comment]
I just tried the updated template (wazuh-elastic2-template.json) from master, the initial bug is fixed, but another one occurred:

`{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Field [rule.id] cannot be analyzed and have doc values"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [wazuh]: Field [rule.id] cannot be analyzed and have doc values",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Field [rule.id] cannot be analyzed and have doc values"
    }
  },
  "status": 400
}`

**Comment by snaow** [comment]
Hi @hex2a,

Thanks for your feedback, we just fix the issue (https://github.com/wazuh/wazuh/commit/be2304c80ba4884724e5a872b2a35c2a77ff8a96)

Some days ago we update the Rule.id mapping type from long to string (https://github.com/wazuh/wazuh/commit/6afac7c200c36ac0ec398ddc79c23e0009611870) but we forgot to add the "not_analyzed" setting.

Please try the last version and let us know if it is working.

**Comment by hex2a** [comment]
Hi @snaow,

thank you, its working now

**Comment by snaow** [comment]
I will close the issue, please don't hesitate to reopen it or create a new one if you need more help or encounter any other issue.

Regards,
Pedro.
