### ISSUE TITLE
Wazuh-logtest hardcoded socket name

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#7216]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Wazuh-logtest | Manager | Packages/Sources | Linux |

Hello team!

WazuhSocket constructor receives string `/var/ossec/queue/ossec/logtest`

https://github.com/wazuh/wazuh/blob/170cc4abbb0fc05b2ed8697990e89d64c9168e18/framework/scripts/wazuh-logtest.py#L213-L226

It causes wazuh-logtest doesn't work if we install Wazuh manager in a different directory.

Best regards,
Eva

**Comment by jnasselle** [comment]
Closed by #7218
