### ISSUE TITLE
Establish a plan to always update python to the latest stable version

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#7221]
Hello team,

For security reasons, as well as to be able to take advantage of the new functionalities of the latest versions of Python, we are going to create a migration plan for our embedded Python.

We need to have a process that indicates the steps to follow as well as the necessary tests to validate that the new version works correctly as well as Wazuh. 

On the other hand, we will investigate how to perform this process automatically. Since we need to review the changes in the Python source code, this process cannot be 100% automated but we will try, as far as possible, to facilitate the process.

Tasks
- [ ] Review all the commands needed to perform the migration.
- [ ] Create a list with the libraries that need a specific process, like cryptography (This one has C code in its code).
- [ ] Create an automated script, as far as possible, for the process to be performed after modifying the Python source code.
- [ ] Create a CLI that allows us to add new dependencies, and if necessary, notify us when these need manual changes.
- [ ] Check that all process is done correctly and both Python and Wazuh work properly.

Regards,
Adrián Peña

**Comment by davidjiglesias** [comment]
Done in Jenkins.
