### ISSUE TITLE
Design and run appropriate tests for python upgraded versions (different OS, architectures, functionality, framework tests, etc)

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#7222]
Hello team,

As part of the migration process, we need to check that Python and Wazuh work properly on all the systems we officially support.

To perform this test we will make use of Jenkins automated tests. In addition to these and in line with what was mentioned in this issue #7221, we will create automatic tests that will check the validity of the Python migration. These tests will be run before the changes are uploaded to the main repository.

Tasks:
- [ ] Add unittests
- [ ] Add system tests

Regards,
Adrián Peña

**Comment by davidjiglesias** [comment]
<
