### ISSUE TITLE
Vulnerability detector stops working after some scans using low interval

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#723]
Hello team, using CentOS 7 and the next configuration:

```xml
<wodle name="vulnerability-detector">
    <disabled>no</disabled>
    <interval>1s</interval>
    <run_on_start>yes</run_on_start>
...
    <feed name="redhat-7">
      <disabled>no</disabled>
      <update_interval>1h</update_interval>
    </feed>
...
  </wodle>
```

The module stops suddenly once 8~10 scans are done. There are no error messages. There are no daemons down. There is no oval being downloaded. 

Discussing with the team, we think it could be caused by low intervals such 1s. If that interval is causing troubles, we need to increase the minimum and/or review it. 

Regards,
Jesús

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/commit/f50ac5d3cd93d41b50ae44e6b78ac0b045c30f9c.
