### ISSUE TITLE
Wazuh API stopped working after unidentified errors

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#7236]
| Wazuh version | Component |
| 3.12.3               | API               |

Hello team,

I am facing the following issue:

The API randomly stops in a period of time. The errors found in the log are the following:
```
WazuhAPI 2020-12-05 21:30:01 GET /agents/?offset=0&limit=1&q=id!%3D000 - 200 - error: '1600'.
{"message": "There is no database for selected agent", "error": 1600}
```

However, the DBs have the proper permission and it's possible to retrieve information from them using API calls, and anything was changed between the issue and the normal operation of it. After restarting the API, seems to be working again. 

Thanks in advance!

**Comment by MiguelCasaresRobles** [comment]
Hello team,

It seems this is a problem related to the global.db and it's not related to the API itself. If we remove that db, the API will throw the aforementioned expectation. However, it won't stop working.

Closing this issue. 

Thank you
