### ISSUE TITLE
Limit number of error downloading the OVAL file from URL on Vulnerability detector

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#724]
Hello team, this is not a problem but if you set a wrong URL to fetch the OVAL file, it's trying to download it with no end. 

Ideas:

- Stop after 5 or 6 failed times
- Set a break time and try it later (Eg: after 30 minutes regardless the interval)

Regards,
Jesús

**Comment by JcabreraC** [comment]
This problem has been solved in the next version, which will be released soon.

Regards,
Juan
