### ISSUE TITLE
Better checking for Vulnerability detector configuration

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#725]
Hello team, this configuration should be invalid:

```xml
<wodle name="vulnerability-detector">
  <disabled>no</disabled>
  <interval>1s</interval>
  <run_on_start>yes</run_on_start>
  <feed name="redhat-7">
    <disabled>no</disabled>
    <url>>https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml</url>
    <url>https://www.redhat.com/security/data/oval/Red_Hat_Enterprise_Linux_7.xml</url>
    <update_interval>1h</update_interval>
    <update_interval>1s</update_interval>
  </feed>
</wodle>
```
This is being ignored: ` <url>>`

Duplicated fields with different values:

```xml
    <update_interval>1h</update_interval>
    <update_interval>1s</update_interval>
```

Regards,
Jesús

**Comment by JcabreraC** [comment]
Hi @jesusgn90 

This configuration has been deprecated since 3.11. It is recommended to use `provider` instead:
https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/vuln-detector.html?highlight=vulnerability%20detector

Regards,
Juan Cabrera
