### ISSUE TITLE
Review API spec parameters

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#7250]
Hello team,

Looking for information about the `GET /syscollector/{agent_id}/packages` endpoint in the documentation, I noticed there are some parameters with wrong description. For instance, this endpoint can receive a `name`:

https://github.com/wazuh/wazuh/blob/9bd5f49aaad5d614405069c1b7d3a459864dbf06/api/api/spec/spec.yaml#L13063

This name relates to the package name, but if we follow the reference, we find this:

https://github.com/wazuh/wazuh/blob/9bd5f49aaad5d614405069c1b7d3a459864dbf06/api/api/spec/spec.yaml#L3949-L3955

As the API reference documentation depends on the API spec, it shows a wrong description:

![image](https://user-images.githubusercontent.com/37274979/105489400-75315200-5cb3-11eb-973b-c2716528ccbf.png)

If we make a request to this endpoint we can confirm that the `name` parameter refers to package name, not agent name:

```json
{
  "data": {
    "affected_items": [
      {
        "scan": {
          "id": 1290946144,
          "time": "2021-01-22T11:37:32Z"
        },
        "section": "libs",
        "size": 269,
        "description": "GCC Quad-Precision Math Library",
        "format": "deb",
        "version": "8.4.0-1ubuntu1~18.04",
        "source": "gcc-8",
        "vendor": "Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>",
        "priority": "optional",
        "architecture": "amd64",
        "multiarch": "same",
        "name": "libquadmath0",
        "agent_id": "000"
      }
    ],
    "total_affected_items": 284,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All specified syscollector information was returned",
  "error": 0
}
```

We should fix this and review the whole spec to see if this happens with more endpoints.

Regards,
Víctor Fernández

**Comment by jctello** [comment]
As well as the spec parameters it will be important to review the naming of the field format validator names.
For example, in the case of the endpoint to add a role to an user: 
![image](https://user-images.githubusercontent.com/36071202/117859071-d8f58000-b28e-11eb-8acf-f46b67db5511.png)


https://github.com/wazuh/wazuh/blob/9bd5f49aaad5d614405069c1b7d3a459864dbf06/api/api/spec/spec.yaml#L14725-L14732

It references `role_ids_required` which in turn references the `Role_id_DELETE` schema that uses the `numbers_delete` format.
https://github.com/wazuh/wazuh/blob/9bd5f49aaad5d614405069c1b7d3a459864dbf06/api/api/spec/spec.yaml#L1675-L1678

There is no documentation on what are the requirements for this format which is presumably thus named because it is used in a deletion endpoint and it seems that this is specified in a different file: 
https://github.com/wazuh/wazuh/blob/d6119bb49306ea1dea3231ee1817be9a2e50f68b/api/api/validator.py#L32

**Comment by Espectro123** [comment]
## Issue update

### Endpoints reviewed

```python
- /active-response
- /agents
- /agents/{agent_id}/config/{component}/{configuration}
- /agents/{agent_id}/group
- /agents/{agent_id}/group/is_sync
- /agents/{agent_id}/group/{group_id}
- /agents/{agent_id}/key
- /agents/{agent_id}/restart
- /agents/{agent_id}/stats/{component}
- /agents/upgrade
- /agents/upgrade_custom
- /agents/upgrade_result
- /agents/group
- /agents/group/{group_id}/restart
- /groups
```

### Endpoints with wrong described parameter

#### /agents/{agent_id}/group/{group_id}
force_single_group:
- **Before**: Whether to append the new group to current agent's multigroup or replace it
- **After**:  Removes the agent from all groups to which it belongs and assigns it to the specified group

#### /agents/upgrade_custom
file_path:
- **Before**: Full path to the WPK file. The file must be on a folder ```on the``` Wazuh's installation directory (by default, <code>/var/ossec</code>)
- **After**: Full path to the WPK file. The file must be on a folder ```inside``` Wazuh's installation directory (by default, <code>/var/ossec</code>)

**Comment by Espectro123** [comment]
## Issue update

### Endpoints reviewed

```python
- /active-response
- /agents
- /agents/{agent_id}/config/{component}/{configuration}
- /agents/{agent_id}/group
- /agents/{agent_id}/group/is_sync
- /agents/{agent_id}/group/{group_id}
- /agents/{agent_id}/key
- /agents/{agent_id}/restart
- /agents/{agent_id}/stats/{component}
- /agents/upgrade
- /agents/upgrade_custom
- /agents/upgrade_result
- /agents/group
- /agents/group/{group_id}/restart
- /groups
- /groups/{group_id}/configuration
- /groups/{group_id}/files/{file_name}/xml
- /agents/insert
- /agents/insert/quick
- /agents/no_group
- /agents/node/{node_id}/restart
- /agents/outdated
- /agents/reconnect
- /agents/restart
- /agents/stats/distinct
- /agents/summary/os
- /agents/summary/status
- /ciscat/{agent_id}/results
- /cluster/local/info
- /cluster/nodes
- /cluster/healthcheck
- /cluster/status
- /cluster/local/config
- /cluster/api/config
- /cluster/{node_id}/status
- /cluster/{node_id}/info
- /cluster/{node_id}/configuration
- /cluster/{node_id}/stats
- /cluster/{node_id}/stats/hourly
- /cluster/{node_id}/stats/weekly
- /cluster/{node_id}/stats/analysisd
- /cluster/{node_id}/stats/remoted
- /cluster/{node_id}/logs
- /cluster/{node_id}/logs/summary
- /cluster/restart
- /cluster/configuration/validation
- /cluster/{node_id}/configuration/{component}/{configuration}
- /lists
- /lists/files/{filename}
- /lists/files
- /logtest
- /logtest/sessions/{token}
- /manager/status
- /manager/info
- /manager/configuration
- /manager/stats
- /manager/stats/hourly
- /manager/stats/weekly
- /manager/stats/analysisd
- /manager/stats/remoted
- /manager/logs
```

### Endpoints with wrong described parameter

#### /agents/{agent_id}/group/{group_id}
force_single_group:
- **Before**: ```Whether to append the new group to current agent's multigroup or replace it```

- **After**:  ```Removes the agent from all groups to which it belongs and assigns it to the specified group```

#### /agents/upgrade_custom
file_path:
- **Before**: Full path to the WPK file. The file must be on a folder ```on the``` Wazuh's installation directory (by default, /var/ossec)

- **After**: Full path to the WPK file. The file must be on a folder ```inside``` Wazuh's installation directory (by default,/var/ossec)

#### /groups
search:
- **Before**: Look for elements containing the specified string. To obtain a complementary search, use '-' at the ```beggining```

- **After**: Look for elements containing the specified string. To obtain a complementary search, use '-' at the ```beginning```

#### /cluster/{node_id}/configuration:
The ```raw_conf``` parameter has been chaged to ```raw```

#### /manager/configuration:
The ```raw_conf``` parameter has been chaged to ```raw```

**Comment by Espectro123** [comment]
## Issue update

### Endpoints reviewed

```python
- /active-response
- /agents
- /agents/{agent_id}/config/{component}/{configuration}
- /agents/{agent_id}/group
- /agents/{agent_id}/group/is_sync
- /agents/{agent_id}/group/{group_id}
- /agents/{agent_id}/key
- /agents/{agent_id}/restart
- /agents/{agent_id}/stats/{component}
- /agents/upgrade
- /agents/upgrade_custom
- /agents/upgrade_result
- /agents/group
- /agents/group/{group_id}/restart
- /groups
- /groups/{group_id}/configuration
- /groups/{group_id}/files/{file_name}/xml
- /agents/insert
- /agents/insert/quick
- /agents/no_group
- /agents/node/{node_id}/restart
- /agents/outdated
- /agents/reconnect
- /agents/restart
- /agents/stats/distinct
- /agents/summary/os
- /agents/summary/status
- /ciscat/{agent_id}/results
- /cluster/local/info
- /cluster/nodes
- /cluster/healthcheck
- /cluster/status
- /cluster/local/config
- /cluster/api/config
- /cluster/{node_id}/status
- /cluster/{node_id}/info
- /cluster/{node_id}/configuration
- /cluster/{node_id}/stats
- /cluster/{node_id}/stats/hourly
- /cluster/{node_id}/stats/weekly
- /cluster/{node_id}/stats/analysisd
- /cluster/{node_id}/stats/remoted
- /cluster/{node_id}/logs
- /cluster/{node_id}/logs/summary
- /cluster/restart
- /cluster/configuration/validation
- /cluster/{node_id}/configuration/{component}/{configuration}
- /lists
- /lists/files/{filename}
- /lists/files
- /logtest
- /logtest/sessions/{token}
- /manager/status
- /manager/info
- /manager/configuration
- /manager/stats
- /manager/stats/hourly
- /manager/stats/weekly
- /manager/stats/analysisd
- /manager/stats/remoted
- /manager/logs
- /manager/logs/summary
- /manager/api/config
- /manager/restart
- /manager/configuration/validation
- /manager/configuration/{component}/{configuration}
- /mitre/groups
- /mitre/metadata
- /mitre/mitigations
- /mitre/references
- /mitre/software
- /mitre/tactics
- /mitre/techniques
- /rootcheck
- /rootcheck/{agent_id}
- /rootcheck/{agent_id}/last_scan
- /rules
- /rules/groups
- /rules/requirement/{requirement}
- /rules/files
- /rules/files/{filename}
- /sca/{agent_id}
- /sca/{agent_id}/checks/{policy_id}
- /syscheck
- /syscheck/{agent_id}
- /syscheck/{agent_id}/last_scan
- /decoders
- /decoders/files
```

### Endpoints with wrong described parameter

#### /agents/{agent_id}/group/{group_id}
force_single_group:
- **Before**: ```Whether to append the new group to current agent's multigroup or replace it```

- **After**:  ```Removes the agent from all groups to which it belongs and assigns it to the specified group```

#### /agents/upgrade_custom
file_path:
- **Before**: Full path to the WPK file. The file must be on a folder ```on the``` Wazuh's installation directory (by default, /var/ossec)

- **After**: Full path to the WPK file. The file must be on a folder ```inside``` Wazuh's installation directory (by default,/var/ossec)

#### /groups
search:
- **Before**: Look for elements containing the specified string. To obtain a complementary search, use '-' at the ```beggining```

- **After**: Look for elements containing the specified string. To obtain a complementary search, use '-' at the ```beginning```

#### The raw_conf parameter has been removed from the API as it was redundant. Now, the raw parameter is used on the affected endpoints.

#### /cluster/{node_id}/configuration:
The ```raw_conf``` parameter has been chaged to ```raw```.

#### /manager/configuration:
The ```raw_conf``` parameter has been chaged to ```raw```.
