### ISSUE TITLE
Generate filtered files for alerts in /var/ossec/logs/alerts/

### ISSUE THREAD

**Issue by akhan23wgu** [wazuh/wazuh#7254]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.1-4008 | Wazuh component | Manager | Packages | CentOS Linux release 7.9.2009 (Core) |

For audit purposes we are seeing that we need to retain certain types of alerts longer than others. It would be great if there was a way to filter alerts in different files in /var/ossec/logs/alerts/.

Example:

Audit alerts are triggered, these alerts would go into /var/ossec/logs/alerts/audit.json.

Current Behavior:

All alerts are dumped into a single alerts.json file.

**Comment by jnasselle** [comment]
Hi @akhan23wgu !

This could be implemented using `ossec-integratord`, allowing to filter alerts by level, rule id, location, group, and then running a custom script to do whatever you want with it, in this case saving it to a different file.

For example, the next `integration` block in manager's `ossec.conf` will filter alerts with id 80703 and 80704 (some audit ones) and run `/var/ossec/integrations/custom-audit-logs` python script:
```xml
<integration>
  <name>custom-audit-logs</name>
  <alert_format>json</alert_format>
  <rule_id>80703,80704</rule_id>
</integration>
```

Then create the file `/var/ossec/integrations/custom-audit-logs` with privileges `750` and `root:ossec` ownership

```python
#!/usr/bin/env python
  
import sys
import json
  
# Read configuration parameters
alert_file = open(sys.argv[1])
  
# Read the alert file
alert = alert_file.read()
alert_file.close()
 
with open('/home/user/audit.json', 'a') as file:
	file.write(alert)
	file.close()

sys.exit(0)
```

This will cause that every alert from rules 80703 and 80704 will be appended to `/home/user/audit.json`.

Here's a [really nice blog about integratord](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/) and also the [integration configuration docs](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/integration.html).

I hope this helps. Let me know if you have further questions

**Comment by jnasselle** [comment]
Closed due to inactivity. Feel free to open the issue again if you have any related question.

Regards,
Nico
