### ISSUE TITLE
Empty wodle block causes weird error

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#727]
Using this empty wodle:

```xml
<wodle name="vulnerability-detector">
</wodle>
```

Causes this error once `ossec-control restart` is executed:

```
OSSEC analysisd: Testing rules failed. Configuration error. Exiting.
```

From my view this could be confused

Regards,
Jesús

**Comment by chemamartinez** [comment]
Done: [#781](https://github.com/wazuh/wazuh/pull/781)
