### ISSUE TITLE
Vulnerability detector - wazuh-modulesd crash

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7272]
## Description

![image](https://user-images.githubusercontent.com/14300208/105886621-60bdc400-5fe9-11eb-8d82-3dc72ebe8d82.png)

Issue found during exploratory / functional test.

When the vendor is empty, it possibly generates a segmentation fault, since the return of wm_vuldet_decode_cpe is not being controlled.

## DoD
- [x] Add sanity to cpe structure before w_strdup
- [x] PR \ CI Pass

**Comment by MarcelKemp** [comment]
Apparently, with some development after `4.2.5`, the condition that fixed this issue has been lost, so the fix needs to be re-added.

Here are the lines of code:
- `4.2.5`:
https://github.com/wazuh/wazuh/blob/d9bdabd771d70933276754fbab02c6939292065e/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L4613
- `4.3`:
https://github.com/wazuh/wazuh/blob/d0ecc1b3134d5746c17ccd98ec384182d6ecf921/src/wazuh_modules/vulnerability_detector/wm_vuln_detector.c#L5015
