### ISSUE TITLE
Sprint 124 Coverity round - dev-syscollector-dbsync-rsync

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7277]
## Description
Sprint 124 Coverity round

## DoD
- [x] Run coverity.
- [x] Analyze issues.
- [x] Fix issues.
- [x] PR - CI PASS

**Comment by tinachoB** [comment]
**Last Coverity execution Results:**
![image](https://user-images.githubusercontent.com/22640902/106812265-2e960d00-664e-11eb-9285-404c4ad45a08.png)

**Issues:**
- 216924 - Unchecked return value
- 216925 - Unchecked return value
- 216926 - Unchecked return value
- 216927 - Dereference null return value
- 216928 - Unchecked return value
- 216929 - Unchecked return value
- 216930 - Unchecked return value
