### ISSUE TITLE
Any possibility of a real-time regex-tester for OS_Regex and OS_Match?

### ISSUE THREAD

**Issue by cbj4074** [wazuh/wazuh#7280]
The ability to test OS_Regex and OS_Match patterns in a real-time tester would make writing Wazuh Decoders and rules so much simpler, in my opinion. The `ossec-logtest` tool can be used for this purpose, but a tool that is specifically for writing and testing patterns, with no concern for the Ruleset, seems like it would be very useful.

While Regex101 is only one of many such real-time testing tools, it provides a framework for "Code generator" flavours, which may render this a fairly straightforward task.

There is already an open Feature Request from Wazuh users asking for Regex101 to add support for these flavours:

https://github.com/firasdib/Regex101/issues/1238

I may take a swing at it, but I suspect that one of the Wazuh developers who works regularly with OS_Regex and OS_Match could do a much better job. :)

**Comment by nmkoremblum** [comment]
Hi Ben!

There is indeed a Regex validator among the Wazuh's tools. Please, take a look at this user-manual page: [**ossec-regex**](https://documentation.wazuh.com/4.0/user-manual/reference/tools/ossec-regex.html). The thing is that, at this time, **it supports OS_Regex _but not yet_ OS_Match** pattern validations.

We just opened an issue to request the feature to be added, I encourage you to follow this request in the following link: [#7288](https://github.com/wazuh/wazuh/issues/7288).

Thanks for your message, we remain at your disposal,

Nicolás Mariano Koremblum

**Comment by cbj4074** [comment]
@nmkoremblum Thank you! That is fantastic, on all fronts! The Wazuh team seems to think of everything.

And now that you mention it, I was able to find the reference documentation:

https://documentation.wazuh.com/4.0/user-manual/reference/tools/ossec-regex.html

I don't know if it's of any interest to the Wazuh team, but as a user and community member, I can say, with gumption, that a browser-based "wrapper" around this tool that allows for real-time, as-you-type analysis would be the "cherry on top". 😄 

I am by no means complaining; the tool is a huge help as it stands, but not to have to re-enter the pattern after each check, and to be able to edit it in a standard form-field and using the arrow-keys and/or mouse, would be truly brilliant.

I'd take a shot at it myself, but nobody probably wants to visit my website to use the tool; hosting it on wazuh.com seems preferable for many reasons!

Just a thought... thanks again!

**Comment by nmkoremblum** [comment]
@cbj4074 thanks to you, again, for sharing your thoughts in order to make Wazuh better! We do pay attention gladly to the users' ideas as we are always looking forward to improve Wazuh.

I added a comment about it in the same issue ([#7288.](https://github.com/wazuh/wazuh/issues/7288)) as before.

Stay tuned! Regards,

Nicolás Mariano Koremblum
