### ISSUE TITLE
How do I manually trigger a vulnerability scan on the agent machine (client)

### ISSUE THREAD

**Issue by kirandevops** [wazuh/wazuh#7284]
Hi there,

Instead of waiting for the scheduled vulnerability scan, how do I force vulnerability scan on the agent machine to get the latest vulnerabilities after fixing issues?

Thanks!

**Comment by pereyra-m** [comment]
Hello @kirandevops !

Thank you for your question.
That feature would be really useful and it is already under development. You can see its progress in the related issues #3231 and #3687.

In the meantime, I can only suggest you to restart Wazuh manager after enabling the [<run_on_start>](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/vuln-detector.html#run-on-start) option in your `ossec.conf` file. This configuration will force a vulnerability scan on every start

```
<vulnerability-detector>
  <enabled>yes</enabled>
  <interval>5m</interval>
  <run_on_start>yes</run_on_start>
  ...
</vulnerability-detector>
```

Also, consider that the agent will collect its packages information according to the `<interval>` option. You may have to restart it too or wait to see the changes. Here is the agents' configuration section 

```
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <os>yes</os>
  <packages>yes</packages>
</wodle>
```

There is more information about it in the [Running a vulnerability scan](https://documentation.wazuh.com/4.0/user-manual/capabilities/vulnerability-detection/running_vu_scan.html#running-a-vulnerability-scan) documentation section.

Please, tell me if there is anything else I can do for you.
Regards.

**Comment by kirandevops** [comment]
Thanks for quick response @pereyra-m. Looking forward for this feature to be released soon.

**Comment by pereyra-m** [comment]
Thanks to you!
Best regards.
