### ISSUE TITLE
Active response fails if the alert is generated in a file with a name with spaces

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#7305]
|Wazuh version|Component|Install type|Install method|
|---|---|---|---|
| 3.13+ | Wazuh remoted/active response | Manager | Packages/Sources |

## Description

When an active response is triggered from a log file that has spaces in its name, the code responsible for forwarding active responses from the manager to an agent fails while parsing the message and the AR is never triggered.

### Example

If we use a simple rule like the following to trigger active responses:
```xml
  <rule id="200104" level="5">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
```

And we configure an agent to monitor logs from a file with spaces in its name:
```xml
  <localfile>
    <location>C:\test log.txt</location>
    <log_format>syslog</log_format>
  </localfile>
```

We can then trigger alerts by simply copying the following line inside the text file:
```
Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
```

We use the following configuration on the manager to trigger ARs based on the previous rule:
```xml
  <command>
    <name>kill-file</name>
    <executable>kill-file.cmd</executable>
    <timeout_allowed>no</timeout_allowed>
  </command>

  <active-response>
    <command>kill-file</command>
    <location>local</location>
    <rules_id>200104</rules_id>
  </active-response>
```

And the manager will show the following log messages:
```
2021/01/28 18:57:19 wazuh-remoted[25496] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (win-vm) any->\test log.txt NRN (null) kill-file0 - - 1611860239.1700589 200104 (win-vm) any->\test log.txt - -
2021/01/28 18:57:19 wazuh-remoted[25496] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd (null) kill-file0 - - 1611860239.1700589 200104 (win-vm) any->\test log.txt - -
```

If we remove the whitespace from the name of the logfile, we can see a difference on the `Active response sent` message:
```
2021/01/28 18:59:28 wazuh-remoted[25496] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (win-vm) any->\test-log.txt NRN (null) kill-file0 - - 1611860368.1702108 200104 (win-vm) any->\test-log.txt - -
2021/01/28 18:59:28 wazuh-remoted[25496] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd kill-file0 - - 1611860368.1702108 200104 (win-vm) any->\test-log.txt - -
```

This last messages are correct and actually trigger the AR on the agent.

What happens is that the function [AR_Forward](https://github.com/wazuh/wazuh/blob/a69482627619a3cf2328b2d5498199c73d421f05/src/remoted/ar-forward.c#L19) uses whitespaces to find a couple of fields that it needs to format the final message to forward to the agent and having whitespaces in the name of the file causes it to lose the point of reference.

**Comment by TomasTurina** [comment]
Fixed in https://github.com/wazuh/wazuh/commit/ea011b31047b32222d7fd0996cc4c93def7c6390
