### ISSUE TITLE
Patches not available in the Microsoft Catalog

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#7329]
Hi team,

We have found a problem related to vulnerabilities in _Windows Server 2016_. 
In this case, we find a server with _Windows Server 2016_ updated to date (`KB4598243`) in which it shows a series of vulnerabilities because it cannot find the following list of patches:

```
KB4471321
KB4512517
KB4507460
KB4025339
KB4038782
KB4053579
KB4487026
KB4041691
KB4013429
```

Upon investigation, patch `KB4512517` is the supersedence of all the others on the list. 
In addition, below we can see that `KB4512517` also has a `KB4516044` supersedence. The problem is that both patches are not available in the catalog, so they cannot be installed and it still shows the associated vulnerabilities.

          "KB4512517": [
               "KB4516044"
          ],

It would be necessary to investigate why this case does not have an updated supersedence that includes all the patches on the list, and find out why the supersedences mentioned above are no longer available in the catalog.

**Comment by thefactor82** [comment]
Hi,
I'm the one who originally reported this problem to Marcel.
If there is anything I can do to support you in troubleshooting this issue, please don't hesitate to ask.
I have a lot of my Win2016 monitored machines with this issue, but not every of them... And it is quite annoying to receive alerts for these missing kbs that I cannot install...

**Comment by MarcelKemp** [comment]
Hi @thefactor82,

The problem seems to be the `KB4512517` patch, because it is not available in the [Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4512517) and we cannot currently associate it directly with other patches due to lack of information from our providers ([Catalog](https://www.catalog.update.microsoft.com/Home.aspx) and [Microsoft API](https://microsoft.github.io/MSRC-Microsoft-Security-Updates-API/)).

However, after a little investigation about the case, I have noticed that there are patches in the Catalog that are supersedences of `KB4512517`. Some examples are the following: [**KB4565511**](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4565511), [**KB4561616**](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4561616), [**KB4571694**](https://www.catalog.update.microsoft.com/Search.aspx?q=KB4571694)...


Therefore, in order to solve this case, we have to implement a _backward recursion search_.
The good news is that this improvement is on our roadmap and we are working on it. 
If you want to see the progress, here is the issue: https://github.com/wazuh/wazuh/issues/6996

I hope it helps you and I'm sorry for the inconvenience.
If you have any questions, do not hesitate to ask.

**Comment by thefactor82** [comment]
Thanks a lot, I will follow the issue 6996!

**Comment by rtjdamen** [comment]
Same issue here, a lot of up 2 date windows machines reporting old cve’s, other tool does report them as up 2 date as well. Think this is the same issue.

**Comment by MarcelKemp** [comment]
As I mentioned in #6996, we have fixed the problem internally and the release of the new MSU will be available this week.
