### ISSUE TITLE
aws.py CloudTrail event overflowing max buffer size on socket

### ISSUE THREAD

**Issue by jjrbg** [wazuh/wazuh#733]
I've seen events from AWS CloudTrail causing aws.py to fall over due to exceeding the maximum string length on the socket. Length of the event was > 200000. :-O

I'm not sure what the buffer is, where it's controlled, or what a reasonable max length to configure is.

if len(formatted.encode()) > 65535:
  continue

...might be worth adding to ignore abnormally long JSON messages from AWS?

The result of the repeated terminations every 10 mins, was reprocessing the same log file over and over and duplicating alerts as the delete step was never reached.

**Comment by UranusBytes** [comment]
Can you provide any hint on what type of CloudTrail event was over 200k in size?  Or even, better, provide an example event?

I'm working on changes in the CloudTrail module right now, and figured I could try to solve this at the same time, but having trouble generating such a large event in CloudTrail...

**Comment by UranusBytes** [comment]
Also, please confirm if you've changed/increased any of the kernel parameters such as net.core.rmem_default or net.core.rmem_max...
