### ISSUE TITLE
Remove os_patch from package table (agent side).

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7335]
## Description

This issue aims to correct a rebase problem when a git merge was done with master, to correct this you just have to remove code from the os_patch field.

## DoD
- [x] Remove from packages table configuration,
- [x] Check/Add os_patch regex on osinfo parser.
- [x] Update tests
- [x] RTR
- [x] PR - CI Pass

**Comment by konangc87** [comment]
cicd failed installing on solaris 11 due to a shutdown issue unrelated with this code. It will be fixed in another PR.
