### ISSUE TITLE
OSSEC Syslog not processing logs

### ISSUE THREAD

**Issue by fayax** [wazuh/wazuh#735]
I have syslog server enabled with the following config
```
<remote>
   <connection>syslog</connection>
   <port>514</port>
   <protocol>udp</protocol>
   <allowed-ips>0.0.0.0/0</allowed-ips>
</remote>
```

I can see that syslog server is started. But I can't see any logs from remote devices in alerts.log file

**Comment by TJOSERAFAEL** [comment]
Hi @fayax,

there are a few things you can check.

1. Set `<allowed-ips>YOUR_SYSLOG_DEVICE_IP</allowed-ips>`
2. Enable the **logall** option on your manager  `<logall>yes</logall>`
3. Restart your manager
4. Watch the file /var/ossec/logs/archives/archives.log for incoming data from your syslog server
  `#tail -f /var/ossec/logs/archives/archives.log`

If you can see the incoming data on the file above, then it's working.

Best regards.

**Comment by fayax** [comment]
@TJOSERAFAEL 

This fixed my issue:
1. Enable log all option `<logall>yes</logall>`
2. Change log alert level from 3 to 1. `<log_alert_level>1</log_alert_level>`

Thanks for the assistance.

**Comment by TJOSERAFAEL** [comment]
Hi @fayax,

I'm glad it worked.

You are welcome!.

**Comment by dipak-dabhi1991** [comment]
Hi All,

after configuring syslog,
Wazuh API not showing logs on Discover Section.

netstat -pna | grep 514
tail -f /var/ossec/logs/archives/archives.log  -> i can seed log here

**Comment by ThaCeeBee** [comment]
> Hi All,
> 
> after configuring syslog, Wazuh API not showing logs on Discover Section.
> 
> netstat -pna | grep 514 tail -f /var/ossec/logs/archives/archives.log -> i can seed log here

Having this same issue. Someone knows hoe to solve this?
