### ISSUE TITLE
Inconsistency between databases (Vulnerability detector)

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#738]
Hello team, researching about https://github.com/wazuh/wazuh/issues/737 we've found another problem:

```
sqlite> select distinct os from VULNERABILITIES;
STRETCH
JESSIE
BIONIC
```
```
sqlite> select * from METADATA;
STRETCH|Debian||5.3|2018-06-07 07:34:49.188-04:00
JESSIE|Debian||5.3|2018-06-07 07:34:30.188-04:00
WHEEZY|Debian||5.3|2018-06-07 07:34:19.188-04:00
BIONIC|Canonical CVE OVAL Generator|1|5.11.1|2018-06-07 09:24:11
```

`WHEEZY` is missing in `VULNERABILITIES` so something is broken.

Regards,
Jesús

**Comment by crolopez** [comment]
Solved in https://github.com/wazuh/wazuh/commit/e49257b431ba623fe01de4cff9841e6106337e0a.
