### ISSUE TITLE
win_agent.c OS_ReadKeys incorrect parameters

### ISSUE THREAD

**Issue by pcurtday** [wazuh/wazuh#74]
Master branch:
src/win32/win_agent.c

Line 205 OS_ReadKeys is missing the third parameter which I assume should be the number 0.

OS_ReadKeys($keys, 1, 0);

TARGET=winagent won't build, obviously, without that

**Comment by pcurtday** [comment]
This is on the Master Branch.

**Comment by vikman90** [comment]
Hi @pcurtday,

thank you very much for reporting it. We have fixed it just now: https://github.com/wazuh/wazuh/commit/4c0ad3f56f9a6697297f00082dcc91e47ce2898d

Thanks again for your feedback!
