### ISSUE TITLE
Wazuh in project documentation

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7437]
## Description

This issue aims to move the readme from the RTR src / readme, also to update the readme from the RTR and move it to where is the build.py

Update with reliable information on the installation steps in INSTALL.MD in root project folder.

## DoD
- [x] Modify readme/install files.
- [x] PR

**Comment by palaciosjeremias** [comment]
Minor redaction observation:
In **/src/shared_modules/dbsync/testtool/Readme.md**

**sql_statement: Database sql structure to be created. This structure will be associated the other files needed to used the tool.**
should be:
**sql_statement: Database sql structure to be created. This structure will be associated with the other files needed to use the tool.**
