### ISSUE TITLE
Bug when parsing Windows agents version from agent-info files

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#747]
Agents version are stored in the `Global.db` database getting that information from the `agent-info` files coming from agents. In 3.2.X, it seems that for Windows agents, the manager is not parsing that field correctly, as we can see in the following list:

```
   "Wazuh v2.1.0": 50,
   "Wazuh v2.1.1": 1524,
   "Wazuh v2.1.1 [Ver: 6.2.9200] - Wazuh v2.1.1": 1,
   "Wazuh v2.0.1": 302,
   "Wazuh v3.2.1": 5235,
   "Wazuh v3.2.1 [Ver: 6.3.9600] - Wazuh v3.2.1": 7
```

Notice that the third and sixth line include duplicated information.

**Comment by jesuslinares** [comment]
This is the agent-info file for an agent with wrong version:
```
cat agentname-any
Microsoft Windows Server 2012 StandardMicrosoft Windows Server 2012 Standard [Ver: 6.2.9200] - Wazuh v3.2.1 [Ver: 6.2.9200] - Wazuh v3.2.1 / ab73af41699f13fdd81903b5f23d8d00
cf6164d99f132aca01b105bfa473e085 merged.mg
#"manager_hostname":...
#"node_name":...
```

**Comment by chemamartinez** [comment]
This issue was related to agents Windows Server 2012 (Standard and Database versions) for Wazuh versions v2.1.1 - v3.2.1 when getting the Operating System information to send the keepalive message to the manager.

For that OS, in Wazuh v3.2.1 that information was being extracted from the WMI tool:

https://github.com/wazuh/wazuh/blob/v3.2.1/src/shared/file_op.c#L1365

However, since v3.2.2 that information is read from registry keys directly:

https://github.com/wazuh/wazuh/blob/v3.2.2/src/shared/file_op.c#L1365

That changes should solve the issue for Wazuh v3.2.2 and later versions.
