### ISSUE TITLE
Security API endpoints 'IndexError' when user doesn't have permissions and use 'all'. 

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7473]
|Wazuh version|Component|
|---|---|
| 4.1/master | API |

## Description

Hi team,

I found a bug in the responses from some `/security` endpoints. When using the parameter `role_ids: all`/`policy_ids: all`/`rule_ids: all` inside DELETE endpoints like  `/security/users/{user_id}/roles`, all the roles for the user `user_id` should be deleted. 

However, if the user has no permissions on any role, the RBAC decorator will return an empty list but the framework will try to access the first item (role_id[0]) so an exception is raised:

> DELETE /security/users/99/roles
```JSON
{
  "title": "Wazuh Internal Error",
  "detail": "Wazuh Internal Error",
  "remediation": "Please, check `WAZUH_HOME/logs/ossec.log`, `WAZUH_HOME/logs/cluster.log` and `WAZUH_HOME/logs/api.log` to get more information about the error",
  "dapi_errors": {
    "unknown-node": {
      "error": "Wazuh Internal Error. See log for more detail",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 1000
}
```
```
2021/02/12 10:43:02 ERROR: Error executing API request locally: list index out of range
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 250, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/var/ossec/framework/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/core/cluster/dapi/dapi.py", line 224, in run_local
    data = self.f(**self.f_kwargs)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/rbac/decorators.py", line 417, in wrapper
    result = func(*args, **kwargs) if not skip_execution else None
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/security.py", line 687, in remove_user_role
    username = get_username(user_id=user_id)
  File "/var/ossec/framework/python/lib/python3.8/site-packages/wazuh-4.1.1-py3.8.egg/wazuh/security.py", line 619, in get_username
    user = am.get_user_id(user_id=int(user_id[0]))
IndexError: list index out of range
2021/02/12 10:43:02 INFO: testing 192.168.32.1 "DELETE /security/users/99/roles" done in 0.015s: 500
```

The problem lies here:
https://github.com/wazuh/wazuh/blob/a9674c6453dd47ad5e9c46282bed482a8fc4bb8b/framework/wazuh/security.py#L849-L865

Similar things occur with endpoints below:
- DELETE /security/roles/{role_id}/policies
- DELETE /security/roles/{role_id}/rules

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by Espectro123** [comment]
## Status update

Hello team, we have duplicated the decorators in the affected functions, we have created a new function to get the role, similar to get_username, and we have added an additional check at the beginning of the function.

This still need testing.

**Comment by Espectro123** [comment]
## Status update

Hello team. I have finish testing this issue. Now, we have duplicate decorators in the affected functions:
### remove_role_rule 
![image](https://user-images.githubusercontent.com/9986983/115239474-126b1d80-a11f-11eb-8eeb-396269f66474.png)
### remove_role_policy
![image](https://user-images.githubusercontent.com/9986983/115239517-2282fd00-a11f-11eb-9a51-a9c0d87d247b.png)
### remove_user_role
![image](https://user-images.githubusercontent.com/9986983/115239404-f7001280-a11e-11eb-9269-0deb9bd82e0d.png)

This fix the issue of the empty list. When you call one of this functions with a user or role that don't exist it will trigger an exception **5001** for the user function and **4002** for the other two functions. 

### remove_role_rule
![image](https://user-images.githubusercontent.com/9986983/115240422-06339000-a120-11eb-985f-8ca98874fb8b.png)
### remove_role_policy
![image](https://user-images.githubusercontent.com/9986983/115240437-07fd5380-a120-11eb-9a70-7f859cf72929.png)
### remove_user_role

**Comment by Espectro123** [comment]
Hi team! 

The integration tests that the DELETE method checks have been updated.

```
test_rbac_black_security_endpoints.tavern.yaml 
	 20 failed, 5 passed, 27 warnings

test_rbac_white_security_endpoints.tavern.yaml 
	 25 passed, 27 warnings

test_security_DELETE_endpoints.tavern.yaml 
	 15 passed, 17 warnings

test_security_GET_endpoints.tavern.yaml 
	 18 passed, 21 warnings

test_security_POST_endpoints.tavern.yaml 
	 7 passed, 9 warnings

test_security_PUT_endpoints.tavern.yaml 
	 9 failed, 11 warnings

```

The rbac_black and PUT integration tests still need to be updated.

Tomorrow I will update them so that they can pass without problems.
