### ISSUE TITLE
Analysisd does not correctly change the option json_null_fields correctly

### ISSUE THREAD

**Issue by psrodrigues** [wazuh/wazuh#7486]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | analysisd | Manager | Packages/Sources | CentOS Linux release 8.3.2011|

Analysisd does not correctly change the option json_null_fields (https://documentation.wazuh.com/4.0/user-manual/ruleset/ruleset-xml-syntax/decoders.html#json-null-field) correctly. After trying to change through the different options (string,discard,empty) I noticed that the discard option does not work. After investigation I reach the code that would do the flag setup of the option: https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L459. In this block of code is where the flags are setup, however, the flags do not come empty with predefined values being setup in https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L298. The values are defined in their headers having the following values setup:

|Option |Value|
|---|---|
|DISCARD|0|
|EMPTY|1|
|SHOW_STRING|2|
|CSV_STRING|4|
|JSON_ARRAY|8|

The default values set at https://github.com/wazuh/wazuh/blob/master/src/analysisd/decoders/decode-xml.c#L298 are **SHOW_STRING | JSON_ARRAY** this will rend the operation as 2+8=A(hex) then the code performs the necessary adjustments with the operation:

`pi->flags |= <DISCARD/EMPTY/SHOW_STRING>;
`
However being discard the NULL value the operation will never change its flag due to the bitwise operation:

`pi->flags |= DISCARD;
A |= 0 <=> A
`

Here are the values that are possible to get from the default setted A flag with the JSON_ARRAY:

|Option |Value (hex)|
|---|---|
|DISCARD| A |
|EMPTY|B |
|SHOW_STRING|A|

![Values from patched code ](https://i.ibb.co/mCLYr3p/2021-02-12-22-55-15-Window.png)

Since the type of the flag value is **u_int8_t** maybe a better alternative is to use the most significant part for the JSON_ARRAY and CSV_STRING (since we either have one or another) and the least significant part for the rest so we can perform bitwise operations such as:

|Option |Value|
|---|---|
|CSV_STRING|16|
|JSON_ARRAY|32|

`pi->flags = pi->flags & 0x0f +<CSV_STRING/JSON_ARRAY> // (for the most significant bit, assuming the CSV_STRING JSON_ARRAY and  such as 16 and 32 to avoid overlapping, otherwise we need to shift the values to the left)
`

`pi->flags = pi->flags & 0xf0 +<DISCARD/EMPTY/SHOW_STRING> // (for the least significant bit)`

**Comment by jnasselle** [comment]
Hi @psrodrigues !

Thank you very much for reporting this bug and with such level of detail! This fix is currently on the way.

In this process we also found that, in case you set `<json_null_field>empty</json_null_field>` within a decoder and any log contain a field with null value, this field is omitted because is empty when writing outputs i.e `alerts.log` and  `alerts.json` (that feeds kibana).

https://github.com/wazuh/wazuh/blob/v4.1.1/src/analysisd/alerts/log.c#L294-L300

https://github.com/wazuh/wazuh/blob/v4.1.1/src/analysisd/format/to_json.c#L495-L502

This behavior will be fixed as well.

Regards,
Nico

**Comment by psrodrigues** [comment]
Thank you very much @jnasselle :)
