### ISSUE TITLE
wazuh-alerts- template missing and index not created

### ISSUE THREAD

**Issue by zWaR** [wazuh/wazuh#7489]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4 | elasticsearch | Manager | Packages | centOS 7 |

Upon the installation, Kibana user interface is broken, because the wazuh-alerts- index is missing. We added the template as outlined here https://documentation.wazuh.com/4.0/user-manual/kibana-app/troubleshooting.html#no-template-found-for-the-selected-index-patternd:

```
curl https: //raw.githubusercontent.com/wazuh/wazuh/v4.0.4/extensions/elasticsearch/7.x/wazuh-template.json | curl -X PUT -k "https://localhost:9200/_template/wazuh" -H 'Content-Type: application/json' -d @-
```
This worked and the template was added successfully:

```
# curl -k https://localhost:9200/_cat/templates/wazuh
wazuh [wazuh-alerts-4.x-*, wazuh-archives-4.x-*] 0 1
```

However, the wazuh-alerts- index is not created:

```
# curl -k https://localhost:9200/_cat/indices?v
health status index                       uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   wazuh-monitoring-2021.02.13 ctqC1weSQwavyZnYOdj6NA   2   0          6            0     93.9kb         93.9kb
green  open   wazuh-statistics-2021.7w    ZJrXvV0qSPStoNo1VdLHPA   2   0         18            0     91.4kb         91.4kb
green  open   .kibana_2                   TMZopK4lTGe93Dhfa84o5Q   1   1          3            0     71.8kb         35.9kb
green  open   .kibana_1                   md4G2_v8RW-QC72cnIZd4w   1   1          1            0     11.7kb          5.8kb
green  open   .opendistro_security        jwMxXM4nRrO1ub7jBYZ6BA   1   2          9            0     96.8kb         48.7kb
green  open   security-auditlog-2021.02   zDqE4yTeS3yBtryjUSr7pA   1   1        360            0    639.6kb        325.2kb
green  open   .tasks                      g3GS-ThkTaqtbG5iGs-6nA   1   1          1            0     13.4kb          6.7kb
green  open   .kibana_3                   Oaj0Fw3JTniNHrmhw4S9bA   1   1          3            1     52.3kb         35.9kb
```

The documentation states that the wazuh-alerts- indices are created automatically:

> They are auto-generated and they store the Wazuh alerts. Filebeat will send data to Elasticsearch and will create an index per day.
(https://documentation.wazuh.com/4.0/user-manual/kibana-app/reference/elasticsearch.html#the-wazuh-alerts-indices)

Is there a workaround/fix for this until this is fixed and brought in line with the expected behavior as per documentation?

Any help is beneficial!
Thanks!

**Comment by hunter-gon** [comment]
any solution for this?

**Comment by muhyuddin** [comment]
Any solution yet ??

**Comment by Waseem-farooqui** [comment]
I tried this again, this has created the alert index.

`curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/4.2/extensions/elasticsearch/7.x/wazuh-template.json`
`chmod go+r /etc/filebeat/wazuh-template.json`

`systemctl restart filebeat`
