### ISSUE TITLE
Remove pipe character at the end of regexes

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#7505]
|Wazuh version|Component|
|---|---|
| 4.2-dev | Wazuh Regex |

## Description

After the change of behaviour added by #7495, some fields in the ruleset will automatically match any string if the final character is a pipe `|`, we should remove them from exisisting rules and decoders.

The following is a list of remaining rules and decoders that should be changed:
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0305-squid_decoders.xml#L46
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0090-dragon-nids_decoders.xml#L17-L24
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2123-L2130
https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2296-L2301

**Comment by JavierBejMen** [comment]
- [wazuh/ruleset/decoders/0305-squid_decoders.xml](https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0305-squid_decoders.xml#L46) it's ok, nothing to do.
- [wazuh/ruleset/decoders/0090-dragon-nids_decoders.xml](https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/decoders/0090-dragon-nids_decoders.xml#L17-L24) it's ok, nothing to do.
- [wazuh/ruleset/rules/0585-win-application_rules.xml](https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2123-L2130) to be removed.
- [wazuh/ruleset/rules/0585-win-application_rules.xml](https://github.com/wazuh/wazuh/blob/79906b5fcfc0c9618fbcdfc7ca64758568ec3743/ruleset/rules/0585-win-application_rules.xml#L2296-L2301) to be removed.

**Comment by JavierBejMen** [comment]
Branch:
[https://github.com/wazuh/wazuh/tree/7505-remove-pipe-character-end-decoders](https://github.com/wazuh/wazuh/tree/7505-remove-pipe-character-end-decoders)
