### ISSUE TITLE
Establish random scan_id on all syscollector tables.

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7527]
## Description
This issue aims to guarantee the conditions to be able to correctly set the scan_id value.

**Issue:**
Keep the scan_id processed in a static variable, and if I change, update the whole table (one time only).

**Solution**
In wazuhdb instance, everything that does not have "checksum" field populated is cleaned (it would be with the algorithm less than 4.2)

**Solution effect:**
Correct functioning vuln detector, based on its package search algorithm.

**Conditions to reproduce**
Manager 4.2
Agent: 4.2

Merge to branch dev-syscollector-tde

## DoD
- [ ] Modify agent code to send random scan_id.
- [ ] Modify manager code for update scan_id to the first synchro scan_id received.
- [ ] Modify unit tests.
- [ ] PR - CI PASS

**Comment by konangc87** [comment]
Close based on team session regarding vuln detector usage of scan_id. Not a bug.
