### ISSUE TITLE
Improve detections on latest public MITRE assessment

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#7557]
Carbanak + Fin7 emulation plan: https://github.com/center-for-threat-informed-defense/adversary_emulation_library

### Epic Scope

- Analyze Operation flow, priorize each scenario based on ATT&CK matrix coverage
- Replicate selected scenario topology 
  - Adapted for Wazuh detections, this means install and configure sysmon and any other tool we may need
  - Defining needed tools for detection may be part of this story
- Do first execution of Scenario 
   - Manually, to verify that environment configuration is ok 
   - Two options, execute complete killchain or do each step in an atomic fashion
   - Generate ATT&CK coverage, collect available telemetry
   - Based on the experience define next iteration 
 - One story per MITRE Technique - each should cover
   - Research detection possibilities
   - Technique simulation. 
      - Procedure provided by MITRE is the bare minimum for analysis 
      - Many techniques do have public samples that implement diverse procedures would be interesting to implement detections for thesewhen possible
   - Define tools for research, in windows environments main log source should be Sysmon, secondary sources may be ProcessHacker, APIMonitor, etc
   - Other sources of Threat intelligence are also valid (blog posts, analysis, etc)
   - Collect relevant logs for detection
   - If no relevant logs are generated, document which capabilities would be required
   - Write or improve required decoders/rule
   - Using logs collected during research, write rules and related code for the technique
   - Rule testing

Carbanak steps:
<table class="tableizer-table">
<thead><tr class="tableizer-firstrow"><th>Step</th><th>Substep</th><th>Kali</th><th>Win10</th><th>WindowsDC</th><th>CentOS</th><th>Analyzed</th><th>Notes</th></tr></thead><tbody>
 <tr><td rowspan="2">1</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td>&nbsp;<td>A requires MS Word installation</td></tr>
 <tr><td>A*</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">2</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">3</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">4</td><td>A</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="3">5</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>X</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>C</td><td>X</td><td>&nbsp;</td><td>X</td><td>X</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>6</td><td>A</td><td>X</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="3">7</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>C</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>8</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>This step only works if 7.C has been executed</td></tr>
 <tr><td>9</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">10</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>Yes</td><td>&nbsp;</td></tr>
</tbody></table>

**Comment by fabamatic** [comment]
Team decided to start with Carbanak scenario as it's easier to set up. Then do Fin7

**Comment by fabamatic** [comment]
This story covers the 10 steps of Carbanak emulation.
From the analysis done in [#8299 Carbanak Scenario Infrastructure Analysis](https://app.zenhub.com/workspace/o/wazuh/wazuh/issues/8299)  it turns out that all the steps are executable as an "atomic" test. 
The priority for execution was set to verify viability of infrastructure:

- Step 2.A: Has basic infrastructure requirements, only needs a Win10 endpoint and Kali + Wazuh stack
- Step 4.A: Ups complexity of infrastructure by adding a Windows DC to the basic Win10 + Kali + Wazuh
- Step 5.A: Infrastructure adds CentOS files server to the DC + Win10 + Kali + Wazuh

Ideally execution and related activities (rule writing and analysis) will be done for all the steps by different members of TI team.

**Comment by fabamatic** [comment]
Completed implementation of detection rules for all 10 Carbanak steps, a total of 62 new rules were added
