### ISSUE TITLE
[API] Return wazuh-remoted configured protocol as array of values

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#7579]
|Wazuh version|Component|
|---|---|
| Branch [1838-remoted-enhancement-support-tcp-udp](https://github.com/wazuh/wazuh/tree/1838-remoted-enhancement-support-tcp-udp)| API |

Hi team!

As part of Epic #1838, is desirable that the simultaneous configuration of TCP and UDP protocols for `wazuh-remoted` `secure` block is correctly returned as an array of values when querying manager's configuration via `GET /manager/configuration?section=remote`

## `UDP` and `TCP` simultaneously configured
* Manager's `secure` configuration
```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>udp,tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```
* Current output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": "udp,tcp",
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```
* Desired output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": ["udp","tcp"],
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```
## `UDP` configured
* Manager's `secure` configuration
```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>udp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```
* Current output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": "udp",
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```
* Desired output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": ["udp"],
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```
## `TCP` configured
* Manager's `secure` configuration
```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>tcp</protocol>
    <queue_size>131072</queue_size>
  </remote>
```
* Current output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": "tcp",
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```
* Desired output
```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": ["TCP"],
            "queue_size": "131072"
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Configuration was successfully read",
  "error": 0
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Nico

**Comment by juliancnn** [comment]
Hi team!,

For the next remote configuration block:
```xml
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <protocol>TCP, udp , test,</protocol>
    <queue_size>131072</queue_size>
  </remote>
```

The following output is produced:
```json
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": [
              "TCP",
              " udp ",
              " test",
              ""
            ],
            "queue_size": "131072"
          },
```

in the protocol array, it is desirable:
- skip empty strings
- remove whitespace before and after the elements.
- show the elements of this array in uppercase letters

i.e.

```json
        "remote": [
          {
            "connection": "secure",
            "port": "1514",
            "protocol": [
              "TCP",
              "UDP",
              "TEST",
            ],
            "queue_size": "131072"
          },
```
