### ISSUE TITLE
Verify WPK with Wazuh CA by default

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#758]
If the configuration declares no certificate for WPK verification, it is implicitly disabled.

An Active response configuration without certificate should enable the Wazuh Root CA by default. We should also add an option to disable WPK verification explicitly.

## Proposed configuration

```xml
<active-response>
  <disabled>no</disabled>
  <ca_store>wpk_root.pem</ca_store>
  <ca_verification>yes<ca_verification>
</active-response>
```

**Comment by vikman90** [comment]
If no configuration available and the file file _wpk_root.pem_ is missing (the file was likely removed):
```
2018/06/11 13:30:58 ossec-execd: INFO: No CA store defined. Using Wazuh default CA (/var/ossec/etc/wpk_root.pem)
2018/06/11 13:32:22 ossec-execd: ERROR: (1117): Could not retrieve informations of file '/var/ossec/etc/wpk_root.pem' due to [(2)-(No such file or directory)].
2018/06/11 13:32:22 ossec-execd: ERROR: Certificate couldn't be verified by CA: unable to get local issuer certificate (20)
2018/06/11 13:32:22 ossec-execd: ERROR: Error verifying WPK certificate.
2018/06/11 13:32:22 ossec-execd: ERROR: At unsign: Couldn't unsign package file '/var/ossec//var/incoming/osquery-3.2.4-1.linux.x86_64_rpm.wpk'
```

**Comment by vikman90** [comment]
Commit: https://github.com/wazuh/wazuh/commit/f6ccb67110e442161ceec5b5aba8f27928a98718
Branch: [fix-wpk-default-cert](https://github.com/wazuh/wazuh/tree/fix-wpk-default-cert).

This message:
```
2018/06/11 13:30:58 ossec-execd: INFO: No CA store defined. Using Wazuh default CA (/var/ossec/etc/wpk_root.pem)
```

appears during the service starting. We should delay it until the applications turns into daemon mode.

**Comment by snaow** [comment]
IMO, the INFO message should include the setting not defined (value/setting missing).
That way Users will be able to look for that setting in Wazuh documentation and get a better explanation.

Example log: 

```
2018/06/11 13:30:58 ossec-execd: INFO: No CA store defined (<ca_store>). Using Wazuh default CA (/var/ossec/etc/wpk_root.pem)
```
