### ISSUE TITLE
ossec-analysisd reporting dbsync and bad response errors.

### ISSUE THREAD

**Issue by hanschl** [wazuh/wazuh#7580]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.13.2|ossec-analysisd|Manager|Packages|CentOS 8.3.2011|

- Linux Agents are running version 4.0.0
- Windows Agents are running version 4.1.0

Since 16th February we are getting the following erros:

> 2021/02/22 12:16:22 ossec-analysisd: ERROR: dbsync: Bad response from database: Invalid DB query syntax, near 'fim_registry'
> 2021/02/22 12:16:23 ossec-analysisd: ERROR: dbsync: Bad response from database: Invalid DB query syntax, near 'fim_file'
> 2021/02/22 12:27:17 ossec-analysisd: ERROR: FIM decoder: Bad response from database: Cannot save Syscheck

I'm not sure if it is a Bug or what I have to do to fix this problem. We didn't update the Manager on that day the last time we installed OS Updates was on 10th Februrary. We also didn't change anything in the ossec config or in other configs of the system itself.

**Comment by antoniomanuelfr** [comment]
Hi @hanschl 

In version 4.1 of Wazuh there was a breaking change in the Windows agents: We have improved the way that FIM monitors the windows registry keys (this is the issue in case you want to check it https://github.com/wazuh/wazuh/issues/5576). In this development, we had to change the structure of the FIM database. Probably, that is going to be the problem that you are experiencing. 

I'm going to create a test environment to check it anyway.

If you don't care about the registry monitoring or don't want to upgrade the manager, the safest thing is to downgrade the Windows agent until you feel like you need to upgrade to the latest version.

This is the link to the changelog of 4.1 https://github.com/wazuh/wazuh/blob/v4.1.0/CHANGELOG.md if you want to check the new features that have been added in this version.

Kind regards.

**Comment by hanschl** [comment]
Hi @antoniomanuelfr 

we have updated to version 4.1 and the errors are gone. Thanks for the help.

Best Regards

**Comment by antoniomanuelfr** [comment]
Hi again.
I'm glad that it was helpful. Let me close this issue. 

Don't hesitate to contact us again if you have any doubts.
Kind regards.
