### ISSUE TITLE
MITRE automation - Feature Request

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#7582]
**Describe the solution you'd like**
Hello,
it would be cool if Wazuh has automated scans for high pattern MITRE match, based on internal/external intelligence feeds.
Alienvault's OTX have a lot of events with MITRE techniques. I've done it for my self with alerting for above 60/70%.

Example: 
Dharma Ransomware has T1133, T1078,  T1064, T1486, T1083, T1135.
If Wazuh sees  T1064, T1486, T1083, T1135 for X period of time it will results in alert. 

Or something like this.

**Comment by Nekaze** [comment]
Hello! We are currently working on improving MITRE capabilities of Wazuh. These are planned for future Wazuh releases, so keep up with out latest news to know about these changes!

These improvements include:

- Adding MITRE techniques, subtechniques and tactic IDs to Wazuh rules that currently dont have any MITRE associated to it
- Improving the MITRE info on the rules that already have it

This new info will enable the kind of alerts you suggested. Does this help?

Kind regards
Nicolas Koziuk

**Comment by Nekaze** [comment]
Hello again, just wondering if my previous answer fully addresses your feature request

Kind regards!

**Comment by a108a108** [comment]
Hello @Nekaze,

thank your response!

These improvements will definitely help, however my overall idea was that automation to be included out of the box in Wazuh instead of me writing scripts to make it happen.

In general I think it would be good if Wazuh can make scans (similar to the vulnerability scanner as an idea) on hashes and MITRE techniques based on threat intel, maybe some kind of integration with MISP/OTX etc.. or even internally stored feeds.

I realize that this wont happened just because I ask... I am putting it out there with hope that there will be a demand from other users :D.

Best regards!

**Comment by Nekaze** [comment]
Hey @a108a108, thanks for your feedback.

We always try to support this kind of suggestions to be included out of the box. We agree that having this kind of automations is great for Wazuh, and as I mentioned before, we´re actively working on improving our integration with MITRE, so we hope we can provide some great news soon. Stay tuned!

Best regards
Nicolas

**Comment by Nekaze** [comment]
@a108a108 I am closing this since there is no more specific action required from us at the moment.

Please reach out should you this need to be reopened or if you need anything else

Kind regards
Nicolas
