### ISSUE TITLE
Investigate and define the most appropriate way to replicate as realistically as possible a very big Wazuh clustered environment

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7606]
Hello team,

We should investigate and define the most appropriate way to replicate as realistically as possible a very big Wazuh clustered environment.

As part of this issue we should determine the platform to be used for the deployment and how to simulate thousand of agents without using real agents (too costly to deploy). 

Any problems and constraints found during the investigation should be clearly defined and addressed.

Regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
## Issue update

### Cluster structure (max. size)

```
wazuh-cluster
|-- master
|   `-- 10000_agents
|-- worker1
|   `-- 10000_agents
|-- worker2
|   `-- 10000_agents
|-- worker3
|   `-- 10000_agents
|-- worker4
|   `-- 10000_agents
|-- worker5
|   `-- 10000_agents
|-- worker6
|   `-- 10000_agents
|-- worker7
|   `-- 10000_agents
|-- worker8
|   `-- 10000_agents
`-- worker9
    `-- 10000_agents
```

That would be a total of 10 wazuh managers and 100000 wazuh agents.


### Considerations

- `wazuh-db` and `wazuh-clusterd` should be on `DEBUG2` for at least the master node and one worker node (ideally for every node in the cluster, but there could be too much flood).
- Agents will be simulated. We need to register them with big labels to increase the number of chunks the cluster will have to synchronize.
- We need to create a lot of agent groups and add an even number of agents to each one.
- We need a script running in the master node making distributed API requests to increase the cluster load.
- We need a script running in every cluster node changing the `agent-info` of each agent to trigger the agent-info synchronization.


### Details

As we believe the cluster is the responsible for the performance issues, we will try to stress it as much as possible. In previous tests we could not pass over 5 chunks per synchronization and we did not see any major perfomance issue. That is why we will increment the number of cluster nodes and add big labels to each agent, hoping that the number of chunks will increase and thus the cluster performance will drop.

Every worker node adds requests to the same queue and this queue has no limit. As the API requests queue, timeouts are considered once the petition is being handled. This does not count the time the petition has been in the queue. This means that if the number of requests in the queue increases faster than the number of requests the cluster can handle, the cluster will slow down without returning any visible error (unless the `send_request` method timeouts).

Regards,
Víctor Fernández
