### ISSUE TITLE
Fix SCA rules where running stat commands

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7624]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.1.0 | SCA policies | N/A | N/A | Linux |

As @jdmedeiros reports at [this comment](https://github.com/wazuh/wazuh/pull/7575#issuecomment-785173266). All the stat commands called in SCA rules should include the `-L` flag to follow symbolic links.

Otherwise, those commands could lead to false results when checking permissions since they check the stats of the symbolic link instead of the original file.

**Comment by mesanchez** [comment]
Fixed rules includidng "stat" command on the following files:

cis_centos6_linux.yml
cis_centos7_linux.yml
cis_centos8_linux.yml
cis_debian7.yml
cis_debian8.yml
cis_debian9.yml
cis_debian10.yml
cis_nginx_1.yml
cis_rhel6_linux.yml
cis_rhel7_linux.yml
cis_rhel8_linux.yml
cis_sles12_linux.yml
cis_sles15_linux.yml
cis_solaris11.yml
