### ISSUE TITLE
Active-response not executed on the agent.

### ISSUE THREAD

**Issue by marinovgit** [wazuh/wazuh#7625]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| wazuh-agent-4.1.0-1.x86_64 | active response | Manager/Agent | Packages/Sources | centos7 |

The active response on the agent stopped working after the upgrade from 4.0 to 4.1.
If the active response is set `<location>server</location>` the active response script is executed on the server/manager with no issues.
If the active response is set `<location>local</location>` nothing happens on the agent. I tried with defined-agent and agent_id but the same.
The script, permission, etc are the same on the agent and on the server. There is no whitelist IP/Hosts. The email alert for this rule is sent 100001 but the active response is not executed on the agent. 

I have the exact same config on different enviroment but with wazuh-manager-4.0.4-1.x86_64 and there everything is working as expected.

 ```
        <command>
                <name>test</name>
                <executable>test.sh</executable>
        </command>
        <active-response>
                <disabled>no</disabled>
                <command>test</command>
                <location>local</location>
                <rules_id>100001</rules_id>
        </active-response>
```

```
<group name="authentication_success">
        <!-- If successful auth notify admin -->
        <rule id="100001" level="13">
                <if_sid>5700</if_sid>
                <match>^Accepted|authenticated\.$</match>
                <description>SSHD authentication success. Pushover sent to the Admin</description>
                <group>authentication_success,</group>
        </rule>
</group>

```
```
[Manager]# ./ossec-control status
wazuh-clusterd not running...
wazuh-modulesd is running...
ossec-monitord is running...
ossec-logcollector is running...
ossec-remoted is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild is running...
ossec-execd is running...
wazuh-db is running...
ossec-authd not running...
ossec-agentlessd not running...
ossec-integratord not running...
ossec-dbd not running...
ossec-csyslogd not running...
wazuh-apid is running...

```

```
[Agent /var/ossec/bin]# ./ossec-control status
wazuh-modulesd is running...
ossec-logcollector is running...
ossec-syscheckd is running...
ossec-agentd is running...
ossec-execd is running...
```
```
[Agent /var/ossec/bin]# cat /var/ossec/etc/shared/ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
test0 - test.sh - 0

```
If I run this on the Manager:
```
[Manager bin]# ./agent_control -b 13.13.13.13 -f test0 -u 005
Wazuh agent_control: Running active response 'test0' on: 005
```
It is OK on the Agent, the script is executed:
```
==> /var/ossec/logs/ossec.log <==
2021/02/25 10:08:05 ossec-execd[132687] execd.c:361 at ExecdStart(): DEBUG: Received message: 'test0 - 13.13.13.13 (from_the_server) (no_rule_id)'
2021/02/25 10:08:05 ossec-execd[132687] execd.c:583 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/test.sh add'

==> /var/ossec/logs/active-responses.log <==
Thu Feb 25 10:08:05 UTC 2021 /var/ossec/active-response/bin/test.sh add - 13.13.13.13 (from_the_server) (no_rule_id)   

```

Best regards

**Comment by vikman90** [comment]
Hi @marinovgit,

Thank you for this descriptive issue. Ain't able to reproduce this issue. I'm using this testing script (`test.sh`):
```sh
#! /bin/bash
echo `date` $@ >> /var/ossec/logs/active-responses.log
```

I also modified rule 100001 for testing convenience:
```xml
<group name="authentication_success">
  <!-- If successful auth notify admin -->
  <rule id="100001" level="13">
    <if_sid>5501</if_sid>
    <description>SSHD authentication success. Pushover sent to the Admin</description>
    <group>authentication_success,</group>
  </rule>
</group>
```

Please note that your group configuration produces alerts like this:
```
** Alert 1614256278.526299: mail  - authentication_successauthentication_success,
```

The group set is the concatenation of `<group name="">` and `<rule><group>`. `<group name>` is missing a trailing comma, and `<group>` is a duplicate of the former.

However, AR is working in both 4.0.4 and 4.1.0. Sure the alert is being produced as you confirm the manager sends it via email. But I don't understand the last part of your comment. Calling `./agent_control` seems to work. Do you mean that it's working in 4.0.4 but not in 4.1.0, or that `agent_control` works in 4.1.0 while alerts don't?

On the other hand, in order to narrow down the cause of this problem, I suggest you enable debug-2 level messages in Remoted, which should confirm that it's sending an AR request to the agent:
```sh
echo remoted.debug=2 >> /var/ossec/etc/local_internal_options.conf
systemctl restart wazuh-manager
```

When the manager sends an AR request to the agent (either triggered by an alert or manually with `agent_control`), you should find a couple of logs like this one:

Command:
```sh
./agent_control -b 13.13.13.13 -f test0 -u 001
```

Log:
```
2021/02/25 13:48:56 ossec-remoted[37593] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (msg_to_agent) [] NNS 001 test0 - 13.13.13.13 (from_the_server) (no_rule_id)
2021/02/25 13:48:56 ossec-remoted[37593] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd test0 - 13.13.13.13 (from_the_server) (no_rule_id)
```

That will help us know if the problem is on producing an AR or on sending it.

Thank you again.
Best regards.

**Comment by marinovgit** [comment]
Hello, thank you for the hints.

First, I noticed these errors when I restarted the manager if they mean something:
```
2021/02/25 13:08:02 ossec-analysisd: ERROR: (1210): Queue '/queue/alerts/ar' not accessible: 'Connection refused'
2021/02/25 13:08:02 ossec-analysisd: ERROR: (1301): Unable to connect to active response queue.
2021/02/25 13:08:02 ossec-analysisd: INFO: Connected to '/queue/alerts/execq' (exec queue)

```

Debug is enabled and when I manually execute this on the manager:

`./agent_control -b 13.13.13.13 -f test0 -u 005`

This is from the manager:
```
2021/02/25 13:10:45 ossec-remoted[10029] ar-forward.c:44 at AR_Forward(): DEBUG: Active response request received: (msg_to_agent) [] NNS 005 test0 - 13.13.13.13 (from_the_server) (no_rule_id)
2021/02/25 13:10:45 ossec-remoted[10029] ar-forward.c:119 at AR_Forward(): DEBUG: Active response sent: #!-execd test0 - 13.13.13.13 (from_the_server) (no_rule_id)
```

This is from the agent:
```
==> /var/ossec/logs/ossec.log <==
2021/02/25 13:10:45 ossec-execd[145843] execd.c:361 at ExecdStart(): DEBUG: Received message: 'test0 - 13.13.13.13 (from_the_server) (no_rule_id)'
2021/02/25 13:10:45 ossec-execd[145843] exec.c:102 at ReadExecConfig(): INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
2021/02/25 13:10:45 ossec-execd[145843] execd.c:583 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/test.sh add'

==> /var/ossec/logs/active-responses.log <==
Thu Feb 25 13:10:45 UTC 2021 add - 13.13.13.13 (from_the_server) (no_rule_id)
```

So far so good, everything is working fine.

But when I manually call the rule (I logged in to the agent server) the rule is hit (I received the email) but there is nothing in the log, neither on the manager nor on the agent.

Another thing, when I login into the manager (ssh) everything is fine the rule is hit, the mail is sent and the active-response is working. This is the log:
```
2021/02/25 13:25:19 ossec-execd[9969] execd.c:361 at ExecdStart(): DEBUG: Received message: 'test0 - - 1614259519.36183761 100001 /var/log/secure - -'
2021/02/25 13:25:19 ossec-execd[9969] exec.c:102 at ReadExecConfig(): INFO: Active response command not present: '/var/ossec/active-response/bin/restart-ossec.cmd'. Not using it on this system.
2021/02/25 13:25:19 ossec-execd[9969] execd.c:583 at ExecdStart(): DEBUG: Executing command '/var/ossec/active-response/bin/test.sh add'
```


The manager does not send the command to the agent.

Best regards

**Comment by vikman90** [comment]
Hi @marinovgit,

That is a good clue. The AR component seems to work, but Analysisd (the daemon that matches logs with rules and produces alerts) cannot deliver an AR request.

This is a key log:
> 2021/02/25 13:08:02 ossec-analysisd: ERROR: (1210): Queue '/queue/alerts/ar' not accessible: 'Connection refused'
> 2021/02/25 13:08:02 ossec-analysisd: ERROR: (1301): Unable to connect to active response queue.

Analysisd must reach Remoted through the queue `alerts/ar` to send AR requests to managers. On the other hand, for local ARs (in the manager), Analysisd calls `alerts/execq`.

It is clear that the problem persists despite restarting the manager. First, please check the queue files permissions:
```
# ls -l /var/ossec/queue/alerts
srw-rw---- 1 ossecr ossec 0 Feb 25 13:48 ar
srw-rw---- 1 root   ossec 0 Feb 25 13:29 cfgaq
srw-rw---- 1 ossecr ossec 0 Feb 25 13:48 cfgarq
srw-rw---- 1 root   ossec 0 Feb 25 13:29 execq
```

If any of them is missing or has incorrect permissions, stop the manager, delete them and start the manager back.

I wonder if this may be caused to a timing issue (Analysisd requires Execd to be up upon startup). Try out this:
```sh
# Start the manager
systemctl start wazuh-manager

# Restart Analysisd only
kill $(pidof ossec-analysisd)
/var/ossec/bin/ossec-analysisd
```

Then, try to login into the agent to produce an alert and send the AR request. If that works, we may need to fix this issue in the code.

Best regards.

**Comment by marinovgit** [comment]
Goood we are good :)
These were the files before:
[Manager alerts]# ll
```
total 0
srw-rw---- 1 ossecr ossec 0 Feb 25 13:39 ar
srw-rw---- 1 root   ossec 0 Nov 20 07:11 cfgaq
srw-rw---- 1 ossecr ossec 0 Feb 25 13:39 cfgarq
srw-rw---- 1 root   ossec 0 Feb 25 13:38 execq
```

I stopped the manager and delete all of them. When I start the manager the files were like this and the problem was still there.
```
[Manager ~]# ls -l /var/ossec/queue/alerts/
total 0
srw-rw---- 1 ossecr ossec 0 Feb 25 15:16 ar
srw-rw---- 1 ossecr ossec 0 Feb 25 15:16 cfgarq
srw-rw---- 1 root   ossec 0 Feb 25 15:16 execq
```

Then I kill ossec-analysisd and start it again as per your advice and voilà everything is working.

If I stop and start the manager the problem is back:
```
2021/02/25 15:29:29 ossec-analysisd: ERROR: (1210): Queue '/queue/alerts/ar' not accessible: 'Connection refused'
2021/02/25 15:29:29 ossec-analysisd: ERROR: (1301): Unable to connect to active response queue.
```
And it is fixed if I kill and start ossec-analysisd.

Best regards

**Comment by vikman90** [comment]
@marinovgit thank you for this feedback!

So we can confirm that the problem is here: [analysisd.c:880-895](https://github.com/wazuh/wazuh/blob/b38a93e8a64ba90e63f1de9c6578bc76bda69926/src/analysisd/analysisd.c#L880-L895). Analysisd tries to connect to Remoted on startup. If Remoted is not ready at that moment, Analysisd disables AR deliveries and does not try to connect again.

### Possible fix

Like other components already do, if Analysisd fails to connect to Remoted, try again after a while.

The information you provided has been very useful for us to find the cause of the problem. Let me mark this issue as a bug, we will fix it as soon as possible.

Thank you again!
Best regards.

**Comment by marinovgit** [comment]
Great thank you :)

If the manager is left in this condition (killed ossec-analysisd and started again manually) will be working without any other issues right?

**Comment by vikman90** [comment]
Hi! Yes, currently other components (Syscheck, all modules, Logcollector and Remoted) should be able to re-connect to Analysisd in case of error. That is just what we need to implement in Analysisd.

**Comment by marinovgit** [comment]
Hello, I want to add some things about this. Not sure they are related to this issue.
After I kill and start ossec-analysisd there are some error messages in the log.

These I think are OK:
```
2021/03/02 09:06:43 ossec-analysisd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2021/03/02 09:06:43 ossec-remoted: ERROR: socketerr (not available).
2021/03/02 09:06:43 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'
2021/03/02 09:06:44 ossec-remoted: ERROR: socketerr (not available).
2021/03/02 09:06:44 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'
2021/03/02 09:06:44 ossec-remoted: ERROR: socketerr (not available).
2021/03/02 09:06:44 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'
2021/03/02 09:06:44 ossec-remoted: ERROR: socketerr (not available).
2021/03/02 09:06:44 ossec-remoted: ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'

.....
2021/03/02 09:07:08 ossec-remoted: INFO: Successfully reconnected to '/queue/ossec/queue'
2021/03/02 09:07:09 ossec-remoted: INFO: Successfully reconnected to '/queue/ossec/queue'
2021/03/02 09:07:09 ossec-remoted: INFO: Successfully reconnected to '/queue/ossec/queue'
2021/03/02 09:07:09 ossec-remoted: INFO: Successfully reconnected to '/queue/ossec/queue'

```


```
2021/03/02 09:06:52 ossec-logcollector: ERROR: socketerr (not available).
2021/03/02 09:06:52 ossec-logcollector: ERROR: Unable to send message to '/var/ossec/queue/ossec/queue' (ossec-analysisd might be down). Attempting to reconnect.

....
2021/03/02 09:07:02 ossec-logcollector: INFO: Successfully reconnected to '/var/ossec/queue/ossec/queue'
```

These are that I am not sure about:
```
2021/03/02 09:13:03 ossec-syscheckd: ERROR: socketerr (not available).
2021/03/02 09:13:03 ossec-syscheckd: ERROR: (1224): Error sending message to queue.

```

and these (I omitted some of the lines because they are many):
```
2021/03/02 09:57:40 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Connection refused)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Socket operation on non-socket)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Socket operation on non-socket)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Socket operation on non-socket)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Socket operation on non-socket)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:40 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Socket operation on non-socket)
2021/03/02 09:57:40 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:41 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:41 wazuh-modulesd:vulnerability-detector: ERROR: (5503): SQL error: 'disk I/O error'
2021/03/02 09:57:41 wazuh-modulesd:vulnerability-detector: ERROR: (5562): The integrity of the database is invalid, so Vulnerability Detector will stop working.
2021/03/02 09:57:41 wazuh-modulesd: ERROR: socketerr (not available).
2021/03/02 09:57:41 wazuh-modulesd: ERROR: At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
2021/03/02 09:57:41 wazuh-db: WARNING: at run_worker(): received string size is bigger than 65536 bytes
2021/03/02 09:57:42 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

Best regards

**Comment by vikman90** [comment]
Hi,

Those logs indeed report that the connection between Analysisd and the rest of the components has been broken. This is the code at Syscheck: [run_check.c](https://github.com/wazuh/wazuh/blob/6c9e3fdcc0324e48620243faf7c9217b8d480a3e/src/syscheckd/run_check.c#L68-L71).

When the connection gets broken, the components try to reconnect immediately (calling `StartMQ()`). This behavior was unified by PR #4510.

Thanks and regards.
