### ISSUE TITLE
Rename users and group according to the Wazuh standard

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7646]
### Description

The goal of this issue is to replace legacy users and group in Unix Wazuh installations as follows:

- Users `ossec` (standard), `ossecr` (Remote daemon) and `ossecm` (Mail daemon), will be replaced by the user `wazuh`
- Group `ossec` will be replaced by the group `wazuh`

This replacement leads to the following statements:

- New user and group should have the same characteristics as the legacy ones in terms of privileges
- At clean installations the user and group are created and assigned the same way the legacy ones were
- On upgrades, existing files and directories owned by the legacy users/group should be reassigned
- On upgrades, legacy users and group should be removed
- External components from the core product referencing the legacy users/group must be adapted to the new ones
- Documentation should reflect these changes when talking about the Wazuh users and group

**Comment by chemamartinez** [comment]
Devel branch: https://github.com/wazuh/wazuh/tree/7646-rename-users-group

**Comment by chemamartinez** [comment]
Apart from issues included in this EPIC, we have to add the following list of issues that cannot be added by the standard process because of the repositories they belong to:

- https://github.com/wazuh/wazuh-ansible/issues/546
- https://github.com/wazuh/wazuh-automation/issues/459
- https://github.com/wazuh/wazuh-cloudformation/issues/84
- https://github.com/wazuh/wazuh-chef/issues/132
- https://github.com/wazuh/wazuh-docker/issues/448
- https://github.com/wazuh/wazuh-puppet/issues/352

Regards.

**Comment by kravietz** [comment]
The `wazuh` user is not initialised anywhere in the Ansible roles which breaks them:
```
TASK [wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-manager : Installing the local_rules.xml (default local_rules.xml)] ***********************************************************************************
Wednesday 21 July 2021  13:27:32 +0100 (0:00:00.168)       0:02:31.283 ******** 
fatal: [xxx]: FAILED! => {"changed": false, "checksum": "f70e436001d300228325e05e539ed2de41b787fd", "gid": 112, "group": "ossec", "mode": "0640", "msg": "chown failed: failed to look up user wazuh", "owner": "ossec", "path": "/var/ossec/etc/rules/local_rules.xml", "size": 501, "state": "file", "uid": 108}
```

**Comment by chemamartinez** [comment]
Hi @kravietz,

This development has been released yet. It is planned to be available for Wazuh v4.3.

Therefore, it is possible that some repositories such as Ansible are pending to adapt to this change.

Sorry for the inconvenience.

Regards,
Chema.

**Comment by kravietz** [comment]
@chemamartinez But this new `owner: wazuh` has been already merged into `master` branch in `wazuh-ansible`, so any user of the Ansible playbooks will now be facing it.

**Comment by chemamartinez** [comment]
I understand, this is why the master branch of the Ansible repository is up to date with this one. If you are running an older version, such as Wazuh v4.1.5, you have to move to the corresponding branch or tag in the Ansible repository as well.

![image](https://user-images.githubusercontent.com/29475387/126661330-fb745805-dda0-4e59-9de2-ce70b5e11349.png)
