### ISSUE TITLE
vuln_cve clear command should be used only on full Vulnerability Detector scans

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#7650]
### Description

As part of the [exploratory testing](https://github.com/wazuh/wazuh/issues/7519) done for the implementation of the epic in which we are adding the capability to know which CVEs affect each agent, we found an issue in the way the vuln_cve table is periodically updated.

The vuln_cve table is now being cleared previous to each vulnerability detector scan. But it doesn't contemplate the possibility of being a partial scan. 
In this way, if a partial scan occurs, the vuln_cve table is cleared, but only the modified packages are analyzed and re-inserted in the table. This leads to missing the vulnerabilities of packages that aren't scanned during the partial scan.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/7652 was merged.
