### ISSUE TITLE
Template for ruleset issues

### ISSUE THREAD

**Issue by juanrricci** [wazuh/wazuh#7656]
Hello team,

The aim of this issue is to add a template for creating ruleset issues on the `wazuh/wazuh` GitHub repository.

The template must include the manual tests and checks that must be verified when adding changes in the ruleset. 

Currently, we use the Core template for our PRs that includes many tests that are not relevant for changes on the ruleset, and other required tests are omitted in the mentioned template.

**Comment by juanrricci** [comment]
### Preliminar version of the template for ruleset issues
---
name: Ruleset issue 
about: Report a bug or make a feature request.
title: ''
labels: 'threatintel,threatintel/rules'
assignees: ''

---

|Wazuh version|
|---|
| X.Y.Z-rev |



## Description



## Configuration options



## Logs/Alerts example



## Tests


- [ ] Added .ini test file for covering related rules
- [ ] Executed unit tests (runtests.py) for checking ruleset integrity
- [ ] Verified mitre.db integrity
- [ ] Verified no errors/warnings related in ossec.log

**Comment by 72nomada** [comment]
Ruleset required action

|Wazuh version| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | rules/decoders/sca | Add new/Error/Improve |

## Description



## Logs/Alerts example



## Log format reference 



## Tests

- [ ] Added .ini test file for covering related rules
- [ ] Executed unit tests (runtests.py) for checking ruleset integrity
- [ ] Verified mitre.db integrity
- [ ] Verified compliance mapping 
- [ ] Verified no errors/warnings related in ossec.log
- [ ] Kibana shows alerts

**Comment by JavierBejMen** [comment]
# Branch
Branch to track changes: https://github.com/wazuh/wazuh/tree/7656_github_ruleset_issue_template

**Comment by JavierBejMen** [comment]
# Update
Issue reopened to further improve the current template, the proposal is to split the ruleset template into one template for SCAs requests, rules/decoders requests and ruleset PRs.

So far the ruleset/decoder request template would be:
```md
---
name: Ruleset issue
about: Report a bug or make a feature request.
title: ''
labels: ''
assignees: ''
---
|Wazuh version| Component | Action type |
|---| --- | --- |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |
<!--
This template reflects sections that must be included in new issues
Contributions from the community are really appreciated. If this is the case, please add the
"contribution" to properly track the issue.
-->
## Description
<!-- Add a detailed description of your issue -->
<!-- Detail the reason that motivates this proposed change on the ruleset -->
### Service
<!-- Add a description of the service you are targeting with the ruleset -->
<!-- Add any URL or doc related to vendor and/or service -->
## Error/Improve
### Current results
<!--  Include current results -->
### Expected results
<!--  Include expected results -->
## Resources
### Log source / integration
<!-- Especify where the logs come from and/or if integration is required-->
### Log reference
<!-- Add any URL or doc related to log format -->
<!-- Add any URL or doc related to log events -->
### Log examples
<!-- Add any logs examples available -->
### Threats and compliance
<!-- List specific threats and compliance to be covered -->
<!-- Include any related URL or doc -->
```

**Comment by JavierBejMen** [comment]
# Update
Added PR tests checks for rules and decoders changes
```md
<!-- Ruleset required checks, rules/decoder -->
- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors
```
SCAs templates needs to be defined
