### ISSUE TITLE
OpenSCAP module should not be compiled for Windows agents

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#769]
When we set the configuration of the OpenSCAP module for a Windows agent, instead of showing a descriptive error telling that is not available for Windows, it is tried to be executed showing the following logs:

```
2018/06/11 01:16:08 ossec-agent: ERROR: (1114): Error during select()-call due to [(0)-(No error)].
2018/06/11 01:16:08 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows 10 Home [Ver: 10.0.16299] - Wazuh v3.3.0).
2018/06/11 01:16:08 wazuh-modulesd:oscap: INFO: Module started.
2018/06/11 01:16:08 wazuh-modulesd:oscap: INFO: Starting evaluation.
2018/06/11 01:16:08 ossec-agent: ERROR: CreateProcess(): 2
2018/06/11 01:16:08 wazuh-modulesd:oscap: ERROR: Internal calling. Exiting...
```

I think that module should not be compiled for Windows agents, and show a descriptive error if is found in the configuration.

**Comment by bah07** [comment]
Done in [#777](https://github.com/wazuh/wazuh/pull/777)
