### ISSUE TITLE
Analyze MITRE DB size with and without deprecated entries

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#7696]
The idea of this issue is to analyze if the MITRE DB size increases a lot when inserting the deprecated entries into it or if its size remains almost the same.

This will allow us to take some conclusions and get to know if it is necessary to keep these entries in the DB or if it is better to discard them.

**Comment by javabalm** [comment]
The Mitre db sizes with and without deprecated rows are:

```
With deprecated rows: 7.0 MB (6995968 bytes)
No deprecated rows: 7.0 MB (6991872 bytes)
```

In conclusion, there are almost no differences between the two cases.
