### ISSUE TITLE
Make vuln_cve table get cleared on Vulnerability Detector start

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#7698]
### Description

As part of the issue https://github.com/wazuh/wazuh/issues/7519 we were doing some exploratory testing for the epic https://github.com/wazuh/wazuh/issues/7479. In this epic we are adding the capability to know which CVEs affect each agent. This information is saved in a new table called `vuln_cves` in the agents' databases.

To guarantee this table doesn't contain outdated data if Vulnerability Detector is disabled, this table should be cleared on Vulnerability Detector init, only when vuldet is disabled.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/7699 was merged.
