### ISSUE TITLE
Remove 'ossec' word from framework

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#7700]
|Wazuh version|Component|
|---|---|
| master | Framework/API |

## Description

Hi team!

In the last months, multiples changes have been performed in order to rename services (#6741), ruleset (https://github.com/wazuh/wazuh-ruleset/issues/784), tools (#6766), etc. from `ossec` to `wazuh`. 

Now, the same must be done with all those places within the framework and API where the word `ossec` is used (comments, functions and methods, variables, etc). 

Unless otherwise stated, the group name and user will not be changed at this time: 
https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/framework/wazuh/core/common.py#L196-L201

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by mcarmona99** [comment]
### Issue status

I have reopened the issue as there were missing `ossec` words that need to be changed to `wazuh`. I will open a new PR.
