### ISSUE TITLE
Replace OSSEC users and groups in Makefile, install scripts and source code

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7701]
### Description

This issue is part of #7646. It covers the replacement of the users and groups for the following files:

- `Makefile`: where are defined to modify MACROS in the source code when building https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/src/Makefile#L46
- Install scripts: used to install Wazuh files with the correct ownership https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/src/init/inst-functions.sh#L679
- Source code: where users and groups are defined to run the binaries https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/src/headers/defs.h#L94

### Requirements

- This issue covers the replacement of the users and group definitions. Not the creation of them when installing.
- Binaries running as root should keep that behavior, only binaries that run as `ossec`, `ossecr` or `ossecm` have to run as `wazuh` now.

**Comment by alromeros** [comment]
Devel branch: https://github.com/wazuh/wazuh/tree/7701-rename-users-group-in-makefile-code

**Comment by chemamartinez** [comment]
Merged #7710
