### ISSUE TITLE
The ipv6 option accepts any value

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#7702]
|Wazuh version|Component|Install type|Install method |
|---|---|---|---|
| 4.2.0 | Wazuh Manager |  Packages | CentOS 8 |

## Description

[ipv6](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html?#ipv6) accepts any invalid value.

![remote_ipv6](https://user-images.githubusercontent.com/11089305/109629975-b0416380-7b44-11eb-8881-b577052a950e.png)

This value is also returned for the API when `GET /manager/configuration`  request is made

![remote_ipv6_api](https://user-images.githubusercontent.com/11089305/109630401-28a82480-7b45-11eb-97f3-3aa7dfd05ca2.png)

**Comment by juliancnn** [comment]
Hi @Rebits,

I add a little more information about the bug.
The endpoint ` /manager/configuration` returns the XML static config.
You can view the loaded remoted configuration with the enpoint `GET /manager/configuration/request/remote`.

```json
{
  "data": {
    "affected_items": [
      {
        "remote": [
          {
            "connection": "secure",
            "ipv6": "no",
            "protocol": [
              "TCP"
            ],
            "port": "1514",
            "queue_size": "131072"
          },
          {
            "connection": "syslog",
            "ipv6": "no",
            "protocol": [
              "UDP"
            ],
            "port": "514",
            "allowed-ips": [
              "any",
              "any"
            ]
          },
          {
            "connection": "syslog",
            "ipv6": "no",
            "protocol": [
              "TCP"
            ],
            "port": "600",
            "allowed-ips": [
              "any",
              "any"
            ]
          }
        ]
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Active configuration was successfully read",
  "error": 0
}
```

Remoted only checks if ipv6 is `yes/YES`, otherwise it takes ipv6 as `no`.

The expected behavior is to show a warning and take the default value (ipv6=no).
