### ISSUE TITLE
Update references to legacy users and group in unit tests

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7705]
### Description

As part of #7646 some unit tests uses as data the legacy users and group.

https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/src/unit_tests/shared/test_privsep_op.c#L24

https://github.com/wazuh/wazuh/blob/564f122cc3c1deb261a550ee8f47dcdc2f312e68/src/unit_tests/shared/test_privsep_op.c#L42

They should be replaced by `wazuh` to get consistency with the rest of the code.

**Comment by alromeros** [comment]
Devel branch: https://github.com/wazuh/wazuh/tree/7701-rename-users-group-in-makefile-code

**Comment by chemamartinez** [comment]
Merged #7710
