### ISSUE TITLE
Syslog - wazuh is receiving firewall messages but they are not being processed and logged in archives.log

### ISSUE THREAD

**Issue by meewash-p** [wazuh/wazuh#7706]
|Wazuh version: 4.1.1-4102|Syslog input|All-in-one installation|Ubuntu 20.04.2 LTS|

Hi,

I am testing wazuh and have faces below issue while implementing OpenWRT logs as a data source. With dnsmasq events everything went with a flying colors, had to write my own decoder and rules, but wazuh is working perfectly fine as expected. However, when I proceeded to firewall logs, things got a little bit complicated. I can see from tcpdumps that syslog messages both for dnsmasq and firewall logs are being send from OpenWRT and both are reaching wazuh server. While dnsmasq logs are properly decoded, kernel (firewall) logs are not - they are visible on tcpdump, but I cannot even see them in archives.log with logall option enabled.

dnsmasq messages visible in archives.log:
![image](https://user-images.githubusercontent.com/51884397/109639569-a113e300-7b4f-11eb-80ef-07c3deb61778.png)

Sample packet with dnsmasq syslog message:
![image](https://user-images.githubusercontent.com/51884397/109637423-129e6200-7b4d-11eb-9be1-ba3d8deb2244.png)

380	133.005208	10.154.10.1	10.154.10.77	Syslog	145	DAEMON.INFO: Mar  2 10:45:09 gw dnsmasq[25242]: 90268 10.154.10.88/33169 cached time1.google.com is 216.239.35.0

kernel messages not visible in archives.log:
![image](https://user-images.githubusercontent.com/51884397/109637174-b6d3d900-7b4c-11eb-9538-d6436d1fe24c.png)

Sample packet with kernel syslog message:
![image](https://user-images.githubusercontent.com/51884397/109637601-48dbe180-7b4d-11eb-9c1f-06ec16934139.png)

381	134.561842	10.154.10.1	10.154.10.77	Syslog	323	KERN.WARNING: Mar  2 10:45:11 gw kernel: [3790399.127213] DROP lan in: IN=br-lan OUT=pppoe-wan PHYSIN=eth1 MAC=3e:3c:50:a0:cd:3d:00:17:88:a0:37:53:08:00 SRC=10.154.10.88 DST=34.90.171.169 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=9932 DF PROTO=TCP SPT=44990 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0

Both dnsmasq and kernel messages visible in tcpdump on wazuh manager:
![image](https://user-images.githubusercontent.com/51884397/109638677-9278fc00-7b4e-11eb-88ea-f9c14f322f64.png)

Have you ever encountered similar issue before? Am I missing something obvious?

**Comment by JcabreraC** [comment]
Hello @meewash-p,

The problem with these logs is the timestamp format. Currently, the date must have two digits on the day of the month for this to be valid. We have open issues with this:
- https://github.com/wazuh/wazuh/issues/5650
- https://github.com/wazuh/wazuh/issues/3525

If the timestamp is written correctly in the example log:
```bash
Mar 02 10:45:11 gw kernel: [3790399.127213] DROP lan in: IN=br-lan OUT=pppoe-wan PHYSIN=eth1 MAC=3e:3c:50:a0cd3d:00:17:88:a0:37:53:08:00 SRC=10.154.10.88 DST=34.90.171.169 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=9932 DF PROTO=TCP SPT=44990 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0
```
You can see with the `wazuh-logtest` tool that the decoder matches the log:
```bash
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line

Mar 02 10:45:11 gw kernel: [3790399.127213] DROP lan in: IN=br-lan OUT=pppoe-wan PHYSIN=eth1 MAC=3e:3c:50:a0cd3d:00:17:88:a0:37:53:08:00 SRC=10.154.10.88 DST=34.90.171.169 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=9932 DF PROTO=TCP SPT=44990 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0

**Phase 1: Completed pre-decoding.
	full event: 'Mar 02 10:45:11 gw kernel: [3790399.127213] DROP lan in: IN=br-lan OUT=pppoe-wan PHYSIN=eth1 MAC=3e:3c:50:a0cd3d:00:17:88:a0:37:53:08:00 SRC=10.154.10.88 DST=34.90.171.169 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=9932 DF PROTO=TCP SPT=44990 DPT=80 WINDOW=29200 RES=0x00 SYN URGP=0'
	timestamp: 'Mar 02 10:45:11'
	hostname: 'gw'
	program_name: 'kernel'

**Phase 2: Completed decoding.
	name: 'kernel'
	parent: 'kernel'
	dstip: '34.90.171.169'
	dstport: '80'
	protocol: 'TCP'
	srcip: '10.154.10.88'
	srcport: '44990'

**Phase 3: Completed filtering (rules).
	id: '4100'
	level: '0'
	description: 'Firewall rules grouped.'
	groups: '['firewall']'
	firedtimes: '1'
	mail: 'False'
```

However, the log will not be displayed because it does not have the `action` field. The decoders using `<type>firewall</type>` must get via `regex` and `order` the next fields:
- action
- srcip
- dstip
- srcport
- dstport
- protocol

If any of these fields are missing, the event will be dropped, and will not be displayed in the `archives.log` file.

Regards,
Juan Cabrera

**Comment by meewash-p** [comment]
Hi @JcabreraC

Thank you for prompt answer! :)

In this case I think the issue is caused by an outdated OpenWRT decoder created for version 15.05:
![image](https://user-images.githubusercontent.com/51884397/109805401-ad697000-7c23-11eb-8b00-fe4f68bbf08e.png)

As for the timestamp, data copypasted straight from Wireshark is not properly formatted, I have checked messages straight from tcpdump gathered on wazuh server and predecoder seems to be working fine.

Later I will try to create custom OpenWRT decoder. Thanks for help!

`
root@wazuh01:~# tcpdump -nnSX port 514 -v
tcpdump: listening on enp2s0, link-type EN10MB (Ethernet), capture size 262144 bytes
10:04:32.295983 IP (tos 0x0, ttl 64, id 5499, offset 0, flags [DF], proto UDP (17), length 150)
    10.154.10.1.38821 > 10.154.10.77.514: SYSLOG, length: 122
        Facility daemon (3), Severity info (6)
        Msg: Mar  3 10:04:32 gw dnsmasq[25242]: 143451 10.154.10.101/50212 query[A] PRINTSAMSUNG.lan.meewash.com from 10.154.10.101
        0x0000:  4500 0096 157b 4000 4011 fb5a 0a9a 0a01  E....{@.@..Z....
        0x0010:  0a9a 0a4d 97a5 0202 0082 6eb2 3c33 303e  ...M......n.<30>
        0x0020:  4d61 7220 2033 2031 303a 3034 3a33 3220  Mar..3.10:04:32.
        0x0030:  6777 2064 6e73 6d61 7371 5b32 3532 3432  gw.dnsmasq[25242
        0x0040:  5d3a 2031 3433 3435 3120 3130 2e31 3534  ]:.143451.10.154
        0x0050:  2e31 302e 3130 312f 3530 3231 3220 7175  .10.101/50212.qu
        0x0060:  6572 795b 415d 2050 5249 4e54 5341 4d53  ery[A].PRINTSAMS
        0x0070:  554e 472e 6c61 6e2e 6d65 6577 6173 682e  UNG.lan.meewash.
        0x0080:  636f 6d20 6672 6f6d 2031 302e 3135 342e  com.from.10.154.
        0x0090:  3130 2e31 3031                           10.101
10:04:32.296320 IP (tos 0x0, ttl 64, id 5500, offset 0, flags [DF], proto UDP (17), length 144)
    10.154.10.1.38821 > 10.154.10.77.514: SYSLOG, length: 116
        Facility daemon (3), Severity info (6)
        Msg: Mar  3 10:04:32 gw dnsmasq[25242]: 143451 10.154.10.101/50212 DHCP PRINTSAMSUNG.lan.meewash.com is 10.154.10.119
        0x0000:  4500 0090 157c 4000 4011 fb5f 0a9a 0a01  E....|@.@.._....
        0x0010:  0a9a 0a4d 97a5 0202 007c e42a 3c33 303e  ...M.....|.*<30>
        0x0020:  4d61 7220 2033 2031 303a 3034 3a33 3220  Mar..3.10:04:32.
        0x0030:  6777 2064 6e73 6d61 7371 5b32 3532 3432  gw.dnsmasq[25242
        0x0040:  5d3a 2031 3433 3435 3120 3130 2e31 3534  ]:.143451.10.154
        0x0050:  2e31 302e 3130 312f 3530 3231 3220 4448  .10.101/50212.DH
        0x0060:  4350 2050 5249 4e54 5341 4d53 554e 472e  CP.PRINTSAMSUNG.
        0x0070:  6c61 6e2e 6d65 6577 6173 682e 636f 6d20  lan.meewash.com.
        0x0080:  6973 2031 302e 3135 342e 3130 2e31 3139  is.10.154.10.119
10:04:33.657130 IP (tos 0x0, ttl 64, id 5725, offset 0, flags [DF], proto UDP (17), length 255)
    10.154.10.1.36264 > 10.154.10.77.514: SYSLOG, length: 227
        Facility kernel (0), Severity warning (4)
        Msg: Mar  3 10:04:33 gw kernel: [3874358.301841] DROP wan in: IN=pppoe-wan OUT= MAC= SRC=194.147.140.150 DST=89.234.219.230 LEN=40 TOS=0x00 PREC=0x00 TTL=245 ID=48418 PROTO=TCP SPT=59801 DPT=21029 WINDOW=1024 RES=0x00 SYN URGP=0
        0x0000:  4500 00ff 165d 4000 4011 fa0f 0a9a 0a01  E....]@.@.......
        0x0010:  0a9a 0a4d 8da8 0202 00eb 5fa8 3c34 3e4d  ...M......_.<4>M
        0x0020:  6172 2020 3320 3130 3a30 343a 3333 2067  ar..3.10:04:33.g
        0x0030:  7720 6b65 726e 656c 3a20 5b33 3837 3433  w.kernel:.[38743
        0x0040:  3538 2e33 3031 3834 315d 2044 524f 5020  58.301841].DROP.
        0x0050:  7761 6e20 696e 3a20 494e 3d70 7070 6f65  wan.in:.IN=pppoe
        0x0060:  2d77 616e 204f 5554 3d20 4d41 433d 2053  -wan.OUT=.MAC=.S
        0x0070:  5243 3d31 3934 2e31 3437 2e31 3430 2e31  RC=194.147.140.1
        0x0080:  3530 2044 5354 3d38 392e 3233 342e 3231  50.DST=89.234.21
        0x0090:  392e 3233 3020 4c45 4e3d 3430 2054 4f53  9.230.LEN=40.TOS
        0x00a0:  3d30 7830 3020 5052 4543 3d30 7830 3020  =0x00.PREC=0x00.
        0x00b0:  5454 4c3d 3234 3520 4944 3d34 3834 3138  TTL=245.ID=48418
        0x00c0:  2050 524f 544f 3d54 4350 2053 5054 3d35  .PROTO=TCP.SPT=5
        0x00d0:  3938 3031 2044 5054 3d32 3130 3239 2057  9801.DPT=21029.W
        0x00e0:  494e 444f 573d 3130 3234 2052 4553 3d30  INDOW=1024.RES=0
        0x00f0:  7830 3020 5359 4e20 5552 4750 3d30 20    x00.SYN.URGP=0.
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel
root@wazuh01:~# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.1.1
Type one log per line

Mar  3 10:04:33 gw kernel: [3874358.301841] DROP wan in: IN=pppoe-wan OUT= MAC= SRC=194.147.140.150 DST=89.234.219.230 LEN=40 TOS=0x00 PREC=0x00 TTL=245 ID=48418 PROTO=TCP SPT=59801 DPT=21029 WINDOW=1024 RES=0x00 SYN URGP=0

**Phase 1: Completed pre-decoding.
        full event: 'Mar  3 10:04:33 gw kernel: [3874358.301841] DROP wan in: IN=pppoe-wan OUT= MAC= SRC=194.147.140.150 DST=89.234.219.230 LEN=40 TOS=0x00 PREC=0x00 TTL=245 ID=48418 PROTO=TCP SPT=59801 DPT=21029 WINDOW=1024 RES=0x00 SYN URGP=0'
        timestamp: 'Mar  3 10:04:33'
        hostname: 'gw'
        program_name: 'kernel'

**Phase 2: Completed decoding.
        name: 'kernel'
        parent: 'kernel'
        dstip: '89.234.219.230'
        dstport: '21029'
        protocol: 'TCP'
        srcip: '194.147.140.150'
        srcport: '59801'

**Phase 3: Completed filtering (rules).
        id: '100011'
        level: '4'
        description: 'Firewall rule'
        groups: '['firewall']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.

Mar  3 10:04:32 gw dnsmasq[25242]: 143451 10.154.10.101/50212 DHCP PRINTSAMSUNG.lan.meewash.com is 10.154.10.119

**Phase 1: Completed pre-decoding.
        full event: 'Mar  3 10:04:32 gw dnsmasq[25242]: 143451 10.154.10.101/50212 DHCP PRINTSAMSUNG.lan.meewash.com is 10.154.10.119'
        timestamp: 'Mar  3 10:04:32'
        hostname: 'gw'
        program_name: 'dnsmasq'

**Phase 2: Completed decoding.
        name: 'dnsmasq'
        parent: 'dnsmasq'
        action: 'DHCP'
        extra_data: '10.154.10.119'
        srcip: '10.154.10.101'
        url: 'PRINTSAMSUNG.lan.meewash.com'

**Phase 3: Completed filtering (rules).
        id: '100002'
        level: '0'
        description: 'dnsmasq messages grouped.'
        groups: '['dnsmasq']'
        firedtimes: '1'
        mail: 'False'

`

**Comment by hitman28594** [comment]
https://github.com/wazuh/wazuh/issues/7706
