### ISSUE TITLE
Replace ossecm user from the mail example

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7707]
### Description

As part of #7646 the email used as an example: `ossecm@example.wazuh.com` should be replaced by `wazuh@example.wazuh.com`

https://github.com/wazuh/wazuh/blob/0fd7b0d255a32bfad5d6661b7149ff0b1608dcf8/etc/ossec-server.conf#L15

Best regards.

**Comment by alromeros** [comment]
Devel branch: https://github.com/wazuh/wazuh/tree/7701-rename-users-group-in-makefile-code

**Comment by chemamartinez** [comment]
Merged #7710
