### ISSUE TITLE
Investigate and define test performance metrics and develop the necessary tools

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7724]
Hello team,

We should investigate and define the most appropriate test performance metrics for the loaded Wazuh environment tests (Wazuh API requests time, cluster synchronization time, wazuh-db access time, processes cpu, processes memory, etc).

Also, as part of this issue we should develop any necessary tools to obtain the required measurements.

Any problems and constraints found during the investigation should be clearly defined and addressed.

Regards,

David J. Iglesias

**Comment by vicferpoy** [comment]
## Status update

Hello team,

After researching which daemons we should monitor and which metrics we should obtain, we have finished a python script for this.

This script can be used both in fore and background, allowing its integration with the performance tests. It is also configurable with the following options:

```
root:/ # ./wazuh-metrics.py -h
usage: wazuh-metrics.py [options]

Wazuh processes metrics

optional arguments:
  -h, --help            show this help message and exit
  -p PROCESS_LIST [PROCESS_LIST ...], --processes PROCESS_LIST [PROCESS_LIST ...]
                        Type the processes name to monitor separated by a whitespace.
  -s SLEEP_TIME, --sleep SLEEP_TIME
                        Type the time in seconds between each entry.
  -u {B,KB,MB}, --units {B,KB,MB}
                        Type unit for the non porcentual values. Default bytes.
  -d, --debug           Enable debug level logging.

```

This script will monitor the following resources for each given process:

- CPU usage
- Virtual Memory usage
- Resident Set Size memory
- Unique Set Size memory
- Proportional Set Size memory
- SWAP memory
- File Descriptors
- Read operations
- Write operations
- Disk read units
- Disk written units
- Disk usage

It will create the following structure, saving all sessions by date and timestamp:

```
process_metrics
├── DAY-MONTH-YEAR
│   └── SESSION_TIMESTAMP
│       ├── process_1.csv
│       └── process_2.csv
└── wazuh-metrics.log

```

### Usage example

We will monitor the `wazuh-apid` and `wazuh-clusterd` daemons, saving the metrics in KB every 3 seconds.

```./wazuh-metrics.py -p wazuh-apid wazuh-clusterd -u KB -s 3```

```
process_metrics/
├── 08-03-2021
│   └── 1615224247
│       ├── wazuh-apid.csv
│       └── wazuh-clusterd.csv
└── wazuh-metrics.log
```

<details>
<summary>wazuh-metrics.log</summary>

```log
2021/03/08 17:24:07 INFO: Started new session: /process_metrics/08-03-2021/1615224247
2021/03/08 17:24:07 INFO: Started monitoring process wazuh-apid (4391)
2021/03/08 17:24:07 INFO: Started monitoring process wazuh-clusterd (4753)
2021/03/08 17:24:31 INFO: Attempting to shutdown all monitor threads
2021/03/08 17:24:31 INFO: Process finished
```

</details>

<details>
<summary>wazuh-apid.csv</summary>

```csv
Timestamp,CPU(%),VMS(KB),RSS(KB),USS(KB),PSS(KB),SWAP(KB),FD,Read_Ops,Write_Ops,Disk_Read(KB),Disk_Written(KB),Disk(%)
17:24:07,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:10,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:13,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:16,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:19,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:22,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:25,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
17:24:28,0.0,387304.0,88496.0,85984.0,86993.0,0.0,20,211,4,0.0,8.0,0.0
```

</details>

<details>
<summary>wazuh-clusterd.csv</summary>

```csv
Timestamp,CPU(%),VMS(KB),RSS(KB),USS(KB),PSS(KB),SWAP(KB),FD,Read_Ops,Write_Ops,Disk_Read(KB),Disk_Written(KB),Disk(%)
17:24:07,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769046,3,0.0,8.0,0.0
17:24:10,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769046,3,0.0,8.0,0.0
17:24:13,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769303,3,0.0,8.0,0.0
17:24:16,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769303,3,0.0,8.0,0.0
17:24:19,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769303,3,0.0,8.0,0.0
17:24:22,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769560,3,0.0,8.0,0.0
17:24:25,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769560,3,0.0,8.0,0.0
17:24:28,0.0,227384.0,37732.0,33776.0,35105.0,0.0,13,769817,3,0.0,8.0,0.0
```

</details>


Regards,
Víctor Fernández
