### ISSUE TITLE
Add ASTYLE to cpp wazuh projects

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7758]
## Description
This issue aims to be able to add a code style checker, this with enough configuration, will automatically help to respect certain standards defined in the project's coding style.

In this way, do not open new code that does not comply with what is defined.

URL:
http://astyle.sourceforge.net/

Source branch: Master
Destination branch: Master

## DoD
- [x] Create custom configuration based on the coding style guideline.
- [x] Add to RTR diff check to set red or green flag.
- [x] Request add astyle as dependency on rtr docker file.
Issue created in wazuh-jenkins repo: https://github.com/wazuh/wazuh-jenkins/issues/2419
- [x] PR CI Pass.

**Comment by tinachoB** [comment]
The following AStyle options will be used as a first approach. This matches with our [Wazuh C++ Coding Style](https://github.com/wazuh/wazuh/wiki/Coding-style-guide-(C-plus-plus)):

```
--style=allman
--dry-run
--indent=spaces=4
--indent-classes
--indent-switches
--indent-cases
--indent-namespaces
--indent-preproc-block
--indent-col1-comments
--delete-empty-lines
--max-instatement-indent=120
--break-blocks
--pad-oper
--pad-header
--align-pointer=type
--align-reference=type
--convert-tabs
--max-code-length=200
--preserve-date
--suffix=none
```
