### ISSUE TITLE
Generate precompiled Arch Linux deps packages

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7766]
### Description

#7058 adds two new external dependencies for Arch Linux installations:

- **pacman-5.2.2**
- **libarchive-3.5.1**

According to the goal proposed at https://github.com/wazuh/wazuh/issues/7586, these libraries should be compiled for Linux i386 and x86_64 to be included along with the rest of the dependencies.

### Requirements

- The packages must be compiled in the OS that ensures compatibility with the rest of Linux distributions
- `tar.gz` precompiled packages should be uploaded to the resources repository
- `make deps` must allow downloading the precompiled packages or the sources to be compiled locally

**Comment by MarcelKemp** [comment]
Development branch: https://github.com/wazuh/wazuh/tree/7766-arch-linux-deps-packages

**Comment by chemamartinez** [comment]
Branch [7766-arch-linux-deps-packages](https://github.com/wazuh/wazuh/tree/7766-arch-linux-deps-packages) has been merged into [7075-arch-linux-support](https://github.com/wazuh/wazuh/tree/7075-arch-linux-support). In addition, the precompiled packages are already uploaded to the dependencies repository.

Thanks to @MarcelKemp!
