### ISSUE TITLE
Add unit testing to Arch Linux support in Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#7768]
### Description

The goal of this issue is to add unit tests to cover 100% of the added code for Vulnerability Detector at #7075.

Therefore, tt should be addressed once the Vulnerability Detector code has been closed (#7767).

**Comment by alromeros** [comment]
**Devel branch:** https://github.com/wazuh/wazuh/tree/7768-archlinux-vd-testing
