### ISSUE TITLE
Question : How to change the admin passowrd in Docker all in one

### ISSUE THREAD

**Issue by AC-WhiteGlint** [wazuh/wazuh#7772]
Hi,

I am deploying the all in one docker containers (small prod env).

However I can't find a way to modify the default admin password.

I am trying tyo use this tool https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic_tuning.html

But it says that it doesn't find opendistro.

How can I change the default admin password for this docker instance?

Best regards.

**Comment by fhielpos** [comment]
Hello AC,

I have just made a little guide on how to change the password on https://github.com/wazuh/wazuh-docker/issues/446#issuecomment-792434196

Feel free to take a look there and ask any questions you may have

Regards

**Comment by AC-WhiteGlint** [comment]
By following the guide, I can see this error coming up : 
[2021-03-09T18:17:32,873][WARN ][c.a.o.s.a.BackendRegistry] [elasticsearch] Authentication finally failed for admin from 172.25.0.4:56154

Wazuh is not able to authenticate in elasicsearch. I followed the guide perfectly and everyhting went fine with no error

**Comment by AC-WhiteGlint** [comment]
This is exactly what I did.

I updated the password for the admin user and this error message came up

**Comment by fhielpos** [comment]
Can you try the following:

```
docker-compose exec wazuh bash
```

Once inside Wazuh, execute the following command to check if Filebeat is able to connect to Elasticsearch:
```
filebeat test output
```

If the everything is correct, you will have something similar to this:

```
elasticsearch: https://elasticsearch:9200...
  parse url... OK
  connection...
    parse host... OK
    dns lookup... OK
    addresses: 172.18.0.3
    dial up... OK
  TLS...
    security... WARN server's certificate chain verification is disabled
    handshake... OK
    TLS version: TLSv1.3
    dial up... OK
  talk to server... OK
  version: 7.10.0
```
If this last one failed, modify the following file to point to the environment variable: `/etc/filebeat/filebeat.yml`

```
output.elasticsearch:
  hosts: ['https://elasticsearch:9200']
  username: 'admin'
  password: ${ELASTIC_PASSWORD}
```

And restart filebeat: `/etc/init.d/filebeat restart`

Let me know if this worked.

**Comment by AC-WhiteGlint** [comment]
Yes it worked.

Last question now.

How to set the maximum retention time in opendistro.

There is no lifecycle rules....

**Comment by fhielpos** [comment]
For Opendistro you can use Index State Management, which allows you to do the same as the Index Lifecycle Management.

You can check it out on this blog post:
https://wazuh.com/blog/wazuh-index-management

Simply scroll down to `OpenDistro ISM` and there you will see how to configure it.

Let me know if this solves your issue!
