### ISSUE TITLE
3.2.x to 3.3.x upgrade issue

### ISSUE THREAD

**Issue by hcv-target** [wazuh/wazuh#778]
After upgrading today, I'm getting the error:

Error. Invalid 'wazuh-app-version' header. Expected version '3.3.x', and found '3.2.x'.

In Wazuh Manager and Agents tabs in Kibana.

Thanks for looking into it.

**Comment by jesuslinares** [comment]
Hi,

The app is compatible with an API in the same _major.minor_. You need to upgrade the app to the version 3.3.x.

Here the list of app packages: https://github.com/wazuh/wazuh-kibana-app#installation.

Thanks,
Jesus.

**Comment by hcv-target** [comment]
Thanks, Jesus. I appears from your link that 3.3.0 is only compatible with kibana 6.2.4, which doesn't appear to be available for debian ATM. Is that expected? Thanks.

**Comment by jesuslinares** [comment]
Just to clarify some concepts:

- The agents are compatible with any manager, if the manager version is equal or higher than the agent version.
- The API must be in the same _major.minor_ than the manager. That means, API v3.3.0 is compatible with manager v3.3.0, but it is not compatible with manger v3.2.0
- Regarding the app:
  - There are 2 versions:
    - Wazuh: The app must be in the same major.minor than the API.
    - Kibana: It must be exactly that version. 
  - Example: wazuhapp-3.3.0_6.2.4.zip
    - The API must be v3.3.x (so the manager must be 3.3.x).
    - Kibana must be in v6.2.4.

We will update the documentation to clarify these points. This link may be useful too: https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html.

What Kibana version are you running?. The previous Kibana versiontki was available for Debian ATM?.

Thanks,
Jesus.

**Comment by hcv-target** [comment]
Thanks for the clarification, Jesus, and thanks for updating the docu. I'm at Kibana v6.2.3, the highest available currently (Ubuntu 16.04 LTS):

```
# apt-get install kibana=6.2.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Version '6.2.4' for 'kibana' was not found
```

**Comment by jesuslinares** [comment]
Do you have the repository enabled?.

Please, check if there are commented lines in _/etc/apt/sources.list.d/elastic-6.x.list_.

**Comment by hcv-target** [comment]
DOH! The repo was indeed commented out. Rookie mistake on my part - now I remember the instructions recommending this at install. I've upgraded elasticsearch, kibana and logstash, restarted all services, everything looks good now. Thanks for the enlightenment!

**Comment by jesuslinares** [comment]
Great!.

**Comment by hcv-target** [comment]
Thanks again @jesuslinares . It seems then that the elastic repo needs to stay disabled and that Wazuh shouldn't be updated without careful examination of the elastic/wazuh compatibility matrix.

Thanks for the insight, and for the great product.

**Comment by JuanjiJG** [comment]
Hello @hcv-target,

We will update the documentation for a better explanation of the compatibility between Wazuh, Elastic and the Wazuh app. In the meantime, you can check this table on the README file from our Wazuh app repository:

https://github.com/wazuh/wazuh-kibana-app#installation

We're constantly updating it with links to our available Wazuh app packages, and you can see the required Wazuh and Elastic version to make it work properly.

Thanks for your patience.

Regards,
Juanjo

**Comment by nikhilsingh42** [comment]
Error. 3005 - Invalid 'wazuh-app-version' header. Expected version '3.8.x', and found '3.6.x'.
Tried the step mentioned on this page still getting the same error.

Regards
Nikhil

**Comment by jesusgn90** [comment]
Hi @nikhilsingh42 ,

Please paste the output from the next two commands:

```
// On the Wazuh API instance
cat /var/ossec/api/package.json | grep version

// On the Wazuh app (Kibana) instance
cat /usr/share/kibana/plugins/wazuh/package.json
```

Regards

**Comment by nikhilsingh42** [comment]
screen shot are in the attachment:

![1](https://user-images.githubusercontent.com/47519186/52555209-0ed8ff00-2e0f-11e9-8cd3-f5b0fcc05b46.PNG)
![2](https://user-images.githubusercontent.com/47519186/52555210-0ed8ff00-2e0f-11e9-9c94-09aaab63b9d3.PNG)

Regards
Nikhil

**Comment by nikhilsingh42** [comment]
screen shots are in the attachment

**Comment by jesusgn90** [comment]
Hi @nikhilsingh42 ,

You are using an old Wazuh app. Your Wazuh API is **3.8.2**, let's see the possible combinations:

- Wazuh **v3.8.2** + Kibana **v6.5.4** + Wazuh app **3.8.2-6.5.4** ([wazuhapp-3.8.2_6.5.4.zip](https://packages.wazuh.com/wazuhapp/wazuhapp-3.8.2_6.5.4.zip))
- Wazuh **v3.8.2** + Kibana **v6.6.0** + Wazuh app **3.8.2-6.6.0** ([wazuhapp-3.8.2_6.6.0.zip](https://packages.wazuh.com/wazuhapp/wazuhapp-3.8.2_6.6.0.zip))

Regards!

**Comment by nikhilsingh42** [comment]
Getting  this error with this combinations

**Comment by nikhilsingh42** [comment]
getting these error when applying above mentioned combination
![5](https://user-images.githubusercontent.com/47519186/52558666-1d2c1880-2e19-11e9-9261-71b9ba7a1015.PNG)

Regards
Nikhil

**Comment by jesusgn90** [comment]
That's right because you are using Kibana 6.4.x, you must upgrade your Elastic stack too. Take a look at our [upgrading guide](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html).

If you have any issue upgrading, let us know.

Regards

**Comment by nikhilsingh42** [comment]
so i need to upgrade my elastic stack only or both wazuh manger and elastic stack?

Regards
Nikhil

**Comment by jesusgn90** [comment]
Every Wazuh version supports a certain Elastic stack version. Currently, and for Wazuh 3.8.2, we are supporting both 6.5.4 and 6.6.0, my suggestion is to have all the Elastic stack on 6.6.0 since it's the latest version.

Regards

**Comment by nikhilsingh42** [comment]
thanks for the update actually my yum package is broken .
One it is resolve i will upgrade elk and share u the update.

Regards
Nikhil
