### ISSUE TITLE
macOS agent stop working after upgrading macOS Big Sur to 11.2.2 or higher

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#7793]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.1 | ossec-execd | Agent | Packages | Macos Bigsur 11 |

We've detected a problem with the macOS agent on Bigsur (reported by a community user [here](https://groups.google.com/u/1/g/wazuh/c/y7oQ99eX58c)) that causes the agent to stop working after upgrading Bigsur to 11.2.2 version or higher.

We can confirm that this happens to upgrade from 11.2.1 or 11.2 and 11.1 to 11.2.2 or 11.3, the following vagrant box has been used for testing and the problem could be reproduced in there: `<ci_bucket>/vms/vagrant/macos/macos_big_sur.box`

For some reason, the OS removes `/Library/Ossec/queue/alerts/` folder during the upgrade, possibly due to some security measurement introduced recently on macos. We still have no clue on what is the exact cause for this.

This causes execd to fail on start because `/Library/Ossec/queue/alerts/execq` socket cannot be created.

```
2021/03/03 09:42:22 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2021/03/03 09:42:22 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2021/03/03 09:42:22 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated: 15)] Received. Exit Cleaning...
2021/03/03 09:47:48 ossec-execd: INFO: Started (pid: 497).
2021/03/03 09:47:48 ossec-execd: CRITICAL: (1210): Queue '/Library/Ossec/queue/alerts/execq' not accessible: 'No such file or directory'
2021/03/03 10:29:24 ossec-execd: INFO: Started (pid: 1595).
2021/03/03 10:29:24 ossec-execd: CRITICAL: (1210): Queue '/Library/Ossec/queue/alerts/execq' not accessible: 'No such file or directory'
2021/03/03 10:30:01 ossec-execd: INFO: Started (pid: 1664).
2021/03/03 10:30:01 ossec-execd: CRITICAL: (1210): Queue '/Library/Ossec/queue/alerts/execq' not accessible: 'No such file or directory'
```

We're currently working to understand what's going on with the upgrade. We could also make some changes in the socket generation to force the creation of the alerts folder if it doesn't exist just as a way to avoid this kind of failures.

Best regards.

**Comment by clopmz** [comment]
Good morning,

 Any news regarding this issue?

**Comment by spothound** [comment]
Hello @clopmz 

Yes, thanks for your patience. 

As you may know, the source of the error is clear, BigSur is deleting an empty directory un update that the Wazuh agent expects to exist. 

We don't know why that happens yet but we're working to get a fix as soon as possible. We're trying to get it ready to be released in the next version,  Wazuh v4.2.0, which should be released soon, even if it required additional changes in our source code.

We will update this issue as soon as we have more information.

Best regards and thanks again for your patience.

**Comment by alberpilot** [comment]
Hello all

  After taking action with Apple support, we published a 4.1.5 rev 2 package: https://packages.wazuh.com/4.x/macos/wazuh-agent-4.1.5-2.pkg with the recommended fix. Hope it help and sorry for the inconvenience. 

Don't hesitate to re-open the issue if you found further problems. 

Regards, 
Alberto R

**Comment by clopmz** [comment]
Perfect!!!! .... many thanks. Can this upgrade be installed via API or via the agent_upgrade command?

**Comment by alberpilot** [comment]
Unfortunately, we have not macOS WPKs (yet). You have two options: 
- Upgrade the package using the guide: https://documentation.wazuh.com/current/upgrade-guide/upgrading-agent.html
- Create a dummy file in `/Library/Ossec/queue/alerts/`. The package creates: `/Library/Ossec/queue/alerts/sockets`. The file doesn't need to contain any information. The macOS bug removes some empty folders, and  `/Library/Ossec/queue/alerts/` is not empty when the Wazuh agent is running, but it is empty after stop the Wazuh agent, just before a macOS upgrade. Keeping a file there, prevents the folder to be removed.
