### ISSUE TITLE
Feature request for Oracle Solaris Wazuh agent

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#7796]
Hello,

We would like to request the following modules for Wazuh agents with regards to Oracle Solaris: 
1) syscollector module;
2) vulnerability detector module.

Issues encountered:
1) system inventory data for Oracle Solaris is not being populated by the agents;
2) remote upgrade is also not possible either via the CLI or the Wazuh API, the following error is obtained: Status: Error 1816 - Agent information not found in database.

Glad if we can have an update on the implementation of the above features soon.

Thanks and best regards.

**Comment by vikman90** [comment]
Hi @sh-arch-x86.

Thank you for opening this request.

Indeed, the agent does not implement Syscollector in Solaris yet. This is partially related to #2561.

Adding this issue to the roadmap.
Best regards.

**Comment by Dwordcito** [comment]
This requirement is being worked on in the following issue, and it's about to merge.
https://github.com/wazuh/wazuh/issues/11706
