### ISSUE TITLE
how to add load balancer url/ip for api

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#780]
Hi Team,

Question-1
I have setuped haproxy as LB for wazuh cluster. This is working for balancing as per expected.
But since issue of api call when i open url of LB then it is asking for add api on every node.
I want to set LB ip for API call. Let me know if it is possible or suggest me for this

Question-2

What ip should be Bind on Master and client nodes servers in below section:

<nodes>
        <node>10.1.1.0/node> ( confim master ip addr OR LB ip add )
    </nodes>

Currently i have binded on Master IP addr

**Comment by jesuslinares** [comment]
Hi @gyanprakashsahu ,

I am not sure if I understood you correctly.

For now, you should use only the API located in the master node (https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#configuring-the-wazuh-kibana-app).

The communication is performed between client nodes and the master node. So, you must use only the master IP in the list of nodes (https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#deploying-a-wazuh-cluster).

The load balancer should be placed between the agents and the cluster: https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#pointing-agents-to-the-cluster-with-a-load-balancer.

I hope it helps.

**Comment by gyanprakashsahu** [comment]
Hi @jesuslinares,

I have succesfully added LB ip for wazuh api example: http://10.1.0.1:55000

Load Balancer (haproxy) configuration are below:

frontend wazuh_app
    bind *:80
    mode http
    default_backend wazuh-app


backend wazuh-app
    mode        http
    balance     roundrobin
    server      wazuh-master-1 10.1.1.10:80 check
    server      wazuh-node-1 10.51.1.11:80 check
    server      wazuh-node-2 10.51.1.12:80 check

frontend wazuh_api
    bind *:55000
    mode http
    default_backend wazuh-api


backend wazuh-api
    mode        http
    balance     roundrobin
    server      wazuh-master-1 10.1.1.10:55000 check
    server      wazuh-node-1 10.1.1.11:55000 check
    server      wazuh-node-2 10.1.1.12:55000 check

Let me know is this right ?
OR it would be below:
frontend wazuh_app
    bind *:80
    mode http
    default_backend wazuh-app


backend wazuh-app
    mode        http
    balance     roundrobin
    server      in-wazuh-master-1 10.51.0.129:80 check

frontend wazuh_api
    bind *:55000
    mode http
    default_backend wazuh-api


backend wazuh-api
    mode        http
    balance     roundrobin
    server      in-wazuh-master-1 10.51.0.129:55000 check

**Comment by jesuslinares** [comment]
You should use only the API in the master node. So, I assume the second configuration is right.

We are working on a distributed API where you can use any API, regardless of the node type. Then, your first configuration will be right.

**Comment by gyanprakashsahu** [comment]
@jesuslinares  Thanks for reply.. I have one more issue..
## Getting error Agent Never Connected.. I am using Load Balancer for wazuh Cluster. 
Wazuh-Master-Node config file  /var/ossec/etc/ossec.conf
<auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>yes</use_source_ip>
    <force_insert>no</force_insert>
    <force_time>0</force_time>
    <purge>no</purge>
    <use_password>no</use_password>
    <limit_maxagents>yes</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>

**Comment by jesuslinares** [comment]
Hi @gyanprakashsahu ,

You can perform several checks:

1. Did you register the agent in the master node?. Only the master must register agents.
2. Does the key exist in all the managers?.
3. Has the agent a key?.
4. What says the agent in the ossec.log?.
5. Are you using TCP or UDP for agents?.

(Please, use the Markdown syntax to highlight your messages. It looks like some parts are missing.)

Thanks.

**Comment by gyanprakashsahu** [comment]
Hi @jesuslinares,
### Note- Please find the attachment . I have attached Master node config file.

### 1- Did you register the agent in the master node?. Only the master must register agents.
**Ans-** Yeah. I have registered agent on master node and puted Load Balancer IP on Agent Server in ossec.config file. 
### 2- Does the key exist in all the managers?.
**Ans-**  Yes. Keys has existed on all Managers such as Master node and clent nodes.
### 3- Has the agent a key?
**Ans-**  Yes..  Key is exist on agent.
### 4- What says the agent in the ossec.log?
**Ans-**   **LOG File**
2018/06/14 11:12:04 ossec-agentd: INFO: Trying to connect to server (10.51.1.178:1514).
2018/06/14 11:12:14 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:12:26 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:12:27 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '10.51.1.178'.
2018/06/14 11:13:28 ossec-agentd: INFO: Trying to connect to server (10.51.1.178:1514).
2018/06/14 11:13:38 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:13:50 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:13:51 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '10.51.1.178'.
2018/06/14 11:14:52 ossec-agentd: INFO: Trying to connect to server (10.51.1.178:1514).
2018/06/14 11:15:02 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:15:14 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:15:15 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '10.51.1.178'.
2018/06/14 11:16:16 ossec-agentd: INFO: Trying to connect to server (10.51.1.178:1514).
2018/06/14 11:16:26 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:16:38 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused
2018/06/14 11:16:39 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '10.51.1.178'.
### 5- Are you using TCP or UDP for agents?.
**Ans-** Defult config was UDP but i changed it to TCP as per Wazuh load balancer document.

--------------------------------------------------------------------
[master-node-ossec-config.pdf](https://github.com/wazuh/wazuh/files/2100974/master-node-ossec-config.pdf)

**Comment by gyanprakashsahu** [comment]
@mgmacias95

**Comment by jesuslinares** [comment]
Hi @gyanprakashsahu ,

Sorry for the late response.

> 2018/06/14 11:15:02 ossec-agentd: ERROR: (1218): Unable to send message to 'server': Connection refused

The agent is not able to reach 10.51.1.178:1514 TCP.

You can use telnet or a similar tool to check if the agent is able to reach it. It could be a firewall issue.

Just in case, review /var/ossec/etc/client.keys in both servers master and agent.

Regards,
Jesus Linares

**Comment by gyanprakashsahu** [comment]
### @jesuslinares Hi, Thanks 
**Issue has been fixed ..**
Wazuh cluster is working properly.

I added a single API only i.e.- Load Balancer IP/dns. (10.1.1.1). ( Removed other api if added )

I have allowed below things in (Haproxy) Load balancer.

port: 80
mode: http

port: 55000
mode: http

port: 1514
mode: tcp

port:1515
mode: tcp

**Note:**
1- Changed the ossec.config file on server and agent both side port UDP to TCP for port number 1514 .
2- When i registered new agent on server then follow the link  and do the registration it   **ANY** ip  as per link: https://documentation.wazuh.com/3.x/user-manual/registering/registration-process.html because of there is three options ( ANY IP, FIXED IP and RANGED IP ).

**Comment by aherroqachraf** [comment]
any news about this topic
