### ISSUE TITLE
Rename ossec.conf to manager.conf and agent.conf in API and Framework

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#7805]
|Wazuh version|Component|
|---|---|
| 5.0.0 | API/Framework |

Working branch: [dev-separate-conf](https://github.com/wazuh/wazuh/tree/dev-separate-conf)

The purpose of this issue is to rename `ossec.conf` in Wazuh API and Framework according to https://github.com/wazuh/wazuh/issues/7787:

- **Agent configuration**: All settings related to Wazuh Agent will be located at `agent.conf`. Blocks:
  - `<active-response>` (client side)
  - `<agent-upgrade>` (client side)
  - `<client>`
  - `<client_buffer>`
  - `<fluent-forward>`
  - `<gcp-pubsub>`
  - `<labels>` (same as manager)
  - `<localfile>`
  - `<logging>` (same as manager)
  - `<rootcheck>`
  - `<sca>`
  - `<socket>`
  - `<syscheck>`
  - `<wodle>`
    - `<wodle name="agent-key-polling">`
    - `<wodle name="aws-s3">`
    - `<wodle name="azure-logs">`
    - `<wodle name="cis-cat">`
    - `<wodle name="command">`
    - `<wodle name="docker-listener">`
    - `<wodle name="open-scap">`
    - `<wodle name="osquery">`
    - `<wodle name="syscollector">`

- **Manager configuration**: All settings related to Wazuh Manager will be located at `manager.conf`. Blocks:
  - `<active-response>` (manager side)
  - `<agentless>`
  - `<agent-upgrade>` (manager side)
  - `<alerts>`
  - `<auth>`
  - `<cluster>`
  - `<command>`
  - `<database_output>`
  - `<email_alerts>`
  - `<global>`
  - `<integration>`
  - `<labels>` (same as agent)
  - `<logging>` (same as agent)
  - `<remote>`
  - `<reports>`
  - `<rule_test>`
  - `<ruleset>`
  - `<syslog_output>`
  - `<task-manager>`
  - `<vulnerability-detector>`

Also, to avoid confusion, `agent.conf` shared configuration file should be renamed to `shared.conf` and `agent-template.conf` file to `shared-template.conf`.

In addition, `gen_ossec.sh` script file has to be renamed to `gen_wazuh.sh`.

WPK agent upgrades should also be tested via API and CLI. This should be the behavior:

- When upgrading using a WPK repository, a version check should be performed:
  - If the agent version is lower than 5.0 and the version to upgrade is greater or equal than 5.0, upgrade should not continue because it is a breaking change (not supported).
  - If the agent version is lower than 5.0 and the version to upgrade is lower than 5.0, upgrade should continue.
- When upgrading using a custom WPK package:
  - If the agent version is lower than 5.0 and the version to upgrade is greater or equal than 5.0, an error will be reported and a roollback has to be done in the agent (check that this is working).
  - If the agent version is lower than 5.0 and the version to upgrade is lower than 5.0, upgrade should continue.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
### Issue status

**Working branch:** feature/7805-rename-ossec-conf

I have updated all API and framework functions using ossec.conf and references to it using the ossec word as now we will use manager.conf and agent.conf.
I have also updated old agent.conf. The new shared configuration file is called shared.conf.

I have also updated the configuration files used in the API integration tests and unittests envionments.

xml_parser.py has also been updated as now the configuration files have the tags wazuh_config instead of ossec_config.


Wazuh installation working.
Cluster working.
API working (some API calls tested).

**Comment by mcarmona99** [comment]
### Unittests updated:

A lot of changes needed, now we don't have a default `ossec.conf `in the repo's `etc` folder. 
Now we have no template and the `manager`/`agent.conf` is generated when installing, using `inst-functions.sh`.
I have saved copies of the default `manager.conf` and `agent.conf` in our unittests data folders.

```
framework/wazuh/core/tests/
============================================== 652 passed, 9 warnings in 2.43s ==============================================
```

Currently fixing `framework/wazuh/tests/` ...

TODO:

- WPK agent upgrades changed in API and CLI
- Fix API integration test environment, old wazuh agents? changed to jenkins env?

**Comment by mcarmona99** [comment]
### Issue status

Issue updates in the linked PR: https://github.com/wazuh/wazuh/pull/8188
