### ISSUE TITLE
Development of SCA policies for new vendors

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#7810]
Hello team,

We should include these new policies in our current SCA ruleset, for the latest version:

- MS IIS. https://www.cisecurity.org/benchmark/microsoft_iis/

- VMware. https://www.cisecurity.org/benchmark/vmware/

- Nginx. https://www.cisecurity.org/benchmark/nginx/

- Mongo. https://www.cisecurity.org/benchmark/mongodb/

- Postgre. https://www.cisecurity.org/benchmark/postgresql/

- Oracle. https://www.cisecurity.org/benchmark/oracle_database/

Regards,

**Comment by jcruzlp** [comment]
All vendors except VMWare was added successfully. Closing this.
