### ISSUE TITLE
Insert a hash in the agents database to uniquely identify the Operating System

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7814]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we need to uniquely identify the alerts generated in Vulnerability Detector with the Operating System when they affect it. Having said that, and based on the design for this epic, we should save in the agents' databases a hash to uniquely identify the Operating System. This hash will be used later to identify the vulnerabilities alerted and stored in the `vuln_cves` table that affect the OS.

**Comment by MiguelazoDS** [comment]
As a brief introduction of the problem, at this moment `Vulnerability Detector` doesn't have a way to update the `vuln_cves` table other than a full scan. If any change in the operating system occurs (i.e. installation of hotfixes), a partial scan won't reflect the changes in the table, ergo we have outdated information. 

Performing a full scan that includes information about packages, hardware, network and others every time we need to update the table is not a efficient solution.

What we were thinking is to delegate to the `SysCollector` module the job to create a `triaged` field in `sys_osinfo` table that will notify to `VulDet` if a new scan is needed, but just for the operating system. 

To support legacy agents that clean the table every time the `sysCollector` component does a new scan, we need to modify the triaged value only when we get new information. This is the purpose of the checksum value, that will be generated using the operating system information along with the hotfixes data.

The `checksum` value needed could be obtained using the existent one taking into account that we need to define a value different than `legacy`.
