### ISSUE TITLE
Syscollector empty location field in package table [macOS]

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#7843]
## Description
This issue points to populate the location field, which is not having values ​​for any records.
![imagen](https://user-images.githubusercontent.com/14300208/110737600-6cb5bc00-820c-11eb-8e2b-56448aab8c58.png)

Actual Result: Location field empty.
Expected Result: Location field with data.

## DoD
- [x] Populate location field.
- [x] Add Unit Test.
- [ ] PR CI Pass.

**Comment by tinachoB** [comment]
It looks like `source` field is missing too. Working to add it too.
