### ISSUE TITLE
YML Decoding Tool: Arrange decoded fields by normalized/not normalized

### ISSUE THREAD

**Issue by juanrricci** [wazuh/wazuh#7850]
Hello team,

The aim of this issue is to develop a new feature for the YML Decoding Tool that has to proceed as follows:
- Parse root keys from WCS list.
- Create a Python list with these keys.
- Compare the obtained keys with the ones that come from input logs after decoding. This defines which keys are normalized and which are not.
- Arrange the decoded fields by following the suggested JSON output structure on #7094.

**Comment by 72nomada** [comment]
Closing this. will reopen if we need to improve the tool
