### ISSUE TITLE
Stock configuration of ossec.conf on macosx results in failure to communicate with manager (auto generated install script from ui)

### ISSUE THREAD

**Issue by JustTom2** [wazuh/wazuh#7866]
1. Installed an agent on macosx using add new agent in Elastic web ui - correctly provided IP of manager, assigned to 'Mac' group, then ran the auto generated script on the new agent host:

curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.1.2-1.pkg && sudo launchctl setenv WAZUH_MANAGER='192.168.1.96' WAZUH_AGENT_GROUP='Mac' && sudo installer -pkg ./wazuh-agent.pkg -target /

Upon installation agent was found to be correctly running on system, however did not register with manager. See key error in log:
agent-auth: ERROR: Could not resolve hostname: 192.168.1.96=WAZUH_AGENT_GROUP=Mac

I proceeded to manually register using agent registration script in bin. However, this only achieved agent registration, not connection. (The agent became listed as never connected)

I fixed the issue by editing the ossec.conf that had been installed automatically and removing =WAZUH_AGENT_GROUP=Mac from the address tags.
The addition of '=WAZUH_AGENT_GROUP=Mac' in the address tags prevented the agent from correctly resolving the IP. 

Latest version of manager and agent was used.

**Comment by Dwordcito** [comment]
Hi @JustTom2 , I hope you are well!

Checking your case, I see that you are making an incorrect use of `launchctl setenv`, the next in this message I show you how you should use it.

The mistake was using the = as a separator for key value.

Correct usage:
`curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.1.2-1.pkg && sudo launchctl setenv WAZUH_MANAGER '192.168.1.96' WAZUH_AGENT_GROUP 'Mac' && sudo installer -pkg ./wazuh-agent.pkg -target /`

![imagen](https://user-images.githubusercontent.com/14300208/111077550-124c8200-84d0-11eb-9234-e0ab4dbc002c.png)

**Comment by JustTom2** [comment]
Hi Dwordcito,

I do not believe this issue is closed.  My point is that I did not create the error -- it was the wazduh manager that put together the incorrect commands from the add agent section of the web interface.

**Comment by jnasselle** [comment]
Hi @JustTom2!

Thanks for reporting this bug. This problem was also reported [here](https://github.com/wazuh/wazuh-kibana-app/issues/3058) and it's currently being solved [here](https://github.com/wazuh/wazuh-kibana-app/pull/3066).

Regards,
Nico
