### ISSUE TITLE
Implement a new API endpoint to force an agent reconnection to the manager

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7896]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7886 we are implementing some mechanism to force a reconnection of the Wazuh agents with the manager. One of them consists of instructing a reconnection from the RESTfull API. Having said that, a new API endpoint should be implemented to perform this action.

### Requirements

- It should follow a similar approach to the one implemented to restart the agents.
- The new endpoint should be included in the RESTfull API documentation.
- The endpoint should send internally the string `force_reconnect` as the AR command.
- This should be implemented as a non-AR command by using the flag `NO_AR_C = '!'`.
- The endpoint URL should be `PUT /agents/reconnect`.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by DProvinciani** [comment]
In the next comment, you can find details of the testing done for the agent's changes.

https://github.com/wazuh/wazuh/pull/7941#issuecomment-802143988

**Comment by mcarmona99** [comment]
### Issue status

Working branch: `feature/7896-force-reconnection-endpoint`

I have added the endpoint and its rbac action.
I have been testing the endpoint and it works, as it can be seen in the following logs:

**MASTER:**
```
2021/03/19 16:08:35 wazuh-remoted[1994] ar-forward.c:40 at AR_Forward(): DEBUG: Active response request received: (msg_to_agent) [] N!S 001 force_reconnect
2021/03/19 16:08:35 wazuh-remoted[1994] ar-forward.c:99 at AR_Forward(): DEBUG: Active response sent: #!-force_reconnect
```

**AGENT:**
```
2021/03/19 16:09:13 wazuh-agentd[1673] receiver.c:92 at receive_msg(): DEBUG: Received message: '#!-force_reconnect'
2021/03/19 16:09:13 wazuh-agentd[1673] receiver.c:131 at receive_msg(): INFO: Wazuh Agent will be reconnected because a reconnect message was received
```

I have refactored `wazuh_queue.py`
I have updated the unit tests. In these tests, I have updated the wazuh_queue ones due to the refactor. I have also added new tests cases to cover the new endpoint's functions.

```
pytest framework/wazuh/tests/
============================== 744 passed, 12 warnings in 56.60s ===============================

pytest framework/wazuh/core/tests/
================================ 657 passed, 11 warnings in 2.43s ================================
```

I have updated the API integration tests. They are not passing due to an error discovered in our API integration tests environment.

Regards,
Manuel.

**Comment by mcarmona99** [comment]
Issue blocked by https://github.com/wazuh/wazuh/pull/7983
