### ISSUE TITLE
odd issue name keeps replacing 

### ISSUE THREAD

**Issue by farzadha2** [wazuh/wazuh#7899]
Hi,
I was wondering if someone could shed some light on the issue im having, Currently i install wazuh agents on linux following this commands

```
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -
echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | tee -a /etc/apt/sources.list.d/wazuh.list
apt-get update

WAZUH_AGENT_NAME='zeuspet' WAZUH_MANAGER="wazuh.mydomain.com" apt-get install wazuh-agent

systemctl daemon-reload
systemctl enable wazuh-agent
systemctl start wazuh-agent

```
after some time the agent goes from zeuspet to zeus which is the real hostname but i need to change to zeuspet because i have other server also named zeus so not sure why it keeps changing back 
any ideas how to trouble shoot this issue?

Thank you

**Comment by johnfont** [comment]
Hi @farzadha2! Hope you're doing well!
I see what is going on here. Since the version 4.0 we are supporting agent enrollment, this mechanism allows to automatically register any agent when it starts without keys, and I think that your issue is related with this feature.
In order to solve your problem you need to declare the agent name that you need inside of the `ossec.conf` in your host, in order to do that you need to edit the `/var/ossec/etc/ossec.conf` and add the `<enrollment>` lines on the `<client>` section:

```
<client>
   <server>
     <address>XXX.XXX.XXX.XXX</address>
     <port>1514</port>
     <protocol>tcp</protocol>
   </server>
   <config-profile>OS</config-profile>
   <notify_time>10</notify_time>
   <time-reconnect>60</time-reconnect>
   <auto_restart>yes</auto_restart>
   <crypto_method>aes</crypto_method>
 <enrollment>
   <agent_name>zeuspet</agent_name>
 </enrollment>
</client>
```

Having the enrollment section without the desired agent_name will register the agent with his hostname automatically. You can find more information about agent enrollment here (https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html)

Let me know if you need further assistance.

**Comment by johnfont** [comment]
Hi @farzadha2!

Have you been able to test the solution provided?

Let me know!

**Comment by farzadha2** [comment]
hey there thanks again for the reply, and sorry for the late reply, 
so im testing with another server to see how it goes, as you see it shows posiedon instead of posiedonmery
so i added the part where you say and restarted the agent it still does now show
![image](https://user-images.githubusercontent.com/62571297/111859079-29460680-890c-11eb-84ad-9dbc99179e01.png)

```
    </server>
    <crypto_method>aes</crypto_method>
	 <enrollment>
   <agent_name>posiedonmery</agent_name>
 </enrollment>

```
would i need to delete the agent and readd it?
quick question on the ID number when i delete an agent it does not replace that ID number? right now i had to delete alot and when i add it instead of replacing the number it just skips it

Thank you again

**Comment by johnfont** [comment]
Hi @farzadha2!

The enrollment feature is activated when the agent is not able to communicate with the manager, so in your case we need to invalidate the existent key linked to the agent and wait 60 seconds for the agent re-authenticate with the name declared on the `agent_name` tag.
You can invalidate the key through a call from the Dev Tools:

![imagen](https://user-images.githubusercontent.com/79602926/112045348-84087980-8b29-11eb-8404-54dffd4c08df.png)

Here is an example of how to delete the agent with ID 200793:

`DELETE /agents?agents_list=200793&older_than=1s&status=all`


Regarding the ID number question, thats right, the id is not getting replaced, instead the new registration is going to assing a new ID number to the agent.

Let me know how it went.

Regards!

**Comment by farzadha2** [comment]
Hi again thank you again so much for the reply, 
so doing the following did the trick to reactivate 
![image](https://user-images.githubusercontent.com/62571297/112086753-cdbd8800-8b5a-11eb-9f00-6430adf2c646.png)

the command that worked for me was to put active instead of all


`DELETE /agents?agents_list=200793&older_than=1s&status=active`

i will post back this week because i would have to the following to all the servers  and see how it goes

as the ID number i shouldn't worry on the gap it has lets say i have ID 101 and another which shows 200793?

Thank you so much again

**Comment by johnfont** [comment]
Hi @farzadha2!

There is no problem with the gap that you are seeing on the Agents section in Wazuh.

Please let me know how it went with the others servers!

Best regards!

**Comment by farzadha2** [comment]
Hey there thank you again so far everything is working great
