### ISSUE TITLE
Reduce verbosity of FIM logs

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#7902]
|Wazuh version|Component|
|---|---|
| 4.2-dev | Wazuh FIM |

We have noticed that FIM is quite verbose even on debug level 1, which makes it hard for logs generated by it to be properly read. 

We will be reviewing log messages and adding them in this issue in order to either lower the level or remove them as we best see fit in each case.

**Comment by Molter73** [comment]
The following `debug1` logs should be demoted to `debug2`:
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/fim_sync.c#L57
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/fim_sync.c#L92
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/main.c#L195
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_check.c#L589
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_check.c#L665
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_check.c#L813
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L100
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L232
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L258
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L395
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L512
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L589
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_realtime.c#L607
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/syscheck.c#L186
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/db/fim_db_files.c#L396-L397
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/db/fim_db_registries.c#L462-L463
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/db/fim_db_registries.c#L492-L493
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/db/fim_db.c#L382
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L121
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L126
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L131
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L187
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L194
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L199
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/audit_rule_handling.c#L213
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/win_whodata.c#L155
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/win_whodata.c#L425
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/win_whodata.c#L729
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/whodata/win_whodata.c#L956

The following `minfo` log must be demoted to `debug2`:
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/run_check.c#L586

The following `debug2` messages should be deleted to help reduce clutter in the log files:
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/create_db.c#L68
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/create_db.c#L109

The following `debug2` messages should be moved to a place where it will only be shown once, since the parameters in play cannot be changed and the message will not change either:
https://github.com/wazuh/wazuh/blob/ff13cc1b8db73ad3b8552d30c2c47a8273bbca4a/src/syscheckd/create_db.c#L201-L207

**Comment by MiguelCasaresRobles** [comment]
Hello team,

it seems these logs are also prompted in Wazuh for info:

```
2021/07/28 04:46:05 ossec-agent: INFO: (6356): Maximum file size limit to generate diff information configured to '51200 KB' for 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon'.
```
it will be generated a line for every line configured. This should be in debug mode.

Regards,

Miguel Casares
