### ISSUE TITLE
Implement unit test cases to cover the implementation of the CVEs inventory in Vulnerability Detector

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7926]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, a mechanism to have a CVEs inventory is being implemented. As part of this implementation, Vulnerability Detector received many changes in its workflow. Having said that, init tests cases should be implemented to cover all the changes implemented.

**Comment by MiguelazoDS** [comment]
Several unit tests cases failed after the changes introduced in #8022 as part of #7915 that were not fully revised. The completion and coverage of the new functionality remains pending to be accomplished in the next sprint that begins 29/03.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8240 was merged.
