### ISSUE TITLE
Vulnerability detection for Oracle Linux

### ISSUE THREAD

**Issue by VAdamec** [wazuh/wazuh#793]
Probably depends on #462 but is there any way how to do vuln. detection for OL6/7 ?

**Comment by crolopez** [comment]
Hi @VAdamec,

As you have seen, a new functionality has been developed to support systems derived from compatible versions. In this way, a RedHat-based system, such as oracle linux, could compare its vulnerabilities with those of RedHat. This functionality will be released in Wazuh 3.4.

However, Oracle Linux has its own feed of vulnerabilities that we will also support in a future release.

Best regards.

**Comment by branchnetconsulting** [comment]
I have a customer with Oracle Linux versions 7, 8, and 9, and we would really like to make Wazuh Vulnerability Detection useful to them.  Any chance 4.8.0 might be that "future release" mentioned above?  Forcing the use of the Redhat CVE feed with the Oracle systems has produced massive false positives.
