### ISSUE TITLE
Custom changes to the ruleset not working properly

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#7948]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4-rev | Ruleset | - | - | - |

Hello team,

We have found an issue when applying custom changes to the ruleset. Specifically to the AWS WAF rules. When adding a tag `overwrite=”yes”` to the default rule. The applied changes do not apply and we get as an output wrong alerts.

Here an example with the default AWS WAF rules:

```
    <rule id="80441" level="0">
        <if_sid>80440</if_sid>
        <match>"ALLOW"</match>
        <description>AWS WAF - Allowed request.</description>
        <group>aws_waf,aws_waf_allow,</group>
        <options>no_full_log</options>
    </rule>
    <rule id="80442" level="3">
        <if_sid>80440,80441</if_sid>
        <match>"BLOCK"</match>
        <description>AWS WAF - Blocked request.</description>
        <group>aws_waf,aws_waf_block,</group>
        <options>no_full_log</options>
    </rule>
```
Applying changes:

```
<group name="amazon,aws,">
  <rule id="80441" level="7" overwrite="yes">
    <if_sid>80440</if_sid>
    <field name="aws.action">ALLOW</field>
    <description>AWS WAF - Allowed request</description>
    <group>aws_waf,aws_waf_allow,</group>
    <options>no_full_log</options>
  </rule>
  <rule id="80442" level="3" overwrite="yes">
    <if_sid>80440</if_sid>
    <field name="aws.action">BLOCK</field>
    <description>AWS WAF - Blocked request</description>
    <group>aws_waf,aws_waf_block,</group>
    <options>no_full_log</options>
  </rule>
</group>
```
Using an AWS WAF log and /var/ossec/bin/ossec-logtest:

`{"integration":"aws","aws":{"terminatingRuleId":"Default_Action","terminatingRuleType":"REGULAR","log_info":{"s3bucket":"XXXXXXXXXXXXXXXXX","log_file":"xxxxxx/xxxx/xx/xx/xx/xxx-xxx-logs-xxx-x-xxxx-xx-xx-xx"},"ruleGroupList":[{"excludedRules":null,"terminatingRule":null,"nonTerminatingMatchingRules":[],"ruleGroupId":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},{"excludedRules":null,"terminatingRule":null,"nonTerminatingMatchingRules":[],"ruleGroupId":"XXXXXXXXXXXXXXXXXXXXXXXX"}],"source":"waf","httpSourceId":"XXXXXXXXXXXXXXX","webaclId":"XXXXXXXXXXXXXXXXXXXXXXXXXXX","action":"ALLOW","httpRequest":{"headers":[{"name":"Host","value":"XXXXXXXXXXXX"},{"name":"Connection","value":"keep-alive"},{"name":"Cache-Control","value":"max-age=0"},{"name":"XXXXXXXXXXXXXXXXXXXXXXXXXXX","value":"1"},{"name":"XXXXXXX","value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"},{"name":"Accept","value":"XXXXXXXXXXXXXXXXXXXXXXXXXXXX"},{"name":"XXXX","value":"XXXX"},{"name":"XXXX","value":"navigate"},{"name":"XXXX","value":"?1"},{"name":"XXXXX","value":"document"},{"name":"XXXXX","value":"\"XXXXXXXXXXXX\";v=\"89\", \"XXXXXXX\";v=\"89\", \";Not A Brand\";v=\"99\""},{"name":"XXXXXXXXXXXXXX","value":"?0"},{"name":"Referer","value":"XXXXXXXXXXXXXXXXXXXXXXXXXXX"},{"name":"Accept-Encoding","value":"XXXXXXXXXXXX"},{"name":"XXXXXXXXXXXXXXXX","value":"XXX"},{"name":"XXXX","value":"XXXXXXXXXXXXXXXXXXXXXXXXX"}],"country":"XX","httpVersion":"XX/XX","requestId":"XXX","clientIp":"XXXXX","httpMethod":"GET","uri":"/prefill"},"rateBasedRuleList":{"limitValue":"XXXXXX","rateBasedRuleName":"rate-XXXX","rateBasedRuleId":"XXXXXXX","maxRateAllowed":"2000","limitKey":"IP"},"httpSourceName":"XXX","nonTerminatingMatchingRules":[],"formatVersion":"1","terminatingRuleMatchDetails":[],"timestamp":"XXXXXXXXXXXXXXXXXXX"}}
`

We get as an output:

```
       *Rule 80440 matched.
       *Trying child rules.
    Trying rule: 80441 - AWS WAF - Allowed request
       *Rule 80441 matched.
       *Trying child rules.
    Trying rule: 80442 - AWS WAF - Blocked request
       *Rule 80442 matched.
       *Trying child rules.
    Trying rule: 80443 - AWS WAF - Multiple Blocked request.

**Phase 3: Completed filtering (rules).
       Rule id: '80442'
       Level: '3'
       Description: 'AWS WAF - Blocked request'
**Alert to be generated.
```
A Blocked request event even though the event doesn't even contain "BLOCK". 

Even changing the rule that matches and placing any field still generates the alert.

Example:

```
  <rule id="80442" level="3" overwrite="yes">
    <if_sid>80440</if_sid>
    <field name="aws.action">TEST</field>
    <description>AWS WAF - Blocked request</description>
    <group>aws_waf,aws_waf_block,</group>
    <options>no_full_log</options>
  </rule>
```
Output:

```
**Phase 3: Completed filtering (rules).
       Rule id: '80442'
       Level: '3'
       Description: 'AWS WAF - Blocked request'
**Alert to be generated.
```
Please check this out and let me know if you have any questions about it.

**Comment by chemamartinez** [comment]
Opening this issue again because we have modified the behavior for these tags in 4.3.1 (see https://github.com/wazuh/wazuh/pull/13439 for more information).

Currently, the use of the following labels is allowed:
- `if_sid`
- `if_group`
- `if_level`
- `if_matched_sid`
- `if_matched_group`
However, these tags will have no effect when creating overwritten rules since it would break the relationship between the original rule with the others that are previously loaded in memory. The original value of these tags is kept but the rest of the rule is overwritten, showing a warning message if the user tried to change its value.

To fix this issue, we have several options.
1. We could ignore the entire overwrite rule when the user tries to update the value of any of these tags. The reason to do that is to avoid loading a rule that works in a different way than the user wrote.
2. Fix the use of these labels, by reloading the rules tree when needed to make it work.
