### ISSUE TITLE
Standardize WazuhDB vuln_cve agents naming methods

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#7953]
### Description

WazuhDB methods in charge of handling **vuln_cve** table from **agents** database should follow the same naming convention as the methods in charge of handling the **global** database.
For example, the methods to generate an insert action should be named in the following way:

**wdb_agents_helpers.c** without specifying the database, only a short description for the client of WazuhDB:
`wdb_insert_vuln_cve()`

**wdb_agents.c** specifying the database and any other required field to describe the actions:
`wdb_agents_insert_vuln_cve()`

**wdb_parser.c** using the same name as the method that will finally call, with "parse" prefix:
`wdb_parse_agents_insert_vuln_cve() `

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8456 was merged.
