### ISSUE TITLE
 Amazon AWS CloudWatch logs are not being decoded.

### ISSUE THREAD

**Issue by c3sar0n** [wazuh/wazuh#7956]
|4.0.4|Decoders and Rules|Cloud

Hello team,
We have recently configured the CloudWatch log service on AWS, but logs are not being decoded.
https://documentation.wazuh.com/current/amazon/services/supported-services/cloudwatchlogs.html#aws-cloudwatchlogs
The configuration file:
```
<wodle name="aws-s3"> 
  <disabled>no</disabled> 
  <interval>5m</interval> 
  <run_on_start>yes</run_on_start> 
  <service type="cloudwatchlogs"> 
    <access_key>my_access_key</access_key> 
    <secret_key>my_secret_key</secret_key> 
    <!--<only_logs_after>2021-MAR-08</only_logs_after>--> 
    <aws_log_groups>VPC_Flow_Group_Logs</aws_log_groups> 
    <regions>us-east-1</regions> 
  </service> 
</wodle>
``` 

I've created the attached decoders and worked correctly for VPC Flow logs taking the following guide as a reference:
https://docs.aws.amazon.com/es_es/vpc/latest/userguide/flow-logs.html#flow-logs-default
Default log format:
`<version> <account-id> <interface-id> <srcaddr> <dstaddr> <srcport> <dstport> <protocol> <packets> <bytes> <start> <end> <action> <log-status>`
Default logs are coming as following from Cloudwatch:
```
2 800000076 eni-0400000009b 45.0.0.21 10.1.14.105 10668 80 6 3 120 1615987246 1615987260 ACCEPT OK
2 800000076 eni-05f10000000cf - - - - - - - 1616017163 1616017177 - NODATA
```
I'm receiving logs as following after these are being decoded in the alerts.json:
> tail alerts.json |grep CloudWatch
> {
>    "timestamp":"2021-03-19T18:15:26.676+0000",
>    "rule":{
>       "level":3,
>       "description":"Amazon CloudWatch: VPC flow Rejected",
>       "id":"107001",
>       "firedtimes":1,
>       "mail":false,
>       "groups":[
>          "aws-cloudwatch"
>       ]
>    },
>    "agent":{
>       "id":"000",
>       "name":"wazuh-manager-master-0"
>    },
>    "manager":{
>       "name":"wazuh-manager-master-0"
>    },
>    "id":"1616177726.0",
>    "cluster":{
>       "name":"97e0000078",
>       "node":"wazuh-manager-master-0"
>    },
>    "decoder":{
>       "name":"aws-cloudwatch"
>    },
>    "data":{
>       "protocol":"6",
>       "action":"REJECT",
>       "srcport":"52090",
>       "dstport":"12133",
>       "version":"2",
>       "account-id":"8000000076",
>       "interface-id":"eni-02c000000005",
>       "srcaddr":"162.0.0.158",
>       "dstaddr":"10.0.0.151",
>       "packets":"1",
>       "bytes":"44",
>       "start":"1616177646",
>       "end":"1616177654",
>       "log-status":"OK"
>    },
>    "location":"Wazuh-AWS"
> }

[amazon_cloudwatch_rules.xml.txt](https://github.com/wazuh/wazuh/files/6174036/amazon_cloudwatch_rules.xml.txt)
[amazon_cloudwatch_decoders.xml.txt](https://github.com/wazuh/wazuh/files/6174038/amazon_cloudwatch_decoders.xml.txt)

Kind regards,
Cesar Moreno.

**Comment by 72nomada** [comment]
CloudWatch will work as a transport method for multiple logs from different services. shouldn't be a CloudWatch decoder itself but specific decoders that will manage them. 

check #9342 as a possible approach on this.
