### ISSUE TITLE
Hide syscheck.diff for GDPR

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#7962]
Hello everyone :)

I would like to hide the syscheck.diff field because it shows the old and new data of the monitored files, this data is a bit sensitive for some clients.

Do you know how to hide them at the agent or manager level? To disable them for example? (I try to put in addition a file monitoring of course)

Thanks you,

Bye bye

**Comment by antoniomanuelfr** [comment]
Hi @simon-verbois 

You can hide the diff information retrieved by the agents if you use the option `nodiff`. You can find more information on this page of the [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/syscheck.html#nodiff).

If you have any doubts, don't hesitate to contact us.

**Comment by simon-verbois** [comment]
Thanks a lot!

**Comment by simon-verbois** [comment]
second question, it's only applicable to files? and not a folder? I don't see anything about it in the doc.

**Comment by antoniomanuelfr** [comment]
Hi @simon-verbois 

You can add the `type` attribute to the `nodiff` option and specify a regular expression. If any path matches the regex, it will be ignored. You can find more info here about the[ syntax of sregex](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#sregex-os-match-syntax) (it only match very simple regex, but should be enough for most cases)
