### ISSUE TITLE
Add the STATUS and TYPE of the vulnerabilities to the GET /agents/{agent_id}/cve API endpoint

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#7972]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we are adding new information to the agents' vulnerabilities inventory. This new information will be:

- `status`: It indicates whether the vulnerability is `VALID`, `PENDING`, or `OBSOLETE`.
- `type`: It indicates whether the vulnerability affects the `OS` or a particular `PACKAGE`.

This information should be added to the `GET /agents/{agent_id}/cve` API endpoint created as part of the epic https://github.com/wazuh/wazuh/issues/7479.

For details about the database columns and the values constraints, check the issue https://github.com/wazuh/wazuh/issues/7888 and the pull https://github.com/wazuh/wazuh/pull/7898.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
We are finally only adding `type` parameter.
