### ISSUE TITLE
Failed to start custom command with active response for custom rules and custom decoders

### ISSUE THREAD

**Issue by sbeugnon** [wazuh/wazuh#7985]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.1-40110 | Wazuh component | Manager | Packages | Ubuntu 18.04 |

Hi, I am a new user of Wazuh. I really like the Wazuh/Elastic Search.Kibana stack. It makes security more accessible to everyone. And I'd like to automate the creation of groups and the assignment of agents to groups based on different geographic or scaling group criteria.

I'm trying to use active responses to run a specific command when a new agent connects to the manager to retrieve some cloud information such as `instance-id, vpc, scaling group` and then create associated groups and sort the agents.
All this on the server side where the manager is located.
 
To setup this active response, I have written this in my manager `ossec.conf`:
```
  <command>
    <name>process-agent-identity</name>
    <executable>process-agent-identity.sh</executable>
    <expect></expect>
  </command>
    <active-response>
    <command>process-agent-identity</command>
    <location>server</location>
    <rules_id>100004</rules_id> <!-- my custom rule -->
    <level>3</level>
  </active-response>
```

In my manager `local_rules.xml` I have:
```

<group name="local,monitor,stats">
    <rule id="100003" level="0">
        <decoded_as>agent-identity</decoded_as>
        <description>Cloud Agent Identity Protocol rules.</description>
    </rule>
    
    
    <rule id="100004" level="4">
        <if_sid>100003</if_sid>
        <field name="type">aws</field>
        <description>Identified Wazuh Agent from AWS (instance-id: $(instance)).</description>
    </rule>
</group>
```
In my manager `local_decoder.xml`:

```
<var name="header">agent-identity</var>
<var name="type_field">type=</var>

<decoder name="agent-identity">
    <prematch>agent-identity: type=</prematch>
    <regex offset="after_prematch">(aws)\s+instance-id=(\S+)</regex>
    <order>type, instance</order>
</decoder>
```

When I use `ossec-logtest` or `wazuh-logtest`, I get:
```
agent-identity: type=aws instance-id=test

**Phase 1: Completed pre-decoding.
	full event: 'agent-identity: type=aws instance-id=test'

**Phase 2: Completed decoding.
	name: 'agent-identity'
	instance: 'test'
	type: 'aws'

**Phase 3: Completed filtering (rules).
	id: '100004'
	level: '3'
	description: 'Identified Wazuh Agent from AWS (instance-id: test).'
	groups: '['local', 'monitor', 'stats']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.
```

My agents frequently run a simple command to send this simple line of log.
My alerts are created (and logged) but my active response does not start.
And when I activate `execd.debug=2` I get this in my logs:

```
2021-03-23T13:57:07+00:00 ossec-execd DEBUG  Received message: 'process-agent-identity0 - - 1616507827.5686445 100004 (ip-XXX-XXX-XXX-XXX) any->command_agent-identify - -'
2021-03-23T13:57:07+00:00 ossec-execd DEBUG  Executing command '/var/ossec/active-response/bin/process-agent-identity.sh add'
```

But my log `active-responses.log` is empty.

I've been at it for 2 days and could use some help checking if what I'm doing is right.

**Comment by mcarmona99** [comment]
Hi @sbeugnon ,

Have you checked your script `process-agent-identity.sh` has execution permissions? Has it user and group `root:ossec`? These 2 things could be reasons why your script is not being executed.

Just to ensure, does your script log the call? If you see the script `restart.sh` in `/var/ossec/active-response/bin` (for example), you will see the following lines:

```
LOCAL=`dirname $0`;
cd $LOCAL
cd ../../
PWD=`pwd`

# Logging the call
echo "`date` $0 $1 $2 $3 $4 $5" >> ${PWD}/logs/active-responses.log
```

This is why you see a log in your `active-responses.log`. If you don't add that lines to your custom script you won't see any logs.

Would you mind sending the content of `process-agent-identity.sh`? It will help me make a deeper investigation of your problem.

**Comment by sbeugnon** [comment]
Hi @mcarmona99 

Thanks you for your help.

Using your lines, I was able to see the execution of my script. 

Now my script is running but I'm facing two new problems:

### First issue:

It seems that my active-response is called from multiple places:
```
Wed Mar 24 08:44:36 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575476.0 533 netstat listening ports
Wed Mar 24 08:44:45 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575485.893232 100004 (ip-XXX-XXX-XXX-XXX) any->command_agent-identify -
Wed Mar 24 08:44:45 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575485.894797 502 ossec-monitord - -
Wed Mar 24 08:44:47 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575487.895126 19011 sca - -
...
Wed Mar 24 08:46:24 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575584.3746581 23503 (ip-XXX-XXX-XXX-XXX) any->vulnerability-detector -
Wed Mar 24 08:46:24 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575584.3750837 23503 (ip-XXX-XXX-XXX-XXX) any->vulnerability-detector -
Wed Mar 24 08:50:50 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575850.5673279 100002 (ip-XXX-XXX-XXX-XXX) any->/var/log/audit/audit.log -

```

Is it because my `active-response` uses `<level>3</level>` or is it because I have not defined my `<program_name>` in my decoder and rule? It seems that my manager's audit system also triggers my active response. It is like active-responses create new active-responses in a loop.

I use this in all my agents:

```
<wodle name="command">
		<disabled>no</disabled>
		<tag>agent-identify</tag>
		<command>/bin/bash /var/ossec/etc/shared/scripts/identify_agent.sh</command>
		<ignore_output>no</ignore_output>
		<run_on_start>yes</run_on_start>
		<interval>1m</interval>
		<timeout>0</timeout>
		<verify_md5></verify_md5>
		<verify_sha1></verify_sha1>
		<verify_sha256></verify_sha256>
</wodle>
```

Should I filter by the `rule_id` at the beginning of my script to avoid these calls? Or is it a way to strictly activate my active-response only for my custom rule `100004`.


### Second issue:

I wish to give to my active-response, extracted fields from my decoder (instance-id, vpc-id, etc). Do I have to use `<expect>` or `<extra_args>`.
Or do I need to extract them manually from the alerts.log using:
```
grep -A 10 "$ALERTTIME" ${PWD}/logs/alerts/alerts.log | grep -v "\.$ALERTLAST: " -A 10 | grep -v "Src IP: " | grep -v "User: " | grep "Rule: " -A 4 | sed '/^$/Q' | cut -c -139 | sed 's/\"//g'
```

**Comment by mcarmona99** [comment]
Hi again,

**About your first issue:**

Your logs include the rule ID that run the active response script (in the following examples, rules `533` and `100004` (the custom one), respectively).

```
Wed Mar 24 08:44:36 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575476.0 533 netstat listening ports
Wed Mar 24 08:44:45 UTC 2021 /var/ossec/active-response/bin/process-agent-identity.sh add - - 1616575485.893232 100004 (ip-XXX-XXX-XXX-XXX) any->command_agent-identify -
```

Therefore, your active response script  is called when those 2 rules generate alerts. This happens because you configured active-response to be run when generating an alert with at least level 3 (`<level>3</level>`).

If you want your active response to be executed only  for rule with ID `100004`, remove the `<level>3</level>` tag so your filter will only be `<rules_id>100004</rules_id>`. Let's say it is like a union operator, with both tags, your AR will be executed for rule `100004` OR rules with `level >=3`.

**Second issue:**

`extra_args` is used to give arguments to your active response script (hardcoded arguments, they can't be extracted fields).

If you want to give extracted fields, use `expect`. I am afraid to say this tag is limited to the values: `srcip`, `user` or `filename`. In your case, if the decoder is a custom one, this may not be a problem as you could give one of that name to the extracted field you want to pass.

Here you can see the [expect](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/commands.html#expect) tag specification.

I hope this helps, let me know if you have more problems!

**Comment by sbeugnon** [comment]
Hi!

Thanks you ! Everything is working well now.

For the second part, I was inspired by the `ossec-slack.sh` script and I retrieved then decoded the alert to get my fields.
I noticed that I had to put a `sleep 1` in order to keep the log file up to date. Otherwise it happened in some cases that the alert was not yet present in the file.

**Comment by mcarmona99** [comment]
Hi! I am going to close this issue as the problem was solved. If you have more questions, feel free to join our [mailing list](https://groups.google.com/forum/#!forum/wazuh), [Slack](https://wazuh.com/community/join-us-on-slack/) or [collaborate in GitHub](https://github.com/wazuh/)!
