### ISSUE TITLE
Wazuh Openscap Internal Error

### ISSUE THREAD

**Issue by Cobra1978** [wazuh/wazuh#7994]
|Wazuh version|Component|Install type|Install method|Platform|
|4.1.3|Openscap|Agent|Packages|Centos 8|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Hi

We have a Wazuh 4.1.x ODFE installation, Kibana, Server and ElasticSearch are on Docker, Agents are on Our Virtual Server.

The OpenScap component is not Working, in the agent logs we see

```
2021/03/24 09:23:26 sca: INFO: Module started.
2021/03/24 09:23:26 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_centos8_linux.yml'
2021/03/24 09:23:26 wazuh-modulesd:oscap: ERROR: Internal error. Exiting...
```

The relevant configuration part is

```
  <wodle name="open-scap">
    <disabled>no</disabled>
    <timeout>1800</timeout>
    <interval>1d</interval>
    <scan-on-start>yes</scan-on-start>

    <content type="xccdf" path="ssg-centos-8-ds.xml">
      <profile>xccdf_org.ssgproject.content_profile_pci-dss</profile>
      <profile>xccdf_org.ssgproject.content_profile_server</profile>
    </content>
  </wodle>
```

Other checks are working good

Someone can help?

There are something we can do to give you more detailed info?

**Comment by Dwordcito** [comment]
Hi @Cobra1978 I hope you are well!

Hi, could you please enable debug logs and post the message immediately before the error you get?

It should be something like "Launching command: [DYNAMIC COMMAND]" 

Also, review that all the files/directories have the proper permissions and owners.
  
Besides this, could you test if python works correctly for you? 
if python works correctly, could you launch the dynamic command that returns the debug log? 



How to enable debug logs: 
https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#wazuh-modules

**Comment by Cobra1978** [comment]
I forgot to write it here, but i've done the steps you described and found that is a problem with python script, the mkfifo problem, that already on the way to be fixed.

Thanks, you could close the issue

**Comment by Dwordcito** [comment]
Thanks for letting me know, that you are doing well!

**Comment by Dwordcito** [comment]
Anyways, OpenScap was deprecated in 4.0.0, please refer to this issue in order to get more information about SCA and the explanation of how to set up openscap manually in case you still need it.

https://github.com/wazuh/wazuh/issues/7110#issuecomment-759537868
