### ISSUE TITLE
ossec-authd service

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh#80]
Hi,

since authd offers multiple authentication methods in 2.0, please add the possibility to start it with the other daemons using ossec-control / a systemd service file to ease deployment using configuration management tools.

**Comment by snaow** [comment]
Hi hex2a,

I agree, make sense.

We already have a systemctl/systemctl/chkconfig/service for ossec-authd but we are not including it out-of-the-box, we plan to do it in the near future.

See attached three versions for the ossec-authd service, we will improve and include them in further releases.

**Note:** Draft version.
[wazuh_authd_systemctl.txt](https://github.com/wazuh/wazuh/files/811267/wazuh_authd_systemctl.txt)
[wazuh-authd_el.txt](https://github.com/wazuh/wazuh/files/811268/wazuh-authd_el.txt)
[wazuh_authd_deb.txt](https://github.com/wazuh/wazuh/files/811269/wazuh_authd_deb.txt)
