### ISSUE TITLE
Trying to restart agents in a group without agents assigned returns "Bad request" message

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#8001]
As @maumrsms reported in https://github.com/wazuh/wazuh-api/issues/499:

--------------------------------------

| **Wazuh version** |
|-|
| 4.x |

Hello team,
There's an issue when trying to restart Agents from a group which has no Agents assigned to it throught the API. It shows status code 400 along with next detail: 
```
{
  "title": "Bad Request",
  "detail": "The group does not have any agent assigned",
  "remediation": "Please select another group or assign any agent to it",
  "dapi_errors": {
    "wazuh-master": {
      "error": "The group does not have any agent assigned"
    }
  },
  "error": 1755
}
```
- The 3.x API almost always returned a "status code 200" so you had to read the error to know something went wrong.
- This can be seen as an actual bug: sending a group restart request to a server that doesn’t have any agents assigned is not a bad request. If someone has 50+ wazuh servers most surely he/she won't want to have to search for Agents in groups on servers (to find out where the agents are) before sending the restart requests. Instead it'll be preferred to send restart requests to all servers and then collect the affected_ids in the results.
- This issue relates specifically to `PUT /agents/group/{group-name}/restart` endpoint.

**Comment by mcarmona99** [comment]
### Issue status

We are raising the `1755` error code and message before calling the `restart_agents` function from the SDK, in the `dapi.py`. 

When we try to do the distributed master call (in `distribute_function`), we call the function `forward_request`. This function uses `get_solver_node` to get the nodes the agents belonging to the specific group are reporting to.

If `len(agents) == 0`, we raise the error mentioned above:

https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/dapi/dapi.py#L548-L549 

I have been investigating and I have come up with some ideas to solve this issue:

1- Update the `valid_nodes` variable to be assigned with a tuple `('', [])`, that indicates unknown node and empty `agent_list`. Bad idea, this will result on a call to `restart_agents` with all agents (as the `agent_list` is empty). Hardcoding [] with an agent_list with a wrong agent will make us need a new exclude_code and a lot of changes in the controller and SDK function.

https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/dapi/dapi.py#L469

2- When the exception with code 1755 raises, return an empty response with a specific message. This may change the consistency of the API response messages, but will maintain its format and the fix will be applied. The fix would be something like this:

```
 except exception.WazuhError as e:
            if e.code == 1755:
                return wresults.WazuhResult(params)
            e.dapi_errors = self.get_error_info(e)
            return e
```

in the `except` part of `distribute_function`.


3- Other ideas like refactoring SDK functions or controllers, bad ones as it is not necessary to make that changes to include this fix.

Regards,
Manuel.

**Comment by mcarmona99** [comment]
## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
