### ISSUE TITLE
Rules/Decoder advice 

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#8009]
|4.1.0-1|Rules/Decoders|Manager|Packages|Ubuntu 16 in docker|

Hi guys,
by default wazuh writes web accesslog in the wazuh elasticsearch index only 4xx and 5xx requests.
I need it to write all 2xx,3xx,4xx and 5xx from one specific file only.

I tried something like this:
```
<rule id=xxxxxx, level=5>
 <if_group>accesslog</if_group> OR <if_sid>the id of the ignored requests rule</if_sid>
 <location>myfile</location>
 <description>Myfile access log</description>
</rule>
```

Which on first look it seems to work fine, however when I set up only filebeat without wazuh and compare them there at least 1k logs missing for a given time.

Is there appropriate way to do this ?
Another question I have, can you advice for child decoder on the web-accesslog with extra_data to be user agent?

**Comment by fabamatic** [comment]
Hi @a108a108 !
You are pretty close to the correct answer for the rule, you should drop the location tag. It should look like this

```
<rule id="XXXXX" level="5">
    <if_sid>31108</if_sid>
    <description>Custom Access Log</description>
</rule>
```
Regarding your second question. It's fine to use either extra_data or a custom "agent" field. Keep in mind that capturing agent data may be tricky depending on the format of the event logs you receive.

**Comment by a108a108** [comment]
Hi @fabamatic !
Thank you for your answer, but I have other access log files. Wouldn't that affected them all?
The idea is to see all logs from one specific location and not from the others.

**Comment by fabamatic** [comment]
Sorry for the delay @a108a108, you are correct, location will to see logs from an specific file.
There is a probability that logs are being dropped by the [anti-flooding mechanism](https://documentation.wazuh.com/current/user-manual/capabilities/antiflooding.html?highlight=agent%20queue%20flood) .
Could you check if the flooding warning events are generated (rule ids 202 ,203 or 204)?

**Comment by fabamatic** [comment]
We are closing this issue. Feel free to reopen it if you still have this problem.
