### ISSUE TITLE
Getting different key results via API /agents/:agentId/key to manage_agents and POST /agents

### ISSUE THREAD

**Issue by Know1** [wazuh/wazuh#801]
As per the title says querying the Agent key via the API returns a different result to using manage_agents
The manage_agents is the correct one, as is the initial one returned when adding an agent. The first 28 characters look correct but it seems to then truncate data.

This affects trying to use the REST API to add agents as you can't easily retrieve the key.

I am running the latest Ubuntu (18.04), not sure if it's supported yet but figuring if that is the problem it will need to be sorted at some point anyway. I've provided all relevant details I can think of below, let me know if there's anything else you want.

`root@server:/var/ossec/etc# curl -u MyUser:MyPass -k -X POST -d '{"name":"NewHost","ip":"10.0.0.9"}' -H 'Content-Type:application/json' "https://localhost:55000/agents?pretty"
{
   "error": 0,
   "data": {
      "id": "002",
      "key": "MDAyIE5ld0hvc3QgMTAuMC4wLjkgMzNhNzc3OTc2ZTM2ODAwYTlkODk5NmIxM2JiZDI5NmU2ZDBkMWMwNjJhODg4NGU1OTM0NTdjNWJlZWVjMjAzZA=="
   }
}`

`root@server:/var/ossec/etc# curl -u MyUser:MyPass -k -X GET https://localhost:55000/agents/002/key?pretty
{
   "error": 0,
   "data": "MDAyIE5ld0hvc3QgMTAuMC4wLjkgTm9uZQ=="
}`

`root@server:/var/ossec/etc# /var/ossec/bin/manage_agents -l
Available agents:
   ID: 002, Name: NewHost, IP: 10.0.0.9`

`root@server:/var/ossec/etc# /var/ossec/bin/manage_agents -e 002
Agent key information for '002' is:
MDAyIE5ld0hvc3QgMTAuMC4wLjkgMzNhNzc3OTc2ZTM2ODAwYTlkODk5NmIxM2JiZDI5NmU2ZDBkMWMwNjJhODg4NGU1OTM0NTdjNWJlZWVjMjAzZA==`

`root@server:/var/ossec/etc# cat client.keys
002 NewHost 10.0.0.9 33a777976e36800a9d8996b13bbd296e6d0d1c062a8884e593457c5beeec203d`

It's a new install running Wazuh 3.3, on Ubuntu 18.04, Python version is "Python 2.7.15rc1"

`root@server:/var/ossec/etc# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic`

`root@server:/var/ossec/etc# curl -u MyUser:MyPass -k -X GET 'https://localhost:55000/manager/info?pretty'
{
   "error": 0,
   "data": {
      "compilation_date": "Thu Jun 14 17:03:33 AEST 2018",
      "version": "v3.3.0",
      "openssl_support": "yes",
      "max_agents": "14000",
      "ruleset_version": "3301",
      "path": "/var/ossec/",
      "tz_name": "AEST",
      "type": "manager",
      "tz_offset": "+1000"
   }
}`

Thanks
Luke

**Comment by Lifka** [comment]
Hello @Know1,

thanks so much for the report. It's a bug of Wazuh 3.3. The fix is in the PR: https://github.com/wazuh/wazuh/pull/802.

To fix it you can modify the file `/var/ossec/framework/wazuh/agent.py` replacing the following lines:

https://github.com/wazuh/wazuh/blob/bb49c61193049f1cf6daa453aeef64c74eb0de1f/framework/wazuh/agent.py#L76-L81

by:

https://github.com/wazuh/wazuh/blob/d5a28a1d7edddad1a27e1bcaa8943329fcb6def3/framework/wazuh/agent.py#L76-L82

Best regards,
Javi.
