### ISSUE TITLE
AWS LB integration doesn't extract port number

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh#8018]
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.0.4 | Decoder | Manager | Cloud |

Hello team,

the AWS LB integration doesn't extract the port number. Information in the original log contains data such as:

```
data.aws.backend_port: ip.ip.ip.ip:port_number
data.aws.target_port: ip.ip.ip.ip:port_number
```

Instead of receiving the IP address and the port number in separated fields, both IP and port are inside the same field.

Regards,

Mauricio.

**Comment by davidjiglesias** [comment]
Already done in #7168
