### ISSUE TITLE
Package install and smoke validation test

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8031]
## Description
This issue aims to test that this epic change works on all compromised operating systems, basically, you have to do manual standard operation tests.

## DoD
- [x] Install/smoke tests in supported SO -> https://documentation.wazuh.com/current/installation-guide/packages-list.html.
- [x] Upgrade tests from 4.2
- [x] Sanity checks.
- [x] Upload evidence.

Components task distribution:
- @konangc87 -> execd, active response.
- @tinachoB -> Logcollector
- @Dwordcito -> syscheckd FIM

## **Charters**
# FIM
**Linux:**
- Process Upgrade From 4.2 and > 4.1 (Delete wazuh-syscheckd and ossec-syscheckd) -> Fail
 1. Upgrade to 5.0
 2. syscheckd binaries should be deleted.

- Test ignore files.  -> PASS
 1. Add scan directory to  /tmp/test-wazuh
 2. Add ignore file to /tmp/test-wazuh/test-ignore
 3. Modify /tmp/test-wazuh/test-ignore.
 4. Force re-scan
 5. No alerts should be generated.

- Test diff alert.  -> PASS
 1. Add scan directory to /tmp/test-wazuh.
 2. Create /tmp/test-wazuh/test-change.
 3. Force re-scan.
 4. Modify /tmp/test-wazuh/test-change.
 5. Force re-scan.
 6. Alerts should be generated.
  
- Test diff alert whodata.  -> PASS
 1. Add scan directory whodata to /tmp/test-wazuh.
 2. Create /tmp/test-wazuh/test-change.
 3. Modify /tmp/test-wazuh/test-change.
 4. Alerts should be generated.
  
- Test diff alert realtime.  -> PASS
1. Add scan directory in realtime whodata to /tmp/test-wazuh.
2. Create /tmp/test-wazuh/test-change.
3. Modify /tmp/test-wazuh/test-change.
4. Alerts should be generated.
  
- Process shutdown   -> PASS
1. Init Wazuh process.
2. /var/ossec/bin/wazuh-control restart
3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
1. Set debug mode = 2
2. Restart Wazuh processes.
3. Configuration should be writed in ossec.log file.

**Windows:**

- Test ignore files.  -> PASS
 1. Add scan directory to  C:/temp/test-wazuh
 2. Add ignore file to C:/temp/test-wazuh/test-ignore
 3. Modify C:/temp/test-wazuh/test-ignore.
 4. Force re-scan
 5. No alerts should be generated.

- Test diff alert.  -> PASS
 1. Add scan directory to C:/temp/test-wazuh.
 2. Create C:/temp/test-wazuh/test-change.
 3. Force re-scan.
 4. Modify C:/temp/test-wazuh/test-change.
 5. Force re-scan.
 6. Alerts should be generated.
  
- Test diff alert whodata.  -> PASS
 1. Add scan directory whodata to C:/temp/test-wazuh.
 2. Create C:/temp/test-wazuh/test-change.
 3. Modify C:/temp/test-wazuh/test-change.
 4. Alerts should be generated.
  
- Test diff alert realtime.  -> PASS
1. Add scan directory in realtime whodata to C:/temp/test-wazuh.
2. Create C:/temp/test-wazuh/test-change.
3. Modify C:/temp/test-wazuh/test-change.
4. Alerts should be generated.
  
- Test diff alert registry.  -> PASS
1. Add scan registry whodata to HKLM/Sofware/data.
2. Create HKLM/Sofware/data.
3. Add value HKLM/Sofware/data.
4. Alerts should be generated.

- Process shutdown   -> PASS
1. Init Wazuh process.
2. Ui wazuhl restart
3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
1. Set debug mode = 2
2. Restart Wazuh processes.
3. Configuration should be writed in ossec.log file.

# Active Response
Comment: https://github.com/wazuh/wazuh/issues/8031#issuecomment-825984151

# Logcollector
Comment: https://github.com/wazuh/wazuh/issues/8031#issuecomment-825983160

**Comment by tinachoB** [comment]
## Logcollector
- Install Wazuh agent (windows and linux) and manager  -> **PASS**
1. Run `./install.sh`.
2. Follow the step by step of installation.
3. Check wazuh agent and manager services are running. 
   - Agent:
![image](https://user-images.githubusercontent.com/22640902/115934767-2fc62180-a468-11eb-8ccd-7cc528510976.png)


   - Manager/Server:
 ![image](https://user-images.githubusercontent.com/22640902/115934726-1c1abb00-a468-11eb-8535-808b1a0b7abc.png)



- Read configuration and print it  -> **PASS**
1. Set debug mode = 2
2. Restart Wazuh processes.
3. Configuration should be written in `ossec.log` file.


- Configure a new local file log into the ossec.conf log analysis section  -> **PASS**
1. Add a new `<localfile>...</localfile>` section with a particular log file path.
2. Restart the wazuh services.
  -> logcollector should take this new file under his analysis set.
3. Update the log file content.
4. Check the log is properly analyzed.


- Check default (windows) security events localfile configuration  -> **PASS**
1. Start the service.
2. Check, in the log, everything is up and running.
3. Check in Kibana, security events dashboard, events are generated successfully.


- Check default active response logs events configuration  -> **PASS**
1. Start the service.
2. Check, in the log, everything is up and running.
3. Configure an active response and a command.
4. Check the AR is successfully generated in the active response log and it's taken by the manager too.

**Comment by konangc87** [comment]
## Active Response

Linux:
- Process Upgrade From 4.2 (Delete wazuh-execd) -> Fail
 1. Upgrade to 5.0
 2. wazuh-execd binary should be deleted.

- Test active response stateful/location all/by rule.  -> PASS
 1. Add active response action (firewall-drop by rule 5720)
 2. Fail to ssh connect to agent several times
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test active response stateful/location all/by level.  -> PASS
 1. Add active response action (firewall-drop by level 10)
 2. Fail to ssh connect to agent several times
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test active response stateful/location all/by group.  -> PASS
 1. Add active response action (firewall-drop by group authentication_failure)
 2. Fail to ssh connect to agent
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test restart agents all.  -> PASS
 1. run /var/ossec/bin/agent_control -R -a
 2. all agents should be restarted

- Process shutdown   -> PASS
 1. Init Wazuh process.
 2. /var/ossec/bin/wazuh-control restart
 3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
 1. Restart Wazuh processes.
 2. Configuration should be writed in ossec.log file.

- Test active response repeated offenders.  -> PASS
 1. Add active response action (firewall-drop by group authentication_failure)
 2. Add repeated offenders config in linux agent
 3. Fail to ssh connect to agent
 4. source ip should be denied in linux agent
 5. after timeout the source ip is allowed again
 6. Fail to ssh connect to agent
 7. source ip should be denied in linux agent
 8. after first offender timeout the source ip is allowed again
 9. Fail to ssh connect to agent
 10. source ip should be denied in linux agent
 11. after second offender timeout the source ip is allowed again
 12. Fail to ssh connect to agent
 13. source ip should be denied in linux agent
 14. after third offender timeout the source ip is allowed again

Windows:
- Process Upgrade From 4.2 -> PASS
 1. Upgrade to 5.0

- Test active response stateful/location all/by rule.  -> PASS
 1. Add active response action (netsh by rule 5720)
 2. Fail to ssh connect to agent several times
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test active response stateful/location all/by level.  -> PASS
 1. Add active response action (netsh by level 10)
 2. Fail to ssh connect to agent several times
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test active response stateful/location all/by group.  -> PASS
 1. Add active response action (netsh by group authentication_failure)
 2. Fail to ssh connect to agent
 3. source ip should be denied in all agents
 4. after timeout the source ip is allowed again

- Test restart agents all.  -> PASS
 1. run /var/ossec/bin/agent_control -R -a
 2. all agents should be restarted

- Process shutdown   -> PASS
 1. Init Wazuh process.
 2. open win32ui.exe and restart agent.
 3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
 1. Restart Wazuh agent.
 2. Configuration should be logged in ossec.log file.

**Comment by Dwordcito** [comment]
**Linux:**
- Process Upgrade From 4.2 and > 4.1 (Delete wazuh-syscheckd and ossec-syscheckd) -> Fail
 1. Upgrade to 5.0
 2. syscheckd binaries should be deleted.

- Test ignore files.  -> PASS
 1. Add scan directory to  /tmp/test-wazuh
 2. Add ignore file to /tmp/test-wazuh/test-ignore
 3. Modify /tmp/test-wazuh/test-ignore.
 4. Force re-scan
 5. No alerts should be generated.

- Test diff alert.  -> PASS
 1. Add scan directory to /tmp/test-wazuh.
 2. Create /tmp/test-wazuh/test-change.
 3. Force re-scan.
 4. Modify /tmp/test-wazuh/test-change.
 5. Force re-scan.
 6. Alerts should be generated.
  
- Test diff alert whodata.  -> PASS
 1. Add scan directory whodata to /tmp/test-wazuh.
 2. Create /tmp/test-wazuh/test-change.
 3. Modify /tmp/test-wazuh/test-change.
 4. Alerts should be generated.
  
- Test diff alert realtime.  -> PASS
1. Add scan directory in realtime whodata to /tmp/test-wazuh.
2. Create /tmp/test-wazuh/test-change.
3. Modify /tmp/test-wazuh/test-change.
4. Alerts should be generated.
  
- Process shutdown   -> PASS
1. Init Wazuh process.
2. /var/ossec/bin/wazuh-control restart
3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
1. Set debug mode = 2
2. Restart Wazuh processes.
3. Configuration should be writed in ossec.log file.

**Windows:**

- Test ignore files.  -> PASS
 1. Add scan directory to  C:/temp/test-wazuh
 2. Add ignore file to C:/temp/test-wazuh/test-ignore
 3. Modify C:/temp/test-wazuh/test-ignore.
 4. Force re-scan
 5. No alerts should be generated.

- Test diff alert.  -> PASS
 1. Add scan directory to C:/temp/test-wazuh.
 2. Create C:/temp/test-wazuh/test-change.
 3. Force re-scan.
 4. Modify C:/temp/test-wazuh/test-change.
 5. Force re-scan.
 6. Alerts should be generated.
  
- Test diff alert whodata.  -> PASS
 1. Add scan directory whodata to C:/temp/test-wazuh.
 2. Create C:/temp/test-wazuh/test-change.
 3. Modify C:/temp/test-wazuh/test-change.
 4. Alerts should be generated.
  
- Test diff alert realtime.  -> PASS
1. Add scan directory in realtime whodata to C:/temp/test-wazuh.
2. Create C:/temp/test-wazuh/test-change.
3. Modify C:/temp/test-wazuh/test-change.
4. Alerts should be generated.
  
- Test diff alert registry.  -> PASS
1. Add scan registry whodata to HKLM/Sofware/data.
2. Create HKLM/Sofware/data.
3. Add value HKLM/Sofware/data.
4. Alerts should be generated.

- Process shutdown   -> PASS
1. Init Wazuh process.
2. Ui wazuhl restart
3. Wazuh process should be restarted without problems.

- Read configuration and print it  -> PASS
1. Set debug mode = 2
2. Restart Wazuh processes.
3. Configuration should be writed in ossec.log file.
