### ISSUE TITLE
Vulnerability detector : Agent has an unsupported OS: 'Kali GNU/Linux'

### ISSUE THREAD

**Issue by TheThingGoesSkra** [wazuh/wazuh#8034]
Hi, I try to monitor vulnerabilities on Kali Linux. 

Even if I try to allow the OS on the manager: 

```
    <!-- Debian OS vulnerabilities -->  
    <provider name="debian">
      <enabled>yes</enabled>
      <os allow="Kali GNU/Linux-2021.1">stretch</os>
      <os allow="Kali GNU/Linux-2021.1">buster</os>
      <os>stretch</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>
```

I get this error message in the logs:

```
2021/03/26 11:23:51 wazuh-modulesd:vulnerability-detector[4099] wm_vuln_detector.c:7024 at wm_vuldet_run_scan(): INFO: (5431): Starting vulnerability scan.
2021/03/26 11:23:51 wazuh-modulesd:vulnerability-detector[4099] wm_vuln_detector.c:4836 at wm_vuldet_set_agents_info(): DEBUG: (5485): Agent '006' has an unsupported OS: 'Kali GNU/Linux'

```
Delete the version number in the following line:

`      <os allow="Kali GNU/Linux-2021.1">stretch</os>`

Creates an error when restarting the manager. Am I missing something or is it a compatibility problem plz ?

**Comment by Dwordcito** [comment]
Hi, I hope you are well!

At first glance it seems that the configuration is correct, anyway I am setting up an environment with Kali to try to reproduce her case.

But let's start with the basics, do we have the package list correctly loaded?

this can be verified with `sqlite3 /var/ossec/queue/db/xyz.db "SELECT * FROM sys_programs;"`
Replace xyz with your agent ID

please post the result of this.

**Comment by Dwordcito** [comment]
![imagen](https://user-images.githubusercontent.com/14300208/112711772-b7406500-8ea9-11eb-83a5-dcb7749d8fb7.png)
![imagen](https://user-images.githubusercontent.com/14300208/112711778-c2939080-8ea9-11eb-8d67-d84438a7acb9.png)
I just did tests, the same kali version that you have, and it seems to me that the wrong thing is the ".1" of the value of the allow attribute.

You can try again with ""

**Comment by TheThingGoesSkra** [comment]
It's ok. I'm sorry, I'm just starting to discover wazuh, I didn't think to check in the sqlite3 database ! I will be more autonomous from now on. 

Thank you very much, you do a great job.

**Comment by Dwordcito** [comment]
you're welcome! for us it is a motivation to help!

**Comment by TheThingGoesSkra** [comment]
I'm confused. I thought it was working but it's not. Sorry.
I tried several possibilities using substring, major and minor versions but nothing changed. 

```
      <os allow="Kali-2021.1,Kali-2021,Kali-1,Kali GNU/Linux-2021.1,Kali GNU/Linux-2021,Kali GNU/Linux-1">stretch</os>
      <os allow="Kali-2021.1,Kali-2021,Kali-1,Kali GNU/Linux-2021.1,Kali GNU/Linux-2021,Kali GNU/Linux-1">buster</os>
```

I keep seeing this error message: 

```
2021/03/26 11:23:51 wazuh-modulesd:vulnerability-detector[4099] wm_vuln_detector.c:7024 at wm_vuldet_run_scan(): INFO: (5431): Starting vulnerability scan.
2021/03/26 11:23:51 wazuh-modulesd:vulnerability-detector[4099] wm_vuln_detector.c:4836 at wm_vuldet_set_agents_info(): DEBUG: (5485): Agent '006' has an unsupported OS: 'Kali GNU/Linux'
```
Even if the configuration seems to be correct : 

```
└─$ cat /etc/os-release                                                                                 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2021.1"
VERSION_ID="2021.1"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

```

```
[root@wazuh-manager /]# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_VERSION FROM AGENT WHERE ID = 007;"
Kali GNU/Linux|2021.1
```
```
[root@wazuh-manager /]# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_MAJOR FROM AGENT WHERE ID = 007;"
Kali GNU/Linux|2021
```
```
[root@wazuh-manager /]# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_MINOR FROM AGENT WHERE ID = 007;"
Kali GNU/Linux|1
```

And the list of packages seems to be loaded correctly:
```
[root@wazuh-manager /]# sqlite3 /var/ossec/queue/db/007.db "SELECT * FROM sys_programs;"
OUTPUT TOO BIG...
```

**Comment by TheThingGoesSkra** [comment]
Just to be sure, are you alerted by new messages in the closed issues? Or do I have to re-open an issue plz?

**Comment by Dwordcito** [comment]
Hi, @TheThingGoesSkra how you do?

Could you try like this and tell me?

```
    <!-- Debian OS vulnerabilities -->  
    <provider name="debian">
      <enabled>yes</enabled>
      <os allow="Kali GNU/Linux-2021">stretch</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>
```

**Comment by TheThingGoesSkra** [comment]
Thank you... It works now. Sorry for you time. 
I just realized that, in fact, I had doubled the line...
Shame on me, this github account will be deleted in 10sec........  Ahah

**Comment by Dwordcito** [comment]
haha, no problem friend! we are here to help !!

Thanks!
