### ISSUE TITLE
OSSEC is  HIDS or HIPS app ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#805]
i read on ossec documentation, said:

> OSSEC is a scalable, multi-platform, **open source Host-based Intrusion Detection System (HIDS)**. It has a powerful correlation and analysis engine, integrating log analysis, file integrity checking, Windows registry monitoring, centralized policy enforcement, rootkit detection, real-time alerting and active response.It runs on most operating systems, including Linux, OpenBSD, FreeBSD, MacOS, Solaris and Windows.

How could, ossec is HIDS, while it has "active-response" which could be categorized as HIPS features. Or is it both ?

**Comment by cristgl** [comment]
Hi @gagantous,

First of all, sorry for the late response.
OSSEC is, indeed, an HIDS. The `active-response` feature only provides the functionality of executing an script when an event is triggered, the HIPS software blocks the suspicious attack and alerts the user, allowing them to decide what to do. Additionally, this systems can monitor the drivers installation, registry keys modifications, and whether regions of memory have been modified. In conclusion, there are a lot of functionalities that are not taken into account in OSSEC, so it cannot be considered an HIPS.

Kind regards

**Comment by gagantous** [comment]
Hi @cristgl
Does wazuh categorized as HIDS too ? Since there more improvement than the Original ossec. So will wazuh still categorized as HIDS only app ?

**Comment by cristgl** [comment]
Hi @gagantous,

Wazuh is also considered an HIDS, as it is based on OSSEC.
The main responsibility of an HIDS is to detect intrusions, an HIPS is known to protect the host against attacks from the network layer to the application layer and report them to the user, blocking or stopping them. Wazuh can be configured to detect rootkits, monitor the security policies or monitor the data sent by the agents that will be analyzed in search of vulnerabilities triggered as alerts, reporting them to the manager, etc.
With the active-response module, Wazuh can implement the functionalities of an HIPS, as it can detect suspicious actions and block them, detect malicious IPs and erase them from the iptables table, etc. But this is not enough to describe Wazuh as an HIPS, as this feature doesn't provide all the functionalities of this kind of software, even so, we are working on improving active-response, making Wazuh a more complete solution.

I hope that solves your question, don't hesitate to ask if you got anymore else.

Kind regards
