### ISSUE TITLE
File integrity : read or copy monitoring

### ISSUE THREAD

**Issue by simon-verbois** [wazuh/wazuh#8068]
Hello everyone,

I want to know if with the file integrity monitoring I can display who has read or copied a file, this would be to protect sensitive files from theft for example.

<br>
Thanks you!

<br>
Bye bye

**Comment by mcarmona99** [comment]
Hi @simon-verbois ,

I am afraid to say you cannot see who has read or copied a file with file integrity monitoring.
You can use [who-data](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/) to obtain who-data information from monitored files. This information contains the **user** who made the changes and the process or program used to carry them out.

With a properly [who-data configuration](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html#configuration), alerts like the following will appear in `/var/ossec/logs/alerts/alerts.log` when adding, changing or removing a file in a monitored directory. If you are using Kibana, they will also appear in the dashboard.

The user _Smith_ added a new IP to the file `/etc/hosts.allow` using the _nano_ editor with _sudo_ privileges:

```
** Alert 1531224328.2834462: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,
2018 Jul 10 14:05:28 (vpc-agent-debian) any->syscheck
Rule: 550 (level 7) -> 'Integrity checksum changed.'
Integrity checksum changed for: '/etc/hosts.allow'
Size changed from '421' to '433'
Old md5sum was: '4b8ee210c257bc59f2b1d4fa0cbbc3da'
New md5sum is : 'acb2289fba96e77cee0a2c3889b49643'
Old sha1sum was: 'd3452e66d5cfd3bcb5fc79fbcf583e8dec736cfd'
New sha1sum is : 'b87a0e558ca67073573861b26e3265fa0ab35d20'
Old sha256sum was: '6504e867b41a6d1b87e225cfafaef3779a3ee9558b2aeae6baa610ec884e2a81'
New sha256sum is : 'bfa1c0ec3ebfaac71378cb62101135577521eb200c64d6ee8650efe75160978c'
(Audit) User: 'root (0)'
(Audit) Login user: 'smith (1000)'
(Audit) Effective user: 'root (0)'
(Audit) Group: 'root (0)'
(Audit) Process id: '82845'
(Audit) Process name: '/bin/nano'
What changed:
10a11,12
> 10.0.12.34
Attributes:
 - Size: 433
 - Permissions: 100644
 - Date: Tue Jul 10 14:05:28 2018
 - Inode: 268234
 - User: root (0)
 - Group: root (0)
 - MD5: acb2289fba96e77cee0a2c3889b49643
 - SHA1: b87a0e558ca67073573861b26e3265fa0ab35d20
 - SHA256: bfa1c0ec3ebfaac71378cb62101135577521eb200c64d6ee8650efe75160978c
```
 
You can also audit [who-data in Windows](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows.html).

I hope this helps, don't hesitate to ask if you have more questions!
