### ISSUE TITLE
Log Rotation Issue?

### ISSUE THREAD

**Issue by farzadha2** [wazuh/wazuh#8095]
Hi
Currently got an alert on Wazuh disk space, so i was reading to run this

`0 6,14,22 * * * /bin/rm /var/ossec/logs/alerts/2021/* -Rf && /bin/systemctl restart wazuh-manager`

which helped to liberate space and also deleted 

`cd /var/ossec/logs/alerts/2020`

and rebooted but now im getting this error

`Health Check. Error connecting to API: 2001 - Unexpected end of JSON input`

Not really sure what to do? 

Thank you 

![image](https://user-images.githubusercontent.com/62571297/113376392-3cf36300-9337-11eb-8455-33b1fcd6e3f9.png)

**Comment by CarlosRS9** [comment]
Hell @farzadha2 

Let me try to help you with this issue. 

That particular error is probably due to the fact that Kibana or Elastic ran out of space at a given time. I suggest you to check your `/usr/share/kibana/optimize/wazuh/config/wazuh.yml` file to ensure everything is OK. Its structure should be something similar to this:
```
hosts:
  - default:
     url: https://localhost
     port: 55000
     username: wazuh
     password: wazuh
     run_as: false
```
Additionally, try this:

1. Ensure you have enough space available

2. Stop the Kibana service
`systemctl stop kibana`

3. Remove wazuh-registry.json file
`rm /usr/share/kibana/data/wazuh/config/wazuh-registry.json`

4. Restart the Kibana service so the file will be re-created
`systemctl restart kibana`

5. Remove the browser cache (cookies, local storage, etc...)

6. Try to access Kibana again

Let me know if this solves this issue.

Regards

**Comment by farzadha2** [comment]
Thank you for the reply. 
What i did is to comment the alert logs which helped

`#    <alerts_log>yes</alerts_log>`

but my question is how long does wazuh keep the index or the logs?

I was looking around and saw this guide but not sure if this guide is what i need to delete index after 90 days?

`https://wazuh.com/blog/wazuh-index-management/`

**Comment by CarlosRS9** [comment]
Wazuh will keep the index indefinitely by default. In case you want to delete an index after a certain amount of time, the way to do it is specified in the blogpost you [shared](https://wazuh.com/blog/wazuh-index-management/). 

As explained, the Index rotation in Elastic is managed by using Elastic ILM and OpenDistro ISM tools. You can move the logs to the Delete phase to permanently delete them.

I suggest you take a look in detail at that post to learn about how to manage indexes lifecycle.

Regards

**Comment by farzadha2** [comment]
Thanks for the reply, so i was first trying to figure out the index, but i also see that it keeps alots of logs which not sure why

which i have the part of the config with alert logs commented out

```
<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
#    <alerts_log>yes</alerts_log>
    <logall>no</logall>
    <logall_json>no</logall_json>
    <email_notification>yes</email_notification>
    <smtp_server>localhost</smtp_server>
    <email_from>ids@domain.com</email_from>
    <email_to>ids@domain.com</email_to>
    <email_maxperhour>12</email_maxperhour>
    <email_log_source>alerts.log</email_log_source>
  </global>
```



```
root@wazuh:/var/log/elasticsearch# ls -l -h 
total 831M
-rw-r--r-- 1 elasticsearch elasticsearch  36K Nov 10 00:00 elasticsearch-2020-11-09-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  33K Nov 10 00:00 elasticsearch-2020-11-09-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 103K Nov 11 00:00 elasticsearch-2020-11-10-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 11 00:00 elasticsearch-2020-11-10-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 12 00:00 elasticsearch-2020-11-11-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 12 00:00 elasticsearch-2020-11-11-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 13 00:00 elasticsearch-2020-11-12-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 13 00:00 elasticsearch-2020-11-12-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 14 00:00 elasticsearch-2020-11-13-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 14 00:00 elasticsearch-2020-11-13-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 15 00:00 elasticsearch-2020-11-14-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 15 00:00 elasticsearch-2020-11-14-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 16 00:00 elasticsearch-2020-11-15-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 16 00:00 elasticsearch-2020-11-15-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 17 00:00 elasticsearch-2020-11-16-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 17 00:00 elasticsearch-2020-11-16-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 18 00:00 elasticsearch-2020-11-17-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 18 00:00 elasticsearch-2020-11-17-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 19 00:00 elasticsearch-2020-11-18-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 19 00:00 elasticsearch-2020-11-18-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 20 00:00 elasticsearch-2020-11-19-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 20 00:00 elasticsearch-2020-11-19-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 21 00:00 elasticsearch-2020-11-20-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 21 00:00 elasticsearch-2020-11-20-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 108K Nov 22 00:00 elasticsearch-2020-11-21-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  87K Nov 22 00:00 elasticsearch-2020-11-21-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 111K Nov 23 00:00 elasticsearch-2020-11-22-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  91K Nov 23 00:00 elasticsearch-2020-11-22-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 24 00:00 elasticsearch-2020-11-23-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 24 00:00 elasticsearch-2020-11-23-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 25 00:00 elasticsearch-2020-11-24-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 25 00:00 elasticsearch-2020-11-24-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 26 00:00 elasticsearch-2020-11-25-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 26 00:00 elasticsearch-2020-11-25-1.log.gz
-rw-r--r-- 1 elasticsearch elasticsearch 109K Nov 27 00:00 elasticsearch-2020-11-26-1.json.gz
-rw-r--r-- 1 elasticsearch elasticsearch  88K Nov 27 00:00 elasticsearch-2020-11-26-1.log.gz

```

**Comment by CarlosRS9** [comment]
I think there is a little confusion about the **_alerts_log_**. It has nothing to do with the logs contained your **_/var/log/elasticsearch_** directory. As stated in our [documentation](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html?highlight=alerts_log#alerts-log), the **_alerts_log_** tag is used to toggle the writting of alerts to the **_/var/ossec/logs/alerts/alerts.log_**.

As you can see in the [elastic official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/logging.html), you can configure how and when to delete the logs present in **_/var/log/elasticsearch_**. I suggest you to take a look to it.

I hope this helps.

**Comment by farzadha2** [comment]
thanks for the reply, what i also saw the syslog was getting really big and found that it was opendistro analyzer filling the logs
so i disable the plugin and so far it seems to be good, i thought it was the wazuh logs but it was not, going to wait a few days to see how it goes and post back 
Thank you 
`
/usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_performance_analyzer`
