### ISSUE TITLE
Vulnerability Detector: Windows agents have empty vulnerability data.

### ISSUE THREAD

**Issue by apuckey** [wazuh/wazuh#8097]
Wazuh 4.1.4 Vulnerability detector ( standard OVA install with admin password changed )

Getting a strange issue with only windows agents ( windows 10 or windows server 2012 ), the vulnerability scanner is not adding any data from windows agents into elastic search, ie:

![image](https://user-images.githubusercontent.com/479676/113500215-80301a80-955f-11eb-8e40-efeb78416672.png)

However the agent lists all kb's and packages installed in the inventory:

![image](https://user-images.githubusercontent.com/479676/113500272-f2a0fa80-955f-11eb-9731-e724b0f5d57c.png)

![image](https://user-images.githubusercontent.com/479676/113500283-08aebb00-9560-11eb-9676-7091c8326b57.png)

I've tried adding debug 2 on wazuh and the wazuh-modules but it doesn't show anything exciting that would cause it

here is the relevant config:

```
  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>15m</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <hotfixes>yes</hotfixes>
    <processes>yes</processes>
  </wodle>
  <vulnerability-detector>
    <enabled>yes</enabled>
    <interval>15m</interval>
    <ignore_time>30m</ignore_time>
    <run_on_start>yes</run_on_start>
    <!-- Ubuntu OS vulnerabilities -->
    <provider name="canonical">
      <enabled>yes</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>
    <!-- Debian OS vulnerabilities -->
    <provider name="debian">
      <enabled>no</enabled>
      <os>stretch</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>
    <!-- RedHat OS vulnerabilities -->
    <provider name="redhat">
      <enabled>no</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <update_interval>1h</update_interval>
    </provider>
    <!-- Windows OS vulnerabilities -->
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>30m</update_interval>
    </provider>
    <!-- Aggregate vulnerabilities -->
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>
  </vulnerability-detector>
```

Any way I can debug why this is happening?

Cheers

**Comment by MarcelKemp** [comment]
Hi @apuckey,

At first it seems that everything is configured correctly, and if you have activated `Debug 2` in _wazuh-modules_ and it does not show any `Error` or anything strange, then it seems that the _vulnerability detector_ is working correctly.

Although to be sure that everything is working correctly, could you provide me with the complete list of patches collected on both a **_Windows 10_** and a **_Windows Server 2012_** (Copy and paste all the content of the different pages shown in the `"Windows Updates"` section of both agents). So I can check if there is any vulnerability, or that everything is correct.

Thanks in advance.

If you have any questions, feel free to ask.

**Comment by apuckey** [comment]
Hi @MarcelKemp,

The paste in the initial post is from the windows 2012 server, below is one from a windows 10 machine:

![image](https://user-images.githubusercontent.com/479676/113633309-0f4c4800-96b0-11eb-97f4-c8bff7dc6bcc.png)

It seems there is no information in elastic relating to these nodes, ie: its not saving any data into elastic

however it is saving info on ubuntu machines ( below is an ubuntu 20 machine )

![image](https://user-images.githubusercontent.com/479676/113633489-6a7e3a80-96b0-11eb-8cbc-783c1017d19b.png)

hope this helps.

**Comment by MarcelKemp** [comment]
Hi again @apuckey,

Sorry, I think I have not explained it well :sweat_smile: 
I need the complete patch list to simulate your case and be 100% sure that everything works correctly.

For this, I would need you to copy and paste the entire list of patches for both agents (since if you look at the image I can only view 10 patches, so I would also need the other pages). If you put the option of 50 rows per page you can copy them easily, although I see that _Windows Server 2012_ will also need to turn the page to obtain the complete list. 
Another option would be to **_generate_** the inventory **_report_** for both agents, and obtain the "Windows Updates" list of the reports generated.

Or it is also possible to obtain this list from the manager, accessing the inventory of each agent with the following command (where **_001_** would be the ID of the agent from which we want to obtain the patches):
`sqlite3 /var/ossec/queue/db/001.db "select hotfix from sys_hotfixes;"`

Sorry for the inconvenience.

**Comment by apuckey** [comment]
On further investigation this does appear correct. I installed python 2.7 on the windows server and it displayed correctly as vulnerable. So closing this for now :)

Thanks for your help!
