### ISSUE TITLE
[4.2.0] Memory leak study in modulesd

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#8105]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.0-rc1 | modulesd | Manager | Packages | CentOS |

Hello team,
We have seen that modulesd increases its memory without decreasing it in any moment. It happened in a 3 days test with a stressed Wazuh manager.

We can see this behaviour in the following chart:
![image](https://user-images.githubusercontent.com/10661307/113592921-10d92a00-9636-11eb-9aa5-d24c61c16ea2.png)
The increase seems to be produced after 20 hours of execution.

Here I attach the log trace of the manager
[ossec.log.zip](https://github.com/wazuh/wazuh/files/6258998/ossec.log.zip)

Regards.

**Comment by vikman90** [comment]
@okynos I ran Modulesd on Valgrind and Address Sanitizer, and they reported no memory leaks.

I wonder if that could be due to memory fragmentation, like #6997.
