### ISSUE TITLE
Write article on Hafnium MS Exchange Server attacks and Wazuh detection

### ISSUE THREAD

**Issue by Nekaze** [wazuh/wazuh#8108]
The idea of this issue is to create an article/blogpost on how Wazuh can respond to [Hafnium MS Exchange Server attacks](https://www.microsoft.com/security/blog/2021/03/02/hafnium-targeting-exchange-servers/) to share with the community

**Comment by fabamatic** [comment]
Did research on using Wazuh vulnerability detector. Had some configuration issues. It should work.

**Comment by fabamatic** [comment]
MS Exchange CPE format for Vulnerability detector is different that what the CPE helper json allows. Currently we can't leverage this feature

**Comment by 72nomada** [comment]
Too old to be published. should be reworked
