### ISSUE TITLE
is there a source code bug in function access?

### ISSUE THREAD

**Issue by 0FuzzingQ** [wazuh/wazuh#8113]
|Wazuh version|Component|Install type|Install method|Platform|
|4.0.3|shared|source code install|./install.sh|linux debian8|

in the source code src/shared/exec_op.c function wpopenv()

`case 0:
        // Child code
        if (flags & W_CHECK_WRITE && !access(path, W_OK)) {
            
            merror("At wpopenv(): file '%s' has write permissions.", path);
            _exit(127);
        }`

access(path, W_OK)returns 0 when all privilage is ok , os this if need access to be -1?

**Comment by 0FuzzingQ** [comment]
now in the latest source code in src/shared/exec_op.c function wpopenv() line 184

when has W_OK privilage to the file,the access will return 0,so it will goto this if and exit without doing execvp in line 224?

i think it should turn 

` if (flags & W_CHECK_WRITE && !access(path, W_OK)) {`
to
` if (flags & W_CHECK_WRITE && access(path, W_OK)) {`

did i misunderstand?

**Comment by juliancnn** [comment]
Hi @0FuzzingQ,

Thanks for your concern on the source code, we love to get feedback from users!.
The `wpopenv()` function was designed to prevent code injection attacks.

You can see some information in [this issue](https://github.com/wazuh/wazuh/issues/581) and [this PR](https://github.com/wazuh/wazuh/pull/600) where it was introduced.

The condition checks that certain binaries or scripts to be executed do not have write permissions. This allows the scripts and code that can be executed to be immutable by Wazuh. 
For example, an integrator script will not be able to modify other scripts that can be executed ([here is the call](https://github.com/wazuh/wazuh/blob/8e599ec706aa5e5898017f1ed2edc10da62d87ff/src/os_integrator/integrator.c#L399-L400)). For an integrator script to work, it must have 750 permissions.


Please let me know if you found this helpful.

Regards,
Julian

**Comment by 0FuzzingQ** [comment]
Hi @juliancnn 
thanks a lot for reply me!
i think i understand you . but for me ,it is strange to use FIM module with my thirdparty IOC  (just like virustotal api) to judge if the file is malware.
but when use it i meet this problem,see at /var/ossec/logs/ossec.log 


2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:264 at OS_IntegratorD(): DEBUG: file /tmp/custom-threatbook-1617850611-188736940.alert was written.
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:265 at OS_IntegratorD(): DEBUG: file content: {"timestamp":"2021-04-08T10:56:50.043+0800","rule":{"level":7,"description":"File deleted.","id":"553","mitre":{"id":["T1107","T1485"],"tactic":["Defense Evasion","Impact"],"technique":["File Deletion","Data Destruction"]},"firedtimes":1,"mail":false,"groups":["ossec","syscheck"],"pci_dss":["11.5"],"gpg13":["4.11"],"gdpr":["II_5.1.f"],"hipaa":["164.312.c.1","164.312.c.2"],"nist_800_53":["SI.7"],"tsc":["PI1.4","PI1.5","CC6.1","CC6.8","CC7.2","CC7.3"]},"agent":{"id":"030","name":"sh-sec-hfish-07","ip":"10.23.32.135"},"manager":{"name":"sh-sec-hfish-09"},"id":"1617850610.174963","full_log":"File '/etc/ddd' deleted\nMode: scheduled\n","syscheck":{"path":"/etc/ddd","mode":"scheduled","size_after":"1223123","perm_after":"rwxrwxrwx","uid_after":"0","gid_after":"0","md5_after":"dc929395f5a27106fa7d2ce380a6b5a0","sha1_after":"1ceba2d01769fede0f331d95b5f3a0e6e7e9109c","sha256_after":"bc872ed9e5a97d796a3ade5c22d19209bd10e440d42dce9e1cae5c1390cf08cd","uname_after":"root","gname_after":"root","mtime_after":"2021-02-25T09:56:13","inode_after":1310813,"event":"deleted"},"decoder":{"name":"syscheck_deleted"},"location":"syscheck"}
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:392 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/custom-threatbook /tmp/custom-threatbook-1617850611-188736940.alert f1a6137fd5744482bc14ba8ab466a492d8b2d62b8652465c91fa0198f35d9c9a https://api.threatbook.cn/v3/file/report debug
2021/04/08 10:56:51 ossec-integratord[6854] exec_op.c:142 at wpopenv(): ERROR: At wpopenv(): file '/var/ossec/integrations/custom-threatbook' has write permissions.
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:408 at OS_IntegratorD(): ERROR: Couldn't execute command (/var/ossec/integrations/custom-threatbook /tmp/custom-threatbook-1617850611-188736940.alert f1a6137fd5744482bc14ba8ab466a492d8b2d62b8652465c91fa0198f35d9c9a https://api.threatbook.cn/v3/file/report debug). Check file and permissions.
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.


the output
 `2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:408 at OS_IntegratorD(): ERROR: Couldn't execute command (/var/ossec/integrations/custom-threatbook /tmp/custom-threatbook-1617850611-188736940.alert f1a6137fd5744482bc14ba8ab466a492d8b2d62b8652465c91fa0198f35d9c9a https://api.threatbook.cn/v3/file/report debug). Check file and permissions.` 

show me that i have no permission to execute  my script. so i locate the problem at wpopenv() return without doing execvp.
i don not know why it happens. but when i change !access(path, W_OK) to access(path, W_OK) . it runs ok 

above is my wazuh process and my file privilage:

root      5271 23703  0 11:05 pts/0    00:00:00 grep ossec
ossec     6775     1  1 10:55 ?        00:00:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root      6857     1  0 10:55 ?        00:00:00 /var/ossec/bin/ossec-integratord
root      6879     1  0 10:55 ?        00:00:02 /var/ossec/bin/ossec-authd
root      6954     1  0 10:55 ?        00:00:00 /var/ossec/bin/wazuh-db
root      6978     1  0 10:55 ?        00:00:00 /var/ossec/bin/ossec-execd
root      7051     1  0 10:55 ?        00:00:00 /var/ossec/bin/ossec-analysisd
root      7142     1 48 10:56 ?        00:04:44 /var/ossec/bin/ossec-syscheckd
root      7265     1  0 10:56 ?        00:00:00 /var/ossec/bin/ossec-remoted
root      7378     1  0 10:56 ?        00:00:00 /var/ossec/bin/ossec-logcollector
root      7396     1  0 10:56 ?        00:00:00 /var/ossec/bin/ossec-monitord
root      7477     1  0 10:56 ?        00:00:00 /var/ossec/bin/wazuh-modulesd

drwxr-x---  2 root root 4096 Apr  8 10:53 .
drwxr-x--- 19 root root 4096 Apr  8 10:53 ..
-rwxr-x--x  1 root root 1025 Apr  6 16:32 custom-threatbook
-rwxr-xr-x  1 root root 8257 Apr  7 15:40 custom-threatbook.py
-rwxr-x---  1 root root 4328 Apr  8 10:52 pagerduty
-rwxr-x---  1 root root 1025 Apr  8 10:53 slack
-rwxr-x---  1 root root 3814 Apr  8 10:52 slack.py
-rwxr-x---  1 root root 1025 Apr  8 10:53 virustotal
-rwxr-x---  1 root root 6442 Apr  8 10:52 virustotal.py

**Comment by 0FuzzingQ** [comment]
Hi @juliancnn
thanks a lot for reply me!
i think i understand you . but for me ,it is strange to use FIM module with my thirdparty IOC (just like virustotal api) to judge if the file is malware.
but when use it i meet this problem,see at /var/ossec/logs/ossec.log

2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:126 at OS_IntegratorD(): DEBUG: jqueue_next()
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.
2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:264 at OS_IntegratorD(): DEBUG: file /tmp/custom-threatbook-1617850611-188736940.alert was written.

2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:392 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/custom-threatbook /tmp/custom-threatbook-1617850611-188736940.alert {{my api token}} https://api.threatbook.cn/v3/file/report debug

2021/04/08 10:56:51 ossec-integratord[6854] exec_op.c:142 at wpopenv(): ERROR: At wpopenv(): file '/var/ossec/integrations/custom-threatbook' has write permissions.

2021/04/08 10:56:51 ossec-integratord[6854] integrator.c:408 at OS_IntegratorD(): ERROR: Couldn't execute command (/var/ossec/integrations/custom-threatbook /tmp/custom-threatbook-1617850611-188736940.alert {{my api token}}  https://api.threatbook.cn/v3/file/report debug). Check file and permissions.


the output show me that i have no permission to execute my script. so i locate the problem at wpopenv() return without doing execvp.
i don not know why it happens. so i change !access(path, W_OK) to access(path, W_OK) and  it runs ok

above is my wazuh process and my file privilage:

root 5271 23703 0 11:05 pts/0 00:00:00 grep ossec
ossec 6775 1 1 10:55 ? 00:00:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
root 6857 1 0 10:55 ? 00:00:00 /var/ossec/bin/ossec-integratord
root 6879 1 0 10:55 ? 00:00:02 /var/ossec/bin/ossec-authd
root 6954 1 0 10:55 ? 00:00:00 /var/ossec/bin/wazuh-db
root 6978 1 0 10:55 ? 00:00:00 /var/ossec/bin/ossec-execd
root 7051 1 0 10:55 ? 00:00:00 /var/ossec/bin/ossec-analysisd
root 7142 1 48 10:56 ? 00:04:44 /var/ossec/bin/ossec-syscheckd
root 7265 1 0 10:56 ? 00:00:00 /var/ossec/bin/ossec-remoted
root 7378 1 0 10:56 ? 00:00:00 /var/ossec/bin/ossec-logcollector
root 7396 1 0 10:56 ? 00:00:00 /var/ossec/bin/ossec-monitord
root 7477 1 0 10:56 ? 00:00:00 /var/ossec/bin/wazuh-modulesd

drwxr-x--- 2 root root 4096 Apr 8 10:53 .
drwxr-x--- 19 root root 4096 Apr 8 10:53 ..
-rwxr-x--x 1 root root 1025 Apr 6 16:32 custom-threatbook
-rwxr-xr-x 1 root root 8257 Apr 7 15:40 custom-threatbook.py
-rwxr-x--- 1 root root 4328 Apr 8 10:52 pagerduty
-rwxr-x--- 1 root root 1025 Apr 8 10:53 slack
-rwxr-x--- 1 root root 3814 Apr 8 10:52 slack.py
-rwxr-x--- 1 root root 1025 Apr 8 10:53 virustotal
-rwxr-x--- 1 root root 6442 Apr 8 10:52 virustotal.py

**Comment by juliancnn** [comment]
@0FuzzingQ,  

Tell me if I'm wrong, but maybe you have changed all the permissions and groups of the files in the `/var/ossec/integrations` folder?
On the other hand, the permissions of the integration script should be 750, and the ossec group.
You could try changing the group and permissions, for this you can use the following commands:

```
chmod -R 750 /var/ossec/integrations/
chown -R root:ossec /var/ossec/integrations 
```

Please let me know if this is helpful to you.

**Comment by 0FuzzingQ** [comment]
Hi @juliancnn

thanks very much , it really make sense! 
i change my file owner and permission and it runs successfully 

best regards to you

**Comment by juliancnn** [comment]
I'm glad to read that. Feel free to create new issues for new doubts!.
 I will close this issue since the problem is solved.

Have a great Friday,
Regards,
Julian
