### ISSUE TITLE
Rename cluster nodes: client -> worker

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh#813]
There are 2 types of nodes in the cluster: _master_ and _client_. It looks like the _client_ type is not appropriate since it is confused with an agent.

The new name is _worker_.

**Comment by mgmacias95** [comment]
Hello @jesuslinares,

We're already using _worker_ in the source code, to refer to the threads created to process file requests:
https://github.com/wazuh/wazuh/blob/2454f1c43cebd6d607b5be0ac1750288cc721cc9/framework/wazuh/cluster/communication.py#L163-L164
https://github.com/wazuh/wazuh/blob/2454f1c43cebd6d607b5be0ac1750288cc721cc9/framework/wazuh/cluster/communication.py#L173-L190
https://github.com/wazuh/wazuh/blob/2454f1c43cebd6d607b5be0ac1750288cc721cc9/framework/wazuh/cluster/communication.py#L195-L216
https://github.com/wazuh/wazuh/blob/2999bfcda65842959bc6e6c8534ccc239b1b41cd/framework/wazuh/cluster/master.py#L61

I think we can rename those internal threads to _thread\_worker_. 

Best regards,
Marta
