### ISSUE TITLE
Support only-future-event  for os_log format (ULS)

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh#8138]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | wazuh-logcollector | Agent | - | macOS Sierra or greater |

Hi Team!,

As part of the epic #4572 and related to #8130 and  #3368, it is necessary add support for [past events ](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/localfile.html#only-future-events). 

The events generated while Wazuh-Logcollector was stopped will be collected with the execution of the `log` command-line tool.

The connection to ULS will be with the execution of the `log` command-line tool, with the respective configuration.

Regards,
Julian

**Comment by jnasselle** [comment]
Closed by #8455
