### ISSUE TITLE
Agent not sending vulnerability data I think

### ISSUE THREAD

**Issue by michaelvanderbeek** [wazuh/wazuh#8139]
Hi Everyone,

Version : both agent and manager wazuh 4.1.4
Both agent and manager running centos 7.9
I just installed them last week.. to test. via the all-in-one method.
curl -so ~/all-in-one-installation.sh https://raw.githubusercontent.com/wazuh/wazuh-documentation/4.1/resources/open-distro/unattended-installation/all-in-one-installation.sh && bash ~/all-in-one-installation.sh

I'm getting this in my manager logs. I turned on the debug logs for more clarity.

2021/04/07 11:10:41 wazuh-modulesd[5321] main.c:84 at main(): DEBUG: Created new thread for the 'vulnerability-detector' module.
2021/04/07 11:10:41 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4017 at wm_vuldet_check_feed(): INFO: (5400): Starting 'National Vulnerability Database' database update.
2021/04/07 11:10:41 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2010' of the vulnerability database.
2021/04/07 11:10:42 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2011' of the vulnerability database.
2021/04/07 11:10:44 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2012' of the vulnerability database.
2021/04/07 11:10:45 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2013' of the vulnerability database.
2021/04/07 11:10:46 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2014' of the vulnerability database.
2021/04/07 11:10:47 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2015' of the vulnerability database.
2021/04/07 11:10:48 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2016' of the vulnerability database.
2021/04/07 11:10:49 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2017' of the vulnerability database.
2021/04/07 11:10:50 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2018' of the vulnerability database.
2021/04/07 11:10:51 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2019' of the vulnerability database.
2021/04/07 11:10:52 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2020' of the vulnerability database.
2021/04/07 11:10:53 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2197 at wm_vuldet_update_feed(): DEBUG: (5401): Synchronizing the year '2021' of the vulnerability database.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4040 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'National Vulnerability Database' feed finished successfully.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4019 at wm_vuldet_check_feed(): DEBUG: (5400): Starting 'Wazuh CPE dictionary' database update.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:5719 at wm_vuldet_fetch_wazuh_cpe(): DEBUG: (5406): The feed 'Wazuh CPE dictionary' is in its latest version.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4042 at wm_vuldet_check_feed(): DEBUG: (5400): Starting 'Wazuh CPE dictionary' database update.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4017 at wm_vuldet_check_feed(): INFO: (5400): Starting 'Microsoft Security Update' database update.
2021/04/07 11:10:54 wazuh-modulesd:download[5321] wm_download.c:226 at wm_download_dispatch(): DEBUG: Downloading 'https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.meta' to '/var/ossec/tmp/vuln-temp'
2021/04/07 11:10:54 wazuh-modulesd:download[5321] wm_download.c:246 at wm_download_dispatch(): DEBUG: Download of 'https://feed.wazuh.com/vulnerability-detector/windows/msu-updates.meta' finished.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:5565 at wm_vuldet_update_MSU(): DEBUG: (5406): The feed 'Microsoft Security Update' is in its latest version.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:4040 at wm_vuldet_check_feed(): INFO: (5430): The update of the 'Microsoft Security Update' feed finished successfully.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:7024 at wm_vuldet_run_scan(): INFO: (5431): Starting vulnerability scan.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2078 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '000' vulnerabilities.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2087 at wm_vuldet_check_agent_vulnerabilities(): WARNING: (5575): Unavailable vulnerability data for the agent '000' OS. Skipping it.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2078 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '001' vulnerabilities.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2087 at wm_vuldet_check_agent_vulnerabilities(): WARNING: (5575): Unavailable vulnerability data for the agent '001' OS. Skipping it.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2078 at wm_vuldet_check_agent_vulnerabilities(): INFO: (5450): Analyzing agent '002' vulnerabilities.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:2087 at wm_vuldet_check_agent_vulnerabilities(): WARNING: (5575): Unavailable vulnerability data for the agent '002' OS. Skipping it.
2021/04/07 11:10:54 wazuh-modulesd:vulnerability-detector[5321] wm_vuln_detector.c:7038 at wm_vuldet_run_scan(): INFO: (5472): Vulnerability scan finished.

In my agent config.

`  <!-- System inventory -->`
`  <wodle name="syscollector">`
`   <disabled>no</disabled>`
`  <interval>1h</interval>`
`   <scan_on_start>yes</scan_on_start>`
`   <hardware>yes</hardware>`
`    <os>yes</os>`
`    <network>yes</network>`
`    <packages>yes</packages>`
`    <ports all="no">yes</ports>`
`    <processes>yes</processes>`
`  </wodle>`

In my manager

`   <wodle name="syscollector">`
`     <disabled>no</disabled>
`     <interval>1h</interval>
`     <scan_on_start>yes</scan_on_start>`
`     <hardware>yes</hardware>`
`     <os>yes</os>`
`     <network>yes</network>`
`     <packages>yes</packages>`
`     <ports all="no">yes</ports>`
`     <processes>yes</processes>`
`   </wodle>`

`   <vulnerability-detector>`
`    <enabled>yes</enabled>`
`     <interval>5m</interval>`
`     <ignore_time>6h</ignore_time>`
`     <run_on_start>yes</run_on_start>`
 
    
    <provider name="canonical">
      <enabled>no</enabled>
      <os>trusty</os>
      <os>xenial</os>
      <os>bionic</os>
      <os>focal</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="debian">
      <enabled>no</enabled>
      <os>stretch</os>
      <os>buster</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="redhat">
      <enabled>no</enabled>
      <os>5</os>
      <os>6</os>
      <os>7</os>
      <os>8</os>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="msu">
      <enabled>yes</enabled>
      <update_interval>1h</update_interval>
    </provider>

    
    <provider name="nvd">
      <enabled>yes</enabled>
      <update_from_year>2010</update_from_year>
      <update_interval>1h</update_interval>
    </provider>

  </vulnerability-detector>

From what I can tell, the manager is successful in downloading the vulnerability databases.
But I think some how the agent is not sending package data (rpms) for the manager to evaluate.

Can anybody give me a direction of what to check?

Man..the block quoting is a bit strange for me writing this.

Thanks!

Regards,

Michael

**Comment by michaelvanderbeek** [comment]
More information
So the agents are sending the rpms from the agent.

[root@wazuh logs]# sqlite3 /var/ossec/queue/db/002.db 'select * from sys_programs;' -header | head
scan_id|scan_time|format|name|priority|section|size|vendor|install_time|version|architecture|multiarch|source|description|location|triaged|cpe|msu_name
23909155|2021/04/07 12:56:45|rpm|boost-regex||System Environment/Libraries|2072|CentOS|2018/08/03 12:38:28|1.53.0-27.el7|x86_64||boost-1.53.0-27.el7.src.rpm|Run-Time component of boost regular expression library||0||
23909155|2021/04/07 12:56:45|rpm|httpd||System Environment/Daemons|9587|CentOS|2019/07/03 11:15:10|2.4.6-89.el7.centos|x86_64||httpd-2.4.6-89.el7.centos.src.rpm|Apache HTTP Server||0||
23909155|2021/04/07 12:56:45|rpm|boost-atomic||System Environment/Libraries|8|CentOS|2018/08/03 12:38:29|1.53.0-27.el7|x86_64||boost-1.53.0-27.el7.src.rpm|Run-Time component of boost atomic library||0||
23909155|2021/04/07 12:56:45|rpm|biosdevname||System Environment/Base|57|CentOS|2018/06/28 16:07:46|0.7.3-1.el7|x86_64||biosdevname-0.7.3-1.el7.src.rpm|Udev helper for naming devices per BIOS names||0||
23909155|2021/04/07 12:56:45|rpm|NetworkManager-libnm||Development/Libraries|6679|CentOS|2019/07/03 11:15:13|1:1.12.0-10.el7_6|x86_64||NetworkManager-1.12.0-10.el7_6.src.rpm|Libraries for adding NetworkManager support to applications (new API).||0||
23909155|2021/04/07 12:56:45|rpm|antnfm-cmds||ANTlabs/Libraries|20|ANTlabs (www.antlabs.com)|2018/07/02 16:56:44|0.3.0-1.el7|x86_64||antnfm-0.3.0-1.el7.src.rpm|Library files and userspace utilties for antnfm||0||
23909155|2021/04/07 12:56:45|rpm|basesystem||System Environment/Base|0|CentOS|2018/06/28 15:56:14|10.0-7.el7.centos|noarch||basesystem-10.0-7.el7.centos.src.rpm|The skeleton package which defines a simple CentOS Linux system||0||
23909155|2021/04/07 12:56:45|rpm|boost||System Environment/Libraries|1|CentOS|2018/08/03 12:38:29|1.53.0-27.el7|x86_64||boost-1.53.0-27.el7.src.rpm|The free peer-reviewed portable C++ source libraries||0||
23909155|2021/04/07 12:56:45|rpm|btrfs-progs||System Environment/Base|4045|CentOS|2018/06/28 16:07:51|4.9.1-1.el7|x86_64||btrfs-progs-4.9.1-1.el7.src.rpm|Userspace programs for btrfs||0||

**Comment by Selutario** [comment]
Hi @michaelvanderbeek!

I see you have CentOS agents (which belong to Redhat). However, your redhat vulnerability feed is not enabled: 
```
<!-- RedHat OS vulnerabilities -->
<provider name="redhat">
  <enabled>no</enabled>
  <os>5</os>
  <os>6</os>
  <os>7</os>
  <os>8</os>
  <update_interval>1h</update_interval>
</provider>
```

Try activating it and restarting your manager to see if that fixes the problem. Let me know otherwise.

In case you need it, here is the full documentation for the vulnerability detection capability:
https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html

Regards!
Selu.

**Comment by michaelvanderbeek** [comment]
Wow.. I'm so blind!

Thanks for your help Selu!
