### ISSUE TITLE
Build failure when building with ZeroMQ

### ISSUE THREAD

**Issue by arshad01** [wazuh/wazuh#8141]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.1.4 | analysisd | Manager/local | install.sh | CentOS 7 |

CZMQ version 2.2.0, ZeroMQ version 3.2.5

Steps to reproduce:

```
$ make deps
$ make USE_ZEROMQ=yes TARGET=local
....
    CC analysisd/output/zeromq.o
analysisd/output/zeromq.c: In function ‘zeromq_output_event’:
analysisd/output/zeromq.c:115:5: error: too few arguments to function ‘Eventinfo_to_jsonstr’
     char *json_alert = Eventinfo_to_jsonstr(lf);
     ^
In file included from analysisd/output/zeromq.c:17:0:
./analysisd/format/to_json.h:17:7: note: declared here
 char *Eventinfo_to_jsonstr(const Eventinfo *lf, bool force_full_log);
       ^
make[1]: *** [analysisd/output/zeromq.o] Error 1
```

**Comment by juliancnn** [comment]
Hi @arshad01,

Thank you very much for reporting this to us.
You are right, we will try to fix it as soon as possible.
You can see the progress of this in this issue.

And again, thank you!

Regards,
Julian

**Comment by arshad01** [comment]
Hi @juliancnn 
Thanks for fixing the issue.
One question:
I looked at the PR and I see that now a value of 'false' is being passed for 'force_full_log' param. From the code it seems that this param controls whether the 'full_log' will be put in the json. Is it possible we can make it 'true' since 'full_log' was historically always present. I may be wrong here, but could you please reconsider.? Or if there is another way to get full_log in json through configuration/rule, please let me know.
Thanks

**Comment by juliancnn** [comment]
Hi @arshad01,

Don't worry, the ZeroMQ output will be the same as in `alert.json`. The parameter to force full log output is only used to force the `full_log` in the `archive.json` file.
The full log will not appear only if it is explicitly configured not to be stored in the rule.
That is, if the rule has the [option no_full_log](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#options) configured, then, only for the events that coincide with this rule, the full_log will not be stored.

Regards,
Julian

**Comment by arshad01** [comment]
Great! Thanks @juliancnn
