### ISSUE TITLE
Create a command to set os_info as triaged

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8165]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we are implementing a mechanism to have an inventory of vulnerabilities that affect the endpoints where the Wazuh agents are installed. Having said that, a new command is required to set the triaged status of os_info after the OS data is obtained.

### Requirements

- Create a command that will set the triaged status on os_info.
- Adapt the main scan flow to use this command.
- Create unit test cases to cover all new methods.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8177 was merged.
