### ISSUE TITLE
Save the Vulnerability Detector feed last_update in the DB

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8166]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we are implementing a mechanism to have an inventory of vulnerabilities that affect the endpoints where the Wazuh agents are installed. Having said that, the full scan is now only generated if the feed related to the agent was updated (and if a min_full_scan_interval elapsed). Actually, the feed structure isn't saving in disk (DB) the last update time, when the vulnerability detector sets this value with the actual time.
It will be a good improvement to save the last scan in the feed database to have a real interpretation of the feed update even if Wazuh restarts.

### Requirements

- Create a new entry in the feed metadata table.
- Create a command to read and set this value.
- Adapt the current feed update mechanism.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8213 was merged.
