### ISSUE TITLE
unable to install elasticsearch using the unattended installer

### ISSUE THREAD

**Issue by jhjacobs81** [wazuh/wazuh#8172]
Debian 10 clean install / Ubuntu 21.04 clean install

I was unable to install wazuh using the unattended installer as per: https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/unattended-installation.html

After removing the debug line first in the script, i noticed it was complaining about gnupg, gnupg1 or gnupg2 not beeing installed. after installing gnupg2 the unattended script worked correctly. 

Maybe this should be included in the script?
i used both a debian 10 clean install, and an ubuntu 21.4 clean install.

**Comment by MiguelazoDS** [comment]
Hello @jhjacobs81, 

Sorry for the late response, according to the date you opened this thread I assume that your version is 4.1.4 or older and I was not able to reproduce this on Debian Buster. 
I tested on a fresh VM without installing anything prior to the unattended installer script. The gpg package is usually part of the utils of other tools like the package manager. I found it was installed as part of apt-utils. 
I wonder if you performed some kind of package deletion before attempting to do this.
In case I missing some and this is correct I can suggest this. 

Regards!
