### ISSUE TITLE
Remove frequency option offset for rules

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#818]
The option `frequency` for rules based on time frame have a +2 offset:

- `frequency="0"` means that a rule must match twice.
- `frequency="1"` means that a rule must match three times.

Fix this case and make this option more coherent.

If this option does not accept values under `0` currently, it should not accept values under `2` after applying this patch.

**Comment by chemamartinez** [comment]
Done: https://github.com/wazuh/wazuh/pull/827
