### ISSUE TITLE
Investigate to delete deprecated HOTFIX_SCAN_ID

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8180]
Description
As part of the epic #7749, we are implementing a mechanism to have an inventory of vulnerabilities that affect the endpoints where the Wazuh agents are installed. During the new scan logic, it was found that **HOTFIX_SCAN_ID** is a deprecated column of **vuln_metadata** table and it is not required in the new scan logic.
Thus, a complete investigation to verify this is required. 
Additionally, this column and all its references should be eliminated.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8195 was merged.
