### ISSUE TITLE
Segmentation Fault running modulesd with an invalid custom feed for Arch Linux (vulnerability detector)

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh#8187]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.0 | Modulesd | Manager | Sources | Tested on Ubuntu Focal|

We're writing integration tests for the new Arch Linux support on Vulnerability Detector, as part of https://github.com/wazuh/wazuh-qa/issues/1119

We've detected that, if using a custom feed with any vulnerability without the 'issues' field, modulesd fails to start.

We've been debugging this with GDB and we've detected a segmentation fault.

![image](https://user-images.githubusercontent.com/15269938/114412787-b566e900-9bad-11eb-8e84-8b58dd09baa8.png)

# Steps to reproduce

- This have been tested on branch `7767-archlinux-support-vd-test` with commit `11f7bab0c109d5c28b87047b90dc4482c8f7c6c4`. Download and install it.

- Add this configuration for vulnerability detector :

```
<vulnerability-detector>
  <enabled>yes</enabled>
    <run_on_start>yes</run_on_start>
    <provider name="arch"><enabled>yes</enabled>
    <path>/tmp/custom_arch_feed.json</path>
  </provider>
  </vulnerability-detector>
```

- And use the following feed: https://gist.github.com/spothound/0109124c9142e61c81d35bea08be4349
- Try to start modulesd.

**Comment by alromeros** [comment]
**Fix committed in devel branch:** https://github.com/wazuh/wazuh/tree/7075-arch-linux-support
