### ISSUE TITLE
Fix error messages in rootcheck

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#819]
Syscheck and Rootcheck are enabled by default. This means that if no `<syscheck>` or `<rootcheck`> sections are defined in the configuration (_ossec.conf_ or _agent.conf_), Syscheck and Rootcheck will be enabled.

If Syscheck or Rootcheck are disabled, the application logs a warning:

```
2018/06/20 11:14:34 ossec-syscheckd: WARNING: Syscheck disabled.
2018/06/20 11:14:34 rootcheck: INFO: Rootcheck disabled. Exiting.
2018/06/20 11:14:34 ossec-syscheckd: WARNING: Rootcheck module disabled.
```

This should be an "INFO" message.

On the other hand, if Rootcheck is —implicitly or explicitly— enabled, it will try to find the rootcheck files in the configuration. 

```
2018/06/20 11:18:28 rootcheck: INFO: No rootcheck_files file configured.
2018/06/20 11:18:28 rootcheck: INFO: No rootcheck_trojans file configured.
```

If it does not find those files it will log an error:

```
2018/06/20 11:17:04 rootcheck: ERROR: No rootcheck_files file: '/var/ossec/etc/rootcheck/rootkit_files.txt'
2018/06/20 11:17:04 rootcheck: ERROR: No rootcheck_trojans file: '/var/ossec/etc/rootcheck/rootkit_trojans.txt'
2018/06/20 11:17:08 rootcheck: ERROR: No unixaudit file: '/var/ossec/etc/rootcheck/system_audit_rcl.txt'
2018/06/20 11:17:08 rootcheck: ERROR: No unixaudit file: '/var/ossec/etc/rootcheck/system_audit_ssh.txt'
2018/06/20 11:17:08 rootcheck: ERROR: No unixaudit file: '/var/ossec/etc/rootcheck/cis_debian_linux_rcl.txt'
```

## Proposed changes

1. If `<rootcheck>` is not defined, it should be disabled by default.
2. If `<rootcheck>` is defined but `<disabled>` is not specified, it should be enabled by default.
3. If those options:
```xml 
<check_files>no</check_files>
<check_trojans>no</check_trojans>
```
are not defined, they should be disabled by default.

4. If the options above are defined but the next options:
```xml
<rootkit_files>/var/ossec/etc/rootcheck/rootkit_files.txt</rootkit_files>
<rootkit_trojans>/var/ossec/etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>
```
are not defined, the application should print an error:
```
2018/06/20 11:18:28 rootcheck: ERROR: No rootcheck_files file configured.
2018/06/20 11:18:28 rootcheck: ERROR: No rootcheck_trojans file configured.
```

**Comment by chemamartinez** [comment]
Done: https://github.com/wazuh/wazuh/pull/829
