### ISSUE TITLE
Remove alert_by_email option

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh#8191]
Hi team, 

it has been brought to our attention, that certain rules still have the `alert_by_email` option enabled. 

These rules are the following: 

* 19123
* 31412
* 31413
* 31421
* 31430
* 60119
* 60611
* 60612
* 62616
* 63616

Additional info can be seen in the following image:

![image (36)](https://user-images.githubusercontent.com/4438081/114458497-908b6980-9bdf-11eb-95ea-39fb4d213e42.png)

This option should be completely removed. When users enable email alerting and set their own parameters, they keep receiving emails for these rules and are forced to manually override the option if they don't want to receive them. It should be the other way round if a user wants to receive an email, they can configure it, not be forced to receive lots of emails they may not want with the default ruleset.

**Comment by Nekaze** [comment]
Hello @mikykeane, I started looking at this, and noticed that there are 6 more rules that have the **alert_by_email** option enabled, and wanted to confirm if those are part of the scope of this task aswell.

The rules are:

**ossec_rules**:
- 501
- 502
- 503
- 504
- 505

**mcafee_av_rules**:
- 7514

Best regards!
