### ISSUE TITLE
recipe for target 'ossec-authd' failed

### ISSUE THREAD

**Issue by eleshar** [wazuh/wazuh#82]
I'm attempting to install on Debian Jessie following the instructions listed here: http://documentation.wazuh.com/en/latest/wazuh_installation.html#wazuh-installation but running into the following error:

```
    CC ossec-authd
os_auth/ssl.o: In function `get_ssl_context':
ssl.c:(.text+0xe2): undefined reference to `SSL_library_init'
ssl.c:(.text+0xe7): undefined reference to `SSL_load_error_strings'
ssl.c:(.text+0xec): undefined reference to `OPENSSL_add_all_algorithms_noconf'
os_auth/check_cert.o: In function `check_subject_alt_names':
check_cert.c:(.text+0x470): undefined reference to `sk_num'
check_cert.c:(.text+0x483): undefined reference to `sk_value'
check_cert.c:(.text+0x49a): undefined reference to `sk_num'
collect2: error: ld returned 1 exit status
Makefile:1033: recipe for target 'ossec-authd' failed
make: *** [ossec-authd] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
```

I've checked that I have the listed dependencies installed
```
git is already the newest version (1:2.11.0-2~bpo8+1).
make is already the newest version (4.1-9).
gcc is already the newest version (4:6.1.1-1).
libc6-dev is already the newest version (2.24-3).
libssl-dev is already the newest version (1.1.0c-1).
```

Any assistance would be greatly appreciated.

**Comment by vikman90** [comment]
Hi @eleshar,

I'm sorry we tried to reproduce your issue but it compiled without errors on Debian 8.

Nevertheless we saw a strange thing when checking the packages version:

- git: 1:2.1.4-2.1+deb8u2
- make: 4.0-8.1
- gcc: 4:4.9.2-2
- libc6-dev: 2.19-18+deb8u7
- libssl-dev: 1.0.1t-1+deb8u6

Attending to your version of git package "1:2.11.0-2~bpo8+1" I think that maybe you have enabled the Backports repository. Please make sure that you are using the stable repository.

Hope it help.
