### ISSUE TITLE
[API] Update logcollector active configuration retrieving for ULS changes

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#8209]
|Working branch| 
|---|
|[4572-dev-uls-logs-enhancement](https://github.com/wazuh/wazuh/tree/4572-dev-uls-logs-enhancement)|

|Wazuh version|Component|
|---|---|
| - | Wazuh API |

Hi team!

As explained in #4572, it is desirable that new values for options, and new attributes for some existing ones can be retrieved by API active configuration request for `wazuh-logcollector` (`GET /agents/{agent_id}/config/logcollector/localfile` and `GET /manager/configuration/logcollector/localfile` ).

### Changes

- New: `oslog` as value for `log_format` option.
- No impact : `oslog` as value for `location` option
- Changed: `query` option allows `type` (with multiples comma-separated values) and `level` attributes
#### `oslog` without `query` option
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
</localfile>
```
```json
{
  "file": "oslog",
  "logformat": "oslog",
  "ignore_binaries": "no",
  "only-future-events": "yes",
  "target": [
    "agent"
  ]
}
```
#### `oslog` with `query` option but without value and attributes
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query></query>
</localfile>
```
```json
{
  "file": "oslog",
  "logformat": "oslog",
  "ignore_binaries": "no",
  "only-future-events": "yes",
  "target": [
    "agent"
  ]
}
```
#### `oslog` with `query` option with value but without attributes
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query>predicate</query>
</localfile>
```
```json
{
  "file": "oslog",
  "logformat": "oslog",
  "ignore_binaries": "no",
  "only-future-events": "yes",
  "target": [
    "agent"
  ],
  "query": {
    "value": "predicate"
  }
}
```
#### `oslog` with `query` option with value and multiple values in `type` attribute
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query type="log,activity">predicate</query>
</localfile>
```
```json
{
  "file": "oslog",
  "logformat": "oslog",
  "ignore_binaries": "no",
  "only-future-events": "yes",
  "target": [
    "agent"
  ],
  "query": {
    "value": "predicate",
    "type": [
      "log",
      "activity"
    ]
  }
}
```
#### `oslog` with `query` option with attributes
```xml
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query type="log,activity" level="debug">predicate</query>
</localfile>
```
```json
{
  "file": "oslog",
  "logformat": "oslog",
  "ignore_binaries": "no",
  "only-future-events": "yes",
  "target": [
    "agent"
  ],
  "query": {
    "value": "predicate",
    "type": [
      "log",
      "activity"
    ],
    "level": "debug"
  }
}
```
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Selutario** [comment]
Hi @jnasselle!

It turns out that the active configuration is directly requested to 
- `wazuh_path/queue/socket/requests <agent_id> <component> getconfig <configuration>` for agents.
- `wazuh_path/queue/socket/<component> getconfig <configuration>` for managers.

A JSON is returned for said requests and the framework is only in charge of loading it and formatting the response. It is not altered in any way, except to add the password saved in authd.pass in certain cases. 

I have been testing the endpoint in your branch with all the proposed configurations and the output has been identical to the ones in your examples, except for the `file` field, which does not appear at any time. For instance:
```XML
<localfile>
  <log_format>oslog</log_format>
  <location>oslog</location>
  <query type="log,activity" level="debug">predicate</query>
</localfile>
```

Current output:
```JSON
      {
        "logformat": "oslog",
        "query": {
          "value": "predicate",
          "level": "debug",
          "type": [
            "log",
            "activity"
          ]
        },
        "ignore_binaries": "no",
        "only-future-events": "yes",
        "target": [
          "agent"
        ]
      }
```

The API reference ([link](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_agent_config)) does not mention the specific configurations of each component, so there would not be any changes to be made either. 

Let me know if you need us to change something I didn't mention. 

Best regards,
Selu.
