### ISSUE TITLE
Upgrade by sources fails to clean previous files due to an empty bash variable

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#8214]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Install/upgrade scripts| Manager | Sources | CentOS |

### Description 

It was found an issue during a source upgrade in the **WazuhUpgrade()** method (but all the mechanism should be analyzed). 

When updating a manager from 4.2 to 4.3 (`master`), the  `$DIRECTORY ` variable is empty, so the old files are not removed.

**Comment by DProvinciani** [comment]
Closing the issue, as this was fixed as part of the pull https://github.com/wazuh/wazuh/pull/7763.
