### ISSUE TITLE
Trouble building CPython on Gentoo

### ISSUE THREAD

**Issue by Dr-Dd** [wazuh/wazuh#8222]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.4 (Master branch) | CPython | Manager | Sources | 5.4.80-gentoo-r1 |

I've been trying to build wazuh on my system, but i've been having problems with building CPython.

Here are the steps to reproduce the problem:
```shell
localhost ~/wazuh-4.1.4# make -C src deps #runs successfully
localhost ~/wazuh-4.1.4# make -C src TARGET=server
```
From here on the compilation runs normally until it starts the `build_python` target, then it halts with this error which i haven't been able to debug further:

```Makefile
export WPATH_LIB="'\$\$ORIGIN/../../../lib'" && export SOURCE_PATH=/root/wazuh-4.1.4/src && \
export WAZUH_FFI_PATH=external/libffi/ && export LD_LIBRARY_PATH=/root/wazuh-4.1.4/src && \
cd external/cpython/ && ./configure --prefix="/var/ossec/framework/python" \
--libdir="/var/ossec/framework/python/lib" --enable-shared \
--with-openssl="/root/wazuh-4.1.4/src/external/openssl/" \
LDFLAGS=" -L/root/wazuh-4.1.4/src -lwazuhext -Wl,-rpath,'\$\$ORIGIN/../../../lib',--disable-new-dtags" \
CPPFLAGS="-I/root/wazuh-4.1.4/src/external/openssl/"  && make
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for python3.9... python3.9
checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... "linux"
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/root/wazuh-4.1.4/src/external/cpython':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [Makefile:1710: build_python] Error 77
make: Leaving directory '/root/wazuh-4.1.4/src'
```

**Comment by Dr-Dd** [comment]
I've tried to fix the problem since it's the same as #6189, but the option `--without-librtmp` isn't recognized by cpython's `configure` script

**Comment by pereyra-m** [comment]
Hello @Dr-Dd !

The team is working in a new feature that will allow the `make deps` command to download a pre-compiled Python executable. This will prevent this kind of issues and it will be available as soon as possible. Sorry for the inconveniences.

In the meantime, this log line may be indicating your system needs an extra package to compile CPython (`libc6-dev` for example)
```
checking whether the C compiler works... no
```

Can you upload the **config.log** ? It may have more information.

Also, check the Gentoo equivalent packages to ones listed here so we can be sure you have all the requirements installed
https://realpython.com/cpython-source-code-guide/#compiling-cpython-linux

Regards.

**Comment by Dr-Dd** [comment]
Sorry @pereyra-m for not answering promptly.

I managed to build the manager by specyfing the `LIBS` environment variable at runtime. This is mentioned in #3012.

The strange thing is, Gentoo's default Python implementation is CPython (which i already have installed), so all the dependencies should already be satisfied unless some USE flag is missing.

I'll report the bug again when writing the ebuild script for the package.

**Comment by pereyra-m** [comment]
Hi @Dr-Dd ! Not problem at all.

I'm glad you were able to solve it.
Wazuh downloads its own CPython and builds it, even if you already have it in your system.This is the expected behavior.
In the future, a pre-compiled version will be downloaded instead.

Regards.
