### ISSUE TITLE
Enrollment ping logic fails during a time window

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8227]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.0.0 | Enrollment | Agent | 

The **enrollment** feature has a mechanism to verify if **Remoted** is reachable previous requesting a new key. This is done to avoid requesting new keys if the connection fails only because **Remoted** wasn´t started or available, a scenario that is not related to the agent keys.
During the execution of **Agentd**, if the connection with the manager fails 5 times (by default, configurable) the agent first pings **Remoted** with an unencrypted message, if **Remoted** answer, **Agentd** considers that the connection with **Remoted** was failing because of a keys problem and request a new one.
But, there is a small time-window where **Remoted** can start or get reachable between the last connection attempt and the ping message. This leads to fail the connection attempts but answer the ping command, and allows the agent to request a new key even if this scenario should be blocked with the ping logic.

To avoid this scenario. An extra connection attempt could be considered right after the ping success, to eliminate this time window.
But this will always leave the possibility to receive an answer from the ping command and not from the connection attempt because of random network issues. The best approach to fully eliminate these possibilities would be to centralize the communication between agent and manager on port 1514, to handle the validation and the request in one unique command. Or, to respond to every agent connection attempt that fails because of missing keys with a representative message.

**Comment by MiguelCasaresRobles** [comment]
Hello team,

Probably, this is not directly related to this but I found the following issue with the enrollment using UDP:

- Version: 4.0.4 - Wazuh server and Wazuh agent
- Cluster environment: Wazuh master and Wazuh worker
- OS: Linux

The agent is connected using UDP and after a network failure, the agent tried to switch to the worker. Then, after 5 retries the agent gets connected by asking for a new key. Everything is under the same sub-network so I suppose the network failure was recovered before asking for the new key.

However, the expected behavior should be that the agent must connect to the worker and not ask for a new key. This is the expected behavior:

```
2021/04/30 18:02:34 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:03:44 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:03:44 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:04:54 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:04:54 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:06:55 ossec-agentd: WARNING: Polling server '192.168.56.22' failed. Skipping enrollment.
2021/04/30 18:07:05 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.56.22'.
2021/04/30 18:07:05 ossec-agentd: WARNING: Unable to connect to any server.
2021/04/30 18:07:05 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:07:05 ossec-agentd: INFO: Trying to connect to server (192.168.56.109:1514/udp).
2021/04/30 18:08:15 ossec-agentd: INFO: Closing connection to server (192.168.56.109:1514/udp).
2021/04/30 18:08:15 ossec-agentd: INFO: Trying to connect to server (192.168.56.109:1514/udp).
2021/04/30 18:09:25 ossec-agentd: INFO: Closing connection to server (192.168.56.109:1514/udp).
2021/04/30 18:09:25 ossec-agentd: INFO: Trying to connect to server (192.168.56.109:1514/udp).
2021/04/30 18:10:35 ossec-agentd: INFO: Closing connection to server (192.168.56.109:1514/udp).
2021/04/30 18:10:35 ossec-agentd: INFO: Trying to connect to server (192.168.56.109:1514/udp).
2021/04/30 18:11:45 ossec-agentd: INFO: Closing connection to server (192.168.56.109:1514/udp).
2021/04/30 18:11:45 ossec-agentd: INFO: Trying to connect to server (192.168.56.109:1514/udp).
2021/04/30 18:13:45 ossec-agentd: WARNING: Polling server '192.168.56.109' failed. Skipping enrollment.
2021/04/30 18:13:55 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.56.109'.
2021/04/30 18:13:55 ossec-agentd: INFO: Trying next server ip in the line: '192.168.56.22'.
2021/04/30 18:13:55 ossec-agentd: INFO: Closing connection to server (192.168.56.109:1514/udp).
2021/04/30 18:13:55 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:15:05 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:15:05 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:16:15 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:16:15 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:17:25 ossec-agentd: INFO: Closing connection to server (192.168.56.22:1514/udp).
2021/04/30 18:17:25 ossec-agentd: INFO: Trying to connect to server (192.168.56.22:1514/udp).
2021/04/30 18:17:25 ossec-agentd: INFO: (4102): Connected to the server (192.168.56.22:1514/udp).

```

This is what happened:

```
2021/04/27 01:14:32 ossec-agent: WARNING: Polling server 'x.x.x.1' failed. Skipping enrollment.
2021/04/27 01:14:42 ossec-agent: WARNING: (4101): Waiting for server reply (not started). Tried: 'x.x.x.1'.
2021/04/27 01:14:42 ossec-agent: INFO: Trying next server ip in the line: 'x.x.x.2.
2021/04/27 01:14:42 ossec-agent: INFO: Closing connection to server (x.x.x.1:1514/udp).
2021/04/27 01:14:42 ossec-agent: INFO: Trying to connect to server (x.x.x.2:1514/udp).
2021/04/27 01:15:53 ossec-agent: INFO: Closing connection to server (x.x.x.2:1514/udp).
2021/04/27 01:15:53 ossec-agent: INFO: Trying to connect to server (x.x.x.2:1514/udp).
2021/04/27 01:17:03 ossec-agent: INFO: Closing connection to server (x.x.x.2:1514/udp).
2021/04/27 01:17:03 ossec-agent: INFO: Trying to connect to server (x.x.x.2:1514/udp).
2021/04/27 01:18:13 ossec-agent: INFO: Closing connection to server (x.x.x.2:1514/udp).
2021/04/27 01:18:13 ossec-agent: INFO: Trying to connect to server (x.x.x.2:1514/udp).
2021/04/27 01:19:23 ossec-agent: INFO: Closing connection to server (x.x.x.2:1514/udp).
2021/04/27 01:19:23 ossec-agent: INFO: Trying to connect to server (x.x.x.2:1514/udp).
2021/04/27 01:20:23 ossec-agent: INFO: Requesting a key from server: x.x.x.2
2021/04/27 01:20:23 ossec-agent: INFO: No authentication password provided
2021/04/27 01:20:23 ossec-agent: INFO: Using agent name as: agent2
2021/04/27 01:20:23 ossec-agent: INFO: Waiting for server reply
2021/04/27 01:20:23 ossec-agent: INFO: Valid key received
2021/04/27 01:20:23 ossec-agent: INFO: Waiting 20 seconds before server connection
```

**Comment by palaciosjeremias** [comment]
### Fix proposals:
- Modify the default value of the force option:
Changing force_time to a value greater than the notify_time of the agent makes no key request to remove an agent active in the manager. It will only remove disconnected agents.
Note: Since the agent's connection status is saved in global.db, this force option could be improved to not work with the antiquity of the agent and a time, it can work using the connection status of the agent agents that is more clear.
This is a very small change without error risk. But it only works if the manager and the agents are actively running and communicating.
This proposal doesn´t fix the scenario of a manager restart, where remoted fails to respond to the connection attempts due to being starting because the last keep alive of the agent is outdated.
Note2: This proposal is also covered [here](https://github.com/wazuh/wazuh/issues/8940)

- Use the controlled connection in TCP to identify when the connection attempt fails because of a network problem instead of a key issue.
With TCP protocol, a network problem can be identified by an invalid connection with the manager or with a timeout error waiting for a response. On the other hand, if the manager actively rejects the connection because the keys are invalid, this socket close can be identified on the agent side and use to trigger an enrollment.
This is a small change. But it will only work with TCP protocol and has a medium risk of errors because of the possibility of non considered scenarios as having an intermediate network handler as a Load Balancer.

**Comment by DProvinciani** [comment]
Considering the next epics that were implemented:

- https://github.com/wazuh/wazuh/issues/9549
- https://github.com/wazuh/wazuh/issues/9550

And the fact that the improvements in the protocol require extra analysis and will be implemented as part of another epic. We close this issue.
