### ISSUE TITLE
Investigate and test GitHub API

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8271]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all GitHub logs using its API:

> GET /orgs/{org}/audit-log

The purpose of this issue is to investigate this API and make some testing in C languaje to retrieve logs from it.

GitHub API description can be found [here](https://docs.github.com/en/rest/reference/orgs#get-the-audit-log-for-an-organization).

**Comment by javabalm** [comment]
Pagination:

- per_page: Results per page (max 100).
- page: number of the results to fetch.

Example:
```
curl -H "Authorization: token XXXXXX" https://api.github.com/orgs/14dias/audit-log?per_page=2&page=1

[
  {
    "actor": "javabalm",
    "@timestamp": 1618924225846,
    "org": "14dias",
    "created_at": 1618924225846,
    "action": "org.invite_member",
    "actor_location": {
      "country_code": "AR"
    },
    "user": "TomasTurina",
    "_document_id": "Eqz536lDJek9Gb1MLfuRZQ"
  },
  {
    "actor": "javabalm",
    "@timestamp": 1618924213370,
    "org": "14dias",
    "created_at": 1618924213370,
    "action": "org.cancel_invitation",
    "actor_location": {
      "country_code": "AR"
    },
    "user": "TomasTurina",
    "_document_id": "uPHan7OEktlt7jKvVP3H9Q"
  }
]
```

**Comment by javabalm** [comment]
Query for dates:

You can search for dates that are earlier or later than another date,  by using >, >=, <, <=. Date formatting must follow the ISO8601 standard, which is YYYY-MM-DD (year-month-day) or you can also add optional time information THH:MM:SS+00:00.

Example: 

`curl -H "Authorization: token XXXXX" 'https://api.github.com/orgs/14dias/audit-log?phrase=created:>=2021-04-21T15:18:34+00:00'`

**Comment by Nicogp** [comment]
Authorization:
It is possible to access the API audit-log endpoint through a token, this token must have set admin:org->read:org permission.

**Comment by javabalm** [comment]
As I already said, the date format must follow the ISO8601 standard for the query, which means that the program must convert the Epoch time format from @timestamp to ISO8601 for the query.

Example:
https://www.epochconverter.com/programming/c
