### ISSUE TITLE
Analyze and classify GitHub audit-logs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8272]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all GitHub logs using its API:

> GET /orgs/{org}/audit-log

The purpose of this issue is to analyze all the logs that this API endpoint retrieves and classify them, so later this classification can be used to create rules.

GitHub audit-logs description can be found [here](https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#audit-log-actions).

**Comment by cborla** [comment]
Following list represent different GitHub events that could be collected through REST API.
Each title represent a group and each sub item an action, that conform the event action field.

Sample:  "action": "org.invite_member", 
In above case the group is "org" and the action "invite_member"

Groups and actions

# account
	billing_plan_change
	plan_change
	pending_plan_change
	pending_subscription_change

# advisory_credit
	accept
	create
	decline
	destroy

# billing
	change_billing_type
	change_email

# dependabot_alerts
	disable
	enable

# dependabot_alerts_new_repos
	disable
	enable

# dependabot_security_updates
	disable
	enable

# dependabot_security_updates_new_repos
	disable
	enable

# dependency_graph
	disable
	enable

# dependency_graph_new_repos
	disable
	enable

# discussion_post
	update
	destroy

# discussion_post_reply
	update
	destroy

# enterprise
	remove_self_hosted_runner
	register_self_hosted_runner
	runner_group_created
	runner_group_removed
	runner_group_runner_removed
	runner_group_runners_added
	runner_group_runners_updated
	runner_group_updated
	self_hosted_runner_updated

# environment
	create_actions_secret
	delete
	remove_actions_secret
	update_actions_secret

# git
	clone
	fetch
	push

# hook
	create
	config_changed
	destroy
	events_changed

# integration_installation_request
	create
	close

# issue
	destroy

# marketplace_agreement_signature
	create

# marketplace_listing
	approve
	create
	delist
	redraft
	reject

# members_can_create_pages
	enable
	disable

# org
	advanced_security_policy_selected_member_disabled
	advanced_security_policy_selected_member_enabled
	audit_log_export
	block_user
	cancel_invitation
	create_actions_secret
	disable_oauth_app_restrictions
	disable_saml
	disable_member_team_creation_permission
	disable_two_factor_requirement
	enable_oauth_app_restrictions
	enable_saml
	enable_member_team_creation_permission
	enable_two_factor_requirement
	invite_member
	oauth_app_access_approved
	oauth_app_access_denied
	oauth_app_access_requested
	register_self_hosted_runner
	remove_actions_secret
	remove_billing_manager
	remove_member
	remove_outside_collaborator
	remove_self_hosted_runner
	revoke_external_identity
	revoke_sso_session
	runner_group_created
	runner_group_removed
	runner_group_updated
	runner_group_runners_added
	runner_group_runner_removed
	runner_group_runners_updated
	self_hosted_runner_updated
	unblock_user
	update_actions_secret
	update_new_repository_default_branch_setting
	update_default_repository_permission
	update_member
	update_member_repository_creation_permission
	update_saml_provider_settings
	update_terms_of_service

# org_credential_authorization
	grant
	deauthorized
	revoke

# organization_label
	create
	update
	destroy

# oauth_application
	create
	destroy
	reset_secret
	revoke_tokens
	transfer

# packages
	package_version_published
	package_version_deleted
	package_deleted
	package_version_restored
	package_restored

# payment_method
	clear
	create
	update

# profile_picture
	update

# project
	create
	link
	rename
	update
	delete
	unlink
	update_org_permission
	update_team_permission
	update_user_permission

# protected_branch
	create
	destroy
	update_admin_enforced
	update_require_code_owner_review
	dismiss_stale_reviews
	update_signature_requirement_enforcement_level
	update_pull_request_reviews_enforcement_level
	update_required_status_checks_enforcement_level
	update_strict_required_status_checks_policy
	rejected_ref_update
	policy_override
	update_allow_force_pushes_enforcement_level
	update_allow_deletions_enforcement_level
	update_linear_history_requirement_enforcement_level

# pull_request
	create
	close
	reopen
	merge
	indirect_merge
	ready_for_review
	converted_to_draft
	create_review_request
	remove_review_request

# pull_request_review
	submit
	dismiss
	delete

# pull_request_review_comment
	create
	update
	delete

# repo
	access
	actions_enabled
	add_member
	add_topic
	advanced_security_disabled
	advanced_security_enabled
	archived
	create
	create_actions_secret
	destroy
	disable
	enable
	remove_actions_secret
	remove_member
	register_self_hosted_runner
	remove_self_hosted_runner
	remove_topic
	rename
	self_hosted_runner_updated
	transfer
	transfer_start
	unarchived
	update_actions_secret

# repository_advisory
	close
	cve_request
	github_broadcast
	github_withdraw
	open
	publish
	reopen
	update

# repository_content_analysis
	enable
	disable

# repository_dependency_graph
	disable
	enable

# repository_secret_scanning
	disable
	enable

# repository_vulnerability_alert
	create
	dismiss
	resolve

# repository_vulnerability_alerts
	authorized_users_teams
	disable
	enable

# secret_scanning
	disable
	enable

# secret_scanning_new_repos
	disable
	enable

# sponsors
	custom_amount_settings_change
	repo_funding_links_file_action
	sponsor_sponsorship_cancel
	sponsor_sponsorship_create
	sponsor_sponsorship_preference_change
	sponsor_sponsorship_tier_change
	sponsored_developer_approve
	sponsored_developer_create
	sponsored_developer_disable
	sponsored_developer_redraft
	sponsored_developer_profile_update
	sponsored_developer_request_approval
	sponsored_developer_tier_description_update
	sponsored_developer_update_newsletter_send
	waitlist_invite_sponsored_developer
	waitlist_join

# team
	add_member
	add_repository
	change_parent_team
	change_privacy
	create
	demote_maintainer
	destroy
	team.promote_maintainer
	remove_member
	remove_repository

# team_discussions
	disable
	enable

# workflows
	cancel_workflow_run
	completed_workflow_run
	created_workflow_run
	delete_workflow_run
	disable_workflow
	enable_workflow
	rerun_workflow_run
	prepared_workflow_job

**Comment by cborla** [comment]
Sample Logs

[Sample_Logs.txt](https://github.com/wazuh/wazuh/files/6358926/Sample_Logs.txt)
