### ISSUE TITLE
Rules for GitHub audit-logs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8279]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all GitHub logs.

The main goal of this issue is to create some rules for the GitHub audit-logs, which are in JSON format.

As part of this issue, it is also necessary to verify that alerts are generated when these events reach the manager.

**Comment by cborla** [comment]
[UniqueSampleJson.txt](https://github.com/wazuh/wazuh/files/6387507/UniqueSampleJson.txt)
Added some sample Json events.

**Comment by cborla** [comment]
[UniqueSampleJson.txt](https://github.com/wazuh/wazuh/files/6393565/UniqueSampleJson.txt)
Sample logs with field **"source":"github"**

**Comment by cborla** [comment]
Sample logs for dual categories


issues or issue

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issue.test","user":"User-1","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issues.test","user":"User-1","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issue.deletes_enabled","user":"User-1","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issues.deletes_enabled","user":"User-1","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issue.destroy","user":"User-1","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"issues.destroy","user":"User-1","source":"github"},


organization_default_label or organization_label

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_default_label.hola","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_label.hola","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_default_label.create","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_label.create","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_default_label.update","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_label.update","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_default_label.destroy","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"organization_label.destroy","source":"github"},


integration_installation_request or integration_installation

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation.test","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation_request.test","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation.create","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation_request.create","source":"github"},

{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation.close","source":"github"},
{"actor":"User-1","org":"14dias","created_at":1619032221869,"action":"integration_installation_request.close","source":"github"},

**Comment by cborla** [comment]
[CustomizedSampleLogs.txt](https://github.com/wazuh/wazuh/files/6395020/CustomizedSampleLogs.txt)

Homemade samples logs, one sample log per rule.
