### ISSUE TITLE
[development] Windows agent stops working after multiple errors (Syscollector/DBSync related)

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#8283]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.2.0-rc3 | remoted/agentd | Agent | Packages | Windows Server |

Hello team,

After review the stress tests I have seen that the Windows agent stops working after a short time. The logs don't keep clear the main problem (anyway I will attach them at the end of this issue).

Here you can see the charts obtained from the agent:
### RSS
![image](https://user-images.githubusercontent.com/10661307/115386133-4e62b900-a1d9-11eb-8e78-ccd965fff4e5.png)

### CPU
![image](https://user-images.githubusercontent.com/10661307/115386169-5884b780-a1d9-11eb-8484-31653bd70ffb.png)

### Agent configuration
[ossec.conf.txt](https://github.com/wazuh/wazuh/files/6343010/ossec.conf.txt)

### Agent complete log (Debug=0)
[ossec.log.txt](https://github.com/wazuh/wazuh/files/6343017/ossec.log.txt)

Some relevant errors that we saw inside logs:
`wazuh-agent: ERROR: Could not EvtSubscribe() for (Forwarded Events) which returned (15007)`
`wazuh-modulesd:syscollector: ERROR: {...JSON_DATA...}`

### Additional information from windows event viewer
General information:
```
Faulting application name: wazuh-agent.exe, version: 0.0.0.0, time stamp: 0x607d4118
Faulting module name: dbsync.dll, version: 0.0.0.0, time stamp: 0x607d411c
Exception code: 0x40000015
Fault offset: 0x000560f6
Faulting process id: 0x1734
Faulting application start time: 0x01d735ccd570de7a
Faulting application path: C:\Program Files (x86)\ossec-agent\wazuh-agent.exe
Faulting module path: C:\Program Files (x86)\ossec-agent\dbsync.dll
Report Id: 8937cf25-f035-43d7-ab04-8f9c42678b5c
Faulting package full name: 
Faulting package-relative application ID: 
```

Description
![image](https://user-images.githubusercontent.com/10661307/115391469-cd5af000-a1df-11eb-8973-6e4c29bf4cbd.png)

Error event XML
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2021-04-20T10:18:24.469290500Z" /> 
  <EventRecordID>12921</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>EC2AMAZ-NRK2S46</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>wazuh-agent.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>607d4118</Data> 
  <Data>dbsync.dll</Data> 
  <Data>0.0.0.0</Data> 
  <Data>607d411c</Data> 
  <Data>40000015</Data> 
  <Data>000560f6</Data> 
  <Data>1734</Data> 
  <Data>01d735ccd570de7a</Data> 
  <Data>C:\Program Files (x86)\ossec-agent\wazuh-agent.exe</Data> 
  <Data>C:\Program Files (x86)\ossec-agent\dbsync.dll</Data> 
  <Data>8937cf25-f035-43d7-ab04-8f9c42678b5c</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

After manual tests disabling Syscollector seems to avoid the mentioned error. We could assure that Syscollector is giving the error.

**Comment by Dwordcito** [comment]
RCA:
1- Memory leak: 
Two snapshots were made, the first one just started the process.
The second one at 30 minutes of execution. 

```
+ 43761632 ( 43761632 -      0)  35417 allocs	BackTrace313D2E4
+   35417 (  35417 -      0)	BackTrace313D2E4	allocations

	ntdll!RtlValidateProcessHeaps+249
	ntdll!LdrSetAppCompatDllRedirectionCallback+F52D
	ntdll!RtlAllocateHeap+32
	msvcrt!malloc+90
	msvcrt!mbsdup+29
	wazuh-agent!receiver_thread+572 (client-agent\receiver-win.c, 144)
	KERNEL32!BaseThreadInitThunk+24
	ntdll!RtlSubscribeWnfStateChangeNotification+439
	ntdll!RtlSubscribeWnfStateChangeNotification+404
```

as you can see from what is described, 35417 allocations are made, and none are ever released.
the result after the analysis is that the allocation with strdup that is done here is never released, 
in these 30 minutes of stress test we have unavoidably allocates equivalents to ~41 mbs with +ust mode.

https://github.com/wazuh/wazuh/blob/d0af591c806b06a72834c3365612ad68a8bc3c01/src/client-agent/receiver-win.c#L144

This should be deallocated post to the call of the active response loop of windows.
https://github.com/wazuh/wazuh/blob/93b2f48e96ec4708bd3a1af4f5c307d5ca684169/src/os_execd/win_execd.c#L101
[RCA.txt](https://github.com/wazuh/wazuh/files/6348336/RCA.txt)

**Comment by Dwordcito** [comment]
2- Corruption / the dbjournal file is blocked (keeps the previous data to rollback an explicit sqlite transaction), apparently sqlite or the operating system is causing this given the test, this is solved by making the journal in memory, which improves the Operational performance and the allocation is not big, it took 6 hours and there is no crash.

**Comment by Dwordcito** [comment]
Branch to be re-tested.

`8283-windows-agent-stop-and-leak`
