### ISSUE TITLE
Syslog with SonicWall Firewall

### ISSUE THREAD

**Issue by BrunoWazuh** [wazuh/wazuh#8297]
Dear,

I need to collect syslog from a sonicwall firewall URGENT, I need the help of someone who has already worked this type of integration with wazuh!

Can someone help me?

I made this configuration, but I don't know if I need to do anything else?

Where do I see the logs arriving at wazuh, kibana, etc?   

My ossec.confg

```
<remote>
    <connection> secure </connection>
    <port> 1514 </port>
    <protocol> tcp </protocol>
    <allowed-ips> 192.168.0.0/24 </allowed-ips>
    <allowed-ips> 10.160.0.0/12 </allowed-ips>
    <allowed-ips> 172.16.0.0/12 </allowed-ips>
    <allowed-ips> 177.190.199.0/12 </allowed-ips>
    <local_ip> 172.16.0.190 </local_ip>
    <queue_size> 131072 </queue_size>
</remote>
<remote>
    <connection> syslog </connection>
    <port> 514 </port>
    <protocol> udp </protocol>
    <allowed-ips> 192.168.0.0/24 </allowed-ips>
    <allowed-ips> 10.160.0.0/12 </allowed-ips>
    <allowed-ips> 172.16.0.0/12 </allowed-ips>
    <allowed-ips> 177.190.199.0/12 </allowed-ips>
    <local_ip> 172.16.0.190 </local_ip>
</remote>
```

/app/wazuh#/manager/?tab=logs

What would these alerts be?

Apr 20, 2021 @ 11: 01: 07.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 07.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].
Apr 20, 2021 @ 11: 01: 02.000 ossec-remoted WARNING Too big message size from 172.16.0.190 [36].

**Comment by vikman90** [comment]
Hi @BrunoWazuh. I think this issue has been solved in the [mailing list](https://groups.google.com/g/wazuh/c/nW8ufLMIR9Y/m/tgJ-4OzWAQAJ) and Slack.
