### ISSUE TITLE
Carbanak Scenario Infrastructure Analysis

### ISSUE THREAD

**Issue by fabamatic** [wazuh/wazuh#8299]
Learn how to use MITRE emulation library scripts to set up both the Attack Platform and the Target Infrastructure.
Details on how to do this are located here https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/carbanak/Emulation_Plan/Scenario_1/Infrastructure.md

-----

### Conclusion

Many of the steps described in Carbanak scenario can be executed with minimum infrastructure, in an atomic fashion, this setup should be used for research in those steps.  A full infrastructure deployment will be required for the steps that implement some variant of lateral movement, and should also be used for final validation. For research on new rule elaboration **Data collection setup** must be done.

**Minimal infrastructure**
This configuration is valid for steps 1.A, 2.A, 2.B, 3.A, 3.B, 5.A, 7.A, 7.C, 8.A, 9.A, 10.A, 10.B
It requires:
Kali linux with IP 192.168.0.4. Should check out MITRE's Carbanak emulation repo from: https://github.com/center-for-threat-informed-defense/adversary_emulation_library
Windows 10 endpoint. defender should be disabled and powershell scripting enabled.

**Full infrastructure**
Adhere to MITRE's guide

**Data collection setup**
On Wazuhmanager:
Enable archives monitoring in Kibana
Steps to configure archives monitoring in kibana:

1. Set `<logall_json>yes</logall_json>` in `/var/ossec/etc/ossec.conf`
2. Set `archives: enabled` to `true` in `/etc/filebeat/filebeat.yml` 
````
archives:
  enabled: true
````
3. Restart wazuh manager: `# systemctl restart wazuh-manager`
4. Go to `kibana -> index management -> indices` and verify `wazuh-archives-x.x-xxxx.xx.xx` is present
5. Go to `kibana -> stack management -> index pattern` and select `Create index pattern`. Use `wazuh-archives-*` as index pattern name
6. Go to `kibana -> discover` and verify archives events are being reported

On windows 10 endpoint:

1. Setup Sysmon with [this config file](https://github.com/olafhartong/sysmon-modular/blob/master/sysmonconfig.xml) `sysmon64 -i sysmonfig.xml`
2. Install Wazuh-agent
3. Enable Sysmon log collection, add the following in ossec.conf:
```
<localfile>
  <location>Microsoft-Windows-Sysmon/Operational</location>
  <log_format>eventchannel</log_format>
</localfile>
```

**Comment by fabamatic** [comment]
Did analysis on execution/setup of each step to help decide if the execution is going to be done as a killchain or in an atomic way

**Comment by fabamatic** [comment]
- Kali server should have static IP address 192.168.0.4

This table specs the minimum requirements to execute each substep, out 18 13 should be doable with Just a Wundows 10 endpoint and Kali attack platform 
<table class="tableizer-table">
<thead><tr class="tableizer-firstrow"><th>Step</th><th>Substep</th><th>Kali</th><th>Win10</th><th>WindowsDC</th><th>CentOS</th><th>Notes</th></tr></thead><tbody>
 <tr><td rowspan="2">1</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>A requires MS Word installation</td></tr>
 <tr><td>A*</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">2</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">3</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">4</td><td>A</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="3">5</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td></tr>
 <tr><td>C</td><td>X</td><td>&nbsp;</td><td>X</td><td>X</td><td>&nbsp;</td></tr>
 <tr><td>6</td><td>A</td><td>X</td><td>&nbsp;</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="3">7</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>C</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>8</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>This step only works if 7.C has been executed</td></tr>
 <tr><td>9</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td rowspan="2">10</td><td>A</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
 <tr><td>B</td><td>X</td><td>X</td><td>&nbsp;</td><td>&nbsp;</td><td></td></tr>
</tbody></table>

**Comment by Nekaze** [comment]
Steps to configure archives monitoring in kibana:

1. Set `<logall_json>yes</logall_json>` in `/var/ossec/etc/ossec.conf`
2. Set `archives` to `enabled` in `/etc/filebeat/filebeat.yml`
3. Restart wazuh manager: `# systemctl restart wazuh-manager`
4. Go to `kibana -> index management -> indices` and verify `wazuh-archives-x.x-xxxx.xx.xx` is present
5. Go to `kibana -> stack management -> index pattern` and select `Create index pattern`. Use `wazuh-archives-*` as index pattern name
6. Go to `kibana -> discover` and verify archives events are being reported
