### ISSUE TITLE
Improvements to ms_dhcp_ipv4 decoder (0380-windows_decoders.xml)

### ISSUE THREAD

**Issue by jsoliani** [wazuh/wazuh#8301]
|4.1.0|Server|Manager|Unattended|CentOS8|

Decoder "ms_dhcp_ipv4" has problems detecting values 'extra_data' (called 'action' in Microsoft DHCP logs) and srcip.

**Features to be improved:** 
  - srcip variable (\S+) captures all the line instead of one IP address.
  - extra_data variable (\w+) could have spaces, in such cases, the decoder doesn't work at all and it's called 'action'.
  - Added 'timestamp' and 'hostname' variables, since the beginning of the log has always the same data in all versions.
  - prematch detection reduced to one line instead of two.

Logs samples:
 DHCP Server 2003:
`35,01/01/01,01:01:01,DNS update request failed,192.0.2.1,sampleHost,000000000000,`
 DHCP Server 2008:
`10,01/01/01,01:01:01,Assign,192.0.2.10,sampleHost1,000000000000,,17739,0,,,`
 DHCP Server 2012:
`21,01/01/2001,01:01:01,Assign,192.0.2.23,sampleHost4, 000000000000,,3096562285,0,,,,0x4D53465420352E30,MSFT 5.0,,,,0`

**--- STACK DECODER ---**
```
<decoder name="ms-dhcp-ipv4">
  <prematch>^\d\d,\d+/\d+/\d\d\d\d,\d+:\d+:\d+,|</prematch>
  <prematch>^\d\d,\d+/\d+/\d\d,\d+:\d+:\d+,</prematch>
  <regex>^(\d\d),\d+/\d+/\d\d\d*,\d+:\d+:\d+,(\w+),(\S+)</regex>
  <order>id,extra_data,srcip</order>
</decoder>
```
**--- IMPROVED DECODER ---**
```
<decoder name="ms-dhcp-ipv4">
  <prematch>^\d\d,\d+/\d+/\d\d\d*,\d+:\d+:\d+,</prematch>
  <regex>^(\d+),(\d+/\d+/\d\d\d*,\d+:\d+:\d+),(\.*),(\S*),(\w*),</regex>
  <order>id,timestamp,action,srcip,hostname</order>
</decoder>
```

**Testing results (with 2003, 2008, and 2012 DHCP formats, all successful):**

DHCP Server 2012 log:
```
**Phase 2: Completed decoding.
       decoder: 'ms-dhcp-ipv4'
       id: '21'
       timestamp: '01/01/2001,01:01:01'
       action: 'Assign'
       srcip: '192.0.2.23'
       hostname: 'sampleHost4'
```

DHCP Server 2003 log:
```
**Phase 2: Completed decoding.
       decoder: 'ms-dhcp-ipv4'
       id: '35'
       timestamp: '01/01/01,01:01:01'
       action: 'DNS update request failed'
       srcip: '192.0.2.1'
       hostname: 'sampleHost'
```

Results: srcip always captures one IP address, action (ex-extra_data) now is working when having spaces, and users have a timestamp and hostname available as well.

Regards,
John.-

**Comment by JavierBejMen** [comment]
# Branch
Branch to track changes: https://github.com/wazuh/wazuh/tree/8301_improve_ms_dhcp_ipv4_decoder

**Comment by JavierBejMen** [comment]
# Update
Updated regexes with pcre2 format
```xml
<decoder name="ms-dhcp-ipv4">
  <prematch type="pcre2">^\d{2},\d{2}\/\d{2}\/\d{2,4},\d{2}:\d{2}:\d+,</prematch>
  <regex type="pcre2">^(\d{2}),(\d{2}\/\d{2}\/\d{2,4},\d{2}:\d{2}:\d+),([^,]+),([^,]+),([^,]+)</regex>
  <order>id,timestamp,action,srcip,hostname</order>
</decoder>
```
