### ISSUE TITLE
Investigate cluster multi-threading pros and cons

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#8308]
Hello team,

We need to further investigate if multi-threading is the proper solution to improve the cluster performance. As it was discussed here, multi-threading may not be the best approach as there would be some threads which could have heavy CPU usage, leading to a bottleneck produced by the Python [Global Interpreter Lock](https://wiki.python.org/moin/GlobalInterpreterLock): https://github.com/wazuh/wazuh/issues/8251#issuecomment-822558940

We must investigate if this issue could be solved with [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) and determine what implications it could have, in addition to the complexity of the development.

Any suggestion or finding about this matter should be added as a comment so we will be able make a decission later on.

Regards,
Víctor Fernández

**Comment by davidjiglesias** [comment]
We hold further investigation for design and possible developments until https://github.com/wazuh/wazuh/issues/7366 is completed and the cluster actual state is properly evaluated.

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

During the investigation in https://github.com/wazuh/wazuh/issues/8439 we tried different approachs to improve the API performance and we came to the conclusion that multi-thread is not scalable in this case, as the API main tasks are synchronous (framework functions) and the cluster has higher CPU usage on larger environments. For these reasons, we have decided to implement multi-process in both cluster and API.

Regards,
Víctor Fernández
