### ISSUE TITLE
Retrieve and analyze API and cluster performance tests data

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#8325]
Hello team,

The final stage for the cluster performance in loaded environments epic issue (https://github.com/wazuh/wazuh/issues/7366) would be to interpretate all the necessary metrics and useful data to decide where the possible bottlenecks or issues could be. To do so, we need to review a bunch of logs, test results and command outputs.

## Logs

- Cluster log
- API log
- wazuh-db log

> **NOTE:** DEBUG level required.

## Test results

- HTML report produced by these API tests: https://github.com/wazuh/wazuh-qa/tree/master/tests/performance/test_api
  Look for any timeout errors or increased response times to find non-scalable endpoints.

## Command outputs

- `/cluster_control -i more`

```shellsession
Cluster name: wazuh

Connected nodes (1):

    master-node (wazuh-master)
        Version: 4.2.0
        Type: master
        Active agents: 1

    worker1 (172.21.0.5)
        Version: 4.2.0
        Type: worker
        Active agents: 0
        Status:
            Last keep Alive:
                Last received: 2021-03-24 13:25:18.645536.
            Integrity check:
                Last integrity check: 2021-03-24 13:25:15.224022 - 2021-03-24 13:25:15.228705.
                Permission to check integrity: True.
            Integrity sync:
                Last integrity synchronization: 2021-03-24 13:25:15.228839 - 2021-03-24 13:25:15.233563.
                Synchronized files: Shared: 0 | Missing: 0 | Extra: 1 | Extra valid: 0.
                Permission to sync extra valid files: True.
                Extra valid files correctly updated in master: 0.
            Agents-info:
                Last synchronization: 2021-03-24 13:25:19.297246 - 2021-03-24 13:25:19.298849.
                Number of synchronized chunks: 0.
```

With this command we will be able to see integrity and agent-info useful information.

This data recollection and study must be done with every parametrization of the loaded environments. New issues will be required in case we find errors, bugs or any undesired behaviour.

## Parametrization:

**Test vertical scalability:**

```
MANAGER_WORKERS= 5
AGENTS_NUMBERS= 10000
```
```
MANAGER_WORKERS= 5
AGENTS_NUMBERS= 25000
```
```
MANAGER_WORKERS= 5
AGENTS_NUMBERS= 50000
```

**Test horizontal scalability:**

```
MANAGER_WORKERS= 10
AGENTS_NUMBERS= 12500
```
```
MANAGER_WORKERS= 10
AGENTS_NUMBERS= 50000
```
```
MANAGER_WORKERS= 25
AGENTS_NUMBERS= 12500
```
```
MANAGER_WORKERS= 25
AGENTS_NUMBERS= 50000
```

**Test limits:** (On hold)

```
MANAGER_WORKERS= 50
AGENTS_NUMBERS= 100000
```

Regards,
Víctor Fernández

**Comment by AdriiiPRodri** [comment]
## Status update

## 1st vertical scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 5
**Agents:** 10000
**Test duration:** 900s

### API test results:
![api_test](https://user-images.githubusercontent.com/15522808/119962464-5c111880-bfa7-11eb-8089-dbe20e9686e5.png)

## Findings:
### Finding1 - DELETE /rootcheck
This is the first failed test (the order can be consulted here: https://github.com/wazuh/wazuh-qa/blob/cluster-performance-pipeline-improvements/tests/performance/test_api/data/configuration.yaml). If we look for the request in the api.log file, we will see that the status of the call is 500, so we are facing a TimeoutError, the API has not been able to process a response in 10 seconds (current Timeout of the API).

#### api.log
```
2021/05/27 10:45:50 INFO: wazuh 172.31.0.228 "PUT /syscheck" with parameters {} and body {} done in 3.045s: 200
2021/05/27 10:46:01 INFO: wazuh 172.31.0.228 "DELETE /rootcheck" with parameters {} and body {} done in 10.409s: 500
2021/05/27 10:46:01 INFO: wazuh 172.31.0.228 "POST /groups" with parameters {} and body {"group_id": "new_test_group"} done in 0.011s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B146_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### Finding2 - PUT /agents/group

In this case, the failed test is PUT /agents/group. The response to the request has code 200 which indicates that in principle everything went well, however, if we review the response carefully, we will see that within the response, the error key is 2. As we see the error is related to the lack of agent-groups files so it is likely that this problem is related to the issue: https://github.com/wazuh/wazuh/issues/8625

#### api.log
```
2021/05/27 10:46:01 INFO: wazuh 172.31.0.228 "POST /security/rules" with parameters {} and body {"name": "new_test_security_rule", "rule": {"MATCH": {"name": "test"}}} done in 0.036s: 200
2021/05/27 10:46:06 INFO: wazuh 172.31.0.228 "PUT /agents/group" with parameters {"group_id": "new_test_group"} and body {} done in 5.135s: 200
2021/05/27 10:46:36 INFO: wazuh 172.31.0.228 "GET /" with parameters {} and body {} done in 0.007s: 200
```

#### Response
```
    ...
      "9989",
      "9994",
      "9996",
      "9998"
    ],
    "total_affected_items": 9715,
    "total_failed_items": 285,
    "failed_items": [
      {
        "error": {
          "code": 1005,
          "message": "Error reading file: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/9983'",
          "remediation": "Please, ensure you have the right file permissions in Wazuh directories"
        },
        "id": [
          "9983"
        ]
      },
      {
        "error": {
          "code": 1005,
          "message": "Error reading file: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/9938'",
          "remediation": "Please, ensure you have the right file permissions in Wazuh directories"
        },
        "id": [
          "9938"
        ]
      },
      {
        "error": {
          "code": 1005,
          "message": "Error reading file: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/9794'",
          "remediation": "Please, ensure you have the right file permissions in Wazuh directories"
        },
        "id": [
          "9794"
        ]
      },
      ...
```

### Finding3 - DELETE /agents

Here we have again a Timeout type error, the API is not able to remove all the agents in 10 seconds, normally in 10 seconds it usually removes around 300-400. We must review and check why sometimes the Timeout trace is in the API log and sometimes not.

#### api.log
```
2021/05/27 10:48:00 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/27 10:48:00 INFO: wazuh 172.31.0.228 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.042s: 500
2021/05/27 10:48:10 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

### Finding4 - DELETE /groups

This case is again a Timeout failure, however, we cannot find the request in question in the api.log file. It is possible that in this case, the request was launched before the master node finished restarting. This could explain the lack of the request in the logging. Furthermore, in the test itself, we can see the response of this request and we can verify that the API was responding.

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

### Finding5 - DELETE /security/users

Again an error by Timeout of the API, this request normally never gives Timeout, this Timeout has been produced just after another Timeout with the call DELETE /agents. We must investigate if this is related.

#### api.log
```
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/27 10:48:36 INFO: wazuh 172.31.0.228 "DELETE /security/users" with parameters {"user_ids": "all"} and body {} done in 10.017s: 500
2021/05/27 10:48:36 INFO: wazuh 172.31.0.228 "DELETE /security/roles" with parameters {"role_ids": "all"} and body {} done in 0.110s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

## Related issue:
- Finding1 - DELETE /rootcheck: N/A
- Finding2 - PUT /agents/group: https://github.com/wazuh/wazuh/issues/8625

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

After performing several tests, we are confident that the endpoints having scaling problems are `DELETE /rootcheck` and `DELETE /agents`. We have removed these two endpoints and the `PUT /agents/group` endpoint from the test as it requires a restart of Wazuh. This restart causes that the following tests fail, so we are going to review carefully this test before continuing with the following executions.

Here we can see the result of the tests after removing the mentioned endpoints:

![image](https://user-images.githubusercontent.com/15522808/120178643-01c3c200-c20a-11eb-9daa-e93b5344eead.png)

Report: 
[result.pdf](https://github.com/wazuh/wazuh/files/6569564/result.pdf)

**Comment by AdriiiPRodri** [comment]
## Status update

## 2st vertical scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 5
**Agents:** 25000
**Test duration:** 900s

### API test results:
![image](https://user-images.githubusercontent.com/15522808/120215899-97754680-c236-11eb-8733-1a5488153f8b.png)


## Findings:
After removing from the tests the endpoints that we know have scalability problems (DELETE /rootcheck, PUT /agents/group, and DELETE /agents), we have launched the pipeline with 25000 agents. The result has been that we have not found any API related problems. No scalability problems have been detected at this stage.

**Comment by AdriiiPRodri** [comment]
## Status update

## 3st vertical scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 5
**Agents:** 50000
**Test duration:** 900s

### API test results:
![image](https://user-images.githubusercontent.com/15522808/120281832-bbc63700-c2b9-11eb-871a-3d140809a8ce.png)


## Findings:
### Finding1 - PUT /rootcheck
This is the first scalability problem found in this run. The `PUT /rootcheck` endpoint has returned a Timeout type error. So we see that it has scalability problems, these problems are not as obvious as the findings found in the previous tests.

#### api.log
```
2021/05/31 16:01:34 INFO: wazuh 172.31.80.61 "GET /tasks/status" with parameters {} and body {} done in 0.011s: 200
2021/05/31 16:01:50 INFO: wazuh 172.31.80.61 "PUT /rootcheck" with parameters {} and body {} done in 15.291s: 500
2021/05/31 16:02:08 INFO: wazuh 172.31.80.61 "PUT /syscheck" with parameters {} and body {} done in 18.297s: 500
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B162_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### Finding2 - PUT /syscheck

As in the previous case, a Timeout type error has occurred. In this case, we will check if this error could have been caused by the previous Timeout (PUT /rootcheck) since they have been successive requests.

#### api.log
```
2021/05/31 16:01:50 INFO: wazuh 172.31.80.61 "PUT /rootcheck" with parameters {} and body {} done in 15.291s: 500
2021/05/31 16:02:08 INFO: wazuh 172.31.80.61 "PUT /syscheck" with parameters {} and body {} done in 18.297s: 500
2021/05/31 16:02:08 INFO: wazuh 172.31.80.61 "POST /groups" with parameters {} and body {"group_id": "new_test_group"} done in 0.009s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B162_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### Finding3 - PUT /agents/restart

Timeout error when trying to restart all the agents and receiving a response in only 10 seconds. This is another endpoint that needs a revision since we send one by one each restart request. We may need a tool that gives us the ability to send a single restart command that propagates to all agents in the system.

#### api.log
```
2021/05/31 16:03:09 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.011s: 200
2021/05/31 16:03:23 INFO: wazuh 172.31.80.61 "PUT /agents/restart" with parameters {} and body {} done in 13.937s: 500
2021/05/31 16:04:23 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.006s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B162_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### Finding4 - PUT /cluster/restart

This time we have that the error is not a Timeout type error, this time we have not received any response, nor has this request been recorded in the api.log file, so it is possible that due to the high load of the environment, 60 seconds of waiting after the restart is not enough. However, we should investigate this as the `GET /` requests have been executed to check the API connectivity:

#### api.log
```
2021/05/31 16:04:30 INFO: wazuh 172.31.80.61 "PUT /manager/restart" with parameters {} and body {} done in 0.111s: 200
2021/05/31 16:04:49 INFO: Listening on 0.0.0.0:55000..
2021/05/31 16:05:30 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.073s: 200
2021/05/31 16:06:49 INFO: Listening on 0.0.0.0:55000..
2021/05/31 16:06:54 INFO: wazuh 172.31.80.61 "GET /" with parameters {} and body {} done in 0.082s: 200
```

## Related issue:
- Finding1 - `PUT /rootcheck`: N/A
- Finding2 - `PUT /syscheck`: N/A
- Finding3 - `PUT /agents/restart`: N/A
- Finding4 - `PUT /cluster/restart`: N/A

**Comment by AdriiiPRodri** [comment]
## Status update

## 1st horizontal scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 10
**Agents:** 12500
**Test duration:** 900s

### API test results:
![image](https://user-images.githubusercontent.com/15522808/120333304-d9ae8e80-c2ef-11eb-885b-915cb3070114.png)

**Comment by AdriiiPRodri** [comment]
## Status update

## 2st horizontal scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 10
**Agents:** 50000
**Test duration:** 1200s

## Findings:
No new problems of any type have been found.

**Comment by AdriiiPRodri** [comment]
## Status update

## 3st horizontal scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 25
**Agents:** 12500
**Test duration:** 1500s

## Findings:
No new problems of any type have been found.

**Comment by AdriiiPRodri** [comment]
## Status update

## 4th horizontal scalability test
### Test parameters:

**Version:** 4.2.0
**Workers:** 25
**Agents:** 12500
**Test duration:** 1500s

## Findings:
No new problems of any type have been found.

**Comment by AdriiiPRodri** [comment]
## Status update

This issue will remain **blocked** until all affected endpoints are improved. It will be unlocked once this issue is closed: https://github.com/wazuh/wazuh/issues/8720

Regards

**Comment by AdriiiPRodri** [comment]
Hi team,

After all the changes made following the issue https://github.com/wazuh/wazuh/issues/8720, we have run the same tests again. This time, we have five errors.

### DELETE /groups
The first one has to do with the `DELETE /groups` endpoint, this error occurs with the first tests, both vertical and horizontal.

```
Request elapsed time: 10.028s

Status code: 500

Full response: 
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

> Environment:
> Vertical: 10000 agents - 5 workers
> Horizontal: 12500 agents - 10 workers

### PUT /agents/group
The second error is related to the `PUT /agents/group` endpoint, this error was already reported in the previous iteration and is not related to the Framework. There is an issue about it: https://github.com/wazuh/wazuh/issues/8625

```
    ...
      {
        "error": {
          "code": 1005,
          "message": "Error reading file: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/9784'",
          "remediation": "Please, ensure you have the right file permissions in Wazuh directories"
        },
        "id": [
          "9784"
        ]
      },
      {
        "error": {
          "code": 1005,
          "message": "Error reading file: [Errno 2] No such file or directory: '/var/ossec/queue/agent-groups/9637'",
          "remediation": "Please, ensure you have the right file permissions in Wazuh directories"
        },
        "id": [
          "9637"
        ]
      }
    ]
  },
  "message": "Some agents were not assigned to new_test_group",
  "error": 2
}
```

> Environment:
> Vertical: 10000 agents - 5 workers
> Horizontal: Does not fail

### DELETE /agents
The third error is a timeout in the `DELETE /agents` endpoint. This time, we have considerably improved this endpoint, going from failing with 10000 agents to failing the following tests. So we can deduce that the approximate maximum amount that can eliminate the API in 10 seconds is between 10000 and 12500. For our part this endpoint can not be improved more:

```
test_case = {'body': {}, 'endpoint': '/agents', 'method': 'delete', 'parameters': {'agents_list': 'all', 'older_than': '0s', 'status': 'all'}}

Request elapsed time: 10.030s

Status code: 500

Full response: 
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

> Environment:
> Vertical: 25000 agents - 5 workers
> Horizontal: 12500 agents - 10 workers

### PUT /rootcheck
The fourth error is related to the `PUT /rootcheck` endpoint, it is a timeout type error. In this case, the Framework code can no longer be optimized, the solution is to modify the socket:

```
Request elapsed time: 24.090s

Status code: 500

Full response: 
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B225_manager_21": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_23": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_6": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_13": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    ...
```

> Environment:
> Vertical: Does not fail
> Horizontal: 50000 agents - 15 workers

### PUT /syscheck
The fifth error is the same as the fourth but with the `PUT /syscheck` endpoint, as with the previous one, the solution is to modify the socket:

```
Request elapsed time: 25.967s

Status code: 500

Full response: 
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B225_manager_21": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_23": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_6": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B225_manager_13": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    ...
```

> Environment:
> Vertical: Does not fail
> Horizontal: 50000 agents - 15 workers
