### ISSUE TITLE
Wrong path generated in Windows agent

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#833]
In the Windows agent, Syscheck stores the paths to the monitored directories by adding slashes when reading a directory recursively.

If the following path is set up in Windows for monitoring:

```
<directories check_all="yes">C:\Windows\test</directories>
```

The entire contents of the 'test' directory will be added with the slash. For example:
```
C:\Windows\test/file1
C:\Windows\test/folderA/file2
C:\Windows\test/folderA/.../...
```

If at any time the path we are monitoring is changed to:
```
 <directories` check_all="yes">C:\Windows\testA</directories>
```

The contents of that folder will be added with the following path:

```
C:\Windows\test\folderA/file2
```

This produces two different paths for the same file duplicating information in the Syscheck database.

To fix this problem the proposed solution is to change all backslashes to slashes in Windows.

**Comment by Cerv1** [comment]
Fixed in #857.
