### ISSUE TITLE
Add pytest cases for issues #8329

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8339]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| master | Syscollector | Manager/Agent | Packages/Sources | windows |

## Description
This issue aims to cover the technical debt of the issued # that proposes to add a case to validate the return and correct operation.

Proposed test cases:
- Add mechanism to run test only for Windows environments.
- Validate nonempty path values with test tool.
- Validate path don't start with /Device on testtool return data.

**DoD**
- [ ] Add test.
- [ ] Validate test.
- [ ] PR - Test CI Pass.

**Comment by vikman90** [comment]
Closing this issue. Superseded by version 5.0.
