### ISSUE TITLE
Wazuh worker not deleting agent DB files in /var/ossec/queue/db

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh#8344]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.4-40113 | Syscheck | Manager | Packages/Sources | CentOS Linux 7 (Core) |

Hi team,

We realized that the number of files within `/var/ossec/queue/db` in a worker within a cluster is not matching the actual number of agents in `client.keys`. We are afraid that these files might not be deleted.

Agents in `client.keys`
```
grep -v "^\!" /var/ossec/etc/client.keys | wc -l
22043
```
> Purge is enabled, there were not removed agents.

Files in `/var/ossec/queue/db/`
```
ls /var/ossec/queue/db/ | wc -l
45242
```

Of which 21 are journal files
```
ls /var/ossec/queue/db/ | grep journal | wc -l
21
```

The number of unique agent IDs files is 45235
```
ls /var/ossec/queue/db/ | cut -d'.' -f1 | sort | uniq | wc -l
45235
```

Additionally, the oldest of these `.db` files dates from Mar 30 2021, when we updated to 4.12 (we updated to 4.14 afterward). This behavior started then.

So, there is a clear mismatching between the number of active agents and the number of files belonging to unique agents.

Please, feel free to ask any further information you may need or change anything on the description of this issue to improve it.

Regards.

**Comment by palaciosjeremias** [comment]
Problem: There is a possibility of a race condition between the deletion of an agent and the usage of its database.
i.e.: Vulnerability Detector can query **global.db** to obtain every connected agent previous to start the scan. After the connected agents are collected, multiple queries to each agent DB can be performed during the scan of Vulnerability Detector, along an extended period of time (in the range of minutes).
An agent deletion can occur between the first collection of agents and the further queries to the agents' database.
As Wazuh-DB creates a new DB if it doesn´t exist, any query to the agents' database, posterior to the database deletion, will create a new one.
This can leave obsolete databases without deletion.

**Comment by palaciosjeremias** [comment]
Possible solution:
We can extend the functionality of **monitord** to periodically check the existent agents' databases and control if these agents still exist in **global.db**. If an obsolete database is found it canbe automatically deleted.

**Comment by jesuslinares** [comment]
It could be related to https://github.com/wazuh/wazuh/issues/8327.

**Comment by Molter73** [comment]
As @jesuslinares pointed out, this issue is already being worked on in #8327. I'm closing this issue so we can focus our efforts there.
