### ISSUE TITLE
Unable to add API configuration [Error. Could not reach server]

### ISSUE THREAD

**Issue by fayax** [wazuh/wazuh#835]
Recently my Wazuh installation got updated, I believe Elastic Stack also got updated, so Kibana was throwing errors.
I re-installed Wazuh-API and Elastic Stack. Now I'm unable to add API configuration to Kibana. I'm getting this error "Settings. Error. Could not reach server". I was able to connect to API using curl
`curl -u wazuh-ossec:wazuh-ossec http://127.0.0.1:55000/agents/000?pretty`
```
{
   "error": 0,
   "data": {
      "status": "Active",
      "name": "ossec",
      "ip": "127.0.0.1",
      "dateAdd": "2018-06-20 18:35:24",
      "version": "Wazuh v3.3.1",
      "manager_host": "ossec",
      "lastKeepAlive": "9999-12-31 23:59:59",
      "os": {
         "major": "9",
         "name": "Debian GNU/Linux",
         "platform": "debian",
         "uname": "Linux |ossec |4.9.0-6-amd64 |#1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) |x86_64",
         "version": "9",
         "codename": "stretch",
         "arch": "x86_64"
      },
      "id": "000"
   }
}

```

Any help is appreciated.

Thanks,
fayax

**Comment by JuanjiJG** [comment]
Hello @fayax,

Maybe the downgrade to the previous version of the Elastic Stack left something bad on the indices. Try the following steps to reset your Wazuh app configuration and insert again the Wazuh API credentials:

1. First, stop the Kibana service (close all your Kibana browser tabs previously):
```
systemctl stop kibana
```
2. Delete the `.wazuh`, `.wazuh-version` and `.kibana` indices. **Warning: deleting the `.kibana` index will delete your saved visualizations and custom index patterns:**
```
curl -XDELETE <ELASTICSEARCH_IP>:9200/.kibana
curl -XDELETE <ELASTICSEARCH_IP>:9200/.wazuh
curl -XDELETE <ELASTICSEARCH_IP>:9200/.wazuh-version
```
3. Restart the Kibana service:
```
systemctl restart kibana
```
4. Open an incognito window on your browser and open the Kibana interface. Try to insert again the API credentials and press on the `Save API` button. Let us know about the results.

Regards,
Juanjo

**Comment by fayax** [comment]
Hi @JuanjiJG 

That resolved the issue.

Thank you for the help

**Comment by JuanjiJG** [comment]
Glad to help you @fayax,

Don't hesitate to open a new issue if you have more questions or problems.

Regards,
Juanjo
