### ISSUE TITLE
Custom active response in ar.conf not triggering

### ISSUE THREAD

**Issue by Dr-Dd** [wazuh/wazuh#8355]
|Wazuh version | Install method|Platform|
|---|---|---|
| 4.1.4 | Sources | 5.4.80-gentoo-r1 |

Following the [doc's guide on auditd monitoring](https://wazuh.com/blog/monitoring-root-actions-on-linux-using-auditd-and-wazuh/) i've added the following rule to the manager's `/var/ossec/ruleset/rules/0365-auditd_rules.xml` :
``` xml
<rule id="80792" level="3">
        <if_sid>80700</if_sid>
        <list field="audit.key" lookup="match_key_value" check_value="command">etc/lists/audit-keys</list>
        <description>Audit: Command: $(audit.exe)</description>
        <group>audit_command,gdpr_IV_30.1.g,</group>
    </rule>
```
This rule triggers the following active response, tied to the `test_expect` command in the manager's `/var/ossec/etc/ossec.conf`:
``` xml
  <command>
    <name>test_expect</name>
    <executable>test_expect.sh</executable>
    <expect>srcip,filename,user</expect>
  </command>

  <active-response>
    <disabled>no</disabled>
    <command>test_expect</command>
    <location>local</location>
    <rules_id>80792</rules_id>
  </active-response>
```
The test_expect.sh script is present on both the manager's and agent's `/var/ossec/active-response/bin/` folder with the following permissions set:
``` bash
-rwxr-x--- 1 root ossec 80 Apr 24 13:07 /var/ossec/active-response/bin/test_expect.sh
```
And this is the script itself
``` bash
#!/bin/sh
echo "srcip=$1 filename=$2 user=$3" >> /tmp/active-response-out.log
```
I've enabled the following internal options for the agent:
``` yaml
logcollector.remote_commands=1
wazuh_command.remote_commands=1
```
And the command gets registered correctly to the manager's `/var/ossec/etc/shared/ar.conf` and is visible through `/var/ossec/bin/agent_control -L`
```
# agent_control -L output
Wazuh agent_control. Available active responses:

   Response name: test_expect0, command: test_expect.sh

# ar.conf
restart-ossec0 - restart-ossec.sh - 0
restart-ossec0 - restart-ossec.cmd - 0
test_expect0 - test_expect.sh - 0
```
The alerts are correctly generated and visible in the logs, but the active response never happens (and `active-responses.log` is empty both on the manager's and agent's side)

Does anyone know what to do? Thanks in advance.

**Comment by Dr-Dd** [comment]
So i've tried to trigger an active response via the API. Sending the following request to the `/active-response` endpoint does indeed trigger the command: 
``` json
{
  "command":"test_expect.sh",
  "custom":true 
}
```
Here's the curl one-liner:
``` bash
curl -k -X PUT "https://localhost:55000/active-response?pretty=true" \ 
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \ 
    -d '{ "command":"test_expect.sh","custom":true }'
```
So the problem is with the active-response in ossec.conf not triggering. The script itself is ok.

**Comment by Dr-Dd** [comment]
Even stranger, i tried to change the command to exec in my rule, and using one of the "stock" scripts, the active-response works correctly. Why is that?

**Comment by s-ocando** [comment]
The custom active response `test_expect` is not triggering as it is not receiving the parameters set in the `expect` field (`scrip`, `filename` and `user`). These parameters are not included in the event that triggers rule `80792`. 
By removing the `expect` line from your command definition the active response should work as expected. Be sure to adapt the `test_expect.sh` script accordingly.

```xml
  <command>
    <name>test_expect</name>
    <executable>test_expect.sh</executable>
  </command>
```

To learn more about the  [expect](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/commands.html#expect) parameter see our documentation.
