### ISSUE TITLE
Email_alert features didnt send an email 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#836]
I have set my email_alert like this but it didnt send me any email alert. The conf is just like below:

```
<email_alerts>
    <email_to>realemailhere1@gmail.com</email_to>
    <email_to>realemailhere2@gmail.com</email_to>
    <rule_id>601, 602</rule_id>
    <do_not_delay/>
 </email_alerts>
```
So it will send me an email alert, when there were alerts 601 and 602 that triggered. My Daily report works nicely. Any thought about that ? Thanks in advanced

**Comment by chemamartinez** [comment]
Hi @gagantous ,

Your configuration seems right. However, another piece of configuration is needed to forward alerts by email, and it is located in the `<global>` section.

On that section, it has to appear something like this:

```
<global>
  ...
  <email_notification>yes</email_notification>
  <smtp_server>your-smtp-server.com</smtp_server>
  <email_from>ossecm@example.wazuh.com</email_from>
  <email_to>realmailhere1@gmail.com</email_to>
  <email_to>realmailhere2@gmail.com</email_to>
</global>
```

It doesn't matter your email addresses are repeated in both sections, they have to be included in the `<global>` section to be able to use the `<email_alerts>` block.

On the other hand, you could find the SMTP server which your email address belongs in your personal email configuration. For Gmail accounts, it uses to be `smtp.gmail.com`.

You can find more information about email alerts in the following link of the documentation:

https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html

I hope it helps.

Best regards,
Chema.

**Comment by gagantous** [comment]
@chemamartinez 

So i have to set inside the email alerts tag like that so that would be:

```
<email_alerts>
    <email_notification>yes</email_notification>
   <smtp_server>your-smtp-server.com</smtp_server>
   <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>realemailhere1@gmail.com</email_to>
    <email_to>realemailhere2@gmail.com</email_to>
    <rule_id>601, 602</rule_id>
    <do_not_delay/>
 </email_alerts>
```

Is it right ?

**Comment by gagantous** [comment]
Hi @chemamartinez  
We can have two tag global ? 
like the default one and that email alert ? like this one ?

```
<global>
  <jsonout_output>yes</jsonout_output>
  <alerts_log>yes</alerts_log>
  <logall>no</logall>
  <logall_json>no</logall_json>
  <email_notification>yes</email_notification>
  <smtp_server>smtp.example.wazuh.com</smtp_server>
  <email_from>ossecm@example.wazuh.com</email_from>
  <email_to>recipient@example.wazuh.com</email_to>
  <email_maxperhour>12</email_maxperhour>
</global>

<global>
    <email_notification>yes</email_notification>
    <smtp_server>your-smtp-server.com</smtp_server>
    <email_from>ossecm@example.wazuh.com</email_from>
    <email_to>realmailhere1@gmail.com</email_to>
    <email_to>realmailhere2@gmail.com</email_to>
</global>

<email_alerts>
    <rule_id>601, 602</rule_id>
    <do_not_delay/>
</email_alerts>

```

**Comment by chemamartinez** [comment]
Hi @gagantous ,

You can set up every global tag that you want. However, there are some options that will take the last value read such as the `smtp_server`, the `email_from` or the `email_maxperhour` tags.

Only the `email_to` tag allows multiple emails to send alerts, so this option will take all email accounts that appear in the configuration file.

Regards,
Chema.
