### ISSUE TITLE
Connect to wcom instead of execq in the framework

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#8360]
|Wazuh version|Component|
|---|---|
| 4.3.0 | Framework |

Hi team.
After the investigation in #7968, some changes need to be done in core and in the framework to fix this problem.
The purpose of this issue is to change all the connections to `execq` to `wcom` as the configuration validation and manager restart capabilities have been moved. This will prevent errors when executing these queries and active response is disabled.

Kind regards.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Issue update
Development is finished. However, I noticed a change in the expected command and I wanted to point it out, as I consider it incorrect.

Before the changes on `wcom`, we would send the following message to the socket:

https://github.com/wazuh/wazuh/blob/38d0507251ffe97521ca705c7b8f713e08aaf1d0/framework/wazuh/core/manager.py#L132-L134

This way, we followed the format we discussed and approved in https://github.com/wazuh/wazuh/issues/5934.

Now, this message is not accepted. To make it work, I had to change that line to:

https://github.com/wazuh/wazuh/blob/49435270521c013f99dc5a5b16e3df7ec2482907/framework/wazuh/core/manager.py#L136

I need a confirmation from @Molter73 if this is correct.

### Pending
- Update unit tests

Regards,
Víctor Fernández

**Comment by Molter73** [comment]
The format discussed on #5934 has not been implemented on `com` yet. This socket handles some minor tasks like restarting the agents when a change on centralized configuration is detected.

Since changing this falls out of scope for the current issues, I would recommend going forward with the available format and opening a separate issue in order to properly coordinate efforts.
