### ISSUE TITLE
Wazuh service stops on agent after some minutes for Windows agent versions newer than v3.3.1

### ISSUE THREAD

**Issue by dmmarag** [wazuh/wazuh#8363]
|Wazuh version|Component            |Install type|Install method|Platform         |
|4.1.5-1             |Agent v4.1.4-v4.1.5|all-in-one  |apt install  step-by-step installation following this: https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all_in_one.html      |Ubuntu 18.04|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

I have installed wazuh 4.1.5-1 on Ubuntu 18.04 server (the whole environment has been gradually upgraded over the years).
Linux agents work without issues.
Recent Window agents get registered, wazuh service is started but after some minutes it stops. The issue is not observed for Windows agents from 3.3.1 and back.

Tried Windows Agent versions: 2.0.1 (works ok), 3.3.1 (works ok), 4.1.4 (service stops), 4.1.5 (service stops)

I have tried using protocol tcp and udp (because 3.3.1 was the agent version when tcp became the default).
I have tried modifying client buffer because I observed buffer issues in logs:
[ossec.log](https://github.com/wazuh/wazuh/files/6375884/ossec.log)
[conf-logs.zip](https://github.com/wazuh/wazuh/files/6375890/conf-logs.zip)

   <client_buffer>
     
     <disabled>no</disabled>
     <queue_size>100000</queue_size>
     <events_per_second>1000</events_per_second>
   </client_buffer>
I have tried modifying the following options to avoid heartbeat-timeout issues:
<notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>

Attaching ossec.conf and ossec.log from agent side in debug mode.

**Comment by Molter73** [comment]
Hi @dmmarag,

This issue looks related to #7836, by looking at the provided logs I can see the same issue regarding synchronization of registry values. Could you check with a version 4.0.4 agent? You can also disable synchronization of the windows registry as described in [this comment](https://github.com/wazuh/wazuh/issues/7836#issuecomment-814758303). If either of these stops the agent from crashing then a fix has already been implemented and is scheduled to be included in version 4.2.0

**Comment by dmmarag** [comment]
Indeed, version 4.0.4 seems stable and the issue has not occurred since yesterday. I will be expecting the fix in v4.2.0. Thank you for your support.
