### ISSUE TITLE
Failed installing wazuh API

### ISSUE THREAD

**Issue by EdanZona** [wazuh/wazuh#837]
I already installed the wazuh manager on RHEL 7, now I'm trying to install the wazuh API. I installed nodejs 4.6.1 as the wazuh installation guide suggests, ran the configure file, make and make install commands and node -v works, but when i try to install wazuh-api-3.3.1-1.x86_64.rpm using rpm -i , an error pops up saying nodesj >= 4.6 is needed. Anybody knows what the problem is?

Thanks in advance.

**Comment by JuanjiJG** [comment]
Hello @EdanZona,

The team will take a look into this. In the meantime, is there a reason to not install at least NodeJS 6.x or 8.x? The 4.x version is quite outdated, and the latest LTS of NodeJS is the 8.x series.

It's true that the documentation says that NodeJS => 4.6.1 is required, but we recommend to install using the 8.x repository, using this command provided in the documentation:
```
curl -sL https://deb.nodesource.com/setup_8.x | bash -
```
And if your system is not compatible with NodeJS 8, you can install NodeJS 6:
```
curl -sL https://deb.nodesource.com/setup_6.x | bash -
```
Try again to install the Wazuh API if you upgrade to NodeJS 6 or 8, and let us know about the results.

Regards,
Juanjo

**Comment by EdanZona** [comment]
Thank you both for the reply, I used 4.6.1 because I wanted to be sure to use the supported version, at first I tried with version 8 but i had problems with the gcc version so i went all the way back to 4. I will try with version 6 as it supports my gcc version. Unfortunately I can not use yum or repositories at all so it has to be source. I'll let you know if I have anymore problems.

**Comment by BraulioV** [comment]
Glad to help @EdanZona ,

but make sure to completely remove the Wazuh API package and make sure that the `/var/ossec/api` directory is also removed. After that, you can try again with NodeJS 6 😄 .
