### ISSUE TITLE
Amazon Linux support: OVAL scan

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8370]
### Description

The aim of this issue is to be able to scan Amazon Linux agents by Vulnerability Detector, once their feeds have been correctly indexed in the Vulnerability databases.

### Tasks / Requirements

- Amazon Linux 1 and 2 agents should be recognized by the detector and assigned the proper target feed
- Create the needed query to match vulnerabilities for these packages
- The RPM version comparator should be used for these agents
- Evaluate if matching the source or binaries packages based on the information coming from the agents' inventory
- The package architecture should be taken into account when matching the vulnerabilities

Regarding the `source` vs `binaries` issue. Let's see an example with https://alas.aws.amazon.com/AL2/ALAS-2021-1630.html

Packages included in ALAS-2021-1630 are:

```
aarch64:
    pki-symkey-10.5.18-12.amzn2.0.1.aarch64
    pki-tools-10.5.18-12.amzn2.0.1.aarch64
    pki-core-debuginfo-10.5.18-12.amzn2.0.1.aarch64

i686:
    pki-symkey-10.5.18-12.amzn2.0.1.i686
    pki-tools-10.5.18-12.amzn2.0.1.i686
    pki-core-debuginfo-10.5.18-12.amzn2.0.1.i686

noarch:
    pki-base-10.5.18-12.amzn2.0.1.noarch
    pki-base-java-10.5.18-12.amzn2.0.1.noarch
    pki-server-10.5.18-12.amzn2.0.1.noarch
    pki-ca-10.5.18-12.amzn2.0.1.noarch
    pki-kra-10.5.18-12.amzn2.0.1.noarch
    pki-javadoc-10.5.18-12.amzn2.0.1.noarch

src:
    pki-core-10.5.18-12.amzn2.0.1.src

x86_64:
    pki-symkey-10.5.18-12.amzn2.0.1.x86_64
    pki-tools-10.5.18-12.amzn2.0.1.x86_64
    pki-core-debuginfo-10.5.18-12.amzn2.0.1.x86_64
```

we have two options:

- Compare the source of the package against `pki-core-10.5.18-12.amzn2.0.1.src` to match the vulnerability
- The more precise way, using the binaries for each architecture to match the vulnerabilities

**Comment by alromeros** [comment]
**Devel branch**: https://github.com/wazuh/wazuh/tree/8370-amazon-oval-scan

**Comment by alromeros** [comment]
**Pull Request:** https://github.com/wazuh/wazuh/pull/8557
