### ISSUE TITLE
SUSE support: Feeds parser and OS detection

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8374]
### Description

Feeds mentioned at https://github.com/wazuh/wazuh/issues/8373 will be added to the vulnerability database in order to support SUSE agents (desktop and server).

These feeds are standard OVAL format so the current parser for the other OVAL feeds should work for these new ones.

However, the goal of this issue is to ensure every interesting data from the feed is properly stored in the database to be able to run the scans.

In addition, we have to take care of the fact that for each OS version, such as 15, we have two different feeds and targets, `desktop` and `server` so they have to be differentiated properly when indexing the vulnerabilities and detecting the agents OS.

**Comment by chemamartinez** [comment]
Branch: [8374-parse-suse-feeds](https://github.com/wazuh/wazuh/tree/8374-parse-suse-feeds)

**Comment by juanmanuelug** [comment]
Hi team,

I have been researching and collecting OS information from a Suse Linux 15sp2 Desktop VM. 
Here I leave you the OS information, the Syscollector logs and the DB.

command: `cat /etc/os-release`
```
NAME="SLED"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Desktop 15 SP2"
ID="sled"
ID_LIKE="suse"
ANSI_COLOR="0.32"
CPE_NAME="cpe:/o:suse:sled:15:sp2"
````
command: `cat /etc/issue`
```
Welcome to SUSE Linux Enterprise Desktop 15 SP2 (x86_64) - Kernel \r (\l).
eth0: \4{eth0} \6{eth0}
````
command: `uname -a`
```
Linux localhost.localdomain 5.3.18-22-default #1 SMP Wed Jun 3 12:16:43 UTC 2020 (720aeba) x86_64 x86_65 x86_64 GNU/Linux
````

Syscollector logs:
[output.txt](https://github.com/wazuh/wazuh/files/6622115/output.txt)

Agent db:
[366.db.gz](https://github.com/wazuh/wazuh/files/6622123/366.db.gz)
