### ISSUE TITLE
Unit tests for ULS functions

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#8380]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | wazuh-logcollector | Agent | - | macOS Sierra or greater |

Hi Team!

As part of the epic https://github.com/wazuh/wazuh/issues/4572, it is necessary to perform unit tests of the main functions responsible for reading logs in MacOS (ULS).

### Unit test
  - [x] w_is_log_cmd_executable
  - [x] w_logcollector_create_oslog_env
  - [ ] oslog_getlog
  - [x] oslog_is_header
  - [ ] read_oslog

Regards,
Juan Cabrera

**Comment by jnasselle** [comment]
Closed by #8627
