### ISSUE TITLE
Theoretical maximums

### ISSUE THREAD

**Issue by weavage** [wazuh/wazuh#839]
Is there a list of theoretical maximums anywhere? Maximum numbers of clients registered to a server node, etc.. 
I understand this would be very relative and depend on several factors, but some baselines would be useful. I haven't found anything documented anywhere, but it's Monday and I may have looked right past it.

**Comment by TJOSERAFAEL** [comment]
Hi @weavage,

as for the Wazuh manager, the important factor is not the number of agents connected, it's the  events per second you are going to handle. For example the Windows agents will send more events per second than the Linux agents by default.

When you install Wazuh manager, the maximum agents that you can connect are 14000 but you can override this if you compile wazuh by your self like this:

`#make TARGET=server MAXAGENTS=YOUR_VALUE`

If you have further questions please don't hesitate to ask.

Best regards

**Comment by weavage** [comment]
Thanks for the reply! That actually leads me to another question regarding maximums and clustering. Is the 14,000 agents you mentioned for a single manager node or for an entire cluster? The documentation on clustering says "It multiplies Wazuh’s event processing capacity and allows to have thousands of agents reporting." Does clustering allow scaling beyond 14,000 connected agents or just help distribute the load?

Also, if others are curious about this, Wazuh has a really useful page regarding Events Per Second:
[https://documentation.wazuh.com/3.x/user-manual/capabilities/antiflooding.html](url)

**Comment by TJOSERAFAEL** [comment]
Hi @weavage 

**- Is the 14,000 agents you mentioned for a single manager node or for an entire cluster?**
No, it is for a single manager node.

**- Does clustering allow scaling beyond 14,000 connected agents or just help distribute the load?**
It allows both, you can connect more than 14,000 agents per node if you compile your own manager as commented on the previous post and distribute the load adding more nodes to the cluster
