### ISSUE TITLE
Monitor rebase branch week 1

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8410]
## Description
This issue aims to keep the branch updated for later merge, introducing the latest changes in 5.0-dev branch into main epic branch..

## DoD
- [x] Branch rebase
- [x] Fix conflicts

**Comment by tinachoB** [comment]
![image](https://user-images.githubusercontent.com/22640902/117026641-53902f80-acd2-11eb-852a-ac478f521817.png)
