### ISSUE TITLE
Monitor rebase branch week 2

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8411]
## Description
This issue aims to keep the branch updated for later merge, introducing the latest changes in 5.0-dev branch into main epic branch..

## DoD
- [x] Branch rebase
- [x] Fix conflicts

**Comment by tinachoB** [comment]
![image](https://user-images.githubusercontent.com/22640902/117026726-66a2ff80-acd2-11eb-9731-72dbb2a67c3f.png)
