### ISSUE TITLE
[Development] AIX ossec.conf bad syntax

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#8417]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-rc3 | Conf. parser | Agent | Packages | AIX 6.1 TL4 |

Hello team,

After some fixes made in the AIX package generation issue https://github.com/wazuh/wazuh-packages/issues/725, we have detected in a testing round that the AIX agent doesn't come with a valid `ossec.conf` file because there is a syntax block without opening tags.

The full `ossec.conf` [ossec_conf_aix6.1.txt](https://github.com/wazuh/wazuh/files/6389997/ossec_conf_aix6.1.txt)
The bad syntax block:
```
    <!-- Database synchronization settings -->
    <synchronization>
      <max_eps>10</max_eps>
    </synchronization>
  </wodle>
```

**Comment by vikman90** [comment]
Generating the configuration from the template file seems to work:

```sh
./gen_ossec.sh conf agent AIX 7.2 /var/ossec
```

However, this step in the SPEC file for AIX erases the `<wodle>` block partially, and that causes the problem.

On the other hand, Syscollector is not starting in AIX:
```
2021/04/29 07:06:20 wazuh-modulesd:syscollector: ERROR: Can't load syscollector.
```

## Proposed fix

1. Do not create a default Syscollector configuration on AIX.
2. Remove the configuration patch in the SPEC file.
