### ISSUE TITLE
Create or edit a custom rule using syscheck fields

### ISSUE THREAD

**Issue by ll305** [wazuh/wazuh#8431]
Hi all, 

I am trying to create a rule that reduces the level of the Integrity checksum changed (550) rule to level 0 in cases where a specific process modifies the monitored files, however I believe that the syscheck field I am using in the rule is incorrect.

Is it possible to identify all fields decoded by the `<decoded_as> syscheck_integrity_changed </decoded_as>` of rule 550?

I think that with that it would be possible to use the field in the created rule.

Below is an example of how I initially wrote the rule:

```
<rule id="100123" level="0">
    <if_sid>550</if_sid>
    <field name="syscheck.audit.process.name">/usr/bin/vim.basic</field>
    <description>Ignoring file edit.</description>
</rule>
```

I also tried with the field generated by the audit:

```
<rule id="100123" level="0">
    <if_sid>550</if_sid>
    <field name="audit.exe">/usr/bin/vim.basic</field>
    <description>Ignoring file edit.</description>
</rule>
```

In neither case was the rule enforced.

Has anyone been through this and can help me?

Thank's all.

**Comment by mcarmona99** [comment]
Hi @ll305 ,

You are right, you are using a wrong name to reference the audit `process_name` field.

In your case you have to use `field="process_name"`.

Your rule should look similar to this one:

```
<rule id="100123" level="0">
    <if_sid>550</if_sid>
    <field name="process_name">/usr/bin/touch</field>
    <description>Ignoring file edit.</description>
</rule>
```

This rule, as an example, will ignore FIM events with `process_name = /usr/bin/touch`.


These are the syscheck fields and the names you have to use to reference them:

```
FIM_FILE = "file"
FIM_SIZE = "size"
FIM_HARD_LINKS = "hard_links"
FIM_MODE = "mode"
FIM_PERM = "perm"
FIM_UID = "uid"
FIM_GID = "gid"
FIM_MD5 = "md5"
FIM_SHA1 = "sha1"
FIM_UNAME = "uname"
FIM_GNAME = "gname"
FIM_MTIME = "mtime"
FIM_INODE = "inode"
FIM_SHA256 = "sha256"
FIM_DIFF = "changed_content"
FIM_ATTRS = "win_attributes"
FIM_CHFIELDS = "changed_fields"
FIM_TAG = "tag"
FIM_SYM_PATH = "symbolic_path"

FIM_USER_ID = "user_id"
FIM_USER_NAME = "user_name"
FIM_GROUP_ID = "group_id"
FIM_GROUP_NAME = "group_name"
FIM_PROC_NAME = "process_name"
FIM_PROC_PNAME = "parent_name"
FIM_AUDIT_PCWD = "parent_cwd"
FIM_AUDIT_CWD = "cwd"
FIM_AUDIT_ID = "audit_uid"
FIM_AUDIT_NAME = "audit_name"
FIM_EFFECTIVE_UID = "effective_uid"
FIM_EFFECTIVE_NAME = "effective_name"
FIM_PPID = "ppid"
FIM_PROC_ID = "process_id"

FIM_REGISTRY_ARCH = "arch"
FIM_REGISTRY_VALUE_NAME = "value_name"
FIM_REGISTRY_VALUE_TYPE = "value_type"
FIM_ENTRY_TYPE = "entry_type"
```

I hope this helps!
Let me know if you have more questions!

**Comment by ll305** [comment]
Hi, @mcarmona99 

Thank you very much `process_name` worked perfectly. That was what was missing.

Thanks also for the syscheck field list, it would certainly be my next question. haha.

Thanks.
