### ISSUE TITLE
[Development] v4.2.0-rc4 AIX agent doesn't switch protocol

### ISSUE THREAD

**Issue by jcruzlp** [wazuh/wazuh#8459]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-rc4 | Agent | Packages | Packages | AIX |

When the connection protocol is changed to UDP from TCP, it doesn't change and still connecting using TCP protocol instead, generating the following errors in logs:

```
2021/04/30 03:38:28 ossec-agentd: INFO: Trying to connect to server (54.81.238.49:1514/tcp).
2021/04/30 03:38:28 ossec-agentd: ERROR: (1216): Unable to connect to '54.81.238.49:1514/tcp': 'Connection refused'.
2021/04/30 03:38:38 ossec-agentd: INFO: Trying to connect to server (54.81.238.49:1514/tcp).
2021/04/30 03:38:38 ossec-agentd: ERROR: (1216): Unable to connect to '54.81.238.49:1514/tcp': 'Connection refused'.
```

[agent.conf.txt](https://github.com/wazuh/wazuh/files/6404184/agent.conf.txt)

[manager.conf.txt](https://github.com/wazuh/wazuh/files/6404185/manager.conf.txt)

Doing another test, it connects using UDP, but it doesn't change to TCP.
The same error happens in version 4.1.4, but in version 4.1.5 works fine.

**Comment by vikman90** [comment]
Hi team,

As we tried again, we managed to connect the agent to the manager via TCP:

```
2021/04/30 04:35:53 wazuh-agentd[401464] start_agent.c:95 at connect_server(): INFO: Trying to connect to server (54.81.238.49:1514/tcp).
2021/04/30 04:35:53 wazuh-agentd[401464] start_agent.c:396 at agent_handshake_to_server(): INFO: (4102): Connected to the server (54.81.238.49:1514/tcp).
```

Then we changed the agent´s config to UDP, and it tried to connect via UDP:
```
2021/04/30 04:53:10 ossec-agentd[680106] start_agent.c:95 at connect_server(): INFO: Trying to connect to server (54.81.238.49:1514/udp).
```

After, we switched the manager to UDP, and the agent managed to connect:
```
2021/04/30 04:59:49 ossec-agentd[475192] start_agent.c:95 at connect_server(): INFO: Trying to connect to server (54.81.238.49:1514/udp).
2021/04/30 04:59:49 ossec-agentd[475192] start_agent.c:396 at agent_handshake_to_server(): INFO: (4102): Connected to the server (54.81.238.49:1514/udp).
```

@wazuh/cicd followed the same steps, with the same results.
Closing this issue.
