### ISSUE TITLE
[Development] Windows MSI installer doesn't show the License text

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#8460]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-rc4 | MSI installer | Agent | Packages | Windows 10 |

Hello team,

We have detected that Windows MSI 4.2.0 installer show bad license text during graphical installation setup.
![image](https://user-images.githubusercontent.com/10661307/116676658-87541800-a9a7-11eb-86cc-208be4bc6489.png)

Regards.

**Comment by vikman90** [comment]
This is a regression caused by #7564.
