### ISSUE TITLE
Error after sending restart request. The cluster restarts but the API does not

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8482]
Hi team,

During the sixth test we have detected that after sending a restart request through the API, one of the worker nodes has restarted the cluster service but not the API one. This should not be possible, we need to investigate it.

API trace (last restart **14:02:35**):
```
2021/04/30 14:02:35 INFO: Listening on 0.0.0.0:55000..
```

Cluster trace (last restart **14:17:53**):
```
2021/04/30 14:17:53 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2021/04/30 14:17:53 DEBUG: [Local Server] [Keep alive] Calculating.
2021/04/30 14:17:53 DEBUG: [Local Server] [Keep alive] Calculated.
```

More information here: https://github.com/wazuh/wazuh/issues/8439#issuecomment-830116285

Regards

**Comment by mcarmona99** [comment]
## Issue update

Normal behaviour when restarting a Wazuh cluster (2 workers):

- worker1 and 2 `cluster.log`: 

```
2021/06/29 11:57:52 INFO: [Cluster] [Main] SIGNAL [(15)-(SIGTERM)] received. Exit...
...
2021/06/29 11:58:06 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
...
2021/06/29 11:58:06 ERROR: [Local Server] [Main] Could not connect to master. Trying again in 10 seconds.
...
2021/06/29 11:58:16 INFO: [Worker worker1] [Main] Sucessfully connected to master.
```

- worker1 and 2 `api.log`: 

```
2021/06/29 11:58:05 INFO: Listening on 0.0.0.0:55000..
```

I have tried to reproduce the error explained in this issue 2 times with the cluster performance pipeline.


### Tests:

Test cluster performance build with **2000 agents** and **6 workers** to see if this error happens again and to investigate it.

- master `api.log` contains:

```
2021/06/30 07:48:31 INFO: wazuh 172.31.50.140 "PUT /cluster/restart" with parameters {} and body {} done in 0.038s: 200
2021/06/30 07:48:48 INFO: Listening on 0.0.0.0:55000..
```

The **PUT /cluster/restart** request was done at 07:48:31. Therefore, all workers APIs have been restarted and each api.log file has a `Listening on ...` log after that timestamp. Each cluster.log should also contain a specific log indicating clusterd was restarted: `Serving on c-internal.sock`.

- worker1 logs:

`2021/06/30 07:48:47 INFO: Listening on 0.0.0.0:55000..
`
`2021/06/30 07:48:51 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
`
- worker2 logs:

`2021/06/30 07:48:47 INFO: Listening on 0.0.0.0:55000..
`
`2021/06/30 07:48:50 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
`
...

All workers have restarted API and clusterd properly (in both Cluster performance runs).


I have also tried to reproduce this in a local docker environment with 10 workers. This error is not happening in this environment. When I restart the cluster, all the workers APIs and clusterd daemons are restarted properl.

Regards,
Manuel.
