### ISSUE TITLE
Possible race condition when deleting agents

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#8497]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | N/A | Manager | Any | Any |

Hello team,

We have detected a possible bug that occurs when deleting agents through the API using `authd`.

In this case, we have an environment with 30000 agents (+3 added in the tests with the API), and we send an API request to delete all of them. This request is known to scale poorly and it is not able to delete all the agents before getting timed out. However, the thread in charge of deleting the agents keeps working and deleting agents. At this point, the API receives a request to restart the master node.

When this occurs, we are left with discrepancies between the information stored in the `client.keys` and the files present for `agent-groups` folder, as we can see in the image below:

![image](https://user-images.githubusercontent.com/48716145/116977441-bbd71500-acc2-11eb-8a0a-38662c3c2727.png)

There were 494 agents deleted from `client.keys` but only 11 files deleted from `agent-groups` folder.

We can also see below an agent that is not stored in the `client.keys` but has an `agent-group` file:
```
[root@ip-172-31-7-5 etc]# grep "16875 " /var/ossec/etc/client.keys 
[root@ip-172-31-7-5 etc]# 

[root@ip-172-31-7-5 agent-groups]# cat 16875
default,new_test_group
```

`wazuh-modulesd` should always ensure that we do not have dangling files in the agent-groups folder (files belonging to non existing agents), this is important because otherwise the cluster tries to synchronize these files continuously, without success. A fix related to this was included in https://github.com/wazuh/wazuh/issues/7856. 

It might be happening that the agents are still alive in the database, and that is why `wazuh-modulesd` does not delete the `agent-groups `files. 

This is creating a huge issue in the cluster, as fully explained below:

- The master node detects changes in client.keys file (494 agents deleted) and sends the new client.keys file to every worker.
```
2021/05/03 12:32:28 INFO: [Worker Test_cluster_performance_B183_manager_2] [Integrity sync] Files to create in worker: 0 | Files to update in worker: 1 | Files to delete in worker: 0 | Files to receive: 0
```
- The workers detect a change in the client.keys, look for the diff and start to delete those agents accordingly:
```
2021/05/03 15:10:26 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Worker does not meet integrity checks. Actions required.
2021/05/03 15:10:26 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Updating local files: Start.
2021/05/03 15:10:26 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 0 missing files to update from master.
2021/05/03 15:10:26 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 1 shared files to update from master.
2021/05/03 15:10:27 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Removing files from 494 agents
```
- In the next integrity cycle, the master detects that the workers are missing a bunch of agent-group files, (494 - 11 properly deleted from both client.keys and agent-groups, totaling 483) and it sends those files to the workers to update:
```
2021/05/03 15:11:03 INFO: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Files to create: 483 | Files to update: 0 | Files to delete: 0 | Files to send: 0
2021/05/03 15:11:03 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Worker does not meet integrity checks. Actions required.
2021/05/03 15:11:03 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Updating local files: Start.
2021/05/03 15:11:03 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 483 missing files to update from master.
```
- However, and since the workers do not have those agents in the client.keys files, nor wazuh-db, wazuh-modulesd deletes them immediately after creation, and the operation is repeated for the next cycle, and for each one afterwards:
```
2021/05/03 15:11:16 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 481 missing files to update from master.
2021/05/03 15:11:27 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 481 missing files to update from master.
2021/05/03 15:11:39 DEBUG: [Worker Test_cluster_performance_B184_manager_1] [Integrity sync] Received 481 missing files to update from master.
```

As a summary, I see two clear errors here, first, we could never end up with different agents in `client.keys vs database` in the master-node, and second, the worker nodes should not be in charge of detecting which agents have been deleted by using diff in the client.keys file changes(https://github.com/wazuh/wazuh/issues/8327).

**Comment by Selutario** [comment]
# Issue update

Hi team!

We have found a few new things about this. It can be reproduced following the steps below:

## Description
### 1. Register an agent
- Agent 002 is registered and its agent-groups file is created (`/var/ossec/queue/agent-groups/002`).

### 2. Stop agent
- If we try to query the agent inside `global.db`, it exists too.
- Group file still exists. 

### 3. Delete agent from client.keys
- As soon as agent is deleted from `client.keys` file, it is removed from `global.db` and cannot longer be retrieved.
- Group file still exists (it should have been deleted)

These logs show up in the `ossec.log`:
```
2021/05/04 11:28:16 wazuh-modulesd[59235] wdb_global_helpers.c:1267 at wdb_remove_agent_db(): DEBUG: (1129): Could not unlink file 'var/db/agents/002-jmv74211-PC.db-shm' due to [(2)-(No such file or directory)].
2021/05/04 11:28:16 wazuh-modulesd[59235] wdb_global_helpers.c:1271 at wdb_remove_agent_db(): DEBUG: (1129): Could not unlink file 'var/db/agents/002-jmv74211-PC.db-wal' due to [(2)-(No such file or directory)].
```

### 4. Restart manager
- Group file is deleted

This log show up in the `ossec.log` (only after restarting):
```
2021/05/04 11:30:29 wazuh-modulesd:database[79834] wm_database.c:400 at wm_clean_dangling_groups(): DEBUG: Deleting dangling group file '002'.
```

## Endless syncing 
As explained above it is possible that the agents are deleted from the `client.keys` but the files are kept until restart. 

When this happens, the master will be sending the updated `client.keys` to each worker. `wazuh-clusterd`, which is in charge of reviewing which agents have been deleted in the `client.keys` and delete its files, will delete all the agent-groups of files missing in the `client.keys`. However, as long as the agent-groups files are not deleted in the master node, they will be sent to the workers (and later deleted) again and again.

## Fix/proposal
If we manually create a file inside agent-groups, for instance `touch /var/ossec/queue/agent-groups/003`, it is **instantly** removed by modulesd:
```
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:737 at wm_inotify_start(): DEBUG: inotify: i='0', name='003', mask='8', wd='2'
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:805 at wm_inotify_push(): DEBUG: Adding 'queue/agent-groups/003' to path table.
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:836 at wm_inotify_pop(): DEBUG: Taking 'queue/agent-groups/003' from path table.
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:489 at wm_sync_file(): DEBUG: Synchronizing file 'queue/agent-groups/003'
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:521 at wm_sync_file(): DEBUG: Deleting dangling group file '003'.
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:737 at wm_inotify_start(): DEBUG: inotify: i='0', name='003', mask='512', wd='2'
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:805 at wm_inotify_push(): DEBUG: Adding 'queue/agent-groups/003' to path table.
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:836 at wm_inotify_pop(): DEBUG: Taking 'queue/agent-groups/003' from path table.
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:489 at wm_sync_file(): DEBUG: Synchronizing file 'queue/agent-groups/003'
2021/05/04 12:29:35 wazuh-modulesd:database[79834] wm_database.c:521 at wm_sync_file(): DEBUG: Deleting dangling group file '003'.
```

We need that all agent-related files are instantly deleted when they are removed from the `client.keys` file, the same way that when the file is manually created.

Regards,
Selu.
