### ISSUE TITLE
Wrong timezone in `date_add` in daylight saving time 

### ISSUE THREAD

**Issue by epol** [wazuh/wazuh#8502]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4 | authd or wazuhDB | Manager | Packages | CentOS Linux 7.6 |

Hello,

to explain this issue it's relevant that we are in the Europe/Rome timezone, so at the moment (with DST) we are in CEST (UTC+2) and in winter we are in CET (UTC+1).

After adding an agent (using authd) at 9:55 (local time, so 7:55 UTC) the wazuh plugin showed that the agent was registerd at 10:55. Reading the Wazuh API data I see that the value returned by the manager is 8:55 UTC.

Using the query `select id,date_add from agent;` on the sqlite database `/var/ossec/queue/db/global.db` I see that the registered date is `1620032142` (as a unix timestamp it convertes to 8:55 UTC), the file `/var/ossec/queue/agents-timestamp` contains `2021-05-03 09:55:42`.

So I suppose that for some reason authd or wazudb is writing the wrong timestamp in the DB.

On the wazuh manager server the timezone is CEST and the time is correct, in elasticsearch i see the logs starting from 9:56 so there wasn't time syncronization issues at the moment the agent was registered.

I don't have access to the server where the agent was installed, but from its log (it's a windows server that logs datetime in UTC format in the eventchannel events) I can see that the time was syncronized enough (maybe it's 30 seconds off the right time), but I haven't checked the timezone.

Can I do anything else to futher debug this issue? It isn't a functional issue (more a cosmetic one), but it can mislead users.

Thank you and best regards.

**Comment by pereyra-m** [comment]
Hello @epol!

Thank you very much for reporting this issue, this is important.

It was also reported here https://github.com/wazuh/wazuh/issues/8565, and there are another issues related (https://github.com/wazuh/wazuh/issues/4605 and https://github.com/wazuh/wazuh/issues/4365).

We'll be working on this and it will be fixed as soon as possible.
I apologize for the inconveniences.
Regards.

**Comment by pereyra-m** [comment]
Hi again!

This issue has been solved in Wazuh v4.2.2 in https://github.com/wazuh/wazuh/pull/9705.
Please contact us again if you still experience troubles.

Regards.

**Comment by epol** [comment]
Thank you for the update, I'm glad to hear that it has been solved!

Best regards.
