### ISSUE TITLE
Exploratory test in Windows (XP, W7, WServer 2016 and W10)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8517]
## Description
Execute defined charter to verify in high level the correct functionality.

Manager: manager-siteox.wazuh.info

## DoD 
- [x] Run charters.
- [x] Post charter results as evidence.

## Charter
- Check libwazuhext and libwazuhshared deployment.
- Validate active response run as well local and e2e for restart-agent.
- Compare size of new installers with pre-release versions -> 
[Link 4.2](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.2.0-1.msi)
[Footprint link](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/windows/wazuh-agent-4.2.0-footprint.msi)
- Compare deployed new agent size vs pre-release version.
- Only for Windows 10 -> Imports dll lists PE-bear / ldd-otool results for each binary Wazuh/bin and Wazuh/active-response/bin
- Test upgrade 4.1.5 to 4.2

**Comment by konangc87** [comment]
Windows 10:
* Fresh install:
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/063a695d-f9ce-4896-a988-232f2f7f6cfc)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/0877f4f2-0fb1-4d24-b2b5-ebc897a53762)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/3cf3074f-ae56-4d0a-92e2-f2a69f172a59)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/d4ffe44a-1a1e-4227-8e6a-3937bfdde26e)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/9f02426b-534a-4ed6-9f27-6173b78e175d)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/2e543340-7ae9-4670-9e14-980cc8865007)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/078997e1-5e1b-4908-8261-bfa9961df3b1)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/da6f19d8-0bb5-478b-8510-625e31046925)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/cfd67621-30a2-4790-8074-e8b94e0441dc)

**Comment by Dwordcito** [comment]
Windows 7

* Fresh Install
![imagen](https://user-images.githubusercontent.com/14300208/118022676-f714bc00-b332-11eb-800f-6605e8448697.png)
![imagen](https://user-images.githubusercontent.com/14300208/118022916-4bb83700-b333-11eb-94a4-396610d19883.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023017-69859c00-b333-11eb-922e-92003cbfeaaf.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023076-7bffd580-b333-11eb-92ad-57f60bc196ac.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023118-891cc480-b333-11eb-8038-79e706d54b02.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023146-946ff000-b333-11eb-932c-abafb97df6b5.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023330-d00aba00-b333-11eb-85a2-f7fee161da0c.png)
![imagen](https://user-images.githubusercontent.com/14300208/118023436-eca6f200-b333-11eb-9a03-d85cba42b24b.png)

Bug:
#8633

**Comment by tinachoB** [comment]
- **Windows XP**

**Fresh Install**
![image](https://user-images.githubusercontent.com/22640902/118026597-5aa0e880-b337-11eb-915d-ef83c4cd4bdb.png)
![image](https://user-images.githubusercontent.com/22640902/118026641-67bdd780-b337-11eb-9b92-25c38c5abacf.png)
![image](https://user-images.githubusercontent.com/22640902/118026831-a8b5ec00-b337-11eb-9fe7-15f792a11b1d.png)
![image](https://user-images.githubusercontent.com/22640902/118026726-845a0f80-b337-11eb-8c7a-5b9da26c5e0b.png)

**Upgrade from 4.1.5**
Without taking into account the uninstall bug, the upgrade works ok as well as the Wazuh functionality.

Bug:
#8633 Wazuh agent on Windows7 / Windows XP doesn't uninstall

**Comment by konangc87** [comment]
**Windows server 2016:**
**Fresh install:**
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/882173ad-f86d-42fe-97ad-872a6ceec2f4)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/57d415a1-a564-471d-be4d-a4ad61eed202)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/cc0ffd21-7c22-4ead-9960-b0f1a9572739)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/2644edc4-acba-4f3d-a091-bb25edbcb346)
**Upgrade from 4.1.5:**
Stopping the old service manually and removing it the upgrade can be completed, probably related to #8631. Besides the known issue with the upgrade and the service stop, everything worked as expected.
