### ISSUE TITLE
Exploratory test in Unix specials (HPUX 11.31, Solaris 10, Solaris 11, AIX 6.2)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8519]
## Description
Execute defined charter to verify in high level the correct functionality.

Manager: manager-siteox.wazuh.info

## DoD 
- [x] Run charters.
- [x] Post charter results as evidence.

## Charter
- Check libwazuhext and libwazuhshared deployment.
- Validate active response run as well local and e2e for restart-agent.
- Compare size of new installers with pre-release versions -> 
[HP-UX](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/hp-ux/wazuh-agent-4.2.0-1-hpux-11v3-ia64.tar)
[Solaris10](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/solaris/i386/10/wazuh-agent_v4.2.0-sol10-i386.pkg)
[Solaris11](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/pre-release/solaris/i386/11/wazuh-agent_v4.2.0-sol11-i386.p5p)
[AIX](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/aix/wazuh-agent-4.2.0-1.aix.ppc.rpm)
- Compare deployed new agent size vs pre-release version.
- Imports dll lists PE-bear / ldd-otool results for each binary Wazuh/bin and Wazuh/active-response/bin
- Test upgrade from 4.1.5

**Comment by Dwordcito** [comment]
Package size 4.2.0:
![imagen](https://user-images.githubusercontent.com/14300208/118029054-2549ca00-b33a-11eb-8957-b45efdaf686f.png)
![imagen](https://user-images.githubusercontent.com/14300208/118033289-0568d500-b33f-11eb-9950-f492f7fc25d6.png)
![imagen](https://user-images.githubusercontent.com/14300208/118033768-95a71a00-b33f-11eb-85f2-ab9545b071a1.png)
![imagen](https://user-images.githubusercontent.com/14300208/118033836-a5bef980-b33f-11eb-862a-9d652a27e91f.png)
![imagen](https://user-images.githubusercontent.com/14300208/118033881-b3747f00-b33f-11eb-88f9-b92a8f87744d.png)
![imagen](https://user-images.githubusercontent.com/14300208/118033997-d9018880-b33f-11eb-800d-f8d2de7a5fca.png)
![imagen](https://user-images.githubusercontent.com/14300208/118034013-e159c380-b33f-11eb-9648-ae43ddb43610.png)
![imagen](https://user-images.githubusercontent.com/14300208/118034114-fcc4ce80-b33f-11eb-86b7-6632bea2b146.png)
![imagen](https://user-images.githubusercontent.com/14300208/118034155-06e6cd00-b340-11eb-9651-c1633b365c65.png)

**Comment by tinachoB** [comment]
**Solaris 11**

- **Package size 4.2.0:**
![image](https://user-images.githubusercontent.com/22640902/118037400-2b44a880-b344-11eb-948c-c01d645a9035.png)

- **Active Response binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118037558-6515af00-b344-11eb-903c-702d27006f65.png)

- **Active Response binaries libraries loaded:**
![image](https://user-images.githubusercontent.com/22640902/118037723-99896b00-b344-11eb-9692-fc17b73b7bb0.png)
![image](https://user-images.githubusercontent.com/22640902/118037777-ae65fe80-b344-11eb-8ec1-b08bb0745e8e.png)
![image](https://user-images.githubusercontent.com/22640902/118037858-c63d8280-b344-11eb-8a25-3a1823b0666b.png)
![image](https://user-images.githubusercontent.com/22640902/118037933-dce3d980-b344-11eb-8036-f7431cf61fa2.png)
![image](https://user-images.githubusercontent.com/22640902/118038031-fab13e80-b344-11eb-99ff-419e0975def0.png)
![image](https://user-images.githubusercontent.com/22640902/118038117-161c4980-b345-11eb-9b02-613f469fc487.png)
![image](https://user-images.githubusercontent.com/22640902/118038135-203e4800-b345-11eb-8a79-33129d0df15f.png)

**Comment by konangc87** [comment]
**AIX**
**Fresh Install**
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/21c493a0-165d-466b-bc5d-fb30f03a6521)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/26e9e6ea-e257-4879-b0f7-bb51a00212b6)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/f9cd5e33-bd57-442f-8230-cc87119fb70a)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/a909d499-0f3c-402a-a7e0-979b001ae605)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/604193e2-52f0-4f2b-a30c-ca75268e03dd)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/6a45d301-7c26-4471-829f-b22ae6c988fc)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/f56ec690-d0c6-4ff3-96f2-1496ab30c4c1)
**Upgrade from 4.1.5**
Worked as expected.
* there were some messages while upgrading using rpm -U:
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/2f0faef6-8162-4e73-9d23-05acfb4aa226)

Issue found: Cannot find libgcc_s.a(shr.o) on every active-response binaries.

**Comment by tinachoB** [comment]
**------------------------------------------------------**
**------------------    HP-UX   -------------------------**
**------------------------------------------------------**

- **Package size 4.2.0:**
![image](https://user-images.githubusercontent.com/22640902/118282235-74ac0980-b4a4-11eb-8f9f-e45961b8e682.png)

- **Wazuh binaries libraries loaded:**
![image](https://user-images.githubusercontent.com/22640902/118282895-277c6780-b4a5-11eb-9f37-dc273f4f1677.png)

- **Active Response binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118282301-87bed980-b4a4-11eb-8c2a-26b02b5a8c3a.png)

- **Active Response binaries libraries loaded:**
![image](https://user-images.githubusercontent.com/22640902/118282450-a91fc580-b4a4-11eb-97c8-e4bf516e65a7.png)
![image](https://user-images.githubusercontent.com/22640902/118282553-c785c100-b4a4-11eb-92c3-e7793c89740e.png)
![image](https://user-images.githubusercontent.com/22640902/118282696-f0a65180-b4a4-11eb-8a44-f398b98ad15f.png)

- **Wazuh Active Responses execution:**
![image](https://user-images.githubusercontent.com/22640902/118282148-5a722b80-b4a4-11eb-98a8-ef806a1d64ad.png)
![image](https://user-images.githubusercontent.com/22640902/118282190-6827b100-b4a4-11eb-9968-e2c715c55798.png)
