### ISSUE TITLE
Exploratory test in bsd based (MacOS Sierra, MacOS BigSur, freeBSD and openBSD)

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8520]
## Description
Execute defined charter to verify in high level the correct functionality.

Manager: manager-siteox.wazuh.info

## DoD 
- [x] Run charters.
- [x] Post charter results as evidence.

## Charter
- Check libwazuhext and libwazuhshared deployment.
- Validate active response run as well local and e2e for restart-agent.
- Compare size of new installers with pre-release versions -> 
[macOS](https://s3-us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/macos/wazuh-agent-4.2.0-footprint.pkg)
- Compare deployed new agent size vs pre-release version.
- Only for Ubuntu, Centos 5 and Centos 8 -> Imports dll lists PE-bear / ldd-otool results for each binary Wazuh/bin and Wazuh/active-response/bin

**Comment by tinachoB** [comment]
**freeBSD**

**Fresh install**
- **Wazuh binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118131193-963dc000-b3d4-11eb-8a77-8996b6af8020.png)

- **Wazuh binaries libraries loaded:**
![image](https://user-images.githubusercontent.com/22640902/118131510-fe8ca180-b3d4-11eb-8721-fee3949b0132.png)

- **Wazuh Active Responses binaries size:**
![image](https://user-images.githubusercontent.com/22640902/118131259-afdf0780-b3d4-11eb-8b22-17aae5cab208.png)

- **Wazuh Active Responses libraries loaded:**
![image](https://user-images.githubusercontent.com/22640902/118131722-414e7980-b3d5-11eb-82f1-0db049453c17.png)
![image](https://user-images.githubusercontent.com/22640902/118131895-778bf900-b3d5-11eb-98f8-f044c55921fb.png)

- **Wazuh Active Responses functionality:**
![image](https://user-images.githubusercontent.com/22640902/118132440-144e9680-b3d6-11eb-8cd8-56697a7f3a84.png)
![image](https://user-images.githubusercontent.com/22640902/118132524-2af4ed80-b3d6-11eb-9567-147c318f1a42.png)
Executing active response `restart-wazuh` manually:
![image](https://user-images.githubusercontent.com/22640902/118132871-8cb55780-b3d6-11eb-98a0-dbd1957b96c8.png)

**Comment by konangc87** [comment]
**OpenBSD**
**Fresh install from sources**
Issues found: missing header <sstream> in timeHelper.h and missing sysinfo lib dep in data providers test tool for OpenBSD.
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/1077ef7a-a42a-420e-87f5-0a03a6c7b788)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/c0a8ed76-f170-4cdb-a6d4-502205730816)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/7a923035-6cd5-4661-a02e-918c1748ca23)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/9fc2d02b-c004-4cc0-b217-f6147ed7de6e)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/4e55a4f3-7399-4103-8b5d-1865d1f646bc)
![image.png](https://images.zenhubusercontent.com/5ef3790e9f70755f0093b99c/1163a706-26e8-4719-a74f-bb7e9de02d64)
** Upgrade from 4.1.5 from sources**
Worked as expected.

**Comment by tinachoB** [comment]
**------------------------------------------------------**
**--------------    macOS Sierra   -------------------**
**------------------------------------------------------**

**Comment by Dwordcito** [comment]
------------------------------------------------------
----------------- macOS bigsur ---------------------
------------------------------------------------------

**Fresh install**
-- Deployed files
![imagen](https://user-images.githubusercontent.com/14300208/118176723-2ba67780-b408-11eb-8bf7-fc0c9e44105e.png)

-- bin wazuh
![imagen](https://user-images.githubusercontent.com/14300208/118177435-10883780-b409-11eb-950c-0d8a8b5a7b5e.png)

-- active-response bin
![imagen](https://user-images.githubusercontent.com/14300208/118177650-5a711d80-b409-11eb-97a9-b55d411fa80a.png)

-- execute active response restart.
![imagen](https://user-images.githubusercontent.com/14300208/118178188-087cc780-b40a-11eb-933b-95e87032271a.png)

-- Active response log
![imagen](https://user-images.githubusercontent.com/14300208/118178258-1fbbb500-b40a-11eb-8240-ee0602c7e900.png)


**Upgrade from 4.1.5 from sources**
Worked as expected.
