### ISSUE TITLE
agent registration error with authd

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#854]
### Note:-I have do the same in other datacenter there are everything is work properly with clustering.
But i have setup it same in other two datacenters then i got below error. Could you help me what i am doing wrong.
### getting below error--
[root@server-1]# /var/ossec/bin/agent-auth -m 10.1.1.1
2018/06/27 11:42:34 agent-auth: INFO: Started (pid: 24533).
INFO: Using password specified on file: /var/ossec/etc/authd.pass
INFO: Connected to 10.1.1.1:1515
INFO: Using agent name as: server-1
INFO: Send request to manager. Waiting for reply.
ERROR: Unable to create key. Either wrong password or connection not accepted by the manager.
INFO: Connection closed.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu ,

` INFO: Using password specified on file: /var/ossec/etc/authd.pass`

you seem to have a password file meaning that you have to provide the password when registering the agent.

`[root@server-1]# /var/ossec/bin/agent-auth -m 10.1.1.1 -P YOUR_PASSWORD`

Best regards.

**Comment by gyanprakashsahu** [comment]
@TJOSERAFAEL **Thanks.**.
I have more query for agent registration.
I am using ssl certificate for agent registration which is working fine for me with where i use direct master ip.
if i have use Load Balancer then what port and protocol would need for allow in LB.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu ,

the only thing that you have to configure is the LB itself. Make sure the LB redirects the traffic to the right manager and all will be fine.

Best regards.
