### ISSUE TITLE
Wazuh web app reports agent registration dates one hour later than that of actual registration time

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#8565]
| Wazuh | Elastic | Rev |
| ----- | ------- | --- |
| 4.1.4   | 7.10.2     | 4105 |

The Wazuh web app agents screen lists for each agent both the **Registration time** and **Last keep alive**, expressed relative to the time zone of the local web browser.  However, the **Registration time** appears to always be reported as one hour later (local web browser time) than when the agent was actually registered.  

For example, at 15:44 EST (my local time), I registered this agent and then it immediately connected to the manager.  The Wazuh web agents screen moments later showed an accurate EST time for the **Last keep alive** (as 1-2 minutes ago), but showed the **Registration date** as 1 hour in the future.  Likely there is an off-by-one error in the time rendering code in the web interface.

![image](https://user-images.githubusercontent.com/13170654/115456359-136c7f80-a1f1-11eb-993b-71e9f66f2c8f.png)

I have reproduced this same issue on two different Wazuh stacks, one on 4.0.4 and one on 4.1.4, with each manager in a different local timezone.  In both cases the **Registration time** was reporting as one hour later than correct.

**Comment by pereyra-m** [comment]
Hi.

This issue has been solved in Wazuh v4.2.2 in https://github.com/wazuh/wazuh/pull/9705.
Please contact us again if you still experience troubles.

Regards.
