### ISSUE TITLE
Improving Wazuh-Agent with using nxlog-ce codebase

### ISSUE THREAD

**Issue by commandline-be** [wazuh/wazuh#8567]
|Wazuh version|Component|
|Future|Wazuh-Agent|
| X.Y.Z-rev | Wazuh component |

Following many mentions in forums, repeat concerns of extra binaries required for Wazuh-Agent, i'd appreciate serious thought be put into onboarding the nxlog-ce codebase. It has that many features it is perplexing and could well fix annoyances which now require extra binaries, configuration, remove limitations and so on. Most of which are not remotely present in Wazuh-Agents today, espcially when it comes to unified log onboarding, integration and so on.

https://nxlog.co/products/nxlog-community-edition/download

Br,

JL

**Comment by AdriiiPRodri** [comment]
Hi @commandline-be,

I apology for the delay in the response. Wazuh agents, as well as managers, increase their capabilities with each release. You can check the product roadmap to get an idea: https://github.com/wazuh/wazuh/projects/41.

Also, you can create an issue asking for some functionality, request a change or give ideas for improvement, all of them will be studied as soon as possible. All the NXLog functionalities that you would like to see in Wazuh can be indicated in as many issues as you need.

Best regards,
Adrián Peña
