### ISSUE TITLE
Make the Vulnerability Detector module obtain the packages to be scaned in an atomic way - Exploratory Testing

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#8573]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/8529, a mechanism to get all the packages installed on an endpoint in an atomic way is implemented. Having said that, and exploratory testing over the Wazuh DB and the Vulnerability Detector modules should be done. This testing session should ensure that:

- When requesting packages to Wazuh DB, the operation is atomic.
- When requesting hotfixes to Wazuh DB, the operation is atomic.
- When a client spends more than one second to get all the data, Wazuh DB cancels the operation by timeout and logs this information.
- The Vulnerability Detector scans, in the three possible types (baseline, full scan, and partial scan) work as expected.

**Comment by pereyra-m** [comment]
### Proposed test

It would be necessary to test the `wdb_query_clear` method, just in case the agent doesn't send a **cheksum** field in the payload.

**Comment by DProvinciani** [comment]
### Proposed test

It would be necessary to test whether the Vulnerability Detector module calculates multiples checksums. If so, we would need to update the `last_completion` value when the checksum is calculated and is equal to the last one received from the agent.

**Comment by palaciosjeremias** [comment]
Issue found:
**scan_ctx->package_scan** is being set even if the package list is returned empty (typical scenario of a partial scan with every package already tagged as triaged). This triggers a vulnerability scan of the packages that should be avoided.

**Comment by palaciosjeremias** [comment]
**Note:**
It was observed that exists a time window between the OS hotfixes request and the OS triaged set. If an update of the hotfixes, falls into this time window, Vulnerability Detector will last until the next full scan or the next OS update to detect the new change and perform a new scan. This will not generate any false positive but can generate an unexpected delay until the change is reflected into a new scan.

**Comment by pereyra-m** [comment]
### Findings

- There were two repeated `INSERT` commands in the `schema_upgrade_v8.sql` file. They were removed in #8677 
- When there is a **syscollector** scan in progress, it can take time to finish and the retry logic prints a `WARNING` message too soon. This issue is described in #8686

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8677 was merged.
