### ISSUE TITLE
FIM alerts of owner change when `LookupAccountSid` fails

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#8575]
|Wazuh version|Component|Platform|
|---|---|---|
| 4.3.0 | Wazuh FIM | Windows |

### Description

It has been reported that whenever a lookup operation on an SID fails FIM is reporting the file has changed, with the owner's user name changing into an empty string. This can happen if a file has an owner defined in AD and the machine gets disconnected from the domain, causing the SID to show up as unmapped. Once the system regains connection to the domain, the account is remapped, the lookup is successful and another alert is generated with the user name changing from an empty string back to the correct one.

### Proposed solution

There are a couple things we need to consider here:
- It could be argued that the metadata associated with a file is the SID and not the user name associated with it, therefore, a change on the user name is not necessarily a change on the file and FIM should not alert of this change.
- If we want to keep alerting on user name changes, it could be worthwhile to add an option to disable this check independently from the SID, or at least give it some granularity so that systems where this issue is observed can disable it. It could look something like this:
  - `check_owner`: Controls alerting on user id (SID on Windows, uid on *nix) and user name changes.
  - `check_owner_id`: Controls alerting on user id changes.
  - `check_owner_name`: Controls alerting on user name changes.

**Comment by antoniomanuelfr** [comment]
QA branch - 8575-fim-win-perms-improvement

**Comment by chemamartinez** [comment]
It remains the issue https://github.com/wazuh/wazuh-kibana-app/issues/3370
