### ISSUE TITLE
Collect the Windows pre-installed software by the data provider

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#8584]
### Description

Currently, the data provider gathers the installed applications in Windows agents by querying the registries generated when an application is installed.

https://github.com/wazuh/wazuh/blob/d944cf154c5aad9bf3f4b8ec2677372e97c0759e/src/data_provider/src/sysInfoWin.cpp#L536

However, packages like Internet Explorer and others are preinstalled in the Windows platforms so they have no associated registry keys being not possible to add them to the package inventory.

On the other hand, indexed vulnerabilities for those packages cannot be reported because of the previous fact.

**Comment by HanesSciarrone** [comment]
After SPIKE on the registry key used to obtain information from Internet Explored, OneDrive, and Apps packages pre-installed on Windows, the following results were obtained. 

- Internet Explore

|Registry Key | Windows 8.1 | Windows 10 | Windows 11 |
| ---------------- | :-----------------: | :-----------------:| :----------------: |
| `HKLM\SOFTWARE\Microsoft\Internet Explore ` | :green_circle: | :green_circle: | :green_circle: |

With the registry key is possible to obtain only the version of the Internet Explore, for this we must first read the `svcVersion` key and, if it doesn't exist read the `Version` key.

- OneDrve

|Registry Key | Windows 8.1 | Windows 10 | Windows 11 |
| ---------------- | :-----------------: | :-----------------:| :----------------: |
| ` HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OneDriveSetup.exe ` | :red_circle: | :green_circle: | :green_circle: |
| ` HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\A52BBA46-E9E1-435F-B3D9-28DAA648C0F6 `  | :green_circle: | :red_circle: | :red_circle: |

The location of the registry key was obtained from:

- [OneDrrive registry key in version <= Windows 8.1 ](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/1ce007d5-ba7b-4c60-ae9c-a291579e6994/how-to-tell-if-user-has-onedrive-installed?forum=wpf)
- Using `procmon` on Windows 10 and 11 with the options:

    - Process Name = SystemSettings.exe
    - Operation = RegOpenKey
    - Result = SUCCESS

![image](https://user-images.githubusercontent.com/58960358/149848829-3dbcc1bd-5daf-4570-abef-81e38ecdefbe.png)

- App installed by default
 
|Registry Key | Windows 8.1 | Windows 10 | Windows 11 |
| ---------------- | :-----------------: | :-----------------:| :----------------: |
| ` HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModel\StateRepository\Cache\package\index\PackageFullName ` | :red_circle: | :green_circle: | :green_circle: |
` HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModel\StateRepository\Cache\package\Data ` | :red_circle: | :green_circle: | :green_circle: |
| ` HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\FolderDescriptions\A52BBA46-E9E1-435F-B3D9-28DAA648C0F6 `  | :green_circle: | :red_circle: | :red_circle: |

**Comment by HanesSciarrone** [comment]
Hi Teams

Currently, Syscollector is collecting  Microsoft Edge and OneDrive information in Windows 8.1, 10, 11. I checked in the database's manager.

![image](https://user-images.githubusercontent.com/58960358/150365830-b9dae43a-6cea-417e-8c94-df2f8029bb53.png)


Best regards
Hanes

**Comment by HanesSciarrone** [comment]
After some research and testing, the result helped us to find a way to get the information from the packages. The following information can be obtained:

| Field | Windows 8.1 | Windows 10 | Windows 11 |
| ------ | :---------------: | :---------------: | :---------------: |
| Format | :green_circle: | :green_circle: | :green_circle: |
| Name | :green_circle: | :green_circle: | :green_circle: |
| Vendor | :green_circle: | :green_circle: | :green_circle: |
| Install_time | :yellow_circle: | :yellow_circle: | :red_circle: |
| Version | :green_circle: | :green_circle: | :green_circle: |
| Architecture | :green_circle: | :green_circle: | :green_circle: |
| Location | :green_circle: | :green_circle:  | :green_circle: |

- Registry

`HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\`

Inside the registry, there is a list of folders, where the folder names are the full name of the application. It is very important to only get the information from the folders that have sub-registries. The image below shows this:

![Screenshot from 2022-01-21 15-36-46](https://user-images.githubusercontent.com/58960358/150581977-bdc44cc2-778f-4e38-9c94-d497ee590027.png)

<details><summary>Name</summary>

The name of the application is with the key `ApplicationName` inside the sub-registry Capabilities that is in 

`HKCR\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\Repository\Packages\<Full name app>\<App, Application, Name app>\Capabilities\`

Sometimes the value of the `ApplicationName` key starts with `@{` characters, in this case, the application name must be looked up in another registry and the value is the key of the other registry. The new registry to look for is 

`HKCR\Local Settings\MrtCache\C:%5CProgram Files%5CWindowsApps%5C<Full-Name-Aplication>%5C<UUID>`

And we must go to the last sub-registry inside this one where it has the Name of the application. In the images below there are an example.

![Screenshot from 2022-01-21 16-29-34](https://user-images.githubusercontent.com/58960358/150588708-b1d7175e-0661-4065-84d1-cdaacf358152.png)

![Screenshot from 2022-01-21 16-31-36](https://user-images.githubusercontent.com/58960358/150589181-52c559f1-3b0c-427f-a4b5-7d9236ac9ba2.png)

</details>
