### ISSUE TITLE
Add Compliance and MITRE information to GitHub logs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8586]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Wazuh Ruleset | Manager | Packages/Sources | All |

As described [here](https://github.com/wazuh/wazuh/issues/7660), a new wodle has been created to gather GitHub audit logs and generate alerts.

GitHub audit logs ruleset, located at `0750-github_rules.xml`, are classified by category and action. Each rule has its own level, acording to Wazuh [rules classification](https://documentation.wazuh.com/current/user-manual/ruleset/rules-classification.html).

The GitHub audit logs ruleset lacks of information about MITRE techniques and PCI-DSS compliance mapping. In order to improve this ruleset in terms of security, it is necessary to introduce this information in every rule.

There are 320 rules. Each one of them needs to be analized in order to determine the proper information that needs to be added to them.

**Comment by Nekaze** [comment]
## First analysis and rules to add MITRE information
Analyzed [github events](https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#audit-log-actions). Focused on @fabamatic [suggestions made here](https://github.com/wazuh/wazuh/pull/8532#pullrequestreview-653530821)

### dependabot_alerts
**Status**: Mapped

**Comment by fabamatic** [comment]
For Codespaces create_an_org_secret, update_an_org_secret and delete_an_org_secret may be mapped to [T1098 Account Manipulation](https://attack.mitre.org/techniques/T1098/) as these [secrets ](https://docs.github.com/en/codespaces/managing-your-codespaces/managing-encrypted-secrets-for-your-codespaces#about-encrypted-secrets-for-codespaces)may have information related to user access

**Comment by Nekaze** [comment]
Reviewed all different categories and identified some others that might be MITRE mappable:

1. dependabot_security_updates_new_repos
2. enterprise
3. environment
4. git
5. hook
6. org
7. organization_domain
8. secret_scanning
9. secret_scanning_new_repos

Next step is to perform a deeper analysis on this categories and write appropiate MITRE mappings where applicable

**Comment by Nekaze** [comment]
## Second analysis and rules to add MITRE information
Analyzed [github events](https://docs.github.com/en/organizations/keeping-your-organization-secure/reviewing-the-audit-log-for-your-organization#audit-log-actions). Focused on what's mentioned [here](https://github.com/wazuh/wazuh/issues/8586#issuecomment-861572948)

[Branch ](https://github.com/wazuh/wazuh/tree/8586_add_mitre_information_to_github_rules)with the changes

### dependabot_security_updates_new_repos
**Status**: Mapped

```xml
    <rule id="91124" level="12">
        <if_sid>91123</if_sid>
        <field name="github.action">dependabot_security_updates_new_repos.disable</field>
        <description>GitHub Dependabot security updates new repos disable.</description>
        <mitre>
            <id>T1562.001</id>
        </mitre>
        <options>no_full_log</options>
        <group>git_dependabot_security_updates_new_repos</group>
    </rule>
```
### enterprise
**Status**: WIP

```xml
WIP
```

### environment
**Status**: WIP

```xml
WIP
```
### git
**Status**: WIP

```xml
WIP
```
### hook
**Status**: WIP

```xml
WIP
```
### org
**Status**: WIP

```xml
WIP
```
### organization_domain
**Status**: WIP

```xml
WIP
```
### secret_scanning
**Status**: WIP

```xml
WIP
```
### secret_scanning_new_repos
**Status**: WIP

```xml
WIP
```

**Comment by 72nomada** [comment]
Closing as this was merged by @fabamatic
