### ISSUE TITLE
wazuh make correlation rule using ip

### ISSUE THREAD

**Issue by jj4st13** [wazuh/wazuh#8592]
I know that using the same srcip and different_srcip fields, can create rules for the same or different ips.

However, if event B occurs after event A occurs, I want to display a new rule alert, but there is a condition here.
A condition is required that the dst ip of the A event must be the same as the src ip of the B event.
What to do for these conditions?

I am collecting suricata events and trying to use Wazuh.
If that's all possible, wazuh gives me all the siem features I need.

**events**
```
{
    "timestamp" : "1"
    "event": "event-A",
    "src ip": "10.0.0.1"
    "dst ip": "10.0.0.3"
    "direction": "inbound"
}
{
    "timestamp" : "2"
    "event": "event-B",
    "src ip": "10.0.0.2"
    "dst ip": "10.0.0.11"
    "direction": "inbound"
}
{
    "timestamp" : "3"
    "event": "event-c",
    "src ip": "10.0.0.3"
    "dst ip": "10.0.0.12"
    "direction": "outbound"
}
{
    "timestamp" : "4"
    "event": "event-D",
    "src ip": "10.0.0.4"
    "dst ip": "10.0.0.13"
    "direction": "inbound"
}
{
    "timestamp" : 5"
    "event": "event-E",
    "src ip": "10.0.0.5"
    "dst ip": "10.0.0.14"
    "direction": "outbound"
}
```

**correlation**
```
{
    "timestamp" : "1"
    "event": "event-A",
    "src ip": "10.0.0.1"
    "dst ip": "10.0.0.3"
    "direction": "inbound"
}
{
    "timestamp" : "3"
    "event": "event-c",
    "src ip": "10.0.0.3"
    "dst ip": "10.0.0.12"
    "direction": "outbound"
}
```

**Comment by chemamartinez** [comment]
Hi @jj4st13,

Is this issue duplicated from [this slack thread](https://wazuh.slack.com/archives/C0A933R8E/p1620623249041000)?

We would appreciate it if you use the Slack #community channel and the Google groups to post your use case questions, leaving this repository to report any product bugs or feature requests.

We will then be able to address these requests more efficiently.

Best regards.

**Comment by chemamartinez** [comment]
I am closing this issue.

@jj4st13 don't hesitate to contact us for further needs.

Best regards.
