### ISSUE TITLE
firewall (pFsense) logs don't appear

### ISSUE THREAD

**Issue by YNRA** [wazuh/wazuh#8598]
Hello there ! 

I'm working with Wazuh to retrieve logs from network devices, such as a pFsense. I ran into an issue that I can't manage to resolve, even with all the documentation and topics on the subject. 
I enabled rsyslog on the pFsense, and on the Wazuh server (which is a CentOS 8).

- If I run a tcpdump on port 514, I can see packets from the pFsense.
- If I tail /var/log/messages, and establish a connection on the Web GUI of pFsense, I can see it.

I tried everything that I had in mind. Plus, I can't see logs in /archives/archives/logs.

My conf in ossec.conf : 

```
<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
  <allowed-ips>192.168.25.126</allowed-ips> # WAN interface pFsense
  <allowed-ips>192.168.97.100</allowed-ips> # LAN interface pFsense
  <local_ip>192.168.25.100</local_ip> # Wazuh manager IP
</remote>
```

I also tried to had : 

```
<syslog_ouput>
    <server>192.168.25.100</server>
    <level>7</level>
   <format>json</format>
 </syslog_ouput>
```

and set `logall`to yes , and `log_alert_level`to 0.

What am I missing ? 

Regards,

EDIT : I succeed to get logs in the Wazuh manager, somehow, but I'm not really sure what was the root cause. I edited filebeat.yml, ossec.conf, and somes others lines

**Comment by YNRA** [comment]
And I also saw that pFsense went to a new file in `var/log/messages-$DATE', I can't figure out why, and how to send this file to Wazuh. Maybe with `<localfile>`? 

Regards,

**Comment by nmkoremblum** [comment]
Rsyslog is meant for sending messages from the device, not for receiving them. So, in your manager, you shouldn't configure rsyslog unless you want to send Syslog messages from the manager to another device. I would additionally remove the `syslog_output` block which is not a configuration for receiving logs but rather to send.

You will only receive alerts from messages that are decoded with the decoders and then matched to the rules that are configured in the following directories:
- /var/ossec/ruleset/decoders/
- /var/ossec/etc/decoders/
- /var/ossec/ruleset/rules/
- /var/ossec/etc/rules/

Custom decoders and rules are commonly configured in the `/var/ossec/ruleset/decoders/local_decoder.xml` and `/var/ossec/etc/rules/local_rules.xml` files, respectively.

To create custom decoders and rules, I would recommend you the following reading:
[Creating decoders and rules from scratch](https://wazuh.com/blog/creating-decoders-and-rules-from-scratch/)
[Custom rules and decoders](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html)

Regards,

Mariano Koremblum

**Comment by nmkoremblum** [comment]
Great to know Arnaud! We will be pleased to assist you whenever you need us, do not hesitate to reach out again through any of [our community channels](https://wazuh.com/community/).

I hope you have a good week,

Best regards,

Mariano
