### ISSUE TITLE
verify-agent-conf for ossec.conf

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh#86]
Hi,

it seems like verify-agent-conf can only verify the shared/agent.conf configuration, it would be useful if it could also verify ossec.conf on manager/agent.
If this will be implemented, please add the verify-agent-conf binary to the wazuh-agent packages.

**Comment by vikman90** [comment]
Hi @hex2a,

Both manager and agent are capable of verify the configuration running daemons with option `-t`, for instance:

> `/var/ossec/bin/ossec-syscheckd -t` (Syscheck/Rootcheck configuration)
> `/var/ossec/bin/logcollector -t` (Local files configuration)
> `/var/ossec/bin/wazuh-modulesd -t` (Wodles configuration)
> `/var/ossec/bin/ossec-analysisd -t` (Global/rules/decoders configuration) (manager only)
> `/var/ossec/bin/ossec-agentd -t` (Client configuration) (agent only)

All of them perform syntax parsing and each one verifies its own configuration.

The thing is that the agent reads the `ossec.conf` and the `agent.conf`, so it always tests both files, but the manager never parses the `agent.conf` (it only sends it to agents), this is why the utility `verify-agent-conf` exists at the manager.

Best regards.
