### ISSUE TITLE
Adapt CIS benchmark for macOS Big Sur

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#8617]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.x | SCA | Add new |

## Description
Develop an SCA policy adapting the CIS benchmark for macOS Big Sur.

### Reason
With the new release of macOS and the first time the major version number is incremented since 2000, Wazuh should provide an out-of-the-box policy to scan new macOS systems.

## Resources
This is the link to the latest CIS benchmark for macOS: https://www.cisecurity.org/benchmark/apple_os/

## Tests

- [ ] Added .ini test file for covering related rules
- [ ] Executed unit tests (runtests.py) for checking ruleset integrity
- [ ] Verified mitre.db integrity
- [ ] Verified compliance mapping 
- [ ] Verified no errors/warnings related in ossec.log
- [ ] Kibana shows alerts

**Comment by 72nomada** [comment]
update current [cis_apple_macOS_11.1.yml](https://github.com/wazuh/wazuh/blob/master/ruleset/sca/darwin/20/cis_apple_macOS_11.1.yml)  with latest [CIS Apple macOS 11.0 Benchmark v1.2.0](https://learn.cisecurity.org/l/799323/2021-05-18/47t24)
