### ISSUE TITLE
Investigate and test Office365 API

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8618]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all Office365 logs using its API.

The purpose of this issue is to investigate this API and make some testing in C languaje to retrieve logs from it.

Office365 API reference can be found [here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference).

Office365 API schema can be found [here](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema).

Information about how to configure Office365 can be found [here](https://wazuh.com/blog/monitor-office-365-with-wazuh/).

**Comment by Nicogp** [comment]
**Process to get logs**

1.  **Get auth token:**
    Method: POST
    Url: https://login.microsoftonline.com/{tenat_id}/oauth2/token
    Header: Content-Type: application/x-www-form-urlencoded
    Body: grant_type=client_credentials&client_id=”client_id”&client_secret=”client_secret”&resource=https://manage.office.com

    Response: 
    ```
    {
      "token_type": "Bearer",
      "expires_in": "3599",
      "ext_expires_in": "3599",
      "expires_on": "1621008173",
      "not_before": "1621004273",
      "resource": "https://manage.office.com",
      "access_token": "token"
    }
    ```

2.  **Subscribe to content:**

    content types are supported:
      - Audit.AzureActiveDirectory
      - Audit.Exchange
      - Audit.SharePoint
      - Audit.General (includes all other workloads not included in the previous content types)
      - DLP.All (DLP events only for all workloads)

    Method: POST
    Url: https://manage.office.com/api/v1.0/{tenat_id}/activity/feed/subscriptions/start?contentType=”content_type”
    Header: Authorization: bearer “token”

    Response:
    ```
     {
        "contentType": "Audit.General",
        "status": "enabled",
        "webhook": null
      }
    ```
    In case of error:
    Subscription is already enabled:
    ```
    {
     "error": {
        "code": "AF20024",
        "message": "The subscription is already enabled. No property change."
     }
    }
    ```
    Bad token:
    ```
    {
     "Message": "Authorization has been denied for this request."
    }
    ```
    Bad permission set:
    ```
     {
      "error": {
      "code": "AF10001",
      "message": "The permission set () sent in the request does not include the expected permission."
     }
    ```

3. **Get content list:**

   Method: GET
   Url: https://manage.office.com/api/v1.0/{client_id} /activity/feed/subscriptions/content?contentType=”content_type”&startTime=”start_time”&endTime=”end_time”
header: Authorization: bearer “token”
   Time format: “2021-05-12T22:19:12”
   Differences between start and end time: 24hs max
   Maximum start time to actual date: according to subscription plan. (7 days in our case)

   Response:
   ```
   [
    {
        "contentUri": "https://manage.office.com/api/v1.0/xxx/activity/feed/audit/20210513153326994000859$20210513195921183000959$audit_azureactivedirectory$Audit_AzureActiveDirectory$emea0010",
        "contentId": "xx$xx$audit_azureactivedirectory$Audit_AzureActiveDirectory$emea0010",
        "contentType": "Audit.AzureActiveDirectory",
        "contentCreated": "2021-05-13T19:59:21.183Z",
        "contentExpiration": "2021-05-27T15:33:26.994Z"
    },
    {
        "contentUri": "https://manage.office.com/api/v1.0/xxx/activity/feed/audit/xx$xx$audit_azureactivedirectory$Audit_AzureActiveDirectory$emea0010",
        "contentId": "xx$xx$audit_azureactivedirectory$Audit_AzureActiveDirectory$emea0010",
        "contentType": "Audit.AzureActiveDirectory",
        "contentCreated": "2021-05-13T20:18:19.201Z",
        "contentExpiration": "2021-05-27T20:02:19.296Z"
    }
   ]
   ```
   In case of error:
   ```
   {
    "error": {
        "code": "AF20055",
        "message": "Start time and end time must both be specified (or both omitted) and must be less than or equal to 24 hours apart, with the start time prior to  end time and start time no more than 7 days in the past. StartTime:2021-04-12T22:19:12, EndTime:2021-05-13T20:19:12"
    }
   }
   ```

4. **Get logs:**

   Method: GET
   Url: contentUri value extracted in previous step
   Header: Authorization: bearer “token”

   Response:
   ```
   [{"CreationTime":"2021-05-13T15:30:27","Id":"71ca9f9e-7e8c-4809-8a2d-be23d1e71400","Operation":"UserLoggedIn","OrganizationId":"xxxx","RecordType":15,"ResultStatus":"Success","UserKey":"xxxx","UserType":0,"Version":1,"Workload":"AzureActiveDirectory","ClientIP":"xx.xx.xx.x","ObjectId":"xx-xx-xx-xx-xx","UserId":"xx@xx.com","AzureActiveDirectoryEventType":1,"ExtendedProperties":[{"Name":"ResultStatusDetail","Value":"Success"},{"Name":"UserAgent","Value":"Mozilla\/5.0 (X11; Linux x86_64) xx\/537.36 (KHTML, like Gecko) Chrome\/89.0.4389.128 Safari\/537.36"},{"Name":"RequestType","Value":"OAuth2:Authorize"}],"ModifiedProperties":[],"Actor":[{"ID":"xx-xx-xx-xx-xx","Type":0},{"ID":"xx.xx@xx.com","Type":5}],"ActorContextId":"xx-xx-xx-xx-xx","ActorIpAddress":"xx.xx.xx.xx","InterSystemsId":"xx-x-xx-xx-xx","IntraSystemId":"xx-xx-xx-xx-xx","SupportTicketId":"","Target":[{"ID":"xx-xx-xx-xx-xx","Type":0}],"TargetContextId":"xx-xx-xx-xx-xx","ApplicationId":"xx-xx-xx-xx-xx","DeviceProperties":[{"Name":"BrowserType","Value":"Chrome"},{"Name":"IsCompliantAndManaged","Value":"False"},{"Name":"SessionId","Value":"xx-xx-xx-xx-xx"}],"ErrorNumber":"0"},{"CreationTime":"…….."}]
   ```
