### ISSUE TITLE
Analyze and classify Office365 logs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8619]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all Office365 logs using its API.

The purpose of this issue is to analyze all the logs that this API endpoint retrieves and classify them, so later this classification can be used to create rules.

Office365 logs description can be found [here](https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log?view=o365-worldwide).

**Comment by cborla** [comment]
Office 365 Activity API schema

[](https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema)
- AzureActiveDirectory
- Exchange
> - Exchange Admin
> - Exchange Maibox
- SharePoint
> - SharePoint Base
> - SharePoint File Operations
> - SharePoint Sharing
- General
- DLP.All

Detailed properties in the audit log
[](https://docs.microsoft.com/en-us/microsoft-365/compliance/detailed-properties-in-the-office-365-audit-log?view=o365-worldwide)

**Comment by cborla** [comment]
Sample logs
[sampleLogs.log](https://github.com/wazuh/wazuh/files/6518332/sampleLogs.log)

**Comment by cborla** [comment]
Sample Rule structure






<group name="office_365,">

	<group name="office_365,">
	  <rule id="92000" level="3">
	  <location>office_365</location>
	  <description>Office 365 $(office_365.Workload) $(office_365.Operation) operation.</description>
	  <options>no_full_log</options>
	  </rule>
	</group>

    
    
    
    <rule id="92001" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^AzureActiveDirectory$</field>
        <description>Office 365 AzureActiveDirectory.</description>
        <options>no_full_log</options>
        <group>AzureActiveDirectory</group>
    </rule>

	
    <rule id="92002" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^Exchange$</field>
        <description>Office 365 Exchange.</description>
        <options>no_full_log</options>
        <group>Exchange</group>
    </rule>

    <rule id="92003" level="3">
        <if_sid>92002</if_sid>
        <field name="office_365.Operation">^Admin$</field>
        <description>Office 365 Exchange Admin.</description>
        <options>no_full_log</options>
        <group>Exchange</group>
    </rule>

    <rule id="92004" level="3">
        <if_sid>92002</if_sid>
        <field name="office_365.Operation">^Maibox$</field>
        <description>Office 365 Exchange Maibox.</description>
        <options>no_full_log</options>
        <group>Exchange</group>
    </rule>

	
    <rule id="92005" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^SharePoint$</field>
        <description>Office 365 SharePoint.</description>
        <options>no_full_log</options>
        <group>SharePoint</group>
    </rule>

    <rule id="92006" level="3">
        <if_sid>92005</if_sid>
        <field name="office_365.Operation">^Base$</field>
        <description>Office 365 SharePoint Base.</description>
        <options>no_full_log</options>
        <group>SharePoint</group>
    </rule>

    <rule id="92007" level="3">
        <if_sid>92005</if_sid>
        <field name="office_365.Operation">^File Operations$</field>
        <description>Office 365 SharePoint File Operations.</description>
        <options>no_full_log</options>
        <group>SharePoint</group>
    </rule>

    <rule id="92008" level="3">
        <if_sid>92005</if_sid>
        <field name="office_365.Operation">^Sharing$</field>
        <description>Office 365 SharePoint Sharing.</description>
        <options>no_full_log</options>
        <group>SharePoint</group>
    </rule>


	
    <rule id="92009" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^General$</field>
        <description>Office 365 General.</description>
        <options>no_full_log</options>
        <group>General</group>
    </rule>

	
    <rule id="92010" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^DLP.ALL$</field>
        <description>Office 365 DLP.</description>
        <options>no_full_log</options>
        <group>DLP</group>
    </rule>

	
    <rule id="92011" level="3">
        <if_sid>92000</if_sid>
        <field name="office_365.Workload">^OneDrive$</field>
        <description>Office 365 OneDrive.</description>
        <options>no_full_log</options>
        <group>OneDrive</group>
    </rule>


    


</group>

**Comment by cborla** [comment]
Sample Alerts
[sampleAlerts.txt](https://github.com/wazuh/wazuh/files/6518336/sampleAlerts.txt)

**Comment by cborla** [comment]
More sample logs
[office365-logs.txt](https://github.com/wazuh/wazuh/files/6518478/office365-logs.txt)
