### ISSUE TITLE
Slow agent-group files creation

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8625]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0 | Wazuh-remoted | Manager | All | Tested in Ubuntu 20.04.2 LTS |

## Description

Hello team!

This question/problem arises after the tests in large environments that we are doing in #8439, specifically in https://github.com/wazuh/wazuh/issues/8439#issuecomment-836673950.

It turns out that in an environment with 50K agents and 10 workers, where each worker has around 5000 connected agents, we find the following behavior: 
![imagen](https://user-images.githubusercontent.com/23361101/117936893-ac307f80-b305-11eb-8514-98899f06ff26.png)

As we can see in the graph, 5000 agents connect to the worker in a span of about 6.5 minutes (13:16:30 - 13:23:00). By minute 13:23:00, no new agents are connecting (as expected). However, if we look at the worker1 `cluster.log` file, we see that file synchronization takes place for almost 9 more minutes after the last agent is connected:
```
2021/05/10 13:23:04 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 133 | Files to update: 1 | Files to delete: 0 | Files to send: 162
...
2021/05/10 13:27:24 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 160 | Files to update: 0 | Files to delete: 0 | Files to send: 351
...
2021/05/10 13:29:26 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 2247 | Files to update: 0 | Files to delete: 0 | Files to send: 293
...
2021/05/10 13:32:02 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 319 | Files to update: 0 | Files to delete: 0 | Files to send: 302
```

We can see that during all these posts, the worker is still sending files to the master. We need to have a few things in mind to interpret this: 
- The only files that a worker sends to a master are the `/var/ossec/queue/agent-groups`. 
- Files are sent at every integrity sync, which happens every 10-30 seconds. 
- At each synchronization, all new or changed files are sent, regardless of how many there are. 
- The agent-group files are created by `wazuh-remoted` when an agent first connects to a node. 

If all new files are sent when a integrity sync takes place, and if the worker is sending files for 9 minutes after the last agent was connected, it means Wazuh is taking 9 minutes to create all agent-groups files after agents were connected. 

Although it is true that it is not a common use case to connect such a large number of agents at the same time, is this behavior expected? Is it normal for files to be created at this rate? 

Regards,
Selu.

**Comment by davidjiglesias** [comment]
Might be fixed by https://github.com/wazuh/wazuh/issues/8974, we need to relaunch the test and confirm the results.

**Comment by yanazaeva** [comment]
## Issue update

As explained above, the `extra_valid` files are the ones that have to be created in the master, instead of being created in the worker. Currently, we have only one type of file that belong to this group: the agent-group one. 

If we check the log above we can see four different `Integrity sync` iterations: 
```
2021/05/10 13:23:04 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 133 | Files to update: 1 | Files to delete: 0 | Files to send: 162
...
2021/05/10 13:27:24 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 160 | Files to update: 0 | Files to delete: 0 | Files to send: 351
...
2021/05/10 13:29:26 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 2247 | Files to update: 0 | Files to delete: 0 | Files to send: 293
...
2021/05/10 13:32:02 INFO: [Worker Test_cluster_performance_B227_manager_1] [Integrity sync] Files to create: 319 | Files to update: 0 | Files to delete: 0 | Files to send: 302
```
When this issue was opened, it was thought that each iteration was unique, meaning that no repeated files were sent between two iterations. However, later it was discovered that if some agent-group files could not be created within the first iteration, this agent-group was going to be present in the following iterations, until its creation. In a nutshell, seeing these logs does not mean that it took so much time, but 

After this, checking how some agent-group files were not created in the master node, or created after a while, we realized that this was due to the long time that it takes for an agent to be added to the `wazuh-modulesd:database`. This time is an average of 4 minutes. We can see that in the logs displayed below: 

- Agent registration and later addition to the database:
```
2021/11/17 15:57:36 wazuh-authd: INFO: Received request for a new agent (1-u1mzJ3yfokiKRAqt-debian10) from: 172.31.59.231
2021/11/17 15:57:36 wazuh-authd: INFO: Agent key generated for '1-u1mzJ3yfokiKRAqt-debian10' (requested by any)
2021/11/17 16:02:09 wazuh-modulesd:database[21769] wm_database.c:279 at wm_sync_agents(): DEBUG: Synchronizing agent 49336 '1-u1mzJ3yfokiKRAqt-debian10'.
2021/11/17 16:02:09 wazuh-modulesd[21769] agent_op.c:286 at get_agent_group(): DEBUG: At get_agent_group(): file 'queue/agent-groups/49336' not found.
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:781 at wm_inotify_start(): DEBUG: inotify: i='0', name='.49336.tmp', mask='128', wd='2'
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:781 at wm_inotify_start(): DEBUG: inotify: i='0', name='49336', mask='128', wd='2'
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:849 at wm_inotify_push(): DEBUG: Adding 'queue/agent-groups/49336' to path table.
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:880 at wm_inotify_pop(): DEBUG: Taking 'queue/agent-groups/49336' from path table.
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:530 at wm_sync_file(): DEBUG: Synchronizing file 'queue/agent-groups/49336'
2021/11/17 16:02:23 wazuh-modulesd:database[21769] wm_database.c:473 at wm_sync_agent_group(): DEBUG: wm_sync_agent_group(49336): 0.094 ms.
``` 

- We can see that the worker tried to send the agent-group file corresponding to that agent a couple of times, but this agent was not registered yet:
```
2021/11/17 15:58:39 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 15:58:55 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 15:59:12 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 15:59:36 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:00:02 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:00:29 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:00:42 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:00:56 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:01:14 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:01:30 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:01:46 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
2021/11/17 16:02:02 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group of an non-existent agent '49336'
``` 

- Once the agent is present in the database, we finally receive this log:
```
2021/11/17 16:02:23 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B104_manager_6] [Main] Received group from agent '49336'
```

**Comment by AdriiiPRodri** [comment]
The agent-groups are going to be deprecated in #10771, we should re-evaluate the performance after all changes are introduced in that Epic issue.
