### ISSUE TITLE
Monitoring log deletion

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#8626]
Hi, 

I am wondering if Wazuh can monitor log deletion.
I did not find answer in the documentation or in google.
I deleted 'auth.log' and 'audit.log' on my host where Wazuh agent is deployed, but nothing was reported.
Could anyone guide me how to solve it?

Best regards

**Comment by JoseAntonioMHerrera** [comment]
Hi rejszynski! Currently, detecting this kind of deleted events cannot be made through logcollector. Right now, the easy way to monitor this is to use syscheck. In your agent machine you can monitor the file deletion using syscheck adding the following line to the syscheck stanza in the ossec.conf file (in this example we'll be monitoring **/var/log/auth.log**):

```
<directories check_all="no">/var/log/auth.log</directories>
```
To avoid wasting agent resources, check_all="no" will ignore modification events, and with no realtime or whodata tags you'll also reduce the resource impact over FIM in this specific case of monitoring the deleted event. There is some drawbacks to this, as it will not generate the deleted events for /var/log/auth.log till the scan is executed again (frequency tag under syscheck holds the time value for this). I hope you find this information useful!

**Comment by rejszynski** [comment]
Hi JoseAntonioMHerra :) 
Thank you for a quick answer. I will give it a try.
Speaking of FIM, I have another issue to ask about - I added <ignore> to my manager configuration for certain directories, but they are still appearing in logs though. 
Should I make another topic about it?

**Comment by JoseAntonioMHerrera** [comment]
Hi! I'm sorry, What do you mean with manager configuration for certain directories? If you could post here the configuration file, it would be helpful. Also, the logs you're talking about are the ones in ossec.log? If not, in which logs are they appearing?

**Comment by rejszynski** [comment]
Sorry, I have mispelled my previous post. I added <ignore> directive to my manager configuration to ignore certain directories on agents. I did the same in central agent configuration and it still did not work. 

Manager:

`  
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <ignore>/etc/zabbix/scripts</ignore>
    <ignore>/etc/dirsrv</ignore>
    <ignore>/etc/prometheus/file_sd/</ignore>
    <ignore>/var/lib/docker/overlay2/</ignore>
    <ignore>/etc/ganesha/export.d/share/</ignore>
`
Central agent config:

```
<syscheck>
     <directories check_all="no" whodata="yes" recursion_level=2>/etc,/usr/bin,/usr/sbin</directories>
     <directories check_all="no" whodata="yes" recursion_level=2>/bin,/sbin,/boot</directories>
     <ignore>/etc/zabbix</ignore>
     <ignore>/etc/dirsrv</ignore>
     <ignore>/var/lib/docker/overlay2/</ignore>
     <ignore>/etc/prometheus/file_sd/</ignore>
  </syscheck>
```
There are still logs from this locations in my elasticsearch index.

**Comment by JoseAntonioMHerrera** [comment]
Could you please post here too a screenshot or a copy-paste of those logs you think shouldn't be appearing?

**Comment by rejszynski** [comment]
Yes, for example logs from `/var/lib/docker/overlay2/` which should be ignored:

```File '/var/lib/docker/overlay2/86123eec722d7799c908119fcffe7e54d6fa1a4ad8cff20e158ac743c929ed2e/diff/var/lib/kolla/venv/lib/python2.7/site-packages/ceilometer/locale/de/LC_MESSAGES/ceilometer-log-warning.po' is owned by root and has written permissions to anyone.```

```File '/var/lib/docker/overlay2/86123eec722d7799c908119fcffe7e54d6fa1a4ad8cff20e158ac743c929ed2e/diff/var/lib/kolla/venv/lib/python2.7/site-packages/ceilometer/locale/ja/LC_MESSAGES/ceilometer.po' is owned by root and has written permissions to anyone.```

**Comment by JoseAntonioMHerrera** [comment]
Hi! Those logs are coming from rootcheck module. You need either to disable rootcheck for files (<check_files>no</check_files>) or add the same <ignore> entries that you have in syscheck in rootcheck too, to avoid logs coming from rootcheck monitoring those files. Also, you could disable rootcheck as a whole if that option doesn't seem interesting to you. I hope you find this information useful!

**Comment by rejszynski** [comment]
> Hi rejszynski! Currently, detecting this kind of deleted events cannot be made through logcollector. Right now, the easy way to monitor this is to use syscheck. In your agent machine you can monitor the file deletion using syscheck adding the following line to the syscheck stanza in the ossec.conf file (in this example we'll be monitoring **/var/log/auth.log**):
> 
> ```
> <directories check_all="no">/var/log/auth.log</directories>
> ```
> 
> To avoid wasting agent resources, check_all="no" will ignore modification events, and with no realtime or whodata tags you'll also reduce the resource impact over FIM in this specific case of monitoring the deleted event. There is some drawbacks to this, as it will not generate the deleted events for /var/log/auth.log till the scan is executed again (frequency tag under syscheck holds the time value for this). I hope you find this information useful!

Hello,

I did what you said, but it does not work for me.
Snippet from my config file:
```<!-- Directories to check  (perform all possible verifications) -->
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
    <directories check_all="no">/var/log/auth.log</directories>
```
After deleting auth.log file, no event has been shipped to my Elasticsearch.
Agent is properly connected and send other logs fine.
Any sugestions?

**Comment by JoseAntonioMHerrera** [comment]
Hi! Remember that the event will be sent after the time you have set in frequency have elapsed. Can you create the file again, set <frequency> tag under <sycheck> to 5 and then restart the manager? After the manager has properly restarted, you can delete the file and it should appear a delete event in /var/ossec/logs/alerts/alert.log. Let's try this first to ensure the event is being sent.

**Comment by rejszynski** [comment]
Still nothing. I changed frequency in manager configuration, agent configuration and shared configuration. 
There is no event about log deletion.

**Comment by JoseAntonioMHerrera** [comment]
Hi again! That seems weird. First, if I recall correctly, the auth.log file you wanted to monitorize for deletion was in your agent machine right? Unless you also want to monitor that event in your manager, you don't have to change the manager configuration. Now, could you please post here the output of the following commands? (please, execute them in that specific order):

Commands to execute in your manager:

 1. grep "auth.log" from /var/ossec/logs/ossec.log 
 2. grep "auth.log" /var/ossec/logs/alerts/alerts.log

Commands to execute in the specific agent from where you want to receive the deleted auth.log event: 

 3. If you can restart the agent without further problems, please execute the following command: **/var/ossec/bin/./wazuh-control restart**. Before doing this, please ensure that in your shared agent configuration or in your specific ossec.conf for that agent (**/var/ossec/etc/ossec.conf**) you have the following line added inside the syscheck module: 
```
<directories check_all="no">/var/log/auth.log</directories>
```
 4. grep "auth.log" /var/ossec/logs/ossec.log
 
One last question, are you having problems with the generation of any other alerts? Thank you in advance for your cooperation.

**Comment by rejszynski** [comment]
Hi Jose, 
Sorry for late response.
Greping auth.log in a way you said is a bit pointless, cause I have tons of logs from auth.log from hundreds of agents.
I tried to combine auditd with Wazuh, but it did not also do the trick.
Furthermore I still can not turn off FIM from certain directories even though I have disabled it in central agent configuration...

`<syscheck>
     <disabled>yes</disabled>
     <directories whodata="yes" recursion_level=2>/etc,/usr/bin,/usr/sbin</directories>
     <directories whodata="yes" recursion_level=2>/bin,/sbin,/boot</directories>
     <directories check_all="no">/var/log/auth.log</directories>
     <ignore>/etc/zabbix</ignore>
     <ignore>/etc/dirsrv</ignore>
     <ignore>/etc/prometheus/file_sd/</ignore>
  </syscheck>
`

Example log:

`
550 | 7 | Integrity checksum changed. | File '/etc/zabbix/scripts/nvme1n1' modified Mode: realtime Changed attributes: mtime,md5,sha1,sha256 Old modification time was: '1622097301', now it is '1622097601' Old md5sum was: '5fe2b4345e51bb6e723a3c2dbaabb12a' New md5sum is : '3234aec7b86c67e890968522556a88ef' Old sha1sum was: '9e3cf559c1a690c747b290f74b744cb2287fe021'
-- | -- | -- | --
`
The problem is it floods important logs with this garbage about checksum from files that change every second.
What is the problem here ?

**Comment by JoseAntonioMHerrera** [comment]
Hi again rejszynski! I have tried using your conf but it seems to have a syntax error. Try adding "" to the numbers you're assigning to recursion_level. It should look like this: 
```
 <directories whodata="yes" recursion_level="2">/bin,/sbin,/boot</directories>
 <directories whodata="yes" recursion_level="2">/etc,/usr/bin,/usr/sbin</directories>
```
After that, execute this command to verify that the shared configuration doesn't have any errors:
```
/var/ossec/bin/verify-agent-conf

```
If everything is correct, it should output the following message:

```
verify-agent-conf: Verifying [etc/shared/default/agent.conf]
verify-agent-conf: OK
```

After that, if you're agents are synced, they should restart after 10 seconds (this is the default value) with the shared configuration enabled. Tell me if this fix your problem!

**Comment by rejszynski** [comment]
Thank you for a quick response Jose.
You were right, there was syntax error, because of lack of double quotes in recursion_level.
Now the configuration is ok.
I will give a shot now with deleting 'auth.log' and let you know what is the result.
I appreciate your help.

**Comment by rejszynski** [comment]
Update:

Still no info about auth.log deletion.
Current shared config:

```
<agent_config>

  <sca>
    <enabled>no</enabled>
    <scan_on_start>no</scan_on_start>
    <interval>12h</interval>
    <skip_nfs>yes</skip_nfs>
  </sca>
  <syscheck>
     <directories whodata="yes" recursion_level="2">/etc,/usr/bin,/usr/sbin</directories>
     <directories whodata="yes" recursion_level="2">/bin,/sbin,/boot</directories>
     <directories check_all="no">/var/log/auth.log</directories>
     <ignore>/etc/zabbix</ignore>
     <ignore>/etc/dirsrv</ignore>
     <ignore>/etc/prometheus/file_sd/</ignore>
     <ignore>/var/lib/docker/</ignore>
     <ignore>/etc/ganesha/export.d/share/</ignore>

  </syscheck>

  <rootcheck>
    <disabled>yes</disabled>
  </rootcheck>

</agent_config>
```
Last log from alerts.json:

```
{"timestamp":"2021-05-27T12:32:23.675+0200","rule":{"level":3,"description":"New ossec agent connected.","id":"501","firedtimes":1,"mail":true,"groups":["ossec"],"pci_dss":["10.6.1"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6"],"tsc":["CC7.2","CC7.3"]},"agent":{"id":"1033","name":"rej-testy"},"manager":{"name":"els01"},"id":"1622111543.294472238","cluster":{"name":"wazuh-cf","node":"els01"},"full_log":"ossec: Agent started: 'rej-testy->any'.","decoder":{"parent":"ossec","name":"ossec"},"data":{"extra_data":"rej-testy->any"},"location":"ossec"}
[root@els01 535]# grep rej-testy /var/ossec/logs/alerts/alerts.json
{"timestamp":"2021-05-27T12:32:23.675+0200","rule":{"level":3,"description":"New ossec agent connected.","id":"501","firedtimes":1,"mail":true,"groups":["ossec"],"pci_dss":["10.6.1"],"gpg13":["10.1"],"gdpr":["IV_35.7.d"],"hipaa":["164.312.b"],"nist_800_53":["AU.6"],"tsc":["CC7.2","CC7.3"]},"agent":{"id":"1033","name":"rej-testy"},"manager":{"name":"els01"},"id":"1622111543.294472238","cluster":{"name":"wazuh-cf","node":"els01"},"full_log":"ossec: Agent started: 'rej-testy->any'.","decoder":{"parent":"ossec","name":"ossec"},"data":{"extra_data":"rej-testy->any"},"location":"ossec"}
```

**Comment by JoseAntonioMHerrera** [comment]
Check the following stanza under syscheck in any of your agents' ossec.conf where that deletion event should be triggered. I do not mean the shared configuration, but the specific ossec.conf of one specific agent. Check the existence of the following line in that specific ossec.conf agent where you're deleting the auth.log file: 

```
<ignore type="sregex">.log$| {another extensions to ignore} </ignore>
```

If you have it, then syscheck is ignoring any file with .log extension. This is set to prevent an overflow of alerts from log files which are constantly changing. Also, to ensure this is your issue, add the following line to /var/ossec/etc/local_internal_options.conf:

```
syscheck.debug=2
```
Then restart the agent. After a few seconds, execute this command:

```
grep "Ignoring 'file' '/var/log/auth.log'" /var/ossec/logs/ossec.log
```

Bear in mind that using an shared configuration do not overwrite entirely the agent configuration, but adds those shared options to the current configuration of the agent.

**Comment by JoseAntonioMHerrera** [comment]
Hi again, sadly Wazuh doesn't provide that kind of functionality. As I mentioned earlier, the shared configuration not always  replaces the options in the agent with the ones in the shared conf but mixes with them. Right now I think the easiest way to achieve this of would be use some command like scp to push one ossec.conf file to all the agents. Check the following link to see how to use it: [scp](https://linuxize.com/post/how-to-use-scp-command-to-securely-transfer-files/). Building a script that reads all the ips from a file and then push the ossec.conf file to /var/ossec/etc/ path in the agent machine. I'm sorry I can't shed more light on this, if you have any other question related to this I'll be glad to help you. Have a  nice day!

**Comment by rejszynski** [comment]
That's a pitty there's no other solution for that, but I get it.
Anyway thank you for your help and your support.
I am closing this issue.
