### ISSUE TITLE
Duplicate configuration  error in 'Syscheck'

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#867]
When two identical directories are configured with different settings:
 ```
<directories check_all="yes" realtime="yes">/root/test</directories>>
<directories check_all="yes">/root/test</directories>>
```

The following error is displayed:
`ERROR: (1756): Duplicated directory given:  '/root/test'`

The prevailing configuration is the first one, which leads to an error when this directory duplication comes from agent.conf, which should prevail over ossec.conf.

**Comment by vikman90** [comment]
Hi @bah07,

You are completely right: if the agent finds a duplicate configuration, the second one should always apply.

In this case, let me add another point: a `<directories>` item should be considered duplicate if both content and `restrict` option match. This will allow selecting options for different files in the same directory.

Thanks!

**Comment by bah07** [comment]
Hi @vikman90 , I'm not quite sure about the second point. In that case, it would be impossible to reconfigure a directory remotely, which could cause some problems if you don't have access to the agent. I think it should be given the possibility to reconfigure it completely.

What do you think?
Regards.

**Comment by bah07** [comment]
Done #1740
